### ISSUE TITLE
Is there any way to set the number of parallels for salt-cloud?

### ISSUE THREAD

**Issue by citaret** [saltstack/salt#45139]
Hi,

salt-cloud support parallel creation of instances by option (-P).

However, in my experience, when the number of parallel is larger than a certain number, such as 30 for Linode, there will be some error that make some instances created with mistake. Switch off the parallel would make the creation time much longer for hundreds of instances.

Is there any way to set the number of parallels for salt-cloud? So that the salt-cloud would continue after the current parallel creation procedure.

Thanks.

**Comment by garethgreenaway** [comment]
@citaret Thanks for the report.  The option you want is the configuration item `pool_size`, https://docs.saltstack.com/en/latest/topics/cloud/config.html#thread-pool-size

**Comment by citaret** [comment]
@garethgreenaway Thanks, it solved my problem.

**Comment by garethgreenaway** [comment]
@citaret Awesome!  If you consider the issue resolve please feel free to close it.  Thanks!
