### ISSUE TITLE
file.recurse   [Errno 13] Permission denied

### ISSUE THREAD

**Issue by qiangshui** [saltstack/salt#45140]
I using file.recurse to transfer a directory to a minion, most of the files in the directory are .dll files. Somtimes there is no problem,but sometimes, the names of some files may be change, and It caused my IIS service to be wrong. 

Here is my .sls file
```
D:\EZP.WeiXin.Service.Host:
  file.recurse:
    - source: salt://release/EZP.WeiXin/{{pillar["version"]}}
    - mkdirs: True
    - include_empty: True
```

### Steps to Reproduce Issue
Sometimes, when I transfer those files first time, this problem will arise, 
this is the error commant:
`Failed to commit change: [Errno 13] Permission denied: u'F:/publish/EZP.WeiXin.Service.Host\\bin\\EZP.WeiXin.Service.Host.dll'`, 
and Execution results show failure.
but when I transfer them again without any change, the problem above was gone，and execution results show successful. In spite of this, some of the names of some files have been changed very strangely.Like this:
![default](https://user-images.githubusercontent.com/24819310/34295072-55eaadd2-e746-11e7-9105-a30f58b12e88.png),it should have been "EZP.WeiXin.Service.Host.dll".
This happens more than once, and it's on different clients, different files. These minions's systems are all Winserver 2008 R2. 

### Versions Report
```
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.11.25.el6.ucloud.x86_64
         system: Linux
        version: CentOS 6.5 Final

```

**Comment by garethgreenaway** [comment]
@qiangshui Thanks for the report.  @twangboy Thoughts on this one?

**Comment by twangboy** [comment]
Maybe the file is in use when the state runs?

**Comment by garethgreenaway** [comment]
If it's modifying DLL files this seems likely and possible.

**Comment by qiangshui** [comment]
@garethgreenaway @twangboy ,Thanks for the reply. Yes, the file is in use when the state runs. But if the cover operation is done manually, there will be no problem. So the problem seems to be on the saltstack.Is there any solution to it？
