### ISSUE TITLE
shadow.lock_password

### ISSUE THREAD

**Issue by woodhead99** [saltstack/salt#45141]
### shadow.lock_password after shadow.del_password causes an error.
If the password field is null we get an IndexError: string index out of range:

`
The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1468, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/shadow.py", line 222, in lock_password
        if pre_info['passwd'][0] == '!':
    IndexError: string index out of range
`

### Setup
salt version 2017.7.1

### Steps to Reproduce Issue
salt 'minion' shadow.del_password <username>
salt 'minion' shadow.lock_password <username>

I see in the code we check to see if the password is already locked:
/usr/lib/python2.7/site-packages/salt/modules/shadow.py: line 222
`if pre_info['passwd'][0] == '!':`
If we change this to:
`if pre_info['passwd'].startswith('!'):`
It should work just fine.  It works for me anyway.

### Versions Report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2017, 11:05:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.4 Nitrogen
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: Scientific Linux 7.4 Nitrogen

**Comment by garethgreenaway** [comment]
@woodhead99 Thanks for the report.  Would you mind submitting a pull request with this fix?  Thanks!
