### ISSUE TITLE
nginx isn't up and running though the top file execution was successful and MASTER/MINION communication is slow (i have setup minion on vagrant) 

### ISSUE THREAD

**Issue by ykm-2012** [saltstack/salt#45159]
### Description of Issue/Question
i have set up saltstack on my Mac OS. master is on mac machine and minion1 on vagrant (ubuntu/trusty64 ). i have followed the below documentation.
https://docs.saltstack.com/en/latest/topics/tutorials/walkthrough_macosx.html
everythings good nginx package is installed and successful. But the nginx navigation page do not load on http://192.168.33.10/ .
i just see the error page.
### Setup
evrything as per saltstack documentation https://docs.saltstack.com/en/latest/topics/tutorials/walkthrough_macosx.html

### Steps to Reproduce Issue
sls file execution logs 

[DEBUG   ] Sending event: tag = salt/job/20171224180909974004/ret/minion1; data = {'fun_args': [], 'jid': '20171224180909974004', 'return': {'pkg_|-nginx_|-nginx_|-installed': {'comment': 'All specified packages are already installed', 'name': 'nginx', 'start_time': '00:09:10.717731', 'result': True, 'duration': 303.752, '__run_num__': 0, '__sls__': 'bin.nginx', 'changes': {}, '__id__': 'nginx'}, 'service_|-nginx_|-nginx_|-running': {'comment': 'The service nginx is already running', 'name': 'nginx', 'start_time': '00:09:11.022010', 'result': True, 'duration': 27.112, '__run_num__': 1, '__sls__': 'bin.nginx', 'changes': {}, '__id__': 'nginx'}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2017-12-25T00:09:11.055884', 'fun': 'state.apply', 'id': 'minion1', 'out': 'highstate'}
[TRACE   ] Master function call _return took 0.00152993202209 seconds

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.10 (default, Feb  7 2017, 00:08:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 16.7.0
         system: Darwin
        version: 10.12.6 x86_64

**Comment by garethgreenaway** [comment]
@ykm-2012 thanks for the report.  Can you provide the output you see after running the state.apply command?

**Comment by ykm-2012** [comment]
**here is the output after execution. i guess the vagrant IP is not exposed, because of which i see the error page in my browser.**

minion1:
----------
          ID: nginx
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 03:26:18.554056
    Duration: 334.998 ms
     Changes:   
----------
          ID: nginx
    Function: service.running
      Result: True
     Comment: The service nginx is already running
     Started: 03:26:18.889829
    Duration: 32.378 ms
     Changes:   

Summary for minion1
------------
Succeeded: 2
Failed:    0
------------
Total states run:     2
Total run time: 367.376 ms

**Nginx is running in my box and i have enabled the firewall setup for both the applications   Nginx HTTP and Nginx HTTPS. below are the details**

vagrant@vagrant-ubuntu-trusty-64:/etc/nginx/sites-enabled$ sudo ufw status verbose
Status: active
Logging: on (low)
Default: deny (incoming), allow (outgoing), disabled (routed)
New profiles: skip

To                         Action      From
--                         ------      ----
80                         ALLOW IN    Anywhere
443                        ALLOW IN    Anywhere
80 (v6)                    ALLOW IN    Anywhere (v6)
443 (v6)                   ALLOW IN    Anywhere (v6)

**Comment by ykm-2012** [comment]
i think after enabling the firewall setup it works. i have restarted the box and i could see the IP running successfully with Nginx welcome page. 
you can close the ticket. 
Thankyou @garethgreenaway

**Comment by garethgreenaway** [comment]
@ykm-2012 awesome. Glad you got it working. Thanks!
