### ISSUE TITLE
Missing repo for AMZN Linux 2 (2017.12)

### ISSUE THREAD

**Issue by maschinetheist** [saltstack/salt#45154]
### Description of Issue/Question
Seems like there is a missing repo for Salt packages for Amazon Linux 2 (2017.12)

### Setup
Just a standard EC2 instance with Amazon Linux 2 provisioned: amzn2-ami-hvm-2017.12.0.20171212.2-x86_64-gp2 (ami-7707a10f)

### Steps to Reproduce Issue
Install the Salt Amazon repo file:
```bash
# yum install https://repo.saltstack.com/yum/amazon/salt-amzn-repo-latest-2.amzn1.noarch.rpm -y
Loaded plugins: langpacks, update-motd
salt-amzn-repo-latest-2.amzn1.noarch.rpm                                                                                    | 4.0 kB  00:00:00
Examining /var/tmp/yum-root-Xrqlcj/salt-amzn-repo-latest-2.amzn1.noarch.rpm: salt-amzn-repo-latest-2.amzn1.noarch
Marking /var/tmp/yum-root-Xrqlcj/salt-amzn-repo-latest-2.amzn1.noarch.rpm to be installed
Resolving Dependencies
--> Running transaction check
---> Package salt-amzn-repo.noarch 0:latest-2.amzn1 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===================================================================================================================================================
 Package                        Arch                   Version                         Repository                                             Size ===================================================================================================================================================Installing:
 salt-amzn-repo                 noarch                 latest-2.amzn1                  /salt-amzn-repo-latest-2.amzn1.noarch                 2.0 k

Transaction Summary
===================================================================================================================================================
Install  1 Package

Total size: 2.0 k
Installed size: 2.0 k
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : salt-amzn-repo-latest-2.amzn1.noarch                                                                                            1/1
  Verifying  : salt-amzn-repo-latest-2.amzn1.noarch                                                                                            1/1

Installed:
  salt-amzn-repo.noarch 0:latest-2.amzn1

Complete!
```

Install salt-minion:
```bash
# yum install salt-minion
Loaded plugins: langpacks, update-motd
https://repo.saltstack.com/yum/amazon/2017.12/x86_64/latest/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
Trying other mirror.


 One of the configured repositories failed (SaltStack Latest Release Channel for native Amazon Linux),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=salt-amzn-latest ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable salt-amzn-latest
        or
            subscription-manager repos --disable=salt-amzn-latest

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=salt-amzn-latest.skip_if_unavailable=true

failure: repodata/repomd.xml from salt-amzn-latest: [Errno 256] No more mirrors to try.
https://repo.saltstack.com/yum/amazon/2017.12/x86_64/latest/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
```

Hardcoding an older `$releasever` in the `repo` file does not appear to work either:
```bash
# grep "baseurl" /etc/yum.repos.d/salt-amzn-latest.repo
baseurl=https://repo.saltstack.com/yum/amazon/2017.09/$basearch/latest
```
```bash
# yum install -y salt-minion
Loaded plugins: langpacks, update-motd
epel/x86_64/metalink                                                                                                        |  15 kB  00:00:00
epel                                                                                                                        | 4.7 kB  00:00:00
(1/3): epel/x86_64/group_gz                                                                                                 | 266 kB  00:00:00
(2/3): epel/x86_64/updateinfo                                                                                               | 862 kB  00:00:01
(3/3): epel/x86_64/primary_db                                                                                               | 6.1 MB  00:00:13
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:2017.7.2-1.amzn1 will be installed
--> Processing Dependency: salt = 2017.7.2-1.amzn1 for package: salt-minion-2017.7.2-1.amzn1.noarch
--> Running transaction check
---> Package salt.noarch 0:2017.7.2-1.amzn1 will be installed
--> Processing Dependency: python27-msgpack > 0.3 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-futures >= 2.0 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-crypto >= 2.6.1 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-zmq for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-six for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-psutil for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-markupsafe for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-jinja2 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-PyYAML for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27(dist-packages) for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27 for package: salt-2017.7.2-1.amzn1.noarch
--> Running transaction check
---> Package python27-msgpack.x86_64 0:0.4.6-2.amzn1 will be installed
---> Package python27-psutil.x86_64 0:5.2.2-2.ius.amzn1 will be installed
---> Package python27-tornado.x86_64 0:4.2.1-2.amzn1 will be installed
--> Processing Dependency: python27(dist-packages) for package: python27-tornado-4.2.1-2.amzn1.x86_64
---> Package python27-zmq.x86_64 0:14.5.0-3.amzn1 will be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-3.amzn1.x86_64
---> Package salt.noarch 0:2017.7.2-1.amzn1 will be installed
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-futures >= 2.0 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-crypto >= 2.6.1 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-six for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-markupsafe for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-jinja2 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-PyYAML for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27(dist-packages) for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27 for package: salt-2017.7.2-1.amzn1.noarch
--> Running transaction check
---> Package python27-tornado.x86_64 0:4.2.1-2.amzn1 will be installed
--> Processing Dependency: python27(dist-packages) for package: python27-tornado-4.2.1-2.amzn1.x86_64
---> Package salt.noarch 0:2017.7.2-1.amzn1 will be installed
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-futures >= 2.0 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-crypto >= 2.6.1 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-six for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-markupsafe for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-jinja2 for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27-PyYAML for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27(dist-packages) for package: salt-2017.7.2-1.amzn1.noarch
--> Processing Dependency: python27 for package: salt-2017.7.2-1.amzn1.noarch
---> Package zeromq.x86_64 0:4.0.5-4.amzn1 will be installed
--> Finished Dependency Resolution
Error: Package: salt-2017.7.2-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-requests >= 1.0.0
Error: Package: salt-2017.7.2-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-PyYAML
Error: Package: salt-2017.7.2-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-crypto >= 2.6.1
Error: Package: salt-2017.7.2-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-futures >= 2.0
Error: Package: salt-2017.7.2-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-six
Error: Package: salt-2017.7.2-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27
Error: Package: salt-2017.7.2-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-markupsafe
Error: Package: salt-2017.7.2-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-jinja2
Error: Package: python27-tornado-4.2.1-2.amzn1.x86_64 (salt-amzn-latest)
           Requires: python27(dist-packages)
Error: Package: salt-2017.7.2-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27(dist-packages)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
We do not support Amazon Linux 2 yet, it should be added in the next release.

**Comment by lorengordon** [comment]
Did Amazon Linux 2 change the default `$releasever` value? It used to by default resolve to `latest`, which would still work, http://repo.saltstack.com/yum/amazon/latest/x86_64/latest/...

**Comment by maschinetheist** [comment]
@lorengordon

It seems like YUM points to `2017.12` instead of `latest`:

```bash
# python -c 'import yum, pprint; yb = yum.YumBase(); pprint.pprint(yb.conf.yumvar, width=1)'
Loaded plugins: langpacks, update-motd
{'arch': 'ia32e',
 'awsdomain': 'amazonaws.com',
 'awsregion': 'us-west-2',
 'basearch': 'x86_64',
 'pointrelease': 'latest',
 'product': 'core',
 'releasever': '2017.12',
 'uuid': '58bdf026-779d-48ef-a0b3-2928186dbc04'}
```

Tweaking `/etc/yum.conf` did not seem to work. Regardless, I will wait patiently for the new Salt release to drop :)

**Comment by gtmanfred** [comment]
@dmurphy18 I am correct in thinking that there are some changes needed to make amazon linux work on the new release of amazon linux?

@maschinetheist you may be able to just hard code the release for centos 7, because amazon 2 is based on that, and we don't have a need to use a newer python version to get to python 2.7 like we did with centos 6/ amazon linux 1.

Thanks,
Daniel

**Comment by jerbowes** [comment]
2018-03-08: No JOY

# curl -L https://bootstrap.saltstack.com -o install_salt.sh 
# sudo sh install_salt.sh -P
 *  INFO: Running version: 2017.12.13
 *  INFO: Executed by: shell pipe
 *  INFO: Command line: 'install_salt.sh -P'

 *  INFO: System Information:
 *  INFO:   CPU:          GenuineIntel
 *  INFO:   CPU Arch:     x86_64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.9.76-38.79.amzn2.x86_64
 *  INFO:   Distribution: Amazon Linux AMI 2

 * ERROR: End of life distributions are not supported.
 * ERROR: Please consider upgrading to the next stable. See:
 * ERROR:     https://aws.amazon.com/amazon-linux-ami/

 # uname -a
Linux ip-172-31-8-86.us-east-2.compute.internal 4.9.76-38.79.amzn2.x86_64 #1 SMP Mon Jan 15 23:35:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux


 # yum info salt-minion
Loaded plugins: langpacks, priorities, update-motd
amzn2-core                                                                                                                                             | 2.0 kB  00:00:00     
salt-amzn-latest                                                                                                                                       | 2.9 kB  00:00:00     
(1/3): amzn2-core/2017.12/x86_64/group_gz                                                                                                              | 2.3 kB  00:00:00     
(2/3): salt-amzn-latest/x86_64/primary_db                                                                                                              |  20 kB  00:00:00     
(3/3): amzn2-core/2017.12/x86_64/primary_db                                                                                                            | 8.7 MB  00:00:00     
Available Packages
Name        : salt-minion
Arch        : noarch
Version     : 2017.7.4
Release     : 1.amzn1
Size        : 41 k
Repo        : salt-amzn-latest/x86_64
Summary     : Client component for Salt, a parallel remote execution system
URL         : http://saltstack.org/
License     : ASL 2.0
Description : The Salt minion is the agent component of Salt. It listens for instructions
            : from the master, runs jobs, and returns results back to the master.


## All baseurl versions fail
 # cat /etc/yum.repos.d/salt-amzn-latest.repo 
[salt-amzn-latest]
name=SaltStack Latest Release Channel for native Amazon Linux
#baseurl=https://repo.saltstack.com/yum/amazon/$releasever/$basearch/latest
#baseurl=https://repo.saltstack.com/yum/amazon/2017.12/$basearch/latest
baseurl=https://repo.saltstack.com/yum/amazon/latest/$basearch/latest
failovermethod=priority
priority=10
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/saltstack-signing-key


 # yum install salt-minion
Loaded plugins: langpacks, priorities, update-motd
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:2017.7.4-1.amzn1 will be installed
--> Processing Dependency: salt = 2017.7.4-1.amzn1 for package: salt-minion-2017.7.4-1.amzn1.noarch
--> Running transaction check
---> Package salt.noarch 0:2017.7.4-1.amzn1 will be installed
--> Processing Dependency: python27-tornado < 5.0 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-msgpack > 0.3 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-futures >= 2.0 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-crypto >= 2.6.1 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-zmq for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-six for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-psutil for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-markupsafe for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-jinja2 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-PyYAML for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27(dist-packages) for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27 for package: salt-2017.7.4-1.amzn1.noarch
--> Running transaction check
---> Package python27-msgpack.x86_64 0:0.4.6-2.amzn1 will be installed
---> Package python27-psutil.x86_64 0:5.2.2-2.ius.amzn1 will be installed
---> Package python27-tornado.x86_64 0:4.2.1-2.amzn1 will be installed
--> Processing Dependency: python27(dist-packages) for package: python27-tornado-4.2.1-2.amzn1.x86_64
---> Package python27-zmq.x86_64 0:14.5.0-3.amzn1 will be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-3.amzn1.x86_64
---> Package salt.noarch 0:2017.7.4-1.amzn1 will be installed
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-futures >= 2.0 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-crypto >= 2.6.1 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-six for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-markupsafe for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-jinja2 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-PyYAML for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27(dist-packages) for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27 for package: salt-2017.7.4-1.amzn1.noarch
--> Running transaction check
---> Package python27-tornado.x86_64 0:4.2.1-2.amzn1 will be installed
--> Processing Dependency: python27(dist-packages) for package: python27-tornado-4.2.1-2.amzn1.x86_64
---> Package salt.noarch 0:2017.7.4-1.amzn1 will be installed
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-futures >= 2.0 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-crypto >= 2.6.1 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-six for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-markupsafe for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-jinja2 for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27-PyYAML for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27(dist-packages) for package: salt-2017.7.4-1.amzn1.noarch
--> Processing Dependency: python27 for package: salt-2017.7.4-1.amzn1.noarch
---> Package zeromq.x86_64 0:4.0.5-4.amzn1 will be installed
--> Finished Dependency Resolution
Error: Package: salt-2017.7.4-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-PyYAML
Error: Package: salt-2017.7.4-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-jinja2
Error: Package: salt-2017.7.4-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-markupsafe
Error: Package: salt-2017.7.4-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27
Error: Package: salt-2017.7.4-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-requests >= 1.0.0
Error: Package: salt-2017.7.4-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-six
Error: Package: salt-2017.7.4-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-crypto >= 2.6.1
Error: Package: python27-tornado-4.2.1-2.amzn1.x86_64 (salt-amzn-latest)
           Requires: python27(dist-packages)
Error: Package: salt-2017.7.4-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27-futures >= 2.0
Error: Package: salt-2017.7.4-1.amzn1.noarch (salt-amzn-latest)
           Requires: python27(dist-packages)
 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest

**Comment by gtmanfred** [comment]
Amazon 2 is not supported yet.

https://github.com/saltstack/salt-bootstrap/issues/1194
