### ISSUE TITLE
[PY3] salt/salt/utils/data.py need to support in and out of different langs

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#45155]
### Description of Issue/Question
data.py is hard coded to use `__salt_system_encoding__`

For example someone calling salt-call could have a different language to the language defined for salt-minion will result in different output.

Salt Team need to say UTF-8 is the standard for templates and sls files etc (except for binaries). Provided a checker/converter tool for the master in salt-common.   salt-call or salt-minion need to convert to the target lang encoding on output, to one provide by the user in an sls file within the state  or the default language of the OS.

UTF-8  SLS could output English and Japanese.  e.g it could have if statement to action/output  different text based on the minion language.  Suitable example might be Windows Group Policies which are defined in the language of the OS is installed in and also US English. (@twangboy pls confirm)

**Comment by twangboy** [comment]
From what I'm reading, `__salt_system_encoding__` is set to `mbcs` in Windows... which is whatever the Windows system encoding is set to. That's basically what you're saying here right?

https://github.com/saltstack/salt/blob/oxygen/salt/__init__.py#L72

**Comment by damon-atkins** [comment]
Nope.   
Here is a summary of comments made against recent PRs
-- 44877
Assume all PY2 input from files (assumed to be UTF-8 unless indicated otherwise) or minion configs (UTF-8) or command lines (`__salt_system_encoding__`) or jinja (UTF-8) will be converted to Unicode and os.getenv() or os.environ.get() (`__salt_system_encoding__`)
This needs to be utf-8 only. For example someone edits a file on Unix in UTF-8 and then applies it to a windows system with a default language of Japanese. Or the other way around someone create a file on Windows in Japanese and then puts in the salt master which is UTF-8, and applies it to Unix systems.

-- 44892
Salts python code is UTF-8, and therefore control/functions statements like pkg.installed are in UTF-8 used within sls files.

Compares some of the 0-255 8bit languages https://en.wikipedia.org/wiki/ISO/IEC_646 Take note of the following chars `[, ], \ {, }, ^`, they are displayed as different characters in different languages.

-- 44877
The idea is that, internally salt is Unicode/UTF-8. A template can be UTF-8 (I would like to see this as must be) on the master, and need to output to Greek language 8bit (non-unicode) on the local minion.

A text file on the minion might be Latin language which needs to be convert correctly into Unicode, so it can be processed within salt to return results to the master. e.g. `salt latin-box cmd.run rd_text_type=latin cat latin-file`, the output to the screen is Unicode/UTF-8 on the master because the person using a terminal which supports UTF-8. Very bad example. Text functions need to be able to override the os default language, we should not make the assumption that it is always `__salt_system_encoding__`.

The master might be running as UTF-8 daemon, and the salt command might be used on the same system with a person using non-Unicode language because that's what their terminal supports..

--
Another example might be the OS language is Mandarin and and the configuration file for an app is US-ASCII, all the file.* need to be able to convert to any format. e.g. UTF-8 SLS file and UTF-8 Template resulting in a US-ASCII file on a OS Language with Mandarin.  Or UTF-8 SLS file altering an US-ASCII file on a  OS Language with Mandarin.

One of the reason SLS files and templates need to be UTF-8 is the salt functions/jinja are in English only and the target can be non-English platform.

@terminalmage been accepting my feed back (with adjustments) so this summary should not be an indication that it has not been accepted.

This bit needs to be change so that other parts of salt can be changed.
