### ISSUE TITLE
RFC: add `salt-key` to "salt-common" package

### ISSUE THREAD

**Issue by jf** [saltstack/salt#45165]
What do folks think of adding the `salt-key` utility to `salt-common`, instead of restricting it to salt-master? I am really only interested in the `salt-key --gen-keys=` functionality. When dynamically spinning up VMs, I want each spun-up VM to be able to generate its own private-public key pair.

**Comment by garethgreenaway** [comment]
@dmurphy18 Thoughts on this one?

**Comment by dmurphy18** [comment]
@jf I believe currently the salt-minion will generate its own key-pair if there is not one already present when it initially boots up, and then pass the public key to the master, noting that minions can be used without a master present in a peer-to-peer environment.  Also you can preseed the keys the minion will use, ref. https://docs.saltstack.com/en/latest/topics/tutorials/preseed_key.html

**Comment by jf** [comment]
> I believe currently the salt-minion will generate its own key-pair if there is not one already present when it initially boots up

Yup, I can confirm that with salt-minion 2016.11.8. If I were to adopt this approach to get the minion to regen its keypair, I have 2 options, neither of which really seem the best for me:

1. I can use cloud-init to run a command upon boot to remove the keys (https://cloudinit.readthedocs.io/en/latest/topics/examples.html#run-commands-on-first-boot). Here, I can use either `bootcmd`, or `runcmd`.

`bootcmd` will run *every single time the instance is booted* and cause the key to change every single time. I dont want that.

For `runcmd`, it's not entirely clear when it'll run, and whether I can actually depend - reliably! - on it to always run before `salt-minion` starts. If it runs after `salt-minion` has started already, it will cause the minion to fail (in minion log: '... `IOError: [Errno 2] No such file or directory: '/etc/salt/pki/minion/minion.pub'`); AND it will not just not regen the keypair, upon reboot this particular minion would be guilty of sending 2 different keys to the salt master. Not good.

2. I can have a finalizing script in my image packing process (we use Packer) to remove the keypair before finalizing the image. That works, but reduces the flexibility of not being able to chain another image after this one is packed.

Granted there are workarounds to number 1 and 2... but really, if salt-key could just be included, it would be much easier. Are there any reasons why it shouldn't be?

**Comment by dmurphy18** [comment]
@jf Perhaps if you could explain the issue / scenario that you are trying to solve with moving salt-key, it might provide more light on the reason why moving salt-key is a good solution.

**Comment by jf** [comment]
@dmurphy18 I have some context in https://github.com/saltstack/salt/issues/45165#issuecomment-354966073. I've solved it currently by simply using a state to add `salt-key` (from the master!) to the image - *and* also disabling salt-minion autostart, so that I can guarantee that the key is generated before the minion starts up, and that only *one* key is sent to the master. As such, I dont *need* `salt-key` to move... but for others in the same situation, there are a few advantages:
1. there will be no ambiguity about what needs to be done to get `salt-key` working on a minion.
2. they don't need to do any work to get `salt-key` on to a minion (nor verify that it works!)
3. practically speaking, since `salt-common` is common across the master and minion, you would not lose anything on the server by moving the file across to `salt-common`.
