### ISSUE TITLE
reactors: target a minion by multiple things

### ISSUE THREAD

**Issue by Danixu** [saltstack/salt#45168]
Hello,

### Description of Issue/Question
My question is if there is any way to target a minion by multiple targets type instead just one.
I've read the document and I've seen that normally the minion is targeted by ID, and with tgt_type you can change the target match to other things like grains.
I want to target a minion by ID and only run the reactor if has a grain so I need to filter by id and then filter by grain, but the reactor only allow one of them at once (and filter by grain affects a lot of minions).

My reactor is just:
```
update_nginx:
  local.state.sls:
    - name: 'Actualiza el nginx'
    - tgt: '{{ data['id'] }}'
    - args:
      - mods: nginx
```
And I want to run this reactor only if target have an item "nginx" on "states" grain.

### Versions Report
```
# salt-master --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.2 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.2 
```
```
# salt-minion --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.10 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.10
```

Thanks!!

**Comment by V3XATI0N** [comment]
The problem with doing it the way you want to is that events don't know anything about grains. They generally only know the name of the minion that spawned them, and pass that to the reactor system. So there's no variable in the event data that you can parse to get the grain data you need.

Have you considered moving your grain evaluation to the state the reactor calls, so that it only executes if the grain is present and matches your value? That way, the reactor can still call the state even if you don't need it, and the state can determine for itself whether or not it should run.

**Comment by Danixu** [comment]
Thanks,

After some research I've seen that is able on the way you say, so I've created a state for reactors with that filters.

Greetings!!
