### ISSUE TITLE
osquery execution module does't work with attrs parameter

### ISSUE THREAD

**Issue by thuhak** [saltstack/salt#45176]
### Description of Issue/Question

in latest osquery, command 'pragma table_info' no longer exists, which cause helper function _table_attrs failed.

```python
def _table_attrs(table):
    '''
    Helper function to find valid table attributes
    '''
    cmd = ['osqueryi'] + ['--json'] + ['pragma table_info{0}'.format(table)]
    res = __salt__['cmd.run_all'](cmd)
    if res['retcode'] == 0:
        attrs = []
        text = json.loads(res['stdout'])
        for item in text:
            attrs.append(item['name'])
        return attrs
    return False
```

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 11.0.0
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by garethgreenaway** [comment]
@thuhak Thanks for the report.  What version of `osquery` are you using?

**Comment by garethgreenaway** [comment]
@thuhak Actually found the issue, it's a bug in the module itself.  Working on a fix now.

**Comment by garethgreenaway** [comment]
The fix for this has been merged.  Going to close this one out.  If the problem persists, please feel free to reopen the issue.  Thanks!
