### ISSUE TITLE
salt/modules/kubernetes.py uses incorrect attribute names

### ISSUE THREAD

**Issue by skorhone** [saltstack/salt#45194]
### Description of Issue/Question
Kubernetes state module uses attribute names from swagger generated classes in configuration processing. As a result camelcase is converted to snake case. This causes issues with configuration items such as 'targetPort'.

State module should make use of 'attribute_map' in swagger generated classes for proper translation.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

nginx-service.yml:

kind: Service
apiVersion: v1
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 18080
    targetPort: 80 # Works only, if written as target_port

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.6.1
      docker-py: 1.9.0
          gitdb: 0.6.4
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-104-generic
         system: Linux

**Comment by gtmanfred** [comment]
@flavio can I get your opinion on this one as well?

Thanks,
Daniel
