### ISSUE TITLE
salt.modules.cmdmod.shell_info docstring needs fixing 2016.11

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#45193]
### Description of Issue/Question
salt.modules.cmdmod.shell_info needs fixing

Should be more like

Args:
- shell (str): Name of the shell. Support shells/script languages include bash, cmd, perl, php, powershell, python, ruby and zsh
- list_modules (bool): True to list modules available to the shell.  Currently only lists powershell modules.

**Comment by gtmanfred** [comment]
Would you mind submitting a PR with this?

Thanks Damon,
Daniel

**Comment by damon-atkins** [comment]
Is their a way to generate the doco in html format so it can be checked, from the checkout git

**Comment by gtmanfred** [comment]
Here is the steps we use to generate the docs for docs.saltstack.com

https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#building-the-documentation
