### ISSUE TITLE
 honor tcp_pub_port when transport type is TCP

### ISSUE THREAD

**Issue by michaelgibson** [saltstack/salt#45202]
### Description of Issue/Question
Currently the "tcp_pub_port" config option for minions is being ignored when transport is set to "tcp".
It is currently getting set to the value passed back from the master's "publish_port".
At least during the initial auth phase of establishing a connection from minion to master.

This may be desirable behavior for zmq transport(although I'd still like to control that as well) but when using TCP it should defer to the minion's config setting.
This is breaking the ability to host the master behind a proxy service as the ports are translated.

I have a workaround here but it's probably not in the implemented in the best spot.
https://github.com/saltstack/salt/pull/45185

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
master config:
publish_port: 4521
transport: tcp

minion config:
transport: tcp
tcp_pub_port: 4521

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt-minion -c ./etc/salt -l debug 
[DEBUG   ] Initializing new AsyncTCPReqChannel for (u'/etc/salt/pki/minion', 'saltdev', u'tcp://127.0.0.1:4506', 'clear')
[ERROR   ] Error while bringing up minion for multi-master. Is master at localhost responding?

### Versions Report
 salt --versions-report
Salt Version:
           Salt: 2017.7.0-968-g808176b
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 2.7.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.7.4
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: 0.6.8
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: LinuxMint 18.1 serena
         locale: UTF-8
        machine: x86_64
        release: 4.13.6-041306-generic
         system: Linux
        version: LinuxMint 18.1 serena

**Comment by gtmanfred** [comment]
That seems reasonable, it might have to go behind a option flag to allow for people to still use the publish_port with the tcp transport.

Whoever comes along and reviews that PR will help get this fixed.

Thanks for the PR!
Daniel
