### ISSUE TITLE
Use "match" argument in "ensure" mode of file.line

### ISSUE THREAD

**Issue by mnieber** [saltstack/salt#45210]
It would be nice if the `ensure` mode of `file.line` would replace an existing line if it matches the `match` argument. If no match is found, it can use the other arguments (such as before/after/location) to ensure that the line is present. If more than 1 match is found, it should (imo) raise an error.

Example implementation:
https://github.com/mnieber/salt/commit/04d4da3e533bf9f3ce2b8fcaa45600c76e0921e1

**Comment by gtmanfred** [comment]
If you wanted to submit a PR upstream to add this, we would greatly appreciate it.

Otherwise, I have marked this as a feature request.

Thanks,
Daniel

**Comment by mnieber** [comment]
@gtmanfred I will have a go at the pull request, but I don't want to promise too much yet (I was able to run the unit tests, and of course a few failed due to the changes I made. I think a PR with fixed tests should not be too hard to accomplish)

**Comment by gtmanfred** [comment]
:+1: let me know if you need any assistance.

There is also a #develop channel on the [saltstack community slack](https://saltstackcommunity.herokuapp.com) if you have any questions feel free to ask there too

Thanks!
Daniel
