### ISSUE TITLE
salt-api is not working. "Authentication failure of type "eauth" occurred"

### ISSUE THREAD

**Issue by girishbin** [saltstack/salt#45214]
my salt-api conf file 

- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -

rest_cherrypy:
  port: 8000
  host: 0.0.0.0
  debug: True
  disable_ssl: true
  
externalauth:
  pam:
    salt:
       - .*
       - '@wheel'   # to allow access to all wheel modules
       - '@runner'  # to allow access to all runner modules
       - '@jobs'    # to allow access to the jobs runner and/or wheel module

- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -

I have created a user called salt and set the password.
Here are the logs for pam 

salt -a pam '*' test.ping -l trace
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master
[DEBUG   ] Missing configuration file: /root/.saltrc
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/salt-api.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/salt-api.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] LazyLoaded pam.auth
username: salt
password:
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt-master_master', 'tcp://127.0.0.1:4506', 'clear')
[TRACE   ] Inserted key into loop_instance_map id 140408101590080 for key ('/etc/salt/pki/master', 'salt-master_master', 'tcp://127.0.0.1:4506', 'clear') and process 28430
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).
Failed to authenticate! This is most likely because this user is not permitted to execute commands, but there is a small possibility that a disk error occurred (check disk/inode usage).

- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -

Versions: 

salt-master:/etc/salt/master.d# salt-api --version
salt-api 2017.7.1 (Nitrogen)

- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -

salt-master:/etc/salt/master.d# salt --versions-report
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1038-aws
         system: Linux
        version: Ubuntu 16.04 xenial
        
- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -- - - - - - -

Salt-master debug logs 

2017-12-28 18:56:50,026 [salt.auth        ][WARNING ][17583] Authentication failure of type "eauth" occurred.
2017-12-28 18:56:50,027 [salt.master      ][WARNING ][17583] Authentication failure of type "eauth" occurred.

**Comment by gtmanfred** [comment]
So, you are not using salt-api, you are only using eauth.

Where is your `salt-api` config file?  These configurations should just go in `/etc/salt/master` and you will need to restart the master.

Daniel

**Comment by girishbin** [comment]
@gtmanfred  Thanks for the reply. 
Below is  my conf file in  **/etc/salt/master.d/salt-api.conf** . This config is picked up and salt-api runs on port 8000


```
rest_cherrypy:
     port: 8000
     host: 0.0.0.0
     debug: True
     disable_ssl: true

externalauth:
pam:
salt:
    - .*
    - '@wheel' # to allow access to all wheel modules
    - '@runner' # to allow access to all runner modules
    - '@jobs' # to allow access to the jobs runner and/or wheel module

```

output of curl 

 ```curl -sSk http://localhost:8000/login     -H 'Accept: application/x-yaml'     -d username='salt'     -d password='xxxxxx'     -d eauth=auto```

```
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/usr/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 744, in hypermedia_handler
    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpdispatch.py", line 34, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1753, in POST
    'Could not authenticate using provided credentials')
HTTPError: (401, 'Could not authenticate using provided credentials')
</pre>
    <div id="powered_by">
    <span>Powered by <a href="http://www.cherrypy.org">CherryPy 3.2.2</a></span>
    </div>
    </body>

```

Even running just  **salt -a pam '*' test.ping -l trace** is not working.

**Comment by gtmanfred** [comment]
This should be external_auth, not externalauth

```
external_auth:
  pam:
    salt:
      - .*
      - '@wheel' # to allow access to all wheel modules
      - '@runner' # to allow access to all runner modules
      - '@jobs' # to allow access to the jobs runner and/or wheel module
```

**Comment by girishbin** [comment]
Tried with external_auth too , did not worked. Thanks 

```external_auth:
 pam:
   salt:
    - .*
    - '@wheel' # to allow access to all wheel modules
    - '@runner' # to allow access to all runner modules
    - '@jobs' # to allow access to the jobs runner and/or wheel module
```

**Comment by gtmanfred** [comment]
```
[root@salt ~]# cat /etc/salt/master
external_auth:
 pam:
   salt:
    - .*
    - '@wheel' # to allow access to all wheel modules
    - '@runner' # to allow access to all runner modules
    - '@jobs' # to allow access to the jobs runner and/or wheel module
[root@salt ~]# systemctl start salt-master salt-minion
[root@salt ~]# useradd -m salt
[root@salt ~]# echo testpass | passwd --stdin salt
Changing password for user salt.
passwd: all authentication tokens updated successfully.
[root@salt ~]# salt-key -Ay
The following keys are going to be accepted:
Unaccepted Keys:
salt
Key for minion salt accepted.
[root@salt ~]# sleep 10
[root@salt ~]# salt -a pam --username=salt --password=testpass \* test.ping
salt:
    True
```

It is working here.

**Comment by sootythebear** [comment]
The `curl` command:
```
curl -sSk http://localhost:8000/login -H 'Accept: application/x-yaml' -d username='salt' -d password='xxxxxx' -d eauth=auto
```
is failing because the `eauth` under `external_auth:` is actual `pam`. The command in this case should be:
```
curl -sSk http://localhost:8000/login -H 'Accept: application/x-yaml' -d username='salt' -d password='xxxxxx' -d eauth=pam
```

**Comment by Arabus** [comment]
So this is a misleading example in the rest_cherrypy documentation?

**Comment by sootythebear** [comment]
Personally, there is definitely a mismatch from the example used, and the default entry in the Salt `master` file - where the `eauth` is `pam`. Ideally, if `auto` is used, the corresponding `master` configuration should be highlighted - it would re-enforce the information under: https://docs.saltstack.com/en/latest/topics/eauth/index.html#matching-syntax

(I would even throw in a mention or link to the `auth` modules at: https://docs.saltstack.com/en/latest/salt-modindex.html#cap-a)

An additional facet to my confusion, was the `POST` example used for the `/login` API call at:
https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#login

Here  the curl command uses `auto` for the `eauth` but the return shows the `eauth` as `pam` - without knowing better, this gave me the impression that `auto` was able to authenticate any `eauth`.
