### ISSUE TITLE
salt file.managed if directory contains chinese failed

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#45230]
### Description of Issue/Question
I want to use file.managed module to scp file from master to minion,but if the directory contains chinese ,it return none of the specified sources were found,what should i do.Thanks
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
deploy.sls:
/tmp/zeus.zip:
  file.managed:
    - source:
      - salt://deploy/20180102/自动化平台/prd/zeus.zip
    - template: jinja

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt '172.20.68.10' state.sls deploy/deploy

     172.20.68.10:
----------
          ID: /tmp/zeus.zip
    Function: file.managed
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 17:20:21.136570
    Duration: 26.546 ms
     Changes:   

     Summary for 172.20.68.10
     ------------
     Succeeded: 0
     Failed:    1
     ------------
    Total states run:     1
    Total run time:  26.546 ms

But the directory is exist.

[root@saltstackprd2 salt]# ls -l /srv/salt/deploy/20180102/自动化平台/prd/zeus.zip 
-rw-r--r--. 1 root root 1856621 Jan  2 09:34 /srv/salt/deploy/20180102/自动化平台/prd/zeus.zip

I have tried set yaml_utf8: True ,but it does not work.What else can i do. Thanks..

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by damon-atkins** [comment]
Try the fix See https://github.com/saltstack/salt/issues/42278#issuecomment-318913952

**Comment by liuhetongzi** [comment]
@damon-atkins Thank you for your reply.I try the fix #42278 but it does not work.And I try update my salt to the lastest version Salt: 2017.7.2,It does not work too.

Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.7 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final


    172.20.7.222:
    ----------
          ID: /tmp/zeus.zip
    Function: file.managed
      Result: False
     Comment: Unable to manage file: none of the specified sources were found
     Started: 10:29:46.643778
    Duration: 15.778 ms
     Changes:   

    Summary for 172.20.7.222
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1
    Total run time:  15.778 ms
