### ISSUE TITLE
custom grain not able to call proxy module function, throws NameError: global name '__proxy__' is not defined

### ISSUE THREAD

**Issue by vnitinv** [saltstack/salt#45265]
### Description of Issue/Question
I have written custom grain, which tries to call proxy function but fails

```
  File "/usr/local/lib/python2.7/dist-packages/salt/loader.py", line 750, in grains
    ret = funcs[key](proxy)
  File "/var/cache/salt/proxy/extmods/proxy01/grains/iagent.py", line 37, in get_version

  File "/usr/local/lib/python2.7/dist-packages/salt/modules/junos.py", line 1354, in cli
    conn = __proxy__['junos.conn']()
NameError: global name '__proxy__' is not defined
```
@cro @mirceaulinic Do you have any suggestion from changes done for https://github.com/saltstack/salt/issues/30642

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
custom grains contents:
```python
import logging

log = logging.getLogger(__name__)

# Define the module's virtual name
#import salt.utils
import salt.utils.platform
#import salt.client


__proxyenabled__ = ['junos']
__virtualname__ = 'junos'

def __virtual__():
    '''
    Only work on proxy
    '''
    try:
        if salt.utils.platform.is_proxy() and \
           __opts__['proxy']['proxytype'] == 'junos':
            return __virtualname__
    except KeyError:
        pass

    return False

import salt.modules.junos

__salt__ = {
    'junos.cli': salt.modules.junos.cli
}

def get_version(proxy):
    if proxy:
        data = __salt__['junos.cli']("show version")
```

### Versions Report
/srv/salt/_grains# salt --versions-report
Salt Version:
           Salt: 2017.7.0-679-gd9dcc40
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.31-moby
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
@cro or @mirceaulinic are definitely the ones that could have some good insight here. Waiting for their input thanks :)

**Comment by cro** [comment]
I need to try this out and see if it got broken in 2017.7.  I will try to get to this tomorrow.
