### ISSUE TITLE
Feature request for saltutil.synced_all and related state modules

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#45264]
### Description of Issue/Question
Currently if I need to sync custom states, modules, grains, etc. and have that triggered from a state sls, I need to wrap the request in a `module.run` block. This has the disadvantage of triggering a system "change" every time that state sls executes, even if everything was already in sync.

I feel this is a common (possibly the most common) use case for using `module.run`, but it's far from ideal.

### Setup
I would like to replace something like:
```
update_all:
  module.run:
    - saltutil.sync_all:
      - refresh: True
```
(assuming `use_superseded` for `module.run` is in play) with:
```
update_all:
  saltutil.synced_all:
    - reload_modules: True
```
The output would ideally show only modules that needed to be synced, or otherwise indicate no changes were necessary to the system. I would expect `saltutil.synced_modules`, `saltutil.synced_states`, etc. be implemented similarly.

### Steps to Reproduce Issue
N/A

### Versions Report
Not implemented as of Salt 2017.7.2 (Nitrogen).

**Comment by Ch3LL** [comment]
I think this is a great idea. We are more than willing to accept a PR for this if you want to give it a go

**Comment by boltronics** [comment]
Thanks. I'd be happy to give it a go when I find enough free time. Probably not any time soon though, so equally happy if someone else beats me to it. :wink:

**Comment by max-arnold** [comment]
@boltronics The linked PR was merged. Perhaps this issue could be closed?

**Comment by boltronics** [comment]
@max-arnold Sorry I didn't notice this previously. It looks like @mchugh19 has done wonderful work. Thanks!

I don't believe I have privileges to do so, but I'm happy for this to be closed.

**Comment by boltronics** [comment]
Oh I do. :wink:
