### ISSUE TITLE
Environment could not be retrieved for User 'foo'

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#45266]
### Description of Issue/Question

This does work:

`somehost# salt-ssh remote-host gray state.sls monitoring`

This does not work:

`otherhost# ssh somehost salt-ssh remote-host gray state.sls monitoring`

Error if called via ssh:
```
          ID: modcron__virtualenv
    Function: virtualenv.managed
        Name: /localhome/user/modcron
      Result: False
     Comment: Environment could not be retrieved for User 'modcron'
     Started: 10:47:44.456176
    Duration: 521.571 ms
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
salt:/srv # salt --versions-report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.22.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.6
 
System Versions:
           dist: SuSE 12.3 x86_64
         locale: UTF-8
        machine: x86_64
        release: 3.7.10-1.45-default
         system: Linux
        version: openSUSE  12.3 x86_64
```

**Comment by guettli** [comment]
I edited the code on the minion like this:

`vi /var/tmp/.root_dcdf8c_salt/py2/salt/modules/cmdmod.py`

I replaced the swallowing of the exception and added a more verbose Exception()

```
...
            for key, val in six.iteritems(env):
                if isinstance(val, six.text_type):
                    try:
                        env[key] = val.encode(fse)
                    except UnicodeEncodeError as exc: ## new
                        raise Exception('%s %r %r %r' % (exc, key, val, fse))
        except IOError:#ValueError as exc: ## new
```
Now the real problem is visible:

```
File "/var/tmp/.root_dcdf8c_salt/py2/salt/modules/cmdmod.py", line 457, in _run
    raise Exception('%s %r %r %r' % (exc, key, val, fse))

Exception: 'ascii' codec can't encode character u'\xe4' in position 15: ordinal not in range(128) u'GPG_TTY' u'kein Ausgabeger\xe4t' 'ANSI_X3.4-1968'
```

There is a german umlaut in the environment variables.

**Comment by Ch3LL** [comment]
Thanks for the pr!! As this resolves the issue I will close here and we can keep the discussion in the PR but please let me know if you need to re-open this.

**Comment by guettli** [comment]
This issue is about the specific problem which I had.

But looking at the code lines above and below my patch, I still think there is something wrong.

I wrote about it here: https://groups.google.com/forum/#!topic/salt-users/Q3wkW81DF-U

Unfortunately there was no reply up to now.

@Ch3LL  What do you think about my message on the salt-users list?

**Comment by Ch3LL** [comment]
From your google groups message "This code does swallow the orignal ValueError and creates a nice CommandExecutionError. But the original root of the error gets lost :-("

can you elaborate on what you want this try,except to do. We don't want to stacktrace with teh valueerror hence that error message but maybe you are saying the valueerror could be for other reasons?

**Comment by guettli** [comment]
@Ch3LL I try to elaborate why I did this patch.

The environment variable 'GPG_TTY'  does contain a german Umlaut in my case: u'kein Ausgabeger\xe4t'

I guess this is the case because /dev/tty can't be read. But in my case it does not matter.

There is a environment variable which fails to be encoded. 

I see these solution variants:

V1: Current state: fail with "Environment could not be retrieved for User 'foo' " It will take some time for an expert who is not afraid of changing salt source code to debug this. Most users will fail in finding the real root of the problem.

V2: Raise an exception where you see which environment variable contains which string. In my case this would not help much. I have no clue where GPG_TTY comes from, and I don't care. I don't need this variable.

V3: do a fail safe encoding. This is the solution I do in my pull request.

I guess there are several other solution variants. If I can be of assistance, please do not hesitate to contact me :-)

**Comment by terminalmage** [comment]
Please see https://github.com/saltstack/salt/pull/45267#pullrequestreview-90580280.

**Comment by guettli** [comment]
@terminalmage thank you very much. I close my issue
