### ISSUE TITLE
Trafficserver module fails when constructing arguments

### ISSUE THREAD

**Issue by NTmatter** [saltstack/salt#45274]
### Description of Issue/Question
The trafficserver state and module always fail with:
`Passed invalid arguments: can only concatenate list (not "tuple") to list.`

This seems to boil down to: https://github.com/saltstack/salt/blob/80d90307b07b3703428ecbb7c8bb468e28a9ae6d/salt/modules/trafficserver.py#L35-L36
https://github.com/saltstack/salt/blob/80d90307b07b3703428ecbb7c8bb468e28a9ae6d/salt/modules/trafficserver.py#L39-L40

As a quick hack, converting the tuple to a list and stringifying seems to work around the issue (beware of potential for problems with shell escaping):
`return ' '.join([_TRAFFICCTL] + [str(arg) for arg in args])`
`return ' '.join([_TRAFFICLINE] + [str(arg) for arg in args])`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
`apt install trafficserver`

### Steps to Reproduce Issue
`salt-call --local trafficserver.status`

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: Not Installed
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-42-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@NTmatter Thanks for the report.  I was able to duplicate this issue.  It looks like you're on the right track for a fix and we would definitely welcome a pull request.
