### ISSUE TITLE
Docs about Ordering States

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#45288]
### Description of Issue/Question
I think the current docs of "Ordering states" could be improved.

> Salt always executes states in a finite manner, meaning that they will always execute in the same order regardless of the system that is executing them. But in Salt 0.17.0, the state_auto_order option was added. This option makes states get evaluated in the order in which they are defined in sls files, including the top.sls file.

>The evaluation order makes it easy to know what order the states will be executed in, but it is important to note that the requisite system will override the ordering defined in the files, and the order option described below will also override the order in which states are defined in sls files.

> If the classic ordering is preferred (lexicographic), then set state_auto_order to False in the master configuration file. Otherwise, state_auto_order defaults to True.

Source https://docs.saltstack.com/en/latest/ref/states/ordering.html#state-auto-ordering

The version 0.17.0 was released on 2013-09-26. I guess 99% of all users use a newer version.

I think it would be much more easier to read, if you just present the current state exclusively. Users of the four years old version should read the four years old docs :-)

This is current state: States get evaluated in the order in which they are defined in sls files.

**Comment by garethgreenaway** [comment]
@guettli Thanks for the report.
