### ISSUE TITLE
External cloud pillar

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#45290]
### Description of Issue/Question
For writing custom external pillar i see that there is following def structure to be used,

def ext_pillar(minion_id,
               pillar,  # pylint: disable=W0613
               url=None):

What is the use of pillar variable here?

2) At the documentation mentioned [here](https://docs.saltstack.com/en/latest/topics/development/external_pillars.html)
Following is the external pillar definition mention,
```
def ext_pillar( minion_id, pillar, *args, **kwargs ):

    my_pillar = {'external_pillar': {}}

    my_pillar['external_pillar'] = get_external_pillar_dictionary()

    return my_pillar
```
What is the use of pillar, args and kwargs here?

I am trying to pass a value to my external pillar depending on which i will be pulling corresponding profile from my external db. That value can be an external id (for example) using which i will be fetching that particular pillar instead of all the pillar values.

Here in my pillar are number of cloud profiles and providers.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@sumeetisp Thanks for the report.  In the ext_pillar function the `pillar` argument is the existing pillar values, the args and kwargs are additional pillar values that should be added.  The example from the documentation that you included illustrates this with the three calls to ext_pillar, each one building on the last with additional values.

**Comment by sumeetisp** [comment]
so if use the following command,
salt-call cloud.profile someprofile vmname pillar={"profile":"someprofile"}

Will the pillar value here be available in my external pillar via pillar attribute in 
def ext_pillar( minion_id, pillar, *args, **kwargs ):

Or is there any other way to get the profile value in my external pillar.

**Comment by sumeetisp** [comment]
@garethgreenaway Please help

**Comment by sumeetisp** [comment]
Can this be achieved?
