### ISSUE TITLE
Can not modify existing RDS instance via boto_rds.present

### ISSUE THREAD

**Issue by hibbert** [saltstack/salt#45300]
### Steps to Reproduce Issue
* Use boto_rds.present to create a RDS instance omitting the tags part
* Database is created
* Add tags into boto_rds.present
* Nothing is update

State file only has create in it https://github.com/saltstack/salt/blob/develop/salt/states/boto_rds.py, it doesn't call modify_db_instance in https://github.com/saltstack/salt/blob/develop/salt/modules/boto_rds.py. Also looks like exists in https://github.com/saltstack/salt/blob/develop/salt/modules/boto_rds.py takes tags as a parameter but does not use it

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by garethgreenaway** [comment]
@hibbert Thanks for the report.  This is definitely something that would be nice to have supported in the state module, especially since it's available in the execution module.  Approving for a future feature addition.  Thanks!
