### ISSUE TITLE
Conditional group.absent - Only remove when group is not in use

### ISSUE THREAD

**Issue by sastorsl** [saltstack/salt#45311]
### group.absent should have an optional condition - remove only if not in use
If such an option existed you could safely use group.absent where many users might share the same group. If the group is in use by any user it should abort successfully _if_ this option was turned on.

salt '*' group.absent foo onlyifempty=True

The default could be discussed, but False will adhere to the current usage.

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
N/A

**Comment by gtmanfred** [comment]
I am marking this as a feature request.

group.absent is a state, so there would need to be changes to that, but it seems like a reasonable idea.  

If you had time to submit a PR we would appreciate it.

Thanks,
Daniel

**Comment by sastorsl** [comment]
Created a PR, @gtmanfred . Have a look.
