### ISSUE TITLE
Malformed topfile if variable is not given in salt call

### ISSUE THREAD

**Issue by Mannoj87** [saltstack/salt#45310]
### Description of Issue/Question
Malformed topfile if variable is not given in salt call. 
As per below top.sls file, I should be able to execute if variable is not given as well.

### Setup
top.sls

```
base:
  '\*':
     - toucher
  'vin-m*':
    {% set myenvvar = salt['environ.get']('MYENVVAR') %}
    {% if myenvvar == 'master' %}
     - toucher_master
    {% elif myenvvar == 'data' %}
     - toucher_slave
    {% endif %}
```
### Steps to Reproduce Issue
Works -> MYENVVAR="master" salt-call state.highstate
Doesn't work -> salt-call state.highstate

### Versions Report
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
        libgit2: 0.24.0
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: 0.24.0
   python-gnupg: Not Installed
          smmap: 0.9.0
        timelib: Not Installed

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.4.0-31-generic
         system: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
```
{%- set myenvvar = salt['environ.get']('MYENVVAR') %}
base:
  '*':
     - toucher
{%- if myenvvar %}
  'vin-m*':
    {%- if myenvvar == 'master' %}
     - toucher_master
    {%- elif myenvvar == 'data' %}
     - toucher_slave
    {%- endif %}
{%- endif %}
```

Each match needs to be a list, what you end up with in yours is `vin-m*: None` and None is not a list, if you wrap that entire block with an if statement that only adds that section if the environment variable is set, then  it will work.
