### ISSUE TITLE
Cloud providers - location attribute

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#45319]
### Description of Issue/Question

I have seen that if we are using something other than 'us-east-1' (which is default in salt code) then location has to be mentioned in provider explicitly.

if location is mentioned in provider then it will be required to create providers for each of the location of ec2 which somehow does not seem correct. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
each provider corresponds to a single setup, and if you want to build in more regions, you have to specify them.  So you need one provider for each region you want to be able to build in.
