### ISSUE TITLE
Feature request to display usage of a runner just like it's done for execution modules

### ISSUE THREAD

**Issue by golmaal** [saltstack/salt#45325]
### Description of Issue/Question
When an execution module function is called incorrectly, it shows a user friendly error (Passed invalid arguments) and displays the Usage of the function. However, when a runner module function is called incorrectly, it simply displays an exception

### Setup
[root@2017 salt]# salt-call pkg.version_cmp
```
Passed invalid arguments: version_cmp() takes at least 2 arguments (0 given).

Usage:
    .. versionadded:: 2015.5.4
    Do a cmp-style comparison on two packages. Return -1 if pkg1 < pkg2, 0 if
    pkg1 == pkg2, and 1 if pkg1 > pkg2. Return None if there was a problem
    making the comparison.

    ignore_epoch : False
        Set to ``True`` to ignore the epoch when comparing versions
        .. versionadded:: 2015.8.10,2016.3.2
    CLI Example:
    .. code-block:: bash
        salt '*' pkg.version_cmp '0.2-001' '0.2.0.1-002'
```
[root@2017 salt]# salt-run pkg.list_upgrades
```
Exception occurred in runner pkg.list_upgrades: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 382, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
TypeError: list_upgrades() takes at least 1 argument (0 given)

```
### Versions Report
Salt Version:
           Salt: 2017.7.0-n/a-dab4a8c

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
totally reasonable.  tagged as a feature request.

Thanks!
Daniel
