### ISSUE TITLE
[ERROR   ] Scheduled job "enabled" should have a dict value, not <type 'bool'>

### ISSUE THREAD

**Issue by vnitinv** [saltstack/salt#45320]
### Description of Issue/Question
Today I synced my repo with development and starting seeing log with some error. Nothing was changed in any of the config file.

```
[DEBUG   ] Loading static grains from /etc/salt/proxy.d/proxy01/grains
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] LazyLoaded status.proxy_reconnect
[ERROR   ] Scheduled job "enabled" should have a dict value, not <type 'bool'>
[DEBUG   ] LazyLoaded mine.update
[ERROR   ] Scheduled job "enabled" should have a dict value, not <type 'bool'>
[ERROR   ] Scheduled job "enabled" should have a dict value, not <type 'bool'>
[ERROR   ] Scheduled job "enabled" should have a dict value, not <type 'bool'>
[ERROR   ] Scheduled job "enabled" should have a dict value, not <type 'bool'>
[ERROR   ] Scheduled job "enabled" should have a dict value, not <type 'bool'>
```
### Setup
proxy executed using command:
```salt-proxy --proxyid=proxy01 -l debug```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
```
# salt --version
salt 2017.7.0-686-gc4ddf50 (Nitrogen)
```

**Comment by vnitinv** [comment]
Looks to be due to change in operator. `or` was changed to `and`

https://github.com/saltstack/salt/commit/7612a5dd14c5b03dda28a4f422705c84b90b02b2#diff-5d25431a967d6d0ff595ab14e9ac4291R1131

**Comment by gtmanfred** [comment]
@garethgreenaway can you take a look at this? was there a reason that this was changed from `or` to `and?

Thanks,
Daniel

**Comment by garethgreenaway** [comment]
That looks to be a typo on my part.  Fixed in that PR.

**Comment by gtmanfred** [comment]
thanks @garethgreenaway !

**Comment by garethgreenaway** [comment]
The fix for this has been merged and will be in the Oxygen & Fluorine releases.
Going to close this one out.  If the problem persists, please feel free to reopen the issue.
Thanks!
