### ISSUE TITLE
salt-ssh: specify minion's python interpreter in roster file

### ISSUE THREAD

**Issue by chschmitt** [saltstack/salt#45321]
### Description of Issue/Question
I am using salt with python 3. I would like to specify the python interpreter that is used on a specific salt-ssh minion via the roster file. I have a minion that is still stuck on Ubuntu 12.04 (Python 3.2) but that has a self-compiled Python 3.5 installed. 

The system's python3 interpreter on the minion throws an exception (see below). If it was possible to tell salt to use the other interpreter (or even better a venv of that interpreter), I could work around that problem.

### Setup
python3 + salt installed via pip in venv of unprivileged user

### Steps to Reproduce Issue
salt-ssh <minion with python 3.2, e.g. ubuntu 12.04>

```
salt@dev:~$ salt-ssh minion test.ping
minion:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "<string>", line 193, in <module>
          File "/usr/lib/python3.2/base64.py", line 83, in b64decode
            raise TypeError("expected bytes, not %s" % s.__class__.__name__)
        TypeError: expected bytes, not str
    stdout:
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.0
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 23 2017, 16:37:01)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-104-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by Ch3LL** [comment]
looks like these options will help ya out:

```
--python2-bin=PYTHON2_BIN
Path to a python2 binary which has salt installed.

--python3-bin=PYTHON3_BIN
Path to a python3 binary which has salt installed.
```

from https://docs.saltstack.com/en/latest/ref/cli/salt-ssh.html

**Comment by chschmitt** [comment]
Actually I tried those options and they had no effect. TBH, I do not know what the desired effect should be by looking at the documentation (which I did). Also, [this bit in in the ssh client](https://github.com/saltstack/salt/blob/66da9b47bcaada8f2e4d4876277065188fc80383/salt/client/ssh/__init__.py#L150) looks like the `--pythonX-bin` option newer makes into the generated shell script.

**Comment by Ch3LL** [comment]
ahh your right diving into the code it looks like this argument is used for generating the thin as you can see this PR that added the feature: https://github.com/saltstack/salt/pull/25772 and not for running the `salt-call` commands further down in the code.

ping @saltstack/team-ssh is there a way to customize the python interpreter for @chschmitt 's test case

**Comment by chschmitt** [comment]
Can I do anything to further the investigation of this issue?

**Comment by linora** [comment]
Does it seem that the issue has gone away? I met the same situation and was very disappointed with salt :(

**Comment by Ch3LL** [comment]
the closest thing i have found that has been added since i looked at this issue previously was this:

https://github.com/saltstack/salt/pull/46684

**Comment by jose1711** [comment]
not ideal but as a workaround you could modify a PATH env. variable in your salt user's profile on minion so that calling python executes your compiled Python

**Comment by aadityabagga** [comment]
@jose1711 thx for the idea, setting `$PATH` in `.bashrc` with python2.7 works!
