### ISSUE TITLE
Compounding nodegroups fails when listing in YAML format

### ISSUE THREAD

**Issue by Paulo-Nunes** [saltstack/salt#45334]
### Description of Issue/Question
Adding a nodegroup that references another nodegroup and uses compound matches can fail if the compounding happens on a YAML list line. (It might be possible that this is not limited to nodegroups)
It seems each list element is not treated as a compound.  If this is not a bug, then the documentation should be updated to make this clear.

The intent of the below nodegroup is to target all minions of a nodegroup, but then exclude some number of nodes from the group.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Nodegroups defined in /etc/salt/master.d/nodegroups.conf

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
**Fails:**
```
nodegroups:
  group1:
    - 'nodes*.com'
  group2:
    - 'N@group1 and not nodes3.com'

salt -N "group2" test.ping
[ERROR   ] Failed nodegroup expansion: unknown nodegroup "group2 and not nodes3.com"
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

**Succeeds:**
```
nodegroups:
  group1:
    - 'nodes*.com'
  group2: 'N@group1 and not nodes3.com'
```

**Also Succeeds:**
```
nodegroups:
  group1:
    - 'nodes*.com'
  group2:
    - 'N@group1'
    - 'not'
    - 'nodes3.com'
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.6.3.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
```

**Comment by rjc** [comment]
This issue should not have been closed - the problem is still there.
Is anyone working on/looking into this?

**Comment by Ch3LL** [comment]
no one is currently looking into this, please feel free to submit a fix.

**Comment by rjc** [comment]
Any reason why issues are being closed without actually being fixed?
