### ISSUE TITLE
fix salt-api doesn't dynamically re-read nodegroups configuration, plase check it for me.

### ISSUE THREAD

**Issue by zhuleiandy888** [saltstack/salt#45346]
[environment]
### Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
### 
----------------------------------------------------------------------
I have modified the salt - API code:  file_path: [/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py]
----------------------------------------------------------------------
`class LowDataAdapter(object):
    '''
    The primary entry point to Salt's REST API

    '''
    exposed = True

    _cp_config = {
        'tools.salt_token.on': True,
        'tools.sessions.on': True,
        'tools.sessions.timeout': 60 * 10,  # 10 hours

        # 'tools.autovary.on': True,

        'tools.hypermedia_out.on': True,
        'tools.hypermedia_in.on': True,
        'tools.lowdata_fmt.on': True,
        'tools.salt_ip_verify.on': True,
    }

    def __init__(self):
        #comment out code
        ##################################
        #**self.opts = cherrypy.config['saltopts']**
        #new added
        **self.opts = salt.config.client_config(os.environ.get('SALT_MASTER_CONFIG', '/etc/salt/master'))**
        ##################################
        self.apiopts = cherrypy.config['apiopts']
        self.api = salt.netapi.NetapiClient(self.opts)

    def exec_lowstate(self, client=None, token=None):
        '''
        Pull a Low State data structure from request and execute the low-data
        chunks through Salt. The low-data chunks will be updated to include the
        authorization token for the current session.
        '''
        #new added
        ##################################
        self.opts = salt.config.client_config(os.environ.get('SALT_MASTER_CONFIG', '/etc/salt/master'))
        ##################################
        lowstate = cherrypy.request.lowstate
        # Release the session lock before executing any potentially
        # long-running Salt commands. This allows different threads to execute
        # Salt commands concurrently without blocking.
        if cherrypy.request.config.get('tools.sessions.on', False):
            cherrypy.session.release_lock()

        # if the lowstate loaded isn't a list, lets notify the client
        if not isinstance(lowstate, list):
            raise cherrypy.HTTPError(400, 'Lowstates must be a list')

        if cherrypy.request.config.get('tools.sessions.on', False):
            cherrypy.session.release_lock()

        # if the lowstate loaded isn't a list, lets notify the client
        if not isinstance(lowstate, list):
            raise cherrypy.HTTPError(400, 'Lowstates must be a list')

        # Make any requested additions or modifications to each lowstate, then
        # execute each one and yield the result.
        for chunk in lowstate:
            if token:
                chunk['token'] = token
                if cherrypy.session.get('user'):
                    chunk['__current_eauth_user'] = cherrypy.session.get('user')
                if cherrypy.session.get('groups'):
                    chunk['__current_eauth_groups'] = cherrypy.session.get('groups')

            if client:
                chunk['client'] = client

            # Make any 'arg' params a list if not already.
            # This is largely to fix a deficiency in the urlencoded format.
            if 'arg' in chunk and not isinstance(chunk['arg'], list):
                chunk['arg'] = [chunk['arg']]
            #new added
            ##################################
            **self.api = salt.netapi.NetapiClient(self.opts)**
            ##################################
            ret = self.api.run(chunk)

            # Sometimes Salt gives us a return and sometimes an iterator
            if isinstance(ret, collections.Iterator):
                for i in ret:
                    yield i
            else:
                yield ret`
----------------------------------------------------------------------
Each request salt - API to re-read the master configuration file,  then salt-api can dynamically re-read nodegroups configuration, after  test, almost no loss performance.  is it ok？ like this. 

If no problem I'm going to apply to the production environment

thank you very much!

**Comment by Ch3LL** [comment]
ping @gtmanfred any insight you can give for @zhuleiandy888 on this code ?

**Comment by gtmanfred** [comment]
It is going to be slower, because it will have to reload the config on each run.

The other thing is I am not sure this is going to work, because I believe all the api does is pass the nodegroups over to the master, and the master requires a reboot in order to pick up new or changed nodegroups.  Unless you change the api to expand the nodegroup, and then pass that expanded matching to the master.

**Comment by zhuleiandy888** [comment]
@gtmanfred    Thanks a lot !
   As you said, it‘s true it's going to be slower. After many tests, speed will at least one times slower. but so far, the service is  running normally. 
 Another question:
   

> "and the master requires a reboot in order to pick up new or changed  nodegroups"

It means that the master requires a reboot,  when the nodegroups have new or changed. is it right?
the "reboot" is not real to  restart the master service, is it right?   
In the fact, when i have modified and saved in the "nodegroups.conf", the salt-master service can apply the modified and saved immediately(use CLI mode), however, the salt-master service does not restart. but, the salt-api must restart service. otherwise, the API will get a error info like below:

`{u'status': 500, u'return': u'Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 744, in hypermedia_handler\n    ret = cherrypy.serving.request._hypermedia_inner_handler(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/cherrypy/_cpdispatch.py", line 60, in __call__\n    return self.callable(*self.args, **self.kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 1181, in POST\n    token=cherrypy.session.get(\'token\')))\n  File "/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py", line 1073, in exec_lowstate\n    ret = self.api.run(chunk)\n  File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 75, in run\n    return l_fun(*f_call.get(\'args\', ()), **f_call.get(\'kwargs\', {}))\n  File "/usr/lib/python2.7/site-packages/salt/netapi/__init__.py", line 103, in local\n    return local.cmd(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 723, in cmd\n    **kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 344, in run_job\n    raise SaltClientError(general_exception)\nSaltClientError: Node group web4 unavailable in /etc/salt/master\n'}`
    
I will continue to test.  do you have any other solution or a plan?
We don't have a high performance requirement now, so,it's enough for us.

thanks again !

**Comment by gtmanfred** [comment]
Yes, sorry, i meant that the master will need to be restarted.

This is what really needs to happen in order to be able to really support this in upstream.

https://github.com/saltstack/salt/issues/570

A SIGHUP to the parent process could be caught and all of the multiprocesses could be told to pick up the new config.

**Comment by zhuleiandy888** [comment]
@gtmanfred  thanks!   
#570 , I think that cann't solve salt-api dynamically re-read nodegroups configuration, via to restart salt-master  service or re-read configuration. (I've tested)

 Whatever whether salt-master restart or re-read, the salt-api service cann't apply the new or changed. 
 Unless you restart the salt-api service. (I've tested)

I optimized the code again: file_path: [/usr/lib/python2.7/site-packages/salt/netapi/rest_cherrypy/app.py]

> `def exec_lowstate(self, client=None, token=None):

        lowstate = cherrypy.request.lowstate
        #new added
        #################################
        if len(lowstate) > 0:
            raw_argv_dict = lowstate[0]
            if raw_argv_dict.has_key("tgt_type") and raw_argv_dict["tgt_type"] == 'nodegroup':
                self.opts = salt.config.client_config(os.environ.get('SALT_MASTER_CONFIG', '/etc/salt/master'))
                self.api = salt.netapi.NetapiClient(self.opts)
        #################################
        # Release the session lock before executing any potentially
        # long-running Salt commands. This allows different threads to execute
        # Salt commands concurrently without blocking.
        if cherrypy.request.config.get('tools.sessions.on', False):
            cherrypy.session.release_lock()

        # if the lowstate loaded isn't a list, lets notify the client
        if not isinstance(lowstate, list):
            raise cherrypy.HTTPError(400, 'Lowstates must be a list')

        # Make any requested additions or modifications to each lowstate, then
        # execute each one and yield the result.
        for chunk in lowstate:
            if token:
                chunk['token'] = token
                if cherrypy.session.get('user'):
                    chunk['__current_eauth_user'] = cherrypy.session.get('user')
                if cherrypy.session.get('groups'):
                    chunk['__current_eauth_groups'] = cherrypy.session.get('groups')

            if client:
                chunk['client'] = client

            # Make any 'arg' params a list if not already.
            # This is largely to fix a deficiency in the urlencoded format.
            if 'arg' in chunk and not isinstance(chunk['arg'], list):
                chunk['arg'] = [chunk['arg']]
            ret = self.api.run(chunk)

            # Sometimes Salt gives us a return and sometimes an iterator
            if isinstance(ret, collections.Iterator):
                for i in ret:
                    yield i
            else:
                yield ret`

Only "tgt_type" is "nodegroup" to re-read the master configuration file, Of course, there are other solutions. for example: to check "nodegroup.conf" file MD5 , only it had a changed to re-read configuration file, and so on.
