### ISSUE TITLE
win_wua.install never actually succeeds

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#45356]
### Description of Issue/Question
Attempting to install Windows Updates via `win_wua.install` **always** fails. 

### Setup
No special setup needed.

### Steps to Reproduce Issue
using `win_wua.install`, regardless of the method of installation (KB name, Update ID, or other), you will always encounter this (seen here executed via `module.run` in a state, but the same thing happens directly from the CLI):
```
          ID: win_wua_cmd
    Function: module.run
        Name: win_wua.install
      Result: True
     Comment: Module function win_wua.install executed
     Started: 13:43:24.359000
    Duration: 7421.0 ms
     Changes:   
              ----------
              ret:
                  ----------
                  Message:
                      Installation Failed
                  Success:
                      False
                  Updates:
                      ----------
                      2bfa71e7-6250-43da-af99-b7c2d9ccb469:
                          ----------
                          AlreadyInstalled:
                              False
                          RebootBehavior:
                              Poss Reboot
                          Result:
                              Installation Failed
                          Title:
                              2018-01 Cumulative Update for Windows 10 Version 1709 for x64-based Systems (KB4056892)
```
I have never seen this succeed on any machine, ever, regardless of build version. Granted, I only have Windows 10 to test with, so maybe it works on Vista or something.

### Versions Report
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: 11.2.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.25.1
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.2.0-042stab111.11
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by V3XATI0N** [comment]
also it still returns with `Result: True` which is annoying, since it clearly fails.

**Comment by garethgreenaway** [comment]
@twangboy Thoughts on this one?

**Comment by twangboy** [comment]
There are a couple things I'd try here...

First, make sure the update will install on the actual machine outside of salt... just run Windows update and apply the changes

Second, try using the wua state:
```
install_kb4056892:
  wua.installed:
    - name: KB4056892
```

**Comment by V3XATI0N** [comment]
Both do fail, indeed. The output of the state:
```
----------
          ID: win_wua_cmd
    Function: wua.installed
        Name: 2bfa71e7-6250-43da-af99-b7c2d9ccb469
      Result: False
     Comment: Updates failed
     Started: 10:34:45.867000
    Duration: 103520.0 ms
     Changes:   
              ----------
              failed:
                  ----------
                  2bfa71e7-6250-43da-af99-b7c2d9ccb469:
                      ----------
                      KBs:
                          - KB4056892
                      Title:
                          2018-01 Cumulative Update for Windows 10...
```

**Comment by twangboy** [comment]
OK. The state is failing because Windows update is failing. Since salt leverages the local Windows update on the machine, you'll have to figure out what's going on there. Once that's resolved, then the state will work.

**Comment by garethgreenaway** [comment]
@twangboy Are we able to get any feedback to use inside the module and state, so we're able to provide that feedback to the user when the updates fail?

**Comment by twangboy** [comment]
@garethgreenaway Sure

**Comment by V3XATI0N** [comment]
I have a feeling that the reason the update fails is because people never reboot their Windows machines. I also realize that Salt is intended more for server management than, say, endpoint management, so such concerns would naturally be less of a priority (assuming server admins know what they are doing). Still, if it's possible for Salt to determine anything about the reason *why* the update failed (pending reboot, update not relevant for Windows version/CPU architecture, etc.), it would be awesome if it could pass such information along in the error message.

**Comment by twangboy** [comment]
@V3XATI0N We could use `win_wua.get_needs_reboot` which is a wrapper for a salt util that will tell you if the machine needs to be rebooted...

**Comment by V3XATI0N** [comment]
I'm mainly frustrated by the fact that Windows Update is a horrible, unreliable heap of garbage that only barely works to begin with. My apologies if I seem short toward Salt developers. `win_wua.get_needs_reboot` is a nice thing to have around, but the majority of these don't fail for that reason. More often, something has gone haywire in the update index or the wuauserv service has decided to stop working altogether for one of ten million reasons. Anyway, as I said, I have never actually seen `win_wua.install` or `wua.installed` _succeed_, even when `Get-WindowsUpdate/Get-WUInstall` or `wusa.exe` does work.
