### ISSUE TITLE
Windows cmd execute "echo %date%" diffent with cmd.run "echo %date%"

### ISSUE THREAD

**Issue by qiangshui** [saltstack/salt#45366]
### Description of Issue/Question
I executed command "echo %date%" in Windows server cmd, its result is different with cmd.run 
### Setup

![default](https://user-images.githubusercontent.com/24819310/34772696-ec2aedf0-f643-11e7-99a0-2205c2cbca16.png)

![default](https://user-images.githubusercontent.com/24819310/34772682-dc83e94c-f643-11e7-9c5a-6476b6d593f8.png)

the chinese "周三" means Wednesday，in the cmd，it's in the end of the line,and in salt cmd.run,it's in the beginning of the line.
### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final

**Comment by garethgreenaway** [comment]
Seems this might be related to the various unicode issues that we're aware of and have several efforts ongoing to fix.
