### ISSUE TITLE
Grain refresh not working on compound command execution

### ISSUE THREAD

**Issue by cavalheiro** [saltstack/salt#45373]
### Description of Issue/Question

Whenever saltutil.refresh_grains is called as part of compound command execution, the other commands won't see the refreshed grains.

What we were able to observe so far is that the Salt minion creates a sub-process to handle those executions, and in case of grain refresh, the sub process is not performing the refresh itself, but signaling the parent to do so. The refreshed grains are not sent back to the sub process, and therefore the next operation on the compound command won't see the updated values.

### Setup

N/A

### Steps to Reproduce Issue

Change some info that is collected by the grains, ex: /etc/os-release and run:
```salt 'minion' saltutil.refresh_grains,grains.items '',''```

Same happens while applying a state with similar behaviour, like:
```
grtest:
  module.run:
   - name: saltutil.refresh_grains

grtest2:
  module.run: 
   - name: grains.items
```

### Versions Report

Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 4.4.21-69-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by garethgreenaway** [comment]
@cavalheiro Thanks for the report.  I was able to duplicate it and it looks like there are different results between using `salt` vs `salt-call`, salt-call gives the expected results.

**Comment by cavalheiro** [comment]
Thanks for the feedback! AFAIK this does not happen with `salt-call` because it spawns a completely different process and that forces a reload of grain-related information from disk. In fact if you change something that affects the grains and run a simple `salt-call grains.items` it will always return the correct values.

**Comment by cavalheiro** [comment]
Will this be fixed as part of next release?

**Comment by rallytime** [comment]
@garethgreenaway Can you take a look at this one when you have a moment?

**Comment by garethgreenaway** [comment]
Spent some time looking at this one it turns out if's an easy fix.  Using the `reload_grains` option in the state file after the call to `saltutil.refresh_grains` will accomplish the desired goal.

```
grtest:
  module.run:
   - name: saltutil.refresh_grains
   - reload_grains: true

grtest2:
  module.run: 
   - name: grains.items
```

**Comment by cavalheiro** [comment]
Thanks!

I would to suggest a documentation update on https://docs.saltstack.com/en/latest/ref/states/requisites.html#reload to make this option more clear
