### ISSUE TITLE
git.latest fails when "depth"  is used with a non-default branch

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#45394]
### Description of Issue/Question
Documentation states that can use git.latest with depth when rev is set to a branch, but fails in error.

### Setup
test_download.sls

{% set specific_user = 'saltstack' %}
{% set tmp_dir = '/tmp/salt_dir' %}
## {# {% set branch_checkout = 'develop' %} #}
{% set branch_checkout = '2017.7' %}

remove_version_tmp_dir:
  file.absent:
    - name: {{tmp_dir}}

create_dir:
  file.directory:
    - name: {{tmp_dir}}
    - user: root
    - dir_mode: 755
    - file_mode: 644
    - makedirs: True

retrieve_desired_salt:
  git.latest:
    - name: https://github.com/{{specific_user}}/salt.git
    - target: {{tmp_dir}}
    - rev: {{branch_checkout}}
    - user: root
    - force_clone: True
    - force_fetch: True
    - force_reset: True
    - depth: 1

### Steps to Reproduce Issue
salt <minion> state.sls test_download

Log file output:
  344 retrieve_desired_salt:
  345   git.latest:
  346     - name: https://github.com/saltstack/salt.git
  347     - target: /root/salt_dir
  348     - rev: 2017.7
  349     - user: root
  350     - force_clone: True
  351     - force_reset: True
  352     - depth: 1
  353 

37200 2018-01-11 18:08:48,077 [salt.loaded.int.module.cmdmod:388 ][INFO    ][4282] Executing command ['git', 'clone', '--depth', '1', '--', 'https://github.com/saltstack/salt.git', '/root/salt_dir'] as user 'root' in dire      ctory '/tmp'
37201 2018-01-11 18:08:56,188 [salt.loaded.int.module.cmdmod:1717][DEBUG   ][4282] stdout: Cloning into '/root/salt_dir'...
37202 2018-01-11 18:08:56,190 [salt.loaded.int.states.git:115 ][INFO    ][4282] Checking local revision for /root/salt_dir
37203 2018-01-11 18:08:56,198 [salt.loaded.int.module.cmdmod:388 ][INFO    ][4282] Executing command ['git', 'rev-parse', 'HEAD'] as user 'root' in directory '/root/salt_dir'
37204 2018-01-11 18:08:56,298 [salt.loaded.int.module.cmdmod:1717][DEBUG   ][4282] stdout: efc75677e108bbc17a9ead6812f65627582be0f7
37205 2018-01-11 18:08:56,299 [salt.loaded.int.states.git:125 ][INFO    ][4282] Checking local branch for /root/salt_dir
37206 2018-01-11 18:08:56,300 [salt.loaded.int.module.cmdmod:388 ][INFO    ][4282] Executing command ['git', 'rev-parse', '--abbrev-ref', 'HEAD'] as user 'root' in directory '/root/salt_dir'
37207 2018-01-11 18:08:56,380 [salt.loaded.int.module.cmdmod:1717][DEBUG   ][4282] stdout: develop
37208 2018-01-11 18:08:56,387 [salt.loaded.int.module.cmdmod:388 ][INFO    ][4282] Executing command ['git', 'reset', '--hard', 'f77a3e9cd4bc1dd6677e69cbb07fa7e06b3c2d72'] as user 'root' in directory '/root/salt_dir'
37209 2018-01-11 18:08:56,483 [salt.loaded.int.module.cmdmod:1715][ERROR   ][4282] Command '['git', 'reset', '--hard', 'f77a3e9cd4bc1dd6677e69cbb07fa7e06b3c2d72']' failed with return code: 128
37210 2018-01-11 18:08:56,484 [salt.loaded.int.module.cmdmod:1719][ERROR   ][4282] stderr: fatal: Could not parse object 'f77a3e9cd4bc1dd6677e69cbb07fa7e06b3c2d72'.
37211 2018-01-11 18:08:56,485 [salt.loaded.int.module.cmdmod:1721][ERROR   ][4282] retcode: 128
37212 2018-01-11 18:08:56,485 [salt.loaded.int.states.git:1857][ERROR   ][4282] Unexpected exception in git.latest state
37213 Traceback (most recent call last):
37214   File "/usr/lib/python2.7/site-packages/salt/states/git.py", line 1768, in latest
37215     password=password)
37216   File "/usr/lib/python2.7/site-packages/salt/modules/git.py", line 3767, in reset
37217     ignore_retcode=ignore_retcode)['stdout']
37218   File "/usr/lib/python2.7/site-packages/salt/modules/git.py", line 366, in _git_run
37219     raise CommandExecutionError(msg)
37220 CommandExecutionError: Command 'git reset --hard f77a3e9cd4bc1dd6677e69cbb07fa7e06b3c2d72' failed: fatal: Could not parse object 'f77a3e9cd4bc1dd6677e69cbb07fa7e06b3c2d72'.
37221 2018-01-11 18:08:56,504 [salt.state       :275 ][ERROR   ][4282] {'forced clone': True, 'new': 'https://github.com/saltstack/salt.git => /root/salt_dir'}

### Versions Report
Salt Version:
           Salt: 2017.7.0-n/a-8e14bc3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
 
Found during speed up of automated packaging, increasing speed of git checkouts

**Comment by terminalmage** [comment]
Fixed in #45399.
