### ISSUE TITLE
Documentation about cp.push is out of date.  It is not supported in 2015.5.10 and should be documented as such.

### ISSUE THREAD

**Issue by Laserwhit** [saltstack/salt#45391]
### Description of Issue/Question
I spent a several hours trying to get cp.push to work between master version 2017.7.0 and minion version 2015.5.10.  The documentation (https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html) seems to indicate that this should work with one comment indicating that the remove_resource parameter is new in version 2016.3.0.  But after working hours to get this to work I found issue #37133 in your github repo(https://github.com/saltstack/salt/issues/37133 .)  I read that you DO NOT support 2015.5.10 anymore!  Your documentation does not indicate this and it would be nice to know this up front before putting in precious time to get this working.  I'm hoping you can document this better.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Create the setup mentioned (master 2017.7.0 and minion 2015.5.10) and then make sure that you have set file_recv: True in the master config on the master and that it is properly restarted.  Next on the minion run: python -c "import salt.config; print salt.config.client_config('/etc/salt/master').get('file_recv')"
and see that it always returns False.  You can also run a simple cp.push from either the master or using salt-call on the minion and it will fail as well.  Here is a debug output of the call:
salt ourminion cp.push /tmp/tmp/afile  -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /opt/salt/var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /opt/salt/var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/opt/salt/etc/salt/pki/master', 'ourmaster_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /opt/salt/var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /opt/salt/var/cache/salt/master/jobs/b7/23a1977256f13f64d4a996d5dead7dd12af600f724838d607b5130f77eabce/.minions.p
[DEBUG   ] get_iter_returns for jid 20180111094315662214 sent to set(['ourminion']) will timeout at 09:43:20.674051
[DEBUG   ] jid 20180111094315662214 return from <minion>
[DEBUG   ] return event: {'ourminion': {'jid': '20180111094315662214', 'retcode': 0, 'ret': False}}
[DEBUG   ] LazyLoaded nested.output
ourminion:
    False
[DEBUG   ] jid 20180111094315662214 found all minions set(['ourminion'])

### Versions Report
 salt-minion --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.8
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 1.5
******************************************
salt --versions-report
Salt Version:
           Salt: 2017.7.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
******************************

**Comment by Laserwhit** [comment]
After rereading the issue that I referenced above #37133, I realize that my title might be misleading.  Either you do support 2015.5.10 but not the 2015 versions talked about at the end of #37133, in which case my issue here is a real issue and not just a documentation issue, or you don't support 2015.5.10 and this is still a valid documentation issue.  Either way we need resolution.

**Comment by gtmanfred** [comment]
Here is our doc on what version is supported for patching.

https://saltstack.com/product-support-lifecycle/

2015.5 will never receive any more patches

I am going to mark this as a documentation issue, that docs need to be added about cp.push not working between minions older than 2015.5 and masters newer than 2017.7
