### ISSUE TITLE
win_path.exists should not change given entry to lowercase

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#45409]
### Description of Issue/Question
Adding a directory to the Windows %PATH% using win_path.exists changes the given PATH entry to lowercase. Please stop doing that.

### Setup
```
add_to_path:
  win_path.exists:
    - name: 'C:\Some\Directory'
```
is added to %PATH% as *c:\some\directory*.

### Steps to Reproduce Issue
Apply above state.

### Versions Report
2017.7.2 on both master and (Windows) minion.

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows can i get some input here. Seems like an easy fix. Not sure if there is a reason we are moving it to lowercase though.

**Comment by twangboy** [comment]
It's probably doing a comparison to see if the path already exists in %PATH%. Though Windows itself is not case sensitive, python is, so it probably uses `.lower()` to make the comparison. I can take a look at this. I don't like that it changes the capitalization either. It should be able to do that comparison and make the changes without modifying the existing entries.

**Comment by dhs-rec** [comment]
@lorengordon, no it's not cosmetic. If Salt changes things at will, it can't be trusted. Also think about automated tests to verify that the provisioned box is in the desired state.
@twangboy, thanks.

**Comment by twangboy** [comment]
@dhs-rec I don't understand your `it can't be trusted` comment. Since path is a single text field, the only way to add a path is to change it. Even if you aren't changing capitalization, you're still writing the entire path.

**Comment by dhs-rec** [comment]
What I mean is: If it changes a simple thing like path capitalization at will, are there other places where it does unwanted changes?

**Comment by terminalmage** [comment]
> Also think about automated tests to verify that the provisioned box is in the desired state.

There were tests, they were just written to confirm the incorrect path normalization behavior. This is fixed as part of https://github.com/saltstack/salt/pull/45703.
