### ISSUE TITLE
salt.modules.cmdmod.powershell password documentation is incorrect

### ISSUE THREAD

**Issue by davejhahn** [saltstack/salt#45417]
I was using 2016.11 previously and upgraded to 2017.7.  After this, my states with PowerShell calls using "runas" and "password" started failing with "Module function cmd.exec_code threw an exception. Exception: password is a required argument for runas on Windows"

It could have been that the username / password was always ignored previously (even though I thought it was being used), regardless after reviewing the python module it shows "runas_password" as the parameter name, but the documentation sows "password" (see documentation here: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html) 

After changing my state to use "runas_password" instead of "password" fixed my problem.

This does not work:
environmentVariable_{{loop.index}}:
  module.run:
    - name: cmd.exec_code
    - lang: powershell
    - code: '[Environment]::SetEnvironmentVariable("{{env.key}}","{{env.value}}","{{env.level}}")'
    - runas: <SECRETUSER>
    - password: <SECRETPASS>

This does work:
environmentVariable_{{loop.index}}:
  module.run:
    - name: cmd.exec_code
    - lang: powershell
    - code: '[Environment]::SetEnvironmentVariable("{{env.key}}","{{env.value}}","{{env.level}}")'
    - runas: <SECRETUSER>
    - runas_password: <SECRETPASS>

Suggest updating the documentation to reflect the correct parameter name for password.

Thanks!

**Comment by damon-atkins** [comment]
Other doco issue for cmdmod #45193
