### ISSUE TITLE
[FEATURE] Salt should take common parameters from a user RC file like $HOME/.salt/saltrc

### ISSUE THREAD

**Issue by czee** [saltstack/salt#4542]
Currently all options to salt are taken from the command line, however it would be far more efficient and practical to optionally take all of these from a client_acl enabled user's RC file in YAML format. It should be available for root too. Perhaps this file could be stored in $HOME/.salt/saltrc falling back to $HOME/.saltrc when the former is not present.

This $HOME/.salt/ directory could also hold future files and data for the named user. Some ideas for extra options which could be taken from the command line and in the RC file include:
- A pager that takes environment variables and options from a program like less:

```
formatting:
      - pager: LESS='FSRX' less
      - fd: single
```

Now we know the user requests that output from salt should be displayed through less, so they don't have to scroll up when reading. An added bonus here would be sending output from targets to multiple FD's so that less can then switch cleanly between the FD's with :n and :1, :2, :3, etc...

```
formatting:
      - pager: LESS='FSRX' less
      - fd: multiple
```
- Additionally logging of salt output should be possible and so should a directory/file specification on where to log to:

```
logging:
      - file.directory: ~/.salt/log
      - format: %h-%m-%M-%Y.log
```

or

```
logging:
      - file.managed: ~/.salt/log
      - format: %h-%m-%M-%Y.log
```

**Comment by obestwalter** [comment]
No - I just stumbled over this line in the logs

    [DEBUG   ] Missing configuration file: ~/.saltrc

and started searching for it to see how this can make my configuration live easier - no docs yet.

**Comment by obestwalter** [comment]
I also find it confusing that it's milestone approved but that progress thingy is only halfway done, although it is released alread since 2014.1.whenever ...

**Comment by cachedout** [comment]
To the best of my recollection much of the `.saltrc` work was done in a sprint by @justincarmony.

**Comment by JustinCarmony** [comment]
Hrm, the work I did was with Saltfiles & salt-ssh: http://docs.saltstack.com/en/latest/topics/ssh/#define-cli-options-with-saltfile

**Comment by gravyboat** [comment]
@jfindlay Could we get this re-opened since it doesn't seem implemented, or if it is, its' not documented in any way that I can find.

**Comment by pgporada** [comment]
I just saw `[DEBUG   ] Missing configuration file: ~/.saltrc` in my debug output on 2016.11.4

**Comment by cachedout** [comment]
@pgporada I'm not sure why that would be a problem?

**Comment by pgporada** [comment]
Ah, I don't think the debug comment is a problem. I failed to articulate, "What can I put in this ~/.saltrc?"

**Comment by UtahDave** [comment]
I added the following to `~/.saltrc`

```
output: json
```

And now I get the following on the cli

```
[boucha@elsapo ~]$ sudo salt \* test.ping
{
    "dasalt": true
}
{
    "cent6test": "Minion did not return. [Not connected]"
}
```

It appears that the `~/.saltrc` has to be valid yaml. Is this just for key/value pairs that you would normally use on the command line? I'm not sure how to put in options like `--summary`
