### ISSUE TITLE
winrepo-ng fault pkg.refresh_db doesn't work - it processes ANY stray .git metadata *.sls files present on minion

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#45432]
### Description of Issue/Question
@twangboy  @damon-atkins I think there is a general fault or corruption in the official winrepo-ng software definition files repo that keeps them from compiling. ( or is it just on my system? and I need to clear a somehow cached 'bad' repo db ? )

So as a consequence of that ```NO``` ```pkg.refresh_db``` or ```pkg.list_upgrades``` or ```pkg.install``` or ```pkg.remove``` cmd works.

This looks and acts very much like back in Nov 2016 when issue  https://github.com/saltstack/salt/issues/37669 was breaking the official repo with  a single new malformed sls file. I know lots has been done to prevent this from happening, but it looks to me as if a very similar thing has happened again.

### Setup
This happens on centos 7 linux, master or windows minions all running 2017.7.2 (Nitrogen)

### Steps to Reproduce Issue
```
salt my_win_minion pkg.refresh_db
mywin_minion:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 605, in refresh_db
        return genrepo(saltenv=saltenv, verbose=verbose, failhard=failhard)
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 761, in genrepo
        successful_verbose
      File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 829, in _repo_process_pkg_sls
        for pkgname, versions in six.iteritems(config):
      File "c:\salt\bin\lib\site-packages\salt\ext\six.py", line 606, in iteritems
        return d.iteritems(**kw)
    AttributeError: 'str' object has no attribute 'iteritems'
```

(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by TheBigBear** [comment]
@twangboy @damon-atkins I think I must be missing something 'obvious' ?

Fro testing and diagnositc purposes I have reverted my winrepo-ng repo back to before the recent commits to a time where I know it was all fine and dandy and worked.

But even when the repo is back at that earlier and known 'good' state, I still get the above error. 

Now seeing that the salt software version has not changed on master nor on the windows minion and the winrepo-ng repo is back on a state where it used to work, makes me think there is some residual data somewhere in a cache or something that is corrupt and until it is cleared I cannot run a successfull pkg db operation.

I have tried running ```saltutil.clear_cache``` and ```saltutil.sync_all``` but the ```pkg.refres_db``` still fails as above. What am I missing?

**Comment by TheBigBear** [comment]
OK, I am getting somewhere ... this is a really strange issue.

It turns out that ```pkg.refresh_db``` appears to be recursively processing ALL *.sls files under the windows minions ```c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\``` INCLUDING any *.sls files under the ```.git``` directory there 
i.e. ```c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\.git\``` 

So the specific issue that stops the dictionary build is:

output of ```salt uk-it-20 pkg.refresh_db```:
< cut some >
```
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\yubikey-personalization-tool.sls:
yubikey-personalization-tool:
  3.1.24:
    full_name: 'YubiKey Personalization Tool'
    installer: 'https://developers.yubico.com/yubikey-personalization-gui/Releases/yubikey-personalization-gui-3.1.24.exe'
    install_flags: '/S'
    uninstaller: "C:\\Program Files (x86)\\Yubico\\YubiKey Personalization Tool\\uninstall.exe"
    uninstall_flags: '/S'
    reboot: False
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('yubikey-personalization-tool', OrderedDict([('3.1.24', OrderedDict([('full_name', 'YubiKey Personalization Tool'), ('installer', 'https://developers.yubico.com/yubikey-personalization-gui/Releases/yubikey-personalization-gui-3.1.24.exe'), ('install_flags', '/S'), ('uninstaller', 'C:\\Program Files (x86)\\Yubico\\YubiKey Personalization Tool\\uninstall.exe'), ('uninstall_flags', '/S'), ('reboot', False)]))]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\yubikey-personalization-tool.sls' using 'yaml' renderer: 0.0939998626709
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\.git\logs\refs\remotes\origin\TheBigBear-create-initial-staywake-init.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
```
and here it descends recursively into the ```.git``` directory
```
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\.git\logs\refs\remotes\origin\TheBigBear-create-initial-staywake-init.sls' using 'jinja' renderer: 0.0
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\.git\logs\refs\remotes\origin\TheBigBear-create-initial-staywake-init.sls:
0000000000000000000000000000000000000000 26b394899eacf3750efdc075fbc3064c7c2aade9 root <root@uk-monitor-1.uk.om.org> 1515778595 +0000	pull: storing head
[ERROR   ] Failed to compile 'salt-winrepo-ng\.git\logs\refs\remotes\origin\TheBigBear-create-initial-staywake-init.sls': Illegal tab character; line 1

---
0000000000000000000000000000000000000000 26b394899eacf3750efdc075fbc3064c7c2aade9 root <root@uk-monitor-1> 1515778595 +0000	pull: storing head     <======================
---
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\.git\refs\remotes\origin\TheBigBear-create-initial-staywake-init.sls
[DEBUG   ] Jinja search path: ['c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\.git\refs\remotes\origin\TheBigBear-create-initial-staywake-init.sls' using 'jinja' renderer: 0.0
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\.git\refs\remotes\origin\TheBigBear-create-initial-staywake-init.sls:
26b394899eacf3750efdc075fbc3064c7c2aade9
[DEBUG   ] Results of YAML rendering: 
26b394899eacf3750efdc075fbc3064c7c2aade9
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\.git\refs\remotes\origin\TheBigBear-create-initial-staywake-init.sls' using 'yaml' renderer: 0.0160000324249
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'str' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 391, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 605, in refresh_db
    return genrepo(saltenv=saltenv, verbose=verbose, failhard=failhard)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 761, in genrepo
    successful_verbose
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 829, in _repo_process_pkg_sls
    for pkgname, versions in six.iteritems(config):
  File "C:\salt\bin\lib\site-packages\salt\ext\six.py", line 606, in iteritems
    return d.iteritems(**kw)
AttributeError: 'str' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "C:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "C:\salt\bin\lib\site-packages\salt\scripts.py", line 391, in salt_call
    client.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "C:\salt\bin\lib\site-packages\salt\cli\caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 605, in refresh_db
    return genrepo(saltenv=saltenv, verbose=verbose, failhard=failhard)
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 761, in genrepo
    successful_verbose
  File "C:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 829, in _repo_process_pkg_sls
    for pkgname, versions in six.iteritems(config):
  File "C:\salt\bin\lib\site-packages\salt\ext\six.py", line 606, in iteritems
    return d.iteritems(**kw)
AttributeError: 'str' object has no attribute 'iteritems'

```

The ```.git file```: 
```c:\salt\var\cache\salt\minion\files\base\win\repo-ng\salt-winrepo-ng\.git\logs\refs\remotes\origin\TheBigBear-create-initial-staywake-init.sls``` is a git housekeeping file. that basically starts with a hash.

@twangboy Please change the winrepo-ng code to stop and NOT process and try to render any 'sls' files anywhere under a ```.git``` metadata housekeeping directory.

Please send me any ```diff``` or a PR to my salt repo for me to test and see that it works.

The confusing part to me is that if I treat the windows master as if it was masterless and issue a 
```salt-call --local pkg.refresh_db``` after having done a update_git_repos cmd before, it compiles the dictionary just fine and completes without an error. Even on the same windows minion that has this stray ```.git``` metadata housekeeping ```*.sls``` file on it. But without the ```--local``` flag it pulls code of the master and processes the 'same' files and fails and stumbles over the stray ```*.sls``` named file in the .git metadata dir.

**Comment by damon-atkins** [comment]
TheBigBear Please try the latest 2016.11 code however.  (or wait for it to reach 2017.x)  If it its a bad sls file it should just keep going and give you a report that it failed, unless your force the error to happen.  For example oxygen can not process the skype sls definition as it has a copy right character or a trade mark character but it keeps going and gives the report.  Salt team are still updating heaps of files to support Unicode.

So why is the .git in this location?  Did it come from the master?  Should file listing coming from the master skip .git by default? (i.e. filtered at the master)

The new version which I have not release still supports the sls files but new format uses .slp file names instead.

**Comment by TheBigBear** [comment]
@damon-atkins thanks for feedback. 
Sorry my master and all my clients are on 2017.x so don't dare downgrade. I thought latest code was on either 2017.x or dev? Obviously not ...

Yeah I agree I expected it to simply ignore bad sls files and get on with the job, and in fact I know it does just that with some of the files it doesn't like, (like the duplicity one) but this particular stray ```'.git'``` metadata file seems sofar fetched from what it expects that is still blows the whole process. Can I send it you for you to test it in your latest 2016.11 tree sticking it in the sls directory (for testing it it is not necessary to have it in ```'.git'``` su directory, simply  to check if it manages to blow the jinjna rendering logic?

I did no manually put it there. It either gets there from the master, or maybe if I run the local windows minion with ```'--local'``` in ```'salt-call winrepo.update_git_repos'```? But either way, the jinja sls pkg.refresh_db rendering dictionary building code should definitely be stopped from recursing into any existing ```'.git'``` subdirectory. Regardless if the file of the day is now called ```'*.sls'``` or ```'*.slp'```? Don't you think so?

BTW what python file should I peek and and see if I can figure out how to stop it descending into ```'.git'``` subdirectories? ( I am not 'really' a python coder - but always wanting to stretch my abilities and seeking to learn and expand my skills )  

Can I please see/read more details on the move from ```'*.sls'``` to ```'*.slp'``` files? ( Very first I hear of it, sorry.  I am immediately thinking of the current winrepo-ng and what it would mean with regards to it? ( it needs hours - weeks even - of cleaning up .... as-is )
Last time in going from winrepo to winrepo-ng format of it ( adding jinja support ) they insisted that they did not want to ```'version'``` the ```'sls'``` software definition files, saying it would be a once in a lifetime switch and then would forever stay in the new jinja format .... Maybe we need to learn from past and pains and bad decisions and improve on some of those infrastructure decisions ?

**Comment by TheBigBear** [comment]
@damon-atkins my stray ```'.git'``` metadata file looked like this, it basically had a single hash in it:
```'TheBigBear-create-initial-staywake-init.sls'```:
```26b394899eacf3750efdc075fbc3064c7c2aade9```

**Comment by damon-atkins** [comment]
From read what you said its the fact that the file is not in the correct format at all.
Your saying its just a line e.g.
something.sls containing will break it.
```
this-is-a-line
```

@saltstack/team-core could someone look at why this is not error the render.

Either the render should have reported as issue or we need to trap Attribute error before starting the loop.
for pkgname, versions in six.iteritems(config):

**Comment by TheBigBear** [comment]
@damon-atkins thanks, cool.
this results in:
```
[ERROR   ] data:26b394899eacf3750efdc075fbc3064c7c2aade9 type:<type 'str'>
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
AttributeError: 'str' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 391, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 605, in refresh_db
    return genrepo(saltenv=saltenv, verbose=verbose, failhard=failhard)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 761, in genrepo
    successful_verbose
  File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 830, in _repo_process_pkg_sls
    for pkgname, versions in six.iteritems(config):
  File "c:\salt\bin\lib\site-packages\salt\ext\six.py", line 606, in iteritems
    return d.iteritems(**kw)
AttributeError: 'str' object has no attribute 'iteritems'
Traceback (most recent call last):
  File "c:\salt\bin\Scripts\salt-call", line 11, in <module>
    salt_call()
  File "c:\salt\bin\lib\site-packages\salt\scripts.py", line 391, in salt_call
    client.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\call.py", line 58, in run
    caller.run()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 134, in run
    ret = self.call()
  File "c:\salt\bin\lib\site-packages\salt\cli\caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 605, in refresh_db
    return genrepo(saltenv=saltenv, verbose=verbose, failhard=failhard)
  File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 761, in genrepo
    successful_verbose
  File "c:\salt\bin\lib\site-packages\salt\modules\win_pkg.py", line 830, in _repo_process_pkg_sls
    for pkgname, versions in six.iteritems(config):
  File "c:\salt\bin\lib\site-packages\salt\ext\six.py", line 606, in iteritems
    return d.iteritems(**kw)
AttributeError: 'str' object has no attribute 'iteritems'
```
it does not give me the .git directory or the filename but the contents are clearly the culprit ```data:26b394899eacf3750efdc075fbc3064c7c2aade9``` that is the hash in the stray ```'.git'``` metadata file.

SO @saltstack/team-core I see ( or hope for ) at least two fixes.

1. stop any jinja sls file ( or slp file in the future ) under ```'.git``` directory to even be attempted to be rendered. 

2. catching this particular error condition as well where the potential sls/slp file is not at all of the expected format without that blowing up the whole process. Because such a file could theoretically be introduced and needs detection and skipping, very much like the code already does for other error conditions.

What's your thinking on this @damon-atkins ? You are clearly much more focused in this area of the systems code?

**Comment by damon-atkins** [comment]
We can check that the config is the right type. I.e. list or dict or OrderDict or both.  It should not be a string.

**Comment by damon-atkins** [comment]
Use
https://docs.saltstack.com/en/latest/ref/configuration/master.html#file-ignore-regex
or
https://docs.saltstack.com/en/latest/ref/configuration/master.html#file-ignore-glob


However it is a bug that its not checking `config` variable type.
