### ISSUE TITLE
Missing / Incomplete modules in SaltStack RPM packages on repo.saltstack.com

### ISSUE THREAD

**Issue by asymetrixs** [saltstack/salt#45455]
### Description of Issue/Question
I downloaded the Salt components from `http://repo.saltstack.com/yum/redhat/7.4/x86_64/latest/` and installed them on a CentOS 7.3 1611.
After using Salt for a bit I figured out, that at least the `selinux execution module` is not in it's latest version. It does not provide the function `selinux.fcontext_policy_present` and some others. I checked my installation and also the content of package `salt-2017.7.2-1.el7.noarch.rpm` and it seems to contain an older version of `selinux.py` or a version that is missing this functionality in general.

### Setup
n/a

### Steps to Reproduce Issue
Check `selinux.py` which resides in `/usr/lib/python2.7/site-packages/salt/modules/selinux.py` from `http://repo.saltstack.com/yum/redhat/7.4/x86_64/latest/salt-2017.7.2-1.el7.noarch.rpm`.

### Versions Report
n/a

According to `https://github.com/saltstack/salt/blob/2017.7/salt/modules/selinux.py` the functionality has been implemented, but as said, in the package `salt-2017.7.2-1.el7.noarch.rpm` it seems to be an older version of that file missing this functionality.

**Comment by gtmanfred** [comment]
That option is not in the 2017.7.2 tag

https://github.com/saltstack/salt/blob/v2017.7.2/salt/modules/selinux.py

It will be in 2017.7.3, which is the next release.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
If you need the newer module right now, you can distribute it using dynamic modules

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

Daniel

**Comment by asymetrixs** [comment]
So then I am confused why the _latest_ version of the documentation ([2017.7.2](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.selinux.html)) says that it is available and was already introduced in 2017.7.0.

> salt.states.selinux.fcontext_policy_present(name, sel_type, filetype='a', sel_user=None, sel_level=None)
> New in version 2017.7.0.
> Makes sure a SELinux policy for a given filespec (name), filetype and SELinux context type is present.

Please clarify, thanks.

**Comment by gtmanfred** [comment]
Ahh, i see what happened, that is a state module, not an execution module.

https://github.com/saltstack/salt/blob/v2017.7.2/salt/states/selinux.py#L311

check `/usr/lib/python2.7/site-packages/salt/states/selinux.py`

**Comment by asymetrixs** [comment]
@gtmanfred, Salt Version: 2017.2.2 (from the repo)

`/usr/lib/python2.7/site-packages/salt/modules/selinux.py` contains a function called `fcontext_policy_apply`, so I would expect to be able to use it.
> etc_t apply:
>  selinux.fcontext_apply_policy
>    - name: /etc/httpd/conf.d/webserver.conf

Now, running `salt-call state.apply` throws an error:
> State 'selinux.fcontext_apply_policy' was not found in SLS 'master'
> Reason: 'selinux.fcontext_apply_policy' is not available.

Documentation says:
>salt.modules.selinux.fcontext_apply_policy(name, recursive=False)
>New in version 2017.7.0.

I am a bit confused, so what am I missing here?

**Comment by gtmanfred** [comment]
you cannot use stuff from `/usr/lib/python2.7/site-packages/salt/modules/` in state files, unless you use the module.run state

you can use anything from `/usr/lib/python2.7/site-packages/salt/states` in state files.
