### ISSUE TITLE
Allow custom modules which run on master

### ISSUE THREAD

**Issue by mitar** [saltstack/salt#45450]
### Setup

I am using `salt-ssh` to deploy configuration to servers. On my computer (SSH master) I have in `states` directory also `_modules` with some simple Python functions I want to run to process values in Jinja templates. I do something like:

```
{% for user in pillar.users %}
  {% set user_groups = salt['servers.groups'](user.get('servers', {}), grains['id']) %}
  ...
```

`servers.groups` is a Python function which returns values from user's pillars based on target ID.

The issue is that this simple pure function runs over SSH on the minion. This is problematic because it really slows down things. Is there a way to configure that the module should be only used during rendering of the state and that it can be run locally on master?

### Versions Report

```
Salt Version:
           Salt: 2016.11.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 23 2017, 22:06:14)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 17.10 artful
        machine: x86_64
        release: 4.13.0-21-generic
         system: Linux
        version: Ubuntu 17.10 artful
```

**Comment by mitar** [comment]
OK, maybe I am misunderstanding something. What I want in the end is to improve the performance of how quickly states are applied. Now, if I call `salt-ssh -l debug 'server' state.highstate` I see in output many many entries of:

```
[DEBUG   ] Could not LazyLoad servers.match: 'servers.match' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
servers.match <redacted> <redacted>
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 17552  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE <redacted>: 0
[DEBUG   ] Could not LazyLoad servers.groups: 'servers.groups' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
servers.groups <redacted> <redacted>
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 17556  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE <redacted>: 0
[DEBUG   ] Could not LazyLoad servers.match: 'servers.match' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
servers.match <redacted> <redacted>
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 17560  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE <redacted>: 0
[DEBUG   ] Could not LazyLoad servers.groups: 'servers.groups' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
servers.groups <redacted> <redacted>
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 17564  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE <redacted>: 0
```

For all entries in `pillar.users`. (I have two such methods, `servers.groups`, and `servers.match`.)

I assumed that state is being rendered on the master and this is why it has to do all these SSH calls over to minions to evaluate code. But in this case code can be evaluated locally. It is just a pure Python function.

Now, if you are saying that state is evaluated on the minion, then I have no idea what all those calls are. Those calls are problematic because they are serial and when there is high latency (server on the other continent) this can take really a lot of time.

**Comment by gtmanfred** [comment]
Hrm, maybe I am wrong, I was pretty certain we just shipped over the whole state tree and rendered it on the minon, but it appears that it does not.

https://github.com/saltstack/salt/blob/2017.7/salt/client/ssh/wrapper/state.py#L624

It would seem reasonable to add `salt.client.ssh.wrappers` as a loader system and then allow to be syncable

I am marking this as a feature request.

**Comment by mitar** [comment]
Yea, I was also surprised by this behavior. It really delays everything. So I do not care if everything is rendered on master or on minion, but it should just be done at one place without SSH connections going all the time.

**Comment by gtmanfred** [comment]
@saltstack/team-ssh would this be even possible?

Thanks,
Daniel

**Comment by mitar** [comment]
This is still useful.

**Comment by mitar** [comment]
Unstale.
