### ISSUE TITLE
Percent sign in file.serialize with configparser throws SerializationError

### ISSUE THREAD

**Issue by NTmatter** [saltstack/salt#45461]
### Description of Issue/Question
The configparser serializer throws an error when fed a single percent sign.

Commented lines and double percent signs come through without issue. The json formatter seems unaffected.

### Setup
foo.sls:
```yaml
serialize test:
  file.serialize:
    - name: /tmp/foo
    - formatter: configparser
    - dataset:
        test:
            negative: double %% not a problem
            # commented: 100%
            uncommented: 110%
```

top.sls:
```
base:
  banana:
    - foo
```

### Steps to Reproduce Issue
`salt banana state.highstate test`:
```
          ID: serialize test
    Function: file.serialize
        Name: /tmp/foo
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 5756, in serialize
                  contents = __serializers__[serializer_name](dataset, **default_serializer_opts.get(serializer_name, {}))
                File "/usr/lib/python2.7/dist-packages/salt/serializers/configparser.py", line 85, in serialize
                  raise SerializationError(error)
              SerializationError: invalid interpolation syntax in '110%' at position 3
     Started: 15:17:57.117646
    Duration: 7.183 ms
     Changes:   

```

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-101-generic
         system: Linux

**Comment by gtmanfred** [comment]
This is a bug in upstream python.

ConfigParser tries to do string interpolation if it finds a `%` in the string that is being laid down.

```
                File "/usr/lib64/python2.7/ConfigParser.py", line 752, in set
                  "position %d" % (value, tmp_value.find('%')))
              ValueError: invalid interpolation syntax in '110%' at position 3
```

What is happening is `%%` is an escaped percent sign, so config parser finds it, but it doesn't actually do anything, but `%` isn't a valid string interpolation.  so it fails.

**Comment by NTmatter** [comment]
Any thoughts on how I can get a single percentage sign in there?

I've tried replacing it with ascii, unicode, and character name, but they all fail in their own way:
"/usr/share/samba/panic-action %d"
"/usr/share/samba/panic-action \x25\x64"
"/usr/share/samba/panic-action \u0025\x64"
"/usr/share/samba/panic-action \N{PERCENTAGE SIGN}\x64"

I can opt to use a template file, but I'd prefer to be pedantic about keeping things in the SLS if possible.

**Comment by gtmanfred** [comment]
Unfortunately I was unable to figure out how to get the single percent sign in there without the ConfigParser library trying to interpolate it.
