### ISSUE TITLE
Add unit test for salt.utils.sanitize_win_path

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#45470]
Add unit test for salt.utils.sanitize_win_path. 

Related to issue found in: https://github.com/saltstack/salt/issues/43022

**Comment by damon-atkins** [comment]
Plan is to remove this function next release

**Comment by twangboy** [comment]
This is being tested now since the test has been updated to use `unicode_literals`. Unicode values are now being passed to the function... which is what was causing it to fail before.
