### ISSUE TITLE
[oxygen] M2Crypto testing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#45471]
Since we are adding M2Crypto back into salt's core functionalities here: https://github.com/saltstack/salt/pull/44962

we will need to manually test this new functionality by doing the following:

- [x] verify m2crypto is being tested in auto test suite
- [x]  install M2crypto during one of our manual test runs
- [x] m2crypto added to bootstrap: https://github.com/saltstack/salt-bootstrap/pull/1198

**Comment by rallytime** [comment]
@Ch3LL I have updated your list above ^^ as I added the M2Crypto pkg install to the git installation functions just now. The stable package installs will be handled on david's side.
