### ISSUE TITLE
[oxygen] Manually Test New salt-ssh / master/ minion feature

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#45478]
On the head of Oxygen please test the new feature https://github.com/saltstack/salt/issues/40997

**Comment by frogunder** [comment]
This is working as expected on the head of Oxygen.

I have added this to the manual test run until we can get it automated

https://saltstack.testrail.com/index.php?/cases/view/3101

**Comment by rallytime** [comment]
Thanks @frogunder! I'll close this.
