### ISSUE TITLE
python 3.6 recieve UnicodeDecodeError

### ISSUE THREAD

**Issue by MiracleYoung** [saltstack/salt#45492]
### Description of Issue/Question
Sorry for my poor english.
I just have one question that I use pyenv and python version is 3.6.3, when I use salt minion test.ping, it raise a UnicodeDecodeError, 
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 22: invalid start byte`

### Setup
Just `yum install salt-master salt-api`, and use python 3.6 to `pip install salt`

### Steps to Reproduce Issue
`salt minion test.ping`

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 11.0.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.3 (default, Dec  8 2017, 15:57:37)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

I have been blocked here for a long time... please help me.

**Comment by Ch3LL** [comment]
I'm not able to replicate this. I wonder if the pip install and the package install are conflicting. Can you clean up your pyc files?

**Comment by MiracleYoung** [comment]
Hi, thanks for your time.
Let me re-describe it.

1. `yum install salt-master salt-api`
2. `pyenv virtualenv 3.6.3 saltstack`
3. `cd /etc/salt/`
4. `pyenv local saltstack`
5. `service salt-master start`

Is it related to when I first install with yum tool and python version was 2.7 for Centos 7 built-in ?
