### ISSUE TITLE
Be able to enable termination protection in salt-cloud via cloud profiles

### ISSUE THREAD

**Issue by hibbert** [saltstack/salt#45496]
### Description of Issue/Question

At the moment you need to specify a command after build out i.e:-

salt-cloud -a enable_term_protect <node>

Maybe this could be changed so it could be added in cloud.providers.d / cloud.profiles.d so it can be stored in git for rebuilds etc

### Versions Report
 salt --versions
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud is this possible?

**Comment by gtmanfred** [comment]
Would be fairly easy to just check an option, and if it is set in the profile or provider, then to just run the enable_term_protection command.

**Comment by gtmanfred** [comment]
PRs welcome. 😺
