### ISSUE TITLE
Azurearm - provisioning using static IP

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#45494]
### Description of Issue/Question

How to provision machines in azure using static ip?

Current documentation [here](https://docs.saltstack.com/en/latest/topics/cloud/azurearm.html) doesnt have mention of statis ip's

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud any ideas here?

**Comment by gtmanfred** [comment]
I am going to have to defer to @techhat for if that is possible

**Comment by shengis** [comment]
For private IP, I believe you can set the IP manually with '**private_ip_address**', but you can't choose to have a static public IP address.
