### ISSUE TITLE
cherrypy should have a way to apply states asynchronously

### ISSUE THREAD

**Issue by bbejot** [saltstack/salt#45506]
### Description of Feature Request

Currently, there is no way to apply states asynchronously through the cherrypy salt-api.  My understanding is that cherrypy uses the client-api on the salt master, but only calls the cmd function for each of the interfaces.  This leaves no way to access the other client-api functions (such as cmd_async in salt.client.LocalClient).  The modules that client-api provides access to (like salt.modules.state) do not have asynchronous support for applying state.

My use case for this is that I have a setup where configuration is kicked off from our CI, but that certain states temporarily take down the NIC.  So if I apply a state synchronously, it will report as failed, even though the task is still ongoing and likely to succeed.  Thus I find myself in need of a way to apply states asynchronously through salt-api.

Thank you all for the hard work you put into this product.

**Comment by Ch3LL** [comment]
ping @saltstack/team-netapi think this is a possibility?

**Comment by gtmanfred** [comment]
Have you tried setting the client to `local_async` in the api call?

**Comment by bbejot** [comment]
You know, sometimes you look for a thing that you think should exist for an entire day and it turns out that the answer was sitting in one of your open tabs.  Thank you, @gtmanfred, local_async was exactly what I was looking for.

**Comment by gtmanfred** [comment]
:+1:
