### ISSUE TITLE
[Oxygen] Runtests.py is failing because of the event bus

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#45507]
### Description of Issue/Question
This started here.  https://github.com/saltstack/salt-jenkins/issues/683

What I found was that either the `salt-master` or `salt-run state.event` is taking longer than expected to attach to the masters event bus .ipc file, and the pytest-salt kills off starting the different services because the [EventListener](https://github.com/saltstack/pytest-salt/blob/master/pytestsalt/utils.py#L751) doesn't see the start event soon enough.

To get around this for now, we have increased the start timeout [here](https://github.com/saltstack/salt/pull/45392) but we should still find out why it is taking longer in oxygen than it used to.

**Comment by rallytime** [comment]
Hi @DmitryKuzmenko Can you look into this? We've worked around it for now by increasing the time we wait for the daemons to start up in the test suite, but I think this is indicative of a larger problem.

Please reach out if you have questions.

**Comment by DmitryKuzmenko** [comment]
With a pleasure.

**Comment by gtmanfred** [comment]
I think this issue was fixed over the weekend when all the unicode issues were being fixed.

I am going to close this issue.

Daniel
