### ISSUE TITLE
boto_vpc.route_table_present throws an error when running test=True if the route table does not exist

### ISSUE THREAD

**Issue by bgridley** [saltstack/salt#45514]
### When managing aws route tables with boto_vpc.route_table_present: state module, an error is thrown when test=True. 

We need to be able to test before running this state. 

salt '*' state.apply routes test=True

     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_vpc.py", line 964, in route_table_present
                  region=region, key=key, keyid=keyid, profile=profile)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_vpc.py", line 1042, in _routes_present
                  route_table = route_table[0]
              IndexError: list index out of range

### Setup
Make sure above state file exists: routes.sls

Make sure my_route_table does not exist in aws vpc. 

my_route_table:
  boto_vpc.route_table_present:
    - name: my_route_table
    - vpc_id: vpc-123456
    - routes:
      - destination_cidr_block: 0.0.0.0/0
        internet_gateway_name: InternetGateway
    - subnet_names:
      - subnet1

### Steps to Reproduce Issue
Execute: salt '*' state.apply routes test=True

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Sep  1 2016, 22:14:00)
   python-gnupg: 0.3.8
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.9.43-17.39.amzn1.x86_64
         system: Linux
        version: Not Installed

**Comment by garethgreenaway** [comment]
@bgridley Thanks for the report.  This should be an easy fix, we just need to check that there is in fact a list before trying to reference an item in it.

**Comment by rallytime** [comment]
@vitaliyf Has this been fixed with #41297?
