### ISSUE TITLE
[Question] Does the salt master or the salt syndic issue bootstrap commands for salt-cloud?

### ISSUE THREAD

**Issue by tyhunt99** [saltstack/salt#45516]
### Description of Issue/Question
I am playing around with the idea of a multi-master setup for salt using the [syndic](https://docs.saltstack.com/en/latest/topics/topology/syndic.html). The basic concept is I have an isolated VPC in a separate AWS account and I want this intermediate node to act as the gateway for all minion within that VPC. 

In order for this to work I need to know when I issue a salt-cloud command to spin up a new instance in the vpc is there a way to force the syndic to handle all of it? Or at least handle the ssh bootstrapping of the new minion so I don't have to have external ssh access into the VPC?

**Comment by gtmanfred** [comment]
The machine that you run the salt-cloud command on will be the one that bootstraps it, it uses [salt.utils.cloud:deploy_script](https://github.com/saltstack/salt/blob/develop/salt/utils/cloud.py#L1172) to bootstrap the minion.

If you want to do this with a syndic, you will either need to run the salt-cloud command from the syndic master server, or you could have a minion also on the syndic master server, and then use `saltutil.wheel` to accept the key as part of your build process.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.wheel
