### ISSUE TITLE
Calling state functions from custom execution modules

### ISSUE THREAD

**Issue by while0pass** [saltstack/salt#45523]
It would be helpful to be able to call state functions with `__states__` both from other states and custom execution modules. One can use `__salt__['state.single']('statemodule.function', **kwargs).values()[0]` for the second case right now, but `__states__` would be much neater.

**Comment by garethgreenaway** [comment]
@while0pass Thanks for the report.  This is currently possible starting in the 2017.7 release, there are several examples in the code base.
