### ISSUE TITLE
Detecting empty grain

### ISSUE THREAD

**Issue by wesleyarthur** [saltstack/salt#45524]
### Description of Issue/Question
Hello, I'm trying to detect if a grain is null, then do something. In particular if a server has no disks then do something. I had previously used the syntax below, but now I can't seem to get it to work. Would anyone know the best way to test for pillar being empty?

### Setup
```
{% if grains.get['disks'] | default (None) == 'y' %}
      do something...
{% endif %}
```

### Versions Report
Salt  Version: 2017.7.2

**Comment by garethgreenaway** [comment]
Not sure if this is a direct cut & paste from what you're using but you appear to have a typo, should be `grains` not `gains`.

**Comment by wesleyarthur** [comment]
Oops. Typo when I put it up here. I've updated to what it is currently set to.
