### ISSUE TITLE
Filtering out paths, while building SPMs might remove too much in some edge cases

### ISSUE THREAD

**Issue by P-Jablonski** [saltstack/salt#45545]
https://github.com/saltstack/salt/blob/bb94a21d09d24332021f97681bb951b19b512a1f/salt/spm/__init__.py#L1075

The way the path is currently filtered out is, that if file path string starts with the string supplied by filter, it will be filtered out

`member.name.startswith('{0}/{1}'.format(self.formula_conf['name'], item))`
`member.name.startswith('{0}/{1}'.format(self.abspath, item))`

So in your /etc/salt/spm config, if you have:

          spm_build_exclude:
            - test

and the files under your formula directory structure are:

          test
          test-1
          test2
          testAAA

It will filter all of them out (which in my opinion is undesirable).
What we need is something like:

          for item in self.opts['spm_build_exclude']:
              rel_path = '{0}/{1}'.format(self.formula_conf['name'], item)
              abs_path = '{0}/{1}'.format(self.abspath, item)
              if member.name == rel_path or member.name.startswith(rel_path + '/'):
                  return None
              elif member.name == abs_path or member.name.startswith(abs_path + '/'):
                  return None

or a regexp solution.

**Comment by gtmanfred** [comment]
You could set exclude to `test/` right now.

But we should make this more explicit. and allow for it to ignore subdirectories in a similar way that .gitignore does it.

I am going to mark this as a feature request.
Daniel
