### ISSUE TITLE
Retuners: no cleanup for salt.returners.pgjsonb ?

### ISSUE THREAD

**Issue by the-glu** [saltstack/salt#45547]
### Description of Issue/Question

I setuped salt to use salt.returners.pgjsonb (as recommanded for postgres) as a returner for my master.

I see that my database is growing and growing and old entries are never removed. 

It seems there is no cleanup function but one seems to exists in one postgres module, `postgres_local_cache.clean_old_jobs`.

What should be done ?

The documentation dosen't specfy it, but I should use `postgres_local_cache` if I want cleanup ?
There is a bug and entries should be cleanup ?
I should cleanup things manually ?

Thanks,

### Setup

```
returner.pgjsonb.host: '127.0.0.1'
returner.pgjsonb.user: 'salt_cache'
returner.pgjsonb.pass: ''
returner.pgjsonb.db: 'salt_cache'
returner.pgjsonb.port: 5432

master_job_cache: pgjsonb
```

### Steps to Reproduce Issue

Use pgjsonb, run stuff, wait >24h, entries are not deleted.

### Versions Report

```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.1 
         locale: UTF-8
        machine: x86_64
        release: 4.13.4-1-pve
         system: Linux
        version: debian 9.1
```

**Comment by the-glu** [comment]
Update:

The function seems to do nothing, even in postgres_local_cache: https://github.com/saltstack/salt/blob/5d7386edc50c6e7d9843cb7196e7f884ed642e7a/salt/returners/postgres_local_cache.py#L411

Mysql's returner seems to be implemented however: https://github.com/saltstack/salt/blob/5d7386edc50c6e7d9843cb7196e7f884ed642e7a/salt/returners/mysql.py#L560

**Comment by gtmanfred** [comment]
These should be implemented for the other returners.

Thanks for the report.
Daniel
