### ISSUE TITLE
Salt Cloud Azure ARM: cannot deploy VM

### ISSUE THREAD

**Issue by cskowronnek** [saltstack/salt#45546]
### Description of Issue/Question
I can't deploy a VM using several sizes:
```
[WARNING ] There was a cloud error: Azure Error: ResourceNotFound
Message: The Resource 'Microsoft.Network/publicIPAddresses/Elastic-Node-4-iface0-ip' under resource group 'ELK' was not found.
[WARNING ] <class 'msrestazure.azure_exceptions.CloudError'>
[ERROR   ] There was a profile error: standard_b4ms
```
### Setup
```
azure-es-node:
  provider: azurearm
  master: saltmaster
  image: Canonical|UbuntuServer|16.04-LTS|latest
  size: Standard_B4ms
  location: westeurope
  network: VNET-PIT
  subnet: VNET-PIT-Subnet1
  storage_account: elkdiag742
  storage_key: something
  ssh_username: user
  ssh_password: topsecret
  public_ip: False
  volumes:
    - {disk_size_gb: 50, name: 'Elastic-Node-4-datadisk1' }

  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True
```

### Steps to Reproduce Issue
It works with a size like "Basic_A0", but not with some other sizes like Standard_B4ms.

DEBUG LOG:
```
[ERROR   ] There was a profile error: standard_b4ms
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 284, in run
    self.config.get('names')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1448, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1278, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1215, in create
    'wait_for_ip_interval_multiplier', vm_, __opts__, default=1),
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2432, in wait_for_ip
    data = update_callback(*update_args, **update_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1190, in _query_ip_address
    data = request_instance(kwargs=vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1103, in request_instance
    VirtualMachineSizeTypes, vm_['size'].lower()
  File "/usr/local/lib/python2.7/dist-packages/enum/__init__.py", line 390, in __getattr__
    raise AttributeError(name)
AttributeError: standard_b4ms

```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
            Salt: 2017.7.2

Dependency Versions:
 Apache Libcloud: 1.5.0
            cffi: 1.11.2
        cherrypy: Not Installed
        dateutil: 2.6.1
       docker-py: Not Installed
           gitdb: 0.6.4
       gitpython: 1.0.1
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: 1.0.3
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: 2.18
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.2.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: Ubuntu 16.04 xenial
          locale: UTF-8
         machine: x86_64
         release: 4.4.0-104-generic
          system: Linux
         version: Ubuntu 16.04 xenial

```

**Comment by gtmanfred** [comment]
@techhat have you seen this problem when writing the azurearm driver?

Thanks,
Daniel

**Comment by shengis** [comment]
VM Size usable by Azure is hardcoded in the python azure driver : 

class VirtualMachineSizeTypes(Enum):
    basic_a0 = "Basic_A0"
    basic_a1 = "Basic_A1"
    basic_a2 = "Basic_A2"
    basic_a3 = "Basic_A3"
    basic_a4 = "Basic_A4"
    standard_a0 = "Standard_A0"
    standard_a1 = "Standard_A1"
    standard_a2 = "Standard_A2"
    standard_a3 = "Standard_A3"
    standard_a4 = "Standard_A4"
    standard_a5 = "Standard_A5"
    standard_a6 = "Standard_A6"
    standard_a7 = "Standard_A7"
    standard_a8 = "Standard_A8"
    standard_a9 = "Standard_A9"
    standard_a10 = "Standard_A10"
    standard_a11 = "Standard_A11"
    standard_d1 = "Standard_D1"
    standard_d2 = "Standard_D2"
    standard_d3 = "Standard_D3"
    standard_d4 = "Standard_D4"
    standard_d11 = "Standard_D11"
    standard_d12 = "Standard_D12"
    standard_d13 = "Standard_D13"
    standard_d14 = "Standard_D14"
    standard_d1_v2 = "Standard_D1_v2"
    standard_d2_v2 = "Standard_D2_v2"
    standard_d3_v2 = "Standard_D3_v2"
    standard_d4_v2 = "Standard_D4_v2"
    standard_d5_v2 = "Standard_D5_v2"
    standard_d11_v2 = "Standard_D11_v2"
    standard_d12_v2 = "Standard_D12_v2"
    standard_d13_v2 = "Standard_D13_v2"
    standard_d14_v2 = "Standard_D14_v2"
    standard_d15_v2 = "Standard_D15_v2"
    standard_ds1 = "Standard_DS1"
    standard_ds2 = "Standard_DS2"
    standard_ds3 = "Standard_DS3"
    standard_ds4 = "Standard_DS4"
    standard_ds11 = "Standard_DS11"
    standard_ds12 = "Standard_DS12"
    standard_ds13 = "Standard_DS13"
    standard_ds14 = "Standard_DS14"
    standard_ds1_v2 = "Standard_DS1_v2"
    standard_ds2_v2 = "Standard_DS2_v2"
    standard_ds3_v2 = "Standard_DS3_v2"
    standard_ds4_v2 = "Standard_DS4_v2"
    standard_ds5_v2 = "Standard_DS5_v2"
    standard_ds11_v2 = "Standard_DS11_v2"
    standard_ds12_v2 = "Standard_DS12_v2"
    standard_ds13_v2 = "Standard_DS13_v2"
    standard_ds14_v2 = "Standard_DS14_v2"
    standard_ds15_v2 = "Standard_DS15_v2"
    standard_g1 = "Standard_G1"
    standard_g2 = "Standard_G2"
    standard_g3 = "Standard_G3"
    standard_g4 = "Standard_G4"
    standard_g5 = "Standard_G5"
    standard_gs1 = "Standard_GS1"
    standard_gs2 = "Standard_GS2"
    standard_gs3 = "Standard_GS3"
    standard_gs4 = "Standard_GS4"
    standard_gs5 = "Standard_GS5"

**Comment by gtmanfred** [comment]
Ahh, so when azure releases a new size, they have to update their python library?

**Comment by shengis** [comment]
Yes, but they don't do it on regular basis.

**Comment by cskowronnek** [comment]
I don't understand the purpose.

I put `size: Standard_B4ms` in my config, a function converts it to lowercase `standard_b4ms` and then looking it up in the library to match it against the former input to send `Standard_B4ms` to the API which was what I put in my config?
