### ISSUE TITLE
cmd.run/cmd.shell Not sourcing BASH login script

### ISSUE THREAD

**Issue by boogybren** [saltstack/salt#45556]
### Description of Issue/Question
When running: 

`salt 'servernamehere' cmd.run 'command here'`
OR
`salt 'servernamehere' cmd.shell 'command here'`

It is not sourcing ANY login script.  Even when `shell=/bin/bash` is provided.

I've tried exporting a variable in several places in the OS that would set the variable with no luck.  It works perfectly from CLI.

/root/.bashrc
/root/.bash_profile
/root/.profile
/etc/profile
/etc/bashrc
/etc/environment

Even with an unadulterated login profile for root, salt is not reporting the same $PATH.

**SALT**
`salt 'servernamehere' cmd.shell 'echo $PATH' shell='/bin/bash'
servernamehere:
    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/bin:/sbin`

**CLI**
`echo $PATH
/usr/local/sbin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

**COMPARE SALT $PATH WITH SERVER $PATH**
FROM MASTER
`salt 'servernamehere' cmd.shell 'echo $PATH' shell='/bin/bash'`

FROM MINION AS ROOT
`echo $PATH`

**EXPORT A VARIABLE IN ANY BASH READ LOGIN SCRIPT, COMPARE RESULTS FROM MASTER AND MINION**

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**MASTER**

> Salt
> Version:
>           Salt: 2017.7.2
>
>Dependency Versions:
>           cffi: Not Installed
>       cherrypy: Not Installed
>       dateutil: Not Installed
>      docker-py: Not Installed
>          gitdb: Not Installed
>      gitpython: Not Installed
>         ioflo: Not Installed
>        Jinja2: 2.7.2
>        libgit2: Not Installed
>        libnacl: Not Installed
>       M2Crypto: Not Installed
>           Mako: Not Installed
>   msgpack-pure: Not Installed
> msgpack-python: 0.4.8
>   mysql-python: 1.2.5
>      pycparser: Not Installed
>       pycrypto: 2.6.1
>   pycryptodome: Not Installed
>       pygit2: Not Installed
>       Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
>   python-gnupg: Not Installed
>         PyYAML: 3.11
>          PyZMQ: 15.3.0
>           RAET: Not Installed
>          smmap: Not Installed
>        timelib: Not Installed
>        Tornado: 4.2.1
>            ZMQ: 4.1.4
>
>System Versions:
>           dist: centos 7.4.1708 Core
>         locale: UTF-8
>        machine: x86_64
>        release: 3.10.0-693.11.6.el7.x86_64
>         system: Linux
>        version: CentOS Linux 7.4.1708 Core

**MINION**
>Salt Version:
>           Salt: 2017.7.2
>
>Dependency Versions:
>           cffi: Not Installed
>       cherrypy: Not Installed
>       dateutil: Not Installed
>      docker-py: Not Installed
>          gitdb: Not Installed
>      gitpython: Not Installed
>          ioflo: Not Installed
>         Jinja2: 2.7.2
>        libgit2: Not Installed
>        libnacl: Not Installed
>       M2Crypto: Not Installed
>           Mako: Not Installed
>   msgpack-pure: Not Installed
> msgpack-python: 0.4.8
>   mysql-python: Not Installed
>      pycparser: Not Installed
>       pycrypto: 2.6.1
>   pycryptodome: Not Installed
>         pygit2: Not Installed
>         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
>   python-gnupg: Not Installed
>         PyYAML: 3.11
>          PyZMQ: 15.3.0
>           RAET: Not Installed
>          smmap: Not Installed
>        timelib: Not Installed
>        Tornado: 4.2.1
>            ZMQ: 4.1.4
>
>System Versions:
>           dist: centos 7.4.1708 Core
>         locale: UTF-8
>        machine: x86_64
>        release: 3.10.0-693.11.6.el7.x86_64
>         system: Linux
>        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
So,  this is the expected behavior.

From the bash man page.

```
       When  bash  is  invoked as an interactive login shell, or as a non-interactive shell with the --login option, it first reads and executes commands from the file /etc/profile, if that file exists.  After reading that file, it looks for ~/.bash_profile, ~/.bash_login, and ~/.profile, in that order, and reads and executes
       commands from the first one that exists and is readable.  The --noprofile option may be used when the shell is started to inhibit this behavior.
```

Any of the profiles are only sourced when bash is started as an interactive login shell, or a non interactive shell with `--login` so only in login shells.  So it will never be sourced by salt because we do not launch login shells.

```
       When an interactive shell that is not a login shell is started, bash reads and executes commands from ~/.bashrc, if that file exists.  This may be inhibited by using the --norc option.  The --rcfile file option will force bash to read and execute commands from file instead of ~/.bashrc.
```

bashrc is only sourced for interactive shells that are not login shells.  So we do not source it because salt is starting a non-interactive shell.

```
       When bash is started non-interactively, to run a shell script, for example, it looks for the variable BASH_ENV in the environment, expands its value if it appears there, and uses the expanded value as the name of a file to read and execute.  Bash behaves as if the following command were executed:
              if [ -n "$BASH_ENV" ]; then . "$BASH_ENV"; fi
       but the value of the PATH variable is not used to search for the file name.
```

When a shell is started with non interactive, bash sources the $BASH_ENV file. so if you want this thing to work, you will have to set the bash_env variable for the cmd.shell command.


```
[root@salt ~]# cat /etc/profile.d/test.sh
export TEST=whatever
[root@salt ~]# salt \* cmd.shell 'echo $TEST' shell=/bin/bash env='{"BASH_ENV": "/etc/profile"}'
salt.c.gtmanfred-1263.internal:
    whatever
```

And if you set BASH_ENV to /etc/profile, and you have the default profiles setup to read /etc/profile.d/*.sh and ~/.bashrc then you can put the file in any place.

This could also be permanent by setting the BASE_ENV in an environment dropin file for the salt-minion service

#/etc/systemd/system/salt-minion.service.d/bashenv.conf
```
[Service]
Environment=BASH_ENV=/etc/profile
```
