### ISSUE TITLE
minion debug crashes on Windows

### ISSUE THREAD

**Issue by rhavenn** [saltstack/salt#45559]
Sometime in the last few weeks the salt-minion debug mode has started to crash on Windows. I haven't had to run a debug in awhile, so I don't know exactly when it started happening, but it last worked in mid to late December. I'm using the same exact minion version and base Windows version.

The service runs fine normally. I was just trying to troubleshoot a new windows package install.

Windows version: Windows 10 Ent 1709 10.0.16299 N/A Build 16299
salt versions output:
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.16299 SP0 Multiprocessor Free
```

I'm a full admin and running either cmd.exe or powershell.exe in admin mode when I run salt-minion-debug.exe I get the following only:
```
C:\salt>.\salt-minion-debug.bat
The salt-minion service is not started.

More help is available by typing NET HELPMSG 3521.

[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\grains.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\grains.conf
[DEBUG   ] Using cached minion ID from c:\salt\conf\minion_id: machine name
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 8912
[DEBUG   ] Multiprocessing queue logging configured for the process running under PID: 8912
[DEBUG   ] Configuration file path: c:\salt\conf\minion
```

It then crashes. The Event Log shows the following in the Application log:
```
Faulting application name: python.exe, version: 3.5.3150.1013, time stamp: 0x587cef4a
Faulting module name: ntdll.dll, version: 10.0.16299.192, time stamp: 0x6dead514
Exception code: 0xc0000374
Fault offset: 0x00000000000f87cb
Faulting process id: 0x22d0
Faulting application start time: 0x01d3915c562d100e
Faulting application path: C:\salt\bin\python.exe
Faulting module path: C:\windows\SYSTEM32\ntdll.dll
Report Id: 38e8305d-9907-4a98-b7c7-b831ea18392b
Faulting package full name: 
Faulting package-relative application ID: 

```

**Comment by gtmanfred** [comment]
Can you provide me with this file so that I can try and replicate this?

`.\salt-minion-debug.bat`

Thanks,
Daniel

**Comment by dafyddj** [comment]
I am seeing this too. Salt minion 2017.7.2 py2, Windows 10 1709 (16299.192)
Just need to run `salt-call state.apply` or `salt-call state.apply test=True` in Powershell or Cmd.

**Comment by rhavenn** [comment]
Sure. File content:
```
@ echo off
:: Script for starting the Salt-Minion
:: Accepts all parameters that Salt-Minion Accepts

:: Define Variables
Set SaltDir=%~dp0
Set SaltDir=%SaltDir:~0,-1%
Set Python=%SaltDir%\bin\python.exe
Set Script=%SaltDir%\bin\Scripts\salt-minion

:: Stop the Salt Minion service
net stop salt-minion

:: Launch Script
"%Python%" -E -s "%Script%" -l debug

```

It's default from the installer.

**Comment by gtmanfred** [comment]
@twangboy have you seen this at all?

Thanks,
Daniel

**Comment by twangboy** [comment]
@gtmanfred I haven't. It's actually python crashing... it might help to have the debug log to see what salt was doing when it crashed.

**Comment by twangboy** [comment]
Was this an upgrade from a previous version of salt? Have you tried reinstalling salt?

**Comment by rhavenn** [comment]
No, I'm working on autodeploys for some VDIs and it's a clean install of salt once the VDI deploys.

I'm running some new builds and I'll see if it's still happening.

**Comment by rhavenn** [comment]
This still occurs. Normally, there are 2 python.exe's running. When using debug mode 1 of them crashes. The one locking the logfile in var/log/salt stays running.

**Comment by TheVakman** [comment]
@twangboy I'm also having this, even on fresh Salt installations now.

This is on Windows 10 1607, December CU. Salt Minion 2017.7.2 (Python 3).

**Comment by TheVakman** [comment]
@phsteve said on Slack to try calling it while being in the directory (C:\salt\bin).

I tried that and it worked for me without crashing.

You can probably close this @rhavenn if that also works for you as well and follow #45138 as that's likely the real issue here.
