### ISSUE TITLE
Atlassian Stride

### ISSUE THREAD

**Issue by Auha** [saltstack/salt#45569]
### Description of Issue/Question
Atlassian is deprecating Hipchat in favor for their new chat app called Stride. I think we should be able to make an engine and a module/state for it as their currently isn't any.

**Comment by gtmanfred** [comment]
We would love an engine, returner module and state for stride!

Hipchat was provided by the community, so i am sure someone will be making some soon.  Or if you wanted to submit a PR we would greatly appreciate it.

Thanks,
Daniel

**Comment by mchugh19** [comment]
Stride was canned by Atlassian, so this can be closed
