### ISSUE TITLE
Slack engine unable to handle large user lists within Slack

### ISSUE THREAD

**Issue by sootythebear** [saltstack/salt#45561]
### Description of Issue/Question

The Slack engine is unable to obtain a user list from Slack due to the number of users within the workspace. A HTTP 500 error (hphp_invoke) is being thrown. 

Slack recommends the use of pagination for large searches.
https://api.slack.com/methods/users.list#pagination

Looking at the 2017.7.3 and develop code branches, the utils/slack.py is performing a lookup with "token" as the only option.

### Setup
Vanilla Salt Master install, Python `slackclient` installed, with the following engine config:

/etc/salt/master.d/slack.conf file:
```
engines:
  - slack:
      token: 'xoxb-'
      control: True
      valid_commands:
        - jobs.list_jobs
      aliases:
        list_jobs:
          cmd: jobs.list_jobs
```

### Steps to Reproduce Issue

From salt-master -l debug:

```
[DEBUG   ] https://slack.com/api/users.list
[DEBUG   ] {'token': 'xoxb-'}
[DEBUG   ] None
[DEBUG   ] {'status': 500, 'error': 'HTTP 500: hphp_invoke'}
```

### Versions Report

Slackclient:
```
slackclient (1.1.0)
```

salt --versions-report:
```
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by gtmanfred** [comment]
This should totally be added.  Thanks for reporting it.  If you had time to submit a pr for the user list stuff in salt.utils.slack we would greatly appreciate it.

@garethgreenaway were you aware of the pagination stuff when this was originally being written?

Thanks,
Daniel

**Comment by sootythebear** [comment]
Continued to review this, and the pagination option is also flawed. It is not guaranteed that a full list will be returned by this method. Slack documentation advises the following:

From https://api.slack.com/docs/pagination
"...It's possible to receive less results than your specified limit, even when there are additional results to retrieve."

The best solution I see at present is to refrain from obtaining the user list, but extract the `user` from the RTM message, call the Slack `users.info` API call, source the `name` from the return, and then verify against the `valid users` list.

**Comment by sootythebear** [comment]
@garethgreenaway Hi Gareth, any thoughts on this?
