### ISSUE TITLE
cmd.run can‘t execute multiple commands at one time in windows

### ISSUE THREAD

**Issue by qiangshui** [saltstack/salt#45571]
### Description of Issue/Question
cmd.run can‘t execute multiple commands at one time in windows
```
test:
  cmd.run:
    - name: |
        echo "hello"
        echo "world"
```
I run this in a windows minion:
![default](https://user-images.githubusercontent.com/24819310/35181525-55af9426-fdfe-11e7-9968-48ce282c73c9.png)
and run in a centos minion:
![default](https://user-images.githubusercontent.com/24819310/35181535-850a79b6-fdfe-11e7-94bc-43451dbcb927.png)
In Windows server, it is always only executed the first command.

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: 1.4.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.8 Final
        machine: x86_64
        release: 2.6.32-642.15.1.el6.x86_64
         system: Linux
        version: CentOS 6.8 Final,

**Comment by damon-atkins** [comment]
You need to use cmd.shell and also separate commands with an  `&` or use cmd.script
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html

**Comment by qiangshui** [comment]
@damon-atkins ,thanks. But why I can execute multiple commands in centos？

**Comment by damon-atkins** [comment]
Its a bug, which I can not spot in the development code or 2016.11 unreleased.

**Comment by gtmanfred** [comment]
you can execute multiple commands in centos, because the subprocess command allows you to do that.

```
Python 2.7.5 (default, Aug  4 2017, 00:39:18)
[GCC 4.8.5 20150623 (Red Hat 4.8.5-16)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import subprocess
>>> subprocess.call('''
... echo hello
... echo world
... ''', shell=True)
hello
world
0
```

The cmd.run state gets run with `python_shell=True` so it acts as a regular bash shell, where each newline is a return to run a new command.

Afaik windows cmd does not support that.

**Comment by morganwillcock** [comment]
Since it is currently run in a shell, switching to the folded block style will get you pretty close.
<pre>test:
  cmd.run:
    - name: >
        echo hello &
        echo world</pre>
...but that is effectively the same as writing:
<pre>test:
  cmd.run:
    - name: |
        echo hello & echo world</pre>
