### ISSUE TITLE
Built in Jiinja filter `difference` does not work in pillar stack module

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#45597]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Jan 22 13:32:20 salt0 salt-master[16462]: [ERROR   ] Execption caught loading ext_pillar 'stack':
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 821, in ext_pillar
Jan 22 13:32:20 salt0 salt-master[16462]:     key)
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/usr/lib/python2.7/dist-packages/salt/pillar/__init__.py", line 764, in _external_pillar_data
Jan 22 13:32:20 salt0 salt-master[16462]:     val)
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/usr/lib/python2.7/dist-packages/salt/pillar/stack.py", line 419, in ext_pillar
Jan 22 13:32:20 salt0 salt-master[16462]:     stack = _process_stack_cfg(cfg, stack, minion_id, pillar)
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/usr/lib/python2.7/dist-packages/salt/pillar/stack.py", line 459, in _process_stack_cfg
Jan 22 13:32:20 salt0 salt-master[16462]:     obj = yaml.safe_load(jenv.get_template(unix_path).render(stack=stack))
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 830, in get_template
Jan 22 13:32:20 salt0 salt-master[16462]:     return self._load_template(name, self.make_globals(globals))
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 804, in _load_template
Jan 22 13:32:20 salt0 salt-master[16462]:     template = self.loader.load(self, name, globals)
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/usr/lib/python2.7/dist-packages/jinja2/loaders.py", line 125, in load
Jan 22 13:32:20 salt0 salt-master[16462]:     code = environment.compile(source, name, filename)
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 591, in compile
Jan 22 13:32:20 salt0 salt-master[16462]:     self.handle_exception(exc_info, source_hint=source_hint)
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/usr/lib/python2.7/dist-packages/jinja2/environment.py", line 780, in handle_exception
Jan 22 13:32:20 salt0 salt-master[16462]:     reraise(exc_type, exc_value, tb)
Jan 22 13:32:20 salt0 salt-master[16462]:   File "/opt/salt/srv/stack/roles/prometheus.yml", line 63, in <module>
Jan 22 13:32:20 salt0 salt-master[16462]:     {% for node in pillar['hosts'].keys() | difference(exclusions) %}
Jan 22 13:32:20 salt0 salt-master[16462]: [CRITICAL] Pillar render error: Failed to load ext_pillar stack: no filter named 'difference'

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.4
       cherrypy: 3.2.3
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: 0.3.6
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6

System Versions:
           dist: debian 9.3
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-5-amd64
         system: Linux
        version: debian 9.3

**Comment by gtmanfred** [comment]
Can you open this issue on the pillarstack github?

https://github.com/bbinet/pillarstack

He has asked in the salt documentation to have issues reported there 

https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html

```
Any issue should be reported to the upstream project at: https://github.com/bbinet/pillarstack/issues
```

Thanks,
Daniel
