### ISSUE TITLE
Windows Exit Code

### ISSUE THREAD

**Issue by tacf** [saltstack/salt#45599]
### Description of Issue/Question
No exit code from `salt-call` on windows (bost cmd and powershell).

### Setup
salt-minion and salt-master version 2017.7

### Steps to Reproduce Issue
Do a `salt-call state.sls some_state` where  `some_state` does not exist.
Execute this command on both windows 2016 server and Ubuntu 16.04.
Windows has exit code 0 and Ubuntu 127

**Comment by gtmanfred** [comment]
@twangboy @UtahDave would one of yall know why this is, or how to fix this?

Thanks,
Daniel

**Comment by UtahDave** [comment]
@tacf can you provide the exact commands you're running and the exact output?

Here's the output I'm getting on Ubuntu:

```
[boucha@elsapo ~]$ sudo salt-call test.version
[sudo] password for boucha: 
local:
    2017.7.2
[boucha@elsapo ~]$ sudo salt-call state.sls asdfasdfsadf
[ERROR   ] Template was specified incorrectly: False
local:
    Data failed to compile:
----------
    No matching sls found for 'asdfasdfsadf' in env 'base'
[boucha@elsapo ~]$ echo $?
0
```

**Comment by gtmanfred** [comment]
This is also a known issue on linux as well, we are not super consistent with exit codes https://github.com/saltstack/salt/issues/18510

**Comment by tacf** [comment]
Just retested on linux and it actualy doesn't work, as you guys said. Don't really know what i did before to make it work (or what i did wrong to get an actual error code).
