### ISSUE TITLE
Some minions do not return when targeted by nodegroup

### ISSUE THREAD

**Issue by tighepatrick** [saltstack/salt#45616]
### Description of Issue/Question
When targeting a large group of minions by nodegroup, some of the minions will return with the "No response" message.  If I target the same list of minions with salt -C 'L@<list>', the minions all return.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Create a nodegroup with at least 10 minions, run a salt -N <nodegroup> test.ping, observe that some minions do not return as expected.
```[root@salt-master ~]# cat /etc/salt/master.d/nodegroups.conf

nodegroups:
  test1:
    - ff3d0eaa814d
    - e79bd1549ad8
    - d9ac2b53fccb
    - c554ed07e9d1
    - 1591a2da8471
    - 50cc1f15cea7
    - 8e73335d0c62
    - 2c00927531a7
    - 0965aa017a96
    - d20941e505aa
    - 2513e063dc96
    - fc6978005fce
    - 8e61a78c3566
    - 8118b97b90e7
    - 1059cd1841bf
    - 2d1099e3c079

[root@salt-master ~]# salt -N test1 test.ping
8118b97b90e7:
    True
d20941e505aa:
    True
2513e063dc96:
    True
0965aa017a96:
    True
1059cd1841bf:
    True
e79bd1549ad8:
    True
8e73335d0c62:
    True
2c00927531a7:
    True
1591a2da8471:
    True
50cc1f15cea7:
    True
8e61a78c3566:
    True
fc6978005fce:
    True
2d1099e3c079:
    True
ff3d0eaa814d:
    Minion did not return. [No response]
c554ed07e9d1:
    Minion did not return. [No response]
d9ac2b53fccb:
    Minion did not return. [No response]
[salt.trace.gz](https://github.com/saltstack/salt/files/1653502/salt.trace.gz)

[root@salt-master ~]# salt -C 'L@8118b97b90e7,d20941e505aa,2513e063dc96,0965aa017a96,1059cd1841bf,e79bd1549ad8,8e73335d0c62,2c00927531a7,1591a2da8471,50cc1f15cea7,8e61a78c3566,fc6978005fce,2d1099e3c079,ff3d0eaa814d,c554ed07e9d1,d9ac2b53fccb' test.ping

50cc1f15cea7:
    True
8e61a78c3566:
    True
e79bd1549ad8:
    True
2513e063dc96:
    True
1591a2da8471:
    True
fc6978005fce:
    True
d20941e505aa:
    True
1059cd1841bf:
    True
0965aa017a96:
    True
8e73335d0c62:
    True
2d1099e3c079:
    True
8118b97b90e7:
    True
2c00927531a7:
    True
c554ed07e9d1:
    True
d9ac2b53fccb:
    True
ff3d0eaa814d:
    True
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by gtmanfred** [comment]
I am not able to replicate this issue.

```
[root@saltmaster /]# cat /etc/salt/master
nodegroups:
  test1:
  - 5a0344fb093a
  - 661f7076e098
  - 72f517495272
  - 865c261dd670
  - 9d957df57af6
  - b3faf7477cdb
  - b54b6e19a23b
  - d5f1dd6007c0
  - d6b52cc615b4
  - dd0dcb6691a9
[root@saltmaster /]# salt -N test1 test.ping
dd0dcb6691a9:
    True
b3faf7477cdb:
    True
b54b6e19a23b:
    True
d5f1dd6007c0:
    True
5a0344fb093a:
    True
9d957df57af6:
    True
d6b52cc615b4:
    True
72f517495272:
    True
661f7076e098:
    True
865c261dd670:
    True
```

Are you sure that the `salt-master` has been restarted since the nodegroup was changed? and that enough time was given afterwards for all the minions to reconnect?

Thanks,
Daniel

**Comment by tighepatrick** [comment]
Yes, the master was restarted, and I just confirmed again today, 2 days after the nodegroup creation that I am still seeing not all minions respond when using a nodegroup for targeting.  This is from my production setup, with hostnames changed for the normal reasons.

```# salt -N test1 test.ping
(removed successes for sake of brevity, there were 17 today)
host1.example.com:
    Minion did not return. [No response]
(there were 8 failures, all worked when targeted individually)
# salt 'host1.example.com' test.ping
host1.example.com:
    True
