### ISSUE TITLE
Azure ARM: Public IPAllocationMethod Hardcoded to Static

### ISSUE THREAD

**Issue by SJern** [saltstack/salt#45615]
### Description of Issue/Question
```
[DEBUG   ] Cannot create more than 20 public IP addresses with static allocation method for this subscription in this region.
[ERROR   ] There was a profile error: Azure Error: StaticPublicIPCountLimitReached
```

This is more of a feature request. Can we make **_dynamic public_** IPAllocationMethod work for Azure VMs? Right now, it's hardcoded to static:

```
    if bool(kwargs.get('public_ip')) is True:
        pub_ip_name = '{0}-ip'.format(kwargs['iface_name'])
        poller = netconn.public_ip_addresses.create_or_update(
            resource_group_name=kwargs['resource_group'],
            public_ip_address_name=pub_ip_name,
            parameters=PublicIPAddress(
                location=kwargs['location'],
                public_ip_allocation_method=IPAllocationMethod.static,
            ),
        )
```

I took a look at the azurearm.py file and the current `create_interface` method doesn't seem like it can work for any dynamic IP allocation since there would be a circular dependency: salt waits for Azure to assign an IP address, while Azure won't assign any unless IPAllocationMethod is static or until the IP resource is associated with a VM which is never going to be created with the current flow.

**Comment by gtmanfred** [comment]
Yeah, that would be great to have if it is possible.  Would you be able to submit a PR to implement this?

Thanks,
Daniel

**Comment by nicholasmhughes** [comment]
Allocating dynamic public IP addresses with the current logic will result in an endless loop since an IP won't be allocated until the VM is running. I'll take a stab at correcting that.
