### ISSUE TITLE
Salt reported what packages failed to install, but installation successfull

### ISSUE THREAD

**Issue by Freezelight** [saltstack/salt#45623]
### Description of Issue/Question
I have a custom created repository, and receive an error when trying to install packages through pkg.installed or pkg.latest on Debian and RedHat.
### Setup
```
----------
   pkg.installed:
     - pkgs:
       - kav4fs
       - klnagent
```
The same thing if i trying to use a specific versions of packages.
pkg.latest can't find any info about my packages.
### Steps to Reproduce Issue

----------
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: klnagent, kav4fs
     Started: 11:10:21.320690
    Duration: 31866.899 ms
     Changes:
              ----------
              kav4fs.i386:
                  ----------
                  new:
                      8.0.4-312
                  old:
              klnagent.i386:
                  ----------
                  new:
                      10.1.0-101
                  old:

```
[INFO    ] Running state [kaspersky] at time 11:10:21.320688
[INFO    ] Executing state pkg.installed for kaspersky
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.check_db: 'pkg.check_db' is not available.
[INFO    ] Executing command ['yum', '--quiet', 'clean', 'expire-cache'] in directory '/root'
[DEBUG   ] output:
[INFO    ] Executing command ['yum', '--quiet', 'check-update', '--setopt=autocheck_running_kernel=false'] in directory '/root'
[DEBUG   ] Failed to get holds, versionlock plugin is probably not installed
[INFO    ] Executing command ['systemd-run', '--scope', 'yum', '-y', 'install', 'klnagent', 'kav4fs'] in directory '/root'
[INFO    ] Executing command ['rpm', '-qa', '--queryformat', '%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)\n'] in directory '/root'
[ERROR   ] Made the following changes:
'klnagent.i386' changed from 'absent' to '10.1.0-101'
'kav4fs.i386' changed from 'absent' to '8.0.4-312'
```

### Versions Report
Salt Version:
           Salt: 2016.11.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by garethgreenaway** [comment]
@Freezelight Thanks for the report.  Can you check the output of the Salt module `pkg.list_pkgs` and see if your custom packages are listed as installed?

**Comment by Freezelight** [comment]
Hello.
Yes, but something wrong with package version:
```
salt -v '*' pkg.list_pkgs |grep kav4fs
    kav4fs.i386:
salt -v '*' pkg.list_pkgs |grep klnagent
    klnagent.i386:
```
And:

```
rpm -qa |grep kav4fs
kav4fs-8.0.4-312.i386

rpm -qa |grep klnagent
klnagent-10.1.0-101.i386
```

**Comment by Freezelight** [comment]
Hello.
Can someone give me an advice about it?

**Comment by reverendj1** [comment]
I think this is by design. 
Try:
----------
   pkg.installed:
     - pkgs:
       - kav4fs.i386
       - klnagent.i386

I just ran into a s similar issue dealing with i386 packages.

**Comment by Padow01** [comment]
I am having this same issue and updating the format did not fix the issue:

`[INFO    ] Running state [managesoft] at time 16:17:02.516598
[INFO    ] Executing state pkg.installed for managesoft
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[DEBUG   ] Could not LazyLoad pkg.check_db: 'pkg.check_db' is not available.
[INFO    ] Executing command ['apt-cache', '-q', 'policy', 'managesoft'] in directory '/root'
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[INFO    ] Executing command ['apt-get', '-q', 'update'] in directory '/root'
[INFO    ] Executing command ['dpkg', '--get-selections', '*'] in directory '/root'
[INFO    ] Executing command ['systemd-run', '--scope', 'apt-get', '-q', '-y', '-o', 'DPkg::Options::=--force-confold', '-o', 'DPkg::Options::=--force-confdef', '--allow-unauthenticated', 'install', 'managesoft'] in directory '/root'
[INFO    ] Executing command ['dpkg-query', '--showformat', '${Status} ${Package} ${Version} ${Architecture}\n', '-W'] in directory '/root'
[ERROR   ] Made the following changes:
'managesoft:i386' changed from 'absent' to '12.4.0'
`

Here is the output from the dpkg-query commmand:

`root@usgbtubu10:~# dpkg-query --showformat '${Status} ${Package} ${Version} ${Architecture}\n' -W managesoft
install ok installed managesoft 12.4.0 i386
`

Here is the relevant portion of the state:

`managesoft:
  pkg.installed:
    - skip_verify: True
    - pkgs:
      - managesoft
    - require:
      - file: mgsft_rollout_response
`
Versions:

`Salt Version:
           Salt: 2016.11.9

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.8.0-36-generic
         system: Linux
        version: Ubuntu 16.04 xenial
`

**Comment by hatifnatt** [comment]
This can happens when package with different name is installed instead specified package. I'm not even sure that it's need to be fixed. For example:
```
# apt-get -s install php7.2-redis
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'php-redis' instead of 'php7.2-redis'
The following packages will be upgraded:
  php-redis
1 upgraded, 0 newly installed, 0 to remove and 72 not upgraded.
Inst php-redis [3.1.6-1+0~20180104152216.4+stretch~1.gbp3cf38a] (4.0.0-1+0~20180412074133.5+stretch~1.gbp24a357 packages.sury.org [amd64])
Conf php-redis (4.0.0-1+0~20180412074133.5+stretch~1.gbp24a357 packages.sury.org [amd64])
```
Note this line:
```
Note, selecting 'php-redis' instead of 'php7.2-redis'
```

Also in this case `pkg.installed` upgrade that package although it should not. State code:
```yaml
php_pkgs:
  pkg.installed:
    - pkgs:
      - php7.2-bcmath
      - php7.2-curl
      - php7.2-gd
      - php7.2-mbstring
      - php7.2-pgsql
      - php7.2-redis
      - php7.2-xml
      - php7.2-zip
```
Output:
```
----------
          ID: php_pkgs
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: php7.2-redis
              The following packages were already installed: php7.2-zip, php7.2-gd, php7.2-pgsql, php7.2-curl, php7.2-bcmath, php7.2-xml, php7.2-mbstring
     Started: 16:18:55.116879
    Duration: 3237.159 ms
     Changes:
              ----------
              php-redis:
                  ----------
                  new:
                      4.0.0-1+0~20180412074133.5+stretch~1.gbp24a357
                  old:
                      3.1.6-1+0~20180104152216.4+stretch~1.gbp3cf38a
```
Minion log:
```
[salt.state       :1795][INFO    ][10514] Executing state pkg.installed for [php_pkgs]
[salt.utils.lazy  :103 ][DEBUG   ][10514] Could not LazyLoad pkg.resolve_capabilities: 'pkg.resolve_capabilities' is not available.
[salt.utils.lazy  :103 ][DEBUG   ][10514] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[salt.utils.lazy  :103 ][DEBUG   ][10514] Could not LazyLoad pkg.check_db: 'pkg.check_db' is not available.
[salt.loaded.int.module.cmdmod:385 ][INFO    ][10514] Executing command [u'apt-cache', u'-q', u'policy', u'php7.2-redis'] in directory '/root'
[salt.utils.lazy  :103 ][DEBUG   ][10514] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[salt.loaded.int.module.cmdmod:385 ][INFO    ][10514] Executing command [u'apt-get', u'-q', u'update'] in directory '/root'
[salt.loaded.int.module.cmdmod:385 ][INFO    ][10514] Executing command [u'dpkg', u'--get-selections', u'*'] in directory '/root'
[salt.loaded.int.module.cmdmod:385 ][INFO    ][10514] Executing command [u'systemd-run', u'--scope', u'apt-get', u'-q', u'-y', u'-o', u'DPkg::Options::=--force-confold', u'-o', u'DPkg::Options::=--force-confdef', u'install', u'php7.2-redis'] in directory '/root'
[salt.loaded.int.module.cmdmod:385 ][INFO    ][10514] Executing command [u'dpkg-query', u'--showformat', u'${Status} ${Package} ${Version} ${Architecture}', u'-W'] in directory '/root'
[salt.state       :292 ][ERROR   ][10514] Made the following changes:
'php-redis' changed from '3.1.6-1+0~20180104152216.4+stretch~1.gbp3cf38a' to '4.0.0-1+0~20180412074133.5+stretch~1.gbp24a357'
```
So minion tries to find is specified package installed. Found that is not installed. Install it and then check again and found that is still not installed.

Salt Version:
```
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

**Comment by mikeadamz** [comment]
This is a problem when upgrading the kernel. The state reports failed when in reality it was a success.

**Comment by jwcmd** [comment]
I'm seeing the same problem trying to install a sumologic collector.

```
/tmp/sumologic_collector.deb:
  file.managed:
    - source: https://collectors.sumologic.com/rest/download/deb/64
    - skip_verify: True
    - user: root
    - group: root
    - mode: 0744

sumologic_collector.deb Install:
  pkg.installed:
    - sources:
      - sumocollector: /tmp/sumologic_collector.deb
    - requires:
        - /tmp/sumologic_collector.deb
```

First attempt:

```
----------
          ID: sumologic_collector.deb Install
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: collector
     Started: 07:19:12.704615
    Duration: 12483.525 ms
     Changes:
              ----------
              sumocollector:
                  ----------
                  new:
                      1:19.253-14
                  old:
----------
```

Subsequent attempts:
```
----------
          ID: sumologic_collector.deb Install
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: collector
     Started: 07:21:42.156914
    Duration: 18476.412 ms
     Changes:
----------
```

Versions report:
```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1029-gcp
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Mapel88** [comment]
Having the same problem with pkg installation on windows.
Package was installed successfully but returned failed.

```
my-minion:
----------
          ID: install_packages_DWH
    Function: pkg.installed
      Result: False
     Comment: The following packages failed to install/update: python2.7
     Started: 06:14:05.667132
    Duration: 33287.504 ms
     Changes:
              ----------
              Python 2.7.16 (64-bit):
                  ----------
                  new:
                      2.7.16150
                  old:

Summary for my-minion
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  33.288 s
```


```

Salt Version:
           Salt: 2019.2.1

Dependency Versions:
           cffi: 1.13.2
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

```

**Comment by bilalcaliskan** [comment]
is there anything new with the issue?

regards.
