### ISSUE TITLE
win_wua.list returns 'nothing to return' in windows 2012 R2 server

### ISSUE THREAD

**Issue by nkrishnakishor** [saltstack/salt#45629]
Does not list available updates when run on Windows server 2012 R2

`salt windows-2012r2 win_wua.list`

Below is the version details of salt master and windows minion is also running the same version 2017.7.2

```
> salt-master --versions-report
> Salt Version:
>            Salt: 2017.7.2
> 
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: Not Installed
>       docker-py: Not Installed
>           gitdb: 0.6.4
>       gitpython: 1.0.1
>           ioflo: Not Installed
>          Jinja2: 2.7.2
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: 0.21.1
>            Mako: Not Installed
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.8
>    mysql-python: Not Installed
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>    pycryptodome: Not Installed
>          pygit2: Not Installed
>          Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
>    python-gnupg: Not Installed
>          PyYAML: 3.11
>           PyZMQ: 15.3.0
>            RAET: Not Installed
>           smmap: 0.9.0
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.1.4
> 
> System Versions:
>            dist: centos 7.4.1708 Core
>          locale: UTF-8
>         machine: x86_64
>         release: 3.10.0-327.el7.x86_64
>          system: Linux
>         version: CentOS Linux 7.4.1708 Core
> 
```

**Comment by garethgreenaway** [comment]
@twangboy Thoughts?

**Comment by twangboy** [comment]
Most of the problems I see with the `win_wua` module have to do with Windows update on the machine against which it is being run. The `win_wua` module is just a wrapper around Windows update. So, I wonder if Windows update runs correctly outside of salt and returns available updates. If it does, and salt isn't picking those up, then we have a problem. Otherwise, it's an issue with Windows update itself.

**Comment by nkrishnakishor** [comment]
@twangboy when we manually check for windows update in the server it shows me a list of updates available for installation but through salt it doesn't show up.

**Comment by twangboy** [comment]
What kind of updates? Drivers? `drivers` is set to `False` by default in the `win_wua.list` function so they won't be shown by salt.

I just spun up a 2012r2 box and did a list. Mine shows 2 updates available: .NET 4.7.1 and Malicious Software Remove Tool. When I enabled Microsoft Updates I got an additional option for Silverlight.

**Comment by twangboy** [comment]
Are you using a WSUS server?

**Comment by nkrishnakishor** [comment]
we use SCCM server but not for servers. This server doesn't have any WSUS entries also in registry.

**Comment by twangboy** [comment]
I think SCCM may use WSUS under the hood...
