### ISSUE TITLE
cmdmod  env, change user and runas implementation

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#45661]
### Description of Issue/Question

The existing code in modules/cmdmod.py runs  su or sudo to become the target user to collect environment vars first, then uses 

What should happen with runas as it should call `subprocess.Popen('su','su argurments','original cmd request to run')` instead. This then will result in:
- pam processing, including  pam adding/removing env settings and ulimit settings (for issues open for this e.g. #37768)
- Groups the user belong to setup

 Newer versions of Linux and sudo also process pam the same as su.   su/sudo in front of the command would give a better outcome, then this two step process.

The current code (below is summary of the code)
```
if runas:
  env_collected=subprocess.Popen(sudo/su python -c 'import sys, os, itertools; sys.stdout.write(\"\\0\".join(itertools.chain(*os.environ.items())))')
  subprocess.Popen('real command', env=env_collected)
```
Unfortunately this code is odd. It might work, but its not the way it should be implemented. My 2c

Alternative examples. 

```
bash -c 'Company=Saltstack PROG=salt printenv'  # General shell example
PROG=salt
Company=Saltstack
SHELL=/bin/bash
TERM=xterm
....

su - username -c 'Company=Salt\ stack PROG=salt printenv'  # runas i.e. cmd.runas_su
PROG=salt
Company=Salt stack
SHELL=/bin/bash
TERM=xterm
....

su username -c  'Company=Salt\ stack PROG=salt printenv' # runas cmd.runas_su
PROG=salt
Company=Salt stack
XDG_SESSION_ID=1
.....
```

It should be moved to something like this.
- `cmd.runas` change the uid/gid, fork()/runas.exe and no pam processing. POSIX and Windows. setting env supported changes (from minion/salt-call current env)
- `cmd.runas_su`  uses su to change users  POSIX Systems, educate commands can be prefixed with VARS
- `cmd.runas_sudo` uses sudo to change users POSIX Systems setting env, sudo will control if the env will get through.

This would also allow targeting the best features of each way.

**Comment by Ch3LL** [comment]
ping @saltstack/team-core can i get your opinions here on @damon-atkins 's proposal?

**Comment by twangboy** [comment]
It looks like it remains unchanged from a Windows perspective.

**Comment by damon-atkins** [comment]
Have not looked to see if this is still an issue.
