### ISSUE TITLE
GCE: Predefine disk size in salt profile

### ISSUE THREAD

**Issue by rung94** [saltstack/salt#45670]
### Description of Issue/Question
I've noticed after looking at the salt documentations that there doesn't seem to be a evident way to define the disk size of the instance in cloud.profiles.d/

Am I missing something here? any work around to create this result would be greatly helpful.

### Versions Report
Salt: 2015.5.10
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.4.8
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by Ch3LL** [comment]
are you refering to the image size?

its just `- size: g1-small` for example.

**Comment by rung94** [comment]
No, that is the machine size. I'm talking about disk size. example: 10gb, 20gb, 30gb, etc.

I see that salt allows defining a standard disk or ssd by using ex_disk_type: pd-ssd

I was hoping there would be a similar command like ex_disk_size: 50gb.

**Comment by rung94** [comment]
Here's my config

**profile:
 image: centos-7
  size: custom-1-7168-ext
  location: us-west1-b
  network: default
  subnetwork: default
  tags: '[]'
  metadata: '{"one": "1", "2": "two",
              "sshKeys":"
  ip_forwarding: True
  use_persistent_disk: True
  delete_boot_pd: False
  deploy: True
  make_master: False
  provider: gce-config
  # create an SSH username to be used since we can't ssh as root
  ssh_username: 
  # the SSH keyfile will be the one at root...
  ssh_keyfile: /root/.ssh/google_compute_engine**

**Comment by Ch3LL** [comment]
thanks for clarifying :)
ping @erjohnso do you know if this is possible currently?

**Comment by tehsu** [comment]
any updates on this? @erjohnso

**Comment by tehsu** [comment]
So, Google uses the image size for the boot disk size, I created an image from Google's image with a 50 gb disk and that solves this if anyone is looking for a workaround.

**Comment by rung94** [comment]
Yes, I came to that conclusion that salt is not strong in defining infrastructure like this. Using gcloud command line to define instances while pairing with salt functionality is more ideal.

**Comment by Ch3LL** [comment]
does @saltstack/team-cloud have any ideas here as well?

**Comment by alektant** [comment]
A bit late, but since the issue is still open thought I'd reply. I had need for this today and spent some time tracking down how to do it. It's possible through using `ex_disks_gce_struct`, which takes params defined in https://cloud.google.com/compute/docs/reference/rest/v1/instances under `disks[].initializeParams`

As an example, if `my-image` size is 30GB, I can alter the boot disk size in my profile to 50GB.
```
my-instance:
  provider: my-provider
  size: n1-standard-4
  ex_disks_gce_struct:
    - 
      autoDelete: true
      boot: true
      initializeParams:
        sourceImage: projects/my-project/global/images/my-image
        diskType: zones/us-central1-b/diskTypes/pd-standard
        diskSizeGb: 50
      type: PERSISTENT
```
