### ISSUE TITLE
file.check_hash [ValueError]: Bad hash format: '0755c87242fc4bcd052379302faccbac'

### ISSUE THREAD

**Issue by lord-i-will** [saltstack/salt#45680]
### Description of Issue/Question
According to https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.check_hash
I use java to connect with rest_cherrypy. But when i use file.check_hash, Errors happened.
So i  login saltmaster to test this command. Still errors. Described as followings:

1).Run this command：**salt 'host-10-101-17-102' file.check_hash /root/haha/ycc.txt 0755c87242fc4bcd052379302faccbac**

Then...Bang！Error as followings：

host-10-101-17-102:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1200, in _thread_return
        return_data = func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/file.py", line 563, in check_hash
        raise ValueError('Bad hash format: {0!r}'.format(file_hash))
    ValueError: Bad hash format: '0755c87242fc4bcd052379302faccbac'

2).Also tried this：**salt 'host-10-101-17-102' file.check_hash /root/haha/ycc.txt md5=0755c87242fc4bcd052379302faccbac**

still Error:

host-10-101-17-102:
    ERROR executing 'file.check_hash': The following keyword arguments are not valid: md5=0755c87242fc4bcd052379302faccbac

I just want to check target file's MD5.....What should i do ?
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
all default
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
I use java to connect with rest_cherrypy.
Program steps as followings:
1. salt 'host-10-101-17-102' cp.get_file salt://ycc/ycc.txt /root/haha/ycc.txt
2. salt 'host-10-101-17-102' file.chown /root/haha/ycc.txt ycc ycc
3. salt 'host-10-101-17-102' file.set_mode /root/haha/ycc.txt 0755
4. salt 'host-10-101-17-102' file.check_hash /root/haha/ycc.txt 0755c87242fc4bcd052379302faccbac

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[root@sz02 salt]# salt --versions-report
           Salt: 2015.5.10
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
         Jinja2: 2.7.2
       M2Crypto: 0.20.2
 msgpack-python: 0.4.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: 0.5.0
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by gtmanfred** [comment]
because there is an equal sign, you will need to specify the variable name.

```
salt 'host-10-101-17-102' file.check_hash /root/haha/ycc.txt file_hash=md5=0755c87242fc4bcd052379302faccbac
```

Not having the `md5` part wasn't added until a newer version of salt.

I highly recommend upgrading to a newer version.

http://repo.saltstack.com/

**Comment by lord-i-will** [comment]
@gtmanfred thx so much~
