### ISSUE TITLE
HKEY_CLASSES_ROOT missing from available hives in reg module

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#45691]
### Description of Issue/Question
HKEY_CLASSES_ROOT is missing from the definition of hkeys in the Registry class of the reg.py execution module, which keeps it from being available for modification/etc by salt

@saltstack/team-windows  perhaps there is a reason it is left out?  Probably not modified very often for sure...

### Setup
Example state:
'''
set_wmi_endpoint_config:
  reg.present:
    - name: 'HKEY_CLASSES_ROOT\AppID\{8BC3F05E-D86B-11D0-A075-00C04FB68820}'
    - vname: EndPoints
    - vdata: 'ncacn_ip_tcp,0,24158'
    - vtype: REG_MULTI_SZ
'''

### Steps to Reproduce Issue
attempt to apply above state, returns a key error when attempting to get the win32con value for HKEY_CLASSES_ROOT in the hkeys dict:
'''
          ID: set_wmi_endpoint_config
    Function: reg.present
        Name: HKEY_CLASSES_ROOT\AppID\{8BC3F05E-D86B-11D0-A075-00C04FB68820}
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\salt\bin\lib\site-packages\salt\state.py", line 1746, in call
                  **cdata['kwargs'])
                File "C:\salt\bin\lib\site-packages\salt\loader.py", line 1704, in wrapper
                  return f(*args, **kwargs)
                File "C:\salt\bin\lib\site-packages\salt\states\reg.py", line 186, in present
                  use_32bit_registry=use_32bit_registry)
                File "C:\salt\bin\lib\site-packages\salt\modules\reg.py", line 435, in read_value
                  hkey = registry.hkeys[local_hive]
              KeyError: u'HKEY_CLASSES_ROOT'
     Started: 15:40:20.528000
    Duration: 15.0 ms
     Changes:
'''

### Versions Report
2016.11, 2017.7

**Comment by twangboy** [comment]
#45694 adds support.

**Comment by damon-atkins** [comment]
https://msdn.microsoft.com/en-us/library/windows/desktop/ms724475(v=vs.85).aspx
