### ISSUE TITLE
Windows patch management, possibility to block specific update.

### ISSUE THREAD

**Issue by martinohansen** [saltstack/salt#45739]
Hi, 

We are looking at saltstack for linux and **windows** patch management, and I have a quick question if thats okay. 

Is it possible, on windows (ranging from window 7/2008 r2 to 10/2016), to hold back or block a specific update from being installed?

Thanks in advance. 

Best regards,
Martin Hansen

**Comment by gtmanfred** [comment]
@twangboy is this possible?

Thanks,
Daniel

**Comment by twangboy** [comment]
Maybe in versions previous to Server2016/Win10. The longest you can delay a patch in the Server2016/Win10 is 1 year. After that it forces the update.

With all versions salt leverages the Windows Update Agent to apply patches. You could optionally turn off Windows update and apply patches using the win_dism module. You would have to manage the `.msu` files yourself.

**Comment by martinohansen** [comment]
Thanks for the input
