### ISSUE TITLE
Escaping single quote

### ISSUE THREAD

**Issue by hibbert** [saltstack/salt#45765]
### Setup
Unable to figure out a way of escaping single quotes have tried the following:-

"'"
''

Yaml escaping such as

{{ '{{' }}
{% raw %}{% endraw %}

### Steps to Reproduce Issue
The string I need to put in yaml is:-
```
 events('priority:all tags:env:prod,service:hosttype "Datadog agent * started on *"').by('host').rollup('count').last('30m') > 4
```

I would also like to have jinja templating in there i.e. service:{{ host_type }} for example

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
You should just be able to put it in unquoted?

```
$ cat test.yml
thing: events('priority:all tags:env:prod,service:hosttype "Datadog agent * started on *"').by('host').rollup('count').last('30m') > 4
$ python
Python 2.7.14 (default, Oct  3 2017, 13:47:00)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import salt.utils.yaml
>>> open('test.yml', 'r')
<open file 'test.yml', mode 'r' at 0x1078af030>
>>> salt.utils.yaml.load(_)
{'thing': 'events(\'priority:all tags:env:prod,service:hosttype "Datadog agent * started on *"\').by(\'host\').rollup(\'count\').last(\'30m\') > 4'}
```

All the jinja will be rendered first, so it just needs to be valid yaml afterwards, have you tried just dropping in 

```
 events('priority:all tags:env:prod,service:{{host_type}} "Datadog agent * started on *"').by('host').rollup('count').last('30m') > 4
```

as is? without surrounding it by quotes?

Thanks,
Daniel

**Comment by hibbert** [comment]
Thanks for the tip. It's a bit more complicated perhaps as that string is coming from a pillar to an sls (which seems to stript out the single quote at the start anyway), so the sls surrounds the pillar value in single quotes. Taking out the single quotes on the sls and in the pillar file seemed to work for this monitor but caused problems on other so I needed to add |yaml_dquote to the end. This seems to have worked okay

**Comment by gtmanfred** [comment]
Can you give me a full example of the setup you are using right now that isn't working, so that I can see that and offer a fix?

Thanks,
Daniel
