### ISSUE TITLE
UnicodeEncodeError whilst trying to run a subprocess

### ISSUE THREAD

**Issue by unixtastic** [saltstack/salt#45783]
### Description of Issue/Question
Salt states that start a subprocess fail on a UnicodeEncodeError. This affects many kinds of salt states.

          ID: clean_tmp
    Function: cron.present
        Name: find /tmp -name test.tmp -delete
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1843, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/cron.py", line 349, in present
                  identifier=identifier)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cron.py", line 461, in set_job
                  lst = list_tab(user)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cron.py", line 293, in list_tab
                  data = raw_cron(user)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cron.py", line 270, in raw_cron
                  python_shell=False)).splitlines(True)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 1318, in run_stdout
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 547, in _run
                  proc = salt.utils.timed_subprocess.TimedProc(cmd, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/utils/timed_subprocess.py", line 42, in __init__
                  self.process = subprocess.Popen(args, **kwargs)
                File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
                  errread, errwrite)
                File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
                  raise child_exception
              UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-32: ordinal not in range(128)
     Started: 17:41:19.429815
    Duration: 106.483 ms
     Changes:   

### Setup
cron.present triggers this bug, as do many other states that create a subprocess.

### Steps to Reproduce Issue
Use salt version 2017.7.2 on ubuntu 16.04.3 LTS to install a cron job.

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-96-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by unixtastic** [comment]
Theis appears related to, but not the same as, other unicode issues reported here. It appears related to unicode being inserted into the subprocess's environment. The following patch fixes this for me:

```
diff --git a/salt/modules/cmdmod.py b/salt/modules/cmdmod.py
index cd23383654..d51ceb2fa9 100644
--- a/salt/modules/cmdmod.py
+++ b/salt/modules/cmdmod.py
@@ -447,9 +447,10 @@ def _run(cmd,
             # Encode unicode kwargs to filesystem encoding to avoid a
             # UnicodeEncodeError when the subprocess is invoked.
             fse = sys.getfilesystemencoding()
+            encoded_env = {}
             for key, val in six.iteritems(env):
-                if isinstance(val, six.text_type):
-                    env[key] = val.encode(fse)
+                encoded_env[key.encode(fse)] = val.encode(fse)
+            env = encoded_env
         except ValueError:
             raise CommandExecutionError(
                 'Environment could not be retrieved for User \'{0}\''.format(
```

**Comment by gtmanfred** [comment]
Would you mind submitting this as a PR to the 2017.7 branch?

https://docs.saltstack.com/en/latest/topics/development/contributing.html

Thanks,
Daniel

**Comment by damon-atkins** [comment]
Look at the code in the existing oxygen branch. However PY2 2016,2016 versions of salt do not support Unicode.  Your would need to run PY3 2017.   Oxygen release will be the first release to support International Character sets.

**Comment by unixtastic** [comment]
The PR is at https://github.com/saltstack/salt/pull/45793
