### ISSUE TITLE
LIBCLOUD_VERSION_INFO tuple for rc versions

### ISSUE THREAD

**Issue by nnew2** [saltstack/salt#45798]
### Description of Issue/Question
When running "salt-cloud -p myprofile.conf ourname" from release candidate 2.0.0rc2 
the following tuple fails because it expect each block to be of type int.

```
LIBCLOUD_VERSION_INFO = tuple([
    int(part) for part in libcloud.__version__.replace('-', '.').split('.')[:3]
])
```
.../site-packages/salt/cloud/libcloudfuncs.py [l=29]

Error

> ValueError: invalid literal for int() with base 10: '0rc2'

Installed via yum repo on Centos 7.4.1708

**Comment by garethgreenaway** [comment]
@nnew2 Thanks for the report.

**Comment by gtmanfred** [comment]
What version of salt are you running?

This should was fixed a while ago.
