### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xiang5** [saltstack/salt#45792]
### Description of Issue/Question
when run the command as follow will clean out crontab of the target machine
salt "*" cmd.run "su test -c crontab -l"

the right command line should be 
salt "*" cmd.run "su test -c 'crontab -l' " 

### Versions Report
           Salt: 2015.5.8
         Python: 2.6.6
         Jinja2: 2.2.1
       M2Crypto: 0.20.2
       msgpack-python: 0.4.6
       pycrypto: 2.0.1
        PyYAML: 3.10
         PyZMQ: 14.3.1
           ZMQ: 3.2.5

**Comment by garethgreenaway** [comment]
@xiang5 Thanks for the report.  Are you seeing the above in a particular module or particular documentation example?
