### ISSUE TITLE
Execution module victorops throws an error "RuntimeError: dictionary changed size during iteration"

### ISSUE THREAD

**Issue by bgridley** [saltstack/salt#45805]
### Description of Issue/Question

victorops execution module returns an error for all paramters tested. Example: 

salt '*' victorops.create_event message_type='INFO'
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/victorops.py", line 209, in create_event
        method='POST'
      File "/usr/lib/python2.7/dist-packages/salt/modules/victorops.py", line 91, in _query
        opts=__opts__,
      File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 534, in query
        result_cookies = parse_cookie_header(result_headers['Set-Cookie'])
      File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 858, in parse_cookie_header
        for item in cookie:
    RuntimeError: dictionary changed size during iteration

### Setup
Make sure relevant API key exists as described in the salt documentation for the module.victorops.

### Steps to Reproduce Issue

salt '*' victorops.create_event routing_key=ops:ops message_type=INFO entity_id='ops/test' -l debug

[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/68/7c2eb93795f86a6015baefdc640a002c3246f9f61f9de361559a344f2ca86b/.minions.p
[DEBUG   ] get_iter_returns for jid 20180131172903618272 sent to set(['salt']) will timeout at 17:29:08.629034
[DEBUG   ] jid 20180131172903618272 return from salt
[DEBUG   ] return event: {'salt': {'jid': '20180131172903618272', 'ret': 'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1470, in _thread_return\n    return_data = executor.execute()\n  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute\n    return self.func(*self.args, **self.kwargs)\n  File "/usr/lib/python2.7/dist-packages/salt/modules/victorops.py", line 209, in create_event\n    method=\'POST\'\n  File "/usr/lib/python2.7/dist-packages/salt/modules/victorops.py", line 91, in _query\n    opts=__opts__,\n  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 534, in query\n    result_cookies = parse_cookie_header(result_headers[\'Set-Cookie\'])\n  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 858, in parse_cookie_header\n    for item in cookie:\nRuntimeError: dictionary changed size during iteration\n', 'out': 'nested'}}
[DEBUG   ] LazyLoaded nested.output
salt:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1470, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/victorops.py", line 209, in create_event
        method='POST'
      File "/usr/lib/python2.7/dist-packages/salt/modules/victorops.py", line 91, in _query
        opts=__opts__,
      File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 534, in query
        result_cookies = parse_cookie_header(result_headers['Set-Cookie'])
      File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 858, in parse_cookie_header
        for item in cookie:
    RuntimeError: dictionary changed size during iteration

### Versions Report

salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov  2 2017, 19:20:38)
   python-gnupg: 0.3.8
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.9.77-31.58.amzn1.x86_64
         system: Linux
        version: Not Installed

**Comment by gtmanfred** [comment]
I have opened a PR to fix this here https://github.com/saltstack/salt/pull/45814

Thanks for reporting!
Daniel
