### ISSUE TITLE
How to check the connection IPs?

### ISSUE THREAD

**Issue by wsw70** [saltstack/salt#45806]
Is there a way to check, **on the master**

-  what is the **minion** IP a minion connected **from** (assuming the **minion** has several IPs)?
- what is the **server** IP the minion connected **to** (provided the **server** has several IPs)?

**Comment by gtmanfred** [comment]
I do not believe that you can show which ip the minion is connecting to, but to show which ip the minion is connected to, you could use the manage.present runner

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.manage.html#salt.runners.manage.present

`salt-run manage.present show_ipv4=true`

Daniel

**Comment by wsw70** [comment]
@gtmanfred Thank you Daniel. 

This is a very useful command, though it shows that some of the minions are connected via `127.0.0.1`, which is not the case (they are remote devices)
```
sent099:
    127.0.0.1
```

**Comment by wsw70** [comment]
OK, the ones connected via `127.0.0.1` were actually though forwarded ports (which show up as `127.0.0.1`). Thanks for the help!
