### ISSUE TITLE
modules/boto3_route53.change_resource_record_sets inifinite loop

### ISSUE THREAD

**Issue by nullify005** [saltstack/salt#45816]
### Description of Issue/Question

When running modules.boto3_route53.change_resource_record_sets the code gets stuck in an infinite loop when the API refuses to do the work, but doesn't return a rate limiting code which might trigger a retry.

An example is say attempting to change a pre-existing record which is a CNAME to an A, which the API doesn't allow for 

I've raised https://github.com/saltstack/salt/pull/45815 to fix it

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
Thanks for the pr to fix this!
Daniel
