### ISSUE TITLE
states/boto3_route53.rr_present NoneType when ResourceRecords are not present from API

### ISSUE THREAD

**Issue by nullify005** [saltstack/salt#45817]
### Description of Issue/Question

When attempting to compare the local changes with the remote, in the case where the DNS entry is based on an AliasTarget (thereby meaning ResourceRecords are not present from the upstream API) salt doesn't first check to see if it's None before attempting to iterate over it.

This ends up throwing the following error:
```
                File "/home/jenkins/jenkins/workspace/aws-ami-cyan@2/var/cache/salt/minion/extmods/states/boto_helper.py", line 67, in route53_cloudfront_present
                  return __states__['boto3_route53.rr_present'](name, DomainName=DomainName, Name=name, Type='A', AliasTarget=AliasTarget, region=region, key=key, keyid=keyid)
                File "/home/jenkins/jenkins/workspace/aws-ami-cyan@2/lib/python2.7/site-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/home/jenkins/jenkins/workspace/aws-ami-cyan@2/lib/python2.7/site-packages/salt/states/boto3_route53.py", line 679, in rr_present
                  if ResourceRecords != sorted(rrset.get('ResourceRecords'), key=lambda x: x['Value']):
              TypeError: 'NoneType' object is not iterable
```

I've raised https://github.com/saltstack/salt/pull/45815 to check whether it's None before iterating over it.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
Thanks for the PR to fix this.
Daniel
