### ISSUE TITLE
saltutil.running shows no job running but jobs.lookup_jid shows  state.highstate is rurnning

### ISSUE THREAD

**Issue by qiangshui** [saltstack/salt#45818]
### Description of Issue/Question
There is a job which jid was 20180131204010595907,i execute "salt-run jobs.lookup_jid 20180131204010595907" and print the output, it show that the job is finished.
Then I run anothor job which jid was 20180131204353461703, I exexute "salt-run jobs.lookup_jid
20180131204353461703", it show 
![default](https://user-images.githubusercontent.com/24819310/35659273-5102af3a-0740-11e8-9e9b-51f9afb6fbe8.png)
this means this job is not finished, right?
But I execute “salt wxapi[1-9] saltutil.running”, it only return the minion's name, this should means there is no jobs running on these minions.
So, did on earth the job 20180131204010595907 or 20180131204353461703 finished yet?

### Versions Report
Salt Version:
           Salt: 2016.11.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Jul 23 2015, 15:22:56)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.11.25.el6.ucloud.x86_64
         system: Linux
        version: CentOS 6.5 Final

**Comment by gtmanfred** [comment]
It is possible that `20180131204010595907` was not finished on one of the minions, even though it was finished on all the other minions. And then it finished between that time, and when you ran saltutil.running.

If that is not the case, can you please provide me with an example of this happening so that I can replicate it?

Thanks,
Daniel
