### ISSUE TITLE
Extra line gets added for windows hosts that use file.managed with contents_pillar option

### ISSUE THREAD

**Issue by poliva83** [saltstack/salt#45812]
### Description of Issue/Question
An extra line gets added for windows hosts in 2017.7.2 that use file.managed with contents_pillar option. 

Its because use of `contents.endswith(os.linesep)`:
https://github.com/saltstack/salt/blob/v2017.7.2/salt/states/file.py#L2207 
Since os.linesep for windows is expecting '\r\n' but pillar getting returned only has '\n' line endings:
https://github.com/saltstack/salt/blob/v2017.7.2/salt/states/file.py#L2142).

### Setup
sample pillar file snippet:
```
ssl:
    cert_pem: |
      -----BEGIN CERTIFICATE-----
      blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
      blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
      blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
      blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah
      blahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblahblah      
      -----END CERTIFICATE-----
```
sample state file snippet:
```
c:/somepath/ssl/cert.pem:
  file.managed:
    - contents_pillar: ssl:cert_pem
```
### Steps to Reproduce Issue
Execute state and review content managed file it has extra os.linesep (ends in '\n\r\n').

### Versions Report
PS > salt-call --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free

**Comment by poliva83** [comment]
Proposed solution would be to change the check to:
```
if contents_newline and not (contents.endswith(os.linesep) or contents.endswith('\n')):
    contents += os.linesep
```

**Comment by gtmanfred** [comment]
So, the reason that the newline is added is because of posix compliance, since windows doesn't really care about posix anyway, i would say we could probably just skip that whole step if it is being run on a windows machine.

**Comment by twangboy** [comment]
It looks like you have to set `contents_newline: False` if you don't want a new line. The default is True.

**Comment by poliva83** [comment]
@twangboy I never had `contents_newline: False` set when using 2016.3.6 and this extra unnecessary newline was not added.

```
contents_newline
: True
New in version 2014.7.0.

Changed in version 2015.8.4: This option is now ignored if the contents being deployed contain binary data.

If True, files managed using contents, contents_pillar, or contents_grains will have a newline added to the end of the file if one is not present. Setting this option to False will omit this final newline.
```
Technically the wording here says `will have a newline added to the end of the file if one is not present`. IMO the detection of a newline is broken for windows hosts.

**Comment by poliva83** [comment]
@twangboy It does seem odd though that the file.managed code doesn't appear that different between `2017.7.2` and `2016.3.6`. So I am now wondering if the `__salt__['pillar.get'](contents_pillar, __NOT_FOUND, delimiter=contents_delimiter)` may now be adding Unix line ending. I am using a `2017.7.2` salt-master for this deployment vs `2016.3.6` salt-master when I didn't see this issue.

I will need to test this out more tomorrow.

**Comment by poliva83** [comment]
This regression seems to have been fixed in 2017.7.5 and 2018.8.3. Please feel free to close.

**Comment by ChrisMcKenzie** [comment]
it appears that this PR https://github.com/saltstack/salt/pull/51252 totally breaks `contents_newline: False` if I understand it correctly this would always add a newline

**Comment by ChrisMcKenzie** [comment]
@dwoz not sure if you are aware of the above message.
