### ISSUE TITLE
Can a salt master provide a state to unavailable minions?

### ISSUE THREAD

**Issue by wsw70** [saltstack/salt#45813]
### Background

I have several servers which run a service I develop. All of them should have the same copy of the service.

To ensure deployment and up-to-dateness I use Ansible, with an idempotent  playbook which deploys the service. Since the servers are on an unreliable network, I have to run the playbook periodically (in a cron job) to reach the servers which may not have been available before.

### Problem

I was under the impression that the SaltStack philosophy is different: I though I could just *"set a state, compile it and offer to a set of minions. These minions would then, at their own leisure, come to the master and get whatever they need to do"*.

This does not seem to be the case: the minions which were not available at deployment time are skipped.

### Question 

Is there a mechanism which would allow for an asynchronous deployment, in the sense that a state set on the master **one time only** would then be pulled and applied by the minions (to themselves) once they are ready / can reach the master? 

Specifically, without the need to continuously re-offer the same state to all minions, in the hope that the ones which were unavailable in the past are now capable to get the update.

*initially asked on [SO](https://stackoverflow.com/q/48364640/903011)

**Comment by gtmanfred** [comment]
The minion can ask for the state whenever it wants.

So with the master/minion you have a minion always running and connected to the master, so you would be able to send the command with `salt <target> state.apply`.

If you want the specific minion to run the command, you would use `salt-call`, then you can use any of the modules that you would normally run from the master.

`salt-call state.apply`

This starts up a separate minion instance, connects to the master, and pulls all the information down, and then runs it.

Daniel

**Comment by wsw70** [comment]
@gtmanfred Thank you - sorry  if I was not clear enough.

What I meant is that I have a state to apply (say, the fact that a service must be up). When applying the state, it is applied to minions which are currently up. The ones which are down do not get the state.

This means that, in the case of an unstable environment (minions being up and down), I need to continuously apply the state from the master (via a cron job for instance).  This is not a huge problem: the states are hopefully idempotent so the minions which get the state applied all the time (because they happen to be stable and up all the time) are not impacted (but still)

I was hoping for a way to apply the state in a generic way and then a minion which is available would get it when it is available. This is a kind of asynchronous state application: the master decides that a state is to be applied, and the minions get it (but not when they are connected at that precise moment).

**Comment by gtmanfred** [comment]
That is not possible.

The minions connect to the publish port/bus and the master puts new jobs on that bus.  Then the minion picks it up and runs the job, if the minion is not connected when the job is published, then it will not see the job.

**Comment by wsw70** [comment]
@gtmanfred Thanks Daniel, this is now clear. And thanks for all the help, and the product!
