### ISSUE TITLE
XenServer Provisioning errors out on this line. removing it succeeds.

### ISSUE THREAD

**Issue by Epiclemonaid** [saltstack/salt#45849]
**Description of Issue/Question**
https://github.com/saltstack/salt/blob/11f73910a6e810ee90c30d0c0a1d3dc672b10a38/salt/utils/cloud.py#L468

**Setup**
I am running the develop branch of salt working with xencenter. Ive run into a few problems here are the stack traces below. and what I've done to fix them. 

```
 [ERROR   ] Failed to create VM lv-dev-backend01. Configuration value u'provider' needs to be set
 Traceback (most recent call last):
   File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1284, in create
     output = self.clouds[func](vm_)
   File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/xen.py", line 644, in create
     _deploy_salt_minion(name, session, vm_)
   File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/xen.py", line 681, in _deploy_salt_minion
     boot_ret = __utils__['cloud.bootstrap'](vm_, __opts__)
   File "/usr/lib/python2.7/site-packages/salt/utils/cloud.py", line 468, in bootstrap
     'provider': vm_['provider'],
 KeyError: u'provider'
 [INFO    ] Complete`
```

my config 

```
myxen:
   driver: xen
   url: http://xxxxxx
   user: root
   password: xxxxxxxxx
```

```
 centos:
   user: root
   password: xxxxxxxxxxx
   provider: myxen
   image: my-image
   storage_repo: 'Local storage'
   clone: True
   minion:
     master: xxxxxxxxx
```
 

this is called in the Xen.py

 ```
def _deploy_salt_minion(name, session, vm_):
     Deploy salt minion during create()
     # Get bootstrap values
     vm_['ssh_host'] = get_vm_ip(name, session)
     vm_['user'] = vm_.get('user', 'root')
     vm_['password'] = vm_.get('password', 'p@ssw0rd!')
     log.debug('{} has IP of {}'.format(name, vm_['ssh_host']))
     # Bootstrap Salt minion!
     if vm_['ssh_host'] is not None:
         log.info('Installing Salt minion  on {0}'.format(name))
         boot_ret = __utils__['cloud.bootstrap'](vm_, __opts__)
         log.debug('boot return: {}'.format(boot_ret))
 
```

removing the line lets the proccess proceed.

**Versions Report**

```
Salt Version:
           Salt: 2018.2.0-2027-ge8ca974

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Epiclemonaid** [comment]
edited to meet submission format.

**Comment by gtmanfred** [comment]
cloud you try deleting this block from the `create` function?

```
    # Since using "provider: <provider-engine>" is deprecated, alias provider
    # to use driver: "driver: <provider-engine>"
    if 'provider' in vm_:
        vm_['driver'] = vm_.pop('provider')
```

Because that is not true anymore, provider and driver should both be specified.

If this fixes the problem I will open a PR for it.

Thanks!
Daniel

**Comment by Epiclemonaid** [comment]
sorry went on vacation to australia looks like that works i reverted my files changes and deleted that section. 

`[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt01
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] All tools for virtual hardware identification failed to execute because they do not exist on the system running this instance or the user does not have the necessary permissions to execute them. Grains output might not be accurate.
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /srv/saltstack/salt/etc/cloud/maps/vpc-lv
[DEBUG   ] Jinja search path: [u'/var/cache/salt/cloud/files/base']
[PROFILE ] Time (in seconds) to render '/srv/saltstack/salt/etc/cloud/maps/vpc-lv' using 'jinja' renderer: 0.00454902648926
[DEBUG   ] Rendered data from file: /srv/saltstack/salt/etc/cloud/maps/vpc-lv:
centos:
  - backend01
  - backend02
  - backend03
  - backend04
  - backend05
  - backend06
  - backend07
  - backend08
  - cattle01
  - cattle02
  - cattle03
[DEBUG   ] Results of YAML rendering:
OrderedDict([('centos', ['backend01', 'backend02', 'backend03', 'backend04', 'backend05', 'backend06', 'backend07', 'backend08', 'cattle01', 'cattle02', 'cattle03'])])
[PROFILE ] Time (in seconds) to render '/srv/saltstack/salt/etc/cloud/maps/vpc-lv' using 'yaml' renderer: 0.003005027771
[INFO    ] Applying map from '/srv/saltstack/salt/etc/cloud/maps/vpc-lv'.
[DEBUG   ] Could not LazyLoad xen.optimize_providers: 'xen.optimize_providers' is not available.
[DEBUG   ] The 'xen' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad xen.list_nodes_min: 'xen.list_nodes_min' is not available.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt01
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] url: http://10.3.8.97 user: root password: XXX-pw-redacted-XXX, originator: salt_cloud_xen_driver
[DEBUG   ] VM guest metrics returned for instance: backend02 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: backend06 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: Copy of  dev-cattle-template 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: lv-stage-ad01 0/ip: 169.254.108.241
[DEBUG   ] VM guest metrics returned for instance: backend01 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: bind01 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: backend04 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: cattle02 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: backend08 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: cattle03 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: cattle01 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: backend03 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: backend05 0/ip: 192.168.x.x
[DEBUG   ] VM guest metrics returned for instance: backend07 0/ip: 192.168.x.x
[WARNING ] 'cattle03' already exists, removing from the create map.
[WARNING ] 'backend06' already exists, removing from the create map.
[WARNING ] 'cattle01' already exists, removing from the create map.
[WARNING ] 'backend02' already exists, removing from the create map.
[WARNING ] 'backend01' already exists, removing from the create map.
[WARNING ] 'cattle02' already exists, removing from the create map.
[WARNING ] 'backend05' already exists, removing from the create map.
[WARNING ] 'backend07' already exists, removing from the create map.
[WARNING ] 'backend04' already exists, removing from the create map.
[WARNING ] 'backend03' already exists, removing from the create map.
[WARNING ] 'backend08' already exists, removing from the create map.
[DEBUG   ] LazyLoaded nested.output`

**Comment by gtmanfred** [comment]
Perfect, thanks!

**Comment by gtmanfred** [comment]
I have submitted https://github.com/saltstack/salt/pull/46168

We have tagged rc1 for 2018.3, so we are working on getting that stable, and the only things that are going into it are stuff to fix the test suite right now.  This change will not make it into the release candidate or 2018.3.0, but it will be in 2018.3.1.

Thanks!
Daniel
