### ISSUE TITLE
Salt minion - startup network timing hostname/ID issue

### ISSUE THREAD

**Issue by wesleyarthur** [saltstack/salt#45848]
I'm trying to dynamically provision about 150 servers.  I'm using salt reactor/beacons to auto accept the key when the servers boot based on the minion id.  When some servers boot, it appears that the networking starts late (about 26 seconds) after salt-minion has already started, and instead of them checking into the salt master with their proper hostname/minion id, they try to authenticate with just "localhost" continuously and get rejected.

It almost seems like I need to alter the salt systemd or something to delay the startup of the salt-minion until eth0 with network manager finally get's it's hostname/networking form the dhcp server.

Has anyone seen this behavour?

### Setup
Salt master on centos 7.4, and salt minions are Centos 7.

### Steps to Reproduce Issue
-  Start a bunch of salt minions with a reactor that auto approves their keys if their ID matches an allowed one.
- On the salt master I can see a bunch of the servers listed with salt-key that are trying to register as "localhost" as their minion id.

### Versions Report
Salt 2017.2.2

**Comment by gtmanfred** [comment]
I have not seen this before but if you add this to the minion:

>/etc/systemd/system/salt-minion.service.d/after.conf
```
[Unit]
After=network.target
```

Does this problem go away?

Thanks,
Daniel
