### ISSUE TITLE
Minion sign to Master with different id

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#45856]
Hey,

I have an environment of one master and few minions.
Now, I'm trying to set the minion ID's using the minion configuration file (/etc/salt/minion).
After setting the ID of the minion I'm restarting the minion and waiting for it to sign to the master and here the trouble begins.

Recently I added few server with the following ID:
101444_263102810263
102457_596102810230
And they have identify with different ID to the Master which is:
101444263102810263
102457596102810230
*The minion report this ID to its grain (and not the expected one)
I have another long id that are signed with the expected ID for example: 1563_CJT56180TR

Now can I solve this issue.
I need the minion to 'report' the ID as i assign it to him. (with the '_' in this case).

### Setup
Master Version: 2017.7.2
Minion Version: 2016.11.3 running on Ubuntu 12.04
Minion Version: 2017.7.2 running on Ubuntu 16.04
Two different versions with the same problem.

Best Regards.
Amiram M.

**Comment by gtmanfred** [comment]
The disappearing underscore is an idiosyncracy with yaml.

```
Python 2.7.14 (default, Oct  3 2017, 13:47:00)
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import yaml
>>> open('this.yml', 'r')
<open file 'this.yml', mode 'r' at 0x10afc2c90>
>>> yaml.load(_)
101444263102810263
```

What you will want to do is quote it, so that yaml does not try to "correct" it.

>/etc/salt/minion
```
id: '101444_263102810263'
```

**Comment by AmiramMaimon** [comment]
Hey,

Thank you for the response, it worked like a charm.

Amiram
