### ISSUE TITLE
configure master_job_cache: mysql, concurrent requests saltstack http api, but sometimes appear 401

### ISSUE THREAD

**Issue by CharlesQQ** [saltstack/salt#45857]
I user requests and threading to request the salt-api, but sometimes return the like this:
HTTPSConnectionPool(host='dev.salt.biz.sogou', port=9000): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x0000000015F6A438>: Failed to establish a  new connection: [Errno 10060] ',));

after that, I request again, return me 401; it means token expired

**Comment by gtmanfred** [comment]
Can you provide me with your configs, and possibly a way to replicate this issue?

Thanks,
Daniel

**Comment by CharlesQQ** [comment]
The salt master config:
[saltstack@xxx]cat /etc/salt/master
default_include: /opt/local/saltstack/conf/master/*.conf
transport: tcp
publish_port: 4505
user: saltstack
ret_port: 4506
pidfile: /opt/local/saltstack/run/salt-master.pid
root_dir: /opt/local/saltstack
conf_file: /etc/salt/master
pki_dir: /opt/local/saltstack/pki/master
cachedir: /opt/local/saltstack/cache/master
module_dirs:
   - /opt/salt/salt-agent
keep_jobs: 10000
timeout: 5
show_timeout: True
sock_dir: /opt/local/saltstack/run
job_cache: True
minion_data_cache: True
max_open_files: 100000
worker_threads: 80
publish_session: 864000
auto_accept: False
log_file: /opt/local/saltstack/log/master/master.log
key_logfile: /opt/local/saltstack/log/master/key.log
log_level: warning 
log_level_logfile: debug
log_datefmt: '%H:%M:%S'
log_datefmt_logfile: '%Y-%m-%d %H:%M:%S'
log_fmt_logfile: '%(asctime)s.%(msecs)03.0f [%(name)-17s] [%(levelname)-8s] %(message)s'

token_expire: 6000
keep_jobs: 1 
mysql.host: 'x.x.x.x'
mysql.user: 'salt'
mysql.pass: 'xxxxx'
mysql.db: 'salt'
mysql.port: 3306
master_job_cache: mysql

The salt minion config: 
[saltstack@xxx]$ cat /etc/salt/minion
default_include: /opt/local/saltstack/conf/minion/*.conf
master:
    - x.x.x.x
transport: tcp

master_port: 4506
user: saltstack
pidfile: /opt/local/saltstack/run/salt-minion.pid
conf_file: /etc/salt/minion
pki_dir: /opt/local/saltstack/pki/minion
cachedir: /opt/local/saltstack/cache/minion
cache_jobs: True
sock_dir: /opt/local/saltstack/run
master_tries: -1
module_dirs: [/opt/bizsalt/salt-agent]
log_file: /opt/local/saltstack/log/minion/minion.log
key_logfile: /opt/local/saltstack/log/minion/key.log
log_level: warning
log_level_logfile: debug
log_datefmt: '%H:%M:%S'
log_datefmt_logfile: '%Y-%m-%d %H:%M:%S'
log_fmt_logfile: '%(asctime)s.%(msecs)03.0f [%(name)-17s] [%(levelname)-8s] %(message)s'



[saltstack@xxx~]$ /opt/local/saltstack/python/bin/salt --versions-report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 10.2.1
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Sep 20 2017, 21:18:32)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.2
 
System Versions:
           dist: redhat 6.6 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-504.23.4.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.6 Santiago

 The above are all config
 Thanks
 Charles
