### ISSUE TITLE
REG Read Not working

### ISSUE THREAD

**Issue by darrenjlowe** [saltstack/salt#45869]
After upgrading to 2017.7.3 on master and minion, reading the registry in a state no longer works

### Setup
Salt State File

{% set selectedusersid = salt['reg.read_value']('HKEY_LOCAL_MACHINE', 'SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI', 'SelectedUserSID') %}

Disabletherestofthevisualeffects:
 reg.present:
   - name: 'HKEY_USERS\{{ selectedusersid.vdata }}\Control Panel\Desktop'
   - vname: UserPreferencesMask
   - vdata: 90,12,01,80
   - vtype: REG_BINARY

Error shows

       ID: Disabletherestofthevisualeffects
   Function: reg.present
       Name: HKEY_USERS\None\Control Panel\Desktop
     Result: False
    Comment: Failed to add HKEY_USERS\None\Control Panel\Desktop to HKEY_USERS\None\Control Panel\Desktop
    Started: 14:41:28.850000
   Duration: 0.0 ms
    Changes:

### Steps to Reproduce Issue
Create a Statefile with these settings, this should read the registry to get the Users SID, and then add it into the HKUser path

### Versions Report

Salt Master

Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

Salt Minion

Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.15063  Multiprocessor Free

(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@twangboy Any ideas on this one?

**Comment by darrenjlowe** [comment]
If I run from the salt master

salt "MACHINENAME" reg.read_value HKEY_LOCAL_MACHINE 'SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI' 'SelectedUserSID'

The Following is returned

    ----------
    comment:
        Cannot find SelectedUserSID in HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI
    hive:
        HKEY_LOCAL_MACHINE
    key:
        SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI
    success:
        False
    vdata:
        None
    vname:
        SelectedUserSID


However, on a minion running 2017.7.2
    hive:
        HKEY_LOCAL_MACHINE
    key:
        SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI
    success:
        True
    vdata:
        S-1-5-21-3817738000-1591130660-2784312656-21229
    vname:
        SelectedUserSID
    vtype:
        REG_SZ

**Comment by twangboy** [comment]
OK. I've had a chance to take a look at this. Here's what I've found. I haven't been able to reproduce this in the same way. Passing `SOFTWARE\Microsoft\Windows\CurrentVersion\Authentication\LogonUI` never works for me, whether on 2017.7.2 or 2017.7.3. So, I don't know how this is working for @darrenjlowe. Here's the output:
```
    ----------
    comment:
        Cannot find key: HKLM\SOFTWAREMicrosoftWindowsCurrentVersionAuthenticationLogonUI
    hive:
        HKLM
    key:
        SOFTWAREMicrosoftWindowsCurrentVersionAuthenticationLogonUI
    success:
        False
    vdata:
        None
    vname:
        SelectedUserSID
```
So, I tried passing `SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Authentication\\LogonUI` and it works everytime on 2017.7.2 and 2017.7.3. So, I suggest escaping the backslashes `\\`.

**Comment by darrenjlowe** [comment]
@twangboy with a double backslash from a salt master

salt "MACHINENAME" reg.read_value HKEY_LOCAL_MACHINE 'SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Authentication\\LogonUI' 'SelectedUserSID'

MACHINENAME:
    ----------
    comment:
        Cannot find SelectedUserSID in HKEY_LOCAL_MACHINE\SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Authentication\\LogonUI
    hive:
        HKEY_LOCAL_MACHINE
    key:
        SOFTWARE\\Microsoft\\Windows\\CurrentVersion\\Authentication\\LogonUI
    success:
        False
    vdata:
        None
    vname:
        SelectedUserSID

**Comment by darrenjlowe** [comment]
@twangboy 

I think I worked this out, I downloaded the 32bit version of Salt Minion installer instead of 64bit, once installed 64bit, this looks to work as expected, even with single backslash
