### ISSUE TITLE
Is it possible to check if minion grain in pillar file in the top.sls ?

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#45875]
Hey,

I would like to run the top.sls file on servers that does not appear in a pillar file.
Meaning, I have pillar file that contain a list to servers (yaml format) that I don't want to apply configuration now.
The file looks like this:
band_servers:
  server1:
    name: real_server1_name
  server2:
    name: real_server2_name

Now, I would like to perform a query on this file before running the top.sls file, something like:
{% if grains['host'] not in salt['pillar.get']('band_servers').keys() %}
base:
  'something':
    - something_else
{% endif %}

Is it possible?
If not, there is different way to get the same results?

Best Regards,
Amiram M.

**Comment by garethgreenaway** [comment]
@AmiramMaimon Thanks for the question.  What you want to accomplish above should be possible, you'll just need to ensure that that pillar value that contains the list of servers is available to all minions or in the pillar get ensure there is a default which is an empty list.  Something like this:
```
{% if grains['host'] not in pillar.get('server_list', []) %}
base:
'something':
- something_else
{% endif %}
```

**Comment by AmiramMaimon** [comment]
Hey,

Thank you for the answer,
I'm handle the pillar file as a dictionary that why I'm searching for a key in there.
So what worked for me is:
{% if not salt['pillar.get']('servers_from_pillar') or grains['host'] not in salt['pillar.get']('servers_from_pillar').keys() %]
The rest of the top.sls file
{% endif %}

The first element in the if check if the pillar file is empty, if it is I want to run the top.sls file.
If it is not empty I need to check if my bad server is one of the pillar keys and so on..

Thank you,
Amiram M.
