### ISSUE TITLE
Typo in docs fixed since 9 months

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#45872]
### Description of Issue/Question
I found a typo in the docs:

```
logstash:
  pkg.installed
    - fromrepo: ppa:wolfnet/logstash

```
There is missing a ":" after "installed".

I started to create a pull request, but then realized, that this was already fixed since May 2017: https://github.com/saltstack/salt/commit/bf7a0076ddbc0dfe02ec07b2278d08dc2b5ca1b7

AFAIK the latest release is younger then 9 months.

**Comment by gtmanfred** [comment]
The change was made in develop, so it will be in the Oxygen docs once they are out https://github.com/saltstack/salt/pull/41017

In the future, it would be best to submit doc fixes to the branch they are being fixed for. So in this case, 2016.11 or 2017.7
