### ISSUE TITLE
We use two salt-master, when  one of the salt-master down, some salt-minion deamon also down;

### ISSUE THREAD

**Issue by CharlesQQ** [saltstack/salt#45871]
We use two salt-master, when  one of the salt-master down, some salt-minion deamon also down, but other salt-minion deamon connect all the time, the count of salt-minion about 1000;

[saltstack@xxxx~]$ /opt/local/saltstack/python/bin/salt --versions-report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Apr 19 2017, 17:25:36)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.2
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by CharlesQQ** [comment]
the salt master config:

[saltstack@xxxx~]$ cat /etc/salt/master
default_include: /opt/local/saltstack/conf/master/*.conf
transport: tcp
publish_port: 4505
user: saltstack
ret_port: 4506
pidfile: /opt/local/saltstack/run/salt-master.pid
root_dir: /opt/local/saltstack
conf_file: /etc/salt/master
pki_dir: /opt/local/saltstack/pki/master
cachedir: /opt/local/saltstack/cache/master
module_dirs:
   - /opt/salt/salt-agent
keep_jobs: 10000
timeout: 5
show_timeout: True
sock_dir: /opt/local/saltstack/run
job_cache: True
minion_data_cache: True
max_open_files: 100000
worker_threads: 80
publish_session: 864000
auto_accept: False
log_file: /opt/local/saltstack/log/master/master.log
key_logfile: /opt/local/saltstack/log/master/key.log
log_level: warning
log_level_logfile: debug
log_datefmt: '%H:%M:%S'
log_datefmt_logfile: '%Y-%m-%d %H:%M:%S'
log_fmt_logfile: '%(asctime)s.%(msecs)03.0f [%(name)-17s] [%(levelname)-8s] %(message)s'

The salt minion config:
[saltstack@xxxx~]$ cat /etc/salt/minion
default_include: /opt/local/saltstack/conf/minion/*.conf
master:
    - x.x.x.x
    - x.x.x.x1
transport: tcp
master_port: 4506
user: saltstack
pidfile: /opt/local/saltstack/run/salt-minion.pid
conf_file: /etc/salt/minion
pki_dir: /opt/local/saltstack/pki/minion
cachedir: /opt/local/saltstack/cache/minion
cache_jobs: True
sock_dir: /opt/local/saltstack/run
master_tries: -1
module_dirs: [/opt/bizsalt/salt-agent]
log_file: /opt/local/saltstack/log/minion/minion.log
key_logfile: /opt/local/saltstack/log/minion/key.log
log_level: warning
log_level_logfile: debug
log_datefmt: '%H:%M:%S'
log_datefmt_logfile: '%Y-%m-%d %H:%M:%S'
log_fmt_logfile: '%(asctime)s.%(msecs)03.0f [%(name)-17s] [%(levelname)-8s] %(message)s'

**Comment by garethgreenaway** [comment]
@CharlesQQ Thanks for the report.  In your minion config, ensure that the `master_type` option is set to `failover` so that the minion will try each one until it finds one that it is able to connect to.
https://docs.saltstack.com/en/latest/ref/configuration/minion.html#master-type

**Comment by CharlesQQ** [comment]
I know, but if I don't use option   master_job_cache: mysql, it's works OK
