### ISSUE TITLE
docs example for x509.get_pem_entries seems wrong

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#45891]
### Description of Issue/Question
```
salt.modules.x509.get_pem_entries(glob_path)

    Returns a dict containing PEM entries in files matching a glob

    glob_path:
        A path to certificates to be read and returned.

    CLI Example:

    salt '*' x509.read_pem_entries "/etc/pki/*.crt"
```

The example mentions read_pem_entries while the function is called get_pem_entries.

### Setup
N/A

### Steps to Reproduce Issue
Check the docs at https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.x509.html

### Versions Report
N/a

**Comment by gtmanfred** [comment]
Yup, that looks like it is just a typo.

Would you mind opening a PR to fix it?

Thanks,
Daniel

**Comment by sjorge** [comment]
Looks like someone beat me too it, I check checked the file in develop and it's fixed.
It needs a backport, but I'm not sure how those are done.

The commit is ```2cf9e10672427735f344162b3a19669395b74f22``` it is relatively recent too. So not sure if it made it into Oxygen either.

**Comment by rallytime** [comment]
@sjorge I have labeled the PR to be backported. Thanks!
