### ISSUE TITLE
Displaying only errors for job

### ISSUE THREAD

**Issue by BenjaminSchiborr** [saltstack/salt#45903]
This is a question/possible story, *not* an issue.

As a developer I want to be able to efficiently debug possible problems that happened during execution of a highstate/state. 

Ways of doing this are by e.g. locally logging to a file and skimming the file or by reading the output of ```state.highstate``` or ```state.apply``` (and restricting the output using additional parameters). 

In my use case I very often troubleshoot issues after the fact (after execution of ```state.highstate``` or ```state.apply```) and I do not want to access local logging. Instead I query for job return using ```jobs.list_jobs``` and ```jobs.lookup_jid```. Usually this returns the output of hundreds of states that are successful and maybe just one that failed making it very hard for me to find that one state.

My question: Is there an easy way to query the return of a finished job and only print output that is filtered for states that threw warnings or failures and to *not* show anything else?

### Versions Report
```
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
There is not, when you query the job, it returns all the job data, you would have to then take that data yourself and pass it through the highstate outputter.

Probably the best way would be to use the RunnerClient, and just use python directly to parse the data for what you want.

https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.runner.RunnerClient


```
import sys

import salt.config
import salt.output
import salt.runner

opts = salt.config.master_config('/etc/salt/master')
opts['state_verbose'] = False
runner = salt.runner.RunnerClient(opts)
jobdata = runner.cmd('jobs.lookup_jid', kwarg={'jid': sys.argv[1]}, print_event=False)
salt.output.display_output(jobdata, out='highstate', opts=opts)
```

This doc shows what the state_verbose stuff does https://docs.saltstack.com/en/latest/ref/output/all/salt.output.highstate.html

But then you can just run the pythonscript with the jobid.

```
root@salt:/# python this.py 20180207193905620155
salt:
----------
          ID: exit 10
    Function: cmd.run
      Result: False
     Comment: Command "exit 10" run
     Started: 19:39:05.728823
    Duration: 11.287 ms
     Changes:
              ----------
              pid:
                  9186
              retcode:
                  10
              stderr:
              stdout:

Summary for salt
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  11.287 ms
```

And it will pass it all back through the highstate outputter which will handle that for you.

**Comment by BenjaminSchiborr** [comment]
@gtmanfred: Thanks a lot. I think this will already help. 

Just to have it asked. Is there a way of piping the output of ```lookup_jid``` into a shell command equivalent of ```salt.output.display_output```

**Comment by gtmanfred** [comment]
you could potentially write a salt runner module that does that, but i would have to fiddle with it for a while, which i unfortunately...

actually one second

```
import salt.output

def test(jid):
    ret = __salt__['jobs.lookup_jid'](jid)
    __opts__['state_verbose'] = False
    salt.output.display_output(ret, out='highstate', opts=__opts__)
```

and then you can put it in `salt://_runners/whatever.py`

and call `salt-run saltutil.sync_runners`

And you should then be able to run `salt-run whatever.test <jid>`  you can change the module name and the function name to get it to be what you want, but that has the same results, but not, it is not returning it, so if you want to use runnerclient to get the actual data, it won't be return anything, it only prints it out.

**Comment by BenjaminSchiborr** [comment]
@gtmanfred 

> which i unfortunately...
> 
> actually one second
Haha. I love it!

Thank you so very much. This is a perfect solution for us.

**Comment by gtmanfred** [comment]
Cool, no problem I am going to close this issue then.

Thanks!
Daniel
