### ISSUE TITLE
ext_pillar is an opaque black box that's impossible to troubleshoot

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#45900]
### Description of Issue/Question
When encountering issues with ext_pillar (specifically git pillar), it's basically impossible to trace the issue since nothing related to git pillar logs anything anywhere until it hits an error. This should be fixed.

### Steps to Reproduce Issue
1. Use git pillars
2. Have an error or unexpected behavior somewhere
3. Try to find out what precisely the ##### is going on
4. Fail because even at garbage-level logging, ext_pillar is completely silent unless it has an error, in which case it just says it has an error and gives no useful information about any part of its process.

### Versions Report
all versions.

**Comment by garethgreenaway** [comment]
@V3XATI0N Thanks for the report.  Tagging this as a future feature addition to improve the logging for ext_pillar.
