### ISSUE TITLE
Oxygen scheduler assumes localtime

### ISSUE THREAD

**Issue by cro** [saltstack/salt#45926]
### Description of Issue/Question

Code in the scheduler in Oxygen is using `mktime` which assumes localtime.  This can generate challenges for infrastructures where masters are in many timezones.  Allow scheduling to be specfiied in different timezones but store and process timestamps in UTC.  This enables client tools to display the time in whatever timezone.

**Comment by msteed** [comment]
The `timestamp()` method on `datetime` objects will do the conversion to Unix timestamp handling the timezone information properly.

**Comment by garethgreenaway** [comment]
Looks like `datetime.timestamp()` is Python 3.x only.

**Comment by msteed** [comment]
😭

**Comment by garethgreenaway** [comment]
The conversion to using datetime objects for everything means this is no longer a blocker for the Oxygen release.
