### ISSUE TITLE
get_minion_data returns None because cache file missing

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#45955]
### Description of Issue/Question

The function [`get_minion_data`](https://github.com/saltstack/salt/blob/9a0ec9c30f65338dda31613516ac8a6121dfb0cb/salt/utils/minions.py#L69) returns `None` when the cache file for the minion is missing:

    [salt.loaded.int.cache.localfs][DEBUG   ][17503] Cache file "/var/cache/salt/master/minions/$MINION_ID.p" does not exist

which causes other functions, such as [`get_policies`](https://github.com/saltstack/salt/blob/5795201ad60fe33540c6f14efddeacc405bfdc57/salt/runners/vault.py#L134), to fail with the following warning:

    [salt.loaded.int.runners.vault][WARNING ][17503] Could not resolve policy pattern saltstack/roles/{grains[roles]}

`get_policies` fails to expand the pattern `saltstack/roles/{grains[roles]}` because 
 [`salt.utils.minions.get_minion_data(minion_id, opts)`](https://github.com/saltstack/salt/blob/5795201ad60fe33540c6f14efddeacc405bfdc57/salt/runners/vault.py#L138) can return None.

This means that the vault module cannot create a token with all the correct policies as the expansion fails and therefore all pillars with `sdb://` calls fail to render.

This happens when running `state.apply` from either the master and the minion, however, it is not easily reproducible. We can have 2-3 successive runs of `state.apply` that run without failure, and then the next run will fail because of the missing cache file.

### Questions

1. Under what circumstances can the cache file be missing? What would cause the cache file to be removed between successive runs of `state.apply`?

2. Why is it not possible to load grains if [`minion_data_cache`](https://github.com/saltstack/salt/blob/9a0ec9c30f65338dda31613516ac8a6121dfb0cb/salt/utils/minions.py#L78) is False?

3. How come [`cache.fetch`](https://github.com/saltstack/salt/blob/9a0ec9c30f65338dda31613516ac8a6121dfb0cb/salt/utils/minions.py#L86) doesn't throw an exception if the cache file is missing?

### Important information

We are running a multi-master set up in our production env. This issue does not happen in our staging or dev env where we have single masters. 

### Versions Report

    Salt Version:
               Salt: 2017.7.2

    Dependency Versions:
               cffi: 1.7.0
           cherrypy: Not Installed
           dateutil: 2.5.3
          docker-py: Not Installed
              gitdb: 2.0.0
          gitpython: 2.1.1
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: 0.24.0
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: 1.3.7
          pycparser: 2.14
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: 0.24.1
             Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.1
            timelib: Not Installed
            Tornado: 4.4.3
                ZMQ: 4.2.1

    System Versions:
               dist: debian 9.3
             locale: UTF-8
            machine: x86_64
            release: 4.9.0-5-amd64
             system: Linux
            version: debian 9.3

**Comment by gtmanfred** [comment]
What kind of multimaster setup do you have? is it active-active?

If this is the case, i think it would be possible for any master to return back the call for a vault token, and it could be the one that doesn't have a grains cache?

If the minion_data_cache is false, then the grains are not cached, so it can't fetch them.

If you use an external grains cache, then both master should be able to share the same one instead of it going missing? possibly?

https://docs.saltstack.com/en/latest/ref/configuration/master.html#cache

localfs does through an IOError if it has a problem reading the cache.

https://github.com/saltstack/salt/blob/9a0ec9c30f65338dda31613516ac8a6121dfb0cb/salt/cache/localfs.py#L95

Thanks,
Daniel

**Comment by grobinson-blockchain** [comment]
We have a multi-master set up as explained here: https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html

> If the minion_data_cache is false, then the grains are not cached, so it can't fetch them

I thought so too. However, in all cases `minion_data_cache` was True, as I inserted additional logging while debugging the issue.

We don't use an external, shared cache, rather each master has its own cache. Could this be the issue?

**Comment by gtmanfred** [comment]
That is my suspicion.  Would you mind trying out one of the external cache modules?

There is a redis one if you don't want to use consul.
https://docs.saltstack.com/en/latest/ref/cache/all/salt.cache.redis_cache.html#module-salt.cache.redis_cache
