### ISSUE TITLE
macOS Timezone Set Using Network Time no longer applies configuration

### ISSUE THREAD

**Issue by darrenjlowe** [saltstack/salt#45964]
Just upgraded to macOS 10.13.3 from 10.12.6 and also upgraded Salt Minion to 2017.7.3, when running 

`salt 'MACHINENAME' timezone.set_using_network_time True`

This returns

`MACHINENAME:
    False`

I have tested against other machines running macOS 10.12.6 and minion 2017.7.2, and macOS 10.13.3 and 2017.7.2 minion, these all return "True"

### Versions Report
Salt Minion

Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 29 2018, 15:44:37)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 17.4.0
         system: Darwin
        version: 10.13.3 x86_64

Salt Master

Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
Can you provide the output of running

```
salt-call timezone.set_using_network_time True -l debug
```

On the minion?

Thanks,
Daniel

**Comment by darrenjlowe** [comment]
This looks to be working today, will close issue, continue to test more and log a new issue if I see a pattern emerging, could be something with reboots of the machine after Salt Minion is upgraded

**Comment by darrenjlowe** [comment]
Looks like when I run the the salt-call on the minion this seems to work


----------------------
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/cpe_mac.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/cpe_mac.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: MACHINENAME
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Including configuration from '/etc/salt/minion.d/cpe_mac.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/cpe_mac.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'MACHINENAME', 'tcp://MASTER_1:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8525)
[DEBUG   ] Setting zmq_reconnect_ivl to '8525ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'MACHINENAME', 'tcp://MASTER_1:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'MACHINENAME', 'tcp://MASTER_1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'MACHINENAME', 'tcp://MASTER_1:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded timezone.set_using_network_time
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'MACHINENAME', 'tcp://MASTER_1:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'MACHINENAME', 'tcp://MASTER_1:4506')
[DEBUG   ] LazyLoaded nested.output
local:
    True

And then when running this on the SaltMaster it also works, however then when running this is as part of a state file it fails, then it fails running running from a SaltMaster

 timezone.set_using_network_time:
   module.run:
     - enable: True

**Comment by gtmanfred** [comment]
Can you try.

```
timezone.set_using_network_time:
  module.run:
    - kwargs:
         enable: True
```

or enable this in the minion config

```
use_superseded:
  - module.run
``` 

and use the new module.run format.

```
set using network time:
  module.run:
    - timezone.set_using_network_time:
      - enable: True
```

Thanks,
Daniel
