### ISSUE TITLE
rabbitmq_user.present seems to error from a dependecy on python-sss

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#45962]
### Description of Issue/Question
I added the rabbitmq_user.present below and got the error below till I installed the python-sss package. It seems like an odd dependency to require pysss for this use case.

### Error

    ----------
          ID: sensu_rabbitmq_user
    Function: rabbitmq_user.present
        Name: sensu
      Result: False
     Comment: Error: RabbitMQ command failed: [TRACE   ] Trying pysss.getgrouplist for 'rabbitmq'
              [TRACE   ] Trying generic group list for 'rabbitmq'
              [TRACE   ] Group list for user 'rabbitmq': '['rabbitmq']'
     Started: 22:33:10.276671
    Duration: 184.277 ms
     Changes:

### Setup
    sensu_rabbitmq_user:
      rabbitmq_user.present:
        - name: sensu
        - password: {{ pillar['sensu']['rabbit_pass'] }}
        - perms:
          - '/sensu':
            - '.*'
            - '.*'
            - '.*'
        - runas: rabbitmq
        - require:
          - service: rabbitmq-server

### Versions Report
    Salt Version:
               Salt: 2017.7.3
 
    Dependency Versions:
               cffi: 1.9.1
           cherrypy: Not Installed
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: 0.9.1
       msgpack-pure: Not Installed
     msgpack-python: 0.3.0
       mysql-python: 1.2.3
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.12 (default, Jul 18 2016, 15:02:52)
       python-gnupg: Not Installed
             PyYAML: 3.10
              PyZMQ: 14.0.1
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.4
 
    System Versions:
               dist: Ubuntu 14.04 trusty
             locale: UTF-8
            machine: x86_64
            release: 3.13.0-79-generic
             system: Linux
            version: Ubuntu 14.04 trusty

**Comment by gtmanfred** [comment]
For getting grouplists, in python2, it only gets groups from local users.

python-sss is required in order to get groups from other pam providers, like ldap or something.

In python3, they have included this method, so we can just use the os.getgrouplist.

https://github.com/saltstack/salt/blob/2017.7/salt/utils/__init__.py#L2955-L2972

Here is where that takes place.  It should still fall back to using `grp.getgrall()` though?

Thanks,
Daniel

**Comment by edgan** [comment]
This message seems to suggest it is trying grp.getgrall(), "Trying generic group list for 'rabbitmq'", but it fails with a trace. Where as if I install pysss, it works without error.

This is python2 as shown in the versions report above.

**Comment by gtmanfred** [comment]
Can you provide the trace?

Thanks,
Daniel

**Comment by edgan** [comment]
This is all I get from salt.

salt-call -l trace state.apply sensu.server :
```
[DEBUG   ] stderr: [TRACE   ] Trying pysss.getgrouplist for 'rabbitmq'
[TRACE   ] Trying generic group list for 'rabbitmq'
[TRACE   ] Group list for user 'rabbitmq': '['rabbitmq']'
[ERROR   ] Error: RabbitMQ command failed: [TRACE   ] Trying pysss.getgrouplist for 'rabbitmq'
````
