### ISSUE TITLE
chocolatey bootstrap should support offline installation of Chocolatey itself

### ISSUE THREAD

**Issue by ferventcoder** [saltstack/salt#45969]
### Description of Issue/Question

Salt is able to bootstrap Chocolatey with [chocolatey.bootstrap](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.chocolatey.html#salt.modules.chocolatey.bootstrap). However, there is nowhere to indicate an internal/offline location of the Chocolatey nupkg like you can with Chef and Puppet. 

Being able to support a fully internal installation seems like a good request as other folks using Salt are using work arounds to make it happen - https://controlaltfail.wordpress.com/2017/08/03/salt-chocolatey-install-totally-offline/

Thoughts?

**Comment by ferventcoder** [comment]
cc @jfindlay @rallytime @twangboy

Just as an FYI, I'm writing some user documentation on how to support offline installation across different configuration managers and I'm noting that it's not possible and pointing back to this issue as a placeholder until this is implemented.

**Comment by ferventcoder** [comment]
FYI here is an image of that documentation included in Chocolatey.Server v0.2.3:
![image](https://user-images.githubusercontent.com/63502/36075617-10815c8e-0f17-11e8-913e-bde5554f0451.png)

**Comment by gtmanfred** [comment]
This seems like a great idea.

We would love to see a PR implementing it.

If you dont have time, @dwoz and @twangboy would yall mind taking a look and seeing if this would be quick to implement?

Thanks,
Daniel

**Comment by ferventcoder** [comment]
@gtmanfred I don't have the skills necessary to implement it. Or at least quickly and correctly.

**Comment by twangboy** [comment]
We could either add a source option to `bootstrap` or we could add `bootstrap_local`. I kind of like `bootstrap_local` because the `bootstrap` does a lot more than just install chocolatey.

- It Windows has the version of PowerShell itneeds
- It installs `.NET 4.0`
- Then it installs Chocolatey

If we're installing chocolatey from a local source, we would need to assume that's already been done and all that's left is to install Chocolatey.

@UtahDave ?

**Comment by abmoham** [comment]
Adding input parameters seems to be an extensible method to achieving the desired result (IMHO - a better choice) and could support any of them exposed in the chef cookbook implementation @ https://github.com/chocolatey/chocolatey-cookbook/blob/master/attributes/default.rb and all the flexibility it provides.

**Comment by ferventcoder** [comment]
@twangboy I believe I agree with @abmoham on this - it feels better to have an attribute/parameter of some sort that can control where I install Chocolatey from, with a default value of the community repository (`https://chocolatey.org/install.ps1` in this case). Since it is pointing to a script instead of using a local version, allow for me to pass in an alternative script that would achieve the same result. 

Code at https://github.com/saltstack/salt/blob/bdcb3cb3028f759127812a3846f58cf90a0f58a8/salt/modules/chocolatey.py#L215

**Comment by twangboy** [comment]
Add `source` parameter to `chocolatey.bootstrap`. Default to `https://chocolatey.org/install.ps1`
Installer will do the following
- [ ] Download nupkg from salt:// or internal url, or specify local file
- [ ]  If it downloads a `ps1` file it will run it
- [ ] If it downloads a `nupkg` file it will unzip the file to `<temp dir>`
- [ ] Run `chocolateyInstall.ps1` from `<temp dir>\tools`
May need to do the following (may be done in the powershell script):
- [ ] Ensure the 'ChocolateyInstall` environment variable is present and set to `%ProgramData%\Chocolatey`
- [ ] Ensure `%ChocolateyInstall%\bin` is in the python environment path
