### ISSUE TITLE
[ERROR   ] No master could be reached or all masters denied the minions connection attempt.

### ISSUE THREAD

**Issue by zhulh200868** [saltstack/salt#45975]
### Description of Issue/Question
```
[root@master log]# salt-call test.ping
[ERROR   ] No master could be reached or all masters denied the minions connection attempt.
Attempt to authenticate with the salt master failed with timeout error
[root@master log]# cat /etc/salt/minion
master:
   - 192.168.16.2
id: 192.168.16.2
random_reauth_delay: 80
tcp_pub_port: 8010
tcp_pull_port: 8011
master_port: 8006
[root@master log]# salt-call test.ping 
local:
    True
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by gtmanfred** [comment]
Can you provide me with more information about what I am looking at and how to replicate this behavior?

Thanks,
Daniel
