### ISSUE TITLE
Using salt-ssh for windows

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#46001]
### Description of Issue/Question

I see that there is a argument to pass winrm=True/False in roster and also in salt-ssh shell.py module has a function gen_shell which checks for type of target shell. Which is also checking for winrm.

This function specifies that saltwinshell should be installed. Is this saltwinshell still under development as i am not able to find any thing related to it installation
If it is under development, which release it will be available with?

**Comment by gtmanfred** [comment]
This is offered in our enterprise product, and will be in 5.3.
