### ISSUE TITLE
service.running with unmask: true does not work as documented

### ISSUE THREAD

**Issue by ghost** [saltstack/salt#46014]
### Description of Issue/Question

Attempts to use service.running with unmask: true fails to work, although the documentation indicates that it should.  Doing a service.unmasked followed by a service.running does work.

### Setup

postgresql_service:
  service.running:
    - name: postgresql
    - enable: true
    - unmask: true

### Steps to Reproduce Issue

Running the above saltstate step produces the following error, indicating that unmask: true is ignored:

ID: postgresql_service
    Function: service.running
        Name: postgresql
      Result: False
     Comment: Running scope as unit run-rf9894e4e64074350a0941db0c4d00140.scope.
              Failed to start postgresql.service: Unit postgresql.service is masked.
     Started: 17:31:45.216514
    Duration: 117.84 ms
     Changes:   

### Versions Report

Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@caseyallenshobe Thanks for the report.
