### ISSUE TITLE
http.wait_for_successful_query gives status:503 error though curl output is 200

### ISSUE THREAD

**Issue by sam0104** [saltstack/salt#46010]
### Description of Issue/Question
http.wait_for_successful_query gives status:503 error . 
Though URL response is 200 using curl command.

**ac-query-http-url:
  http.wait_for_successful_query:
    - name: 'http://localhost:{{ salt['pillar.get']('ac-tomcat:connector:port') }}/appControl/v1/types'
    - status: 200
    - wait_for: 30**
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
On Salt master and minion on Centos7.
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Ch3LL** [comment]
Can you please paste any related sanitized debug logs when this occurs?

**Comment by sam0104** [comment]
I do not have any specific log. Which log can I provide ? 

When I replace http://localhost  with http://10.x.x.x it is working fine. When I test with curl command both http://localhost  and http://10.x.x.x. works fine.  


Does http.wait_for_successful_query hard coded for listen http code on specific network interface ( eth0 )?

**Comment by Ch3LL** [comment]
which proxy settings are you using? can you paste a sanitized version here?

**Comment by sam0104** [comment]
Here is the minion configuration file . **When we disable  #proxy_host: http://proxy.test  it works fine.**
cat /etc/salt/minion
##### Primary configuration settings #####
##########################################
# This configuration file is used to manage the behavior of the Salt Minion.
# With the exception of the location of the Salt Master Server, values that are
# commented out but have an empty line after the comment are defaults that need
# not be set in the config. If there is no blank line after the comment, the
# value is presented as an example and is not the default.

# Per default the minion will automatically include all config files
# from minion.d/*.conf (minion.d is a directory in the same directory
# as the main minion config file).
#default_include: minion.d/*.conf

# Set the location of the salt master server. If the master server cannot be
# resolved, then the minion will fail to start.
#master: salt

# Set http proxy information for the minion when doing requests
**#proxy_host: http://proxy.test**
#proxy_port: 3128
#proxy_username:
#proxy_password:

# If multiple masters are specified in the 'master' setting, the default behavior
# is to always try to connect to them in the order they are listed. If random_master is
# set to True, the order will be randomized instead. This can be helpful in distributing
# the load of many minions executing salt-call requests, for example, from a cron job.
# If only one master is listed, this setting is ignored and a warning will be logged.
# NOTE: If master_type is set to failover, use master_shuffle instead.
#random_master: False

**Comment by sam0104** [comment]
**Here is the minion configuration file . When we disable  #proxy_host: http://proxy.test  it works fine.
cat /etc/salt/minion
##### Primary configuration settings #####
**### ##########################################
# This configuration file is used to manage the behavior of the Salt Minion.
# With the exception of the location of the Salt Master Server, values that are
# commented out but have an empty line after the comment are defaults that need
# not be set in the config. If there is no blank line after the comment, the
# value is presented as an example and is not the default.

# Per default the minion will automatically include all config files
# from minion.d/*.conf (minion.d is a directory in the same directory
# as the main minion config file).
#default_include: minion.d/*.conf

# Set the location of the salt master server. If the master server cannot be
# resolved, then the minion will fail to start.
#master: salt

# Set http proxy information for the minion when doing requests
**#proxy_host: http://proxy.test**
#proxy_port: 3128
#proxy_username:
#proxy_password:

# If multiple masters are specified in the 'master' setting, the default behavior**
# is to always try to connect to them in the order they are listed. If random_master is
# set to True, the order will be randomized instead. This can be helpful in distributing
# the load of many minions executing salt-call requests, for example, from a cron job.
# If only one master is listed, this setting is ignored and a warning will be logged.
# NOTE: If master_type is set to failover, use master_shuffle instead.
#random_master: False**

**Comment by sam0104** [comment]
Here is the minion configuration file . When we disable  #proxy_host: http://proxy.test  it works fine.

**Comment by sam0104** [comment]
[minion.txt](https://github.com/saltstack/salt/files/1724485/minion.txt)

**Comment by Ch3LL** [comment]
k thanks for posting that :) looks like the proxy settings you have posted are not configurable outside of the minion config. 

If you look here: https://github.com/saltstack/salt/blob/v2017.7.2/salt/utils/http.py#L461-L464

you can see that its querying those options from opts, which is information from minion config. Looks like this would need to be improved to be able to send it in as a kwarg/arg.

**Comment by sam0104** [comment]
Thanks for the update. So this should be fixed on next release of minion version ? Is there any workaround we can perform now ?
