### ISSUE TITLE
Extention Modules -Salt saltutil sync issues

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#46030]
### Description of Issue/Question

When i place custom module at /usr/lib/python2.7/dist-packages/salt/modules/ all the imports work perfectly.

Then i moved the custom module to /srv/salt/_modules and used saltutil.sync_modules to sync it minion,which worked. 
But after this i have started seeing import errors for boto3 python library.
Please help.

**Comment by garethgreenaway** [comment]
@sumeetisp Thanks for the report.  Can you provide the output for salt --versions-report and the custom module you're attempting to use?

**Comment by sumeetisp** [comment]
Salt Version:
           Salt: 2017.7.1

Dependency Versions:
           cffi: 1.11.4
       cherrypy: 3.2.2
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Oct 26 2016, 20:30:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-77-generic
         system: Linux
        version: Ubuntu 14.04 trusty

The custom module is for deploying aws cfn templates. It imports boto3 module which is failing when put in /srv/salt/_modules and synced.

**Comment by sumeetisp** [comment]
Please help.

Following are the imports,
        import boto
        import boto.cloudformation
        import boto_rds
        import boto3

**Comment by sumeetisp** [comment]
Issue 2 -
Consider module 1 which is in _sdb and module 2 which is in _utils
And module 1 is importing module 2 then after sync_all, module 1 fails to import because it is unable to find module 2.
Please help

**Comment by sumeetisp** [comment]
@garethgreenaway Please help.

**Comment by garethgreenaway** [comment]
@sumeetisp if I understand the first issue that you're describing you've written a custom module which is importing the above mentioned boto libraries and placing that module under /srv/salt/_module.  Once it's synced to the minions the custom module is failing to import.  Do you have those boto libraries installed and available on the minions where it's failing?

**Comment by sumeetisp** [comment]
Yes, When I place it at /usr/....../salt/modules it works fine. 
Similarly in issue 2, I am importing utils module from sdb module which are place at  srv/salt/_utils and /srv/salt/_sdb respectively. And its failing too.
