### ISSUE TITLE
Using `!` as comment char with `file.comment_line` results in 'None' being used instead

### ISSUE THREAD

**Issue by hop** [saltstack/salt#46034]
The command

    salt '*' file.comment_line /etc/ca-certificates.conf '^mozilla/DigiCert_Global_Root_CA\.crt' '!'

results in

    Nonemozilla/DigiCert_Global_Root_CA.crt

in the file. In order to get the correct result, one has to use

    salt '*' file.comment_line /etc/ca-certificates.conf '^mozilla/DigiCert_Global_Root_CA\.crt' '"!"'

(the order of `'` and `"` is important to keep bash from interpreting the `!`).

I could trace this back you `yaml.load('!')` returning `None`, but I was not able to determine why the problem doesn't occur with `#`.

If this behaviour is intentional, it should at least be mentioned in the documentation.

**Comment by hop** [comment]
Sorry, forget to mention that I use versions `2016.11.5` and `2016.11.9`.

I could not find a previous bug report for this, but maybe I couldn't come up with the right search terms.

**Comment by garethgreenaway** [comment]
@hop As you pointed out this is actually your shell interpreting the `!` before Salt can get to it.  Since the `!` is used to call previous commands I'm not sure this is a scenario that we can work around and the behavior is expected.  Quoting the `!` as you've done would be the recommended solution.

**Comment by hop** [comment]
No, it is not. Using single quotes prevents bash from interpreting the `!`. You can verify this by using double quotes instead.

**Comment by github-abcde** [comment]
I have traced this to `salt/utils/args.py:yamlify_arg`.
In 2018.3, this happens:
```
>>> import salt.utils.yaml
>>> print(salt.utils.yaml.safe_load('!'))
None
>>>
```
In 2019.2, neon and develop, this happens:
```
>>> import salt.utils.yaml
>>> print(salt.utils.yaml.safe_load('!'))

>>>
```
This *only* happens when an arg consists of just an exclamation mark.
I'll see about creating PRs that fix this.
