### ISSUE TITLE
pkg.upgrade breaks yum/rpm when upgrading kernel

### ISSUE THREAD

**Issue by Kaydub00** [saltstack/salt#46033]
This is semi-related to #45924. I would like to run pkg.upgrade to upgrade all packages on a system. This seems to break when the kernel-utils package is upgraded(possibly all kernel packages?). I was looking into the code and I saw [on lines 1748-1758 here](https://github.com/saltstack/salt/blob/develop/salt/modules/yumpkg.py) that this issue seems to have been brought up before but in relation to the salt-minion upgrading. 

During the yum upgrade the yum command dies immediately after kernel-utils is upgraded. Packages are not cleaned up, duplicates are installed, and not all the necessary packages upgraded complete installation. Trying to yum-complete-transaction, package-cleanup, and other yum troubleshooting commands does not fix the problem. The broken kernel packages are causing a kernel panic at system reboot. 

Maybe this is a known issue and there's documentation on this? Should there just be documentation on this? Consensus from some message boards seems to be that you shouldn't run a pkg.upgrade to upgrade everything, which is understandable, but I take snapshots of my systems prior to an upgrade and it's simple to rollback. I say this is related to #45924 because I attempted to exclude the kernel but that doesn't seem to work either.

Let me know if you need any more info, I have some bandwidth available and wouldn't mind further troubleshooting if there are any other questions or things I should try here.

## Setup
Salt-minions running from a Master. All in AWS GovCloud. I haven't tested elsewhere yet.

### Salt-Master:
Salt Version:
           Salt: 2017.7.3
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

### Salt-Minion
Salt Version:
           Salt: 2017.7.3
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

## Reproduce issue

`salt 'hostname' pkg.upgrade`

Breaks after kernel-utils package is upgraded according to the yum logs.

**Comment by garethgreenaway** [comment]
@terminalmage Might be related to the recent fix you make to the yumpkg module?

**Comment by terminalmage** [comment]
Well, the exclude doesn't help you when you don't use it. I can't even find a record of what is in `kernel-utils`, There doesn't appear to be a reason the yum command would die in the middle of upgrading it, and certainly not a reason I would expect to be caused by Salt.

**Comment by Kaydub00** [comment]
The other ticket was filed because when exclude is used it doesn't work.
