### ISSUE TITLE
fromrepo parameter in pkg.uptodate state not working

### ISSUE THREAD

**Issue by hammondrm** [saltstack/salt#46048]
After updating the salt master to 2017.7.2 our Linux server patching started failing. The fromrepo parameter was being passed directly to yum rather than being converted to disablerepo '*' enablerepo <repolist>. This worked fine before the upgrade but failed after. 

We are working around this issue by using the disablerepo and enablerepo parameters. This is working but it looks like these parameters are being doubled in the command being sent to the minion.

In the error we see in the logs:
pkg_|-do_update_|-UpToDate_|-uptodate": {
                    "comment": "Problem encountered upgrading packages. Additional info follows:\n\nresult:\n    ----------\n    pid:\n        26346\n    retcode:\n        1\n    stderr:\n        Command line error: no such option: --fromrepo\n    stdout:\n        Usage: yum [options] COMMAND ...

### Steps to Reproduce Issue
This can be reproduced by calling the pkg.upgrade module directly.

salt '<Target>' pkg.upgrade fromrepo='<RepoList>'

<Target>:
    ERROR: Problem encountered upgrading packages. Additional info follows:

    changes:
        ----------
    result:
        ----------
        pid:
            2196
        retcode:
            1
        stderr:
            Running scope as unit run-2196.scope.
            Command line error: no such option: --fromrepo
        stdout:
            Usage: yum [options] COMMAND

            List of Commands:
...

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.16.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago

**Comment by gtmanfred** [comment]
@terminalmage is this related to the yumpkg.py stuff you found the other day?

Thanks,
Daniel

**Comment by hammondrm** [comment]
You may be confusing me with someone else. This is the first time I have brought this up. I did notice the problem last month but just worked around it. If someone else has already reported this then this issue could be closed as a duplicate. Do you have a reference for the other issue report?

**Comment by gtmanfred** [comment]
I am not confusing you with someone else, terminalmage fixed a problem in yumpkg.py that might be related to this.

**Comment by gtmanfred** [comment]
Can you check if this fixes your issue? https://github.com/saltstack/salt/pull/45991

**Comment by hammondrm** [comment]
Sorry to misunderstand. I wasn't sure how to determine what changes terminalmage made to the package.

Looking at his comments from #45991 I think this addresses the issue with the duplicate entries on the command line but I don't think it addresses the main issue with the fromrepo argument not being converted to the form yum needs using the disablerepo and enablerepo.

**Comment by gtmanfred** [comment]
But it would run move the fromrepo option from kwargs so that it isn't passed to _get_extra_opts. It is converted to enable and disable repo options in the other get opts function.

**Comment by hammondrm** [comment]
OK, I guess I missed that from his comment. If that is what is happening in the code then it should be back to what was happening before we updated and this fix will resolve the issue we are having.

Is there a target release for this fix?

**Comment by gtmanfred** [comment]
it should be in the oxygen release which we are working on, or 2017.7.5

Also, you can distribute it to your minions using dynamic modules.

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html

**Comment by hammondrm** [comment]
Sounds great. Thank You.
