### ISSUE TITLE
Windows Installer should include everything need by windows modules

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#46065]
### Description of Issue/Question
'mssql' __virtual__ returned False: The mssql execution module cannot be loaded: the pymssql python library is not available.

Please add 
- FreeTDS http://pymssql.org/en/stable/freetds.html
- pymssql Python module

**Comment by lorengordon** [comment]
I'd downvote this. Some modules have additional requirements. Windows users can use salt's packaged python to install them using pip.

**Comment by rallytime** [comment]
Yeah, I agree with @lorengordon. This is a common practice in Salt. We can't package for every module dependency and it's standard for users to handle installing the various dependencies they need. This practice shouldn't be different for Windows.

**Comment by damon-atkins** [comment]
Difference is windows is a private version of python. Not shared. Pip install only works if you do not have to compile anything as part of a pip install.  I suppose companies will just need to get security to sign off on C compiler on production systems. Or create their own msi to install the extra they need.

Does not seem simple.

**Comment by lorengordon** [comment]
It seems to me the Salt team has been handling this fine. _If_ a dependency must be compiled on Windows, _then_ it will be distributed by the salt package. I'd prefer to keep it tight and focused like that, only doing what is required. That's not what it seems this issue is requesting though, hence the downvote.

**Comment by damon-atkins** [comment]
Basically if needs to be compiled it needs to be included. Looking at it from what would be useful for windows I suspect their would not be much missing at all, hence I made this generic.

**Comment by lorengordon** [comment]
I use pip install a ton on Windows, and have pretty much never needed to pre-compile anything. Without solid reproducible examples of a wide-spread problem, I just don't see the need to make a sweeping change here.

**Comment by damon-atkins** [comment]
C:\salt>set PYMSSQL_BUILD_WITH_BUNDLED_FREETDS=1
