### ISSUE TITLE
Redirecting apt repositories to HTTPS requires additional local packages

### ISSUE THREAD

**Issue by morganwillcock** [saltstack/salt#46082]
### Description of Issue/Question
It looks like the apt repositories are now redirecting to HTTPS, so when you add a source you just end up with an update error from the lack of HTTPS support, as it isn't installed in Debian by default.

### Steps to Reproduce Issue
Add `deb http://repo.saltstack.com/apt/debian/9/amd64/latest stretch main` to package list and try to update.

<pre>$ sudo apt-get update
Ign:1 http://ftp.uk.debian.org/debian stretch InRelease
Hit:2 http://security.debian.org/debian-security stretch/updates InRelease  
Hit:3 http://ftp.uk.debian.org/debian stretch Release                       
Reading package lists... Done                                               
E: The method driver /usr/lib/apt/methods/https could not be found.
N: Is the package apt-transport-https installed?</pre>

To continue you must either remove the Salt repo from the sources list, or blindly trust the transport package:

<pre>$ sudo apt-get install apt-transport-https
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  apt-transport-https
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 138 kB of archives.
After this operation, 195 kB of additional disk space will be used.
WARNING: The following packages cannot be authenticated!
  apt-transport-https
Install these packages without verification? [y/N]</pre>

As well as stopping a new installation, it stops updates being applied on running installations (which would previously upgrade fine). There is some benefit to using HTTPS, but I think a lot of people are going to be wondering why their servers don't update any more. Perhaps add some notes to the installation instructions, or just implement HTTPS for the next OS versions (when people must actively switch their sources)?

**Comment by Ch3LL** [comment]
ping @dmurphy18 ^^

**Comment by gtmanfred** [comment]
@UtahDave we might consider switching off the automatic redirects on the repo server?

**Comment by UtahDave** [comment]
Thanks for your input. I've disabled the redirect.

Can you test again?

**Comment by UtahDave** [comment]
I've disabled the redirect. I'm going to close this issue.  If further discussion is needed please comment here and we'll reopen.

Thanks again for your input!
