### ISSUE TITLE
Documentation about 'master_failback_interval' not clear

### ISSUE THREAD

**Issue by jf** [saltstack/salt#46096]
https://docs.saltstack.com/en/latest/ref/configuration/minion.html#master-failback-interval says

> If the minion is in multi-master mode, the :conf_minion`master_type` configuration is set to failover, and the master_failback option is enabled, the master failback interval can be set to ping the top master with this interval, in seconds.

But what does this mean when the default is `0`? Do the minions *never* check on the top master, and therefore **never failback**?

**Comment by gtmanfred** [comment]
Would you mind submitting docs to make this more clear?

Looking at the code, it looks like if `master_failback` is True, then either `master_failback_interval` is used, or if `master_failback_interval` is 0, then it is set to `master_alive_interval`.

And it puts a job in the scheduler, that tries to ping the master on that interval, and after checking the scheduler, setting the seconds to 0 in the scheduler, will run the job every second.

So, 0 is the default, but that just means the master will be checked every second to see if the minion should fail to another master.

Daniel

**Comment by jf** [comment]
Sorry, but no. I'm not inclined to do this right now.
