### ISSUE TITLE
Timeout error while loading external pillar

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#46095]
### Description of Issue/Question

I am using and external pillar which has the following procedure to render,
Get pillar details via api call -> Resolve ssh_paasword from password vault -> Return pillar

Getting the pillar from API call works fine but this resolving password from vault is becoming a pain point.
This rendering from vault increases the time to render a single profile, which keeps on increasing as the number of profiles increase. Does salt have any parameter  which can be configured to say " never time out" for external pillar?

**Comment by Ch3LL** [comment]
i'm not aware of an option to never time out, but you can use https://docs.saltstack.com/en/latest/ref/configuration/master.html#timeout

and set it to a high number to ensure it doesn't timeout for that amount of time. Does that work for your use case?
