### ISSUE TITLE
Entry in pillar top.sls with dot in path does not work

### ISSUE THREAD

**Issue by majo83** [saltstack/salt#4610]
Hey folks,

with the version 0.14.0 it does not work to have a dot in a dirname which servers a pillar.

Example: 
As a top.sls in /srv/pillar

```
base: 
    '*' 
      - data
      - dir.with.dot.in.dirname
```

With a pillar tree structure as follows:
/srv/pillar/
/srv/pillar/top.sls
/srv/pillar/data/init.sls
/srv/pillar/dir.with.dot.in.dirname/init.sls

Issuing 
$ salt-call pillar.data  --local 
will complain, that dir.with.dot.in.dirname was not found.

**Comment by twellspring** [comment]
There is another ticket on this same issue, Issue #19513 
Which has a documentation fix #19859

**Comment by basepi** [comment]
Awesome thanks @twellspring!

**Comment by damon-atkins** [comment]
My biggest problem is that it is not documented in http://docs.saltstack.com/en/latest/topics/pillar/index.html that you can not use dot in the file name.  I suggest if file name restrictions exist that they are documented on the relevant pages.  Thanks

**Comment by basepi** [comment]
@damon-atkins That's a good point. Would you mind opening a new issue for this docs fix?

**Comment by arnoutpierre** [comment]
Not sure I'm helping here (mostly since the issue is tagged as `Documentation`), but for who search an hacky way to include a `sls` file containing dot in name here is a dirty solution:
This simply use `from <module> import <submodule>` python state.

#### Don't work
```
# file: /srv/salt/foo.sls
include
  # try to include `path/to/dir/filename.ext`
  - path.to.dir.filename.ext

whatever:
  cmd.run:
    - echo {{ things[0] }}
```
```
# file: /srv/salt/path/to/dir/filename.ext
things:
  - first thing
  - second thing
```

#### Hacked
```
# file: /src/salt/foo.sls
{% from "path/to/dir/filename.ext" import bar with context %}

whatever:
  cmd.run:
    - echo {{ bar['things'][0] }}
```
```
# file: /srv/salt/path/to/dir/filename.ext
{% load_yaml as bar %}
things:
  - first thing
  - second thing
{% endload %}
```

That worked for me, I don't think it's the best way, but it's one.

**Comment by phil123456** [comment]
this is pure unbelievable...
does salt at least supports escaping dots a s a feature ?

**Comment by phil123456** [comment]
@basepi so you can manage everything but files with dots in the name, I think it is the most restrictive thing EVER on a linux based fs

**Comment by basepi** [comment]
@phil123456 It's less than ideal. Salt doesn't support escaping at the moment. It's something that should definitely be added, but most people just rename their files to not include dots and so it hasn't been a huge focus. There are a lot of bugs to be squashed before tackling features like that.

**Comment by willxy** [comment]
I was wanting to do this today (store host-specific data in fqdn-named files).  In case it's valuable to anyone else coming here from a google search, as I did, I found these two approaches useful:

1. Leveraging @st0ne-dot-at's [post above](#issuecomment-40198089) and going with the aforementioned `_` separator:

 ```
 ## /srv/pillar/top.sls:

 {% set under_id = grains['id'].replace(".","_") %}

 base:
    '*':
      - hosts/{{ under_id }}
 ```

 and eg:

 ```
 ## /srv/pillar/hosts/foo_example_com.sls

 foo: bar
 baz: whee
 ```

 Of course, other separators could be used (`,` `=` `+` etc). I tried several and couldn't find any that substituted well enough for `.` to go with.

2. Leveraging https://github.com/saltstack/salt/issues/23910#issuecomment-120371039, with:

 ```
## /srv/pillar/top.sls:

 base:
    '*':
      - fqdn
```
 and:

 ```
## /srv/pillar/fqdn.sls

{% include "hosts/" + grains['id'] + ".sls" %}
```

 and eg:

 ```
## /srv/pillar/hosts/foo.example.com.sls

 foo: bar
 baz: whee
```

**Comment by willxy** [comment]
And then, this was easier than I expected: 3. Using an [ext_pillar](https://docs.saltstack.com/en/latest/topics/development/external_pillars.html), in particular [PillarStack](https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html), with:

 ```
## /etc/salt/master

...
ext_pillar:
  - stack:
    - /srv/pillar/stack.cfg
...
```

and:

 ```
## /srv/pillar/stack.cfg

hosts/{{ minion_id }}.sls
```

and again eg:

 ```
## /srv/pillar/hosts/foo.example.com.sls

foo: bar
baz: whee
```

This is what I'm leaning toward for my situation; this also has the added benefit of being able to reference these when setting normal other/pillar values (eg with `ext_pillar_first: true`).
