### ISSUE TITLE
Mountpoint in git_pillar

### ISSUE THREAD

**Issue by Boulet-** [saltstack/salt#46128]
### Description of Issue/Question

Mountpoint with git_pillar seems broken.
Doc: https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.git_pillar.html#mountpoints

For me it's something between 5f90812b122bf8b78ddbf94e99cccdbd4cc19203 and 120f49f2c4ec0bb2f36e94d294cd4c15a878b350

Relative commits/pull: 
- e2bd8a809ca2d017d5e762c04c6ade695d31fab2
- https://github.com/saltstack/salt/pull/42506

Workarround, comment this line: https://github.com/saltstack/salt/blob/fba9c9a935a6e81784e0b52a0caab65df4526b1a/salt/pillar/git_pillar.py#L499

### Setup

Ext_pillar with git and mountpoint:
```
ext_pillar:
  - git:
    - master git+ssh://git@x/y/salt-pillars.git:
      - mountpoint: y
```

### Steps to Reproduce Issue

Use above config then restart the Salt master

Master log:
```
2018-02-21 11:29:58,280 [salt.utils.gitfs :271 ][CRITICAL][30359] Invalid git_pillar configuration parameter 'mountpoint' in remote 'master git+ssh://git@x/y/salt-pillars.git'. Valid parameters are: env, root, ssl_verify, refspecs, name.
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-109-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
Looks like i'm able to replicate this using the following config:

```
ext_pillar:
  - git:
    - master https://github.com/saltstack/salt.git:
      - mountpoint: web/server/
```

And when running `salt-master -ldebug`:

```
[CRITICAL] Invalid git_pillar configuration parameter 'mountpoint' in remote 'master https://github.com/saltstack/salt.git'. Valid parameters are: env, root, ssl_verify, refspecs, user, password, pubkey, privkey, passphrase, insecure_auth, name.
[CRITICAL] Failed to load git_pillar
[CRITICAL] Master failed pre flight checks, exiting
```

ping @terminalmage can you take a look here.

**Comment by terminalmage** [comment]
This was an incorrect merge conflict resolution, it seems. I remember fixing this a while back but it looks like I did not fix it in the 2017.7 branch. This has been corrected in https://github.com/saltstack/salt/pull/46264.

**Comment by terminalmage** [comment]
Thanks for the heads-up!

**Comment by sathieu** [comment]
@Boulet- shouldn't this bug be closed?
