### ISSUE TITLE
Filipino Localization

### ISSUE THREAD

**Issue by cordeta** [saltstack/salt#46126]
Hello , i would like to contribute  Filipino Translations of your document. 

Your reply is highly appreciated

**Comment by Ch3LL** [comment]
We don't currently have the ability to support different languages in our docs. As this is a big undertaking this is not currently on our roadmap either. We really appreciate the willingness to help but this is not something we can currently support.

**Comment by cordeta** [comment]
Thank You for your response maam . Just leave this issue open so that you can call my attention if you are open for localization already . Thanks
