### ISSUE TITLE
Silent option for Salt Minion Windows uninstaller

### ISSUE THREAD

**Issue by dumol** [saltstack/salt#4614]
It's immensely helpful that the Windows installer for Salt Minion has a /S switch for unattended install and I think it would be equally helpful to have a /S switch for c:\salt\uninst.exe so that we could do unattended uninstalls. 

Currently the only method to automatically upgrade Salt Minion on Windows is to install over the previous version. Which has worked for me for 0.14.0 -> 0.14.1, but a cleaner upgrade path should be preferable.

Thank you!

**Comment by dhs-rec** [comment]
/S does NOT work. It still opens an "Are you sure ..." type message box (2014.7.2).

**Comment by dumol** [comment]
For the record, the uninstaller does have a silent option now, and it's using the `/S` switch.
