### ISSUE TITLE
Salt is unable to uninstall packages on windows

### ISSUE THREAD

**Issue by AmbicaY** [saltstack/salt#46144]
I used pkg.remove and pkg.purge for uninstalling wireshark, but it does not work.
## wireshark.sls file:
```
{% set PROGRAM_FILES = "%ProgramFiles%" %}
wireshark:
  {% for version in '2.2.12', '2.4.4', '2.5.0' %}
  '{{ version }}':
    {% if grains['cpuarch'] == 'AMD64' %}
    full_name: 'Wireshark {{ version }} (64-bit)'
    installer: 'https://2.na.dl.wireshark.org/win64/Wireshark-win64-{{ version }}.exe'
    {% else %}
    full_name: 'Wireshark {{ version }}'
    installer: 'https://2.na.dl.wireshark.org/win32/Wireshark-win32-{{ version }}.exe'
    {% endif %}
    install_flags: '/S /desktopicon=yes /quicklaunchicon=yes'
    uninstaller: '{{ PROGRAM_FILES }}\Wireshark\uninstall.exe'
    uninstall_flags: ' /S '
    msiexec: False
    locale: en_US
    reboot: False
  {% endfor %}
```

### Steps to Reproduce Issue
salt <servername> pkg.remove 'wireshark'
salt <servername> pkg.purge 'wireshark'
Output for both these commands is the same:
hqdvsaltminion01:
    ----------
    wireshark:
        ----------
        current:
            not installed

# But I still see wireshark on the server as well as it is listed on pkg.list_pkgs
### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.2
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-98-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by damon-atkins** [comment]
I assume you have a version installed other than
`{% for version in '2.2.12', '2.4.4', '2.5.0' %}`

**Comment by AmbicaY** [comment]
I have installed wireshark with the same sls file, so the version I have is 2.5.0:

Output from pkg.list_pkgs:

    Wireshark 2.5.0 64-bit:
        2.5.0

**Comment by AmbicaY** [comment]
I figured it out.

It seems, the full name should match the exact name listed under "Programs and Features" once the package is installed.

So I changed the full name in the sls file as:

full_name: 'Wireshark {{ version }} 64-bit'
