### ISSUE TITLE
"test" module missing from "salt-modindex"

### ISSUE THREAD

**Issue by curiositycasualty** [saltstack/salt#46153]
### Description of Issue/Question
"test" module missing from the [salt-modindex.html](https://docs.saltstack.com/en/latest/salt-modindex.html) page.

It's a tad confusing to have all 3 of these:
- https://docs.saltstack.com/en/latest/salt-modindex.html
- https://docs.saltstack.com/en/latest/ref/modules/all/
- https://docs.saltstack.com/en/latest/salt-modindex.html

Which is the best place to find a definitive list of modules?
Read https://github.com/saltstack/salt/issues/27919 and am none the wiser.

**Comment by garethgreenaway** [comment]
@curiositycasualty Thanks for the report.  Not sure I completely understand the issue you're seeing.  
The `test` module is listed on the https://docs.saltstack.com/en/latest/salt-modindex.html page, it's under `salt.modules.test`.  
This page, https://docs.saltstack.com/en/latest/salt-modindex.html, is the best place for a definitive list of modules, they're organized by subsystem.

**Comment by curiositycasualty** [comment]
I think that clears me up, thanks for getting back to me.

**Comment by garethgreenaway** [comment]
Sounds good!  Definitely let us know any other questions you have. We're always looking to improve our documentation.
