### ISSUE TITLE
sphinx.util.compat and salt/doc/_ext/youtube.py 

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#46158]
### Description of Issue/Question
From salt\doc\_ext\youtube.py  need to do the following for it to work
```
from docutils.parsers.rst import directives, Directive
#from sphinx.util.compat import Directive
```

Seems sphinx project do not want people using  sphinx.util.compat  anymore.

**Comment by gtmanfred** [comment]
This seems reasonable to me.

@saltstack/team-core who is the most familiar with the sphinx documentation that can just OK this?

Thanks,
Daniel

**Comment by rallytime** [comment]
What is the `Directive` call being used for? What version of sphinx is this removed in? We need to check what our system is using before we can remove something like that.

**Comment by damon-atkins** [comment]
Install Sphinx 1.7.0 from pip

**Comment by damon-atkins** [comment]
From http://www.sphinx-doc.org/en/stable/changes.html
3873: Failure of deprecation warning mechanism of sphinx.util.compat.Directive
1.6b1
sphinx.util.compat.Directive class is now deprecated. Please use instead docutils.parsers.rst.Directive
sphinx.util.compat.docutils_version is now deprecated
