### ISSUE TITLE
Roster as pillar?

### ISSUE THREAD

**Issue by danbst** [saltstack/salt#46177]
### Description of Issue/Question
I'd like to reference hosts, defined in flat roster, from state files:
```
{{ pillar['roster']['minion-id']['host'] }}
```
So, changing the IP in roster will propagate change to config files.

Currently I found a workaroud. I set in master config
```
ext_pillars:
   - cmd_yaml: cat /home/ubuntu/servers/etc/roster
```
and can use resulting pillar as `{{ pillar['minion-id']['host'] }}`. But this sucks because I have to supply absolute roster path.

Is there a way to supply current roster data as pillar data?

Salt 2017.7.0

**Comment by Ch3LL** [comment]
ping @saltstack/team-ssh anyone here have any other ideas here on how to approach this?
