### ISSUE TITLE
How many minions the saltstack can suport in target by use  -L (list target match) 

### ISSUE THREAD

**Issue by SwinBlackSea** [saltstack/salt#46188]
command:  salt -L "minion1,minion2,minion3......" test.ping
Q: How many minions the saltstack can suport in target by use  "-L"
if anyone has the answer, please tell me 

Thank you!

**Comment by waynew** [comment]
It should be infinite, limited only by the amount of RAM. Are you running into a problem?

**Comment by SwinBlackSea** [comment]
@waynew  Thank you very much! I just want to evaluate it because my company try to use saltstack.

**Comment by waynew** [comment]
Well if you want to check the status of all minions you'd typically do

```
salt '*' test.ping
```

(Or really `salt-run manage.status`)

It would also be reasonable to group them by name like `salt 'web*'`, or in your example `salt 'minion*' test.ping`

**Comment by SwinBlackSea** [comment]
@waynew I am sorry for no reply to you timely.  Thanks for your advice.
