### ISSUE TITLE
state.alternatives does support slave links

### ISSUE THREAD

**Issue by alasdairdc** [saltstack/salt#46195]
`salt.state.alternatives` does not (or the documentation does not state it does) support slave links.

The Debian man page for `update-alternatives` states:

> update-alternatives  handles  this  by means of master and slave links; when the master is changed, any associated slaves are changed too.  A master link and its associated slaves make up a link group.

This is noticable on Debian 9 (Stretch) which by default install `mailutils`, however if you install `heirloom-mailx` (to support cli args for `CC / BCC`) you need to manually create the alternative using something like

    sudo update-alternatives --install /usr/bin/mailx mailx /usr/bin/heirloom-mailx \
    60 --slave /usr/bin/mail mail /usr/bin/heirloom-mailx

If you not use the `--slave` option, only the `/usr/bin/mailx` is updateable whereas if you do use the `--slave` option as in the command above it controls both `/usr/bin/mail` and `/usr/bin/mailx`

**Comment by Ch3LL** [comment]
glancing at the code i'm not seeing this option being used as well. will approve as a feature request. 

ping @rrada looks like you added this state, mind taking a look here if you get a chance?
