### ISSUE TITLE
Issue #44034 still unresolved

### ISSUE THREAD

**Issue by seanjnkns** [saltstack/salt#46207]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
See issue #44034

### Steps to Reproduce Issue
See issue #44034

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.9
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.4.3
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
        machine: x86_64
        release: 4.9.84-1.el7.centos.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by seanjnkns** [comment]
Just tested this with 2016.11.9-2 on CentOS 7.4, and the issue still exists even though I've confirmed the patch is applied. This seems consistent with how I had the issue before even with the patch applied, and yet using the git branch and installing from source vs. upstream RPMs, seemed to correct the issue.

I'll check out 2017.7.4 and see if that changes my outcome and respond back here.

**Comment by seanjnkns** [comment]
2017.7.4 has the same issue.

**Comment by seanjnkns** [comment]
In fact, reverting back to 2016.11.8 and then applying the 1 line patch from #44483, and restarting the salt-master service, still doesn't fix the issue.  I'm guessing some environment variable, stroke of luck, idk, triggered this to work during my testing before on the other ticket as it's still not resolved unfortunately.

**Comment by garethgreenaway** [comment]
@terminalmage Looks like were working on this before.

**Comment by terminalmage** [comment]
This works just fine for me (docker commands run from root of repo):

```
% for tag in v2016.11.8 v2016.11.9 v2017.7.2 v2017.7.3 v2017.7.4; do git checkout -q $tag; echo -n "$tag: "; sudo find . -type f -name \*.pyc -delete; docker run --rm -it -v $PWD:/testing terminalmage/issues:44034 sh /test.sh >/dev/null 2>&1 && echo "works" || echo "broken"; done; git checkout -q develop
v2016.11.8: broken
v2016.11.9: works
v2017.7.2: broken
v2017.7.3: works
v2017.7.4: works
```

Here's the test script:
```
% docker run --rm -it -v $PWD:/testing terminalmage/issues:44034 cat /test.sh
salt-master -d; salt-minion -d
sleep 10
echo "" > /var/log/salt/master
/usr/bin/salt-call state.highstate pillar='{"foo":"bar"}'
fgrep "PILLAR: {'foo': 'bar'}" /var/log/salt/master && exit 0 || exit 1
```

The master config file:
```
% docker run --rm -it -v $PWD:/testing terminalmage/issues:44034 egrep '^[^#]' /etc/salt/master
extension_modules: /srv/modules
ext_pillar:
  - my_ext_pillar:
```

The custom ext_pillar:
```
%  docker run --rm -it -v $PWD:/testing terminalmage/issues:44034 cat /srv/modules/pillar/my_ext_pillar.py
import logging

log = logging.getLogger(__name__)

def ext_pillar(minion_id, pillar, *args, **kwargs):
    log.critical("PILLAR: %s" % str(pillar))
    return None
```

You can also browse around the container if you just run it without the `sh /test.sh` after.

If you can provide a use case where this fails in newer releases, I'd be happy to take a look at it though.

**Comment by seanjnkns** [comment]
This works until you start adding any role based setup, CMDB to manage roles, pillars (excluding ext_pillar), etc.  If you have this in the most basic of skeleton setups, yes, it works, add even the most basic entry in /srv/pillar, and you lose 100% of your pillar output from the external pillar.  Even with ext_pillar_first: True set in /etc/salt/master, it's as if this isn't honored.  I'll see if I can package up another example to better illustrate this.

**Comment by seanjnkns** [comment]
[issue-44034.tar.gz](https://github.com/saltstack/salt/files/1781946/issue-44034.tar.gz)

The attached example should give a better understanding of what's happening.  Even with ext_pillar_first, /srv/pillar is being read first.  Try changing merging strategies, no change.  Remove /srv/pillar/top.sls, and your ext_pillar output will have output.  No amount of manipulating the the master or minion configs seems to change the outcome.

Let me know if there's anything further I can provide.

**Comment by terminalmage** [comment]
@seanjnkns Thanks, I'll have a look at this over the next couple days.

**Comment by seanjnkns** [comment]
@terminalmage Any update or have you at least confirmed that you're able to reproduce the issue now?

**Comment by terminalmage** [comment]
@seanjnkns I was able to reproduce, I should have a fix soon.

**Comment by terminalmage** [comment]
I hadn't been able to, but that was user error, I was looking for the wrong thing, I literally just figured out where I was going wrong about 20 mins before your recent comment.

**Comment by rallytime** [comment]
@seanjnkns Can you give #46493 a try? That should fix this up for you.

**Comment by terminalmage** [comment]
@seanjnkns https://github.com/saltstack/salt/pull/46493 has a fix, and includes a docker container for confirming the fix.

**Comment by seanjnkns** [comment]
Testing this now.

**Comment by seanjnkns** [comment]
Tested on 2016.11.9 and confirmed working.  Haven't tested on 2017.7.4 however, but I can if you need me to.  Also, tested w/ and w/out ext_pillar_first: True, to see if this option was honored when True or False, and it is.  Any chance we can get this fix backported to 2016.11.x?

**Comment by terminalmage** [comment]
@rallytime Are we planning on doing another 2016.11 release? Do you think it would be worth backporting just in case?

**Comment by rallytime** [comment]
@terminalmage There is not another 2016.11 release planned. It is in CVE-only mode now.

**Comment by terminalmage** [comment]
@seanjnkns It doesn't look like this will be backported to 2016.11, since 2016.11.10 (if released) would receive CVE fixes only.
