### ISSUE TITLE
git_pillar_branch doesnt do anything

### ISSUE THREAD

**Issue by The-Loeki** [saltstack/salt#46224]
### Description of Issue/Question
```
[theloeki@murphy salt]$ grep -R git_pillar_branch
conf/suse/master:#git_pillar_branch: master
conf/master:#git_pillar_branch: master
doc/man/salt.7:.SS \fBgit_pillar_branch\fP
doc/man/salt.7:git_pillar_branch: pillardata
doc/man/salt.7:#git_pillar_branch: master
doc/ref/configuration/master.rst:.. conf_master:: git_pillar_branch
doc/ref/configuration/master.rst:``git_pillar_branch``
doc/ref/configuration/master.rst:    git_pillar_branch: pillardata
salt/config/__init__.py:    'git_pillar_branch': str,
salt/config/__init__.py:    'git_pillar_branch': 'master',
salt/config/__init__.py:    'git_pillar_branch': 'master',
tests/support/gitfs.py:    'git_pillar_branch': 'master',
```

**Comment by gtmanfred** [comment]
@terminalmage do you remember if there was something else that replaced this in the git_pillar config?

Thanks,
Daniel

**Comment by terminalmage** [comment]
The docs are pretty clear on what it does: https://docs.saltstack.com/en/latest/ref/configuration/master.html#git-pillar-branch

[This block](https://github.com/saltstack/salt/blob/d6c2d06/salt/utils/gitfs.py#L1013-L1027) is where the value comes into play.

A simple grep doesn't always tell the whole story. :)

**Comment by gtmanfred** [comment]
Thanks Erik!
Daniel

**Comment by The-Loeki** [comment]
hehehe I did a few, but not that particular one. Sorry ;)

**Comment by terminalmage** [comment]
@The-Loeki Actually, I did find an issue with the branch being overridden by the `git_pillar_branch`, so thanks for the heads-up: https://github.com/saltstack/salt/issues/46259

Fix should be coming soon.
