### ISSUE TITLE
win_dsc - Usage clarification

### ISSUE THREAD

**Issue by absolutejam** [saltstack/salt#46234]
Hey people,

I'm trying to use Salt as an engine to manage & deploy DSC configurations to multiple environments and I'm struggling to get to grips with exactly how the current implementation works. I don't want this to come across as negative, but instead I'm willing to tweak the module and documentation as needed, but just wanted a bit of feedback before doing so.

First of all, the module says that you provide a .ps1 script containing a `configuration` block and you can generate a DSC config (.MOF) from that. Also, you can specify the configuration if the file contains multiple. However, I found that I had to both define the configuration block and call it within the same script. I've yet to test generating multiple (as I'd do that in separate files anyway).

Additionally, the `_pshell` method used to call the `Start-DSCConfiguration` powershell cmdlet expects some sort of structured output that can be transformed to JSON - And errors if this isn't given. But from what I've seen, with a general run of `Start-DSCConfiguration`, there generally isn't any output that conforms to this - Am I required to add this somewhere, and if so, how would I as this would be output from the MOF file, not the .ps1.

So, to clarify the situation, do the docs need making more specific with some fuller examples and prerequesuite, or do some of the methods need tweaking? For example, the `compile_config` method could dot source the .ps1 and run the configuration instead of directly running the entire file?

What are your thoughts?

**Comment by absolutejam** [comment]
Re-reading and it looks like the module should/does run the configuration block! Need to test this more as it hasn't worked yet for me.

**Comment by gtmanfred** [comment]
@damon-atkins @twangboy @UtahDave It looks like yall have all worked on this.  As I have never used DSC before, would you mind assisting with @absolutejam 's questions?

Thanks!
Daniel

**Comment by twangboy** [comment]
I haven't been in the code for a while, but I'll take a look

**Comment by absolutejam** [comment]
I've only been able to have a quick run through the code, but it looks like an issue with the `_pshell` module failing if the output can't be converted to JSON, but not all instances of it need to/can output JSON. I'm going to try and suppress/catch the `CommandExecutionError` and see how it works out.

**Comment by twangboy** [comment]
@absolutejam The `compile_config` function attempts to compile the config file as is first. If it fails, then it attempts to dot source it. There is an issue with how _pshell is handling the return. I'm working on a fix for this.

**Comment by absolutejam** [comment]
Awesome, thanks @twangboy!

Once that's approved, I'm going to look at adding `Invoke-DSCResource` as a function too, as I find myself needing just a single DSC resource frequently (eg. some from `xRemoteDesktopSessionHost`) and eventually, I'm going to try and convert them into states...

**Comment by muddman** [comment]
Is there a complete working example of how to use win_dsc anywhere? thanks!
