### ISSUE TITLE
utils.configcomparer does not detect all changes 

### ISSUE THREAD

**Issue by iustinam** [saltstack/salt#46245]
### Description of Issue/Question
utils.configcomparer does not detect if values were removed in the new config (which existed in the old config) because it only checks if anything in the new config would change something in the old config. eg. "new_config-old_config" but not "old_config-new_config"

### Setup
https://github.com/saltstack/salt/blob/develop/salt/utils/configcomparer.py#L39

### Steps to Reproduce Issue
Let's say new config is {'a':'b'} and old config is {'a':'b', 'c':d'}
The config comparer won't see that the new config does not have 'c':'d' and won't report any change

### Versions Report
2017.7.2

**Comment by gtmanfred** [comment]
@gauntletbuild can you take a look at this?

@iustinam brings up a good point, but is this the way the comparer was intended to work. It looks like it was specifically written for the chronos and marathon proxy minions that were included in this PR

https://github.com/saltstack/salt/pull/28778

Thanks,
Daniel

**Comment by iustinam** [comment]
@gtmanfred I am using marathon_proxy in my case. I have an external pillar that fetches secrets from vault and puts them in the app env. It happened to me that one secret was not in vault but marathon_app state didn't detect that there was a change on this app. If I stop the containers and redeploy the app, that secret would be missing.

**Comment by iustinam** [comment]
@gtmanfred why would this be the way it is intended to work? Can you provide an example?

**Comment by gtmanfred** [comment]
If you look at the PR, this was specifically added to work with those modules.  All I am doing is asking for feedback from the original author of the code.

It isn't used anywhere else, only by his code, so he should have some input.

**Comment by toddtomkinson** [comment]
Currently, it looks like this code preserves any attributes in the config that are not in the config passed by salt:

```
            # compare each key in the base config with the values in the
            # update_config, overwriting the values that are different but
            # keeping any that are not defined in config
```

I believe this was a feature that preserved changes made via the marathon admin tools for properties that were not defined in the salt pillar data.  In most cases this is probably not wanted, but if it is going to be changed it should probably be passed a flag to change the logic to remove the keys.

I am not actively using this anymore, so feel free to change.

**Comment by gtmanfred** [comment]
Perfect, thanks Todd.

I am going to mark this as a feature request to add a flag to allow for removing keys.

Thanks,
Daniel
