### ISSUE TITLE
chocolatey.installed broken on 2017.7.4

### ISSUE THREAD

**Issue by jkrauz** [saltstack/salt#46240]
### Description of Issue/Question
chocolatey.installed fails when checking if the package already exists before attempting to install.
The same as in this closed issue: [https://github.com/saltstack/salt/issues/42521](https://github.com/saltstack/salt/issues/42521)

### Steps to Reproduce Issue

salt-call state.single chocolatey.installed microsoft-build-tools

          ID: microsoft-build-tools
    Function: chocolatey.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1851, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\chocolatey.py", line 104, in installed
                  version_info = __salt__['chocolatey.version'](name, check_remote=True)
                File "c:\salt\bin\lib\site-packages\salt\modules\chocolatey.py", line 889, in version
                  'available': available[pkg]}
              KeyError: 'microsoft-build-tools'
     Started: 02:16:34.942000
    Duration: 2359.0 ms
     Changes:

Strange part is it fails with the above error for some packages (microsoft-build-tools) but works fine for others (dotnet3.5).

### Versions Report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.16299  Multiprocessor Free

**Comment by gtmanfred** [comment]
@twangboy @dwoz can one of yall look at this?

Thanks,
Daniel

**Comment by gtmanfred** [comment]
yup, thanks @whytewolf 

Closing as a duplicate.
