### ISSUE TITLE
pillar.get is not working inside  for hubblestack_data/hubblestack_nova_profiles/*.YAML file 

### ISSUE THREAD

**Issue by sam0104** [saltstack/salt#46252]
### Description of Issue/Question

pillar.get is not working inside  for hubblestack_data/hubblestack_nova_profiles/*.YAML file . We have few OS related audits where we want to call pillar data for set Timezone  from pillar value. Standard Salt pillar syntax is not working. 

### Setup

(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
we have  2017.7.2  and using latest hubble modules as Formula .

### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

Below is the OS related YAML file where we are trying to use pillar value for Timezone but it is not working.  **How can I use pillar value inside hubble ?**
```
OS_Linux.yaml is under  /srv/formulas/hubblestack_nova_profiles/
Error: /OS_Linux.yaml:
            while parsing a flow mapping
              in "/var/cache/salt/minion/files/base/hubblestack_nova_profiles/OS_Linux.yaml", line 16, column 23
            expected ',' or '}', but got '['
              in "/var/cache/salt/minion/files/base/hubblestack_nova_profiles/OS_Linux.yaml", line 16, column 31
==========================
grep:
  whitelist:
    timezone_set:
      data:
        '*':
        - /etc/timezone:
            **pattern: {{ pillar['hubblestack_nova']['timezone'] }}**
            tag: OS_Linux_v12-2
      description: Ensure timezone is set correctly
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt --versions-report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by basepi** [comment]
Unfortunately profiles in hubble-salt are not currently run through the jinja templating system. If you'd like, you can file a feature request in our repo: https://github.com/hubblestack/hubble/issues/new
