### ISSUE TITLE
SSL Handshake error when adding 3rd party apt repo for influxdb on Ubuntu 14.04

### ISSUE THREAD

**Issue by PredatorVI** [saltstack/salt#46266]
### Description of Issue/Question
For the first time in a while we are deploying an application to Ubuntu 14.04.  We have recently updated to the latest SaltStack 2017.7.2 (and now 2017.7.3) packages though I do NOT know what version this started to fail in since our efforts have been focused elsewhere.  

When we try to install telegraf using a simple formula (not sure the original source of the files), we see this SSLv3 Error on both new, clean Ubuntu 14.04 minions as well as minions that have previously had this repo installed and working.
```
                 "pkgrepo_|-influxdata_repo_|-deb https://repos.influxdata.com/ubuntu trusty stable_|-managed": {
                    "comment": "Failed to configure repo 'deb https://repos.influxdata.com/ubuntu trusty stable': [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure",
                    "_stamp": "2018-02-28T01:22:29.641720",
                    "return": "Error: pkgrepo.managed",
                    "retcode": 2,
                    "success": false,
                    "start_time": "01:22:21.209159",
                    "jid": "20180228011851990582",
                    "name": "deb https://repos.influxdata.com/ubuntu trusty stable",
                    "fun": "state.highstate",
                    "result": false,
                    "duration": 265.252,
                    "__run_num__": 93,
                    "__sls__": "telegraf.telegraf",
                    "changes": {
                        
                    }
```

I've seen the following other issues that are similar (based on the error message), but I can not find a way to work around this, beyond manually adding the repo key and repo and manually installing the package.

https://github.com/influxdata/influxdb/issues/9199
https://github.com/saltstack/salt/issues/42485

In issue 9199 above suggests using variations on the URL to use HTTP and/or add the trailing '/' but all variations fail.

### Versions Report
> Salt Version:
>            Salt: 2017.7.3
> 
> Dependency Versions:
>            cffi: Not Installed
>        cherrypy: Not Installed
>        dateutil: 1.5
>       docker-py: Not Installed
>           gitdb: Not Installed
>       gitpython: Not Installed
>           ioflo: Not Installed
>          Jinja2: 2.7.2
>         libgit2: Not Installed
>         libnacl: Not Installed
>        M2Crypto: Not Installed
>            Mako: 0.9.1
>    msgpack-pure: Not Installed
>  msgpack-python: 0.4.6
>    mysql-python: 1.2.3
>       pycparser: Not Installed
>        pycrypto: 2.6.1
>    pycryptodome: Not Installed
>          pygit2: Not Installed
>          Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
>    python-gnupg: Not Installed
>          PyYAML: 3.10
>           PyZMQ: 14.4.0
>            RAET: Not Installed
>           smmap: Not Installed
>         timelib: Not Installed
>         Tornado: 4.2.1
>             ZMQ: 4.0.5
> 
> System Versions:
>            dist: Ubuntu 14.04 trusty
>          locale: UTF-8
>         machine: x86_64
>         release: 3.13.0-141-generic
>          system: Linux
>         version: Ubuntu 14.04 trusty

[telegraf.zip](https://github.com/saltstack/salt/files/1769050/telegraf.zip)

**Comment by rickh563** [comment]
ZD-2293

**Comment by PredatorVI** [comment]
I've tried the following variations on the repo URL:

https://repos.influxdata.com/ubuntu
https://repos.influxdata.com/ubuntu

**Comment by PredatorVI** [comment]
I've tried the following variations on the repo URL:

http://repos.influxdata.com/ubuntu
http://repos.influxdata.com/ubuntu/
https://repos.influxdata.com/ubuntu
https://repos.influxdata.com/ubuntu/

Since the top 3 urls redirect to the last one, I hoped the issue was related to the '301 - Moved Permanently' response and the last one would be the one that works but it didn't.

**Comment by gtmanfred** [comment]
Just to double check, do you have the `apt-transport-https` package installed, which is required to use https repositories for apt?

Daniel

**Comment by PredatorVI** [comment]
Yes, though I didn't explicitly install it.

```
root@testtelegrafinstall:/var/log# dpkg -l | grep apt-transport-https
ii  apt-transport-https                 1.0.1ubuntu2.17                            amd64        https download transport for APT
```

**Comment by whytewolf** [comment]
The issue looks to be salt grabbing the key, not the name field. Not sure if this is a bug in tornado, pyOpenSSL, or openssl yet. 

```
salt-call cp.cache_file https://repos.influxdata.com/influxdb.key
[WARNING ] SSL Error on 18 ('54.192.146.253', 443): [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 474, in cache_file
    result = _client().cache_file(path, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 189, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 698, in get_url
    **get_kwargs
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 507, in query
    **req_kwargs
  File "/usr/local/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch
    self._async_client.fetch, request, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 11, in <module>
    salt_call()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 391, in salt_call
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/call.py", line 58, in run
    caller.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 134, in run
    ret = self.call()
  File "/usr/lib/python2.7/dist-packages/salt/cli/caller.py", line 204, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 474, in cache_file
    result = _client().cache_file(path, saltenv)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 189, in cache_file
    return self.get_url(path, '', True, saltenv, cachedir=cachedir)
  File "/usr/lib/python2.7/dist-packages/salt/fileclient.py", line 698, in get_url
    **get_kwargs
  File "/usr/lib/python2.7/dist-packages/salt/utils/http.py", line 507, in query
    **req_kwargs
  File "/usr/local/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch
    self._async_client.fetch, request, **kwargs))
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 458, in run_sync
    return future_cell[0].result()
  File "/usr/local/lib/python2.7/dist-packages/tornado/concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
ssl.SSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure
```

**Comment by gtmanfred** [comment]
You should be able to see if it is a bug in tornado by setting `backend: requests` in /etc/salt/minion, then it will use requests in salt.utils.http instead of tornado.

**Comment by whytewolf** [comment]
okay, changing that option had 0 effects. so this looks like pyOpenSSL or openssl. most likely openssl. as updating pyOpenssl did not fix.

**Comment by PredatorVI** [comment]
I just found this link regarding the need to use SNI (Server Name Indication) with certain sites or the handshake will fail.  

https://stackoverflow.com/questions/34187934/openssl-connection-error-ssl23-get-server-hello-but-browser-and-curl-works

I tried the following:

(FAIL) :# openssl s_client -connect repos.influxdata.com:443 -prexit 

(WORKS) :# openssl s_client -connect repos.influxdata.com:443 -servername repos.influxdata.com -prexit

I don't know exactly what SNI is or how that would translate to salt's use of SSL.

**Comment by Ch3LL** [comment]
i believe SNI support was added in python 2.7.9. ping @team-core anyone know if there is a way to handle this for versions lower then 2.7.9

**Comment by rallytime** [comment]
No, not that I know of. You would need to upgrade to a newer version of Python.
