### ISSUE TITLE
Not able to pass kwargs in destroy function of azurearm.py

### ISSUE THREAD

**Issue by nkv16786** [saltstack/salt#46279]
### Description of Issue/Question

Hi i want to give the following options in destroy vm command:-
cleanup_disks=True
cleanup_vhds=True
cleanup_data_disks= True
cleanup_interfaces=True

But i am not able to set this values.

I have used the following commands : 

```
salt-call cloud.action destroy instance=deletetestvm17 kwargs='{"cleanup_interfaces":True}'

salt-call cloud.action destroy instance=deletetestvm17 cleanup_interfaces=True
```

**But kwargs is not being set .**

Please let me know how to set the above mentioned values

### Versions Report
Salt: **2017.7.1**

**Comment by Ch3LL** [comment]
You can set these in your cloud provider or cloud profile config shown below:

```
  cleanup_disks: True
  cleanup_vhds: True
  cleanup_services: True
```

**Comment by nkv16786** [comment]
yes i know i can set thes values in profile or provider but is there a way to send these values in salt destroy vm command like as follows:-

salt-call cloud.action destroy instance=deletetestvm17 kwargs='{"cleanup_interfaces":True}'

**Comment by nkv16786** [comment]
It worked by changing the kwargs position in destroy function of azurearm.py

Earlier it was like--    `def destroy(name, conn=None, call=None, kwargs=None):`

I changed it to--        `def destroy(name,kwargs=None, call=None,conn=None):`

**Comment by Ch3LL** [comment]
ahh thanks for clarifying. Seems you have a possible patch here. ping @saltstack/team-windows do you think this is an appropriate patch for this issue? or is there already a way to currently do this?
