### ISSUE TITLE
salt master not releasing memory

### ISSUE THREAD

**Issue by jvrahav** [saltstack/salt#46282]
### Description of Issue/Question
I have a salt master running in a docker container hooked on to 280 minions running in different vms on the same network.

When the master is not connected to any minions it uses about 300 mb of ram. As i add new minions, i provision these through a script, the master start consuming more memory. For 100 minions it consumes about 1.4gb ram. As i add more minions the ram keeps increasing reaching about 2 gb ram utilization for 280 minions. After an hour when there is no user induced operation on the setup, master reduces its memory consumption to 1.7gb. It stays at this level for long time coming down only until 1.3 gb after which when any operation is performed like applying sls on a minion or a ping command it increases to say 1.9gb and after some time comes down to 1.8gb and stays there.

I expect the salt master to free up ram after some time but the ram it relinquishes is pretty much negotiable. The master host has 5gb ram.

are there any pointers to how i can tune this master to utlize resources better.vi etc

### Setup
master config

```
keep_jobs: 1
job_cache: False
external_auth:
  pam:
    admin:
      - '@wheel'
      - '@runner'
      - '@jobs'
      - .*
rest_tornado:
  port: 8553
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
  webhook_url: /hook
  websockets: True
  disable_ssl: False
  debug: False
  zmq_filtering: True
  log_level_logfile: error
```

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 25 2017, 01:32:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.114-1.ph1
         system: Linux
        version: Not Installed

**Comment by Ch3LL** [comment]
can you install setproctitle and paste output of `ps aux | grep -i salt`?

aslo anything useful in the debug logs?

**Comment by jvrahav** [comment]
just to add more info, this is a slightly bigger setup than the one mentioned in the issue, however the symptoms and behaviour are the same

here we have one salt master connected to 15k minions.

when we do a test.ping from master we get response as 8k are connected. The rest of them say no response or not connected

i tried for few of the minions. After restarting the minion, the master was able to conenct to the minion.

salt master spec
GiB Mem : 73.7/47.168  
GiB Swap: 38.5/4.000  

free -m
                    total        used        free      shared  buff/cache   available
Mem:          48300       35149        3141           0       10009       12707
Swap:          4095        1576        2519

**Comment by damon-atkins** [comment]
`lsof -i` will help id which process is accepting all the connections.

**Comment by jvrahav** [comment]
output of lsof -i | egrep salt  shows
7742 connections for 4505 - consumed by process 67
1050 connections for 4506 - consumed by process 23667

root        62  0.0  0.0 277012 14504 ?        S    Feb28   0:06 /bin/python /usr/bin/salt-master -d
root        63  0.0  0.0 273756  9068 ?        S    Feb28   0:00 /bin/python /usr/bin/salt-master -d
root        67  0.6  1.9 1171232 954272 ?      Sl   Feb28  27:58 /bin/python /usr/bin/salt-master -d
root        68  5.7  4.1 2744528 2072804 ?     S    Feb28 247:48 /bin/python /usr/bin/salt-master -d
root        73 14.1  0.7 5029416 353548 ?      Sl   Feb28 612:58 /bin/python /usr/bin/salt-master -d
root        75  0.0  0.0 277012 14112 ?        S    Feb28   0:06 /bin/python /usr/bin/salt-master -d
root        77  6.3  0.1 465332 75816 ?        Sl   Feb28 274:08 /bin/python /usr/bin/salt-master -d
root        85  6.2  0.1 467380 78168 ?        Sl   Feb28 272:02 /bin/python /usr/bin/salt-master -d
root        86  6.2  0.1 466332 75836 ?        Sl   Feb28 273:08 /bin/python /usr/bin/salt-master -d
root        87  6.3  0.1 463264 74432 ?        Sl   Feb28 274:01 /bin/python /usr/bin/salt-master -d
root        88  6.3  0.1 465608 76000 ?        Sl   Feb28 275:17 /bin/python /usr/bin/salt-master -d
root        92  0.0  0.0 199776  2924 ?        S    Feb28   0:05 /bin/python /usr/bin/salt-api -d
root        94  0.6  0.0 210244 40052 ?        S    Feb28  29:05 /bin/python /usr/bin/salt-api -d
root     23667  2.4 61.2 32869484 30310204 ?   Sl   Mar01  59:15 /bin/python /usr/bin/salt-master -d
root     29260  0.3  0.1 300444 61676 ?        S    Mar01   7:26 /bin/python /usr/bin/salt-master -d

**Comment by jvrahav** [comment]
/proc/sys/fs/file-max - 2097152

**Comment by damon-atkins** [comment]
Yes number of minions = number of connections
Try `egrep 'Current values for max open files soft/hard setting'  /var/log/salt/master`

**Comment by damon-atkins** [comment]
When you past text please place  ``` start end end of the text or click <> while the text is high-lighted (You can edit you existing posts)

**Comment by jvrahav** [comment]
@damon-atkins there are no log entries in the master for the given text.

Also, i dont see anything in the logs on the minion when i run salt-run manage.down or salt 'minionid' test.ping

**Comment by jvrahav** [comment]
@damon-atkins  however when i restart the minion, the master able to successfully ping the minion

**Comment by jvrahav** [comment]
after setting a higher ulimit on the salt master docker to 100000, i can still only see max of 7800 connections to port 4505

netstat -tp | grep python | grep '2d009d977b0c:4505' | wc -l (all are in ESTABLISHED state)

**Comment by damon-atkins** [comment]
`Current values for max open files soft/hard setting` is log.info.  I suggest you are hitting some sort of limit.

**Comment by jvrahav** [comment]
logs are at debug level. I dont see any logs that match the error you have mentioned. The logs mostly has that statements related to sending request and receiving reponse related to ping commands i run.

**Comment by Ch3LL** [comment]
You can see the log.info here: https://github.com/saltstack/salt/blob/v2017.7.2/salt/master.py#L407

which is on your version of salt 2017.7.2

and i checked to ensure one would expect to see this with: `grep -ri "Current values for max open files " /var/log/salt`

```➜  salt git:(1439da8d76) sudo grep -ri "Current values for max open files " /var/log/salt
/var/log/salt/master:2018-01-09 10:45:24,264 [salt.master      :403 ][INFO    ][31562] Current values for max open files soft/hard setting: 1024/4096
/var/log/salt/master:2018-01-09 11:30:03,501 [salt.master      :403 ][INFO    ][11108] Current values for max open files soft/hard setting: 1024/4096
```

can you try that grep command?

**Comment by jvrahav** [comment]
this is what it says in the log Current values for max open files soft/hard setting: 100000/100000
as i have set that as the limit

**Comment by damon-atkins** [comment]
I suspect it could be fact your running in a docker container. Need to check inside and outside the container.

`sysctl net.netfilter.nf_conntrack_max`
`cat /proc/sys/net/ipv4/netfilter/ip_conntrack_max`

**Comment by jvrahav** [comment]
hi,

sorry to have left this unanaswered. I tried few more tests and found better success even with master running in a docker.

However the original issue of salt master not releasing memory still exists for example

i have 40 minions connected to a master. Master is consuming 

```
cache 10436608
rss 556679168
```
 
After an hour i turned of all minions. Right now there are no minions connected to the master. Yet the master memory consumption hasnt come down. its been more than 12 hours since the minions were turned off. I would like to know if there is a way to initiate grabage collection of the process

```
oot     23189  0.0  0.5 279060 40992 ?        S    May16   0:01 /bin/python /usr/bin/salt-master -d ProcessManager
root     23190  0.0  0.4 275852 37752 ?        S    May16   0:00 /bin/python /usr/bin/salt-master -d MultiprocessingLoggingQueue
root     23192  0.0  0.5 287000 41720 ?        Sl   May16   0:00 /bin/python /usr/bin/salt-master -d ZeroMQPubServerChannel
root     23195  0.0  0.7 302000 62080 ?        S    May16   0:01 /bin/python /usr/bin/salt-master -d EventPublisher
root     23197  0.5  1.7 1271800 143896 ?      Sl   May16   6:03 /bin/python /usr/bin/salt-master -d Reactor
root     23198  0.0  0.7 300960 62960 ?        S    May16   0:24 /bin/python /usr/bin/salt-master -d Maintenance
root     23199  0.0  0.4 279060 39080 ?        S    May16   0:01 /bin/python /usr/bin/salt-master -d ReqServer_ProcessManager
root     23200  0.0  0.5 582184 43436 ?        Sl   May16   0:01 /bin/python /usr/bin/salt-master -d MWorkerQueue
root     23201  0.0  0.8 453372 66656 ?        Sl   May16   0:04 /bin/python /usr/bin/salt-master -d MWorker-0
root     23208  0.0  0.8 453672 66852 ?        Sl   May16   0:04 /bin/python /usr/bin/salt-master -d MWorker-1
root     23209  0.0  0.8 453452 66468 ?        Sl   May16   0:04 /bin/python /usr/bin/salt-master -d MWorker-2
root     23211  0.0  0.8 453600 66452 ?        Sl   May16   0:04 /bin/python /usr/bin/salt-master -d MWorker-3
root     23212  0.0  0.8 453736 67580 ?        Sl   May16   0:04 /bin/python /usr/bin/salt-master -d MWorker-4
```

**Comment by damon-atkins** [comment]
FYI Solaris does not return memory to OS once free() is called and others OS likely do the same thing.  
Found this discussion for you https://stackoverflow.com/questions/12050777/how-to-return-memory-from-process-to-the-os

This is why a lot of servers folk a process to respond.

**Comment by jvrahav** [comment]
salt master is running on rhel based os. Any pointers on tool to profile the memory so we can identify which thread or code is consuming the memory.
