### ISSUE TITLE
Build 449: unit.test_pyobjects.RendererTests

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#46350]
[unit.test_pyobjects.RendererTests.test_basic](https://jenkins.saltstack.com/job/2017.7/job/salt-dev-c7-windows-py2/449/testReport/junit/unit.test_pyobjects/RendererTests/test_basic/)
[unit.test_pyobjects.RendererTests.test_extend](https://jenkins.saltstack.com/job/2017.7/job/salt-dev-c7-windows-py2/449/testReport/junit/unit.test_pyobjects/RendererTests/test_extend/)
[unit.test_pyobjects.RendererTests.test_import_random_password](https://jenkins.saltstack.com/job/2017.7/job/salt-dev-c7-windows-py2/449/testReport/junit/unit.test_pyobjects/RendererTests/test_import_random_password/)
[unit.test_pyobjects.RendererTests.test_import_scope](https://jenkins.saltstack.com/job/2017.7/job/salt-dev-c7-windows-py2/449/testReport/junit/unit.test_pyobjects/RendererTests/test_import_scope/)
[unit.test_pyobjects.RendererTests.test_include](https://jenkins.saltstack.com/job/2017.7/job/salt-dev-c7-windows-py2/449/testReport/junit/unit.test_pyobjects/RendererTests/test_include/)
[unit.test_pyobjects.RendererTests.test_invalid_function](https://jenkins.saltstack.com/job/2017.7/job/salt-dev-c7-windows-py2/449/testReport/junit/unit.test_pyobjects/RendererTests/test_invalid_function/)
[unit.test_pyobjects.RendererTests.test_random_password](https://jenkins.saltstack.com/job/2017.7/job/salt-dev-c7-windows-py2/449/testReport/junit/unit.test_pyobjects/RendererTests/test_random_password/)
[unit.test_pyobjects.RendererTests.test_requisite_implicit_list](https://jenkins.saltstack.com/job/2017.7/job/salt-dev-c7-windows-py2/449/testReport/junit/unit.test_pyobjects/RendererTests/test_requisite_implicit_list/)
[unit.test_pyobjects.RendererTests.test_sls_imports](https://jenkins.saltstack.com/job/2017.7/job/salt-dev-c7-windows-py2/449/testReport/junit/unit.test_pyobjects/RendererTests/test_sls_imports/)

**Comment by twangboy** [comment]
I believe @terminalmage said he needed to fix this one

**Comment by twangboy** [comment]
Passes when run Manually

**Comment by terminalmage** [comment]
I don't recall saying anything about these tests, I don't really know much about pyobjects.

It looks like the `__salt__` dunder doesn't have the config.get function, but I can't tell you why. It passes on the previous lines where mine.get, etc. are referenced, so ¯\_(ツ)_/¯.
