### ISSUE TITLE
Build 66: unit.fileserver.test_gitfs

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#46363]
[unit.fileserver.test_gitfs.GitPythonTest.test_dir_list](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/unit.fileserver.test_gitfs/GitPythonTest/test_dir_list/)
[unit.fileserver.test_gitfs.GitPythonTest.test_envs](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/unit.fileserver.test_gitfs/GitPythonTest/test_envs/)
[unit.fileserver.test_gitfs.GitPythonTest.test_file_list](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/unit.fileserver.test_gitfs/GitPythonTest/test_file_list/)
[unit.fileserver.test_gitfs.GitPythonTest.test_ref_types_global](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/unit.fileserver.test_gitfs/GitPythonTest/test_envs/)
[unit.fileserver.test_gitfs.GitPythonTest.test_ref_types_per_remote](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/unit.fileserver.test_gitfs/GitPythonTest/test_ref_types_per_remote/)

**Comment by sathieu** [comment]
What does this bug mean?

**Comment by waynew** [comment]
The links for this are broken/missing. I'm gonna go ahead and close this since I'm creating other issues for test failures.
