### ISSUE TITLE
Build 66: integration.modules.test_state

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#46362]
[integration.modules.test_state.StateModuleTest.test_catch_recurse](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/integration.modules.test_state/StateModuleTest/test_catch_recurse/)
[integration.modules.test_state.StateModuleTest.test_onchanges_in_requisite](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/integration.modules.test_state/StateModuleTest/test_onchanges_in_requisite/)
[integration.modules.test_state.StateModuleTest.test_onchanges_requisite](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/integration.modules.test_state/StateModuleTest/test_onchanges_requisite/)
[integration.modules.test_state.StateModuleTest.test_onchanges_requisite_multiple](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/integration.modules.test_state/StateModuleTest/test_onchanges_requisite_multiple/)
[integration.modules.test_state.StateModuleTest.test_requisites_onchanges_any](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/integration.modules.test_state/StateModuleTest/test_requisites_onchanges_any/)
[integration.modules.test_state.StateModuleTest.test_state_sls_id_test_state_test_post_run](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/integration.modules.test_state/StateModuleTest/test_state_sls_id_test_state_test_post_run/)

**Comment by waynew** [comment]
develop failed [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/integration.modules.test_state/StateModuleTest/test_onchanges_requisite_multiple)
---

'bool' object is not subscriptable

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\modules\test_state.py", line 1611, in test_onchanges_requisite_multiple
    test_data = state_run['cmd_|-test_two_changing_states_|-echo "Success!"_|-run']['comment']
TypeError: 'bool' object is not subscriptable
		
```
