### ISSUE TITLE
Build 66: unit.serializers.test_serializers

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#46371]
[unit.serializers.test_serializers.TestSerializers.test_serialize_yaml](https://jenkins.saltstack.com/job/2018.3/job/oxygen-salt-windows-py2/66/testReport/junit/unit.serializers.test_serializers/TestSerializers/test_serialize_yaml/)

**Comment by waynew** [comment]
Link is dead - https://github.com/saltstack/salt/issues/52927 has more info
