### ISSUE TITLE
Is salt-minion could be tar as  a stand-alone executables.

### ISSUE THREAD

**Issue by hxnan** [saltstack/salt#46390]
### Question
#
### Is salt-minion could be tar as  a stand-alone executables?
Our team need to deploy the salt-minion to a lot of host(Mayb be 10000 ), include centos5 6 7, suse 11 12. And you know all the host can not reach the internet directly because of safety , we need the local mirror.
But I found something in `bootstrap-salt.sh` like:
>  -R  Specify a custom repository URL. Assumes the custom repository URL
        points to a repository that mirrors Salt packages located at
        repo.saltstack.com. The option passed with -R replaces the
        "repo.saltstack.com". If -R is passed, -r is also set. Currently only
        works on CentOS/RHEL and Debian based distributions.
What can i do  in suse ....

Any idea like tar the salt-minion as a executables by using pyinstaller or other way would be helpful. :smiley: 
Thanks.

**Comment by Ch3LL** [comment]
you can just mirror our repo.saltstack.com repo using instructions here: https://repo.saltstack.com/#mirror and just install from there.

You can also use the tar file supplied with the pypi package if you would rather take that approach. If you need to use the bootstrap script then suse logic would need to be added to the bootstrap script to support this option.
