### ISSUE TITLE
Several instances of http_json in ext_pillar

### ISSUE THREAD

**Issue by mallniya** [saltstack/salt#46397]
### Description of Issue/Question
For git or consul exp_pillar there is possibility to use more than one source, for example:
```
ext_pillar:
  - git: master file:///srv/pillar1
  - git: master file:///srv/pillar2
```
It will be good feature to have for http_json, like:
```
ext_pillar:
  - http_json: http://example1.com/api/<nodename>
  - http_json: http://example2.com/api/<nodename>
```
(however implementation of `with_grains: True` is not so obvious within this scheme, so it's debatable)
As I didn't find this in https://docs.saltstack.com/en/develop/ref/pillar/all/salt.pillar.http_json.html please consider this either feature request or request to extend the documentation, if such feature is already there.

**Comment by garethgreenaway** [comment]
@mallniya Thanks for the report.  This would be a useful feature to have.  Approving for a future feature addition.
