### ISSUE TITLE
salt cmd.run module start tomcat failed

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#46412]
### Description of Issue/Question
I want to use salt cmd.run module to start my tomcat,but it failed,has no log.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
executecmd.sls
```
{% set cmd = pillar.get('cmd') %}
{% set sysuser = pillar.get('sysuser') %}

cmd-run:
  cmd.run:
    - name: {{cmd}}
    - runas: {{sysuser}}

[root@saltstackprd2 salt]# salt '172.20.7.222' state.sls deploy/executecmd pillar="{'cmd':'/opt/apache-         tomcat-8.0.44/bin/startup.sh','sysuser':'tomcat'}"
    172.20.7.222:
     ----------
          ID: cmd-run
    Function: cmd.run
        Name: /opt/apache-tomcat-8.0.44/bin/startup.sh
      Result: True
     Comment: Command "/opt/apache-tomcat-8.0.44/bin/startup.sh" run
     Started: 16:50:52.016360
    Duration: 62.21 ms
     Changes:   
              ----------
              pid:
                  1154
              retcode:
                  0
              stderr:
              stdout:
                  Using CATALINA_BASE:   /opt/apache-tomcat-8.0.44
                  Using CATALINA_HOME:   /opt/apache-tomcat-8.0.44
                  Using CATALINA_TMPDIR: /opt/apache-tomcat-8.0.44/temp
                  Using JRE_HOME:        /usr/java/jdk1.8.0_101
                  Using CLASSPATH:       /opt/apache-tomcat-8.0.44/bin/bootstrap.jar:/opt/apache-tomcat-8.0.44/bin/tomcat-juli.jar
                  Tomcat started.

    Summary for 172.20.7.222
    ------------
     Succeeded: 1 (changed=1)
     Failed:    0
    ------------
    Total states run:     1
    Total run time:  62.210 ms

172.20.7.222 result below,tomcat was not started:
[root@FUYINPRO logs]# !ps
ps -ef|grep java
root      1189   377  0 16:51 pts/0    00:00:00 grep java
```
When i execute start command on the 172.20.7.222,it success
```
root@FUYINPRO logs]# su  - tomcat
[tomcat@FUYINPRO ~]$ /opt/apache-tomcat-8.0.44/bin/startup.sh
Using CATALINA_BASE:   /opt/apache-tomcat-8.0.44
Using CATALINA_HOME:   /opt/apache-tomcat-8.0.44
Using CATALINA_TMPDIR: /opt/apache-tomcat-8.0.44/temp
Using JRE_HOME:        /usr/java/jdk1.8.0_101
Using CLASSPATH:       /opt/apache-tomcat-8.0.44/bin/bootstrap.jar:/opt/apache-tomcat-8.0.44/bin/tomcat-juli.jar
Tomcat started.

[tomcat@FUYINPRO ~]$ !ps
ps -ef|grep tomcat|grep -v grep
root      1191   377  0 16:53 pts/0    00:00:00 su - tomcat
tomcat    1192  1191  0 16:53 pts/0    00:00:00 -bash
tomcat    1228     1 99 16:53 pts/0    00:00:03 /usr/java/jdk1.8.0_101/bin/java -Djava.util.logging.config.file=/opt/apache-tomcat-8.0.44/conf/logging.properties -Djava.util.logging.manager=o
rg.apache.juli.ClassLoaderLogManager -Djdk.tls.ephemeralDHKeySize=2048 -Djava.protocol.handler.pkgs=org.apache.catalina.webresources -Djava.endorsed.dirs=/opt/apache-tomcat-8.0.44/endorsed -classpath /opt/apache-tomcat-8.0.44/bin/bootstrap.jar:/opt/apache-tomcat-8.0.44/bin/tomcat-juli.jar -Dcatalina.base=/opt/apache-tomcat-8.0.44 -Dcatalina.home=/opt/apache-tomcat-8.0.44 -Djava.io.tmpdir=/opt/apache-tomcat-8.0.44/temp org.apache.catalina.startup.Bootstrap start
```
what should i do Thanks.
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by garethgreenaway** [comment]
@liuhetongzi Thanks for the report.  It sounds like maybe the command you're running via Salt is attempting to run in the foreground and once the Salt run finishes the process is killed.

Can you try updating your state to this:
```
{% set cmd = pillar.get('cmd') %}
{% set sysuser = pillar.get('sysuser') %}

cmd-run:
  cmd.run:
    - name: {{cmd}}
    - runas: {{sysuser}}
    - bg: True
```

**Comment by liuhetongzi** [comment]
@garethgreenaway I find the reason,but I don not kown how to resolve it.
my salt start use non root user,
![default](https://user-images.githubusercontent.com/23496061/37190579-96731700-2395-11e8-8302-d53c9872add9.png)
it causes the  ValueError: No JSON object could be decoded
when i comment the user salt,it can receive the result PID
![default](https://user-images.githubusercontent.com/23496061/37190608-c8f1175e-2395-11e8-8bb3-2ec0d613e923.png)

![default](https://user-images.githubusercontent.com/23496061/37190614-cea37dd6-2395-11e8-95b8-48a56fbdce64.png)

I do not want to comment the user salt,what should I do?
