### ISSUE TITLE
restart salt-master remotely via salt-api

### ISSUE THREAD

**Issue by Naitreey** [saltstack/salt#46436]
### Description of Issue/Question
Is it possible to restart salt-master service remotely via salt-api? According to my test,
Doing this will hangs the SSL connection.

#### restart locally
Salt now supports restart salt-master service locally from master node, provided a minion
is installed on master itself. Like so:

```sh
naitree@master:~$ sudo salt <master-id> service.restart salt-master
<master-id>:
    True
```

#### restart remotely
I'm using salt-api + cherrypy on master node to provide remote access. On remote
node, I use pepper module, trying to do the same operation as above.

```python
>>> api = Pepper('https://<master-ip>:<cherry-port>')
>>> api.login('<user>', '<pass>', 'pam')
>>> api.local('<master-id>', 'service.restart', kwarg=dict(name='salt-master')) # hangs
```

The last step above hangs the thread.

#### workaround

To partially work around the hanging issue, I can execute operation asynchronously,
then lookup job result at later time.

```python
>>> jid = api.local_async('<master-id>', 'service.restart', kwarg=dict(name='salt-master'))['return'][0]['jid']
>>> time.sleep(5)
>>> api.lookup_jid(jid)
{'return': [{'<master-id>': True}]}
```

But clearly this is unreliable, as how long to wait is not known before hand.

### Versions Report
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 23 2017, 22:06:14)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.10 artful
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-36-generic
         system: Linux
        version: Ubuntu 17.10 artful
```

**Comment by Naitreey** [comment]
A slightly more sensible workaround would be to replace `time.sleep()` by 
`socket.setdefaulttimeout()`. Then we can at least check for timeout in a loop.

**Comment by gtmanfred** [comment]
The problem I think you are running into is that `salt-api` requires the master to be running.

I can't think of any way to make this work, that doesn't end with the tornado io_loop dieing.

What you could do is just keep looking up the jid until something has returned.

@whiteinge Can you think of another way to accomplish this?

Thanks,
Daniel

**Comment by whiteinge** [comment]
Salt things restarting Salt things is just not something we're set up to do. The only exception to that is the Master restarting a Minion and even that is not 100%.

For this use-case one complication is that the salt-api process is started and managed by the salt-master process. But even if that process were disowned or started by something else (like Apache), we'd have the additional problem of if the Master config were changed prior to the restart then salt-api would not get those changes which could lead to other weird problems.

I see the use-case and I wish we could do this but I think it's fundamentally out of reach until we can start reworking internals to handle SIGHUP (#570) and dynamically reload `__opts__` everywhere.
