### ISSUE TITLE
Minions doesn't return [No response] but not always

### ISSUE THREAD

**Issue by kaluznyt** [saltstack/salt#46508]
### Description of Issue/Question
I have a lab environment of windows machines managed by salt. However, have an issue, not sure if it's related to salt directly or to some network configuration issue, but perhaps you may give me some hint's as I'm stuck myself.  

Basically the issue is that minions doesn't return (even on simple test.ping):
![image](https://user-images.githubusercontent.com/572605/37340111-e5abb058-26b4-11e8-9a5b-4503ea4fe6b5.png)

But return while for example I ping salt master from a minion:

So, when I run a:
ping salt

Reply from 10.0.0.100: bytes=32 time<1ms TTL=63
Reply from 10.0.0.100: bytes=32 time<1ms TTL=64
Reply from 10.0.0.100: bytes=32 time<1ms TTL=64
Reply from 10.0.0.100: bytes=32 time<1ms TTL=64

Salt can see a response from this one, so like a ping was unlocking the connectivity, which for me is weird:
![image](https://user-images.githubusercontent.com/572605/37340178-2a974dbc-26b5-11e8-90b1-44b3e05fd1f5.png)

And this is quite consistent. 

Network configuration is that the managed machines are on a 10.0.0.0/24 network including salt master being on 10.0.0.100 (and bound to this address in config, but it initially wasn't bound and had the same issue). 

Salt master have also another (public) / office lan interface, with internet access so it can run updates, retrieve repos etc. 

On minions in debug mode I can see this while it happen:
![image](https://user-images.githubusercontent.com/572605/37340426-fc612dcc-26b5-11e8-86e2-dc67a7162b14.png)

But after I start to ping salt - master from the same machine constantly it 'unlocks':
![image](https://user-images.githubusercontent.com/572605/37340457-1c92a012-26b6-11e8-93e2-0a389698f0e9.png)

Do you have any ideas why this might be happening ?

Bad routing on salt-master ? I'm not a network expert, so cannot really validate that throughly. 

### Versions Report

![image](https://user-images.githubusercontent.com/572605/37340288-85dd4172-26b5-11e8-8d09-079a477fcd37.png)

**Comment by gtmanfred** [comment]
If all your minions are windows, I would recommend increasing the timeout to 30 seconds for your salt commands.

Windows minions are significantly slower than linux minions.  Because windows does not have anything like `os.fork` in linux, which forks all of the process memory and loads a new one, we have to make a fake forking process. What windows does is `pickle` the memory and then start a new process that loads that pickle back into memory, but you can't pickle loaded functions, for example all the execution and state modules, so there is some extra time that is spent loading those modules on windows.

If you set a timeout of 30 in the /etc/salt/master or run `sudo salt '*' -t 30 test.ping` do all the minions return?

Thanks,
Daniel

**Comment by kaluznyt** [comment]
Thanks for reply. No that didn't help, I tried a couple of times and the result is:
![image](https://user-images.githubusercontent.com/572605/37395191-97102316-276d-11e8-925a-43455086c593.png)

But only, after I run a network ping from salt to the minions:
![image](https://user-images.githubusercontent.com/572605/37395226-a82fbfee-276d-11e8-93cb-19bb721ad9ff.png)

I can see results almost immediately:
![image](https://user-images.githubusercontent.com/572605/37395246-b2593400-276d-11e8-9af6-abbb49d9dfef.png)

Not sure on what level the issue is. But I can I think say it's not because of timeout, as when there is a 'connectivity' so after I run some random pings between these machines the result from test.ping can be almost immediate, but then it's like these 'lose' connectivity.

**Comment by kaluznyt** [comment]
I think the issue is solved, I had invalid route on master.

Now everything is working nicely!

![image](https://user-images.githubusercontent.com/572605/37395631-98cb91d0-276e-11e8-893c-59819743598a.png)

**Comment by gtmanfred** [comment]
Perfect!

Thanks for following up,
Daniel
