### ISSUE TITLE
exclude multiple directories with rsync not work?

### ISSUE THREAD

**Issue by jils2013** [saltstack/salt#46505]
### Description of Issue/Question
rsync can user {} to exclude multiple directories:
```
[root@myhost tmp]# find test* -type f 
testdst/2/3
testdst/2/exclude
testdst/1/exclude
testdst/1/5
testdst/3/todelete
testdst/4/todelete
testsrc/2/3
testsrc/1/5
[root@myhost  tmp]# rsync -avz --delete --exclude={1/exclude,2/exclude} /tmp/testsrc/ /tmp/testdst/
sending incremental file list
1/
2/
3/
deleting 3/todelete
4/
deleting 4/todelete

sent 126 bytes  received 28 bytes  308.00 bytes/sec
total size is 0  speedup is 0.00 
``` 

but with rsync.rsync not worked
```
[root@master step]# salt 'myhost' cmd.run 'find /tmp/test* -type f'
myhost:
    /tmp/testdst/2/3
    /tmp/testdst/2/exclude
    /tmp/testdst/1/exclude
    /tmp/testdst/1/5
    /tmp/testdst/3/todelete
    /tmp/testdst/4/todelete
    /tmp/testsrc/2/3
    /tmp/testsrc/1/5
[root@master ~]# salt 'myhost' rsync.rsync /tmp/testsrc/ /tmp/testdst/ delete=True exclude={1/exclude,2/exclude}
myhost:
    ----------
    pid:
        9904
    retcode:
        0
    stderr:
    stdout:
        sending incremental file list
        1/
        deleting 1/exclude --this should be passed 
        3/
        deleting 3/todelete
        4/
        deleting 4/todelete
        
        sent 123 bytes  received 25 bytes  296.00 bytes/sec
        total size is 0  speedup is 0.00
```
### Steps to Reproduce Issue
2018-03-13 15:32:59,114 [salt.minion                                          ][INFO    ][9903] Starting a new job with PID 9903
2018-03-13 15:32:59,118 [salt.utils.lazy                                      ][DEBUG   ][9903] LazyLoaded rsync.rsync
2018-03-13 15:32:59,121 [salt.utils.lazy                                      ][DEBUG   ][9903] LazyLoaded direct_call.get
2018-03-13 15:32:59,121 [salt.loader.*.int.module.rsync           ][DEBUG   ][9903] Running rsync command: ['rsync', '-avz', '--delete', '--exclude', '2/exclude', '/tmp/testsrc/', '/tmp/testdst/']
2018-03-13 15:32:59,123 [salt.utils.lazy                                      ][DEBUG   ][9903] LazyLoaded cmd.run_all
2018-03-13 15:32:59,123 [salt.loader.*.int.module.cmdmod          ][INFO    ][9903] Executing command ['rsync', '-avz', '--delete', '--exclude', '2/exclude', '/tmp/testsrc/', '/tmp/testdst/'] in directory '/root'
2018-03-13 15:32:59,188 [salt.loader.*.int.module.cmdmod          ][DEBUG   ][9903] stdout: sending incremental file list
1/
deleting 1/exclude
3/
deleting 3/todelete
4/
deleting 4/todelete

sent 123 bytes  received 25 bytes  296.00 bytes/sec
total size is 0  speedup is 0.00
2018-03-13 15:32:59,189 [salt.minion                                          ][DEBUG   ][9903] Minion return retry timer set to 7 seconds (randomized)
2018-03-13 15:32:59,190 [salt.minion                                          ][INFO    ][9903] Returning information for job: 20180313153259054900

### Versions Report
Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.6.3.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago

**Comment by gtmanfred** [comment]
exclude only allows for strings to be passed, so if you want it to work right now, you should pass

```
alt 'myhost' rsync.rsync /tmp/testsrc/ /tmp/testdst/ delete=True exclude='1/exclude --exclude 2/exclude'
```

I have added the feature of being able to pass a list of files, and it will be in the next major release of salt, Fluorine

#46515

**Comment by jils2013** [comment]
still not work
```
[root@master  ~]# salt 'myhost' rsync.rsync /tmp/testsrc/ /tmp/testdst/ delete=True exclude='1/exclude --exclude=2/exclude'
nkgts625f101-mwc:
    ----------
    pid:
        1497
    retcode:
        0
    stderr:
    stdout:
        sending incremental file list
        1/
        deleting 1/exclude
        2/
        deleting 2/exclude
        3/
        deleting 3/todelete
        4/
        deleting 4/todelete
        
        sent 126 bytes  received 28 bytes  308.00 bytes/sec
        total size is 0  speedup is 0.00
[root@master ~]# salt 'myhost' rsync.rsync /tmp/testsrc/ /tmp/testdst/ delete=True exclude='1/exclude --exclude 2/exclude'
nkgts625f101-mwc:
    ----------
    pid:
        1515
    retcode:
        0
    stderr:
    stdout:
        sending incremental file list
        1/
        deleting 1/exclude
        2/
        deleting 2/exclude
        3/
        deleting 3/todelete
        4/
        deleting 4/todelete
        
        sent 126 bytes  received 28 bytes  308.00 bytes/sec
        total size is 0  speedup is 0.00
```
