### ISSUE TITLE
Documentation for require_any is impossible.

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#46514]
### Description of Issue/Question

The following paragraph of documentation from the Oxygen Release Notes (and, we presume the actual docs for the feature) present a logically impossible situation: ...

> The use of require_any demands that one of the required states executes before the dependent state. The state containing the require_any requisite is defined as the dependent state. The states specified in the require_any statement are defined as the required states. If at least one of the required state's execution succeeds, the dependent state will then execute. If at least one of the required state's execution fails, the dependent state will not execute.

### Steps to Reproduce Issue

Assume that State X has require_any of state A and state B.

State A succeeds, and state B fails.

So "If at least one of the required state's execution succeeds, the dependent state will then execute" means that state X will execute, since A succeeded.

But "If at least one of the required state's execution fails, the dependent state will not execute" and state B failed, so state X cannot execute.

State X cannot both execute and not execute, so the situation is impossible.

### Versions Report
[Oxygen RC1](https://docs.saltstack.com/en/develop/topics/releases/2018.3.0.html#new-requisites-available-in-state-compiler)

**Comment by gtmanfred** [comment]
@garethgreenaway can you clarify this?

Thanks,
Daniel

**Comment by garethgreenaway** [comment]
This was definitely wrong.  The documentation has been cleared up in that PR.

**Comment by vernondcole** [comment]
Fix verified.
