### ISSUE TITLE
[FEATURE] Boto3 SSM Parameter Store module

### ISSUE THREAD

**Issue by blade2005** [saltstack/salt#46510]
I'd love to see support of [SSM](https://boto3.readthedocs.io/en/latest/reference/services/ssm.html) as a module and as a SDB driver.

Specifically the Parameter Store: [get_parameter](https://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.get_parameter) and [put_parameter](https://boto3.readthedocs.io/en/latest/reference/services/ssm.html#SSM.Client.put_parameter).

Presently I'm looking at Vault to use for SDB but I'd end up creating a lot of duplicated keys in both locations.

**Comment by gtmanfred** [comment]
That would be great, I would love to see a Pull Request implementing that.

Thanks for the request,
Daniel

**Comment by blade2005** [comment]
@gtmanfred I was thinking of following the same premise that the Vault stuff did and have a SSM module(modules/boto_ssm.py) and then have another module under sdb(sdb/ssm.py) which uses the other one. Does this sound like an appropriate idea?

**Comment by gtmanfred** [comment]
yeah, that sounds perfect!
Daniel

**Comment by rv-ptighe** [comment]
@blade2005 Is there a repo you're working from for this feature?  We also would like to see this in Salt, and would like to help contribute to getting this into the product.

**Comment by blade2005** [comment]
@rv-ptighe I've not had a chance to put too much effort into this feature.  I did start work on it in a branch. https://github.com/blade2005/salt/tree/feature/aws-ssm

**Comment by mchugh19** [comment]
Hey @blade2005. What's the status of your ssm module? We could use this functionality as well. Is it in a usable state?

**Comment by blade2005** [comment]
Hey @mchugh19 I've not and I do feel bad for not putting more than an initial effort. I'm not working a lot with salt right now. If you fork my branch feel free to PR against me or saltstack's repo. 

I don't want to keep hope up that I will finish this because I just don't have the cycles to spare.

**Comment by mchugh19** [comment]
With the merge, I think this can be closed.

**Comment by DenisBY** [comment]
In what salt version it's going to be released?

**Comment by mchugh19** [comment]
@DenisBY good news! was released in Neon! 
https://docs.saltstack.com/en/develop/topics/releases/neon.html#module-changes

https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.boto_ssm.html

**Comment by DenisBY** [comment]
Could you give me a hint how I can use SSM parameters store as replacement of grains?
I mean get values from SSM instead of getting them from grains.
Thanks

**Comment by mchugh19** [comment]
@DenisBY since grains are info on the minion, the parameter store wouldn't replace that data. But it could provide values similar to how pillar works.

I don't have an AWS environment ready to validate, but you should be able to write a state file like:
```
{% set supersecret = salt['boto_ssm'].get_parameter('test-param') %}
{# or if parameter is encrypted #}
{% set supersecret = salt['boto_ssm'].get_parameter('test-param withdecryption=True') %}
{# you can then use this value in your jinja #}

test of value:
    test.nop:
    - name: {{ supersecret }}
```
 This was mostly intended as a datastore for secret data. While you could host parameters with lots of data, or query many parameters, I've not personally tested it, so I'm not sure how it performs.

**Comment by DenisBY** [comment]
@mchugh19 sorry, I messed grains with pillars. Thank you for example!

**Comment by DenisBY** [comment]
It seems it's not possible to use it in pillars, right? If I use it, I'm getting string 'False' instead of value from ssm.
