### ISSUE TITLE
`--name` argument not honored for cloud test suite

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#46521]
### Description of Issue/Question

The runtests.py script does not honor the `--name` argument for the 'cloud' test suite and a few other suites which are not a part of the default integration tests.

### Versions Report

2018.3

**Comment by rallytime** [comment]
@gtmanfred Yeah, that is a bug. Just never came back around to fixing it. I don't know of another issue for this though.

**Comment by gtmanfred** [comment]
cool, thanks, then I will leave this one!

Daniel

**Comment by rallytime** [comment]
Fixed via #46567
