### ISSUE TITLE
salt-cloud gives "FutureWarning: The behavior of this method will change in future versions."

### ISSUE THREAD

**Issue by HenriWahl** [saltstack/salt#46538]
### Description of Issue/Question
Every call of a salt-cloud like "-d" or "-p" give the error message:
[WARNING ] /usr/lib/python2.7/site-packages/salt/cloud/clouds/opennebula.py:4574: FutureWarning: The behavior of this method will change in future versions. Use specific 'len(elem)' or 'elem is not None' test instead.
  if vm.find('TEMPLATE').find('TEMPLATE_ID'):

### Setup
Saltstack with OpenNebula Cloud

### Steps to Reproduce Issue
call  salt-cloud commands like "-d" or "-p"

### Versions Report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Ch3LL** [comment]
looks like this was added here: bd2490b1498

ping @gtmanfred any ideas here?

**Comment by HenriWahl** [comment]
Yes, this came in new with 2017.7.2 - at least I did not see this before.

**Comment by gtmanfred** [comment]
Yeah, it just needs to be changed to their recommendation.

**Comment by gtmanfred** [comment]
This should fix the problem #47067
