### ISSUE TITLE
Use the python client api to execute the state.sls file, and the results do not recognize the saltenv parameter

### ISSUE THREAD

**Issue by solitarywares** [saltstack/salt#46536]
### Description of Issue/Question
I want to use the python client api interface of saltstack to execute the state.sls module. The result is an exception and the saltv parameter is specified. The result does not have any effect. It will only be found in the base environment directory. I am very confused and hopefully my calling format is not Wrong, But there is no problem with using the salt CLI to execute the test sls file, thanks.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
**import salt.client 
local = salt.client.LocalClient()  
local.cmd(minion_id, 'state.sls', ['test'], saltenv='Onlineen')** 

Result：
       **{'minion_id': ["No matching sls found for 'test' in env 'base'"]}**

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
（1）"test" sls file path
         /etc/salt/Onlineen/states/test/init.sls
（2）file_roots path configure
        file_roots:
            base:
                  - /etc/salt/Onlineen/states
（3）"test" file content
        vim  test/init.sls     
        test:
           cmd.run:
              - name: echo "1" >/tmp/a

**#salt CLI excute result**
 salt 'minion' state.sls test saltenv=Onlineen test=True
minion:
----------
          ID: test
    Function: cmd.run
        Name: echo "1" >/tmp/a
      Result: None
     Comment: Command "echo "1" >/tmp/a" would have been executed
     Started: 17:02:38.952399
    Duration: 0.355 ms
     Changes:   

Summary for minion
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   0.355 ms

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2016.11.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.2.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3c1
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 6.5 Final
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: CentOS 6.5 Final

**Comment by Ch3LL** [comment]
In your file roots you show:

```
file_roots:
base:
- /etc/salt/Onlineen/states
```

but you are specifying `saltenv='Onlineen'`. You will need to either specify the onlineen environment or use `saltenv=base` or remove saltenv as base is the default environment. Im pretty confused as to why its working outside of this script.

**Comment by solitarywares** [comment]
@Ch3LL   Really sorry, don't paste wrong information,The correct configuration information is：

file_roots:
Onlineen:
- /etc/salt/Onlineen/states

**Comment by solitarywares** [comment]
@Ch3LL   I've googled a lot of information about the saltstack api, and I didn't see an example of specifying the saltenv parameter. Can you provide a good example of calling state.sls and specifying the saltenv parameter? Thank you very much.

**Comment by solitarywares** [comment]
I have already responded to your detailed information in github, some of
the information provided in the previous question was pasted incorrectly.

2018-03-14 22:08 GMT+08:00 Megan Wilhite <notifications@github.com>:

**Comment by Ch3LL** [comment]
you need to pass it as a kwarg like so: `local.cmd('*', 'state.sls', ['test'], kwarg={'saltenv': 'onlineen'})`

**Comment by solitarywares** [comment]
☺Thank you very much for your enthusiasm. I have solved my problems, but I
still feel sorry for the lack of examples in the official API
documentation. I hope to contribute some energy to the community in my
future work practices.

2018-03-15 21:49 GMT+08:00 Megan Wilhite <notifications@github.com>:

**Comment by Ch3LL** [comment]
Yeah if you want to make your first contribution a doc PR would be greatly appreciated. I can help walk you through how to do that if you want?

**Comment by solitarywares** [comment]
@Ch3LL  I come from China. The English level is very bad. It makes me very annoyed. So the presentation of documents will be weaker. I think I can improve this part of the configuration example in future practice. If you can get your advice, it will be victorious. grateful.

**Comment by Ch3LL** [comment]
We have some documentation on contributing to salt: https://docs.saltstack.com/en/latest/topics/development/contributing.html

But if you want to update the documentation for the cherrypy docs you would just send a PR in for this file: salt/netapi/rest_cherrypy/app.py where the documentation strings are. Thanks!
