### ISSUE TITLE
parallel:True not work on salt.states.archive 

### ISSUE THREAD

**Issue by jils2013** [saltstack/salt#46535]
### Description of Issue/Question
in my states,minion need get some tar/zip files from a http file server;
i use salt.states.archive to extracted them like belows:
```
#!py
...
ret[_ids['extracted']]={'archive.extracted':[{'source':_source,'name':_tmpath,'source_hash':_sourcehash,'parallel':True}]}
....
```
get exception:
```
2018-03-14 14:52:00,224 [salt.state                                                     ][ERROR   ][20689] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/salt/state.py", line 1746, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.6/site-packages/salt/loader.py", line 1703, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.6/site-packages/salt/states/archive.py", line 1177, in extracted
    **kwargs)
TypeError: unzip() got an unexpected keyword argument 'parallel'

```
remove 'parallel':True will work well,but a little slower one by  one;
### Versions Report
Salt Version:
Salt: 2017.7.2

Dependency Versions:
cffi: Not Installed
cherrypy: unknown
dateutil: Not Installed
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.8.1
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.6
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1

pycryptodome: Not Installed
pygit2: Not Installed
Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
python-gnupg: Not Installed
PyYAML: 3.11
PyZMQ: 14.5.0
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.0.5

System Versions:
dist: redhat 6.9 Santiago
locale: UTF-8
machine: x86_64
release: 2.6.32-696.6.3.el6.x86_64
system: Linux
version: Red Hat Enterprise Linux Server 6.9 Santiago

**Comment by Ch3LL** [comment]
I'm getting a different error on 2017.7.2 when running this state for the first time:

```
foo_app:
  archive.extracted:
    - name: /tmp/test
    - source: http://repo.saltstack.com/apt/debian/8/amd64/latest/msgpack-python_0.4.2-1.debian.tar.xz
    - skip_verify: True
    - parallel: True
```

```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/testing/salt/utils/process.py", line 663, in _run
    return self._original_run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/testing/salt/state.py", line 1706, in _call_parallel_target
    with salt.utils.fopen(tfile, 'wb+') as fp_:
  File "/testing/salt/utils/__init__.py", line 1357, in fopen
    fhandle = open(*args, **kwargs)  # pylint: disable=resource-leakage
IOError: [Errno 2] No such file or directory: '/var/cache/salt/minion/20180314135219308976/archive_|-foo_app_|-/tmp/test_|-extracted'
[DEBUG   ] File /var/cache/salt/minion/accumulator/41337488 does not exist, no need to cleanup.
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: foo_app
    Function: archive.extracted
        Name: /tmp/test
      Result: False
     Comment: Parallel cache failure
     Started: 13:52:19.513506
    Duration: 6.916 ms
     Changes:   
```

And when i use 2017.7.4 it works just fine. Can you try 7.4?

**Comment by jils2013** [comment]
sorry to blocked the issue;
the problem is occered on on minion(rhel5.11)with version 2016.11.3;
any new version plan for rhel/centos 5?

**Comment by jils2013** [comment]
@Ch3LL ,thx for your help;
