### ISSUE TITLE
network.default_route on kernel Linux doesn't return inet6 routes

### ISSUE THREAD

**Issue by lvg01** [saltstack/salt#46555]
### Description of Issue/Question
`salt <minionid> network.default_route family=inet6` doesn't  return routes on CentOS

### Versions Report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by garethgreenaway** [comment]
@lvg01 Thanks for the report and we would definitely welcome a PR with this fix.

**Comment by lvg01** [comment]
I Followed the procedure as described in https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request several times but I keep failing at the last part (push) with error:

$ git push upstream fix-46555
ERROR: Permission to saltstack/salt.git denied to lvg01.
fatal: Could not read from remote repository.
