### ISSUE TITLE
State.Sls File throwing an Ambiguous Error

### ISSUE THREAD

**Issue by swapnilpotnis** [saltstack/salt#46560]
### Description of Issue/Question
I am trying to run an AWS command making use of "cmd.run" feature. The values are getting populated as expected. The query created after all the values get populated also works fine on command line but getting errors when the same query is not being able to run via cmd.run

### Setup
Following is the lambda.sls file that I am using

```
lambda_create:
  cmd.run:
   - name: aws lambda create-function --function-name xxx --runtime xxx--handler xxx--role xxx --code "S3Bucket"="xxx","S3Key"="xxx" --environment '{"Variables":{"name": "test", "surname": "user"}}'
```
### Steps to Reproduce Issue
Simply create the above SLS file and run
state-call state.sls lambda.sls

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
 Salt: 2016.11.9

**Comment by garethgreenaway** [comment]
@swapnilpotnis Thanks for the report.  Can you provide any errors or output you receive when you attempt to run the state file above?

**Comment by swapnilpotnis** [comment]
@garethgreenaway : ERROR: mapping values not allowed in the state.
The issue seems to be with the 
**--environment '{"Variables":{"name": "test", "surname": "user"}}'** as removing them from the command makes it run just fine.
