### ISSUE TITLE
Lazy Load for mssql doesn't appear to be working.

### ISSUE THREAD

**Issue by blade2005** [saltstack/salt#46564]
### Description of Issue/Question
Executing mssql.version in a formula appears to not work. If I execute from the command line with salt-call --local mssql.version and pass in the arguments it works fine.

### Setup
```
# cat backup.sls 
blah_version:
  mssql.version:
    - server: '<redacted>'
    - port:   1433
    - user:   'admin'
    - password:   '<redacted>'
    - database: '<redacted>'
```

### Steps to Reproduce Issue
I have my master also being a minion and set up with the pillar. Here is what I used to execute the command: `salt-call --local state.apply backup`
Output:
```
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.module.boto_elbv2. Module will not be loaded: 'boto3.assign_funcs'
[WARNING ] salt.loaded.int.module.boto_kinesis.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto_kinesis', please fix this.
[ERROR   ] State 'mssql.version' was not found in SLS 'backup'
Reason: 'mssql.version' is not available.

local:
----------
          ID: blah_version
    Function: mssql.version
      Result: False
     Comment: State 'mssql.version' was not found in SLS 'backup'
              Reason: 'mssql.version' is not available.
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 31 2018, 00:17:36)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.9.81-35.56.amzn1.x86_64
         system: Linux
        version: Not Installed

```
# pip-2.7 --version
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
```

```
# pip-2.7 list | grep mssql
pymssql (2.1.3)
```

```
# md5sum /usr/lib/python2.7/dist-packages/salt/modules/mssql.py
762e4ec54aff7a7062829b217bbb1d13  /usr/lib/python2.7/dist-packages/salt/modules/mssql.py
```

**Comment by gtmanfred** [comment]
Can you run `python -c 'import pymssql; print(pymssql.__file__)'?

Also, how did you install that module?

Thanks,
Daniel

**Comment by blade2005** [comment]
I assume you mean `__file__`
```
# python -c 'import pymssql; print(pymssql.__file__)'
/usr/lib64/python2.7/dist-packages/pymssql.so
```

**Comment by gtmanfred** [comment]
Yeah, that is what I meant, but github converts double underscores to bold, if you don't wrap them in backtics.

Hrm, ok I will try and replicate this.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Which distro are you getting this from?

Because I cannot find that module in the Amazon Linux 1 repos.

```
[root@ip-10-0-0-36 ~]# yum search mssql
Loaded plugins: priorities, update-motd, upgrade-helper
============================================================================================================================================================================ N/S matched: mssql ============================================================================================================================================================================
php-mssql.x86_64 : MSSQL database module for PHP
php54-mssql.x86_64 : MSSQL database module for PHP
php55-mssql.x86_64 : MSSQL database module for PHP
php56-mssql.x86_64 : MSSQL database module for PHP
php-ZendFramework-Db-Adapter-Pdo-Mssql.noarch : Zend Framework database adapter for MS SQL PDO

  Name and summary matches only, use "search all" for everything.
```

**Comment by blade2005** [comment]
hrm. maybe I didn't install via system and just used pip. I know that I had to uninstall salt from python2.6 because aws linux 1 didn't have pymssql. 

Default python is 2.6.  I had to uninstall salt from py2.6 and install salt under python2.7.

I did add a line to /usr/lib/python2.7/dist-packages/salt/modules/mssql.py 

```
with open('/root/blah', 'w') as outfile:
    import sys
    outfile.write('\n'.join(sys.path))
    outfile.write(sys.version)
```

Which yields the following information.
```
/usr/bin
/usr/lib/python27.zip
/usr/lib64/python2.7
/usr/lib64/python2.7/plat-linux2
/usr/lib64/python2.7/lib-tk
/usr/lib64/python2.7/lib-old
/usr/lib64/python2.7/lib-dynload
/usr/local/lib64/python2.7/site-packages
/usr/local/lib/python2.7/site-packages
/usr/lib64/python2.7/site-packages
/usr/lib/python2.7/site-packages
/usr/lib64/python2.7/dist-packages
/usr/lib64/python2.7/dist-packages/PIL
/usr/lib/python2.7/dist-packages
/usr/lib/python2.7/dist-packages/salt/modules
2.7.13 (default, Jan 31 2018, 00:17:36) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)]
```

Which clearly shows /usr/lib64/python2.7/dist-packages being in the path.

**Comment by gtmanfred** [comment]
Are you installing salt from the amzn1 repos that we package?

http://repo.saltstack.com/#amzn

Or via pip install?

**Comment by blade2005** [comment]
I ran the boostrap originally and the one it installed was pretty old then again it was last year when i did this install so it's possibly related to that. At present salt is installed via pip on python2.7

**Comment by blade2005** [comment]
Should I uninstall salt and install from http://repo.saltstack.com/#amzn ? I show the current version as 2017.7.4

```
# yum info salt-minion
Loaded plugins: priorities, update-motd, upgrade-helper
1100 packages excluded due to repository priority protections
Available Packages
Name        : salt-minion
Arch        : noarch
Version     : 2017.7.4
Release     : 1.el6
Size        : 37 k
Repo        : saltstack-repo/x86_64
Summary     : Client component for Salt, a parallel remote execution system
URL         : http://saltstack.org/
License     : ASL 2.0
Description : The Salt minion is the agent component of Salt. It listens for instructions
            : from the master, runs jobs, and returns results back to the master.
```

**Comment by gtmanfred** [comment]
if you installed using bootstrap, that is the current version from that repo. and it should be installed on python27, since 2017.7 does not support python 2.6

**Comment by blade2005** [comment]
So when I installed from bootstrap originally it was around march 2017. I don't think it ever got upgraded after that. I've just tried bootstrapping to the newest version and... got the following error
```
Error: Package: salt-2017.7.4-1.el6.noarch (saltstack-repo)
           Requires: python27-tornado >= 4.2.1
           Installed: python27-tornado-2.2.1-7.8.amzn1.noarch (@amzn-main)
               python27-tornado = 2.2.1-7.8.amzn1
```

```
# yum info python27-tornado.noarch
Loaded plugins: priorities, update-motd, upgrade-helper
1100 packages excluded due to repository priority protections
Installed Packages
Name        : python27-tornado
Arch        : noarch
Version     : 2.2.1
Release     : 7.8.amzn1
Size        : 1.9 M
Repo        : installed
From repo   : amzn-main
Summary     : Scalable, non-blocking web server and tools
URL         : http://www.tornadoweb.org
License     : ASL 2.0
Description : Tornado is an open source version of the scalable, non-blocking web
            : server and tools.
            : 
            : The framework is distinct from most mainstream web server frameworks
            : (and certainly most Python frameworks) because it is non-blocking and
            : reasonably fast. Because it is non-blocking and uses epoll, it can
            : handle thousands of simultaneous standing connections, which means it is
            : ideal for real-time web services.
            : 
            : This package is meant to be used with Python 2.7.

```
