### ISSUE TITLE
"No roster file found" when using --roster=scan

### ISSUE THREAD

**Issue by mnieber** [saltstack/salt#46576]
Version: based on 7b7eb740def56620d693746507bd51d65f3f69b9

When i run `salt-ssh -l debug --roster=scan --priv=~/.ssh/id_vegtech_rsa 172.17.0.2 test.ping` I get `IOError: No roster file found`

It seems salt is trying to read the roster file even though my roster is not based on a file.

**Comment by sumeetisp** [comment]
Please try the following
salt-ssh -l debug --roster scan --priv=~/.ssh/id_vegtech_rsa 172.17.0.2
test.ping
Thanks,
Sumeet Salvankar

**Comment by gtmanfred** [comment]
I am unable to replicate this error.

```
[root@salt ~]# salt-ssh --roster scan --sudo --user daniel --passwd braves123 127.0.0.1 test.ping
WARNING: CONFIG '/etc/salt' directory does not exist.
127.0.0.1:
    True
[root@salt ~]# mkdir /etc/salt
mkdir: cannot create directory ‘/etc/salt’: File exists
[root@salt ~]# ls -l /etc/salt
total 0
drwxr-xr-x. 3 root root 20 Mar 16 13:56 pki
[root@salt ~]# salt-ssh --roster scan --sudo --user daniel --passwd braves123 127.0.0.1 test.ping
127.0.0.1:
    True
```

Can you provide any more information?

Thanks,
Daniel

**Comment by mnieber** [comment]
@sumeetisp  @gtmanfred 

This is the call with "-l debug" added (note that I am leaving out my ssh-key because I am now using key forwarding, but this should make no difference for the current problem). btw I will follow up with a work around that might be useful for diagnosing what happens.

salt-ssh -l debug --roster scan 172.17.0.2 test.ping
[DEBUG   ] Missing configuration file: /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: localdev
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
IOError: No roster file found
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 420, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 24, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 236, in __init__
    self._expand_target()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 361, in _expand_target
    self._get_roster()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 339, in _get_roster
    roster_file = salt.roster.get_roster_file(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/roster/__init__.py", line 54, in get_roster_file
    raise IOError('No roster file found')
IOError: No roster file found
Traceback (most recent call last):
  File "/usr/bin/salt-ssh", line 10, in <module>
    salt_ssh()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 420, in salt_ssh
    client.run()
  File "/usr/lib/python2.7/dist-packages/salt/cli/ssh.py", line 24, in run
    ssh = salt.client.ssh.SSH(self.config)
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 236, in __init__
    self._expand_target()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 361, in _expand_target
    self._get_roster()
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 339, in _get_roster
    roster_file = salt.roster.get_roster_file(self.opts)
  File "/usr/lib/python2.7/dist-packages/salt/roster/__init__.py", line 54, in get_roster_file
    raise IOError('No roster file found')
IOError: No roster file found

**Comment by mnieber** [comment]
The workaround is to create an empty roster file (`./roster`) and call

salt-ssh -l debug --roster-file=./roster --roster scan 172.17.0.2 test.ping
[DEBUG   ] Missing configuration file: /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: localdev
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: ./roster
[DEBUG   ] Template is an empty file: ./roster
[DEBUG   ] LazyLoaded scan.targets
[DEBUG   ] Matched minions: {'172.17.0.2': {'host': '172.17.0.2', 'port': 22}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded local_cache.prep_jid
[DEBUG   ] Adding minions for job 20180316141901916175: ['172.17.0.2']
[DEBUG   ] Could not LazyLoad test.ping: 'test.ping' is not available.
[DEBUG   ] Performing shimmed, blocking command as follows:
test.ping
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 101  STDOUT_FD: 10  STDERR_FD: 12
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE 172.17.0.2: 0
[DEBUG   ] LazyLoaded nested.output
172.17.0.2:
    True

**Comment by mnieber** [comment]
Since this solves my problem, I am happy enough with the workaround.

**Comment by gtmanfred** [comment]
Ok, but can you try upgrading to 2017.7.4? I was unable to replicate that error?

If you are ok with the work around, you can close the issue.

**Comment by mnieber** [comment]
@gtmanfred My version is based on a commit from Dec 27, 2017. Could it be that in your setup, there is a roster file that can be found by salt?

**Comment by gtmanfred** [comment]
There is no roster file in my setup, as I showed above, /etc/salt/ only had
a pki directory in it, and no roster file.

**Comment by mnieber** [comment]
For anyone reading this (later), the workaround with the empty roster file did not work, so I decided to just create a roster file on the fly and use this, instead of `--roster scan`.
