### ISSUE TITLE
win_useradd.delete doesn't work due to bad win32ts.error usage when no user is logged in

### ISSUE THREAD

**Issue by lukasraska** [saltstack/salt#46578]
### Description of Issue/Question
Due to the fact `win32ts.error` doesn't exist, when used in https://github.com/saltstack/salt/blob/develop/salt/modules/win_useradd.py#L386 it creates exception with `AttributeError: 'module' object has no attribute 'error'`.

This seems to be issue for Windows 2012/2012 R2 where `win32ts.WTSEnumerateSessions()` call can throw `pywintypes.error: (259, 'WTSEnumerateSessions', 'No more data is available.')`. In the code it also seems it would fail afterwards even if the code was correct due to the fact `sess_list` is not initialised beforehand.

I assume the correct fix would be replacing all `win32ts.error` calls with `pywintypes.error` and the same for other win32* modules where error attribute is missing if used (plus initializing `sess_list` first). If so, I can prepare PR to address it.

### Setup
Windows 2012 / 2012 R2 with nobody logged in (clean installation).

### Steps to Reproduce Issue
Run `salt '<win2012 minion>' user.delete <existinguser>`

### Versions Report
Tested on 2017.7, however the code seems to be similar in 2018.3

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any opinions on the suggested fix to the issue?
