### ISSUE TITLE
puppet.fact tries to parse output to stderr

### ISSUE THREAD

**Issue by qcpeter** [saltstack/salt#46581]
### Description of Issue/Question
When using the puppet.fact module it runs the `facter` executable using `cmd.run`, this means that `stderr` gets merged into output. The module then tries to parse this. When `facter` encounters a non-fatal error it prints a message to `stderr` this then means that salt cannot interpret the output and the module execution fails.

I think parsing should only be done on stdout output, also facter now has `--json` flag for its output which may be easier to parse.

### Versions Report
Verision 2017.7+

**Comment by Ch3LL** [comment]
seems you have the solution in mind, want to take a stab at a PR?

**Comment by qcpeter** [comment]
I'll post a submit a PR later this evening :)
