### ISSUE TITLE
cron.present creates duplicate cron jobs after 'identifier' is specified

### ISSUE THREAD

**Issue by rongshengfang** [saltstack/salt#46596]
### Description of Issue/Question

When a cron.present state is configured without the `identifier`, the comment for the cron job will be created as follows:

`# <comment> SALT_CRON_IDENTIFIER:<name>`

When `identifier` is later added to the same cron.present state, it will create another identical cron job without a different comment line:

`# <comment> SALT_CRON_IDENTIFIER:<identifier>`

I would expect adding the `identifier` should cause the existing cron job to update its comment line with the new identifier specified from the default `name`.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

State without the `identifier`:
```
test_cron:
  cron.present:
    - name: ls /etc
    - hour: 1
    - minute: 0
    - user: root
```
Later we add the `identifier` to the same state:
```
test_cron:
  cron.present:
    - name: ls /etc
    - hour: 1
    - minute: 0
    - user: root
    - identifier: 'test_cron'
```
Result: duplicate cron jobs:
```
# crontab -l
# SALT_CRON_IDENTIFIER:ls /etc
0 1 * * * ls /etc
# SALT_CRON_IDENTIFIER:test_cron
0 1 * * * ls /etc
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
# salt-call --local --versions-report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.20.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by Ch3LL** [comment]
I view this as expected behavior because initially you created a `cron.present` with the identifier of `ls /etc` because by default the cron state module uses the name to identify which cron job to edit. Then you added identifier which changes the default behavior to look for a identifier argument to id the job so it does not see that new identifier so it will add that new job.

**Comment by rongshengfang** [comment]
I get it from technical standpoint, but this behavior is very puzzling and counterintuitive. Imagine that I want to create a cron job, but then I realized that I didn't want to use the `name` as the default identifier because it's a long command and clutters the crontab. So I add a shorter `identifier`. In my mind, this is still the same cron job and I shouldn't have to go in cron and delete the old cron job created by Salt with the `name` as the identifier. Maybe it's best to use the ID of the state as the identifier as it's more intuitive that one ID maps to one cron job (which is how Puppet does it by the way).

**Comment by Ch3LL** [comment]
i think that makes sense :)
