### ISSUE TITLE
Salt jinja errors point to wrong source

### ISSUE THREAD

**Issue by johnkeates** [saltstack/salt#46598]
This probably is related to another issue, but I can't find an error-reporting improvement ticket to add or link to.

### Description of Issue/Question
Executing state.apply on this install.sls: https://github.com/johnkeates/prometheus-formula/blob/split-formulas-wip/prometheus/exporter/node/install.sls

With this line in map.jinja: https://github.com/johnkeates/prometheus-formula/blob/dcbe717f6f2824f97ffac4bad1a1d34f7c04efe7/prometheus/exporter/node/map.jinja#L19

Gives: 

```
local:
    Data failed to compile:
----------
    Rendering SLS 'base:prometheus.exporter.node.install' failed: Jinja variable 'dict object' has no attribute 'version'
```
The problem in the map.jinja was that prometheus_exporter_node.version might not be set, but checking if it is defined and reading the value happened in the same if statement. This was resolved one commit later, but during testing salt pointed out the error and listed the wrong SLS. Or maybe not the wrong SLS, the state was correct, but the error was in a different file.

### Steps to Reproduce Issue
Clone repo at `dcbe717f6f2824f97ffac4bad1a1d34f7c04efe7` and execute `salt-call state.apply prometheus.exporter.node.install`

### Version
salt-call 2017.7.4 (Nitrogen)

**Comment by Ch3LL** [comment]
This is technically not the wrong sls as all salt is doing is trying to import the map file here: https://github.com/johnkeates/prometheus-formula/blob/split-formulas-wip/prometheus/exporter/node/install.sls#L3 and thats when it runs into the error. So technically it is failing on trying to render that sls file. 

ping @saltstack/team-core is there any ideas on a possible way to improve the error here or is this a limitation on jinja rendering?

**Comment by johnkeates** [comment]
Yeah, I had some talks on Slack, was indeed more of an issue that Salt scopes everything to the state that it is rendering for, so even if a render issue in a file two imports away it will still reference the file the state was in.

I'd imagine that if the renderer has some internal state that can track where it is while rendering, or perhaps some recursive render stack, that could be used to present more usable output.
