### ISSUE TITLE
How can salt execute module by [module]name.[class]name.[method]name?

### ISSUE THREAD

**Issue by SwinBlackSea** [saltstack/salt#46591]
In my company,we want to use a python module 
named **uiautomation** from website by insert into 
salt default module path
 _C:\salt\bin\Lib\site-packages\salt\modules_

and I can use the module by
 `salt wlj uiautomation.ShowDesktop`,

but I can't use it by 
`uiautomation.Win32API.GetScreenSize` 

note:Win32API is a class in uiautomation. 

**so my question is how can I use method of class in uiautomation by salt**

If you have answer,Please tell me ,
Thank you for your help

**Comment by Ch3LL** [comment]
The loader system does not currently expose Classes. If you require class logic you can still write classes but expose the necessary logic in the function.
