### ISSUE TITLE
Bootstrap of Chocolatey: Ensure file integrity

### ISSUE THREAD

**Issue by eglipeter** [saltstack/salt#46599]
Please ensure that in the file ` salt/salt/modules/chocolatey.py ` the http links to Microsoft are replaced by https links. These should work with only changing http:// to https://. In addition it would be nice if after the download some checksum would be verified to ensure that the downloaded file is neither corrupted nor manipulated during download. The same applies also to the Install.ps of chocolatey. If the latter is not possible since the files are changing too frequently, it should be at least ensured that the proper TLS certificates are used.

At the moment download via http without any checks is a real security issue!

Yours,
Peter

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows opinions?

**Comment by morganwillcock** [comment]
Are we talking about the links to the Windows Updates? MSU files are signed updates, so they shouldn't install if modified, but the .NET4 installer might be an issue. The Chocolatey bootstrap looks like it is already using HTTPS.

**Comment by eglipeter** [comment]
I suggest, that all links should be changed to the https:// (TLS secured) version. I tested all of them with https:// instead of http:// and they are all working. So although, the msu files are signed, I think we don't loose anything when changing the URLs to the https version. 

Concerning the .NET installer one should think about including a SHA256 sum (or any other checksum) into the source code of salt in order to ensure that the file is not manipulated. Also this URL can be changed to https://

Yours,
Peter
