### ISSUE TITLE
feature request: support for lldp information on minions

### ISSUE THREAD

**Issue by c0de123** [saltstack/salt#46636]
### Description of Issue/Question

Hi,
I think it'd be nice to have lldp information from, let's say, lldpctl from lldpd. I know there is partial support for that via napalm but it would be nice to not have this dependency and lldp information is also valuable from devices that are not explicitely network devices (and we can argue back and forth how a network device is a computer and vice versa ;)).
If there is anything you need from me regarding this, just ping back.
I would otherwise highly appreciate if we could get this information in the future automatically via built in salt mechanisms.

**Comment by Ch3LL** [comment]
ping @saltstack/team-network this is a bit over my head, mind commenting here?

**Comment by mirceaulinic** [comment]
Sounds like a good idea to me, and relatively simple to implement (at least on some Unix distributions). For example on the majority of Linux systems you can do just `__salt__['cmd.run']('lldpctl -f json')` and load that JSON output, so basically the module would become as short as:

```python
import json

def interfaces():
    return json.loads(__salt__['cmd.run']('lldpctl -f json'))
```

**Comment by c0de123** [comment]
Yep, as a module this would be really nice to have. 
I would also suggest to put lldp information into grains, to be honest. I'd like to match minions via their network neighborship. This will be a little bit more code, though.

**Comment by mirceaulinic** [comment]
I agree. Yes, I would encourage you to submit a PR adding the execution module, and the grains module can just use it straight away.
