### ISSUE TITLE
salt-ssh executes old code even with --thin option

### ISSUE THREAD

**Issue by mnieber** [saltstack/salt#46654]
Version: based on 7b7eb740def56620d693746507bd51d65f3f69b9

When I called salt-ssh with the --thin option, I expected salt to use the latest source files on the remote server. Instead it runs with the *old* sources, though it renews the source files on the remote server (as a post processing step?). This means that on a subsequent call, it would use the new sources.

The best fix would imo be to change the behaviour and run with the new sources. Otherwise, it would be good to make it clear in the documentation that when --thin is supplied in the current call, the old sources are still used during that call.

**Comment by garethgreenaway** [comment]
@mnieber Thanks for the report.
