### ISSUE TITLE
states/boto3_route53.rr_present won't make A records 

### ISSUE THREAD

**Issue by brenwhyte** [saltstack/salt#46662]
### Description of Issue/Question
Unable to add an A record via boto3 on Windows and Debian host, throwing an exception.
### Setup
SLS file

    addarecord:
      boto_route53.rr_present:
        - ResourceRecords:
          - {{ grains['ipv4'] }}
        - DomainName: 'domain.dr.'
        - Name: '{{ grains['id'] }}'
        - Type: 'A'
        - TTL: 300
        - region: 'eu-west-1'

Fails with:

    root@saltmaster:~# salt 'server.domain.dr' state.sls aws.route53_addarecord -l debug
    [DEBUG   ] Reading configuration from /etc/salt/master
    [DEBUG   ] Including configuration from '/etc/salt/master.d/acl.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/acl.conf
    [DEBUG   ] Including configuration from '/etc/salt/master.d/admins.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/admins.conf
    [DEBUG   ] Including configuration from '/etc/salt/master.d/cherrpy.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/cherrpy.conf
    [DEBUG   ] Including configuration from '/etc/salt/master.d/mastersettings.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/mastersettings.conf
    [DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf
    [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltmaster.domain.svc
    [DEBUG   ] Missing configuration file: /root/.saltrc
    [DEBUG   ] Configuration file path: /etc/salt/master
    [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
    [DEBUG   ] Reading configuration from /etc/salt/master
    [DEBUG   ] Including configuration from '/etc/salt/master.d/acl.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/acl.conf
    [DEBUG   ] Including configuration from '/etc/salt/master.d/admins.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/admins.conf
    [DEBUG   ] Including configuration from '/etc/salt/master.d/cherrpy.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/cherrpy.conf
    [DEBUG   ] Including configuration from '/etc/salt/master.d/mastersettings.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/mastersettings.conf
    [DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups.conf'
    [DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups.conf
    [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltmaster.domain.svc
    [DEBUG   ] Missing configuration file: /root/.saltrc
    [DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
    [DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
    [DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master',         'saltmaster.domain.svc_master', 'tcp://127.0.0.1:4506', 'clear')
    [DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
    [DEBUG   ] LazyLoaded local_cache.get_load
    [DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/16/5073307456709330a82f31d93eaf3d4d9f7ed87276d22ef7af4210170e1e4c/.minions.p
    [DEBUG   ] get_iter_returns for jid 20180320162422455331 sent to set(['server.domain.dr']) will timeout at 16:24:27.462980
    [DEBUG   ] jid 20180320162422455331 return from server.domain.dr
    [DEBUG   ] return event: {'server.domain.dr': {'jid': '20180320162422455331', 'retcode': 2, 'ret': {'boto_route53_|-addarecord_|-addarecord_|-rr_present': {'comment': "State 'boto_route53.rr_present' was not found in SLS 'aws.route53_addarecord'\nReason: 'boto_route53' __virtual__ returned False\n", '__run_num__': 0, 'changes': {}, 'result': False, 'name': 'addarecord'}}, 'out': 'highstate'}}
    [DEBUG   ] LazyLoaded highstate.output
    server.domain.dr:
    ----------
              ID: addarecord
        Function: boto_route53.rr_present
          Result: False
         Comment: State 'boto_route53.rr_present' was not found in SLS 'aws.route53_addarecord'
                  Reason: 'boto_route53' __virtual__ returned False
         Changes:

    Summary for server.domain.dr
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1
    Total run time:   0.000 ms
    [DEBUG   ] jid 20180320162422455331 found all minions set(['server.domain.dr'])
    ERROR: Minions returned with non-zero exit code

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

```boto3==1.5.20```

Master

    Salt Version:
               Salt: 2017.7.4
    
    Dependency Versions:
               cffi: 1.11.4
           cherrypy: 3.2.3
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: Not Installed
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.3
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1052-aws
         system: Linux
        version: Ubuntu 16.04 xenial```

Minion

    salt-call --versions-report
    Salt Version:
           Salt: 2017.7.4
    
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: unknown
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:53:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.0
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
    
    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free

**Comment by garethgreenaway** [comment]
@brenwhyte Thanks for the report.  It appears that the boto_route53 module is not loading.  Most likely because the python boto libraries are not installed but another cause could be that the minimum version is not installed.  Can you check that either python-boto or python-botocore are installed?  It should be at least version 1.2.6 for python-boto and 1.3.23 for python-botocore.

**Comment by brenwhyte** [comment]
Thanks Gareth.

These are the installed modules on the minion, including the boto3 modules

    C:\Users\Administrator>C:\salt\bin\python.exe -m pip freeze
    appdirs==1.4.3
    asn1crypto==0.24.0
    backports-abc==0.5
    backports.ssl-match-hostname==3.5.0.1
    boto3==1.5.20
    botocore==1.8.50
    certifi==2018.1.18
    cffi==1.10.0
    cheroot==6.0.0
    CherryPy==10.2.1
    cryptography==1.8.1
    docutils==0.14
    enum34==1.1.6
    futures==3.1.1
    gitdb==0.6.4
    gitdb2==2.0.3
    GitPython==2.1.3
    idna==2.5
    ioloop==0.1a0
    ipaddress==1.0.18
    Jinja2==2.9.6
    jmespath==0.9.3
    libnacl==1.6.1
    lxml==3.7.3
    Mako==1.0.6
    MarkupSafe==1.0
    more-itertools==4.1.0
    msgpack-python==0.4.8
    packaging==17.1
    portend==2.2
    psutil==5.2.2
    pyasn1==0.2.3
    pycparser==2.17
    pycrypto==2.6.1
    pycurl==7.43.0
    PyMySQL==0.7.11
    pyOpenSSL==17.0.0
    pyparsing==2.2.0
    pypiwin32==223
    python-dateutil==2.6.0
    python-gnupg==0.4.0
    pytz==2018.3
    pywin32==223
    PyYAML==3.12
    pyzmq==16.0.2
    requests==2.13.0
    s3transfer==0.1.13
    salt==2017.7.4
    singledispatch==3.4.0.3
    six==1.10.0
    smmap==0.9.0
    smmap2==2.0.3
    tempora==1.10
    timelib==0.2.4
    tornado==4.5.1
    WMI==1.4.9
    
    C:\Users\Administrator>

Anything else just let me know.

Bren

**Comment by brenwhyte** [comment]
Hi Gareth,

I just tried updating the boto3 modules on the minion but it didn't help. (minion service restarted afterwards)

```
C:\Users\Administrator>C:\salt\bin\python.exe -m pip install --upgrade boto3
Collecting boto3
  Downloading boto3-1.6.15-py2.py3-none-any.whl (128kB)
    100% |################################| 133kB 1.7MB/s
Collecting botocore<1.10.0,>=1.9.15 (from boto3)
  Downloading botocore-1.9.15-py2.py3-none-any.whl (4.1MB)
    100% |################################| 4.1MB 261kB/s
Requirement already up-to-date: s3transfer<0.2.0,>=0.1.10 in c:\salt\bin\lib\sit
e-packages\s3transfer-0.1.13-py2.7.egg (from boto3)
Requirement already up-to-date: jmespath<1.0.0,>=0.7.1 in c:\salt\bin\lib\site-p
ackages\jmespath-0.9.3-py2.7.egg (from boto3)
Collecting python-dateutil<2.7.0,>=2.1 (from botocore<1.10.0,>=1.9.15->boto3)
  Downloading python_dateutil-2.6.1-py2.py3-none-any.whl (194kB)
    100% |################################| 194kB 2.2MB/s
Requirement already up-to-date: docutils>=0.10 in c:\salt\bin\lib\site-packages\
docutils-0.14-py2.7.egg (from botocore<1.10.0,>=1.9.15->boto3)
Collecting futures<4.0.0,>=2.2.0 (from s3transfer<0.2.0,>=0.1.10->boto3)
  Downloading futures-3.2.0-py2-none-any.whl
Collecting six>=1.5 (from python-dateutil<2.7.0,>=2.1->botocore<1.10.0,>=1.9.15-
>boto3)
  Downloading six-1.11.0-py2.py3-none-any.whl
Installing collected packages: six, python-dateutil, botocore, boto3, futures
  Found existing installation: six 1.10.0
    Uninstalling six-1.10.0:
      Successfully uninstalled six-1.10.0
  Found existing installation: python-dateutil 2.6.0
    Uninstalling python-dateutil-2.6.0:
      Successfully uninstalled python-dateutil-2.6.0
  Found existing installation: botocore 1.8.50
    Uninstalling botocore-1.8.50:
      Successfully uninstalled botocore-1.8.50
  Found existing installation: boto3 1.5.20
    Uninstalling boto3-1.5.20:
      Successfully uninstalled boto3-1.5.20
  Found existing installation: futures 3.1.1
    Uninstalling futures-3.1.1:
      Successfully uninstalled futures-3.1.1
Successfully installed boto3-1.6.15 botocore-1.9.15 futures-3.2.0 python-dateuti
l-2.6.1 six-1.11.0

C:\Users\Administrator>C:\salt\bin\python.exe -m pip freeze
appdirs==1.4.3
asn1crypto==0.24.0
backports-abc==0.5
backports.ssl-match-hostname==3.5.0.1
boto3==1.6.15
botocore==1.9.15
certifi==2018.1.18
cffi==1.10.0
cheroot==6.0.0
CherryPy==10.2.1
cryptography==1.8.1
docutils==0.14
enum34==1.1.6
futures==3.2.0
gitdb==0.6.4
gitdb2==2.0.3
GitPython==2.1.3
idna==2.5
ioloop==0.1a0
ipaddress==1.0.18
Jinja2==2.9.6
jmespath==0.9.3
libnacl==1.6.1
lxml==3.7.3
Mako==1.0.6
MarkupSafe==1.0
more-itertools==4.1.0
msgpack-python==0.4.8
packaging==17.1
portend==2.2
psutil==5.2.2
pyasn1==0.2.3
pycparser==2.17
pycrypto==2.6.1
pycurl==7.43.0
PyMySQL==0.7.11
pyOpenSSL==17.0.0
pyparsing==2.2.0
pypiwin32==223
python-dateutil==2.6.1
python-gnupg==0.4.0
pytz==2018.3
pywin32==223
PyYAML==3.12
pyzmq==16.0.2
requests==2.13.0
s3transfer==0.1.13
salt==2017.7.4
singledispatch==3.4.0.3
six==1.11.0
smmap==0.9.0
smmap2==2.0.3
tempora==1.10
timelib==0.2.4
tornado==4.5.1
WMI==1.4.9

C:\Users\Administrator>
```
