### ISSUE TITLE
cmd.run_stdout runas=root hangs for 90 sec

### ISSUE THREAD

**Issue by pjcreath** [saltstack/salt#46667]
### Description of Issue/Question
Nearly always (but not quite), cmd.run_stdout will stall for 90 seconds before returning.

### Setup
I originally encountered this when `cron.env_present` states would each take 90 seconds sometimes but not always.  I tracked it down to `cmd.run_stdout` when the `runas` argument is passed.

I can reproduce this by running `salt '*' cmd.run_stdout 'crontab -l' runas=root`.  Most of the time it takes 90 seconds.  Every once in a while it'll finish in 0.5s.

### Steps to Reproduce Issue
Here's an instrumented version of `modules/cmdmod.py` (with the Popen().communicate() split into two statements):
```
            log.error("before popen")
            log.error(repr(env_cmd))
            log.error(py_code.encode(__salt_system_encoding__))
            proc = subprocess.Popen(
                env_cmd,
                stdin=subprocess.PIPE,
                stdout=subprocess.PIPE
            )
            log.error("proc created")
            env_encoded = proc.communicate(py_code.encode(__salt_system_encoding__))[0]
            log.error("communicate done")
```
and here's sample log output:
```
2018-03-22 15:15:34,425 [salt.loader.10.10.10.10.int.module.cmdmod:435 ][ERROR   ][8505] before popen
2018-03-22 15:15:34,425 [salt.loader.10.10.10.10.int.module.cmdmod:436 ][ERROR   ][8505] ('su', '-s', '/bin/sh', '-', 'root', '-c', '/usr/bin/python')
2018-03-22 15:15:34,425 [salt.loader.10.10.10.10.int.module.cmdmod:437 ][ERROR   ][8505] import sys, os, itertools; sys.stdout.write("\0".join(itertools.chain(*os.environ.items())))
2018-03-22 15:15:34,428 [salt.loader.10.10.10.10.int.module.cmdmod:445 ][ERROR   ][8505] proc created
2018-03-22 15:17:04,501 [salt.loader.10.10.10.10.int.module.cmdmod:448 ][ERROR   ][8505] communicate done
```
I've tried a bunch of different approaches to fix this:
1. Adding `sys.stdout.flush()` or `sys.stdout.close()` to `py_code`.
2. Changing env_cmd to invoke python with `-u`, e.g. `'/usr/bin/python -u'`
3. Combinations of the above.

None of these have consistently resolved the stall.

I'm not sure what else to try.  I can prepare a PR once we arrive at a solution.

### Versions Report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by garethgreenaway** [comment]
@pjcreath Thanks for the report.  Are you seeing the 90 second Salt runs always with `crontab -l` or is it with other commands as well?  Since you're using `runas=root` are you running the Salt minion as a different user than root?  Are you able to run the Salt minion in debug mode to see where it might be getting stuck when running commands. Thanks!

**Comment by pjcreath** [comment]
Addressing your questions in order:
1. The 90-second salt run happens with any command, not just `crontab -l` (I chose that as a sample since it was the command that `cron.env_present` was executing). The stall is happening before the actual command is run, under an `if runas` section that's collecting the runas user's environment before doing so.
2. salt is also running as root.  I'm using `runas=root` because that's how `cron.env_present` invokes `cmd.run_stdout` and the `runas` parameter is what causes the above section to be executed.
3. Debug mode is uninformative, as there is insufficient logging information (debugging or otherwise) emitted by the module without the instrumentation I added above. For simplicity I added the debug messages as `log.error` so that they would appear without having to relaunch salt-minion in debug mode.

You can find the relevant code in modules/cmdmod.py by searching for `if runas:` or `py_code`.  Comparing that to the log above, you'll see that the stall is happening when calling `communicate` on the process created to collect the runas user's environment (again, not when running `crontab -l`).

It seems like a buffering deadlock, where the process's stdout is being buffered, so communicate() isn't returning until some timeout expires, but the usual tricks (such as invoking python with the `-u` flag) didn't work.

**Comment by pjcreath** [comment]
I also tried executing the exact command that run_stdout is invoking here directly, and it never stalled:

`# echo 'import sys, os, itertools; sys.stdout.write("\0".join(itertools.chain(*os.environ.items())))' | su -s /bin/sh - root -c /usr/bin/python`

And in case you're still curious, here's the additional information provided by turning on debug logging.  As you can see, it doesn't provide any additional insight:

```
2018-03-22 14:03:57,336 [salt.utils.lazy  :97  ][DEBUG   ][19970] LazyLoaded cron.env_present
2018-03-22 14:03:57,336 [salt.state       :1742][INFO    ][19970] Running state [my_var] at time 14:03:57.336311
2018-03-22 14:03:57,336 [salt.state       :1775][INFO    ][19970] Executing state cron.env_present for [my_var]
2018-03-22 14:03:57,336 [salt.loaded.int.module.cmdmod:388 ][INFO    ][19970] Executing command 'crontab -l' as user 'root' in directory '/root'
2018-03-22 14:03:57,337 [salt.loaded.int.module.cmdmod:434 ][ERROR   ][19970] before popen
2018-03-22 14:03:57,337 [salt.loaded.int.module.cmdmod:435 ][ERROR   ][19970] ('su', '-s', '/bin/sh', '-', 'root', '-c', '/usr/bin/python')
2018-03-22 14:03:57,337 [salt.loaded.int.module.cmdmod:436 ][ERROR   ][19970] import sys, os, itertools; sys.stdout.write("\0".join(itertools.chain(*os.environ.items())))
2018-03-22 14:03:57,343 [salt.loaded.int.module.cmdmod:442 ][ERROR   ][19970] proc created
2018-03-22 14:05:27,421 [salt.loaded.int.module.cmdmod:444 ][ERROR   ][19970] communicate done
2018-03-22 14:05:27,438 [salt.loaded.int.module.cmdmod:1342][DEBUG   ][19970] stdout: # Lines below here are managed by Salt, do not edit
my_var=foo

2018-03-22 14:05:27,439 [salt.state       :273 ][INFO    ][19970] Cron env my_var already present
2018-03-22 14:05:27,439 [salt.state       :1915][INFO    ][19970] Completed state [my_var] at time 14:05:27.439439 duration_in_ms=90103.126
```

An interesting side note, though:  running `salt-minion -l debug` from the console never stalls.  So I had to add `--log-file-level debug` to the `salt-minion.service` file to view this.

I wonder if that's a clue?

Just in case it was an issue of salt-minion's python doing the buffering, I tried adding `-u` both to the `#!` line in salt-minion and to the process being invoked by run_stdout, but that didn't fix it.  It sometimes varied the timeout somewhat, sometimes 30 sec, sometimes 80, sometimes 60, sometimes 90, but it's still there.

For good measure, I also added `sys.stdout.close()` to `py_code` and `bufsize=0` to the `Popen` call, with no effect.

**Comment by adambarnett52** [comment]
Hi, 

 i am also seeing this on salt-call 2017.7.4 (Nitrogen)

**Comment by adambarnett52** [comment]
Any movement on this? We are finding that salt will just hang and never move on . Happy to help with testing

**Comment by garethgreenaway** [comment]
Apologies for the delay on this one.  So far I haven't been able to reproduce this particular issue.  If someone is able to provide a snapshot, Docker image, etc. of a system where the problem is reproducible that would be helpful.

**Comment by adambarnett52** [comment]
Hi 

I cannot give an image ( NDA/Security ) but i am happy to help debug. 
I had a machine last week that i could reproduce  this 100% of the time on every salt run 

Thanks
Adam

**Comment by damon-atkins** [comment]
What has recently changes, e.g. salt version, patches etc.  Is it one server or lots of servers?  I assume your using ssh-salt.  Instead of  `crontab -l`   try `/usr/bin/time /usr/bin/true`

**Comment by adambarnett52** [comment]
This has happened since upgrading to 2017.7.4
I am running the salt minion and it is  crontab state that is causing it, when it runs something like this 


```
/usr/local/clamXav/bin/freshclam:
  cron:
    - present
    - user: root
    - dayweek: 7
    - hour: 23
    - minute: 0
    - identifier: update virus definitions and scan / and /user_data


```

**Comment by adambarnett52** [comment]
looks to be happening on OSX 10.13
