### ISSUE TITLE
SCEP , NDES , EST support

### ISSUE THREAD

**Issue by miradam** [saltstack/salt#46678]
### Description of Issue/Question
This is more question or request for engineering rather than a bug itself. I'm looking for the most appropriate way to request X.509 certificates with SaltStack from external Certificate Authority.
In other words using self signed certs is not an option and ideally I'd like to have SCEP , NDES , EST integrated into X.509 module.

**Comment by Ch3LL** [comment]
I believe the x509 states currently work with remote CAs as documented here: https://docs.saltstack.com/en/develop/ref/states/all/salt.states.x509.html#module-salt.states.x509

does that fit your use case?

**Comment by miradam** [comment]
AFAIU existing module depends on create_certificate function
https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.x509.html#salt.modules.x509.create_certificate
This function defines property signing_policy which can define different, non default signing policies. But still these policies depends on X.509 keys stored on master e.g.
    - signing_private_key: /etc/pki/ca.key
    - signing_cert: /etc/pki/ca.crt

**Comment by miradam** [comment]
This is of course useful but specifically doesn't deal with signing certificates over the network via SCEP, NDES or EST. Remote CA with SCEP/NDES/EST protocol support is not covered by this module and must be implemented separately. At this moment I'm not aware of SaltStack module providing this, just FYI.
