### ISSUE TITLE
docker_container.running connect default bridge

### ISSUE THREAD

**Issue by supfors** [saltstack/salt#46708]
### Description of Issue/Question
When using the new `networks` argument from `salt.states.docker_container.running` in `2018.3.0rc1`,  my container is also connected to the default `bridge`.
I would expect my container to only be connected to the specified network(s).

### Setup
```
test-container:
  docker_container.running:
    - image: alpine
    - name: test-container
    - networks:
      - test
```

```
salt dockerhost state.sls test
dockerhost:
----------
          ID: test-container
    Function: docker_container.running
      Result: True
     Comment: Created container 'test-container'
     Started: 14:44:33.407015
    Duration: 2074.814 ms
     Changes:   
              ----------
              container:
                  ----------
                  Networks:
                      ----------
                      test:
                          ----------
                          Gateway:
                              ----------
                              new:
                                  172.18.0.1
                              old:
                                  None
                          IPAddress:
                              ----------
                              new:
                                  172.18.0.2
                              old:
                                  None
              container_id:
                  ----------
                  added:
                      c84b6ede4fe316b690a73d9af234bae685c2da84fe5d0c40d6f299ecd7a3d725
              state:
                  ----------
                  new:
                      running
                  old:
                      None

Summary for dockerhost
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   2.075 s
```

```
root@dockerhost:~# docker ps --format 'table {{ .Names }}\t{{ .Networks }}'
NAMES               NETWORKS
test-container      bridge,test
```

#### master:
```
salt --versions-report
Salt Version:
           Salt: 2018.3.0rc1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.3 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: debian 9.3
```

#### minion:

```
salt-minion --versions-report
Salt Version:
           Salt: 2018.3.0rc1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 3.1.4
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
@terminalmage Thoughts on this one?

**Comment by terminalmage** [comment]
The way that this feature works is that when Salt creates a container, it adds the specified networks. So, this implicitly assumes the default networks will remain attached. I can see how this may be confusing, however.

The question is, how should we manage this? Should we require that `bridge` (or any other default network) be specified in the SLS, lest it be removed? Or should we introduce another argument to the state to instruct it to delete any networks that aren't specified in the `networks` option (if present, otherwise we wouldn't want to touch the networks).

I personally think that the OP's expectation is correct, and we shouldn't introduce another option to force that behavior. This would however require a slight modification to the `docker_container.running` state which would be released with 2018.3.1. So, we would have one release with the existing behavior, and all subsequent releases would have a different behavior. So long as this is properly documented, I have no problem with this.

@saltstack/team-core thoughts?

**Comment by garethgreenaway** [comment]
@terminalmage I would think the specified networks would be the only ones that the container is included in.  In the case that `networks` isn't specified then it defaults to the default one.

**Comment by terminalmage** [comment]
I agree. https://github.com/saltstack/salt/pull/46718 addresses this and will be targeted for the 2018.3.1 release.

**Comment by terminalmage** [comment]
As a correction, that change has be re-targeted for the next feature release.

**Comment by supfors** [comment]
Something to add:  
From a security point of view I now use `docker.disconnect_container_from_network`
to remove containers from the default `bridge` network, by default, as a workaround.

This however sort of breaks consecutive highstates, as the temporary container to 
compare with has the default `bridge` network, while my `test-container` does not:

```
ID: test-container
Function: docker_container.running
Name: test-container
Result: True
Comment: Container 'test-container' is already configured as specified
Started: 12:38:06.332507
Duration: 1741.451 ms
Changes:   
    ----------
    container:
        ----------
        Networks:
            ----------
            bridge:
                ----------
                IPConfiguration:
                    ----------
                    new:
                        automatic
                    old:
                        not connected
```

Would love to see your pull request merged rather sooner than later.
Thank you for the new salt docker toys. Much appreciated!

**Comment by supfors** [comment]
Furthermore: removing the default `bridge` from the container also breaks f.e. `watch` or `watch_in` statements.  Always resulting in above output, without restarting the container on changes.

**Comment by terminalmage** [comment]
@supfors The pull request I opened last week addresses both of these issues by disconnecting unspecified containers both from the running container (if the container does not need to be replaced due to config differences), and from the temp container used for comparisons.
