### ISSUE TITLE
TCPPubServerChannel consumes high memory

### ISSUE THREAD

**Issue by jvrahav** [saltstack/salt#46725]
### Description of Issue/Question
I have about 3k minions connected to a single master. we are testing to check salt scale.
we had issues with zeromq transport where we were unable to reach certain minions. We switched over to TCP.  With TCP we are able to reach all the minions however memory consumption has increased a lot when compared to using zeromq transport.

This is the output of ps command

 2645.58 Mb /bin/python /usr/bin/salt-master -d TCPPubServerChannel
      1503.43 Mb /bin/python /usr/bin/salt-master -d Reactor
       138.95 Mb /bin/python /usr/bin/salt-master -d MWorker-3
       136.97 Mb /bin/python /usr/bin/salt-master -d MWorker-1
       136.86 Mb /bin/python /usr/bin/salt-master -d MWorker-2
       136.16 Mb /bin/python /usr/bin/salt-master -d MWorker-0
       134.22 Mb /bin/python /usr/bin/salt-master -d MWorker-4
       133.91 Mb /bin/python /usr/bin/salt-master -d EventPublisher
       121.21 Mb /bin/python /usr/bin/salt-master -d Maintenance
       107.59 Mb /bin/python /usr/bin/salt-master -d ProcessManager
       107.59 Mb /bin/python /usr/bin/salt-master -d ReqServer_ProcessManager
       106.45 Mb /bin/python /usr/bin/salt-master -d MultiprocessingLoggingQueue
        36.93 Mb /bin/python /usr/bin/salt-api -d
        34.21 Mb /bin/python /usr/bin/salt-api -d NetAPIProcessManager

Is this expected that TCP would consume more memory than zeromq. Is there some tuning that needs to be done for TCP w.r.t memory consumption

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 25 2017, 01:32:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.114-1.ph1
         system: Linux
        version: Not Installed

**Comment by Ch3LL** [comment]
ping @saltstack/team-transport can you chime in here? Is this expected behavior?

**Comment by jvrahav** [comment]
im sorry as we had to drop tcp as we were experiencing high memory usage in salt master. I dont have the setup any more to get the information that you require. I will try to set up a new setup and get that information.
