### ISSUE TITLE
file.recurse fails with "none of the specified sources were found"

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#46737]
This is a new issue opened based off of conversation with @markuskramerIgitt in https://github.com/saltstack/salt/issues/32128.

Master is running 2016.11.5, Minions are 2016.11.3

SLS causing the failure:

```
Sync the config folder with clean:
  file.recurse:
    - name: /apps/dhlcopy/conf
    - source: salt://rootWin/c/apps/dhlcopy/conf
    - clean: True

Sync the tools folder with clean:
  file.recurse:
    - name: /apps/dhlcopy/tools
    - source: salt://rootWin/c/apps/dhlcopy/tools
    - clean: True
```

**Comment by terminalmage** [comment]
@markuskramerIgitt is the master running Windows?

**Comment by terminalmage** [comment]
I'm not able to reproduce with a master running 2016.11.5 and a minion running 2016.11.3. Does the minion perhaps have the `environment` config param set in the minion config file?

**Comment by terminalmage** [comment]
Also, what is the output of `salt <minion_id> cp.list_master_dirs`, or `salt <minion_id> cp.list_master_dirs envname` if `environment` is set in the minion config file?

**Comment by markuskramerIgitt** [comment]
The minions have no `environment` config param set in the minion config file. The file contains the unaltered comment  `#environment: None`

The output of `salt <minion_id> cp.list_master_dirs` is empty

In my understanding, the output of cp.list_master_dirs should not be empty.

On the salt-master, salt:// should translate to /srv/salt.

I verified that the source files are still there and readable:


```
root@salt1:~# ls -l /srv/salt/rootWin/c/apps/dhlcopy/conf/
total 4
-rw-r--r-- 1 root root 100 Jan 23 13:12 altiris-policies.conf
```

Where can I verify that salt:// is /srv/salt?

What other tests can I perform?  What other (e.g. network) requirements can I test?

**Comment by terminalmage** [comment]
You're correct that `cp.list_master_dirs` should not be empty; that is the reason for the error being returned in the state. There are a few reasons why this might be the case, let's see if we can narrow them down.

The default path for the `base` environment should be `/srv/salt`. There are a couple things I can think of off the top of my head that could affect this:

1. The `file_roots` has explicitly been set in the master configuration to something other than `/srv/salt` for the `base` environment.
2. The `fileserver_backend` has explicitly been in the master configuration, and does not include `roots`. This would mean that the `file_roots` is completely disregarded, and all `salt://` URLs refer to files from a different fileserver backend (e.g. git).

Can you share any uncommented lines in your master configuration (taking care of course to obscure any sensitive information)? Note that this includes `/etc/salt/master` as well as any `.conf` files in `/etc/salt/master.d`.

Something else you can do would be to temporarily add `pillar_opts: True` to the minion configuration for one of the affected minions, and then restart the salt-minion service. This will add a pillar key called `master` which contains the master configuration, and you would then be able to do `salt <minion_id> pillar.get master:file_roots` (or `master:fileserver_backend`, etc.) to see the master's configuration.

**Comment by markuskramerIgitt** [comment]
Before Salt stopped working, no one changed the configuration. 
But many port where closed recently, due to Meltdown and Spectre. 
Could Salt commands work, but file.recurse fail, due to firewalls blocking ports?
Could than a Wireshark recording help?

We have not altered the 'file_roots' environment nor use fileserver-backends.
Below is our configuration, sensitive information removed.
File `/etc/salt/master` is unaltered
This is `/etc/salt/master/master.conf`:

```
# 2017-04-26     Markus Kramer  worker_threads: 40   preserve memory
worker_threads: 40



# 2017-03-16     Markus Kramer    for performance
key_cache: 'sched'


reactor:
  - 'minion_tells_master_yIPv4':
    - /srv/reactor/event_minion_tells_master_yIPv4_reaction.sls


# 2017-07-18   mkr   modify the rawfile_json returner, should be in a file of its own. Copy .py manually
event_return: rawfile_json
rawfile_json.filename: '/var/log/salt/eventsMarkus'
event_return_blacklist:
  - salt/master/not_this_tag_another_time


# 2017-07-19   mkr   Dont mention minions that timeout when running commands 
show_timeout: False

```
I stopped using the reactor because it was unreliable and too heavy on load.
I should remove `minion_tells_master_yIPv4` from the master.conf.

**Comment by markuskramerIgitt** [comment]
I looked at /var/log/salt/master and found

```
2018-03-28 15:50:54,718 [salt.master      ][ERROR   ][7679] Error in function _dir_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1600, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/__init__.py", line 813, in dir_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 429, in dir_list
    return _file_lists(load, 'dirs')
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 391, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/lib/python2.7/dist-packages/salt/fileserver/roots.py", line 339, in _add_to
    log.trace('roots: Processing %s', abs_path)
  File "/usr/lib/python2.7/dist-packages/salt/log/mixins.py", line 35, in trace
    self.log(getattr(logging, 'TRACE', 5), msg, *args, **kwargs)
  File "/usr/lib/python2.7/logging/__init__.py", line 1224, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 310, in _log
    self, level, msg, args, exc_info=exc_info, extra=extra
  File "/usr/lib/python2.7/logging/__init__.py", line 1278, in _log
    record = self.makeRecord(self.name, level, fn, lno, msg, args, exc_info, func, extra)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 344, in makeRecord
    exc_info, func)
  File "/usr/lib/python2.7/dist-packages/salt/log/setup.py", line 191, in __init__
    self.colormsg = '%s%s%s' % (cmsg, self.getMessage(), reset)
  File "/usr/lib/python2.7/logging/__init__.py", line 335, in getMessage
    msg = msg % self.args
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 26: ordinal not in range(128)

```

I remember an earlier UnicodeDecodeError. This could explain that some Salt commands work, but no file transfer. 

I will now search non-ASCII characters in /srv/salt/* file names.

**Comment by edusperoni** [comment]
I'm having the same problem.

The issue is that a single directory has non-ASCII characters. As soon as I move the directory `Internação` to the salt structure, the error starts appearing and the state starts to fail.

**Comment by terminalmage** [comment]
The 2018.3 release cycle will include a lot of improvements to unicode handling, which fix this sort of issue. One such improvement is in our logging handler, in which we now normalize both the arguments _and_ the message (in 2017.7 and earlier only the message was being normalized).

I'm going to look at the changes made to the logging handler for 2018.3 and see if any of them can be backported to 2017.7.

**Comment by terminalmage** [comment]
See https://github.com/saltstack/salt/pull/46867

**Comment by terminalmage** [comment]
I've added some additional information to the comments of that PR which can be used to confirm that the PR fixes the issue: https://github.com/saltstack/salt/pull/46867#issuecomment-378630912

**Comment by markuskramerIgitt** [comment]
As @edusperoni reported, a non-ASCII filename somewhere under `/srv/salt/*` breaks the salt master.

We can limit our filenames to (7-bit) ASCII, just finding this issue has blocked us for weeks.

**Comment by terminalmage** [comment]
@markuskramerIgitt Yeah, I figured that out from his earlier comments. The pull request I linked to above fixes the problem. From 2017.7.6 forward, non-ascii filenames will not cause this problem.

**Comment by terminalmage** [comment]
Closing since the PR which fixes this has been merged.
