### ISSUE TITLE
Intermittent inline pillar 'data loss' within runner.state.orchestrate

### ISSUE THREAD

**Issue by sootythebear** [saltstack/salt#46736]
### Description of Issue
The description probably should be 'data loss' during the Jinja template rendering process, however I am only seeing this problem in the following scenario: beacon -> reactor -> runner.state.orchestrate

As the number of beacons/systems increase on the Salt Master, I start to see intermittent "Rendering SLS failed" messages.

```
2018-03-27 14:19:38,272 [salt.state       :3227][CRITICAL][28075] Rendering SLS 
'base:dashboard.server_disk' failed: Jinja error: unsupported operand type(s) for +: 'NoneType' and 
'str'
```

### Setup
/etc/salt/master.d/reactor.conf:
```
reactor:
  - salt/beacon/*/load/:
    - /srv/reactor/cpu_user.sls
  - salt/beacon/*/diskusage/:
    - /srv/reactor/disk_user.sls
  - salt/beacon/*/memusage/:
    - /srv/reactor/mem_user.sls
...
```
/srv/reactor/mem_user.sls:
```
update_mem_data:
  runner.state.orchestrate:
    - args:
      - mods: dashboard.server_mem
      - pillar:
          server: "{{ data['id'] }}"
          _stamp: "{{ data['_stamp'] }}"
          memusage: {{ data['memusage'] }}
```
/srv/reactor/disk_user.sls:
```
update_disk_data:
  runner.state.orchestrate:
    - args:
      - mods: dashboard.server_disk
      - pillar:
          server: "{{ data['id'] }}"
          _stamp: "{{ data['_stamp'] }}"
          mount: "{{ data['mount'] }}"
          diskusage: {{ data['diskusage'] }}
```
/srv/salt/dashboard/server_disk.sls (head):
```
{% set server_Disk = pillar.get('server') + "_Disk" %}
{% set server_Bad_MP = pillar.get('server') + "_Bad_MP" %}
{% set server_Marg_MP = pillar.get('server') + "_Marg_MP" %}
{% set server_Time = pillar.get('_stamp') %}

{% if ( salt['pillar.get']('diskusage') > grains['dashboard_Disk_Bad'] ) %}
...
```

### Steps to Reproduce Issue
Environment is ~50 servers configured with the beacons (load, diskusage and memusage) configured with an interval set to 300 seconds for each. There are a number of other reactors and scheduled tasks, that are being processed by the Salt Minion on the Master, and my plan was to move the reactor's SLS processing from the Minion (`local.state.apply`) to the Salt Master Runner. 

When I configure one reactor to use `runner.state.orchestrate:` everything ticks over fine. When I add the second and third, the following is thrown in `/var/log/salt/master` (note: the example log below shows a `diskusage` failure, however errors for the `load` and `memusage` flows are also being thrown sporadically too) :

```
2018-03-27 14:19:38,272 [salt.state       :3227][CRITICAL][28075] Rendering SLS 
'base:dashboard.server_disk' failed: Jinja error: unsupported operand type(s) for +: 'NoneType' and 
'str'
```
Followed by:
```
2018-03-27 14:19:38,285 [salt.utils.event :728 ][DEBUG   ][28075] Sending event: tag = 
salt/run/20180327141931538570/ret; data = {'fun_args': [{'pillar': OrderedDict([('server', 'xxxx-xxxxx-
06'), ('_stamp', '2018-03-27T14:19:31.345455'), ('mount', '/'), ('diskusage', 17.8)]), 'mods': 
'dashboard.server_disk'}], 'jid': '20180327141931538570', 'return': {'outputter': 'highstate', 'data': 
{'salt.xxxxxxx_master': ['Rendering SLS \'base:dashboard.server_disk\' failed: Jinja error: unsupported 
operand type(s) for +: \'NoneType\' and \'str\'\nTraceback (most recent call last):\n  File 
"/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 418, in render_jinja_tmpl\n    output = 
template.render(**decoded_context)\n  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", 
line 969, in render\n    return self.environment.handle_exception(exc_info, True)\n  File 
"/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception\n    
reraise(exc_type, exc_value, tb)\n  File "<template>", line 1, in top-level template code\nTypeError: 
unsupported operand type(s) for +: \'NoneType\' and \'str\'\n\n; line 1\n\n---\n{% set server_Disk = 
pillar.get(\'server\') + "_Disk" %}    <======================\n{% set server_Bad_MP = 
pillar.get(\'server\') + "_Bad_MP" %}\n{% set server_Marg_MP = pillar.get(\'server\') + "_Marg_MP" 
%}\n{% set server_Time = pillar.get(\'_stamp\') %}\n\n{% if ( salt[\'pillar.get\'](\'diskusage\') > 
grains[\'dashboard_Disk_Bad\'] ) %}\n[...]\n---']}, 'retcode': 1}, 'success': False, '_stamp': '2018-03-
27T14:19:38.285813', 'user': 'Reactor', 'fun': 'runner.state.orchestrate'}

```
However 3 seconds later, another system/beacon renders and processes fine:
```
2018-03-27 14:19:41,696 [salt.utils.event :728 ][DEBUG   ][28075] Sending event: tag = 
salt/run/20180327141938441340/ret; data = {'fun_args': [{'pillar': OrderedDict([('server', 'xxxxxxx-
xxxxxx-05'), ('_stamp', '2018-03-27T14:19:38.205254'), ('mount', '/'), ('diskusage', 17.8)]), 'mods': 
'dashboard.server_disk'}], 'jid': '20180327141938441340', 'return': {'outputter': 'highstate', 'data': 
{'salt.xxxxx_master': {'cmd_|-update_server_disk_table_|-/srv/scripts/server_disk xxxxxxx-xxxxxx-05 
2018-03-27T14:19:38.205254_|-run': {'comment': 'Command "/srv/scripts/server_disk xxxxxxx-
xxxxxx-05 2018-03-27T14:19:38.205254" run', 'name': '/srv/scripts/server_disk xxxxxxx-xxxxxx-05 
2018-03-27T14:19:38.205254', 'start_time': '14:19:40.931922', 'result': True, 'duration': 760.561, 
'__run_num__': 0, '__sls__': u'dashboard.server_disk', 'changes': {'pid': 3989, 'retcode': 0, 'stderr': '', 
'stdout': ''}, '__id__': 'update_server_disk_table'}}}, 'retcode': 0}, 'success': True, '_stamp': '2018-03-
27T14:19:41.695950', 'user': 'Reactor', 'fun': 'runner.state.orchestrate'}
```

### Versions Report

```
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
 
```

**Comment by gtmanfred** [comment]
First, for concatinating in jinja `~` should be used.

Also , can you try using `salt.pillar.get` or `salt['pillar.get']` instead of using the pillar dictionary?  I am wondering is that is the problem with how those are handled.  `pillar` just accesses the pillar dictionary, where `salt.pillar.get()` uses the `pillar.get` execution module.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Yeah, so now it isn't a concatenation error, but it is still basically the same problem, the server name is going missing from the pillar data.

Can you add a `salt.log.error(data['id'])` to the reactor, and just make certain that it is actually set to what you expect?   the only thing I can think of is if that is set to `None` for some reason

Thanks,
Daniel

**Comment by sootythebear** [comment]
Added the logging to the reactor, and this shows the values are there at this point. 

The calling of the state also suggests that the values are being passed - see `OrderedDict`:

2018-03-27 14:19:38,285 [salt.utils.event :728 ][DEBUG   ][28075] Sending event: tag = 
salt/run/20180327141931538570/ret; `data = {'fun_args': [{'pillar': OrderedDict([('server', 'xxxx-xxxxx-
06'), ('_stamp', '2018-03-27T14:19:31.345455'), ('mount', '/'), ('diskusage', 17.8)]), 'mods': 
'dashboard.server_disk'}]`, 'jid': '20180327141931538570', 'return': ....

**Comment by gtmanfred** [comment]
can you add a `salt.log.error(pillar)` to the orchestration state, and check the master log after this runs, just to see what is in that dict, and see if there are any pillar values in it at all?

Thanks,
Daniel

**Comment by sootythebear** [comment]
So there is no `orch` state in between the reactor and the final state; I wish the state to run on the Salt Master itself.

**Comment by jvrahav** [comment]
Any resolution on this. I have also run into this issue where there are many minions triggering the reactor process. randomly i get this error stating the pillar is not available.however the minion id is set as pillar. Following are relevant lines from salt master log

`2019-03-12 12:34:57,210 [salt.utils.event                                                                   :739 ][DEBUG   ][25] Sending event: tag = salt/run/20190312123457148188/new; data = {'jid': '20190312123457148188', 'fun': 'runner.state.orchestrate', 'user': 'Reactor', '_stamp': '2019-03-12T12:34:57.210425', 'fun_args': ['orch.install_configure_collectd', {'pillar': OrderedDict([('minion', '0aab2768-f8a2-4a37-9367-27415dd30f33-109')]), 'pillarenv': None, 'test': None, 'pillar_enc': None, 'orchestration_jid': None, 'exclude': None, 'saltenv': 'base'}]}
2019-03-12 12:35:31,564 [salt.utils.event                                                                   :739 ][DEBUG   ][25] Sending event: tag = salt/run/20190312123457148188/ret; data = {'success': False, 'jid': '20190312123457148188', 'fun': 'runner.state.orchestrate', 'user': 'Reactor', 'return': {'retcode': 1, 'outputter': 'highstate', 'data': {'be1c8c9af94d_master': ["Rendering SLS 'base:orch.install_configure_collectd' failed: Jinja variable 'salt.pillar object' has no attribute 'minion'"]}}, '_stamp': '2019-03-12T12:35:31.564567', 'fun_args': ['orch.install_configure_collectd', {'pillar': OrderedDict([('minion', '0aab2768-f8a2-4a37-9367-27415dd30f33-109')]), 'pillarenv': None, 'test': None, 'pillar_enc': None, 'orchestration_jid': None, 'exclude': None, 'saltenv': 'base'}]}`
