### ISSUE TITLE
virt.purge deletes attached ISO DVD images

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#46747]
### Description of Issue/Question

Running the virt.purge function on a libvirt guest prunes the all disk images, including the cdrom/dvd ISO images the user surely wants to reuse. Removing the cdrom devices should be an option defaulting to false.

I haven't checked so far what happens if the device attached to the cdrom is not an ISO but a physical device... surely a "funny" behavior trying to remove /dev/sr0.

### Setup

Setup a virtual machine on a QEMU minion and attach a ISO to the cdrom.

### Steps to Reproduce Issue

Just run `salt virt.purge myguest` and see the ISOs being removed. 

### Versions Report

    Salt Version:
           Salt: 2016.11.4
    Dependency Versions:
           cffi: 1.5.2
           cherrypy: 3.6.0
           dateutil: 2.4.2
           docker-py: Not Installed
           gitdb: Not Installed
           gitpython: Not Installed
           ioflo: Not Installed
           Jinja2: 2.8
           libgit2: 0.24.0
           libnacl: Not Installed
           M2Crypto: 0.21.1
           Mako: Not Installed
           msgpack-pure: Not Installed
           msgpack-python: 0.4.6
           mysql-python: Not Installed
           pycparser: 2.10
           pycrypto: 2.6.1
           pycryptodome: Not Installed
           pygit2: 0.24.0
           Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
           python-gnupg: Not Installed
           PyYAML: 3.10
           PyZMQ: 14.0.0
           RAET: Not Installed
           smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.2.1
           ZMQ: 4.0.4
    System Versions:
           dist: SuSE 12 x86_64
           machine: x86_64
           release: 4.4.21-69-default
           system: Linux
           version: SUSE Linux Enterprise Server  12 x86_64

**Comment by cbosdo** [comment]
Solution:
 * Output a boolean property `cdrom` for each disk in `get_disks()`
 * Filter out the disks based on that property in `purge()`

**Comment by gtmanfred** [comment]
Seems reasonable to add a keyword argument that defaults to True for now, for deleting the disks, and then deprecate it and switch it in two version releases.

https://docs.saltstack.com/en/latest/topics/development/deprecations.html
https://docs.saltstack.com/en/latest/topics/development/contributing.html

A PR would be greatly appreciated.

Thanks,
Daniel

**Comment by cbosdo** [comment]
@gtmanfred yep, will do as soon as I finished something else here

**Comment by cbosdo** [comment]
Can be closed now that the code is merged
