### ISSUE TITLE
workaround for salt-ssh hanging on one host while sending salt_states.tgz over scp

### ISSUE THREAD

**Issue by chrisxaustin** [saltstack/salt#46761]
### Description of Issue/Question

I'm using salt-ssh to manage 60ish devices on customer networks.
Most work fine, but one has an unreliable network and running it w/ debug enabled shows that it hangs while copying the salt_state.tgz over w/ scp.
To scp to that box I need to use the `-l` flag to limit the bandwidth used, e.g. `-l 5000`.

I've reviewed the salt-ssh documentation, some of the source code, and the ssh_config man page, but haven't found a way to include scp options.

The ability to configure this behaviour in the salt roster would make my life much easier.
This could be in the form of an scp options setting, or a bandwidth limit option if that's preferred.

### Steps to Reproduce Issue
Difficult to reproduce unless you have an unreliable network to work with.

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-108-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
This would be great to have.  

It should be really easy to just add an `scp_options` to the salt-ssh and then have that be able to be added in the _cmd_str function here.

https://github.com/saltstack/salt/blob/2017.7/salt/client/ssh/shell.py#L258

```
if ssh == 'scp' and self.scp_options:
    command.append(self.scp_options)
```

Or something like that, it would be a little more work and would need to be documented.

I am marking this as a feature request.

Thanks,
Daniel
