### ISSUE TITLE
[Feature Request] inline slot functions (expressions)

### ISSUE THREAD

**Issue by srkunze** [saltstack/salt#46771]
based on the observation here: #46516

Salt already provides 1000s of useful standard functions and modules. I actually would want to reuse all of them as slots.

However, as soon as they return something which I cannot use directly, e.g. because it's a dict (like **user.info**), I need to write a whole custom function for a thing such as small as a attribute access.

It would be great if salt provides a way to do inline slot functions in jinja templates, to enable this:

```
__slot__:user.info(user_name).home:
  ...
```

Syntax-wise maybe the colon could be a separator to signify the end of the expression.

**Comment by gtmanfred** [comment]
@DmitryKuzmenko when you have a second can you take a look at this?

Thanks,
Daniel

**Comment by DmitryKuzmenko** [comment]
@srkunze I'm not sure what do you mean saying "in jinja templates"? Templates are rendered earlier. Slots are executed right before the state execution. Slots are the last step.

If you just want to use a slot value as a part of state value like you've described in #46516: technically it's possible we just should update the syntax declaration and the slots parser.
@thatch45 what do you think?

**Comment by srkunze** [comment]
@DmitryKuzmenko I said jinja template because that's where I would use slots. 🙂

**Comment by guettli** [comment]
@DmitryKuzmenko are there any reason making `__salt__` availlable in slots (without writing a custom function) is a bad idea? 

I personally like the syntax of the first comment of this issue.

**Comment by DmitryKuzmenko** [comment]
I agree this feature proposal looks interesting and useful.

**Comment by mchugh19** [comment]
To update on this, the requested functionality was implemented in Neon. 
`__slot__:salt:user.info("root").home` should work as desired

**Comment by srkunze** [comment]
Nice!
