### ISSUE TITLE
Group name error when primary group has no name

### ISSUE THREAD

**Issue by ksofa2** [saltstack/salt#46781]
### Description of Issue/Question

If the user's primary group doesn't have a name (only a gid), a CRITICAL message is created.

### Setup
Followed [Installing Salt for Development](https://docs.saltstack.com/en/latest/topics/development/hacking.html) instructions on my MacBook Pro (macOS 10.13.3). 

My user's primary group has a gid, but no name (some side effect of my employer's OS management process).

### Steps to Reproduce Issue

Run `salt-master` or `salt-minion` . Get a CRITICAL message with following traceback as below...

```
[CRITICAL] Failed to load grains defined in grain file minion_process.grains in function <function grains at 0x107650ed8>, error:
Traceback (most recent call last):
  File "/Users/steinhof/src/salt/salt/loader.py", line 756, in grains
    ret = funcs[key]()
  File "/Users/steinhof/src/salt/salt/grains/minion_process.py", line 74, in grains
    'groupname': _groupname(),
  File "/Users/steinhof/src/salt/salt/grains/minion_process.py", line 60, in _groupname
    groupname = grp.getgrgid(os.getgid()).gr_name
KeyError: 'getgrgid(): gid not found: 123'
```

### Versions Report
Salt Version:
           Salt: 2018.3.0-242-g95be4e4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Mar 15 2018, 11:04:49)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 17.4.0
         system: Darwin
        version: 10.13.3 x86_64

**Comment by Ch3LL** [comment]
Thanks for the PR! As this fixes this issue I will go ahead and close this issue but please let me know if we need to re-open. :)

**Comment by ksofa2** [comment]
Thanks!

If I'm planning a PR for something simple like this, should I bother with the issue, or is the PR (with details about the bug) sufficient?
