### ISSUE TITLE
Vault auth mountpoit is not customizable

### ISSUE THREAD

**Issue by Albibek** [saltstack/salt#46793]
### Description of Issue/Question
Vault allows alternate path for auth mountpoint, that also can contain slash. 
Example:
`vault auth enable -path=test-approle/subpath approle`

In that case authentication to Vault should be done via
`v1/auth/test-approle/subpath/login`

In Salt's Vault module[ this value is hardcoded](https://github.com/saltstack/salt/blob
/7f326c0c17725a65bc7802f7f9f49a4c1278c3ad/salt/utils/vault.py#L109)
(the `/approle/`) part is the one that should be changeable.

The proposal is to make  this an option.

**Comment by Ch3LL** [comment]
Sounds reasonable. Please feel free to take a stab at a PR for this if you can :)
