### ISSUE TITLE
Add User for CherryPy REST API?

### ISSUE THREAD

**Issue by agardnerIT** [saltstack/salt#46810]
### Description of Question
Trying to add a user for CherryPy. I'm following the guide [here](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html).

I'm trying to get the `salt-api` working with CherryPy.

I've created my self-signed SSL key with `salt-call --local tls.create_self_signed_cert`

I've added my external_auth configuration to /etc/salt/master

    external_auth:
      pam:
        myuser:
          - .*
According to docs, this gives `myuser` permission to run all modules on the minions.

I've also added this to /etc/salt/master:

    rest_cherrypy:
      port: 8000
      ssl_crt: /etc/pki/tls/certs/localhost.crt
      ssl_key: /etc/pki/tls/certs/localhost.key

I can successfully connect to https://localhost:8000/login but my question is, how do I add `myuser` and specify a password? How does `salt-api` know about `myuser`?

The docs aren't clear on how I add a user and specify a password.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

root@saltstack-master:/etc/salt# salt-api --version
salt-api 2017.7.4 (Nitrogen)

root@saltstack-master:/etc/salt# salt --version
salt 2017.7.4 (Nitrogen)

root@saltstack-minion:~# salt-minion --version
salt-minion 2017.7.4 (Nitrogen)

root@saltstack-master:/etc/salt# salt --versions-report
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by agardnerIT** [comment]
Thanks, so here's what I've done now:

    useradd myuser
    passwd myuser

    nano /etc/salt/master
    # set to:
    external_auth:
      pam:
        myuser:
        - .*

    service salt-master stop
    service salt-api stop
    service salt-master start
    service salt-api start

Now following the guide...

    curl -sSk https://localhost:8000/login \
    -H 'Accept: application/x-yaml' \
    -d username=myuser \
    -d password=password \
    -d eauth=auto

And I get a 401:
   
    < body>
        < h2>401 Unauthorized</h2>
        < p>Could not authenticate using provided credentials</p>

**Comment by gtmanfred** [comment]
try 

```
-d eauth=pam
```

**Comment by agardnerIT** [comment]
That fixed it. Created a PR if you think it's relevant to change docs. Thanks.
