### ISSUE TITLE
unresolved merge conflict cause by ed46ce3c746b9c9bba77240ad4a9a39cd3a11aad

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#46860]
### Description of Issue/Question
There seems to be unresolved merge conflicts cause by ed46ce3c746b9c9bba77240ad4a9a39cd3a11aad

e.g. https://github.com/saltstack/salt/blob/develop/salt/modules/zpool.py#L350
There might be more but I noticed that the tests for this on develop were failing today.

cc: @rallytime as you did the merge

**Comment by rallytime** [comment]
Thanks for the heads up @sjorge - this snuck in during a merge forward. I'll get that fixed right up!

**Comment by rallytime** [comment]
Fixed in #46866
