### ISSUE TITLE
[RESOLVED] Invalid network setting -- Setting: hostname, Expected: [server1.example.com]

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#46885]
### Description of Issue/Question
We just migrated from 2017.2 to 2018.3 (master and minion) and we have a problem on RH7.

It works fine with RH 6.X, with all versions of salt, even the last 2018.3.

We are not sure if it is a RH 7.4 problem or a salt one.
We are still investigating.

###Solution
in /etc/sysconfig/network the variable HOSTNAME= was not defined.
we though it was /etc/hostname which were used by salt: this was well defined.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

LXC/LXD containers
tested with:

minion:
  2018.3
  2017.7.4
  2017.7.2

  Redhat 7.4

master:
  2018.3
  2017.7.4

### Steps to Reproduce Issue
We have a state:

system:
  network.system:
    - enabled: true
    - nozeroconf: True
    - order: 4
    - gateway: {{ salt['pillar.get']('network:gateway') }}

we do not specify hostname. But we never did.

state.apply won't work:

2018-04-05 10:46:58,150 [salt.state       :1762][INFO    ][10552] Running state [system] at time 10:46:58.149995
2018-04-05 10:46:58,150 [salt.state       :1795][INFO    ][10552] Executing state network.system for [system]
2018-04-05 10:46:58,151 [salt.loaded.int.module.rh_ip:920 ][ERROR   ][10552] Invalid network setting -- Setting: hostname, Expected: [server1.example.com]
2018-04-05 10:46:58,151 [salt.state       :292 ][ERROR   ][10552] Invalid network setting -- Setting: hostname, Expected: [server1.example.com]
2018-04-05 10:46:58,152 [salt.state       :1943][INFO    ][10552] Completed state [system] at time 10:46:58.152263 (duration_in_ms=2.268)

### Versions Report

Minion:
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.4 Maipo
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

master:
Salt Version:
           Salt: 2018.3.0 && 2017.7.4 && 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
Based on the update to the issue title, this appears to be resolved.  Is that the case?

**Comment by gaetanquentin** [comment]
yes

but maybe it would be fine to add in the  doc that network.system hostname default value (when not set)  is not    the /etc/hostname value  but  /etc/sysconfig/network:HOSTNAME one.

**Comment by mruepp** [comment]
Hi, AFAIK with 2018.3.2 this is not resolved. I am not able to skip the hostname key in the state. The state will not run if hostname is not set.
