### ISSUE TITLE
Cron.file - source file not found

### ISSUE THREAD

**Issue by SynPrime** [saltstack/salt#46881]
### Description of Issue/Question

Getting an error, when I try to run cron.file function. The source file isn't found.
The file is present at base/cron/starscream/root = salt://cron/starscream/root

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

```
root_crontab:
  cron.file:
    - name: salt://cron/starscream/root
    - user: root
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

`salt-call state.apply cron.starscream`

```
[ERROR   ] Source file salt://cron/starscream/root not found
local:
----------
          ID: root_crontab
    Function: cron.file
        Name: salt://cron/starscream/root
      Result: False
     Comment: Source file salt://cron/starscream/root not found
     Started: 03:57:06.065633
    Duration: 498.876 ms
     Changes:

Summary for local
------------
Succeeded: 0
Failed:    1
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

**Comment by garethgreenaway** [comment]
@SynPrime Thanks for the report.  Are your state files stored under `/srv/salt/` on the Salt master?  Have you changed the default file roots at all?

**Comment by SynPrime** [comment]
@garethgreenaway Thanks for your reply.

My salt files are stored under `/srv/salt/` and I haven't changed the default file roots.

If I call the function _file.managed_, salt can find the source file (the crontab file) without any problems.

**Comment by garethgreenaway** [comment]
@SynPrime Something to try.  In the state file can you change the past to include `base`?
```
root_crontab:
  cron.file:
    - name: salt://base/cron/starscream/root
    - user: root
```

**Comment by SynPrime** [comment]
@garethgreenaway Sorry, this isn't working.

I configured my file roots as follows:

`/etc/salt/master`:

```
file_roots:
  base:
    - /srv/salt
```

In `/srv/salt/cron/starscream` is the crontab file `root` (full path: `/srv/salt/cron/starscream/root`)

So, the state file should look like this:
```
root_crontab:
  cron.file:
    - name: salt://cron/starscream/root
    - user: root
```
Am I wrong?

If I call the function _file.managed_ with this path, the source file is found.

**Comment by garethgreenaway** [comment]
@SynPrime Apologies.  I misread the first comment and thought your Salt files were under /srv/salt/base.  You are correct and the file should be under accessible via salt://cron/starscream/root.  Will mark this as a bug and we'll get it fixed asap.  Thanks!

**Comment by SynPrime** [comment]
Sorry for my first confusing comment. Thank you very much.
