### ISSUE TITLE
2018.3 release breaks ext_nodes.py

### ISSUE THREAD

**Issue by eric-anderton-at-sony** [saltstack/salt#46897]
### Description of Issue/Question

SaltStack ext_nodes for support for Cobbler/Foreman style Top data is broken in the 2018.3 release.

I've traced the problem to this commit, where a refactoring placed a closed-paren in the wrong place:

https://github.com/saltstack/salt/commit/002aa88a97ed8a1c51f4ab1c965d22d064ea30a8#diff-af4b598dfcb7c851b2d98b54785a8c08R83

```
+    ndata = salt.utils.yaml.safe_load(
+        subprocess.Popen(
+            cmd,
+            shell=True,
+            stdout=subprocess.PIPE.communicate()[0])
+    )
```
Python complains that `PIPE` is an integer instead of an object with the attribute `commmunicate`.  The line should read something like `stdout=subprocess.PIPE).communicate()[0]` instead.

### Setup
In the master config, set `master_tops:ext_nodes` to reference a command that prints a Cobbler-style yaml structure:

/etc/salt/master:
```
master_tops:
  ext_nodes: /usr/local/bin/ext_nodes_test.sh
```
/usr/local/bin/ext_nodes_test.sh:
```
#!/bin/bash
# script will take one argument for the hostname - this is discarded for test purposes
echo '---'
echo 'classes: []'  #  maps to host states for Top
echo 'parameters: {}'  # maps to host Pillars
echo 'environment: base'  # maps to salt environment
```
... and `chmod 777 /usr/local/bin/ext_nodes_test.sh` so the salt master can execute the script.

### Steps to Reproduce Issue
Use the steps provided above, and attempt to gather Top data for any host (e.g. run `state.highstate`).

### Versions Report
I've since repaired my system and lost the broken version of the software.  This should apply to all Salt versions that have the linked commit above, which is at least in the 2018.3.0 release.  https://github.com/saltstack/salt/commit/002aa88a97ed8a1c51f4ab1c965d22d064ea30a8

**Comment by gtmanfred** [comment]
This is being fixed in 2018.3.1

https://github.com/saltstack/salt/pull/46872

**Comment by gtmanfred** [comment]
And tests have been added so this won't be missed again.

Thanks for reporting!
Daniel

**Comment by eric-anderton-at-sony** [comment]
My pleasure.  I'm glad the team is on it.  And thanks for the rapid response!
