### ISSUE TITLE
salt-cloud copies all master config options when using make_master

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#46904]
When using `make_master` in a map file it copies all of the default configs from the master that salt-cloud is installed onto the master it builds. To show an example:

```
linode_cent7:
  - ch3ll-master-py2:
      make_master: True
  - ch3ll-minion-1
```

And when the master is built it has a ton of master config options such as 

```
key_pass: null
pillarenv: null
winrepo_remotes_ng:
- https://github.com/saltstack/salt-winrepo-ng.git
winrepo_ssl_verify: true
winrepo_user: ''
worker_floscript: /home/ch3ll/git/salt/salt/daemons/flo/worker.flo
worker_threads: 5
zmq_backlog: 1000
zmq_filtering: false
zmq_monitor: false
```

Can we only set the minimum amount of configuration options there instead of copying everything?

ping @saltstack/team-windows  what do you think?

**Comment by Ch3LL** [comment]
sorry i meant @saltstack/team-cloud

**Comment by gtmanfred** [comment]
We do the same thing here as we do for minions, if no master: dict is specified, then we dump the default MASTER_OPTS dictionary into the /etc/salt/master file, this is how it works on the minion as well.

If you specify master: {}, it shouldn't drop anything i don't think?
