### ISSUE TITLE
Redis cache error

### ISSUE THREAD

**Issue by huynhnangit** [saltstack/salt#46916]
### Description of Issue/Question
I found an bug when use redis for caching, i don't know it is bug or not, but i think i should let your know :)
Sorry my english not good.

So i changed the code in line 346 to: log.debug('Setting the value for %s under %s (%s)', key, bank, redis_key)
And the error not show.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
2018-04-06 10:00:49,502 [/usr/lib/python2.7/site-packages/salt/cache/redis_cache.pyc:300 ][DEBUG   ][11055] Adding 10-90-32-39 to $BANK_minions
2018-04-06 10:00:49,503 [salt.master      :1783][ERROR   ][11055] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1776, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1487, in _pillar
    'pillar': data})
  File "/usr/lib/python2.7/site-packages/salt/cache/__init__.py", line 156, in store
    return self.modules[fun](bank, key, data, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/salt/cache/redis_cache.py", line 346, in store
    log.debug(
  File "/usr/lib64/python2.7/logging/__init__.py", line 1137, in debug
    self._log(DEBUG, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'redis_key'

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 1.5
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 2.1.9
          ioflo: 1.7.4
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: 0.1.3
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.18
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: 0.6.8
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 4.15.7-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Ch3LL** [comment]
@huynhnangit thanks for finding this :). would you mind submitting a PR for that fix?

**Comment by huynhnangit** [comment]
@Ch3LL i don't know how to do it, can you do it for me :)

**Comment by Ch3LL** [comment]
Yep fixed in https://github.com/saltstack/salt/pull/46989 :) thanks for opening an issue :)

**Comment by rallytime** [comment]
Closed via #46989
