### ISSUE TITLE
Minion disconnecting from master and not restoring connection

### ISSUE THREAD

**Issue by beybol** [saltstack/salt#46914]
### Description of Issue/Question
I have one master and 3 minions. Two of them are fine but the third is all the time disconnecting from the master. Only restarting salt-minion service helps and restores connection.

### Setup
All systems are Ubuntu 16.4 hosted in Azure and are up to date.
The only difference between minions is that the one disconnecting is communicating with master over a public network (IP) while those two working fine are in the same LAN as master.
Turning on ping interval:
ping_interval: 1
doesn't solve the problem.

### Steps to Reproduce Issue
every minute debug log:
2018-04-05 23:33:59,459 [salt.transport.zeromq][DEBUG   ][2916] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'tVM-proxy', 'tcp://xx.yy.zz.ww:4506', 'aes')
2018-04-05 23:33:59,460 [salt.crypt       ][DEBUG   ][2916] Initializing new SAuth for ('/etc/salt/pki/minion', 'tVM-proxy', 'tcp://xx.yy.zz.ww:4506')
2018-04-05 23:34:59,459 [salt.transport.zeromq][DEBUG   ][2916] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'tVM-proxy', 'tcp://xx.yy.zz.ww:4506', 'aes')
2018-04-05 23:34:59,460 [salt.crypt       ][DEBUG   ][2916] Initializing new SAuth for ('/etc/salt/pki/minion', 'tVM-proxy', 'tcp://xx.yy.zz.ww:4506')

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Master:
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-1012-azure
         system: Linux
        version: Ubuntu 16.04 xenial

Minions:
Salt Version:
           Salt: 2015.8.8

Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: Not Installed

System Versions:
           dist: Ubuntu 16.04 xenial
        machine: x86_64
        release: 4.13.0-1012-azure
         system: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
you can try `ping_interval` as discussed here: https://github.com/saltstack/salt/issues/45052#issuecomment-367022712

Also  i noticed your minion is a very old version: ` 2015.8.8` which is no longer supported so might be worth it to upgrade the minion.

**Comment by beybol** [comment]
Hi,
I've updated minion to:
root@tVM-proxy:/home/beybol# salt-minion -V
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-1012-azure
         system: Linux
        version: Ubuntu 16.04 xenial

Didn't help :(

**Comment by Ch3LL** [comment]
and did you try ping_interval? as discussed in the other issue?

**Comment by beybol** [comment]
Yes, didn't help :(

**Comment by beybol** [comment]
I have 
ping_interval: 1
in /etc/stalt/minion

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud any ideas here with azure and a public network vs LAN?

**Comment by gtmanfred** [comment]
Is your server setup in one of these scenerios?

https://docs.microsoft.com/en-us/azure/load-balancer/load-balancer-outbound-connections#scenarios

**Comment by beybol** [comment]
There is no load balancer in my setup.
Both servers (master and minion) have LAN IP and are translated to public IP's.
Is there any setup for minion allowing to automatically reconnect it to master if the connection is broken?

**Comment by gtmanfred** [comment]
https://docs.saltstack.com/en/latest/ref/configuration/minion.html#keepalive-settings

There are some tcp keepalive settings that can be tuned for zeromq on the minion

**Comment by beybol** [comment]
Looks like it solved problem
Case closed
