### ISSUE TITLE
Non-ASCII files fail with Jinja templating, without Jinja variables being non-ASCII

### ISSUE THREAD

**Issue by icks** [saltstack/salt#46910]
### Description of Issue/Question
Whenever non-ASCII files are used with the state module `file.managed` with Jinja rendering, `state.highstate` and `state.apply` fails hard. The Jinja/pillar variables themselves do **not** need to be in a non-ASCII format.

I first thought it was #6287, but then noticed that the non-ASCII character that breaks saltstack was inside the config file itself and not the pillar data.

### Setup
I have some a file `config.yaml` that is managed in the following way:
```
/config.yaml:
  file.managed:
    - source: salt://config.yaml.j2
    - template: jinja
```

And `salt://config.yaml.j2` has the following content:
```
umlauts:
  - ä
  - ö
  - ü
jinja: {{ nothing_relevant }}
```

### Steps to Reproduce Issue

Using the setup above in a masterless setup causes an error like this:
```
root@host # salt-call state.highstate
local:
----------
          ID: [...]
    Function: file.managed
      Result: False
     Comment: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 178, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "/usr/lib/python2.7/dist-packages/salt/utils/templates.py", line 409, in render_jinja_tmpl
                  log.debug("TmplStr: {0}".format(tmplstr))
              UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 809: ordinal not in range(128)
     Started: 20:51:06.160906
    Duration: 91.349 ms
     Changes:  
```

The character producing the error is the German umlaut `ä` (`\xe4`). When the following is removed from the demo `.sls` file above, the highstate finishes without errors (apart from not actually using Jinja templating):

```
    - template: jinja
```

### Versions Report
Masterless setup on Debian 9:
```
# salt-call --versions-report                                                                                                                                                
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

**Comment by garethgreenaway** [comment]
@icks Thanks for the report.  Prior to the release of 2018.3, a lot of unicode related things were known to be broken.  In the 2018.3 release there was a major effort to ensure that unicode was better supported.

**Comment by icks** [comment]
@garethgreenaway Sorry for taking your time and thanks for hinting me to the current version. Using the new version from the [SaltStack Package Repo for Debian](https://repo.saltstack.com/#debian) it works without any flaws.

**Comment by garethgreenaway** [comment]
@icks No worries!  Glad the issue is resolved!
