### ISSUE TITLE
orchestrate runner does not process jinja correctly

### ISSUE THREAD

**Issue by jan--f** [saltstack/salt#46920]
### Description of Issue/Question
In an orchestration file I have something like this:
```
{% set foo = salt['cmd.shell']('shellcmd to get some info') %}

set option {{ foo }}:
  salt.function:
    - name: cmd.run
    - tgt: minion
    - arg:
      - another shell call set {{ foo }}
```

When I check this using ```state.show_sls``` the correct yaml is generated. However when I run this using ```state.orch``` the state described above is run with ```foo``` resolving to an empty string. This then of course runs the wrong command.

This minion log prints the failures when running the command:
```
2018-04-05 16:33:13,537 [salt.loader.admin.int.module.cmdmod][ERROR   ][888852] Command 'another shell call set  ' failed with return code: 22
```
The command expects another parameter that ```{{ foo }}``` should have added.

### Versions Report
salt --versions-report
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 4.4.120-94.17-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by Ch3LL** [comment]
any chance you can share the cmd you are running? The jinja looks correct to me.
