### ISSUE TITLE
Upgrade to 2018.3 no exception if deprecated cmd.run arg "user" gets used

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#46927]
### Description of Issue/Question

We upgraded to 2018.3

My team mates wasted a lot of time to find why things don't work like before.

The reason was found: `cmd.run` swallows the "user" argument.

It would be very nice if there would be an exception of you supply an invalid argument.

Do you need a pull request, or do you want to make this one-line patch yourself?

**Comment by Ch3LL** [comment]
what one line patch are you proposing @guettli
