### ISSUE TITLE
Upgrade to 2018.3.0 : pki repository is void 

### ISSUE THREAD

**Issue by tonthon** [saltstack/salt#46921]
### Description of Issue/Question
I upgraded from 2016.11.2 to 2018.3.0.
The /etc/salt/pki/ directory was totally reset. The master key changed and there was no minion key left.
I had to
1- remove /etc/salt/pki/minion_master.pub on all minions
2- restart salt-minion service
3- Accept minion keys again

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Master is installed on a Debian buster/sid.
I used the following repositoty 
deb http://repo.saltstack.com/apt/debian/9/amd64/latest stretch main

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
1- Install a salt-master 2016.11.2
2- Connect a minion
3- upgrade the salt-master to the 2018.3.0 version
4- Run salt-key -L (no minion appears)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Minions are under several salt-minion versions going from 2016.11.2 to 2018.3.0

Salt Master 

Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: 0.7.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.0.4
 
System Versions:
           dist: debian buster/sid 
         locale: UTF-8
        machine: x86_64
        release: 3.14-2-amd64
         system: Linux
        version: debian buster/sid

**Comment by Ch3LL** [comment]
@tonthon i cannot replicate this. might be a duplicate of https://github.com/saltstack/salt/issues/46868 ?
