### ISSUE TITLE
Salt not reading Azure subscription ID?

### ISSUE THREAD

**Issue by esell** [saltstack/salt#46935]
### Description of Issue/Question

I am trying to simply list the available images and/or deploy a VM to Azure using the `azurearm` driver but am running into the following error (snipped):

```
  [ERROR   ] Failed to get the output of 'azurearm.avail_images()': Parameter 'subscription_id' must be str.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 874, in image_list
    data[alias][driver] = self.clouds[fun]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 381, in avail_images
    compconn = get_conn(client_type='compute')
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 323, in get_conn
    client_type=client_type, **conn_kwargs
  File "/usr/lib/python2.7/dist-packages/salt/utils/azurearm.py", line 176, in get_client
    base_url=cloud_env.endpoints.resource_manager,
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/compute_management_client.py", line 75, in __init__
    self.config = ComputeManagementClientConfiguration(credentials, subscription_id, base_url)
  File "/usr/local/lib/python2.7/dist-packages/azure/mgmt/compute/compute_management_client.py", line 41, in __init__
    raise TypeError("Parameter 'subscription_id' must be str.")
TypeError: Parameter 'subscription_id' must be str.
[DEBUG   ] LazyLoaded nested.output
azure:
    ----------
```

### Setup
My `/etc/salt/cloud.providers.d/azure.conf` looks like:

```
azure:
  driver: azurearm
  master: salt
  subscription_id: my_sub_id
  client_id: my_client_id
  secret: my_client_secret
  tenant: my_tenant_id
  location: westus
  resource_group: saltFun
  network: salt-Fun-vnet
```

### Steps to Reproduce Issue
* Install dev version of salt using bootstrap.sh script (`sh bootstrap-salt.sh -L -M -N git develop`)
* create `/etc/salt/cloud.providers.d/azure.conf`
* run `salt-cloud -l debug --list-images azure`

I did try the various quote tricks on the values in the config file, none of which seemed to do anything.

### Versions Report

Salt Version:
           Salt: 2018.3.0-300-ged8e94a

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-1012-azure
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by esell** [comment]
Ok, so I found the issue. It looks like the Azure client wants a byte string but salt is sending a UTF encoded string. I'll play around with what I hope is a simple fix and submit a PR.

**Comment by Ch3LL** [comment]
Thanks for the PR! I will close this issue as it resolves the issue but please let me know if i need to re-open :)

**Comment by cskowronnek** [comment]
Your change was for the develop branch. I can't find the file or the part of code in the 2018.3.0 release. Could you take a look where to change it in the stable release?

**Comment by esell** [comment]
@cskowronnek it looks like the `salt/utils/azurearm.py` did not exist until commit 1f1a9962edab9d4c023b1232109dd21a0985e9bd so that is probably why you were not able to find it.
