### ISSUE TITLE
Beacons documentation update for 2018.3

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#46938]
In the release notes for 2018.3.0, it lists [Beacon Configuration Changes](https://docs.saltstack.com/en/latest/topics/releases/2018.3.0.html#beacon-configuration-changes), but the documentation at https://docs.saltstack.com/en/latest/topics/beacons/ does not appear to reflect the new syntax.

**Comment by Ch3LL** [comment]
ping @garethgreenaway i think you did a lot of work here. mind taking a look here?

**Comment by edlane** [comment]
We just ran into this same issue...

A breaking change like this needs to also be updated in the current documentation for those attempting to implement beacons in the current released version of Salt.

**Comment by garethgreenaway** [comment]
@Ch3LL On it.
