### ISSUE TITLE
grains.filter_by does not use default parameter when using salt-ssh

### ISSUE THREAD

**Issue by ixs** [saltstack/salt#46948]
### Description of Issue/Question
The epel-formula at https://github.com/saltstack-formulas/epel-formula/blob/d31fa81901b406a407baa0688119f9c266e3b942/epel/map.jinja uses grains.filter_by to select the right epel repository parameters, depending on the operating system installed.

Specifically, filter_by is used with the grain parameter pointing to 'os', to differentiate between 'RedHat' and 'Amazon' Linux.
The default parameter is used to have operating systems like CentOS or SCL use the RedHat lookup_dict key.
Last the base parameter is pointing at the 'common' lookup_dict key to provide common defaults.

This is working fine when the epel state is included and the state is run via salt-call or salt.
When running via salt-ssh though, the state run errors with the following message:

    - Rendering SLS 'base:epel' failed: Jinja variable 'dict object' has no attribute 'key_name'

Modifying the epel statefile to print the context of the jinja variable that contains the result of the map file shows that _only_ the values of the 'common' key are provided. This would indicate that the default parameter has been disregarded.

### Setup
1. Import the epel-formula into /srv/formulas/epel-formula and add it to file_roots->base:
```
file_roots:
  base:
    - /srv/salt
    - /srv/formulas/epel-formula
```
2. For good measure, add a Saltfile in $HOME with the following content to ensure that the map.jinja file is really present in the thin-salt package used by salt-ssh (known Problem https://github.com/saltstack/salt/issues/26585):
```
salt-ssh:
  wipe: False
  ignore_host_keys: True
  extra_filerefs:
    - salt://epel/map.jinja
```

3. Ensure salt-ssh is working:
`salt-ssh <host> test.ping`

4. Ensure the epel formula is correctly installed and is callable.
`salt <host> state.apply epel test=True`

### Steps to Reproduce Issue
1. Run salt-ssh against <host>:
```
# salt-ssh host.example.com state.apply epel
[ERROR   ] Rendering exception occurred
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 169, in render_tmpl
    output = render_str(tmplstr, context, tmplpath)
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 390, in render_jinja_tmpl
    buf=tmplstr)
SaltRenderError: Jinja variable 'dict object' has no attribute 'key_name'
[CRITICAL] Rendering SLS 'base:epel' failed: Jinja variable 'dict object' has no attribute 'key_name'
host.example.com:
    - Rendering SLS 'base:epel' failed: Jinja variable 'dict object' has no attribute 'key_name'
```

2. To compare, run via remote salt-agent:
```
# salt host.example.com state.apply epel
host.example.com:
  Name: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7 - Function: file.managed - Result: Clean Started: - 20:35:02.494032 Duration: 169.441 ms
  Name: epel_release - Function: pkg.installed - Result: Clean Started: - 20:35:05.490056 Duration: 2191.504 ms
  Name: /etc/yum.repos.d/epel.repo - Function: file.replace - Result: Clean Started: - 20:35:07.683520 Duration: 114.042 ms
  Name: /etc/yum.repos.d/epel.repo - Function: file.replace - Result: Clean Started: - 20:35:07.799391 Duration: 101.293 ms
  Name: /etc/yum.repos.d/epel.repo - Function: file.replace - Result: Clean Started: - 20:35:07.901957 Duration: 98.785 ms
  Name: /etc/yum.repos.d/epel-testing.repo - Function: file.replace - Result: Clean Started: - 20:35:08.001852 Duration: 98.916 ms

Summary for host.example.com
------------
Succeeded: 6
Failed:    0
------------
Total states run:     6
Total run time:   2.774 s
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this but Im seeing it in 2017.7.5 as well. I feel like this should really be working. ping @saltstack/team-ssh is there some setting we might be missing here?

**Comment by ixs** [comment]
Problem still exists. Even with latest 2019.2.0.

**Comment by itscaro** [comment]
Still applies to 3001.3

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
