### ISSUE TITLE
state.apply with file.recurse fails with certain binary files

### ISSUE THREAD

**Issue by jtd330** [saltstack/salt#46949]
I am seeing an issue where using the test=True functionality for file.recurse does not work correctly when I add a binary file.  This is with an Ubuntu master and an Ubuntu minion on the same computer.  I tried this on the develop branch (commit 8a1f895f18f274eb1fc98e0482b7561eebcaf3cd
on 4/6/18) and on the latest release  #2018.3.0.

After adding this binary file, SaltStack barfs when trying to perform a diff against a file already present:

(virt) root@master-Z97X-Gaming-3:/saltd/virt# salt -c ./etc/salt 'salt-dev' state.apply UbuntuTest test=True
salt-dev:
----------
          ID: /SEP/StageSEP
    Function: file.recurse
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/saltd/virt/local/lib/python2.7/site-packages/salt/state.py", line 1924, in call
                  **cdata['kwargs'])
                File "/saltd/virt/local/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/saltd/virt/lib/python2.7/site-packages/salt/states/file.py", line 3572, in recurse
                  manage_file(dest, src, replace)
                File "/saltd/virt/lib/python2.7/site-packages/salt/states/file.py", line 3519, in manage_file
                  **pass_kwargs)
                File "/saltd/virt/lib/python2.7/site-packages/salt/states/file.py", line 2414, in managed
                  **kwargs
                File "/saltd/virt/lib/python2.7/site-packages/salt/modules/file.py", line 4727, in check_managed_changes
                  group, mode, attrs, saltenv, contents)
                File "/saltd/virt/lib/python2.7/site-packages/salt/modules/file.py", line 4818, in check_file_meta
                  sfn, name, template=True, show_filenames=False)
                File "/saltd/virt/lib/python2.7/site-packages/salt/modules/file.py", line 4977, in get_diff
                  for x in fp_.readlines()])
                File "/saltd/virt/local/lib/python2.7/site-packages/salt/utils/stringutils.py", line 118, in to_unicode
                  return _normalize(s.decode(__salt_system_encoding__, errors))
                File "/saltd/virt/lib/python2.7/encodings/utf_8.py", line 16, in decode
                  return codecs.utf_8_decode(input, errors, True)
              UnicodeDecodeError: 'utf8' codec can't decode byte 0x90 in position 2: invalid start byte
     Started: 14:35:39.426354
    Duration: 1738.122 ms
     Changes:   

Summary for salt-dev
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.738 s
ERROR: Minions returned with non-zero exit code
(virt) root@master-Z97X-Gaming-3:/saltd/virt# 

The following was my state file:

/SEP/StageSEP:
  file.recurse:
    - source: salt://SEP
    - user: master
    - group: master
    - file_mode:  '744'
    - dir_mode:   '2775'

Attempting to apply changes with test=False resulted in failed state and the file not being updated on the minion.

(virt) root@master-Z97X-Gaming-3:/saltd/virt# salt -c ./etc/salt 'salt-dev' state.apply UbuntuTest test=False
salt-dev:
----------
          ID: /SEP/StageSEP
    Function: file.recurse
      Result: False
     Comment: #### /SEP/StageSEP/bin/SEP.exe ####
              Unable to manage file: 'utf8' codec can't decode byte 0x90 in position 2: invalid start byte
     Started: 14:37:34.826475
    Duration: 7064.927 ms
     Changes:   

Summary for salt-dev
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   7.065 s
ERROR: Minions returned with non-zero exit code
(virt) root@master-Z97X-Gaming-3:/saltd/virt# 

Here are the versions of the Ubuntu master develop branch:

(virt) root@master-Z97X-Gaming-3:/saltd/virt# salt -c ./etc/salt --versions
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-38-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
(virt) root@master-Z97X-Gaming-3:/saltd/virt#

**Comment by jtd330** [comment]
Also, I was not seeing this error on release 2017.7 for a Windows 10 minion and Ubuntu 16.04 master, and performed this exact test.

**Comment by jtd330** [comment]
I found that commenting out "_normalize(s.decode(__salt_system_encoding__, errors))" on line 119 in salt/utils/stringutils.py at line 111 and replacing with "return s" resolves the issue:

        elif isinstance(s, (str, bytearray)):
            if encoding:
                return _normalize(s.decode(encoding, errors))
            else:
                try:
                    # Try UTF-8 first
                    return _normalize(s.decode('utf-8', errors))
                except UnicodeDecodeError:
                    # Fall back to detected encoding
                    #_normalize(s.decode(__salt_system_encoding__, errors))
                    return s 
        raise TypeError('expected str or bytearray')

I don't think that is the correct fix.  It seems like what this code is trying to do is convert the string to unicode, but __salt_system_encoding__ is defined as utf8 and python 2 is throwing an exception trying to decode something inside the SEP.exe file.

**Comment by Ch3LL** [comment]
ping @terminalmage any help/ideas with @jtd330 's fix here?

**Comment by terminalmage** [comment]
@Ch3LL @jtd330 I think that https://github.com/saltstack/salt/pull/47061 should fix this.
