### ISSUE TITLE
zypper.py module does always a force refresh which is usually not needed

### ISSUE THREAD

**Issue by mansam-ger** [saltstack/salt#46954]
### Description of Issue/Question
the zypper module always forces the refresh of the zypper db. This is usually not needed as a databse refresh is always executed when new  packages are available. the --force paramtere causes the zypper db to be recreated even if not needed. 

here is an excerpt of man zypper:

     refresh (ref) [alias|name|#|URI]...
           Refresh repositories specified by their alias, name, number, or URI. If no repositories are specified, all enabled
           repositories will be refreshed.

           See also METADATA REFRESH POLICY section for more details.

           -f, --force
               Force a complete refresh of specified repositories. This option will cause both the download of raw metadata
               and parsing of the metadata to be forced even if everything indicates a refresh is not needed.

This can cause severe errors if executed regularly and causes Logs to grow huge.

### Setup
n.a.
### Steps to Reproduce Issue
n.a.

### Versions Report
all versions.

**Comment by Ch3LL** [comment]
ping @saltstack/team-suse can you look here?

**Comment by isbm** [comment]
What does it mean "not needed"? Is there a specific example where it is really not needed but Zypper module still puts it to the force? Because Zypper knows when it is needed, and where it is not.

**Comment by brejoc** [comment]
I've actually asked that myself last time skimming through the zypper module. Due to the docs the zypper module indeed forces a refresh in `list_upgrades`, `info_available`, `latest_version`, `upgrade_available`, `upgrade` (although that is probably needed), `download` (but that might be wrong) and `resolve_capabilities`.

**Comment by mansam-ger** [comment]
The --force switch is only needed in case of an error with the zypper database. In any other cases a zypper ref (without force) does it right. It does an update of the repo database only if needed and leaves it alone if nothing to to. A forced zypper ref generates alone about 2 MB of zypper.log every time it is executed.

@isbm not needed means that the database is dropped ven when no new packages are there.

**Comment by joesusecom** [comment]
Looks like we should fix this. I guess this has quite some impact on performance as well.

**Comment by mansam-ger** [comment]
@joesusecom This sounds great and would fix some serious issues we occured

**Comment by brejoc** [comment]
@mlandres What do you think about this? Can we get rid of the force as a default in those cases?

**Comment by isbm** [comment]
@brejoc the refactoring won't be simple here, as Zypper behaves very differently on various OS versions. In some cases (Tumbleweed) this is just performance drop, but in older versions like SLE11 it will be a necessity.

**Comment by mansam-ger** [comment]
I just checked on SLES 11 SP1 and SP3 and it seems, that it behaves exactly like on SLES12 SP1-SP3. I don't know how it behaved on SLES10 though. I still think that a complete forced rebuild of all metadate should not be the default.

**Comment by isbm** [comment]
@mansam-ger certainly we need to look at it, but there are inconsistencies we need to be careful of.
@mlandres Thoughts?

**Comment by brejoc** [comment]
Thanks for the clarification, @mlandres!

@isbm How about switching the default of this for >= SLE15. This way we wouldn't break anything in SLE11 and SLE12 but would benefit in the future. Maybe after that and if everything works as expected we could also see if we can change it for SLE12.

**Comment by brejoc** [comment]
@isbm yeah, that's clear. But I just had an other idea. Wouldn't it make more sense to check for the zypper instead of the SUSE version?

**Comment by isbm** [comment]
@brejoc I didn't said that. What I meant is that Zypper module for Salt at the moment cannot now verify the version of Zypper installed, neither can get its defaults that are specifically set in particular OS version. So this is not just "a simple fix"...

**Comment by joesusecom** [comment]
I wouldn't say the Zypper module _can_ not check for the version. It _does_ not. The check would be just a "zypper --version" away. :-)

But sure, the logic to determine which zypper versions actually behave different would have to be implemented one way or the other. Given that we sometimes update Zypper pretty aggressively even on older OS releases, checking for zypper (and maybe even giving zypper some "capability" info for major changes) would certainly be the safer bet.

**Comment by isbm** [comment]
Well yes, knowing bare zypper's version is no brainer. But that is not much of help. We also need to know what settings it has for its capabilities and thus know how it goes to behave on the particular platform.
