### ISSUE TITLE
salt py3 2018.3.0 sync files Chinese BUG:'gbk' codec can't decode

### ISSUE THREAD

**Issue by xiaopanggege** [saltstack/salt#46956]
## Description of Issue/Question
My salt-master version is py3.
The client system is Linux without problems.
There is a problem with the client system for Windows.
When I execute file.recurse , there are the following errors. :

```
Rendering SLS rsync_dir failed, render error: 'gbk' codec can't decode byte 0xad in position 29: illegal multibyte sequence
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\state.py", line 3397, in render_state
    rendered_sls=mods
  File "C:\salt\bin\lib\site-packages\salt\template.py", line 80, in compile_template
    render_pipe = template_shebang(template, renderers, default, blacklist, whitelist, input_data)
  File "C:\salt\bin\lib\site-packages\salt\template.py", line 170, in template_shebang
    line = salt.utils.stringutils.to_unicode(ifile.readline())
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 29: illegal multibyte sequence

```
This problem has always existed in all the Windows versions of salt, I hope this update will solve this problem in 2018.3.0, but the test finds that this bug still exists.

Before 2018.3.0 ,If the Windows installation is py3's salt-minion, I need to modify the following to solve the Chinese problem:
Edit C:\salt\bin\Lib\site-packages\salt\template.py
```
    in "def template_shebang" It's about 171-172 lines:
    Change "with salt.utils.fopen(template, 'r') as ifile" to "with salt.utils.fopen(template, 'rb') as ifile"
    and
    Change  "line = ifile.readline()" to  "line = ifile.readline().decode('utf8')"
```

In 2018.3.0:
`Change "with salt.utils.files.fopen(template, 'r') as ifile" to "with salt.utils.files.fopen(template, 'rb') as ifile"`

Now you can sync with Chinese or other files and directories that require utf8 encoding.

If the Windows installation is py2's salt-minion,I need to modify more configurations to fully support Chinese.

I hope the next version will use this modification to completely solve the Windows synchronization file coding problem.

## Setup

rsync_dir:
  file.recurse:
    - source: salt://{{pillar['source_path']}}?saltenv=svn
    - name: {{pillar['name_path']}}
    {% if grains['os']=='CentOS' %}
    - user: {{ pillar['user'] }}
    - group: {{ pillar['group'] }}
    {% endif %}
    - include_empty: True
    - clean: True
    - exclude_pat: E@\.svn($|/)
    - show_changes: False

 Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

## ` Versions Report`

Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.5 (default, Dec 11 2017, 14:22:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by xiaopanggege** [comment]
@damon-atkins  
The Windows version：Windows7、windows server 2008 R2 Enterprise。
You're right，I'm trying to 
`Change "with salt.utils.files.fopen(template, 'r') as ifile" to "with salt.utils.files.fopen(template, 'r',encoding='utf-8') as ifile"`
Problems also can be solved.

The reason for this problem is that the SLS file is written under Linux(my salt-master system). The default encoding of Linux on my side is utf8, and then the SLS file is transferred from Linux to Windows, and stored in C:\salt\var\cache\salt\minion\files\base\rsync_dir\init.sls,and his encoding is utf8.
so,version 2018.3.0 in salt/template.py
When  execute "with salt.utils.fopen(template, 'r') as ifile" in  "def template_shebang",in function salt.utils.files.fopen() include "kwargs['encoding'] = __salt_system_encoding__" ,This encoding is assigned to cp936 in Windows.cp936 = gbk .so  this error occurred using cp936 to decode utf8 files.

I find it can only change C:\salt\bin\Lib\site-packages\salt\utils\files.py 
in function fopen()
about 361 line 
change
kwargs['encoding'] = __salt_system_encoding__
to
kwargs['encoding'] = __salt_system_encoding__
if salt.utils.platform.is_windows():
    kwargs['encoding'] = 'utf-8'"
Problems also can be solved.

But I don't know which method is better, because
```
if salt.utils.platform.is_windows():
    kwargs['encoding'] = 'utf-8'"
```
 this method will change the encoding of all files to utf-8 in Windows when use function fopen.

change C:\salt\bin\Lib\site-packages\salt\template.py only the SLS files are affected.

**Comment by damon-atkins** [comment]
The SLS files should be read as UTF-8 on every platform even if the `__salt_system_encoding__`  is not UTF-8  to prevent this problem its a bug with 2018.3.0

**Comment by damon-atkins** [comment]
.
