### ISSUE TITLE
2017.7 repo not returning salt-minion package

### ISSUE THREAD

**Issue by paul-mulvihill** [saltstack/salt#46961]
### Description of Issue/Question
the yum repo for 2017.7 doesn't appear to return the `salt-minion` package when doing a yum search or a yum install

### Setup
CentOS 7 server trying to install the latest 2017.7.* minion.

### Steps to Reproduce Issue
Take a CentOS 7 server
yum remove salt.noarch salt-minion.noarch salt-repo.noarch
yum install -y https://repo.saltstack.com/yum/redhat/salt-repo-2017.7-1.el7.noarch.rpm
yum search salt
results:
![image](https://user-images.githubusercontent.com/15688266/38503718-ac330176-3c0a-11e8-967c-361c8b27897f.png)

cat /etc/yum.repos.d/salt-2017.7.repo
[salt-2017.7]
name=SaltStack 2017.7 Release Channel for RHEL/Centos $releasever
baseurl=https://repo.saltstack.com/yum/redhat/7/$basearch/2017.7
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/saltstack-signing-key

Is something wrong with the repo. I've had the same results on two different servers.

**Comment by Ch3LL** [comment]
i'm having a hard time replicating. You can see this if you have a docker installed:

`docker run -it centos:7  /bin/bash -c "yum install https://repo.saltstack.com/yum/redhat/salt-repo-2017.7-1.el7.noarch.rpm -y; yum search salt-minion"`

and it returns salt-minion on the return of yum search salt-minion:
`salt-minion.noarch : Client component for Salt, a parallel remote execution system`

and you can see in the repo that salt-minion is available: https://repo.saltstack.com/yum/redhat/7/x86_64/2017.7/

Do you have multiple salt repo's possibly?

**Comment by paul-mulvihill** [comment]
Hi @Ch3LL 
Think i've tracked it down.. it was an unexpected behaviour of the yum lock packages feature.
it appears if you lock the version using yum. it removes any version that isn't that explicit version from the yum command.
So this is my fault. I'll have to stick with just locking the repo version instead for now.
thanks for the help

**Comment by Ch3LL** [comment]
no problem. Glad you got it figured out :)
