### ISSUE TITLE
Is there any equivalent to Ansible delegate_to in saltstack?

### ISSUE THREAD

**Issue by uzwal111** [saltstack/salt#46972]
### Description of Issue/Question
I want to use grains information of the minion and then use those grain values to copy some files to other host.Which can be done in Ansible using delegate_to.Like using "fqdn" grains value from minion and copying {{ fqdn }}.cfg on other host.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by garethgreenaway** [comment]
@uzwal111 Thanks for the report.  Based on the description above I think perhaps the Salt mine night accomplish what you want to do: https://docs.saltstack.com/en/latest/topics/mine/
You can use it to share information, such as grain information, between minions.

**Comment by uzwal111** [comment]
Thanks for your reply.I really didn't understand the salt mine documentation.Can you please post an example of a state which is passing the grains information from one minion to other minion.It will be helpful.

**Comment by junovitch** [comment]
@uzwal111, an example:
`/etc/salt/minion`
```
mine_functions:
  fqdn_ip4:
    - mine_function: grains.get
    - fqdn_ip4
```

With that on several minions run a `salt '*' mine.update` on your master.

Now on a minion I can run something like `salt-call mine.get '*' fqdn_ip4` to get the fqdn_ip4 grain of all other host that are exporting it as mine data. In a state file the the Jinja syntax is shown at the URL from earlier but it can be a bit busy looking so be sure to QA your state file syntax closely.

**Comment by jose1711** [comment]
from: https://tesonet.com/tips/automation-from-ansible-to-saltstack/
> Orchestration Runner – As I mentioned previously, Salt executes most of the work on the end host. As such, there’s no easy way to delegate tasks to a different host during a run (unless you allow minions to control each other – yes, there are options for this). An orchestrate runner is a special type of state execution module, where the state gets applied to the master, but the master can then trigger states on any other host in whatever order you wish. This really allows you to implement an equivalent of Ansible’s **delegate_to** parameter.
