### ISSUE TITLE
Copy/paste module refrences might not work because some might be virtualnames, and it's hard to tell.

### ISSUE THREAD

**Issue by damntoken** [saltstack/salt#46976]
### Copy/paste module refrences might not work because some might be virtualnames, and it's hard to tell.
Add this to top, the reist is same..

### Description of Issue/Question

Error with sls file: Reason: 'win_system.reboot' is not available.

salt win2016 sys.list_state_modules 'win_*'

    - win_dacl
    - win_dns_client
    - win_firewall
    - win_path
    - win_pki
    - win_servermanager
    - win_smtp_server
    - win_update

Im new to salt, and was amazed that it could kinda replace GPO and take over my windows stuff. But this list of "win_.." supported configuration options is kinda thin compared to what is listed on documentation.

I guess there is somekind of grain based lockdown for "features". If this is based on auto-tested "features" only allowed and broken not - cool - then it seems I have to wait. But I doubt because "shutdown" and reboot commands for windows have not changed for a long time.

But if it's bureucratic versioning mess, then this creates a recurring complication with future OS release adoption into salt managed systems - that makes me want to stick with abusing puppet.

Wouldnt an os/env grouped "this works/this brakes" reporting system for "features" at documentation be better - instead of removing the possibility for users to try untested "features"? 
Something like winehq.com has... a lot of windows programs/games/whatever can't run perfectly with wine, but it's ok - it's just important to let users gather what works and what brakes so other users can decide if something suits them or not.

### Setup
salt win2016  grains.items

    ----------
    SSDs:
    biosversion:
        Default System BIOS
    cpu_model:
        AMD Opteron(TM) Processor ####
    cpuarch:
        AMD64
    disks:
    domain:
        str
    fqdn:
        ##########
    fqdn_ip4:
        - 17#.########
    fqdn_ip6:
    gpus:
    groupname:
    host:
        abelia
    hwaddr_interfaces:
        ----------
        Xen PV Network Device #0:
            00:05:##:##:##:##
    id:
        abelia
    init:
        Windows
    ip4_interfaces:
        ----------
        Xen PV Network Device #0:
            - 17#.########
    ip6_interfaces:
        ----------
        Xen PV Network Device #0:
            - ####::####:####:####:####
    ip_interfaces:
        ----------
        Xen PV Network Device #0:
            - 17#.########
            - ####::####:####:####:####
    ipv4:
        - 172.17.1.110
    ipv6:
        - fe80::11ee:40f4:2727:6b41
    kernel:
        Windows
    kernelrelease:
        10.0.14393
    kernelversion:
        10.0.14393
    locale_info:
        ----------
        defaultencoding:
            cp1257
        defaultlanguage:
            #####
        detectedencoding:
            cp1257
    localhost:
        abelia
    manufacturer:
        Xen
    master:
        salt
    mem_total:
        9983
    motherboard:
        ----------
        productname:
            None
        serialnumber:
            None
    nodename:
        abelia
    num_cpus:
        6
    num_gpus:
        0
    os:
        Windows
    os_family:
        Windows
    osfinger:
        Windows-2016Server
    osfullname:
        Microsoft Windows Server 2016 Standard Evaluation
    osmanufacturer:
        Microsoft Corporation
    osrelease:
        2016Server
    osrelease_info:
        - 2016
    osservicepack:
        None
    osversion:
        10.0.14393
    path:
        C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\salt;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32
    pid:
        620
    productname:
        HVM domU
    ps:
        tasklist.exe
    pythonexecutable:
        c:\salt\bin\python.exe
    pythonpath:
        - c:\salt\bin\lib\site-packages\git\ext\gitdb
        - c:\salt\bin\Scripts
        - c:\salt\bin\python27.zip
        - c:\salt\bin\DLLs
        - c:\salt\bin\lib
        - c:\salt\bin\lib\plat-win
        - c:\salt\bin\lib\lib-tk
        - c:\salt\bin
        - c:\salt\bin\lib\site-packages
        - c:\salt\bin\lib\site-packages\win32
        - c:\salt\bin\lib\site-packages\win32\lib
        - c:\salt\bin\lib\site-packages\gitdb\ext\smmap
    pythonversion:
        - 2
        - 7
        - 14
        - final
        - 0
    saltpath:
        c:\salt\bin\lib\site-packages\salt
    saltversion:
        2018.3.0
    saltversioninfo:
        - 2018
        - 3
        - 0
        - 0
    serialnumber:
        #####
    server_id:
        ###1582###
    shell:
        C:\Windows\system32\cmd.exe
    timezone:
        #####
    username:
        #####A$
    virtual:
        Xen
    virtual_subtype:
        HVM domU
    windowsdomain:
        ###
    zfs_support:
        False
    zmqversion:
        4.1.6

### Steps to Reproduce Issue

Try using 'win_system.reboot' in sls file for Win Server 2016 Standard minion. 
Or check that this and many other are not avaliable with:
salt minion sys.list_state_modules 'win_*'

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by damntoken** [comment]
I tried extra steps in multiple orders, but nothing works.

```
salt win2016 saltutil.clear_cache
win2016:
    True
salt win2016 saltutil.refresh_modules
win2016:
    True
salt win2016 saltutil.clear_cache
win2016:
    True
salt win2016 saltutil.refresh_modules
win2016:
    True
salt win2016 saltutil.sync_all
salt win2016 sys.list_state_modules 'win_*'
win2016:
    - win_dacl
    - win_dns_client
    - win_firewall
    - win_iis
    - win_path
    - win_pki
    - win_servermanager
    - win_smtp_server
    - win_update
```

I reviewed the "win_system" code.. I hope i found the correct one.
https://github.com/saltstack/salt/blob/2018.3/salt/modules/win_system.py
I ran python from minion bin folder and ran import codes and then the check codes just work..
```
>>>
>>> salt.utils.platform.is_windows()
True
>>> HAS_WIN32NET_MODS
True
>>>
```
PS: I found this also 
https://github.com/saltstack/salt/blob/2018.3/salt/states/win_system.py
Tried same things.. "salt.utils.platform.is_windows()" returns True but I dont think I can test the weird "and .. computerdescription in __salt__" so robustly, i get "global name '__salt__' is not defined" which is expected.

I have ran salt minion in debug mode, and viewed it's log file. There are no hints on why win_system is not in sys.list_state_modules.

Please help me?

**Comment by gtmanfred** [comment]
Can you join the #windows channel on the Community Slack? Or IRC.

https://github.com/saltstack/salt#get-saltstack-support-and-help

or can @twangboy or @dwoz help here?

Thanks,
Daniel

**Comment by damntoken** [comment]
I digged more code at minion side.. C:\salt\bin\Lib\site-packages\salt\states\win_system 
(love the cleanness of python)

So I got "win_system" listed finally with the "salt minion sys.list_state_modules 'win_*'" command.
The "fix" was to comment out the line " __virtualname__ = 'system' ". Although now i understand that I should have called ".system" not ".win_system".

But this is not so obvious as I expected this list:
https://docs.saltstack.com/en/latest/ref/states/all/index.html
To match "salt minion sys.list_state_modules" command.. which would be as salt wants to be.. simple and direct. Though yes under the specific page after the huge headline "salt.states.win_system" there indeed is example codeblock with "system.computer_name: []" .. but i needed reboot, so I always scroolled down and copied "salt.states.win_system.reboot" to my code.

Case closed - lesson learned - problem solved for me. 

But I don't think such confusion for newcomers is only this module or windows specific and maybe it should be addressed.

So if module uses __virtualname__ = 'system'.. then the /ref/ webpage for this module also shows lines addresably as "salt.states.system.reboot" ?

**Comment by gtmanfred** [comment]
No, because the docs for each state should show that it is called `system`.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_system.html

```
ERIK-WORKSTATION:
  system.computer_name: []

This is Erik's computer, don't touch!:
  system.computer_desc: []
```

I am marking this as a documentation issue, because each module should have an example state in it to show how to use it.

**Comment by gtmanfred** [comment]
Here is more information about the virtualname.

https://docs.saltstack.com/en/latest/ref/modules/#virtualname

Unfortunately if we went by the same virtualname for all of them, then this would overwrite the

**Comment by damntoken** [comment]
Ah yes impossible to even generate the url... and link for menu.. I dont know then.

But to me it seems generall first thing to scroll long state /ref/ documentation.. like
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_system.html
Scroll to section needed (I needed reboot) and try to implement what is visible.. so visible should be callable code.. so only change inside final ref/states/all/salt.states.win_system.html page "win_system" -> "system" would be fine.. leave the first header as is.

**Comment by damntoken** [comment]
Sorry for close/open, misclick.. 
I'm not sure what could be done then to guide newbies from remaking such mistake over and over.
Mostly scrolling + copy/paste module refrences from /ref/ pages simply works because many dont use virtualnames.. and those which do, don't make it obvious if you just continue scroll down, check  parameters + copy/paste.

**Comment by pljoel** [comment]
+1 I made that mistake, it is not obvious at all. At least I found this thread to help me out!
