### ISSUE TITLE
States for running sql scripts

### ISSUE THREAD

**Issue by dara0418** [saltstack/salt#4697]
There's no states for running sql scripts. But in the deployment, most projects need to create the DB schema by running sql scripts.
Is it possible to add this state?

**Comment by pierluca** [comment]
I'm also interested if ever this feature were to be developed. We also have SQL migration scripts with an off-the-shelf solution for our main code base, but it'd be convenient to be able to run SQL scripts from Saltstack for one-off setups (e.g., create some views needed by a monitoring tool)

**Comment by thatch45** [comment]
does this not work?
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.mysql_query.html#module-salt.states.mysql_query

**Comment by pierluca** [comment]
Not in a PostgreSQL shop.

**Comment by thatch45** [comment]
Salt does have extensive PostgreSQL support:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.postgres.html
including many modules and states, so I suspect adding the ability to run a query would be easy. Also you could use the MySQL state as a starting point.

**Comment by pierluca** [comment]
Agreed, there's extensive PostgreSQL support and I've had great pleasure in working with it so far. 

However it's limited query-wise, as the psql_query command only accepts SELECT statements, and not everything can be done from within such a statement. I need to create a VIEW. I'd be happy to be proven wrong, but I don't see how to do that from within Salt.

Of course I could also develop my own thing, I just came across this issue and wanted to share a use case that may still be relevant. If you want the details, it involves deploying this:
https://github.com/wrouesnel/postgres_exporter (cf "Running as non-superuser")

**Comment by OrangeDog** [comment]
The tricky thing is how do you make the state stateful?
It's going to depend entirely on what the script does, and some SQL statements are intrinsically not stateful.
The only real solution is to write a custom state for whatever your specific case is.
This also lets you bypass `psql_query` and use `psql` (or a python driver) directly.

**Comment by darkn3rd** [comment]
I would be interested to send SQL queries to PostgresSQL, especially as the posgres modules are not working well, and do not have all features I need, such as setting search path.

There should be a an optionally to pass a second query that checks success/fail of the SQL statement.

**Comment by OrangeDog** [comment]
This feature is probably still wanted, but not obvious how to implement.

**Comment by darkn3rd** [comment]
I am still interested in this feature.  It would be great.

**Comment by dmurphy18** [comment]
@dara0418 Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue/feature request, which will have metrics in tracking issues.
