### ISSUE TITLE
file.managed not working with repeated gzipped file

### ISSUE THREAD

**Issue by superlinkx** [saltstack/salt#46978]
### Description of Issue/Question
This issue started around the release of 2018.3.0. When managing a database dump in gzipped format, I get the following error if the file had been previously added through the managed state: "Unable to manage file: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte". This happens regardless of if the file has changed or not changed since the last run. I'm using this in Vagrant to provision a copy of the database dump for additional operations, and it previously worked flawlessly.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I use a similar file.managed state as below:

file.managed:
    - name: '/usr/share/mysql-dump/dump-dbname.sql.gz'
    - makedirs: True
    - source: salt://mysql/dump-dbname.sql.gz
    - skip_verify: True

I don't see a reason why the file needs to be read. It should just get hashed to determine if it should be copied. The error does not occur if the file does not exist prior to running the state, but happens every time I run the state after the file is created.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run the above state.
Get error:  "Unable to manage file: 'utf8' codec can't decode byte 0x8b in position 1: invalid start byte"

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Running masterless through Vagrant config.
Minion reports:

Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@terminalmage Some potential fallout from the Unicode changes?

**Comment by terminalmage** [comment]
@garethgreenaway I think this has something to do with how file.managed attempts to get a diff of what was changed. It should be fixed with https://github.com/saltstack/salt/pull/47061.
