### ISSUE TITLE
MAC/OSX: Local salt commands function, but not from master

### ISSUE THREAD

**Issue by tcharette** [saltstack/salt#46988]
### Description of Issue/Question

When calling a salt command from the master (either targetting by the OS grain or by hostname strings) I have about 1/3rd of my macs that respond. However, if I ssh into these macs and run a salt-call manually it works. I've SOMEWHAT worked around it by scheduling highstates with the salt scheduling module, but this isn't quite ideal. 

The tricky part in all this is that a third of them DO work, and there doesn't seem to be any pattern to the whole thing. We're in the process of migrating all our macs to our new salt master (the old one is a huge mess) but the old one doesn't have this issue at all, even with a mixed OSX environment of 10.8.5 to 10.13+

We don't experience this issue at all with our 1000+ Centos 7.4 hosts. 

### Setup
All Macs connected to this salt master are high sierra, and I use brew to install salt in a setup script. They're all running 2017.7.4, as is the master. 

### Steps to Reproduce Issue
brew install saltstack
salt-minion -d 
do regular salt stuff. 

This is probably for another ticket, but I should include this little tidbit. I haven't used launchctl on our new macs, just brew. It seems using launchctl brings back an issue we had in the past, where the combination of salt on startup + active directory causes a spinning wheel of death and forces us to rebind the machine to AD. 

### Versions Report
Master:
[tristan@mtl-salt03 ~]$ salt --versions-report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
 

Thanks for the help. Loving salt so far, great work.

**Comment by garethgreenaway** [comment]
@tcharette Thanks for the report.  It sounds like perhaps the minions on the OS X machines aren't actually connecting to the master.  Are you able to run them manually with debugging to verify the connection is taking place?

**Comment by tcharette** [comment]
Hey Gareth,

The macs that don't respond to calls from the master ("Minion did not return") I'm able to ssh to, and run salt-calls no problem. It gets the latest code. 

I think this would be the relevant debug section: 

[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'wrk105d.rodeofx.com', 'tcp://192.168.64.168:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (7569)
[DEBUG   ] Setting zmq_reconnect_ivl to '7569ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'wrk105d.rodeofx.com', 'tcp://192.168.64.168:4506', 'clear')
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'wrk105d.rodeofx.com', 'tcp://192.168.64.168:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'wrk105d.rodeofx.com', 'tcp://192.168.64.168:4506')
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'wrk105d.rodeofx.com', 'tcp://192.168.64.168:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'wrk105d.rodeofx.com', 'tcp://192.168.64.168:4506')
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render

**Comment by tcharette** [comment]
Also, not sure if it's related but adding schedules doesn't seem to work in some cases.(When it's not a clean high sierra install, but an upgrade+xcode+salt upgrade) Maybe it has to do with python versions

[ERROR   ] Failed to add job base-schedule to schedule.
local:
----------
          ID: base-schedule
    Function: schedule.present
      Result: False
     Comment: Failed to add job base-schedule to schedule.
     Started: 14:49:18.062688
    Duration: 3029.588 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   3.030 s

base-schedule:
base-schedule:
  schedule.present:
    - enabled: True
    - function: state.highstate
    - when:
      - Monday 4:00am
      - Tuesday 4:00am
      - Wednesday 4:00am
      - Thursday 4:00am
      - Friday 4:00am
    - splay: 3600

**Comment by tcharette** [comment]
Sorry about confusing the issue, the schedule thing is probably a seperate ticket but just in case it's related I figure I should mention it. Upgrading to the latest salt minion(2017.4) resolved the schedule issue on most of my macs (The ones that were clean wipe+high sierra install) 

Also, I get this warning when running salt:
[WARNING ] /usr/local/Cellar/saltstack/2017.7.4_1/libexec/lib/python2.7/site-packages/salt/minion.py:653: DeprecationWarning: zmq.eventloop.ioloop is deprecated in pyzmq 17. pyzmq now works with default tornado and asyncio eventloops.
  io_loop = zmq.eventloop.ioloop.ZMQIOLoop()

**Comment by tcharette** [comment]
Still an issue with 2018
