### ISSUE TITLE
salt-cloud GCE full-query failing

### ISSUE THREAD

**Issue by bigbitbus** [saltstack/salt#46984]
### Description of Issue/Question
salt cloud's --full-query option is failing on GCE.

### Setup
Plain salt-cloud setup for GCE. The VM created is otherwise fully functional.

#### --full-query with -F fails

salt-cloud -F -l debug 
...
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Starting new HTTPS connection (1): www.googleapis.com
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/REDACTED/zones HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/REDACTED/regions HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/REDACTED/aggregated/instances HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/REDACTED/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
[DEBUG   ] LazyLoaded cloud.cache_node_list
[DEBUG   ] Failed to execute 'gce.list_nodes_full()' while querying for running nodes: can't serialize <GCEZone id="2231" name="us-east1-b" status="UP">
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2393, in run_parallel_map_providers_query
    cloud.clouds[data['fun']]()
  File "/usr/lib/python2.7/dist-packages/salt/cloud/libcloudfuncs.py", line 489, in list_nodes_full
    __utils__['cloud.cache_node_list'](ret, __active_provider_name__.split(':')[0], __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2902, in cache_node_list
    msgpack.dump(nodes[node], fh_, encoding=MSGPACK_ENCODING)
  File "/usr/lib/python2.7/dist-packages/msgpack/__init__.py", line 38, in pack
    stream.write(packer.pack(o))
  File "msgpack/_packer.pyx", line 223, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:223)
  File "msgpack/_packer.pyx", line 225, in msgpack._packer.Packer.pack (msgpack/_packer.cpp:225)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 184, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:184)
  File "msgpack/_packer.pyx", line 220, in msgpack._packer.Packer._pack (msgpack/_packer.cpp:220)
TypeError: can't serialize <GCEZone id="2231" name="us-east1-b" status="UP">
[DEBUG   ] LazyLoaded nested.output

############

#### Just --query works

salt-cloud --query -l debug
...
[DEBUG   ] The 'gce' cloud driver is unable to be optimized.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Starting new HTTPS connection (1): www.googleapis.com
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/REDACTED/zones HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/REDACTED/regions HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/REDACTED/aggregated/instances HTTP/1.1" 200 None
[DEBUG   ] https://www.googleapis.com:443 "GET /compute/v1/projects/REDACTED/aggregated/disks?maxResults=500 HTTP/1.1" 200 None
[DEBUG   ] LazyLoaded nested.output
gce-config:
    ----------
    gce:
        ----------
        sm:
            ----------
            id:
                639132680374040XXXX
            image:
                ubuntu-1604-xenial-v20180306
            name:
                sm
            private_ips:
                - P.Q.R.S
            public_ips:
                - A.B.C.D
            size:
                n1-standard-1
            state:
                RUNNING

### Versions Report

Salt Version:
            Salt: 2018.3.0-310-g133d098

Dependency Versions:
 Apache Libcloud: 2.3.0
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.4.2
       docker-py: Not Installed
           gitdb: 0.6.4
       gitpython: 1.0.1
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: 1.0.3
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.2.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: Ubuntu 16.04 xenial
          locale: UTF-8
         machine: x86_64
         release: 4.4.0-119-generic
          system: Linux
         version: Ubuntu 16.04 xenial

**Comment by bigbitbus** [comment]
Update on this - the same serialization bug seen in the error also shows up when a GCE instance is assigned an "external_ip" in a map file.

**Comment by lokimac** [comment]
This issue is a blocker for my use cases. Can confirm that I can not supply an external_ip and get the serialize error when I do. Is there a status on when this will be fixed? I've had to patch programs to use gcloud sdk instead of salt-cloud -- which feels dirty to me.
