### ISSUE TITLE
Napalm / Capirca Issue

### ISSUE THREAD

**Issue by prashanthtuttu** [saltstack/salt#47011]
### Description of Issue/Question
Attribute Error  "'_Term' object has no attribute 'priority'" when using netacl.load_term_config. 

below are the 2 issues referencing the same error.

Error 'netacl.load_filter_config' is not available. #46889
napalm/capirca issue #46918

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

my-filter:
    ----------
    my-term:
        ----------
        action:
            accept
        destination_address:
            any
        source_address:
            1.1.1.1

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

testdevice-ios:
----------
          ID: netacl_example
    Function: netacl.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1851, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1795, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/netacl.py", line 961, in managed
                  debug=debug)
                File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 430, in func_wrapper
                  return func(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/napalm_acl.py", line 844, in load_policy_config
                  revision_date_format=revision_date_format)
                File "/usr/lib/python2.7/dist-packages/salt/modules/capirca_acl.py", line 1178, in get_policy_config
                  merge_pillar=merge_pillar)
                File "/usr/lib/python2.7/dist-packages/salt/modules/capirca_acl.py", line 537, in _get_policy_object
                  **term_fields)
                File "/usr/lib/python2.7/dist-packages/salt/modules/capirca_acl.py", line 492, in _get_term_object
                  log.debug(str(term))
                File "/root/src/src/aclgen/lib/policy.py", line 731, in __str__
                  if self.priority:
              AttributeError: '_Term' object has no attribute 'priority'

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2017.7.3

Dependency Versions:
           cffi: 1.11.4
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-87-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
@mirceaulinic can you help with this?

Thanks,
Daniel

**Comment by mirceaulinic** [comment]
Hey @prashanthtuttu - I think this has been already solved via https://github.com/saltstack/salt/pull/44508 (although it's not clear to me why that bugfix was not accepted into a minor release). Please upgrade to 2018.3.0, or simply copy the module into your environment (i.e., https://github.com/saltstack/salt/blob/develop/salt/modules/capirca_acl.py into the `_modules` directory).

**Comment by gtmanfred** [comment]
I marked it to be backported to 2017.7, so it will hopefully be in 2017.7.6

**Comment by mirceaulinic** [comment]
Thanks @gtmanfred!

**Comment by prashanthtuttu** [comment]
@mirceaulinic - I copied the capirca module into _modules directory , but this time facing new error , below are the details , please refer to it.
salt 'testdevice-ios' netacl.load_filter_config my-filter pillar_key=netacl debug=True test=True
Error : 
testdevice-ios:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1493, in _thread_return
        return_data = executor.execute()
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 28, in execute
        return self.func(*self.args, **self.kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/utils/napalm.py", line 430, in func_wrapper
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/modules/napalm_acl.py", line 643, in load_filter_config
        filter_config = __salt__['capirca.get_filter_config'](platform,
      File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1114, in __getitem__
        func = super(LazyLoader, self).__getitem__(item)
      File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 101, in __getitem__
        raise KeyError(key)
    KeyError: 'capirca.get_filter_config'

Pillar File:
netacl:
  - my-filter:
      terms:
        - my-term:
            source_port: [1234, 1235]
            action: reject
        - my-other-term:
            source_port:
              - [5678, 5680]
            protocol: tcp
            action: acceptnetacl:
  - my-filter:
      terms:
        - my-term:
            source_port: [1234, 1235]
            action: reject
        - my-other-term:
            source_port:
              - [5678, 5680]
            protocol: tcp
            action: accept

**Comment by mirceaulinic** [comment]
Seems that you have a syntax error in your YAML Pillar:

```action: acceptnetacl:``` shouldn't have the trailing `:`.

**Comment by prashanthtuttu** [comment]
@mirceaulinic : Changed my pillar info as below and tried exeution, but still same error occurs.

testdevice-ios:
    ----------
    netacl:
        |_
          ----------
          my-filter:
              ----------
              terms:
                  |_
                    ----------
                    my-term:
                        ----------
                        action:
                            accept
                        destination_address:
                            2.2.2.2
                        source_address:
                            1.2.3.4

**Comment by prashanthtuttu** [comment]
netacl:
  - my-filter:
     terms:
       - my-term:
          source_address: 1.2.3.4
          destination_address: 2.2.2.2
          action: accept

**Comment by mirceaulinic** [comment]
It would probably help if you could use the Markdown syntax so we can see the exact structure you used (in the current form above, nobody can follow) - see https://guides.github.com/features/mastering-markdown/.

**Comment by prashanthtuttu** [comment]
@mirceaulinic Pls refer https://gist.github.com/prashanthtuttu/ae59945bdc5ba47853f2c4c9e09a6eb6

**Comment by prashanthtuttu** [comment]
@mirceaulinic - Pls find the output 

root@sc-net-salt-proxy-dev-01:~# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import aclgen
>>>

**Comment by prashanthtuttu** [comment]
root@sc-net-salt-proxy-dev-01:~# python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import aclgen
>>>

**Comment by prashanthtuttu** [comment]
@mirceaulinic - Attaching the result
https://gist.github.com/prashanthtuttu/80586187371273188b44946c65b95609
