### ISSUE TITLE
Difference between the onfail and onchanges requisites vs their new _any variants unclear

### ISSUE THREAD

**Issue by forty8bits** [saltstack/salt#47015]
While the value added from the `require_any` and `watch_any` requisites introduced in v2018.3.0 is clear and useful, and the documentation explains this well, it's unclear to me how the behaviour of `onfail_any` and `onchanges_any` is supposed to differ from the standard `onfail` and `onchanges` requisites?

From the docs on `onfail`, confirming it uses OR logic:
> Beginning in the 2016.11.0 release of Salt, onfail uses OR logic for multiple listed onfail requisites. Prior to the 2016.11.0 release, onfail used AND logic.

And for `onchanges`:
> If a state has multiple onchanges requisites then the state will trigger if any of the watched states changes.

Perhaps `onchanges` would fail if any of the states listed failed, whereas `onchanges_any` wouldn't? It would be nice to have these ambiguities cleared up in the docs.

**Comment by gtmanfred** [comment]
@garethgreenaway can you take a look at this to clarify the docs?

Thanks,
Daniel

**Comment by garethgreenaway** [comment]
Upon closer investigation it appears that `onfail_any` and `onfail` & `onchanges_any` and `onchanges` respectively perform the same function.  Since `onfail` and `onchanges` existed first, we should remove the `onfail_any` and `onchanges_any`.

**Comment by mattp-** [comment]
@garethgreenaway providing the inversion would be useful (onfail_all, onchanges_all)

**Comment by mattp-** [comment]
@forty8bits other than onfail and onchanges, every other requisite is implicitly AND, alongside _any for its OR equivalent (ie, the require_all you mentioned is already what require is), its implemented and released. we're just missing the AND for onchanges/onfail to complete the set of possible situations.
fwiw, it seems onfail originally WAS using AND, but was switched with https://github.com/saltstack/salt/issues/22370 . I'm going to take a look and see how easy it will be to revert that logic for onfail_all / onchanges_all

**Comment by forty8bits** [comment]
@mattp- I understand that, I just meant migrating all requisites to be fully qualified with `_all` and `_any` across the board would be nicely consistent and unambiguous.

**Comment by mattp-** [comment]
@forty8bits aye, agreed. i think its pretty trivial to create aliases; will try to keep that in mind when I find some tuits to look at this 👍

**Comment by baby-gnu** [comment]
Hello.

I think this should stay open.

Regards.
