### ISSUE TITLE
windows pkg.latest full_name issue 2018.3.0

### ISSUE THREAD

**Issue by jeremylarose** [saltstack/salt#47036]
### Description of Issue/Question
I haven't seen this with any other software yet, but if "Adobe Flash Player 29 PPAPI" or "Adobe Flash Player 29 NPAPI" is already installed on the system (ex: upgrading 29.0.0.113 to .140) and set as the "full_name" and pkg.latest is used in a state, it fails without downloading the pkg to the minion ("Package flash failed to update.").  If you change the full_name to anything else (ex: Adobe Flash Player 29 WHATEVER), it works.  Also, pkg.installed with version=latest works just fine, so i'm using that for flash right now.  This isn't a critcal issue, and I already have a work around, just bringing it up, since it affected every windows 10 or windows 7 machine I tried.

### Setup
repo flash.sls...
flash:
  '29.0.0.140':
    full_name: 'Adobe Flash Player 29 PPAPI'
    installer: 'salt://win/repo-ng/files/AdobeFlashPlayer-29.0.0.140.exe'
    uninstaller: 'salt://win/repo-ng/files/flash_remove.exe'
    msiexec: False
    locale: en_US
    reboot: False

state sls that DOESN'T work...
flash_update:
  pkg.latest:
    - name: flash
    - onlyif:
      - 'if not exist "%SYSTEMROOT%\{{ systemfolder }}\Macromed\Flash\FlashPlayerUpdateService.exe" MD; 2>NUL'

state sls that DOES work....
flash_update:
  pkg.installed:
    - name: flash
    - version: latest
    - onlyif:
      - 'if not exist "%SYSTEMROOT%\{{ systemfolder }}\Macromed\Flash\FlashPlayerUpdateService.exe" MD; 2>NUL'

### Steps to Reproduce Issue
state.apply debug output...

[INFO    ] Running state [flash] at time 12:23:34.898000
[INFO    ] Executing state pkg.latest for [flash]
[DEBUG   ] Could not LazyLoad pkg.mod_run_check: 'pkg.mod_run_check' is not available.
[INFO    ] Executing command 'if not exist "%SYSTEMROOT%\SysWOW64\Macromed\Flash\FlashPlayerUpdateService.exe" MD; 2>NUL
[DEBUG   ] output:
[DEBUG   ] Last command return code: 0
[DEBUG   ] Could not LazyLoad pkg.resolve_capabilities: 'pkg.resolve_capabilities' is not available.
[DEBUG   ] Using existing pkg metadata db for saltenv 'base' (age is 0:00:02.700737)
[DEBUG   ] Latest installed version of flash is 29.0.0.113
[DEBUG   ] Latest available version of package flash is 29.0.0.140
[DEBUG   ] Upgrade of flash from 29.0.0.113 to 29.0.0.140 is available
[DEBUG   ] Using existing pkg metadata db for saltenv 'base' (age is 0:00:02.759737)
[DEBUG   ] Could not LazyLoad pkg.normalize_name: 'pkg.normalize_name' is not available.
[DEBUG   ] Using existing pkg metadata db for saltenv 'base' (age is 0:00:02.821737)
**[DEBUG   ] A version (None) already installed for package flash**
[DEBUG   ] Using existing pkg metadata db for saltenv 'base' (age is 0:00:02.874737)
[ERROR   ] Package flash failed to update.

### Versions Report
minion
Salt Version:
           Salt: 2018.3.0
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.2
            ZMQ: 4.1.6
System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.15063  Multiprocessor Free

master... 
Salt Version:
           Salt: 2018.3.0
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-119-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by damon-atkins** [comment]
if you provide a version '29.0.0.140' latest checks the highest version is installed.  Should not need the onlyif.

pkg.installed with no version number will install the latest if no version is installed at all. And will never 
upgrade it or down grade it. Again should not need the onlyif.

If the software comes with a helper to perform self upgrades then you should use 'lastest' the flash.sls for the version string. 

uninstaller can be a local binary.

You will find this in the release notes which will dump some for information out for you see what is going on. Note salt itself does not use this code yet, but it prints a lot of useful information.
```
chcp 65001
c:\salt\bin\python.exe c:\salt\bin\lib\site-packages\salt\utils\pkg\win.py
c:\salt\bin\python.exe c:\salt\bin\lib\site-packages\salt\utils\pkg\win.py detail system
```
