### ISSUE TITLE
minion macOS High Sierra fails to connect to VirtualBox master

### ISSUE THREAD

**Issue by resolutecake** [saltstack/salt#47030]
### Description of Issue/Question
minion can authenticate successfully
- subsequent test.ping/manage.status/state.highstate fails
 Minion did not return. [Not connected]

this is suspect, I think:
"lsof" returncode = 1, likely no active TCP sessions.

- tried to use SSH forwarding instead: ssh -L…
- tried both brew and pip sources for minion
- the salt master works for its own minion
- and this setup worked a year ago

### Setup
minion is physical macOS High Sierra
master is Ubuntu VirtualBox
Network is NAT with Port Forwarding
(this setup used to work on older macOS and 17.04) 

### Steps to Reproduce Issue
**salt-minion -l debug**
(with master_alive_interval: 5)
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: c87
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "c87"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Master URI: tcp://127.0.0.1:1501
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'c87', u'tcp://127.0.0.1:1501')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (3622)
[DEBUG   ] Setting zmq_reconnect_ivl to '3622ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'c87', u'tcp://127.0.0.1:1501', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:1501
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:1501
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://127.0.0.1:500
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'c87', u'tcp://127.0.0.1:1501', u'aes')
[DEBUG   ] Re-using AsyncAuth for (u'/etc/salt/pki/minion', u'c87', u'tcp://127.0.0.1:1501')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:1501
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:1501
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Initializing new Schedule
[DEBUG   ] LazyLoaded timezone.get_offset
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {u'_stamp': '2018-04-12T07:39:07.412967', u'complete': True, u'schedule': {u'__mine_interval': {u'function': u'mine.update', u'return_job': False, u'enabled': True, u'jid_include': True, u'maxrunning': 2, u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] LazyLoaded mine.update
[INFO    ] Updating job settings for scheduled job: __mine_interval
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_add_complete; data = {u'_stamp': '2018-04-12T07:39:07.417312', u'complete': True, u'schedule': {u'__mine_interval': {u'function': u'mine.update', u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 2, u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[INFO    ] Added mine.update to scheduler
[INFO    ] Added new job __master_alive_127.0.0.1 to scheduler
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_add_complete; data = {u'_stamp': '2018-04-12T07:39:07.421014', u'complete': True, u'schedule': {u'__master_alive_127.0.0.1': {u'function': u'status.master', u'seconds': 5, u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 1, u'kwargs': {u'connected': True, u'master': u'127.0.0.1'}}, u'__mine_interval': {u'function': u'mine.update', u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 2, u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {u'_stamp': '2018-04-12T07:39:07.423788', u'complete': True, u'schedule': {u'__master_alive_127.0.0.1': {u'function': u'status.master', u'seconds': 5, u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 1, u'kwargs': {u'connected': True, u'master': u'127.0.0.1'}}, u'__mine_interval': {u'function': u'mine.update', u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 2, u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] Minion 'c87' trying to tune in
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'c87', u'tcp://127.0.0.1:1501', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'c87', u'tcp://127.0.0.1:1501')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:1501
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:1501
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'c87', u'tcp://127.0.0.1:1501', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'c87', u'tcp://127.0.0.1:1501')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:1501
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:1501
[INFO    ] Minion is ready to receive requests!
[DEBUG   ] Minion of '127.0.0.1' is handling event tag '/salt/minion/minion_schedule_delete_complete'
[DEBUG   ] Minion of '127.0.0.1' is handling event tag '/salt/minion/minion_schedule_add_complete'
[DEBUG   ] Minion of '127.0.0.1' is handling event tag '/salt/minion/minion_schedule_add_complete'
[DEBUG   ] Minion of '127.0.0.1' is handling event tag '/salt/minion/minion_schedule_delete_complete'
[DEBUG   ] LazyLoaded status.master
[INFO    ] Running scheduled job: __master_alive_127.0.0.1
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 1
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {u'fun_args': [], u'jid': u'20180412003913489024', u'schedule': u'__master_alive_127.0.0.1', u'pid': 12225, u'fun': u'status.master', u'id': u'c87'}
[DEBUG   ] LazyLoaded status.master
[DEBUG   ] LazyLoaded config.get
[WARNING ] "lsof" returncode = 1, likely no active TCP sessions.
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = __master_disconnected; data = {u'_stamp': '2018-04-12T07:39:13.618770', u'master': u'127.0.0.1'}
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20180412003913489024
[DEBUG   ] Minion of '127.0.0.1' is handling event tag '__master_disconnected'
[INFO    ] Connection to master 127.0.0.1 lost
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {u'_stamp': '2018-04-12T07:39:13.625890', u'complete': True, u'schedule': {u'__mine_interval': {u'function': u'mine.update', u'_next_scheduled_fire_time': datetime.datetime(2018, 4, 12, 1, 39, 13, 451766), u'name': u'__mine_interval', u'enabled': True, u'_splay': None, u'return_job': False, u'_seconds': 3600, u'jid_include': True, u'maxrunning': 2, u'_next_fire_time': datetime.datetime(2018, 4, 12, 1, 39, 8, 457198), u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] Persisting schedule
[DEBUG   ] Minion of '127.0.0.1' is handling event tag '/salt/minion/minion_schedule_delete_complete'
…

### Versions Report
salt-call --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Mar 22 2018, 14:43:05)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 17.5.0
         system: Darwin
        version: 10.13.4 x86_64

salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 23 2017, 22:06:14)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.10 artful
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-38-generic
         system: Linux
        version: Ubuntu 17.10 artful

**Comment by Ch3LL** [comment]
i'm not seeing anything that is glaring in that debug output. If you increase the timeout when running the command against the minion do you get a return. For example `salt 'minion' test.ping -t 100`? 

Also if you attach a remote linux minion does it work?

**Comment by resolutecake** [comment]
It works with bridged networking. But that's not available for Wi-Fi

[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: c87
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "c87"
[DEBUG   ] Created pidfile: /var/run/salt-minion.pid
[INFO    ] Starting up the Salt Minion
[DEBUG   ] AsyncEventPublisher PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] AsyncEventPublisher PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[INFO    ] Creating minion process manager
[DEBUG   ] Process Manager starting!
[DEBUG   ] Process Manager starting!
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] Master URI: tcp://192.168.1.71:501
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (8080)
[DEBUG   ] Setting zmq_reconnect_ivl to '8080ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.168.1.71:501
[DEBUG   ] Trying to connect to: tcp://192.168.1.71:501
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://192.168.1.71:500
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501', u'aes')
[DEBUG   ] Re-using AsyncAuth for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.168.1.71:501
[DEBUG   ] Trying to connect to: tcp://192.168.1.71:501
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Initializing new Schedule
[DEBUG   ] LazyLoaded timezone.get_offset
[DEBUG   ] LazyLoaded config.merge
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {u'_stamp': '2018-04-13T20:34:04.539354', u'complete': True, u'schedule': {u'__mine_interval': {u'function': u'mine.update', u'return_job': False, u'enabled': True, u'jid_include': True, u'maxrunning': 2, u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] LazyLoaded mine.update
[INFO    ] Updating job settings for scheduled job: __mine_interval
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_add_complete; data = {u'_stamp': '2018-04-13T20:34:04.543709', u'complete': True, u'schedule': {u'__mine_interval': {u'function': u'mine.update', u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 2, u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[INFO    ] Added mine.update to scheduler
[INFO    ] Added new job __master_alive_192.168.1.71 to scheduler
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_add_complete; data = {u'_stamp': '2018-04-13T20:34:04.547558', u'complete': True, u'schedule': {u'__master_alive_192.168.1.71': {u'function': u'status.master', u'seconds': 5, u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 1, u'kwargs': {u'connected': True, u'master': u'192.168.1.71'}}, u'__mine_interval': {u'function': u'mine.update', u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 2, u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {u'_stamp': '2018-04-13T20:34:04.550515', u'complete': True, u'schedule': {u'__master_alive_192.168.1.71': {u'function': u'status.master', u'seconds': 5, u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 1, u'kwargs': {u'connected': True, u'master': u'192.168.1.71'}}, u'__mine_interval': {u'function': u'mine.update', u'enabled': True, u'return_job': False, u'jid_include': True, u'maxrunning': 2, u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[INFO    ] Minion is starting as user 'root'
[DEBUG   ] Minion 'c87' trying to tune in
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.168.1.71:501
[DEBUG   ] Trying to connect to: tcp://192.168.1.71:501
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.168.1.71:501
[DEBUG   ] Trying to connect to: tcp://192.168.1.71:501
[INFO    ] Minion is ready to receive requests!
[DEBUG   ] Minion of '192.168.1.71' is handling event tag '/salt/minion/minion_schedule_delete_complete'
[DEBUG   ] Minion of '192.168.1.71' is handling event tag '/salt/minion/minion_schedule_add_complete'
[DEBUG   ] Minion of '192.168.1.71' is handling event tag '/salt/minion/minion_schedule_add_complete'
[DEBUG   ] Minion of '192.168.1.71' is handling event tag '/salt/minion/minion_schedule_delete_complete'

** ### HERE'S A SUCCESSFUL test.ping from MASTER ###*
[DEBUG   ] LazyLoaded status.master
[INFO    ] User sudo_root Executing command test.ping with jid 20180413133407485205
[DEBUG   ] Command details {u'tgt_type': u'glob', u'jid': u'20180413133407485205', u'tgt': u'c87', u'ret': u'', u'user': u'sudo_root', u'arg': [], u'fun': u'test.ping'}
[INFO    ] Starting a new job with PID 49005
[DEBUG   ] LazyLoaded test.ping
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] test.ping received for minion 'c87'
[DEBUG   ] Minion return retry timer set to 8 seconds (randomized)
[INFO    ] Returning information for job: 20180413133407485205


** ### AND HERE'S THE MINION PING ### **
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'c87', u'tcp://192.168.1.71:501')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.168.1.71:501
[DEBUG   ] Trying to connect to: tcp://192.168.1.71:501
[DEBUG   ] minion return: {u'fun_args': [], u'jid': u'20180413133407485205', u'return': True, u'retcode': 0, u'success': True, u'fun': u'test.ping'}
[INFO    ] Running scheduled job: __master_alive_192.168.1.71
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 1
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {u'fun_args': [], u'jid': u'20180413133410621464', u'schedule': u'__master_alive_192.168.1.71', u'pid': 49022, u'fun': u'status.master', u'id': u'c87'}
[DEBUG   ] LazyLoaded status.master
[DEBUG   ] LazyLoaded config.get
[WARNING ] "lsof" returncode = 1, likely no active TCP sessions.
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = __master_disconnected; data = {u'_stamp': '2018-04-13T20:34:10.721871', u'master': u'192.168.1.71'}
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20180413133410621464
[DEBUG   ] Minion of '192.168.1.71' is handling event tag '__master_disconnected'
[INFO    ] Connection to master 192.168.1.71 lost
[DEBUG   ] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_13636c5951_pub.ipc
[DEBUG   ] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/minion/minion_event_13636c5951_pull.ipc
[DEBUG   ] Sending event: tag = /salt/minion/minion_schedule_delete_complete; data = {u'_stamp': '2018-04-13T20:34:10.729314', u'complete': True, u'schedule': {u'__mine_interval': {u'function': u'mine.update', u'_next_scheduled_fire_time': datetime.datetime(2018, 4, 13, 14, 34, 10, 576914), u'name': u'__mine_interval', u'enabled': True, u'_splay': None, u'return_job': False, u'_seconds': 3600, u'jid_include': True, u'maxrunning': 2, u'_next_fire_time': datetime.datetime(2018, 4, 13, 14, 34, 5, 577955), u'minutes': 60}}}
[DEBUG   ] Persisting schedule
[DEBUG   ] Persisting schedule
[DEBUG   ] Minion of '192.168.1.71' is handling event tag '/salt/minion/minion_schedule_delete_complete'
[INFO    ] Running scheduled job: __master_alive_192.168.1.71
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 1
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {u'fun_args': [], u'jid': u'20180413133415614855', u'schedule': u'__master_alive_192.168.1.71', u'pid': 49042, u'fun': u'status.master', u'id': u'c87'}
[DEBUG   ] LazyLoaded status.master
[DEBUG   ] LazyLoaded config.get
[WARNING ] "lsof" returncode = 1, likely no active TCP sessions.
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20180413133415614855
[INFO    ] Running scheduled job: __master_alive_192.168.1.71
[DEBUG   ] schedule: This job was scheduled with jid_include, adding to cache (jid_include defaults to True)
[DEBUG   ] schedule: This job was scheduled with a max number of 1
[DEBUG   ] schedule.handle_func: adding this job to the jobcache with data {u'fun_args': [], u'jid': u'20180413133420606341', u'schedule': u'__master_alive_192.168.1.71', u'pid': 49061, u'fun': u'status.master', u'id': u'c87'}
[DEBUG   ] LazyLoaded status.master
[DEBUG   ] LazyLoaded config.get
[WARNING ] "lsof" returncode = 1, likely no active TCP sessions.
[DEBUG   ] schedule.handle_func: Removing /var/cache/salt/minion/proc/20180413133420606341

**Comment by resolutecake** [comment]
Could you look into why VirtualBox NAT networking no longer works for a Salt Master running inside VirtualBox?

Meanwhile I'll be on bridging, but that is not available for some network interfaces and is reliant on  external dhcp: troubles…

**Comment by resolutecake** [comment]
VirtualBox host-only network does not work either

**Comment by Ch3LL** [comment]
did you recently update salt? can you try an older version of salt and see if it doesn't work still?

**Comment by Annnetta** [comment]
Hi, I had exactly the same issue.

I am using physical MacOS High Sierra 10.13.5
Minion is on the Mac. Salt-minion version  is 2018.3.1

Master is on Debian 9 in VirtualBox, salt-master version is 2018.3.0
I am using Bridge adapter as network. The pings from Master to Minion and vise versa worked fine.

**What worked for me:**
On Mac, launch 

> salt-minoin start

here I had the error message:

```
[ERROR ] Error while bringing up minion for multi-master. Is master at 10.11.49.79 responding?
[CRITICAL] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2018.3.1, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
```


So
 - I updated Master to 2018.3.1
 - I deleted the file /etc/salt/pki/minion/minion_master.pub
 - Restarted the Master and the Minion

Now everything works fine.
