### ISSUE TITLE
pkg.installed should not auto-refresh without configuration

### ISSUE THREAD

**Issue by EvaSDK** [saltstack/salt#47079]
### Setup

I found myself updating a Gentoo LXC based setup recently which used to work fine but cannot be updated anymore with saltstack changes. Namely pkg.installed requires a refresh where it used not to.
I'm not sure of the exact last version that worked correctly, maybe it was 2015.5.3.
The particularity of this setup is that LXC containers have a read-only mount of the package database so as to minimize used disk space (~711MB).
Also pkg.refresh in Gentoo is not an operation that should be run too often, more than daily is discouraged as described in the documentation on mirrors: https://www.gentoo.org/support/rsync-mirrors/ and running it on each highstate certainly not in line with that.
Calls to `pkg.install` run just fine as they do not trying to refresh package database first.

### Steps to Reproduce Issue

* Create a Gentoo minion with read-only /usr/portage.
* Apply pkg.installed state.
* Observe salt-minion trying to eix-sync and fail.

### Versions Report

```
# salt-master --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.4
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.4.4
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 14 2018, 13:44:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.2.2
 
System Versions:
           dist: gentoo 2.4.1 
         locale: UTF-8
        machine: x86_64
        release: 4.14.31-gentoo
         system: Linux
        version: Gentoo Base System 2.4.1 
```

**Comment by EvaSDK** [comment]
I understand that for most distros out there, which are binary based, package database is low disk-space and refreshing it mostly low cost but this isn't true for Gentoo, its derivatives and friends. An option to control this behavior in a highstate run would be nice.

**Comment by gtmanfred** [comment]
If you set `refresh: False` on the pkg.installed state, does it still refresh your repos?

Here is the notes on the refresh option on pkg.installed.

```

param bool refresh:
--
  | This parameter controls whether or not the package repo database is updated prior to installing the requested package(s). If True, the package database will be refreshed (apt-get update or equivalent, depending on platform) before installing. If False, the package database will not be refreshed before installing. If unset, then Salt treats package database refreshes differently depending on whether or not a pkg state has been executed already during the current Salt run. Once a refresh has been performed in a pkg state, for the remainder of that Salt run no other refreshes will be performed for pkg states which do not explicitly set refresh to True. This prevents needless additional refreshes from slowing down the Salt run.
```

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed

**Comment by EvaSDK** [comment]
I have not tested, but the wording suggests that any call to pkg.installed that would not specify refresh would be a candidate to trigger the refresh. Since I use a couple of formulas, I didn't go this route yet. I'll give it a shot in a couple of hours and report.

**Comment by EvaSDK** [comment]
FTR, since last comment I converted my Gentoo minions to LXD images and disabled main-repository sync by default so it is much less of a problem for me. I haven't checked if salt updates did any change to this behavior.

**Comment by hasues** [comment]
I just stumbled on this issue while searching for some options.  I can confirm that this isn't an issue, and that by using `refresh: False` is the appropriate method for preventing portage to perform a `sync` when installing packages.

Example:
```
net-fs/nfs-utils:
  pkg.installed:
    - refresh: False
    - name: "net-fs/nfs-utils"
```
This should not be marked as a bug and it should be closed.
