### ISSUE TITLE
allow root volume tagging (aws ec2) in cloud map for salt-cloud

### ISSUE THREAD

**Issue by thetoolsmith** [saltstack/salt#47097]
Volume tagging can be set in cloud map as implemented in this change: https://github.com/saltstack/salt/issues/18451

However, tagging of root volume in the cloud map is not possible. 
I have tried a couple of different tests. 

1. duplicate the block_device_mappings volume config in the volumes: {} block. This creates two volumes and fails to attach one.
2. add tagging directly to the block_device_mappings block, no success here either.

In our automation we have to get return metadata from AWS, do an instance/root vol lookup and then add a tag. This is a lot of extra code to workaround.

**Comment by gtmanfred** [comment]
I am marking this as a feature request.

Daniel

**Comment by thetoolsmith** [comment]
thank you.
