### ISSUE TITLE
https://repo.saltstack.com/yum/redhat/7/ppc64le/latest/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found

### ISSUE THREAD

**Issue by nbari** [saltstack/salt#47093]
### Description of Issue/Question

How to install salt-minion on `ppc64-le` architecture 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

    sh  bootstrap-salt.sh 

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

    

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
We do not package for PowerPC, you will need to pip install the package using python.

**Comment by nbari** [comment]
hi @gtmanfred  currently trying: `pip install salt` but just prints `Collecting salt` and nothing else happens.

Any ideas?

**Comment by gtmanfred** [comment]
Sounds like it is collecting downloading the salt package from pip to install it.

**Comment by nbari** [comment]
Right, but not fetching nothing, just for testing did the same on a macOS and there is no progress

**Comment by nbari** [comment]
The issue was with https://status.python.org/incidents/1y1f44q6srh2
