### ISSUE TITLE
Failed to load ext_pillar reclass: Item in ``from list'' not a string

### ISSUE THREAD

**Issue by epcim** [saltstack/salt#47126]
### Description of Issue/Question
Usage of __future__.unicode_literals prevents python 2 user to use `from xyz import *` and related.

The issue is also described here: https://bugs.python.org/issue4128

Best-practice, recommendation what way to use with the old code to be both ways compatible? 

### Setup
Salt 2018.3 from stable and reclass (from gh:salt-formulas/reclass)

### Steps to Reproduce Issue
covered by https://bugs.python.org/issue4128

### Versions Report
```
root@cfg01:/usr/local/lib/python2.7/dist-packages/reclass# salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-15-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by garethgreenaway** [comment]
@epcim Thanks for the report.  Seems like this is an upstream issue.  Because of the recent Unicode works that went into 2018.3 we need unicode_literals.

**Comment by bbinet** [comment]
I also have the same issue "Failed to load ext_pillar reclass: Item in ``from list'' must be str, not unicode".
Any workaround to make reclass to work with 2018.3?

**Comment by bbinet** [comment]
@garethgreenaway When you say it is an upstream issue, you mean this should be fixed in reclass, not salt?

**Comment by mightybigcar** [comment]
The linked issue https://bugs.python.org/issue4128 is a 12 year old WONTFIX optimization issue for Python 2.6.  Do you have a correct link for this?  Thanks.

**Comment by bbinet** [comment]
@garethgreenaway any chance the upcoming 2018.3.1 release will fix this issue?

**Comment by epcim** [comment]
It's not just reclass ext_pillar what is affected, do we have any example fix from other PR to fix similar?

**Comment by max-arnold** [comment]
I made a fork of `reclass` which fixes this issue https://github.com/max-arnold/reclass/commits/maintenance and also ported reclass to Python 2.7/3.6.  This fix took less time than migration attempt to built-in `saltclass`.

Briefly tested this with Salt 2018.3.1, Python2.7/Python3.6 and existing reclass tree (~300 classes, ~70 nodes). Any feedback/bugs are appreciated.

**Comment by epcim** [comment]
Seems to me as fixed by this: https://github.com/salt-formulas/reclass/pull/49
(can someone confirm independently, that reclass on that branch is passing)

(way to force_install_reclass on any CI env: 
https://github.com/salt-formulas/salt-formulas-scripts/blob/master/bootstrap.sh#L407
```
export VERSION=develop
for s in $(python -c "import site; print(' '.join(site.getsitepackages()))"); do
          sudo -H pip install --install-option="--prefix=" --upgrade --force-reinstall -I \
            -t "$s" git+https://github.com/salt-formulas/reclass.git@${VERSION};
done
```

**Comment by epcim** [comment]
I think we may close. I can confirm 2018.3.1 works with salt-formulas/reclass (v1.5.4).

Original reclass also have got fix in Max fork https://github.com/max-arnold/reclass/commits/maintenance.
