### ISSUE TITLE
Backport to Salt 2018.3 of zfs support parsable output

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#47137]
### Description of Issue/Question
Backport to Salt 2018.3 of https://github.com/saltstack/salt/pull/46933

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by rallytime** [comment]
This is the work that needs to be done to fix #46903. Once this issue is done, we should be able to close #46903 as well.

**Comment by rallytime** [comment]
Closed via #47186
