### ISSUE TITLE
Wildcard support in service.status does not work for systemd instantiated services

### ISSUE THREAD

**Issue by Eelis** [saltstack/salt#47139]
### Description of Issue/Question

Salt 2018.3.0 added wildcard support to `service.status`, but it currently appears unable to find systemd [instantiated services](http://0pointer.de/blog/projects/instances.html).

### Steps to Reproduce Issue

1. start a systemd instantiated service (with a unit id like `myapp@bla.service`)
2. run `salt "*" service.status "myapp@bla"` and observe that the service is correctly reported to be running
3. run `salt "*" service.status "myapp*"` and observe that it only reports that the (non-existent) service `myapp@` is not running.

Example:

    root@groen:/# salt '*' service.status "myapp@bla"
    machine0:
        True
    root@groen:/# salt '*' service.status "myapp*"
    machine0:
        ----------
        myapp@:
            False

### Versions Report

Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.2
      gitpython: 2.1.5
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Sep 23 2017, 22:06:14)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.1
 
System Versions:
           dist: Ubuntu 17.10 artful
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.8.0-59-generic
         system: Linux
        version: Ubuntu 17.10 artful

**Comment by eliasp** [comment]
Did you try `myapp@*` instead of `myapp*`?

**Comment by garethgreenaway** [comment]
@Eelis Thanks for the report.  According to the documentation this looks like something that should be supported.

**Comment by dbellavista** [comment]
If it can help, executing `service.status myservice@*` with `-l debug` calls

`systemctl status myservice@.service` which is erroneous. The correct invocation should be
`systemctl status myservice@*`, so that systemctl can check the status for the dependent services.

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
