### ISSUE TITLE
Comments not allowed in reactor .sls files?

### ISSUE THREAD

**Issue by sgh1** [saltstack/salt#47157]
### Description of Issue/Question

I tried the reactor example here: https://codehammer.io/blog/post/saltstack-highstate-email-alerts/

It works as stated, but if I add this at the top of the file, it doesn't seem to work anymore:

\# Here is a comment

Not sure if that's stated in the docs, but I didn't see it. Maybe comments aren't advised in any .sls files, but I've been doing it for a while!

### Setup
See above.

### Steps to Reproduce Issue
See above.

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by garethgreenaway** [comment]
Because the SLS file is being interpreted by default as a Jinja template, you need to use Jinja comments.
`{# This is a comment #}`
http://jinja.pocoo.org/docs/2.10/templates/#comments
