### ISSUE TITLE
Documentation 404 page shows old releases

### ISSUE THREAD

**Issue by tighepatrick** [saltstack/salt#47179]
### Description of Issue/Question
On docs.saltstack.com, when hitting an invalid page, such as https://docs.saltstack.com/en/latest/foo a user will see old releases in the top right corner of the page.  2016.3.x is marked with the red checkmark, and 2015.8.x is the other version shown
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Browse to https://docs.saltstack.com/en/latest/foo

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
@UtahDave @rallytime @Ch3LL can yall take a look at this?

I assume it is somewhere on our docs page for specifying the versions on the 404 page.

**Comment by UtahDave** [comment]
@rallytime I think this might be the problem change:  https://github.com/saltstack/salt/commit/5b50eaf6b0b74f431f931c3e052632311eec72a1#diff-684a0ceb2878d48b19612ca360e277ef

A similar change was reverted in this PR:  https://github.com/saltstack/salt/commit/56b53c95e36656edda6c080012b9e684464cbba4#diff-684a0ceb2878d48b19612ca360e277ef

Is there a way to make sure this section doesn't get overwritten/changed again?

**Comment by rallytime** [comment]
@UtahDave Oh, usually that part conflicts when merging forward, so I usually catch it. But on develop, that's not the case. I am not sure how we can flag that better so I don't miss it in the future. I will think about it, but ideas are welcome!
