### ISSUE TITLE
Saltmaster Redis Cache incorrectly cut's mine data because of null character in grains

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#47188]
Running 2017.7.2 on Debian Jessie/8 

I was testing multimaster setup with 2 saltmaster nodes which should do Redis caching.
Idea was to use this shared mine to easily upgrade to Debian Sid/9.

Since there is no real documentation howto use it I was searching with intentionally search engine which show me various issues related to this type of cache which contains also a configuration / reference to the commment in saltstack... 

Important is to install additional Debian package ````python-redis```` and restart salt-master after setup a config like this:

````
# https://docs.saltstack.com/en/latest/topics/cache/index.html#pluggable-data-cache
# https://docs.saltstack.com/en/latest/ref/cache/all/salt.cache.redis_cache.html

cache: redis
cache.redis.host: salt-mine.xxxxxxx.0001.euc1.cache.amazonaws.com
cache.redis.port: 6379
cache.redis.db: '0'
#cache.redis.password: my pass
#cache.redis.bank_prefix: #BANK
#cache.redis.bank_keys_prefix: #BANKEYS
#cache.redis.key_prefix: #KEY
#cache.redis.separator: '@'
````

First problem (for other people interesting in setup such framework) ist that saltstack offers no real sync mechanism for the minion keys like here written:
https://docs.saltstack.com/en/latest/topics/tutorials/multimaster.html
My idea was to use the program / package ````unsion```` to setup a 2 way sync between the 2 salt master nodes.

**But I got stucked because the stored content in Redis isn't valid/complete.**

I use yet this EC2 grain addition to get easily needed information for the main instances:
https://github.com/saltstack/salt-contrib/blob/master/grains/ec2_info.py
and it's data is stored in the filesystem fine.
So I was wondering that the redis data was cutted nearly after this grain entry ````...<?>ec2?<?>````

Checking the file like /var/cache/salt/master/minions/<minion>/mine.p shows me that exact at this point a null character is written.
From code in ec2_info there is no implicit usage of null character so it seems that saltstack is storing null characters in it's backend as separator of multi-line/value responses between parameter and value in it's own mine value .

This storing fails to Redis because there the null character is the "real end" of a null-terminated string. :(
And Saltstack is pushing the data 1:1 without validation / replacing unwanted characters with other special chars (which should be best configurable I think).

**Comment by Ch3LL** [comment]
i'm having a hard time following where the exact issue is. Are you stating there is a null character being added due to the ec2 grain or a different grain? Any chance you can include steps on how to replicate this?

**Comment by Reiner030** [comment]
In my grains I see them only in ec2 grain but I have only a test.ping, network.address in front of ec2 grain setup.

Replicate of this error is done by adding https://github.com/saltstack/salt-contrib/blob/master/grains/ec2_info.py to the grains folder (/srv/salt/aws/_grains/ec2_info.py) so it should be possible to run: 
```
# salt-call grains.get ec2
local:
    ----------
    account_id:
        123456789012
    ami_id:
        ami-b58f1cda
...
    user-data:
    version:
        2017-09-30
```

To get data into the mine I use:
```
# cat /etc/salt/minion.d/95-mine.conf
mine_functions:
  network.interfaces: []
  test.ping: []
  network.ip_addrs:
    cidr: 172.16.0.0/12
    interface: eth0
  ec2:
   - mine_function: grains.get
   - ec2
```
and setup in first highstate a state which does equivalent of
```# salt-call mine.send ec2```

Here first part of my data file with little anonymized data and first three of 14 null characters (to catch better the lines with null character I wrote them additional on right-hand of table):
```
# hexdump -C /var/cache/salt/master/minions/salt-euc1-02/mine.p
00000000  86 b0 70 72 69 76 61 74  65 5f 69 70 5f 61 64 64  |..private_ip_add|
00000010  72 73 91 ac 31 37 32 2e  33 31 2e 31 37 2e 34 33  |rs..172.31.17.43|
00000020  a9 74 65 73 74 2e 70 69  6e 67 c3 b0 6e 65 74 77  |.test.ping..netw|
00000030  6f 72 6b 2e 69 70 5f 61  64 64 72 73 91 ac 31 37  |ork.ip_addrs..17|
00000040  32 2e 33 31 2e 31 37 2e  34 33 af 70 75 62 6c 69  |2.31.17.43.publi|
00000050  63 5f 69 70 5f 61 64 64  72 73 ac 35 32 2e xx xx  |c_ip_addrs.52.xx|
00000060  2e xx xx 2e xx xx xx a3  65 63 32 de 00 24 b1 61  |.xx.xxx.ec2..$.a|          00
00000070  76 61 69 6c 61 62 69 6c  69 74 79 5f 7a 6f 6e 65  |vailability_zone|
00000080  ad 65 75 2d 63 65 6e 74  72 61 6c 2d 31 61 ab 70  |.eu-central-1a.p|
00000090  75 62 6c 69 63 5f 69 70  76 34 ac 35 32 2e xx xx  |ublic_ipv4.52.xx|
000000a0  2e xx xx 2e xx xx xx aa  72 61 6d 64 69 73 6b 5f  |.xx.xxx.ramdisk_|
000000b0  69 64 c0 aa 6c 6f 63 61  6c 5f 69 70 76 34 ac 31  |id..local_ipv4.1|
000000c0  37 32 2e 33 31 2e 31 37  2e 34 33 b1 61 6d 69 5f  |72.31.17.43.ami_|
000000d0  6d 61 6e 69 66 65 73 74  5f 70 61 74 68 a9 28 75  |manifest_path.(u|
000000e0  6e 6b 6e 6f 77 6e 29 aa  70 72 69 76 61 74 65 5f  |nknown).private_|
000000f0  69 70 ac 31 37 32 2e 33  31 2e 31 37 2e 34 33 af  |ip.172.31.17.43.|
00000100  70 75 62 6c 69 63 5f 68  6f 73 74 6e 61 6d 65 da  |public_hostname.|
00000110  00 33 65 63 32 2d 35 32  2d xx xx 2d xx xx 2d xx  |.3ec2-52-xx-xx-x|   00
00000120  xx xx 2e 65 75 2d 63 65  6e 74 72 61 6c 2d 31 2e  |xx.eu-central-1.|
00000130  63 6f 6d 70 75 74 65 2e  61 6d 61 7a 6f 6e 61 77  |compute.amazonaw|
00000140  73 2e 63 6f 6d ae 72 65  73 65 72 76 61 74 69 6f  |s.com.reservatio|
00000150  6e 5f 69 64 b3 72 2d 30  38 66 37 30 xx xx xx xx  |n_id.r-08f70xxxx|
00000160  xx xx xx xx xx xx xx xx  af 73 65 63 75 72 69 74  |xxxxxxxx.securit|
00000170  79 5f 67 72 6f 75 70 73  bc 73 61 6c 74 6d 61 73  |y_groups.saltmas|
00000180  74 65 72 2d 70 75 62 6c  69 63 0a 73 73 68 2d 70  |ter-public.ssh-p|
00000190  75 62 6c 69 63 a3 69 61  6d 82 a4 69 6e 66 6f 84  |ublic.iam..info.|
000001a0  a4 63 6f 64 65 a7 53 75  63 63 65 73 73 b4 69 6e  |.code.Success.in|
000001b0  73 74 61 6e 63 65 5f 70  72 6f 66 69 6c 65 5f 61  |stance_profile_a|
000001c0  72 6e da 00 35 61 72 6e  3a 61 77 73 3a 69 61 6d  |rn..5arn:aws:iam|      00
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud any ideas here?

**Comment by gtmanfred** [comment]
I think the problem is the fact that redis does not allow storing newlines in simple strings.

```
RESP Simple Strings

Simple Strings are encoded in the following way: a plus character, followed by a string that cannot contain a CR or LF character (no newlines are allowed), terminated by CRLF (that is "\r\n").

Simple Strings are used to transmit non binary safe strings with minimal overhead. For example many Redis commands reply with just "OK" on success, that as a RESP Simple String is encoded with the following 5 bytes:

"+OK\r\n"

In order to send binary-safe strings, RESP Bulk Strings are used instead.

When Redis replies with a Simple String, a client library should return to the caller a string composed of the first character after the '+' up to the end of the string, excluding the final CRLF bytes.
```

And if you have a multiline string in the grains, that is causing the problem.

Can you verify if there are any multiline strings in the grains you are storing in the mine?

Thanks,
Daniel

**Comment by Reiner030** [comment]
The only thing I can do is referencing the code because I didn't know how saltstack pushes this data into redis but I could see as some months ago written that the result shows newlines in the binary cache file:

https://github.com/saltstack/salt-contrib/blob/master/grains/ec2_info.py#L60

````
53                line = _dash_to_snake_case(line)
54                try:
55                    data = json.loads(call_response_data)
56                    if isinstance(data, dict):
57                        data = _snake_caseify_dict(data)
58                    d[line] = data
59                except ValueError:
60                    if "\n" in call_response_data:
61                        d[line] = []
62                        for dline in call_response_data.split("\n"):
63                            d[line].append(dline)
64                    else:
65                        d[line] = call_response_data
66            else:
````

Myself I had done a workaround by using unison synchronisation between my old and new saltmaster instance (Debian Jessie -> Stretch) instead.

**Comment by Reiner030** [comment]
was this newline to null char exception fixed? I think not...

**Comment by sagetherage** [comment]
@Akm0d can you take this to @saltstack/team-cloud Working Group for follow up, please?
