### ISSUE TITLE
Using Hashicorp Vault - No such file or directory

### ISSUE THREAD

**Issue by ccoughle** [saltstack/salt#47183]
### Description of Issue/Question

I have set up an instance of Vault for testing integration with our salt-master.  I have set-up policies on the Vault server and using the generated tokens I can access my secrets there via the local command line as well as remotely from my salt-master via curl.  
However, no matter what I try I cannot get the salt processes themselves to communicate with the Vault instance correctly.  While I do not get permission denied, every connection attempt returns the error "No such file or directory"

Commands attempted and their output are below:  
=========================================================
salt-call pillar.items
local:
    ----------
    _errors:
        - Failed to load ext_pillar vault: [Errno 2] No such file or directory
    acb_pod:
.....
.....

=========================================================

salt-run sdb.get sdb://vault-test/secret/first
[ERROR   ] Failed to read secret! SSLError: [Errno 2] No such file or directory
Exception occurred in runner sdb.get: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/sdb.py", line 27, in get
    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
  File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 46, in sdb_get
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/sdb/vault.py", line 114, in get
    raise salt.exceptions.CommandExecutionError(e)
CommandExecutionError: [Errno 2] No such file or directory

=========================================================
salt-call sdb.get sdb://vault-test/secret/first
[ERROR   ] Failed to get token from master! Response is not a dict: Exception occurred in runner vault.generate_token: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
    'Token generation request for %s (impersonated by master: %s)'.
AttributeError: 'unicode' object has no attribute 'minion_id'

[ERROR   ] Failed to read secret! CommandExecutionError: Exception occurred in runner vault.generate_token: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
    'Token generation request for %s (impersonated by master: %s)'.
AttributeError: 'unicode' object has no attribute 'minion_id'

Error running 'sdb.get': Exception occurred in runner vault.generate_token: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/vault.py", line 43, in generate_token
    'Token generation request for %s (impersonated by master: %s)'.
AttributeError: 'unicode' object has no attribute 'minion_id'

=========================================================

curl -v     --header "X-Vault-Token: $VAULT_TOKEN"      -X GET http://vault-ccoughle.engrit.illinois.edu:8200/v1/secret/first

* About to connect() to <Vault-Server-Hostname> port 8200 (#0)
*   Trying 172.22.144.156...
* Connected to <Vault-Server-Hostname> (172.22.144.156) port 8200 (#0)
> GET /v1/secret/first HTTP/1.1
> User-Agent: curl/7.29.0
> Host: <Vault-Server-Hostname>:8200
> Accept: */*
> X-Vault-Token: 312cf098-dc3e-414d-e04d-5b00c1d31ad2
>
< HTTP/1.1 200 OK
< Cache-Control: no-store
< Content-Type: application/json
< Date: Thu, 19 Apr 2018 15:23:51 GMT
< Content-Length: 179
<
{"request_id":"557ec11e-48e3-3d43-9f40-6b183b6b7828","lease_id":"","renewable":false,"lease_duration":2764800,"data":{"foo":"world"},"wrap_info":null,"warnings":null,"auth":null}
* Connection #0 to host <Vault-Server-Hostname> left intact

=========================================================

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

/etc/salt/master.d/vault.conf

vault:
    url: https://<vault-server-hostname>:8200
    verify: /etc/ssl/certs/rtificates.crt
    auth:
        method: token
        token: < Have tried both the root token and the policy token associated with the policy listed below>
    policies:
        - my-policy

=========================================================

/etc/salt/master.d/vault-connection.conf         <this is for the sdb integration>

vault-test:
  driver: vault

=========================================================

/etc/salt/master.d/external_pillar.conf

ext_pillar:
  - vault: path=secret/first

=========================================================

Vault config.hcl file

storage "file" {
  path = "/srv/salt-secrets"
}
listener "tcp" {
 address     = "0.0.0.0:8200"
 tls_disable = 1
}

=========================================================

Output of:   vault policy read my-policy

path "secret/external-pillar-conf" {
  capabilities = ["read", "list", "update"]
}

path "secret/first" {
  capabilities = ["read", "list", "update"]
}

path "auth/*" {
  capabilities = ["read", "list","sudo","create","update","delete"]
}

=========================================================

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
This is a duplicate and it is fixed by this https://github.com/saltstack/salt/pull/46865

It will be in the next release

**Comment by ccoughle** [comment]
Hello, 

Thank you for the quick reply.
I went and looked at that pull request and manually edited in the change into salt/runners/vault.py and re-ran the above examples.  The pillar.items return was the same.  The salt-run and salt-call commands continue to throw errors.  Shown Below:  

===========================================================

salt-run sdb.get sdb://vault-test/secret/first

[ERROR   ] Failed to read secret! SSLError: [Errno 2] No such file or directory
Exception occurred in runner sdb.get: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/client/mixins.py", line 387, in _low
    data['return'] = self.functions[fun](*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/runners/sdb.py", line 27, in get
    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
  File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 46, in sdb_get
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/sdb/vault.py", line 114, in get
    raise salt.exceptions.CommandExecutionError(e)
CommandExecutionError: [Errno 2] No such file or directory

===========================================================

salt-call sdb.get sdb://vault-test/secret/first -l debug

Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cli/caller.py", line 212, in call
    ret['return'] = func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/sdb.py", line 28, in get
    return salt.utils.sdb.sdb_get(uri, __opts__, __utils__)
  File "/usr/lib/python2.7/site-packages/salt/utils/sdb.py", line 46, in sdb_get
    return loaded_db[fun](query, profile=profile)
  File "/usr/lib/python2.7/site-packages/salt/sdb/vault.py", line 114, in get
    raise salt.exceptions.CommandExecutionError(e)
CommandExecutionError: {'error': '[Errno 2] No such file or directory'}
Error running 'sdb.get': {'error': '[Errno 2] No such file or directory'}

===========================================================

So, it seems that there is still something off on my side.  I can't seems to trace down where the error is coming from.  I am currently running these test in a development environment, so any changes or tests are completely fine (why I could get away with editing the salt/runners/vault.py file directly)

Thanks
ccoughle

**Comment by gtmanfred** [comment]
If you comment out the try/except block in that portion of the code, you should be able to see what the actual raised error is.

```
    #try:
    url = 'v1/{0}'.format(path)
    response = __utils__['vault.make_request']('GET', url, profile)
    if response.status_code != 200:
        response.raise_for_status()
    data = response.json()['data']

    return data[key]
    #except Exception as e:
    #    log.error('Failed to read secret! {0}: {1}'.format(type(e).__name__, e))
    #    raise salt.exceptions.CommandExecutionError(e)

```

**Comment by gtmanfred** [comment]
If you comment out the try/except block in that portion of the code, you should be able to see what the actual raised error is.

```
    #try:
    url = 'v1/{0}'.format(path)
    response = __utils__['vault.make_request']('GET', url, profile)
    if response.status_code != 200:
        response.raise_for_status()
    data = response.json()['data']

    return data[key]
    #except Exception as e:
    #    log.error('Failed to read secret! {0}: {1}'.format(type(e).__name__, e))
    #    raise salt.exceptions.CommandExecutionError(e)

```

**Comment by ccoughle** [comment]
There was also a comment by Andrew George as well that I got an email alert about that I can't see here.  
After the ticket was closed, I tracked down my core issue.  It wasn't very clear from the documentation.  But what it boiled down to as that to make a call to a secret stored in hashicorp, you need to specify the actual keyname of the keyname value pair in the secret you are trying to access.  Also, regardless of what you set for tls on the hasicorp side you cannot use self signed certs without an extra step.  

So, for example.  

If you have the secret in hasicorp (like in my example above) named secret/first, the curl command will return the following:

curl -v --header "X-Vault-Token: $VAULT_TOKEN" -X GET http://vault-ccoughle.engrit.illinois.edu:8200/v1/secret/first

{"request_id":"557ec11e-48e3-3d43-9f40-6b183b6b7828","lease_id":"","renewable":false,"lease_duration":2764800,"data":{"foo":"world"},"wrap_info":null,"warnings":null,"auth":null}

The important thing here is that secret/first contains a set of internal key value pairs.  In this case the key-vaule pair is 
foo: world

So, in an sdb call to the vault server, you need to specify the key directly.  

salt-call sdb.get sdb://vault-test/secret/first            # This won't work
salt-call sdb.get sdb://vault-test/secret/first/foo        # This will work

The error return isn't very helpful in tracking this down.  Makes snse once you realize that each hasicorp secret can contain multiple key-vaule pairs inside it.  

Also, you tend to get a file not found error when using self signed certs in testing.  You can add the self-signed cert to the cert chain on your salt-master by copying the ssl cert from your vault server over to your master and running 
update-ca-trust 
to add it to the chain.  

Please let me know if this helps.

**Comment by gtmanfred** [comment]
Ok, cool!

Thanks for following up @ccoughle 

Daniel
