### ISSUE TITLE
state.highstate error with require_in: sls: 

### ISSUE THREAD

**Issue by MartinEmrich** [saltstack/salt#47182]
### Description of Issue/Question
`state.highstate test=true` returns with

```
    Passed invalid arguments to state.highstate: list indices must be integers, not unicode
```
(followed by the complete state.highstate docs).

`state.show_top` works fine, and returns the expected result.

running `state.sls` with each individual state works, too.
But `state.highstate` does not.

I found that when I removed the "require_in" block of something like

```
include:
  - slsfile1
  - slsfile2

some-state:
  test.nop:
    - require:
      - sls: slsfile1
    - require_in:
      - sls: slsfile2
```

the error no longer appears. The same states worked fine in Salt 2017.x.x

The closest Issue I found is #22852, but that's supposed to be fixed. In either case, an error message pointing to the exact location would be nice (I had to "bisect" the state tree down to the exact location).

In the minion log file (level: trace), I found this Traceback:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1600, in _thread_return
    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/modules/state.py", line 1055, in highstate
    orchestration_jid=orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 3881, in call_highstate
    return self.state.call_high(high, orchestration_jid)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 2693, in call_high
    high, req_in_errors = self.requisite_in(high)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1574, in requisite_in
    hinges = find_sls_ids(pname, high)
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 246, in find_sls_ids
    if item['__sls__'] == sls:
TypeError: list indices must be integers, not unicode
```

### Steps to Reproduce Issue
see above

### Versions Report
Master:
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.20.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

Minion:
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

Thanks,

Martin

**Comment by MartinEmrich** [comment]
At least no one was complaining... If you can replicate it, it is safe to assume that noone tried it before our upgrade to 2018.3.

**Comment by Ch3LL** [comment]
ping @saltstack/team-core any ideas why this is occuring?

**Comment by terminalmage** [comment]
This doesn't make sense to me... @MartinEmrich, your second example references two undefined SLS files in stateB.sls.

**Comment by terminalmage** [comment]
I'm sorry, I don't understand your reply. Are you saying to create `slsfile1` and `slsfile2` and put any states into them?

**Comment by terminalmage** [comment]
Yeah that looks like what you meant. I've gotten it to reproduce in 2017.7 as well as 2018.3. I have a fix already written, and attempting to write a unit test for this now

**Comment by MartinEmrich** [comment]
Yes indeed, just two arbitrary state files, where stateB works as a kind of "barrier" between the two.
Good to hear that you found the issue :)

**Comment by terminalmage** [comment]
This is fixed in https://github.com/saltstack/salt/pull/47682. @Ch3LL I set up a docker container to reproduce, can you sanity check it? Just run the following from the root of a git checkout of the head of 2017.7 and 2018.3:

```
docker run --rm -it -v $PWD:/testing terminalmage/issues:47182 salt-call state.apply
```

This should reproduce the error referenced in the OP (though on 2017.7 it will mention `str` instead of `unicode`).

However, when [checking out my PR locally](https://help.github.com/articles/checking-out-pull-requests-locally/) and running it against that branch, the state.apply should run as expected.

**Comment by jeffdyke** [comment]
I added a comment to the PR, but this did not make it into 2018.3.2 and i'm hitting the same issue. I can patch all my minions, but that seems silly.

**Comment by jeffdyke** [comment]
Solved in PR comments.  thanks to @gtmanfred
