### ISSUE TITLE
NAPALM grains not updating

### ISSUE THREAD

**Issue by aesposito91** [saltstack/salt#47203]
### Description of Issue/Question
It appears the once a proxy minion is spun up, all grain data is static and unable to be refreshed with saltutil.refresh_grains

Issue logged @ napalm - https://github.com/napalm-automation/napalm/issues/664

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

It appears the once a proxy minion is spun up, all grain data is static and unable to be refreshed with saltutil.refresh_grains

salt==2017.7.4
napalm-base==1.0.0
napalm-eos==0.6.1

#Get current hostname from salt grain
$ salt 'dev1' grains.get hostname
dev1:
dev1

#Get current hostname from device
$ salt 'dev1' net.cli "show hostname"
dev1:
----------
comment:
out:
----------
show hostname:
Hostname: dev1
FQDN: dev1.company.com
result:
True

#I changed the hostname on the device and checked on device
$ salt 'dev1' net.cli "show hostname"
dev1:
----------
comment:
out:
----------
show hostname:
Hostname: test
FQDN: test.company.com
result:
True

#Refresh grains
$ salt 'dev1' saltutil.refresh_grains
dev1:
True

#Check grains for update...
$ salt 'dev1' grains.get hostname
dev1:
dev1

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

$ salt 'host' grains.get version --versions-report
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: 1.11.4
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.9 Santiago
         locale: ISO-8859-1
        machine: x86_64
        release: 3.10.107-el6.ia32e.limeprod.2
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago

**Comment by Ch3LL** [comment]
ping @mirceaulinic can you take a look here?

**Comment by mirceaulinic** [comment]
Yep... spoke to @aesposito91 in private, I am aware of this issue and I might know what's causing it. I will try to get to it somewhere mid-next week.
@Ch3LL Can you please assign it to me so it's on my radar?

**Comment by rallytime** [comment]
Closed via #47513

**Comment by mirceaulinic** [comment]
@aesposito91 to confirm, but I'm not sure #46546 solved this one too. We might need to reopen.

**Comment by aesposito91** [comment]
Yes, you can proceed to close.

Thanks.

**Comment by rallytime** [comment]
Thank you @aesposito91 for fixing this. :)
