### ISSUE TITLE
Salt-API has no Return-Code

### ISSUE THREAD

**Issue by meaksh** [saltstack/salt#47208]
### Description of Issue/Question
As discussed with @rallytime , I bring https://github.com/saltstack/salt/pull/36318#issuecomment-370778513 as a new issue to rise a discussion about how we can approach this.

"Salt-API does not have Return-Code": You cannot differentiate between a value "False" and Minion down producing "False".

Example:
```
curl -sSk http://localhost:9080/ 
  -H 'Accept: application/json' 
  -H 'X-Auth-Token: xyz'
   -d client=local
   -d tgt='*'
   -d fun=grains.get -d arg=ip_gw
```
This return when minion is running:
```
{"return": [{"minion": true}]}
```
When I stop the minion I get:
```
{"return": [{"minion": false}]}
```

How should I know that "false" mean here "minion down" and that it is not the value for the grain `ip_gw`?

**Comment by Ch3LL** [comment]
Can you include a versions report?

**Comment by mchugh19** [comment]
Similar to #37043

**Comment by brejoc** [comment]
@Ch3LL This is pretty much version independent, since it's more or less a design flaw in Salt-API. So this happens in 2016.x, 2017.x and 2018.x.

**Comment by Ch3LL** [comment]
Thanks for specifying the versions. appreciate it @brejoc 

Through the issue @mchugh19 pointed me too I found this PR: https://github.com/saltstack/salt/pull/41356 I know that does not resolve this particular issue but figured it might be useful to know for others related to this issue. 

I will keep this issue open while still linked to 37043 as its a specific use case and we can focus on fixing this as well.

**Comment by Ch3LL** [comment]
ping @saltstack/team-netapi any ideas here on a fix?

**Comment by mattp-** [comment]
as referenced in #41356 you can use full_return kwarg to access the retcode among other metadata of the job. this issue can be resolved.

**Comment by mchugh19** [comment]
@mattp- I think the referenced feature only supports the LocalClient and Runner cmd function. So it helps, but doesn't fully address the issue raised here and in #37043

**Comment by mattp-** [comment]
@mchugh19 it looks like wheel client also supports full_return. the example in the original issue is also covered, ie:
```
DEBUG 2018-04-25 18:27:04,993 libpepper: [{'tgt_type': 'glob', 'full_return': True, 'tgt': 'testbox', 'batch': None, 'client': 'local', 'arg': [], 'fun': 'test.false'}]
{
    "return": [
        {
            "testbox": {
                "jid": "20180425182705054749",
                "ret": false,
                "retcode": 0
            }
        }
    ]
}
```

**Comment by brejoc** [comment]
Ah, this looks good. Thanks @mattp-!

@lucidd, what do you think?

**Comment by lucidd** [comment]
looks good. Is there any documentation regarding `retcode`?

**Comment by brejoc** [comment]
@lucidd I'm not aware of anything. @meaksh, @isbm maybe?

**Comment by brejoc** [comment]
I don't think that anything has changed here!

**Comment by sagetherage** [comment]
not stale

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
