### ISSUE TITLE
salt.utils.decorators.path.which seems broken

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#47223]
### Description of Issue/Question
Looks like the which decorator is broken.

https://github.com/saltstack/salt/blob/develop/salt/modules/zpool.py#L1100

```
(saltdev) root@zoltest:~# which mkfile
(saltdev) root@zoltest:~# mkfile
mkfile: command not found
(saltdev) root@zoltest:~# salt-call --local zpool.create_file_vdev 1G /tmp/vdisk0
Command required for 'zpool.create_file_vdev' not found: The 'mkfile' binary was not found in $PATH.
```
I would expect zpool.create_file_vdev to not be available, this used to be the case at least in 2016.x

### Versions Report
Current develop head build about 10 minutes ago from the time of writing

**Comment by garethgreenaway** [comment]
@sjorge Thanks for the report. The code appears to be doing what it's supposed to be doing.  The `mkfile` binary is not available and that is what is being reported above.  Looking back at the module in 2016.11 it appears to be the same, the only major difference is the decorator.  Do you have an example of what the output looked like in 2016.11?

**Comment by sjorge** [comment]
Maybe I am just remembering it wrong? I though I gave the same result as when you called a non defined function.
