### ISSUE TITLE
import fuction in py renderer

### ISSUE THREAD

**Issue by jils2013** [saltstack/salt#47222]
### Description of Issue/Question
In my sls files(py renderer) there are some same actions,i want share function between sls files
like what **import** do in python script(code reuse).

when use **import** i get the load path problem as the following issue:
https://github.com/saltstack/salt/issues/45521

any advice？

**Comment by jils2013** [comment]
a.sls  
```
#!py
def run():
	return sharef(a)

def sharef():
	...
```
b.sls  
```
#!py
def run():
	return sharef(b)

def sharef():
#the same as code **sharef** in a.sls
```
any fuction define sharef() once,and a.sls/b.sls can use fuction like **import** in python

**Comment by garethgreenaway** [comment]
@jils2013 Thanks for providing the example SLS.  I believe your best approach for accomplishing what you want to do, is by writing a customer Salt module that includes the shared function.  Then referencing that custom module inside your state files.  Something like this:
```
# -*- coding: utf-8 -*-
from __future__ import absolute_import


def __virtual__():
    return "common"


def share():
    return 'Hello'
```
```
#!py

def run():
    return __salt__['common.share']()
```
