### ISSUE TITLE
Unable to execute saltstack for docker operations 

### ISSUE THREAD

**Issue by adyanthaya17** [saltstack/salt#47234]
Hi,

I have installed docker on my minion nodes but executing the state files gives error message as seen below. Is the function command not working or is there something I am missing.

server.example.com
----------
          ID: mycontainer
    Function: docker_container.running
      Result: False
     Comment: State 'docker_container.running' was not found in SLS 'mycontainer'
              Reason: 'docker_container.running' is not available.
     Changes:

Summary for server.example.com
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms

**Comment by garethgreenaway** [comment]
@adyanthaya17 Thanks for the report.  The Docker state module requires that the execution module is available.  And the execution module requires that the python Docker library is installed.  If the state module is reporting as not being available it's likely that the execution module is also not available, which is likely because the python Docker library is not installed.

**Comment by adyanthaya17** [comment]
@garethgreenaway Hi, thanks for the quick reply. 

Pardon my basic knowledge but when you said execution module, did you mean the state files which are placed in the /srv/salt/ path?

Actually I have installed the Docker on three of my machines, and I am able to get the container running on 2 machines but not the third machine even though it has the same packages of docker installed as below:

# dpkg --list | grep docker
ii  docker-ce                            17.09.0~ce-0~ubuntu                        amd64        Docker: the open-source application container engine
ii  docker-compose                       1.8.0-2~16.04.1                            all          Punctual, lightweight development environments using Docker
rc  docker-engine                        1.13.1~cs6-0~ubuntu-xenial                 amd64        Docker: the open-source application container engine
ii  python-docker                        1.9.0-1~16.04.1                            all          Python wrapper to access docker.io's control socket
ii  python-dockerpty                     0.4.1-1~16.04.1                            all          Pseudo-tty handler for docker Python client (Python 2.x)


The minions that are able to get the containers running, are having trouble in pulling down the docker images, which gives the error: Comment: State 'docker.pulled' was not found in SLS 'test2', Reason: 'docker.pulled' is not available.

**Comment by garethgreenaway** [comment]
@adyanthaya17 No worries, we all started off with Salt the same.  The execution modules are modules and module functions like `cmd.run`, that are used for remote execution.  There is one that is used for interacting with Docker using functions like `docker.ps` for example to get a list of running containers.  The Docker state module uses the execution and if the execution module is not available then the state module is unavailable.

It appears that you have the correct packages installed, can you provide a copy of the state file that you're attempting to use?

**Comment by adyanthaya17** [comment]
Hi there, the below is one of the simple docker sls file I created. It seems like it works for few of the machines but when I install docker on new machine along with docker-py packages, it is unable to run it.

cat case1.sls
nginx:
  docker_image.present:
    - tag: latest


I get the below error:

ID: nginx
    Function: docker_image.present
      Result: False
     Comment: State 'docker_image.present' was not found in SLS 'case1'
              Reason: 'docker_image.present' is not available.

**Comment by garethhowell** [comment]
Has there been any progress on this? I'm getting the same error with a newly created docker server.
python-pip is installed as the docker pip package.

**Comment by wattwood** [comment]
I am also running into this issue.

**Comment by garethhowell** [comment]
I think I’ve got to the bottom of this. My salt state to install the docker engine installed the latest version in the apt respository. It turns out that this is very old.

Once I changed the state to install the latest version from the docker respository, using the instructions from the docker website, the problem disappeared.
