### ISSUE TITLE
timeout errors for salt calls should return an exit code other than 0

### ISSUE THREAD

**Issue by jf** [saltstack/salt#47235]
### Description of Issue/Question

I have salt set up to run in a CI tool, and the problem is that when salt is unable to reach a minion, or has a timeout for some reason, the status code returned is 0, which results in the CI tool not detecting it as an error.

`salt unreachable-or-down-minon test.ping; echo $?`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

I do not believe this has changed in the latest version, but fyi:

```
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-109-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
This makes sense.
@saltstack/team-core Anyone have strong thoughts either way on this one?

**Comment by gtmanfred** [comment]
It should be easy enough to just add `'retcode': 1` to the data that is yielded while waiting for minion returns.

https://github.com/saltstack/salt/blob/2017.7/salt/client/__init__.py#L1624

and then the retcode would be set if one of the minions doesn't return.

https://github.com/saltstack/salt/blob/2017.7/salt/cli/salt.py#L193

I can't think of a reason to not have an exit code when a minion does not return.

Daniel

**Comment by erwindon** [comment]
Or simply use `salt --static unreachable-or-down-minon test.ping; echo $?`
The exit code is 0 when it succeeds, otherwise it is 2.

**Comment by terminalmage** [comment]
@gtmanfred is spot-on, here. I recently did some work to make Salt's exit status work better and more reliably for the upcoming Fluorine release. I've added this and am working on an automated test to confirm the behavior.

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/49217

**Comment by jf** [comment]
Excellent! Thanks, @terminalmage !
