### ISSUE TITLE
salt-api not working from minion 

### ISSUE THREAD

**Issue by thatsk** [saltstack/salt#47244]
[23/Apr/2018:13:33:05] ENGINE Started monitor thread 'Autoreloader'.
[INFO    ] [23/Apr/2018:13:33:05] ENGINE Started monitor thread 'Autoreloader'.
[23/Apr/2018:13:33:05] ENGINE Serving on http://0.0.0.0:9191
[INFO    ] [23/Apr/2018:13:33:05] ENGINE Serving on http://0.0.0.0:9191
[23/Apr/2018:13:33:05] ENGINE Bus STARTED
[INFO    ] [23/Apr/2018:13:33:05] ENGINE Bus STARTED
[INFO    ] [api_acl] Authentication not checked for user test from IP 172.16.13.205
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'salt_master', 'tcp://127.0.0.1:4506', 'clear')
172.16.13.205 - - [23/Apr/2018:13:33:17] "POST /login HTTP/1.1" 401 753 "http://salt/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"
[INFO    ] 172.16.13.205 - - [23/Apr/2018:13:33:17] "POST /login HTTP/1.1" 401 753 "http://salt/login" "Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:58.0) Gecko/20100101 Firefox/58.0"

**Comment by thatsk** [comment]
[api_acl] Authentication not checked for user test from IP 172.16.13.205

**Comment by thatsk** [comment]
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: 1.7.4
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.21.1
           Mako: 1.0.7
   msgpack-pure: 0.1.3
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: 0.4.2
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: 0.6.8
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by thatsk** [comment]
salt-api-2017.7.4-1.el7.noarch
python-cherrypy-5.6.0-2.el7.noarch
CentOS Linux release 7.3.1611 (Core)

**Comment by thatsk** [comment]
cat /etc/salt/master
rest_cherrypy:
  port: 9191
  host: 0.0.0.0
  disable_ssl: True
  debug: True

external_auth:
  ldap:
    admins%:
      - '*.com':
        - '@*'
    servereng%:
      - '*.com':
        - '@*'

**Comment by garethgreenaway** [comment]
@thatsk Thanks.  That looks correct.  How are you attempting to interact with the API?  If you're using `curl` can you provide the command line that you're using?

**Comment by thatsk** [comment]
curl -k http://salt:9191     -H 'Accept: application/x-yaml'     -H 'X-Auth-Token: dc23b240f6b1d624f2b47593fa13d672f26eeca3'    -d client=local     -d tgt='*'     -d fun=test.ping
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/cherrypy/_cprequest.py", line 631, in respond
    self._do_respond(path_info)
  File "/usr/lib64/python2.7/site-packages/cherrypy/_cprequest.py", line 681, in _do_respond
    self.hooks.run('before_request_body')
  File "/usr/lib64/python2.7/site-packages/cherrypy/_cprequest.py", line 114, in run
    raise exc
HTTPError: (401, None)
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 14.0.1</a>
      </span>
    </div>
    </body>
</html>




curl -i -H accept=application/json -d username=test -d password=Kunalsing39@ -d eauth=ldap http://salt:9191/login
HTTP/1.1 200 OK
Content-Length: 198
Access-Control-Expose-Headers: GET, POST
Vary: Accept-Encoding
Server: CherryPy/14.0.1
Allow: GET, HEAD, POST
Access-Control-Allow-Credentials: true
Date: Fri, 27 Apr 2018 04:57:33 GMT
Access-Control-Allow-Origin: *
X-Auth-Token: 0d1621f46d1b6d0a74f8c5a77f01682c57993049
Content-Type: application/json
Set-Cookie: session_id=0d1621f46d1b6d0a74f8c5a77f01682c57993049; expires=Fri, 27 Apr 2018 14:57:33 GMT; Max-Age=36000; Path=/

{"return": [{"perms": [{"*": ["@*"]}], "start": 1524805053.333448, "token": "0d1621f46d1b6d0a74f8c5a77f01682c57993049", "expire": 1524848253.333449, "user": "test", "eauth": "ldap"}]}
