### ISSUE TITLE
Modifying a managed file using Jinja templating with data calculated in a state

### ISSUE THREAD

**Issue by asymetrixs** [saltstack/salt#47266]
### Description of Issue/Question
I just installed JRE 8 and noticed, that it is not installed in a generic directory like it was for JRE6 and JRE7 like `C:\Program Files\Java\jre6`. Now it is installed in a directory named `jre<version>_<update>`, like `C:\Program Files\Java\jre1.8.0_172`, which makes it difficult to place files inside it after installation of JRE 8.
As shown below, I found a solution for that. My problem now is:
The file `deploy.config` shown below also needs adjustments. I need to place the value of `jrePath` inside the file and tried it with templating adding the line `- template: jinja` and referring to `{{ jrePath }}` inside the file `deploy.config`. Unfortunately this does not work as `jrePath` seems to be NULL so that the whole file is empty when created by Salt.

Question is, is there a way to place the value of `jrePath` also inside `deploy.config`?

### Setup
Placing of the file into the correct directory:
```
{% for jrePath in salt['find.file']("C:\Program Files\Java", iregex="jre1[\.]8[\.][\d]+$") %}

Copy file {{ jrePath }}:
  file.managed:
    - name: '{{ jrePath }}\lib\deploy.config'
    - source: salt://[...]/deploy.config
{% endfor %}
```
deploy.config, which needs the path of the directory:
```
deployment.system.config={{ jrePath }}\some\where.properties
```

Thanks

### Versions Report
```
Salt Version:
    Salt: 2017.7.4
  
Dependency Versions:
    cffi:             1.10.0
    cherrypi:         unknown
    dateutil:         2.6.0
    docker-py:        not installed
    gitdb:            2.0.3
    gitpython:        2.1.3
    ioflo:            not installed
    Jinja2:           2.9.6
    libgit2:          not installed
    libnacl:          not installed
    M2Crypto:         not installed
    Mako:             1.0.6
    msgpack-pure:     not installed
    msgpack-python:   0.4.8
    mysql-python:     not installed
    pycparser:        2.17
    pycrypto:         2.6.1
    pycryptodome:     not installed
    pygit2:           not installed
    Python:           3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
    python-gnupg:     0.4.0
    PyYAML:           3.12
    PyZMQ:            16.0.2
    RAET:             not installed
    smmap:            2.0.3
    timelib:          0.2.4
    Tornado:          4.5.1
    ZMQ:              4.1.6

System Versions:
    dist:
    locale:           cp1252
    machine:          AMD64
    release:          7
    system:           Windows
    version:          7 6.1.7601 SP1 Multiprocessor Free
```

**Comment by asymetrixs** [comment]
Well, it happens in the same state, like this. `java-8-x64` is defined in winrepo-ng.

```
Install Java:
  pkg.installed:
    - pkgs:
      - java-8-x64

{% for jrePath in salt['find.file']("C:\Program Files\Java", iregex="jre1[\.]8[\.][\d]+$") %}

Copy file {{ jrePath }}:
  file.managed:
    - name: '{{ jrePath }}\lib\deploy.config'
    - source: salt://[...]/deploy.config

{% endfor %}
```

**Comment by gtmanfred** [comment]
Yeah, that isn't going to work, because the jinja is all run before the package is installed.

You will need to use __slots__ and make a custom module to do this.

make `/srv/salt/_modules/custom.py`
```
def get_jre_deploy_path(path, iregex='jre1[\.]8[\.][\d]+$'):
    return r'{0}\lib\deploy.config'.format(__salt__['file.find'](path, iregex))
```
Then sync the module and use that for the name in your state.

`salt \* saltutil.sync_modules`

```
Install Java:
  pkg.installed:
    - pkgs:
      - java-8-x64

Copy file to jrePath:
  file.managed:
    - name: __slots__:salt:custom.get_jre_deploy_path()
    - source: salt://[...]/deploy.config
```

This will then be resolved at runtime, instead of compile time, so the package will be installed by the time the file.find is run.

https://docs.saltstack.com/en/latest/topics/slots/index.html

Thanks,
Daniel

**Comment by asymetrixs** [comment]
Thanks, that looks like what I need. However, now I need to upgrade to 2018.3.0 first.

I guess there is no similar functionality to do something like that in 2017.7.4, right? I thought about something like using Jinja to retrieve the version number of the last and perhaps second last entry in win-repo-ng/jre8.sls and to do string manipulations on the version number to get the install path (assuming it follows a pattern), so that this can be used in a state as path?

**Comment by gtmanfred** [comment]
slots was added in 2018.3. so you would need to upgrade.

You could just store the path to where it will be installed in pillars, i am not sure of a way to look into win-repo-ng to figure that out.

Looking at the sls for jre8, it does not look like it specifies the path that it will be installed to.

https://github.com/saltstack/salt-winrepo-ng/blob/master/jre8.sls

Potentially, you could use some pkg.latest_version module to get the latest version of the jre, and use that if you are always going to be upgrading to the newest?

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_pkg.html#salt.modules.win_pkg.latest_version

**Comment by asymetrixs** [comment]
Thank you, but for now I will use a workaround.
I will install JRE 8 by using an answer-file as described here: [https://docs.oracle.com/javase/8/docs/technotes/guides/install/config.html#installing_with_config_file](https://docs.oracle.com/javase/8/docs/technotes/guides/install/config.html#installing_with_config_file)
It allows to specify the destination directory by using `INSTALLDIR=` and I will simply install it to `C:\Program Files\Java\jre8` (or `C:\Program Files (x86)\Java\jre8` for i586) like for older versions... This way I know exactly where it is and I can prepare the configuration files that need to know this path in advance.

**Comment by gtmanfred** [comment]
Sounds good, I am closing this issue.
