### ISSUE TITLE
staltstack for windows excute powershell script get an error

### ISSUE THREAD

**Issue by yplonggit** [saltstack/salt#47265]
Processing -File ''c:\windows\temp\__salt.tmp.cq9hem.ps1'' failed: The given path's format is not supported. Specify a valid path for the -File parameter.

**Comment by gtmanfred** [comment]
Can you provide me with more information, including the --versions-report that the issue template requested, and steps to reproduce this?

Daniel

**Comment by yplonggit** [comment]
salt stack version:  Salt-Minion-2018.3.0-Py3-AMD64-Setup.exe 
windows powershell  version：5.0.10586.117

salt '*' cmd.script salt://scripts/windows_task.ps1  shell='powershell'

**Comment by gtmanfred** [comment]
This is fixed by this PR #45716

It will be in 2018.3.1, and is already in 2017.7.6
