### ISSUE TITLE
disable_saltenv_mapping not working as expected

### ISSUE THREAD

**Issue by mew1033** [saltstack/salt#47260]
### Description of Issue/Question
I can't seem to get the disable_saltenv_mapping feature working on my master. When I add in that line, I'm never able to list the files on the master.
### Setup
Here's the relevant part of my config:

    fileserver_backend:
      - roots
      - gitfs

    file_roots:
      base:
        - /srv/salt

    gitfs_remotes:
      - git://my.git.repo/git/repo:
        - root: salt
        - base: master
    #    - disable_saltenv_mapping: True

### Steps to Reproduce Issue
I do a `salt-run fileserver.file_list` and it lists all my files. If I remove that comment character, then delete the cache `rm -rf /var/cache/salt/`, restart the master `service salt-master restart`, and start listing files again, I don't get anything from my git repo. Add the comment back, and everything (slowly) starts to work again.

### Versions Report
I just upgraded the master to 2018.3. Specifically for this feature actually.

    Salt Version:
               Salt: 2018.3.0
    
    Dependency Versions:
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: 0.21.0
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.1
       mysql-python: Not Installed
          pycparser: 2.10
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: 0.21.4
             Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
    
    System Versions:
               dist: centos 7.1.1503 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-327.36.3.el7.x86_64
             system: Linux
            version: CentOS Linux 7.1.1503 Core

**Comment by gtmanfred** [comment]
You have disabled all mapping to saltenvs, and have not specified any saltenvs in the git repo setup.

```
gitfs_remotes:
  - git://my.git.repo/git/repo:
    - root: salt
    - disable_saltenv_mapping: true
    - saltenv:
      - base:
        - ref: master
```

Try this.
Daniel

**Comment by mew1033** [comment]
@gtmanfred I changed my config to look like what you said: 

    gitfs_remotes:
      - git://my.git.repo/git/repo:
        - root: salt
        - disable_saltenv_mapping: true
        - saltenv:
          - base:
            - ref: master
    #    - base: master

and it still doesn't work.
Also, I thought that the `disable_saltenv_mapping` flag would disable all the branch/tag-->saltenv mappings _except for_ master-->base. That's what (if I understand it correctly) it says in the docs.

**Comment by gtmanfred** [comment]
It appears that you are correct.

I am able to replicate this issue as well.

@terminalmage can you take a look at this when you get a minute?

Thanks,
Daniel

**Comment by terminalmage** [comment]
Fixed in https://github.com/saltstack/salt/pull/47410
