### ISSUE TITLE
Add 'vmm' to list of allowed outputs from `virt-what`

### ISSUE THREAD

**Issue by troyjfarrell** [saltstack/salt#47296]
On OpenBSD vmm with virt-what installed, this debug warning is triggered:
https://github.com/saltstack/salt/blob/71cf4584d8c89ad4dedb620b189e9b88883479e4/salt/grains/core.py#L796-L801

This can be fixed by adding 'vmm' to the list of allowed outputs from `virt-what` on line 704:
https://github.com/saltstack/salt/blob/71cf4584d8c89ad4dedb620b189e9b88883479e4/salt/grains/core.py#L703-L706

**Comment by Ch3LL** [comment]
seems you have a grasp here of the fix want to take a stab at a PR? If not I can.

**Comment by troyjfarrell** [comment]
I can try it this weekend.

**Comment by eradman** [comment]
I don't think that `virt-what` adds any useful information here. Salt already infers that we're running under VMM

https://github.com/saltstack/salt/blob/71cf4584d8c89ad4dedb620b189e9b88883479e4/salt/grains/core.py#L941-L942

Isn't the problem with the warning itself? We warn that information _might_ not be correct even when we have all of the data!

**Comment by garethgreenaway** [comment]
Closing this out, if the problem persists please comment & we'll re-open the issue or feel free to open a new issue.
