### ISSUE TITLE
Remove dead code

### ISSUE THREAD

**Issue by troyjfarrell** [saltstack/salt#47295]
A bad merge (d25677e954a898fd4a23e271ece3674d34b26ddf) in 2015 resulted in this dead code being added.

Dead code:
https://github.com/saltstack/salt/blob/71cf4584d8c89ad4dedb620b189e9b88883479e4/salt/grains/core.py#L773-L779

This code is dead because there is a matching `elif command == 'virt-what':` above it:
https://github.com/saltstack/salt/blob/71cf4584d8c89ad4dedb620b189e9b88883479e4/salt/grains/core.py#L703-L715

**Comment by Ch3LL** [comment]
Thanks for pointing this out. fixed in https://github.com/saltstack/salt/pull/47302
