### ISSUE TITLE
repo.saltstack.com being blocked as malicious by Firefox and Chrome

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#47306]
repo.saltstack.com is being blocked by Firefox and Chrome with a warning that it contains harmful software. "install unwanted or malicious software on visitor's computers" is the warning presented.

**Comment by edgan** [comment]
I am seeing the same in Chrome.

**Comment by rhoths** [comment]
It's currently listed on the [Safe Browsing list](https://transparencyreport.google.com/safe-browsing/search?url=https:%2F%2Frepo.saltstack.com%2F&hl=en-US) as failing.

**Comment by bicofino** [comment]
Same here.

**Comment by fritzstauff** [comment]
Same

**Comment by ftolead** [comment]
Same here, Would this prevent my Redhat systems from being able to install/update salt packages?

**Comment by iannate** [comment]
It's related to the Windows installer for 2018.3.0. This file does not have security issues, and SaltStack has requested a review from Google, which can take up to 72 hours. We’re looking at building our own service manager so the Windows installers do not trigger future warnings. Just click “Details” and “visit this site” to proceed. Thanks for your patience and understanding!

**Comment by garethgreenaway** [comment]
The Windows packages in question were rebuilt, rescanned by Google, and the warning has been lifted.  We believe this issue should now be resolved.
