### ISSUE TITLE
GPG module needs updating to leverage gpg2, now standard on Debian/Ubuntu family

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#47318]
### Description of Issue/Question
gpg2 has become the standard on current Debian and Ubuntu family platforms, and while gpp1 is still available, at some point it will be dropped, hence the need to utilize gpg2.

This work should be done for the Fluorine cycle

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by dmurphy18** [comment]
With Ubuntu 18.04 LTS, gpg2 has been renamed to gpg and is version 2.2.4

**Comment by Reiner030** [comment]
Hi,

this feature is urgently needed and is no "Thus this becomes a don't care as comes with the platform" point as closed by initiator of this issue.

GPG2 is default since years - even Debian Jessie had it as default!
https://superuser.com/a/959634
https://summit.debconf.org/debconf15/meeting/195/gnupg-in-debian-report/
And GPG2 offers enhanced chipers/security which are required for good actual security since several years: https://manpages.debian.org/jessie/gnupg2/gpg2.1.en.html


I was wondering why my by Saltstack setup key wasn't shown when I called `gpp --list-keys` after my sls run with state:
```
sury.org-gpg-key:
  gpg.present:
    - name: B188E2B695BD4743
    - keys: B188E2B695BD4743
    - keyserver: keys.gnupg.net
    - user: root
    - trust: fully
    - require:
        - pkg: python-gnupg
```
and I found in debug mode the reason - Saltstack calls explicit `gpg1`:
```
[INFO    ] Running state [B188E2B695BD4743] at time 18:20:59.075345
[INFO    ] Executing state gpg.present for [B188E2B695BD4743]
[DEBUG   ] ['gpg1', '--status-fd', '2', '--no-tty', '--homedir', '/root/.gnupg', '--version']
[DEBUG   ] stderr reader: <Thread(Thread-1, initial daemon)>
[DEBUG   ] stdout reader: <Thread(Thread-2, initial daemon)>
[DEBUG   ] chunk: 'gpg (GnuPG) 1.4.21\nCopyright (C) 2015 Free Software Foundation, Inc.\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permit'
[DEBUG   ] ['gpg1', '--status-fd', '2', '--no-tty', '--homedir', '/root/.gnupg', '--list-keys', '--fixed-list-mode', '--fingerprint', '--fingerprint', '--with-colons']
[DEBUG   ] stderr reader: <Thread(Thread-3, initial daemon)>
[DEBUG   ] stdout reader: <Thread(Thread-4, initial daemon)>
[DEBUG   ] chunk: 'tru::1:1559672238:0:3:1:5\npub:-:3072:1:B188E2B695BD4743:1552904095:1615976095::f:::scESC:\nfpr:::::::::15058500A0235D97F5D10063B188E2B695BD4743:\nuid:-::::1552904095::5A6880F9B1075434C4E8CF3B0E5CC319E0A6B8E8::DEB.SURY.ORG Automatic Signing Key <deb@sury.org>'
[DEBUG   ] line: u'tru::1:1559672238:0:3:1:5'
[DEBUG   ] line: u'pub:-:3072:1:B188E2B695BD4743:1552904095:1615976095::f:::scESC:'
[DEBUG   ] line: u'fpr:::::::::15058500A0235D97F5D10063B188E2B695BD4743:'
[DEBUG   ] line: u'uid:-::::1552904095::5A6880F9B1075434C4E8CF3B0E5CC319E0A6B8E8::DEB.SURY.ORG Automatic Signing Key <deb@sury.org>:'
[DEBUG   ] line: u'sub:-:3072:1:B214EAC28059B8AC:1552904095:1615976095:::::e:'
[DEBUG   ] line: u'fpr:::::::::45BEA3E529112086C622F8A4B214EAC28059B8AC:'
[DEBUG   ] ['gpg1', '--status-fd', '2', '--no-tty', '--homedir', '/root/.gnupg', '--version']
[DEBUG   ] stderr reader: <Thread(Thread-5, initial daemon)>
[DEBUG   ] stdout reader: <Thread(Thread-6, initial daemon)>
[DEBUG   ] chunk: 'gpg (GnuPG) 1.4.21\nCopyright (C) 2015 Free Software Foundation, Inc.\nLicense GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>\nThis is free software: you are free to change and redistribute it.\nThere is NO WARRANTY, to the extent permit'
[DEBUG   ] ['gpg1', '--status-fd', '2', '--no-tty', '--homedir', '/root/.gnupg', '--list-keys', '--fixed-list-mode', '--fingerprint', '--fingerprint', '--with-colons']
[DEBUG   ] stderr reader: <Thread(Thread-7, initial daemon)>
[DEBUG   ] stdout reader: <Thread(Thread-8, initial daemon)>
[DEBUG   ] chunk: 'tru::1:1559672238:0:3:1:5\npub:-:3072:1:B188E2B695BD4743:1552904095:1615976095::f:::scESC:\nfpr:::::::::15058500A0235D97F5D10063B188E2B695BD4743:\nuid:-::::1552904095::5A6880F9B1075434C4E8CF3B0E5CC319E0A6B8E8::DEB.SURY.ORG Automatic Signing Key <deb@sury.org>'
[DEBUG   ] line: u'tru::1:1559672238:0:3:1:5'
[DEBUG   ] line: u'pub:-:3072:1:B188E2B695BD4743:1552904095:1615976095::f:::scESC:'
[DEBUG   ] line: u'fpr:::::::::15058500A0235D97F5D10063B188E2B695BD4743:'
[DEBUG   ] line: u'uid:-::::1552904095::5A6880F9B1075434C4E8CF3B0E5CC319E0A6B8E8::DEB.SURY.ORG Automatic Signing Key <deb@sury.org>:'
[DEBUG   ] line: u'sub:-:3072:1:B214EAC28059B8AC:1552904095:1615976095:::::e:'
[DEBUG   ] line: u'fpr:::::::::45BEA3E529112086C622F8A4B214EAC28059B8AC:'
[INFO    ] Executing command [u'/usr/bin/gpg', u'--import-ownertrust'] as user 'root' in directory '/root'
[INFO    ] Set trust level for B188E2B695BD4743 to fully
GPG Public Key B188E2B695BD4743 already in keychain
[INFO    ] Completed state [B188E2B695BD4743] at time 18:20:59.148600 (duration_in_ms=73.255)
```

**Comment by dmurphy18** [comment]
@Reiner030 This is a closed issue. If there is a problem issue , it is best to open a new issue having first checked to see if there is not an issue already open for the problem.

Please include the output of --versions-report or test .versions for the system exhibiting the issue, helps immensely when debugging the issue.

From the above it looks like output from running on an older Debian 8 / Ubuntu 14.04 system in debbuild.py, that file detects the appropriate gpg version to use and will use gpg2  when appropriate.

Note with current Buster there is no gpg1 or gpg2
root@deb10min:/home/david# l /usr/bin/gpg*
-rwxr-xr-x 1 root root  3.5K Dec 14 18:17 /usr/bin/gpg-zip
-rwxr-xr-x 1 root root  196K Dec 14 18:17 /usr/bin/gpg-wks-server
-rwxr-xr-x 1 root root  435K Dec 14 18:17 /usr/bin/gpgv
-rwxr-xr-x 1 root root  152K Dec 14 18:17 /usr/bin/gpgtar
-rwxr-xr-x 1 root root   83K Dec 14 18:17 /usr/bin/gpgsplit
-rwxr-xr-x 1 root root  496K Dec 14 18:17 /usr/bin/gpgsm
-rwxr-xr-x 1 root root   31K Dec 14 18:17 /usr/bin/gpgparsemail
-rwxr-xr-x 1 root root  159K Dec 14 18:17 /usr/bin/gpg-connect-agent
-rwxr-xr-x 1 root root  171K Dec 14 18:17 /usr/bin/gpgconf
-rwxr-xr-x 1 root root  846K Dec 14 18:17 /usr/bin/gpgcompose
-rwxr-xr-x 1 root root  397K Dec 14 18:17 /usr/bin/gpg-agent
-rwxr-xr-x 1 root root 1018K Dec 14 18:17 /usr/bin/gpg
root@deb10min:/home/david# lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
root@deb10min:/home/david# 

If there is an issue, please open a new issue with the above requested information.
Thanks

**Comment by Reiner030** [comment]
I am running Debian Stretch latest version on all servers with actual Saltstack 2018.3.4 because 2019.9.2 is too buggy to upgrade yet... 
I'll check if there is some other open issue for GPG and if not open a new one.
This issue has the nice feature to be already tagged as "Approved"....
