### ISSUE TITLE
Feature-Request -- Add a `clean_old_jobs` function to the `pgjsonb returner`

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#47316]
Feature-Request -- Add a `clean_old_jobs` function to the `pgjsonb returner`

**Comment by rickh563** [comment]
ZD-2278

**Comment by rallytime** [comment]
@garethgreenaway This is a feature request we need for Fluorine. Can you add this feature?

**Comment by rallytime** [comment]
Closed via #47366
