### ISSUE TITLE
archive.extracted keep and/or keep_source not working

### ISSUE THREAD

**Issue by rlschilperoort** [saltstack/salt#47324]
When the archive.extracted state is used with the option(s)  keep = False and/or keep_source = False
The passed argument is not used; and the result is that the source file is always kept
Debug log states "Keeping cached source file"

The cause of this problem is within the file ./salt/states/archive.py
In this file the occurence of the keep and/or keep_source is checken and popped from the args
But then is checken a second time; after the first time the arguments have been popped therefore the second the will result in the else statement:
else:
        # Neither was passed, default is True
        keep_source = True

### Setup
./salt/states/archive.py

### Steps to Reproduce Issue
Use the archive.extracted state with keep = False or keep_source = False

### Versions Report
salt-minion --version report
salt-minion 2018.3.0 (Oxygen)

**Comment by rallytime** [comment]
Closed via #47332
