### ISSUE TITLE
Nested External Pillar returns in Vault

### ISSUE THREAD

**Issue by ccoughle** [saltstack/salt#47336]
### Description of Issue/Question

I was trying to get the vault external pillar to return the data in a nested format.  the cobbler external pillar had the ability and so I look into it a bit and it seems to be a simple change that could be enacted for vault pillar (and likely other pillars too)  

These changes would allow for each vault source specified to be nested under a keyname in the pillar return.  Also, if duplicate keynames are present (as in the example confs below) they get merged.  Lastly, it shouldn't affect existing configs, as the old config file format continues to work when no nesting_key is specified.  Probably worth changing "conf" to something more descriptive in the ext_pillar definition so that the configuration file is easier to read.  

I have tested this with local edits on my test instance salt master and it seems to work as intended.  I haven't looked at any other external pillar modules to see if a similar nesting tag would be doable.  

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

/usr/lib/python2.7/site-packages/salt/pillar/vault.py:  

=======Adding a line to the ext_pillar def===========
def ext_pillar(minion_id,  # pylint: disable=W0613
               pillar,  # pylint: disable=W0613
               conf):

-------

def ext_pillar(minion_id,  # pylint: disable=W0613
               pillar,  # pylint: disable=W0613
               conf,
               nesting_key=None):
=======Adding a line to the ext_pillar def===========

=======editing the data return at the end of the file===========
return vault_pillar

-------

    if nesting_key:
        vault_pillar = {nesting_key: vault_pillar}
    return vault_pillar

=======editing the data return at the end of the file===========

=======Update documentation for the external pillar conf file===========

    ext_pillar:
      - vault: path=secret/salt
      - vault: path=secret/root
      - vault: path=secret/minions/{minion}/pass

    ext_pillar:
      - vault: 
           conf: path=secret/salt
           nesting_key: keyname1
      - vault: 
           conf: path=secret/root
           nesting_key: keyname1
      - vault: 
           conf: path=secret/minions/{minion}/pass
           nesting_key: keyname2

=======Update documentation for the external pillar conf file===========

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
Can you open a PR to implement this on the develop branch of salt?

Thanks,
Daniel

**Comment by ccoughle** [comment]
I just submitted a PR:  
https://github.com/saltstack/salt/pull/47409

Never have before, so let me know if any additional information is needed.
