### ISSUE TITLE
Unable to get salt-proxy to work

### ISSUE THREAD

**Issue by sk1988** [saltstack/salt#47346]
### Description of Issue/Question

I have recently setup salt-master from https://repo.saltstack.com/2017.7.html#rhel using the below command.

**sudo yum install https://repo.saltstack.com/yum/redhat/salt-repo-2017.7-1.el7.noarch.rpm** 

I am trying to setup a proxy minion using the documentation @ https://docs.saltstack.com/en/develop/topics/proxyminion/demo.html which doesn't seem to be working.  I am able to accept the key on the salt-master, but when I do a test.ping against the proxy minion, I get an error.

**Minion did not return. [Not connected]**

I have setup the proxy minion process on the salt-master which didn't work.  I have also tried setting it up on another machine without and with salt-minion running on it, but the behavior is the same.  I get the same result when I do test.ping from salt master.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

[root@vm07 pillar]# pwd
/srv/pillar
[root@vm07 pillar]# cat top.sls p8000.sls
base:
  'p8000':
    - p8000

proxy:
  proxytype: rest_sample
  url: http://10.43.1.85:8000
[root@vm07 pillar]# cat /etc/salt/proxy | grep ^master
master: localhost
[root@vm07 pillar]#

[root@vm07 pillar]# systemctl status salt-master
● salt-master.service - The Salt Master Server
   Loaded: loaded (/usr/lib/systemd/system/salt-master.service; disabled; vendor preset: disabled)
   Active: active (running) since Fri 2018-04-27 00:07:40 EDT; 46min ago
     Docs: man:salt-master(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 32527 (salt-master)
   CGroup: /system.slice/salt-master.service
           ├─32527 /usr/bin/python /usr/bin/salt-master
           ├─32533 /usr/bin/python /usr/bin/salt-master
           ├─32538 /usr/bin/python /usr/bin/salt-master
           ├─32539 /usr/bin/python /usr/bin/salt-master
           ├─32542 /usr/bin/python /usr/bin/salt-master
           ├─32543 /usr/bin/python /usr/bin/salt-master
           ├─32544 /usr/bin/python /usr/bin/salt-master
           ├─32546 /usr/bin/python /usr/bin/salt-master
           ├─32552 /usr/bin/python /usr/bin/salt-master
           ├─32553 /usr/bin/python /usr/bin/salt-master
           ├─32554 /usr/bin/python /usr/bin/salt-master
           └─32555 /usr/bin/python /usr/bin/salt-master

Apr 27 00:07:39 vm07.smt.wqllc.net systemd[1]: Starting The Salt Master Server...
Apr 27 00:07:40 vm07.smt.wqllc.net systemd[1]: Started The Salt Master Server.
[root@vm07 pillar]#

[root@vm07 pillar]# salt-key
Accepted Keys:
p8000
smtwq-leaf-019
smtwq-sto-001a
smtwq-sto-001b
vm07.smt.wqllc.net
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@vm07 pillar]#

[root@vm07 pillar]# salt '*' test.ping
vm07.smt.wqllc.net:
    True
smtwq-sto-001b:
    True
smtwq-leaf-019:
    True
smtwq-sto-001a:
    True
p8000:
    Minion did not return. [Not connected]

[root@vm07 pillar]# salt --version
salt 2017.7.5 (Nitrogen)
[root@vm07 pillar]#

As mentioned, I also tried setting up salt proxy minion on another machine and below is the configuration on it:

[root@vm08 ~]# cat /etc/salt/proxy | grep ^master
master: vm07.smt.wqllc.net
[root@vm08 ~]#

[root@vm08 ~]# yum list installed | grep salt
salt.noarch                        2016.11.3-1.el7                     @wqa
salt-minion.noarch                 2016.11.3-1.el7                     @wqa
[root@vm08 ~]#

### Steps to Reproduce Issue
Version of salt master and the configuration that is in use has been provided already.

### Versions Report

[root@vm07 pillar]# salt --version
salt 2017.7.5 (Nitrogen)
[root@vm07 pillar]#

**Comment by gtmanfred** [comment]
Do you have the rest_example python script running?

https://github.com/saltstack/salt-contrib/tree/master/proxyminion_rest_example

I do not see this mentioned in your writeup

Daniel

**Comment by gtmanfred** [comment]
No problem! happy to help
