### ISSUE TITLE
FreeBSD grains return incorrect data in 2018.3.0

### ISSUE THREAD

**Issue by sylgeist** [saltstack/salt#47365]
### Description of Issue/Question
After upgrading to 2018.3.0 the following grains return the wrong data:

os_family: proxy
osrelease: proxy

### Setup
py36-salt-2018.3.0_1 master and minion
FreeBSD 11.1

### Steps to Reproduce Issue
Running any states that reference the above grains fail with something similar:
`----------
          ID: dovecot-pkg
    Function: pkg.installed
        Name: dovecot
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'imap'
              Reason: 'pkg' __virtual__ returned False
     Changes:   
`
This is across multiple systems, physical and virtual.

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Apr  5 2018, 20:34:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE-p9
         system: FreeBSD
        version: Not Installed

**Comment by Ch3LL** [comment]
can you try the fix in https://github.com/saltstack/salt/issues/47006 and clear out your pycache? possibly is directly related

**Comment by dereckson** [comment]
On FreeBSD 11.2, with 2018.3.1 (current ports version), I can repro the issue.

After manually applying 205abe209d5d8af6db2a619fa0c97de26f7b4256 + clearing pycache, it solves the issue.

**Comment by Ch3LL** [comment]
awesome thanks for verifying :) i'll go ahead and close this issue especially since cedwards stated its been updated in freebsd as well.
