### ISSUE TITLE
Public IP not being created with azurearm

### ISSUE THREAD

**Issue by esell** [saltstack/salt#47370]
### Description of Issue/Question

It appears that a public IP is not being created when creating a VM for Azure using the `azurearm` driver. This happens even if I put `public_ip: True` in the cloud profile. The error returned is:

`[ERROR   ] There was a profile error: list index out of range`

Note that the VM itself is actually created (along with the NIC, disk, etc), it just is missing the public IP. 

### Setup

Here is a sample cloud profile that I am using:

```azure-ubuntu:
  provider: azure
  image: Canonical|UbuntuServer|16.04-LTS|latest
  size: Standard_DS2_v2
  location: westus
  subnet: default
  ssh_username: esell
  ssh_password: MyTestPassword
  public_ip: True
```

### Steps to Reproduce Issue

* Create cloud profile
* use salt-cloud to provision a VM in Azure

### Versions Report

```Salt Version:
           Salt: 2018.3.0-380-g63b5391

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-1014-azure
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by nicholasmhughes** [comment]
The parameter to cause a public IP to be created is: ``allocate_public_ip: True``

**Comment by esell** [comment]
Thanks @nicholasmhughes, that was it. I will see about putting together a PR to update the docs with this info (unless it is already there and I just missed it?). I'll go ahead and close this...
