### ISSUE TITLE
Updating Windows Salt Minions

### ISSUE THREAD

**Issue by tjgruber** [saltstack/salt#47377]
### Description of Issue/Question
The only way I can get Windows Salt-Minions to upgrade is by using the following command on the Salt-Master:
`salt 'minionName' cmd.run 'choco upgrade saltminion -y --ignore-checksums'`

The problem with this, is that it disconnects and never returns the results.  It says:  
```
minionname.domain.com:
"Minion did not return. [Not connected]"
```
Is there still not a real way to upgrade Minions?  This seems pretty important...

In version 2018.3.0, I can use the chocolatey.upgraded module.  This seems to work well, BUT... **How do I get all of my Windows Minions to this version reliably???... and without having to manually restart the salt-minion service on them all?**

### Versions Report
Salt-Minions are:
```
2017.7.3
```

The Salt-Master is:
```
Salt Version:
           Salt: 2017.7.3
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.14 (default, Mar 14 2018, 13:36:31)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: fedora 27 Twenty Seven
         locale: UTF-8
        machine: x86_64
        release: 4.15.14-300.fc27.x86_64
         system: Linux
        version: Fedora 27 Twenty Seven
```

**Comment by damon-atkins** [comment]
The supported method to perform a salt minion upgrade on windows is `salt abc pkg.latest salt-minion` using the https://github.com/saltstack/salt-winrepo-ng/blob/master/salt-minion-py3.sls

Salt-Minion needs to be uninstalled before being installed again as a newer version.  Windows does not allow open files to be overwritten. Hence Salt has to be stopped/killed, which cause the minion to disconnect from the master in the middle of the run.    With recent changes you should get a response back to the salt-master most of the time, however the software will not have been upgraded yet.  It will be upgraded a few minutes later.
