### ISSUE TITLE
problem in salt-ssh scan roster

### ISSUE THREAD

**Issue by sahama** [saltstack/salt#47381]
### Description of Issue/Question
when i use scan roster it seems roster file necessary that it should not be.

 aslo
i configured salt as `https://github.com/saltstack/salt/issues/46891#issuecomment-385148734`
when i use wrong port in scan roster like this `salt-ssh  --roster==scan --scan-ports=23 "127.0.0.1" --user=root --passwd=1 cmd.run whoami` i see this result:

    [ERROR   ] Unable to load range library
    localhost:
      root

this mean salt-ssh used default port 22 for ssh

also if i use `salt-ssh  --roster==scan --scan-ports=23 "127.0.0.1" --user=root --passwd=1 cmd.run whoami` is:

    [ERROR   ] Unable to load range library
    [CRITICAL] Unable to make cachedir /var/tmp/.root_659579_salt/running_data/var/cache/salt/minion/file_lists/roots
    [CRITICAL] Unable to make cachedir /var/tmp/.root_659579_salt/running_data/var/cache/salt/minion/file_lists/roots
    [CRITICAL] Unable to make cachedir /var/tmp/.root_659579_salt/running_data/var/cache/salt/minion/file_lists/roots
    [CRITICAL] Unable to make cachedir /var/tmp/.root_659579_salt/running_data/var/cache/salt/minion/file_lists/roots
    [CRITICAL] Unable to make cachedir /var/tmp/.root_659579_salt/running_data/var/cache/salt/minion/file_lists/roots
    [CRITICAL] Unable to make cachedir /var/tmp/.root_659579_salt/running_data/var/cache/salt/minion/file_lists/roots
    [CRITICAL] Unable to make cachedir /var/tmp/.root_659579_salt/running_data/var/cache/salt/minion/file_lists/roots
    [CRITICAL] Unable to make cachedir /var/tmp/.root_659579_salt/running_data/var/cache/salt/minion/file_lists/roots
    localhost:
    ----------
              ID: create test file
        Function: file.managed
            Name: /root/delme
          Result: False
         Comment: Source file salt://sample_file not found in saltenv 'base'
         Started: 06:59:20.125257
        Duration: 19.701 ms
         Changes:   

    Summary for localhost
    ------------
    Succeeded: 0
    Failed:    1
    ------------
    Total states run:     1
    Total run time:  19.701 ms

i explained it in [this issue](https://github.com/saltstack/salt/issues/46891#issuecomment-385148734)

**Comment by gtmanfred** [comment]
Is this a regression from 2017.7? or is it in both 2018.3 and 2017.7?

**Comment by isbm** [comment]
@gtmanfred I would say this is a bug that wasn't really tested before. And not much people are using this, hence did not reported. :wink:

**Comment by Ch3LL** [comment]
Not a regression.  As @isbm stated this just was probably not tested before.

**Comment by gtmanfred** [comment]
Cool, i was just wondering if it needed to be fixed right now for 2018.3.1, or if it could wait.

**Comment by nergdron** [comment]
I just upgraded to salt=3000, and started seeing this error. now I'm not using the scan roster, but it seems like this maybe was fixed and has just regressed? I'm not sure. salt was installed via `pip3 install salt=3000` on Ubuntu 19.04, and wasn't emitting this error with 2019.02.x.

**Comment by Ch3LL** [comment]
this particular issue is related to the salt-ssh scan roster not picking up the port form the cli args. If you are not using the scan roster its most likely not related to this issue and would need to create a new one.

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
