### ISSUE TITLE
Unable to connect to a low end Cisco switch (SG220) using salt proxy

### ISSUE THREAD

**Issue by sk1988** [saltstack/salt#47392]
### Description of Issue/Question

I have recently setup salt proxy minion on the server which is also salt-master.  I am able to communicate with Cisco IOS device using salt-proxy.  There are also various other Arista EOS switches I am able to directly register to salt master as a minion.  However, there is a low end **Cisco SG220 switch** which I am unable to setup salt proxy for.  I have tried both napalm/ios and networkswitch proxy and it is failing in both cases.

### Setup

in /srv/pillar:

# cat top.sls
base:
  dumbdevice:
    - dumbdevice
#

# cat dumbdevice.sls
proxy:
  proxytype: networkswitch
  host: 10.43.64.59
  username: xxxx
  passwd: xxxx

#

### Steps to Reproduce Issue

I have initially configured the device for proxy type napalm and driver IOS (similar to another Cisco switch which is working fine).  This is however a very low end Cisco switch, so I have also tried changing it to proxytype **networkswitch**.  I have deleted the salt-key for the device and ran **sudo systemctl start salt-proxy@dumbdevice** and continue to see the below logs.  Do I need a separate extension or software for proxytype networkswitch?  Please let me know if you need more details and I can provide them accordingly.

NetMikoAuthenticationException: Authentication failure: unable to connect cisco_ios dumbdevice:22
NetMikoAuthenticationException: Authentication failure: unable to connect cisco_ios dumbdevice:22
NetMikoAuthenticationException: Authentication failure: unable to connect cisco_ios dumbdevice:22
NetMikoAuthenticationException: Authentication failure: unable to connect cisco_ios dumbdevice:22
NetMikoAuthenticationException: Authentication failure: unable to connect cisco_ios dumbdevice:22

NetMikoAuthenticationException: Authentication failure: unable to connect cisco_ios smtwq-mgtac-001.mgmt:22
Authentication failed.
2018-04-30 03:46:20,772 [/usr/lib/python2.7/site-packages/salt/utils/napalm.pyc:228 ][ERROR   ][7586] Cannot execute "get_facts" on [unspecified hostname] as . Reason: not connected!
2018-04-30 03:46:20,772 [/usr/lib/python2.7/site-packages/salt/utils/napalm.pyc:229 ][ERROR   ][7586] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 158, in call
    raise Exception('not connected')
Exception: not connected

2018-04-30 03:46:23,191 [/usr/lib/python2.7/site-packages/salt/utils/napalm.pyc:228 ][ERROR   ][7586] Cannot execute "get_facts" on [unspecified hostname] as . Reason: not connected!
2018-04-30 03:46:23,191 [/usr/lib/python2.7/site-packages/salt/utils/napalm.pyc:229 ][ERROR   ][7586] Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 158, in call
    raise Exception('not connected')
Exception: not connected

### Versions Report

# salt --versions-report
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 4.4.110-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

#

**Comment by sk1988** [comment]
Understand.  If you need either a running-config or "show tech" from the device or any other outputs from the device, please let me know and I can attach them for your reference.

In the meanwhile, could you please let me know regarding this question?

**Do I need a separate extension or software for proxytype networkswitch?**

Or is there a list on which Cisco switch hardware models are supported under networkswitch proxy?  I saw the below logs on /var/log/salt/proxy, but they are not appearing anymore.

2018-04-30 03:33:15,313 [salt.minion      :3305][ERROR   ][23169] Proxymodule networkswitch is missing an init() or a shutdown() or both. Check your proxymodule.  Salt-proxy aborted.
2018-04-30 03:33:15,314 [salt.cli.daemons :532 ][ERROR   ][23169] Proxymodule networkswitch is missing an init() or a shutdown() or both. Check your proxymodule.  Salt-proxy aborted.

**Comment by gtmanfred** [comment]
So, i do not actually see a proxy minion module for `networkswitch` I believe that one is just an example of how it would be setup.

**Comment by leeclemens** [comment]
I can reproduce this with an `SG300`, looks like it fails to establish the SSH connection. I tried `salt-ssh` as well and get:

```
# salt-ssh -c ./etc/salt sg300 test.ping
sg300:
    ----------
    retcode:
        255
    stderr:
        packet_write_wait: Connection to <switch IP> port 22: Broken pipe
    stdout:
        <user>@<switch IP>'s password: 
```

pillar:
```
proxy:
  proxytype: napalm
  driver: ios
  host: x.y.z
  username: xxx
  passwd: xxx
```

pcap shows:
`Salt`: Client: SSH-2.0-paramiko_2.4.1
`Switch`: Server: SSH-2.0-OpenSSH_5.9p1.RL
`Salt`: Ack
`Switch`: Rst, Rst

When salt-proxy fails to connect, the switch logs:
```
%AAA-I-CONNECT: User CLI session for user <user> over ssh , source <salt IP> destination  <switch IP> ACCEPTED
```

I can SSH successfully from the salt server's command line (CentOS 7.4)
```
Salt Version:
           Salt: 2018.3.0-2650-g63b5391
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: 3.2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by whytewolf** [comment]
I also own a couple of SG300's and an sg500 all of which use the same OS as the sg220. These devices are not napalm capable. They do not use a true version of iOS,  even if you got them to connect through ssh napalm would not know what to do with them. I have been looking for add on napalm drivers for them but have not found one yet.

I did get napalm to connect to my sg500 however because of the differences in the OS napalm didn't know it was connected because the commands do not line up with what it is expecting.

**Comment by whytewolf** [comment]
so, little more info. 

Latest versions of netmiko does support sg300 as a driver. however napalm does not look to have bindings into sg300 to use netmiko with sg300 command interface. 

This looks like an update to napalm for these devices is needed. to add a driver that uses netmiko for sg300 style devices.

**Comment by whytewolf** [comment]
One more piece. 

I did find a sg350 community driver for napalm. However, the commands are just too different than my sg500 or sg300 for it to work. 

This could mean in order to support all of the sg* line of switches. We might need one of every kind just to make sure that the command syntax works between them.

**Comment by mirceaulinic** [comment]
Hey guys. Thanks for clarifying this @whytewolf - yes, it's a general issue with Cisco platforms to be completely different in terms of commands and their output provided. If you know the maintainers of the sg350 community driver for napalm, please inform them that they might want to submit their driver to https://github.com/napalm-automation-community so everyone will be aware of their work. Thanks!

**Comment by whytewolf** [comment]
@micahhausler The napalm driver for sg350's is already a member of https://github.com/napalm-automation-community. That is how I found it. https://github.com/napalm-automation-community/napalm-s350

Btw thank you for all the sweet work on Napalm.

**Comment by micahhausler** [comment]
Wrong user

**Comment by whytewolf** [comment]
@micahhausler sorry about that.

**Comment by mirceaulinic** [comment]
@sk1988 is there anything you'd like to add here, or can we close?

**Comment by sk1988** [comment]
We are good to close this one.  Thank you all.
