### ISSUE TITLE
nxos_ssh ntp is making changes to devices and saying otherwise!

### ISSUE THREAD

**Issue by sk1988** [saltstack/salt#47426]
### Description of Issue/Question

I am using NAPALM proxy module nxos_ssh to manage my Cisco Nexus switch and I am currently testing some changes on the device.  I created a ntp_config file which I am pushing to the device.  It is taking a long time for it to generate output and while salt is making changes on the device, it is throwing an error that it couldn't commit_config.

### Setup

cat ntp_config.sls
ntp.servers:
  - 10.5.116.144
  - 10.5.113.246

 cat n305wl19.sls
proxy:
  proxytype: napalm
  driver: nxos_ssh
  host: n305wl19
  username: xxxx
  passwd: xxxx
  prompt_name: n305wl19
  ssh_args: '-o PubkeyAuthentication=no'
  key_accept: True
include:
  - ntp_config

### Steps to Reproduce Issue

salt n305wl19 state.sls router.ntp
n305wl19:
----------
          ID: update_my_ntp_config
    Function: netntp.managed
      Result: False
     Comment: Unable to commit the changes: Cannot execute "commit_config" on n305wl19 as xxxx. Reason: Error while applying config!!.
                      Will try to rollback now!
     Started: 02:38:21.166869
    Duration: 26677.809 ms
     Changes:
              ----------
              servers:
                  ----------
                  added:
                      - 10.5.116.144
                      - 10.5.113.246

Summary for n305wl19
------------
Succeeded: 0 (changed=1)
Failed:    1
------------
Total states run:     1
Total run time:  26.678 s
ERROR: Minions returned with non-zero exit code

The configuration has been applied to the device, but it shows an error.  When I run the same command again, the output says "Device configured properly".

salt n305wl19 state.sls router.ntp
n305wl19:
----------
          ID: update_my_ntp_config
    Function: netntp.managed
      Result: True
     Comment: Device configured properly.
     Started: 02:39:12.594522
    Duration: 1607.223 ms
     Changes:

Summary for n305wl19
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   1.607 s

**On a Cisco IOS device, the same configuration goes through normally in the first instance itself, albeit rather slow:**

salt c205wz01 state.sls router.ntp
c205wz01:
----------
          ID: update_my_ntp_config
    Function: netntp.managed
      Result: True
     Comment:
     Started: 02:52:52.717125
    Duration: 68634.826 ms
     Changes:
              ----------
              servers:
                  ----------
                  added:
                      - 10.5.116.144
                      - 10.5.113.246

Summary for c205wz01
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  68.635 s

### Versions Report

 salt --versions-report
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 4.4.110-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by gtmanfred** [comment]
@mirceaulinic if you could look at this one too, that would be great.

Thanks,
Daniel
