### ISSUE TITLE
"salt-cloud -m" fails with nova driver: "There was a query error: u'state'"

### ISSUE THREAD

**Issue by bcharron** [saltstack/salt#47424]
### Description of Issue/Question

When I run "salt-cloud -m <map file>" with the nova driver, if a VM from that map already exists, I get the following error:

```
[INFO    ] Applying map from 'blah'.
[DEBUG   ] Could not LazyLoad nova.optimize_providers: 'nova.optimize_providers' is not available.
[DEBUG   ] The 'nova' cloud driver is unable to be optimized.
[DEBUG   ] LazyLoaded versions.warn_until
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[ERROR   ] There was a query error: u'state'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 303, in run
    dmap = mapper.map_data()
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 2005, in map_data
    matching = get_matching_by_name(name)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1994, in get_matching_by_name
    matches[driver] = details['state']
KeyError: u'state'
```

### Setup

I have an Openstack cloud provider using the driver "nova". (I wasn't able to get the openstack driver to work correctly in my environment, hence why I stuck with nova for now.)

I've worked around the issue by changing "status" to "state" in `salt/utils/openstack/nova.py:server_list_min()`, but I don't know if that breaks anything else.

Might be of interest: both `server_list()` and `server_list_detailed()` define the attribute "state", but `server_list_min()` defines "status".

### Steps to Reproduce Issue

Using the nova cloud provider, spawn a map using "salt-cloud -m <map file>". Once the VMs are created, run "salt-cloud -m <map file>" again.

### Versions Report
```
Salt Version:
            Salt: 2018.3.0

Dependency Versions:
 Apache Libcloud: 2.0.0
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: Not Installed
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
           ioflo: Not Installed
          Jinja2: 2.8.1
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.13 (default, Mar 27 2017, 16:47:34)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 14.5.0
            RAET: Not Installed
           smmap: Not Installed
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.0.5

System Versions:
            dist: centos 6.7 Final
          locale: UTF-8
         machine: x86_64
         release: 2.6.32-696.16.1.el6.x86_64
          system: Linux
         version: CentOS 6.7 Final
```

**Comment by gtmanfred** [comment]
> I have an Openstack cloud provider using the driver "nova". (I wasn't able to get the openstack driver to work correctly in my environment, hence why I stuck with nova for now.)

First, what was the problem you were having with the openstack driver, and why hasn't that been reported?


And yes, the nova driver should be reporting `state` instead of status, I will submit a PR to fix this.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Also, i highly recommend using the newer openstack driver, or reporting stuff so we can get it fixed, because that driver behaves much better and supports all the newer openstacks and keystonev3 much better.

**Comment by bcharron** [comment]
To answer the question raised in the first reply, I had the following problems with the openstack driver:
- VMs would automatically take a floating-ip. This seemed possibly related to #31762
- I was unable to get `userdata` working in openstack. (`userdata_file` works for me in nova.)

The recommendation in #31762 seemed to be "use nova". Given that I'm dealing with an older release of Openstack, I wasn't sure it was appropriate to report these issues.. Let me know if I should, I'll gladly debug them.

(Apologies if this re-opens the issue!)

**Comment by gtmanfred** [comment]
If you do not want it to automatically get a floating_ip address, set `auto_ip` to False in the profile.

As for userdata, were you passing a path to a file, or the contents of the file?

I will need to check that one.

Thanks,
Daniel
