### ISSUE TITLE
redis_cache fails to create or read anything ever

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#47439]
### Description of Issue/Question

The `redis` minion data cache is unable to store anything in Redis despite correct configuration.

### Setup
```
cache.redis.host: redis.server
cache.redis.port: 6379
cache.redis.db: '0'
cache.redis.password: superAwesomePassword123
cache: redis
```

### Steps to Reproduce Issue
1. run `salt \* pillar.items` or something to build the cache
2. run `salt-run cache.grains tgt='*'` to retrieve the cache
3. receive nothing instead

Inspect logs, see this for every attempt to write to the cache:
```
2018-05-02 12:09:24,335 [salt.template    :26  ][PROFILE ][24328] Time (in seconds) to render '/srv/pillar/common/init.sls' using 'yaml' renderer: 0.00437879562378
2018-05-02 12:09:24,336 [/usr/lib/python2.7/dist-packages/salt/cache/redis_cache.pyc:300 ][DEBUG   ][24328] Adding minion.name to $BANK_minions
2018-05-02 12:09:24,336 [salt.master      :1783][ERROR   ][24328] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1776, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1487, in _pillar
    'pillar': data})
  File "/usr/lib/python2.7/dist-packages/salt/cache/__init__.py", line 156, in store
    return self.modules[fun](bank, key, data, **self._kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/cache/redis_cache.py", line 346, in store
    key=key, bank=bank, redis_key=redis_key
  File "/usr/lib/python2.7/logging/__init__.py", line 1155, in debug
    self._log(DEBUG, msg, args, **kwargs)
TypeError: _log() got an unexpected keyword argument 'redis_key'
```
It looks like this may be specific to `_log()` and not necessarily related to storing anything in the cache, but either way, it goes away when `cache: redis` is disabled, and there's nothing else related to redis in the cache. Still, there is never anything stored in Redis. Using `redis-cli` shows nothing in `db0` at all, even if I initialize the db with some other data first.

### Versions Report
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: 11.2.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.25.1
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.25.1
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.2.0-042stab111.11
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
can you try the fix in https://github.com/saltstack/salt/pull/46989

**Comment by V3XATI0N** [comment]
That patch fixes the issue where the cache module can't write to the cache. However, I must completely misunderstand the purpose of an external cache module. It was my understanding that this mechanism would allow multiple masters to share a minion data cache such that the cache would be available from any one of the masters. But instead, only one master can store its cache in redis at a time. Is this expected behavior, and if so, are there any plans at all to develop a multi-master setup capable of truly sharing the minion data cache?
