### ISSUE TITLE
Remove/update release warning banner on new/upcoming release note pages

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#47431]
### Description of Issue/Question
We always add a new release notes file after the next stable release launches. For example, [2018.3.1 release notes](https://docs.saltstack.com/en/latest/topics/releases/2018.3.1.html) exist. This is done so people can add changes to the file as we prepare for the 2018.3.1 release.

Since the 2018.3.1 release is presently not the current stable release, nor is it in the `develop` branch, a warning banner displays at the bottom of the page:

```
These release notes are for an old release of Salt. This release might contain known security and other issues that are fixed in the latest release.
```

This is incorrect and confusing. At the very least, we need to remove that banner for "future" release notes. 

It would be even better to have a warning there still, but change the text to say that it is an unreleased version presently. This approach would make it even more clear that those release notes are for a version that has not be released yet.

**Comment by Ch3LL** [comment]
just verified this is working. closing for now :)

**Comment by Ch3LL** [comment]
actually re-opening 2017.7.6 doesn't seem to be showing changes. will check into that

**Comment by Ch3LL** [comment]
this is halfway fixed. It now does not show the warning on in progress releases. But we want to implement an approach that will automatically notfiy the user that this is an in progress release without having to manually add this to the release notes each time. So I will keep open until we can implement this.
