### ISSUE TITLE
Ubuntu 18.04 package on repo.saltstack.org

### ISSUE THREAD

**Issue by jellisii** [saltstack/salt#47434]
### Description of Issue/Question

Currently there is no option to deploy to Ubuntu 18.04/bionic from repo.saltstack.com.

Is there an estimated date for this to happen?

**Comment by Ch3LL** [comment]
we are working on building packages for the next release :)

**Comment by Ch3LL** [comment]
by next release I mean the next dot release. So 2018.3.1 and 2017.7.6 will be the first releases for which ubuntu18 packages will be provided from repo.saltstack.com.

**Comment by kartiksubbarao** [comment]
Cool, thanks for the clarification.

**Comment by Deshke** [comment]
any timeframe for 2018.3.1?

**Comment by Ch3LL** [comment]
We are currently fixing up a couple more issues found during the testing phase then we will re-test and package then release. We are shooting for next week if things go well during testing :)

**Comment by Deshke** [comment]
thanks

**Comment by Ch3LL** [comment]
we have pushed ubuntu 18 packages up now for 2017.7.6 and 2018.3.1 :)
