### ISSUE TITLE
Input validation does not raise SaltInvocationError in win_dsc.py

### ISSUE THREAD

**Issue by skylerberg** [saltstack/salt#47443]
### Description of Issue/Question

Browsing the tool LGTM, I saw several errors that are initialized but not raised for input validation in win_dsc.py: https://lgtm.com/projects/g/saltstack/salt/snapshot/cea932162130f65040b889fc4e2f0f3bae98c27d/files/salt/modules/win_dsc.py?sort=name&dir=ASC&mode=heatmap&showExcluded=false#L722

Looking at `SaltInvocationError` and its base class, there doesn't seem to be any magic happening on initialization that would cause the error to be automatically raised. My conclusion is that this is likely a mistake and the input validation routines are most likely not doing anything.

The impact of this is that the powershell command that this code generates could be malformed or have invalid values.

I considered potential security ramifications, but I think there are not any because this would just allow powershell cmd injection on servers where you can already run modules with salt. Please let me know if I have overlooked any security concerns around this.

**Comment by garethgreenaway** [comment]
@dwoz Since you self-assigned I'll let you determine the issue status, eg. bug or not, and the severity.

**Comment by dwoz** [comment]
@garethgreenaway This doesn't look like it has any real security impact. It does look pretty buggy however. I will patch for the bug and make sure we have tests.
