### ISSUE TITLE
Issue with file.managed contents: and existing file

### ISSUE THREAD

**Issue by cmconner156** [saltstack/salt#47457]
### Setup

I checked the develop branch and this is still broken there.   The fix is super simple, it's caused because we never initiate "ret" in the situation where contents is set and the file already exists.  I've attached a diff if you want it.
[salt_file_managed_contents.zip](https://github.com/saltstack/salt/files/1971730/salt_file_managed_contents.zip)

If you create a salt state that uses a managed file plus contents and the file exists already on the OS, the get_diff method fails. 

Example:

/root/.cifscreds:
  file.managed:
    - contents:
      - username=user1
      - password=user1password

Error:

2018-05-03 11:56:36,572 [salt.state       :310 ][ERROR   ][25584] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/state.py", line 1905, in call
    **cdata['kwargs'])
  File "/usr/lib/python3.4/site-packages/salt/loader.py", line 1830, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.4/site-packages/salt/states/file.py", line 2396, in managed
    **kwargs
  File "/usr/lib/python3.4/site-packages/salt/modules/file.py", line 4738, in check_managed_changes
    group, mode, attrs, saltenv, contents)
  File "/usr/lib/python3.4/site-packages/salt/modules/file.py", line 4847, in check_file_meta
    differences = get_diff(name, tmp, show_filenames=False)
  File "/usr/lib/python3.4/site-packages/salt/modules/file.py", line 5025, in get_diff
    return ret
UnboundLocalError: local variable 'ret' referenced before assignment

The lines in above stack are slightly off as I added some instrumentation to make sure I knew what the issue was.
      
### Steps to Reproduce Issue
You create an sls with managed file that uses contents like:

/root/.cifscreds:
  file.managed:
    - contents:
      - username=user1
      - password=user1password

Try to apply it and it will fail.

### Versions Report

Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.8 (default, Mar 23 2018, 10:04:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.5

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 4.16.3-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by garethgreenaway** [comment]
This has been fixed in https://github.com/saltstack/salt/pull/47405 and will be available in 2018.3.1.
