### ISSUE TITLE
net.load_config is not working and net.cli is not working as expected

### ISSUE THREAD

**Issue by sk1988** [saltstack/salt#47468]
### Description of Issue/Question

net.load_config is not working across various vendors connected to the salt-master

### Setup
**I am trying to load a line of configuration directly from the command line which seems to be failing.**

```
[root@vm07 pillar]# salt -G 'os:eos' \ net.load_config \ text='ntp server 10.5.113.246'
sto-001b:
    ' net.load_config' is not available.
sto-001a:
    ' net.load_config' is not available.
leaf-019:
    ' net.load_config' is not available.
ERROR: Minions returned with non-zero exit code
[root@vm07 pillar]# salt -G 'os:ios' \ net.load_config \ text='ntp server 10.5.113.246'
c205wz01:
    ' net.load_config' is not available.
ERROR: Minions returned with non-zero exit code
[root@vm07 pillar]# salt -G 'os:nxos_ssh' \ net.load_config \ text='ntp server 10.5.113.246'
n305wl19:
    ' net.load_config' is not available.
ERROR: Minions returned with non-zero exit code
[root@vm07 pillar]#
[root@vm07 pillar]# salt -G 'vendor:Cisco' \ net.load_config \ text='ntp server 10.5.113.246'
n305wl19:
    ' net.load_config' is not available.
c205wz01:
    ' net.load_config' is not available.
ERROR: Minions returned with non-zero exit code
[root@vm07 pillar]#
```
**If I try the same from a file, I am also noticing an error for all device types:**
```
[root@vm07 pillar]# pwd
/srv/pillar
[root@vm07 pillar]# cat ntpconfig.cfg
ntp server 10.5.113.246
ntp server 10.5.116.144
[root@vm07 pillar]# salt -G 'os:eos' net.load_config /srv/pillar/ntpconfig.cfg
sto-001b:
    ----------
    already_configured:
        False
    comment:
        Cannot execute "compare_config" on None as None. Reason: Error [1000]: CLI command 2 of 2 'show session-config named napalm_588867 diffs' failed: could not run command [Session napalm_588867 does not exist]!
    diff:
        None
    loaded_config:
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 153, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/lib/python2.7/site-packages/napalm_eos/eos.py", line 176, in load_merge_candidate
            self._load_config(filename, config, False)
          File "/usr/lib/python2.7/site-packages/napalm_eos/eos.py", line 145, in _load_config
            with open(filename, 'r') as f:
        IOError: [Errno 2] No such file or directory: '/srv/pillar/ntpconfig.cfg'
```

**I am also noticing that the net.cli is very sensitive for Arista devices and it is expecting the command in full to provide the output.  See below for example:**

On Arista:
```
[root@vm07 pillar]# salt -G 'os:eos' net.cli "show ver | i Uptime"
sto-001b:
    ----------
    comment:
        Cannot execute "cli" on None as None. Reason: {u'show ver | i Uptime': u'Invalid command: "show ver | i Uptime"'}!
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 153, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/lib/python2.7/site-packages/napalm_eos/eos.py", line 572, in cli
            raise CommandErrorException(str(cli_output))
        CommandErrorException: {u'show ver | i Uptime': u'Invalid command: "show ver | i Uptime"'}
```
**If I execute the full command (version instead of ver and include instead of i, it works fine, as shown below.  In the case of Arista devices, it seems the NAPALM code is trying to assess the command's validity, instead of letting the target device decide on its own.**
```
[root@vm07 pillar]# salt -G 'os:eos' net.cli "show version | include Uptime"
sto-001b:
    ----------
    comment:
    out:
        ----------
        show version | include Uptime:
            Uptime:                 24 weeks, 6 days, 21 hours and 42 minutes
    result:
        True
```
On Cisco IOS, it seems to be doing the right thing:
```
[root@vm07 pillar]# salt -G 'os:ios' net.cli "show ver | i uptime"
c205wz01:
    ----------
    comment:
    out:
        ----------
        show ver | i uptime:
            c205wz01 uptime is 2 years, 7 weeks, 6 days, 8 hours, 48 minutes
    result:
        True
[root@vm07 pillar]#
```
### Steps to Reproduce Issue
Already provided in the above output.

### Versions Report
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 18 2016, 15:58:25)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 4.4.110-1.el7.elrepo.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**configuration from /etc/salt/master:**

file_roots:
  base:
    - /srv/salt
    - /srv/salt/states

pillar_roots:
  base:
    - /srv/pillar

**Comment by garethgreenaway** [comment]
@sk1988 Thanks for the report.  The first example you included it appears that the slashes might be the cause of the commands not running.  Salt is attempting to run using a module named ` net.load_config`, which does not exist.  The other examples the errors seem to be coming back from the devices themselves, perhaps the command syntax is not supported?
@mirceaulinic DO you have any additional thoughts on this one?

**Comment by sk1988** [comment]
Thank you.  I modified my initial command and used \ in the correct manner and that seems to work now.

In all other cases, the issue still exists.  The device doesn't throw an error if I run the below command on the device directly.

smtwq-sto-001b#show ver | i Uptime
Uptime:                 25 weeks, 2 days, 18 hours and 56 minutes
smtwq-sto-001b#

The error shows up only through SALT.

[root@vm07 pillar]# salt 'smtwq-sto-001b' net.cli 'show ver | i Uptime'
smtwq-sto-001b:
    ----------
    comment:
        Cannot execute "cli" on None as None. Reason: {u'show ver | i Uptime': u'Invalid command: "show ver | i Uptime"'}!
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 153, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/lib/python2.7/site-packages/napalm_eos/eos.py", line 572, in cli
            raise CommandErrorException(str(cli_output))
        CommandErrorException: {u'show ver | i Uptime': u'Invalid command: "show ver | i Uptime"'}
[root@vm07 pillar]#

If I run the full command using SALT, that works fine.  This is what makes me think that SALT is probably trying to evaluate if the command is right instead of letting the device decide it.

[root@vm07 pillar]# salt 'smtwq-sto-001b' net.cli 'show version | include Uptime'
smtwq-sto-001b:
    ----------
    comment:
    out:
        ----------
        show version | include Uptime:
            Uptime:                 25 weeks, 2 days, 18 hours and 58 minutes
    result:
        True
[root@vm07 pillar]#

**Comment by cathode911** [comment]
issue is still reproducing with arista 
root@nvpa-nwksalt-01:~# salt-master --version
salt-master 2019.2.0 (Fluorine)

Minion is 2018.3.0-2772-g34b3b90 (Oxygen)

`root@nvpa-nwksalt-01:~# salt 'nvpa-spine-01' net.cli "show version"
nvpa-spine-01:
    ----------
    comment:
    out:
        ----------
        show version:
            Arista vEOS
            Hardware version:
            Serial number:
            System MAC address:  0050.5604.ca70

            Software image version: 4.20.1F
            Architecture:           i386
            Internal build version: 4.20.1F-6820520.4201F
            Internal build ID:      790a11e8-5aaf-4be7-a11a-e61795d05b91

            Uptime:                 10 minutes
            Total memory:           4011524 kB
            Free memory:            2967608 kB

    result:
        True`

`root@nvpa-nwksalt-01:~# salt 'nvpa-spine-01' net.cli "show ver"
nvpa-spine-01:
    ----------
    comment:
        Cannot execute "cli" on None as None. Reason: {u'show ver': u'Invalid command: "show ver"'}!
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/usr/lib/python2.7/site-packages/salt/utils/napalm.py", line 167, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/usr/lib/python2.7/site-packages/napalm/eos/eos.py", line 635, in cli
            raise CommandErrorException(str(cli_output))
        CommandErrorException: {u'show ver': u'Invalid command: "show ver"'}`

**Comment by Arderos** [comment]
+1

**Comment by kiawizard** [comment]
Please look into this, the issue prevents reusing existing short-style control scripts via salt
