### ISSUE TITLE
MySQL Comments Can Cause mysql_query.run_file to Fail

### ISSUE THREAD

**Issue by doc987** [saltstack/salt#47488]
**Comments with ```--```:** Comments in sql files that start with ```--``` and continue to the end of the line are not recognized when by ```salt.states.mysql_query.run_file```.  That state calls ```salt.modules.mysql.file_query```, which uses ```re.match``` to ignore lines that _begin_ with ```--```.  However, comments that are later on the line are not ignored, but instead are included in the ```query_string```.  Since ```query_string``` is a concatenation of the lines in the file, a ```--``` will comment out the rest of the concatenated query.

**Comments with ```#```:** These can't be used with ```run_file``` because they are not recognized by ```run_file```.  MySQL will recognize them, but I don't think they're standard SQL.

**Comments with ```/* ... */```:** These seem to work okay because concatenating lines doesn't break this type of comment.

**Comments Containing a Semicolon:** These can't be used inside a comment in a query with ```run_file``` because they're interpreted as ending the query, whether using ```--```, ```#```, or ```/* ... */```.

**Error Messages:** One result of the lines being concatenated is the any syntax error (caused by this, or otherwise) always reports a problem on line 1, which can make it difficult to locate the problem.  When I tried running a file directly (```mysql < input.sql```), it ran with no issues, but running the same file with ```run_file``` failed.

Salt Version: 2017.7.3

**Comment by gtmanfred** [comment]
Thanks for reporting this.  A pr to fix it would be greatly appreciated.

Thanks
Daniel

**Comment by doc987** [comment]
Some additional code could be written to parse the input better (which may be able to handle most cases).  If one wanted to handle *any* SQL provided, I think an actual SQL parser would be needed.  Some possible approaches are:
1. Write a new SQL parser.
2. Use an existing SQL parser.  One option is https://github.com/andialbrecht/sqlparse.  Splitting a string into individual statements can be done as shown below.
```python
import sqlparse
statements = sqlparse.split(sql_string)
```
3. Don't parse the SQL.  Send the whole file directly to MySQL, and let MySQL do the parsing.

**Comment by gtmanfred** [comment]
I think that 2 or 3 seems fine, if you can switch it to just sending the whole sql file in python i think that would be the better option.

**Comment by doc987** [comment]
Looks like 3 can be done with either MySQLdb or mysql.connector, and with nearly the same code (example of each below).  I imagine some of this would replace code in ```file_query()``` in modules/mysql.py.  However, since this is a query, it partially steps on the what ```query()``` is doing (```file_query()``` is currently using ```query()```).  I wonder if ```query()``` should be modified to be able to accept a string with multiple queries in it, or ```query()``` should only be used for single queries.
```python
# MySQLdb
import MySQLdb
conn = MySQLdb.connect(host='host',database='database',user='user',password='password')
cursor = conn.cursor()
sql = "Query 1 ...; Query 2 ...; Query 3 ...;"
cursor.execute(sql)
while cursor.nextset():
  pass
cursor.close()
conn.commit()
conn.close()
```
```python
# mysql.connector
import mysql.connector
conn = mysql.connector.connect(host='host',database='database',user='user',password='password')
cursor = conn.cursor()
sql = "Query 1 ...; Query 2 ...; Query 3 ...;"
result = cursor.execute(sql,multi=True)
for x in result:
  pass
cursor.close()
conn.commit()
conn.close()
```

Another alternative is use a child process (https://stackoverflow.com/a/4563950).

**Comment by mchugh19** [comment]
Still valid

**Comment by mchugh19** [comment]
Not stale and or #54371 should fix it

**Comment by DmitryKuzmenko** [comment]
Here's the official MariaDB documentation related to supported SQL code comments style.
https://mariadb.com/kb/en/comment-syntax/
Just a formality.
