### ISSUE TITLE
mysql_query.run_file Doesn't Work when query_file = salt://...

### ISSUE THREAD

**Issue by doc987** [saltstack/salt#47491]
The input file (```query_file```) for ```salt.states.mysql_query.run_file``` doesn't accept a file using a ```salt://``` URL.

As a workaround, I used ```file.managed``` for the ```query_file``` and then used ```run_file``` on the managed file.

Salt Version: 2017.7.3

**Comment by gtmanfred** [comment]
Great idea, I implemented that here #47508

Thanks,
Daniel

**Comment by doc987** [comment]
Nice!  Excited to see this in the next release.
