### ISSUE TITLE
Document that the table_out outputter's virtual name is just 'table'

### ISSUE THREAD

**Issue by manish-kumar1993** [saltstack/salt#47509]
### Description of Issue/Question
I am running below YAML command and getting 
"[ERROR   ] Invalid outputter table_out specified, fall back to nested" error
CLI 
 sudo salt '*' oracle.run_query my_db "select to_char(sysdate,'dd-mm-yyyy') from dual" --output table_out
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Run sudo salt '*' oracle.run_query my_db "select to_char(sysdate,'dd-mm-yyyy') from dual" --output table_out
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 17:41:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: oracle 7.5
         locale: UTF-8
        machine: x86_64
        release: 4.1.12-61.1.18.el7uek.x86_64
         system: Linux
        version: Oracle Linux Server 7.5

**Comment by gtmanfred** [comment]
The virtualname for is just `table`

can you try 

`Run sudo salt '*' oracle.run_query my_db "select to_char(sysdate,'dd-mm-yyyy') from dual" --output table`

Thanks,
Daniel
