### ISSUE TITLE
service.enable (and .disable) destroys /etc/rc.conf on FreeBSD

### ISSUE THREAD

**Issue by psagers** [saltstack/salt#47502]
### Description of Issue/Question

Enabling/disabling a service on FreeBSD removes all newlines from /etc/rc.conf.

This appears to have been introduced in b3c1be27fbe0538b75622a3bca33c00f46602aa1 with the addition of an `.rstrip('\n')` and no corresponding changes to the subsequent string handling.

### Setup
None.

### Steps to Reproduce Issue
`salt-call service.enable validservicename`

/etc/rc.conf will be rewritten without newlines. Of course this also impacts enabling a service during state application.

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Dec 24 2017, 00:02:42)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: amd64
        release: 11.1-RELEASE-p8
         system: FreeBSD
        version: Not Installed

**Comment by stromnet** [comment]
For the record, this just fried one of my remote systems too. Luckily I could get some remote hands and restore rc.conf via backup.

**Comment by stromnet** [comment]
@psagers, @rallytime; since you added commit with fix, pinging you. 

Looking at the referenced commit b3c1be2, it seem like at least one more locations should be patched? It seems to have the same mode of operation. 

https://github.com/saltstack/salt/blob/develop/salt/modules/freebsd_sysctl.py#L147

**Comment by psagers** [comment]
I wouldn't be surprised; it looked rather like a copy/paste bug, but I didn't look around for others. At the time, I was more focused on a minimal fix for speedy acceptance.

Where rc.conf is concerned, this should probably be relying on the [sysrc module](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.sysrc.html), which itself sensibly calls [sysrc(8)](https://www.freebsd.org/cgi/man.cgi?query=sysrc&sektion=0). I just haven't circled back to put together a more comprehensive pull request yet.

I don't believe there's an equivalent for sysctl, although perhaps it can express its line-editing operation using the file module.

**Comment by ari** [comment]
Perhaps it should write to etc/rc.conf.d/appname instead?

**Comment by stromnet** [comment]
Agree on using sysrc module.

As for rc.conf.d, it would require some additional logic to see if it is already set in rc.conf (in case of changes), to know where to change?

**Comment by silenius** [comment]
please, please, please ... would it be possible to add a test case for this... it was "silently hidden" during 2018.3.0 upgrade and caused (tons of) machines/VM to become unbootable ...

thanks

**Comment by ari** [comment]
On the plus side, 2018.3.0 was such a buggy release (especially on FreeBSD) that I can't figure how anyone even managed to get it to run. The -O1 optimisation in FreeBSD ports completely broke it. So the impact is less than it might have been.
