### ISSUE TITLE
File.line and file.replace are strange

### ISSUE THREAD

**Issue by Angelo-Verona** [saltstack/salt#47512]
### Description of Issue/Question

I found file.line and file.replace utterly confusing

I would like to get file.replace to fail if the pattern is not found, it seems that the state will never fail if the pattern is not found salt will report "No changes needed to be made" doesn't matter if I set it to ignore_if_missing: False or True.
So I can't use onfail hook in another state on it.

file.line on other hand seems totally uncontrollable as it removes anything randomly if "ensure" mode is used and before and after will remove something respectively to ensure that the line is inserted right after. Ensure shouldn't delete anything just insert if not found.

Or did I miss something?

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.5.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Ch3LL** [comment]
First of all can you clarify that you are refering to the state module and not execution modules? My answers below are based off the fact that you are using the state modules when running into these issues.

looking at the `file.replace` state module looks indeed that it is only catching errrors for cases where the `name` argument is not supplied or if the file does not exist. As you can see here https://github.com/saltstack/salt/blob/v2018.3.0/salt/states/file.py#L4113-L4126 if the file exists and name is set then it just checks for changes. We could probably set an argument that checks for if the file actually replaces something or not and fails if its not found. ill approve as a feature request. 

`file.line`: can you include an example. i'm not seeing easily where in the code this would be occurring.
