### ISSUE TITLE
sshconfig salt-ssh roster is missing in the documentation

### ISSUE THREAD

**Issue by joesusecom** [saltstack/salt#47511]
### Description of Issue/Question
Even the most recent documentation at https://docs.saltstack.com/en/develop/ref/roster/all/index.html doesn't mention the sshconfig roster that's shipping in 2018.3.0.

### Steps to Reproduce Issue
Open https://docs.saltstack.com/en/develop/ref/roster/all/index.html  and look for the sshconfig roster.

### Versions Report
Bug applies to both Develop and 2018.3.0 documentation on the web. I haven't double-checked whether the docs are completely missing or just not linked into the tree.

**Comment by gtmanfred** [comment]
I have added them here.

#47531
