### ISSUE TITLE
Many processes are running for salt master and salt minion

### ISSUE THREAD

**Issue by venkat-koppisetti** [saltstack/salt#47537]
#**Description of Issue/Question**
Many processes are running for salt master and salt minion

#**Setup**
#**OS version:**
[root@localhost ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

#**Docker version:**
[root@localhost ~]# docker --version
Docker version 18.03.0-ce, build 0520e24

#**Steps to Reproduce Issue**
Run below command inside docker container for both salt-master and salt-minion
#**for salt-master:**
[root@740feb5d2864 /]# ps -ef | grep salt
root        48     1  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root        80    48  0 12:33 ?        00:00:01 /usr/bin/python /usr/bin/salt-master
root        82    48  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root        83    48  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root        87    48  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root        90    87  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root        91    87  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root        92    87  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root       100    87  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root       101    87  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master
root       107    87  0 12:33 ?        00:00:00 /usr/bin/python /usr/bin/salt-master

#**for salt-minion:**
[root@d8239b59c5a5 /]# ps -ef | grep salt
root        49     1  0 11:48 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
root        69    49  0 11:48 ?        00:00:01 /usr/bin/python /usr/bin/salt-minion
root       246     1  0 12:49 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion

#**Dockerfile for salt-master:**
FROM centos:7
ENV container docker
RUN yum -y install epel-release && \
    yum -y update; yum clean all && \
    yum -y install salt-master
VOLUME [ "/sys/fs/cgroup" ]
RUN sed -i "/#interface: 0.0.0.0/c\interface: $(hostname -I)" /etc/salt/master; systemctl enable salt-master
CMD ["/usr/sbin/init"]

#**Dockerfile for salt-minion:**
FROM centos:7
ENV container docker
RUN yum -y install epel-release && \
    yum -y update; yum clean all && \
    yum -y install salt-minion
VOLUME [ "/sys/fs/cgroup" ]
ARG master_ip
RUN sed -i "/#master: salt/c\master: $master_ip" /etc/salt/minion; systemctl enable salt-minion
CMD ["/usr/sbin/init"]

#**Versions Report**
[root@740feb5d2864 /]# salt --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.5.1
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by Ch3LL** [comment]
this is expected behavior. if you install setproctitle you can see the process names. Different processes are setup for different parts of salt such as Mworkers. By default there are 5 mworkers so you will have have 5 master processes alone for that. 

Are you running into a separate issue that led you to thinking this was an issue?

**Comment by venkat-koppisetti** [comment]
I just wanted to know why many processes are running, what are those processes?

Am running salt-master and salt-minion as a separate container.
For salt-master nearly 11 processes are running and 3 processes for salt-minion

**Comment by rdutch** [comment]
Have a look at the documentation here, which gives an high level overview about the different salt processes and their function.
https://docs.saltstack.com/en/latest/topics/development/architecture.html
