### ISSUE TITLE
Target dependent issue when using salt-ssh

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#47560]
### Description of Issue/Question

When using salt-ssh I get error as follows,

decide() doesn't take any arguments

Target has Python 2.6.6 installed 
How to fox this?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@sumeetisp Thanks for the report.  What version of Salt-SSH are you using?  Can you provide the output from the command:
`salt --versions-report`

The last version of Salt that supported Python 2.6.x was 2016.11.

**Comment by sumeetisp** [comment]
I am using salt 2017.7.1

So salt-ssh will use the python installed on the target machine?

Thanks,
Sumeet Salvankar

**Comment by sumeetisp** [comment]
salt-ssh will be using python installed on target machine?

**Comment by garethgreenaway** [comment]
That is correct. There is not a minion running on the target but all the required code is securely copied over to the target and run with the version of Python installed there.
