### ISSUE TITLE
Incorrect warning message in firewalld.present state function

### ISSUE THREAD

**Issue by nhavens** [saltstack/salt#47579]
Starting in version 2018.3.0, the firewalld.present state function has the following warning message for users that fail to provide a prune_services argument:

> The \'prune_services\' argument default is currently True, but will be changed to **True** in future releases.

I believe the bolded True in the warning message should be **False**.

PR #43780 introduced the warning message, but the fix should be easy.

**Comment by Ch3LL** [comment]
fixed in https://github.com/saltstack/salt/pull/47590 thanks for bringing this to our attention
