### ISSUE TITLE
 custom development saltstack expansion pack, stored in a module_dirs directory ，ImportError: cannot import name 

### ISSUE THREAD

**Issue by qihanglys** [saltstack/salt#47583]
### Description of Issue/Question
we custom development saltstack expansion pack, stored in a module_dirs directory，But sometimes after code updates module_dirs, sometimes encountered similar error (__virtual__ returned False: always import a name XXXX)

### Setup
salt-minion configuration 
module_dirs: /opt/dir

### Steps to Reproduce Issue

The actual scene, to make it easier to customize the needs of the business, we custom development saltstack expansion pack, stored in a module_dirs directory, this way to solve our actual demand.But sometimes after code updates module_dirs, sometimes encountered similar error (__virtual__ returned False: always import a name XXXX), reboot after salt - minion problem solving.Want to make sure the code extensions directory after the release of the code is not to resume the salt - a minion, there are better ways to make salt - new minion process dynamic identification code logic

2018-05-09 19:07:44.039 [salt.minion                                                                  ] [INFO    ] Starting a new job with PID 29915
2018-05-09 19:07:44.043 [salt.loader                                                                  ] [DEBUG   ] Failed to import module biziptables:
Traceback (most recent call last):
  File "/opt/local/saltstack/python/lib/python2.7/site-packages/salt/loader.py", line 1411, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/opt/bizsalt/salt-agent/biziptables.py", line 12, in <module>
    from  biz_lib.biz_iptables import iptables_set
  File "/opt/bizsalt/salt-agent/biz_lib/biz_iptables/iptables_set.py", line 16, in <module>
    from  biz_lib.common.saltagent_api import get_osversin
ImportError: cannot import name get_osversin

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt --versions-report
Salt Version:
           Salt: 2017.7.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Apr 21 2017, 19:44:49)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.2
 
System Versions:
           dist: redhat 5.8 Tikanga
         locale: GBK
        machine: x86_64
        release: 2.6.18-308.24.1.el5
         system: Linux
        version: Red Hat Enterprise Linux Server 5.8 Tikanga

**Comment by Ch3LL** [comment]
possibly using the `__salt__` object as explained here: https://github.com/saltstack/salt/issues/39678#issuecomment-282769603 would allow more dynamic imports.
