### ISSUE TITLE
salt-cloud UnicodeDecodeError when using UTF-8 characters in script-args

### ISSUE THREAD

**Issue by donoles** [saltstack/salt#47584]
Having utf-8 characters in --script-args salt-cloud produces an error trying to actually run the deployment script.

[ERROR   ] There was a query error: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 343, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2237, in run_map
    profile, local_master=local_master
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/ec2.py", line 2760, in create
    for key, value in six.iteritems(__utils__['cloud.bootstrap'](vm_, __opts__)):
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 566, in bootstrap
    deployed = deploy_script(**deploy_kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1514, in deploy_script
    deploy_command += ' {0}'.format(script_args)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 21: ordinal not in range(128)

### Versions Report
#salt-cloud --versions-report
Salt Version:
            Salt: 2018.3.0

Dependency Versions:
 Apache Libcloud: 1.5.0
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.4.2
       docker-py: Not Installed
           gitdb: 0.6.4
       gitpython: 1.0.1
           ioflo: Not Installed
          Jinja2: 2.8
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: 1.0.3
    msgpack-pure: Not Installed
  msgpack-python: 0.4.6
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
    python-gnupg: Not Installed
          PyYAML: 3.11
           PyZMQ: 15.2.0
            RAET: Not Installed
           smmap: 0.9.0
         timelib: Not Installed
         Tornado: 4.2.1
             ZMQ: 4.1.4

System Versions:
            dist: Ubuntu 16.04 xenial
          locale: UTF-8
         machine: x86_64
         release: 4.4.0-119-generic
          system: Linux
         version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
can you paste a sanitized version of what you are using for your script args. i'm not replicating this with `-A master.升` included in the script args.

**Comment by donoles** [comment]
It's like
salt-cloud --out=txt --assume-yes --map=foo.map --script-args "fooo rene.foobar 'René Foobar'"

**Comment by donoles** [comment]
One more interesting thing. When the deployment script in its output also had that é, the salt-cloud capturing its output also produced UnicodeDecodeError, but only when it was run from the cron job, but when run from regular login console, it did not! I guess something must be in environment to make python behave differently.
Techically it's the regular Ubuntu AWS instance, and the salt stuff comes from
deb http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial main
