### ISSUE TITLE
proxy_hostid keeps updating in zabbix_host.present

### ISSUE THREAD

**Issue by paulrolandw** [saltstack/salt#47588]
### Description of Issue/Question

zabbix_host.present keeps updating the host on every state.apply, although proxy_host is not configured and there is no proxy_host.

### Setup

{% set zabbix_url = 'http://someurl/api_jsonrpc.php' %}
{% set zabbix_user = 'Admin' %}
{% set zabbix_password = 'zabbix' %}

create_host_{{ grains['id'] }}:
  zabbix_host.present:
    - _connection_user: {{ zabbix_user }}
    - _connection_password: {{ zabbix_password }}
    - _connection_url: {{ zabbix_url }}
    - host: {{ grains['id'] }}
    - groups:
      - Linux
    - interfaces:
      - {{ grains['id'] }}:
        - ip: 192.168.1.69
        - type: Agent
        - port: 10050

### Steps to Reproduce Issue

root@master:/srv/salt# salt linux1 state.apply zabbix_add
linux1:
----------
          ID: create_host_group
    Function: zabbix_hostgroup.present
        Name: Linux
      Result: True
     Comment: Host group Linux already exists.
     Started: 13:16:56.294667
    Duration: 328.253 ms
     Changes:
----------
          ID: create_host_linux1
    Function: zabbix_host.present
      Result: True
     Comment: Host linux1 updated.
     Started: 13:16:56.623507
    Duration: 976.858 ms
     Changes:
              ----------
              proxy_hostid:
                  None

Summary for linux1
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time:   1.305 s
root@master:/srv/salt#

### Versions Report

Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1057-aws
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
looks like `update_proxy` was added here: https://github.com/saltstack/salt/pull/40107

ping @mchugh19  any ideas here

**Comment by Ch3LL** [comment]
awesome thanks for pointing this out i'll go ahead and close the issue :)
