### ISSUE TITLE
salt builds for SUSE/OPENSUSE/SLES

### ISSUE THREAD

**Issue by dafenko** [saltstack/salt#47592]
### Description of Issue/Question
I'm looking for actual (2017.7.x) salt builds for SUSE/SLES/OPENSUSE.
Can you please suggest how can I get SUSE/SLES/OPENSUSE build?

I found only RedHat  and amazon linux RPMs for 2017.7.x (e.g. 2017.7.5) in salt-stack repo.
Am I supposed to use RedHat packages for SUSE?

### Setup
N/A

### Steps to Reproduce Issue
1. I've synced full repo:
rsync -vaH --numeric-ids --delete --delete-after --delay-updates rsync://repo.saltstack.com/saltstack_pkgrepo_full ./fullrepo

2. I found no rpm packages for suse
 find . -name *.rpm | grep -i suse | grep 2017 | wc -l
 0

I found only RedHat  and amazon linux RPMs for 2017.7.x (e.g. 2017.7.5) or 2018.3.

### Versions Report
2017.7
2018.3

**Comment by Ch3LL** [comment]
my understanding is that there are not 2017.7 packages available which are managed through the opensuse company..

maybe @saltstack/team-suse has some ideas on workarounds to install that version?

**Comment by isbm** [comment]
@dafenko we do not support 2017.7 for SLES. Please either use 2016.11.4, available for SLES or switch to 2018.3 directly, which will be also available on SLE 15 on Python 3.
