### ISSUE TITLE
Documentation: Debian versions wrong

### ISSUE THREAD

**Issue by heini** [saltstack/salt#47606]
On https://docs.saltstack.com/en/latest/topics/installation/debian.html it says:

> Stretch (Testing) and Sid (Unstable) distributions are already contain mostly up-to-date Salt
> packages built by Debian Salt Team. You can install Salt components directly from Debian.
>
> On Jessie (Stable) there is an option to install Salt minion from Stretch with python-tornado
> dependency from jessie-backports repositories.

This has meanwhile changed to:
* Jessie -> Oldstable
* Stretch -> Stable
* Buster -> Testing

**Comment by Ch3LL** [comment]
fixed in https://github.com/saltstack/salt/pull/47611  from what I can tell there is only old salt packages in the main debian repositories so I tried to update the docs to reflect that.
