### ISSUE TITLE
salt myminion dockerng.ps filters    is not working 

### ISSUE THREAD

**Issue by sam0104** [saltstack/salt#47605]
### Description of Issue/Question
salt myminion dockerng.ps filters    is not working  . I am trying to fetch data from all docker containers ( running and stopped ) Ports : { PrivatePort } and { PublicPort }  but I am not able to get it using filters.  

Example : 
salt minion dockerng.ps filters="{'Labels':}"
salt minion dockerng.ps filters="{'Ports':}"
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 3.2.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by Ch3LL** [comment]
as you can see form teh docs here: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockermod.html#salt.modules.dockermod.ps

the only available filters are:

>exited (int): Only containers with specified exit code
>status (str): One of restarting, running, paused, exited
>label (str): format either "key" or "key=value"

so your port filter will not work. Your label filter is incomplete you will need to include which label you are filtering for. 

When i tried this example: `salt-call --local dockerng.ps all=True filters='{"status": "exited"}'` it worked on all containers stopped and running and returned exited containers
