### ISSUE TITLE
salt minion exists when server refuses the key.

### ISSUE THREAD

**Issue by itamarjp** [saltstack/salt#47602]
mai 10 16:43:21 fedora systemd[1]: Started The Salt Minion.
mai 10 16:43:21 fedora salt-minion[2636]: [ERROR   ] Command '/usr/sbin/zpool list -H -p -o name,size' failed with return code: 1
mai 10 16:43:21 fedora salt-minion[2636]: [ERROR   ] output: connect: No such file or directory
mai 10 16:43:21 fedora salt-minion[2636]: Please make sure that the zfs-fuse daemon is running.
mai 10 16:43:21 fedora salt-minion[2636]: internal error: failed to initialize ZFS library
mai 10 16:43:24 fedora salt-minion[2636]: [CRITICAL] The Salt Master has rejected this minion's public key!
mai 10 16:43:24 fedora salt-minion[2636]: To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
mai 10 16:43:24 fedora salt-minion[2636]: Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
mai 10 16:43:24 fedora systemd[1]: salt-minion.service: Main process exited, code=exited, status=77/n/a
mai 10 16:43:24 fedora systemd[1]: salt-minion.service: Failed with result 'exit-code'.

**Comment by Ch3LL** [comment]
this is expected behavior to stop when the key cannot be accepted by the master. Can you elaborate why you think this is a bug?
