### ISSUE TITLE
[Feature request] Add bhyve support to virt

### ISSUE THREAD

**Issue by jeroen92** [saltstack/salt#47619]
### Description of Issue/Question
I'm in the process of setting up an automated VM provisioning pipeline in which Salt is going to play the main character :) Since bhyve now has some decent libvirt support, I'd like to build in support for bhyve into Salt as well.

Bhyve has a limitation in that it can only handle raw disks (or images), so we can't use the qcow format. Cloning/creating ZFS zvols would be a nice option instead.

I've already written a working implementation. PR will be uploaded in a minute.

**Comment by Ch3LL** [comment]
Thanks for the PR! We always appreciate that :)
