### ISSUE TITLE
Conditionally Include an SLS File

### ISSUE THREAD

**Issue by doc987** [saltstack/salt#47627]
I want to run a whole group of states based on a single condition.  Is that possible?

**Named Include States:** One way to do it might be to conditionally include an SLS file, but I haven't found a way to make that work.  Named include states (https://github.com/saltstack/salt/issues/14899#issuecomment-51994564) may work by allowing requisites for a whole SLS file, but that issue is currently open.

**Jinja Variables:** I tried setting a Jinja variable, and then enclosing the group of states inside a template ```if``` statement.  This didn't work in this case because the template is rendered before any of the states are run, and the necessary package to set the Jinja variable doesn't get installed until earlier states are run (and after template rendering).

**Comment by Ch3LL** [comment]
Have you looked at the workarounds in that Named include states. Seems there are a couple of workarounds in that issue with a couple of caveats but might work for your use case?

**Comment by doc987** [comment]
Are you talking about using a Jinja include statement, i.e. ```{% include 'state_file.sls' %}```?  I think this would work in the same instances where using Jinja variables would work, and also fails in the same instances where Jinja variables fail.  In particular, the instance I mentioned, i.e. the necessary package to evaluate the condition is not installed at the time of the template rendering.

**Comment by Ch3LL** [comment]
So if i understand it right you want to be able to run a bunch of states based on whether a package is installed, but the problem you are running into is jinja is rendered first and the package is not installed until later in the states. I believe this is the problem you are trying to solve but correct me if i'm wrong.

- one solution i can think up of is using orchestration to orchestrate the order of states and keeping the jinja logic you added initially to see if a package is installed

- you can use a different renderer such as the py renderer where you will get a lot more power by using the python language. 

- use a new feature in 2018.3.0 refered to as slots: https://docs.saltstack.com/en/latest/topics/slots/index.html  this is rendered right before the state execution, where as jinja is rendered much earlier.

hopefully that gives you some ideas on how to approach this.

**Comment by doc987** [comment]
Not based on whether a package is installed.  Doing the check requires a package.  For example, suppose I want to run a state if a database exists.
```
{% if salt.modules.mysql.db_exists(dbname) %}
...
{% endif %}
```
or assign a variable
```
{% set db_exists = salt.modules.mysql.db_exists(dbname) %}
{% if db_exists %}
...
{% endif %}
```
I can't use ```db_exists()``` until the necessary mysql package(s) are installed.  Even though the package is installed by the time any contents of the section would get run.  The ```if``` fails because it's evaluated at render time.  I think named include states could get around this because requisites could be used instead of Jinja.

**Comment by Ch3LL** [comment]
agreed the feature you pointed to is probably a good approach i'm just setting out some workarounds as that feature is still open and is not currently being worked on as other issues are higher priority.

anyone from @saltstack/team-core have any other workaround ideas?

**Comment by gtmanfred** [comment]
The only solution would be to use the orchestration runner to run multiple state runs, one to install the stuff needed to run the jinja in the next.

**Comment by felixmarch** [comment]
Any news on this issue?
