### ISSUE TITLE
salt-api on different container then salt-master

### ISSUE THREAD

**Issue by msupinodn** [saltstack/salt#47629]
### Description of Issue/Question
is there a way to run salt-api in a different container then salt-master ? i see it tries to connect to 
tcp://127.0.0.1:4506, i have shared the ipc directory between the two containers, 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
2 containers, one running salt-master, one running salt-api, ipc directory shared

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
[INFO    ] [13/May/2018:11:31:03] ENGINE Bus STARTED
[INFO    ] [api_acl] Authentication not checked for user test from IP 10.0.0.20
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'salt-master_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[INFO    ] [api_acl] Authentication not checked for user test from IP 10.0.0.20

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: 3.3.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.11+ (default, Apr 17 2016, 14:00:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.13.0-32.35-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
i'm actually not sure if this is even possible. ping @saltstack/team-netapi any ideas here?

**Comment by msupinodn** [comment]
i found a way, i shared the directory with the IPC files between the containers, and configured the interface in the salt-api container with the IP of the salt-master container

it will be nice if salt-api was de-coupled from the master, there is no real reason for them to be attached.

**Comment by metashock** [comment]
@msupinodn 
>and configured the interface: in the salt-api container config file with the IP of the salt-master container

Wich value did you change in the config?

**Comment by msupinodn** [comment]
the value of interface

https://docs.saltstack.com/en/2017.7/ref/configuration/master.html#interface
