### ISSUE TITLE
[Tornado 5.0] TCPClientKeepAlive._create_stream is broken with tornado 5.0

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#47630]
I am making this issue for @sergeizv 

We are running into an issue with the TCP transport having problems sending back to the master, and it is being broken by the overriding function you created here for the keep alive stuff.

We are looking at it, but any help you could provide would be great.

To reproduce this, install the 2018.3.1 branch of salt, and then install tornado 5.0 and pyzmq 17.0.0 with that branch, and try to connect a minion to the master with the tcp transport.  We are seeing it fail to connect to the master using the overriding function.  Then once we just comment out the function, it tries to connect, and sends data to the master process, and then the port seems to be closed, and no response comes back.

Thanks for the help.

Daniel

**Comment by gtmanfred** [comment]
If you get a chance to help us with this, the test that we are running to replicate this is.

`python -m tests.runtests -v -n unit.transport.test_tcp.AESReqTestCases.test_basic`

Thanks,
Daniel

**Comment by gtmanfred** [comment]
We got it working.

Daniel

**Comment by sergeizv** [comment]
Hi, Daniel,

Always glad to help, but it seems that the code in the question is authored by @skizunov :)

**Comment by gtmanfred** [comment]
Bah, you are right, thanks
