### ISSUE TITLE
salt-key --delete= depends on minion service status

### ISSUE THREAD

**Issue by doxmebro** [saltstack/salt#47657]
### Description of Issue/Question
When using `salt-key --delete=hostname`, the actual status of weather it get's deleted or not depends on the state of the salt-minion. If the service is running, the key won't get deleted. If it's not running, it will.

Not sure if this is intended behaviour, it's unintuitive for me at least.

### Setup
No sls files.

### Steps to Reproduce Issue

Initially there are no keys:

    root@ubuntu-xenial:/srv/salt# salt-key --list all
    Accepted Keys:
    Denied Keys:
    Unaccepted Keys:
    Rejected Keys:
At this point, I ping from minion node (status currently running).

    root@ubuntu-xenial:/srv/salt# salt-key --list all
    Accepted Keys:
    Denied Keys:
    Unaccepted Keys:
    ubuntu-xenial
    Rejected Keys:
Attempting to delete, but doesn't get deleted.

    root@ubuntu-xenial:/srv/salt# salt-key --delete=ubuntu-xenial
    The following keys are going to be deleted:
    Unaccepted Keys:
    ubuntu-xenial
    Proceed? [N/y] y
    Key for minion ubuntu-xenial deleted.
    root@ubuntu-xenial:/srv/salt# salt-key --list all
    Accepted Keys:
    Denied Keys:
    Unaccepted Keys:
    ubuntu-xenial
    Rejected Keys:
At this point, I `service salt-minion stop`. Try to delete again; this time it works

    root@ubuntu-xenial:/srv/salt# salt-key --delete=ubuntu-xenial
    The following keys are going to be deleted:
    Unaccepted Keys:
    ubuntu-xenial
    Proceed? [N/y] y
    Key for minion ubuntu-xenial deleted.
    root@ubuntu-xenial:/srv/salt# salt-key --list all
    Accepted Keys:
    Denied Keys:
    Unaccepted Keys:
    Rejected Keys:

### Versions Report

    Salt Version:    
    Salt: 2018.3.0    
    Dependency Versions:    
    cffi: Not Installed    
    cherrypy: Not Installed    
    dateutil: 2.4.2    
    docker-py: Not Installed    
    gitdb: 0.6.4    
    gitpython: 1.0.1    
    ioflo: Not Installed    
    Jinja2: 2.8    
    libgit2: Not Installed    
    libnacl: Not Installed    
    M2Crypto: Not Installed    
    Mako: 1.0.3    
    msgpack-pure: Not Installed    
    msgpack-python: 0.4.6   
    mysql-python: Not Installed   
    pycparser: Not Installed    
    pycrypto: 2.6.1    
    pycryptodome: Not Installed    
    pygit2: Not Installed    
    Python: 2.7.12 (default, Dec  4 2017, 14:50:18)    
    python-gnupg: Not Installed   
    PyYAML: 3.11    
    PyZMQ: 15.2.0    
    RAET: Not Installed    
    smmap: 0.9.0    
    timelib: Not Installed    
    Tornado: 4.2.1    
    ZMQ: 4.1.4    
    System Versions:    
    dist: Ubuntu 16.04 xenial   
    locale: UTF-8   
    machine: x86_64    
    release: 4.4.0-124-generic    
    system: Linux    
    version: Ubuntu 16.04 xenial

Minion comes from straight from this vagrant box: [https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box](https://cloud-images.ubuntu.com/xenial/current/xenial-server-cloudimg-amd64-vagrant.box)

**Comment by gtmanfred** [comment]
What is happening here, you have the minion running, and then you delete the key from Unaccepted, then the minion continues to try and connect every 10 seconds, so it gets put back in Unaccepted.

You will either need to stop the minion, or just reject the key and the minion will stop trying to be accepted.

Daniel
