### ISSUE TITLE
subprocess error when enabling ext_nodes

### ISSUE THREAD

**Issue by johnj** [saltstack/salt#47655]
### Description of Issue/Question

When tops/ext_nodes.py is loaded, with python 3, there is an AttributeError thrown by the subprocess call:

`2018-05-14 01:22:09,735 [salt.daemons.masterapi:548 ][ERROR   ][16707] Top function ext_nodes failed with error 'int' object has no attribute 'communicate' for minion minion1...
`

The tops from ext_nodes do not get merged in from there.

### Setup

ext_nodes is enabled via:

`master_tops:
  ext_nodes: /path/command
`

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 23 2017, 16:37:01)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-104-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by terminalmage** [comment]
This was already fixed in https://github.com/saltstack/salt/pull/46863, and backported to 2018.3 in https://github.com/saltstack/salt/pull/46872.

**Comment by johnj** [comment]
Thanks!
