### ISSUE TITLE
Use source_hash and source_hash_name even with salt:// uris

### ISSUE THREAD

**Issue by yannj-fr** [saltstack/salt#47660]
### Description of Issue/Question
I am trying to reduce deployment time when deploying a large amount of files. 
The current behaviour when using salt:// scheme is to instanciate a file client and request the hash from the master for each file which, in some environment with latency and a high number of minions leads to delays and high load.

My proposal is to also be able to provide the source_hash or source_hash_name for files served by salt.
This way when writing sls files, the hash can be included and reduce the number of messages.

If this make sense, I will provide a patch.

**Comment by gtmanfred** [comment]
@terminalmage do you have an opinion on this?

Thanks,
Daniel

**Comment by yannj-fr** [comment]
Additionnaly, the behaviour look strange for me:
- in get_managed (modules/file.py), the method cp.hash_file is called to get the source_sum, this will result in a call to the master
- a few time after that, the call to manage_file (in the method managed states/files.py) will always result in a call to the method cache_file (as the availability of the file for scheme == 'salt' is not performed before). This will also ask for the checksum from the server...

I think this could be optimized
