### ISSUE TITLE
yum-complete-transaction module/state

### ISSUE THREAD

**Issue by leeclemens** [saltstack/salt#47685]
### Description of Issue/Question
It may be helpful for some to be able to call `yum-complete-transaction` as a module/state, instead of directly from `cmd.run`. The available option is `--cleanup-only`, and it may be useful to allow for it to be called recursively via the config.

### Setup
Feature request, would require a system using yum and with `yum-complete-transaction` (`yum-utils`) installed.

### Steps to Reproduce Issue
None, feature request

### Versions Report
Not available in 2018.3.1

Discussion/Question: Should this be implemented under the virtual package `salt.modules.pkg` (I'm not sure how many other package management systems have a similar functionality) or only by directly addressing `salt.modules.yumpkg` directly or ___?

**Comment by gtmanfred** [comment]
if it gets put in yumpkg.py, it will be available in pkg.whatever, on yum based systems.

I am marking this as a feature request.

PRs are greatly appreciated.

Thanks,
Daniel

**Comment by leeclemens** [comment]
PR updated to only include the module (for now, potentially) after discussion.
