### ISSUE TITLE
Do you support active mode? 

### ISSUE THREAD

**Issue by topicgit** [saltstack/salt#47699]
### Description of Issue/Question
Do you support active mode? The client automatically goes to master synchronization.
### Setup
I want the client to synchronize automatically

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by gtmanfred** [comment]
You just want the minion to check in every so often?

Just schedule a cron job for a highstate, or use the salt scheduler to schedule a state run however often.

**Comment by gtmanfred** [comment]
https://docs.saltstack.com/en/latest/ref/cli/salt-call.html

**Comment by topicgit** [comment]
Like salt-call, I want salt-minion to automatically synchronize my module with the salt-master every 10 minutes. In this way, I only need to maintain the salt-master, and the client will automatically update. Can I support this?

**Comment by gtmanfred** [comment]
if you run a highstate on the minion every 10 minutes using the scheduler, it will do all that.

Why do you want to do it this way?  That is not the way salt is designed.  Salt is designed to push only when you have meaningful change or actually expect things to change.

You can do this by just running saltutil.sync_all in a schedule as well to just do it, but we do not have an eventual consistency model, so salt only does things when it is directed to, or scheduled in the scheduler or reactor.

**Comment by topicgit** [comment]
Like salt-call, I want salt-minion to automatically synchronize my module with the salt-master every 10 minutes. In this way, I only need to maintain the salt-master, and the client will automatically update. Can I support this?

**Comment by topicgit** [comment]
I know, thank you for your answer.
