### ISSUE TITLE
2017.7.5 zpool.present does not check for properties=None before attempting to enumerate properties

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#47696]
#37932 is not fixed in 2017.7.5

The zpool state still attempts to enumerate the contents of 'properties' when properties is None throwing a ```TypeError: 'NoneType' object is not iterable```

https://github.com/saltstack/salt/blob/19bb725698c1ead096a06749d99aad59266fbad8/salt/states/zpool.py#L199

It is fixed in 2018.  Can the fix be backported?

https://github.com/saltstack/salt/blob/fb3bf1ff3e8593b60b515ff6d40ed87a5a6d846c/salt/states/zpool.py#L269

**Comment by gtmanfred** [comment]
Unfortunately there was a huge change between 2017.7 and 2018.3, so it can't be easily backported.

https://github.com/saltstack/salt/commit/3f30ab2ed66#diff-817aa4ecf848121d64232f521f7894bbR268

If you wanted to submit a smaller change just to fix this issue, we would be more than happy to include it in 2017.7, just open a PR against the 2017.7 branch.

Thanks!
Daniel
