### ISSUE TITLE
win_servermanager state throwing value error - Fluorine is misspelled

### ISSUE THREAD

**Issue by parkerbyron** [saltstack/salt#47715]
### Description of Issue/Question

In version 2018.3.0 When running states that use the win_servermanager to install windows features I am getting a ValueError that states Named Version 'Flourine' is not known - the o and u in Fluorine are swapped and I suspect this is triggering the error.

### Setup

Here is from a state that worked previously

    Function: win_servermanager.installed
        Name: Web-Common-HTTP
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1878, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_servermanager.py", line 119, in installed
                  'Parameter \'force\' has been detected in the argument list. This'
                File "c:\salt\bin\lib\site-packages\salt\utils\versions.py", line 116, in warn_until
                  version = salt.version.SaltStackVersion.from_name(version)
                File "c:\salt\bin\lib\site-packages\salt\version.py", line 278, in from_name
                  'Named version \'{0}\' is not known'.format(name)
              ValueError: Named version 'Flourine' is not known
     Started: 12:54:49.158419
    Duration: 0.0 ms
     Changes:

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

I can reproduce it every time running a win_servermanager to install a feature

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Minion Version (Master is the same):
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

Thanks!
Parker Byron

**Comment by Ch3LL** [comment]
thanks for bringing this to our attention. i'm working on a PR right now. i also noticed other instances of misspellings for this. Will get this fixed up with a test so we don't run into this again. thanks

**Comment by GitHubAre** [comment]
Hello,
How can I get fixed version? Right now there is no release that is containing it - any plans of making a new release soon?

Right now the only thing of getting the fix is pulling the development branch?
