### ISSUE TITLE
Cannot ping minion after iptables changes

### ISSUE THREAD

**Issue by johje349** [saltstack/salt#47746]
### Description of Issue/Question
After setting iptables INPUT policy to drop on a new minion the master cannot ping the minion. 
This is done by reactor on salt/cloud/*/created event which runs highstate, where a number of iptables rules are set ending with setting INPUT policy to drop. A while after that the following can be seen in the master log:
```
2018-05-21 11:17:05,173 [salt.state       :275 ][ERROR   ][7488] Run failed on minions: asx-b-r13
Failures:
    asx-b-r13:
        Minion did not respond

2018-05-21 11:17:05,174 [salt.state       :1915][INFO    ][7488] Completed state [run-highstate] at time 11:17:05.174134 duration_in_ms=161963.265
```
I've tried setting master_alive_interval but it didn't help.

### Setup
Minion config:
```
hash_type: sha256
id: asx-jj1
log_level: info
master: 10.133.45.67
master_alive_interval: 10
```

iptables on master:
```
-P INPUT DROP
-P FORWARD DROP
-P OUTPUT ACCEPT
-A INPUT -i lo -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 8 -j ACCEPT
-A INPUT -p icmp -m icmp --icmp-type 0 -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
-A INPUT -i eth1 -p tcp -m multiport --dports 4505,4506 -m state --state NEW,ESTABLISHED -j ACCEPT
-A INPUT -s 10.133.45.143/32 -i eth1 -p tcp -m state --state NEW,ESTABLISHED -m tcp --dport 8181 -j ACCEPT
-A INPUT -s 10.133.45.143/32 -i eth1 -p tcp -m state --state NEW,ESTABLISHED -m tcp --dport 22 -j ACCEPT
-A INPUT -s 10.133.45.143/32 -i eth1 -p udp -m udp --dport 53 -j ACCEPT
```

### Steps to Reproduce Issue
Create a new VM using salt-cloud.

Test ping:
```
root@asx-salt:~# salt 'asx-jj1' test.ping
asx-jj1:
    True
```

Run iptables command on VM:
```
root@asx-jj1:~# iptables -A INPUT -i lo -j ACCEPT
root@asx-jj1:~# iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
root@asx-jj1:~# iptables -A INPUT -s 10.133.45.67/32 -i eth1 -p tcp -m state --state NEW,ESTABLISHED -m tcp --dport 22 -j ACCEPT
root@asx-jj1:~# iptables -P INPUT DROP
```

Test ping again:
```
root@asx-salt:~/asx-salt/salt/scripts# salt -l debug 'asx-jj1' test.ping
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: asx-salt
[DEBUG   ] Missing configuration file: /home/johan.jerrang/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: asx-salt
[DEBUG   ] Missing configuration file: /home/johan.jerrang/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'asx-salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/94/9e6e1fdee60c9731d7675dfed0be5eaae6b6b2e7e3fc8c6dfb8cea50d1dbe6/.minions.p
[DEBUG   ] get_iter_returns for jid 20180521132915629148 sent to set(['asx-jj1']) will timeout at 13:29:35.642921
[DEBUG   ] Checking whether jid 20180521132915629148 is still running
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'asx-salt_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] retcode missing from client return
[DEBUG   ] return event: {'asx-jj1': {'failed': True}}
[DEBUG   ] LazyLoaded localfs.init_kwargs
[DEBUG   ] LazyLoaded localfs.init_kwargs
[DEBUG   ] LazyLoaded no_return.output
asx-jj1:
    Minion did not return. [No response]

```

Restart the minion or wait 5(?) minutes and ping works again.

### Versions Report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-121-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
The salt master does not connect to the minion at all.

What happens instead is the minion opens a listening connection outbound on the masters port 4505, and waits for events to be published.  You can check on the master to see if the minion is still connected using `ss -ntlp` and see if the minion stays connected, or you can try using presence to see if the master sees the minion still listening, but there is not a lot that we can do if iptables is knocking out the connection.

You could add a restart of the salt minion to the end of your states, because they will keep running even if the minion disconnects, you will just lose the results of that state run.

Daniel

**Comment by johje349** [comment]
I added input policy deny after highstate completes, and then restart the minion. This seems to work fine.
