### ISSUE TITLE
Can't schedule state.highstate with salt-2018.3.0

### ISSUE THREAD

**Issue by edgan** [saltstack/salt#47743]
### Description of Issue/Question
I want to schedule the state.highstate from the master config, but found it doesn't work from the master. I also tried it from the minion config, but it did nothing.

It seems PR #39791 removed this ability. I tried reverting the change, and it didn't work. Though I still think that scheduling it from the master is simpler, and ideal. Why change the minion on every system when we could just change the master.

### Errors
/var/log/salt/master:
```
2018-05-21 00:47:32,463 [salt.utils.schedule:737 ][ERROR   ][17535] Unhandled exception running state.highstate
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 652, in handle_func
    message=self.functions.missing_fun_string(func))
  File "/usr/lib/python2.7/dist-packages/salt/utils/error.py", line 36, in raise_error
    raise ex(message)
Exception: 'state.highstate' is not available.
```

### Setup
/etc/salt/master or /etc/salt/minion:
```
schedule:
  highstate:
    function: state.highstate
    minutes: 1
    splay:
      start: 10
      end: 15
```

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.3
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1052-aws
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by edgan** [comment]
I got it working via the pillar method.

I realized another reason it would be better implemented from the master. The splay is a very poor choice from the minion's perspective. Where as if the master splayed per minion, it would be far better. Even better would be batch mode from issue #30214 .

**Comment by gtmanfred** [comment]
That change did not remove loading the modules on the minion, all it did was revert to the previous behavior where the modules when referenced in the scheduler on the master were runner modules like they had always been.

The minion should still be able to run a highstate, when configured in /etc/salt/minion or in pillars like you are doing.

What was happening before is it would run a highstate on the master, not targeting other minions.

If you want to target minions, you should schedule state.orchestrate, and then target the minions in that.

Also, this only triggers one event, so even if it did target minions, the splay would hit all the minions at once, unless you did a batch.  With the splayed, the minions each run it randomly in that time period.

The scheduler in the master config is not for configuring minions, it is for configuring jobs run on the master, which is far better to have runners available.
