### ISSUE TITLE
mount-option-user

### ISSUE THREAD

**Issue by neighbour-oldhuang** [saltstack/salt#47757]
### Description of Issue/Question
    user
                The user to own the mount; this defaults to the user salt is
                running as on the minion
i think the owner of mount dir is myuser ? but seems salt use myuser to exec mount
### Setup
/xxx:
  mount.mounted:
    - device: "x.x.x.x:/xxx"
    - fstype: nfs
    - mkmnt: True
    - user: _**myuser**_
    - opts:
      - defaults
### Steps to Reproduce Issue
salt tell me  mount can running by root only

### Versions Report
minion: 2015.5.8-1   master: 2015.5.11

**Comment by gtmanfred** [comment]
Probably the best thing to do would be to manage the mount point using a file.directory, and then mount with root.

The user i think is only usable for FUSE mounts which can be mounted by non root users.

I am going to mark this as a documentation issue.

Thanks,
Daniel
