### ISSUE TITLE
pip.installed failing (Result: False) if package already installed (for python3 pip3 packages)

### ISSUE THREAD

**Issue by VirtualAirwaves** [saltstack/salt#47752]
### Description of Issue/Question

The  documentation for pip.installed says its function is to "Make sure the package is installed" and this is how it used to work. If the package was already installed, it wouldn't fail with a Result: False. 

Now pip.installed is failing for packages that are already installed

Log file:

```
 ID: service_identity3
    Function: pip.installed
        Name: service_identity
      Result: False
     Comment: Python package service_identity was already installed
              Failed to install packages: . Error:  ERROR: You must give at least one requirement to install (see "pip help install")
     Started: 17:52:39.280853
    Duration: 1405.756 ms
     Changes:
```

### Setup

from the sls

```
service_identity3:
  pip.installed:
  - bin_env: '/usr/bin/pip3'
  - name: service_identity
  - require:
    - pkg: dev-packages
    - pkg: python34-pip
```

### Steps to Reproduce Issue
(See log above)

### Versions Report
```

[vagrant@localhost ~]$ salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

pip version (pip3)

> pip 10.0.1 from /usr/lib/python3.4/site-packages/pip (python 3.4)

**Comment by gtmanfred** [comment]
What is the output of `salt \* pip.version bin_env=/usr/bin/pip3` ?

If it is `>= 10.0.0` downgrade pip to `<=9.0.3` until 2017.7.6 and 2018.3.1 are released

`pip install pip<=9.0.3`

Or use get-pip.py to install pip, instead of the epel package https://bootstrap.pypa.io/get-pip.py

`python get-pip.py "<=9.0.3"`

**Comment by VirtualAirwaves** [comment]
Thanks, gtmanfred. I downgraded to 9.0.3 and it's working as expected. I guess the bigger problem is there needs to be a pip3.installed salt-state, too. Many/most people have to deal with python2 and python3 on the same systems...

**Comment by gtmanfred** [comment]
that is what bin_env is for.  if you run salt using the python3 packages, pip.installed should default to pip from pip3, because we actually just use python -m pip, where python is pulled from the salt grains for which python binary started salt.
