### ISSUE TITLE
saltutil.sync_XXX doesn't sync items which are not available in base

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#47763]
### Description of Issue/Question
We're using gitfs for providing the environments served by our Salt master. Now, when a new custom grain, module, state, etc. is added to the Git repository on a branch (in _grains, _states, ...), a following `salt-call saltutil.sync_all saltenv=thebranch` doesn't actually sync the new item to the minion. It only starts doing so once the item is available in the base environment, too (after the branch has been merged into master, for example).
### Setup
```
fileserver_backend:
  - git
  - roots
gitfs_remotes:
  - <Repository URL>:
    - root: states
```
### Steps to Reproduce Issue
1. Create new branch in repository
1. Add new custom state to _states
1. Commit and push
1. Wait for master to pull from Git repository
1. Run `salt-call saltutil.sync_all saltenv=<branch name>` on a minion
### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1060-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
I am unable to replicate this.

```
[root@3bc37f834fd2 gitrepo]# salt \* cp.list_master
3bc37f834fd2:
    - _modules/README.md
[root@3bc37f834fd2 gitrepo]# salt \* cp.list_master saltenv=branch
3bc37f834fd2:
    - _modules/README.md
    - _modules/testmod.py
[root@3bc37f834fd2 gitrepo]# salt \* saltutil.sync_modules
3bc37f834fd2:
[root@3bc37f834fd2 gitrepo]# salt \* saltutil.sync_modules saltenv=branch
3bc37f834fd2:
    - modules.testmod
[root@3bc37f834fd2 gitrepo]# salt \* testmod.ping
3bc37f834fd2:
    True
```

I only have testmod.py in the `branch` branch, and not in `master`, but when I set the saltenv for the sync_modules it syncs fine.

Can you provide me with a setup and git repository that is able to replicate this?

Thanks,
Daniel

**Comment by dhs-rec** [comment]
Shame on me. This seems to have been an issue on my side. I use packer to provision machines in AWS, which in turn remote execs a script on the Salt master to sync stuff and then trigger a highstate. Said script had a bug which caused it to always pass "saltenv=base" to the salt command, regardless of which environment was specified on its command line options.
