### ISSUE TITLE
Dynamic proxy minion connections & Key Accepting

### ISSUE THREAD

**Issue by prashanthtuttu** [saltstack/salt#47792]
Hi,

My requirement is to connect to set of network devices from a list and perform certain activities , since i am new to saltstack , is there any way to accept key and start the proxy minion processes at runtime.

Thanks in advance

**Comment by Ch3LL** [comment]
Can you clarify more of your use case i'm a bit confused as to what you are attempting to do?

**Comment by prashanthtuttu** [comment]
Hi @Ch3LL ,

My requirement is to do certain ACL activities on the network devices , a file will hold the entries of devices. now my query is how can i performing key accepting and starting proxy minion process for all the list of devices @ runtime.

**Comment by Ch3LL** [comment]
If you are seeing to a have a more dynamic way of accepting minion keys as minions start up you could look into preseeding minions as documented here: https://docs.saltstack.com/en/latest/topics/tutorials/preseed_key.html  or turning on `auto_accept` although there are security implications when turning on auto_accept.

**Comment by prashanthtuttu** [comment]
Thanks @Ch3LL , Will check on the same
