### ISSUE TITLE
 Feature: Filter Vault Pillar by Nodegroup membership

### ISSUE THREAD

**Issue by nickgarber** [saltstack/salt#47817]
### Description of Issue/Question

The Vault pillar allows namespace joining according to minion_id.

Could the ability to filter by nodegroup membership be added? It'd be a very handy addition alongside minion_id.

Allowing nodegroup-based filtering would close this gap and enable many more use-cases.

(Similar to #39501)

**Comment by nokernel** [comment]
:+1:

**Comment by nickgarber** [comment]
I'm not expecting to use/need this feature-request anymore so will mark it closed.
