### ISSUE TITLE
network.managed error "TypeError: decoding Unicode is not supported"

### ISSUE THREAD

**Issue by davejhahn** [saltstack/salt#47829]
### Setup
Ethernet0:
  network.managed:
    - ip_proto: static
    - dns_proto: static
    - dns_servers:
      - 10.0.0.5
      - 10.0.0.6
    - ip_addrs:
      - 10.0.0.50/24
    - gateway: 10.0.0.1

### Steps to Reproduce Issue
Run above state against a Win OS minion, with appropriate subnet.  This was working prior to the upgrade.

XX-XX-XX:
----------
          ID: Ethernet0
    Function: network.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1878, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1823, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_network.py", line 302, in managed
                  errors = _validate(dns_proto, dns_servers, ip_proto, ip_addrs, gateway)
                File "c:\salt\bin\lib\site-packages\salt\states\win_network.py", line 118, in _validate
                  if not salt.utils.validate.net.ipv4_addr(x)]
                File "c:\salt\bin\lib\site-packages\salt\utils\validate\net.py", line 73, in ipv4_addr
                  return __ip_addr(addr, socket.AF_INET)
                File "c:\salt\bin\lib\site-packages\salt\utils\validate\net.py", line 52, in __ip_addr
                  socket.inet_pton(address_family, ip)
                File "c:\salt\bin\lib\site-packages\salt\ext\win_inet_pton.py", line 40, in inet_pton
                  ipaddress.ip_address(six.u(ip_string))
                File "c:\salt\bin\lib\site-packages\salt\ext\six.py", line 654, in u
                  return unicode(s.replace(r'\\', r'\\\\'), "unicode_escape")
              TypeError: decoding Unicode is not supported
     Started: 23:18:31.528000
    Duration: 62.0 ms
     Changes:

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.21.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.21.4
         Python: 2.7.5 (default, Aug  9 2016, 05:27:46)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo

**Comment by gtmanfred** [comment]
Can you provide the output of `salt <minionid> test.versions_report`?

@dwoz and @twangboy if yall could take a look here.

Thanks,
Daniel

**Comment by davejhahn** [comment]
The version report for the minion (2018.3.0):

XXX-X-XXX-XX-XX:
    Salt Version:
               Salt: 2018.3.0

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: 0.7.11.None
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1                                                                                                                                                             500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600  Multiprocessor Free

**Comment by twangboy** [comment]
This is fixed in https://github.com/saltstack/salt/pull/46219. Should be included in the next release.
