### ISSUE TITLE
Salt Master is failing to start when running as Normal User or UnPrivileged User

### ISSUE THREAD

**Issue by sandilyasd** [saltstack/salt#47834]
### Description of Issue/Question
Salt Master is failing to start when running as Normal User or UnPrivileged User.

### Setup
After installing the salt-master, master got started without any issues. But when the master config file is updated with user parameter and the below folders ownership is changed to the User.

/var/log/salt
/var/run/salt
/var/cache/salt
/etc/salt

I am getting the below error

2018-05-24 08:41:12,967 [salt.log.setup   :1165][ERROR   ][8950] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 97, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 215, in start
    self.master.start()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 641, in start
    salt.crypt.Crypticle.generate_key_string()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 260, in Array
    return Array(typecode_or_type, size_or_initializer, **kwds)
  File "/usr/lib64/python2.7/multiprocessing/sharedctypes.py", line 119, in Array
    lock = RLock()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 183, in RLock
    return RLock()
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 172, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1)
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 2] No such file or directory
[root@RCOVLNX3300 salt]# ls -ltr /usr/lib/python2.7/site-packages/salt/scripts.py
-rw-r--r--. 1 root root 15370 Mar 29 11:52 /usr/lib/python2.7/site-packages/salt/scripts.py
[root@RCOVLNX3300 salt]# ls -ltr /usr/bin/salt-master
-rwxr-xr-x. 1 root root 744 Apr  2 10:42 /usr/bin/salt-master
[root@RCOVLNX3300 salt]# ls -ltr /usr/lib/python2.7/site-packages/salt/cli/daemons.py
-rw-r--r--. 1 root root 23579 Mar 29 11:52 /usr/lib/python2.7/site-packages/salt/cli/daemons.py
[root@RCOVLNX3300 salt]# ls -ltr /usr/lib/python2.7/site-packages/salt/master.py
-rw-r--r--. 1 root root 90137 Mar 29 11:52 /usr/lib/python2.7/site-packages/salt/master.py
[root@RCOVLNX3300 salt]# ls -ltr /usr/lib64/python2.7/multiprocessing/__init__.py
-rwxr-xr-x. 1 root root 7805 May  3  2017 /usr/lib64/python2.7/multiprocessing/__init__.py
[root@RCOVLNX3300 salt]# ls -ltr /usr/lib64/python2.7/multiprocessing/sharedctypes.py
-rwxr-xr-x. 1 root root 7697 May  3  2017 /usr/lib64/python2.7/multiprocessing/sharedctypes.py
[root@RCOVLNX3300 salt]# ls -ltr /usr/lib64/python2.7/multiprocessing/__init__.py
-rwxr-xr-x. 1 root root 7805 May  3  2017 /usr/lib64/python2.7/multiprocessing/__init__.py
[root@RCOVLNX3300 salt]# ls -ltr /usr/lib64/python2.7/multiprocessing/synchronize.py
-rwxr-xr-x. 1 root root 10653 May  3  2017 /usr/lib64/python2.7/multiprocessing/synchronize.py
[root@RCOVLNX3300 salt]# ls -ltr /usr/lib64/python2.7/multiprocessing/synchronize.py
-rwxr-xr-x. 1 root root 10653 May  3  2017 /usr/lib64/python2.7/multiprocessing/synchronize.py 
 

### Steps to Reproduce Issue
1. Update the user parameter in Master config file 
2.  Change the ownership to use for the below folders
/var/log/salt/
/var/cache/salt/
/var/run/salt/
/etc/salt/

### Versions Report
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by gtmanfred** [comment]
Can you provide the full --versions-report of the master, that includes the salt version?

Thanks,
Daniel

**Comment by sandilyasd** [comment]
Hello,

When i am trying this in test cloud server it is working fine for me.

But when i am trying actual production server, it is throwing me an error ''No Such file / directory". Not sure which file / directory it is trying to access.

Below is the complete log trace

[root@RCOVLNX3300 master]# salt-master -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Master
[DEBUG   ] Marking 'base64_encode' as a jinja filter
[DEBUG   ] Marking 'base64_decode' as a jinja filter
[DEBUG   ] Marking 'md5' as a jinja filter
[DEBUG   ] Marking 'sha256' as a jinja filter
[DEBUG   ] Marking 'sha512' as a jinja filter
[DEBUG   ] Marking 'hmac' as a jinja filter
[DEBUG   ] Marking 'random_hash' as a jinja filter
[DEBUG   ] Marking 'rand_str' as a jinja filter
[DEBUG   ] Marking 'file_hashsum' as a jinja filter
[DEBUG   ] Marking 'http_query' as a jinja filter
[DEBUG   ] Marking 'yaml_dquote' as a jinja filter
[DEBUG   ] Marking 'yaml_squote' as a jinja filter
[DEBUG   ] Marking 'yaml_encode' as a jinja filter
[DEBUG   ] Marking 'raise' as a jinja global
[DEBUG   ] Marking 'match' as a jinja test
[DEBUG   ] Marking 'equalto' as a jinja test
[DEBUG   ] Marking 'skip' as a jinja filter
[DEBUG   ] Marking 'sequence' as a jinja filter
[DEBUG   ] Marking 'to_bool' as a jinja filter
[DEBUG   ] Marking 'quote' as a jinja filter
[DEBUG   ] Marking 'regex_escape' as a jinja filter
[DEBUG   ] Marking 'regex_search' as a jinja filter
[DEBUG   ] Marking 'regex_match' as a jinja filter
[DEBUG   ] Marking 'regex_replace' as a jinja filter
[DEBUG   ] Marking 'uuid' as a jinja filter
[DEBUG   ] Marking 'unique' as a jinja filter
[DEBUG   ] Marking 'min' as a jinja filter
[DEBUG   ] Marking 'max' as a jinja filter
[DEBUG   ] Marking 'avg' as a jinja filter
[DEBUG   ] Marking 'union' as a jinja filter
[DEBUG   ] Marking 'intersect' as a jinja filter
[DEBUG   ] Marking 'difference' as a jinja filter
[DEBUG   ] Marking 'symmetric_difference' as a jinja filter
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded master key: /etc/salt/pki/master/master.pem
[INFO    ] Preparing the root key for local communication
[DEBUG   ] Removing stale keyfile: /var/cache/salt/master/.root_key
[INFO    ] Preparing the fttacct key for local communication
[DEBUG   ] Removing stale keyfile: /var/cache/salt/master/.fttacct_key
[PROFILE ] Beginning pwd.getpwall() call in masterapi access_keys function
[PROFILE ] End pwd.getpwall() call in masterapi access_keys function
[DEBUG   ] Created pidfile: /var/run/salt-master.pid
[DEBUG   ] Chowned pidfile: /var/run/salt-master.pid to user: fttacct
[INFO    ] Starting up the Salt Master
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[INFO    ] salt-master is starting as user 'fttacct'
[INFO    ] Current values for max open files soft/hard setting: 1024/4096
[INFO    ] The value for the 'max_open_files' setting, 100000, is higher than the highest value the user running salt is allowed to set (4096). Defaulting to 4096.
[INFO    ] Raising max open files value to 4096
[INFO    ] New values for max open files soft/hard values: 4096/4096
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 97, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 215, in start
    self.master.start()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 641, in start
    salt.crypt.Crypticle.generate_key_string()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 260, in Array
    return Array(typecode_or_type, size_or_initializer, **kwds)
  File "/usr/lib64/python2.7/multiprocessing/sharedctypes.py", line 119, in Array
    lock = RLock()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 183, in RLock
    return RLock()
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 172, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1)
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 2] No such file or directory
Traceback (most recent call last):
  File "/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 97, in salt_master
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 215, in start
    self.master.start()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 641, in start
    salt.crypt.Crypticle.generate_key_string()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 260, in Array
    return Array(typecode_or_type, size_or_initializer, **kwds)
  File "/usr/lib64/python2.7/multiprocessing/sharedctypes.py", line 119, in Array
    lock = RLock()
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 183, in RLock
    return RLock()
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 172, in __init__
    SemLock.__init__(self, RECURSIVE_MUTEX, 1, 1)
  File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in __init__
    sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 2] No such file or directory


Please help me with this issue.

**Comment by gtmanfred** [comment]
Can you run `ls /dev/shm` on that server?

Thanks,
Daniel

**Comment by sandilyasd** [comment]
Hello,

There are no contents in the folder and the permissions of the folder is below

drwxrwx---. 2 root root 40 May 30 10:47 /dev/shm/

Please share your thoughts.

**Comment by gtmanfred** [comment]
I believe that is your problem.

For multiprocessing to work, the user running the command must be able to write to /dev/shm, so it should be 1777 like /tmp.
```
[root@ea22b39147a4 /]# ls -ld /dev/shm
drwxrwxrwt 2 root root 40 May 31 13:09 /dev/shm
```

That is why it cannot write while setting the SemLock on _multiprocessing.

```
File "/usr/lib64/python2.7/multiprocessing/init.py", line 183, in RLock
return RLock()
File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 172, in init
SemLock.init(self, RECURSIVE_MUTEX, 1, 1)
File "/usr/lib64/python2.7/multiprocessing/synchronize.py", line 75, in init
sl = self._semlock = _multiprocessing.SemLock(kind, value, maxvalue)
OSError: [Errno 2] No such file or directory
```

**Comment by sandilyasd** [comment]
Thanks for the details. I will try changing the permissions and will let you know the outcome.

**Comment by gtmanfred** [comment]
it cannot find the command you are trying to run, which you have also redacted.

`reason: command not found`

Make sure that the path for that file is added for the user you are running, and not just only added for the root user.

**Comment by sandilyasd** [comment]
These errors are coming during the startup. Not sure which path needs to be added to the user.

Please share your thoughts on this

**Comment by gtmanfred** [comment]
looking at the logs, it may be rpm?
```
May 31 16:33:04 rcovlnx3300.corp.frk.com salt-master[13140]: osarch = salt['cmd.run']('rpm --eval %{_host_cpu}').strip()
```

It may be best to make a new salt master and just migrate over if you are having problems with this server.

**Comment by gtmanfred** [comment]
users should be allowed to run the rpm command, this is used on rpm systems to get information about the host_cpu.

**Comment by sandilyasd** [comment]
Thanks for the information, it worked after changing the permissions of /usr/bin/rpm
