### ISSUE TITLE
can't import ipv6 addresses

### ISSUE THREAD

**Issue by pasanmdev** [saltstack/salt#47830]
I can't import an ipv6 address definition out of an sls. It complains it encountered and unexpected ':'  character. I tried to quote the content but got no luck :/. How do I keep ipv6 data in a yaml structure ? If I do a yamllint check it parses it properly.

### Setup

srv/pillar/networks/subnets.sls

```
vinet_2xxx_xxxx_1c:
  subnet: "2xxx:xxxx:1c::/64"
  family : 6
  rule: v.inet
```

/srv/pillar/firewall.sls

```
{% import_yaml 'networks/subnets.sls' as subnets %}
firewall:
  type: vhost
  snet_dev: bond1.xx
  net_interfaces:
     bond0.xx:
       subnets: [ {{  subnets.vinet_2xxx_xxxx_1c }} ]

```

### Steps to Reproduce Issue
[CRITICAL] Rendering SLS 'firewall' failed, render error:
 found unexpected ':'; line 7

### Versions Report
--- master --
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.76-local.20180111-152449
         system: Linux
        version: debian 9.4 

-- minion ---
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.101-local.20180522-135143
         system: Linux
        version: debian 9.4

**Comment by gtmanfred** [comment]
Unfortunately I am unable to replicate this behavior.

```
[root@salt pillar]# tail -c +0 /srv/pillar/*.sls
==> /srv/pillar/firewall.sls <==
{% import_yaml 'subnets.sls' as subnets %}
firewall:
  type: vhost
  snet_dev: bond1.xx
  net_interfaces:
     bond0.xx:
       subnets: [ {{  subnets.vinet_2xxx_xxxx_1c }} ]

==> /srv/pillar/subnets.sls <==
vinet_2xxx_xxxx_1c:
  subnet: "2xxx:xxxx:1c::/64"
  family : 6
  rule: v.inet

==> /srv/pillar/top.sls <==
base:
  '*':
    - firewall
[root@salt pillar]# salt \* pillar.get firewall:net_interfaces:bond0.xx:subnets
tester:
    |_
      ----------
      family:
          6
      rule:
          v.inet
      subnet:
          2xxx:xxxx:1c::/64
salt:
    |_
      ----------
      family:
          6
      rule:
          v.inet
      subnet:
          2xxx:xxxx:1c::/64
```

Can you provide us with any more information to replicate it?

Thanks,
Daniel

**Comment by pasanmdev** [comment]
@gtmanfred are you using same version ? I'm still getting the error, I'll put complete log from the master. I have tweak some naming stuff. I even tried the exact content that you tried and getting the error.

/srv/pillar/networks/subnets.sls
```
vinet_nsw_v6:
  subnets:  "2xxx:xxxx:1c::/64" 
  family : 6
  rule: v.inet
```
/srv/pillar/firewall.sls
```
{% import_yaml 'networks/subnets.sls' as subnets %}
firewall:
  type: vhost
  snet_dev: bond1.xx
  net_interfaces:
     bond0.xx:
       networks: [ {{ subnets.vinet_nsw_v6 }} ]
 
```


master log file
```
salt-master[4938]: [DEBUG   ] Rendered data from file: /var/cache/salt/master/git_pillar/c4d6824b9875e126dd3a689b076cb80c6f54e5f04184427f2bb063d490215550/srv/pillar/firewall.sls:
salt-master[4938]: firewall:
salt-master[4938]:   type: vhost
salt-master[4938]:   snet_dev: bond1.xx
salt-master[4938]:   net_interfaces:
salt-master[4938]:      bond0.xx:
salt-master[4938]:        networks: [ {u'subnets': u'2406:3400:1c::/64', u'rule': u'v.inet', u'family': 6} ]
salt-master[4938]: [CRITICAL] Rendering SLS 'firewall' failed, render error:
salt-master[4938]: found unexpected ':'; line 7
salt-master[4938]: ---
salt-master[4938]: [...]
salt-master[4938]: firewall:
salt-master[4938]:   type: vhost
salt-master[4938]:   snet_dev: bond1.xx
salt-master[4938]:   net_interfaces:
salt-master[4938]:      bond0.70:
salt-master[4938]:        networks: [ {u'subnets': u'2xxx:xxxx:1c::/64', u'rule': u'v.inet', u'family': 6} ]    <======================
salt-master[4938]: [...]
salt-master[4938]: ---
salt-master[4938]: [CRITICAL] Pillar render error: Rendering SLS 'firewall' failed. Please see master log for details.

```

**Comment by gtmanfred** [comment]
yes, i am using 2018.3.0

Are you using git pillar, or pillar_roots?

Because i see it pulling from git pillar here.

`salt-master[4938]: [DEBUG   ] Rendered data from file: /var/cache/salt/master/git_pillar/c4d6824b9875e126dd3a689b076cb80c6f54e5f04184427f2bb063d490215550/srv/pillar/firewall.sls:`

Does the problem go away when you use pillar roots?

Thanks,
Daniel

**Comment by pasanmdev** [comment]
@gtmanfred yes I'm using git pillars.

I tried pillar roots too. same error :/

```
 salt-master[18889]: [PROFILE ] Time (in seconds) to render '/srv/pillar/firewall.sls' using 'jinja' renderer: 0.0181920528412
 salt-master[18889]: [DEBUG   ] Rendered data from file: /srv/pillar/firewall.sls:
 salt-master[18889]: firewall:
 salt-master[18889]:   type: vhost
 salt-master[18889]:   snet_dev: bond1.xx
 salt-master[18889]:   net_interfaces:
 salt-master[18889]:      bond0.xx:
 salt-master[18889]:        networks: [ {u'subnets': u'2xxx:xxxx:1c::/64', u'rule': u'v.inet', u'family': 6} ]
 salt-master[18889]: [CRITICAL] Rendering SLS 'firewall' failed, render error:
 salt-master[18889]: found unexpected ':'; line 7
 salt-master[18889]: ---
 salt-master[18889]: [...]
 salt-master[18889]: firewall:
 salt-master[18889]:   type: vhost
 salt-master[18889]:   snet_dev: bond1.xx
 salt-master[18889]:   net_interfaces:
 salt-master[18889]:      bond0.xx:
 salt-master[18889]:        networks: [ {u'subnets': u'2xxx:xxxx:1c::/64', u'rule': u'v.inet', u'family': 6} ]    <======================
 salt-master[18889]: ---

```

**Comment by gtmanfred** [comment]
Can you create a docker container with this happening in it and push it to hub.docker.com so that we can replicate it?

Thanks,
Daniel

**Comment by pasanmdev** [comment]
@gtmanfred ok,I'll give it a try, i'm not familar with docker stuff, But I'll try to get it done. btw I'm using saltstack provided deb repo.

deb http://repo.saltstack.com/apt/debian/9/amd64/latest stretch main

**Comment by pasanmdev** [comment]
@gtmanfred I have replicated the issue in a docker container env. Please check it. Same issue occurred there.
https://hub.docker.com/r/pasanmdev/salttest/

**Comment by gtmanfred** [comment]
I /think/ what is happening is a json string is being dropped down, but because it is yaml, the quotes are being stripped, which is causing the weird behavior.  It doesn't like the `u` prefixes.

If you do this for firewall.sls, to load the json string, it works as expected.

```
{% import_yaml 'subnets.sls' as subnets %}
firewall:
  type: vhost
  snet_dev: bond1.xx
  net_interfaces:
     bond0.xx:
       subnets: [ {{subnets.vinet_2xxx_xxxx_1c|json}} ]
```

**Comment by pasanmdev** [comment]
@gtmanfred yup, it takes it well with json wrapping. so this is not a bug ?or is this a workaround ?
