### ISSUE TITLE
ini.options_present - long time duration

### ISSUE THREAD

**Issue by 82lolop** [saltstack/salt#47858]
Hi, I've noticed that as a result of the salt upgrade, the state is running longer with the same configuration. 
The salt 2018 version is extremely long. 
One processor core is 100% charged with the salt process.
 
Have you also observed such a phenomenon? 
Is this the correct behavior?

================================
          ID: openstack_nova                                                                                          
    Function: ini.options_present                                                                                     
        Name: /etc/nova/nova.conf                                                                                     
      Result: True                                                                                                    
     Comment: Changes take effect                                                                                     
     Started: 13:31:16.845943                                                                                         
    Duration: 64707.647 ms                                                                                            
     Changes:

salt-call grains.get saltversion
local:
    2016.11.9

=======================================
          ID: openstack_nova
    Function: ini.options_present
        Name: /etc/nova/nova.conf
      Result: True
     Comment: No anomaly detected
     Started: 11:19:03.331468
    Duration: 158318.573 ms
     Changes:

salt-call grains.get saltversion
local:
    2017.7.5

============================
          ID: openstack_nova
    Function: ini.options_present
        Name: /etc/nova/nova.conf
      Result: True
     Comment: No anomaly detected
     Started: 12:47:33.581740
    Duration: 856533.31 ms
     Changes:

salt-call grains.get saltversion
local:
    2018.3.0

**Comment by garethgreenaway** [comment]
@82lolop Thanks for the report.  This definitely does not sound like it should be the expected situation when using `init.options_present`.

**Comment by msciciel** [comment]
I've performed some debugging and it looks that time is wasted in function https://github.com/saltstack/salt/blob/develop/salt/modules/ini_manage.py#L81:
``` 
inifile = _Ini.get_ini_file(file_name, separator=separator)
```
Because of the loop in refresh() method in class _Section https://github.com/saltstack/salt/blob/develop/salt/modules/ini_manage.py#L269.

I have investigated that most time is used for commented lines. Maybe the solution is to skip lines with '#' at the beginning ? In our case nova.conf has `8042` commented out or empty lines and just 130 proper lines.

**Comment by msciciel** [comment]
How to reproduce:
1. curl -o /etc/nova.conf https://docs.openstack.org/nova/latest/_downloads/nova.conf.sample
2. create /srv/salt/test.sls:
```
openstack_nova:
  ini:
    - name: /etc/nova.conf
    - options_present
    - sections:
        DEFAULT:
          rpc_backend: rabbit
          my_ip: example
          use_neutron: true
          linuxnet_interface_driver: nova.network.linux_net.LinuxOVSInterfaceDriver
          firewall_driver: nova.virt.firewall.NoopFirewallDriver
          verbose: True
          debug: false
          vcpu_pin_set: example
          resume_guests_state_on_host_boot: true
          multi_instance_display_name_template: "%(name)s%(count)s"
          reserved_host_memory_mb: 12048
          reserved_host_disk_mb: 18192
          cpu_allocation_ratio: 116.0
          disk_allocation_ratio: 2.3
          ram_allocation_ratio: 4.5
          resize_confirm_window: 36000
        api:
          auth_strategy: keystone
        placement:
          os_region_name: example
          project_domain_name: example
          user_domain_name: example
          project_name: example
          auth_url: http://example:35357/v3
          auth_type: example
          username: example
          os_interface: internal
        oslo_messaging_rabbit:
          rabbit_retry_interval: 1
          rabbit_retry_backoff: 2
          rabbit_max_retries: 0
          rabbit_ha_queues: false
          rabbit_port: 5672
          rabbit_userid: nova
          rabbit_virtual_host: /
          amqp_durable_queues: false
        oslo_concurrency:
          lock_path: /var/lib/nova/tmp
        keystone_authtoken:
          auth_uri: http://example:5000
          auth_url: http://example:35357
          auth_plugin: password
          project_domain_id: default
          user_domain_id: default
          project_name: services
          username: nova
        libvirt:
          virt_type: example
          live_migration_progress_timeout: 0
          snapshot_image_format: qcow2
          snapshot_compression: true
          hw_disk_discard: unmap
          cpu_mode: example
          cpu_model: example
        glance:
          api_servers: http://example:9292
        neutron:
          url: http://example:9696
          auth_strategy: keystone
          admin_auth_url: http://example:35357/v2.0
          admin_tenant_name: services
          admin_username: neutron
        cinder:
          catalog_info: volumev2:cinderv2:internalURL
          cross_az_attach: false
        vnc:
          novncproxy_base_url: https://example:6080/vnc_auto.html
          vncserver_listen: 0.0.0.0
          vncserver_proxyclient_address: example
          enabled: true
        workarounds:
          disable_libvirt_livesnapshot: false
```
3. salt-call --local state.sls test -l debug

Result:
```
----------
          ID: openstack_nova
    Function: ini.options_present
        Name: /etc/nova.conf
      Result: True
     Comment: Changes take effect
     Started: 12:00:02.649629
    Duration: 570166.998 ms
```
