### ISSUE TITLE
Saltstack: Not able to copy file from SALT minion (Windows) to salt master (ubuntu)

### ISSUE THREAD

**Issue by sahilkhadilkar** [saltstack/salt#47856]
I am running

salt 'WIN-34Q11PE64RK.abc.com' cp.push C:\salt\var\cache\salt\minion\test.txt

command to copy file from minion to master.

File_recv is true. file size is very low that max limit.  I have kept firewall off also made that folder shared. but still I am getting error. I am getting output as false.
both minion and master are using salt 2018.3.0 (Oxygen) version.

<img width="189" alt="screen shot 2018-05-28 at 3 59 00 pm" src="https://user-images.githubusercontent.com/13384530/40610487-308b3848-6290-11e8-9ccc-5f5c48f7bcbe.png">

**Comment by garethgreenaway** [comment]
@sahilkhadilkar Thanks for the report.  Are you able to produce any error messages?  Increasing the log level to see what exactly is going wrong?

**Comment by sahilkhadilkar** [comment]
@garethgreenaway Hello, I was able to send the file. I first cached the file on the minion and then tried to send it to master and it worked.
Just I am not able to move at desired location. If I give path like "upload_path=destination" it is creating that folders in master's minion folder.
Is it possible to get that file not in minion folder but directly on /home/XYZ/
