### ISSUE TITLE
Minion run all of the available environment

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#47854]
Hey,
I have salt-master with two envs and each agent configure to use just one of the envs hard coded in the minion configuration file.
And still when running salt-call state.highstate on the agent he run both of the envs instead of the configured one.

My master version is: 2018.3
I have two minion versions: 2018.3 and 2017.7
This is happen only at the 2018.3 minion version.

Best regards,
Amiram

**Comment by garethgreenaway** [comment]
@AmiramMaimon Thanks for the report.  How are your environments setup?  Do you have a top.sls file in each one or is there a shared top file between the environments?  It could be that the targeting isn't working as expecting, causing both environments to be applied.

**Comment by AmiramMaimon** [comment]
Hey,

I have top.sls file for each env places under the file_root of the relevant env.

Amiram

**Comment by AmiramMaimon** [comment]
Hey,

Any update?

Amiram

**Comment by garethgreenaway** [comment]
@AmiramMaimon thanks. Can you provide the top files you're using.

**Comment by AmiramMaimon** [comment]
Hey,

I have two top.sls file one in each env with the same name 'top.sls'
-------------------------------------------
Production:
  '*':
    - Testing
-------------------------------------------
QA:
  '*':
    - Testing

Amiram

**Comment by DmitryKuzmenko** [comment]
@AmiramMaimon have you resolved this issue?
If not: how do you specify the environment on minion? It should be `saltenv: <environment name>` (`saltenv: Production` for example).
What happens if you are doing `salt 'minion_id' state.highstate`? Also what will happen if you'll add `saltenv=Production` to the end of both `salt` and `salt-call` commands?
