### ISSUE TITLE
YaST network installation, wrong ID

### ISSUE THREAD

**Issue by Dejv56** [saltstack/salt#47861]
Hello. I have a problem when installing SLES 12 SP3 using YaST network installation. Recently i added Salt as configuration management in YaST XML profile, according to documentation:
```
<configuration_management>
    <type>salt</type>
    <master>192.168.20.10</master>
    <auth_attempts config:type="integer">5</auth_attempts>
    <auth_time_out config:type="integer">10</auth_time_out>
</configuration_management>
```

Configuration of Salt happens during first stage of installation, is this behauvior normal, that it's not running in second stage? 

Next problem occurs when minion search for it's ID, it always come up with the name "install" `[DEBUG] Found minion id from generate_minion_id(): install`, althought hostname is set in XML. I think that is because it is running in first stage.

Is there any possibility to set minion_ID directly in YaST XML profile in configuration management section?

Thanks.

**Comment by garethgreenaway** [comment]
@Dejv56 This seems like an issue that would be better reported against YaST rather than Salt, as it seems very specific to YaST rather than Salt specific.

**Comment by rallytime** [comment]
@saltstack/team-suse FYI ^

**Comment by Dejv56** [comment]
Let's say, that the Salt configuration is running in stage of installation where it should be running. Where does the function "generate_minion_id()" get ID from?

**Comment by brejoc** [comment]
@Dejv56 Thanks for reporting this. But you should indeed report this in SUSE Bugzilla and/or contact SUSE service so that the right people are made aware of this.
