### ISSUE TITLE
salt-ssh initial connection issue

### ISSUE THREAD

**Issue by tganzeboom** [saltstack/salt#47864]
### Description of Issue/Question

salt-ssh -i <machine> test.ping
Permission denied for host <machine>, do you want to deploy the salt-ssh key? (password required):
[Y/n]
----------
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.username_358757_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.username_358757_salt/py2/salt/scripts.py", line 395, in salt_call
            import salt.cli.call
          File "/var/tmp/.username_358757_salt/py2/salt/cli/call.py", line 5, in <module>
            import salt.utils.parsers
          File "/var/tmp/.username_358757_salt/py2/salt/utils/parsers.py", line 27, in <module>
            import salt.config as config
          File "/var/tmp/.username_358757_salt/py2/salt/config/__init__.py", line 24, in <module>
            import salt.utils.data
          File "/var/tmp/.username_358757_salt/py2/salt/utils/data.py", line 18, in <module>
            import salt.utils.stringutils
          File "/var/tmp/.username_358757_salt/py2/salt/utils/stringutils.py", line 196
            trans_args = ({ord(x): None for x in text_characters},)
                                          ^
        SyntaxError: invalid syntax
    stdout:

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Command through the CLI

/etc/salt/roster:
\<machine\>:
  host: \<ipnumber\>
  user: \<username\>
  sudo: True

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Repeat the command.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
 salt-ssh --version
salt-ssh 2018.3.0 (Oxygen)

**Comment by gtmanfred** [comment]
Are you using 2018.3.0 against a minion that has py26 (like centos 6?) because if so, then you will need to go back to using 2016.11 until this is available https://github.com/saltstack/salt/pull/46684

Or you can install python 2.7 onto that machine, and have salt use that instead of the python26 install.

**Comment by tganzeboom** [comment]
It is a RHEL 6 machine, yes. There's no minion involved, however, since it's salt-ssh.

What was the idea behind doing an upgrade like this, going from supporting py26 to not supporting py26?

**Comment by gtmanfred** [comment]
python 2.6 is no longer supported by core python, so we dropped support it.

And it technically has a minion, because we sync over the salt libraries, and use that to run the minion with salt-call --local on the minion, and return that back to the salt-ssh command.

**Comment by tganzeboom** [comment]
Ah, good to know that salt-ssh work this way. Is there a reason why it doesn't use the ansible way of ssh connecting?

Concerning the fact that py26 is no longer supported, I would think it is expeditious to drop it in saltstack, unless I am unaware of something. I think most of us still have to support machines for wha'eva reason that still have this. But I guess this is shown by that fact that it's going to be put back in there.

Any date on when it's going to be in there again?

**Comment by aadityabagga** [comment]
Hi @gtmanfred, can you tell how to make salt-ssh use different python version (python2.7) on the client?

Could be useful for https://github.com/saltstack/salt/issues/45321 as well.

**Comment by gtmanfred** [comment]
We have dropped python 2.6 support in salt, but salt-ssh still looks for the python2 binary, but if you have a python2.7 binary available, salt-ssh will use that instead.

It is going to be in the next major release, which will be this Fall.

@aadityabagga i do not know.

**Comment by tganzeboom** [comment]
Any idea on installing py27 on the machines affected? I mean not 1, but 1000's? Oh right, revert back to the previous release on the saltmaster.

**Comment by gtmanfred** [comment]
@tganzeboom in the end you are going to have to downgrade, but it might be worth while to install it first, should be in epel, but we also provide a python27 and python27-pip package on the repo.saltstack.com repository for el6

**Comment by tganzeboom** [comment]
I did revert back to 2017.7.5:
First edited the saltstack repo to point to 2017.7.

`[saltstack]
name=SaltStack latest Release Channel for RHEL/CentOS $releasever
#baseurl=https://repo.saltstack.com/yum/redhat/7/$basearch/latest/
baseurl=https://repo.saltstack.com/yum/redhat/7/$basearch/2017.7/
skip_if_unavailable=True
gpgcheck=1
#gpgkey=https://repo.saltstack.com/yum/redhat/7/$basearch/latest/SALTSTACK-GPG-KEY.pub
gpgkey=https://repo.saltstack.com/yum/redhat/7/$basearch/2017.7/SALTSTACK-GPG-KEY.pub
enabled=1
enabled_metadata=1`

On RHEL it saves the old config files to *.rpmsave. I don't know if other distro's have the same behaviour, so watch out.

Then did a `yum erase salt-master salt-2018.3.0-1.el7.noarch salt-minion-2018.3.0-1.el7.noarch salt-ssh-2018.3.0-1.el7.noarch`

After that `yum install salt-master salt-ssh` and moving the old configs back. `systemctl restart salt-master` and luckily nothing happened with the PKI infra of saltstack, so salt-key showed all machines in my case.

**Comment by gtmanfred** [comment]
If you want to run salt-ssh against a minion with only python2.6, you need to go back to a version that supported py26. which is 2016.11

My suggestion is to go back to 2016.11, and then use salt-ssh to install python27 on your machines.

**Comment by tganzeboom** [comment]
I'm pretty sure this used to be possible with the 2017.7 range, since I upgraded from that. Did the 2018 range also upgrade libraries which are still installed on the system that also have to be reverted?

**Comment by gtmanfred** [comment]
you could try wiping the thin tarball from the minions since it will probably be the 2018.3 thin tarball.

add -W to your salt-ssh command.

The problem is that dictionary comprehension `{key: value for key, value in list_of_tuples}` is not a valid syntax in 2.6, it was added in 2.7.

**Comment by PeterS242** [comment]
So the SaltStack command `salt-ssh` no longer supports Red Hat's RHEL6?

Commands that once worked on newly-installed RHEL6 systems no longer function due to this Python 2.7 requirement.

It's funny because I was using `salt-ssh` to do bare-metal configuration on new RHEL systems, which included installing and configuring the Salt Minion.  Due to this change it looks like I'll have to find a way to get the SaltStack REPO on the system and pre-install Python2.7 from there before I can use the "non-minion" "ultra-thin client" `salt-ssh`.

**Comment by gtmanfred** [comment]
This will be fixed with fluorine, you can specify to use salt-ssh 2016.11 

https://github.com/saltstack/salt/pull/46684

https://docs.saltstack.com/en/develop/topics/releases/fluorine.html#saltssh-major-updates
