### ISSUE TITLE
Salt master support for multiple Active Directory servers

### ISSUE THREAD

**Issue by kefiras** [saltstack/salt#47887]
### Description of Issue/Question
Hello,

We have two different AD domains: one for Americas and second one for EMEA. Is it supported two have to LDAP servers defined in Salt master config file ? 

Thanks a lot

### Versions Report
Salt Version:               
           Salt: 2016.11.2

**Comment by gtmanfred** [comment]
Are you trying to use them for external auth or something else?

Thanks,
Daniel

**Comment by kefiras** [comment]
Yes, external auth

**Comment by gtmanfred** [comment]
Unfortunately we only support one ldap configuration for the ldap eauth setup.  Though i can see the usefulness to support more.

I am going to mark this as a feature request.

Daniel
