### ISSUE TITLE
Question regarding win_servermanager - install windows features

### ISSUE THREAD

**Issue by GitHubAre** [saltstack/salt#47885]
### Description of Issue/Question
I am using latest version where this bug is present: https://github.com/saltstack/salt/issues/47715
Since this issue was already fixed, I would like to ask when are you planning to release new version where this is fixed? For Windows management it is a very critical issue.

### Versions Report
Salt: 2018.3.0

**Comment by gtmanfred** [comment]
It will be fixed in 2018.3.1, which we have branched and are stablizing now.

IF you want to go ahead and use it, you can drop it into the dynamic modules directory and sync it to your minions.

https://docs.saltstack.com/en/latest/ref/file_server/dynamic-modules.html
