### ISSUE TITLE
pillar data from environment variables

### ISSUE THREAD

**Issue by konstest** [saltstack/salt#47884]
### Question
I would like to have this feature

Shell environment variables from commands: set/env/export

Have pillar configuration in master config file:
```
ext_pillar:
  - environ:
      pillar_path: environment
```
And then when i will run CLI commands:
salt ...
salt-run ...
salt-call ...
I will have environment variables into pillar data dictionary:
1. into .sls files:
```
{%- set VAR1_VALUE = pillar.environment.VAR1 %}
{%- set VAR2_VALUE = pillar.environment.VAR2 %}
```
2. From cli salt MINION pillar.get environment
```
# salt MINION pillar.get environment
MINION:
    ----------
    VAR1:
        VAR1_VALUE
    VAR2:
        VAR2_VALUE
...
```

**Comment by gtmanfred** [comment]
You can already have that using sdb.

https://docs.saltstack.com/en/latest/ref/sdb/all/salt.sdb.env.html

```
VAR1: {{salt.sdb.get('sdb://osenv/VAR1')}}
VAR2: {{salt.sdb.get('sdb://osenv/VAR2')}}
```

And just put that in a regular pillar roots file.

You can also configure any salt config file with sdb variables, and they get rendered when the daemon starts up, using this functionhttps://github.com/saltstack/salt/blob/2017.7/salt/config/__init__.py#L2352-L2373
