### ISSUE TITLE
Matcher for pillar defined

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#47889]
I would like to have a compound matcher that matches all minions that has a specific pillar defined (independent of value). According to https://docs.saltstack.com/en/latest/topics/targeting/pillar.html, I don't see this supported. Is it? If so, documentation should be improved. Is it not? If so, see this as a feature request :-)

**Comment by gtmanfred** [comment]
you should be able to just put a glob, which is kind of what the second one is doing.

`salt -I 'foo:bar:baz*' test.ping`

It is checking for anything with `baz*` which could be extrapolated to use `*`

Try

`salt -I 'foo:*' test.ping`

Daniel

**Comment by JensRantil** [comment]
Of course, that should work! Didn't think of that... Thanks!

**Comment by gtmanfred** [comment]
No problem!
