### ISSUE TITLE
salt-cloud invoking bootstrap-salt.sh on remote instance incorrectly parses non-ascii chars

### ISSUE THREAD

**Issue by gmwubs** [saltstack/salt#47898]
Description of Issue/Question
We're deploying instances on GCE using salt-cloud in order to have the minions connect to our saltmaster immediately after deploy. The problem is, that when a debian 9 (and possibly others with kernel 4.x) instance is created using salt-cloud and the necessary provider and profile, bootstrap-salt.sh spits out an error message as soon as systemctl enable salt-minion occurs. We want to use bootstrap-salt.sh, or a custom script invoking it after adjusting the necessary apt sources to point to our internal mirror, to remain OS agnostic.

Setup
salt-master running on a google compute instance.

/etc/salt/cloud.provider.d/gcp-project-id.conf
gcp-project-id:

Set up the Project name and Service Account authorization
project: "gcp-project-id"
service_account_email_address: "salt-cloud@gcp-project-id.iam.gserviceaccount.com"
service_account_private_key: "/path/to/json-file"

Set up the location of the salt master
minion:
master: FQDN or IP of Master
start_action: state.apply

Set up grains information, which will be common for all nodes
using this provider
grains:
node_type: broker
release: 1.0.1

driver: gce

/etc/salt/cloud.profiles.d/gcp-project-id.conf
gcp-project-id-deb:
provider: gcp-project-id
size: f1-micro
image: debian-9-stretch-v20180510
network: gcp-project-id-vpc
subnetwork: europe-west4
location: europe-west4-a
external_ip: "None"
tags: '["ssh", "tag-to-enable-nat"]'
use_persistent_disk: True
delete_boot_pd: False
ssh_interface: private_ips
ssh_username: ssh-username-to-be-used-by-salt-cloud
ssh_keyfile: /path/to/accompanying-ssh-key

Now, a salt-cloud -p gcp-project-id-deb instanceName would result in salt-cloud spinning an instance on GCP, copying the generated key-pair, minion-config and deploy script. However, as soon as the bootstrap script gets to enabling the service in case of systemd and debian 9, it spits out an error stating there's a problem with the profile. Have been searching for a day and a half, but I can'f find any error in my configs.

Steps to Reproduce Issue
Create project in gcp, create service account with compute-admin privs, create a key (json format) for use in salt-cloud provider config, create profile and try salt-cloud -p as described above.

Logs
salt-cloud -l debug --script-args='-D' (read the latter arg somewhere, seems to increase verbosity)
Setting up salt-common (2018.3.0+ds-1) ...
[ERROR ] There was a profile error: 'ascii' codec can't encode character u'\u2192' in position 317: ordinal not in range(128)
Traceback (most recent call last):
File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 281, in run
self.config.get('names')
File "/usr/lib/python2.7/dist-packages/salt/cloud/init.py", line 1454, in run_profile
ret[name] = self.create(vm_)
File "/usr/lib/python2.7/dist-packages/salt/cloud/init.py", line 1284, in create
output = self.cloudsfunc
File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/gce.py", line 2581, in create
ret = utils['cloud.bootstrap'](vm_, opts)
File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 566, in bootstrap
deployed = deploy_script(**deploy_kwargs)
File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1547, in deploy_script
if root_cmd(deploy_command, tty, sudo, **ssh_kwargs) != 0:
File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 2248, in root_cmd
retcode = _exec_ssh_cmd(cmd, allow_failure=allow_failure, **kwargs)
File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1809, in _exec_ssh_cmd
stdout, stderr = proc.recv()
File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 310, in recv
return self._recv(maxsize)
File "/usr/lib/python2.7/dist-packages/salt/utils/vt.py", line 688, in _recv
self.stream_stdout.write(stdout)
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2192' in position 317: ordinal not in range(128)

However, on the minion, in /tmp/ there's a log file named bootstrap-salt-log. The last lines read:
Setting up salt-common (2018.3.0+ds-1) ...
Setting up salt-minion (2018.3.0+ds-1) ...

Configuration file '/etc/salt/minion'
==> File on system created by you or by a script.
==> File also in package provided by package maintainer.
==> Using current old file as you requested.
Created symlink /etc/systemd/system/multi-user.target.wants/salt-minion.service → /lib/systemd/system/salt-minion.service.

Versions and Systems
Salt Version:
Salt: 2018.3.0

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.5.3
docker-py: Not Installed
gitdb: 2.0.0
gitpython: 2.1.1
ioflo: Not Installed
Jinja2: 2.9.4
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.4.8
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 2.7.13 (default, Jan 19 2017, 14:48:08)
python-gnupg: Not Installed
PyYAML: 3.12
PyZMQ: 16.0.2
RAET: Not Installed
smmap: 2.0.1
timelib: Not Installed
Tornado: 4.4.3
ZMQ: 4.2.1

System Versions:
dist: debian 9.2
locale: ANSI_X3.4-1968
machine: x86_64
release: 4.9.0-4-amd64
system: Linux
version: debian 9.2

./bootstrap-salt.sh -- Version 2018.04.25

Extra information: 
To determine whether or not this issue is related to bootstrap-script or not, I spun a default GCP instance, ran curl -L https://bootstrap.saltstack.com | sudo sh on it and deployed salt-minion with no problem at all:
`Setting up salt-common (2018.3.0+ds-1) ...
Setting up salt-minion (2018.3.0+ds-1) ...
Created symlink /etc/systemd/system/multi-user.target.wants/salt-minion.service → /lib/systemd/system/salt-minion.service.
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u3) ...

INFO: Running install_debian_check_services()
INFO: Running install_debian_restart_daemons()
INFO: Running daemons_running()
INFO: Salt installed!
`
Somehow that arrow symbol causes the bootstrap to fail when invoked from salt-cloud.

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud any ideas here?

**Comment by gtmanfred** [comment]
is the --versions-report output from the machine you are running `salt-cloud` on? or the one you are trying to bootstrap?

Because the locale is ANSI and not unicode.  Can you try setting your locale to a unicode locale and trying again?

Thanks,
Daniel

**Comment by gmwubs** [comment]
I've run export LC_ALL=en_US.UTF-8. After this I ran salt -V, which gave the following output:
System Versions:
          dist: debian 9.2
        locale: UTF-8
       machine: x86_64
       release: 4.9.0-4-amd64
        system: Linux
       version: debian 9.2

After the output confirmed that the correct locale was set, I've had salt-cloud create an instance and install the minion again. This failed, with the same error message, so I ran salt -V again:
System Versions:
           dist: debian 9.2 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.0-4-amd64
         system: Linux
        version: debian 9.2 

I was getting a bit fed-up with it, so started searching on how to enforce these setting system-wide. Setting LC_ALL=en_US.UTF-8 in /etc/default/locale turned out to be the solution!

**Comment by gmwubs** [comment]
For confirmations sake, the output from salt-cloud on the master:

Setting up salt-common (2018.3.0+ds-1) ...
Setting up salt-minion (2018.3.0+ds-1) ...

Configuration file '/etc/salt/minion'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Using current old file as you requested.
Created symlink /etc/systemd/system/multi-user.target.wants/salt-minion.service → /lib/systemd/system/salt-minion.service.
Processing triggers for libc-bin (2.24-11+deb9u3) ...
Processing triggers for systemd (232-25+deb9u3) ...

**Comment by gtmanfred** [comment]
:+1: no problem.
