### ISSUE TITLE
is it possible to change the logging level of an execution module?

### ISSUE THREAD

**Issue by daks** [saltstack/salt#47891]
### Description of Issue/Question

Running 2016.11 on Debian Stretch (mostly).
We don't configure log_level or log_level_logfile so they are at 'WARNING' log level (default).

We don't want to change the loglevel of all Salt minion but just raise it to 'INFO' on one execution module. 

Is it possible?

(We don't want to create a new handler to manage our logs, but just pipe them in the salt global logging setup)

### Setup

In my execution module I have code to log. Something like

```
import logging
log = logging.getLogger(__name__)

#...

def process():
     log.info('Starting processing')
```

I tried to raise the level on this specific module adding `log.setLevel(logging.INFO)` but without success.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

On Minion
```
# salt-call --versions-report
Salt Version:
           Salt: 2016.11.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

On master
```
$ salt --versions-report
Salt Version:
           Salt: 2016.11.9
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
        machine: x86_64
        release: 4.14.0-0.bpo.3-amd64
         system: Linux
        version: debian 9.4 
```

**Comment by gtmanfred** [comment]
I would try doing

```
salt.log.setup.setup_console_logger('info')
```

That might do what you want, and then just turn it back to warning at the bottom of the function you want to log.

there is nothing built in to be able to configure a per module log level.

Daniel

**Comment by daks** [comment]
I'm not sure but I think Salt uses the standard Python logging module. And this one let you do just what I want, so I'm surprised it's not possible in Salt.

**Comment by gtmanfred** [comment]
Yes, we use the python logging module, but we have a bunch of other stuff on it to make sure that it handles multiprocessing and other stuff better.

All of that can be found here https://github.com/saltstack/salt/blob/develop/salt/log/setup.py

**Comment by daks** [comment]
Issue is still relevant.

**Comment by daks** [comment]
still relevant

**Comment by sagetherage** [comment]
@dwoz can you please attempt to answer the `Question` and then update the ticket, please?

**Comment by daks** [comment]
still relevant
