### ISSUE TITLE
Documentation on how to downgrade SaltStack

### ISSUE THREAD

**Issue by kveroneau** [saltstack/salt#47916]
### Description of Issue/Question
I noticed that a few things which worked in 2017.7.? are now broken in 2018.3.0, and some of the changes to state modules are not forward compatible requiring states to be updated.

In the case of accidental or automated updates to the salt-master or salt-minion, documentation should be available on how to properly downgrade to a prior version of SaltStack.

### Setup
Upgrade your SaltStack from 2017.7.5 to 2018.3.0, and notice that say `mysql_grants` state is now broken, and oddly `mysql.user_grants` reports it as being set, but doing a real check in MySQL indeed shows the grant is not set.  This costed about an hour of troubleshooting to figure out why a database was failing on a newly provisioned box...  This is just an example, an issue for `mysql_grants` has already been reported.  This issue is to request downgrade documentation.

### Steps to Reproduce Issue
Visit docs.saltstack.com and see no documentation on how to properly downgrade SaltStack.

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.10 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-6-amd64
         system: Linux
        version: debian 8.10

**Comment by garethgreenaway** [comment]
@kveroneau Thanks for the report.  There is some information about pinning Salt to specific versions on the https://repo.saltstack.com/ page, but having it in the documentation would be helpful.
