### ISSUE TITLE
Does it support grains judgment to do some operations

### ISSUE THREAD

**Issue by topicgit** [saltstack/salt#47919]
### Description of Issue/Question
I have two computer rooms, D and E, and each machine sets up the labelling of the upper computer room through grains.

Now I want to distribute different files through the computer labelling set up by grains. How should I write?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
salt dd-web89-e.ld.co grains.item idc_tag
```
dd-web8989-e.ld.co:
    ----------
    idc_tag:
        E

{% if grains['idc_tag'] == 'E' %}
/home/work/www/run/dd-web/.env:
  file.managed:
    - source: salt://webapps/dd-web/files/config/prod-e/.env
    - makedirs: True
    - user: work
    - group: work
{% endif %}
```

```
salt dd-web89-e.ld.co state.sls tmp.jiet test=True
dd-web89-e.ld.co:
    Data failed to compile:
----------
    Rendering SLS 'base:tmp.jiet' failed: Jinja variable 'dict object' has no attribute 'idc_tag'
```
### Steps to Reproduce Issue

(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@topicgit Thanks for the report.  What you have above should work, I'd suspect that something isn't synced up and when you're running the state run the grains are not available.  A safer approach would be the following:
```
{% if salt['grains.get']('idc_tag', '') == 'E' %}
/home/work/www/run/dd-web/.env:
  file.managed:
    - source: salt://webapps/dd-web/files/config/prod-e/.env
    - makedirs: True
    - user: work
    - group: work
{% endif %}
```
This approach is calling out to the `get` function in the `grains` module but also includes a default value in the event that the grain value is unable.

**Comment by topicgit** [comment]
@garethgreenaway Thank you very much. It's working now.
