### ISSUE TITLE
.format in log.debug can cause unicode error in template.py

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#47934]
### Description of Issue/Question

Much like the unicode error That happened in #44452. 
.format does not like when unicode is put through it's variables. 

For that reason if unicode is in any of the variables between 
https://github.com/saltstack/salt/blob/v2017.7.5/salt/utils/templates.py#L456-L460

You will end up with a unicode error, instead of the actual error produced. even if not useing debug. 

### Setup
Use a template that will be rendered and has unicode, and get jinja to throw an error that isn't caught through the other catches.

### Steps to Reproduce Issue
This is based on observation. Have not found a way to trip the exception everytime that gets to that point. but have seen .format throw unicode exceptions in much the same way before. 

### Versions Report

```
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by whytewolf** [comment]
ZD-2514

**Comment by gtmanfred** [comment]
Does this still happen in 2018.3?

**Comment by whytewolf** [comment]
@gtmanfred no, it does not happen in 2018.3. Sorry for the late response.

**Comment by gtmanfred** [comment]
Ok, my recommendation is going to be updating to 2018.3, specifically because of all of the work we added for making sure unicode worked on py2 and py3.
