### ISSUE TITLE
how to revise the configure path?

### ISSUE THREAD

**Issue by cong520** [saltstack/salt#47942]
we know,the configure path is /etc/salt  ,now, I want to set the configure path as /opt/salt .
What should I do?
eg: the minion configure?

**Comment by gtmanfred** [comment]
if you put the minion config file in /opt/salt/minion, you can pass `-c /opt/salt/` and then specify the root_dir or any of the other minion options to move the configuration and other files there.

You will also need to edit your init scripts, or use a dropin file for systemd to point to using that directory for the minion config.

https://docs.saltstack.com/en/latest/ref/configuration/minion.html
