### ISSUE TITLE
Question: How to update windows salt minion - silent installation

### ISSUE THREAD

**Issue by GitHubAre** [saltstack/salt#47971]
### How to update salt minion on windows from command line?
I havent found direct answer to this in the docs, but I think that calling the .exe might do the trick and there is actually no need to uninstall the previous version (just guessing based on googling).

### Steps to Reproduce Issue
Lets say I have Installed minion version 2018.3.0 and now version 2018.3.1 is released.
Can I run the executable like this:
Salt-Minion-Setup.exe /S /master=1.2.3.4 /minion-name=name
Will this perform an upgrade?
Is there some recommendation i.e. files to backup?

Thank you!

**Comment by xenophonf** [comment]
Re-run the installer with the same flags as before.  You can test this yourself by installing an older minion and then upgrading it.  It preserves the existing configuration and keying material.

Alternatively, configure the [Windows Package Manager](http://docs.saltstack.com/en/latest/topics/windows/windows-package-manager.html) to use [salt-winrepo-ng](https://github.com/saltstack/salt-winrepo-ng), and use it to install the upgraded package.

**Comment by garethgreenaway** [comment]
@GitHubAre Thanks for the report.  Does the suggestion by @xenophonf answer your question?

**Comment by GitHubAre** [comment]
@garethgreenaway Yes it does.
Thanks!
