### ISSUE TITLE
virt.running state silently drops libvirt errors

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#47972]
### Description of Issue/Question

The `virt.running` state doesn't report any of the libvirt error. Actually the code catching **libvirt.libvirtError** assumes that the error is that the domain was running, which case is ruled out by the `vm_state != 'running'` that is above. This exception catching statement should always report an error.

### Setup

The setup, just requires a salt master and a salt minion running on a KVM (or whichever hypervisor) host.

### Steps to Reproduce Issue

* On the minion, create a virtual network and make sure it is not started. This is important since this will trigger the start error later.
* On the minion, create a VM using the previously defined network.
* Start the VM using the following state file:

```yaml
vmname:
    virt.running
```

The salt minion will succeed and report `Domain master exists and is running` instead of throwing an error and saying that the VM can't start since the network is not up. Note that for that particular case, the libvirt exception that was caught has this message **Requested operation is not valid: network 'salt-test' is not active**

### Versions Report
Bug present in all versions of salt for far

**Comment by cbosdo** [comment]
Taking the issue, will submit a PR for it soon

**Comment by garethgreenaway** [comment]
@cbosdo Thanks for the report and the PR.
