### ISSUE TITLE
Blacklist salt-call for certain (or all) minions

### ISSUE THREAD

**Issue by rlschilperoort** [saltstack/salt#47997]
### Description of Issue/Question
Would it be possible to blacklist minions from using salt-call ?

I have a setup where not all of my minions are managed by me;
Some minions are in controll (root level) by other persons.
I do not want these minions to be able to "publish" a job to the master for example list the master salt:// folder/files
The publisher_acl_blacklist only applies for commands run from the master;
Is there any functionality I can configure at the "master" level that I can use to blacklist the minions functionaliteit/access ?

### Steps to Reproduce Issue
On the minion run the following command
salt-call cp.list_master_symlinks

Versions Report
salt-minion --version report
salt-minion 2018.3.0 (Oxygen)

**Comment by garethgreenaway** [comment]
@rlschilperoort Thanks for the report.  I don't believe this is currently supported but would be possible with an additional configuration flag for the minion.  Approving for as a future feature request.

**Comment by rlschilperoort** [comment]
@garethgreenaway Thanx for the quick response.
It would be great if this feature could be configured from/within the master and cannot be controlled/changed within the configuration at the minion side.

**Comment by rlschilperoort** [comment]
@garethgreenaway Thanx for the quick response.
It would be great if this feature could be configured from/within the master and cannot be controlled/changed within the configuration at the minion side.
