### ISSUE TITLE
Azure VM Custom Image

### ISSUE THREAD

**Issue by frankthetankmay** [saltstack/salt#48019]
### Description of Issue/Question
It's known that Salt can create Azure VM image from the Marketplace by specifying the publisher, sku etc... in the cloud profile. I would like to know whether Salt can create an Azure VM from a custom generalized image which is of type **Microsoft.Compute/images** not **Microsoft.Compute/virtualMachines**; this means just like a Marketplace image with no VHD but stored in our local Azure subscription.

### Setup
General question.

### Steps to Reproduce Issue
We cannot specify a generalized image name of type Microsoft.Compute/images

**Comment by gtmanfred** [comment]
@nicholasmhughes or @techhat do either of yall know the answer to this?

Thanks!
Daniel

**Comment by nicholasmhughes** [comment]
@frankthetankmay , to confirm... you want to specify the ID of an image resource instead of the publisher, sku, offer, and version... correct?

That functionality doesn't currently exist, but could be added somewhat trivially.

**Comment by frankthetankmay** [comment]
@nicholasmhughes Correct. Our custom image - similar to a Marketplace image - is created in our subscription below:

ResourceGroupName    : ****
SourceVirtualMachine : Microsoft.Azure.Management.Compute.Models.SubResource
StorageProfile       : Microsoft.Azure.Management.Compute.Models.ImageStorageProfile
ProvisioningState    : Succeeded
Id                   : /subscriptions/****/resourceGroups/****/providers/Microsoft.Compute/images/OurCustomImageName
Name                 : OurCustomImageName
Type                 : Microsoft.Compute/images
Location             : westus2
Tags                 : {}

Therefore, in our cloud profile we should be able to specify 'OurCustomImageName'. This gives us much more power in terms of feeding salt a more pre-configured image obviously. It also allows us to use managed disks. Is this trivial to enhance Salt with this functionality?

Thank you for your feedback.

**Comment by nicholasmhughes** [comment]
I'll take a look at the code, but it would probably entail adding a new keyword (say... `image_resource_id` or something like that) which would reference the full path to the resource ID of the image you want to use. Then, the code would use that instead of attempting to build the image reference from the publisher, etc. I can take a look at the change as early as tomorrow. Would you be able to test a patch once complete?

**Comment by frankthetankmay** [comment]
@nicholasmhughes Yes we can test the patch once complete. This is a customer's Salt install so I would need to get approval from there devops team to apply the patch but that shouldn't be an issue since we need this behaviour to get them moved to Azure ideally. I appreciate you working on this. 

Thank you.

**Comment by nicholasmhughes** [comment]
What version are they running?

**Comment by frankthetankmay** [comment]
2018.3.0 Latest version. If you need version detail I can SSH to server and get it in a few. Let me know thanks.

**Comment by frankthetankmay** [comment]
@nicholasmhughes see below

# salt --versions
Salt Version:
          Salt: 2018.3.0

Dependency Versions:
          cffi: 1.11.5
      cherrypy: 3.5.0
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 0.6.4
     gitpython: 1.0.1
         ioflo: Not Installed
        Jinja2: 2.8
       libgit2: Not Installed
       libnacl: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.3
  msgpack-pure: Not Installed
msgpack-python: 0.4.6
  mysql-python: Not Installed
     pycparser: 2.18
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
  python-gnupg: Not Installed
        PyYAML: 3.11
         PyZMQ: 15.2.0
          RAET: Not Installed
         smmap: 0.9.0
       timelib: Not Installed
       Tornado: 4.2.1
           ZMQ: 4.1.4

System Versions:
          dist: Ubuntu 16.04 xenial
        locale: UTF-8
       machine: x86_64
       release: 4.4.0-87-generic
        system: Linux
       version: Ubuntu 16.04 xenial

**Comment by nicholasmhughes** [comment]
@frankthetankmay , I also want to make sure that you understand that the current stable version does not have support for a lot of functionality which you may require, such as managed disks, assigning instances to availability sets and backend load balancer pools, as well as working userdata script functionality.

**Comment by frankthetankmay** [comment]
@nicholasmhughes When you say there is no support for managed disks, can you clarify. Does this mean you cannot create VMs with managed disks and/or does it mean we cannot configure a VM, install app software on the VM with Salt if that VM has a managed disk?

**Comment by nicholasmhughes** [comment]
Purely from a cloud module instance creation perspective. The current stable version is only capable of creating instances with "unmanaged" blob storage disks.

**Comment by nicholasmhughes** [comment]
I'm not sure I follow your meaning... There are execution modules in `develop` which can perform the "generalize" operation, etc. However, that is not in a stable release.

**Comment by frankthetankmay** [comment]
Ok understood. I suppose we will continue on with unmanaged disks then and will move to managed disks when the next stable release includes creating generalized images. 

I appreciate your quick feedback on this.

**Comment by frankthetankmay** [comment]
@nicholasmhughes One final question here. If we were to use the Develop version, does it include the ability to specify Azure custom image in our cloud profile or would you need to add it to there first? Customer would consider using this version to test their process of generalized images.

Thanks

**Comment by nicholasmhughes** [comment]
No. It's not in develop either. However, I could probably have the patch in by the end of tomorrow. PRs get merged pretty quickly for small fixes like that.

**Comment by frankthetankmay** [comment]
I would appreciate it if you could put it in for us. We would be able to test it tomorrow or Monday whenever you are ready with it.

Thanks
