### ISSUE TITLE
Docker state authenticate with credentials helpers

### ISSUE THREAD

**Issue by oarmstrong** [saltstack/salt#48066]
### Description of Issue/Question

I have a docker image registry (AWS ECR) that requires authentication before pulling images. I'm making using of a [credential helper](https://github.com/docker/docker-credential-helpers), specifically the [amazon-ecr-credential-helper](https://github.com/awslabs/amazon-ecr-credential-helper) project.

With my configuration I am able to pull images using the Docker CLI without any prior commands, that is no `login` or similar. However, this does not appear to work with Salt.

I believe this may be related to #40480 when the Docker authentication was rewritten.

I have only briefly tried to look at the Docker code, would it be possible with the current way it works to handle this feature? I'd be more than happy to take a look myself if I can get a little guidance where to look. I'm aware this may be something that `docker-py` has to support (if it doesn't already).

It may be worth noting that I've had problems with `docker-compose` (https://github.com/docker/compose/issues/4948) which could be relevant.  The configuration I've outlined below is what works with `docker-compose` correctly.

### Setup

`/root/.docker/config.json`:

```
{
	"auths": {
		"XXXXXXXXXXXX.dkr.ecr.eu-west-1.amazonaws.com": {}
	},
	"credsStore": "ecr-login"
}
```

### Steps to Reproduce Issue

1. Install the `amazon-ecr-credential-helper` binary.
1. Use my above template for `/root/.docker/config.json` and configure `/root/.aws/credentials`.
1. See that images can be pulled from that repository without any authentication required.
1. Wait for 8 hours for the token to be revoked (or work out how to manually revoke the token).
1. Write a simple salt state using `docker_container.running` with an image from the private repository.
1. See that the container fails to run as authentication fails.

### Versions Report

**Master:**

```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

```

**Minion:**

```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by gtmanfred** [comment]
We just use the .docker/config.json file for the user salt is running as.

Does the helper script just reauthenticate?

This would be pretty simple to do the docker state, and then add an onfail: requisite, and if it fails, just do a cmd.run state for authenticating again, and then add a second copy of the state, that only runs onfail as well, but after the token is recreated.

**Comment by oarmstrong** [comment]
Sorry I'm not actually intimately familiar with how the credential helpers work.

That docker configuration let's docker know that it needs to basically run the `ecr-login` binary to obtain the authentication token. The binary does what it needs to do to grab an authentication token from AWS and then caches it for future use, returning it to docker to use to authenticate to the registry.

When using this interactively on the CLI, there's no other commands needed. One just configures the `.docker/config.json` and everything works. I do not need to run `docker login`, nor any other command.

---

With some further testing, it works using `salt-call` on the minion but not running `salt` from the master. This looks to me like an environment issue. Good chance this could be a configuration error on my behalf. I'll keep investigating and report back later today.

**Comment by oarmstrong** [comment]
Sorry for the ping but can you have a look at my update please @gtmanfred ?

**Comment by gtmanfred** [comment]
Which home are you trying to set? your users home or root's home?

You can set HOME in the a systemd dropin file.

```
# mkdir /etc/systemd/system/salt-minion.service.d/
# tee /etc/systemd/system/salt-minion.service.d/home.conf <<HERE
[Service]
Environment=HOME=/home/user
HERE
```

And that should set it on the environment in the service.  This is specifically a systemd thing since it isn't actually a shell, it doesn't get all the environment variables, so you have to set what you need on the systemd service.

**Comment by oarmstrong** [comment]
Yep I get that I could do that, thanks. Wasn't too sure if there would be other repercussions though. If you aren't too happy with my proposed patch then I won't bother working on it and I'll use the workaround. I can't think of any nicer codebase solutions so feel free to close this up.

Cheers.

**Comment by gtmanfred** [comment]
Cool, :+1: yeah, i am just not sure that setting a HOME manually is the correct way to do this.  It feels much better to just have the user set the HOME variable if they need it.

Thanks!
Daniel
