### ISSUE TITLE
Client safe mode

### ISSUE THREAD

**Issue by JensRantil** [saltstack/salt#48065]
We recently had an issue where someone mistakenly executed

    salt '*' state.highstate

. This, combined with a small bug, temporarily brought down a few services. MySQL has [`--safe-updates`](https://dev.mysql.com/doc/refman/8.0/en/mysql-command-options.html#option_mysql_safe-updates) which forces a user to set limits on executions. How about having a setting in the Salt client config that forces a user to define a batch window (`-b`) when applying changes?

**Comment by gtmanfred** [comment]
I am marking this as a feature request.

**Comment by gtmanfred** [comment]
Actually... Would this work for you?

```
# These two batch settings, batch_safe_limit and batch_safe_size, are used to
# automatically switch to a batch mode execution. If a command would have been
# sent to more than <batch_safe_limit> minions, then run the command in
# batches of <batch_safe_size>. If no batch_safe_size is specified, a default
# of 8 will be used. If no batch_safe_limit is specified, then no automatic
# batching will occur.
#batch_safe_limit: 100
#batch_safe_size: 8
```

It was added here https://github.com/saltstack/salt/pull/41021  to fix https://github.com/saltstack/salt/issues/19054

And is in 2018.3.0.

**Comment by JensRantil** [comment]
@gtmanfred `batch_safe_size` is exactly what I was looking for! Thanks!

**Comment by Hitamashi** [comment]
@gtmanfred Sorry for bring up this issue. May I know if you guys will bring this feature to Salt 2017.7?

**Comment by gtmanfred** [comment]
We do not backport features, only bug fixes.  so you will need to upgrade to get the new feature.
