### ISSUE TITLE
Restarting windows minion during state execution and continue after restart

### ISSUE THREAD

**Issue by GitHubAre** [saltstack/salt#48073]
### How to restart windows minion during salt state and execute other states after reboot

Can you please give me a hint in this scenario:
`I would like to rename disk where pagefile.sys is located from D: to S:`

**This activity consists of these steps:**

1. Move paging file from D: to C:
2. Rename D: to S:
3. Reboot computer
4. Move paging file to S:
5. Reboot again

I know how to do those steps individually, but not in a sequence inside one sls file :(

**Comment by Ch3LL** [comment]
you can look at saltstack orchestration here: https://docs.saltstack.com/en/2017.7/topics/orchestrate/orchestrate_runner.html

**Comment by GitHubAre** [comment]
My scenario is in terms of event-driven infrastructure where new minion is created (in Azure) and I would like to apply certain states (like moving the pagefile.sys swap file) when that event is fired.

That would mean creating orchestration that is running against a single minion (the one that fired the event). I know that orchestration is used where multiple deployment targets need to be coordinated, therefore it sounds weird.

Would you recommend using orchestration runner in that scenario?

**Comment by Ch3LL** [comment]
ahh thanks for clarifying. Might be best to use saltstacks reactor which can run some states after certain events. Here are the docs for the reactor: https://docs.saltstack.com/en/latest/topics/reactor/

Essentially you can create the node and salt-cloud will create events once its created adn started. And once that event is seen you can have the reactor run certain states adn then once it restarts run the rest of the states that you want. :)

I think that approach is more dynamic for your setup :) Hopefully that makes sense

**Comment by GitHubAre** [comment]
I understand the part when I will hookup my state file to machine start event (or cloud event). Which I am not certain about is how to continue after I reboot the computer. What I assume is that it will reboot - for example after joining to active directory domain and once it reboots it will fire another new event and it will run the same state file as it did before the reboot. The difference will be - that it will not reboot after the state where domain join happened, because it is already in domain and it will continue with afterwards steps. Is my assumption correct?

Thank you very much for your answers!

**Comment by Ch3LL** [comment]
You can take a look here to see what kind of events you can react off of: 

https://docs.saltstack.com/en/latest/topics/event/master_events.html

In your situation this is one way to approach it:

1. When you see this event `salt/cloud/*/created` you run the first initial states before the VM reboots.

(to note: an alternative is to use the configuration: `start_action: state.highstate` documented here: https://docs.saltstack.com/en/latest/topics/cloud/deploy.html#post-deploy-commands  essentially these are post deploy commands you can run. Might be easier to use this approach on the first state run, depending on your use case)

During this first initial state run you run whatever states you want including the restart. 

2. then you will probably want to wait for this event `salt/minion/<MID>/start` to run the rest of your states.

One problem you will run into is this start event occurs anytime the minion starts so you need to make sure you add a check to your state to see if this state has run previously. One way to do that is to set a grain teh first time its run and check for that grain each time.

**Comment by GitHubAre** [comment]
I have used startup event targeting specific .sls files which did the work.
Thank you very much :)
