### ISSUE TITLE
Saltstack to manage db clusters as minion

### ISSUE THREAD

**Issue by indigoarc** [saltstack/salt#48093]
### Description of Issue/Question
I have a DB server which has 5 nodes as a DB cluster.
They share the same DNS name and the primary node owns the DNS name.

Question:
When install minion on these nodes, is there any special considerations? 
I assume they would have to have the same minion id so that master can communicate with any one of those being the master?
Is there any instruction on how to do this?
Thanks.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
the minion id needs to be unique so you will need to give the nodes unique minion ids.

**Comment by indigoarc** [comment]
Would that be an issue if the same DNS name used by many minions depending which node is the primary in the cluster?

**Comment by Ch3LL** [comment]
it should not but please open an issue if you see any problems
