### ISSUE TITLE
Failed to load ext_pillar git: object.__new__(thread.lock) is not safe, use thread.local.__new()

### ISSUE THREAD

**Issue by frankthetank** [saltstack/salt#48107]
I posted the following over on the Google group at https://groups.google.com/forum/#!msg/salt-users/_wr0Bd2RRxo/X9d4SizNAgAJ but received no responses so I am assuming that it's not an easy configuration issue that I've somehow borked.

I am receiving the above message when trying to load pillar data from git.  If I load the pillar data from local storage then I do not receive this error.

Unfortunately I am not able to copy the entire stack over, but the first five lines (transcribed) are:
```
2018-06-08 15:05:02,571 [salt.pillar    :951 ][ERROR  ][11678] Exception caught loading ext_pillar 'git':
File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 941, in ext_pillar
  key)
File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 870, in _external_pillar_data
  *val) 
File "/usr/lib/python2.7/site-packages/salt/pillar/git_pillar.py", line 446, in ext_pillar
  local_pillar = Pillar(opts, __grains__, minion_id, env)
File "/usr/lib/python2.7/site-packages/salt/pillar/__init__.py", line 371, in __init__
  ext_pillar_opts = copy.deepcopy(self.opts)
...
```
Everything beyond that descends into the copy.deepcopy() realm.  

salt-master pillar configuration (note that the salt states appear to work properly):
```
ext_pillar:
  - dev git@mygitserver:infrastructure/salt-pillars.git
pillarenv_from_saltenv: True
```

The current dev:top.sls looks like:
```
dev:
  'roles:gitlab-runner':
    - match: grain
    - gitlab-runner
```

The gitlab-runner/init.sls looks like:
```
gitlab-runner:
  registration_token: aaaabbbbcccc
```
If I run 
`salt-call pillar.data pillarenv=dev` on the minion or `salt '*' pillar.data pillarenv=dev` on the server then the above error is displayed.

Does anyone have any thoughts on what could be wrong here or a generally better way to approach this?

As with the stacktrace, I cannot copy the version report as is so I will transcribe what I hope are the most relevant portions:
```
Salt Version:
     Salt:  2018.3.0

Dependency Versions:
...
    gitdb: 0.6.4
gitpython: 1.0.1
...
     pygit2: 0.26.4
    Python: 2.7.5 (default, Apr 11 2018, 07:36:10)

System Versions:
      dist: centos 7.5.1804 Core
     locale: UTF-8
   machine: x86_64
   release: 3.10.0-862.3.2.el7.x86_64
    system: Linux
    version: CentOS Linux 7.5.1804 Core
```
Thanks!

**Comment by Ch3LL** [comment]
im suprised in your configuration here: ```ext_pillar:
  - dev git@mygitserver:infrastructure/salt-pillars.git``` that you do not have any auth setup like keys as this is using ssh. Have oyu just removed that information for the sake of sanitizing the output here?

Was this working previously?

**Comment by frankthetank** [comment]
The git keys are defined in the global git_pillar_*key since all of my repositories are accessed by the same git user.

As far as working, I've never had the pillar data pulling from git due to this error.  All pillar data this far was from the local (server) filesystem.  I do have salt started pulling from git, though.

**Comment by frankthetank** [comment]
Is there any additional info needed to maintain the "Info Needed" label?  I've been able to change how I access the network that I am deploying salt into and can now grab the full output from commands rather than having to retype everything.  I am attaching the full version report below.

```Salt Version:
           Salt: 2018.3.1
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Ch3LL** [comment]
thanks for the additional information.

ping @terminalmage any ideas here?

**Comment by terminalmage** [comment]
This is not valid git_pillar configuration, since you haven't told `git_pillar` which ext_pillar to use:

```yaml
ext_pillar:
  - dev git@mygitserver:infrastructure/salt-pillars.git
```

It would need to be something like this:

```yaml
ext_pillar:
  - git:
    - dev git@mygitserver:infrastructure/salt-pillars.git
```

However, this may just have been an omission made in the creation of the initial post. I configured a git external pillar on CentOS 7 and was unable to reproduce this. What this suggests is that the issue is unique somehow to your configuration.

The opts should only ever contain dicts and lists, and the string/numeric data types. My recommendation is for you to edit `/usr/lib/python2.7/site-packages/salt/pillar/__init__.py` and add the following directly before the deepcopy on line 371:

```python
import pprint
log.warning('master opts: %s', pprint.pformat(self.opts))
```

The `log.warning` is to ensure that it is printed to the log file with the default log level. Then, start the master and minion again, and take a look at the log file. Look for anything that doesn't look like a dictionary, list, or string/numeric data type. For example, something like a class instance, i.e. something that looks like `<foo.Bar instance at 0x7fdb445539e0>`.

Let me know what you find.

**Comment by frankthetank** [comment]
Thanks!!  I hope it was an omission on my part in transcribing configuration but will double check tomorrow when I get into the office.

**Comment by frankthetank** [comment]
OK - I verified that the configuration noted above was an error when I transcribed the configuration from my other network over to here.  HOWEVER - I have also run through an upgrade to the latest salt version and the error is no longer occurring.  Weird, but resolved.

**Comment by terminalmage** [comment]
@frankthetank OK, if this happens in the future, my suggestion for troubleshooting would be the same, so keep this in the back of your mind.
