### ISSUE TITLE
 Salt-master executes 'ulimit -n' and gets a wrong result

### ISSUE THREAD

**Issue by linuxyn** [saltstack/salt#48119]
### Description of Issue/Question
Sometimes I can't use the salt master to get the correct ulimit -n execution result，The result of executing with salt-master is 1024。But I manually logged in to ssh and executed 'ulimit -n' directly. I found it to be 65535.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
[root@master_1 ~]# ulimit -n
655350
[root@master_1 ~]# salt 'master_1' cmd.run 'ulimit -n'
master_1:
    1024
[root@master_1 ~]#

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2017.7.1-5642-g543d3ef

Dependency Versions:
           cffi: 1.11.2
       cherrypy: 3.2.3
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.2 (default, Dec  6 2011, 12:12:28)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6

System Versions:
           dist: centos 6.6 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-504.16.2.el6.x86_64
         system: Linux
        version: CentOS 6.6 Final

**Comment by Paulo-Nunes** [comment]
I also experience this issue on both 2017.7.7 and 2019.2.0.
This happens on at least RHEL7 and maybe some RHEL6

`cmd.run "su - user -c 'ulimit -Sn -Hn'"`
```
    logname: no login name
    open files                      (-n) 8192
    open files                      (-n) 8192
```

on the minion it is:
```
open files                      (-n) 1024
open files                      (-n) 1024
```

I have tried using runas and playing with the shell and variables, but nothing seems to work.
This does not occur on every minion.  Everytime the `logname: no login name` error shows up the output is incorrect.

There are many issues like this. Some say to use `su -l`, but that does not work for me.  This really limits salts ability to do things on minions.

**Comment by Paulo-Nunes** [comment]
Issue still exists
