### ISSUE TITLE
apk.py Python 3 compatibility

### ISSUE THREAD

**Issue by bowmanjd-lms** [saltstack/salt#48128]
https://github.com/saltstack/salt/blob/9a0ec9c30f65338dda31613516ac8a6121dfb0cb/salt/modules/apk.py#L307

In Python 3, this yields `TypeError: 'dict_keys' object does not support indexing`

Similar to Issue #40437

I suggest:
`next(iter(p)) for p in pkgs`

PR #48131

**Comment by garethgreenaway** [comment]
@bowmanjd-lms Thanks for the report and the PR!
