### ISSUE TITLE
(feature) Allow `state.single` to accept a path to a SLS file to run

### ISSUE THREAD

**Issue by nickgarber** [saltstack/salt#48139]
### Description of Issue/Question
 Allow `state.single` to accept a path to a state file to run

For example:

```
salt-call --local state.single --sls-file=<<EOF
useful for embedding salt, testing stanzas, and sharing snippets:
  test.succeed_without_changes:
     - name: "A well-intended but specious example :)"
EOF
```

I find that I'll often switch back and forth between YAML stanzas and CLI `state.single` calls while testing and sometimes wish there was less translating in that process.

Use Cases include:
 - embedding stand-alone states inside systemd service units and shell scripts
 - incrementally running a large SLS one stanza at a time from the CLI
 - eases some kinds of stanza/unit-testing

Benefits:
 - Makes for a _very_ simple and grokable demo of declarative state management.
 - Simplifies some "masterless" use cases.
 - Lowers translational friction between the CLI and YAML forms when authoring states.
 - May remove the need to learn the CLI syntax for some folks, where YAML is the only desired, expected, or accepted format.

Open Questions:
 - Should this only work in `--local` mode?
 - Is `state.single` the best place for this capability?
 - Are the proposed/example CLI arguments the best choice?

**Comment by garethgreenaway** [comment]
The state module has a `template` function that I believe will accomplish what you want:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html#salt.modules.state.template

**Comment by nickgarber** [comment]
Cheers @garethgreenaway, thanks for that!

For anyone interested, here's an example incantation I've settled on for interactive, cut/paste states:
```
$> ln -fs $(mktemp) ~/scratch.sls ; cat <<EOF > ~/scratch.sls ; salt-call state.template tem=~/scratch.sls
# Copy Pasta State from $(date)
firewall-config:
  firewalld.present:
    - name: public
    - services:
      - mysql
      - ssh
EOF
```

I think there should be a `read` and `$REPLY` herestring incantation that could also shake out of this.
