### ISSUE TITLE
Failed to load ext_pillar saltclass: can only assign an iterable

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#48145]
### Description of Issue/Question

Saltclass is not compatible with existing reclass tree - it fails on empty yaml keys.

### Steps to Reproduce Issue

Example class `consul.yml`:

```
classes:
states:
pillars:
  consul:
    cur_version: 1.0.3
    versions:
      1.0.3:
        source: https://releases.hashicorp.com/consul/1.0.3/consul_1.0.3_linux_amd64.zip
        source_hash: sha256=4782e4662de8effe49e97c50b1a1233c03c0026881f6c004144cc3b73f446ec5
```

The place where it fails with Exception:

```
            # Now replace class element in classes_to_expand by expansion
            if 'classes' in expanded_classes[klass]:
                l_id = classes_to_expand.index(klass)
                print(expanded_classes[klass])
                classes_to_expand[l_id:l_id] = expanded_classes[klass]['classes']
```

This is printed before the exception:
```
{
    u'states': None,
    u'pillars': {
        u'consul': {
            u'cur_version': u'1.0.3', u'versions': {
                u'1.0.3': {
                    u'source': u'https://releases.hashicorp.com/consul/1.0.3/consul_1.0.3_linux_amd64.zip',
                    u'source_hash': u'sha256=4782e4662de8effe49e97c50b1a1233c03c0026881f6c004144cc3b73f446ec5'
                }
            }
        }
    },
    u'classes': None
}
```

And this is the exception itself:

```
  File "/Users/user/.virtualenvs/salt-2018/lib/python2.7/site-packages/salt/utils/saltclass.py", line 178, in expand_classes_in_order
    classes_to_expand[l_id:l_id] = expanded_classes[klass]['classes']

[CRITICAL] Pillar render error: Failed to load ext_pillar saltclass: can only assign an iterable
local:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Failed to load ext_pillar saltclass: can only assign an iterable
```

### Versions Report

<details><summary>salt --versions-report</summary>
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, May  2 2018, 00:53:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 17.6.0
         system: Darwin
        version: 10.13.5 x86_64
</details>

**Comment by max-arnold** [comment]
Simple fix:

```
-           if 'classes' in expanded_classes[klass]:
+           if expanded_classes[klass].get('classes'):
```

@olivier-mauras

**Comment by olivier-mauras** [comment]
Thanks for the fix, do you mind sending a PR directly?

**Comment by gtmanfred** [comment]
would it be better to do `isinstance(expanded_classes[klass], dict) and 'classes' in expanded_classes[klass]`?

If one of yall would be able to submit a PR we would greatly appreciate it.

Thanks!
Daniel

**Comment by max-arnold** [comment]
I'll submit the PR.

@gtmanfred Are you sure that `expanded_classes[klass]` is a `dict`? In all these examples it is a list: https://docs.saltstack.com/en/latest/topics/releases/2018.3.0.html#new-saltclass-pillar-master-tops-modules

**Comment by gtmanfred** [comment]
If it is not a dict, then `+           if expanded_classes[klass].get('classes'):` won't work.  because only dicts have a .get function.

I was just going off what you posted above.

**Comment by gtmanfred** [comment]
Nevermind, I understand what you are trying to do now, approved PR, thanks for the integration test too!

**Comment by gtmanfred** [comment]
Looks like the fix for this has been merged.

**Comment by max-arnold** [comment]
Sorry that I haven't closed the issue. My impression was that it should be done after a merge-forward is completed.

**Comment by gtmanfred** [comment]
No worries, i just happened to come across the issue today, and saw the fix was merged.
