### ISSUE TITLE
win.powercfg documentation is incorrect 

### ISSUE THREAD

**Issue by adamsewell** [saltstack/salt#48169]
### Description of Issue/Question
The documentation located https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_powercfg.html states that the value for set_timeout is in minutes but it's actually in seconds.

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows can you confirm?

**Comment by rallytime** [comment]
@adamsewell Can you give the fix in #48345 a try?
