### ISSUE TITLE
service.running times out while waiting on a Windows service that starts successfully after 90 seconds.

### ISSUE THREAD

**Issue by samc-6ft** [saltstack/salt#48163]
### Description of Issue/Question
I have a service that has a long startup time; greater than 90s.  Unfortunately this is something I can't control as the software is not mine.  When running a service.running against the minion hosting the service Salt reports the service failed to start after 90 seconds.  After logging into the minion and checking the services list the service was still starting up and actually came up successfully around 120 seconds.

I attempted to use init_delay, but that only applies after the service has reported back within the first 90 seconds.  What I need is a way to extend the timeout that salt waits for a service to start.

### Setup

test_service_start.sls

startup_service:
  service.running:
    - name: some_service
    - enable: False

### Steps to Reproduce Issue
Execute a service.running against a Windows service with a long (90+seconds) start up time.  Observe timeout at 90 seconds.  Observe process continuing to start correctly on minion.

### Versions Report
The salt master and minion are on the same salt version (2017.7.2)

Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 19 2016, 06:48:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-65-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by samc-6ft** [comment]
I should add that the minion is running Windows Server 2012 R2 Standard.

**Comment by Ch3LL** [comment]
looks like for the win_service module it checks for the status here: https://github.com/saltstack/salt/blob/v2018.3.1/salt/modules/win_service.py#L416

which RETRY_ATTEMPTS is hardcoded to 90.

ping @saltstack/team-windows is there purpose behind hardcoding this value?

**Comment by damon-atkins** [comment]
Windows Start and Stop Services have 30 seconds to respond.   If they do not respond the service goes into an error state.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms685149.aspx

Anything over 35 is most likely wasting time.

**Comment by damon-atkins** [comment]
Windows Start and Stop Services have 30 seconds to respond. If they do not respond the service goes into an error state.

However seems there are work around for it.
https://msdn.microsoft.com/en-us/library/windows/desktop/ms685149.aspx

Could you stop the service and start it and run this every 10 seconds until it has started.
salt-call  service.info name_of_service

Does the service have any dependency?   i.e. its starting these first?

**Comment by samc-6ft** [comment]
This is where it sits until it starts, and then I get the output posted above.

```
Status:
        Start Pending
    Status_CheckPoint:
        1
    Status_ExitCode:
        No Error
    Status_ServiceCode:
        0
    Status_WaitHint:
        1000
```
