### ISSUE TITLE
[salt syndic] : Error targeting minions

### ISSUE THREAD

**Issue by PhilCANDIDO** [saltstack/salt#48187]
### Issue Description
I realize a architecture with a master, syndic and minions managed by syndic.
The architecture is detailled in section _Description of architecture_

The master is the server __prv01.lan__.
The syndic is the server __prv02.dmz__.
The minion is the server __api01.dmz__.

From the master :   
When I try the command test.ping on all minions, I have a response :
```
root@prv01.lan:~# salt '*' test.ping
prv01.lan:
    True
prv02.dmz:
        True
api01.dmz:
        True
```
We can not targeting the minion managed by the syndic. Only the minion installed on salt-syndic respond to the test.ping command.    
Example :  
```
root@prv01.lan:~# salt '*.dmz' test.ping
prv02.dmz:
        True
```
But if a stop the salt-minion on syndic server I have a reponse from minion server under the syndic :   
```
root@prv01.lan:~# salt '*.dmz' test.ping
api01.dmz:
        True
```

I restart the salt-minion on syndic server, and a test the test.ping command on it :   
```
root@prv02.dmz:~# salt '*.dmz' test.ping
api01.dmz:
        True
``` 

### Description of architecture
I have the following architecture :   
function | Hostname | packages | versions
-------- | -------- | --------  | --------
Master | prv01.lan | salt-master | 2018.3.1
Syndic | prv02.dmz | salt-master, salt-minion, salt-syndic | 2018.3.1
minion | api01.dmz | salt-minion | 2018.3.0

### Setup files
On master (prv01) :   
- /etc/salt/master :   
```
## Saltstack Master Configuration
# Network binding
interface: 0.0.0.0
ipv6: False

# Security
hash_type: sha256
order_masters: True
```

On syndic server (prv02) :
- /etc/salt/master :
```
# Salt-syndic configuration file
syndic_master: prv01
## Saltstack Master Configuration
# Network binding
interface: 0.0.0.0
ipv6: False

# Security
hash_type: sha256
```
- /etc/salt/minion :
```
## Salt-minion configuration file
# Master address or hostname
master: prv01.lan
```

On minion server (api01):
- /etc/salt/minion :
```
## Salt-minion configuration file
# Master address or hostname
master: prv02.dmz
```

### Versions Report
__Same version on each servers__
# salt --versions-report
Salt Version:
           Salt: 2018.3.1

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-128-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by PhilCANDIDO** [comment]
Before the upgrade, the syndic server worked normaly.   

I complete my explantion with this schema.   
![issue48187](https://user-images.githubusercontent.com/13585152/41641314-2d156b70-7465-11e8-979d-88dcff279a52.png)

I realized the following tests.   
## Tests
### Scenario 1
On prv02.dmz salt-minion, salt-master and sant-syndic are running.
```
root@prv01.lan:~# salt '*' test.ping
prv02.dmz:
    True
api01.dmz:
    True
wbe01.dmz:
    True
wfe01.dmz:
    True
dbm.dmz:
    True
```
   
```		
root@prv01.lan:~# salt '*.dmz' test.ping
prv02.dmz:
    True
```
Only the salt-minion on the server prv02.dmz is responding. There is no timeout error on minions. The minions under the syndic server __prv02.dmz__ are not targeting.

### Scenario 2
On prv02.dmz salt-master and sant-syndic are running and __salt-minion stopped__.

```
root@prv01.lan:~# salt '*' test.ping
api01.dmz:
    True
wbe01.dmz:
    True
wfe01.dmz:
    True
dbm.dmz:
    True
prv02.dmz:
    Minion did not return. [Not connected]
```
   
```	
root@prv01.lan:~# salt '*.dmz' test.ping
api01.dmz:
    True
wbe01.dmz:
    True
wfe01.dmz:
    True
dbm.dmz:
    True
prv02.dmz:
    Minion did not return. [Not connected]
```

In this case when I targeting the minions, all respond unless the minion on server prv02.dmz.

**Comment by WangWenchao** [comment]
Is there any update?  I met this today on 2019.2.0

**Comment by Ch3LL** [comment]
ping @DmitryKuzmenko are you able to look into this? i was never able to replicate this.

**Comment by DmitryKuzmenko** [comment]
@Ch3LL Sorry. Missed the notification. Thanks for ping.

@WangWenchao sorry it looks like you either have another issue or we need more input to understand why it could happen for you.

@PhilCANDIDO I've looked up the corresponding code and sorry can't say something useful by code review. Is it possible for you to share master and syndic debug log?
