### ISSUE TITLE
after upgrade to 2017.7.6 highrun is not possible

### ISSUE THREAD

**Issue by jasonvoor** [saltstack/salt#48197]
### Description of Issue/Question
as soon as a minion is upgraded to 2017.7.6 a highrun is not possible (Error message: "No Top file or master_tops data matches found.")
downgrade of the minion resolves the issue again.

### Setup
we use one top.sls in "base" which covers "playground" and "prod" environments:
```
$ cat top.sls
playground:
  'suma-*':
    - common

prod:
  'saltmaster':
    - common
```

### Steps to Reproduce Issue
show below is a test on the saltmaster itself, but the same it true for multiple minions running on ubuntu 16.04
```
$ salt saltmaster state.highstate test=true -l debug
[DEBUG   ] Missing configuration file: /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups_VIG.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups_VIG.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltmaster
[DEBUG   ] Missing configuration file: /home/rjesacher/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Missing configuration file: /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/nodegroups_xxx.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/nodegroups_xxx.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: saltmaster
[DEBUG   ] Missing configuration file: /home/foobar/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'lamgm002.mgnt.at_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/39/a311606f853fc6cb68ebf1ea11e4ab02cd65fd135ce9cfa8cf5dfc80298aeb/.minions.p
[DEBUG   ] get_iter_returns for jid 20180619103954556585 sent to set(['saltmaster']) will timeout at 10:39:59.569317
[DEBUG   ] jid 20180619103954556585 return from saltmaster
[DEBUG   ] return event: {'saltmaster': {'jid': '20180619103954556585', 'retcode': 2, 'ret': {'no_|-states_|-states_|-None': {'comment': 'No Top file or master_tops data matches found.', '__run_num__': 0, 'changes': {}, 'result': False, 'name': 'No States'}}, 'out': 'highstate'}}
[DEBUG   ] LazyLoaded highstate.output
saltmaster:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found.
     Changes:

Summary for saltmaster
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
```

### Versions Report
Salt Version:
           Salt: 2017.7.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by garethgreenaway** [comment]
@jasonvoor Thanks for the report.  For your minions are you including the environment during targeting or is it provided in the minion configuration file?

**Comment by jasonvoor** [comment]
it's only done via the "base" top.sls file - so targeting only.
The minions only have a "master:" line and eventually "test: true" - nothing else.

**Comment by JonathanWilbur** [comment]
@jasonvoor , I am having the same issue. It seems to have started upon just attempting to use the reactor system just once. I have since commented out all code that I have changed, and this issue persists, which seems to indicate it is a result of something bad being cached somewhere. I also have a bunch of errors showing:

```
[CRITICAL][17320] Engine 'reactor' could not be started!
```

Version information:

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by JonathanWilbur** [comment]
Actually, my problem was that I somehow incorrectly re-named an environment in my `top.sls` file. Please ignore my earlier comment. Sorry.

**Comment by jasonvoor** [comment]
meanwhile I upgraded everything to 2018.3.0 (the same version Suse Manager uses). the issue is gone here & it works again as expected.
