### ISSUE TITLE
poor performance of the state system in long distance connections

### ISSUE THREAD

**Issue by sundowner69** [saltstack/salt#48196]
### Description of Issue/Question
We see significant poor performance in the state system compared to execution system if dealing with minions far away from home. 
Our guess is that salt delivers much more data next to the "state.apply" event e.g. grains, pillars etc. which will slow down the process. Since we have a couple of states more (several hundred) in one highstate it takes half an hour and longer to run compared to a couple of seconds if executed traditionally by ssh or salt execution modules. Any idea about this? Help is very appreciated. Thank you very much for your assistance. 
**Example:**
Master is located in Germany, Minion in South Africa.

<pre><code>
master:/srv/salt # time salt minion cmd.run hostname
minion:
    minion

real    0m1.902s
user    0m0.245s
sys     0m0.054s
</pre></code>
<pre><code>
master # time salt minion state.apply hostname
minion:
----------
          ID: /bin/hostname
    Function: cmd.run
      Result: True
     Comment: Command "/bin/hostname" run
     Started: 09:42:36.382825
    Duration: 15.065 ms
     Changes:
              ----------
              pid:
                  27382
              retcode:
                  0
              stderr:
              stdout:
                  minion

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  15.065 ms

real    0m32.312s
user    0m0.593s
sys     0m0.067s
</pre></code>

### Setup
<pre><code>
master:/srv/salt # cat hostname.sls
/bin/hostname :
  cmd.run : []
</code></pre>

### Versions Report
**Master and Minion :**
<pre><code>
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 4.4.103-6.38-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
</code></pre>

**Comment by garethgreenaway** [comment]
@sundowner69 Thanks for the report.  Based on the output above, it appears that the state calling hostname is taking 15ms to run but something else is holding up the return.  Are you able to run the command with debugging enabled, `-l debug`, and provide that result?  Also run the Salt event runner, `salt-run state.event pretty=True`, and see if you can see the command running and returning to the Salt mater.  Thanks!

**Comment by sundowner69** [comment]
@garethgreenaway thanks for your fast reply. As requested please find the output below:

<pre><code>
master:~ # salt-run state.event pretty=True
20180620081343689497    {
    "_stamp": "2018-06-20T06:13:43.689959",
    "minions": [
        "minion"
    ]
}
salt/job/20180620081343689497/new       {
    "_stamp": "2018-06-20T06:13:43.690452",
    "arg": [
        "hostname"
    ],
    "fun": "state.apply",
    "jid": "20180620081343689497",
    "minions": [
        "minion"
    ],
    "tgt": "s175*",
    "tgt_type": "glob",
    "user": "root"
}
salt/job/20180620081343689497/ret/minion {
    "_stamp": "2018-06-20T06:14:08.506284",
    "cmd": "_return",
    "fun": "state.apply",
    "fun_args": [
        "hostname"
    ],
    "id": "minion",
    "jid": "20180620081343689497",
    "out": "highstate",
    "retcode": 0,
    "return": {
        "cmd_|-/bin/hostname_|-/bin/hostname_|-run": {
            "__id__": "/bin/hostname",
            "__run_num__": 0,
            "changes": {
                "pid": 22584,
                "retcode": 0,
                "stderr": "",
                "stdout": "minion"
            },
            "comment": "Command \"/bin/hostname\" run",
            "duration": 13.366,
            "name": "/bin/hostname",
            "result": true,
            "start_time": "08:14:07.739037"
        }
    },
    "success": true
}
</code></pre>

<pre><code>
master:~ # salt minion state.apply hostname
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/mars.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mars.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/ncc.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/ncc.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/suma.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/suma.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/mars.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/mars.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/ncc.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/ncc.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/suma.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/suma.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'master_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/f6/095b676f53a1f85e61b65aeed4cab7cd5e8dd356f3dfaa4f1cbc3f521b66f0/.minions.p
[DEBUG   ] get_iter_returns for jid 20180620081343689497 sent to set(['minion']) will timeout at 08:14:43.701135
[DEBUG   ] jid 20180620081343689497 return from minion
[DEBUG   ] LazyLoaded highstate.output
[DEBUG   ] LazyLoaded nested.output
[DEBUG   ] jid 20180620081343689497 found all minions set(['minion'])
minion:
----------
          ID: /bin/hostname
    Function: cmd.run
      Result: True
     Comment: Command "/bin/hostname" run
     Started: 08:14:07.739037
    Duration: 13.366 ms
     Changes:
              ----------
              pid:
                  22584
              retcode:
                  0
              stderr:
              stdout:
                  minion

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  13.366 ms

real    0m25.202s
user    0m0.516s
sys     0m0.065s
</code></pre>

**Comment by sundowner69** [comment]
Still a big problem...
