### ISSUE TITLE
Functions are not executing in the host

### ISSUE THREAD

**Issue by alok183** [saltstack/salt#48240]
### Description of Issue/Question
Below issue I am getting only on specific host.

Note: It was working before.

salt-ssh -i  vmaalind18  state.apply copydir
vmaalind18:
----------
          ID: copy_installation_files
    Function: file.recurse
        Name: /tmp/installation
      Result: False
     Comment: State 'file.recurse' was not found in SLS 'copydir'
              Reason: 'file.recurse' is not available.
     Changes:   

Summary for vmaalind18
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms

### Versions Report
salt-master 2018.3.0 (Oxygen)

**Comment by alok183** [comment]
I  am able to ping the host.
salt-ssh -i  vmaalind18  test.ping
vmaalind18:
    True

**Comment by garethgreenaway** [comment]
@alok183 thanks for the report.  can you provide the contents of the state file you're attempting to run?  Also some details about the machine you're attempting to run salt-ssh against?  What operating system and what version of Python is installed there?  Thanks!
