### ISSUE TITLE
How to find the conflicts in salt pillars for avoiding conflicts between different states used same config

### ISSUE THREAD

**Issue by sam0104** [saltstack/salt#48245]
### Description of Issue/Question
We are using salt states by different teams like OS , network , DB and Application. We have individual directories under /srv/salt and /srv/pillar . For few states different teams using configuration which are coming from different pillar to make the same changes on minions. Like changing /etc/hosts /etc/resolv.conf  where OS team modify some parameter but DB team execute another state and again change those configuration made by OS team. Which leads to outage and issues.

We have pillar coming from internal github where different team update their pillar files and we merge and built as a rpm package , which goes to install on Salt master. 

Is there any best practices or tool from Saltstack we can use to find the conflicts in states which are coming from pillar data ( example : hostname , IP address , OS config ) and resolve it before execution. This will help us to find any similar configurations changes which are going to be executed inside states.

Please advise.  

example  : /srv/salt/OS , /srv/salt/DB , /srv/salt/ APP and /srv/pillar/OS , /srv/pillar/DB , /srv/pillar/APP
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
General to Salt . We are using Salt open source version but  going for Salt Enterprise soon
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@saltstack/team-core Anyone have thoughts on this?

**Comment by gtmanfred** [comment]
I am not aware of one, but it may be useful to have trace level logs added to the master rendering pillar data for when data gets overwritten.

**Comment by sam0104** [comment]
Is it possible with Salt Enterprise ? We are evaluating Salt Enterprise. May be good idea to add some python based script or tool to Salt or Salt Enterprise , which will be really helpful for large scale environment where multiple teams have their own pillar and top file and creates conflict and change system configurations. We have seen outages due to change kernel parameter on a Linux or Database systems .

**Comment by sam0104** [comment]
any update on this .

**Comment by gtmanfred** [comment]
That is something that you will have to ask the enterprise team as you talk to them.  It is not something that i am aware of in enterprise, but i don't work with salt enterprise on a daily basis.

**Comment by rallytime** [comment]
@sam0104 Are you working with someone in sales? They should be able to help you out with that question regarding salt enterprise.

**Comment by sam0104** [comment]
It is more over generic question for Salt open source and Enterprise  Yes we are in touch with Salt sales team
