### ISSUE TITLE
cmd.script windows powershell fails in 2018.3.0

### ISSUE THREAD

**Issue by jyurdal** [saltstack/salt#48266]
### Description of Issue
Running cmd.script on windows salt-minion **2018.3.0** fails with error:

> Processing -File ''C:\Windows\TEMP\__salt.tmp.9feekqzq.ps1'' failed: The given path's format is not supported. Specify a valid path for the -File parameter

Applying this  state works on windows salt-minion 2017.7.1 

### file.sls
install_docker:
    cmd.script:
      - source: salt://win-setup-docker/files/install_docker.jinja.ps1
      - template: jinja
      - shell: powershell

###Salt versions
  Salt Version:
               Salt: 2018.3.0
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: 1.10.6
              gitdb: 2.0.3
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.18
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.3
            timelib: 0.2.4
            Tornado: 4.5.2
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.14393 SP0 Multiprocessor Free

**Comment by Ch3LL** [comment]
this should be fixed in 2018.3.1 by this: https://github.com/saltstack/salt/pull/45716 can you verify?

**Comment by jyurdal** [comment]
Yes it works in 2018.3.1
Thanks :)
