### ISSUE TITLE
Import file (json|yaml ...) from a pillar file does not work anymore

### ISSUE THREAD

**Issue by gcamus** [saltstack/salt#48263]
### Description of Issue/Question
I try to migrate from salt 2016.3.4  to Salt 2017.7.6 and I found that importing file from external git pillar file does not work anymore.

Thanks for your help.

### Setup
sls from git ext pillar
```
{#- vim: set ft=yaml ts=2 et ff=unix sw=2 ai sm: -#}
{%- import_yaml 'template/applications/versions.sls' as versions -%}
server-1:
  ServerName: {{grains['fqdn']|lower}}
  Version: {{versions._Versions['comp1']}}
```

template/applications/versions.sls file from pillar_roots, base, /tmp/salt/specific/pillar :
```
_Versions:
  comp1: 3.0.3-1
```

Extract from salt-master configuration :
```
fileserver_backend:
  - roots
  - git

pillar_roots:
  base:
    - /tmp/salt/specific/pillar

ext_pillar:
  - git: master ssh://git@xxxx:7999/saltdev/pillar.git
```

### Steps to Reproduce Issue
Just run a command to get pillar:
`salt 'xxxx' pillar.items`

```
2018-06-22 09:06:31,224 [salt.utils.templates                                  :463 ][DEBUG   ][30390] Exception: template/applications/versions.sls
2018-06-22 09:06:31,224 [salt.utils.templates                                  :464 ][DEBUG   ][30390] Out:
/home/appserv/salt/var/cache/salt/master/git_pillar/e5df9da198f6b642db5853aaad5880bd1ff0232ab9e4d8002f28967ba7aebb27/templates/apache/template.sls(3):
---
{#- vim: set ft=yaml ts=2 et ff=unix sw=2 ai sm: -#}
{%- import_yaml 'template/applications/versions.sls' as versions -%}    <======================
[...]
---
2018-06-22 09:06:31,224 [salt.utils.templates                                  :465 ][DEBUG   ][30390] Line: 0
2018-06-22 09:06:31,224 [salt.utils.templates                                  :466 ][DEBUG   ][30390] TmplStr:
2018-06-22 09:06:31,224 [salt.utils.templates                                  :467 ][DEBUG   ][30390] TraceStr: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/templates.py", line 425, in render_jinja_tmpl
    output = template.render(**decoded_context)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "<template>", line 24, in top-level template code
  File "/home/appserv/salt/var/cache/salt/master/git_pillar/e5df9da198f6b642db5853aaad5880bd1ff0232ab9e4d8002f28967ba7aebb27/templates/components.sls", line 3, in template
    {%- from 'templates/'~template~'/template.sls' import addComponent -%}
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1029, in module
    self._module = rv = self.make_module()
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1013, in make_module
    return TemplateModule(self, self.new_context(vars, shared, locals))
  File "/usr/lib/python2.7/site-packages/jinja2/environment.py", line 1070, in __init__
    self._body_stream = list(template.root_render_func(context))
  File "/home/appserv/salt/var/cache/salt/master/git_pillar/e5df9da198f6b642db5853aaad5880bd1ff0232ab9e4d8002f28967ba7aebb27/templates/apache/template.sls", line 3, in top-level template code
    {%- import_yaml 'template/applications/versions.sls' as versions -%}
  File "/usr/lib/python2.7/site-packages/salt/utils/jinja.py", line 138, in get_source
    raise TemplateNotFound(template)
**TemplateNotFound: template/applications/versions.sls**

```

### Versions Report
Salt Version:
           Salt: 2017.7.6

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Ch3LL** [comment]
can you clarify where the versions.sls file is set? as you state: `versions.sls file from a local directory` can you clarify if that is in your pillars, file_roots etc?

**Comment by gcamus** [comment]
From pillar_roots, I will update.

**Comment by gcamus** [comment]
@Ch3ll, Do you have enough details to unblock this issue ?

**Comment by Ch3LL** [comment]
hmmm i cant seem to get this to even work in 2016.3.4 to try to bisect this issue. Are there any other configurations you have set?

ping @terminalmage your more familiar with this area any ideas here?

**Comment by Ch3LL** [comment]
ya i'm not seeing anything that points out to having differed between our configurations that would cause this. if @terminalmage can take a look here since he is more familiar with this area.

**Comment by gcamus** [comment]
@terminalmage, @Ch3LL do you have any update on this topic ? I tested with 2019.2 and the issue is still there ? Or at least can you provide a lead to continue my investigation ?

**Comment by terminalmage** [comment]
I don't think it was ever possible for this to have worked in the past, based on how git_pillar works. It works by using the same `salt.pillar.Pillar` class used to compile pillar data from the `pillar_roots` configuration, but using the cloned git repos as the `pillar_roots` instead of the _actual_ `pillar_roots`. So, git_pillar knows nothing about the `pillar_roots` configuration (hence its inability to find the file), and as far as I know it never has.

**Comment by gcamus** [comment]
@terminalmage thanks for your quick response, but I assure you it was working.
I saw in a previous version that this line was removed :
```
# Fix self.opts['file_roots'] so that ext_pillars know the real
# location of file_roots. Issue 5951
ext_pillar_opts['file_roots'] = self.actual_file_roots
```
https://github.com/saltstack/salt/blob/64fd839377c4fd50ede65c8f5f3b22a954273c1c/salt/pillar/__init__.py#L303 

So to avoid my issue, your advice to import a template outside of git pillars is to use an absolute path ?

**Comment by terminalmage** [comment]
Not related. That line was removed in 58f5fde in October 2018. If it were the cause, you would not be experiencing this in 2017.7.6.

**Comment by terminalmage** [comment]
After some further looking, the jinja importer is being handled by the `SaltCacheLoader` class in salt/utils/jinja.py.

@Ch3LL, the `get_source()` func is looking through the dirs defined in the class' `searchpath` attribute, set in the dunder init to try to find the file to be imported.

**Comment by terminalmage** [comment]
The git_pillar external pillar works by making a copy of the master config, and then replacing `pillar_roots` with a dictionary mapping pillar environments to the paths to the local git clones that git_pillar has created. It then renders pillar data using the same code used to render pillar data from `pillar_roots`. This is why the searchpath doesn't contain the dirs from the `pillar_roots` in the master config file, and why the file can't be found.

I still don't see how it ever _would_ have worked, though. :man_shrugging:

Going back to earlier versions, the code that sets the searchpath has not been changed in a significant way between 2016.3.4 and 2017.7.6. There were the above-mentioned changes in October 2018 but they did not functionally change what dirs end up in the searchpath.

**Comment by gcamus** [comment]
I don't know why but in version 2016.3, opts['file_roots'] contained pillar_roots plus 'git_pillar_roots'
Extract from the logs :

> mbtest: ['/tmp/salt/specific/pillar', '/home/P1xs/salt/var/cache/salt/master/pillar_gitfs/5f2ac1c829c3bfa4abd4c3549d044b61']
> mbtest: /home/P1xs/salt/var/cache/salt/master
> Jinja search path: ['/tmp/salt/specific/pillar', '/home/P1xs/salt/var/cache/salt/master/pillar_gitfs/5f2ac1c829c3bfa4abd4c3549d044b61']

salt/utils/jinja.py"
```
 71         if self.opts['file_roots'] is self.opts['pillar_roots']:
 72             self.searchpath = opts['file_roots'][saltenv]
 73         else:
 74             self.searchpath = [path.join(opts['cachedir'], 'files', saltenv)]
 75         log.debug("mbtest: {0}".format(opts['file_roots'][saltenv]))
 76         log.debug("mbtest: {0}".format(opts['cachedir']))
 77         log.debug('Jinja search path: %s', self.searchpath)
```
2019.X logs:

> mbtest pillar_roots: {u'base': [u'/home/appserv/salt/var/cache/salt/master/git_pillar/907822a298312e5ac8a6479a0ff0a6147ea92266ed18c613cbc3c6b9ff8653f5']}
> mbtest file_roots: {u'base': [u'/tmp/salt/deliveries']}
> mbtest cachedir: /home/appserv/salt/var/cache/salt/master/files/base
> Jinja search path: [u'/home/appserv/salt/var/cache/salt/master/git_pillar/907822a298312e5ac8a6479a0ff0a6147ea92266ed18c613cbc3c6b9ff8653f5']

At this point why file_roots contains pillar_roots which it is not the same behaviour in 2019.X

**Comment by terminalmage** [comment]
I can't reproduce this on 2016.3.4:

```
2019-07-29 15:04:26,678 [salt.utils.jinja][DEBUG   ][1013] file_roots = {'base': ['/var/cache/salt/master/pillar_gitfs/6823463be10a19a05abd55f54ce279fe']}
```

> At this point why file_roots contains pillar_roots which it is not the same behaviour in 2019.X

This is explained in https://github.com/saltstack/salt/commit/58f5fde03c3903afd97d09ccb04e825bc145e045, which I mentioned a few days ago. Again, this change happened less than a year ago, so I'm not sure why you're focusing on it.

**Comment by gcamus** [comment]
I'm not focusing on this, I've wanted to add some logs where I know the search path is filled to show you the differences between the two versions.

Thanks you for your time i will try to change my of doing
