### ISSUE TITLE
Can not send commands to nxos proxy minion

### ISSUE THREAD

**Issue by nightcrow100** [saltstack/salt#48312]
I have installed two clean devices and this is what I did to try and get my nxos proxy up and running.

On minion:
Installed salt-minion
configured `/etc/salt/proxy` with the id of my master

On Master:
created `/src/pillar` directory
in `/src/pillar` i created `top.sls`:
```base:
nxos_proxy:
 - nxos_proxy```

then created `nxos_proxy.sls` in `/srv/pillar/`:
```proxy:
 proxytype: nxos
 host: <IP>
 username: <USER>
 password: <PASS>
 prompt_name: switch
 ssh_args: '-o PubkeyAuthentication=no'
 key_accept: True```

Next I restarted my master and ran my proxy-minion as follows:
`salt-proxy --proxyid='nxos_proxy' -l all`

I accepted the key on the master and the proxy minion starts to run and logs into the switch at which point its stops at the switchs prompt/command line.

I then moved to the master and ran:
`salt 'nxos_proxy' nxis,cmd sendline 'show ver'`

to which I received:

```nxos_proxy:
Minion did not return. [No Response]```

**Comment by gtmanfred** [comment]
make sure you set multiprocessing to False.

I would highly recommend using a different proxy minion module for nxos, because this one hasn't been touched in a while, and the napalm modules are a quite a bit better.

And nxos is supported by napalm.

http://napalm.readthedocs.io/en/latest/support/nxos.html

@mirceaulinic can you help with this? as while i wrote the nxos proxyminion, i have no access to those devices anymore.

Thanks,
Daniel

**Comment by gtmanfred** [comment]
Also, what does it say in the proxy minions log if you set `log_level: debug`?

**Comment by mirceaulinic** [comment]
Yes, please assign this issue to me Daniel and I will try to look at the
nxos modules this summer (didn't ever play with them, so it might be a good
opportunity).

**Comment by gtmanfred** [comment]
I am pretty sure they still work, though it isn't as documented, it just needs to make sure multiprocess is set to False, and again, we probably need logs from @nightcrow100 before we can know what is actually failing.

If this statement is true
```
On minion:
Installed salt-minion
configured /etc/salt/proxy with the id of my master
```

Then the multiprocess stuff is probably the problem.

**Comment by nightcrow100** [comment]
Apologies - as discussed with @mirceaulinic multiprocessing is set to False. Just forgot to include it here as part of my configuration.

@gtmanfred In terms on the `-l debug` it would just hang at:
`Terminal Command: /bin/sh -c ssh -l <USER> <SWITCH_IP>`

**Comment by gtmanfred** [comment]
Can you provide the entire debug log?

Thanks,
Daniel

**Comment by nightcrow100** [comment]
Unfortunately not.

That environment doesnt have access to the internet/outside.

Ill be happy to answer any questions though.

**Comment by mirceaulinic** [comment]
@nightcrow100 can you confirm if @cro's patch from https://github.com/saltstack/salt/pull/48378 fixes your issue as well?

**Comment by nightcrow100** [comment]
Nope - doesnt look like it.

Masters still reports:
_get_event() waited 0 seconds and received nothing. 
I have changed the timeout as well.
