### ISSUE TITLE
cmd.script, remote source goes into /tmp

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#48334]
Hi,

When using cmd.script with a remote source, the uploaded file goes to /tmp. So when having something like a self executable we saturate this folder.

Is there any way to switch to /var/tmp without predownloading the file to a specific location ?

Best regards

**Comment by Ch3LL** [comment]
you can specify `cwd=/var/tmp` and it will download and run the file from there.

**Comment by Poil** [comment]
Thanks
