### ISSUE TITLE
Feature request: Make salt-minion interact with desktop on Windows

### ISSUE THREAD

**Issue by kemadz** [saltstack/salt#4834]
The salt-minion windows service does not interact with desktop. So, when you start a program through salt-minion, you will never see the GUI window.

I tried to set the salt-minion service interacted with desktop by `sc config salt-minion type= own type= interact`. It worked. But the salt-minion displayed a console window on the desktop and this was a little annoying.

Is there a way to hide the console window?

**Comment by Slimmons** [comment]
Was this feature, or any way to run something like notepad in the UI for a windows minion implemented?

**Comment by marianomd** [comment]
Any plans to implement this? I need to launch a full screen app on a kiosk after updating it.

**Comment by kemadz** [comment]
@marianomd 

A Workaround.
- Create an `interactive` windows scheduled task manually. `You need to set the password of the running user manually`.
- Launch the task via `salt`.

**Comment by marianomd** [comment]
Thanks @kemadz I will give it a try.
