### ISSUE TITLE
Regression: salt-ssh ignoring pillar_merge_lists in master configuration in 2017.7.6

### ISSUE THREAD

**Issue by kivoli** [saltstack/salt#48357]
### Description of Issue/Question

When using `salt-ssh` with Salt 2017.7.6 (worked with 2017.7.5) the option `pillar_merge_lists: True` is ignored if it is set via the master configuration. This may be a symptom of a wider issue but that’s how we got bitten.

In contrast setting it via `minion_opts` in `/etc/salt/roster` does work.

### Setup

I used Vagrant with the libvirt provider to set up a test environment for anyone to reproduce.

Create `Vagrantfile`
```sh
cd $(mktemp -d) && cat >Vagrantfile <<EOF
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/stretch64"
  config.vm.provision :salt do |salt|
    # This sets the official Salt repositories up for us
    salt.install_master = true
    salt.install_type = 'stable'
    salt.install_args = '2017.7.6'
    salt.no_minion = true
  end
end
EOF
```

Commands
```sh
vagrant up
vagrant ssh
# Now continue in the vagrant box
ssh-add -L >>.ssh/authorized_keys
sudo -i
apt update && apt install salt-ssh vim
```

Files to be created inside the Vagrant box:
```sh
mkdir -p /srv/{salt,pillar}
cat >/etc/salt/roster <<EOF
dory:
  host: localhost
  user: vagrant
  sudo: True
  # Setting this option here works
  # minion_opts:
  #   pillar_merge_lists: True
EOF

cat >/etc/salt/master.d/vagrant.conf <<EOF
pillar_merge_lists: True
ssh_use_home_key: True
EOF

cat >/etc/sudoers.d/vagrant-ssh <<EOF
Defaults    env_keep+=SSH_AUTH_SOCK
EOF
exit
sudo -i

cat >/srv/pillar/top.sls <<EOF
base:
  '*':
    - nemo
    - shiny
EOF

cat >/srv/pillar/nemo.sls <<EOF
found:
  - nemo
EOF

cat >/srv/pillar/shiny.sls <<EOF
found:
  - shiny
EOF
```

### Steps to Reproduce Issue

Fire up the above Vagrant environment and play around with the option, i.e.
enable it in `/etc/roster`.

```sh
$> salt-ssh -i dory pillar.items
dory:
    ----------
    found:
        - shiny
$> vim /etc/salt/roster
[1]+  Stopped                 vim /etc/salt/roster
$> salt-ssh -i dory pillar.items
dory:
    ----------
    found:
        - nemo
        - shiny
```

### Versions Report

```
root@stretch:~% salt --versions-report
Salt Version:
           Salt: 2017.7.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.4
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4
```

PS: I did not further investigate this time but please also see my long-resolved issue #39685 for the last time this was an issue.

**Comment by rallytime** [comment]
@gtmanfred Can you take a look at this one?

**Comment by gtmanfred** [comment]
@terminalmage can you take a look at this with me?

It looks like this behavior was changed in b4a1d34b47a7d7931f31ad2dfbb53e870915d4f7

Thanks,
Daniel

**Comment by kivoli** [comment]
Unfortunately I just found out that 2018.3.2 is also affected. :-/

**Comment by gtmanfred** [comment]
Ok, I am hesitant to "fix" this.

Here is what happens when salt-ssh writes a config for the salt-ssh minion.  It takes the /etc/salt/master config file, and then it does a `.update()` with the DEFAULT_MINION_OPTS from `salt.config`, and then it applies the `minion_opts` from the roster.  Before 2017.7.6, there was no default for `pillar_merge_lists` in the default minion opts.  This was added in https://github.com/saltstack/salt/commit/b4a1d34b47a7d7931f31ad2dfbb53e870915d4f7 .

Now, we could just remove that default, but that just seems like the wrong way to do that, because it could be eventually overwritten again, and though we already set an inline default for that variable in cases that it is not set, that is not how we handle anything else in salt.

Also, we have a way to set these defaults for salt-ssh minions that does not require the master config file to be inherited to the minion.  you can set `roster_defaults`

So to get the same behavior as you had before, you can set the minion opts for all minion using a roster_defaults in /etc/salt/master to be applied at the end to all minions.

```
roster_defaults:
  minion_opts:
    pillar_merge_lists: True
```

@saltstack/team-core specifically @rallytime , do we still consider this a blocker/bug, knowing what the fix would entail and knowing that there is a more correct solution?

Thanks,
Daniel

**Comment by terminalmage** [comment]
I agree with @gtmanfred's solution. Maybe we should add some documentation [here](https://docs.saltstack.com/en/latest/topics/ssh/roster.html#target-defaults) to explain that `minion_opts` can be used to set default minion configuration for all ssh minions.

**Comment by rallytime** [comment]
Thank you for the thorough investigation and explanation @gtmanfred. I agree with you and @terminalmage here.

Some docs explaining the minion_opts would be ++.

I wouldn't consider this a blocker any more from my perspective.

@cachedout?

**Comment by kivoli** [comment]
@gtmanfred I was not aware of the possibility to use `roster_defaults` but we are actually using them for the already documented purposes. It would be nice if the documentation could be updated to reflect the full potential of them.

Regarding patching the documentation on [version numbers](https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html) speaks of “bugfix releases” which semantically sounds a lot like “patch level” from semver and in my opinion does not give the least hint that there will be breaking changes from one “bugfix release” to another. 

Changing this behaviour from 2017.7 to 2018.3 is totally o.k. on the other hand although I would prefer at least a warning in the changelog about it.

**Comment by gtmanfred** [comment]
Yes, it was an unintended feature, and it was a mistake to break it, but i don't feel like it would be worthwhile to "unbreak" it at this point.

But I will definitely keep this in mind in the future when i am reviewing PRs that make changes to the minions default options.

I can only offer my sincerest apologies that it caused you problems now.

**Comment by gtmanfred** [comment]
I will open a new issue about adding more documentation around roster_defaults.

**Comment by cachedout** [comment]
I am fine with this but I don't want people to hit this and then have to search around in the docs for the reason. If we're displaying warnings about what's happening that's fine but if it's going to do something unexpectedly and silently, I think that's a problem.
