### ISSUE TITLE
Permission mismatch when using salt-ssh while salt-master is running under user salt

### ISSUE THREAD

**Issue by brejoc** [saltstack/salt#48351]
### Description of Issue

If you are running SaltStack under a non-root user (e.g. `salt`), the job-cache in `/var/cache/salt/master/jobs` is created with the ownership `salt:salt`. If you are now running a job with `salt-ssh`, the job cache entry that is being created has the ownership `root:root`. Seems like `salt-ssh` is not dropping privileges.

Is this behaviour intended? Shouldn't `salt-ssh` also respect the settings from the master config and drop privileges?

### Setup

E.g. SaltStack on openSUSE or SLES with `salt` as user for `salt-master`.

### Steps to Reproduce Issue

1. Run salt-master with `user: salt` in config
2. `salt "*" test.ping`
3. Check job cache ownership in `/var/cache/salt/master/jobs`. Everything should be `salt:salt`
4. Setup a roster for `salt-ssh`
5. `salt-ssh 'sshtest1' test.ping`
6. Check job cache ownerships again. One of the jobs should have the ownership `root:root`.

### Versions Report

```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.73-5-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
```

**Comment by garethgreenaway** [comment]
@saltstack/team-core Thoughts?

**Comment by DmitryKuzmenko** [comment]
If I'm not wrong salt-ssh logs in as the user set in roster and works as that user doing nothing with privileges. So if you'd like to run it as `salt` user configure it to log in by ssh and set `user: salt` in the roster file.

**Comment by brejoc** [comment]
@DmitryKuzmenko This is not about the user that is used to login to the target minion. This is about the user that is use to run `salt-ssh` itself.

**Comment by gtmanfred** [comment]
I think it would be reasonable to do a setuid down to the `user` to run salt-ssh, which would require forking off a new process.

But we already have the stuff available to fork off the process, and then listen to the event bus for the job returns, just like with LocalClient.
