### ISSUE TITLE
Grain uuid missing on Linux host without dmidecode, although core.py should read it from file

### ISSUE THREAD

**Issue by elvinasp** [saltstack/salt#48350]
### Description of Issue/Question
When creating asset inventory states I have noticed, that CentOS 6 Linux host is missing "uuid" grain item. Further inspection and some search in salt issue lists suggested that missing _dmidecode_ might be the case and it seems this is true. However Salt grain core.py has a function _hw_data(), which supposed to read uuid value from sysfs file and this function seems to be initialized.

[_hw_data()](https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L2327)
Function seems to be called by os_data()
[ grains.update(_hw_data(grains))](https://github.com/saltstack/salt/blob/develop/salt/grains/core.py#L1941)

Questions:
1. Why uuid and other hardware data  grains are not available without dmidecode?
2. Can I somehow utilize core.py in my custom grain states/modules. For example to run that _hw_data() explicitly if I see UUID is missing. Some "hello world" example would not hurt... :) 

Thanks in advance

### Setup
Default setup with Centos 7 and Centos 6 minion hosts added.

### Steps to Reproduce Issue

Before installing dmidecode
```
root@TSM-215 ~]# salt CentOS6withMinion1  saltutil.sync_grains
CentOS6withMinion1:
[root@TSM-215 ~]# salt CentOS6withMinion1  grains.item uuid
CentOS6withMinion1:
    ----------
    uuid:
[root@TSM-215 ~]# salt CentOS6withMinion1  cmd.run 'cat /sys/class/dmi/id/product_uuid'
CentOS6withMinion1:
    421052B4-7675-B331-8AA9-743D37A3C0B8
[root@TSM-215 ~]# 
```
After dmidecode is installed on minion and salt-minion restarted.

```
[root@TSM-215 ~]# salt CentOS6withMinion1  saltutil.sync_grains
CentOS6withMinion1:
[root@TSM-215 ~]# salt CentOS6withMinion1  grains.item uuid
CentOS6withMinion1:
    ----------
    uuid:
        421052b4-7675-b331-8aa9-743d37a3c0b8
```

### Versions Report
[root@TSM-215 ~]# salt --versions-report
Salt Version:
           Salt: 2017.7.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.13.2.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by garethgreenaway** [comment]
@elvinasp Thanks for the report.  It seems like the UUID should be able to be grabbed without the need for dmidecode, the only question I would have is whether this is supported on other systems that don't have the `/sys` filesystem.

Here is a good explanation and example of writing a custom grain module that might be helpful for what you're trying to do.

**Comment by elvinasp** [comment]
Well regarding /sys filesystem, as far as I see in core.py file, this code block is explicitly limited to Linux systems. Somehow I suspect that the following statement becomes false and code falls back to dmidecode part:
`if osdata['kernel'] == 'Linux' and os.path.exists('/sys/class/dmi/id'):`

As path clearly exists and check returns true, the only suspect left is osdata dict, but I have no idea how to debug core.py.
