### ISSUE TITLE
Modify nxos proxy minion to support regular expression for prompts

### ISSUE THREAD

**Issue by cro** [saltstack/salt#48366]
### Description of Issue/Question

When using the nxos proxy minion to upgrade switch firmware, the switch will ask for confirmation before beginning the upgrade.  Currently the proxy minion looks for the switch CLI prompt to know if it can send the next command, and this prompt style is mostly hardcoded into `proxy/nxos.py`, and does not match the confirmation prompt.  As a result, firmware upgrades (or any command that subsequently requires confirmation) will timeout and fail.

Rather than hardcoding the prompt, the proxy option `prompt_name` should be changed to support a regular expression.  Then it would be possible to change it to something like

```
hostname.*#|\(y\/n\).*
```
which would match either

```
hostname#
```
(default nxos prompt, hostname replaced with the real hostname (obviously))

or

```
Complete firmware upgrade (y/n)?  [n]
```
which is the prompt before the switch will allow the upgrade.

**Comment by gtmanfred** [comment]
Seems reasonable.
