### ISSUE TITLE
Typo dependency on "dateutils" (SmartOS only?)

### ISSUE THREAD

**Issue by pganssle** [saltstack/salt#48374]
### Description of Issue/Question

It seems that you have [`dateutils`](https://github.com/saltstack/salt/blob/develop/setup.py#L1098) in your `setup.py`. That refers to [this package](https://pypi.org/project/dateutils/) which is almost certainly not what you wanted. I'm guessing you wanted [`python-dateutil`](https://pypi.org/project/python-dateutil/) and made a mistake about the package name. Since `dateutils` depends on `python-dateutil`, you probably didn't notice the mistake.

**Comment by gtmanfred** [comment]
@sjorge can you take a look at this?

Thanks,
Daniel

**Comment by sjorge** [comment]
Yeah that should probably be python-dateutil.

**Comment by MTecknology** [comment]
@sjorge Should this issue be closed?

**Comment by sjorge** [comment]
Yes, this can be closed
