### ISSUE TITLE
SIGTERM -- Return error when salt-minion service/process receives a SIGTERM -- Feature Request

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#48390]
### Description of Issue/Question

Currently, when salt-minion service/process receives a SIGTERM, it just exits. 
It leaves all the running jobs in orphan state. 

**Feature-Request**: Please return some kind of errors for those jobs before stopping the minion.

**Comment by rickh563** [comment]
ZD-2652

**Comment by markuskramerIgitt** [comment]
Good point.

**Comment by KChandrashekhar** [comment]
Adding Gareth's question and response from user 
so when you send the TERM signal, do you still expect the minion to stop?  And those running jobs should also stop?  Or should continue running?  Or it should say an error message that there are or might be jobs still running?

Response from user: 
When we init a TERM signal, we know there could be running jobs, but we choose to send the TERM signal. So in that case, we prefer to STOP all those running jobs with some trace in log about TERM signal, and then stop the minion. Maybe a small sleep is needed in case those running jobs could not be stopped.

**Comment by jsbalrog** [comment]
I created an integration test that sends a `salt minion --async test.sleep 30` command and then immediately after sends a `salt minion kill` command. I get the following output from the `kill` command:

`'Exiting gracefully on Ctrl-c', "This job's jid is: 20191011102452738530", 'The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:', '', 'salt-run jobs.lookup_jid 20191011102452738530']`

Is this a request for something more than this? Do I understand this correctly? Or is this working as designed?

**Comment by sagetherage** [comment]
@Akm0d is still in progress?

**Comment by DmitryKuzmenko** [comment]
@rickh563 I've consolidated the termination behavior, PR #56723 makes minion to terminate the child processes so it behaves in the same way as if you terminate it with `Ctrl-C` in the command line.
Now I have a question: is it enough to resolve this issue? Or this is more about reporting the job failure to master before terminate the minion?

**Comment by sagetherage** [comment]
@doesitblend @whytewolf @oeuftete can one of you also take a peek at PR https://github.com/saltstack/salt/pull/56723?

**Comment by DmitryKuzmenko** [comment]
Here are some results from my investigation.

The original issue was reported against v2017.7.2 where minion main process worked as described receiving SIGTERM.

This commit 9f1fe42b3cca0809616e2782a13b8bbf4dd4e3c9 from #54259 changed this behavior so the main process doesn't exit untill all the workers terminated. All the jobs results are reported to master as well.

Meanwhile the `salt` command still reporting `Minion did not return. [No response]` in the case minion is terminated in the middle of a state execution.

This behavior was changed in commit 1c08709464078975d332d76148576b471051d207 from #56793. Now `salt` if there's no return prints the `salt-run` command that could be used for the job results lookup.

So all we need is to add a way to force terminate workers.

**Comment by sagetherage** [comment]
Discussed in Grooming 2021-MAY-24 - considering closing the PR and may want to write a new issue here. I need to follow up and will review, again in following weeks.

**Comment by whytewolf** [comment]
given the history of this ticket I'm going to close it. if someone has this issue and wishes it to progress please open a new ticket. and if possible a PR to fix it.
