### ISSUE TITLE
Contribution Documentation Refers to Incorrect Pylintrc

### ISSUE THREAD

**Issue by samilaine** [saltstack/salt#48417]
### Description of Issue/Question

The documentation section "[Contributing](https://docs.saltstack.com/en/latest/topics/development/contributing.html#salt-coding-style)" and "[Salt Coding Style](https://docs.saltstack.com/en/latest/topics/development/conventions/style.html#linting)" claims that: 

> SaltStack recommends running the .pylintrc file on any files you are changing with your code contribution before submitting a pull request to Salt's repository. 
> Most Salt style conventions are codified in Salt's .pylintrc file.
> The .pylintrc file is found in the root of the Salt project[.]

However, In PR #48373 it has been revealed that:

> We use .testing.pylintrc for our pylint tests[.]

The documentation should include information about:

1. In which situations it's recommended to use `.pylintrc`? Always, when pushing to any other branch except "development"?
2. In which situations one should be using `.pylintrc.testing`? Only when pushing to the branch "development"?

**Comment by rallytime** [comment]
@samilaine I have updated the docs in PR #48795. How does that look to you?
