### ISSUE TITLE
macOS service.running failing due unavailable service after recent creation.

### ISSUE THREAD

**Issue by weswhet** [saltstack/salt#48414]
### Description of Issue/Question

On macOS if you run `service.running` for `foo` near the beginning of a highstate and then later another state creates a service `bar` with `file.managed` and you try to start with `service.running`, `bar` will fail to start because salt thinks the service doesn't exist. I believe I tracked the issue to here https://github.com/saltstack/salt/blob/develop/salt/utils/mac_utils.py#L379 where all the services are cached on the first call. On any subsequent calls, it just uses the cache that doesn't include the recently created service. 

I'm creating this issue for tracking purposes and visibility. I chatted with @terminalmage and @gtmanfred on slack about a fix for this. The partial conversation below.

```
terminalmage [1:31 PM]
we should be using `__context__` there

@wes we just need to make sure that we properly clear it
when there are things that change available services
see the `pkg` modules for examples
aptpkg, yumpkg, etc. (edited)
usually just done with a `__context__.pop()`
```

I'm going to attempt a PR myself but if someone beats me to it I wouldn't complain. :)

**Comment by terminalmage** [comment]
@weswhet I'm going to close this since your PR was merged a couple weeks ago. Thanks!
