### ISSUE TITLE
Salt master gives TypeError when parsing TCP response

### ISSUE THREAD

**Issue by Cull-Methi** [saltstack/salt#48411]
### Description of Issue/Question
Using TCP networking on 2018.3.1/salt-unity/pex, I occasionally get the following error on the salt-syndic-master (master on the same server as the syndic):

```
2018-07-02 19:04:47,561 [salt.transport.tcp:1296][ERROR   ][10268] Exception parsing response
Traceback (most recent call last):
  File "/root/.pex/install/salt-2018.3.1_1_ge1035a6-py3-none-any.whl.1121c685594156d9569db3f436db1abad3b5bae4/salt-2018.3.1_1_ge1035a6-py3-none-any.whl/salt/transport/tcp.py", line 1277, in _stream_read
    body = framed_msg['body']
TypeError: 'int' object is not subscriptable
```

As far as I can tell these events are not triggered by anything being done by me, there are no corresponding messages in the syndic log, and no salt commands are being sent off

### Setup
Top level salt master --> Salt syndic == salt syndic master --> Salt minions

Using a pex executable built off of the 2018.3.1 tag with https://github.com/saltstack/salt/pull/48308 `git cherrypick`ed in

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2018.3.1-1-ge1035a6
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: unknown
       dateutil: 2.2
      docker-py: 1.2.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.3 (default, Nov 28 2017, 16:41:13)
   python-gnupg: Not Installed
         PyYAML: 4.1
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-112-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

No differences in versions - all of them are using the same binary. Built with ` pex . tornado==4.5.1 cffi==0.8.6 cherrypy==8.1.3  docker-py==1.2.2 jinja2==2.9.4 mako==1.0.0  pycparser==2.10 python-dateutil==2.2 -c salt-unity -o dist/salt.pex`

syndic-master and syndic-minion config:

```
transport: tcp
tcp_authentication_retries: -1
tcp_keepalive_idle: 300
tcp_keepalive_cnt: 9
tcp_keepalive_intvl: 30
return_retry_timer: 5
return_retry_timer_max: 30
recon_max: 149000
random_reauth_delay: 150
```

**Comment by nshalman** [comment]
@Cull-Methi, heads-up that #48308 has been refactored (and depending on feedback might get altered further before landing...)

**Comment by Ch3LL** [comment]
@Cull-Methi how often are you seeing this error?

ping @saltstack/team-transport any ideas here?

**Comment by Cull-Methi** [comment]
Hi Ch3ll, I'm out of office until Monday but I'll follow up with you then. Thanks!

**Comment by Cull-Methi** [comment]
Hi @Ch3LL , it's coming in anywhere from 1-10 messages per minute it looks like. There are approx 1550 minions attached to this master

**Comment by DmitryKuzmenko** [comment]
Again looks like the issue related to forking with running event loop and bound port. https://github.com/saltstack/salt-jenkins/issues/995

**Comment by DmitryKuzmenko** [comment]
Or not... I've checked master code already it looks good from that viewpoint but this issue is about syndic that runs a minion part too. I'll check this later.

**Comment by Cull-Methi** [comment]
It is worth noting that we moved these servers to Debian Jessie (instead of ubuntu trusty) using the same executable and I've only seen 65 hits for this in the past 24 hours

**Comment by MacgradyHuang** [comment]
i get a same problem, but i found it is caused by python package.

**Comment by nshalman** [comment]
> i get a same problem, but finally i found it is caused by python package.
@MacgradyHuang could you elaborate?
