### ISSUE TITLE
Minion Install (Win x64) Command Line Switches -- Feature-Request

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#48424]
### Feature-Request

When running the Minion installer for Windows -- Request that an option be added that makes it possible to use the CLI to input the key of the Master or Syndic
when running the Minion installer for Windows, augmenting the existing options:

* https://docs.saltstack.com/en/latest/topics/installation/windows.html#silent-installer-options

**Comment by rickh563** [comment]
ZD-2641

**Comment by markuskramerIgitt** [comment]
@rickh563,  you mean the public key of the master?

**Comment by whytewolf** [comment]
yes, public master key.

**Comment by twangboy** [comment]
This is how I intend to implement this:
Pass the following switch
```
/master-key=C:\path\to\master.pub
```
which would then be placed in `c:\salt\conf\pki\minion\minion_master.pub`

@whytewolf Does this sound like the solution you're looking for?

**Comment by whytewolf** [comment]
@twangboy That seems like a reasonable method. Works for me.

**Comment by KChandrashekhar** [comment]
Closing this as the associated ZD as been closed by BB
