### ISSUE TITLE
TypeError: can't serialize <azure.mgmt.compute.v2017_03_30.models.sub_resource.SubResource object at 0x7fc20779ead0>

### ISSUE THREAD

**Issue by diepes** [saltstack/salt#48438]
### Description of Issue/Question
salt-cloud, failing on Azure.
It creates the VM, but fails before the bootstrap

Found a closed bug with the same type of error: **https://github.com/saltstack/salt/issues/47096**
And a open one **https://github.com/saltstack/salt/issues/45884**
Is there instruction on how to run salt-cloud from a git clone ?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
salt-master as azure VM with az tools installed.
driver: azurearm

#/etc/salt/cloud/cloud.profile.d/inf.conf
```
azure_vm_INF_UBUNTU14_CPU4_RAM8_HDD16:
  provider: azurearm
  image: Canonical|UbuntuServer|14.04.5-LTS|14.04.201806270
  size: Standard_DS2_v2
  location: australiaeast
  ssh_username: admin
  ssh_password: abcdefg
  #storage_resource_group: xxx
  storage_resource_group: INF
  storage_account: inf01xxx
  storage_key: xxxxx...xxxx==
  resource_group: INF
  #security_group: $nsgname
  network_resource_group: VNET
  network: VNET-INF
  subnet: INF
  public_ip: False
  availability_set: INF
```

/etc/salt/cloud.maps.d/inf.conf
```
azure_vm_INF_UBUNTU14_CPU4_RAM8_HDD16:
  - INF01:
      minion:
        master: 10.x.y.z
        tcp_keepalive: True
        tcp_keepalive_idle: 180
        mysql.default_file: '/etc/mysql/debian.cnf'
      grains:
        environment: INF01
        role:
          - microservices
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```
# az vm delete --resource-group INF  --name INF01
# /usr/bin/salt-cloud -l info -m /etc/salt/cloud.maps.d/INF.conf
```
...
...
```
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[ERROR   ] There was a query error: can't serialize <azure.mgmt.compute.v2017_03_30.models.sub_resource.SubResource object at 0x7fc20779ead0>
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/cloud/cli.py", line 343, in run
    ret = mapper.run_map(dmap)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 2237, in run_map
    profile, local_master=local_master
  File "/usr/lib/python2.7/dist-packages/salt/cloud/__init__.py", line 1284, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/dist-packages/salt/cloud/clouds/azurearm.py", line 1308, in create
    ret = __utils__['cloud.bootstrap'](vm_, __opts__)
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 553, in bootstrap
    transport=opts.get('transport', 'zeromq')
  File "/usr/lib/python2.7/dist-packages/salt/utils/cloud.py", line 1786, in fire_event
    event.fire_event(args, tag)
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 725, in fire_event
    dump_data = self.serial.dumps(data)
  File "/usr/lib/python2.7/dist-packages/salt/payload.py", line 217, in dumps
    return msgpack.dumps(msg, default=ext_type_encoder, use_bin_type=use_bin_type)
  File "/usr/lib/python2.7/dist-packages/msgpack/__init__.py", line 47, in packb
    return Packer(**kwargs).pack(o)
  File "msgpack/_packer.pyx", line 284, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 290, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 287, in msgpack._packer.Packer.pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 234, in msgpack._packer.Packer._pack
  File "msgpack/_packer.pyx", line 281, in msgpack._packer.Packer._pack
TypeError: can't serialize <azure.mgmt.compute.v2017_03_30.models.sub_resource.SubResource object at 0x7fc20779ead0>

```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
# salt-cloud --version
salt-cloud 2018.3.2 (Oxygen)
# salt --versions-report
Salt Version:
           Salt: 2018.3.2
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.3 
      docker-py: 1.10.6
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1013-azure
         system: Linux
        version: Ubuntu 18.04 bionic
root@SLT01:~#
```

**Comment by Ch3LL** [comment]
ping @nicholasmhughes any ideas here? im guessing your fix here https://github.com/saltstack/salt/pull/47774 isn't what we are looking for since the typerror message isn't related to disks

**Comment by nicholasmhughes** [comment]
@diepes any change you can test with the code from the `develop` branch? It has a lot of functionality additions as well as some fixes that didn't make it into stable versions. Let me know if that's possible.

Also, please post you Azure SDK versions (`pip freeze | egrep '(msrest|azure)'`) in case I need to dig into the error with a similar environment.

**Comment by diepes** [comment]
Here is the pip versions from our azure salt master.
`# pip freeze | egrep '(msrest|azure)'
azure==3.0.0
azure-batch==4.1.3
azure-cli==2.0.38
azure-cli-acr==2.0.27
azure-cli-acs==2.1.1
azure-cli-advisor==0.5.1
azure-cli-ams==0.1.1
azure-cli-appservice==0.1.35
azure-cli-backup==1.1.1
azure-cli-batch==3.2.4
azure-cli-batchai==0.3.0
azure-cli-billing==0.1.8
azure-cli-cdn==0.0.14
azure-cli-cloud==2.0.14
azure-cli-cognitiveservices==0.1.13
azure-cli-command-modules-nspkg==2.0.1
azure-cli-configure==2.0.16
azure-cli-consumption==0.3.1
azure-cli-container==0.1.24
azure-cli-core==2.0.38
azure-cli-cosmosdb==0.1.21
azure-cli-dla==0.1.0
azure-cli-dls==0.0.22
azure-cli-dms==0.0.1
azure-cli-eventgrid==0.1.12
azure-cli-eventhubs==0.1.3
azure-cli-extension==0.0.15
azure-cli-feedback==2.1.2
azure-cli-find==0.2.10
azure-cli-interactive==0.3.23
azure-cli-iot==0.1.21
azure-cli-keyvault==2.0.22
azure-cli-lab==0.0.22
azure-cli-monitor==0.1.7
azure-cli-network==2.1.4
azure-cli-nspkg==3.0.2
azure-cli-profile==2.0.26
azure-cli-rdbms==0.2.4
azure-cli-redis==0.2.13
azure-cli-reservations==0.2.0
azure-cli-resource==2.0.31
azure-cli-role==2.0.26
azure-cli-servicebus==0.1.2
azure-cli-servicefabric==0.0.12
azure-cli-sql==2.0.27
azure-cli-storage==2.0.35
azure-cli-vm==2.0.34
azure-common==1.1.13
azure-cosmosdb-nspkg==2.0.2
azure-cosmosdb-table==1.0.4
azure-datalake-store==0.0.22
azure-eventgrid==0.1.0
azure-graphrbac==0.40.0
azure-keyvault==0.3.7
azure-mgmt==2.0.0
azure-mgmt-advisor==1.0.1
azure-mgmt-applicationinsights==0.1.1
azure-mgmt-authorization==0.30.0
azure-mgmt-batch==5.0.1
azure-mgmt-batchai==0.2.0
azure-mgmt-billing==0.1.0
azure-mgmt-cdn==2.0.0
azure-mgmt-cognitiveservices==2.0.0
azure-mgmt-commerce==1.0.1
azure-mgmt-compute==3.0.1
azure-mgmt-consumption==2.0.0
azure-mgmt-containerinstance==0.3.1
azure-mgmt-containerregistry==1.0.1
azure-mgmt-containerservice==3.0.1
azure-mgmt-cosmosdb==0.3.1
azure-mgmt-datafactory==0.4.0
azure-mgmt-datalake-analytics==0.3.0
azure-mgmt-datalake-nspkg==2.0.0
azure-mgmt-datalake-store==0.3.0
azure-mgmt-datamigration==0.1.0
azure-mgmt-devtestlabs==2.2.0
azure-mgmt-dns==1.2.0
azure-mgmt-eventgrid==0.4.0
azure-mgmt-eventhub==1.2.0
azure-mgmt-hanaonazure==0.1.1
azure-mgmt-iothub==0.4.0
azure-mgmt-iothubprovisioningservices==0.1.0
azure-mgmt-keyvault==0.40.0
azure-mgmt-loganalytics==0.1.0
azure-mgmt-logic==2.1.0
azure-mgmt-machinelearningcompute==0.4.1
azure-mgmt-managementgroups==0.1.0
azure-mgmt-managementpartner==0.1.0
azure-mgmt-marketplaceordering==0.1.0
azure-mgmt-media==0.2.0
azure-mgmt-monitor==0.4.0
azure-mgmt-msi==0.1.0
azure-mgmt-network==1.7.1
azure-mgmt-notificationhubs==1.0.0
azure-mgmt-nspkg==2.0.0
azure-mgmt-powerbiembedded==1.0.0
azure-mgmt-rdbms==0.1.0
azure-mgmt-recoveryservices==0.2.0
azure-mgmt-recoveryservicesbackup==0.1.1
azure-mgmt-redis==5.0.0
azure-mgmt-relay==0.1.0
azure-mgmt-reservations==0.1.0
azure-mgmt-resource==1.2.2
azure-mgmt-scheduler==1.1.3
azure-mgmt-search==1.0.0
azure-mgmt-servermanager==1.2.0
azure-mgmt-servicebus==0.4.0
azure-mgmt-servicefabric==0.1.0
azure-mgmt-sql==0.8.6
azure-mgmt-storage==1.5.0
azure-mgmt-subscription==0.1.0
azure-mgmt-trafficmanager==0.40.0
azure-mgmt-web==0.34.1
azure-multiapi-storage==0.2.0
azure-nspkg==2.0.0
azure-servicebus==0.21.1
azure-servicefabric==6.1.2.9
azure-servicemanagement-legacy==0.20.6
azure-storage==0.36.0
azure-storage-blob==1.3.0
azure-storage-common==1.3.0
azure-storage-file==1.3.0
azure-storage-nspkg==3.0.0
azure-storage-queue==1.3.0
msrest==0.5.1
msrestazure==0.4.34
root@SLT01:~#`

**Comment by nicholasmhughes** [comment]
@diepes it looks like it's crashing due to the specification of an availability set as a `SubResource` object which gets passed to the `cloud.bootstrap` utility. As a quick test, it'll probably work (or get farther) if you remove it from the profile.

For you reference, that [parameter expects the full ID path](https://github.com/saltstack/salt/blob/2018.3.2/salt/cloud/clouds/azurearm.py#L1029) of the availability set in `2018.3.2`... so once/if this is working, you'll need to make sure the parameter is in "`/subscriptions/<UUID>/resourceGroups/<rg name>/providers/Microsoft.Compute/availabilitySets/<avail set name>`" format. To further confuse things, the `develop` code doesn't require the full ID path... so your profile would work as-is using that code. Actually, the `develop` code doesn't create the `SubResource` object at all... so you might want to check out `develop` and see if it solves all of your problems.

@Ch3LL whatever updates have occurred to the `cloud.bootstrap` utility have caused it to barf on any Azure objects created to build an instance. The Azure SDK will accept dictionaries to pass to the API, but we lose the object validation prior to making that remote call. Other possible avenues include keeping a separate "dictionary only" VM definition from the object that is passed to the API just so we can pass the dictionary to the bootstrap, or modifying the bootstrap to pop out "unknown" objects before firing the event (which is probably less desirable). Any thoughts?

**Comment by diepes** [comment]
Thanks @nicholasmhughes , 
removing the "availability_set: INF" from /etc/salt/cloud/cloud.profile.d/inf.conf allowed it to proceed.
Yay! :1st_place_medal: 

Are there instructions on how to run salt-cloud from the development branch?
  -  git clone,  -> virtualenv ?

**Comment by nicholasmhughes** [comment]
Glad that worked for you.

Are you looking for something like [this documentation](https://docs.saltstack.com/en/latest/topics/development/hacking.html)?

**Comment by diepes** [comment]
Thanks again. I will try the deployment with the "availability_set" on the development branch and log a new issue if there is still a problem.
