### ISSUE TITLE
How to use match: grain on subelement of the grain ?

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#48452]
Hi

I have a "structured" grain like this :

```
    os_custom:
        ----------
        type:
            custom1
        version:
            20181202
```

I would like to use "match: grain" in the top-formula or in pillar, but I'm unable to find the right way, is it possible to do this without doing a Jinja hack like this one ?

```
{% if grains['os_custom'] | default (None) and grains['os_custom']['type'] | default (None) == 'custom1' %}
```

What I've tried :

```
  'os_custom["type"]:custom1':
    - match: grain

  'os_custom[type]:custom1':
    - match: grain

  'os_custom.type:custom1':
    - match: grain
```

Best regards,

**Comment by Ch3LL** [comment]
```
'os_custom:type:custom1':
  - match: grain
```

does that work?

**Comment by Poil** [comment]
It works !

Perhaps it should be a good idea to add this to this documentation  https://docs.saltstack.com/en/latest/topics/grains/
