### ISSUE TITLE
support for RunOnce commands in the salt-cloud vmware driver

### ISSUE THREAD

**Issue by cvedel** [saltstack/salt#48455]
VMware guest customization lets you [run commands on the first login to a Windows machine](https://www.vmware.com/support/developer/vc-sdk/visdk25pubs/ReferenceGuide/vim.vm.customization.GuiRunOnce.html). It would be useful to support this in the driver. 
Our specific use case is setting the certificate for WinRM which needs to be done after the host name is set but cannot be done later on because an incorrect certificate prevent the deployment of the minion through WinRM.

**Comment by garethgreenaway** [comment]
Thanks for the report and the PR!
