### ISSUE TITLE
Windows installer 2017.7.7 missing libnacl

### ISSUE THREAD

**Issue by mbochenk** [saltstack/salt#48459]
### Description of Issue/Question
Same as https://github.com/saltstack/salt/issues/45178 but for 2017.7.7 
Seems to have been reverted by commit: https://github.com/saltstack/salt/pull/46990/commits/b9efec8526f323bdc27350104a8be973752221a4

Not sure why removed. My understanding is that libnacl is required for nacl.dec/enc (sealedbox/secretbox) and it was previously present in windows installer. 

Is there a different way this should be handled on windows? Doing pip install on windows is not the most convenient thing to do, so prepackaged with installer would be nice to get back.

### Setup
Same as https://github.com/saltstack/salt/issues/45178 but for 2017.7.7 

### Steps to Reproduce Issue
Same as https://github.com/saltstack/salt/issues/45178 but for 2017.7.7

**Comment by mbochenk** [comment]
`libsodium.dll` is also missing, seems also due to dependencies cleanup. Had to figure out that 120 (I assume this is msvcrt version? not really into windows) has to be used.

**Comment by garethgreenaway** [comment]
@dmurphy18 @dwoz Any insight here?

**Comment by mbochenk** [comment]
https://github.com/saltstack/salt/pull/48476

**Comment by mbochenk** [comment]
@garethgreenaway seems this is already fixed in 2017.7 source (not in 2018.3 to my understanding): https://github.com/saltstack/salt/pull/48476
