### ISSUE TITLE
Symantec Endpoint Protection (SEP) quarantines Salt-Minion-*-Setup.exe

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#48468]
Could you let Symantec white list the installers?

SEP says:

There is strong evidence that this file is untrustworthy.
This file has been seen by hundreds of Symantec users.
Symantec has known about this file approximately 2 weeks.
Hash:  A949870AD4670CA7900091339D3C63EFF3DBD7AE3EA5B09EBD90B97105EC1891

![SEP](https://user-images.githubusercontent.com/8489107/42390792-6ba150e4-814d-11e8-9226-23f9956d1831.PNG)

**Comment by dwoz** [comment]
I have submitted the file to Symantec's false positive reporting.

https://submit.symantec.com/false_positive/

**Comment by dwoz** [comment]
In relation to submission 98240.

Upon further analysis and investigation we have verified your submission and, as such, the detection(s) for the following file(s) will be removed from our products:

    File name: Salt-Minion-2018.3.2-Py2-AMD64-Setup.exe
    MD5: 0EB9170A38DF0BE582A33969D9673A98
    SHA256: A949870AD4670CA7900091339D3C63EFF3DBD7AE3EA5B09EBD90B97105EC1891
    Note: Whitelisting may take up to 24 hours to take effect via Live Update


@markuskramerIg are you able to verify that this is no longer reporting a threat?

**Comment by markuskramerIgitt** [comment]
@dwoz, yes. 
I will wait one day to increase probability that the whitelisting arrived.

**Comment by markuskramerIgitt** [comment]
SEP no longer reports a threat.
I just downloaded the installer from another client.

**Comment by markuskramerIgitt** [comment]
Same story for     Salt-Minion-2018.3.2-Py3-AMD64-Setup.exe

My guess is that Symantec can detect "ingredients" of the Salt-Minion and rules it must be malware.

You could whitelist all installers, or discuss this with Symantec.

**Comment by markuskramerIgitt** [comment]
May be related

I installed 32bit 2018.3.2, executed `\salt\bin\python.exe`   and got

```
---------------------------
python.exe - System Error
---------------------------
The program can't start because python27.dll is missing from your computer. Try reinstalling the program to fix this problem. 
---------------------------
OK   
---------------------------
```

**Comment by markuskramerIgitt** [comment]
SEP currently does not quarantine exe and msi installers and a lot of dll's.
