### ISSUE TITLE
Logging/auditing - Is there any possibility to use syslog as default returner for the minions?

### ISSUE THREAD

**Issue by jangithub80** [saltstack/salt#48460]
Hi,

I have the task to create a kind of audit logging for our saltstack environment.
The aim is to log the salt commands with all options and all targets. 
Perfect would be if i can see which minions have reacted.

I found out that the salt option "--returner syslog" works fine for me, but I have the problem that these option must be added at each salt command.

Is there any possibility to set syslog as default returner to prevent that someone misses this addition?

I've tried already to use the logging of salt but this works only at "debug" level fine for me...but in a big environment this would be too much logging.

Do anyone have an idea?

**Comment by garethgreenaway** [comment]
@jangithub80 Sounds like you want the default returner configuration option for the Salt master:
https://docs.saltstack.com/en/latest/ref/configuration/master.html#event-return
