### ISSUE TITLE
[QUESTION/SECURITY PROBLEM] Does user that owns portus@portus.com owns your on premise registry ?

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#48475]
### Setup
NA

### Steps to Reproduce Issue
NA

### Versions Report
NA

If someone gains or has access to ``portus@portus.com`` inbox, he can then reset any portus registry with default setup for the portus hidden user.
I think this is a major security flaw and that user should have at least a non routable DEFAULT mail or no mail at all, and maybe additionally some code inside the app that for``id=1`` doesnt allow mail reset without an explicit config setting.

**Comment by garethgreenaway** [comment]
This seems like perhaps it was filed against the wrong project.  Closing.  Reopen if it is related.

**Comment by kiorky** [comment]
IT IS RELATED !!!!

**Comment by kiorky** [comment]
Arf, browser problem , sorry  for the noise !
