### ISSUE TITLE
salt.beacons.inotify python-pyinotify dependency installation failure

### ISSUE THREAD

**Issue by indigoarc** [saltstack/salt#48479]
### Description of Issue/Question
I want to use salt beacons module which depends on python-pyinotify.
Internet connection is turned off. Saltstack repository is hosted internally.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
install_python:
  pkg.installed:
    - name: python27-pip

install_inotify:
  pip.installed:
    - name: pyinotify
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

----------
          ID: install_python
    Function: pkg.installed
        Name: python27-pip
      Result: True
     Comment: The following packages were installed/updated: python27-pip
     Started: 18:56:16.595178
    Duration: 12484.12 ms
     Changes:   
              ----------
              python27-pip:
                  ----------
                  new:
                      9.0.1-2.ius.el6
                  old:
              python27-setuptools:
                  ----------
                  new:
                      36.6.0-1.ius.el6
                  old:
----------
          ID: install_inotify
    Function: pip.installed
        Name: pyinotify
      Result: False
     Comment: Failed to install packages: pyinotify. Error: Collecting pyinotify   Retrying (Retry(total=4, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7efe25cb0d50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyinotify/
                Retrying (Retry(total=3, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7efe25cb0ed0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyinotify/
                Retrying (Retry(total=2, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7efe25cb0410>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyinotify/
                Retrying (Retry(total=1, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7efe25cb0610>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyinotify/
                Retrying (Retry(total=0, connect=None, read=None, redirect=None)) after connection broken by 'NewConnectionError('<pip._vendor.requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x7efe26d7add0>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/pyinotify/
                Could not find a version that satisfies the requirement pyinotify (from versions: )
              No matching distribution found for pyinotify
     Started: 18:56:31.188033
    Duration: 85914.213 ms
     Changes:   

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.28.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by gtmanfred** [comment]
Do The following

```
install_python:
  pkg.installed:
    - name: python27-pip
    - reload_modules: True

install_inotify:
  pip.installed:
    - name: pyinotify
    - bin_env: /usr/bin/python2.7
```

So that it uses the python2.7 environment, instead of the default pip which is for python2.6.
