### ISSUE TITLE
Minion Timeout on Long States Even when Still Running Properly

### ISSUE THREAD

**Issue by doc987** [saltstack/salt#48470]
**Expected**: If a minion is running the tasks without issue, then that minion should report that everything is okay immediately upon request.

**Observed**: When on the master, and running ```state.apply```, there can be timeout issues, even when the minion(s) are still alive and running the tasks as expected.  It seems that a minion will reply to a master when between states, but not during a state.  In other words, if all of the states take a short period of time, then there is  unlikely to be a timeout, but if any one of the states takes too long, then there will be a timeout.

**Current Option**: The only way to prevent a timeout seems to be to set a timeout setting on the master that is longer than the time it would take any individual state to run on any machine.  Issues with this include:
- The period of time is not known, and cannot be known, and so the only way to choose one is to guess.
- Suppose that all the states required a short period of time, except for one (e.g. system update).  Setting a timeout long enough to cover the long task (if this could be guessed) means that the timeout is far too long for every other task.  The salt master might be waiting a long period of time on short tasks, even if there is a issue as soon as they start.
- The master should be able to quickly detect an issue on a minion, rather than waiting a maximum possible time.

**Existing Settings**: There are couple of master configuration timeout settings for this:
- [timeout](https://docs.saltstack.com/en/latest/ref/configuration/master.html#timeout):  This has a command line option (```-t```), so at least it can be set per ```salt``` command.  However, this doesn't solve the problem of having states with widely different execution times in the same ```state.apply``` run.  Setting ```timeout``` to a high value isn't appealing because then the master just won't check with the minion(s) for a long time.
- [gather_job_timeout](https://docs.saltstack.com/en/latest/ref/configuration/master.html#gather-job-timeout): This does not have a command line option (master configuration file only), and so must be the same for all ```salt``` commands.  Setting this to a high value can help by making the salt master wait for long running states on a minion to complete, but can also cause long delays before a failure is reported.

**Possible Fixes**: Ideally salt minions would be able to reply at any time (including while running an individual state).  In that case, the default low timeout settings would likely be fine.  Any issue on a minion would be detected quickly, and the other issues mentioned here would be moot.  Perhaps there could be an event loop, or a separate thread for responding to the master?  Making ```gather_job_timeout``` a command line option would be a minor improvement because it could vary by ```salt``` command.

**Comment by garethgreenaway** [comment]
@doc987 Thanks for the report. Something you might want to look at is the `ping-interval` option.
https://docs.saltstack.com/en/latest/ref/configuration/minion.html#ping-interval

**Comment by doc987** [comment]
```ping_interval``` doesn't seem to help.  I tried setting it to 5 (i.e. half the default value of ```gather_job_timeout```), but I still get the ```Minion did not return. [No response]``` message when running ```state.apply``` from the master.

Also, does ```ping_interval``` just ping during ```state.apply```, or would the minion ping the master every 5 seconds, all the time, forever?  I don't think it would be desirable to be pinging all the time.  I'm really just trying to avoid a timeout for a successfully running job.

**Comment by RogueOverride** [comment]
I too am seeing this same issue on salt-2018.3.4-1. It appears to run the state, but loses communication between the minion and master during the state's run. Therefore the master never receives a "completed" status from the minion and continues to wait for it to return.

**Comment by smithfarm** [comment]
This should be reopened.

**Comment by smithfarm** [comment]
It seems to be a problem only on larger Salt clusters (the one we are seeing it on has >100 minions).

**Comment by smithfarm** [comment]
In the master log we see lots of messages like this:

```
2020-08-28 14:15:06,071 [salt.transport.mixins.auth:361 ][INFO    ][11043] Authentication failed from host dpscalam152-osd-80.openstack.local, the key is in pending and needs to be accepted with salt-key -a dpscalam152-osd-80.openstack.local
```

We also see this message in smaller clusters when Salt is working fine. But on the big (>100 minion) cluster there are lots more of these messages. Don't know if it's relevant, but thought I'd mention it (maybe it's even worth a separate bug report, since we are certain all the minion keys were accepted before running any Salt States).

**Comment by nschoonm** [comment]
I agree this would be useful.  Possible duplicate of: https://github.com/saltstack/salt/issues/46706
