### ISSUE TITLE
decouple token auth from private key in netbox execution module 

### ISSUE THREAD

**Issue by ngrundler** [saltstack/salt#48474]
### Description of Issue/Question
Currently the netbox execution module bundles token authentication together with the private key file needed for working with the `secrets` app.  If you set up the NetBox application to require login by default, the `netbox.filter` and `netbox.get` functions will return a 403 because unless you're working with the `secrets` endpoint, the token doesn't get passed to the api.

### Steps to Reproduce Issue
Set `LOGIN_REQUIRED = True` in your netbox `configuration.py` and attempt to use `netbox.filter` or `netbox.get` and you'll receive a 403 trace even if you specify your token in the minion configuration file.

**Comment by ngrundler** [comment]
I spoke with @zachmoody in slack about this, and he's already identified an easy fix :)

**Comment by garethgreenaway** [comment]
@ngrundler Thanks for the report.  Look forward to the PR @zachmoody.
