### ISSUE TITLE
salt-ssh returns with minimal unicode related error message, no useful debugging output

### ISSUE THREAD

**Issue by chschmitt** [saltstack/salt#48473]
### Description of Issue/Question

A minion returned the following error when a state was applied via the salt-ssh Python API and state.sls:

```
sanitized_minion_id:
    ----------
    return:
        An Exception occurred while executing state.sls: 'utf-8' codec can't decode bytes in position 1022-1023: unexpected end of data
```
**Note:** There is no useful output in the master logs. Even the running_data/salt-call.log on the minion is not helpful. Is there any chance to recover the full stack trace on the minion to see which piece of code causes the error?

### Setup
Salt is installed via pip in a virtual environment (Python 3.6). There is a custom roster implementation. The top file and some pillars use the Python renderer. Salt-ssh is called via the Python API.

### Steps to Reproduce Issue

Execute the following state. It produces binary output within a cmd.run state. In my original states, I am running some commands that (now) include latin1 or cp1252 strings in the output. I seems that the error depends on the exact sequence/position of the "bad" bytes (which is why the error was not reliably reproducible in the first place).

As a workaround, I redirect the cmd.run stdout and stderr to files.

```
put_script:
  file.managed:
    - name: /tmp/script.py
    - contents: |
        import sys
        sys.stdout.buffer.write(b'\xef'*4096)

run_script:
   cmd.run:
     - name: python3 /tmp/script.py
     - require:
       - put_script
```

Original description: Executing the same state on an identical VM created from the same VM snapshot. Executing the state a second time will not trigger the error.

### Versions Report

Also applies to 2018.3.0

```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.12
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.3 (default, Jan  4 2018, 16:40:53)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
```

**Comment by garethgreenaway** [comment]
@chschmitt Thanks for the report.  Can you provide the state file(s) that you're using that are causing this issue?  Also, if you're able to, upgrade to 2018.8.2, there have been a lot of Unicode related fixes since 2018.3.0 was released.

**Comment by chschmitt** [comment]
Thanks for the quick reply. The update fixed the issue. I will leave it at that if there is no way to narrow down the error. The overall state has over 1000 lines of code and over 100 state declarations, split up into multiple sls files. Since I was not able to isolate the error by running them separately, I do not assume that posting the entire directory tree will be helpful.

**Comment by chschmitt** [comment]
Unfortunately, the error re-appeared also with 2018.3.2. I am still trying to reproduce it.

**Comment by chschmitt** [comment]
@garethgreenaway I found the culprit (see the editied original post).

**Comment by chschmitt** [comment]
@garethgreenaway Can we now move this issue forward?
