### ISSUE TITLE
 file.blockreplace fails on Windows 2012

### ISSUE THREAD

**Issue by pthirumalachar** [saltstack/salt#48484]
### Description of Issue/Question
On Window 2012 R2 box, the file.blockreplace throws the following error

```
line 2478, in blockreplace\n    perms['mode'])\n  File \"C:\\hidden\\hidden\\salt\\bin\\lib\\site-packages\\salt\\modules\\win_file.py\", line 1740, in check_perms\n    if 'applies_to' in grant_perms[user]:\nTypeError: string indices must be integers\n", 
```

The user is an administrator user with all admin privileges.

On probing this further, the check_perms in the file win_file module - At # Verify Grant Permissions,
**The grant_perms object was coming in as unicode instead of dictonary.**

The calling function file.py is sending a unicode object instead of dictonary
E.g. the input is coming as "Administrators". So the iterated object would be "A"
In the check_permsThe next line, checks to see if this user A exists and if exist, tries to get the "applies to" for the user.
Normally this fails and does not proceed as there is no user.
_But strangely on one box, we are getting a user 'd', even though there is no such user.
So it enter's the other loop, which tries to get the user in a dictionary.
As it is not a dictionary, it is throwing the above error._

One of the solutions we are trying in that "checking for (type(grant_perms) is dict)".  This resolves, but this is just a work around.  

Has anyone faced this issue
### Setup
Salt Version:
           Salt: 2017.7.3-8-gb5b083f

Dependency Versions:
           cffi: 1.10.0
       cherrypy: unknown
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 24 2018, 16:00:02) [MSC v.1500 64 bit (AMD
64)]
   python-gnupg: 0.4.0
         PyYAML: 3.11
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free

### Steps to Reproduce Issue
This is happening on one particular setup.  So not sure how to reproduce.

Run a state file which is using file.blockreplace

**Comment by gtmanfred** [comment]
I would be ok with adding that type check.

`isinstance(grant_perms, dict)`

If you wanted to open a PR against the 2017.7 branch, we would greatly appreciate it!

Thanks,
Daniel

**Comment by pthirumalachar** [comment]
Thanks so much.  I will go ahead with this check.  Also, will raise a PR on 2017,7 branch.

Thanks

**Comment by KChandrashekhar** [comment]
@pthirumalachar Were you planning on raising a PR for this ? Thanks !

**Comment by pthirumalachar** [comment]
Hi,
Yes, I was planning to.  
Thanks
Padmini
