### ISSUE TITLE
diff-feature in file.recurse on dry-runs

### ISSUE THREAD

**Issue by bseidenspinner** [saltstack/salt#48489]
### Setup

In our setup we use salt-ssh 2016.11.6 (Carbon) and we want to switch to version salt-ssh 2018.3.2 (Oxygen).

We're missing the diff-feature in file.recurse on dry-runs (test=True). Is there any chance to get this feature back?

With Oxygen and file.recurse in a dry-run we doesn't get the diff, with 2016.11.6 (Carbon), we get the needed diff:

### Steps to Reproduce Issue

salt-ssh 2016.11.6 (Carbon):

salt-ssh -i 'testhost' state.apply teststate test=True

testhost:
----------
          ID: teststate
    Function: file.recurse
        Name: test
      Result: None
     Comment: #### test ####
              The file test.xml is set to be changed
     Started: 14:46:54.247541
    Duration: 1469.814 ms
     Changes:   
              ----------
              test.xml:
                  ----------
                  diff:
                      --- 
                      +++ 
                      @@ -6182,4 +6182,8 @@
                           </md:EntityDescriptor>
                       

                      +
                      +
                      +
                      +
                       </EntitiesDescriptor>

Summary for testhost
------------
Succeeded: 1 (unchanged=1, changed=1)
Failed:    0

salt-ssh 2018.3.2 (Oxygen):

salt-ssh -i 'testhost' state.apply teststate test=True
testhost:
----------
          ID: teststate
    Function: file.recurse
        Name: test
      Result: None
     Comment: #### test ####
              The file test.xml is set to be changed
     Started: 14:47:55.253115
    Duration: 1437.098 ms
     Changes:   

Summary for testhost
------------
Succeeded: 1 (unchanged=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.437 s

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt-ssh 2018.3.2 (Oxygen)
salt-ssh 2016.11.6 (Carbon)

**Comment by gtmanfred** [comment]
I would bet that this falls under the same change that happened here.

https://github.com/saltstack/salt/issues/45895#issuecomment-385508939

**Comment by gtmanfred** [comment]
Yeah, it is, this was an intentional change, try using `mock=True` instead of `test=True`?

**Comment by tilmanschwaner** [comment]
I"ve got the same problem after updating from 2016 to 2018. Mock=True also only shows a diff, when test=False. Is there any way to reactivate the diff-output in test=True mode?
