### ISSUE TITLE
EventPublisher consuming 4.6 GB memory

### ISSUE THREAD

**Issue by jvrahav** [saltstack/salt#48498]
Hi,

in my setup i have 6k minions connected to a single master. The master is a 16GB RAM, built of a variant of CENTOS based OS.

I have a automated script to bring the minions up.The script brings provisions 200 minions in one cycle with an hour gap between each cycle until it provisions 6k minions.

In between this, we have some operations triggered on the minion like collecting some stats and installing some softwares.

we are seeing that the memory slowly increases to about 5.8 GB and then stabilizes at that. At this point there are no events being posted on the event bus. Yet after 5-6 hrs salt does not seem to release the memory allocated.

Following this i restarted the salt master services. The memory consumption came down to 500 MB and stabilized at 900MB ~ 1GB.

I have attached here a snapshot of the memory profile of salt master process. 

doing a strace on the eventpublisher process which was consuming 4.6GB of memory before, i only see epoll_wait and not other processing.
![screen shot 2018-07-10 at 1 08 09 pm](https://user-images.githubusercontent.com/27826808/42496392-7d45d6fa-8443-11e8-8677-fe75401f08cf.png)

Salt Version:
           Salt: 2017.7.2
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.5
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Apr 18 2018, 12:23:00)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.4
 
System Versions:
           dist:   
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.130-2.ph1
         system: Linux
        version: Not Installed

**Comment by jvrahav** [comment]
Master Config

keep_jobs: 1
job_cache: False
external_auth:
  pam:
    admin:
      - '@wheel'
      - '@runner'
      - '@jobs'
      - .*
rest_tornado:
  port: 8553
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
  webhook_url: /hook
  websockets: True
  disable_ssl: False
  debug: False

log_level_logfile: error
max_open_files: 100000
salt_event_pub_hwm: 128000
event_publisher_pub_hwm: 64000
loop_interval: 600

**Comment by jvrahav** [comment]
Minion config

master: salt
random_reauth_delay: 180
recon_default: 10000
recon_max: 170000

**Comment by jvrahav** [comment]
@Ch3LL let me know if the above posted configs are sufficient for analysis

**Comment by jvrahav** [comment]
i tried kill -10 <pid of zero mq> which is consuming the most at the moment. the stack trace printed has this

```
======== Salt Debug Stack Trace =========
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 92, in salt_mastt
er
    master.start()
  File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 208, in starr
t
    self.master.start()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 554, in start
    chan.pre_fork(self.process_manager)
  File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 802, inn
 pre_fork
    process_manager.add_process(self._publish_daemon)
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 335, in add
d_process
    process.start()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 130, in start
    self._popen = Popen(self)
  File "/usr/lib/python2.7/multiprocessing/forking.py", line 126, in __init__
    code = process_obj._bootstrap()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
```

**Comment by jvrahav** [comment]
I used command line for this test. For the previous tests i used tornado.

**Comment by jvrahav** [comment]
Anyone have any suggestions here on what can be done to manage salt memory

**Comment by DmitryKuzmenko** [comment]
@jvrahav sorry for late response. There is an issue related to how ZeroMQ publisher works: if a client is subscribed and don't read the messages the server side publisher keeps that messages in memory. Probably this is the issue you're seeing.
We had memory issues related to this in the past but now all known issues are resolved. So this is why I'm asking how do you contact master to trigger operations.
Can you please share the sanitized script or the command-line sequence that reproduces the memory issue?

**Comment by jvrahav** [comment]
@DmitryKuzmenko , thanks for the reply. 

Can you please let me know the version in which the memory issue you are referring to was fixed.

Unfortunately, i dont have the script with me at the moment. But the script itself does this
1. install salt minion in the endpoint
2. Once the minion connects to the master, reactor kicks in to apply a state on the endpoint
3. At this point there is a rise in salt master memory usage
4. After a cool off period, apply a state file on the endpoint sequentially.
5. At this point, there is a rise in salt master memory. After  a cool off period, it relents about 300 MB memory on the master
6. Run any command for instance list of jobs on the master
7. At this point, the memory on master increases
8. When master is left idle after previous step, the memory is stable and does not reduce even after couple of hours.

**Comment by DmitryKuzmenko** [comment]
@jvrahav I've wrote about this PRs:
https://github.com/saltstack/salt/pull/36024
https://github.com/saltstack/salt/pull/36720

I don't try to say your issue is the same. It's just an assumption. It could be if you use LocalClient or SaltEvent in a wrong manner. For instance probably you create LocalClient, send a command, read an event (here client subscribes to events) and don't read events anymore and don't destroy the client.

But probably problem is somewhere else. If you'd be so kind to try to figure out a minimal reproduction procedure I'd investigate it deeper.

**Comment by jvrahav** [comment]
@DmitryKuzmenko 

the procedure is

1. start salt master with the settings mentioned above in this conversation
2. start the minions on the vms - 5000 t0 6000. All minions are using the configuration specified above in this thread
3. notice the master memory shooting up.
4. after some time invoke sls operations via salt-api based out of tornado
5. After this eventpublisher memory shoots up to to 5.5 GB.

**Comment by DmitryKuzmenko** [comment]
Thank you for descriptions. I can take this and try to reproduce and analyze the issue. But I can't start work on it now. It would be later, closer to the end of Aug.
@rallytime does that sound good?

**Comment by rallytime** [comment]
@DmitryKuzmenko Yeah, that sounds good. Thanks!

**Comment by tsaridas** [comment]
the memory leak exists in msgpack library version.

https://github.com/msgpack/msgpack-python/blob/0.4.8/msgpack/fallback.py#L238

The specific version does not clear buffer and by default the buffer is unlimited.

Upgrading to the latest version of msgpack should help.

**Comment by jvrahav** [comment]
Thanks Andreas, I will try it out

**Comment by tsaridas** [comment]
@jvrahav 
I deleted the previous comment because it needs more investigation.

https://github.com/msgpack/msgpack-python/issues/283

https://github.com/saltstack/salt/blob/develop/salt/transport/ipc.py#L175

To my understanding its normal that python does not release memory and as long as there is free memory the OS will always try to give it more. This should not be a problem as long as the OS does not swap. I tested trying to allocate some memory with another process and the OS did release memory from the EventListener. 

Saying that, you should have no problem even if memory goes high and let the OS deal with it in case it needs more.

An easy way to test this is to run the master in a server with low memory (512MB) and you will notice that EventListener memory does decrease by itself.


The only way to was able to make EventPublisher not increase memory is by adding a buffer (max_buffer_size=32000) to the Unpacker (latest msgpack) and doing garbage collection in an interval with periodCallback. The buffer size is tested with a low load and I'm not sure how much it should be increased for higher loads.


I'll do some more tests and get back to you if I find more information.

**Comment by jvrahav** [comment]
> @jvrahav
> I deleted the previous comment because it needs more investigation.
> 
> [msgpack/msgpack-python#283](https://github.com/msgpack/msgpack-python/issues/283)
> 
> https://github.com/saltstack/salt/blob/develop/salt/transport/ipc.py#L171
> 
> To my understanding its normal that python does not release memory and as long as there is free memory the OS will always try to give it more. This should not be a problem as long as the OS does not swap. I tested trying to allocate some memory with another process and the OS did release memory from the EventListener.
> 
> Saying that, you should have no problem even if memory goes high and let the OS deal with it in case it needs more.
> 
> An easy way to test this is to run the master in a server with low memory (512MB) and you will notice that EventListener memory does decrease by itself.
> 
> The only way I was able to make EventPublisher not increase memory is by adding a buffer (max_buffer_size=32000) to the Unpacker (latest msgpack) and doing garbage collection in an interval with periodCallback. The buffer size is tested with a low load and I'm not sure how much it should be increased for higher loads. Having a buffer can have negative impacts though. Messages might get lost of buffer is full. I'm not even sure if a buffer is needed since I imagine messages are never the same.
> 
> I was worried myself when I saw high memory usage on EventListener but until now I haven't seen any negative effects.
> 
> Another way to have python automatically do the garbage collection for the unpacker would be to create a new one inside the loop and delete the object at the end.
> 
> ```
>         while not stream.closed():
>             unpacker = msgpack.Unpacker(encoding=encoding)
>             try:
>                 wire_bytes = yield stream.read_bytes(4096, partial=True)
>                 unpacker.feed(wire_bytes)
>                 for framed_msg in unpacker:
>                     body = framed_msg['body']
>                     self.io_loop.spawn_callback(self.payload_handler, body, write_callback(stream, framed_msg['head']))
>             except tornado.iostream.StreamClosedError:
>                 log.trace('Client disconnected from IPC %s', self.socket_path)
>                 break
>             except socket.error as exc:
>                 # On occasion an exception will occur with
>                 # an error code of 0, it's a spurious exception.
>                 if exc.errno == 0:
>                     log.trace('Exception occured with error number 0, spurious exception: %s', exc)
>                 else:
>                     log.error('Exception occurred while handling stream: %s', exc)
>             except Exception as exc:
>                 log.error('Exception occurred while handling stream: %s', exc)
>             del unpacker
> ```
> The above solution would work with lower versions of msgpack too but I noticed performance issues.
> The unpacker is used the same way in other parts of the saltstack code so if changed lower memory footprints should be noticed.
> 
> I am not from SaltStack team though so I would suggest @DmitryKuzmenko takes a look at this.

Thanks @tsaridas for your inputs. For now i have limited resource to salt master and that seems to do the trick with consuming less memory. However i would like to hear from @DmitryKuzmenko  as well on your findings.

**Comment by szjur** [comment]
Hi

Please note that minion responses larger than max_buffer_size will cause exception there and in the other approach (creating a new Unpacker inside the while loop) any response larger than 4096 bytes will not work (which is obvious from looking at this code), so this may not be the best solution.
I scrutinised msgpack source and can't really understand why it leaks memory with no buffer set, meaning the Cython version will default to the maximum buffer of INT_MAX.
When the code above is switched to use msgpack.fallback.Unpacker (without any max_buffer_size) it uses very little memory at the cost of being slightly (~10% in my tests) slower.

**Comment by DmitryKuzmenko** [comment]
@szjur I'll look at that right when I'll have more time.

**Comment by szjur** [comment]
@DmitryKuzmenko it actually seems that the main reason of leaks are forgotten event consumers (https://github.com/saltstack/salt/issues/34215). It is easy to overlook this when you have a client with a dedicated event listener but then also use the LocalClient to start some async jobs.

msgpack using Cython code does seem to have some tiny leak or otherwise under very heavy testing that process slowly grows to at least 230+ MB. I've just done 800 iterations of a massive test running jobs on 1650 minions with 16k response and with msgpack.fallback.Unpacker the memory usage hovers around 45 MB at the tradeoff of using a bit more CPU.

**Comment by simmel** [comment]
Bump

**Comment by simmel** [comment]
Wow, every month huh?

**Comment by Ch3LL** [comment]
ping @simmel  this should not go stale again, let me know otherwise

ping @DmitryKuzmenko any update here?

**Comment by DmitryKuzmenko** [comment]
@Ch3LL unfortunately not. It's in my todos

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
