### ISSUE TITLE
2018.3.2 Minion "[CRITICAL][7471] The Salt Master server's public key did not authenticate!" with 2018.3.2 Master.  

### ISSUE THREAD

**Issue by rnickle** [saltstack/salt#48505]
### Setup

Master and Minion both installed 2018.3.2 from stable repo.

Minion was accepted and working.

### Steps to Reproduce Issue

What I'm trying to do is get M2Crypto working on Ubuntu 18.04 so that I can use the x509 and mine functions to create a certificate authority as described in the salt.modules.x509 documentation.

I ran into trouble with M2Crypto when I switched to Ubuntu 18.04.

Here's how I was able to get M2Crypto to the same version on the Minion:

<pre>
sudo apt-get install -y build-essential python3-pip python3-dev python-dev libssl-dev swig
</pre>

Followed by pip3 install:

<pre>
sudo pip3 install M2Crypto
</preO>
After I did that, I was still having trouble with x509 functions, and then when restarting my minion, my minion lost contact with the master.

So my thoughts now are:

- should I wait for a new version?
- should I abandon using salt.mine and x509 (I have expended a few days on it already)?
- should I upgrade my salt master to Ubuntu 18.04 and 2018.3.2?

Minion Startup Log:

`
2018-07-10 08:57:43,119 [salt.minion      :1004][ERROR   ][7471] Error while bringing up minion for multi-master. Is master at salt responding?
2018-07-10 08:57:53,164 [salt.crypt       :743 ][CRITICAL][7471] The Salt Master server's public key did not authenticate!
The master may need to be updated if it is a version of Salt lower than 2018.3.2, or
If you are confident that you are connecting to a valid Salt Master, then remove the master public key and restart the Salt Minion.
The master public key can be found at:
/etc/salt/pki/minion/minion_master.pub
2018-07-10 08:57:53,165 [salt.minion      :1004][ERROR   ][7471] Error while bringing up minion for multi-master. Is master at salt responding?
`

### Versions Report

Minion (Ubuntu 18.04):

`
$ sudo salt-minion --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.3
         pygit2: Not Installed
         Python: 3.6.5 (default, Apr  1 2018, 05:46:30)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-23-generic
         system: Linux
        version: Ubuntu 18.04 bionic
`

Master (Ubuntu 16.04):

`
$ sudo salt-master --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-96-generic
         system: Linux
        version: Ubuntu 16.04 xenial
`

**Comment by Ch3LL** [comment]
are you seeing the same error in the master log as this issue? https://github.com/saltstack/salt/issues/48320

**Comment by rnickle** [comment]
No, I did not, I updated the ticket where it was cross-referenced also.

Thanks,

Rick

*RICHARD E. NICKLE*
*Sr. Technical Services Engineer*
Information Technology Services
rnickle@holycross.edu
*phone: *(508) 793-2569
www.holycross.edu

**Comment by Ch3LL** [comment]
I was able to replicate your issue and verified this fix actually does fix your issue: https://github.com/saltstack/salt/pull/48358

if you apply that 2 line fix it should start working.

**Comment by rnickle** [comment]
Thanks Megan,

I tried applying that patch manually to
/usr/lib/python2.7/dist-packages/salt/crypt.py (on my 16.04 master), and
/usr/lib/python3/dist-packages/salt/crypt.py and I am still seeing:

2018-07-11 14:37:44,891 [salt.minion      :1004][ERROR   ][40726] Error
while bringing up minion for multi-master. Is master at salt responding?

2018-07-11 14:37:54,935 [salt.crypt       :743 ][CRITICAL][40726] The Salt
Master server's public key did not authenticate!

The master may need to be updated if it is a version of Salt lower than
2018.3.2, or

If you are confident that you are connecting to a valid Salt Master, then
remove the master public key and restart the Salt Minion.

The master public key can be found at:

/etc/salt/pki/minion/minion_master.pub

I also tried removing the minion_master.pub keys (and all of my PKI keys on
the client), and restarting.

I also tried unaccepting and reaccepting the minion on the master.

Am I missing a step in applying the patch?

Thanks,

Rick

*RICHARD E. NICKLE*
*Sr. Technical Services Engineer*
Information Technology Services
rnickle@holycross.edu
*phone: *(508) 793-2569
www.holycross.edu

**Comment by Ch3LL** [comment]
you probably already did this but did you restart the services? Also on the python3 box can you make sure to clear out any pycache files. There is a known issue with the loader that does not refresh files if they already have a pycache file. 

If none of that works I might have to re-try the replication and fix. I remember i did do some different things while replicating the issue so I coudl start fresh if the above does not help and let you know what I did with exact steps :) Let me know if the above does not work

**Comment by rnickle** [comment]
I did restart the services, and it didn't seem to work, but I will retry.

I had the same thought along another line.  I have little invested in the
machine, it is a VM I am building it as a template for a series of
machines.  Perhaps I should rebuild it, reinstall salt-minion, get it
running, apply your patch and then reinstall M2Crypto?

I could get that done shortly.

Thanks,

Rick

*RICHARD E. NICKLE*
*Sr. Technical Services Engineer*
Information Technology Services
rnickle@holycross.edu
*phone: *(508) 793-2569
www.holycross.edu

**Comment by rnickle** [comment]
Thanks for your patience Megan, I reproduced my initial test and found that
I had typo'd "b''" as "'b'"

I had in parallel started my test of building a new VM from scratch,
installing salt, applying your patch, and then installed M2Crypto, and that
was also successful, so I'm ready to close my bug.

Rick



*RICHARD E. NICKLE*
*Sr. Technical Services Engineer*
Information Technology Services
rnickle@holycross.edu
*phone: *(508) 793-2569
www.holycross.edu

**Comment by rnickle** [comment]
Ch3LL's fix worked for me on review, and I confirmed it with a new instance.
