### ISSUE TITLE
Special char bug in highstate_return module

### ISSUE THREAD

**Issue by rainer042** [saltstack/salt#48502]
### Description of Issue/Question
When a highstate is run and the module highstate_returner is used eg for sending email upon state changes this module may fail silently because of state names containing special charchters like the pipe char (|).  The returner is failing silently. In such a case you may find a message in /var/log/salt/minion or /var/log/salt/master like noted below.

The highstate itself is successful only the returner fails  and does not return anything. So the chosen satenames are valid state names for salt but invalid for highstate-returner. This should be fixed.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
An example state where I could observe this problem is:

# /srv/salt/top.sls
base:
  '*':    
    - reposcheck

# /srv/pillar/top.sls
base:
  '*': 
    - highstateReturner

# /srv/salt/reposcheck.sls
reposcheck:
  cron.present:
    - name: "/bin/sh -c \"if test `zypper lr|wc -l` -lt 10; then rm -f /root/salt/lib/statefiles/SMT-{{ grains['host'] }}; fi\""
    - identifier: checkrepos
    - user: root
    - minute: 15
    - hour:  5
    - dayweek: '6'

with the following highstate config:
# /srv/pillar/highstateReturner.sls:
highstate:
  report_failures: True
  report_changes: True
  report_everything: False
  report_format: html
  report_delivery: smtp
  smtp_success_subject: 'success minion {id} on host {host}'
  smtp_failure_subject: 'failure minion {id} on host {host}'
  smtp_server: localhost
  smtp_recipients: mymail@mydomain.de
  smtp_sender: root@mydomain.de

and a call like: 
salt '*' state.highstate --return highstate

After finding out what was causing the problem my workaround was to put the shell command containing the '|' -char causing the returner problem into a script file and then to call the script from the state instead of the bare shell command.  By this there is no longer a '- name:' -ressource with pipe characters in it. 

### Steps to Reproduce Issue
Call a highstate with log returner:

salt '*' state.highstate --return highstate

Log messages in /var/log/salt/minion:
2018-07-10 09:38:46,815 [salt.utils.schedule:738 ][ERROR   ][23864] Unhandled exception running state.apply
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/schedule.py", line 730, in handle_func
    self.returners[ret_str](ret)
  File "/usr/lib/python2.7/site-packages/salt/returners/highstate_return.py", line 480, in returner
    report, failed = _generate_report(ret, setup)
  File "/usr/lib/python2.7/site-packages/salt/returners/highstate_return.py", line 386, in _generate_report
    {'states': _generate_states_report(sorted_data)}
  File "/usr/lib/python2.7/site-packages/salt/returners/highstate_return.py", line 299, in _generate_states_report
    [x.rstrip('_').lstrip('-') for x in state.split('|')]
ValueError: too many values to unpack

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt master and minion are the same OS (SLES12SP3) with identical salt versions. 

On the minion:
# rpm -qa|grep salt
salt-2018.3.0-46.28.1.x86_64
python2-salt-2018.3.0-46.28.1.x86_64
salt-minion-2018.3.0-46.28.1.x86_64

On the master:
# salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.138-94.39-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by Ch3LL** [comment]
possible duplicate of https://github.com/saltstack/salt/issues/46225 which was fixed here: https://github.com/saltstack/salt/pull/46434

which was added in 2018.3.1
