### ISSUE TITLE
Unable to pull files from S3 bucket with dot in name

### ISSUE THREAD

**Issue by BenjaminSchiborr** [saltstack/salt#48506]
### Description of Issue
When using file.managed with an S3 bucket as source the state will fail if the S3 bucket name contains a dot.

The returned error would look comparable to this:

```
myserver:
    The minion function caused an exception: Traceback (most recent call last):
      File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1606, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "c:\salt\bin\lib\site-packages\salt\executors\direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "c:\salt\bin\lib\site-packages\salt\modules\cp.py", line 405, in get_url
        path, dest, makedirs, saltenv, source_hash=source_hash)
      File "c:\salt\bin\lib\site-packages\salt\fileclient.py", line 575, in get_url
        'Could not fetch from {0}. Exception: {1}'.format(url, exc)
    MinionError: Could not fetch from s3://my.bucket/test. Exception: HTTPSConnectionPool(host='my.bucket.s3.amazonaws.com', po
rt=443): Max retries exceeded with url: /test (Caused by SSLError(CertificateError("hostname 'my.bucket.s3.amazonaws.com' doesn't match
 either of '*.s3.amazonaws.com', 's3.amazonaws.com'",),))

```

### Setup
1. Have two S3 buckets: mybucket and my.bucket
2. Have a test file in both buckets, e.g. test
3. Use either cp.get_url or file.managed to get the file.

Either one of those *will* work:
```
test:
        file.managed:
            - name: "C:/test"
            - source: s3://mybucket/test
```
or 

```
salt 'myserver' cp.get_url s3://mybucket/test C:/test
```

Either one of those *won't* work:
```
test:
        file.managed:
            - name: "C:/test"
            - source: s3://my.bucket/test
```
or 

```
salt 'myserver' cp.get_url s3://my.bucket/test C:/test
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-79-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
I believe this should be fixed in 2018.3 with the additional of https://github.com/saltstack/salt/pull/48328/files

**Comment by garethgreenaway** [comment]
Upon closer inspection it appears this issue is unrelated to the other fixed in #48328 and the `.` in the bucket name is causing issues with the wildcard SSL certificate which is expecting the name to be `something-something.s3.amazonaws.com` or simply `s3.amazonaws.com`.  Need to dig a bit further down to see if that URL is being generated by Salt or an external library.

**Comment by BenjaminSchiborr** [comment]
@garethgreenaway : I think the error comes out of salt/ext/ssl_match_hostname.py (e.g. https://github.com/saltstack/salt/blob/develop/salt/ext/ssl_match_hostname.py), which is a component taken from urllib3 (see here: https://github.com/urllib3/urllib3/blob/master/src/urllib3/packages/ssl_match_hostname/_implementation.py).

**Comment by garethgreenaway** [comment]
@BenjaminSchiborr Right, the error is coming from there, I am curious if Salt is generating the:
`my.bucket.s3.amazonaws.com` URL that is being used in the attempt to download the file or if it's being generating by something outside of Salt, eg. the Python Boto libraries perhaps.

**Comment by garethgreenaway** [comment]
@BenjaminSchiborr Found the spot in the code that is generating the URL in question (https://github.com/saltstack/salt/blob/2017.7/salt/utils/s3.py#L95).  If you set the following in your minion configuration then the cp.get_url should work as expected:
```s3.path_style: True```

**Comment by BenjaminSchiborr** [comment]
That's awesome! Thank you.

**Comment by garethgreenaway** [comment]
@BenjaminSchiborr No worries!  An opportunity for me to something learn as well.  If you feel that the issue is resolved please feel free to close this out.

**Comment by BenjaminSchiborr** [comment]
When using ``s3.path_style: True`` as an option for the salt-minion I can download files from a bucket with dots in its name.
