### ISSUE TITLE
2018.3.2 file.recurse fails on certain filename

### ISSUE THREAD

**Issue by jonasgit** [saltstack/salt#48510]
### Description of Issue/Question
file.recurse ends up with an exception on this filename. Filename could be considered illegal but rsync and others handles it.
The file.recurse operation fails completly without transferring any files at all.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Centos 7 as master and minion.
Set up an sls with file.recurse to distribute files.
Unpack the attached file to where the files should be on master
[badfile.tar.gz](https://github.com/saltstack/salt/files/2181804/badfile.tar.gz)
The filename is "datoraff\344rer.html"

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt '*' state.highstate
master log says:
2018-07-10 15:02:53,712 [salt.master      :444 ][ERROR   ][4233] Uncaught exception while updating roots fileserver cache
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 440, in _do_update
    update_func(*args)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 161, in update
    new_mtime_map = salt.fileserver.generate_mtime_map(__opts__, __opts__['file_roots'])
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 190, in generate_mtime_map
    for directory, dirnames, filenames in salt.utils.path.os_walk(path):
  File "/usr/lib/python2.7/site-packages/salt/utils/path.py", line 410, in os_walk
    yield salt.utils.data.decode(item, preserve_tuples=True)
  File "/usr/lib/python2.7/site-packages/salt/utils/data.py", line 112, in decode
    if preserve_tuples \
  File "/usr/lib/python2.7/site-packages/salt/utils/data.py", line 236, in decode_tuple
    preserve_dict_class, True, to_str)
  File "/usr/lib/python2.7/site-packages/salt/utils/data.py", line 202, in decode_list
    preserve_dict_class, preserve_tuples, to_str)
  File "/usr/lib/python2.7/site-packages/salt/utils/data.py", line 214, in decode_list
    item = _decode_func(item, encoding, errors, normalize)
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 124, in to_unicode
    return _normalize(s.decode(__salt_system_encoding__, errors))
  File "/usr/lib64/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.6.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by garethgreenaway** [comment]
@jonasgit Thanks for the report.

**Comment by garethgreenaway** [comment]
@terminalmage Ideas on this one?

**Comment by importepeu** [comment]
Instead of creating a new thread, I'll use this one to report a similar problem with file.recurse.

When I want to push a directory to minions containing a directory which contains ":", it fails without error : other files/links are copied but the directory (and its contain) named with some ":" is not copied on the target.

Here is the source directory I want to copy :

```
drwxr-xr-x 4 root root 4096 Feb 21 15:58 ./
drwxr-xr-x 3 root root 4096 Feb 21 15:55 ../
lrwxrwxrwx 1 root root   16 Feb 21 15:57 alm.sncf.fr -> alm.sncf.fr:443//
drwxr-xr-x 2 root root 4096 Feb 21 11:50 alm.sncf.fr:443/
lrwxrwxrwx 1 root root   24 Feb 21 15:58 registry.it.sncf.fr -> registry.it.sncf.fr:443//
drwxr-xr-x 2 root root 4096 Feb 21 11:50 registry.it.sncf.fr:443/
```

And the resulting states :
```
----------
          ID: pushDirectory_/etc/docker/certs.d
    Function: file.recurse
        Name: /etc/docker/certs.d
      Result: True
     Comment: Recursively updated /etc/docker/certs.d
     Started: 17:03:58.603366
    Duration: 276.499 ms
     Changes:
              ----------
              /etc/docker/certs.d/alm.sncf.fr:
                  ----------
                  new:
                      /etc/docker/certs.d/alm.sncf.fr
              /etc/docker/certs.d/registry.it.sncf.fr:
                  ----------
                  new:
                      /etc/docker/certs.d/registry.it.sncf.fr
```

Only links were created :

```
total 8
drwxr-xr-x 2 root root 4096 Feb 21 17:03 ./
drwx------ 3 root root 4096 Feb 21 17:03 ../
lrwxrwxrwx 1 root root   16 Feb 21 17:03 alm.sncf.fr -> alm.sncf.fr:443/
lrwxrwxrwx 1 root root   24 Feb 21 17:03 registry.it.sncf.fr -> registry.it.sncf.fr:443/
```

I had to add a state to create the empty directory "alm.sncf.fr:443" and "registry.it.sncf.fr:443/" and then another state to create files with file.managed to reach my goal.

I wonder if a bug isn't possible with file.recurse while trying to copy filename with special characters.

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
