### ISSUE TITLE
rsync.synchronized state is unfriendly or has some bug？

### ISSUE THREAD

**Issue by wlwio** [saltstack/salt#48539]
### Description of Issue/Question
when use rsync.synchronized state I can not rename the file or dir,bug rsync.rsync  module is ok. I think the module and state methods should be as uniform as possible, and the rsync.synchronized state calls the rsync.rsync module method.

I see the  /usr/lib/python2.7/site-packages/salt/states/rsync.py find some problem
Source code：
```
def synchronized(name, source,
                 delete=False,
                 force=False,
                 update=False,
                 passwordfile=None,
                 exclude=None,
                 excludefrom=None,
                 prepare=False,
                 dryrun=False,
                 additional_opts=None):
    ret = {'name': name, 'changes': {}, 'result': True, 'comment': ''}
​
    if not os.path.exists(name) and not force and not prepare:  #here？？？
        ret['result'] = False
        #not exists is False？How do I rename the file（or dir）
        ret['comment'] = "Destination directory {dest} was not found.".format(dest=name)
    else:
        if not os.path.exists(name) and prepare:
            os.makedirs(name)     #if prepare=True，The file I want to rename is treated as a directory
​
        if __opts__['test']:
            dryrun = True
​
        result = __salt__['rsync.rsync'](source, name, delete=delete,
                                         force=force, update=update,
                                         passwordfile=passwordfile,
                                         exclude=exclude,
                                         excludefrom=excludefrom,
                                         dryrun=dryrun,
                                         additional_opts=additional_opts)
```

This method seems to treat the file as a directory, name can not be the final file name, if it is a directory, name is the second-to-last directory

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

use rsync.synchronized state  to synchronize the remote server（192.168.1.100）  123 directory under the test module to the local /data/test，bug cannot rename dir or file
```
cat /srv/salt/rsync.sls 
rsync_test:
  rsync.synchronized:
    - name: /data/test/
    - source: rsync://x_user@192.168.1.100:873/test/123 
    - passwordfile: /root/rsyncd.pass
```
I will not have this problem directly using rsync.rsync module
```
salt '192.168.1.1' rsync.rsync  "rsync://x_user@192.168.1.100:873/test/test.txt" "/tmp/test123.txt" passwordfile="/root/rsyncd.pass"   
salt '192.168.1.1' rsync.rsync  "rsync://x_user@192.168.1.100:873/test/123/" "/data/test/456/" passwordfile="/root/rsyncd.pass" 
```
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-504.30.3.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by gtmanfred** [comment]
It looks like you should be able to rename the file by setting `force: True`

The ability to rename files/directories should be added.  There will need to be some extra logic added for rsync to reach out and check the filetype of the file on the remote system to know if it is a file or a directory that is being synced, so that the mkdir can be done on the whole path or on the dirname of the path if it is a file, but that shouldn't be that difficult.

Thanks for the request.
Daniel

**Comment by wlwio** [comment]
Thank you for your answer.

force: True  is used to delete
In the state should be setting `prepare: True`

/usr/lib/python2.7/site-packages/salt/modules/rsync.py
`def _check(delete, force, update, passwordfile, exclude, excludefrom, dryrun, rsh):
    '''
    Generate rsync options
    '''
    options = ['-avz']

    if delete:
        options.append('--delete')
    if force:
        options.append('--force')
`
Set ` force: True`  is to add rsync --force parameter

rsync -h |grep force
 -B, --block-size=SIZE       force a fixed checksum block-size
     --force                 force deletion of directories even if not empty
--force is used to delete

But set `prepare: True`
The name is the second-to-last directory，not the last directory

 /usr/lib/python2.7/site-packages/salt/states/rsync.py
`if not os.path.exists(name) and not force and not prepare:
        ret['result'] = False
        ret['comment'] = "Destination directory {dest} was not found.".format(dest=name)
    else:
        if not os.path.exists(name) and prepare:
            os.makedirs(name)
`
Because the source code creates the name as a directory, instead of passing the name to rsync to create it. So set `prepare: True`, The name is the second-to-last directory，not the last directory.

Thank you again for your answer.

**Comment by gtmanfred** [comment]
Ok, then yeah this will need to be added, see the second part of my previous response.

A pr would be need to be submitted that reached out to the remote location using rsync to see if it is a file or a directory, that way we know to makedir(name) or makedir(os.path.dirname(name)).

And then it should be able to do what you are wanting.
