### ISSUE TITLE
Missing state git.cloned is listed in the docs as new for 2018.3.2

### ISSUE THREAD

**Issue by calvinhp** [saltstack/salt#48542]
### Description of Issue/Question

The docs say that `git.cloned` was added in 2018.3.2, but it the feature isn't released yet.

https://docs.saltstack.com/en/latest/ref/states/all/salt.states.git.html#salt.states.git.cloned

It does appear to be in the `develop` branch and the `2018.3` branch.

**Comment by gtmanfred** [comment]
Yup, 2018.3.2 was a smaller bugfix release, which didn't have everything in it that was planned, all of that stuff has been bumped to 2018.3.3.

I will open a pr, thanks!
Daniel
