### ISSUE TITLE
Feature: target minions via topfile / highstate whitelist

### ISSUE THREAD

**Issue by mind-code** [saltstack/salt#48546]
### Description of Issue/Question

I would like to have the option to target via topfile.

Lets say I have a formula with multiple states. Some minions get them all, some only a few, others one and maybe most even none for this particluar formula. Ive done all the targetting in the topfile already.

Now I change something in the state or pillar data and want to propagate that change to all affected minions. I dont wanna call a highstate for all minions. That leaves me with salt <TARGETING> state.apply <STATE>

So now I would have to extract all the targeting Ive already done in the top.sls and run a salt command for every target group. Id love an option to just tell salt to apply these states according to the targeting in the top.sls. Something like:

(-T = target via topfile)
```bash
salt -T state.apply sls1,sls2
salt -T state.apply sls1*
```

In my search for this feature, I stumbled upon the _whitelist_ option for _state.highstate_ . It is undocumented and I only found it in one the example code boxes (module.state doc). It works, but with 2 caveats. First, it only works as a list, no globbing etc and second, every minion which does not get a state applied produced an error (_No states found for this minion_)

Lets say I have 200 minions and have 4-5 target groups summing up maybe 50 minions, getting 150 errors to update a state or calling a highstate on all 200 minions is not ideal.

Expanding the whitelist feature with globbing and being able to suppress the no state errors would make it useable in the same way. In any way, Id love this feature. 

Thx for reading.

**Comment by gtmanfred** [comment]
I saw yall discussing this on irc.

It would be a cool idea.

Thanks for the request.
Daniel

**Comment by yuriks** [comment]
This would still be really nice to have. (In fact, this is how I intuitively expected `state.apply` to work at first.)
