### ISSUE TITLE
Async is a protected word in python 3.7

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#48556]
### Description of Issue/Question
We use the word `async` throughout salt, and it has become a reserved word in python 3.7.

This will cause breaking changes in salt if we change this in an old release, because we use the keyword `async` in client mixins.

This will need to be fixed for us to support python3.7

**Comment by gtmanfred** [comment]
```
$ python -c 'async = True'                                                                                                                                                                                                                                                                                                      4.8m
  File "<string>", line 1
    async = True
          ^
SyntaxError: invalid syntax
```

**Comment by gtmanfred** [comment]
Keyword added to the reserved words in 3.7 

https://docs.python.org/3/reference/lexical_analysis.html#keywords

`adef` was also added, but we do not use that afaik.

**Comment by gtmanfred** [comment]
@saltstack/team-core @saltstack/team-suse do yall have any thoughts on this?

Right now we are talking about only making this change in develop.

**Comment by isbm** [comment]
Mainly this is `salt.utils.async` that we probably also need to rename. This doesn't seem to be hard to fix:

- Rename `salt.utils.async` to `salt.utils.asynchronous` (because other shortcuts are just confusing).
- Rename variables from `async` to `asynchronous` too.

But we will likely need to port this to 2018.3 too.

**Comment by DmitryKuzmenko** [comment]
Also there are some places, like `salt.client.get_local_client` where I named kwarg `sync` to avoid using the `async` keyword. I propose to refactor this name too.

**Comment by gtmanfred** [comment]
We are going to fix this in 2018.3.3 and Fluorine, but not 2017.7

**Comment by gtmanfred** [comment]
This has been completed and is in both 2018.3 and Fluorine for the next releases.

**Comment by isbm** [comment]
@meaksh @dincamihai @brejoc could you please get the port to the package?
