### ISSUE TITLE
Reopen or Provide Reference in Issue Closed by stale bot

### ISSUE THREAD

**Issue by dsteele0301** [saltstack/salt#48578]
Issue #5054 appears to have been closed by stale bot and I am unsure if this issue/feature request was ever implemented or could be referenced to another issue or pull request that may have occurred since it was created.

**Comment by Ch3LL** [comment]
Looks like it was re-opened. If stale-bot ever closes an issue you can always ask in the issue to re-open if you believe its still affected in the latest release.
