### ISSUE TITLE
Proposal to remove cache for building Windows minion offline

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#48575]
### Question/Proposal
When you build a Windows minion, resources are downloaded from repo.saltstack.com/windows/dependencies and pypy.

To build a Windows minion offline, I added a cache which is enabled by 3 environment variables (SALTREPO_LOCAL_CACHE, SALT_REQ_LOCAL_CACHE, SALT_PIP_LOCAL_CACHE)

The cache needs to be manually filled, which is tedious for pypy.

I think the risk of a wrong cache is higher than the benefit.

Does anyone use it?
I propose and offer to remove the cache.

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any opinions here?

**Comment by twangboy** [comment]
@markuskramerIgitt I accept your proposal.
