### ISSUE TITLE
salt-ssh test.ping returns cannot locate python even though its installed on target host

### ISSUE THREAD

**Issue by adtyashgl** [saltstack/salt#48595]
### Description of Issue/Question
salt-ssh cannot recognise installed python on minion even though it is installed and is at the version higher than what it needs.

I have the following roster file
Test:
   host: xx.xx.xx.xx
   sudo: True
   user: root
   passwd: <password>

Running the test.ping returns

```
salt-ssh Test test.ping

Test:
    ----------
    retcode:
        10
    stderr:
        ERROR: Unable to locate appropriate python command
    stdout:
        ERROR: salt requires python 2.6 or newer on target hosts, must have same major version as origin host

```
Running raw python yields the path of python
```
salt-ssh Test -r 'which python'
Test:
    ----------
    retcode:
        0
    stderr:
    stdout:
        /usr/bin/python

```
```
salt-ssh Test -r 'python --version'
Test:
    ----------
    retcode:
        0
    stderr:
        Python 2.7.5
    stdout:

```
Python version on Master

```
python --version
Python 2.6.6

```

Could anyone please help or point me to what I am doing wrong?
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.23.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by gtmanfred** [comment]
I am unable to replicate this on 2018.3.2, can you try upgrading to that version?

```
[root@salt ~]# salt-ssh \* -i test.ping
minion:
    True
[root@salt ~]# salt-ssh --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.30.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

[root@salt ~]# salt-ssh minion test.versions_report
minion:
    Salt Version:
               Salt: 2018.3.2

    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: Not Installed
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: Not Installed
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: Not Installed

    System Versions:
               dist: centos 7.5.1804 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-862.3.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.5.1804 Core
```

I am also using a centos 6 server for my salt-ssh master, which uses python2.7 installed from the salt repository, and am logging into a centos 7 machine.

**Comment by adtyashgl** [comment]
Hi Daniel,
I was able to fix the issue. Turns out salt-api, salt-master was installed under python 2.7 and salt-ssh was installed under python 3.6 on the system I was running my tests on.

Once I fixed the versions salt-ssh worked.

You can close this issue. Thanks for your time on this
