### ISSUE TITLE
processes not cleaned after connection closed 

### ISSUE THREAD

**Issue by nadezhdabelan** [saltstack/salt#48601]
if execute asynch call from java client then process does not collapse
 ps -ef | grep -c salt-api
3
the number of processes will increase (for example 100) after some timeout they will be closed, but thread can be exhausted
but if I set expire_responses  in true, processes will be 2
but in new version expire_responses is deprecated, how to solve the problem with increasing processes?

**Versions Report**
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

Add CommentCollapse

**Comment by gtmanfred** [comment]
It looks like the `engine.timeout_monitor.on` for cherrypy has been removed starting in cherrypy 12.0.0, which is what we used to implement `expire_responses`.  As long as you use cherrypy < 12.0.0, we will still enable it, but there is not a way to implement it in the newer versions of cherrypy.

https://github.com/saltstack/salt/issues/44601

If you find a way to implement it, please let us know and we will add that method.

Thanks,
Daniel
