### ISSUE TITLE
salt-api return http error 500 during execution async task

### ISSUE THREAD

**Issue by nadezhdabelan** [saltstack/salt#48602]
in the peak load hour, we have a lot of requests for salt-api, at this time when creating more asynchronous calls from the client's java, the server returns error 500, for what reason it can be?
only in the peak load hour....
job lasts a long time

**Versions Report**
```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by garethgreenaway** [comment]
@nadezhdabelan Thanks for the report.  Can you provide a bit more detail of how you're using the Salt API?  How you have it configured and if you're using rest_cherrypy or one of the other salt api modules.

**Comment by nadezhdabelan** [comment]
hi, thanks.
yes we use rest_cherrypy 
logs:
![image](https://user-images.githubusercontent.com/36509865/42808451-091ba240-89bc-11e8-9d43-673512b0e931.png)
![image](https://user-images.githubusercontent.com/36509865/42808478-16a2673c-89bc-11e8-98a6-a0196fb33f8e.png)

**Comment by nadezhdabelan** [comment]
hello, it seems to me that I found the error:
error of deleting the file .minions.p occurs when at the same time 2 commands are sent per one minion
I have eliminated this behavior and there is no such error.
