### ISSUE TITLE
Filter output of a Salt Module

### ISSUE THREAD

**Issue by patatman** [saltstack/salt#48620]
### Description of Question
I'm trying to filter the output of a Salt Module, in this specific case the salt.module.postgres.
the command is: ```salt '*' postgres.db_list```
The output looks like this: 
```
    db1-rerun:
        ----------
        Access privileges:
            {db1_owner=CTc/db1_owner,=Tc/db1_owner}
        Collate:
            en_US.UTF-8
        Ctype:
            en_US.UTF-8
        Encoding:
            UTF8
        Owner:
           db1_owner
        Tablespace:
            pg_default
    db2:
        ----------
        Access privileges:
            {db2_owner=CTc/db2_owner,=Tc/db2_owner,user_read=c/db2_owner}
        Collate:
            en_US.UTF-8
        Ctype:
            en_US.UTF-8
        Encoding:
            UTF8
        Owner:
            db2_owner
        Tablespace:
            pg_default
```
I would like to filter the output by name, for instance:

```salt '*' postgres.db_list filter=name```
I'd like the output to be:
```
    db1-rerun:
        ----------
    db2:
        ----------
```

If it's possible the behavior should be like grain.get. For instance:
```salt '*' grains.get systemd:features```
Docs: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.grains.html#salt.modules.grains.get

Is this something that can be globally set, or should this be kept at per module level? Otherwise I'll have a look at the postgres module to implement something like the grains.get module.

**Comment by gtmanfred** [comment]
I would highly recommend using `jq` or `yq` to query the json/yaml for the output that you want.

We do not include anything in salt to do that.

https://github.com/kislyuk/yq
https://stedolan.github.io/jq/

Because otherwise, this would have to be implemented on every salt module.  You could also implement an outputter that allows you to specify a query argument for the yaml to only print certain things out.

**Comment by patatman** [comment]
Thanks for the response, and I'm aware of jq. 
I was just wondering if it was possible natively in Saltstack.
Creating a outputter is also a interesting idea, will have a look into that! 
Thanks
