### ISSUE TITLE
How to pass tty in salt-ssh CLI

### ISSUE THREAD

**Issue by hasija** [saltstack/salt#48622]
### How to pass tty in salt-ssh CLI

Error: sudo: sorry, you must have a tty to run sudo, When trying to run command " salt-ssh --roster=scan 'minion' --sudo --user='user' --passwd='pass' test.ping  -i "
There is no option mentioned to pass tty in the cli as metioned in the documentation:- https://docs.saltstack.com/en/latest/ref/cli/salt-ssh.html#cmdoption-salt-ssh--sudo

**Comment by gtmanfred** [comment]
There is not a way afaik.

You would need to do something like add it to roster_defaults.

```
roster_defaults:
  tty: True
```

In /etc/salt/master.

I am going to mark this as a feature request.

**Comment by andreasnuesslein** [comment]
this would still be nice, will stalebot reactivate on comment? :test:
