### ISSUE TITLE
NPM install forever -g command in State file - not working

### ISSUE THREAD

**Issue by jasonp26** [saltstack/salt#48669]
### Setup
copy_npm:
  file.managed:
    - name: /tmp/npm.sh
    - source: salt://scripts/os/npm.sh
    - user: root
    - mode: 755
run-npm:
  cmd.run:
    - name: /tmp/npm.sh

Inside that 'npm.sh' script is just one line of code: `npm install forever -g`

I have tried to run the above by just doing it directly from the state file in the - name field but i get the same error as below.

run-npm:
  cmd.run:
    - name:  npm install forever -g

The error i am getting is this:
----------
          ID: install-npm
    Function: cmd.run
        Name: npm install forever -g
      Result: False
     Comment: Command "npm install forever -g" run
     Started: 13:23:12.011120
    Duration: 6.344 ms
     Changes:
              ----------
              pid:
                  21945
              retcode:
                  127
              stderr:
                  /bin/sh: npm: command not found
              stdout:`

### Versions Report
`Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

Thanks in advanced to any help.

**Comment by garethgreenaway** [comment]
The error you're getting looks like `npm` is not in the root user's PATH.  When you're running it manually are you running it as root as well?  Can you run `which npm` from the command line and inside your script include a line that is `echo $PATH`?

**Comment by jasonp26** [comment]
Hi @garethgreenaway thank you and yes you were on the right path "pun" lol i have just got it sorted it turned out that i needed this to make it work (- runas: root)

Here is the new code layout that works.

run_vfa:
  cmd.run:
    - name: ./vfa.sh
    - cwd: /etc/profile.d/
    - runas: root
run-code:
  cmd.run:
    - name: ./npm.sh
    - cwd: /tmp/
    **- runas: root**
