### ISSUE TITLE
Question: How to automatically delete old key and accept new key automatically

### ISSUE THREAD

**Issue by renatasV** [saltstack/salt#48686]
### Description of Issue/Question
Maybe missed somewhere, but not finding a way to auto-accept minion key when previously used minion key is accepted in the master. 

Currently what I have is: 
using reactor and once I see "salt/auth" event i triger state.  
```
{# minion failed to authenticate -- remove accepted key #}
{% if not data['result'] and data['act'] == 'denied' %}
minion_remove:
  wheel.key.delete:
    - args:
      - match: {{ data['id'] }}
{% endif %}

{# minion is sending new key -- accept this key #}
{% if 'act' in data and data['act'] == 'pend' %}
minion_add:
  wheel.key.accept:
    - args:
      - match: {{ data['id'] }}
{% endif %}
```
I delete previously used VM with minion inside, this mean in master key is already accepted.
Create a new VM and deploy salt. (minion ID will be the same)
so far as in documentation and my example, salt master react to salt/auth event and triggers key delete state. HOWEVER because OLD key was already accepted New minion Key becomes denied and minion shutdowns. 

When it is started up again New key will be accepted. 

how to do this with reactor so key is refreshed without minion start/restart?

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.13.2.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by gtmanfred** [comment]
AFAIK, there is no way to do this with the default configs.  The only thing you could do is set open mode, which just always accepts all keys.

That kind of looks like what you have implemented anyway using the reactor.

https://docs.saltstack.com/en/2017.7/ref/configuration/master.html#open-mode
