### ISSUE TITLE
file.blockreplace regression in 2018.3.2

### ISSUE THREAD

**Issue by nhavens** [saltstack/salt#48695]
### Setup
/srv/salt/blockreplace.sls
```
add another child div to test.html:
  file.blockreplace:
    - name: /tmp/test.html
    - marker_start: child1
    - marker_end: div
    - content: |
        <div id="child2" />
    - unless:
      - grep "<div id=\"child2\" />" /tmp/test.html
```
/tmp/test.html
```
<html>
<body>
<div id="parent">
  <div id="child1" />
</div>
</body>
</html>
```

### Steps to Reproduce Issue
Expected behavior, and that of previous releases (I'm not sure which was the first release to have this problem) was to preserve the entire line containing marker_end. In version 2018.3.2, all characters preceding marker_end on the line containing marker_end are removed.  In the output below, notice that `</` is missing from what should be `</div>` following the inserted block.

```
user@master /srv/salt $ sudo salt 'master' state.apply blockreplace
master:
----------
          ID: add another child div to test.html
    Function: file.blockreplace
        Name: /tmp/test.html
      Result: True
     Comment: Changes were made
     Started: 16:49:14.409016
    Duration: 1851.095 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -2,6 +2,7 @@
                   <body>
                   <div id="parent">
                     <div id="child1" />
                  -</div>
                  +<div id="child2" />
                  +div>
                   </body>
                   </html>

Summary for master
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   1.851 s
user@master /srv/salt $ 
```
I believe this issue was introduced by @terminalmage in commit https://github.com/saltstack/salt/commit/479818703504a838a1f42c9b766abf1695231133#diff-7c48191b14cdf053cf954d03cc317963R2624. Specifically, I think the call to `_add_content` on line 2624 should pass in `end_line=line` rather than `end_line=line[marker_end_pos:]`.

### Versions Report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by terminalmage** [comment]
This change was made in order to handle newlines around the marker better. Try changing your marker to `'</div'` or `'</div>'`, either should work.

BTW, this change was stated in the [file.blockreplace docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.blockreplace) (see `Changed in version 2017.7.5,2018.3.1`), but it was not listed in the release notes for either 2017.7.5 or 2018.3.1. I've opened https://github.com/saltstack/salt/pull/48699 to add this information to the release notes for those releases.

**Comment by neilehavens** [comment]
Thanks @terminalmage, I've made the suggested change, and it's working.

I read the [file.blockreplace docs](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.blockreplace) when I stumbled across this issue. I missed the Changed in version 2017.7.5,2018.3.1 section. Sorry about that. 
My concern now is that section contradicts the explanation for the marker_end argument, which still says:

> The line content identifying a line as the end of the content block. Note that the whole line containing this marker will be considered, so whitespace or extra content before or after the marker is included in final output.

**Comment by terminalmage** [comment]
Good catch! I've opened https://github.com/saltstack/salt/pull/48847 to further correct the docs.

**Comment by terminalmage** [comment]
Fix was merged 18 months ago, please close.

**Comment by nhavens** [comment]
Thanks @terminalmage. Sorry for leaving this open so long.

**Comment by terminalmage** [comment]
No problem, I was actually directing that at the project maintainers :smile:
