### ISSUE TITLE
What Salt solution do you use to manage your servers outside?

### ISSUE THREAD

**Issue by Annnetta** [saltstack/salt#48728]
Hello everyone!

I am wondering what do you use to manage your servers that are outside your local network(on the Google Cloud for example)?

I am thinking about Salt-SSH, but it is a little bit complicated as our servers can change IP addresses frequently... 

Thanks in advance!
Hanna

**Comment by garethgreenaway** [comment]
@Annnetta Thanks for the question.  Salt-SSH is definitely an option but you can only use regular Salt and even taken advantage of Salt Cloud for managing instances in Google Cloud.  If you want to go with the traditional master/minion approach you do need to make sure that your Salt master is accessible outside the local network.

**Comment by Annnetta** [comment]
@garethgreenaway thank you! I will try Salt Cloud then, maybe it will meet our company's demands.
