### ISSUE TITLE
[Feature Request] Allow removal of existing content and add new one in a file using file.blockreplace.

### ISSUE THREAD

**Issue by abh23** [saltstack/salt#48729]
This feature will be useful in replacing existing content in a file with new content. 
Example, I install chrony/apache and I want to replace all the lines in their respective configuration files with the new content that I am sure works for me. Also, these files will have a lot of comment section which I want to remove as well. 

Is it possible to implement? 

The only way I can think of achieving this today is using a file.rename before attempting to file.blockreplace to make sure the resultant config file has content that I intend to have.

**Comment by garethgreenaway** [comment]
@abh23 Thanks for the report.  This seems like the perfect situation for using the `file.managed` Salt state with a template.  This will allow you to define the file exactly the way you want it.

**Comment by abh23** [comment]
You are right @garethgreenaway but ` file.managed` if we see from end to end orchestration front adds to required configuration file management/version control along with additional steps to make it available on the salt-master in a stack(talking about openstack here). 

Apart from that, if we have an option to replace the existing content and add new block controlled content, all the content can be kept in state file itself. We anyways have an option of keeping a backup so the user can always keep backup of the file if it is to be referred(which I feel won't be a requirement at least in a production environment)

Your comments on this?
