### ISSUE TITLE
Salt upgrade from 2015.8.12 to 2017.7.7

### ISSUE THREAD

**Issue by vamih** [saltstack/salt#48732]
### Description of Issue/Question
Hello,

I want to upgrade salt-packages from 2015.8.12 to 2017.7.7 on RedHat 6.6 but I see a strange behavior of the minion after the upgrade.
Firstly I upgraded salt-master and everything went ok, then I tried to upgrade the minions with a state and it failed, I don't know why.  The service got suck and the only option was to  connect on the machine where salt-minion is running and reinstall the package. After reinstall salt minion started but with some errors in the logs ( see below) and furthermore when I try to ping it from the master I receive 'test.ping'  is not available.
### Setup
In order to upgrade salt packages I firstly installed python27-pip since python2.6 isn't supported by newer versions of Saltstack. More than this I still need python 2.6 since it's used by both yum and the application that runs on my servers.
The state used to upgrade my minion is:

Salt repo:
  file.managed:
    - name: /etc/yum.repos.d/salt-2017.7.repo
    - source: salt://upgrade/files/salt-2017.7.repo
    - unless: ls /etc/yum.repos.d/salt-2017.7.repo

Salt clean cache:
  cmd.run:
    - name: yum clean expire-cache

Restart Salt Minion:
  cmd.run:
{%- if grains['kernel'] == 'Windows' %}
    - name: 'start powershell "Restart-Service -Name salt-minion"'
{%- else %}
    # fork and disown the process
    - name: |-
        exec 0>&- # close stdin
        exec 1>&- # close stdout
        exec 2>&- # close stderr
        nohup salt-call --local service.restart salt-minion &
{%- endif %}
    - order: last

Upgrade Salt Minion:
  pkg.installed:
    - name: salt-minion
    - version: 2017.7.7

### Steps to Reproduce Issue
I just run "salt "*" test.ping" and from upgraded minion I received this:
indosv2cdmi07:
    True
indosv2cdmi07:
    'test.ping' is not available.

Into the logs I see this:
[salt.loaded.int.module.mine                          ][ERROR   ][8092] Function grains.get in mine_functions not available
2018-07-24 12:31:19,383 [salt.loaded.int.module.mine                          ][ERROR   ][8092] Function grains.get in mine_functions not available
2018-07-24 12:31:19,384 [salt.loaded.int.module.mine                          ][ERROR   ][8092] Function grains.get in mine_functions not available
2018-07-24 12:31:19,384 [salt.loaded.int.module.mine                          ][ERROR   ][8092] Function grains.items in mine_functions not available
2018-07-24 13:31:19,275 [salt.loaded.int.module.mine                          ][ERROR   ][8161] Function grains.get in mine_functions not available
2018-07-24 13:31:19,276 [salt.loaded.int.module.mine                          ][ERROR   ][8161] Function grains.get in mine_functions not available
2018-07-24 13:31:19,276 [salt.loaded.int.module.mine                          ][ERROR   ][8161] Function grains.get in mine_functions not available
2018-07-24 13:31:19,277 [salt.loaded.int.module.mine                          ][ERROR   ][8161] Function grains.items in mine_functions not available

If I target specifically the minion responds to ping:
salt "indosv2cdmi07" test.ping
indosv2cdmi07:
    True

### Versions Report
salt-master --versions-report
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jun  8 2018, 10:46:35)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.6 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.11.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.6 Santiago

salt-minion --versions-report
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jun  8 2018, 10:46:35)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.6 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-642.11.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.6 Santiago

On both master I only activated the following variables in config:
cachedir: /salt/master
sqlite_queue_dir: /salt/master/queues
log_file: /salt/master/logs/master

On the minion the config is this one:
cat /etc/salt/minion.d/_schedule.conf
schedule:
  __mine_interval: {enabled: true, function: mine.update, jid_include: true, maxrunning: 2,
    minutes: 60, return_job: false}

I pretty sure that I encounter this situation because of python packages but I don't know how to fix it, so any advice is more than welcomed.
Thanks!

**Comment by garethgreenaway** [comment]
@vamih Thanks for the report.  Based on the results you're getting back it appears that the previous version is still running but the python pieces have been removed.  When you encounter this can you see if there are multiple copies of the Salt minion running?  In a normal situations there should be two copies running.

**Comment by vamih** [comment]
@garethgreenaway Thanks for your help. You were right, I had a salt-minion process still running.
But since I'm using a state to upgrade where into it should I include a check for that process?
