### ISSUE TITLE
Create a Window's install process via winrm using powershell -- Feature-Request 

### ISSUE THREAD

**Issue by rickh563** [saltstack/salt#48751]
### Feature-Request

Create a Window's install process via winrm using powershell

At a minimum, this work will include documentation on how to properly remote install salt via powershell that includes sample scripts

**Comment by KChandrashekhar** [comment]
This may be resolved by using the new Salt-SSH for Windows.This enables using salt-ssh over WinRM to run Salt states and modules, including executing Powershell scripts.

Enterprise customers you can access this feature from the enterprise download portal under the section titled, "Agentless Windows Module".
