### ISSUE TITLE
Salt-Minions not restarting automatically in Windows

### ISSUE THREAD

**Issue by manish-kumar1993** [saltstack/salt#48763]
### Description of Issue/Question
Salt-Minions not restarting automatically in Windows. In some minions, while restarting in debug mode we are getting below error message 
Error parsing configuration file: c:\salt\conf\minion.d\_schedule.conf - unacceptable character #x0000: special characters are not allowed
  in "c:\salt\conf\minion.d\_schedule.conf", position 0
![nul_error_log](https://user-images.githubusercontent.com/29351140/43193420-922f6f8c-901d-11e8-9a61-a555047ee213.JPG)
and NULNULNULNUL.... is there in c:\salt\conf\minion.d\_schedule.conf file. 
![nul_error](https://user-images.githubusercontent.com/29351140/43193520-dac42d0a-901d-11e8-8634-beab864afca6.JPG)
After deleting those special characters I am able to start salt-minions.  
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Not able to replicate but it is happening with multiple minions.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-master version:- salt 2018.3.0 (Oxygen)
salt-minions version:- salt 2018.3.0 (Oxygen)

**Comment by gtmanfred** [comment]
Unfortunately without being able to replicate this, there isn't a lot that we can do to fix it.

I know that yaml won't like NULL characters in those files, so that part makes sense.

What was happening on the machines before this happened?  Did you upgrade them from a previous release?

Thanks,
Daniel

**Comment by lubyou** [comment]
Hi,

I also ran into this issue on a few Windows machines.
Unfortunately, this happened a few months ago and I do not have a lot of infos.

The machines in questions were all running french Windows 7 SP1 and used salt minion 2016.11.5 or 2016.11.9.
The top file at that time upgraded the salt minions to 2017.7.7.
The schedule was added via schedule.present state.

Once we noticed the issue, we stopped using schedule.present.

I will try to gather more information.

I think it would be very good if #48278 gets implemented, the thought of having a bunch of remote windows minions in paused mode is a bit scary :)

Thanks

**Comment by TheVakman** [comment]
Yes, #48278 would be excellent. I have run into this a few times now during upgrades of the minions.

**Comment by scottalanmiller** [comment]
I still have this issue today.

**Comment by QuasiDev** [comment]
I am also experiencing this in my minions on Windows 10 running 3001 and master on 3001.
