### ISSUE TITLE
Nested grain in autosign_grains

### ISSUE THREAD

**Issue by others-git** [saltstack/salt#48776]
### Description of Issue/Question

When using `autosign_grains`, nested grains cannot be used. 

### Setup

In my example I use `ip4_interfaces:eth0` as a file name for sake of example, though I know this would not be compatible with Windows. 

My expectation is that the minion would, in the same way `grains.get` returns a nested value of grain, obtain the value to send to the master for auto-acceptance. 

### Steps to Reproduce Issue

On **master**, in `/etc/salt/master`:

```
...
autosign_grains_dir: /etc/salt/autosign_grains
...
```

On **master**, in `/etc/salt/autosign_grains/ip4_interfaces:eth0`

```
10.40.0.1
```

On **minion**, in `/etc/salt/minion`:

```
...
autosign_grains:
  - ip4_interfaces:eth0
...
```

On **minion**, output of `salt-call grains.get "ip4_interfaces:eth0" --local`

```
10.40.0.1
```

### Versions Report
Minion/master are same versions/OS.
```Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core```

**Comment by Ch3LL** [comment]
https://github.com/saltstack/salt/blob/v2018.3.2/salt/crypt.py#L804

looks like we are only grabbing that first grain value as yous stated and no other nested values if available. This would need to be added.

**Comment by Oloremo** [comment]
not stale

**Comment by jynolen** [comment]
Hello please considered my PR to implement the change.
Thank you

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
