### ISSUE TITLE
Job triggers reactor, then reactor creates new job, creating an infinite loop

### ISSUE THREAD

**Issue by JonathanWilbur** [saltstack/salt#48772]
### Description of Issue/Question

I created a reactor to send a message to a Microsoft Teams channel when a server is configured. The reactor configuration looks like this:

```
reactor:
  - 'salt/job/*/new':
    - /srv/salt/reactor/start-notification.sls
```

The idea is to create a notification whenever something is done to configure a host. Though not shown--because it does not exist yet--I plan to have another reactor like the one shown above that posts another message to the Teams channel that indicates whether the configuration was successful, or whether it failed.

The problem that I discovered--and which led to me being blocked by the Teams API for spamming requests--is that, when a reactor runs, it creates a new job. This new job then triggers the reactor once more, repeating the process ad infinitem. The salt-minion's CPU gets hammered, and the salt-master's hard-drive fills up with millions of cached job files.

I would like to see this changed so that jobs created by reactors do not fire this event--or at least do something different that prevents the reactor from looping indefinitely.

### Setup

The contents of `/srv/salt/reactor/start-notification.sls`, referenced above, though slightly modified to remove sensitive information:

```sls
send_start_message:
  local.msteams.post_card:
    - tgt: "*"
    - args:
      - title: "SaltStack configuration started"
      - message: "SaltStack configuration starting for hosts matching this target: "
      - hook_url: <URL REMOVED>
```

### Steps to Reproduce Issue

Create any reactor that executes in response to the `salt/job/*/new` event. Then run a job to kick off the infinite loop. **WARNING: Do not try this with any execution module / state function that sends HTTP requests or anything that can cost you money!**

### Versions Report

Salt Master:

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

Salt Minion:

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug 29 2016, 10:12:21)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.2 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.36.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.2 Maipo
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-core do you think this would be possible? Or possibly set an argument for when a job that is created from the reactor doesn't set off the reactor again?

also @JonathanWilbur you can add some jinja logic in your reactor state to make sure it only runs when you want as detailed in the docs https://docs.saltstack.com/en/latest/topics/reactor/

**Comment by gtmanfred** [comment]
What you would need to do is check if the function that is being passed in the reactor is `msteams.post_card` and then not run the reactor.

```
{%- if not data['fun'] == 'msteams.post_card' %}
send_start_message:
  local.msteams.post_card:
    - tgt: "*"
    - args:
      - title: "SaltStack configuration started"
      - message: "SaltStack configuration starting for hosts matching this target: "
      - hook_url: <URL REMOVED>
{%- endif %}
```

There isn't a good way to know what the message is being sent from, we could add `__opts__['__cli']` to the job on the event stream, but that wouldn't be super useful, because then you wouldn't see events from the scheduler on the master pushed to your msteams either.

**Comment by JonathanWilbur** [comment]
I get that there is a Jinja workaround. I tried implementing almost that exact code that you have above, @gtmanfred (this answers your question to me, @Ch3LL ) . Still, the point remains that this is functionality that likely brings down both the master and minion unless one knows ahead of time to do implement that Jinja condition. In other words, it's broken by default. At the very least, the documentation needs to be updated with warnings about this phenomenon; but the fix that would make this do what users expect is to prevent any reactor from throwing the same event that triggered it in the first place.
