### ISSUE TITLE
should 'cp.cache_file' support the 'pillar://' scheme?

### ISSUE THREAD

**Issue by thewilli** [saltstack/salt#48787]
I originally wanted to use the [win_pki.import_cert](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_pki.html#salt.modules.win_pki.import_cert) module to install a certificate bundle on a Windows Minion. That certificate is - for reasons of security - present in the Pillar only (one could argue if having a password set is sufficient, but I don't want wildcard cert bundles be stored in the Minion-wide available fsroot).

So my first idea was to propose to add a `pillar_source` option, just like `salt.states.file` does for example. But then I did some digging in the underlying code. The `import_cert` function, and many others, are using [salt.modules.cp.cache_file](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.cache_file) to create a path to a locally cached file. This function accepts fsroot references (`salt://`) as well as http(s) and ftp. So my idea was: Why not extend this function to support a `pillar://` scheme was well? This would out-of-the-box add Pillar support to many different state- and execution module functions. But of course there might be some drawbacks as well:

* Pillar items might contain very sensitive information, and we might not want them to reside in the filesystem (but what about the local Pillar cache? doesn't it do the same?)
* we might not actually be able to *cache* Pillar items, because we can't guarantee they are up to date (or is there a way). that might not be a big issue, though.

What do you think? Do you see any *strong* reasons why that scheme shouldn't be supported as well?

**Comment by damon-atkins** [comment]
`pillar://`  could just call `pillar.get`  it would be still cache to a file I suspect.

**Comment by garethgreenaway** [comment]
@saltstack/team-core Thoughts?

**Comment by gtmanfred** [comment]
Once I finish this, it would be super easy to support pillar:// in the file protocols.

https://github.com/saltstack/salt/pull/48654
