### ISSUE TITLE
Feature-Request:  add the ability to use Set-WebConfiguration command set to win_iis

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#48792]
### Description of Issue/Question

The [win_iis](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_iis.html) module needs the ability to use set-WebConfiguration from the [webadministration PowerShell module](https://docs.microsoft.com/en-us/powershell/module/webadministration/?view=win10-ps). 

The win_iis state module should also reflect this change.

This is to allow setting items like `/system.webServer/security/authentication/anonymouseAuthentication -name 'userName'` 

This will allow much wider ability to configure the web services within IIS.

**Comment by twangboy** [comment]
ZD-2693

**Comment by rickh563** [comment]
### Next Steps

* Discuss with Salt-Support before initiating development any development of this Feature-Request

* ZD-2693 has written a `state module` and a `custom execution module` to manage this for internal to their organization;

* It is possible that they my contribute this to the project;

* FOSS policy is under discussion;

**Comment by rickh563** [comment]
See PR https://github.com/saltstack/salt/pull/49399
