### ISSUE TITLE
Write some tests for new file.tidied function

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#48807]
https://github.com/saltstack/salt/pull/47718 needs some tests written and @gtmanfred is awesome and agreed to help.

**Comment by gtmanfred** [comment]
https://github.com/dhs-rec/salt/pull/1

**Comment by cachedout** [comment]
@gtmanfred Did you mean to submit this to the fork that you did?

**Comment by gtmanfred** [comment]
Yes, i submitted it to his branch, so once he merges it, it will appear in the PR that he has opened at #47718

**Comment by gtmanfred** [comment]
If he doesn't merge it, I can push it to his repository instead.
