### ISSUE TITLE
Reporting while job scheduling

### ISSUE THREAD

**Issue by Annnetta** [saltstack/salt#48819]
Hi all,
I have a question about the reporting from Minions.

When I schedule the Minions to execute the job every 10 minutes, I would like to know whether this job has been successfully executed or not. 

I would like to have something like what gives 
salt-run jobs.exit_success job_id
but for all Minions and jobs, like:
name_of_the_minion – job(function) – success/not

Does it exist?

Thank you in advance,
Hanna

**Comment by gtmanfred** [comment]
There is nothing that exists like that right now.

You could write something that runs https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.jobs.html#salt.runners.jobs.list_jobs_filter 

and then passes the output to jobs.exit_success.

I am marking this as a feature request, PRs welcome.

Thanks,
Daniel
