### ISSUE TITLE
Broken Link in Docs

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#48818]
### Description of Issue/Question
on this page https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.removed

The link to "pkg.removed" links to "pkg.installed". Same for "pkg.purged".

**Comment by 4815162342lost** [comment]
All fine for me.

**Comment by gtmanfred** [comment]
I am unable to replicate this.  It is going to the link id anchor correctly.

**Comment by guettli** [comment]
I talk about this line:

> In version 2015.8.9, an ignore_epoch argument has been added to pkg.installed, pkg.removed, and pkg.purged states

"pkg.removed" links to "pkg.installed"

**Comment by gtmanfred** [comment]
Yup, it looks like it just needs to be fixed on those lines.

https://github.com/saltstack/salt/blob/2017.7/salt/states/pkg.py#L978

Thanks.
Daniel

**Comment by gtmanfred** [comment]
Fixed pending #48840
