### ISSUE TITLE
Multimaster salt deploy failover

### ISSUE THREAD

**Issue by yagnik** [saltstack/salt#48848]
### Description of Issue/Question
We are currently running multiple salt masters in our dc. We deploy our salt masters just the way we do with our apps i..e rolling deploy of all salt masters. In the case that a deploy happens on the master where a minion is connected and getting data from, that particular job fails due to salt timeout as expected. How does the core team solve this issue ? Is there a way I can tell salt to not accept any jobs ?

### Versions Report
```
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.10.6
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 20 2017, 18:23:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-128-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by garethgreenaway** [comment]
@yagnik Thanks for the report.  To clarify, are you seeing this behavior when you're deploying updates to Salt masters when a minion is in the middle of a Salt run?  Or is it that the minions are not switching over to the other masters if the one they're connected to disappears?

**Comment by yagnik** [comment]
@garethgreenaway this is in the middle of salt run, minions transfer over no problem.

**Comment by garethgreenaway** [comment]
@yagnik During the Salt run the minion is connected directly to the address of the Salt master, my suggestion would be to have either a load balancer or shared IP mechanism in front of the Salt masters.
@saltstack/team-core any other thoughts?

**Comment by yagnik** [comment]
@garethgreenaway correct me if I'm wrong but I expected that even if I put a lb in front, it won;t solve my problem in the following case:
- minion 1 sends publish.publish to minion 2 using the bus on master
- master dies before minion 2 has sent the reply back
- We failover to other master but it didn't know about the publish and therefore won't get response back to it.

This may not be true if minion sends events to all masters always, I assumed that is not the case.

**Comment by yagnik** [comment]
@gtmanfred I assume by failover you mean setting `master_type` to `failover`, which we don't, in that case will it publish to all masters ?

To implement retry logic on my side, I'll have to ask it to try the other master myself ? Salt won't take care of it ?

**Comment by gtmanfred** [comment]
correct, `master_type: failover`, so you should be sending the publish.publish to all masters afaik.

If you were using master_type: failover, you should just have to wait after getting your message back, and the minion should automatically failover, so if you don't get back a response and the publish.publish times out, sleep for however long your failover timer is, and then you should be able to send the publish.publish again to the new master.

**Comment by yagnik** [comment]
Odd, so in our case it should publish to all and both minions should move over no problem and publish should return no problem but it isn't, am I missing something ?

**Comment by gtmanfred** [comment]
hrm, maybe my understanding of the publish.publish and the multimaster is wrong.

yup, looking at the code it looks like it just publishes to the first master in the list.

```
    if via_master:
        if 'master_uri_list' not in __opts__:
            raise SaltInvocationError(message='Could not find list of masters \
                    in minion configuration but `via_master` was specified.')
        else:
            # Find the master in the list of master_uris generated by the minion base class
            matching_master_uris = [master for master
                    in __opts__['master_uri_list']
                    if '//{0}:'.format(via_master)
                    in master]

            if not matching_master_uris:
                raise SaltInvocationError('Could not find match for {0} in \
                list of configured masters {1} when using `via_master` option'.format(
                    via_master, __opts__['master_uri_list']))

            if len(matching_master_uris) > 1:
                # If we have multiple matches, consider this a non-fatal error
                # and continue with whatever we found first.
                log.warning('The `via_master` flag found \
                        more than one possible match found for {0} when evaluating \
                        list {1}'.format(via_master, __opts__['master_uri_list']))
            master_uri = matching_master_uris.pop()
    else:
        # If no preference is expressed by the user, just publish to the first master
        # in the list.
        master_uri = __opts__['master_uri']
```

But you can specify which master to publish.publish to with `via_master`, so you should publish to the first one, if youdon't get anything back, publish to the second one.
