### ISSUE TITLE
Short lived minions support

### ISSUE THREAD

**Issue by yagnik** [saltstack/salt#48857]
### Description of Issue/Question
We are looking to run salt inside containers only for the duration of the container. They act as our management containers, come online, do the task and then die. 
What do you think of the concept of short lived minions ? or do you think there is a better way to achieve this ?

**Comment by garethgreenaway** [comment]
There have been a number of people who gotten Salt running inside a container, I'm not sure if they were short lived containers but this could be a use case for a proxy minion.  

One potential issue would be key management, unless you were using the same pre-signed key each time you would need to have Salt auto-accept keys and could also potentially end up with a lot of unused keys to clean up from old short lived minions.

**Comment by yagnik** [comment]
Exactly facing the issue you listed:
- We currently have auto-accept set to true but aren;t able to clean up nicely. Any ideas on doing that ?
- What do you think of lease based acceptance which auto deletes the key ?

**Comment by yagnik** [comment]
Could you elaborate on how you'd use proxy minion for this ?
