### ISSUE TITLE
fileserver/roots msgpack errors

### ISSUE THREAD

**Issue by amuhametov** [saltstack/salt#48862]
### Description of Issue/Question
Getting random error:
Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: Unpack failed: error = 0
### Setup
```
worker_threads: 192
file_roots:
  base:
    - /srv/salt
```
### Steps to Reproduce Issue
Added traceback right after error message to payload.py:

Aug 01 17:57:54 saltmaster salt-master[50947]: [CRITICAL] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: Unpack failed: error = 0
Aug 01 17:57:54 saltmaster salt-master[50947]: Traceback (most recent call last):
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 138, in loads
Aug 01 17:57:54 saltmaster salt-master[50947]: ret = msgpack.loads(msg, use_list=True, encoding=encoding)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "msgpack/_unpacker.pyx", line 211, in msgpack._unpacker.unpackb
Aug 01 17:57:54 saltmaster salt-master[50947]: UnpackValueError: Unpack failed: error = 0
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/bin/salt-master", line 22, in <module>
Aug 01 17:57:54 saltmaster salt-master[50947]: salt_master()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 97, in salt_master
Aug 01 17:57:54 saltmaster salt-master[50947]: master.start()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 209, in start
Aug 01 17:57:54 saltmaster salt-master[50947]: self.master.start()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 599, in start
Aug 01 17:57:54 saltmaster salt-master[50947]: name='ReqServer')
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 333, in add_process
Aug 01 17:57:54 saltmaster salt-master[50947]: process.start()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 717, in start
Aug 01 17:57:54 saltmaster salt-master[50947]: super(SignalHandlingMultiprocessingProcess, self).start()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
Aug 01 17:57:54 saltmaster salt-master[50947]: self._popen = Popen(self)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/forking.py", line 126, in __init__
Aug 01 17:57:54 saltmaster salt-master[50947]: code = process_obj._bootstrap()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Aug 01 17:57:54 saltmaster salt-master[50947]: self.run()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 663, in _run
Aug 01 17:57:54 saltmaster salt-master[50947]: return self._original_run()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 760, in run
Aug 01 17:57:54 saltmaster salt-master[50947]: self.__bind()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 753, in __bind
Aug 01 17:57:54 saltmaster salt-master[50947]: name=name)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 333, in add_process
Aug 01 17:57:54 saltmaster salt-master[50947]: process.start()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 717, in start
Aug 01 17:57:54 saltmaster salt-master[50947]: super(SignalHandlingMultiprocessingProcess, self).start()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
Aug 01 17:57:54 saltmaster salt-master[50947]: self._popen = Popen(self)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/forking.py", line 126, in __init__
Aug 01 17:57:54 saltmaster salt-master[50947]: code = process_obj._bootstrap()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Aug 01 17:57:54 saltmaster salt-master[50947]: self.run()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 663, in _run
Aug 01 17:57:54 saltmaster salt-master[50947]: return self._original_run()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 916, in run
Aug 01 17:57:54 saltmaster salt-master[50947]: self.__bind()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 843, in __bind
Aug 01 17:57:54 saltmaster salt-master[50947]: self.io_loop.start()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
Aug 01 17:57:54 saltmaster salt-master[50947]: super(ZMQIOLoop, self).start()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 865, in start
Aug 01 17:57:54 saltmaster salt-master[50947]: handler_func(fd_obj, events)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
Aug 01 17:57:54 saltmaster salt-master[50947]: return fn(*args, **kwargs)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
Aug 01 17:57:54 saltmaster salt-master[50947]: self._handle_recv()
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
Aug 01 17:57:54 saltmaster salt-master[50947]: self._run_callback(callback, msg)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
Aug 01 17:57:54 saltmaster salt-master[50947]: callback(*args, **kwargs)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
Aug 01 17:57:54 saltmaster salt-master[50947]: return fn(*args, **kwargs)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
Aug 01 17:57:54 saltmaster salt-master[50947]: self.on_recv(lambda msg: callback(self, msg), copy=copy)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
Aug 01 17:57:54 saltmaster salt-master[50947]: yielded = next(result)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 665, in handle_message
Aug 01 17:57:54 saltmaster salt-master[50947]: ret, req_opts = yield self.payload_handler(payload)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 215, in wrapper
Aug 01 17:57:54 saltmaster salt-master[50947]: result = func(*args, **kwargs)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 873, in _handle_payload
Aug 01 17:57:54 saltmaster salt-master[50947]: 'clear': self._handle_clear}[key](load)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 903, in _handle_aes
Aug 01 17:57:54 saltmaster salt-master[50947]: return self.aes_funcs.run_func(data['cmd'], data)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 1611, in run_func
Aug 01 17:57:54 saltmaster salt-master[50947]: ret = getattr(self, func)(load)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 756, in file_list
Aug 01 17:57:54 saltmaster salt-master[50947]: ret.update(self.servers[fstr](load))
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 431, in file_list
Aug 01 17:57:54 saltmaster salt-master[50947]: return _file_lists(load, 'files')
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 319, in _file_lists
Aug 01 17:57:54 saltmaster salt-master[50947]: __opts__, form, list_cache, w_lock
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 132, in check_file_list_cache
Aug 01 17:57:54 saltmaster salt-master[50947]: return serial.load(fp_).get(form, []), False, False
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 168, in load
Aug 01 17:57:54 saltmaster salt-master[50947]: return self.loads(data)
Aug 01 17:57:54 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 150, in loads
Aug 01 17:57:54 saltmaster salt-master[50947]: traceback.print_stack()
Aug 01 17:57:55 saltmaster salt-master[50947]: [CRITICAL] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: Unpack failed: error = 0
Aug 01 17:57:55 saltmaster salt-master[50947]: Traceback (most recent call last):
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 138, in loads
Aug 01 17:57:55 saltmaster salt-master[50947]: ret = msgpack.loads(msg, use_list=True, encoding=encoding)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "msgpack/_unpacker.pyx", line 211, in msgpack._unpacker.unpackb
Aug 01 17:57:55 saltmaster salt-master[50947]: UnpackValueError: Unpack failed: error = 0
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/bin/salt-master", line 22, in <module>
Aug 01 17:57:55 saltmaster salt-master[50947]: salt_master()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 97, in salt_master
Aug 01 17:57:55 saltmaster salt-master[50947]: master.start()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 209, in start
Aug 01 17:57:55 saltmaster salt-master[50947]: self.master.start()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 599, in start
Aug 01 17:57:55 saltmaster salt-master[50947]: name='ReqServer')
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 333, in add_process
Aug 01 17:57:55 saltmaster salt-master[50947]: process.start()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 717, in start
Aug 01 17:57:55 saltmaster salt-master[50947]: super(SignalHandlingMultiprocessingProcess, self).start()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
Aug 01 17:57:55 saltmaster salt-master[50947]: self._popen = Popen(self)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/forking.py", line 126, in __init__
Aug 01 17:57:55 saltmaster salt-master[50947]: code = process_obj._bootstrap()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Aug 01 17:57:55 saltmaster salt-master[50947]: self.run()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 663, in _run
Aug 01 17:57:55 saltmaster salt-master[50947]: return self._original_run()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 760, in run
Aug 01 17:57:55 saltmaster salt-master[50947]: self.__bind()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 753, in __bind
Aug 01 17:57:55 saltmaster salt-master[50947]: name=name)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 333, in add_process
Aug 01 17:57:55 saltmaster salt-master[50947]: process.start()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 717, in start
Aug 01 17:57:55 saltmaster salt-master[50947]: super(SignalHandlingMultiprocessingProcess, self).start()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
Aug 01 17:57:55 saltmaster salt-master[50947]: self._popen = Popen(self)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/forking.py", line 126, in __init__
Aug 01 17:57:55 saltmaster salt-master[50947]: code = process_obj._bootstrap()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Aug 01 17:57:55 saltmaster salt-master[50947]: self.run()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 663, in _run
Aug 01 17:57:55 saltmaster salt-master[50947]: return self._original_run()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 916, in run
Aug 01 17:57:55 saltmaster salt-master[50947]: self.__bind()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 843, in __bind
Aug 01 17:57:55 saltmaster salt-master[50947]: self.io_loop.start()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
Aug 01 17:57:55 saltmaster salt-master[50947]: super(ZMQIOLoop, self).start()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 865, in start
Aug 01 17:57:55 saltmaster salt-master[50947]: handler_func(fd_obj, events)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
Aug 01 17:57:55 saltmaster salt-master[50947]: return fn(*args, **kwargs)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
Aug 01 17:57:55 saltmaster salt-master[50947]: self._handle_recv()
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
Aug 01 17:57:55 saltmaster salt-master[50947]: self._run_callback(callback, msg)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
Aug 01 17:57:55 saltmaster salt-master[50947]: callback(*args, **kwargs)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
Aug 01 17:57:55 saltmaster salt-master[50947]: return fn(*args, **kwargs)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
Aug 01 17:57:55 saltmaster salt-master[50947]: self.on_recv(lambda msg: callback(self, msg), copy=copy)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
Aug 01 17:57:55 saltmaster salt-master[50947]: yielded = next(result)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 665, in handle_message
Aug 01 17:57:55 saltmaster salt-master[50947]: ret, req_opts = yield self.payload_handler(payload)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 215, in wrapper
Aug 01 17:57:55 saltmaster salt-master[50947]: result = func(*args, **kwargs)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 873, in _handle_payload
Aug 01 17:57:55 saltmaster salt-master[50947]: 'clear': self._handle_clear}[key](load)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 903, in _handle_aes
Aug 01 17:57:55 saltmaster salt-master[50947]: return self.aes_funcs.run_func(data['cmd'], data)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 1611, in run_func
Aug 01 17:57:55 saltmaster salt-master[50947]: ret = getattr(self, func)(load)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 818, in dir_list
Aug 01 17:57:55 saltmaster salt-master[50947]: ret.update(self.servers[fstr](load))
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 445, in dir_list
Aug 01 17:57:55 saltmaster salt-master[50947]: return _file_lists(load, 'dirs')
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 319, in _file_lists
Aug 01 17:57:55 saltmaster salt-master[50947]: __opts__, form, list_cache, w_lock
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 132, in check_file_list_cache
Aug 01 17:57:55 saltmaster salt-master[50947]: return serial.load(fp_).get(form, []), False, False
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 168, in load
Aug 01 17:57:55 saltmaster salt-master[50947]: return self.loads(data)
Aug 01 17:57:55 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 150, in loads
Aug 01 17:57:55 saltmaster salt-master[50947]: traceback.print_stack()
Aug 01 17:57:56 saltmaster salt-master[50947]: [CRITICAL] Could not deserialize msgpack message.This often happens when trying to read a file not in binary modeTo see message payload, enable debug logging and retry. Exception: Unpack failed: error = 0
Aug 01 17:57:56 saltmaster salt-master[50947]: Traceback (most recent call last):
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 138, in loads
Aug 01 17:57:56 saltmaster salt-master[50947]: ret = msgpack.loads(msg, use_list=True, encoding=encoding)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "msgpack/_unpacker.pyx", line 211, in msgpack._unpacker.unpackb
Aug 01 17:57:56 saltmaster salt-master[50947]: UnpackValueError: Unpack failed: error = 0
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/bin/salt-master", line 22, in <module>
Aug 01 17:57:56 saltmaster salt-master[50947]: salt_master()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 97, in salt_master
Aug 01 17:57:56 saltmaster salt-master[50947]: master.start()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/cli/daemons.py", line 209, in start
Aug 01 17:57:56 saltmaster salt-master[50947]: self.master.start()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 599, in start
Aug 01 17:57:56 saltmaster salt-master[50947]: name='ReqServer')
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 333, in add_process
Aug 01 17:57:56 saltmaster salt-master[50947]: process.start()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 717, in start
Aug 01 17:57:56 saltmaster salt-master[50947]: super(SignalHandlingMultiprocessingProcess, self).start()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
Aug 01 17:57:56 saltmaster salt-master[50947]: self._popen = Popen(self)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/forking.py", line 126, in __init__
Aug 01 17:57:56 saltmaster salt-master[50947]: code = process_obj._bootstrap()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Aug 01 17:57:56 saltmaster salt-master[50947]: self.run()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 663, in _run
Aug 01 17:57:56 saltmaster salt-master[50947]: return self._original_run()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 760, in run
Aug 01 17:57:56 saltmaster salt-master[50947]: self.__bind()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 753, in __bind
Aug 01 17:57:56 saltmaster salt-master[50947]: name=name)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 333, in add_process
Aug 01 17:57:56 saltmaster salt-master[50947]: process.start()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 717, in start
Aug 01 17:57:56 saltmaster salt-master[50947]: super(SignalHandlingMultiprocessingProcess, self).start()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 130, in start
Aug 01 17:57:56 saltmaster salt-master[50947]: self._popen = Popen(self)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/forking.py", line 126, in __init__
Aug 01 17:57:56 saltmaster salt-master[50947]: code = process_obj._bootstrap()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Aug 01 17:57:56 saltmaster salt-master[50947]: self.run()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 663, in _run
Aug 01 17:57:56 saltmaster salt-master[50947]: return self._original_run()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 916, in run
Aug 01 17:57:56 saltmaster salt-master[50947]: self.__bind()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 843, in __bind
Aug 01 17:57:56 saltmaster salt-master[50947]: self.io_loop.start()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
Aug 01 17:57:56 saltmaster salt-master[50947]: super(ZMQIOLoop, self).start()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/ioloop.py", line 865, in start
Aug 01 17:57:56 saltmaster salt-master[50947]: handler_func(fd_obj, events)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
Aug 01 17:57:56 saltmaster salt-master[50947]: return fn(*args, **kwargs)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
Aug 01 17:57:56 saltmaster salt-master[50947]: self._handle_recv()
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
Aug 01 17:57:56 saltmaster salt-master[50947]: self._run_callback(callback, msg)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
Aug 01 17:57:56 saltmaster salt-master[50947]: callback(*args, **kwargs)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/stack_context.py", line 274, in null_wrapper
Aug 01 17:57:56 saltmaster salt-master[50947]: return fn(*args, **kwargs)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 191, in <lambda>
Aug 01 17:57:56 saltmaster salt-master[50947]: self.on_recv(lambda msg: callback(self, msg), copy=copy)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 230, in wrapper
Aug 01 17:57:56 saltmaster salt-master[50947]: yielded = next(result)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/transport/zeromq.py", line 665, in handle_message
Aug 01 17:57:56 saltmaster salt-master[50947]: ret, req_opts = yield self.payload_handler(payload)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib64/python2.7/site-packages/tornado/gen.py", line 215, in wrapper
Aug 01 17:57:56 saltmaster salt-master[50947]: result = func(*args, **kwargs)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 873, in _handle_payload
Aug 01 17:57:56 saltmaster salt-master[50947]: 'clear': self._handle_clear}[key](load)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 903, in _handle_aes
Aug 01 17:57:56 saltmaster salt-master[50947]: return self.aes_funcs.run_func(data['cmd'], data)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 1611, in run_func
Aug 01 17:57:56 saltmaster salt-master[50947]: ret = getattr(self, func)(load)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 818, in dir_list
Aug 01 17:57:56 saltmaster salt-master[50947]: ret.update(self.servers[fstr](load))
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 445, in dir_list
Aug 01 17:57:56 saltmaster salt-master[50947]: return _file_lists(load, 'dirs')
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 319, in _file_lists
Aug 01 17:57:56 saltmaster salt-master[50947]: __opts__, form, list_cache, w_lock
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 132, in check_file_list_cache
Aug 01 17:57:56 saltmaster salt-master[50947]: return serial.load(fp_).get(form, []), False, False
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 168, in load
Aug 01 17:57:56 saltmaster salt-master[50947]: return self.loads(data)
Aug 01 17:57:56 saltmaster salt-master[50947]: File "/usr/lib/python2.7/site-packages/salt/payload.py", line 150, in loads
Aug 01 17:57:56 saltmaster salt-master[50947]: traceback.print_stack()

I also appended each `msg` to /tmp/zzz:

[root@saltmaster master]# tail -7 /tmp/zzz|head -1|wc
      1     155  282625
[root@saltmaster master]# tail -6 /tmp/zzz|head -1|wc
      1     288  499713
[root@satlmaster master]# tail -5 /tmp/zzz|head -1|wc
      1     288  499713
[root@saltmaster master]# tail -4 /tmp/zzz|head -1|wc
      1     237  417793
 [root@saltmaster master]# tail -3 /tmp/zzz|head -1|wc
      1     200  368641
 [root@saltmaster master]# tail -2 /tmp/zzz|head -1|wc
      1      18   28673
As you can see the length of broken `msg` differs.

The `msg` itself seems to be a part of `/var/cache/salt/master/file_lists/roots/base.p`

### Versions Report
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 16.0.4
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.3
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by garethgreenaway** [comment]
@amuhametov Thanks for the report.  Can you check if any of the files under /var/cache/salt are zero length?

**Comment by amuhametov** [comment]
/var/cache/salt/minion/module_refresh
and everything under /var/cache/salt/master/syndics/

**Comment by amuhametov** [comment]
@garethgreenaway any ideas on this? could this be a race between workers?

**Comment by amuhametov** [comment]
I suppose the problem is within fileserver/__init__.py wait_lock
