### ISSUE TITLE
digital_ocean driver not working/digitalocean does work

### ISSUE THREAD

**Issue by jjcroftiv** [saltstack/salt#48878]
### Description of Issue/Question
I am using salt-cloud, and have a DigitalOcean provider configured.  It previously worked as 'digital_ocean', but now generates the error:
The cloud driver, 'digital_ocean', configured under the 'coderz-do' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'digital_ocean' driver.
However, changing the driver to digitalocean does work.  It's a simple fix, but I am posting the issue to hopefully save someone else the frustration.

### Setup
`coderz-do:`
`   driver: digitalocean`
`   personal_access_token: 'my token'`
`   ssh_key_file: /etc/salt/keys/salt.pem`
`   ssh_key_names: salt`
`   securitygroup: default`

### Steps to Reproduce Issue
Change driver from 'digitalocean' to 'digital_ocean'

### Versions Report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-131-generic
         system: Linux
        version: Ubuntu 16.04 xenial

Thank you -
John

**Comment by gtmanfred** [comment]
This will be fixed in 2018.3.3

https://github.com/saltstack/salt/pull/48188
