### ISSUE TITLE
Ping all Minions that belong to one group, except those that appear in another group

### ISSUE THREAD

**Issue by Annnetta** [saltstack/salt#48886]
Hi all,
I have a question. Is it possible to execute a function for all Minions that belong to one group, except those that are already in another group?

For example I have this groups in /etc/salt/master:
```
nodegroups:
  laptops: terminatorsmbp2.cosmo
  internal_users: windows-minion, ubuntu-hanna-minion, terminatorsmbp2.cosmo, ubuntu-minion2
```
I would like to ping every machine that is in internal_users and not a laptop => windows-minion, ubuntu-hanna-minion, ubuntu-minion2

I saw that something like that is possible for minions if manage them by id:
`salt -C '* and not web-dc1-srv' test.ping`

Does exist the same thing for groups?

**Salt version** is : 2018.3.1 (Oxygen)

Thanks in advance,
Hanna

**Comment by Annnetta** [comment]
Hi Daniel, 

Unfortunately that doesn't work, the output is:
```
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

**Comment by gtmanfred** [comment]
hrm, well that is no good, it looks like nodegroups are not expanded in the compound matcher, so that is what is preventing this.

So this will be basically a duplicate of https://github.com/saltstack/salt/issues/38169

**Comment by gtmanfred** [comment]
Could you try.

`salt -C 'internal_users and not laptops'` 

?

Thanks,
Daniel

**Comment by Annnetta** [comment]
Here I have the same error:
```
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
```

I will take a look on the issue you have mentioned.

**Comment by Annnetta** [comment]
@gtmanfred, I don’t think that it is related to the issue you have mentioned.

I can execute
`salt -N 'internal_users' test.ping`
And it gives the right output.

Also I have` -match: nodegroup `in top.sls. And I can apply a state correctly.

I have found in the documentation that:

    The N@ classifier cannot be used in compound matches within the CLI or top file, it is only recognized in the nodegroups master config file parameter.

So normally
`salt -C 'N@internal_users' `won’t work and it doesn’t work.
Please, correct me if I am mistaken.

What I am looking for is something like
`salt -N ‘internal_users and not laptops’ test.ping`
But that doesn’t work. Maybe it simply doesn’t exist for now?

Thanks,
Hanna

**Comment by gtmanfred** [comment]
Yes, but the problem is, all of the `and`, `not`, `or` stuff is only usable in compound matches, which Nodegroups are not useable in.  Which is the problem listed in this issue https://github.com/saltstack/salt/issues/38169

The only way you would be able to do this, is if you specified another nodegroup

```
nodegroups:
  laptops: terminatorsmbp2.cosmo
  internal_users: windows-minion, ubuntu-hanna-minion, terminatorsmbp2.cosmo, ubuntu-minion2
  internal_users_and_not_laptops: 'N@internal_users and not N@laptops'
```

Then you can use the new group, but you also have to restart the master service, so you can't just do this on the fly.

The other thing you could do is use pillars to target minions, and give them roles, that would allow you to target pillars on the fly.

```
top:
  laptops:
    - match: nodegroup
    - laptop
  internal_users:
    - match: nodegroup
    - internal_user
```
```
internal_users: true
```
```
laptop: true
```

Then you can target them with pillars.

```
salt -C 'I@internal_user:True and not I@laptop`
```

Those are your options right now.

Daniel
