### ISSUE TITLE
shell=cmd is not usable via module, works via CLI (2018.3.1 Windows 2016)

### ISSUE THREAD

**Issue by damntoken** [saltstack/salt#48887]
### Description of Issue/Question
I found a weird behaviour with **cmd.run shell='cmd'** with Win 2016 client.

### Steps to Reproduce Issue
`salt 'client' cmd.run_all cmd='echo ABC' shell='cmd'`
Returns ABC as expected.
```
    ----------
    pid: 6892
    retcode:  0
    stderr:
    stdout:  ABC
```
But inside custom module.

```
	runtest=__salt__['cmd.run_all'](cmd='echo ABC',shell='cmd')
	ret = {
		'runtest retrun': str(runtest['retcode']) +'|'+ runtest['stderr'] +'|'+ runtest['stdout'],
		}
```

Results always in :  **ERROR: Unable to run command 'echo ABC' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -1, u'env': bla bla bla.. reason: command not found.**
I checked env variables are all correct.
It also seemed to me that the ret output format defined 'runtest retrun..' was completely ignored by the output.

`cmd='echo ABC > C:\\salt\\var\\log\\salt\\test1.txt',shell='cmd'`
Echo to file also fails via module, but works via CLI.
`cmd='ipconfig',shell='cmd'`
Works direct and from module. The IP info is displayed.
`cmd='echo ABC > C:\\salt\\var\\log\\salt\\test1.txt',shell='**powershell**'`
Works direct and from module via powershell.

### Versions Report
Client 2018.3.1 Windows 2016, 
Master 2018.3.2 Ubuntu 16.04
both x64 and py 2.7

**Comment by gtmanfred** [comment]
@dwoz when you get a minute, could you look into this?

Thanks,
Daniel

**Comment by morganwillcock** [comment]
I think is is because if you want to use features within the shell (i.e. call the shell command echo instead of try to find echo.exe and run it, use pipes and redirection, etc.) you need to set `python_shell = True`.
