### ISSUE TITLE
unresponsive minion when disk is full (windows/linux)

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#48894]
### Description of Issue/Question
When the partition that minion's cache is full the minion is unresponsive.
Minion is unable to create the jid file hence the issue and the exception if the log file partition is not full.

Ideally the minion should respond to the master with a notification that disk is full.
Also it would be nice if minion could run synchronous commands like cmd.run without writing anything to the cache in order for user to be able to delete some files in order to clear disk space.

### Setup
make the partition that minion cache is located full.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Should be all versions but I'm under 2016.11.9 and haven't tested the rest.

**Comment by gtmanfred** [comment]
As with the last time you brought this up

```
We had an internal discussion that we did not consider this particular request a bug, given the pervasive nature of salt's need for disk access this would prove to be an impossible endeavor to completely alleviate.
```

Closing as a duplicate.

https://github.com/saltstack/salt/issues/40641#issuecomment-293406952

Thanks,
Daniel

Internal log from April 11th, 2017.

```
Thomas Hatch [3:18 PM]
blech
making programs magically run with a full disk is in and of itself a nightmare
Thomas Hatch [4:09 PM]
so basically, the response to that issue should be something like:
we will accept pull requests to alleviate a disk full failure, but given the pervasive nature of salt's need for disk access this would prove to be an impossible endeavor to completely alleviate.
Mike Place [4:11 PM]
This is going to result in somebody trying to queue jobs in memory and then me breaking my laptop over my head.
IMHO we should close issues like that as `wontfix`
```

**Comment by tsaridas** [comment]
You have a better memory than me.

Thank you for reminding me.

My idea would be to catch the exception and return an event to the minion to show that disk is full.

I understand that keeping jobs in memory is a hassle but it doesn't have to be that way. Maybe we can just have a config options for users to allow not writing jobs to disk in case of something like this happens. sync commands should work fine if we catch the exception that jid was not able to be written to disk and pass.

**Comment by gtmanfred** [comment]
We would accept a PR, but it is not something we are going to implement.
