### ISSUE TITLE
Invalid grain fqdn_ip4 resolution

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#48906]
### Description of Issue/Question
As I understand https://github.com/saltstack/salt/blame/develop/salt/utils/network.py#L196 the idea is to get fqdn based on RevDNS and then overwrite it with hostname if it is possible to obtain ip of hostname. But current code does only the first thing and because of that grain fqdn_ip4 could be unavailable in some situations when RevDNS != hostname.

### Steps to Reproduce Issue
Set RevDNS for something different than hostname.

### Versions Report
Salt Version:
           Salt: 2017.7.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.7 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-573.26.1.el6.x86_64
         system: Linux
        version: CentOS 6.7 Final

**Comment by Ch3LL** [comment]
Thanks for the PR! We always appreciate that :)
