### ISSUE TITLE
Unclear distinction between publisher_acl and external_auth in master.conf

### ISSUE THREAD

**Issue by Arabus** [saltstack/salt#48915]
### Description of Issue/Question
When configuring salt for use by a non-root user or for use with the salt-api there is some confusion whether to use the external_auth or publisher_acl directives in the master.conf.

While there is a distinction at https://docs.saltstack.com/en/latest/topics/eauth/access_control.html#when-to-use-each-authentication-system the respective subpages https://docs.saltstack.com/en/latest/ref/publisheracl.html and https://docs.saltstack.com/en/latest/topics/eauth/index.html give no such clue.

I propose adding the respective section from the access_control page to either subpages top descriotion part to clarify things.

**Comment by Ch3LL** [comment]
yeah that could definitely help clear things up, great find. Seems you have a grasp on the fix we definitely would welcome a PR if you want to take a go at it.
