### ISSUE TITLE
pkg.install doesn't return current version

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#48931]
### Description of Issue/Question
From https://groups.google.com/forum/#!topic/salt-users/IfuYCGFiw34

Usually, when installing a package like "vlc" on a windows minion, I get the version of the installed program (or both: the versions  of the old an the newly installed package): 
```
salt 'winpc2017' pkg.refresh_db
winpc2017: 
    ---------- 
    failed: 
        0 
    success: 
        8 
    total: 
        8 
```
```
salt 'winpc2017' pkg.install vlc 
winpc2017: 
    ---------- 
    vlc: 
        ---------- 
        current: 
            3.0.3 
```

After an upgrade from
2017.7.4  (Salt-Minion-2017.7.4-Py2-AMD64-Setup.exe)  to 
2018.3.2  (Salt-Minion-2018.3.2-Py2-AMD64-Setup.exe) 

I do NOT get the installed version of vlc any more: 
```
salt 'winpc2018' pkg.install vlc 
winpc2018: 
    ---------- 
```

### Versions Report
21018.3 on Windows

**Comment by damon-atkins** [comment]
This is caused by the delay in the registering updating after the installer has complete. In 2019+ version this is already fixed.  The fix is to wait/sleep a bit before calling list_pkgs after the install to give the registry a chance to update. Simple sleep(3) would catch 99% of the cases.

**Comment by damon-atkins** [comment]
The following was without the sleep added before `old = list_pkgs`. It worked in every case. I was hoping the registry would at least once take to long to update. 
```
C:\salt>salt-call pkg.list_available vlc
local:
    - 2.2.6
    - 2.2.8
    - 3.0.0
    - 3.0.1
    - 3.0.2
    - 3.0.3

C:\salt>salt-call pkg.install vlc version=3.0.0
local:
    ----------
    vlc:
        ----------
        new:
            3.0.0
        old:
            2.2.6

C:\salt>salt-call pkg.install vlc version=3.0.1
local:
    ----------
    vlc:
        ----------
        new:
            3.0.1
        old:
            3.0.0

C:\salt>salt-call pkg.install vlc version=3.0.2
local:
    ----------
    vlc:
        ----------
        new:
            3.0.2
        old:
            3.0.1

C:\salt>salt-call pkg.install vlc version=3.0.3
local:
    ----------
    vlc:
        ----------
        new:
            3.0.3
        old:
            3.0.2

C:\salt>salt-call pkg.install vlc version=3.0.4
[ERROR   ] win_pkg.install Version 3.0.4 not found for package vlc
local:
    ----------
    vlc:
        ----------
        not found:
            3.0.4

C:\salt>salt-call pkg.install vlc version=3.0.0
local:
    ----------
    vlc:
        ----------
        new:
            3.0.0
        old:
            3.0.3
```

**Comment by twangboy** [comment]
@damon-atkins You're describing a different problem here. The issue is with pkg.install with an existing installation of the same version.

**Comment by damon-atkins** [comment]
Based on your comment above. Here is an example of it, showing no changes in version no results return.
```
# salt-call -l info  pkg.version curl
[INFO    ] cmdmod._run Executing command [u'rpm', u'-qa', u'--queryformat', u'%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)_|-%{INSTALLTIME}'] in directory '/root'
local:
    7.59.0-5.fc28

# salt-call -l info  pkg.install curl  version=7.59.0-5.fc28
[INFO    ] cmdmod._run Executing command [u'rpm', u'-qa', u'--queryformat', u'%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)_|-%{INSTALLTIME}'] in directory '/root'
[WARNING ] rpm.version_cmp rpmdevtools is not installed, please install it for more accurate version comparisons
[INFO    ] cmdmod._run Executing command [u'systemd-run', u'--scope', u'dnf', u'-y', u'--best', u'--allowerasing', u'install', u'curl-7.59.0-5.fc28'] in directory '/root'
[INFO    ] cmdmod._run Executing command [u'rpm', u'-qa', u'--queryformat', u'%{NAME}_|-%{EPOCH}_|-%{VERSION}_|-%{RELEASE}_|-%{ARCH}_|-(none)_|-%{INSTALLTIME}'] in directory '/root'
local:
    ----------
```

**Comment by ruko42** [comment]
The documentation of https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_pkg.html for 2018.3.2 says:

salt.modules.win_pkg.install(name=None, refresh=False, pkgs=None, **kwarg
...
Returns:	Return a dict containing the new package names and versions
If the package is installed by pkg.install:
{'<package>': {'old': '<old-version>',
                    'new': '<new-version>'}}
If the package is already installed:
{'<package>': {'current': '<current-version>'}}


.... which is different to the so called "standard" in other modules !
I would prefer to get the installed version, and NOT to do an extra pkg.version
Maybe a solution would be to have a parameter (perhaps "showinstalled (bool)" ) with all pkg.install... ?

... and it is  pkg.install  and not  pkg.installed ,  isn't it?

**Comment by damon-atkins** [comment]
Hi ruko42
The data is feed into the rest of the salt system i.e. `pkg.installed` state calls `pkg.install` `pkg.list_pkgs` etc. All platforms should return the data in the correct format expected by `pkg.installed`. And hence Windows needs needs to conform.  The doco should have been update to remove the section on `current`  The release notes covered this change.  

What are you using in your sls files module pkg.install or state pkg.installed?

The following is the behaviour for the current releases of 2016, 2017 and 2018 since December/January.
```
#salt win10test state.high {'grepwin':{'pkg':['installed']}}
win10test:
    ----------
    pkg_|-grepwin_|-grepwin_|-installed:
        ----------
        __id__:
            grepwin
        __run_num__:
            0
        __sls__:
            None
        changes:
            ----------
            grepwin:
                ----------
                new:
                    1.6.682
                old:
        comment:
            The following packages were installed/updated: grepwin
        duration:
            28764.621
        name:
            grepwin
        result:
            True
        start_time:
            02:49:50.644832

# salt win10test state.high {'grepwin':{'pkg':['installed']}}
win10test:
    ----------
    pkg_|-grepwin_|-grepwin_|-installed:
        ----------
        __id__:
            grepwin
        __run_num__:
            0
        __sls__:
            None
        changes:
            ----------
        comment:
            All specified packages are already installed
        duration:
            28122.063
        name:
            grepwin
        result:
            True
        start_time:
            02:51:30.499313

```
Your request should be for a debate on the output expected from all platforms rather than just Windows.  If there is a better way, then all platforms need to be updated.

**Comment by damon-atkins** [comment]
Hi @ruko42
The data is feed into the rest of the salt system i.e. `pkg.installed` state calls `pkg.install` `pkg.list_pkgs` etc. All platforms should return the data in the correct format expected by `pkg.installed`. And hence Windows should conform.  
https://docs.saltstack.com/en/latest/topics/releases/2017.7.3.html#pkg-execution-module
``Some execution module functions results, now behave more like their Unix/Linux versions.`` 

What are you using in your sls files module pkg.install or state pkg.installed?

The following is the behaviour for the current releases of 2016, 2017 and 2018 since December/January (might of been earlier than this).
```
#salt win10test state.high {'grepwin':{'pkg':['installed']}}
win10test:
    ----------
    pkg_|-grepwin_|-grepwin_|-installed:
        ----------
        __id__:
            grepwin
        __run_num__:
            0
        __sls__:
            None
        changes:
            ----------
            grepwin:
                ----------
                new:
                    1.6.682
                old:
        comment:
            The following packages were installed/updated: grepwin
        duration:
            28764.621
        name:
            grepwin
        result:
            True
        start_time:
            02:49:50.644832

# salt win10test state.high {'grepwin':{'pkg':['installed']}}
win10test:
    ----------
    pkg_|-grepwin_|-grepwin_|-installed:
        ----------
        __id__:
            grepwin
        __run_num__:
            0
        __sls__:
            None
        changes:
            ----------
        comment:
            All specified packages are already installed
        duration:
            28122.063
        name:
            grepwin
        result:
            True
        start_time:
            02:51:30.499313

```
Your request should be for a debate on the output expected from all platforms rather than just Windows.  If there is a better way, then all platforms need to be updated.
