### ISSUE TITLE
kernelrelease grains and Oracle uptrack technology

### ISSUE THREAD

**Issue by 4815162342lost** [saltstack/salt#48938]
Hello,

We are using Oracle Linux 7 with **uptrack**.[ Uptrack technology ](https://ksplice.oracle.com/uptrack/guide)may able install new kernel 'on fly' without downtime and reboot.

But after that 'uname -r' command show booted, but 'not running' kernel version. For see real running kernel need run the 'uptrack-uname -r' command.

Example:
```
sudo salt oracle grains.get kernelrelease
oracle: 
    4.1.12-61.1.18.el7uek.x86_64
 
uname -r
4.1.12-61.1.18.el7uek.x86_64
 
uptrack-uname -r
4.1.12-112.14.2.el7uek.x86_64
```

Could you please investigate this case? is it an issue?

Salt-minion version is 2018.3.0 (Oxygen).

Thanks in advance.

**Comment by garethgreenaway** [comment]
@4815162342lost Thanks for the report.  If I understand correctly, with Oracle Linux 7 for providing the current running kernel Salt should be using `uptrack-uname -r` instead of `uname -r` when populating the `kernelrelease` grain.

**Comment by 4815162342lost** [comment]
Hello @garethgreenaway,

Thanks for your interesting.

Not sure, uptrack should be installed and enabled (it is not free feature, need buy Oracle support).
And command should be something like to this:
`uptrack-uname -r 2>/dev/null || uname -r`

But i am really not sure. I do not have test environment for 'play'. I do not know what if 'uptrack installed, but is not enabled; what if standard RedHat kernel booted' and etc.

Sorry. I have only critical prod. environments.

**Comment by MTecknology** [comment]
It sounds like, if uptrack is present, then there should be a new grain populated, since the kernel the system booted with could still be important information. Without valid test systems, it's pretty much impossible to write this feature without expecting it to not work correctly.

If you'd be interested in arranging for me to have access to a dev box with this feature, I'd be happy to see about writing a proper grain for it. Otherwise, it looks like it'll be up to you to write it.

**Comment by 4815162342lost** [comment]
Hello,

Above i was not very right, ksplice have a 30-days trial version:
https://www.ksplice.com/try/trial

is it OK for you? Is it suitable? 

Thanks in advance.

**Comment by MTecknology** [comment]
Ksplice doesn't support running on CentOS and I don't have access to a RHEL or Oracle-branded RHEL system. Neither are free beer. I'm also not interested in signing up for an Oracle account just so I can download a trial of more not-so-free software.

I could help you write a grain and help you get it into salt; I could even write it given a test system, but I'm not going to go through the effort/headache of dealing with licensing garbage to do it.
