### ISSUE TITLE
Problem with importing stock price on yahoo through http://ichart.finance.yahoo.com/table.csv

### ISSUE THREAD

**Issue by ThieryLebeau** [saltstack/salt#48937]
Hi everyone!
I have 2 problems with this code for which I want your help please. 

# Beginning of code snippet:
# Construct the Yahoo URL with the correct integer query parameters
    # for start and end dates. Note that some parameters are zero-based!
    ticker_tup = (
        ticker, start_date[1]-1, start_date[2], 
        start_date[0], end_date[1]-1, end_date[2], 
        end_date[0]
    )
    yahoo_url = "http://ichart.finance.yahoo.com/table.csv"
    yahoo_url += "?s=%s&a=%s&b=%s&c=%s&d=%s&e=%s&f=%s"
    yahoo_url = yahoo_url % ticker_tup

    # Try connecting to Yahoo Finance and obtaining the data
    # On failure, print an error message.
    try:
        yf_data = requests.get(yahoo_url).text.split("\n")[1:-1]
        prices = []
        for y in yf_data:
            p = y.strip().split(',')
            prices.append( 
                (datetime.datetime.strptime(p[0], '%Y-%m-%d'),
                p[1], p[2], p[3], p[4], p[5], p[6]) 
            )
    except Exception as e:
        print("Could not download Yahoo data: %s" % e)
    return prices

# End of code snippet 

Problem 1: 
I cannot obtain stock price from yahoo finance using "http: // ichart.finance.yahoo.com/table.csv" anymore. 

Problem 2: When I run my code below I also receive an error message saying that "local variable 'prices' referenced before assignment".

Any insight will be appreciated. 
Thank you.

**Comment by gtmanfred** [comment]
1) it looks like you are using requests, and not salt's http.query, so i would say you should talk to the requests guys about this, or figure out if something went wrong with the yahoo api.

2) If there is an exception, where it cannot download the data, you won't have set prices, and that is probably where your error is?  Set prices before the try statement, and it will probably help

You could probably remove the try except block, and see if requests gives you an error.

**Comment by garethgreenaway** [comment]
@ThieryLebeau Are you attempting to run this with Salt, perhaps in a custom Salt module?  It's difficult to see how this fits based on the code snippet above.
