### ISSUE TITLE
salt-ssh: Cannot escape '{' in case of list merging 

### ISSUE THREAD

**Issue by hkriszh** [saltstack/salt#48944]
### Setup

In this use case I want to merge 2 files, but it's not possible if some values contain '{'. See:

```
vagrant@salt:~/salt-ssh$ sudo salt-ssh managed state.apply state_with_template_merge
[CRITICAL] Rendering SLS 'base:state_with_template_merge' failed: while parsing a flow mapping
  in "<unicode string>", line 7, column 19:
          - settings: {u'key': u'value{}value'}
                      ^
expected ',' or '}', but got '{'
  in "<unicode string>", line 7, column 35:
          - settings: {u'key': u'value{}value'}
                                      ^
managed:
    - Rendering SLS 'base:state_with_template_merge' failed: while parsing a flow mapping
        in "<unicode string>", line 7, column 19:
                - settings: {u'key': u'value{}value'}
                            ^
      expected ',' or '}', but got '{'
        in "<unicode string>", line 7, column 35:
                - settings: {u'key': u'value{}value'}
                                            ^
```
I tried to escape '{' in many ways, but no luck. 

Here you can find my configuration:

```
vagrant@salt:~/salt-ssh/states$ ls -lh 
total 12K
-rw-rw-r-- 1 vagrant vagrant  20 Aug  6 07:34 defaults.yaml
-rw-rw-r-- 1 vagrant vagrant  25 Aug  6 06:53 generic_template.jinja
-rw-rw-r-- 1 vagrant vagrant 237 Aug  6 07:57 state_with_template_merge.sls
```
```
vagrant@salt:~/salt-ssh/states$ cat state_with_template_merge.sls 
{% import_yaml "defaults.yaml" as defaults  %}
{% set settings = salt['pillar.get']('default', default=defaults, merge=True) %}
/tmp/testfile:
  file.managed:
    - source: salt://generic_template.jinja
    - context:
      - settings: {{settings}}
```

```
vagrant@salt:~/salt-ssh/states$ cat defaults.yaml 
key: 'value{}value'
```
```
vagrant@salt:~/salt-ssh/states$ cat generic_template.jinja 
## some generic header

{{settings|yaml(False)}}
```

### Steps to Reproduce Issue
Use the 3 provided files and apply the state. 

### Versions Report
salt-ssh --version
salt-ssh 2018.3.2 (Oxygen)

This is a vagrant test environment based on [this](https://docs.saltstack.com/en/getstarted/ssh/system.html) how-to.

**Comment by garethgreenaway** [comment]
Seems like a YAML quirk, similar to this https://github.com/saltstack/salt/issues/7650
@saltstack/team-core Anyone have any thoughts on this?

**Comment by hkriszh** [comment]
Yes, it seems something similar to that. Unfortunately none of the mentioned workarounds worked.

**Comment by redbaron4** [comment]
I ran into a similar issue. In my case the `json` filter helped. Can you try to modify the merge sls like so?

vagrant@salt:~/salt-ssh/states$ cat state_with_template_merge.sls 
{% import_yaml "defaults.yaml" as defaults  %}
{% set settings = salt['pillar.get']('default', default=defaults, merge=True) %}
/tmp/testfile:
  file.managed:
    - source: salt://generic_template.jinja
    - context:
      - settings: {{settings|json}}

**Comment by terminalmage** [comment]
Yeah, you need to use a filter for this, the `u` prefix in Python 2 unicode strings is not valid YAML.

The `json` filter is one that we wrote, but `tojson` (Jinja 2.9+) handles non-ascii unicode better than that, so it's probably the best solution. 2018.3.3 and later will have a port of this filter bundled with Salt itself, which will be used when the version of Jinja is older than 2.9 to provide this functionality.

Long term, we will probably point our own `json` filter at `tojson` because of the better unicode support.

**Comment by redbaron4** [comment]
Thanks for explaining this @terminalmage 

I think my formula (which had a similar issue) worked correctly atleast in 2017.7.0 but broke in 2018.3.0 (Both on Python-2.7)
