### ISSUE TITLE
[Feature Request] salt-key delete by keystate

### ISSUE THREAD

**Issue by tbennett6421** [saltstack/salt#48951]
#### Background 
Our team uses a template to deploy linux software, this template then runs a `prep-tool` that generates new ssh keys, joins active directory, installs and configures salt-minion. We use this goldenmaster for all production/development work. Only when it goes into production does the salt-key get accepted on the master side.

As a result, with rapid prototyping this list of unaccepted/rejected keys can get large. We have to go back and clear each key out manually. We'd like to request the ability to delete, reject, deny by the state of the key on the master side.

### Description of Issue/Question
salt-key --list un will show a list of unaccepted keys
we would like to be able to do something along the lines of...
`salt-key --delete un`
`salt-key --delete state=un`
`salt-key --state un --delete`
`salt-key -C 'state:un' --delete`
https://docs.saltstack.com/en/latest/ref/cli/salt-key.html

### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.3
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-127-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@tbennett6421 Thanks for the report.  This would be a useful feature to have.  Approving for a future feature addition.
