### ISSUE TITLE
host.only creates invalid host entries with garbage 

### ISSUE THREAD

**Issue by jagguli** [saltstack/salt#48967]
### Description of Issue/Question
Given I am collecting host entries using salt mine
and updating hosts using host.only
then I ocassionally I get garbage in my hosts file.

Expected

Host.only should do some validation on input data

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.2.3
       dateutil: 2.6.1
      docker-py: 1.10.6
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.1.6

System Versions:
           dist: debian 9.3
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-5-amd64
         system: Linux
        version: debian 9.3

**Comment by gtmanfred** [comment]
Can you provide some example states to replicate this? and also the garbage output you are seeing would be useful.

Daniel

**Comment by jagguli** [comment]
here's the state, as for the output it looks like there is some binary daa mixed in, the issue could be in the salt mine also , I'm trying to see if there is any thing inmy state that might cause it

```#!pyobjects
# Local Variables:
# mode: python
# End:
# flake8: noqa=F821
import logging
from pprint import pformat
from itertools import chain

loopbacks = {
    "127.0.0.1": [
        "localhost",
        "%s.localdomain" % grains('id'),
    ],
    "::1": [
        "localhost",
        "%s.localdomain" % grains("id"),
        "ip6-localhost",
        "ip6-loopback",
    ],
    "ff02::1": [
        "ip6-allnodes",
    ],
    "ff02::2": [
        "ip6-allrouters",
    ],
}

overrides = pillar('ip_overrides', {})
managed_hosts = salt.mine.get('*', 'network.ip_addrs')
current_hosts = salt.hosts.list_hosts()
remove_hosts = set([])
extra_hosts = {server: pillar('extra_hosts:' + server) for server in managed_hosts.keys()}

logging.info("overrides=%s", pformat(overrides))
logging.info("managed_hosts=%s", pformat(managed_hosts))
logging.info("current_hosts=%s", pformat(current_hosts))
logging.info("extra_hosts=%s", pformat(extra_hosts))

for ip, servers in current_hosts.items():
    if ip not in chain.from_iterable(
        (
            chain.from_iterable(managed_hosts.values()),
            chain.from_iterable(extra_hosts.values()),
            loopbacks.keys(),
            overrides.values(),
        )
    ):
        remove_hosts.add(ip)

logging.info("remove_hosts=%s", pformat(remove_hosts))


for loopback, addrs in loopbacks.items():    
    Host.only(
        loopback,
        hostnames=addrs
    )

deployments = salt.mine.get('*', 'deployments')
deployment = grains('deployment:name')
salt_master = pillar('salt:master:host')

for server, addrs in managed_hosts.items():
    if (
            deployments.get(server, {}).get('name') != deployment and
            grains('id') != salt_master and
            server != salt_master
            ):
        pass
    #if (
    #    server.startswith('hawk') and not
    #    grains('id').startswith('hawk') and
    #    grains('id') != pillar('salt:master:host')
    #    ):
    #      pass
    else:
        Host.only(
            overrides.get(server, addrs[0]),
            hostnames=[
                "%s.streethawk.com" % server,
                server,
            ] + [
                extra for extra in pillar('extra_hosts:' + server)
            ]
        )


for ip in remove_hosts:
    for server in set(current_hosts[ip]):
        Host.absent("remove_%s_%s" % (server, ip), name=server, ip=ip)
```

**Comment by gtmanfred** [comment]
And when the binary garbage gets added to one of the hostfiles, where does it get added? at the end, with the hostname, with the ip address?

Can you provide an example /etc/hosts file?

**Comment by jagguli** [comment]
It gets added in between, I'll save the file the next time it happens its an intermittent issue.

**Comment by gtmanfred** [comment]
That would be great thanks!

Once i can see it, i can have a better idea of where to look. My best guess is that is something in the  mine that is behaving badly, your state looks fine.

**Comment by gtmanfred** [comment]
hrm, it looks like it is adding it between each character, once i remove the representation of the binary, i get.

```
11.0.1.7           bison-riak0
```

Does that look familiar to you? is it something you are still using or is it something extra that might be left over in the mine?  It is odd that the binary is added between every line.

Thanks,
Daniel

**Comment by jagguli** [comment]
Looking at the issue referenced by @sunyq I think we can rule out the possibility of this being related to mine. 

@gtmanfred yes that line is what is expected

**Comment by jagguli** [comment]
There is a lot of low level byte handling going on in the hosts module, not sure why, I suspect the issue is in rm_host. I'll try to dig deeper but im inclined to write a custom module using https://github.com/jonhadfield/python-hosts which seem to be a more through implementation
