### ISSUE TITLE
cron.present fails when no prior crons are defined

### ISSUE THREAD

**Issue by rso-support** [saltstack/salt#48984]
### Setup
'/etc/salt/minion.d/minionCheck.sh':
  cron.present:
    - user: root
    - minute: 0
    - hour: '*/4'

### Steps to Reproduce Issue
use  above sls on a host with a user with no existing cron

### Versions Report

--- master ----
salt --versions-report
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.3
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, Feb 20 2018, 09:19:12)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo

--- minon ---

Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.7 Santiago
         locale: UTF-8
        machine: x86_64
        release: 3.8.13-118.3.2.el6uek.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.7 Santiago

**Comment by rso-support** [comment]
This behavior seems to only be present in RHEL6.X hosts

minon debug log attached

[minion-debug.txt](https://github.com/saltstack/salt/files/2268198/minion-debug.txt)

**Comment by rso-support** [comment]
This also _seems_ to be killing the minion (the following was witnessed on the terminal after the minion exited)

INFO    ] Shutting down the Salt Minion
[DEBUG   ] Stopping the multiprocessing logging queue listener
[DEBUG   ] closing multiprocessing queue
[DEBUG   ] joining multiprocessing queue thread
[DEBUG   ] Stopped the multiprocessing logging queue listener
The Salt Minion is shutdown. Minion received a SIGTERM. Exited.


**< - minion exited, control returned to terminal - >**

[root@hostanme ~]# ps -ef | grep salt
root      3605     1  0 22:02 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -l debug
root      3606  3605  0 22:02 ?        00:00:00 /bin/bash -c salt-call state.apply |mail -s "[MINION] STARTUP RUN - hostanme.localdomain.com" ot-uxlxinfrastructure@localdomain.com
root      3607  3606  4 22:02 ?        00:00:01 /usr/bin/python2.7 /usr/bin/salt-call state.apply
root      4701  3607  0 22:03 ?        00:00:00 /bin/sh /sbin/service salt-minion restart
root      4708  4701  0 22:03 ?        00:00:00 /bin/sh /etc/init.d/salt-minion restart
root      5065  3448  0 22:03 pts/3    00:00:00 grep salt
[root@hostanme ~]#
[root@hostanme ~]#
[root@hostanme ~]#
[root@hostanme ~]# ps -ef | grep salt
root      3605     1  0 22:02 ?        00:00:00 /usr/bin/python2.7 /usr/bin/salt-minion -l debug
root      3606  3605  0 22:02 ?        00:00:00 /bin/bash -c salt-call state.apply |mail -s "[MINION] STARTUP RUN - hostanme.localdomain.com" ot-uxlxinfrastructure@localdomain.com
root      3607  3606  2 22:02 ?        00:00:01 /usr/bin/python2.7 /usr/bin/salt-call state.apply
root      4701  3607  0 22:03 ?        00:00:00 /bin/sh /sbin/service salt-minion restart
root      4708  4701  0 22:03 ?        00:00:00 /bin/sh /etc/init.d/salt-minion restart
root      5195  3448  0 22:03 pts/3    00:00:00 grep salt
[root@hostanme ~]#

**< - minion procs still running background and throw this error/output to the temrinal - >**


[root@hostanme ~]# [DEBUG   ] stdout: [ERROR   ] Command '['crontab', '-l']' failed with return code: 1
[ERROR   ] stderr: no crontab for root

[ERROR   ] retcode: 1
[DEBUG   ] Minion return retry timer set to 7 seconds (randomized)
[INFO    ] Returning information for job: 20180807220255325075
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'hostanme.localdomain.com', 'tcp://10.32.7.244:4506', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'hostanme.localdomain.com', 'tcp://10.32.7.244:4506')
[DEBUG   ] minion return: {'fun_args': ['salt-call state.apply |mail -s "[MINION] STARTUP RUN - hostanme.localdomain.com" ot-uxlxinfrastructure@localdomain.com'], 'jid': '20180807220255325075', 'return': "[ERROR   ] Command '['crontab', '-l']' failed with return code: 1\n[ERROR   ] stderr: no crontab for root\n\n[ERROR   ] retcode: 1", 'retcode': 0, 'success': True, 'fun': 'cmd.run'}


**< - minion procs and all childresn are all now dead - >**



[root@hostname~]# ps -ef | grep salt
root      6094  6084  0 22:06 pts/3    00:00:00 grep salt

**Comment by Ch3LL** [comment]
i looked at your debug output you attached and i'm not seeing the actual state being run. I assume those are logs for when the minion is shutting down. I'm having a hard time replicating this, can you share a sanitized version of the actual cron job?

**Comment by rso-support** [comment]
Yup, I didn't see it in the debug log either. Its almost like the minion exits, before the logs can received by the actual state run? (guess).  Take a closer look at the terminal output after the minion exists. You'll see remnants of what looks like output of the state run. I included the terminal output because it didn't appear in the debug log. 

the sls renders to this on the host (if thats what you're asking for)

```
# crontab -l 
# Lines below here are managed by Salt, do not edit
# SALT_CRON_IDENTIFIER:/etc/salt/minion.d/minionCheck.sh
0 */4 * * * /etc/salt/minion.d/minionCheck.sh
```

**Comment by Ch3LL** [comment]
can you paste the sanitized contents from `salt-call --local state.sls <state> -ldebug`?

also i was looking for the sanitized contents of : `/etc/salt/minion.d/minionCheck.sh`

**Comment by rso-support** [comment]
I think I have this one figured out. 

We recently added a cmd.run to the state. This recent addition triggered a bug that existed in a system wide profile in /etc/profile.d. Essentially, a tput call in /etc/profile.d/somefile.sh bombs out because no tty is attached when sourced as part of the cmd.run call. Once we removed the tput call, problem ceased to exist. 

This may still be interpreted as a problem depending on you look at it, considering the error was not communicated back up through the error reporting mechanism for cmd.run. Sadly, I was unable to see the error, I just happen to remember a similar issue that had occurred with something else (unrelated to salt) within our environment a week or so back .

**Comment by rso-support** [comment]
Additionally, as previously mentioned,  the minion received a SIGTERM when this happens. IMO, a state failure would be expected here, not a failed minion.

**Comment by Ch3LL** [comment]
can you share the cmd.run state and replication steps, so we can try to replicate the issue to see if we can do a better job at raising an error?

**Comment by rso-support** [comment]
any cmd.run should suffice. the key here is to drop a problematic shell init file in /etc/profile.d/ that causes an error. in my case, I had a few calls to tput which caused the problem. specifically, since  cmd.run doesn't have a terminal attached,  tput bombs out. I suspect anything that exits abnormally would trigger the problem. 

/etc/profile.d/trigger.sh
```
someFunc() {

   export bold=$(tput bold)
   export reset=$(tput sgr0)


   printf "%s\n" "${bold}This should trigger it${reset}"
}

someFunc


```

**Comment by Ch3LL** [comment]
still having a hard time replicating with that in my profile.d.

I just ran a cmd.run state liek below:

```
[root@10126eef57bb /]# cat /srv/salt/test.sls
echo test:
  cmd.run
```

```
[root@10126eef57bb /]# salt-call --local state.sls test
local:
----------
          ID: echo test
    Function: cmd.run
      Result: True
     Comment: Command "echo test" run
     Started: 14:54:59.000474
    Duration: 153.444 ms
     Changes:   
              ----------
              pid:
                  337
              retcode:
                  0
              stderr:
              stdout:
                  test

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 153.444 ms
```

can you replciate it with just a cmd.run state with that in your profile?
