### ISSUE TITLE
salt.states.file.managed replace=False not working

### ISSUE THREAD

**Issue by ProcenaFr** [saltstack/salt#49001]
I am trying to diff several files but the "replace=False" is not working with salt.state.file.managed.

### Steps to Reproduce Issue
```
/srv/salt/file.sls :
test diff:
  file.managed:
    - name: /root/toto
    - source: salt://toto
    - replace:
      - False
```

`salt "minion1" state.apply file`

### Result : 

```
minion1:
----------
          ID: test diff
    Function: file.managed
        Name: /root/toto
      Result: True
     Comment: File /root/toto updated
     Started: 15:54:24.307449
    Duration: 140.065 ms
     Changes:   
              ----------
              diff:
                  --- 
                  +++ 
                  @@ -1 +1 @@
                  -hello
                  +helloO

Summary for minion1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time: 140.065 ms
```
The normal behavior is supposed to be : 

> replace
> : True
> If set to False and the file already exists, the file will not be modified even if changes would otherwise be made. Permissions and ownership will still be enforced, however.

### Version
Salt version : salt-2018.3.0-46.28.1.15763.1.PTF.1102218.x86_64

**Comment by Ch3LL** [comment]
```
test diff:
  file.managed:
    - name: /root/toto
    - source: salt://toto
    - replace: False
```

can you try that?

**Comment by ProcenaFr** [comment]
It is working, thanks.
