### ISSUE TITLE
Add cache.grain tests 

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#49017]
Add cache.grain runner tests

**Comment by gtmanfred** [comment]
👌

**Comment by gtmanfred** [comment]
There is already a generic `cache.grains` test, what specifically is this supposed to test?

https://github.com/saltstack/salt/blob/fluorine/tests/integration/runners/test_cache.py#L53-L61

**Comment by gtmanfred** [comment]
Adding tests for this

https://github.com/saltstack/salt/issues/48694

**Comment by gtmanfred** [comment]
Tests for this was added in https://github.com/saltstack/salt/pull/49034
