### ISSUE TITLE
add MasterPillarUtil tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#49018]
Add tests for the masterpillarutil class in salt/utils/master.py

**Comment by garethgreenaway** [comment]
@rallytime @Ch3LL The cache runner has three functions (grains, pillar, & mine) which use the corresponding functions in MasterPillarUtil, testing these as part of the cache runner tests seems like a good approach to testing MasterPillarUtil.  Thoughts?

**Comment by rallytime** [comment]
Yeah, I think that sounds like a good approach.

Some unit tests might be good as well where you think appropriate. After a quick glance, maybe some of those helper functions could use some unit tests since those seem to be doing most of the logical heavy lifting.
