### ISSUE TITLE
RSYNC source on repo.saltstack.com for new Python3 packages

### ISSUE THREAD

**Issue by haam3r** [saltstack/salt#49029]
### Description of Issue/Question
There does not seem to be a way to use rsync to create a local mirror of the new Python 3 packages 
i.e. would like to see something similar to:
`rsync://repo.saltstack.com/py3/saltstack_pkgrepo_ubuntu?`

Additionally adding the URI paths from here: https://github.com/saltstack/salt/issues/29222#issuecomment-234020952
to the http://repo.saltstack.com/#mirror page, would make it much simpler for people to configure the local mirroring without downloading the full repo. Therefore also potentially minimizing resource usage on the main repo side.

### Setup
Not applicable

### Steps to Reproduce Issue
Not applicable

### Versions Report
Not applicable

**Comment by UtahDave** [comment]
@haam3r I've added the python3 rsync directories.  I'm getting this output now:

```
[boucha@flaco ~]$ rsync rsync://repo.saltstack.com
saltstack_pkgrepo_full	Contents of repo.saltstack.com
saltstack_pkgrepo_full_python3	Contents of repo.saltstack.com Python3 only
saltstack_pkgrepo_debian	SaltStack Debian repo
saltstack_pkgrepo_debian_python3	SaltStack Debian repo Python3 only
saltstack_pkgrepo_ubuntu	SaltStack Ubuntu repo
saltstack_pkgrepo_ubuntu_python3	SaltStack Ubuntu repo Python3 only
saltstack_pkgrepo_rhel	SaltStack RHEL repo
saltstack_pkgrepo_rhel_python3	SaltStack RHEL repo Python3 only
saltstack_pkgrepo_freebsd	SaltStack FreeBSD repo
saltstack_pkgrepo_opensuse	SaltStack OpenSUSE repo
saltstack_pkgrepo_windows	SaltStack Windows repo
saltstack_pkgrepo_osx	SaltStack OS X repo
```

I'm making all python3 repos available, which at the moment are RedHat, Ubuntu, and Debian. I'll add others as they are packaged.

@haam3r  Could you test this?

```
rsync -vaH --numeric-ids --delete --delete-after --delay-updates rsync://repo.saltstack.com/saltstack_pkgrepo_full_python3 ./fullrepo_py3

rsync -vaH --numeric-ids --delete --delete-after --delay-updates rsync://repo.saltstack.com/saltstack_ubuntu_python3 ./ubuntu_py3

rsync -vaH --numeric-ids --delete --delete-after --delay-updates rsync://repo.saltstack.com/saltstack_pkgrepo_debian_python3 ./debian3

rsync -vaH --numeric-ids --delete --delete-after --delay-updates rsync://repo.saltstack.com/saltstack_pkgrepo_rhel_python3 ./redhat3
```

**Comment by haam3r** [comment]
@UtahDave Thanks for the quick reaction :)
I was able to successfully rsync against all 4 targets.
The second command had the path wrong i.e. should be: 
`rsync -vaH --numeric-ids --delete --delete-after --delay-updates sync://repo.saltstack.com/saltstack_pkgrepo_ubuntu_python3 ./ubuntu_py3`
instead of:
`rsync -vaH --numeric-ids --delete --delete-after --delay-updates rsync://repo.saltstack.com/saltstack_ubuntu_python3 ./ubuntu_py3` 
The path is correct in the rsync module listing, only the command had the typo.

Total space needed after rsync:
```bash
du -h --max-depth=1 ./
265M	./debian3
245M	./redhat3
252M	./ubuntu_py3
761M	./fullrepo_py3
1.5G	./
```
Was able to install the salt-minion package for ubuntu as well:
```bash
salt-call --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Apr  1 2018, 05:46:30)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-29-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

Would you like me to test anything else?

**Comment by UtahDave** [comment]
Nope!  Thanks for testing that out!  Good catch on my typo. You did find the correct directory name.  I'll go ahead and close this. Let us know if we need to make any other changes.

**Comment by hnsz2002** [comment]
@UtahDave rsync is not working... Can you check it, please?
