### ISSUE TITLE
syncing _grains directory

### ISSUE THREAD

**Issue by souadsadek** [saltstack/salt#49054]
Hello!
I install the laste version salt-master et salt-minion:
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed

In my root directory :

i have the custom grains: /salt/custom/_grains #
where i have script.py and severs files.sls, when i did salt-call saltutil.sync_all to synchronise my files, in the directory /var/cache/salt/minion/files/base/_grains/
I have just script.py and not files.sls

Can you please advice why the files.sls dont copy in cache minion??

**Comment by gtmanfred** [comment]
sync_all only syncs .py files for custom grains, it does not sync .sls files.

Those files are only synced when the minion asks for them.

`salt-call cp.cache_file salt://_grains/files.sls` will request the file and cache it on the minion in the file cache.

**Comment by souadsadek** [comment]
I have servers files .sls how can automatise  synchronicing theses files sls

**Comment by souadsadek** [comment]
I need this files to customise grains

**Comment by souadsadek** [comment]
I add sls extension in the file extmods.py and my pb is resolved 
thanks
