### ISSUE TITLE
Documentation EPUB does not pass validation

### ISSUE THREAD

**Issue by youk** [saltstack/salt#49065]
### Description of Issue/Question
[EPUB](https://docs.saltstack.com/en/epub/Salt-2018.3.2.epub) with the documentation does not seem to be completely valid. Checking it with [IDPF EPUB Validator](http://validator.idpf.org) gives [multiple errors](https://github.com/saltstack/salt/files/2280006/EPUB.Validator.beta.Results.txt).

In practice this might make some tools unable to display the file. For example, Google Play Books cannot display it as the file fails processing.

### Steps to Reproduce Issue
- Validate [Salt-2018.3.2.epub](https://docs.saltstack.com/en/epub/Salt-2018.3.2.epub) with [IDPF EPUB Validator](http://validator.idpf.org) and see the report.
- Upload [Salt-2018.3.2.epub](https://docs.saltstack.com/en/epub/Salt-2018.3.2.epub) to [Google Play Books](https://play.google.com/books/uploads) and see the error processing it.

### Versions Report
Salt-2018.3.2.epub

**Comment by Ch3LL** [comment]
ping @rallytime or @UtahDave have any ideas on how to fix these errors? there seems to be numerous errors here and I am not sure how to approach the fixes here. OR possibly know the person to point this to?

**Comment by rallytime** [comment]
Hrm, unfortunately, this isn't something I know much about.

**Comment by youk** [comment]
This issue is still here with [Salt-2019.2.2.epub](https://docs.saltstack.com/en/epub/Salt-2019.2.2.epub).

Error report from IDPF EPUB Validator:
[EPUB Validator (beta) Results.txt](https://github.com/saltstack/salt/files/4044761/EPUB.Validator.beta.Results.txt)

**Comment by youk** [comment]
Fix it already for fuck's sake instead of trying to close it.

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
