### ISSUE TITLE
Add support for GovCloud to the S3 module

### ISSUE THREAD

**Issue by ketzacoatl** [saltstack/salt#49069]
### Question

I am using the `file.managed` state to grab a file object from a bucket on S3. The bucket is private, and I'm running saltstack on an EC2 instance that has an IAM Instance Profile. I have confirmed I can access the object with the regular AWS utilities. The bucket is in AWS GovCloud partition/region. I have `s3.location: us-gov-west-1` in my minion config, and have tried various `service_url`s:

```
s3.service_url: s3-fips-us-gov-west-1.amazonaws.com
#s3.service_url: s3-us-gov-west-1.s3.amazonaws.com
#s3.service_url: s3-us-gov-west-1.amazonaws.com
```

When I use the `file.managed` state in this way on GovCloud, I see the following error returned:

```
Exception: Failed to get file. AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-gov-west-1' is wrong; expecting 'us-east-1'
```

This suggests the request is going to the default url, but enabling debug logging suggests the request url gets setup correctly:

```
https://s3-us-gov-west-1.s3.amazonaws.com/bucket_name/file_name
```

```
Starting new HTTPS connection (1): s3-us-gov-west-1.s3.amazonaws.com
```

Should this "just work" with GovCloud? am I configuring this incorrectly? or does support need to be added?

UPDATE: While this was originally a question, we confirmed the gap and this is now a feature request.

### Versions Report

```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-131-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud i don't think we have support for this but i'm not entirely sure?

**Comment by gtmanfred** [comment]
I am not aware of GovCloud, or what the difference would be.

I would assume it should just work.

**Comment by Ch3LL** [comment]
looks like we had to add support for salt-cloud here: https://github.com/saltstack/salt/pull/45187

so i'm just gonna take a guess we might need to with s3? not sure though

ping @ketzacoatl for reference what version of salt are you running?

**Comment by Ch3LL** [comment]
doh thats for azure scratch that but still if we could get the versions report.

**Comment by gtmanfred** [comment]
Then i think this needs to be a feature request to add support for govcloud.

**Comment by ketzacoatl** [comment]
OK, thanks for the confirmation. I can close this ticket and create another one, or update the ticket title/description to fit, which would you prefer?

**Comment by gtmanfred** [comment]
It should be fine, just needs to be tagged as a feature request.

**Comment by doesitblend** [comment]
ZD-3075

**Comment by ketzacoatl** [comment]
Hello, any progress on support for GovCloud Regions or pointers where the updates need to be made?

**I hope SaltStack realizes the impact GovCloud has on the industry and devops tooling.**

**If you don't support GovCloud, architects, system builders, integrators and operators move on to other tools, and SaltStack becomes not-relevant to our work on GovCloud.**

Please don't underestimate the opportunities available when supporting GovCloud!

**Comment by tombin** [comment]
Is this still being considered?  I am also trying to fetch files from s3 in AWS govcloud and am getting the same issue:

`Error running 's3.get': Failed s3 operation. AuthorizationHeaderMalformed: The authorization header is malformed; the region 'us-gov-east-1' is wrong; expecting 'us-east-1'`

**Comment by dpedu** [comment]
This works for me under salt 3000.5 with both `s3.service_url` configured correctly:

```
s3.service_url: s3.us-gov-east-1.amazonaws.com
```

And I must specify `location=` in my s3 calls: 

```
__salt__['s3.get'](location="us-gov-east-1" .... )
```

It doesn't work if I set `s3.location` and leave out the location argument.
