### ISSUE TITLE
Missing ARPCHECK option in rh7_eth template

### ISSUE THREAD

**Issue by scornelissen85** [saltstack/salt#49074]
### Description of Issue/Question
I'm missing arpcheck option in rh7_eth template

### Setup
See https://github.com/saltstack/salt/blob/develop/salt/templates/rh_ip/rh6_eth.jinja, it contains an ARPCHECK option. This option is missing in https://github.com/saltstack/salt/blob/develop/salt/templates/rh_ip/rh7_eth.jinja. 

### Steps to Reproduce Issue
Setting `arpcheck: no` on `network.managed`-state on RedHat 7 has no effect

### Versions Report
Currently it is in develop. There was a change which added arpcheck=no to rhel6: https://github.com/saltstack/salt/commit/2d28640c1794cef72ddfa7b92cdeeb74992c1700

**Comment by Ch3LL** [comment]
seems like you have a good grasp of the fix want to give a go at a fix for r7?

**Comment by scornelissen85** [comment]
Yes, I will make a PR for it. But there are more differences between them. For example:
`rh6_eth.jinja`:
```
IPADDR{{loop.index - 1}}="{{ipparts[0]}}"
PREFIX{{loop.index - 1}}="{{ipparts[1]}}"
```
vs.
`rh7_eth.jinja`:
```
IPADDR{{loop.index}}="{{i['ipaddr']}}"
PREFIX{{loop.index}}="{{i['prefix']}}"
```
Actually, I'm wondering why there is a template per major release. If we could write them down to 1 template then it is easier to maintain, and you couldn't miss such differences (I guess).

I have created a PR: #49094

**Comment by Ch3LL** [comment]
my only guess is there are differences between how each OS is setup. ping @saltstack/team-core know for sure or can we possibly combine both?

**Comment by Ch3LL** [comment]
oh also thanks for the pr @scornelissen85  :) really appreciate it
