### ISSUE TITLE
Fluorine - MultiMaster Failover dont work

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#49093]
### Description of Issue/Question
In Fluorine, MultiMaster Failover dont work. If the original master goes down, minions wont connect to other master. If I manually restart the minions they will connect to the other master.

I see nothing in the logs, just nothing happens. If I restart the original stopped master I can continue to run commands from that master, they are still connected to that one.

### Setup
Install Fluorine. I used this commit: 1f668c0
```
wget -O bootstrap.sh https://bootstrap.saltstack.com
sh bootstrap.sh -g https://github.com/saltstack/salt.git -M -P git 1f668c0011394f508c3a5dc8062ca246f1dce0c6
```
Set up MultiMaster Failover setup
```
master:
  - master_a
  - master_b

master_shuffle: True
master_type: failover
master_alive_interval: 30
```

### Steps to Reproduce Issue
Make sure minions are connected to one of the masters, stop that master and minions wont failover to other master.

### Versions Report
```
Salt Version:
           Salt: 2018.11.0-257-g1f668c0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by rallytime** [comment]
@garethgreenaway You're up!

**Comment by frogunder** [comment]
I did see this issue when this failed. Maybe its related?

https://github.com/saltstack/salt/issues/49082

**Comment by garethgreenaway** [comment]
@DmitryKuzmenko Mentioned that this works using a built in scheduler job, I've discovered an issue where scheduled jobs using seconds, minutes, etc. aren't running as expected.  This is likely that cause of the master-master fail over not working.  Looking into the scheduler issue.

**Comment by garethgreenaway** [comment]
@frogunder I believe this one should also be fixed in the PR that I referenced above.  Are you able to test MultiMaster failover using that branch?

**Comment by frogunder** [comment]
Just checked on the head of fluorine which installed this version `2018.11.0-461-g02823e5` and this is working correctly now.

**Comment by garethgreenaway** [comment]
Awesome. Closing this one out.
