### ISSUE TITLE
[Fluorine] Minionswarm dont work - ImportError

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#49114]
### Description of Issue/Question
In Fluorine, when trying to use minionswarm, it fails with tis error:
```
Traceback (most recent call last):
  File "minionswarm.py", line 31, in <module>
    import tests.support.helpers
ImportError: No module named tests.support.helpers
```

### Setup
Install Fluorine and grab the minionswarm.py file
```
wget https://raw.githubusercontent.com/saltstack/salt/fluorine/tests/minionswarm.py
```

### Steps to Reproduce Issue
Run this command and you'll see the traceback
```
[root@frode1 ~]# python2 minionswarm.py -m 20 --master localhost
Traceback (most recent call last):
  File "minionswarm.py", line 31, in <module>
    import tests.support.helpers
ImportError: No module named tests.support.helpers
[root@frode1 ~]# 
```

### Versions Report
```
Salt Version:
           Salt: 2018.11.0-257-g1f668c0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by garethgreenaway** [comment]
@frogunder You're installing Fluorine via packages?  I don't believe the testing suite is included in the packages.  Did this work with previous versions?

**Comment by frogunder** [comment]
@garethgreenaway I installed using the bootstrap script, not the newest version since that dont work with Fluorine. I did this:
```
wget -O bootstrap.sh https://raw.githubusercontent.com/saltstack/salt-bootstrap/466d62fccc3dad3f1b4903b16caae4ffa0ee5dae/bootstrap-salt.sh
sh bootstrap.sh -g https://github.com/saltstack/salt.git -M -P git 1f668c0011394f508c3a5dc8062ca246f1dce0c6
```
Yes it works with previous versions, seems like in the minionswarm.py file this was added for fluorine
```
import tests.support.helpers
```
which is not in the 2018.3.2 minionswarm.py, which I just tried and it works fine there

**Comment by garethgreenaway** [comment]
@dwoz Looks like you were the one that made this change.  Thoughts?

**Comment by frogunder** [comment]
I see the same issue on 2017.7.8.

Checked 2017.7.7 and its working correctly there.

**Comment by rallytime** [comment]
Adding that import definitely is causing this to fail, but since `minionswarm` is in the same directory as the other files in `tests` (helpers in this case), I think this is expected behavior. The testing files don't come with a package install, and I don't think we make any promises that minionswarm will work on it's own.

@saltstack/team-core any additional thoughts?

**Comment by frogunder** [comment]
Closing this. 
When installing using the bootstrap script the `tests` dir don't get copied over. If installing using git or do a git clone its working correctly.
