### ISSUE TITLE
PDF documentation is not complete

### ISSUE THREAD

**Issue by patrikelmberg** [saltstack/salt#49149]
### Description of Issue/Question
https://docs.saltstack.com/en/pdf/Salt-2018.3.2.pdf does not contain the full documentation.
Ends after chapter 13 Salt Cloud.

Earlier version seems to match the web pages well.
https://docs.saltstack.com/en/pdf/Salt-2017.7.7.pdf

**Comment by Ch3LL** [comment]
thanks for the heads up. i'll take a look into this.
