### ISSUE TITLE
salt-cloud intermittent AWS failure assigning tags

### ISSUE THREAD

**Issue by boltronics** [saltstack/salt#49145]
### Description of Issue/Question
I provisioned a new host and ran into this:
```
$ sudo salt-cloud -m ec2-company-us-west-2b.map 
[WARNING ] 'XXXX' already exists, removing from the create map.
[WARNING ] 'YYYY' already exists, removing from the create map.
...etc
The following virtual machines already exist:
  XXXX
  YYYY
  ...etc
The following virtual machines are set to be created:
  ZZZ

Proceed? [N/y] y
... proceeding
[ERROR   ] AWS Response Status Code and Error: [400 400 Client Error: Bad Request for url: https://ec2.us-west-2.amazonaws.com/?Action=CreateTags&ResourceId.1=i-093f49a9cc86e21e6&Tag.0.Key=management&Tag.0.Value=salt&Tag.1.Key=misc&Tag.1.Value=cron&Tag.2.Key=Name&Tag.2.Value=ZZZ&Version=2014-10-01] {'Errors': {'Error': {'Message': "The instance ID 'i-093f49a9cc86e21e6' does not exist", 'Code': 'InvalidInstanceID.NotFound'}}, 'RequestID': '5f426b3b-8efd-471c-88e3-37b5af3fe8da'}
```
The instance was created successfully, but none of the tags existed which caused other problems for us. Nuking the instance after identifying the issue and recreating it in the same way worked.

I have created many instances before, with a variety of AMIs (including the one in use here) and this was the first time I've noticed this happening.

### Setup
The AMI is a custom Debian Stretch GNU/Linux HVM type for the amd64 architecture with an EBS root volume, created using debian-image-builder.

### Steps to Reproduce Issue
Unknown. Just get unlucky?

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.5 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.5 
 
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud any ideas here as this one seems to be a bit hard to replicate?

**Comment by gtmanfred** [comment]
Can we get the debug logs for this?  probably just need better exception handling for assigning tags, i am not sure what the issue would be at this moment.

**Comment by boltronics** [comment]
Unfortunately I don't have debug logs for the above error. I've since launched about 10 more instances using the same AMI in the same way and not experienced the issue again, so I don't think such logs are going to be easy to obtain. I agree that it probably just needs some exception handling, and ideally a couple of automatic retries before a hard failure.

**Comment by gtmanfred** [comment]
Actually, looking at the error message, i bet it is just a race condition thing.  

```
'Code': 'InvalidInstanceID.NotFound'
```

But looking at the code, it looks like the `query_instance` function in the ec2 driver should wait until the device exists before the tag command gets run.

Hrm, yeah i will need more information about this, and the debug logs before we can come up with an actual solution for it.

**Comment by boltronics** [comment]
I have created a Salt configuration to ensure my salt-cloud installations now log to file at the debug logging level. If I ever see it happen again I'll update this issue to provide the associated log.

**Comment by gtmanfred** [comment]
Awesome, thank you very much for help with this.
