### ISSUE TITLE
Minion continues to run execution modules with incorrect authentication key

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#49141]
### Description of Issue/Question
In this scenario, I deleted the minion key files from the minion. If this ever happened, I expect communication to persist while the minion is up since I believe the key loaded into memory at that point. So this is mostly expected behavior below.
```
[root@dd9e2b965227 minion]# salt-key
Accepted Keys:
dd9e2b965227
Denied Keys:
dd9e2b965227
Unaccepted Keys:
Rejected Keys:
[root@dd9e2b965227 minion]# salt '*' test.version
dd9e2b965227:
    2018.3.2
[root@dd9e2b965227 minion]# salt-call test.version
[ERROR   ] The Salt Master has rejected this minion's public key.
To repair this issue, delete the public key for this minion on the Salt Master.
The Salt Minion will attempt to to re-authenicate.
Minion failed to authenticate with the master, has the minion key been accepted?
```

Where this goes wrong is I'm seeing that it can't process `state.apply`, but it can return info from modules like `test.version` or `pkg.install` still. This happens with [rotate-aes-key](https://docs.saltstack.com/en/latest/ref/configuration/master.html#rotate-aes-key) enabled or not.

### Steps to Reproduce Issue
Configure a salt minion and master with 2018.3.2 installed from RPM on RHEL 7.5. Accept the key from the minion. Then delete the `minion.pem` and `minion.pub` files from `/etc/salt/pki/minion` with the minion daemon still running.

Run any execution module. This is expected to return and generate a new key for the minion.
Run any state and this will fail with an authentication error.

### Versions Report
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.93-linuxkit-aufs
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-core i'm actually note sure what would be expected in this scenario. Any thoughts on what should be occurring here?

**Comment by gtmanfred** [comment]
@doesitblend can you verify that the aes key actually rotated when the minion key was deleted? I am wondering if it could be a race condition.
