### ISSUE TITLE
incorrect default value of minion's 'ipv6' option 

### ISSUE THREAD

**Issue by wenxin-wang** [saltstack/salt#49159]
### Description of Issue/Question

In the documentation of the [latest version(2018.3.2)](https://docs.saltstack.com/en/latest/ref/configuration/minion.html#ipv6), and the [develop version](https://docs.saltstack.com/en/develop/ref/configuration/minion.html#ipv6), the default value of minion's `ipv6` option is documented as `None`.

However, in the code of [2018.3.2](https://github.com/saltstack/salt/blob/v2018.3.2/salt/config/__init__.py#L1352) and the [develop branch](https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L1377), the default value is coded as `False`.

This makes IPv6-only minion still use master's IPv4 address when using a domain name. To work around this issue currently, set an empty `ipv6` option in `/etc/salt/minion`:

```yaml
ipv6:
```  

This sets `opts['ipv6']` in the code to `None`, and now the minion respects the preference of the OS.

### Steps to Reproduce Issue
1. Disable IPv4 on the minion
2. Do not set `ipv6` in the minion config
3. Use domain name for master, and make sure it has AAAA record
4. run `salt-minion -l debug`. The minion will try to connect to the master using IPv4 address, over and over again.

### Versions Report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: armv7l
        release: 4.14.50-v7+
         system: Linux
        version: debian 9.4

**Comment by Ch3LL** [comment]
looks like the ipv6 default value was changed to false here: ccfa24260db which is in this PR https://github.com/saltstack/salt/pull/45354

ping @terminalmage any possibilities we can change it back to None and avoid the warning?

**Comment by terminalmage** [comment]
Good catch, since I don't recall the reasoning for changing that, I've reverted it in https://github.com/saltstack/salt/pull/49263 and set it so that `None` will not cause a warning when this value is set to that.
