### ISSUE TITLE
Feature: Suppress a configurable domain in utils.network._generate_minion_id()

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#49212]
## Proposal
When the salt minion lacks an id, [utils.network.generate_minion_id()](https://github.com/saltstack/salt/blob/943e21f3e6e314a0fe1af7f08354a2b58303d224/salt/utils/network.py#L169) generates a fully qualified domain name, using a variety of sources.

I propose a new setting `minion_id_generate_no_domain`, to suppresses a single domain in the result of above function.

### Current Behavior
The function returns `king_bob.foo.bar`
### Proposed behavior:
Without `minion_id_generate_no_domain `, as currently.
With `minion_id_generate_no_domain = foo.baz`, as currently
With `minion_id_generate_no_domain = foo.bar`, the function returns `king_bob `

**Comment by Ch3LL** [comment]
thanks for the PR!! As the pr resolves this issue I will close but please let me know if it needs to be reopened :)

**Comment by markuskramerIgitt** [comment]
thank you, @Ch3LL

**Comment by markuskramerIgitt** [comment]
@Ch3LL, could you please help me with PR https://github.com/saltstack/salt/pull/49378
Which are the requested changes?

**Comment by markuskramerIgitt** [comment]
Hi @Ch3LL, I think the requested changes are from terminalmage, I asked him.

**Comment by Ch3LL** [comment]
glad you got it figured out. let me know if  can help with anything else :)

**Comment by markuskramerIgitt** [comment]
Yep, and terminalmarge already explained his request in all details.


Thank you for the offer.

I just looked at your PR https://github.com/saltstack/salt/pull/48866.
I will come back to twangboy and might come back to you because I would like that Jenkins creates the Windows msi installer. 

First I need to verify the installer.
