### ISSUE TITLE
salt-minion communication via Proxy server

### ISSUE THREAD

**Issue by dpkkumar01** [saltstack/salt#49224]
I have installed salt-master/salt-api in one of my Master application server where i am connecting multiple salt-minion servers directly.  

Now i have to connect few more minion servers which doesn't have direct connectivity with my salt-master server. These new minion servers are reachable from one of my other server which is reachable from my salt-master application server as well.

Is there any way to connect these new minion applications via existing salt-master server?

**Comment by dpkkumar01** [comment]
Thanks for your valuable response. I have made the setup and able to execute my command in salt-minion servers via salt-syndic.

Earlier i use to check my minion status in my main salt master application server using saly-key command. Now i am getting only "my_syndic" id in my main master. 

I want to check my other end minion servers connected on salt-syndic server from my main master server.  

How do we list all complete minion list on my main master server??

**Comment by Ch3LL** [comment]
salt-key will only show the minions attached directly to each master but you should be able to run `salt '*' test.ping` from the master of masters and it should return all the minions.

**Comment by dpkkumar01** [comment]
Thanks for your guidance. I have made the setup and tested couple of functionalities. it is working fine.

Now i want to use cp.get_file and cp.push commands from my Main master to syndic minion servers directly which is not working. Is there any way to do this??

**Comment by Ch3LL** [comment]
if i remember correctly the file you are trying to copy would also need to be on the syndic in order to work as it does not transfer the file to the syndic master

**Comment by dpkkumar01** [comment]
Thanks for your support
