### ISSUE TITLE
Salt-key using external auth and token file is broken

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#49222]
### Description of Issue/Question
It's not possible to use token file with external auth:
```
$ salt-key -T --auth=pam
username: example
password:
Error: 'token_file'

$ ls salt_token
ls: cannot access salt_token: No such file or directory

### Setup
Enable external auth on salt-master:
```
external_auth:
  pam:
    users%:
      - '.*'
      - '@wheel'
      - '@runner'
      - '@jobs'
    limited%:
      - 'test.ping'
      - 'state.apply'
      - 'state.highstate'
      - 'grains.get'
      - 'grains.item'
      - 'grains.items'
      - 'pillar.get'
      - 'pillar.item'
      - 'pillar.items'
      - 'pkg.list_pkgs'
      - 'pkg.list_repos'
      - 'pkg.version'
```

### Steps to Reproduce Issue
$ salt-key -T --auth=pam

### Versions Report
```
Salt Version:
           Salt: 2017.7.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.30.1.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by Ch3LL** [comment]
thanks for the PR! We really appreciate it :) since the PR resolves the issue I will close here and we can keep the discussion in the PR. Let me know if you want me to re-open here though :)
