### ISSUE TITLE
Unable to running the salt minion on windows as an unprivileged user

### ISSUE THREAD

**Issue by qiushics** [saltstack/salt#49220]
I want to start salt as an unprivileged user
after change the owner of c:\salt, can't start salt-minion

C:\salt>salt-minion.bat
CRITICAL: Unable to securely set the owner of "c:\salt".

salt version:2018.3.2
system version:win 10

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any insight here?

**Comment by damon-atkins** [comment]
Could you please provide some examples of use which do not require Admin access?

**Comment by qiushics** [comment]
@damon-atkins for example: start firefox installed by an unprivileged user.

**Comment by damon-atkins** [comment]
> Start firefox installed by an unprivileged user.

Results in firefox being installed just for that user.
pkg.list_pkgs will not see it, as it only supports software installed for everyone. There are large issue to overcome with supporting user installed software.

The other issue is User Registry is not divided into 64bit and 32bit like the Machine registry.

Your example does not tell us what your aim is?

One day salt might have on windows a   salt-call-user   which sets all the paths inside the users directory tree and tells the salt master its a user.  But this would also mean that Machine (as now) needs a accepted salt-key and also each user would need an accepted salt-key. As you would not want users getting access to information they should not.

We need to have more information on the Goal?

**Comment by qiushics** [comment]
We have several machines, I want to use salt to control every machine opening firefox with a website.
Each machine is auto logging, what I want is using salt to control software after the desktop is displayed.
I've tried using salt as services (default, no matter the services belonged to admininistrator or certain user), the gui of firefox doesn't pop up.
So I want to run salt by an unprivileged user. But after I run salt-minion.bat, it outputs the things  above.

**Comment by twangboy** [comment]
I would recommend adding a startup script to the machine that launches firefox instead.

On Windows 10, that script would be in `C:\ProgramData\Microsoft\Windows\Start Menu\Programs\StartUp`.

You could also point to your script in the registry at : `HKEY_LOCAL_MACHINE\Software\Microsoft\Windows\CurrentVersion\Run`

Or you could use Group policy to define a script that runs at startup.
