### ISSUE TITLE
service.status doesn't behave the same way on MacOS as on other platforms

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#49237]
### Description of Issue/Question
On most platforms, the `service.status` module returns either `True` or `False` depending on the status of a given service. But on MacOS, it returns `False` if the service isn't running, or a list of process IDs if the service is running. This makes it difficult to make platform-agnostic tools on top of Salt, since special consideration has to be made for Mac OS.

### Steps to Reproduce Issue
Run `salt MACOS-MINION service.status servicename` against a running service

### Versions Report
2018.3.2

**Comment by weswhet** [comment]
I'm going to change the behavior of this to the above and create another function to handle any PID searching, @garethgreenaway any opposition to this before I start typing?

**Comment by garethgreenaway** [comment]
@weswhet No objections, thanks for picking this up :smile:

**Comment by weswhet** [comment]
Will have a fix for this shortly.
