### ISSUE TITLE
No minions matched the target. No command was sent, no jid was assigned. ERROR: No return received

### ISSUE THREAD

**Issue by lyddragon** [saltstack/salt#49249]
**salt cli:**

> $ salt -N 'n.node' test.ping
> No minions matched the target. No command was sent, no jid was assigned.
> ERROR: No return received

**salt master config:**
> nodegroups:
>   n.v1n: "L@192.168.1.107,192.168.1.108"
>   n.v2n: "L@192.168.1.109,192.168.1.110"
>   n.node: "N@n.v1n and N@n.v2n"

**salt-master version:**

> rpm -qi salt-master
> Name        : salt-master
> Version     : 2015.5.10
> Release     : 2.el7
> Architecture: noarch
> Install Date: Tue 12 Sep 2017 02:44:24 PM CST
> Group       : System Environment/Daemons
> Size        : 1061800
> License     : ASL 2.0
> Signature   : RSA/SHA256, Wed 01 Jun 2016 03:45:00 PM CST, Key ID 6a2faea2352c64e5
> Source RPM  : salt-2015.5.10-2.el7.src.rpm
> Build Date  : Tue 31 May 2016 10:12:16 PM CST
> Build Host  : buildhw-06.phx2.fedoraproject.org
> Relocations : (not relocatable)
> Packager    : Fedora Project
> Vendor      : Fedora Project
> URL         : http://saltstack.org/
> Summary     : Management component for salt, a parallel remote execution system
> Description :
> The Salt master is the central server to which all minions connect.

**salt master log:**
> 2018-08-22 18:57:31,375 [salt.utils.minions][DEBUG   ][22083] nodegroup_comp("n.v1n") => ( L@192.168.1.107,192.168.1.108 )
> 2018-08-22 18:57:31,375 [salt.utils.minions][DEBUG   ][22083] nodegroup_comp("n.v2n") => ( L@192.168.1.109,192.168.1.110 )
> 2018-08-22 18:57:31,376 [salt.utils.minions][DEBUG   ][22083] nodegroup_comp("n.node") => ( ( L@192.168.1.107,192.168.1.108 ) and ( L@192.168.1.109,192.168.1.110 ) )
> 2018-08-22 18:57:31,377 [salt.utils.minions][DEBUG   ][7966] Evaluating final compound matching expr: ( ( set(['192.168.1.108', '192.168.1.107']) ) & ( set(['192.168.1.110', '192.168.1.109']) ) )

**Comment by garethgreenaway** [comment]
@lyddragon Thanks for the report.  Unfortunately the version of the Salt master that you're using (2015.5.10) is quite old and no longer supported.  More details about what versions are still supported can be found here, https://saltstack.com/product-support-lifecycle/
