### ISSUE TITLE
New module.run syntax does not support keyword arguments

### ISSUE THREAD

**Issue by BenjaminSchiborr** [saltstack/salt#49295]
### Description of Issue
With Sodium a new syntax for the "module.run' function will be introduced as indicated by the following message: ``The function "module.run" is using its deprecated version and will expire in version "Sodium"``.
The required changes are described here: (https://docs.saltstack.com/en/develop/topics/releases/2017.7.0.html#state-module-changes)

This new syntax no longer supports the use of keyword arguments in a state. As such, converted states might show very confusing outcomes.
The first argument of the file.copy function is "src" and the second argument ist "dst" (https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.copy). In the example below this order is not followed.

### Setup
Given a (windows?) minion with two folders "Source" and "Dest". In each one of those folders there is a file.
We have two states. Both states copy content from folder "Source" to folder "Dest". State "old_copy" uses the old syntax and state "new_copy" uses the new syntax.

```
old_copy:
  module.run:
    - name: file.copy
    - dst: C:/Dest
    - src: C:/Source
    - recurse: True
    - remove_existing: False
```

```
new_copy:
  module.run:
    - file.copy:
      - dst: C:/Dest
      - src: C:/Source
      - recurse: True
      - remove_existing: False
```

Necessary changes to minion config to activate new syntax:
```
use_superseded:
- module.run
```

### Steps to Reproduce Issue
1. Execute state "old_copy" against the minion. The result will be that the folder "Dest" is containing both it's original files and those from folder "Source".
2. Revert the content of both folders back to its original state
3. Change the minion config to utilize the new module.run syntax
4. Execute state "new_copy" against the minion. The result will be that the folder "Source" is containing both it's original files and those from folder "Dest".

### Versions Report
```
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.0-79-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by Ch3LL** [comment]
im able to replicate this. it looks like in the code we are getting the functions argspec and it only passes the kwargs that the function is expecting to be kwargs and passes the rest as args. If you reverse the two dst and src calls you can get it working for now, but I think we should support being able to send it in the wrong order since we supported that previously. 

ping @isbm

**Comment by isbm** [comment]
Looking at this at the moment. It appears that in your case `file.copy` is called this way:
```
file.copy(['C:/Dest', 'C:/Source'], {'remove_existing': False, 'recurse': True})
```
Seems like the keyworded arguments aren't aligned by the function signature. I am on it right now. Stay tuned.

**Comment by isbm** [comment]
Here. You have it: https://github.com/saltstack/salt/pull/50049

**Comment by isbm** [comment]
Adding some UT for this.

**Comment by isbm** [comment]
UT: https://github.com/saltstack/salt/pull/50072

**Comment by isbm** [comment]
Leap/SUSE users, packages with this fix are, as always, here:
https://build.opensuse.org/package/show/systemsmanagement:saltstack:testing/salt

@Ch3LL @rallytime seems we should to close this.
