### ISSUE TITLE
virtual modules shadow/service have unaccessible online documentation

### ISSUE THREAD

**Issue by erwindon** [saltstack/salt#49335]
### Description of Issue
The documentation for both the virtual module `shadow` and the execution module `shadow` have the same page url. Therefore the online documentation for execution module `shadow` cannot be accessed.
The same happens for virtual module `service`.
It does not happen for any of the other virtual modules.

### Setup
none, existing saltstack.com website only

### Steps to Reproduce Issue
Go to the page for virtual module `shadow`: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.shadow.html. Now try to see the documentation for execution module `shadow` by following link `shadow` and see that it points to the same page again.
The same happens for virtual module `service`.

My suggestion is to rename execution module `shadow` to `linux_shadow`; and to rename execution module `service` to `sysvinit_service`.

### Versions Report
N/A

**Comment by garethgreenaway** [comment]
@erwindon Thanks for the report.

**Comment by max-arnold** [comment]
I wonder if it is possible to write a test or make a change in the build process that will prevent this from happening in the future.

**Comment by mchugh19** [comment]
Sounds like this would also be helped by implementing the naming convention suggestions from #30533

**Comment by johnnybubonic** [comment]
worth nothing this does NOT occur for the "online"(in the classical sense of the word) docs, e.g. `salt-call sys.doc shadow` or `salt '<TGT>' sys.doc shadow` - the Linux shadow execution module is shown. i didn't check to see if you're generating the HTML docs from `sys.doc`'s source or vice versa, but if you are, the namespacing issue is not present on `sys.doc`.

same for the `service` execution module (is indeed accessible via `sys.doc`).

**Comment by max-arnold** [comment]
Bump

**Comment by max-arnold** [comment]
https://github.com/saltstack/salt/pull/53296

**Comment by barbaricyawps** [comment]
Closing as this was resolved by https://github.com/saltstack/salt/pull/53296
