### ISSUE TITLE
2016.3 - config.get master returns only 1 value from master list

### ISSUE THREAD

**Issue by f3flight** [saltstack/salt#49350]
### Description of Issue/Question
`salt-call config.get master` will only return 1 value from master: section even if it's a list
### Setup
configure `master:` section in minion config to have 2 values as a list:
```
master:
- 1.2.3.4
- 1.2.3.5
```
### Steps to Reproduce Issue
set config like above, run `salt-call config.get master`

### Versions Report
found on 2016.3

Note: custom config options are correctly returned as lists if they are lists.
Same issue when using `__opts__` dict inside salt modules.

**Comment by gtmanfred** [comment]
Correct, this is by design, it returns the master the minion is connected to for that call.

**Comment by f3flight** [comment]
Sow gow to get a list of masters from config?

**Comment by gtmanfred** [comment]
I am not sure that you can, the reason it gets narrowed down to 1 is so that it knows which one to connect to.

Are you using a failover or an active-active connection?

**Comment by f3flight** [comment]
Using failover mode. I'm trying to find the easiest way to fix the problem with a specific 3rd party module code which needs to get a list of masters as defined in config, but only gets one.

**Comment by gtmanfred** [comment]
yeah, the way failover mode works is that it sets just one in the `master` for opts, and that is the one that it connects to, so you won't get the full list from that option, have you tried dumping the whole opts dictionary or the grains.items, and checking if the full list is specified in there?

try `config.get master_list` or `local_masters`.
