### ISSUE TITLE
salt-cloud does not maintain state

### ISSUE THREAD

**Issue by sam0104** [saltstack/salt#49359]
### Description of Issue/Question
salt-cloud does not maintain state. Is it possible to maintain state for salt-cloud deployment without write custom modules . 
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
salt states , salt-cloud for Vmware
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Generic question for supporting states in salt cloud
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
2017.7.7

**Comment by gtmanfred** [comment]
What do you mean by "maintain state"?

Do you want to update the cloud servers after they have been built?

**Comment by sam0104** [comment]
yes similar to Terraform .

**Comment by sam0104** [comment]
yes something like Terraform state.  Which managed infrastructure and configuration  used to map real world resources to configuration, keep track of metadata, and to improve performance for large infrastructures. Also can be used for roll back

**Comment by gtmanfred** [comment]
See https://github.com/saltstack/salt/issues/49208
