### ISSUE TITLE
env_order ignored regarding pillar_roots

### ISSUE THREAD

**Issue by chschmitt** [saltstack/salt#49369]
### Description of Issue/Question
I am trying to set up a deterministic merging of multiple pillar environments using a single (pillar) top file.

- `base` environment: regular pillars
- `alt` environment: pillars to selectively override the regular pillar values

The pillar values are merged, but not in the right order (ignoring env_order, see below).

### Setup
```
# /etc/salt/master.d/pillar_roots.conf
pillar_roots:
  alt:
   - /srv/pillar
  base:
   - /srv/pillar

env_order:
  - base
  - alt
```
```
# /srv/pillar/top.sls
base:
  '*':
    - basepillar
alt:
  # the targeting pattern is more specific in reality
  '*':
    - altpillar
```
```
# /srv/pillar/basepillar.sls
p: basevalue
```
```
# /srv/pillar/altpillar.sls
p: altvalue
added: foo
```
### Steps to Reproduce Issue
`salt minion pillar.items`

Result:
```
minion:
    ----------
    added:
        foo
    p:
        basevalue
```

Also, reversing `env_order` has no effect.

### Versions Report
```
Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.6.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo
```
Edit: Typos

**Comment by chschmitt** [comment]
@Ch3LL Just for the record: I had the issue with sallt-ssh and a 2018.3.X release a while ago, but I did not have the time to carve out a minimal, reproducible example for a bug report.

**Comment by chschmitt** [comment]
@terminalmage @Ch3LL Can you clarify what the intended behavior actually is? It seems the base environment always "wins". Are there any merging rules that can be relied upon?

**Comment by terminalmage** [comment]
I don't know off the top of my head, but it seems to be down to set iteration order. The envs are compiled [here](https://github.com/saltstack/salt/blob/74dc587/salt/pillar/__init__.py#L477-L481) and iterated over [here](https://github.com/saltstack/salt/blob/74dc587/salt/pillar/__init__.py#L510).

**Comment by chschmitt** [comment]
@terminalmage Thank you for pointing me in the right direction.

I had a look at the code. The pillar compilation uses [`get_top()`](https://github.com/saltstack/salt/blob/74dc58722a8abaa3b12e5a03640e9d8aa23024f2/salt/pillar/__init__.py#L626), which returns a simple (unorderd) dict.

But There are two undocumented (?) features that could actually support my use case.

- [Inclusion of other pillar top files](https://github.com/saltstack/salt/blob/74dc58722a8abaa3b12e5a03640e9d8aa23024f2/salt/pillar/__init__.py#L528)
- [Ordering of target declarations](https://github.com/saltstack/salt/blob/4e6199b907aea125b076b55cdb1470ff158a6fb6/salt/pillar/__init__.py#L592)

Are those safe to use?

Instead of defining another environment, I could simply include a second top file for the base environment and use `order: -1` for each target in that included top file to have the specified pillars merged in first. But now there is the problem with duplicate targets. If there is a `*` in both top files, only the pillars of one target will be included. Does this have something to do with `pillar_source_merging_strategy` or do I have to use workarounds like `*` and `E@.*` to include both targets?

```
# top.sls
include:
  - top_base

base:
  '*':
    - altpillar
```

```
# top_base.sls
base:
  'E@.*':
    - order: -1
    - basepillar
```

**Comment by terminalmage** [comment]
I am really not sure, to be honest. Most of my familiarity with how top files are compiled comes from the state compiler, and for some reason pillar was written with a separate implementation, which has diverged over time. This is the reason why we're hoping to converge the two into a (mostly) shared codebase eventually.
