### ISSUE TITLE
Problem into partition.get_id execution module

### ISSUE THREAD

**Issue by konstest** [saltstack/salt#49360]
### Description of Issue/Question
Get text of error message into output partition.get_id:
```
root@devops-salt:/# salt test-minion partition.get_id /dev/sda 1
test-minion:
    - sfdisk: print-id is deprecated in favour of --part-type
    - 8e
```
Needs fix this [string of code](https://github.com/saltstack/salt/blob/develop/salt/modules/parted.py#L304) on:
    cmd = 'sfdisk --part-type {0} {1}'.format(device, minor)

**Comment by gtmanfred** [comment]
so, it may not be that simple, you may have to check which version of sfdisk is running and when this changed.

But if you wouldn't mind submitting that as a PR, we would greatly appreciate it.

Thanks!
Daniel

**Comment by johncollaros** [comment]
partition.get_id and partition.set_id both seem broken

root@MASTER:~# salt -C "$(printf '%s ' ${salt_filter[@]})" partition.set_id /dev/sdb 1 83
HOST1:
    ERROR: Invalid system_id passed to partition.set_id
HOST2:
    ERROR: Invalid system_id passed to partition.set_id
ERROR: Minions returned with non-zero exit code
root@MASTER:~# salt -C "$(printf '%s ' ${salt_filter[@]})" partition.get_id /dev/sdb 1
HSOT1:
    - sfdisk: print-id is deprecated in favour of --part-type
    - 83
HOST2:
    - sfdisk: print-id is deprecated in favour of --part-type
    - 83
root@MASTER:~#
