### ISSUE TITLE
Requiring an SLS only requires states inside SLS

### ISSUE THREAD

**Issue by BenjaminSchiborr** [saltstack/salt#49384]
### Description of Issue/Question
When requiring an SLS through a state I would expect that everything in that state is executed beforehand. This is currently **not** the case.

This ticket is to determine whether or not this is wanted and if this is the case to ensure it is documented.

### Setup
Assume the following state. It includes the sls "required_state".

```
 {% requiring_state.sls %}

'This state requires another sls':
  test.succeed_without_changes:
    - require:
        - sls: required_state
```

The state in the sls below includes another sls called "included_state". This state is just included, but not directly required.

```
{% required_state.sls %}

include:
  - included_state

'The sls containing this state is required by another state. This sls contains includes':
  test.succeed_without_changes
```

Finally, the included sls:

```
{% included_state.sls %}

'This state is included by another state':
  test.succeed_without_changes
```

At what point in the runtime should "included_state" be executed? 

Intuitively one might expect this to ***always*** happen before "requiring_state.sls", because it requires everything in another sls. 
Effectively this is not the case. To ensure that this will happen the "required_state" has to be adapted:

```
{% fixed_required_state.sls %}

include:
  - included_state

'The sls containing this state is required by another state. This sls contains includes':
  test.succeed_without_changes:
    - require:
        - sls: included_state
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-119-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by gtmanfred** [comment]
Include does not physically put the state inside of another state, the yaml needs to be processed, and it is run after requisites.

If you want it run before, you need to explicitly require it, or actually put the state into the file by importing it using jinja.

```
{# required_state.sls #}

{% import_yaml 'included_state.sls' as included_state %}

{{ included_state|yaml(False) }}

'The sls containing this state is required by another state. This sls contains includes':
  test.succeed_without_changes
```

Unless you do it this way, that state is not actually inside of the required_state.sls, it is just telling the state system to include it.


Now, as for if it is the desired behavior.

@saltstack/team-core does anyone have opinions on handling include state should be considered actually included for sls: requires?

Thanks,
Daniel
