### ISSUE TITLE
archive.extracted fails when using non-salt-master secondary source

### ISSUE THREAD

**Issue by dfragazi** [saltstack/salt#49425]
### Description of Issue/Question
Setting the source field to have more than one source in case the primary is unavailable. The second source in this case is a web server (Windows Server 2003 with Apache24). The target system is also a web server (Windows Server 2008 R2 with Apache 24).  Both servers are running Salt 2016.3.6. The Salt-Master is 2016.11.6 Once the command is executed and a few minutes have elapsed, a folder (from if_missing) does appear, but is empty. On the salt-master an exception is received (same as Error log). Error log entry has the following:
2018-08-27 17:21:01 [salt.state     ][ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\state.py", line 1735, in call
    **cdata['kwargs'])
  File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1653, in wrapper
    return f(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\states\archive.py", line 414, in extracted
    files = __salt__['archive.unzip'](filename, name, trim_output=trim_output, password=password)
  File "c:\salt\bin\lib\site-packages\salt\modules\archive.py", line 611, in unzip
    'Exception encountered unpacking zipfile: {0}'.format(exc)
CommandExecutionError: Exception encountered unpacking zipfile: [Errno 2] No such file or directory: 'c:\\salt\\var\\cache\\salt\\minion\\files\\base\\c__Apache24_htdocs_ics_repo_.zip'

2018-08-27 17:23:59 [salt.loaded.int.states.archive][WARNING ] Cannot find unzip command for archive.cmd_unzip: using archive.unzip instead
2018-08-27 17:23:59 [salt.loaded.int.module.archive][WARNING ] Due to bug 15795 in python's zip lib, the permissions of the extracted files may not be preserved when using archive.unzip
2018-08-27 17:23:59 [salt.loaded.int.module .archive][WARNING ] To preserve the permissions of extracted files, use archive.cmd_unzip
  
If the zip file is located on the primary (ie salt) the archive.extracted function works without a problem.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
deploy_c2_apps_compressed_to_Enterprise_Server:
  archive.extracted:
    - name: 'c:/Apache24/htdocs/ics_repo'
    - source:
      - salt://ngc/deploy_to_servers/ics_repo.zip
      - http://10.200.56.70:4507/ics_repo.zip
    - archive_format: zip
    - user: administrator
    - if_missing: 'c:/Apache24/htdocs/ics_repo'

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Two Windows servers and Salt-Master on the same IP span. The 2003 server is setup as the secondary source of the zip file. Port 4507 has been configured as the listen port for Apache web server. The 2008 server is a reverse proxy configuration pointing to the 2003 server.
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Version report for Windows Server 2008R2
C:\salt>salt-call --local --versions
Salt Version:
           Salt: 2016.3.6

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:
0 32 bit (Intel)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.5

System Versions:
           dist:
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7600 SP0 Multiprocessor Free

Version report for Windows Server 2003
Salt Version:
           Salt: 2016.3.6
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:19:22) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.5
 
System Versions:
           dist:   
        machine: x86
        release: UNKServer
         system: Windows
        version: UNKServer 5.2.3790 SP2 Multiprocessor Free

**Comment by rickh563** [comment]
ZD-2809

**Comment by Ch3LL** [comment]
i was able to replicate this on 2016.3.6. Fortunately it looks like this is working in 2017.7.7, but to note you will need to either specify the hash of the file or add `skip_verify: True` to your state as the hash is required by default if skip_verify is not set.

**Comment by dfragazi** [comment]
Thanks Megan. I’ll add the skip_verify.

Dennis

**Comment by Ch3LL** [comment]
awesome! i'll go ahead and close this issue but let me know if it needs to be reopened
