### ISSUE TITLE
new groups do not get created

### ISSUE THREAD

**Issue by jaggura** [saltstack/salt#49439]
### Description of Issue/Question
I have a new state file that had many changes to try to get groups configured into the Linux OS.  I can get my users added from a similar set-up but not groups.  I added the salt.log.error call to confirm I entered the state file and I have confirmed the logic does print 'here'.

What else do I need to consider to get the groups created?  I confirmed spacing, no tabs, and file mode and ownership.

### Setup

top.sls includes directory:  groups
groups directory has init.sls that includes the following group state file.
```
freedog_group:
  group.present:
    - name: freedog
    - gid: 9988
    - system: True

{% do salt.log.error('here') %}
```
### Steps to Reproduce Issue

salt 'servername*' state.highstate
     output doesn't show any freedog group creation.   Log file shows 'here'.

salt --versions-report
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.120-92.70-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

salt-minion --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 7.4 Maipo
         locale: ISO-8859-1
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by jaggura** [comment]
It has to be something with /srv/salt versus /srv/pillar.  When I put this code in /srv/salt path it updates the server successfully.  When I put it in /srv/pillar, it executes because I see the log output, but does not update the server.

susemgr:/srv/pillar/groups # cat init.sls
freedog_group:
  group.present:
    - name: freedog
    - gid: 9988
    - system: True

addgroup_cmd:
  cmd.run:
    - names:
      - 'groupadd -g 77777 xxxd'

{% do salt.log.error('group test') %}

**Comment by Ch3LL** [comment]
/srv/pillar directory is for pillar which renders on the master and wont run the states but will try to render it as pillar and /srv/salt is for you state files. This is expected behavior you need to add them to your /srv/salt directory

**Comment by jaggura** [comment]
Thank you.

[Medline]<http://www.medline.com/?cmpid=eid:signature-logo-US-Default>



Jeffrey Gura
IS-Linux Unix Admin Team Lead
Information Services-Information Service
Medline Industries, Inc.
www.medline.com<http://www.medline.com/?cmpid=eid:signature-link-US-Default>


847-643-4847 (Phone)
847-344-6367 (Mobile)
jgura@medline.com<mailto:JGura@medline.com>

**Comment by Ch3LL** [comment]
no problem. i'll go ahead and close this issue but please let me know if it needs to be re-opened.
