### ISSUE TITLE
Iptables rule fails when using the uid-owner module 

### ISSUE THREAD

**Issue by alandrees** [saltstack/salt#49479]
### Description of Issue/Question
I am trying to create a iptables rule (using the pyobjects renderer) using the uid-owner module, and two problems arise:

1. the iptables rule which gets generated does not include `-m owner`
2. It also adds the `for ipv4`, which even when manually adding the iptables rule, the rule gets rejected.

### Setup
    Iptables.append(**{'id_'         : 'allow_outgoing_ssh',
                       'table'       : 'filter',
                       'chain'       : 'OUTPUT',
                       'jump'        : 'ACCEPT',
                       'destination' : "192.168.1.232/32",
                       'protocol'    : 'tcp',
                       'dport'       : 22,
                       'uid-owner'   : 1000,
                       'save'        : True})

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Attempting to run that against a host, runs into the following error:

          ID: allow_outgoing_ssh
    Function: iptables.append
      Result: False
     Comment: Failed to set iptables rule for allow_outgoing_ssh.
              Attempted rule was /sbin/iptables --wait -t filter -A OUTPUT  -p tcp --dport 22 --uid-owner 1000 --destination 192.168.1.232/32 --jump ACCEPT for ipv4
     Started: 11:24:34.529956
    Duration: 282.573 ms
     Changes:   

Which is incorrect, as the `--uid-owner 1000` argument requires a preceeding `-m owner`.

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Jan 19 2017, 14:11:04)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 9.4

**Comment by garethgreenaway** [comment]
@alandrees Thanks for the report.  At the moment the `iptables` module is not looking to see if the `uid-owner` parameter is included and automatically adding the `owner` module.  However, if you update your call to the following:
```
Iptables.append(**{'id_'         : 'allow_outgoing_ssh',
                   'table'       : 'filter',
                   'chain'       : 'OUTPUT',
                   'jump'        : 'ACCEPT',
                   'destination' : "192.168.1.232/32",
                   'protocol'    : 'tcp',
                   'dport'       : 22,
                   'match'     : 'owner',
                   'uid-owner'   : 1000,
                   'save'        : True})
```

I believe it should do what you're trying to accomplish.
