### ISSUE TITLE
Feature: allow inclusion of pillars from other environment

### ISSUE THREAD

**Issue by zerthimon** [saltstack/salt#49495]
State can include state from other environment using this syntax:

```
include:
  - some_env: some_state
```

This, however, doesn't work for pillars, resulting in error:
```
[ERROR   ] Got a bad pillar from master, type str, expecting dict:
```

It would be very convenient to have the ability to include pillars from other environments.

**Comment by Ch3LL** [comment]
will approve as a feature request :)

**Comment by zerthimon** [comment]
... which made me wondering: should this just work and it's actually a bug ? @Ch3LL

**Comment by Ch3LL** [comment]
if the change to add this for pillar is not super intrusive i am okay adding this into a bug fix release, but my concern is it might be more intrusive, but wouldn't know until someone dove into it.
