### ISSUE TITLE
Error with cron module

### ISSUE THREAD

**Issue by nidhi-chourasia** [saltstack/salt#49509]
### Description of Issue/Question

All the cron states are failing.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
The state giving the error is:

stop_push_logs:
  cron.absent:
    - identifier: push_logs_to_s3
    - name: /usr/bin/pushlogs.sh -r
    - user: root
    - special: '@hourly'

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

       ID: stop_push_logs
    Function: cron.absent
        Name: /usr/bin/pushlogs.sh -r
      Result: False
     Comment: State 'cron.absent' was not found in SLS 'anonymous_state'
              Reason: 'cron' __virtual__ returned False: cron module could not be loaded

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
For salt master:
Salt Version:
           Salt: 2016.11.9

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Mar  1 2015, 12:57:24)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.2
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.2

For salt-minion:
Salt Version:
           Salt: 2016.11.9

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.6
        machine: x86_64
        release: 3.16.0-4-amd64
         system: Linux
        version: debian 8.6

**Comment by garethgreenaway** [comment]
@nidhi-chourasia Thanks for the report.  The above error indicates that the cron Salt module was unable to be loaded.  The module checks that the crontab binary is installed and available, if it is not then the module will not be available.  Can you ensure that the crontab binary is installed?

**Comment by nidhi-chourasia** [comment]
I wanted to check that because it is working in other places but could not find the exact command to do so.
How to check if that binary is installed.Sorry if I am question is stupid .I am new to this.Thanks for the reply.
@g

**Comment by nidhi-chourasia** [comment]
@garethgreenaway

**Comment by garethgreenaway** [comment]
@nidhi-chourasia Assuming Saltstack is configured using the defaults it will be running as root, so as the root user type `which crontab` at the command line to ensure that it's available.

**Comment by nidhi-chourasia** [comment]
It was not installed.It is working now.Thanks.
@garethgreenaway
