### ISSUE TITLE
Question: how to use salt-cloud commands with salt-api, when positional args are  needed?

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#49529]
Salt versions: 2017+

### Description of Issue/Question
On this doc it is said that runner does not take positional arguments.

So how to do a "salt-cloud -a stop INSTANCE" with salt-api?

How to name the "stop" argument?

curl -s http://btt2026vu:8443 -o /data/rundeck/var/tmp/saltapi-resp.sLTI -H 'Content-type: application/json' -H 'X-Auth-Token: 6d2f74b463f8c4f7a93665e2cfebda4648271113' -d '[{"client":"runner","provider":"vcenter","instance":"INSTANCE","fun":"cloud.action","arg":["stop"]}]'

-> Does nothing, and no errors..

**Comment by Ch3LL** [comment]
you need to pass as kwarg:

```
curl -sS localhost:8000/run -H 'Accept: application/x-yaml' -H 'Content-type: application/json'  -d '[{
        "client": "runner",
        "fun": "cloud.action",
        "username": "",
        "password": "",
        "eauth": "pam",
        "kwarg": {
          "func": "stop",
          "instance": "ch3ll-cent7"
        }
}]'
```

**Comment by gaetanquentin** [comment]
ok thanks a lot. where is this explained in the doc?

**Comment by gaetanquentin** [comment]
And shouldn't the api return error when args are missing or badly named?

**Comment by Ch3LL** [comment]
its in the docs right here: https://docs.saltstack.com/en/latest/topics/netapi/index.html#salt.netapi.NetapiClient.runner

> Note that runner functions must be called using keyword arguments. Positional arguments are not supported.

What docs were you looking at, maybe we can add a note somewhere else to clear it up?

if i recall correctly i remember getting an error that i wasn't passing the correct args when i was testing. What are you getting returned?

**Comment by gaetanquentin** [comment]
the doc i am looking for is the one where it is said that to have an api equivalent of a cli command, we have to turn positional arguments  of cli commands (salt-cloud) into kwargs arguments named "func".

i have done new tests and i am quite confused, my report was incorrect:

- i wanted the api equivalent of:
salt-cloud -f list_hosts vcenter

So i guessed that it was the runner to call  in api but, it is very hard to find theapi  equivalent with arguments:

we can guess that is is the cloud.action to call but how to translate the "list_hosts" positional argument of the cli? I have just realized that we can name them "arg", or "func" : it works with the 2 of them:
 
curl -vv -s http://XXX  -H 'Content-type: application/json' -H 'X-Auth-Token: 5db199dd36ce3df827def5172a432febec41bb13' -d '[{"client":"runner","provider":"vcenter","fun":"cloud.action","arg":"list_hosts"}]'

curl -vv -s http://XXX  -H 'Content-type: application/json' -H 'X-Auth-Token: 5db199dd36ce3df827def5172a432febec41bb13' -d '[{"client":"runner","provider":"vcenter","fun":"cloud.action","func":"list_hosts"}]'


- If i add a kwarg not used for this function:
 "instance":"XXX"

i will have this in return:
{"return": [{}]}

Shouldn't be an error instead?

**Comment by Ch3LL** [comment]
ahh gotchya yea i think we would want to add the error here. I'll label this as a salt-api bug then to improve the error reporting here.
