### ISSUE TITLE
[salt-cloud] Non-ascii chars cause an exception in salt-cloud

### ISSUE THREAD

**Issue by MTecknology** [saltstack/salt#49523]
### Description of Issue/Question

If a bootstrap script produces a non-ascii character, salt-cloud will produce an exception when trying to print that text to the console. I suspect this is a case of some missing `.encode('utf-8')`'s.

### Steps to Reproduce Issue

The following bootstrap script is the simplest example I can come up with that reproduces the issue.

```
#!/usr/bin/env python
print(u'\u2018')
```

It will produce an error similar to this:
```
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2018' in position 89: ordinal not in range(128)
```

### Versions Report

root@prd-salt-01:/etc/salt# salt --versions-report
Salt Version:
           Salt: 2018.3.2
 
System Versions:
           dist: debian 9.5 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.18-4-pve
         system: Linux
        version: debian 9.5

**Comment by Ch3LL** [comment]
thanks for the PR. Looks like there are some comments on the PR there to change the encoding as he stated utf-8 will not work for everyone. I would also take a look at `salt.utils.data` there are some useful functions there that also handle cases for python2 and python3.

**Comment by rbjorklin** [comment]
I had a quick look and all of these might be duplicates:

https://github.com/saltstack/salt/issues/49304
https://github.com/saltstack/salt/issues/48825
https://github.com/saltstack/salt/issues/49816

Which will all be solved once this has been completed: https://github.com/saltstack/salt/issues/37692

**Comment by Ch3LL** [comment]
oh i commented before viewing the issue you referenced. We should keep this open as we probably just need to update in vt.py to handle this since we added a bunch of unicode work in the 2018.3 release.

**Comment by Ch3LL** [comment]
i'm wondering if we need to do something similar to https://github.com/saltstack/salt/pull/49525 which was closed because utf-8 wont work for everyone. i'm wondering if right there we just need to do `salt.utils.to_unicode`.

**Comment by MTecknology** [comment]
I'd be interesting in taking another look at this. Can you show me an example or two so I could make sure I implement this properly? It's not as simple as just replacing foo.encode('utf-8') with salt.utils.to_unicode(foo), is it?

**Comment by Ch3LL** [comment]
yes i believe that might work. without being familiar with the code or really diving in i'm guessing its either the use case for `to_unicode`, `salt.utils.data.decode()`, or `salt.utils.data.encode()`

**Comment by damon-atkins** [comment]
This should fail the `locale: ANSI_X3.4-1968` i.e. ASCII  not `UTF-8` 

If you expect input to be UTF-8 you need your local to be UTF-8 or tell salt you expect it to be the input not hard code it.  It will break other platforms.
