### ISSUE TITLE
Masterstate system

### ISSUE THREAD

**Issue by thatch45** [saltstack/salt#4953]
Add the ability to compile the state tree on the master and only make the final highdata and files available to the calling mininon

**Comment by jraby** [comment]
Hey guys, are you planning to work on this eventually?

It kind of break the principle of least surprise that any minion can execute any states defined on the master and fetch any file from the fileserver. Or at least, I was surprised when I realized this, after more than a year of use...

**Comment by kiorky** [comment]
It is an add or a replace ? as if the state tree is compiled on master, then if we use exec mods on our states, it will have to be re implemented elseway.

**Comment by basepi** [comment]
This is actually mostly done. We do this for `salt-ssh`, compile the states on the master. What we do need to do, however, is create the ability to easily create portable state runs via state.pkg. 

I created a new issue for this smaller task: https://github.com/saltstack/salt/issues/21561

**Comment by kiorky** [comment]
@basepi you didnt answer here, can i have an answer please :).

**Comment by basepi** [comment]
@kiorky I don't understand the question, could you clarify?

**Comment by kiorky** [comment]
@basepi 
If the compilation which happens nowadays on minion side, is removed, it is more that a huge workflow change.
Eg, we can use execution modules to modulate the states from jinja, and this minion side, on the context of what is on the minion and what the minion sees.
If the states come into the minion, pre and hard baked, without how it is today, it is more than a little change and maybe it does not fits for everyone.
If it is just an option, or not the default, then great, another cool feature !

**Comment by basepi** [comment]
@kiorky No, we will not be changing the current state execution at all. This will be an additional option to make portable state runs. It will actually be a little bit limited -- for example we won't be able to use jinja which uses minion-specific data, such as grains or pillar or execution module calls -- because the state pkg is only lowdata, which is all post-render.

Anyway, no worries, this will not affect the current state system.

**Comment by jraby** [comment]
@basepi  your explanation seem to contradict the description of the issue:

> Add the ability to compile the state tree on the master and only make the final highdata and files available to the calling mininon


vs

> ...
> It will actually be a little bit limited -- for example we won't be able to use jinja which uses minion- specific data, such as grains or pillar or execution module calls -- because the state pkg is only lowdata, which is all post-render.
```

What was asked for in the original #4763 issue, if I understand it correctly, was a way to limit what a minion could have access to, to exactly what its highstate is.  (and that's what I'm looking for :)

**Comment by kiorky** [comment]
Yep, i think that i totally well understood what the feature does, and the usefulness in setups (enforce things from master, compile less on limited minions where we would only transfer static states (either for security reasons or minion capabilities)).
I was just unsure if it was a will to harden things and let be only masterside, as an only default.
You just made me happy by telling me that it is just another feature salt will can do.
Maybe the ultimate behavior would be to have the ability to mix the behaviors, to tell where (inside the top file would be logical) we can compile on minions, and where we must transfer a static payload (highdata + files).

**Comment by kiorky** [comment]
oups, cc @basepi

**Comment by basepi** [comment]
@jraby This will be possible. If you keep your statefiles out of the fileserver area that's accessible to the minion, you can just provide the minion with access to the state pkg which contains the low data and the necessary files.

There are a number of open issues about limiting minion access to the fileserver, which is largely a separate issue.

@kiorky Cool, glad we got on the same page.
