### ISSUE TITLE
Removal of build products while building the Minion (Windows)

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#49566]
### Question 1

During the creation of the Nullsoft NSIS Minion installer, build products of a previous build are removed also by calling:
https://github.com/saltstack/salt/blob/7bde9a720f67b52764600d936c936af5b2ff6c18/pkg/windows/build.bat#L117

On my machine this command becomes `rd /s /q "c:/git/salt\dist"` and this directory does not exist.

Could `"%SrcDir%\dist"`  ever exist? 

If no, then I propose to delete  the command.

If yes, then I propose to prepend `if exist "%SrcDir%/dist"`.

### Question 2

I propose to replace 
https://github.com/saltstack/salt/blob/7bde9a720f67b52764600d936c936af5b2ff6c18/pkg/windows/build.bat#L116-L117

with `python setup.py clean --all`

**Comment by garethgreenaway** [comment]
@twangboy @dwoz Thoughts?

**Comment by twangboy** [comment]
The directory does exist if the setup.py has been run on the machine previously. The above PR should address this issue.

**Comment by markuskramerIgitt** [comment]
I tested above PR removes, it works and removes an error message.
