### ISSUE TITLE
ps.pgrep doesn't use regex pattern matching

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#49565]
### Description of Issue/Question
Unlike the `pgrep` command line utility, `ps.pgrep` doesn't use regex pattern matching. This confusion is exacerbated by the [use of the word "pattern"](https://github.com/saltstack/salt/blob/develop/salt/modules/ps.py#L315) as an argument for the module. As shown in the [code](https://github.com/saltstack/salt/blob/develop/salt/modules/ps.py#L342), a Python "in" statement is use for straight string matching.

### Setup
N/A

### Steps to Reproduce Issue
```
[root@localhost ~]# salt-call ps.pgrep 'bash' user=nick full=True
local:
    - 19813
    - 33659
[root@localhost ~]# salt-call ps.pgrep 'b.sh' user=nick full=True
local:
    None
[root@localhost ~]# pgrep -u 1001 'bash'
19813
33659
[root@localhost ~]# pgrep -u 1001 'b.sh'
19813
33659
```

### Versions Report
All versions? The code is still like this in develop as of this date.

**Comment by garethgreenaway** [comment]
@nicholasmhughes Thanks for the report.  Since this would change current functionality I'm going to mark is as a feature request.  Ideally we want to handle situations where what is passed can be indicated as a raw string, eg. something like file.py, but also indicate that it should be treated as a pattern.  An additional argument would be indicating that the string should be a regular expression would be a great way to accomplish this.

**Comment by nicholasmhughes** [comment]
@garethgreenaway the concern is that an input static string "pattern" will be inadvertently parsed as a regex pattern (I'm looking for exactly `b<dot>sh`, and the change will cause `b<any character>sh` to match), correct?

Something like `pattern_is_regex=True/False`, which defaults to `False`?

**Comment by garethgreenaway** [comment]
@nicholasmhughes Exactly the concern I was thinking of and `patter_is_regex` would be perfect.

**Comment by nicholasmhughes** [comment]
@garethgreenaway take a look at #49598 when you have a moment and let me know if that's what you were thinking.

**Comment by nicholasmhughes** [comment]
New functionality for posterity:
```
[root@localhost ~]# salt-call ps.pgrep 'sshd:' user=centos full=True pattern_is_regex=False
local:
    - 1671
[root@localhost ~]# salt-call ps.pgrep 'ssh.:' user=centos full=True pattern_is_regex=False
local:
    None
[root@localhost ~]# salt-call ps.pgrep 'ssh.:' user=centos full=True pattern_is_regex=True
local:
    - 1671
[root@localhost ~]# salt-call ps.pgrep 'sshd' user=centos full=False pattern_is_regex=False
local:
    - 1671
[root@localhost ~]# salt-call ps.pgrep 'ssh.' user=centos full=False pattern_is_regex=False
local:
    None
[root@localhost ~]# salt-call ps.pgrep 'ssh.' user=centos full=False pattern_is_regex=True
local:
    - 1671
```
