### ISSUE TITLE
Documentation issue, Sphinx having inheritance issues with rest_tornado.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#49575]
### Description of Issue/Question

It looks like the documentation for rest_tornado is having an issue with the rendering of the class docstrings.
This is only happening on the classes. such as https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_tornado.html#salt.netapi.rest_tornado.saltnado.SaltAPIHandler

Looks to be related to the inheritance of the class.

**Comment by whytewolf** [comment]
ZD-2816

**Comment by rallytime** [comment]
I poked around at this a little bit today, and I fixed a couple of issues with the sphinx warnings, but wasn't able to figure out why this is happening without digging into sphinx more. It definitely is related to sphinx interpreting the `__builtins__` of the classes.

**Comment by cachedout** [comment]
@rallytime 

Did you look at the Sphinx config? I vaguely remember having to mock these out once in the config to get the build to work because CherryPy was possibly getting in the way? It was a long time ago, though. Fixing this might not be easy.

**Comment by rallytime** [comment]
@cachedout I did poke around in there, yes, but there isn't anything that looks to resolve this issue. At least not with the CherryPy mocking. IIRC, mocking those functions is more to get the docs to build at all, not necessarily something that deals with builtins because of the way the classes are inherited. I'm not sure though because I'm not very familiar with the internals of sphinx. I think you're right that this will be tricky to track down.

**Comment by garethgreenaway** [comment]
Did some digging on this one and it seems related to the tornado mocking.  The moment I comment out all the tornado mocking in conf.py then this particular page builds as expected.

**Comment by rallytime** [comment]
It's possible that the tornado mocking was added long ago. I wonder if it is still needed?

**Comment by garethgreenaway** [comment]
@rallytime Looks like they've been there for 4-5 years, one was added 5 months ago.

**Comment by whytewolf** [comment]
this documentation is still broken

**Comment by sagetherage** [comment]
@garethgreenaway looks like this is still an issue, can you check please?

**Comment by garethgreenaway** [comment]
I believe this is actually fixed now with the release of 3000 and the vendoring of tornado.

**Comment by whytewolf** [comment]
with the v3000 release, this does look fixed.
