### ISSUE TITLE
How to group actions?

### ISSUE THREAD

**Issue by wsw70** [saltstack/salt#49583]
### Description of Question

I am trying to write some `.sls` files beyond what is provided in the examples and I am completely at loss when it comes to understanding when to use a dash and when not.

Below is an example of a state which is supposed to configure `salt-call` on minions:

    '/etc/systemd/system/salt-call.service':
      file.managed:
        - source: salt-call.service
    
    '/etc/systemd/system/salt-call.timer':
      file.managed:
        - source: salt-call.timer
    
    'salt-call.timer':
      systemd:
        enable: []
        start: []
    
    restart-if-changed:
      systemd.systemctl_reload:
        - on_change: '/etc/systemd/system/salt-call.service'
        - on_change: '/etc/systemd/system/salt-call.timer'

I tried all kind or combinations for the `salt-call.timer` :

    'salt-call.timer':
      systemd:
        enable: []
        start: []

    'salt-call.timer':
      systemd:
        - enable: []
        - start: []

    'salt-call.timer':
      systemd.enable: []
      systemd.start: []

    'salt-call.timer':
      - systemd.enable: []
      - systemd.start: []

and possibly a few others - all end with cryptic errors such as 

    State 'salt-call.timer' in SLS 'salt-call' is not formed as a list

**Is there a simple rule on how to format this file, specifically when to use bare commands/options, and when to append them with a dash?**

I understand that this is a YAML file and that a dash corresponds to a list while a bare entry to a dictionary key but this does not help much without understanding what should be used in which case.

**Comment by Ch3LL** [comment]
you should be able to just use `service.running` with `enable=True`. There is no need to call both of them.

So to show you the full example:

```
sshd:
  service.running:
    - enable: True
```
