### ISSUE TITLE
Problem while using custom returners with salt.client.Caller().

### ISSUE THREAD

**Issue by sundowner69** [saltstack/salt#49587]
### Description of Issue/Question
I am using custom returners to create different log file on the minions. This is working from the command line with:
salt '*' state.apply mystate --return=myreturner 
or
salt-call state.apply mystate --return=myreturner

I am using the same returner in python scripts too and is working fine:
<pre><code>
import salt.client
local=salt.client.LocalClient()
local.cmd('*','state.apply',['mystate'],ret=myreturner)
</code></pre>
But if I try to use the returner in a Caller it doesn't work like expected.
<pre><code>
import salt.client
__opts__ = salt.config.minion_config('/etc/salt/minion')
local = salt.client.Caller(mopts=__opts__ )
local.cmd('state.apply',['mystate'],ret='myreturner')
</code></pre>
The state has been executed without any errors but the returner doesn't work.

Where do I miss the point? Do I use the wrong options? The caller.cmd does not seem to care about any option I provide..
Maybe you can show me how to handle this. Thank you very much in advance.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.138-94.39-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by garethgreenaway** [comment]
@sundowner69 Thanks for the report.  Definitely seems to be a bug.  Native returners are not called properly.  We'll get this fixed.

**Comment by garethgreenaway** [comment]
@sundowner69 I spent some more time digging into this and this is actually the expected behavior: 
```
import salt.client
__opts__ = salt.config.minion_config('/etc/salt/minion')
local = salt.client.Caller(mopts=__opts__ )
local.cmd('state.apply',['mystate'],ret='myreturner')
```

Is the equivalent of running `salt-call --local` from the command line.  Neither one is expecting or using a local minion or a master, so returners are not available.

**Comment by sundowner69** [comment]
@garethgreenaway Thank you very much for the analysis. I am just curious, is there any technical reason for that limitation?
