### ISSUE TITLE
saltclass master_tops custom grains & sdb

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#49599]
Hi,

If I use saltclass to replace top-formula, should I keep a top-formula for custom _grains/_sdb or is there a native way in saltclass to distribute these ?

Best regards,

**Comment by garethgreenaway** [comment]
@saltstack/team-core Anyone know saltclass care to weigh in on this question?

**Comment by gtmanfred** [comment]
@olivier-mauras can you comment on this?
