### ISSUE TITLE
[RFE] Salt could use a pillar that provides initial random secrets and stores them on the master

### ISSUE THREAD

**Issue by jdelic** [saltstack/salt#49603]
### Problem Space
A common way to introduce and manage secrets with Salt is to have a git submodule in your Salt configuration that contains them. Thereby your secrets are spread to a whole number of people in your organization. Other third-party solutions, like Hashicorp Vault or CertHub, provide you with good storage solutions, but have a chicken/egg problem while bootstrapping a cluster. There are some proprietary solutions in different cloud environments (Google KMS, AWS Secrets manager) that solve this problem, but they lock you into a specific environment.

Salt itself provides a number of ways to put secrets into the master configuration.  

 * Some, like SDB, are not integrated with the `top.sls` structure, therefor providing little privilege separation. 
 * Others, like encrypted pillars, are static, but at least secure.

### Idea
I think that a simple pillar-integrated system to create secure, random values for pillars, managed by the master and assigned to minions through `top.sls` would easily close the gap between bootstrapping a cluster from a Salt master and bringing up a secure secrets storage solution like Vault. 

In my own configuration I tend to think of these as two tiers. Tier one contains services that provide the basic building blocks for then dropping tier two services into the cluster. All tier two services can create, manage and store their secrets in Vault. But bringing the cluster to the point where Vault is available already requires a number of secrets to be spread between the Salt master and minions. For example: Secure, random values must be created for "the consul encryption key", "each node's consul ACL token", "SSH host keys" and more.

### Possible Solutions
I built [jdelic/dynamicsecrets](https://github.com/jdelic/dynamicsecrets/) for my own purposes to solve this exact problem. It's a `ext_pillar` with it's own logic to filter values to hosts that have certain grains or node ids. However, I think that it would be useful to include such functionality in Salt proper. This might be as simple as integrating my solution, but I only implemented a small part of the many host-matching options that Salt itself provides. Perhaps someone can point me to how to reuse Salt's own matching engine. A better solution might be to extend the SDB mechanism to support pillar-like assignment. 

I might also be missing the forest for the trees and such a feature might already exist somewhere else.

Anyway, I'd be interested in starting the discussion around what a feature like this can look like. Thank you.

**Comment by garethgreenaway** [comment]
@saltstack/team-core Thoughts?
