### ISSUE TITLE
Installation error, probably releated to #28144

### ISSUE THREAD

**Issue by tganzeboom** [saltstack/salt#49600]
### Description of Issue/Question

The GPG keys listed for the "Saltstack Repo" repository are already installed but they are not correct for this package.
Check that the correct key URLs are configured for this repository.

Failing package is: python-jinja2-2.7.2-2.el7.noarch

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Can't, because the salt-minion won't install. Trying to install via custom repo through Satellite 6. Probably related to issue #28144.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

yum -y install salt-minion

Won't install with the above mentioned error in the description.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Master:
salt --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo

Minion does not install

**Comment by tganzeboom** [comment]
Seems to be related to issue #29094, missing the RPM-GPG-KEY-CentOS-7.

**Comment by tganzeboom** [comment]
..... continuing here

> [Salt-latest]
metadata_expire = 1
sslclientcert = /etc/pki/entitlement/8204124746525827413.pem
baseurl = https://somewhere.com/pulp/repos/somewhere/Library/rhel7_P/custom/Saltstack/Saltstack_Repo
sslverify = 1
name = Saltstack Latest Release Channel for RHEL/Centos $releasever
sslclientkey = /etc/pki/entitlement/8204124746525827413-key.pem
#gpgkey = https://somewhere.com/katello/api/repositories/179/gpg_key_content
gpgkey = file:///etc/pki/rpm-gpg/saltstack-signing-key
         file:///etc/pki/rpm-gpg/RPM-GPG-KEY-CentOS-7
enabled = 1
sslcacert = /etc/rhsm/ca/katello-server-ca.pem
gpgcheck = 1

and now it worked.

**Comment by rootchord** [comment]
Has anything been done on this? I'm working on automating my salt-minion deployment, but because of this i can't use the bootstrap at all.

**Comment by dmurphy18** [comment]
@rootchord Pyhton-jinja2 should be available from regular RHEL 7 (extras - I believe), the version in base_dir was in case some user had a stripped out repo (RHEL 7.0).

Having issues getting into my RHEL 7.5 but RHEL 7.3 is showing  the following:
python-jinja2.noarch  2.7.2-2.el7  rhui-REGION-rhel-server-releases

and preference should be given to RHEL packages, noting that SaltStack repo.saltstack.com does not contain python-jinja2 for point releases 2018.3.4 and 2019.2.0.

Can you provide the output of 'yum repolist' and try again with one of the latest point releases above.

**Comment by dmurphy18** [comment]
@rootchord Wondering if you have any further information on this issue.

**Comment by dmurphy18** [comment]
Closing this as with latest install repo rpm's also now include the Centos 7 public key along with the SaltStack public key. If you find the issue reoccurs, please reopen
