### ISSUE TITLE
Add an execution module to test load_yaml/load_json

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#49619]
This would be a function that would import the same code used by our Jinja renderer to handle load_yaml/load_json, to be used as a sanity check so one can see what data that map file contains. This would be very helpful to troubleshoot instances in which the data that is loaded doesn't match what the user expects, resulting in SLS errors.

Additionally, it would be useful to also have an option to use grains.filter_by to see what a given platform would load out of that map file.

**Comment by terminalmage** [comment]
Implemented via #51047.

**Comment by sastorsl** [comment]
Would love to see this.

**Comment by max-arnold** [comment]
@sastorsl I backported this feature to the master branch, hopefully it will be included in Salt Neon release: https://github.com/saltstack/salt/pull/55253
