### ISSUE TITLE
AttributeError: 'module' object has no attribute 'UDPLogstashHandler'

### ISSUE THREAD

**Issue by austinbenincasa** [saltstack/salt#49627]
### Description of Issue/Question
 Logstash UDP Module is failing to start. The following stack trace is printed in /var/log/salt/master

```
2018-09-12 08:33:54,678 [salt.utils.process:435 ][INFO    ][12412] Process <clas                                                                                                                                                                                               s 'salt.engines.Engine'> (15903) died with exit status 0, restarting...
2018-09-12 08:33:54,696 [salt.engines     :132 ][CRITICAL][15939] Engine 'logsta                                                                                                                                                                                               sh' could not be started!
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/engines/__init__.py", line 128, in                                                                                                                                                                                                run
    self.engine[self.fun](**kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/engines/logstash.py", line 55, in                                                                                                                                                                                                start
    logstashHandler = logstash.UDPLogstashHandler
AttributeError: 'module' object has no attribute 'UDPLogstashHandler'
```

### Setup

This is was it defined in my master config file.

```
logstash_udp_handler:
  host: 127.0.0.1
  port: 8000
  version: 1
  msg_type: logstash
```

### Steps to Reproduce Issue

This error should be printed whenever you try to deploy a salt state. With the LogstashUDPHandler configured

### Versions Report

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-130-generic
         system: Linux
        version: Ubuntu 16.04 xenial

```

**Comment by Ch3LL** [comment]
what version of logstash are you using?

**Comment by austinbenincasa** [comment]
I am using Logstash 6.4.0

My Logstash config is

```
input {
  udp {
    port => 8000
    codec => json
  }
}

output {
	elasticsearch {
		hosts => "elasticsearch:9200"
	}
}
```

**Comment by Ch3LL** [comment]
sorry i wasn't clear, i meant the python-logstash version?

**Comment by austinbenincasa** [comment]
It looks like I don't have the python-logstash library installed for python2.7.5 which I would assume is causing this error.

This looks like the engine logstash.py is importing itself. Then trying to access UDPLogstashHandler which is not defined in itself. 

``python
# Import third-party libs
try:
    import logstash
    HAS_LOGSTASH = True
except ImportError:
    HAS_LOGSTASH = False


def __virtual__():
    if not HAS_LOGSTASH:
        return False
    else:
        return True

log = logging.getLogger(__name__)


def start(host, port=5959, tag='salt/engine/logstash', proto='udp'):
    '''
    Listen to salt events and forward them to logstash
    '''

    if proto == 'tcp':
        logstashHandler = logstash.TCPLogstashHandler
    elif proto == 'udp':
        logstashHandler = logstash.UDPLogstashHandler

``

**Comment by Ch3LL** [comment]
hmm if you didn't even have python-logstash installed it shouldn't of even loaded the engine because of this:

```
    if not HAS_LOGSTASH:
        return False
```

So i assumed you had an older verison of python-logstash that did not have `UDPLogstashHandler` hence the reason asking for a version so i can check when that was added.

**Comment by austinbenincasa** [comment]
I just double verified and I do not have any version of logstash installed on my system. 
```
Last login: Fri Sep 28 09:42:05 2018 from XXX.XXX.XXX.XXX
abenincasa@computer:~$ python
Python 2.7.12 (default, Dec  4 2017, 14:50:18)
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import logstash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named logstash
>>> exit()
abenincasa@computer:~$ python3
Python 3.5.2 (default, Nov 23 2017, 16:37:01)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logstash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named 'logstash'
>>> exit()
abenincasa@computer:~$ python3.6
Python 3.6.6 (default, Jun 28 2018, 04:42:43)
[GCC 5.4.0 20160609] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import logstash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'logstash'
>>> exit()
```
The salt stack engine is called logstash.py so you are are importing yourself not the library. You can import yourself in python.

**Comment by Ch3LL** [comment]
ahh thanks for clarifying that. so just to clarify if you install the logstash module does it start working?

Also ping @saltstack/team-core what do we usually do in this situations to make sure we catch in the loader that the module is not installed. Just rename the file?

**Comment by gtmanfred** [comment]
yeah, just rename it logstash_return and then set the virtualname to logstash.

**Comment by austinbenincasa** [comment]
Yeah its really weird edge case. It has bitten myself a couple times while writing interfaces for various libraries. Might be worth while to also have `python-logstash` as a requirement for salt-stack?

**Comment by gtmanfred** [comment]
No, we aren't going to do that, that defeats the purpose of all the `__virtual__` functions.

All we have to do is change the name of the engine module to `logstash_engine.py` and then use `__virtualname__` to be `logstash`, so that it still loads into the loader as `logstash`

**Comment by gtmanfred** [comment]
The reason that this is happening, is that we add the `salt/engines` directory to the `sys.path` list when importing modules, so the same thing that is happening here.

https://github.com/saltstack/salt/pull/47726#issuecomment-425740551

**Comment by austinbenincasa** [comment]
Gotcha, makes sense.

**Comment by garethgreenaway** [comment]
Closing this out, if the problem persists please comment & we'll re-open the issue or feel free to open a new issue.
