### ISSUE TITLE
Add a test.master_ping function

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#49621]
This would be used by salt-call to ensure that the minion can talk to the master.

The code to do this already exists as part of the `ping_interval` config option, and could easily be adapted for this purpose.

**Comment by rares-pop** [comment]
I'm trying to understand when would this be useful.

Doing a salt-call without the --local, won't do this?

There is also the status.master module which is doing something similar. Or I got it all wrong?

**Comment by terminalmage** [comment]
@rares-pop good point. I actually was suggested to write this func at SaltConf and was not aware of `status.master`. That function seems to be better suited to this task, so I'll close this.
