### ISSUE TITLE
pkg.installed lacks a good way to install deb packages with a specific architecture

### ISSUE THREAD

**Issue by mostynb** [saltstack/salt#49637]
### Description of Issue/Question

The pkg.installed state does not seem to have a good way to install a specific architecture of a .deb package.  I basically want salt to run something like "apt-get install zlib1g:i386" on an amd64 ubuntu machine, but when I use the name zlib1g:i386 I get a warning that this is a virtual package and support for this will be removed in the flourine release (and by the looks of the git log, support has now been removed).

### Setup / Steps to Reproduce Issue
I have a state like the following:

misc-pkgs:
  pkg.installed:
    - pkgs:
      - zlib1g:i386

When it is applied on an amd64 ubuntu machine, I get the following warning:

    Warnings: The following package(s) are "virtual package" names: zlib1g:i386.
              These will no longer be supported as of the Fluorine release.
              Please update your SLS file(s) to use the actual package name.

But this is not a virtual package, as far as I can tell.  "apt-cache show zlib1g:i386" shows the info for the i386 architecture variant of the zlib1g package.

### Versions Report

Salt version: 2018.3.2 (and I guess this is completely broken in "flourine" / on the master branch now)

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.13.0-45-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@terminalmage Kicking this over to you since you were dealing with virtual packages and the `pkg` modules.

**Comment by terminalmage** [comment]
Are you installing this from some alternate repository? I get this when I try to install on Ubuntu 16.04:

```
root@6c6504dd419f:/# apt-get install zlib1g:i386
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package zlib1g:i386 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'zlib1g:i386' has no installation candidate
```

**Comment by garethgreenaway** [comment]
@terminalmage You might need to enable the other architecture.  https://wiki.debian.org/Multiarch/Implementation

**Comment by mostynb** [comment]
I think you can run "dpkg --add-architecture i386" and then "apt-get update ; apt-get install zlib1g:i386" (all as root).

**Comment by grittyshaker** [comment]
Any progress on this? It was working for me in '2019.2.0' and is no longer working in '3000.2'. [The documentation still states it should work](https://docs.saltstack.com/en/2019.2/ref/modules/all/salt.modules.aptpkg.html#salt.modules.aptpkg.install). This is a major bug for me.

Example of bug _removing_ 32b package and installing 64b package (it should keep the 32b package installed):

```
root@salt:~# salt 'myminion1' pkg.install libgeoip-dev:i386
myminion1:
    ----------
    libgeoip-dev:
        ----------
        new:
            1.6.9-1
        old:
    libgeoip-dev:i386:
        ----------
        new:
        old:
            1.6.9-1
```

**Comment by grittyshaker** [comment]
The problem appears to be somewhere in modules.pkg_resource.parse_targets. I stopped digging because I found a workaround:
```
libgeoip-dev:i386:i386:
  pkg.installed
```

**Comment by terminalmage** [comment]
This appears to have been fixed since this issue was initially opened, but then broken in #55580. I've opened #57084 to fix it.
