### ISSUE TITLE
RSS feed of SaltStack blog

### ISSUE THREAD

**Issue by SuperPommeDeTerre** [saltstack/salt#49636]
### Description of Issue/Question
Hey, you guys have a blog without an RSS/Atom feed. :)

http://www.saltstack.com/blog/

(Seems a regression since #8298)

**Comment by mygithubthrowaway** [comment]
+1 for this, please add feed :)

**Comment by sagetherage** [comment]
The Open Core team no longer owns or develops the dot com site or the blog - will assign to our Community Manager for follow up on a blog RSS feed.

**Comment by sagetherage** [comment]
This has been updated: https://saltproject.io/blog/feed/
