### ISSUE TITLE
Can't set HTTP headers as arg to s3.put to ensure correct Content-Type is set

### ISSUE THREAD

**Issue by colin-stubbs** [saltstack/salt#49649]
### Setup

Using module.run s3.put to place HTML files in an S3 bucket.

### Steps to Reproduce Issue

Try using s3.put to place an object into an S3 bucket.
As s3.put has no header argument available the correct Content-Type will not be set, e.g. text/html
The default is binary/octet-stream and this is what is currently set for any objects created using s3.put

Refer to: https://docs.aws.amazon.com/AmazonS3/latest/API/RESTObjectPUT.html

### Versions Report

n/a - see pull request diff

**Comment by garethgreenaway** [comment]
@colin-stubbs Thanks for the report and the PR!
