### ISSUE TITLE
pillarenv ignored in state.apply: "Specified SLS  ...in environment 'base' is not ain environment 'base' is not available on the salt master

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#49640]
### Description of Issue/Question
Even if specifying saltenv and pillarenv, salt search pillars in base environment in a state apply.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

master:
---------
```
 conf salt:
  top_file_merging_strategy: same
  pillarenv_from_saltenv : True
file_roots:
  base:
    - /data/saltstack/states
  gquentin:
    - /home/gquentin/Work/salt/saltstack/states
pillar_roots:
  base:
    - /data/saltstack/pillar
  gquentin:
    - /home/gquentin/Work/salt/saltstack/pillar
```

Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-43-generic
         system: Linux
        version: Ubuntu 14.04 trusty

minion:
--------
conf:
no saltenv, pillarenv, environment set.

Salt Version:
           Salt: 2017.7.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-133-generic
         system: Linux
        version: Ubuntu 16.04 xenial

states:
---------
 base:
  top.sls:
  base:
    '*':
[...]

 gquentin:
  top.sls:
{{ saltenv }}:
  '*':
[...]
 
pillars
-------
 base:
  top.sls:
  base:
    '*':
[...]

 gquentin:
  top.sls:
{{ saltenv }}:
  '*':
[...]

### Steps to Reproduce Issue
sudo salt   'XXX' state.apply state1,state2,state3  saltenv=gquentin pillarenv=gquentin  test=true

XXX:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'state1,state2,state3' in environment 'base' is not available on the salt master

**Comment by Ch3LL** [comment]
i'm having a hard time replicating this. If you run `salt-run fileserver.file_list saltenv=gquentin` does it show the state sls files? Also what is in your `gquentin` pillar top.sls file. you only shared some of it? Does it include state1,state2 and state3?

**Comment by gaetanquentin** [comment]
- salt-run fileserver.file_list saltenv=gquentin 
yes i can  see states
FYI the  states are not called in top.sls willingly

- i made a mistake in the report: it is not state1, state2, state3,  but pillar1,pillar2,plillar3 of course since it is a pillar error.
So state1, state2,state3 use pillar1,pillar2,pillar3.

 
the fact is that in the error message, it speaks about 'base' environment.
Specified SLS 'dir1.dir2.pillar1' in environment 'base' is not available on the salt master

while i asked him to read pillars in gquentin environment.

when i set the minion conf:
saltenv: gquentin
pillarenv: gquentin
environment: gquentin

i have not the problem, but i don't want to do that since i want to switch between environments (base,develop,gquentin)  easily without restarting minion.

in the gquentin pillar top.sls:

{{ saltenv }}:
  '*':
[ ... ]
{% if salt['pillar.file_exists']('dir1/dir2/pillar1/init.sls' %}
   - dir1/dir2/pillar1/init
{% endif %}
[ ... ]


in the base top.sls (which should not be read, there is not saltenv variable:
base:
  '*':
[ ... ]
{% if salt['pillar.file_exists']('dir1/dir2/pillar1/init.sls' %}
   - dir1/dir2/pillar1/init
{% endif %}
[ ... ]



it looks like it is reading the 'base' top.sls instead gquentin top.sls.

**Comment by gaetanquentin** [comment]
still cannot reproduce?

**Comment by Ch3LL** [comment]
im still not able to reproduce. When you state: `So state1, state2,state3 use pillar1,pillar2,pillar3.` do you mean in the actual `state.apply` call? Because that would not work to call pillar files with state.apply, so not sure where you are specifying i should use that.

I have  the files state1.sls, state2.sls and state3.sls all in the directory ` /home/gquentin/Work/salt/saltstack/states`

I created a docker container so maybe you can see if my setup is incorrect compared to yours:

1. `docker run -it -v ~/git/salt/:/testing/ ch3ll/issues:49640 /bin/bash` (where ~/git/salt is a local cloned git repo of salt with teh version checked out you want to test)

2. `salt-master -d; salt-minion -d`
3. `salt '*' state.apply state1,state2,state3 saltenv=gquentin pillarenv=gquentin test=true`
