### ISSUE TITLE
repo.saltstack.com ubuntu16 making apt crazy

### ISSUE THREAD

**Issue by alexz-kh** [saltstack/salt#49653]
### Description of Issue/Question
`apt` not able to proceed auto-install\update . 

### Setup
```
root@cfg01:/etc/apt/sources.list.d# apt-cache policy libsodium18
libsodium18:
  Installed: 1.0.8-5
  Candidate: 1.0.8-5
  Version table:
 *** 1.0.8-5 500
        500 http://ua.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
     1.0.8-5 1100
       1100 http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2017.7 xenial/main amd64 Packages
###
root@cfg01:/etc/apt/sources.list.d# cat /etc/apt/sources.list.d/saltstack.list 
deb [arch=amd64] http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2017.7/ xenial main
root@cfg01:/etc/apt/sources.list.d# cat /etc/apt/sources.list
deb [arch=amd64] http://ua.archive.ubuntu.com/ubuntu/ xenial main restricted multiverse universe
deb [arch=amd64] http://ua.archive.ubuntu.com/ubuntu/ xenial-updates main restricted multiverse universe
###
root@cfg01:/etc/apt/preferences.d# ll /etc/apt/preferences.d/
total 12
drwxr-xr-x 2 root root 4096 Sep 14 14:44 ./
drwxr-xr-x 6 root root 4096 Sep 14 14:40 ../
-rw-r--r-- 1 root root   57 Sep 14 14:36 saltstack
root@cfg01:/etc/apt/preferences.d# cat /etc/apt/preferences.d/saltstack 

Package: *
Pin: release o=SaltStack
Pin-Priority: 1100

```

### Steps to Reproduce Issue
Configure usual ubuntu 16 repo + salstack16 repo.
Enable basic pining for saltstack repo (see setup description)

Try to run upgrade \ install libsodium18 multiple time.
`apt` will *always* try to downgrade:
```
root@cfg01:/etc/apt/preferences.d# for i in 1 2 3 ; do apt-get install libsodium18 -y --allow-downgrades  ; done
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be DOWNGRADED:
  libsodium18
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 12 not upgraded.
Need to get 0 B/144 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 71433 files and directories currently installed.)
Preparing to unpack .../libsodium18_1.0.8-5_amd64.deb ...
Unpacking libsodium18:amd64 (1.0.8-5) over (1.0.8-5) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Setting up libsodium18:amd64 (1.0.8-5) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be DOWNGRADED:
  libsodium18
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 12 not upgraded.
Need to get 0 B/144 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 71433 files and directories currently installed.)
Preparing to unpack .../libsodium18_1.0.8-5_amd64.deb ...
Unpacking libsodium18:amd64 (1.0.8-5) over (1.0.8-5) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Setting up libsodium18:amd64 (1.0.8-5) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be DOWNGRADED:
  libsodium18
0 upgraded, 0 newly installed, 1 downgraded, 0 to remove and 12 not upgraded.
Need to get 0 B/144 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 71433 files and directories currently installed.)
Preparing to unpack .../libsodium18_1.0.8-5_amd64.deb ...
Unpacking libsodium18:amd64 (1.0.8-5) over (1.0.8-5) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Setting up libsodium18:amd64 (1.0.8-5) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...

```

Exact problem here, that you'r not able to automate process of installation - DOWNGRADED are issue for apt, and wont be proceed automatically w\o extra flag `--allow-downgrades`

**Comment by garethgreenaway** [comment]
@dmurphy18 Thoughts?

**Comment by dmurphy18** [comment]
@alexz-kh Initial thoughts are that a version of a package was built with libsodium18 and is expecting it to be available.  For example: zeromq library libzmq5

root@david-VirtualBox:/home/david# apt-cache depends libzmq5
libzmq5
  Depends: libc6
  Depends: libgcc1
  Depends: libsodium18
  Depends: libstdc++6
root@david-VirtualBox:/home/david#pt-cache policy libzmq5
libzmq5:
  Installed: 4.1.4-7
  Candidate: 4.1.4-7
  Version table:
 *** 4.1.4-7 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
root@david-VirtualBox:/home/david# 

Try downgrading the version of libzmq5, but version 4.1.4 has been in use for some time.

Note this dependency can also be found using the following:
root@david-VirtualBox:/home/david# apt-cache rdepends libsodium18
libsodium18
Reverse Depends:
  libsodium-dbg
  libsodium-dev
  libsodium-dbg
  python3-libnacl
  python-libnacl
  python3-nacl
  python-nacl
  netsniff-ng
  **libzmq5**
  libsodium-dev
  dnscrypt-proxy
  fastd
  dnsdist

**Comment by alexz-kh** [comment]
Issue not in rebuild-ed\forked package or whatever - issue that package have _exactly same version_ .
Anyway, if someone would stuck on same issue, use pin rule:
```
Package: libsodium18
Pin: release o=SaltStack
Pin-Priority: 50

Package: *
Pin: release o=SaltStack
Pin-Priority: 1100
```

**Comment by dmurphy18** [comment]
@alexz-kh Sorry for the latest in replying to this issue but mining through old GitHub issues mentioning me, when I came across this still outstanding issue.

Can you confirm if this is still and issue for you since with recent Salt point releases 2018.3.4 and 2019.2.0,the number of dependencies for Salt have been reduced, for example: for Ubuntu 16.04 Python 2

ubuntu_pkg.sls
 13 ##    - pkg.libsodium.1_0_8.ubuntu1604      ## xenial libsodium18 1.0.8-5
 14     - pkg.python-ioflo.1_5_0.ubuntu1604
 15     - pkg.python-libcloud.1_5_0.ubuntu1604
 16     - pkg.python-libnacl.4_1.ubuntu1604
 17     - pkg.python-raet.0_6_5.ubuntu1604
 18     - pkg.python-timelib.0_2_4.ubuntu1604
 19 ##    - pkg.python-tornado.4_2_1.ubuntu1604 ## xenial 4.2.1-1ubuntu3
 20     - pkg.salt.2018_3_4.ubuntu1604

where essentially there is support for Salt, and transport Raet and its dependencies (deprecated and to be removed in Neon).

ubuntu_pkg is from GitHub repository https://github.com/saltstack/salt-pack/blob/develop/file_roots/versions/2018_3_4/ubuntu_pkg.sls

If the issue is resolved with the above information, please consider closing this issue or provide additional information with which I can help resolve you issue.

**Comment by dmurphy18** [comment]
@alexz-kh Reminder, is this still an issue for you ?, libsodium18 should be coming from the OS, not from Salt's repo.saltstack.com

**Comment by dmurphy18** [comment]
@alexz-kh Reminder, is this still an issue for you ?, libsodium18 should be coming from the OS, not from Salt's repo.saltstack.com.  If the information provided resolves the issue for you, please consider closing this issue.

**Comment by alexz-kh** [comment]
@dmurphy18 i guess issue outdated, lets close it.
For xenial - it was w-aded with pining. for another version's - has no chance to double chceck.
