### ISSUE TITLE
win_system.join_domain returning empty change dictionary

### ISSUE THREAD

**Issue by hrumph** [saltstack/salt#49660]
### Description of Issue/Question
win_system.join does not return a changes dictionary even if changes are made.

**Comment by dwfreed** [comment]
I don't think you intended to tag me.  Perhaps you meant dwoz?  (I've never touched either the win_system execution module or the state module)

**Comment by garethgreenaway** [comment]
@dwfreed Apologies. Wasn't paying attention to the auto-complete. :)

**Comment by hrumph** [comment]
versions report is as follows:
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.7
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, May 15 2018, 15:37:31)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 5.1
            ZMQ: 4.2.5
 
System Versions:
           dist: fedora 27 Twenty Seven
         locale: UTF-8
        machine: x86_64
        release: 4.17.14-102.fc27.x86_64
         system: Linux
        version: Fedora 27 Twenty Seven
```
the salt minion version is also 2018.3.2 (64 bit Python 3)

**Comment by hrumph** [comment]
@Twangboy, I confess that I haven't looked closely at the code (yet). All I know is that when the state is ran I get output like this:

```
          ID: join domain
    Function: system.join_domain
        Name: AD.QUEENSU.CA
      Result: True
     Comment: Computer added to 'AD.QUEENSU.CA'
     Started: 15:32:08.403369
    Duration: 3955.51 ms
     Changes:   
```

Note that the  _Changes:_ subdictionary is empty, even though a change did occur. I would think that I should see the standard _New_ and _Old_ subsubdictionaries.

**Comment by twangboy** [comment]
@hrumph Oooh, OK. I didn't realize we were talking about a state here. The code I posted above was for the execution module. I'll take a look at the code for the state.

**Comment by twangboy** [comment]
The above PR should take care of this issue. Should be in 2018.3.4 and 2017.7.9
