### ISSUE TITLE
IPv6 egress rule is not being pushed to AWS security groups

### ISSUE THREAD

**Issue by kenanbiel** [saltstack/salt#49667]
### Description of Issue/Question

I'm trying to make my AWS security group persistent but IPv6 part is failing.

### Setup
I have two cases:

1) cidr and cidr_ipv6 is only in one block
```
stagingAlbSecGroup:
  boto_secgroup.present:
    - name: staging-security-group
    - description: Default Staging ALB Security Group
    - vpc_name: vpc
    - region: us-east-1
    - rules:
        - ip_protocol: tcp
          from_port: 80
          to_port: 80
          cidr_ip:
            - 0.0.0.0/0
          cidr_ipv6:
            - ::/0
        - ip_protocol: tcp
          from_port: 443
          to_port: 443
          cidr_ip:
            - 0.0.0.0/0
          cidr_ipv6:
            - ::/0
```

- With this one, i don't get an error but IPv6 is not applied, only the IPv4 rules.

2) I've separated the IPv6 cidr block.

```
stagingAlbSecGroup:
  boto_secgroup.present:
    - name: staging-security-group
    - description: Default Staging ALB Security Group
    - vpc_name: vpc
    - region: us-east-1
    - rules:
        - ip_protocol: tcp
          from_port: 80
          to_port: 80
          cidr_ip:
            - 0.0.0.0/0
        - ip_protocol: tcp
          from_port: 80
          to_port: 80
          cidr_ipv6:
            - ::/0
        - ip_protocol: tcp
          from_port: 443
          to_port: 443
          cidr_ip:
            - 0.0.0.0/0
        - ip_protocol: tcp
          from_port: 443
          to_port: 443
          cidr_ipv6:
            - ::/0
```
With this one, i get an error: 

```
----------
          ID: stagingAlbSecGroup
    Function: boto_secgroup.present
        Name: staging-security-group
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1879, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1826, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_secgroup.py", line 196, in present
                  profile=profile)
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_secgroup.py", line 426, in _rules_present
                  to_delete, to_create = _get_rule_changes(rules, sg['rules'])
                File "/usr/lib/python2.7/dist-packages/salt/states/boto_secgroup.py", line 362, in _get_rule_changes
                  raise SaltInvocationError('cidr_ip, source_group_group_id, or'
              SaltInvocationError: cidr_ip, source_group_group_id, or source_group_name must be provided for security group rules.
     Started: 06:14:57.281284
    Duration: 81.012 ms
     Changes:
```

Based on this i'm assuming cidr_ipv6 is not available? So 2 part question:
1) Why isn't it giving me an error in the first case?
2) Any available workaround for this?

### Versions Report

Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1060-aws
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@kenanbiel Thanks for the report.  It appears that the Salt modules that the state module is using behind the scenes does not support using IPv6 values.  Since this would be a new addition, I've marked this as a feature request for a future release.
