### ISSUE TITLE
Open Source website has dead link to docs site

### ISSUE THREAD

**Issue by briancain** [saltstack/salt#49687]
👋 Hi! I was going to see if I could fix this in a PR, but I can't find your repo for the site https://s.saltstack.com/salt-open-source/. Apologies if this is the wrong repo for this.

### Description of Issue/Question

https://s.saltstack.com/salt-open-source/ links to its `GET STARTED` documentation at https://docs.ssaltstack.wpengine.com/en/latest/ , which can't be reached. Instead, it should probably link to https://docs.saltstack.com/en/latest/

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
N/A

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
See description

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
N/A

**Comment by Ch3LL** [comment]
ping @dubb-b i think this is your realm? if not do you know who is?

**Comment by dubb-b** [comment]
@briancain I can submit a fix for this. The website is still in transition from old to new. 

Let me see if I can get the website folks to update that link.

**Comment by dubb-b** [comment]
@briancain this should be complete now.

**Comment by briancain** [comment]
Thanks @Ch3LL @dubb-b !
