### ISSUE TITLE
file.replace never reply false, only true or ""

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#49691]
### Description of Issue/Question
in search mode and dry_run mode:
file.replace never reply false, only true or ""

### Setup
master: (Linux)
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-43-generic
         system: Linux
        version: Ubuntu 14.04 trusty

Minion: (Windows)
    Salt Version:
               Salt: 2016.3.2
     
    Dependency Versions:
               cffi: 1.6.0
           cherrypy: 5.3.0
           dateutil: 2.5.3
              gitdb: 0.6.4
          gitpython: 2.0.2
              ioflo: 1.5.3
             Jinja2: 2.8
            libgit2: Not Installed
            libnacl: 1.4.5
           M2Crypto: Not Installed
               Mako: 1.0.4
       msgpack-pure: Not Installed
     msgpack-python: 0.4.7
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
             pygit2: Not Installed
             Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.3.8
             PyYAML: 3.11
              PyZMQ: 15.2.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: 0.2.4
            Tornado: 4.3
                ZMQ: 4.1.2
     
    System Versions:
               dist:   
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.14393  Multiprocessor Free

### Steps to Reproduce Issue
sudo salt 'XXX' file.replace 'd:\\thing.log' pattern='GOOD_WORD' repl='' count=1 dry_run=True  search_only=True --out=json

{
    "XXX": true
}

sudo salt 'XXX' file.replace 'd:\\thing.log' pattern='BAD_WORD' repl='' count=1 dry_run=True  search_only=True --out=json

{
    "XXX": ""
}

-> should reply "false"

**Comment by Ch3LL** [comment]
it looks like it does a diff: `return ''.join(difflib.unified_diff(orig_file_as_str, new_file_as_str))` and doesn't handle cases when that is empty. looks like we can improve this thanks.

**Comment by garethgreenaway** [comment]
Closing this out, if the problem persists please comment & we'll re-open the issue or feel free to open a new issue.
