### ISSUE TITLE
win_lgpo error: windll.GetSystemDefaultUILanguage - int object has no attribute replace

### ISSUE THREAD

**Issue by bobbysmith007** [saltstack/salt#49699]
### Description of Issue/Question
https://github.com/saltstack/salt/blob/develop/salt/modules/win_lgpo.py#L132
produces AttributeError: 'int' object has no attribute 'replace'

`    INSTALL_LANGUAGE = locale.windows_locale.get(
        windll.GetSystemDefaultUILanguage(), 1033).replace('_', '-')`

It should be either:

`    INSTALL_LANGUAGE = str(locale.windows_locale.get(
        windll.GetSystemDefaultUILanguage(), 1033)).replace('_', '-')`

or perhaps:

`    INSTALL_LANGUAGE = locale.windows_locale.get(
        windll.GetSystemDefaultUILanguage(), "1033").replace('_', '-')`

### Setup
Basic new salt install on a new windows host.

### Steps to Reproduce Issue
Basic new salt install on a new windows host.

### Versions Report
Seems to be across a number of versions
Master:

```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.2.4
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.2.0-18-generic
         system: Linux
        version: Ubuntu 14.04 trusty

```

I am logged out of the minion, but the bug still exists in the master branch

**Comment by Ch3LL** [comment]
did you want to push a PR? seems you have an understanding on the right fix here. thanks :)
