### ISSUE TITLE
Useless requirement for prlsrvctl in Parallels module

### ISSUE THREAD

**Issue by cstarke** [saltstack/salt#49709]
We have machines running PVC 7 without the installation of prlsrvctl.
The module only requires prlsrvctl in one function, which is prlsrvctl(), but the whole module will error if there's no prlsrvctl binary found.

https://github.com/saltstack/salt/blob/ab7dc68c3b033fa46c38fe59ab77bf7d1df36e68/salt/modules/parallels.py#L52

IMHO it would be good to split those dependencies in different functions (like _has_prlctl() and _has_prlsrvctl()) and check within executed functions whether those requirements are met or to omit those checks completely and rely on sane output of the underlying cmd.run() call. ("tell don't ask")

Is that possible? I would create a PR for that if one of my idea is okey or you tell me about another solution.

Thanks :)

**Comment by Ch3LL** [comment]
yeah we would accept that :) if only one module requires that dependency then we only need to do that check in that function.
