### ISSUE TITLE
Support for Azure REST API

### ISSUE THREAD

**Issue by zikalino** [saltstack/salt#49727]
### Description of Issue/Question

I think it would be useful to have a feature similar to this module which I made for Ansible:

https://docs.ansible.com/ansible/latest/modules/azure_rm_resource_module.html

It enables users to easily use entire Azure REST API,
we also built VSC extension and have support in Azure Resource Manager:

https://resources.azure.com/

I would like to learn what's the opinion of Salt community, and who could review my PR if I create one?

**Comment by garethgreenaway** [comment]
@zikalino Thanks for the report.  The Ansible module that you linked to looks like some really solid work.  Currently in Salt we have a Salt cloud module for interacting with Azure.  Did you get a chance to look at that?  There might be some overlap with what you're proposing.
