### ISSUE TITLE
Group state cannot force empty group membership

### ISSUE THREAD

**Issue by MTecknology** [saltstack/salt#49744]
### Description of Issue/Question

As reported on IRC, the following state will produce no changes to group membership.

```
shadow:
  group.present:
    - members: []
```

This happens because the group state checks for false-like values and an empty list is false-like, producing a no-op change.

Desired Outcome: Group 'shadow' has no members.

Realized Outcome: Group 'shadow' member list in unchanged.

### Versions Report

```
root@saltmaster:/srv/salt/system/cis# salt-call --versions-report
Salt Version:
           Salt: 2018.3.2

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
Thanks for the PR!
