### ISSUE TITLE
cmd.script not respecting thin directory in salt-ssh

### ISSUE THREAD

**Issue by delit0** [saltstack/salt#49773]
I've found that in salt-ssh the cmd.script module will ignore the thin_dir option set in the roster file, and will instead only run out of /tmp. This is problematic due to setting noexec on /tmp as a hardening measure.

### Setup
This is an example entry from roster:
```
some_host:
  host: some_ip
  thin_dir: /some/path/to/thin
```

example cmd.script:
```
Run some script:
  cmd.script:
    - source: salt://some/path/to/script
```

### Steps to Reproduce Issue
- Set roster with thin directory
- Re-thin if necessary
- remount /tmp as noexec
- run any script with cmd.script from a state

### Versions Report
Salt Version:
           Salt: 2017.7.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 23 2017, 15:49:48)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-121-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by garethgreenaway** [comment]
@delit0 Thanks for the report.  We'll get this fixed.

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
