### ISSUE TITLE
Pillar in state.sls not work from reactor

### ISSUE THREAD

**Issue by immortalaxay** [saltstack/salt#49789]
### Description of Issue/Question
Pillar in state.sls not works from reactor
Pillar in state.sls works from command line
Pillar is state.apply works from reactor

### --------------------------------------------
$ cat /etc/salt/minion_id 
minion
### --------------------------------------------
$ cat /srv/salt/test.sls 
{% set foo = pillar['foo'] %}

echo_foo:
  cmd.run: 
    - name: 'echo {{ foo }}'
### --------------------------------------------
$ cat /srv/salt/top.sls 
base:
  '*':
     - test
### --------------------------------------------
$ cat /srv/reactor/test.sls 
{% set postdata = data.get('post', {}) %}

test:
  local.state.sls:
    - tgt: '{{ postdata.tgt }}'
    - arg:
      - test
      - pillar: {{ postdata.pillar }}
### --------------------------------------------
$ cat /srv/reactor/test1.sls 
{% set postdata = data.get('post', {}) %}

test1:
  local.state.apply:
    - tgt: '{{ postdata.tgt }}'
    - args:
      - pillar: {{ postdata.pillar }}
### --------------------------------------------
$ cat /etc/salt/master.d/reactor.conf
reactor:
  - 'salt/netapi/hook/test':
    - /srv/reactor/test.sls
  - 'salt/netapi/hook/test1':
    - /srv/reactor/test1.sls
### Result of command line

$ sudo salt 'minion' state.sls test pillar='{ "foo" : "bar" }'
minion:
----------
          ID: echo_foo
    Function: cmd.run
        Name: echo bar
      Result: True
     Comment: Command "echo bar" run
     Started: 08:08:18.430007
    Duration: 13.136 ms
     Changes:   
              ----------
              pid:
                  27747
              retcode:
                  0
              stderr:
              stdout:
                  bar

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  13.136 ms
### state.apply from reactor
$ curl -sS localhost:8000/hook/test1 \
 -b ~/cookies.txt \
 -H 'Content-type: application/json' \
 -d '{ "tgt": "minion", "pillar": { "foo": "bar" } }'
### Events of state.apply from reactor
$ sudo salt-run state.event pretty=True
salt/netapi/hook/test1	{
    "_stamp": "2018-09-26T03:11:36.167124", 
    "body": "{ \"tgt\": \"minion\", \"pillar\": { \"foo\": \"bar\" } }", 
    "headers": {
        "Accept": "*/*", 
        "Content-Length": "48", 
        "Content-Type": "application/json", 
        "Cookie": "session_id=3c22c31693752bf62b9031203a5f34a0d163252b", 
        "Host": "localhost:8000", 
        "Remote-Addr": "127.0.0.1", 
        "User-Agent": "curl/7.35.0"
    }, 
    "post": {
        "pillar": {
            "foo": "bar"
        }, 
        "tgt": "minion"
    }
}
20180926084136355591	{
    "_stamp": "2018-09-26T03:11:36.355977", 
    "minions": [
        "minion"
    ]
}
salt/job/20180926084136355591/new	{
    "_stamp": "2018-09-26T03:11:36.358635", 
    "arg": [
        {
            "__kwarg__": true, 
            "pillar": {
                "foo": "bar"
            }
        }
    ], 
    "fun": "state.apply", 
    "jid": "20180926084136355591", 
    "minions": [
        "minion"
    ], 
    "missing": [], 
    "tgt": "minion", 
    "tgt_type": "glob", 
    "user": "root"
}
minion/refresh/minion	{
    "Minion data cache refresh": "minion", 
    "_stamp": "2018-09-26T03:11:36.541406"
}
salt/job/20180926084136355591/ret/minion	{
    "_stamp": "2018-09-26T03:11:37.381406", 
    "cmd": "_return", 
    "fun": "state.apply", 
    "fun_args": [
        {
            "pillar": {
                "foo": "bar"
            }
        }
    ], 
    "id": "minion", 
    "jid": "20180926084136355591", 
    "out": "highstate", 
    "retcode": 0, 
    "return": {
        "cmd_|-echo_foo_|-echo bar_|-run": {
            "__id__": "echo_foo", 
            "__run_num__": 0, 
            "__sls__": "test", 
            "changes": {
                "pid": 30031, 
                "retcode": 0, 
                "stderr": "", 
                "stdout": "bar"
            }, 
            "comment": "Command \"echo bar\" run", 
            "duration": 31.268, 
            "name": "echo bar", 
            "result": true, 
            "start_time": "08:41:37.327607"
        }
    }, 
    "success": true
}

### state.sls from reactor
$ curl -sS localhost:8000/hook/test \
 -b ~/cookies.txt \
 -H 'Content-type: application/json' \
 -d '{ "tgt": "minion", "pillar": { "foo": "bar" } }'
### Events of state.sls from reactor
$ sudo salt-run state.event pretty=True
salt/netapi/hook/test	{
    "_stamp": "2018-09-26T03:02:54.757862", 
    "body": "{ \"tgt\": \"minion\", \"pillar\": { \"foo\": \"bar\" } }", 
    "headers": {
        "Accept": "*/*", 
        "Content-Length": "48", 
        "Content-Type": "application/json", 
        "Cookie": "session_id=3c22c31693752bf62b9031203a5f34a0d163252b", 
        "Host": "localhost:8000", 
        "Remote-Addr": "127.0.0.1", 
        "User-Agent": "curl/7.35.0"
    }, 
    "post": {
        "pillar": {
            "foo": "bar"
        }, 
        "tgt": "minion"
    }
}
20180926083254971172	{
    "_stamp": "2018-09-26T03:02:54.973273", 
    "minions": [
        "minion"
    ]
}
salt/job/20180926083254971172/new	{
    "_stamp": "2018-09-26T03:02:54.975835", 
    "arg": [
        "test", 
        {
            "pillar": {
                "foo": "bar"
            }
        }
    ], 
    "fun": "state.sls", 
    "jid": "20180926083254971172", 
    "minions": [
        "minion"
    ], 
    "missing": [], 
    "tgt": "minion", 
    "tgt_type": "glob", 
    "user": "root"
}
minion/refresh/minion	{
    "Minion data cache refresh": "minion", 
    "_stamp": "2018-09-26T03:02:55.172777"
}
salt/job/20180926083254971172/ret/minion	{
    "_stamp": "2018-09-26T03:02:55.339205", 
    "cmd": "_return", 
    "fun": "state.sls", 
    "fun_args": [
        "test", 
        {
            "pillar": {
                "foo": "bar"
            }
        }
    ], 
    "id": "minion", 
    "jid": "20180926083254971172", 
    "out": "highstate", 
    "retcode": 1, 
    "return": [
        "Rendering SLS 'base:test' failed: Jinja variable u'salt.pillar object' has no attribute 'foo'"
    ], 
    "success": true
}

### Versions Report
master and minion both are installed on same machine.
$ salt --versions-report 
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Jun 22 2015, 17:58:13)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-61-generic
         system: Linux
        version: Ubuntu 14.04 trusty

**Comment by Ch3LL** [comment]
as documented here: https://docs.saltstack.com/en/latest/topics/reactor/#jinja-context  

> Reactor SLS files only have access to a minimal Jinja context. grains and pillar are not available. 

so this is expected behavior.
