### ISSUE TITLE
boto errors and warnings when invoking "onlyif"

### ISSUE THREAD

**Issue by af85** [saltstack/salt#49788]
### Description of Issue/Question

When using file.recurse, if an "onlyif" parameter is used, several warnings and errors relating to boto are spewed. The onlyif statement works as expected. I understand onlyif isn't documented for the file.recurse function: 
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html#salt.states.file.recurse
That said, I think every function should have a conditional option, or an implementation similar to how ansible "blocks" work with the "when" statement.

### Setup

On Master, create a working test.sls:

copy_dinosaurs:
  file.recurse:
    - name: /etc/dinosaurs/conf.d
    - source: salt://creatures/files/dinosaurs/
    - clean: False

No errors or warnings there. Now update the test.sls to look like the following:

copy_dinosaurs:
  file.recurse:
    - name: /etc/dinosaurs/conf.d
    - source: salt://creatures/files/dinosaurs/
    - clean: False
    - onlyif: '/bin/egrep -q "^dinosaur: dorkasaurus" /etc/salt/grains'

This will produce errors and warnings like:

[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.utils.boto. Module will not be loaded: 'module' object has no attribute '__version__'
[WARNING ] salt.loaded.int.utils.boto.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'boto', please fix this.

### Steps to Reproduce Issue

See "Setup" above.

### Versions Report

MASTER:

#salt --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

The minion is a different host, also running the same versions of CentOS and salt.

**Comment by Ch3LL** [comment]
duplicate of https://github.com/saltstack/salt/issues/47694 fixed in https://github.com/saltstack/salt/pull/47726
