### ISSUE TITLE
Function name different for rebooting the machine in Mac OS vs Windows/Linux

### ISSUE THREAD

**Issue by PraneshRJ** [saltstack/salt#49793]
### Description of Issue/Question
The function name to reboot a machine is "system.restart" in execution module for mac (salt.module.system) and "system.reboot" in execution module for windows/linux.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
This is the behavior using default configuration.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
cmd for mac - salt [machine name] system.restart
cmd for windows/linux - salt [machine name] system.reboot

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
For master:
Salt Version:
           Salt: 2018.3.2

For minion (In all platforms - mac, linux and windows)
Salt Version:
           Salt: 2018.3.2

**Comment by Ch3LL** [comment]
we could possibly setup an alias for mac so not to break backwards compatibility.

**Comment by PraneshRJ** [comment]
I agree. That would be good enough.
