### ISSUE TITLE
netconfig.managed setting changed=1 in test mode/when no changes made

### ISSUE THREAD

**Issue by ngrundler** [saltstack/salt#49814]
### Description of Issue/Question
Running 2018.3.2, I'm noticing the `netconfig.managed` module is returning `(changed=1)` when I run states in test mode, and for states that run but do not actually change anything.

### Setup
just a very basic `netconfig.managed` state that loads a jinja template:
```
---                                                                                                                   
apply-config-template:
  netconfig.managed:
    - template_name: salt://path/to/template.j2
    - replace: True
```
### Steps to Reproduce Issue
Simply run a state:
```
grundler@salt-master:~$ salt 'junos-minion' state.highstate test=true                                                        
junos-minion:                                                                                                               
----------
          ID: apply-config-template
    Function: netconfig.managed
      Result: True
     Comment: Configuration discarded.
     Started: 02:04:17.417462
    Duration: 5538.287 ms
     Changes:   
              ----------
              diff:

Summary for junos-minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   5.538 s
```
### Versions Report

Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-22-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by garethgreenaway** [comment]
@ngrundler Thanks for the report.

**Comment by ngrundler** [comment]
Interesting to note however that `onchanges` requisite appears to still work just fine:
```
grundler@salt-master:~$ salt 'junos-minion' state.sls test.template                                
junos-minion:                                                                                                               
----------
          ID: apply-template
    Function: netconfig.managed
      Result: True
     Comment: Already configured.
     Started: 23:45:35.845456
    Duration: 4358.228 ms
     Changes:   
              ----------
              diff:
----------
          ID: test-on-changes
    Function: module.run
        Name: test.ping
      Result: True
     Comment: State was not run because none of the onchanges reqs changed
     Started: 23:45:40.207110
    Duration: 0.028 ms
     Changes:   

Summary for junos-minion
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time:   4.358 s
```

... and then if I change the config on the minion directly and re-run:
```
grundler@salt-master:~$ salt 'junos-minion' state.sls test.template                           
junos-minion:                                                                                                               
----------
          ID: apply-template
    Function: netconfig.managed
      Result: True
     Comment: Configuration changed!
     Started: 23:46:50.365215
    Duration: 15658.602 ms
     Changes:   
              ----------
              diff:
                  [edit interfaces ge-0/0/0]
                  -   description foo;
----------
          ID: test-on-changes
    Function: module.run
        Name: test.ping
      Result: True
     Comment: Module function test.ping executed
     Started: 23:47:06.026665
    Duration: 9.923 ms
     Changes:   
              ----------
              ret:
                  True

Summary for junos-minion
------------
Succeeded: 2 (changed=2)
Failed:    0
------------
Total states run:     2
Total run time:  15.669 s
```

**Comment by bigpick** [comment]
It looks like I am getting a similar result. Inside a state sls:

```
compare_with_stored_config:
  module.run:
    - net.load_config:
      - filename: salt://configs/{{ hostname }}.cfg
      - test: True
      - replace: True
```
Results in nothing being changed by coming back with a `Succeeded: 1 (changed=1)`

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
