### ISSUE TITLE
"module.run" state does not appear in docs

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#49851]
See https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html

This is likely due to the decorator used for that function. We have the `@depends` decorator which does not cause this problem, so examining them side-by-side should hopefully help reveal what is causing the problem.

**Comment by gtmanfred** [comment]
Duplicate of #45360

**Comment by terminalmage** [comment]
d'oh, I should have searched

**Comment by gtmanfred** [comment]
no worries, i closed the other one
