### ISSUE TITLE
RHEL/CentOS 7.5 masters RSAError: bad signature

### ISSUE THREAD

**Issue by dmarkwat** [saltstack/salt#49863]
### Description of Issue/Question

Master has been running for over a year; it was upgraded to 2018.3.2 from 2017.7.7 about 2 months ago. RHEL 6 (6.9) machines running 2017.7.7 or 2018.3.2 seem to work fine with the master, however RHEL 7 machines (only tested on 7.3 and 7.5) on either minion version 2017.7.7 or 2018.3.2, have grave issues communicating with a 2018.3.2 master when using `state.apply` or `state.sls`. These minions receive the highstate command, process it correctly, sign their returns, and send them, but the master responds with `Minion did not return. [No response]` on the command line and the following in journald:

```
Oct 02 08:04:53 <hostname> salt-master[2277]: [ERROR   ] Error in function _return:
Oct 02 08:04:53 <hostname> salt-master[2277]: Traceback (most recent call last):
Oct 02 08:04:53 <hostname> salt-master[2277]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 1776, in run_func
Oct 02 08:04:53 <hostname> salt-master[2277]: ret = getattr(self, func)(load)
Oct 02 08:04:53 <hostname> salt-master[2277]: File "/usr/lib/python2.7/site-packages/salt/master.py", line 1561, in _return
Oct 02 08:04:53 <hostname> salt-master[2277]: if not salt.crypt.verify_signature(this_minion_pubkey, serialized_load, sig):
Oct 02 08:04:53 <hostname> salt-master[2277]: File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 247, in verify_signature
Oct 02 08:04:53 <hostname> salt-master[2277]: return pubkey.verify(digest, signature)
Oct 02 08:04:53 <hostname> salt-master[2277]: File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 281, in verify
Oct 02 08:04:53 <hostname> salt-master[2277]: return m2.rsa_verify(self.rsa, data, signature, digest_type)
Oct 02 08:04:53 <hostname> salt-master[2277]: RSAError: bad signature
```

All other basic commands seem to work: `test.ping` to simulate simple connectivity; `file.readdir` to simulate basic command-response.

I tried this line of testing with both 2018.3.2 and 2017.7.7 on the same minion machine (after removing all traces of salt on the minion and its key on the master) and I'm met with the same problem.

I further tested this by uninstalling salt on the minion once more and installing 2017.7.7 and joining it to a master that we've kept on 2017.7.7: it works just fine. In fact, all of the RHEL 7 builds appear to work fine when talking to the 2017.7.7 master, just not the 2018.3.2 one.

The only discernible difference between our two installs is the public keys for minion signing (minion_master.pub and master.pub): the 2018.3.2 master uses a `BEGIN RSA PUBLIC KEY` header and the 2017.7.7 master uses a `BEGIN PUBLIC KEY` header. When using M2Crypto directly, same RHEL 7 minion giving issues doesn't like the key containing `RSA` and when I remove `RSA` from the header it doesn't complain (though the minion was suspiciously mum about this in its logs during operation).
Before removing RSA from header:
```
>>> import M2Crypto
>>> M2Crypto.RSA.load_pub_key('/etc/salt/pki/minion/minion_master.pub')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 426, in load_pub_key
    return load_pub_key_bio(bio)
  File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 441, in load_pub_key_bio
    rsa_error()
  File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 330, in rsa_error
    raise RSAError(Err.get_error_message())
M2Crypto.RSA.RSAError: no start line
```
After:
```
>>> import M2Crypto
>>> M2Crypto.RSA.load_pub_key('/etc/salt/pki/minion/minion_master.pub')
<M2Crypto.RSA.RSA_pub instance at 0x7f9fc613f908>
```

I tried changing they key to remove RSA when the minion was talking to the 2018.3 master, but the minion just keeps changing the key back so I can't tell if it's using my modified key.

Another observation in the logs is the `ret_val` line; when this RHEL 7 machine--or any machine for that matter--is talking to a working salt master, I see `ret_val = None`; but when it talks to the 2018.3 master I see `ret_val = `. This occurs right after the signing and returning. I also notice that the 2017.7.7 minion talking to the 2018.3 master has an extra `saltutil.find_job` after it decodes the payload following the minion return which when talking to the 2017.7 master it does not, but that could be nothing.

### Setup
Minion should be configured with
```
minion_sign_messages: True
verify_master_pubkey_sign: True
```
and minion_master.pub file under /etc/salt/pki/minion/

Master should be configured with
```
sign_pub_messages: True
master_sign_pubkey: True
```

#### RHEL 7 master running 2018.3.2 and freshly-minted RHEL 7 minion running 2017.7.7
From master:
- `salt-key -a ...`
- `salt ... test.ping` => True
- `salt ... state.apply test=True` => `Minion did not return. [No response]`
  - logs reveal above RSAError

#### RHEL 7 master running 2017.7.7 and freshly-minted RHEL 7 minion running 2017.7.7
Repeat steps from above; output is shown for state.apply with no RSAError

### Versions Report

Salt master:
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.5
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 0.26.3
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.9.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

Minion (2017.7):
```
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.9.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

**Comment by mattp-** [comment]
this looks familiar to other issues that were being dealt with in the past wrt rsa key handling

**Comment by mattp-** [comment]
https://github.com/saltstack/salt/issues/46868

**Comment by dmarkwat** [comment]
Thanks for the fast response! I did see that one and it does look to be almost the same issue I'm looking at. What tipped me off that maybe it wasn't resolved or possibly different was this comment, https://github.com/saltstack/salt/issues/46868#issuecomment-384667717, detailing that the fix for that issue should be in for 2018.3.1.

Now that I look closer at the stack traces and the PR I think I have a better sense of it: the PR, https://github.com/saltstack/salt/pull/46930, removes the RSA from the header and therefore should make the pub key load on the minion or master; this is reflected in the fact that the minion throws no errors and apparently signs the message and returns it to the master. The master similarly gets past the loading of this pub key, however, appears to simply not like whatever the minion has sent back, as the pub key is loaded but the verification fails.
```
...
# can't get here without getting through the patched code in the PR
salt-master[2277]: File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 247, in verify_signature
salt-master[2277]: return pubkey.verify(digest, signature)
salt-master[2277]: File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 281, in verify
salt-master[2277]: return m2.rsa_verify(self.rsa, data, signature, digest_type)
salt-master[2277]: RSAError: bad signature
```

Am I on the right track or does that help at all? Where I'm stuck is this would all make more sense to me if every minion wasn't working, but it seems to only be RHEL 7.*. I saw what I thought was a related issue in the salt-pack project some time ago, but I can't find it any longer.

**Comment by dmarkwat** [comment]
These were the issues I was thinking of, but they were apparently for a different (but possibly tangential?) problem: https://github.com/saltstack/salt/issues/49156 and https://github.com/saltstack/salt-pack/issues/580

**Comment by dmurphy18** [comment]
@dmarkwat There were issues with older versions of RHEL 7 (7.2) where it uses an old version of openssl (v1.0.1e), which was causing problems with M2Crypto.  In the upcoming version of Salt 2018.3.3 this is ameliorated by shipping a version of openssl (v1.0.2k) which is compatible with the M2Crypto provided by SaltStack.  Noting that this was the version of openssl provided with Centos 7.2.

It is rare to see differences between Centos 7 and RHEL 7 versions but here openssl was one of them.

With the next release of Salt 2018.3.3, the issues with use of M2Crypto should be resolved on older versions of RHEL 7.

**Comment by dmarkwat** [comment]
@dmurphy18 so that covers older versions with the wrong version of openssl; but what about newer ones, such as 7.5? The 7.5 I'm working with has openssl version, 1.0.2k-fips; so is it safe to assume since it's 1.0.2k that #49156 is unrelated to my current situation?

**Comment by dmarkwat** [comment]
@mattp- after trying a few more things the closest I can get is manual calls to the `sign_message` and `verify_signature` methods to verify they are working--trying to rule out machine- or compiler-related errors. The only way I get an RSAError raised from `verify_signature` is if the message isn't the same one the signature pairs with.
```
import salt.crypt as c
signed = c.sign_message('/etc/salt/pki/minion/minion.pem', 'abc')
c.verify_signature('/etc/salt/pki/minion/minion.pub', 'abc', signed)
# 1

c.verify_signature('/etc/salt/pki/minion/minion.pub', 'ab', signed)       
# Traceback (most recent call last):
#   File "<stdin>", line 1, in <module>
#   File "/usr/lib/python2.7/site-packages/salt/crypt.py", line 247, in verify_signature
#     return pubkey.verify(digest, signature)
#   File "/usr/lib64/python2.7/site-packages/M2Crypto/RSA.py", line 281, in verify
#     return m2.rsa_verify(self.rsa, data, signature, digest_type)
# M2Crypto.RSA.RSAError: bad signature
```

I even signed on a 7.5 minion that isn't working, copied the signature from there to the 2018.3 master machine it communicates with, and verified the signature manually. Like so:
```
# on the minion, 'hostname1'
import salt.crypt as c
signed = c.sign_message('/etc/salt/pki/minion/minion.pem', 'abc')
signed
# byte string...

# on the master
import salt.crypt as c
signed = # copied byte string...
c.verify_signature('/etc/salt/pki/master/minions/hostname1.pub', 'abc', signed)
# 1
```

So manually verifying *a* signature works; but that's all I have. After this, I'm limited in how much further I can go without a more skilled eye looking at whether salt itself has a bug related to particular payloads (e.g. highstate/sls vs not) or interactions specifically with RHEL 7-based systems.

Sorry for the long-winded comments. Hope they're helping at least a little!

**Comment by dmurphy18** [comment]
@dmarkwat @mattp- The version of openssl that ships with RHEL 7.5 is fine, if memory serves correctly, that is the version that Centos 7.2 shipped with, but I do not have a system to quickly check with at the moment.

**Comment by dmarkwat** [comment]
Reverting the salt master to 2017.7 resolves the issue I was seeing. Is there any information saltstack needs regarding this? Should I wait and see if 2018.3.3 fixes the issue and reopen if it doesn't?

**Comment by dmurphy18** [comment]
@dmarkwat Can you confirm if your issues are resolved and consider closing this issue, esp. with the latest point releases Salt 2018.3.4 and 2019.2.0.

**Comment by lukasraska** [comment]
@dmurphy18 I can verify this is still issue, but with slightly different setup. 2017.7.8 master upgraded to 2018.3.4. Linux minions (RHEL 7.5, 7.6) seem to work okay, but Windows 2016 minions with 2017.7.8 version are throwing this on master for certain job outputs (such as grains.items). Other calls to the minion seem to be working (such as `cmd.exec_code_all` to fetch minion logs), but at least `grains.items` is not working.

The windows minion has `minion_sign_messages: True` configured, I will try to test multiple scenarios and determine why this is happening.


Strangely enough, `grains.get osrelease` works just fine on the Windows minion

**Comment by mattp-** [comment]
@lukasraska what set of m2crypto, pycryptodome, pycrypto are you running?
if you have m2crypto, can you try removing it? and if you have pycryptodome can you try removing it?

the order of preference for libraries is: m2crypto, cryptodome, pycrypto, so I'm trying to determining if the problem exists in one of the 3. thanks

**Comment by lukasraska** [comment]
@mattp- 
This is report from the master. I should also mention it's Python 2 in first place.
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Mar 26 2019, 22:13:06)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.6 Maipo
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-957.12.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo
```


It seems both m2crypto and pycrypto are installed, will try with just one of them (if they don't have any hard dependencies) and let you know

**Comment by lukasraska** [comment]
@mattp- So seems like m2crypto is the perpetrator here. In RHEL 7 it's required dependency for RHN (which is obsolete, so no problems) and redhat-support-tool (not used by us, but might be used by others) while python2-crypto is dependency of Salt itself.

After removal of m2crypto package and restart of master, grains.items now suddenly works just fine.

**Comment by mattp-** [comment]
@thatch45 im inclined to suggest pycryptodome as a permanent hard dependency, and remove m2crypto and pycrypto (unmaintained) from salt.crypt and requirements. it reduces complexity and pushes all crypto through one code path. What are your thoughts?

**Comment by dmurphy18** [comment]
@mattp- Perhaps python3-cryptography. would be better given its support in RHEL 8

**Comment by dmurphy18** [comment]
@dmarkwat Can you confirm if your issues are resolved and consider closing this issue, esp. with the latest point releases Salt 2018.3.4 and 2019.2.0.
