### ISSUE TITLE
what's the $arrInstalled mean?

### ISSUE THREAD

**Issue by LyTuan** [saltstack/salt#49892]
Hi guy, 

I'm researching about how to build msi installer for saltstack. In the file build_env_2.ps1 line 264, I don't understand the $arrInstalled mean. I find more information about it and print it's value. However, I didn't see anything. Can yous tell me what's it mean? 

This is code:
```
ForEach($key in $ini[$bitDLLs].Keys) {
    If ($arrInstalled -notcontains $key) {
        Write-Output "   - $key . . ."
        $file = "$($ini[$bitDLLs][$key])"
        $url  = "$($ini['Settings']['SaltRepo'])/$bitFolder/$file"
        $file = "$($ini['Settings']['DownloadDir'])\$bitFolder\$file"
        DownloadFileWithProgress $url $file
        Copy-Item $file  -destination $($ini['Settings']['Python2Dir'])
    }
}
```
Thanks.

**Comment by gtmanfred** [comment]
@twangboy can you help here?

Thanks,
Daniel

**Comment by twangboy** [comment]
It was probably left over from something that was removed. I think undefined vars in Powershell return `None`, so the loop would still run because the key is not in `None`. Anyway, the above PR removes it.
