### ISSUE TITLE
event_publisher_pub_hwm and salt_event_pub_hwm still appear in the docs and sample config

### ISSUE THREAD

**Issue by szjur** [saltstack/salt#49925]
### Description of Issue/Question
As mentioned in https://github.com/saltstack/salt/pull/38723 and https://github.com/saltstack/salt/issues/38674 event_publisher_pub_hwm and salt_event_pub_hwm are dummy settings no longer doing anything. Since Salt master does not fail on dummy config variables the presence of these in the docs (https://docs.saltstack.com/en/latest/ref/configuration/master.html#salt-event-pub-hwm-and-event-publisher-pub-hwm) and the sample config (/etc/salt/master) can easily mislead people (such as myself) into thinking that you can actually make something better by tweaking them.

You guys mentioned some doc regeneration in the PR and issue mentioned above but apparently this has never happened.

### Setup
N/A

### Steps to Reproduce Issue
Navigate to https://docs.saltstack.com/en/latest/ref/configuration/master.html#salt-event-pub-hwm-and-event-publisher-pub-hwm and see the doc not "regenerated" for almost 2 years.

### Versions Report
All recent versions

**Comment by rallytime** [comment]
@szjur Apologies for missing that. I probably just forgot to remove them from the docs when I was searching for those references. I will do that today.

**Comment by rallytime** [comment]
@szjur Alright, I've removed those references from the docs. The docs _have_ been regenerated since that initial PR, but I missed some of the documentation references originally. #49934 removes those references from the docs now.

**Comment by szjur** [comment]
Thanks a lot guys!

**Comment by szjur** [comment]
By the way is expected that these 2 are still present on https://docs.saltstack.com/en/latest/ref/configuration/master.html#salt-event-pub-hwm-and-event-publisher-pub-hwm , right?

**Comment by rallytime** [comment]
@szjur Yeah, that's expected right now. It will take several days to get the changes merged forward and the docs to rebuild after that.
