### ISSUE TITLE
Write a lint rule for logging in __virtual__()

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#49935]
### Description of Issue/Question
We should never be logging inside a `__virtual__()` function. We need to write a lint rule to catch this.

Refs PR #49920

@gtmanfred Can you take a look at this when you get a moment?

**Comment by gtmanfred** [comment]
:+1:

**Comment by mchugh19** [comment]
This is done and can be closed

**Comment by rallytime** [comment]
Thank you @mchugh19!
