### ISSUE TITLE
Problem with telegram listener beacon

### ISSUE THREAD

**Issue by MedourMehdi** [saltstack/salt#49945]
### Description of Issue/Question
If telegram bot have an edited message beacons do not work anymore
Error in minion log:

AttributeError: 'NoneType' object has no attribute 'chat'

I've already open an issue here:
https://github.com/python-telegram-bot/python-telegram-bot/issues/1244

### Setup
beacons:
  telegram_bot_msg:
    - token: "XXXX:XXXXXXXX"
    - accept_from:
      - "XXXXX"
    - interval: 50

### Steps to Reproduce Issue
Edit message with the telegram bot.

### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.12
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-130-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by gtmanfred** [comment]
Thanks for reporting this.  It looks like the solution is included in the bug you opened with the python-telegram-bot project, would you mind opening a PR?

@rafaelcaricio it looks like you wrote this beacon, can you take a look at fixing this?

Thanks,
Daniel

**Comment by rafaelcaricio** [comment]
I can have a look on that. But if @MedourMehdi want's to send a PR right away feel free to do that.
