### ISSUE TITLE
salt.client mess with logging

### ISSUE THREAD

**Issue by bclermont** [saltstack/salt#4994]
tested on 0.14.0

```
import logging
import sys
import salt.client
logger = logging.getLogger()
logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format="Debug: %(message)s")
logger.debug("Test")
```

Nothing show, but if I move `salt.client` import just after the logging is initialized:

```
import logging
import sys

logging.basicConfig(stream=sys.stdout, level=logging.DEBUG, format="Debug: %(message)s")
import salt.client

logger = logging.getLogger()
logger.debug("Test")
```

I get:

```
Debug: Test
```

**Comment by uvsmtid** [comment]
+1
It took me some time to figure this out.
Should it rather be a bug than a feature?
```
#!/usr/bin/env python
import logging
# Without this line `salt.client` somehow prevents all subsequent `logging` output.
logging.debug('initialize logging')
# Salt modules.
import salt.client
# ... other imports
```

**Comment by mcarlton00** [comment]
This is still a bug and still present as far as I can tell.  At the very least this needs to be documented on the [salt client](https://docs.saltstack.com/en/latest/ref/clients/index.html) page if it's not going to be changing, because it's not expected behavior in most non-salt python modules.

Nonworking Example:
```python
import logging
import salt.client

print('before logger')

logging.basicConfig(
    format='%(asctime)s %(levelname)s:%(message)s',
    datefmt='%m/%d/%Y %I:%M:%S %p',
    level=logging.INFO)

logging.info('info')
logging.warning('warning')
logging.error('error')

print('after logger')
```
Output:
```
$ python example.py
before logger
after logger
```

Working Example:
```python
import logging

print('before logger')

logging.basicConfig(
    format='%(asctime)s %(levelname)s:%(message)s',
    datefmt='%m/%d/%Y %I:%M:%S %p',
    level=logging.INFO)

import salt.client

logging.info('info')
logging.warning('warning')
logging.error('error')

print('after logger')
```
Output:
```
$ python example.py
before logger
01/29/2020 09:40:32 AM INFO:info
01/29/2020 09:40:32 AM WARNING:warning
01/29/2020 09:40:32 AM ERROR:error
after logger
```

**Comment by s0undt3ch** [comment]
Care to open a new issue requesting a documentation clarification please?

Salt is not a library, though it can be used as one, and the working example you posted is how you can use it as a library with regards to the expected logging behavior of libraries.

**Comment by network-shark** [comment]
@mcarlton00 Wow super helpful thank you !

**Comment by tacerus** [comment]
It took me a long time to realize my logging issues were related to the `salt.client` import. Thanks a lot for this thread!

One more thing which might be handy for future visitors, setting the log level independently:

```
import logging

myloglevel = logging.DEBUG
saltloglevel = logging.WARNING

logging.basicConfig()

mylog = logging.getLogger('myprogram')
mylog.setLevel(myloglevel)

import salt.config

saltlog = logging.getLogger('salt')
saltlog.setLevel(saltloglevel)

mylog.debug('foo')
```

This allows to use log levels like "DEBUG" for debug output related to ones program without adding possibly irrelevant debug output from Salt.
For a while I attempted to use Salt's built in log initialization functions, such as `set_logger_level()`, however found the native way shown above to be easier.
