### ISSUE TITLE
gem.installed version does not support dependency specifiers like >= or ~>

### ISSUE THREAD

**Issue by icycle77** [saltstack/salt#49954]
### Description of Issue/Question
This issue was originally seen while validating #49866 and I noted that this behavior should be tracked in a separate issue, thus here we are. 

In summary, Ruby gem installs support specifying version dependencies using symbols like `>`, `>=`, `<`, `<=`, and `~>` (this may not be the full list...). However, the salt `gem.installed` state only does direct string compares of the `version` field against the list of versions already installed when determining whether the state needs to run or not. Thus, not only is any version dependency symbology not taken into account, it also will break the string compare and cause the state to always run. Once it runs, however, the underlying `gem` call will properly interpret the dependency symbology.

This issue is therefore a request for salt to support the nuances of acceptable `gem` version dependency symbology in determining whether a `gem.installed` state should run or not.

### Setup
This is the usual case which is supported:
```
json Gem Installed:
  gem.installed:
    - name: json
    - version: '2.1.0'
```
results in:
```
[INFO    ] Running state [json] at time 19:21:40.010850
[INFO    ] Executing state gem.installed for [json]
[INFO    ] Executing command ['gem', 'list', 'json'] in directory '/root'
[DEBUG   ] stdout: json (default: 2.1.0)
[INFO    ] Executing command ['/usr/local/rbenv/bin/rbenv', 'rehash'] in directory '/root'
[DEBUG   ] versions is ['2.1.0'], version is 2.1.0
[INFO    ] Gem is already installed.
```
(Note: fix for #49866 has been manually applied to allow this use case to succeed with the `default: ` prefix in the stdout above)

### Steps to Reproduce Issue
If we modify the working case by adding a `>=` to the `version`:
```
json Gem Installed:
  gem.installed:
    - name: json
    - version: '>= 2.1.0'
```
it will fail the string compare and always (re)install (the proper version of) the gem:
```
[INFO    ] Running state [json] at time 20:03:47.455722
[INFO    ] Executing state gem.installed for [json]
[INFO    ] Executing command ['gem', 'list', 'json'] in directory '/root'
[DEBUG   ] stdout: json (default: 2.1.0, 2.0.4)
[INFO    ] Executing command ['/usr/local/rbenv/bin/rbenv', 'rehash'] in directory '/root'
[DEBUG   ] versions is ['2.1.0', '2.0.4'], version is >= 2.1.0
[INFO    ] Executing command ['gem', 'install', 'json', '--version', '>= 2.1.0', '--no-rdoc', '--no-ri'] in directory '/root'
[DEBUG   ] stdout: Building native extensions. This could take a while...
Successfully installed json-2.1.0
1 gem installed
```

### Versions Report
```
$ salt --versions-report
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: 0.4.2
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core
```

**Comment by Ch3LL** [comment]
looks like we need to handle `>=` versions. will mark as a bug

**Comment by garethgreenaway** [comment]
Closing this out, if the problem persists please comment & we'll re-open the issue or feel free to open a new issue.

**Comment by icycle77** [comment]
Thanks @garethgreenaway -- I actually missed that this issue got a fix merged. We can pick it up and try again, and will reopen this or a new ticket if something remains amiss.
