### ISSUE TITLE
Feature request: salt-run jobs needs more functionality

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#4995]
Could it be possible to extend salt-run jobs to include list jobs by user,function,target.
so the command looks like:

```
- salt-run jobs.list_user username
- salt-run jobs.list_target 'db*' 
- salt-run jobs.list_function state.highstate
```

And as a bonus jobs.list_result, where you can specify True, none, False
and it will print out only jobs with false in it or none with test runs.

This functionality will make salt auditing easier and more fine grained.

**Comment by UtahDave** [comment]
`salt-run jobs.list_jobs` now has options for searching through all this metadata.

https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.jobs.html#salt.runners.jobs.list_jobs
