### ISSUE TITLE
Authentication token is not working after restarting salt-master service

### ISSUE THREAD

**Issue by dpkkumar01** [saltstack/salt#49993]
I have generated the token using the following command,

curl -sSk https://X.X.X.X:9999/login     -H 'Accept: application/x-yaml'     -d username=salt     -d password=salt     -d eauth=pam

return:
- eauth: pam
  expire: 1578657565.681728
  perms:
  - '@wheel'
  - .*
  start: 1539237565.681727
  **token: e8b54c33088e45b44cbc3f798febeb7f59ff3046**
  user: salt

I was using this token across my system for API access.  I have restarted my salt-master application service recently. I am unable to access the API & getting "**401 Unauthorized**".  

I don't want to regenerate the token again. How to use the same token after master service restart??

Please suggest.

**Comment by garethgreenaway** [comment]
@dpkkumar01 Thanks for the report.  The way this is working is by design for security.  The token is stored in memory not stored on disk, so when the Salt master is restarted the token is gone.
