### ISSUE TITLE
Not able to change the config file path in Windows Minion installer builder.

### ISSUE THREAD

**Issue by nithinh123** [saltstack/salt#49996]
###Salt folder getting created in C drive even after changing it

I tried to make a Windows Minion Installer by changing the default Path to my "D" drive. I am able to install the minion using the installer i build. But there is a "salt" folder getting created in "C" drive with the "conf" and "var" folder.

Tried editing all the paths in "Salt-Minion-Setup.nsi" file in the windows installer build folder. But still this "salt" folder is getting created in "C" drive.
[Salt-Minion-Setup.txt](https://github.com/saltstack/salt/files/2468413/Salt-Minion-Setup.txt)

Uploaded the file here with .txt format since .nsi is not supported.

**Comment by garethgreenaway** [comment]
@nithinh123 Can you provide the output from `salt --versions-report`?

@twangboy @dwoz Thoughts?

**Comment by twangboy** [comment]
Is `c:\salt\conf` created before the minion is started or after?

**Comment by twangboy** [comment]
Related: https://github.com/saltstack/salt/issues/42801

**Comment by nithinh123** [comment]
Changing the path in the file D:\Salt_Backup\Salt-Dev\salt\salt\syspath.py will resolve this issue.

ROOT_DIR = __generated_syspaths.ROOT_DIR
if ROOT_DIR is None:
    # The installation time value was not provided, let's define the default
    if __PLATFORM.startswith('win'):
        ROOT_DIR = **r'c:\salt'**   #changing this path and folder will fix this issue
    else:
        ROOT_DIR = '/'

**Comment by nithinh123** [comment]
> 
> 
> Is `c:\salt\conf` created before the minion is started or after?

It is getting created after starting the minion. I fixed the issue.

**Comment by nithinh123** [comment]
> 
> 
> @nithinh123 Can you provide the output from `salt --versions-report`?
> 
> @twangboy @dwoz Thoughts?

I resolved the issue. Thanks.
