### ISSUE TITLE
salt-client  No reason down

### ISSUE THREAD

**Issue by liuwei881** [saltstack/salt#49992]
### Description of Issue/Question
salt-minion no reason down

### Steps to Reproduce Issue
salt-minion auto down

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-696.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final

**Comment by garethgreenaway** [comment]
@liuwei881 Would it be possible to provide a bit more information about the situation that you're seeing?  Unfortunately there isn't much to go on based on the above report.  Are you seeing anything in any of the Salt minion log files?  Are you able to start up the Salt minion manually and see something in the log messages that might help us figure out the issue?  Thanks.
