### ISSUE TITLE
salt-ssh not working for python 2.6 minion

### ISSUE THREAD

**Issue by rbbuckingham** [saltstack/salt#50020]
### Description of Issue/Question
salt-ssh complaining of python version error from python 3.0 salt master to python 2.6 minion.  salt master has python2 dependencies installed.  Minion has python 2.6.9 installed, and installing python 3.0 on it is not an option.

### Setup
Fresh openSUSE Leap15 install with the following installed packages:
  salt
  salt-master
  salt-ssh
  python3-salt
  python2-salt

### Steps to Reproduce Issue
salt:~ # salt-ssh '*' test.ping
hostname-redacted:
    ----------
    retcode:
          10
    stderr:
    stdout:
           ERROR: Python version error.  Recommendation(s) follow:
           - Install Python 2.6/2.7 Salt dependencies on the Salt SSH
             master to interact with Python 2.6/2.7 targets
           - Install Python 3 on the target machine(s)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-lp150.12.19-default
         system: Linux
        version: Not Installed

**Comment by gtmanfred** [comment]
This is because support for python 2.6 was dropped in salt 2017.7

Starting with fluorine you will be able to specify using an old version of salt for salt ssh to py26 minions.

https://github.com/saltstack/salt/pull/46684

**Comment by rbbuckingham** [comment]
Thank you for the quick reply.  I'll read #46684 and explore my options.
