### ISSUE TITLE
Default values in master config file - missing blank lines

### ISSUE THREAD

**Issue by rjc** [saltstack/salt#50025]
This report has been prompted by a [user comment](https://groups.google.com/d/msg/salt-users/wP5r2nStBtI/TMripp5sAgAJ).

The very top of the `/etc/salt/master` config file reads:

    ##### Primary configuration settings #####
    ##########################################
    # This configuration file is used to manage the behavior of the Salt Master.
    # Values that are commented out but have an empty line after the comment are
    # defaults that do not need to be set in the config. If there is no blank line
    # after the comment then the value is presented as an example and is not the
    # default.

However, as mentioned there, some defaults do **not** have an empty line immediately following them, i.e.:

    #file_roots:
    #  base:
    #    - /srv/salt
    #

or:

    #pillar_roots:
    #  base:
    #    - /srv/pillar
    #

The reverse is also true, i.e.:

    #file_ignore_regex:
    #  - '/\.svn($|/)'
    #  - '/\.git($|/)'
    

or:

    #ext_pillar:
    #  - hiera: /etc/hiera.yaml
    #  - cmd_yaml: cat /etc/salt/yaml
    

It is quite confusing as, despite a very clear comment at the beginning of the config file, one cannot be sure whether a particular value is the default or not.

Do you have any means of auto-generating the `master` config file with the defaults correctly followed by a blank line?

If not, please let me know and I'll provide a patch.

**Comment by Ch3LL** [comment]
i dont believe this is auto generated as its directly in the code in conf/master, but @saltstack/team-core might be able to correct me if i'm wrong.

**Comment by gtmanfred** [comment]
Yeah, this is not automatically created, the file is manually made in the source, so it can just be edited.

**Comment by rjc** [comment]
The same information is included in said file, the `salt(7)` manual page, other docs.

Does that mean that **all** of them need to be updated individually?

Is any of them the canonical one from which all of the others are updated?

Better still, is there a way to have only one copy of the information and the remaining documentations "slurps up" the canonical version, i.e. in the style of `#include <file>`, etc.?

**Comment by gtmanfred** [comment]
no, just the conf/<configfile> needs to be updated, the man 7 salt is autogenerated based on  the other files.

**Comment by rjc** [comment]
I believe I covered everything in #50164, when it comes to `conf/master`.

**Comment by rjc** [comment]
The fix has now been now been merged.
