### ISSUE TITLE
file.replace: How to find multiline string at the end of file with complex regex  without making minion crash

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#50040]
I want to search the last block in a file where a string sequence exists. There are several block with this sequence, i just want the last one.
So i created a regex beginning with (.+) and followed by the specific pattern i want at the end of file. 
 As (.+) will be the biggest string possible, i though there was no problem to find the searched string at the end.

sudo salt 'XXX' file.replace 'text_file' flags='[MULTILINE, IGNORECASE, DOTALL]' pattern='^(.+)(^\d{4}-\d{2}-\d{2} \d{2}:\d{2}:\d{2},\d{3} .+ Starting OpenHR server bidule.+)$' repl='' count=1 dry_run=True  search_only=True show_changes=True --out=json

but this never ends, if fact minion crash in an restart in an infinite loop.

And in this regex online interpretor https://regex101.com/r/cG3kG8/1 there is a 'catastrophic backtracking' result.
 
the text_file contains 20812 lines.

As the file.replace function never answer 'False' but either True or nothing, by test is on the 'True' answer.

So, what should be the better way in salt to find the last block in a file containing a string sequence , on windows and on Linux? (no powershell please)

So how to do that?
Salt master: 2017.7.7 on ubuntu
Salt minion: 2017.7.5 on Microsoft Windows Server 2016 Datacenter

**Comment by Ch3LL** [comment]
i tested to see if i could run a `file.replace` on a file that has 20000 lines and it worked. If you run it with `salt-call` on the minion does it still crash? To answer your question about possible alternatives there is the `file.search` module but it looks like it actually calls into the `replace` function anyways so i'm not sure that will help you. There is also `file.sed` but I believe that would only work on linux.

**Comment by Ch3LL** [comment]
also is there any information in the debug logs as to why its crashing?

**Comment by gaetanquentin** [comment]
have you tried my regex? crash is regex dependant.

a regex beginning by (.+) for example, like in my regex, is the main problem, since it generate lot of work.  But how to do it in an other way? Looks like we need a function to search from the end of a file for exemple, it would be less cpu/memory expensive.

**Comment by Ch3LL** [comment]
i did try your regex. Maybe you can share a sanitized snippet of your file that the regex is catching and i can try that.

Also i think thats a sound idea to add an argument to start search at the end of the file. I cant think of a way to currently do that unless @saltstack/team-core has any ideas.
