### ISSUE TITLE
Add MSI Transform file from Salt repo

### ISSUE THREAD

**Issue by Radapompa** [saltstack/salt#50043]
### Description of Issue/Question
Hi,
I've started to setup package installations for Windows servers. So been looking into the winrepo module and tried out some installations here.

The issue I have is when I want to use a transform file to my msi. The msi is loaded from our local salt repo. But I can't get the transform to be loaded aswell from there. It seems to me that the salt path is not usable in installer_flags variable.

Any idea on how to do this? Or would it require a "Msi_Transform" parameter for it to work?

### Setup
my-msi-package:
  {% for version in ['1.0.0.0'] %}
  '{{ version }}':
    full_name: 'MSI Package {{ version }}'
    installer: 'salt://win/packages/msi/MSI-Package-{{ version }}.msi'
    install_flags: 'TRANSFORMS=salt://win/packages/msi/MSI-Package.mst /qn'
    uninstaller: '{F6D187D5-DDF9-4B83-96A0-A411850E626A}'
    uninstall_flags: '/qn'
    refresh: True
    msiexec: True
    use_scheduler: False
    reboot: False
  {% endfor %}

### Steps to Reproduce Issue
[INFO    ] Executing command '"C:\Windows\system32\cmd.exe" /s /c ""msiexec" /I "c:\salt\var\cache\salt\minion\files\dev\win\packages\msi\MSI-Package-1.0.0.0.msi" ALLUSERS=1 TRANSFORMS=salt://win/packages/msi/MSI-Package.mst /qn"' in directory 'c:\salt\var\cache\salt\minion\files\dev\win\packages\msi'
[ERROR   ] Command '"C:\Windows\system32\cmd.exe" /s /c ""msiexec" /I "c:\salt\var\cache\salt\minion\files\dev\win\packages\msi\MSI-Package-1.0.0.0.msi" ALLUSERS=1 TRANSFORMS=salt://win/packages/msi/MSI-Package.mst /qn"' failed with return code: 1624
[ERROR   ] stdout: E r r o r   a p p l y i n g   t r a n s f o r m s .     V e r i f y   t h a t   t h e   s p e c i f i e d  t r a n s f o r m   p a t h s   a r e   v a l i d .
[ERROR   ] retcode: 1624

### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.5
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.5

**Comment by damon-atkins** [comment]
`install_flags: 'TRANSFORMS=salt://win/packages/msi/MSI-Package.mst /qn`
It will not process the salt:// above.
What is the use case for TRANSFORMS?

**Comment by Radapompa** [comment]
Hi,
It won't use it. If you check the debug logs above. You can see that it tries to use the salt:// in the Windows command. As Windows won't know how to handle it, it gives an error.

The TRANSFORMS is pretty much a configuration file for an MSI package. So we're adding different configurations with it when installing the MSI package.

But after reading through the documentation more, I found the cache_file parameter. So now, I'm able to download the .mst file to the minion. I've also successfully used it, but I had to hardcode the cache path. Which can be different depending on the environment. How can I point it to the cached file, without specifying the whole path?

my-msi-package:
{% for version in ['1.0.0.0'] %}
'{{ version }}':
full_name: 'MSI Package {{ version }}'
installer: 'salt://win/packages/msi/MSI-Package-{{ version }}.msi'
cache_file: 'salt://win/packages/msi/MSI-Package.mst'
install_flags: 'TRANSFORMS=C:\salt\var\cache\salt\minion\files\dev\win\packages\msi\MSI-Package.mst /qn'
uninstaller: '{F6D187D5-DDF9-4B83-96A0-A411850E626A}'
uninstall_flags: '/qn'
refresh: True
msiexec: True
use_scheduler: False
reboot: False
{% endfor %}

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any ideas here?

**Comment by twangboy** [comment]
@Radapompa This is a known issue. For now you have to use a batch file to call the msi with the command line switches you want. Basically, have the MSI, the MST, and a Batchfile all in the same directory.  Specify cache_dir = True in the Software definition file and point the installer to the batchfile. You'll also need to set msiexec to False:
```
installer: salt://win/repo-ng/mysoftware/install.cmd
cache_dir: True
msiexec: False
```
The batchfile would be something like this:
```
:: Get the current directory, includes trailing \
Set "CurDir=%~dp0"
msiexec /i "%CurDir%MSI-Package-<hardversion>.msi" TRANSFORMS="%CurDir%MSI-Package.mst" /qn
```
I've never tested this as I don't have software on hand that requires a transform. I may have gotten some of the quoting wrong... but it may work. Let me know.

The uninstaller would be similar, but use `msiexec /s %CurDir%Msi-Package-<hardversion>.msi`

The drawbacks to this workaround are that you can't templatize the batch file. So, if you're dealing with multiple versions of the same software, you'd have to write a batch file for each one. In that case, instead of naming them `install.cmd` and `uninstall.cmd`, you'd name them the version they're installing, ie: `install-2.1.10.cmd` and `uninstall-2.1.10.cmd` or something like that. Each time you get a new version, you'd have to add new batch files with the new version.

I hope this makes sense and that it stears you in the right direction. Let me know what issues you have.

**Comment by damon-atkins** [comment]
In a future 2019 release, this is not a problem, as you can down load as much as you want, and all downloads go to the same location for the same package, and install command runs from that directory.  So you would use TRANSFORM=abc.mst

**Comment by Radapompa** [comment]
@twangboy Thanks for the scripts. The install and uninstall worked well. In this particular case, we can be without the version handling. As the program will be updated from the master server itself. So will only use this to install the program on the servers that is missing it.

@damon-atkins Good to know that this will be fixed in a future release. Then we'll wait for that release and see if we can change the script accordingly.
