### ISSUE TITLE
Backport runtests.py's --from-filenames functionality to 2018.3 branch

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#50050]
Once we have `--from-filenames` working in develop, we need to backport several PRs to 2018.3 so that 2018.3 and fluorine can use this functionality.

- https://github.com/saltstack/salt/pull/47337
- https://github.com/saltstack/salt/pull/49135
- https://github.com/saltstack/salt/pull/49941
- https://github.com/saltstack/salt/pull/50019
- https://github.com/saltstack/salt/pull/50036
- https://github.com/saltstack/salt/pull/50075

**Comment by rallytime** [comment]
OK, so in PR #50182 there were 3 test files back-ported for files that don't exist in 2018.3.

The following test files were removed:
- unit/beacons/test_smartos_imgadm.py
- unit/beacons/test_smartos_vmadm.py
- unit/beacons/test_watchdog.py

All three of the associated beacons exist in `fluorine`, so after #50182 is merged forward to `fluorine`, the test files will need to be added again to the `fluorine` branch.

**Comment by rallytime** [comment]
#50230 needs to be back-ported as well, once it's merged.

**Comment by rallytime** [comment]
OK, I did all of the clean up mentioned in my comments above, so this is nearly done.

Unfortunately, it appears that once I merged in #50182, some branch tests started failing on 2018.3. I will need to investigate that first thing in the morning.

**Comment by rallytime** [comment]
Those test failures should be resolved with #50308

**Comment by rallytime** [comment]
All of the work here should be done now. Closing!
