### ISSUE TITLE
lgpo.set state not finding the policy "Remove access to use all Windows Update features"

### ISSUE THREAD

**Issue by bc-alex** [saltstack/salt#50079]
### Description of Issue/Question
When using the lgpo.set state to try and configure this group policy I get a return of Unable to find Machine Policy Remove access to use all Windows Update features

### Setup
```
store-lgpo:
  lgpo.set:
    - computer_policy:
        Configure Automatic Updates: Disabled
        Remove access to use all Windows update features: Enabled
```

### Steps to Reproduce Issue
Using the above setup in a state and then running a state.apply for the state on a Windows Minions

### Versions Report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 1.10.6
          gitdb: 2.0.4
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.4
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by garethgreenaway** [comment]
@dwoz @twangboy Thoughts?

**Comment by twangboy** [comment]
@bc-alex LGPO is case sensitive. You need to capitalize the `U` in Windows Update...
```
        Remove access to use all Windows Update features: Enabled
```

**Comment by bc-alex** [comment]
I do have the U capitalized

**Comment by bc-alex** [comment]
@twangboy 
`store-lgpo:
  lgpo.set:
    - computer_policy:
        Configure Automatic Updates: Disabled
        Remove access to use all Windows Update features: Enabled`

I have changed the U to be uppercase. And am now getting a slightly different return: 
`       ID: store-lgpo
    Function: lgpo.set
      Result: False
     Comment: Unable to find a policy with the name "Remove access to use all Windows Update features".
`

**Comment by bc-alex** [comment]
@twangboy I solved this. For some reason, for that particular policy I had to define the full path to it:
`Windows Components\Windows Update\Remove access to use all Windows Update features: Enabled`

**Comment by twangboy** [comment]
OK, so it looks like it's not finding the policy with that Name. So I set the value in gpedit and then ran `lgpo.get machine` . This returned something that looked like this:
```
Windows Components\Windows Update\Remove access to use all Windows Update features
```
So, then I did `lgpo.get_policy_info "Windows Components\Windows Update\Remove access to use all Windows Update features" machine` and I got the following:
```
local:
    ----------
    message:
    policy_aliases:
        - Remove access to use all Windows Update features
        - DisableUXWUAccess
        - Windows Components\Windows Update\Remove access to use all Windows Update features
    policy_class:
        machine
    policy_elements:
    policy_found:
        True
    policy_name:
        Windows Components\Windows Update\Remove access to use all Windows Update features
    rights_assignment:
        False
```
So, from what this is returning, you should be able to use anything under `policy_aliases` to set/get policy, but the one we're using isn't working. So, you can try one of the other two. I was able to get policy info using `DisableUXWUAcess` and `Windows Components\Windows Update\Remove access to use all Windows Update features`, so either of those should work to set it.
