### ISSUE TITLE
lowpkg.diff refers to a package name, but a package file is required

### ISSUE THREAD

**Issue by aplanas** [saltstack/salt#50097]
### Description of Issue/Question
`lowpkg.diff` (rpm.py) have a parameter named `package` that refers to a package name (apache2, xz, etc), but internally is using `rpm2cpio` to see the content of the package. The problem is that this command requite a RPM file.

This can be a documentation issue, that affect the examples and all system dependent package managers too.

If is a documentation issue I can fix it, but first I would like to have a confirmation that the expectations are not wrong.

### Versions Report
develop branch

**Comment by Ch3LL** [comment]
ping @isbm looks like you add this here: https://github.com/saltstack/salt/pull/21769

mind answering @aplanas 's concerns

**Comment by isbm** [comment]
@aplanas yeah, the diff would require downloaded file.

**Comment by aplanas** [comment]
Ok, fixing this
