### ISSUE TITLE
Fail function returns stacktrace

### ISSUE THREAD

**Issue by mruepp** [saltstack/salt#50091]
### Description of Issue/Question
Try to use fail function for pkg-upgrade state in orchestrator:

```
upgrade_all_packages:
  salt.function:
    - name: pkg.upgrade
    - tgt: {{ salt['pillar.get']('servers', '') }}
    - saltenv: {{ saltenv }}
    - fail_function: 'upgret.test'
```

Tried both functions, named it upgret.py and it is in _modules. Also exchanged retdata and retval:
First version:
```
import logging

# Set up logging
log = logging.getLogger(__name__)

def test(retval):
    log.info("Return data upgrade: {0}".format(retval))
    return True
```
Second version:
```
def test(retdata):
    return True
```

The following error occurs ALWAYS:

```
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1905, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1830, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/saltmod.py", line 582, in function
    m_func = (not fail_function and True) or __salt__[fail_function](m_ret)
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1143, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python2.7/site-packages/salt/utils/lazy.py", line 104, in __getitem__
    raise KeyError(key)
KeyError: u'upgret.test'
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by gtmanfred** [comment]
It looks like fail_function is run inside the orchestration, so it would run in the context of the master, do you have your module synced to the minion extmods or the master extmods?

Because you will also need to run `salt-run saltutil.sync_modules` if you have not, so that it is in /var/cache/salt/master/extmods/modules, so the master can use them.

**Comment by mruepp** [comment]
Hi, yes for sure, i run saltutil.sync_all before the orchestrator

**Comment by gtmanfred** [comment]
What was the exact command that you used to run it, and can you provide the output of `find /var/cache/salt/master/extmods`

Thanks,
Daniel

**Comment by mruepp** [comment]
sudo salt '*' saltutil.sync_modules
sudo salt '
(_module is in base)

**Comment by gtmanfred** [comment]
right, so as I said, you need to sync the modules to the master extmods cache, using `salt-run saltutil.sync_modules`
