### ISSUE TITLE
NAPALM grains returning the wrong data 

### ISSUE THREAD

**Issue by adambarnett52** [saltstack/salt#50107]
### Description of Issue/Question
When using Napalm and connecting to a switch  the information returned for all devices in all the same and wrong.

### Setup
Using salt 
```
salt1 /etc/salt/proxy.d # salt 'devswitch1' grains.get hostname
devswitch1:
    switch-rb09-2
```
Direct on the switch
```
devswitch1#show hostname
Hostname: devswitch1
FQDN:     devswitch1.dneg.com
```

### Steps to Reproduce Issue
Running the proxy minion in debug i can see that is returning the wrong values 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

```
pip list |grep napalm
napalm (2.3.0)
napalm-base (1.0.0)
```

**Comment by gtmanfred** [comment]
@mirceaulinic can you take a look at this?

Thanks,
Daniel

**Comment by adambarnett52** [comment]
Was there any update on this?

**Comment by adambarnett52** [comment]
Was there any update on this issue

**Comment by sagetherage** [comment]
@adambarnett52 is also an issue on newer Salt releases?

**Comment by sagetherage** [comment]
seems like we have similar issue in the backlog https://github.com/saltstack/salt/issues/54694  assigning a few people to take a look if these are duplicate issues or not

**Comment by twangboy** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
