### ISSUE TITLE
About pillar_cache only work for pillar_roots but not ext_pillar

### ISSUE THREAD

**Issue by rongzeng54** [saltstack/salt#50104]
### Description of Issue/Question
A personal suggestion
Except for different data sources, Pillar_roots and ext_pillar have different frequency of change and real-time data requirements. The latter usually changes more frequently and the real-time requirements are higher.
Pillar_cache has worked fine, we confirming that it can reduce the CPU overhead caused by the pillar request.
Is it possible to control the separate cache of the pillar_roots by adding new configuration items, and ext_pillar will not cache?

**Comment by Ch3LL** [comment]
i dont think this is possible but maybe @saltstack/team-core can correct me if i'm wrong.
