### ISSUE TITLE
Update or remove Salt documentation on salt.readthedocs.io

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#50110]
Outdated Salt documentation published at https://salt.readthedocs.io/en/stable/contents.html still shows up in search engine results.  While the root url (https://salt.readthedocs.io/) redirects to https://docs.saltstack.com/, other pages on the domain do not. 

See https://www.google.com/search?q=site:salt.readthedocs.io for examples.

The documentation on salt.readthedocs.io is over 3 years old and has led me to unwittingly using deprecated features. It should probably be removed entirely, or updated to be in sync with docs.saltstack.com.

**Comment by Ch3LL** [comment]
ping @saltstack/team-core i was not aware of these docs. Does anyone have any knowledge around these and can answer @corywright 's concerns

**Comment by terminalmage** [comment]
@corywright It looks like salt.readthedocs.io has redirected to our own docs for a while. The only "old" docs I found are links to individual release documentation PDFs, and a (probably defunct) community-run chinese language docs project: https://salt-zh.readthedocs.io/en/latest/

Can you show me some of the links you're seeing in search engines?

**Comment by corywright** [comment]
@terminalmage A recent search I made:

- https://www.google.com/search?q=saltstack+from+reactor+call+local+state+sls+file

On the first page of results, the 7th item down for me, is a link to a page on salt.readthedocs.io:

 ***

<img width="636" alt="screen shot 2018-10-18 at 11 26 49 am" src="https://user-images.githubusercontent.com/130219/47165802-ced29700-d2c8-11e8-876d-f76b41bef45a.png">

***

Both Google and DuckDuckGo give results for many pages on salt.readthedocs.io:

- https://www.google.com/search?q=site:salt.readthedocs.io 
- https://duckduckgo.com/?q=site:salt.readthedocs.io

The past few days I've been searching a lot for Salt documentation and many pages on salt.readthedocs.io have been near the top in the search results.

**Comment by terminalmage** [comment]
I got ahold of the person who set up our ReadTheDocs account, and had him delete the project. This should result in the pages from RTD being de-indexed over time.

Thanks for bringing this up, we thought this was resolved awhile back but it clearly wasn't.
