### ISSUE TITLE
cron.set_env appends environment variables instead of prepending, which is a no-op

### ISSUE THREAD

**Issue by JonathanWilbur** [saltstack/salt#50138]
### Description of Issue/Question

The cron.set_env appends environment variables to cron files rather than prepending them. Environment variables that come after cron jobs do not have any effect.

This example will successfully fill a file `/tmp/test.txt` with `bloop`:

```bash
BLAP=bloop
* * * * * echo $BLAP > /tmp/test.txt
```

This one, which is what SaltStack does, does not assign a value to `BLAP` when the cron job is run:

```bash
* * * * * echo $BLAP > /tmp/test.txt
BLAP=bloop
```

### Steps to Reproduce Issue

Set any environment variable on a salt minion using the `cron.set_env` execution module, then create a cron job that uses it or `echo` it to a file to see that it is not set.

#### Salt Master

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

#### Salt Minion

```
    Salt Version:
               Salt: 2018.3.2

    Dependency Versions:
               cffi: 1.11.5
           cherrypy: Not Installed
           dateutil: 1.5
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.28.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, May 31 2018, 09:41:32)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4

    System Versions:
               dist: redhat 7.5 Maipo
             locale: ascii
            machine: x86_64
            release: 3.10.0-862.14.4.el7.x86_64
             system: Linux
            version: Red Hat Enterprise Linux Server 7.5 Maipo
```

**Comment by ManicoW** [comment]
Can't reproduce here, same salt version, but debian dist. The cron modules code seems to take care of env lines before cron lines. Some more informations to reproduce (like states files) ?

**Comment by JonathanWilbur** [comment]
@ManicoW Please refer to [this repository I just made](https://github.com/JonathanWilbur/saltstack-issues-50138) which **proves** that this is an issue on both RPM and Debian distros, and please review and explain why you do not experience this issue on your machine.

@mgomersbach I don't see how your comment is relevant. I am saying that SaltStack appends environment variables to `/etc/crontab` instead of prepending them, which makes them not available to the crontab entries above them.

@gtmanfred Please refer to [this repository I just made](https://github.com/JonathanWilbur/saltstack-issues-50138) which **proves** that this is an issue on both RPM and Debian distros.

**Comment by mgomersbach** [comment]
@jonathanwilbur my wording could have been better. The code there is the relevant code. This does not mean you are not experiencing this bug. Thank you for the extra information.

**Comment by ManicoW** [comment]
@JonathanWilbur I'm sorry but your repository just proves that environment variables after crontab makes them not available, not that salt cron.set_env append them.

My test and the code, as mentioned by @mgomersbach , show that salt takes care of environment variables before any crontab, which result salt prepending the environment variables.

That's why I was asking for some salt state file (or command, but something related to salt).

@mgomersbach If I understand the code, all the environment variables are prepend before all the crontab lines, so there is no way to add an environment variable between two crontab, is there ?

**Comment by gtmanfred** [comment]
@JonathanWilbur can you provide the states that you used that caused the crontab to be setup like this?

Thanks,
Daniel

**Comment by JonathanWilbur** [comment]
@ManicoW and @mgomersbach This is the issue here:

The `cron` module first searches for the `flag` line, which is `# Lines below here are managed by Salt, do not edit`. Anything that comes after that line gets parsed as you would expect:

https://github.com/saltstack/salt/blob/63df92054c96efa3b2b16e1cae6bfdbf16f746d2/salt/modules/cron.py#L330-L334

But anything that comes before this `flag` line is just stuffed into the `pre` key of `list`:

https://github.com/saltstack/salt/blob/63df92054c96efa3b2b16e1cae6bfdbf16f746d2/salt/modules/cron.py#L399-L400

Later on, when `lst` is rendered, the `pre` value gets inserted into the crontab first. It is entirely untracked by SaltStack:

https://github.com/saltstack/salt/blob/63df92054c96efa3b2b16e1cae6bfdbf16f746d2/salt/modules/cron.py#L122-L123

**This means that any existing crontab entries will not have the environment variable applied to them.** Only crontab entries managed by SaltStack will be able to read the environment variables set by SaltStack.

@gtmanfred I can create a file that will do this if you want, but I think the code above is pretty self-explanatory. If you want, this will recreate it:

```bash
echo "* * * * * echo \$BLARP > /tmp/result3.txt" > /var/spool/cron/crontabs/root
salt 'ubuntuhost' cron.set_env root BLARP bloop
```

Then confirm that nothing is written to `/tmp/result3.txt`.

**Comment by mgomersbach** [comment]
Correct and seems like correct behaviour?
As in: do not touch or alter existing entries?

**Comment by JonathanWilbur** [comment]
I would call it _understandable behavior_, but not _correct behavior_. It seems to defeat the point that you can't completely manage the crontab from SaltStack. It certainly defeated the point in my case, where all I needed to do was apply an environment variable to all cron jobs by putting it at the top of the file.

For that matter, if the parsing logic works for everything after the flag, it should work for everything before it. SaltStack's management of this file--including `pre`--might rearrange cron jobs that were already there, but otherwise, it would not break anything (unless the `pre` cron jobs were dependent upon a very particular ordering of environment variables).

At the very least, this unintuitive behavior should be documented, but I think this module should manage the whole file completely, and do so by putting all new environment variables at the very top.

**Comment by mgomersbach** [comment]
Personally I've found the '# Lines below here are managed by Salt, do not edit' self explanatory.
Usually in your described situation a '# Do not touch, this file is managed from salt' is present.
But a more clear documentation would never hurt!
This is for obvious reasons as salt would not be able to tell when something is custom or managed.
