### ISSUE TITLE
XCP-ng packages and services management

### ISSUE THREAD

**Issue by ManicoW** [saltstack/salt#50132]
The XCP-ng distribution is not handled in packages and services management

XCP-ng is a fork of XenServer, so packages and services can be managed as they are managed for XenServer.

Manually setting grains os to XenServer and os_family to RedHat in the minion configuration makes the management working, but it would be better if salt can natively handle this.

Here are the relevant grains in a XCP-ng classic installation : 

```
    os:
        XCP-ng
    os_family:
        XCP-ng
    osarch:
        x86_64
    oscodename:
        XCP-ng 7.5.0
    osfinger:
        XCP-ng-7
    osfullname:
        XCP-ng
    osmajorrelease:
        7
    osrelease:
        7.5.0
    osrelease_info:
        - 7
        - 5
        - 0
```
There is no /etc/lsb-release

**Comment by gtmanfred** [comment]
Thanks for the PR for this.

Daniel
