### ISSUE TITLE
salt-ssh can not get pillar "glibc:version"

### ISSUE THREAD

**Issue by autumnw** [saltstack/salt#50149]
### Description of Issue/Question
When I use "salt-ssh my_host pillar.get glibc:version", it always returns "None", I tried both on entos6 and 7. However, with "salt my_host pillar.get glibc:version", it always return the right value.

### Setup
salt-master and salt-ssh version is: 2018.3.2-1.el7.noarch
salt master OS version is centos 7

### Steps to Reproduce Issue
on salt master, run "salt-ssh my_host pillar.get glibc:version", will get None

### Versions Report
[root@sv3-salt1 ca-ec2]# salt --versions-report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by gtmanfred** [comment]
I am going to need more information on your setup so that I can replicate this issue.

@mgomersbach pillar.items should not be needed because the way salt-ssh works, it runs salt-call --local on the salt-ssh minion, so it will start up a whole minion process and get the pillar data.
