### ISSUE TITLE
artifactory.downloaded state is not respecting test=True

### ISSUE THREAD

**Issue by mikemartino** [saltstack/salt#50155]
### Description of Issue/Question
I'm using the `artifactory.downloaded` state to download an artifact from a Nexus repository to one of my managed hosts. It works well with the exception that the state seems to ignore the `test=True` flag during a `state.apply`:

```
salt 'my-host' state.apply relevant.state.here saltenv=feature/my_branch_for_nexus_dep test=True
```

And the file gets downloaded to the host. I'm not sure how the `test` flag fits into the SaltStack architecture, but I read on another ticket that it's left to the state to decide what to do with it? I don't think it's something that I'm doing wrong, but I'd be willing to adjust my configuration accordingly if it is. 

Note: The `test=True` is respected for the other states in the SLS file (`file.managed`, `archive.extracted`, etc).

### Steps to Reproduce Issue
Noted in the description. Run an `artifactory.downloaded` state with `test=True` and the file is downloaded to the host (i.e. not tested, but applied).

### Versions Report
Salt version is the same on master and minion (2017.7.2).

**Comment by mikemartino** [comment]
After a few hours fighting with my configuration, I realize that the `test` flag is used in more places than I previously knew. For instance, it's used by [`prereq`](https://docs.saltstack.com/en/latest/ref/states/requisites.html#prereq) which has been the cause of much confusion for me this 

I'm trying to download a more recent version of a JAR using the `artifactory.downloaded`. To avoid deploying multiple versions of the same library to a folder, I've been running with a `prereq` that runs a command to delete all of the similarly named JAR files. I can't quite word the order in which things are happening, but I do know that the JAR file is being downloaded during the `prereq` test step which is making state application super confusing haha.

**Comment by garethgreenaway** [comment]
Closing this out, if the problem persists please comment & we'll re-open the issue or feel free to open a new issue.

**Comment by mikemartino** [comment]
Awesome, thank you very much!
