### ISSUE TITLE
Amazon ECR Credential Helper not working with Salt 

### ISSUE THREAD

**Issue by kenanbiel** [saltstack/salt#50166]
### Description of Issue/Question
I'm using Amazon's ECR service as my private container registry.

Unfortunately, whenever I want to pull images from that registry, i need to re-authenticate and the token changes every 12 hours. Amazon has gladly provided a workaround (https://aws.amazon.com/blogs/compute/authenticating-amazon-ecr-repositories-for-docker-cli-with-credential-helper/) for CI/CD purposes.

I honestly don't know how the it works in the backend but basically, i just do a
`docker pull XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/mycontainer:latest` 
and it will pull the image without authentication.

Someone reported a similar thing https://github.com/saltstack/salt/issues/48066 but that user didn't provide much details about his setup and i don't experience the problem he did.

I turned on debug mode and it's looking for a docker authentication based on this (https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockermod.html#docker-authentication) but with the binary file provided by Amazon, it's not anymore needed.

```
[INFO    ] Executing state docker_image.present for [XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/mycontainer]
[DEBUG   ] Attempting to run docker-py's "images" function with args=() and kwargs={'all': False}
[DEBUG   ] Attempting to run docker-py's "images" function with args=() and kwargs={'all': True}
[DEBUG   ] Trying paths: ['/root/.docker/config.json', '/root/.dockercfg']
[DEBUG   ] Found file at path: /root/.docker/config.json
[DEBUG   ] Found 'credsStore' section
[DEBUG   ] Attempting to run docker-py's "pull" function with args=('XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/mycontainer',) and kwargs={'tag': 'latest', 'stream': True}
[DEBUG   ] Looking for auth config
[DEBUG   ] Using credentials store "ecr-login"
[DEBUG   ] Looking for auth entry for 'XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com'
[DEBUG   ] No entry found
[DEBUG   ] No entry in credstore - fetching from auth dict
[DEBUG   ] Looking for auth entry for 'XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com'
[DEBUG   ] No entry found
[DEBUG   ] No auth config found
[ERROR   ] Encountered error pulling XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/mycontainer:latest: Unable to perform pull: 500 Server Error: Internal Server Error for url: http+docker://localhost/v1.38/images/create?tag=latest&fromImage=XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com%2Fmycontainer
```

### Setup

config.sls
```
mycontainer:
  docker_image.present:
    - name: XXXXXXXXXXX.dkr.ecr.us-east-1.amazonaws.com/mycontainer
    - tag: latest
```

/root/.docker/config.json
```
{
    "credsStore": "ecr-login"
}
```

### Steps to Reproduce Issue

1. Install the amazon-ecr-credential-helper binary.
2. Use my above template for /root/.docker/config.json and configure /root/.aws/credentials or correct IAM permission.
3. See that images can be pulled from that repository without any authentication required.
4. Write a simple salt state using docker_image.running with an image from Amazon's ECR service.

### Versions Report
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1060-aws
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by garethgreenaway** [comment]
@terminalmage Any insight on this one?

**Comment by bogdanr** [comment]
I would also like to know if there is some workaround for it.

**Comment by bogdanr** [comment]
Works for me.
My formula for putting the helper on machines looks like this:
```
/usr/local/bin/docker-credential-ecr-login:
  file.managed:
    - source: salt://docker/ecr-helper/docker-credential-ecr-login
    - mode: 755

/root/.docker/config.json:
  file.managed:
    - source: salt://docker/ecr-helper/config.json
    - mode: 400
```

**Comment by terminalmage** [comment]
If this is even a bug, it would be upstream with docker-py.

docker-py will use the config.json whenever authentication is required. Based on @bogdanr's comment, it seems that it does indeed work, so maybe your config.json is incorrectly formatted. @bogdanr, since you've gotten this to work, can you share the structure of your config.json, with all sensitive information redacted? This may help @kenanbiel.

**Comment by cheald** [comment]
I can't seem to get this to work. It's fine via salt-call, but broken when trying to invoke from the salt master.

```
# cat ~/.docker/config.json
{
    "credsStore": "ecr-login",
    "credHelpers": {
          "xxxxxx.dkr.ecr.us-west-1.amazonaws.com": "ecr-login"
    }
}
```

```
# which docker-credential-ecr-login
/usr/bin/docker-credential-ecr-login
```

Works fine from a shell:

```
# docker pull xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0
v0.3.0: Pulling from dnsapi
Digest: sha256:22a891d95be79cd6441ce1e4032004c19dd055b68bc8d52a73b07bc875f9c27f
Status: Image is up to date for xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0
xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0
```

Works fine via salt-call:

```root@salt-master:~# salt-call cmd.run "docker pull xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0"
local:
    v0.3.0: Pulling from dnsapi
    Digest: sha256:22a891d95be79cd6441ce1e4032004c19dd055b68bc8d52a73b07bc875f9c27f
    Status: Image is up to date for xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0
    xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0
```

```
# salt-call docker.pull xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0
local:
    ----------
    Status:
        Image is up to date for xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0
    Time_Elapsed:
        0.9563000202178955
    retcode:
        0
```

Fails via salt:

```
root@salt-master:~# salt salt-master cmd.run "docker pull xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0"
salt-master:
    Error response from daemon: Get https://xxxxxxx.dkr.ecr.us-west-1.amazonaws.com/v2/dnsapi/manifests/v0.3.0: no basic auth credentials
```

```
# salt salt-master docker.pull xxxxxxxx.dkr.ecr.us-west-1.amazonaws.com/dnsapi:v0.3.0
salt-master:
    ERROR: Error 500: Get https://xxxxxxxx.dkr.ecr.us-west-1.amazonaws.com/v2/dnsapi/manifests/v0.3.0: no basic auth credentials
```

**Comment by 11qeq11** [comment]
Not sure if this is a 100% correct solution, but I overcome it by temporary setting correct HOME variable for Salt process in states.
```yaml
HOME:
   environ.setenv:
     - value: /root
     - require_in:
       - <state_with_your_docker_container.running>
```
Making your Docker state require this state will ensure that the needed variable is in place, and it's there only when it's needed, so we won't play around too much and set any variables permanently unnecessary.
