### ISSUE TITLE
Jid conflicts

### ISSUE THREAD

**Issue by whistle-china** [saltstack/salt#50165]
### Description of Issue/Question
Use the python module threading to call the salt api asynchronously
1. {'client': 'local_async', 'tgt': tgt, 'fun': 'cmd.run_all', 'arg': arg, 'expr_form': 'list'}
2. {'client': 'runner', 'fun': 'jobs.exit_success',  'jid': jid }
3. {'client': 'runner', 'fun': 'jobs.lookup_jid',  'jid': jid }

2018-10-18 21:20:44,233 [salt.utils.event                                    ][DEBUG  ][11111] Sending event: tag = salt/run/20181018212043355237/new; data = {'fun': 'runner.jobs.lookup_jid', 'fun_args': [{'jid': '20181018212034469862'}], 'jid': '20181018212043355237', 'user': 'salt-api', '_stamp': '2018-10-18T13:20:44.233261'}

2018-10-18 21:20:44,299 [9 [salt.utils.event                                        ][DEBUG  ][11110] Sending event: tag = salt/run/20181018212043355237/new; data = {'fun': 'runner.jobs.exit_success', 'fun_args': [{'jid': '20181018212036486834'}], 'jid': '20181018212043355237', 'user': 'salt-api', '_stamp': '2018-10-18T13:20:44.298706'}

The same jid 20181018212043355237 appears ?

How to avoid the same jid?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
Unrepeatable at this time

### Versions Report
[root@salt-master ~]# salt --versions-report
Salt Version:
           Salt: 2016.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.6.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 17 2014, 18:11:42)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.1.1503 Core
        machine: x86_64
        release: 3.10.0-229.el7.x86_64
         system: Linux
        version: CentOS Linux 7.1.1503 Core
 
[root@salt-master ~]#

**Comment by garethgreenaway** [comment]
@whistle-china Thanks for the report.  Are you making the above calls to the runner functions simultaneously?  Based on the time stamps they appear very close.
@saltstack/team-core Thoughts?

**Comment by whistle-china** [comment]
@garethgreenaway Multiple threads are used with module threading, and each thread calls the runner functions separately. The number of threads at the time of the problem cannot be determined for a while, but dozens of threads are available.

I think creating jid with {0:%Y%m%d%H%M%S%f}'.format(datetime.datetime.now()) is very accurate, but it still causes jid to repeat

I found a post https://github.com/saltstack/salt/commit/3c58717c5881ec4ecc50f0c699f8ddd355c35569#diff-b461b34aa42bcedb767bd9c98ef43056, but this version is too high, because I have a lot of minion where the operating system is very low, there is no way to upgrade the operating system, Unable to take the upgrade 2018.2 this strategy

I want to modify the source code in the existing version to solve this problem, can you help me with some suggestions?
