### ISSUE TITLE
Job ID changes in event data between salt-call start and job return

### ISSUE THREAD

**Issue by Tanoti** [saltstack/salt#50193]
### Description of Issue/Question
The Job ID appears to change between the start of a salt-call state run on a minion and the return data for that job. For instance, with "state_events: True" a simple one-step state will return these tags:

Job Progress
--------------
Sending event: tag = salt/job/**20181024085257863424**/prog/saltdev/0; data = {'jid': '20181024085257863424', 'cmd': '_minion_event', '_stamp': '2018-10-24T08:52:58.296653', 'tag': 'salt/job/20181024085257863424/prog/saltdev/0', 'data': {'ret': {'comment': 'Path /tmp/salt_test exists', 'pchanges': {}, 'name': '/tmp/salt_test', 'start_time': '08:52:58.198263', 'result': True, 'duration': 0.848, '__run_num__': 0, '__func__': 'file.exists', '__sls__': 'tests.test_simple', 'changes': {}, '__id__': 'test_simple'}, 'len': 1}, 'id': 'saltdev'}

Job Return
------------
Sending event: tag = salt/job/**20181024085258308094**/ret/saltdev; data = {'tgt_type': 'glob', 'fun_args': ['tests.test_simple', 'test=False'], 'jid': '20181024085258308094', 'return': {'file_|-test_simple_|-/tmp/salt_test_|-exists': {'comment': 'Path /tmp/salt_test exists', 'pchanges': {}, 'name': '/tmp/salt_test', 'start_time': '08:52:58.198263', 'result': True, 'duration': 0.848, '__run_num__': 0, '__func__': 'file.exists', '__sls__': 'tests.test_simple', 'changes': {}, '__id__': 'test_simple'}}, 'retcode': 0, 'tgt': 'saltdev', 'cmd': '_return', '_stamp': '2018-10-24T08:52:58.309873', 'arg': ['tests.test_simple', 'test=False'], 'fun': 'state.apply', 'id': 'saltdev', 'out': 'highstate'}

As you can see the salt-call Job ID is 20181024085257863424 while the return for the same job is 20181024085258308094. This makes it impossible to correlate the event data for a running job with that of a completed one when using the event bus for a real-time job analysis system.

### Setup
No special setup required.

### Steps to Reproduce Issue
Enable "state_events: True" on the salt master and enable debug logging.
Run a state and observe the event tag returns.

### Versions Report
Salt Version:
           Salt: 2017.7.7

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.18.44-20.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by dwoz** [comment]
@Tanoti Thank you for reporting this.
