### ISSUE TITLE
_load_library in rsax931.py on openwrt systems

### ISSUE THREAD

**Issue by kangelos** [saltstack/salt#50191]
### Description of Issue/Question
find_library does not work on systems like openwrt where utils like ldd ldconfig etc behave differently

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
just plain python3.7 setup.py install
[rsax.error.txt](https://github.com/saltstack/salt/files/2509498/rsax.error.txt)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt-minion -l debug

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
I am using the development version with python3.7

### fixup patch
really simple
[rsax.patch.txt](https://github.com/saltstack/salt/files/2509502/rsax.patch.txt)

**Comment by Ch3LL** [comment]
seems you have a clear grasp here, mind submitting a PR?
