### ISSUE TITLE
Redodata is missed on yum/redhat/6/i386/latest/

### ISSUE THREAD

**Issue by rpisarev** [saltstack/salt#50213]
Redodata is missed on 
https://repo.saltstack.com/yum/redhat/6/i386/latest/

On the other hand we have https://repo.saltstack.com/yum/redhat/6/x86_64/latest/repodata/

Please recreate repodata for redhat/6/i386

**Comment by Ch3LL** [comment]
ping @dmurphy18

**Comment by dmurphy18** [comment]
@rpisarev The RHEL 6 32-bit repository is now available for Salt 2018.3.3, sorry about that oversight, it is one of the few left which is built by hand and a step was missed in making the 32-bit repository.

Please let us know if there are any issues with its use, and if not, can you close this issue once you are satisfied.

**Comment by rpisarev** [comment]
@dmurphy18 Thank you! I'll close it then
