### ISSUE TITLE
salt-master debian package upgrade to 2018.3.3+ds-1 fails 

### ISSUE THREAD

**Issue by dudleyperkins** [saltstack/salt#50217]
### Description of Issue/Question

I just tried to upgrade the salt-master package, but the restart of the service during that upgrade fails. That leaves the salt-master package as unconfigured for dpkg and unusable on the system.

Error messages ( from /var/log/salt/master) during the restart are:

2018-10-25 06:28:32,267 [salt.log.setup   :1165][ERROR   ][6901] An un-handled exception was caught by salt's global exception handler:
ImportError: No module named concurrent
Traceback (most recent call last):
  File "/usr/bin/salt-master", line 22, in <module>
    salt_master()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 97, in salt_master
    master.start()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 211, in start
    super(Master, self).start()
  File "/usr/lib/python2.7/dist-packages/salt/utils/parsers.py", line 1044, in start
    self.prepare()
  File "/usr/lib/python2.7/dist-packages/salt/cli/daemons.py", line 191, in prepare
    import salt.master
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 35, in <module>
    import salt.client.ssh.client
  File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 47, in <module>
    import salt.utils.thin
  File "/usr/lib/python2.7/dist-packages/salt/utils/thin.py", line 16, in <module>
    import concurrent
ImportError: No module named concurrent

### Setup

This ist just a regular, up-to-date, Debian Stretch. Upgrade for the Salt Packages were available for:
salt-cloud, salt-minion, salt-master, salt-common and salt-api
where version "2018.3.2+ds-1" would've been upgraded to "2018.3.3+ds-1".

### Steps to Reproduce Issue

1. Install salt-master version 2018.3.2+ds-1 from repo https://repo.saltstack.com/apt/debian/9/amd64/latest stretch main
2. Upgrade theat Package to 2018.3.3+ds-1 from the same repository with the help of apt

### Versions Report

Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.5
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.5

**Comment by promulo** [comment]
We had the same problem after an unattended upgrade on Ubuntu installed `2018.3.3+ds-1` (we were already on 2018.3.3). 

In our case, installing the `python-concurrent.futures` package mitigated the issue.

**Comment by dudleyperkins** [comment]
Thank you that did the trick.

I leave this issue open for now, cause i think this should be added as a dependency for the package. If a Developer states otherwise this might as well be closed.

**Comment by gtmanfred** [comment]
This is being tracked over here.

https://github.com/saltstack/salt-pack/issues/593
