### ISSUE TITLE
after uprgrade to  2018.3.3+ds-1 salt-minon,salt-master fails to start

### ISSUE THREAD

**Issue by pasanmdev** [saltstack/salt#50242]
### Description of Issue/Question
I have upgrade the salt-master/salt-minon nodes on my network to latest pkg 2018.3.3+ds-1 via saltstack deb repo ( http://repo.saltstack.com/apt/debian/9/amd64/latest stretch/main amd64) and it appears to missing a python dependency and causes minion and master process start up fail with below message.

Oct 26 18:23:15 tigernut salt-master[11768]:     import salt.client.ssh.client
Oct 26 18:23:15 tigernut salt-master[11768]:   File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 47, in <module>
Oct 26 18:23:15  salt-master[11768]:     import salt.utils.thin
Oct 26 18:23:15  salt-master[11768]:   File "/usr/lib/python2.7/dist-packages/salt/utils/thin.py", line 16, in <module>
Oct 26 18:23:15  salt-master[11768]:     import concurrent
Oct 26 18:23:15  salt-master[11768]: ImportError: No module named concurrent
Oct 26 18:23:16  systemd[1]: salt-master.service: Main process exited, code=exited, status=1/FAILURE
Oct 26 18:23:16  systemd[1]: Failed to start The Salt Master Server.
Oct 26 18:23:16  systemd[1]: salt-master.service: Unit entered failed state.
Oct 26 18:23:16  systemd[1]: salt-master.service: Failed with result 'exit-code'.

### Setup
not relevant as issue related to package installation
 
### Steps to Reproduce Issue
not relevant

### Versions Report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.5 
         locale: UTF-8
        machine: x86_64
        release: 4.9.103-local.20180529-145754
         system: Linux
        version: debian 9.5 
 

I was able to start master/minion after installing following python pkg.

apt-get install python-concurrent.futures

**Comment by dmurphy18** [comment]
@pasanmdev This is being handled saltstack/salt-pack#593

But basically stretch supplies python-tornado (not SaltStack) which has a recommends on concurrent-futures, not a depends. Salt is using the python-tornado that is supplied with the OS.

However shall look into steps to help with the issue.

**Comment by dmurphy18** [comment]
Closing this since being address as detailed above
