### ISSUE TITLE
salt can't connect to the master.

### ISSUE THREAD

**Issue by markododa** [saltstack/salt#50245]
On a new install of saltstack 2018.3 (from the apt repo) on debian 9, i can't run commands to the master, only salt-call works.
Even salt minion_id test.ping hangs
The error i get in stderror is

`
^CException SystemExit: SystemExit(u'\nExiting gracefully on Ctrl-c',) in <bound method AsyncReqMessageClient.__del__ of <salt.transport.zeromq.AsyncReqMessageClient object at 0x7f8e9c11bdd0>> ignored
Exception AttributeError: "'AsyncReqMessageClientPool' object has no attribute 'message_clients'" in <bound method AsyncReqMessageClientPool.__del__ of <salt.transport.zeromq.AsyncReqMessageClientPool object at 0x7f8e9c11be10>> ignored
argument must be an int, or have a fileno() method.
`

In the master log i see

`2018-10-26 12:36:56,784 [salt.utils.process:754 ][ERROR   ][3493] An un-handled exception from the multiprocessing process 'MWorker-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 1092, in run
    self.__bind()
  File "/usr/lib/python2.7/dist-packages/salt/master.py", line 990, in __bind
    req_channel.post_fork(self._handle_payload, io_loop=self.io_loop)  # TODO: cleaner? Maybe lazily?
  File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 630, in post_fork
    self.stream = zmq.eventloop.zmqstream.ZMQStream(self._socket, io_loop=self.io_loop)
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 114, in __init__
    self._init_io_state()
  File "/usr/lib/python2.7/dist-packages/zmq/eventloop/zmqstream.py", line 535, in _init_io_state
    self.io_loop.add_handler(self.socket, self._handle_events, self._state)
  File "/usr/local/lib/python2.7/dist-packages/tornado/ioloop.py", line 910, in add_handler
    self._impl.register(fd, events | self.ERROR)
TypeError: argument must be an int, or have a fileno() method.
`
repeated again and again

**Comment by Ch3LL** [comment]
can you see if installing `python-concurrent.futures` helps?

**Comment by markododa** [comment]
It seems that installing the newest tornado via pip causes the problem, keeping the system's tornado fixes the issue

**Comment by Ch3LL** [comment]
are you running python3 or python2? tornado 5.0 should work with python2 but we are still working on making it compatible with python3

**Comment by dwoz** [comment]
This will happen if `pyzmq<17.0.0` and the `salt.utils.zeromq.install_zmq` method is not called before creating an event loop.
