### ISSUE TITLE
pgjsonb returner is not multi-syndic safe / duplicate jids

### ISSUE THREAD

**Issue by roskens** [saltstack/salt#50249]
### Description of Issue/Question
Using pgjsonb in a master-of-masters (1 master-of-masters, X syndics, Y minions), leads to large numbers of duplicate key errors on the jids table when running large numbers of concurrent jobs.

This comment from the multi_returner returner sums this problem up:
> TODO: finish this, what do do when you get different jids from 2 returners... since our jids are time based, this make this problem hard, because they aren't unique, meaning that we have to make sure that no one else got the jid and if they did we spin to get a new one, which means "locking" the jid in 2 returners is non-trivial

Possibly a duplicate of https://github.com/saltstack/salt/issues/50165 ?

### Setup
1 master-of-masters running master/minion process. its master is itself.
3 syndics running master/syndic/minion processes. the syndics master is the master-of-masters.
X minions. each minion is configured to use all 3 of the syndics in a failover fashion. 

### Steps to Reproduce Issue
Run job from master-of-master that targets a large number of minions attached to the syndic masters.

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.26.3
        libnacl: 1.6.1
       M2Crypto: 0.28.2
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.6.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

**Comment by roskens** [comment]
I was comparing pgjsonb.save_load() with local_cache.save_load(). local_cache's version will *overwrite* the existing JID file each time it is called for the same JID!

**Comment by Ch3LL** [comment]
i'm having a  hard time making a difference between this issue and https://github.com/saltstack/salt/issues/50238

Can you clarify and answer my questions in the other issue? Or this one if you want to keep this issue open

**Comment by roskens** [comment]
This is being logged in the local postgresql database logs:
```
< 2018-10-26 15:56:30.476 CDT >< syndic1(39926) >< 5bd37f7e.5c30 > ERROR:  duplicate key value violates unique constraint "jids_pkey"
< 2018-10-26 15:56:30.476 CDT >< syndic1(39926) >< 5bd37f7e.5c30 > DETAIL:  Key (jid)=(20181026155630440249) already exists.
< 2018-10-26 15:56:30.476 CDT >< syndic1(39926) >< 5bd37f7e.5c30 > STATEMENT:  INSERT INTO jids
                       (jid, load)
                        VALUES ('20181026155630440249', '{"tgt_type": "list", "jid": "20181026155630440249", "cmd": "publish", "tgt": ["minion1", "minion2", "minion3", "minion4", "minion5"], "kwargs": {"user": "root"}, "ret": "", "user": "root", "arg": ["20181026155616530559"], "fun": "saltutil.find_job"}')
```

This has nothing to do with the `KeyError: u'ret'` exception as far as I can tell. This is probably closer to #50165, but specific to pgjsonb.

**Comment by roskens** [comment]
Following up on my comment earlier about local_cache.py:

I modified this section from save_load() in salt/returners/local_cache.py to save each load to a unique file:
```
    try:
        load_p = str(LOAD_P)
        if os.path.exists(os.path.join(jid_dir, load_p)):
            log.debug('save_load: file {0} exists!'.format(os.path.join(jid_dir, LOAD_P)))
            n = 0
            load_p = '{0}.{1}'.format(LOAD_P, n)
            while os.path.exists(os.path.join(jid_dir, load_p)):
                n = n + 1
                load_p = '{0}.{1}'.format(LOAD_P, n)
        with salt.utils.files.fopen(os.path.join(jid_dir, load_p), 'w+b') as wfh:
            serial.dump(clear_load, wfh)
```

Then ran a job that targeted 9 minions (these also happen to be syndics), and this was what I found in the local job cache on the master:
```
# ls -laR --full-time
.:
total 88
drwxr-xr-x. 11 root root 4096 2018-10-26 16:32:00.031634308 -0500 .
drwxr-xr-x.  3 root root   75 2018-10-26 16:31:59.611633455 -0500 ..
-rw-r--r--.  1 root root   20 2018-10-26 16:31:59.705633646 -0500 jid
-rw-r--r--.  1 root root  518 2018-10-26 16:31:59.613633459 -0500 .load.p
-rw-r--r--.  1 root root  161 2018-10-26 16:31:59.660633555 -0500 .load.p.0
-rw-r--r--.  1 root root  163 2018-10-26 16:31:59.666633567 -0500 .load.p.1
-rw-r--r--.  1 root root  161 2018-10-26 16:31:59.672633579 -0500 .load.p.2
-rw-r--r--.  1 root root  161 2018-10-26 16:31:59.680633595 -0500 .load.p.3
-rw-r--r--.  1 root root  163 2018-10-26 16:31:59.684633603 -0500 .load.p.4
-rw-r--r--.  1 root root  162 2018-10-26 16:31:59.688633612 -0500 .load.p.5
-rw-r--r--.  1 root root  162 2018-10-26 16:31:59.694633624 -0500 .load.p.6
-rw-r--r--.  1 root root  162 2018-10-26 16:31:59.698633632 -0500 .load.p.7
-rw-r--r--.  1 root root  163 2018-10-26 16:31:59.708633652 -0500 .load.p.8
-rw-r--r--.  1 root root   38 2018-10-26 16:31:59.649633532 -0500 .minions.minion-pre-1.p
-rw-r--r--.  1 root root   38 2018-10-26 16:31:59.713633662 -0500 .minions.minion-pre-2.p
-rw-r--r--.  1 root root   38 2018-10-26 16:31:59.720633677 -0500 .minions.minion-pre-3.p
-rw-r--r--.  1 root root   39 2018-10-26 16:32:00.031634308 -0500 .minions.minion-prod-1.p
-rw-r--r--.  1 root root   39 2018-10-26 16:31:59.931634105 -0500 .minions.minion-prod-2.p
-rw-r--r--.  1 root root   39 2018-10-26 16:31:59.917634077 -0500 .minions.minion-prod-3.p
-rw-r--r--.  1 root root   73 2018-10-26 16:32:00.014634274 -0500 .minions.minion-qa-1.p
-rw-r--r--.  1 root root  109 2018-10-26 16:31:59.703633642 -0500 .minions.minion-qa-2.p
-rw-r--r--.  1 root root   73 2018-10-26 16:31:59.849633938 -0500 .minions.minion-qa-3.p
-rw-r--r--.  1 root root  334 2018-10-26 16:31:59.613633459 -0500 .minions.p
drwxr-xr-x.  2 root root   21 2018-10-26 16:31:59.698633632 -0500 minion-pre-1
drwxr-xr-x.  2 root root   21 2018-10-26 16:31:59.694633624 -0500 minion-pre-2
drwxr-xr-x.  2 root root   21 2018-10-26 16:31:59.689633614 -0500 minion-pre-3
drwxr-xr-x.  2 root root   21 2018-10-26 16:31:59.673633581 -0500 minion-prod-1
drwxr-xr-x.  2 root root   21 2018-10-26 16:31:59.708633652 -0500 minion-prod-2
drwxr-xr-x.  2 root root   21 2018-10-26 16:31:59.685633605 -0500 minion-prod-3
drwxr-xr-x.  2 root root   21 2018-10-26 16:31:59.677633589 -0500 minion-qa-1
drwxr-xr-x.  2 root root   21 2018-10-26 16:31:59.665633565 -0500 minion-qa-2
drwxr-xr-x.  2 root root   21 2018-10-26 16:31:59.681633597 -0500 minion-qa-3
```

So this would confirm my suspicion that save_load is overwriting the LOAD_P file, while other returners are enforcing a strict requirement that JID be unique for every entry.

**Comment by Ch3LL** [comment]
ping @saltstack/team-core are any of you aware of this being an issue with returners and how we properly handle these cases?

**Comment by roskens** [comment]
Any updates on this? Had an interesting case where my salt master-of-masters filled up disk today, and the postgresql logs were multiple gigabytes due to constraint errors.

A secondary issue we think caused the issue: bash auto-completion can cause the master-of-masters to issue a null command, which leads to all minions returning the list of execution modules available.

**Comment by roskens** [comment]
@Ch3LL i haven't been able to discover anything more about the null command.

Running `alter database salt set log_min_error_statement = fatal;` when connected as an adminstrator in the database causes the statements causing an error to no longer be logged. You still get the error and details for why there was an error.
