### ISSUE TITLE
mine.get broken in Python 3

### ISSUE THREAD

**Issue by ezh** [saltstack/salt#50255]
### Description of Issue/Question
ctx['salt']['saltutil.runner']('mine.get', tgt='*', fun='network.ip_addrs')
"\nPassed invalid arguments: unhashable type: 'list'\n\nUsage:\n\n    Gathers the data from the specified minions' mine, pass in...

salt/utils/minions:1176

fun 'test.ping'
data.get(functions)
TypeError: TypeError("unhashable type: 'list'",)
functions ['test.ping']

mine.py:317
https://github.com/saltstack/salt/blob/7248c3f2a013e9db1217e7e3873f9a7f526c82d1/salt/modules/mine.py#L317

### Setup
nothing special

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
ctx['salt']['saltutil.runner']('mine.get', tgt='\*', fun='network.ip_addrs')
ctx['salt']['mine.get'](tgt='\*', fun='test.ping')
from orchestrator, for example

### Versions Report
Salt Version:                                                                                                                  [3/6278]
           Salt: 2018.3.0-n/a-fe3a582

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: 3.5.1
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.72-73.55.amzn2.x86_64
         system: Linux
        version: Not Installed

**Comment by ezh** [comment]
I checked the develop branch tip. Error is present.

Python 3.5.5 (default, Jun 26 2018, 08:06:41)
[GCC 6.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> dict = {'firstKey':1, 'secondKey':2, 'thirdKey':3}
>>> dict.get(['firstKey'])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: unhashable type: 'list'
>>> {key:dict.get(key) for key in ['firstKey', 'secondKey']}
{'secondKey': 2, 'firstKey': 1}

**Comment by ezh** [comment]
What branch I should get for PR with fix?

**Comment by rallytime** [comment]
Hi @ezh - Please submit your fix to the `2018.3` branch if you would. :)

**Comment by ezh** [comment]
I checked 2018.3.3 branch. There is different code and it is working.
@rallytime Could you please backport working part to develop branch?

**Comment by rallytime** [comment]
@ezh The code from earlier branches is always merged forward to `develop`. If `2018.3.3` is working, then something has regressed in the `develop` branch and will need to be fixed there. I won't have time to track this down right now, unfortunately. Is that something you're still willing to look into?
