### ISSUE TITLE
smtp returners can not properly display Chinese

### ISSUE THREAD

**Issue by wong751236** [saltstack/salt#50269]
### Description of Issue/Question
Learning saltstack for a couple of weeks 
I'm wondering if there is a way to make the email human readable when I use smtp returners.
Currently, getting something like this

id: someid
function: state.sls
function args: [u'atrm1', {u'pillar': {u'time': u'20:00 10/29/2018'}}]
jid: 20181029130430101864
return: {u'at_|-atrm_|-atrm_|-absent': {u'comment': u'removed 0 job(s)', u'name': u'atrm', u'start_time': '13:04:36.316459', u'result': True, u'duration': 33.01, u'__run_num__': 0, u'__sls__': u'atrm1', u'changes': {}, u'__id__': u'atrm'}, u'cmd_|-echo_|-echo \u53d6\u6d88\u4efb\u52a1\u8ba1\u5212\u6210\u529f_|-run': {u'comment': u'Command "echo \u53d6\u6d88\u4efb\u52a1\u8ba1\u5212\u6210\u529f" run', u'name': u'echo \u53d6\u6d88\u4efb\u52a1\u8ba1\u5212\u6210\u529f', u'start_time': '13:04:36.351986', u'result': True, u'duration': 14.325, u'__run_num__': 1, u'__sls__': u'atrm1', u'changes': {u'pid': 30987, u'retcode': 0, u'stderr': u'', u'stdout': u'\u53d6\u6d88\u4efb\u52a1\u8ba1\u5212\u6210\u529f'}, u'__id__': u'echo'}}

So  1. How can I get the stdout when returning characters include Chinese?? 
      2. Is there a way to make the email human readable ??

 ID: echo
    Function: cmd.run
        Name: echo 取消任务计划成功
      Result: True
     Comment: Command "echo 取消任务计划成功" run
     Started: 13:04:36.351986
    Duration: 14.325 ms
     Changes:   
              ----------
              pid:
                  30987
              retcode:
                  0
              stderr:
              stdout:
                  取消任务计划成功
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

**Comment by garethgreenaway** [comment]
@wong751236 Thanks for the report.  As far as making the email more human readable, one of the available configuration options for the SMTP returner is the option to include a template for what the body of the email should be.  You can configure it with the data that you want in the format you want it.

As far as displaying the Chinese characters correctly in the email, because the template is specified as a jinja template, you have access to all the built in and Salt specific jinja filters, and one of those should be able to output the data correctly.

**Comment by dwoz** [comment]
I think we're asking for trouble when it comes to non-ascii characters with this simple string formatting:

https://github.com/saltstack/salt/blob/develop/salt/returners/smtp_return.py#L237

We should be using the mime specification to properly support emails with non ascii characters.

https://docs.python.org/2/library/email.mime.html#email.mime.text.MIMEText
