### ISSUE TITLE
python-futures: Dependency missing on Debian 9

### ISSUE THREAD

**Issue by paulkramme** [saltstack/salt#50260]
### Description of Issue/Question
I just updated my salt-master via `salt '...' pkg.upgrade` from version 2018.3.2 to 2018.3.3. After the update, all Salt commands issued from the master failed with "No module named concurrent" and journalctl reporting a python stacktrace (appended below). After some research, I installed the debian package `python-futures`. After a salt-master service restart, the master is working again. Is this a bug? Can this be fixed by adding the dependency to the salt packages?

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
`journalctl -xe | cut -d : -f 4` after update via `salt '...' pkg.upgrade`  and `systemctl restart salt-master.service`
``` 
Traceback (most recent call last)
   File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 997, in _connect_minion
     yield minion.connect_master(failed=failed)
   File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
     value = future.result()
   File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
     raise_exc_info(self._exc_info)
   File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1021, in run
     yielded = self.gen.throw(*exc_info)
   File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1188, in connect_master
     master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe, failed)
   File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 1015, in run
     value = future.result()
   File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 237, in result
     raise_exc_info(self._exc_info)
   File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 285, in wrapper
     yielded = next(result)
   File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 697, in eval_master
     pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
   File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 161, in factory
     import salt.transport.zeromq
   File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 31, in <module>
     import salt.transport.mixins.auth
   File "/usr/lib/python2.7/dist-packages/salt/transport/mixins/auth.py", line 16, in <module>
     import salt.master
   File "/usr/lib/python2.7/dist-packages/salt/master.py", line 35, in <module>
     import salt.client.ssh.client
   File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 47, in <module>
     import salt.utils.thin
   File "/usr/lib/python2.7/dist-packages/salt/utils/thin.py", line 16, in <module>
     import concurrent
 ImportError
 [CRITICAL] Unexpected error while connecting to [REDACTED]
 Traceback (most recent call last)
```
### Versions Report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.5
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.5

**Comment by codepanda** [comment]
Swallowing my prideful opinions about javascript and manually installing `python-concurrent.futures` resolves the problem. It's a shame that the maintainers of `python-concurrent.futures` have a hard dependency on `libjs-sphinxdoc`.

**Comment by paulkramme** [comment]
Unfortunately salt-minion seems to be affected, too. The salt-minion crashes with the same error, apparently, which generates huge error logs, which caused my servers to fail over the weekend. The service has to be fixed manually by installing python-futures.

**Comment by codepanda** [comment]
the `v2018.3.3` tag includes an import for `concurrent`:

    salt/utils/thin.py:16:import concurrent

that the `v2018.3.2` tag does not have. This comes from commit 70c60345.

While searching for imports of `concurrent`, I did find that there are quite a few uses of `tornado.concurrent` common to both tags. Here's a selection:

    salt/transport/tcp.py:44:import tornado.concurrent
    salt/transport/ipc.py:20:import tornado.concurrent
    salt/transport/zeromq.py:49:import tornado.concurrent
    salt/utils/async.py:9:import tornado.concurrent

I'm not familiar with either library, not sure how they are or are not related in terms of usage. Just doing some spelunking.

On Ubuntu 18.04, `tornado.concurrent` is provided by `python-tornado`, which has a `Recommends` to `python-concurrent.futures`.

**Comment by gtmanfred** [comment]
This is being handled over here.

https://github.com/saltstack/salt-pack/issues/593
