### ISSUE TITLE
index error in _get_boot_time_aix() for uptime < 1 day

### ISSUE THREAD

**Issue by kappacher** [saltstack/salt#50279]
### Description of Issue/Question
On AIX systems, the status.uptime (salt/modules/status.py) does not work for uptime <1 day.
An index error is raised for etime strings without a day prefix (before a "-").
OK: 7-20:46:46
Not OK:  20:46:46
The list variable "days" tries in all cases to index the fields before/after separator "-".
```
    bt_time = res['stdout']
    days = bt_time.split('-')
    hms = days[1].split(':')
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I promise I will learn how to handle git PR.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt aixhost1 status.uptime

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
verified in 2017.7.7, and cannot find a fix in devel.

**Comment by kappacher** [comment]
Even the Hours part is optional: [[ dd-]hh:]mm:ss

**Comment by garethgreenaway** [comment]
@kappacher Thanks for the report.  Seems like this should be a simple fix, some detection to see if the `-` is in the string and run the split, otherwise just run the split on the `:`.

**Comment by kappacher** [comment]
This whole function _get_boot_time_aix() does exactly the same as psutil.boot_time()  does (or the api interface to psutil of the salt module function ps.boot_time()), but I have not verified if psutil is a mandatory python module in the Salt distribution and if it's hardened against AIX 6/7. If you need some assistance / tests on AIX hosts I am willing to spend some time on it.
