### ISSUE TITLE
Dependency missing in 2018.3.3 .deb

### ISSUE THREAD

**Issue by te-af-github** [saltstack/salt#50297]
### Description of Issue/Question

Missing dependency for 

_python-concurrent.futures_

from 2018.3.3 .deb package. Minion crashes if _python-concurrent.futures_ is not installed.

Seems to have happened back in the days: [33801](https://github.com/saltstack/salt/issues/33801)

### Setup
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: debian 8.11
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-6-amd64
         system: Linux
        version: debian 8.11

### Steps to Reproduce Issue

- Update minion 2018.3.2 -> 2018.3.3
- Restart minion

Result:

Oct 29 23:53:36 node2 salt-minion[3860]: [CRITICAL] Unexpected error while connecting to salt
Oct 29 23:53:36 node2 salt-minion[3860]: Traceback (most recent call last):
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 997, in _connect_minion
Oct 29 23:53:36 node2 salt-minion[3860]: yield minion.connect_master(failed=failed)
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
Oct 29 23:53:36 node2 salt-minion[3860]: value = future.result()
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
Oct 29 23:53:36 node2 salt-minion[3860]: raise_exc_info(self._exc_info)
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 876, in run
Oct 29 23:53:36 node2 salt-minion[3860]: yielded = self.gen.throw(*exc_info)
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1188, in connect_master
Oct 29 23:53:36 node2 salt-minion[3860]: master, self.pub_channel = yield self.eval_master(self.opts, self.timeout, self.safe, failed)
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 870, in run
Oct 29 23:53:36 node2 salt-minion[3860]: value = future.result()
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result
Oct 29 23:53:36 node2 salt-minion[3860]: raise_exc_info(self._exc_info)
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/tornado/gen.py", line 230, in wrapper
Oct 29 23:53:36 node2 salt-minion[3860]: yielded = next(result)
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 697, in eval_master
Oct 29 23:53:36 node2 salt-minion[3860]: pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/salt/transport/client.py", line 161, in factory
Oct 29 23:53:36 node2 salt-minion[3860]: import salt.transport.zeromq
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/salt/transport/zeromq.py", line 31, in <module>
Oct 29 23:53:36 node2 salt-minion[3860]: import salt.transport.mixins.auth
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/salt/transport/mixins/auth.py", line 16, in <module>
Oct 29 23:53:36 node2 salt-minion[3860]: import salt.master
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/salt/master.py", line 35, in <module>
Oct 29 23:53:36 node2 salt-minion[3860]: import salt.client.ssh.client
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/salt/client/ssh/__init__.py", line 47, in <module>
Oct 29 23:53:36 node2 salt-minion[3860]: import salt.utils.thin
Oct 29 23:53:36 node2 salt-minion[3860]: File "/usr/lib/python2.7/dist-packages/salt/utils/thin.py", line 16, in <module>
Oct 29 23:53:36 node2 salt-minion[3860]: import concurrent
Oct 29 23:53:36 node2 salt-minion[3860]: ImportError: No module named concurrent

### Versions Report
Minion specific.

**Comment by dmurphy18** [comment]
duplicate and fixed https://github.com/saltstack/salt-pack/issues/593

**Comment by te-af-github** [comment]
Not fixed for Debian 8.
