### ISSUE TITLE
Very slow salt-master start under a NIS/YP environment.

### ISSUE THREAD

**Issue by aplanas** [saltstack/salt#50304]
### Description of Issue/Question

Very slow salt-master start under a NIS/YP environment.

During the start up there is a check for ACL that implies a call to `pwd.getpwall()` in order to get all the users available in the system:

https://github.com/saltstack/salt/blob/develop/salt/daemons/masterapi.py#L241

If the system is under NIS/YP, this call will require some network access and some request to external services, that can slow down the master start. In my current system this is more than two minutes, but is a variable measure.

I realized that under the same system a call for `pwd.getpwnam()` is very fast, for existing and non existing users.

I think that the iteration needs to be changed, in order to reverse the query, from the acl list to the users in the system.

**Comment by dwoz** [comment]
@aplanas Thank you for reporting this.

**Comment by aplanas** [comment]
Well, I realized that my proposal to solve the issue is not correct, and the check is against an ACL, that can have regular expressions, so there is not sense in iterating over it.

Maybe we can avoid the iteration making access_keys lazy somehow, that checks if the user have rights or not under request.
