### ISSUE TITLE
feature request: dockermod.build network_mode option

### ISSUE THREAD

**Issue by DrPyser** [saltstack/salt#50300]
### Description of Issue/Question
salt.modules.dockermod.build doesn't support all options provided by docker build command and the client.images.build function of the `docker` python sdk(see https://docker-py.readthedocs.io/en/stable/images.html#docker.models.images.ImageCollection.build for all options). 

One such option that would be useful to have is the `network_mode`(e.g. to connect to a docker network, or to the host, when running RUN commands during build).  
Other options I'd like to see supported include `labels`(to set image labels), `target`(to set target stages in multistage builds).

Thanks.

**Comment by dwoz** [comment]
@DrPyser Thanks for opening this issue. Would you like to try making a PR to add these options?

**Comment by DrPyser** [comment]
@dwoz Sure.

**Comment by DrPyser** [comment]
@dwoz Does this require adding/modifying a test case somewhere? If so, should I include it in the PR?
