### ISSUE TITLE
Feature request: skip state if __virtual__ module is not loaded

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#50325]
### Description of Issue/Question
When saltstack state has a module that is not loaded or not available on a system it will fail the state with an error message:
```
Reason: 'cron' __virtual__ returned False: cron module could not be loaded
```
### Steps to Reproduce Issue
have a state run with a module that isn't available on a minion.

### Future handling

is a state is run where a module isn't loaded or can't be loaded the state shouldn't fail but skip with a warning. `state skipped  __virtual__ module 'example' isn't loaded` 
but when a requisite is set on that state it should fail.

**Comment by Ch3LL** [comment]
ping @saltstack/team-core can i get your opinions on this feature request?

**Comment by gtmanfred** [comment]
I disagree that it should be skipped, people should be told that their state failed if it is not loaded.

What i would support is making `onfail` be able to mark a state as successful if it fails, so if a state isn't loaded, you could have an onfail that installs the stuff necessary to run it again, and succeed, and then mark the first run of the failed state as a success if onfail is successful. 

https://github.com/saltstack/salt/issues/46419

**Comment by aboe76** [comment]
@gtmanfred you are right that the normal behavior should be fail, but there should also be a workaround if you know that only that state can fail on your machine and you wan't the rest to continue.

something like `absent` shouldn't cause a failure if a module couldn't even be loaded than it means that it is surely `absent`, and the other way around is also true, if the state is `present` or `running` than if the state module failed to load it should fail the state.
