### ISSUE TITLE
ar

### ISSUE THREAD

**Issue by LaughHammers** [saltstack/salt#50357]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by dwoz** [comment]
I am assuming this was a mistake.

**Comment by LaughHammers** [comment]
Yes whatever is it, it was definitely something just fat fingered. Thanks!
