### ISSUE TITLE
Cannot validate HMAC on CLI when it ends on '=' and has no other special character

### ISSUE THREAD

**Issue by reschl** [saltstack/salt#50377]
### Description of Issue/Question
It is not possible to validate an HMAC via the CLI if it ends on a "=" and has no other special character before the "=". The result is "ERROR executing 'hashutil.hmac_signature': The following keyword arguments are not valid:" for the given challenge_hmac.

It is only a CLI problem. Adding a unit test for hashutils with the same input works just fine.
```
diff --git tests/unit/utils/test_hashutils.py tests/unit/utils/test_hashutils.py
index b37cd6ae27..d0c40ca9c3 100644
--- tests/unit/utils/test_hashutils.py
+++ tests/unit/utils/test_hashutils.py
@@ -156,6 +156,13 @@ class HashutilsTestCase(TestCase):
                 self.bytes_hmac_challenge
             )
         )
+        self.assertTrue(
+            salt.utils.hashutils.hmac_signature(
+                b'Foo',
+                b'secret',
+                b'X8hBZyVkEFWSxUFQWEkrZCVFd5u5a8up75WDxFzaIbc='
+            )
+        )
 
     def test_get_hash_exception(self):
         self.assertRaises(
```

### Setup
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 3.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

### Steps to Reproduce Issue
run either command
```
salt-call hashutil.hmac_signature 'Foo' 'secret' 'X8hBZyVkEFWSxUFQWEkrZCVFd5u5a8up75WDxFzaIbc='
salt \* hashutil.hmac_signature 'Foo' 'secret' 'X8hBZyVkEFWSxUFQWEkrZCVFd5u5a8up75WDxFzaIbc='
```
Adding "/" right in front of "=" the module is executed just fine
```
salt-call hashutil.hmac_signature 'Foo' 'secret' 'X8hBZyVkEFWSxUFQWEkrZCVFd5u5a8up75WDxFzaIbc/='
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
seems salt is interpreting the `=` as a kwarg:

```
(salt-py2) ➜  50376 sudo salt-call --local hashutil.hmac_signature 'Foo' 'secret' 'X8hBZyVkEFWSxUFQWEkrZCVFd5u5a8up75WDxFzaIbc='
The following keyword arguments are not valid: X8hBZyVkEFWSxUFQWEkrZCVFd5u5a8up75WDxFzaIbc=
(salt-py2) ➜  50376 
```
