### ISSUE TITLE
one minion return lots hosts result 

### ISSUE THREAD

**Issue by xjpresley** [saltstack/salt#50372]
### Description of Issue/Question
i have six vm minionid is web01-web06
when i run :  salt 'web01' grains.item ipv4  in salt master 10.0.0.1 
its return six hosts and six  ip （one host only has one ip） . 
i run salt web01 cmd.run ifconfig . it return ip random in web01-web06     i am shock
and im sure those hosts all config different minion id in  /etc/salt/minion_id  .  and more suprise  two of those hosts config the master ip is 10.0.0.2 its another saltmaster  ...  five vm all copy from the first vm web01 host and modify minion id and restart salt minion ..   i want to know how to fix it.     i want to query the minion id cache but i dont know where can find  and i donnot to use salt-key -d to delete the copy vm first    

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
can you paste the sanitized output so I can see clearly the issue? Also can you include the salt versions report
