### ISSUE TITLE
[Question] Is there is a way to programmatically check if pillars are able to render?

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#50375]
### Description of Issue/Question
I'm looking for a way to programmatically check if pillars are able to render and\or up to date.

As I understand so far `saltutil.refresh_pillar` call is asynchronous and can't be used for this at all. I looked into the synchronous refresh_pillar PR(https://github.com/saltstack/salt/pull/50168) and looks like it won't help either. 

I wish there is a `pillar.get` an argument which will force to return an error is the key can't be looked up. Right now it always returns 0 even if there is no key and only in master logs I can find the root of the problem - error in pillar rendering.

```
[behavox@test-run-kproskurin-rm stack]$ salt 'test-run-kproskurin-rm' pillar.get common
test-run-kproskurin-rm:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1607, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/pillar.py", line 188, in get
        raise KeyError('Pillar key not found: {0}'.format(key))
    KeyError: u'Pillar key not found: common'


-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 0
-------------------------------------------
[behavox@test-run-kproskurin-rm stack]$ echo $?
0
```

**Comment by Oloremo** [comment]
Kinda related to https://github.com/saltstack/salt/issues/39793
And https://github.com/saltstack/salt/issues/18510
And https://github.com/saltstack/salt/issues/802

**Comment by Ch3LL** [comment]
Can you include the version you are seeing this? Looks like we need to change the exit code when this fails.

**Comment by roskens** [comment]
I was just dealing with an ext_pillar (makostack) that was failing to render because of a duplicate key. It sure would be nice if `saltutil.pillar_refresh` would have returned False for minions where the pillar data experienced a failure during rendering.

**Comment by Oloremo** [comment]
@Ch3LL 

```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.2.5

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by Ch3LL** [comment]
thanks. So it seems we can use this issue to make sure the exit code is not a 0 when there is a keyerror. Currently `saltutil.pillar_refresh` is currently asynchronous and looking at the PR it looks like it will still simply send an event to make sure the pillar refreshes and wait for the event to return. It looks like there is a try/except there to handle KeyErrors but i'm not seeing where we would ever see that since we are simply firing and waiting for events.

**Comment by Oloremo** [comment]
kinda not sure, but let's mark it as not stale for now.

**Comment by Oloremo** [comment]
Seems like it's fixed in the current master at least.
