### ISSUE TITLE
start java process by saltstack , java process env no LANG var

### ISSUE THREAD

**Issue by linuxeryt** [saltstack/salt#50373]
I start java process by custom mudle of saltstack, java process env no LANG var

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
caSalt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.2.2
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: unknown
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Ch3LL** [comment]
can you please include more information related to the issue? Can you include a small snippet of the custom module? And show the output of what happens when you run the command?

**Comment by linuxeryt** [comment]
I discovered the problem by starting the process with salt-minion-c /etc/ salt-d rather than a startup script. salt-minion-c /etc/ salt-d  does not load the environment variables
