### ISSUE TITLE
rest_cherrypy py3-incompatible POST /keys handler

### ISSUE THREAD

**Issue by pewpewp3w** [saltstack/salt#50381]
### Description of Issue/Question
Exception: 
```
2018-11-02 13:16:44,371 [cherrypy.error.140549867175384:216 ][ERROR   ][1033] [02/Nov/2018:13:16:44] HTTP 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 628, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cprequest.py", line 687, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/lib/encoding.py", line 219, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/cherrypy/_cpdispatch.py", line 54, in __call__
    return self.callable(*self.args, **self.kwargs)
  File "/usr/lib/python3/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1720, in POST
    tarball.addfile(pub_key_file, six.StringIO(pub_key))
  File "/usr/lib/python3.6/tarfile.py", line 1973, in addfile
    self.fileobj.write(buf)
TypeError: string argument expected, got 'bytes'
```

### Steps to Reproduce Issue
```
curl -H 'Content-type: application/json' \
-d '{"mid": "minion_id", "eauth": "pam", "username": "username", "password": "password"}' \
http://salt_api_url/keys
```

### Versions Report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 18.0.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Sep 12 2018, 18:26:19)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-38-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by Ch3LL** [comment]
did this just start occurring after an upgrade? i'm guessing this is related to the Unicode work we did in 2018.3

**Comment by Ch3LL** [comment]
thanks for the PR! I will go ahead and close the issue.

**Comment by pewpewp3w** [comment]
2019.2 released without this fix, /keys still broken
