### ISSUE TITLE
salt service is not logging on windows server 2012

### ISSUE THREAD

**Issue by cbojja22** [saltstack/salt#50404]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
salt-call.bat -l log_file debug state.apply

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by dwoz** [comment]
@cbojja22 Does it work correctly using the `--log-file` option? The command would be something like this `salt-call.bat --log-file salt-call.log -l debug`
