### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode characters

### ISSUE THREAD

**Issue by crazyeefly** [saltstack/salt#50408]
### Description of Issue/Question

salt '*' cp.get_dir salt://shenjh  /temp can not work

there is some wrong log  on other master :
2018-11-07 11:13:38,485 [salt.master                                           :1795][ERROR   ][26762] Error in function _file_list:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 1788, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python2.7/site-packages/salt/utils/decorators/__init__.py", line 594, in wrapped
    **salt.utils.data.decode_dict(kwargs)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/__init__.py", line 752, in file_list
    ret.update(self.servers[fstr](load))
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 422, in file_list
    return _file_lists(load, 'files')
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 398, in _file_lists
    _add_to(ret['files'], path, root, files)
  File "/usr/lib/python2.7/site-packages/salt/fileserver/roots.py", line 335, in _add_to
    is_link = salt.utils.path.islink(abs_path)
  File "/usr/lib/python2.7/site-packages/salt/utils/path.py", line 44, in islink
    return os.path.islink(path)
  File "/usr/lib64/python2.7/posixpath.py", line 135, in islink
    st = os.lstat(path)
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 88-89: ordinal not in range(256)

python  env:
Python 2.7.8 (default, Oct 20 2015, 16:03:21) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> import locale
>>> def p(f):
...     print '%s.%s(): %s' % (f.__module__, f.__name__, f())
... 

>>> p(sys.getdefaultencoding)
sys.getdefaultencoding(): ascii
>>> p(sys.getfilesystemencoding)
sys.getfilesystemencoding(): UTF-8
>>> p(locale.getdefaultlocale)
locale.getdefaultlocale(): ('en_US', 'UTF-8')
>>> p(locale.getpreferredencoding)
locale.getpreferredencoding(): UTF-8
>>> exit()

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt --versions-report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
 
System Versions:
           dist: redhat 7.3 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by dwoz** [comment]
@crazyeefly Thank you for reporting the issue. I am having trouble re-producing this on a fresh install of Redhat 7.3. Is the python package up-to-date on both systems?

**Comment by Slamoth** [comment]
I am also having that problem. I can give some information though.
This pc is a parallels virtual windows10 (10 is on in Turkish).
I can run command `salt -G os:Windows grains.items` with success.
But when I try to `salt-run cache.grains 'windowson'` it is not a success.
UnicodeEncodeError: 'latin-1' codec can't encode character '\u015f' in position 323: ordinal not in range(256)
That character is one of the latin characters like üÜıİşŞğĞçÇ -> http://www.fileformat.info/info/unicode/char/15f/index.htm
```
salt --versions-report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 3.8.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 3.8.2
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.6 (default, Mar 22 2017, 12:26:13) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.2

System Versions:
           dist: SuSE 42.3 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.18.7-1.g952d850-default
         system: Linux
        version: openSUSE  42.3 x86_64

salt -G os:Windows grains.items
windowson:
    ----------
    SSDs:
        - \\.\PhysicalDrive0
    biosversion:
        14.1.0 (45387)
    cpu_model:
        Intel(R) Core(TM) i7-4870HQ CPU @ 2.50GHz
    cpuarch:
        AMD64
    disks:
    domain:
        xxx.xxx.com
    fqdn:
        windowson.xxx.xxx.com
    fqdn_ip4:
        - 10.10.10.14
    fqdn_ip6:
    gpus:
    groupname:
    host:
        windowson
    hwaddr_interfaces:
        ----------
        Intel(R) 82574L Gigabit Network Connection:
            00:1C:42:72:F7:19
    id:
        windowson
    init:
        Windows
    ip4_interfaces:
        ----------
        Intel(R) 82574L Gigabit Network Connection:
            - 10.10.10.14
    ip6_interfaces:
        ----------
        Intel(R) 82574L Gigabit Network Connection:
    ip_interfaces:
        ----------
        Intel(R) 82574L Gigabit Network Connection:
            - 10.10.10.14
    ipv4:
        - 10.10.10.14
    ipv6:
    kernel:
        Windows
    kernelrelease:
        10.0.17763
    kernelversion:
        10.0.17763
    locale_info:
        ----------
        defaultencoding:
            cp1254
        defaultlanguage:
            tr_TR
        detectedencoding:
            cp1254
    localhost:
        windowson
    manufacturer:
        Parallels Software International Inc.
    master:
        10.0.100.136
    mem_total:
        2025
    motherboard:
        ----------
        productname:
            Parallels Virtual Platform
        serialnumber:
            None
    nodename:
        windowson
    num_cpus:
        2
    num_gpus:
        0
    os:
        Windows
    os_family:
        Windows
    osfinger:
        Windows-10
    osfullname:
        Microsoft Windows 10 Pro
    osmanufacturer:
        Microsoft Corporation
    osrelease:
        10
    osrelease_info:
        - 10
    osservicepack:
        None
    osversion:
        10.0.17763
    path:
        C:\Program Files (x86)\Parallels\Parallels Tools\Applications;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\salt;C:\Windows\system32\config\systemprofile\AppData\Local\Microsoft\WindowsApps;c:\salt\bin\lib\site-packages\pywin32_system32;c:\salt\bin\lib\site-packages\pywin32_system32
    pid:
        2460
    productname:
        Parallels Virtual Platform
    ps:
        tasklist.exe
    pythonexecutable:
        c:\salt\bin\python.exe
    pythonpath:
        - c:\salt\bin\lib\site-packages\git\ext\gitdb
        - c:\salt\bin\Scripts
        - c:\salt\bin\python27.zip
        - c:\salt\bin\DLLs
        - c:\salt\bin\lib
        - c:\salt\bin\lib\plat-win
        - c:\salt\bin\lib\lib-tk
        - c:\salt\bin
        - c:\salt\bin\lib\site-packages
        - c:\salt\bin\lib\site-packages\win32
        - c:\salt\bin\lib\site-packages\win32\lib
        - c:\salt\bin\lib\site-packages\gitdb\ext\smmap
    pythonversion:
        - 2
        - 7
        - 14
        - final
        - 0
    saltpath:
        c:\salt\bin\lib\site-packages\salt
    saltversion:
        2018.3.4
    saltversioninfo:
        - 2018
        - 3
        - 4
        - 0
    serialnumber:
        Parallels-A3 92 47 6B 69 8A 4D 2F 96 46 5B 65 62 B1 B9 47
    server_id:
        1171136065
    shell:
        C:\Windows\system32\cmd.exe
    timezone:
        (UTC+02:00) Atina, Bükreş
    username:
        WINDOWSON$
    virtual:
        Parallels
    windowsdomain:
        ssm.gov.tr
    zfs_feature_flags:
        False
    zfs_support:
        False
    zmqversion:
        4.1.6
salt-run cache.grains 'windowson'
Traceback (most recent call last):
  File "/usr/bin/salt-run", line 10, in <module>
    salt_run()
  File "/usr/lib/python3.4/site-packages/salt/scripts.py", line 412, in salt_run
    client.run()
  File "/usr/lib/python3.4/site-packages/salt/cli/run.py", line 40, in run
    ret = runner.run()
  File "/usr/lib/python3.4/site-packages/salt/runner.py", line 271, in run
    daemonize=False)
  File "/usr/lib/python3.4/site-packages/salt/client/mixins.py", line 485, in _proc_function
    return self.low(fun, low, full_return=False)
  File "/usr/lib/python3.4/site-packages/salt/client/mixins.py", line 261, in low
    return self._low(fun, low, print_event=print_event, full_return=full_return)
  File "/usr/lib/python3.4/site-packages/salt/client/mixins.py", line 418, in _low
    mminion=self.mminion,
  File "/usr/lib/python3.4/site-packages/salt/utils/job.py", line 107, in store_job
    mminion.returners[savefstr](load['jid'], load)
  File "/usr/lib/python3.4/site-packages/salt/returners/mysql.py", line 344, in save_load
    cur.execute(sql, (jid, salt.utils.json.dumps(load)))
  File "/usr/lib/python3.4/site-packages/pymysql/cursors.py", line 166, in execute
    result = self._query(query)
  File "/usr/lib/python3.4/site-packages/pymysql/cursors.py", line 322, in _query
    conn.query(q)
  File "/usr/lib/python3.4/site-packages/pymysql/connections.py", line 854, in query
    sql = sql.encode(self.encoding, 'surrogateescape')
UnicodeEncodeError: 'latin-1' codec can't encode character '\u015f' in position 558: ordinal not in range(256)
```
