### ISSUE TITLE
Windows 7 32-bit Minions broken on 2018.3.3 - Windows Service Gone

### ISSUE THREAD

**Issue by tjgruber** [saltstack/salt#50444]
### Description of Issue/Question

On a bunch of Windows Minions, suddenly, the salt-minion service is gone. When I look at services.msc or Get-Service in PowerShell, there is not a salt-minion service.

Installing fresh, reinstall from Chocolatey, or a reinstall from the Windows installers located [here](https://docs.saltstack.com/en/latest/topics/installation/windows.html) results in a successful reinstall. However, there is no salt-minion service afterwards. It's like the installation never creates a salt-minion service on the system and therefore, of course, cannot ever start salt-minion.

Another thing, is that most of these minions were previously working well with the Salt Master, and show up in the salt-key -L list.

### Versions Report
Version 2018.3.3
I tried with both 32-bit Py2 and Py3 versions.

I'm 99% sure that the commonality between all these Windows machines is Windows 7 32-bit.  I can NOT seem to find any Win10 x64 minions with the same issue. If I do, I'll update.

I did find a Win7 x64 minion, and that IS working just fine.

**Comment by tjgruber** [comment]
This all started with "Latest release: 2018.3.3 (October 24, 2018)".

Everything is great before that, so definitely a correlation there.

What logs from where should I pull up to identify the issue?

**Comment by twangboy** [comment]
What version are you migrating from?

**Comment by dwoz** [comment]
@tjgruber Are you downloading the packages from https://repo.saltstack.com ?

**Comment by tjgruber** [comment]
> What version are you migrating from?

I'm not migrating from anything. It's like this from a fresh install of Salt-Minion.

**Comment by tjgruber** [comment]
> @tjgruber Are you downloading the packages from https://repo.saltstack.com ?

I haven't from there. I have used from https://docs.saltstack.com/en/latest/topics/installation/windows.html and https://chocolatey.org/packages/saltminion.

**Comment by tjgruber** [comment]
I think I found the issue. 

It may be the AV killing it on those computers. I'm not sure what Win7 32-bit has to do with it, but I have added the exception. I'll update on the status next week.

**Comment by tjgruber** [comment]
This was due to ESET marking it as an unsafe application.
I have added exceptions and is now is now functioning properly.

This issue can be closed.
