### ISSUE TITLE
PyGit2 wrong user for .gitconfig

### ISSUE THREAD

**Issue by cdalvaro** [saltstack/salt#50459]
PyGit2 is trying to use the wrong `.gitconfig` file when `salt-master` is launch as `root` but the user `/etc/salt/master` is set to a different one.

```
[CRITICAL] Exception caught while initializing gitfs remote '#########': failed to stat '/root/.gitconfig'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 449, in __init__
    self.new = self.init_remote()
  File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1604, in init_remote
    self.repo = pygit2.init_repository(self.cachedir)
  File "/usr/local/lib/python3.5/dist-packages/pygit2/__init__.py", line 149, in init_repository
    check_error(err)
  File "/usr/local/lib/python3.5/dist-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: failed to stat '/root/.gitconfig'
[CRITICAL] Failed to load gitfs
[CRITICAL] Master failed pre flight checks, exiting
```

I think the problem is the way in which the `search_path` for the global config for pygit2 is set

https://github.com/saltstack/salt/blob/b87bfd36b23104b0ba0cd4a10c266c1eb066964e/salt/utils/gitfs.py#L1625-L1626

I understand that launching `salt-master` as root but setting it for running as another user is the intended purpose with the current implementation. At least, this is what I understand after reading the [official guide](https://docs.saltstack.com/en/latest/ref/configuration/nonroot.html).

Please, correct me if I am wrong.

**Comment by dwoz** [comment]
@cdalvaro Thanks for reporting this. I have confirmed it is an issue in 2018.3.3. Can you please provide us with the output from `salt -V`?

**Comment by cdalvaro** [comment]
```sh
salt -V
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: 1.7.5
         Jinja2: 2.8
        libgit2: 0.27.7
        libnacl: 1.6.1
       M2Crypto: 0.30.1
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.0
   pycryptodome: Not Installed
         pygit2: 0.27.2
         Python: 3.5.2 (default, Nov 23 2017, 16:37:01)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: 0.6.8
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.4.59+
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by dwoz** [comment]
Looks like we can set the search path via pygit2. I added this above the `init_repository` call:
```
pygit2.option(pygit2.GIT_OPT_SET_SEARCH_PATH, pygit2.GIT_CONFIG_LEVEL_GLOBAL, os.environ.get('HOME', '/root'))
```
That seems to have resolved the issue.

**Comment by cdalvaro** [comment]
When you run `salt-master` as `root` but `user` is set to another user (e.g. `salt`) in the `master` config file, is the `HOME` env variable set to the correct one (e.g. `/home/salt`)?

Thank you for your time!

**Comment by dwoz** [comment]
Yes, I tested this with the `user` setting in the master config. In my case I was running as user `admin` and the HOME environment variable is `/home/admin`.
