### ISSUE TITLE
Remove final RAET references from pkg files

### ISSUE THREAD

**Issue by rallytime** [saltstack/salt#50529]
RAET was deprecated in Oxygen and needed to be removed in Neon. All of the code was removed in PR https://github.com/saltstack/salt/pull/49916. However, some lingering references for raet/ioflo remain in the `pkg` directory. These need to be handled and I wasn't able to get to them in the original PR. This issue is to track that effort.

Refs: https://github.com/saltstack/salt/issues/49432

**Comment by sagetherage** [comment]
@Ch3LL I keep wanting a label for deprecation tickets, but not sure `deprecation` is correct and understood. It doesn't look like this was on the Epic for Neon deprecation list, I can start an Epic for Sodium and should I put this in there?

**Comment by Ch3LL** [comment]
I just verified that none of the current package files reference raet, only in files in `pkg/old` which is an archive of the old package files.
