### ISSUE TITLE
cp.get_url in _modules not work on salt-ssh

### ISSUE THREAD

**Issue by jils2013** [saltstack/salt#50525]
### Description of Issue/Question
i used cp.get_url(other function seems not work on salt-ssh with salt filesystem) in my module,Unlike direct calls, always return False in the module.

any preparation before call cp.get_url in a module?
### Setup
```
[root@saltmaster ~]# cat /srv/salt/_modules/testmod.py 
def get_url(source,dest):
        return __salt__['cp.get_url'](source,dest)
[root@saltmaster ~]# cat /srv/salt/testcp.sls 
#!py
import logging

def run():
        log=logging.getLogger(__name__)
        log.error(__salt__['cp.get_url']('salt://testfile','/tmp/'))
        log.error(__salt__['testmod.get_url']('salt://testfile','/tmp/'))
        return {}
[root@saltmaster ~]# salt-ssh tgthost state.apply testcp
[ERROR   ] True
[ERROR   ] False
tgthost :

Summary for tgthost 
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
Total run time:  0.000 ms
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
master version:2018.3.3

**Comment by dwoz** [comment]
@jils2013 Have you tried the `file.managed` state?

```
/home/admin/testfile:
  file.managed:
    - source: salt://testfile
```

**Comment by jils2013** [comment]
@dwoz ,when i call salt.client.ssh.Single like client/ssh/wrapper/cp.py,get following
`[root@saltmaster ~]# cat /srv/salt/testcp.sls 
#!py
import logging

def run():
        log=logging.getLogger(__name__)
        log.error(__salt__['cp.get_url']('salt://testfile','/tmp/'))
        log.error(__salt__['testmod.get_url']('salt://testfile','/tmp/',__salt__.kwargs))
        return {}
[root@saltmaster ~]# cat /srv/salt/_modules/testmod.py  
import logging
import salt.client.ssh.client

def get_url(source,dest,saltkwargs):
        log=logging.getLogger(__name__)
        single = salt.client.ssh.Single(__opts__,'',**saltkwargs)
        ret = single.shell.send(source, dest)
        return ret
[root@saltmaster ~]# salt-ssh tgthost state.apply testcp
[ERROR   ] True
[ERROR   ] [u'', u'ssh: Could not resolve hostname salt: Name or service not known\r\n', 1]
tgthost:

Summary for tgthost
-----------
Succeeded: 0
Failed:   0
-----------
Total states run:    0
Total run time:  0.000 ms`
