### ISSUE TITLE
Error while running sls through reactor

### ISSUE THREAD

**Issue by nkv16786** [saltstack/salt#50537]
### Description of Issue/Question
I have  windows masterless minion setup.
I am trying to run a sls file through reactor but not able to do so(getting error).
The sls file is running fine when triggered directly using state.sls
`salt-call state.sls test`

### Setup

```
**SLS**
exc_cmd:
  cmd.run:
    - name: hostname
```

**Reactor**
```
reactor:
  - 'salt/engines/hook/test':
    - salt://test.sls

```
### Steps to Reproduce Issue

```
018-11-16 01:49:50,726 [salt.utils.verify:535 ][WARNING ][2144] Insecure logging configuration detected! Sensitive data may be logged.
2018-11-16 01:52:31,614 [salt.utils.reactor:423 ][ERROR   ][900] Reactor 'exc_cmd' failed to execute local 'run'
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\utils\reactor.py", line 335, in run
    wrap_call = salt.utils.args.format_call(l_fun, low)
  File "c:\salt\bin\lib\site-packages\salt\utils\args.py", line 447, in format_call
    used_args_count
SaltInvocationError: local takes at least 2 arguments (1 given)
```

### Versions Report
salt-call 2018.3.2 (Oxygen)
Windows 2012R2

**Comment by nkv16786** [comment]
@sumeetisp

**Comment by markuskramerIgitt** [comment]
Not every valid state.sls is a valid reactor.sls 
A reactor cannot `cmd.run`

Reactors are executed on the master.
As reactors run on the maser, I think masterless cannot make use of the reactor.

To run state test.sls on the minion you must write a seperate reactor on the master at /srv/salt/reactor/execute_test_state_on_minion.sls:
```
execute_test_state_on_minion:
  local.state.sls :
    - tgt: {{data['id']}}
    - arg:
      - test
```

https://docs.saltstack.com/en/getstarted/event/reactor.html

**Comment by nkv16786** [comment]
I am just trying this article, and it looks reactors work in masterless setup also.

https://blog.gtmanfred.com/masterless-reactor.html

**Comment by Ch3LL** [comment]
you will want to use the local reactions and target your minion as documented here: https://docs.saltstack.com/en/latest/topics/reactor/#local-reactions

but use `local.cmd.run` instead. 

For your use case I believe this would work but have not tested:

```
clean_tmp:
  local.cmd.run:
    - tgt: 'os:Ubuntu'
    - expr_form: grain
    - arg:
      - hostname
```

**Comment by nkv16786** [comment]
Hi,
I tried with ,
`clean_tmp:
  local.cmd.run:
    - tgt: 'os:Ubuntu'
    - expr_form: grain
    - arg:
      - hostname`

but got the following error in minion logs,
`2018-11-18 20:58:19,075 [salt.utils.reactor:423 ][ERROR   ][1580] Reactor 'clean_tmp' failed to execute local 'cmd.run'
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\utils\reactor.py", line 415, in run
    l_fun(*args, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\utils\reactor.py", line 442, in local
    self.client_cache['local'].cmd_async(tgt, fun, **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\client\__init__.py", line 464, in cmd_async
    **kwargs)
  File "c:\salt\bin\lib\site-packages\salt\client\__init__.py", line 354, in run_job
    raise SaltClientError(general_exception)
SaltClientError: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
`

**Comment by nkv16786** [comment]
This worked for me,
exc_command:
  caller.cmd.shell:
    - args:
      - 'hostname'

Thanks for the help :)
