### ISSUE TITLE
salt-key: key deletion not working with eauth

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#50544]
### Description of Issue/Question
When using external auth is not possible to delete the minion key.

It looks that key name is not passed to `_run_cmd` function in https://github.com/saltstack/salt/blob/develop/salt/key.py#L179
```
_run_cmd: {'fun': 'key.delete', 'token': '7590720fd41faa2e98ddb3cd6947934bcf4c9fc5f74928a41ab08c375db22271', 'kwarg': {}, 'arg': [None]}
```
I was able to fix it by changing:
https://github.com/saltstack/salt/blob/develop/salt/key.py#L268
```
 ret = self._run_cmd(cmd)
```
Into:
```
                if self.opts.get('eauth') and cmd in ('accept', 'reject', 'delete'):
                    ret = self._run_cmd(cmd, args=ret['minions'])
                else:
                    ret = self._run_cmd(cmd)
```
It looks rather like workaround than a proper solution for me but it's working and I was unable to fix it in better way.

When `eauth` is not used then key name is fetched here: https://github.com/saltstack/salt/blob/develop/salt/key.py#L168

If You agree to such fix I could provide PR or provide better fix with some guidance how to do this in a proper way.

### Setup
Enable eauth in /etc/salt/master
```
external_auth:
  pam:
    users%:
      - '.*'
      - '@wheel'
      - '@runner'
      - '@jobs'
```
Add user to group `users`

### Steps to Reproduce Issue
Log on you user account and execute:
```
salt-key -T --auth=pam -d example_minion
```

### Versions Report
```
Salt Version:
           Salt: 2017.7.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

```

**Comment by Ch3LL** [comment]
ping @DmitryKuzmenko can you take a look at @msciciel proposed fix. Does that seem like a proper fix?

**Comment by DmitryKuzmenko** [comment]
The minion list for 'accept', 'reject' and 'delete' commands is created by an additional match command and is kept in 'dict_match' variable.
If `salt-key` is not using `eauth` it manages keys directly like master does. It uses the key interface commands that have both `match` and `dict_match` arguments.
If `salt-key` is using `eauth` it asks master to manage keys via `wheel` interface that is slightly different. It has different commands for `match` and `dict_match` like `delete` and `delete_dict`.
So slightly hacky but more general solution would look like this:
```
diff --git a/salt/key.py b/salt/key.py
index e732919966..4490bb3079 100644
--- a/salt/key.py
+++ b/salt/key.py
@@ -172,6 +172,9 @@ class KeyCLI(object):
                 ret.pop('local', None)
             return ret
 
+        if cmd in ('accept', 'reject', 'delete'):
+            cmd += '_dict'
+            self.opts['match'] = self.opts.get('dict_match')
         fstr = 'key.{0}'.format(cmd)
         fun = self.client.functions[fstr]
         args, kwargs = self._get_args_kwargs(fun, args)
```

**Comment by DmitryKuzmenko** [comment]
@msciciel are you able to test this patch? I'll make PR for this if it works good for you.

**Comment by msciciel** [comment]
@DmitryKuzmenko unfortunately yours patch is not working :(

**Comment by msciciel** [comment]
@DmitryKuzmenko any chances for another solution?

**Comment by DmitryKuzmenko** [comment]
@msciciel sorry for long delay. Just checked that once more. The following must work.
```diff
diff --git a/salt/key.py b/salt/key.py
index 78b359bc3b..18bbce83bf 100644
--- a/salt/key.py
+++ b/salt/key.py
@@ -173,6 +173,8 @@ class KeyCLI(object):
                 ret.pop('local', None)
             return ret
 
+        if cmd in ('accept', 'reject', 'delete') and args is None:
+            args = self.opts.get('match_dict', {}).get('minions')
         fstr = 'key.{0}'.format(cmd)
         fun = self.client.functions[fstr]
         args, kwargs = self._get_args_kwargs(fun, args)
```

**Comment by msciciel** [comment]
@DmitryKuzmenko I've tested and it's working now properly. Thanks.
