### ISSUE TITLE
Saltstack issue rhel7

### ISSUE THREAD

**Issue by KalyaniRaval** [saltstack/salt#50560]
[WARNING ] Unable to bind socket 192.168.14.146:4505, error: [Errno 98] Address already in use; Is there another salt-master running?
The salt master is shutdown. The ports are not available to bind

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

getting this error for salt-master...
killing all the  process using killall salt-master.....still the same issue

**Comment by Poil** [comment]
Please give the result of `salt --versions-report`
Do you have selinux enabled ?

**Comment by KalyaniRaval** [comment]
no...i have almost worked on basic things in salt-stack....i am not even able to configure rest-api

**Comment by KalyaniRaval** [comment]
Not able to configure rest api for salt-stack
systemctl restart salt-mastercurl -sSk http://:8000/login -H 'Accept: application/x-yaml' -d username=halite -d password=halite -d eauth=auto

command used to authenticate the salt-api
errror: Failed to parse signal string Sk.

Salt-version

Salt Version:
Salt: 2018.3.3

Dependency Versions:
cffi: 1.6.0
cherrypy: unknown
dateutil: Not Installed
docker-py: 1.10.6
gitdb: 0.6.4
gitpython: 2.0.8
ioflo: Not Installed
Jinja2: 2.7.2
libgit2: 0.26.3
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.5.6
mysql-python: Not Installed
pycparser: 2.14
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: 0.26.4
Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
python-gnupg: Not Installed
PyYAML: 3.11
PyZMQ: 15.3.0
RAET: Not Installed
smmap: 0.9.0
timelib: Not Installed
Tornado: 4.2.1
ZMQ: 4.1.4

System Versions:
dist: centos 7.5.1804 Core
locale: UTF-8
machine: x86_64
release: 3.10.0-862.11.6.el7.x86_64
system: Linux
version: CentOS Linux 7.5.1804 Core


here is my full information about rest-api....i have no idea about how to configure and use it......

**Comment by KalyaniRaval** [comment]
no proper answer so closing the issue
