### ISSUE TITLE
different operations of cmd.run in _modules

### ISSUE THREAD

**Issue by jils2013** [saltstack/salt#50561]
### Description of Issue/Question
in target host,i run a failed mv command due a filename starting with .
```
[root@tgthost ~]# ls -a /tmp/dira
.  ..  .1
[root@tgthost ~]# ls -a /tmp/dirb
.  ..
[root@tgthost ~]# mv /tmp/dira/* /tmp/dirb;rmdir --ignore-fail-on-non-empty -p /tmp/dira
mv: cannot stat '/tmp/dira/*': No such file or directory

```
but why running this command in _modules give an diffrent error(from direct run/call cmd.run)?
```
[root@saltmaster ~]# cat /srv/salt/_modules/testmod.py      
import os

def runcmd():
        cmd='mv /tmp/dira/* /tmp/dirb;rmdir --ignore-fail-on-non-empty -p /tmp/dira'
        return __salt__['cmd.run'](cmd)

[root@saltmaster ~]# salt tgthost saltutil.sync_modules
tgthost:
    - modules.testmod
[root@saltmaster ~]# salt tgthost cmd.run 'mv /tmp/dira/* /tmp/dirb;rmdir --ignore-fail-on-non-empty -p /tmp/dira'  
tgthost:
    mv: cannot stat '/tmp/dira/*': No such file or directory
[root@saltmaster ~]# salt tgthost testmod.runcmd
tgthost:
    mv: unrecognized option '--ignore-fail-on-non-empty'
    Try 'mv --help' for more information.
ERROR: Minions returned with non-zero exit code

```

### Setup
see above.
### Steps to Reproduce Issue
see above.
### Versions Report
2018.3.3

**Comment by garethgreenaway** [comment]
@jils2013 Thanks for the report.  It appears that the `cmd` is being processed and treated as one command.  Looking at what you're trying to accomplish above, I believe calls out to other Salt modules might solve the problem easier and cleaner.  For the move, you can use `file.move` and for the rmdir, you could use `file.remove`.
