### ISSUE TITLE
Feature request: add salt.modules.file.tail

### ISSUE THREAD

**Issue by cruscio** [saltstack/salt#50578]
### Description of Issue/Question

It'd be useful to have a `tail` method in the `file` module, for retrieving the end of log files from minions when troubleshooting issues - particularly on Windows where `cmd.run 'tail -n <#> <file_name>'` isn't an option. Regardless of platform, it'd be nice to have a python-native tail implementation.  

E.g. `salt.modules.file.tail(path, lines=10)` - [example implementations](https://stackoverflow.com/questions/136168/get-last-n-lines-of-a-file-with-python-similar-to-tail) 

-----

Alternatively, implement/document use of negative `seek` & `offset` parameters in `seek_read` - which doesn't seem possible without a significant change to `seek_read`, given that [internally it uses `os.lseek`](https://github.com/saltstack/salt/blob/0b32461f0f3923193f06c2a68b45ab661246bade/salt/modules/file.py#L3238)

**Comment by steveno** [comment]
I'll be submitting a PR for this later today. Feel free to assign to me.

**Comment by cruscio** [comment]
I was just testing this change, but if you have something you want to submit, go for it. 

```


def tail(path,lines='10'):
    '''
    .. versionadded:: Neon

    Just like the ``tail`` command, return the last lines of a file.

    path
        path to file

    lines
        number of lines to return. Default is 10

    CLI Example:

    .. code-block:: bash

        salt '*' file.tail /path/to/file 100
    '''
    path = os.path.realpath(os.path.expanduser(path))

    if not os.path.isfile(path):
        raise SaltInvocationError('File not found: {0}'.format(path))

    if not __utils__['files.is_text'](path):
        raise SaltInvocationError(
            'Cannot tail a binary file: {0}'.format(path))

    try:
        lines = int(lines)
    except ValueError:
        log.error('file.tail: \'lines\' value must be an integer')
        lines = 10

    try:
        with salt.utils.files.fopen(path,mode='r') as ofile:
            # Source: https://stackoverflow.com/a/13790289
            _buffer=4098
            lines_found = []
            block_counter = -1
            while len(lines_found) <= int(lines):
                try:
                    ofile.seek(block_counter * _buffer, os.SEEK_END)
                except IOError:
                    ofile.seek(0)
                    lines_found = ofile.readlines()
                    break
                lines_found = ofile.readlines()
                block_counter -= 1
            return lines_found[-lines:]
    except (OSError, IOError) as exc:
        raise CommandExecutionError(
            "Unable to open file '{0}'. "
            "Exception: {1}".format(path, exc)
        )
```

**Comment by steveno** [comment]
This issue can be closed now. #50708 was merged.
