### ISSUE TITLE
SSH authorized keys

### ISSUE THREAD

**Issue by arahnale** [saltstack/salt#50584]
Hello. Managing public keys on clients only allows you to add and delete keys. But it does not give control over the keys.

There is not enough functionality to specify only allowed keys. That other keys (for example added manually) were deleted.

**Comment by mchugh19** [comment]
This functionality was added in #50141 which will be released with Neon

**Comment by Ch3LL** [comment]
since this is already closed i will go ahead and close. thanks @mchugh19
