### ISSUE TITLE
[Feature Request] Ability to override retcode of cmd.run based on the output

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#50597]
### Description of Issue/Question
This feature is inspired by Ansible's [failed_when](https://docs.ansible.com/ansible/2.7/user_guide/playbooks_error_handling.html) feature which is very useful in many strange cases.

So the idea is to rely on the specific thing in the output of the cmd execution if explicitly asked. 

So example Hadoop has this command
```
hdfs namenode -initializeSharedEdits -nonInteractive
```

Which is idempotent, but if you run it the second time it will return exit code 1 and text like:
> Running in non-interactive mode, and data appears to exist in QJM to [172.31.27.49:8485, 172.31.18.78:8485, 172.31.28.233:8485]. Not formatting.
> 18/11/21 12:46:00 INFO util.ExitUtil: Exiting with status 1

So, I'd like not to fail in this situation since everything is fine.

The alternative is to use the `cmd.script` and write a script... which will catch both exit code and the output and produce the result based on some logic but it's not really convenient, especially if you want to write such script in bash.

The most simple and stupid approach for illustration only will look like this:
```
--- /usr/lib/python2.7/site-packages/salt/states/cmd.py	2018-11-21 01:45:58.743596210 +0000
+++ /opt/behavox/salt/states/_states/cmd.py	2018-11-21 12:39:51.143085915 +0000
@@ -669,6 +669,7 @@
         hide_output=False,
         timeout=None,
         ignore_timeout=False,
+        ok_when=False,
         use_vt=False,
         **kwargs):
     '''
@@ -906,6 +907,15 @@
             ret['changes']['retcode'] = 0
             ret['result'] = True

+    # Ignore exit code if asked and check for the pattern in the output
+    if ok_when:
+        for stream in ['stderr', 'stdout']:
+            for line in ret['changes'][stream].splitlines():
+                 if ok_when in line:
+                      ret['changes']['retcode'] = 0
+                      ret['result'] = True
+                      break
+
     if stateful:
         ret = _reinterpreted_state(ret)
     if __opts__['test'] and cmd_all['retcode'] == 0 and ret['changes']:
```

**Comment by Ch3LL** [comment]
will approve as a feature request :)

**Comment by Oloremo** [comment]
Looks like this feature is implemented, thanks!
