### ISSUE TITLE
salt-call Segmentation fault: No such process (src/thread.cpp:147) means out of memory

### ISSUE THREAD

**Issue by morgana2313** [saltstack/salt#50598]
### Description of Issue/Question

When salt-call runs out of memory it can give an enigmatic message: "Segmentation fault: No such process (src/thread.cpp:147)"

It might be better to show a n out-of-memory error. Perhaps this is not a bug as such in Saltstack, if so this report might hint others to the cause of this segmentation fault.

### Setup
I tested this in an LXD container running Alpine/Edge and squeezed the memory on the lxd host: `lxc config set container_name limits.memory  100MB`
Inside the container: `while salt-call saltutil.sync_all; do top -b -n1 |head -n1; done`

Strace shows that the fault occurs when salt-call makes a new thread:

```
mmap(NULL, 94208, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fd950018000
mprotect(0x7fd95001a000, 86016, PROT_READ|PROT_WRITE) = 0
clone(child_stack=0x7fd95002e648, flags=CLONE_VM|CLONE_FS
No such process (src/thread.cpp:147)
|CLONE_FILES|CLONE_SIGHAND|CLONE_THREAD|CLONE_SYSVSEM|CLONE_SETTLS|CLONE_PARENT_SETTID|CLONE_CHILD_CLEARTID|0x400000, parent_tidptr=0x7fd95002eb20, tls=0x7fd95002eae8, child_tidptr=0x7fd95002eb20) = 3693
+++ killed by SIGSEGV +++
Segmentation fault
```

### Versions Report
~ # salt --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Aug 16 2018, 14:17:09)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-34-generic
         system: Linux
        version: Not Installed

**Comment by morgana2313** [comment]
Shortage of memory seems to trigger the segfault, but it also happens on containers that have 900MB memory free.

**Comment by Ch3LL** [comment]
ping @saltstack/team-core is this something we can handle since its seg faulting?

**Comment by morgana2313** [comment]
I think this problem may have started with Alpine/3.8 and may not be related to saltstack. Alpine ticket: https://bugs.alpinelinux.org/issues/9675
