### ISSUE TITLE
Redis returner fail with KeyError when 'cluster_mode' set to False

### ISSUE THREAD

**Issue by Mark3K** [saltstack/salt#50593]
### Description of Issue/Question
using configurations as below:
```yaml
redis.db: 0
redis.host: 127.0.0.1
port: 6379
cluster_mode: False
```
the redis returner will fail at:
```python
if not HAS_REDIS_CLUSTER and _get_options()['cluster_mode']:
        return (False, "Please install the redis-py-cluster package.")
```
with KeyError

the reason is at salt/returners/__init__.py::_options_browser
```
 # default place for the option in the config
 value = _fetch_option(cfg, ret_config, virtualname, options[option])

    if value:
        yield option, value
        continue
```

the configuration will be ignored if the configure value is like as `False`, `0`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
what version of salt are you seeing this in?

**Comment by Mark3K** [comment]
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.2.1511 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

Megan Wilhite <notifications@github.com> 于2018年11月21日周三 下午11:05写道：

**Comment by Mark3K** [comment]
@Ch3LL 
https://github.com/saltstack/salt/blob/develop/salt/returners/__init__.py#L178
the code still here in develop branch
