### ISSUE TITLE
Document setuptools entry points

### ISSUE THREAD

**Issue by astronouth7303** [saltstack/salt#50594]
Salt supports adding directories to look for extmods in by querying setuptools entry points. However, this is not documented. This allows extensions for salt to be packaged and shipped via standard python packaging tools. However, you can only find this by looking at the source.

What I'm doing is:

```python
    entry_points={
        'salt.loader': [
            '{0}_dirs=spirofs.loader:{0}'.format(tag)
            for tag in (
                'auth', 'beacons', 'cache', 'engines', 'executor', 'fileserver',
                'grains', 'log_handlers', 'module', 'pillar', 'render',
                'returner', 'runner', 'serializers', 'tokens', 'top', 'utils',
                'wheel',
            )
        ],
    },
```

**Comment by Ch3LL** [comment]
sounds like a great addition :)

**Comment by astronouth7303** [comment]
I'm actually not sure where this should live in the documentation. I thought there was a list of extmods somewhere?

Maybe there just needs to be a page outlining what extmods there are and what they do, with links to further information when available.

**Comment by astronouth7303** [comment]
Finally found the files.
