### ISSUE TITLE
Bash autocompletion results in non-responsive master

### ISSUE THREAD

**Issue by davideagen** [saltstack/salt#50608]
### Description of Issue/Question

The bash autocomplete support in 2018.3.3 results in a non-responsive master as it appears to try and discover all possible commands that could be run. CPU and memory usage are high and attempts to run commands result in "master is not responding" errors.

Based on data in the returner it appears that the MoM is returning all exexcution modules from all minions:

> 
> < 2018-11-21 15:19:09.618 CST >< 127.0.0.1(54916) >< 5bf5cbcd.5224 > STATEMENT:  INSERT INTO jids
>                        (jid, load)
>                         VALUES ('20181121140041990610', '{"fun_args": null, "jid": "20181121140041990610", "return": ["acl.delfacl", "acl.getfacl", "acl.modfacl", "acl.version", "acl.wipefacls", "aliases.get_target", "aliases.has_target", "aliases.list_aliases", "aliases.rm_alias", "aliases.set_target", "alternatives.auto", "alternatives.check_exists", "alternatives.check_installed", "alternatives.display", "alternatives.install",...

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Master of masters and 3 syndics controlling ~2500 minions.

### Steps to Reproduce Issue
Type 'salt <selector>' and then hit TAB.

### Versions Report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.26.3
        libnacl: 1.6.1
       M2Crypto: 0.28.2
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, May 31 2018, 09:41:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo

**Comment by dwoz** [comment]
@davideagen Thank you for reporting this issue. I am un-able to reproduce it using our default bash completion script. Can you provide us the output from the following command?

`complete -p salt`

Thanks

**Comment by davideagen** [comment]
It turns out we were mistaken. Something else is overwhelming the master. Closing this issue as invalid.
