### ISSUE TITLE
Only one master can reach a minion at a time in multi-master setup

### ISSUE THREAD

**Issue by jinm** [saltstack/salt#50606]
### Description of Issue/Question
2017.7.7 for both masters and minions. Two masters with same master key pair and NOT sharing /etc/salt/pki/master/minions. Both masters are configured to auto-accept minions.

When failing over to secondary master, minions and secondary master behave as expected. However, when the primary master is back, primary master cannot reach minions. Both masters have minion1 public key at /etc/salt/pki/master/minions/minion1 with same checksum.

I could be wrong, but per "tcpdump host master1", master1 can ping minion1 but test.ping did not generate any packets from master1 to minion1. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Minion:
master:
  - master1
  - master2

master_type: failover
master_falilback: True
master_alive_interval: 15
retry_dns: 0

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
1. Have both masters running
2. test ping from master1
3. fail salt-master service from master1
4. test ping from master2: result should be True after timeout.
5. start salt-master service on master1
6. test ping from master1: Minion did not return

master1# salt -l all minion1 test.ping                                                                                                                                                            
[DEBUG   ] Reading configuration from /etc/salt/master                                                                                                                                                                                       
[DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'                                                                                                                                                                 
[DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf                                                                                                                                                                     
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master1                                                                                                                                             
[DEBUG   ] Missing configuration file: /root/.saltrc                                                                                                                                                                                         
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.                                                                                     
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.                                                
[DEBUG   ] Configuration file path: /etc/salt/master                                                                                                                                                                                         
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.                                                                                                                                                            
[DEBUG   ] Reading configuration from /etc/salt/master                                                                                                                                                                                       
[DEBUG   ] Including configuration from '/etc/salt/master.d/master.conf'                                                                                                                                                                 
[DEBUG   ] Reading configuration from /etc/salt/master.d/master.conf                                                                                                                                                                     
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: master1                                                                                                                                             
[DEBUG   ] Missing configuration file: /root/.saltrc                                                                                                                                                                                         
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc                                                                                                                                                             
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc                                                                                                                                                           
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'master1', 'tcp://127.0.0.1:4506', 'clear')                                                                               
[TRACE   ] Inserted key into loop_instance_map id 48423640 for key ('/etc/salt/pki/master', 'master1', 'tcp://127.0.0.1:4506', 'clear') and process 168671                                               
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc                                                                                                                                                    
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pub.ipc                                                                                                                                                        
[TRACE   ] func get_cli_event_returns()                                                                                                                                                                                                      
[DEBUG   ] LazyLoaded local_cache.get_load                                                                                                                                                                                                   
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/23/984e711966db367e2a66a7e34382ab6b7bcb1e21016c7d23e6a29d279b9400/.minions.p                                                                                                 
[DEBUG   ] get_iter_returns for jid 20181121095551823847 sent to set(['minion1']) will timeout at 09:55:54.842474                                                                                               
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] get_event() received = {'tag': 'salt/job/20181121095551823847/new', 'data': {'tgt_type': 'glob', 'jid': '20181121095551823847', 'tgt': 'minion1', '_stamp': '2018-11-21T14:55:51.825895', 'user': 'ro
ot', 'arg': [], 'fun': 'test.ping', 'minions': ['minion1']}}                                                                                                                                                    
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[TRACE   ] _get_event() waited 0 seconds and received nothing                                                                                                                                                                                
[DEBUG   ] Checking whether jid 20181121095551823847 is still running                                                                                                 
### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by Ch3LL** [comment]
looks like there is typo in your configuration:

`master_falilback: True`

should be `master_failback: True`

**Comment by jinm** [comment]
Thanks for catching that.

But default value for master_failback is false. Does it mean that recovered master will not be able to reach minion?

Thank you.

Jin.

**Comment by Ch3LL** [comment]
yes `master_failback` is false by design. When using the failover multi-master setup it is by design for the minion to only be attached to one master at a time. The only time it would fail back to master one when `master_failback` is not set is when the second master is not able to be reached. You can also look at the standard multi-master architecture. You will be able to run commands against your minion from both masters
