### ISSUE TITLE
Jinja unicode representation of nested string

### ISSUE THREAD

**Issue by mruepp** [saltstack/salt#50618]
### Description of Issue/Question
We have following yaml:
```
options:     
  default-ulimits:
    nofile:
      Soft: 2048
      Hard: 2048
```

And a template file which looks like this:
```
{%- from "docker/map.jinja" import host with context -%}
{%- for k, v in host.get('options', {}).iteritems() -%}

  {%- if v is string %}
    "{{ k }}": "{{ v }}"{%- if not loop.last %},{% endif %}

  {%- elif v is mapping %}
  {%- }
    "{{ k }}": {
      {%- for ki, kv in v.iteritems() %}
      "{{ ki }}": "{{ kv }}"{%- if not loop.last %},{% endif %}
      {%- endfor %}
    }{%- if not loop.last %},{% endif %}

  {%- elif v is iterable %}
    "{{ k }}": [
    {%- for i in v %}
      "{{ i }}"{% if not loop.last %},{% endif %}
    {%- endfor %}
    ]{%- if not loop.last %},{% endif %}

  {%- elif v in [True, False] %}
    "{{ k }}": {{ v|lower }}{%- if not loop.last %},{% endif %}

  {%- endif -%}

{%- endfor **%}
```

**
The rendered output file looks like this:

```
    "default-ulimits": {
      "nofile": "{u'Hard': 2048, u'Soft': 2048}"
    }
```
```
Expected would be a proper formatted json:
    "default-ulimits": {
      "nofile": {"Hard": 2048, "Soft": 2048}
    }
```

The docker daemon can not parse the unicode strings.
Funny though, the not nested dict (first level) parses the strings ok

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by max-arnold** [comment]
This Jinja logic is too complex and very hard to understand.  If you want to translate your YAML map to a JSON config file, there is a much simpler way to do it:

```
{% import_yaml "docker/docker.yaml" as docker -%}
{{ docker['options'] | tojson(indent=True) }}
```

The result:

```
{
 "default-ulimits": {
  "nofile": {
   "Hard": 2048,
   "Soft": 2048
  }
 }
```

**Comment by mruepp** [comment]
I do not get the filter working:
`SaltRenderError: Jinja syntax error: no filter named 'tojson'; line 2`

**Comment by max-arnold** [comment]
@mruepp You need Salt 2018.3.3 for this to work https://docs.saltstack.com/en/latest/topics/jinja/index.html#tojson

For older versions try `json_decode_dict` or `json_encode_dict` (whatever will work).

**Comment by mruepp** [comment]
Thanks, will close issue
