### ISSUE TITLE
Timeout for LocalClient.cmd

### ISSUE THREAD

**Issue by furgerf** [saltstack/salt#50612]
### Description of Issue/Question
Hi, I'm trying to retrieve the contents of a directory from a set of minions using a python script. Specifically, I run:
```python
local_client.cmd(minion_id, "cp.push_dir", ["path-on-minion"], timeout=<timeout>, kwarg={"upload_path": "<path-on-master>"})
```
However, I'm confused about the `timeout`, because the jobs sometimes terminate quickly (as expected) and sometimes, they terminate after the timeout I've specified in `/etc/salt/master` (not all minions are always connected).

This is from the [documentation of the LocalClient](https://docs.saltstack.com/en/latest/ref/clients/#localclient):
> The cmd method will execute and wait for the timeout period for all minions to reply, then it will return all minion data at once.

Then, specific about the parameter: 
> timeout -- Seconds to wait after the last minion returns but before all minions return.

I don't quite understand what this last part means - shouldn't the command return after the last minion returns? And what's the difference between when the "last minion" returns and when "all minions" return?

To sum up, I'd expect the command to return - no matter what - after a specified time. Is the `timeout` supposed to do that? If not, how do I achieve that?

Thanks in advance!

### Versions Report
```
Salt Version:
           Salt: 2017.7.8 <--- From the python script, I'm using salt==2018.3.3 installed from pip in a virtualenv

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 13 2018, 12:45:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.19.0-80-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by dwoz** [comment]
@furgerf Good question, I was just looking at the code for the `cmd` function and `get_iter_returns` in `salt.client.LocalClient`. It looks like the `timeout` will happen when there is no response from any minion within the specified amount of time. If we get a response from a minion, we reset the timer and keep waiting. So, `timeout` is not a global timeout for the command.

It looks like you could implement a global timeout yourself by running the command with `cmd_async` and then retrieving the results with `get_event_iter_returns`.

**Comment by furgerf** [comment]
Thanks for your response @dwoz, that's clear now.

I think my question was two-fold: First, how I should interpret the documentation regarding the timeout, and second, why does it seem like my custom timeout is ignored and the globally-configured timeout is used instead. I'm sorry, I wasn't very clear.

You've encouraged me to play around a bit and I'm afraid the second part is rather uninteresting: `timout=timeout` is not supposed to work, I guess... I'm surprised at the lack of error regarding the invalid kwarg, though.
