### ISSUE TITLE
file.directory on Windows creates in lowercase

### ISSUE THREAD

**Issue by dan-rus** [saltstack/salt#50610]
Hey,

Following https://github.com/saltstack/salt/pull/49167, when I set a file.directory state, the directory is created in lowercase and not the case I have specified.  Windows is case insensitive so it is not breaking applications, but it would be nice to have my case kept.

To replicate
------------
abcdef:
  file.directory:
    - name: C:\AbcDef\GhIJ
    - makedirs: True

What happens
----------------
C:\abcdef\ghij folder is created

What is desired
------------------
C:\AbcDef\GhIJ is created

I am running 2018.3.3 masterless salt minion with the following versions:

C:\salt>salt-call --versions
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free

**Comment by dwoz** [comment]
@dan-rus Thanks for pointing this out. I agree it would be nice to preserve the case specified by the state.

**Comment by dhs-rec** [comment]
@dwoz, no it should NOT just "be nice". It's the same as #45409. If the user specifies a path in whatever casing, she might do this for a reason. It's not Salt's task to question this and change the casing at will. That's a bug which should be fixed ASAP, NOT a feature.

**Comment by dhs-rec** [comment]
Any news on this? It's still annoying. And can it be changed to a bug, please?

**Comment by pintu-gupta** [comment]
I am also facing this issue with file.managed on Windows. Do we have an update on this issue when will it be fixed?

**Comment by cprior** [comment]
+1 from me. Camelcase exists for a reason, and file.managed should not change input data.

**Comment by mccaslin** [comment]
+1 for preserving case.  I think this issue is causing file.recurse to delete portions of a CAD configuration that we use saltstack to manage on Windows clients.  We don't prepare the configuration, so we can't stop the input from being mixed case.

**Comment by dhs-rec** [comment]
Reopening. Now can this be finalised, please? It's still a no-go.

**Comment by piterpunk** [comment]
@twangboy , your change in 64f45f8650fb30a4938c4e261124524f35c47cbb didn't also fix this bug?

**Comment by sagetherage** [comment]
@twangboy doesn't think the above commit has fixed this, so re-opening it

**Comment by dhs-rec** [comment]
@sagetherage, please remove the "severity-low" label again. This is annoying us since years now and it's still a NO-GO. A provisioning tool should NOT, in any way, change at will what it was told to do!

**Comment by sagetherage** [comment]
not sure that removing the label helps - but I can add a higher severity

**Comment by mccaslin** [comment]
I don't know if it helps or not, but I can tell you this issue has been a deal breaker for us as far as using Saltstack to manage windows machines because of the interaction with file.recurse that causes it to delete files we are attempting to manage from the clients.  A configuration manager that wipes managed folders on the managed machines is not usable. This bug should get more attention.

**Comment by xeacott** [comment]
Hey @dhs-rec is this the desired output?

```
win_box:
----------
          ID: abcdef
    Function: file.directory
        Name: C:\AbcDef\GhIJ
      Result: True
     Comment:
     Started: 16:45:26.493141
    Duration: 62.483 ms
     Changes:
              ----------
              C:\AbcDef\GhIJ:
                  ----------
                  directory:
                      new

Summary for win_box
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  62.483 ms
[DEBUG   ] jid 20210616224524053150 found all minions {'win_box'}
[DEBUG   ] Closing IPCMessageSubscriber instance

C:\dev\salt (win_patch_func -> origin)
λ
```
<img width="802" alt="camelcase1" src="https://user-images.githubusercontent.com/31625359/122304510-942ebb80-cec2-11eb-84f2-849ead20d4b1.PNG">
<img width="775" alt="camelcase2" src="https://user-images.githubusercontent.com/31625359/122304511-955fe880-cec2-11eb-82ea-678025cd5cf9.PNG">

**Comment by dhs-rec** [comment]
@xeacott, if `C:\AbcDef\GhIJ` matches what's defined in `abcdef` in a *.sls file, then yes, that's how it should be. ;-)

**Comment by xeacott** [comment]
Yep, this was the state I ran no modifications from when OP posted it:

abcdef:
  file.directory:
    - name: C:\AbcDef\GhIJ
    - makedirs: True

**Comment by xeacott** [comment]
Closing this ticket. Should be fixed in master. Please re-open if this continues to be an issue
