### ISSUE TITLE
Traction/Acknowledge of 49147

### ISSUE THREAD

**Issue by rochen-joshua** [saltstack/salt#50629]
Hello all,

I know your busy but can we get some traction or acknowledgment of issue 49147?

This is affecting several production minions for myself and others but does not affect an entire deployment for anyone I've' spoken to yet. Much appreciated! I'm only double posting because it looks like it was written off before, but now several new people are seeing the issue.

**Comment by Ch3LL** [comment]
i changed the severity of the issue and pinged the developer that is assigned. will close here as we are tracking in the other issue.

**Comment by rochen-joshua** [comment]
@Ch3LL any chance you could push for another update on that thread? It's been well over a month and close to 2 now since we've had any real progress, and it's affecting a lot larger base of people now.

**Comment by Ch3LL** [comment]
i pinged the engineer. if he can't get to it we will try to get it assigned to someone else :) thanks
