### ISSUE TITLE
Q: Case-insensitive dictionary implementation

### ISSUE THREAD

**Issue by tonybaloney** [saltstack/salt#50644]
### Case-insensitive dictionary implementation

I'm working on #50321 and it's become apparent that the state comparison check between a 3rd party libraries' return value and the state has case-sensitive keys.

Just thinking it would be worthwhile for a case-insensitive dictionary implementation to be added to `salt.utils`, similar to the one requests uses.
https://github.com/requests/requests/blob/master/requests/structures.py#L13-L84 

Any thoughts on this? Has it been discussed before?

**Comment by garethgreenaway** [comment]
Seems like a good idea.
@saltstack/team-core Thoughts?
