### ISSUE TITLE
win_firewall.delete_rule works from CLI but not SLS file.

### ISSUE THREAD

**Issue by mikesoule** [saltstack/salt#50658]
### Description of Issue/Question

The following works from a terminal...
```
salt 'winhost' win_firewall.delete_rule Foo
```

but the equivalent state in a SLS file does not work.
```
remove-firewall-rule:
  win_firewall.delete_rule:
    - name: Foo
```

The following error is returned:
_**
State 'win_firewall.delete_rule' was not found in SLS 'winhost.sls'
Reason: 'win_firewall.delete_rule' is not available.
**_

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Salt Master v2018.3.3 on CentOS 7
Minion v2.24.103.0 on Windows Server 2012 R2

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Attempt to use state `win_firewall.delete_rule` from SLS file.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

**Comment by teizz** [comment]
Hi Mike,

The state modules don't always reflect the execution modules exactly. I suppose it doesn't always make sense to mirror the exact functionality in a confituration management state that you'd want to use in a remote execution module. Though in this case it doesn't seem unfair to expect there to be a ``win_firewall.delete_rule``  in the state module, just like there is in the execution module.

If nobody beats me to it I'll see if I can make a PR to have that added to the state module :smiley: 

FWIW, the docs:
Remote execution module: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_firewall.html
vs
State module: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.win_firewall.html

**Comment by mikesoule** [comment]
@teizz Thank you for the explanation, that didn't even occur to me. But yes, the ability to have more control over the firewall via states would be very useful.

**Comment by dwoz** [comment]
@mikesoule If you don't want to use `cmd.run` you can also run the module function like this.
```
remove-firewall-rule:
  module.run:
    - name: win_firewall.delete_rule
    - name: MyRule
```
