### ISSUE TITLE
salt client will return lots of reply such as 'Minion did not return. [No response]'

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#50697]
### Description of Issue/Question
I got  lots of returns such as 'Minion did not return. [No response]' when I opened 5 salt client or more, and execute the cmd "salt '*' test.ping" at the same time.
But it's ok when I just opened one salt client and execute the cmd.

### Setup
My primary salt master config:
max_open_files: 65535
worker_threads: 30
pub_hwm: 10000
salt_event_pub_hwm: 128000
event_publisher_pub_hwm: 64000
ret_port: 8006

My primary salt minion config:
recon_default: 1000
recon_max: 59000
recon_randomize: True
random_reauth_delay: 60
tcp_pub_port: 8010
tcp_pull_port: 8011
master_port: 8006

And there're 2000 minions in the master.

### Steps to Reproduce Issue
Open many salt clients and execute test.ping at the same time.

### Versions Report
my salt version is:  salt-master 2017.7.8 (Nitrogen)

**Comment by andyyumiao** [comment]
how can we execute salt cmd concurrently and without lots of 'Minion did not return. [No response]'?

**Comment by dwoz** [comment]
@andyyumiao You can use the `--timeout` option to increase the amount of time the salt client will wait for responses. The `--timeout` option defaults to `5` seconds.

**Comment by andyyumiao** [comment]
> @andyyumiao You can use the `--timeout` option to increase the amount of time the salt client will wait for responses. The `--timeout` option defaults to `5` seconds.

Thanks your reply @dwoz , and this can solve the problem. 
But i am curious why a timeout occurs when executing concurrently. I know salt uses zmq for communication, so it should be asynchronous and 
commands should be executed in parallel, isn't that the case?

**Comment by arizvisa** [comment]
@andyyumiao, you can run the job asynchronously with --async and just lookup the jid to ensure that everything is done.
