### ISSUE TITLE
How to customize the salt minions for windows

### ISSUE THREAD

**Issue by Prakashhh23** [saltstack/salt#50698]
Description of Issue/Question

Can you please explain the way to customize the salt minion rather than communicating with master only ?
Queries:
1.Where I can find the salt minion source code ?
2.What is the procedure to customize ? - step by step process to do the changes in order to work properly

**Comment by dwoz** [comment]
The salt minion is designed to work by `communicating with a master`. You can also run salt in `masterless` mode. You can find documentation on masterless minions at:

https://docs.saltstack.com/en/latest/topics/tutorials/quickstart.html
https://docs.saltstack.com/en/latest/topics/tutorials/standalone_minion.html

When the minion has been installed via the Windows installer the source code will be found in `c:\salt\bin\lib\site-packages\salt`.

If you really want to *customize* salt, I suggest creating a development environment. Using a development environment will allow you to run the tests to verify you changes work properly. Documentation about development environments can be found at:

https://docs.saltstack.com/en/latest/topics/development/hacking.html

**Comment by Prakashhh23** [comment]
@dwoz : Appreciate your response. We have reviewed the minion's source code from the path "c:\salt\bin\lib\site-packages\salt, actually  we are trying to develop a API/REST API for Salt-Minion to communicate with other third party APIs. In the mentioned path we are seeing so many python files and not sure which one is right source code for minion, same case for master we clone the source code form the github.
We need your guidance on how to establish a API connection with minion.

**Comment by twangboy** [comment]
https://docs.saltstack.com/en/latest/ref/clients/index.html
https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html
https://docs.saltstack.com/en/latest/ref/cli/salt-api.html

And this may be helpful
https://medium.com/@pavithra_38952/understanding-the-salt-api-2dfb5dbb9394
