### ISSUE TITLE
Delete salt key that got a coma in it eg: key is "LoadTest-API-04,LoadTest-API-03"

### ISSUE THREAD

**Issue by amitht** [saltstack/salt#50712]
Delete salt key that got a coma in it eg: key is "LoadTest-API-04,LoadTest-API-03"

I am not able to delete the saltkey since the key got a coma in it. 
Please let me know how to delete it. 

Thanks,
Amith

**Comment by Ch3LL** [comment]
`salt-key -d LoadTest-API-04*LoadTest-API-03` does that work?

**Comment by teizz** [comment]
Chucking it straight from the pki dir on the master. should do the trick as well: )
