### ISSUE TITLE
State 'logrotate' in SLS 'logrotate' is not formed as a list

### ISSUE THREAD

**Issue by suneeta1** [saltstack/salt#50721]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@suneeta1 Can you please provide the output from `salt --versions-report` so we know what version of Salt you're reporting this error against.  Also please provide the state that you're attempting to use the `logrotate` state module in.  Thanks!
