### ISSUE TITLE
 Data failed to compile: ----------     State 'logrotate' in SLS 'logrotate' is not formed as a list

### ISSUE THREAD

**Issue by suneeta1** [saltstack/salt#50720]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by suneeta1** [comment]
salt 2017.7.4 (Nitrogen)

**Comment by garethgreenaway** [comment]
@suneeta1 Thanks for the report.  Can you also provide the state file that you're attempting to use the logrotate state module in?  Thanks!
