### ISSUE TITLE
grains.disks returns nothing for Windows servers

### ISSUE THREAD

**Issue by josephsutton** [saltstack/salt#50726]
### Description of Issue/Question
Windows Minions do not return disks grains.
### Setup
Salt master 2018.3.3 (rhel7) 
minions - 2008r2 salt-minion 2018.3.0 py27
              - 2012r2 salt-minion 2018.3.2 py27
              - 2016 salt-minion 2018.3.0 py27
              - 2016 salt-minion 2018.3.3 py3
### Steps to Reproduce Issue
salt 'os:windows' grains.get disks
salt 'os:windows' grains.items

return no disks.

salt 'os:windows' disks.usage - returns disk usage as expected.

### Versions Report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.9
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.21.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by josephsutton** [comment]
I realized forgot to add this is only happening to minion VMs (vmware esxi 6.5 but varying levels of VMtools).  This is not happening with physical minions.

**Comment by garethgreenaway** [comment]
@josephsutton Thanks for the report.

**Comment by gposton** [comment]
I'm having the same issue on Amazon Linux.
