### ISSUE TITLE
flask can't run with importing SaltStack client API

### ISSUE THREAD

**Issue by ripkop** [saltstack/salt#50723]
### Description of Issue/Question
In my Salt Master machine, I want to provide flask rest API to call salt client, but when I import salt.client, flask can't run.

### Steps to Reproduce Issue
for example very simple following code won't run on my machine.
```python
app = Flask(__name__)
api = flask_restful.Api()
import salt.client
client = salt.client.get_local_client()
class Test(flask_restful.Resource):
    def get(self):
        return {"what": "ever"}
api.add_resource(Test,"/")
api.init_app(app)
if __name__ == "__main__":
    app.run(debug=True)
```

### Versions Report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.6 (default, Sep 12 2018, 18:26:19)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-39-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by garethgreenaway** [comment]
@ripkop Thanks for the report.  Can you provide any error messages or logs you receive when attempting to run flask?

**Comment by ripkop** [comment]
I think I found the problem is with logging, and when I run the above code, somehow salt.client prevent flask and werkzeug from logging, the server is up now, but no logging, I followed this [issue](https://github.com/saltstack/salt/issues/4994) but it doesn't help
