### ISSUE TITLE
salt.saltutil.runner('salt.execute'.. does not take args correctly

### ISSUE THREAD

**Issue by mruepp** [saltstack/salt#50730]
### Description of Issue/Question

When using the following runner state in orchestrate, the arguments are not working as expected:
(node is jinja variable and represents a minion id)

```
{% set restart = salt.saltutil.runner('salt.execute', node, 'cmd.retcode', "['needs-restarting']") %}

Rendering SLS 'mr/orchlifecycle:orchestrate.lifecycle' failed: Problem running salt function in Jinja template: arg must be formatted as a list/tuple; line 28

{% set restart = salt.saltutil.runner('salt.execute', node, 'cmd.retcode', arg="['needs-restarting']") %}
{% set restart = salt.saltutil.runner('salt.execute', node, 'cmd.retcode', arg='("needs-restarting",)') %}

File "<template>", line 28, in top-level template code
TypeError: runner() got multiple values for keyword argument 'arg'

{% set restart = salt.saltutil.runner('salt.execute', node, 'test.ping') %}

Rendering SLS 'mr/orchlifecycle:orchestrate.lifecycle' failed: Problem running salt function in Jinja template: arg must be formatted as a list/tuple; line 28

 {% set restart = salt.saltutil.runner('salt.execute', node, 'cmd.retcode', "('needs-restarting',)") %}
{% set restart = salt.saltutil.runner('salt.execute', node, 'cmd.retcode', ('needs-restarting',)) %}

```

### Versions Report
Master/Minions:
2018.3.3

**Comment by mruepp** [comment]
Thanks for the hint, the runner works, but I get this ret:
`{u'salt.dev.sc.intra': u'ERROR: The shell s is not available'}`

On Slack @gtmanfred suggested, that I use:
`{% set reboot = salt.saltutil.cmd(tgt=node, fun='cmd.retcode', arg=['needs-restarting -r']) %}`
Which will get me the proper ret. dict:
`{u'salt.dev.sc.intra': {u'jid': u'20181205090137196241', u'retcode': 1, u'ret': 1}}`

**Comment by Ch3LL** [comment]
glad you got help. Are you okay to close here?

**Comment by mruepp** [comment]
Thanks alot, funny though that the command gets no shell. I will close this
