### ISSUE TITLE
Compound command execution in scheduled jobs

### ISSUE THREAD

**Issue by Naitreey** [saltstack/salt#50754]
### Description of Issue/Question
Does Salt's scheduled job system support compound command execution like do `salt` command?

For example, given the following salt invocation:

```sh
sudo salt '*' cmd.run,status.time date,
```

Is there an equivalent to be used in scheduled job? I tried the following without luck.

```sh
salt '*' schedule.add test_compound function='["cmd.run", "status.time"]' job_args='[["date"],[]]' seconds=5
```

The minion log complains:

```
Dec 05 09:59:59 <id> salt-minion[4709]: [ERROR   ] Exception unhashable type: 'list' occurred in scheduled job
```

**Comment by dwoz** [comment]
@garethgreenaway Do you know if this is possible?

**Comment by garethgreenaway** [comment]
@dwoz it seems like not. :smile: I honestly didn't know this existed. Should be fairly straightforward to support though.

**Comment by garethgreenaway** [comment]
Available in the develop branch and will be available in the NEON release.  Closing this out, if the problem persists we can reopen this issue.
