### ISSUE TITLE
Windows 2019 grains for osrelease are incorrect

### ISSUE THREAD

**Issue by infantvin** [saltstack/salt#50758]
### Issue description
On the recently released version of Microsoft Windows Server 2019 it is seen that the grains for osrelease are not correctly being reported. Please confirm if this is a saltstack related issue or if we are doing something incorrectly at minion end.

Below is a sample snippet of a Win 2019 Std host where we are seeing the information being incorrect in the grains

 os:
        Windows
    os_family:
        Windows
    osfinger:
        Windows-2016Server
    osfullname:
        Microsoft Windows Server 2019 Standard
    osmanufacturer:
        Microsoft Corporation
    osrelease:
        2016Server
    osrelease_info:
        - 2016
    osservicepack:
        None
    osversion:
        10.0.17763

### Steps to Reproduce Issue

Install Windows 2019 on a host followed by salt-minion of any version. Tested the minion versions 2016.11.8 and 2018.3.3 (both Python2 and 3 versions). 

Connect to a salt-master and run

salt minion-name grains.items. Listing will be as reported above.

### Versions Report
MASTER:
salt --versions-report
Salt Version:
           Salt: 2016.11.8

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.24.6
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
        machine: x86_64
        release: 3.10.0-693.17.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

MINION:

    Salt Version:
               Salt: 2018.3.3

    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.3 (v3.5.3:1880cb95a742, Jan 16 2017, 16:02:32) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2016Server
             system: Windows
            version: 2016Server 10.0.17763 SP0 Multiprocessor Free

**Comment by infantvin** [comment]
Hi,
Thank you for working on this.
Can you please confirm if this fix is rolled out to the salt-minion/master packages available on the saltstack website?

I just updated a system and a test master to 2018.3.3 and still see the grains reporting the version as 2016 server for Win 2019.

If I need to wait or correct something from my side, please let me know.

**Comment by twangboy** [comment]
@infantvin It will be in the next release, 2018.3.4 and Fluorine.
