### ISSUE TITLE
cloud salt-minion build as a stand-alone executables?

### ISSUE THREAD

**Issue by wubumihuo** [saltstack/salt#50751]
### Description of Issue/Question
we want to deploy salt-minion to hosts on our company, more than 20000 of centos(redhat) 6,7。But we don't want to make any effect to the host. We would like to build a linux executable salt-minion like windows salt-minion that all the dependcies are in my own folder 。Is there any solution like pyinstaller can solve it? Thanks!

**Comment by dwoz** [comment]
@wubumihuo pyinstaller would probably work but might be a challenging for C based dependencies. My recommendation would be to use a virtual environment. You might be able to tar up salt and it's virtual environment and extract it for a simple install. Then you'll just need to configure the minion ID and make sure the minions keys are refreshed.
