### ISSUE TITLE
Question about asynchronous nature of the Reactor

### ISSUE THREAD

**Issue by crux-capacitor** [saltstack/salt#50775]
### Description of Issue/Question

I'm hoping to get some clarification on the asynchronous nature of the reactor.

If I have a reactor start a long-running orchestration job, does that reactor thread wait for the job it created to finish before returning back to the thread pool, or does it immediately go back after the job starts? 

I want to make sure that the threads do not wait for the job to finish. Do I need to set 'async: True' in the reactor SLS to accomplish this, or does it do that by default?

-------------------------------------------------------------------------------

Example Reactor SLS:

Are these 2 reactors functionally equivalent? If not, what is accomplished by setting 'async: True'?

```
"Long Orchestration - Async True":
  runner.state.orchestrate:
    - args:
      - mods: orchestrate.job
      - pillar:
          id: {{ node }}
    -  async: True
```

```
"Long Orchestration":
  runner.state.orchestrate:
    - args:
      - mods: orchestrate.job
      - pillar:
          id: {{ node }}
```

A couple follow up questions:

1. Should 'async: True' be under the args dictionary?
2. If I have 2 reactors defined under one event tag, will that use 2 threads, or just 1 to handle both reactors?

**Comment by Ch3LL** [comment]
i'm not certain on how to answer these questions. Can anyone from @saltstack/team-core answer @crux-capacitor 's questions

I did find this other issue https://github.com/saltstack/salt/issues/46431#issuecomment-406449840 that mentions `reactor_worker_hwm` when handling long running jobs with the reactor

**Comment by DmitryKuzmenko** [comment]
Looked up the code. 
1. I don't see async argument anywhere in the reactor pipeline. So both declarations are equal.
2. Reactor uses a pool of `threading.Thread` objects to run runner and wheel modules that is your case. Both reactions will be run in different threads simultaneously. The number of threads is set from the number of hardware threads by default that could be overridden with `reactor_worker_threads` configuration option. Also the mentioned `reactor_worker_hwm` is setting the size of the queue that is the maximum number of items (reactions) could be put into the queue without blocking. It's 10K by default.

@crux-capacitor welcome for any questions.
@saltstack/team-core please correct me if I'm wrong anywhere.

**Comment by crux-capacitor** [comment]
@DmitryKuzmenko Thanks for your responses!

So to clarify, setting async: True really accomplishes nothing?

Also, I'm still unclear on the answer to my main question:

> If I have a reactor start a long-running orchestration job, does that reactor thread wait for the job it created to finish before returning back to the thread pool, or does it immediately go back after the job starts?

Does the reactor wait for the job it created to finish, or is it truly asynchronous?

**Comment by DmitryKuzmenko** [comment]
> So to clarify, setting async: True really accomplishes nothing?

Yes.

> Does the reactor wait for the job it created to finish, or is it truly asynchronous?

Each thread runs jobs synchronously.

**Comment by crux-capacitor** [comment]
@DmitryKuzmenko 

Thanks. Last question - is there a way to make the thread immediately return to the thread pool after it starts the job? So that it does not wait for the job to complete?

**Comment by ReubenM** [comment]
From the [docs](https://docs.saltstack.com/en/latest/topics/reactor/#best-practices-for-writing-reactor-sls-files)

> Matching and rendering Reactor SLS files is done sequentially in a single process. For that reason, reactor SLS files should contain few individual reactions (one, if at all possible). Also, keep in mind that reactions are fired asynchronously (with the exception of caller) and do not support requisites.
> 
> Complex Jinja templating that calls out to slow remote-execution or runner functions slows down the rendering and causes other reactions to pile up behind the current one. The worker pool is designed to handle complex and long-running processes like orchestration jobs.
> 
> Therefore, when complex tasks are in order, orchestration is a natural fit. Orchestration SLS files can be more complex, and use requisites. Performing a complex task using orchestration lets the Reactor system fire off the orchestration job and proceed with processing other reactions.

**Comment by DmitryKuzmenko** [comment]
@Ch3LL could you please forward the last question to somebody closer to support, I don't see an answer by a quick look to the code, sorry.

**Comment by crux-capacitor** [comment]
@ReubenM Yes, I've read those docs as well but after some conversations with some people in the Salt IRC channel, I found out that the reactor isn't truly asynchronous as the docs lead you to believe. That last sentence in particular is what my question is really about. Based on that, it sounds as if the reactor fires the job and immediately goes back into the reactor thread pool to handle more reactions, without waiting for the job it fired to complete. But as @DmitryKuzmenko confirmed, thats not really the case (unless I'm misunderstanding?).

@DmitryKuzmenko Now I'm starting to wonder if I am misunderstanding. As an example, I have the reactor running orchestration jobs that highstate my minions. The highstates can take around 10 minutes to run. Does that mean that the reactor thread will wait and be occupied for 10 minutes until that orchestration job returns? Is that what you mean by "synchronously"?

**Comment by ReubenM** [comment]
@crux-capacitor That's the impression I get from that doc snippet. If that is not correct, I would assume that would have serious scalability implications. If it turns out that the reactor threads do block waiting on the runner, a follow up question would be "how does this effect thorium?" I haven't had reason to look into the code, but it could be possible that the thread of the reactor handler forks itself into a new processes and blocks inside the new process waiting for the runner to finish. In that case it would be both asynchronous and synchronous at the same time.

**Comment by DmitryKuzmenko** [comment]
@crux-capacitor the main reactor thread puts all the reaction chunks to job queue. Threads are reading the tasks one-by-one and execute them synchronously, i.e. each thread waits until the reaction chunk is done.
This is correct for `runner` and `wheel` reactions.
So yes you're right. If you'll have 20 jobs 10 minutes each and 10 threads, overall time would be about 20 minutes. Does it make sense?

**Comment by crux-capacitor** [comment]
@DmitryKuzmenko Yes, that makes sense. Thanks for clarifying.

I'm still wondering if there is a way to make the threads not wait, if there is a way at all.

**Comment by Ch3LL** [comment]
@crux-capacitor there is this issue with some possible workarounds for you: https://github.com/saltstack/salt/issues/39723

**Comment by DmitryKuzmenko** [comment]
@Ch3LL thank you! Just because I'm out of answers here. =)
@crux-capacitor for now we have moving forward to make more and more things in salt to be async. So if it's ok like a temporary solution to just find out the optimal thread count for your case and just wait some months, I think you'll see stuff you need.

**Comment by crux-capacitor** [comment]
@Ch3LL @DmitryKuzmenko Thanks to you both for the answers!

Would you agree that the documentation on this (namely the portion that ReubenM quoted) is misleading? Can that be updated with a summary of what we discussed here? I think that would be really beneficial for others who are trying to optimize their reactions.

**Comment by ReubenM** [comment]
Yes, from the docs I linked to, it led me to believe that the orchestration runners were called by the reactor handlers without waiting for the orchestration runner to return. I have a lot of long running orchestrations that are triggered by events, and in light of this I'll probably need to increase the pool size of threads for the reactor job queue.

**Comment by crux-capacitor** [comment]
Another thing. Should this:

> Complex Jinja templating that calls out to slow remote-execution or runner functions slows down the rendering and causes other reactions to pile up behind the current one. The worker pool is designed to handle complex and long-running processes like orchestration jobs.

actually be this?

> Complex Jinja templating that calls out to slow remote-execution or runner functions slows down the rendering and causes other reactions to pile up behind the current one. The worker pool is **_not_** designed to handle complex and long-running processes like orchestration jobs.
