### ISSUE TITLE
dist() and linux_distribution() functions are deprecated warning on python3.7.1

### ISSUE THREAD

**Issue by kk21986** [saltstack/salt#50792]
### Description of Issue/Question
Getting the below warning messages on salt 2018.3.3 with python3.7.1. Due to these warning messages the automation not behaving properly which uses salt. 

`/usr/local/tools/python371/lib/python3.7/site-packages/salt/version.py:632: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  lin_ver = linux_distribution()`

### Steps to Reproduce Issue
Compile python 3.7.1 on centos 6 and install salt using pip. Then run the salt --version-report where you can see the those warning message. 

### Versions Report
`# salt --versions-report
/usr/local/tools/python371/lib/python3.7/site-packages/salt/utils/immutabletypes.py:38: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class ImmutableList(collections.Sequence):
/usr/local/tools/python371/lib/python3.7/site-packages/salt/version.py:632: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  lin_ver = linux_distribution()
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.1 (default, Nov 23 2018, 02:59:05)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: redhat 6.9 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.39-400.296.2.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.9 Santiago
`

**Comment by garethgreenaway** [comment]
@kk21986 Thanks for the report.  The `collections` deprecation messages were taken care of in https://github.com/saltstack/salt/pull/49487 and we have logic in place to rely on the `distro` library when `platform` no longer has those functions, we just need to ensure `distro` is included with our packages.  Thanks!

**Comment by kk21986** [comment]
@garethgreenaway  Thanks. Today I have noticed the same error on loader as well. 

```
/usr/local/tools/python371/lib/python3.7/site-packages/salt/loader.py:765: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  ret = funcs[key]()
```

Is this related with the same one or do I have to open new issue for this?

**Comment by garethgreenaway** [comment]
@kk21986 Looks related.  Thanks for the update.

**Comment by kk21986** [comment]
Looks like fixed. Unfortunately the `dist` value is showing `Unknown` on Windows.
`System Versions:
           dist: Unknown OS Name Unknown OS Release Unknown OS Codename
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600 SP0 Multiprocessor Free`

**Comment by ikoruk** [comment]
I am still getting the warning on Mac OS Mojave with salt 2019.2.0.

**Comment by garethgreenaway** [comment]
Needs a backport but will also likely be fixed when we're able to start focusing on various fixes needed for Python 3.8.

**Comment by s0undt3ch** [comment]
FYI, I believe 3001 no longer throws any of these warnings.

**Comment by sagetherage** [comment]
Closing this as fix in v3001
