### ISSUE TITLE
[fluorine] multi-master failover minion stops when masters not available

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#50791]
### Description of Issue/Question
When a minion is configured to use multi-master failover and both masters are down for more then 5 minutes the minion will stop.

### Setup
/etc/salt/minion

```
master_type: failover
master_alive_interval: 10
master:
  - master1
  - master2
```

### Steps to Reproduce Issue
1. Start master1, master2 and minion
2. verify you can run a `test.ping` from master1

```
[root@master1 /]# salt '*' test.ping
minion1:
    True
[root@master1 /]# 
```

3. stop both masters `pkill salt-master`. kill master2 first then master1
4. wait a couple minutes and you will see the minion ends up stopping

```
[DEBUG   ] Trying to connect to: tcp://172.24.0.4:4506
[INFO    ] (u'Master %s could not be reached, trying next next master (if any)', u'master2')
[ERROR   ] No master could be reached or all masters denied the minion's connection attempt.
[ERROR   ] Error while bringing up minion for multi-master. Is master at [u'master1', u'master2'] responding?
[ERROR   ] Minion unable to successfully connect to a Salt Master.  Exiting.
[INFO    ] Stopping the Salt Minion
[ERROR   ] Minion unable to successfully connect to a Salt Master.  Exiting.
[INFO    ] Shutting down the Salt Minion
[DEBUG   ] Stopping the multiprocessing logging queue listener
[DEBUG   ] closing multiprocessing queue
[DEBUG   ] joining multiprocessing queue thread
[DEBUG   ] Stopped the multiprocessing logging queue listener
The Salt Minion is shutdown.
Minion unable to successfully connect to a Salt Master.  Exiting.
[root@minion1 /]# 
```

### Versions Report

```
Salt Version:
           Salt: 2018.11.0-2383-g0ffd1e5

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.4.1708 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.18.7-rt5-MANJARO
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by dwoz** [comment]
@DmitryKuzmenko This is likely related to #50854. This patch might resolve it #50855.

**Comment by DmitryKuzmenko** [comment]
@dwoz Yes, #50855 shall fix it. So here we just wait it to get merged.

**Comment by Ch3LL** [comment]
@dwoz i'm still seeing an issue with multi-master failover. Its the exact same steps as above but to note i could only replicate this on linux when running `salt-minion -d` instead of `salt-minion -ldebug`. What occurs is i see this in the log when the masters go down:

```
2019-01-09 21:58:32,033 [salt.minion                                            :662 ][ERROR   ][1162] No master could be reached or all masters denied the minion's connection attempt.
2019-01-09 21:58:32,033 [salt.scripts                                           :149 ][WARNING ][1162] Fatal functionality error caught by minion handler:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/scripts.py", line 146, in minion_process
    minion.start()
  File "/usr/lib/python3.4/site-packages/salt/cli/daemons.py", line 350, in start
    raise SaltClientError('Minion could not connect to Master')
salt.exceptions.SaltClientError: Minion could not connect to Master
2019-01-09 21:58:32,034 [salt.scripts                                           :150 ][WARNING ][1162] ** Restarting minion **
2019-01-09 21:58:32,034 [salt.scripts                                           :155 ][INFO    ][1162] waiting random_reauth_delay 2s
```

and the minion just dies.

**Comment by dwoz** [comment]
@Ch3LL Okay, I will look at it.

**Comment by damon-atkins** [comment]
The master down/retry connect seems complex.   Should only be a few settings
master_retry_attempts = 0  (0 for ever)
master_retry_time_delay_adjustment_percent =10
master_retry_time_between_attempts = 300  # With a bit of doco saying its +/- 10% random interval i.e. 270 to 330

These values should encompass dns resolution, tcp connection time out, etc.

For example DNS resolution should perform the normal lookup (which generally several attempts over few minutes) and if it fails to resolve wait master_retry_between_attempts before trying again.  No need for a separate config option for DNS.  So if DNS took 270 seconds to fail looking up the hostname, salt would try again in 30 seconds. i.e.  `master_retry_time_between_attempts - 270 = 30`
`30 + (master_retry_time_delay * (master_retry_time_delay_adjustment_percent  *  0.01))`

However I do think salt should store the last known IP address of the salt-master, for when DNS fails. Or a person push out a change using salt which effects DNS resolution on the minion.

Remove RETRY_DNS, RETRY_DNS_COUNT, MASTER_TRIES, AUTH_TRIES, TCP_AUTHENTICATION_RETRIES
Remove RANDOM_REAUTH_DELAY, RANDOM_STARTUP_DELAY
i.e. RANDOM_STARTUP_DELAY is `master_retry_time_between_attempts * master_retry_time_delay_adjustment_percent  *  0.01`

Then there are the RECON_* settings.
 
There are too many settings

The aim at the end of the day is not to have the minion spin cpu trying to connect, not to overload the master with connection attempts, not to have all minions connect at the same time (hence randomish).

Can this be simplified?

**Comment by sagetherage** [comment]
closing this ticket, but assigning @dwoz to the open ticket referenced here
