### ISSUE TITLE
get 'AttributeError: 'module' object has no attribute 'Stopwatch' when execute salt-master

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#50800]
### Description of Issue/Question
I get 'AttributeError: 'module' object has no attribute 'Stopwatch' , when I start salt-master.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt-master 2017.7.8 (Nitrogen)

**Comment by garethgreenaway** [comment]
@andyyumiao Thanks for the report.  Can you provide more information from `salt --versions-report` so we can see information what about system the Salt master is running, eg. operating system, versions of Python libraries, etc.

**Comment by andyyumiao** [comment]
> @andyyumiao Thanks for the report. Can you provide more information from `salt --versions-report` so we can see information what about system the Salt master is running, eg. operating system, versions of Python libraries, etc.

@garethgreenaway thanks for the reply, my config:
Salt Version:
           Salt: 2017.7.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 15 2016, 22:37:39)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.5
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.28.3.el7.x86_64
         system: Linux
