### ISSUE TITLE
Seems Salt minion always use powershell x86 version

### ISSUE THREAD

**Issue by chen-j-y** [saltstack/salt#50808]
### Setup
-

### Steps to Reproduce Issue
Hi, 
My Salt minion is installed on Windows(64 bit), with python2.7(32 bit). But it seems that I can only call the 32 bit version powershell. That raise some problems for I need use some modules registered in powershell 64 bit.

I googled that `C:\Windows\syswow64\WindowsPowerShell\v1.0\powershell.exe` is 32 bit version, and `C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe` is 64 bit version.

and I try some command on salt minion server.
```
C:\Users\Administrator>C:\Windows\syswow64\WindowsPowerShell\v1.0\powershell.exe
 [intPtr]::Size
4

C:\Users\Administrator>C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe
 [intPtr]::Size
8

C:\Users\Administrator>salt-call cmd.run "[intPtr]::Size" shell=powershell
local:
    4

C:\Users\Administrator>salt-call cmd.which powershell
local:
    C:\Windows\System32\WindowsPowerShell\v1.0\powershell.EXE(That is 64 bit version?)

C:\Users\Administrator>salt-call cmd.run "C:\Windows\system32\WindowsPowerShell\v1.0\powershell.exe [intPtr]::Size"
local:
    4

C:\Users\Administrator>salt-call cmd.run "C:\Windows\syswow64\WindowsPowerShell\v1.0\powershell.exe [intPtr]::Size"
local:
    4
```
I am quite confused by the result, it returns differently between salt-call and system cmd even I have indicated which executive file to run. Dose the version of python matter?
So how can I make sure my command send from salt-mater is run with powershell x64?
### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp936
        machine: AMD64
        release: 2008ServerR2
         system: Windows
        version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free

**Comment by dwoz** [comment]
@chen-j-y Thank you for reporting this! If there are any other programs salt calls from system32 directory we should look into a general solution for all of them.

**Comment by damon-atkins** [comment]
Just notice `Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]` this in your salt report. Yep 32bit version of salt minion.

**Comment by damon-atkins** [comment]
If you want 64bit powershell install 64bit salt minion.

**Comment by damon-atkins** [comment]
The other suggest is to use the Python3 version as this works better with Windows 64bit.
