### ISSUE TITLE
ec2_pillar.py not pulling grain correctly

### ISSUE THREAD

**Issue by mr337** [saltstack/salt#50818]
### Description of Issue/Question

`ec2_pillar.py` will not pull `instance-id` when present in grains list falsely failing to populate pillar data.

### Setup
Setup of master config to enable ec2_pillar
```
ext_pillar:
  - ec2_pillar:
      use_grain: True
      tag_list_sep: ';'
```

### Steps to Reproduce Issue
Enable the ec2_pillar with the above and refresh pillar. Doing so will not populate the pillar correctly and have an error message when running salt master in debug.

```
Minion-id is not in AWS instance-id formation, and there is no instance-id grain for minion XXXX
```

Following up on this log it looks like the ec2_pillar file is calling grains but not in the correct way.

Modifying this line https://github.com/saltstack/salt/blob/95d1b9c032a6aa336891552dcc27c05bbe4ba5c8/salt/pillar/ec2_pillar.py#L113 to
```
grain_instance_id = __grains__.get('instance-id', None)
```
fixes the issue and pulls the `instance-id` correctly. When running a `grains.ls` I do not see a `meta-data` key either.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Main difference is master is using python2 and minion is on python3.

Master
```
Salt Version:
           Salt: 2018.3.3
                                    
Dependency Versions:  
           cffi: Not Installed
       cherrypy: Not Installed  
       dateutil: 2.6.1
      docker-py: Not Installed      
          gitdb: 2.0.3
      gitpython: 2.1.8                                            
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1029-aws
         system: Linux
        version: Ubuntu 18.04 bionic
```

Minion
```
Salt Version:   
           Salt: 2018.3.3           
                      
Dependency Versions:   
           cffi: Not Installed  
       cherrypy: Not Installed
       dateutil: 2.7.5              
      docker-py: Not Installed
          gitdb: Not Installed                                                        
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.5 (default, Apr  1 2018, 05:46:30)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1021-aws
         system: Linux
        version: Ubuntu 18.04 bionic

```

**Comment by dwoz** [comment]
@mr337 Thank you for reporting this issue.

**Comment by damon-atkins** [comment]
The code is correct, I suggest you have not told the minion to collect the ec2 data, and hence meta-data grain structure is empty. i.e. `metadata_server_grains: True` in the minion configuration file.

**Comment by damon-atkins** [comment]
This is a doco issue with salt.pillar.ec2_pillar

**Comment by mr337** [comment]
I do not believe I have that setup as so. The confusing part is the minon gets EC2 related info as a ec2 grain stored under `ec2`. I don't recall enabling that and assumed that was autodetected by salt.

Let me tweak and confirm the changes.

**Comment by damon-atkins** [comment]
EC2 pillar need a way to determine the instance with in AWS.  If the minion name or hostname is the aws instance-id it can find it.   Grains option allows you to call the minion something else and so it uses the grain data from the minion to get the instance-id so you need to trust the minion will not provide false information to gain extra access.

**Comment by mr337** [comment]
That worked like a charm. I now need to undo my fixes :D

I have a PR https://github.com/saltstack/salt/pull/50860 to improve the docs. Closing for now since this is a mis-configuration that the new docs should clear up.
