### ISSUE TITLE
Bootstrapping test instances for kitchen-salt is broken

### ISSUE THREAD

**Issue by gtmanfred** [saltstack/salt#50813]
### Description of Issue/Question 

https://github.com/saltstack/salt/blob/develop/.kitchen.yml#L33

This is pointing to a git branch that no longer exists, it should either be switched back to using stable releases, or have a `v` placed in front of `<%= version>` so that it references the tag.

**Comment by gtmanfred** [comment]
@s0undt3ch @dubb-b Thanks

**Comment by dubb-b** [comment]
@gtmanfred I missed that one. Thanks! I updated all the kitchen Jenkins slave ones.

**Comment by dubb-b** [comment]
@gtmanfred just out of curiosity. Would it be better to use `stable` or `git`? I figured git was better because than we are pinned to the point in which we tagged for the release.

**Comment by gtmanfred** [comment]
I always used stable where I could because it was faster than having to clone the whole git repo just to do an install, especially when we didn't have to.

**Comment by dubb-b** [comment]
This is complete.
