### ISSUE TITLE
Saltstack configuration

### ISSUE THREAD

**Issue by vinolinjermiahj** [saltstack/salt#50830]
### Description of Issue/Question
I am a new user for saltstack- configuration management.I am getting the following error.Can anyone guide me in fixing this.

WARNING: Unable to bind socket 10.0.0.1:4505, error: [Errno 99] Cannot assign requested address; Is there another salt-master running?
The salt master is shutdown. The ports are not available to bind

### Setup
I am using an Ubuntu instance in AWS.
![salt error](https://user-images.githubusercontent.com/44571711/49847723-9dbda100-fdf7-11e8-82c0-6683bd950a86.png)

**Comment by Ch3LL** [comment]
you probably have a  master that is already running in the background. `ps aux | grep -i salt` should show you if its already running.

If there is not another salt-master running can you verify that port is not being used by something else? `netstat -tlnp`
