### ISSUE TITLE
[BUG] 3003 cmdmod passes NOTIFY_SOCKET

### ISSUE THREAD

**Issue by Luit** [saltstack/salt#50851]
### Description of Issue/Question
We have a couple of `cmd.run` invocations calling a subprocess which will gladly notify `STOPPING=1`, causing systemd to enter the stop-sigterm state for the salt-minion service (killing it 90 seconds later).

### Setup

Debian with Salt 2018.3 (both master and minion).

### Steps to Reproduce Issue

Apply this state to kill your minions:

    sh -c 'echo "STOPPING=1" | nc -uU $NOTIFY_SOCKET':
      cmd.run:
      - bg: True

In our case the process doing this was `asterisk`.

### Versions Report

    Salt Version:
               Salt: 2018.3.2
    
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.5.3
          docker-py: 3.5.0
              gitdb: 2.0.0
          gitpython: 2.1.1
              ioflo: Not Installed
             Jinja2: 2.9.4
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (default, Nov 24 2017, 17:33:09)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.1
            timelib: Not Installed
            Tornado: 4.4.3
                ZMQ: 4.2.1
     
    System Versions:
               dist: debian 9.5 
             locale: UTF-8
            machine: x86_64
            release: 4.9.0-5-amd64
             system: Linux
            version: debian 9.5

**Comment by Luit** [comment]
Currently mitigated by doing this:

    root@salt-master-dev1:/srv/saltstack/salt# diff -u /usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py _modules/cmdmod.py 
    --- /usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py	2018-10-08 17:56:30.000000000 +0200
    +++ _modules/cmdmod.py	2018-12-06 16:50:25.487343358 +0100
    @@ -542,6 +542,8 @@
             run_env = os.environ.copy()
             run_env.update(env)
     
    +    run_env.pop('NOTIFY_SOCKET', None)
    +
         if prepend_path:
             run_env['PATH'] = ':'.join((prepend_path, run_env['PATH']))
     

Would it be OK to alter cmdmod.py this way?

**Comment by garethgreenaway** [comment]
@Luit Thanks for the report.  Removing an environmental variable in cmdmod.py is definitely not something we want to do, eg. there could be a situation where someone else's needs require that to be there.  Looking at what you have above, can you help me understand what exactly you're trying to do?  There might be a better way to accomplish the goal that doesn't require using cmd.run.

**Comment by Luit** [comment]
Our main issue is with running Asterisk commands. The example was to demonstrate the NOTIFY_SOCKET is there, which (in my opinion) isn't right.

We can, for example, run `salt ... cmd.run 'asterisk -rx "module reload ..."'` on our fleet of machines. When we do this, the subprocess can see a `NOTIFY_SOCKET` in its environment, and will emit sd_notify events like the `STOPPING=1` I demonstrated. 

Because the service unit for salt-minion contains `NotifyAccess=all`, any subprocess is allowed to do this. When this happens, the unit goes into the stop-sigterm state and be killed by systemd if it takes too long to shut down. 

In my opinion the `NOTIFY_SOCKET` that salt-minion is passed by systemd, should stay with salt-minion and not leak into any subprocess it starts. If you don't agree with that, that's okay. I have to say this mitigation was a quick hack as well, and there might be a better location to pop the variable as well.

**Comment by max-arnold** [comment]
Maybe #48021 could be extended to support this use-case?

**Comment by Luit** [comment]
From what I understand, #48021 is for cmdmod calls from apt/yum/zypper/etc. instead of a generic cmdmod alteration. As described in my last comment, we also directly call cmd.run from the command line for some ops work.

**Comment by Luit** [comment]
Let's give this issue an update shall we.

As far as I can see, the `NOTIFY_SOCKET` is only used by the salt processes to signal `READY=1`. If this is not the case, disregard the rest of this comment.

The sd_notify C API has an parameter called `unset_environment`, with the following documentation:
> If the unset_environment parameter is non-zero, sd_notify() will unset the $NOTIFY_SOCKET environment variable before returning (regardless of whether the function call itself succeeded or not). Further calls to sd_notify() will then fail, but the variable is no longer inherited by child processes.

AFAICT this option is there to do exactly that: notify ready, and remove any chances of it getting any other status from us or our children.

I suggest `salt.utils.process.notify_systemd` is altered to do this. The `systemd.daemon.notify` function has this parameter, and the custom implementation in the `except ImportError` block can easily `os.unsetenv('NOTIFY_SOCKET')` before returning from the function.

**Comment by wdoekes** [comment]
Is it fixed then? (Maybe it is.. I don't run latest.)

If not, surely you don't want processes called from cmd.run that touch NOTIFY_SOCKET to break systemd-support for salt-minion parent.

Side-note: the immediate cause here was rasterisk (asterisk -r), which should probably _also_ be fixed (*). But that doesn't change the fact that the systemd notify socket should not be exposed to unrelated children.

(*) patch to asterisk/asterisk#master
```patch
--- a/main/asterisk.c
+++ b/main/asterisk.c
@@ -2013,7 +2013,7 @@ static void really_quit(int num, shutdown_nice_t niceness, int restart)
                run_cleanups = 0;
        }
 
-       if (!restart) {
+       if (!restart && !ast_opt_remote) {
                ast_sd_notify("STOPPING=1");
        }
        if (ast_opt_console || (ast_opt_remote && !ast_opt_exec)) {
```

**Comment by sagetherage** [comment]
@garethgreenaway looks like this might be fixed, can you please do a little follow up?

**Comment by sagetherage** [comment]
Reopened -- still an issue as noted in IRC - salt and asterisk:
`the salt minion on the target machine is Killed by systemd around 90 seconds after execution. "systemd[1]: salt-minion.service: Killing process 15212 (salt-minion) with signal SIGKILL."...  I changed systemd NotifyAccess to "exec" instead of "all" and this is what I just got:  systemd[1]: salt-minion.service: Got notification message from PID 16969, but reception only permitted for main PID 16845... Ok, so this is definitely because of the Notify= setting to "all" by default. Asterisk apparently sends an sd_notify() message when running a remote command as I have been doing. Once I put it all together it seems like this has already been triaged somewhat here: https://github.com/saltstack/salt/issues/50851  although apparently was never "fixed"`

**Comment by hbonath** [comment]
I ran into this issue using Salt 3003 on Debian Based systems while interacting with the Asterisk PBX.

### Salt Master:
```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: 1.3.10
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-1039-azure
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```

### Salt Minion (Ubuntu)
```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.0.3
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-1046-azure
        system: Linux
       version: Ubuntu 20.04 focal
```
### Salt Minion (Debian)
```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-16-cloud-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```

### Steps to Reproduce:
I started with minions running the [Ubuntu 20.04 cloud image](https://cloud-images.ubuntu.com/focal/current/focal-server-cloudimg-amd64-disk-kvm.img) and the [Debian Buster cloud image](https://cloud.debian.org/images/cloud/OpenStack/current-10/debian-10-openstack-amd64.qcow2) on Openstack.
I installed the Salt Minion via the [Debian](https://repo.saltstack.com/#debian) and [Ubuntu](https://repo.saltstack.com/#ubuntu) methods outnlined at https://repo.saltstack.com. 
I then installed the distro-packaged version of asterisk via `sudo apt -y install asterisk`

Once my keys were accepted on the master, I issued: `sudo salt myminion cmd.run '/usr/sbin/asterisk -rx "core show version"'`

After 90 seconds, systemd kills the primary minion process, leaving one child process orphaned.

I was also able to reproduce with netcat: `sudo salt myminion cmd.run "printf 'STOPPING=1' | nc -uU /run/systemd/notify" bg=True`

Changing the systemd unit file on the affected minion to read `NotifyAccess=exec` instead of `NotifyAccess=all` prevents this from happening altogether, however I have not tested the ramifications of leaving it like this long term.
