### ISSUE TITLE
 Question: How to use proxy or not with http.query ?

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#50853]
### Description of Issue/Question
i want to use proxy settings   or not with http.query module , depending on context. In fact, i want to use different proxy settings, depending on target

Using proxy_host conf in minion is not a solution, since it cannot be deactivated, and there is no no_proxy directive, and can't use multiple proxies

Using environment variables could be a solution, setting and unsetting http_proxy with environ.setenv module. But  http.query   module do not use it.

Examples: 
  http.query http://www.xxx.com  : want to use proxy 1 this time
 
   http.query http://www.xx2.com  : want to use proxy 2 this time

   http.query http://www.xx3.com  : don't want to use proxy this time

So how to do?
### Setup
salt-master: 2017.7.7
salt-minion: 2016.3.8

### Versions Report
master:
Salt Version:
           Salt: 2017.7.7
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 13 2018, 12:45:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-43-generic
         system: Linux
        version: Ubuntu 14.04 trusty

minion:
Salt Version:
           Salt: 2016.3.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.3 Maipo
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

**Comment by garethgreenaway** [comment]
@gaetanquentin Thanks for the report.  You should be able to pass `proxy_host`, `proxy_username`, and `proxy_password` parameters to `http.query` in order to use variable proxy settings.

**Comment by max-arnold** [comment]
It will be possible in the Fluorine release: #48108

**Comment by gaetanquentin** [comment]
> @gaetanquentin Thanks for the report. You should be able to pass `proxy_host`, `proxy_username`, and `proxy_password` parameters to `http.query` in order to use variable proxy settings.

That's not explained in the doc.
