### ISSUE TITLE
GPG Decryption Failed

### ISSUE THREAD

**Issue by kenanbiel** [saltstack/salt#50882]
### Description of Issue/Question

My salt environment has been setup for 2 years now and I've been experiencing GPG decryption failed every, now and then. 

Based on salt master logs:
```
{ "highstate-timestamp": "2018-12-16 17:03:58,595", "name": "salt.loaded.int.render.gpg", "levelname": "WARNING ", "message": "Could not decrypt cipher -----BEGIN PGP MESSAGE-----
Version: GnuPG v1

hQEMAw9iLKXotYWZAQgAqWanFkBMos5tEeH0P6dyHonlA5pkUv2xFj4oDGoaBCG2
TwbvD3/HXI6rTvvvSK757nvKiTHR+Aq6LLVYJ0+S2HYuhG5A33FWCvZ/pMQBCHhg
1hQ/oTzuHLSZAsk9dhtEskNnXJRt0iGkmAeH5qUk8ZOBHNUHsLzggQ56BosSuglA
e63QAf9PMvd0tgNGnC7ZBmchWWDh8VPHJCotQFrEb6BvDvKXvp5fSVed/7QFPQK3
5mlasbKWwPQBZwe66HZ2xs/XhF60cvz1Jh5lv/KjQtrGnkzXcr6pe9vBZjmItPw7
d8GyWy9BFSAGFY5iINkFpg8bnPAYM9oIKjHw+B/jxNJJAWHvb54Fggl8wNdA3gDj
Yd74jjvM3OC0i7JDUAacjg7hdTxLbL9JxNNKvBhCtRzcTfy9Uinm2N6W1tuEBu4N
TT9L3ZlUAAn0nA==
=+diQ
-----END PGP MESSAGE-----
, received: [GNUPG:] ENC_TO <reducted>
gpg: can't connect to the agent: IPC connect call failed
[GNUPG:] KEY_CONSIDERED <reducted>
gpg: encrypted with 2048-bit RSA key, ID <reducted>, created 2017-02-07
      "companykey"
[GNUPG:] NO_SECKEY <reducted>
[GNUPG:] BEGIN_DECRYPTION
[GNUPG:] DECRYPTION_FAILED
gpg: decryption failed: No secret key
[GNUPG:] END_DECRYPTION
" }
```

But on the next scheduled highstate, i don't experience the problem.

### Setup

/srv/salt/pillar/schedule.sls:
```
schedule:
  highstate:
    function: state.highstate
    seconds: 300
    splay: 60
```
/srv/salt/pillar/db.sls
```
#!jinja|yaml|gpg
api:
  db_username: |
    -----BEGIN PGP MESSAGE-----
    Version: GnuPG v1

    hQEMAw9iLKXotYWZAQgAqWanFkBMos5tEeH0P6dyHonlA5pkUv2xFj4oDGoaBCG2
    TwbvD3/HXI6rTvvvSK757nvKiTHR+Aq6LLVYJ0+S2HYuhG5A33FWCvZ/pMQBCHhg
    1hQ/oTzuHLSZAsk9dhtEskNnXJRt0iGkmAeH5qUk8ZOBHNUHsLzggQ56BosSuglA
    e63QAf9PMvd0tgNGnC7ZBmchWWDh8VPHJCotQFrEb6BvDvKXvp5fSVed/7QFPQK3
    5mlasbKWwPQBZwe66HZ2xs/XhF60cvz1Jh5lv/KjQtrGnkzXcr6pe9vBZjmItPw7
    d8GyWy9BFSAGFY5iINkFpg8bnPAYM9oIKjHw+B/jxNJJAWHvb54Fggl8wNdA3gDj
    Yd74jjvM3OC0i7JDUAacjg7hdTxLbL9JxNNKvBhCtRzcTfy9Uinm2N6W1tuEBu4N
    TT9L3ZlUAAn0nA==
    =+diQ
    -----END PGP MESSAGE-----
```

Also, I don't generate my keys anymore. I just copy it manually from my stash to /etc/salt/gpgkeys, then just do import the public key:
```
/usr/bin/gpg --import /etc/salt/gpgkeys/public_key.gpg
```

Right now here's the contents of my /etc/salt/gpgkeys: 
```
$ ls /etc/salt/gpgkeys/
S.gpg-agent
S.gpg-agent.browser
S.gpg-agent.extra
S.gpg-agent.ssh
private-keys-v1.d
public_key.gpg
pubring.gpg
secring.gpg
trustdb.gpg
```

### Steps to Reproduce Issue
I tried from salt master to list keys and it doesn't fail:

```
$ sudo salt 'server-1' pillar.items 
server-1:
    ----------
    api:
        ----------
        db_username:
            db_username
```
            
I'm not exactly sure how to reproduce this because this only happened just once in a blue moon (but this has happened multiple times before).

I was reading some issues posted in Google about this same issue:
http://joshbolling.com/2017/05/21/quick-tip-fix-gpg-cant-connect-to-the-agent-ipc-connect-call-failed-error/
https://blog.badgerops.net/2017/05/31/gpg-encrypting-secrets-with-saltstack/

According to those two:
-  Error was being caused by a GPG agent that was already running

Am i doing something wrong here? Is it because of the directory where the keys are located? Is it because my scheduler is too fast?

### Versions Report

Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.13
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1021-aws
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by Ch3LL** [comment]
can you check the gpg log file and see if there is any useful information there.

also can you check when this occurs in the salt debug log if there is another process right before that thats trying to render the gpg

**Comment by kenanbiel** [comment]
I just started the GPG logging. I'll update this thread once i encounter it again and post the GPG log.

But here's the output of the salt debug log:

```
kenan@salt-master:~$ sudo salt 'server-1' pillar.items -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/engine.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/engine.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/f_defaults.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/f_defaults.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/lxc_profiles.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/lxc_profiles.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master
[DEBUG   ] Missing configuration file: /home/kenan/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/engine.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/engine.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/f_defaults.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/f_defaults.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/lxc_profiles.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/lxc_profiles.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Changed git to gitfs in master opts' fileserver_backend list
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-master
[DEBUG   ] Missing configuration file: /home/kenan/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Popen(['git', 'version'], cwd=/home/kenan, universal_newlines=False, shell=None)
[DEBUG   ] Popen(['git', 'version'], cwd=/home/kenan, universal_newlines=False, shell=None)
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'salt-master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/2c/9d118024bbe4db9ff2b585b3635c1c597e8493bcfab9aba8c06d250675ee3a/.minions.p
[DEBUG   ] get_iter_returns for jid 20181218070623416000 sent to set(['server-1']) will timeout at 07:06:53.428735
[DEBUG   ] jid 20181218070623416000 return from server-1
[DEBUG   ] return event: {u'server-1', u'retcode': 0, u'ret': { <reducted>
```

**Comment by kenanbiel** [comment]
Hi @Ch3LL it happened again to me. This is the output for gpg-agent.log

```
2019-01-11 10:06:25 gpg-agent[26930] gpg-agent (GnuPG) 2.2.4 stopped
2019-01-11 23:24:22 gpg-agent[10138] gpg-agent (GnuPG) 2.2.4 started
2019-01-11 23:24:22 gpg-agent[10138] socket file has been removed - shutting down
2019-01-11 23:24:22 gpg-agent[10138] gpg-agent (GnuPG) 2.2.4 stopped
2019-01-11 23:24:22 gpg-agent[10150] gpg-agent (GnuPG) 2.2.4 started
2019-01-11 23:24:22 gpg-agent[10150] error enabling daemon termination by socket removal: No such file or directory
2019-01-11 23:25:22 gpg-agent[10150] can't connect my own socket: IPC connect call failed
2019-01-11 23:25:22 gpg-agent[10150] this process is useless - shutting down
2019-01-11 23:26:22 gpg-agent[10150] gpg-agent (GnuPG) 2.2.4 stopped
2019-01-12 00:52:50 gpg-agent[29756] gpg-agent (GnuPG) 2.2.4 started
2019-01-12 00:52:50 gpg-agent[29756] socket file has been removed - shutting down
```
Any ideas how to resolve this?

**Comment by Ch3LL** [comment]
and do you have the salt time stamps to go along with those logs by chance?

**Comment by Ch3LL** [comment]
the salt debug log time stamps that is

**Comment by Ch3LL** [comment]
thanks for the additional information. I was specifically looking for the logs in teh log file /var/log/salt/master as those include timestamps. I am trying to tie your error: `socket file has been removed - shutting down` to what happens in salt. It looks like something is shutting down your gpg agent. 

are you handing the gpg-agent service anywhere else? or even possibly in your state files?

**Comment by kenanbiel** [comment]
Unfortunately, my debug logs wasn't turned on during that period. It's happening now more regularly. 

```
February 17th 2019, 20:56:44.039 | gpg: decryption failed: No secret key
February 17th 2019, 20:56:44.039 | gpg: can't connect to the agent: IPC connect call failed
February 17th 2019, 20:56:44.039 | gpg: encrypted with 2048-bit RSA key, ID 0F622CA5E8B58599, created 2018-02-07
February 15th 2019, 06:01:35.675 | gpg: decryption failed: No secret key
February 15th 2019, 06:01:35.675 | gpg: encrypted with 2048-bit RSA key, ID 0F622CA5E8B58599, created 2018-02-07
February 15th 2019, 06:01:35.674 | gpg: can't connect to the agent: IPC connect call failed
February 14th 2019, 14:13:33.970 | gpg: encrypted with 2048-bit RSA key, ID 0F622CA5E8B58599, created 2018-02-07
February 14th 2019, 14:13:33.970 | gpg: can't connect to the agent: IPC connect call failed
February 14th 2019, 14:13:33.970 | gpg: decryption failed: No secret key
February 13th 2019, 23:00:39.255 | gpg: encrypted with 2048-bit RSA key, ID 0F622CA5E8B58599, created 2018-02-07
February 13th 2019, 23:00:39.255 | gpg: decryption failed: No secret key
February 13th 2019, 23:00:39.255 | gpg: can't connect to the agent: IPC connect call failed
February 12th 2019, 22:25:20.725 | gpg: decryption failed: No secret key
February 12th 2019, 22:25:20.725 | gpg: encrypted with 2048-bit RSA key, ID 0F622CA5E8B58599, created 2018-02-07
```

GPG service is within the salt-master server. I already have the keys initially. I just imported them via these set of commands:

```
cp public_key.gpg /etc/salt/gpgkeys
cp pubring.gpg /etc/salt/gpgkeys
cp secring.gpg /etc/salt/gpgkeys
cp trustdb.gpg /etc/salt/gpgkeys
chmod 600 -R /etc/salt/gpgkeys

/usr/bin/gpg --import /etc/salt/gpgkeys/public_key.gpg
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-core have any other ideas here whats going on?

**Comment by waynew** [comment]
I'll take a look at this either today or tomorrow

**Comment by kenanbiel** [comment]
Thanks @waynew. Let me know what other details you need from me.

**Comment by waynew** [comment]
@kenanbiel do you have gpg logs and salt master logs from the same time period?

**Comment by waynew** [comment]
I've done a cursory check - for gpg-agent, or `S.gpg-agent` (the default socket filename), or `gpg-connect-agent` (which gives me `can't connect to the agent: IPC connect call failed`)...

**Comment by waynew** [comment]
Also, what is the output of `ps aux | grep gpg` when the call is failing?

**Comment by kenanbiel** [comment]
I have just reactivated gpg logs, salt-debug logs and adding `ps aux|grep gpg` monitor when this happens again. I'll update this thread as soon as i experience it again.

**Comment by dmurphy18** [comment]
@kenanbiel I presume that you are using Ubuntu 18.04 since gpg v2.2.4 ( the version which ships with Ubuntu 18.04).  I have found that with the move to using systemd internally by gpg-agent that items now should be done as a non-root user rather than as root, for gpg-agent to function similar as in the past, especially with the use of passphrase caching.  I first noticed this issue with non-root instantiation with on Raspbian 9 (approx. Debian 9.2). The standard sockets are created differently between root and non-root users.

Had to change how debbuild.py (debbuild_pkgbuild.py in develop) in 2019.2.0 used gpg internally for a non-root user, also check salt-pack or salt-pack-py3 for how file_roots/setup/ubuntu/gpg_agent.sls starts and stop gpg-agent.

Run into some issues still with orchestration and Ubuntu 18.04 and gpg-agent v2.2.4, however with Ubuntu 18.10 and gpg-agent v2.2.8 do not occur (some fixes for pinentry may explain no more issues).

Hope this helps resolve your issue

**Comment by kenanbiel** [comment]
@waynew so here are the debug logs i got:

From /var/log/gpg_agent.log, basically no changes from the moment i have re-started it:
```
2019-03-25 16:12:30 gpg-agent[12649] gpg-agent (GnuPG) 2.2.4 started
/var/log/gpg_agent.log (END)
```

From /var/log/salt/master:
```
2019-03-28 05:58:26,917 [salt.utils.lazy  :100 ][DEBUG   ][7941] LazyLoaded local_cache.clean_old_jobs
2019-03-28 05:58:26,985 [salt.utils.gitfs :2675][DEBUG   ][7954] Re-using gitfs object for process 7954
2019-03-28 05:58:26,986 [salt.utils.gitfs :2675][DEBUG   ][7954] Re-using gitfs object for process 7954
2019-03-28 05:58:26,989 [salt.utils.gitfs :2675][DEBUG   ][7947] Re-using gitfs object for process 7947
2019-03-28 05:58:26,991 [salt.utils.gitfs :2675][DEBUG   ][7947] Re-using gitfs object for process 7947
2019-03-28 05:58:26,991 [salt.utils.lazy  :100 ][DEBUG   ][7941] LazyLoaded localfs.list_tokens
2019-03-28 05:58:26,992 [salt.utils.gitfs :852 ][DEBUG   ][7941] Set update lock for git_pillar remote 'master git@gitrepo:project/
devops-saltpillar.git'
2019-03-28 05:58:26,992 [salt.utils.gitfs :755 ][DEBUG   ][7941] Fetching git_pillar remote 'master git@@gitrepo:project/devops-salt
pillar.git'
2019-03-28 05:58:26,993 [git.cmd          :719 ][DEBUG   ][7941] Popen(['git', 'fetch', '-v', 'origin'], cwd=/var/cache/salt/master/git_pillar/02fa59166
b906c9ae290dec334229800a9b78a3309cc11766b2fc77dd9e8e719, universal_newlines=True, shell=None)
2019-03-28 05:58:26,994 [salt.utils.gitfs :2675][DEBUG   ][7956] Re-using gitfs object for process 7956
2019-03-28 05:58:27,172 [salt.utils.gitfs :2675][DEBUG   ][7955] Re-using gitfs object for process 7955
2019-03-28 05:58:27,179 [salt.utils.gitfs :2675][DEBUG   ][7955] Re-using gitfs object for process 7955
2019-03-28 05:58:27,182 [salt.utils.gitfs :2675][DEBUG   ][7945] Re-using gitfs object for process 7945
2019-03-28 05:58:27,189 [salt.utils.gitfs :2675][DEBUG   ][7945] Re-using gitfs object for process 7945
2019-03-28 05:58:27,192 [salt.utils.gitfs :2675][DEBUG   ][7954] Re-using gitfs object for process 7954
2019-03-28 05:58:27,400 [salt.loaded.int.returner.local_cache:249 ][DEBUG   ][7947] Adding minions for job 20190328055827399749: [u'salt-minion']
2019-03-28 05:58:27,401 [salt.utils.job   :68  ][INFO    ][7947] Got return from salt-minion for job 20190328055
827399749
2019-03-28 05:58:27,401 [salt.utils.event :739 ][DEBUG   ][7947] Sending event: tag = salt/job/20190328055827399749/ret/salt-minion; data data = {u'tgt_type': u'glob', 'fun_args': [], 'jid': u'20190328055827399749', 'return': { <<< REDACTED >>>   apikey: <redacted> \n+    fullstory.apikey: -----BEGIN PGP MESSAGE-----\\nVersion: GnuPG v1\\n\\nhQEMAw9iLKXotYWZAQgAqKs6bj2GT1c99IR32lmiW/e7Rtm/8F9OqtCQ5lL7/X3t\\nTEjpLwzjuGlvL0i4hgeKIZ4IkfnlMpTwkfBk57GSn1ftPvBr71NCsrSRlbDrGjK0\\ntpfPm//4UIxAHYmaZPz6zDAN2fpetXl/IKIvH8m6VX/kkPN9cNBQbA8sZpHxHIm8\\nuEcg0ZkHrQ+lg4caXocdLNWoP8oJS8AKyEKKbu9/aBoVeNnio3EMwbwE7vtwYQJg\\nhhIypLGAzuw+FWPee69K3b6S6326cC1Bh+ctW/0TKNpGsYFh4CEFEagVDlRGeR3w\\n84Lnffxb5Z9fZXSRaPfzkX1u0ycF91n7XOspsbp6/dJbAa4h9CSRxi9zizFiMaB8\\nC1+DGfx9QGTU6YcDOeYSbPfDIsXziUcnAB8x7cYmzEllLhB9yXZhJ4CI9pLhvirB\\nA0J4QWn9aL/nwTAqb+7TfvPh3Ib1jgQM0JtW/w==\\n=UbsW\\n-----END PGP MESSAGE-----\\n\n}}, , 'retcode': 0, 'success': True, 'schedule': 'highstate', u'tgt': salt-minion', 'cmd': '_return', 'pid': 9763, '_stamp': '2019-03-28T05:58:27.401316', u'arg': [], 'fun': 'state.highstate', 'id': 'salt-minion', 'out': 'highstate'}
2019-03-28 05:58:27,407 [salt.utils.reactor:109 ][DEBUG   ][7940] Gathering reactors for tag salt/job/20190328055827399749/ret/salt-minion
2019-03-28 05:58:27,407 [salt.utils.reactor:196 ][DEBUG   ][7940] Compiling reactions for tag salt/job/20190328055827399749/ret/salt-minion
2019-03-28 05:58:27,407 [salt.utils.gitfs :2675][DEBUG   ][7940] Re-using gitfs object for process 7940
2019-03-28 05:58:27,404 [salt.loaded.int.returner.local_cache:249 ][DEBUG   ][7947] Adding minions for job 20190328055827399749: [u'salt-minion']
2019-03-28 05:58:27,414 [salt.utils.gitfs :2675][DEBUG   ][7940] Re-using gitfs object for process 7940
2019-03-28 05:58:27,414 [salt.utils.gitfs :2675][DEBUG   ][7940] Re-using gitfs object for process 7940
```

According to the debug logs, there's no indication why decryption failed. I have redacted the other states in the debug file. The weird part is that i am decrypting around 20-30 keys for this server and only one key failed to be decrypted. Of course, on the next highstate, salt-master was able to decrypt and provide correct value.

**Comment by kenanbiel** [comment]
@dmurphy18 Yes, you are right - i'm using Ubuntu 18.04 and gpg v2.2.4. 

This really doesn't happen regularly, just once in a while but it has affected my prod environment multiple times already. So your advice is to update my salt-master's Ubuntu to 18.10 so it would use gpg 2.2.8?

**Comment by waynew** [comment]
That seems like the suggestion - though I wonder if there's a backport of gpg 2.2.8

**Comment by dmurphy18** [comment]
@kenanbiel @waynew Most times 18.10 works for me, but still fighting 18.04 gpg-agent v2.2.4.  Have not found a satisfactory solution myself yet.  When I get time, plan on looking at changes and back-porting, since attempting to utilise v2.2.8 directly was a non-starter, too many dependent changes.

**Comment by marcmerlin** [comment]
We've seen this on our server too,  The problem was that we were running out of locked memory and gpg was just failng to run and decrypt.
Sadly salt does not detect any failure and passed on the undecrypted file, to overwrite the correct decrypted file, breaking whatever relies on it.
It seems like a pretty bad flaw. You may want to try this in your systemd file:  
LimitMEMLOCK=infinity

**Comment by phoerious** [comment]
We are having the same issue. It is impossible to target more than a handful of nodes at once or else GPG will fail to decrypt all pillars for all nodes. We run the salt master in a Docker container and I tried setting all necessary flags for unlimited mlock, but I can't seem to get it working. Setting LimitMEMLOCK in the salt-master unit file has no effect and the gpg-agent isn't managed by systemd. Any tips how I can solve this issue?

**Comment by phoerious** [comment]
I enabled debugging for the gpg-agent and this is what appears in the log:

```
2020-10-21 15:49:20 gpg-agent[15763] gpg-agent (GnuPG) 2.2.4 stopped
2020-10-21 15:49:21 gpg-agent[15770] gpg-agent (GnuPG) 2.2.4 started
2020-10-21 15:49:50 gpg-agent[15770] Warning: using insecure memory!
2020-10-21 15:49:50 gpg-agent[15770] decryption failed: Cannot allocate memory
2020-10-21 15:49:50 gpg-agent[15770] command 'PKDECRYPT' failed: Cannot allocate memory <gcrypt>
2020-10-21 15:49:50 gpg-agent[15770] decryption failed: Cannot allocate memory
2020-10-21 15:49:50 gpg-agent[15770] command 'PKDECRYPT' failed: Cannot allocate memory <gcrypt>
2020-10-21 15:49:50 gpg-agent[15770] Ohhhh jeeee: ... this is a bug (../../src/sexp.c:1433:do_vsexp_sscan)
2020-10-21 15:49:51 gpg-agent[16203] gpg-agent (GnuPG) 2.2.4 started
```

There is enough free memory left on the host and the memlock limits of the gpg-agent process are unlimited.

**Comment by phoerious** [comment]
I can reduce the number of workers on the master to 35, which gets rid of the problem. Any number above that will reliably trigger the bug. Unfortunately, this means that now we are getting the occasional minion response timeout again when the worker pool is exhausted.

**Comment by Ch3LL** [comment]
what version of libgcrypt do you have installed? There was some improvements implemented in gpg to help gpg handle more concurrent connections in 1.8.2 of libgcrypt and gpg 2.2.4 (which you have)

There is also this flag to gpg you can use if using secure memory: ` --auto-expand-secmem` https://dev.gnupg.org/T3530

**Comment by phoerious** [comment]
gpg-agent 1.8.1, which is the latest in Ubuntu 20.04 at the moment. I already tried auto-expand-secmem, but that doesn't solve the problem.

**Comment by oeuftete** [comment]
@phoerious I suspect the `libgcrypt` version is the problem.  Updating it past 1.8.1 was the resolution for Ubuntu 18.04 in another case I've recently been involved with.  To summarize (and this is nothing more than @Ch3LL [posted above](https://github.com/saltstack/salt/issues/50882#issuecomment-715293206)):

* `libgcrypt` added support for `auto-expand-secmem` in 1.8.2
* GnuPG added support for `auto-expand-secmem` in 2.2.4
* Ubuntu 18.04 (and apparently, 20.04) distributes `libgcrypt` 1.8.1 and GnuPG 2.2.4
* Therefore, the problem here is essentially Ubuntu distributing GnuPG without the library it needs to be fully featured.

See also #51356.

**Comment by dlatendresse** [comment]
im having the same issue with CentOS 7

**Comment by frebib** [comment]
We're experiencing exactly this issue when migrating our (regrettably python2) masters to 2019.2 with python 3. Out of 7 masters that I've tried, we saw it in all of them to varying degrees. Understandably it's worse in masters with more minions, although we also see it in one master with a mere ~11 minions connected on occasion. In 6 of the masters, setting `auto-expand-secmem` in `/etc/salt/gpgkeys/gpg-agent.conf` seems to have completely solved the issues, although one master for some inexplicable reason continues to fail. We have a reasonably large number of GPG blobs (unfortunately) which I presume only makes the problem worse still. I also tried setting the `memlock` ulimit to infinite and it had no effect. 

At this point I'm at a loss as to what to do and have no real alternative than to revert the master to python2 until we have a better fix, or we make less use of GPG. Any advice is welcomed.

**Comment by dmurphy18** [comment]
@frebib This issue is closed over a year, please open a new issue with details of the system, versions of Salt used etc. and how to reproduce the issue and any other information which would help to resolve the issue.

Adding to issues which have been closed for over a year, is not a good approach to getting issues resolved.

**Comment by phoerious** [comment]
We're also still having problems with that when addressing more than about 50-70 nodes at once. I would assume that with gpg_decrypt_must_succeed becoming the default, more people will start noticing this. Previously, this was more of a silent failure in many cases.
