### ISSUE TITLE
New Azure module automodule docs missing from module document 

### ISSUE THREAD

**Issue by MDPolaris** [saltstack/salt#50893]
### Description of Issue/Question
Automodule docs for the Azure modules are not present at this location: https://github.com/saltstack/salt/tree/fluorine/doc/ref/modules/all

Modules impacted:
https://github.com/saltstack/salt/blob/fluorine/salt/modules/azurearm_compute.py
https://github.com/saltstack/salt/blob/fluorine/salt/modules/azurearm_network.py
https://github.com/saltstack/salt/blob/fluorine/salt/modules/azurearm_resource.py

https://github.com/saltstack/salt/blob/fluorine/salt/states/azurearm_compute.py
https://github.com/saltstack/salt/blob/fluorine/salt/states/azurearm_network.py
https://github.com/saltstack/salt/blob/fluorine/salt/states/azurearm_resource.py

### Setup
N/A - Issue present in online documentation

### Steps to Reproduce Issue
View Repo here: https://github.com/saltstack/salt/tree/fluorine/doc/ref/modules/all
or visit development documentation page here: https://docs.saltstack.com/en/develop/salt-modindex.html

### Versions Report
N/A - Issue present in online documentation

**Comment by garethgreenaway** [comment]
@MDPolaris Thanks for the report.

**Comment by MTecknology** [comment]
This seems to also be true for azurearm_dns.py, which is missing from the release tarball and documentation.

**Comment by nicholasmhughes** [comment]
the DNS modules didn't make the 2019.2 cut, but I added the rst files for azurearm_dns to develop so it's there when it makes a release
