### ISSUE TITLE
How to use salt-api with Tornado?

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#50908]
### Description of Issue/Question
How to use salt-api with Tornado? instead of CherryPy?

**Comment by dwoz** [comment]
@andyyumiao There are two options for running salt-api:

1) configure a webserver to use wsgi
2) run `salt-api` and use cherrypy as the server

Unfortunately, `salt-api` doesn't support running with tornado.

**Comment by dwoz** [comment]
@andyyumiao My last comment is incorrect. The documentation for running salt-api with tornado can be found here:

https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_tornado.html

**Comment by andyyumiao** [comment]
> @andyyumiao My last comment is incorrect. The documentation for running salt-api with tornado can be found here:
> 
> https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_tornado.html

@dwoz many thanks!
