### ISSUE TITLE
DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly

### ISSUE THREAD

**Issue by kk21986** [saltstack/salt#50911]
### Description of Issue/Question
Getting the below warning messages on salt 2018.3.3 with python3.7.1. Due to these warning messages the automation not behaving properly which uses salt.

```
/usr/local/python371/lib/python3.7/site-packages/salt/utils/decorators/signature.py:31: DeprecationWarning: `formatargspec` is deprecated since Python 3.5. Use `signature` and the `Signature` object directly
  *salt.utils.args.get_function_argspec(original_function)
```

### Steps to Reproduce Issue
Compiled python 3.7.1 on centos 6 and installed salt using pip. When I try to apply any states, started seeing the above warning message on the minion log file. 

### Versions Report
```
# salt --versions-report
Salt Version:
Salt: 2018.3.3

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.7.5
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.10
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.5.6
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 3.7.1 (default, Nov 23 2018, 02:59:05)
python-gnupg: Not Installed
PyYAML: 3.13
PyZMQ: 17.1.2
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.2.5

System Versions:
dist: redhat 6.9 Santiago
locale: UTF-8
machine: x86_64
release: 2.6.39-400.296.2.el6.x86_64
system: Linux
version: Red Hat Enterprise Linux Server 6.9 Santiago
```

**Comment by dwoz** [comment]
@kk21986 Thank you for reporting this issue. Salt does not yet support python 3.7 and we do not support python 3 on redhat 6 due to missing dependency packages.

We will still look into fixing this as we move towards supporting python 3.7.

**Comment by marcosps** [comment]
Using openSUSE Tumbleweed 20190509, I have the same warnings.

**Comment by joel6890** [comment]
Are there any updates on Python 3.7 support?

**Comment by nergdron** [comment]
looking into this as well now that 3.7 is standard on stable Ubuntu releases. got a whole block of 3.7 deprecation warnings it's important to know where Salt's support status is at for this stable python release.

**Comment by nergdron** [comment]
Also! setting PYTHONWARNINGS="ignore" in the shell doesn't suppress these in the mean time, which I assume means salt is explicitly re-enabling them in the codebase. is there a recommended way to suppress these warnings until 3.7 compatibility has been completed?

**Comment by tomlaredo** [comment]
Any news on this?
I tried to run Saltstack on Debian 10 (which comes with python 3.7) and I also see those warnings.

Since bootstrap seems to be broken on Debian 10 (https://github.com/saltstack/salt-bootstrap/issues/1353), what should we do?

**Comment by jyoder-deloitte** [comment]
This is still an issue.  Any updates on Python 3.7 support?

**Comment by AdityaJakkam** [comment]
> This is still an issue. Any updates on Python 3.7 support?

I have this issue!

**Comment by joel6890** [comment]
We solved our issue by using the competing product on our shortlist instead. One with a name beginning with "ans...." and developed by that big Linux company with the logo and name derived from red headwear.

We're running in pull mode, which is scaleable nearly infinitely, and it's serving our purposes very well. And with that, I'll lapse once more into quietness; but you may also want to consider other options rather than a product that struggles to support a Python version for months / years after its release.

Just saying! :)

**Comment by sferia82** [comment]
any solution? It also gave me that error in the installation and it is coming out while I am using the web portal.

**Comment by Ch3LL** [comment]
this should resolve the warning https://github.com/saltstack/salt/pull/56027

**Comment by sagetherage** [comment]
We have opened a SEP for python version support to more explicitly say what version is currently supported and what is going to be supported: https://github.com/saltstack/salt-enhancement-proposals/pull/26

**Comment by OrangeDog** [comment]
Linking to #55835
