### ISSUE TITLE
state.apply test documentation unclear

### ISSUE THREAD

**Issue by dpkirchner** [saltstack/salt#50919]
I'm looking into how to use `state.apply`, however I found the documentation unclear:

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.state.html

The documentation describes how to apply all states and how to apply a single state, however the examples for both have the same command and suggest they do different things: `salt '*' salt.apply test`. In the former case, the docs say it will do a dry-run. In the latter, the docs say it will apply the state `test`.

**Comment by dwoz** [comment]
@dpkirchner I can see why the docs are a bit confusing. Hopefully I can explain it a bit further here.

To apply all states run state.apply without any arguments:

`salt '*' state.apply`

To run the states found in `test.sls` run `state.apply` with a single argument  `test`:

`salt '*' state.apply test`

If you want to apply the states in `test.sls` as a `dry-run`, you'll use the *keyword argument*  `test` set to `true`:

`salt '*' state.apply test test=true`

**Comment by terminalmage** [comment]
Docs updated in https://github.com/saltstack/salt/pull/50940. Thanks for reporting!
