### ISSUE TITLE
FreeBSD 12.0 support 

### ISSUE THREAD

**Issue by thechile** [saltstack/salt#50914]
Hi

Now FreeBSD 12.0 is out, does anyone have an ETA for its support in `bootstraps.sh` and `https://repo.saltstack.com/freebsd/` ?

Thank you.

**Comment by dwoz** [comment]
@thechile Thanks for pointing this out. @saltstack/team-core does anyone know what it will take to package salt for FreeBSD 12.0?

**Comment by cedwards** [comment]
Salt is packaged for FreeBSD 12.0, available in the quarterly and latest repositories. Bootstrap deployment _shouldn't_ change between 11.2 and 12.0.

**Comment by thechile** [comment]
thanks @cedwards for packages .. but for the bootstrap script it only supports up to 11.x as per the following functions using the major version number. When i try it on 12.0 it fails because it doesn't match an available method. 

```
install_freebsd_9_stable_deps()
install_freebsd_10_stable_deps()
install_freebsd_11_stable_deps()
```

Thanks.

**Comment by arizvisa** [comment]
@maintainers:
The only thing left that is needed to close this issue is to update http://repo.saltstack.com/freebsd

**Comment by terminalmage** [comment]
@dmurphy18 Seems like not much of a lift to push this one over the line, can you have a look?

**Comment by sagetherage** [comment]
@dmurphy18 @jshatch can you two please look at this - this week?

**Comment by dmurphy18** [comment]
@cedwards The ip address used to rsync with that SaltStack used is no longer working, can you suggest an appropriate location to rsync with to pick up the salt-packages

**Comment by krionbsd** [comment]
FreeBSD-12 is fully supported, you might use https://bootstrap.saltstack.com/develop to bootstrap it, or use official FreeBSD packages - `pkg install py-salt` which is on 3000.1 at this moment.
