### ISSUE TITLE
#48290 broke os grain in Fluorine

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#50924]
### Description of Issue/Question
With napalm installed, #48290 causes the `os` grain to be `None`  in Fluorine.  The virtual function is no longer detecting if is is running inside a proxy minion, so it is running and attempting to overwrite the `os` 
grain.

@mirceaulinic FYI, tagging you since you made that change.

### Setup
Install napalm with Salt fluorine release.

### Steps to Reproduce Issue
Run salt-call grains.get os

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by mirceaulinic** [comment]
I submitted https://github.com/saltstack/salt/pull/50934 to attempt to fix this - please let me know if that works @garethgreenaway.

**Comment by garethgreenaway** [comment]
@mirceaulinic That fixes the issue.  Will this in place does it still fix the issue from the original PR?

**Comment by mirceaulinic** [comment]
Yes, it does. Thank you!

**Comment by garethgreenaway** [comment]
@mirceaulinic Perfect!  Thanks!
