### ISSUE TITLE
tpldir should be documented and included in best pratices

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#50925]
seeing a few users cut their teeth in this.
we should include `tpldir` in  https://docs.saltstack.com/en/latest/ref/states/vars.html

and use it in the best practices:
https://docs.saltstack.com/en/latest/topics/best_practices.html

**Comment by steverweber** [comment]
ref: https://github.com/saltstack/salt/issues/41195

**Comment by hatifnatt** [comment]
I think this is still an issue. I'm not 100% sure but it looks like `tpl*` variables are not documented anywhere.

**Comment by OrangeDog** [comment]
Apparently there also exist `tpldot` and `tplfile`.

**Comment by max-arnold** [comment]
This was solved in https://github.com/saltstack/salt/pull/58238

**Comment by barbaricyawps** [comment]
Closing as this issue is resolved based on @max-arnold 's comment.
