### ISSUE TITLE
Feature Request: Salt-Cloud command line options for credentials

### ISSUE THREAD

**Issue by mattboston** [saltstack/salt#50935]
### Description of Issue/Question
Currently the way salt-cloud works, you need to specify credentials in the /etc/salt/cloud.providers.d files, meaning you need to either put your credentials or a shared account.  We are not allowed to put our account credentials or a shared/service accounts, and if we put our credentials in here it violates our company policies.

### Desired Result
Ability to leave credentials blank in the /etc/salt/cloud.providers.d, at which point two command line options will be required. Have two additional command line options for "username" and "password".  Password should prompt for password.

`salt-cloud -m /etc/salt/cloud.maps.d/prod.map --username "AD\username" --password`

**Comment by mattboston** [comment]
^^^ We use VMWare, so obviously use use Active Directory credentials.  For other cloud providers, there may be other options needed.

**Comment by Ch3LL** [comment]
this was added a long time ago: https://github.com/saltstack/salt/pull/12291

but it seems like it would need to be added per cloud driver. This was only added to openstack at the time

**Comment by Ch3LL** [comment]
you could also setup sdb with keyring

**Comment by mattboston** [comment]
Thanks. Closing ticket
