### ISSUE TITLE
salt-run jobs.list_jobs OOM

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#50931]
### Setup
My machine is a Virtual Machine with 16GB of memory, before calling jobs.list_jobs I have 15GB free.
I have 42 nodes connected on the Salt master.
I also use the returner pgjsonb (event_return and master_job_cache)

### Steps to Reproduce Issue
I query jobs list from yesterday and only one node match
```
salt-run jobs.list_jobs start_time='2018-12-20' search_target='tlsslt-p01-mst*'
```

It seems like all the data are get and python is filtering.

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.5
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.4.9 (default, Aug 14 2018, 21:28:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by Poil** [comment]
This seems to be already discussed here #21450 some work had been made but the discussion habe been closed before resolving all

**Comment by Poil** [comment]
I've wrote get_jids_filter but this does not fix my issue.
I think we need to add the ability to delegate the filtering to the returners, easy I think for postgresql and other databases that support json

**Comment by Ch3LL** [comment]
thanks for the PRs!

**Comment by Poil** [comment]
I've cleaned #50936, not sure if we can have a better code or not, perhaps a real developer can look at it :)

**Comment by Poil** [comment]
Also it should be possible to avoid this step "salt.utils.jid.format_jid_instance" by doing a select like 
```
SELECT 
                   jid, 
                   row_to_json(tmp) as load FROM (
                     SELECT
                       jid,
                       jid as "StartTime",
                       load->'fun' as "Function",
                       load->'arg' as "Arguments",
                       load->'tgt' as "Target",
                       load->'tgt_type' as "Target-type",
                       load->'user' as "User",
                       load->'metadata' as "Metadata"
                      FROM jids
```

**Comment by vangourd** [comment]
@Poil 

Can you try using this function in your api call? I have the same issue as you and discovered this by reading through the docs/repo again. 


https://github.com/saltstack/salt/blob/27ada9a0de1955fef5bf54a3dea12b13f62834e3/salt/runners/jobs.py#L377

**Comment by vangourd** [comment]
I am also having a memory issue with jobs.list_jobs when I perform queries. I believe it might be related so if you want me to do any testing that would be great.

My postulation was that each query of list_jobs will expand the amount of data that will be queried by the next (exponential? I can't remember) as list_job jobs are not filtered out by the query. 

Possibly a feature for this should be added as well to reduce the overhead of returning say the last 24 hours as well as duplicate return data for the last 10 checks on that data you did with jobs.list_jobs?

I'm a newbie here so I apologize if this is out of line. I can't find anything in the logs to describe what might be happening on the back-end so I'm just going off of what I read while reading through the functions in the repo.

**Comment by Poil** [comment]
You also need to patch salt/runners/jobs.py.
And yes only on master side, no need to restart the master to be taken into account (I don't understand why but ...)

**Comment by vangourd** [comment]
I'll keep testing but my queries were taking in the order of minutes if they completed at all before the server would OOM crash.

With your patch I'm getting queries back almost immediately and so far no OOM issues.

I'll keep monitoring to see if anything pops up.  @Poil 👏 you rock
