### ISSUE TITLE
External Pillar documentation typo

### ISSUE THREAD

**Issue by Hipska** [saltstack/salt#50932]
On [doc/topics/development/external_pillars.rst](https://github.com/saltstack/salt/blame/develop/doc/topics/development/external_pillars.rst#L156) there is a missing `{` in the example of `ext_pillar`:
```py
ext_pillar( id, pillar, keyA='valueA', keyB='valueB' } )    # example_c
```
I guess it needs to be before `keyA`?

**Comment by Hipska** [comment]
Hi @Ch3LL, I have seen your commit referencing this issue. Is it now solved and can this one be closed?

**Comment by Ch3LL** [comment]
yep :)
