### ISSUE TITLE
NoneType object has no attribute 'lower'

### ISSUE THREAD

**Issue by 519seven** [saltstack/salt#50942]
### Description of Issue/Question
Functionality isn't broken, I just can't get a salt run without error count being equal to 1.

I am receiving this error on only one out of many pip packages:

```
          ID: pip-deps
    Function: pip.installed
        Name: python
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1913, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/pip_state.py", line 910, in installed
                  if pkg_name.lower() in already_installed_packages:
              AttributeError: 'NoneType' object has no attribute 'lower'
     Started: 13:14:27.731677
    Duration: 1944.946 ms
     Changes:

```

### Setup
State file: 
```
pip-deps:
  pip.installed:
    - names:
      - nose
      - mock
      - redis
      - pyyaml
      - coverage
      - gitpython
      - python
      - python-redis
      - nose-exclude
```
Other packages that are already installed are returned as being installed as you can see here (compare inclusion of "coverage" and "gitpython" in pip.packages above to output below):
```
          ID: pip-deps
    Function: pip.installed
        Name: coverage
      Result: True
     Comment: Python package coverage was already installed
              All specified packages are already installed
     Started: 13:14:26.692770
    Duration: 512.597 ms
     Changes:
----------
          ID: pip-deps
    Function: pip.installed
        Name: gitpython
      Result: True
     Comment: Python package gitpython was already installed
              All specified packages are already installed
     Started: 13:14:27.205854
    Duration: 525.234 ms
     Changes:
```
But only the python package is throwing this error.

### Steps to Reproduce Issue
1.)  Run salt against your minion and include the pip.packages clause above, specifically "python".
2.)  Make sure your minion already has python installed (via pip):
```
[devopsuser@slave-salttesting-pja01 ~]$ pip install python
Requirement already satisfied: python in /usr/lib64/python2.7/lib-dynload
You are using pip version 9.0.3, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```
My minion is a CentOS 7.4.1708 machine.

### Versions Report
**Master**:
```
[root@foreman-staging config-mgmt]# salt --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

```
**Minion**:
```
[devopsuser@slave-salttesting-pja01 ~]$ salt-call --version
salt-call 2018.3.3 (Oxygen)
[devopsuser@slave-salttesting-pja01 ~]$ salt-minion --version
salt-minion 2018.3.3 (Oxygen)
```

**Comment by whytewolf** [comment]
This would never work. `python` is not a pip package. It only gets listed when you run pip install but doesn't show up in a pip list or pip freeze which is the part that is used to check if a package is installed. But in order to even use pip python has to already be installed.

**Comment by terminalmage** [comment]
@whytewolf is right, but we still shouldn't be throwing a traceback here. https://github.com/saltstack/salt/pull/50963 fixes this.

**Comment by 519seven** [comment]
Hi, @whytewolf 

I thought this was rather strange - pip installing python.  The angle I'm coming from is simply this: I'm maintaining a script that is known to work for my team.  The team has a work-around in place for this specific error and I'd rather get the error resolved so our error count is nil.  After what you have pointed out, I will be removing "python" from the list because why in the hell is it there?  I really don't know and believe it or not, I thought about removing it.  It was easier to open a ticket with you than to open a ticket to get "python" removed from the list :D  But like @terminalmage says, it would probably be good to fix the traceback.

Thanks, everybody for taking the time to respond to my nonsensical use of your tool!
