### ISSUE TITLE
Does salt has rpm auto-build script？How to build rpm package?

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#50956]
### Description of Issue/Question
We modify some salt codes and want to re-build rpm package, does salt has rpm auto-build script?

**Comment by dwoz** [comment]
Hi @andyyumiao Good question, I think @dmurphy18 will be able to answer this.

**Comment by andyyumiao** [comment]
> Hi @andyyumiao Good question, I think @dmurphy18 will be able to answer this.

Hi @dwoz, I just know /pkg/rpm/build.py can do this, thank you.

**Comment by dmurphy18** [comment]
@andyyumiao Take a look at salt-pack or salt-pack-py3, or salt-auto-pack for how the nightly build packages are built, all are open-source on GitHub

The Salt spec files are in salt-pack and salt-pack-py3, for example:

salt c7m state.sls setup.redhat.rhel7  pillar='{ "build_dest" : "/srv/redhat/2019.2/pkgs", "build_version" : "2019_2" }'
salt c7m state.sls pkg.salt.2019_2.rhel7  pillar='{ "build_dest" : "/srv/redhat/2019.2/pkgs", "build_version" : "2019_2" }'
salt c7m state.highstate  pillar='{ "build_dest" : "/srv/redhat/2019.2/pkgs", "build_version" : "2019_2" }'
salt c7m state.sls repo.redhat.rhel7  pillar='{ "build_dest" : "/srv/redhat/2019.2/pkgs", "keyid" : "your-key-here", "build_version" : "2019_2" , "gpg_passphrase" : "fill-in here" }'

salt c7m state.sls setup.redhat.rhel7  pillar='{ "build_dest" : "/srv/redhat/2019.2/pkgs", "build_version" : "2019_2", "build_py3" : True }'
salt c7m state.sls pkg.salt.2019_2.rhel7  pillar='{ "build_dest" : "/srv/redhat/2019.2/pkgs", "build_version" : "2019_2", "build_py3" : True }'
salt c7m state.highstate  pillar='{ "build_dest" : "/srv/redhat/2019.2/pkgs", "build_version" : "2019_2", "build_py3" : True }'
salt c7m state.sls repo.redhat.rhel7  pillar='{ "build_dest" : "/srv/redhat/2019.2/pkgs", "keyid" : "your-key-here", "build_version" : "2019_2", "build_py3" : True , "gpg_passphrase" : "fill-in here" }'
