### ISSUE TITLE
Possible version incompatibility in `cp` module

### ISSUE THREAD

**Issue by furgerf** [saltstack/salt#50955]
### Description of Issue/Question
I'm retrieving files on master from several minions using `cp.push_dir`, which doesn't seem to work with old minions.

Unfortunately, we are currently running a mix of versions: The master is 2017.7.8, while the minions are either 2015.8.1, 2017.7.2, 2017.7.3, or 2018.3.3. However, I noticed that `cp.push_dir` doesn't seem to work with minions of version 2015.8.1 - I didn't find any relevant output in the logs, it seems to fail silently.

For testing, I updated one of the 2015.8.1-minions to 2018.3.3, without changing anything else: afterwards, it worked.

The  [docu](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cp.html#salt.modules.cp.push_dir) states that `cp.push_dir` was introduced with 2014.7.0 so I assumed it would also work with 2015.8.1 - is there some known problem? Maybe something that is fixed in the meantime, but means that such an old minion is incompatible with a "reasonably-recent" master?

### Versions Report
```
Salt Version:
           Salt: 2017.7.8

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 13 2018, 12:45:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: Ubuntu 14.04 trusty
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.19.0-80-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by dwoz** [comment]
Hi @furgerf 

In many cases older minions will work with the new master. In this case however it's likely that something changed causing `cp.push` to break. This is likely because the master is a major version newer. 2015.8.x is on 'CVE only' which means we're only fixing security issues. So, it's probably best to upgrade those minions if possible. 

In addition, I noticed some of your minions are running the 2018.3 release which is newer than your master. This configuration is not supported at this time.

**Comment by dwoz** [comment]
There is this issue: https://github.com/saltstack/salt/issues/37133

**Comment by furgerf** [comment]
Thanks for your reply @dwoz. I'm not expecting a fix - I'm not surprised that this old version isn't supported :smile:  I don't know how you usually handle that, I thought maybe you might want to add a note to the documentation or so.

In the meantime, I found something about minion-master compatibility in the [FAQ](https://docs.saltstack.com/en/latest/faq.html#can-i-run-different-versions-of-salt-on-my-master-and-minion): basically, any non-matching versions aren't guaranteed to be compatible. However, are there some more practical guidelines? For instance, can I restrict myself to only upgrade major versions? Unfortunately, many of our minions aren't trivial to reach and upgrade.
