### ISSUE TITLE
Freshly installed distro packaged `salt-master` fails to run on clean Ubuntu Cosmic install

### ISSUE THREAD

**Issue by bwesterb** [saltstack/salt#50967]
### Description of Issue/Question
When `salt-master` is installed on a clean Ubuntu Cosmic, it fails to start with the error `salt-master: error: Failed to load configuration: unknown error (_ssl.c:2788)`.  This bug also occurred on Debian testing and [filed](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910236), but didn't gain traction.  (Note that [your website](https://docs.saltstack.com/en/latest/topics/installation/ubuntu.html) advices to install Ubuntu's own packages.)

### Steps to Reproduce Issue
`apt-get install salt-master` on Ubuntu Cosmic.

To conveniently reproduce, you can use [Vagrant](https://www.vagrantup.com) with the following `Vagrantfile`

```
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/cosmic64"

  config.vm.provision "shell", inline: <<-SHELL
    apt-get update
    apt-get install -y salt-master
  SHELL
end
```

### Versions Report
```
vagrant@ubuntu-cosmic:~$ salt --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python3/dist-packages/salt/scripts.py", line 476, in salt_main
    client.run()
  File "/usr/lib/python3/dist-packages/salt/cli/salt.py", line 33, in run
    import salt.client
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 31, in <module>
    import salt.cache
  File "/usr/lib/python3/dist-packages/salt/cache/__init__.py", line 18, in <module>
    import salt.loader
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 26, in <module>
    import salt.utils.event
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 70, in <module>
    import tornado.iostream
  File "/usr/lib/python3/dist-packages/tornado/iostream.py", line 40, in <module>
    from tornado.netutil import ssl_wrap_socket, _client_ssl_defaults, _server_ssl_defaults
  File "/usr/lib/python3/dist-packages/tornado/netutil.py", line 45, in <module>
    ssl.Purpose.SERVER_AUTH)
  File "/usr/lib/python3.6/ssl.py", line 502, in create_default_context
    context = SSLContext(PROTOCOL_TLS)
  File "/usr/lib/python3.6/ssl.py", line 391, in __new__
    self = _SSLContext.__new__(cls, protocol)
ssl.SSLError: unknown error (_ssl.c:2788)
```

The installed package is `salt-master 2017.7.4+dfsg1-1`.

### Other distro's / versions
* The issue does not occur on Debian Stretch.  (It installs `salt-master 2016.11.2+ds-1+deb9u2`.)
* I couldn't check Debian Testing, as it won't install salt-master due to a dependency conflict involving tornado.
* The issue does not occur on Ubuntu Bionic. (It installs `salt-master 2017.7.4+dfsg1-1` as well!)

**Comment by garethgreenaway** [comment]
@dmurphy18 FYI.

**Comment by dmurphy18** [comment]
@bwesterb This is due to Salt is not able to function correctly with python-tornado > 5 using Python 3.
Salt support for python-tornado >= 5 in Python 3 environments is being actively worked on, but there is no time frame as to when this will be resolved.  Currently targeting the Neon Release, and possible back-port to earlier releases but that is dependent on the final solution to the issue.

Also see https://github.com/saltstack/salt-pack-py3/issues/116 since this affects Fedora, upcoming Buster and RHEL 8  releases too.

If this information is sufficient, please close the issue. You can track the solution by following the issue above, since once the fix is available, it will be done for all of those platforms.

**Comment by bwesterb** [comment]
Is it possible at all to run salt on Ubuntu Cosmic?

**Comment by dmurphy18** [comment]
@bwesterb There is a version of Salt which Debian / Ubuntu ship with the OS, Salt 2017.7.4+ds-xxxx , note that this version of the branch has entered CVE-only support and doesn't support Python3 well, full Python 3 support did not occur until branch 2018.3.  However you should be able to do most things with that version of Salt with Python 2.

Note that with the upcoming Buster, Debian Salt has a version of python-tornado4 which works with the version of Salt that they provide and can co-exist with the regular python-tornado v5.  In Buster, the version of Salt provided by Debian is 2018.3.4+ds-xxxx.  Hence you could install these from the Debian testing repo as a stop gap solution until SaltStack Salt fully supports python-tornado v5 or greater.

**Comment by bwesterb** [comment]
It's fixed in Ubuntu Disco.
