### ISSUE TITLE
2018.3.3 missing a patch to salt/modules/nxos.py

### ISSUE THREAD

**Issue by klafkoff** [saltstack/salt#50966]
### Description of Issue/Question
Running `salt cisco.switch.blah nxos.cmd show_ver`

I found this error

`cisco.switch.blah:`
`    The minion function caused an exception: Traceback (most recent call last):`
`     File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1607, in _thread_return`
`        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)`
`      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute`
`        return func(*args, **kwargs)`
`      File "/usr/lib/python2.7/site-packages/salt/modules/nxos.py", line 62, in cmd`
`        for k in kwargs:`
`    RuntimeError: dictionary changed size during iteration`

I found this patch for a different module, applied it to nxos.py manually, and it resolved the issue -- https://github.com/rallytime/salt/commit/430c462f34eb4eedf2384e06fbee8dc19b8026f6

This is fixed in the develop branch

**Comment by garethgreenaway** [comment]
@klafkoff Thanks for the report.  It appears that that change is present in the 2018.3.3 tag, https://github.com/saltstack/salt/blob/v2018.3.3/salt/proxy/fx2.py#L331.  Can you confirm that you have the 2018.3.3 installed with salt --version-report?  Thanks!

**Comment by klafkoff** [comment]
This is for salt/modules/nxos.py ---- not ---- salt/proxy/fx2.py. 

What I am saying is: the patch for the fx2.py resolved the issue with the cisco nexus bug -- that I opened this issue about.

**Comment by UtahDave** [comment]
This is fixed by https://github.com/saltstack/salt/pull/51080
