### ISSUE TITLE
Saltstack RHEL6 python27-requests removes the OS default python-requests

### ISSUE THREAD

**Issue by dbond4r** [saltstack/salt#50965]
### Description of Issue/Question

When installing salt-minion from the Saltstack repo for RHEL/centOS6 x86_64 the OS default python-requests RPM was removed and replaced with localized python27-requests braking scripts depending on it.

### Setup

$ cat /etc/redhat-release 
CentOS release 6.4 (Final)

$ yum info  python-requests
Available Packages
Name        : python-requests
Arch        : noarch
Version     : 2.6.0
Release     : 4.el6
Size        : 96 k
Repo        : base
Summary     : HTTP library, written in Python, for human beings
URL         : http://pypi.python.org/pypi/requests
License     : ASL 2.0
Description : Most existing Python modules for sending HTTP requests are extremely verbose and
            : cumbersome. Python’s built-in urllib2 module provides most of the HTTP
            : capabilities you should need, but the API is thoroughly broken. This library is
            : designed to make HTTP requests easy for developers.

$ cat /etc/yum.repos.d/salt-latest.repo 
[salt-latest]
name=SaltStack Latest Release Channel for RHEL/Centos $releasever
baseurl=https://repo.saltstack.com/yum/redhat/$releasever/$basearch/latest
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/saltstack-signing-key

$ rpm -qa --qf '[%{obsoletes}\n]' python27-requests 
python-requests

### Steps to Reproduce Issue

   yum install -y https://repo.saltstack.com/yum/redhat/salt-repo-latest-1.el5.noarch.rpm
   yum install -y  salt-minion

Loaded plugins: fastestmirror, presto
Loading mirror speeds from cached hostfile
 * base: mirror.vcu.edu
 * epel: reflector.westga.edu
 * epel-testing: reflector.westga.edu
 * extras: mirrors.advancedhosters.com
 * rpmforge: mirror.teklinks.com
 * updates: mirror.ash.fastserv.com
Setting up Install Process
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:2018.3.3-1.el6 will be installed
--> Processing Dependency: salt = 2018.3.3-1.el6 for package: salt-minion-2018.3.3-1.el6.noarch
--> Processing Dependency: /usr/bin/python2.7 for package: salt-minion-2018.3.3-1.el6.noarch
--> Running transaction check
---> Package python27.x86_64 0:2.7.13-3.ius.el6 will be installed
--> Processing Dependency: python27-libs(x86-64) = 2.7.13-3.ius.el6 for package: python27-2.7.13-3.ius.el6.x86_64
--> Processing Dependency: libpython2.7.so.1.0()(64bit) for package: python27-2.7.13-3.ius.el6.x86_64
---> Package salt.noarch 0:2018.3.3-1.el6 will be installed
--> Processing Dependency: python27-tornado < 6.0 for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-tornado >= 4.2.1 for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-requests >= 1.0.0 for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-msgpack >= 0.4 for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-futures >= 2.0 for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-crypto >= 2.6.1 for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-zmq for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-six for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-psutil for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-markupsafe for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: python27-jinja2 for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: pciutils for package: salt-2018.3.3-1.el6.noarch
--> Processing Dependency: PyYAML27 for package: salt-2018.3.3-1.el6.noarch
--> Running transaction check
---> Package PyYAML27.x86_64 0:3.11-3.el6 will be installed
--> Processing Dependency: libyaml-0.so.2()(64bit) for package: PyYAML27-3.11-3.el6.x86_64
---> Package pciutils.x86_64 0:3.1.10-4.el6 will be installed
--> Processing Dependency: pciutils-libs = 3.1.10-4.el6 for package: pciutils-3.1.10-4.el6.x86_64
---> Package python-requests.noarch 0:2.6.0-4.el6 will be obsoleted
---> Package python27-crypto.x86_64 0:2.6.1-5.el6 will be installed
---> Package python27-futures.noarch 0:3.0.3-3.el6 will be installed
---> Package python27-jinja2.noarch 0:2.8.1-3.el6 will be installed
--> Processing Dependency: python27-babel >= 0.8 for package: python27-jinja2-2.8.1-3.el6.noarch
---> Package python27-libs.x86_64 0:2.7.13-3.ius.el6 will be installed
---> Package python27-markupsafe.x86_64 0:0.11-12.el6 will be installed
---> Package python27-msgpack.x86_64 0:0.4.6-3.el6 will be installed
---> Package python27-psutil.x86_64 0:5.4.2-1.ius.el6 will be installed
---> Package python27-requests.noarch 0:2.20.1-2.el6 will be obsoleting
--> Processing Dependency: python27-urllib3 >= 1.23 for package: python27-requests-2.20.1-2.el6.noarch
--> Processing Dependency: python27-chardet >= 3.0.4 for package: python27-requests-2.20.1-2.el6.noarch
--> Processing Dependency: python27-idna for package: python27-requests-2.20.1-2.el6.noarch
---> Package python27-six.noarch 0:1.9.0-4.el6 will be installed
---> Package python27-tornado.x86_64 0:4.2.1-4.el6 will be installed
--> Processing Dependency: python27-pycurl for package: python27-tornado-4.2.1-4.el6.x86_64
---> Package python27-zmq.x86_64 0:14.5.0-4.el6 will be installed
--> Processing Dependency: libzmq.so.4()(64bit) for package: python27-zmq-14.5.0-4.el6.x86_64
--> Running transaction check
---> Package libyaml.x86_64 0:0.1.4-1.el6.rf will be installed
---> Package pciutils-libs.x86_64 0:3.1.10-2.el6 will be updated
---> Package pciutils-libs.x86_64 0:3.1.10-4.el6 will be an update
---> Package python-urllib3.noarch 0:1.10.2-3.el6 will be obsoleted
---> Package python27-babel.noarch 0:0.9.4-5.3.el6 will be installed
---> Package python27-chardet.noarch 0:3.0.4-8.el6 will be installed
---> Package python27-idna.noarch 0:2.7-4.el6 will be installed
---> Package python27-pycurl.x86_64 0:7.19.0-11.el6 will be installed
---> Package python27-urllib3.noarch 0:1.23-5.el6 will be obsoleting
--> Processing Dependency: python27-pysocks for package: python27-urllib3-1.23-5.el6.noarch
--> Processing Dependency: python27-ipaddress for package: python27-urllib3-1.23-5.el6.noarch
--> Processing Dependency: python27-backports-ssl_match_hostname for package: python27-urllib3-1.23-5.el6.noarch
---> Package zeromq.x86_64 0:4.0.5-4.el6 will be installed
--> Running transaction check
---> Package python27-backports-ssl_match_hostname.noarch 0:3.4.0.2-4.el6 will be installed
--> Processing Dependency: python27-backports for package: python27-backports-ssl_match_hostname-3.4.0.2-4.el6.noarch
---> Package python27-ipaddress.noarch 0:1.0.18-6.el6 will be installed
---> Package python27-pysocks.noarch 0:1.6.8-7.el6 will be installed
--> Running transaction check
---> Package python27-backports.x86_64 0:1.0-7.el6 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

================================================================================
 Package                              Arch   Version          Repository   Size
================================================================================
Installing:
 python27-requests                    noarch 2.20.1-2.el6     salt-latest 120 k
     replacing  python-requests.noarch 2.6.0-4.el6
 python27-urllib3                     noarch 1.23-5.el6       salt-latest 180 k
     replacing  python-urllib3.noarch 1.10.2-3.el6
 salt-minion                          noarch 2018.3.3-1.el6   salt-latest  38 k
Installing for dependencies:
 PyYAML27                             x86_64 3.11-3.el6       salt-latest 152 k
 libyaml                              x86_64 0.1.4-1.el6.rf   rpmforge    107 k
 pciutils                             x86_64 3.1.10-4.el6     base         85 k
 python27                             x86_64 2.7.13-3.ius.el6 salt-latest  82 k
 python27-babel                       noarch 0.9.4-5.3.el6    salt-latest 1.4 M
 python27-backports                   x86_64 1.0-7.el6        salt-latest 5.1 k
 python27-backports-ssl_match_hostname
                                      noarch 3.4.0.2-4.el6    salt-latest  11 k
 python27-chardet                     noarch 3.0.4-8.el6      salt-latest 188 k
 python27-crypto                      x86_64 2.6.1-5.el6      salt-latest 501 k
 python27-futures                     noarch 3.0.3-3.el6      salt-latest  27 k
 python27-idna                        noarch 2.7-4.el6        salt-latest 102 k
 python27-ipaddress                   noarch 1.0.18-6.el6     salt-latest  36 k
 python27-jinja2                      noarch 2.8.1-3.el6      salt-latest 284 k
 python27-libs                        x86_64 2.7.13-3.ius.el6 salt-latest 5.6 M
 python27-markupsafe                  x86_64 0.11-12.el6      salt-latest  24 k
 python27-msgpack                     x86_64 0.4.6-3.el6      salt-latest  69 k
 python27-psutil                      x86_64 5.4.2-1.ius.el6  salt-latest 383 k
 python27-pycurl                      x86_64 7.19.0-11.el6    salt-latest  76 k
 python27-pysocks                     noarch 1.6.8-7.el6      salt-latest  30 k
 python27-six                         noarch 1.9.0-4.el6      salt-latest  28 k
 python27-tornado                     x86_64 4.2.1-4.el6      salt-latest 660 k
 python27-zmq                         x86_64 14.5.0-4.el6     salt-latest 478 k
 salt                                 noarch 2018.3.3-1.el6   salt-latest 9.2 M
 zeromq                               x86_64 4.0.5-4.el6      salt-latest 568 k
Updating for dependencies:
 pciutils-libs                        x86_64 3.1.10-4.el6     base         34 k

Transaction Summary
================================================================================
Install      27 Package(s)
Upgrade       1 Package(s)

Total download size: 20 M
Downloading Packages:
Setting up and reading Presto delta metadata
Processing delta metadata
Package(s) data still to download: 20 M
--------------------------------------------------------------------------------
Total                                           8.9 MB/s |  20 MB     00:02     
Running rpm_check_debug
Running Transaction Test
Transaction Test Succeeded
Running Transaction
  Installing : python27-libs-2.7.13-3.ius.el6.x86_64                       1/31 
  Installing : python27-2.7.13-3.ius.el6.x86_64                            2/31 
  Installing : python27-markupsafe-0.11-12.el6.x86_64                      3/31 
  Installing : python27-six-1.9.0-4.el6.noarch                             4/31 
  Installing : python27-psutil-5.4.2-1.ius.el6.x86_64                      5/31 
  Installing : python27-chardet-3.0.4-8.el6.noarch                         6/31 
  Installing : python27-futures-3.0.3-3.el6.noarch                         7/31 
  Installing : python27-idna-2.7-4.el6.noarch                              8/31 
  Installing : python27-pycurl-7.19.0-11.el6.x86_64                        9/31 
  Installing : python27-tornado-4.2.1-4.el6.x86_64                        10/31 
  Installing : python27-pysocks-1.6.8-7.el6.noarch                        11/31 
  Installing : python27-ipaddress-1.0.18-6.el6.noarch                     12/31 
  Installing : python27-crypto-2.6.1-5.el6.x86_64                         13/31 
  Installing : python27-babel-0.9.4-5.3.el6.noarch                        14/31 
  Installing : python27-jinja2-2.8.1-3.el6.noarch                         15/31 
  Installing : python27-msgpack-0.4.6-3.el6.x86_64                        16/31 
  Installing : python27-backports-1.0-7.el6.x86_64                        17/31 
  Installing : python27-backports-ssl_match_hostname-3.4.0.2-4.el6.noar   18/31 
  Installing : python27-urllib3-1.23-5.el6.noarch                         19/31 
  Installing : python27-requests-2.20.1-2.el6.noarch                      20/31 
  Installing : libyaml-0.1.4-1.el6.rf.x86_64                              21/31 
  Installing : PyYAML27-3.11-3.el6.x86_64                                 22/31 
  Installing : zeromq-4.0.5-4.el6.x86_64                                  23/31 
  Installing : python27-zmq-14.5.0-4.el6.x86_64                           24/31 
  Updating   : pciutils-libs-3.1.10-4.el6.x86_64                          25/31 
  Installing : pciutils-3.1.10-4.el6.x86_64                               26/31 
  Installing : salt-2018.3.3-1.el6.noarch                                 27/31 
  Installing : salt-minion-2018.3.3-1.el6.noarch                          28/31 
  Erasing    : python-requests-2.6.0-4.el6.noarch                         29/31 
  Erasing    : python-urllib3-1.10.2-3.el6.noarch                         30/31 
  Cleanup    : pciutils-libs-3.1.10-2.el6.x86_64                          31/31 
  Verifying  : python27-urllib3-1.23-5.el6.noarch                          1/31 
  Verifying  : salt-minion-2018.3.3-1.el6.noarch                           2/31 
  Verifying  : python27-psutil-5.4.2-1.ius.el6.x86_64                      3/31 
  Verifying  : salt-2018.3.3-1.el6.noarch                                  4/31 
  Verifying  : python27-chardet-3.0.4-8.el6.noarch                         5/31 
  Verifying  : pciutils-3.1.10-4.el6.x86_64                                6/31 
  Verifying  : python27-markupsafe-0.11-12.el6.x86_64                      7/31 
  Verifying  : python27-2.7.13-3.ius.el6.x86_64                            8/31 
  Verifying  : python27-six-1.9.0-4.el6.noarch                             9/31 
  Verifying  : pciutils-libs-3.1.10-4.el6.x86_64                          10/31 
  Verifying  : python27-backports-ssl_match_hostname-3.4.0.2-4.el6.noar   11/31 
  Verifying  : python27-futures-3.0.3-3.el6.noarch                        12/31 
  Verifying  : python27-idna-2.7-4.el6.noarch                             13/31 
  Verifying  : python27-pycurl-7.19.0-11.el6.x86_64                       14/31 
  Verifying  : python27-pysocks-1.6.8-7.el6.noarch                        15/31 
  Verifying  : python27-ipaddress-1.0.18-6.el6.noarch                     16/31 
  Verifying  : python27-requests-2.20.1-2.el6.noarch                      17/31 
  Verifying  : PyYAML27-3.11-3.el6.x86_64                                 18/31 
  Verifying  : python27-jinja2-2.8.1-3.el6.noarch                         19/31 
  Verifying  : zeromq-4.0.5-4.el6.x86_64                                  20/31 
  Verifying  : python27-crypto-2.6.1-5.el6.x86_64                         21/31 
  Verifying  : python27-babel-0.9.4-5.3.el6.noarch                        22/31 
  Verifying  : python27-zmq-14.5.0-4.el6.x86_64                           23/31 
  Verifying  : python27-tornado-4.2.1-4.el6.x86_64                        24/31 
  Verifying  : python27-libs-2.7.13-3.ius.el6.x86_64                      25/31 
  Verifying  : libyaml-0.1.4-1.el6.rf.x86_64                              26/31 
  Verifying  : python27-msgpack-0.4.6-3.el6.x86_64                        27/31 
  Verifying  : python27-backports-1.0-7.el6.x86_64                        28/31 
  Verifying  : pciutils-libs-3.1.10-2.el6.x86_64                          29/31 
  Verifying  : python-urllib3-1.10.2-3.el6.noarch                         30/31 
  Verifying  : python-requests-2.6.0-4.el6.noarch                         31/31 

Installed:
  python27-requests.noarch 0:2.20.1-2.el6  python27-urllib3.noarch 0:1.23-5.el6 
  salt-minion.noarch 0:2018.3.3-1.el6     

Dependency Installed:
  PyYAML27.x86_64 0:3.11-3.el6                                                  
  libyaml.x86_64 0:0.1.4-1.el6.rf                                               
  pciutils.x86_64 0:3.1.10-4.el6                                                
  python27.x86_64 0:2.7.13-3.ius.el6                                            
  python27-babel.noarch 0:0.9.4-5.3.el6                                         
  python27-backports.x86_64 0:1.0-7.el6                                         
  python27-backports-ssl_match_hostname.noarch 0:3.4.0.2-4.el6                  
  python27-chardet.noarch 0:3.0.4-8.el6                                         
  python27-crypto.x86_64 0:2.6.1-5.el6                                          
  python27-futures.noarch 0:3.0.3-3.el6                                         
  python27-idna.noarch 0:2.7-4.el6                                              
  python27-ipaddress.noarch 0:1.0.18-6.el6                                      
  python27-jinja2.noarch 0:2.8.1-3.el6                                          
  python27-libs.x86_64 0:2.7.13-3.ius.el6                                       
  python27-markupsafe.x86_64 0:0.11-12.el6                                      
  python27-msgpack.x86_64 0:0.4.6-3.el6                                         
  python27-psutil.x86_64 0:5.4.2-1.ius.el6                                      
  python27-pycurl.x86_64 0:7.19.0-11.el6                                        
  python27-pysocks.noarch 0:1.6.8-7.el6                                         
  python27-six.noarch 0:1.9.0-4.el6                                             
  python27-tornado.x86_64 0:4.2.1-4.el6                                         
  python27-zmq.x86_64 0:14.5.0-4.el6                                            
  salt.noarch 0:2018.3.3-1.el6                                                  
  zeromq.x86_64 0:4.0.5-4.el6                                                   

Dependency Updated:
  pciutils-libs.x86_64 0:3.1.10-4.el6                                           

Replaced:
  python-requests.noarch 0:2.6.0-4.el6   python-urllib3.noarch 0:1.10.2-3.el6  

Complete!

### Versions Report

$ salt-minion --versions-report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.4 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-358.23.2.el6.x86_64
         system: Linux
        version: CentOS 6.4 Final

**Comment by 4815162342lost** [comment]
Hello,

I believe it must be p1 (critical) incident.

```
[root@host: ~]# python
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> exit()


[root@host: ~]# yum update
==============================================================================================================================================================================================
 Package                                                        Arch                            Version                                        Repository                                Size
==============================================================================================================================================================================================
Installing:
 kernel                                                         x86_64                          2.6.32-754.9.1.el6                             CentOS_updates                            32 M
 python27-requests                                              noarch                          2.20.1-2.el6                                   saltstack-repo                           120 k
     replacing  python-requests.noarch 2.6.0-4.el6
 python27-urllib3                                               noarch                          1.23-5.el6                                     saltstack-repo                           180 k
     replacing  python-urllib3.noarch 1.10.2-3.el6
Updating:
 autofs                                                         x86_64                          1:5.0.5-140.el6_10                             CentOS_updates                           730 k
 ghostscript                                                    x86_64                          8.70-24.el6_10.2                               CentOS_updates                           4.4 M
 kernel-firmware                                                noarch                          2.6.32-754.9.1.el6                             CentOS_updates                            29 M
 kernel-headers                                                 x86_64                          2.6.32-754.9.1.el6                             CentOS_updates                           4.5 M
 ntp                                                            x86_64                          4.2.6p5-15.el6.centos                          CentOS_updates                           600 k
 ntpdate                                                        x86_64                          4.2.6p5-15.el6.centos                          CentOS_updates                            79 k
 perf                                                           x86_64                          2.6.32-754.9.1.el6                             CentOS_updates                           4.7 M
 python27-chardet                                               noarch                          3.0.4-8.el6                                    saltstack-repo                           188 k
Removing:
 kernel                                                         x86_64                          2.6.32-754.3.5.el6                             @CentOS_updates                          133 M
Installing for dependencies:
 python27-backports                                             x86_64                          1.0-7.el6                                      saltstack-repo                           5.1 k
 python27-backports-ssl_match_hostname                          noarch                          3.4.0.2-4.el6                                  saltstack-repo                            11 k
 python27-idna                                                  noarch                          2.7-4.el6                                      saltstack-repo                           102 k
 python27-ipaddress                                             noarch                          1.0.18-6.el6                                   saltstack-repo                            36 k
 python27-pysocks     
 
 
 [root@host: ~]# python
Python 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named requests
>>> exit()
```


Server's patching can rouine an application which use standard python.

**Comment by Poil** [comment]
(Same?) Bug on EL7 : #49928

**Comment by garethgreenaway** [comment]
@dmurphy18 FYI.

**Comment by msciciel** [comment]
The same problem for  `salt-minion-2017.7.8`. It breaks system `python 2.6` and it is a critical issue.

**Comment by dmurphy18** [comment]
@msciciel Thanks for the information, and it has been fixed for python17-requests and python27-urllib3. They will be available with the next point releases/

**Comment by 4815162342lost** [comment]
Hello @dmurphy18,

Sorry, but i do not fully understand you. Why issue can not be fixed ASAP right now? From my point of view issue is very critical and must be fixed immediately.  The issue can break critical applications on prod-systems. Salt is 'prod-ready' tool.

Sorry for pushing you, but i am confused.

Have a nice week!

**Comment by damon-atkins** [comment]
I suspect the solution is to copy the salt rpm only and create your own repo.  You should always mirror/copy upstream repo, so you can control the content.  Then update will not find the salt versions of request etc.

**Comment by damon-atkins** [comment]
PS I think salt should split the repo into pure salt and dependency

**Comment by 4815162342lost** [comment]
Hello @damon-atkins, 

Thanks for your advises. But as far as i know sometimes salt can require python-libs which is not exist  in official distro-repository.  And due to this ' salt rpm only' is not suitable. 

Also i am not fully agree with you, salt should be stable and prod-ready tool, salt-users should not 'play' with private repository. Official repository should be stable and 100% safely. Otherwise users will choose a  competing products (ansible and etc.).

We are using salt on prod-environment (500+ crit. systems) 3+ years and we want to continue to use salt, because salt is really great tool.

**Comment by damon-atkins** [comment]
Several reason to have your own repo.  Salt one is down, or gets hacked, speed of a local download is faster, there is no SLA for salt repo.  Most companies have proxies which may or may not be HA. Many reason to mirror a repo internally.

Take the rpm you need, which are not available for RHEL, create a repo and see how you go.

When puppet was pure ruby it split the puppet repo from the dependency repo.

> salt-users must not 'play' with private repository. 

this seems odd statement to make with complaints salt replaces the os versions of rpms.

This is the only specific version requirements for RHEL 7
```
 yum deplist salt | egrep '<|>|='
  dependency: python(abi) = 2.7
  dependency: python-crypto >= 2.6.1
  dependency: python-futures >= 2.0
  dependency: python-msgpack >= 0.4
  dependency: python-requests >= 1.0.0
  dependency: python-tornado >= 4.2.1
  dependency: python-tornado < 6.0
```
For RHEL 6 it is from [here](https://github.com/saltstack/salt-pack/blob/develop/file_roots/pkg/salt/2019_2/rhel6/spec/salt.spec)
```
BuildRequires: python%{?__python_ver}-tornado >= 4.2.1
BuildRequires: python%{?__python_ver}-futures >= 2.0
BuildRequires: python%{?__python_ver}-crypto >= 2.6.1
BuildRequires: python%{?__python_ver}-jinja2
BuildRequires: python%{?__python_ver}-msgpack >= 0.4
BuildRequires: python%{?__python_ver}-pip
BuildRequires: python%{?__python_ver}-zmq >= 14.5
```

Again the issues would be solved if pure salt rpm were in a repo by them selves and the dependency repo optional.  You need to look at the dependency (version), I suspect you will find RHEL rpm do not need to be updated.

**Comment by dmurphy18** [comment]
@4815162342lost @damon-atkins I understand your desire for an immediate solution and fix, however, the reason for the delay is due to limited pipeline. Fluorine RC1 (2019.2.0rc1) should be released today, following that work on 2018.3.4 point release should start.  That is, busy getting the Release Candidate out, and then on to the next point release for the 2018.3 branch which will contain your desired fixes.

SaltStack has considered separate repo's for Salt and dependencies, but issues are complicated with the looming end-of-life for Python 2.7 and how to support older Python 2.7 client while still being able to move forward with Python 3 features, given that RHEL 7 and Amazon Linux 2 will be supporting Python 2.7 for some years to come.  The final solution has not been made, but have made not of your recommendation.

@4815162342lost Hoping your patience can extend a little longer but SaltStack should have a solution for you soon.

**Comment by dmurphy18** [comment]
@4815162342lost @damon-atkins With the recent release of 2018.3.4 and 2019.2.0, can you check that your issue is resolved.
Thanks

**Comment by dmurphy18** [comment]
Closing this but feel free to re-open if the problem re-occurs
