### ISSUE TITLE
cmd.run Failing when command contains braces ( )

### ISSUE THREAD

**Issue by nkv16786** [saltstack/salt#50987]
### Description of Issue/Question
I am trying to run the following command on Windows minion,
 ```
salt 126ui cmd.run 'robot --variable UserId:u170041 --variable Password:xxxxxx --variable Job:"TSO SUBMIT 'U170041.JOBS(TEST)'" C:\\Mainframe_Integration\\mainframe_usecase\\mainframe_usecase\\MainFrameTesting.robot'
```

But getting the error as ,
`bash: syntax error near unexpected token `(' 
`
If i run the command manually on the Minion, it is working fine

### Versions Report
salt 2017.7.8 (Nitrogen)

**Comment by garethgreenaway** [comment]
@twangboy @dwoz Thoughts?

**Comment by twangboy** [comment]
@nkv16786 Looks like an issue with escaping characters on the command line in Linux... try this:
```
salt dev12 cmd.run "robot --variable UserId:u170041 --variable Password:xxxxxx --variable Job:\"TSO SUBMIT 'U170041.JOBS(TEST)'\" C:\\Mainframe_Integration\\mainframe_usecase\\mainframe_usecase\\MainFrameTesting.robot"
```

**Comment by twangboy** [comment]
@nkv16786 Did the above command work?

**Comment by nkv16786** [comment]
Yes it is working thanks :)
