### ISSUE TITLE
run salt-api: Not loading 'salt.loaded.int.netapi.rest_cherrypy'. Error loading CherryPy: No module named 'cherrypy'

### ISSUE THREAD

**Issue by wzlee** [saltstack/salt#50993]
![image](https://user-images.githubusercontent.com/4182865/50504750-bb069680-0aaa-11e9-856b-dda660b38386.png)
![image](https://user-images.githubusercontent.com/4182865/50504754-c8238580-0aaa-11e9-91bb-d2fd9f384503.png)

**Comment by garethgreenaway** [comment]
@wzlee Thanks for the report. It appears that you do not have the `cherrypy` Python package installed.  You'll need to install it using either the operating system package management system or using the Python `pip` binary.
