### ISSUE TITLE
gpg rendering issue

### ISSUE THREAD

**Issue by nkrishnakishor** [saltstack/salt#50995]
### Description of Issue/Question
Unable to generate key using gpg
### Setup

`#gpg --gen-key --homedir /etc/salt/gpgkeys`
gpg (GnuPG) 2.0.22; Copyright (C) 2013 Free Software Foundation, Inc.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.

Please select what kind of key you want:
   (1) RSA and RSA (default)
   (2) DSA and Elgamal
   (3) DSA (sign only)
   (4) RSA (sign only)
Your selection? 1
RSA keys may be between 1024 and 4096 bits long.
What keysize do you want? (2048)
Requested keysize is 2048 bits
Please specify how long the key should be valid.
         0 = key does not expire
      <n>  = key expires in n days
      <n>w = key expires in n weeks
      <n>m = key expires in n months
      <n>y = key expires in n years
Key is valid for? (0)
Key does not expire at all
Is this correct? (y/N) y

GnuPG needs to construct a user ID to identify your key.

Real name: saltserver
Email address:
Comment:
You selected this USER-ID:
    "saltserver"

Change (N)ame, (C)omment, (E)mail or (O)kay/(Q)uit? O
You need a Passphrase to protect your secret key.

gpg: can't connect to the agent: IPC connect call failed
gpg: problem with the agent: No agent running
gpg: can't connect to the agent: IPC connect call failed
gpg: problem with the agent: No agent running
gpg: Key generation canceled.
[root@server ~]# ls /etc/salt/gpgkeys/
pubring.gpg  random_seed  secring.gpg

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
`# gpg --gen-key --homedir /etc/salt/gpgkeys`

### Versions Report
 `salt --versions-report`

```
# salt --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 14.3.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5

System Versions:
           dist: centos 7.2 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2 Core
```

**Comment by garethgreenaway** [comment]
@nkrishnakishor Looks like the GPG binary is looking for the gpg-agent, https://www.gnupg.org/documentation/manuals/gnupg/Invoking-GPG_002dAGENT.html

**Comment by nkrishnakishor** [comment]
@garethgreenaway thanks for the reply.

I have tried as per the link suggestion but getting the same error.

**Comment by nkrishnakishor** [comment]
@garethgreenaway i was able to generate key but without `--homedir /etc/salt/gpgkeys` option.

Will this help me in using encrypted data is state files ?
