### ISSUE TITLE
Docker state does not have equivalent of docker create and start

### ISSUE THREAD

**Issue by Poil** [saltstack/salt#51023]
Hi,

There is no way to call a `docker create` in saltstack.

This should be nice because `docker run` fails if the container already exists (but stopped). So doing a conditionnal `docker create` and a `docker start` seems to be a better way to manage this.

Ref. https://docs.docker.com/engine/reference/commandline/create/#extended-description

I think it should be the same function as `def run_container` from `modules/dockermod.py` except we stop at `ret['Name'] = name`

Also the `docker start` function should be the last part of this function.

So we can split it into `def create_container` and `def start_container`, and call these 2 functions for compatibility in `def run_container`

**Comment by garethgreenaway** [comment]
@Poil Thanks for the report.  There is a `create` function available in the docker and dockercompose execution modules.  If you need to call either of these from a state you could utilize the `module.run` state function.
