### ISSUE TITLE
RFC0004: Rename __salt__ to __runner__ in the Runner functions

### ISSUE THREAD

**Issue by mirceaulinic** [saltstack/salt#51039]
Comments for https://github.com/saltstack/salt/blob/develop/rfcs/0004-dunder-runner.md

**Comment by sjorge** [comment]
I read though this and why not keep __salt__ for the standard deprecation time of 2 (?) release but introduce the ```__runner__``` and a new one for the minion side exec modules, I have always found the ```__salt__``` to be rather confusing as to where it will run.

**Comment by thatch45** [comment]
I think that sounds reasonable, yes lets edit the RFC

**Comment by dwoz** [comment]
Closing this since the PR for the RFC has been merged.

**Comment by mirceaulinic** [comment]
Even though this issue has been closed, if there are any further suggestions, please write them below. Thanks!

@mattp- also mentioned in https://github.com/saltstack/salt/pull/51032#issuecomment-452802216:

```
you could have use the superseded functionality enable to be able to turn this on immediately while waiting for deprecation to take place
```

Which makes sense to me.

**Comment by mattp-** [comment]
@mirceaulinic are you hacking on this?  I can lend a hand. Another downside currently is calling runners from orchs have to go through saltutil.runner which involves instantiating another runnerclient, which has loader overhead that could be negated entirely.

maybe we should create a salt-rfcs similar to https://github.com/chef/chef-rfc, having it part of the main repo is confusing/difficult to track. When an rfc has been implemented -> PR is merged. that way there is a space for continuing conversation.
