### ISSUE TITLE
Unable to load xml for file.managed "contents" output.

### ISSUE THREAD

**Issue by thechile** [saltstack/salt#51035]
Hi

I'm running 2018.3.3 and trying to load .xlm file to be used in file.managed state.

```
{% set template = 'template_os_freebsd' %}
{% set template_contents = salt.cp.get_file_str("salt://zabbix/files/templates/template_os_freebsd.xml") %}

zabbix_template_{{ template }}:
  file.managed:
    - name: /tmp/zabbix_{{ template }}.xml
    - contents: {{ template_contents }}

{% endfor %}
```

I get error:

```
      ---
       local:
           Data failed to compile:
       ----------
           Rendering SLS 'base:zabbix.frontend.bootstrap' failed: could not find expected ':'; line 2259

       ---
       [...]
                    </item>
                </graph_item>
            </graph_items>
        </graph>
           </graphs>
       </zabbix_export>    <======================

           #- source: salt://zabbix/files/templates/template_os_freebsd.xml
```

I tried various `| xml` or `| load_text` but nothing seems to work. If i change the contents of the file to be non-xml it works fine. 

Can anyone suggest a fix please or if this is a bug somewhere ?

The exact .xml i'm using is [here](https://share.zabbix.com/index.php?option=com_mtree&task=att_download&link_id=443&cf_id=40)

Thank you.

**Comment by thechile** [comment]
Update: If i remove all newlines on the .xml it seems ok. With that in mind i tried 

`{% set template_contents = salt.cp.get_file_str("salt://zabbix/files/templates/template_os_freebsd.xml") | regex_replace('\n','') %}` 

but didn't seems to work which was odd.

**Comment by terminalmage** [comment]
YAML is indentation dependent. If you want to load multiline content, you'll need to use the YAML syntaxt for multi-line strings, and combine that with the jinja `indent` filter:

```
zabbix_template_{{ template }}:
  file.managed:
    - name: /tmp/zabbix_{{ template }}.xml
    - contents: |
        {{ template_contents | indent(8) }}
```

**Comment by dwoz** [comment]
@thechile has @terminalmage's answer resolved your issue?

**Comment by thechile** [comment]
thanks.. i had to use the following to get it working in my use case as the quotes in the xml were erroring 

`{{ template_contents | indent(8) | replace('"',"'") }}` 

but works now thank you.
