### ISSUE TITLE
salt-minion log not getting updated

### ISSUE THREAD

**Issue by hbangaruu** [saltstack/salt#51052]
### Description of Issue/Question

salt-minion log not getting update even after restarting the salt-minion service. Default log file location is C:\salt\var\log\salt\minion.

Tried updating 'salt-minion-debug' config as below and restarted but log file not got created.

"%Python%" "%Script%" -l debug >C:\salt\var\log\salt-minion-python.log 2>&1

### Setup
OS: Windows Server 2012 R2 Standard

### Steps to Reproduce Issue
Manual restart of salt-minion service from services windows.

### Versions Report
C:\salt>salt-minion --versions-report
Salt Version:
           Salt: 2016.3.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.3.0
       dateutil: 2.5.3
          gitdb: 0.6.4
      gitpython: 2.0.2
          ioflo: 1.5.3
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.4
   msgpack-pure: Not Installed
 msgpack-python: 0.4.7
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.12 (v2.7.12:d33e0cf91556, Jun 27 2016, 15:24:40) [MSC v.150
0 64 bit (AMD64)]
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.3
            ZMQ: 4.1.2

System Versions:
           dist:
        machine: AMD64
        release: 8.1
         system: Windows
        version: 8.1 6.3.9600  Multiprocessor Free

**Comment by hbangaruu** [comment]
@vutny @mikeadamz : Please kindly help with above issue.

**Comment by garethgreenaway** [comment]
@twangboy @dwoz Thoughts?

**Comment by mikeadamz** [comment]
So I think first of all redirecting the log file like this won't work

```
"%Python%" "%Script%" -l debug >C:\salt\var\log\salt-minion-python.log 2>&1
```

Salt has several configuration file options to configure the log file. 

Please see `log_file` and `log_level_logfile` here: https://docs.saltstack.com/en/latest/ref/configuration/logging/

I suspect you may end up in a situation where the redirect is causing problems with salt's ability to open and write to that file.
