### ISSUE TITLE
[2018.3.2] File Exists traceback

### ISSUE THREAD

**Issue by DaveQB** [saltstack/salt#51050]
### Setup
{% set WALDIR = '/srv/logs.wal' %}
{% set INFLUXWAL = 'influx.wal' %}
{% set HOST = 'ops-log05' %}

# Symlink to the EFS mount
{{ WALDIR }}:
  file.symlink:
    - target: /srv/efs/logs.wal
    - makedirs: True
    - force: True
    - require:
      - mount: {{ HOST }}-efs

{{ HOST }}-dir-wal:
  file.directory:
    - name: {{ WALDIR }}/{{ INFLUXWAL }}
    - mode: 755
    - user: influxdb
    - makedirs: True
    - require:
      - mount: {{ HOST }}-efs

### Steps to Reproduce Issue
Run highstate and get the below. I think the issue is the next nature of the file.symlink and file.managed but I wouldn't have expected that would be an issue much less result in a traceback.

          ID: ops-log05-dir-wal
    Function: file.directory
        Name: /srv/logs.wal/influx.wal
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1905, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1830, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/file.py", line 2992, in directory
                  mode=dir_mode)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 5598, in makedirs_
                  mkdir(directory_to_create, user=user, group=group, mode=mode)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 5530, in mkdir
                  makedirs_perms(directory, user, group, mode)
                File "/usr/lib/python2.7/dist-packages/salt/modules/file.py", line 5630, in makedirs_perms
                  os.mkdir(name)
              OSError: [Errno 17] File exists: '/srv/logs.wal'
     Started: 18:16:15.769330
    Duration: 1.978 ms
     Changes: 

### Versions Report
MINION:
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial

Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Jul  1 2016, 15:12:24)
   python-gnupg: 0.3.8
         PyYAML: 3.13
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-116-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by DaveQB** [comment]
Looks like an OS level issue as the root cause, although a traceback to the user should be fixed, ideally. This is odd and I can't explain it. See below:


```
/root> mkdir -p /srv/logs.data/rsyslog.clients
mkdir: cannot create directory ‘/srv/logs.data’: File exists

/root> ls -l  /srv/logs.data
lrwxrwxrwx 1 root root 18 Jan  4 18:02 /srv/logs.data -> /srv/efs/logs.data

/root> mkdir -p /srv/efs/logs.data/rsyslog.clients
/root> mkdir -p /srv/logs.data/rsyslog.clients

/root> rmdir  /srv/efs/logs.data/rsyslog.clients
/root> rmdir /srv/logs.data/rsyslog.clients

/root> mkdir -p /srv/logs.data/rsyslog.clients
/root> rmdir /srv/logs.data/rsyslog.clients
/root> rmdir /srv/logs.data/rsyslog.clients
rmdir: failed to remove '/srv/logs.data/rsyslog.clients': No such file or directory

/root> mkdir -p /srv/logs.data/rsyslog.clients
/root> rmdir /srv/logs.data/rsyslog.clients
```

**Comment by DaveQB** [comment]
Further digging and the issue is the directory path trying to be made, with the symlink in it, does not exist yet and even with a -p mkdir can't make it without the parent if the path includes a symlink. News to me.

```
/root> mkdir -p /srv/logs.wal/influx.wal
mkdir: cannot create directory ‘/srv/logs.wal’: File exists
/root> ls -l /srv/logs.wal
lrwxrwxrwx 1 root root 17 Jan  4 18:02 /srv/logs.wal -> /srv/efs/logs.wal
/root> ls /srv/efs/logs.wal
ls: cannot access '/srv/efs/logs.wal': No such file or directory
```

So a small edge case that would be better to be handled better (or other errors like this for the file.managed module) but not a high priority issue. Maybe even the file(.directory) module could check and take care of this in the background to save needing another block to get this going? A feature request perhaps.

**Comment by dwoz** [comment]
@DaveQB Thanks for reporting this and digging into the cause. Are you comfortable enough with the code to create a PR that fixes the issue?

**Comment by DaveQB** [comment]
> @DaveQB Thanks for reporting this and digging into the cause. Are you comfortable enough with the code to create a PR that fixes the issue?

Not at all sorry. Never looked at the salt stack code and I am not a coder either.
