### ISSUE TITLE
Feature request? A way to deal with predictable network interfaces

### ISSUE THREAD

**Issue by dpkirchner** [saltstack/salt#51065]
Many OSs come with systemd's so-called predictable network interfaces enabled by default. This makes it difficult or impossible to predict what the interface name will be at any given boot. This is especially a problem when working with servers in a remote DC where you may have remote hands changing your hardware. See https://github.com/systemd/systemd/issues/3715 for a more detailed explanation of the problem.

Is there a way to deal with this problem in salt? If not, this could be considered feature request. If so, I guess it'd be a documentation request.

It'd be useful to have some way to determine the correct interface names to use when applying, say, sysctl states (think `net.ipv4.conf.eth0.arp_filter` which may now be, say, `net.ipv4.conf.enp24s0f0.arp_filter`). You're supposed to be able to programmatically determine the interface name with a `lspci -d`, and I figure that results could be exposed as grain values.

```bash
$ sudo lspci -d '::0200'
18:00.0 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
18:00.1 Ethernet controller: Intel Corporation I350 Gigabit Network Connection (rev 01)
```

which map to `enp24s0f0` and `enp24s0f1` (`0x18` is dec `24`, `:00` is `s0` and the last `0` or `1` are `f0` or `f1`, I believe). If we assume that the sorted order of the interfaces returned by `lspci` is always consistent (i.e. the first one in the sorted list is always the first interface in the computer) then I think it'd be totally possible to expose the value as a grain named something like `eth0` (heh), which would then map automatically to the correct value.

With this feature, if someone added a video card their network-related rules would still work unchanged. If they added a network card they may be SOL, but that'd be something they'd need to watch out for even if they weren't using predictable network interface names.

I don't know enough about the underpinnings of salt to know if this is even possible, but I'm hoping y'all have already considered it and have some ideas about a solution. (Other than disabling the "predictable" feature entirely, which I'm hoping to avoid if only because I don't know how long that will be possible.)

**Comment by Ch3LL** [comment]
you only want to add this feature to sysctl.py state? 

I think it would be doable if we can determine the name programmatically and add it as a feature with a kwarg such as discover=True.

**Comment by dpkirchner** [comment]
Sorry for the slow reply -- I'd be using the interface name in multiple places, sysctl was just an example. I'd totally understand if this ends up being out of scope as something to workaround a systemd issue.

**Comment by Ch3LL** [comment]
Could you determine the name using some jinja logic and then refer to that interface with `{{ interface_name }}` throughout your states?

**Comment by johnnybubonic** [comment]
This is actually similar to how BSDs name their interfaces. (I prefer it, personally; once you understand [HOW](https://github.com/systemd/systemd/blob/master/src/udev/udev-builtin-net_id.c#L20) the names are determined, they actually are predictable as long as you know the NICs' hardware and where it's attached.) However, the `lspci` listing may be consistent - or may not. From memory, it's whatever order the hardware initializes (which is explained in the "Why?" section [here](https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/)).

The main problem would be determining a canonical and programmatic approach of what the primary interface "should" be (which even the classic eth0/eth1 naming scheme doesn't address without some further distro-level hacks - RedHat family does this by manually changing a device's name based on a static cache of interface names to MAC address in NetworkManager/udev). I personally used to do this with [pyroute2](https://docs.pyroute2.org/) and finding which iface has the default route:

```Python
from pyroute2 import IPDB

ip = IPDB()
# oif is "output interface" for outgoing routes;
# you'll want to use "iif" if you use a different iface
# for incoming but that's silly for default routes.
iface_id = ip.routes['default']['oif']
iface_nm = ip.interfaces[iface_id].ifname
```
(You'll want to do some further logic on that if you use different ifaces for IPv4 vs. IPv6.)

But this information is already available via Salt ([network.default_route](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.network.html#salt.modules.network.default_route)). The 'interface' key in that returned dict is what you want. Presumably this is for a WAN iface, so the default route iface should be reliable enough unless you're doing something more advanced like iface bonding or such.

By the way, if you really, really don't like it, you CAN disable it via a couple methods:

1. `ln -s /dev/null /etc/systemd/network/99-default.link` (I'm not sure if this would work if you use, say, NetworkManager.)
2. The kernel cmdline parameter `net.ifnames=0` will do it. throw that on your kernel line in your bootloader, done. If you have a kickstart/debian pre-seed server/whatever set up, this should be a cinch and you wouldn't even need to touch the machine. Just throw it in a post task to edit the bootloader entries.
3. You can arbitrarily and statically name interfaces but this is probably not very maintainable.

Hope this helps!

**Comment by dpkirchner** [comment]
network.default_route is interesting -- thanks! I'll see what I can do with it.

And yeah, I really, really, really don't like this feature of systemd, but I'm concerned that it's just the way of the future, so I'm going along with it.

(As for how they're determined, as you say you may be able figure it out if you know the order in which the hardware is attached, but most of my work is remote-hands. Even in person, I don't know if the physical slot order will always match the order exposed to the software. I think it'd be an interesting challenge to give someone: "here's a computer with built-in NICs. tell me exactly what the network interface names will be after this RAID adapter is installed.")

**Comment by johnnybubonic** [comment]
(good point re: RAID adapter installation! i've definitely been bitten by hardware being jostled to a different slot during e.g. a disk replacement! glad i could help!)
