### ISSUE TITLE
no response of few hosts during highstate when run in bulk.

### ISSUE THREAD

**Issue by iadityagrover** [saltstack/salt#51078]
### Description of Issue/Question
When we are running highstate in our enviroment on multiple servers in batches of 30 out the list of 230 with timeout 300 we find few servers not providing any output. We get below output:
example:
hostname1.corp.adobe.com:
    ----------
hostname2.corp.adobe.com:
    ----------
hostname3.corp.adobe.com:
    ----------
hostname4.corp.adobe.com:

When we rerun highstate on these machine, they get successfully completed. There is no recurrence of issue on exact same set of machines which didnt not respond initially. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
We have master syndic, highstate files are pulled from git. All the highstates are pushed from master syndic cron to the minions.

We have multiple OS in the ENV and issue spans mostly in RHEL, AIX, SUSE, Windows.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 12 2018, 05:31:16)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo

**Comment by Ch3LL** [comment]
can you check the minion logs and see if its still attempting to run the highstate after it returns that?

Or any other useful information in the minion debug log when this occurs?

**Comment by iadityagrover** [comment]
I did check on the server. It's no longer attempting to run highstate after it returns. There are no longs generated. We just see the server name and blank output. There is no summary to go after. I did check the minion logs as well as well as on master but no luck finding any information. I have faced this during patching as well.

**Comment by Ch3LL** [comment]
do you have debug log settings turned on?that should show us more information
