### ISSUE TITLE
netsnmp.managed throws an error

### ISSUE THREAD

**Issue by misch42** [saltstack/salt#51087]
### Description of Issue/Question
Basically this is a question about the usage / configuration of the netsnmp.managed function. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
in states/snmp.sls I have:
snmp_example:
  netsnmp.managed:
    - config:
      location: here
    - defaults:
      contact: me

basically this is copied over from the doc.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
salt 'myswitch' state.sls snmp

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
# salt --versions-report
Salt Version:
           Salt: 2018.3.3
(...)

salt 'myswitch' state.sls ntp from the netntp.managed function works.

**Comment by Ch3LL** [comment]
I'm not seeing the error that is thrown when this is run. Can you include the error output?

**Comment by misch42** [comment]
Sorry. somehow the copy&paste gone wrong.

# salt 'myswitch' state.sls snmp
myswitch:
----------
          ID: snmp_example
    Function: netsnmp.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1913, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/netsnmp.py", line 357, in managed
                  expected_config = _expand_config(config, defaults)
                File "/usr/lib/python3/dist-packages/salt/states/netsnmp.py", line 81, in _expand_config
                  defaults.update(config)
              AttributeError: 'NoneType' object has no attribute 'update'
     Started: 21:36:51.384892
    Duration: 33.739 ms
     Changes:   
    Warnings: 'location' and 'contact' are invalid keyword arguments for
              'netsnmp.managed'. If you were trying to pass additional data to
              be used in a template context, please populate 'context' with
              'key: value' pairs. Your approach will work until Salt Fluorine is
              out. Please update your state files.

Summary for myswitch
------------
Succeeded: 0
Failed:    1
Warnings:  1
------------
Total states run:     1
Total run time:  33.739 ms
ERROR: Minions returned with non-zero exit code

**Comment by Ch3LL** [comment]
thanks for posting the error. It looks like your state just needs a couple of spaces. So from this:

```
snmp_example:
  netsnmp.managed:
    - config:
      location: here
    - defaults:
      contact: me
```

to this:

```
snmp_example:
  netsnmp.managed:
    - config:
        location: here
    - defaults:
        contact: me
```

i was able to replicate your issue only when location and contact were not in the correct spacing.

**Comment by misch42** [comment]
With community configured it also fails with:

myswitch:
----------
          ID: snmp_example
    Function: netsnmp.managed
      Result: False
     Comment: Cannot push new SNMP config: 
              Cannot execute "load_template" on 192.168.88.240 as admin. Reason: Unable to render the Jinja config template snmp_config: 'dict object' has no attribute 'iteritems'!
              Configuration discarded.
     Started: 13:38:37.493891
    Duration: 1999.222 ms
     Changes:   
              ----------
              added:
                  ----------
                  community:
                      ----------
                      public:
                          ----------
                          mode:
                              ro
                  contact:
                      Me
                  location:
                      Munich

Summary for myswitch
------------
Succeeded: 0 (changed=1)
Failed:    1

**Comment by Ch3LL** [comment]
ping @mirceaulinic any chance you can take a look here?

**Comment by misch42** [comment]
No comment for a while. So I will close the issue. I wrote my own state file for now.
