### ISSUE TITLE
How to build a rpm package correctly?

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#51092]
### Description of Issue/Question
I changed some code base on 2017.7.8 and build a rpm package with new version code(2019.1.8), but got the error when I run test.ping:  
              Module 'test' is not available.

###Note: It's normal when I go to the minion's python shell and import functools, I am sure functools module is just in my python package.

### Steps to Reproduce Issue
go to master terminal and run:   salt 'xxxxx' test.ping
then got:
xxxxxx:
    Module 'test' is not available.

### Versions Report

Python Version: 2.7.5

salt --versions-report:
Salt Version:
           Salt: 2017.7.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

pip freeze:
altgraph==0.16.1
apache-libcloud==2.0.0rc2
Babel==0.9.6
backports.ssl-match-hostname==3.5.0.1
chardet==2.2.1
CherryPy==3.2.0
configobj==4.7.2
decorator==3.4.0
dis3==0.1.2
future==0.17.1
futures==3.0.5
iniparse==0.4
ipaddress==1.0.16
IPy==0.75
Jinja2==2.7.2
kitchen==1.1.1
langtable==0.0.31
linecache2==1.0.0
M2Crypto==0.30.1
macholib==1.11
MarkupSafe==0.11
mock==1.0.1
msgpack-python==0.4.8
netsnmp-python==1.0a1
numpy==1.15.4
pefile==2018.8.8
pefile2==1.2.11
perf==0.1
policycoreutils-default-encoding==0.1
psutil==2.2.1
pycrypto==2.6.1
pycurl==7.19.0
pygobject==3.14.0
pygpgme==0.3
PyInstaller==3.4
pyliblzma==0.5.3
python-augeas==0.5.0
python-dmidecode==3.10.13
pytoml==0.1.18
pyudev==0.15
pyxattr==0.5.1
PyYAML==3.10
pyzmq==15.3.0
redis==3.0.1
registries==0.1
requests==2.6.0
salt==2017.7.8
seobject==0.1
sepolicy==1.1
six==1.9.0
slip==0.4.0
slip.dbus==0.4.0
tornado==4.2.1
traceback2==1.4.0
typing==3.6.6
unittest2==1.1.0
urlgrabber==3.10
urllib3==1.10.2
yum-langpacks==0.4.2
yum-metadata-parser==1.1.4

**Comment by Ch3LL** [comment]
are you asking how to build a rpm package of salt with your changed code?

**Comment by andyyumiao** [comment]
> are you asking how to build a rpm package of salt with your changed code?

yes, can you provide the help? much thanks...

**Comment by Ch3LL** [comment]
we use https://github.com/saltstack/salt-pack to build our rpm.

@dmurphy18 is the README The only documentation for a user to get up to speed with salt-pack?

**Comment by dmurphy18** [comment]
Currently yes, I have a task to write up a fuller document on how to build, etc.

Note for Python 3 https://github.com/saltstack/salt-pack-py3

And their is open-sourced how we have the nightly builds and tagged versions automated
https://github.com/saltstack/salt-auto-pack

see file_roots/auto_setup/autobuild, a bash script to kick it all off, it leverages orchestration and builds the platforms in parallel.

Note all of the above are open-sourced and any contributions are welcome.

Apologies that have not completed better documentation but that limited resource of time.

**Comment by Ch3LL** [comment]
thanks for the follow up information @dmurphy18 

hopefully that helps you out @andyyumiao 

also to note if you are just updating code for a module you can use the `sync_modules` https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_modules

and add your fixes to salt://_modules and deploy with sync_modules and it will deploy the fix to all minions.
