### ISSUE TITLE
Including extension_modules causes an error: six.py

### ISSUE THREAD

**Issue by misch42** [saltstack/salt#51103]
I wanted to include the netbox ext pillar on my ubuntu 18.04 system. The netbox.py is located in

/usr/lib/python3/dist-packages/salt/modules/netbox.py

so I configured in /etc/salt/master:

extension_modules: /usr/lib/python3/dist-packages/salt

When I start salt I get the the error:

Jan 08 20:54:58 nms salt-master[18922]: ModuleNotFoundError: No module named 'http.client'; 'http' is not a package
Jan 08 20:54:58 nms salt-master[18922]: Traceback (most recent call last):
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/bin/salt-master", line 22, in <module>
Jan 08 20:54:58 nms salt-master[18922]:     salt_master()
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/scripts.py", line 97, in salt_master
Jan 08 20:54:58 nms salt-master[18922]:     master.start()
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/cli/daemons.py", line 211, in start
Jan 08 20:54:58 nms salt-master[18922]:     super(Master, self).start()
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/utils/parsers.py", line 1044, in start
Jan 08 20:54:58 nms salt-master[18922]:     self.prepare()
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/cli/daemons.py", line 191, in prepare
Jan 08 20:54:58 nms salt-master[18922]:     import salt.master
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/master.py", line 35, in <module>
Jan 08 20:54:58 nms salt-master[18922]:     import salt.client.ssh.client
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/client/ssh/__init__.py", line 34, in <
Jan 08 20:54:58 nms salt-master[18922]:     import salt.minion
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/minion.py", line 81, in <module>
Jan 08 20:54:58 nms salt-master[18922]:     import salt.pillar
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 20, in <modu
Jan 08 20:54:58 nms salt-master[18922]:     import salt.fileclient
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/fileclient.py", line 15, in <module>
Jan 08 20:54:58 nms salt-master[18922]:     from tornado.httputil import parse_response_start_line, HTTPHeaders, HTTPInput
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/tornado/httputil.py", line 39, in <module>
Jan 08 20:54:58 nms salt-master[18922]:     import http.cookies as Cookie
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/utils/http.py", line 60, in <module>
Jan 08 20:54:58 nms salt-master[18922]:     import salt.ext.six.moves.http_client
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 210, in load_module
Jan 08 20:54:58 nms salt-master[18922]:     mod = mod._resolve()
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 122, in _resolve
Jan 08 20:54:58 nms salt-master[18922]:     return _import_module(self.mod)
Jan 08 20:54:58 nms salt-master[18922]:   File "/usr/lib/python3/dist-packages/salt/ext/six.py", line 89, in _import_modul
Jan 08 20:54:58 nms salt-master[18922]:     __import__(name)
Jan 08 20:54:58 nms salt-master[18922]: ModuleNotFoundError: No module named 'http.client'; 'http' is not a package
Jan 08 20:54:59 nms systemd[1]: salt-master.service: Main process exited, code=exited, status=1/FAILURE
Jan 08 20:54:59 nms systemd[1]: salt-master.service: Failed with result 'exit-code'.
Jan 08 20:54:59 nms systemd[1]: Failed to start The Salt Master Server.

Versions report:
# salt-master -V
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.2
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by dwoz** [comment]
@misch42 `/usr/lib/python3/dist-packages/salt/modules/netbox.py` is a salt module which would be available by default in your installation. Pillars and pillar data should not be confused with modules. Generally, extension_modules will be modules that you write and will live somewhere under your file_roots. For example `/srv/salt/_modules/my_module`.

Can you explain more about what you are trying to accomplish?

**Comment by misch42** [comment]
I want to use netbox as an external pillar as described in
https://docs.saltstack.com/en/develop/ref/pillar/all/salt.pillar.netbox.html

First I want to define devices in netbox and make salt to know about the devices. Finally I want to define devices in netbox and make salt to implement the configuration.

When I configure the external pillar as described above salt tells me "ext_pillar netbox interface is unavailable"

**Comment by misch42** [comment]
it seems to be a problem with python3. With python2.7 everything works as described in the doc.
