### ISSUE TITLE
sakt-api  “Authentication failure of type "eauth" occurred”

### ISSUE THREAD

**Issue by fandaye** [saltstack/salt#51109]
### Description of Issue/Question
`curl -sSk http://127.0.0.1:58080/login -H 'Accept: application/x-yaml' -d username='saltapi' -d password='123456' -d eauth=pam`

    <!DOCTYPE html PUBLIC
    "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
        <title>401 Unauthorized</title>
        <style type="text/css">
        #powered_by {
            margin-top: 20px;
            border-top: 2px solid black;
            font-style: italic;
        }
    
        #traceback {
            color: red;
        }
        </style>
    </head>
        <body>
            <h2>401 Unauthorized</h2>
            <p>Could not authenticate using provided credentials</p>
            <pre id="traceback"></pre>
        <div id="powered_by">
          <span>
            Powered by <a href="http://www.cherrypy.org">CherryPy 5.6.0</a>
          </span>
        </div>
        </body>
    </html>

If you re-create a user and configure the password, modify the salt-api configuration file, restart salt-master and salt-api, and execute:

    [root@001 ~]# curl -sSk http://127.0.0.1:58080/login -H 'Accept: application/x-yaml' -d username='saltad' -d password='123456' -d eauth=pam       
    return:
    - eauth: pam
      expire: 1547079096.214643
      perms: {}
      start: 1547035896.214641
      token: 08337065c73df44bf5aa32a62d76d1626a54b66a
      user: saltad
    [root@001 ~]# curl -sSk http://127.0.0.1:58080/login -H 'Accept: application/x-yaml' -d username='saltad' -d password='123456' -d eauth=pam
    return:
    - eauth: pam
      expire: 1547079097.57972
      perms: {}
      start: 1547035897.579719
      token: 8acc27560451e55271ba68d13d0522168c80678d
      user: saltad
    [root@001 ~]# curl -sSk http://127.0.0.1:58080/login -H 'Accept: application/x-yaml' -d username='saltad' -d password='123456' -d eauth=pam
    return:
    - eauth: pam
      expire: 1547079098.824643
      perms: {}
      start: 1547035898.824642
      token: 70aea9163c6fd5359599d66a606c0a9bc4edcbc6
      user: saltad
    [root@001 ~]# curl -sSk http://127.0.0.1:58080/login -H 'Accept: application/x-yaml' -d username='saltad' -d password='123456' -d eauth=pam
    return:
    - eauth: pam
      expire: 1547079099.915474
      perms: {}
      start: 1547035899.915473
      token: 159cb26a9f04b93981a5b01420919605ea9a35fb
      user: saltad
    [root@001 ~]# curl -sSk http://127.0.0.1:58080/login -H 'Accept: application/x-yaml' -d username='saltad' -d password='123456' -d eauth=pam
    return:
    - eauth: pam
      expire: 1547079100.98678
      perms: {}
      start: 1547035900.986778
      token: 13aeb6ece4fa22eab745b34023950be74372a133
      user: saltad
    [root@001 ~]# curl -sSk http://127.0.0.1:58080/login -H 'Accept: application/x-yaml' -d username='saltad' -d password='123456' -d eauth=pam
    <!DOCTYPE html PUBLIC
    "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
    <html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
        <title>401 Unauthorized</title>
        <style type="text/css">
        #powered_by {
            margin-top: 20px;
            border-top: 2px solid black;
            font-style: italic;
        }
    
        #traceback {
            color: red;
        }
        </style>
    </head>
        <body>
            <h2>401 Unauthorized</h2>
            <p>Could not authenticate using provided credentials</p>
            <pre id="traceback"></pre>
        <div id="powered_by">
          <span>
            Powered by <a href="http://www.cherrypy.org">CherryPy 5.6.0</a>
          </span>
        </div>
        </body>
    </html>

The previous requests were normal, but failed over a period of time.

Why?

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

    /etc/salt/master.d/api.conf 
    external_auth:
      pam:
        saltad:
          - .*
          - '@wheel'
          - '@runner'
          - '@jobs'
    
    rest_cherrypy:
      port: 58080
      host: 0.0.0.0
      disable_ssl: True
      debug: True

    [DEBUG   ][14517] LazyLoaded pam.auth
    [WARNING ][14517] Authentication failure of type "eauth" occurred.
    [WARNING ][14517] Authentication failure of type "eauth" occurred.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

    salt --versions-report
    Salt Version:
               Salt: 2018.3.3
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: unknown
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: 1.2.5
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.13 (default, Mar 30 2018, 15:31:59)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.5.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
     
    System Versions:
               dist: centos 6.9 Final
             locale: UTF-8
            machine: x86_64
            release: 2.6.32-696.30.1.el6.x86_64
             system: Linux
            version: CentOS 6.9 Final

**Comment by ZAM-** [comment]
Why was this closed?
