### ISSUE TITLE
Windows 10 Minions use very high CPU if salt-key is rejected / unaccepted on master

### ISSUE THREAD

**Issue by tjgruber** [saltstack/salt#51138]
### Description of Issue/Question

My CPU usage is 51-100% + for Python.exe (salt-minion) on any PC who's denied/not accepted on the salt-master.

Background:
Multiple PCs, including my own, have been chewing high CPU resources constantly... fan spinning fast, degraded performance, etc. When I looked, it was python.exe (salt-minion) using over 51% of CPU and showing high power consumption.

Once I checked the salt-master, and removed the PCs via salt-key -d, then accepted them, it got better immediately.

In my case specifically, the computer was reloaded, so the old key was accepted, and the new but current key was denied. I removed both from salt-master, waited a second, then accepted the new current key.

I found an old identical issue here: https://github.com/saltstack/salt/issues/9052

### Versions

salt-minion (2018.3.3)
Windows 10 1809

**Comment by twangboy** [comment]
So, when running the salt-minion in debug mode it looks like the salt-minion process just stops when the key has been denied by the master. That could cause this behavior when salt-minion is running as a service.

The service manager we use monitors the status of the minion. If the process dies for any reason, the process manager will restart the salt-minion service. So, the minion will try to connect, find out it's denied, and die. The service manager will restart the service again and the process repeats. I'm guessing this is what you're seeing.

The service manager does have a `delay restart` option. It's set to 0 by default... no delay. I set it to 10 secs and now I see a cpu spike every 10 seconds. Maybe 60 seconds would be a good default. To set this do the following:

1. Open a comman prompt
2. Navigate to `C:\salt\bin`
3. Type: `ssm set salt-minion AppRestartDelay 60000`

That should fix the issue. We'll need to add this to the installer for situations such as this.

@dwoz @UtahDave Does 60 seconds sound like a sane default?

**Comment by tjgruber** [comment]
> I set it to 10 secs and now I see a cpu spike every 10 seconds.

How long does the spike last?

I'm asking because once the denied key is deleted on the master, it could then take up to 60 seconds for

**Comment by tjgruber** [comment]
Hit the wrong link.

**Comment by twangboy** [comment]
This fix above addresses the issue from Salt code. It adds a random sleep of 10 to 20 seconds before it issues the `sys.exit` command.
