### ISSUE TITLE
python3: pynetbox cannot be loaded?

### ISSUE THREAD

**Issue by misch42** [saltstack/salt#51140]
Hi,

I installed netbox, salt and pynetbox on a new ubuntu 18.04 (bionic). I configured an external pillar according to the docs (/etc/salt/master).
```
ext_pillar:
  - netbox:
    api_url: http://127.0.0.1/api/
    api_token: XXXXX 
    proxy_return: True
    proxy_username: admin
```
But salt isn't able to use the pillar:

# salt myswitch netbox.get dcim devices
``` 
myswitch:
    'netbox' __virtual__ returned False: The netbox execution module cannot be loaded: pynetbox library is not installed.
ERROR: Minions returned with non-zero exit code
```
 salt-master and salt-proxy for my switch are on the same machine.

# salt -V
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.2
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic

# pip3 list  | grep netbox
pynetbox (4.0.6)

Any ideas?

**Comment by garethgreenaway** [comment]
@misch42 Thanks for the report. To confirm, you have installed `pynetbox` on the Salt master and have restarted the Salt master process?

**Comment by misch42** [comment]
yes.

**Comment by misch42** [comment]
yes. How to debug?

**Comment by misch42** [comment]
It seems to be a problem of python with pynetbox installed in /usr/local/lib/python3.6/dist-packages. If I export PYTHONPATH="/usr/local/..." then salt starts without problem. Now the error message is:

 # salt myswitch netbox.get dcim devices name="myswitch"
myswitch:
    ERROR: NetBox execution module configuration could not be found

Any ideas?

**Comment by misch42** [comment]
it seems to be a problem with python3. With python2.7 everything works as described in the doc.

**Comment by misch42** [comment]
follow up: I installed salt, netbox again with python3. The netbox module of salt is installed in
/usr/lib/python3/dist-packages/salt/modules/netbox.py

But pynetbox is installed in
/usr/local/lib/python3.6/dist-packages/pynetbox

So it seems that salt just cannot find the pynetbox from the other path.

Ideas?

**Comment by awlx** [comment]
Did you ever find a solution for this issue? I am experiencing the same at the moment with Python 3.6.

**Comment by misch42** [comment]
reinstalled everything about 5 times. works for me now.
