### ISSUE TITLE
Upgrading Windows 10 minon from 2017.7.4 to 2018.3.3 

### ISSUE THREAD

**Issue by daeo** [saltstack/salt#51155]
### Description of Issue/Question
On Windows 10, upgrading from 2017.7.4 to 2018.3.3 results in a new config file being generated for the minion with the previously designated name removed.  Previous updates didn't require a switch to keep the same name.

### Steps to Reproduce Issue
-Grab 2018.3.3 from repo
  `sudo wget https://repo.saltstack.com/windows/Salt-Minion-2018.3.3-Py2-AMD64-Setup.exe`

-Move file to /srv/salt

-Distribute file to minion(s)
 `sudo salt 'hostname.server.name' cp.get_file 'salt://Salt-Minion-2018.3.3-Py2-AMD64-Setup.exe' 'c:\path\to\exe\Salt-Minion-2018.3.3-Py2-AMD64-Setup.exe' `

-Run the installer via the master on the minion(s)
 `sudo salt 'minion.name' cmd.run 'START /B c:\path\to\installer\Salt-Minion-2018.3.3-Py2-AMD64-Setup.exe /S /master=saltmaster.foo.bar'`

### Versions Report

-master version report:

    Salt Version:
           Salt: 2018.3.3
 
    Dependency Versions:
           cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.5.3
           docker-py: Not Installed
           gitdb: 2.0.0
           gitpython: 2.1.1
           ioflo: Not Installed
           Jinja2: 2.9.4
           libgit2: Not Installed
           libnacl: Not Installed
           M2Crypto: Not Installed
           Mako: Not Installed
           msgpack-pure: Not Installed
           msgpack-python: 0.4.8
           mysql-python: Not Installed
           pycparser: Not Installed
           pycrypto: 2.6.1
           pycryptodome: Not Installed
           pygit2: Not Installed
           Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
           python-gnupg: Not Installed
           PyYAML: 3.12
           PyZMQ: 16.0.2
           RAET: Not Installed
           smmap: 2.0.1
           timelib: Not Installed
           Tornado: 4.4.3
           ZMQ: 4.2.1 
    System Versions:
           dist: debian 9.6 
           locale: UTF-8
           machine: x86_64
           release: 4.9.0-3-amd64
           system: Linux
           version: debian 9.6 
 

-minion version report (after upgrade):

    Salt Version:
               Salt: 2018.3.3
     
    Dependency Versions:
               cffi: 1.10.0
           cherrypy: 10.2.1
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: 2.1.3
              ioflo: Not Installed
             Jinja2: 2.9.6
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.6
       msgpack-pure: Not Installed
     msgpack-python: 0.4.8
       mysql-python: Not Installed
          pycparser: 2.17
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.3
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.1
                ZMQ: 4.1.6
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 10
             system: Windows
            version: 10 10.0.17134  Multiprocessor Free

**Comment by dwoz** [comment]
@daeo Thanks for reporting this. Using the `/master` option will cause the installer to overwrite the config. If you just use `/S` the config will be left alone. Does this work for you?

**Comment by twangboy** [comment]
@cmcmarrow 
- [ ] Verify that the `/master` option does overwrite the existing config
- [ ] Verify that not passing `/master` does not overwrite
- [ ] Make sure it is documented in the installer and in the documentation

**Comment by daeo** [comment]
/master does indeed overwrite the config on an upgrade, while using simply /S does not affect the existing config.

The webpage used as a guide was simply https://repo.saltstack.com/index.html#windows , which does not clearly state to use a different line for upgrading.  It may have simply been that I needed to look at another page to see clear upgrade instructions.
