### ISSUE TITLE
Python 3 on CentOS 7, "ImportError: No module named 'requests'" (Missing dependency)

### ISSUE THREAD

**Issue by johnnybubonic** [saltstack/salt#51162]
### Description of Issue/Question

Fresh installation of salt 2018.3.3-1 on a freshly-installed and fully updated CentOS 7.

When starting salt-master on CentOS 7.6.1810 using the _https://repo.saltstack.com/py3/redhat/7/$basearch/latest_repository ([RPM](https://repo.saltstack.com/py3/redhat/salt-py3-repo-latest-2.el7.noarch.rpm)), the following occurs during startup:

```
[DEBUG   ] Failed to import runners vault:
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/usr/lib64/python3.4/imp.py", line 235, in load_module
    return load_source(name, filename, file)
  File "/usr/lib64/python3.4/imp.py", line 171, in load_source
    module = methods.load()
  File "<frozen importlib._bootstrap>", line 1220, in load
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "/usr/lib/python3.4/site-packages/salt/runners/vault.py", line 15, in <module>
    import requests
ImportError: No module named 'requests'
```
(startup continues; non-fatal)

Manually performing a `yum install python34-requests` before starting salt-master, however, leads to the ImportError not showing up. Probably just a missed dependency; should be a quick fix. :)

### Setup
```
[root@salttest-server ~]# sed -re '/^[[:space:]]*(#|$)/d' /etc/salt/master
interface: '::'
ipv6: True
show_jid: True
cli_summary: True
con_cache: True
keysize: 4096
hash_type: sha512
```

### Steps to Reproduce Issue
See above.

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.4.9 (default, Aug 14 2018, 21:28:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
Installed salt RPMs:

```
[root@salttest-server ~]# rpm -qa | egrep '^salt'
salt-2018.3.3-1.el7.noarch
salt-api-2018.3.3-1.el7.noarch
salt-py3-repo-latest-2.el7.noarch
salt-master-2018.3.3-1.el7.noarch
salt-cloud-2018.3.3-1.el7.noarch
salt-minion-2018.3.3-1.el7.noarch
salt-syndic-2018.3.3-1.el7.noarch
salt-ssh-2018.3.3-1.el7.noarch
```

**Comment by dwoz** [comment]
@johnnybubonic thank for reporting this!

**Comment by johnnybubonic** [comment]
of course! very easy mistake; i do a lot of packaging for Arch AUR and some RPM packaging for work. believe me, i know how easy it is to miss deps, especially runtime deps!

thanks! saltstack is great, by the way, for all the devs reading this.

**Comment by dmurphy18** [comment]
@johnnybubonic Thanks for the catch, it is in BuildRequires and missing from Requires, editing error since in Python 2 version of spec file. will have fixed in next point release which will be soon.

**Comment by dmurphy18** [comment]
See https://github.com/saltstack/salt-pack-py3/pull/90 containing fix.  Please close this issue if satisfactory, as will appear in the next point release.

**Comment by johnnybubonic** [comment]
you got it, closing. fantastic turnaround.

**Comment by dmurphy18** [comment]
@johnnybubonic FYI won't be in Salt 2019.2.0rc1 as that was done last Friday, but it will be in the Release Candidate 2 which will in a couple of weeks.

**Comment by johnnybubonic** [comment]
@dmurphy18 no worries; i have it installed just fine currently and this system isn't even in prod yet. :) appreciate the heads-up though!
