### ISSUE TITLE
Python3 - pip3- Depreciation of python 2

### ISSUE THREAD

**Issue by jynolen** [saltstack/salt#51178]
### Description of Issue/Question

My question is the following:
Python2 is gonna be deprecated on 01/01/2020 so it will be really great if we can use pip3 or even better to specify the pip executable to be able to install / develop on top of python3.

Is there any chance we managed to do so ?

### Setup
test_packages:
  pip.installed:
    - pkgs:
      - pytest
      - testinfra
    - bin_env: '/usr/bin/pip3'
  require:
    - pkg: python34-pip

### Result
An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.

**Comment by waynew** [comment]
@jynolen for reference, the output of `salt-call --versions-report` is super helpful! Some might even say it's necessary 🙂

**Comment by jynolen** [comment]
My bad sorry !
`Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
`

Ok I find something just
`test_packages:
pip.installed:
- pkgs:
- pytest
- testinfra
- bin_env: '/usr/bin/pip3'
require:
- pkg: python34-pip`

Does not work when no python2-pip found
But with it, there is no issue package are correctly install on python3 env.

But I'm asking (I know a lot of apps / etc. still run under python2) but as py2 is going to be out of support soon, do you think it's possible to put py3 by default ?

Thanks !

**Comment by waynew** [comment]
@jynolen that's definitely in the works - we're definitely all for it (and we support installs on Python3), but our biggest challenge is that we have a not-insignificant userbase that's still using platforms that only have Python 2.7 (by default, at least).

We're currently working on a roadmap for when we're going to drop Python 2 support, since it's hitting EOL in January 2020.

---

I believe that you're running into this problem because you're using Python 2.7 for your Salt install - if you install Salt via pip (e.g. `sudo python34 -m pip install salt` - you may need to handle some dependencies), then it *should* pick up the python34 pip.

**Comment by jynolen** [comment]
Ok then, let's wait for your py3 roadmap ;)
I was just to have some clues about py3

Thanks :)
