### ISSUE TITLE
conflicting python packages for salt-minion

### ISSUE THREAD

**Issue by jordiprats** [saltstack/salt#51189]
### Description of Issue/Question

salt-minion installation conflicts with an already installed app. Our workround was to change permissions for jinja2 since we cannot modify the installed app:

chown -R 700 /usr/lib/python2.7/dist-packages/jinja2

Is there any way to install saltstack isolated? I've found no reference online on how to actually do it

### Setup
We have installed salt-minion 2018.3.2 using the bootstrap script:

curl -sL https://bootstrap.saltstack.com | sudo sh -s -- -A salt-fdsfsd.sys.dfssdffsd.cat stable 2018.3.2

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.5 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.5

**Comment by garethgreenaway** [comment]
@dmurphy18 Thoughts?

**Comment by dmurphy18** [comment]
@jordiprats You could play around with /etc/apt/preferences to given preference to the desired packages over other packages.
