### ISSUE TITLE
Salt-cloud vmware.py Documentation Add

### ISSUE THREAD

**Issue by GMAzrael** [saltstack/salt#51190]
### Description of Issue/Question
Salt documentation needs to add customization_spec to the list to select a customization profile. Users would not know how to ensure there vm is being provisioned with a customization without looking at the source code.

**Comment by garethgreenaway** [comment]
@GMAzrael Thanks for the report.  Can you point us at the location of the documentation that you're referring to and what version of Salt this documentation is for?

**Comment by GMAzrael** [comment]
Sorry about that @garethgreenaway . Place I was discussing was https://docs.saltstack.com/en/latest/topics/cloud/vmware.html#profiles. Many configuration options are listed, but the Configuration_spec item is missing. If you want to use the `Customization: True` (which is default), you need to list a customization profile.

**Comment by GMAzrael** [comment]
@garethgreenaway just wanted to ping this. Shouldn't be blocked anymore.
