### ISSUE TITLE
SCRAM-SHA-256 support for states.postgres_user

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#51217]
Current implementation either sends and compares plaintext or an md5hash.
There's no way to send plaintext for the server to hash, because it also adds `UNENCRYPTED` to the query.
> ERROR: UNENCRYPTED PASSWORD is no longer supported

**Comment by OrangeDog** [comment]
Python 3 implementation of postgres' algorithm
```python
import base64
import hashlib
import hmac
import secrets


def scram_sha_256(password):
    # TODO: saslprep
    if not isinstance(password, (bytes, bytearray)):
        password = password.encode('utf8')
    iterations = 4096
    salt = secrets.token_bytes(16)
    salted_password = hashlib.pbkdf2_hmac('sha256', password, salt, iterations)
    stored_key = hmac.new(salted_password, b'Client Key', 'sha256').digest()
    stored_key = hashlib.sha256(stored_key).digest()
    server_key = hmac.new(salted_password, b'Server Key', 'sha256').digest()
    return 'SCRAM-SHA-256$%d:%s$%s:%s' % (
        iterations,
        base64.b64encode(salt).decode('ascii'),
        base64.b64encode(stored_key).decode('ascii'),
        base64.b64encode(server_key).decode('ascii')
    )

**Comment by OrangeDog** [comment]
I currently have a workaround using a custom state+module to check and update the password hash.

**Comment by dwoz** [comment]
@OrangeDog Can you provide me with an example state that I can use to test this?

**Comment by OrangeDog** [comment]
@dwoz not sure what you mean by example state, but see linked commit.

You can see from saltstack's source code that the `states.postgres_user` state is only able to compare and set unencrypted or MD5 passwords. To use SCRAM passwords, PostgreSQL 10 or higher is required.

**Comment by OrangeDog** [comment]
Still a desired feature.

**Comment by OrangeDog** [comment]
There doesn't seem to be any python library providing just saslprep.
There is [an implementation in `pymongo`](https://github.com/mongodb/mongo-python-driver/blob/master/pymongo/saslprep.py).
