### ISSUE TITLE
Aws does not see aws instance

### ISSUE THREAD

**Issue by Wilybald** [saltstack/salt#51229]
### Description of Issue/Question
Hello, I have a problem with create and destroy instance of AWS.
If I try create instance so I get this error https://github.com/saltstack/salt/issues/39737
The error I tried to fixed by hemebond of post. Just on the 2790 of line.
`node = _get_node(instance_id=vm_['instance_id'], location=location)`
So create of part is fine now. 
But If i destroy instances so I get this 
`root@ip-172-31-46-62:~# salt-cloud -d test10`
No machines were found to be destroyed
Because salt-cloud does not see my instance of aws.

### Versions Report
```
root@ip-172-31-46-62:~# salt-cloud --versions-report
Salt Version:
            Salt: 2018.3.3
 
Dependency Versions:
 Apache Libcloud: 1.5.0
            cffi: Not Installed
        cherrypy: Not Installed
        dateutil: 2.5.3
       docker-py: Not Installed
           gitdb: 2.0.0
       gitpython: 2.1.1
           ioflo: Not Installed
          Jinja2: 2.9.4
         libgit2: Not Installed
         libnacl: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
    msgpack-pure: Not Installed
  msgpack-python: 0.4.8
    mysql-python: Not Installed
       pycparser: Not Installed
        pycrypto: 2.6.1
    pycryptodome: Not Installed
          pygit2: Not Installed
          Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
    python-gnupg: Not Installed
          PyYAML: 3.12
           PyZMQ: 16.0.2
            RAET: Not Installed
           smmap: 2.0.1
         timelib: Not Installed
         Tornado: 4.4.3
             ZMQ: 4.2.1
 
System Versions:
            dist: debian 9.6 
          locale: UTF-8
         machine: x86_64
         release: 4.9.0-8-amd64
          system: Linux
         version: debian 9.6 
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-cloud any ideas here?

**Comment by waynew** [comment]
Hi @Wilybald thanks for the report! Does https://github.com/saltstack/salt/issues/39737#issuecomment-426353931 work for you? I'm not familiar with this module at all, but it would appear that something is definitely missing somewhere!

**Comment by Wilybald** [comment]
Yes, but it works only for create instances.

**Comment by Wilybald** [comment]
Hi, I think that the problem is here `def` _get_node(name=None, instance_id=None, location=None)`
Because this call of aws.querry return error `{u'error': {'Errors': {'Error': {'Message': "The instance ID 'i-032bb50237c00aad3' does not exist", 'Code': 'InvalidInstanceID.NotFound'}}`

**Comment by Wilybald** [comment]
So, I set `DEFAULT_LOCATION=None` from `DEFAULT_LOCATION = 'us-east-1'` and everything works. Could you tell me what shoud be a problem with this constant?

**Comment by waynew** [comment]
@Wilybald You said in your previous post

> I set in the config of profile us-east-2

Is that still set? And how do you have that set? Have you looked into the `config.get_cloud_config_value` function? Is that doing the right thing?

Ultimately I guess the question here is: is this a misconfigured value or is this a bug? And, if this is a misconfigured value - is the documentation unclear?

**Comment by Wilybald** [comment]
The constant `DEFAULT_LOCATION` is in the here https://github.com/saltstack/salt/blob/develop/salt/cloud/clouds/ec2.py is not paremeter in conf. :-)

**Comment by Wilybald** [comment]
I can make pull request and you can test it. Is it possible?

**Comment by waynew** [comment]
Hi @Wilybald, I'm not sure what you're asking.

Or maybe it wasn't clear what I was asking - `DEFAULT_LOCATION` is defined in the code - but is there some place where a config value could override that?

**Comment by Wilybald** [comment]
It is simple, DEFAULT_LOCATION if is set to 'us-east-1' so the DEFAULT_LOCATION override value which set on config file....

**Comment by Wilybald** [comment]
Yes should be, but does not it do this.

**Comment by Wilybald** [comment]
So?

**Comment by waynew** [comment]
in the ec2.py if you `print(__opts__.get('location', 'no location set'))` and then

```
print(
        config.get_cloud_config_value(
            'location',
            vm_ or get_configured_provider(),
            __opts__,
            default=DEFAULT_LOCATION,
            search_global=False
        )
)
```

What do you get?

Also, how are you setting your location in the config? If the config value is set correctly in the config but it's not actually getting used, then there's definitely a problem.

**Comment by waynew** [comment]
FWIW, https://github.com/saltstack/salt/blob/develop/salt/config/__init__.py#L3271 is where the code starts for getting the value from the cloud config.
