### ISSUE TITLE
Allow git pillar files to be referenced by pillar roots top files

### ISSUE THREAD

**Issue by firelizzard18** [saltstack/salt#51254]
### Description of Feature

I want git pillar to behave like the gitfs fileserver backend. E.g. I have pillar files in a git pillar, but no top file; I have a top file in a pillar root that references pillar files in the git pillar.

- `/srv/pillar`
  - `top.sls`
- `git@example.com:my/pillar.git`
  - `shared/pillar.sls`

```yaml
# /srv/pillar/top.sls
base:
  '*':
  - shared.pillar
```

**Comment by garethgreenaway** [comment]
@terminalmage thoughts?

**Comment by terminalmage** [comment]
I don't think that is ever going to happen. ext_pillar is invoked completely separately and differently from pillar_roots, the two do not know anything about each other.
