### ISSUE TITLE
startup_states sls_list for Windows minions not launching

### ISSUE THREAD

**Issue by gitbrianb** [saltstack/salt#51251]
### Description of Issue/Question
I've tried several variants of using the "sls_list" for launching my Windows minions in AWS, but can't seem to make any work. I see a lot of documentation for running in highstates, which may apply for my needs down the road, but right now I'm merely trying to get it to change the hostname at launch time and of course later I would like it to join the domain as well, but it's become quite frustrating to keep launching these instances and no sign of error and no sign of execution.

I can launch the base/postboot.sls manually without issue, but from the "startup_states" in the /etc/salt/minion file, doesn't seem to apply. 

Any suggestions on how I can make this work?

### /etc/cloud/minion file (relevant piece):
startup_states: sls

sls_list:
  - base.postboot

### /srv/salt/base/postboot.sls
initialize_drives:
  cmd.script:
    - source: 'C:\ProgramData\Amazon\EC2-Windows\Launch\Scripts\InitializeDisks.ps1'
    - shell: powershell

change_hostname:
  system.hostname:
    - name: {{ grains['id'] }}
  module.run:
    - name: system.reboot
    - in_seconds: True
    - timeout: 1
    - order: last

### /etc/cloud.profiles.d/ec2-profiles.conf
base-east-hd3:
  provider: aws-cloud
  location: us-east-2
  image: ami-0170ffc1abff2ebdc
  size: t2.medium
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 100
      Ebs.VolumeType: gp2
  volumes:
    - {size: 200, device: /dev/sdf, type: gp2,
      tags: {"Name": "SALT-TEST D DRIVE APPLICATION",
        "Pi2-Environment": "QA"}}
    - {size: 400, device: /dev/sdg, type: gp2,
      tags: {"Name": "SALT-TEST E DRIVE DATABASE",
        "Pi2-Environment": "QA"}}
  network_interfaces:
    - DeviceIndex: 0
      AssociatePublicIpAddress: True
      SubnetId: subnet-08d67c1cadc7f948e
      SecurityGroupId:
        - sg-0641ea4055e5de2f2
  del_root_vol_on_destroy: True
  del_all_vol_on_destroy: True
  rename_on_destroy: True

### Steps to Reproduce Issue
Executing in the normal profile manual files to execute the /salt/srv/base/postboot.sls file.
salt-cloud -p base-east-hd3 salt-test01

manually this works fine:
salt 'salt-test01' state.apply base.postboot

### Versions Report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by garethgreenaway** [comment]
@saltstack/team-windows Anyone familiar with launching Windows instances via salt-cloud have experience using startup_states?

**Comment by dwoz** [comment]
@garethgreenaway I am working on reproducing this.

**Comment by guilhermerezendemarques** [comment]
I have the same problem. You resolved it ?

**Comment by gitbrianb** [comment]
> I have the same problem. You resolved it ?

No, never resolved, this and any other case I've posted got no attention. As you can see from the last thread. "Ill work on this", and nothing. Nice to see it get no attention. Price you pay for open source software I suppose, just have to deal with it until more people complain of it being an issue.
