### ISSUE TITLE
Targeting multiple grains in Salt minions using API

### ISSUE THREAD

**Issue by jmhierro** [saltstack/salt#51269]
### Description of Issue/Question
In our infrastructure, we set multiples grains on the minion including an "environment" and "app" grain. When we use the cli, we can get the correct minions using:

`salt -C "G@app:middle_tier_1 and G@environment:dev" test.ping`

But if we try to use the cherrypy api, only got a result if set only one target like:

`[{"client":"local","tgt_type":"grain","fun":"test.ping","tgt":"G@app:middle_tier_1"}]`
or
`[{"client":"local","tgt_type":"grain","fun":"test.ping","tgt":"G@environment:dev"}]`
with multiples one, don't get any

`[{"client":"local","tgt_type":"grain","fun":"test.ping","tgt":"G@app:middle_tier_1 and G@environment:dev"}]
[{"client":"local","tgt_type":"grain","fun":"test.ping","tgt":["G@app:middle_tier_1","G@environment:dev"]}]`

### Setup
According with the documentation, i can use a list in the tgt paramenter.
I have looked their documentation fairly extensively and have found no examples of this type of minion targeting. Is this even possible, and if so, how would I go about doing it?

### Steps to Reproduce Issue
Try to target minions using multiples grains filters.

### Versions Report
salt-master 2018.3.2 (Oxygen) 
salt-api 2018.3.2 (Oxygen)
python-cherrypy3/oldstable,now 3.5.0-1 all

**Comment by max-arnold** [comment]
In the command line you used the `-C` flag, which means compound matching. Try using the same type for API: `"tgt_type": "compound"`.

The full list of possible `tgt_type` values can be found here: https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.cmd

**Comment by jmhierro** [comment]
Thanks max-arnold! It's work!

**Comment by jmhierro** [comment]
Sorry, forget to close it
