### ISSUE TITLE
Misleading warning with salt-run from non-root saltmaster

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#51268]
### Description of Issue/Question
My saltmaster runs under a dedicated user with a noIogin shell, and when I recently upgraded from 2016.11 to the latest RC, commands like `sudo salt-run fileserver.update` started issuing lots of warnings:

```
tarjei@saltmaster:~$ sudo salt-run fileserver.update
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.
[WARNING ] Attempt to run a shell command with what may be an invalid shell! Check to ensure that the shell </usr/sbin/nologin> is valid for this user.

True
```
The same happens if I run `sudo -u saltmaster salt-run fileserver.update`, not sure which one is technically more correct for a non-root saltmaster. The update does seem to actually happen though, although it's a bit hard to say if it's because of the `salt-run` I did or just the regular gitfs updater that actually performs it. 

Why does `salt-run` try to run a shell for the saltmaster in the first place? I don't want my saltmaster to have a shell as it's not a user one should be able to log in as.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
I think you don't need anything beyond a saltmaster with the latest RC with gitfs trying to run `fileserver.update`.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2019.2.0rc1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: 2.3.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-6-amd64
         system: Linux
        version: debian 9.4 
```

**Comment by garethgreenaway** [comment]
@terminalmage Thoughts?

**Comment by terminalmage** [comment]
That is from a shell check in `salt/modules/cmdmod.py`, which has been present in Salt for nearly 5 years. My guess is that `salt-run` is generating grains for some purpose, which is causing those log messages.

**Comment by terminalmage** [comment]
Grains generation uses a `_run_quiet()` helper function in `salt/modules/cmdmod.py` to run the commands without any logging of the commands being run or their output. I modified the shell check so that it doesn't happen when quieted logging is desired.

The change is in https://github.com/saltstack/salt/pull/51491.
