### ISSUE TITLE
How to properly fix API?

### ISSUE THREAD

**Issue by isbm** [saltstack/salt#51273]
### Description of Issue/Question

In 2019.2 Fluorine, when I call just a `ping.test` using `auto` authentication, but also want to insert a metadata in there, now I get crash at master: 

```
salt.exceptions.SaltInvocationError: 'metadata' is an invalid keyword  argument for
'salt.loaded.int.auth.auto.auth'
```

This is the reproducer:

```
curl http://localhost:9080/run \
    -X POST \
    -H 'Accept: application/json' \
    -H 'Content-Type: application/json' \
    -d '[{"eauth": "auto", "tgt":"*", "password":"", "metadata":"Have some donuts!", \
    "tgt_type":"glob", "client":"local", "fun":"test.ping", "username":"admin"}]'
```

As you can see, I want my `test.ping` also eat some donuts metadata. So essentially, I send the following JSON:

```json
[
  {
    "eauth": "auto",
    "tgt": "*",
    "username":"admin",
    "password": "",
    "metadata": "Have some donuts!",
    "tgt_type": "glob",
    "client": "local",
    "fun": "test.ping"
  }
]
```

So since [documentation says](https://docs.saltstack.com/en/latest/ref/netapi/all/salt.netapi.rest_cherrypy.html#salt.netapi.rest_cherrypy.app.Run) "accept username/password/eauth **OR** token", I would expect that metadata should be set alongside with the username and password. But instead of 200/true I receive 500/ISE error.

In current design there seem two ways of fixing this:

- Add "metadata" keyword to the [white-list of of allowed keywords](https://github.com/saltstack/salt/blob/develop/salt/auth/__init__.py#L41-L52) (and then this works).
- Make all authentication modules [accept also `**kwargs`](https://github.com/saltstack/salt/blob/develop/salt/auth/auto.py#L8).

But to me both ways seem wrong. Because nor I want some metadata throw donuts at my authentication module, neither I like to throw at my authentication module literally everything.

This sort of API request would probably make more sense:

```json
[
  {
    "eauth": {
        "password": "",
        "username": "admin",
        "module": "auto"
    },
    "client": "local",
    "fun": "test.ping",
    "metadata": "Have some donuts!",
    "tgt_type": "glob",
    "tgt": "*"
  }
]
```

But at the moment I do not know which way we would like to fix it (without reverting everything on this topic back to 2018.3 when it was working). @thatch45 @garethgreenaway @dwoz  any ideas here?

**Comment by thatch45** [comment]
We need to get that fixed. Let me look into this

**Comment by thatch45** [comment]
@isbm the fix should be merged, can you please verify?

**Comment by isbm** [comment]
@thatch45 this should be part of RC1.

**Comment by isbm** [comment]
@thatch45 however, this doesn't fix very much, unless you whitelist basically everything... Here is another one example that doesn't work:

```
curl http://localhost:9080/run \
   -X POST \
   -H 'Accept: application/json' \
   -H 'Content-Type: application/json' \
   -d '[{"eauth":"auto", "password":"", \ 
       "id_":"some_more_donuts", "client":"wheel", \
       "force":false, "fun":"key.gen_accept", \
       "username":"admin"}]'
```

This is also a regression, because on 2018.3 it works.

**Comment by thatch45** [comment]
Should the validation be removed then?

**Comment by garethgreenaway** [comment]
This was something we had a depreciation notice in for awhile.

**Comment by isbm** [comment]
@garethgreenaway `"Some exception handling minion payload"` is not the best return. How this should work as of today?

**Comment by amannch** [comment]
> ```
> curl http://localhost:9080/run \
>    -X POST \
>    -H 'Accept: application/json' \
>    -H 'Content-Type: application/json' \
>    -d '[{"eauth":"auto", "password":"", \ 
>        "id_":"some_more_donuts", "client":"wheel", \
>        "force":false, "fun":"key.gen_accept", \
>        "username":"admin"}]'
> ```

When I try this on 2018.3 it works and I get no deprecation warning whatsoever. That means it **should** work on 2019.2 aswell, right?

**Comment by isbm** [comment]
@thatch45 so how do we proceed here? If there was no deprecation warning thrown (at least I cannot see any on 2018.3), then I would propose to let the validation allow all these cases for now. Then in `develop` we can fix it for the next release.

What do you say?

**Comment by KChandrashekhar** [comment]
Closing as below fix is merged, which addresses this issue as well
https://github.com/saltstack/salt/pull/51318
