### ISSUE TITLE
Replace pycrypto with cryptography

### ISSUE THREAD

**Issue by aikchar** [saltstack/salt#51301]
### Description of Issue/Question

pycrypto has not been updated on PyPI since 2013. GitHub is alerting my repo, which uses Salt, because pycrypto has a known vulnerability. Replacing with [cryptography](https://pypi.org/project/cryptography/) is a good option since it's more actively maintained. This is a more urgent issue than previously reported (https://github.com/saltstack/salt/issues/30287).

### Setup
N/A

### Steps to Reproduce Issue
Install Salt version 2018.3.3.

### Versions Report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 3.7.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.0
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.2 (default, Dec 30 2018, 08:55:50)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 18.2.0
         system: Darwin
        version: 10.14.2 x86_64

**Comment by garethgreenaway** [comment]
@aikchar Thanks for the report. As part of the Oxygen release we migrated to favor M2Crypto, , which is actively maintained, but still maintain compatibility with pycrypto as it is still installed by default on many distributions.
@DmitryKuzmenko @saltstack/team-core Any thoughts/comments here?

**Comment by waynew** [comment]
Just from a library perspective, I have some preference for cryptograph as I really appreciate their approach - having the primitives "hidden", and exposing APIs that should make you at least be doing the right things.

That being said, I have no experience with what or how we're using the crypto libraries in Salt (yet), so my opinion is specifically preference for the library.

**Comment by DmitryKuzmenko** [comment]
I agree with @garethgreenaway. I mean that we have support of M2Crypto and M2Crypto is the default library we use. So there is nothing critical and this issue looks like a feature request like the mentioned #30287.

**Comment by waynew** [comment]
Oh, yeah, I'd say this is a dupe of #30287 - feel free to reopen if you disagree 🙂
