### ISSUE TITLE
Drive encryption and volume labels on AWS instance launch

### ISSUE THREAD

**Issue by gitbrianb** [saltstack/salt#51310]
### Description of Issue/Question
Looking to manage volumes names and encryption, but preferable in a state file as opposed to using the 'salt-cloud' command with individual change requests. Is that possible? I didn't see the options documented and have failed with a few attempts on my own with different syntax.

### Setup
Here is my profile file now:
```
base-east-hd3:
  provider: aws-cloud
  location: us-east-2
  image: ami-0170ffc1abff2ebdc
  size: t2.medium
  block_device_mappings:
    - DeviceName: /dev/sda1
      Ebs.VolumeSize: 100
      Ebs.VolumeType: gp2
  volumes:
    - {size: 200, device: /dev/sdf, type: gp2,
      tags: {"Name": "SALT-TEST D DRIVE APPLICATION",
        "Pi2-Environment": "QA"}}
    - {size: 400, device: /dev/sdg, type: gp2,
      tags: {"Name": "SALT-TEST E DRIVE DATABASE",
        "Pi2-Environment": "QA"}}
  network_interfaces:
    - DeviceIndex: 0
      AssociatePublicIpAddress: True
      SubnetId: subnet-08d67c1cadc7f948e
      SecurityGroupId:
        - sg-0641ea4055e5de2f2
  del_root_vol_on_destroy: True
  del_all_vol_on_destroy: True
  rename_on_destroy: True
  tag: {'Pi2-BuiltBy': 'Brian Beard',
    'PQ-BizUnit': 'XXXXXXXX',
    'Pi2-Customer': 'XXXXXXX',}
```
What I would like is to do is encrypt the volumes in the profile options above and also label the root volume with a name and/or tags like I have for the other attached volumes. Can this be done?

### Steps to Reproduce Issue
I've tried to use drive mapping options like:
Ebs.Encryption: True

And for the naming of the root drive and tagging, not sure how that would apply either. Is the only way to make this work is to launch the server as I have it configured and then encrypt the volumes and change the names with individual 'salt-cloud' commands for volume management after the server has been launched and built with salt states?

### Versions Report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by garethgreenaway** [comment]
@gitbrianb Thanks for the report.  There is an option available when using salt-cloud to create a volume that is encrypted, it should be an available option when using profiles.  https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.ec2.html#salt.cloud.clouds.ec2.create_volume
@saltstack/team-cloud FYI.
