### ISSUE TITLE
saltstack/salt on lgtm.com

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#51350]
### Description of Question

Does the salt dev team know of the existence of this:
https://lgtm.com/projects/g/saltstack/salt/alerts/?mode=list

Looks interesting and maybe usefull?

**Comment by dwoz** [comment]
@aboe76 Thanks for pointing this out. We already have linter and code climate running on all pull requests.

@saltstack/team-core Thoughts on if we should add this?

**Comment by waynew** [comment]
At a glance it looks pretty neat. I know we've been having some discussion around some linter features getting disabled, this might be able to help with that.

It would also help with being able to point to on PRs, e.g. "Please fix these lint errors before we merge"

I'm sure there's a learning curve to it, and the one thing that I question is the possibility that a bunch of those may be false positives.

But in general if it's 1) free, and 2) improves our community then I'm 💯 for it.
