### ISSUE TITLE
saltstack state.apply command showing u.junos.conn error, but CONF is successfully applied to router via netconf 

### ISSUE THREAD

**Issue by juthewiz** [saltstack/salt#51355]
is it possible this could be related to a bug? i am getting the LockError when attempting to run state.apply but the user it is referring to is a super user

```
/srv/pillar % sudo salt sj1e2 state.apply DrainSJ1SG1secondary

sj1e2:

----------

ID: Drain SJ1SG1 secondary

Function: netconfig.managed

Result: False

Comment: Cannot execute "load_merge_candidate" on *.*.*.* as SALT. Reason: LockError(severity: error, bad_element: lock-configuration, message: permission denied)!

Configuration discarded.

Started: 15:09:34.276672

Duration: 1146.165 ms

Changes:

----------

diff:



Summary for sj1e2

------------

Succeeded: 0 (changed=1)

Failed: 1

------------

Total states run: 1

Total run time: 1.146 s

ERROR: Minions returned with non-zero exit code
```

This is the juniper device config related to user SALT

```
set system login user SALT uid 2003

set system login user SALT class super-user

set system services netconf ssh
```

here is the sj1e2 (proxy-2.sls) and the Top.sls under /srv/pillar

```
proxy:

proxytype: napalm

driver: junos

host: *.*.*.*

username: SALT

password: ******

port: 830



base:

'sj1e2':

- proxy-2



```

When running -l debug with the state.apply command there are two things that stick out besides the LockError
```

State 'netconfig.managed' was not found in SLS 'DrainSJ1SG1secondary'
Reason: 'netconfig' __virtual__ returned False: "netconfig"" (/usr/lib/python2.7/dist-packages/salt/states/netconfig.pyc) cannot be loaded: NAPALM is not installed or not running in a (proxy) minion



```
but netconfig.managed is in DrainSJ1SG1secondary.sls here

```


DrainSJ1SG1secondary:
netconfig.managed:
- template_name: salt://DrainSJ1SG1secondary.conf

```

also napalm is installed on the minion and the master cut a lot of lines out
```

saltminion% pip install napalm
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Requirement already satisfied: napalm in ./.local/lib/python2.7/site-packages (2.3.3)
Requirement already satisfied: asn1crypto>=0.21.0 in ./.local/lib/python2.7/site-packages (from cryptography>=1.5->paramiko>=1.15.2->junos-eznc>=2.1.5->napalm) (0.24.0)
[2019-01-26 18:18:43-0800] saltminion% salt-minion --version
salt-minion 2018.3.3 (Oxygen)
```

and above i posted the proxy-2.sls (sj1e2) which shows the proxytype as napalm

which is is the /srv/pillar dir on the master along with the top.sls. also i could do the configure exclusive from the SALT user name on the device cli

```
SALT> configure exclusive
warning: uncommitted changes will be discarded on exit
Entering configuration mode

{master}[edit]
SALT#
```

i can run other modules fine but its state.apply that is specifically giving me issues, so connections to the device isnt a issue.

this is from the master 

``` sudo salt --versions-report
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Dec  4 2017, 14:50:18)
   python-gnupg: 0.3.8
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: ISO-8859-1
        machine: x86_64
        release: 4.4.0-124-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-network any ideas here?

**Comment by juthewiz** [comment]
Now i am getting the following errors 

```
bjn-sj1-e2:
----------
          ID: DrainSJ1SG1secondary
    Function: netconfig.managed
      Result: False
     Comment: Cannot execute "load_merge_candidate" on 199.48.152.3 as SALT. Reason: [{'source': None, 'message': "invalid interface type in '<xe-0/0/7>'", 'bad_element': '<xe-0/0/7>', 'severity': 'error', 'edit_path': None}, {'source': None, 'message': 'error recovery ignores input until this point', 'bad_element': '}', 'severity': 'error', 'edit_path': None}, {'source': None, 'message': 'mgd: statement must contain additional statements', 'bad_element': None, 'severity': 'warning', 'edit_path': None}, {'source': None, 'message': "invalid interface type in '<xe-0/0/7>'", 'bad_element': '<xe-0/0/7>', 'severity': 'error', 'edit_path': None}, {'source': None, 'message': 'error recovery ignores input until this point', 'bad_element': '}', 'severity': 'error', 'edit_path': None}, {'source': None, 'message': 'mgd: statement must contain additional statements', 'bad_element': None, 'severity': 'warning', 'edit_path': None}, {'source': None, 'message': 'invalid value', 'bad_element': '}', 'severity': 'error', 'edit_path': None}]!
              Configuration discarded.
     Started: 09:47:37.147257
    Duration: 1425.097 ms
     Changes:
              ----------
              diff:

Summary for bjn-sj1-e2
------------
Succeeded: 0 (changed=1)
Failed:    1

```

**Comment by wasabi222** [comment]
It sounds like we cleared this up via slack. The fix was to add `multiprocessing: false` to the proxy config, and the error above was due to wrapping the interface name in `<>`, which is invalid junos syntax. Once they were removed, the state rendered as expected. @juthewiz can you confirm this issue can be closed?

**Comment by juthewiz** [comment]
> It sounds like we cleared this up via slack. The fix was to add `multiprocessing: false` to the proxy config, and the error above was due to wrapping the interface name in `<>`, which is invalid junos syntax. Once they were removed, the state rendered as expected. @juthewiz can you confirm this issue can be closed?

Hey actually i am getting a new error. i am no longer getting the lock error. please see below


[DEBUG   ] return event: {u'bjn-sj1-e2': {u'jid': u'20190128174643448211', u'retcode': 2, u'ret': {u'netconfig_|-DrainSJ1SG1secondary_|-DrainSJ1SG1secondary_|-managed': {u'comment': u'Cannot execute "load_merge_candidate" on *.*.*.* as SALT. Reason: LockError(severity: error, bad_element: None, message: configuration database locked by:\n  SALT terminal  (pid 53129) on since 2019-01-28 17:46:44 PST\n      exclusive)!\nCannot execute "discard_config" on *.*.*.* as SALT. Reason: RpcError(severity: error, bad_element: None, message: configuration database locked by:\n  SALT terminal  (pid 53129) on since 2019-01-28 17:46:44 PST\n      exclusive)!\n\nConfiguration diff:\n\n[edit protocols rsvp interface xe-0/0/7.0]\n+    disable;\n[edit protocols isis interface xe-0/0/7.0]\n+     passive;', u'pchanges': {u'diff': u'[edit protocols rsvp interface xe-0/0/7.0]\n+    disable;\n[edit protocols isis interface xe-0/0/7.0]\n+     passive;'}, u'name': u'DrainSJ1SG1secondary', u'start_time': u'17:46:44.634489', u'result': False, u'duration': 1085.385, u'__run_num__': 0, u'__sls__': u'DrainSJ1SG1secondary', u'changes': {}, u'__id__': u'DrainSJ1SG1secondary'}}, u'out': u'highstate'}}

**Comment by juthewiz** [comment]
> It sounds like we cleared this up via slack. The fix was to add `multiprocessing: false` to the proxy config, and the error above was due to wrapping the interface name in `<>`, which is invalid junos syntax. Once they were removed, the state rendered as expected. @juthewiz can you confirm this issue can be closed?

Hey actually i am getting a new error. It is stating there is a config lock by the user SALT which is the login i have assigned the proxy.
`
[DEBUG   ] return event: {u'
***-sj1-e2': {u'jid': u'20190128174643448211', u'retcode': 2, u'ret': {u'netconfig_|-DrainSJ1SG1secondary_|-DrainSJ1SG1secondary_|-managed': {u'comment': u'Cannot execute "load_merge_candidate" on *.*.*.* as SALT. Reason: LockError(severity: error, bad_element: None, message: configuration database locked by:\n  SALT terminal  (pid 53129) on since 2019-01-28 17:46:44 PST\n      exclusive)!\nCannot execute "discard_config" on *.*.*.* as SALT. Reason: RpcError(severity: error, bad_element: None, message: configuration database locked by:\n  SALT terminal  (pid 53129) on since 2019-01-28 17:46:44 PST\n      exclusive)!\n\nConfiguration diff:\n\n[edit protocols rsvp interface xe-0/0/7.0]\n+    disable;\n[edit protocols isis interface xe-0/0/7.0]\n+     passive;', u'pchanges': {u'diff': u'[edit protocols rsvp interface xe-0/0/7.0]\n+    disable;\n[edit protocols isis interface xe-0/0/7.0]\n+     passive;'}, u'name': u'DrainSJ1SG1secondary', u'start_time': u'17:46:44.634489', u'result': False, u'duration': 1085.385, u'__run_num__': 0, u'__sls__': u'DrainSJ1SG1secondary', u'changes': {}, u'__id__': u'DrainSJ1SG1secondary'}}, u'out': u'highstate'}}
`

**Comment by juthewiz** [comment]
```
Cannot execute "load_merge_candidate" on *.*.*.* as SALT. Reason: LockError(severity: error, bad_element: None, message: configuration database locked by:
                SALT terminal  (pid 53129) on since 2019-01-28 17:46:44 PST
                    exclusive)!
              Cannot execute "discard_config" on *.*.*.* as SALT. Reason: RpcError(severity: error, bad_element: None, message: configuration database locked by:
                SALT terminal  (pid 53129) on since 2019-01-28 17:46:44 PST
                    exclusive)!

              Configuration diff:

              [edit protocols rsvp interface xe-0/0/7.0]
              +    disable;
              [edit protocols isis interface xe-0/0/7.0]
              +     passive;
     Started: 17:46:44.634489

```

**Comment by juthewiz** [comment]
so i ran 
`request system logout pid 53129
`
then ran the same sudo salt state.apply line and got the following 

```
bjn-sj1-e2:
----------
          ID: DrainSJ1SG1secondary
    Function: netconfig.managed
      Result: False
     Comment: Cannot execute "compare_config" on 199.48.152.3 as SALT. Reason: ConnectClosedError(199.48.152.3)!
     Started: 18:03:53.274180
    Duration: 48.586 ms
     Changes:
              ----------
              diff:
                  None

Summary for bjn-sj1-e2
------------
Succeeded: 0 (changed=1)
Failed:    1
```

**Comment by juthewiz** [comment]
i ran the following from the juniper device then ran the sudo salt command again and received a new error

`request system logout pid 53129
`
```
bjn-sj1-e2:
----------
          ID: DrainSJ1SG1secondary
    Function: netconfig.managed
      Result: False
     Comment: Cannot execute "compare_config" on *.*.*.* as SALT. Reason: ConnectClosedError(*.*.*.*)!
     Started: 18:03:53.274180=
    Duration: 48.586 ms
     Changes:
              ----------
              diff:
                  None

Summary for bjn-sj1-e2
------------
Succeeded: 0 (changed=1)
Failed:    1

```
`

**Comment by juthewiz** [comment]
i ran the following from the juniper device then ran the sudo salt command again and received a new error. i found https://github.com/Juniper/py-junos-eznc/issues/703 which sounds kind of related @wasabi222 

`request system logout pid 53129
`
```
comment": "Cannot execute \"load_merge_candidate\" on *.*.*.* as SALT. Reason: Premature end of data in tag rpc-reply line 1, line 27, column 30 (line 27)!\nConfiguration discarded."

```
`

**Comment by juthewiz** [comment]
i ran the following from the juniper device then ran the sudo salt command again and received a new error. i found https://github.com/Juniper/py-junos-eznc/issues/703 which sounds kind of related @wasabi222 

`request system logout pid 53129
`
```
comment": "Cannot execute \"load_merge_candidate\" on *.*.*.* as SALT. Reason: Premature end of data in tag rpc-reply line 1, line 27, column 30 (line 27)!\nConfiguration discarded."

```
logs from the router 
```

Jan 28 18:21:32  bjn-sj1-e2-re0 mgd[52887]: UI_LOAD_EVENT: User 'SALT' is performing a 'rollback'
Jan 28 18:21:33  bjn-sj1-e2-re0 mgd[52887]: UI_LOAD_EVENT: User 'SALT' is performing a 'rollback'

```

**Comment by juthewiz** [comment]
i ran the following from the juniper device then ran the sudo salt command again and received a new error. i found https://github.com/Juniper/py-junos-eznc/issues/703 which sounds kind of related @wasabi222 

`request system logout pid 53129
`
```
comment": "Cannot execute \"load_merge_candidate\" on *.*.*.* as SALT. Reason: Premature end of data in tag rpc-reply line 1, line 27, column 30 (line 27)!\nConfiguration discarded."

```
logs from the router 
```

Jan 28 18:21:32 sj1-e2 mgd[52887]: UI_LOAD_EVENT: User 'SALT' is performing a 'rollback'
Jan 28 18:21:33 sj1-e2 mgd[52887]: UI_LOAD_EVENT: User 'SALT' is performing a 'rollback'

```

**Comment by mirceaulinic** [comment]
```
Jan 28 18:21:32 sj1-e2 mgd[52887]: UI_LOAD_EVENT: User 'SALT' is performing a 'rollback'
Jan 28 18:21:33 sj1-e2 mgd[52887]: UI_LOAD_EVENT: User 'SALT' is performing a 'rollback'
```

These are executed when discarding the configuration changes.

The other error:

```
Premature end of data in tag rpc-reply line 1, line 27, column 30 (line 27)!
```

Is thrown by the operating system (Junos) and you'd probably need to investigate (potentially with the help of JTAC) why NETCONF returns a malformed XML document. In other words, unfortunately this is not something that can be solved in Salt: best case it may be resolved in [junos-eznc](https://github.com/Juniper/py-junos-eznc), worst case there's a bug in the Junos version you're running.

**Comment by juthewiz** [comment]
thanks i have opened a SR with Juniper. if you want i will leave this open and report the Juniper PR if one is created if anyone else runs into something similar while running the same junos 17.1R2S7

**Comment by juthewiz** [comment]
@mirceaulinic yes i have some MX10ks in Amsterdam running 17.4R1S4.2 so i will try on the secondary router and transport circuit tonight and provide more feedback there

**Comment by juthewiz** [comment]
@wasabi222 @mirceaulinic when i change the Drain*.sls from `netconf.managed: ` to `junos.install-config` i get a new error when running sudo salt * state.apply . please see below

 sudo salt ***-sj1-e2 state.apply DrainSJ1SG1secondary
***-sj1-e2:
----------
          ID: DrainSJ1SG1secondary
    Function: junos.install_config
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1913, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/junos.py", line 330, in install_config
                  ret['changes'] = __salt__['junos.install_config'](name, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/junos.py", line 805, in install_config
                  conn = __proxy__['junos.conn']()
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1155, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 106, in __getitem__
                  return self._dict[key]
              KeyError: u'junos.conn'
     Started: 16:57:17.874687
    Duration: 2.792 ms
     Changes:

Summary for ***-sj1-e2
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   2.792 ms
ERROR: Minions returned with non-zero exit code

**Comment by wasabi222** [comment]
Did you switch to using the junps proxy or are you still using napalm? If the latter, you should instead use net.load_template instead of junos.load_config, or else back port the new napalm module and use napalm.junos_call - let me know if you need help doing this.

**Comment by juthewiz** [comment]
@wasabi222 how do i import the new napalm module and use napalm.junos_call? i did switch it to the junos proxy for the junos.install_config but i have now switched it back to napalm and will try the net.load_template

also Juniper is still working on the SR and i have provided them a lot of data plus we have done a screen share walk through for the initial problem

**Comment by juthewiz** [comment]
@wasabi222 would the SLS look like 
```
DrainSJ1SG1secondary:
 net.load_template:
 - name: salt://DrainSJ1SG1secondary.conf

```

and running` sudo salt sj1-e2 net.load_template DrainSJ1SG1secondary`

**Comment by juthewiz** [comment]
i believe the junos driver was the issue for the above like you said. once i double checked everything and made corrections i am now seeing
```

          ID: DrainSJ1SG1secondary
    Function: netconfig.managed
      Result: False
     Comment: Cannot execute "compare_config" on **** as SALT. Reason: ConnectClosedError(****)!
     Started: 17:47:58.189693
    Duration: 903.04 ms
     Changes:
              ----------
              diff:
                  None

```



```
Jan 30 17:47:59   mgd[20190]: UI_LOAD_EVENT: User 'SALT' is performing a 'rollback'
Jan 30 17:48:00   mgd[20341]: UI_LOAD_EVENT: User 'SALT' is performing a 'rollback'
Jan 30 17:48:00   mgd[20190]: UI_LOAD_EVENT: User 'SALT' is performing a 'rollback'
Jan 30 17:48:38   sshd[60305]: Accepted password for SALT from **** port 22813 ssh2


```

**Comment by juthewiz** [comment]
Just an update Juniper is still analyzing my netconf logs related to the rpc errors coming from my juniper device when executing state.apply

**Comment by juthewiz** [comment]
@wasabi222 @mirceaulinic on the devices running 17.4R1 they arent having the same errors. They are able to succesfully load/commit CONF to routers via netconf...but the saltstack output shows that it fails due to NAPALM minion/proxy not being installed...even though the state.apply was successful https://github.com/saltstack/salt/issues/51482

juniper has escalated the original issue with 17.1R2. which is pending updates from juniper

**Comment by juthewiz** [comment]
actually it seems to be a salt issue just like #51482 . after updating proxy port in /srv/pillar/poxy[1-7].sls i can now successfully apply CONF files via sudo salt host state.apply. but again the saltstack output like #51482 shows errors. even though the conf file was successfully applied to the router in draining and undraining

showing what was applied by SALT via netconf from router cli

```
  0                    2019-02-03 14:31:24 PST by SALT via netconf commit synchronize
  1                    2019-02-03 14:22:43 PST by SALT via netconf commit synchronize

sj1-e2#rollback 1

sj1-e2# show | compare
[edit protocols rsvp interface xe-0/0/7.0]
+    disable;
[edit protocols isis interface xe-0/0/7.0]
+     passive;
```
after drain via saltstack master

```
show rsvp interface
RSVP interface: 3 active
                          Active  Subscr- Static      Available   Reserved    Highwater
Interface          State  resv    iption  BW          BW          BW          mark
et-0/3/0.0             Up       5   100%  40Gbps      37.75Gbps   2.25Gbps    29Gbps
xe-0/0/0.0             Up       6   100%  10Gbps      9.25Gbps    750Mbps     10Gbps
xe-0/0/7.0             Up       0   100%  10Gbps      10Gbps      0bps        0bps
```

after undraining via saltstack master 

```
show rsvp interface
RSVP interface: 3 active
                          Active  Subscr- Static      Available   Reserved    Highwater
Interface          State  resv    iption  BW          BW          BW          mark
et-0/3/0.0             Up       5   100%  40Gbps      39Gbps      1000Mbps    29Gbps
xe-0/0/0.0             Up       6   100%  10Gbps      9.25Gbps    750Mbps     10Gbps
xe-0/0/7.0             Up       2   100%  10Gbps      8.25Gbps    1.75Gbps    1.75Gbps
```


```

bjn-sj1-e2:
----------
          ID: UnDrainSJ1SG1secondary
    Function: junos.install_config
        Name: salt://UnDrainSJ1SG1secondary.conf
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1913, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1898, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/junos.py", line 330, in install_config
                  ret['changes'] = __salt__['junos.install_config'](name, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/junos.py", line 805, in install_config
                  conn = __proxy__['junos.conn']()
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1155, in __getitem__
                  func = super(LazyLoader, self).__getitem__(item)
                File "/usr/lib/python2.7/dist-packages/salt/utils/lazy.py", line 106, in __getitem__
                  return self._dict[key]
              KeyError: u'junos.conn'
     Started: 14:31:16.136583
    Duration: 1.204 ms
     Changes:

Summary for bjn-sj1-e2
------------
Succeeded: 0
Failed:    1
```

**Comment by wasabi222** [comment]
here's how you backport the most recent napalm module with the ability to call `napalm.junos_call` to do what you're looking for (from my dev box):

```
root@master:~# cd /srv/salt/
root@master:/srv/salt# mkdir _modules
root@master:/srv/salt# cd _modules/
root@master:/srv/salt/_modules# wget https://raw.githubusercontent.com/saltstack/salt/develop/salt/modules/napalm_mod.py
root@master:/srv/salt/_modules# ls napalm_mod.py
napalm_mod.py
root@master:/srv/salt/_modules# salt-call saltutil.sync_modules
local:
    - modules.napalm_mod
root@master:/srv/salt/_modules# pip install jxmlease
root@master:/srv/salt/_modules# [restart proxy connections here]
root@master:/srv/salt# salt junos napalm.junos_call install_config salt://juliusdemo.txt
junos:
    ----------
    message:
        Successfully loaded and committed!
    out:
        True
root@master:/srv/salt# salt junos napalm.junos_call cli 'show system rollback compare 1 0'
junos:
    ----------
    message:

        [edit protocols]
        +   rsvp {
        +       interface et-0/0/0.0 {
        +           disable;
        +       }
        +   }
        +   isis {
        +       interface et-0/0/0.0 {
        +           passive;
        +       }
        +   }
    out:
        True
root@master:/srv/salt#
```

Here are the docs for the junos_call function: https://docs.saltstack.com/en/develop/ref/modules/all/salt.modules.napalm_mod.html#salt.modules.napalm_mod.junos_call

**Comment by juthewiz** [comment]
thanks @wasabi222 for the backport walk-through. but i can now  execute the state.apply module successfully so i will keep using that...it just produces an error like it wasn't successful, but in reality t was.
