### ISSUE TITLE
[Question] Is there a requisite for executing a state when a number of other states don't have any changes?

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#51371]
Essentially, I'd like to have a state execute if a number of other states return that there were no changes. So essentially the opposite of `onchanges_any`. Is this possible in some way?

**Comment by garethgreenaway** [comment]
So something like an `onchanges_none`?

**Comment by arizvisa** [comment]
Not really the suffix which refers to the states that it would track, but the prefix which corresponds to the changes as mentioned in the topic.

So like something that would trigger on `test.succeed_without_changes` and \_not\_ on `test.succeed_with_changes`. I guess that would also imply that it would also include `test.fail_without_changes`.

**Comment by arizvisa** [comment]
I'm assuming by the unresponsivenes that adding something like this is not as easy as one would initially think?

There's two ways to do this, one of them is to add a sort-of meta-requisite that inverts the conditions of all of its sub-requisites (which uglies up the schema), and the other way is to add an explicit condition which appears to add another pass into the state compiler in order to deal with `test.succeed_without_changes` (and not `test.succeed_with_changes`).

Adding either of these appears to be a chore, however, as it seems that it's not as easy as changing the semantics of a few edges in a dependency graph and instead would consist of adding another pass to recurse through said dependencies in order to sort them into place? This will probably kill performance + memory even moreso...

Sounds about right?

**Comment by arizvisa** [comment]
Closing this as it didn't seem like there was any interest in this type of requisite. I think my original need for this was to distinguish between `test.success_with_changes` and `test.success_without_changes`.

I might've been wanting this to multiplex states iirc, but the requisite system is already complex and I don't think it's safe to patch in a new requisite like this in after the system has already been designed and stabilized. In fact, I think It'd be much more safe/stable to plan all the potential requisites for the dependency graph ahead of time, and then implement it. So at this point, the boat has already left the dock...
