### ISSUE TITLE
mac_service can't tell the difference between agents and daemons with the same name.

### ISSUE THREAD

**Issue by weswhet** [saltstack/salt#51373]
### Description of Issue/Question

If you have a mac_service agent and daemon with the same Label name salt will not be able to notice the agent as the list of available services is kept in a dictionary with the label name as the key. Since the Daemons are processed after the Agents the Daemon overwrites the agent. 

Just making this issue to make it visible to others.

@Ch3LL Thinking about changing the services to be stored with file_path as the main identifier key. Thoughts?

**Comment by Ch3LL** [comment]
will an agent and daemon on mac always contain a file_path?

**Comment by weswhet** [comment]
I believe so yes. That’s the only way to create one that I know off.

**Comment by Ch3LL** [comment]
Sounds good to me then :)
