### ISSUE TITLE
salt-cloud azure documentation has dead link

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#51388]
### Description of Issue/Question
On this page `https://docs.saltstack.com/en/latest/topics/cloud/azure.html#managing-service-certificates`
there is a link labeled "Manage Certificates" that points to `https://msdn.microsoft.com/en-us/library/azure/gg981929.aspx`

That link is dead.

### Steps to Reproduce Issue
Browse to `https://docs.saltstack.com/en/latest/topics/cloud/azure.html#managing-service-certificates` then click on the `Manage certificates` link.

**Comment by garethgreenaway** [comment]
Closing this out as the documentation was fixed and is available in 2018.3 and later branches.
