### ISSUE TITLE
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding.

### ISSUE THREAD

**Issue by iadityagrover** [saltstack/salt#51463]
### Setup
All the highstates are pushed from master syndic using cron to the minions.
command:
salt -C 'G@os_family:RedHat and ( G@adbe:network_info:*:region:<region> or I@adbe:hostinfo_itcloud:cloud_location:<region>)' state.highstate --batch-size 30 -t 240

### Steps to Reproduce Issue
I am just running highstate using grains based on OS and region which targets around 4000 servers with batch size 25 and timeout 300. I dont think you can reproduce the error unless you have that big enviroment. 

### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 12 2018, 05:31:16)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo

**Comment by iadityagrover** [comment]
![salt](https://user-images.githubusercontent.com/21380656/52119577-7f2d9680-263f-11e9-9e53-c4f7848621fe.jpg)

**Comment by dwoz** [comment]
@iadityagrover Thanks for reporting the issue. I'm editing the issue title. The original title was.

```
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
```

**Comment by dwoz** [comment]
@iadityagrover if you increase the timeout of the command does the state finish?

**Comment by IvanShokin** [comment]
Hello! We have the same problem. There are 10,000 minions in our setup. Increasing the timeout does not help. Please update the ticket.
