### ISSUE TITLE
nftables state not indempotent

### ISSUE THREAD

**Issue by antifob** [saltstack/salt#51483]
### Description of Issue/Question

When using the `nftables` state, running `state.apply` multiple times result in duplicate rules.

### Setup
```
# dummy.sls
simple nftables rule:
    nftables.append:
        - table: filter
        - chain: output
        - proto: udp
        - dport: 53
        - jump: accept
```

### Steps to Reproduce Issue

1. apply above state a couple of times (make sure `nft` is installed)
2. run `nft list ruleset`

### Versions Report

`Salt: 2018.03.03`

**Comment by Ch3LL** [comment]
it should be catching it here:

https://github.com/saltstack/salt/blob/v2018.3.3/salt/states/nftables.py#L245-L253


i'm assuming if you run that as an execution module its returning false?

or if you add this patch:

```
diff --git a/salt/states/nftables.py b/salt/states/nftables.py
index 4543ccf46b..a4748cc6e2 100644
--- a/salt/states/nftables.py
+++ b/salt/states/nftables.py
@@ -242,10 +242,12 @@ def append(name, family='ipv4', **kwargs):
     rule = __salt__['nftables.build_rule'](family=family, **kwargs)
     command = __salt__['nftables.build_rule'](full=True, family=family, command='add', **kwargs)
 
-    if __salt__['nftables.check'](kwargs['table'],
+    check = __salt__['nftables.check'](kwargs['table'],
                                   kwargs['chain'],
                                   rule,
-                                  family) is True:
+                                  family)
+    log.error(check)
+    if check is True:
         ret['result'] = True
         ret['comment'] = 'nftables rule for {0} already set ({1}) for {2}'.format(
             name,
```

it should log an error with the return of the check call.

**Comment by antifob** [comment]
I provided steps to reproduce this issue in #51641 

I'm not sure what info you need here. The above patch fails because there is no module named `log`.

**Comment by garethgreenaway** [comment]
I looked at this last night and see several issues with the state and module. Assigned it to myself and will be spending some time looking at it.

**Comment by aidecoe** [comment]
I have used example from documentation:

```
httpd:
  nftables.append:
    - table: filter
    - chain: input
    - family: inet
    - jump: accept
    - match: state
    - connstate: new
    - dport: 80
    - proto: tcp
    - sport: 1025:65535
    - save: True
```

I only added `family: inet`. The problem is still there in salt 3006.1. It keeps appending the rules despite they exist.
