### ISSUE TITLE
Saltclass globbing breaks class expansion

### ISSUE THREAD

**Issue by a-a-abramov** [saltstack/salt#51489]
### Description of Issue/Question
Saltclass globbing introduced with commit a3c0158188 breaks saltclass. To be specific this line of code inside a recursive function `expand_classes_in_order`:
`classes_to_expand = expand_classes_glob(classes_to_expand, salt_data)`
calls function, where classes_to_expand pointer seems to be overwritten, so we have this picture during debug: 

### Setup
**nodes/node.yml:**
```
classes:
  - test.0-level-class.yml
```

**classes/0-level-class.yml:**
```
classes:
  - test.1-level-class
```

**classes/1-level-class.yml:**
```
classes:
  - test.2-level-class
```

**classes/2-level-class.yml:**
```
classes:
  - test.3-level-class
```

**classes/3-level-class.yml:**
```
pillars:
```

### Steps to Reproduce Issue
Get pillars for a `node` described in saltclass with several (>1) levels of nested classes.
Expected behavior:
```
node:
    ----------
    __saltclass__:
        ----------
        classes:
            - test.3-level-class
            - test.2-level-class
            - test.1-level-class
            - test.0-level-class
```

Actual behavior:
```
node:
    ----------
    __saltclass__:
        ----------
        classes:
            - test.1-level-class
            - test.0-level-class
```

All classes below second level are lost due to the fact that `classes_to_expand` pointer is overwritten in the middle of recursion somewhere inside `expand_classes_glob`. If we log `classes_to_expand` at the beginning and right before the return of function `expand_classes_in_order` we would get this:
```
Start: []
Start: [u'test.1-level-class', u'test.0-level-class']
Start: [u'test.2-level-class', u'test.1-level-class', u'test.0-level-class']
Start: [u'test.3-level-class', u'test.2-level-class', u'test.1-level-class', u'test.0-level-class']
Start: [u'test.3-level-class', u'test.2-level-class', u'test.1-level-class', u'test.0-level-class']
Return: [u'test.3-level-class', u'test.2-level-class', u'test.1-level-class', u'test.0-level-class']
Return: [u'test.3-level-class', u'test.2-level-class', u'test.1-level-class', u'test.0-level-class']
Return: [u'test.3-level-class', u'test.2-level-class', u'test.1-level-class', u'test.0-level-class']
Return: [u'test.2-level-class', u'test.1-level-class', u'test.0-level-class']
Return: [u'test.1-level-class', u'test.0-level-class']
```
In the end we get only classes from node definition and from the first level of `expand_classes_in_order`.
### Versions Report
Master is deployed right from develop branch.
**Master report**
Salt Version:
           Salt: 2019.2.0 
 
Dependency Versions:
           cffi: 1.11.4
       cherrypy: Not Installed
       dateutil: 2.7.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.24.0
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Oct  4 2018, 15:13:23)
   python-gnupg: 0.4.3
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.2
 
System Versions:
           dist: gentoo 2.4.1 
         locale: UTF-8
        machine: x86_64
        release: 4.14.65-gentoo-xen-guest-cgroups
         system: Linux
        version: Gentoo Base System 2.4.1 
 
**Minion report:**
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.4
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.24.0
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Oct  4 2018, 15:13:23)
   python-gnupg: 0.4.3
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: gentoo 2.4.1 
         locale: UTF-8
        machine: x86_64
        release: 4.14.65-gentoo-xen-guest-cgroups
         system: Linux
        version: Gentoo Base System 2.4.1

**Comment by rbthomp** [comment]
@Ch3LL the commit in question was introduced by @awerner. I haven't see any activity from @olivier-mauras on resolving issues for saltclass since Jun 2018. These pull requests by @a-a-abramov  are worth reviewing #51487 #51488.
