### ISSUE TITLE
Community feedback for Py2 deprecation in SaltStack

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#51508]
### Description of Issue/Question
Below is the RFC detailing the 'End of Python 2 support in SaltStack'
https://github.com/saltstack/salt/blob/develop/rfcs/0006-py2-deprecation.md

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
will be re-opening the RFC in a new RFC repo so we can keep the conversation there. Closing here for now.
