### ISSUE TITLE
salt minion not sending start event

### ISSUE THREAD

**Issue by jvrahav** [saltstack/salt#51514]
### Description of Issue/Question
i have an automated script that deploys the minions on endpoints and brings them up. I have a reactor/orchestrator set to act when a minion start even occurs. I recently upgraded to 2018.3.2. After upgrade i see minion failing to send the start event to the master. This seems to happen randomly.
On the master i'm hooked into the salt event bus, here i dont see any start event from the minion when the issue occurs. Can some one point to possible cause for this issue or to pointers that would help me debug the issue.

A restart of the minion on the endpoint seems to fix this issue. however i would like to avoid this.

### Setup
minion running on centos 7 as a virtualenv.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Aug 10 2017, 23:51:58)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by Ch3LL** [comment]
Can you include a sanitized version of your master logs. Do you see hte start event in the log like below?

```
2019-02-06 10:27:25,323 [salt.utils.event                               :739 ][DEBUG   ][10983] Sending event: tag = salt/minion/the_cake_is_a_lie/start; data = {'id': 'the_cake_is_a_lie', 'cmd': '_minion_event', 'pretag': None, 'data': 'Minion the_cake_is_a_lie started at Wed Feb  6 10:27:25 2019', 'tag': 'salt/minion/the_cake_is_a_lie/start', '_stamp': '2019-02-06T15:27:25.323297'}
```

**Comment by jvrahav** [comment]
in enabling debug logs on the master, i got to know that start event was indeed being sent by the minion to the master. Although the master when it executes the reactor state, the state run was failing some permission errors and file not found errors. 
Dug a bit more to realize something was going wrong with reactor execution. Found the issue https://vrbc-gerrit.eng.vmware.com/#/c/17523/ filed for the same reason. As upgrading salt master to latest version is not an option for me, i implemented the workaround mentioned in the bug that helped me.
