### ISSUE TITLE
host.absent creates nullbyte characters

### ISSUE THREAD

**Issue by stratusjerry** [saltstack/salt#51524]
### Description of Issue/Question
host.absent creates nullbyte characters which break any subsequent attempt to match host entries

### Setup
With vi/vim, create a hosts file with 3 entries:
`127.0.0.1       localhost test1 test2`

Create a state to remove hostnames and apply it to the minion
`remove_hosts_entries:
  host.absent:
    - ip: 127.0.0.1
    - names:
      - test1
      - test2`

### Steps to Reproduce Issue
The first name match will be detected and removed, but nullbyte characters (^@^@^) will be added to the matching hosts line and the line below it.  The second name will not be detected due to the nullbytes and not removed.
Resulting hosts file:
`1^@^@^@2^@^@^@7^@^@^@.^@^@^@0^@^@^@.^@^@^@0^@^@^@.^@^@^@1^@^@^@ ^@^@^@  ^@^@^@ ^@^@^@l^@^@^@o^@^@^@c^@^@^@a^@^@^@l^@^@^@h^@^@^@o^@^@^@s^@^@^@t^@^@^@ ^@^@^@t^@^@^@e^@^@^@s^@^@^@t^@^@^@2^@^@^@
^@^@^@`

### Versions Report
Master and minion running 2018.3.3

Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: 1.7.0
       cherrypy: 3.5.0
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.7
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.1
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.13
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-112-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by dwoz** [comment]
@stratusjerry I've confirmed this is an issue in 2018.3.3. I also tested it on the latest 208.3.4 branch and it has been fixed there.

**Comment by stratusjerry** [comment]
@dwoz thanks, looks like it was fixed in
#49394
