### ISSUE TITLE
salt.utils.etcd_util emits an EtcdNotFile error (emits not a file to logs) when creating a directory (because it's not a file)

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#51537]
### Description of Issue/Question
`salt.utils.etcd_util` doesn't properly distinguish between creating directories and files. When creating a directory with `etcd.directory` (or anything else), `salt.utils.etcd_util` stupidly outputs "$path not a file".

### Setup
Setup etcd somewhere.

### Steps to Reproduce Issue
Simply call etcd.directory on a directory that already exists.

### Versions Report
All of them, nobody seems to use `etcd`.

### Report
The issue is that all writes to etcd have been funnelled into a method off of the `salt.utils.etcd_util.EtcdClient` object. This method, .write(), takes a parameter `dir` to distinguish between whether to reset `value` to `None` or not and is later used to distinguish between the property types.

This is fine, but when an exception is raised, the method does not bother to distinguish between the types of exceptions and thus an exception used to distinguish when a key exists (which occurs when applying states) an error gets passed through.

**Comment by arizvisa** [comment]
(whenever that gets merged that is). Sorry, phrased that prior comment in the wrong tense.

**Comment by dwoz** [comment]
@arizvisa Thanks so much for reporting the issue and for the PR!

**Comment by arizvisa** [comment]
Closing this as it was fixed by PR #51538.
