### ISSUE TITLE
docker_container.running changes ownership of volume root even when test=True

### ISSUE THREAD

**Issue by jorsermar** [saltstack/salt#51540]
### Description of Issue/Question
When testing docker_container.running (so, when running it with test=True), it changes the ownership of the volume root. Reading issues like https://github.com/saltstack/salt/issues/50155 it makes me thing the test flag might be ignored there.

Also, I'm not sure why the :ro directive in binds parameter is changing the volume root instead of simply updating the permissions on the folder inside the container.

### Setup
run_wp_web:
  docker_container.running:
    - name: wp-web
    - image: wp-web:latest
    - restart_policy: always
    - links:
      - wp-php:php
    - binds:
      - wp-uploads:/var/www/html/docroot/wp-content/uploads:ro

### Test

sudo salt 'host01' state.sls_id 'run_wp_web' host01.wac test=True

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
       cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
       docker-py: Not Installed
       gitdb: 0.6.4
       gitpython: 1.0.1
       ioflo: Not Installed
       Jinja2: 2.7.2
       libgit2: 0.24.6
       libnacl: Not Installed
       M2Crypto: Not Installed
       Mako: Not Installed
       msgpack-pure: Not Installed
       msgpack-python: 0.5.1
       mysql-python: Not Installed
       pycparser: 2.14
       pycrypto: 2.6.1
       pycryptodome: Not Installed
       pygit2: 0.24.2
       Python: 2.7.5 (default, Apr 11 2018, 07:36:10)
       python-gnupg: Not Installed
       PyYAML: 3.11
       PyZMQ: 15.3.0
       RAET: Not Installed
       smmap: 0.9.0
       timelib: Not Installed
       Tornado: 4.2.1
        ZMQ: 4.1.4
System Versions:
         dist: centos 7.5.1804 Core
         locale: UTF-8
         machine: x86_64
         release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
         version: CentOS Linux 7.5.1804 Core

**Comment by dwoz** [comment]
@jorsermar Thanks for reporting this. Do you feel comfortable with making a PR to resolve the issue?

**Comment by jorsermar** [comment]
Sorry but i'm not familiar enough with salt or even python to do that

**Comment by BenKennish** [comment]
Can anyone else reproduce this issue?
