### ISSUE TITLE
test_argspec_report fails

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#51555]
### Description of Issue/Question

The test_argspec_report test fails on Debian testing/unstable:

```
======================================================================
FAIL: test_argspec_report (unit.utils.test_args.ArgsTestCase)
[CPU:100.0%|MEM:21.2%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/autopkgtest-lxc.f3h876pv/downtmp/autopkgtest_tmp/tests/unit/utils/test_args.py", line 134, in test_argspec_report
    {'kwargs': True, 'args': None, 'defaults': None, 'varargs': True}})
AssertionError: {'tes[18 chars]': {'args': ['arg1', 'arg2', 'kwarg1'], 'defau[43 chars]one}} != {'tes[18 chars]': {'kwargs': True, 'args': None, 'defaults': [18 chars]rue}}
- {'test_module.test_spec': {'args': ['arg1', 'arg2', 'kwarg1'],
+ {'test_module.test_spec': {'args': None,
-                            'defaults': (None,),
?                                        -     --

+                            'defaults': None,
-                            'kwargs': None,
?                                      ^^^

+                            'kwargs': True,
?                                      ^^^

-                            'varargs': None}}
?                                       ^^^

+                            'varargs': True}}
?                                       ^^^
```

salt 2018.3.3 and the 2018.3 salt branch are affected. Full test log: https://ci.debian.net/data/packages/testing/amd64/s/salt/1867772.log

The `test_argspec_report` code:
```python
def _test_spec(arg1, arg2, kwarg1=None):
    pass

sys_mock = create_autospec(_test_spec)
test_functions = {'test_module.test_spec': sys_mock}
ret = salt.utils.args.argspec_report(test_functions, 'test_module.test_spec')
self.assertDictEqual(ret, {'test_module.test_spec':
                               {'kwargs': True, 'args': None, 'defaults': None, 'varargs': True}})
```

Reading this test code, the actual result looks more like what I would expect from `argspec_report`:
```python
{
  'args': ['arg1', 'arg2', 'kwarg1'],
  'defaults': (None,),
  'kwargs': None,
  'varargs': None
}
```

**Comment by garethgreenaway** [comment]
@bdrung Thanks for the report.  We are not seeing this particular test fail in our testing suite using either Python 2 or 3, in either Debian or Ubuntu instances.  Can you provide some additional information about the environment where tests are running?  Thanks!

**Comment by bdrung** [comment]
Here is the setup of the test environment: https://ci.debian.net/data/packages/testing/amd64/s/salt/1867772.log
Test log: https://ci.debian.net/data/autopkgtest/testing/amd64/s/salt/1874812/log.gz

Why does the test case expect `args` to be `None` despite `_test_spec` having arguments? Why does this test case uses `create_autospec`? What's the purpose of this test?

**Comment by waynew** [comment]
@garethgreenaway we are now :trollface: 

2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-42-py3/11/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-m2crypto/10/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1804-py3/11/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report)
---

{'tes[18 chars]': {'args': ['arg1', 'arg2', 'kwarg1'], 'defau[43 chars]one}} != {'tes[18 chars]': {'kwargs': True, 'args': None, 'defaults': [18 chars]rue}} - {'test_module.test_spec': {'args': ['arg1', 'arg2', 'kwarg1'], + {'test_module.test_spec': {'args': None, -                            'defaults': (None,), ?                                        -     --  +                            'defaults': None, -                            'kwargs': None, ?                                      ^^^  +                            'kwargs': True, ?                                      ^^^  -                            'varargs': None}} ?                                       ^^^  +                            'varargs': True}} ?                                       ^^^ 

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_args.py", line 133, in test_argspec_report
    {'kwargs': True, 'args': None, 'defaults': None, 'varargs': True}})
AssertionError: {'tes[18 chars]': {'args': ['arg1', 'arg2', 'kwarg1'], 'defau[43 chars]one}} != {'tes[18 chars]': {'kwargs': True, 'args': None, 'defaults': [18 chars]rue}}
- {'test_module.test_spec': {'args': ['arg1', 'arg2', 'kwarg1'],
+ {'test_module.test_spec': {'args': None,
-                            'defaults': (None,),
?                                        -     --

+                            'defaults': None,
-                            'kwargs': None,
?                                      ^^^

+                            'kwargs': True,
?                                      ^^^

-                            'varargs': None}}
?                                       ^^^

+                            'varargs': True}}
?                                       ^^^

		
```

**Comment by garethgreenaway** [comment]
Fixed with https://github.com/saltstack/salt/pull/52852
