### ISSUE TITLE
RFC: Implement a MWorker cache

### ISSUE THREAD

**Issue by johnskopis** [saltstack/salt#51573]
Before I start building something I wanted to see if there's already something available/planned that does what I want.

I would like to implement a cache to be used inside external on-demand pillars. I want to use salt.cache API but there is no way to use the same in-memory cache instance. This probably works fine if you are using an external cache but in-memory cache does not work.

The proposed feature is adding an option worker_cache allowing users to specify which cache driver to use for this purpose. This cache instance would live on the MWorker/AESFuncs and would be passed into the get_pillar and ultimately passed into the ext_pillar.

Additionally, I would like to implement an If-Modified-Since Cache (IMSCache). The existing cache API requires the caller to know the expiry when this policy might be dictated using cache-control headers. An IMSCache would work similarly to a Cache but embed the expiry inside the cached object. The user-supplied `fun` argument would accept updated,tag arguments and perform conditional validation when the object is expired.

Finally, I would like to implement a TieredCache driver to allow stacking cache drivers. The first level is always an IMSCache (or Cache) using the MemCache driver and the second level is an IMSCache (or Cache) using the e.g. redis driver. I haven't thought about this much but the idea is to prevent many minion workers from overwhelming the backend resource on cache expiry. On a refresh the TierCache would "lock" the key and subsequent requests would either block until lock expired or serve stale data until lock expired or key is refreshed.

At some point the Cache could be deprecated as IMSCache should work mostly the same. The user-supplied `fun` would need to be updated to return the expiry, but could ignore the updated,tag if they do not wish to conditionally validate.

Please let me know what you think. I can always implement this outside of salt but it seems like it might be generally useful.

**Comment by damon-atkins** [comment]
See also #45314

**Comment by mattp-** [comment]
I know its a bit confusing, but have you taken a look at salt.utils.cache? It's what is used with the current pillar_cache implementation, and is separate from the salt.cache functionality for job returns etc. How would this differ from that? Is it specifically for caching ext pillar?

**Comment by johnskopis** [comment]
I have looked at salt.utils.cache but will admit I didn't try. Seems that because the salt.utils.cache is not a Singleton, and the factoried cache is not accessible inside the ext_pillar context, there is no way to do use a cache within ext_pillar. Passing a factoried cache into the ext_pillar is what I want because it gives the ext_pillar a finer grained control over what to cache/how.

We are not using PillarCache because simple TTL caching does not work in our environment. We also use a lot of external API to provide info about the environment the minon runs in. These API might be semi-expensive to call and return a lot of data, and are implemented as ext_pillar. The output is currently cached in minion data cache, which has some nasty effects anyway (deserialize minion from data cache takes ~4-7s/minion). This is related and I think switching to on-demand pillar would help here.

I think that ext_pillar should have access to a cache. I think the cache should be pluggable (though I would like to use a 1st level cache inside MWorker and shared external cache for all MWorker). The cache should be able to support IMS semantics.

While the intended use case is an ext_pillar cache I could see a worker_cache being generally useful to execution modules as well. This is different from context cache because all workers would use the same cache. Also, with IMS the cache would be invalidated.

A quick grep for cache found github module. Consider using an IMSCache instead:

```
__context__[foo] = load_slow_blocking_resource()
```

becomes
```
def conditional_fetch(last_cache=cache):
   ... do a conditional fetch using last_cached item to revalidate
   return load_slow_blocking_resource()
__context__[foo] = cache(__name__, foo, _conditional_fetch)
```

Each worker only needs to make that blocking request 1x -- regardless of how many subsequent context need access to slow_blocking_resource.

Using a shared_cache (tiered cache) -- upon closer inspection the MemCache kind of does this already would allow each master to only make the request 1x regardless of how many workers there are.

The thinking is the same for on-demand ext_pillar. hopefully it makes sense?

**Comment by mattp-** [comment]
@isbm do you have thoughts here?

**Comment by isbm** [comment]
@mattp- Well, first thoughts would be:

- Close this issue
- Rewrite RFC [according to the template](https://github.com/saltstack/salt/blob/develop/rfcs/0000-template.md)
- Open a PR for this
- Ping everyone in the community

:wink: 

I would like to see a better design here. Might be a good idea.

**Comment by mattp-** [comment]
thats a fair point. @johnskopis since this is a larger change that involves trying to bring some cohesion to the already fragmented cache interfaces in salt, do you think you could move this over to https://github.com/saltstack/salt-rfc ? You can be the first lucky author :) (the idea of a separate RFC repo was introduced a few days ago for salt)

**Comment by johnskopis** [comment]
I will try to finish up a good spec this weekend.

I didn't really want to do a major refractor here. any work I do should
make it easier to refactor if that's what you want to do. I want a pony but
I don't mind parking in the donkey stable (if the analogy makes sense). 😁

**Comment by johnskopis** [comment]
RFC is here: https://github.com/saltstack/salt-rfc/pull/3

**Comment by KChandrashekhar** [comment]
@Ch3LL Can we close this, now that we have a separate RFC for this being tracked ?

**Comment by Ch3LL** [comment]
sounds good.
