### ISSUE TITLE
dockercompose timeout value

### ISSUE THREAD

**Issue by sotona-** [saltstack/salt#51574]
### Description of Issue/Question
When I'm triyng to manage a lot of containers in one docker-compose file, time to time docker-compose exits with timeout error because docker starting/stopping/erasing containers longer than default 60s timeout. 
When I run docker-compose manually I'm able to set DOCKER_CLIENT_TIMEOUT and COMPOSE_HTTP_TIMEOUT variables to increase this timeout. 

Will this variables work with a salt's dockercompose module? For example like this:

`set_docker_timeout:
  environ.setenv:
    - name: DOCKER_CLIENT_TIMEOUT
    - value: 180
    - update_minion: True

set_compose_timeout:
  environ.setenv:
    - name: COMPOSE_HTTP_TIMEOUT
    - value: 180
    - update_minion: True

stop_containers:
  module.run:
    - name: dockercompose.stop
    - path: /opt/containers/application
` 
If not, I think that we need to add some timeout argument to dockercompose module.

### Setup
Minion with docker-compose

### Steps to Reproduce Issue
make a docker-compose file with lot of containers(~30 in my case) and try to start/stop/rm it via salt's dockercompose module

### Versions Report
salt 2018.3.3

**Comment by Ch3LL** [comment]
since those values are set in docker-compose via environment variables i would say yes that should work. If it does not we can dive into docker-compose's library to see if they allow setting this via code instead of a env variable.

**Comment by sotona-** [comment]
> since those values are set in docker-compose via environment variables i would say yes that should work. If it does not we can dive into docker-compose's library to see if they allow setting this via code instead of a env variable.

Thanks. If this workaround will not help, i'll write.
