### ISSUE TITLE
MasterPillarUtil __opts__ assignment seems to be poisoning salt-master options when used in ext_pillar module

### ISSUE THREAD

**Issue by kylehuff** [saltstack/salt#51578]
### Description of Issue/Question
Providing unique run-time options (opts) to `MasterPillarUtil` within an external pillar provider seems to be poisoning the configured options of the running salt-master process(es) after invoking `get_minion_pillar()`.  Is this intended/desired behavior?  It doesn't seem desirable that an external instantiation of MasterPillarUtil with custom options would alter the configuration of the running salt-master process(es).

### Setup
Can be demonstrated by instantiating MasterPillarUtil with a custom options dictionary that sets the `ext_pillar` config item to an empty list and then invoking `get_minion_pillar()`.  After doing so, subsequent requests for pillar data no longer invoke ext_pillar providers (this lasts until the salt-master process is restarted).  For expedience, the example master config below sets the WORKER_THREADS value to 1 to quickly illustrate this behavior (otherwise, the second iteration may be executed by a worker thread that has not yet been poisoned).

Master config:
 
    worker_threads: 1
 
    file_roots:
      base:
        - /srv/salt/states
 
    pillar_roots:
      base:
        - /srv/salt/pillar
 
    extension_modules: /srv/salt/modules
 
    ext_pillar:
      - cmd_json: 'echo {\"pillar_from_cmd_json\":\"a_json_value\"}'
      - my_pillar_module: noargs
 
Example ext_pillar provider `/srv/salt/modules/pillar/my_pillar_module.py`:
 
    #!/bin/env python
 
    import salt.utils.master
    import salt.pillar
 
    import logging
 
    log = logging.getLogger('my_pillar_module')
 
 
    def ext_pillar(minion_id, pillar, *args, **kwargs):
      # return pillar
      ret_pillar = {'dual-shared-value': 'no match'}
 
      neighbor = pillar.get('neighbor')
      log.info("ext_pillar 'my_pillar_module' checking relationship between {} and {}".format(minion_id, neighbor))
 
      # disable ext_pillars, we don't want a recursion problem
      master_options = {}
      master_options.update(__opts__)
      master_options['ext_pillar'] = []
 
      # setup pillar request
      pillar_util = salt.utils.master.MasterPillarUtil(
        neighbor,
        "glob",
        use_cached_grains=True,
        grains_fallback=False,
        use_cached_pillar=True,
        pillar_fallback=False,
        opts=master_options,
      )
     
      # get the other minion's pillar value for "neighbor"
      neighbor_value = pillar_util.get_minion_pillar().get(neighbor, {}).get('neighbor')
 
      # check if relationship is mutual
      if neighbor_value == minion_id:
        ret_pillar['dual-shared-value'] = '... something shared from somewhere else ...'
 
      return ret_pillar
 

### Steps to Reproduce Issue
1st execution:
 
    # salt 'some-minion' pillar.items
    some-minion:
        ----------
        dual-shared-value:
            no match
        neighbor:
            someotherid
        pillar_from_cmd_json:
            a_json_value
 
subsequent execution(s):
 
    # salt 'some-minion' pillar.items
    some-minion:
        ----------
        neighbor:
            someotherid

### Versions Report
NOTE: I discovered this in salt version 2017.7 (was not present in 2016.11, AFAICT), but this example was done using 2018.3 to show it is present in the current release.
 
    # salt --versions-report
    Salt Version:
               Salt: 2018.3.3
    
    Dependency Versions:
               cffi: 0.8.6
           cherrypy: Not Installed
           dateutil: 2.2
          docker-py: Not Installed
              gitdb: 0.5.4
          gitpython: 0.3.2 RC1
              ioflo: Not Installed
             Jinja2: 2.7.3
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: 1.0.0
       msgpack-pure: Not Installed
     msgpack-python: 0.4.2
       mysql-python: 1.2.3
          pycparser: 2.10
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.9 (default, Jun 29 2016, 13:08:31)
       python-gnupg: Not Installed
             PyYAML: 3.11
              PyZMQ: 14.4.0
               RAET: Not Installed
              smmap: 0.8.2
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.0.5
 
    System Versions:
               dist: debian 8.11
             locale: UTF-8
            machine: x86_64
            release: 3.16.0-6-amd64
             system: Linux
            version: debian 8.11

**Comment by dwoz** [comment]
@saltstack/team-core Does anyone have some input on this?

**Comment by waynew** [comment]
I can take a look at this probably tomorrow

**Comment by waynew** [comment]
I'm not reproducing this on Ubuntu 18.04, at least running the master/minion under Docker. I'll try a couple of more things to see if I can reproduce.

**Comment by kylehuff** [comment]
@waynew I am able to reliably reproduce this issue on Ubuntu 18.04, salt version 2018.3.

I created a repository (https://github.com/kylehuff/saltstack-51578) that includes the external pillar provider, salt-master config and a Vagrantfile to reproduce the test on a few different target distro/releases.

I can reproduce the issue every time on debian/jessie, debian/stretch and ubuntu/bionic.

**Comment by waynew** [comment]
@kylehuff Excellent! I'll take a look at this tomorrow

**Comment by waynew** [comment]
Not sure *why* it's doing what it's doing, still looking into that... but meanwhile, you can avoid the problem by not poisoning the opts:

```
has_run = False

def __virtual__():
    global has_run
    if has_run:
        return False
    else:
        has_run = True
        return True
```

**Comment by waynew** [comment]
I've narrowed it down to when `compile_pillar()` is called - after it's called the first time, any subsequent calls no longer produce the expected result.

**Comment by waynew** [comment]
For the record, when you say **external** as in:

> It doesn't seem desirable that an external instantiation of MasterPillarUtil with custom options would alter the configuration of the running salt-master process(es).

it's not external in the way you might typically think - external modules are still imported and used within the master process(es).

All that being said, there is still somewhere that the opts is getting updated, which it probably shouldn't be doing. Still working on tracking that spot down.

**Comment by waynew** [comment]
Okay! So I tracked this down! It's down in the depths of `LazyLoader`.

There are a multitude of places where simply replacing `self.opts = opts` with `self.opts = dict(**opts)` totally fixes the problem. I think the lowest level point is here: https://github.com/saltstack/salt/blob/2019.2/salt/loader.py#L1604

If that becomes something like

```
setattr(mod, p_name, copy.deepcopy(p_value))
```

There are no longer problems with this code (though there are some other things that have to happen there). You can also just set `self.pack['__opts__'] == dict(**self.pack['__opts__'])` in the `__init__` method and that works.

I'm not entirely sure which place is the most correct location for that change, but almost any point in the call stack works.

**Comment by waynew** [comment]
Turns out there's a pretty simple fix for this, @kylehuff. Give that a shot and see if it solves your problem.

**Comment by kylehuff** [comment]
@waynew Yes, that seems to have done it. I can no longer reproduce this behavior with that change.

> it's not external in the way you might typically think - external modules are still imported and used within the master process(es).

I struggled with a meaningful way to articulate what I meant. Though external modules/providers are consumed within in the master process(es), I wouldn't expect a sub-process's alteration of the options to persist beyond the lifecycle of that sub-process without some explicit instruction to do so.

Thanks for looking at this.

**Comment by waynew** [comment]
To be honest, it's a little weird to me looking at the code, why it does what it does. There are some complex, if not downright complicated, interactions going on there. The weirdest thing to me is the fact that as soon as I swapped out that dictionary there was no longer a problem.

Hm. But I didn't check swapping out the dictionary for a wrapped up dictionary in the ext_module. That might be interesting, to see if it exhibits the same behavior as a natural dictionary.

**Comment by cachedout** [comment]
Has there been any discussion about whether or not to issue a security advisory about this? The ability to modify the configuration of a running master from an external service is a serious concern.

**Comment by waynew** [comment]
Wait, am I missing something here?

I'm not seeing the attack vector that would be a concern here. My understanding is that this code will only be accessed by the running master, and the only way to modify the behavior is to add files to a location that should only be writable (and maybe not even that??) by the master? Is that not correct?

**Comment by cachedout** [comment]
After reviewing the sample case provided, I think I misunderstood the nature of this initially. Based on the title, I thought this was being injected from the remote pillar source itself and not from the python which _describes_ the pillar. Given where this bug actually sits, I still think that this should be fixed but I don't think it is serious as I previously assumed. Apologies for the misunderstanding.

**Comment by waynew** [comment]
Okay, good, I feel way better about things now 😆 There are still a lot of internals in Salt that I haven't wrapped my head around so I was super worried that I was missing something huge.

> I still think that this should be fixed

Agreed - We've had several discussions about it internally, and it may be intense enough of a change that we should start a SEP on it, but basically the idea tossed around was to turn opts into a frozendict, to eliminate changes to it as a source of bugs. Which I personally think is a *great* idea, because you really shouldn't be implicitly futzing with options. I don't necessarily have something against updating them, but it should basically be reloading your process with the new options. I think 😛 

But that argument probably belongs on a SEP :trollface:
