### ISSUE TITLE
Running schedule.enable or schedule.disable breaks schedule.save

### ISSUE THREAD

**Issue by TheLocehiliosan** [saltstack/salt#51600]
### Description of Issue/Question

After running `schedule.enable` or `schedule.disable`, one can no longer run `schedule.save` successfully until salt-minion is restarted. The error reported:
```
TypeError: 'bool' object is not iterable
````
I think this is because a key value pair `enabled: True` is added to the schedule data structure, at the same level as the jobs, so it is attempted to be treated as a job to save, but can not be processed successfully. I came across this error while searching for a way to set the global scheduling "enabled/disabled" state within the minion configuration.

### Setup
None

### Steps to Reproduce Issue
1. Create any sort of schedule.
2. Run either `schedule.enable` or `schedule.disable`
3. Attempt to run `schedule.save` (this will result in error)

You can observe the added `enabled: <boolean>` by running `schedule.list show_all=True`. 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 4.9.93-linuxkit-aufs
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by garethgreenaway** [comment]
Closing this out as the fix is in the 2018.3 and later branches, and will be available in the next minor releases. If the problem persists, let us know and we can reopen this issue.
