### ISSUE TITLE
grains.os_string which is importable as SLS file

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#51619]
### Description of Issue/Question

Unfortunately `grains.osfinger` can contain a dot.

This means, this does not work:
```

 include:
  - .osfinger-{{ grains.osfinger }}
```

I like this pattern very much, so that I wrote a custom grain:
```

salt:/srv # cat salt/_grains/os_string.py
# -*- coding: utf-8 -*-
import re
import traceback


def _traceback_on_exception(func):
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as exc:
            return '{} {}'.format(str(exc), ''.join(traceback.format_exc(exc)))
    return wrapper

@_traceback_on_exception
def _get_data():
    data = dict()
    for line in open('/etc/os-release'):
        match = re.match(r'^\s*(\S+)\s*=\s*"?(.+?)"?\s*$', line)
        if not match:
            continue
        data[match.group(1)]=match.group(2)
    os_string = '{}-{}'.format(data['NAME'], data['VERSION_ID'])
    return os_string.replace(' ', '_').replace('.', '_')


def main():
    return dict(os_string=_get_data())

if __name__=='__main__':
    print(main())

```

This is a feature-request. It would be nice if salt would provide something like this by default.

This way I can use this:

```

 include:
  - .os-{{ grains.os_string }}
```

The files (`os-Ubuntu-18_04.sls`, `os-SLES-12_3.sls`, ....) I can decide what to do: use custom config, or include a general file.

This way I can avoid a lot of "ifing" and "elsing".

**Comment by Ch3LL** [comment]
im not clear what the feature request is exactly. Are you simply asking that `osfinger` does not return a `.`?

**Comment by guettli** [comment]
Changing the output from `grains.osfinger` from "Ubuntu-18.04" to "Ubuntu-18_04" to make it possible to import "Ubuntu-18_04.sls" is too much. This would break a lot of systems.

That's why I want to add a new grain.

Is it more clear now?

**Comment by max-arnold** [comment]
Have you considered using a Jinja filter? Something like this:

`{{ grains.osfinger | replace('.', '_')}}`

Also, quite soon you will be able to simplify your custom grain, see #47372

**Comment by guettli** [comment]
@max-arnold yes, I know the Jinja replace() filter. But since I will use the grain very often, I would like to avoid this extra typing each time I use `grains.osfinger` without a dot.
