### ISSUE TITLE
NameError: global name '__opts__' is not defined

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#51618]
### Description of Issue/Question

I try to call `salt.grains.core.os_data()` in my custom grain, but this fails.

### Setup
```
salt:/srv # cat salt/_grains/os_string.py
# -*- coding: utf-8 -*-
# https://github.com/saltstack/salt/issues/51618

import traceback
from salt.grains import core


def traceback_on_exception(func):
    def wrapper(*args, **kwargs):
        try:
            return func(*args, **kwargs)
        except Exception as exc:
            return '{} {}'.format(str(exc), ''.join(traceback.format_exc(exc)))
    return wrapper

@traceback_on_exception
def get_data():
    return core.os_data()['osfinger'].replace('.', '_')

def main():
    return dict(os_string=get_data())

if __name__=='__main__':
    print(main())

```

### Steps to Reproduce Issue

```
salt:/srv # salt-ssh --verbose -W aptguettler grains.get os_string
```

Output:
```
    global name '__opts__' is not defined Traceback (most recent call last):
      File "/var/tmp/.07b1a5/running_data/var/cache/salt/minion/extmods/grains/os_string.py", line 11, in wrapper
        return func(*args, **kwargs)
      File "/var/tmp/.07b1a5/running_data/var/cache/salt/minion/extmods/grains/os_string.py", line 18, in get_data
        return core.os_data()['osfinger'].replace('.', '_')
      File "/var/tmp/.07b1a5/py2/salt/grains/core.py", line 1668, in os_data
        grains.update(_linux_gpu_data())
      File "/var/tmp/.07b1a5/py2/salt/grains/core.py", line 170, in _linux_gpu_data
        if __opts__.get('enable_lspci', True) is False:
    NameError: global name '__opts__' is not defined
```
### Versions Report

salt:/srv # salt --versions-report
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.22.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: SuSE 12.3 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.114-42.1-default
         system: Linux
        version: openSUSE  12.3 x86_64

**Comment by Ch3LL** [comment]
see issue here: https://github.com/saltstack/salt/issues/47338

if you see in that issue there is a proposed solution here: https://github.com/saltstack/salt/pull/47372 that will be added in the next fluorine release.

**Comment by guettli** [comment]
Thank you for your answer.
