### ISSUE TITLE
How to ignore unconnected minions in grain matching

### ISSUE THREAD

**Issue by mattdodge** [saltstack/salt#51615]
### Description of Issue/Question
I have a Salt Master that I'd like to "pre-load" some devices on by generating keys, accepting them, and then downloading the private keys to provision on to the devices at a later time.

The problem is, when I do this all of my "grain matching" gets way slower because Salt Master is trying to hit those minions, even though they aren't online yet. (sample reproduce below). Is there a way to target using a grain but assume the grain does not match if the node hasn't reported yet? Perhaps another form of the same question, is there a way that on a grain cache miss to *not* interrogate the minion for its grains?

### Example/Reproduce
```bash
$ salt-key -L
Accepted Keys:
online-node-1
online-node-2

# Notice that test.ping will only target the one node right now
# It knows that online-node-2 doesn't match this grain
$ salt -G 'grain:value' test.ping
online-node-1:
    True

# Pre-accept some keys for some new nodes that will connect later
$ salt-key --gen-keys=offline-node-1
$ salt-key --gen-keys=offline-node-2
$ mv *.pub /etc/salt/pki/master/minions/
$ salt-key -L
Accepted Keys:
online-node-1
online-node-2
offline-node-1
offline-node-2

# This next command takes some time, because it is trying to contact 
# minions that have never connected/reported
$ salt -G 'grain:value' test.ping
online-node-1:
    True
offline-node-1:
    Minion did not return. [No response]
offline-node-2:
    Minion did not return. [No response]
```

How can I skip the minions that have never connected to the salt master?

**Comment by Ch3LL** [comment]
One possible solution is to target multiple grains. The initial grain value you want to target `'grain:value'` and another grain value that is set after the node is connected and setup.

**Comment by mattdodge** [comment]
The problem (at least what I am observing, maybe not a "problem" per se) is that when the minion hasn't yet connected salt master tries to ask the node for it's grains, making the request take a long time and thus getting the "no response" statuses. So another grain that gets set when the minion is set up wouldn't change the fact that the salt master doesn't know about the minion yet - it would just be interrogating it for *that* grain value too. Unless I'm misunderstanding something (not an unlikely possibility ha).

**Comment by Ch3LL** [comment]
ahh your completely right that this would actually not work. i wonder if you could somehow mkae sure of presence events and the manage.alived runner.

ping @saltstack/team-core does anyone have any clever ideas here? or maybe i'm missing a more simple solution?

**Comment by hemantaltair** [comment]
Not stale. Even I am facing a similar issue when I try to use grains all others minion which doesn't match with grains give Minion did not return. [No response]
How do I avoid it?
