### ISSUE TITLE
Cannot load custom module in salt-master runner

### ISSUE THREAD

**Issue by Wilybald** [saltstack/salt#51611]
### Description of Issue/Question
Hello, I tried to create custom module. The module is store in /srv/salt/_modules/ name is test_mod.py. 
In the master config I set 
```
module_dirs:
    - /srv/salt/_modules
```
### Steps to Reproduce Issue

So my problem is that salt runner cannot import this module.
I got this exceptions:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1514, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/srv/salt/_runner/process_minion_data.py", line 2, in <module>
    import salt.modules.test_mod
```

But if I call module from minion so it works.
```
salt-call --local test_mod.hello
local:
    hello world
```

So could you tell me where have I a problem? Thanks 

### Versions Report
```Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.7 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.7``

**Comment by Ch3LL** [comment]
Can you clarify this statement for me "So my problem is that salt runner cannot import this module."? Are you trying to run the custom module like so `salt-run test_mod.hello` and its not working? Or you are trying to call the custom module from another custom runner you are using?

I believe you are trying to import it from a custom runner since your stack trace shows that, but i wanted to be clear.

If that is indeed what you are trying to accomplish you do not need to import it but just call it similar to: `__salt__['salt.cmd'](fun=fun, args=args, kwargs=kwargs)` as documented here: https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.salt.html

> Execution modules are also available to salt runners:

>__salt__['salt.cmd'](fun=fun, args=args, kwargs=kwargs)

**Comment by Wilybald** [comment]
I wrote custom runner for send email. The custom runnes was write in python so I want import my custom module to the my custom runner. Because is possible import salt modules and I don't understand why I cannot import my custom module. And Yes `run salt-run test_mod.hello` is not working.

**Comment by Wilybald** [comment]
So?

**Comment by Ch3LL** [comment]
okay i did a little more digging. `__salt__` in the runner modules will call other runner modules not execution modules. you will want to follow along with this example:

https://github.com/saltstack/salt/issues/23480#issuecomment-221347420

to make sure its loaded up properly when you import the execution module.
