### ISSUE TITLE
return code breaks expected behaviour for pkg.info_installed

### ISSUE THREAD

**Issue by brejoc** [saltstack/salt#51620]
### Description of Issue/Question

There have been changes in the way the `retcode` is handled when doing a `pkg.info_installed`. With `2018.3.0` (the latest version we use in SUSE) there was no `retcode` when `pkg.info_installed` was invoked. This has changed for `2019.2.0 RC2`. Now a `retcode` is returned and if a pkg is not installed, it is `1`, which produces a `CommandExecutionError`.

Of course the `retcode` is coming from `rpm -q <pkgname>`, which returns `0` if the pkg is installed and `1` if the pkg is not installed. I can see why this has been changed, but this breaks expected behaviour when used in SLS files. My question is: Was this intended?

Related commits:
This introduced `retcode`: https://github.com/saltstack/salt/commit/e995cba7323b6439693fc2d364464bab999fe3e2
And some refactoring: https://github.com/saltstack/salt/commit/4c233442a23211ef310a6ce394746a4c9e0c1b49

### Steps to Reproduce Issue

2018.3.0:
```
bash-4.4# salt -L "C, E"  pkg.info_installed ceph-common
A:
    ERROR: package ceph-common is not installed
```

2019.2.0 RC2:
```
bash-4.4# salt \* pkg.info_installed ceph-common
A:
    ERROR: package ceph-common is not installed
ERROR: Minions returned with non-zero exit code
```
In the second case (2019.2.0 RC2) the job execution is marked as failed.

### Versions Report

This is for Salt 2019.2.0 RC2.

**Comment by isbm** [comment]
Well, the package was not installed, therefore `salt.defaults.exitcodes.EX_GENERIC`. So I am not really sure how this is an _issue_.

**Comment by brejoc** [comment]
@isbm I understand that the new behaviour is better, but this breaks the expected behaviour when coming from an older Salt version and will cause headache for a lot of customers.

**Comment by terminalmage** [comment]
The retcode handling is expected behavior and is not going to be changed.

What seems wrong to me is that a function that is meant to return info about an installed package raises an exception instead of simply returning an empty dictionary.

**Comment by terminalmage** [comment]
It seems to me the correct fix is not to make `lowpkg.info` raise an exception.

**Comment by terminalmage** [comment]
Or, like @isbm suggested to me just now, catch it in `pkg.info_installed`.

**Comment by dincamihai** [comment]
the problem would be when `rpm` would be called with an invalid option. For example: `rpm -t abc` the retcode would also be 1

**Comment by isbm** [comment]
The `lowpkg.info` is actually raising it because of non-zero retcode, so I believe it is correct. The forming final result is the job of virtual `pkg.info_installed`, so I think this should be captured there.

However, the retcode, I still think is actually correct behaviour and all these kind of exceptions should be treated as non-zero retcodes at the end.

**Comment by terminalmage** [comment]
> the problem would be when `rpm` would be called with an invalid option. For example: `rpm -t abc` the retcode would also be 1

Then.... don't use invalid options? I don't understand why this is Salt's problem.

**Comment by thatch45** [comment]
Yes, the retcode is not an issue, it is that an exception is being raised. @terminalmage is right as usual

**Comment by dincamihai** [comment]
@terminalmage my point is how to make the difference between valid retcode 1 (wrong option) and package not installed 1

**Comment by terminalmage** [comment]
If you want to set a different exit code, you can set `__context__['retcode'] = 2`, and use `salt-call --retcode-passthrough` on the minion.

https://docs.saltstack.com/en/develop/topics/return_codes/index.html

**Comment by terminalmage** [comment]
So, catch the exception, interpret it, and set `__context__['retcode']` appropriately. If you want to include the information from the failed command, `CommandExecutionError` accepts an `info` param that gets assigned as the exception's `info` attribute. So, when raising the exception, just use `info=call` or something, and catch it in `pkg.info_installed`.
