### ISSUE TITLE
lgpo does not properly set "boolean" admx element types

### ISSUE THREAD

**Issue by lomeroe** [saltstack/salt#51634]
### Description of Issue/Question
The lgpo module does not properly generate the data for a True "boolean" admx element type.  Boolean elements are typically represented as check boxes in an Administrative Template item in the gpedit.msc GUI.

### Setup
For example, elements 'Install during automatic maintenance' and 'Install updates for other Microsoft products' of the 'Configure Automatic Updates' policy on a 2016 server are boolean elements.  Lgpo properly sets these on "False" (unchecked) but not on "True" (checked).

For example:
```
configure_wsus:
  lgpo.set:
    - computer_policy:
        'Configure Automatic Updates':
            'Configure automatic updating': ' 4 - Auto download and schedule the install'
            'Install during automatic maintenance': False
            'Schedule install day': '7 - Every Saturday'
            'Schedule install time': '17:00'
            'Install updates for other Microsoft products': True
```

### Steps to Reproduce Issue
Run the above state and `gpupdate`, the 'AllowMUUpdateService' registry value will have an invalid value.

### Versions Report
Issue exists in 2017.7 and above

**Comment by twangboy** [comment]
Closed by 51635
