### ISSUE TITLE
cmd.script failing when /tmp is mounted noexec

### ISSUE THREAD

**Issue by antifob** [saltstack/salt#51642]
### Description of Issue/Question

The `cmd.script` function fails if `/tmp` is mounted `noexec`. This behavior is despite passing an explicit `shell` interpreter.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

`2018.3.3`

Linking with #46773 in the process.

**Comment by garethgreenaway** [comment]
@antifob Thanks for the report.  Are you using cmd.script to run a script that is in /tmp?

**Comment by antifob** [comment]
The script's source is under `salt://`. It is automatically copied under `/tmp` by `cmd.script`.

**Comment by csanders-git** [comment]
This is compounded by Salt Enterprise's CIS controls setting the noexec option on /tmp as part of CIS control enforcement

The following options are specified: {%- set mount_options = 'rw,nosuid,nodev,noexec,relatime' %}
