### ISSUE TITLE
salt-cloud w/shade is broken by default on bootstrapped Bionic.

### ISSUE THREAD

**Issue by andrew-vant** [saltstack/salt#51657]
### Description of Issue/Question

After running salt-bootstrap on a stock Bionic installation, salt-cloud is broken, apparently due to an unlisted Shade dependency. Attempting to create new instances fails with the error message: `There was a profile error: get_server() got an unexpected keyword argument 'bare'`. Other commands fail with other errors; the underlying pattern is "various issues with passing arguments or accessing attributes that don't exist".

### Setup

```
# cloud.providers.d/stuff.conf
providername:
  driver: openstack
  profile: racksapce
  region_name: IAD
  auth:
    username: username
    project_id: ######
    password: notarealpassword

# cloud.profiles.d/stuff.conf
profile1:
  provider: providername
  image: <long ID here>
  size: general1-2
  ssh_key_file: /root/.ssh/id_rsa
  ssh_key_name: saltmaster
```

### Steps to Reproduce Issue

1. Run salt-bootstrap on Ubuntu Bionic; install salt-cloud and python-shade with -L or -p.
2. Provide config files as above.
3. `salt-cloud -p profile1 servername`

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

NOTE: Shade is not included in the version report; it is v1.7.0-2.

### Thoughts

Things appear to work if I install Shade from pip instead of APT, and the [shade documentation says that this argument does exist](https://docs.openstack.org/shade/latest/user/usage.html#shade.OpenStackCloud.get_server). I think the version of salt-cloud installed on Bionic by salt-bootstrap depends on a more recent version of Shade than is available through the stock Bionic repo.

That might be okay if there were a useful error message, but there isn't, and part of the reason for that is that no shade dependency is listed in the package. So instead of getting an error on installation "hey, you've asked for a package with a dependency APT can't satisfy", it cheerfully installs an unusable version.

I'm not sure what the correct fix is. Presumably Shade isn't listed as a dependency in the salt-cloud package because salt-cloud is supposed to be pluggable (?). OTOH, I don't think it's unreasonable to expect the bootstrap script, when run on a supported platform, not to create a setup that is broken by default.

Possible solutions:

1. Provide a package for the required version of shade (and similar optional dependencies?) in the same repo as the salt packages.

2. List dependency versions in the package where apt can see them, so that it can complain. If necessary provide something like a `salt-cloud-plugin-shade` dummy package (depending on `salt-cloud` and `python-shade>=whatever` to do this. List these as Suggests: in `salt-cloud`.

3. If packages in the salt repo have optional dependencies that cannot be satisfied from either the saltstack repo or the official one, have salt-bootstrap complain, and maybe suggest installing them from pip.

4. Make salt-cloud aware of its own optional dependencies, and print a useful error message if something is wrong.

**Comment by garethgreenaway** [comment]
@dmurphy18 @saltstack/team-cloud FYI.

**Comment by gtmanfred** [comment]
The correct solution would be to figure out what is the oldest version of shade that works, and just add that as a requirement on the module.

I don't think salt should need to provide a package for this, it would be up to the user to make sure their version is new enough to work for the distro, otherwise pip install it.

**Comment by waynew** [comment]
> I don't think salt should need to provide a package for this

Agreed - though we *should* have some kind of minimum version specifier - though if it's a dependency of a dependency (or more 🐢 🐢 🐢) I'm not entirely certain what the right approach is - file a bug report with a dependency that they pin their dependencies (or at least specify minimum versions)?

**Comment by andrew-vant** [comment]
I scripted a test against each shade minor version in turn, as below. It pip-installs each version of Shade starting from 1.30 and descending, checks if a server build succeeds using that version, and stops bothering after five failures:

```sh
cloudtest ()
{
        profile=$1
        logfile=$2
        export PYTHONIOENCODING=UTF-8
        i=30
        failures=0
        for i in {30..7}
        do
                pip install -q "shade>=1.$i,<1.$(expr $i + 1)" &>> $logfile
                echo -n $(pip freeze 2>/dev/null | grep shade | tr -d '\n') $'\t'
                salt-cloud -l debug -p $profile salt-cloud-test-1.$i &>> $logfile
                result=$?

                if [ $result -eq 0 ]
                then
                        echo "OK"
                else
                        echo "FAILED"
                        let failures++
                fi
                if  [ $failures -gt 4 ]
                then
                        break
                fi
        done
}
```

I got the following output:

```
shade==1.30.0   OK
shade==1.29.0   FAILED
shade==1.28.0   OK
shade==1.27.2   OK
shade==1.26.0   OK
shade==1.25.0   OK
shade==1.24.0   OK
shade==1.23.0   OK
shade==1.22.2   OK
shade==1.21.0   OK
shade==1.20.0   OK
shade==1.19.0   OK
shade==1.18.1   FAILED
shade==1.17.0   FAILED
shade==1.16.0   FAILED
shade==1.15.0   FAILED
```

I'm not sure what made 1.29 fail, but it doesn't seem to be transient, at least not on my system. The specific error is `'dict' object has no attribute 'id'` on openstack.py line 463. Someone else should probably replicate. But going by the above, it looks like the dependency is shade >= 1.19, != 1.29.0.

**Comment by gtmanfred** [comment]
This should be handled like all other salt-cloud dependencies.

We just need to add a version check to the `get_dependencies` function.

I suggest that we do >= 1.19.0.

https://github.com/saltstack/salt/blob/2018.3/salt/cloud/clouds/openstack.py#L268-L279

**Comment by gtmanfred** [comment]
Based on the information provided, this should give more information about which versions of shade are supported by salt-cloud

https://github.com/saltstack/salt/pull/51689

**Comment by gtmanfred** [comment]
Also, when someone has time, this should really be migrated over to openstacksdk, now that that is officially supported (it was still in the works when i was writing this module, but it should be fairly easy to support both pypi modules now)

https://docs.openstack.org/openstacksdk/latest/user/

My understanding is it should be 95% a dropin replacement https://github.com/openstack/openstacksdk/blob/master/openstack/connection.py#L214

**Comment by gtmanfred** [comment]
Here is a work in progress pr for making that change https://github.com/saltstack/salt/pull/51690

I still need to test it. @andrew-vant if you wouldn't mind taking a look at it, that would be greatly appreciated, as it is going to take me a while to get an openstack cluster running again.

**Comment by gtmanfred** [comment]
If anyone @saltstack/team-cloud wants to test it, I use the google cloud, because it was easy to setup the next hop stuff for the ip routing of VMs inside the one box server.

this is what to run on an ubuntu 16.04 server https://github.com/gtmanfred/devstack-states/blob/master/openstack.sh to install openstack pike

And this for the salt-cloud/salt-master server

https://github.com/gtmanfred/devstack-states/blob/master/salt.sh

This line will need to be modified to install the correct stuff.

https://github.com/gtmanfred/devstack-states/blob/master/salt.sh#L12

**Comment by gtmanfred** [comment]
Moved the PR over to be a Draft PR now that that feature has been added to the salt repo.

https://github.com/saltstack/salt/pull/51729
