### ISSUE TITLE
Pillar render error: Failed to load ext_pillar csv - NoneType Found

### ISSUE THREAD

**Issue by HekMe** [saltstack/salt#51662]
Hello

### Description of Issue/Question
I'm having issue with csvpillar where it seems that there's some problem with fopen(path, 'rb'). The csv file is accessible, and with 777 permissions. 
When i try 'salt "*" pillar.items', the result is following:
_errors:
        - Failed to load ext_pillar csv: coercing to Unicode: need string or buffer, NoneType found

### Setup
Salt Master ext_pillar configuration(tried both options from docs):
https://hastebin.com/enakowaxic.makefile

CSV(I've tried many similar versions of this file with different delimiters, with or without dictionary keys, also i've tried the same thing as in docs but nothing was working):
https://hastebin.com/ijujizegob.csv

Salt Master Log:
https://hastebin.com/odagefixel.md

### Versions Report
https://hastebin.com/titixesiza.css

Thanks

**Comment by dwoz** [comment]
@HekMe Can you provide us the output of `salt -V`?

**Comment by HekMe** [comment]
`Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-17134-Microsoft
         system: Linux
        version: Ubuntu 16.04 xenial`

**Comment by HekMe** [comment]
@dwoz 
Do you need some other information?
