### ISSUE TITLE
Salt fileserver backend not updating consistently 

### ISSUE THREAD

**Issue by tcharette** [saltstack/salt#51665]
### Description of Issue/Question
Lately, we've had to manually run salt-run fileserver.update backend=git for our salt master to push changes that are stored on our git fileserver. (online bitbucket in our case) We've been running this set up for over a year now without issue.

### Setup
salt master 2018.3.3
gitfs_remotes point to our bitbucket repos

### Steps to Reproduce Issue
Push code changes to git, wait a few minutes, try to push from master. Sometimes it doesn't see the changes until a manual update is ran. 

### Versions Report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.7.0
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by tcharette** [comment]
Could it have to do with the polling? bitbucket throttling to every 5 minutes?

**Comment by garethgreenaway** [comment]
@tcharette Thanks for the report.  Bitbucket throttling could definitely be a factor here.  @saltstack/team-core Any thoughts?

**Comment by tcharette** [comment]
Seems to be a bitbucket throttling issue. Working around it by doing a manual fileserver.update on the master.

Cheers
