### ISSUE TITLE
Move command line arguments parsing to standalone library

### ISSUE THREAD

**Issue by rominf** [saltstack/salt#51682]
I'm working on an API for some product and I want to create a CLI (let's call it `app`). Suppose I have following code in my API library:
```python
class Camera:
    def create(name: str, url: URL, vendor: Optional[str] = None, record: bool = True):
        ...
```

I want that the user could invoke `Camera.create` using this:
```bash
$ app camera.create name='My camera' url=rtsp://camera/ record=False
```

As you see, it's very similar to `salt` invocation.

I've tried to find the library for this, but didn't find any. The easiest solution is to copy salt code.

So, I'm proposing to move command line arguments parsing to standalone library so that everyone could write apps like `salt`.

If you are not planning to do this yourself, will you use the library, created by me that uses salt codebase?

**Comment by garethgreenaway** [comment]
@rominf Thanks for the report.  The Python library you want to take a look at is `optparse`.

**Comment by rominf** [comment]
@garethgreenaway,
What have I found in the docs:
> Deprecated since version 3.2: The optparse module is deprecated and will not be developed further; development will continue with the argparse module.

Also, if I understand it correctly related code is in the `salt/utils/args.py` and it's more then 0.5 KLOC. It's too much to write it from scratch. In my opinion, it should be easy to create standalone library from it.
