### ISSUE TITLE
napalm_yang.managed does not work with Cisco IOS: "error 5"

### ISSUE THREAD

**Issue by misch42** [saltstack/salt#51686]
### Description of Issue/Question

when I try to set the description of an interface of a Cisco switch with napalm_yang.managed, I get the following error:

Configuration diff:
              
You have encountered the obscure 'error 5' message. This generally means you need to add an 'end' statement to the end of your merge changes.
              
Loaded config:
              
interface FastEthernet0/6
  description new description example
    exit

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
salt 2019.2.0rc2

state file:
```
{%- set expected_config =  pillar.get('openconfig_interfaces_cfg') -%}
{# {%- set expected_config =  salt['pillar.get']('netbox:openconfig') -%} #}
interfaces_config:
  napalm_yang.managed:
    - data: {{ expected_config | json }}
    - models:
      - models.openconfig_interfaces
    - debug: true
root@nms2:~# salt --version
salt 2019.2.0rc2 (Fluorine)
root@nms2:~# cat /srv/states/switch/interfaces.sls 
{%- set expected_config =  pillar.get('openconfig_interfaces_cfg') -%}
interfaces_config:
  napalm_yang.managed:
    - data: {{ expected_config | json }}
    - models:
      - models.openconfig_interfaces
    - debug: true

pillar:
openconfig_interfaces_cfg:
  interfaces:
    interface:
      FastEthernet0/6:
        config:
          description: "new description example"
          enabled: True
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
```
# salt switch02 state.apply switch.interfaces test=true
switch02:
----------
          ID: interfaces_config
    Function: napalm_yang.managed
      Result: None
     Comment: Configuration discarded.
              
              Configuration diff:
              
              You have encountered the obscure 'error 5' message. This generally means you need to add an 'end' statement to the end of your merge changes.
              
              Loaded config:
              
              interface FastEthernet0/6
                  description new description example
                  exit
     Started: 11:05:38.454741
    Duration: 27163.614 ms
     Changes:
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2019.2.0rc2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.27.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by garethgreenaway** [comment]
@mirceaulinic Any ideas on this one?
