### ISSUE TITLE
Documentation edit workflow?

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#51696]
### Description of Issue/Question
What is the exact workflow to get the documentation changes committed in git?
I am asking for a complete example of commands. I know conceptually how to use git/github and conceptually understand how Saltstack wants to receive PR's.

### Steps to Reproduce the problem

[SENDING A GITHUB PULL REQUEST](https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request)
1) Forked your salt repository
2) Cloned to my workstation
3) Added `saltstack/salt` upstream
4) Created a branch

[BUILDING THE DOCUMENTATION](https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#building-the-documentation)

5) Built the docs 
6) Made changes to the docs that are broken/wrong/useless/incorrect [Redacted words of frustration]

### The big problem
7) I attempt `git diff` & `git add *` commands. 
At this point nothing happens and I realize this work flow doesnt make any sense.
8) Checked the .gitignore file, and of course the `doc/_build` is ignored.
Following the logic it makes sense that I am not suppose to edit the docs that were created/compiled by `make,`so where am I actually suppose to do it?

NOTE: I am not trying to [ADD MODULE DOCUMENTATION TO THE INDEX](https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#adding-module-documentation-to-the-index), I am trying to modify your generalized salt docs that have nothing to do with a specific module or snippet of code.

**Comment by garethgreenaway** [comment]
@alan-cugler Thanks for the report.  The `doc/_build` directory is included in .gitignore because the documentation is built and the built documentation is not included is the repository.   All the documentation is built from the various `.rst` files found in this location, https://github.com/saltstack/salt/tree/develop/doc.  Was there a particular part of the documentation that you were attempting to fix?

**Comment by alan-cugler** [comment]
I have several doc changes to make around the documentation pages. I have not listed them out in issues, since that would be a lot issues to list out. There are already several that are listed under the documentation label. #51127 is the main issue that got me started on trying to submit doc changes.

**Comment by garethgreenaway** [comment]
@alan-cugler Perfect, that particular one can be found here: https://github.com/saltstack/salt/blob/develop/doc/topics/cloud/config.rst

A majority of them will likely live under the doc/topics folder under the main project.  I pasted the URL for the develop branch so please adjust the branch accordingly.  Please let me know if I can help with any other documentation locations.

**Comment by alan-cugler** [comment]
Thank you for the clarification!
