### ISSUE TITLE
Add vlan-aware option for bridge interfaces

### ISSUE THREAD

**Issue by konfiot** [saltstack/salt#51708]
Using salt 2018.3.3, and looking at the source code on master, it seems that there is no way to put arbitrary options with the network state, for example I would like to be able to specify the `bridge-vlan-aware` and `bridge-vids` options to put on the bridge interfaces of proxmox hosts, but I have not found any way to do that other than writing the interfaces files manually

**Comment by garethgreenaway** [comment]
@konfiot Thanks for the report.  Approving this for a future feature addition.
