### ISSUE TITLE
Salt-minion-proxy : Inconsistent behaviour with running same instance

### ISSUE THREAD

**Issue by vdani** [saltstack/salt#51731]
### Description of Issue/Question
Observing inconsistent behavior if we run the multiple instances of same proxy-minion. In some instances, it errors out suggesting there is already an instance running but in some case it does accept it and then whenever we run any command against that minion, we get replicated outputs (equal to number of instances running).

Case 1: Here when I try to run the same instance, it is getting rejected as shown below:
 
(salt_virtenv) [root@localhost salt_virtenv]# salt-proxy -c ./etc/salt --proxyid n3k-proxy-87-nxapi -l debug
[DEBUG   ] Reading configuration from /root/salt_virtenv/etc/salt/proxy
[DEBUG   ] Configuration file path: /root/salt_virtenv/etc/salt/proxy
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up "n3k-proxy-87-nxapi" the Salt ProxyMinion
[INFO    ] An instance is already running. Exiting the Salt ProxyMinion
[INFO    ] Shutting down the Salt ProxyMinion
The Salt ProxyMinion is shutdown.
 
 
Case 2: Multiple copies of same instance are accepted:
 
(salt_virtenv) [root@localhost salt_virtenv]# ps -ef | grep proxy
root       876     1  0 22:17 ?        00:00:05 /root/salt_virtenv/bin/python2 /root/salt_virtenv/bin/salt-proxy -c ./etc/salt --proxyid n3k-proxy-87-nxapi -d
root      1292     1  0 22:17 ?        00:00:06 /root/salt_virtenv/bin/python2 /root/salt_virtenv/bin/salt-proxy -c ./etc/salt --proxyid n3k-proxy-87-ssh -d
root      1808     1  0 22:18 ?        00:00:05 /root/salt_virtenv/bin/python2 /root/salt_virtenv/bin/salt-proxy -c ./etc/salt --proxyid n3k-proxy-87-nxapi -d
root      4439     1  0 22:38 ?        00:00:03 /root/salt_virtenv/bin/python2 /root/salt_virtenv/bin/salt-proxy -c ./etc/salt --proxyid n3k-proxy-88 -d
root      5431     1  0 22:44 ?        00:00:05 /root/salt_virtenv/bin/python2 /root/salt_virtenv/bin/salt-proxy -c ./etc/salt --proxyid n3k-proxy-88-ssh -d
root      6607     1  0 22:48 ?        00:00:03 /root/salt_virtenv/bin/python2 /root/salt_virtenv/bin/salt-proxy -c ./etc/salt --proxyid n3k-proxy-88 -d
root      7076     1  1 22:48 ?        00:00:04 /root/salt_virtenv/bin/python2 /root/salt_virtenv/bin/salt-proxy -c ./etc/salt --proxyid n3k-proxy-88-ssh -d
 
 

### Steps to Reproduce Issue
1. Configure and run salt-minion-proxy
2. Rerun the same salt-minion-proxy as a daemon (-d option) multiple times
3. It will get rejected few times and accepted few times as well depicting inconsistent behavior

### Versions Report
(salt_virtenv) [root@localhost salt_virtenv]# salt --versions-report
Salt Version:
           Salt: 2019.2.0rc1-3530-g86adb6b
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.2.5
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by Ch3LL** [comment]
looks like i'm able to replicate this. i'm also able to replicate this on 2018.3.3 as well so this is not a regression. we will need to get this fixed up thanks.

fyi @saltstack/team-network
