### ISSUE TITLE
encoding is deprecated

### ISSUE THREAD

**Issue by Ofloo** [saltstack/salt#51741]
### Description of Issue/Question

[WARNING ] /usr/local/lib/python2.7/site-packages/salt/payload.py:145: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
just run salt
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

# salt --versions-report
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15 (default, Feb  7 2019, 01:15:05)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: US-ASCII
        machine: amd64
        release: 12.0-RELEASE
         system: FreeBSD
        version: Not Installed

**Comment by Ofloo** [comment]
https://github.com/Ofloo/salt/commit/3e62ad17c1e8af8f03d72b65d3af647b2fb082e5#diff-30108e69fa3d1358454431c6c9b08965 Should fix it

**Comment by Ch3LL** [comment]
mind pushing that as a PR?

**Comment by Ofloo** [comment]
What do you mean,..?

**Comment by alxwr** [comment]
> mind pushing that as a PR?

@Ch3LL Here you go: #52480

**Comment by alxwr** [comment]
@Ofloo Thanks for the initial work!

**Comment by Ch3LL** [comment]
thanks for that. looks like this PR https://github.com/saltstack/salt/pull/52487 will be what will be merged to resolve this just for anyone that sees this issue. Thanks for the initial work though :)

**Comment by mkeen** [comment]
Is this fixed in a release?

**Comment by sagetherage** [comment]
@garethgreenaway @waynew can you see if this has a PR that was ported to master, please?

**Comment by Ch3LL** [comment]
i'm seeing the code https://github.com/saltstack/salt/blob/master/salt/payload.py#L109 in master adn 2019.2.3. @mkeen  are you still seeing it? and if so what version of salt?

**Comment by mkeen** [comment]
@Ch3LL I'm no longer seeing it in `2019.2.2`

**Comment by Ch3LL** [comment]
perfect i'll go ahead and close :) thanks for confirming

**Comment by grichmond-salt** [comment]
This issue appears to have resurfaced:
```
[root@ip-172-31-27-137 minion]# salt --versions
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Sep 26 2019, 11:57:09)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: rhel 7.5 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.5 Maipo
```

Example:
```
# salt \* test.ping
[WARNING ] /usr/lib/python3.6/site-packages/salt/utils/msgpack.py:152: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  return msgpack.unpackb(packed, **_sanitize_msgpack_unpack_kwargs(kwargs))

SaltDocs-RaaS-01:
    True
SaltDocs-PostgreSQL-01:
    True
SaltDocs-RaaS-02:
    True
SaltDocs-Redis-01:
    True
SaltDocs-Master-02:
    True
SaltDocs-Master-01:
    True
```

**Comment by sagetherage** [comment]
This has resurfaced, opening and putting through triage.

**Comment by cmcmarrow** [comment]
@grichmond-salt I got the same warning on 3001 but on master I no longer get this warning on master. 
I used msgpack==0.6.2.  
I looked around for any other encoding args/warnings that would bother you and did not see any. 
If you see anymore warnings pls reopen the PR and given the commanded you ran to give it. 
Here is the PR that fixed the problem https://github.com/saltstack/salt/pull/51262.
