### ISSUE TITLE
Adding python 3 http server command

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#51748]
## Question
I am about to make a PR for adding the python 3 command ```python3 -m http.server``` to the [BUILDING THE DOCS](https://docs.saltstack.com/en/2017.7/topics/development/conventions/documentation.html#building-the-documentation) BASH commands in step 4. My question is which ***style*** is more preferred?

### Exhibit A:
![screenshot001](https://user-images.githubusercontent.com/25991646/53191427-675b8980-35d1-11e9-9977-ba1fc55491df.png)
### Exhibit B:
![screenshot002](https://user-images.githubusercontent.com/25991646/53191455-76dad280-35d1-11e9-96ef-6e2ad5b25a46.png)
### Exhibit C:
![screenshot003](https://user-images.githubusercontent.com/25991646/53191462-7b9f8680-35d1-11e9-84f0-da2285f20cfe.png)

**Comment by garethgreenaway** [comment]
@alan-cugler Thanks for this report and the upcoming PR, my preference is `exhibit A`.  @saltstack/team-core Thoughts?

**Comment by thatch45** [comment]
I would say exhibit b, python3 should always get top billing

**Comment by garethgreenaway** [comment]
@thatch45 What about the layout, eg. different boxes, of Exhibit A but top billing of Python 3 as in Exhibit B?

**Comment by thatch45** [comment]
Yes, I will go with you there, Exhibit A with python3 top billing would be the best

**Comment by alan-cugler** [comment]
Alright, I'll put in a PR later.
