### ISSUE TITLE
vmware cloud module global name 'opts' has not defined

### ISSUE THREAD

**Issue by alexey-mz** [saltstack/salt#51743]
### Description of Issue/Question
How the module for vmware should work? Each command returns an error "global name '__opts__' is not defined". Is there a way to define it? What i'm doing wrong?
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
vmware.conf

vcenter:
  driver: vmware
  user: ''
  password: ''
  url: ''
  protocol: 'https'
  port: 443
  minion:
    master: salt

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
>>> import salt.cloud.clouds.vmware
>>> salt.cloud.clouds.vmware.test_vcenter_connection(call='function')
u"failed to connect: global name '__opts__' is not defined"

>>> salt.cloud.clouds.vmware.avail_locations()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 2069, in avail_locations
    return list_datacenters(call='function')
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 1566, in list_datacenters
    return {'Datacenters': salt.utils.vmware.list_datacenters(_get_si())}
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 244, in _get_si
    'url', get_configured_provider(), __opts__, search_global=False
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/vmware.py", line 191, in get_configured_provider
    __opts__,
NameError: global name '__opts__' is not defined

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jul 13 2018, 13:06:57)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.5.1804 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.5.1804 Core

pip show pyVmomi
---
Metadata-Version: 1.1
Name: pyvmomi
Version: 5.5.0.2014.1.1
Summary: VMware vSphere Python SDK
Home-page: https://github.com/vmware/pyvmomi
Author: VMware, Inc.

**Comment by Ch3LL** [comment]
if you are trying to run this from the python interpeter or script you will need to make sure you initialize opts.  You can follow the python client api docs here: https://docs.saltstack.com/en/latest/ref/clients/ to set all the options required to run this.

There is also the cloudclient: https://docs.saltstack.com/en/latest/ref/clients/#cloudclient which might be easiest to use.

**Comment by alexey-mz** [comment]
Could you provide a sample of code how to fetch __opts__ and then use it with vmware module?

**Comment by Ch3LL** [comment]
sure what are you trying to accomplish? I'm guessing using cloudclient will be the best for ya but want to make sure i know what you are trying to write up?
