### ISSUE TITLE
Reactor state not getting applied due to "No minions responded"

### ISSUE THREAD

**Issue by piersf** [saltstack/salt#51752]
Hello,

I'm trying to set up a reactor. I have the below state to be executed whenever a new minion connects to the master:

```
sync_all:
  salt.function:
    - name: saltutil.sync_all
    - tgt: data['id']
    - tgt_type: glob
    - reload_modules: True
```

The execution gets triggered successfully, but monitoring the events from the event-bus, i can see the below "error" is returned saying that no minion responded:

 ```
"salt_|-sync_all_|-saltutil.sync_all_|-function": {  
     "__id__": "sync_all",                            
     "__run_num__": 0,                                
     "__sls__": "reactors.startup",                   
     "changes": {},                                   
     "command": "No minions responded",               
     "comment": "",                                   
     "duration": 79.314,                              
     "name": "saltutil.sync_all",                     
     "result": false,                                 
     "start_time": "21:35:09.720611"                  
 },

```
To simulate a new minion joining, i'm just restarting an already connected minion which the master can talk to just fine and it can also do `state.highstate` without an issue(done manually).

The event is fired by the minion but I don't see any `data` dictionary in the event bus for `salt/minion/*/start` event. Below is what happens when I restart the minion(to simulate a new minion):

Output of `salt-run state.event pretty=True` :
```
salt/auth       {
    "_stamp": "2019-02-20T21:38:02.229705",
    "act": "accept",
    "id": "MINION_ID",
    "pub": "-----BEGIN PUBLIC KEY-----\nPUBLIC-KEY-HERE\n-----END PUBLIC KEY-----",
    "result": true
}
minion/refresh/MINION_ID      {
    "Minion data cache refresh": "MINION_ID",
    "_stamp": "2019-02-20T21:38:03.465887"
}
minion_start    {
    "_stamp": "2019-02-20T21:38:03.725725",
    "cmd": "_minion_event",
    "data": "Minion MINION_ID started at Wed Feb 20 21:38:03 2019",
    "id": "MINION_ID",
    "pretag": null,
    "tag": "minion_start"
}
salt/minion/MINION_ID/start   {
    "_stamp": "2019-02-20T21:38:03.731569",
    "cmd": "_minion_event",
    "data": "Minion MINION_ID started at Wed Feb 20 21:38:03 2019",
    "id": "MINION_ID",
    "pretag": null,
    "tag": "salt/minion/MINION_ID/start"
}
salt/run/20190220223804142830/new       {
    "_stamp": "2019-02-20T21:38:04.144838",
    "fun": "runner.state.orchestrate",
    "fun_args": [
        {
            "mods": "reactors.startup"
        }
    ],
    "jid": "20190220223804142830",
    "user": "Reactor"
salt/run/20190220223804142830/ret       {
    "_stamp": "2019-02-20T21:38:04.821378",
    "fun": "runner.state.orchestrate",
    "fun_args": [
        {
            "mods": "reactors.startup"
        }
    ],
    "jid": "20190220223804142830",
    "return": {
        "data": {
            "SALT_MASTER_NAME": [
                "Rendering SLS 'base:reactors.startup' failed: Jinja variable 'data' is undefined"
            ]
        },
        "outputter": "highstate",
        "retcode": 1
    },
    "success": false,
    "user": "Reactor"
}
```
It is strange because I also have a reactor for a `salt/auth` event to automatically accept the key when the minion starts up by using the `wheel.key.accept` function which is also using the `data['id']` key and that works fine. I also have a reactor for a `salt/presence/change` event to automatically delete the key when the minion disconnects by using the `wheel.key.delete` function but the difference here is that it's using the `data['lost']` key and that also works fine.

Any ideas why there's no minions matching? Do i have my target above wrong?
From the above data coming from the event bus, there's seems to be an issue recognizing the `data` dictionary as it's failing with `Rendering SLS 'base:reactors.startup' failed: Jinja variable 'data' is undefined`

My `reactor.conf` file looks like:

```
presence_events: True
reactor:
  - 'salt/minion/*/start':
    - salt://reactors/orchestration.sls
```

The `project/salt/reactors/orchestration.sls` looks like:
```
startup_orchestrate:
  runner.state.orchestrate:
    - args:
      - mods: reactors.startup
```

And the  `project/salt/reactors/startup.sls` file looks like(also pasted at the start above):
```
sync_all:
  salt.function:
    - name: saltutil.sync_all
    - tgt: data['id']
    - tgt_type: glob
    - reload_modules: True
```
According to the documentation, this should work. We had this working in the past on a Master running on RedHat 6 and Salt version `salt 2017.7.3 (Nitrogen)`. But now we moved the Master to a Debian 9 machine and higher version of Salt(as seen below), and it's not working anymore.

Any hints or suggestions are much appreciatted!

### Versions Report
`salt 2018.3.3 (Oxygen)` - both master and minion

Thank you

**Comment by garethgreenaway** [comment]
@piersf Thanks for the report.  To confirm, does the `sync_all` reactor execute correctly and the `saltutil.sync_all` runs as expected?  Or the reactor does not execute correctly.  Thanks!

**Comment by piersf** [comment]
@garethgreenaway the sync_all reactor gets triggered/executed but does not do anything as it fails with an error `Rendering SLS 'base:reactors.startup' failed: Jinja variable 'data' is undefined` as you can see from the output above. And the problem seems to be with the `data` dictionary that is not recognized.
