### ISSUE TITLE
docs page for _syspaths.py

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#51768]
### Description of Issue/Question
Currently, there is an outdated tutorial on the saltstack [docs site](https://docs.saltstack.com/en/latest/topics/tutorials/rooted.html) I was going to do a PR to update the `_syspaths.py` file being shown. However, there should probably just be a docs page for this file somewhere in docs.saltstack.com.

A section of the proposed docs page can be dedicated to explaining each path variable. A lot of these variables are self explanatory if you have a strong understanding of salt. However, for newer salt learning users these variables have no meaning and context.

### The Old tutorial version:
```PYTHON
# you need to edit this
ROOT_DIR = *your current dir* + '/salt/root'

# you need to edit this
INSTALL_DIR = *location of source code*

CONFIG_DIR =  ROOT_DIR + '/etc/salt'
CACHE_DIR = ROOT_DIR + '/var/cache/salt'
SOCK_DIR = ROOT_DIR + '/var/run/salt'
SRV_ROOT_DIR= ROOT_DIR + '/srv'
BASE_FILE_ROOTS_DIR = ROOT_DIR + '/srv/salt'
BASE_PILLAR_ROOTS_DIR = ROOT_DIR + '/srv/pillar'
BASE_MASTER_ROOTS_DIR = ROOT_DIR + '/srv/salt-master'
LOGS_DIR = ROOT_DIR + '/var/log/salt'
PIDFILE_DIR = ROOT_DIR + '/var/run'
CLOUD_DIR = INSTALL_DIR + '/cloud'
BOOTSTRAP = CLOUD_DIR + '/deploy/bootstrap-salt.sh'
```
### The current version in 2018.3:
```PYTHON
ROOT_DIR = None                                                                                          
SHARE_DIR = None                                                                                         
CONFIG_DIR = None                                                                                        
CACHE_DIR = None                                                                                         
SOCK_DIR = None                                                                                          
SRV_ROOT_DIR= None                                                                                       
BASE_FILE_ROOTS_DIR = None                                                                               
BASE_PILLAR_ROOTS_DIR = None                                                                             
BASE_MASTER_ROOTS_DIR = None                                                                             
BASE_THORIUM_ROOTS_DIR = None                                                                            
LOGS_DIR = None                                                                                          
PIDFILE_DIR = None                                                                                       
SPM_PARENT_PATH = None                                                                                   
SPM_FORMULA_PATH = None                                                                                  
SPM_PILLAR_PATH = None                                                                                   
SPM_REACTOR_PATH = None                                                                                  
HOME_DIR = None
```
As you can see, a lot of the variables have changed since the tutorial was written.

**Comment by garethgreenaway** [comment]
@alan-cugler Thanks for the report.  Seems like a good idea.  @saltstack/team-core Anyone see a reason not to include a new doc page for the various syspath variables?

**Comment by waynew** [comment]
I'm 💯 for enhancing the docs this way.

**Comment by alan-cugler** [comment]
Alright, I will create a new docs page for `_syspaths.py` file and its variable definitions.

Now my questions are:
- Should I make a seperate issue to go over the variable definitions for the new docs page I will make?
- Should we get rid of this tutorial page all together or update it to be accurate again and useful again?
- I actually created a salt deescalated user installation not from source git (so separate from this tutorial), should I make a tutorial page for that variation as well?

**Comment by alan-cugler** [comment]
@waynew @garethgreenaway 
![2xs2kc](https://user-images.githubusercontent.com/25991646/55586327-4e74e680-56ee-11e9-8b73-b279af12ee51.png)

**Comment by waynew** [comment]
I'd recommend just using this issue, unless there's a big question about something or another.

I don't have a reason to get rid of this tutorial page - I don't know how much it's used, but I know that there are some people/situations that are into it.

My personal preference is to keep it on this page just split it off in its own section.

**Comment by alan-cugler** [comment]
Cool, I will update the tutorial as a separate PR from the new docs page on the _syspaths.py variables.
On that note here are my questions/assumptions for those variables:

1. `ROOT_DIR` 
      - is the general root for salt files in general.
2. `SHARE_DIR` 
      - is for?
3. `CONFIG_DIR` 
      - is for the minion, master, and cloud configs among other things.
4. `CACHE_DIR` 
      - what kind of files are cached here? 
      - I would like a comprehensible description of what can be cached here.
5. `SOCK_DIR` 
      - Setting unix socket.
      - Is this over ruled by the master config option when set?
6. `SRV_ROOT_DIR` 
      - literally just for setting a directory that traditionally holds the salt dir, pillar dir, and top file?
7. `BASE_FILE_ROOTS_DIR` 
      - is this just for explicitly stating where the salt/ directory for salt states is?
8. `BASE_PILLAR_ROOTS_DIR` 
      - setting pillars root file?
9. `BASE_MASTER_ROOTS_DIR` 
      - no idea...
10. `BASE_THORIUM_ROOTS_DIR` 
      - found the thorium docs, so obviously this is for that. traditionally its /srv/thorium as a sibling to salt/
11. `LOGS_DIR` 
      - what kind of logs are present here? a minions log, masters log? reactor/beacons/etc 
      - I would like a comprehensible description of what logs are found here.
12. `PIDFILE_DIR` 
      - I assume the systemcan see these process IDs right? otherwise `systemctl` wouldn't be able to give me a status or restart/start/stop
13. `SPM_PARENT_PATH` 
      - whats it for?
14. `SPM_FORMULA_PATH` 
      - This is the only one mentioned in the SPM docs
15. `SPM_PILLAR_PATH` 
      - whats it for? 
      - the SPM setup talks about having a directory specifically to place the pillars, is this to override that?
16. `SPM_REACTOR_PATH` 
      - whats it for? special reactors the formula creates but doesnt get integrated with your regular reactor directory?
17. `HOME_DIR` 
      - not sure what exactly this affects?
