### ISSUE TITLE
netbox external pillar fails with python3

### ISSUE THREAD

**Issue by misch42** [saltstack/salt#51789]
### Description of Issue/Question

I set up a 2019.2.0-rc2 with python3.4. The netbox external pillar fails.

### Setup
See install instructions of salt and
https://docs.saltstack.com/en/develop/ref/pillar/all/salt.pillar.netbox.html
replate all "pip" with "pip3".

### Steps to Reproduce Issue

When I start salt '*' pillar.items I get an error message in the log:
[salt.pillar      :968 ][CRITICAL][20166] Specified ext_pillar interface netbox is unavailable

Starting the salt-master with logging level debug reveals two problems with the file 
/usr/lib/python3/dist-packages/salt/ext/ipaddress.py

Both lines do not work in python3:
from itertools import imap as map
range = xrange

replace with:
try:
    from itertools import imap
except ImportError:
    imap=map

try:
    xrange
except NameError:
    xrange = range

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

# salt --versions-report
Salt Version:
           Salt: 2019.2.0rc2
 
Dependency Versions:
           cffi: 1.12.1
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.2
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by dwoz** [comment]
@mirceaulinic @ksofa2 Can either of you look into this please?
