### ISSUE TITLE
user error or pipenv problem with dev-packages.httpretty section?

### ISSUE THREAD

**Issue by natemarks** [saltstack/salt#51780]
### Description of Issue/Question
This is probably a user error but I'm baffled.  It may also be a pipenv bug, but I couldn't find anything like that in their issues.

When I use the Pipfile  (pipenv install --dev) it creates the environment without any packages.  If I remote that last section, I get all the packages in the installed environment.  Is there some trick I'm missing?

### Setup
If I remove these, my lockfile and installed packages allseem to be complete.  Otherwise, I get no packages installed or registered in the lockfile

I had to remove these lines to get it to work:
```
[dev-packages.httpretty]
# httpretty Needs to be here for now even though it's a dependency of boto.
# A pip install on a fresh system will decide to target httpretty 0.8.10 to
# satisfy other requirements, and httpretty 0.8.10 has bugs in setup.py that
# prevent it from being successfully installed (at least on Python 3.4).
version = "*"
markers = "python_version >= '3.4'"
```
### Steps to Reproduce Issue
pipenv install --dev

### Versions Report
N/A

**Comment by dwoz** [comment]
@natemarks What is the output of `python3 --version`?

**Comment by natemarks** [comment]
I'm on the develop branch and python3 --version returns 3.6.8 which is specified in pyenv. I have some examples below. I can't seem to reproduce it on my mac  but I can reproduce it on my AWS workspace which is Amazon Linux 2.  If I delete everything after line 34 and run pipenv install --dev, it seems to install  all of the packages correctly. I'm starting to think this is a pipenv bug.

linux_1$ git checkout develop
Switched to branch 'develop'
Your branch is up to date with 'origin/develop'.
linux_1$ git pull
Already up to date.
linux_1$ python3 --version
Python 3.6.8
linux_1$ python2 --version
Python 2.7.15
linux_1$ pyenv global
2.7.15
linux_1$ pyenv local
3.6.8
2.7.15
linux_1$ pipenv install --dev
Creating a virtualenv for this project...
Pipfile: /home/nate/PycharmProjects/salt/Pipfile
Using /usr/bin/python (2.7.14) to create virtualenv...
⠦ Creating virtual environment...Already using interpreter /usr/bin/python
New python executable in /home/nate/.local/share/virtualenvs/salt-6tns2BGN/bin/python
Installing setuptools, pip, wheel...
done.

✔ Successfully created virtual environment! 
Virtualenv location: /home/nate/.local/share/virtualenvs/salt-6tns2BGN
Installing dependencies from Pipfile.lock (07c7e7)...
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Ignoring httpretty: markers 'python_version >= "3.4"' don't match your environment
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:00
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
linux_1$ pipenv run pip list
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
Package    Version
---------- -------
futures    3.1.1  
pip        19.0.3 
setuptools 40.8.0 
six        1.12.0 
wheel      0.33.1 
linux_1$ pipenv --rm
Removing virtualenv (/home/nate/.local/share/virtualenvs/salt-6tns2BGN)…
linux_1$ pipenv --python 3.6.8 install --dev
Creating a virtualenv for this project...
Pipfile: /home/nate/PycharmProjects/salt/Pipfile
Using /home/nate/.pyenv/versions/3.6.8/bin/python3.6 (3.6.8) to create virtualenv...
⠋ Creating virtual environment...Using base prefix '/home/nate/.pyenv/versions/3.6.8'
New python executable in /home/nate/.local/share/virtualenvs/salt-6tns2BGN/bin/python3.6
Also creating executable in /home/nate/.local/share/virtualenvs/salt-6tns2BGN/bin/python
Installing setuptools, pip, wheel...
done.
Running virtualenv with interpreter /home/nate/.pyenv/versions/3.6.8/bin/python3.6

✔ Successfully created virtual environment! 
Virtualenv location: /home/nate/.local/share/virtualenvs/salt-6tns2BGN
Installing dependencies from Pipfile.lock (07c7e7)...
Ignoring futures: markers 'python_version < "3.0"' don't match your environment
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 3/3 — 00:00:01
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.
linux_1$ pipenv run pip list
Package    Version
---------- -------
httpretty  0.9.6  
pip        19.0.3 
setuptools 40.8.0 
six        1.12.0 
wheel      0.33.1

**Comment by natemarks** [comment]
I think your Pipfile is affected by this pipenv bug.  not much to do but with for the fix to trickle down, but it's probably good to be aware of it.
https://github.com/pypa/pipenv/issues/3566
