### ISSUE TITLE
Typo in documentation of _check_cache_minions function

### ISSUE THREAD

**Issue by ritishverma** [saltstack/salt#51788]
https://github.com/saltstack/salt/blob/61baab97de511aab9273446062430f02623f5d2d/salt/utils/minions.py#L275

There is a typo in this line in the documentation of function _check_cache_minions.
It should say 'absent' and not 'absend'
This typo exists in all branches.

**Comment by dwoz** [comment]
@ritishverma Thanks for reporting this.
