### ISSUE TITLE
netbox.openconfig_interfaces fails: '<' not supported between instances of 'dict' and 'dict'

### ISSUE THREAD

**Issue by misch42** [saltstack/salt#51797]
### Description of Issue/Question
In my setup netbox.get_interfaces works. Now I tried netbox.openconfig_interfaces. This fails with:
Passed invalid arguments to netbox.openconfig_interfaces: '<' not supported between instances of 'dict' and 'dict'

### Setup
Plain setup of salt-2019.2.0-rc2, netbox with python 3.6

### Steps to Reproduce Issue
salt -l debug nms3 netbox.openconfig_interfaces device_name='switch03'
(...)
[DEBUG   ] return event: {'nms3': {'ret': "Passed invalid arguments to netbox.openconfig_interfaces: '<' not supported between instances of 'dict' and 'dict' .. versionadded:: 2019.2.0\n\n    Return a dictionary structured as standardised in the\n    `openconfig-interfaces <http://ops.openconfig.net/branches/master/openconfig-interfaces.html>`_\n    YANG model, containing physical and configuration data available in Netbox,\n    e.g., IP addresses, MTU, enabled / disabled, etc.\n\n    device_name: ``None``\n        The name of the device to query the interface data for. If not provided,\n        will use the Minion ID.\n\n    CLI Example:\n\n    .. code-block:: bash\n\n        salt '*' netbox.openconfig_interfaces\n        salt '*' netbox.openconfig_interfaces device_name=cr1.thn.lon\n    ", 'out': 'nested', 'retcode': 1, 'jid': '20190225154145768780'}}
[DEBUG   ] LazyLoaded nested.output
nms3:
    Passed invalid arguments to netbox.openconfig_interfaces: '<' not supported between instances of 'dict' and 'dict'
(...)

### Versions Report
Salt Version:
           Salt: 2019.2.0rc2
 
Dependency Versions:
           cffi: 1.12.1
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.2
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by dwoz** [comment]
@misch42 Thanks for reporting this.

@Ichabond  @zachmoody  Can either of you look into this please?

**Comment by zachmoody** [comment]
Iirc, it's because we're sorting the return from `.filter_()`. I'll submit a PR to remove it.

**Comment by misch42** [comment]
Fix works for me.

**Comment by maznu** [comment]
This bug still exists in SaltStack 3000, and it looks like the patch above has not been committed to master.

Is it worth re-opening this issue until it's been merged into main?

**Comment by krionbsd** [comment]
@zachmoody please note, we miss a test case for this change in 58067, if you might provide the one - it would be awesome

**Comment by sagetherage** [comment]
As we start to get closer to the code freeze date for the Magnesium Release I am looking to de-scope lower severity and PRs that still need test cases written, therefore, moving this to the next release cycle - Aluminium targeted for early 2021.

**Comment by pankajghadge** [comment]
This issue is still exists in version Salt: 3002.6

```
delete test:
  module.run:
    - file.find:
      - path: /tmp/
      - iname: "*_access_log.*.log"
      - delete: f
      - maxdepth: 1
      - mtime: +10d
      - print: path,size,mtime

```
output:--
----------
 ```
         ID: delete test
    Function: module.run
      Result: False
     Comment: 'file.find' failed: '<' not supported between instances of 'str' and 'list'
     Started: 17:10:34.548267
    Duration: 14.472 ms
     Changes:
```
------------------
