### ISSUE TITLE
netbox module fails: The netbox execution module cannot be loaded

### ISSUE THREAD

**Issue by misch42** [saltstack/salt#51795]
### Description of Issue/Question

When I use the netbox module i.e netbox.openconfig_interfaces I get the error
The netbox execution module cannot be loaded:
pynetbox library is not installed.

It seems that the import of netbox does not work properly. When I comment the line about pynetbox.lib everything works. Please check if pynetbox.lib exists at all.

try:
    import pynetbox
    # from pynetbox.lib import RequestError
    HAS_PYNETBOX = True
except ImportError:
    HAS_PYNETBOX = False

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by dwoz** [comment]
@misch42 Thanks for reporting this.

@mirceaulinic @ksofa2 Can either of you look into this please?
