### ISSUE TITLE
saltstack 2019.2 can't be installed on debian 8 (jessie) without python-systemd

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#51808]
### Description of Issue/Question

the new salt-common package 2019.2 for debian 8 has a depency on python-systemd
which isn't in debian 8 default repo's.

### Setup
clean vm debian 8

### Steps to Reproduce Issue
run bootstrap.sh script

this gives the error:
 salt-minion : Depends: salt-common (= 2019.2.0+ds-1) but it is not going to be installed

issue:
apt show salt-common
Package: salt-common
Source: salt
Version: 2019.2.0+ds-1
Maintainer: Debian Salt Team <pkg-salt-team@lists.alioth.debian.org>
Installed-Size: 28.1 MB
Depends: python-apt, python-dateutil, python-jinja2, python-msgpack (>= 0.4), python-pkg-resources, python-requests (>= 1.0.0), python-concurrent.futures, python-tornado (>= 4.2.1), python-yaml, python-systemd, python-psutil, python:any
(<< 2.8), python:any (>= 2.7.5-5~)
Recommends: lsb-release, python-croniter
Breaks: python-mako (<< 0.7.0)
Homepage: http://saltstack.org/
Priority: extra
Section: admin
Download-Size: 6,334 kB

temp solution:
install jessie backports:

add this to sources.list
deb http://deb.debian.org/debian jessie-backports main

run bootstrap.sh again and this time everything get's installed.

**Comment by Ch3LL** [comment]
ping @dmurphy18

**Comment by thunder-spb** [comment]
Got same error for Salt 2018.3

**Comment by thunder-spb** [comment]
@Ch3LL Hi, do I need to fill another issue for 2018.3 version?

**Comment by dafyddj** [comment]
Response provided [here](https://github.com/saltstack/salt-pack/issues/657#issuecomment-467932962).

**Comment by Ch3LL** [comment]
ahhh thanks for finding that @dafyddj i'll go ahead and close this here and anyone can comment there if needed.

**Comment by myii** [comment]
For Docker, using `debian:jessie-backports` has worked for us (the reference link directly above).

**Comment by dmurphy18** [comment]
Reopened to note https://github.com/saltstack/salt-pack/issues/657
