### ISSUE TITLE
schedule.disable doesn't work in 2019.2.0

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#51825]
Master and minion on 2019.2.0.
Either `schedule.disable` doesn't work at all, or the application of a `schedule.present` state turns it back on.
This is a very annoying change in behaviour from 2018.3.3.

**Comment by garethgreenaway** [comment]
@OrangeDog To confirm, are you talking about `disable` which disables the entire scheduler or `disable_job` which disables one schedule job?

**Comment by OrangeDog** [comment]
> are you talking about `disable` which disables the entire scheduler

Yes

**Comment by garethgreenaway** [comment]
@OrangeDog Thanks!  That definitely shouldn't be happening.  Will take a look.

**Comment by garethgreenaway** [comment]
Closing out as this is fixed in the 2019.2 branch and will be available in the 2019.2.1 release.
