### ISSUE TITLE
unit.utils.test_schema.ConfigTestCase-20190225154848 is failing

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#51845]
There are 4 failures here:

https://jenkinsci.saltstack.com/job/2017.7/job/salt-ubuntu-1604-py2/46/testReport/unit.utils.test_schema/ConfigTestCase/

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_schema.py", line 1889, in test_anyof_config_validation
    self.assertIn('is not valid under any of the given schemas', excinfo.exception.message)
AssertionError: 'is not valid under any of the given schemas' not found in "'maybe' is not one of ['yes']"
```		

Happening under (at least):

- fedora28 - py2
- debian8 - py2
- centos7 - py2
- centos6 -py2
- windows2019-py2

**Comment by dwoz** [comment]
This should be fixed as of https://github.com/saltstack/salt-jenkins/pull/1319
verified by https://jenkinsci.saltstack.com/job/2017.7/job/salt-centos-7-py2/48/

**Comment by dwoz** [comment]
This has been fixed and verified
