### ISSUE TITLE
[Feature Request] pip.installed has no support for "--user" argument 

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#51847]
### Description of Issue/Question
Pip supports installation in user namespace: https://pip.pypa.io/en/stable/user_guide/#user-installs
Currently, `pip.installed` state doesn't support it in any release

Would be really nice if this could be added.

**Comment by Ch3LL** [comment]
will approve as a feature request thanks

**Comment by waynew** [comment]
@xeacott this was the issue
