### ISSUE TITLE
python-jinja2 Hash Sum mismatch

### ISSUE THREAD

**Issue by mheder79** [saltstack/salt#51859]
Hi,

You have 2 version of **python-jinja2_2.9.4-1_all.deb**:
http://repo.saltstack.com/py3/debian/9/armhf/2018.3/dists/stretch/main/binary-armhf/Packages
**Size: 110634**
SHA256: 954060b6e3259fe1c77547470f5eee073fc70a4e896cf67e30f70d0e0efeb6a9
Depends: python-markupsafe, python:any (<< 2.8), python:any (>= **2.7.5-5~**)

https://repo.saltstack.com/salt_rc/apt/debian/9/amd64/dists/stretch/main/binary-i386/Packages
**Size: 118230**
SHA256: 0827e8c8b67490ba5ed03f8f277a6cac88d8ed0e2e0731545f1138d3a412a287
Depends: python-markupsafe, python:any (<< 2.8), python:any (>= **2.7~**)

2 days ago our jfrog artifactory changed the cached file:
```
Err:1 https://artifacts.ourdomain.com/mirror-saltstack.com-debian/debian/9/amd64/2018.3 stretch/main amd64 python-jinja2 all 2.9.4-1
  Hash Sum mismatch
  Hashes of expected file:
   - SHA256:0827e8c8b67490ba5ed03f8f277a6cac88d8ed0e2e0731545f1138d3a412a287
   - SHA1:5402d77113abacd26c00b04d8e4d038cdb92fa73 [weak]
   - MD5Sum:b95c1764ed69788484c1cd0efacce618 [weak]
   - Filesize:118230 [weak]
  Hashes of received file:
   - SHA256:954060b6e3259fe1c77547470f5eee073fc70a4e896cf67e30f70d0e0efeb6a9
   - SHA1:180719a596e36b0e0c40f2f012ae3414d206fde2 [weak]
   - MD5Sum:9005606dcfa956e3742fcd68df2e5bab [weak]
   - Filesize:110634 [weak]
  Last modification reported: Thu, 21 Jun 2018 20:56:02 +0000
```

Please check your infrastructure and/or build flow.

Thank you.
Regards,

**Comment by garethgreenaway** [comment]
@dmurphy18 FYI.

**Comment by dmurphy18** [comment]
@mheder79 This issue has already been reported and is being worked on in salt-pack GitHub repository, which is the correct place for Salt packaging issues. see issue https://github.com/saltstack/salt-pack/issues/594 . You can track the issue there.

Unfortunately don't have a working solution at the moment but it is getting attention.
Closing this since already an issue for this.
