### ISSUE TITLE
integration.shell.test_runner.RunTest and integration.shell.test_key.KeyTest test failures - seems like results are swapped

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#51851]
https://jenkinsci.saltstack.com/job/2017.7/job/salt-fedora-28-py2/50/testReport/integration.shell.test_key/KeyTest/test_list_acc_eauth/

and

https://jenkinsci.saltstack.com/job/2017.7/job/salt-fedora-28-py2/50/testReport/integration.shell.test_runner/RunTest/test_salt_run_with_eauth_all_args/

The latter expected an `eauth` failure, but instead got some kind of result. The former expected to get a list of accepted keys, but got an `eauth` failure. It might be a coincidence, which would be surprising.

@s0undt3ch it looks like you made some changes here - if this doesn't look like it's anything you've had a hand in let me know and I can take it.

**Comment by s0undt3ch** [comment]
This test failure is no longer present in 2017.7 nor 2017.7.9
