### ISSUE TITLE
How to re-run a custom grain

### ISSUE THREAD

**Issue by mattdodge** [saltstack/salt#51857]
### Description of Issue/Question
We have a custom grain set up that tracks a version of a Python package that is installed.
```python
def pkg_version_grain():
    import mypkg
    return {'mypkg': {'version': mypkg.__version__}}
```

After syncing the grain it works fine:
```bash
$ salt myhost saltutil.sync_grains
$ salt myhost grains.get mypkg
myhost:
  -------
  version:
     1.0.0
```

However, then after I update the package, say with a `pip install`, I cannot get the grain value to update without a minion restart.
```bash
$ salt myhost pip.install mypkg==2.0.0
$ salt myhost grains.get mypkg
myhost:
  -------
  version:
     1.0.0
```

I have tried `saltutil.sync_grains`, `saltutil.refresh_grains`, `saltutil.refresh_modules`, `saltutil.sync_all`, all to no avail. After the minion restarts the grain value is picked up correctly though. 

I know grains aren't supposed to change that often but I feel like a package version is a valid custom grain. Is there any way to trigger the custom grain to "run again"? Thanks!

**Comment by ymasson** [comment]
Hi, @mattdodge 

what is your salt version ?

I have a similar issue since upgraded in 2019.2.0, but I can't confirm and reproduce it. The grains on master side seems not correctly upgraded.

Thanks

**Comment by mattdodge** [comment]
I'm on 2018.3.3 still (I actually didn't even realize that 2019.2.0 was out, so that's good to know!)
