### ISSUE TITLE
Fluorine: minion_pillar_cache: True leads to exception

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#51854]
### Description of Issue/Question
After updating to the Fluorine and switching to python36 I run on the problem with `salt-call`. Any execution of the `salt-call` with any module leads to the this stackstrace:
https://gist.github.com/Oloremo/8c1d9da8a66342f0eb2354442825d9ce

Simplest example is somethinf like `cmd.run ls`

I pinpoint this problem to a single minion option - `minion_pillar_cache: True`. Setting it to False solves the issue. 

### Steps to Reproduce Issue
I have a very customized Salt deployment, it's a Centos 7 with python36 from EPEL and salt is installed via pip and runs from non-root user so I'm not sure if it's reproducible on a normal deployment.

But I was able to reproduce it using a docker to mimic mine deployment. So if you like or if you can't reproduce it on your env, you could download docker project from here: https://www.dropbox.com/s/b5j5qp55e0c622j/salt-bug.tar.gz?dl=0
unpack it in some dir and follow 3 steps instruction(included in README file):
```
1) cd into root of this directory
2) docker build -t salt-bug .
3) docker run -it salt-bug bash /start-daemons.sh
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.6 (default, Aug 13 2018, 18:24:23)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core
```

**Comment by waynew** [comment]
Looks like there's a place where we're not encoding before dumping to the cache. Putting together some tests & a PR.

**Comment by waynew** [comment]
@Oloremo give that patch a try and see if that takes care of things for you!
