### ISSUE TITLE
The win_dism module does not work on a 64-bit architecture when running inside a 32-bit process

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#51860]
### Description of Issue/Question
On a 64-bit windows system, there are two versions of the `DISM.exe` binary. The first one (64-bit) is `/Windows/System32/Dism.exe` and the second one (32-bit) is `/Windows/SysWOW64/Dism.exe`. The `win_dism` module simply trusts that the PATH is set correctly as it just tries to execute "dism".

It is prudent to note that on 64-bit versions of windows, the directories for `/Windows/System32` and `/Windows/SysWOW64` have different semantics depending on the architecture of the application that is being used. So the path to the correct instance of `Dism.exe` is different depending on the Python interpreter that is running the salt process.

Normally it is assumed that `/Windows/SysWOW64` contains the 32-bit binaries (such as `Dism.exe`) and `/Windows/System32` contains the 64-bit binaries. However, when running a 32-bit application (such as the 32-bit version of Python) both the `/Windows/SysWOW64` and `/Windows/System32` directories point to the 32-bit binaries for the platform. This is done for compatibility reasons as historically the `/Windows/System32` directory contains the system tools available for the platform.

Unfortunately this means that via a 32-bit process, it would normally be impossible to call the correct 64-bit version of `Dism.exe`. However, on a 32-bit process windows creates a file-system redirection to the 64-bit platform tools at `/Windows/Sysnative`. So depending on the process architecture, the correct path can be either `/Windows/System32` or `/Windows/Sysnative`.

In summary, if one is running salt on a 32-bit version of Windows. Nothing matters, everything is okay.
If one is running salt on a 64-bit version of Windows, then the correct path to `Dism.exe` depends on the architecture of the Python interpreter that is running.

If salt is running in a 32-bit interpreter, then the path to the 64-bit `Dism.exe` is at `/Windows/Sysnative/Dism.exe`. If salt is running in a 64-bit interpreter, then the path to the 64-bit `Dism.exe` is at `/Windows/System32`.

### Symptom (in minion log file)
```
2019-02-27 09:29:52,104 [salt.minion      :1667][WARNING ][2740] The minion function caused an exception
2019-02-27 09:30:02,510 [salt.loaded.int.module.cmdmod:774 ][ERROR   ][3132] Command '[u'DISM', u'/English', u'/Online', u'/Get-Features']' failed with return code: 11
2019-02-27 09:30:02,510 [salt.loaded.int.module.cmdmod:776 ][ERROR   ][3132] stdout: 
Deployment Image Servicing and Management tool
Version: 6.2.9200.16384


Error: 11

You cannot service a running 64-bit operating system with a 32-bit version of DISM. 
Please use the version of DISM that corresponds to your computer's architecture.

The DISM log file can be found at C:\Windows\Logs\DISM\dism.log
2019-02-27 09:30:02,510 [salt.loaded.int.module.cmdmod:780 ][ERROR   ][3132] retcode: 11
```

### Setup
Install a 64-bit version of Windows that is newer than Vista (inclusive), and then use the 32-bit salt-minion so that a 32-bit version of Python gets installed.

### Steps to Reproduce Issue
Try to use anything in the `win_dism` module such as `get_features` or something.. Another way to prove that the wrong one is being executed would be to use `cmd.which` as so:
```
$ salt $target cmd.which Dism
bX_nxPEVRyWOcIDBECwW:
    C:\Windows\system32\dism.EXE

-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 1
# of minions returned: 1
# of minions that did not return: 0
# of minions with errors: 0
-------------------------------------------
```
If the path to the System32 `Dism.exe` is returned, then the `win_dism` module will not work despite the tool being available

### Notes
Really this will happen with all the platform tools on Windows. If one wants to avoid smashing gophers related to calling the wrong tool, there should be a utility to locate platform-specific tools. It's really not safe/reliable to explicitly trust the PATH environment to locate these types of tools.

### Versions Report
This is independant of the version as none of the commits try to do anything funny with `/Windows/System32/Sysnative`

**Comment by arizvisa** [comment]
I don't have time to fix this one either. It'd be greatly appreciated if you guys can fix this one.

**Comment by arizvisa** [comment]
The issue I mentioned with pathing will require a little bit more effort than just hardcoding paths. Probably reading the `%windir%` environment variable and then working from there. However, I did a quick search and found a couple modules that also have issues related to pathing

The `salt.modules.win_license` module seems to hardcode the Path to System32 here where one can use an environment variable to get there.

The `salt.modules.win_autoruns` seems to hardcode a ton of paths, some of which won't work on different versions of Windows (Newer than Win7). This module should probably be deprecated, (or if one really wants to fix it they should use environment variables as often as possible).

**Comment by arizvisa** [comment]
You can ignore the notes section in my report as it seems that there aren't enough cases to warrant something under `salt.utils`. Unless you guys think it's worthwhile to expose some simple system to users for third-party modules I guess. Anyways...

**Comment by twangboy** [comment]
Are you using the official salt installers? Did you install 32bit installer on a 64bit system? This will not only affect paths but also the registry as well. There's a SysWOW64 section in the registry for 32bit stuff. We don't recommend running 32bit salt on 64bit systems for this very reason.

Or are you running 32bit python and installed salt via other means?

**Comment by arizvisa** [comment]
Yes, default salt installers. 32-bit installer on a 64-bit system.

You're right that there is a 32-bit mapping of the registry for the Application key, but you're mistaken in that it will also affect salt as well. None of the registry keys that salt explicitly trusts are under the Software key and so the semantics between 32-bit and 64-bit accesses of the registry are the same.

However, due to the salt installer running as LocalSystem this puts the default userprofile under the system/config/systemprofile directory which is actually different depending on whether or not you're running 32-bit or 64-bit. Regardless of this side-effect, Salt explicitly trusts the environment for the path to system binaries (Such as Dism.exe) or binaries that Salt depends on. This is wrong as a simple install of some application that modifies the System Path will interfere with salt modules accessing these paths thus breaking them.

**Comment by arizvisa** [comment]
This is surprisingly really common in the codebase, such as my salt.utils.path.which patch which originated due to Node.js including two scripts `npm`, and `npm.cmd` for example.

Something for node.js would be expected since that's a moving target and your release schedule makes it hard for one to adapt and catch these kinds of issues, but something like a System binary such as Dism.exe is something that is easy to fix and make the module more reliable.

**Comment by arizvisa** [comment]
It's up to y'all though. I'm actually surprised how many things in your 2018.3.3 release just were just simply not working but documented as they were (in Windows). With more defensive programming such as searching for absolute paths to binaries that modules depend on, or ensuring strings fetched from external sources are correctly formatted these small-simple bugs that prevent modules from working won't exist.

**Comment by twangboy** [comment]
Thanks for pointing us to these issues. We've recently gotten the test suite running on Windows running a specific group of tests. I think once we're able to get all the tests running on Windows it will catch a lot of these things.

So, are you suggesting we add an option to specify 32 or 64-bit binaries to be used in the modules? Or modify `salt.utils.files.which` to return the version that corresponds to the salt bitness and not the platform architecture itself? Is there a case where salt would need to run the 32-bit dism one time and the 64-bit dism another?

Is there a specific issue you're trying to solve by running 32-bit salt on 64-bit windows? Are you averse to using 64-bit salt for some reason? The reason I asked is we have talked about disallowing the 32-bit installer on 64-bit systems to avoid issues like these. But if there's a need to have 32-bit salt run 64-bit binaries then we would need to look at this more closely.

**Comment by arizvisa** [comment]
I mean the safest bet is to look at the architecture of the operating system and then call the correct one via the full path, right? Whether a 32-bit process or a 64-bit process is running doesn't differentiate which path to the tool is the correct one to use. There's already a grain there to determine the system architecture, so when determining the path to a system tool walk through `sysnative`, and then `system32`.

On the Windows platform, the ability to run 64-bit binaries from a 32-bit address-space is possible as that was the whole purpose of the implementation of the WOW64 subsystem (probably because of the desire to not force users to have to upgrade their unmaintained proprietary garbage). But in reality, your 32-bit process is running in a 64-bit address-space, so the operating system is not really limiting you on whether a 32-bit process can use any of the 64-bit tool/system-calls. And in all actuality from a 32-bit process, all of your system calls are tunneled through `wow64cpu.dll` so you can even still use the 64-bit apis from a 32-bit process via a call gate. So running 32-bit or 64-bit binaries and linking with 32-bit/64-bit libaries is not a limitation of the operating system in the slightest.

The issue here is that there's two versions of the `Dism.exe` platform tool (`sysnative` and `syswow64`) and that both executables explicitly look at the architecture and then tell you if you're using the wrong path. Normally there isn't a difference here as none of the other platform tools that Salt uses explicitly checks the architecture except for `Dism.exe`. But, the reason why the wrong version is being called is because Salt is explicitly trusting the PATH environment variable to locate platform tools (as this is set in the `HKLM` hive via a non-virtualized key so it has no knowledge of the system architecture), and other than the PATH environment variable, executing anything else between a 32-bit process and a 64-bit will be the same.

Essentially due to Salt running as LocalSystem, only the PATH environment variable and the location of the LocalSystem profile have differing semantics depending on whether a wow64 or non-wow64 process is loaded due to the file-system redirect I had prior mentioned.

**Comment by twangboy** [comment]
OK... I think we'll add this to `salt.utils.files.which`. We'll have it look in the native System32 and then fall back to `path` if not found there for binaries that aren't part of the Windows system.

**Comment by arizvisa** [comment]
Rather than changing the semantics of `which`, which is well-defined, wouldn't it be safer to modify the dism module to call `%windir%\Sysnative\Dism.exe`, and then on failure call `%windir%\System32\Dism.exe`?

**Comment by arizvisa** [comment]
I mean safer by it affecting less of the software which in essence makes it more reliable since you're improving only what is necessary. I mean I guess I can write a PR if you'll accept it.

**Comment by twangboy** [comment]
That would be fantastic!

**Comment by twangboy** [comment]
@arizvisa The above PR should address this issue.

**Comment by arizvisa** [comment]
@twangboy, looks perfect sir. I'll test it out in just a second here.

**Comment by arizvisa** [comment]
flawless. works without issue. just tested all of its functions. I had to backport it to 2018.3.3 because those are the only minions that I have, but I'd be pretty surprised if it acted differently in 2019.2.0

**Comment by arizvisa** [comment]
Now I have hearts.exe on all my Windows minions. yay.

**Comment by arizvisa** [comment]
The only issue (which is probably where your testcases com up) is when you're using `environ.get`, you're missing the second parameter which should return a string:

It results in the following exception on posixy platforms:
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1471, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/var/cache/salt/minion/extmods/modules/win_dism.py", line 31, in <module>
    if os.path.exists(os.path.join(os.environ.get('SystemRoot'), 'SysNative')):
  File "/usr/lib64/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
```

**Comment by arizvisa** [comment]
I modified your path test to the following. This way if the environment is non-standard in some way, it'll fall back to the original logic, and also `bin_dism` will still be assigned on non-windows environments. (even though it shouldn't matter)
```
# We always want to use the version of dism that matches the architecture of the
# host machine. On 32bit boxes that will always be System32. On 64bit boxes that
# are running 64bit salt that will always be System32. On 64bit boxes that are
# running 32bit salt the 64bit dism will be found in SysNative
# Sysnative is a virtual folder, a special alias, that can be used to access the
# 64-bit System32 folder from a 32-bit application
try:
    # Wndows has none of this stuff
    if salt.utils.platform.is_windows():
        raise OSError

    if os.path.exists(os.path.join(os.environ['SystemRoot'], 'SysNative')):
        bin_path = os.path.join(os.environ['SystemRoot'], 'SysNative')
    else:
        bin_path = os.path.join(os.environ['SystemRoot'], 'System32')
    bin_dism = os.path.join(bin_path, 'Dism.exe')

except:
    bin_dism = 'Dism.exe'
```

**Comment by arizvisa** [comment]
lol, that first case should be inverted. but i think you get it...

**Comment by twangboy** [comment]
Yeah, I didn't test what would happen outside of Windows... My bad. I'll get that fixed up.

**Comment by arizvisa** [comment]
All good.
