### ISSUE TITLE
Icinga2 path fix doesn't work

### ISSUE THREAD

**Issue by sevrob** [saltstack/salt#51862]
### Description of Issue/Question

In 2018.3.3 icinga2 module had hardcoded wrong paths to cert files. (icinga <2.8 uses /var/lib/icinga2/certs, while older versions uses /etc/icinga2/pki).
We fixed this by hacking the icinga2.py module.

In 2018.3.4 this is supposed to be fixed.
But at least in our environment it's just broke another way...
The old icinga2.py module files hacked with correct paths still works fine (in 2018.3.4).

Error message from minion log:
```
:321 ][ERROR   ][9720] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/states/icinga2.py", line 180, in save_cert
    cert = "{0}trusted-master.crt".format(get_certs_path())
  File "/usr/lib/python2.7/site-packages/salt/utils/icinga2.py", line 22, in get_certs_path
    icinga2_output = __salt__['cmd.run_all']([salt.utils.path.which('icinga2'), "--version"], python_shell=False)
NameError: global name '__salt__' is not defined
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Master: 2018.3.4
Minion: 2018.3.4

icinga2 config state file (started from reactor after icinga2 client is installed) :
save_cert:
  icinga2.save_cert:
    - name: {{ host }}
    - master: {{ site.master }}
    - require:
        - file: make_certdir

create_nodeconfig:
  icinga2.node_setup:
    - name: {{ host }}
    - ticket: {{ ticket }}
    - master: {{ site.master }}
    - require:
      - icinga2: save_cert

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
run icinga2.save_cert

### Versions Report
Master: 2018.3.4
Minion: 2018.3.4

**Comment by garethgreenaway** [comment]
Fixed in https://github.com/saltstack/salt/pull/50765 and available in 2018.3.4.  If you're minion is still running 2018.3.3 the fix for that particular issue will not be in place.  You'll need to upgrade the minion to 2018.3.4 as well as the master.

**Comment by sevrob** [comment]
Ah, I see I did a mistake, I meant to write that we had 2018.3.4 on both. We thought we could remove our old hack from 2018.3.3, but the new fix seems to fail on our system.

**Comment by garethgreenaway** [comment]
@sevrob Thanks.  Now I see the problem.  Had to wrap the traceback in tick marks as Github was rendering it differently.

**Comment by Talkless** [comment]
@garethgreenaway Any ideas why you fix is not available in latest 2018.3.5 release ( https://github.com/saltstack/salt/blob/v2018.3.5/salt/utils/icinga2.py) ?

**Comment by garethgreenaway** [comment]
@Talkless Apologies for the delay in responding.  The 2018.3.5 release was a CVE release only and we wanted to minimize the changes that went in so it was based off the 2018.3.4 branch, which did not include that fix.  The fix is in the master branch as well as the 3000 and 3001 releases.

**Comment by gasmick** [comment]
On CentOS machines, probably in all RedHat family, this get_certs_path() throws an error: 
> AttributeError: 'NoneType' object has no attribute 'group'

This happens because
` version = re.search(r"r\d+\.\d+", icinga2_output["stdout"]).group(0)`
doesn't find anything, since the version label in "icinga2 --version" doesn't include the letter 'r' as on Ubuntu, probably in all Debian family. It would work without 'r' inside the regex.

**Comment by sagetherage** [comment]
this was fixed in Neon (3000), closing, if more issues persist, please open a new issue with all relevant information.
