### ISSUE TITLE
pony output module broken on colour terminals

### ISSUE THREAD

**Issue by nergdron** [saltstack/salt#51877]
### Description of Issue/Question

ponysay output broken because of ANSI colour codes.

### Steps to Reproduce Issue
run a local command using the pony output module, see a bunch of escape codes instead of the actual ANSI graphics. ;)

```
salt-call --local --out pony disk.percent /
b'\x1b[0m\x1b[0m ___________________________ \x1b[0m\n\x1b[0m/ \x1b[0;36mlocal:\x1b[0;0m\x1b[0m\x1b[0m                    \\\x1b[0m\n\x1b[0m\\ \x1b[0m\x1b[0;32m    21%\x1b[0;0m\x1b[0m                   /\x1b[0m\n\x1b[0m --------------------------- \x1b[0m\x1b[00m\n
[...etc]
```

probably needs to just pass through the output uninterpreted on systems with a colour terminal.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 3.6.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: Ubuntu 18.10 cosmic
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-15-generic
         system: Linux
        version: Ubuntu 18.10 cosmic
```

**Comment by mchugh19** [comment]
I got curious about this one and took a look. It seems that salt simply passes the execution module output to ponysay. 
https://github.com/saltstack/salt/blob/develop/salt/output/pony.py#L67
`return subprocess.check_output(['ponysay', salt.utils.data.decode(high_out)])`

So all of the ANSI codes are from ponysay and have nothing to do with salt. If you are seeing escape codes, it's probably down to terminal configuration. Does running ponysay outside of salt show different output?

**Comment by nergdron** [comment]
yeah, ponysay outside of salt works correctly, shows some lovely colour graphics and stuff. however, I've found a fix that seems very easy! in the check_output call, if you add universal_newlines=True, then it works correctly:

```python
    return subprocess.check_output(['ponysay', salt.utils.data.decode(high_out)], universal_newlines=True)  # pylint: disable=E0598
```

**Comment by neildataprophet** [comment]
This does, indeed fix the issue
