### ISSUE TITLE
[fluorine] fedora 28 auth test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#51885]
@Ch3LL commented on [Tue Dec 11 2018](https://github.com/saltstack/salt-jenkins/issues/1238)

the tests:

```
integration.shell.test_auth.AuthTest.test_pam_auth_valid_group
integration.shell.test_auth.AuthTest.test_pam_auth_valid_user
integration.shell.test_runner.RunTest.test_salt_run_with_eauth_all_args
```

are failing on fedora 28 python2 tests

https://jenkinsci.saltstack.com/job/fluorine/job/salt-fedora-28-py2/56/

---

@Ch3LL commented on [Tue Dec 11 2018](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-446231473)

also this test as well: integration.shell.test_key.KeyTest.test_list_acc_eauth

---

@terminalmage commented on [Fri Dec 21 2018](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-449451548)

Can't reproduce in docker, spinning up an AWS box now.

---

@terminalmage commented on [Thu Jan 03 2019](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-451171735)

Was not able to reproduce in AWS either. Destroying box and recreating, will try again.

---

@terminalmage commented on [Mon Jan 07 2019](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-452005490)

At least some of this appears to have been caused by SSSD issues on Fedora 28, which are non-fatal but nonetheless make the set_date/set_expire functions fail. https://github.com/saltstack/salt/pull/51079 fixes those issues in the shadow module. I made that fix in 2018.3 however, so it'll need to be merged forward into fluorine and then the tests will need to run after that merge, before we know how many of the failures were fixed by this.

---

@Ch3LL commented on [Mon Jan 07 2019](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-452015001)

also fixes this possibly: https://github.com/saltstack/salt-jenkins/issues/1217

---

@terminalmage commented on [Mon Jan 07 2019](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-452097159)

Apologies for the confusion, I meant to make the above comment on #1217. I actually still cannot reproduce these failures, even using an AWS box created using TestKitchen. The PAM eauth plugin is failing despite being configured correctly, and despite the `shadow.set_password` function returning `True` (suggesting that the password was properly set).

Here's some logging from the jenkins run. Note that I've redacted the password, though it doesn't matter since the user is removed (and the box is gone anyway).

```
10:28:36,737 [salt.auth             :297 ][WARNING ] Authentication failure of type "eauth" occurred.
10:28:36,737 [salt.master           :2085][WARNING ] Authentication failure of type "eauth" occurred.
10:28:36,740 [salt.transport.zeromq :226 ][DEBUG   ] Closing AsyncZeroMQReqChannel instance
10:28:36,741 [salt.transport.ipc    :394 ][DEBUG   ] Closing IPCMessageSubscriber instance
10:28:36,743 [salt.utils.lazy       :104 ][DEBUG   ] LazyLoaded nested.output
10:28:36,922 [tests.support.case    :503 ][DEBUG   ] Result of run_salt for command '-c /tmp/salt-tests-tmpdir/config -t 500 -a pam "*" test.ping --username saltdev --password REDACTED': ['Authentication error occurred.']
```

---

@Ch3LL commented on [Tue Jan 15 2019](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-454413933)

did you try running the entire test suite?

---

@Ch3LL commented on [Tue Jan 15 2019](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-454500734)

also just as a note these are failing on 2018.3 as well.

---

@Ch3LL commented on [Tue Jan 15 2019](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-454501540)

also this test is failing and seems to be related: integration.shell.test_key.KeyTest.test_list_acc_eauth

---

@sagetherage commented on [Tue Jan 15 2019](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-454563255)

Tom approved to remove this from 2019.2 - keeping it assigned to @terminalmage 

---

@Ch3LL commented on [Mon Jan 28 2019](https://github.com/saltstack/salt-jenkins/issues/1238#issuecomment-458184542)

this is no longer failing on 2019.2.0.rc1, but still on 2018.3.4

**Comment by bryceml** [comment]
We don't test fedora 28 anymore.
