### ISSUE TITLE
netaddr dependency issue on CentOS 6

### ISSUE THREAD

**Issue by dvandok** [saltstack/salt#51880]
### Description of Issue/Question

The module [netaddress](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.netaddress.html#module-salt.modules.netaddress) does not function on CentOS 6 due to a missing dependency on python-netaddr and a mismatching python version between salt (python 2.7) and python-netaddr (python 2.6).

### Setup
Only a stand-alony salt-minion is required.

### Steps to Reproduce Issue

1. Take a CentOS 6.10 machine (here's one I made earlier)
2. yum install https://repo.saltstack.com/yum/redhat/salt-repo-latest.el6.noarch.rpm
3. yum install salt-minion
4. salt-call --local netaddress.cidr_netmask 192.168.0.0/20

Result:
```
'netaddress' __virtual__ returned False: The netaddress execution module cannot be loaded: netaddr python library is not installed.
```

Further steps: install python-netaddr manually
```
yum install python-netaddr
```
Followed by the above command results in the same output.

Dependencies of python-netaddr (truncated for brevity):

```
# rpm -qilR python-netaddr
Name        : python-netaddr               Relocations: (not relocatable)
Version     : 0.7.5                             Vendor: CentOS
Release     : 4.el6                         Build Date: wo 07 dec 2011 18:27:14 CET
Install Date: wo 27 feb 2019 21:21:36 CET      Build Host: c6b18n3.bsys.dev.centos.org
Group       : Development/Libraries         Source RPM: python-netaddr-0.7.5-4.el6.src.rpm
Size        : 5194930                          License: BSD
Signature   : RSA/SHA1, do 08 dec 2011 22:00:44 CET, Key ID 0946fca2c105b9de
Packager    : CentOS BuildSystem <http://bugs.centos.org>
URL         : https://github.com/drkjam/netaddr
Summary     : Pythonic manipulation of IPv4, IPv6, CIDR, EUI and MAC network addresses
Description :
A pure Python network address representation and manipulation library.
...
/usr/bin/python  
python(abi) = 2.6
rpmlib(CompressedFileNames) <= 3.0.4-1
rpmlib(FileDigests) <= 4.6.0-1
rpmlib(PartialHardlinkSets) <= 4.0.4-1
rpmlib(PayloadFilesHavePrefix) <= 4.0-1
rpmlib(PayloadIsXz) <= 5.2-1
/usr/bin/netaddr
/usr/lib/python2.6/site-packages/netaddr
...
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 20 2019, 09:59:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.10 Final
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-754.6.3.el6.x86_64
         system: Linux
        version: CentOS 6.10 Final
```

**Comment by Ch3LL** [comment]
you will need to install the python2.7 version of the package, since salt runs python2.7. you can do this with pip.

**Comment by dvandok** [comment]
> you will need to install the python2.7 version of the package, since salt runs python2.7. you can do this with pip.

As a workaround I've rebuild the rpm for python2.7. I think there shouldn't be a specific python version dependency in that package. But the correct solution is to ship it with salt.

**Comment by Ch3LL** [comment]
we only include the packages that require to run salt defaults. We do not include additional dependencies in our repo for additional modules. This is expected behavior and you will need to either build the rpm as you have done or pip install the module.

**Comment by dvandok** [comment]
While I understand the point of view, I am very disappointed.

From the user's perspective, the system is broken. Everything is installed with yum and rpm, the error message reads
```
netaddr python library is not installed.
```
but according to the rpm database, it clearly is. This is the point where the majority of users would
be stumped and need expert help to figure out what to do next.

It took me a while to figure out what the actual cause was: saltstack doesn't work with the native python implementation but ships its own python2.7. Diverting from the base OS can be a valid choice but it does have implications: it carries over the responsibility for taking care of the dependencies to those who decided to divert.

I have found a solution that works for me. I did not need to file this bug report, but I felt it would be the right thing to do for a good citizen of the community to helpfully point out flaws in a system, so they can be fixed and the end result be made better.

I thought the bug report was short, to the point, easy to understand, trivial to reproduce and therefore simple to fix. Flagging the broken behaviour as 'expected' is a very disappointing
outcome.

At the very least, a workaround should be documented. I haven't tried but I bet that if I typed `pip install netaddr` it would install the python2.6 version of the module since that is what the native pip will do.

In a real use case this should be rolled out to hundreds of minions, so an example piece of salt state to make sure the module is installed would be a valuable addition to the documentation.

**Comment by Ch3LL** [comment]
First of all i do want to say thank you for opening the issue, we always love it when users do this and I hope you will continue to do so going forward.  Unfortunately we decided at the time of the 2017.7 release and going forward to not build the packages for all of the additional modules outside of salts main dependencies.

this was initially documented with the 2017.7 release: https://docs.saltstack.com/en/latest/topics/releases/2017.7.0.html#python-2-6-deprecation

There was also a duplicate issue here: https://github.com/saltstack/salt/issues/42979

You do bring up a good point that we could document this so its more visible outside of just the 2017.7.0 release notes. I think it would be good to mention a note here as well: https://repo.saltstack.com for the centos6 tab to make it more obvious. I'll approve this as a documentation bug assign to myself and update those docs.

**Comment by dvandok** [comment]
Thank you very much. I really appreciate that.
