### ISSUE TITLE
[2019.2.0rc1] windows tests timing out

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#51888]
@Ch3LL commented on [Tue Jan 15 2019](https://github.com/saltstack/salt-jenkins/issues/1252)

The tests on windows python3 are hanging and not completing the test run:

https://jenkinsci.saltstack.com/job/2019.2.0.rc1/view/Python3/job/salt-windows-2016-py3/8/console

ping @dwoz or @twangboy do you guys have any ideas here?

---

@twangboy commented on [Tue Jan 15 2019](https://github.com/saltstack/salt-jenkins/issues/1252#issuecomment-454609133)

From slack:
All the py3 tests seem to be hanging on `integration.modules.test_cp.CPModuleTest.test_get_file_templated_paths`
I've run that test locally and it finishes just fine... (edited) 
Shane Lee [12:21 PM]
 Ooooo... when I run all the `CPModuleTest` tests, it hangs (I'm assuming on that one) on Py3
Hmmm... now it's continuing. It just takes a long time on one. I'll have to run it again with `-v` to see which one is running really slow to be sure
Daniel Wozniak [12:23 PM]
 yes, that's the one
looks like it's always happening on the same test
test_get_file_templated_paths (integration.modules.test_cp.CPModuleTest)
Shane Lee [12:24 PM]
 yesh
Shane Lee [12:26 PM]
 Here's the stack trace that occurs just before salt continues. I don't know if it's related:
```
Exception ignored in: <bound method RemoteClient.__del__ of <salt.fileclient.RemoteClient object at 0x000001FFED9E9BA8>>
Traceback (most recent call last):
  File "c:\\dev\\salt\salt\fileclient.py", line 1026, in __del__
    self.destroy()
  File "c:\\dev\\salt\salt\fileclient.py", line 1033, in destroy
    self.channel.close()
  File "c:\\dev\\salt\salt\utils\asynchronous.py", line 57, in __getattribute__
    attr = getattr(self.asynchronous, key)
  File "c:\\dev\\salt\salt\utils\asynchronous.py", line 56, in __getattribute__
    raise ex
  File "c:\\dev\\salt\salt\utils\asynchronous.py", line 53, in __getattribute__
    return object.__getattribute__(self, key)
AttributeError: 'SyncWrapper' object has no attribute 'asynchronous'
```
Daniel Wozniak [12:27 PM]
 could be
Shane Lee [12:27 PM]
 I think it's probably related as it's the CP module
Which uses the fileclient object
The stacktrace is not thrown on Py2
Looks like Bo was poking around in there
https://github.com/saltstack/salt/pull/48705 (edited) 
Daniel Wozniak [12:34 PM]
 yeah maybe he missed something specific to windows
Shane Lee [12:34 PM]
 He just went from using `async` to `asynchronous`. Maybe that's something in `ioloop`
He just renamed it...
```
-    async = AsyncClass()
+    asynchronous = AsyncClass()
```
Daniel Wozniak [12:41 PM]
 async is a keyword in python >=3.6
Shane Lee [1:38 PM]
 Right, but the PR says it's to make the code compatible with 3.7...
But all he did is change the variable name... at least in the case of `asynchronous.py`
And he even changed the name... it was `async.py`
There's probably more to it than that... I just didn't look at all the files modified...

---

@Ch3LL commented on [Wed Jan 16 2019](https://github.com/saltstack/salt-jenkins/issues/1252#issuecomment-454789448)

thanks so are you looking into it @twangboy 

---

@twangboy commented on [Thu Jan 17 2019](https://github.com/saltstack/salt-jenkins/issues/1252#issuecomment-455404884)

That was the extent of me looking into it... I don't know what to do about it. Py3 is just really slow for some reason. twice as slow as Py2

---

@Ch3LL commented on [Tue Jan 22 2019](https://github.com/saltstack/salt-jenkins/issues/1252#issuecomment-456593666)

the tests pass when runtests is run outside of kitchen. We are going to skip these tests for fluorine so we can get test results and @twangboy will continue investigating.

---

@twangboy commented on [Tue Jan 22 2019](https://github.com/saltstack/salt-jenkins/issues/1252#issuecomment-456593684)

Until we can figure out what's going on ^^^

---

@Ch3LL commented on [Mon Jan 28 2019](https://github.com/saltstack/salt-jenkins/issues/1252#issuecomment-458190583)

i'm seeing this timeout again after a different spot

```
19:57:56          test_sync_all_blacklist (integration.modules.test_saltutil.SaltUtilSyncModuleTest)
20:42:56 Build timed out (after 45 minutes). Marking the build as aborted.
```

seems this is flaky behavior. Sometimes we get test results and sometimes its timing out. @twangboy 

As we are able to get test results this is not a release blocker, but should still be looked into, as it seems like its not just the test_cp tests that are the issue.

**Comment by twangboy** [comment]
We ended up skipping that test on Py3

https://github.com/saltstack/salt/pull/51286

**Comment by ribx** [comment]
I have the same error with 2019.2 from an ubuntu minion to a gentoo master, both running python 3.6

**Comment by Ch3LL** [comment]
@ribx can you open a separate issue with further details and detail wether the stack trace is impacting behavior.

**Comment by ribx** [comment]
I think the problem was that the master was still running 2.7 when the command line was already running in 3.6, but I am not sure. The problem disappeared after a restart of the master.
