### ISSUE TITLE
[fluorine] mac test_salt_contains_function test failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#51884]
@Ch3LL commented on [Wed Nov 28 2018](https://github.com/saltstack/salt-jenkins/issues/1219)

the test `integration.states.test_renderers.TestJinjaRenderer.test_salt_contains_function` is failing on mac sierra and highsierra. 

https://jenkinsci.saltstack.com/job/fluorine/job/salt-mac-sierra-py2/61/
https://jenkinsci.saltstack.com/job/fluorine/job/salt-mac-sierra-py2/61/

---

@dwoz commented on [Wed Dec 19 2018](https://github.com/saltstack/salt-jenkins/issues/1219#issuecomment-448673720)

I have not seen this fail in a while. I think it has been fixed.

---

@dwoz commented on [Tue Jan 08 2019](https://github.com/saltstack/salt-jenkins/issues/1219#issuecomment-452395705)

Looks like this is still failing:

https://jenkinsci.saltstack.com/job/2019.2/job/salt-mac-highsierra-py2/lastCompletedBuild/testReport/integration.states.test_renderers/TestJinjaRenderer/test_salt_contains_function/

---

@Ch3LL commented on [Tue Jan 15 2019](https://github.com/saltstack/salt-jenkins/issues/1219#issuecomment-454414419)

https://github.com/saltstack/salt/pull/51145

---

@Ch3LL commented on [Tue Jan 15 2019](https://github.com/saltstack/salt-jenkins/issues/1219#issuecomment-454415007)

i believe its still failing even with the PR above https://jenkinsci.saltstack.com/job/2019.2.0.rc1/job/salt-mac-sierra-py2/9/

---

@waynew commented on [Wed Jan 23 2019](https://github.com/saltstack/salt-jenkins/issues/1219#issuecomment-456904932)

I dug into this a little bit and I'm *pretty* sure it's happening due to the minion failing to start. If you run:

```
python runtests.py --interactive
```

then pop up a new terminal and run

```
salt -c /tmp/salt-tests-tmpdir/config/ minion state.sls jinja_dot_notation
```

It works and the result is True, as expected.

On the other hand, when I just run the test:

```
python runtests.py -n integration.states.test_renderers.TestJinjaRenderer.test_salt_contains_function; say done
```

I get this output:

```
Starting integration.states.test_renderers.TestJinjaRenderer.test_salt_contains_function Tests
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
objc[8622]: +[NSValue initialize] may have been in progress in another thread when fork() was called.
objc[8622]: +[NSValue initialize] may have been in progress in another thread when fork() was called. We cannot safely call it or ignore it in the fork() child process. Crashing instead. Set a breakpoint on objc_initializeAfterForkError to debug.
```

So it looks like something is getting borked *somewhere* - the test works when manually running it, just not on autopilot 🤷‍♂️ 

---

@waynew commented on [Wed Jan 23 2019](https://github.com/saltstack/salt-jenkins/issues/1219#issuecomment-456910898)

Oh, also, it's definitely something going on with the Mac libs, because I can run the same test within a Docker (ubuntu 18.04) container and it works A-OK

**Comment by KChandrashekhar** [comment]
This test last failed on Feb 7th, so need to make sure if its still failing on 2019.2 before this gets deemed a blocker or not. Assigning it to Gareth since he's working on getting the Mac test machines to run again.

**Comment by garethgreenaway** [comment]
Marking this as fixed since tests are running again since the move to kitchen-salt.
