### ISSUE TITLE
[fluorine] unit.utils.test_vmware tests failing on fedora py3

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#51886]
@Ch3LL commented on [Wed Dec 12 2018](https://github.com/saltstack/salt-jenkins/issues/1243)

a ton of test_vmware unit tests are failing on both fedora 28 and 29 py3

unit.utils.test_vmware.CreateDatacenterTestCase.test_create_datacenter_raise_no_permission
unit.utils.test_vmware.CreateDatacenterTestCase.test_create_datacenter_raise_vim_fault
unit.utils.test_vmware.CreateDatacenterTestCase.test_create_datacenter_runtime_fault
unit.modules.test_mandrill.MandrillModuleTest.test_send
unit.utils.test_vmware.GetLicenseManagerTestCase.test_raise_no_permission
unit.utils.test_vmware.GetLicenseManagerTestCase.test_raise_runtime_fault
unit.utils.test_vmware.GetLicenseManagerTestCase.test_raise_vim_fault
unit.utils.test_vmware.GetAssignedLicensesTestCase.test_instance_uuid_raises_no_permission
unit.utils.test_vmware.GetAssignedLicensesTestCase.test_instance_uuid_raises_runtime_fault
unit.utils.test_vmware.GetAssignedLicensesTestCase.test_instance_uuid_raises_vim_fault
unit.utils.test_vmware.GetAssignedLicensesTestCase.test_query_assigned_licenses_raises_no_permission
unit.utils.test_vmware.GetAssignedLicensesTestCase.test_query_assigned_licenses_raises_runtime_fault
unit.utils.test_vmware.GetAssignedLicensesTestCase.test_query_assigned_licenses_raises_vim_fault

is just a subset of the tests. but there are more here: 

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-fedora-28-py3/57/#showFailuresLink

https://jenkinsci.saltstack.com/job/fluorine/view/Python3/job/salt-fedora-29-py3/13/#showFailuresLink

i'm assuming they are all related.

---

@Ch3LL commented on [Wed Dec 12 2018](https://github.com/saltstack/salt-jenkins/issues/1243#issuecomment-446715986)

we are going to skip these tests for fluorine and come back to them after the release. Whoever is assinged herd please just add a skip for these failing tests on fedora and keep this issue open and we will come back to it when the release is done. 

---

@dwoz commented on [Mon Jan 07 2019](https://github.com/saltstack/salt-jenkins/issues/1243#issuecomment-452090506)

I think these were failing due to some work @dubb-b was doing on our vmware setup.

---

@Ch3LL commented on [Tue Jan 15 2019](https://github.com/saltstack/salt-jenkins/issues/1243#issuecomment-454413670)

these tests are still failing. they do not access our vmware cluster.

**Comment by waynew** [comment]
I'm seeing failures on:

- unit.utils.test_vmware.GetDvssTestCase.test_traversal_spec
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetContentTestCase.test_defined_container_ref
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_ssl_default_context_loaded
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_datastores_filtered_by_both_name_and_backing_disk
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_get_no_uplink_pg
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_mount_info_call
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_datastores_filtered_by_name
- unit.utils.test_vmware.AddLicenseTestCase.test_add_license_raises_vim_fault
- unit.utils.test_vmware.GetClusterTestCase.test_traversal_spec_init
- unit.utils.test_vmware.GetContentTestCase.test_create_container_view_raise_vim_fault
- unit.utils.test_vmware.GetStorageSystemTestCase.test_empty_mors_result
- unit.utils.test_vmware.GetStorageSystemTestCase.test_hostname_argument
- unit.utils.test_vmware.GetDvssTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetStorageSystemTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetContentTestCase.test_local_properties_set
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_ssl_default_context_not_loaded
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetContentTestCase.test_local_traversal_spec
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_get_mors_with_properties
- unit.utils.test_vmware.GetServiceInstanceFromManagedObjectTestCase.test_si_return_and_stub_assignment
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_get_new_stub_2_7_8_python
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_get_no_pgs
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_traversal_spec_datacenter_parent
- unit.utils.test_vmware.GetDatastoresTestCase.test_cluster_traversal_spec
- unit.utils.test_vmware.GetContentTestCase.test_create_container_view_raise_runtime_fault
- unit.utils.test_vmware.GetDatastoresTestCase.test_unsupported_reference_type
- unit.utils.test_vmware.GetContentTestCase.test_retrieve_contents_raise_runtime_fault
- unit.utils.test_vmware.GetServiceInstanceFromManagedObjectTestCase.test_service_instance_instantiation
- unit.utils.test_vmware.AddLicenseTestCase.test_add_license_arguments
- unit.utils.test_vmware.GetContentTestCase.test_create_container_view_raise_no_permission
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_get_new_stub
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_datastores_filtered_by_backing_disk
- unit.utils.test_vmware.GetContentTestCase.test_destroy_raise_runtime_fault
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_new_stub_returned
- unit.utils.test_vmware.GetDatastoresTestCase.test_backing_disks_no_mount_info
- unit.utils.test_vmware.GetContentTestCase.test_empty_container_ref
- unit.utils.test_vmware.GetStorageSystemTestCase.test_traversal_spec
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_get_all_pgs
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_filtered_pgs
- unit.utils.test_vmware.GetDatastoresTestCase.test_host_traversal_spec
- unit.utils.test_vmware.GetContentTestCase.test_external_traversal_spec
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_unsupported_parrent
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_reference_name_call
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_no_datastores
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_traversal_spec
- unit.utils.test_vmware.AddLicenseTestCase.test_no_license_manager_passed_in
- unit.utils.test_vmware.GetServiceInstanceFromManagedObjectTestCase.test_default_name_parameter
- unit.utils.test_vmware.GetContentTestCase.test_retrieve_contents_raise_no_permission
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_get_uplink_pg
- unit.utils.test_vmware.GetDatastoresTestCase.test_datacenter_traversal_spec
- unit.utils.test_vmware.GetDatastoresTestCase.test_root_folder_traversal_spec
- unit.utils.test_vmware.AddLicenseTestCase.test_label_settings
- unit.utils.test_vmware.GetDvssTestCase.test_get_no_dvss
- unit.utils.test_vmware.GetDvssTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.GetContentTestCase.test_retrieve_contents_raise_vim_fault
- unit.utils.test_vmware.GetServiceInstanceFromManagedObjectTestCase.test_name_parameter_passed_in
- unit.utils.test_vmware.GetContentTestCase.test_property_obj_filter_specs_and_contents
- unit.utils.test_vmware.GetStorageSystemTestCase.test_valid_mors_result
- unit.utils.test_vmware.GetStorageSystemTestCase.test_no_hostname_argument
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_traversal_spec
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_get_network_folder
- unit.utils.test_vmware.CreateDvsTestCase.test_no_dvs_create_spec
- unit.utils.test_vmware.AddLicenseTestCase.test_valid_license_added
- unit.utils.test_vmware.AddLicenseTestCase.test_add_license_raises_runtime_fault
- unit.utils.test_vmware.GetDvssTestCase.test_filtered_all_dvss
- unit.utils.test_vmware.GetContentTestCase.test_destroy_raise_no_permission
- unit.utils.test_vmware.GetClusterTestCase.test_get_mors_with_properties_call
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_all_datastores
- unit.utils.test_vmware.GetContentTestCase.test_destroy_raise_vim_fault
- unit.utils.test_vmware.GetDatastoresTestCase.test_get_storage_system_call
- unit.utils.test_vmware.GetUplinkDvportgroupTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.GetDvssTestCase.test_get_all_dvss
- unit.utils.test_vmware.AddLicenseTestCase.test_add_license_raises_no_permission
- unit.utils.test_vmware.GetNetworkFolderTestCase.test_get_no_network_folder
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_traversal_spec_dvs_parent
- unit.utils.test_vmware.GetDvportgroupsTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.AddLicenseTestCase.test_license_manager_passed_in
- unit.utils.test_vmware.GetNewServiceInstanceStub.test_session_cookie_in_context

They look like:

2019.2.1 failed [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/unit.utils.test_vmware/GetDatastoresTestCase/test_unsupported_reference_type), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/unit.utils.test_vmware/GetDatastoresTestCase/test_unsupported_reference_type)
develop failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/unit.utils.test_vmware/GetDatastoresTestCase/test_unsupported_reference_type)
---

No module named 'salt.utils.vmware.vmodl'; 'salt.utils.vmware' is not a package

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 4086, in setUp
    patcher.start()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1524, in start
    result = self.__enter__()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1377, in __enter__
    self.target = self.getter()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1547, in <lambda>
    getter = lambda: _importer(target)
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1234, in _importer
    thing = _dot_lookup(thing, comp, import_path)
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1223, in _dot_lookup
    __import__(import_path)
ModuleNotFoundError: No module named 'salt.utils.vmware.vmodl'; 'salt.utils.vmware' is not a package
		
```

**Comment by waynew** [comment]
Also seeing these:

2019.2.1 failed [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/unit.utils.test_vmware/PrivateGetServiceInstanceTestCase/test_userpass_mechanism_no_domain), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/unit.utils.test_vmware/PrivateGetServiceInstanceTestCase/test_userpass_mechanism_no_domain)
develop failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/unit.utils.test_vmware/PrivateGetServiceInstanceTestCase/test_userpass_mechanism_no_domain)
---

<module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'SmartConnect'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 1364, in setUp
    patcher.start()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1524, in start
    result = self.__enter__()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1393, in __enter__
    original, local = self.get_original()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1367, in get_original
    "{} does not have the attribute {!r}".format(target, name)
AttributeError: <module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'SmartConnect'
		
```

in

- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_third_attempt_successful_connection
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_sspi_empty_principal
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_second_attempt_unsuccsessful_connection_default_error
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_first_attempt_unsuccessful_connection_vim_fault
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_first_attempt_unsuccessful_connection_default_error
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_invalid_mechianism
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_third_attempt_unsuccessful_connection_detault_error
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_third_attempt_unsuccessful_connection_vim_fault
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_userpass_mechanism_empty_username
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_userpass_mech_domain_unused
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_sspi_get_token_error
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_second_attempt_successful_connection
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_userpass_mechanism_no_domain
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_second_attempt_unsuccsessful_connection_vim_fault
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_first_attempt_successful_connection
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_userpass_mechanism_empty_password
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_sspi_empty_domain
- unit.utils.test_vmware.PrivateGetServiceInstanceTestCase.test_sspi_get_token_success_

**Comment by waynew** [comment]
Also seeing

2019.2.1 failed [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/unit.utils.test_vmware/GetPropertiesOfManagedObjectTestCase/test_managed_object_no_name_property), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/unit.utils.test_vmware/GetPropertiesOfManagedObjectTestCase/test_managed_object_no_name_property)
develop failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/unit.utils.test_vmware/GetPropertiesOfManagedObjectTestCase/test_managed_object_no_name_property)
---

name 'vmodl' is not defined

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 981, in get_properties_of_managed_object
    local_properties=True)
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1091, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1146, in _mock_call
    raise result
pyVmomi.VmomiSupport.vmodl.query.InvalidProperty: (vmodl.query.InvalidProperty) {
   dynamicType = <unset>,
   dynamicProperty = (vmodl.DynamicProperty) [],
   msg = <unset>,
   faultCause = <unset>,
   faultMessage = (vmodl.LocalizableMessage) [],
   name = ''
}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 844, in test_managed_object_no_name_property
    self.fake_mo_ref, self.mock_props)
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 983, in get_properties_of_managed_object
    except vmodl.query.InvalidProperty:
NameError: name 'vmodl' is not defined
		
```

in

- unit.utils.test_vmware.GetClusterTestCase.test_get_managed_object_name_call
- unit.utils.test_vmware.GetClusterTestCase.test_get_mors_with_properties_returns_empty_array
- unit.utils.test_vmware.GetClusterTestCase.test_cluster_found
- unit.utils.test_vmware.GetPropertiesOfManagedObjectTestCase.test_managed_object_no_name_property
- unit.utils.test_vmware.GetClusterTestCase.test_get_service_instance_from_managed_object
- unit.utils.test_vmware.GetClusterTestCase.test_cluster_not_found

**Comment by waynew** [comment]
Also seeing

2019.2.1 failed [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/unit.utils.test_vmware/DisconnectTestCase/test_disconnect_raise_vim_fault), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/unit.utils.test_vmware/DisconnectTestCase/test_disconnect_raise_vim_fault)
develop failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/unit.utils.test_vmware/DisconnectTestCase/test_disconnect_raise_vim_fault)
---

<module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'Disconnect'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_vmware.py", line 2006, in test_disconnect_raise_vim_fault
    with patch('salt.utils.vmware.Disconnect', MagicMock(side_effect=exc)):
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1393, in __enter__
    original, local = self.get_original()
  File "/usr/local/lib/python3.7/site-packages/mock/mock.py", line 1367, in get_original
    "{} does not have the attribute {!r}".format(target, name)
AttributeError: <module 'salt.utils.vmware' from '/tmp/kitchen/testing/salt/utils/vmware.py'> does not have the attribute 'Disconnect'
		
```

in

- unit.utils.test_vmware.DisconnectTestCase.test_disconnect
- unit.utils.test_vmware.DisconnectTestCase.test_disconnect_raise_vim_fault
- unit.utils.test_vmware.DisconnectTestCase.test_disconnect_raise_runtime_fault
- unit.utils.test_vmware.DisconnectTestCase.test_disconnect_raise_no_permission

**Comment by Ch3LL** [comment]
this is now passing here:

https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-fedora-29-py3/38/

There was an issue with fedora conflicting between the urlib3 system and pip packages. When attempting to import urllib3 there was an importerror and said the module did not exist. When i uninstalled the system urllib3 package the test would pass. The test is passing now because of the transition to using nox which installs the dependencies with pip.
