### ISSUE TITLE
SSDs grain reports Device Mapper (LVM) devices as SSDs

### ISSUE THREAD

**Issue by wido** [saltstack/salt#51898]
### Setup
Linux hosts running Ceph OSDs deployed with ceph-volume which creates Logical Volumes on top of these SSDs.

<pre>salt 'srv-*03-07*' grains.item SSDs</pre>

This returns:

<pre>
    SSDs:
        - sda
        - sdb
        - sdc
        - sdd
        - sde
        - sdf
        - sdg
        - sdh
        - sdi
        - sdj
        - sdk
        - dm-0
        - dm-1
        - dm-2
        - dm-3
        - dm-4
        - dm-5
        - dm-6
        - dm-7
        - dm-8
        - dm-9
</pre>

I checked the code (commit 4cd0680b7f48790cc82a8074695ef8f04b99c74a) and I see that salt/grains/disks.py contains this:

<pre>
def _linux_disks():
    '''
    Return list of disk devices and work out if they are SSD or HDD.
    '''
    ret = {'disks': [], 'SSDs': []}

    for entry in glob.glob('/sys/block/*/queue/rotational'):
        try:
            with salt.utils.files.fopen(entry) as entry_fp:
                device = entry.split('/')[3]
                flag = entry_fp.read(1)
                if flag == '0':
                    ret['SSDs'].append(device)
                    log.trace('Device %s reports itself as an SSD', device)
                elif flag == '1':
                    ret['disks'].append(device)
                    log.trace('Device %s reports itself as an HDD', device)
                else:
                    log.trace(
                        'Unable to identify device %s as an SSD or HDD. It does '
                        'not report 0 or 1', device
                    )
        except IOError:
            pass
    return ret
</pre>

It only checks in */sys/block/X/queue/rotational* if this reports 1 or 0 and for a Device Mapper device it's 0, but this is a virtual device:

<pre>
[salt@ceph-salt (GN3) ~]$ salt 'XXXX' cmd.shell 'cat /sys/block/dm-9/queue/rotational'
srv-XXX03-07.XXXX:
    0
[salt@ceph-salt (GN3) ~]$
</pre>

There should probably be a better check at this point to check if these devices are real and not device mapper devices.

### Versions Report
<pre>
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
</pre>

**Comment by dwoz** [comment]
@wido Thanks for reporting the issue and the PR.

**Comment by wido** [comment]
This one is still valid. Leaving it here :)

**Comment by piterpunk** [comment]
@dwoz , this one also can be closed by the #57613 merge.

**Comment by piterpunk** [comment]
@sagetherage I guess this one did slip under the carpet and got forgotten, it issue was fixed by #57613 merge and can be closed.
