### ISSUE TITLE
Question: Regarding salt.modules.junos update in fluorine

### ISSUE THREAD

**Issue by rsmekala** [saltstack/salt#51897]
### Description of Issue/Question
Wanted to know the release junos-module related changes will be checked in. I don't seem them in latest 2019.2.0 docs.

Commit : https://github.com/saltstack/salt/pull/51164

We are looking forward for it to be released in fluorine itself.

**Comment by dwoz** [comment]
@rsmekala This was merged to develop after we branched and feature froze Fluorine. It won't get included until Neon. You can add it to you're 2019.2.0 install by copying the module source and using ext_mods.
