### ISSUE TITLE
[2019.2.0.rc1] opensuse is not bootstrapping

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#51890]
@Ch3LL commented on [Tue Feb 05 2019](https://github.com/saltstack/salt-jenkins/issues/1296)

opensuse is not bootstrapping with error:

```
01:21:58        ----------
01:21:58                  ID: man
01:21:58            Function: pkg.installed
01:21:58              Result: False
01:21:58             Comment: An error was encountered while installing package(s): Zypper command failure: Package 'python-MySQL-python' not found.
01:21:58             Started: 06:19:27.731070
01:21:58            Duration: 24883.627 ms
01:21:58             Changes:   
```

https://jenkinsci.saltstack.com/job/2019.2.0.rc1/view/Python3/job/salt-opensuse-py3/40/consoleFull

---

@Ch3LL commented on [Tue Feb 05 2019](https://github.com/saltstack/salt-jenkins/issues/1296#issuecomment-460717120)

this is also impacting 2018.3/2018.3.4 tests

---

@Ch3LL commented on [Wed Feb 27 2019](https://github.com/saltstack/salt-jenkins/issues/1296#issuecomment-468036110)

salt-opensuse-15-py3 is not currently bootstrapping:

https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-opensuse-15-py3/15/console

**Comment by dwoz** [comment]
These are failing on multiple branches:

```
Suite salt-opensuse-15-py2 failed on 2017.7, 2017.7.9, 2018.3, 2019.2, develop
Suite salt-opensuse-15-py3 failed on 2017.7, 2017.7.9, 2018.3, 2019.2, develop
Suite salt-opensuse-42-py2 failed on 2017.7, 2017.7.9, 2018.3, 2019.2
Suite salt-opensuse-42-py3 failed on 2017.7, 2017.7.9, 2018.3, 2019.2, develop
```

**Comment by Ch3LL** [comment]
both suse 42 and 15 are bootstrapping now. I just need to merge forward to all the other branches and verify

**Comment by Ch3LL** [comment]
one last OS is not bootstrap suse 15 py3. looking into it now

**Comment by Ch3LL** [comment]
fixed by https://github.com/saltstack/salt-jenkins/pull/1388

**Comment by Ch3LL** [comment]
yay! suse 15 py3 got to the test run :) https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-opensuse-15-py3/9/console
