### ISSUE TITLE
integration.shell.test_auth.AuthTest failures under py2 on fedora28

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#51927]
- [ ] https://jenkinsci.saltstack.com/job/2017.7/job/salt-fedora-28-py2/52/testReport/junit/integration.shell.test_auth/AuthTest/test_pam_auth_valid_user/
- [ ] https://jenkinsci.saltstack.com/job/2017.7/job/salt-fedora-28-py2/52/testReport/junit/integration.shell.test_auth/AuthTest/test_pam_auth_valid_group/

failures look like this:

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/shell/test_auth.py", line 146, in test_pam_auth_valid_group
    'minion:' in resp
AssertionError: False is not true
```

**Comment by Ch3LL** [comment]
i'm having a hard time replicating this one. I just started an entire test run to see if i can replicate.

**Comment by Ch3LL** [comment]
actually it looks like its not failing anymore? https://jenkinsci.saltstack.com/job/2017.7/job/salt-fedora-28-py2/53/

I'll go ahead and close this for now and we can re-open if it shows again.
