### ISSUE TITLE
Salt's reg.read_value function does not properly remove nulls from REG_SZ string types

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#51940]
### Description of Issue/Question
In some critical places, such as determining the current system's timezone at minion start, the `reg.read_value` is assumed to return a properly formatted string. This is actually not the case as in all versions of Windows as you can store '\0' bytes in a REG_SZ string due to REG_SZ not actually being a constraint that is linked to the value, but really just a type that is stored in a registry hive.

This results in some parts of salt which assume a string is being returned not acting correctly when being compared or used as a key to a dictionary.

As mentioned before, the current system's timezone is used at minion start which unfortunately results in a real weird issue on a system I installed a minion on where an exception is raised before the minion constructor actually completes execution which results in an invalid attribute being fetched every single interval (flooding the minion's log). The exception that is raised is due to being unable to determine the timezone as a result of the terminating null bytes, the timezone "Unknown" is returned. This is then searched in `mapper.get_unix` (in the win_timezone.get_zone function) which doesn't exist, thus raising the exception that demonstrates the following symptoms.

```
2019-03-02 05:54:03,575 [salt.minion      :1014][CRITICAL][548] Unexpected error while connecting to 172.33.33.160
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 997, in _connect_minion
    yield minion.connect_master(failed=failed)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1063, in run
    yielded = self.gen.throw(*exc_info)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1189, in connect_master
    yield self._post_master_init(master)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1055, in run
    value = future.result()
  File "c:\salt\bin\lib\site-packages\tornado\concurrent.py", line 238, in result
    raise_exc_info(self._exc_info)
  File "c:\salt\bin\lib\site-packages\tornado\gen.py", line 1069, in run
    yielded = self.gen.send(value)
  File "c:\salt\bin\lib\site-packages\salt\minion.py", line 1234, in _post_master_init
    cleanup=[master_event(type='alive')])
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 88, in __new__
    cls.instance.__singleton_init__(opts, functions, returners, intervals, cleanup, proxy, utils, standalone)
  File "c:\salt\bin\lib\site-packages\salt\utils\schedule.py", line 115, in __singleton_init__
    self.time_offset = self.functions.get('timezone.get_offset', lambda: '0000')()
  File "c:\salt\bin\lib\site-packages\salt\modules\win_timezone.py", line 237, in get_offset
    tz_object = pytz.timezone(get_zone())
  File "c:\salt\bin\lib\site-packages\pytz\__init__.py", line 178, in timezone
    raise UnknownTimeZoneError(zone)
UnknownTimeZoneError: 'Unknown'
2019-03-02 05:54:05,355 [salt.minion      :433 ][ERROR   ][548] Exception 'Schedule' object has no attribute 'loop_interval' occurred in scheduled job
... repeats every loop interval ...
```

### Setup
Make sure a registry key of REG_SZ is set with some null bytes at the end.

### Steps to Reproduce Issue
Use `reg.read_value` to read it. This is critical if any part of Salt is trusting that a well-formed string is stored in the registry.

```
salt --out=json $t reg.read_value hive=HKLM key='SYSTEM\CurrentCo ntrolSet\Control\TimeZoneInformation' vname=TimeZoneKeyName | jq
{
  "QbuyaXYq9Jl2wTuTZry3": {
    "vtype": "REG_SZ",
    "vname": "TimeZoneKeyName",
    "success": true,
    "hive": "HKLM",
    "vdata": "GMT Standard Time\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
    "key": "SYSTEM\\CurrentControlSet\\Control\\TimeZoneInformation"
  }
}
```

### Versions Report
```
Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:19:30) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 8
         system: Windows
        version: 8 6.2.9200 SP0 Multiprocessor Free
```

**Comment by arizvisa** [comment]
The response to this thread on stackoverflow points out the issue that led to this:


https://stackoverflow.com/questions/27716746/hklm-system-currentcontrolset-control-timezoneinformation-timezonekeyname-corrup

**Comment by arizvisa** [comment]
PR #51941 remedies this issue. As mentioned it's probably not safe to remove terminating null bytes from a registry value as doing this actually changes the meaning of the value, but there are numerous in salt that assumes that all terminating null bytes are removed and therefore fixing it in one place for all users is a lot easier than yelling at committers for not stripping off terminating null bytes.

**Comment by garethgreenaway** [comment]
@twangboy FYI

**Comment by arizvisa** [comment]
Closing this issue as it looks like the PR was merged.

**Comment by twangboy** [comment]
Hey, @arizvisa. I'm trying to replicate this Windows behavior of having null bytes in the registry key. The solution from a community member was to use `tzutil /g` instead of looking in the registry. But this is causing some other issues. (https://github.com/saltstack/salt/pull/51095). I would be interested to know what the display language is on the systems having this problem.

**Comment by arizvisa** [comment]
The display language is en-US, but it's windows 8.0. If you want, you can just write null bytes with the api call since the registry api allows it.

**Comment by arizvisa** [comment]
I think Windows 8.0 or less will probably have null bytes.
