### ISSUE TITLE
Errors in regex_match in Jinja2

### ISSUE THREAD

**Issue by wl2776** [saltstack/salt#51972]
### Description of Issue/Question
Got errors while tried to list nVidia GPU devices with Jinja2

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

SLS:
```
add_gpu_gres:
    file.managed:
        - name: /etc/slurm-llnl/gres.conf
        - source: salt://cluster/slurm-configs/gres.conf.template
        - user: {{ slurm_username }}
        - group: {{ slurm_username }}
        - template: jinja
        - onlyif: test -c /dev/nvidia0
```
gres.conf.template:
```
{% for device in "/dev" | list_files | regex_match(b'nvidia', ignorecase=False) %}
Name=gpu File=/dev/{{ device }}
{% endfor %}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

command
sudo salt <minion> state.apply <state> 

returns following errors:
```
----------
          ID: add_gpu_gres
    Function: file.managed
        Name: /etc/slurm-llnl/gres.conf
      Result: False
     Comment: Unable to manage file: Jinja syntax error: expected token ',', got 'string'; line 1

              ---
              {% for device in "/dev" | list_files | regex_match(b'nvidia', ignorecase=False) %}    <======================
              Name=gpu File=/dev/{{ device }}
              {% endfor %}

              ---
     Started: 16:44:43.105627
    Duration: 752.012 ms
     Changes:
```

If I remove `b` in call to `regex_match`, I get following error, related to different unicode defaults

```
----------
          ID: add_gpu_gres
    Function: file.managed
        Name: /etc/slurm-llnl/gres.conf
      Result: False
     Comment: Unable to manage file: Jinja error: expected string or bytes-like object
              Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/utils/templates.py", line 392, in render_jinja_tmpl
                  output = template.render(**decoded_context)
                File "/usr/lib/python3/dist-packages/jinja2/asyncsupport.py", line 76, in render
                  return original_render(self, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 1008, in render
                  return self.environment.handle_exception(exc_info, True)
                File "/usr/lib/python3/dist-packages/jinja2/environment.py", line 780, in handle_exception
                  reraise(exc_type, exc_value, tb)
                File "/usr/lib/python3/dist-packages/jinja2/_compat.py", line 37, in reraise
                  raise value.with_traceback(tb)
                File "<template>", line 1, in top-level template code
                File "/usr/lib/python3/dist-packages/salt/utils/jinja.py", line 404, in regex_match
                  obj = re.match(rgx, txt, flag)
                File "/usr/lib/python3.6/re.py", line 172, in match
                  return _compile(pattern, flags).match(string)
              TypeError: expected string or bytes-like object

              ; line 1

              ---
              {% for device in "/dev" | list_files | regex_match('nvidia', ignorecase=False) %}    <======================
              Name=gpu File=/dev/{{ device }}
              {% endfor %}


              Traceback (most recent call last):
              [...]
              ---
     Started: 16:48:52.902127
    Duration: 684.563 ms
     Changes:
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
~$ salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-142-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
Minion version

```
~$ salt-minion --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-45-generic
         system: Linux
        version: Ubuntu 18.04 bionic

```
Master runs on Ubuntu 16.04 with python 2
Minion runs on Ubuntu 18.04 with python 3

**Comment by Ch3LL** [comment]
this occurs because the data is a list and regex_match needs a string to match against.

you could do something along the lines of:

```
{%- for device in "/dev" | list_files -%}
  {%- if device | regex_match('nvidia', ignorecase=False) != None -%} 
Name=gpu File=/dev/{{ device }}
  {%- endif -%}
{%- endfor -%}
```

**Comment by wl2776** [comment]
This didn't work. Resulting file was empty.
Moreover, I see that documentation to these filters (at least regex_search and regex_match) is incomplete, nowhere is said about what it expects as input and what is its output

**Comment by Ch3LL** [comment]
I tested that sls file against the devices listed out in /dev on my machine. Can you add `{%- do salt.log.error(device) -%}` in that for loop so we make sure nvidia is in that list and what is being output there?

**Comment by wl2776** [comment]
I've tried following code:
```
{%- for device in "/dev" | list_files -%}
{%- do salt.log.error(device) -%}
  {%- if device | regex_match('nvidia', ignorecase=False) != None -%} 
Name=gpu File=/dev/{{ device }}
  {%- endif -%}
{%- endfor -%}
```

As a result, I've see lots of messages in /var/log/minion, listing all devices, `/dev/nvidia0`, `/dev/nvidia1`, etc are also listed
```
2019-03-13 09:57:17,963 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/char/4:52
2019-03-13 09:57:17,963 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/fd/52
2019-03-13 09:57:17,963 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/char/89:11
2019-03-13 09:57:17,963 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/input/by-path/pci-0000:00:14.0-usb-0:14:1.0-event-kbd
...
2019-03-13 09:57:17,966 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/fd/14
2019-03-13 09:57:17,966 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/char/89:4
2019-03-13 09:57:17,966 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/snd/controlC2
2019-03-13 09:57:17,966 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/tty40
2019-03-13 09:57:17,966 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/dri
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/char/89:9
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/snd/pcmC2D9p
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/dri/by-path/pci-0000:81:00.0-card
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/char/4:28
...
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/nvidia0
...
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/char/89:18
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/char/10:59
...
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/nvidia1
...
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/stdin
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/ecryptfs
...
2019-03-13 09:57:17,967 [salt.loaded.int.module.logmod:65  ][ERROR   ][46477] /dev/nvidia2
...
```

Have changed code to the following (added '/dev/' to regex):
```
{%- for device in "/dev" | list_files -%}
{%- do salt.log.error(device) -%}
  {%- if device | regex_match('/dev/nvidia', ignorecase=False) != None -%} 
Name=gpu File=/dev/{{ device }}
  {%- endif -%}
{%- endfor -%}
```
Resulting file:
```
$ cat /etc/slurm-llnl/gres.conf
Name=gpu File=/dev//dev/nvidia1Name=gpu File=/dev//dev/nvidia-uvmName=gpu File=/dev//dev/nvidiactlName=gpu File=/dev//dev/nvidia2Name=gpu File=/dev//dev/nvidia-uvm-toolsName=gpu File=/dev//dev/nvidia3Name=gpu File=/dev//dev/nvidia0
```
So,  `regex_match` currently seems to work very similar to `startswith`

**Comment by wl2776** [comment]
I have looked in the sources and have found that `regex_search` and `regex_match` are indentical

```
@jinja_filter('regex_search')
def regex_search(txt, rgx, ignorecase=False, multiline=False):
    '''
    Searches for a pattern in the text.

    .. code-block:: jinja

        {% set my_text = 'abcd' %}
        {{ my_text | regex_search('^(.*)BC(.*)$', ignorecase=True) }}

    will be rendered as:

    .. code-block:: text

        ('a', 'd')
    '''
    flag = 0
    if ignorecase:
        flag |= re.I
    if multiline:
        flag |= re.M
    obj = re.search(rgx, txt, flag)
    if not obj:
        return
    return obj.groups()


@jinja_filter('regex_match')
def regex_match(txt, rgx, ignorecase=False, multiline=False):
    '''
    Searches for a pattern in the text.

    .. code-block:: jinja

        {% set my_text = 'abcd' %}
        {{ my_text | regex_match('^(.*)BC(.*)$', ignorecase=True) }}

    will be rendered as:

    .. code-block:: text

        ('a', 'd')
    '''
    flag = 0
    if ignorecase:
        flag |= re.I
    if multiline:
        flag |= re.M
    obj = re.match(rgx, txt, flag)
    if not obj:
        return
    return obj.groups()
```

**Comment by Ch3LL** [comment]
There is a slight difference between `regex_search` and `regex_match` functions.

`regex_search` uses `re.search()` whereas `regex_match` users `re.match()`

If you look at the re docs for `re.match()`: https://docs.python.org/2/library/re.html#re.match

> If zero or more characters at the beginning of string match the regular expression pattern, return a corresponding MatchObject instance. Return None if the string does not match the pattern; note that this is different from a zero-length match.

>Note that even in MULTILINE mode, re.match() will only match at the beginning of the string and not at the beginning of each line.

And for `re.search()` https://docs.python.org/2/library/re.html#re.search

> Scan through string looking for the first location where the regular expression pattern produces a match, and return a corresponding MatchObject instance. Return None if no position in the string matches the pattern; note that this is different from finding a zero-length match at some point in the string.

as you can see particularly from `re.match()` its looking at the beginning of the string, so this is expected behavior. this is also documented in saltstacks docs here: https://docs.saltstack.com/en/latest/topics/jinja/index.html#regex-match

Sorry i didn't catch that from earlier. When i tested it I was using `/dev/<devicename>`

**Comment by wl2776** [comment]
It is not documented in saltstack docs. Documentation consists of a single sentence with some missing words.

> If zero or more characters at the beginning of string match this regular expression, 

... what happens in this case? 

> otherwise returns None.

That's obvious, example also shows it.

**Comment by Ch3LL** [comment]
We could probably add some more context for `regex_match` and possibly another example where its not returning None

> Docstring in regex_match is invalid, it is identical to one from regex_search.

i'm not sure i'm following how `regex_match` and `regex_search` are the same docstrings. Can you elaborate? Thanks in advance

**Comment by wl2776** [comment]
Please, see my [comment above](https://github.com/saltstack/salt/issues/51972#issuecomment-472844101).  I've pasted code of these functions, that I've copied from files on my system. 

Also, compare [this](https://github.com/saltstack/salt/blob/138c9321d43aa1aa3950df8509f3d47aa24fe244/salt/utils/jinja.py#L366) and [this](https://github.com/saltstack/salt/blob/138c9321d43aa1aa3950df8509f3d47aa24fe244/salt/utils/jinja.py#L393)

**Comment by Ch3LL** [comment]
ahh thank you for clearing that up. Yep we definitely need to update those code blocks. Thanks for the quick response!

Did you want to take a go at a PR for this?

**Comment by wl2776** [comment]
Could you describe how I can run those synthetic tests?

**Comment by Ch3LL** [comment]
I'm not sure i'm following synthetic tests? Did you want to know how to run our test runner?

It should not be required when updating the docs. If you want to make sure your changes to the docs are correctly update you can try to build the docs as documented here: https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#building-the-documentation

**Comment by wl2776** [comment]
You write in manuals: 
```
 {% set my_text = 'abcd' %}
 {{ my_text | regex_match('^(.*)BC(.*)$', ignorecase=True) }}
```
will be renderes as:
```
some output
```
How did you get this output? 
I wonder is there any easy way to render those Jinja templates, with just a couple of commands, without disturbing already functioning installation of salt master and minions.

I store my salt states in a git repo, and to test them, I have to create additional branch in that repo, push some code into it, then call `fileserver.update`, then try to call `state.show_sls`... Too messy.

**Comment by Ch3LL** [comment]
if you cant use your production system to test the jinja u could start up a docker container or use the getting started vagrant VMs here: https://docs.saltstack.com/en/getstarted/fundamentals/index.html

there is also kitchen-salt https://github.com/saltstack/kitchen-salt that people use to test their states that you can look into. 

but the way to do it is just to copy and paste into an sls file and run it to show the output. You can just run `salt-call --local state.show_sls <sls>` so you only need to use a minion and not master.

**Comment by wl2776** [comment]
Thank you for the recommendations.

And answer to your question about PR.
I'd like to, but not now. Changes are minor, but currently I have no time to make them.

**Comment by wl2776** [comment]
> but the way to do it is just to copy and paste into an sls file and run it to show the output. You can just run salt-call --local state.show_sls <sls> so you only need to use a minion and not master.

Adding command line switches `--file-root=$(pwd) --pillar-root=$(pwd)/samples/pillar` does the trick
