### ISSUE TITLE
salt.states.boto_ec2.snapshot_created() is not idempotent

### ISSUE THREAD

**Issue by odhekar** [saltstack/salt#51985]
https://github.com/saltstack/salt/blob/ae69e87df5598c9810507d921b7da29509fb3d05/salt/states/boto_ec2.py#L550

Repeat application of this state function fails because it does not check if AMI with given name already exists.

**Comment by Ch3LL** [comment]
thanks we will need to get this fixed up.

fyi @saltstack/team-boto
