### ISSUE TITLE
Messed up module documentation

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#52000]
https://docs.saltstack.com/en/2018.3/ref/modules/all/salt.modules.service.html

There are 6 modules (group, kernelpkg, pkg, service, shadow, user) duplicated at the top of the list, and half the service modules have been renamed (launchctl, smf, systemd, upstart) so the links don't work.

![screenshot](https://user-images.githubusercontent.com/675056/53879715-0d15ec00-4007-11e9-836c-0f151f8a8c88.png)

**Comment by twangboy** [comment]
@jacobhammons @newwebash ^^^

**Comment by newwebash** [comment]
I'm tagging @KChandrashekhar and @Ch3LL since they're more familiar with the open Salt docs and processes than I am.

**Comment by Ch3LL** [comment]
i can definitely fix up the services issue, but I'm not quit sure what you mean by "There are 6 modules (group, kernelpkg, pkg, service, shadow, user) duplicated at the top of the list," I think you are referencing the virtual models? That should stay as we are documenting which of these modules are virtual modules

**Comment by OrangeDog** [comment]
@Ch3LL I mean they're both listed on their own at the top of the list, and also in their correct alphabetical order. If it's deliberate that they're listed separately there should be some sort of divider, and possibly no duplicate in the rest of the list.

**Comment by Ch3LL** [comment]
![image](https://user-images.githubusercontent.com/6886822/54548443-50187d80-497e-11e9-8fdc-70f048867208.png)

I believe you are referring to these virtual modules? In my opinion there is a clear division here.

**Comment by OrangeDog** [comment]
@Ch3LL see my screenshot.
There is no division in the sidebar that appears on every page.

**Comment by sagetherage** [comment]
fixed with port to master -- will be released in sodium
