### ISSUE TITLE
excluded does not  work with includes 

### ISSUE THREAD

**Issue by adambarnett52** [saltstack/salt#52039]
### Description of Issue/Question
If i have an sls that excludes another sls that has an include in it it does not exclude it 
### Setup
For example: 

Test.sls
```
exclude:
  - automount
```
automount init.sls 
```
include:
  - automount.{{ grains['os_family']| lower }}
```

in the above example ```automount.{{ grains['os_family']| lower }}``` still gets run even ( when doing a salt highstate  when test.sls in the top file) though in test.sls the automount init.sls has been excluded 

### Versions Report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: 1.11.4
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  4 2017, 00:39:18)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by dwoz** [comment]
@adambarnett52 I am unable to reproduce this using the following test scenario (version 2017.7.4).

top.sls
```
base:
   '*':
     - testa
```

testa.sls
```
exclude:
  - testb
```

testb/init.sls
```
include:
  - testb.{{ grains['os_family']| lower }}
```

testb/debian.sls
```
platforms file:
  file.managed:
    - name: /home/dwoz/meh.yaml
    - contents: |
        platforms:
        - name: debian
```

Perhaps your automount state is getting included from another state?
