### ISSUE TITLE
Create pylint rule to warn about `__del__` usage

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52031]
### Description of Issue/Question

There are several places that we use `__del__` which is not ideal. We should be closing and doing explicit teardown of things (like network connections and file handles). We do not want to promote this behavior while we ween off `__del__` where it's being used today. Create a pylint rule that will cause the linter to fail and explicitly ignore this rule where it's used today.

**Comment by arizvisa** [comment]
Definitely +1 on this, as `__del__` is not actually guaranteed to get called in Python especially if there's a cycle. If re-factoring, it might be better to use contexts where possible. You can probably do a class decorator (if you're a fan of that) that adds `__enter__` and `__exit__` as in the following, or just explicitly add it to classes that implement `.__del__`

```
class whee_python_is_silly(object):
    ...
    def __enter__(self):
        return self
    def __exit__(self, exc_type, exc_value, exc_traceback):
        self.__del__()    
```

**Comment by cmcmarrow** [comment]
http://pylint.pycqa.org/en/stable/how_tos/custom_checkers.html
I found this to be a helpful article.

**Comment by cmcmarrow** [comment]
https://github.com/saltstack/salt-pylint/pull/39
