### ISSUE TITLE
integration.runners.test_fileserver.FileserverTest.test_dir_list

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#52102]
```
integration.runners.test_fileserver.FileserverTest.test_dir_list
--------------------------------------------------------------------------------
develop failed salt-centos-7-py2-m2crypto, salt-centos-7-py2-pycryptodomex, salt-centos-7-py3, salt-centos-7-py3-m2crypto, salt-centos-7-py3-pycryptodomex, salt-centos-7-py3-transport, salt-debian-8-py2, salt-debian-8-py3, salt-debian-9-py2, salt-debian-9-py3, salt-fedora-28-py2, salt-fedora-28-py3, salt-fedora-29-py2, salt-fedora-29-py3, salt-opensuse-42-py2, salt-ubuntu-1404-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2-m2crypto, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-tornado, salt-ubuntu-1604-py3, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1804-py2, salt-windows-2019-py2
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{u'retcode': 70} is not an instance of <type 'list'>
................................................................................

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\runners\test_fileserver.py", line 26, in test_dir_list
    self.assertIsInstance(ret['return'], list)
AssertionError: {u'retcode': 70} is not an instance of <type 'list'>
```

**Comment by waynew** [comment]
Still failing on develop:

develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_empty_dir_list)
---

{'retcode': 70} is not an instance of <class 'list'>

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\runners\test_fileserver.py", line 44, in test_empty_dir_list
    self.assertIsInstance(ret['return'], list)
AssertionError: {'retcode': 70} is not an instance of <class 'list'>
		
```
