### ISSUE TITLE
TCPPubServerChannel._publish_daemon exit with error "Cannot share PollIOLoops across processes"

### ISSUE THREAD

**Issue by Mark3K** [saltstack/salt#52109]
### Description of Issue/Question
with python2.7 and tornado > 5.0.0 the `PollIOLoop` is not allowed share across processes

but the code in https://github.com/saltstack/salt/blob/develop/salt/transport/tcp.py#L1434 
```python
# Check if io_loop was set outside
if self.io_loop is None:
    self.io_loop = tornado.ioloop.IOLoop.current()
```
is try to grab the current `IOLoop` which is create by master main process, so it will raise the error "Cannot share PollIOLoops across processes"

clear the parent's instance before that seems work well
```python
# Check if io_loop was set outside
if self.io_loop is None:
    tornado.ioloop.IOLoop.clear_instance()
    self.io_loop = tornado.ioloop.IOLoop.current()
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Ch3LL** [comment]
ping @DmitryKuzmenko i know you have done a lot of work around tornado 5.0. Can you take a look here?

**Comment by DmitryKuzmenko** [comment]
@Ch3LL thank you for pointing me to this question.

@Mark3K About usage of TCPPubServerChannel: it is only used by Master. Master performs it's initialization and forking workers before instantiate and start the IOLoop. So it's OK for now.
What about the design of that part of code: following Tornado 5.0 guideline I'm cutting the `io_loop` argument from everywhere, all the code will use the `current()` one. Also it's a deprecated practice to fork after IOLoop is started and I'm working on dropping such things from Salt.

**Comment by Mark3K** [comment]
@DmitryKuzmenko after digging some code, I found the Master called the `tornado.ioloop.IOLoop.current()` in the [GitFS.__new__](https://github.com/saltstack/salt/blob/develop/salt/utils/gitfs.py#L2698) when [Master._pre_flight](https://github.com/saltstack/salt/blob/develop/salt/master.py#L590) is called

so when you use gitfs with tcp transport together the the publish daemon process will terminated with this error. 

by the way, you did not cache the error and log it:
```python
# run forever
        try:
            self.io_loop.start()
        except (KeyboardInterrupt, SystemExit):
            salt.log.setup.shutdown_multiprocessing_logging()
```
so user can't instantly found the reason why publish daemon process exit

**Comment by DmitryKuzmenko** [comment]
Interesting. Thank you for the analysis @Mark3K .
I don't have correct solution for this now. Let me think about it some time.
