### ISSUE TITLE
module.acme does not support DigitalOcean DNS-01 verification plugin

### ISSUE THREAD

**Issue by salty-vagrant** [saltstack/salt#52114]
### Description of Issue/Question

`module.acme` supports only `cloudflare` `dns_plugin`. DigitalOcean plugin for `certbot` is available and could be supported in `module.acme` with a trivial change.

### Setup
Default installation

### Steps to Reproduce Issue
Attemp to use `digitalocean` as `dns_plugin` to `module.acme`

### Versions Report
2019.2

**Comment by salty-vagrant** [comment]
This is a trivial change. I've made the changes and have raised this issue to associate with a Pull Request.

**Comment by Ch3LL** [comment]
thanks for the PR!  I'll go ahead and close here now since its merged :) thanks!
