### ISSUE TITLE
host.present always returns None when in test=True

### ISSUE THREAD

**Issue by lordcirth** [saltstack/salt#52116]
### Description of Issue/Question
host.present returns True when clean, but when test=True is set, it always returns None, implying changes.

See also other host.present issues:
#49889
#29592

### Steps to Reproduce Issue
```
hosts:
  host.present:
    - ip: 192.168.1.100
    - names:
      - foo.bar
    - clean: True
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-137-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
i was able to replicate this and I bisected it to this commit: 30f1b85c098eece23cec3ace8f329f3718a59c35  which is from this PR: https://github.com/saltstack/salt/pull/50657

thanks we will need to fix this up

**Comment by waynew** [comment]
I've got a PR in for this. @lordcirth if you can test it out that would be 💯 ✨ 

No problem if not, though 🙂
