### ISSUE TITLE
GCE doesn't have support for Labels

### ISSUE THREAD

**Issue by tehsu** [saltstack/salt#52118]
### Description of Issue/Question
When deploying a server, Labels is set to None, I tried to use metadata and it sets it as metadata, I was able to fix it by adding support to gce.py.

### Setup
cloud profile

cent-7-test:
  image: centos
  size: n1-standard-1
  location: 
  network: 
  subnetwork: 
  use_persistent_disk: True
  delete_boot_pd: False
  deploy: True
  make_master: False
  provider: 
  ssh_interface: private_ips
  ssh_username: 
  ssh_keyfile:
  external_ip: "None"
  labels: '{"environment": "test"}'

### Steps to Reproduce Issue
Set labels as above and nothing is set on the server

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.3.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by Ch3LL** [comment]
thanks for the PR! Since the PR fixes this i will go ahead close here and continue conversation in PR. thanks again!
