### ISSUE TITLE
[RFE] salt-key to provide duplicated fingerprints finding

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#52111]
### Description of Issue/Question
Adding extra salt-key argument  to list out duplicated fingerprints from minions.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
following shell script can list out  one fingerprint is used by two minions.

salt-key -F |sort -k2,2 |  awk -F':  ' '{print $2}' | uniq --count |egrep -v '1 '
```
[me@salt01 salt]$ sudo salt-key -F |sort -k2,2 |  awk -F':  ' '{print $2}' | uniq --count |egrep -v '1 '
      2 1b:d6:me71:2f:42:82:b2:70:9e:c8:30:42:21:ff:91:7a:b5:54:46:ed:86:e5:48:19:fc:df:53:a5:13:c3:f1:df
      4
[me@salt01 salt]$

```
Hope this can be translated info python code and as an option like "salt-key --duplicate"

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

2019.2.0

**Comment by Ch3LL** [comment]
possible duplicate of https://github.com/saltstack/salt/issues/46045?
