### ISSUE TITLE
Warnings: 'clean' is an invalid keyword argument for 'host.present'. 

### ISSUE THREAD

**Issue by EpsilonAlpha** [saltstack/salt#52123]
### Description of Issue/Question
I switched from host.only States to host.present States with the "Clean:True" like described [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.host.html#salt.states.host.present)

Because i had the previous issue that from Hosts with Dynamic IP's, if the IP changes then Salt creates an additional host entry for each time, but (for obvious reasons) there should be the current IP listed with the Host File.

Switching to host.present was easy: switching out 'name' to 'ip' and 'hostnames' to 'name' (with multiple states for each hostname ofc) and after applying the state i got this:

```
ID: heimnetzwerk
    Function: host.present
      Result: True
     Comment: Host heimnetzwerk (xxx.xxx.xxx.xxx) already present
     Started: 01:45:26.113380
    Duration: 0.968 ms
     Changes:
    Warnings: 'clean' is an invalid keyword argument for 'host.present'. If you
              were trying to pass additional data to be used in a template
              context, please populate 'context' with 'key: value' pairs. Your
              approach will work until Salt Fluorine is out. Please update your
              state files.
```
The IP Adress is obviously altered from me but the Warning doesn't make sense, since it's describes on the Docs-Page to use it like that:

```
salt.states.host.present(name, ip, clean=False)
Ensures that the named host is present with the given ip

name
The host to assign an ip to
ip
The ip addr(s) to apply to the host. Can be a single IP or a list of IP addresses.
clean
: False
Remove any entries which don't match those configured in the ip option.

New in version 2018.3.4.
```

So i'm clueless why it appears when i did how the Docs told me, it appears also on 3 minions. So it should be no problem with the individual machine.

### Setup
The Message above will be produced by this:

salt/hosts/cloud.sls:
```
heimnetzwerk:
  host.present:
   - ip: {{ homeip }}
   - name: heimnetzwerk
   - clean: True
```

the According Pillar calls the dig command and gives back the correct IP of my Home Network

### Steps to Reproduce Issue
I tried to run the state alone and highstate, always the same result

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-45-lowlatency
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by s-sebastian** [comment]
This option was introduced in `2018.3.4`. Check the version on your minions:
```
# salt --out txt '*' grains.get saltversion
test01: 2019.2.0
```

**Comment by EpsilonAlpha** [comment]
Good Point!

```
salt --out txt '*' grains.get saltversion
cloudserver2: 2019.2.0
twitchrecorder: 2018.3.3
schnittstelle: 2017.7.4
server1: 2017.7.4
```

OMG you are absolutely right @s-sebastian . 

Tbh i was expecting that the Minion-Packages will be updated since i call from time to time pkg.upgrade.

The interesting part here is that: 'schnittstelle' and 'server1' are brand new! Both have been created not a month ago!

**Comment by EpsilonAlpha** [comment]
Is there an elegant way to upgrade them all?

The Package Upgrade for the Salt-Minion must be hold back, either 
- not to auto-install a new version which can result in difficulties
or
- the Minion can't upgrade the packages when he needs an update by himself.

**Comment by EpsilonAlpha** [comment]
Okay, i got into action and did the update on 'twitchrecorder' manually where the apt-get told me basically 'nothing to upgrade'

Then i was wondering: Do all minions get the latest salt-minion from their repository?

So i installed _apt-show-versions_ on all Minions and called:

`salt '*' cmd.run 'apt-show-versions salt-minion'`

and the result proven that my guess was right:

```
cloudserver2:
    salt-minion:all/bionic 2019.2.0+ds-1 uptodate
twitchrecorder:
    salt-minion:all 2018.3.3+ds-1 newer than version in archive
schnittstelle:
    salt-minion:all/bionic 2017.7.4+dfsg1-1 uptodate
server1:
    salt-minion:all/bionic 2017.7.4+dfsg1-1 uptodate
```

They get different versions!

**Comment by EpsilonAlpha** [comment]
Well, after some additions to the sources of the minion i finally have 'twitchrecorder' on the latest version but 'server1' and 'schnittstelle' still don't get the lastest minion-version from the repo:

```
salt '*' cmd.run 'apt-show-versions salt-minion'        

cloudserver2:
    salt-minion:all/bionic 2019.2.0+ds-1 uptodate
twitchrecorder:
    salt-minion:all/bionic 2019.2.0+ds-1 uptodate
schnittstelle:
    salt-minion:all/bionic 2017.7.4+dfsg1-1 uptodate
server1:
    salt-minion:all/bionic 2017.7.4+dfsg1-1 uptodate
```

**Comment by EpsilonAlpha** [comment]
Okay, i figured out:

```
salt '*' cmd.run 'apt-cache policy | grep salt'
cloudserver2:
     500 https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic/main amd64 Packages
         release o=SaltStack,n=bionic,l=salt_ubuntu1804,c=main,b=amd64
         origin repo.saltstack.com
twitchrecorder:
     500 https://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic/main amd64 Packages
         release o=SaltStack,n=bionic,l=salt_ubuntu1804,c=main,b=amd64
         origin repo.saltstack.com
schnittstelle:
server1:
```
'server1' and 'schnittstelle' don't have any salt repo, however that is possible

**Comment by EpsilonAlpha** [comment]
'schnittstelle' is cooperating in the meantime, but when i update 'server1' via 

`sudo apt-get update`

i get this 
```
Hit:1 http://mirror.hetzner.de/ubuntu/packages bionic InRelease
Hit:2 http://mirror.hetzner.de/ubuntu/packages bionic-updates InRelease
Hit:3 http://mirror.hetzner.de/ubuntu/packages bionic-backports InRelease
Hit:4 http://mirror.hetzner.de/ubuntu/packages bionic-security InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic InRelease
Get:6 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
Hit:7 http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic InRelease
Get:8 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
Get:9 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
Fetched 252 kB in 1s (222 kB/s)
Reading package lists... Done
**N: Skipping acquire of configured file 'main/binary-i386/Packages' as repository 'http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic InRelease' doesn't support architecture 'i386'**
```

well would be true, IF the machine would be non-64 bit but it is 64bit:

```
uname -m
x86_64
```

**Comment by EpsilonAlpha** [comment]
Okay seems like i had some i386 on this minion..

i did [this](https://superuser.com/a/714392) and the update gone through after basically reinstall the salt-minion, re accept the minion key i FINALLY got this:
```

salt '*' cmd.run 'apt-show-versions salt-minion'
cloudserver2:
    salt-minion:all/bionic 2019.2.0+ds-1 uptodate
twitchrecorder:
    salt-minion:all/bionic 2019.2.0+ds-1 uptodate
server1:
    salt-minion:all/bionic 2019.2.0+ds-1 uptodate
schnittstelle:
    salt-minion:all/bionic 2019.2.0+ds-1 uptodate
```

**Comment by EpsilonAlpha** [comment]
Everything progressed now well on the next highstate run.

Thanks @s-sebastian
