### ISSUE TITLE
archive.extract "clean: True" cannot delete top level files

### ISSUE THREAD

**Issue by angeloudy** [saltstack/salt#52127]
### Description of Issue/Question
When apply archive.extract state, if `clean` is set to `True`, only files paths that belong to the zip file will be deleted. 

For example, A zip file contains the following
```
test1.txt
test2.txt
testdir
testdir/test.txt
```
When applying `archive.extract`, everything in the list above will be deleted before the archive is extracted. However, if I add another file to the target directory `test3.txt`, it will never be deleted.

It's the same when you update your archive, say `test2.txt` is no longer part of the archive, `test2.txt`  will never get deleted in the target directory.

This has caused some drama for us because we use archive.extract to deploy a lot of applications.

**Comment by angeloudy** [comment]
This could be resolved by always having a top level directory. But the problem with that is you may have to rename the director after extraction, which make the checksum useless.

**Comment by Ch3LL** [comment]
glancing at the code it looks like this is done on purpose. we could possibly add a new argument that deletes the files in the directory it extracts the archive too

**Comment by angeloudy** [comment]
@Ch3LL
That would be great.
I would suggest adding a new argument `toplevel_dir` and add it as prefix to all paths in `archive.list`. If `toplevel_dir` is set, then ignore `enforce_toplevel`.

**Comment by Oloremo** [comment]
I think that is what you want: https://github.com/saltstack/salt/pull/55418

**Comment by Ch3LL** [comment]
ping @angeloudy can you verify the fix in #55418 looks like its ready to be closed.

**Comment by angeloudy** [comment]
@Ch3LL  verified. Thanks for adding the new feature.
