### ISSUE TITLE
Import from custom _utils

### ISSUE THREAD

**Issue by kiemlicz** [saltstack/salt#52136]
### Description of Issue/Question
Is it possible to import custom utilities via python imports?
The doc https://docs.saltstack.com/en/latest/topics/utils/index.html suggests so but I couldn't get it working.

### Setup
Follow `Foo` class example from:  
https://docs.saltstack.com/en/latest/topics/utils/index.html

### Steps to Reproduce Issue
In any custom execution module, e.g.,: `_modules/customModule.py` it is not possible to write:
`import mymodule` (given I've named the `Foo` class file `mymodule.py`)  
It always fails with `No module named 'mymodule'`
Of course `__utils__['mymodule.foo']()` syntax works, the question is about import

Could you please clarify if the doc is wrong?

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: 1.10.6
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.4
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.0-7-amd64
         system: Linux
        version: debian 9.8
```

**Comment by Ch3LL** [comment]
i thought you had to use `__utils__` because thats how we pack it in  when we load `minion_mods`, but maybe someone on the @saltstack/team-core can correct me? Looks like that doc example makes it seem like you can import utils, but i thought we always wanted to use `__utils__`?

**Comment by UtahDave** [comment]
@Ch3LL There are a lot of place where we're importing from Salt utils.

```
[boucha@flaco salt (develop u=)]$ grep -rn 'import salt.utils' * | wc -l
2711
```

I'm running into this problem when I'm trying to use an execution module from develop in 2019.2. The execution module needs a utils module. I put the execution module in `_modules` and the utils module in `_utils` and run `saltutil.sync_all`.  Everything syncs fine, but it's not possible to import  the utils function.

Should we go through and replace all `2711` instances where we're importing directly from salt.utils and use `__utils__`?

**Comment by UtahDave** [comment]
looks like @max-arnold has a fix in #53167

**Comment by waynew** [comment]
@kiemlicz does the fix in #53167 work for you?

**Comment by kiemlicz** [comment]
I think yes!
I'm waiting for merge then

**Comment by kiemlicz** [comment]
not yet stale

**Comment by kiemlicz** [comment]
not yet

**Comment by sagetherage** [comment]
will be released in sodium - closing
