### ISSUE TITLE
Documentation improvement for salt.states.pkgrepo

### ISSUE THREAD

**Issue by wolfpackmars2** [saltstack/salt#52131]
### Description of Issue/Question
Documentation link: [https://docs.saltstack.com/en/2019.2/ref/states/all/salt.states.pkgrepo.html#module-salt.states.pkgrepo](https://docs.saltstack.com/en/2019.2/ref/states/all/salt.states.pkgrepo.html#module-salt.states.pkgrepo)
Ubuntu 18.04 doesn't have a package called "python-software-properties" as described in a Note recommending installation of the package. It seems that the python-software-properties package was renamed to software-properties-common in Ubuntu 12.10 and later. Also, there are two packages available: software-properties-common for Python3 and python-properties-common for Python 2.7.

As of version 2019.2, it appears Salt is still using Python 2.7. In light of this, it might be best to install packages for both versions of Python.  It might also be helpful to know if this note is still relevant. What does installing these packages improve?

The documentation can be expanded to provide more details for the users.

Additional details here: [https://askubuntu.com/a/422976](https://askubuntu.com/a/422976)

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-46-generic
         system: Linux
        version: Ubuntu 18.04 bionic
 
root@testmaster:/srv/salt# salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-46-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by Ch3LL** [comment]
looks like we just need to update the name of the package. nice find.

https://github.com/saltstack/salt/pull/8330 is the original PR that added the warning. It looks like it uses a python module from that package and is able to do better detection in the code by using this module directly.

**Comment by wolfpackmars2** [comment]
Looks like "python-properties-common" package isn't available for Ubuntu 18.04. I'll continue digging on this in the next few days.
