### ISSUE TITLE
[RFE] salt-run  manage.down_NODNS removekeys=True

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#52135]
### Description of Issue/Question

Hoping manage.down_nodns can  check if disconnected minion is DNS resolvable via forward/backward DNS lookup.

### Setup

NA
### Steps to Reproduce Issue

Current " manage.down removekeys=True" will remove minion in maintenance mode. minions could be down for many days. 

### Versions Report

2019.2.0

**Comment by Ch3LL** [comment]
I believe by RFE you are referring to a request for enhancement. we actually just setup a salt-enhancement-proposal repo right there: https://github.com/saltstack/salt-enhancement-proposals 

The README should describe how to submit an enhancement proposal in that repo.

**Comment by tjyang** [comment]
Thanks, I will open RFE there.

**Comment by gtmanfred** [comment]
all of what is being requested could be done with jinja in an orchestration state now.

you would do a module run to see what minions aren't responding, using the saltutil.runner module to run the manage.down state, or you could probably just target all minions using saltutil.cmd, and run test.ping and only move forward with minions that return false.

Then you would use the dnsutil module to lookup and see if the a record was defined, and if it isn't make a orchestrate salt.wheel state that deletes the key.

`salt://delminions.sls`
```
delete key for {{minionid}}:
  salt.wheel:
    - name: key.delete_dict
    - match:
        minions:
{%- for minionid, result in salt.saltutil.cmd(tgt='*', fun='test.ping').items() %}
  {%- if result == false %}
    {%- if not salt.dnsutil.A(minionid) %}
        - {{minionid}}
    {%- endif %}
  {%- endif %}
{%- endfor %}
```

and then run that state from the master with `salt-run state.orch delminions`
