### ISSUE TITLE
Add tests for module.acme

### ISSUE THREAD

**Issue by salty-vagrant** [saltstack/salt#52132]
### Description of Issue/Question

Add tests to `module.acme`

### Setup

Standard

### Steps to Reproduce Issue

Addition of tests (absence noted in PR #52115).

### Versions Report

2019.2

**Comment by Ch3LL** [comment]
thanks for opening this for tracking purposes :) will be great to get these tests in

**Comment by schorsch3000** [comment]
How is this issue closed if nothing was done and the issue clearly did not resolve itself?
