### ISSUE TITLE
boto_rds.replica_present not working global name 'backup_retention_period' is not defined

### ISSUE THREAD

**Issue by Sanpegi** [saltstack/salt#52159]
### Description of Issue/Question
Unable to create rds read replica. Giving below error
NameError: global name 'backup_retention_period' is not defined

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Below is the sls content

create_rds_replica:
  boto_rds.replica_present:
    - name: cstestrep
    - source: cstest

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
After executing the salt state file on the instances having aws access on role attached.

[root@ip-hostname salt]# salt '*' state.sls createreplicae -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'ip-hostname.ec2.internal_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/0e/438dc0853e7cf4083604bd866a5999a96ed3d5f392822525c38a73968f8c9d/.minions.p
[DEBUG   ] get_iter_returns for jid 20190313083736497556 sent to set(['hostname']) will timeout at 08:37:41.508856
[DEBUG   ] jid 20190313083736497556 return from hostname
[DEBUG   ] return event: {u'hostname': {u'jid': u'20190313083736497556', u'retcode': 2, u'ret': {u'boto_rds_|-create_rds_replica_|-cstestrep_|-replica_present': {u'comment': u'An exception occurred in this state: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call\n    **cdata[\'kwargs\'])\n  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper\n    return f(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/states/boto_rds.py", line 399, in replica_present\n    keyid, profile)\n  File "/usr/lib/python2.7/site-packages/salt/modules/boto_rds.py", line 337, in create_read_replica\n    if not backup_retention_period:\nNameError: global name \'backup_retention_period\' is not defined\n', u'name': u'cstestrep', u'start_time': u'08:37:36.732212', u'result': False, u'duration': 171.893, u'__run_num__': 0, u'__sls__': u'createreplicae', u'changes': {}, u'__id__': u'create_rds_replica'}}, u'out': u'highstate'}}
[DEBUG   ] LazyLoaded highstate.output
hostname:
----------
          ID: create_rds_replica
    Function: boto_rds.replica_present
        Name: cstestrep
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1919, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1918, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/boto_rds.py", line 399, in replica_present
                  keyid, profile)
                File "/usr/lib/python2.7/site-packages/salt/modules/boto_rds.py", line 337, in create_read_replica
                  if not backup_retention_period:
              NameError: global name 'backup_retention_period' is not defined
     Started: 08:37:36.732212
    Duration: 171.893 ms
     Changes:

Summary for hostname
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time: 171.893 ms
[DEBUG   ] jid 20190313083736497556 found all minions set([u'hostname'])
ERROR: Minions returned with non-zero exit code

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (default, Jul 26 2018, 19:59:38)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.101-91.76.amzn2.x86_64
         system: Linux
        version: Not Installed

**Comment by Ch3LL** [comment]
looks like this was added here: https://github.com/saltstack/salt/pull/34123/files#diff-59e36191d3e2ecda4e684feddb25b2d0R305

we added `backup_retention_period` but its not added into the function arguments. 

ping @rterbush looks like you added this, can you take a look here?

or if someone from @saltstack/team-boto wants to pick this one up.

**Comment by Sanpegi** [comment]
@rterbush and @saltstack/team-boto
Please help us on this issue.
This has become a show stopper for us in our deployment.

**Comment by Ch3LL** [comment]
@Sanpegi want to give the fix in #52223 a try?

Also thanks @s-sebastian !

**Comment by odhekar** [comment]
This fix is failing silently for me,
```
secure_minion:
----------
          ID: create_rds
    Function: boto_rds.replica_present
        Name: target-rds
      Result: True
     Comment: RDS replica target-rds created.
     Started: 21:31:51.829113
    Duration: 61374.955 ms
     Changes:
              ----------
              new:
                  ----------
                  instance:
              old:
                  ----------
                  instance:
                      None

Summary for secure_minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  61.375 s
```
sls file is simple,
```
create_rds:
  boto_rds.replica_present:
    - name: target-rds
    - source: cstest
```

**Comment by s-sebastian** [comment]
The changes from my PR were to fix this specific error that was related to `boto_rds.create_read_replica` execution module but looking at `boto_rds.replica_present` state module some further changes are required so I'll look into that.

**Comment by s-sebastian** [comment]
@odhekar please check 1d3363a

**Comment by odhekar** [comment]
I am not able to checkout your commits.

**Comment by s-sebastian** [comment]
This looks like you're running with `test=True`?

You can try this command to check this option:

```
# salt secure_minion config.option test
```

**Comment by odhekar** [comment]
Nope.
```
[root@salt-master salt]# salt secure_minion config.option test
secure_minion:
    False
```

**Comment by s-sebastian** [comment]
What's the purpose for `- debug`? It seems to be the culprit.

**Comment by odhekar** [comment]
you're right 🤦‍♂️ that was supposed to be -l debug. I am now getting what looks like a permission error. Looking into this.

**Comment by odhekar** [comment]
It worked!
