### ISSUE TITLE
Error in x509.private_key_managed example?

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#52166]
Not sure, but shouldn't `ca.key` be `www.key` here?
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.x509.html#salt.states.x509.private_key_managed
```
/etc/pki/www.key:
  x509.private_key_managed:
    - bits: 4096
    - new: True
    {% if salt['file.file_exists']('/etc/pki/ca.key') -%}
    - prereq:
      - x509: /etc/pki/www.crt
    {%- endif %}
```

**Comment by Ch3LL** [comment]
yeah that makes more sense to me. Want to push a change for that? should be easy

**Comment by Akm0d** [comment]
Fixed in the PR mentioned above
