### ISSUE TITLE
Minions re-authing continuously | Running Salt at Scale

### ISSUE THREAD

**Issue by ritishverma** [saltstack/salt#52179]
Hey Salt experts,

We are running a salt setup where we have 35k+ minions connected to a single master.
(I know that's a huge number!) We have seen that our minions are continuously reauthing to the master which makes the master heavily loaded.

For eg : On an average in 24 hours we saw approx 1194880 reauths.
That means a minion is reauthing atleast once an hour if we are running a 40k minion connected to a single master setup.

We are still running on Salt 2016.11.3 version and we are playing around with these config values to fix this issue and reduce the no of reauths considerably - 
`auth_timeout: 120
recon_default: 1000
recon_max: 59000`

I am following the resolutions mentioned in the following old issues - https://github.com/saltstack/salt/issues/11781
Is it related to how zeromq reconnects to the socket every 1000ms?

Is anyone running salt at such a scale and have experienced similar issues? How did you get around it?

Thanks!

**Comment by markuskramerIgitt** [comment]
We run ~25k minions on a single 2018.8.3 master, we see reauthing but a very moderate CPU load.

How did you count the reauth events?
I would like to verify that number on our installation.

**Comment by Ch3LL** [comment]
Might want to also look at these docs: https://docs.saltstack.com/en/latest/topics/tutorials/intro_scale.html

as that is detailing your problem it seems and has some solutions
