### ISSUE TITLE
Wrong versioned files in release 2018.3.4

### ISSUE THREAD

**Issue by quodt** [saltstack/salt#52177]
### Description of Issue/Question

The rpm package of the release `2018.3.4` contains files of different version. For example the file `/usr/lib/python2.7/site-packages/salt/modules/boto_route53.py` packaged into this release does not corespond with the counterpart in the git repository https://github.com/saltstack/salt/blob/v2018.3.4/salt/modules/boto3_route53.py

I did not check if this happens for other distros or on other versions as well.

### Steps to Reproduce Issue

```
mkdir /tmp/salt-2018-3-4
cd /tmp/salt-2018-3-4
wget https://repo.saltstack.com/yum/redhat/7.6/x86_64/2018.3/salt-2018.3.4-1.el7.noarch.rpm
rpm2cpio salt-2018.3.4-1.el7.noarch.rpm | cpio  -idmv

# This shows the content of the boto_route53 module from the rpm
cat ./usr/lib/python2.7/site-packages/salt/modules/boto_route53.py

# And this shows the content of the counter part from the git repo
curl https://raw.githubusercontent.com/saltstack/salt/v2018.3.4/salt/modules/boto3_route53.py
```

### Versions Report

Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.7.0
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.2.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by Ch3LL** [comment]
you are comparing two different files

`boto_route53.py` and `boto3_route53.py` so there would be some differences.

I triple checked to make sure the boto3_route53.py was indeed the same file as in the tag.

**Comment by Ch3LL** [comment]
I realized i might not have made that clear enough. The difference in the filenames is the 3 in `boto` versus `boto3`. Took me a second to see that one, they look so similar :)

**Comment by waynew** [comment]
Maybe vertically comparing:

```
boto_route53.py
boto3_route53.py
-----^
```

Might also make that clearer 🙂 

```
----------------------------------------------------------------------------------V
                                             cat ./usr/lib/python2.7/site-packages/salt/modules/boto_route53.py
curl https://raw.githubusercontent.com/saltstack/salt/v2018.3.4/salt/modules/boto3_route53.py
```

**Comment by quodt** [comment]
OMG, sorry for the noise, my fault. Thanks for clarification.
