### ISSUE TITLE
hosts: Allow to add comments

### ISSUE THREAD

**Issue by dhs-rec** [saltstack/salt#52185]
### Description of Issue
Entries in the /etc/hosts file can have comments. Unfortunately host.only or host.present doesn't have such an attribute. This ist the equivalent in Puppet, for example:
```
host { 'some_host':
  name         => 'somehost.example.com',
  ip           => '11.22.33.44',
  host_aliases => ['somehost'],
  comment      => 'Description for somehost',
  ensure       => present,
}
```
which results in this line in /etc/hosts:
```
11.22.33.44 somehost.example.com somehost # Description for somehost
```
Would be nice if execution/state modules for hosts could be enhanced to support comments as well.

**Comment by dhs-rec** [comment]
As a workaround I can add the comment as last name, but that's of course quite cumbersome:
```
11.22.33.44:
  host.only:
    - hostnames:
      - somehost.example.com
      - somehost
      - '# Description for somehost'
```

**Comment by dhs-rec** [comment]
Any news here?

**Comment by dhs-rec** [comment]
Ping.

**Comment by garethgreenaway** [comment]
Apologies for the delay on this.  Need to add a new PR to the master branch.
