### ISSUE TITLE
improve error reports for failed states

### ISSUE THREAD

**Issue by iluminite** [saltstack/salt#5219]
in short: when salt errors out when processing states for a minion, salt should better report _where_ the failure occurred.

It may be difficult to be specific about certain details, such as when jinja/etc are involved, but salt SHOULD know what state it is processing when it fails, and salt SHOULD tell the user where to start looking (the state file/etc) 

as a _small_ example, though there are so, _so_ many other examples:

```
 [salt.loaded.int.module.pkg_resource][WARNING ] "name" parameter will be ignored in favor of "pkgs"
```

if I have 30 state files that use pkgs, how do I know where to start looking?

**Comment by UtahDave** [comment]
A lot of work has been done on this topic.  Line numbers and locations in jinja are now provided. I'm going to close this for now.  

Please comment here if we need to reopen this issue for further development or discussion.

Thanks!
