### ISSUE TITLE
Server 2016 win_psget ConvertTo-Json problems

### ISSUE THREAD

**Issue by haodeon** [saltstack/salt#52216]
### Description of Issue/Question

I am trying to use the win_psget module to install DSC resources. The module appears to be bootstrapping and installing modules correctly but the minion is not able to return correct results.

The problem appears to come from piping the results of the PSGet cmdlets into the ConvertTo-Json cmdlet. The ConvertTo-Json cmdlet doesn't appear to be compatible with Install-Module and Get-PackageProvider.

### Setup

I have a salt-master on Ubuntu 18.04 and a salt-minion running on Server 2016. All I am using is the salt execution module win_psget.

### Steps to Reproduce Issue

I am using salt commands like:

"salt -G 'os:windows' psget.bootstrap"
"salt -G 'os:windows' psget.avail_modules"
"salt -G 'os:windows' psget.install xExchange"

bootstrap produces an error complaining about "An item with the same key has already been added". This error is not from the Get-PackageProvider cmdlet, it is from the ConvertTo-Json cmdlet

avail_modules ends up with result "VALUE_TRIMMED"

install produces the following:

```
ERROR: No JSON results from powershell. Additional info follows:

    retcode:
        0
    stderr:
    stdout:
```

### Versions Report

```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-1013-azure
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by cmcmarrow** [comment]
I have been able to replicate this problem. Thank you @haodeon for letting us know.

**Comment by cmcmarrow** [comment]
The Source of the problem may be that PowerShell is case insensitive. When Json is case sensitive.

**Comment by cmcmarrow** [comment]
We found the solution and will probably push the changes by the end of the day.

**Comment by cmcmarrow** [comment]
https://github.com/cmcmarrow/salt/tree/convertTo_Json_fix its a start

**Comment by cmcmarrow** [comment]
https://github.com/cmcmarrow/salt/tree/json_to_xml_psget_fix
This is the fix! Went from Json to Xml!
