### ISSUE TITLE
minion reporting missing pillar data

### ISSUE THREAD

**Issue by jvrahav** [saltstack/salt#52227]
### Description of Issue/Question

I have setup the orchestrator to pass on the id of a minion to trigger a state file execution. Unfortunately once in a while the orchestrator run fails with the below errror. I printed out the pillars in the sls and verified that the pillar value for minion does exist. this behaviour though is random i have 30 other minions where the orchestrator executed successfully.

This is my orchestrator file

install_some:
  salt.state:
     - name: installSome
     - tgt: '{{pillar['minion']}}'
     - sls:
        - some

this is the salt master log

`2019-03-18 17:05:57,769 [salt.utils.event                                                                   :739 ][DEBUG   ][25] Sending event: tag = salt/run/20190318170557765644/new; data = {'fun_args': ['orch.install_configure_collectd', {'orchestration_jid': None, 'pillar': OrderedDict([('minion', '0aab2768-f8a2-4a37-9367-27415dd30f33_vm-726')]), 'test': None, 'exclude': None, 'pillar_enc': None, 'pillarenv': None, 'saltenv': 'base'}], 'jid': '20190318170557765644', 'user': 'Reactor', 'fun': 'runner.state.orchestrate', '_stamp': '2019-03-18T17:05:57.769812'}
2019-03-18 17:06:24,214 [salt.utils.event                                                                   :739 ][DEBUG   ][25] Sending event: tag = salt/run/20190318170557765644/ret; data = {'fun': 'runner.state.orchestrate', 'fun_args': ['orch.install_configure_collectd', {'orchestration_jid': None, 'pillar': OrderedDict([('minion', '0aab2768-f8a2-4a37-9367-27415dd30f33_vm-726')]), 'test': None, 'exclude': None, 'pillar_enc': None, 'pillarenv': None, 'saltenv': 'base'}], 'jid': '20190318170557765644', 'success': False, 'return': {'data': {'4eafda608d13_master': ["Rendering SLS 'base:orch.install_configure_collectd' failed: Jinja variable 'salt.pillar object' has no attribute 'minion'"]}, 'retcode': 1, 'outputter': 'highstate'}, 'user': 'Reactor', '_stamp': '2019-03-18T17:06:24.214601'}`

Versions
=========

Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.6 (default, Mar  4 2019, 07:09:26)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: redhat 7.3 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: Centos

**Comment by dwoz** [comment]
@jvrahav Thanks for reporting the issue. Is the version report from your master or the minion this failure is for?

Also does this make a difference `{{ pillar['get']('minion')}}`?
