### ISSUE TITLE
Salt Master CleanUp Old Minions

### ISSUE THREAD

**Issue by ssoto2** [saltstack/salt#52229]
### Description of Issue/Question
I am looking to improve my master. specifically i want to clean up old minions automatically. It looks like i am living in the dark ages because per #13141 something like this was already implemented. I see an additional case regarding this in #34358 

My concern is before i start to implement this thorium reactor i am reading the notes and it specifically list in the 2019.2.0 documentation that thorium is still experimental and could be changed / be removed. Is this still the case? Or is it now fully supported?

![Selection_431](https://user-images.githubusercontent.com/5123879/54555081-5e6d9600-498c-11e9-9cca-28eaf0837661.jpg)

**Comment by Ch3LL** [comment]
the thorium reactor is still considered experimental, since we do not currently have anyone dedicated to building it to its full potential including in the community.

**Comment by Ch3LL** [comment]
since this was a question and not an issue with salt I will go ahead and close, but let me know if i need to re-open :)
