### ISSUE TITLE
salt break of _syspaths.py

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#52228]
### Issue
My salt installation is currently broken, I can't even `salt --version`.

### Description of Issue
I have allowed updates over the last month and a half while not using salt.
Last time it worked (in February, 2019) I was working with 2018.3.3 in a deescalated user (non-root).
The salt installation is using apt updating with the proper salt repo added in to my `source.list` file, with the `_syspaths.py` file uniquely modified to a single directory for testing and git versioning.

I am assuming my salt version is 2019.2.0

### Configuration
* /usr/lib/python2.7/dist-packages/salt/_syspaths.py
```PY
# Variables overlapping between auto-generation and online tutorial
ROOT_DIR = '/home/alan-cugler/testing/Salt_training/alans-salt-experiments'
CONFIG_DIR = ROOT_DIR + '/etc/salt'
CACHE_DIR = ROOT_DIR + '/var/cache/salt'
SOCK_DIR = ROOT_DIR + '/var/run/salt'
SRV_ROOT_DIR= ROOT_DIR + '/srv'
BASE_FILE_ROOTS_DIR = ROOT_DIR + '/srv/salt'
BASE_PILLAR_ROOTS_DIR = ROOT_DIR + '/srv/pillar'
BASE_MASTER_ROOTS_DIR = ROOT_DIR + '/srv/salt-master'
LOGS_DIR = ROOT_DIR + '/var/log/salt'
PIDFILE_DIR = ROOT_DIR + '/var/run'

# Variables not present in file but were in Docs
INSTALL_DIR = None
#CLOUD_DIR = INSTALL_DIR + '/cloud'
BOOTSTRAP = '/home/alan-cugler/testing/Salt_training/bootstrap-salt.sh'

# Variables present in file but not in Docs
SHARE_DIR = None
BASE_THORIUM_ROOTS_DIR = None
SPM_FORMULA_PATH = None
SPM_PILLAR_PATH = None
SPM_REACTOR_PATH = None
HOME_DIR = None
```
### The Error
```BASH
(vENV) alan-cugler@CPC:~$ salt --versions-report
Traceback (most recent call last):
  File "/usr/bin/salt", line 10, in <module>
    salt_main()
  File "/usr/lib/python2.7/dist-packages/salt/scripts.py", line 511, in salt_main
    import salt.cli.salt
  File "/usr/lib/python2.7/dist-packages/salt/cli/salt.py", line 11, in <module>
    import salt.utils.job
  File "/usr/lib/python2.7/dist-packages/salt/utils/job.py", line 11, in <module>
    import salt.minion
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 67, in <module>
    import salt.client
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 30, in <module>
    import salt.config
  File "/usr/lib/python2.7/dist-packages/salt/config/__init__.py", line 36, in <module>
    import salt.syspaths
  File "/usr/lib/python2.7/dist-packages/salt/syspaths.py", line 78, in <module>
    SHARE_DIR = __generated_syspaths.SHARE_DIR
AttributeError: 'module' object has no attribute 'SHARE_DIR'
```
### Related issues
- [Justification for my weird system](https://github.com/saltstack/salt/issues/51127)
- [_syspaths.py file is not well recorded](https://github.com/saltstack/salt/issues/51768)

**Comment by alan-cugler** [comment]
Solved the issue.
The variable `SPM_PARENT_PATH` was added in from 2018.3.3 to 2019.2.0 though I couldn't find any mention of it from the release notes.

by adding `SPM_PARENT_PATH = None` salt started working again.

**Comment by guettli** [comment]
same here:  I can't even `salt --version`.

Any reason why the pull request was not merged yet?
