### ISSUE TITLE
different minion can execute different cmd at the same time?

### ISSUE THREAD

**Issue by liuhetongzi** [saltstack/salt#52238]
### Description of Issue/Question
I wonder if different minion can execute different cmd at the same time.
I know different minion can execute same cmd like this
`salt -L '192.168.1.1,192.168.1.2' cmd.run 'df -h'`. but I want
192.168.1.1 cmd.run df -h
192.168.1.2 cmd.run free -m
they execute at the same time.
what should i do? thank you very much
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Aug 18 2016, 15:13:37)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: centos 6.9 Final
        machine: x86_64
        release: 2.6.32-573.el6.x86_64
         system: Linux
        version: CentOS 6.9 Final
```

**Comment by Ch3LL** [comment]
this is not currently supported. You should be able to run multiple salt commands at the same time and this should work. The closest thing supported to what you are attempting is compound command execution: `salt '*' cmd.run,test.ping,test.echo 'echo "1,2,3"' , , foo` but this of course would run against all minions and not run on a specific host in that target group.
