### ISSUE TITLE
Unable to target minion through customized grains

### ISSUE THREAD

**Issue by batilei** [saltstack/salt#52237]
I created a simple Salt Stack Cluster with a master and minion (pretty much follow https://docs.saltstack.com/en/latest/topics/installation/rhel.html). The Salt version is latest 2019.
 I manually added a customized grains to the minion in the file /etc/salt/grains.
`mykey: hello-key
`
I did see this key when running "salt '*' grains.items" in the master
```
  ...
  localhost:
        ip-172-31-24-109.us-west-2.compute.internal
    lsb_distrib_codename:
        CentOS Linux 7 (Core)
    lsb_distrib_id:
        CentOS Linux
    machine_id:
        b30d0f2110ac3807b210c19ede3ce88f
    manufacturer:
        Xen
    master:
        ec2-54-186-104-181.us-west-2.compute.amazonaws.com
    mdadm:
    mem_total:
        15883
    mykey:
        hello-key
    ...
```
Now the wired part is when I tried to target this minion through my customized grains, it doesn't work while every other way works!
```

[root@ip-172-31-28-130 ~]# salt '*' saltutil.refresh_modules
ip-172-31-24-109.us-west-2.compute.internal:
    True
[root@ip-172-31-28-130 ~]# salt '*' test.ping
ip-172-31-24-109.us-west-2.compute.internal:
    True
[root@ip-172-31-28-130 ~]# salt -G 'mem_total:*' test.ping
ip-172-31-24-109.us-west-2.compute.internal:
    True


[root@ip-172-31-28-130 ~]# salt -G 'mykey:hello-key' test.ping
ip-172-31-24-109.us-west-2.compute.internal:
    Minion did not return. [No response]
```
Anyone has a idea or suggestion?

**Comment by Ch3LL** [comment]
i'm not able to replicate this:

```
[root@bfb83254284b /]# salt -G 'mykey:hello-key' test.ping
bfb83254284b:
    True
```

i'm on 2019.2.0 is that the version you are on?

**Comment by batilei** [comment]
Hi Megan. Thanks for following up. The salt version is salt-minion 2019.2.0 (Fluorine). I restarted the minion machine, it works now......Not sure restart is required or?

**Comment by Ch3LL** [comment]
You could have also refreshed the grains. See note here: https://docs.saltstack.com/en/latest/topics/grains/#grains-in-etc-salt-grains

> Grains are static, and since they are not often changed, they will need a grains refresh when they are updated. You can do this by calling: salt minion saltutil.refresh_modules

**Comment by batilei** [comment]
Hi Megan. I tried to run the refresh command saltutil.refresh_grains and  saltutil.refresh_modules whenever I added a new grain key value. Still, 
```
salt '*' saltutil.refresh_modules
ip-172-31-23-214.us-west-2.compute.internal:
    True
ip-172-31-24-109.us-west-2.compute.internal:
    True

salt -G 'testkey:testvalue' test.ping
ip-172-31-24-109.us-west-2.compute.internal:
    Minion did not return. [No response]
ip-172-31-23-214.us-west-2.compute.internal:
    Minion did not return. [No response]
```

But the old grains key-value or '*' works.
```
[root@ip-172-31-28-130 salt]# salt '*' test.ping
ip-172-31-23-214.us-west-2.compute.internal:
    True
ip-172-31-24-109.us-west-2.compute.internal:
    True
```
Basically every time I added a new grain key-value, it seems I must restart the minion machine to get it work. I think it is pretty easy to reproduce. Just follow that tutorial, get two VMs on AWS, one master one minion, add a new grain key value on the minon, then run salt -G 'newkey:newvalue' test.ping. It never works for me (I tried all kinds of refresh) unless I restart the minion machine.

**Comment by whytewolf** [comment]
could this be a duplicate of #51934
