### ISSUE TITLE
Salt docs not propagating changes to 2019.2 version

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#52232]
### Question
I did a PR to include python 3 & 2 instruction for getting the built in http server up and running for doc checking #51774. This was added in 2017.7 and is showing up in 2018.3 docs, but not the 2019.2 docs. 

Did I do something wrong in the PR?

**Comment by Ch3LL** [comment]
It still needs to be merged forward. Looks like its waiting in this merge forward: https://github.com/saltstack/salt/pull/52190

We are currently having issues with our windows tests across all PRs so we cannot merge until those are resolved

**Comment by Ch3LL** [comment]
Since this was just a question I'll go ahead and close as this is resolved and is not an issue.
