### ISSUE TITLE
glusterfs.peered fails with glusterfs 5.5  XML cleanup issue

### ISSUE THREAD

**Issue by kangelos** [saltstack/salt#52243]
### Description of Issue/Question
glusterfs.peered fails with
```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1745, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1702, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/glusterfs.py", line 79, in peered
                  peers = __salt__['glusterfs.peer_status']()
                File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 156, in peer_status
                  root = _gluster_xml('peer status')
                File "/usr/lib/python2.7/dist-packages/salt/modules/glusterfs.py", line 84, in _gluster_xml
                  raise CommandExecutionError('\n'.join(result.splitlines()[:-1]))
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
a few well placed prints show that the result retrieved from salt['cmd.run'] contains the command sent to the gluster utils like so
```
==========
peer status
gluster> peer status
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<cliOutput>
  <opRet>0</opRet>
  <opErrno>0</opErrno>
  <opErrstr/>
  <peerStatus>
    <peer>
      <uuid>ba68fdb3-f37c-4b6c-ba38-328f3cccfd34</uuid>
      <hostname>xxxxxxx</hostname>
      <hostnames>
        <hostname>xxxxxxx</hostname>
        <hostname>xxxxxxxx</hostname>
      </hostnames>
      <connected>1</connected>
      <state>3</state>
      <stateStr>Peer in Cluster</stateStr>
    </peer>
  </peerStatus>
</cliOutput>
gluster>
==========
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
alt Version:
           Salt: 2016.11.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.8 
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8

**Comment by garethgreenaway** [comment]
@kangelos Thanks for the report.  Was this working with a previous version of Gluster?  Do know if something changed in 5.5?  Thanks!

**Comment by dgengtek** [comment]
I think this is the same issue as described in #50707

**Comment by kangelos** [comment]
> @kangelos Thanks for the report. Was this working with a previous version of Gluster? Do know if something changed in 5.5? Thanks!

I skipped that version so I could not tell you, sorry

**Comment by pruiz** [comment]
ping

**Comment by pruiz** [comment]
This affects glusterfs 6+ too, due to output from gluster command now (always) returning a banner like:
> Welcome to gluster prompt, type 'help' to see the available commands.

Which results on salt failing with: 

```
Error running 'glusterfs.info': Welcome to gluster prompt, type 'help' to see the available commands.
```

**Comment by sagetherage** [comment]
@garethgreenaway can you follow up here?
