### ISSUE TITLE
salt-ssh 2019.2.0 double unicode character in list

### ISSUE THREAD

**Issue by PauloGDPeixoto** [saltstack/salt#52242]
I'm trying to create a list in a template, retrieving data from various pillars to create it during the rendering, to be used in several states. Before going further, let me just say that this works correctly with any previous version of salt-ssh.

I'm using salt-ssh 2019.2.0 and I'm running the following to create my list:
```
{%- set countries = [] -%}
{%- for country in pillar['web']['data'] -%}
  {%- do countries.append(country) -%}
{%- endfor -%}
{%- do countries.append('others')%}
```
The pillars where the data is coming from are in the following form:
```
web:
  data:
    us:
      [other data, not important]
```
The output of this rendering is the following:
`[u"u'common'", u"u'us'", u"u'es'", u"u'it'", u"u'uk'", u"u'ru'", u'others']`
Where the following was expected:
`[u'common', u'us', u'es', u'it', u'uk', u'uk', u'others']`
Adding tojson as:
` {%- do countries.append(country | tojson) -%}`
as suggested in multiple other issues wields the following output:
`[u'Markup(u\'"common"\')', u'Markup(u\'"us"\')', u'Markup(u\'"es"\')', u'Markup(u\'"it"\')', u'Markup(u\'"uk"\')', u'Markup(u\'"ru"\')', u'others']`

**Comment by Ch3LL** [comment]
Can you clarify where you are using this pillar data in your state?

Im just looking for more context around your sls file that is using this data:

```
{%- set countries = [] -%}
{%- for country in pillar['web']['data'] -%}
  {%- do countries.append(country) -%}
{%- endfor -%}
{%- do countries.append('others')%}
```

I'm guessing we just need to ad the tojson filter somewhere else and not in that portion of the jinja.

**Comment by PauloGDPeixoto** [comment]
I'm sending it as context to a file template, I also just tested and figured out that I should add the tojson filter in the context.
Anyway, is this the expected behaviour, or is this something that will be fixed?
Also, thanks for your input, without your comment I would still be stuck with this!

**Comment by t0fik** [comment]
Problem also occurs in states ran by agent.
Example letsencrypt.install from letsencrypt-formula:
```
# -*- coding: utf-8 -*-
# vim: ft=sls
{% from "letsencrypt/map.jinja" import letsencrypt with context %}

letsencrypt-client:
  {% if letsencrypt.use_package %}
  pkg.installed:
    - pkgs: {{ letsencrypt.pkgs }}
  {% else %}
  pkg.installed:
    - name: git
  {% if letsencrypt.version is defined and letsencrypt.version|length %}
  git.cloned:
    - name: https://github.com/certbot/certbot
    - branch: {{ letsencrypt.version }}
    - target: {{ letsencrypt.cli_install_dir }}
  {% else %}
  git.latest:
    - name: https://github.com/certbot/certbot
    - target: {{ letsencrypt.cli_install_dir }}
    - force_reset: True
  {% endif %}
  {% endif %}
```
Renders to:
```
# -*- coding: utf-8 -*-
# vim: ft=sls


letsencrypt-client:
  
  pkg.installed:
    - pkgs: [u'python2-certbot-apache']
```
That is interpreted by `salt.utils.yamlloader.SaltYamlSafeLoader` to that:
```
OrderedDict([(u'letsencrypt-client', OrderedDict([(u'pkg.installed', [OrderedDict([(u'pkgs', [u"u'python2-certbot-apache'"])])])]))])
```

**Comment by Ch3LL** [comment]
@PauloGDPeixoto i'm glad you got it figured out :) this is expected behavior for python2 as documented in our 2019.2.0 release notes here: https://docs.saltstack.com/en/develop/topics/releases/2019.2.0.html#non-backward-compatible-change-to-yaml-renderer  you should be able to also use the json and yaml filter depending on your use case.
