### ISSUE TITLE
integration.states.test_beacon.BeaconStateTestCase.test_present_absent

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#52245]
```
integration.states.test_beacon.BeaconStateTestCase.test_present_absent
--------------------------------------------------------------------------------
2019.2 failed salt-centos-6-py2, salt-centos-7-py2, salt-ubuntu-1804-py3, 
--------------------------------------------------------------------------------
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Beacon "diskusage" is not available.
................................................................................
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_beacon.py", line 38, in test_present_absent
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 560, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
```

**Comment by waynew** [comment]
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1804-py3/11/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent)
---

False is not True. Salt Comment: Beacon "diskusage" is not available.

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 555, in assertSaltTrueReturn
    self.assertTrue(saltret)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_beacon.py", line 39, in test_present_absent
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 561, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
Beacon "diskusage" is not available.
		
```

This one failed again 😞

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1804-py3/55/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/56/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/56/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/54/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-2-py3/4/

**Comment by Ch3LL** [comment]
should be fixed by https://github.com/saltstack/salt/pull/53275
