### ISSUE TITLE
What does the variable "zone" mean?

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#52251]
### Question
- What does "zone" mean in this doc?
Please describe and give examples so that I can edit this doc to better explain meaning.

### Description
At [this doc](https://docs.saltstack.com/en/latest/topics/tutorials/firewall.html#fedora-18-and-beyond-rhel-7-centos-7) it shows a code snippet for a command to run in a terminal.

### Example
```BASH
firewall-cmd --permanent --zone=<zone> --add-port=4505-4506/tcp
```

**Comment by garethgreenaway** [comment]
@alan-cugler This might help:
```A network zone defines the level of trust for network connections. This is a one to many relation, which means that a connection can only be part of one zone, but a zone can be used for many network connections.```
https://firewalld.org/documentation/man-pages/firewalld.zones.html

**Comment by alan-cugler** [comment]
I'll add something like this to the doc then:

A network zone defines the level of trust for network connections.
Examples: `drop, block, public, external, dmz, work, home, internal, trusted.`
