### ISSUE TITLE
build_env_3.ps1 script hangs after pip install

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#52265]
### Description of Issue/Question
The Windows build environment script for Python 3 hangs after it finishes installing the pip requirements. You have to `ctrl+c` to end the script and then restart it. It will then finish successfully. This issue exists on all branches of Salt

### Setup
On a system, make sure Python 3 is not installed and that the Python 3 directory has been deleted. Run the `build_env_3.ps1` script.
Observe the hang.

**Comment by cmcmarrow** [comment]
https://github.com/saltstack/salt/pull/52365
