### ISSUE TITLE
trivial bug when using etcd with sdb

### ISSUE THREAD

**Issue by jnielsendotnet** [saltstack/salt#52268]
### Description of Issue/Question
After configuring etcd as an sdb target, running a command like this produces an error:
salt-call sdb.set sdb://mysdb/mynewkey mynewval
...
  File "/usr/lib/python2.7/site-packages/salt/sdb/etcd_db.py", line 78, in get
    return result.value
AttributeError: 'unicode' object has no attribute 'value'

The 'get' function in the EtcdClient class defined in utils/etcd_util.py already returns just the 'value' attribute of the python-etcd return object:
    return getattr(result, 'value', None)

But then 'get' in sdb/etcd_db.py tries to get the value of the value, which fails:
    client = _get_conn(profile)
    result = client.get(key)
    return result.value

Patching that to just 'return result' fixes the issue.

--- sdb/etcd_db.py.orig	2019-03-20 16:57:18.326708536 -0400
+++ sdb/etcd_db.py	2019-03-20 16:57:49.103070138 -0400
@@ -74,8 +74,9 @@
     Get a value from the etcd service
     '''
     client = _get_conn(profile)
-    result = client.get(key)
-    return result.value
+    return client.get(key)
 
 def delete(key, service=None, profile=None):  # pylint: disable=W0613

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by dwoz** [comment]
@jnielsendotnet Thanks for reporting this issue!

**Comment by jnielsendotnet** [comment]
This is still a problem and my PR still fixes it. Please merge it!
