### ISSUE TITLE
error source file not found

### ISSUE THREAD

**Issue by rajkamal31** [saltstack/salt#52267]
Both minions are running on SLES 12.1, same version of salt. But, on minion1 everything is good but on minion2, its not working, getting error source file not found

cat /srv/salt/test/top.sls

test:
  'G@os:RedHat':
    - updatemotd
  'G@osrelease:12.1':
    - updatemotd

master:/srv/salt/test # cat updatemotd/init.sls
update /etc/motd ile:
  file.managed:
    - name: /etc/motd
    - source: salt://updatemotd/motd

master:/srv/salt/test # cat updatemotd/motd
THIS IS MESSAGE OF THE DAY FILE

Both minions running on sles 12.1

minion1:
    Salt Version:
              Salt: 2018.3.0
minion2:
    Salt Version:
               Salt: 2018.3.0

master:/srv/salt/test # salt 'minion1' state.apply
minion1:
----------
          ID: update /etc/motd ile
    Function: file.managed
        Name: /etc/motd
      Result: True
     Comment: File /etc/motd updated
     Started: 16:20:18.761726
    Duration: 114.062 ms
     Changes:
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for minion1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time: 121.117 ms

master:/srv/salt/test # salt 'minion2' state.apply
minion2:
----------
          ID: update /etc/motd ile
    Function: file.managed
        Name: /etc/motd
      Result: False
     Comment: Source file salt://updatemotd/motd not found
     Started: 15:16:58.302448
    Duration: 70.146 ms
     Changes:

Summary for minion2
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  70.146 ms
ERROR: Minions returned with non-zero exit code

**Comment by dwoz** [comment]
@rajkamal31 Can you please provide the output from `salt -V` for both minions and the master?

**Comment by rajkamal31** [comment]
Hi, Please find the details below. Just to add another minion running on RHEL 7.4 also, it works fine. only one minion has the problem.

master:/srv/salt/test # salt -V
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-95.6-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64


minion1:~ # salt-minion -V
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 3.12.74-60.64.40-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64



minion2:~ # salt-minion -V
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 3.12.74-60.64.40-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64



minion1:~ # salt-minion -V
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.1.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Dec 21 2014, 11:02:59) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 3.12.74-60.64.40-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64



[root@minion3 ~]# salt-minion -V
/usr/lib/python2.7/site-packages/salt/scripts.py:198: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by rajkamal31** [comment]
@dwoz : I've added the following lines and restarted the minion which has issue, after which it was picking up the environment. If I put only one of environment or saltenv, it was not picking up.

lock_saltenv: True
environment: test
saltenv: test

**Comment by rajkamal31** [comment]
@dwoz, having said that, it is not consistent. I am trying to update syslog to redirect logs to remote hosts and again see errors that source file not found.
