### ISSUE TITLE
salt-cloud access resources from other projects in GCP

### ISSUE THREAD

**Issue by jinm** [saltstack/salt#52275]
### Description of Issue/Question
My setup has one global project collecting disk images, network definition and other shareable resources. When trying to create a team project, I failed to find a way to add another private project for salt-cloud to find resources. By looking near gce.py, it does not seem to be able to get images from other projects. I am having the same issue to use a network defined in a global project to start an instance in a team project.

https://github.com/saltstack/salt/blob/27474994ea6552002b4a361ec6353e61bcbda3d3/salt/cloud/clouds/gce.py#L357

Does anyone know if this is doable or discussed in an existing thread already?

Thanks!

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

$ rpm -qa | grep cloud
google-cloud-sdk-237.0.0-1.el7.noarch
python2-libcloud-2.0.0rc2-1.el7.noarch
salt-cloud-2019.2.0-1.el7.noarch

**Comment by gtmanfred** [comment]
It is not currently possible afaik.

That feature would need to be added to gce.py

**Comment by jinm** [comment]
GCE driver in ibcloud supports an ex_project option in some functions (list_images) but not all (ex_list_network). Looks like I need to explore another option for my setup where the central project manages many resources.

Thanks all for looking into this!
