### ISSUE TITLE
Replace ping with version in docx

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#52277]
### Suggested docx change
 replace:
`salt "*" test.ping`
with:
`salt "*" test.version`

### Reasoning
Any experienced salt user I talk to recommends using `version` over `ping` because it completes the same task and gives awareness of your salt versioning and a potential chance to catch a versioning mistake.

On this [docx page](https://docs.saltstack.com/en/latest/topics/installation/index.html) and any others I can find.

**Comment by alan-cugler** [comment]
If its already recommended by salt savvy peoples, then we should teach it from the beginning when people are first learning salt.

**Comment by Ch3LL** [comment]
that is a fair suggestion. should be a easy change if you want to give it a go

**Comment by alan-cugler** [comment]
Yeah, I'll replace and PR. Thanks @Ch3LL

**Comment by erwindon** [comment]
Please do not remove `test.ping`. Everyone trusts that to be present. It is the first thing to use for new minions and connections problems. Plenty of 3rd part scripts and procedures exists that refer to it.
A new function `test.version` is obviously no problem.
