### ISSUE TITLE
SaltSSH and 'service' modules/states with non-systemd master and systemd target conflict

### ISSUE THREAD

**Issue by NicolasT** [saltstack/salt#52272]
We're running into a strange issue with `salt-ssh`: running `salt-ssh` from within a CentOS7-based container, but targetting a plain CentOS7 host, when we run `salt-ssh node state.single service.running sshd`, it produces a warning and fails:

```
[WARNING ] org.freedesktop.DBus.Error.FileNotFound: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory
node:
    - Specified state 'service.running' was not found
```
However, running `salt-ssh node state.apply foo.bar` where the `foo.bar` SLS is basically

```
sshd:
    service.running
```

works just fine:

```
node:
------
          ID: sshd
    Function: service.running
      Result: True
     Comment: The service sshd is already running
     Started: 14:35:39.276547
    Duration: 59.714 ms
     Changes:

Summary for node
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  59.714 ms
```

Debugging this, it *appears* that in the first case, `state.single service.running ...`, the 'service' module is dispatched on the `salt-ssh` host, i.e. inside the container, where there's no DBus or `systemd` running and such, so no valid `service` implementation can be 'found'.

However, with `state.apply` this works out fine, maybe because the SLS rendering is delayed and only happens on the target host, at which point (only) the 'service' module can be looked up (somehow). Just guessing :)

If the guesswork above is correct, then of course it's a bit odd if indeed the 'service' module dispatching is performed on the host from which `salt-ssh` is invoked, without taking the target host into account. Similarly, when invoking the same `salt-ssh node state.single service.running sshd` from a 'full-fledged' CentOS7 host, not a container, this works just fine (which is in line with the guesswork above as well).

**Comment by dwoz** [comment]
@NicolasT What is the output of `salt -V`?

**Comment by NicolasT** [comment]
```
Salt Version:
           Salt: 2018.3.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

```

Tried with 2019.2.0 as well, +- same result.

**Comment by NicolasT** [comment]
What more info is needed here?

**Comment by NicolasT** [comment]
Ping @dwoz

**Comment by NicolasT** [comment]
Nope, not 'stale'...

**Comment by sagetherage** [comment]
@dwoz can you please do a little follow up, here?
