### ISSUE TITLE
OpenSUSE Leap repository is outdated

### ISSUE THREAD

**Issue by TheLastProject** [saltstack/salt#52273]
### Description of Issue/Question
https://repo.saltstack.com/#suse states, after clicking OpenSUSE LEAP 15, "Installs the latest release."

However, the repository still contains salt 2018.3 instead of 2019.2: https://repo.saltstack.com/opensuse/openSUSE_Leap_15.0/src/

Is this an oversight or is there an explicit reason why the repository provides an old version?

**Comment by dmurphy18** [comment]
@TheLastProject  The Salt packages for OpenSUSE and SLES are produced by SUSE and SaltStack makes available a copy of those packages on repo.saltstack.com, basically provide a mirror of the packages that SUSE provides.

Given that Salt 2019.2.0 is a recent release, perhaps SUSE has not had time to build, test, verify and  release that version of Salt  yet.  Unfortunately, SaltStack is dependent on SUSE timeframes as to when Salt packages and what versions and OS platforms are released.

If this information is satisfactory for your issue, perhaps you will consider closing it.

**Comment by TheLastProject** [comment]
That makes sense. May I suggest that the text on the webpage shouldn't say it installs the latest version then? Because to me that would mean 2019.2, so receiving 2018.3 instead was quite unexpected.

**Comment by dmurphy18** [comment]
Perhaps it should state **_'latest available from SUSE'_**

Made that a Documentation issue.
