### ISSUE TITLE
Amazon Linux 2 with Python 3 giving broken CPE_NAME format

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#52281]
### Description of Issue/Question
Reporting broken CPE_NAME format in /etc/os-release for Amazon Linux 2 (seen on Python 3)

### Setup
Install Amazon Linux 2 salt-minion and  grains.items

### Steps to Reproduce Issue
143 2019-03-21 19:55:08,228 [salt.loaded.int.grains.core:1773][ERROR   ][4113] Broken CPE_NAME format in /etc/os-release!

witt current 2019.2 branch (21 March 2019)

### Versions Report
[root@ip-10-200-13-81 ec2-user]# salt-call --local test.versions
[ERROR   ] Broken CPE_NAME format in /etc/os-release!
local:
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: 1.6.0
           cherrypy: Not Installed
           dateutil: 2.6.0
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.31.0
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.4.6
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.14 (default, Jul 26 2018, 19:59:38)
       python-gnupg: 0.4.3
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist:   
             locale: UTF-8
            machine: x86_64
            release: 4.14.104-95.84.amzn2.x86_64
             system: Linux
            version: Not Installed

**Comment by edeefelt** [comment]
I am seeing this issue on AMI ami-00b882ac5193044e4 on a clean setup/install from bootstrap:

`sh-4.2$ sudo salt-call --version
salt-call 2019.2.0 (Fluorine)
sh-4.2$ sudo salt-call grains.item osfinger
[ERROR   ] Broken CPE_NAME format in /etc/os-release!
local:
    ----------
    osfinger:
        Amazon Linux-2`

**Comment by jars99** [comment]
I'm getting this same error on Amazon Linux 2 with salt version 2018.3.5
