### ISSUE TITLE
Document requisite wildcards

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#52308]
It appears that wildcards can be used in requisites, but this is not documented.

    - file: /etc/nginx/sites-enabled/*

Although a bare `*` results in an error

    - acme: *

> expected alphabetic or numeric character, but found '\n'

**Comment by Akm0d** [comment]
Checked in https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html
This is where I would expect to find this behavior documented but it isn't there. 

The closest thing I can find is under salt.modules.file.grep where it says:

"Globbing is supported (i.e. /var/log/foo/*.log, but if globbing is being used then the path should be quoted to keep the shell from attempting to expand the glob expression."

**Comment by dmurphy18** [comment]
Documantation should be added to Requisites, should be single quoted, similar to example in https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html, WILDCARD Versions

mypkg:
  pkg.installed:
    - version: '1.2.34*'

**Comment by max-arnold** [comment]
It is documented - see #52020 and [glob matching in requisites](https://docs.saltstack.com/en/develop/ref/states/requisites.html#glob-matching-in-requisites). Probably needs to be backported.

**Comment by OrangeDog** [comment]
That doesn't say it needs to be quoted, nor whether it matches globally or only in the current sls.
The wording could be taken to mean it matches file changes (whether there's a state or not), not state changes.

**Comment by max-arnold** [comment]
Also, this feature is not consistent (as many other things in Salt, unfortunately). It doesn't work with `*_in` style requisites.

**Comment by max-arnold** [comment]
Bump

**Comment by OrangeDog** [comment]
unstale

**Comment by OrangeDog** [comment]
unstale

**Comment by OrangeDog** [comment]
> Checked in https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html
> This is where I would expect to find this behavior documented

@Akm0d that's another problem caused by lack of documentation, people think `file` states are somehow special because the only wildcard examples use `file`. The documentation should be here:

https://docs.saltproject.io/en/latest/ref/states/requisites.html#glob-matching-in-requisites

Calling it "glob matching" is highly misleading, as `glob` is specifically for matching files.

**Comment by dkacar-oradian** [comment]
Also, it should be specified which glob operators are supported. Do I have all of these available?
http://zsh.sourceforge.net/Doc/Release/Expansion.html#Glob-Operators

Globbing in shells isn't used for matching files only. For example:
```
foo=bar
if [[ $foo == ba* ]]; then
    echo It works
fi
It works
```
will work that way in a number of shells. However, if I want an expression like this:
```
if [[ $val != [0-9]##(|[MG]) ]]; then
    ...
fi
```
then things become problematic. That won't work everywhere and I'd really like to know which glob operators are supported.

**Comment by OrangeDog** [comment]
@dkacar-oradian that's not globbing, that's pattern matching. The historical program `glob` and the current C library function `glob` are specifically for matching filenames. Your zsh documentation has it under "Filename Generation". And as Wikipedia says

> In computer programming, glob patterns specify sets of filenames with wildcard characters.

Matching states with wildcard patterns should not be called globbing. It just fuels the confusion that it only works on files.

**Comment by dkacar-oradian** [comment]
OK, you're right, but you didn't manage to come up with convincing argument. :-)

My usage of the term "globbing" is very loose and basically indicates the syntax of the expression. As opposed to the regexp syntax, mostly.

However, after some investigation, the defining properties are:
```
       Globbing is applied on each of the components of a pathname separately.
       A '/' in a pathname cannot be matched by a '?' or '*' wildcard, or by a
       range like "[.-0]".  A range containing an explicit  '/'  character  is
       syntactically  incorrect.  (POSIX requires that syntactically incorrect
       patterns are left unchanged.)

       If a filename starts with a '.', this character must be matched explic-
       itly.   (Thus,  rm * will not remove .profile, and tar c * will not ar-
       chive all your files; tar c . is better.)
```
