### ISSUE TITLE
 Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute

### ISSUE THREAD

**Issue by ReubenM** [saltstack/salt#52302]
### Versions Report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  1 2018, 03:12:47)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: oracle 7.6
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: Oracle Linux Server 7.6

----
I'm have reactors calling orchestrations and passing the event data to them. (orchestrations is turn, apply states using the data) About 80% of the time it works, but it randomly fails saying an attribute is not available, when in the very same log output the attribute is there.

Not sure what else would be useful to provide. I can provide sls files if it helps any.

```
[DEBUG   ] Sending event: tag = salt/run/20190322195347727719/new; data = {u'fun': u'runner.state.orchestrate', u'fun_args': [{u'pillar': OrderedDict([(u'event_tag', u'abl/camm7/db/fan/instance'), (u'event_data', OrderedDict([(u'VERSION', u'1.0'), (u'cluster', u'camm7-cluster'), (u'database', u'cdicom'), (u'db_domain', u'world'), (u'host', u'dh2rcammdb03'), (u'instance', u'cdicom1'), (u'pillarenv', None), (u'reason', u'USER'), (u'saltenv', u'camm7'), (u'service', u'cdicom.world'), (u'status', u'down'), (u'timestamp', u'2019-03-22 19:52:42'), (u'timezone', u'-05:00')]))]), u'mods': u'orch.master_worker.fan.instance'}], u'jid': u'20190322195347727719', u'user': u'Reactor', u'_stamp': '2019-03-23T00:53:47.799895'}
[DEBUG   ] Sending event: tag = salt/run/20190322195347727719/ret; data = {u'fun_args': [{u'pillar': OrderedDict([(u'event_tag', u'abl/camm7/db/fan/instance'), (u'event_data', OrderedDict([(u'VERSION', u'1.0'), (u'cluster', u'camm7-cluster'), (u'database', u'cdicom'), (u'db_domain', u'world'), (u'host', u'dh2rcammdb03'), (u'instance', u'cdicom1'), (u'pillarenv', None), (u'reason', u'USER'), (u'saltenv', u'camm7'), (u'service', u'cdicom.world'), (u'status', u'down'), (u'timestamp', u'2019-03-22 19:52:42'), (u'timezone', u'-05:00')]))]), u'mods': u'orch.master_worker.fan.instance'}], u'jid': u'20190322195347727719', u'return': {u'outputter': u'highstate', u'data': {u'dh2vrcammpnacl1_master': [u"Rendering SLS 'base:orch.master_worker.fan.instance' failed: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'instance'"]}, u'retcode': 1}, u'success': False, u'_stamp': '2019-03-23T00:54:11.235819', u'user': u'Reactor', u'fun': u'runner.state.orchestrate'}
[INFO    ] Runner completed: 20190322195347727719
```

**Comment by ReubenM** [comment]
This looks similar to #29018.

**Comment by dmurphy18** [comment]
Seeing similar issue with reactor for Cloud VM deletion , not fully deleting the occasional VM in the nightly builds.

**Comment by ReubenM** [comment]
I think I've found the source of my issue (which is probably unrelated to dmurphy18's issue):

The missing attribute was missing from the grain dictionary, not the data dictionary passed from the orchestration. They just happened to have the same name.

I was basically doing something like:

```
{% if salt['grains.get']('foo:bar') == salt['pillar.get']('event_data:bar') %}
```
The missing attribute "bar" was missing from grains, not the pillar.

The grains always had bar when manually querying it, so I was working on the assumption that the issue was the data passing with pillar. (The error log doesn't indicate the name of the dictionary missing the attribute)

The problem was that I wasn't aware that the grains are re-evaluated every time they are accessed (when using default settings) and the sequence of states being applied just happened to cause the grain to not evaluate properly depending on how the timings worked out (which is why it sometimes worked and other times didn't). I implemented a cache file into the custom grain so that the grain is not actually evaluated unless the cache file is missing. Now that the cached data is used, everything works.

**Comment by dmurphy18** [comment]
@ReubenM Glad to hear that you were able to resolve the issue.  My issue was resolved by adding a requires to ensure that the salt-cloud destroy operation completed in my reactor before removing the minion from the master.  Occasionally the destroy operation could take some time on AWS.

  runner.cloud.destroy:
    - args:
        instances: {{data['id']}}
  wheel.key.delete:
    - args:
        match: {{data['id']}}
    - require:
      - runner: runner.cloud.destroy

If you have resolved this issue, please consider closing the issue, unless there is something else related to the issue I can help you with.

**Comment by ReubenM** [comment]
Only left this open in case there was anything that needed attention from your issue. Closing.
