### ISSUE TITLE
Add Salt Docker Images to Docker Hub

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52325]
### Description of Issue/Question
We need to create docker images with both salt-master and salt-minion installed that are available on Docker Hub.

- [ ] Docker images for both the current nightly builds and the salt releases.
- [ ] publish docker compose files
- [ ] publish helm charts

**Comment by astronouth7303** [comment]
My version of this is https://gitlab.com/spirostack/salt-container

I also have a tool that (as part of its work) runs salt-bootstrap against docker images.

**Comment by dmurphy18** [comment]
Wonder about the sanity of doing nightly builds given that they may be unstable, why give users the equivalent of items to drop on their feet.

**Comment by garethgreenaway** [comment]
Nightly builds, like all nightly builds, should come with a caveat that they are likely to be in various stages of brokenness.

**Comment by gtmanfred** [comment]
What is the reason for including the minion?

The master and API is the service that makes the most sense including in this. Inevitably people will want to have extra stuff on their minion, and starting from the salt-minion layer is unlikely to be as useful as just doing it on their own.

I would love to discuss this with someone as I have automated the builds for the most part, would just need to include a nightly portion.

https://github.com/gtmanfred/saltdocker

**Comment by garethgreenaway** [comment]
My understanding is that there were a couple ideas behind wanting Docker images for both the Salt minion as well as the master.  First, it would provide a contained, ready to go setup for those people who want to try it out.  Without having to install to a virtual machine or install a completely new system locally.  Second, it would allow us to provide images for people to test upcoming releases in a contained environment, for similar reasons as the first example.

**Comment by wasosa** [comment]
I recently filed an issue here, and went looking for docker images I could use to write a reduced test case. Since I couldn't find any, I wrote my own Dockerfile (https://github.com/wasosa/pillar-render-error/blob/master/Dockerfile). Having images with master and minion would have come in handy.

**Comment by bluemalkin** [comment]
Hi - is there an ETA when we can expect the images on official saltstack dockerhub ?  :-)

**Comment by KChandrashekhar** [comment]
> Hi - is there an ETA when we can expect the images on official saltstack dockerhub ? :-)

Expected to be out by May 6th

**Comment by gtmanfred** [comment]
This has been released https://hub.docker.com/r/saltstack/salt
