### ISSUE TITLE
Metadata Server Grains (metadata_server_grains) doesn't work in Google anymore

### ISSUE THREAD

**Issue by timwsuqld** [saltstack/salt#52332]
### Description of Issue/Question
Google Instances don't respond to http://169.254.169.254/latest anymore. It was likely an endpoint they had for compatibility until they built out their own system.

### Setup
```yaml
metadata_server_grains: True
```

### Steps to Reproduce Issue
Load up a Google Compute Instance (GCE) with custom metadata and check the URL http://169.254.169.254/latest for that data.

The new URL that is needed is  http://metadata.google.internal/computeMetadata/v1/instance/attributes/ (direct to IP also works http://169.254.169.254/computeMetadata/v1/instance/attributes/) and it requires the header `Metadata-Flavor: Google`

More details available at https://cloud.google.com/compute/docs/storing-retrieving-metadata

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1028-gcp
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by dmurphy18** [comment]
With 2019.2 branch

doc/ref/configuration/minion.rst:``http://169.254.169.254/latest`` for use in grains (see :py:mod:`here
doc/man/salt.7:Grains from cloud metadata servers at 169.254.169.254
doc/man/salt.7:Grains from cloud metadata servers at 169.254.169.254
doc/man/salt.7:To enable these grains that pull from the \fI\%http://169.254.169.254/latest\fP
salt/grains/metadata.py:Grains from cloud metadata servers at 169.254.169.254
salt/grains/metadata.py:To enable these grains that pull from the http://169.254.169.254/latest
salt/grains/metadata.py:IP = '169.254.169.254'
salt/utils/aws.py:                "http://169.254.169.254/latest/meta-data/iam/security-credentials/",
salt/utils/aws.py:                "http://169.254.169.254/latest/meta-data/iam/security-credentials/{0}".format(role),
salt/utils/aws.py:            "http://169.254.169.254/latest/dynamic/instance-identity/document",
salt/modules/win_status.py:          TCP    10.1.1.26:56868        169.254.169.254:80     CLOSE_WAIT

but will affect 2018.3 too

**Comment by timwsuqld** [comment]
Not stale

**Comment by timwsuqld** [comment]
Not stale

**Comment by timwsuqld** [comment]
Not stale

**Comment by timwsuqld** [comment]
@sagetherage Can you please reopen this and triage it so stalebot leaves it alone.

**Comment by timwsuqld** [comment]
@dmurphy18 You also appear to have repo access, can we please get the correct labels added to this to stop stalebot from closing it (and please reopen it)

**Comment by sagetherage** [comment]
@timwsuqld reopened, not sure why the stale bot is so badly configured since it says it will open it, but looking to remove it or upgrade to something better, soon.

**Comment by sagetherage** [comment]
@timwsuqld apologies for not seeing the mention - I use email filter and that has apparently stopped working as well, so my fault completely!

**Comment by timwsuqld** [comment]
@sagetherage Thanks for reopening this. Looking forward to Stalebot being replaced with something that works.

**Comment by cwray** [comment]
Might just be able to change the path here https://github.com/saltstack/salt/blob/1d7ccd10b3f7c4fd2d7c922c8afc78abb2d4eea3/salt/grains/metadata.py#L29

**Comment by sagetherage** [comment]
Great! @timwsuqld or @cwray want to open a PR?

**Comment by cwray** [comment]
Digging into this a bit further. It looks like this works for AWS also. If we just change this path we will break the metadata pulling in AWS.

GCP and AWS both have different metadata endpoints now.

**Comment by xeacott** [comment]
> GCP and AWS both have different metadata endpoints now.

So it sounds like we just need a pool of endpoints, and based on our host, decide which one to use and then use it? @cwray

**Comment by cwray** [comment]
Yes, That might work.

**Comment by cwray** [comment]
GCP Metadata documentation for reference. https://cloud.google.com/compute/docs/storing-retrieving-metadata

**Comment by xeacott** [comment]
Would you be able to throw up a PR with those changes? @cwray

**Comment by sagetherage** [comment]
The Core team won't be able to get to this in `Aluminium` but we will gladly review a PR.

**Comment by superzc-github** [comment]
hi @whytewolf , Im seeing same grains metadata issue on TencentCloud seems it's tend that cloud using their own FQDN for metadata, so cloud we consider to add a parameter to replace the metadata url?
some thing like:
metadata_server_grains: True
metadata_server_url: http://metadata.tencentyun.com/latest/meta-data

**Comment by whytewolf** [comment]
@superzc-github You are welcome to add that functionality yourself. in the end with this ticket i had to actually create a whole new grains module as gce didn't just change the url they actually changed the way their metadata server works as a whole. googles metadata server is not ec2 compatible. 

but google at least uses the correct ip. 169.254.169.254 this is a pretty standard ip for metadata servers. even google with their non ec2 compatible metadata server still use this ip address. the module uses that ip and isn't tied to a fqdn. so if tencent is using a different ip for their metadata server then i would start looking into what they changed and why.

**Comment by superzc-github** [comment]
> @superzc-github You are welcome to add that functionality yourself. in the end with this ticket i had to actually create a whole new grains module as gce didn't just change the url they actually changed the way their metadata server works as a whole. googles metadata server is not ec2 compatible.
> 
> but google at least uses the correct ip. 169.254.169.254 this is a pretty standard ip for metadata servers. even google with their non ec2 compatible metadata server still use this ip address. the module uses that ip and isn't tied to a fqdn. so if tencent is using a different ip for their metadata server then i would start looking into what they changed and why.

@whytewolf  thank a lot bro, not sure if I have permission to submit a commit to add that kind of feature, will have a try.
