### ISSUE TITLE
import_yaml don't allow variable 

### ISSUE THREAD

**Issue by cde0** [saltstack/salt#52348]
I want to read a file but with a variable and i get this error:

>  Rendering SLS 'base:xcore.os.bonding' failed: Jinja syntax error: expected token 'as', got '{'; line 12

The code:

> {% import_yaml '/home/x/'{{ file }} as yaml_config %}

**Comment by dmurphy18** [comment]
@cde0 You are using {{}} inside a Jinja statement, the line should probably read as follows:

{% set file = 'myfile' %}
{% import_yaml '/home/x/' ~ file  as yaml_config %}

inside the Jinja statement no need for '{{ }}'

Not a Salt issue, hence closing, please re-open if this is not unsatisfactory, with comments
