### ISSUE TITLE
mysql_user error in host with IP/netmask

### ISSUE THREAD

**Issue by minusf** [saltstack/salt#52358]
### Description of Issue/Question

This is the reposting of #52337 which was closed by @dmurphy18 without any kind of meaningful discussion.

```
          ID: mariadb-create-user-monitor
    Function: mysql_user.present
        Name: monitor
      Result: False
     Comment: Failed to create user monitor@10.10.10.0/255.255.255.0
     Started: 13:38:44.108402
    Duration: 17.458 ms
     Changes:   
```

```
[INFO    ] Running state [monitor] at time 13:38:44.108402
[INFO    ] Executing state mysql_user.present for [monitor]
[DEBUG   ] Doing query: SELECT VERSION()
[DEBUG   ] Doing query: SELECT column_name from information_schema.COLUMNS WHERE table_schema=%(schema)s and table_name=%(table)s and column_name=%(column)s args: {u'column': u'Password', u'table': u'user', u'schema': u'mysql'} 
[ERROR   ] MySQL Error 1045: Access denied for user 'monitor'@'localhost' (using password: YES)
[DEBUG   ] Doing query: SELECT VERSION()
[DEBUG   ] Doing query: SELECT column_name from information_schema.COLUMNS WHERE table_schema=%(schema)s and table_name=%(table)s and column_name=%(column)s args: {u'column': u'Password', u'table': u'user', u'schema': u'mysql'} 
[DEBUG   ] Doing query: SELECT User,Host FROM mysql.user WHERE User = %(user)s AND Host = %(host)s args: {u'host': u'10.10.10.0/255.255.255.0', u'user': u'monitor'} 
[DEBUG   ] Doing query: SELECT VERSION()
[DEBUG   ] Doing query: SELECT VERSION()
[DEBUG   ] Doing query: SELECT column_name from information_schema.COLUMNS WHERE table_schema=%(schema)s and table_name=%(table)s and column_name=%(column)s args: {u'column': u'Password', u'table': u'user', u'schema': u'mysql'} 
[DEBUG   ] Doing query: SELECT User,Host FROM mysql.user WHERE User = %(user)s AND Host = %(host)s args: {u'host': u'10.10.10.0/255.255.255.0', u'user': u'monitor'} 
[DEBUG   ] Doing query: SELECT column_name from information_schema.COLUMNS WHERE table_schema=%(schema)s and table_name=%(table)s and column_name=%(column)s args: {u'column': u'Password', u'table': u'user', u'schema': u'mysql'} 
[DEBUG   ] Doing query: CREATE USER %(user)s@%(host)s IDENTIFIED BY %(password)s args: {u'host': u'10.10.10.0/255.255.255.0', u'password': u'password', u'user': u'monitor'} 
[DEBUG   ] Doing query: SELECT VERSION()
[ERROR   ] MySQL Error 1045: Access denied for user 'monitor'@'localhost' (using password: YES)
[INFO    ] User 'monitor'@'10.10.10.0/255.255.255.0' was not created
[ERROR   ] Failed to create user monitor@10.10.10.0/255.255.255.0
[INFO    ] Completed state [monitor] at time 13:38:44.125860 (duration_in_ms=17.458)
```

But the user is created:

```
+--------------------------+----------+-------------------------------------------+
| host                     | user     | password                                  |
+--------------------------+----------+-------------------------------------------+
| 10.10.10.0/255.255.255.0 | monitor  | *91F4DA1D373A3012AAE8C67A1DF9C54CBD0846F9 |
+--------------------------+----------+-------------------------------------------+
```

I think the issue is, that the creation is considered successful _only_ if the user can connect back using 'localhost' (the last section of the debug log).

This of course fails, as these users have explicit IPs that they can connect from and localhost is not one of them.  I think the check should simply see if the user is present in `mysql.user` and not try to be too "smart" about it.

### Setup

```
mariadb-create-user-monitor:
  mysql_user.present:
    - name: "monitor"
    - password: "password"
    - host: "10.10.10.0/255.255.255.0"
```

### Versions Report

```
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by garethgreenaway** [comment]
@minusf Thanks for the report.  This appears related to some recent changes in the MySQL module following changes made by MySQL in how password authentication works.  The change was made to how we verify if the password needed to be updated, etc.  Unfortunately the approach I took made certain assumptions that turned out not to be accurate.  I've assigned this one to myself and will be taking a look.  Thanks!

**Comment by minusf** [comment]
@garethgreenaway any news on this?

it's not clear to me why `run_verify` is needed at all besides `qry` checking if the user is present in the system tables.  i don't think it is salt's job to actually try and login as that user because that just makes a lot of assumptions about the how the user will be used.

**Comment by minusf** [comment]
i see now in git log that this was introduced because of some mysql 8 changes. as far as i know mariadb is not deprecating `PASSWORD`, and i think mariadb should be excluded from this special casing.

regardless i dont know how this would work with mysql 8 users having a non-localhost `host` field...
trying to login as the user is simply not a good idea.

**Comment by garethgreenaway** [comment]
@minusf Apologies for the delay on this one.  The `run_verify` was added as a work around to verify that the password was correct.  Previously we could generate the password in a query but beginning with the changes in MySQL 8 the PASSWORD function was removed and is no longer available.  The tricky part is that all the variants of MySQL are currently using the same Salt code, so we have to account for all use cases in one module.

**Comment by garethgreenaway** [comment]
I believe the above PR fixes the issues here, if you're able to try out the changes that would be greatly appreciated.

**Comment by garethgreenaway** [comment]
May have jumped the gun, there are a few other functions that need to be updated.  Stay tuned :smile:

**Comment by garethgreenaway** [comment]
Okay. Should have taken care of the various bugs reported, if you're able to test the changes in the PR above that would be greatly appreciated.
