### ISSUE TITLE
[BUG] certname in acme module doesn't work

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#52361]
The acme state and module functions take an optional `certname` argument that's supposed to change the default CN-based name.

However, it's only use is to pass the `--cert-name` parameter to certbot, causing it to create the certificate correctly at the `certname` path.
Everything else then fails, because it looks for files using the `name` instead of `certname`.

As far as I can tell, this feature has never worked since it was added by @mprenditore in https://github.com/saltstack/salt/commit/665803a

**Comment by OrangeDog** [comment]
My fixes are ongoing. Now I've got this error.
> TypeError: can't serialize dict_keys(['keyUsage', 'extendedKeyUsage', 'basicConstraints', 'subjectKeyIdentifier', 'authorityKeyIdentifier', 'authorityInfoAccess', 'subjectAltName', 'certificatePolicies', 'ct_precert_scts'])

**Comment by OrangeDog** [comment]
It also returns a changes dict even when nothing has changed.

**Comment by OrangeDog** [comment]
PR: 52362

**Comment by a-schuurman** [comment]
I've got the same issues as you have; resulting in the fact that the minion doesn't return to the master but does create the certificate. It would be nice to have a fix for this.

**Comment by OrangeDog** [comment]
Still not fixed in 2019.2.1 because I didn't have time to write a testcase (nor am I sure how to).

**Comment by OrangeDog** [comment]
Not stale, but I still don't have time to build any tests. If someone else wants to help...

**Comment by nee2c** [comment]
I have update the PR due to the conflicts with master.  If I get a chance next week I'll get some unit test written.

**Comment by nee2c** [comment]
I have added new PR #57569, with tests and docs updates

**Comment by OrangeDog** [comment]
@sagetherage no, why does it need unlinking?

**Comment by sagetherage** [comment]
I meant this issue wouldn't close if linked, but I guess that PR is now closed so once the latest PR https://github.com/saltstack/salt/pull/57569 merges then it should close this issue - that was all I was trying to do, ensure the automation to close the issue works.
