### ISSUE TITLE
git docs clarification

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#52364]
### Description of Issue
This [doc](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.git.html#salt.states.git.cloned) doesn't require `target` and defaults to `None`. However, it doesn't clarify what happens if you don't specify the target. 

So where does it default download to? 
Does this change from centos OS to ubuntu OS, etc? (I am not including Windows/MacOS in the scope of this question)

#DocumentationLabel #PendingDiscussionLabel

**Comment by garethgreenaway** [comment]
@alan-cugler FYI
```
mylocalrepo:
  git.cloned:
    - name: https://github.com/garethgreenaway/salt-pillar-teset.git
```

```
➜ sudo salt-call --local state.sls test.52364 test=True 
[ERROR   ] Failed to import module saltsupport, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/home/gareth/code/salt/salt/loader.py", line 1555, in _load_module
    mod = imp.load_module(mod_namespace, fn_, fpath, desc)
  File "/home/gareth/code/salt/salt/modules/saltsupport.py", line 44, in <module>
  File "/home/gareth/code/salt/salt/cli/support/collector.py", line 196, in <module>
AttributeError: 'module' object has no attribute 'SaltSupportOptionParser'
[ERROR   ] 'target' argument is required
local:
----------
          ID: mylocalrepo
    Function: git.cloned
        Name: https://github.com/garethgreenaway/salt-pillar-teset.git
      Result: False
     Comment: 'target' argument is required
     Started: 12:39:58.575931
    Duration: 1.749 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.749 ms
```

**Comment by alan-cugler** [comment]
to be clear, we only need to replace `target=None` with `target` to make this doc accurate again correct?

**Comment by garethgreenaway** [comment]
@alan-cugler That doc is generated from the docstring in the code and the function definition, so those would need to be updated.  There is something logic in the code to check to see if the value is None and provide a message if it is.  A simple fix would be to call out that the value is required in the docstring.

**Comment by alan-cugler** [comment]
@garethgreenaway mark me as assignee please, and should I PR this into 2018.3 or develop since its a docstring adjustment outside of a regular .rst file?

**Comment by garethgreenaway** [comment]
@alan-cugler Since it's a bug fix, I think 2018.3 would be a good branch to based a PR on.

**Comment by alan-cugler** [comment]
@garethgreenaway @nixjdm looking at the code, I need to change this for all the git functions correct?
functions to be adjusted:
 - salt.states.git.cloned
 - salt.states.git.detached
 - salt.states.git.latest

They all have the same setup, so I am confident they will all error, just wanted a second opinion before PRing that.

**Comment by alan-cugler** [comment]
tested, all three functions require latest

**Comment by alan-cugler** [comment]
please unassign me from this ticket

**Comment by alan-cugler** [comment]
PR still in place to deal with this issue
