### ISSUE TITLE
set variable dependency in jinja

### ISSUE THREAD

**Issue by msamadzadegan** [saltstack/salt#52367]
Hi
how is it possible to set variable depend to run some module successfully. 
I create partition with mkpart, after that set a list of block device with partition.blkid, but new partition doesn't exist in list.
I think set variable done when creating partition unfinished.
Thanks

**Comment by garethgreenaway** [comment]
@msamadzadegan Thanks for the report.  Can you provide an example of a state file that you're using currently and how you're calling the various parts of Salt to accomplish your goal?  That will give us a better understanding of what you're trying to do and what isn't working.

**Comment by msamadzadegan** [comment]
Thank @garethgreenaway, I need dynamic data that I found this can not be done with jinja, because at first jinja statements run. #44778 this case announced.
I write a code to scan all disk of system, check size of all mount points that supply with pillar and then create/extend required partition, PVs, VGs and LVs. but after create each partition I need to compare list of existence partition with new list to find new partition. A sample code like:

{% set sys_disks = salt['partition.get_block_device']() %}

{% set list_exist_part = salt['disk.blkid']() %}
    list_exist:
      cmd.run:
        - name: "echo 'exist: {{ list_exist_part }}'"
{% set list_sd_exist = [] %}
{% for item in list_exist_part %}
  {% if "/dev/sd" in item %}
    {% do list_sd_exist.append(item) %}
    show_{{ item }}:
      cmd.run:
        - name: "echo 'item: {{ item }}'"
  {% endif %}
{% endfor %}

    create_partition:
      module.run:
        - name: partition.mkpart
        - device: /dev/{{ disk_name }}
        - part_type: primary
        - start: {{ start_part_with_unit }}
        - end: {{ diff_lv_size_without_unit }}kB


    {% set new_list_exist_part = [] %}
    {% for i in disk_name %}
      {% set j = salt['disk.blkid']() %}
      {% do new_list_exist_part.append(j) %}
    {% endfor %}
    show_new_list:
      cmd.run:
        - name: "echo 'list: {{ new_list_exist_part }}'"
    {% for item in new_list_exist_part %}
      {% if item not in list_sd_exist %}
       do somethine 
     {% endif %}
    {% endfor %} {# find new sd partition in new list #}

I try done all my code with python, but I think this requirement must be support by jinja
