### ISSUE TITLE
Port Junos-related bug fixes from develop to 2019.2

### ISSUE THREAD

**Issue by rsmekala** [saltstack/salt#52391]
### Description of Issue/Question
Following are the issues in current Junos modules, states and proxy.

1. junos.install_config state always reports success even if config.load fails Juniper/salt#41.
2. Add exception handling in Junos proxy to handle device connect errors Juniper/salt#56
3. junos os_install with no_copy broken Juniper/salt#38
4. Commit happens on vSRX cluster but with out=false Juniper/salt#47
5. junos-execution-module should return success of or fail in "result" field and not in "out" field Juniper/salt#60
6. dev_timeout is defined in doc but not implemented Juniper/salt#69
7. add dry-run with junos modules. Juniper/salt#44

@dwoz These fixes are already merged into develop, but will need to port it to 2019.2 branch. I will raise an MR by EOD tommorow

**Comment by KChandrashekhar** [comment]
Closing this as merge is done.
