### ISSUE TITLE
Minions fail to return with message signing turned on.

### ISSUE THREAD

**Issue by Church-** [saltstack/salt#52390]
### Description of Issue/Question
When running a highstate on a minion or series of minions it fails to return, only returning " Minion did not return. [No response]" per each minion.
### Setup
Have triggered this with a top.sls that contains at least 7 to 8 states under the base env.
### Steps to Reproduce Issue
```
sudo salt '*' state.highstate
```
Note that this works for some odd reason:
```
sudo salt '*' cmd.run 'salt-call state.highstate -l debug'
```
### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.1
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by frogunder** [comment]
Thanks for the report but I am unable to replicate it.

Do you have a lot going on in the sls files? maybe it just need a little more time to run?
You can try to run the command with `-t60` to allow extra time for the command to finish and see if that helps. 

`salt '*' state.highstate -t60`

**Comment by Church-** [comment]
@frogunder It might just be a timeout issue. I've tried with a timeout of 30 but maybe 60 will work. If not I'll clean up my states of work data and publish a repo to test with.

**Comment by Church-** [comment]
@frogunder So still got an error message with a timeout of sixty, let me clean my states up and place them in a repo to link.

**Comment by Church-** [comment]
@frogunder So the states are stored on a keyfile authed gitfs, a pared down state repo is located at: https://github.com/Church-/test_saltstack_states_repo that should hopefully help repo this issue.

**Comment by frogunder** [comment]
@Church- Thank you, I will take a look at this later today or tomorrow.

**Comment by Church-** [comment]
Not a problem, glad to help!

**Comment by frogunder** [comment]
I still have not been able to replicate this, maybe someone at @saltstack/team-core can take a look when they have time?

Thanks.

**Comment by Church-** [comment]
@frogunder Thanks for taking a look. Maybe it's from also using key signing and forcing messages to drop as well? Going to attempt to replicate this further on a fresh install.

**Comment by waynew** [comment]
@Church- any updates on this?

**Comment by Church-** [comment]
@waynew So far none, problem continues to persist. I can only assume it's due to having message signing turned on and drop message if verification fails turned on.

**Comment by waynew** [comment]
Could you share the (relevant?) parts of your config?

**Comment by Church-** [comment]
@waynew Hey Wayne,

So minimal minion config to repro this is:
----------------------------------------
always_verify_signature: true
hash_type: sha256
id: INSERT_HERE
log_level: warn
master: INSERT_HERE
master_finger: INSERT_HERE
master_sign_key_name: master_sign
minion_sign_messages: true
open_mode: false
permissive_pki_access: false
verify_master_pubkey_sign: true

Minimal master config is:
-----------------------------------
master_sign_pubkey: True
sign_pub_messages: True
require_minion_sign_messages: True
drop_messages_signature_fail: True
fileserver_backend:
  - git

gitfs_provider: pygit2
gitfs_user: 'git'
gitfs_pubkey: '/etc/salt/salt_git_key.pub'
gitfs_privkey: '/etc/salt/salt_git_key'
gitfs_remotes:
  - ssh://git@hack.in.DOMAIN.io/source/salt.git
  - ssh://git@hack.in.DOMAIN.io/source/salt-macros.git
gitfs_refspecs:
  - '+refs/heads/*:refs/remotes/origin/*'
ext_pillar:
  - git:
    - master ssh://git@hack.in.DOMAIN.io/source/salt-pillar.git:
      - env: base
pillar_gitfs_ssl_verify: True
git_pillar_provider: pygit2
git_pillar_user: 'git'
git_pillar_pubkey: '/etc/salt/salt_git_key.pub'
git_pillar_privkey: '/etc/salt/salt_git_key'
git_pillar_refspecs:
  - '+refs/heads/*:refs/remotes/origin/*'

Noticed messages not being verified and being dropped on state.applys using states that contained either macros, templating, or both.

**Comment by Church-** [comment]
Can also add, I tried being aggressive with timeouts for individual states, using timeouts in a range of a minute to 10 minutes. That didn't help, so I'm reasonably certain it's the message being dropped.

**Comment by Church-** [comment]
@here Was anyone able to repro this with the above added info?

**Comment by waynew** [comment]
@Church- I haven't been able to yet - it's possible that there's an issue related to the git backend that's triggering the problem. I haven't been able to  test with the git backend. But with the rest of the settings, everything seems to work just fine :suspect:

**Comment by Church-** [comment]
Hmm... that's odd. @waynew For further info using pub key auth with pygit2 for git auth. And the git repo is hosted on a phabricator based setup.
