### ISSUE TITLE
Can We Deploy Our Own Executors?

### ISSUE THREAD

**Issue by qcpeter** [saltstack/salt#52410]
### Description of Issue/Question
We are using to manage a compute cluster, there are various salt states and modules that should only be run when there are no jobs running as they may restart services which jobs may need. We'd like to have an executor that can test whether it is "safe" to run i.e. that there are no jobs also potentially to disable the host in the scheduler, wait for all running jobs to complete, run the salt function and then re-enable the host in the scheduler. Our scheduling system is somewhat bespoke so I'm afraid this isn't something that would be useful to the wider salt community.

Whilst there is [documentation](https://docs.saltstack.com/en/latest/ref/executors/index.html#writing-salt-executors) on how to write a salt executor, there is no support for syncing them from the salt master. Is there any technical reason for this or has it just not been required? Without a sync function is there a way to add an executor in so that the loader will pick it up? We make use of the packaged version of salt. I have experimented with installing the executor file into the executors directory deployed by the package but this didn't seem to have any effect.

Thanks!

**Comment by frogunder** [comment]
@saltstack/team-core Can you help answer this question? Thanks.

**Comment by max-arnold** [comment]
Yes, you can, but only in Salt Neon (develop branch), which is too far from being released.

Thomas @thatch45 said it could potentially be backported: https://github.com/saltstack/salt/pull/51427#issuecomment-460764366

**Comment by qcpeter** [comment]
Hi @max-arnold,

Thanks for the response but I think you may be misunderstanding the problem, the conflicts aren't with salt jobs/states but with jobs issued by our job scheduler that may be consuming services that salt is managing. These jobs may take multiple hours of compute time and be part of a dependency tree with other jobs so causing them to fail can be a real problem in terms of wasted time. The idea for the executor is to ensure that a salt function can only be run once all of these compute jobs have completed. Currently I'm getting similar functionality for states by wrapping them in other states, but this is not particularly reliable.

Without the Neon release and the built in support for deploying them is there a way I can manually add executors to be picked up by Salt's loader?

Thanks,

Peter

**Comment by max-arnold** [comment]
@qcpeter You can grab the patch from the PR mentioned above, apply the necessary changes to `salt/modules/saltutil.py` and `salt/states/saltutil.py` (on top of your Salt version) and put these patched modules into the`_modules` and `_states` dirs correspondingly.

Then you can run `saltutil.sync_all` and these patched modules should override packaged ones (no need to patch your Salt install).

Then you will be able to add custom executors to the `_executors` dir and sync them via `saltutil.sync_executors`.  Do not forget to remove modules after you upgrade your infra to Salt Neon (otherwise you can miss other changes).

**Comment by qcpeter** [comment]
Excellent! Thanks for the help!

**Comment by max-arnold** [comment]
Another idea is to use the [minion blackout feature](https://docs.saltstack.com/en/latest/topics/blackout/). You can add the blackout grain via `salt-call` from your job scheduler and then remove it after the job finishes.

**Comment by qcpeter** [comment]
Ah I wasn't aware of that, but the issue is unless we take action (as part of the salt command) to disable the host so that no more jobs are started on it we could be waiting indefinitely for an opening. Also the documentation you've linked seems to indicate that minion blackout is done via pillar data rather than grains?

**Comment by max-arnold** [comment]
Blackout via grains seems to be undocumented: #45108. Found here: https://pimiento.github.io/salt_blackout.html
