### ISSUE TITLE
Support provider-managed auto-scaling

### ISSUE THREAD

**Issue by extesy** [saltstack/salt#5241]
From this thread: https://groups.google.com/d/topic/salt-users/xt0rMWYzspA/discussion

Amazon's auto-scaling is very powerful and provides additional cost benefit of using very cheap spot instances. These instances spin up and down quite often which makes whole inventory very dynamic.

Salt currently doesn't support scenarios when inventory is controlled by cloud provider and not Salt itself - there is no official way of automatically supplying new preseeded key for a fresh instance.

**Comment by chdeliens** [comment]
For what it's worth, I'm using the "ec2-autoscale" [Salt Reactor](https://github.com/saltstack-formulas/ec2-autoscale-reactor) and it works well. As soon as the AutoScale group is adding an instance, a SNS notification is triggered to my SaltStack server, and salt-cloud is provisioning the booted instance (preseeding with an accepted key). 

I'm just running into an issue now where only the last provider configuration is taken into account (cloud.create runner doesn't run at all for other providers). Guess I'll open a separate issue for this once I've done some more testing to pinpoint the issue.

Hope this helps!

**Comment by thedrow** [comment]
Should we force the user to use SNS if salt already has an events system?

@basepi As @ryan-lane said on #19302 all functionality that salt cloud exposes should come from salt modules.
