### ISSUE TITLE
re-frame faq question

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#52418]
### Description of Issue/Question
In [this](https://github.com/saltstack/salt/blob/develop/doc/faq.rst#when-i-run-testping-why-dont-the-minions-that-arent-responding-return-anything-returning-false-would-be-helpful) question the answer talks about `salt -v \* test.ping` to get the "Minion did not return" response. This is now standard response without `-v` right? Which means the question can be entirely removed.

However some of the later answers below are top notch facts and info in response to the outdated question. I would like to preserve those, but IDK how I would go about doing that. suggestions?

The valuable text to be preserved:
```
Another option is to use the :mod:`manage.down <salt.runners.manage.down>`
runner:

.. code-block:: bash

    salt-run manage.down

Also, if the Master is under heavy load, it is possible that the CLI will exit
without displaying return data for all targeted Minions. However, this doesn't
mean that the Minions did not return; this only means that the Salt CLI timed
out waiting for a response. Minions will still send their return data back to
the Master once the job completes. If any expected Minions are missing from the
CLI output, the :mod:`jobs.list_jobs <salt.runners.jobs.list_jobs>` runner can
be used to show the job IDs of the jobs that have been run, and the
:mod:`jobs.lookup_jid <salt.runners.jobs.lookup_jid>` runner can be used to get
the return data for that job.

.. code-block:: bash

    salt-run jobs.list_jobs
    salt-run jobs.lookup_jid 20130916125524463507

If you find that you are often missing Minion return data on the CLI, only to
find it with the jobs runners, then this may be a sign that the
:conf_master:`worker_threads` value may need to be increased in the master
config file. Additionally, running your Salt CLI commands with the ``-t``
option will make Salt wait longer for the return data before the CLI command
exits. For instance, the below command will wait up to 60 seconds for the
Minions to return:

.. code-block:: bash

    salt -t 60 '*' test.ping
```

**Comment by frogunder** [comment]
@alan-cugler Thank you for your report.

You are right, `-v` can be removed.

You could for example do something like:

Rephrase the topic title to emphasis why a user would not get returns.
And change that section, that you will get `minion did not return` if it doesn’t respond in time or if the minion is down.

Thanks.

**Comment by alan-cugler** [comment]
go ahead and assign me, and I'll get a PR in.

**Comment by alan-cugler** [comment]
please unassign me from this ticket
