### ISSUE TITLE
Salt 2018.3 has a broken rpm python-msgpack-0.4.6-1.el7.x86_64.rpm

### ISSUE THREAD

**Issue by joen1** [saltstack/salt#52428]
### Description of Issue/Question
The rpm python-msgpack-0.4.6-1.el7.x86_64.rpm is broken. A yum install of the minion fails with Package does not match intended download. A d/l and rpm-i of the rpm also fails as the file is not detected as an rpm.  I was able to get around this but d/l a working version of the rpm from the 2017.7 directory. 

### Setup
This was noticed on centos 7.5 but I suspect you will see the issue on every rpm based OS.

### Steps to Reproduce Issue
rpm -i or yum install 
### Versions Report
2018.3

**Comment by Ch3LL** [comment]
can you point me to the exact url of the package you are having issues with? I cannot replicate this behavior. thanks
