### ISSUE TITLE
sdb-stored config changes are not effective on extpillars

### ISSUE THREAD

**Issue by alexntt** [saltstack/salt#52422]
### Description of Issue/Question

We have a configuration setting pointing to SDB.

If we update SDB, running config.get via the CLI shows the updated value, but this change is not effective when doing config.get within an external pillar.

We see some "lazy loading" debug log messages, so we don't know if this behavior is expected, or if any magic cache/refresh operation can be used to force the update.

edit: if we restart the salt-master, the changes are reflected in the external pillar.

### Versions Report

```
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core
```

**Comment by frogunder** [comment]
@alexntt Thank you for submitting this issue.

Can you please provide a use-case on how to reproduce your error?
I would like to try and replicate it to see what is going on, I am not sure if your issue is excepted behavior or not.

Thanks.

**Comment by alexntt** [comment]
Hi,

Our use case is that we have some runners/pillars/etc. which communicate with external systems via a APIs; we store the credentials in SDB and make them available to code via the configuration (so they can do config.get and retrieve endpoints, credentials, etc.).

We have implemented some runners to update encrypted values on the SDB so for instance in case of API credentials which need to be changed (limited lifetimes, etc.) we can do so executing a Salt command which takes care of the encryption, plus the change is (or should be) immediate.

...

As to how to reproduce, if you set up some SDB-backed config:

```
sdb_xxxx:
  driver: yaml
  files:
    - /path/to/xxxx.yaml
  gpg: true

xxxx:
    - user: sdb://sdb_xxxx/user
    - password: sdb://sdb_xxxx/password
```

And implement a runner which does a `config.get` of `xxxx.user`, it should print the value present at startup in `xxxx.yaml` even if you edit it.

**Comment by frogunder** [comment]
Thank you for this information.

@saltstack/team-core Can you take a look at this when you have time? Especially if you know if this looks like expected behavior or not? 

Thanks.
