### ISSUE TITLE
Boto Cloudfront present throttling error

### ISSUE THREAD

**Issue by mlg-mentch** [saltstack/salt#52437]
### Description of Issue/Question
When calling boto_cloudfront.present for a named cloudfront every few calls produces a throttling error. ie. Comment: Error checking distribution xxxxxxx: {u'message': u'An error occurred (Throttling) when calling the ListTagsForResource operation (reached max retries: 4): Rate exceeded', u'aws': {u'message': u'An error occurred (Throttling) when calling the ListTagsForResource operation (reached max retries: 4): Rate exceeded'}}

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
Call boto.cloudfront.present inside state with a valid config.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 13 2018, 12:45:42)
   python-gnupg: 0.3.6
         PyYAML: 3.10
          PyZMQ: 14.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.3
            ZMQ: 4.0.4
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty
```

**Comment by Ch3LL** [comment]
ping @saltstack/team-boto any ideas here?

**Comment by waynew** [comment]
I'm not familiar with this section of the codebase but we probably want to make sure that if it's got a retry section that's it's doing a backoff. My current theory is that we do, and it doesn't 😛

**Comment by waynew** [comment]
Interesting! Looks like boto does (did?) handle the rate limiting: https://github.com/boto/botocore/issues/882

There's no mention of retry count that I can find around https://github.com/saltstack/salt/blob/develop/salt/modules/boto_efs.py#L117 (which, AFAICT is where we're building up the connection). My guess is that it should be possible then to configure this via `~/.aws/` config files.
