### ISSUE TITLE
salt-minion install on centos7 fails 

### ISSUE THREAD

**Issue by nujragan** [saltstack/salt#52446]
### Description of Issue/Question
sudo yum install salt-minion - fails
Error: Package: salt-2019.2.0-1.el7.noarch (salt-py3-latest)
           Requires: python34-markupsafe
Error: Package: salt-2019.2.0-1.el7.noarch (salt-py3-latest)
           Requires: python34-jinja2
Error: Package: salt-2019.2.0-1.el7.noarch (salt-py3-latest)
           Requires: python34-crypto >= 2.6.1
### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
following the steps under https://repo.saltstack.com/#rhel
install epel-release
install rpm
install salt-minion
on centos 7
### Versions Report
latest version 2019.2

**Comment by dmurphy18** [comment]
@nujragan SaltStack Python 3 support for RHEL 7 currently requires EPEL to be installed which has recently changed from a default of Py 3.4 to Py 3.6.

Can you provide the output of 'yum repolist' and the full output of 'salt-call --local test.versions'

Thanks

**Comment by nujragan** [comment]
Repolist
base/7/x86_64  - CentOS-7 - Base  
epel/x8    Extra Packages for Enterprise Linux 7 - x86_64 
extras/7/x86_64 - CentOS-7 - Extras                                                                                          
salt-py3-2018.3/x86_64 -SaltStack 2018.3 Release Channel for Python 3 RHEL/Centos 7                                   
updates/7/x86_64 - CentOS-7 - Updates                

salt-call - will not work as salt-minion is not installed

**Comment by dmurphy18** [comment]
@nujragan I see the problem, and thanks for bring this to SaltStack attention, from my Centos 7.6 with EPEL
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
       python-gnupg: 0.4.3
             PyYAML: 3.11
              PyZMQ: 15.3.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7.6.1810 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-957.10.1.el7.x86_64
             system: Linux
            version: CentOS Linux 7.6.1810 Core
     
[root@ip-10-200-28-36 centos]# 
[root@ip-10-200-28-36 centos]# yum list | grep -i markupsafe
python-markupsafe.x86_64                 0.11-10.el7                     installed
python36-markupsafe.x86_64               0.23-2.el7                      epel   
[root@ip-10-200-28-36 centos]#

python34-markupsafe is no longer available, but from information I saved off on April 2, 2019
python34-markupsafe.x86_64               0.23-1.el7                         epel

There is a PR for migrating from Py 3.4 to Py 3.6 soon to be processed, it's urgency just got raised.
see https://github.com/saltstack/salt-pack-py3/issues/113

**Comment by dmurphy18** [comment]
@nujragan FYI - working on mitigating this issue, should have resolution soon.

**Comment by dmurphy18** [comment]
@nujragan Can you check if this is still an issue with recent point releases now utilizing Python 3.6 on RHEL 7 and no longer requiring EPEL installed

**Comment by dmurphy18** [comment]
@nujragan Can you confirm that this issue is fixed and close the issue unless there is something else related to this matter
