### ISSUE TITLE
integration.cloud.clouds.test_gce.GCETest.test_instance_extra failure

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52449]
### Description of Issue/Question
The test `integration.cloud.clouds.test_gce.GCETest.test_instance_extra` is failing on 2019.2

https://jenkinsci.saltstack.com/job/2019.2/view/Cloud/job/salt-centos-7-py2-cloud/46/testReport/junit/integration.cloud.clouds.test_gce/GCETest/test_instance_extra/

Here is the failure:

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_gce.py", line 128, in test_instance_extra
    self.assertIn(self.INSTANCE_NAME, delete_str)
AssertionError: u'cloud-test-lprpnj' not found in u''
```

**Comment by sagetherage** [comment]
@garethgreenaway assign you, but isn't a release blocker

**Comment by Ch3LL** [comment]
im still seeing this fail repeatedly on python3 but NOT in python2

https://jenkinsci.saltstack.com/job/2019.2.1/view/Cloud/job/salt-centos-7-py3-cloud/7/

**Comment by Ch3LL** [comment]
re-adding as a release blocker.

@garethgreenaway seeing this fail here still fail on python2 as well.

https://jenkinsci.saltstack.com/job/2019.2/view/Cloud/job/salt-centos-7-py2-cloud/73/#showFailuresLink

**Comment by Ch3LL** [comment]
actually this is only failing on 2019.2 not 2019.2.1, so this still needs to stay open but not for 2019.2.1 release

**Comment by Ch3LL** [comment]
duplicate of https://github.com/saltstack/salt/issues/53012
