### ISSUE TITLE
ImportError: No module named backports.ssl_match_hostname

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#52453]
### Description of Issue/Question

I installed the new version of Salt today (2019.2.0).

After working around #51768 I face the next error:

```foohost:
    ----------
    _error:
        Failed to return clean data
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_dcdf8c_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.root_dcdf8c_salt/pyall/salt/scripts.py", line 426, in salt_call
            import salt.cli.call
          File "/var/tmp/.root_dcdf8c_salt/pyall/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/var/tmp/.root_dcdf8c_salt/pyall/salt/cli/caller.py", line 18, in <module>
            import salt.loader
          File "/var/tmp/.root_dcdf8c_salt/pyall/salt/loader.py", line 31, in <module>
            import salt.utils.event
          File "/var/tmp/.root_dcdf8c_salt/pyall/salt/utils/event.py", line 75, in <module>
            import tornado.iostream
          File "/var/tmp/.root_dcdf8c_salt/py2/tornado/iostream.py", line 40, in <module>
            from tornado.netutil import ssl_wrap_socket, ssl_match_hostname, SSLCertificateError, _client_ssl_defaults, _server_ssl_defaults
          File "/var/tmp/.root_dcdf8c_salt/py2/tornado/netutil.py", line 56, in <module>
            import backports.ssl_match_hostname
        ImportError: No module named backports.ssl_match_hostname

```

I had the same error roughly one year ago, and the work-around does still work:

https://serverfault.com/a/911447/90324

Minion: openSUSE 12.3 (Dartmouth) (x86_64)

**Comment by Ch3LL** [comment]
duplicate of https://github.com/saltstack/salt/issues/41020

Can you try the new feature `ssh_ext_alternatives` in 2019.2.0 https://docs.saltstack.com/en/develop/topics/releases/2019.2.0.html#saltssh-major-updates

this would allow you to copy over the  library that you need on the minion.

**Comment by guettli** [comment]
Is there no way to automatically detect an old Python2 version on the minion? For me it is a boolean thing: the old version is supported or it is not supported. I don't see why I should do something to get it supported.

**Comment by Ch3LL** [comment]
im not sure i'm completely following but i think you are saying that salt-ssh should automatically detect if its an older version of python and automatically add those libraries to the tar ball?

The only caveat is you would need that python version installed on the salt-ssh host and salt-ssh would need to know where it is. That could be added into the logic of the `ssh_ext_alternatives` feature.

**Comment by craigafinch** [comment]
@Ch3LL The lack of documentation for the new `ssh_ext_alternatives` feature is blocking this issue and several others.  It appears that you specify an alternative for every single dependency, even if you don't need an alternative for that package. The release notes provide no information about how to install a module or package. How can we learn how to use `ssh_ext_alternatives`?

**Comment by Ch3LL** [comment]
agreed we should add some more documentation around this new feature outside of just the release docs.

> how to install a module or package.

If i'm understanding the question correctly you would just need to install the module like you normally would either via system packages or pip and then point to the path where that library is installed.
