### ISSUE TITLE
integration.runners.test_fileserver.FileserverTest.test_clear_file_list_cache test failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52467]
### Description of Issue/Question
The test `integration.runners.test_fileserver.FileserverTest.test_clear_file_list_cache` is failing on the following:

salt-debian-8-py3, salt-debian-9-py2, salt-fedora-29-py3, salt-ubuntu-1604-py3, salt-ubuntu-1604-py3-transport, salt
-ubuntu-1804-py2, salt-windows-2019-py2

```
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
{u'retcode': 70} != {} - {u'retcode': 70} + {}
................................................................................

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\runners\test_fileserver.py", line 119, in test_clear
_file_list_cache
    self.assertEqual(ret['return'], {})
AssertionError: {u'retcode': 70} != {}
- {u'retcode': 70}
+ {}
```

https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/163/#showFailuresLink

**Comment by waynew** [comment]
Looks like this is failing across the board:

develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/integration.runners.test_fileserver/FileserverTest/test_clear_file_list_cache)
---

{'retcode': 70} != {} - {'retcode': 70} + {}

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\runners\test_fileserver.py", line 119, in test_clear_file_list_cache
    self.assertEqual(ret['return'], {})
AssertionError: {'retcode': 70} != {}
- {'retcode': 70}
+ {}
		
```
