### ISSUE TITLE
integration.modules.test_system test failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52469]
### Description of Issue/Question
The tests:

```
integration.modules.test_system.SystemModuleTest.test_set_system_date_time_utc
integration.modules.test_system.SystemModuleTest.test_set_system_date_time_utcoffset_east
integration.modules.test_system.SystemModuleTest.test_set_system_date_time_utcoffset_west
integration.modules.test_system.SystemModuleTest.test_set_system_time
```

are failing  on salt-debian-8-py3, salt-debian-9-py2, salt-fedora-29-py3, salt-ubuntu-1604-py3, salt-ubuntu-1604-py3-transport, salt
-ubuntu-1804-py2

https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/163/#showFailuresLink

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 10:53:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/217/
