### ISSUE TITLE
unit.utils.test_schema test failure on macosx

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52486]
### Description of Issue/Question
the tests:

```
unit.utils.test_schema.ConfigTestCase.test_anyof_config_validation
unit.utils.test_schema.ConfigTestCase.test_dict_config_validation
unit.utils.test_schema.ConfigTestCase.test_oneof_config_validation
unit.utils.test_schema.ConfigTestCase.test_optional_requirements_config_validation
```

are failing on salt-mac-highsierra-py2, salt-mac-sierra-py2

https://jenkinsci.saltstack.com/job/develop/job/salt-mac-highsierra-py2/122/#showFailuresLink

This was previously failing on linux here: https://github.com/saltstack/salt/issues/51845

So the fix could be similar

**Comment by Ch3LL** [comment]
should be fixed by https://github.com/saltstack/salt/pull/52627 when merged forward.

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 21, 2019 3:20:34 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-2-py2/1/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-1-py2/3/
