### ISSUE TITLE
unit.modules.test_cmdmod.CMDMODTestCase.test_run_cwd_in_combination_with_runas test failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52484]
### Description of Issue/Question
The test `unit.modules.test_cmdmod.CMDMODTestCase.test_run_cwd_in_combination_with_runas` is failing on mac with error:

```
Stacktrace

Traceback (most recent call last):
  File "/testing/tests/unit/modules/test_cmdmod.py", line 360, in test_run_cwd_in_combination_with_runas
    self.assertEqual(stdout, cwd)
AssertionError: u'' != u'/tmp'
+ /tmp
```

https://jenkinsci.saltstack.com/job/develop/job/salt-mac-highsierra-py2/122/testReport/junit/unit.modules.test_cmdmod/CMDMODTestCase/test_run_cwd_in_combination_with_runas/

**Comment by frogunder** [comment]
Closing this issue. It was reported as mac py2 failure, and we don't do py2 tests anymore on develop branch. I cannot see it failing on other branches either.
There also have been done a lot of work on the mac tests since this was reported.
If the error shows up again, we can re-open this issue.
