### ISSUE TITLE
Minion initially works, then stops responding until service restart

### ISSUE THREAD

**Issue by ChaosOrd** [saltstack/salt#52491]
Hello,

We have few dozens of minions and a single master.
Most of minions work fine, but we have encountered connectivity issues in a small subset of them:

After initially being able to respond to commands from master, eventually minion stops responding until restarted. Usually it happens in less then one hour, and often after trying to execute some heavy command, for example saltuti.sync_all.

While being in the unresponsive state, the minion is still capable of executing commands locally using salt-call command. 

The issue looks similar to what happens in #6231. I have tried all suggested solutions in that thread, like upgrading ZMQ version and adding

```
tcp_keepalive: True
tcp_keepalive_idle: 60
```

to configuration, but it does not seem to solve the problem.

Here is an output of `salt-call -l debug test.ping`

[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Loading static grains from /etc/salt/grains
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] "saltstack.trax-cloud.com" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://<master_ip_address>:4506
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'my_minion_id', u'tcp://<master_ip_address>:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (9926)
[DEBUG   ] Setting zmq_reconnect_ivl to '9926ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'my_minion_id', u'tcp://<master_ip_address>:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://<master_ip_address>:4506
[DEBUG   ] Trying to connect to: tcp://<master_ip_address>:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://<master_ip_address>:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'gateway_shufersal_4', u'tcp://<master_ip_address>:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'my_minion_id', u'tcp://<master_ip_address>:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://<master_ip_address>:4506
[DEBUG   ] Trying to connect to: tcp://<master_ip_address>:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded test.ping
[DEBUG   ] test.ping received for minion 'my_minion_id'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'my_minion_id', u'tcp://<master_ip_address>:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'my_minion_id', u'tcp://<master_ip_address>:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://<master_ip_address>:4506
[DEBUG   ] Trying to connect to: tcp://<master_ip_address>:4506
[DEBUG   ] LazyLoaded nested.output

### Versions Report
master:

Salt Version:
           Salt: 2018.3.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: 3.6.0
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 0.9.1
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.6 (default, Nov 13 2018, 12:45:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.3.1
 
System Versions:
           dist: Ubuntu 14.04 trusty
         locale: UTF-8
        machine: x86_64
        release: 3.13.0-74-generic
         system: Linux
        version: Ubuntu 14.04 trusty

minion:

Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 3.6.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.3.13
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.3.1
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.10.0-42-generic
         system: Linux
        version: Ubuntu 16.04 xenial

Will appreciate any help
Thank you

**Comment by Ch3LL** [comment]
is there any difference with the minions that are disconnecting? Are they in a separate network? Different versions of zmq or salt? etc.

when the minion drops is there anything in the minion or master debug logs when it disconnects?

We try to make sure masters can be a lower version but its not fully supported or recommended . Is it possible to upgrade the master to 2018.3.4 as well? Or downgrade your minion to 2018.3.3

**Comment by ChaosOrd** [comment]
Thanks @Ch3LL ,

I could not upgrade the master version but to test the newer version, I have reassigned the minion to a different master which runs 2018.3.4  version, and it seems to resolve the issue. 

Thank you again for your help

**Comment by Ch3LL** [comment]
no problem :) i did go ahead and tested having a 2018.3.3 master and 2018.3.4 minion and i haven't been able to replicate the issue. Are you okay to close?

**Comment by ChaosOrd** [comment]
Sure, it's fine to close. Thanks again.

**Comment by zmeggyesi** [comment]
I seem to be running into this on v3000 (or something that presents identical to this one): after about an hour or so "idling", the minion stops responding until the Salt daemon is restarted via SystemD. It still responds to local commands, logs show no abnormality even at the debug level, and it responds to connections just fine (it's running an HTTP server), which makes me think it's not a networking issue.

[Output of salt-call -l debug test.ping](https://github.com/saltstack/salt/files/4275136/local-ping.txt)
[minion-version-report.txt](https://github.com/saltstack/salt/files/4275141/minion-version-report.txt)
[master-version-report.txt](https://github.com/saltstack/salt/files/4275151/master-version-report.txt)
