### ISSUE TITLE
proxy tests are not completing the test run

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52514]
### Description of Issue/Question
All of the proxy tests are not completing the entire test run.  Here is where it stops:

```
16:21:38        20:21:38,824 [pytestsalt.utils                    :118 ][INFO    ] Process ['/usr/bin/python3', '/tmp/salt-tests-tmpdir/scripts/cli_master.py', '-c', '/tmp/salt-tests-tmpdir/config', '-l', 'quiet', 'EventPublisher'] terminated with exit code: None
16:21:38        20:21:38,825 [pytestsalt.utils                    :141 ][INFO    ] Terminating process list. 2nd step. kill: True, slow stop: False
16:21:39        chmod: cannot access '/tmp/coverage.xml': No such file or directory
16:21:39 >>>>>> ------Exception-------
16:21:39 >>>>>> Class: Kitchen::ActionFailed
16:21:39 >>>>>> Message: 1 actions failed.
16:21:39 >>>>>>     Failed to complete #verify action: [SSH exited (1) for command: [sudo -E chmod -R +r /tmp/coverage.xml]] on py3-ubuntu-1604
16:21:39 >>>>>> ----------------------
16:21:39 >>>>>> Please see .kitchen/logs/kitchen.log for more details
16:21:39 >>>>>> Also try running `kitchen diagnose --all` for configuration
16:21:39 Build step 'Execute shell' marked build as failure
```

https://jenkinsci.saltstack.com/job/2019.2/view/Proxy/job/salt-ubuntu-1604-py3-proxy/47/console

**Comment by frogunder** [comment]
The proxy tests are now running and passing on 2019.2.1.

The issue seems to be related to  in docker py 4.0.0 they dropped support for python3.4 which is the version of python 3 we test on centos-7.

**Comment by frogunder** [comment]
Proxy tests are only failing on develop and 2019.2.
The other branches are good.

**Comment by frogunder** [comment]
This is passing on develop. Still failing on 2019.2 but I believe that is only because that branch has not switched to nox yet.

**Comment by waynew** [comment]
Looks like it's finishing now. It's failing, but, finishing. I guess I'd say we can close this for now.
