### ISSUE TITLE
directory tree manipulation with _syspaths.py variables

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#52515]
### Question
- Is there an orchestration specific variable for setting its directory like there is for most parts of salt?
- is the below variable manipulation going to internally break salts pathing when using orchestration, sls files, and pillars?
### Current setup:
```
/srv/
   ├── pillar/
   │    ├── top.sls
   │    └── ssh.sls
   └── salt/
        ├── top.sls
        ├── nano.sls
        ├── github/
        │    └── init.sls
        ├── nginx/
        │    ├── init.sls
        │    └── adjustment.sh
        └── orch/
             ├── cluster_cloud.sls
             └── cluster_destroy.sls
```
So I can set some variables in _syspaths.py
- `base_pillar_roots_dir` for the pillars directory
- `base_file_roots_dir` for the sls & orch
### Wanted outcome:
```
/srv/salt/
      ├── pillar/
      │    ├── top.sls
      │    └── ssh.sls
      ├── sls/
      │    ├── top.sls
      │    ├── nano.sls
      │    ├── github/
      │    │    └── init.sls
      │    └── nginx/
      │         ├── init.sls
      │         └── adjustment.sh
      └── orch/
           ├── cluster_cloud.sls
           └── cluster_destroy.sls
```

**Comment by Ch3LL** [comment]
> Is there an orchestration specific variable for setting its directory like there is for most parts of salt?

By directory do you mean where the orchestartion files are stored? Saltstack's orchestration just grabs the files from file_roots. 

> is the below variable manipulation going to internally break salts pathing when using orchestration, sls files, and pillars?

setting these should still work when using orchestration. Are you running into an issue?
