### ISSUE TITLE
virt.purge throws a libvirt exception on Xen hypervisor

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#52547]
### Description of Issue/Question

When running the virt.purge function with a connection to a Xen hypervisor, the following exception is thrown:

> Exception: unsupported flags (0x4) in function libxlDomainUndefineFlags

### Setup

Vanilla salt

### Steps to Reproduce Issue

1. Setup a salt minion as a Xen hypervisor with one vm.
1. Run `virt.purge testvm` on that minion

### Versions Report

Fluorine is on master and minion

**Comment by cbosdo** [comment]
Would be fixed by commit 29a44ac

**Comment by cbosdo** [comment]
@s0undt3ch I verified that the commit fixes the issue before submitting the PR and I was the reporter. I think we can consider this verified unless you want someone else to do the verification

**Comment by DmitryKuzmenko** [comment]
Since this is fixed I'm closing this issue. Please reopen if there's any unfinished work.
