### ISSUE TITLE
Orchestration return incorrect result

### ISSUE THREAD

**Issue by Dejv456** [saltstack/salt#52545]
### Description of Issue/Question
When running salt orchestration, salt.state return false even if job is still running or is finished with "true" (jobs.list_job).

EDIT:
It works ok, when i have interface or bond connected to single network. It always fail after 15s when i add another interface to a different network.

          ID: 1_inst
    Function: salt.state
      Result: False
     Comment: Run failed on minions: minion1
     Started: 06:05:58.712732
    Duration: 15399.438 ms
     Changes:
              minion1:
                  False
...

          ID: post_inst
    Function: salt.state
      Result: False
     Comment: Run failed on minions: minion1
     Started: 06:06:14.119415
    Duration: 2252.798 ms
     Changes:
              minion1:
                  Data failed to compile:
              ----------
                  The function "state.sls" is running as PID 6184 and was started at 2019, Apr 15 06:05:58.898131 with jid 20190415060558898131

### Versions Report
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.5 (default, Apr 05 2018, 13:30:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-25.25-default
         system: Linux
        version: Not Installed

**Comment by Dejv456** [comment]
I tried to upgrade to 2019.2.0 (Fluorine), but still the same behauviour.

Adding "- timeout: 300" parameter to salt.state fixed the problem.

**Comment by DmitryKuzmenko** [comment]
@Dejv456 some questions just to be sure I understand the problem correctly:
1. Did that work before? Or it's first time you're trying to get Salt work in that configuration.
2. Do you set the master's `interface` config option to something non-default? By default it's `0.0.0.0`
3. Are both interfaces ipv4?
4. Can you ping your `minion` from master's host?
5. Do you start master after you've added the second interface?

**Comment by DmitryKuzmenko** [comment]
And sorry for the response delay. I'll try to be more operative next time.

**Comment by Dejv456** [comment]
1. First time.
2. I'll try that. I have only master IP address in minion's config file.
3. Yes.
4. Yes.
5. I not sure if a restarted service, i'll try it.

**Comment by Dejv456** [comment]
Update:
2. Nothing, again 15s and false result.
5. I've restarted service after adding second interface with same result as above.
