### ISSUE TITLE
The Returned Format of Python Client API

### ISSUE THREAD

**Issue by batilei** [saltstack/salt#52558]
### Description of Issue/Question
Is there any official document describing the format of python client API's returned result?  As you can see after I run the` local.cmd`, the returned result has so much information. I can't find any guideline how to parse the returned result.  It seems the result is composed of dict{key1:list1[dict],...}. I think the key1 is the  minion name, then how about list1( I guess each item in the list is the result of each command)? And is there any single field in the returned result  indicating whether the state.apply succeeded or not?  And lastly, can we make the return result doesn't use the unicode?

I would like to write a function parse the results, but it would be great if there are some official documents describing what the python client api would return (otherwise if the format of the returned results change from time to time,  our parse code logic would break and need to re-write again). Thank you.

local.cmd('*', 'state.apply', ['test=True'])

`{u'ip-172-31-25-10.us-east-1.compute.internal': {u'file_|-/usr/share/nginx/html/kok_|-/usr/share/nginx/html/kok_|-directory': {u'comment': u'The directory /usr/share/nginx/html/kok is in the correct state', u'pchanges': {}, u'name': u'/usr/share/nginx/html/kok', u'start_time': u'01:37:22.899203', u'result': True, u'duration': 0.737, u'__run_num__': 10, u'__sls__': u'kok.ami_creator.pre_installation', u'changes': {}, u'__id__': u'/usr/share/nginx/html/kok'}, u'pkgrepo_|-set_up_telegraf_repo_|-telegraf_|-managed': {u'comment': u"Package repo 'telegraf' already configured", u'name': u'telegraf', u'start_time': u'01:37:26.138098', u'result': True, u'duration': 32.256, u'__run_num__': 98, u'__sls__': u'kok.services.telegraf', u'changes': {}, u'__id__': u'set_up_telegraf_repo'},............`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by DmitryKuzmenko** [comment]
@team-core maybe anybody have a better answer but mine one is the following.
@batilei we have no strong template for the return data. I'm not sure where to get that information in docs. The best way to find useful user experience is to ask your question in salt-user google group https://groups.google.com/forum/#!forum/salt-users
