### ISSUE TITLE
Wrong schema for mysql returner

### ISSUE THREAD

**Issue by mattLLVW** [saltstack/salt#52554]
### Description of Issue/Question
The current schema for salt.returners.mysql raises an error:
`ERROR 1061 (42000): Duplicate key name 'jid'`
 because `jid` is already a BTREE index.

### Steps to Reproduce Issue
Insert the mysql schema provided in the [docs](https://docs.saltstack.com/en/latest/ref/returners/all/salt.returners.mysql.html). 

I think removing `CREATE INDEX jid ON jids(jid) USING BTREE;` should do the trick since `UNIQUE` constraint makes `jid` a BTREE index.

**Comment by s0undt3ch** [comment]
Hello @mattLLVW !
Thanks for reporting this issue.

Can we get a `--versions-report` from the setup where this issue is triggered please?

**Comment by mattLLVW** [comment]
Sure, if you want, but i don't see the point, the problem is not in salt code, it's in the docs for Mysql returner.
Specifically :

```
35201fc8dae salt/returners/mysql.py        (Mike Place          2015-03-31 11:18:56 -0600  81)     CREATE INDEX jid ON jids(jid) USING BTREE;
```

**Comment by mattLLVW** [comment]
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.8 
         locale: UTF-8
        machine: x86_64
        release: 5.0.6-200.fc29.x86_64
         system: Linux
        version: debian 9.8 
```

**Comment by s0undt3ch** [comment]
Thank You.
This will allow us to fix the docs on the right branch.

**Comment by mattLLVW** [comment]
hey @Ch3LL , it's not blocked, and there's no info needed. I can submit a PR i needed.
