### ISSUE TITLE
Can you set a data disk to be created for a Linode via the mapfile in salt cloud?

### ISSUE THREAD

**Issue by Church-** [saltstack/salt#52569]
Less an issue and more a general question on salt-cloud and mapfiles I haven't been able to find a sufficient answer on. 

Via (https://docs.saltstack.com/en/latest/ref/clouds/all/salt.cloud.clouds.linode.html) I know that you can create a data disk to attach to a linode via .create_data_disk(). But is there a way to specify this for an instance you're creating via a mapfile? Ideally I'd like to deploy an instance and have the data disk attached before executing any states as they depend on their being a volume attached already.

**Comment by s0undt3ch** [comment]
@saltstack/team-cloud any useful input here?

**Comment by gtmanfred** [comment]
It does not look like the boot command passes anything that could specify a data disk

https://github.com/saltstack/salt/blob/2019.2/salt/cloud/clouds/linode.py#L467-L480

You would need to do it after the fact, using the cloud.action state.

**Comment by DmitryKuzmenko** [comment]
@Church- is you question answered? Could we close this issue?
