### ISSUE TITLE
Problem with -t parameter

### ISSUE THREAD

**Issue by dbagan13** [saltstack/salt#52579]
### Description of Issue/Question
I'm running SaltStack from a python program, and everything seemed to work properly, but I'm having problems with the timeout (-t) parameter.
If I run from the CLI _salt minion01 status.uptime -t 5_, the command works properly.
If I run from the python program without timeout _local.cmd( 'minion01', 'status.uptime' )_, it also works.
But if I add the opcion _-t_ in the python program _local.cmd( 'minion01', 'status.uptime' , '-t', timeout)_, where timeout is an integer:
     - If the master can't find the minion, the timeout is correctly executed.
     - If the minion is correctly connected, the response is the following error:
_Passed invalid arguments to status.uptime: uptime() takes no arguments (4 given)_

I guess I'm doing something wrong, but I don't know how to pass the timeout parameter.
Could you help me?
Thanks.

### Steps to Reproduce Issue
local.cmd( 'minion01', 'status.uptime' , '-t', timeout)

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: 2.5.1
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-47-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by lukasraska** [comment]
The -t parameter should be passed to salt command, but as you're using LocalClient, it assumes the parameters are for the function instead.

LocalClient itself has kwarg timeout, can you try using it? Like this:

local.cmd( 'minion01', 'status.uptime', timeout=timeout)

**Comment by dbagan13** [comment]
Thanks you! It works!

**Comment by dbagan13** [comment]
Thanks you! It works!
