### ISSUE TITLE
Testing support for Amazon Linux 2 Python 2 and Python 3

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#52584]
### Description of Issue/Question
Need to start testing Amazon Linux 2 for both Python 2 (even though it is a clone of RHEL 7, it is not a full clone) and Python 3.  Amazon Linux 2 Python 3 support is currently Py 3.7, whereas RHEL 7 is Py 3.6 with EPEL.  Hence need to test Python 3 support on Amazon Linux 2 separately.

Note it is close but will have a point release for Python 3 support on Amazon Linux 2 with Salt 2019.2.1.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by s0undt3ch** [comment]
Refs:
* https://github.com/saltstack/salt-jenkins/pull/1400

**Comment by s0undt3ch** [comment]
Golden Images Created and Jenkins Jobs Added.
