### ISSUE TITLE
Prep for testing support for RHEL 8 Python 3

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#52586]
### Description of Issue/Question
Need to add RHEL 8 to the test matrix for Python 3.  Currently aiming to only package for Python 3 on RHEL 8

This issue is such that the matter is not forgotten.

Also test the boot script to make sure it works on this new OS.

**Comment by bryceml** [comment]
https://github.com/saltstack/salt/pull/55307

**Comment by bryceml** [comment]
This is done.
