### ISSUE TITLE
Prep for testing support for Debian 10 (Buster) Python 3

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#52585]
### Description of Issue/Question
Need to add Debian 10 (Buster) to the test matrix for Python 3.  Currently aiming to only package for Python 3 on Buster. The Debian 10 release should be some time this summer, the  Debian 10 installer has just released RC1.

This issue is such that the matter is not forgotten.

Also test the boot script to make sure it works on this new OS.

**Comment by spirritus** [comment]
The 2019.2 version of salt-common (py3) depends on python3-tornado.
The current debian 10 lists TWO lines for that dependency:

--python3-tornado (<5) (UNAVAILABLE)
--python3-tornado (>=4.2.15)

Even if you install the 4.2.15 version manualy the installer (aptitude) will not let you install salt-common due to unmet dependencies. As a human you clearly see that 4.2.15 is smaller than 5. However, the installer does not care ...

**Comment by mickenordin** [comment]
It seems that the version of python3-tornado in buster is 5.1.1-4 which is greater than 5, does anyone know what the problem with tornado greater than 5 is for saltstack?

https://packages.debian.org/buster/python3-tornado

**Comment by plinkable** [comment]
Buster provides a python3-tornado4 package that could be used for a new dependency, but I don't think the current package will accept that without modification.

**Comment by dmurphy18** [comment]
@mickenordin @plinkable Plan is to make use of tornado4 that comes with Buster until such time that Salt is correctly functioning with Tornado > 5 on Python 3.  The issue there is with the use of ioloop and the changes made to it in Tornado > 5. Solution is almost there, just a few corner cases left to resolve and work interrupted by the the need to tighten testing to get point release 2019.2.1 done.

**Comment by mickenordin** [comment]
How is the progress with this? Will 2019.2.1 be released soon?

**Comment by Svolentin** [comment]
```
aptitude install salt-minion salt-common
Warning: Invalid locale (please review locale settings, this might lead to problems later):
  locale::facet::_S_create_c_locale name not valid
The following NEW packages will be installed:
  dctrl-tools{a} libnorm1{a} libpgm-5.2-0{a} libsodium23{a} libzmq5{a} python3-crypto{a} python3-dateutil{a} python3-msgpack{a} python3-psutil{a} python3-systemd{a} 
  python3-tornado{a} python3-zmq{a} salt-common{b} salt-minion 
The following packages are RECOMMENDED but will NOT be installed:
  debconf-utils python3-croniter 
0 packages upgraded, 14 newly installed, 0 to remove and 0 not upgraded.
Need to get 8577 kB of archives. After unpacking 38.4 MB will be used.
The following packages have unmet dependencies:
 salt-common : Depends: python3-tornado (< 5) but 5.1.1-4 is to be installed
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     salt-common [Not Installed]                        
2)     salt-minion [Not Installed]                        



Accept this solution? [Y/n/q/?] 
```

**Comment by bryceml** [comment]
@Svolentin what repo are you pointing to?  you should be pointing to https://s3.repo.saltstack.com/py3/debian/10/amd64/latest/, so something like 
```
deb [arch=amd64] https://repo.saltstack.com/py3/debian/10/amd64/latest buster main
```
should be in your apt sources

debian 10 support is completely added.
