### ISSUE TITLE
Incorrect links in 2019.2 and Develop documentation

### ISSUE THREAD

**Issue by vosscodes** [saltstack/salt#52643]
### Description of Issue/Question
In the 2019.2 and develop docs, links to the Python std types for more parameters have been added in `states.pkg` docs, but links for the `list` type all point to the list function of the Ansiblegate module instead of the Python docs.

The other types on this page all seem to be correct. I didn't see any links to this on other pages, but only checked a few as I didn't see quick way to search/sed the docs content.

### Steps to Reproduce Issue
Links to `(list)` are broken: `pkgs, names, sources, ignore_types, verify_options`
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pkg.html#salt.states.pkg.installed

Pointing to:
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.ansiblegate.html#salt.modules.ansiblegate.list

Should point to:
https://docs.python.org/3/library/stdtypes.html#list

**Comment by Ch3LL** [comment]
nice find. Any chance you want to give it a go at a PR to fix this?

**Comment by snlnspc** [comment]
sure, but I'm actually not sure where this one is coming from! these links seem to be generated by sphinx, but when building the docs myself I am getting the correct links. see:

```html
<li><p><strong>ignore_types</strong> (<a class="reference external" href="https://docs.python.org/3/library/stdtypes.html#list" title="(in Python v3.7)"><em>list</em></a>) – <p>List of types to ignore when verifying the package</p>
```

I'd love to help if you can point me some kind of direction here

**Comment by vosscodes** [comment]
sure, but I'm actually not sure where this one is coming from! these links seem to be generated by sphinx, but when building the docs myself I am getting the correct links. see:

```html
<li><p><strong>ignore_types</strong> (<a class="reference external" href="https://docs.python.org/3/library/stdtypes.html#list" title="(in Python v3.7)"><em>list</em></a>) – <p>List of types to ignore when verifying the package</p>
```

I'd love to help if you can point me some kind of direction here

**Comment by Ch3LL** [comment]
ahh interesting. what version of sphinx are you building on? We are working on trying to start build sphinx on the latest version. i wonder if this will resolve this issue.

**Comment by vosscodes** [comment]
I had a sec to look for other instances of this over the weekend:

loader.py in the py client api
modules/cmdmod.py
pillar/csvpillar.py
modules/win_task.py has `:param list $var:` which generates (list) but is not linked

I'm seeing the correct links building from develop on Manjaro. 
python2 2.7.16-1
python2-sphinx 1.8.5-2

Site note, are the [development docs](https://docs.saltstack.com/en/latest/topics/development/hacking.html) on building with py3 still relevant? I saw no issues/bad links
python 3.7.3-1
python-sphinx 2.0.1-1

If they are, I would recommend adding something to the [writing/building documentation](https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html) as well

**Comment by Ch3LL** [comment]
to clarify @vosscodes you are stating that develop docs work on both python2 and python3?

Also can you quote exactly what portion of the development docs you are refering to. Maybe add the quote here? i'm not certain what portion you are referring to.

**Comment by vosscodes** [comment]
Sorry, I must've snipped out the anchor tags somehow

Yep, I was able to build the docs on python 3 as well just fine. The [editing documentation](https://docs.saltstack.com/en/latest/topics/development/hacking.html#editing-and-previewing-the-documentation) section has a note for building on Arch where py3 is the default:

>  To build the docs on Arch Linux, the python2-sphinx package is required. Additionally, it is necessary to tell make where to find the proper sphinx-build binary, like so:
>
> make SPHINXBUILD=sphinx-build2 html

I didn't notice this at first while looking at the [building the docs](https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html#building-the-documentation) section here, which only has a python 2 vs python 3 note about the built in http server

**Comment by Ch3LL** [comment]
thanks for all of the clarifications. I do know there are other issues with building with python3 related to missing headers , so I think once we figure out all of those issures then we could remove that entry from the docs. I am hoping our work to migrate to building the docs in production with python3 will solve this issue your are specifying. ping @bryceml i know you are doing this migration path, before we migrate to python3 can you verify these issues are resolved? If not i can dive into them.

**Comment by bryceml** [comment]
I was looking at this and I think the upgrade to sphinx 2.0.1 with python3 have fixed it.  I looked at the pages mentioned and they seem to be pointing to the right place now.
see the relevant code:
https://github.com/saltstack/builddocs/blob/master/build_env.sh
https://github.com/saltstack/builddocs/blob/master/build_html.sh
