### ISSUE TITLE
DDNS Module logging is subpar

### ISSUE THREAD

**Issue by DeForce** [saltstack/salt#52648]
### Description of Issue/Question
Debugging DDNS module is meaning going to source code and go line by line on what happens. There is no logging implemented for it, so it's really not easy to debug what is happening and what is wrong.

No logging whatsoever, only thing that is happening is a return boolean (True, False, None)

**Comment by DeForce** [comment]
I have created PR #52649 to address this issue.

**Comment by Ch3LL** [comment]
thanks for the PR! that will be a great improvement :)
