### ISSUE TITLE
[2019.2.1] Multimaster Failover Error if both masters go down.

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#52658]
### Description of Issue/Question
In 2019.2.1, in a multimaster failover setup, if both masters go down, minions will be disconnected with this error ` [ERROR   ] No master could be reached or all masters denied the minion's connection attempt.`

### Setup
Install 2019.2.1 and config multimaster failover setup. I used 2 master and 2 minions.

Minion config:
```
master:
  - 192.237.244.61
  - 192.237.244.153

id: minion_B





master_shuffle: True
master_type: failover
master_alive_interval: 30
```
### Steps to Reproduce Issue
Run cmd from masters, then stop/kill both masters and minions will stopp trying to connect to masters.
```
[DEBUG   ] Trying to connect to: tcp://192.237.244.153:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[INFO    ] (u'Master %s could not be reached, trying next next master (if any)', '192.237.244.153')
[WARNING ] Master ip address changed from 192.237.244.153 to 192.237.244.61
[DEBUG   ] Master URI: tcp://192.237.244.61:4506
[DEBUG   ] Initializing new AsyncAuth for (u'/etc/salt/pki/minion', u'minion_B', u'tcp://192.237.244.61:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (2952)
[DEBUG   ] Setting zmq_reconnect_ivl to '2952ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/minion', u'minion_B', u'tcp://192.237.244.61:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://192.237.244.61:4506
[DEBUG   ] Trying to connect to: tcp://192.237.244.61:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Re-init ZMQ socket: Message timed out
[DEBUG   ] Trying to connect to: tcp://192.237.244.61:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[INFO    ] (u'Master %s could not be reached, trying next next master (if any)', '192.237.244.61')
[ERROR   ] No master could be reached or all masters denied the minion's connection attempt.
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0-1389-g4859e6c
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Sep 12 2018, 05:31:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo
```

**Comment by garethgreenaway** [comment]
@frogunder It looks like this is by design per this change by @s0undt3ch (https://github.com/saltstack/salt/commit/52ea848edcae0abc81b6cc0f9a9bb112dda226c8) and that setting master_tries (https://docs.saltstack.com/en/latest/ref/configuration/minion.html#master-tries) to -1 will have the minion indefinitely try.

**Comment by frogunder** [comment]
@garethgreenaway Thanks for looking. Yea that worked fine when using `master_tries: -1`.

One thing though, on `2019.2.0` I do not see this behavior, I mean I do not have to set `master_tries: -1`.
In fact I have never seen this behavior before, and this is one of the tests that are done for every new tag/release we do.

It might just be a new thing and everything is good, that this is all just expected behavior, but just wanted to double check before I close it. (Double check that it is indeed expected behavior :-))

Thanks.

**Comment by garethgreenaway** [comment]
@frogunder Looking at the PR it appears the change went into the develop branch before the 2019.2.0  branch was created.

**Comment by garethgreenaway** [comment]
Closing this one out as it doesn't seem like a bug and the desired behavior can be accomplished with the `master_tries` option.
