### ISSUE TITLE
Feature Request: file.managed verify_ssl option. 

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#52663]
### Description of Issue/Question
Currently, there is not a way of disabling the verification of SSL in `https` sources. This could lead to code breakages while trying to install certs. Or even during the first run before a system is setup fully if using `https` sources 

```
example state:
  file.managed:
    - name: /tmp/file
    - source: https://badcert.url/good/file.crt
    - verify_ssl: False
```

**Comment by whytewolf** [comment]
ZD-3632

**Comment by KChandrashekhar** [comment]
Customer is installing the certs that would be needed for verification using an https source. Hence initially they want to disable ssl verification. 

file.managed has nothing to control anything about ssl. So the request is to introduce something similar to verify_ssl which is in http module (https://docs.saltstack.com/en/latest/topics/tutorials/http.html#ssl-verification) to this module as well.

**Comment by xeacott** [comment]
After initial investigation I believe this should need the following...

1. Add an extra argument to state/file.managed ssl_verification=True and the user would specify False in this case
2. Keep passing the argument along, all the way down to where an HTTP request happens
3. When the request object is made to fulfill the http request, make sure ssl_verification=False gets here so create an unsecure session object

**Comment by xeacott** [comment]
When Sodium gets a little closer, I can investigate this more or support the engineer that takes this on!

**Comment by whytewolf** [comment]
this is not stale
