### ISSUE TITLE
Update documentation to clarify that config files are yaml only.

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#52668]
### Description of Issue/Question
see https://github.com/saltstack/salt/issues/51596.
Need to make clear in documentation that the Salt config files are for yaml use only .

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by awarecheetah** [comment]
@dmurphy18 What exactly is meant by "Salt config files are for yaml use only?"
