### ISSUE TITLE
Minions still get jobs after key is deleted

### ISSUE THREAD

**Issue by pizzapanther** [saltstack/salt#52662]
### Description of Issue/Question

When you delete a minion key there is a small window when the minion still gets jobs. The minion gets jobs until the master key is rotated.

### Setup

1 master and 1 or more minions

### Steps to Reproduce Issue

1. run `salt '*' test.ping`, verify minion executes job successfully
2. delete a minion key
3. run `salt '*' test.ping` again before the master key is rotated, verify the minion still gets the job.
4. wait for master key to rotate and run `test.ping` again, verify job is not received 

### Versions Report
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Mar  5 2019, 16:27:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.1
            ZMQ: 4.1.5

System Versions:
           dist: debian 9.8
         locale: UTF-8
        machine: x86_64
        release: 4.19.16-02893-g2cf2c17c8a43
         system: Linux
        version: debian 9.8
```

**Comment by Ch3LL** [comment]
im having a hard time replicating this. can you verify a couple things for me to help replicate this?

1. > delete a minion key

what command are you running to delete the minion key?

2. how often is your key rotating on your master? the default is 24 hours

3. > verify the minion still gets the job.

how are you verifying this? checking logs? checking event bus? are you actually getting a return from the minion on the master of True?

**Comment by pizzapanther** [comment]
OK this was originally found by running a minion swarm and then I was able to reproduce. I tried again this morning and it didn't work at first. Then I ran two minions on the same machine with different configs and that seems to be the problem. So maybe not a problem? Maybe i need to change something in the config for this to work right?

Video of my session: https://drive.google.com/file/d/18C1UZLCO8mlPyz7kNV7cdcMH6wArrg6Q/view?usp=sharing

**Comment by Ch3LL** [comment]
okay i was able to replicate this when running two minions. Here was my other minion config to make it easier for anyone to replicate:

```
(salt-py2) ➜  salt git:(0ca04ffbeb) cat /etc/salt2/minion
master: localhost
id: minion_2
pidfile: /var/run/salt-minion2.pid
cachedir: /var/cache/salt/minion2
```

to me this seems like a bug but want to get @saltstack/team-core 's opinions here. any ideas if there is a config option around this? to me it seems like a bug that should not be occurring by default.

**Comment by waynew** [comment]
So is this happening here just with two minions running on the same machine?

**Comment by pizzapanther** [comment]
haven't tried with more but yes.

**Comment by waynew** [comment]
Ah! That's very interesting. If I can get some time later this week I'll dig in and see what I can grok from this.
