### ISSUE TITLE
ZFS shouldn't be limited to only Solaris, SmartOS, and FreeBSD.

### ISSUE THREAD

**Issue by robertkeizer** [saltstack/salt#5266]
I'm running ZFS on Linux. Currently the code checks against a set of valid OS's. It should instead simply check for command existence.

**Comment by kim0** [comment]
@huntermatthews can you check if this is still failing on 2015.2 ? let me know what's failing for you and I'll try to fix

**Comment by huntermatthews** [comment]
I'm sorry but I'm not able to test this anymore - I've changed jobs and am no longer salt based.

--
Hunter Matthews Photography
hunter@huntermatthews.com

**Comment by sjorge** [comment]
As of 2016.3 the zfs and zpool modules also work on Solaris/SmartOS, I have not testes ZoL. But it should work as we check for zfs and zpool binaries.

**Comment by UtahDave** [comment]
Thanks, sjorge. I'll go ahead and close this issue, then.

Please comment here if we need to reopen.

Thanks!
