### ISSUE TITLE
Multi environments with basic sls files

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#52679]
Hey,

I have several environments on my salt-master (master version: 2019.2.0).
Several questions:
1. Is there a way to sign a minion configuration from different environments?

2. I have a basic configuration that I want to apply to **all** of the minions sign to this salt-master in addition to the configuration that they are getting inside their environment.
    2.1. How can I do this? 
    2.2. How the top files will look like?
    2.3. How the master config file will look like?

3. Is there a way to design the master hierarchy so it will behave like inheritance? 
4. Is it possible to override a title? if section 4 is true...
5. The order of execution of a sls files are the order they are included and presented in the file (top and sls files)?

Amiram

**Comment by DmitryKuzmenko** [comment]
@AmiramMaimon probably some of @saltstack/team-core could help you.
But the best way to get an answer to questions is to ask them in salt-users google group. https://groups.google.com/forum/#!forum/salt-users

**Comment by DmitryKuzmenko** [comment]
@AmiramMaimon as I think [this answer](https://github.com/saltstack/salt/issues/52677#issuecomment-486720507) covers most of questions being asked here. Could you please take a look and re-ask questions that aren't resolved yet for you?
