### ISSUE TITLE
Why distutils over setuptools?

### ISSUE THREAD

**Issue by CMeza99** [saltstack/salt#52706]
### Description of Issue/Question
I am trying to understand what consistency, or other, issues are preventing the use of setuptools over disutils. https://github.com/saltstack/salt/blob/develop/setup.py#L85-L86

From looking through the issues history, I understand I am not the first to bring this up. But I could not find why this choice whats made. Thx.

### Versions Report
since salt 0.10.1

**Comment by Ch3LL** [comment]
ping @s0undt3ch or @dmurphy18 any chance you can comment here?
