### ISSUE TITLE
file_map example for windows as a target

### ISSUE THREAD

**Issue by diegolaz** [saltstack/salt#52702]
When using profile file with salt-cloud, all file_map examples are with unix style paths... tried diferent ways on windows target but failed to work...

file_map:
    /path/to/local/custom/script: /path/to/remote/script
    /path/to/local/file: /path/to/remote/file
    /srv/salt/yum/epel.repo: /etc/yum.repos.d/epel.repo

Does anyone have a working example with windows paths ? 
Thanks!

**Comment by Ch3LL** [comment]
ping @saltstack/team-windows any ideas here to help out @diegolaz ?

**Comment by diegolaz** [comment]
For now I'm dealing it by doing a remote copy after the VM is cloned.

There is a lack of documentation on some paramters like win_run_once ... that points to VMWare documentation which is a commandList, but there is no reference or sample on hoy that commandList should look like... any ideas?

**Comment by Ch3LL** [comment]
ping @twangboy any ideas here?
