### ISSUE TITLE
integration.cli.test_grains fails on windows

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52719]
The following tests are failing on windows 2012:

```
integration.cli.test_grains.GrainsTargetingTest.test_grains_targeting_disconnected
integration.cli.test_grains.GrainsTargetingTest.test_grains_targeting_minion_id_running
integration.cli.test_grains.GrainsTargetingTest.test_grains_targeting_os_running
```

https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2012r2-py2/7/

**Comment by twangboy** [comment]
There seems to be problems with tests on 2012r2 in general. Until those are resolved, I am closing this.
