### ISSUE TITLE
unittest.loader._FailedTest.unit.cloud.clouds.test_joyent py3 failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52722]
The test `unittest.loader._FailedTest.unit.cloud.clouds.test_joyent` is failing on:

2019.2.1 failed salt-centos-7-py3, salt-centos-7-py3-pycryptodomex, salt-centos-7-py3-transport, salt-debian-9-py3, salt-fedora-28-py3, salt
-fedora-29-py3, salt-opensuse-42-py3, salt-ubuntu-1604-py3, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-transport, salt-ubuntu-
1804-py3, salt-windows-2016-py3

https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-centos-7-py3/7/testReport/junit/unittest.loader._FailedTest.unit.cloud/clouds/test_joyent/

```
Traceback (most recent call last):
  File "/usr/lib64/python3.4/unittest/case.py", line 59, in testPartExecutor
    yield
  File "/usr/lib64/python3.4/unittest/case.py", line 618, in run
    testMethod()
  File "/usr/lib64/python3.4/unittest/loader.py", line 33, in testFailure
    raise self._exception
ImportError: Failed to import test module: unit.cloud.clouds.test_joyent
Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/cloud/clouds/joyent.py", line 63, in <module>
    from M2Crypto import EVP
ImportError: No module named 'M2Crypto'
```

**Comment by KChandrashekhar** [comment]
Not a blocker for 2019.2.1 release.

**Comment by Ch3LL** [comment]
re-adding as a blocker

**Comment by Akm0d** [comment]
I was not able to duplicate the bug on 2019.2.1 using kitchen salt
