### ISSUE TITLE
unit.cloud.clouds.test_ec2 test failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52721]
The test `unit.cloud.clouds.test_ec2.EC2TestCase.test_get_password_data` is failing on:

2019.2.1 failed salt-centos-7-py3, salt-centos-7-py3-pycryptodomex, salt-centos-7-py3-transport, salt-debian-9-py3, salt-fedora-28-py3, salt-fedora-29-py3, salt-opensuse-42-py3, salt-ubuntu-1604-py3, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-transport, salt-ubuntu-1804-py3, salt-windows-2016-py3

https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-centos-7-py3/7/

```
Traceback (most recent call last):
  File "/usr/lib/python3.4/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/tmp/kitchen/testing/tests/unit/cloud/clouds/test_ec2.py", line 88, in test_get_password_data
    assert ret['password'] == 'testp4ss!'
KeyError: 'password'
```

**Comment by waynew** [comment]
Still failing on develop across the platforms:

develop failed [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data), [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.cloud.clouds.test_ec2/EC2TestCase/test_get_password_data)
---

'password'

```

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\mock\mock.py", line 1329, in patched
    return func(*args, **keywargs)
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\cloud\clouds\test_ec2.py", line 88, in test_get_password_data
    assert ret['password'] == 'testp4ss!'
KeyError: 'password'
		
```

**Comment by Akm0d** [comment]
re-run centos-7

**Comment by Akm0d** [comment]
This continues to be an issue for develop but doesn't seem to block 2019.2.1
