### ISSUE TITLE
Gentoo install minion only

### ISSUE THREAD

**Issue by luckylinux** [saltstack/salt#52725]
### Description of Issue/Question
I would like to install only salt-minion (and possibly salt-call) on my Gentoo minions.
The documentation at https://docs.saltstack.com/en/latest/topics/installation/gentoo.html only tells to run "emerge app-admin/salt". 

### Setup
This however install also salt-master on the client (minion) which I don't want (overhead, possible security risk, ...).

Is there a USE flag that needs to be set/unset?
I currently have salt installed with the following USE="zeromq -cherrypy -gnupg -keyring -ldap -libcloud -libvirt -mako -mongodb -mysql -neutron -nova -openssl -portage -profile -raet -redis -selinux -test -timelib -vim-syntax"

### Steps to Reproduce Issue
Install salt on Gentoo
emerge app-admin/salt

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.4
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 3.6.6
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Apr 24 2019, 20:03:26)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: gentoo 2.6 
         locale: UTF-8
        machine: x86_64
        release: 4.2.5-hardened-r1
         system: Linux
        version: Gentoo Base System 2.6

**Comment by waynew** [comment]
Is there an `emerge app-admin/salt-minion`?

Alternatively, you could try an install with either the bootstrap script or pip.

**Comment by luckylinux** [comment]
No there is not. I tried to create a custom app-admin/salt-minion where based on the USE flags I could turn on or off the different features. But I could only control the services to be installed (/etc/init.d/salt-minion, /etc/init.d/salt-master, ...). The salt-minion, salt-master, ... commands would be installed anyway.

The bootstrap script didn't work for me. app-admin/salt-9999 was retired because unmaintained/broken, see https://gitweb.gentoo.org/repo/gentoo.git/log/app-admin/salt?showmsg=1). And that ebuild is requested by the bootstrap script.

I didn't try an installation with pip. That might be a possible solution although I'm not sure that is the reccomended way ...

**Comment by waynew** [comment]
@luckylinux It looks like this actually belongs on the Gentoo bug tracker - I just learned that they're the ones maintaining the salt package(s) on Gentoo.

**Comment by waynew** [comment]
Since Gentoo maintains that package, I'm going to go ahead and close this issue.
