### ISSUE TITLE
custom module for minion accept, pending, deny...

### ISSUE THREAD

**Issue by GwiYeong** [saltstack/salt#52737]
### Description of Issue/Question
Hi, i would like to customize the way for establishing connection between minion and master.
Like external auth module(ldap, mysql etc...), salt-master just call specific function in custom module and then if the function return true or something other value, master will accept minion or deny, pending minion. is there any way for this?

**Comment by waynew** [comment]
If you have a minion on your master then you can just have it call `salt-key`. There may be some other way that I'm not sure about.

You might get quicker results on [ServerFault](https://serverfault.com/questions/ask), or one of the other [community resources](https://www.saltstack.com/resources/community/).

**Comment by GwiYeong** [comment]
I already know `salt-key` for managing minion key. but what i try to looking for is programmable way, not manually accept or deny key using `salt-key`. I think there is no way for this right now. could you guide me to which point to write code for programmable way to accept minion key when establish connection between minion and master? 

Thanks in advance

**Comment by max-arnold** [comment]
@GwiYeong You can try to explore the following ideas:

1. Autoaccept keys based on grains: https://docs.saltstack.com/en/latest/topics/tutorials/autoaccept_grains.html
2. Use a reactor: https://docs.saltstack.com/en/latest/topics/reactor/#a-complete-example
3. Write an engine that listens to events. You can look at `stalekey` engine for inspiration: https://github.com/saltstack/salt/blob/develop/salt/engines/stalekey.py

**Comment by waynew** [comment]
@GwiYeong did any of those resources help you?

**Comment by GwiYeong** [comment]
@waynew
sorry for late reply. 

@max-arnold 
i will try out your idea 2, 3. i think it will be good solution for my purpose.
thanks aging.

closing this issue.
