### ISSUE TITLE
CPU load is gradually rising after update to 2019.2

### ISSUE THREAD

**Issue by Dejv456** [saltstack/salt#52741]
### Description of Issue/Question
Recently i upgraded Salt from version 2018.3.0 to 2019.2.0 and i noticed, that CPU usage of salt-master process is slowly rising and during 2 days it hits 100% of CPU load. It happens both on virtual and physical machines. It does this, no matter how many minions i have connected. Restarting service brings CPU load back to 0.

I am running on SLE 15.

![salt cpu](https://user-images.githubusercontent.com/43398879/56892830-15c3f500-6a81-11e9-8b9c-37081f39956f.PNG)

### Steps to Reproduce Issue
Install salt-master, run service. 

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.4
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.5 (default, Apr 05 2018, 13:30:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-150.14-default
         system: Linux
        version: Not Installed

**Comment by waynew** [comment]
Hi @Dejv456, thanks for the report!

A couple of questions:

- Are you using any gitfs backends?
- Is there anything in your `/etc/salt/master` file? 
   - If you replace it with a blank file, do you still see the same problem?
- Do you see anything suspect in your logs? Check `/var/log/salt/`.
- How are you installing salt? With `pip` or via SUSE's installer? If you try the other method, do you still see this same behavior?

Thanks!

**Comment by Dejv456** [comment]
Thanks for the feedback.

I installed Salt via pip and its fixed. It looks like, there is something wrong with the package we have.
