### ISSUE TITLE
VMWare Driver does not support tag info

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#52764]
### Description of Issue/Question
The current cloud vmware driver does not support retrieving information about tags.
Example `salt-cloud -a show_instance <instancename>` does not display the information about tags. The instance when viewing in vSphere does have tags. If we use the same command in AWS tag info is retrieved and displayed. The tag values are crucial for managing the cloud infra structure.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Version info:
Salt: 2018.3.4
Vsphere: 6.5

**Comment by doesitblend** [comment]
ZD-3633

**Comment by waynew** [comment]
https://vdc-download.vmware.com/vmwb-repository/dcr-public/6b586ed2-655c-49d9-9029-bc416323cb22/fa0b429a-a695-4c11-b7d2-2cbc284049dc/doc/vim.ManagedEntity.html#tag

According to this doc it seems like that might be (currently) an experimental feature. Not sure if it's supported in pyvmomi yet?

**Comment by rdutch** [comment]
The set of tags associated with this managed entity. Experimental. Subject to change.
**Since vSphere API 4.0**
I would not call this Experimental

**Comment by doesitblend** [comment]
Reviewing the current version of pyvmomi (master branch) the tests pull an object containing a key tag.

```
[...trimmed for brevity..]
"dynamicProperty": [], "dynamicType": null, "key": "host"}, "tag": [], "triggeredAlarmState": [],
[...trimmed for brevity..]
```

**Comment by xeacott** [comment]
Upon much investigation, VMWare PyVmomi does not support tagging. This has been stated by tianhao64 in a few github issues that have been opened in pyvmomi, for example:
 
- [Issue 307](https://github.com/vmware/pyvmomi/issues/307)
- [Issue 733](https://github.com/vmware/pyvmomi/issues/733) 

To support this feature, tagging requires vSphere Automation SDK (formerly known as vCloud Suite SDK, which can be viewed [here)](https://code.vmware.com/web/sdk/60/vcloudsuite-python?h=VMware%20vCloud%20Suite%20SDK%20for%20Python) of version 6.0 at minimum. This is a feature that is being worked on at the moment and will be implemented using the new SDK suite.

**Comment by xeacott** [comment]
@doesitblend I looked into the salt-cloud command, specifically `show_instance` and, while we don't have a 1-to-1 command in `vsphere.py`, there is `get_vm` that displays information about the virtual machine. I believe this is the method you wish to give associated tags too?

**Comment by sagetherage** [comment]
@doesitblend this is fixed - can you verify using https://github.com/saltstack/salt/pull/54058?

**Comment by sagetherage** [comment]
This is merged @doesitblend ok to close that this will be released in Neon?
