### ISSUE TITLE
External Pillar docs broken

### ISSUE THREAD

**Issue by femaref** [saltstack/salt#52789]
When googling or using the search in the docs, the link for external pillar docs (https://docs.saltstack.com/en/latest/topics/development/external_pillars.html) is broken and 404's.

**Comment by waynew** [comment]
Interesting. I know we tried updating Sphinx, which kind of broke many things, but I would have thought this would have made it back if it was related :suspect:

**Comment by bryceml** [comment]
It looks like it just moved here: https://docs.saltstack.com/en/latest/topics/development/modules/external_pillars.html

Things weren't getting deleted for a while so maybe it never got deleted when it moved.

**Comment by bryceml** [comment]
There is nothing we can do really except wait for google to find it.  Duckduckgo can find it https://duckduckgo.com/?q=salt+external_pillars

**Comment by appi1411** [comment]
It is very important, Search google allot did not find the any thing
relevant.

**Comment by bryceml** [comment]
I told our SEO team, hopefully they get google to find it.
