### ISSUE TITLE
FQDNs grains generate errors in IPv6

### ISSUE THREAD

**Issue by aplanas** [saltstack/salt#52788]
### Description of Issue/Question

My salt-master is over a host that contains IPv4 and IPv6 addresses, and not all the IPv6 can be resolved by a DNS.

The grains in core try to resolve all the IPs, but not all of them can be resolved, so my master log errors like this ones:

```
[ERROR   ] Exception during resolving address: [Errno 1] Unknown host
```

```
[ERROR   ] Exception during resolving address: [Errno 4] No address associated with name
```

Those errors correspond to the HOST_NOT_FOUND and NO_DATA from the socket API.

### Setup
Any deployment of develop will recreate the issue

### Versions Report
`develop` branch

**Comment by waynew** [comment]
I could be wrong, but it seems like this is behavior that we would like to have, or at least optionally turn off. @saltstack/team-core @saltstack/team-network do you have any thoughts here?

**Comment by aplanas** [comment]
If I understand the problem, Error 1 will never go away as is an IPv6 that will never have a domain name associated, and I do not see this as an error per se.

Error 4 is when an old IPv6 disappear from the resolver, something that, looks like, can happen frequently as there is some kind of temporary IPv6 or something. If this is correct, I would thing that this is neither an error relevant to be logged (maybe a WARNING or an INFO)

**Comment by aplanas** [comment]
The fix is rebased on master now
