### ISSUE TITLE
unit.modules.test_win_file.WinFileTestCase.test_issue_52002_check_file_remove_symlink test failure

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52781]
# unit.modules.test_win_file.WinFileTestCase.test_issue_52002_check_file_remove_symlink test failure

2019.2 failed salt-windows-2016-py3, salt-windows-2019-py3
--------------------------------------------------------------------------------

Could not create 'C:\Users\ADMINI~1\AppData\Local\Temp\base-a_dga918\child 2\link' - [1314] A required privilege is not held by the client.

```
Traceback (most recent call last):
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_file.py", line 1151, in symlink
    win32file.CreateSymbolicLink(link, src, int(is_dir))
pywintypes.error: (1314, 'CreateSymbolicLink', 'A required privilege is not held by the client.')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\tests\support\helpers.py", line 129, in wrap
    return caller(cls)
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_win_file.py", line 76, in test_issue_52002_check_file_remove_symlink
    self.assertTrue(win_file.symlink(target, symlink))
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_file.py", line 1158, in symlink
    exc.strerror
salt.exceptions.CommandExecutionError: Could not create 'C:\Users\ADMINI~1\AppData\Local\Temp\base-a_dga918\child 2\link' - [1314] A required privilege is not held by the client.
```

**Comment by waynew** [comment]
This is failing on develop with a different error

develop failed [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unit.modules.test_win_file/WinFileCheckPermsTestCase/test_issue_52002_check_file_remove_symlink), [salt-windows- 2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.modules.test_win_file/WinFileCheckPermsTestCase/test_issue_52002_check_file_remove_symlink), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/unit.modules.test_win_file/WinFileCheckPermsTestCase/test_issue_52002_check_file_remove_symlink), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.modules.test_win_file/WinFileCheckPermsTestCase/test_issue_52002_check_file_remove_symlink)
---

'dacl.set_perms'

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\modules\test_win_file.py", line 314, in test_issue_52002_check_file_remove_symlink
    self.assertTrue(win_file.makedirs_(target))
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_file.py", line 1461, in makedirs_
    reset=reset)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_file.py", line 1327, in mkdir
    reset=reset)
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\modules\win_file.py", line 1730, in set_perms
    return __utils__['dacl.set_perms'](obj_name=path,
KeyError: 'dacl.set_perms'
		
```

**Comment by waynew** [comment]
`KeyError: 'dacl.*` failures also show up in these tests:

- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_reset_test_true
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_grant_test_true
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_reset
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_deny
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_inheritance_false
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_grant
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_set_owner_test_true
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_inheritance_true
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_inheritance_false_test_true
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_deny_test_true
- unit.modules.test_win_file.WinFileCheckPermsTestCase.test_check_perms_set_owner

**Comment by twangboy** [comment]
@waynew There are some merge forwards that need to happen to fix those.

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/pull/52145

And it looks like it was fixed once before...
https://github.com/saltstack/salt/pull/52144/files

**Comment by twangboy** [comment]
I guess I'll take a look... again... It's a moving target

**Comment by twangboy** [comment]
Fixed again!

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py2/59/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2016-py2/52/
May 20, 2019 8:00:00 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py3/48/

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/
