### ISSUE TITLE
Adding RunSynchronousCommands to the sysprep file created

### ISSUE THREAD

**Issue by diegolaz** [saltstack/salt#52790]
Working with the profile (.conf) file to prepare for automated clones. Almost all working good, but I could find anyware to add commands to the RunSynchronousCommand section of the answer file created for the sysprep.

I assume that salt creates the answer file that then sends to vmware to do the clone, and I managed to add commands to the FirstLogon, but I needed to add one to the RunSynchronousCommand so it executes before the first logon or actually before sysprep does the first reboot.

Is that posible?

Thank you
Diego

**Comment by waynew** [comment]
Hi,

You might get a quicker answer on the [Salt user group](https://groups.google.com/forum/#!forum/salt-users), the Salt [Community Slack](https://saltstackcommunity.slack.com/), or [ServerFault](https://serverfault.com/questions/ask/advice?)(though in its current form, this wouldn't be a good question on ServerFault).
