### ISSUE TITLE
unit.grains.test_core.CoreGrainsTestCase.test__windows_platform_data

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52801]
2019.2.1 failed [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py2/14/testReport/junit/unit.grains.test_core/CoreGrainsTestCase/test__windows_platform_data)
---

u'virtual' not found in {u'biosversion': u'Default System BIOS', u'osrelease': u'2019Server', u'kernelrelease': u'10.0.17763', u'motherboard': {u'serialnumber': None, u'productname': None}, u'serialnumber': u'ec22b9bb-67aa-194e-cb6f-c51ad8219fe7', u'timezone': u'(UTC) Coordinated Universal Time', u'manufacturer': u'Amazon EC2', u'kernelversion': '10.0.17763', u'osservicepack': None, u'windowsdomaintype': u'Workgroup', u'productname': u'c5.xlarge', u'osfullname': u'Microsoft Windows Server 2019 Datacenter', u'osmanufacturer': u'Microsoft Corporation', u'osversion': u'10.0.17763', u'windowsdomain': u'WORKGROUP'}

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\grains\test_core.py", line 158, in test__windows_platform_data
    self.assertIn(key, grains)
AssertionError: u'virtual' not found in {u'biosversion': u'Default System BIOS', u'osrelease': u'2019Server', u'kernelrelease': u'10.0.17763', u'motherboard': {u'serialnumber': None, u'productname': None}, u'serialnumber': u'ec22b9bb-67aa-194e-cb6f-c51ad8219fe7', u'timezone': u'(UTC) Coordinated Universal Time', u'manufacturer': u'Amazon EC2', u'kernelversion': '10.0.17763', u'osservicepack': None, u'windowsdomaintype': u'Workgroup', u'productname': u'c5.xlarge', u'osfullname': u'Microsoft Windows Server 2019 Datacenter', u'osmanufacturer': u'Microsoft Corporation', u'osversion': u'10.0.17763', u'windowsdomain': u'WORKGROUP'}
		
```
develop failed [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unit.grains.test_core/CoreGrainsTestCase/test_windows_platform_data), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.grains.test_core/CoreGrainsTestCase/test_windows_platform_data), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/unit.grains.test_core/CoreGrainsTestCase/test_windows_platform_data), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.grains.test_core/CoreGrainsTestCase/test_windows_platform_data)
---

'virtual' not found in {'osrelease': '2019Server', 'osmanufacturer': 'Microsoft Corporation', 'productname': 'c5.xlarge', 'kernelversion': '10.0.17763', 'windowsdomain': 'WORKGROUP', 'timezone': '(UTC) Coordinated Universal Time', 'motherboard': {'productname': None, 'serialnumber': None}, 'windowsdomaintype': 'Workgroup', 'osversion': '10.0.17763', 'osfullname': 'Microsoft Windows Server 2019 Datacenter', 'osservicepack': None, 'kernelrelease': '10.0.17763', 'manufacturer': 'Amazon EC2', 'serialnumber': 'ec25afb9-2c2e-1cb8-f860-bac0e00459a8', 'biosversion': 'Default System BIOS'}

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\grains\test_core.py", line 598, in test_windows_platform_data
    self.assertIn(grain, returned_grains)
AssertionError: 'virtual' not found in {'osrelease': '2019Server', 'osmanufacturer': 'Microsoft Corporation', 'productname': 'c5.xlarge', 'kernelversion': '10.0.17763', 'windowsdomain': 'WORKGROUP', 'timezone': '(UTC) Coordinated Universal Time', 'motherboard': {'productname': None, 'serialnumber': None}, 'windowsdomaintype': 'Workgroup', 'osversion': '10.0.17763', 'osfullname': 'Microsoft Windows Server 2019 Datacenter', 'osservicepack': None, 'kernelrelease': '10.0.17763', 'manufacturer': 'Amazon EC2', 'serialnumber': 'ec25afb9-2c2e-1cb8-f860-bac0e00459a8', 'biosversion': 'Default System BIOS'}
		
```

**Comment by waynew** [comment]
Looks like this was also failing on develop, so we'll definitely need to get a merge forward on this 👍

**Comment by twangboy** [comment]
The above PR will bring those changes into develop
