### ISSUE TITLE
integration.modules.test_cp.CPModuleTest.test_get_url_https_dest_empty test failure

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52807]
2019.2.1 failed [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1404-py2/10/testReport/junit/integration.modules.test_cp/CPModuleTest/test_get_url_https_dest_empty)
---

[Errno 2] No such file or directory: u'The minion function caused an exception: Traceback (most recent call last):\n  File "/tmp/kitchen/testing/salt/minion.py", line 1663, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "/tmp/kitchen/testing/salt/executors/direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "/tmp/kitchen/testing/salt/modules/cp.py", line 418, in get_url\n    path, dest, makedirs, saltenv, source_hash=source_hash)\n  File "/tmp/kitchen/testing/salt/fileclient.py", line 694, in get_url\n    **get_kwargs\n  File "/tmp/kitchen/testing/salt/utils/http.py", line 566, in query\n    result = download_client.fetch(url_full, **req_kwargs)\n  File "/usr/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch\n    self._async_client.fetch, request, **kwargs))\n  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 445, in run_sync\n    return future_cell[0].result()\n  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result\n    raise_exc_info(self._exc_info)\n  File "<string>", line 3, in raise_exc_info\nSSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure\n'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_cp.py", line 312, in test_get_url_https_dest_empty
    with salt.utils.files.fopen(ret, 'r') as instructions:
  File "/tmp/kitchen/testing/salt/utils/files.py", line 399, in fopen
    f_handle = open(*args, **kwargs)  # pylint: disable=resource-leakage
IOError: [Errno 2] No such file or directory: u'The minion function caused an exception: Traceback (most recent call last):\n  File "/tmp/kitchen/testing/salt/minion.py", line 1663, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "/tmp/kitchen/testing/salt/executors/direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "/tmp/kitchen/testing/salt/modules/cp.py", line 418, in get_url\n    path, dest, makedirs, saltenv, source_hash=source_hash)\n  File "/tmp/kitchen/testing/salt/fileclient.py", line 694, in get_url\n    **get_kwargs\n  File "/tmp/kitchen/testing/salt/utils/http.py", line 566, in query\n    result = download_client.fetch(url_full, **req_kwargs)\n  File "/usr/lib/python2.7/dist-packages/tornado/httpclient.py", line 102, in fetch\n    self._async_client.fetch, request, **kwargs))\n  File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line 445, in run_sync\n    return future_cell[0].result()\n  File "/usr/lib/python2.7/dist-packages/tornado/concurrent.py", line 215, in result\n    raise_exc_info(self._exc_info)\n  File "<string>", line 3, in raise_exc_info\nSSLError: [Errno 1] _ssl.c:510: error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure\n'
		
```

**Comment by dmurphy18** [comment]
@KChandrashekhar THis should not be a Blocker since no more Ubuntu 14.04 support

**Comment by dmurphy18** [comment]
Closing since Ubuntu 14.04 is EOL and we are not supporting now
