### ISSUE TITLE
iNotify support using watchdog- Windows

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#52804]

**Comment by sagetherage** [comment]
@twangboy looks like the PR above is merged ok to close this issue then?

**Comment by dmurphy18** [comment]
Solaris and AIX still have to be delivered with point release 2019.2.3

**Comment by sagetherage** [comment]
Isn't there a ticket for Solaris and AIX separate from this windows ticket @dmurphy18 ?

**Comment by dmurphy18** [comment]
There is, but this issue doesn't mention that it is for Windows, hence thought this was a general issue tracking work done for all platforms, given the Solaris and AIX are on another rarely checked repo.

Can close if you want.

**Comment by sagetherage** [comment]
That is a good point, I will update this issue noting it is Windows platform only that is fixed and when you get a change send me the links to the tickets for Solaris and AIX I will want to check that repo more often.

**Comment by dmurphy18** [comment]
See Solaris and AIX respectively

https://github.com/saltstack/salt-pack-extras/issues/168
https://github.com/saltstack/salt-pack-extras/issues/169
