### ISSUE TITLE
unit.renderers.test_gpg.GPGTestCase.test_render_with_translate_newlines_should_translate_newlines test failure

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52806]
2019.2.1 failed [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py2/14/testReport/junit/unit.renderers.test_gpg/GPGTestCase/test_render_with_translate_newlines_should_translate_newlines)
---

u'Use\u2039 more\u2039 salt.\n\nUse\u2039 more\u2039 salt.\n\nUse\u2039 more\u2039 salt.' != 'Use\x8b more\x8b salt.\n\nUse\x8b more\x8b salt.\n\nUse\x8b more\x8b salt.'

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\renderers\test_gpg.py", line 169, in test_render_with_translate_newlines_should_translate_newlines
    expected,
AssertionError: u'Use\u2039 more\u2039 salt.\n\nUse\u2039 more\u2039 salt.\n\nUse\u2039 more\u2039 salt.' != 'Use\x8b more\x8b salt.\n\nUse\x8b more\x8b salt.\n\nUse\x8b more\x8b salt.'
		
```

**Comment by Ch3LL** [comment]
verified fixed by https://github.com/saltstack/salt/pull/52771

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/
