### ISSUE TITLE
unit.states.test_file.TestFileState.test_file_managed_should_fall_back_to_binary test failure

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52803]
2019.2.1 failed [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py2/14/testReport/junit/unit.states.test_file/TestFileState/test_file_managed_should_fall_back_to_binary)
---

u'\u2039\r\n' != '\x8b'

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\states\test_file.py", line 617, in test_file_managed_should_fall_back_to_binary
    self.assertEqual(actual_contents, expected_contents)
AssertionError: u'\u2039\r\n' != '\x8b'
		
```

**Comment by waynew** [comment]
I worked on this original bugfix - I'm sure I can offer some context here. I'm guessing this failure has to do with the encoding on Windows :suspect:

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/
