### ISSUE TITLE
Testing support for Amazon Linux 1 Python 2

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#52811]
### Description of Issue/Question
Though Amazon Linux 1 is similar to RH6, Linux 1 uses Py 2.7 and RH6 uses Py 2.6
Hence Amazon Linux 1 needs to get tested separately 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by s0undt3ch** [comment]
Base Image builds, working on CI image.

**Comment by s0undt3ch** [comment]
Additional work https://github.com/saltstack/salt-jenkins/pull/1400

**Comment by s0undt3ch** [comment]
Golden Images Created and Jenkins Jobs Added.
