### ISSUE TITLE
unit.modules.test_telegram.TelegramModuleTest.test_post_message

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52817]
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.modules.test_telegram/TelegramModuleTest/test_post_message)
---

The dictionary keys returned by TelegramModuleTest.setup_loader_modules() must be an imported module, not <class 'str'>

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 374, in wrapper
    type(module)
RuntimeError: The dictionary keys returned by TelegramModuleTest.setup_loader_modules() must be an imported module, not <class 'str'>
		
```

This is similar to another error I recently created an issue for. It had "must be an imported module". Ah, it was #52815.

**Comment by KChandrashekhar** [comment]
Not a blocker for 2019.2.1 so we will reconsider fixing this for 2019.2.2 release

**Comment by Ch3LL** [comment]
re-adding as a blocker

**Comment by Ch3LL** [comment]
blocked:

https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/32/console

is not running the tests. I believe this is related to the nox changes recently merged in, but diving into it now.

**Comment by Ch3LL** [comment]
bootstrap issue will be fixed by https://github.com/saltstack/salt/pull/52968
