### ISSUE TITLE
unit.modules.test_mandrill.MandrillModuleTest.test_send - dictionary keys must be an imported module

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52815]
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/11/testReport/junit/unit.modules.test_mandrill/MandrillModuleTest/test_send)
---

The dictionary keys returned by MandrillModuleTest.setup_loader_modules() must be an imported module, not <class 'str'>

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 374, in wrapper
    type(module)
RuntimeError: The dictionary keys returned by MandrillModuleTest.setup_loader_modules() must be an imported module, not <class 'str'>
		
```

**Comment by KChandrashekhar** [comment]
Not a blocker for 2019.2.1 so we will reconsider fixing this for 2019.2.2 release

**Comment by Ch3LL** [comment]
re-adding as a blocker

**Comment by frogunder** [comment]
This test issue error seems to be resolved by the move to use nox.
It has not failed on 2019.2.1 since the change was made.

I think it will also be resolved one develop branch once we start using nox on develop branch.

Closing this issue.
