### ISSUE TITLE
integration.cloud.clouds.test_linode.LinodeTest.test_instance

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52822]
2019.2.1 failed [salt-centos-7-py3-cloud](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py3-cloud/9/testReport/junit/integration.cloud.clouds.test_linode/LinodeTest/test_instance)
---

'CLOUD-TEST-QF5MS9' not found in ["[b'Alpine 3.9',", "b'Arch Linux',", "b'CentOS 6.8',", "b'CentOS 7',", "b'CoreOS Container Linux',", "b'Debian 8',", "b'Debian 9',", "b'Fedora 27',", "b'Fedora 28',", "b'Fedora 29',", "b'Fedora 30',", "b'Gentoo',", "b'Slackware 14.1',", "b'Slackware 14.2',", "b'Ubuntu 16.04 LTS',", "b'Ubuntu 18.04 LTS',", "b'Ubuntu 18.10',", "b'Ubuntu 19.04',", "b'openSUSE Leap 15.0',", "b'openSUSE Leap 42.3']"]

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_linode.py", line 73, in test_instance
    [i.strip() for i in self.run_cloud('-p linode-test {0}'.format(INSTANCE_NAME), timeout=500)]
AssertionError: 'CLOUD-TEST-QF5MS9' not found in ["[b'Alpine 3.9',", "b'Arch Linux',", "b'CentOS 6.8',", "b'CentOS 7',", "b'CoreOS Container Linux',", "b'Debian 8',", "b'Debian 9',", "b'Fedora 27',", "b'Fedora 28',", "b'Fedora 29',", "b'Fedora 30',", "b'Gentoo',", "b'Slackware 14.1',", "b'Slackware 14.2',", "b'Ubuntu 16.04 LTS',", "b'Ubuntu 18.04 LTS',", "b'Ubuntu 18.10',", "b'Ubuntu 19.04',", "b'openSUSE Leap 15.0',", "b'openSUSE Leap 42.3']"]
		
```

**Comment by frogunder** [comment]
@KChandrashekhar 

I think this can be closed.

Last time this issue was present was back on May 1st. 

It have had over 10 successful runs after that with no errors. Test has not failed since May 1st.
