### ISSUE TITLE
unit.utils.test_args.ArgsTestCase.test_argspec_report failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#52836]
### Description of Issue/Question

```
Error Message

{'tes[29 chars]ts': (None,), 'varargs': None, 'kwargs': None,[32 chars]1']}} != {'tes[29 chars]ts': None, 'varargs': True, 'kwargs': True, 'args': None}} - {'test_module.test_spec': {'args': ['arg1', 'arg2', 'kwarg1'], + {'test_module.test_spec': {'args': None, -                            'defaults': (None,), ?                                        -     --  +                            'defaults': None, -                            'kwargs': None, ?                                      ^^^  +                            'kwargs': True, ?                                      ^^^  -                            'varargs': None}} ?                                       ^^^  +                            'varargs': True}} ?                                       ^^^ 

Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_args.py", line 133, in test_argspec_report
    {'kwargs': True, 'args': None, 'defaults': None, 'varargs': True}})
AssertionError: {'tes[29 chars]ts': (None,), 'varargs': None, 'kwargs': None,[32 chars]1']}} != {'tes[29 chars]ts': None, 'varargs': True, 'kwargs': True, 'args': None}}
- {'test_module.test_spec': {'args': ['arg1', 'arg2', 'kwarg1'],
+ {'test_module.test_spec': {'args': None,
-                            'defaults': (None,),
?                                        -     --

+                            'defaults': None,
-                            'kwargs': None,
?                                      ^^^

+                            'kwargs': True,
?                                      ^^^

-                            'varargs': None}}
?                                       ^^^

+                            'varargs': True}}
?                                       ^^^
```

https://jenkinsci.saltstack.com/job/2019.2.1/view/Crypto/job/salt-ubuntu-1604-py3-pycryptodomex/11/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report/

**Comment by waynew** [comment]
Also failing on develop

2019.2.1 failed [ch3ll-zmq-filter-salt-centos-7-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/ch3ll-zmq-filter-salt-centos-7-py3/1/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-centos-7-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py3/22/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-centos-7-py3-m2crypto](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py3-m2crypto/16/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-centos-7-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py3-pycryptodomex/18/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-debian-8-py3/20/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-debian-9-py3/21/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/23/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-42-py3/21/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3/20/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-ubuntu-1604-py3-transport](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-transport/17/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1804-py3/21/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report)
develop failed [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.utils.test_args/ArgsTestCase/test_argspec_report)
---

{'tes[29 chars]ts': (None,), 'args': ['arg1', 'arg2', 'kwarg1[32 chars]one}} != {'tes[29 chars]ts': None, 'kwargs': True, 'varargs': True, 'args': None}} - {'test_module.test_spec': {'args': ['arg1', 'arg2', 'kwarg1'], + {'test_module.test_spec': {'args': None, -                            'defaults': (None,), ?                                        -     --  +                            'defaults': None, -                            'kwargs': None, ?                                      ^^^  +                            'kwargs': True, ?                                      ^^^  -                            'varargs': None}} ?                                       ^^^  +                            'varargs': True}} ?                                       ^^^ 

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\utils\test_args.py", line 133, in test_argspec_report
    {'kwargs': True, 'args': None, 'defaults': None, 'varargs': True}})
AssertionError: {'tes[29 chars]ts': (None,), 'args': ['arg1', 'arg2', 'kwarg1[32 chars]one}} != {'tes[29 chars]ts': None, 'kwargs': True, 'varargs': True, 'args': None}}
- {'test_module.test_spec': {'args': ['arg1', 'arg2', 'kwarg1'],
+ {'test_module.test_spec': {'args': None,
-                            'defaults': (None,),
?                                        -     --

+                            'defaults': None,
-                            'kwargs': None,
?                                      ^^^

+                            'kwargs': True,
?                                      ^^^

-                            'varargs': None}}
?                                       ^^^

+                            'varargs': True}}
?                                       ^^^

		
```

**Comment by garethgreenaway** [comment]
Will get fixed on develop during the next merge forward.
