### ISSUE TITLE
Undesirable ERRORS when using git repo which contains symlinks

### ISSUE THREAD

**Issue by sticky-note** [saltstack/salt#52830]
### Description of Issue/Question
Undesirable Error on salt master when using git repo which contains symlinks
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
`master.d/fileserver.conf`
```
fileserver_backend:
  - gitfs
  - roots  # Needed for local lab

file_roots:
  base:
    - /srv/salt

pillar_roots:
  base:
    - /srv/pillar

# Disable global lock ( Useful for single-master )
gitfs_global_lock: False

# Waiting for SSL/TLS support in debian's pygit2
gitfs_provider: gitpython

gitfs_remotes:
  - ssh://git@blabla.tld:8022/folder/repo.git # <- Repo which contains symlinks
  - https://github.com/saltstack-formulas/mysql-formula.git
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Running state using `file.managed` with `source: salt://...` from gitfs repo which contains symlinks produces undesirable ERROR in master log
However, the pointed file which isn't a symlink is correctly found and managed. The master log produces this Error but the state is executed correctly without error.
Not tested yet with `file.managed` `source: salt://...`  pointing on a symlink 
```
May 05 20:04:15 sm salt-master[404]: Traceback (most recent call last):
May 05 20:04:15 sm salt-master[404]:   File "/usr/lib/python3/dist-packages/salt/master.py", line 1838, in run_func
May 05 20:04:15 sm salt-master[404]:     ret = getattr(self, func)(load)
May 05 20:04:15 sm salt-master[404]:   File "/usr/lib/python3/dist-packages/salt/utils/decorators/__init__.py", line 666, in wrapped
May 05 20:04:15 sm salt-master[404]:     return function(*args, **kwargs)
May 05 20:04:15 sm salt-master[404]:   File "/usr/lib/python3/dist-packages/salt/fileserver/__init__.py", line 789, in file_list
May 05 20:04:15 sm salt-master[404]:     ret.update(self.servers[fstr](load))
May 05 20:04:15 sm salt-master[404]:   File "/usr/lib/python3/dist-packages/salt/fileserver/gitfs.py", line 185, in file_list
May 05 20:04:15 sm salt-master[404]:     return _gitfs().file_list(load)
May 05 20:04:15 sm salt-master[404]:   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2943, in file_list
May 05 20:04:15 sm salt-master[404]:     return self._file_lists(load, 'files')
May 05 20:04:15 sm salt-master[404]:   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 2920, in _file_lists
May 05 20:04:15 sm salt-master[404]:     repo_files, repo_symlinks = repo.file_list(load['saltenv'])
May 05 20:04:15 sm salt-master[404]:   File "/usr/lib/python3/dist-packages/salt/utils/gitfs.py", line 1311, in file_list
May 05 20:04:15 sm salt-master[404]:     file_blob.stream_data(stream)
May 05 20:04:15 sm salt-master[404]:   File "/usr/lib/python3/dist-packages/git/objects/base.py", line 119, in stream_data
May 05 20:04:15 sm salt-master[404]:     stream_copy(istream, ostream)
May 05 20:04:15 sm salt-master[404]:   File "/usr/lib/python3/dist-packages/git/util.py", line 127, in stream_copy
May 05 20:04:15 sm salt-master[404]:     destination.write(chunk)
May 05 20:04:15 sm salt-master[404]: TypeError: string argument expected, got 'bytes'
```

Finally : ```salt-run filserver.file_list``` or ```salt-run filserver.dir_list``` without arguments produces:
```
Passed invalid arguments: string argument expected, got 'bytes'

Usage:

...
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9 
```
No matter which minion is targeted

EDIT: I didn't included whole python stacktrace. Now it is complete.

**Comment by waynew** [comment]
FWIW git doesn't really [handle symlinks like a normal file](https://stackoverflow.com/q/954560/344286), which might be causing your issues. It's a much healthier approach to create your symlink(s) in the other direction.

**Comment by sticky-note** [comment]
@waynew Not sure I understand what you mean by "other direction".
I am just pointing here filerserver.file_list and fileserver.dir_list doesn't work as expected when gitfs repos contains symlinks.

**Comment by waynew** [comment]
I mean that you have a repository that contains symlinks. Say it's something like:

    /path/to/repo/foo -> /usr/bin/foo

Instead, you want to create the link in the other direction. The local file should be a symlink, while the actual file lives in your repo:

    /usr/bin/foo -> /path/to/repo/foo

**Comment by sticky-note** [comment]
Ideally yes, but historically this repo uses symlinks to centralize nginx conf on several servers.
A `_sites-available` folder at root contains all available sites and a `server` folder contains all sites-enabled with symlinks by servers. `servers/srv1/sites-enabled/` contains all sites enabled for `srv1`. I wanted to use use this repo just to take configs from the first folder and make the mapping with salt and saw this issue. I am managing to not use the old pattern any more..

**Comment by waynew** [comment]
So you're using (or were trying to use) Salt+git to actually store the symlinks themselves?? i.e. you were actually trying to store a *link* from `example.com -> ../sites-available/example.com`? Not the *contents*?

That seems like a recipe for disaster 😛  Specifically, I'm not sure if the symlink tracking behavior in git is guaranteed. Maybe it is, but that still doesn't seem very reliable. 

Unless I understood wrong!

---

Of course, there are some good nginx formulas out there so you could specify which config should be enabled and which ones shouldn't. Kind of like you were doing with these symlinks, but with behavior you can rely on 😄

**Comment by sticky-note** [comment]
Totally agree with you, I use already nginx-formula, works well and personally want to sweep those symlinks in this git repo. I have managed to convince at work that it won't be worth it to use Salt for automation with this kind of handcrafted architecture in repos or to use Salt to edit repos. Won the game ^^
The thing is we can't use `filserver.file_list` or `fileserver.dir_list` runners when a gitfs repo contains symlinks.
Just pointing the issue, if it is not enough relevant to treat it or to keep it open, feel free to close it.
Comforted to not be alone thinking symlinks in repos are recipe for disaster anyway ;)

**Comment by L4rS6** [comment]
I got the exact same behaviour on salt-master version 2019.2.2 running on python 3. In my opinion to remove all symlinks isn't a proper solution. Might there be any chance that this gets fixed?

**Comment by sticky-note** [comment]
Think there is a need to reconsider this issue
