### ISSUE TITLE
Deprecation iptables to nftables

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#52837]

**Comment by waynew** [comment]
@KChandrashekhar Should this be in the approved milestone?

**Comment by KChandrashekhar** [comment]
> @KChandrashekhar Should this be in the approved milestone?

I'm adding priority milestone to the ones which are upcoming. Like next couple of releases and it's prioritized by Product to be worked on

**Comment by sagetherage** [comment]
keeping both closing
