### ISSUE TITLE
unit.utils.test_master.MasterUtilsIsPidHealthy.test_pid_not_running

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52859]
develop failed [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unit.utils.test_master/MasterUtilsIsPidHealthy/test_pid_not_running), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.utils.test_master/MasterUtilsIsPidHealthy/test_pid_not_running), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/unit.utils.test_master/MasterUtilsIsPidHealthy/test_pid_not_running), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.utils.test_master/MasterUtilsIsPidHealthy/test_pid_not_running)
---

```

Traceback (most recent call last):
  File "C:\Python35\lib\site-packages\mock\mock.py", line 1329, in patched
    return func(*args, **keywargs)
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\utils\test_master.py", line 85, in test_pid_not_running
    assert master.is_pid_healthy(99999999) is False
AssertionError
		
```

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/
