### ISSUE TITLE
integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_single_source

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52867]
develop failed [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.pillar.test_git_pillar/TestGitPythonAuthenticatedHTTP/test_single_source)
---

Cmd('git') failed due to: exit code(128)   cmdline: git fetch -v origin   stderr: 'fatal: unable to access 'http://gitpillaruser:saltrules@127.0.0.1:38569/repo.git/': The requested URL returned error: 502'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/pillar/test_git_pillar.py", line 146, in test_single_source
    ''')
  File "/tmp/kitchen/testing/tests/support/gitfs.py", line 353, in get_pillar
    *ext_pillar_opts['ext_pillar'][0]['git']
  File "/tmp/kitchen/testing/salt/pillar/git_pillar.py", line 413, in ext_pillar
    global_only=GLOBAL_ONLY)
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 2144, in __init__
    global_only)
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 2210, in init_remotes
    repo_obj.fetch()
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 776, in fetch
    return self._fetch()
  File "/tmp/kitchen/testing/salt/utils/gitfs.py", line 1262, in _fetch
    fetch_results = origin.fetch()
  File "/usr/local/lib/python3.6/dist-packages/git/remote.py", line 789, in fetch
    res = self._get_fetch_info_from_stderr(proc, progress)
  File "/usr/local/lib/python3.6/dist-packages/git/remote.py", line 675, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
  File "/usr/local/lib/python3.6/dist-packages/git/cmd.py", line 415, in wait
    raise GitCommandError(self.args, status, errstr)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(128)
  cmdline: git fetch -v origin
  stderr: 'fatal: unable to access 'http://gitpillaruser:saltrules@127.0.0.1:38569/repo.git/': The requested URL returned error: 502'
		
```

**Comment by waynew** [comment]
Also applies to:

- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_includes_disabled
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_multiple_sources_master_dev_merge_lists
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_includes_enabled_solves___env___with_mountpoint
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_root_and_mountpoint_parameters
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_master_dev_merge_lists
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_multiple_sources_dev_master_merge_lists
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_with_pillarenv
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_root_parameter
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_multiple_sources_master_dev_no_merge_lists
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_root_parameter
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_dev_master_no_merge_lists
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_multiple_sources_with_pillarenv
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_includes_enabled
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_mountpoint_parameter
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_dev_master_merge_lists
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_includes_disabled
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_multiple_sources_master_dev_no_merge_lists
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_multiple_sources_dev_master_no_merge_lists
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_includes_enabled
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_single_source
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_root_and_mountpoint_parameters
- integration.pillar.test_git_pillar.TestGitPythonHTTP.test_mountpoint_parameter
- integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP.test_includes_enabled_solves___env___with_mountpoint

**Comment by frogunder** [comment]
Seems to be fixed with https://github.com/saltstack/salt/pull/53015
