### ISSUE TITLE
unit.utils.test_master.MasterUtilsIsPidHealthyPsUtil.test_is_pid_healthy_running_salt

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52861]
Possibly a dupe of #52860 - definitely related

---

develop failed [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unit.utils.test_master/MasterUtilsIsPidHealthyPsUtil/test_is_pid_healthy_running_salt), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/unit.utils.test_master/MasterUtilsIsPidHealthyPsUtil/test_is_pid_healthy_running_salt), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/unit.utils.test_master/MasterUtilsIsPidHealthyPsUtil/test_is_pid_healthy_running_salt), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/unit.utils.test_master/MasterUtilsIsPidHealthyPsUtil/test_is_pid_healthy_running_salt)
---

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\utils\test_master.py", line 63, in test_is_pid_healthy_running_salt
    assert master.is_pid_healthy(1) is True
AssertionError
		
```

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
