### ISSUE TITLE
integration.states.test_bower.BowerStateTest.test_bower_installed_removed - cert not yet valid

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52875]
develop failed [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.states.test_bower/BowerStateTest/test_bower_installed_removed)
---

False is not True. Salt Comment: Error installing 'underscore': [{   "data": {     "endpoint": {       "name": "",       "source": "underscore",       "target": "*"     }   },   "id": "error",   "level": "error",   "message": "Request to https://registry.bower.io/packages/underscore failed: CERT_NOT_YET_VALID",   "stacktrace": "Error: Request to https://registry.bower.io/packages/underscore failed: CERT_NOT_YET_VALID\n    at createError (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/lib/util/createError.js:2:15)\n    at Request._callback (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/lib/lookup.js:97:29)\n    at self.callback (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/node_modules/request/request.js:188:22)\n    at Request.EventEmitter.emit (events.js:95:17)\n    at Request.request.emit (/usr/local/lib/node_modules/bower/lib/node_modules/request-replay/index.js:69:33)\n    at Request.onRequestError (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/node_modules/request/request.js:884:8)\n    at ClientRequest.EventEmitter.emit (events.js:95:17)\n    at CleartextStream.socketErrorListener (http.js:1561:9)\n    at CleartextStream.EventEmitter.emit (events.js:95:17)\n    at SecurePair.<anonymous> (tls.js:1389:19)" }]

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 129, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/states/test_bower.py", line 33, in test_bower_installed_removed
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 569, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
Error installing 'underscore': [{
  "data": {
    "endpoint": {
      "name": "",
      "source": "underscore",
      "target": "*"
    }
  },
  "id": "error",
  "level": "error",
  "message": "Request to https://registry.bower.io/packages/underscore failed: CERT_NOT_YET_VALID",
  "stacktrace": "Error: Request to https://registry.bower.io/packages/underscore failed: CERT_NOT_YET_VALID\n    at createError (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/lib/util/createError.js:2:15)\n    at Request._callback (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/lib/lookup.js:97:29)\n    at self.callback (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/node_modules/request/request.js:188:22)\n    at Request.EventEmitter.emit (events.js:95:17)\n    at Request.request.emit (/usr/local/lib/node_modules/bower/lib/node_modules/request-replay/index.js:69:33)\n    at Request.onRequestError (/usr/local/lib/node_modules/bower/lib/node_modules/bower-registry-client/node_modules/request/request.js:884:8)\n    at ClientRequest.EventEmitter.emit (events.js:95:17)\n    at CleartextStream.socketErrorListener (http.js:1561:9)\n    at CleartextStream.EventEmitter.emit (events.js:95:17)\n    at SecurePair.<anonymous> (tls.js:1389:19)"
}]
		
```

**Comment by waynew** [comment]
Fails in:

- integration.states.test_bower.BowerStateTest.test_bower_installed_from_file
- integration.states.test_bower.BowerStateTest.test_bower_installed_pkgs
- integration.states.test_bower.BowerStateTest.test_bower_installed_removed

**Comment by KChandrashekhar** [comment]
Not a blocker for the release. If not done by code complete date of Neon or any high priority, mark this for next release

**Comment by Ch3LL** [comment]
re-adding as a release blocker
