### ISSUE TITLE
integration.states.test_virtualenv_mod.VirtualenvTest.test_issue_2594_non_invalidated_cache - ensure pip is not available on Ubunut 18.04

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52870]
develop failed [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.states.test_virtualenv_mod/VirtualenvTest/test_issue_2594_non_invalidated_cache)
---

False is not True. Salt Comment: The virtual environment was not created successfully because ensurepip is not available.  On Debian/Ubuntu systems, you need to install the python3-venv package using the following command.      apt-get install python3-venv  You may need to use sudo with that command.  After installing the python3-venv package, recreate your virtual environment.  Failing command: ['/tmp/salt-tests-tmpdir/issue-2594-ve/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 563, in assertSaltTrueReturn
    self.assertTrue(saltret)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_virtualenv_mod.py", line 93, in test_issue_2594_non_invalidated_cache
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 569, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.

    apt-get install python3-venv

You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.

Failing command: ['/tmp/salt-tests-tmpdir/issue-2594-ve/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
		
```

We probably just need to just have the test states install python3-venv if the OS is ubuntu 18.04. There are a couple of test failures with this cause.

**Comment by frogunder** [comment]
Fixed by https://github.com/saltstack/salt/pull/53015
