### ISSUE TITLE
integration.ssh.test_state.SSHStateTest.test_state_show_top

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52884]
develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.ssh.test_state/SSHStateTest/test_state_show_top)
---

{'base': ['core']} != {'base': ['core', 'master_tops_test']} - {'base': ['core']} + {'base': ['core', 'master_tops_test']}

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/ssh/test_state.py", line 101, in test_state_show_top
    self.assertEqual(ret, {'base': ['core', 'master_tops_test']})
AssertionError: {'base': ['core']} != {'base': ['core', 'master_tops_test']}
- {'base': ['core']}
+ {'base': ['core', 'master_tops_test']}
		
```

It's possible the behavior is correct and the test just needs updating? Or, maybe something is broken.

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 10:53:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/217/
