### ISSUE TITLE
integration.reactor.test_reactor.ReactorTest.test_reactor_reaction - Timeout of 30 seconds reached

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52896]
develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_reaction)
---

Timeout of 30 seconds reached

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/reactor/test_reactor.py", line 81, in test_reactor_reaction
    event = master_event.get_event(full=True)
  File "/tmp/kitchen/testing/salt/utils/event.py", line 662, in get_event
    ret = self._get_event(wait, tag, match_func, no_block)
  File "/tmp/kitchen/testing/salt/utils/event.py", line 561, in _get_event
    raw = self.subscriber.read_sync(timeout=wait)
  File "/tmp/kitchen/testing/salt/transport/ipc.py", line 758, in read_sync
    self.io_loop.start()
  File "/usr/local/lib/python3.6/dist-packages/tornado/ioloop.py", line 863, in start
    event_pairs = self._impl.poll(poll_timeout)
  File "/tmp/kitchen/testing/tests/integration/reactor/test_reactor.py", line 56, in alarm_handler
    raise TimeoutException('Timeout of {0} seconds reached'.format(self.timeout))
integration.reactor.test_reactor.TimeoutException: Timeout of 30 seconds reached
		
```

**Comment by frogunder** [comment]
I can not replicate this test error, I cannot see it as failing anymore either on develop branch. Closing this issue.
