### ISSUE TITLE
integration.shell.test_enabled.EnabledTest.test_shell_disabled

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52898]
develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_disabled)
---

'first second third | wc -l ; export SALTY_VARI[57 chars]null' != 'first\nsecond\nthird\n|\nwc\n-l\n;\nexport\nSA[73 chars]null' - first second third | wc -l ; export SALTY_VARIABLE=saltines && echo $SALTY_VARIABLE ; echo duh &> /dev/null ?      ^      ^     ^ ^  ^  ^ ^      ^                       ^  ^    ^               ^ ^    ^   ^  ^ + first second third | wc -l ; export SALTY_VARIABLE=saltines && echo $SALTY_VARIABLE ; echo duh &> /dev/null ?      ^      ^     ^ ^  ^  ^ ^      ^                       ^  ^    ^               ^ ^    ^   ^  ^ 

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/shell/test_enabled.py", line 44, in test_shell_disabled
    self.assertEqual(ret, disabled_ret)
AssertionError: 'first second third | wc -l ; export SALTY_VARI[57 chars]null' != 'first\nsecond\nthird\n|\nwc\n-l\n;\nexport\nSA[73 chars]null'
- first second third | wc -l ; export SALTY_VARIABLE=saltines && echo $SALTY_VARIABLE ; echo duh &> /dev/null
?      ^      ^     ^ ^  ^  ^ ^      ^                       ^  ^    ^               ^ ^    ^   ^  ^
+ first
second
third
|
wc
-l
;
export
SALTY_VARIABLE=saltines
&&
echo
$SALTY_VARIABLE
;
echo
duh
&>
/dev/null
?      ^      ^     ^ ^  ^  ^ ^      ^                       ^  ^    ^               ^ ^    ^   ^  ^

		
```

Not sure exactly what's happening here but it looks an awful lot like something isn't properly getting processed...

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 10:53:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/217/

**Comment by Akm0d** [comment]
The fix for this needs to be cherry-picked into Neon

**Comment by xeacott** [comment]
> The fix for this needs to be cherry-picked into Neon

https://github.com/saltstack/salt/pull/53476
