### ISSUE TITLE
integration.runners.test_jobs.ManageTest.test_lookup_jid - {'retcode': 70} != {}

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52892]
This is a duplicate of an issue I was just looking at, but I can't seem to find it right now.

develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/integration.runners.test_jobs/ManageTest/test_lookup_jid)
---

{'retcode': 70} != {} - {'retcode': 70} + {}

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\runners\test_jobs.py", line 30, in test_lookup_jid
    self.assertEqual(ret['return'], {})
AssertionError: {'retcode': 70} != {}
- {'retcode': 70}
+ {}
		
```

**Comment by frogunder** [comment]
Closing this issue. I do not see this test failure anymore on the develop branch.
