### ISSUE TITLE
integration.shell.test_enabled.EnabledTest.test_shell_default_enabled - '0\nsaltines' != '3\nsaltines'

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52899]
develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.shell.test_enabled/EnabledTest/test_shell_default_enabled)
---

'0\nsaltines' != '3\nsaltines' - 0 + 3   saltines

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/shell/test_enabled.py", line 34, in test_shell_default_enabled
    self.assertEqual(ret.strip(), enabled_ret)
AssertionError: '0\nsaltines' != '3\nsaltines'
- 0
+ 3
  saltines
		
```

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 10:53:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/217/

**Comment by Akm0d** [comment]
This fix needs to be cherry-picked into Neon

**Comment by xeacott** [comment]
> This fix needs to be cherry-picked into Neon

https://github.com/saltstack/salt/pull/53476 <- This PR should fix the issue above and the other EnabledTest shell integration test.
