### ISSUE TITLE
integration.runners.test_jobs.ManageTest.test_active - {'20190506223455492284': {'Target-type': '[220 chars]et'}} != {}

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52893]
develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py3/19/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/integration.runners.test_jobs/ManageTest/test_active), [salt-windows-2019-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py3/60/testReport/junit/integration.runners.test_jobs/ManageTest/test_active)
---

{'20190506223455492284': {'Target-type': '[220 chars]et'}} != {} + {} - {'20190506223455492284': {'Arguments': [], -                           'Function': 'runner.jobs.active', -                           'Returned': [], -                           'Running': [{'minion': 4616}], -                           'StartTime': '2019, May 06 22:34:55.492284', -                           'Target': 'unknown-target', -                           'Target-type': 'list', -                           'User': 'sudo_EC2AMAZ-7S118UU\\Administrator'}}

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\runners\test_jobs.py", line 22, in test_active
    self.assertEqual(ret['return'], {})
AssertionError: {'20190506223455492284': {'Target-type': '[220 chars]et'}} != {}
+ {}
- {'20190506223455492284': {'Arguments': [],
-                           'Function': 'runner.jobs.active',
-                           'Returned': [],
-                           'Running': [{'minion': 4616}],
-                           'StartTime': '2019, May 06 22:34:55.492284',
-                           'Target': 'unknown-target',
-                           'Target-type': 'list',
-                           'User': 'sudo_EC2AMAZ-7S118UU\\Administrator'}}
		
```

Might be related to #52092 (same test), but different failure mode

**Comment by frogunder** [comment]
I don't see this test as failing anymore on develop branch in Jenkins. I cannot replicate it either. Closing this issue.
