### ISSUE TITLE
integration.reactor.test_reactor.ReactorTest.test_reactor_is_leader - {'retcode': 70} is not false

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52897]
develop failed [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py2/184/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-debian-8-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-8-py3/203/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-debian-9-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py2/185/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-debian-9-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-debian-9-py3/199/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-opensuse-42-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-opensuse-42-py3/69/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2/192/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-m2crypto/141/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-pycryptodomex/133/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py2-transport/155/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3/187/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-m2crypto/129/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1604-py3-pycryptodomex/140/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py2/202/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.reactor.test_reactor/ReactorTest/test_reactor_is_leader)
---

{'retcode': 70} is not false

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/reactor/test_reactor.py", line 104, in test_reactor_is_leader
    self.assertFalse(ret['return'])
AssertionError: {'retcode': 70} is not false
		
```

**Comment by frogunder** [comment]
I can not replicate this test error, I cannot see it as failing anymore either on develop branch. Closing this issue.
