### ISSUE TITLE
integration.modules.test_mine.MineTest.test_mine_flush

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52903]
Similar to #52087 but it looks like it might be a different issue? (Or, perhaps it's exactly the same underlying problem)

2018.3 failed [salt-fedora-28-py2](https://jenkinsci.saltstack.com/job/2018.3/job/salt-fedora-28-py2/188/testReport/junit/integration.modules.test_mine/MineTest/test_mine_flush)
---

{u'kernelrelease': u'5.0.9-100.fc28.x86_64', u'selinux': {u'enforced': u'Enforcing', u'enabled': True}, u'virtual': u'kvm', u'saltversioninfo': [2018, 3, 0, 0], u'systemd': {u'version': u'238', u'features': u'+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid'}, u'uuid': u'ec21bc67-d2db-c47f-487d-1eff6398669d', u'hwaddr_interfaces': {u'lo': u'00:00:00:00:00:00', u'eth0': u'02:fd:13:48:6e:56'}, u'init': u'systemd', u'lsb_distrib_id': u'Fedora', u'cpu_flags': [u'fpu', u'vme', u'de', u'pse', u'tsc', u'msr', u'pae', u'mce', u'cx8', u'apic', u'sep', u'mtrr', u'pge', u'mca', u'cmov', u'pat', u'pse36', u'clflush', u'mmx', u'fxsr', u'sse', u'sse2', u'ss', u'ht', u'syscall', u'nx', u'pdpe1gb', u'rdtscp', u'lm', u'constant_tsc', u'rep_good', u'nopl', u'xtopology', u'nonstop_tsc', u'cpuid', u'aperfmperf', u'tsc_known_freq', u'pni', u'pclmulqdq', u'ssse3', u'fma', u'cx16', u'pcid', u'sse4_1', u'sse4_2', u'x2apic', u'movbe', u'popcnt', u'tsc_deadline_timer', u'aes', u'xsave', u'avx', u'f16c', u'rdrand', u'hypervisor', u'lahf_lm', u'abm', u'3dnowprefetch', u'invpcid_single', u'pti', u'fsgsbase', u'tsc_adjust', u'bmi1', u'hle', u'avx2', u'smep', u'bmi2', u'erms', u'invpcid', u'rtm', u'mpx', u'avx512f', u'avx512dq', u'rdseed', u'adx', u'smap', u'clflushopt', u'clwb', u'avx512cd', u'avx512bw', u'avx512vl', u'xsaveopt', u'xsavec', u'xgetbv1', u'xsaves', u'ida', u'arat', u'pku', u'ospke'], u'match': u'maker', u'cpu_model': u'Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz', u'oscodename': u'Twenty Eight', u'gpus': [], u'num_gpus': 0, u'disks': [], u'productname': u'c5.xlarge', u'osarch': u'x86_64', u'machine_id': u'ec2db97b1746f1ca496490a45dd59c73', u'biosversion': u'1.0', u'kernel': u'Linux', u'domain': u'us-west-2.compute.internal', u'zookeeper': {u'username': u'daniel', u'password': u'test', u'hosts': u'localhost:2181', u'default_acl': [{u'username': u'daniel', u'read': True, u'create': True, u'write': True, u'admin': True, u'password': u'test', u'delete': True}], u'prod': {u'username': u'daniel', u'password': u'test', u'hosts': u'localhost:2181', u'default_acl': [{u'username': u'daniel', u'read': True, u'create': True, u'write': True, u'admin': True, u'password': u'test', u'delete': True}]}}, u'tokenv2': {u'keystone.endpoint': u'http://localhost:35357/v2.0', u'keystone.token': u'administrator'}, u'tokenv3': {u'keystone.endpoint': u'http://localhost:35357/v3', u'keystone.token': u'administrator'}, u'ip_interfaces': {u'lo': [u'127.0.0.1', u'::1'], u'eth0': [u'10.200.42.71', u'fe80::fd:13ff:fe48:6e56']}, u'mem_total': 7622, u'mdadm': [], u'companions': {u'one': [u'susan', u'ian', u'barbara']}, u'osfullname': u'Fedora', u'test_grain': u'cheese', u'localhost': u'ip-10-200-42-71.us-west-2.compute.internal', u'demov3': {u'keystone.password': u'demopass', u'keystone.tenant': u'demo', u'keystone.user': u'demo', u'keystone.auth_url': u'http://127.0.0.1:5000/v3/'}, u'demov2': {u'keystone.password': u'demopass', u'keystone.tenant': u'demo', u'keystone.user': u'demo', u'keystone.auth_url': u'http://127.0.0.1:5000/v2.0/'}, u'lsb_distrib_release': u'28', u'salttesting-grain-key': [], u'server_id': 266635400, u'saltpath': u'/tmp/kitchen/testing/salt', u'host': u'ip-10-200-42-71', u'osfinger': u'Fedora-28', u'biosreleasedate': u'10/16/2017', u'manufacturer': u'Amazon EC2', u'kernelversion': u'#1 SMP Mon Apr 22 02:13:09 UTC 2019', u'ip4_gw': u'10.200.32.1', u'fqdn': u'ip-10-200-42-71.us-west-2.compute.internal', u'alot': u'many', u'os': u'Fedora', u'pythonpath': [u'/tmp/kitchen/testing', u'/tmp/kitchen/testing/tests', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib/python2.7/site-packages/git/ext/gitdb', u'/tmp/salt-tests-tmpdir/scripts', u'/tmp/kitchen/testing/tests/support/coverage', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib/python27.zip', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7/plat-linux2', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7/lib-tk', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7/lib-old', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7/lib-dynload', u'/usr/lib64/python2.7', u'/usr/lib/python2.7', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib/python2.7/site-packages', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib/python2.7/site-packages/gitdb/ext/smmap'], u'a_custom': {u'k2': u'v2'}, u'path': u'/tmp/kitchen/testing/tests/integration/mockbin:/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', u'SSDs': [u'nvme0n1'], u'ps': u'ps -efHww', u'locale_info': {u'detectedencoding': u'UTF-8', u'defaultlanguage': u'en_US', u'defaultencoding': u'UTF-8'}, u'ip_gw': True, u'script': u'grail', u'osrelease_info': [28], u'gid': 0, u'master': u'localhost', u'ipv4': [u'10.200.42.71', u'127.0.0.1'], u'dns': {u'domain': u'', u'sortlist': [], u'nameservers': [u'10.200.0.2'], u'ip4_nameservers': [u'10.200.0.2'], u'search': [u'us-west-2.compute.internal'], u'ip6_nameservers': [], u'options': []}, u'ipv6': [u'::1', u'fe80::fd:13ff:fe48:6e56'], u'username': u'root', u'shell': u'/bin/bash', u'saltversion': u'2018.3.0-1192-gd375bae', u'pythonversion': [2, 7, 15, u'final', 0], u'zfs_feature_flags': False, u'level1': {u'level2': u'foo'}, u'cpuarch': u'x86_64', u'uid': 0, u'zmqversion': u'4.3.1', u'serialnumber': u'ec21bc67-d2db-c47f-487d-1eff6398669d', u'pid': 1656, u'groupname': u'root', u'planets': [u'mercury', u'venus', u'earth', u'mars'], u'zfs_support': False, u'id': u'minion', u'osrelease': u'28', u'adminv2': {u'keystone.password': u'adminpass', u'keystone.tenant': u'admin', u'keystone.user': u'admin', u'keystone.auth_url': u'http://127.0.0.1:5000/v2.0/'}, u'adminv3': {u'keystone.password': u'adminpass', u'keystone.tenant': u'admin', u'keystone.user': u'admin', u'keystone.auth_url': u'http://127.0.0.1:5000/v3/'}, u'ip6_interfaces': {u'lo': [u'::1'], u'eth0': [u'fe80::fd:13ff:fe48:6e56']}, u'num_cpus': 4, u'ip4_interfaces': {u'lo': [u'127.0.0.1'], u'eth0': [u'10.200.42.71']}, u'fqdn_ip4': [u'10.200.42.71'], u'fqdn_ip6': [u'fe80::fd:13ff:fe48:6e56'], u'nodename': u'ip-10-200-42-71.us-west-2.compute.internal', u'ip6_gw': False, u'osmajorrelease': 28, u'os_family': u'RedHat', u'pythonexecutable': u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/bin/python2.7', u'swap_total': 0, u'lsb_distrib_codename': u'', u'setgrain': u'grainval'} != None

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_mine.py", line 106, in test_mine_flush
    self.assertEqual(ret_flushed.get('minion', None), None)
AssertionError: {u'kernelrelease': u'5.0.9-100.fc28.x86_64', u'selinux': {u'enforced': u'Enforcing', u'enabled': True}, u'virtual': u'kvm', u'saltversioninfo': [2018, 3, 0, 0], u'systemd': {u'version': u'238', u'features': u'+PAM +AUDIT +SELINUX +IMA -APPARMOR +SMACK +SYSVINIT +UTMP +LIBCRYPTSETUP +GCRYPT +GNUTLS +ACL +XZ +LZ4 +SECCOMP +BLKID +ELFUTILS +KMOD +IDN2 -IDN +PCRE2 default-hierarchy=hybrid'}, u'uuid': u'ec21bc67-d2db-c47f-487d-1eff6398669d', u'hwaddr_interfaces': {u'lo': u'00:00:00:00:00:00', u'eth0': u'02:fd:13:48:6e:56'}, u'init': u'systemd', u'lsb_distrib_id': u'Fedora', u'cpu_flags': [u'fpu', u'vme', u'de', u'pse', u'tsc', u'msr', u'pae', u'mce', u'cx8', u'apic', u'sep', u'mtrr', u'pge', u'mca', u'cmov', u'pat', u'pse36', u'clflush', u'mmx', u'fxsr', u'sse', u'sse2', u'ss', u'ht', u'syscall', u'nx', u'pdpe1gb', u'rdtscp', u'lm', u'constant_tsc', u'rep_good', u'nopl', u'xtopology', u'nonstop_tsc', u'cpuid', u'aperfmperf', u'tsc_known_freq', u'pni', u'pclmulqdq', u'ssse3', u'fma', u'cx16', u'pcid', u'sse4_1', u'sse4_2', u'x2apic', u'movbe', u'popcnt', u'tsc_deadline_timer', u'aes', u'xsave', u'avx', u'f16c', u'rdrand', u'hypervisor', u'lahf_lm', u'abm', u'3dnowprefetch', u'invpcid_single', u'pti', u'fsgsbase', u'tsc_adjust', u'bmi1', u'hle', u'avx2', u'smep', u'bmi2', u'erms', u'invpcid', u'rtm', u'mpx', u'avx512f', u'avx512dq', u'rdseed', u'adx', u'smap', u'clflushopt', u'clwb', u'avx512cd', u'avx512bw', u'avx512vl', u'xsaveopt', u'xsavec', u'xgetbv1', u'xsaves', u'ida', u'arat', u'pku', u'ospke'], u'match': u'maker', u'cpu_model': u'Intel(R) Xeon(R) Platinum 8124M CPU @ 3.00GHz', u'oscodename': u'Twenty Eight', u'gpus': [], u'num_gpus': 0, u'disks': [], u'productname': u'c5.xlarge', u'osarch': u'x86_64', u'machine_id': u'ec2db97b1746f1ca496490a45dd59c73', u'biosversion': u'1.0', u'kernel': u'Linux', u'domain': u'us-west-2.compute.internal', u'zookeeper': {u'username': u'daniel', u'password': u'test', u'hosts': u'localhost:2181', u'default_acl': [{u'username': u'daniel', u'read': True, u'create': True, u'write': True, u'admin': True, u'password': u'test', u'delete': True}], u'prod': {u'username': u'daniel', u'password': u'test', u'hosts': u'localhost:2181', u'default_acl': [{u'username': u'daniel', u'read': True, u'create': True, u'write': True, u'admin': True, u'password': u'test', u'delete': True}]}}, u'tokenv2': {u'keystone.endpoint': u'http://localhost:35357/v2.0', u'keystone.token': u'administrator'}, u'tokenv3': {u'keystone.endpoint': u'http://localhost:35357/v3', u'keystone.token': u'administrator'}, u'ip_interfaces': {u'lo': [u'127.0.0.1', u'::1'], u'eth0': [u'10.200.42.71', u'fe80::fd:13ff:fe48:6e56']}, u'mem_total': 7622, u'mdadm': [], u'companions': {u'one': [u'susan', u'ian', u'barbara']}, u'osfullname': u'Fedora', u'test_grain': u'cheese', u'localhost': u'ip-10-200-42-71.us-west-2.compute.internal', u'demov3': {u'keystone.password': u'demopass', u'keystone.tenant': u'demo', u'keystone.user': u'demo', u'keystone.auth_url': u'http://127.0.0.1:5000/v3/'}, u'demov2': {u'keystone.password': u'demopass', u'keystone.tenant': u'demo', u'keystone.user': u'demo', u'keystone.auth_url': u'http://127.0.0.1:5000/v2.0/'}, u'lsb_distrib_release': u'28', u'salttesting-grain-key': [], u'server_id': 266635400, u'saltpath': u'/tmp/kitchen/testing/salt', u'host': u'ip-10-200-42-71', u'osfinger': u'Fedora-28', u'biosreleasedate': u'10/16/2017', u'manufacturer': u'Amazon EC2', u'kernelversion': u'#1 SMP Mon Apr 22 02:13:09 UTC 2019', u'ip4_gw': u'10.200.32.1', u'fqdn': u'ip-10-200-42-71.us-west-2.compute.internal', u'alot': u'many', u'os': u'Fedora', u'pythonpath': [u'/tmp/kitchen/testing', u'/tmp/kitchen/testing/tests', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib/python2.7/site-packages/git/ext/gitdb', u'/tmp/salt-tests-tmpdir/scripts', u'/tmp/kitchen/testing/tests/support/coverage', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib/python27.zip', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7/plat-linux2', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7/lib-tk', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7/lib-old', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib64/python2.7/lib-dynload', u'/usr/lib64/python2.7', u'/usr/lib/python2.7', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib/python2.7/site-packages', u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/lib/python2.7/site-packages/gitdb/ext/smmap'], u'a_custom': {u'k2': u'v2'}, u'path': u'/tmp/kitchen/testing/tests/integration/mockbin:/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', u'SSDs': [u'nvme0n1'], u'ps': u'ps -efHww', u'locale_info': {u'detectedencoding': u'UTF-8', u'defaultlanguage': u'en_US', u'defaultencoding': u'UTF-8'}, u'ip_gw': True, u'script': u'grail', u'osrelease_info': [28], u'gid': 0, u'master': u'localhost', u'ipv4': [u'10.200.42.71', u'127.0.0.1'], u'dns': {u'domain': u'', u'sortlist': [], u'nameservers': [u'10.200.0.2'], u'ip4_nameservers': [u'10.200.0.2'], u'search': [u'us-west-2.compute.internal'], u'ip6_nameservers': [], u'options': []}, u'ipv6': [u'::1', u'fe80::fd:13ff:fe48:6e56'], u'username': u'root', u'shell': u'/bin/bash', u'saltversion': u'2018.3.0-1192-gd375bae', u'pythonversion': [2, 7, 15, u'final', 0], u'zfs_feature_flags': False, u'level1': {u'level2': u'foo'}, u'cpuarch': u'x86_64', u'uid': 0, u'zmqversion': u'4.3.1', u'serialnumber': u'ec21bc67-d2db-c47f-487d-1eff6398669d', u'pid': 1656, u'groupname': u'root', u'planets': [u'mercury', u'venus', u'earth', u'mars'], u'zfs_support': False, u'id': u'minion', u'osrelease': u'28', u'adminv2': {u'keystone.password': u'adminpass', u'keystone.tenant': u'admin', u'keystone.user': u'admin', u'keystone.auth_url': u'http://127.0.0.1:5000/v2.0/'}, u'adminv3': {u'keystone.password': u'adminpass', u'keystone.tenant': u'admin', u'keystone.user': u'admin', u'keystone.auth_url': u'http://127.0.0.1:5000/v3/'}, u'ip6_interfaces': {u'lo': [u'::1'], u'eth0': [u'fe80::fd:13ff:fe48:6e56']}, u'num_cpus': 4, u'ip4_interfaces': {u'lo': [u'127.0.0.1'], u'eth0': [u'10.200.42.71']}, u'fqdn_ip4': [u'10.200.42.71'], u'fqdn_ip6': [u'fe80::fd:13ff:fe48:6e56'], u'nodename': u'ip-10-200-42-71.us-west-2.compute.internal', u'ip6_gw': False, u'osmajorrelease': 28, u'os_family': u'RedHat', u'pythonexecutable': u'/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/bin/python2.7', u'swap_total': 0, u'lsb_distrib_codename': u'', u'setgrain': u'grainval'} != None
		
```

**Comment by twangboy** [comment]
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/50/testReport/junit/integration.modules.test_mine/MineTest/test_mine_flush/

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 21, 2019 7:57:00 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/53/
