### ISSUE TITLE
tearDownClass (integration.states.test_docker_network.DockerNetworkTestCase) - bytes-like required, not 'str'

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52918]
2019.2.1 failed [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/23/testReport/junit/tearDownClass (integration.states/test_docker_network/DockerNetworkTestCase))
---

a bytes-like object is required, not 'str'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_docker_network.py", line 132, in tearDownClass
    if process.returncode != 0 and 'No such image' not in output:
TypeError: a bytes-like object is required, not 'str'
		
```

**Comment by Ch3LL** [comment]
not failing anymore
