### ISSUE TITLE
integration.modules.test_cp.CPModuleTest.test_get_url_https - u'Bootstrap' not found in u''

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52916]
2019.2.1 failed [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1404-py2/20/testReport/junit/integration.modules.test_cp/CPModuleTest/test_get_url_https)
develop failed [salt-ubuntu-1404-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1404-py2/200/testReport/junit/integration.modules.test_cp/CPModuleTest/test_get_url_https)
---

u'Bootstrap' not found in u''

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 975, in <lambda>
    lambda testcase, *args, **kwargs: self.wrap(testcase, *args, **kwargs)  # pylint: disable=W0108
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 983, in wrap
    return self.func(testcase, name, *args, **kwargs)
  File "/tmp/kitchen/testing/tests/integration/modules/test_cp.py", line 298, in test_get_url_https
    self.assertIn('Bootstrap', data)
AssertionError: u'Bootstrap' not found in u''
		
```

**Comment by KChandrashekhar** [comment]
This defect is on a OS version that has attained EOL. Hence not fixing this
