### ISSUE TITLE
unittest.loader.ModuleImportFailure.unit.cloud.clouds.test_joyent - ImportError: No module named Crypto.Hash

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52914]
2018.3 failed [salt-centos-7-py2-m2crypto](https://jenkinsci.saltstack.com/job/2018.3/job/salt-centos-7-py2-m2crypto/131/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/2018.3/job/salt-ubuntu-1604-py2-m2crypto/132/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent)
develop failed [salt-windows-2016-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/19/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/66/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent)
---

Failed to import test module: unit.cloud.clouds.test_joyent Traceback (most recent call last):   File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests     module = self._get_module_from_name(name)   File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name     __import__(name)   File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\cloud\clouds\test_joyent.py", line 20, in <module>     from salt.cloud.clouds import joyent   File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\cloud\clouds\joyent.py", line 66, in <module>     from Crypto.Hash import SHA256 ImportError: No module named Crypto.Hash 

```

ImportError: Failed to import test module: unit.cloud.clouds.test_joyent
Traceback (most recent call last):
  File "C:\Python27\lib\unittest\loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "C:\Python27\lib\unittest\loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\cloud\clouds\test_joyent.py", line 20, in <module>
    from salt.cloud.clouds import joyent
  File "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\salt\cloud\clouds\joyent.py", line 66, in <module>
    from Crypto.Hash import SHA256
ImportError: No module named Crypto.Hash

		
```

Also failing on test `unittest.loader._FailedTest.unit.cloud.clouds.test_joyent`

**Comment by DmitryKuzmenko** [comment]
The same is on windows, 2019.2:

https://jenkinsci.saltstack.com/job/2019.2/job/salt-windows-2016-py2/90/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent/
