### ISSUE TITLE
integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_reconnect - failed to build image

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52919]
2019.2.1 failed [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/23/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_reconnect)
---

Failed to build image

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_docker_network.py", line 90, in wrapper
    build_image()
  File "/tmp/kitchen/testing/tests/integration/states/test_docker_network.py", line 75, in build_image
    raise Exception('Failed to build image')
Exception: Failed to build image
		
```

**Comment by waynew** [comment]
Also fails in:

- integration.states.test_docker_network.DockerNetworkTestCase.test_absent_with_disconnected_container
- integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_containers
- integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_no_reconnect

**Comment by Ch3LL** [comment]
not failing anymore https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/31/
