### ISSUE TITLE
integration.modules.test_shadow.ShadowModuleTest.test_set_del_root_password - '!locked' != None

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52924]
2019.2.1 failed [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/integration.modules.test_shadow/ShadowModuleTest/test_set_del_root_password)
---

'!locked' != None

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 129, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/modules/test_shadow.py", line 240, in test_set_del_root_password
    self.assertEqual(self.run_function('shadow.info', ['root'])['passwd'], self._password)
AssertionError: '!locked' != None
		
```

**Comment by dmurphy18** [comment]
@waynew F28 is EOL soon, should we be doing this on F30, or testing on F28 at all

**Comment by Ch3LL** [comment]
im not seeing this fail anymore

**Comment by twangboy** [comment]
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/50/testReport/junit/integration.modules.test_shadow/ShadowModuleTest/test_set_del_root_password/

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/56/
