### ISSUE TITLE
integration.states.test_beacon.BeaconStateTestCase.test_present_absent - Beacon "diskusage" is not available

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52926]
2019.2.1 failed [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/23/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1804-py3/21/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent), [salt-amazon-2-py3](https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-amazon-2-py3/96/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent/)
2018.3 failed [dwoz-fedora28-py3](https://jenkinsci.saltstack.com/job/2018.3/job/dwoz-fedora28-py3/8/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent), [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2018.3/job/salt-fedora-28-py3/194/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2018.3/job/salt-opensuse-15-py3/68/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent)
develop failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-ubuntu-1804-py3/203/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent)
---

False is not True. Salt Comment: Beacon "diskusage" is not available.

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 563, in assertSaltTrueReturn
    self.assertTrue(saltret)
  File "/usr/lib/python3.6/unittest/case.py", line 682, in assertTrue
    raise self.failureException(msg)
AssertionError: False is not true

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_beacon.py", line 39, in test_present_absent
    self.assertSaltTrueReturn(ret)
  File "/tmp/kitchen/testing/tests/support/mixins.py", line 569, in assertSaltTrueReturn
    **(next(six.itervalues(ret)))
AssertionError: False is not True. Salt Comment:
Beacon "diskusage" is not available.
		
```

**Comment by garethgreenaway** [comment]
Seems like this one might be taken care of with this https://github.com/saltstack/salt/pull/52814

**Comment by DmitryKuzmenko** [comment]
2019.2:
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-fedora-29-py3/144/testReport/junit/integration.states.test_beacon/BeaconStateTestCase/test_present_absent/

**Comment by Akm0d** [comment]
This fix needs to be cherry-picked into Neon
