### ISSUE TITLE
integration.modules.test_shadow.ShadowModuleTest.test_unlock_password

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52922]
2019.2.1 failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/integration.modules.test_shadow/ShadowModuleTest/test_unlock_password)
---

False is not true

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 129, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/modules/test_shadow.py", line 173, in test_unlock_password
    self.assertTrue(self.run_function('shadow.unlock_password', [self._test_user]))
AssertionError: False is not true
		
```

**Comment by Ch3LL** [comment]
confirmed they are passing now here:

https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/57/consoleFull

**Comment by DmitryKuzmenko** [comment]
The same is in 2017.7:

https://jenkinsci.saltstack.com/job/2017.7/job/salt-fedora-29-py2/107/testReport/junit/integration.modules.test_shadow/ShadowModuleTest/test_unlock_password/

Need a backport?
