### ISSUE TITLE
integration.modules.test_dockermod.DockerCallTestCase.test_docker_call

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52921]
2019.2.1 failed [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/23/testReport/junit/integration.modules.test_dockermod/DockerCallTestCase/test_docker_call)
---

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_dockermod.py", line 85, in test_docker_call
    assert ret is True
AssertionError
		
```

**Comment by Ch3LL** [comment]
this is no longer failing.https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-opensuse-15-py3/31/
