### ISSUE TITLE
unit.serializers.test_serializers.TestSerializers.test_sls_aggregate

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52927]
2019.2.1 failed [salt-fedora-28-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/21/testReport/junit/unit.serializers.test_serializers/TestSerializers/test_sls_aggregate), [salt-fedora-29-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py2/21/testReport/junit/unit.serializers.test_serializers/TestSerializers/test_sls_aggregate)
---

{a: lol, foo: [hello], bar: [1, 2, 3], baz: {a: 42, b: 666, c: the beast}}

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/serializers/test_serializers.py", line 187, in test_sls_aggregate
    """).strip() == yamlex.serialize(sls_obj), sls_obj
AssertionError: {a: lol, foo: [hello], bar: [1, 2, 3], baz: {a: 42, b: 666, c: the beast}}
		
```

**Comment by Ch3LL** [comment]
this should be fixed by https://github.com/saltstack/salt/pull/52957
