### ISSUE TITLE
unit.modules.test_vsphere.RenameDatastoreTestCase.test_supported_proxes - name 'vim' 'Disconnect' is not defined

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52923]
2019.2.1 failed [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py3/21/testReport/junit/unit.modules.test_vsphere/RenameDatastoreTestCase/test_supported_proxes), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/21/testReport/junit/unit.modules.test_vsphere/RenameDatastoreTestCase/test_supported_proxes)
develop failed [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/develop/job/salt-fedora-29-py3/122/testReport/junit/unit.modules.test_vsphere/RenameDatastoreTestCase/test_supported_proxes)
---

name 'vim' is not defined

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 484, in disconnect
    Disconnect(service_instance)
NameError: name 'Disconnect' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/modules/vsphere.py", line 384, in _gets_service_instance_via_proxy
    salt.utils.vmware.disconnect(local_service_instance)
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 485, in disconnect
    except vim.fault.NoPermission as exc:
NameError: name 'vim' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 484, in disconnect
    Disconnect(service_instance)
NameError: name 'Disconnect' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/modules/test_vsphere.py", line 1786, in test_supported_proxes
    vsphere.rename_datastore('current_ds_name', 'new_ds_name')
  File "/tmp/kitchen/testing/salt/modules/vsphere.py", line 295, in __supports_proxies
    return fn(*args, **salt.utils.args.clean_kwargs(**kwargs))
  File "/tmp/kitchen/testing/salt/modules/vsphere.py", line 389, in _gets_service_instance_via_proxy
    salt.utils.vmware.disconnect(local_service_instance)
  File "/tmp/kitchen/testing/salt/utils/vmware.py", line 485, in disconnect
    except vim.fault.NoPermission as exc:
NameError: name 'vim' is not defined
		
```

**Comment by waynew** [comment]
Also fails in:

- unit.utils.test_vmware.GetRootFolderTestCase.test_raise_runtime_fault
- unit.modules.test_vsphere.CreateDatacenterTestCase.test_returned_value
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_erase_disk_partitions
- unit.utils.test_vmware.GetHostsTestCase.test_get_all_host_flag_not_set_and_no_host_names
- unit.utils.test_vmware.UpdateDvsTestCase.test_reconfigure_dvs_task_raises_runtime_fault
- unit.utils.test_vmware.GetDatacentersTestCase.test_get_mors_with_properties_call
- unit.utils.test_vmware.GetLicenseAssignmentManagerTestCase.test_raise_no_permission
- unit.modules.test_vsphere.ListClusterTestCase.test_no_cluster_raises_argument_value_error
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_no_permission
- unit.utils.test_vmware.SetDvsNetworkResourceManagementEnabledTestCase.test_enable_network_resource_management_raises_vim_fault
- unit.utils.test_vmware.UnregisterVirtualMachineTestCase.test_unregister_vm_raise_vim_fault
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_default_params
- unit.utils.test_vmware.WaitForTaskTestCase.test_inner_loop_task_info_raise_runtime_fault
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_system_fault
- unit.utils.test_vmware.SetDvsNetworkResourceManagementEnabledTestCase.test_enable_network_resource_management_raises_no_permission
- unit.utils.test_vmware.GetHostsTestCase.test_get_si_no_datacenter_no_cluster
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_instance_uuid_raises_no_permission
- unit.utils.test_vmware.UpdateDvsTestCase.test_reconfigure_dvs_task_raises_no_permission
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_get_diskgroups
- unit.utils.test_vmware.GetLicenseManagerTestCase.test_raise_runtime_fault
- unit.utils.test_vmware.GetDatacentersTestCase.test_get_all_datastores
- unit.utils.test_vmware.AssignLicenseTestCase.test_instance_uuid_raises_no_permission
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_multiple_datastores_found
- unit.utils.test_vmware.GetHostsTestCase.test_no_hosts
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_no_disk_id_or_scsi_address
- unit.utils.test_vmware.SetDvsNetworkResourceManagementEnabledTestCase.test_enable_network_resource_management_raises_runtime_fault
- unit.utils.test_vmware.GetHostsTestCase.test_filter_hostname
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_success_output
- unit.utils.test_vmware.RenameDatastoreTestCase.test_rename_datastore_raise_no_permission
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_invalid_argument_no_fault_message
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_invalid_argument_with_fault_message
- unit.utils.test_vmware.WaitForTaskTestCase.test_first_task_info_raise_no_permission
- unit.utils.test_vmware.WaitForTaskTestCase.test_inner_loop_task_info_raise_no_permission
- unit.modules.test_vsphere.CreateDatacenterTestCase.test_default_service_instance
- unit.utils.test_vmware.CreateDvportgroupTestCase.test_create_dvporgroup_task_raises_vim_fault
- unit.utils.test_vmware.GetDatacentersTestCase.test_datastore_found
- unit.utils.test_vmware.CreateDvsTestCase.test_get_managed_object_name_call
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_remove_capacity_from_diskgroup_data_evacuation_false
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_query_assigned_licenses_raises_vim_fault
- unit.modules.test_vsphere.CreateDatacenterTestCase.test_supported_proxies
- unit.utils.test_vmware.RegisterVirtualMachineTestCase.test_register_vm_raise_vim_fault
- unit.utils.test_vmware.GetLicenseAssignmentManagerTestCase.test_raise_runtime_fault
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_invalid_schema_validation
- unit.utils.test_vmware.CreateDvportgroupTestCase.test_create_dvporgroup_task_raises_no_permission
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test__get_proxy_target_call
- unit.utils.test_vmware.GetLicenseAssignmentManagerTestCase.test_raise_vim_fault
- unit.utils.test_vmware.UpdateVirtualMachineTestCase.test_update_vm_raise_runtime_fault
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_scsi_address_not_found
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_remove_capacity_from_diskgroup
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_rename_datastore_call
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_instance_uuid_raises_runtime_fault
- unit.utils.test_vmware.GetRootFolderTestCase.test_raise_vim_fault
- unit.utils.test_vmware.CreateDvsTestCase.test_create_dvs_task_raises_runtime_fault
- unit.utils.test_vmware.GetServiceInfoTestCase.test_about_raises_runtime_fault
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_query_assigned_licenses_raises_no_permission
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_get_proxy_target
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_get_datastore_call
- unit.utils.test_vmware.IsConnectionToAVCenterTestCase.test_api_type_raise_runtime_fault
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_exception
- unit.utils.test_vmware.CreateDvsTestCase.test_get_network_folder
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_supported_proxes
- unit.utils.test_vmware.RegisterVirtualMachineTestCase.test_register_vm_raise_runtime_fault
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_datastore_not_found
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_instance_uuid_raises_vim_fault
- unit.modules.test_vsphere.ListClusterTestCase.test_supported_proxies
- unit.utils.test_vmware.IsConnectionToAVCenterTestCase.test_api_type_raise_vim_fault
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_supported_proxies
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_returned_array
- unit.utils.test_vmware.DeleteVirtualMachineTestCase.test_destroy_vm_raise_vim_fault
- unit.utils.test_vmware.GetHostsTestCase.test_get_si_datacenter_name_and_cluster_name
- unit.utils.test_vmware.AssignLicenseTestCase.test_update_assigned_licenses_raises_runtime_fault
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_get_datastores_call
- unit.utils.test_vmware.RenameDatastoreTestCase.test_rename_datastore_raise_vim_fault
- unit.utils.test_vmware.GetHostsTestCase.test_filter_cluster
- unit.utils.test_vmware.IsConnectionToAVCenterTestCase.test_api_type_raise_no_permission
- unit.utils.test_vmware.RenameDatastoreTestCase.test_rename_datastore_raise_runtime_fault
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_supported_proxes
- unit.utils.test_vmware.GetDatacentersTestCase.test_get_mors_with_properties_returns_empty_array
- unit.utils.test_vmware.WaitForTaskTestCase.test_first_task_info_raise_vim_fault
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_supported_proxies
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_defined_datacenter_names
- unit.modules.test_vsphere.EraseDiskPartitionsTestCase.test_scsi_address_to_disk_id_map
- unit.utils.test_vmware.CreateVirtualMachineTestCase.test_create_vm_raise_runtime_fault
- unit.utils.test_vmware.AssignLicenseTestCase.test_update_assigned_licenses_raises_vim_fault
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_supported_proxes
- unit.utils.test_vmware.CreateVirtualMachineTestCase.test_create_vm_host_task_call
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_disk_not_found_safety_checks_set
- unit.utils.test_vmware.GetDatacentersTestCase.test_datastore_not_found
- unit.utils.test_vmware.CreateClusterTestCase.test_create_cluster_raise_vim_fault
- unit.utils.test_vmware.CreateDvsTestCase.test_create_dvs_task_raises_no_permission
- unit.utils.test_vmware.GetLicensesTestCase.test_raise_no_permission
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_diskgroup_not_found
- unit.utils.test_vmware.UpdateVirtualMachineTestCase.test_update_vm_raise_vim_fault
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_success_output
- unit.utils.test_vmware.CreateDatacenterTestCase.test_create_datacenter_raise_no_permission
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_supported_proxes
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_validate
- unit.modules.test_vsphere.ListClusterTestCase.test_default_service_instance
- unit.modules.test_vsphere.ListDatacentersViaProxyTestCase.test_get_managed_object_name_calls
- unit.utils.test_vmware.CreateClusterTestCase.test_create_cluster_raise_no_permission
- unit.utils.test_vmware.GetServiceInfoTestCase.test_about_raises_vim_fault
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_default_service_instance
- unit.utils.test_vmware.CreateVirtualMachineTestCase.test_create_vm_raise_no_permission
- unit.utils.test_vmware.GetDatacentersTestCase.test_no_parameters
- unit.utils.test_vmware.GetAssignedLicensesTestCase.test_query_assigned_licenses_raises_runtime_fault
- unit.utils.test_vmware.AssignLicenseTestCase.test_instance_uuid_raises_runtime_fault
- unit.utils.test_vmware.UpdateDvsTestCase.test_reconfigure_dvs_task_raises_vim_fault
- unit.utils.test_vmware.UpdateDvportgroupTestCase.test_reconfigure_dvporgroup_task_raises_no_permission
- unit.utils.test_vmware.WaitForTaskTestCase.test_first_task_info_raise_runtime_fault
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test_get_disks
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_disk_group_not_found_safety_checks_set
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_remove_datastore_call
- unit.utils.test_vmware.AssignLicenseTestCase.test_instance_uuid_raises_vim_fault
- unit.modules.test_vsphere.ListClusterTestCase.test_get_cluster_call
- unit.utils.test_vmware.UpdateClusterTestCase.test_reconfigure_compute_resource_raise_vim_fault
- unit.utils.test_vmware.CreateDvportgroupTestCase.test_create_dvporgroup_task_raises_runtime_fault
- unit.utils.test_vmware.CreateDatacenterTestCase.test_create_datacenter_raise_vim_fault
- unit.utils.test_vmware.RemoveDvportgroupTestCase.test_destroy_treconfigure_dvporgroup_task_raises_runtime_fault
- unit.utils.test_vmware.RegisterVirtualMachineTestCase.test_register_vm_raise_no_permission
- unit.utils.test_vmware.WaitForTaskTestCase.test_info_error_vim_fault
- unit.utils.test_vmware.RemoveDvportgroupTestCase.test_destroy_task_raises_no_permission
- unit.utils.test_vmware.GetLicensesTestCase.test_raise_vim_fault
- unit.utils.test_vmware.CreateDvsTestCase.test_create_dvs_task_raises_vim_fault
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_remove_disk_group_data_accessibility_false
- unit.utils.test_vmware.UpdateClusterTestCase.test_reconfigure_compute_resource_raise_runtime_fault
- unit.utils.test_vmware.GetHostsTestCase.test_host_get_all_hosts
- unit.utils.test_vmware.UpdateDvportgroupTestCase.test_reconfigure_dvporgroup_task_raises_vim_fault
- unit.utils.test_vmware.GetLicenseManagerTestCase.test_raise_vim_fault
- unit.utils.test_vmware.UpdateClusterTestCase.test_reconfigure_compute_resource_raise_no_permission
- unit.utils.test_vmware.CreateDatacenterTestCase.test_create_datacenter_runtime_fault
- unit.utils.test_vmware.WaitForTaskTestCase.test_inner_loop_task_info_raise_vim_fault
- unit.utils.test_vmware.CreateVirtualMachineTestCase.test_create_vm_raise_vim_fault
- unit.modules.test_vsphere.ListClusterTestCase.test__get_cluster_dict_call
- unit.utils.test_vmware.CreateClusterTestCase.test_create_cluster_raise_runtime_fault
- unit.utils.test_vmware.GetHostsTestCase.test_get_si_datacenter_name_no_cluster_name
- unit.utils.test_vmware.UnregisterVirtualMachineTestCase.test_unregister_vm_raise_runtime_fault
- unit.modules.test_vsphere.RemoveCapacityFromDiskgroupTestCase.test__get_proxy_target_call
- unit.utils.test_vmware.AssignLicenseTestCase.test_update_assigned_licenses_raises_no_permission
- unit.modules.test_vsphere.RenameDatastoreTestCase.test_get_no_datastores
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_get_disk_groups
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test__get_proxy_target_call
- unit.utils.test_vmware.UpdateDvportgroupTestCase.test_reconfigure_dvporgroup_task_raises_runtime_fault
- unit.utils.test_vmware.GetHostsTestCase.test_one_host_returned
- unit.utils.test_vmware.GetLicensesTestCase.test_raise_runtime_fault
- unit.utils.test_vmware.RemoveDvportgroupTestCase.test_destroy_treconfigure_dvporgroup_task_raises_vim_fault
- unit.utils.test_vmware.GetRootFolderTestCase.test_raise_no_permission
- unit.utils.test_vmware.GetLicenseManagerTestCase.test_raise_no_permission
- unit.modules.test_vsphere.RemoveDiskgroupTestCase.test_remove_disk_group
- unit.modules.test_vsphere.RemoveDatastoreTestCase.test_success_output
- unit.utils.test_vmware.GetServiceInfoTestCase.test_about_raises_no_permission
- unit.utils.test_vmware.DeleteVirtualMachineTestCase.test_destroy_vm_raise_runtime_fault

**Comment by garethgreenaway** [comment]
Passing in 2019.2.1 here https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py3/51/, related to #52047 which was fixed with nox.  Should be fixed on develop once nox is in place there.
