### ISSUE TITLE
integration.modules.test_mine.MineTest.test_mine_delete - KeyError: u'minion'

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52931]
2019.2.1 failed [salt-fedora-28-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/21/testReport/junit/integration.modules.test_mine/MineTest/test_mine_delete)
2018.3 failed [dwoz-fedora28-py2](https://jenkinsci.saltstack.com/job/2018.3/job/dwoz-fedora28-py2/10/testReport/junit/integration.modules.test_mine/MineTest/test_mine_delete), [salt-fedora-28-py2](https://jenkinsci.saltstack.com/job/2018.3/job/salt-fedora-28-py2/188/testReport/junit/integration.modules.test_mine/MineTest/test_mine_delete)
---

u'minion'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/modules/test_mine.py", line 128, in test_mine_delete
    self.assertEqual(ret_grains['minion']['id'], 'minion')
KeyError: u'minion'
		
```

Might be an encoding issue for the grains keys. I don't think this is a dupe of #52087

**Comment by twangboy** [comment]
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/50/testReport/junit/integration.modules.test_mine/MineTest/test_mine_delete/

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 21, 2019 7:57:00 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/53/
