### ISSUE TITLE
unit.serializers.test_serializers.TestSerializers.test_serialize_complex_sls

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#52930]
2019.2.1 failed [salt-fedora-28-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-28-py2/21/testReport/junit/unit.serializers.test_serializers/TestSerializers/test_serialize_complex_sls), [salt-fedora-29-py2](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-29-py2/21/testReport/junit/unit.serializers.test_serializers/TestSerializers/test_serialize_complex_sls)
---

foo: 1 bar: 2 baz: true

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/serializers/test_serializers.py", line 82, in test_serialize_complex_sls
    assert serialized == '{foo: 1, bar: 2, baz: true}', serialized
AssertionError: foo: 1
bar: 2
baz: true
		
```

**Comment by Ch3LL** [comment]
Fixed by https://github.com/saltstack/salt/pull/52957
