### ISSUE TITLE
NACL dec enconding

### ISSUE THREAD

**Issue by tacf** [saltstack/salt#52960]
### Description of Issue/Question
When using `{{ salt.nacl.dec('....')` in pillar it renders the string as `b'..'`. Which afaik seems related to python 3 way of handling string.

The solution was to add `....decode('utf-8')` in the nacl module return, for example, `return b.decrypt(base64.b64decode(data)).decode('utf-8')`.

Am i missing something on python environment configuration? How do i work around this? 

### Setup
Salt-version: 2019.2.0
Nacl code from pr #51818

Dockerized environment

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.9.125-linuxkit
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by garethgreenaway** [comment]
@tacf Thanks for the report.  You are correct, the issue you're running into and the one you linked to are because of the differences between  how strings are handled in Py2 vs Py3, the issue as it relates to Salt is related to the fact that as much of the code is now using bytes where possible. Unfortunately there are a lot of instances where a string is still needed, the fix here (https://github.com/saltstack/salt/pull/51913/)   corrects that in the nacl code.

**Comment by tacf** [comment]
As a matter of fact I'm overwriting nacl module with the code from the PR you linked. In that case it fixes the handling of the pk and sk being missing from the config files, but I'm pretty sure it does not fix the issue with the return type of the decryption functions.

**Comment by garethgreenaway** [comment]
@tacf Thanks for that clarification.  I'll need to double check the code but that sounds right.

**Comment by syphernl** [comment]
@garethgreenaway It appears that this is still causing issues on Salt 2019.2.2 (running on Python 3.6.8). We're now using the `yaml_encode` Jinja filter as a workaround (since `.decode('utf-8')` doesn't look too good / is longer.

**Comment by syphernl** [comment]
Unstale

**Comment by gee456** [comment]
This is still a problem in 3004.1 , The fix sounded simple, why can't it be implemented? Do I need to open a new Bug request?
