### ISSUE TITLE
Sporadic KeyError: 'runner' in reactor

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#52961]
### Description of Issue/Question
A salt-master has only one runner that reacts on the minion_ping event  of 3000 client..

The runner works fine, but there are sporadic errors in `/var/log/salt/master` like the one below 

What does this error mean?

```
2019-05-10 05:41:54,280 [salt.utils.reactor:423 ][ERROR   ][22195] Reactor 'minion_ping_reaction' failed to execute runner 'minion_ping_runner.main'
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/reactor.py", line 391, in run
    react_fun = self.client_cache[low['state']].functions.get(low['fun'])
  File "/usr/lib/python2.7/site-packages/salt/utils/cache.py", line 70, in __getitem__
    return dict.__getitem__(self, key)
KeyError: u'runner'

```
### Versions Report

Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

Minions are 2016 Windows

**Comment by garethgreenaway** [comment]
@markuskramerIgitt Thanks for the report.  Can you provide the contents of the reactor in question that is producing these messages?

**Comment by markuskramerIgitt** [comment]
The reactor has just 4 lines, apart from the comments

```
# /srv/salt/reactor/minion_ping_reactor.sls (Yaml syntax)
#

minion_ping_reaction:
  runner.minion_ping_runner.main:
    - arg:
      - {{ data }}
```

**Comment by markuskramerIgitt** [comment]
@garethgreenaway I assume `KeyError: u'runner'` refers to `runner.minion_ping_runner.main`?

**Comment by markuskramerIgitt** [comment]
@garethgreenaway, do you need more input?

**Comment by markuskramerIgitt** [comment]
2 times a week
I can neglect that
