### ISSUE TITLE
boto3 client returns a SQS url that is different from the one seen in the UI

### ISSUE THREAD

**Issue by Saravana9210** [saltstack/salt#52974]
### Setup

Python version 3.7

### Steps to Reproduce Issue
1. Create boto3 client
2. Get SQS url using following code:
`sqs = boto3.client('sqs')
response = sqs.get_queue_url(QueueName='saravana-queue')
print(response['QueueUrl'])`

Output: 
https://ap-south-1.queue.amazonaws.com/{accountId}/saravana-queue

3. Get SQS url through CLI
`aws sqs get-queue-url --queue-name saravana-queue`

Output:
{
    "QueueUrl": "https://ap-south-1.queue.amazonaws.com/{accountId}/saravana-queue"
}

4. But, the actual queue url seen in the UI is 
"https://sqs.ap-south-1.amazonaws.com/{accountId}/saravana-queue"

**Comment by s-sebastian** [comment]
Why do you think this is related to SaltStack?

This is more likely related to this Python [bug](https://github.com/aws/aws-cli/issues/1715).

It seems to work fine with other AWS SDKs like Go for instance:

```
package main

import (
    "fmt"

    "github.com/aws/aws-sdk-go/aws"
    "github.com/aws/aws-sdk-go/aws/session"
    "github.com/aws/aws-sdk-go/service/sqs"
)

func main() {
    sess, err := session.NewSession(&aws.Config{
        Region: aws.String("ap-south-1")},
    )

    svc := sqs.New(sess)

    result, err := svc.GetQueueUrl(&sqs.GetQueueUrlInput{
        QueueName: aws.String("test"),
    })

    if err != nil {
        fmt.Println("Error", err)
        return
    }

    fmt.Println("Success", *result.QueueUrl)
}
```
```
# go run main.go 
Success https://sqs.ap-south-1.amazonaws.com/<account-id>/test
```

**Comment by Saravana9210** [comment]
My kind apologies! Posted in a wrong repo.

**Comment by anilfunde** [comment]
I just went though boto source and found a solution for boto client. If you want get_queue_url to return URL in format {service}.{region}.amazonaws.com , use "endpoint_url" argument while creating client

    sqs_client = boto3.client(
        'sqs',
        aws_access_key_id=#####,
        aws_secret_access_key=#####,
        region_name=####,
        endpoint_url='https://sqs.' + {region_name} + '.amazonaws.com'
    ) 
sqs client created this way will return queue url in the desired format
