### ISSUE TITLE
query for Grain role:database did not resolve for test.ping

### ISSUE THREAD

**Issue by sidharthavadla16** [saltstack/salt#52978]
[root@salt ~]# salt 'minion2' grains.set 'role' database
minion2:
   ----------
   changes:
       ----------
       role:
           database
   comment:
   result:
       True
[root@salt ~]# salt 'minion2' grains.fetch role
minion2:
   database
[root@salt ~]# salt -G 'role:database' test.ping
minion2:
   Minion did not return. [No response]
ERROR: Minions returned with non-zero exit code

**Comment by max-arnold** [comment]
If you are using Salt 2019.2.0, then it is a known issue #51934 that will be fixed in 2019.2.1

**Comment by garethgreenaway** [comment]
Duplicate of #51934 so closing out.
