### ISSUE TITLE
Documentation supports usage of () when should be {} in modules disk.smart_attributes attributes=(var)

### ISSUE THREAD

**Issue by swilson-cxp** [saltstack/salt#52970]
### Description of Issue/Question
Usage of module.disk.smart_attributes fails when specifying attributes=(values)
error is a bash syntax error as ( wasn't expected. Documentation for usage of the module supports parenthesis, using curly braces works correctly this a suggestion on documentation adjustment.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Install smartmontools, salt-minion (optionally salt-master)
no special configs or SLS necessary
Smartctl version 6.6

### Steps to Reproduce Issue
Attempt salt '*' disk.smart_attributes /dev/(disk) attributes=(values)

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: LinuxMint 3 cindy
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: LinuxMint 3 cindy

**Comment by garethgreenaway** [comment]
@swilson-cxp Thanks for the report.  Can you provide an error or log message you receive which makes you think the documentation is incorrect?  The value in the documentation would produce a tuple, which is used later to see if the results returned from smartctl are ones included in the requested attributes.

**Comment by swilson-cxp** [comment]
@garethgreenaway Sure thing. 
Problem is it doesn't produce an error log that would be made by salt as its a bash syntax issue. Syntax checking would have me escape the \(\) at which point salt would provide an invalid arguments error otherwise if I don't escape them will get a syntax error.
Example Bash:
`sudo salt '*' disk.smart_attributes /dev/sda attributes=(5,187,188,197,198)`
Invalid Arguments Error from \(\) escaped:
`Passed invalid arguments to disk.smart_attributes: coercing to Unicode: need string or buffer, in found`
Bash Syntax Error using ():
`bash: syntax error near unexpected token `('`
This error is related to bash expecting it to equal something such as a string or integer parenthesis are not an expected in this case.
Refer to documentation for disk.smart_attributes 2019.2.0 https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.disk.html
It's referring to bash cli usage however will get a syntax error if using that documentation.
using {} in place of () doesn't cause any bash syntax issues and works as expected.
