### ISSUE TITLE
pkg.upgrade does not handle --allow-downgrades for apt dist-upgrade

### ISSUE THREAD

**Issue by mitroko** [saltstack/salt#52977]
### Cannot pass kwargs to pkg.upgrade function in aptpkg.py. It does not allow to set --allow-downgrades option for apt command.
See code block for explanation:
https://github.com/saltstack/salt/blob/develop/salt/modules/aptpkg.py#L1047-L1054

### Setup
salt-call 2017.7.8 (Nitrogen)
Ubuntu 16.04 Xenial

### Steps to Reproduce Issue
salt-call pkg.upgrade dist_upgrade=true kwargs=["allow_downgrades"]

### Versions Report
master = minion = Nitrogen

Expected:
kwargs=["allow_downgrades"]

    if kwargs.get('allow_downgrades', False):
        cmd.append('--allow-downgrades')

Once fixed, please backport to older releases as well: 2016.x/2017.x/2018.x

**Comment by garethgreenaway** [comment]
@mitroko Thanks for the report.  This would be a new addition so labeling it as a feature.  We no longer support 2016.x branches and 2017.x branches are now only updated for security releases.  It should, however, be something that we can add to 2018.3.  Thanks!

**Comment by jakelyz** [comment]
Is there still desire for this to be added? If so, I would like to take it

**Comment by mitroko** [comment]
Please do so. I am still interested.
