### ISSUE TITLE
integration.states.test_docker_network - OpenSUSE

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53006]
integration.states.test_docker_network.DockerNetworkTestCase.test_present_enable_ipv6
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_enable_ipv6), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_enable_ipv6)

integration.states.test_docker_network.DockerNetworkTestCase.test_present_internal test
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_internal), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_internal)

integration.states.test_docker_network.DockerNetworkTestCase.test_present_labels
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_labels), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_labels)

integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_custom_ipv4
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_custom_ipv4), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_custom_ipv4)

integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_custom_ipv6
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_custom_ipv6), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_custom_ipv6)

integration.states.test_docker_network.DockerNetworkTestCase.test_absent_with_disconnected_container
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_absent_with_disconnected_container), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_absent_with_disconnected_container)

integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_containers
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_containers), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_containers)

integration.states.test_docker_network.DockerNetworkTestCase.test_present_with_reconnect
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_reconnect), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_with_reconnect)

integration.modules.test_dockermod.DockerCallTestCase.test_docker_call test
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.modules.test_dockermod/DockerCallTestCase/test_docker_call), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.modules.test_dockermod/DockerCallTestCase/test_docker_call)

integration.modules.test_dockermod.DockerCallTestCase.test_docker_highstate
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.modules.test_dockermod/DockerCallTestCase/test_docker_highstate), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.modules.test_dockermod/DockerCallTestCase/test_docker_highstate)

integration.modules.test_dockermod.DockerCallTestCase.test_docker_sls
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.modules.test_dockermod/DockerCallTestCase/test_docker_sls), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.modules.test_dockermod/DockerCallTestCase/test_docker_sls)

integration.states.test_docker_network.DockerNetworkTestCase.test_present_attachable test failures
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_attachable), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present_attachable)

integration.states.test_docker_network.DockerNetworkTestCase.test_present test failures
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_present)

integration.states.test_docker_network.DockerNetworkTestCase.test_absent
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_absent), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.states.test_docker_network/DockerNetworkTestCase/test_absent)

tearDownClass (integration.states.test_docker_network.DockerNetworkTestCase)
---
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/tearDownClass (integration.states/test_docker_network/DockerNetworkTestCase)), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/tearDownClass (integration.states/test_docker_network/DockerNetworkTestCase))

**Comment by KChandrashekhar** [comment]
Test is failing on 2019.2 branch and not on 2019.2.1 so it will be fixed in 2019.2.2 release
