### ISSUE TITLE
unittest.loader._FailedTest.unit.states.test_grafana_datasource test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53007]
2019.2 failed [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-28-py3/79/testReport/junit/unittest.loader._FailedTest.unit/states/test_grafana_datasource), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-29-py3/79/testReport/junit/unittest.loader._FailedTest.unit/states/test_grafana_datasource)
---

Failed to import test module: unit.states.test_grafana_datasource Traceback (most recent call last):   File "/usr/lib64/python3.7/unittest/loader.py", line 436, in _find_test_path     module = self._get_module_from_name(name)   File "/usr/lib64/python3.7/unittest/loader.py", line 377, in _get_module_from_name     __import__(name)   File "/tmp/kitchen/testing/tests/unit/states/test_grafana_datasource.py", line 17, in <module>     import salt.states.grafana_datasource as grafana_datasource   File "/tmp/kitchen/testing/salt/states/grafana_datasource.py", line 29, in <module>     import requests   File "/usr/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>     import urllib3   File "/usr/lib/python3.7/site-packages/urllib3/__init__.py", line 8, in <module>     from .connectionpool import (   File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 11, in <module>     from .exceptions import (   File "/usr/lib/python3.7/site-packages/urllib3/exceptions.py", line 2, in <module>     from .packages.six.moves.http_client import ( ModuleNotFoundError: No module named 'urllib3.packages.six' 

```

ImportError: Failed to import test module: unit.states.test_grafana_datasource
Traceback (most recent call last):
  File "/usr/lib64/python3.7/unittest/loader.py", line 436, in _find_test_path
    module = self._get_module_from_name(name)
  File "/usr/lib64/python3.7/unittest/loader.py", line 377, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/unit/states/test_grafana_datasource.py", line 17, in <module>
    import salt.states.grafana_datasource as grafana_datasource
  File "/tmp/kitchen/testing/salt/states/grafana_datasource.py", line 29, in <module>
    import requests
  File "/usr/lib/python3.7/site-packages/requests/__init__.py", line 43, in <module>
    import urllib3
  File "/usr/lib/python3.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python3.7/site-packages/urllib3/connectionpool.py", line 11, in <module>
    from .exceptions import (
  File "/usr/lib/python3.7/site-packages/urllib3/exceptions.py", line 2, in <module>
    from .packages.six.moves.http_client import (
ModuleNotFoundError: No module named 'urllib3.packages.six'

		
```

**Comment by KChandrashekhar** [comment]
Test is failing on 2019.2 branch and not on 2019.2.1 so it will be fixed in 2019.2.2 release
