### ISSUE TITLE
integration.cloud.clouds.test_joyent.JoyentTest.test_instance

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53009]
2019.2 failed [salt-centos-7-py2-cloud](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-cloud/77/testReport/junit/integration.cloud.clouds.test_joyent/JoyentTest/test_instance)
---

u'CLOUD-TEST-VGUFIG' not found in []

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_joyent.py", line 76, in test_instance
    [i.strip() for i in self.run_cloud('-p joyent-test {0}'.format(INSTANCE_NAME), timeout=500)]
AssertionError: u'CLOUD-TEST-VGUFIG' not found in []

**Comment by Akm0d** [comment]
Joyent is EOL very soon and we are removing the Joyent tests from 2019.2.1
