### ISSUE TITLE
integration.runners.test_salt.SaltRunnerTest.test_salt_cmd_invalid test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53013]
2019.2 failed [salt-centos-7-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2/79/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-centos-7-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-m2crypto/80/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-centos-7-py2-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-transport/73/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-centos-7-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3/75/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-centos-7-py3-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3-m2crypto/82/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-centos-7-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3-pycryptodomex/81/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-centos-7-py3-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3-transport/73/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-fedora-28-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-28-py3/79/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-29-py3/79/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/67/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-opensuse-15-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py3/64/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1604-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2/78/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-m2crypto/78/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-pycryptodomex/79/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-transport/74/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3/77/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1604-py3-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3-m2crypto/78/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3-pycryptodomex/82/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1604-py3-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3-transport/73/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1804-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1804-py2/79/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-ubuntu-1804-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1804-py3/81/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-windows-2016-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-windows-2016-py3/24/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-windows-2019-py2/63/testReport/junit/integration.runners.test_salt/SaltRunnerTest/test_salt_cmd_invalid)
---

u'Passed invalid arguments:' not found in u'Exception occurred in runner salt.cmd: Traceback (most recent call last):\n  File "C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\kitchen\\\\testing\\salt\\client\\mixins.py", line 374, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\nTypeError: cmd() takes at least 1 argument (0 given)\n'

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\integration\runners\test_salt.py", line 35, in test_salt_cmd_invalid
    self.assertIn(expected, ret['return'])
AssertionError: u'Passed invalid arguments:' not found in u'Exception occurred in runner salt.cmd: Traceback (most recent call last):\n  File "C:\\\\Users\\\\ADMINI~1\\\\AppData\\\\Local\\\\Temp\\\\kitchen\\\\testing\\salt\\client\\mixins.py", line 374, in low\n    data[\'return\'] = self.functions[fun](*args, **kwargs)\nTypeError: cmd() takes at least 1 argument (0 given)\n'
		
```

**Comment by KChandrashekhar** [comment]
Test is failing on 2019.2 branch and not on 2019.2.1 so it will be fixed in 2019.2.2 release
