### ISSUE TITLE
integration.cloud.clouds.test_gce failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53012]
integration.cloud.clouds.test_gce.GCETest.test_instance_extra test failures
=======

2019.2 failed [salt-centos-7-py2-cloud](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-cloud/77/testReport/junit/integration.cloud.clouds.test_gce/GCETest/test_instance_extra), [salt-centos-7-py3-cloud](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3-cloud/77/testReport/junit/integration.cloud.clouds.test_gce/GCETest/test_instance_extra)
---

'cloud-test-mqge3x:' not found in []

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 212, in wrap
    raise exc
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 209, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_gce.py", line 118, in test_instance_extra
    self.assertIn(ret_str, instance)
AssertionError: 'cloud-test-mqge3x:' not found in []


integration.cloud.clouds.test_gce.GCETest.test_instance test failures
=======

2019.2 failed [salt-centos-7-py2-cloud](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-cloud/77/testReport/junit/integration.cloud.clouds.test_gce/GCETest/test_instance), [salt-centos-7-py3-cloud](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py3-cloud/77/testReport/junit/integration.cloud.clouds.test_gce/GCETest/test_instance)
---

'cloud-test-fv10bo:' not found in []

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 212, in wrap
    raise exc
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 209, in wrap
    return caller(cls)
  File "/tmp/kitchen/testing/tests/integration/cloud/clouds/test_gce.py", line 87, in test_instance
    self.assertIn(ret_str, instance)
AssertionError: 'cloud-test-fv10bo:' not found in []
		
```

**Comment by Ch3LL** [comment]
seeing this fail on 2019.2.1 now: https://jenkinsci.saltstack.com/job/2019.2.1/view/Cloud/job/salt-centos-7-py3-cloud/99/testReport/junit/integration.cloud.clouds.test_gce/GCETest/test_instance_extra/

**Comment by Ch3LL** [comment]
i'm also seeing integration.cloud.clouds.test_gce.GCETest.test_instance fail:

https://jenkinsci.saltstack.com/job/2019.2.1/view/Cloud/job/salt-centos-7-py3-cloud/99/testReport/junit/integration.cloud.clouds.test_gce/GCETest/test_instance/

**Comment by Akm0d** [comment]
Verified the bug, it looks as though our SSL certificates for accessing the gce test machine is expired

**Comment by Akm0d** [comment]
@bryceml let's see if a certificate has expired in GCE and renew it

**Comment by Akm0d** [comment]
updated gce keys for jenkins https://github.com/saltstack/sre-jenkins/commit/4e22a4d76eacfcbaa3d481578710ecde323e79c2

**Comment by Akm0d** [comment]
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/support/helpers.py", line 212, in wrap
    raise exc
AssertionError: u'cloud-test-bbe7og' not found in u''

**Comment by Akm0d** [comment]
This error might be related to all the cloud tests failing
```
[ERROR   ] Exception raised when processing __virtual__ function for salt.loaded.int.clouds.openstack. Module will not be loaded: global name 'shade' is not defined
[WARNING ] salt.loaded.int.clouds.openstack.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'openstack', please fix this.
```

**Comment by gtmanfred** [comment]
/shrug

I have no access to run or see those tests anymore.  But they were passing last year when i wrote it.
