### ISSUE TITLE
debian.saltstack.com no longer working

### ISSUE THREAD

**Issue by mattayes** [saltstack/salt#53028]
### Description of Issue/Question

Attempting to access [debian.saltstack.com](http://debian.saltstack.com/) results in timeouts. My team is using an old version of Salt that is only available here (not available on [repo.saltstack.com](https://repo.saltstack.com)), which we can no longer download given these timeouts.

Reached out on the Slack community page and @gtmanfred recommended I open an issue. Why did debian.saltstack.com go away? Can you bring it back?

### Setup

N/A

### Steps to Reproduce Issue

Visit http://debian.saltstack.com/.

### Versions Report

N/A

**Comment by garethgreenaway** [comment]
@mattayes thanks for the report.  The site in question is back online, it will however be taken offline and replaced with a different site at a later today, still to be determined. The packages that are hosted there are no longer supported.

**Comment by mattayes** [comment]
Thanks @garethgreenaway! Did you mean "at a later date" or "later today"?

I get that they're not supported, we're working to get off those old versions, though it'll take some time. If you could let me know when the site will be taken down (or point me to where I can find that info when the decision is made) I'd greatly appreciate it.

**Comment by garethgreenaway** [comment]
@mattayes Apologies.  Yup!  At a later date.  We'll make sure to make an announcement in community Slack, the Salt mailing lists and  I'll update this ticket with the new information.

**Comment by mattayes** [comment]
@garethgreenaway Did those Slack/mailing list announcements go out?

**Comment by sagetherage** [comment]
@garethgreenaway can you do a bit more follow up here, please?
