### ISSUE TITLE
Documentation of Minion Keys

### ISSUE THREAD

**Issue by Linuturk** [saltstack/salt#53032]
### Description of Issue/Question

I'm having trouble finding technical documentation on the type of encryption keys used for authorization of salt minions, and the encryption of the traffic sent on ports 4505 and 4506. Is there a white paper or other similar technical documentation?

**Comment by garethgreenaway** [comment]
@Linuturk Thanks for the question.  Does this page answer your question, https://docs.saltstack.com/en/getstarted/system/communication.html?

**Comment by Linuturk** [comment]
That page covers the communication at a high level, but doesn't include things like key strength, the mechanics of the RSA key vs the AES rotating key, the negotiation process between the master minion, and a host of other things. I'm looking for something more technical that would be useful to a security team in understanding the deep detail of these things.

**Comment by garethgreenaway** [comment]
@saltstack/team-core Anyone know of any additional documentation with this information?

**Comment by waynew** [comment]
I'm not aware of any, but I think that this would be a great thing for us to have!

**Comment by Linuturk** [comment]
If I wanted to review the code that ensures unauthorized minions don't get access to things on port 4505 and 4506, where would I start?

**Comment by sbehrens** [comment]
Specifically we'd like to understand if we had a publically exposed ZeroMQ port (4505, 4506) what security controls are in place to prevent:

1.) Unauthorized access to those ports to read or put messages on the queue
2.) Denial of service attacks on those ports.

**Comment by waynew** [comment]
I'm not sure about DOS attacks - I don't know that Salt does anything to mitigate that (or what they really could. Though I suppose doing something like https://nullprogram.com/blog/2019/03/22/ could help).

https://github.com/saltstack/salt/blob/develop/salt/master.py#L646 is probably as good a spot as any if you're looking at doing some in depth auditing. You'll also probably want to check out the ReqServer in that file

The (no longer appropriately named) AESFuncs class in there is also worth a review. I'm not sure what else you'd want to see, but that should give you a great jumping off point for anything else you're interested in.

**Comment by sbehrens** [comment]
Thanks for the tips, this was helpful.

**Comment by Linuturk** [comment]
https://docs.saltstack.com/en/latest/topics/development/architecture.html I found this page as well that demystifies some things.
