### ISSUE TITLE
syndic logs are not rotated in rpm

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#53040]
### Description of Issue/Question
There is not rotation for syndic logs.

### Versions Report
all version

**Comment by garethgreenaway** [comment]
@dmurphy18 FYI.

**Comment by tsaridas** [comment]
ping

**Comment by tsaridas** [comment]
ping @dmurphy18

**Comment by sagetherage** [comment]
@dmurphy18 can you follow here, please?

**Comment by dmurphy18** [comment]
@tsaridas From what I understand (asked around) Salt does not do log rotation, that is dependent on the underlying OS and logrotate command for example.  However I am digging deeper on this since that seems strange that there would not be a config setting for that. Will let you know what I find.

**Comment by dmurphy18** [comment]
@tsaridas  Shall add /var/log/salt/syndic to logrotate files, also noticed no api logs either.  This should be fixed soon in a release
