### ISSUE TITLE
unittest.loader.ModuleImportFailure.unit.cloud.clouds.test_joyent test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53067]
2018.3 failed [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/2018.3/job/salt-ubuntu-1604-py2-m2crypto/153/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent)
2019.2 failed [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/69/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent), [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-windows-2019-py2/65/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent)
2019.2.1 failed [salt-centos-7-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-m2crypto/43/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-pycryptodomex/41/testReport/junit/unittest.loader.ModuleImportFailure.unit.cloud/clouds/test_joyent)
---

Failed to import test module: unit.cloud.clouds.test_joyent Traceback (most recent call last):   File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests     module = self._get_module_from_name(name)   File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name     __import__(name)   File "/tmp/kitchen/testing/tests/unit/cloud/clouds/test_joyent.py", line 38, in <module>     @skipIf(joyent.HAS_REQUIRED_CRYPTO is False, reason='PyCrypto or Cryptodome not installed') AttributeError: 'module' object has no attribute 'HAS_REQUIRED_CRYPTO' 

```

ImportError: Failed to import test module: unit.cloud.clouds.test_joyent
Traceback (most recent call last):
  File "/usr/lib/python2.7/unittest/loader.py", line 254, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib/python2.7/unittest/loader.py", line 232, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/unit/cloud/clouds/test_joyent.py", line 38, in <module>
    @skipIf(joyent.HAS_REQUIRED_CRYPTO is False, reason='PyCrypto or Cryptodome not installed')
AttributeError: 'module' object has no attribute 'HAS_REQUIRED_CRYPTO'

		
```

**Comment by Ch3LL** [comment]
no longer failing here: https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-pycryptodomex/53/
