### ISSUE TITLE
salt-api: Minion targetting

### ISSUE THREAD

**Issue by AmbicaY** [saltstack/salt#53075]
### Description of Issue/Question
While using a salt-api, how can we use minion targetting like ones mentioned here:
https://docs.saltstack.com/en/latest/topics/targeting/compound.html#targeting-compound

Currently when I use salt api, I use tgt. But how can I do more complex minion targetting through salt-api?

**Comment by garethgreenaway** [comment]
@AmbicaY Thanks for the report.  You can use the same targeting types when using the API, you just need an additional argument in your call.  For example, the following will target all minions that have the `os` grain of Ubuntu:
```
$ curl -sSk http://localhost:5555 \   
    -H 'Accept: application/x-yaml' \
    -H 'X-Auth-Token: xxxxxxxxxxxxxxxxxxxxxxxxxx'\
    -d client=local \
    -d tgt='G@os:Ubuntu' -d tgt_type='compound' \
    -d fun=test.ping
```
