### ISSUE TITLE
load_yaml renders strings with commas as a list

### ISSUE THREAD

**Issue by heaje** [saltstack/salt#53077]
### Description of Issue/Question
I'm using the load_yaml jinja function to read in some yaml to a Jinja variable.  I've found that if any keys in that yaml are a string that has commas in it, the returned value will be wrong. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Create a test sls file that looks like this on any host with a minion:
```
{% load_yaml as test %}
test: "test2,test3,test4"
{% endload %}

{{test}}
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

On the host with the test SLS file, run this:
```salt-call slsutil.renderer /path/to/test.sls```

Notice the output is incorrect:
```
local:
    ----------
    test:
        u'test2
    test3:
        None
    test4':
        None
```

What I expected was:
```
local:
    ----------
    test:
        test2,test3,test4
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core
```

**Comment by heaje** [comment]
I've tried multiple ways of representing the string and they all have the same issue.  I've tried things like this:

```test: !!str "test2,test3,test4"```
```test: '"test2,test3,test4"'

**Comment by garethgreenaway** [comment]
@heaje Thanks for the report.  Sounds like a solution was found, if you believe this to be resolve please feel free to close out this issue.  Thanks!

**Comment by heaje** [comment]
@garethgreenaway - I feel like what I found is a workaround rather than a solution.  Is what I was seeing the expected behavior?
