### ISSUE TITLE
unit.roster.test_ansible.AnsibleRosterTestCase.test_script test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53083]
2019.2 failed [salt-centos-7-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-pycryptodomex/85/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-debian-8-py2/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-29-py3/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/70/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-m2crypto/81/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-pycryptodomex/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-tornado](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-tornado/76/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-transport/77/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3/80/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script)
2019.2.1 failed [salt-centos-7-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-m2crypto/46/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-centos-7-py2-transport](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-transport/41/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-pycryptodomex/44/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-transport/45/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-pycryptodomex/44/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script)
---

'ungrouped'

```

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/roster/test_ansible.py", line 99, in test_script
    ret = ansible.targets('*')
  File "/tmp/kitchen/testing/salt/roster/ansible.py", line 124, in targets
    hosts = [host for host in _get_hosts_from_group('all') if fnmatch.fnmatch(host, tgt)]
  File "/tmp/kitchen/testing/salt/roster/ansible.py", line 134, in _get_hosts_from_group
    hosts.extend(_get_hosts_from_group(child))
  File "/tmp/kitchen/testing/salt/roster/ansible.py", line 132, in _get_hosts_from_group
    hosts = [host for host in inventory[group].get('hosts', [])]
KeyError: 'ungrouped'
		
```

**Comment by twangboy** [comment]
Neon failing on `salt-amazon-1-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1804-py2`

Error:
```
Unable to run command '[u'ansible-inventory', u'-i', u'/tmp/kitchen/testing/tests/unit/files/rosters/ansible/roster.py', u'--list']' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -2, u'env': {'LC_NUMERIC': 'C', 'TESTS_XML_OUTPUT_DIR': '/tmp/kitchen/testing/artifacts/xml-unittests-output', 'SSH_DAEMON_RUNNING': 'True', 'TESTS_LOG_LEVEL': '2', 'LC_CTYPE': 'C', 'SSH_CLIENT': '10.200.4.87 58324 22', 'LOGNAME': 'root', 'USER': 'root', 'SYSTEMROOT': '', 'LC_PAPER': 'C', 'HOME': '/home/ubuntu', 'UCF_FORCE_CONFFOLD': '1', 'COVERAGE_PROCESS_START': '/tmp/kitchen/testing/.coveragerc', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'LANGUAGE': 'C', 'LC_MEASUREMENT': 'C', 'APT_LISTCHANGES_FRONTEND': 'none', 'PYTHONPATH': '/tmp/kitchen/testing/tests/support/coverage', 'SUDO_USER': 'ubuntu', 'DESTRUCTIVE_TESTS': 'True', 'LC_MONETARY': 'C', 'USERNAME': 'root', 'CI': '1', 'XDG_RUNTIME_DIR': '/run/user/1000', 'SUDO_COMMAND': '/usr/bin/env CI=1 nox -f /tmp/kitchen/testing/noxfile.py -e runtests-zeromq-2.7(coverage=True) -- --output-columns=120 --sysinfo --xml=/tmp/kitchen/testing/artifacts/xml-unittests-output -v --run-destructive --ssh-tests', 'LC_ADDRESS': 'C', 'DEBIAN_FRONTEND': 'noninteractive', 'SUDO_UID': '1000', 'PATH': '/tmp/kitchen/testing/.nox/runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin', 'TESTS_MIN_LOG_LEVEL_NAME': 'DEBUG', 'XDG_SESSION_ID': '4', '_': '/usr/bin/sudo', 'LC_IDENTIFICATION': 'C', 'SUDO_GID': '1000', 'LC_MESSAGES': 'C', 'COVERAGE_FILE': '/tmp/kitchen/testing/.coverage', 'SSH_TTY': '/dev/pts/0', 'LC_COLLATE': 'C', 'LC_TELEPHONE': 'C', 'SHLVL': '1', 'PWD': '/home/ubuntu', 'LC_NAME': 'C', 'MAIL': '/var/mail/ubuntu', 'LC_TIME': 'C', 'SSH_CONNECTION': '10.200.4.87 58324 10.200.62.63 22', 'APT_LISTBUGS_FRONTEND': 'none', '_COVERAGE_RCFILE': '/tmp/kitchen/testing/.coveragerc'}, u'stdout': -1, u'close_fds': True, u'stdin': None, u'cwd': u'/home/ubuntu'}', reason: [Errno 12] Cannot allocate memory
```
