### ISSUE TITLE
unit.roster.test_ansible test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53084]
unit.roster.test_ansible.AnsibleRosterTestCase.test_yml test failures

2019.2 failed [salt-centos-7-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-pycryptodomex/85/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-debian-8-py2/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-29-py3/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/70/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-m2crypto/81/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-pycryptodomex/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-ubuntu-1604-py2-tornado](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-tornado/76/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-transport/77/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3/80/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml)
2019.2.1 failed [salt-centos-7-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-m2crypto/46/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-centos-7-py2-transport](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-transport/41/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-pycryptodomex/44/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-transport/45/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-pycryptodomex/44/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_yml)
---

unit.roster.test_ansible.AnsibleRosterTestCase.test_script test failures

2019.2 failed [salt-centos-7-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-pycryptodomex/85/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-debian-8-py2/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-29-py3/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/70/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-m2crypto/81/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-pycryptodomex/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-tornado](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-tornado/76/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-transport/77/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3/80/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script)
2019.2.1 failed [salt-centos-7-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-m2crypto/46/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-centos-7-py2-transport](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-transport/41/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-pycryptodomex/44/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-transport/45/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-pycryptodomex/44/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_script)
---

unit.roster.test_ansible.AnsibleRosterTestCase.test_ini test failure

2019.2 failed [salt-centos-7-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2-pycryptodomex/85/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-debian-8-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-debian-8-py2/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-fedora-29-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-fedora-29-py3/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-opensuse-15-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-opensuse-15-py2/70/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-ubuntu-1604-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-m2crypto/81/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-pycryptodomex/82/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-ubuntu-1604-py2-tornado](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-tornado/76/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2-transport/77/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-ubuntu-1604-py3](https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py3/80/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini)
2019.2.1 failed [salt-centos-7-py2-m2crypto](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-m2crypto/46/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-centos-7-py2-transport](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-transport/41/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-ubuntu-1604-py2-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-pycryptodomex/44/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-ubuntu-1604-py2-transport](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-transport/45/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini), [salt-ubuntu-1604-py3-pycryptodomex](https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-pycryptodomex/44/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini)
---
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/roster/test_ansible.py", line 86, in test_ini
    ret = ansible.targets('*')
  File "/tmp/kitchen/testing/salt/roster/ansible.py", line 120, in targets
    inventory = __runner__['salt.cmd']('cmd.run', 'ansible-inventory -i {0} --list'.format(get_roster_file(__opts__)))
  File "/tmp/kitchen/testing/salt/runners/salt.py", line 113, in cmd
    if fun in functions \
  File "/tmp/kitchen/testing/salt/modules/cmdmod.py", line 1221, in run
    **kwargs)
  File "/tmp/kitchen/testing/salt/modules/cmdmod.py", line 693, in _run
    raise CommandExecutionError(msg)
CommandExecutionError: Unable to run command '[u'ansible-inventory', u'-i', u'/tmp/kitchen/testing/tests/unit/files/rosters/ansible/roster.ini', u'--list']' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -2, u'env': {'LC_NUMERIC': 'C', 'TESTS_XML_OUTPUT_DIR': '/tmp/xml-unittests-output/', 'TESTS_LOG_LEVEL': '2', 'LC_CTYPE': 'C', 'LESSOPEN': '||/usr/bin/lesspipe.sh %s', 'SSH_CLIENT': '10.200.26.197 35420 22', 'LOGNAME': 'root', 'USER': 'root', 'HOME': '/root', 'LC_PAPER': 'C', 'PATH': '/sbin:/bin:/usr/sbin:/usr/bin', 'COVERAGE_PROCESS_START': '', 'LANG': 'en_US.UTF-8', 'TERM': 'xterm', 'SHELL': '/bin/bash', 'LANGUAGE': 'C', 'LC_MEASUREMENT': 'C', 'LESS_TERMCAP_me': '\x1b[0m', 'LESS_TERMCAP_md': '\x1b[01;38;5;208m', 'LESS_TERMCAP_mb': '\x1b[01;31m', 'AWS_ELB_HOME': '/opt/aws/apitools/elb', 'SUDO_USER': 'ec2-user', 'JAVA_HOME': '/usr/lib/jvm/jre', 'EC2_HOME': '/opt/aws/apitools/ec2', 'LC_MONETARY': 'C', 'USERNAME': 'root', 'SUDO_COMMAND': '/usr/bin/python2.7 /tmp/kitchen/testing/tests/runtests.py --sysinfo --output-columns=80 --transport=zeromq -v --run-destructive --coverage-xml=/tmp/coverage.xml --xml=/tmp/xml-unittests-output/ --ssh', 'LC_ADDRESS': 'C', 'COVERAGE_OPTIONS': '{"source": ["/tmp/kitchen/testing/salt"], "branch": true, "data_suffix": true}', 'SHLVL': '1', 'SUDO_UID': '500', 'SUDO_GID': '500', 'AWS_AUTO_SCALING_HOME': '/opt/aws/apitools/as', 'AWS_ACCESS_KEY_ID': 'foobar_key', '_': '/usr/bin/sudo', 'DESTRUCTIVE_TESTS': 'True', 'LC_IDENTIFICATION': 'C', 'LESS_TERMCAP_ue': '\x1b[0m', 'LC_MESSAGES': 'C', 'AWS_PATH': '/opt/aws', 'SSH_TTY': '/dev/pts/0', 'LC_COLLATE': 'C', 'AWS_CLOUDWATCH_HOME': '/opt/aws/apitools/mon', 'LC_TELEPHONE': 'C', 'LESS_TERMCAP_se': '\x1b[0m', 'EC2_AMITOOL_HOME': '/opt/aws/amitools/ec2', 'PWD': '/home/ec2-user', 'LESS_TERMCAP_us': '\x1b[04;38;5;111m', 'AWS_SECRET_ACCESS_KEY': 'foobar_secret', 'LC_NAME': 'C', 'MAIL': '/var/mail/ec2-user', 'LC_TIME': 'C', 'SSH_CONNECTION': '10.200.26.197 35420 10.200.50.29 22', 'SSH_DAEMON_RUNNING': 'True'}, u'stdout': -1, u'close_fds': True, u'stdin': None, u'cwd': u'/root'}', reason: [Errno 2] No such file or directory
```

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 21, 2019 3:20:34 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-2-py2/1/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-1-py2/3/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-2-py3/4/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-tornado/49/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-tornado/47/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-transport/50/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-transport/52/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-transport/48/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-m2crypto/54/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2-pycryptodomex/53/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2-m2crypto/52/
May 22, 2019 1:36:36 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-m2crypto/49/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py3-pycryptodomex/52/

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 4:11:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-amazon-1-py2/1/

**Comment by frogunder** [comment]
After nox testing got put in on the 2019.2.1 branch, I do not see these tests fail anymore.
I will remove the 2019.2.1 label
