### ISSUE TITLE
Add Watchdog execution module and state

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#5309]
A Watchdog module and state would allow for some interesting things.
https://pypi.python.org/pypi/watchdog
1. Notify the master if certain files were modified or deleted unexpectedly or without
   authorization.
2. Take action when certain files are dropped in a certain directory.

**Comment by arroyoc** [comment]
@jfindlay @UtahDave  Do you guys remember why this feature was blocked? Any reason why we shouldn't approve this?

**Comment by UtahDave** [comment]
I don't know.  This probably should be a beacon instead of an execution module, though

**Comment by UtahDave** [comment]
This was implemented as a beacon with inotify

https://docs.saltstack.com/en/latest/ref/beacons/all/salt.beacons.inotify.html#module-salt.beacons.inotify
