### ISSUE TITLE
unit.states.test_environ.TestEnvironState.test_setenv_permanent test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53106]
### Description of Issue/Question
develop failed [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/87/testReport/junit/unit.states.test_environ/TestEnvironState/test_setenv_permanent)
---

{u'test': False} != {u'test': u'value'} - {u'test': False} ?           ^  ^  + {u'test': u'value'} ?           ^^^  ^ + 

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\states\test_environ.py", line 62, in test_setenv_permanent
    self.assertEqual(ret['changes'], {'test': 'value'})
AssertionError: {u'test': False} != {u'test': u'value'}
- {u'test': False}
?           ^  ^

+ {u'test': u'value'}
?           ^^^  ^ +

		
```
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/
