### ISSUE TITLE
unit.test_minion.MinionTestCase.test_minion_manage_schedule test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53103]
develop failed [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/87/testReport/junit/unit.test_minion/MinionTestCase/test_minion_manage_schedule)
---

'test_job' not found in {u'__mine_interval': {u'function': u'mine.update', u'run_on_start': True, u'jid_include': True, u'maxrunning': 2, u'enabled': True, u'minutes': 60, u'return_job': False}}

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\test_minion.py", line 357, in test_minion_manage_schedule
    self.assertIn('test_job', minion.opts['schedule'])
AssertionError: 'test_job' not found in {u'__mine_interval': {u'function': u'mine.update', u'run_on_start': True, u'jid_include': True, u'maxrunning': 2, u'enabled': True, u'minutes': 60, u'return_job': False}}
		
```

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/
