### ISSUE TITLE
unit.renderers.test_gpg.GPGTestCase.test_render_with_binary_data_should_return_binary_data test failures

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#53105]
develop failed [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/87/testReport/junit/unit.renderers.test_gpg/GPGTestCase/test_render_with_binary_data_should_return_binary_data)
2019.2 failed [salt-windows-2019-py2](https://jenkinsci.saltstack.com/job/2019.2/job/salt-windows-2019-py2/66/testReport/junit/unit.renderers.test_gpg/GPGTestCase/test_render_with_binary_data_should_return_binary_data)
---

u'Use\u2039 more\u2039 salt.\nUse\u2039 more\u2039 salt.\nUse\u2039 more\u2039 salt.' != 'Use\x8b more\x8b salt.\nUse\x8b more\x8b salt.\nUse\x8b more\x8b salt.'

```

Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\renderers\test_gpg.py", line 146, in test_render_with_binary_data_should_return_binary_data
    self.assertEqual(gpg.render(crypted), expected)
AssertionError: u'Use\u2039 more\u2039 salt.\nUse\u2039 more\u2039 salt.\nUse\u2039 more\u2039 salt.' != 'Use\x8b more\x8b salt.\nUse\x8b more\x8b salt.\nUse\x8b more\x8b salt.'
		
```

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 5:42:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2019-py2/95/
May 21, 2019 9:43:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-windows-2016-py2/49/

**Comment by DmitryKuzmenko** [comment]
The same is on 2019.2

https://jenkinsci.saltstack.com/job/2019.2/job/salt-windows-2016-py2/90/testReport/junit/unit.renderers.test_gpg/GPGTestCase/test_render_with_translate_newlines_should_translate_newlines/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-windows-2016-py2/90/testReport/junit/unit.renderers.test_gpg/GPGTestCase/test_render_with_binary_data_should_return_binary_data/
