### ISSUE TITLE
How to change minion extmods cache dir?

### ISSUE THREAD

**Issue by d-shi** [saltstack/salt#53114]
### Description of Issue/Question
I would like to change the default location of the minion cache directory, so I have added `cachedir: /data/cache/salt/minion` to the minion config file. However, the extmods directory still keeps getting created in `/var/cache/salt/minion/extmods`.

This is likely because we have some grains and returners in the master file server under `salt://<env>/_grains` and `salt://<env>/_returners`. However, I am not able to find a way to change this behavior. This issue makes it sound like it should already be moved by changing `cachedir`: https://github.com/saltstack/salt/issues/42943

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Minion config file:
```
master: <redacted>

top_file_merging_strategy: same
default_top: base
saltenv: base

pillarenv_from_saltenv: True
startup_states: highstate
state_output: mixed

use_superseded:
  - module.run

cachedir: /data/cache/salt/minion
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Delete `/var/cache/salt/minion` on the minion then run highstate. Afterwards, `/var/cache/salt/minion/extmods` is created again with `grains` and `returners` inside. The rest of the minion cache is in `/data/cache/salt/minion` as expected.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Minion:
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 3.5.0
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-50-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

Master:
```
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-148-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by twangboy** [comment]
@saltstack/team-core Is this expected behavior? ext_mods should use the same cachedir, right?

**Comment by waynew** [comment]
I'm not sure? https://docs.saltstack.com/en/latest/ref/configuration/master.html#extension-modules

> Changed in version 2016.3.0: The default location for this directory has been moved. Prior to this version, the location was a directory named extmods in the Salt cachedir (on most platforms, /var/cache/salt/extmods). It has been moved into the master cachedir (on most platforms, /var/cache/salt/master/extmods).

I don't know exactly how I'd read that :suspect: It almost reads like they belong in a new directory? Though, that is referring to the master config. I'm not sure if that's how the location is specified. 

@d-shi If you set `extension_modules: /data/cache/salt/minion/extmods` in your master (or minion config, for that matter) does it change anything?

**Comment by d-shi** [comment]
@waynew it seems like setting `extension_modules: /data/cache/salt/minion/extmods` in the minion config fixes the issue. After setting that I can delete `/var/cache/salt` and it does not get recreated again on subsequent highstate applications.

**Comment by waynew** [comment]
Sounds like that answers the question, then. I'm going to go ahead and close this issue, but if you feel like there's something missing, let me know and I'll be happy to re-open!
