### ISSUE TITLE
Requiring an undefined state results in success

### ISSUE THREAD

**Issue by Paulo-Nunes** [saltstack/salt#53127]
### Description of Issue/Question
As per the docs:
```
The use of require demands that the required state executes before the dependent state.
...
If the required state's execution succeeds, the dependent state will then execute. If the required state's execution fails, the dependent state will not execute.
```
Contrary to the docs, if a require is defined on a state, and the required stated is not defined, then the requiring state executes as if the require had been satisfied.
Docs clearly state: "use of require **demands** that the **required state executes** before the dependent state"
If the state does not exist, and it is demanded to run, it should result in a failure to run.
Currently, in addition to a succeed and fail state there is an undefined state (as the required state did not successfully execute, nor did it return a failure. Therefore, it must be a third state).

The expected behavior, given what the docs state, is that the requiring state should fail to run because not every required state successfully executes.

### Setup
Example (Note: `pkg: x` is not defined)
CLI:
```
salt minion state.single cmd.run name='echo hello' require='pkg:x'
```
SLS:
```
hello
  cmd.run:
    - name: echo hello
    - require:
      - pkg: x
```

Result from the CLI:
```
minion:
----------
          ID: echo hello
    Function: cmd.run
      Result: True
     Comment: Command "echo hello" run
     Started: 09:36:52.598438
    Duration: 58.621 ms
     Changes:   
              ----------
              pid:
                  128466
              retcode:
                  0
              stderr:
              stdout:
                  hello

Summary for minion
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  58.621 ms
```

### Versions Report
Same behavior on salt-master 2017.7.7

Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.20.3
         Python: 2.7.14 (default, Jan 31 2018, 02:12:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.10 Santiago
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-754.11.1.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.10 Santiago

**Comment by twangboy** [comment]
@Paulo-Nunes Thanks for reporting this. I can verify this bug exists in current branches.

**Comment by Paulo-Nunes** [comment]
This has been labeled as a bug, but no fix has been proposed. Should not be closed
