### ISSUE TITLE
Exception when applying state with --out json -s --out-file=result and output data lost

### ISSUE THREAD

**Issue by kk21986** [saltstack/salt#53136]
### Description of Issue/Question
When I tried to apply the state on 515 servers with json formatted output and groupping them ended up with exception and due to that lost the complete the execution to be written on the given file.  

```
salt -L "$(cat servers.lst)" state.apply test --out json -s --out-file=result
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/local/python371/bin/salt", line 11, in <module>
    load_entry_point('salt==2019.2.0', 'console_scripts', 'salt')()
  File "/usr/local/python371/lib/python3.7/site-packages/salt/scripts.py", line 516, in salt_main
    client.run()
  File "/usr/local/python371/lib/python3.7/site-packages/salt/cli/salt.py", line 66, in run
    self._run_batch()
  File "/usr/local/python371/lib/python3.7/site-packages/salt/cli/salt.py", line 270, in _run_batch
    for res in batch.run():
  File "/usr/local/python371/lib/python3.7/site-packages/salt/cli/batch.py", line 262, in run
    ret[minion] = data['ret']
KeyError: 'ret'
Traceback (most recent call last):
  File "/usr/local/python371/bin/salt", line 11, in <module>
    load_entry_point('salt==2019.2.0', 'console_scripts', 'salt')()
  File "/usr/local/python371/lib/python3.7/site-packages/salt/scripts.py", line 516, in salt_main
    client.run()
  File "/usr/local/python371/lib/python3.7/site-packages/salt/cli/salt.py", line 66, in run
    self._run_batch()
  File "/usr/local/python371/lib/python3.7/site-packages/salt/cli/salt.py", line 270, in _run_batch
    for res in batch.run():
  File "/usr/local/python371/lib/python3.7/site-packages/salt/cli/batch.py", line 262, in run
    ret[minion] = data['ret']
KeyError: 'ret'
```

### Steps to Reproduce Issue
Run the below sample command is the step to re-produce. be make sure some of the minions should respond during that time. 

### Versions Report
```
Salt Version:
Salt: 2019.2.0

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.7.5
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.10
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: Not Installed
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.5.6
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: Not Installed
pycryptodome: 3.7.3
pygit2: Not Installed
Python: 3.7.1 (default, Nov 23 2018, 02:59:05)
python-gnupg: Not Installed
PyYAML: 3.13
PyZMQ: 17.1.2
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.2.5

System Versions:
dist: redhat 7.6
locale: UTF-8
machine: x86_64
release: 4.14.134-1234.2.5.el7.x86_64
system: Linux
version: Red Hat Enterprise Linux Server 7.6
```

**Comment by twangboy** [comment]
@kk21986 What does `servers.lst` look like? I need to know the format. Is it
```
server1,server2,server3
```
or
```
server1
server2
server3
```

Additionally, can you post the state you're applying?

**Comment by kk21986** [comment]
The servers.lst is a file which contains the list of servers in newline separated format. Since I had to apply the state on selected 140 minions out of complete inventory I used this method. 

For example, 

server1
server2
server3

State details:
--------------
`
{% if grains['os_family'] == 'RedHat' %}

as_exists:
  file.exists:
    - name: /usr/local/test.sh

copy_scripts:
  file.managed:
    - name: /etc/apps/config
    - source: salt://test/scripts/config
    - user: root
    - group: root
    - mode: 0755
    - require:
      - file: as_exists

config_exists:
  file.exists:
    - name: /etc/apps/config

bin_exists:
  file.exists:
    - name: /sbin/app_bin

OMCSSrv:
  cmd.run:
    - name: /sbin/app_bin run
    - unless: chkconfig --list | grep '3:on' | grep some_service
    - require:
      - file: config_exists
      - file: bin_exists

{% endif %}
`

**Comment by kk21986** [comment]
I suspect that it happened due another issue https://github.com/saltstack/salt/issues/53135 (Unable to apply the state across the fleet in the inventory and state.apply stuck on some servers) where some minions got stuck with applying the states wherein there was no response from those. But I think even if the minion not responding then it should display the message "Minion did not return. [No response]" I believe. Correct me if am wrong.

**Comment by twangboy** [comment]
It may be because the `-L` is expecting a comma-separated list `server1,server2,server3, etc...`. You may need to add some logic to your `cat` command to take the text file and convert it to a comma-separated list.

**Comment by kk21986** [comment]
Ok I will check with as suggested and come back

**Comment by kk21986** [comment]
I ran with ` salt '*' state.apply test --out json -s --out-file=result ` and got the same issue.
