### ISSUE TITLE
update doc pr's to be built using python3 and sphinx 2.0.1

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#53137]
### Description of Issue/Question
Doc PR's are tested using python2, I'm not sure of the version of sphinx, however, the actual docs that go on docs.saltstack.com are built using python3 and sphinx 2.0.1.

We need to move the pr builds to run on python3

The means update
* .ci/docs
* requirements/static/docs.in
* update things in sre-jenkins

verify it works.

**Comment by s0undt3ch** [comment]
2018.3, 2019.2.1, neon and develop have migrated to building docs on Py3.
2019.2 will get that when the merge-forward is merged.
2017.7.9 and 2017.7 need extra work to switch.

**Comment by bryceml** [comment]
This is done.
