### ISSUE TITLE
Salt does not allow custom validation dates to be specified for new X509 certificates

### ISSUE THREAD

**Issue by jeduardo** [saltstack/salt#53148]
### Description of Issue/Question

The current Salt x509 support issues certificates based on the current timestamp when the module is invoked as the starting date ("not_before") and with the expiration date ("not_after") being calculated based on a number of validity dates.

I would like to make it possible to issue certificates with well-defined expiration dates, however when passing dates as `not_before` and `not_after` attributes for the X509 state, these attributes are ignored.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by waynew** [comment]
Fixed in #53149
