### ISSUE TITLE
Documentation example of boto_route53 function: update_record is wrong

### ISSUE THREAD

**Issue by Reiner030** [saltstack/salt#53146]
I guess the modify_record function was renamed but forgotten to replace all occurences:

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.boto_route53.html#salt.modules.boto_route53.update_record

CLI example:
````
salt myminion boto_route53.modify_record test.example.org 1.1.1.1 example.org A
````

**Comment by twangboy** [comment]
@Reiner030 That would be a pretty easy PR if you want to take a stab at it.

**Comment by Reiner030** [comment]
mmh, too much stale bot answers these weeks ... overseen this still open bug/issue...
