### ISSUE TITLE
integration.states.test_network.NetworkTest.test_managed

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#53171]
```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/states/test_network.py", line 34, in test_managed
    self.assertEqual('Interface dummy0 is set to be added.', ret[state_key]['comment'])
AssertionError: u'Interface dummy0 is set to be added.' != u'Interface dummy0 is set to be updated:\n'
- Interface dummy0 is set to be added.
?                                ^^  ^
+ Interface dummy0 is set to be updated:

?                               +++ ^  ^ +
```

**Comment by twangboy** [comment]
Failing on 2019.2.1:
May 21, 2019 3:20:34 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-2-py2/1/
May 21, 2019 5:22:00 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-1-py2/2/
May 22, 2019 1:37:37 PM - https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-2-py3/4/

**Comment by twangboy** [comment]
Failing on develop:
May 21, 2019 4:11:00 PM - https://jenkinsci.saltstack.com/job/develop/job/salt-amazon-1-py2/1/

**Comment by DmitryKuzmenko** [comment]
Failing on 2019.2 Amazon Linux py2 and py3:
https://jenkinsci.saltstack.com/job/2019.2/job/salt-amazon-1-py2/57/testReport/junit/integration.states.test_network/NetworkTest/test_managed/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-amazon-2-py2/58/testReport/junit/integration.states.test_network/NetworkTest/test_managed/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-amazon-2-py3/55/testReport/junit/integration.states.test_network/NetworkTest/test_managed/

**Comment by Akm0d** [comment]
This needs to be fixed in Neon

**Comment by waynew** [comment]
It will be fixed in the (final?) merge forward
