### ISSUE TITLE
ERROR: Unable to locate appropriate python command

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#53233]
### Setup

I am running `salt-ssh` with option `-l all`.

Now I see several times this output:

> ERROR: Unable to locate appropriate python command

### Steps to Reproduce Issue

Run `salt-ssh` with `-l all`

output:
```
exec $SUDO "$py_cmd_path" -c \
'import base64;
exec(base64.b64decode("""IyBweWxpbnQ6IGRpc2FibGU9bm8tZW5jb2RpbmctaW4tZmlsZSxyZXNv...
ICAgc3lzLmV4aXQobWFpbihzeXMuYXJndikpCg==
""").decode("utf-8"))'
fi
exit 0
else
continue
fi
done
echo "ERROR: Unable to locate appropriate python command" >&2
exit $EX_PYTHON_INVALID
EOF
```

What command is salt missing here?

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.1.0
       cherrypy: 3.6.0
       dateutil: 2.1
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.22.0
        libnacl: Not Installed
       M2Crypto: 0.22
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.12
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.22.0
         Python: 2.7.3 (default, Apr 14 2012, 08:58:41) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: SuSE 12.3 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.114-42.1-default
         system: Linux
        version: openSUSE  12.3 x86_64
```

**Comment by dmurphy18** [comment]
@guettli At the present, salt_ssh expects that Python is already installed on the target machine.

The python command is typically, one of the following :
python3 python27 python2.7 python26 python2.6 python2 python

see: https://github.com/saltstack/salt/blob/08a12d01e28512e05b7a467edcbb8084deabd8de/salt/client/ssh/__init__.py#L150

If this resolves your issue, please consider closing this issue

**Comment by guettli** [comment]
In my case Python 2.7 is installed on the minion. The message " ERROR: Unable to locate appropriate python command" is just a message. Everything works like expected. But the message is confusing, since python is available on the minion.

**Comment by dmurphy18** [comment]
@guettli Wondering if your python is not in an expected path, can you provide the contents of PATH, that is, echo $PATH, and the actual absolute path path to python on your system.

**Comment by guettli** [comment]
`python` is in its default location and on `$PATH`. The only thing which is a bit strange is the old operating system on the central host.

On the host which executes `salt-ssh` (SuSE 12.3) :
```
salt:/srv # type python
python is /usr/bin/python
salt:/srv # echo $PATH
/sbin:/usr/sbin:/usr/local/sbin:/root/bin:/usr/local/bin:/usr/bin:/bin:/usr/bin/X11:/usr/X11R6/bin:/usr/games

```

On the minion (Ubuntu 18.04)

```
root@aptguettler:~# type python
python ist /usr/bin/python
root@aptguettler:~# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin

```

**Comment by guettli** [comment]
It contains mappings like this:

```
foo-host: foo-host
bar-host: bar-host

...
# Automatically added by "root" at 2018-06-21T09:33:15.132106
foo-archive.example.lan:
    host: foo-archive.example.lan
    user: root
    passwd: 
```

What kind of error do you think could be in the roster file?

**Comment by cmcmarrow** [comment]
I believe this is the script that is giving you the error message
`SSH_SH_SHIM = \
    '\n'.join(
        [s.strip() for s in r'''/bin/sh << 'EOF'
set -e
set -u
DEBUG="{{DEBUG}}"
if [ -n "$DEBUG" ]
    then set -x
fi
SUDO=""
if [ -n "{{SUDO}}" ]
    then SUDO="sudo "
fi
SUDO_USER="{{SUDO_USER}}"
if [ "$SUDO" ] && [ "$SUDO_USER" ]
then SUDO="sudo -u {{SUDO_USER}}"
elif [ "$SUDO" ] && [ -n "$SUDO_USER" ]
then SUDO="sudo "
fi
EX_PYTHON_INVALID={EX_THIN_PYTHON_INVALID}
PYTHON_CMDS="python3 python27 python2.7 python26 python2.6 python2 python"
for py_cmd in $PYTHON_CMDS
do
    if command -v "$py_cmd" >/dev/null 2>&1 && "$py_cmd" -c \
        "import sys; sys.exit(not (sys.version_info >= (2, 6)
                              and sys.version_info[0] == {{HOST_PY_MAJOR}}));"
    then
        py_cmd_path=`"$py_cmd" -c \
                   'from __future__ import print_function;
                   import sys; print(sys.executable);'`
        cmdpath=`command -v $py_cmd 2>/dev/null || which $py_cmd 2>/dev/null`
        if file $cmdpath | grep "shell script" > /dev/null
        then
            ex_vars="'PATH', 'LD_LIBRARY_PATH', 'MANPATH', \
                   'XDG_DATA_DIRS', 'PKG_CONFIG_PATH'"
            export `$py_cmd -c \
                  "from __future__ import print_function;
                  import sys;
                  import os;
                  map(sys.stdout.write, ['{{{{0}}}}={{{{1}}}} ' \
                  .format(x, os.environ[x]) for x in [$ex_vars]])"`
            exec $SUDO PATH=$PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH \
                     MANPATH=$MANPATH XDG_DATA_DIRS=$XDG_DATA_DIRS \
                     PKG_CONFIG_PATH=$PKG_CONFIG_PATH \
                     "$py_cmd_path" -c \
                   'import base64;
                   exec(base64.b64decode("""{{SSH_PY_CODE}}""").decode("utf-8"))'
        else
            exec $SUDO "$py_cmd_path" -c \
                   'import base64;
                   exec(base64.b64decode("""{{SSH_PY_CODE}}""").decode("utf-8"))'
        fi
        exit 0
    else
        continue
    fi
done
echo "ERROR: Unable to locate appropriate python command" >&2
exit $EX_PYTHON_INVALID
EOF'''.format(
            EX_THIN_PYTHON_INVALID=salt.defaults.exitcodes.EX_THIN_PYTHON_INVALID,
            ).split('\n')])`

**Comment by cmcmarrow** [comment]
I believe this is the script giving you the error message 
```
SSH_SH_SHIM = \
    '\n'.join(
        [s.strip() for s in r'''/bin/sh << 'EOF'
set -e
set -u
DEBUG="{{DEBUG}}"
if [ -n "$DEBUG" ]
    then set -x
fi
SUDO=""
if [ -n "{{SUDO}}" ]
    then SUDO="sudo "
fi
SUDO_USER="{{SUDO_USER}}"
if [ "$SUDO" ] && [ "$SUDO_USER" ]
then SUDO="sudo -u {{SUDO_USER}}"
elif [ "$SUDO" ] && [ -n "$SUDO_USER" ]
then SUDO="sudo "
fi
EX_PYTHON_INVALID={EX_THIN_PYTHON_INVALID}
PYTHON_CMDS="python3 python27 python2.7 python26 python2.6 python2 python"
for py_cmd in $PYTHON_CMDS
do
    if command -v "$py_cmd" >/dev/null 2>&1 && "$py_cmd" -c \
        "import sys; sys.exit(not (sys.version_info >= (2, 6)
                              and sys.version_info[0] == {{HOST_PY_MAJOR}}));"
    then
        py_cmd_path=`"$py_cmd" -c \
                   'from __future__ import print_function;
                   import sys; print(sys.executable);'`
        cmdpath=`command -v $py_cmd 2>/dev/null || which $py_cmd 2>/dev/null`
        if file $cmdpath | grep "shell script" > /dev/null
        then
            ex_vars="'PATH', 'LD_LIBRARY_PATH', 'MANPATH', \
                   'XDG_DATA_DIRS', 'PKG_CONFIG_PATH'"
            export `$py_cmd -c \
                  "from __future__ import print_function;
                  import sys;
                  import os;
                  map(sys.stdout.write, ['{{{{0}}}}={{{{1}}}} ' \
                  .format(x, os.environ[x]) for x in [$ex_vars]])"`
            exec $SUDO PATH=$PATH LD_LIBRARY_PATH=$LD_LIBRARY_PATH \
                     MANPATH=$MANPATH XDG_DATA_DIRS=$XDG_DATA_DIRS \
                     PKG_CONFIG_PATH=$PKG_CONFIG_PATH \
                     "$py_cmd_path" -c \
                   'import base64;
                   exec(base64.b64decode("""{{SSH_PY_CODE}}""").decode("utf-8"))'
        else
            exec $SUDO "$py_cmd_path" -c \
                   'import base64;
                   exec(base64.b64decode("""{{SSH_PY_CODE}}""").decode("utf-8"))'
        fi
        exit 0
    else
        continue
    fi
done
echo "ERROR: Unable to locate appropriate python command" >&2
exit $EX_PYTHON_INVALID
EOF'''.format(
            EX_THIN_PYTHON_INVALID=salt.defaults.exitcodes.EX_THIN_PYTHON_INVALID,
            ).split('\n')])

**Comment by cmcmarrow** [comment]
I can confirm this and will push a fix for it.

**Comment by cmcmarrow** [comment]
Thank you guettli for reporting this

**Comment by cmcmarrow** [comment]
guettli I don't believe this is bug. When you have the flag "-l all" it will print out strings tagged by trace. This includes GPG keys and Terminal Commands. I believe your looking at a raw terminal command that was executed. This is why you see "echo "ERROR: Unable to locate appropriate python command" >&2". If the error did happen you should see "ERROR: Unable to locate appropriate python command". If you scroll up a little you should see "[Trace ] Terminal Command: ..." If you don't want to see this message just run with the flag "-l debug"

**Comment by guettli** [comment]
@cmcmarrow yes, I guess you are right: This is not an error, this is just a shell line which gets parsed but not executed. I think you found the solution. But nevertheless this is confusing. Now I know what is going on. But I guess this will confuse other people in the future, if this does not change.
