### ISSUE TITLE
 [VMWare Cloud] I/O operation on closed file

### ISSUE THREAD

**Issue by samcarlos22** [saltstack/salt#53246]
### VMware cloud plugin generates an "I/O operation on closed file" during new VMs deploy.
![image](https://user-images.githubusercontent.com/7332555/58407765-d632fd80-806c-11e9-9cc3-abbd45b517f7.png)

### Setup
_cat /etc/salt/cloud.providers_

<pre>
dkprofile:  
      driver: vmware
      user: ************
      password: *******
      url: '**************'
      protocol: 'https'
      port: 443
</pre>

 _cat /etc/salt/cloud.profiles.d/vmware.conf_
<pre>
linux_minion:
   provider: 'dkprofile'
   clonefrom: 'dkatest-lintemp'
   datastore: **************
   folder: **************
   datacenter: **********
   power_on: False
   deploy: True
   minion:
     master: salt
</pre>

_cat /etc/salt/cloud.maps.d/vmware.map_
<pre>
linux_minion:
    saltdeploy01:
       num_cpus: 4
       memory: 4GB
    saltdeploy02:
       num_cpus: 2
       memory: 4GB
</pre>

### Steps to Reproduce Issue
**salt-cloud -P -m /etc/salt/cloud.maps.d/vmware.map**

### Versions Report
<pre>
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.27.0
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 3.8.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15rc1 (default, Nov 12 2018, 14:31:15)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-50-generic
         system: Linux
        version: Ubuntu 18.04 bionic
</pre>

**Comment by dmurphy18** [comment]
@samcarlos22 Can you provide the version of Salt that you are using, it appears to be missing from the versions report.  If you could also provide the output of _lsb_release -a_, that would be helpful

**Comment by samcarlos22** [comment]
@dmurphy18 Thanks for the reply. The salt version is `Salt: 2019.2.0-784-gabbfad1` and the output is
<pre>
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:        18.04
Codename:       bionic
</pre>

**Comment by dmurphy18** [comment]
@samcarlos22 Can you try it with the packaged Salt 2019.2.0 and see if the problem occurs.  Cannot be sure of what is in 2019.2.0-784-gabbfad1 since that is not an official release, and could contain transient issues which have since been resolved or still outstanding.  If the packaged version is problematic, at least the released version from PyPI, but packaged version is preferred since the dependencies are a known quantity.

**Comment by samcarlos22** [comment]
@dmurphy18 I installed the version 2019.2.0 and it's working fine. Thanks for the help, issue closed. :D
