### ISSUE TITLE
Windows Salt-Minion installation: copy python.exe to salt-minion.exe

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#53254]
### Proposal
For maintenance and bug-reporting, among other things, it would be beneficial if the client processes in the Windows task manager would be named `salt-minion.exe` instead of `python.exe`

After looking through the alternatives, I will copy `python.exe` to `salt-minion.exe` and use the latter. 
First, [in the msi installer](https://github.com/markuskramerIgitt/salt-windows-msi).

I kindly ask for comments.

## Failed alternatives

**Setproctitle** [does not and will never work on Windows](https://github.com/dvarrazzo/py-setproctitle/issues/61)

## Related issues

  - https://github.com/saltstack/salt/issues/42862

## Long term Improvements

Use a junction instead of a copy

**Comment by dmurphy18** [comment]
@markuskramerIgitt I think this might be better handled as a SEP since it will change how Salt is currently utilized on Windows.

Here is the url: https://github.com/saltstack/salt-enhancement-proposals

Using this process would allow for a fuller discussion of the issues and the changes to be made.
Let me know your thoughts

**Comment by twangboy** [comment]
I know @dwoz has some ideas on building salt-minion (among others) binaries on Windows. Unfortunately, we've been pulled to work on more pressing matters...

**Comment by twangboy** [comment]
However, I wouldn't recommend we shift from the way we're building the .exe's.

Also, if you're interested, we're going to start a Windows working group. It would be awesome if you could be a part of it. More information here: https://github.com/saltstack/salt-enhancement-proposals/pull/12

**Comment by markuskramerIgitt** [comment]
@dmurphy18, the suggested copy does not "change how Salt is currently utilized on Windows" 
It is a workaround for the limitations of setproctittle. 
I think it does not fit into the salt-enhancement-proposal.

**Comment by markuskramerIgitt** [comment]
@twangboy, I already applied to the Windows working group a few days ago. Looking forward to the first meeting!

**Comment by dmurphy18** [comment]
@markuskramerIgitt It changes how Salt is expected to be used on Windows, and before making the suggestion on SEP, I discussed it with @twangboy who thought it would be appropriate as a SEP and possibly tie it in with the work that @dwoz was considering.

**Comment by markuskramerIgitt** [comment]
https://github.com/saltstack/salt-enhancement-proposals/pull/15
