### ISSUE TITLE
Clarify docs on targeting & matching logic (and possibly minion command invocation)

### ISSUE THREAD

**Issue by MatthewDaize** [saltstack/salt#53252]
### Description of Issue/Question

The documentation is unclear where/how the targeting and matching logic is actually performed/evaluated.

Based on the details here: https://docs.saltstack.com/en/latest/topics/matchers/index.html there is a quote that implies that the targeting is done by the minion themselves (the mention regarding needing to sync them down to the minion by way of `saltutil.sync_matchers`) unless perhaps this is used when running `salt-call` locally?

Could this be clarified in these docs -- or perhaps some sort of logic diagram that illustrates the process of command invocation and data passing between master and one/more minions?

I would offer to assist with this however I do not have enough of an understanding of the internal structure to write something accurate (compared to someone who knows the codebase intimately) and in any timely manner...

Thanks!

**Comment by markuskramerIgitt** [comment]
The matching can be evaluated (or "filteted") either on the server or the client.

There are a number of implications. 

The (currently) default configurarion uses ZMQ serverside filtering.
After you configured `zmq_filtering` on server and all clients, you get clientside filtering.

I would like to assist in improving the documentation.

**Comment by MatthewDaize** [comment]
Thanks @markuskramerIgitt ... That would be very beneficial to us all!!
