### ISSUE TITLE
After updating to 2019.2 log is full with error

### ISSUE THREAD

**Issue by petervarkoly** [saltstack/salt#53261]
### Description of Issue/Question
After update to 2019.2 from 2018.3.2 the salt master logs continously (every 10 seconds) logs following error:

Mai 27 23:36:02 admin salt-master[2579]: [ERROR   ] An un-handled exception from the multiprocessing process 'Maintenance-2819' was caught:
Mai 27 23:36:02 admin salt-master[2579]: Traceback (most recent call last):
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 765, in _run
Mai 27 23:36:02 admin salt-master[2579]:     return self._original_run()
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/master.py", line 241, in run
Mai 27 23:36:02 admin salt-master[2579]:     self.handle_presence(old_present)
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/master.py", line 343, in handle_presence
Mai 27 23:36:02 admin salt-master[2579]:     present = self.ckminions.connected_ids()
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 643, in connected_ids
Mai 27 23:36:02 admin salt-master[2579]:     addrs = salt.utils.network.local_port_tcp(int(self.opts['publish_port']))
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 1384, in local_port_tcp
Mai 27 23:36:02 admin salt-master[2579]:     ret = _remotes_on(port, 'local_port')
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 1402, in _remotes_on
Mai 27 23:36:02 admin salt-master[2579]:     ret = _netlink_tool_remote_on(port, which_end)
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 1494, in _netlink_tool_remote_on
Mai 27 23:36:02 admin salt-master[2579]:     if which_end == 'local_port' and int(local_port) != port:
Mai 27 23:36:02 admin salt-master[2579]: ValueError: invalid literal for int() with base 10: ':ffff:127.0.0.1:53808'
Mai 27 23:36:02 admin salt-master[2579]: Process Maintenance-2819:
Mai 27 23:36:02 admin salt-master[2579]: Traceback (most recent call last):
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
Mai 27 23:36:02 admin salt-master[2579]:     self.run()
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 765, in _run
Mai 27 23:36:02 admin salt-master[2579]:     return self._original_run()
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/master.py", line 241, in run
Mai 27 23:36:02 admin salt-master[2579]:     self.handle_presence(old_present)
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/master.py", line 343, in handle_presence
Mai 27 23:36:02 admin salt-master[2579]:     present = self.ckminions.connected_ids()
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/minions.py", line 643, in connected_ids
Mai 27 23:36:02 admin salt-master[2579]:     addrs = salt.utils.network.local_port_tcp(int(self.opts['publish_port']))
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 1384, in local_port_tcp
Mai 27 23:36:02 admin salt-master[2579]:     ret = _remotes_on(port, 'local_port')
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 1402, in _remotes_on
Mai 27 23:36:02 admin salt-master[2579]:     ret = _netlink_tool_remote_on(port, which_end)
Mai 27 23:36:02 admin salt-master[2579]:   File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 1494, in _netlink_tool_remote_on
Mai 27 23:36:02 admin salt-master[2579]:     if which_end == 'local_port' and int(local_port) != port:
Mai 27 23:36:02 admin salt-master[2579]: ValueError: invalid literal for int() with base 10: ':ffff:127.0.0.1:53808'

### Setup
/etc/salt/master:
interface: 0.0.0.0
ipv6: False
user: salt
syndic_user: salt
#Accept all minions automaticaly
auto_accept: True

#Schedule the presence events
presence_events: True

#OSS specific state file places
file_roots:
  base:
    - /srv/salt
    - /srv/salt/packages

#How verbose should be the event handling
oss_event_log_level: warning

#Enable the minions to send files
file_recv: True

server_id_use_crc: Adler32

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 03 2017, 17:41:54) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: SuSE 4.0.1 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.4.176-96-default
         system: Linux
        version: OSS  4.0.1 x86_64
OSS 4.0.1 is based on openLeap 42.3

**Comment by petervarkoly** [comment]
When I remove /etc/salt/master: Following ERRORs stand:

Mai 28 00:58:44 admin salt-master[42093]: [ERROR   ] Exception during resolving address: [Errno 4] No address associated with name
Mai 28 00:58:45 admin salt-master[42093]: [ERROR   ] Exception during resolving address: [Errno 4] No address associated with name
Mai 28 00:58:45 admin salt-master[42093]: [ERROR   ] Exception during resolving address: [Errno 4] No address associated with name
Mai 28 00:58:45 admin salt-master[42093]: [ERROR   ] Exception during resolving address: [Errno 4] No address associated with name
Mai 28 00:58:45 admin salt-master[42093]: [ERROR   ] Exception during resolving address: [Errno 4] No address associated with name

**Comment by petervarkoly** [comment]
When I remove "presence_events: True" the first reported errors disappear and only the errors which exist without any configuration stand.

**Comment by petervarkoly** [comment]
This seems to solve the first reported problem:

 --- /usr/lib/python2.7/site-packages/salt/utils/network.py-orig 2019-05-28 01:11:49.031247277 +0200
+++ /usr/lib/python2.7/site-packages/salt/utils/network.py      2019-05-28 01:10:12.318884560 +0200
@@ -1471,7 +1471,7 @@
     remotes = set()
     valid = False
     try:
-        data = subprocess.check_output(['ss', '-ant'])  # pylint: disable=minimum-python-version
+        data = subprocess.check_output(['ss', '-4ant'])  # pylint: disable=minimum-python-version
     except subprocess.CalledProcessError:
         log.error('Failed ss')
         raise

**Comment by dmurphy18** [comment]
@petervarkoly Are you making use of the scheduler, or alternatively reactor's ?

See something similar on Centos 7 with Salt 2018.3.3 locally on some masters but no resolution on it yet, but suspect the scheduler is resource leaking, dying with networking sockets getting messed up too.

from our log:
2019-05-10 04:23:28,287 [salt.utils.process:754 ][ERROR   ][16355] An un-handled exception from the multiprocessing process 'Maintenance-10' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/utils/process.py", line 747, in _run
    return self._original_run()
  File "/usr/lib/python2.7/site-packages/salt/master.py", line 223, in run
    salt.daemons.masterapi.clean_old_jobs(self.opts)
  File "/usr/lib/python2.7/site-packages/salt/daemons/masterapi.py", line 169, in clean_old_jobs
    rend=False,
  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 874, in __init__
    self.opts['grains'] = salt.loader.grains(opts)
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 737, in grains
    ret = funcs[key]()
  File "/usr/lib/python2.7/site-packages/salt/grains/core.py", line 2142, in hwaddr_interfaces
    ifaces = _get_interfaces()
  File "/usr/lib/python2.7/site-packages/salt/grains/core.py", line 1420, in _get_interfaces
    _INTERFACES = salt.utils.network.interfaces()
  File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 1053, in interfaces
    return linux_interfaces()
  File "/usr/lib/python2.7/site-packages/salt/utils/network.py", line 850, in linux_interfaces
    stderr=subprocess.STDOUT).communicate()[0]
  File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1224, in _execute_child
    self.pid = os.fork()
OSError: [Errno 12] Cannot allocate memory

**Comment by petervarkoly** [comment]
I do not use scheduler or reactor. But I'm using a self written daemon which catch the start, lost and present events:
##########
import fnmatch
import subprocess
import threading
import salt.config
import salt.utils.event

def event_handler(ret):
    if event_log_level == "debug":
       print ret
    if fnmatch.fnmatch(ret['tag'], 'salt/minion/*/start'):
       print "Client started: " + ret['data']['id']
       #Start the plugins
       subprocess.call(["/usr/share/oss/plugins/client_plugin_handler.sh","start", ret['data']['id']])
    if fnmatch.fnmatch(ret['tag'], 'salt/presence/change'):
       print "Client lost: " + ','.join(ret['data']['lost'])
       subprocess.call(["/usr/share/oss/plugins/client_plugin_handler.sh","lost", ','.join(ret['data']['lost'])])
    if fnmatch.fnmatch(ret['tag'], 'salt/presence/present'):
       subprocess.call(["/usr/share/oss/plugins/client_plugin_handler.sh","present", ','.join(ret['data']['present'])])


opts = salt.config.client_config('/etc/salt/master')
sevent = salt.utils.event.get_event(
        'master',
        sock_dir=opts['sock_dir'],
        transport=opts['transport'],
        opts=opts)

event_log_level="warning"
if opts.has_key('oss_event_log_level'):
   event_log_level = opts['oss_event_log_level']

while True:
    ret = sevent.get_event(full=True)
    if ret is None:
        continue
    if fnmatch.fnmatch(ret['tag'], 'salt/event/exit'):
        continue
    t = threading.Thread(target=event_handler,args=(ret,))
    t.start()
