### ISSUE TITLE
unit.modules.test_win_file.WinFileTestCase.test_issue_52002_check_file_remove_symlink failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53276]
The test `unit.modules.test_win_file.WinFileTestCase.test_issue_52002_check_file_remove_symlink` is failing on both windows 2016 and 2019 python 2

https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2016-py2/lastFailedBuild/
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2019-py2/lastFailedBuild/

it looks like https://github.com/saltstack/salt/pull/53157 attempted to resolve this error but i'm still seeing it fail on the most recent branch builds.

**Comment by cmcmarrow** [comment]
I have replicate the error
