### ISSUE TITLE
integration.states.test_pkg failing on amazon 1 py2

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53274]
The tests:

```
integration.states.test_pkg.PkgTest.test_pkg_009_latest_with_epoch
integration.states.test_pkg.PkgTest.test_pkg_010_latest_with_epoch_and_info_installed
```

are failing on amazon 1 python 2
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-1-py2/lastFailedBuild/

**Comment by dmurphy18** [comment]
Amazon Linux 1 does not have bash-completion as a package

[root@ip-10-200-45-57 ec2-user]# yum list | grep bash
bash.x86_64                           4.2.46-28.37.amzn1            installed   
bash-doc.x86_64                       4.2.46-28.37.amzn1            amzn-main   

Test is expecting bash-completion to exist on Amazon Linux 1 when it does not

19:46:02         -----------------------------------------------------------------------------------------------------------------------
19:46:02         --------  Failed Tests  -----------------------------------------------------------------------------------------------
19:46:02           -> integration.states.test_pkg.PkgTest.test_pkg_009_latest_with_epoch  ..............................................
19:46:02        Traceback (most recent call last):
19:46:02          File "/tmp/kitchen/testing/tests/support/helpers.py", line 212, in wrap
19:46:02            raise exc
19:46:02        AssertionError: False is not True. Salt Comment:
19:46:02        Error occurred installing package(s). Additional info follows:
19:46:02        
19:46:02        errors:
19:46:02            - Loaded plugins: priorities, update-motd, upgrade-helper
19:46:02              No package **_bash-completion_** available.
19:46:02              Error: Nothing to do
19:46:02           **..........................
**

**Comment by dmurphy18** [comment]
Adjusted tests, https://github.com/saltstack/salt/pull/53323

**Comment by dmurphy18** [comment]
Updated test after review suggestion to leverage _bash-doc_ instead of _bash-completion_ on Amazon Linux 1

**Comment by KChandrashekhar** [comment]
Ok, closing this as not seeing this failure anymore
