### ISSUE TITLE
"No module named zmq" on multiple test failures in transport TCP tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53280]
The following tests:

unit.test_auth.MasterACLTestCase.test_args_empty_spec
unittest.loader.ModuleImportFailure.integration.netapi.rest_tornado.test_app
unit.utils.test_verify.TestVerify.test_zmq_verify_insufficient 
unittest.loader.ModuleImportFailure.unit.netapi.test_rest_tornado
unittest.loader.ModuleImportFailure.unit.transport.test_zeromq

are failing here https://jenkinsci.saltstack.com/job/2019.2.1/view/Transport/job/salt-centos-7-py2-tcp/9/

due to an import error:

```
ImportError: Failed to import test module: unit.netapi.test_rest_tornado
Traceback (most recent call last):
  File "/usr/lib64/python2.7/unittest/loader.py", line 252, in _find_tests
    module = self._get_module_from_name(name)
  File "/usr/lib64/python2.7/unittest/loader.py", line 230, in _get_module_from_name
    __import__(name)
  File "/tmp/kitchen/testing/tests/unit/netapi/test_rest_tornado.py", line 19, in <module>
    from tests.unit.utils.test_event import eventpublisher_process, SOCK_DIR  # pylint: disable=import-error
  File "/tmp/kitchen/testing/tests/unit/utils/test_event.py", line 16, in <module>
    import zmq
ImportError: No module named zmq
```

**Comment by s0undt3ch** [comment]
@KChandrashekhar, @DmitryKuzmenko I'm taking over this ticket since I know what the breakage is - https://github.com/saltstack/salt/pull/53297

**Comment by DmitryKuzmenko** [comment]
@s0undt3ch I thought we shall work on changing code to make tcp transport independent on zmq libraries. But if it's not a point for the current release I'm ok. Thank you!

**Comment by s0undt3ch** [comment]
#53297 was merged, this should now be fixed.

**Comment by s0undt3ch** [comment]
This particular failure is no longer happening, ie, it's now fixed.
