### ISSUE TITLE
salt-api authentication denied (http 401 is returned) using runner module

### ISSUE THREAD

**Issue by steoli** [saltstack/salt#53313]
### Description of Issue
Hi
Im having trouble using salt-api and the runners module/client. I succeed to run commands using client=local but as soon as I try anything using client=runner im getting authentication problems.

I have google'd like crazy and found exact and similar situations just as me but found no-one with a solutions so I really need help on this one.

I have salt-api started in debug mode (salt-api -l debug) and the output from the 3 curl commands mentioned in the reproduce section below is generating this salt-api debug output:

[INFO    ] [api_acl] Authentication not checked for user salttest from IP 127.0.0.1
[DEBUG   ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None)
[DEBUG   ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None)
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'rod1salt03_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[30/May/2019:13:28:59] ENGINE Started monitor thread 'Session cleanup'.
[INFO    ] [30/May/2019:13:28:59] ENGINE Started monitor thread 'Session cleanup'.
[DEBUG   ] Configuration for external_auth malformed for eauth 'pam', and user 'salttest'.
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1892, in POST
    perms.extend(eauth.get('*', []))
AttributeError: 'unicode' object has no attribute 'extend'
127.0.0.1 - - [30/May/2019:13:28:59] "POST /login HTTP/1.1" 200 155 "" "curl/7.47.0"
[INFO    ] 127.0.0.1 - - [30/May/2019:13:28:59] "POST /login HTTP/1.1" 200 155 "" "curl/7.47.0"

[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'rod1salt03_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/40/0142b08890b7fb797d7ad29881d5b3025aaa1503711254ecf036bebea13f2d/.minions.p
[DEBUG   ] get_iter_returns for jid 20190530132913130438 sent to set(['RCSPLAYtest1']) will timeout at 13:29:18.138032
[DEBUG   ] jid 20190530132913130438 return from RCSPLAYtest1
[DEBUG   ] return event: {u'RCSPLAYtest1': {u'jid': u'20190530132913130438', u'retcode': 0, u'ret': True}}
[DEBUG   ] jid 20190530132913130438 found all minions set([u'RCSPLAYtest1'])
[DEBUG   ] Closing IPCMessageSubscriber instance
127.0.0.1 - - [30/May/2019:13:29:13] "POST / HTTP/1.1" 200 36 "" "curl/7.47.0"
[INFO    ] 127.0.0.1 - - [30/May/2019:13:29:13] "POST / HTTP/1.1" 200 36 "" "curl/7.47.0"

[DEBUG   ] LazyLoaded salt.cmd
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'rod1salt03_master', u'tcp://127.0.0.1:4506', u'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Closing IPCMessageSubscriber instance
127.0.0.1 - - [30/May/2019:13:30:00] "POST / HTTP/1.1" 401 1356 "" "curl/7.47.0"
[INFO    ] 127.0.0.1 - - [30/May/2019:13:30:00] "POST / HTTP/1.1" 401 1356 "" "curl/7.47.0"

### Setup

/etc/salt/master:
...
external_auth:
  pam:
    salttest:
      — .*
      — ‘@runner’
      — ‘@jobs’
    saltstack:
      — .*
      — ‘@runner’
      — ‘@jobs’
...
rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
  debug: true

### Steps to Reproduce Issue
~$ curl -sSk https://localhost:8000/login \
      -c /tmp/cookies.txt \
      -H 'Accept: application/x-yaml' \
      -d username=salttest \
      -d password=<xxxxx> \
      -d eauth=pam
return:
- eauth: pam
  expire: 1559266139.237897
  perms: {}
  start: 1559222939.237896
  token: <xxxxx>
  user: salttest

~$ curl -sSk https://localhost:8000 \
      -b /tmp/cookies.txt \
      -H 'Content-type: application/json' \
      -d '
[{
    "client": "local",
    "fun": "test.ping",
    "tgt": "RCSPLAYtest1"
}]
'
{"return": [{"RCSPLAYtest1": true}]}

~$ curl -sSk https://localhost:8000 \
      -b /tmp/cookies.txt \
      -H 'Content-type: application/json' \
      -d '
[{
    "client": "runner",
    "fun": "salt.cmd",
    "kwarg": {
      "fun": "cmd.run",
      "cmd": "whoami",
      "shell": "/bin/sh"
    }
}]
'
<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>No permission -- see authorization schemes</p>
        <pre id="traceback">Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 630, in respond
    self._do_respond(path_info)
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 689, in _do_respond
    response.body = self.handler()
  File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
    self.body = self.oldhandler(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 863, in hypermedia_handler
    raise cherrypy.HTTPError(401)
HTTPError: (401, None)
</pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 17.4.1</a>
      </span>
    </div>
    </body>
</html>

### Versions Report
master/minion versions are the same and on version 2019.2

~# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1079-aws
         system: Linux
        version: Ubuntu 16.04 xenial

~# salt-api --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.1
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1079-aws
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by dmurphy18** [comment]
@steoli This seems similar to https://github.com/saltstack/salt/issues/46550.  Can you retry this with the version packaged by SaltStack for Ubuntu 16.04, which is python-cherrypy v5.6.0 and inform me of the results.

**Comment by steoli** [comment]
ok not sure if I got the saltstack packaged version of  but I uninstalled cherrypy and then executed "pip install CherryPy==5.6.0"

# salt-api --versions-report | grep cherrypy
       cherrypy: 5.6.0

Still the same problem. Did I get the correct version (the one packaged by saltstack) by installing it using pip like this ?

Is there something more I can test ?

**Comment by dmurphy18** [comment]
Typically if SaltStack ships a version of cherrypy it is 5.6.0 and assumed we shipped that version for Ubuntu 16.04, however I just checked and SaltStack relies on the version supplied by the OS:

root@david-VirtualBox:/home/david# apt-cache policy python-cherrypy
python-cherrypy:
  Installed: (none)
  Candidate: 2.3.0-5
  Version table:
     2.3.0-5 500
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe amd64 Packages
        500 http://us.archive.ubuntu.com/ubuntu xenial/universe i386 Packages
root@david-VirtualBox:/home/david# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial

Please retry with the OS supplied version.  Sorry about my incorrect assumption on v5.6.0.

Did this work for you on earlier versions of Salt ?, or is this the first time trying it on Salt and 2019.2.0.
Wondering if recent work on support for Python 3 encode / decode has affected how this code operates.

**Comment by steoli** [comment]
This is our first attempt using salt-api like this so we never got it to work.

I have deinstalled cherrypy and instead install the OS provided version

root@rodf1salt03:~# apt list -a python-cherrypy
Listing... Done
python-cherrypy/xenial,now 2.3.0-5 all [installed]

root@rodf1salt03:~# salt-api --versions-report | grep cherrypy
       cherrypy: 2.3.0

Now cherrypy wont even start so we have nothing running that is  listening on port 8000.

Startup info (on which the RunNetapi-1 error repeats with new start attemps every 5 second aprox)


[INFO    ] Starting rest_cherrypy.start netapi module
[DEBUG   ] Started 'RunNetapi' with pid 18770
[DEBUG   ] Process Manager starting!
[DEBUG   ] LazyLoaded rest_cherrypy.start
[WARNING ] Import of cherrypy.cpstats failed.
[ERROR   ] An un-handled exception from the multiprocessing process 'RunNetapi-1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/client/netapi.py", line 49, in run
    netapi_func()
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/__init__.py", line 79, in start
    from . import app
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1114, in <module>
    setattr(cherrypy.tools, tool_name, cherrypy.Tool(
AttributeError: 'module' object has no attribute 'tools'
Process RunNetapi-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/client/netapi.py", line 49, in run
    netapi_func()
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/__init__.py", line 79, in start
    from . import app
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1114, in <module>
    setattr(cherrypy.tools, tool_name, cherrypy.Tool(
AttributeError: 'module' object has no attribute 'tools'



[INFO    ] Process <class 'salt.client.netapi.RunNetapi'> (18770) died with exit status 1, restarting...
[DEBUG   ] Started 'salt.client.netapi.RunNetapi' with pid 18821
[DEBUG   ] LazyLoaded rest_cherrypy.start
[WARNING ] Import of cherrypy.cpstats failed.
[ERROR   ] An un-handled exception from the multiprocessing process 'RunNetapi-2' was caught:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/client/netapi.py", line 49, in run
    netapi_func()
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/__init__.py", line 79, in start
    from . import app
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1114, in <module>
    setattr(cherrypy.tools, tool_name, cherrypy.Tool(
AttributeError: 'module' object has no attribute 'tools'
Process RunNetapi-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/dist-packages/salt/utils/process.py", line 765, in _run
    return self._original_run()
  File "/usr/lib/python2.7/dist-packages/salt/client/netapi.py", line 49, in run
    netapi_func()
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/__init__.py", line 79, in start
    from . import app
  File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1114, in <module>
    setattr(cherrypy.tools, tool_name, cherrypy.Tool(
AttributeError: 'module' object has no attribute 'tools'
...

I saw that you have a Ubuntu running also, does this work for you trying to just start it up ?

Not sure if we are missing some other dependency package or perhaps something else being on wrong version or something. 

If I from this stage upgrade cherrypy to lets say 5.6.0 using pip it starts fine and we have a service listening on port 8000 but then we have the initial problem with the runner module not authenticating.

**Comment by steoli** [comment]
I just spun up a new Ubuntu 16.04 server, installed salt and cherrypy, applied the same salt_master config, tested and its the same problem on a complete clean installation

**Comment by dmurphy18** [comment]
Thanks for that info.

**Comment by cmcmarrow** [comment]
https://github.com/saltstack/salt/issues/43581

**Comment by cmcmarrow** [comment]
By the looks of it cherrypy has changed again or you got a custom cherrypy some how.

**Comment by steoli** [comment]
Thx, for looking in to this issue, really appreciated.

Not sure if it helps but im attaching the Vagrantfile im using to spun up new Ubuntu16 with salt automagically installed and configured as per my test.

[Vagrantfile.txt](https://github.com/saltstack/salt/files/3287926/Vagrantfile.txt)

The CherryPy version i end up using in this vagrantfile  is 3.2.3 (installed using pip). The native version 3.5.0 that comes with the ubuntu repo is giving me "curl: (56) GnuTLS recv error (-15): An unexpected TLS packet was received" error on my initial curl /login attempt.

**Comment by davidme4** [comment]
Hi, guys, I have the same issue, with Salt 3000.3 on CentOS7 and cherryPy 5.6.0 : 401 using salt cherryPi REST API for Runners (with `client=runner`).
API OK with other `client=local`... 
PAM external_auth is set with `@runner` in master conf.
Config :
```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.14.0
       cherrypy: 5.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.12.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```

**Comment by shorawitz** [comment]
I am seeing the same issue as well with 3001.1 on Centos7:

```sudo salt-api --versions-report
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: 1.14.3
       cherrypy: 5.6.0
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 5.4.0-47-generic
         system: Linux
        version: CentOS Linux 7 Core
```

master config:
```
external_auth:
  pam:
    saltapi:
      - .*
      - '@runner'
```

**Comment by sooraj2589** [comment]
> ### Description of Issue
> Hi
> Im having trouble using salt-api and the runners module/client. I succeed to run commands using client=local but as soon as I try anything using client=runner im getting authentication problems.
> 
> I have google'd like crazy and found exact and similar situations just as me but found no-one with a solutions so I really need help on this one.
> 
> I have salt-api started in debug mode (salt-api -l debug) and the output from the 3 curl commands mentioned in the reproduce section below is generating this salt-api debug output:
> 
> [INFO ] [api_acl] Authentication not checked for user salttest from IP 127.0.0.1
> [DEBUG ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None)
> [DEBUG ] Popen(['git', 'version'], cwd=/root, universal_newlines=False, shell=None)
> [DEBUG ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'rod1salt03_master', u'tcp://127.0.0.1:4506', u'clear')
> [DEBUG ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
> [DEBUG ] Trying to connect to: tcp://127.0.0.1:4506
> [DEBUG ] Closing AsyncZeroMQReqChannel instance
> [30/May/2019:13:28:59] ENGINE Started monitor thread 'Session cleanup'.
> [INFO ] [30/May/2019:13:28:59] ENGINE Started monitor thread 'Session cleanup'.
> [DEBUG ] Configuration for external_auth malformed for eauth 'pam', and user 'salttest'.
> Traceback (most recent call last):
> File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 1892, in POST
> perms.extend(eauth.get('*', []))
> AttributeError: 'unicode' object has no attribute 'extend'
> 127.0.0.1 - - [30/May/2019:13:28:59] "POST /login HTTP/1.1" 200 155 "" "curl/7.47.0"
> [INFO ] 127.0.0.1 - - [30/May/2019:13:28:59] "POST /login HTTP/1.1" 200 155 "" "curl/7.47.0"
> 
> [DEBUG ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
> [DEBUG ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
> [DEBUG ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'rod1salt03_master', u'tcp://127.0.0.1:4506', u'clear')
> [DEBUG ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
> [DEBUG ] Trying to connect to: tcp://127.0.0.1:4506
> [DEBUG ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
> [DEBUG ] Closing AsyncZeroMQReqChannel instance
> [DEBUG ] LazyLoaded local_cache.get_load
> [DEBUG ] Reading minion list from /var/cache/salt/master/jobs/40/0142b08890b7fb797d7ad29881d5b3025aaa1503711254ecf036bebea13f2d/.minions.p
> [DEBUG ] get_iter_returns for jid 20190530132913130438 sent to set(['RCSPLAYtest1']) will timeout at 13:29:18.138032
> [DEBUG ] jid 20190530132913130438 return from RCSPLAYtest1
> [DEBUG ] return event: {u'RCSPLAYtest1': {u'jid': u'20190530132913130438', u'retcode': 0, u'ret': True}}
> [DEBUG ] jid 20190530132913130438 found all minions set([u'RCSPLAYtest1'])
> [DEBUG ] Closing IPCMessageSubscriber instance
> 127.0.0.1 - - [30/May/2019:13:29:13] "POST / HTTP/1.1" 200 36 "" "curl/7.47.0"
> [INFO ] 127.0.0.1 - - [30/May/2019:13:29:13] "POST / HTTP/1.1" 200 36 "" "curl/7.47.0"
> 
> [DEBUG ] LazyLoaded salt.cmd
> [DEBUG ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
> [DEBUG ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
> [DEBUG ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
> [DEBUG ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'rod1salt03_master', u'tcp://127.0.0.1:4506', u'clear')
> [DEBUG ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
> [DEBUG ] Trying to connect to: tcp://127.0.0.1:4506
> [DEBUG ] Closing AsyncZeroMQReqChannel instance
> [DEBUG ] Closing IPCMessageSubscriber instance
> 127.0.0.1 - - [30/May/2019:13:30:00] "POST / HTTP/1.1" 401 1356 "" "curl/7.47.0"
> [INFO ] 127.0.0.1 - - [30/May/2019:13:30:00] "POST / HTTP/1.1" 401 1356 "" "curl/7.47.0"
> 
> ### Setup
> /etc/salt/master:
> ...
> external_auth:
> pam:
> salttest:
> — .*
> — ‘@runner’
> — ‘@jobs’
> saltstack:
> — .*
> — ‘@runner’
> — ‘@jobs’
> ...
> rest_cherrypy:
> port: 8000
> ssl_crt: /etc/pki/tls/certs/localhost.crt
> ssl_key: /etc/pki/tls/certs/localhost.key
> debug: true
> 
> ### Steps to Reproduce Issue
> ~$ curl -sSk https://localhost:8000/login
> -c /tmp/cookies.txt
> -H 'Accept: application/x-yaml'
> -d username=salttest
> -d password=
> -d eauth=pam
> return:
> 
> * eauth: pam
>   expire: 1559266139.237897
>   perms: {}
>   start: 1559222939.237896
>   token: 
>   user: salttest
> 
> ~$ curl -sSk https://localhost:8000
> -b /tmp/cookies.txt
> -H 'Content-type: application/json'
> -d '
> [{
> "client": "local",
> "fun": "test.ping",
> "tgt": "RCSPLAYtest1"
> }]
> '
> {"return": [{"RCSPLAYtest1": true}]}
> 
> ~$ curl -sSk https://localhost:8000
> -b /tmp/cookies.txt
> -H 'Content-type: application/json'
> -d '
> [{
> "client": "runner",
> "fun": "salt.cmd",
> "kwarg": {
> "fun": "cmd.run",
> "cmd": "whoami",
> "shell": "/bin/sh"
> }
> }]
> '
> 
> <title>401 Unauthorized</title> <style type="text/css"> #powered_by { margin-top: 20px; border-top: 2px solid black; font-style: italic; }
> ```
> #traceback {
>     color: red;
> }
> </style>
> ```
> 
> ## 401 Unauthorized
> No permission -- see authorization schemes
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 630, in respond
>     self._do_respond(path_info)
>   File "/usr/local/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 689, in _do_respond
>     response.body = self.handler()
>   File "/usr/local/lib/python2.7/dist-packages/cherrypy/lib/encoding.py", line 221, in __call__
>     self.body = self.oldhandler(*args, **kwargs)
>   File "/usr/lib/python2.7/dist-packages/salt/netapi/rest_cherrypy/app.py", line 863, in hypermedia_handler
>     raise cherrypy.HTTPError(401)
> HTTPError: (401, None)
> Powered by [CherryPy 17.4.1](http://www.cherrypy.org)
> ### Versions Report
> master/minion versions are the same and on version 2019.2
> 
> ~# salt --versions-report
> Salt Version:
> Salt: 2019.2.0
> 
> Dependency Versions:
> cffi: 1.11.5
> cherrypy: unknown
> dateutil: 2.4.2
> docker-py: Not Installed
> gitdb: 2.0.5
> gitpython: 2.1.11
> ioflo: Not Installed
> Jinja2: 2.8
> libgit2: Not Installed
> libnacl: Not Installed
> M2Crypto: Not Installed
> Mako: 1.0.3
> msgpack-pure: Not Installed
> msgpack-python: 0.4.6
> mysql-python: Not Installed
> pycparser: 2.19
> pycrypto: 2.6.1
> pycryptodome: Not Installed
> pygit2: Not Installed
> Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
> python-gnupg: 0.3.8
> PyYAML: 3.11
> PyZMQ: 15.2.0
> RAET: Not Installed
> smmap: 2.0.5
> timelib: Not Installed
> Tornado: 4.2.1
> ZMQ: 4.1.4
> 
> System Versions:
> dist: Ubuntu 16.04 xenial
> locale: UTF-8
> machine: x86_64
> release: 4.4.0-1079-aws
> system: Linux
> version: Ubuntu 16.04 xenial
> 
> ~# salt-api --versions-report
> Salt Version:
> Salt: 2019.2.0
> 
> Dependency Versions:
> cffi: 1.11.5
> cherrypy: 17.4.1
> dateutil: 2.4.2
> docker-py: Not Installed
> gitdb: 2.0.5
> gitpython: 2.1.11
> ioflo: Not Installed
> Jinja2: 2.8
> libgit2: Not Installed
> libnacl: Not Installed
> M2Crypto: Not Installed
> Mako: 1.0.3
> msgpack-pure: Not Installed
> msgpack-python: 0.4.6
> mysql-python: Not Installed
> pycparser: 2.19
> pycrypto: 2.6.1
> pycryptodome: Not Installed
> pygit2: Not Installed
> Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
> python-gnupg: 0.3.8
> PyYAML: 3.11
> PyZMQ: 15.2.0
> RAET: Not Installed
> smmap: 2.0.5
> timelib: Not Installed
> Tornado: 4.2.1
> ZMQ: 4.1.4
> 
> System Versions:
> dist: Ubuntu 16.04 xenial
> locale: UTF-8
> machine: x86_64
> release: 4.4.0-1079-aws
> system: Linux
> version: Ubuntu 16.04 xenial

How you created the saltuser" salttest"? we are also on the same phase of using apis.. could help please

**Comment by ixs** [comment]
@saltbot-open please reopen, issue is still current.

**Comment by dmurphy18** [comment]
@ixs I noticed in this old issue that the version of Python is 2.7.  That is long EOL'd and is no longer supported.
And the versions of Salt 3000.3 are also long EOL'd.  The previous comment is from 2020, and the issue has been closed for over 2 years.

If you are experiencing a similar issue, please open a new issue with details on the version of Salt used for salt-master and salt-minion, the version of the OS, the version of Python used, and steps to re-create the issue.
