### ISSUE TITLE
Windows automated tests failing due to openssl installer 404

### ISSUE THREAD

**Issue by LuAPi** [saltstack/salt#53312]
### Description of Issue
The initial salt state apply in the windows builds is failing because `slproweb.com` doesn't seem to be hosting `Win64OpenSSL-1_0_2r.exe` anymore. It seemed to have disappeared around 24 hours ago.
```
18:28:28           ID: openssl
18:28:28            Function: module.run
18:28:28         Name: winrepo_pkg.install
18:28:28              Result: False
18:28:28             Comment: Module function winrepo_pkg.install threw an exception. Exception: Error: HTTP 404: Not Found reading https://slproweb.com/download/Win64OpenSSL-1_0_2r.exe
```

Examples:
https://jenkinsci.saltstack.com/job/pr-kitchen-windows2016-py3/job/PR-53234/14/consoleFull
https://jenkinsci.saltstack.com/job/pr-kitchen-windows2016-py2/job/PR-53234/14/consoleFull

### Setup
Any PR that triggers a windows build that attempts to install openssl using this state
https://github.com/saltstack/salt-jenkins/blob/2019.2/windows/openssl.sls

### Steps to Reproduce Issue
Open a PR or push a commit to an existing one that triggers a windows build that doesn't break before trying to apply that state.

### Versions Report
N/A

Should I have reported this here or in https://github.com/saltstack/salt-jenkins ?

**Comment by twangboy** [comment]
Yeah, looks like they removed  https://slproweb.com/download/Win64OpenSSL-1_0_2r.exe
Should update to  https://slproweb.com/download/Win64OpenSSL-1_0_2s.exe

**Comment by LuAPi** [comment]
Did the automated merge forward fail?
https://github.com/saltstack/salt-jenkins/blob/2019.2/windows/openssl.sls still points at Win64OpenSSL-1_0_2r.exe
but branches 2017.7 , 2018.3 and develop all point at Win64OpenSSL-1_0_2s.exe .

**Comment by LuAPi** [comment]
Looks like a merge forward happened an hour ago and fixed this.
