### ISSUE TITLE
Redhat 8

### ISSUE THREAD

**Issue by tcarysmith** [saltstack/salt#53322]
Anyone running the minion under Redhat 8?

SaltStack Latest Release Channel Python 3 for RHEL/Centos 8                                                 417 kB/s |  54 kB     00:00    
Error: 
 Problem: package salt-minion-2019.2.0-2.el7.noarch requires salt = 2019.2.0-2.el7, but none of the providers can be installed
  - conflicting requests
  - nothing provides python36-six needed by salt-2019.2.0-2.el7.noarch
  - nothing provides python36-PyYAML needed by salt-2019.2.0-2.el7.noarch
  - nothing provides python36-requests needed by salt-2019.2.0-2.el7.noarch
  - nothing provides python36-jinja2 needed by salt-2019.2.0-2.el7.noarch
  - nothing provides python36-markupsafe needed by salt-2019.2.0-2.el7.noarch
  - nothing provides python36-psutil needed by salt-2019.2.0-2.el7.noarch
  - nothing provides systemd-python needed by salt-2019.2.0-2.el7.noarch
  - nothing provides python36-crypto >= 2.6.1 needed by salt-2019.2.0-2.el7.noarch
  - nothing provides python36-msgpack >= 0.4 needed by salt-2019.2.0-2.el7.noarch
  - nothing provides python36-tornado >= 4.2.1 needed by salt-2019.2.0-2.el7.noarch
  - nothing provides python36-tornado < 5.0 needed by salt-2019.2.0-2.el7.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)

**Comment by dmurphy18** [comment]
@tcarysmith Redhat 8 has a number of issues with running Salt as it currently stands on Python 3.  First and foremost is lack of python-tornado, and a number of other packages, for example: Cython, msgpack, zeromq, etc.

However there will be support for Redhat 8 with the next point release, where these dependent packages are provided by SaltStack, similar to other Redhat 7 and 6 support.  Already have a hand-built version of Salt for Redhat 8 which is currently used for automated building, and is awaiting the Salt 2019.2.1 point release.  Note the provided version of python-tornado used on Python 3 is v4.5.2 with Salt modified to use this version (Salt hand-built version 2019.2.0), waiting on test completion for support of python-tornado v5.x in Salt 2019.2.1, among other fixes for point release.

The issue tracking the Redhat 8 support was https://github.com/saltstack/salt-pack-py3/issues/120

If this provided information is sufficient, please consider closing this issue.
