### ISSUE TITLE
salt prints the output from first command if using cmd.run with pipes

### ISSUE THREAD

**Issue by gecube** [saltstack/salt#53359]
### Description of Issue

I intensively use salt-ssh and found some kind of unexpected behavior. For example, I want to make remote server run shell command with pipe:

```bash
$ salt-ssh server cmd.run "uname -a | awk '{print $1}'"
[ERROR   ] Failed collecting tops for Python binary python3.
server:
    Linux MS-7A75 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
It prints the output from the first part of command sent to remote server. I checked `cmd.shell` instead of `cmd.run` and observed the same.
Also I tried different magic with prepending the command with "sh -c" - still no luck.

I believe that salt should write the next output:
```bash
$ salt-ssh server cmd.run "uname -a | awk '{print $1}'"
[ERROR   ] Failed collecting tops for Python binary python3.
server:
    Linux
```

### Versions Report

salt-ssh 2018.3.4
salt-ssh 2019.2.0 (Fluorine)
and many others

**Comment by Akm0d** [comment]
Under the hood cmd.run uses the subprocess module.  As described [here](https://stackoverflow.com/questions/13332268/how-to-use-subprocess-command-with-pipes) you can pass piped commands using the "shell=True" flag, although it isn't advisable to pipe commands through subprocess.

**Comment by Akm0d** [comment]
Well, `salt-call --local cmd.run "uname -a|awk '{print $1}'" shell='/bin/bash'` yielded the same result you described above, and "shell=True" gave me an error.  I'll take a look into cmdmod.py to see if I can pin this down

**Comment by Akm0d** [comment]
Related to https://github.com/saltstack/salt/issues/44226

**Comment by Akm0d** [comment]
In the [docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html) it says pipes are acceptable for cmd.run cmd.shell and cmd.run_all.  "Even with the python_shell=True" flag I haven't got any of those to work with `uname -a|awk '{print $1}'`.  There is definitely a bug.

**Comment by gecube** [comment]
@Akm0d thanks for checking the issue
Also I'd like to ask why issue has "Windows" flag. I use linux distributions (primarily ubuntu 18.04 lts).

**Comment by gecube** [comment]
I made more investigation and found interesting thing and it began to look like some kind of escaping issue

```
root@5f426a4e0dd9:/# uname -a | awk '{print $1}'
Linux
root@5f426a4e0dd9:/# sh -c "uname -a | awk '{print $1}'"
Linux 5f426a4e0dd9 5.1.4-1-default #1 SMP Wed May 22 11:11:40 UTC 2019 (0739fa4) x86_64 GNU/Linux
```
so invovation of inner shell 'eats' `$` sign and awk incorrectly works.
If we escape, it begin to work:
```
root@5f426a4e0dd9:/# sh -c "uname -a | awk '{print \$1}'"
Linux
```
Let's try the same trick with salt:
```
root@5f426a4e0dd9:/# salt-call -l all --local cmd.run "uname -a | awk '{print $1}'"
...
[DEBUG   ] key: cmd_blacklist_glob, ret: _|-
[DEBUG   ] key: cmd_whitelist_glob, ret: _|-
[INFO    ] Executing command 'uname -a | awk '{print }'' in directory '/root'
[DEBUG   ] stdout: Linux 5f426a4e0dd9 5.1.4-1-default #1 SMP Wed May 22 11:11:40 UTC 2019 (0739fa4) x86_64 GNU/Linux
[DEBUG   ] output: Linux 5f426a4e0dd9 5.1.4-1-default #1 SMP Wed May 22 11:11:40 UTC 2019 (0739fa4) x86_64 GNU/Linux
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {u'local': u'Linux 5f426a4e0dd9 5.1.4-1-default #1 SMP Wed May 22 11:11:40 UTC 2019 (0739fa4) x86_64 GNU/Linux'}
local:
    Linux 5f426a4e0dd9 5.1.4-1-default #1 SMP Wed May 22 11:11:40 UTC 2019 (0739fa4) x86_64 GNU/Linux
root@5f426a4e0dd9:/# salt-call -l all --local cmd.run "uname -a | awk '{print \$1}'"
...
[INFO    ] Executing command 'uname -a | awk '{print $1}'' in directory '/root'
[DEBUG   ] stdout: Linux
[DEBUG   ] output: Linux
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {u'local': u'Linux'}
local:
    Linux
```

So it looks like salt instantiate a shell anyway when runnning `cmd.run` state.
I'm not sure if it is correct to ask to make salt parse `cmd.run` argument and process the pipelining on it's own. I make something similar in my scripts sending output from one Popen call to another (chaining?). Like here: https://stackoverflow.com/questions/7389662/link-several-popen-commands-with-pipes/29755431

**Comment by Akm0d** [comment]
@gecube No problem!  My next step on Monday will be to test this on multiple branches to see what the earliest affected branch is.

**Comment by Akm0d** [comment]
If I escape the `$` then the command works as expected.  I'll check to make sure this behavior is documented correctly.  `salt-call --local cmd.run "uname -a|awk '{print \$1}'" shell='/bin/bash'`

**Comment by Akm0d** [comment]
The [docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html) say explicitly that special characters need to be escaped on MacOSx after 2018.3.  The examples have `$` escaped but it doesn't say anywhere I can see that it is necessary.

**Comment by piersf** [comment]
I can also confirm this issue. And after escaping the '$' it worked fine.
Running Debian 4.9.30-2+deb9u5 and
```
salt-master 2018.3.3 (Oxygen)
salt-minion 2018.3.3 (Oxygen)
```
