### ISSUE TITLE
user.add problem to windows

### ISSUE THREAD

**Issue by Dtengfei** [saltstack/salt#53363]
### Description of Issue

I executed "salt win15-ky.cq3 user.add name=" 2019123" groups=" Remote Desktop Users" on salt-master to prompt users to be int type. I don't know how pure digital users like me can add it? It seems that all operations involving Windows user are problematic. User. update is no good either.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.useradd.html
salt.modules.useradd.add(name, uid=None, gid=None, groups=None, home=None, shell=None, unique=True, system=False, fullname='', roomnumber='', workphone='', homephone='', other='', createhome=True, loginclass=None, root=None, nologinit=False)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
`  Passed invalid arguments to user.add: Objects of type 'int' can not be converted to Unicode.
    
        Add a user to the minion.
    
        Args:
            name (str): User name
    
            password (str, optional): User's password in plain text.
    
            fullname (str, optional): The user's full name.
    
            description (str, optional): A brief description of the user account.
    
            groups (str, optional): A list of groups to add the user to.
                (see chgroups)
    
            home (str, optional): The path to the user's home directory.
    
            homedrive (str, optional): The drive letter to assign to the home
                directory. Must be the Drive Letter followed by a colon. ie: U:
    
            profile (str, optional): An explicit path to a profile. Can be a UNC or
                a folder on the system. If left blank, windows uses it's default
                profile directory.
    
            logonscript (str, optional): Path to a login script to run when the user
                logs on.
    
        Returns:
            bool: True if successful. False is unsuccessful.
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' user.add name password`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
`Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.3
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core`

`win15-ky.cq3:
    2019.2.0`

**Comment by Dtengfei** [comment]
This problem hasn't been solved！

**Comment by twangboy** [comment]
The Above PR should fix this issue, among other issues.
