### ISSUE TITLE
--state-verbose=False output does not display warnings

### ISSUE THREAD

**Issue by raddessi** [saltstack/salt#53391]
### Description of Issue
When running salt commands with state_verbose set to False it appears that warnings are not shown, is this by design?

### Setup
Standard setup, my warning was caused by using file_mode rather than mode on a file.managed state:
```
----------
          ID: /some/test/file
    Function: file.managed
      Result: True
     Comment: File /some/test/file exists with proper permissions. No changes made.
     Started: 22:25:39.424675
    Duration: 2.833 ms
     Changes:
    Warnings: The 'file_mode' argument will be ignored.  Please use 'mode'
              instead to set file permissions.
```

### Steps to Reproduce Issue
Warnings are shown when True
```bash
# salt-run jobs.lookup_jid 20190605221907093347 --state-verbose True | grep -A20 "Summary for"
[INFO    ] Executing command '/usr/sbin/zpool list -H -o name,size' in directory '/root'
[INFO    ] Executing command '/usr/sbin/zpool list -H -o name,size' in directory '/root'
[INFO    ] Executing command '/usr/sbin/zpool list -H -o name,size' in directory '/root'
Summary for foo
---------------
Succeeded: 1245 (changed=16)
Failed:       0
Warnings:     6
---------------
Total states run:     1245
[INFO    ] Runner completed: 20190605224238022777
Total run time:    542.851 s
```

But not when False
```bash
# salt-run jobs.lookup_jid 20190605221907093347 --state-verbose False | grep -A20 "Summary for"
[INFO    ] Executing command '/usr/sbin/zpool list -H -o name,size' in directory '/root'
[INFO    ] Executing command '/usr/sbin/zpool list -H -o name,size' in directory '/root'
[INFO    ] Executing command '/usr/sbin/zpool list -H -o name,size' in directory '/root'
Summary for foo
---------------
Succeeded: 1245 (changed=16)
Failed:       0
---------------
Total states run:     1245
[INFO    ] Runner completed: 20190605224251996894
Total run time:    542.851 s
```
The entries for the states are also not shown (not just the summary) when set to False

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.2 |Continuum Analytics, Inc.| (default, Jul 20 2017, 13:51:32)
   python-gnupg: 0.4.4
         PyYAML: 5.1
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: fedora 29 Twenty Nine
         locale: UTF-8
        machine: x86_64
        release: 5.0.17-200.fc29.x86_64
         system: Linux
        version: Fedora 29 Twenty Nine
 
```

**Comment by raddessi** [comment]
OK thank you, good to know it's not be design :) This actually looks like a super simple fix.


```diff
--- output/highstate_backup.py	2019-06-06 13:49:22.109600887 -0600
+++ output/highstate.py	2019-06-06 13:47:01.904210746 -0600
@@ -267,6 +267,7 @@
                 not __opts__.get("state_verbose", False)
                 and ret["result"]
                 and not schanged
+                and "warnings" not in ret
             ):
                 continue
```

I'm not sure if this is the best way to do it but it seems to work for me. I can send a PR if you would like

**Comment by cmcmarrow** [comment]
Thanks raddessi for the info. Will get a fix in soon.

**Comment by cmcmarrow** [comment]
`state_verbose
    By default `state_verbose` is set to `True`, setting this to `False` will
    instruct the highstate outputter to omit displaying anything in green, this
    means that nothing with a result of True and no changes will not be printed`

raddessi I looked more into this and it looks like it is by design. But you can put in a feature request to get a flag like state_verbose with the only differences is it will show warnings too.

**Comment by cmcmarrow** [comment]
I'll go an add a state_verbose_warning flag

**Comment by raddessi** [comment]
Hmm.. the way I read that, I would still assume it would show these warnings since the warnings were printed not green. I can send a screenshot if you want. Some of the output for the state was green but the warning text itself was red I think.. possibly orange? I would have to run again to check.

As long as we could set the state_verbose_warning in our config file so its a constant global like everything else I think that would effectively resolve this issue for us. Thanks!

**Comment by cmcmarrow** [comment]
@raddessi I push state_verbose_warnings into 2018.3 for you. In joy!

**Comment by cmcmarrow** [comment]
Also if you happy with the changes can you please close the issue.

**Comment by raddessi** [comment]
Nice! This will be included in further releases as well correct? If so when that is merged this can be closed.
