### ISSUE TITLE
postgresql states use wrong user on FreeBSD

### ISSUE THREAD

**Issue by kgbsd** [saltstack/salt#53393]
### Description of Issue
https://github.com/saltstack/salt/pull/53327
Default user for 'postgresql' is outdated on FreeBSD.
KeyError: "getpwnam(): name not found: 'pgsql'"

That user was updated from 'pgsql' to 'postgresql' in 2016:
https://svnweb.freebsd.org/ports/head/UPDATING?revision=502290&view=co
20160905:
AFFECTS: users of databases/postgresql96-server
AUTHOR: girgen@FreeBSD.org

The default unix user used by the PostgreSQL daemon has changed to
postgres' to reflect the long time upstream's convention. Any scripts you have using the old pgsql' unix user should be modified when upgrading to
PostgreSQL version 9.6. Older versions of PostgreSQL will continue using
`pgsql' until their end-of-life.

### Setup
py36-salt-2019.2.0_1
12.0-STABLE FreeBSD

### Steps to Reproduce Issue
Try to run postgres_database or postgres_user salt states.

### Versions Report
py36-salt-2019.2.0_1
12.0-STABLE FreeBSD

**Comment by gecube** [comment]
Just my one cent. We are using salt with postgres in docker, so there is no need of psql client on the host, but I was forced to install it and configure postgres module according to https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.postgres.html And it works. The only thing that I don't remember if one could set the full path to psql binary.

So I believe that the setting correct pillar or configuration of minion will workaround the issue.

**Comment by piterpunk** [comment]
@sagetherage this issue can be closed with the #58915 's merge
