### ISSUE TITLE
unit.utils.test_win_osinfo.WinOsInfo.test_get_os_version_info failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#53459]
The test `unit.utils.test_win_osinfo.WinOsInfo.test_get_os_version_info` is failing on windows 2016:

https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-windows-2016-py2/101/testReport/junit/unit.utils.test_win_osinfo/WinOsInfo/test_get_os_version_info/

```
Traceback (most recent call last):
  File "c:\users\admini~1\appdata\local\temp\kitchen\testing\tests\unit\utils\test_win_osinfo.py", line 33, in test_get_os_version_info
    self.assertEqual(sys_info.major, int(get_info['MajorVersion']))
AssertionError: <MagicMock name=u'getwindowsversion().major' id='879303984'> != 6
```

**Comment by waynew** [comment]
Should be an easy fix: this line does not belong :P https://github.com/saltstack/salt/pull/52211/files#diff-354a77f7b380cb16e5924afbe18d81d6R351

(Also, it's being patched over 2 lines later)

**Comment by twangboy** [comment]
Fixed by https://github.com/saltstack/salt/pull/53437
