### ISSUE TITLE
Code blocks in Tables Rendered with Incorrect Whitespace

### ISSUE THREAD

**Issue by jhmcstanton** [saltstack/salt#53519]
### Description of Issue
Noticed on the [reactor system](https://docs.saltstack.com/en/2018.3/topics/reactor/index.html#runner-reactions) page, any code block in a table has weird whitespace. Noticed in firefox on Linux and safari.

Also noticed that the issue does not occur when locally building the docs with `make html`

### Setup
See above

### Versions Report
Noticed in all doc versions going back to 2018.3.4

**Comment by xeacott** [comment]
Running `make html` now to see how these differ and I'll report back. Marking with documentation label now thanks.
