### ISSUE TITLE
race condition with init script

### ISSUE THREAD

**Issue by tsaridas** [saltstack/salt#53549]
### Description of Issue
If user tries to start the agent at the same time with the init script in RH/centos the agent will be started twice.

### Steps to Reproduce Issue
run the script at the same time on the same box

### Versions Report
all versions of the minion

**Comment by Akm0d** [comment]
Can we get more details about exactly how to reproduce the bug as well as the output of `salt-call --local test.versions` on the minion?

**Comment by tsaridas** [comment]
@Akm0d I added both the information you requested in the initial message. Feels like you are copy pasting the message instead of reading the ticket.

**Comment by Akm0d** [comment]
I request more information on all issues that lack detailed information.  The more information given, the quicker we can get to the bottom of an issue and submit a fix.  It keeps me from having to guess exactly what is happening and brute-force trying to reproduce the issue.  Logs help, the exact commands run prior to encountering the issue really help.  Maybe the issue does occur on all minions, but using the same environment as you will eliminated noise from other unknown factors.

**Comment by tsaridas** [comment]
the issue does occur to all RH based init script minions.
you can test it by running the script on a different shell at the same time.

**Comment by waynew** [comment]
@tsaridas thanks for the report! I believe the point of `test.versions` is that we have multiple releases of Salt - 2018.3, 2019.2 that are currently supported. Knowing which version of Salt you're running helps us when we try to reproduce the issue.

**Comment by waynew** [comment]
@tsaridas could you also provide the exact command you used in the "run the script at the same time" step? There are numerous ways to actually start Salt, and it's not clear from your report which command(s) you used.

Thanks!

**Comment by tsaridas** [comment]
I used 
```
/etc/init.d/salt-minion start
```
this should affect all versions of the minion that use an init.d script to start.
