### ISSUE TITLE
'win_firewall.get_settings' is not available.

### ISSUE THREAD

**Issue by Dtengfei** [saltstack/salt#53558]
### Description of Issue
I deployed salt-minion version 2019.2 on Windows 2008ServerR2 and salt matser 2019.2 on CentOS 7.3. Then I used "salt win123 win_firewall.get_settings domain state" on matser and returned to'win_firewall.get_settings'is not available. Please help me to see the problem. I did not find error information in the master log.

### Setup

Modules I call directly
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.win_firewall.html

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
master-version
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.2.3
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.21.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

minion-version
    Salt Version:
               Salt: 2019.2.0
     
    Dependency Versions:
               cffi: 1.11.5
           cherrypy: 17.4.1
           dateutil: 2.7.5
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: 1.6.1
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.3
             PyYAML: 3.13
              PyZMQ: 17.1.2
               RAET: Not Installed
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.2.5
     
    System Versions:
               dist:   
             locale: cp936
            machine: AMD64
            release: 2008ServerR2
             system: Windows
            version: 2008ServerR2 6.1.7601 SP1 Multiprocessor Free

**Comment by xpicio** [comment]
Do you have tried with `salt win123 firewall.get_settings domain state` ?
On my windows 10 pro minion is working. You must reference to the modules with his virtual_name, from `win_firewall.py`

```
# Define the module's virtual name
__virtualname__ = 'firewall'
```

**Comment by Dtengfei** [comment]
First of all, I would like to express my gratitude to you for your answers. I can use the method you provided to run normally. Secondly, the previous error was operated according to our example, so the previous error occurred. Thank you again.
