### ISSUE TITLE
netconfig.managed commits config on Cisco IOS in the presence of test=True

### ISSUE THREAD

**Issue by dractyl** [saltstack/salt#53619]
### Description of Issue
I have two netconfig.managed stanzas for a particular switch. With test=True on the command line, the first instance respects it and does not commit, while the second instance ignores test=True and commits the config.

### Setup
I need to delete the switch config specific stuff, but I don't see that as relevant to this issue anyway.

```
SLS file:
cisco_basic_switch_config:
  netconfig.managed:
    - template_name: salt://{{ slspath }}/files/switch.jinja

cisco_individual_switch_config:
  netconfig.managed:
    - template_name: salt://{{ slspath }}/files/individual_config.jinja

```
When executed, cisco_basic_switch_config works properly and does not commit but then cisco_individual_switch_config runs and unexpectedly does.

This happened during a production maintenance window, so the flurry of unexpected log messages was something of a surprise.

We're moving to collapse these two configs into one, but neither the contents of the configs nor the fact that there are two should result in test=True being ignored.

FWIW, the configs are non-overlapping (one handles interfaces and the other, everything else)

### Steps to Reproduce Issue
I have not attempted to reproduce as my maintenance window has passed, but here is the command and its output (with switch config specifics removed; I'm offering what I can even if it's an imperfect bug report):

```
salt 'switch-a' state.apply test=True

switch-a:
----------
          ID: cisco_basic_switch_config
    Function: netconfig.managed
      Result: None
     Comment: Configuration discarded.
              
              Configuration diff:

< A diff of what would have been done >
              
     Started: 05:41:18.578389
    Duration: 18581.07 ms
     Changes:   
              ----------
              diff:
 < The same diff of what would have been done, a bit verbosely perhaps >
---------
          ID: cisco_individual_switch_config
    Function: netconfig.managed
      Result: True
     Comment: Configuration changed!
     Started: 05:41:37.159805
    Duration: 14933.766 ms
     Changes:   
              ----------
              diff:

< A diff of actual changes that it actually did >

Summary for switch-a
------------
Succeeded: 2 (unchanged=1, changed=2)
Failed:    0
------------
Total states run:     2
Total run time:  33.515 s

```
I can give this another go in our maintenance window, two weeks from now.

### Versions Report
On the master:

```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 5.1.1
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-36-generic
         system: Linux
        version: Ubuntu 18.04 bionic

```

On the Proxy:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.7 (default, Oct 22 2018, 11:32:17)
   python-gnupg: 0.4.1
         PyYAML: 5.1.1
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-52-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by raddessi** [comment]
I'm having this same issue right now in EOS, not even passing `test: True` to the state itself is being respected.

**Comment by sagetherage** [comment]
@dmurphy18

**Comment by raddessi** [comment]
https://github.com/saltstack/salt/pull/56299 may have resolved this, can someone check if behaviour has changed?

**Comment by sagetherage** [comment]
@raddessi I am seeing if there is someone who can test it this week, holiday this past Monday in US is making it a bit limited, but letting you know I am working on it!

> #56299 may have resolved this, can someone check if behaviour has changed?

**Comment by dmurphy18** [comment]
@raddessi Do you have a sample configuration which demonstrates the issue on EOS.  I have access to some Virtual EOS machines which I can test against.

**Comment by raddessi** [comment]
Any config should show the issue, as long as there is a config change, running with `test=True` would still apply changes. I don't have a config I can easily copy I'm afraid.

**Comment by raddessi** [comment]
We just finished updating to 3002.6 however, I'll check this some time next week and get back to you.

**Comment by dmurphy18** [comment]
@raddessi Any update on this with Arista.
@dractyl Sorry for talking so long to get back to you on this.  Are you still experiencing the problem, also what version of Cisco router are you using, recently got access to IOS-XR and IOS-XE.

Lastly presuming you are using Napalm, have you taken pre-cautions in config that Napalm documents about using config ?  https://napalm.readthedocs.io/en/latest/support/ios.html

**Comment by dractyl** [comment]
We stopped using salt for network tasks immediately after the incident (this is not the kind of excitement we can have in production) and the last of our Cisco devices are scheduled to be put to a well-earned death in the next couple of months.

So we’re no longer exposed to this bug for reasons both unfortunate and joyous, respectively.

On Jun 16, 2021, at 8:04, David Murphy ***@***.******@***.***>> wrote:



@raddessi<https://github.com/raddessi> Any update on this with Arista.
@dractyl<https://github.com/dractyl> Sorry for talking so long to get back to you on this. Are you still experiencing the problem, also what version of Cisco router are you using, recently got access to IOS-XR and IOS-XE.

Lastly presuming you are using Napalm, have you taken pre-cautions in config that Napalm documents about using config ? https://napalm.readthedocs.io/en/latest/support/ios.html

**Comment by raddessi** [comment]
Sorry, work has been busy. I can try to get some time for this soon, and yes I can open a new issue and link back here.

**Comment by raddessi** [comment]
Example of my failure was in https://github.com/saltstack/salt/issues/56289

**Comment by dmurphy18** [comment]
Closing this issue as PR #56299 appears to address the issue
