### ISSUE TITLE
integration.runners.test_state.OrchEventTest.test_jid_in_ret_event fails with AttributeError

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#53625]
The integration.runners.test_state.OrchEventTest.test_jid_in_ret_event test fail.
Similar errors appear for
integration.runners.test_state.OrchEventTest.test_orchestration_soft_kill
integration.runners.test_state.OrchEventTest.test_parallel_orchestrations

2019.2:
Pyhton 2:
https://jenkinsci.saltstack.com/job/2019.2/job/salt-amazon-1-py2/57/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-amazon-2-py2/58/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-6-py2/141/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2/142/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-debian-8-py2/142/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-debian-9-py2/142/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2/140/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Tornado/job/salt-centos-7-py2-tornado/134/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Transport/job/salt-centos-7-py2-transport/136/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Transport/job/salt-ubuntu-1604-py2-transport/139/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-centos-7-py2-m2crypto/142/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-centos-7-py2-pycryptodomex/146/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-ubuntu-1604-py2-m2crypto/142/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/

Python 3:
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-amazon-2-py3/55/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-centos-7-py3/138/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-debian-9-py3/142/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-fedora-29-py3/142/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-opensuse-15-py3/126/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-ubuntu-1604-py3/140/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-ubuntu-1804-py3/141/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Transport/job/salt-centos-7-py3-transport/134/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Transport/job/salt-ubuntu-1604-py3-transport/136/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-centos-7-py3-m2crypto/148/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-centos-7-py3-pycryptodomex/147/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-ubuntu-1604-py2-pycryptodomex/142/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-ubuntu-1604-py3-m2crypto/144/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-ubuntu-1604-py3-pycryptodomex/145/testReport/junit/integration.runners.test_state/OrchEventTest/test_jid_in_ret_event/

Error message looks like this:
```
Error Message
base_env
Stacktrace
AttributeError: base_env
```

**Comment by frogunder** [comment]
Also fails on Neon branch with timeout error.

salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-amazon-1-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py2, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-8-py3, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py2, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-debian-9-py3, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py2, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-fedora-29-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-opensuse-15-py3, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-pycryptodomex, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-m2crypto, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-pycryptodomex, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1604-py3-tcp, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2, salt-ubuntu-1804-py2
