### ISSUE TITLE
Tornado python3 tests timing out on all branches

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#53623]
Tornado py3 tests timing out on all branches 

LInks to 2091.2.1:

https://jenkinsci.saltstack.com/job/2019.2.1/view/Tornado/job/salt-centos-7-py3-tornado/138/consoleFull
https://jenkinsci.saltstack.com/job/2019.2.1/view/Tornado/job/salt-ubuntu-1604-py3-tornado/140/consoleFull

**Comment by KChandrashekhar** [comment]
Not a blocker for 2019.2.1
Tornado 5.0 will be supported for Neon release.
