### ISSUE TITLE
Multiple tests in unit.roster.test_ansible.AnsibleRosterTestCase fail with KeyError: u'ungrouped'

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#53635]
Failing tests are:
unit.roster.test_ansible.AnsibleRosterTestCase.test_ini
unit.roster.test_ansible.AnsibleRosterTestCase.test_script
unit.roster.test_ansible.AnsibleRosterTestCase.test_yml

2019.2:
https://jenkinsci.saltstack.com/job/2019.2/job/salt-amazon-2-py2/58/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-6-py2/141/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-centos-7-py2/142/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-debian-8-py2/142/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/job/salt-ubuntu-1604-py2/140/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-amazon-2-py3/57/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-centos-7-py3/140/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-debian-9-py3/144/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-fedora-29-py3/144/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-opensuse-15-py3/128/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-ubuntu-1604-py3/143/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Python3/job/salt-ubuntu-1804-py3/143/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Tornado/job/salt-centos-7-py2-tornado/134/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Transport/job/salt-centos-7-py2-transport/136/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Transport/job/salt-centos-7-py3-transport/134/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Transport/job/salt-ubuntu-1604-py2-transport/139/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Transport/job/salt-ubuntu-1604-py3-transport/136/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-centos-7-py2-m2crypto/142/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-centos-7-py2-pycryptodomex/146/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-centos-7-py3-m2crypto/148/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-centos-7-py3-pycryptodomex/147/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-ubuntu-1604-py2-m2crypto/142/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-ubuntu-1604-py2-pycryptodomex/142/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-ubuntu-1604-py3-m2crypto/144/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/
https://jenkinsci.saltstack.com/job/2019.2/view/Crypto/job/salt-ubuntu-1604-py3-pycryptodomex/145/testReport/junit/unit.roster.test_ansible/AnsibleRosterTestCase/test_ini/

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/roster/test_ansible.py", line 87, in test_ini
    ret = ansible.targets('*')
  File "/tmp/kitchen/testing/salt/roster/ansible.py", line 124, in targets
    hosts = [host for host in _get_hosts_from_group('all') if fnmatch.fnmatch(host, tgt)]
  File "/tmp/kitchen/testing/salt/roster/ansible.py", line 134, in _get_hosts_from_group
    hosts.extend(_get_hosts_from_group(child))
  File "/tmp/kitchen/testing/salt/roster/ansible.py", line 132, in _get_hosts_from_group
    hosts = [host for host in inventory[group].get('hosts', [])]
KeyError: u'ungrouped'
```

**Comment by twangboy** [comment]
Also failing on Neon
