### ISSUE TITLE
Test Suite Documentation Lacks Details

### ISSUE THREAD

**Issue by samilaine** [saltstack/salt#53633]
### Description of Issue

Following the instructions for setting up the SaltStack test suite from either the [documentation online](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html) or the file "HACKING.txt" in the SaltStack source tree doesn't lead to a fully functional testing environment.

### Setup

Not relevant to the issue at hand.

### Steps to Reproduce Issue

Prepare a test environment, as told in the documentation:

```
$ git clone https://github.com/saltstack/salt.git
$ cd salt
$ git checkout -b test develop
$ pip install -r requirements/dev_python27.txt
$ pip install -r requirements/zeromq.txt
```

Obviously `pip install`s did work. If they didn't in your computer when trying to verify this issue, then you're not reproducing the issue anymore. So, fix your `pip` before continuing to verify this issue.

At this point the documentation instructs that `./setyp.py test` should be run. However, the results are less than encouraging:

```
$ ./setup.py test
[ ... plenty of lines removed ... ]
copying salt/templates/virt/libvirt_pool.jinja -> build/lib/salt/templates/virt
copying salt/templates/virt/libvirt_domain.jinja -> build/lib/salt/templates/virt
running build_scripts
copying and adjusting scripts/salt-support -> build/scripts-2.7
changing mode of build/scripts-2.7/salt-support from 644 to 755
running test
Traceback (most recent call last):
  File "/Users/XXXXXXXX/salt/tests/runtests.py", line 62, in <module>
    from tests.integration import TestDaemon  # pylint: disable=W0403
  File "/Users/XXXXXXXX/salt/tests/integration/__init__.py", line 34, in <module>
    from tests.support.processes import *  # pylint: disable=wildcard-import
  File "/Users/XXXXXXXX/salt/tests/support/processes.py", line 18, in <module>
    from pytestsalt.utils import collect_child_processes, terminate_process, terminate_process_list  # pylint: disable=unused-import
ImportError: No module named pytestsalt.utils
```

### Versions Report

Not relevant to the issue at hand.

The error is reproducible using both Python 2.7.15 and Python 3.4.9.

**Comment by sagetherage** [comment]
@Akm0d looks like this ticket and the PR were opened on `develop`. Do you know if this was ported to `Master` by chance?

**Comment by samilaine** [comment]
I have no idea. The issue hardly seems worth pursuing now when Python 2.7 is mostly obsolete anyway.

I can't but point out how having this discussion in the first place tells something about the way PRs are handled. Or rather, not handled.

**Comment by sagetherage** [comment]
@Akm0d please follow up on the port to master, updated the labels so it will not stale-out again
