### ISSUE TITLE
Jinja renderer appears to strip more whitespaces than expected

### ISSUE THREAD

**Issue by yohonet** [saltstack/salt#53657]
### Description of Issue
Whitespace control in salt does not seem to follow what's documented in the jinja documentation. After a "-" at the end of a block, all whitespaces and newlines are removed until the next printable character. According to documentation, "the first newline after a template tag is removed automatically" but nothing more. The same appears to be true for a "-" at the beginning of a block, it strips all characters including the newline, not just "strip[ping] tabs and spaces from the beginning of a line to the start of a block", as written in the doc.

### Setup
Create the same file as in the jinja doc and add "-" at the beginning and the end of each block 
```
<div>
    {%- if True -%}
        yay
    {%- endif -%}
</div>
```

Then create a file.managed state, "template" being jinja and a "source" being this file.

### Steps to Reproduce Issue
* Apply the state you've just created
* The result according to documentation should be 
```
<div>
      yay
</div>
```
but it is
```<div>yay</div>```

### Versions Report

--------
Master:
--------

Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  2 2016, 04:20:16)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.3 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.3 Maipo

---------
Minion:
--------
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, May  3 2017, 07:55:04)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.4 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.4 Maipo

**Comment by rossengeorgiev** [comment]
Salt follows jinja2 default behaviour:

```python
In [1]: import jinja2

In [2]: tmpl = jinja2.Template("""
   ...: <div>
   ...:     {%- if True -%}
   ...:         yay
   ...:     {%- endif -%}
   ...: </div>
   ...: """)

In [3]: print(tmpl.render())

<div>yay</div>
```

The behaviour you expect is possible when certain configuration switched are turned on. See http://jinja.pocoo.org/docs/2.10/templates/#whitespace-control

**Comment by yohonet** [comment]
I'll indeed report this behaviour upstream, it's not linked to salt.
