### ISSUE TITLE
cp.push broken in modules and CLI for 2019.2.0

### ISSUE THREAD

**Issue by js-capra** [saltstack/salt#53683]
### Description of Issue
**Summary of questions:**
Can wild cards be used from CLI on the master to get minions to push files? example: *.xml
Am I doing something wrong from within the module?

This appears to be broken in 2019.2.0....

I can run it from the CLI of the Master server... but as a part of custom module it fails.

Yes - I have set file_recv: True and reset the server.

It seems to work from the CLI if I give it and exact file name... no wild cards.  But if executed from within a module I get:

The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1660, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/var/cache/salt/minion/extmods/modules/custom.py", line 525, in stageReports
        salt.modules.cp.push(targetLocationOfReport,upload_path=reportName)
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 807, in push
        auth = _auth()
      File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 40, in _auth
        if 'auth' not in __context__:
    NameError: global name '__context__' is not defined

This is frustrating.  Any help with wild card file names from CLI or more importantly from within a module would be greatly appreciated.  Thanks!

LOGS from Master Debug:

[DEBUG   ] Sending event: tag = salt/job/20190702164742017766/ret/sim2; data = {'fun_args': ['latest'], 'jid': '20190702164742017766', 'return': 'The minion function caused an exception: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 1660, in _thread_return
   return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
  File "/usr/lib/python2.7/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)\n  File "/var/cache/salt/minion/extmods/modules/custom.py", line 525, in stageReports
   salt.modules.cp.push(targetLocationOfReport,upload_path=reportName)
  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 807, in push
   **auth = _auth()\n  File "/usr/lib/python2.7/dist-packages/salt/modules/cp.py", line 40, in _auth
    if \'auth\' not in __context__:**
**NameError: global name \'__context__\' is not defined**
', 'retcode': 1, 'success': False, 'cmd': '_return', u'_stamp': '2019-07-02T16:47:42.249886', 'fun': 'custom.stageReports', 'id': 'sim2', 'out': 'nested'}
[ERROR   ] Received minion error from [sim1]: The minion function caused an exception

The command from within the module:
`salt.modules.cp.push(targetLocationOfReport,upload_path=reportName)`

If this is not the right place to discuss this please let me know.  Thanks!
The file is less than 100 Mb.  Its a very small text file.

Again, thank you for any help!

### Setup
Master and Minions are 2019.2.0.
Master is Ubuntu 2018 Server and Minions are on Debian.

### Steps to Reproduce Issue
Run `'sudo salt '*' cp.push '/path/to/xmls/*.xml'`
or
From inside a module
`salt.modules.cp.push(targetLocationOfReport,upload_path=reportName)`

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

**DIFFERENCES**
Master v Minion:
dateutil: 2.6.1 vs 2.5.3
gitdb: 2.0.3 vs not-installed
gitpython: 2.1.8 vs not-installed
Jinja2: 2.10 vs 2.9.4
Mako: 1.0.7 vs not-installed
msgpack-python: 0.5.6 vs not-installed
Python: 2.7.15+ (default, Nov 27 2018, 23:36:35) vs Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
python-gnupg: 0.4.1 vs not-installed
smmap: 2.0.3 vs not-installed
Tornado: 4.5.3 vs 4.4.3
ZMQ: 4.2.5 vs 4.2.1
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-54-generic
         system: Linux
        version: Ubuntu 18.04 bionic

Minions
sim2:
    2019.2.0
sim1:
    2019.2.0

**Comment by js-capra** [comment]
I see its been blocked and flagged as a question.  Though I did make my questions clear at the beginning of the write-up I do believe it is a bug.... cp.push is not working as documented.

**Comment by sjkummer** [comment]
For me cp.push_dir works - just cp.push is not working as expected.

**Comment by mattpascoe** [comment]
I just confirmed in my instance that cp.push does not work but cp.push_dir does work... Seems to me something is busted.

**Comment by js-capra** [comment]
Exactly my experience as well. Either the documentation isn’t correct or the feature is simply broken.

James Smith
Senior Security Engineer
720.360.6441

221 N LaSalle St #1325
Chicago, IL 60601
www.wcapra.com
________________________________

**Comment by js-capra** [comment]
Awesome. Can and admin remove my information above? Email auto reply just had some great information leakage.
________________________________
