### ISSUE TITLE
Fedora repo links are broken 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53686]
### Description of Issue
Fedora have changed how pkgdb is done
https://fedoraproject.org/wiki/Infrastructure/WhatHappenedToPkgdb 

Because of which the 'Browse repo' link in repo.saltstack.com#fedora which currently points to pkgdb isn't working 
https://admin.fedoraproject.org/pkgdb/

The above link needs to be updated to https://apps.fedoraproject.org/packages/salt 

### Setup
NA

### Steps to Reproduce Issue
NA

### Versions Report
NA

**Comment by bryceml** [comment]
@KChandrashekhar someone in the community slack said that
https://apps.fedoraproject.org/packages/salt-/
might be better to point to, what do you think?

**Comment by bryceml** [comment]
https://github.com/SS-priv/sse-docs/pull/300
https://github.com/saltstack/docs-repo-landing

**Comment by bryceml** [comment]
This is done.
