### ISSUE TITLE
win_drives.py uses String.uppercase when Salt-Minion-Py3 is installed 

### ISSUE THREAD

**Issue by chokkoretto** [saltstack/salt#53708]
### Description of Issue
Using Salt Master with this minion install Salt-Minion-2019.2.0-Py3-AMD64-Setup causes some warning when it runs.  It seems to complete fine however  

This file C:\salt\var\cache\salt\minion\extmods\grains\win_drives.py has string.uppercase which apparently doesn't work in python 3, but string.ascii_uppercase does.  I'm not sure if its an issue with my master - however there are no updates available when I run yum update.

### Setup
winFeatures/init.sls
------------------------------
install_SNMP-Service:
  win_servermanager.installed:
    - name: SNMP-Service

top.sls
------------------------------
base:
 '*':
  - winFeatures

### Steps to Reproduce Issue
I run on the minion machine: salt-call state.highstate

This error shows up before running the states, which seem to run fine.
[CRITICAL] Failed to load grains defined in grain file win_drives.get_harddrives in function <function get_harddrives at 0x000002B1ADC7CEA0>, error:
Traceback (most recent call last):
  File "C:\salt\bin\lib\site-packages\salt\loader.py", line 798, in grains
    ret = funcs[ key ](**kwargs)
  File "c:\salt\var\cache\salt\minion\extmods\grains\win_drives.py", line 7, in get_harddrives
    for letter in string.uppercase:
AttributeError: module 'string' has no attribute 'uppercase'

To remedy this, I changed the file
"c:\salt\var\cache\salt\minion\extmods\grains\win_drives.py"

Line 7 has 
for letter in string.uppercase:
Changed to 
for letter in string.ascii_uppercase:

and it seemed to be fine.  However editing this file manually on every isn't great, so I've gone back to using the Py2 version of salt minion.

### Versions Report
Salt Master
Installed Packages
salt.noarch                         2019.2.0-1.el7                   @saltstack-repo
salt-master.noarch                  2019.2.0-1.el7                   @saltstack-repo
salt-minion.noarch                  2019.2.0-1.el7                   @saltstack-repo
salt-ssh.noarch                     2019.2.0-1.el7                   @saltstack-repo

Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

Salt Minion
Windows Server 2016
Salt-Minion-2019.2.0-Py3-AMD64-Setup from https://docs.saltstack.com/en/latest/topics/installation/windows.html

**Comment by xeacott** [comment]
Hi @chokkoretto I read your ticket over just now and it appears you're using a file called win_drives.py yes? It doesn't appear that we have that file in our code base, which makes me believe it is your own custom file?

If that is the case, I don't believe there is anything inside of salt that needs to be fixed here. But yes 
 `string.ascii_uppercase` can be used on python2/3 whereas `string.Uppercase` requires a python2 system only.

**Comment by xeacott** [comment]
Closing this as I don't believe this is a salt related issue.
