### ISSUE TITLE
Minions not responding post master rebuild

### ISSUE THREAD

**Issue by nkrishnakishor** [saltstack/salt#53713]
### Description of Issue
Minions not responding post master rebuild with same IP address

### Setup
NA

### Steps to Reproduce Issue
salt windows-minion test.ping
[WARNING ] /usr/lib/python2.7/site-packages/salt/payload.py:149: DeprecationWarning: encoding is deprecated, Use raw=False instead.
  ret = msgpack.loads(msg, use_list=True, ext_hook=ext_type_decoder, encoding=encoding)

windows-minion:
    Minion did not return. [No response]
ERROR: Minions returned with non-zero exit code

### Versions Report
`salt --versions-report`
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 0.8.6
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 0.8.1
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.2.1511 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: Linux
        version: CentOS Linux 7.2.1511 Core

**Comment by Akm0d** [comment]
If the master was rebuilt then my first thought is that the keys it uses for authentication with the minions have changed.   What does `salt-key -l windows-minion` give you from the master?

**Comment by jheiselman** [comment]
We are experiencing similar issues. We realized that msgpack got upgraded somehow from 0.5.6 to 0.6.1. We downgraded it on our Salt master and, so far, our errors have all gone away. The DeprecationWarning is gone. We haven't experienced any issues with minion responses.

This change was just made today, so I can't say for certain that the issue is completely resolved, but you may try it yourself.

**Comment by nkrishnakishor** [comment]
i have modified the file content in ``` /usr/lib/python2.7/site-packages/salt/payload.py``` to raw=False and it worked out.
