### ISSUE TITLE
hgfs fileserver broken: mismatch between virtual name and fileserver_backend entry name

### ISSUE THREAD

**Issue by ptonelli** [saltstack/salt#53730]
### Description of Issue
the fileserver_backend can now accept either hg or hgfs, hg being converted to hgfs.

In the fileserver code, the virtualname is set as hg, and the load check is:

    if __virtualname__ not in __opts__['fileserver_backend']:
        return False

to fix virtualname must be changed from hg to hgfs

### Steps to Reproduce Issue
add hgfs backend, the backend is never loaded 

### Versions Report
salstack 2019.2 (broken from 2018.x I believe)

**Comment by cmcmarrow** [comment]
Thanks for bring this up @ptonelli. I agree that the virtual name should be 'hgfs'. But I don't believe it would be a good idea to change the virtual name now. The reason why is it could break other peoples code. Forgive me if I failed to understand you. @ptonelli are you trying to say the this module is failing to load or another modules it not loading?

**Comment by ptonelli** [comment]
in 2019.2 this module is broken, it does not load for the first configuration option:

```
fileserver_backend:
  - hgfs
```
and it does not load if you put the code :
```
fileserver_backend:
  - hg
```

doing the requested change fixes both configurations.
