### ISSUE TITLE
http.wait_for_successful_query module doesn't support 'request_interval'

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#53738]
### Description of Issue
There is a slight difference between `http.wait_for_successful_query` state and module.
State does support `request_interval` kwargs while module doesn't. 

Running this module without this feature creates a http connections flood since it trying to repeat http connection as soon as possible.

Why don't I just use a state? Well, first of all I think it's inconsistency which needs to be fixed. Second, I'm trying to combine `loop.until` with `http.wait_for_successful_query` to be able to parse the serialized output of http endpoints since `match` feature of http utils is not good for that, and I get a http connection flood.

### Steps to Reproduce Issue
You can run it like:
`salt-call http.wait_for_successful_query http://127.0.0.1:7777 wait_for=10 -l debug` 
And just check how many http connection will be executed.

While using it as a state you can throttle this by `request_interval` kwargs.

### Versions Report
I'm using 2019.02 but all version are affected.

**Comment by cmcmarrow** [comment]
Thanks for the Featrue/Change request @Oloremo.

**Comment by Oloremo** [comment]
Feature merged!
