### ISSUE TITLE
`virt.volume_infos` should not fail where there is no VM

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#53754]
### Description of Issue

When calling `virt.volume_infos` on a hypervisor that has no VM defined an error is thrown:

    A command in 'virt.volume_infos' had a problem: No virtual machines found.

Instead the list of pools and volumes should be returned.

### Steps to Reproduce Issue

* Prepare a KVM or Xen minion with some virtual storage pools and volumes inside them, but no virtual machine defined.
* from the master run `salt '*kvm*' virt.volume_infos`

Actual result:

```
test-min-kvm.tf.local:
    ERROR: No virtual machines found.
ERROR: Minions returned with non-zero exit code
```

Expected result: the list of pools and volumes with their infos. Of course the `used_by` property will contain an empty value since no VM is defined. 

### Versions Report

All neon

**Comment by cmcmarrow** [comment]
I agree!

**Comment by cbosdo** [comment]
fixed now
