### ISSUE TITLE
setUpClass (unit.modules.test_zcbuildout.BuildoutOnlineTestCase)

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#53778]
Neon fails on `salt-amazon-1-py2, salt-debian-9-py2, salt-debian-9-py3, salt-fedora-29-py2, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py3-tcp, salt-windows-2016-py2, salt-windows-2019-py2`

Error:
```
Command '[u'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\kitchen\\testing\\.nox\\runtests-parametrized-2-7-coverage-true-crypto-none-transport-zeromq\\Scripts\\virtualenv.EXE', u'--no-site-packages', u'c:\\users\\admini~1\\appdata\\local\\temp\\salt-tests-tmpdir\\tmpkz7deo\\psetuptools']' returned non-zero exit status 1
```

**Comment by DmitryKuzmenko** [comment]
The same is in 2018.3 builds now:
https://jenkinsci.saltstack.com/job/2018.3/job/salt-windows-2016-py2/134/testReport/junit/setUpClass%20(unit.modules/test_zcbuildout/BuildoutOnlineTestCase_/
https://jenkinsci.saltstack.com/job/2018.3/job/salt-windows-2016-py2/134/testReport/junit/setUpClass%20(unit.states/test_zcbuildout/BuildoutTestCase_/
https://jenkinsci.saltstack.com/job/2018.3/job/salt-windows-2019-py2/133/testReport/junit/setUpClass%20(unit.modules/test_zcbuildout/BuildoutOnlineTestCase_/
https://jenkinsci.saltstack.com/job/2018.3/job/salt-windows-2019-py2/133/testReport/junit/setUpClass%20(unit.modules/test_zcbuildout/BuildoutTestCase_/
https://jenkinsci.saltstack.com/job/2018.3/job/salt-windows-2019-py2/133/testReport/junit/setUpClass%20(unit.states/test_zcbuildout/BuildoutTestCase_/
