### ISSUE TITLE
unit.test_auth.MasterACLTestCase

### ISSUE THREAD

**Issue by twangboy** [saltstack/salt#53788]
Neon fails on `salt-fedora-29-py2, salt-ubuntu-1604-py2-tcp, salt-ubuntu-1604-py3-tcp`
Error:
```
'NoneType' object is not subscriptable
```

**Comment by Akm0d** [comment]
All these tests have the same failure:

unit.test_auth.MasterACLTestCase.test_args_empty_spec
--
unit.test_auth.MasterACLTestCase.test_args_kwargs_match
unit.test_auth.MasterACLTestCase.test_args_mixed_match
unit.test_auth.MasterACLTestCase.test_args_more_args
unit.test_auth.MasterACLTestCase.test_args_simple_match
unit.test_auth.MasterACLTestCase.test_master_publish_name
unit.test_minion.MinionTestCase.test_minion_manage_schedule
