### ISSUE TITLE
package installations should create the /srv/salt directory if it doesn't exist

### ISSUE THREAD

**Issue by karlp** [saltstack/salt#5384]
Definitely, installing a packaged version of salt stack should not trample an existing /srv/salt tree, but if the directory doesn't even exist, it should be created with package appropriate permissions and ownership, and optionally contain a top.sls.example file (for instance)

18:48 < Corey> karlp: File an issue plz. :-)

**Comment by MTecknology** [comment]
I really don't think any package should ever create anything underneath of /srv, not even an empty directory structure. In this case, there's no parent directory for salt stuff either.

Also, it violates Debian policy. https://lintian.debian.org/tags/dir-or-file-in-srv.html

**Comment by karlp** [comment]
@MTecknology that's fair, but is sort of sideways.  Should salt use /srv as the default? :)

**Comment by MTecknology** [comment]
That one is a bit more iffy. I don't disagree with the defaults. In fact,
before I knew those were the defaults, I was already choosing nearly the same
locations. (moved to git now so it doesn't matter)

I actually think how it behaves now is best. I have a long explanation why, but
it'll take a while to type out and I'm lazy.

**Comment by UtahDave** [comment]
We'll do the appropriate thing for each distro.
