### ISSUE TITLE
cmd.retcode in conditionals produces errors if the retcode isn't 0

### ISSUE THREAD

**Issue by ConstipatedNinja** [saltstack/salt#53859]
### Description of Issue
If `cmd.retcode` is used in a conditional and the return code collected is non-zero, the subsequent debug logs show an [ERROR] line for it.

### Setup
Code contained in reproduction section.

### Steps to Reproduce Issue
Here's some simple example code:
```
{%- if 0 == salt['cmd.retcode']('aa-status | grep -q "/usr/sbin/sssd"') %}
disable sssd in apparmor:
  cmd.run:
    - name: aa-disable /usr/sbin/sssd
{%- endif %}
```
and if the `grep -q` doesn't match any lines then it will return a status of 1, allowing the cmd.run to be skipped. However, in returning with a status of 1 you'll get
```
[ERROR   ] Command '[u'aa-status', u'|', u'grep', u'-q', u'/usr/sbin/sssd']' failed with return code: 1
```
showing up. This doesn't seem like an error to me, and it continually confuses management into thinking there's errors in the code where there aren't. 

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
 
The minion is running the same version of salt.

**Comment by waynew** [comment]
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html

> **ignore_retcode** (bool) -- If the exit code of the command is nonzero, this is treated as an error condition, and the output from the command will be logged to the minion log. However, there are some cases where programs use the return code for signaling and a nonzero exit code doesn't necessarily mean failure. Pass this argument as True to skip logging the output if the command has a nonzero exit code.

Is that what you're looking for?

**Comment by waynew** [comment]
I'm going to go ahead and close this - if you feel like there's an unanswered question please go ahead and comment and we can re-open!
