### ISSUE TITLE
Fix for container detection on virtual machines

### ISSUE THREAD

**Issue by nkukard** [saltstack/salt#53868]
This is basically a one liner fix for detection of LXC on VirtualBox and other virtual machines.

The PR is here #53849

The only line being added is...
> if 'virtual' not in grains:

## Current Behavior

When running an LXC container on a VirtualBox virtual machine the following is observed...

>     $ salt-call grains.items
>     ...
>     virtual:
>     VirtualBox
>     ...

## New Behavior

After applying the patch, the following is observed...

>     $ salt-call grains.items
>     ...
>     virtual:
>     LXC
>     ...

**Comment by waynew** [comment]
@xeacott I've assigned this to you since you already had some communication on the PR.
