### ISSUE TITLE
Investigate kitchen failure that looks like ami (or other) limits

### ISSUE THREAD

**Issue by smokeytheblair** [saltstack/salt#53871]
### Description of Issue
16:13:26  -----> Creating <py2-debian-8>...
16:13:29  >>>>>> ------Exception-------
16:13:29  >>>>>> Class: Kitchen::ActionFailed
16:13:29  >>>>>> Message: 1 actions failed.
16:13:29  >>>>>>     Failed to complete #create action: [Request limit exceeded.] on py2-debian-8
16:13:29  >>>>>> ----------------------
16:13:29  >>>>>> Please see .kitchen/logs/kitchen.log for more details
16:13:29  >>>>>> Also try running `kitchen diagnose --all` for configuration

### Setup
see this https://jenkinsci.saltstack.com/job/pr-kitchen-debian8-py2/job/PR-53750/2/

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by smokeytheblair** [comment]
from @dwoz:

from kitchen-ec2-3.0.1/lib/kitchen/driver/ec2.rb
```572       def with_request_limit_backoff(state)
573         retries = 0
574         begin
575           yield
576         rescue ::Aws::EC2::Errors::RequestLimitExceeded, ::Aws::Waiters::Errors::UnexpectedError => e
577           raise unless retries < 5 && e.message.include?("Request limit exceeded")
578           retries += 1
579           info("Request limit exceeded for instance <#{state[:server_id]}>." \
580                " Trying again in #{retries**2} seconds.")
581           sleep(retries**2)
582           retry
583         end
584       end```

**Comment by bryceml** [comment]
https://www.hadoopandcloud.com/aws/ec2-api-requestlimitexceeded-error/

**Comment by s0undt3ch** [comment]
That doesn't resemble the error we get if we maxed out the 5k running instances....

**Comment by felippeb** [comment]
This issue has not been seen recently. Assuming this is resolved. going to move to completed.
