### ISSUE TITLE
Checkmarx vulnerability scan 

### ISSUE THREAD

**Issue by sumeetisp** [saltstack/salt#53881]
### Description of Issue
We found an issue in checkmarx vulnerability scan. Following are the details,
Method open_resource at line 78 of
salt/pkg/windows/buildenv/bin/Lib/site-packages/pytz/__init__.py gets
dynamic data from the get element. This element’s value then flows through the code and is eventually used in a file path for local disk access in open_resource at line 78 of
salt/pkg/windows/buildenv/bin/Lib/site-packages/pytz/__init__.py. This
may cause a Path Traversal vulnerability.

Please may i know if this will be fixed in future releases.
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by waynew** [comment]
This sounds like it's an issue found in `pytz`, it's not clear from your report how or if salt could be affected, or which versions of pytz are (potentially) vulnerable. Pytz bug tracker is found https://code.launchpad.net/pytz

Also FWIW this comes from `os.environ`. If someone can provide arbitrary environment variables then you're already pwned.
