### ISSUE TITLE
zmq_filtering problems on Windows Minions later than 2016.11.10

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#53885]
### Description of Issue

We rely on zmq_filtering, which enables [publisher side filtering](https://docs.saltstack.com/en/latest/topics/transports/zeromq.html).

We intend to upgrade our salt-minions to a recent version. Therefore we tested “Can the master contact the minion with zmq_filtering?”:

"minion_start delay" means the time between starting the salt-minion service and the minion_start event showing up in the event bus (of an salt-master having only one minion).

We used two servers:
 - WSL = Windows Server for Linux Debian.
 - CentOS7

 Minion-version                            | Does `test.ping` work in both directions? (master-version: minion_start delay)
 -------------------------------------|--------------------------------
 3001 Py3 | Yes (2019.2.5 Py2 CentOS8)
 v3000.1-344-Py3-64 | Yes (WSL2: 5s)
 3000.1-Py3-64 | Yes (3000.2Py3 CentOS7: 60; 2018.3.4 Py2 CentOS7: NO; WSL2: 5s )
 2019.2.3-Py3-D64 | Yes (WSL: 5s)
 2018.3 (Git head 1255) Py3 64   |   Yes (2018.3.4 Py2 CentOS: 6m)
 2018.3.4-Py3-D64  |   No   
 2018.3.4-Py2-64 | Yes (2018.3.4 Py2 CentOS: 6m)
 2018.3.3-Py2-64 | Yes (2018.3.4 Py2 CentOS: 6m)
 2017.7.8-Py3-32  | No (Exception below)
 2016.11.10-32  | Yes (no delay)
 2016.11.3-64 |  Yes  (no delay)

### Setup

To enable/disable publisher side filtering we used the following 6 steps:
1. Stop salt-master service
2. Stop salt-minion service
3. Add/remove the setting “zmq_filtering: True” on the master
4. Add/remove the setting “zmq_filtering: True” on the minion
5. Start salt-master service
6. Start salt-minion service

We used the following two commands to test “can the server contact the minion?”:
1. salt minion1 test.version
2. salt-run manage.status

Success of "salt-run manage.status" is given when the minion status is “up”.

## Notes

All above minions can contact the master without zmq_filtering.

All above minions can contact the master with zmq_filtering, except 2017.7.8-Py3-x86 (see below).

We noted that after disabling publisher side filtering, it took several minutes before the master could contact the minion. 

### Salt-Minion-2017.7.8-Py3-x86-Setup.exe

Salt-Minion-2017.7.8-Py3-x86-Setup.exe and “publisher side filtering” and “\salt\salt-call -l debug test.version” resulted in an Exception. Reproduced in a second installation.

```

TypeError: unicode not allowed, use setsockopt_string
Traceback (most recent call last):
..snip..
  File "C:\salt\bin\lib\site-packages\salt\minion.py", line 620, in eval_master
    pub_channel = salt.transport.client.AsyncPubChannel.factory(self.opts, **factory_kwargs)
  File "C:\salt\bin\lib\site-packages\salt\transport\client.py", line 162, in factory
    return salt.transport.zeromq.AsyncZeroMQPubChannel(opts, **kwargs)
  File "C:\salt\bin\lib\site-packages\salt\transport\zeromq.py", line 340, in __init__
    self._socket.setsockopt(zmq.SUBSCRIBE, self.hexid)
  File "zmq\backend\cython\socket.pyx", line 374, in zmq.backend.cython.socket.Socket.set (zmq\backend\cython\socket.c:4610)
TypeError: unicode not allowed, use setsockopt_string

```

#### Second note on Salt-Minion-2017.7.8-Py3-x86-Setup.exe

About 30 minutes after the TypeError, a python.exe process with an empty command line (command line is an optional column of Windows Task-Manager/Processes) uses 28% CPU, resulting in 50% overall CPU consumption and a fan running at maximum. 
	

### Versions Report

The salt-master has default configuration. 

The only change to the configuration is zmq_filtering.

```

salt-run --versions-report
Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core


```

**Comment by markuskramerIgitt** [comment]
With Salt-Minion-2018.3.3-Py2-AMD64-Setup.exe and zmq_filtering, the master can contact the minion. 

The issue seems to be the combination of zmq_filtering and Python3.

**Comment by markuskramerIgitt** [comment]
With Salt-Minion-2018.3.4-Py2-AMD64-Setup.exe and zmq_filtering, the master can contact the minion, but not in the first 6 minutes after minion start.

**Comment by markuskramerIgitt** [comment]
@twangboy, can you reproduce that the 2018.3.4-Py2 minion sends a `minion_start` only after ~6 minutes?

**Comment by twangboy** [comment]
I don't understand what you mean by minion_start...

I can confirm that on 2018.3.4 PY3 I get the following on the minion when issuing commands to the minion with zmq_filtering on:
```
[DEBUG   ] Publish received for not this minion: 654946cd65a199d1f3c2aa5d4d5e68a4f1f4b5e9
```

This doesn't appear to be a problem on the head of 2018.3, so it looks like it's been fixed there.

We're probably not going to do another release on 2017.7, unless it's to address a CVE.

**Comment by markuskramerIgitt** [comment]
@twangboy, thank you 

This is my test scenario with the 2018.3.4-Py2 minion:
 - The salt-minion service does not run
 - On the master I started `salt-run state.event pretty=True` (Only one minion on the master)

When I do `net start salt-minion`, I see the `minion_start` event on the master after 6 (+/- 10 seconds) minutes. I see the `minion_start` event of an 2016.11.3 minion after 1-3 seconds. 
The 2018.3.4-Py2 minion "does nothing for 6 minutes" when asked to start.

This 6 minute delay is the issue.
Can you reproduce?

That's good news of the 2018.3-Py head, is there is an integration test for zmq_filtering?

I noticed [Py3 performance problems](https://github.com/saltstack/salt/issues/53890) and therefore focus on Python2.

**Comment by markuskramerIgitt** [comment]
@twangboy 
I just built Minion Python3 `2018.3.0-1255-g4e500bf` from the Git HEAD.
1. The server can contact the minion (with zmq_filtering)
2. Performance improved: One new python.exe process above 20% runs for 8 seconds. This is still not as efficient as the 3 seconds of the 2016.11 minion.
3. The minion still has a delay of 6 minutes between start of the service and minion_start event arrives at the master  event bus. 


I edited the table above and the [Performance issue]( https://github.com/saltstack/salt/issues/53890)

**Comment by twangboy** [comment]
I just tested 2018.3.4 Py2 and Py3. They both connect with my master in less than 5 seconds with `zmq_filtering: True`.

Could you post sanitized master and minion configs? Perhaps there is a conflict there.

**Comment by markuskramerIgitt** [comment]
@twangboy, excellent news, I will repeat the tests and post the config here.

**Comment by markuskramerIgitt** [comment]
For ease of lookup:  `test_publish_to_pubserv_ipc()` in `tests/unit/transport/test_zeromq.py` is  the currently only unit test that sets `zmq_filtering` is skiped on Windows because it involves inter process communication (ipc), which is apparently not supported on Windows:  
[permalink](https://github.com/saltstack/salt/blob/5238b903a6011653f6b4ff6c93ea5c358c7afd58/tests/unit/transport/test_zeromq.py#L470)

**Comment by markuskramerIgitt** [comment]
@twangboy, I believe the configuration of the server to be, as described above, default except zmq_filtering. I will double check, possibly tomorrow. Curious....

**Comment by markuskramerIgitt** [comment]
master running in a local VM
 - 2019.2.1 Py2  
 - default configuration  except zmq_filtering: True
 - on WSL. release: 4.4.0-18362-Microsoft, version: debian 10.1

Salt-Minion-2018.3.4-Py2-AMD64-Setup.exe connects in less than 5 seconds.

Salt-Minion-2019.2.1-Py3-AMD64-Setup.exe connects in less than 5 seconds.

This is good!

I will test against a remote master.

**Comment by markuskramerIgitt** [comment]
Unfortunately, with a remote master (2018.3.4 Py2 as above) the issue is reproducible:
 - Salt-Minion-2019.2.1-Py3-AMD64-Setup.exe connects only after 5 minutes.

This means: I start the minion service, and only 5 minutes later the master receives the `minion_start` event. Tested twice.

master  complete configuration: 
    zmq_filtering: True

Master has 2 minions and service has 1 drop-in:

    /etc/systemd/system/salt-master.service.d/filelimit.conf:
        LimitNOFILE=887221


minion  complete configuration: 

    zmq_filtering: True
    master:********

minion log file empty.

What else can I look for?

**Comment by twangboy** [comment]
I wonder if it has anything to do with the master in WSL....

**Comment by markuskramerIgitt** [comment]
8 day ago, October 22, when I tested against the "remote master" on centos 7.6,  WSL was not running.

So WSL has nothing to do with this

**Comment by markuskramerIgitt** [comment]
Not stale

**Comment by markuskramerIgitt** [comment]
First test of Salt-Minion-2019.2.3-Py3-AMD64-Setup.exe showed no minion_start delay.

**Comment by markuskramerIgitt** [comment]
Update: 

 Installer                            | Successsful communication
 -------------------------------------|--------------------------------
Salt-Minion-v3000.1-344-ge8c1ab2877-Py3-64bit.msi | Yes (no minion_start delay on WSL2)
Salt-Minion-3000.1-Py3-64bit.msi | Yes (no minion_start delay on WSL2)

Need to verify on master on remote RedHat, hopefully this times better results than 2018.3.4 Py2.

**Comment by markuskramerIgitt** [comment]
Salt master 2018.3.4 (Py2) does not communicate with Salt-Minion-3000.1-Py3-64bit.msi

**Comment by markuskramerIgitt** [comment]
Salt master 3000.1 (Py3) does communicate with Salt-Minion-3000.1-Py3-64bit.ms creating 60 seconds CPU load for test.version

**Comment by markuskramerIgitt** [comment]
Python 2 salt master 2019.2.5 does communicate with Python 3 Salt-Minion-3001, load is OK

**Comment by twangboy** [comment]
@markuskramerIgitt So, is the issue resolved in 3001?

**Comment by markuskramerIgitt** [comment]
I am testing

**Comment by markuskramerIgitt** [comment]
@twangboy  zmq_filtering between a Python 3 Salt-Minion-3001 patched with https://github.com/saltstack/salt/pull/58008 and a Py2  2019.2.5 master works.

I regard the issue as resolved.
