### ISSUE TITLE
default salt cli command does not work as intended

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#53887]
### issue
Default docs shows an example command for `slsutil.renderer`
```
salt \* slsutil.renderer salt://examplefile.jinja 'jinja'
```
This command listed in the [docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.slsutil.html#salt.modules.slsutil.renderer) is suppose to override the standard 'jinja|yaml' with just 'jinja' just like if the file had a `#!jinja` tag at the top of the file.

**Comment by max-arnold** [comment]
The docs are probably outdated. The working command should look like this:

```
salt \* slsutil.renderer salt://examplefile.jinja default_renderer=jinja
```

You can fix the docs by submitting a PR against the oldest supported branch (I guess that would be 2017.7 or 2018.3)

**Comment by alan-cugler** [comment]
please add labels for documentation bug so that it wont be closed til done.

**Comment by alan-cugler** [comment]
on to do list still
