### ISSUE TITLE
Collection of Windows CPU consumption of a simple command for several salt-minions

### ISSUE THREAD

**Issue by marbx** [saltstack/salt#53890]
### Description of Issue

We compared Windows CPU consumption of several salt-minions with 2016.11.3 (Python 2) and noted a very strong (up to 10-fold) performance detoriation for Python3.

This is to publically collect Windows CPU consumption of several salt-minions.

### Test  command

The test command `test.version` is intentionally simple 

### Test procedure

To observe CPU, open Windows Task Manager, selected Details, sort by Name.  

 Installer ______________________________ | Observations of `test.version` in the Windows Task Manager
 ---------------------|---------------
3000.1-Py3-64bit   | One python.exe process above 25% runs for 60 seconds, a second python.exe process above 10% runs for 60 seconds.
3000-Py3-64bit.msi   | One python.exe process above 20% runs for 4 seconds, a second python.exe process is quiet. Fan starts.
 2018.3 Git 1255 Py3 AMD64  | One python.exe process above 20% runs for 8 seconds. (zmq_filtering)
 2018.3.4-Py3-AMD64 |	 Two python.exe processes above 20%, each, run for 15 seconds at the same time, resulting in a combined CPU consumption of 50% for 15 seconds. (zmq_filtering: False)
2018.3.4-Py2-AMD64  | As 2016.11.3-AMD64
 2018.3.3-Py2-AMD64  | As 2016.11.3-AMD64
 2017.7.8-Py3-x86 |	 One python.exe processe above 20% runs for 6 seconds, after the salt-master got the return, a second python.exe processe above 20% runs for another 6 seconds, sometimes a third python.exe above 20% runs for another 4 seconds. (zmq_filtering: False)
 2016.11.3-AMD64 | One python.exe process above 20% runs for 3 seconds. (any zmq_filtering)

**Comment by markuskramerIgitt** [comment]
Related https://github.com/saltstack/salt/issues/42790

**Comment by waynew** [comment]
Note that 2016.11.3 is no longer officially supported, though I'm unsure if more modern versions of Salt have improved the underlying issue - I'm not aware of any efforts in that area, anyway.

**Comment by cmcmarrow** [comment]
Salt has improved the way windows does multiprocessing in the later versions of salt. As of CPU consumption I do not know. I do now when salt needs a new processes that processes will start a lot faster than older versions like 2016. How did you test this? What states or modules did you run?

**Comment by markuskramerIgitt** [comment]
@waynew , the more modern Salter versions with Python 3 have a much worser performance. I hope this issue helps to depict the importance for an effort to understand the underlying issues.

**Comment by markuskramerIgitt** [comment]
@cmcmarrow, I see no improvement of later versions of salt. 
If processes start faster, I do not notice. I remember a comment in another issue, that multiprocessing is used in a very resource demanding way.
This issue is intended to document the very noticeable deterioration of processes count, duration and CPU consumption. 

To test I counted seconds in Windows Task Manager. The test function is just `test.version`. I will add captions to the description to make that clearer.

**Comment by markuskramerIgitt** [comment]
Updated for version 3000

**Comment by markuskramerIgitt** [comment]
Updated for version 3000.1

**Comment by markuskramerIgitt** [comment]
### test.ping from master to minion

Who, master + minion = seconds of CPU on minion

Markus,  3000.2P3 + 3000.1Py3 = 40-60 seconds
Markus,    2019.2Py2 + 2016.11.3Py2 = 8 seconds
Twangboy, 3000.2P3 + 3000.1Py3 = 10 seconds

**Comment by marbx** [comment]
Since `multithreading: False` improvements, no longer collected
