### ISSUE TITLE
Pipeline destroy function not working 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53907]
### Description of Issue
Some of the older builds VMs isn't getting cleaned up. 

### Setup
NA

### Steps to Reproduce Issue
NA

### Versions Report
NA

**Comment by s0undt3ch** [comment]
To clarify. This was happening on non pipeline jobs.
We're waiting a couple of days to see if the same behavior is seen on the new pipeline jobs.

**Comment by s0undt3ch** [comment]
This is solved.
