### ISSUE TITLE
Code coverage failure on Amazon Linux 2 Py2 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53905]
### Description of Issue
Excerpt from below test failure 
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-2-py2/70/console 

Command coverage run tests/runtests.py --tests-logfile=/tmp/kitchen/testing/artifacts/logs/runtests.log --transport=zeromq --output-columns=120 --sysinfo --xml=/tmp/kitchen/testing/artifacts/xml-unittests-output -v --run-destructive --ssh-tests failed with exit code -9

### Setup
NA

### Steps to Reproduce Issue
NA

### Versions Report
2019.2.1

**Comment by waynew** [comment]
As far as I can tell, (and the build artifact just got discarded), this was actually just an older commit being built - we put in a fix that shouldn't see this problem anymore.

**Comment by waynew** [comment]
i.e. it built this:
```
│[2019-07-18T12:15:22.862Z] Checking out Revision 61e9efd7e0dbd5c122c363cd191037219027a2c8 (origin/2019.2.1)                                                                                       │
│[2019-07-18T12:15:23.578Z] Commit message: "Merge pull request #53873 from bryceml/2019.2.1-increase-sleep"                                                                                       │
│[2019-07-18T12:15:22.858Z]  > git rev-parse origin/2019.2.1^{commit} # timeout=10                                                                                                                 │
│[2019-07-18T12:15:22.865Z]  > git config core.sparsecheckout # timeout=10                                                                                                                         │
│[2019-07-18T12:15:22.871Z]  > git checkout -f 61e9efd7e0dbd5c122c363cd191037219027a2c8                                                                                                            │
│[2019-07-18T12:15:23.623Z]  > git rev-list --no-walk 61e9efd7e0dbd5c122c363cd191037219027a2c8 # timeout=10
```
But that was two merges before https://github.com/saltstack/salt/commit/22b7b1a9ef8a19f2a520c3d90778f9966de1657a.
