### ISSUE TITLE
SSH connection errors on CentOS 7

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53906]
### Description of Issue
Check 
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-7-py2/72/console 

### Setup
NA

### Steps to Reproduce Issue
NA

### Versions Report
2019.2.1 release branch

**Comment by KChandrashekhar** [comment]
Waiting for the metrics data to do RCA on this

**Comment by bryceml** [comment]
This can probably be closed since we determined it was dhclient not renewing the dhcp lease that was causing the majority of the ssh timeouts.
