### ISSUE TITLE
salt-run saltutil.sync_all doesn't sync roster modules

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#53914]
### Description of Issue

The `salt-run saltutil.sync_all` command doesn't sync roster modules, although `saltutil.sync_roster` function exists in the same runner.

https://github.com/saltstack/salt/blob/2017.7/salt/runners/saltutil.py#L39-L61

### Versions Report

All versions are affected, starting with 2017.7

**Comment by dwoz** [comment]
@max-arnold Thank you for reporting this!

**Comment by max-arnold** [comment]
Still valid
