### ISSUE TITLE
Salt 2019.2.1 Ubuntu py3 18.04 test failures 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53930]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-ubuntu-1804-py3/75/ 

20 test cases failed 
integration.cli.test_batch.BatchTest.test_batch_exit_code
integration.cli.test_batch.BatchTest.test_batch_run
integration.cli.test_batch.BatchTest.test_batch_run_grains_targeting
integration.cli.test_batch.BatchTest.test_batch_run_number
integration.cli.test_grains.GrainsTargetingTest.test_grains_targeting_minion_id_running
integration.cli.test_grains.GrainsTargetingTest.test_grains_targeting_os_running
integration.client.test_kwarg.StdTest.test_cmd_arg_kwarg_parsing
integration.client.test_kwarg.StdTest.test_full_return_kwarg
integration.client.test_kwarg.StdTest.test_full_returns
integration.client.test_kwarg.StdTest.test_kwarg_type
integration.client.test_standard.StdTest.test_cli
integration.client.test_standard.StdTest.test_full_returns
integration.client.test_standard.StdTest.test_missing_minion_list
integration.client.test_standard.StdTest.test_missing_minion_nodegroup
integration.client.test_syndic.TestSyndic.test_ping
integration.client.test_syndic.TestSyndic.test_fib
integration.doc.test_man.ManTest.test_man
integration.netapi.rest_tornado.test_app.TestSaltAPIHandler.test_simple_local_runner_post
integration.netapi.test_client.NetapiClientTest.test_local
integration.netapi.test_client.NetapiClientTest.test_local_batch

**Comment by dmurphy18** [comment]
Subsequent rebuilds work fine.  Running locally with extra debug information and nothing to report

**Comment by dmurphy18** [comment]
Check for infrastructure failures such as a minion or master, for example:
 25  * [0;1;32mStarting salt-master ... STARTED!
 26 [2019-08-03T18:18:17.236Z]        [0;0m * [0;1;33mStarting salt-minion ... [0;0m
 27 
 28  * [0;1;32mStarting salt-minion ... STARTED!
 29 [2019-08-03T18:24:26.616Z]        [0;0m * [0;1;33mStarting sub salt-minion ... [0;0m
 30 
 31  * [0;1;31mStarting sub salt-minion ... _**FAILED!**_
 32 [2019-08-03T18:24:30.245Z]        [0;0m * [0;1;33mStarting syndic salt-master ... [0;0m
 33 
 34  * [0;1;32mStarting syndic salt-master ... STARTED!
 35 [2019-08-03T18:24:30.245Z]        [0;0m * [0;1;33mStarting salt-syndic ... [0;0m

Slows down testing such that around the timeout of 6 hours, the above tests get killed and the tests stop.
