### ISSUE TITLE
Neon Py3 centos transport test failures 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53949]
### Description of Issue
https://jenkinsci.saltstack.com/job/neon/view/Transport/job/salt-centos-7-py3-tcp/72/console

**Comment by sagetherage** [comment]
I am going to close this ticket since it was for Neon and there are still failures on Py3 for Centos but that is being worked in a different ticket - I believe, re-open if that is incorrect @dwoz
