### ISSUE TITLE
add more explicit labels for documentation

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#53944]
### Discussion
Currently, we have a `documentation` tag.
I would like to replace this tag with several more explicit tags listed below in the 'examples' section.

### Reasoning
Issues are extremely useful as an archive to look through when a user needs further material for the problem they are grappling with. Extended doc tags would expand the use of these closed issues in the future. As well as communicate better what people are asking for in these new issues related to docs.

### Examples:
- Someone is asking a question/clarification on documentation:
  + `docs-question` or `docs-clarification`
- This documentation page has an error or deadlink.
  + `docs-correction`
- This documentation is becoming irrelevant because of salt development but shouldn't be deleted yet.
  + `docs-deprecated`
- The documentation is confusing and not easily understood. This is often a result of the "cant see the forest through the trees" problem a lot of veteran salt contributors suffer from.
  + `docs-unclear` or `docs-convoluted` or `docs-rework`
- This is for a new documentation page.
  + `docs-expansion` or `docs-request`
- This once small documentation page needs to be fleshed out into several pages.
  + `docs-split` or `docs-fork`
- A discussion is needed to determine if documentation still has value.
  + `docs-obsolete` or `docs-demolition` or `docs-foreclosed`

### Misc
- I can give several more benefits for the label expansion I am requesting if needed.
- I care about what problem the tags are communicating more than what they are called.
- The `question` tag is different than the `docs-question` tag. One is a clarification on salt behavior, and the later is concerned with how the behavior is described in documentation.
- Issues with documentation suggestions and changes should be spinning out of most regular issues that are on salt behavior and "can I do this?" questions.

**Comment by cachedout** [comment]
Historically, the problem has been much more finding people to work on documentation than a lack of organization around issues but if re-organizing the issues are a step toward solving that problem, I am all for it.

**Comment by dwoz** [comment]
@saltstack/team-core @cachedout Does this deserve a SEP?

**Comment by alan-cugler** [comment]
I am writing one.

**Comment by alan-cugler** [comment]
This will be brought up in the new docs working group

**Comment by sagetherage** [comment]
@alan-cugler I will self assign and look at updating labels for docs in the very near future.

**Comment by sagetherage** [comment]
@alan-cugler I have added these and tried to use few characters and the most relevant and shortest word, but please let me know if `docs` vs `doc` is imperative
![image](https://user-images.githubusercontent.com/36676171/74266978-10573480-4cba-11ea-909b-e02b4af88175.png)

If this is sufficient, then please simply close the ticket. I hope this helps, and will help with getting these in use for the current 85 tickets labeled simply `Documentation`

**Comment by alan-cugler** [comment]
Thank you @sagetherage, I will close this!
