### ISSUE TITLE
Py3 Ubuntu 16.04 failures 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53945]
### Description of Issue
https://jenkinsci.saltstack.com/job/neon/view/Python3/job/salt-ubuntu-1604-py3/73/

**Comment by dmurphy18** [comment]
Subsequent builds test fine.
Examining possible race conditions from self.run_function

**Comment by dmurphy18** [comment]
Closing this since time as moved on and updates have been made
