### ISSUE TITLE
Neon Py3 Ubuntu transport test failures 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#53950]
### Description of Issue
https://jenkinsci.saltstack.com/job/neon/view/Transport/job/salt-ubuntu-1604-py3-tcp/72/

**Comment by KChandrashekhar** [comment]
Non - release blocker

**Comment by sagetherage** [comment]
@dwoz I know you are not actively working on this and it doesn't look like it needs attention. Closing for now.
