### ISSUE TITLE
Uptime / since_t should be part of the grains

### ISSUE THREAD

**Issue by sbernhard** [saltstack/salt#53960]
### Description of Issue
The uptime / since_t is often required but currently it's not included in the grains. Instead, a status.uptime needs to be called. 

It would be very helpful, if 
- status.uptime -> seconds or
- status.uptime -> since_t 
is included in the salt grains of a minion

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.6.0
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  9 2019, 14:30:50)
   python-gnupg: 0.4.3
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-862.14.4.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by dwoz** [comment]
@sbernhard Grains contain information about the system that does not frequently change. Since uptime is always changing I'm not sure it belongs in a grain. For example, We have a grain for system memory but not how much memory is being used at any given time.
