### ISSUE TITLE
user.present updating workphone, homephone fails

### ISSUE THREAD

**Issue by sotho** [saltstack/salt#53961]
A state definition like this:

foo:
  user:
    - present
    - workphone: 123

fails:
  comment: These values could not be changed: {u'workphone': 123}

I think the problem is that "123" is (internally) of type int instead of string and the final check if the update worked then fails.

I changed ./salt/states/user.py and it works for me.

In version 2018.3.4:

`    if workphone is not None:`
`-        workphone = sdecode(workphone)`
`+        workphone = sdecode(str(workphone))`
`    if homephone is not None:`
`-        homephone = sdecode(homephone)`
`+        homephone = sdecode(str(homephone))`

In version 2019.2.0:

`     if roomnumber is not None:`
`         roomnumber = salt.utils.data.decode(roomnumber)`
`     if workphone is not None:`
`-        workphone = salt.utils.data.decode(workphone)`
`+        workphone = salt.utils.data.decode(str(workphone))`
`     if homephone is not None:`
`-        homephone = salt.utils.data.decode(homephone)`
`+        homephone = salt.utils.data.decode(str(homephone))`
`     if other is not None:`
`         other = salt.utils.data.decode(other)`

roomnumber might also be affected, but didn't try.

Regards,
Alexander

**Comment by dwoz** [comment]
@sotho 

Does the state work without these changes if you modify your state to this?

```
foo:
  user:
    - present
    - workphone: '123'
```

I still think we might want to make the change to always cast these values to a string but I am just wondering if this is a reasonable work around for now.

Ultimately we need to have better input validation for both states and modules.

**Comment by sotho** [comment]
Yes, adding quotes seems to help indeed.

**Comment by priyank-R** [comment]
FYI, I've made the modification suggested by @sotho on the following fields:
- fullname
- workphone
- homephone
- roomnumber
- other
