### ISSUE TITLE
General question about targeting partial IP address

### ISSUE THREAD

**Issue by LaughHammers** [saltstack/salt#53998]
I am trying to use some jinja logic like so... 

```
{% if grains["ipv4"] == "10.171.*" %}

do stuff

{% endif %}
```

but this does not work, so how can I go about achieving this?

Thanks,

Greg
UWHealth

**Comment by dwoz** [comment]
@LaughHammers The first thing that comes to mind is this:

```
{% if grains["ipv4"].startswith("10.171") %}

do stuff

{% endif %}
```

If this doesn't work then you'll probably want to look into using a custom module. An example of this can be found here: https://groups.google.com/forum/#!topic/salt-users/EUbnCGlroAA

**Comment by LaughHammers** [comment]
@dwoz This is what ended up working for me.

{% if salt.network.ip_in_subnet( salt['network.ip_addrs']() , '10.171.0.0/16' ) %}
