### ISSUE TITLE
supervisord module does not acount for non-zero return codes introduced in Supervisor 4.0

### ISSUE THREAD

**Issue by redbaron4** [saltstack/salt#54028]
Supervisor-4.0 has introduced non-zero return codes to communicate the status of processes. See [this issue on supervisor page for more info](https://github.com/Supervisor/supervisor/issues/1223). As per new policy, `supervisorctl` commands can return non-zero return codes to communicate the status of underlying processes. E.g. `3` is used if a process is not running.

Salt's supervisor module/state depend on return of `0` code.

Our current `supervisord.running` states are all showing unexpected behaviour when used with supervisor-4.x. The states attempts to add and start the process on each run (even if the process is already running) and thus is marked as "CHANGED".

I experimented with passing `ignore_retocde` and `success_retcodes` to the `cmd.run_all` in `supervisord` module and it looks like passing `success_retcodes=range(256)` does fix the problem.

There is an open feature request #50566 which asks for something similar.

### Setup
Install any version of salt and supervisor 4.0 (latest is 4.0.4)

### Steps to Reproduce Issue

Ensure atleast one process is in the `STOPPED` state before running this test.

```
# salt-call -l warning supervisord.status
[ERROR   ] Command '[u'/usr/bin/supervisorctl', u'status']' failed with return code: 3
[ERROR   ] stdout: barnyard2                           RUNNING   pid 871, uptime 7:14:29
bryacu                              RUNNING   pid 14224, uptime 9 days, 22:26:14
fprobe:fprobe_netflow_logtash_mac   RUNNING   pid 14226, uptime 9 days, 22:26:14
net_transcript:transcript_server    RUNNING   pid 14229, uptime 9 days, 22:26:14
net_transcript:transcript_webapp    RUNNING   pid 14231, uptime 9 days, 22:26:14
netsniff-ng                         RUNNING   pid 3615, uptime 15:45:17
netsniff-ng-rollover                STOPPED   Jul 26 12:00 AM
parse_stats                         RUNNING   pid 14234, uptime 9 days, 22:26:14
snort                               RUNNING   pid 843, uptime 7:14:45
snort_u2streamer                    RUNNING   pid 14223, uptime 9 days, 22:26:14
[ERROR   ] retcode: 3
local:
    ----------
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.13
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jul 12 2017, 17:32:34)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.1.6
 
System Versions:
           dist: redhat 6.6 Carbon
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-431.el6.x86_64
         system: Linux
        version: Scientific Linux 6.6 Carbon

```

**Comment by garethgreenaway** [comment]
This request seems the same as https://github.com/saltstack/salt/issues/50566, I'm inclined to close this one in favor of the previous request.  Can you explain how this one might be different?

**Comment by redbaron4** [comment]
@garethgreenaway This is similar to linked issue but that issue talks about checking the return code (and possibly modifying code paths for different return codes). As seen in supervisor discussion page, return codes have a lot of interchangeable meanings (process STOPPED or FATAL both return 3). 
Since salt already uses textual parsing to deduce state of individual processes from the output, IMO it would be better to disregard the return codes altogether.

**Comment by L4rS6** [comment]
Reactivate...

**Comment by sagetherage** [comment]
@garethgreenaway can you follow up here, please?

**Comment by redbaron4** [comment]
Reactivate

**Comment by sagetherage** [comment]
this maybe a good candidate for a salt-extension module that has lots of changes that could be iterated upon outside of the core salt code base you can see an [overview](https://www.youtube.com/watch?v=hhomJkwxK3Q&t=18s) on our youtube channel and there is a repo for the simple tool to make a salt-extension module. Docs are still pending.

**Comment by garethgreenaway** [comment]
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.
