### ISSUE TITLE
zabbix.configuration_import "'applications': {'updateExisting': True } is obsolete and causes errors in new zabbix versions

### ISSUE THREAD

**Issue by vvolas** [saltstack/salt#54020]
### Description of Issue
salt/modules/zabbix.py:2458
default_rules = {'applications': {'createMissing': True, **'updateExisting': False,** 'deleteMissing': False},

Is obsolete and causes issues on newer zabbix versions.
https://www.zabbix.com/documentation/4.2/manual/api/reference/configuration/import

### Steps to Reproduce Issue
`salt ubuntu18 zabbix.configuration_import /testas.xml`

```
ubuntu18:
    ----------
    message:
        Zabbix API: Invalid params. (Invalid parameter "/rules/applications": unexpected parameter "updateExisting".)
    name:
        /testas.xml
    result:
        False
ERROR: Minions returned with non-zero exit code
```

### Versions Report
salt 2019.2.0 (Fluorine)
zabbix 3.4?+ (dont know exact version which introduced the change) I m using zabbix_server (Zabbix) 4.2.4

**Comment by vvolas** [comment]
As a fix I would suggest removing defaults all together so you have to always specify them just like in api. But it would break existing scripts.

**Comment by dwoz** [comment]
@vvolas Thanks for reporting this issue.

**Comment by flassman** [comment]
Would make sense to me to have different defaults in salt/modules/zabbix.py:configuration_import() depending on the apiinfo_version(), just like it is done in other functions in the same module
