### ISSUE TITLE
maybe a state.sls  service bug 

### ISSUE THREAD

**Issue by kussatom** [saltstack/salt#54043]
### Description of Issue
use state.sls to start or stop a  service in windows  ,in a general way  there is no problem,but  if the service is running as a customized user  not  the default by system, it will fail
### Setup
nothing special,only the windows user which the service run with is a  cutomized user or the  default user as other service ,

### Steps to Reproduce Issue
in the windows minion  ,the log sshow that    log in failed.BUT if i use service.start command ,it will success.

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: 3.7.2
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.3
         Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by dwoz** [comment]
@twangboy Isn't there a way to specify the use a service should be run as?

**Comment by kussatom** [comment]
@dwoz  the document about service : https://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html  i cann't find any  parameter to specify  a user

**Comment by twangboy** [comment]
@kussatom What user is salt-minion running under. What user is the service you're trying to start/stop running under?

**Comment by kussatom** [comment]
> @kussatom What user is salt-minion running under. What user is the service you're trying to start/stop running under?  salt-minion user is "system" which is the default user , my own service user is a ordinary user without administration role which i add it
