### ISSUE TITLE
salt-masterless packer build showing state failed, but succeeds

### ISSUE THREAD

**Issue by ejmason101** [saltstack/salt#54065]
### Steps to Reproduce Issue

Building custom GCP image using packer, using the salt-masterless provisioner:

```
{
        "type": "salt-masterless",
        "skip_bootstrap": true,
        "log_level": "warning",
        "local_state_tree": "salt-state-tree",
        "pause_before": "10s"
}
```

When building, the salt state.highstate will fail on updating the motd with 

```'
place custom MOTD:
  file.managed:
    - name: /etc/motd
    - source: salt://config/linux/generic/motd/files/motd.txt
    - user: root
    - group: root
    - mode: 644
```

In the packer build the state will return 

```
googlecompute: ----------
    googlecompute:           ID: place custom MOTD
    googlecompute:     Function: file.managed
    googlecompute:         Name: /etc/motd
    googlecompute:       Result: False
    googlecompute:      Comment: Unable to manage file: 'module' object has no attribute 'path'
    googlecompute:      Started: 17:15:37.201064
    googlecompute:     Duration: 15.481 ms
    googlecompute:      Changes:
    googlecompute:

```

However, if I remove the MOTD state call from top.sls, get a successful image build, and then call `salt-call --local state.apply` the same error will show, but the motd will be updated

https://gist.github.com/ejmason101/9411c6ecf9943281fd165e0bb993a25e

### Versions Report
custom-image-testing:~ # salt-call --versions-report
Salt Version:
           Salt: 2016.11.4

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
        machine: x86_64
        release: 4.4.180-94.97-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by ejmason101** [comment]
I updated the motd init.sls to include show_changes: True and the state still showed as failed, but updated the /etc/motd

**Comment by garethgreenaway** [comment]
@ejmason101 Thanks for the report.  It appears that you're running the 2016.11 release of Salt.  Unfortunately this version is no longer supported.  If possible, please upgrade to one of the supported versions such as 2018.3 or 2019.2.
