### ISSUE TITLE
Profile Error when trying to generate an Azure VM from saltmaster

### ISSUE THREAD

**Issue by Abuba-369** [saltstack/salt#54088]
### Description of Issue
My Salt Master is in local and I am trying to get vm generation in Azure to work from a salt master. I am able to communicate with Azure and it begins the process of spinning up the VM but it fails during the creation with a profile error.

### Setup
Provider Configuration:
```
azure-ubuntu:
  driver: azurearm
  subscription_id: SUBSCRITION_ID

  tenant: TENANT_ID
  client_id: CLIENT_ID
  secret: MY_SECRET

  location: eastus
  resource_group: AzureDemo
  network_resource_group: AzureDemo
  storage_account: MY_STORAGE_ACCOUNT
  storage_key: MY_STORAGE_KEY

  cleanup_disks: True
  cleanup_vhds: True
  cleanup_data_disks: True
  cleanup_interfaces: True
```

  # Set up the location of the salt master
  #
```
  minion:
    master: MASTER_IP
```

Profile Configuration:
```
azure-ubuntu:
  provider: azure-ubuntu
  image: Canonical|UbuntuServer|18.04-LTS|18.04.201804262
  size: Standard_DS1
  ssh_username: MY_USERNAME
  ssh_password: MY_PASSWORD
  location: eastus

  network: AzureDemo-Network
  public_ip: False
```

### Steps to Reproduce Issue
```
[ERROR   ] There was a profile error: __init__() takes exactly 1 argument (2 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1458, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 1403, in create
    vm_request = request_instance(vm_=vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 1330, in request_instance
    NetworkInterfaceReference(vm_['iface_id']),
TypeError: __init__() takes exactly 1 argument (2 given)
```

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by Abuba-369** [comment]
My Salt Master is in local and I am trying to get vm generation in Azure to work from a salt master. I am able to communicate with Azure and it begins the process of spinning up the VM but it fails during the creation with a profile error.

**Comment by garethgreenaway** [comment]
@Abuba-369 Thanks for the report.  I wonder if something changed in the Python Azure libraries.  Are you able to provide the version that is installed where you're seeing this issue?  @saltstack/team-cloud Any thoughts?

**Comment by nicholasmhughes** [comment]
@Abuba-369 please provide the output of `pip freeze | egrep 'azure|msrest'`

**Comment by Abuba-369** [comment]
sorry

**Comment by Abuba-369** [comment]
For that late reply, azure storage is missing after I install azure-storage via pip
pip install azure-storage it's working fine
