### ISSUE TITLE
saltutil.sync_grains failed on many minions when perform the action against the complete inventory

### ISSUE THREAD

**Issue by kk21986** [saltstack/salt#54086]
### Description of Issue
When I run `salt '*' saltutil.sync_grains -t 60 --summary` again 6k minions the sync is not happening on almost 4k minions and got the error `Minion did not return. [No response]`. But when I do the `test.ping` able to get a response from most of them. Not sure if am performing this action in the wrong way and guide if there is a better method to perform action seamlessly. 

```
-------------------------------------------
Summary
-------------------------------------------
# of minions targeted: 5778
# of minions returned: 2095
# of minions that did not return: 3683
# of minions with errors: 0
-------------------------------------------
````

### Steps to Reproduce Issue
`salt '*' saltutil.sync_grains -t 60 --summary`

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.7.3
         pygit2: Not Installed
         Python: 3.7.1 (default, Nov 23 2018, 02:59:05)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 4.1.16-145.26.7.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo
```

**Comment by garethgreenaway** [comment]
@kk21986 Thanks for the report.  It's possible that the sync_grains is completing on all hosts just not returning to the Salt master in the time allowed.  Do you have any custom grains in place?

**Comment by kk21986** [comment]
Yes. I have custom grains which is what am trying to sync across the fleet. Though we have 8 syndic masters which manage all the minions and all syndics masters are connected with Multi-Master. FYI, I have running sync command from multi-master.

**Comment by kk21986** [comment]
@garethgreenaway Please don't mark this as stale as we are still facing this error.

**Comment by kk21986** [comment]
@garethgreenaway  Am still facing this issue. Can you please get this issue re-opened?
