### ISSUE TITLE
will the certification between master and minion get  expired

### ISSUE THREAD

**Issue by kussatom** [saltstack/salt#54085]
### Description of Issue
when the master accept the minion,everything is ok ,i wonder whether the certification become out of date, then i have to begin a new cetification 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@kussatom Thanks for the report.  The keys that are generated by the Salt master for the Salt minion do not expire and will remain in use unless you force a regeneration of the keys.
