### ISSUE TITLE
salt-cp high memory consumption

### ISSUE THREAD

**Issue by Gerarddp** [saltstack/salt#54089]
### Description of Issue
When using `salt-cp` with a file of at least 400Mb, salt-master will start using memory until the file is copied or the command cancelled.

### Setup
Tried on multiple set-ups, with the same issue.

### Steps to Reproduce Issue
`# salt-cp minion file.zip /path/`

### Versions Report
````
# salt-cp --version
salt-cp 2019.2.0 (Fluorine)

# salt --versions-report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.8
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8
````

**Comment by garethgreenaway** [comment]
@Gerarddp Thanks for the report.  While not ideal this is the expected behavior when copying large files using `salt-cp` or the `cp` execution module.  The Salt fileserver isn't designed or intended for use with large files.  The recommended approach is to use something like an HTTP or rsync server in these sitautions.

**Comment by mspi92** [comment]
To add some information to this issue: 
In the first step the memory usage of the saltmaster increased to the maximum available memory of the OS and the master was killed with an OOM Error.
Following after that the same behaviour occured on ALL connected minions, regardless if it was targeted via the salt-cp command or not. This also caused the applications on this remote servers to stop, as no more memory was available on the OS, until the minion was killed by the OOM protection of the OS.
This is a very dangerous behaviour and should be captured in the salt-cp tool, as it could lead to downtime of services or require a lot of manual work to recover from this failure condition, if the salt-cp command is used with a large filesize.

At least a big warning should be added in the documentation
