### ISSUE TITLE
stop depending on pycrypto

### ISSUE THREAD

**Issue by JanZerebecki** [saltstack/salt#54115]
### Description of Issue
PyCrypto is unmaintained and has open security issues. This was already reported in e.g. https://github.com/saltstack/salt/issues/52674 but it is currently closed.

### Steps to Reproduce Issue
Run `pip download salt` and check if it mentions pycrypto. It currently does, but it should not. It currently comes from https://github.com/saltstack/salt/blob/develop/requirements/zeromq.txt .

### Versions Report
Checked for 2019.2.0 via pip, and on branch develop by inspecting the above file.

**Comment by OrangeDog** [comment]
Note that OS packages (e.g. python3-crypto) should already have the security issues patched on currently-supported systems.
