### ISSUE TITLE
integration.cloud.clouds.test_gce.GCETest.test_instance

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54114]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Cloud/job/salt-centos-7-py3-cloud/117/

**Comment by KChandrashekhar** [comment]
This is intermittently happening again 
https://jenkinsci.saltstack.com/job/2019.2.1/view/Cloud/job/salt-centos-7-py2-cloud/208/

**Comment by Akm0d** [comment]
If the instance is being destroyed in the tearDown rather on the first call to delete, my first guess would to be to increase the timeout from 500 to 1000 in `tests/cloud/clouds/helpers/cloud_test_base.py`

**Comment by Ch3LL** [comment]
we okay to close this @Akm0d
