### ISSUE TITLE
2019.2.0 with py3: is very slow compared to 2017.7.4 with py2

### ISSUE THREAD

**Issue by disaster123** [saltstack/salt#54125]
### Description of Issue
salt got very slow after updating to 2019.2.0

### Steps to Reproduce Issue
run states with 2017 py2 and 2019.2.0 py3 and compare run time

2017.7.4:
```
time salt-call state.apply test=true
...
Summary for local
--------------
Succeeded: 236 (unchanged=25, changed=6)
Failed:      0
--------------
Total states run:     236
Total run time:     5.783 s

real    0m22,220s
user    0m12,270s
sys     0m2,307s
```

2019.2.0:
```
time salt-call state.apply test=true
...
Summary for local
--------------
Succeeded: 236 (unchanged=25, changed=6)
Failed:      0
--------------
Total states run:     236
Total run time:    11.279 s

real    0m36,997s
user    0m27,404s
sys     0m2,694s
```

These results are reproducable.

**Comment by twangboy** [comment]
We're seeing the same thing in our tests. Python 3 runs 50% to 100% slower than Python 2. It is likely we'll continue to have this problem until we are able to drop Py2 support and optimize for Python 3.

**Comment by tomlaredo** [comment]
How long this situation is supposed to last?
When the full python 3 version will be released?

This is a big regression for users that have hundreds of servers.
Also, I'm observing issues due to this execution time. Many requests initiated by the master are lasting with "Minion did not return. [No response]" error message. Is tis related?

**Comment by disaster123** [comment]
Yes same here - as @twangboy commented this issue will stay for month or may be years. I just switched back to py2.

**Comment by robertchen** [comment]
I saw same issue, very big difference:

salt-2018.3.3
`[root@use-exs salt]# time /usr/bin/salt-call cmd.run hostname
local:
    use-exs

real    0m1.342s

`
salt-2019.2.2:
`[root@use-exs2 home]# time /usr/bin/salt-call cmd.run hostname
local:
    use-exs2

real    0m4.829s

4 times slow

**Comment by sagetherage** [comment]
not stale

**Comment by anilsil** [comment]
Please retest with the latest 3006.x and file a new issue if you observe similar behavior.
