### ISSUE TITLE
Fedora 30 py2 test failures on 2019.2.1 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54139]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-fedora-30-py2/

**Comment by dmurphy18** [comment]
Previous failure build 96 was due to CodeCov outage

**Comment by dmurphy18** [comment]
Back working with builds 98 through 100, with CodeCov back.
Closing since failure due to missing CodeCov service (that is 503) outtages
