### ISSUE TITLE
Ssh timeouts in salt test cases

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54132]
### Description of Issue
This issue is to deep dive and fix Salt ssh timeouts

**Comment by KChandrashekhar** [comment]
Need to check Ruby logs to triage the ssh timeouts 
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-amazon-2-py2/127/artifact/.kitchen/logs/py2-amazon-2-verify.log/*view*/

**Comment by dmurphy18** [comment]
closing this out since Salt 2019.2.1 is released and Wayne is following up
