### ISSUE TITLE
Py3 Ubuntu 18.04 failures on 2019.2.1 branch

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54168]
### Description of Issue
Failing in https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-ubuntu-1804-py3/127/ 

@felippeb Checking to see if testing process is still active but no logging happening, and to get more logging.

**Comment by Ch3LL** [comment]
this is a duplicate of https://github.com/saltstack/salt/issues/54182
