### ISSUE TITLE
error when processing LocalClient get_cli_returns

### ISSUE THREAD

**Issue by sundowner69** [saltstack/salt#54175]
### Description of Issue
When starting a state.apply from a LocalClient with run_job() function and waiting for the returns with the get_cli_returns() function an error message from the event modul appears.
The error happens when the function unsubscribe() in the salt.utils.event modul tries to remove the job from an already empty list.
<pre><code>
 def unsubscribe(self, tag, match_type=None):
        '''
        Un-subscribe to events matching the passed tag.
        '''
       ...
        self.pending_tags.remove([tag, match_func]) 
       ....
/code></pre>

### Setup
Master and minion on same host.
State file test.sls:
<pre><code>
test1 :
  test.succeed_with_changes : []
</code></pre>
Script: apitest.py
<pre><code>
import salt.client
import json

local = salt.client.LocalClient()

ret = local.run_job('*','state.apply',['test'])
if ret :
    returned = local.get_cli_returns(ret['jid'],ret['minions'], verbose=True)
    for server in returned :
        print( json.dumps( server, indent=4 ) )
</code></pre>
Output:
<pre><code>
leap151:/srv/salt # python3 apitest.py 
Executing job with jid 20190810142659884529
-------------------------------------------

{
    "leap151.asteras.cool": {
        "ret": {
            "test_|-test1_|-test1_|-succeed_with_changes": {
                "name": "test1",
                "changes": {
                    "testing": {
                        "old": "Unchanged",
                        "new": "Something pretended to change"
                    }
                },
                "result": true,
                "comment": "Success!",
                "__sls__": "test",
                "__run_num__": 0,
                "start_time": "14:27:00.036770",
                "duration": 0.442,
                "__id__": "test1"
            }
        },
        "out": "highstate"
    }
}
salt/job/20190810142659884529
Traceback (most recent call last):
  File "apitest.py", line 12, in <module>
    for server in returned :
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 987, in get_cli_returns
    self._clean_up_subscriptions(jid)
  File "/usr/lib/python3.6/site-packages/salt/client/__init__.py", line 1866, in _clean_up_subscriptions
    self.event.unsubscribe('salt/job/{0}'.format(job_id))
  File "/usr/lib/python3.6/site-packages/salt/utils/event.py", line 355, in unsubscribe
    self.pending_tags.remove([tag, match_func])
ValueError: list.remove(x): x not in list
</code></pre>

### Versions Report
<pre><code>
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.26.8
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.5 (default, Mar 31 2018, 19:45:04) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-lp151.28.10-default
         system: Linux
        version: Not Installed
</code></pre>

**Comment by dmurphy18** [comment]
@sundowner69 Can you provide the Operating Platform that the above is being performed on, for example: contains of cat /etc/redhat-release or lsb_release -a, in order to reproduce the issue seen.

**Comment by sundowner69** [comment]
@dmurphy18 I tried on SLES 12 SP4, SLES15 SP1 and openLEAP 15.1. The last available 2018.3 version in the repositories is ok but after upgrading to 2019.2 the thing is somehow broken.

**Comment by dmurphy18** [comment]
@sundowner69 Presuming by  _last available 2018.3 version in the repositories is ok_ you imply Salt 2018.3.4 for Python 3.  However on Ubuntu 18.04 (checking before bringing up a SLES environment) I find that 2018.3.4 has errors with the provided files:
root@david-VirtualBox:~/dev# python3 apitest.py
Executing job with jid 20190813114432824899
-------------------------------------------

{
    "t18043": {
        "ret": {
            "test_|-test1_|-test1_|-succeed_with_changes": {
                "name": "test1",
                "changes": {
                    "testing": {
                        "old": "Unchanged",
                        "new": "Something pretended to change"
                    }
                },
                "result": true,
                "comment": "Success!",
                "__sls__": "test",
                "__run_num__": 0,
                "start_time": "11:44:32.962267",
                "duration": 0.818,
                "__id__": "test1"
            }
        },
        "out": "highstate"
    }
}
Traceback (most recent call last):
  File "apitest.py", line 9, in <module>
    for server in returned :
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 1114, in get_cli_returns
    self._clean_up_subscriptions(jid)
  File "/usr/lib/python3/dist-packages/salt/client/__init__.py", line 2018, in _clean_up_subscriptions
    self.event.unsubscribe('salt/job/{0}'.format(job_id))
  File "/usr/lib/python3/dist-packages/salt/utils/event.py", line 356, in unsubscribe
    self.pending_tags.remove([tag, match_func])
ValueError: list.remove(x): x not in list
root@david-VirtualBox:~/dev# cat /srv/salt/test.sls 

test1 :
  test.succeed_with_changes : []

root@david-VirtualBox:~/dev# salt-call --local test.versions
[DEBUG   ] Configuration file path: /etc/salt/minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/minion
[DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
[DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
[DEBUG   ] Please install 'virt-what' to improve results of the 'virtual' grain.
[DEBUG   ] Determining pillar cache
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded test.versions
[DEBUG   ] Popen(['git', 'version'], cwd=/root/dev, universal_newlines=False, shell=None)
[DEBUG   ] Popen(['git', 'version'], cwd=/root/dev, universal_newlines=False, shell=None)
[DEBUG   ] LazyLoaded nested.output
local:
    Salt Version:
               Salt: 2018.3.4
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: 2.6.1
          docker-py: Not Installed
              gitdb: 2.0.3
          gitpython: 2.1.8
              ioflo: Not Installed
             Jinja2: 2.10
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
       python-gnupg: 0.4.1
             PyYAML: 3.12
              PyZMQ: 16.0.2
               RAET: Not Installed
              smmap: 2.0.3
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.2.5
     
    System Versions:
               dist: Ubuntu 18.04 bionic
             locale: UTF-8
            machine: x86_64
            release: 4.15.0-20-generic
             system: Linux
            version: Ubuntu 18.04

Is there some other file or state required to pass on Salt 2018.3.4 ?  Noting that for this simple test, I believe the OS is not a factor given similar Python 3 etc.

**Comment by sundowner69** [comment]
@dmurphy18 Not sure if I understand your question correctly. The last available 2018.3 version from the SUSE repositories is 2018.3.0-46.62.1, whatever that means. I guess SUSE is packaging own versions regarding the minor number. However this version is working fine.
The next available update jumps to 2019.2.0-46.65.2 which is definitely causing the error.
Since we often make use of this kind of python scripts I only gave a minimal example to show the issue we are facing. Is this the answer to your question?

**Comment by dmurphy18** [comment]
@sundowner69 SUSE packages Salt, and SaltStack only provides access to them as a convenice in repo.saltstack.com. Seeing version numbering that you report 2018.3.0-46.62.1 and 2019.2.0-46.65.2 raises concerns since Salt packages should not have that as a version number, it should be 2018.3.0 and 2019.2.0.

w.r.t my previous comment, it does not work with the provided information from you on 2018.3.4, hence my wonder about 2019.2.0, that is, trying to ensure I had a working version on 2018.3.4 before upgrading, failed.

I shall try with openLeap 15.1 or which is your prefer version of SLES ?

**Comment by sundowner69** [comment]
@dmurphy18 Since openLeap 15.1 only provides salt 2019.2 you should test with SLES12 SP4 or openLeap 42.3. Both should bring repositories which deliver salt 2018.3.0 and 2019.2. You can try both versions by forced reinstall of a lower version and you will see it working fine on salt 2018.3. Thanks!

**Comment by dmurphy18** [comment]
@sundowner69 can you provide the commands with which you installed your version of Salt 2018.3.0 and 2019.2.0, since I see a number of different versions of Salt for different versions of SUSE's OS's, and I wan tot ensure I install the exact same versions that you utilized, especially since you state 2018.3.0, and the latest stable for that branch is 2018.3.4.  The problem you are experiencing may not be due to 2019.2.0 but in a different 2018.3.x point release, which would explain the error I saw with your provided example on Salt 2018.3.4.

Using SLES 12sp3 since easily available on AWS.

**Comment by dmurphy18** [comment]
Able to duplicate with Debian 9 and Salt 2018.3.0 and 2018.3.1

**2018.3.0**
root@deb9min:~/dev# python ./apitest.py 
Executing job with jid 20190815170808240714
-------------------------------------------

{
    "t9": {
        "ret": {
            "test_|-test1_|-test1_|-succeed_with_changes": {
                "comment": "Success!", 
                "name": "test1", 
                "start_time": "17:08:08.362656", 
                "result": true, 
                "duration": 1.476, 
                "__run_num__": 0, 
                "__sls__": "test", 
                "changes": {
                    "testing": {
                        "new": "Something pretended to change", 
                        "old": "Unchanged"
                    }
                }, 
                "__id__": "test1"
            }
        }, 
        "out": "highstate"
    }
}


**2018.3.1**
root@deb9min:~/dev# python ./apitest.py 
Executing job with jid 20190815170945352502
-------------------------------------------

{
    "t9": {
        "ret": {
            "test_|-test1_|-test1_|-succeed_with_changes": {
                "comment": "Success!", 
                "name": "test1", 
                "start_time": "17:09:45.472250", 
                "result": true, 
                "duration": 1.476, 
                "__run_num__": 0, 
                "__sls__": "test", 
                "changes": {
                    "testing": {
                        "new": "Something pretended to change", 
                        "old": "Unchanged"
                    }
                }, 
                "__id__": "test1"
            }
        }, 
        "out": "highstate"
    }
}
Traceback (most recent call last):
  File "./apitest.py", line 9, in <module>
    for server in returned :
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 1100, in get_cli_returns
    self._clean_up_subscriptions(jid)
  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 1997, in _clean_up_subscriptions
    self.event.unsubscribe('salt/job/{0}'.format(job_id))
  File "/usr/lib/python2.7/dist-packages/salt/utils/event.py", line 351, in unsubscribe
    self.pending_tags.remove([tag, match_func])
ValueError: list.remove(x): x not in list
root@deb9min:~/dev#

**Comment by dmurphy18** [comment]
Problem is need to check if list is empty before attempting to remove an item from it, speed execution
and need a try/except for ValueError in case the item is not found in utils/event.py

list.remove(x)
Remove the first item from the list whose value is x. It is an error if there is no such item.

**Comment by dmurphy18** [comment]
@sundowner69 Thanks for finding the issue.
