### ISSUE TITLE
2019.2.1 Tornado failures 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54187]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Tornado/job/salt-centos-7-py2-tornado/129/
https://jenkinsci.saltstack.com/job/2019.2.1/view/Crypto/job/salt-ubuntu-1604-py3-pycryptodomex/118/

**Comment by s0undt3ch** [comment]
No more access to logs, but I remember addressing this
