### ISSUE TITLE
Py3 Pycrypto domex test failures in 2019.2.1

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54188]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Crypto/job/salt-centos-7-py3-pycryptodomex/138/

Also notice that below test that failed took about 25 mins to finish 
05:54:56           test_all_saltenvs (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP) ... ERROR (1550.861s)
06:20:43           test_all_saltenvs_base (integration.pillar.test_git_pillar.TestGitPythonAuthenticatedHTTP) ... ERROR (1550.845s)

**Comment by s0undt3ch** [comment]
The issue here was that the salt-minion test daemon failed to start, which triggered a bunch of failures because we didn't have a minion running.
The fix in #54263 is to stop the test suite prematurely if one of the test daemons fails to start.
