### ISSUE TITLE
integration.shell.test_syndic.SyndicTest

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54182]
### Description of Issue
Test is timing out on couple of options https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-ubuntu-1804-py3/127/
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-fedora-29-py3/126/

[2019-08-09T10:24:23.662Z]          test_exit_status_unknown_user (integration.shell.test_syndic.SyndicTest) ... OK (10.599s)
[2019-08-09T15:23:08.963Z] Cancelling nested steps due to timeout

**Comment by Ch3LL** [comment]
also holding up on this test too: `test_exit_status_unknown_user (integration.shell.test_minion.MinionTest) ... OK (11.036s)`

**Comment by LuAPi** [comment]
Also seen on 2018.3 Py3 Amazon Linux 2, Py3 CentOS 7, Py3 Ubuntu 18.04.
The last successful test on Amazon and CentOS 7 was `test_exit_status_unknown_user`. On Ubuntu the logs said
```
14:09:49           test_shadowed_dict_method (unit.utils.test_jinja.TestDotNotationLookup) ... OK (0.026s)
14:09:49           test_fallback (unit.utils.test_jinja.TestGetTemplate) ... 13:09:48,890 [salt.loader                                               :1718][ERROR   ] Failed to load function roo.envs because its module (roo) is not in the whitelist: ['roots']
14:09:49         13:09:48,891 [salt.loader                                               :1718][ERROR   ] Failed to load function roo.envs because its module (roo) is not in the whitelist: ['roots']
14:09:49         OK (0.060s)
17:43:59  Cancelling nested steps due to timeout
```

**Comment by Ch3LL** [comment]
not failing anymore after https://github.com/saltstack/salt/pull/54223
