### ISSUE TITLE
Salt-Cloud Windows VM error: name 'PsExecClient' is not defined

### ISSUE THREAD

**Issue by DaWoschbar** [saltstack/salt#54195]
### Description of Issue
I want to deploy a windows server 2019 VM on my vCenter/vSphere instance that is running on an ESXi 6.7. The VM shall be created from a Windows server template, that has the latest update and a disabled firewall. I installed all the requirements on the Salt-Master (Source [here](https://salt-cloud.readthedocs.io/en/latest/topics/windows.html))  for the deployment. When i now want to deploy it on the vCenter Server, i get the following error:
```
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Deploying 10.0.0.32 at 1565703846.0 (Windows)
[DEBUG   ] Attempting connection to host 10.0.0.32 on port 445
[ERROR   ] Unable to execute command
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/cloud.py", line 1015, in wait_for_psexecsvc
    'cmd.exe', '/c hostname', host, username, password, port=port
  File "/usr/lib/python3/dist-packages/salt/utils/cloud.py", line 962, in run_psexec_command
    client = Client(host, username, password, port=port, encrypt=False, service_name=service_name)
  File "/usr/lib/python3/dist-packages/salt/utils/cloud.py", line 875, in __init__
    self._client = PsExecClient(server, username, password, port, encrypt)
NameError: name 'PsExecClient' is not defined
[DEBUG   ] Retrying psexec connection to host 10.0.0.32 on port 445 (try 1)
[ERROR   ] Unable to execute command
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/cloud.py", line 1015, in wait_for_psexecsvc
    'cmd.exe', '/c hostname', host, username, password, port=port
  File "/usr/lib/python3/dist-packages/salt/utils/cloud.py", line 962, in run_psexec_command
    client = Client(host, username, password, port=port, encrypt=False, service_name=service_name)
  File "/usr/lib/python3/dist-packages/salt/utils/cloud.py", line 875, in __init__
    self._client = PsExecClient(server, username, password, port, encrypt)
NameError: name 'PsExecClient' is not defined
```
The Salt-Master is stuck in a loop trying to get the PsExecClient on the windows server running. The deployment from the template and the installation of the VMware-Tools are successful. 
When i go to the vSphere WebClient, i can see that the VM is cloned from the template and running without any errors. A login to the virtual machine is also possible via the web console

Is there something i may have missed or what exactly does the PsExeClient on the Windows server? I haven't encountered this problem when deploying CentOS or Debian VM via the Salt-Master.
 I also haven't found any additional parameter that have to be declared in the [Salt docs](https://docs.saltstack.com/en/latest/topics/cloud/vmware.html).
### Setup
Cloud Provider:
```
esxi:
  driver: vmware
  user: [REDACTED]
  password: [REDACTED]
  url: '10.0.0.50'
  protocol: 'https'
  port: 443

vcenter:
  driver: vmware
  user: [REDACTED]
  password: [REDACTED]
  url: 10.0.0.234
```

cloud.profile:
```
ex-win_temp:
  provider: vcenter
  clonefrom: WinServer19_template
  resourcepool: Resources

  minion:
    master: 10.0.0.100

  win_username: [REDACTED]
  win_password: [REDACTED]
  plain_text: True
  win_installer: /setups/Salt-Minion-2019.2.0-Py3-x86-Setup.exe
```

### Steps to Reproduce Issue
`salt-cloud -p ex-win_temp WindowsServerVM -l debug`

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9
```

**Comment by dmurphy18** [comment]
@DaWoschbar The documentation that you linked to is quite old, from 2012-2013 and the use of smbclient and winexe is no longer recommended since smb v1.0 has been compromised and smb 2.0 is now recommended for safe and secure communications.

Please utilize the documentation at https://docs.saltstack.com/en/latest/topics/installation/windows.html and https://docs.saltstack.com/en/latest/topics/cloud/windows.html, the referenced pypsexec provides the missing PsExecClient

If this information resolves your issue, please consider closing the issue.

**Comment by DaWoschbar** [comment]
It looks like i somehow missed those articles, thank you for help!
