### ISSUE TITLE
Consider releasing packages for RHEL/CentOS 8

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#54215]
### Description of Issue
The [redhat package repo](https://repo.saltstack.com/#rhel) has packages for RHEL7 / CentOS 7 only. RHEL 8.1 is almost out, and you can get a license for it [for free](https://developers.redhat.com/blog/2016/03/31/no-cost-rhel-developer-subscription-now-available/) as a developer. Can someone build packages for RHEL8 for Salt?

**Comment by SEJeff** [comment]
related: saltstack/salt-pack-py3#137

**Comment by dmurphy18** [comment]
@SEJeff The RHEL 8 support is being delayed by the next point release of Salt 2019.2.1. There is support for RHEL 8 in 2019.2.1, which is under-going final QA, hence once 2019.2.1 is tagged, then packages for RHEL 8 will be produced similar to RHEL 7, etc.ote also 

Note also https://github.com/saltstack/salt-pack-py3/issues/120

Please consider closing this if the answer is sufficient

**Comment by SEJeff** [comment]
@dmurphy18 yeah that PR doesn't give me warm fuzzies as it just comments out exceptions in some cases. This will work, but I'm a bit disheartened looking at that PR. It doesn't look like a very well done "port".
