### ISSUE TITLE
Deprecate Joyent API

### ISSUE THREAD

**Issue by Akm0d** [saltstack/salt#54211]
### Description of Issue
Joyent is EOL as of November 9, 2019.   It's API in salt needs to be deprecated in the current release and removed from the next release

**Comment by nwilkens** [comment]
We've (https://mnx.io) been handling Joyent EOL refugees, and run the same Triton stack.  I'd like  consideration for a cloud provider rename, or maybe a better solution would be to rename this to API to Triton.

**Comment by sagetherage** [comment]
@Ch3LL

**Comment by sagetherage** [comment]
The deprecation cycle is described in the documentation: https://docs.saltstack.com/en/latest/topics/development/deprecations.html 

"A deprecation warning should be in place for at least two major releases before the deprecated code and its accompanying deprecation warning are removed. More time should be given for more complex changes." 

Core team will review and update the issue.

**Comment by sagetherage** [comment]
@Akm0d do you have an opinion on how to handle this deprecation?

**Comment by Akm0d** [comment]
We'll put it off for now until more is done for openstack/joyent/trident in idem-cloud
