### ISSUE TITLE
Issues with installing salt-minion 

### ISSUE THREAD

**Issue by karkey83** [saltstack/salt#54248]
### Description of Issue
Unable to install salt-minion (any version)

### Setup
yum install salt-minion -y

### Steps to Reproduce Issue
yum install salt-minion -y

### Versions Report
Getting issues with installing salt-minion latest version (2019.2.0) and 2018.3.4 version.
There seems to be some dependency issue with the rhel 7 packages.

Error: Package: systemd-python-219-42.el7_4.10.x86_64 (rhel-7-server-rpms)Requires: systemd = 219-42.el7_4.10Installed: systemd-219-42.el7_4.16.x86_64 (@rhel-7-server-eus-rpms)

result: 

Loaded plugins: enabled_repos_upload, package_upload, product-id, search-
              : disabled-repos, subscription-manager
Resolving Dependencies
--> Running transaction check
---> Package salt-minion.noarch 0:2019.2.0-1.el7 will be installed
--> Processing Dependency: salt = 2019.2.0-1.el7 for package: salt-minion-2019.2.0-1.el7.noarch
--> Running transaction check
---> Package salt.noarch 0:2019.2.0-1.el7 will be installed
--> Processing Dependency: python-tornado < 6.0 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python2-futures >= 2.0 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-tornado >= 4.2.1 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-requests >= 1.0.0 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-msgpack >= 0.4 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-crypto >= 2.6.1 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: yum-utils for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: systemd-python for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-zmq for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-psutil for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-markupsafe for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: python-jinja2 for package: salt-2019.2.0-1.el7.noarch
--> Processing Dependency: PyYAML for package: salt-2019.2.0-1.el7.noarch
--> Running transaction check
---> Package PyYAML.x86_64 0:3.11-1.el7 will be installed
--> Processing Dependency: libyaml-0.so.2()(64bit) for package: PyYAML-3.11-1.el7.x86_64
---> Package python-jinja2.noarch 0:2.7.2-2.el7 will be installed
--> Processing Dependency: python-babel >= 0.8 for package: python-jinja2-2.7.2-2.el7.noarch
---> Package python-markupsafe.x86_64 0:0.11-10.el7 will be installed
---> Package python-psutil.x86_64 0:5.0.1-1.el7sat will be installed
---> Package python-requests.noarch 0:2.6.0-1.el7_1 will be installed
--> Processing Dependency: python-urllib3 >= 1.10.2-1 for package: python-requests-2.6.0-1.el7_1.noarch
--> Processing Dependency: python-chardet >= 2.2.1-1 for package: python-requests-2.6.0-1.el7_1.noarch
---> Package python-tornado.x86_64 0:4.2.1-1.el7 will be installed
--> Processing Dependency: python-backports-ssl_match_hostname for package: python-tornado-4.2.1-1.el7.x86_64
---> Package python-zmq.x86_64 0:15.3.0-3.el7 will be installed
--> Processing Dependency: zeromq >= 4 for package: python-zmq-15.3.0-3.el7.x86_64
--> Processing Dependency: libzmq.so.5()(64bit) for package: python-zmq-15.3.0-3.el7.x86_64
---> Package python2-crypto.x86_64 0:2.6.1-16.el7 will be installed
--> Processing Dependency: libtomcrypt.so.0()(64bit) for package: python2-crypto-2.6.1-16.el7.x86_64
---> Package python2-futures.noarch 0:3.0.5-1.el7 will be installed
---> Package python2-msgpack.x86_64 0:0.5.6-5.el7 will be installed
---> Package systemd-python.x86_64 0:219-42.el7_4.10 will be installed
--> Processing Dependency: systemd-libs = 219-42.el7_4.10 for package: systemd-python-219-42.el7_4.10.x86_64
--> Processing Dependency: systemd = 219-42.el7_4.10 for package: systemd-python-219-42.el7_4.10.x86_64
---> Package yum-utils.noarch 0:1.1.31-42.el7 will be installed
--> Processing Dependency: python-kitchen for package: yum-utils-1.1.31-42.el7.noarch
--> Running transaction check
---> Package libtomcrypt.x86_64 0:1.17-25.el7 will be installed
--> Processing Dependency: libtommath >= 0.42.0 for package: libtomcrypt-1.17-25.el7.x86_64
--> Processing Dependency: libtommath.so.0()(64bit) for package: libtomcrypt-1.17-25.el7.x86_64
---> Package libyaml.x86_64 0:0.1.4-11.el7_0 will be installed
---> Package python-babel.noarch 0:0.9.6-8.el7 will be installed
---> Package python-backports-ssl_match_hostname.noarch 0:3.4.0.2-4.el7 will be installed
--> Processing Dependency: python-backports for package: python-backports-ssl_match_hostname-3.4.0.2-4.el7.noarch
---> Package python-chardet.noarch 0:2.2.1-1.el7_1 will be installed
---> Package python-kitchen.noarch 0:1.1.1-5.el7 will be installed
---> Package python-urllib3.noarch 0:1.10.2-3.el7 will be installed
---> Package systemd-libs.i686 0:219-42.el7_4.10 will be installed
--> Processing Dependency: libselinux.so.1 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: librt.so.1(GLIBC_2.3.4) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: librt.so.1(GLIBC_2.2) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: librt.so.1 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libresolv.so.2 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpthread.so.0(GLIBC_2.2) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpthread.so.0(GLIBC_2.1) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpthread.so.0(GLIBC_2.0) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpthread.so.0 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpam_misc.so.0(LIBPAM_MISC_1.0) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpam_misc.so.0 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpam.so.0(LIBPAM_MODUTIL_1.0) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpam.so.0(LIBPAM_EXTENSION_1.0) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpam.so.0(LIBPAM_1.0) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libpam.so.0 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libm.so.6 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: liblzma.so.5(XZ_5.0) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: liblzma.so.5 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libgpg-error.so.0 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libgcrypt.so.11(GCRYPT_1.2) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libgcrypt.so.11 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libgcc_s.so.1(GLIBC_2.0) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libgcc_s.so.1(GCC_3.3.1) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libgcc_s.so.1(GCC_3.0) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libgcc_s.so.1 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libdw.so.1 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libdl.so.2 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libcap.so.2 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.9) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.8) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.7) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.4) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.3.4) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.3.3) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.3.2) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.3) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.2.3) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.2) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.17) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.16) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.14) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.1.3) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.1.2) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.1.1) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.1) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6(GLIBC_2.0) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: libc.so.6 for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: ld-linux.so.2(GLIBC_2.3) for package: systemd-libs-219-42.el7_4.10.i686
--> Processing Dependency: ld-linux.so.2 for package: systemd-libs-219-42.el7_4.10.i686
---> Package systemd-python.x86_64 0:219-42.el7_4.10 will be installed
--> Processing Dependency: systemd = 219-42.el7_4.10 for package: systemd-python-219-42.el7_4.10.x86_64
---> Package zeromq.x86_64 0:4.1.4-7.el7 will be installed
--> Processing Dependency: libsodium.so.23()(64bit) for package: zeromq-4.1.4-7.el7.x86_64
--> Processing Dependency: libpgm-5.2.so.0()(64bit) for package: zeromq-4.1.4-7.el7.x86_64
--> Running transaction check
---> Package elfutils-libs.i686 0:0.168-8.el7 will be installed
--> Processing Dependency: elfutils-libelf(x86-32) = 0.168-8.el7 for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libz.so.1(ZLIB_1.2.2.3) for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libz.so.1 for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libelf.so.1(ELFUTILS_1.7) for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libelf.so.1(ELFUTILS_1.6) for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libelf.so.1(ELFUTILS_1.5) for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libelf.so.1(ELFUTILS_1.4) for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libelf.so.1(ELFUTILS_1.3) for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libelf.so.1(ELFUTILS_1.1.1) for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libelf.so.1(ELFUTILS_1.0) for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libelf.so.1 for package: elfutils-libs-0.168-8.el7.i686
--> Processing Dependency: libbz2.so.1 for package: elfutils-libs-0.168-8.el7.i686
---> Package glibc.i686 0:2.17-196.el7_4.2 will be installed
--> Processing Dependency: glibc-common = 2.17-196.el7_4.2 for package: glibc-2.17-196.el7_4.2.i686
--> Processing Dependency: libfreebl3.so(NSSRAWHASH_3.12.3) for package: glibc-2.17-196.el7_4.2.i686
--> Processing Dependency: libfreebl3.so for package: glibc-2.17-196.el7_4.2.i686
---> Package libcap.i686 0:2.22-9.el7 will be installed
--> Processing Dependency: libattr.so.1(ATTR_1.0) for package: libcap-2.22-9.el7.i686
--> Processing Dependency: libattr.so.1 for package: libcap-2.22-9.el7.i686
---> Package libgcc.i686 0:4.8.5-16.el7_4.2 will be installed
---> Package libgcrypt.i686 0:1.5.3-14.el7 will be installed
---> Package libgpg-error.i686 0:1.12-3.el7 will be installed
---> Package libselinux.i686 0:2.5-11.el7 will be installed
--> Processing Dependency: libsepol(x86-32) >= 2.5-6 for package: libselinux-2.5-11.el7.i686
--> Processing Dependency: libsepol.so.1(LIBSEPOL_1.0) for package: libselinux-2.5-11.el7.i686
--> Processing Dependency: libsepol.so.1 for package: libselinux-2.5-11.el7.i686
--> Processing Dependency: libpcre.so.1 for package: libselinux-2.5-11.el7.i686
---> Package libsodium.x86_64 0:1.0.18-1.el7 will be installed
---> Package libtommath.x86_64 0:0.42.0-5.el7 will be installed
---> Package openpgm.x86_64 0:5.2.122-2.el7 will be installed
---> Package pam.i686 0:1.1.8-18.el7 will be installed
--> Processing Dependency: libdb-5.3.so for package: pam-1.1.8-18.el7.i686
--> Processing Dependency: libcrack.so.2 for package: pam-1.1.8-18.el7.i686
--> Processing Dependency: libaudit.so.1 for package: pam-1.1.8-18.el7.i686
---> Package python-backports.x86_64 0:1.0-8.el7 will be installed
---> Package systemd-python.x86_64 0:219-42.el7_4.10 will be installed
--> Processing Dependency: systemd = 219-42.el7_4.10 for package: systemd-python-219-42.el7_4.10.x86_64
---> Package xz-libs.i686 0:5.2.2-1.el7 will be installed
--> Running transaction check
---> Package audit-libs.i686 0:2.7.6-3.el7 will be installed
--> Processing Dependency: libcap-ng.so.0 for package: audit-libs-2.7.6-3.el7.i686
---> Package bzip2-libs.i686 0:1.0.6-13.el7 will be installed
---> Package cracklib.i686 0:2.9.0-11.el7 will be installed
---> Package elfutils-libelf.i686 0:0.168-8.el7 will be installed
---> Package glibc.i686 0:2.17-196.el7_4.2 will be installed
--> Processing Dependency: glibc-common = 2.17-196.el7_4.2 for package: glibc-2.17-196.el7_4.2.i686
---> Package libattr.i686 0:2.4.46-12.el7 will be installed
---> Package libdb.i686 0:5.3.21-21.el7_4 will be installed
---> Package libsepol.i686 0:2.5-6.el7 will be installed
---> Package nss-softokn-freebl.i686 0:3.28.3-8.el7_4 will be installed
---> Package pcre.i686 0:8.32-17.el7 will be installed
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4.9) for package: pcre-8.32-17.el7.i686
--> Processing Dependency: libstdc++.so.6(GLIBCXX_3.4) for package: pcre-8.32-17.el7.i686
--> Processing Dependency: libstdc++.so.6(CXXABI_1.3) for package: pcre-8.32-17.el7.i686
--> Processing Dependency: libstdc++.so.6 for package: pcre-8.32-17.el7.i686
---> Package systemd-python.x86_64 0:219-42.el7_4.10 will be installed
--> Processing Dependency: systemd = 219-42.el7_4.10 for package: systemd-python-219-42.el7_4.10.x86_64
---> Package zlib.i686 0:1.2.7-17.el7 will be installed
--> Running transaction check
---> Package glibc.i686 0:2.17-196.el7_4.2 will be installed
--> Processing Dependency: glibc-common = 2.17-196.el7_4.2 for package: glibc-2.17-196.el7_4.2.i686
---> Package libcap-ng.i686 0:0.7.5-4.el7 will be installed
---> Package libstdc++.i686 0:4.8.5-16.el7_4.2 will be installed
---> Package systemd-python.x86_64 0:219-42.el7_4.10 will be installed
--> Processing Dependency: systemd = 219-42.el7_4.10 for package: systemd-python-219-42.el7_4.10.x86_64
--> Finished Dependency Resolution
Error: Package: systemd-python-219-42.el7_4.10.x86_64 (rhel-7-server-rpms)
           Requires: systemd = 219-42.el7_4.10
           Installed: systemd-219-42.el7_4.16.x86_64 (@rhel-7-server-eus-rpms)
               systemd = 219-42.el7_4.16
           Available: systemd-208-11.el7.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7
           Available: systemd-208-11.el7_0.2.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7_0.2
           Available: systemd-208-11.el7_0.4.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7_0.4
           Available: systemd-208-11.el7_0.5.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7_0.5
           Available: systemd-208-11.el7_0.6.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7_0.6
           Available: systemd-208-20.el7.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7
           Available: systemd-208-20.el7_1.2.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7_1.2
           Available: systemd-208-20.el7_1.3.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7_1.3
           Available: systemd-208-20.el7_1.5.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7_1.5
           Available: systemd-208-20.el7_1.6.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7_1.6
           Available: systemd-219-19.el7.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7
           Available: systemd-219-19.el7_2.4.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.4
           Available: systemd-219-19.el7_2.7.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.7
           Available: systemd-219-19.el7_2.9.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.9
           Available: systemd-219-19.el7_2.11.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.11
           Available: systemd-219-19.el7_2.12.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.12
           Available: systemd-219-19.el7_2.13.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.13
           Available: systemd-219-30.el7.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7
           Available: systemd-219-30.el7_3.3.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.3
           Available: systemd-219-30.el7_3.6.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.6
           Available: systemd-219-30.el7_3.7.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.7
           Available: systemd-219-30.el7_3.8.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.8
           Available: systemd-219-30.el7_3.9.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.9
           Available: systemd-219-42.el7.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7
           Available: systemd-219-42.el7_4.1.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.1
           Available: systemd-219-42.el7_4.4.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.4
           Available: systemd-219-42.el7_4.6.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.6
           Available: systemd-219-42.el7_4.7.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.7
           Available: systemd-219-42.el7_4.10.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.10
Error: Package: glibc-2.17-196.el7_4.2.i686 (rhel-7-server-rpms)
           Requires: glibc-common = 2.17-196.el7_4.2
           Installed: glibc-common-2.17-196.el7_4.3.x86_64 (@rhel-7-server-eus-rpms)
               glibc-common = 2.17-196.el7_4.3
           Available: glibc-common-2.17-55.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-55.el7
           Available: glibc-common-2.17-55.el7_0.1.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-55.el7_0.1
           Available: glibc-common-2.17-55.el7_0.3.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-55.el7_0.3
           Available: glibc-common-2.17-55.el7_0.5.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-55.el7_0.5
           Available: glibc-common-2.17-78.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-78.el7
           Available: glibc-common-2.17-105.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-105.el7
           Available: glibc-common-2.17-106.el7_2.1.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-106.el7_2.1
           Available: glibc-common-2.17-106.el7_2.4.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-106.el7_2.4
           Available: glibc-common-2.17-106.el7_2.6.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-106.el7_2.6
           Available: glibc-common-2.17-106.el7_2.8.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-106.el7_2.8
           Available: glibc-common-2.17-157.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7
           Available: glibc-common-2.17-157.el7_3.1.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7_3.1
           Available: glibc-common-2.17-157.el7_3.2.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7_3.2
           Available: glibc-common-2.17-157.el7_3.4.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7_3.4
           Available: glibc-common-2.17-157.el7_3.5.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7_3.5
           Available: glibc-common-2.17-196.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-196.el7
           Available: glibc-common-2.17-196.el7_4.2.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-196.el7_4.2
**********************************************************************
yum can be configured to try to resolve such errors by temporarily enabling
disabled repos and searching for missing dependencies.
To enable this functionality please set 'notify_only=0' in /etc/yum/pluginconf.d/search-disabled-repos.conf
**********************************************************************

 You could try using --skip-broken to work around the problem
 You could try running: rpm -Va --nofiles --nodigest
Uploading Enabled Repositories Report
Loaded plugins: product-id, subscription-managerError: Package: systemd-python-219-42.el7_4.10.x86_64 (rhel-7-server-rpms)
           Requires: systemd = 219-42.el7_4.10
           Installed: systemd-219-42.el7_4.16.x86_64 (@rhel-7-server-eus-rpms)
               systemd = 219-42.el7_4.16
           Available: systemd-208-11.el7.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7
           Available: systemd-208-11.el7_0.2.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7_0.2
           Available: systemd-208-11.el7_0.4.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7_0.4
           Available: systemd-208-11.el7_0.5.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7_0.5
           Available: systemd-208-11.el7_0.6.x86_64 (rhel-7-server-rpms)
               systemd = 208-11.el7_0.6
           Available: systemd-208-20.el7.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7
           Available: systemd-208-20.el7_1.2.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7_1.2
           Available: systemd-208-20.el7_1.3.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7_1.3
           Available: systemd-208-20.el7_1.5.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7_1.5
           Available: systemd-208-20.el7_1.6.x86_64 (rhel-7-server-rpms)
               systemd = 208-20.el7_1.6
           Available: systemd-219-19.el7.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7
           Available: systemd-219-19.el7_2.4.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.4
           Available: systemd-219-19.el7_2.7.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.7
           Available: systemd-219-19.el7_2.9.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.9
           Available: systemd-219-19.el7_2.11.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.11
           Available: systemd-219-19.el7_2.12.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.12
           Available: systemd-219-19.el7_2.13.x86_64 (rhel-7-server-rpms)
               systemd = 219-19.el7_2.13
           Available: systemd-219-30.el7.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7
           Available: systemd-219-30.el7_3.3.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.3
           Available: systemd-219-30.el7_3.6.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.6
           Available: systemd-219-30.el7_3.7.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.7
           Available: systemd-219-30.el7_3.8.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.8
           Available: systemd-219-30.el7_3.9.x86_64 (rhel-7-server-rpms)
               systemd = 219-30.el7_3.9
           Available: systemd-219-42.el7.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7
           Available: systemd-219-42.el7_4.1.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.1
           Available: systemd-219-42.el7_4.4.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.4
           Available: systemd-219-42.el7_4.6.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.6
           Available: systemd-219-42.el7_4.7.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.7
           Available: systemd-219-42.el7_4.10.x86_64 (rhel-7-server-rpms)
               systemd = 219-42.el7_4.10
Error: Package: glibc-2.17-196.el7_4.2.i686 (rhel-7-server-rpms)
           Requires: glibc-common = 2.17-196.el7_4.2
           Installed: glibc-common-2.17-196.el7_4.3.x86_64 (@rhel-7-server-eus-rpms)
               glibc-common = 2.17-196.el7_4.3
           Available: glibc-common-2.17-55.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-55.el7
           Available: glibc-common-2.17-55.el7_0.1.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-55.el7_0.1
           Available: glibc-common-2.17-55.el7_0.3.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-55.el7_0.3
           Available: glibc-common-2.17-55.el7_0.5.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-55.el7_0.5
           Available: glibc-common-2.17-78.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-78.el7
           Available: glibc-common-2.17-105.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-105.el7
           Available: glibc-common-2.17-106.el7_2.1.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-106.el7_2.1
           Available: glibc-common-2.17-106.el7_2.4.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-106.el7_2.4
           Available: glibc-common-2.17-106.el7_2.6.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-106.el7_2.6
           Available: glibc-common-2.17-106.el7_2.8.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-106.el7_2.8
           Available: glibc-common-2.17-157.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7
           Available: glibc-common-2.17-157.el7_3.1.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7_3.1
           Available: glibc-common-2.17-157.el7_3.2.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7_3.2
           Available: glibc-common-2.17-157.el7_3.4.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7_3.4
           Available: glibc-common-2.17-157.el7_3.5.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-157.el7_3.5
           Available: glibc-common-2.17-196.el7.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-196.el7
           Available: glibc-common-2.17-196.el7_4.2.x86_64 (rhel-7-server-rpms)
               glibc-common = 2.17-196.el7_4.2non-zero return code

**Comment by frogunder** [comment]
@karkey83 thank you for reporting this issue.
I am not able to replicate this error.

Do you mind trying to install salt with instructions from our Package repo and see it that works for you? 
http://repo.saltstack.com/

Thanks.
