### ISSUE TITLE
Double Quoting backslashes and numbers fails in a grains file

### ISSUE THREAD

**Issue by xenadmin** [saltstack/salt#54244]
### Description of Issue
I'm trying to build a custom grains file. I set some sane defaults in the top, which will solve 80% of my use-cases. Later I override them via IF, as special hosts need a different setting. This will later be used in a custom state where I build a config file. 

### Setup
```
{% set agentshare = "\\\zabprox\\zabbix-agent" %}
{% set agentbat = "\\\zabprox\\zabbix-agent\\InstallZabbixAgent.bat" %}
{% set updateuser = "SYSTEM" %}
{% set updatepassword = "" %}

{% if grains['id'] == 'zabprox.HOST.de' %}
  {% set agentshare = "\\\10.193.105.253\zabbix-agent$" %}
{% endif %}

zabbix-config-bat:
  agentshare: {{ agentshare }}
  agentbat: {{ agentbat }}
  updateuser: {{ updateuser }}
  updatepassword: {{ updatepassword }}
```
**Result:**
```
root@salt:/srv# salt 'zabprox.HOST.de' pillar.items zabbix-config-bat
zabprox.HOST.de:
    ----------
    zabbix-config-bat:
        ----------
        agentbat:
            \\zabprox\zabbix-agent\InstallZabbixAgent.bat
        agentshare:
            \10.193.105.253\zabbix-agent$
        updatepassword:
            None
        updateuser:
            SYSTEM
```
Notice that the line `agentshare:` has only one starting backslash, while it should have two? If you compare it to the line with `agentbat:` which is defined in the top block and not overwritten by the IF block, you can see it worked, resulting in two backslashes. Although I write something similar in the IF block, compared to the top block, the results differ. But worse If I write it the same, the SLS render will fail, telling me I use not allowed characters:
```
2019-08-17 15:44:23,491 [salt.pillar      :735 ][CRITICAL][32455] Rendering SLS 'zabbix.config-bat' failed, render error:
unacceptable character #x0008: special characters are not allowed
  in "<unicode string>", position 45
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 730, in render_pstate
    **defaults)
  File "/usr/lib/python3/dist-packages/salt/template.py", line 93, in compile_template
    ret = render(input_data, saltenv, sls, **render_kwargs)
  File "/usr/lib/python3/dist-packages/salt/renderers/yaml.py", line 53, in render
    data = load(yaml_data, Loader=get_yaml_loader(argline))
  File "/usr/lib/python3/dist-packages/salt/utils/yamlloader.py", line 215, in load
    return yaml.load(stream, Loader=Loader)
  File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 70, in load
    loader = Loader(stream)
  File "/usr/lib/python3/dist-packages/salt/renderers/yaml.py", line 38, in yaml_loader
    return SaltYamlSafeLoader(*args, dictclass=OrderedDict)
  File "/usr/lib/python3/dist-packages/salt/utils/yamlloader.py", line 42, in __init__
    super(SaltYamlSafeLoader, self).__init__(stream)
  File "/usr/lib/python3/dist-packages/yaml/loader.py", line 24, in __init__
    Reader.__init__(self, stream)
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 74, in __init__
    self.check_printable(stream)
  File "/usr/lib/python3/dist-packages/yaml/reader.py", line 144, in check_printable
    'unicode', "special characters are not allowed")
yaml.reader.ReaderError: unacceptable character #x0008: special characters are not allowed
  in "<unicode string>", position 45
2019-08-17 15:44:23,497 [salt.pillar      :1018][CRITICAL][32455] Pillar render error: Rendering SLS 'zabbix.config-bat' failed. Please see master log for details.
```
### Steps to Reproduce Issue
Create a grains file. Set a variable outside and inside an if block. Use Backslashes inside the variable content. 
By now I'm totally confused. I tried several variants and sometimes it fails, and sometimes it doesn't. I don't see a pattern, yet. 
This is just an example, obviously I've only tested this while one line was active:
```
{% if grains['id'] == 'zabprox.HOST.de' %}
  {% set agentshare = "\\\zabprox\\zabbix-agent" %} <- Works
  {% set agentshare = "\\\zab\\zabbix-agent" %} <- Works
  {% set agentshare = '"\\\111\\zabbix-agent"' %} <- Doesn't work, results in a Roman "I"
  {% set agentshare = "\\\10\\zabbix-agent$" %} <- Doesn't work. I start to question myself if the number in the "" is my problem. Anyway trying single quotes now.
  {% set agentshare = '\\\zabprox\\zabbix-agent' %} <- Works
  {% set agentshare = '\\\z\\zabbix-agent' %} <- Works
  {% set agentshare = '\\\10\\zabbix-agent' %} <- Doesn't work. This is killing me. 
{% endif %}
```
So I narrowed it down I guess. As soon as I write double backslash AND numbers in double quotes, that state will fail. Due to my understanding, the normal way to resolve this would be double quotes. So is this my error or a real issue?
### Solution
I solved this myself, for me it just wasn't obvious, so I leave this here for others who might search for it. As far as I understand it, I have to use single quotes to escape numbers which are following backslashes. But I still have to escape each single backslash although I'm using quotes. That's what I don't understand. But now it works:
```
{% if grains['id'] == 'zabprox.HOST.de' %}
  {% set agentshare = '\\\\10.193.105.253\\zabbix-agent$' %}
{% endif %}

root@salt:/srv# salt 'zabprox.HOST.de' saltutil.refresh_pillar && salt 'zabprox.HOST.de' pillar.items zabbix-config-bat
zabprox.HOST.de:
    True
zabprox.HOST.de:
    ----------
    zabbix-config-bat:
        ----------
        agentbat:
            \\zabprox\zabbix-agent\InstallZabbixAgent.bat
        agentshare:
            \\10.193.105.253\zabbix-agent$
        updatepassword:
            None
        updateuser:
            SYSTEM
```
### Versions Report
```
root@salt:/srv# salt --versions-report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9
```

**Comment by frogunder** [comment]
@xenadmin thank you for reporting this issue.

I am able to replicate it. I will reach out to the core team for input on this issue.
@saltstack/team-core any thoughts on this?

Thanks.

**Comment by xenadmin** [comment]
Hi @frogunder and thank you very much for your reply. Did you also read my section about a solution? After I worked out how to "solve" this by using single quotes and escaping each backslash with another backslash, everything worked out. But I'm far from being able to understand, if I just found a workaround for a real bug, or if I was doing it wrong right from the start. Can you explain me which is the case? Thank you!

**Comment by waynew** [comment]
@xenadmin Hey, thanks for reaching out!

This can be super confusing behavior because it's not apparently consistent. And to make matters worse, it's possible that Jinja renders the text and then YAML *also* renders it.

With a string like this:

    \\\zabprox\zabbix\

The reason it's working like you *think* it should is because there's no escape sequence `\z`. If you change this to `\\\tabprox\zabbix` you'll see a very different result! That's because `\t` is a tab escape. Same for `\n`, but newline.

The rule to remember is that if you want a `\` then you must have `\\` everywhere you want one. You've seen that it will occasionally work by accident, but it's not a guarantee.

If you want to get this:

    \\zabprox\zabbix-agent\InstallZabbixAgent.bat

into the proper form, the easiest way is actually just to use Python.

```
>>> r'\\zabprox\zabbix-agent\InstallZabbixAgent.bat'
'\\\\zabprox\\zabbix-agent\\InstallZabbixAgent.bat'
```

Unfortunately Jinja doesn't appear to have the `r` prefix for strings or you could just use that.

Though, FWIW, most of the time in Windows environments they actually do support/translate `/` to `\` for you, so you could possibly use `//zabprox/zabbix-agent/` instead.

HTH!
