### ISSUE TITLE
salt-key throws Error: 'ascii' codec can't decode byte

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#54262]
### Description of Issue
I have a minion that I cannot delete the key of.

    salt-key -d MINION 
    Error: 'ascii' codec can't decode byte 0xc2 in position 15: ordinal not in range(128)

### Versions Report
`salt --versions-report`

Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by frogunder** [comment]
@markuskramerIgitt thank you for reporting this issue.

I can only replicate this issue when doing `salt-key -d <unicode character>`.
But the key is not accepted, its just an empty run.
```
[root@server-01 master]# salt-key -d Æ
Error: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```

```
[root@server-01 master]# salt-key
Accepted Keys:
Denied Keys:
Unaccepted Keys:
Rejected Keys:
[root@server-01 master]# salt-key -d test
The key glob 'test' does not match any unaccepted keys.
[root@server-01 master]# salt-key -d Æ
Error: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
[root@server-01 master]# salt-key -d testÆ
Error: 'ascii' codec can't decode byte 0xc3 in position 4: ordinal not in range(128)
```
Just to be clear, are you trying to delete an accepted key? 
What is the name of the key you are trying to delete?
Do you maybe have an unicode character in your minion name?

Thanks.

**Comment by markuskramerIgitt** [comment]
Cannot reproduce
