### ISSUE TITLE
git pillar test failures 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54271]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-ubuntu-1604-py2/158/

**Comment by KChandrashekhar** [comment]
https://github.com/saltstack/salt/pull/54252

**Comment by s0undt3ch** [comment]
This is fixed. We now have better insight when it fails https://github.com/saltstack/salt/issues/54337
