### ISSUE TITLE
MacOS user.present inconsistent behavior for createhome

### ISSUE THREAD

**Issue by Volune** [saltstack/salt#54288]
Found in the code:

On one side, it says `createhome` is not supported:
https://github.com/saltstack/salt/blob/develop/salt/states/user.py#L494-L496
(looking at the commit, it seems the reason is "because the doc says so")

On the other side, it is supported:
https://github.com/saltstack/salt/blob/develop/salt/modules/mac_user.py#L129-L130

**Comment by sagetherage** [comment]
@garethgreenaway I don't know if this was fixed or not, can you follow up, please?

**Comment by garethgreenaway** [comment]
Need to re-open the PR for this one against the master branch.

**Comment by sagetherage** [comment]
merged into master closing
