### ISSUE TITLE
[bug report salt-2019-2.0] salt-minion --config-dir takes no effect to pki files.

### ISSUE THREAD

**Issue by xq2248** [saltstack/salt#54289]
my salt minion config dir has been moved to /etc/salt2019,  as follows:
./bin/salt-minion --daemon --config-dir='/etc/salt2019'
After master accept the minion key,  the minion.pem, minion.pub,minion_master.pub are still stored in /etc/salt/pki/minion/,  not in /etc/salt2019/pki/minion. Maybe this is a bug? 

host-10-47-231-53:/etc/salt2019/pki/minion # ll
total 0

host-10-47-231-53:/etc/salt2019/pki/minion #  ll ../../../salt/pki/minion/
total 12
-r-------- 1 root root 1678 Aug 23 19:16 minion.pem
-rw-r--r-- 1 root root  450 Aug 23 19:16 minion.pub
-rw-r--r-- 1 root root  451 Aug 23 19:19 minion_master.pub

host-10-47-231-53:~/miniconda3 # ./bin/salt-minion --daemon --config-dir='/etc/salt2019'
host-10-47-231-53:~/miniconda3 # ./bin/salt-minion -V
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 |Continuum Analytics, Inc.| (default, Jul  2 2016, 17:53:06)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

**Comment by frogunder** [comment]
@xq2248 Thank you for reporting this issue. I will check with the core team if this is expected behavior or a bug.

@saltstack/team-core Anybody have any thoughts on this?

Thanks.

**Comment by waynew** [comment]
I believe you have to config either the pki dir or the root dir: https://docs.saltstack.com/en/latest/ref/configuration/master.html#root-dir

**Comment by xq2248** [comment]
@waynew Thanks. That's it.
