### ISSUE TITLE
postfix.show_queue failing with UnboundLocalError

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#54298]
### Description of Issue
When I run "salt 'mail*' postfix.show_queue I get the following error:

>
      The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/modules/postfix.py", line 356, in show_queue
        queue.append({'queue_id': queue_id, 'size': size, 'timestamp': timestamp, 'sender': sender, 'recipient': recipient})
    UnboundLocalError: local variable 'queue_id' referenced before assignment

### Setup
[root@salt-master]# salt 'mail*' postfix.show_queue

### Steps to Reproduce Issue

> [DEBUG   ] Reading configuration from /etc/salt/master
> [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-2p-master.example.com
> [DEBUG   ] Missing configuration file: /root/.saltrc
> [DEBUG   ] Configuration file path: /etc/salt/master
> [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
> [DEBUG   ] Reading configuration from /etc/salt/master
> [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt-2p-master.example.com
> [DEBUG   ] Missing configuration file: /root/.saltrc
> [DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
> [DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
> [DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'/etc/salt/pki/master', u'salt-2p-master.example.com_master', u'tcp://127.0.0.1:4506', u'clear')
> [DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
> [DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
> [DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
> [DEBUG   ] LazyLoaded local_cache.get_load
> [DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/c1/7da33981f6d518e5d3b3afa68996f06c4cbaafa3a9518505195aad85cd6a4c/.minions.p
> [DEBUG   ] get_iter_returns for jid 20190823171050219361 sent to set(['mail-1p-in-w2.example.com', 'mail-1p-in-w1.example.com', 'mail-1p-in-t2.example.com', 'mail-1p-in-t1.example.com']) will timeout at 17:11:50.267177
> [DEBUG   ] jid 20190823171050219361 return from mail-1p-in-w2.example.com
> [DEBUG   ] return event: {u'mail-1p-in-w2.example.com': {u'jid': u'20190823171050219361', u'ret': u'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/modules/postfix.py", line 356, in show_queue\n    queue.append({\'queue_id\': queue_id, \'size\': size, \'timestamp\': timestamp, \'sender\': sender, \'recipient\': recipient})\nUnboundLocalError: local variable \'queue_id\' referenced before assignment\n', u'out': u'nested'}}
> [DEBUG   ] LazyLoaded nested.output
> mail-1p-in-w2.example.com:
>     The minion function caused an exception: Traceback (most recent call last):
>       File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return
>         return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
>         return func(*args, **kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/modules/postfix.py", line 356, in show_queue
>         queue.append({'queue_id': queue_id, 'size': size, 'timestamp': timestamp, 'sender': sender, 'recipient': recipient})
>     UnboundLocalError: local variable 'queue_id' referenced before assignment
> [DEBUG   ] jid 20190823171050219361 return from mail-1p-in-t1.example.com
> [DEBUG   ] return event: {u'mail-1p-in-t1.example.com': {u'jid': u'20190823171050219361', u'ret': u'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/modules/postfix.py", line 356, in show_queue\n    queue.append({\'queue_id\': queue_id, \'size\': size, \'timestamp\': timestamp, \'sender\': sender, \'recipient\': recipient})\nUnboundLocalError: local variable \'queue_id\' referenced before assignment\n', u'out': u'nested'}}
> [DEBUG   ] LazyLoaded nested.output
> mail-1p-in-t1.example.com:
>     The minion function caused an exception: Traceback (most recent call last):
>       File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return
>         return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
>         return func(*args, **kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/modules/postfix.py", line 356, in show_queue
>         queue.append({'queue_id': queue_id, 'size': size, 'timestamp': timestamp, 'sender': sender, 'recipient': recipient})
>     UnboundLocalError: local variable 'queue_id' referenced before assignment
> [DEBUG   ] jid 20190823171050219361 return from mail-1p-in-w1.example.com
> [DEBUG   ] return event: {u'mail-1p-in-w1.example.com': {u'jid': u'20190823171050219361', u'ret': u'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/modules/postfix.py", line 356, in show_queue\n    queue.append({\'queue_id\': queue_id, \'size\': size, \'timestamp\': timestamp, \'sender\': sender, \'recipient\': recipient})\nUnboundLocalError: local variable \'queue_id\' referenced before assignment\n', u'out': u'nested'}}
> [DEBUG   ] LazyLoaded nested.output
> mail-1p-in-w1.example.com:
>     The minion function caused an exception: Traceback (most recent call last):
>       File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return
>         return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
>         return func(*args, **kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/modules/postfix.py", line 356, in show_queue
>         queue.append({'queue_id': queue_id, 'size': size, 'timestamp': timestamp, 'sender': sender, 'recipient': recipient})
>     UnboundLocalError: local variable 'queue_id' referenced before assignment
> [DEBUG   ] jid 20190823171050219361 return from mail-1p-in-t2.example.com
> [DEBUG   ] return event: {u'mail-1p-in-t2.example.com': {u'jid': u'20190823171050219361', u'ret': u'The minion function caused an exception: Traceback (most recent call last):\n  File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return\n    return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute\n    return func(*args, **kwargs)\n  File "/usr/lib/python2.7/site-packages/salt/modules/postfix.py", line 356, in show_queue\n    queue.append({\'queue_id\': queue_id, \'size\': size, \'timestamp\': timestamp, \'sender\': sender, \'recipient\': recipient})\nUnboundLocalError: local variable \'queue_id\' referenced before assignment\n', u'out': u'nested'}}
> [DEBUG   ] LazyLoaded nested.output
> mail-1p-in-t2.example.com:
>     The minion function caused an exception: Traceback (most recent call last):
>       File "/usr/lib/python2.7/site-packages/salt/minion.py", line 1637, in _thread_return
>         return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/executors/direct_call.py", line 12, in execute
>         return func(*args, **kwargs)
>       File "/usr/lib/python2.7/site-packages/salt/modules/postfix.py", line 356, in show_queue
>         queue.append({'queue_id': queue_id, 'size': size, 'timestamp': timestamp, 'sender': sender, 'recipient': recipient})
>     UnboundLocalError: local variable 'queue_id' referenced before assignment
> [DEBUG   ] jid 20190823171050219361 found all minions set([u'mail-1p-in-w2.example.com', u'mail-1p-in-w1.example.com', u'mail-1p-in-t2.example.com', u'mail-1p-in-t1.example.com'])

### Versions Report
Salt Master:
    Salt Version:
               Salt: 2018.3.4
     
    Dependency Versions:
               cffi: 1.6.0
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: 0.6.4
          gitpython: 1.0.1
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: 0.26.3
            libnacl: Not Installed
           M2Crypto: 0.31.0
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.14
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: 0.26.4
             Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
       python-gnupg: 0.4.3
             PyYAML: 3.11
              PyZMQ: 14.7.0
               RAET: Not Installed
              smmap: 0.9.0
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7.6.1810 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-957.27.2.el7.x86_64
             system: Linux
            version: CentOS Linux 7.6.1810 Core

Salt Minions:

    Salt Version:
               Salt: 2018.3.4
     
    Dependency Versions:
               cffi: Not Installed
           cherrypy: Not Installed
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
              ioflo: Not Installed
             Jinja2: 2.7.2
            libgit2: Not Installed
            libnacl: Not Installed
           M2Crypto: 0.21.1
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
       python-gnupg: 0.4.3
             PyYAML: 3.11
              PyZMQ: 14.7.0
               RAET: Not Installed
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.2.1
                ZMQ: 4.1.4
     
    System Versions:
               dist: centos 7.6.1810 Core
             locale: UTF-8
            machine: x86_64
            release: 3.10.0-957.21.3.el7.x86_64
             system: Linux
            version: CentOS Linux 7.6.1810 Core

**Comment by racooper** [comment]
Good grief, I finally got around to testing.  The patched module seems to be working a lot better.

**Comment by racooper** [comment]
ah...though I may have found a typo, line 342: 

queue_id, size, timestatmp, sender, recipient = None, None, None, None, None

should probably be "timestamp" instead of "timestatmp"

**Comment by sagetherage** [comment]
@garethgreenaway let's take the PR from 2018.3 and correct the spelling error and get that one fix into `Sodium` - if there are more issues, let's open tickets for them individually or at least broken up in some way, perhaps in code blocks of smaller PRs to correct @racooper if you can help with that it would be much appreciated, also if you want to take @garethgreenaway PR and make corrections in a PR we will get it reviewed.
