### ISSUE TITLE
VMWare cluster cloud tests are failing due to 404 errors 

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54292]
### Description of Issue
- [x] VMware cluster image update
- [ ] put packer so that it’s updated regularly
- [ ] Decide the frequency of update

Test failing: 
https://jenkinsci.saltstack.com/job/2019.2.1/view/Cloud/job/salt-centos-7-py2-cloud/180/

**Comment by bryceml** [comment]
we need to decide if it's worth having a packer build specifically for this.  as far as I can tell, its just a base install of centos7 with open-vm-tools installed.  We could probably just use the existing packer job we have that generates the centos7 template that is on vsphere already: https://github.com/saltstack/os-imager/tree/master/VMware/centos/
