### ISSUE TITLE
Update VMWare/vSphere documentation for upcoming feature 

### ISSUE THREAD

**Issue by xeacott** [saltstack/salt#54294]
This issue is to ensure documentation is added about the new vCenter features coming for tagging and related abilities. This should, at minimum, specify that the python package **vSphere-Automation-SDK** is required to use these features. The current version of this SDK is 1.3.0.

The package can be pip installed, and the information for this is from the github page found [here](https://github.com/vmware/vsphere-automation-sdk-python).

**Comment by sagetherage** [comment]
trying to get stale bot to not close this one

**Comment by sagetherage** [comment]
@saltstack/docs-working-group

**Comment by barbaricyawps** [comment]
This documentation request has been fulfilled by the following documentation: https://docs.saltproject.io/salt/extensions/salt-ext-modules-vmware/en/latest/ref/modules/saltext.vmware.modules.tag.html

Closing.
