### ISSUE TITLE
vt.py tries to call __detect_parent_terminal_size on windows but that is not defined 

### ISSUE THREAD

**Issue by LuAPi** [saltstack/salt#54290]
### Description of Issue
__detect_parent_terminal_size is called here:
https://github.com/saltstack/salt/blob/2018.3/salt/utils/vt.py#L141-L145
but is only defined on non-windows platforms here:
https://github.com/saltstack/salt/blob/2018.3/salt/utils/vt.py#L709
This caused some tests to fail in a PR I made https://jenkinsci.saltstack.com/job/pr-kitchen-windows2016-py3/job/PR-53404/19/testReport/junit/unit.utils.test_vt/VTTestCase/test_split_multibyte_characters_unicode/

I'm not sure on the preferred solution to this. I'm opening this issue to have an issue number to reference in the reason for disabling the test VT tests I wrote on windows.

### Setup
--

### Steps to Reproduce Issue
Instantiate a VT on windows.

### Versions Report
--

**Comment by frogunder** [comment]
@saltstack/team-windows FYI
