### ISSUE TITLE
Salt randomly times out when executing modules or applying states

### ISSUE THREAD

**Issue by purdel** [saltstack/salt#54330]
### Description of Issue
After updating from Salt 2018 to Py2 Salt 2019.2.0, timeouts started randomly appearing when issuing commands:

```bash
Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.
```

We have the same issue when running async as Salt doesn't return any jid, even though the command gets executed on the minion.

As already stated, this happens randomly. Salt works most of the time but this issue greatly impacts our work. 

### Setup
We tried increasing the `sock_pool_size` to 15 and the number of errors decreased (not sure if due to this setting or because we restarted the salt-master service).

### Steps to Reproduce Issue
Cannot provide steps as it happens randomly.

### Versions Report
```bash
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-95.29-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
```

**Comment by chforster** [comment]
Here is the log when "NOT" using async (e.g. here for pillar.item)

    Traceback (most recent call last):
      File "/scripts/mycron.py", line 64, in <module>
        pillars = client.cmd('G@opsrole:*web-1 or G@opsrole:*app-1', 'pillar.item',{'my:pillar:value'},  tgt_type='compound')
      File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 672, in cmd
    **kwargs)
      File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 349, in run_job
    raise SaltClientError(general_exception)
    salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. You may need to run your command with `--async` in order to bypass the congested event bus. With `--async`, the CLI tool will print the job id (jid) and exit immediately without listening for responses. You can then use `salt-run jobs.lookup_jid` to look up the results of the job in the job cache later.

**Comment by purdel** [comment]
@Ch3LL Sorry for the late reply. No memory leaks or high CPU load, nothing in the logs of either master or minion. The error usually occurs when executing long running processes like grabbing the pillar values from a long list of machines (see @chforster 's comment above) and sometimes even when executing something as simple as a `test.ping`.

**Comment by Ch3LL** [comment]
can you share a sanitized version of your configs?

Also how many minions are you targeting when you see this?

**Comment by Ch3LL** [comment]
do you still see the issue when you target a smaller subset of minions? like only 10? or even 1?

**Comment by purdel** [comment]
Yes, it also happens with only one target.

**Comment by purdel** [comment]
As this happened randomly, I've decided to monitor the Master's CPU and memory utilization over a longer stretch of time.

It turned out that the CPU was spiking at regular intervals to 100% for a minute or so. Tried executing a simple `test.ping` while this was happening and I finally managed to replicate the timeout issue.

A cronjob was set up to execute a Python script that gathered info from all the minions by means of the Salt Python API. The spike happened when trying to retrieve all the pillars from the entire minion pool: `pillars = client.cmd('*', 'pillar.items')` (please note that this used to work with Salt 2018).

I have brought the CPU usage down to 15% by using batches and calling `pillar.raw` instead of `pillar.items`.

```python
pillars = {}
pillar_generator = client.cmd_batch('*', 'pillar.raw', batch='5')
for pill in pillar_generator:
    pillars.update(pill)
```

With Salt 2019 running on Python 2, it seems that the CPU utilization is higher than on the previous version as even a `state.apply` sometimes brings it to 40%.

**Comment by Ch3LL** [comment]
I know there was some issues in 2019.2.0/1 that caused higher cpu utilization rates and affects the number of calls to pillar on each salt call, so I'm curious if 2019.2.2 when it comes out will help on the 2019.2 versions. It should be coming out within this week or next. you can monitor this issue to closely monitor the release https://github.com/saltstack/salt/issues/55009
