### ISSUE TITLE
salt '*' test.ping returns with <ERROR: Minions returned with non-zero exit code>

### ISSUE THREAD

**Issue by karkey83** [saltstack/salt#54341]
### Description of Issue
Recently we have upgraded to 2019.2.0 version. Since then I'm getting error when executing the test.ping from salt-master along with the minion result.

ERROR: Minions returned with non-zero exit code

I want to use the result of test.ping in my code for analysis but due to this error its not executing properly

is there any workaround for this issue?

### Steps to Reproduce Issue
Sample output:
salt '*' test.ping
minion1:
    True
minion2:
    True
minion3:
    True
minion4:
    Minion did not return. [Not connected]
minion5:
    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code

### Versions Report
2019.2.0

**Comment by gaetanquentin** [comment]
because salt master have keys of minions who do not exists any more, or theses minions are down.

sudo salt-run  manage.down removekeys=True will supress bad keys.

**Comment by karkey83** [comment]
Thanks @gaetanquentin for reply.

Is there any option to show all the minions which are connected (TRUE) , Minion did not return. [Not connected] and Minion did not return. [No Response] with the salt-master. 

As said I'm in the process of using script to validate the minion status (like prometheus exporter ) as and when required. Using that we can monitor the minions connectivity status in  a dashboard.

**Comment by gaetanquentin** [comment]
look at the manage doc: sudo salt-run -d manage

**Comment by karkey83** [comment]
It works.
Thanks for your help!!
