### ISSUE TITLE
Code coverage reports memory full issue

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54349]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-debian-8-py3/187/console

01:04:21         Test suite execution finalized with exit code: 0
01:04:22         nox > Command coverage run tests/runtests.py --tests-logfile=/tmp/kitchen/testing/artifacts/logs/runtests.log --transport=zeromq --output-columns=120 --sysinfo --xml=/tmp/kitchen/testing/artifacts/xml-unittests-output -v --run-destructive --ssh-tests failed with exit code -9
01:04:22         nox > coverage combine
01:05:31         nox > coverage xml -o /tmp/kitchen/testing/artifacts/coverage/coverage.xml
01:06:10         nox > Session runtests-parametrized-3(coverage=True, crypto=None, transport='zeromq') failed.
01:06:10         nox > Ran multiple sessions:
01:06:10         nox > * runtests-zeromq-3(coverage=True): success
01:06:10         nox > * runtests-parametrized-3(coverage=True, crypto=None, transport='zeromq'): failed
01:06:10  >>>>>> ------Exception-------
01:06:10  >>>>>> Class: Kitchen::ActionFailed
01:06:10  >>>>>> Message: 1 actions failed.
01:06:10  >>>>>>     Failed to complete #verify action: [SSH exited (1) for command: [sudo -E env CI=1 nox -f /tmp/kitchen/testing/noxfile.py -e 'runtests-zeromq-3(coverage=True)' -- --output-columns=120  --sysinfo --xml=/tmp/kitchen/testing/artifacts/xml-unittests-output -v --run-destructive --ssh-tests  ]] on py3-debian-8

**Comment by sagetherage** [comment]
closing this as we now know this is a Codecov issue
