### ISSUE TITLE
blackout tests cause hang in test suite sometimes

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54348]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-windows-2019-py3/186/

05:29:18         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
05:29:18         Starting integration.minion.test_blackout Tests
05:29:18         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
05:29:18         
05:29:18         Running tests...
05:29:18         ----------------------------------------------------------------------
05:29:18           test_blackout (integration.minion.test_blackout.MinionBlackoutTestCase)
13:09:34  Cancelling nested steps due to timeout
13:09:34  Sending interrupt signal to process

**Comment by LuAPi** [comment]
Same time out issue as https://github.com/saltstack/salt/issues/54182 ?
