### ISSUE TITLE
archive module doesn't use options reliably

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#54346]
### Description of Issue
When using the `archive` function to perform any operation that requires listing the contents of a simple tar archive (including `archive.list` and the `archive.extracted`state, and probably others), Salt doesn't actually use the command specified in the `options` parameter, even if the python tarfile module fails to read the file.

### Setup
Salt 2019.2.0 on Linux

### Steps to Reproduce Issue
1. Create a tar archive that the python `tarfile` module can't read (for example with `maven-assembly-plugin` version 2.3).
2. Try to list the contents of the file using the `tar` command (`tar -tvf /path/to/file.tar`); this succeeds.
3. Try to list the contents of the file using Salt (`salt-call --local archive.list /path/to/file.tar`); this fails because python's `tarfile` module can't read the file. Fair enough.
4. Try to read the file using the `options` parameter (`salt-call --local archive.list /path/to/file.tar options="tar -tvf"`); this also fails, and Salt doesn't even *try* to use the `tar` command.

**Comment by dmurphy18** [comment]
@V3XATI0N I have tried what you gave as an example, and was unable to repoduce the issue, using the latest Salt v3003 on an up to date Centos 7.

Downloaded maven-assembly-plugin-2.3-source-release.zip, created a tarball with tar.
```
tar -cvf test_tar.tar maven-assembly-plugin-2.3-source-release.zip
``` 
and then moved the maven-assembly-plugin-2.3-source-release.zip to an arch directory
```
root@Unknown:/srv/salt/archive_test# salt-call --local archive.list salt://archive_test/test_tar.tar
local:
    - maven-assembly-plugin-2.3-source-release.zip
root@Unknown:/srv/salt/archive_test# salt-call --local archive.list salt://archive_test/test_tar.tar options='tar -tvf'
local:
    - maven-assembly-plugin-2.3-source-release.zip
root@Unknown:/srv/salt/archive_test# salt-call --local archive.list salt://archive_test/arch/maven-assembly-plugin-2.3-source-release.zip
local:
    - maven-assembly-plugin-2.3/
    - maven-assembly-plugin-2.3/DEPENDENCIES
    - maven-assembly-plugin-2.3/LICENSE
    - maven-assembly-plugin-2.3/NOTICE
    - maven-assembly-plugin-2.3/integration-test-archetype/
    - maven-assembly-plugin-2.3/integration-test-archetype/pom.xml
    - maven-assembly-plugin-2.3/integration-test-archetype/src/
...
    - maven-assembly-plugin-2.3/src/test/java/org/apache/maven/plugin/assembly/utils/ProjectUtilsTest.java
    - maven-assembly-plugin-2.3/src/test/java/org/apache/maven/plugin/assembly/utils/TypeConversionUtilsTest.java
    - maven-assembly-plugin-2.3/src/test/resources/
    - maven-assembly-plugin-2.3/src/test/resources/assemblies/
    - maven-assembly-plugin-2.3/src/test/resources/assemblies/empty.xml
root@Unknown:/srv/salt/archive_test# 
```
Can you provide the versions-report for the system you were using, in order to better identify the issue.
Retry with the latest version of Salt, and perhaps attach an example of a file which exhibits the issue.
