### ISSUE TITLE
Sporadical KeyError produced on minion with salt module ps.proc_info

### ISSUE THREAD

**Issue by aionita81** [saltstack/salt#54358]
### Description of Issue
sporadically command:

`salt <target> ps.proc_info <pid>`

produces errors on the minions, more specifically KeyError as below:
```
2019-08-06 12:32:46,717 [salt.master :1532][ERROR ][70] Received minion error from [VAPONDEM01AX101]: The minion function caused an exception
2019-08-06 12:32:46,775 [salt.crypt :1429][DEBUG ][35] Failed to authenticate message
2019-08-06 12:32:46,776 [salt.utils.job :68 ][INFO ][35] Got return from VAPONDEM01AX101 for job 20190806123229623133
2019-08-06 12:32:46,776 [salt.utils.event :744 ][DEBUG ][35] Sending event: tag = salt/job/20190806123229623133/ret/VAPONDEM01AX101; data =
{'id': 'VAPONDEM01AX101', 'success': False, 'jid': '20190806123229623133', 'fun': 'ps.proc_info', 'fun_args': [55588], 'out': 'nested', 'cmd': '_return', 'return': 'The minion function caused an exception: Traceback (most recent call last):\n File "c:\\salt\\bin\\lib\\site-packages\\salt_ _minion.py", line 1637, in _thread_return\n return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)\n File "c:\\salt\\bin\\lib\\site-packages\\salt\\executors_ _direct_call.py", line 12, in execute\n return func(*args, **kwargs)\n File "c:\\salt\\bin\\lib\\site-packages\\salt\\modules_ _ps.py", line 215, in proc_info\n return proc.as_dict(attrs)\n File "c:\\salt\\bin\\lib\\site-packages\\psutil_ ___init__.py", line 563, in as_dict\n ret = meth()\n File "c:\\salt\\bin\\lib\\site-packages\\psutil_ ___init__.py", line 1196, in open_files\n return self._proc.open_files()\n File "c:\\salt\\bin\\lib\\site-packages\\psutil _pswindows.py", line 620, in wrapper\n return fun(self, *args, **kwargs)\n File "c:\\salt\\bin\\lib\\site-packages\\psutil _pswindows.py", line 854, in open_files\n _file = convert_dos_path(_file)\nKeyError: (\'\\\\Device\\\\HarddiskVolume4\\\\Program Files\\\\Java\\\\jdk-11.0.2\\\\bin\\\\api-ms-win-crt-math-l1-1-0.dll\',)\n', '_stamp': '2019-08-06T12:32:46.776795'} 
```

I looked a bit in the python code bundled with salt from the minion  :
- in file c:\\salt\\bin\\lib\\site-packages\\psutil_pswindows.py 
-the function: def convert_dos_path(s): 
will produce the KeyError (e.g.: KeyError: (\'\\\\\\\\Device\\\\\\\\HarddiskVolume4\\\\\\\\Program Files\\\\\\\\Java\\\\\\\\jdk-11.0.2\\\\\\\\bin\\\\\\\\api-ms-win-crt-math-l1-1-0.dll\', )when it will receive paths with  '\\\\\\\\' ( 4 backslashes). It assumes that all windows paths should contain only two backslashes: '\\\\'

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.9.76-3.78.amzn1.x86_64
         system: Linux
        version: Ubuntu 18.04 bionic

Master version = minion version

**Comment by Ch3LL** [comment]
ping @twangboy can you take a look here? seems we just need to allow more than 2 backslashes in the path?

**Comment by Ch3LL** [comment]
This looks to be an upstream issue to me since psutil's is the one raising the keyerror

**Comment by Ch3LL** [comment]
Closing as this looks to be an upstream issue, if you think this is not an upstream issue and are still running into the issue on the latest release of Salt 3006.3 please open a new issue with the details.
