### ISSUE TITLE
integration.netapi.test_client.NetapiClientTest.test_local

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54389]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/job/salt-centos-6-py2/198/

Error Message

{u'minion': True, 'sub_minion': False} != {u'minion': True, u'sub_minion': True} - {u'minion': True, 'sub_minion': False} ?                                 ^^^^  + {u'minion': True, u'sub_minion': True} ?                   +              ^^^ 
Stacktrace

Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/integration/netapi/test_client.py", line 44, in test_local
    self.assertEqual(ret, {'minion': True, 'sub_minion': True})
AssertionError: {u'minion': True, 'sub_minion': False} != {u'minion': True, u'sub_minion': True}
- {u'minion': True, 'sub_minion': False}
?                                 ^^^^

+ {u'minion': True, u'sub_minion': True}
?                   +              ^^^

**Comment by Ch3LL** [comment]
`integration.netapi.test_client.NetapiClientTest.test_local` is the first test to run in the test suite. One thing i've found so far through my investigation is that the syndic is still starting up even when this test starts.

1. `05:02:38,608 [tests.support.processes                :176 ][INFO    ] [salt-syndic/syndic] The pytest salt-syndic(syndic) is running and accepting commands after 1 attempts`

at 5:02:38 we can see pytest thinks the syndic is up and running

2. `05:02:51,276 [tests.support.xmlunit                  :59  ][DEBUG   ] >>>>> START >>>>> integration.netapi.test_client.NetapiClientTest.test_local 05:02:51,276 [salt.config `

The very first test then starts running at 5:02:51

But then we see the syndic still starting up while this test is running:

3. `05:03:07,523 [salt.cli.daemons                       :85  ][INFO    ] Starting up the Salt Syndic`
and the start events being shown:

`05:03:08,055 [salt.utils.event                       :738 ][DEBUG   ] Sending event: tag = salt/master/syndic_master/start;`

The test then finishes with failure here

4. `05:03:13,968 [tests.support.xmlunit                  :71  ][DEBUG   ] <<<<< END <<<<<<< integration.netapi.test_client.NetapiClientTest.test_local`

Im not certain if this is the cause for the failure, but noting here for now while i still investigate

**Comment by Ch3LL** [comment]
ping @s0undt3ch have you ever seen the above? any ideas on how we can ensure its not starting up in the middle of a test?

**Comment by KChandrashekhar** [comment]
Not a release blocker.

**Comment by dwoz** [comment]
These are now failing on py2-fedora-30
https://jenkinsci.saltstack.com/job/pr-kitchen-fedora30-py2/job/master/105/
