### ISSUE TITLE
Using Custom grains with depth in pillar

### ISSUE THREAD

**Issue by wesleyarthur** [saltstack/salt#54397]
```
mygrain:
    customsubgrain: dev

```
And then I do this in the pillar files to try and get it with an if statement:

```
  {% if grains['mygrain:customsubgrain] == 'dev' %}

  apache: httpd
  vim: vim-enhanced
  {% else %}
  apache: dfsdfsf
  vim: vim-blah
  {% endif %}`
```

It doesn't seem to work.  Are there any code examples of if statements using sub/nested grains?

**Comment by gigi206** [comment]
I have the same issue and I use this code instead :
```
  {% if salt['grains.get']('mygrain:customsubgrain') == 'dev' %}

  apache: httpd
  vim: vim-enhanced
  {% else %}
  apache: dfsdfsf
  vim: vim-blah
  {% endif %}
```

**Comment by wesleyarthur** [comment]
Thanks! I'll try this out tomorrow.

**Comment by xeacott** [comment]
Thanks for providing your working version @gigi206 I'll add appropriate labels to this. @wesleyarthur could you ping back if that worked for you?

**Comment by xeacott** [comment]
Also, @gigi206 @wesleyarthur what versions of salt are you running?
