### ISSUE TITLE
how to download dependency files of latest salt

### ISSUE THREAD

**Issue by karkey83** [saltstack/salt#54405]
### Description of Issue
I want to download the latest salt rpm with all its dependency, as I want to setup salt-master on host behind FW (which does not have internet access)

I tried the below command but it is downloading 2018 version, not sure how to download 2019.2.0 version.
yum install --downloadonly --downloaddir=<download_path> salt

**Comment by xeacott** [comment]
Hi @karkey83 check our repo page https://repo.saltstack.com/ for the latest instructions! If you find yourself still stuck, I'll keep watch on this.

**Comment by xeacott** [comment]
Wanted to follow up with this - just installed in a docker container with `apt` and it gave me 2017 by default. If you want the latest, you'll definitely find it in the link above!
