### ISSUE TITLE
What commit is release 2019.2 on

### ISSUE THREAD

**Issue by jeffdyke** [saltstack/salt#54415]
### Description of Issue

I think this question is better suited to the development community as it could apply in future releases.

Release `2019.2` is no longer the branch of `2019.2` you can see by the update date in git here i'm limiting the scope to the mysql.py module, but could apply to any.  The release version uses `user_chpass` and the branch version now has `_user_chpass-[mysql|mariadb]` functions.  I would like to be able to live patch the release when a bug is found b/c its an immediate blocker for building new machines.    

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
no special setup required for this question.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Ubuntu 18.04
- sudo apt install salt-minion (from `http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic main`)
- open salt/modules/mysql.py
- go to the [2019.2 branch modules/mysql.py](https://github.com/saltstack/salt/blob/2019.2/salt/modules/mysql.py)
- the differences are pretty drastic.  Since this was released in February and it was updated 6 days ago, are the `apt` repo's just not updated?  

For now i'll make a patch off of the release itself, but i can't really submit a PR if i don't know what to compare it to.  
### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Nov 27 2018, 23:36:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1047-aws
         system: Linux
        version: Ubuntu 18.04 bionic

No difference in master and Minion version, python or salt.

**Comment by jeffdyke** [comment]
Attached is a diff patch for the `modules/mysql.py` file.
[mysql.py.2019.2.patch.txt](https://github.com/saltstack/salt/files/3581238/mysql.py.2019.2.patch.txt)

In case someone see's this and needs it as well.

**Comment by dwoz** [comment]
@jeffdyke Release commits are tagged: https://github.com/saltstack/salt/tree/v2019.2.0

**Comment by jeffdyke** [comment]
Fantastic, thank kindly!
