### ISSUE TITLE
extfs.tune is misdocumented and missing a keyword argument

### ISSUE THREAD

**Issue by qcpeter** [saltstack/salt#54426]
### Description of Issue
In the documentation for `extfs.tune` "reserved" is listed as a keyword argument twice (lines 148 and 153 in `salt/modules/extfs.py` for versions 2018.3 and 2019.2) once for the percentage reserved and once for the number of blocks. It is interpreted as the block count when passing the flags to `tune2fs`.

It seems that a second kwarg (perhaps `reserved_percentage`?) should be used in the docs and that added to the kwarg_map to actually allow the reserved blocks to be set as a percentage and to avoid the confusion.

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
2018.3. and 2019.2 (at least)

**Comment by DmitryKuzmenko** [comment]
The `reserved` is `-r` that is the reserved blocks count.
The `-m` flag for reserved blocks percentage is missing.

**Comment by qcpeter** [comment]
Hi @DmitryKuzmenko, just to be clear if you read the documentation carefully you'll notice that reserved is listed _twice_ with two separate descriptions. See [here](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.extfs.html#salt.modules.extfs.tune). "reserved" is both the 11th and 16th entry. My suggestion to add `reserved_percentage` was based on the fact that the current behaviour is to set the block count.

**Comment by DmitryKuzmenko** [comment]
@qcpeter sorry, I wasn't clear in my comment. I'm just confirming your report.
