### ISSUE TITLE
Update repo.saltstack.com landing page for SUSE SLE_12_SP4 and SLE_15

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#54431]
### Description of Issue
Need to update the SUSE tab on repo.saltstack.com for SUSE SLE_12_SP4 and SLE_15.

Recently sync'd SUSE packages for Salt due to requests for SLE 12 SP4, also updated for SLE 15 while working on the sync script.

Definition of Done: 
- [ ] Add tab for SLE 12 SP4
- [ ] Redhat 8 Py3 only
- [ ] Debian 10 Py3 only
- [ ] Raspbian 10 Py3 only

**Comment by dmurphy18** [comment]
Will also need landing page tabs for Redhat 8 Py3 only and Debian 10 Py3 only

**Comment by dmurphy18** [comment]
And Raspbian 10 Py3 only

**Comment by frogunder** [comment]
@KChandrashekhar 

Suse tab updated with: https://github.com/saltstack/docs-repo-landing/pull/7

Redhat8, Debian10, Raspbian10, and Amazon Linux 2 (all Py3) got updated for the 2019.2.1 release.
