### ISSUE TITLE
Phanton Minion Return Errors

### ISSUE THREAD

**Issue by V3XATI0N** [saltstack/salt#54430]
### Description of Issue
If I target a command by grain match, in addition to minions with the appropriate grain value responding as expected, I also see a list of "phantom" minions that don't even exist anymore with the "did not return" error.

I have tried clearing the cached grain values completely from the master, but that doesn't have any effect.

### Setup
- Salt 2019.2.0 on master and minions
- Minion data cache enabled

### Steps to Reproduce Issue
1. Enable and populate minion data cache
2. Delete a few minions
3. Run a grain-match command (like `salt -G asset_type:server test.ping`)
4. See valid returns for minions with the matching `asset_type` value, but ALSO see the minions you deleted earlier show up with `did not return [No response]`.

**Comment by xeacott** [comment]
This may be a case of the other minions still being defined somewhere else, or the key's are still cached somewhere. Can you run a `salt-key -L` and see if they still show up?

**Comment by V3XATI0N** [comment]
The keys don't exist. They don't show up with `salt-key -L` and they don't have directories in /etc/salt/pki/master/minions. If they're still defined somewhere, I have no idea where that could be.

**Comment by xeacott** [comment]
How did you install? If you installed with `apt` check `/var/lib/salt/pki` and if you run a `find` you'll probably see the files in there.

**Comment by V3XATI0N** [comment]
The directory `/var/lib/salt` doesn't exist.

**Comment by xeacott** [comment]
Okay, how did you install it? And what OS are you on, I'll ask around and see where other locations can be.

**Comment by V3XATI0N** [comment]
version report: 
```
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: 1.4.5
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Aug 22 2019, 16:36:40)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-64-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

It was installed with the official salt-bootstrap script.

**Comment by waynew** [comment]
@V3XATI0N when you say "enable and populate minion data cache", what steps did you take there?

**Comment by waynew** [comment]
The other question is what precisely you did with "delete a few minions".

With the default configuration (that contains a localfs cache) I deleted keys for old minions, stopped their services, and ran using the `salt -G master:my_master test.version` and also with `test.ping` and neither of those produced output for anything but the minions that were currently listed in `salt-key -L`.

**Comment by V3XATI0N** [comment]
I just mean that the cache is enabled on the Master. Populating just means to do anything that causes the cache to be filled (like `saltutil.sync_all` or similar). And "deleting a few minions" just means... deleting minions. As in `salt-key -yd minion-id`.

**Comment by waynew** [comment]
@V3XATI0N are you referring to the [minion_data_cache](https://docs.saltstack.com/en/latest/ref/configuration/master.html#minion-data-cache), the [cache](https://docs.saltstack.com/en/latest/ref/configuration/master.html#cache), the [job cache](https://docs.saltstack.com/en/latest/ref/configuration/master.html#job-cache) or something else?

> the cache is enabled on the Master

is not enough information for me to understand what you mean.

Once you deleted your minions from the master's keys, did you also stop the minion processes? Or are they still running?

**Comment by V3XATI0N** [comment]
It just means that the `cache` option isn't set to `false`. The standard minion data cache is enabled. Idk what other information you need. It's using the local filesystem, not Redis or any other pluggable cache modules. Very vanilla.

And no, the minions are not still running. The hosts don't exist at all.
