### ISSUE TITLE
Failed to unregister the VM

### ISSUE THREAD

**Issue by KChandrashekhar** [saltstack/salt#54443]
### Description of Issue
https://jenkinsci.saltstack.com/job/2019.2.1/view/Python3/job/salt-mac-sierra-py3/159/console
Possible reason: looks like the issue of multiple VMs trying to run on there from the same checkout location.

13:56:42  [Pipeline] { (Create VM)
13:56:42  [Pipeline] sh
13:56:43  + bundle exec kitchen create py3-macosx-sierra
13:56:43  -----> Starting Kitchen (v2.2.5)
13:56:44  -----> Creating <py3-macosx-sierra>...
13:56:46         Bringing machine 'default' up with 'parallels' provider...
13:56:46         ==> default: Registering VM image from the base box 'jk-sierra-test'...
13:56:47         ==> default: Creating new virtual machine as a linked clone of the box image...
13:56:52         
[K==> default: Unregistering the box VM image...
13:56:52         ==> default: Unregistering the box VM image...
13:56:53         There was an error while command execution. The command and stderr is shown below.
13:56:53         
13:56:53         Command: ["/usr/local/bin/prlctl", "unregister", "64e354b9-39ef-42a0-9d0e-23248e9e1235"]
13:56:53         
13:56:53         Stderr: Failed to unregister the VM: Unable to perform the action because the virtual machine is busy. The virtual machine is being cloned. Please try again later.

**Comment by sagetherage** [comment]
not stale
