### ISSUE TITLE
Archive.extract retains the name of tar package on extraction

### ISSUE THREAD

**Issue by Nishanth25** [saltstack/salt#54446]
### Description of Issue
Hello , I am working on a scenario where i have to execute a archive.extract in for loop to explode the tar files, the first tar package is unique and extraction fine where as for the other two extractions i have extract the same package in two different locations, I am able to achive it but archive.extract seems to retain the tar package name even after extraction.

### Setup
{% for instances, arg in salt['pillar.get']('sacred:fun:services:instances', {}).iteritems() %}
{{ instances }}:
  archive.extracted:
    - name: {{ arg.name }}
    - source: {{ arg.source }}
    - archive_format: tar
    - tar_options: v
    - template: jinja
    - makedirs: True
    - user: {{ pillar['sacred']['funtl']['services']['user'] }}
    - group: {{ pillar['sacred']['funtl']['services']['group'] }}
    - mode: 775

### Versions Report
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 11 2019, 12:19:05)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.27.2.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo

**Comment by DmitryKuzmenko** [comment]
@Nishanth25 I've tried to reproduce this but for me the `archive.extraced` state works as documented.
Could you please provide more details like the content of `salt['pillar.get']('sacred:fun:services:instances')` in your case. Your archives names and content layout and the results of the state execution?

**Comment by Nishanth25** [comment]
@DmitryKuzmenko Thanks for your response, I was able to fix with "--strip" options and achieve what i wanted. Thanks.

**Comment by DmitryKuzmenko** [comment]
@Nishanth25 thank you for response.
