### ISSUE TITLE
Salt-call test.ping much slower than ping from master

### ISSUE THREAD

**Issue by Daemonslayer2048** [saltstack/salt#54440]
### Description of Issue
salt-call test.ping takes approximately 40+ seconds while a ping from the master takes a little over one. This has been very consistent time wise so this isn't a one time issue. I understand the master publishes jobs normally and then a minion takes a job (excuse my ignorance if I am wrong) so I imagine that probably plays into this but a 40 second delay makes me think otherwise. Would anybody have some guidance on how to debug this or improve this response time? 

### Setup
No relevant configs used here

### Steps to Reproduce Issue
From master:
```
time sudo salt 'Dev-*' test.ping
Dev-One:
    True
Dev-Two:
    True

real	0m1.343s
user	0m0.385s
sys	0m0.115s
```
From Dev-One:
```
root@Dev-One:~# time salt-call test.ping
local:
    True

real	0m45.714s
user	0m43.725s
sys	0m1.126s
```
From Dev-Two:
```
root@Dev-Two:~# time salt-call test.ping
local:
    True

real	0m43.333s
user	0m39.724s
sys	0m1.036s

```

### Versions Report
The master generates the following:
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Nov 12 2018, 14:36:49)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.19.8-x86_64-linode120
         system: Linux
        version: Ubuntu 16.04 xenial
```
Both salt minions run the following:
```
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.2 (default, Nov 12 2018, 13:43:14)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: aarch64
        release: 4.14.0
         system: Linux
        version: Ubuntu 16.04 xenial
```
### Note:
I was not aware of the version difference until now.

**Comment by DmitryKuzmenko** [comment]
@Daemonslayer2048 Salt-call will be slower because it initializes an instance of a minion. Depending on your minion configuration and hardware set up it could be much slower.
Could you please check how long `salt-call --local test.ping` takes on your minion machine please?

@saltstack/team-core can anybody please correct me if I'm wrong?

**Comment by Daemonslayer2048** [comment]
Looks like execution time is the same.  There is a strong chance the hardware may be underpowered and my configuration is stock from install minus the master and master finger settings. The minions in this use case are on ARM boards. Watching CPU usage during the call I have noticed both devices see 100% CPU usage so it sure is a hardware limitation. That is my bad I didn't even check that. Is there room to improve this for less resource available systems, or is this a conversation for else where? 
```
root@Dev-One:~# time salt-call --local test.ping
local:
    True

real	0m42.599s
user	0m41.475s
sys	0m1.091s
```
```
root@Dev-Bin:~# time salt-call --local test.ping
local:
    True

real	0m42.503s
user	0m40.484s
sys	0m1.000s
```
