### ISSUE TITLE
sync_after_install: grains causes salt-cloud to fail

### ISSUE THREAD

**Issue by cavepopo** [saltstack/salt#54452]
### Description of Issue
Adding the `sync_after_install: True` in cloud config file causes salt-cloud to fail with 
```
[ERROR   ] There was a query error: Authentication error occurred.

[...]

  File "/usr/lib/python2.7/dist-packages/salt/client/__init__.py", line 344, in run_job
    raise AuthenticationError(err)

AuthenticationError: Authentication error occurred.
```

Same as this issue : #34124

### Setup
Standard master and minion config, nothing shiny here :)

### Steps to Reproduce Issue
Add `sync_after_install: True` to the cloud config file and provision a vm.

### Versions Report
Master:
```

Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.9 
         locale: UTF-8
        machine: x86_64
        release: 5.0.15-1-pve
         system: Linux
        version: debian 9.9 
```
Same on minion.

**Comment by DmitryKuzmenko** [comment]
For some reason the PR #51361 that fixes similar issues #40695 and #34124 in 2017.7.9 is not in 2019.2.
@cavepopo do you have a chance to patch your installation with changes from #51361 and check it?

**Comment by cavepopo** [comment]
Dunno yet if the patching is possible here, I'll check tom and get back here to report.

**Comment by cavepopo** [comment]
Hi, after some time I finally found a company in which I use salt, lucky me :)
But i encounter this bug again, though it is through a new error : 
`[ERROR   ] There was a query error: 'ImmutableDict' object has no attribute 'update'
`

I tried with 'grains' and 'all' attribute to the sync_after_install key, but none works.

Any ideas ?

**Comment by cavepopo** [comment]
Same issue [here|https://github.com/saltstack/salt/issues/40695#] looks not fixed as of today
