### ISSUE TITLE
partition.mkpart doesn't work without fstype making it useless to create partitions without filesystem

### ISSUE THREAD

**Issue by monofumado** [saltstack/salt#54456]
### Description of Issue
The module partition.mkpart doesn't work without fstype making it useless to create partitions without filesystem (needed for example for LVM)

### Steps to Reproduce Issue
call partition.mkpart without giving a fstype always return the error "Invalid fs_type passed to partition.mkpart"

### Versions Report
Salt Version:
Salt: 2019.2.0

Dependency Versions:
cffi: 1.11.5
cherrypy: Not Installed
dateutil: 2.8.0
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.10
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: 0.30.1
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.6.1
mysql-python: Not Installed
pycparser: 2.19
pycrypto: 2.6.1
pycryptodome: Not Installed
pygit2: Not Installed
Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
python-gnupg: Not Installed
PyYAML: 3.13
PyZMQ: 18.0.2
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.3.1

System Versions:
dist: debian 9.9
locale: UTF-8
machine: x86_64
release: 4.9.0-9-amd64
system: Linux
version: debian 9.9

In the code fstype is initialized to None, but then is checked against _is_fstype before checking if it's not None, which results in returning always and error
```python
if not _is_fstype(fs_type):
        raise CommandExecutionError(
            'Invalid fs_type passed to partition.mkpart'
        )
```

**Comment by cr1st1p** [comment]
Bumped today into this as well.
saltstack version 3000.1
The problem is where bug reporter showed.

I think condition should read:
```
if fs_type and not _is_fstype(fs_type):

```
as to reflect also the condition further down in the code.

Note that the documentation also gives an example *without*  a fs_type parameter.

**Comment by robertpenberthy** [comment]
Yeah, looking at the code for this in 2018.3 (https://github.com/saltstack/salt/blob/v2018.3.3/salt/modules/parted.py#L443) and here in 3000.1, whoever made the changes, they removed to test to see if fs_type is even defined.

It should be updated to how @cr1st1p stated in the comment above.  I tested the change locally.  So should be a very simple fix for someone to add back in `fs_type and ` to this module.
