### ISSUE TITLE
salt-ssh default `thin_dir` does not respect `root_dir`

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#54450]
As a rule, all default directories should obey the `root_dir` config option to ease sandboxing efforts.

https://github.com/saltstack/salt/blob/e04efc315567ef126bdaedc103c40e948b52586c/salt/client/ssh/__init__.py#L65-L67
and
https://github.com/saltstack/salt/blob/e04efc315567ef126bdaedc103c40e948b52586c/salt/client/ssh/__init__.py#L315-L317

**Comment by xeacott** [comment]
This may be of use to mention here, but myself and @nergdron discussed something related [here](https://github.com/saltstack/salt/issues/54105). If you want to specify your own root_dir, then you can use a Saltfile to control that.

**Comment by brianthelion** [comment]
@xeacott Interesting discussion on the other thread. Unclear how to use that here, though. I can set the `thin_dir` by hand in the roster if I need to. But unless I'm reading the source code (above) wrong, the default `thin_dir` -- again, if you don't set it explicitly -- doesn't care what `salt_root` is in your master configuration.
