### ISSUE TITLE
custom module can not load dunder variables from subfiles

### ISSUE THREAD

**Issue by guanxudong** [saltstack/salt#54451]
### Description of Issue
salt custom module like [here](https://docs.saltstack.com/en/latest/ref/modules/#creating-a-zip-archive-module), can not load **dunder** from submodule

### Setup
the structure of custom module
```
└── demo
    ├── __init__.py
    └── subdemo
        └── __init__.py
```

```
# demo/__init__.py
from demo import subdemo

__virtualname__ = 'demo'

def __virtual__():
    return __virtualname__

def info():
    return {'minion_id': subdemo.grain_id()}
```
```
# demo/subdemo/__init__.py
def grain_id():
    return __grains__['id']
```
### Steps to Reproduce Issue
`salt '*' saltutil.sync_modules`
`salt '*' demo.info`

salt will return `NameError: name '__grains__' is not defined`

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-17134-Microsoft
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by DmitryKuzmenko** [comment]
The loader doesn't do that. The salt dunders are only injected into the module itself, not into it's sub-modules or other dependencies.
If you'd like to have dunders in your submodule you can do this:

```python
# demo/__init__.py
def __init__(opts):
    setattr(subdemo, '__grains__', __grains__)
```

**Comment by guanxudong** [comment]
Thanks @DmitryKuzmenko ! 
It sounds like we have to pass **dunders** from top to bottom, so that sub-modules can use it
