### ISSUE TITLE
Very slow creating of containers.

### ISSUE THREAD

**Issue by gecube** [saltstack/salt#54465]
Hello!

I found a very interesting corner case when working with [docker_container](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.docker_container.html) state.

Let's assume that you have an empty host with installed docker. Than apply state containing a lot of containers like:

```
test:
  docker_container.running:
    - image: ubuntu
    - restart_policy: unless-stopped
    - command:
      - sleep
      - infinity
```

One can use jinja-like style for multiplicating the number of containers. And... everything goes ok. Every container is created in sane time (~ 1 container per 1 minute)

The next situation when we want to recreate containers. It works slower. But it is OK too.

But when you are trying to recreate containers which are *in failed* state and are *always restarting* (for example, the application inside the container exits because of the some exception) - the state with 50 containers can take as much as 2 hours to be applied.

Right now I use as workaround total removal of containers and then - apply the state.

I am not sure what is the reason for such behavior, but it definitely looks like a bug: in Docker API or maybe in Salt's docker container state.

I will make further investigation and return with more data on the issue.

Also the affected versions are all versions of Salt since 2018.*.* and 2019.*.*
I did not find any correlation with Docker daemon version or docker-py version, so probably all versions are affected.

**Comment by xeacott** [comment]
So this issue follows the situation...
1. Use a state file to create _tons_ of containers (assuming that some can be in a failed state?)
2. Recreate the containers (mindful that some are in a failed state)
3. Endure long wait times because of the failed containers trying to be recreated.

So what's going on here at a surface level is that some of the docker containers end up in a failed state, and Salt (or maybe Docker) is not accounting for this in a sense that the container is attempting to either clean itself up, or run the command it was given, or even restart for that matter - but when Salt looks to apply the state again, it's waiting for the container to 'do' whatever it was suppose to. Or am I totally missing the mark?

**Comment by gecube** [comment]
@xeacott You are almost right. Regarding p.1 - it is enough to create 10 containers. 10 is definitely is not _dozens_ or _tons_. I said about _half of hundred_ containers because it emphasize the issue.

> Endure long wait times because of the failed containers trying to be recreated.

I don't care why there are failed because it is not Salt's business to check their state. Maybe I am not right. But it really is some kind of design flaw.

> but when Salt looks to apply the state again, it's waiting for the container to 'do' whatever it was suppose to.

Salt is not the supervisor. It's just SCM. It can't fix broken container. As it can't fix broken systemd-unit. Also there is always gap in time between the moment when the container was started and when it failed. Let's assume hypothetical situation that I use salt for bootstrapping the configuration (Salt is more superior in many moments, than Ansible) and the containers will fail after long time. Will be state applied fast and without errors? Yes. So what is the difference with my situation? Only the races between when Salt create the container and checks it's state ?

**Comment by xeacott** [comment]
That is a good question! 

I don't know how forceful salt needs to be in a situation like this, unless this type of example needs human intervention to mitigate containers that find themselves in these states. Unless the docker state can have some type of fail-safe that force kills non-responding containers. It can't fix a broken container but I'm sure it can totally nuke a broken container 😄 

Maybe @terminalmage can offer some advice. Although I am trying to learn as much about the docker modules, I don't have as much a history with them as some of our other members do.

**Comment by terminalmage** [comment]
This likely has to do with the timeout for shutting down a container. When you tell docker to stop a container, if it doesn't respond to the stop request within the timeout (default is 10 seconds) the container will be force-stopped. I can tell you from my testing when I was developing the docker states that having a container running a sleep command will always result in it having to wait to be force-stopped. Why I am not certain, as I never delved deeply enough to understand what sort of signal or method docker uses to stop the running container. With a large number of containers, this will mean a lot of time spent waiting for the timeout as each state is run serially.

You can try setting a shorter timeout using the `shutdown_timeout` argument in your `docker_container.running` state.
