### ISSUE TITLE
module mysql user_chpass force the use of auth_socket

### ISSUE THREAD

**Issue by poofyteddy** [saltstack/salt#54479]
### Description of Issue

I have issue with the actual mysql module from release 2019.2.0 (Fluorine) (see #52723 )
i try the module actualy in develop and i have an issue with how auth pluging are chosen by the user_chpass methode
https://github.com/saltstack/salt/blame/develop/salt/modules/mysql.py#L1562
```
1559     if salt.utils.data.is_true(allow_passwordless) and \
1560             salt.utils.data.is_true(unix_socket):
1561         if host == 'localhost':
1562             args['unix_socket'] = 'auth_socket'
```
on the last stable mariadb server on debian 9's mariadb official repo (Ver 15.1 Distrib 10.4.8-MariaDB) There is no `auth_socket` and the default is called `unix_socket`. see https://mariadb.org/authentication-in-mariadb-10-4/
This cause `mysql_user.present` to fail when using `allow_passwordless: True` and `unix_socket: True` with error `Failed to clear password for user root@localhost (MySQL Error 1396: Operation ALTER USER failed for 'root'@'localhost')`

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
on a debian 9, download install mariadb server from repo here : https://downloads.mariadb.org/mariadb/repositories/#distro=Debian&distro_release=stretch--stretch&mirror=aarnet_pty_ltd&version=10.4
replace the module mysql.py by the one from the develop branch
run a state like 
```
mysql_user.present:
    - name: root
    - host: localhost
    - allow_passwordless: True
    - unix_socket: True
```
you'll get in debug
```
[DEBUG   ] Doing query: ALTER USER %(user)s@%(host)s IDENTIFIED WITH %(unix_socket)s AS %(user)s; args: {u'unix_socket': u'auth_socket', u'host': u'localhost', u'user': u'root'}                                  
[ERROR   ] MySQL Error 1396: Operation ALTER USER failed for 'root'@'localhost'                                                                                                                                    
[ERROR   ] Failed to clear password for user root@localhost (MySQL Error 1396: Operation ALTER USER failed for 'root'@'localhost')
```
if you try to check for the plugin in mysql you get a `No such file`
```
MariaDB [(none)]> INSTALL SONAME 'auth_socket';
ERROR 1126 (HY000): Can't open shared library '/usr/lib/mysql/plugin/auth_socket.so' (errno: 2, cannot open shared object file: No such file or directory)
```
if you run the same command with `unix_socket` module it work
```
MariaDB [(none)]> ALTER USER 'root'@'localhost' IDENTIFIED WITH 'unix_socket' AS 'root';
Query OK, 0 rows affected (0.002 sec)
```
### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.9
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-9-amd64
         system: Linux
        version: debian 9.9

With mysql module from develop branch

**Comment by DmitryKuzmenko** [comment]
Duplicates #52206

**Comment by poofyteddy** [comment]
Sorry, i swear i search on the bug list :( got to be blind
