### ISSUE TITLE
No matching sls found for 'init' in env 'base'

### ISSUE THREAD

**Issue by lmq1999** [saltstack/salt#54509]
I'm trying to push file from master to minion but so long i have the problems when run: salt '*' state.apply init

ubuntu:
    Data failed to compile:
----------
    No matching sls found for 'init' in env 'base'

### Setup
I only edit this master file in /etc/salt/master
file_roots:
  base:
    - /srv/salt

i also try to run this
root@quanlm:~# salt-run fileserver.file_list saltenv=base
- ejabberd.yml
- init.sls
- usr.sbin.ejabberdctl

### Versions Report
Salt Version:
           Salt: 2017.7.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 3.6.8 (default, Aug 20 2019, 17:12:48)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-27-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by cmcmarrow** [comment]
I am not seeing anything odd. Also you don't need to change the master.conf because base is /srv/salt by default.
