### ISSUE TITLE
Sign /opt/salt/bin/python3 for macOS

### ISSUE THREAD

**Issue by lashomb** [saltstack/salt#54513]
With expectations for code execution in macOS starting to require signing (and possibly notarization eventually), can we sign the included `python3` binary?

Use case is when using the included binary that calls code that affects certain parts of user space. This framework is referred to as Transparency Consent and Control (TCC also known as PPPC) within macOS. These code executions will prompt for user approval, but can be whitelisted by an MDM profile. To be able to whitelist this however, it is required to be signed.

https://github.com/saltstack/salt/blob/705e8cca0b9ad6441c3884e76798cac1ff7859d7/pkg/osx/build_sig.sh#L53

**Comment by lashomb** [comment]
@weswhet As talked about in today's macOS working group.

**Comment by lashomb** [comment]
I know chef is signing all the binaries in chef, probably want the same approach here for salt. https://github.com/chef/chef/pull/9275#issuecomment-581549410

**Comment by weswhet** [comment]
this script is probably helpful in singing / notarizing all of salt and its bundled python. https://github.com/munki/munki/pull/986/files

**Comment by lashomb** [comment]
Did the Apple dev account ever get sorted for this to be signed?

**Comment by arubdesu** [comment]
I left a comment with thoughts on the matter on @twangboy's gist investigating this https://gist.github.com/twangboy/064936b14e3c5ce4b58771d3e4534c9a
