### ISSUE TITLE
shorten hostname in kitchen tests infrastructure

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#54514]
The tests:

```
    unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_bad
    unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_correct_timestamp_reply
    unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_outdated_timestamp_quiet
    unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_outdated_timestamp_reply
    unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_wrong_timestamp_quiet
    unit.utils.test_ssdp.SSDPFactoryTestCase.test_datagram_signature_wrong_timestamp_reply
    unit.utils.test_ssdp.SSDPFactoryTestCase.test_transport_sendto_retry
    unit.utils.test_ssdp.SSDPFactoryTestCase.test_transport_sendto_success
```

are failing only on PR tests with this error:

```
Traceback (most recent call last):
  File "/tmp/kitchen/testing/tests/unit/utils/test_ssdp.py", line 290, in test_datagram_signature_correct_timestamp_reply
    factory = ssdp.SSDPFactory()
  File "/tmp/kitchen/testing/salt/utils/ssdp.py", line 122, in __init__
    self.my_ip = socket.gethostbyname(socket.gethostname())
socket.gaierror: [Errno -2] Name or service not known
```

this is because the hostname in /etc/hostname is different from /etc/hosts:

/etc/hostname: `ubuntu-1604py2runtests-zeromq1-54478.prod.pdx.ci.aws.saltstack.n`
/etc/hosts: `127.0.1.1 ubuntu-1604py2runtests-zeromq1-54478 ubuntu-1604py2runtests-zeromq1-54478.prod.pdx.ci.aws.saltstack.net` notice the `et` missing at the end on /etc/hostname. this is most likely because of the 64 character limit for hostnames on some linux distros. 

This issue is being created to track the work to shorten the hostnames so we do not see these type of errors in our test suite

**Comment by bryceml** [comment]
This should be fixed by https://github.com/saltstack/salt/pull/53919, we are also waiting for https://github.com/saltstack/salt/pull/53921
