### ISSUE TITLE
Unable to use salt on Azure

### ISSUE THREAD

**Issue by hemantaltair** [saltstack/salt#54511]
Trying to get azure resources from salt CLI but getting this error:
bash-3.2# salt-cloud -l debug --list-sizes azure-config
[DEBUG   ] Missing configuration file: /etc/salt/cloud
[DEBUG   ] Missing configuration file: /etc/salt/master
[DEBUG   ] Missing configuration file: /etc/salt/cloud.providers
[DEBUG   ] Including configuration from '/etc/salt/cloud.providers.d/azure.conf'
[DEBUG   ] Reading configuration from /etc/salt/cloud.providers.d/azure.conf
[DEBUG   ] Reading configuration from /etc/salt/cloud.profiles
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] salt-cloud starting
[WARNING ] Missing dependency: 'azure'. The azure driver requires 'azure' to be installed.
[DEBUG   ] Could not LazyLoad parallels.avail_sizes: 'parallels' __virtual__ returned False
[DEBUG   ] LazyLoaded parallels.avail_locations
[DEBUG   ] LazyLoaded proxmox.avail_sizes
[DEBUG   ] Could not LazyLoad azure.get_configured_provider: 'azure.get_configured_provider' is not available.
[WARNING ] The cloud driver, 'azure', configured under the 'azure-config' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'azure' driver.
In rare cases, this could indicate the 'azure.get_configured_provider()' function could not be found.
Removing 'azure' from the available providers list
Error: There was an error listing sizes: No cloud providers matched 'azure-config'. Available selections:

### Setup
Azure config
bash-3.2# cat azure.conf 
azure-config:
  driver: azure
  subscription_id: **********************************************
  certificate_path: /etc/salt/azure.pem

  minion:
    master: localhost

### Steps to Reproduce Issue
bash-3.2# salt-cloud -l debug --list-sizes azure-config

### Versions Report
bash-3.2# salt --versions-report
/usr/local/Cellar/salt/2019.2.0_2/libexec/lib/python3.7/site-packages/salt/version.py:632: DeprecationWarning: dist() and linux_distribution() functions are deprecated in Python 3.5
  lin_ver = linux_distribution()
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.28.3
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.1
         Python: 3.7.4 (default, Sep  7 2019, 18:27:02)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 18.6.0
         system: Darwin
        version: 10.14.5 x86_64

**Comment by hemantaltair** [comment]
Any help will be appreciated!

**Comment by hemantaltair** [comment]
bash-3.2# salt-cloud --list-images my-azure-config
[ERROR   ] Failed to import clouds msazure, this is due most likely to a syntax error:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/salt/loader.py", line 1548, in _load_module
    mod = spec.loader.load_module()
  File "<frozen importlib._bootstrap_external>", line 407, in _check_name_wrapper
  File "<frozen importlib._bootstrap_external>", line 907, in load_module
  File "<frozen importlib._bootstrap_external>", line 732, in load_module
  File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/salt/cloud/clouds/msazure.py", line 61, in <module>
    import azure.servicemanagement
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azure/servicemanagement/__init__.py", line 27, in <module>
    from .servicemanagementclient import parse_response_for_async_op
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/azure/servicemanagement/servicemanagementclient.py", line 372
    def _perform_put(self, path, body, async=False, x_ms_version=None):
                                           ^
SyntaxError: invalid syntax
[WARNING ] The cloud driver, 'azure', configured under the 'azure-config' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'azure' driver.
In rare cases, this could indicate the 'azure.get_configured_provider()' function could not be found.
Removing 'azure' from the available providers list
Error: There was an error listing images: No cloud providers matched 'my-azure-config'. Available selections:

**Comment by nicholasmhughes** [comment]
@hemantaltair you'll want to use the newer [Azure Resource Manager driver](https://docs.saltstack.com/en/latest/topics/cloud/azurearm.html) in your provider config:
```
driver: azurearm
```
Also, make sure you install the Azure Python SDK.

**Comment by sagetherage** [comment]
@hemantaltair is this still an issue?

**Comment by hemantaltair** [comment]
no anymore please close. thanks
