### ISSUE TITLE
Failed to cache s3 / Could not fetch from s3 Python2

### ISSUE THREAD

**Issue by Guiduret** [saltstack/salt#54690]
### Description of Issue
Not sure if there was any Python 2.7 or specific Ubuntu 16.04 updates lately, but the **file managed state on S3 sources seems to not work anymore** for couple of days (weeks?).

The error is `Exception: super() takes at least 1 argument (0 given)`,  no update of my salt state have been made and it was surely working.

### Setup
State:

    file.managed:
      - name: /home/myfile
      - source: s3://my-bucket/path/to/file
      - skip_verify: True
      - makedirs: True
      - user: ubuntu

### Steps to Reproduce Issue
Just salt call from minion directly (same error while using salt command from master), and here is the error log:

    ----------
        ID: instance-configuration.packages.download
        Function: file.managed
        Name: /home/myfile
        Result: False
        Comment: Failed to cache s3://my-bucket/path/to/file: Could not fetch from s3://my-bucket/path/to/file. Exception: super() takes at least 1 argument (0 given)
        Started: 12:04:22.435953    Duration: 10.453 ms
        Changes:
    ----------

### Versions Report
Salt:

    salt-minion 2019.2.0 (Fluorine)

Ubuntu:

    Distributor ID: Ubuntu
    Description:    Ubuntu 16.04.6 LTS
    Release:        16.04
    Codename:       xenial

Python:

    Python 2.7.12

Also tested on previous salt-minion version 2018 & 2017, same issue.
Thanks in advance if someone has an idea or have reproduced this case!

### Edit

The s3.get state is to the one failing actually (called by file.managed on s3 souces):

    # salt 'myminion' s3.get bucket="mybucket" path="path/to/file" local_file="/home/myfile" 
    /usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
    warnings.warn(warning, RequestsDependencyWarning)

    Passed invalid arguments: super() takes at least 1 argument (0 given).

    Usage: [...]

This same command works on former instances...

**Comment by sagetherage** [comment]
@Guiduret is this still an issue with Python 3.6+ and a supported version of Salt >3000.9?

**Comment by Guiduret** [comment]
@sagetherage No problem anymore, at least ok on python 2.7 and Salt > 3000.
