### ISSUE TITLE
Salt custom modules not working

### ISSUE THREAD

**Issue by karkey83** [saltstack/salt#54728]
### Description of Issue
I have custom module called checkout, it is working fine on many hosts and for some host it is not working as expected. When tried to execute the module on the host getting the below error
    return __salt__['sys.list_functions']('checkout.*')
    NameError: global name '__salt__' is not defined

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt Version:
           Salt: 2019.2.0
Salt-master: 2019.2.0

Please advise on how to fix the issue.

**Comment by xeacott** [comment]
Hi @karkey83 would you be able to provide a full traceback when you run into the issue? Also for the hosts that it is working and then for the hosts that it isn't working, what are the differences between them?
