### ISSUE TITLE
Jinja shell command execution issue but same command works fine with Salt

### ISSUE THREAD

**Issue by alok183** [saltstack/salt#54726]
### Description of Issue
Jinja shell command execution issue but same command works fine with salt

### Setup
{% set hostip = salt['cmd.run']("kubectl get po -n ingress-nginx -o wide --kubeconfig={{ var.helm.KUBECONFIG }} | grep internal-nginx-nginx-ingress-controller | grep -E -o '([0-9]{1,3}[\.]){3}[0-9]{1,3}'") %}

ingress_host_entry:
  host.present:
    - name: chartmuseum.{{ config.wmic_int_url }}
    - ip: {{ hostip }}

### Steps to Reproduce Issue
**working with Salt with out using jinja**
**command:** 
salt alsh-prod-aps1-master-03 cmd.run "kubectl get po -n ingress-nginx -o wide --kubeconfig=/etc/kubernetes/admin.conf" | grep internal-nginx-nginx-ingress-controller | grep -E -o '([0-9]{1,3}[\.]){3}[0-9]{1,3}'
**output :** 
192.168.152.72

 ID: ddgddd_dddnnd
    Function: cmd.run
        Name: kubectl get po -n ingress-nginx -o wide --kubeconfig=/etc/kubernetes/admin.conf | grep internal-nginx-nginx-ingress-controller | grep -E -o '([0-9]{1,3}[\.]){3}[0-9]{1,3}'
      Result: True
     Comment: Command "kubectl get po -n ingress-nginx -o wide --kubeconfig=/etc/kubernetes/admin.conf | grep internal-nginx-nginx-ingress-controller | grep -E -o '([0-9]{1,3}[\.]){3}[0-9]{1,3}'" run
     Started: 13:36:34.325531
    Duration: 103.201 ms
     Changes:
              ----------
              pid:
                  3173
              retcode:
                  0
              stderr:
              stdout:
                  192.168.152.72

**Issue when using Jinja:**

{% set hostip = salt['cmd.run']("kubectl get po -n ingress-nginx -o wide --kubeconfig=/etc/kubernetes/admin.conf | grep internal-nginx-nginx-ingress-controller | grep -E -o '([0-9]{1,3}[\.]){3}[0-9]{1,3}'") %}

**Error:**

Data failed to compile:
----------
    Rendering SLS 'cdep:alsh' failed: mapping values are not allowed in this context

### Versions Report
Salt Version:
Salt: 2019.2.0

**Comment by cmcmarrow** [comment]
`{%set var = salt['cmd.run']('ls | grep -E -o \'([0-9])\'') %}` you need to change the syntax  in Jinja.
