### ISSUE TITLE
reactor is skipping the event task execution on some of the minions 

### ISSUE THREAD

**Issue by alok183** [saltstack/salt#54720]
### Description of Issue
reactor is skipping the event task execution on some of the minions but same conditional event is getting executed on some minion .Also manually triggering the event executes the task successfully on rest of the minion.  

### Setup
AWS
1. Added sls execution path on the minion start event.
2. Added sls file in reactor directory to execute orchestrate file (install docker and kubelet)
3. Added 3 minions
4. Noticed orchestrate file executed on 1,2 minion and 3rd one got skipped.
5.  Restarted salt minion service manually on 3rd node and event got triggered successfully 

Note: Salt minion is auto provisioned and keys are auto accepted by salt master.

### Versions Report
Salt Version:
           Salt: 2019.2.0

**Comment by cmcmarrow** [comment]
Can I see your sls files please? Also can I get move info on your master and minions?

**Comment by alok183** [comment]
reactorconf:
- 'salt/minion/{{ var.misc.PRODUCT_NAME }}*node*/start':
    - /srv/reactor/nodes-highstate.sls

**reactor file: /srv/reactor/nodes-highstate.sls**

invoke_orchestrate_node_install:
    runner.state.orchestrate:
      - args:
          - mods: cdep.orchestrate.reactor_task_install_nodes
          - pillar:
                new_minion: {{ data['id'] }}


**state file called: cdep.orchestrate.reactor_task_install_nodes**

{% set new_minion = salt['pillar.get']('new_minion') %}
install_nodes:
  salt.state:
    - tgt: {{ new_minion }}
    - sls:
        - common/install_epel
        - node/node_pkgs
        - common/install_docker
        - common/install_kubeadm
        - node/install_node
    - saltenv: "cdep"
