### ISSUE TITLE
2018.8.3.2 Failed to return clean data

### ISSUE THREAD

**Issue by glkappe** [saltstack/salt#54727]
### Description of Issue

my salt-master : DB4-43
minion:6102
The first execution of salt-ssh error：
`[root@DB4-3 salt]# salt-ssh '6102' state.sls salt.install_salt-minion -i                                             
6102:
    ----------
    _error:
        Failed to return clean data
    retcode:
        0
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.root_183985_salt/salt-call", line 15, in <module>
            salt_call()
          File "/var/tmp/.root_183985_salt/py2/salt/scripts.py", line 395, in salt_call
            import salt.cli.call
          File "/var/tmp/.root_183985_salt/py2/salt/cli/call.py", line 5, in <module>
            import salt.utils.parsers
          File "/var/tmp/.root_183985_salt/py2/salt/utils/parsers.py", line 27, in <module>
            import salt.config as config
          File "/var/tmp/.root_183985_salt/py2/salt/config/__init__.py", line 24, in <module>
            import salt.utils.data
          File "/var/tmp/.root_183985_salt/py2/salt/utils/data.py", line 18, in <module>
            import salt.utils.stringutils
          File "/var/tmp/.root_183985_salt/py2/salt/utils/stringutils.py", line 214
            trans_args = ({ord(x): None for x in text_characters},)
                                          ^
        SyntaxError: invalid syntax
    stdout:`
6102 python version ：
`[root@db6-102 ~]# python -V
Python 2.6.6`

The strange thing is that to solve this error you need to manually install python 2.7.17 in 6102, my sls file, the first step is to do so.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
`[root@DB4-3 salt]# salt --versions-report 
Salt Version:
           Salt: 2018.3.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Oct  9 2018, 14:04:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.6
 
System Versions:
           dist: centos 6.10 Final
         locale: UTF-8
        machine: x86_64
        release: 4.4.180-1.el6.elrepo.x86_64
         system: Linux
        version: CentOS 6.10 Final`

**Comment by xeacott** [comment]
Can you provide the SLS file? Also I would make sure that you use 2.7.16 across the board, if you are going to use 2.7 as it's the latest we currently support.
