### ISSUE TITLE
Installing salt 2019.2.0 from the rpm found on repo.saltstack.com installs too low of a version of msgpack-python

### ISSUE THREAD

**Issue by Nate-Watts** [saltstack/salt#54748]
### Setup
Setup requires a CentOS7 instance.
Install pip for CentOS
1. `curl -O https://bootstrap.pypa.io/get-pip.py`
2. `python get-pip.py`

### Steps to Reproduce Issue
1. Visit https://repo.saltstack.com/#rhel 
2. Follow instructions for installing for CentOS7 Python2
a. `sudo yum install https://repo.saltstack.com/yum/redhat/salt-repo-latest.el7.noarch.rpm `
b. `sudo yum clean expire-cache`
c. `sudo yum install salt-minion`

3. Run a `pip freeze` and check the version of msgpack-python = 0.4.6
```[root@ip-10-27-65-75 salt]# python
Python 2.7.5 (default, Aug  7 2019, 00:51:29) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-39)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import msgpack
>>> a = msgpack.dumps({'foo': 'bar'})
>>> a
'\x81\xa3foo\xa3bar'
>>> msgpack.loads(a)
{'foo': 'bar'}
>>> msgpack.loads(a, raw=False)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "msgpack/_unpacker.pyx", line 99, in msgpack._unpacker.unpackb (msgpack/_unpacker.cpp:101)
TypeError: unpackb() got an unexpected keyword argument 'raw'
>>> msgpack.loads(a, encoding='utf-8')
{u'foo': u'bar'}
>>> msgpack.version
(0, 4, 6)
>>> 
```
4. Running a `pip install msgpack-python --upgrade` resolves the issue by upgrading to version 0.5.6

### More Info
Under the 2019.2.0 branch, inside requirements/base.txt
```# This should be changed to msgpack-python for Packages
# msgpack-python>0.3,!=0.5.5
msgpack>=0.5,!=0.5.5
```
SSE Raas ticket that brought up this issue: https://github.com/saltstack/raas/issues/5528
Raas specifies that it requires msgpack 0.5.6
*msgpack-python is a deprecated package

### Versions Report
`salt-minion --versions-report`
Note that msgpack-python was upgraded from 0.4.6 originally installed from rpm to 0.5.6
```Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
 
```

**Comment by dmurphy18** [comment]
@Nate-Watts SaltStack provides a minimum version of a dependency for Salt in order for Salt to function on that platform, with the hope that eventually the underlying OS will eventually release a more modern version of the package, which typically they eventually do, at which point the OS supplied package supersedes that provided by SaltStack.

The correct solution is to install EPEL which currently has the following:
msgpack.x86_64                            1.4.1-1.el7         epel              
msgpack-devel.x86_64                      1.4.1-1.el7         epel          
python2-msgpack.x86_64                    0.5.6-5.el7         epel              
python36-msgpack.x86_64                   0.5.6-5.el7         epel  

Salt on Redhat is functioning as designed, hence if please consider closing this issue.
If you need to have an installation without EPEL then let talk with Jeff etc. to discuss the matter.

**Comment by revmehul** [comment]
> Salt in order for Salt to function on that platform, with the hope that eventually the underlying OS will eventually release a more modern version of the package, which typically they eventually do,

From what I can tell, the gist of the matter is, the minimum version of msg-pack we recommend does not allow salt to function properly on that platform. Basically with current recommendations scans run from SSE fail by default. They only work is msg-pack version is 0.5.6 or higher.

**Comment by Nate-Watts** [comment]
Discussion is that the requirements specified were unused. Raas has fixed the issue in vman so no backport is needed. No documentation is needed either. Things will be fixed on our end.

**Comment by dmurphy18** [comment]
see https://github.com/saltstack/salt-pack/issues/700
