### ISSUE TITLE
downloadonly vs download_only

### ISSUE THREAD

**Issue by brejoc** [saltstack/salt#54790]
### Description of Issue

[This merged PR](https://github.com/saltstack/salt/pull/41210) clashes with the downloadonly parameter we already had for the [yum](https://github.com/Da-Juan/salt/blob/ed8dde469a34b00532b0e0eafa57d1de6fb00aa4/salt/modules/yumpkg.py#L1113) and [zypper](https://github.com/Da-Juan/salt/blob/ed8dde469a34b00532b0e0eafa57d1de6fb00aa4/salt/modules/zypper.py#L898) module. The parameter should be `downloadonly` and not `download_only`.

### Versions Report
Salt >= 2017.7.0.

**Comment by brejoc** [comment]
I'd suggest to *also* support `downloadonly` as an attribute in `aptpkg.py` to not break any existing code and deprecate `download_only` in some of the future releases.

Is it possible to get this into `2019.2.1` as a bugfix?

**Comment by brejoc** [comment]
I've just opened a [draft](https://github.com/saltstack/salt/pull/54793) for the change I had in mind.

**Comment by cmcmarrow** [comment]
Thanks
