### ISSUE TITLE
salt-master causes high cpu usage in 2019.2.1

### ISSUE THREAD

**Issue by paladox** [saltstack/salt#54794]
### Description of Issue

Hi, since updating to 2019.2.1 from 2019.2.0 we are experiencing high cpu usage from salt-master. Another user was asking me about this too (so it's not only me).

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

We use https://github.com/miraheze/puppet/tree/master/modules/salt / https://github.com/miraheze/puppet/tree/master/modules/role/manifests/salt

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Install salt-master version 2019.2.1, watch as the load goes up.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.11 
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-042stab138.1
         system: Linux
        version: debian 9.11 
```

**Comment by Svolentin** [comment]
same.
also, in repos 2019.2.0 version has removed, so you must downgrade from cache

**Comment by paladox** [comment]
I think i found the problem https://github.com/saltstack/salt/issues/54795

(it's the updated minions causing it)

Even though i downgraded the master (including the minion on the master) there was still high load until i downgraded the minions on all hosts.

**Comment by hedrickbt** [comment]
I have created a support ticket for this:
https://help.saltstack.com/hc/en-us/requests/4183

**Comment by dafyddj** [comment]
> also, in repos 2019.2.0 version has removed, so you must downgrade from cache

This seems to be a common misunderstanding. There are instructions on [repo.saltstack.com](https://repo.saltstack.com) on how to pin to a minor release.
