### ISSUE TITLE
Salt dependencies from EPEL-release

### ISSUE THREAD

**Issue by karkey83** [saltstack/salt#54818]
### Description of Issue
We are using EPEL-Repo to install salt-minion and its dependencies.
Is there any way to identify the dependencies so that we can download the rpm's on our local repo, this is to avoid external communication.

Minion version: 2018 and 2019
Master version: 2019.2

**Comment by dmurphy18** [comment]
Yes the dependencies built with Salt  to avoid requiring EPEL are available for Python 2 from https://github.com/saltstack/salt-pack/tree/develop/file_roots/versions and for Python 3 from https://github.com/saltstack/salt-pack-py3/tree/develop/file_roots/versions, with a directory for each point release.  For example: for the dependencies for Redhat 8 Python 3  Salt 2019.2.1, the dependencies can be found in the file https://github.com/saltstack/salt-pack-py3/blob/develop/file_roots/versions/2019_2_1/redhat_pkg.sls

Both of the repositories are open-source.  Typically SaltStack provides the minimum version of a dependency for Salt to operate ( or the version available when the platform was first supported ) with the intention that eventually the OS platform will provide a later version.  An example of this is python-tornado v4.2.1 which was eventually updated on most OS's..

There is a similar https://github.com/saltstack/salt-pack-py3/blob/develop/pillar_roots/versions/2019_2_1/pkgbuild.sls which contains the exact versions of a package and which packages must be built before the package itself is built (that is build_deps).

Packages which have been manipulated will have their release version bumped with an explanation in the changelog.  Efforts have been made to use renamed the packages and still function successfully (upgrades, etc) with EPEL and Redhat but those efforts have come to nought.

If this information is sufficient, please consider closing this issue or let me know if there is any further explanation that I can provide.
