### ISSUE TITLE
enable_ssh_minions missing in conf/master

### ISSUE THREAD

**Issue by jude** [saltstack/salt#54837]
### Description of Issue
The https://github.com/saltstack/salt/pull/44578/files changes added support for enable_ssh_minions, but didn't update conf/master.   

I can add 'enable_ssh_minions: True' to /etc/salt/master to enable to feature, but /etc/salt/master should include the option documentation and default value like the rest of the master options.

Suggested diff:

    diff --git a/conf/master b/conf/master
    index fc49a552e4..57717338bb 100644
    --- a/conf/master
    +++ b/conf/master
    @@ -27,6 +27,9 @@
     # modified files cause conflicts, set verify_env to False.
     #user: root
     
    +# Tell the master to also use salt-ssh when running commands against minions.
    +#enable_ssh_minions: False
    +
     # The port used by the communication interface. The ret (return) port is the
     # interface used for the file server, authentication, job returns, etc.
     #ret_port: 4506

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Jul  9 2019, 16:51:35)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.0.0-23-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by sagetherage** [comment]
closing as fixed
