### ISSUE TITLE
 Salt error 'Failed to import states pip_state' since 2019.2.1+ds-1

### ISSUE THREAD

**Issue by CaptainSanders** [saltstack/salt#54831]
### Description of Issue
After updating the minion salt state requires pip, which I don't use. Before the update state apply functions normally

### Versions Report
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Aug 22 2019, 16:36:40)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-161-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by maikelpoot** [comment]
+1

Found the same problem on Centos 7 machines.
Tracked it down to a formula having:
```filename:
  file.managed:
    - watch:
      - pkg: package-name
```
Changing the `watch` to `require` fixed the error so maybe the culprit is mod_watch?

installing pip on the minion also solved the problem

**Comment by CaptainSanders** [comment]
Nice find! I'll check this and confirm when tested. Installing pip did indeed solve the problem, but pip on Ubuntu has all sorts of dependencies I'd rather not install

**Comment by CaptainSanders** [comment]
After a short testing-round unfortunately it still does not work. Even with require instead of watch (which I need because of services restarting then conf files change, require does not do this) the state call fails when pip is not installed.

**Comment by CaptainSanders** [comment]
Continued in #54755
