### ISSUE TITLE
GPG Rendering issue with binary content

### ISSUE THREAD

**Issue by Vacuois** [saltstack/salt#54836]
### Description of Issue
Salt fail to render the content_pillar of a GPG-encrypted binary cert since upgrading from 2018.4.x / Py2 to 2019.2.x / Py3

```
----------
          ID: /path/to/cert.p12:
    Function: file.managed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/file.py", line 2769, in managed
                  **kwargs
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 4841, in check_managed_changes
                  group, mode, attrs, saltenv, contents)
                File "/usr/lib/python3/dist-packages/salt/modules/file.py", line 4945, in check_file_meta
                  tmp_.write(salt.utils.stringutils.to_str(contents))
                File "/usr/lib/python3/dist-packages/salt/utils/stringutils.py", line 102, in to_str
                  raise exc  # pylint: disable=raising-bad-type
                File "/usr/lib/python3/dist-packages/salt/utils/stringutils.py", line 95, in to_str
                  return _normalize(s.decode(enc, errors))
              UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 1: invalid start byte
     Started: 08:55:13.571809
    Duration: 6.159 ms
     Changes:   
```

### Setup
```yaml
/path/to/cert.p12:
  file.managed:
    - contents_pillar: certificates_p12
    - user: myuser
    - group: mygroup
    - mode: 600
```

### Steps to Reproduce Issue
Encrypt a binary P12 cert with GPG, set it up in a pillar.
Try to deploy it through the content_pillar method on your minion.
### Versions Report
Salt Version:
           Salt: 2019.2.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug 20 2019, 17:12:48)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-48-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by fortunejuggle** [comment]
Hi @Vacuois - we don't use p12 certificates - but with two certificates we also had this error. After we re-encrypted them, everything went as usual.  What is also possible that the key has changed, then it also comes to this error.  Maybe this will help you.

**Comment by Vacuois** [comment]
Hello @fortunejuggle,

I tried to reencrypt the certificate directly, however, still no luck, this is not working, I still have an UTF-8 error :(

Thanks for the help.

**Comment by fortunejuggle** [comment]
hi @Vacuois - can you try to decrypt it with the master key on cmd line? you need that file on the master and run somthing like: `cat <your placed p12 file> | gpg --homedir /etc/salt/gpgkeys/ --encrypt -r <your masters key id>`

**Comment by fortunejuggle** [comment]
did this ever worked? - maybe Iam  wrong. I think about it and you can't add this enrypted p12 to your pillar. you have to place that to `files` and than add it to your filesystem - please refer https://docs.saltstack.com/en/latest/ref/states/all/salt.states.file.html - you have to use `source` 
```
/path/to/cert.p12:
  file.managed:
    - source: salt://<your state/cert.p12
    - user: myuser
    - group: mygroup
    - mode: 600  ```

**Comment by fortunejuggle** [comment]
openssl pkcs12 -export -out keyStore.p12 --inkey key.pem -in cert.pem # it is binary 
gpg --encrypt keyStore.p12 -r <my key> # it remains binary # iam not able to add it to my pillar  eg: ```
��
    eě:[
           �~�o_,�p":4r��
                         �{��/��CS9�]7��!�z}ۅv'X���$��U��q�`���b�
�':;S����?L�ja��LZ�}��Y�+�������[��"yu-��o���v3�e�>h�.����3��0��^@6��T��l�N"Ey�����Z��
�NX�����XD-ĝ]�߷���_xI�L;�PH��24x�~���]�K�񀧻�r�_Q]uhZ1�E�z�I!��                       �/�e(����,���v�
                                                                 �F�
 ```

**Comment by Vacuois** [comment]
Re,

this is working fine when I'm decrypting the GPG-encrypted content from the command line on the master:
`cat toto.txt | gpg --homedir /etc/salt/gpgkeys/ -d`

And I don't have any issue encrypting the file with GPG:
`gpg --output toto.txt --encrypt -r "Salt Pillar GPG Key" cert.p12`

```
file cert.p12                                     
cert.p12: data
```

And yes, it used to work on Py2 / 2018.4.

I guess I could use the file.managed with the source attribute, but I'd rather keep the cert encrypted in my pillars if possible.

**Comment by fortunejuggle** [comment]
ok - i just wonder if it is actually a real p12 cert or just a gpg encrypted certificate - can you just provide your clear pillar  - you can use dummys for confidential data

**Comment by Vacuois** [comment]
Well, the cert is just binary content.
I can provide it to you, but I'm not sure It'll help.

I've been doing some more testing, and it seems that if I b64 encore the data before GPG-encrypting it, it's working.

I now have something like that in my state:
```YAML
/path/to/cert.p12:
  file.decode:
    - contents_pillar: cert_p12
    - encoding_type: base64

Set proper permission on P12 cert:
  file.managed:
    - name: /path/to/cert.p12
    - user: user
    - group: group
    - mode: 600
```

I'm still not sure where the original issue come from, to be honest.

**Comment by fortunejuggle** [comment]
Hi again, i think this makes sense - it is stated in the Dokumentation. I found it yesterday. `The simplest way to embed binary data in your pillar is to make use of YAML's built-in binary data type, which requires base64 encoded data.`  And I found this - https://github.com/saltstack/salt/pull/52334/commits -  the docs are updated with 2019.02

**Comment by Vacuois** [comment]
Indeed.
Here's the documentation: https://docs.saltstack.com/en/latest/topics/pillar/#binary-data-in-the-pillar
Well, I'm still not sure why it worked before the upgrade.

But as this seem to be intended and I found a "workaround" (or a proper working way), I'll close this issue.

Thanks @fortunejuggle for your help! :)

**Comment by mitar** [comment]
Using YAML built-in binary data type does not work with salt-ssh, sadly. #31576
