### ISSUE TITLE
Changes from schedule.enable / schedule.disable not persisted

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#54847]
### Description of Issue
Changes made by `salt-call schedule.enable` or `salt-call schedule.disable` are not reflected on-disk in `/etc/salt/minion.d/_schedule.conf`, but do appear in `salt-call schedule.list`. Similarly, `salt-call schedule.reload` doesn't have any affect on the global status.

https://gist.github.com/OrangeDog/fd08470a682752347efd52fe7a5b830d

**Comment by garethgreenaway** [comment]
This should be a simple fix and we'll get it for the Neon release since it would technically be a new feature, we currently support being able to persist when enabling and disabling individual jobs but not the entire scheduler.

**Comment by OrangeDog** [comment]
Still a desired feature

**Comment by OrangeDog** [comment]
This was released in 3000.
