### ISSUE TITLE
salt pillars fail to render in 2019.8 if an unused environment is listed in the topfile.

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#54864]
### Description of Issue
I guess this has changed since 2019.2. If an environment is specified in a pillar's topfile, but is not specified in the salt configuration (not used anywhere). Salt fails to render all pillars. This situation might happen if you're using salt-masterless to transition to a new environment by writing extra config to `/etc/salt/minion.d` so that the final salt environment can be enabled from a salt-masterless deployment.

### Setup
First create your states/pillars with the following (bash):
```
mkdir -p /srv/test/{salt,pillar}
cat >/srv/test/pillar/top.sls <<'EOF'
master:
 '*': []
unused:
 '*':
  - nothing
EOF
touch /srv/test/pillar/nothing.sls
cat >/srv/test/salt/top.sls <<'EOF'
master:
    '*': []
EOF
```
This creates an empty state that does nothing, and pillars that also do nothing. The pillar includes two "environments". The unused environment needs something defined (which implies that salt might be trying to render the pillars for all environments). 

Next create a salt-minion configuraton that references only the environment that you want to use.
```
cat >|/etc/salt/minion <<'EOF'
conf_file: /etc/salt/minion
log_level: debug
root_dir: /
saltenv: master
pillarenv: master
file_roots:
 master:
  - /srv/test/salt
pillar_roots:
 master:
  - /srv/test/pillar
EOF
```

### Steps to Reproduce Issue
Now we can use salt-call to render the topfile, and lo-and-behold salt complains about a missing pillar environment.
```
[root@master srv]# salt-call -linfo --local state.show_top
[ERROR   ] Received bad data when setting the match from the top file
[ERROR   ] Received bad data when setting the match from the top file
[CRITICAL] Pillar render error: No matching pillar environment for environment 'unused' found
[INFO    ] Loading fresh modules for state activity
Error running 'state.show_top': Pillar failed to render. Additional info follows:

- No matching pillar environment for environment 'unused' found
```
### Versions Report
```
Salt Version:
           Salt: 2019.8.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Apr 30 2019, 15:54:43)
   python-gnupg: Not Installed
         PyYAML: 5.1
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 5.0.2
            ZMQ: 4.3.1

System Versions:
           dist: fedora 30 Thirty
         locale: UTF-8
        machine: x86_64
        release: 4.14.96-coreos
         system: Linux
        version: Fedora 30 Thirty
```

**Comment by arizvisa** [comment]
actually it appears that all pillar environments are merged regardless of setting `top_file_merging_strategy`.. lmk if you care about a testcase for this symptom for some reason.

**Comment by waynew** [comment]
@arizvisa thanks for the report!

However, 2019.8 isn't actually a released version of Salt. I think you must have directly installed from a branch - the most recent release of salt is 2019.2.0. 2019.2.1 is available as an archived version, and we expect to release 2019.2.2 next week.

If this *is* actually a problem in 2019.2.0, or our 2019.2.2 pre-release, please let me know, and I'll re-open this issue.

**Comment by arizvisa** [comment]
Gotcha. Actually, there's a v2019.8 tag.

**Comment by arizvisa** [comment]
I forgot I created this issue actually. Thanks for going through it.

Until I encountered this issue my system would automatically grab the latest tag from the git repo assuming it was the latest release which is wrong.

**Comment by hegyre** [comment]
Got the exact same issue.
I fixed it by setting `pillarenv_from_saltenv: True` in the minion file.
