### ISSUE TITLE
salt cloud fails to start minion on windows after upgrade from 2018.3.4 to 2019.2.1

### ISSUE THREAD

**Issue by Mapel88** [saltstack/salt#54904]
### Description of Issue
After upgrading from 2018.3.4 to 2019.2.1 salt-minion fails to start on windows when deploying server via salt cloud.
Service is still stopping while start command is activated.

### Setup
I'm using salt minion version 2018.3.4 setup due to a bug in "system.join_domain" #54869 but this happens in version 2019.2.1 as well.

My cloud profile:
```
nl1-win2016:
  provider: nlxen
  image: windows_2016_web_template
  clone: True
  win_installer: /srv/salt/win/files/Salt-Minion-2018.3.4-Py3-AMD64-Setup.exe
  win_username: AdminUser
  win_password: 'AdminPassword'
  minion:
    master:
      - myMaster.my.domain.com
  ipv4_cidr: 1.1.1.1/24
  ipv4_gw: 1.1.1.254
  use_winrm: False
  winrm_verify_ssl: False
  winrm_port: 5986
  port_timeout: 30

```
### Steps to Reproduce Issue
```
[INFO    ] Connecting to SMB Tree \\1.1.1.1\ADMIN$
[INFO    ] Creating open to PAExec file with delete on close flags
[INFO    ] Disconnecting from SMB Tree \\1.1.1.1\ADMIN$
[DEBUG   ] psexec connected...
[DEBUG   ] SMB port 445 on 1.1.1.1 is available
[DEBUG   ] Logging into 1.1.1.1:445 as AdminUser
[INFO    ] Get connection smbprotocol
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[DEBUG   ] Deleting PAExec service at the end of the process
[INFO    ] Connecting to SMB Tree \\1.1.1.1\ADMIN$
[INFO    ] Creating open to PAExec file with delete on close flags
[INFO    ] Disconnecting from SMB Tree \\1.1.1.1\ADMIN$
[DEBUG   ] _delete_directory_smbprotocol - share: C$, path: salttemp
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[DEBUG   ] Deleting PAExec service at the end of the process
[INFO    ] Connecting to SMB Tree \\1.1.1.1\ADMIN$
[INFO    ] Creating open to PAExec file with delete on close flags
[INFO    ] Disconnecting from SMB Tree \\1.1.1.1\ADMIN$
[DEBUG   ] Run psexec: sc start salt-minion
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[DEBUG   ] Deleting PAExec service at the end of the process
[INFO    ] Connecting to SMB Tree \\1.1.1.1\ADMIN$
[INFO    ] Creating open to PAExec file with delete on close flags
[INFO    ] Disconnecting from SMB Tree \\1.1.1.1\ADMIN$
[ERROR   ] Failed to start Salt on host nl1-test
[DEBUG   ] boot return: {u'Error': {u'Not Deployed': u'Failed to start Salt on host nl1-test'}}
```
No other related salt-minion info in the debug log or minion log.
I can see the minion setup file is copied to salttemp, and salt minion is installed, but fails to start automatically. It does start manually.
I checked the salt-minion during the installation part and noticed that it was running, then it was stopping to apply minion configs. While it was stopping "Failed yo start minion" error appeared, which means the start action took place while it was stopping.
Need to add more delay / check service status before trying to start.

### Versions Report
minion version 2018.3.4 & 2019.2.1

Salt Version:
           Salt: 2019.2.1

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.7.0
         pygit2: 0.26.4
         Python: 2.7.5 (default, Oct 30 2018, 23:45:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.26.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by dmurphy18** [comment]
Closing this since 2019.2.x is long since EOL
