### ISSUE TITLE
Minor type-o in salt.modules.dpkg_lowpkg._get_pkg_info() when calling cmd.run_all

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#54907]
### Description of Issue
This is pretty minor and should get low priority, but when `_get_pkg_info` from `salt.modules.dpkg_lowpkg` calls `cmd.run_all`, the original author mistakenly passed the parameter `python_chell=False`.

This should probably be `python_shell=False`, but since the `python_shell` parameter for `cmd.run_all` is `None` by default, the misspelling doesn't directly affect anything.

### Setup
Found while tracking down some other issue.

### Steps to Reproduce Issue
File and line-number is in `salt/modules/dpkg_lowpkg.py:239` which is linked at
https://github.com/saltstack/salt/blob/develop/salt/modules/dpkg_lowpkg.py#L329

### Versions Report
Looks like it was introduced by commit 1aa8a8509fca5ca92a5e624a056ee460654b627d which is from v2016.3.

**Comment by jgphilpott** [comment]
:)

**Comment by arizvisa** [comment]
This type-o hasn't been fixed yet. The PR is there, but it hasn't been merged.

**Comment by spencer-burke** [comment]
Hello, I will take care of this typo.

**Comment by arizvisa** [comment]
good luck. I've tried to fix type-o's before and they've made me write unit tests for them.
