### ISSUE TITLE
pip.installed on python3 salt-minion uses pip3 to install modules

### ISSUE THREAD

**Issue by ipsecguy** [saltstack/salt#54905]
I am using the python3 version of the salt-minion 2019.2.1 on Raspberry Pi 4 - Master is running 2019.2.1 on Py2 with x86

Using a state with pip.installed (in my case fritzcollectd) installs the pip module with pip3.

I need to use pip - not pip3 - to install it (as collectd is using python2 for now)

This seems to be unrelated to Raspian version 10.

I assume the py3 version of salt uses pip3 to install pip packages, the py2 version pip? If so this prevents managing py3 services with py2 and vice versa, a nightmare for migration scenarios.

### Steps to Reproduce Issue

```
pip uninstall fritzconnection fritzcollectd
pip3 uninstall fritzconnection fritzcollectd
pip list | grep fritz
pip3 list | grep fritz
```

After running the state with pk.installed

```
pip list | grep fritz
pip3 list | grep fritz
fritzcollectd   0.6.3
fritzconnection 0.7.3
```

### Versions Report

```
(on the master) salt --versions-report
Salt Version:
           Salt: 2019.2.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Aug 22 2019, 16:36:40)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-1075-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

I am using the python3 version of the salt-minion 2019.2.1 on Raspberry Pi 4 - Master is running 2019.2.1 on Py2 with x86

**Comment by max-arnold** [comment]
By default Salt uses pip from currently running Python: https://github.com/saltstack/salt/blob/develop/salt/modules/pip.py#L146-L148

However, you can specify the `bin_env` argument that points to absolute path to a virtual environment directory or absolute path to a pip executable: https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html#salt.states.pip_state.installed

**Comment by dwoz** [comment]
@ipsecguy can you verify using `bin_env` resolves this for you?

**Comment by ipsecguy** [comment]
Yes, adding - bin_env: /usr/bin/pip resolves that issue, i.e. python2 pip is resolved that. Should be put in the documentation.

**Comment by waynew** [comment]
@ipsecguy would you be willing to put together a simple PR adding that information? If you need help I'd be happy to point you in the right direction.
