### ISSUE TITLE
AIX 2019.2.1 Minions not starting. OSError: SemLock

### ISSUE THREAD

**Issue by kappacher** [saltstack/salt#54912]
### Description of Issue
Changes for platform Darwin in Salt Source 2019.2.1 are incompatible with Platform AIX.
Thus, AIX minions cannot even start.

### Setup
AIX Minion with Salt Source 2019.2.1
After inserting IF-Stmt for platform Darwin, we have no exception for AIX:
IF-Stmt should be:   if is_darwin() or is_aix()  .....
Queue maxsize is also used for SemLock maxvalue, but AIX defines maxvalue=32767. 

### Steps to Reproduce Issue
/opt/lib/python2.7/site-packages/salt/log/setup.py:844 (incl. lines before):
    if __MP_LOGGING_QUEUE is None:
        if is_darwin():
            __MP_LOGGING_QUEUE = multiprocessing.Queue(32767)
        else:
            __MP_LOGGING_QUEUE = multiprocessing.Queue(100000)

### Versions Report
oslevel: AIX 7.1.5.2, applies to AIX versions 6.1, 7.1, 7.2 and Python 3.7.3 32/+64bit .
Bug is described properly. Versions Report is irrelevant.

**Comment by dmurphy18** [comment]
@kappacher Wondering how you are installing Salt 2019.2.1 onto AIX, given I have not built packages for 2019.2.1 yet, but will fix the issue for 2019.2.2 which should be released soon for the Linux platforms

**Comment by kappacher** [comment]
Hello, we are building AIX Minions (incl Py3.7/32bit) ourselves, using "tcp transport" only (ignoring ZMQ), and M2Crypto/pycryptodome instead of pycrypto. This issue applies to AIX 6.1 / 7.1 / 7.2, SEM__MAX_VALUE=32767. We are also testing with Py3.7/64bit at the moment.

**Comment by dmurphy18** [comment]
@kappacher Thanks for letting me know.  SaltStack doesn't build for AIX 6.1 since EOL.  will be sure to add the fix in Salt 2019.2.2.

**Comment by kappacher** [comment]
Just for clarification/correction: Error occurs with Python 2.7.15, not with Python 3.7.3. Today, I succeeded with compiling Python 3.8 / 64bit with 2019.2.1, and I did not encounter this issue, as far as I can remember. I thought it's strictly AIX-specific. Now, I am confused. I will try to redo this scenario.

**Comment by kappacher** [comment]
I have checked it once again. 2019.2.0 does not have this if-Stmt. 2019.2.1 with Python2.7 has got this issue ( because of the "if is_darwin()"  affecting all 3 AIX releases), but with Python3.8 it's fine! For me, there is no pressure, because we have to patch many AIX-specific issues in the .py Code. Moreover, I want to switch to Py38/64bit/2019.2.2 with the risk of additional "new Py38 symptoms".

**Comment by kappacher** [comment]
For Python3.8: salt-call works without Patch, but salt-minion needs the Patch, as proposed for Python2.7.
My temporary workaround is:
/opt/lib/python2.7/site-packages/salt/log/setup.py:844 (incl. lines before):
if is_darwin():
__MP_LOGGING_QUEUE = multiprocessing.Queue(32767)
else:
__MP_LOGGING_QUEUE = multiprocessing.Queue(**32767**)   # old: 100000
Better would be:   if is_darwin() or is_aix() ...

**Comment by dmurphy18** [comment]
gone to QA for Salt 3000

**Comment by dmurphy18** [comment]
@kappacher Sorry for the delay but the latest version has just gone live, Salt 3000.1.  Please confirm that the fix is correct and if so, consider closing this issue
