### ISSUE TITLE
How to enable file eauth system to salt-api?

### ISSUE THREAD

**Issue by xq2248** [saltstack/salt#54944]
We want to use file eauth system for restful calls to salt-api. 
The salt-api returns 401 Unauthorized, as file auth module is disabled.

 curl -X POST -k https://127.1:8000/login \
  -H 'Accept: application/json' \
 -H 'Content-type: application/json' \
 -d '[{
        "client": "local",
        "username": "dean",
      "password": "goneFishing",
         "eauth": "file"
    }]'

The failed logs in /var/log/salt/master as follows:
2019-10-10 18:55:08,460 [salt.auth        :296 ][DEBUG   ][21340] The eauth system "file" is not enabled
2019-10-10 18:55:08,460 [salt.auth        :297 ][WARNING ][21340] Authentication failure of type "eauth" occurred.
2019-10-10 18:55:08,460 [salt.master      :2030][WARNING ][21340] Authentication failure of type "eauth" occurred.

The config external_auth and  eauth_acl_module  in /etc/salt/master as follows:

external_auth:
    file:
        ^filename: /etc/insecure-user-list.txt
        gene:
            - .*
        dean:
            - test.*

eauth_acl_module: file

[root@node1 ~]# cat /etc/insecure-user-list.txt
dean:goneFishing
gene:OceanMan

**Comment by xq2248** [comment]
[root@node1 ~]# salt -V
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: 1.3.8
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 25 2019, 21:02:35)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: 0.6.6
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.4.1708 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.11.6.el7.x86_64
         system: Linux
        version: CentOS Linux 7.4.1708 Core

**Comment by xq2248** [comment]
I found the problem.
The config item external_auth of /etc/salt/master was overrided by /etc/salt/master.d/eauth.conf.
The file auth module is appended to /etc/salt/master.d/eauth.conf then it works.

 [root@node1 master.d]# cat /etc/salt/master.d/eauth.conf 
 external_auth:
     pam:
       saltapi:
         - .*  
         - '@wheel'  
         - '@runner' 
     file:
       ^filename: /etc/salt/salt-user-list.txt
       ^filetype: text
       gene:
         - .*
         - '@wheel'
         - '@runner' 
       dean:
         - test.*

**Comment by xq2248** [comment]
Problem solved

**Comment by sooraj2589** [comment]
> Problem solved

How you created those users in insecure-user-list.txt? is the dummy user or linux accounts?
