### ISSUE TITLE
onchanges always fires even when a file has not changed

### ISSUE THREAD

**Issue by kangelos** [saltstack/salt#54947]
### Description of Issue
onchanges cmd gets executed every time even though the watched file has no changes

### Setup
update grub:
  file.managed:
    - name: /etc/default/grub
    - source: salt://common/files/grub.sls
  cmd.run: 
    - name: update-grub
    - onchages:
      - file: /etc/default/grub

### Steps to Reproduce Issue
mox-node2:
----------
          ID: update grub
    Function: file.managed
        Name: /etc/default/grub
      Result: True
     Comment: File /etc/default/grub is in the correct state
     Started: 17:05:39.147293
    Duration: 44.95 ms
     Changes:   
----------
          ID: update grub
    Function: cmd.run
        Name: update-grub
      Result: True
     Comment: Command "update-grub" run
     Started: 17:05:39.192976
    Duration: 897.345 ms
     Changes:   
              ----------
              pid:
                  4406
              retcode:
                  0
              stderr:
                  Generating grub configuration file ...
                  Found linux image: /boot/vmlinuz-4.19.0-6-amd64
                  Found initrd image: /boot/initrd.img-4.19.0-6-amd64
                  Found linux image: /boot/vmlinuz-4.19.0-5-amd64
                  Found initrd image: /boot/initrd.img-4.19.0-5-amd64
                  done
              stdout:

Summary for mox-node2
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time: 942.295 ms

### Versions Report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.1 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.1

**Comment by Ch3LL** [comment]
looks like there is a spelling error: `onchages` needs to be `onchanges`
