### ISSUE TITLE
Docs not rendered online for pkg runner

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#54987]
### Issue
Online documentation is missing an expansive portion of `pkg` runner documentation

### Description
Was looking for the online documentation for `pkg.version` runner, since it wasn't working for one of my packages on a Centos 7 virtual machine. I found this webpage: https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.pkg.html

### Notes
I used `salt \* sys.doc pkg` in terminal and got a proper full list of the runner's documentation.
So the documentation exists but it wasn't properly built for the rendered documentation.

**Comment by garethgreenaway** [comment]
@alan-cugler Thanks for the report.  The output from `sys.doc` is showing the docs for the pkg execution module, not the pkg runner docs.  To show the runner docs from the command line you can use `sys.runner_doc`.

**Comment by alan-cugler** [comment]
haha my mistake, thanks
