### ISSUE TITLE
iLO module does not work on python3

### ISSUE THREAD

**Issue by nfarhadian** [saltstack/salt#54989]
### Description of Issue
iLO module does not work on python 3 and following error is returned:
```Passed invalid arguments: a bytes-like object is required, not 'str'.```

I read the source code and it seems "mode" is not passed to "NamedTemporaryFile" and since default mode is "w+b" I got this problem.
[Here](https://github.com/saltstack/salt/blob/124c8ecb3c93c5d5b5f1e1265771f91a92817883/salt/modules/ilo.py#L42) is the mentioned line of code

I fixed this issue by adding " mode='w' " to this file

### Steps to Reproduce Issue
salt-call ilo.network

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 4.0.2
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.9
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-0.bpo.5-amd64
         system: Linux
        version: debian 9.9
```

**Comment by garethgreenaway** [comment]
@nfarhadian Thanks for the report.  It sounds like you have an understanding of where the issue is, would you be able to produce a pull request with the fix and a regression test so we can make sure this doesn't happen with future changes?

**Comment by nfarhadian** [comment]
Hi
Unfortunately I'm not experienced in developing using python (Actually I'm an operation guy maintaining linux systems)
I have read tests of this module, but couldn't figure out how can I test creation of a file
Sorry for late response
