### ISSUE TITLE
Python package distro should not be imported on Windows

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#55023]
### Description of Issue
[salt/version py imports distro](https://github.com/saltstack/salt/blob/29a016f78e80633a23ada1af3fba5580b81969b7/salt/version.py#L22)

[distro does not support Windows](https://github.com/nir0s/distro/issues/177)

Running salt/version.py on Windows results in 

    ImportError: No module named 'distro'

Current Workaround is to install distro on Windows.

**Comment by xeacott** [comment]
I have this in a WIP PR, just thinking about what test needs to be added to address behavior.

**Comment by xeacott** [comment]
https://github.com/saltstack/salt/pull/54953

**Comment by markuskramerIgitt** [comment]
Thanks
I commented there.

I suggest to simply call the module, as a test.
Even without checking the result, it serves as a test case.

**Comment by markuskramerIgitt** [comment]
See the PR
