### ISSUE TITLE
salt.runners.cloud missing function map_destroy (or equivalent)

### ISSUE THREAD

**Issue by dkfsalt** [saltstack/salt#55033]
### Description of Issue

salt.runners.cloud has a map_run function, but no map_delete/map_destroy function. So you can use the runner to execute a cloud map, but you can't also use it do delete the servers in the map.

There also doesn't appear to be a way to pass a "destroy" parameter to the runner either.

### Setup

1. Install salt-cloud
1. Configure cloud provider
1. Configure cloud profile
1. Configure cloud map

Try to find a way to get the runner to delete minions in the map file. 

### Steps to Reproduce Issue
Look at the docs...  https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.cloud.html
You will notice that there is only one function to deal with cloud maps.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: 5.6.0
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by garethgreenaway** [comment]
@saltstack/team-cloud Anyone from the cloud team have thoughts on this one?
