### ISSUE TITLE
repo.saltstack.com/#debian suggested repo has no release file

### ISSUE THREAD

**Issue by johnkeates** [saltstack/salt#55035]
### Description of Issue
The repository suggested and installed has no release file giving an error in APT
```
E: The repository 'https://repo.saltstack.com/py3/debian/10/amd64/latest buster Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

```

### Setup
Debian 10

### Steps to Reproduce Issue
- Install Debian 10
- Add the saltstack Debian 10 Py3 repo
- apt-get update

**Comment by garethgreenaway** [comment]
@dmurphy18 Thoughts on this one?

**Comment by nbraud** [comment]
Duplicate of #54979.  TL;DR: The repository doesn't have a `buster` suite because no release of Salt supports Debian 10 (buster) yet.

**Comment by johnkeates** [comment]
Commented on the other one as well; since 2019.2.2 is just released, would that then create the first Buster release?

**Comment by johnkeates** [comment]
This has been resolved, the py3 repo now contains a Buster release.
