### ISSUE TITLE
Ubuntu 18.04.3 AWS image urllib3 incompatibility with salt 2018.3.4 

### ISSUE THREAD

**Issue by nix-power** [saltstack/salt#55042]
### Description of Issue
When trying to install docker-ce with salt state, got the following error
----------
          ID: docker_ce_pip_prerequisities
    Function: pip.installed
      Result: False
     Comment: An importable Python 2 pip module is required but could not be found on your system. This usually means that the system's pip package is not installed properly.
     Started: 16:03:47.948674
    Duration: 745.594 ms

The problem can be resolved by
pip install --upgrade urllib3==1.22

### Setup
salt-mininn has been installed with the following command
./bootstrap-salt.sh -F -j '{"master": "10.0.0.1"}' stable 2018.3.4

### Versions Report
Ubuntu 18.04.3
asn1crypto==0.24.0
awscli==1.16.261
backports-abc==0.5
botocore==1.12.251
certifi==2018.1.18
chardet==3.0.4
colorama==0.4.1
cryptography==2.1.4
docutils==0.15.2
enum34==1.1.6
futures==3.3.0
idna==2.6
ipaddress==1.0.17
Jinja2==2.10
jmespath==0.9.4
keyring==10.6.0
keyrings.alt==3.0
Mako==1.0.7
MarkupSafe==1.0
msgpack==0.5.6
psutil==5.4.2
pyasn1==0.4.7
pycrypto==2.6.1
pygobject==3.26.1
pyOpenSSL==17.5.0
python-apt==1.6.4
python-dateutil==2.8.0
python-gnupg==0.4.1
pyxdg==0.25
PyYAML==5.1.2
pyzmq==16.0.2
requests==2.18.4
rsa==3.4.2
s3transfer==0.2.1
salt==2018.3.4
SecretStorage==2.3.1
singledispatch==3.4.0.3
six==1.11.0
systemd-python==234
tornado==4.5.3
urllib3==1.25.6

Salt Version:
           Salt: 2018.3.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: 0.4.1
         PyYAML: 5.1.2
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
         dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1048-aws
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by garethgreenaway** [comment]
@nix-power Thanks for the report.  So far I haven't been able to reproduce this issue.  Would you be able to provide the state file that you're using?  Thanks!

**Comment by nix-power** [comment]
Hi, here is the state:
{% from 'apps/docker-ce/map.jinja' import docker_ce_details with context %}

docker_ce_repository:
  pkgrepo.managed: {{ docker_ce_details.repo | json }}

docker_ce_prerequisities:
  pkg.installed:
    - pkgs: {{ docker_ce_details.pre_pkgs }}
    - require_in:
      - pkgrepo: docker_ce_repository

docker_ce_pip_prerequisities:
  pip.installed:
    - pkgs: {{ docker_ce_details.pre_pip_pkgs }}
    - require:
      - pkg: docker_ce_prerequisities
    - failhard: True

docker_ce_packages:
  pkg.installed:
    - pkgs: {{ docker_ce_details.pkgs }}
    - require:
      - pkgrepo: docker_ce_repository
    - failhard: True

docker_service:
  service.running:
    - name: docker
    - enable: True
    - reload: True
    - require:
      - pkg: docker_ce_packages
==========================================
map.jinja:
{% set docker_ce_details = salt.grains.filter_by({
  'Debian' : {
    'repo' : [
      {'humanname' : 'Docker-CE Repository'},
      {'name' : 'deb [arch=' + salt['grains.get']('osarch') + '] https://download.docker.com/linux/' +  salt['grains.get']('osfullname')|lower + ' ' 
                + salt['grains.get']('oscodename') + ' stable'},
      {'key_url' : 'https://download.docker.com/linux/' + salt['grains.get']('osfullname')|lower + '/gpg'},
      {'file': '/etc/apt/sources.list.d/docker-ce.list'},
      {'gpgcheck' : 1}
    ],
    'pre_pkgs': [
      'apt-transport-https',
      'ca-certificates',
      'curl',
      'software-properties-common',
      'python-pip'
    ],
    'pre_pip_pkgs': [
      'docker'
    ],
    'pkgs' : [
      {'docker-ce': salt['pillar.get']('docker_ce_version')}
    ] 
  }
}, default='Debian') %}
