### ISSUE TITLE
service state module missing "status" function

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#55044]
### Feature Request
Add a status function for the services state module.

### Description of Issue
I am statefully automating setup devices and a visual aid of outcome confirmation is logs.
We have the service module which allows us to run `systemctl` commands as salt states. However, I found there are state functions for start, restart, stop but not just status?

### Resource
- https://docs.saltstack.com/en/latest/ref/states/all/salt.states.service.html

**Comment by garethgreenaway** [comment]
@alan-cugler Thanks for the report.  Not sure a `status` function would fit with the service state as the idea behind states is they're setting the state of something, in this case the state of a service.  A different approach would be to use the `module.run` state module function to run the `service.status` execution module function.
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.module.html

**Comment by alan-cugler** [comment]
Thanks for the reply, after further offline discussion of why this issue was created it is apparent I either need to start a new issue or SEP more directly arguing for stateful status functions.
