### ISSUE TITLE
Redhat / CentOS 8 PY3 packages are advertised on website but download links are broken

### ISSUE THREAD

**Issue by jodok** [saltstack/salt#55041]
### Description of Issue

on the installation website the instructions for RHEL8 are available (https://repo.saltstack.com/#rhel) - but the packages linked from there don't exist.

**Comment by dmurphy18** [comment]
@jodok Please read the Warning message, about OS support introduced in 2019.2.1.
The archive path http://repo.saltstack.com/py3/redhat/8/x86_64/archive/2019.2.1 exists to allow access.
It is hoped that finally Salt 2019.2.2 will be released next week unless QA find something major broken.

**Comment by jodok** [comment]
thanks and sorry for the noise!
