### ISSUE TITLE
Add state support for pkg.group_install

### ISSUE THREAD

**Issue by racooper** [saltstack/salt#5504]
At the request of @terminalmage I'm entering this ticket based on my query in #salt.  Please add state support for pkg.group_install (in my case, particularly for yum).

**Comment by francis2211** [comment]
I am really interested by this feature too

**Comment by alzadude** [comment]
+1, would be very useful - am evaluating Salt vs Ansible for a project, and Ansible can do this ;)

**Comment by bahymohammmed** [comment]
is there anynews ? , this will be very useful

**Comment by vladionescu** [comment]
I would very much like this as well
