### ISSUE TITLE
Salt keys in both accepted keys and denied keys

### ISSUE THREAD

**Issue by jayshah11** [saltstack/salt#55056]
### Description of Issue
When a saltminion (which had already authenticated with saltmaster successfully) is rebuilt with the same public key that has been accepted by saltmaster, the saltminion lands up in accepted keys as well as denied keys. 

### Steps to Reproduce Issue
1. Configure saltmaster with a public key
2. Build a saltminion with the same public key
3. Rebuild the saltminion

### Versions Report
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 3.2.2
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.27.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by garethgreenaway** [comment]
@jayshah11 Thanks for the report.  Can you give a bit more information about how you're rebuilding the Salt minion and using the same key?  I am only able to reproduce this if I delete the contents of the `/etc/salt/pki/minion` directory but leave the signed key for the minion on the master.

**Comment by jayshah11** [comment]
The minions are KVM guests built via images. Once image is laid down on the host, here is the salt installation process:

1. salt packages are installed
2. minion configuration in place
3. public key is placed in /etc/salt/pki/minion
4. saltminion process is started
