### ISSUE TITLE
network_settings beacon and wildcard

### ISSUE THREAD

**Issue by ebusto** [saltstack/salt#55061]
### Description of Issue
The network_settings beacon does not work when the interface name contains a wildcard (`*`), contrary to the documentation.

```
[CRITICAL] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 2592, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python2.7/dist-packages/salt/minion.py", line 449, in process_beacons
    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member
  File "/usr/lib/python2.7/dist-packages/salt/beacons/__init__.py", line 112, in process
    raw = self.beacons[fun_str](b_config[mod])
  File "/usr/lib/python2.7/dist-packages/salt/beacons/network_settings.py", line 170, in beacon
    expanded_config[match.group()] = config['interfaces'][interface]
TypeError: list indices must be integers, not unicode
```

### Setup
Example beacon.

```
beacons:
  network_settings:
    - interfaces:
        'eth*':
          operstate:
```

### Steps to Reproduce Issue
Enable the above beacon and start the Salt minion (`salt-minion -l debug`).

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Jun 21 2019, 00:38:53)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.11 
         locale: UTF-8
        machine: x86_64
        release: 4.1.0-cl-7-amd64
         system: Linux
        version: debian 8.11

**Comment by garethgreenaway** [comment]
@ebusto Thanks for the report.  I was able to reproduce it and we'll get this fixed asap.

**Comment by garethgreenaway** [comment]
The PR with the fix has been merged so going to close this one out.
