### ISSUE TITLE
cmd.script cant execute, when  minion's "/tmp" noexec Permission

### ISSUE THREAD

**Issue by xingstudy** [saltstack/salt#55071]
### Description of Issue
When I execute"salt myminion  cmd.script salt://scripts/xxx.sh" , return error info: "/bin/bash: /tmp/__salt.tmp.YrblJs.sh: Permission denied"

### Description of Issue
- I mount the directory "/tmp" with patter "noexec" on the minion.
- When I execute"salt myminion  cmd.script salt://scripts/xxx.sh" at mater server , return error info: "/bin/bash: /tmp/__salt.tmp.YrblJs.sh: Permission denied" 

#### minion
- mount -o remount,loop,nodev,nosuid,noexec,rw /tmpfs /tmp
#### master
- execute"salt myminion cmd.script salt://scripts/xxx.sh"

### Versions Report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.2.3
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Jun 21 2019, 14:57:02)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

**Comment by xeacott** [comment]
So, curious about the file permissions set on the file you're specifying as the source file. Shelling out with salt, I believe at least, should have root permissions already.
