### ISSUE TITLE
ubuntu xenial: 2019.2.1 not found on salt repository. but found in archives..

### ISSUE THREAD

**Issue by gaetanquentin** [saltstack/salt#55086]
on ubuntu xenial: trying to upgrade from 2019.2.0 to 2019.2.1:

E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/pool/main/s/salt/salt-cloud_2019.2.1+ds-1_all.deb  404  Not Found
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/pool/main/s/salt/salt-minion_2019.2.1+ds-1_all.deb  404  Not Found
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/pool/main/s/salt/salt-ssh_2019.2.1+ds-1_all.deb  404  Not Found
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/pool/main/s/salt/salt-master_2019.2.1+ds-1_all.deb  404  Not Found
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/pool/main/s/salt/salt-common_2019.2.1+ds-1_all.deb  404  Not Found
E: Failed to fetch http://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest/pool/main/s/salt/salt-api_2019.2.1+ds-1_all.deb  404  Not Found

and it is true: there is 2019.2.0, not 2019.2.1:
http://repo.saltstack.com/apt/ubuntu/16.04/amd64/2019.2/pool/main/s/salt/:

  | salt-api_2019.2.0+ds-1_all.deb | 2019-02-19 18:59 | 13K |  
-- | -- | -- | -- | --
  | salt-cloud_2019.2.0+ds-1_all.deb | 2019-02-19 18:59 | 14K |  
  | salt-common_2019.2.0+ds-1_all.deb | 2019-02-19 18:59 | 6.0M |  
 

but 2019.2.1 can be found in archives....:
http://repo.saltstack.com/apt/ubuntu/16.04/amd64/archive/2019.2.1/pool/main/s/salt/

  | salt-api_2019.2.1+ds-1_all.deb | 2019-10-10 23:06 | 13K |  
-- | -- | -- | -- | --
  | salt-cloud_2019.2.1+ds-1_all.deb | 2019-10-10 23:06 | 14K |  
  | salt-common_2019.2.1+ds-1_all.deb | 2019-10-10 23:06 | 6.1M |  
 

So?

**Comment by dmurphy18** [comment]
@gaetanquentin Please read the Warning message at the top of the page about Salt 2019.2.1.

**Comment by gaetanquentin** [comment]
Where exactly? Don't see anything on https://docs.saltstack.com/en/latest/topics/releases/2019.2.1.html

**Comment by gaetanquentin** [comment]
and 2019.2.2 is already in "previous releases":

![image](https://user-images.githubusercontent.com/5774881/67377463-fd431c00-f585-11e9-8a0b-1810151a8f6a.png)

**Comment by xeacott** [comment]
@gaetanquentin This is the page David was mentioning... https://repo.saltstack.com/

**Comment by gaetanquentin** [comment]
pb corrected
