### ISSUE TITLE
[RC1 Sodium] salt fails on macOS Catalina, due to loading unversioned /usr/lib/libcrypto.dylib

### ISSUE THREAD

**Issue by bayandin** [saltstack/salt#55084]
### Description of Issue
salt crashes on macOS Catalina (10.15). 
I find out that the problem happens on loading `/usr/lib/libcrypto.dylib` library (https://github.com/saltstack/salt/blob/v2019.2.1/salt/utils/rsax931.py#L57). 
There is a similar issue with another python library: https://github.com/wbond/asn1crypto/issues/158

### Setup
- N/A

### Steps to Reproduce Issue
- Install salt to macOS Catalina (10.15) via pip or brew
- Then run `salt --version`, it will crash with `Abort trap: 6`

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
$ python3 --version
Python 3.7.4

$ python3 -m pip install salt
Processing /Users/bayandin/Library/Caches/pip/wheels/2d/98/b0/95c23563552c50dc3349e24745f755fdfb63201bcc4602e988/salt-2019.2.1-cp37-none-any.whl
Requirement already satisfied: msgpack!=0.5.5,>=0.5 in /usr/local/lib/python3.7/site-packages (from salt) (0.5.6)
Requirement already satisfied: PyYAML<5.1 in /usr/local/lib/python3.7/site-packages (from salt) (3.13)
Requirement already satisfied: tornado<5.0,>=4.2.1 in /usr/local/lib/python3.7/site-packages (from salt) (4.5.3)
Requirement already satisfied: MarkupSafe in /usr/local/lib/python3.7/site-packages (from salt) (1.1.1)
Requirement already satisfied: pycrypto>=2.6.1 in /usr/local/lib/python3.7/site-packages (from salt) (2.6.1)
Requirement already satisfied: pyzmq>=2.2.0 in /usr/local/lib/python3.7/site-packages (from salt) (18.1.0)
Requirement already satisfied: requests>=1.0.0 in /usr/local/lib/python3.7/site-packages (from salt) (2.22.0)
Requirement already satisfied: Jinja2 in /usr/local/lib/python3.7/site-packages (from salt) (2.10.3)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/site-packages (from requests>=1.0.0->salt) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /usr/local/lib/python3.7/site-packages (from requests>=1.0.0->salt) (1.25.6)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/site-packages (from requests>=1.0.0->salt) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/site-packages (from requests>=1.0.0->salt) (3.0.4)
Installing collected packages: salt
Successfully installed salt-2019.2.1
```

**Comment by xeacott** [comment]
Thanks for submitting! This may be an issue with `Salt 2019.2.1` as there has some known and unknown issues with it. Maybe an earlier version, such as 2019.2 works for you.

Can you also provide the stack trace as well?

**Comment by bayandin** [comment]
The only way to get a stack trace is via setting [`PYTHONDEVMODE=1`](https://docs.python.org/3.7/using/cmdline.html#envvar-PYTHONDEVMODE) (salt==2019.2.2):
```
$ PYTHONDEVMODE=1 salt
/Users/bayandin/venv/lib/python3.7/site-packages/tornado/httputil.py:106: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class HTTPHeaders(collections.MutableMapping):
Fatal Python error: Aborted

Current thread 0x000000010ed1ad40 (most recent call first):
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364 in __init__
  File "/usr/local/Cellar/python/3.7.4_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 442 in LoadLibrary
  File "/Users/bayandin/venv/lib/python3.7/site-packages/salt/utils/rsax931.py", line 57 in _load_libcrypto
  File "/Users/bayandin/venv/lib/python3.7/site-packages/salt/utils/rsax931.py", line 65 in _init_libcrypto
  File "/Users/bayandin/venv/lib/python3.7/site-packages/salt/utils/rsax931.py", line 96 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/bayandin/venv/lib/python3.7/site-packages/salt/crypt.py", line 69 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/bayandin/venv/lib/python3.7/site-packages/salt/minion.py", line 69 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/bayandin/venv/lib/python3.7/site-packages/salt/utils/job.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/bayandin/venv/lib/python3.7/site-packages/salt/cli/salt.py", line 11 in <module>
  File "<frozen importlib._bootstrap>", line 219 in _call_with_frames_removed
  File "<frozen importlib._bootstrap_external>", line 728 in exec_module
  File "<frozen importlib._bootstrap>", line 677 in _load_unlocked
  File "<frozen importlib._bootstrap>", line 967 in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 983 in _find_and_load
  File "/Users/bayandin/venv/lib/python3.7/site-packages/salt/scripts.py", line 511 in salt_main
  File "/Users/bayandin/venv/bin/salt", line 8 in <module>
Abort trap: 6
```

I also have checked versions `2019.2.1`, `2019.2.0`, and `2018.3.4` — they fail as well.

**Comment by cdalvaro** [comment]
Is the same issue as with Homebrew/homebrew-core#44996

Apparently, some homebrew formulas are outdated and they must be updated in order to fix this issue.

As @fxcoudert pointed out in wbond/asn1crypto#158

**Comment by bayandin** [comment]
@cdalvaro I think it's vice versa.
In https://github.com/Homebrew/homebrew-core/issues/44996 `pip` failed because it used an old version of `asn1crypto`. And the old version of `asn1crypto` was broken on Catalina (similar problem with `/usr/lib/libcrypto.dylib` as this issue about).

For example here it finds `/usr/lib/libcrypto.dylib`: https://github.com/saltstack/salt/blob/v2019.2.2/salt/utils/rsax931.py#L38
And here it tries to load it and crashes:
https://github.com/saltstack/salt/blob/v2019.2.2/salt/utils/rsax931.py#L57

And exactly the same problem is reproducebly on `salt` installed from pypi.

Correct me if I'm wrong.

**Comment by cdalvaro** [comment]
> @cdalvaro I think it's vice versa.
> In [Homebrew/homebrew-core#44996](https://github.com/Homebrew/homebrew-core/issues/44996) `pip` failed because it used an old version of `asn1crypto`. And the old version of `asn1crypto` was broken on Catalina (similar problem with `/usr/lib/libcrypto.dylib` as this issue about).
> 
> For example here it finds `/usr/lib/libcrypto.dylib`: https://github.com/saltstack/salt/blob/v2019.2.2/salt/utils/rsax931.py#L38
> And here it tries to load it and crashes:
> https://github.com/saltstack/salt/blob/v2019.2.2/salt/utils/rsax931.py#L57
> 
> And exactly the same problem is reproducible on `salt` installed from pypi.
> 
> Please correct me if I'm wrong.

Yes, you are totally right, @bayandin 

Another thing I noticed is that after upgrading macOS from Mojave to Catalina in my MacBook `salt` still working.

More even, I was able to copy that installation of `salt` into a Mac with a fresh installation of Catalina where `salt` had been previously installed via homebrew and it wasn't working, and after the copy `salt` began to work perfectly until got updated by revision 1 of the formula.

**Comment by jpmckinney** [comment]
I have the same issue, discussed in the thread at https://github.com/Homebrew/homebrew-core/issues/44996

The problem can’t be solved at Homebrew’s end.

**Comment by jpmckinney** [comment]
After doing `pip install salt salt-ssh` I can run salt and salt-ssh commands without the 'abort trap 6'. Homebrew installs 2019.2.1_1, whereas with pip I installed 2019.2.2, so perhaps the latest version fixes the abort issue?

**Comment by fxcoudert** [comment]
@jpmckinney we welcome a Homebrew pull request to update to the latest version!

**Comment by cdalvaro** [comment]
I can confirm that homebrew/homebrew-core#45895 works on Catalina!

**Comment by bayandin** [comment]
Unfortunately, it doesn't work neither for me nor [for CI:](https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/50594/version=catalina/)
```bash
$ brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/1fa258efcd1ae72e6ecb48d0d81bb338adb12ec3/Formula/salt.rb # Install salt 2019.2.2
$ salt --version
Abort trap: 6
```
I use Python 3.7.4

The same result for me if I installed this version from pypi.

**Comment by cdalvaro** [comment]
So this is my research...

I have installed `salt 2019.2.2` from formula https://raw.githubusercontent.com/Homebrew/homebrew-core/1fa258efcd1ae72e6ecb48d0d81bb338adb12ec3/Formula/salt.rb on my MacBook which has been upgraded from Mojave to Catalina and it is currently running macOS Catalina 10.15.1. `salt-minion` is working perfectly and states are being applied properly.

On the other hand, on my Mac Pro where Catalina was installed as a fresh installation, `salt 2019.2.2` installed with the same formula is not working...

And last test, I have copied my `salt` installation from my MacBook into my Mac Pro, and `salt-minion` is now running properly on my Mac Pro too.

```sh
rsync -aP --delete 2019.2.2_macOS_upgrade_installation/ /usr/local/Cellar/salt/2019.2.2/
```

You can find attached to this comment both salt installations in order to improve this research.

✅ [2019.2.2_macOS_upgrade_installation.tar.gz](https://github.com/saltstack/salt/files/3785740/2019.2.2_macOS_upgrade_installation.tar.gz) - macOS Catalina upgraded from Mojave

❌ [2019.2.2_macOS_new_installation.tar.gz](https://github.com/saltstack/salt/files/3785743/2019.2.2_macOS_new_installation.tar.gz) - macOS Catalina fresh installation

**Comment by mariusvw** [comment]
Workaround that actually worked so far:

```
brew install openssl
cd /usr/local/lib
ln -s /usr/local/opt/openssl/lib/libssl.dylib libssl.dylib
ln -s /usr/local/opt/openssl/lib/libcrypto.dylib libcrypto.dylib
```
You might need to use sudo for the link commands, wasn't needed in my case.

More info
- https://stackoverflow.com/questions/58272830/python-crashing-on-macos-10-15-beta-19a582a-with-usr-lib-libcrypto-dylib/58596931#58596931
- https://github.com/Homebrew/homebrew-core/issues/45687#issuecomment-547102000

**Comment by bayandin** [comment]
Hey @xeacott, is there more information required for the issue? I'll be happy to provide it. Thanks!

**Comment by fxcoudert** [comment]
The problem is here: https://github.com/saltstack/salt/blob/master/salt/utils/rsax931.py#L38

A short reproducer on macOS Catalina:

```
>>> from ctypes.util import find_library
>>> lib = find_library('crypto')
>>> lib
'/usr/lib/libcrypto.dylib'
>>> from ctypes import cdll
>>> cdll.LoadLibrary(lib)
zsh: abort      python3
```

Because unversioned `/usr/lib/libcrypto.dylib` should not be used on macOS Catalina.
What would help is if the build path of libcrypto could be detected during build, and used after that.

**Comment by sromanenko** [comment]
The problem is still here. When I run command salt-ssh -i remotehost test.ping
`remotehost:
    ----------
    retcode:
        1
    stderr:
        Traceback (most recent call last):
          File "/var/tmp/.s_romanenko_5ec184_salt/salt-call", line 27, in <module>
            salt_call()
          File "/var/tmp/.s_romanenko_5ec184_salt/pyall/salt/scripts.py", line 426, in salt_call
            import salt.cli.call
          File "/var/tmp/.s_romanenko_5ec184_salt/pyall/salt/cli/call.py", line 8, in <module>
            import salt.cli.caller
          File "/var/tmp/.s_romanenko_5ec184_salt/pyall/salt/cli/caller.py", line 19, in <module>
            import salt.minion
          File "/var/tmp/.s_romanenko_5ec184_salt/pyall/salt/minion.py", line 69, in <module>
            import salt.crypt
          File "/var/tmp/.s_romanenko_5ec184_salt/pyall/salt/crypt.py", line 69, in <module>
            import salt.utils.rsax931
          File "/var/tmp/.s_romanenko_5ec184_salt/pyall/salt/utils/rsax931.py", line 96, in <module>
            libcrypto = _init_libcrypto()
          File "/var/tmp/.s_romanenko_5ec184_salt/pyall/salt/utils/rsax931.py", line 65, in _init_libcrypto
            libcrypto = _load_libcrypto()
          File "/var/tmp/.s_romanenko_5ec184_salt/pyall/salt/utils/rsax931.py", line 57, in _load_libcrypto
            return cdll.LoadLibrary(lib)
          File "/usr/lib/python3.5/ctypes/__init__.py", line 425, in LoadLibrary
            return self._dlltype(name)
          File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
            self._handle = _dlopen(self._name, mode)
        OSError: /usr/local/opt/openssl@1.1/lib/libcrypto.dylib: cannot open shared object file: No such file or directory
    stdout:`

**Comment by bayandin** [comment]
> OSError: /usr/local/opt/openssl@1.1/lib/libcrypto.dylib: cannot open shared object file: No such file or directory

It looks like it requires `openssl@1.1` brew package.

Have you installed `salt` using `brew` or `pip`? Have you patched an installation somehow (including the creation of symlinks)?

**Comment by sromanenko** [comment]
@bayandin I've installed saltstack and openssl using `brew`
```➜  ~ salt --version
salt 2019.2.2 (Fluorine)
➜  ~ brew list | grep openssl
openssl@1.1```
I've tryed to create symlinks https://github.com/saltstack/salt/issues/55084#issuecomment-552510505 but it hasn't worked.

**Comment by bayandin** [comment]
@sromanenko ah, probably I've misunderstood the original message. Does this stacktrace come from the remote machine?

**Comment by sromanenko** [comment]
@bayandin no, I suppose it comes from my macbook, because remote machine is linux host and I use `salt-ssh`
```
➜  ~ ls /usr/local/opt/openssl@1.1/lib/libcrypto.dylib
/usr/local/opt/openssl@1.1/lib/libcrypto.dylib

➜  ~ brew install openssl
Updating Homebrew...
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/cask).
No changes to formulae.

Warning: openssl@1.1 1.1.1d is already installed and up-to-date
To reinstall 1.1.1d, run `brew reinstall openssl@1.1`
```

**Comment by rbobrovnikov** [comment]
Cryptography meta package upgrade solved my problem on Catalina 10.15.2:

`# pip install --upgrade cryptography`

**Comment by andresvia** [comment]
@rbobrovnikov trying to run pip also crashes with the same error, what does installing those packages actually do? Can they be installed the same way python was installed (brew for example)? Thanks!

**Comment by andresvia** [comment]
All: Probably look at this issue: https://github.com/wbond/asn1crypto/issues/158 and comment: https://github.com/Homebrew/homebrew-core/issues/44996#issuecomment-543945199

**Comment by CodingMinds** [comment]
@bayandin / @sromanenko :
> OSError: /usr/local/opt/openssl@1.1/lib/libcrypto.dylib: cannot open shared object file: No such file or directory

I've the same issue on my end while using `salt-ssh` on OS X Catalina to manage a Ubuntu Bionic host. The Workaround from the last PR Homebrew/homebrew-core#45895 to Homebrew caused this issue. 

The Ubuntu host has no idea about the local brew paths and therefore fails to open `libcrypto.dylib`. Reverting the workaround (https://github.com/Homebrew/homebrew-core/blob/master/Formula/salt.rb#L132) after installing salt via Homebrew fixed that for me, but I don't know if any other Salt functionality is affected. I just tested it with `salt-ssh` which works pretty fine, now.
I guess updating `asn1crypto` on my local host with Catalina fixed the underlying issue (See https://github.com/Homebrew/homebrew-core/issues/44996#issuecomment-550674321).

The first call on each affected host required a thin tarball regeneration with `--regen-thin` to update the changed file on the remote host.

**Comment by waynew** [comment]
Looks like this is an issue kind of across the board with Python, crypto, and Catalina. Dang it, Apple, get it together! 😝

**Comment by waynew** [comment]
I found a workaround [here](https://dbaontap.com/2019/11/11/python-abort-trap-6-fix-after-catalina-update/)

```
cd /usr/local/Cellar/openssl/1.0.2t/lib
sudo cp libssl.1.0.0.dylib libcrypto.1.0.0.dylib /usr/local/lib/
cd /usr/local/lib
sudo ln -s libssl.1.0.0.dylib libssl.dylib
sudo ln -s libcrypto.1.0.0.dylib libcrypto.dylib
```
Basically it appears that asn1crypto is using unversioned crypto libs or something? And Catalina says that's not allowed.

It looks like newer asn1crypto fixes this though? https://github.com/pyca/pyopenssl/issues/874

**Comment by CodingMinds** [comment]
I'm pretty sure this should not be closed. The problem still exists in `2019.2.3`

**Comment by nijotz** [comment]
Homebrew is patching salt until this is fixed: https://github.com/Homebrew/homebrew-core/blob/99ad7c17f96d18ff55251d65e878b04e746d5899/Formula/salt.rb#L130

**Comment by waynew** [comment]
2019.2.3 is in CVE only now. If this is still a problem in v3000 then we can re-open it.

**Comment by nijotz** [comment]
I'm experiencing the problem with v3000. And that homebrew recipe that I linked is for v3000.

**Comment by arren-ru** [comment]
Still doesn't work for me neither versions 2019.2.3 or 3000.
salt-ssh tolds:
```
OSError: /usr/local/opt/openssl@1.1/lib/libcrypto.dylib: cannot open shared object file: No such file or directory
```

I did everything what was suggested by community in this thread and nothing.....

**Comment by bayandin** [comment]
@arren-ru it happens when you use salt from homebrew on mac to connect to Linux remote machine (which doesn't have `/usr/local/opt/openssl@1.1/lib/libcrypto.dylib` file).

I'm removing the patch from homebrew (https://github.com/Homebrew/homebrew-core/pull/51843) and letting salt folks to fix the problem if it still happens.

**Comment by jhass** [comment]
I locally modified the patch to result into

```python
    elif sys.platform == 'darwin':
      return cdll.LoadLibrary('/usr/local/opt/openssl@1.1/lib/libcrypto.dylib')
    else:
        lib = find_library('crypto')
```

Which still isn't ideal, but works for now.

**Comment by johnkeates** [comment]
> Still doesn't work for me neither versions 2019.2.3 or 3000.
> salt-ssh tolds:
> 
> ```
> OSError: /usr/local/opt/openssl@1.1/lib/libcrypto.dylib: cannot open shared object file: No such file or directory
> ```
> 
> I did everything what was suggested by community in this thread and nothing.....

Same issue here and I'm not on Catalina. (Mojave instead)
File exists, but (in my case) salt-ssh still reports 
```OSError: /usr/local/opt/openssl@1.1/lib/libcrypto.dylib: cannot open shared object file: No such file or directory```

**Comment by kaorihinata** [comment]
I've encountered this issue as well, and based on Apple's `dlopen(3)` implementation (`src/dyld.cpp` under the `dyld` project) we can achieve effectively the same result (forbid unversioned loads by policy, and prefer the latest versioned library) by simply globbing the libraries in `/usr/lib` (ignoring the unversioned stub) and reverse sorting (as they do still follow a sane naming scheme.)

Taking the SunOS/AIX exceptions (also in `_load_crypto`) as an example, the following works just fine for me (in `salt/utils/rsax931.py`, after line 47):

```python
        elif salt.utils.platform.is_darwin():
            # Find versioned libraries in system locations, being careful to
            # avoid the unversioned stub which is no longer permitted.
            lib = glob.glob('/usr/lib/libcrypto.*.dylib')
            if lib:
                # Sort so as to prefer the newest version.
                lib = list(reversed(sorted(lib)))
            else:
                # Find library symlinks in Homebrew locations.
                lib = glob.glob('/usr/local/opt/openssl/lib/libcrypto.dylib')
                lib = lib or glob.glob('/usr/local/opt/openssl@*/lib/libcrypto.dylib')
            lib = lib[0] if lib else None
```

This will attempt to use the system libcrypto libraries before falling back to Homebrew. If you haven't installed `openssl` or `openssl@1.1` via Homebrew, then naturally those 2 directories in `/usr/local/opt` won't exist, and you'll be out of luck, but as recently as Catalina you still have compatible libraries in `/usr/lib`. Just avoid the stub.

Anyway, I've not run it through any testing beyond confirming that the `salt` command runs at the moment as I actually started today wanting to give Salt a shot for the first time. Installing Python 3.7, patching timelib, and writing this later, I have yet to do that, but hey, the more you know.

I can submit a Pull request if desired, but I'll need to find the contributor/developer docs.

**Comment by almoore** [comment]
I am having this issue with `salt-ssh 3000.1`
I was able to get it to work with a few additions to the `_load_crypto`.
As recommended by @kaorihinata I added the block for `elif salt.utils.platform.is_darwin():`
I also added a check to the end for if the path exists. 
```
        if not os.path.exists(lib):
            lib = find_library('crypto')
        if lib:
            return cdll.LoadLibrary(lib)
        raise OSError('Cannot locate OpenSSL libcrypto')
```

**Comment by kaorihinata** [comment]
> I also added a check to the end for if the path exists.

`find_library` is already called near the top of `_load_libcrypto` (line 38, just above the SunOS check) which starts us through the remaining check blocks, so there's no need to call it again:

```python
    else:
        lib = find_library('crypto')
        if not lib and salt.utils.platform.is_sunos():
```

Additionally, it would be pretty hard for the path in `lib` to not exist if it hasn't been set to `None` because all checks above use `glob` (which craws directories), or `find_library` (which does the same).

**Comment by almoore** [comment]
@kaorihinata 
Looks like when I brew installed salt it does not match the v3000.1 release. The path for the lib is hard coded `/usr/local/opt/openssl@1.1/lib/libcrypto.dylib` in the brew version for some reason. 

```diff 
38c38
<         lib = find_library('crypto')
---
>         lib = '/usr/local/opt/openssl@1.1/lib/libcrypto.dylib'
47a48,60
>         elif salt.utils.platform.is_darwin():
>             # Find versioned libraries in system locations, being careful to
>             # avoid the unversioned stub which is no longer permitted.
>             import glob
>             lib = glob.glob('/usr/lib/libcrypto.*.dylib')
>             if lib:
>                 # Sort so as to prefer the newest version.
>                 lib = list(reversed(sorted(lib)))
>             else:
>                 # Find library symlinks in Homebrew locations.
>                 lib = glob.glob('/usr/local/opt/openssl/lib/libcrypto.dylib')
>                 lib = lib or glob.glob('/usr/local/opt/openssl@*/lib/libcrypto.dylib')
>             lib = lib[0] if lib else None
55a69,70
>         if not os.path.exists(lib):
>             lib = find_library('crypto')
```

**Comment by kaorihinata** [comment]
@almoore I see. I suppose that's about what we can expect from them. I'll create a Pull Request right now so that we can be done with this.
