### ISSUE TITLE
Misspelling of key "manufacturer" in grains for SunOS

### ISSUE THREAD

**Issue by lucas-sanches** [saltstack/salt#55082]
### Description

`manufacturer` is misspelled as `manufacture` in [salt/grains/core.py](https://github.com/saltstack/salt/blob/49274718d07dfd96cfc9808e88a61fd24a5ca2b0/salt/grains/core.py)'s code. That key might cause issues for someone expecting to receive the data for SunOS in the `manufacturer` key.

### Affected lines

https://github.com/saltstack/salt/blob/49274718d07dfd96cfc9808e88a61fd24a5ca2b0/salt/grains/core.py#L2654
https://github.com/saltstack/salt/blob/49274718d07dfd96cfc9808e88a61fd24a5ca2b0/salt/grains/core.py#L2722
https://github.com/saltstack/salt/blob/49274718d07dfd96cfc9808e88a61fd24a5ca2b0/salt/grains/core.py#L2725

**Comment by xeacott** [comment]
Interesting, thanks for submitting and identifying where the fixes need to go. Go ahead and open a PR with these changes and I'll put all related comments in there.
