### ISSUE TITLE
salt-ssh No ssh binary found in path on Windows

### ISSUE THREAD

**Issue by jro974** [saltstack/salt#55114]
### Description of Issue
salt-ssh is unable to find ssh.exe on Windows

C:\salt\bin\Scripts>salt-ssh.exe salt -r ls -l trace
[DEBUG   ] Missing configuration file: c:\salt\conf\master
[TRACE   ] The required configuration section, 'fluent_handler', was not found the in the configuration. Not loading the fluent logging handlers module.
[TRACE   ] None of the required configuration sections, 'logstash_udp_handler' and 'logstash_zmq_handler', were found in the configuration. Not loading the Logstash logging handlers module.
[DEBUG   ] Configuration file path: c:\salt\conf\master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[TRACE   ] 'ssh' could not be found in the following search path: '[u'C:\\ProgramData\\DockerDesktop\\version-bin', u'C:\\Program Files\\Docker\\Docker\\Resources\\bin', u'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', u'C:\\Python27\\', u'C:\\Python27\\Scripts', u'C:\\ProgramData\\Boxstarter', u'C:\\WINDOWS\\system32', u'C:\\WINDOWS', u'C:\\WINDOWS\\System32\\Wbem', u'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', u'C:\\WINDOWS\\System32\\OpenSSH\\', u'C:\\metasploit-framework\\bin\\', u'C:\\Program Files\\nodejs\\', u'C:\\ProgramData\\chocolatey\\bin', u'C:\\Program Files\\Git\\cmd', u'C:\\Program Files\\Calibre2\\', u'C:\\WINDOWS\\system32', u'C:\\WINDOWS', u'C:\\WINDOWS\\System32\\Wbem', u'C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\', u'C:\\WINDOWS\\System32\\OpenSSH\\', u'C:\\salt', u'C:\\Users\\JulienROUSSELOT\\AppData\\Local\\Microsoft\\WindowsApps', u'C:\\Program Files (x86)\\Sophos\\Sophos SSL VPN Client\\bin', u'C:\\Users\\JulienROUSSELOT\\AppData\\Local\\Programs\\Microsoft VS Code\\bin', u'C:\\Program Files (x86)\\Nmap', u'C:\\Users\\JulienROUSSELOT\\AppData\\Roaming\\npm', u'C:\\Users\\JulienROUSSELOT\\AppData\\Local\\Microsoft\\WindowsApps', u'C:\\Windows\\System32\\OpenSSH', u'c:\\salt\\bin\\lib\\site-packages\\pywin32_system32']'
No ssh binary found in path -- ssh must be installed for salt-ssh to run. Exiting.

>dir c:\Windows\System32\OpenSSH\ssh.exe

19/03/2019  16:02           882 688 ssh.exe

Salt Version:
           Salt: 2019.2.2

**Comment by xeacott** [comment]
Interesting, can you provide a salt --versions-report as well so we can get a bit more info about the system please?

**Comment by jro974** [comment]
Hello Joe

here is the report : 

C:\salt\bin\Scripts>salt-ssh.exe --versions
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.10
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:22:17) [MSC v.1500 32 bit (Intel)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362  Multiprocessor Free


best regards
