### ISSUE TITLE
file.get_selinux_context incorrect works with directories

### ISSUE THREAD

**Issue by alexminder** [saltstack/salt#55152]
### Description of Issue
`file.get_selinux_context` incorrect works with directory as path.

### Steps to Reproduce Issue
```
# salt-call --local file.get_selinux_context /run --out=json
14:50:25 [INFO    ] Executing command ['ls', '-Z', '/run'] in directory '/root' [salt.loaded.int.module.cmdmod]
{
    "local": "system_u:object_r:getty_runtime_t:s0"
}
```
Try to manualy lookup:
```
# ls -Z /run|head -1
      system_u:object_r:getty_runtime_t:s0 agetty.reload

# ls -dZ /run
system_u:object_r:var_run_t:s0 /run
```
As you can see the `file.get_selinux_context` returns selinux context for first file in directory. It is wrong.

### Versions Report
2019.2.2

**Comment by sagetherage** [comment]
PR merged and will be released in Sodium mid-June 2020
