### ISSUE TITLE
Update salt-ssh docs with explicit examples with custom file_roots

### ISSUE THREAD

**Issue by xeacott** [saltstack/salt#55167]
### Description of Issue
This is to address the resolution in issue https://github.com/saltstack/salt/issues/54105

From the current documentation of salt-ssh found [here](https://docs.saltstack.com/en/latest/topics/ssh/) usage of Rosterfile isn't specific enough with file_roots and custom `_module` and `_grains` locations when using an environment that isn't `C:\salt\` or `etc/salt and srv/salt`. So improving documentation and providing a full salt tree with custom locations.

### Setup
None

### Versions Report
User reported 2019.2 but documentation should be updated for master and all branches moving forward.

**Comment by sagetherage** [comment]
closing as merged PR above will be released in Sodium
