### ISSUE TITLE
Missing Modules

### ISSUE THREAD

**Issue by steveno** [saltstack/salt#55172]
### Description of Issue
The master branch is missing the `snap` and `flatpak` modules. What happened to them? Were any other modules removed?

**Comment by frogunder** [comment]
@steveno Thank you for reporting this issue.

@saltstack/team-core Do any of you have any insight to this and can answer this question?

**Comment by max-arnold** [comment]
@steveno These modules only exist in `develop` and `neon` branches. They will be eventually backported to the `master` branch: https://github.com/saltstack/salt/projects/5#column-6831403

**Comment by max-arnold** [comment]
Snap support is now available as a Salt extension: https://github.com/salt-extensions/saltext-snap
