### ISSUE TITLE
CI tests not working "Neither image_id nor an image_search specified for [machine type]"

### ISSUE THREAD

**Issue by LuAPi** [saltstack/salt#55182]
### Description of Issue
All the unit and integration tests in PR https://github.com/saltstack/salt/pull/53404 have stopped running properly and quickly fail with messages of the form:
```
13:35:16  + bundle exec kitchen create py2-centos-7
13:35:16  -----> Starting Kitchen (v1.23.5)
13:35:16  -----> Creating <py2-centos-7>...
13:35:17  >>>>>> Search returned 0 images.
13:35:17  >>>>>> ------Exception-------
13:35:17  >>>>>> Class: Kitchen::ActionFailed
13:35:17  >>>>>> Message: 1 actions failed.
13:35:17  >>>>>>     Failed to complete #create action: [Neither image_id nor an image_search specified for instance py2-centos-7! Please specify one or the other.] on py2-centos-7
```
This happens for all other image types, not just py2-centos-7.

I suspect a misconfiguration of the CI server as I've just been merging changes from 2018.3 while other suspected problems with the CI were fixed. Of the last three builds which were all triggered by merges from 2018.3 The last two exhibited this problem. Dates of builds:
28-Sep-2019 - Did not have this problem
24-Oct-2019 - Problem first observed, thought it might be transient
31-Oct-2019 - Problem observed again so making an issue

### Setup
PR merging into 2018.3

### Steps to Reproduce Issue
Trigger a build on that PR. It might also work on other PRs into the 2018.3 branch, I can't confirm but my PR doesn't change any CI configs so it's probably not caused by my changes since previous builds worked.

### Versions Report
2018.3 branch

**Comment by frogunder** [comment]
@LuAPi Thank you for reporting this issue.

With the new branch strategy https://github.com/saltstack/salt-enhancement-proposals/pull/20 
all new PR's will need to point to the master branch.

**Comment by LuAPi** [comment]
So should all existing PRs which don't work with this new change rebase their changes onto master and change the merge-into branch to master instead of merging into the branch specified in the prior system?

**Comment by frogunder** [comment]
Yes, that should be the correct way. thanks.
