### ISSUE TITLE
salt-minion service (for Windows) fails to start when changing its user to a service user instead of the local admin

### ISSUE THREAD

**Issue by asoliman** [saltstack/salt#55188]
### Description of Issue
I am trying to change the user on the salt-minion service on Windows server. I would like to use a service account that was created with administrative privileges instead of the local administrator account, but the minion fails to restart afterwords, causing the salt-minion service to go into a "Paused" state. 

### Setup
Here's the powershell script I am using to update the user account for the minion service.
$adminUsername="****"
$adminPassword="****"
sc.exe config "salt-minion" obj= ".\$adminUsername" password= "$adminPassword"
Stop-Service -Name salt-minion
Start-Sleep -s 3
Start-Service -Name salt-minion 

### Steps to Reproduce Issue
Here's the result when trying to add a service user instead of the local admin account:
 [SC] ChangeServiceConfig SUCCESS
Start-Service : Failed to start service 'salt-minion (salt-minion)'.
At line:9 char:1
+ Start-Service -Name salt-minion
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OpenError: (System.ServiceProcess.ServiceController:ServiceController) [Start-Service], ServiceCommandException
    + FullyQualifiedErrorId : StartServiceFailed,Microsoft.PowerShell.Commands.StartServiceCommand
 
 
and here's the output of my script when using the local admin user:
 [SC] ChangeServiceConfig SUCCESS

PS C:\Windows\system32>  

### Versions Report
running salt-minion 2.2 currently but tested the above problem on older versions as well.
![Screen Shot 2019-11-02 at 10 27 04 PM](https://user-images.githubusercontent.com/13020927/68081037-8c410700-fdc4-11e9-829a-78019c595da7.jpg)

**Comment by lukasraska** [comment]
What does `c:\salt\var\log\salt\minion` says about the failure?

**Comment by asoliman** [comment]
2019-11-01 11:25:40,792 [salt.crypt       :738 ][CRITICAL][5340] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2019-11-01 11:25:58,260 [salt.crypt       :738 ][CRITICAL][6920] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2019-11-01 11:26:17,058 [salt.crypt       :738 ][CRITICAL][6480] The Salt Master has rejected this minion's public key!
To repair this issue, delete the public key for this minion on the Salt Master and restart this minion.
Or restart the Salt Master in open mode to clean out the keys. The Salt Minion will now exit.
2019-11-01 11:26:36,792 [salt.crypt       :757 ][ERROR   ][6608] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2019-11-04 10:51:01,130 [salt.crypt       :757 ][ERROR   ][2440] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate
2019-11-04 10:51:11,177 [salt.crypt       :757 ][ERROR   ][2440] The Salt Master has cached the public key for this node, this salt minion will wait for 10 seconds before attempting to re-authenticate

**Comment by asoliman** [comment]
I included the log file above. However, when I update the user for the salt-minion service that does not change the log file at all.

**Comment by asoliman** [comment]
I think I found the issue with this. The C:\salt folder was encrypted as part of the script I used to install salt. I used the local admin user account to run that script and that's way it only ran using this account. All the other account did not have permission to modify this folder.

**Comment by Ch3LL** [comment]
to clarify @asoliman are you saying this is fixed and it was only an issue with your custom script?

**Comment by asoliman** [comment]
@Ch3LL Correct! Thank you!
