### ISSUE TITLE
Cannot post JSON with http.query runner

### ISSUE THREAD

**Issue by cruscio** [saltstack/salt#55208]
### Description of Issue

The http.query runner converts JSON to a python dict when passing it as a string in the `data` parameter and there's no way to convert it back to JSON before the HTTP request is made. The data_renderer only applies to `data_file`, not `data` 

I resolved this locally by hacking a bool parameter into `/usr/lib/python3/dist-packages/salt/utils/http.py` that will convert `data` to JSON when `true`

```
    if data_file is None and data_to_json and isinstance(data, dict):
        log.trace('Converting data to json.')
        data = salt.utils.json.dumps(data)
```

Not a great solution, but it worked.  

I _think_ a better solution would be to apply data_renderer to both data_file and data. This is the only place data_renderer is used in `salt.utils.http`:

```
    if data_file is not None:
        data = _render(
            data_file, data_render, data_renderer, template_dict, opts
        )
```

### Setup
Create a new receiver on http://ptsv2.com
Use the generated URL in place of the one in the examples below

### Steps to Reproduce Issue

```
curl -X POST http://ptsv2.com/t/tezq5-1572961067/post -H "Content-Type: application/json"  -d '{"foo": "bar"}'
```
Expected Result: Server receives: `{"foo": "bar"}`
Actual Result: Server receives: `{"foo": "bar"}`
Good result

```
salt-run http.query http://ptsv2.com/t/tezq5-1572961067/post method=POST data='{"foo": "bar"}' header_dict='{"Content-Type": "application/json"}'
```
Expected Result: Server receives: `{"foo": "bar"}`
Actual Result: Server receives: `foo=bar`
Bad result

The `salt-run` command should post the same data as the `curl` command but instead it posts malformed JSON. 

### Versions Report
```
salt --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.15+ (default, Oct  7 2019, 17:39:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.0-66-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by Ch3LL** [comment]
can you try quoting the data like so: `data="'{\"foo1\": \"bar1\"}'"` that worked for me

**Comment by cruscio** [comment]
That worked - I'd still like to request this stay open as a feature request to allow for passing JSON as a data string without having to escape it first. Or apply the `data_render` parameter to the `data` parameter (not just to the `data_file` parameter).

**Comment by cruscio** [comment]
staleaway. Can't think of any reason `data_render` should only apply to file input.

**Comment by Ch3LL** [comment]
you have to escape it because of the way your shell is rendering it, this is not related to salt rendering it.

```
(salt-py2)  ✘ ch3ll@thecakeisalie  ~/git/salt   spm_py3 ●  echo data="'{\"foo1\": \"bar1\"}'"
data='{"foo1": "bar1"}'
```

```
(salt-py2)  ch3ll@thecakeisalie  ~/git/salt   spm_py3 ●  echo data='{"foo": "bar"}'
data={"foo": "bar"}
```

**Comment by cruscio** [comment]
I seem to be failing to communicate what it is I'm asking for here.
