### ISSUE TITLE
Certain LGPO configuration (possibly invalid) induced by Microsoft trips up salt.

### ISSUE THREAD

**Issue by H20-17** [saltstack/salt#55211]
### Description of Issue
Site to Zone Assignment list LGPO causing traceback. I have 99% certainty that this was working in version 2019.2.0 (py3) and it is not working when the minion has version 2019.2.2. I don't know about 2019.2.1.

### Setup
In an sls state file on my salt master called _security_test.sls_, I have the following formula

```
OUR Intranet sites hostname:
    lgpo.set:
        - computer_policy:
            Site to Zone Assignment List:
               Enter the zone assignments here.:
                   hostname.my.org: 1
```

### Steps to Reproduce Issue
Run the following command from the salt-master

```
salt -t 300 some_windows_minion state.apply security_test
```

I get the following big stacktrace

```
some_windows_minion:
------------------------------
         ID: OUR Intranet sites OURITSTOR
    Function: lgpo.set
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt\state.py", line 1933, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt\loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt\states\win_lgpo.py", line 267, in set_
                  hierarchical_return=False)
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 7784, in get
                  return_not_configured=return_not_configured))
                File "c:\salt\bin\lib\site-packages\salt\modules\win_lgpo.py", line 6108, in _checkAllAdmxPolicies
                  keyvalue=policy_item_key)
                File "src\lxml\xpath.pxi", line 441, in lxml.etree.XPath.__call__
                File "src\lxml\xpath.pxi", line 95, in lxml.etree._XPathContext.registerVariables
                File "src\lxml\extensions.pxi", line 561, in lxml.etree._wrapXPathObject
                File "src\lxml\apihelpers.pxi", line 1474, in lxml.etree._utf8
              ValueError: All strings must be XML compatible: Unicode or ASCII, no NULL bytes or control characters
     Started: 13:32:53.824881
    Duration: 32494.192 ms
     Changes: 
```

### Versions Report
```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.4 (default, Jul  9 2019, 16:32:37)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 30 Thirty
         locale: UTF-8
        machine: x86_64
        release: 5.3.7-200.fc30.x86_64
         system: Linux
        version: Fedora 30 Thirty
```

**Comment by Ch3LL** [comment]
im having a hard time replicating this. it works just fine for me on 2019.2.2.

ping @saltstack/team-windows anyone else can replicate this error?

**Comment by H20-17** [comment]
I just learned that this works on some minions and not on others. It works fine on my test VM. It provokes the bug in the real world. I don't know what else distinguishes the minions at the moment.

**Comment by H20-17** [comment]
OK I have more information now.

I see that salt scans the gpo policies and it gets into trouble when it scans one particular one (i.e. "Define file shares for downloading definition updates"). The minions where I have the problem have been adjusted by SCCM (not my VM). For that particular policy, it is set to "Enabled" but no list of strings is set (so it may be an invalid configuration). Can @Twangboy coment on this? THanks

**Comment by H20-17** [comment]
I just received word from my SCCM admin. He's not setting this particular policy directly from SCCM. He sent me a screenshot of what he did do. The screenshot is of a dialog titled "Configure Definition Update Sources"

In it he has checked off

- Updates distributed from Microsoft Malware Protection Center
- Updates distributed from Configuration Manager
- Updates distributed from Microsoft Update
- Updates distributed from WSUS

He has _not_ checked off

- Updates from UNC file shares.

The end result, however is that, the policy is enabled with an empty list and and its tripping up salt.

**Comment by H20-17** [comment]
Hi everyone I just discovered according to Salt, the policy is actually set to
```
][SOFTWARE\Policies\Microsoft\Windows Defender\spynet
```
which suggests some kind of unterminated string or something like that is involved. In the gpedit GUI, the field for the list is empty (even though setting it that way (with the policy set to "Enabled" seems to be illegal).

**Comment by H20-17** [comment]
@Twangboy here is what I did to work around this.
I modified win_lgpo.py as follows:

the line:
```
admx_items = REGKEY_XPATH(admx_policy_definitions,
                          keyvalue=policy_item_key)
```
into the following block of code,

```
                    try:
                       admx_items = REGKEY_XPATH(admx_policy_definitions,
                                                 keyvalue=policy_item_key)
                    except ValueError as e:
                       log.error("ValueError exception thrown while attempting to acquire policies for policy item key %s", policy_item_key)
                       log.error("Exception text is: %s", e)
                       log.error("Review this policy item manually with gpedit.exe and check that all settings are sane.")
                       admx_items = []

```
@Twangboy could you do a PR that does something like this? This _works_ but I doubt that it's really good enough.

**Comment by lomeroe** [comment]
@H20-17 can you download/run the lgpo.exe utility from Microsoft on a machine that exhibits the issue?  Does it successfully parse the registry.pol file?

```
lgpo.exe /parse /m c:\windows\system32\grouppolicy\machine\registry.pol
```

If it does parse it, what does it show 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates\DefinitionUpdateFileSharesSources'?

What does regedit show 'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates\DefinitionUpdateFileSharesSources' is set to?

**Comment by H20-17** [comment]
Hi @lomeroe.
Sorry for taking so long to get back to you. Was busy with some stuff.

The file does parse but the result looks bad.
I can see the following:

```
Computer
Software\Policies\Microsoft\Windows Defender\Signature Updates
DefinitionUpdateFileSharesSources
SZ:\0][Software\\Policies\\Microsoft\\Windows Defender\\Signature Updates
```
With regedit.exe, the value of
_'HKLM\Software\Policies\Microsoft\Windows Defender\Signature Updates\DefinitionUpdateFileSharesSources_ is blank (empty field).

So it does look like MS tools have messed things up (somewhere along the way). It would be nice, at the very least, if lgpo could just swallow the exception and move on instead of dying when it encounters this. Thanks.

**Comment by H20-17** [comment]
I have a fresh image untouched by salt and at the very start, the problematic section looks like:

```
Computer
Software\Policies\Microsoft\Windows Defender\Signature Updates
DefinitionUpdateFileSharesSources
SZ:
```

It looks invalid because there is no string after where it says _SZ_ but I think that salt should be able to handle this now that I see it.

**Comment by H20-17** [comment]
Alright, I'm going to close this. I'm not sure that it really is a good idea for salt to work around this sort of thing (as I was hoping for) I think that this fix is better. For all those interested, here is the best solution I was able to come up with.
```
Set Windows Defender Antivirus File Shares Disabled:
    lgpo.set:
        - computer_policy:
{% if grains['osversion'] in ['10.0.18363'] %}
{% set sig_pol_name = "Define file shares for downloading security intelligence updates" %}
{% else %}
{% set sig_pol_name = "Define file shares for downloading definition updates" %}
{% endif %}
            {{sig_pol_name}}: Disabled
        - require:
            - Overwrite Windows Defender Admin Template


Replace corrupt pol file created by SCCM:
    file.managed:
        - name: "C:\\Windows\\System32\\GroupPolicy\\Machine\\Registry.pol"
        - source: salt://win/pol_files/registry_seed.pol
        - onfail:
              - Set Windows Defender Antivirus File Shares Disabled
```
The file _salt://win/pol_files/registry_seed.pol_ is a minimal pol file that just has "Define file shares for downloading definition updates" (or "Define file shares for downloading definition updates") set to Disabled.
This works because (it appears for now anyway) that SCCM does not corrupt the pol file if the it starts off this way. SCCM will still successfully apply its changes whenever it is scheduled to do so.

THere is another issue with windows 10.0.18363 administrative templates which I had to fix to before this would work but that's another issue.
