### ISSUE TITLE
Napalm fails to load (virtualname) in salt/utils/napalm.py due to check on opts too early

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#55222]
### Description of Issue
pip.req has been removed from versions of pip later than 10.
see https://stackoverflow.com/questions/25192794/no-module-named-pip-req
see https://github.com/pypa/pip/pull/4700

### Setup
Came across this running salt-bin whereby build Python3.7.4 with ensurepip, but pip 3 install napalm-base fails since no pip.req.  T

### Steps to Reproduce Issue
Now a clean box install Python 3.7.4 with ensurepip
then just for latest
```
pip3 install --upgrade pip
[root@c664min scripts]# pip3 install napalm-base
Collecting napalm-base
  Using cached https://files.pythonhosted.org/packages/14/2f/e923b0595b8123a58330a95f078fc864c70352d4c74716709a44e793cb8b/napalm-base-1.0.0.tar.gz
    ERROR: Command errored out with exit status 1:
     command: /usr/local/python37/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-umwc_g9i/napalm-base/setup.py'"'"'; __file__='"'"'/tmp/pip-install-umwc_g9i/napalm-base/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-umwc_g9i/napalm-base/pip-egg-info
         cwd: /tmp/pip-install-umwc_g9i/napalm-base/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-umwc_g9i/napalm-base/setup.py", line 5, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
[root@c664min scripts]# python3.7 --version
Python 3.7.4
[root@c664min scripts]# pip3 --version
pip 19.3.1 from /usr/local/python37/lib/python3.7/site-packages/pip (python 3.7)
[root@c664min scripts]# 
```

Note on Amazon Linux 2 Python 3, has Python 3.7.4 and pip3 v9.0.3 so evenif you upgrade, pip.req still sticks around.  Similarly on RHEL 8, Python 3.6.8 and pip3 v9.0.3.

But this it bites on Debian 10, Python 3.7.3 pip3 v18.1-75

```
root@d10min:/home/david# pip3 install napalm-base
Collecting napalm-base
  Downloading https://files.pythonhosted.org/packages/14/2f/e923b0595b8123a58330a95f078fc864c70352d4c74716709a44e793cb8b/napalm-base-1.0.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-ifpzbzoi/napalm-base/setup.py", line 5, in <module>
        from pip.req import parse_requirements
    ModuleNotFoundError: No module named 'pip.req'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-ifpzbzoi/napalm-base/
root@d10min:/home/david# 
```

The problem is with older pypi packages which have not allowed for the pip.req removal.
StackOverflow shows a work-around we could use but dislike '_internal' as a solution since does not have a permanence about it.

### Versions Report
All current supported versions

**Comment by dmurphy18** [comment]
@dwoz You might want to change the labels, but wanted to get your attention on this, esp. since Debian 10 and will hit it with Ubuntu 20.04

**Comment by dmurphy18** [comment]
Note Napalm-base is no longer supported, from Slack with Mircea Ulinic
Network Engineer at DigitalOcean

Need to update this execution module to not rely on it

**Comment by dmurphy18** [comment]
Okay issue is not as originally thought, napalm has incorporated base as part of latest napalm (2.5.0 and for some time) and the separate napalm-base is no long used.  However having logic errors in salt.utils.napalm where HAS_NAPALM_BASE is getting set to False even when napalm.base is installed correctly (test system had it pip installed, and checked by hand).  Debugging further into why this is occurring.

**Comment by dmurphy18** [comment]
@waynew we have a logic error, setting HAS_NAPALM_BASE = False, after successful import

   41     import napalm                                                                              run [SaltCall] call.py:47
   42     import napalm.base as napalm_base                                                          factory caller.py:80
   43     # pylint: enable=W0611                                                                     __init__ [ZeroMQCaller] caller.py:332
   44     HAS_NAPALM = True                                                                          __init__ [ZeroMQCaller] caller.py:106
>  45     HAS_NAPALM_BASE = False  # doesn't matter anymore, but needed for the logic below          __init__ [SMinion] minion.py:835
   46     try:                                                                                       grains loader.py:782
   47         NAPALM_MAJOR = int(napalm.__version__.split('.')[0])                                   __iter__ [LazyLoader] lazy.py:120
   48     except AttributeError:                                                                     _load_all [LazyLoader] loader.py:1798
   49         NAPALM_MAJOR = 0                                                                       _load_module [LazyLoader] loader.py:1572
   50 except ImportError:                                                                            <module> napalm.py:28
   51     HAS_NAPALM = False                                                                      >> <module> napalm.py:45
   52     try:                                                                                    
   53         import napalm_base                                                                  
   54         HAS_NAPALM_BASE = True                                                              Breakpoints:
   55     except ImportError:                                                                     
   56         HAS_NAPALM_BASE = False 

salt/utils/napalm.py.  

The comment for line 45 should change too, since the code is obviously  is making Salt think Napalm not available.  CR also ran his eyes over the code and agrees the issue, by way of confirmation


From pudb
>>> dir(napalm)                                                                                   
['SUPPORTED_DRIVERS', '_SUPPORTED_DRIVERS', '__all__', '__builtins__', '__doc__', '__file__',     
'__name__', '__package__', '__path__', '__version__', 'base', 'get_network_driver',               
'pkg_resources', 'sys'] 
>>> dir(napalm.base)                                                                              
['MockDriver', 'ModuleImportError', 'NetworkDriver', '__all__', '__builtins__', '__doc__',        
'__file__', '__name__', '__package__', '__path__', 'base', 'canonical_map', 'constants',          
'exceptions', 'get_network_driver', 'helpers', 'importlib', 'inspect', 'mock', 'print_function',  
'py23_compat', 'unicode_literals', 'utils', 'validate']                                           
>>>  

We will never hit the importerror and HAS_NAPALM_BASE will be left False, should probably make that default to True.  The code for HAS_NAPALM_BASE in salt/runners/bgp.py salt/runners/net.py looks good to my eye.

Any chance this might make it into the next point release.

**Comment by dmurphy18** [comment]
Also further issue is 'napalm' is not in 'opts' so the is_minion check fails, line 95
>>> opts['napalm']                                                                                
Traceback (most recent call last):                                                                
  File "<pudb command line>", line 1, in <module>                                                 
KeyError: 'napalm' 

function proxy_napalm_wrap has opts['napalm'] getting set on line 454 salt/utils/napalm.py, but that is long after virtualname resolution, and proxy_napalm_wrap only appears to be called by napalm execution modules.  Looks like chicken and egg error

**Comment by dmurphy18** [comment]
This PR https://github.com/saltstack/salt/issues/50924 added the troublesome code for ' napalm in opts'

**Comment by dmurphy18** [comment]
Reason for grains **os** being **None** is due to grains/napalm.py and __retrieve_device_cache_ call by function _napalm.getos_ when loading grains.

The problem is yet again checking _is_proxy_ and _is_minion_ which are checking for key **napalm**, but that will not be set for some time later (chicken and egg again)

**Comment by waynew** [comment]
@dmurphy18 is there a Docker image or Vagrant VM that I can look at to get a napalm native minion setup?

**Comment by sagetherage** [comment]
@waynew @dmurphy18 we have committed to this for Sodium so what needs to happen here to move this forward?

**Comment by Akm0d** [comment]
Related to PR https://github.com/saltstack/salt/pull/55421
