### ISSUE TITLE
initial_states feature request

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#55238]
### Description of feature
I would like a minion (and possibly master) option added that allows you to list highstate, list of states, and possibly orchestration states for master that would be ran a single time and then deactivated. This allows for the true initial start of a minion in a server, VM, or container to run a select set of states useful only for that unique first start.
***

### How it would work
This would essentially work the same as `startup_states` option in the minion. However, this works once.

Unique attributes to discuss for this feature:
- A flag to set whether this runs instead of startup_states, or if it just has precedence over startup_states.
- an option to target a custom top file that is not the standard top file. Again useful running a complex startup build but not wanted for consecutive runs.
***

### Examples
```
initial_states: sls
initial_startup_order: first
                           #startup runs after initial

sls_list:
  - edit.vim
  - hyper
```
```
initial_states: top
initial_startup_order: only 
                           #initial runs instead of startup

initial_top: salt://srv/salt/tops/alternative_top_file.sls 
                          #can also target local file system
```
***

### Whats a similar feature that already exists
The go to for this is obviously the `startup_states` feature for the minion configuration. I originally wanted to just extend the startup states feature but then realized I want to be able to have both options to list an initial state list to run and also have a startup state list used for every minion restart.
***

### Resources
- https://docs.saltstack.com/en/latest/ref/states/startup.html

**Comment by Ch3LL** [comment]
https://docs.saltstack.com/en/latest/topics/cloud/deploy.html#post-deploy-commands

 `start_action` ? although according to the docs it does not work with all providers.

or you could setup a custom deploy script that runs the states you want to run.
