### ISSUE TITLE
aptpkg does not correctly pass force_conf_new

### ISSUE THREAD

**Issue by mskogorev** [saltstack/salt#55239]
### Description of Issue
Ticket #23501  and #40558 is not correctly fixed and should be reopened.
I filed a new ticket as I could not reopen that ticket.

I think the merged fix from 9d0bb55 is not correct.

If `force_conf_new: True` is given, salt adds both options:
`'-o', 'DPkg::Options::=--force-confnew', '-o', 'DPkg::Options::=--force-confdef'`

As net effect apt-get will then not use force-confnew, but force-confdef.

The following patch fixed the problem for me

```
diff --git a/salt/modules/aptpkg.py b/salt/modules/aptpkg.py
index 3a96d63..87ca989 100644
--- a/salt/modules/aptpkg.py
+++ b/salt/modules/aptpkg.py
@@ -635,7 +635,7 @@ def install(name=None,
             cmd_prefix.extend(['-o', 'DPkg::Options::=--force-confnew'])
         else:
             cmd_prefix.extend(['-o', 'DPkg::Options::=--force-confold'])
-        cmd_prefix += ['-o', 'DPkg::Options::=--force-confdef']
+            cmd_prefix += ['-o', 'DPkg::Options::=--force-confdef']
         if 'install_recommends' in kwargs:
             if not kwargs['install_recommends']:
                 cmd_prefix.append('--no-install-recommends')
```
That patch is not complete though..
The following code is wrong too salt/modules/aptpkg.py

```
 cmd.extend(['apt-get', '-q', '-y',
                '-o', 'DPkg::Options::={0}'.format(force_conf),
                '-o', 'DPkg::Options::=--force-confdef'])
```
The patch above is just to demonstrate the problem, a better fix is probably needed.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
use force_conf_new, and see it fail

### Versions Report
2019.2.0

**Comment by Ch3LL** [comment]
glancing at the code seems your right `--force-confdef` should not be used alongside `--force-confnew` but does work alongside `--force-confold`. Did you want to try give it a go at a fix and submit a PR?

**Comment by mskogorev** [comment]
> glancing at the code seems your right `--force-confdef` should not be used alongside `--force-confnew` but does work alongside `--force-confold`. Did you want to try give it a go at a fix and submit a PR?

Yes, this problem needs to be fixed in several places where `--force-confnew` is used

**Comment by mskogorev** [comment]
https://github.com/saltstack/salt/pull/55264

**Comment by mskogorev** [comment]
Create pull request

**Comment by nicholasmhughes** [comment]
not sure at what point it was merged, but the proposed fix is already in the current master branch

https://github.com/saltstack/salt/blob/c5936f92ae441bc1cc5acfd81125f5b9c30063b9/salt/modules/aptpkg.py#L876-L880
