### ISSUE TITLE
'pip.installed' is not available

### ISSUE THREAD

**Issue by ksalman** [saltstack/salt#55247]
I installed a different version of python using ```pyenv.installed```
```
2.7.15:
    pyenv.installed
```
 and now I am trying to install its pip packages, but I am not able to target pip in that python location. I have tried using ```cwd``` option for ```pip.installed``` but that does not appear to work.
```
openstacksdk:
    pip.installed:
        - cwd: /usr/local/pyenv/versions/2.7.15/bin/
```
I also tried using the ```bin_env``` option, as shown here https://docs.saltstack.com/en/latest/ref/states/all/salt.states.pip_state.html, but I get same result
```
openstacksdk:
    pip.installed:
        - bin_env: /usr/local/pyenv/versions/2.7.15/bin/pip
```
```
       ----------
                 ID: openstacksdk
           Function: pip.installed
             Result: False
            Comment: State 'pip.installed' was not found in SLS 'packages.python.2_7_15'
              Reason: 'pip.installed' is not available.
```
```
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 20 2019, 09:59:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.10 Carbon
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-43-generic
         system: Linux
        version: Scientific Linux 6.10 Carbon
```

**Comment by xeacott** [comment]
What is the package you are looking to install? Have you also written out the require as such:
```
          django:
            pip.installed:
              - name: django >= 1.6, <= 1.7
              - bin_env: /foo/.virtualenvs/bar
              - require:
                - pkg: python-pip
```

**Comment by ksalman** [comment]
Well, why would that be required though? python-pip package will install pip for a python that is in a different location and most likely a different version compared to what I have installed at the bin_env location, `/usr/local/pyenv/versions/2.7.15/bin`.

**Comment by ksalman** [comment]
This is not stale.

**Comment by sagetherage** [comment]
@Akm0d @xeacott can one of you please follow up here?

**Comment by Akm0d** [comment]
Does this PR address the issue? https://github.com/saltstack/salt/pull/56023

**Comment by Akm0d** [comment]
The referenced PR is a step towards a fix for this issue, let's remove  the `if salt.utils.platform.is_windows()` and solve whatever issues pop up after that in a new PR

**Comment by thoward27** [comment]
Was there any resolution for this issue? I am having trouble getting anything to install to a pyenv-installed version of python.

My goal is to install pyenv, then use that to install python3.8, then install pipx into that version of python. Any tips?

**Comment by robsteneha** [comment]
Hey is this issue resolved? I am also facing the same issue where python3-pip (system) is required to install anything using the virtual-env pip. bin_env also doesn't help in this case unless the pip is installed on system.
