### ISSUE TITLE
Salt Cloud Proxmox Driver: Hardcoded API Port

### ISSUE THREAD

**Issue by BrianTillman** [saltstack/salt#55240]
### Description of Issue
The Salt Cloud Proxmox Driver is hardcoded to call the Proxmox service API on the default port of 8006. The port number cannot be appended to the URL setting. It is not possible to leverage the Proxmox driver against a Proxmox PVE deployment where the web services (pveproxy) are using a non-default port.  

### Setup
Current production builds of Salt-Cloud, Proxmox PVE, and Salt-Cloud Proxmox Driver (proxmox.py)

### Steps to Reproduce Issue
Deploy Proxmox and configure a working integration with Salt-Cloud.
Modify the Proxmox web services (pveproxy) to listen on TCP 443.
Make awkward attempts to shove '443' into your providers.conf (/etc/salt/cloud.providers.d/Proxmox.conf or similar)

### Versions Report
root@Salt:/srv/salt# salt --versions-report
Salt Version:
           Salt: 2018.3.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.7.3 (default, Oct  7 2019, 12:56:13)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: Ubuntu 19.04 disco
         locale: utf-8
        machine: x86_64
        release: 5.0.21-4-pve
         system: Linux
        version: Ubuntu 19.04 disco

**Comment by Ch3LL** [comment]
seems an easy enough change, add a new option and convert it to a more dynamic url. Did you want to give a go at a PR fix?

**Comment by BrianTillman** [comment]
@Ch3LL I have a fix, looking at creating some tests for this driver before submitting the PR. Heads up: I ran into a few additional minor issues, including #40297. I'll see if I can't put together a few PRs.

**Comment by BrianTillman** [comment]
Opened PR #55246

**Comment by max-arnold** [comment]
This feature already exists in the `neon` branch: https://github.com/saltstack/salt/pull/50620

**Comment by mthibaut** [comment]
Only recently found this issue, I'll be looking at it.
