### ISSUE TITLE
states.virt.pool_running expects a different pool_info dictionary

### ISSUE THREAD

**Issue by tash** [saltstack/salt#55250]
### Description of Issue
If pool "pool_1" exists, a call to state.pool_running will return an error. The reason is, that the expected dictionary contains the key element of the pool name "pool_1" instead of the 'state' key.

Expected dictionary by state.virt.pool_running:
{ 'state': '...', ...}
Observed dictionary returned by virt.pool_info:
{ 'pool_1': { 'state': '...', ...} }

### Setup
Master on host 1, QEMU/KVM with libvirt on host 2. Host 2 is a Minon.

### Steps to Reproduce Issue
- create pool "pool_1" on VM host
- call virt.pool_running with name="pool_1", ie. by a sls like:
`pool_1:
   virt.pool_running:
    ....`

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.26.8
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.9 (default, Oct 29 2019, 10:39:36) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-lp151.28.25-default
         system: Linux
        version: Not Installed

**Comment by tash** [comment]
Operating System: openSUSE Leap 15.1
       CPE OS Name: cpe:/o:opensuse:leap:15.1
            Kernel: Linux 4.12.14-lp151.28.25-default
      Architecture: x86-64

**Comment by xeacott** [comment]
Thanks for submitting. I do not have much knowledge in this area of Salt so maybe someone on @saltstack/team-core with SUSE knowledge can be of better assistance but, it seems that the expected dictionary has changed or it's being created incorrectly by the time it gets read in. Can you also post the stack trace for this?

**Comment by tash** [comment]
stack trace:
```
[DEBUG   ] LazyLoaded virt.pool_running
[INFO    ] Running state [salt-images] at time 14:56:38.310661
[INFO    ] Executing state virt.pool_running for [salt-images]
[DEBUG   ] key: virt.connect, ret: _|-
[DEBUG   ] key: libvirt:connection, ret: _|-
[DEBUG   ] key: virt:connection:uri, ret: _|-
[DEBUG   ] key: libvirt:hypervisor, ret: _|-
[DEBUG   ] An exception occurred in this state: 'state'
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 1939, in call
    ret = self.states[cdata['full']](*cdata['args'], **cdata['kwargs'])
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/states/virt.py", line 765, in pool_running
    if info['state'] == 'running':
KeyError: 'state'
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/state.py", line 1939, in call
    ret = self.states[cdata['full']](*cdata['args'], **cdata['kwargs'])
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1941, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/states/virt.py", line 765, in pool_running
    if info['state'] == 'running':
KeyError: 'state'
```

It is unlikely a SUSE issue as the expected dictionary in state.virt.pool_running does not match modules.virt.pool_info: 
https://github.com/saltstack/salt/blob/0ca04ffbebb9daeb8469a6e80d868b8a6524bd99/salt/states/virt.py#L761-L765
https://github.com/saltstack/salt/blob/0ca04ffbebb9daeb8469a6e80d868b8a6524bd99/salt/modules/virt.py#L4728-L4733

**Comment by tash** [comment]
still persists, with a fairly easy fix. Any takers? :>

**Comment by tash** [comment]
Fixed in https://github.com/saltstack/salt/commit/23a3fe556f7e8fa88257de8233c1f1623a2f9bbc
