### ISSUE TITLE
integration.netapi.rest_tornado.test_app.TestSaltAPIHandler.test_simple_local_runner_post fail.

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#55252]
### Description of Issue
https://jenkinsci.saltstack.com/job/pr-kitchen-amazon1-py2/job/master/86/ shows a failure on integration.netapi.rest_tornado.test_app.TestSaltAPIHandler.test_simple_local_runner_post test.  This started happening when we switched from an c5.xlarge to an m5.large.  I'm changing it back, but we should fix the test as it doesn't fail on other distros that run on m5.large.

**Comment by xeacott** [comment]
Addressed with an open PR.

**Comment by sagetherage** [comment]
@xeacott @jshatch can either of you check to see if this fixed since Bryce is out for a while, please? or maybe we ask the Core team to check it?

**Comment by sagetherage** [comment]
@xeacott can you reference the PR number, please?

**Comment by xeacott** [comment]
Although closed, the PR was this https://github.com/saltstack/salt/pull/55259 however @s0undt3ch it looks like you've addressed this else where?

**Comment by s0undt3ch** [comment]
Nope. That was the fix. And I think getting back to the old VM type.

**Comment by xeacott** [comment]
👍
