### ISSUE TITLE
lvm.lv_present state allow resize

### ISSUE THREAD

**Issue by Armadill0** [saltstack/salt#55265]
### Description of Issue
With #15348 the linux_lvm module has been extended to support the lv_resize function. There also have been requests in the former issue to support the resizing in the state module. But only the module has been extended.
Please extend the lvm state lv_present to automatically resize the named logical volume if the specified size does not match the current values.

Please also include a switch to allow the automatic resize of the file system of the logical volume if this is supported.

FYI: There are a lot of limitations with resizing file systems depending on the file system type which is being used. Some types don't support any resizing, some only support increasing the size and so on.
Imho we should trust the underlying lvm tools to report a failure if a resizing of whatever reason is not possible. This error should be reported, so the user is able to act accordingly.

### Setup
Currently if you create a logical volume lets say with 10GiB:
```
lv_opt:
  lvm.lv_present:
    - name: opt
    - vgname: default
    - size: 10G
```
and want to resize the volume to 20GiB:
```
lv_opt:
  lvm.lv_present:
    - name: opt
    - vgname: default
    - size: 20G
```
Nothing will happen, because the LV already exists and the state reports a success.

### Steps to Reproduce Issue
State reports back with no changes or errors.

### Versions Report
```
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: 1.0.0
   msgpack-pure: Not Installed
 msgpack-python: 0.4.2
   mysql-python: 1.2.5
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 25 2018, 20:42:16)
   python-gnupg: 0.3.6
         PyYAML: 3.11
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: debian 8.11 
         locale: UTF-8
        machine: x86_64
        release: 3.16.0-5-amd64
         system: Linux
        version: debian 8.11
```

**Comment by xeacott** [comment]
Thanks for submitting this, I will leave this as a feature request for now and link the PR that got merged previously. This would make sense to have the state also updated to be more inline with the module.

Link to PR: https://github.com/saltstack/salt/pull/15407

**Comment by Armadill0** [comment]
not stale

**Comment by david-ecc** [comment]
not stale
