### ISSUE TITLE
win_task repeating task not working

### ISSUE THREAD

**Issue by UnknownGnome** [saltstack/salt#55273]
### Description of Issue
The win_task.create_task function works fine unless I add parameters for repeat_interval and repeat_duration. 
With those defined, the run completes, but the task is not created.

### Setup
salt 'WIN' task.create_task SaltRepeat user_name=System force=True action_type=Execute cmd=c:\salt\salt-call.bat arguments=state.apply trigger_type=Daily trigger_enabled=True repeat_interval='30 minutes' repeat_duration='Indefinitely'

### Steps to Reproduce Issue
 salt 'WIN' task.create_task SaltRepeat user_name=System force=True action_type=Execute cmd=c:\salt\salt-call.bat arguments=state.apply trigger_type=Daily trigger_enabled=True repeat_interval='30 minutes' repeat_duration='Indefinitely' -l debug
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Popen(['git', 'version'], cwd=/srv/salt/windows_common, universal_newlines=False, shell=None)
[DEBUG   ] Popen(['git', 'version'], cwd=/srv/salt/windows_common, universal_newlines=False, shell=None)
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/master', 'ip-10-195-4-114.us-west-2.compute.internal_master', 'tcp://127.0.0.1:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://127.0.0.1:4506
[DEBUG   ] Trying to connect to: tcp://127.0.0.1:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded local_cache.get_load
[DEBUG   ] Reading minion list from /var/cache/salt/master/jobs/65/017a06efd6e94061a6b6a86ba41fd6bba0f5ba27cfb36a692f57ba39c0b48d/.minions.p
[DEBUG   ] get_iter_returns for jid 20191112114907157405 sent to {'WIN'} will timeout at 11:54:07.163729
[DEBUG   ] jid 20191112114907157405 return from WIN
[DEBUG   ] return event: {'WIN': {'ret': False, 'retcode': 0, 'jid': '20191112114907157405'}}
[DEBUG   ] LazyLoaded nested.output
WIN:
    False
[DEBUG   ] jid 20191112114907157405 found all minions {'WIN'}
[DEBUG   ] Closing IPCMessageSubscriber instance

### Versions Report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct  7 2019, 12:59:55)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1052-aws
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by UnknownGnome** [comment]
Windows System
c:\salt>salt-call --versions-report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393 SP0 Multiprocessor Free

**Comment by xeacott** [comment]
Thanks for submitting! @cmcmarrow might have an answer for this before I investigate.

**Comment by cmcmarrow** [comment]
Hello @UnknownGnome. What version of windows are you using?

**Comment by cmcmarrow** [comment]
If you run ```salt 'WIN' task.create_task SaltRepeat user_name=System force=True action_type=Execute cmd=c:\salt\salt-call.bat arguments=state.apply trigger_type=Daily trigger_enabled=True repeat_interval='30 minutes``` Windows 10 defaults to repeat_duration='Indefinitely'

**Comment by cmcmarrow** [comment]
I'm right know trying to find out why this is happening.

**Comment by cmcmarrow** [comment]
@UnknownGnome I put in a fix for the bug. https://github.com/saltstack/salt/pull/55822

**Comment by cmcmarrow** [comment]
Just need to add some test to avoid this mess from coming up again.

**Comment by UnknownGnome** [comment]
Sweet!
