### ISSUE TITLE
Update saltstack version on docker ci-centos-7:2019.2 to 2019.2.x

### ISSUE THREAD

**Issue by mjtrangoni** [saltstack/salt#55302]
### Description of Issue
The [2019.2 Docker Image for CentOS7](https://hub.docker.com/layers/saltstack/ci-centos-7/2019.2/images/sha256-33143cacc5bfa60d257da05f2a842b51891745a80ad2d71dab31b9136d33f8c8) runs on CentOS .7.7 but the version of saltstack inside is still the 2018.3.4 one

### Steps to Reproduce Issue
```shell
$ docker pull saltstack/ci-centos-7:2019.2
$ docker run -it saltstack/ci-centos-7:2019.2
# salt-call --versions-report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: ascii
        machine: x86_64
        release: 4.15.0-66-generic
         system: Linux
        version: CentOS Linux 7.7.1908 Core

```

### Versions Report

See above

**Comment by xeacott** [comment]
Gotcha, thanks for reporting! I'll ask how soon we can get these guys updated because I'm sure this applies to other docker containers.

**Comment by s0undt3ch** [comment]
Let me shed some light on this matter.
* These images aren't yet officially publicized nor supported.
* These images are an effort to make testing salt within docker containers possible, which is still an ongoing task.
* These are **not** images of salt with that version installed, ie, `saltstack/ci-centos-7:2019.2` is not CentOS 7 with Salt 2019.2.x installed.
* These images were salted with the 2019.2 branch of [salt-jenkins](https://github.com/saltstack/salt-jenkins), for CI purposes only.
* At the time they were created, we used salt 2019.3.4 to salt them, hence the salt version you see being reported.

There has been some discussion about creating officially supported docker containers with the official releases, however, we don't create those, officially.

We do have plans to improve our usage of docker containers, and [saltstack](https://hub.docker.com/u/saltstack) at docker hub has quite a few images, but as mentioned, none of these images is officially promoted or supported.
