### ISSUE TITLE
Windows Tests failing on new images

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#55308]
### Description of Issue
after removing beats and rebuilding the images with this PR https://github.com/saltstack/salt-jenkins/pull/1613  the windows tests are failing:

https://jenkinsci.saltstack.com/job/Full-PR/job/full-pr-windows-2016/job/PR-1613/7/
https://jenkinsci.saltstack.com/job/Full-PR/job/full-pr-windows-2019/job/PR-1613/7/

We have not pushed these images yet so we will need to fix these failures before we do so.

**Comment by sagetherage** [comment]
Assigning both so that Chad can get help from DWoz, but to not overload DWoz more so.

**Comment by cmcmarrow** [comment]
https://github.com/saltstack/salt-jenkins/pull/1613 is merged now
