### ISSUE TITLE
archive.extracted ignores "enforce-toplevel: False" with a tar.gz when option - options: "--strip-components=1 is used

### ISSUE THREAD

**Issue by hartmutreusch** [saltstack/salt#55341]
### Description of Issue
I like to extract a tar.gz file but remove the top level directory and use another name instead. But enforce-toplevel: False in combination with options: "--strip-components=1" doesn't work.

The tar file looks like this:
root@icinga2:/tmp# tar ztf v0.3.0.tar.gz 
icingaweb2-module-ipl-0.3.0/
icingaweb2-module-ipl-0.3.0/.gitignore
icingaweb2-module-ipl-0.3.0/LICENSE
icingaweb2-module-ipl-0.3.0/README.md
.
.

Error:
Result: False
Comment: Archive does not have a single top-level directory. To allow this archive to be extracted, set 'enforce_toplevel' to False. To avoid a 'tar-bomb' it may also be advisable to set a top-level directory by adding it to the 'name' value (for example, setting 'name' to /usr/share/icingaweb2/modules/ipl/some_dir instead of /usr/share/icingaweb2/modules/ipl/).

### Setup
extract_ipl:
  archive.extracted:
    - name: /usr/share/icingaweb2/modules/ipl
    - enforce-toplevel: False
    - if_missing: /usr/share/icingaweb2/modules/ipl
    - skip_verify: True
    - source: https://github.com/Icinga/icingaweb2-module-ipl/archive/v0.3.0.tar.gz
    - options: "--strip-components=1"

### Steps to Reproduce Issue

Execute the State.

### Versions Report
# salt --versions-report
Salt Version:
           Salt: 2018.3.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 3.0.2
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.1 
         locale: UTF-8
        machine: armv7l
        release: 4.19.66-v7+
         system: Linux
        version: debian 10.1

# salt-minion --versions-report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct  7 2019, 12:59:55)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: ISO-8859-1
        machine: x86_64
        release: 4.15.0-70-generic
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by Oloremo** [comment]
kinda related: https://github.com/saltstack/salt/issues/54012

**Comment by sagetherage** [comment]
@hartmutreusch is this still an issue in a supported version of Salt >3000.9?

**Comment by Ch3LL** [comment]
Close due to inactivity. If this issue is still existing on the latest version of Salt please open a new issue with the details on Salt 3006.2
