### ISSUE TITLE
salt ordermaster use high mem

### ISSUE THREAD

**Issue by menglong81** [saltstack/salt#55343]
saltversion:

```
salt-master --versions-report
Salt Version:
           Salt: 2016.3.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.7.0
       dateutil: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.3.0
   mysql-python: 1.2.4b5
      pycparser: Not Installed
       pycrypto: 2.6
         pygit2: Not Installed
         Python: 2.7.4 (default, Dec 24 2013, 16:30:42)
   python-gnupg: Not Installed
         PyYAML: 3.10
          PyZMQ: 13.1.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: centos 6.4 Final
        machine: x86_64
        release: 2.6.32-358.23.2.el6.x86_64
         system: Linux
        version: CentOS 6.4 Final

```

My architecture is the master of master。
When I ran salt order_master for a while, I found that the salt-master process occupies 20G of memory.

`ps aux|grep salt-master
`![image](https://user-images.githubusercontent.com/12707137/69045421-c7cd0980-0a31-11ea-9f19-b1e6ed3e2fe1.png)

`cat /proc/42748/smaps`
![image](https://user-images.githubusercontent.com/12707137/69045251-7755ac00-0a31-11ea-954e-5560aa291497.png)

Private_Dirty:  21378260 kB
Whether the Private_Dirty value is normal or not, this value is related to what？

**Comment by waynew** [comment]
@menglong81 thanks for the report! This seems like it could be a difficult issue to track down.

Some questions:
- What does your master/master/minion architecture look like? (e.g. number of masters/minions, minions per master)
- Is this just a single call that consumes all the memory?
- Does restarting the master of master process reset the memory usage?

@saltstack/team-core does anyone else have any ideas about what's going on here?
