### ISSUE TITLE
salt/templates/rh_ip/rh8_eth.jinja needs to be verified that it is correct for redhat 8

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#55359]
### Description of Issue
salt/templates/rh_ip/rh8_eth.jinja was added by me to make the network tests pass here https://github.com/saltstack/salt/pull/55307.  I just copied and pasted the rh7 one.  We need to go through and verify that it is correct for rh8 and make changes if necessary.  We don't have a lot of test coverage on that file so it needs some manual effort.

See also https://github.com/saltstack/salt/issues/55334

**Comment by sagetherage** [comment]
Not stale @dhiltonp are you currently working on this or plan to?
