### ISSUE TITLE
Add File Server events to documentation

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#55369]
### Description of Issue
This is a request to add the file server events to this document:

https://docs.saltstack.com/en/latest/topics/event/master_events.html

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by Akm0d** [comment]
Can you give a few more details?  What file server events do you refer to?
