### ISSUE TITLE
SLS search syntax should support nested grains

### ISSUE THREAD

**Issue by octplane** [saltstack/salt#5538]
Hi,

It would be nice if the G@ syntax to search in grains supported nested grains as described in https://groups.google.com/forum/#!search/nested$20grains$20sls/salt-users/PuLsf3VB4aM/KA14kcNOyZoJ

**Comment by jacobhammons** [comment]
Looks like this is documented, https://docs.saltstack.com/en/latest/topics/targeting/grains.html

Closing.
