### ISSUE TITLE
New smbprotocol release

### ISSUE THREAD

**Issue by jborean93** [saltstack/salt#55407]
### Description of Issue
Hi, apologies if this is the wrong place to post this but I'm currently in the process of creating a new release of `smbprotocol` based on https://github.com/jborean93/smbprotocol/pull/17 and some changes before it. I can see that this is being used in Salt and wanted to make sure the changes I've made hasn't broken anything here.

This is a pretty major release of this library and the primary purpose is to introduce the `smbclient` package as an easy to use interface on top of `smbprotocol`. I've had a quick through the code base and it doesn't look like anything should be broken but it would be great if you could test it out before I make an actual release. You could probably even simplify some of your code in some areas, for example to delete a file it's as simple as (compared to the arduous task it is on the low level interface):

```
import smbclient

smbclient.register_session("server", username="user", password="pass")
smbclient.remove(r"\\server\share\file.txt")
```

### Setup
N/A

### Steps to Reproduce Issue
N/A

### Versions Report
N/A

**Comment by s0undt3ch** [comment]
Sorry for the long wait to get this through triage @jborean93 

Issue has been labelled and the `Help Wanted` label added.
