### ISSUE TITLE
Virtual grain on Windows in OpenStack

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#55406]
### Description of Issue
In a virtual environment, the virtual grain is attempted to be resolved to some value. Then in Windows it gets hardcoded to `physical` before attempting to resolve it again.

https://github.com/saltstack/salt/blob/a62c74126a92b06a8d0aa55e3796f05287277a66/salt/grains/core.py#L628

This is causing VMs to have their virtual grain set to `physical` if it doesn't match one of the options in this function.

### Setup
Run a Windows 2016 VM in any virtualization other than one listed in the function.

This happens in 2019.2.2.

**Comment by cmcmarrow** [comment]
I agree. 

line 628 should be some like this `grains.setdefault('virtual', 'physical')`

**Comment by cmcmarrow** [comment]
Also _virtual should tak _virtual(osdata, )

**Comment by cmcmarrow** [comment]
Both PRs should fix the error.
