### ISSUE TITLE
SALT does not read updated Pillar data in _modules

### ISSUE THREAD

**Issue by praveenkulkarni22** [saltstack/salt#55427]
### Description of Issue

I have a pillar set with the following format:
```
s_pgs:
  release: '11'
```

However, When I try to read the pillar from external modules (_modules), the values are never fetched:

`{% set pgrelease = salt['pillar.get']('s_pgs:release', '10') %}`

I am always getting the default value 10 and not 11

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
```
s_pgs_file:
  file.managed:
    - name: /tmp/gcheck.txt
    - contents: {{pgrelease}}
```

The pgrelease never picks up the right value. It always has the default value.

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
Salt Version:
           Salt: 2018.3.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.12.14-95.24-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
```

**Comment by max-arnold** [comment]
It is not clear if you are talking about accessing pillar values in Jinja

```
{% set pgrelease = salt['pillar.get']('s_pgs:release', '10') %}
```

or in custom Python `_modules/`.

For custom modules this behaviour is intentional: https://docs.saltstack.com/en/latest/topics/pillar/#in-memory-pillar-data-vs-on-demand-pillar-data

**Comment by praveenkulkarni22** [comment]
The above line of code that I have shared is in one of the custom modules. In the Custom module I try to read pillar data and then continue with further processing. Thanks for the link to behavior of Pillar data. I updated my states now. The first state I run in the series is to refresh the pillar data as stated in the link. Below is the relevant state.

```
s_db_pillar_refresh:
  module.run:
  -  name: saltutil.refresh_pillar
```
However, the result is still the same. I updated `release ` version is not returned from the pillar and I always get the default value `10` from this code.

**Comment by max-arnold** [comment]
Does the state show the same value on the second run?

**Comment by max-arnold** [comment]
Maybe there is not enough time for `refresh_pillar` to take effect. It is possible to call it synchronously, but this feature is not yet released: https://github.com/saltstack/salt/pull/50168

**Comment by praveenkulkarni22** [comment]
No. each time i try reading this pillar in the module, it never returns the right value. If I fetch it from the command line, i get the right value:

`salt '*" pillar.get s_pgs:release
Minion:
    11
`

However, the same command within the module never gets the pillar value and in turn returns only the default value. Wonder why is that?

**Comment by max-arnold** [comment]
Could you post the source code for your custom Python module?
