### ISSUE TITLE
salt-cloud: outdated AWS API version

### ISSUE THREAD

**Issue by nnsense** [saltstack/salt#55436]
### Description of Issue
While trying to use salt-cloud I've realised I could pass any attribute to `block_device_mappings` provided is part of AWS API, much like VolumeSize and VolumeType.
I needed to encrypt using my KMS key but apparently the `Ebs.Encrypted` is working while `Ebs.KmsKeyId` it is not. Updating the default API version on the following files to the latest (`2016-11-15`) worked

https://github.com/saltstack/salt/blob/master/salt/utils/aws.py#L44 
https://github.com/saltstack/salt/blob/master/salt/cloud/clouds/ec2.py#L167

I'm not comfortable to send a PR updating this because I'm afraid it could break something but it should be updated. I will extensively test it during the next days if it can be of any help.

**Comment by bryceml** [comment]
@Akm0d should this not be left stale?

**Comment by nnsense** [comment]
This should be fixed, it is providing more features to Salt cloud, I'm currently updating this manually into the source code on each update.
