### ISSUE TITLE
grains.virtual always returns "LDOM" on Oracle Solaris

### ISSUE THREAD

**Issue by asomers** [saltstack/salt#55444]
### Description of Issue
`grains.virtual` unconditionally returns "LDOM" on Oracle solaris, regardless of whether the system is running in LDOM, on bare metal, in VMWare, etc.

### Setup
No special setup required

### Steps to Reproduce Issue
`salt myhostname grains.get virtual`

### Versions Report
2019.2.0

### Analysis
The bug was introduced by f7f8a8ff1fc0841171cdfda99b5c51e465db65fd .  As you can see from the diff, the virtual grain now returns "LDOM" as long as the `virtinfo` command exists.  It doesn't attempt to interpret `virtinfo`'s output at all.

**Comment by asomers** [comment]
cc @clallen

**Comment by clallen** [comment]
Thanks for letting me know about this. Is there a particular platform you're on?
I thought the other checks for VMWare, etc would take precedence but I guess that's not the case.
Also if I remember correctly there is at least another check to determine if the system is a zone.

**Comment by asomers** [comment]
I'm using Oracle Solaris 11.3 and 11.4, both on bare metal and on VMWare.  In all cases the virtual grain reports "LDOM".

**Comment by clallen** [comment]
On the bare metal, what is the system model?
For the VMWare side, I'll see if I can get an instance up in the workstation player and do some poking around there.

**Comment by asomers** [comment]
What do you mean by "system model"?  These aren't Oracle hardware, if
that's what you're asking. They're supermicro boxes.

**Comment by clallen** [comment]
Oh, ok, I thought it was SPARC hardware.

**Comment by clallen** [comment]
I think I have a fix for this, could you try dropping this file in ```<salt_basedir>/grains```:
https://github.com/clallen/salt/blob/master/salt/grains/core.py

Then run:
```salt-call --local grains.get virtual```
```salt-call --local grains.get virtual_subtype```

I've tested it on these 11.4 environments:
- VMWare x86
- SPARC LDOM
- SPARC non-global zone
- SPARC kernel zone
- Physical x86 (a Dell laptop)

On 11.3 the only environments I could get were:
- SPARC LDOM
- SPARC non-global zone
- SPARC kernel zone

So far it seems to work, but please let me know what you find.

**Comment by asomers** [comment]
Works for me on:
11.4 / VMWare
11.4 / bare metal
11.3 / zone

I'm unable to test any other combination.

**Comment by clallen** [comment]
Works for me, I'll put a PR in.

**Comment by sagetherage** [comment]
closing as fixed and will be released in Sodium
