### ISSUE TITLE
Monitoring and alerting system

### ISSUE THREAD

**Issue by nrebelski** [saltstack/salt#55458]
### Description of Issue
I am trying to develop some kind of monitoring and alerting system for salt, where whenever minion fails to deploy certain configuration from salt master I will get notification through email.
I have created schedule using state file so that every minion will run the configuration once every hour.
Currently I get the email with errors after one or more minions will fail to apply the changes only when I run the command "salt '*' state.sls nameofmodule" from command line. Email is not sent, during scheduled run. I need alerting to work during scheduled run.
Email, that I get after running above command manually is also not ideal, because among the machines with errors in the same email I also get machines, that run the state file successfully. This is making the content of the email much more obfuscated and difficult to find machines with problems quickly.

### Setup
Here is the setup.

_runners/process_minion_data.py
```import subprocess
import salt.modules.smtp

def email_errors(fromaddr, toaddrs, subject, data_str, smtp_server):
   data = eval(data_str)
   error = False
   changes = False

   if type(data['return']) is dict:
      for state, result in data['return'].iteritems():
         if not result['result']:
            error = True
            break
         if result['changes']:
            changes = True
            break
   else:
      if not data['success']:
         error = False

   if error:
      body = subprocess.check_output(["salt-run", "jobs.lookup_jid", data['jid']])
      salt.modules.smtp.send_msg(\
            toaddrs,\
            body,\
            subject=subject,\
            sender=fromaddr,\
            server=smtp_server,\
            use_ssl=True)

   return True
```
reactor/email-on-failure.sls
```
email-on-failure:
  runner.process_minion_data.email_errors:
    - smtp_server: smtp.example.com
    - fromaddr: root@server.example.com
    - toaddrs: user@example.com
    - subject: "Salt master: minion failure or changes: id: {{ data['id'] }} jid: {{ data['jid'] }}"
    - data_str: {{ data|yaml_dquote }}
```
/etc/salt/master
```
reactor:
  - 'salt/job/*/ret/*':
    - salt://reactor/email-on-failure.sls

runner_dirs:
  - /srv/salt/_runners

state_output: changes
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Jun 19 2019, 17:20:54)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.14.123-111.109.amzn2.x86_64
         system: Linux
        version: Not Installed

**Comment by garethgreenaway** [comment]
@nrebelski Thanks for the question.  As far as the scheduled jobs, if you monitor the event bus on the Salt master using `salt-run state.event pretty=True` do you see those jobs returning?
