### ISSUE TITLE
pymssql removed from windows/req.txt

### ISSUE THREAD

**Issue by haodeon** [saltstack/salt#55484]
### Description of Issue
Issue #52805 requested pymssql lib to be included in the Salt windows package. This was merged in #52827. Pull request #53408 (commit b9618f6) removed pymssql from reqs.txt.

Was it intended to reverse the inclusion of pymssql with Salt? I believe inclusion would be good as working with mssql is a common scenario for windows minions.

**Comment by cmcmarrow** [comment]
I don't know let me ask the person who merged it.

**Comment by cmcmarrow** [comment]
The person who removed it says it may have been breaking something, but does not remember fully. So I see no harm if a new PR is opened a merged with pymssql.
