### ISSUE TITLE
Update docs to reflect new branching strategy

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#55494]
### Description of Issue

The documentation about contributing needs to get updated to reflect the new branching strategy.

https://docs.saltstack.com/en/latest/topics/development/contributing.html#the-develop-branch

**Comment by sagetherage** [comment]
@cmcmarrow @barbaricyawps assigning both of you - Chad, Alyssa can help with the technical English, but she will need you write the changes, first. This really should get done for Neon.
