### ISSUE TITLE
Pillar data can't use custom renderers

### ISSUE THREAD

**Issue by mathukumillia** [saltstack/salt#55495]
### Description of Issue
Custom renderers are not used in pillar data.

### Setup
I have a custom renderer called cfg.py in salt://_renderers. This renderer looks like: 
```
def render(data, saltenv='base', sls='', **kws):
  return {"test": "hello"}
```
I'm trying to use this in pillar to load some data from a file called crimson.sls. This file looks like: 
```
#!cfg
```
Crimson is included in the top.sls inside /pillar. However, when I print out pillar, there is no "test" key.

### Steps to Reproduce Issue
As described in the setup, this issue manifests whenever a custom renderer is used to render pillar data.

### Versions Report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.8 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.8

**Comment by DmitryKuzmenko** [comment]
@mathukumillia have you synced renderers on master first?
```
salt-run saltutil.sync_renderers
```

**Comment by mathukumillia** [comment]
Yes. I have run this command and verified that the renderer exists in /var/cache/salt/master/extmods/renderers.
