### ISSUE TITLE
Documentation on syncing custom modules slightly inaccurate and missing info on sync to master

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#55514]
### Description of Issue

The [custom modules documentation](https://docs.saltstack.com/en/latest/ref/modules/) says that running `state.apply` will sync the custom modules to the minions.  This is misleading, as it will not sync them if `state.apply` is run with a state as an argument, but only when run without arguments, i.e. running a highstate.

As well, there should be explicit documentation about the requirement to sync custom modules to the master with `salt-run` in order for them to be available in orchestrations.

**Comment by sagetherage** [comment]
will be released in Sodium
