### ISSUE TITLE
package and package repo tests are being skipped on everything except arch linux

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#55524]
### Description of Issue
https://jenkinsci.saltstack.com/job/pr-centos7-py2/job/master/217/testReport/integration.states.test_pkg/
https://jenkinsci.saltstack.com/job/pr-centos7-py2/job/master/217/testReport/integration.states.test_pkgrepo/

This isn't happening on 2019.2.3 so this is recent.

**Comment by dmurphy18** [comment]
Problem is due to checking for modules but failing tests are for states, that is,

pkgrepo,managed, pkg.installed and pkg.removed are states not execution modules.

**Comment by dmurphy18** [comment]
@bryceml @Akm0d  is working on solution for this, assigning him to it

**Comment by bryceml** [comment]
@Akm0d @sagetherage I think this was fixed, do you know if that's the case?

**Comment by sagetherage** [comment]
yes, it looks like this is fixed - closing
