### ISSUE TITLE
Reconfigure Salt Stalebot to exclude specifics

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#55549]
### Description of Issue
Add to the slatebot exemptLabels: 
  - P1
  - P2
  - Blocker
  - Critical

### Setup
N/A

### Steps to Reproduce Issue
github > saltstack org > settings > Installed GitHub Apps > stalebot > configure
requires Admin access to the org

### Versions Report
N/A

**Comment by waynew** [comment]
`Confirmed` should also be excluded, I think.

**Comment by waynew** [comment]
From our discussion in Salt Community Open Hour, we've had a bunch of discussion around Stalebot. To summarize the discussion:

- Stalebot does a *lot* of good - out of 4,000+ stale issues, less than ~10% have been (possibly) erroneously closed.
- Stalebot shouldn't close "Confirmed" issues. Ever.
- The community suggested that closing *earlier* might actually better - if we mark stale after 30 days, issues will be more fresh in people's minds.

I went ahead and created a PR with the aforementioned changes 🎉
