### ISSUE TITLE
Bhyve support in Fluorine is broken

### ISSUE THREAD

**Issue by jeroen92** [saltstack/salt#55556]
### Description of Issue
After upgrading to salt 2019.2.0 the virt module is broken for me.

```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/local/lib/python2.7/site-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/local/lib/python2.7/site-packages/salt/loader.py", line 1939, in wrapper
                  return f(*args, **kwargs)
                File "/usr/local/lib/python2.7/site-packages/salt/states/virt.py", line 460, in running
                  password=password)
                File "/usr/local/lib/python2.7/site-packages/salt/modules/virt.py", line 1498, in init
                  .format(hypervisor)
              SaltInvocationError: Unsupported hypervisor when handling disk image: bhyve
     Started: 21:51:38.589633
    Duration: 5.294 ms
     Changes:
```
It seems two commits adding bhyve & zfs support to virt (9cace9adb9ddef8da94b6ee2db3943a40d061817 and 18d605efda354d24f255067ccb854f3c5a7b3545) of my MR last year (https://github.com/saltstack/salt/pull/47620) are not included in the master branch. Manually checking out the salt repo and running from the develop branch still works for me (as those MRs commits are still on there as well). Bhyve support on master however is completely broken.

### Setup
salt-call 2019.2.0 (Fluorine)

**Comment by waynew** [comment]
@jeroen92 thanks for this issue!

Yes, that's correct - in fact, the `develop` branch would have been the Sodium release so it definitely wouldn't have been in `2019.2.x` at all.

With our shift to a single release branch, we've committed to merge all the changes that made it into other branches into master. You can view progress here: https://github.com/saltstack/salt/projects/5

As you can see, there's a huge amount of work to do, despite every one of us wanting to get them all done yesterday... there's just not enough of us to go around 🙃 

They *will* get ported to master, the only question is one of timing. If you'd like to hurry the process along, your PR looks like it did have some tests, so if you wanted to just rebase/cherry pick your commits on top of `master`, that would definitely expedite things.

Or if you don't have the time or inclination, we'll get there as soon as we can. Unfortunately, that may not be *soon* 😩 

Let me know if you have any questions!
