### ISSUE TITLE
S3 Pillar: Failed to load ext_pillar s3: [Errno 17] File exists: '/var/cache/salt/master/pillar_s3fs/base/mybucket/pillar/minionid'

### ISSUE THREAD

**Issue by Linuturk** [saltstack/salt#55594]
### Description of Issue
We receive this error when attempting to apply salt states to a given minion.

```
# salt 'myminion1' state.apply
...
 myminion1:
 Data failed to compile:
 ----------
 Pillar failed to render with the following messages:
 ----------
 Failed to load ext_pillar s3: [Errno 17] File exists: '/var/cache/salt/master/pillar_s3fs/base/mybucket/pillar/myminion2'
...
```

### Setup

Configure salt master to use S3 as a pillar source:
```
ext_pillar:
  - git:
    - __env__ ssh://git@mygitserver.com/pillar.git:
      - pubkey: '/etc/salt/ssh/saltmaster-id_rsa.pub'
      - privkey: '/etc/salt/ssh/saltmaster-id_rsa'
  - s3:
      bucket: mys3bucket
      prefix: pillar
```

Write your pillar data to S3. We have a unique pillar setup for each minion in the format of `minionid/init.sls`. We currently have 2249 pillar folder/file combinations in the bucket.

### Steps to Reproduce Issue
Doesn't seem to be consistently reproducible. Manually clearing the file it complains about typically allows us to run commands again. My guess is maybe there's a cleanup process for the cache that isn't fully clearing all files.

I've seen older issues related to the Pillar S3 provider not syncing more than 1000 files, but that seems to have been closed in 2015, so I don't think that's the problem.

### Versions Report
```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 1.5.2
       cherrypy: 3.5.0
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.24.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6                                                                                                  
   mysql-python: Not Installed                                                                                          
      pycparser: 2.14                                                                                                   
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.0
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-1054-aws
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by waynew** [comment]
Hi @Linuturk thanks for the report!

There may have been something closed in 2015, but it wasn't because there was a fix - that was implemented just recently https://github.com/saltstack/salt/pull/55694

Could you give that fix a try and see if it solves your issue?

**Comment by sagetherage** [comment]
Looks like this is fixed, so merely updating the label @Linuturk can you let us know if #55694 solves the issue, please?

**Comment by sagetherage** [comment]
Fix has been merged, closing the ticket as fixed. @Linuturk please let us know if you still experience issues.
