### ISSUE TITLE
Update or deprecate heat module and keystone state module to work with new keystoneng module

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#55611]
### Description of Issue
This issue https://github.com/saltstack/salt/issues/49419 was setup to track deprecating the keystone module in salt/modules/keystone.py in favor of salt/modules.keystoneng.py. The problem is there are a couple other files that use this module that still need to either be deprecated or updated to work with the new keystoneng module.

For now I am going to push the deprecation warning out to a later release and use this issue to track setting these other modules on a deprecation path or updating them to use the new keystoneng module. The modules that still call salt/modules/keystone are:

- salt/states/keystone.py
- salt/modules/heat.py

glance module also calls the keystone module but the glance module is already set on a deprecation path itself for its own module.

**Comment by waynew** [comment]
pushing this (once again) to Magnesium

**Comment by sagetherage** [comment]
closing this issue in favor of linked issue
