### ISSUE TITLE
Only 1 minion returns with cowsay. Others respond with /bin/sh: 1: cowsay: not found

### ISSUE THREAD

**Issue by Davo77** [saltstack/salt#55619]
1st installed cowsay on all minions with

$ sudo salt '*' pkg.install cowsay 
They all returned ok. 

Tested with 
$ sudo salt '*' cmd.run 'cowsay Merry Christmas - Hou'

1 Returned ok. 
2 other minions responded with: /bin/sh: 1: cowsay: not found

What is wrong?

**Comment by garethgreenaway** [comment]
@Davo77 Thanks for the report.  Can you provide a bit of information on the minions where the command is not running as expected?  The version of Salt, the operating system and the output from:
`sudo salt '*' cmd.run 'echo $PATH'`.  Thanks!
