### ISSUE TITLE
cpan modules not working with state : Reason: Module 'cpan' is not available.

### ISSUE THREAD

**Issue by fabrice1972** [saltstack/salt#55657]
### Description of Issue
when invoquing cpan.install directly, it is OK :

> [root@lnxtst01-foncier /srv/salt/test]# salt 'lnxtst01*' cpan.install XML::Twig
> lnxtst01-foncier.appli.dgfip:
>     ----------
>     new:
>         3.52
>     old:
>         3.52
> 

when invoked from a state, it does not work : 

> [root@lnxtst01-foncier /srv/salt/test]# salt 'lnxtst01*' state.apply perl.tata
> lnxtst01-foncier.appli.dgfip:
>     ----------
>     cpan_|-XML::Twig_|-XML::Twig_|-installed:
>         ----------
>         __run_num__:
>             0
>         changes:
>             ----------
>         comment:
>             State 'cpan.installed' was not found in SLS 'perl.tata'
>             Reason: Module 'cpan' is not available.
>         name:
>             XML::Twig
>         result:
>             False
> 

I think that the problem comes from the line :  "Could not LazyLoad cpan.installed" that you can see in the minion side of the debug log, when invoked from state

### Setup
file tata.sls : (I tried different syntax, including the examples in the doc)

```
XML::Twig:
  cpan.installed

```
### debug logs : invocation from state : minion side

> [DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20191216125816405245', 'tgt': '*', 'ret': '', 'user': 'root', 'arg': ['perl.tata'], 'fun': 'state.apply'}
> [INFO    ] Starting a new job with PID 30103
> [DEBUG   ] LazyLoaded state.apply
> [DEBUG   ] LazyLoaded saltutil.is_running
> [DEBUG   ] LazyLoaded grains.get
> [DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'lnxtst01-foncier.appli.dgfip', 'tcp://127.0.0.1:4506')
> [DEBUG   ] Reading configuration from /etc/salt/minion
> [DEBUG   ] Including configuration from '/etc/salt/minion.d/_schedule.conf'
> [DEBUG   ] Reading configuration from /etc/salt/minion.d/_schedule.conf
> [DEBUG   ] The `dmidecode` binary is not available on the system. GPU grains will not be available.
> [DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'lnxtst01-foncier.appli.dgfip', 'tcp://127.0.0.1:4506')
> [DEBUG   ] Loaded minion key: /etc/salt/pki/minion/minion.pem
> [INFO    ] Loading fresh modules for state activity
> [DEBUG   ] LazyLoaded jinja.render
> [DEBUG   ] LazyLoaded yaml.render
> [DEBUG   ] Fetching file from saltenv 'base', ** attempting ** 'salt://perl/tata.sls'
> [INFO    ] Fetching file from saltenv 'base', ** done ** 'perl/tata.sls'
> [DEBUG   ] Jinja search path: ['/var/cache/salt/minion/files/base']
> [DEBUG   ] Rendered data from file: /var/cache/salt/minion/files/base/perl/tata.sls:
> XML::Twig:
>   cpan.installed
> 
> [DEBUG   ] LazyLoaded config.get
> [DEBUG   ] Results of YAML rendering:
> OrderedDict([('XML::Twig', 'cpan.installed')])
> [DEBUG   ] LazyLoaded sysctl.show
> [DEBUG   ] Error loading module.ipmi: No module named pyghmi.ipmi
> [DEBUG   ] Error loading module.tls: ['PyOpenSSL version 0.10 or later must be installed before this module can be used.']
> [DEBUG   ] Error loading module.glusterfs: glusterfs server is not installed
> [DEBUG   ] Error loading module.nacl: libnacl import error, perhaps missing python libnacl package
> [DEBUG   ] Error loading module.npm: npm execution module could not be loaded because the npm binary could not be located
> [DEBUG   ] Could not LazyLoad xmpp.send_msg
> [DEBUG   ] LazyLoaded lvs.get_rules
> [DEBUG   ] Could not LazyLoad firewall.get_config
> [DEBUG   ] LazyLoaded portage_config.get_missing_flags
> [DEBUG   ] LazyLoaded layman.add
> [DEBUG   ] LazyLoaded selinux.getenforce
> [DEBUG   ] LazyLoaded win_servermanager.install
> [DEBUG   ] LazyLoaded boto_iam.role_exists
> [DEBUG   ] Error loading states.ipmi: No module named pyghmi.ipmi
> [DEBUG   ] Could not LazyLoad redis.set_key
> [DEBUG   ] LazyLoaded boto_asg.exists
> [DEBUG   ] LazyLoaded mysql.user_create
> [DEBUG   ] LazyLoaded boto_elb.exists
> (...)
> [DEBUG   ] Could not LazyLoad influxdb.db_exists
> [DEBUG   ] LazyLoaded zk_concurrency.lock
> [DEBUG   ] LazyLoaded ps.pkill
**> [DEBUG   ] Could not LazyLoad cpan.installed**
> [INFO    ] Running state [XML::Twig] at time 12:58:16.907832
> [DEBUG   ] Could not LazyLoad cpan.installed
> [ERROR   ] State 'cpan.installed' was not found in SLS 'perl.tata'
> Reason: Module 'cpan' is not available.
> 
> [DEBUG   ] File /var/cache/salt/minion/accumulator/4396392701792 does not exist, no need to cleanup.
> [DEBUG   ] Minion return retry timer set to 7 seconds (randomized)
> [INFO    ] Returning information for job: 20191216125816405245
> 

### debug logs : invocation from state : master side

> [DEBUG   ] LazyLoaded local_cache.prep_jid
> [DEBUG   ] Sending event - data = {'_stamp': '2019-12-16T11:58:16.405392', 'minions': ['lnxtst01-foncier.appli.dgfip', 'lnxtst02-foncier.appli.dgfip']}
> [DEBUG   ] Sending event - data = {'tgt_type': 'glob', 'jid': '20191216125816405245', 'tgt': '*', '_stamp': '2019-12-16T11:58:16.405566', 'user': 'root', 'arg': ['perl.tata'], 'fun': 'state.apply', 'minions': ['lnxtst01-foncier.appli.dgfip', 'lnxtst02-foncier.appli.dgfip']}
> [INFO    ] User root Published command state.apply with jid 20191216125816405245
> [DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20191216125816405245', 'tgt': '*', 'ret': '', 'user': 'root', 'arg': ['perl.tata'], 'fun': 'state.apply'}
> [DEBUG   ] LazyLoaded jinja.render
> [DEBUG   ] LazyLoaded yaml.render
> [DEBUG   ] Jinja search path: ['/srv/pillar']
> [DEBUG   ] Rendered data from file: /srv/pillar/top.sls:
> base:
>   'lnxtst01*':
>     - machines.test
>     - users.si2b
> (...)
> [DEBUG   ] Sending event - data = {'fun_args': ['perl.tata'], 'jid': '20191216125816405245', 'return': {'cpan_|-XML::Twig_|-XML::Twig_|-installed': {'comment': "State 'cpan.installed' was not found in SLS 'perl.tata'\nReason: Module 'cpan' is not available.\n", '__run_num__': 0, 'changes': {}, 'result': False, 'name': 'XML::Twig'}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2019-12-16T11:58:17.003503', 'fun': 'state.apply', 'id': 'lnxtst02-foncier.appli.dgfip'}
> [INFO    ] Got return from lnxtst01-foncier.appli.dgfip for job 20191216125816405245
> [DEBUG   ] Sending event - data = {'fun_args': ['perl.tata'], 'jid': '20191216125816405245', 'return': {'cpan_|-XML::Twig_|-XML::Twig_|-installed': {'comment': "State 'cpan.installed' was not found in SLS 'perl.tata'\nReason: Module 'cpan' is not available.\n", '__run_num__': 0, 'changes': {}, 'result': False, 'name': 'XML::Twig'}}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2019-12-16T11:58:17.011611', 'fun': 'state.apply', 'id': 'lnxtst01-foncier.appli.dgfip'}
> 

### debug logs : direct invocation, minion side : 
> [DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'lnxtst01-foncier.appli.dgfip', tcp://127.0.0.1:4506')
> [INFO    ] User root Executing command cpan.install with jid 20191216131046791563
> [DEBUG   ] Command details {'tgt_type': 'glob', 'jid': '20191216131046791563', 'tgt': 'lnxtst01*', 'ret': '', 'user': 'root', 'arg': ['XML::Twig'], 'fun': 'cpan.install'}
> [INFO    ] Starting a new job with PID 31260
> [DEBUG   ] LazyLoaded cpan.install
> [INFO    ] Executing command 'cpan -D XML::Twig' in directory '/root'
> [DEBUG   ] output: Reading '/root/.cpan/Metadata'
>   Database was generated on Thu, 18 Jan 2018 18:54:16 GMT
> XML::Twig
> xxxxx
>         (no description)
>         M/MI/MIROD/XML-Twig-3.52.tar.gz
>         /usr/local/share/perl5/XML/Twig.pm
>         Installed: 3.52
>         CPAN:      3.52  up to date
>         Michel Rodriguez (MIROD)
>         xmltwig@gmail.com
> [INFO    ] Executing command 'cpan -J' in directory '/root'
> [DEBUG   ] output: $CPAN::Config = {
>                   'applypatch' => '',
>                   'auto_commit' => '0',
> (...)
>                   'yaml_load_code' => '0',
>                   'yaml_module' => 'YAML'
>                 };
> 
> 1; 
> __END__
> [INFO    ] Executing command 'cpan -i XML::Twig' in directory '/root'
> [DEBUG   ] output: Reading '/root/.cpan/Metadata'
>   Database was generated on Thu, 18 Jan 2018 18:54:16 GMT
> XML::Twig is up to date (3.52).
> [INFO    ] Executing command 'cpan -D XML::Twig' in directory '/root'
> [DEBUG   ] output: Reading '/root/.cpan/Metadata'
>   Database was generated on Thu, 18 Jan 2018 18:54:16 GMT
> XML::Twig
> xxxxx
>         (no description)
>         M/MI/MIROD/XML-Twig-3.52.tar.gz
>         /usr/local/share/perl5/XML/Twig.pm
>         Installed: 3.52
>         CPAN:      3.52  up to date
>         Michel Rodriguez (MIROD)
>         xmltwig@gmail.com
> [INFO    ] Executing command 'cpan -J' in directory '/root'
> [DEBUG   ] output: $CPAN::Config = {
>                   'applypatch' => '',
>                   'auto_commit' => '0',
>                   'build_cache' => '100',
> (...)
>                   'yaml_load_code' => '0',
>                   'yaml_module' => 'YAML'
>                 };

> 1;
> __END__
> [DEBUG   ] Minion return retry timer set to 10 seconds (randomized)
> [INFO    ] Returning information for job: 20191216131046791563
> [DEBUG   ] Re-using SAuth for ('/etc/salt/pki/minion', 'lnxtst01-foncier.appli.dgfip', 'tcp://127.0.0.1:4506')
> "Reading '/root/.cpan/Metadata'\n  Database was generated on Thu, 18 Jan 2018 18:54:16 GMT\nXML::Twig is up to date (3.52)."
> 

### debug logs : direct invocation, master side : 

> [DEBUG   ] Sending event - data = {'_stamp': '2019-12-16T13:01:48.388216', 'minions': ['lnxtst01-foncier.appli.dgfip']}
> [DEBUG   ] Sending event - data = {'tgt_type': 'glob', 'jid': '20191216140148388031', 'tgt': 'lnxtst01*', '_stamp': '2019-12-16T13:01:48.388472', 'user': 'root', 'arg': ['XML::Twig'], 'fun': 'cpan.install', 'minions': ['lnxtst01-foncier.appli.dgfip']}
> [INFO    ] User root Published command cpan.install with jid 20191216140148388031
> [DEBUG   ] Published command details {'tgt_type': 'glob', 'jid': '20191216140148388031', 'tgt': 'lnxtst01*', 'ret': '', 'user': 'root', 'arg': ['XML::Twig'], 'fun': 'cpan.install'}
> [INFO    ] Got return from lnxtst01-foncier.appli.dgfip for job 20191216140148388031
> [DEBUG   ] Sending event - data = {'fun_args': ['XML::Twig'], 'jid': '20191216140148388031', 'return': {'new': '3.52', 'old': '3.52'}, 'retcode': 0, 'success': True, 'cmd': '_return', '_stamp': '2019-12-16T13:01:52.567082', 'fun': 'cpan.install', 'id': 'lnxtst01-foncier.appli.dgfip'}
> 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
[root@lnxtst01-foncier /tmp]# salt --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Jun 25 2019, 07:10:03)
         Jinja2: 2.9.6
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

**Comment by garethgreenaway** [comment]
@fabrice1972 Thanks for the report.  I noticed that you're using version 2015.5.10 of Salt, which is no longer supported.  Additionally the cpan state was only recently added to the code base.

**Comment by reinaldo-gomes** [comment]
I'm having the same issue on Salt version 3000
