### ISSUE TITLE
migrate neutron pillar to use neutronng module

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#55663]
Currently the `neutron` external pillar is setup to use the `neutron` module, but this module is set to be deprecated. It was set to be deprecated in neon with this issue: https://github.com/saltstack/salt/issues/49430 but it will need to be bumped to `Aluminium` to give us time to ensure the neutron pillar is migrated to the new module `neutronng` first. This issue is to track that work.

**Comment by cmcmarrow** [comment]
im working on this dep
