### ISSUE TITLE
Docs: Missing space before default value

### ISSUE THREAD

**Issue by guettli** [saltstack/salt#55673]
in the current docs there is a space missing before the default value:

Source:

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.file.html#salt.modules.file.blockreplace

![image](https://user-images.githubusercontent.com/414336/70987380-1072f380-20c0-11ea-9804-88d0e52ac611.png)

Browser: Chromium | 78.0.3904.108 (Offizieller Build) Built on Ubuntu , running on Ubuntu 18.04 (64-Bit)

**Comment by cmcmarrow** [comment]
Thanks @guettli
