### ISSUE TITLE
AzureARM - Unable to Build Servers Using ssh_publickeyfile

### ISSUE THREAD

**Issue by og-blsy** [saltstack/salt#55677]
### Description of Issue
Unable to build VMs because the `ssh_password` field is required.  

The documentation: https://docs.saltstack.com/en/latest/topics/cloud/azurearm.html suggests that you can use an SSH key OR a Password.

Even when building using `ssh_password`,  Salt is still unable to fully provision the server, since it doesn't have sudo rights (NOPASSWD:ALL).

```
> cat /etc/sudoers.d/waagent
azure ALL=(ALL) ALL
```

### Setup

azure:
  provider: azure
  resource_group: my-rg
  image: CentOS-7.5.1810-5
  size: Standard_D1_v2
  ssh_keyfile: /path/to/keyfile
  ssh_publickeyfile: /path/to/publickeyfile.pub
  ssh_username: azure
  #ssh_password: fails-if-i-dont-have-one
  network: network-1
  subnet: subnet-1
  virtual_network_name: network-1
  allocate_public_ip: False
  bootstrap_interface: private

### Steps to Reproduce Issue

salt-cloud -p azure server1 -l debug

[ERROR   ] There was a profile error: expected str, bytearray, or unicode
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 281, in run
    self.config.get('names')
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1458, in run_profile
    ret[name] = self.create(vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/__init__.py", line 1288, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 1403, in create
    vm_request = request_instance(vm_=vm_)
  File "/usr/lib/python2.7/site-packages/salt/cloud/clouds/azurearm.py", line 1042, in request_instance
    'win_password', vm_, __opts__, search_global=True
  File "/usr/lib/python2.7/site-packages/salt/utils/stringutils.py", line 118, in to_str
    raise TypeError('expected str, bytearray, or unicode')
TypeError: expected str, bytearray, or unicode

### Versions Report

Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.12.3
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 20 2019, 20:27:34)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.7.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core

**Comment by nicholasmhughes** [comment]
This should be fixed in the latest 2019.2 release

https://github.com/saltstack/salt/pull/53238

**Comment by cmcmarrow** [comment]
https://github.com/saltstack/salt/pull/54173/files

**Comment by cmcmarrow** [comment]
The fix has been merged!
