### ISSUE TITLE
lxd states - fail in test mode

### ISSUE THREAD

**Issue by cr1st1p** [saltstack/salt#55686]
### Description of Issue
I'm trying to use saltstack in test mode (```salt .... test=True```) to see what it would do.
I have some LXD setup being done (using standard lxd saltstack formula), but it fails.

LXD modules seem to not have maybe code to handle test mode?

### Setup
Just using saltstack formula https://github.com/saltstack-formulas/lxd-formula.git which is creating  a few things, like  setting **core.trust_password**, or creating a profile, via a state **lxd_profile.present**
Both fails with error "CommandNotFoundError: The 'lxd' binary was not found in $PATH."
Which is normal, since I did the run in test mode, so it did not install lxd.

### Steps to Reproduce Issue
You can also just use this sls:
```

lxd_config_password:
  lxd.config_managed:
    - name: core.trust_password
    - value: somePassword
    - force_password: True

```
Then try running it, with ```test=True```

### Versions Report
```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.17 (default, Nov  7 2019, 10:07:09)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.3.15-1-MANJARO
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by Ch3LL** [comment]
this is expected behavior. If you have a state that is set to install a binary and another state that requires that binary to check if `config_managed` has already run with those settings, you will see the failure that the binary is not there. I did check the code and it looks like `config_managed` does have code to check if test is set, but it will not load the module because the binary does not exists, which is required to load the module.
