### ISSUE TITLE
salt-run net.find 1.2.3.4 fails on 2019.2.2 / Python 3

### ISSUE THREAD

**Issue by chonty** [saltstack/salt#55691]
### Description of Issue

On Salt 2019.2.2 with Python 3, `salt-run net.find <ip address>` fails because of some out-of-date code.

```
[root@salt runners]# salt-run net.find 1.2.3.4
Details for all interfaces that include network 1.2.3.4/32 - only best match returned
ARP Entries for IP 1.2.3.4
Exception occurred in runner net.find: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 377, in low
    data['return'] = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/runners/net.py", line 894, in find
    device, interface, mac = _find_interfaces_mac(ip)
  File "/usr/lib/python3.6/site-packages/salt/runners/net.py", line 228, in _find_interfaces_mac
    ip_addresses.extend(interface_ipaddrs.get('ipv6', {}).keys())
AttributeError: 'dict_keys' object has no attribute 'extend'
```
and
```
[root@salt runners]# salt-run net.find 1.2.3.4

Passed invalid arguments: '>' not supported between instances of 'IPNetwork' and 'NoneType'
```

### Setup
On proxy minions:

```
mine_functions:
  net.ipaddrs: []
  net.lldp: []
  net.mac: []
  net.arp: []
  net.interfaces: []
```
### Steps to Reproduce Issue
```
[root@salt runners]# salt-run net.find 1.2.3.4
Details for all interfaces that include network 1.2.3.4/32 - only best match returned
ARP Entries for IP 1.2.3.4
Exception occurred in runner net.find: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 377, in low
    data['return'] = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/runners/net.py", line 894, in find
    device, interface, mac = _find_interfaces_mac(ip)
  File "/usr/lib/python3.6/site-packages/salt/runners/net.py", line 228, in _find_interfaces_mac
    ip_addresses.extend(interface_ipaddrs.get('ipv6', {}).keys())
AttributeError: 'dict_keys' object has no attribute 'extend'
```

```
[root@salt runners]# salt-run net.find 1.2.3.4

Passed invalid arguments: '>' not supported between instances of 'IPNetwork' and 'NoneType'
```
### Versions Report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

**Comment by sagetherage** [comment]
@chonty assigning you to the issue since you also submitted the PR and thank you so much! I don't want the stale bot to close this so updating.
