### ISSUE TITLE
Documentation tables with yaml examples are badly aligned

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#55693]
### Description of Issue

Documentation that includes yaml examples in a table are badly formatted, e.g. https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.stack.html#merging-examples:

![image](https://user-images.githubusercontent.com/170730/71106035-fa833280-2194-11ea-9a14-cc6de0611aac.png)

It looks like this can be fixed by disabling `text-align: center`:

![image](https://user-images.githubusercontent.com/170730/71106203-46ce7280-2195-11ea-8d5f-e122145a89b7.png)

![image](https://user-images.githubusercontent.com/170730/71106274-71b8c680-2195-11ea-89b5-953d56c65a56.png)

But it's not clear to me how to change the RST or documentation build process to not assign the `align-center` class to these tables.

**Comment by oeuftete** [comment]
not stale.  cc: @saltstack/docs-working-group

**Comment by oeuftete** [comment]
The [reactor documentation](https://docs.saltstack.com/en/latest/topics/reactor/#local-reactions) is another place where this problem is clear.

**Comment by alan-cugler** [comment]
Good to know, thanks for bringing it to my attention. I will add this to the kick off meeting for docs work group.

**Comment by sagetherage** [comment]
stale bot not

**Comment by sagetherage** [comment]
the label `bug`  and `Confirmed` which should keep the stale bot at bay -- with `Documentation and the bug label the Open Core team will know that it is something wrong with the docs to update - I am also thinking we need a Doc WG like team-wg-docs (team-docs is internal) or simply `WG` for working group will take up this work @alan-cugler thoughts? or no? it would be easy to add that to the stale bot config as well.

**Comment by oeuftete** [comment]
Something along the way fixed the examples I gave (sphinx upgrade?).

![image](https://user-images.githubusercontent.com/170730/97106836-9bd6f100-16a2-11eb-8824-b4eafcb1d0c5.png)

![image](https://user-images.githubusercontent.com/170730/97106841-a7c2b300-16a2-11eb-9be6-42637a09d167.png)
