### ISSUE TITLE
file.directory_exists won't work

### ISSUE THREAD

**Issue by Cybergenik** [saltstack/salt#55703]
"That's not valid jinja, at all. Given what you've provided, it doesn't look like this is actually an issue with Salt, so I'm going to go ahead and close this.

Here's a good primer on using Salt + Jinja: https://docs.saltstack.com/en/latest/topics/jinja/index.html
If you're unable to find the answers to your questions there, check out [this community page](https://www.saltstack.com/resources/community/) for links to Slack, IRC, and a mailing list. "

_Originally posted by @waynew in https://github.com/saltstack/salt/issues/55627#issuecomment-566603725_

----------------------------------------------------------------------------------------------

Hi @waynew , 

I made a mistake by not putting my code in \`\`\` however it was pretty clear that it was a mistake, I updated the comment with the correct format. You can clearly see that in the initial post I used correct Jinja syntax... Please reopen the initial post.

**Comment by garethgreenaway** [comment]
Reopened original issue, closing this one.
