### ISSUE TITLE
test.py engine does not work, fails on the 'with' statement

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#55742]
### Description of Issue
```
[CRITICAL] Engine 'test' could not be started!
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/engines/__init__.py", line 132, in run
    self.engine[self.fun](**kwargs)
  File "/srv/salt_engines/test.py", line 38, in start
    with event_bus_context(__opts__) as event_bus:
AttributeError: __exit__
```

### Setup
Use test.py engine module from https://github.com/saltstack/salt/blob/master/salt/engines/test.py
salt-master 2019.2.2 (Fluorine)

### Steps to Reproduce Issue
Use test.py engine module from https://github.com/saltstack/salt/blob/master/salt/engines/test.py
Save file to /srv/salt_engines/test.py
# cat /etc/salt/master.d/engines.conf
```
engines:
  - test: []

engines_dirs:
  - /srv/salt_engines
```

Start salt-master:
```
[CRITICAL] Engine 'test' could not be started!
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/engines/__init__.py", line 132, in run
    self.engine[self.fun](**kwargs)
  File "/srv/salt_engines/test.py", line 38, in start
    with event_bus_context(__opts__) as event_bus:
AttributeError: __exit__
```

### Versions Report
salt-master 2019.2.2 (Fluorine)

### Workaround:
The code in the attached file works fine.
Just replaced the 'with' statement on line 38.
```
    #with event_bus_context(__opts__) as event_bus:
    event_bus = event_bus_context(__opts__)
```

[engine_example copy.py.txt](https://github.com/saltstack/salt/files/4005659/engine_example.copy.py.txt)

**Comment by garethgreenaway** [comment]
@amalaguti Thanks for the report.  So far I haven't been able to reproduce this one.  Can you provide the output from `salt --versions-report`?
