### ISSUE TITLE
Deb package compile instructions removed.. wtf?

### ISSUE THREAD

**Issue by foxx** [saltstack/salt#5575]
In [1], the deb package compile instructions were included. However in the latest [2], they have been removed. Is there any legit reason to not have this info included? If not, then I'll get a patch done to put the info back in.

Thanks

Cal

[1] http://salt.readthedocs.org/en/v0.12.1/topics/installation/debian.html
[2] http://docs.saltstack.com/topics/installation/debian.html

**Comment by UtahDave** [comment]
The salt-pack project defines how to build the deb packages now
