### ISSUE TITLE
requirements/dev_python27.txt missing 

### ISSUE THREAD

**Issue by morgana2313** [saltstack/salt#55804]
### Description of Issue

@garethgreenaway, @dwoz:

The [test suite introduction](https://docs.saltstack.com/en/latest/topics/tutorials/writing_tests.html#getting-set-up-for-tests) refers to `requirements/dev_python27.txt`:

```
pip install -r requirements/dev_python27.txt
pip install -r requirements/dev_python34.txt
```

The same goes for the [SALT'S TEST SUITE](https://docs.saltstack.com/en/latest/topics/development/tests/index.html#running-the-tests) page.

I think the contents of this file moved elsewhere (`requirements/static/py2.7/linux` ?) and the documentation is not updated yet after #54604

**Comment by waynew** [comment]
This issue should be handled when we re-write the testing docs, because we should be using `nox` to run the tests, which will take care of this invalid instruction :P

**Comment by sagetherage** [comment]
@ScriptAutomate @waynew did we fix this in the clean up of the testing docs and contributor docs?

**Comment by morgana2313** [comment]
Dank voor uw bericht.

Ik ben afwezig tot 16 mei 2021 en lees sporadisch mijn mail.

Voor dringende zaken kunt u contact opnemen met mijn collega's via  070 891 9 891 of via ***@***.***
