### ISSUE TITLE
Configuration options will change in 2019.2.0. in doc when 2019.2.2 is out

### ISSUE THREAD

**Issue by soloturn** [saltstack/salt#55809]
### Description of Issue
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.kubernetes.html

says :
Warning
Configuration options will change in 2019.2.0.

i am not sure where this message comes from to make a pull request, but 2019.2.0 is out isn't it?

**Comment by dmurphy18** [comment]
Closing since 2019.x.x is long since EOL
