### ISSUE TITLE
salt github releases has invalid warning

### ISSUE THREAD

**Issue by soloturn** [saltstack/salt#55810]
https://github.com/saltstack/salt/releases says:

WARNING: The tarball generated by GitHub will not have the correct version information when using a version not ending in .0 . Please use the tarball generated by SaltStack instead. See issue #41847 for more information.

the referenced ticket is closed since 3 months. should this message hence be removed now?

**Comment by sagetherage** [comment]
@soloturn you make a good point, I am unsure if we are keeping that for historical purposes, but will attempt to get your question answered or update the ticket labels.
