### ISSUE TITLE
ERROR executing 'docker.prune': Invalid client action 'prune_images'

### ISSUE THREAD

**Issue by kveroneau** [saltstack/salt#55818]
### Description of Issue
Cannot run the salt execution module *docker.prune*, causes the error mentioned in the subject line.

### Setup
I originally tried to run docker.prune in a reactor to attempt diskspace self-heal, but after the self-heal did not work, I attempted to run the salt command manually:

`salt 'dockerhost' docker.prune images=True`

I should note that even without `images=True` it still fails.

### Steps to Reproduce Issue
Run the above salt command to attempt to run docker prune on the selected host.

### Versions Report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 1.9.0
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: 0.24.5
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.10 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-11-amd64
         system: Linux
        version: debian 9.10 

master/minion in this case are on the same host.

**Comment by Ch3LL** [comment]
this commit https://github.com/docker/docker-py/commit/7f0c2e75 added `prune_images` which was added in 2.3.0 and you are using version 1.9.0. Also they renamed that library from `docker-py` to `docker` as stated in our docs here https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.dockermod.html  so you will need to do a `pip install docker` to get the most recent versions.

**Comment by kveroneau** [comment]
I generally do not like using pip globally, and prefer using my distro's package manager to install system-level Python packages.  I guess this means that Debian Stretch does not ship with a new version of python-docker.  I downloaded the latest version from PyPi, and will know soon if the updated version resolves the issue.  I believe it should.  I wish the official Docker CE Debian repository had the newest version of the python-docker package.

**Comment by Ch3LL** [comment]
any luck?

**Comment by kveroneau** [comment]
Yes, it worked.  Thank you for pointing out the version differences.
