### ISSUE TITLE
Epic: Support for Python 3.8

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#55835]
### Description of Issue
Epic or bucket ticket for tasks for supporting Python 3.8 changes going forward, as an epic this ticket may span more than one release over time.

### Related ticket(s):
- https://github.com/saltstack/salt/issues/55310
- https://github.com/saltstack/salt/issues/55847
- https://github.com/saltstack/salt/issues/56998
- #55976
- #56027
- https://github.com/saltstack/salt/pull/56031

**Comment by Ch3LL** [comment]
- [ ] https://github.com/saltstack/salt/issues/55976

Deprecation Warnings that need to be cleaned up

**Comment by bdrung** [comment]
#55976 is a duplicate of #50911, which is addressed in pull request #56027

**Comment by bdrung** [comment]
I pushed more commits to pull request #56031. Now it fixes all Python 3.8 unit test failures. So after backporting these commits, the Debian package 2019.2.3+dfsg1-2 will build on Ubuntu 20.04 (which contains Python 3.8).

**Comment by s0undt3ch** [comment]
Related https://github.com/saltstack/salt/pull/55900

**Comment by s0undt3ch** [comment]
For anyone working on Py3.8 support, some work has been done in https://github.com/saltstack/salt/tree/features/py38-compat?files=1

**Comment by baby-gnu** [comment]
I think this should be excluded from stalebot.

**Comment by twangboy** [comment]
- [ ] https://github.com/saltstack/salt/issues/56998
