### ISSUE TITLE
network.connect and cmd.run module inconsistent return code

### ISSUE THREAD

**Issue by deput-d** [saltstack/salt#55837]
### Description of Issue
Not getting usable return codes from various salt modules like network.connect and cmd.run when checking network connections.

Using the network.connect module and jinja logic to test network connections, a simple if statement doesn't provide the expected return code (always returns true). It always picks up the first outcome even if it cant connect to it (in this case cant-connect.com). If the evaluation is explicitly set to a string to force a fail, then it will proceed onto the else outcome, so I know its at least attempting to evaluate the if statements. 

This also occurs if we try to work around the network.connect module by replacing network.connect with cmd.run and useing nc. 

Example:
map.jinja:
```
{% if salt['network.connect']('cant-connect.com 80') %}
  {% set http_proxy = 'cant-connect.com:80' %}
{% elif salt['network.connect']('www.example.com 80') %}
  {% set http_proxy = 'www.example.com:80 %}
{% else %}
  {% set http_proxy = 'localhost:3128' %}
{% endif %}
```

### Setup
master --> minion

lets say for example:
- master is able to resolve both cant-connect.com & www.example.com
- minion is only able to resolve www.example.com, so in theory it should fail the first evaluation and pass the second

A .sls file imports the above logic from a mapfile and applies it as a default to the template like so. 

```
/etc/environment:
  file.managed:
    - source: salt://etc/environment.jinja
    - template: jinja
    - defaults:
       proxyname: {{ http_proxy | json }}
```

### Steps to Reproduce Issue
Attempt to set variables at runtime by leveraging the network.connect module to dynamically set a variable based on ability to connect. 

### Versions Report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.12.3
       cherrypy: 3.5.0
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: 0.28.2
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: 3.7.2
         pygit2: 0.28.2
         Python: 2.7.12 (default, Aug 22 2019, 16:36:40)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-151-generic
         system: Linux
        version: Ubuntu 16.04 xenial

**Comment by Ch3LL** [comment]
it looks like `network.connect` is running `socket.getaddrinfo` to resolve the dns to ip. If you run this script:

```
import socket


(family, socktype, _proto, garbage, _address) = socket.getaddrinfo('thisseriouslydoesnotexist', 80, 0, 0, 6)[0]

print('trying to connect to {0}'.format(_address))
skt = socket.socket(family, socktype, _proto)
skt.connect(_address)
```

Does it connect? If so try passing in different dns names and see if you are returning the same IP addresses. Your DNS might be returning the same address for unknown hosts.

**Comment by deput-d** [comment]
Thanks for getting back to me so quickly, Unfortunatly not getting a connection when passing anything unresolvable. The script returns true as expected when I pass a known entry to it tho. 

Getting a `socket.gaierror: [Errno -2] Name or service not known` error when passing unresolvable/unknown queries. Could this maybe be a return that was unexpected/unaccounted for in the network.connect module?

**Comment by deput-d** [comment]
need anything else from me? 

I would think this would just works since the module returns True and False, but doesnt when you try to run it in the middle of a state. Sounds like a bug of some sort to me

**Comment by Ch3LL** [comment]
Went ahead and tried your state to take a closer look. The reason you are seeing this behavior is because you need to ensure you are passing the args correctly to the network module. So you need to change this `('cant-connect.com 80')` to `('cant-connect.com', 80)`. What was occuring is when you passed in `cant-connect.com 80'` the network module only saw that as the first `host` arg and port was None. 

The other issue is the network module returns a dictionary with result and comment, so you need to parse for the result like so: `{% if salt['network.connect']('cant-connect.com', 80)['result'] %}`

Heres a complete example:

```
{% if salt['network.connect']('cant-connect.com', 80)['result'] %}
  {% set http_proxy = 'cant-connect.com:80' %}
{% elif salt['network.connect']('www.example.com', 80)['result'] %}
  {% set http_proxy = 'www.example.com:80' %}
{% else %}
  {% set http_proxy = 'localhost:3128' %}
{% endif %}

echo {{ http_proxy }}:
  cmd.run
```

**Comment by deput-d** [comment]
wow that makes too much sense... I feel pretty silly I didnt check to see if it was returning something else w/ the status. 

I appreciate all the feedback and should be able to work with this.

**Comment by Ch3LL** [comment]
no problem. you okay closing?
