### ISSUE TITLE
research change log use of tools 

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#55836]
### Description of Issue
Research ticket task for exploring the use of a change log tools such as towncrier

**Comment by s0undt3ch** [comment]
The reason behind this ticket is because a single changelog file being updated in multiple PRs will always impose solving conflicts after each PR is merged.
This is extra work that we don't want to impose on the SaltStack team and more importantly on the SaltStack community.

**Comment by mchugh19** [comment]
Open feature and not stale
