### ISSUE TITLE
Amazon 1 Tests Test Run Time is Too High

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#55852]
Currently the amazon 1 tests on the master branch take around 6 hours to run, whereas they used to take 2-4 hours to run. This issue is created to track the work to investigate why amazon linux1 is taking longer to run then previously. We did bump the timeout to 7 hours for the time being but will still need to investigate to decrease this test run time.

**Comment by sagetherage** [comment]
Assigning @s0undt3ch to mentor @Akm0d as this looks bigger and may need more than one person, good way to learn, enjoy!

**Comment by Ch3LL** [comment]
@s0undt3ch and @Akm0d looks like amazon linux 1 (and also amazon linux 2 now) are once again timing out some times.

https://jenkinsci.saltstack.com/job/pr-amazon1-py2/job/PR-56380/1/

https://jenkinsci.saltstack.com/job/pr-amazon2-py2/job/PR-56380/1/

even with the increased timeout
