### ISSUE TITLE
[security] Salt-master should run as non-root user by default

### ISSUE THREAD

**Issue by harmv** [saltstack/salt#55886]
### Description of Issue

Running any server application, typically accessible via the internet, as root user is a security risk.
Bugs _do_ happen, in any application.   Apps should run with as little rights as possible.

Salt-master by default, runs as root user and salt documents how you can run salt-server as non root.(https://docs.saltstack.com/en/latest/ref/configuration/nonroot.html) 

This is the wrong way around.  It should run as non-root by default. And document when/why/how you can run it as root.

Installation scripts should install it as the proper user, chmod the proper files etc.

If I read the documentation correctly its PAM external auth that breaks when running as non-root (https://github.com/saltstack/salt/issues/7762)
If that really cannot be fixed in salt, then the Salt PAM external auth documentation should mention how you can change your salt installation to run as root.

### PAM external auth
I suspect(hope?) the problem with PAM external auth can be fixed even. That way you _never_ need to run salt-master as root.

I am no PAM expert, but pam_unix has a setuid helper (unix_chkpwd) that seems exactly intended for this. For applications, without read access to /etc/shadow/ to do authentication.

**Comment by udf2457** [comment]
I agree wholeheartedly with the sentiment expressed by @harmv 

Its 2020. The days of "meh, let's just run as root and leave it to the user to sort it out if they want to run unprivileged".  It should be unprivileged by default !  Lots of other software does it (e.g. Postfix) so there's no reason for Salt not to.

**Comment by Ch3LL** [comment]
i think this would make more sense to add to a salt-enhancement-proposal here: https://github.com/saltstack/salt-enhancement-proposals as this would definitely could be considered a substantial change. Would you mind closing here and opening a SEP so we can discuss there with the entire core team?

**Comment by mchugh19** [comment]
Not stale

**Comment by Ch3LL** [comment]
im going to close here as this discussion should be taking place in a SEP as stated in my previous comment so we can formalize the request and discussion.

**Comment by harmv** [comment]
Filed as SEP: https://github.com/saltstack/salt-enhancement-proposals/pull/25

**Comment by harmv** [comment]
ref: https://github.com/saltstack/salt-enhancement-proposals/pull/35
