### ISSUE TITLE
Need to update Salt versioning for Neon to 3000

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#55892]
### Description of Issue
Currently SaltStackVersion produces 3000.0.0 for Neon RC1. This needs to be improved to allow for 3000 as the first Neon version with the ability for patching producing 3000.1 if a patch is necessary.

Captured Slack conversation:
dwoz:coffee: 11:37
sure
My opinion is that we should try too make the change

if not for the RC, then for Neoon
daithi:office: 11:39
from quick scan of SaltStackVersion, between code / tests, I feel better to leave major and minor in there and leave them unused, this close to tagging especially
dwoz:coffee: 11:39
so if we ship the RC as 3000.0.0.rc1
but ship neon as 3000
daithi:office: 11:39
that would be it
dwoz:coffee: 11:39
I'm fine with that
daithi:office: 11:40
we would need to allow for 3000.1 for patches, implies 3000.0 with '.0' stripped and implied in all usage, install, testing, etc
dwoz:coffee: 11:40
yes
daithi:office: 11:41
fine with that, 3000.0.0rc1 it is
dwoz:coffee: 11:41
:+1:

This implies a large number of changes to Salt, testing, and di

### Setup
david@david-lap2:~/devcode/dgm_salt_master/salt$ cat salt/_version.py
from salt.version import SaltStackVersion
__saltstack_version__ = SaltStackVersion( 3000, 0, 0, 0, '', 0, 0, None )

### Steps to Reproduce Issue
python setup.py sdist

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by thusoy** [comment]
Hi! Sorry if this isn't the right place, but seemed the best existing issue I could find. From someone that primarily gets updates about salt from the salt-announce mailing list, the change in versioning scheme came out of the blue with no background info, and it doesn't seem to be reflected in https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html yet. What is the motivation for the change? Would be great if such changes would actually be communicated on the announce list as one should be able to stay up to date on major changes only by following that.

**Comment by sagetherage** [comment]
@thusoy we opened a SEP in November 2019 https://github.com/saltstack/salt-enhancement-proposals/pull/20 and you are correct we need to be better about communication and also correct that we have not yet updated the documentation. That is in the works as we speak, I haven't seen the PR open yet, but I talked to her about it, today and will link you to that once I have it.

**Comment by sagetherage** [comment]
I will also work with our new Community Manager on the communication in the announcements channel in the community Slack but for now will also put the SEP there as in the final comment period.

**Comment by thusoy** [comment]
Great, thanks for the links, was able to get up to speed. A brief note in the salt-announce mailing list with a link to the SEP would have been sufficient - I would prefer to not have to join another Slack just to get major updates about what's happening.

**Comment by dmurphy18** [comment]
Closing since this was a reminder for Salt 3000 which is now released and working as intended
