### ISSUE TITLE
python 3.7 warning on encodestring() deprecation

### ISSUE THREAD

**Issue by sblaisot** [saltstack/salt#55899]
### Description of Issue
in minion logs (salt 2019.2.3 on debian buster installed from official py3 packages):
```
2020-01-17 14:42:13,137 [py.warnings      :110 ][WARNING ][12187] /usr/lib/python3/dist-packages/salt/utils/hashutils.py:61: DeprecationWarning: encodestring() is a deprecated alias since 3.1, use encodebytes()
  base64.encodestring(salt.utils.stringutils.to_bytes(instr)),
```

### Setup
Unable to know what configuration or state trigger this.

### Steps to Reproduce Issue
Unable to know what configuration or state trigger this.

### Versions Report
# salt-minion -V
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 8.9.1
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.0 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-5-cloud-amd64
         system: Linux
        version: debian 10.0

**Comment by Ch3LL** [comment]
looks like there are other instances of `encodestring` other than just the file `hashutils.py` so we will need to get these cleaned up. The instance in hashutils.py is only used if using python2, so we should be able to get this fixed post neon since we are migrating to only python3 for the sodium release.

**Comment by Ajnbro** [comment]
@Ch3LL Does #55506 already address this issue or at least part of this issue?

**Comment by Ch3LL** [comment]
thanks for pointing that out, it should clean up the instance in hashutils,but there is still other instances in the code we need to clean up.
