### ISSUE TITLE
wrong success status for runners in pgjsonb returner

### ISSUE THREAD

**Issue by ihakh** [saltstack/salt#55909]
### Description of Issue
in salt_return table in Postgresql the 'success' column is always false for runners
the full_ret structure is different for runners :
there is a "return" dict in "return" dict in full_ret
the real success status is inside that.
I think the outer "return" must be updated with inner "return" values and must not include it

### Versions Report
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: 0.8.6
       cherrypy: unknown
       dateutil: 2.2
      docker-py: Not Installed
          gitdb: 0.5.4
      gitpython: 0.3.2 RC1
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.3
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.9 (default, Sep 14 2019, 20:00:08)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.4.0
           RAET: Not Installed
          smmap: 0.8.2
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

**Comment by ihakh** [comment]
is the current return layout correct?
I am going to write my queries based on this layout.
is it a bug?

**Comment by xeacott** [comment]
I wouldn't take this as a bug, as it seems as though the output is okay but the layout seems a little confusing. So you're meaning that is the following okay: `return[return[status_code]]` ?

**Comment by ihakh** [comment]
the row in the database shows the status wrong
success is always false
yes I think the real status_code is in there
