### ISSUE TITLE
Audit releasenotes for Neon

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#55902]
It's come to our attention that some of the changes listed in the release notes haven't actually made it into master. This is probably due to doc-only merges that got ported to master.

Let's take a look and make sure that our release notes are correct:

https://github.com/saltstack/salt/blob/master/doc/topics/releases/neon.rst

**Comment by sagetherage** [comment]
@saltstack/team-core

**Comment by sagetherage** [comment]
@waynew is this still pending, I thought you (at least) did an audit, right?

**Comment by waynew** [comment]
I did, we can close this.
