### ISSUE TITLE
Stale bot going rampage

### ISSUE THREAD

**Issue by heini** [saltstack/salt#55913]
### Description of Issue
Today, stale bot closed two of my issues after just one month of inactivity. This is WAY to short! All in all, I needed to reopen ~10+ issues in the last few weeks because of stale bot going rampage on them. Please reconfigure that stupid bot so that it's less annoying or even disable it altogether. Thanks a lot.

**Comment by 4815162342lost** [comment]
I agree, my several issues were closed without resolution.

**Comment by sagetherage** [comment]
Core team will review this week.

**Comment by sagetherage** [comment]
This week we discussed your suggestion of adding time to the stalebot config. This week a PR did get merged that would have prevented all of your issues (except one that was already closed) from the stalebot. We feel at this time the current configuration is sufficient, and you can see this in the yml file here .github/stale.yml in this repo.  

I will note your suggestion in the original ticket that is currently still open for feedback as we move towards iterating on the stalebot configuration plus, other ideas and suggestions. You can find that ticket by searching for the label `Community` and linking it here https://github.com/saltstack/salt/issues/55829 

Thank you for your feedback and please continue to send us more. We want to hear from you! Closing for now.
