### ISSUE TITLE
Failed to deploy salt-minion in salt cloud using a map file 

### ISSUE THREAD

**Issue by vg22** [saltstack/salt#55912]
I am ttrying to set up 3 VMs in Opennebula using salt-cloud. two of them are Windows 2016 servers and 1 is centos7. I am having issues while deploying salt-minion on one of the windows machine. I get this error :

```
+ sudo /usr/bin/salt-cloud -m /etc/salt/cloud.maps.d/12-3set.conf -P -y
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[ERROR   ] Port connection timed out: 900
[ERROR   ] Failed to start Salt on host exchange-vgautam-625
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
appliance-625:
    ----------
    deployed:
        True
    id:
        3444
    image:
        zzAppliance_win2k16_2020
    name:
        appliance-625
    private_ips:
        10.27.8.124
    public_ips:
    size:
        8192
    state:
        3
backend-625:
    ----------
    deployed:
        True
    id:
        3446
    image:
        zzBackend-CentOS7_20191120.raw
    name:
        backend-625
    private_ips:
        10.27.9.26
    public_ips:
    size:
        4096
    state:
        3
exchange-625:
    ----------
    Error:
        ----------
        Not Deployed:
            Failed to start Salt on host exchange-625
    id:
        3445
    image:
        zzExchange_win2k16_2020.raw
    name:
        exchange-625
    private_ips:
        10.27.9.10
    public_ips:
    size:
        16384
    state:
        3

```
This whole process takes almost 25 minutes which is very slow. Most of the time is spent while installing salt-minions on Windows VM and has a different behavior everytime. If i log on to the failed machine i dont see any salt folder or service.

```
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.13.1
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.1.0
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.5.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by xeacott** [comment]
Thanks for the report! Is it both window's boxes that fail? Or is it a single box that is failing to install the minion?

**Comment by vg22** [comment]
@xeacott  I bumped the memory from 8 to 16 GB, it is able to install the minion nowt. But overall installing the minion takes around 20 to 30 minutes( The VMs are up in around 3 4 minutes) when run in parallel which is too much I think.  Is there a better and a more consistent way to do it?

**Comment by vg22** [comment]
Also I wanted to add that there is anoither error which is not reproducible but I thought I'll share here
[```
WARNING ] Failed auth for mech KRB5 (1.2.840.113554.1.2.2): Failed to acquire GSSAPI credential with password: Major (131072): An invalid name was supplied, Minor (2529639136): Configuration file does not specify default realm
[WARNING ] Failed auth for mech KRB5_U2U (1.2.840.113554.1.2.2.3): Mech Type 1.2.840.113554.1.2.2.3 is not yet supported
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[WARNING ] Failed auth for mech KRB5 (1.2.840.113554.1.2.2): Failed to acquire GSSAPI credential with password: Major (131072): An invalid name was supplied, Minor (2529639136): Configuration file does not specify default realm
[WARNING ] Failed auth for mech KRB5_U2U (1.2.840.113554.1.2.2.3): Mech Type 1.2.840.113554.1.2.2.3 is not yet supported
[WARNING ] Failed auth for mech NEGOEX (1.3.6.1.4.1.311.2.2.30): Mech Type 1.3.6.1.4.1.311.2.2.30 is not yet supported
[WARNING ] Failed auth for mech KRB5 (1.2.840.113554.1.2.2): Failed to acquire GSSAPI credential with password: Major (131072): An invalid name was supplied, Minor (2529639136): Configuration file does not specify default realm
[WARNING ] Failed auth for mech KRB5_U2U (1.2.840.113554.1.2.2.3): Mech Type 1.2.840.113554.1.2.2.3 is not yet supported
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 54: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 491, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 356, in run
    self.handle_exception(msg, exc)
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 426, in handle_exception
    msg.format(exc),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 54: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/bin/salt-cloud", line 10, in <module>
    salt_cloud()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 491, in salt_cloud
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 356, in run
    self.handle_exception(msg, exc)
  File "/usr/lib/python2.7/site-packages/salt/cloud/cli.py", line 426, in handle_exception
    msg.format(exc),
UnicodeDecodeError: 'ascii' codec can't decode byte 0xaa in position 54: ordinal not in range(128)
```

**Comment by sagetherage** [comment]
@Akm0d can you help Joe to follow up here, please?
