### ISSUE TITLE
config.get returns pillar values for inexistant config keys

### ISSUE THREAD

**Issue by sblaisot** [saltstack/salt#55919]
### Description of Issue

`salt salt-master config.get item` returns pillar value of `item` if there is no `item` in config.

More specifically, `config.items` contains a `pillar` item containing the whole pillar for salt master. When looking for a specific config item with `config.item`, if item is not found, then `config.item` returns corresponding pillar item

### Setup
master pillar top.sls:
```
base:
  '*':
    - mypillar
```

master pillar mypillar.sls:
```
environment: dev
```

minion config on master server: 
```
master: mymaster
environment: base
```

=> Ok, `config.get environment` returns `base`

but if environment is not set in minion config
minion config on master server: 
```
master: mymaster
```

=> Failed, `config.get environment` returns `dev` (pillar value)

### Steps to Reproduce Issue

- Add a `mykey: myvalue` pair in pillar
- `salt-run saltutil.pillar_refresh` to refresh pillar
- `salt master config.get mykey`

=> it returns `myvalue` even if `mykey` is a pillar key and not directly a config key (note that if `mykey` match an existing config key, then the correct config value is returned)

Note that `salt-run config.get mykey` doen't return anything

### Versions Report
```
# salt -V
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: 0.27.7
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.0 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-5-cloud-amd64
         system: Linux
        version: debian 10.0 
```

**Comment by sblaisot** [comment]
`salt 'master*'  config.get environment omit_pillar=True` works as expected, though.

https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.config.html#salt.modules.config.get sates:

> Attempt to retrieve the named value from the minion config file, pillar, grains or the master config.

so maybe it's intended behaviour and not a real bug.

**Comment by xeacott** [comment]
It does seem to be intended this way as it goes through an order of operations, and then defaults to pillar. But thanks for the report! I'll put this in blocked and label it appropriately and won't close in case you have more questions or concerns. :)

**Comment by sblaisot** [comment]
ok, what confused me is that it appears this behaviour has changed from salt 2017.7 and I didn't expect that.
I added `omit_pillar=True` in my  sls file and it is working back as expected.
So I'm closing this now
Thanks for your comments.
