### ISSUE TITLE
Please create openSUSE Leap 15.1 repo

### ISSUE THREAD

**Issue by udf2457** [saltstack/salt#55924]
As per https://repo.saltstack.com/#suse, it does not appear that SaltStack has an openSUSE Leap 15.1 repo available.

As per https://en.opensuse.org/Lifetime, openSUSE Leap 15.0 is EOL as of 3 December 2019.

Please therefore update openSUSE repo accordingly.

Thanks

**Comment by xeacott** [comment]
This is something we are working on, thanks for addressing this. And we need to do 15.2, too.

**Comment by dmurphy18** [comment]
@udf2457 We have been waiting for SUSE to get back to us with the correct location for SaltStack repo's they build, but should be able to update with current location in the meantime

**Comment by dmurphy18** [comment]
Done, 15.1 will appear with the next point release Neon (Salt 3000) which is immanent (mid-Feb)
Closing this as resolved
