### ISSUE TITLE
Saltstack documentation/recommendation for upgrade existing minions & master to python3

### ISSUE THREAD

**Issue by ssoto2** [saltstack/salt#55925]
### Description of Issue/Question

Looking through the documentation there seems to be no real documentation on steps to upgrade existing minion and masters to python3. Is it expected that a fresh install should be done? 

right now the new rpm for saltstack + py3 does not remove the existing file from bootstrap, and bootstrap will install python3 packages when selected -x python3 but does not update the python version salt is using per --versions-report

It would be nice to know what steps salt prefer users to use. 

### Setup
On RHEL/CENTOS 7 machine with salt-master installed via bootstrap
run yum install from https://repo.saltstack.com/#rhel for python3
view that the python version does not update

On RHEL/CENTOS 7 machine with salt installed via bootstrap
run bootstap with -M and -x python3 

### Versions and Systems
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.1.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

bootstrap:
bootstrap-salt.sh -- Version 2019.11.04

**Comment by sagetherage** [comment]
@ssoto2 labeling this to get the Core team to discuss and decide the recommendation for upgrading and then get it documented. I am placing this on the next discussion date agenda and will follow up.

**Comment by max-arnold** [comment]
@ssoto2 I recently wrote a blog post on this exact topic: https://salt.tips/upgrading-salt-to-python-3/

**Comment by barbaricyawps** [comment]
@max-arnold  and @ssoto2 , I'm reviewing any open issues with the install guide label and I'm wondering if there is still a need for this content. Given that @max-arnold already has a great guide for this, I'm wondering if we still need this issue or if it has gone stale.

How many users are likely to still need to upgrade to Py3? My hunch would be not a lot, but I'm not 100% confident in that assessment. If some users are still impacted, maybe a way to resolve this issue would be to link to Max's article on a relevant topic in the core Salt docs?

**Comment by ssoto2** [comment]
@barbaricyawps nothing is needed from me at this point. with py2 being EOL for years now I would hope most if not everyone is now on py3. So in IMHO, I would agree with your thoughts. If you would like me to close the case i can, pending there is nothing on Salt's end that you all still want to do.

**Comment by barbaricyawps** [comment]
Thanks so much for getting back to me, @ssoto2 . Let's go ahead and close it, then. I appreciate the quick turnaround!
