### ISSUE TITLE
Unicode character "bullet" breaks salt highstate console output

### ISSUE THREAD

**Issue by DagW** [saltstack/salt#55931]
### Description of Issue

When running highstate on a machine with a file.managed change we got a bytestring printed to the terminal instead of the normal highstate output.

```
> salt 'prometheus.dev.com' state.highstate --state-output=changes
b'\x1b[0;1;33mpromethe..............'
```

We found that a unicode character in the change ('\u2022', the bullet character) triggered this. Our workaround is to replace this character in output/highstate.py before its printed.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
Make a file managed append the bullet character '\u2022' to a file so that it shows in the salt state changes.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
```
148 > salt -V
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: 1.13.2
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.28.2
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```

**Comment by xeacott** [comment]
Nice catch, and thanks for the report!

**Comment by twangboy** [comment]
I cannot replicate this on 3006.7. If this is still an issue, please create a new issue with detailed steps to reproduce this issue.
