### ISSUE TITLE
pchanges should be removed from states/reg.py and states/linux_acl.py

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#55934]
This PR removed pchanges from a bunch of other stuff https://github.com/saltstack/salt/pull/49832/files

But when I checked at revision 12c5b33396 it looks like there are a few modules that have new `pchanges`:

```
salt/states/reg.py
388:           'pchanges': {},

salt/states/linux_acl.py
343:           'pchanges': {},
387:                   'pchanges': {},
431:                                'result': None, 'pchanges': changes})
455:                                    'result': None, 'pchanges': changes})
482:                            'result': None, 'pchanges': changes})
```

If I understand correctly, these should be removed, or they will cause issues for `test=True` mode.

**Comment by xeacott** [comment]
We'll keep this ticket to track and make sure that all pchanges get removed. For now, I'll mark as medium severity?

**Comment by sagetherage** [comment]
It might be `Critical` @s0undt3ch when you get time can you confirm Wayne's understanding that it will causes issue for `test=True` or not, pretty please?

**Comment by s0undt3ch** [comment]
Yes Sage, that's also my understanding.
