### ISSUE TITLE
ConfigTestCase.test_datetime_config_validation fails

### ISSUE THREAD

**Issue by bdrung** [saltstack/salt#55936]
### Description of Issue
The ConfigTestCase.test_datetime_config_validation test case fails on Debian unstable:

```
======================================================================
FAIL: test_datetime_config_validation (unit.utils.test_schema.ConfigTestCase)
[CPU:0.0%|MEM:54.9%] 
----------------------------------------------------------------------
Traceback (most recent call last):
  File "tests/unit/utils/test_schema.py", line 848, in test_datetime_config_validation
    format_checker=jsonschema.FormatChecker())
AssertionError: ValidationError not raised

----------------------------------------------------------------------
```

### Setup

Debian unstable with these Python libraries installed:

```
# dpkg-query -W -f='${binary:Package}=${Version}\n' 'python3*' | grep -v '=$'
python3=3.7.5-3
python3-atomicwrites=1.1.5-2
python3-attr=18.2.0-1
python3-distutils=3.8.0-1
python3-importlib-metadata=1.4.0-1
python3-isodate=0.6.0-1
python3-jinja2=2.10.1-1
python3-jsonschema=3.0.2-4
python3-lib2to3=3.8.0-1
python3-markupsafe=1.1.0-1+b2
python3-minimal=3.7.5-3
python3-more-itertools=4.2.0-1
python3-msgpack=0.5.6-3
python3-packaging=19.1-2
python3-pkg-resources=44.0.0-1
python3-pluggy=0.13.0-2
python3-psutil=5.6.7-2
python3-py=1.8.0-1
python3-pyparsing=2.4.2-1
python3-pyrsistent:amd64=0.15.5-1
python3-pytest=4.6.9-1
python3-pytest-helpers-namespace=2019.1.8-1
python3-pytest-tempdir=2016.8.20-1
python3-pytestsalt=2019.6.13-1
python3-setuptools=44.0.0-1
python3-six=1.14.0-2
python3-tornado4=4.5.3-3+b1
python3-wcwidth=0.1.8+dfsg1-3
python3-yaml=5.3-1
python3-zipp=1.0.0-1
python3.7=3.7.6-1+b1
python3.7-minimal=3.7.6-1+b1
```

### Steps to Reproduce Issue

You can use a minimal Debian unstable chroot, checkout the salt git repository and run:
```
apt install python3 python3-jsonschema python3-yaml python3-pytestsalt python3-tornado4 python3-msgpack python3-jinja2 python3-isodate
LC_ALL=en_US.UTF-8 python3 ./tests/runtests.py -v --no-report -n unit.utils.test_schema.ConfigTestCase
```

### Versions Report
salt 2019.2.3

**Comment by xeacott** [comment]
I think this may be an environment issue. I just checked our CI jobs in Jenkins for Debian 9 and 10, which are running Python 3.7.3 this test and the other reported failure are passing. I'm wondering if it's because of Debian Unstable?

**Comment by bdrung** [comment]
Since I can confirm that the test succeeds on Debian 10, this failure is most likely caused by an upgrade Python library. Debian unstable comes with python3-jsonschema 3.0.2-4 for example, compared to 2.6.0-4 in Debian 10.

**Comment by xeacott** [comment]
Yeah I just looked at the reqs in py3.7 and we building with jsonschema==2.6.0 so it wouldn't surprise me if that's what is causing the issue.

**Comment by sagetherage** [comment]
@bdrung apologies on the change of labels, we are working on our internal process and this is merely to separate this ticket and have it assigned so it doesn't get lost. If this is an environment issue if can let us know by commenting and/or closing the ticket, please? We do not have to leave it hanging and we do want to know if it is truly something to fix or not. Thank you!

**Comment by bdrung** [comment]
This issue is still open.

**Comment by bdrung** [comment]
still open

**Comment by xeacott** [comment]
Hi @bdrung would you be able to open a PR against this if this is still an issue? I saw your addition of skipping the test and we can discuss that change in a PR.

**Comment by bdrung** [comment]
Tested the master branch and this issue is fixed:
```python
    @skipIf(HAS_RFC3987 is False, "The 'rfc3987' library is missing")
```

**Comment by bdrung** [comment]
I probably made a mistake while testing. This issue is still present.
