### ISSUE TITLE
a question of change hostname of one minion 

### ISSUE THREAD

**Issue by ludi1981** [saltstack/salt#55930]
### Description of Issue
I have a server A for example, the IP address is 1.1.1.1. I also have a server B , the IP address is 2.2.2.2

Because server A was expired, it was replaced by B. So, we exchanged the IP and hostname. So now, the server 'B' is named 'A', and IP is 1.1.1.1; 'A' is closed( power off). 

Now, the problem is in the salt master. The 1.1.1.1 and 2.2.2.2 was pointed to the new A server. We tried to remove minion key by salt-key. The minon key will be added by a few miniums. 
We also changed minion_id in server 'A'.

So, my question is: can I remove 2.2.2.2 of the previous one from the salt master in this situation?

I'm not familar with salt. Please correct me if my description is incorrect. Thanks.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
[root@config-master-node ~]# salt --versions-report
Salt Version:
           Salt: 2016.11.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.4.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.20.0
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.0.1
   pycryptodome: 3.4.3
         pygit2: 0.20.3
         Python: 2.6.6 (r266:84292, May 22 2015, 08:34:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5
 
System Versions:
           dist: redhat 6.8 Santiago
        machine: x86_64
        release: 2.6.32-642.el6.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.8 Santiago

**Comment by xeacott** [comment]
It seems like you have it covered - as long as the keys were removed, and in /etc/salt/minion the host still points to the IP of your master and the two (meaning salt master and salt minion) can communicate then should be fine.

**Comment by ludi1981** [comment]
> It seems like you have it covered - as long as the keys were removed, and in /etc/salt/minion the host still points to the IP of your master and the two (meaning salt master and salt minion) can communicate then should be fine.

Thank you for help. Yes, at the first, I told my colleagues the same answer. But, his script want to use the IP and hostname to check someting by salt. In this case, his script will check the IP, '2.2.2.2' and be broken because of the incorrect hostname and IP relationship.  This is why we tried to remove the older item.

Any suggestion?
