### ISSUE TITLE
Salt 3000.0rc2 cannot be installed on MacOS Catalina

### ISSUE THREAD

**Issue by vernondcole** [saltstack/salt#55951]
### Description of Issue

Attempting to install Salt using the provided package fails.

### Steps to Reproduce Issue

1) Download http://repo.saltstack.com/salt_rc/osx/salt-3000.0rc2-py3-x86_64.pkg

2) Click on the package.

<img width="448" alt="image" src="https://user-images.githubusercontent.com/628485/73019106-3044b800-3de0-11ea-9973-ebbf16323b71.png">

### Versions Report

System Versions:
           dist:   
         locale: UTF-8
        machine: x86_64
        release: 19.2.0
         system: Darwin
        version: 10.15.2 x86_64

**Comment by xeacott** [comment]
Thanks for bringing this up. Are you able to go into the security control panel and click "open anyways"?

**Comment by vernondcole** [comment]
Yes, that works for me. I had totally forgotten about that "feature" since
I only develop software ON rather than FOR MacOS.

**Comment by xeacott** [comment]
Glad that worked!
