### ISSUE TITLE
New Office 2016 administrative templates not picked up by salt-minion but can be seen in gpedit.msc

### ISSUE THREAD

**Issue by jpsv** [saltstack/salt#55987]
### Description of Issue
Trying to prevent Bing from changing search engines in Firefox/Chrome, and keep getting a not found error.

I can see the policy setting on the minion under gpedit.msc so why can't Saltstack?

### Setup
Windows minion: Windows 10 Pro 17763.973

State file that gets the same error:
```
{% if grains['osfullname'] == 'Microsoft Windows 10 Pro' %}
Prevent Bing search engine override:
  lgpo.set:
    - name: "Microsoft Office 2016 (Machine)\\Updates\\Don\'t install extension for Microsoft Search in Bing that makes Bing the default search engine"
    - setting: Enabled
    - policy_class: Machine
{% endif %}
```
```
----------
          ID: Prevent Bing search engine override
    Function: lgpo.set
        Name: Microsoft Office 2016 (Machine)\Updates\Don't install extension for Microsoft Search in Bing that makes Bing the default search engine
      Result: False
     Comment: Unable to find Machine policy Don't install extension for Microsoft Search in Bing that makes Bing the default search engine
     Started: 10:00:14.148313
    Duration: 1862.754 ms
```
### Steps to Reproduce Issue
Module command:
`sudo salt DESKTOP lgpo.set_computer_policy "Microsoft Office 2016 (Machine)\Updates\Don't install extension for Microsoft Search in Bing that makes Bing the default search engine" Enabled`
Minion log:
`2020-01-27 10:06:22,046 [salt.minion      :1721][ERROR   ][10464] Problem executing 'lgpo.set_computer_policy': Unable to find Machine policy Don't install extension for Microsoft Search in Bing that makes Bing the default search engine`

### Versions Report
Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.1
          ioflo: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.11
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.15.18-11-pve
         system: Linux
        version: debian 9.11

**Comment by xeacott** [comment]
Thanks for the report! I'll triage this issue by end of day and see what's up with this. Chances are it's just a very slight change in the `name` param that is needed.

**Comment by xeacott** [comment]
Further update on this... so posting the link here in case another engg grabs this but basically.. https://docs.microsoft.com/en-us/deployoffice/microsoft-search-bing#how-to-exclude-the-extension-for-microsoft-search-in-bing-from-being-installed

Upon downloading the .admx/adml files and dropping them into `C:\\Windows\\PolicyDefinitions`, the policy becomes available is is located in `Computer Configuration\Policies\Administrative Templates\Microsoft Office 2016 (Machine)\Updates`

However the name of policy includes a Microsoft's SmartQuote, which poses a problem that has already been addressed in our Neon release. So in the policy name, `Don't` actually shows up as `Don\u2018t`, otherwise the lgpo module won't _actually_ find the policy. This is what we're expecting the issue to be, but I'll confirm this. :)

**Comment by jpsv** [comment]
Found a similar issue with the same smartquote that was closed for staleness in 2017, https://github.com/saltstack/salt/issues/40653

Although it would make sense for an earlier error I got with a different state edit, `2020-01-27 09:11:36,004 [salt.state       :3487][CRITICAL][22880] Rendering SLS 'base:win.policies.prevent_bing_override' failed: did not find expected hexdecimal number`

**Comment by jpsv** [comment]
Not sure if this is related, but I also get a `Not connected` response when using `lgpo.get return_not_configured=true`

HOWEVER I got it to work.... only because the description had the same quote, this thing: ’

It won't work in the module,  but it will work in a state file.

It's wasn't **\u2018**, but rather **\u2019**, the right-quote, not left.

**Comment by xeacott** [comment]
Ah, cool glad you got it to work with the state. Would you be able to post the .sls file you used?

**Comment by jpsv** [comment]
```
{% if grains['osfullname'] == 'Microsoft Windows 10 Pro' %}
Prevent Bing search engine override:
  lgpo.set:
    - name: "Microsoft Office 2016 (Machine)\\Updates\\Don’t install extension for Microsoft Search in Bing that makes Bing the default search engine"
    - setting: Enabled
    - policy_class: Machine
{% endif %}
```

**Comment by xeacott** [comment]
Thanks. I'll leave this ticket open in case there's other issues but @twangboy has done a lot of awesome work lately with LGPO and this may be resolved with Neon.

**Comment by xeacott** [comment]
Closing this for now since it sounds like its been address.
