### ISSUE TITLE
Etcd data cache performance with many minions

### ISSUE THREAD

**Issue by malletp** [saltstack/salt#55988]
### Description of Issue
When using etcd minion data cache with a lot of minions, filtering minions with grains/pillar is very slow with many minions.

### Setup
Master with more than 100 minions. Etcd cache configured.

### Steps to Reproduce Issue
Compare time required for filter minions by grains with etcd cache enable and without etcd cache.
To retrieve salt grains, one call to etcd is done per minion. This step takes a lot of time with many minions.
A fix can be to retrieve all minions data in one call to etcd.

### Versions Report
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.4
        libnacl: Not Installed
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.9.1
         pygit2: 0.26.4
         Python: 2.7.5 (default, Jun 11 2019, 14:33:56)
   python-gnupg: 0.4.4
         PyYAML: 3.10
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.6 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.7.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.6 Maipo

**Comment by whytewolf** [comment]
So, I know there was a lot of heavy lifting of most of the cache modules including etcd. I'm going to close this ticket as this ticket might have got missed when those issues closed, however if someone tests and still has this problem on 3006.x please open a new ticket with full details about the issue.
