### ISSUE TITLE
I can not get a custom returner working for salt master_job_cache

### ISSUE THREAD

**Issue by ihakh** [saltstack/salt#56025]
I have customized the pgjsonb returner and renamed it to something like: mypgjsonb

I have putted it in this folders but neither of them working:

- /srv/_returners/
- /srv/salt/_returners/
- /srv/salt-master/_returners/

in master config I have :
master_job_cache: mypgjsonb

and I get these in master log with -ldebug:
[DEBUG   ] Could not LazyLoad mypgjsonb.clean_old_jobs: 'mypgjsonb.clean_old_jobs' is not available.
and:
[DEBUG   ] Could not LazyLoad mypgjsonb.prep_jid: 'mypgjsonb.prep_jid' is not available.
[ERROR   ] Failed to allocate a jid. The requested returner 'mypgjsonb' could not be loaded.
[DEBUG   ] Sending event: tag = {u'error': u"Failed to allocate a jid. The requested returner 'mypgjsonb' could not be loaded."};

where I should place it so the salt-master can see it?

**Comment by ihakh** [comment]
Please someone response...

**Comment by whytewolf** [comment]
@ihakh 

Location is dependent on your `file_roots` or other fileserver based settings.The default would be `/srv/salt/_returners/`. the sync commands take the file from `salt://_returners` 

After that, you need to make sure you run `salt-run saltutil.sync_all` or `salt-run saltutil.sync_returners` This will sync it to the master. 

Even after that it still takes a restart of the master sometimes.
