### ISSUE TITLE
[Docs] Deprecation of salt-unity, need to remove the doc references

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#56055]
### Description of Issue
Salt-unity was deprecated, but the docs still exist

Docs: https://docs.saltstack.com/en/latest/ref/cli/salt-unity.html

**Comment by Ch3LL** [comment]
@sagetherage i dont think this has ben properly deprecated has it? We would need to add a note to Sodium release that it will be deprecated in two releases and log a warning if someone is using it.

**Comment by sagetherage** [comment]
I did not write this very well, @s0undt3ch if you can help with this one, please for Sodium. Should be very small in scope.

**Comment by s0undt3ch** [comment]
I believe the only thing to do is document it on the release notes that it **was** removed in Neon.
And sure, I can do that.

**Comment by sagetherage** [comment]
@saltstack/docs-working-group @barbaricyawps the docs still exist for salt-unity which has been deprecated from the code base docs can be seen here: https://docs.saltstack.com/en/latest/ref/cli/salt-unity.html

**Comment by ScriptAutomate** [comment]
Running the following:

```bash
# bash shell
# From root of repo
grep -R "salt-unity" | \
    egrep -v "Binary|/_build/" | \
    cut -d":" -f1 | \
    sort | \
    uniq
```

Shows that all of the following files in `master` mention `salt-unity`:

```
doc/conf.py
doc/man/salt-unity.1
doc/ref/cli/index.rst
doc/ref/cli/salt-unity.rst
pkg/rpm/salt.spec
pkg/suse/salt.spec
pkg/windows/build_pkg.bat
setup.py
tests/pkg/rpm/salt.spec
tests/unit/setup/test_man.py
```

Here are some more details on lines where they are referenced:

```bash
# bash shell
grep -n -R "salt-unity" | \
    egrep -v "Binary|/_build/" | \
    cut -d":" -f1,2
```

```
pkg/windows/build_pkg.bat:587
pkg/windows/build_pkg.bat:588
pkg/suse/salt.spec:775
pkg/suse/salt.spec:776
pkg/rpm/salt.spec:258
pkg/rpm/salt.spec:264
setup.py:894
setup.py:1144
setup.py:1164
setup.py:1209
setup.py:1228
setup.py:1255
setup.py:1273
doc/conf.py:553
doc/ref/cli/salt-unity.rst:2
doc/ref/cli/salt-unity.rst:12
doc/ref/cli/salt-unity.rst:23
doc/ref/cli/index.rst:83
doc/ref/cli/index.rst:87
doc/man/salt-unity.1:5
tests/pkg/rpm/salt.spec:285
tests/pkg/rpm/salt.spec:291
tests/unit/setup/test_man.py:40
```

To generate markdown formatted GitHub links to the lines where these are found, I ran the following:

```bash
grep -n -R "salt-unity" | \
    egrep -v "Binary|/_build/" | \
    cut -d":" -f1,2 | \
    sed 's:\::#L:g' | \
    sed 's:^:- https\://github.com/saltstack/salt/blob/master/:g'
```

This generated the following markdown output:

- https://github.com/saltstack/salt/blob/master/pkg/windows/build_pkg.bat#L587
- https://github.com/saltstack/salt/blob/master/pkg/windows/build_pkg.bat#L588
- https://github.com/saltstack/salt/blob/master/pkg/suse/salt.spec#L775
- https://github.com/saltstack/salt/blob/master/pkg/suse/salt.spec#L776
- https://github.com/saltstack/salt/blob/master/pkg/rpm/salt.spec#L258
- https://github.com/saltstack/salt/blob/master/pkg/rpm/salt.spec#L264
- https://github.com/saltstack/salt/blob/master/setup.py#L894
- https://github.com/saltstack/salt/blob/master/setup.py#L1144
- https://github.com/saltstack/salt/blob/master/setup.py#L1164
- https://github.com/saltstack/salt/blob/master/setup.py#L1209
- https://github.com/saltstack/salt/blob/master/setup.py#L1228
- https://github.com/saltstack/salt/blob/master/setup.py#L1255
- https://github.com/saltstack/salt/blob/master/setup.py#L1273
- https://github.com/saltstack/salt/blob/master/doc/conf.py#L553
- https://github.com/saltstack/salt/blob/master/doc/ref/cli/salt-unity.rst#L2
- https://github.com/saltstack/salt/blob/master/doc/ref/cli/salt-unity.rst#L12
- https://github.com/saltstack/salt/blob/master/doc/ref/cli/salt-unity.rst#L23
- https://github.com/saltstack/salt/blob/master/doc/ref/cli/index.rst#L83
- https://github.com/saltstack/salt/blob/master/doc/ref/cli/index.rst#L87
- https://github.com/saltstack/salt/blob/master/doc/man/salt-unity.1#L5
- https://github.com/saltstack/salt/blob/master/tests/pkg/rpm/salt.spec#L285
- https://github.com/saltstack/salt/blob/master/tests/pkg/rpm/salt.spec#L291
- https://github.com/saltstack/salt/blob/master/tests/unit/setup/test_man.py#L40

https://github.com/saltstack/salt/blob/master/tests/unit/setup/test_man.py#L40

https://github.com/saltstack/salt/blob/84987d151522ca36c76f0e15944e95b2b5f9ef5e/tests/unit/setup/test_man.py#L40

From a docs perspective, would we delete [doc/ref/cli/salt-unity.rst](https://github.com/saltstack/salt/blob/master/doc/ref/cli/salt-unity.rst) and remove the `salt-unity` index mention from [doc/ref/cli/index.rst](https://github.com/saltstack/salt/blob/master/doc/ref/cli/index.rst)? I'm wanting to get a good idea for what is in doc scope from this ticket, and what else can be cleaned up relating to `salt-unity` deprecation.
