### ISSUE TITLE
master_roots

### ISSUE THREAD

**Issue by nee2c** [saltstack/salt#56053]
### master_roots
I have started to refactor our master and I started with updating the master from 2019.2.0 to 2019.2.3(py2).  Then have uncommented this line in the config and I get this warning message.
```
[WARNING ] Config option 'master_roots' with value /srv/salt-master has an invalid type of unicode, a dict is required for this option
```

### Documentation
I have found the documentation to be inaccurate and unclear about this option
https://docs.saltstack.com/en/latest/ref/configuration/master.html#master-roots

We are planning to only use gitfs and was wounding if it is not an idea to have this opting supported by gitfs aswell.

**Comment by dhiltonp** [comment]
Yeah, the structure of the option has the same structure as `file_roots` and `pillar_roots`:

```yaml
master_roots:
  base:
    - /srv/salt-master
```

Thanks for the catch!

**Comment by dhiltonp** [comment]
Feel free to open another issue about gitfs if `gitfs_root` or `gitfs_base` aren't enough for your use case :)

**Comment by sagetherage** [comment]
merged and will be released in Sodium
