### ISSUE TITLE
Creating instances with static IP fails.

### ISSUE THREAD

**Issue by mariusvw** [saltstack/salt#56056]
### Description of Issue

Creating instances with static IP fails.

### Setup

Configure salt-cloud according to the documentation of 2019.2.3

### Steps to Reproduce Issue

```
salt cloud -p profile vmname
```

### Versions Report

```
Salt Version:
           Salt: 2019.2.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Nov  7 2019, 10:07:09)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-74-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by dhiltonp** [comment]
Thanks for your contribution!

Can you share what version of libcloud you have installed?

At a first look this seems rather odd, given that `__create_orget_address` returns a [GCEAddress](https://libcloud.readthedocs.io/en/stable/_modules/libcloud/compute/drivers/gce.html#GCEAddress) from libcloud, and then passes it back to [libcloud's gce create_node](https://libcloud.readthedocs.io/en/stable/compute/drivers/gce.html#libcloud.compute.drivers.gce.GCENodeDriver.create_node), which accepts `external_ip` as a `GCEAddress`, `str` or `None` and doesn't mention dict.
