### ISSUE TITLE
saltstack 2019 does not come with python-ldap 

### ISSUE THREAD

**Issue by dtmateojr** [saltstack/salt#56066]
### Description of Issue

LDAP authentication does not work because python-ldap is not bundled with the 2019.2.3 RPMs.

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

external_auth:
    ldap:
       someuser:
            - .*

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

Access the salt-api using eauth=ldap

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

Salt 2019.2.3
on EL6

### Fix:

pip2.7 install python-ldap

**Comment by dhiltonp** [comment]
In general, we're moving towards relying on system packages vs. bundling everything with salt - and we don't want to pull in all possible requirements for every feature we support!

This is a little tricky with RHEL6 as they still package Python 2.6. We ship with 2.7 as a result and so you've got to use pip2.7 (as you've learned).

Thanks for the report :)
