### ISSUE TITLE
file.managed is taking newlines and replacing them with spaces from -contents

### ISSUE THREAD

**Issue by jrdemasi** [saltstack/salt#56074]
### Description of Issue

When file.managed is passed a string with linebreaks denoted as \n in them, it replaces them with spaces instead of newlines
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
I'm setting a jinja variable from a vault module call and trying to use it to put a cert in a file, like so:
```
{%- set pki_data = salt.vault.write_secret("pki_consul/issue/consul", common_name=grains['fqdn']) -%}

install-ssl-certs:
  file.managed:
    - name: /etc/my/certs/{{ grains['fqdn'] }}.crt
    - contents: 
      - "{{ pki_data['certificate'] }}"
    - user: root
    - group: root
```
### Steps to Reproduce Issue
Get data and save to a variable from a module such as vault.write_secret (in my example) and pass it to file.managed.  If you print the jinja var (`{%- do salt.log.error(pki_data) -%}
`) it will look like this: 
```
'certificate': '-----BEGIN CERTIFICATE-----/nMIICnDCCAkKgAwIBAgIQBl6V77mvpeMmaWfqcSZICDAKBggqhkjOPQQDAjCBuTEL/nMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2Nv/nMRowGAYDVQQJExExMDEgU2Vjb25kIFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAV/nBgNVBAoTDkhhc2hpQ29ycCBJbmMuMUAwPgYDVQQDEzdDb25zdWwgQWdlbnQgQ0Eg/nMTMyMDY5MjM2MDg2OTYxNzI1NTQ5NjE0MDY0OTU0MzAwODIxNTUwMB4XDTIwMDIw/nNTE5MDEyNVoXDTIxMDIwNDE5MDEyNVowHDEaMBgGA1UEAxMRc2VydmVyLmRjMS5j/nb25zdWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARTCCuVwD5jG/tQxsQhgNlM/nkgkyPsVZkoav7AGGqS1PNZgf/8/rXswofIpYRIZBQUqkWtdK5eO3h+E9jY8o85DR/no4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB/nBQUHAwIwDAYDVR0TAQH/BAIwADApBgNVHQ4EIgQgfwdlagQqxvQBRgYDvtXAn6xG/nPyPeUZYCN/3ZKgw9swwwKwYDVR0jBCQwIoAgDFclnplR1y0JYVlwvivZUlGLjjWF/nbOrY6Q9MgTm+p1MwLQYDVR0RBCYwJIIRc2VydmVyLmRjMS5jb25zdWyCCWxvY2Fs/naG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiBa7g+JXPWyxcpf1GW7wJhQC1Vy/n7LYqtVn887W4Q2+KiwIhAL8bq4iB3JwcwsFo6KQ5GQOl/m0inwiQuHCOschg0tPS/n-----END CERTIFICATE-----/n'
```
However when the file gets written via file.managed, newlines are replaced with spaces:
```
-----BEGIN CERTIFICATE----- MIICnDCCAkKgAwIBAgIQBl6V77mvpeMmaWfqcSZICDAKBggqhkjOPQQDAjCBuTEL MAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2Nv MRowGAYDVQQJExExMDEgU2Vjb25kIFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAV BgNVBAoTDkhhc2hpQ29ycCBJbmMuMUAwPgYDVQQDEzdDb25zdWwgQWdlbnQgQ0Eg MTMyMDY5MjM2MDg2OTYxNzI1NTQ5NjE0MDY0OTU0MzAwODIxNTUwMB4XDTIwMDIw NTE5MDEyNVoXDTIxMDIwNDE5MDEyNVowHDEaMBgGA1UEAxMRc2VydmVyLmRjMS5j b25zdWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARTCCuVwD5jG/tQxsQhgNlM kgkyPsVZkoav7AGGqS1PNZgf/8/rXswofIpYRIZBQUqkWtdK5eO3h+E9jY8o85DR o4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB BQUHAwIwDAYDVR0TAQH/BAIwADApBgNVHQ4EIgQgfwdlagQqxvQBRgYDvtXAn6xG PyPeUZYCN/3ZKgw9swwwKwYDVR0jBCQwIoAgDFclnplR1y0JYVlwvivZUlGLjjWF bOrY6Q9MgTm+p1MwLQYDVR0RBCYwJIIRc2VydmVyLmRjMS5jb25zdWyCCWxvY2Fs aG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiBa7g+JXPWyxcpf1GW7wJhQC1Vy 7LYqtVn887W4Q2+KiwIhAL8bq4iB3JwcwsFo6KQ5GQOl/m0inwiQuHCOschg0tPS -----END CERTIFICATE-----
```
### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Oct 11 2019, 15:04:54)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.2
            ZMQ: 4.3.2
 
System Versions:
           dist: redhat 8.1 Ootpa
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-147.3.1.el8_1.x86_64
         system: Linux
        version: Red Hat Enterprise Linux 8.1 Ootpa

**Comment by dhiltonp** [comment]
In your example the escape characters are backwards - they should be `\n`, not `/n`.

Can you confirm that it is broken with `\n`?

`'certificate': '-----BEGIN CERTIFICATE-----/nMIICnDCCAkKgAwIBAgIQBl6V77mvpeMmaWfqcSZICDAKBggqhkjOPQQDAjCBuTEL/nMAkGA1UEBhMCVVMxCzAJBgNVBAgTAkNBMRYwFAYDVQQHEw1TYW4gRnJhbmNpc2Nv/nMRowGAYDVQQJExExMDEgU2Vjb25kIFN0cmVldDEOMAwGA1UEERMFOTQxMDUxFzAV/nBgNVBAoTDkhhc2hpQ29ycCBJbmMuMUAwPgYDVQQDEzdDb25zdWwgQWdlbnQgQ0Eg/nMTMyMDY5MjM2MDg2OTYxNzI1NTQ5NjE0MDY0OTU0MzAwODIxNTUwMB4XDTIwMDIw/nNTE5MDEyNVoXDTIxMDIwNDE5MDEyNVowHDEaMBgGA1UEAxMRc2VydmVyLmRjMS5j/nb25zdWwwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAARTCCuVwD5jG/tQxsQhgNlM/nkgkyPsVZkoav7AGGqS1PNZgf/8/rXswofIpYRIZBQUqkWtdK5eO3h+E9jY8o85DR/no4HHMIHEMA4GA1UdDwEB/wQEAwIFoDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYB/nBQUHAwIwDAYDVR0TAQH/BAIwADApBgNVHQ4EIgQgfwdlagQqxvQBRgYDvtXAn6xG/nPyPeUZYCN/3ZKgw9swwwKwYDVR0jBCQwIoAgDFclnplR1y0JYVlwvivZUlGLjjWF/nbOrY6Q9MgTm+p1MwLQYDVR0RBCYwJIIRc2VydmVyLmRjMS5jb25zdWyCCWxvY2Fs/naG9zdIcEfwAAATAKBggqhkjOPQQDAgNIADBFAiBa7g+JXPWyxcpf1GW7wJhQC1Vy/n7LYqtVn887W4Q2+KiwIhAL8bq4iB3JwcwsFo6KQ5GQOl/m0inwiQuHCOschg0tPS/n-----END CERTIFICATE-----/n'
`

**Comment by jrdemasi** [comment]
Oops - that's my snafu in a find/replace when I was scrubbing sensitive
data and making up a fake cert for the GH issue.  I can confirm that in
production, it's the right way (\n).  I apologize for the error.

**Comment by OrangeDog** [comment]
Probably not a bug. That's just how YAML syntax works.
If you want to preserve newlines you need to use e.g. `contents: |`.

**Comment by jrdemasi** [comment]
Yeah, but it isn't actually newlines, just the escape character which gets
replaced with spaces. Why would it get replaced at all?

**Comment by OrangeDog** [comment]
YAML expands escape sequences in quoted strings.

**Comment by dhiltonp** [comment]
Thanks for the report @jrdemasi, and thanks for chiming in @OrangeDog :)
