### ISSUE TITLE
`order: last` is not respected if another state requires

### ISSUE THREAD

**Issue by mlasevich** [saltstack/salt#56076]
### Description of Issue
When determining order of execution, if a state has `order: last` in it (and i suspect any order directive), it is ignored if there is a `requires` involved. 

My expectation is that if I specify order explicitly, any relative dependencies are  relative to that order - but instead all relative dependencies are treated as absolute  and order is only used if there are no relative dependencies

I realize this may be inherent in the way this is implemented, but it results in very unpredictable behavior when used at scale. :-/

### Setup
Here is a simple state demonstrating this:
```
a:
  test.succeed_with_changes:
    - order: last
b:
  test.succeed_with_changes:
    - require:
      - test: a
c:
  test.succeed_with_changes: []
```

I would expect the order to be `c` -> `a` -> `b` but instead we get `a` -> `b` -> `c`

### Steps to Reproduce Issue

see above state

### Versions Report

Confirmed in multiple versions including:
```
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-150-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```

**Comment by dhiltonp** [comment]
You are correct. Ordering is separate from the requisite system.

Hopefully these links are enlightening :)

https://docs.saltstack.com/en/master/ref/states/ordering.html#the-order-option
https://docs.saltstack.com/en/master/ref/states/requisites.html#requisite-overview

**Comment by mlasevich** [comment]
Ok,  understand this, and this is the problem - there are two independent systems here for doing same job or controlling the order of the states in a different, conflicting manor, resulting in unexpected/unstable behavior, esp. when used in a larger organization where you cannot read every single state to understand and maintain every relationship manually  :-/ This is a serious problem.

**Comment by waynew** [comment]
@mlasevich It may be unexpected behavior, but it's not unstable, or even non-deterministic. Additionally, running `test=True` will also verify the order.

Requisites, excludes, and ordering *always* have the potential to change the ordering of your states. The only way to get around that is to forbid ordering or requisites. But if you allow the ability to use them, eventually you'll run into a situation where what you expected to happen, won't.

Perhaps `listen/listen_in` https://docs.saltstack.com/en/master/ref/states/requisites.html#id2 would be more appropriate for your needs?

**Comment by mlasevich** [comment]
> Requisites, excludes, and ordering always have the potential to change the ordering of your states.

That is the expectation, and the desired effect, but the order change should be logical, which it is not. The same documentation says that the point of `order:last` is to be able to order from the end, which is flat out not possible - making `order: last` directive largely useless if you want to use it to control ordering with relation to other states

I get it now that this behavior IS documented, but it is still not really what is desired or expected. I want to be able to do what `order: last` promised. I get and expect that if something is requiring it, it would go after it  - but why arbitrary move it into the front of everything else is beyond me.
