### ISSUE TITLE
salt.modules.mssql Documentation Omits Minion Config  

### ISSUE THREAD

**Issue by batgranny** [saltstack/salt#56088]
### Description of Issue
https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.mssql.html 
The mssql module documentation neglects to mention explicitly that the pymssql python module should be installed on both the Salt master and the minion.

**Comment by dhiltonp** [comment]
Yeah, the pymssql Python module will need to be installed on the system where the salt mssql module is being used.

I can see the confusion. 

The rest of the documentation is written in the same way - specifying dependencies, but not saying *where* they need to be installed.

When attempting to run a salt module without having the necessary python module you should have received a pretty helpful error message. Did you find the error message easy to understand?

If not, maybe we could improve that...

**Comment by batgranny** [comment]
The error message was along the lines of "The function mssql.whatever is not available" which wasn't hugely helpful.  It was only really a guess that it might be the module on the minion side that led to the resolution

**Comment by sagetherage** [comment]
@saltstack/docs-working-group

**Comment by sagetherage** [comment]
@batgranny can you give us the steps and exact error message? Then we can take a look at updating that if it wasn't a helpful error message.
