### ISSUE TITLE
[Feature request] add lvm pvresize and lvextend to linux_lvm

### ISSUE THREAD

**Issue by MrDiba** [saltstack/salt#56089]
### Description of Issue
I would like to resize lvm physical volumes and extend the logical volumes, but both of the functions are not implemented in the linux_lvm module.

https://docs.saltstack.com/en/master/ref/modules/all/salt.modules.linux_lvm.html

**Comment by dhiltonp** [comment]
Thanks!

For now, I suggest you use a shell command.

We also accept code contributions - maybe you could improve the module and share your changes!

**Comment by doesitblend** [comment]
ZD-4605

**Comment by piterpunk** [comment]
@sagetherage , I guess this one can be closed. I included this feature in #58133 , which is now merged.
