### ISSUE TITLE
The salt-api use nodegroup to targeting，but return {}

### ISSUE THREAD

**Issue by maining123** [saltstack/salt#56096]
### Description of Issue

/etc/salt/master
```
interface: 0.0.0.0

external_auth:
  pam:
    saltapi:
      - .*
      - '@wheel'
      - '@runner'
      - '@jobs'

rest_cherrypy:
  port: 8000
  ssl_crt: /etc/pki/tls/certs/localhost.crt
  ssl_key: /etc/pki/tls/certs/localhost.key
  debug: True
file_recv: True

include: /data/projects/soms/saltconfig/*.conf

nodegroup.conf
nodegroups:
  test:
    - 10.206.132.160
    - webserver
```

### Setup
```
salt -N test test.ping
10.206.132.160:
    True
webserver:
    True
curl -k https://localhost:8000/ -H "Accept: application/x-yaml" -H "X-Auth-Token: 16c7afb97b35103b00acb477a72fc7241105ea9b" -d client='local' -d tgt='test' -d expr_form='nodegroup' -d fun='test.ping'
return:
- {}
```
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt 2019.2.3 (Fluorine)
salt-api 2019.2.3 (Fluorine)

**Comment by DmitryKuzmenko** [comment]
@maining123 could you please provide the corresponding debug log and full output of the `--versions-report`?
