### ISSUE TITLE
salt-cloud not working with azure and unmanaged disk

### ISSUE THREAD

**Issue by tkykm** [saltstack/salt#56091]
### Description of Issue

The azurearm module fail to create a unmanaged disk.
Because it attempt to create VirtualHardDisk instance with string arugment, but it should pass it as keyword argument like VirtualHardDisk(uri='https://~~~')
https://github.com/saltstack/salt/blob/master/salt/cloud/clouds/azurearm.py#L1162

### Setup
stable 2019.2.2 python3

### Steps to Reproduce Issue
set `vhd: unmanaged` to profile or mapfile and then deploy

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 67, in _call
    ret = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 2294, in create_multiprocessing
    local_master=parallel_data['local_master']
  File "/usr/lib/python3.6/site-packages/salt/cloud/__init__.py", line 1253, in create
    output = self.clouds[func](vm_)
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/azurearm.py", line 1404, in create
    vm_request = request_instance(vm_=vm_)
  File "/usr/lib/python3.6/site-packages/salt/cloud/clouds/azurearm.py", line 1167, in request_instance
    volume['lun'],
TypeError: __init__() takes 1 positional argument but 2 were given
```

### Versions Report
I've used this pip modules: 
https://raw.githubusercontent.com/saltstack/salt/v2019.2.2/requirements/static/py3.6/cloud.txt

Salt Version:
           Salt: 2019.2.2

Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 3.10.0-514.10.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

**Comment by dhiltonp** [comment]
It looks like there is a change in behavior between the azure Python2 and Python3 APIs.

[The Python 3 API no longer accepts positional args - at least for VirtualDisk](
https://github.com/Azure/azure-sdk-for-python/blob/3a7c58c4ecdf3b3c389fd5764c7329a0b06600ea/sdk/compute/azure-mgmt-vmwarecloudsimple/azure/mgmt/vmwarecloudsimple/models/_models_py3.py#L1158).

Changing all API args to named arguments should fix this incompatibility. Adding tests would be good, too.
