### ISSUE TITLE
Multiple tests reports "cannot allocate memory" on centos6 py2 master builds

### ISSUE THREAD

**Issue by DmitryKuzmenko** [saltstack/salt#56109]
### Description of Issue
https://jenkinsci.saltstack.com/job/pr-centos6-py2/job/master/623/testReport/junit/

```
[Errno 12] Cannot allocate memory
```

**Comment by s0undt3ch** [comment]
Hotfix in https://github.com/saltstack/sre-jenkins/pull/261
