### ISSUE TITLE
docs clarification for pillar_opts configuration option

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#56116]
### Description of Issue
This [salt doc](https://docs.saltstack.com/en/latest/topics/tutorials/pillar.html#setting-up-pillar) has a section about the `pillar_opts` option for sharing the master config file as a pillar for the minions to see. It doesnt make it clear that there are actually two `pillar_opts` to be enabled/disabled. One is on the master and one is on the minion.

### relevant section
```
By default, the contents of the master configuration
file are not loaded into pillar for all minions. This 
default is stored in the pillar_opts setting, which 
defaults to False.

The contents of the master configuration file can 
be made available to minion pillar files. This makes 
global configuration of services and systems very 
easy, but note that this may not be desired or 
appropriate if sensitive data is stored in the master's 
configuration file. To enable the master configuration 
file to be available to a minion's pillar files, set 
pillar_opts to True in the minion configuration file.
```

### Recommended Solution
Just a clarification to explicitly state what `pillar_opts` toggle for master and `pillar_opts` toggle for minions accomplishes.

***
- beginner friendly
- issue for docs-working group
- single person task

**Comment by ScriptAutomate** [comment]
Other related documentation that needs review, and potential revision:

- [config execution module: config.get](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.config.html#salt.modules.config.get)
- [Configuration: master](https://docs.saltstack.com/en/master/ref/configuration/master.html)
- [Configuration: minion](https://docs.saltstack.com/en/master/ref/configuration/master.html)

It may be wise to use the `.. warning::` admonition for the messages around security risks, such as with this portion from the initial comment in this issue:

> The contents of the master configuration file can 
be made available to minion pillar files. This makes 
global configuration of services and systems very 
easy, but note that this may not be desired or 
appropriate if sensitive data is stored in the master's 
configuration file. To enable the master configuration 
file to be available to a minion's pillar files, set 
pillar_opts to True in the minion configuration file.

Other files that show up when grepping that may need to also have the same review from a docs and docstrings/comments perspective:

```bash
# From root of salt repo
grep -R 'pillar_opts' | \
    egrep -v "Binary|_build|doc\/man\/|doc\/topics\/releases\/|tests\/|doc\/man" | \
    cut -d':' -f1 | \
    uniq
```
```
salt/modules/nacl.py
salt/modules/config.py
salt/modules/dockermod.py
salt/modules/etcd_mod.py
salt/modules/twilio_notify.py
salt/pillar/__init__.py
salt/runners/nacl.py
salt/config/__init__.py
salt/states/etcd_mod.py
doc/ref/configuration/master.rst
doc/topics/pillar/index.rst
doc/topics/tutorials/pillar.rst
conf/suse/master
conf/master
```

**Comment by bryceml** [comment]
Fixed by https://github.com/saltstack/salt/pull/58599
