### ISSUE TITLE
v3000 is missing a release branch in the apt repo

### ISSUE THREAD

**Issue by thusoy** [saltstack/salt#56134]
### Description of Issue
Currently the only release branch one can pin to an apt repo on py3 is `2019.2` as there's no subdirectory for `3000`. Without this one can't pin to a version that will only receive critical bug fixes and not new features.

**Comment by Armadill0** [comment]
It's the same for all platforms in the official repositories. 3000 is only available via the latest branch.

**Comment by dmurphy18** [comment]
This should be available later this week.

**Comment by dmurphy18** [comment]
@thusoy Closing this since the major versions were updated this morning on repo.saltstack.com for all platforms released for Salt 3000
