### ISSUE TITLE
Oddness with test suite

### ISSUE THREAD

**Issue by cachedout** [saltstack/salt#56137]
Something unusual seems to be happening with the test suite.

Take for example, this test: https://jenkinsci.saltstack.com/job/pr-centos7-py2-tornado/job/master/563/

In it, Jenkins reports that all tests have passed, but the log shows something unusual.

The logs are full of stacktraces like the following:

`AuthenticationError: message authentication failed`

Finally, toward the end there is this:

`[CRITICAL] The number of accepted minion keys(256) should be lower than 1/4 of the max open files soft setting(256). salt-master will crash pretty soon! According to the system's hard limit, there's still a margin of 1048320 to raise the salt's max_open_files setting. Please consider raising this value.`

**Comment by OrangeDog** [comment]
You're sure there aren't tests that are deliberately checking those error conditions?

**Comment by cachedout** [comment]
I cannot rule that out, but even if a test were causing deliberate authentication errors, I would not expect those errors to persist for the remainder of the test run.

**Comment by dwoz** [comment]
As far as  authentication errors. They will be resolved in the zeromq suites with this change #56132, however they can't be resolved when using the TCP transport unless we add something to the messages which can allow the tcp transport to do similar filtering.

I'm pretty sure that this message is un-related to the Authentication errors. I will keep an eye out for it.
```
[CRITICAL] The number of accepted minion keys(256) should be lower than 1/4 of the max open files soft setting(256). salt-master will crash pretty soon! According to the system's hard limit, there's still a margin of 1048320 to raise the salt's max_open_files setting. Please consider raising this value.
```

**Comment by cachedout** [comment]
Interesting. Why is the syndic sending failed that fail to auth at all, though? That seems odd.

**Comment by cachedout** [comment]
> You're sure there aren't tests that are deliberately checking those error conditions?

A closer look suggests that that `test_verify.py` might be the source of the max keys log entries.
