### ISSUE TITLE
[Feature requests][salt-cloud][AzureARM] support multiple NICs

### ISSUE THREAD

**Issue by tkykm** [saltstack/salt#56153]
### Description of Issue

It would be good to have a option about multiple NICs.
In some case, we want to associate a VM to 2 or more subnet e.g. frontend and backend

Thanks!
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Ideally profile
```
vm:
  provider: azure
  nics:
    - network: vnet1
       subnet: subnet1
    - network: vnet1
       subnet: subnet2
       security_group: sg1
```

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
I've used this pip modules:
https://raw.githubusercontent.com/saltstack/salt/v2019.2.2/requirements/static/py3.6/cloud.txt

Salt Version:
Salt: 2019.2.2

Dependency Versions:
cffi: 1.13.2
cherrypy: Not Installed
dateutil: 2.8.1
docker-py: Not Installed
gitdb: Not Installed
gitpython: Not Installed
ioflo: Not Installed
Jinja2: 2.8.1
libgit2: Not Installed
libnacl: Not Installed
M2Crypto: 0.35.2
Mako: Not Installed
msgpack-pure: Not Installed
msgpack-python: 0.5.6
mysql-python: Not Installed
pycparser: 2.19
pycrypto: Not Installed
pycryptodome: Not Installed
pygit2: Not Installed
Python: 3.6.8 (default, Aug 7 2019, 17:28:10)
python-gnupg: Not Installed
PyYAML: 3.12
PyZMQ: 15.3.0
RAET: Not Installed
smmap: Not Installed
timelib: Not Installed
Tornado: 4.4.2
ZMQ: 4.1.4

System Versions:
dist: centos 7.7.1908 Core
locale: ANSI_X3.4-1968
machine: x86_64
release: 3.10.0-514.10.2.el7.x86_64
system: Linux
version: CentOS Linux 7.7.1908 Core

**Comment by nicholasmhughes** [comment]
The Azure functionality in Salt is moving to https://github.com/salt-extensions/saltext-azurerm

I have opened an issue there to represent the feature request here.
