### ISSUE TITLE
[Question] job states synchronization between multiple masters

### ISSUE THREAD

**Issue by xq2248** [saltstack/salt#56150]
There are two masters master1/master2, and a minion node1.
The file_root contents and pillars of  two masters are the same.
The node1  connects to two at the same time.

On master1: salt "node1" state.sls test1 queue=True &
The salt job id is: 20200213150840608071
On master2: salt-run jobs.lookup_jod 20200213150840608071
'jobs.lookup_jod' is not available.
Unfortunately， the excuting result of job 20200213150840608071 can not be catched.

Is there any way to sync the job session within the two masters ? So that, once master1 crashes, we can manage the unfinished salt jobs of master1 on master2.

Thanks

**Comment by DmitryKuzmenko** [comment]
@xq2248 there is a mistype in your second command `jobs.lookup_jod` should be `jobs.lookup_jid`. Here's my log with both comands from the same master, I'm getting the same error message but the correct command shows me the result:
```
(venv-3.7.5) $ export PROMPT_COMMAND=
(venv-3.7.5) $ ./scripts/salt --async -l critical alpha state.sls test queue=True 
Executed command with job ID: 20200214162000783916
(venv-3.7.5) $ ./scripts/salt-run -l critical jobs.lookup_jod 20200214162000783916
'jobs.lookup_jod' is not available.
(venv-3.7.5) $ ./scripts/salt-run -l critical jobs.lookup_jid 20200214162000783916
alpha:
----------
          ID: test_ttt
    Function: module.run
        Name: test.echo
      Result: True
     Comment: Module function test.echo executed
     Started: 19:20:01.218643
    Duration: 0.884 ms
     Changes:   
              ----------
              ret:
                  whoami

Summary for alpha
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   0.884 ms
```
