### ISSUE TITLE
[Question] autosign_grains exposed in salt/auth events?

### ISSUE THREAD

**Issue by SDedik** [saltstack/salt#56189]
### Description of Issue
Hello,
Let's say I have a minion configured to send autosign_grains:
```
autosign_grains:
  - windowsdomain
  - ipv4
  - os
... some others
```
And I have salt-master configured to autoaccept minions based on those grains. I can confirm that this part is working as expected. No problem here.

Now, I have a group of servers which are redepoyed/reimaged very often and in automated manner. Autoaccept doesn't work for them because of duplicate minion ID - their keys are moved to `denied` group automatically.

I had an idea to use reactor to make additional checks to decide if key is coming from a server belonging to this dynamic environment and force-accept it.
However, I can't see any of the autosign_grains data in the salt/auth events..

These are events when minion with such ID authenticates for the very first time and gets autoaccepted:
```
salt-run state.event pretty=True
salt/auth       {
    "_stamp": "2020-02-18T11:00:45.487077",
    "act": "accept",
    "id": "myid",
    "pub": "-----BEGIN PUBLIC KEY----- ... -----END PUBLIC KEY-----",
    "result": true
}
minion/refresh/myid       {
    "Minion data cache refresh": "myid",
    "_stamp": "2020-02-18T11:00:46.958746"
}
minion_start    {
    "_stamp": "2020-02-18T11:00:47.611473",
    "cmd": "_minion_event",
    "data": "Minion myid started at Tue Feb 18 12:00:47 2020",
    "id": "myid",
    "pretag": null,
    "tag": "minion_start"
}
...
```
And this is event when a new minion with the same ID tries to authenticate and gets denied
```
salt-run state.event pretty=True
salt/auth       {
    "_stamp": "2020-02-18T11:07:04.842653",
    "act": "denied",
    "id": "myid",
    "pub": "-----BEGIN PUBLIC KEY----- ... -----END PUBLIC KEY-----",
    "result": false
}
```
As can be seen from the output, no data reported by autosign_grains is visible in the events. So my question is, is there a way to capture autosign_grains data after all for reactor purposes?

### Versions Report
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: 0.28.4
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.0.3
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```

**Comment by waynew** [comment]
Hi @SDedik, for questions you might have better luck asking on one of our community resources:

- [#salt on freenode](https://kiwiirc.com/nextclient/irc.freenode.net/?nick=IRC-Source_?#salt)
- [Salt Users email list](https://groups.google.com/forum/#!forum/salt-users)
- [Salt Community Slack](https://saltstackcommunity.herokuapp.com/)

**Comment by SDedik** [comment]
Apologies for asking question here and thank you for the links. I'll close the issue now.
