### ISSUE TITLE
Windows minion installer litters in SystemDrive

### ISSUE THREAD

**Issue by SDedik** [saltstack/salt#56198]
### Description of Issue
Minion Installer for Windows https://repo.saltstack.com/windows/Salt-Minion-3000-Py3-AMD64-Setup.exe
After running installer, 4 files are unpacked into root of SystemDrive (by default C:\) and are left there. This is not harmful behavior, but not exactly clean and tidy. I don't see a reason why those files can't be extracted into temp folder or be cleaned up afterwards by installer.
```
C:\Windows6.0-KB2999226-x64.msu
C:\Windows6.1-KB2999226-x64.msu
C:\Windows8-RT-KB2999226-x64.msu
C:\Windows8.1-KB2999226-x64.msu
```

**Comment by waynew** [comment]
@twangboy do you know what's happening here?

**Comment by twangboy** [comment]
I've assigned it to me... I've take a look

**Comment by twangboy** [comment]
I have tried to reproduce this with the installer specified above. No files are left in `C:\`. They should be created in the user temp directory and that is where I see them get created. (`C:\Users\Administrator\AppData\Local\Temp`). A folder that begins with `nsu` and ends with `.tmp` gets created in the temp dir. It is removed when the installation ends.

**Comment by SDedik** [comment]
Thank you for taking your time to look into it. This result was a bit of surprising for me and I did some more investigation. Apparently the issue manifests itself only if unattended installation mode is used:
```
(PowerShell)
$env:USERPROFILE\Downloads\Salt-Minion-3000-Py3-AMD64-Setup.exe /S
```
![image](https://user-images.githubusercontent.com/20631290/76283170-f6a21080-62aa-11ea-96d6-638a2cd71bcb.png)

**Comment by SDedik** [comment]
@twangboy Can you please confirm if you can reproduce the issue when launching installer with `/S` switch?

**Comment by sagetherage** [comment]
@twangboy please follow up on this issue.

**Comment by twangboy** [comment]
I can confirm this bug with the 3000.3 installer users the silent switch `/S`

**Comment by twangboy** [comment]
This issue has been addressed by: https://github.com/saltstack/salt/pull/57578
3001 builds include the above fix.
