### ISSUE TITLE
'saltutil.kill_all_jobs' is not available.

### ISSUE THREAD

**Issue by saurabhnemade** [saltstack/salt#56217]
<img width="405" alt="Screenshot 2020-02-21 at 9 54 38 AM" src="https://user-images.githubusercontent.com/17445338/75004172-46ea3780-5490-11ea-8218-4a588101354e.png">

Somehow saltutil package itself is not available

**Comment by waynew** [comment]
@saurabhnemade Thanks for the report! Unfortunately I cannot reproduce. Can you put together a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)?

This report is also missing `--versions-report`, etc.

**Comment by sagetherage** [comment]
@saurabhnemade are you still seeing this issue and can you provide a [MCVE](https://stackoverflow.com/help/minimal-reproducible-example) - salt version report, state files used, example config, the jobs, if it is on a schedule and any other relevant info with sensitive info redacted, please?
