### ISSUE TITLE
Python SALT API Result Formatter

### ISSUE THREAD

**Issue by praveenkulkarni22** [saltstack/salt#56211]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
**pkg_install.sls**
```
my_pkg_chk:
  pkg.latest:
    - pkgs:
      - python-M2Crypto
```

**Python API Program**
```
import os
import sys
import warnings
import salt.config
import salt.loader
import salt.client

if not sys.warnoptions:
    warnings.simplefilter("ignore")

print("code sync")
__opts__ = salt.config.minion_config('/etc/salt/minion')
caller = salt.client.Caller(mopts=__opts__)
result=caller.cmd('state.apply','pkgi')
salt.output.display_output({'local': result}, out='highstate', opts=__opts__)
```

The above python script works perfectly fine and displays the result as below:

```
local:
----------
          ID: my_pkg_chk
    Function: pkg.latest
      Result: True
     Comment: Package python-M2Crypto is already up-to-date
     Started: 16:07:00.086517
    Duration: 91051.932 ms
     Changes:

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  91.052 s
```
However, I need a tweak in the program to get only the `Succeeded` and `Failed` value in a variable. Is that feasible with `salt.output.display_output`?

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.29.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.12.14-95.24-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

**Comment by waynew** [comment]
@praveenkulkarni22 this question may be more appropriate on IRC, the salt-users mailing list, or the community Slack, which you can find [here](https://www.saltstack.com/resources/community/)

**Comment by waynew** [comment]
It's unclear what you're asking, but this might do what you're looking for?

```
 result = caller.cmd('state.apply', 'pkgi')
data = {'failed': 0, 'succeeded': 0}
for state in result:
    if result[state] == True or result[state] and result[state].get('result') == True:
        data['succeeded'] += 1
    else:
        data['failed'] += 1

print(data)
```

If that doesn't work, let me know and I'll re-open the issue.
