### ISSUE TITLE
Python 3 porting problem

### ISSUE THREAD

**Issue by eqvis** [saltstack/salt#56232]
### Description of Issue
 File "/usr/lib/python3/dist-packages/salt/modules/highstate_doc.py", line 626, in proccesser_markdown
    requisites += _format_markdown_requisite(w.items()[0][0], w.items()[0][1])
TypeError: 'odict_items' object does not support indexing

### What I did:
I used the example for highstate_doc adding some states to my top.sls.
Then I called: `salt-call state.apply makereadme`

### Fixed by
replacing `w.items()` with `list(w.items())` in above file

**Comment by xuhcc** [comment]
I got a similar error at `states/acme.py", line 141, in cert`. This patch resolves the issue: #56243

**Comment by sagetherage** [comment]
closing as fixed will be released in Sodium
