### ISSUE TITLE
`salt 'instance' cmd.run group=group ...` assumes sudo

### ISSUE THREAD

**Issue by St4rz** [saltstack/salt#56236]
### Description of Issue

The command `salt 'server1' cmd.run runas=user1 group=group1 'touch /tmp/test;ls -la /tmp/test'` returns an error on a system where sudo is not installed:

```bash
ERROR: group argument requires sudo but not found
```

Alternatively, it can be ran without the `group=group1` argument to get past the group requirement, but the touched file will still have a group of `root` (our filesystem default), which isn't valid.

```bash
salt 'server1' cmd.run runas=user1 'touch /tmp/test;ls -la /tmp/test'
-rw-r--r-- 1 user1 root 0 Feb 19 17:31 /tmp/test
```

Relevant code: https://github.com/saltstack/salt/blob/master/salt/modules/cmdmod.py#L452-L499

It looks like `cmd.run` [assumes](https://github.com/saltstack/salt/blob/master/salt/modules/cmdmod.py#L452) that the `sudo` command needs to exist in order to switch groups for the command `su -g [group] [user]`, but since we are already running as root, we don't need `sudo`.

### Steps to Reproduce Issue

I'm not sure it will matter if you have a valid minion connected to the master, as long as salt is installed and sudo is not.

1. Create an image with no `sudo` installed (or remove `which sudo`).
2. Run `salt 'server1' cmd.run runas=user1 group=group1 'touch /tmp/test;ls -la /tmp/test'` as root.

### Versions Report
```bash
Salt Version:
           Salt: 2016.11.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.20.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.3
         pygit2: Not Installed
         Python: 2.6.6 (r266:84292, Dec  4 2019, 16:59:32)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.5

System Versions:
           dist: oracle 6.10
        machine: x86_64
        release: 2.6.32-754.25.1.el6.x86_64
         system: Linux
        version: Oracle Linux Server 6.10
```

**Comment by cmcmarrow** [comment]
@St4rz We no longer maintain salt 2016.11. I would suggest upgrading to a later version of salt. If you still can’t run this command I would put in another ticket for it.
