### ISSUE TITLE
Salt Cloud doesn't expose full filter capabilites of amazon describe-images api

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#56240]
### Description of Issue
Salt Cloud only lets you specify amis by id or by name, we should be able to pass it any filter, especially owner-id.  Currently if you specify `Windows_Server-2016-English-Full-Base-20*` without specifying the owner-id, you end up getting a 3rd party ami instead of the official one.  There also doesn't appear to be a way to limit the search to private amis because of this.

This could potentially become a security problem.

As an example, 
```
aws ec2 describe-images --filter 'Name=name,Values=Windows_Server-2016-English-Full-Base-20*'|jq '.Images[].ImageLocation'
```
returns 
```
"amazon/Windows_Server-2016-English-Full-Base-2019.11.13"
"amazon/Windows_Server-2016-English-Full-Base-2019.12.16"
"aws-marketplace/Windows_Server-2016-English-Full-Base-2020.02.12-a97d6aea-584e-4ded-ba41-290a4fe5b8b3-ami-0248046b079ca082f.4"
"amazon/Windows_Server-2016-English-Full-Base-2020.01.15"
"amazon/Windows_Server-2016-English-Full-Base-2020.02.12"
```
vs 

```
ec2 describe-images --filter 'Name=name,Values=Windows_Server-2016-English-Full-Base-20*' 'Name=owner-id,Values=801119661308'|jq '.Images[].ImageLocation'
```
which returns 
```
"amazon/Windows_Server-2016-English-Full-Base-2019.11.13"
"amazon/Windows_Server-2016-English-Full-Base-2019.12.16"
"amazon/Windows_Server-2016-English-Full-Base-2020.01.15"
"amazon/Windows_Server-2016-English-Full-Base-2020.02.12"
```

### Setup
specify a name for `image:` in salt-cloud profile and you end up getting an ami you didn't expect because you can't filter it by owner.

### Versions Report
master branch

**Comment by Akm0d** [comment]
Solves https://github.com/saltstack/salt/issues/56233

**Comment by sagetherage** [comment]
I think you did this backwards @Akm0d -- you use the syntax in the PR to resolve the issue. closing as done.
