### ISSUE TITLE
salt.states.smartos.vm_present fails when vrrp_vrid is specified

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#56244]
Issue for #55906 as requested

# Description
SmartOS supports VRRP configuration for native zones, when adding a nic with `vrrp_vrid` specified.

The mac for these nics is automatically set to the proper mac as are based on the VRID. As we are keying the nics dict on the `mac` key this causes issues.

# Workaround
Calculate the correct mac and use that as the key for the nics dict.

# Solution
In #55906 we will replace the key with the proper mac when a `vrrp_vrid` is specified.  When chacging VRID's the state will remove the old nic and then add a new one with the proper mac + vrid combo copying all other configuration.

**Comment by sagetherage** [comment]
this is fixed in 3000.1
