### ISSUE TITLE
Which event tags exist?

### ISSUE THREAD

**Issue by jmagnusson** [saltstack/salt#5625]
Looking in the code didn't make me any smarter. Some documentation on which event tags exist would be awesome.

**Comment by rallytime** [comment]
@whiteinge Looks like you added [salt-cloud events](https://docs.saltstack.com/en/latest/topics/event/master_events.html#cloud-events) with #13460. I can't think of anymore that should be added here. Is this one good to close?

**Comment by rallytime** [comment]
I'm going to go ahead and close this. If any new events need to be added to the docs, leave a comment here, and we can re-open. Or feel free to open a new issue. Thanks!

**Comment by whiteinge** [comment]
Whoops. Missed your ping-before-last somehow. Thanks for closing. :+1:
