### ISSUE TITLE
Passed invalid arguments: argument of type 'bool' is not iterable

### ISSUE THREAD

**Issue by vankhoa011** [saltstack/salt#56252]
### Description of Issue
I developed a salt runner script. 
```
def change_account_status(login):
    client = salt.client.get_local_client(__opts__['conf_file'])
    dnscmd = "xxxx".format(login)
    minions = client.cmd_subset(ADC_TGT, 'cmd.run', [dnscmd], timeout=__opts__['timeout'], sub=1)

    return minions
```
Then I run the command by this command on Salt master. 

```
salt-run myscript.change_account_status myname
```
It is working correctly.  I set cronjob to run the command every one hour. However, sometimes the command failed. It's weird issue.  The problem happened randomly.
```
Passed invalid arguments: argument of type 'bool' is not iterable
```
I don't know how to debug this issue . I think it happened because of timeout ? But I couldn't reproduce the issue. Any thought ? Thank you in advance. 

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report

Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: 0.26.3
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.9.6
         pygit2: 0.26.4
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.12.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

Minion version:
    salt-minion 2019.2.0 (Fluorine)

**Comment by cmcmarrow** [comment]
@vankhoa011 It looks like a function most be returning a bool or an iter. Then that return gets passed to another function that only wants an inter. 

Can I get the full stack trace please. It will make finding this bug a lot easier.

**Comment by vankhoa011** [comment]
@cmcmarrow : The problem happens frequently. I couldn't reproduce the issue. When the problem happen again, I will get the debug log for you . Thank you for working on this issue.

**Comment by Ch3LL** [comment]
Closing due to info needed. If you are still experiencing this issue on the latest version of Salt please open a new issue with the logs included in the information of the issue.
