### ISSUE TITLE
win_lgpo: `lgpo.set` with secedit policy always generates `KeyError: u'lgpo.secedit_data'`

### ISSUE THREAD

**Issue by lorengordon** [saltstack/salt#56288]
### Description of Issue

Running the `lgpo.set` execution module with a secedit policy always generates an error: `KeyError: u'lgpo.secedit_data'`.

This happens because `set` calls [_write_secedit_data()](https://github.com/saltstack/salt/blob/9adc2214c3bb7c68f820f7bd5fe5e132b7b3fbc9/salt/modules/win_lgpo.py#L5529) which attempts to pop `lgpo.secedit_data` off the `__context__`, but `set` never calls `_get_secedit_data()` which is where it is added to context.

### Setup
None really required. Just install salt. Tested both 2018.3.4 and 2019.2.3.

### Steps to Reproduce Issue
```
C:\salt\salt-call.bat lgpo.set computer_policy="{'GuestAccountStatus': 'Enabled'}"
```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by garethgreenaway** [comment]
@twangboy Is this a known issue?

**Comment by lorengordon** [comment]
I searched but found no other mentions...

**Comment by garethgreenaway** [comment]
@lorengordon Thanks for the PR with tests!
