### ISSUE TITLE
salt-minion fails startup on Windows Server 2012R2

### ISSUE THREAD

**Issue by xiaohuazi123** [saltstack/salt#56296]
### Description of Issue

salt-minion fails startup on Windows Server 2012R2，due to api-ms-win-crt-runtime-l1-1-0.dll is missing
![QQ截图20200303214632](https://user-images.githubusercontent.com/45115671/75782322-b8cc5600-5d99-11ea-94dc-f86029d76227.jpg)

### Setup
Nothing modified after installing the Salt-Minion-3000-Py3-AMD64-Setup.exe on Windows Server 2012R2
Basic setup, with default configuration files (except for minion id and master id, set during the setup).

### Steps to Reproduce Issue
1/ install Salt-Minion-3000-Py3-AMD64-Setup.exeon a Windows Server 2012R2
2/ start manually C:\salt\salt-minion.bat or C:\salt\salt-minion-debug.bat in a cmd in admin mode.
3/Pop up a dialog box saying (api-ms-win-crt-runtime-l1-1-0.dll) is missing

### Versions Report
Client : Microsoft Windows Server 2012 R2 Datacenter 6.3.9600  Build 9600
Salt-minion : Salt-Minion-3000-Py3-AMD64-Setup.exe

**Comment by garethgreenaway** [comment]
@twangboy FYI.

**Comment by twangboy** [comment]
Looks like the VCRedist is corrupted. Those are bundled in the installer. Try doing a repair in the Add/Remove programs.

**Comment by xiaohuazi123** [comment]
@twangboy  Thanks for your reply, I have tried before

**Comment by twangboy** [comment]
One of these was possibly corrupted during install...
http://repo.saltstack.com/windows/dependencies/64/ucrt/

**Comment by xiaohuazi123** [comment]
Hi @twangboy ，
In another detailed test yesterday, I found that the salt-minion service could not be run on an unactivated Windows machine.

Here are my test results:

- Salt-Minion-3000.1-Py2-AMD64-Setup.exe:Can run the salt-minion service without activating Windows without any errors.
- Salt-Minion-3000.1-Py2-x86-Setup.exe:Can run the salt-minion service without activating Windows without any errors.
- Salt-Minion-3000.1-Py3-AMD64-Setup.exe:Cannot run the salt-minion service without activating Windows. The error message is that there is a lack of api-ms-win-crt-runtime-l1-1-0.dll .
- Salt-Minion-3000.1-Py3-x86-Setup.exe:Can run the salt-minion service without activating Windows without any errors.

The following list of Windows patches cannot be installed without Windows activation
http://repo.saltstack.com/windows/dependencies/64/ucrt/

These results have been tested on Windows2012R2, Windows2016, and Windows2019

**Comment by xiaohuazi123** [comment]
Hi  @twangboy ，
I just tested it again and found that it can fix this problem by installing a patch on an inactive Windows machine 

The following are the detailed steps:
1.Install KB2939087, KB2975061 first, and then restart the operating system
2.Then install KB2919355 and restart the operating system
3.Then install KB2999226 and restart the operating system
4.Finally, install vc_redist.x64.exe and restart the operating system

**This solves the problem of missing api-ms-win-crt-runtime-l1-1-0.dll**

**Comment by arizvisa** [comment]
This also happens on Windows 8.1.

**Comment by arizvisa** [comment]
One way to allow users to fix this themselves would be to implement the `preflight_cmds` configuration option that salt-cloud has only implemented for posix environments. This way users can customize the minion environment prior to deployment similar to how you're able to do against posix environments.

**Comment by arizvisa** [comment]
Was able to resolve this manually by using dism to install the update rather than wusa.

```
:: Salt-minion installer just drops all the relevant KBs to the root of the filesystem for some reason.
:: They're writable (changeable) by all authenticated users on all my systems, so probably a security issue as they can be backdoored...but whatever.
C> cacls /*.msu
[172.33.33.180]: PS C:\Users\root\Documents> cmd /c cacls \*.msu
C:\Windows6.0-KB2999226-x64.msu BUILTIN\Administrators:(ID)F
                                NT AUTHORITY\SYSTEM:(ID)F
                                BUILTIN\Users:(ID)R
                                NT AUTHORITY\Authenticated Users:(ID)C

C:\Windows6.0-KB2999226-x86.msu BUILTIN\Administrators:(ID)F
                                NT AUTHORITY\SYSTEM:(ID)F
                                BUILTIN\Users:(ID)R
                                NT AUTHORITY\Authenticated Users:(ID)C

C:\Windows6.1-KB2999226-x64.msu BUILTIN\Administrators:(ID)F
                                NT AUTHORITY\SYSTEM:(ID)F
                                BUILTIN\Users:(ID)R
                                NT AUTHORITY\Authenticated Users:(ID)C

C:\Windows6.1-KB2999226-x86.msu BUILTIN\Administrators:(ID)F
                                NT AUTHORITY\SYSTEM:(ID)F
                                BUILTIN\Users:(ID)R
                                NT AUTHORITY\Authenticated Users:(ID)C

C:\Windows8-RT-KB2999226-x64.msu BUILTIN\Administrators:(ID)F
                                 NT AUTHORITY\SYSTEM:(ID)F
                                 BUILTIN\Users:(ID)R
                                 NT AUTHORITY\Authenticated Users:(ID)C

C:\Windows8-RT-KB2999226-x86.msu BUILTIN\Administrators:(ID)F
                                 NT AUTHORITY\SYSTEM:(ID)F
                                 BUILTIN\Users:(ID)R
                                 NT AUTHORITY\Authenticated Users:(ID)C

C:\Windows8.1-KB2999226-x64.msu BUILTIN\Administrators:(ID)F
                                NT AUTHORITY\SYSTEM:(ID)F
                                BUILTIN\Users:(ID)R
                                NT AUTHORITY\Authenticated Users:(ID)C

C:\Windows8.1-KB2999226-x86.msu BUILTIN\Administrators:(ID)F
                                NT AUTHORITY\SYSTEM:(ID)F
                                BUILTIN\Users:(ID)R
                                NT AUTHORITY\Authenticated Users:(ID)C

:: Choose the correct one for your system here so you can extract the relevant .cab from it
C> wusa C:\Windows8.1-KB29999226-x86.cab /extract:%TEMP%

:: You should now have a .cab file in your TEMP (%LOCALAPPDATA%\Temp)
C> dism /online /add-package /packagepath:%TEMP%\Windows8.1-KB2999226-x86.cab

:: Run Python to ensure the c-runtime was installed
C> c:\salt\bin\python --version
Python 3.5.4
```

**Comment by arizvisa** [comment]
@xiaohuazi123, sorry to bug you. But is that a screenshot from Windows Server 2012R2? The reason why I ask is because my Windows 8.1 boxes also appear to use the exact same version "6.3.9600. The full version that I listed is from the following:
```
[172.33.33.180]: PS C:\Users\root\Documents> cmd /c systeminfo | findstr "OS Version"
OS Name:                   Microsoft Windows 8.1 Enterprise Evaluation
OS Version:                6.3.9600 N/A Build 9600
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
BIOS Version:              Phoenix Technologies LTD 6.00, 5/19/2017
```

If it is definitely Windows Server 2012R2 and you still have access to it, can you run that `systeminfo` command and paste me its output (specifically "OS Name")? Essentially I'm trying to determine which patch to use using the value from "OS Version", and I need to do it from a cmd.exe script in order to fix boxcutter/windows#185.

**Comment by xiaohuazi123** [comment]
@arizvisa ,
Yes, this is a screenshot of Windows Server 2012R2.
This is my full version output as follows
```powershell  

$ systeminfo | findstr "OS Version"
OS Name:          Microsoft Windows Server 2012 R2 Datacenter
OS Version:          6.3.9600 N/A Build 9600
OS Manufacturer:        Microsoft Corporation
OS Configuration:         Standalone Workstation
OS Build Type:      Multiprocessor Free
BIOS Version:        Phoenix Technologies LTD 6.00, 2015/9/21
```

**Comment by arizvisa** [comment]
Awesome. Thanks a bunch, @xiaohuazi123.

That's interesting.. heh. I suppose I need to check the major/minor version, and then check "OS Name:" for "Windows Server".

Much appreciated, good sir!

**Comment by sagetherage** [comment]
this has been merged, closing
