### ISSUE TITLE
Reactor events not reliably being recieved by minions

### ISSUE THREAD

**Issue by Will-Shanks** [saltstack/salt#56307]
### Description of Issue
On 'minion_start' events the master is configured to highstate the new new minion, but the minion does not always receive this message. Looking at the master log it always sends this event, but when more than one minion_start event happens in quick succession, generally only one minion receives the highstate command. If only one minion_start event happens, it appears to always be successful. 

From looking through the logs and messing with this for a while it feels like a race condition but I'm unsure how to debug further

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
$ cat /etc/salt/master.d/reactor.conf
reactor:
  - 'salt/auth':
    - /srv/salt/reactor/auth-pending.sls
  - 'minion_start':
    - /srv/salt/reactor/setup.sls

$ cat /srv/salt/reactor/auth-pending.sls
\# aware this isn't very secure
{% if 'act' in data and data['act'] != 'accept' and data['id'].startswith('aws') %}
minion_add:
  wheel.key.accept:
    - match: {{ data['id'] }}
{% endif %}

$ cat /srv/salt/reactor/setup.sls
minion_highstate:
  local.state.apply:
    - tgt: {{ data['id'] }}

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)
1. Install salt-minion on multiple nodes
2. enable salt-minion (so salt-minion starts on boot)
3. reboot them all simultaneously 

All keys get accepted, but only a small minority (usually only one) receive the highstate command

logs attached, all set to max logging
- master log - master.txt
- minion that received highstate - aws0-success.txt
- minion that didn't get highstate - aws1-failure.txt
[aws0-success.txt](https://github.com/saltstack/salt/files/4289172/aws0-success.txt)
[aws1-failure.txt](https://github.com/saltstack/salt/files/4289173/aws1-failure.txt)
[master.txt](https://github.com/saltstack/salt/files/4289174/master.txt)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Master is a cent OS 7.7.1908 vm
$ salt --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

Minions are Amazon Linux ec2 instances (AMI=ami-00c03f7f7f2ec15c3)
$ /usr/bin/salt-minion --versions-report
           Salt: 2015.5.10
         Python: 2.7.16 (default, Dec 12 2019, 23:58:22)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.7.0
           RAET: Not Installed
            ZMQ: 4.1.4
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.6.0

**Comment by garethgreenaway** [comment]
@Will-Shanks Thanks for the report.  Unfortunately we do not support the version 2015.5.10, the oldest release that we're currently supporting for bug fixes is 2019.2.x.  Are you able to upgrade to a newer release such as 2019.2.3 or the recently released 3000?

**Comment by Will-Shanks** [comment]
I will try updating and see if that fixes it. The only reason I've been using such an old version is that it is in epel, but it appears that convenience comes at a cost.

**Comment by Will-Shanks** [comment]
Updating to salt 3000 appears to have fixed the problem.

**Comment by garethgreenaway** [comment]
@Will-Shanks Great!  I'l go ahead and close this out then.
