### ISSUE TITLE
file.append fails with "No text found to append." even if text is populated

### ISSUE THREAD

**Issue by margau** [saltstack/salt#56317]
### Description of Issue
file.append-state fails with "No text found to append. Nothing appended", even if "text" is successfully filled.

Failure Message:
```
          ID: ssh-authorized-keys
    Function: file.append
        Name: /root/.ssh/authorized_keys
      Result: False
     Comment: No text found to append. Nothing appended
     Started: 12:25:12.005439
    Duration: 9.522 ms
     Changes:   
```

```
salt '(host)' state.show_sls common.root
(host):
    ----------
    ssh-authorized-keys:
        ----------
        __env__:
            base
        __sls__:
            common.root
        file:
            |_
              ----------
              name:
                  /root/.ssh/authorized_keys
            |_
              ----------
              makedirs:
                  True
            |_
              ----------
              text:
                  - (...)
                  - (...)
            - append
            |_
              ----------
              order:
                  10000
```

### Setup
common/root.sls:
```
ssh-authorized-keys:
  file.append:
    - name: /root/.ssh/authorized_keys
    - makedirs: true
    - text:
{% for key in salt['pillar.get']('admin:ssh:authorized_keys', []) %}
      - {{ key }}
{% endfor %}
```

pillar:
```
(host):
    ----------
    admin:
        ----------
        ssh:
            ----------
            authorized_keys:
                - (...)
                - (...)
```

### Steps to Reproduce Issue

See above, `salt '(host)' state.apply`

### Versions Report
Minion:
```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.12 
         locale: UTF-8
        machine: x86_64
        release: 4.15.18-25-pve
         system: Linux
        version: debian 9.12 
```

Master:
```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: 0.27.7
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.27.4
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.3 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-6-amd64
         system: Linux
        version: debian 10.3 
```

**Comment by garethgreenaway** [comment]
@margau Thanks for the report.  Unfortunately I haven't been able to reproduce this one.  It appears that you're only seeing it when attempting to append text to a file.

**Comment by margau** [comment]
Hi,
yes, I'm only seeing this when i'm appending to an existing file. As mentioned above, it happens when appending to an already existing authorized_keys.

I investigated a little bit further:
I'm adding two lines (two SSH-Keys) to the existing file. If the file is (manually) deleted, it works. 
One of both Keys was in the file before, but manipulating this line - even at the begin - didn't worked out.

On a fresh machine without any content it works at the first try.

**Comment by sagetherage** [comment]
looks like this needs some follow up @garethgreenaway yes?

**Comment by sagetherage** [comment]
kicking this back to triage for review and will follow up by Tuesday, 2020-04-14

**Comment by DmitryKuzmenko** [comment]
The only place where the error could come from is here:
https://github.com/saltstack/salt/blob/master/salt/states/file.py#L5666-L5682

I played around that code as with state and pillar files as with python interpreter. Probably it's something specific to the keys data itself.

@margau is it possible for you to reproduce the issue with a little change in the code on the minion side?

```patch
diff --git a/salt/states/file.py b/salt/states/file.py
index dd5bcec62a..df8fc03359 100644
--- a/salt/states/file.py
+++ b/salt/states/file.py
@@ -5571,8 +5571,9 @@ def append(name,
             for line_item in chunk.splitlines():
                 append_lines.append('{0}'.format(line_item))
 
-    except TypeError:
-        return _error(ret, 'No text found to append. Nothing appended')
+    except TypeError as exc:
+        log.warning(traceback.format_exc())
+        return _error(ret, 'Unable to search in file: {0}'.format(exc))
 
     if __opts__['test']:
         ret['comment'] = 'File {0} is set to be updated'.format(name)
```

**Comment by suptimal** [comment]
Hello i went in a similar issue.
After change in /usr/lib/python3/dist-packages/salt/states/file.py i get "Unable to search in file: sequence item 0: expected str instance, bytes found"

**statefile:**

    /tmp/file_append_test.conf:
      file.append:
        - text:
          - Trust no one unless you have eaten much salt with him.
          - "Salt is born of the purest of parents: the sun and the sea."
    /etc/pve/lxc/2110.conf:
      file.append:
        - text:
          - Trust no one unless you have eaten much salt with him.
          - "Salt is born of the purest of parents: the sun and the sea."
         
Comment after change in /usr/lib/python3/dist-packages/salt/states/file.py


    root@salt-master:/srv/salt# salt 'proxmox01' state.apply min_test test=1
    proxmox01:
    ----------
              ID: /tmp/file_append_test.conf
        Function: file.append
          Result: None
         Comment: File /tmp/file_append_test.conf is set to be updated
         Started: 19:31:37.848124
        Duration: 6.231 ms
         Changes:   
                  ----------
                  diff:
                      --- 
                      
                      +++ 
                      
                      @@ -9,3 +9,5 @@
                      
                       unprivileged: 1
                       lxc.cgroup.devices.allow: c 166:* rwm
                       lxc.mount.entry: /dev/ttyACM0 dev/ttyACM0 none bind,optional,create=file
                      +Trust no one unless you have eaten much salt with him.
                      +Salt is born of the purest of parents: the sun and the sea.
    ----------
              ID: /etc/pve/lxc/2110.conf
        Function: file.append
          Result: False
         Comment: Unable to search in file: sequence item 0: expected str instance, bytes found
         Started: 19:31:37.854456
        Duration: 3.723 ms
         Changes:   

    Summary for proxmox01
    ------------
    Succeeded: 1 (unchanged=1, changed=1)
    Failed:    1
    ------------
    Total states run:     2
    Total run time:   9.954 ms
    ERROR: Minions returned with non-zero exit code

md5sum and content of files  /tmp/file_append_test.conf is a copy of /etc/pve/lxc/2110.conf

    root@salt-master:/srv/salt# salt 'proxmox01' cmd.run 'md5sum /etc/pve/lxc/2110.conf /tmp/file_append_test.conf'
    proxmox01:
        5fa0c7380ce6201e9e98cf28ad1a7eb1  /etc/pve/lxc/2110.conf
        5fa0c7380ce6201e9e98cf28ad1a7eb1  /tmp/file_append_test.conf
    root@salt-master:/srv/salt# salt 'proxmox01' cmd.run 'cat /etc/pve/lxc/2110.conf'
    proxmox01:
        arch: amd64
        features: keyctl=0,nesting=0
        hostname: zigbee2mqtt
        memory: 1024
        net0: name=eth0,bridge=vmbr0,gw=192.168.2.1,hwaddr=AA:CE:38:FC:15:64,ip=192.168.2.110/24,type=veth
        ostype: ubuntu
        rootfs: SamsungSSD:subvol-2110-disk-0,size=10G
        swap: 512
        unprivileged: 1
        lxc.cgroup.devices.allow: c 166:* rwm
        lxc.mount.entry: /dev/ttyACM0 dev/ttyACM0 none bind,optional,create=file

salt minion on proxmox01 runs as root and can can edit the file:

    root@salt-master:/srv/salt# salt 'proxmox01' cmd.run 'test -w /etc/pve/lxc/2110.conf && echo OK'
    proxmox01:
        OK
    root@salt-master:/srv/salt# salt 'proxmox01' cmd.run 'test -r /etc/pve/lxc/2110.conf && echo OK'
    proxmox01:
        OK

salt version:

    Salt Version:
              Salt: 3005
     
    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.9
         gitpython: 3.1.24
            Jinja2: 3.0.3
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: Not Installed
           msgpack: 1.0.3
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: 3.11.0
            pygit2: Not Installed
            Python: 3.10.6 (main, Aug 10 2022, 11:40:04) [GCC 11.3.0]
      python-gnupg: 0.4.8
            PyYAML: 5.4.1
             PyZMQ: 22.3.0
             smmap: 5.0.0
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.4
     
    System Versions:
              dist: ubuntu 22.04 Jammy Jellyfish
            locale: utf-8
           machine: x86_64
           release: 5.15.53-1-pve
            system: Linux
           version: Ubuntu 22.04 Jammy Jellyfish

**Comment by miconx** [comment]
i have exactly the same problem - in my case i just wanted to add keys to /root/.ssh/authorized_keys on a proxmox system - the problem maybe arises because this file (on proxmox)  is a symlink to /etc/pve/priv/authorized_keys

**Comment by tdobes** [comment]
Infuriating that this is closed but not fixed.  I suspect that this might be the same and/or related to #54075, as I experience this problem when the file to which I'm trying to while I'm trying to append is on a fuse filesystem.
