### ISSUE TITLE
salt-cloud doesn't support linode v4 API (and it's now impossible to get v3 API keys)

### ISSUE THREAD

**Issue by dsnopek** [saltstack/salt#56319]
We were using salt-cloud to provision servers on Linode, and all was good, until our API key expired. :-(

It appears the old Linode API is still available and working (we have some valid API keys on our dev Linode account which appear to be working), but the old manager was decommissioned in January 2020, so you can't make new API keys for the old API:

https://www.linode.com/2019/11/18/notice-legacy-linode-manager-users/

I looked at the code in the master branch for the Linode driver and it looks like it's all specific to the old API (you can tell from the all caps JSON keys):

https://github.com/saltstack/salt/blob/master/salt/cloud/clouds/linode.py

Going forward, salt-cloud is going to need to interact with the API, because no one is going to be able to get keys for the old API (and probably at some point they'll decommission the old API too). m. Until that point, we're going to be locked out from using salt-cloud!

**Comment by ellisbenjamin** [comment]
Hey there,

I can provide a more thorough answer tomorrow, but you should be able to generate new apiv3 keys via the API, authenticating with user / pass

```
user.getapikey()
Authenticates a Linode Manager user against their username, password, and two-factor token (when enabled), and then returns a new API key, which can be used until it expires. The number of active keys is limited to 20. Batch requests will be rejected if they include this API action.

Parameters
username - string (required)
password - string (required)
token - string (optional)
Required when two-factor authentication is enabled. Emergency scratch codes are not permitted.
expires - numeric (optional)
Number of hours the key will remain valid, between 0 and 8760. 0 means no expiration. Defaults to 168.
label - string (optional)
An optional label for this key.
Example Response
{
   "ERRORARRAY":[],
   "ACTION":"user.getAPIKey",
   "DATA":{
      "USERNAME":"chris",
      "API_KEY":"aNW3ydF53LpVftU9s50e0reFEwy0piwGhwaLKAj4okRZ"
   }
}

**Comment by ellisbenjamin** [comment]
I’m going to dig a little more and see what the deal is with these docs.. will have to talk to the docs team on Monday. If the above info isn’t public already it should be.

**Comment by dsnopek** [comment]
Ok, thanks!

Is there a v3 client library that can be used to do this? Or a way with the linode-cli? The CLI app seems to want to have a key in advance to do anything. Or just like a curl command that I can substitute my username/password into?

**Comment by dsnopek** [comment]
For folks who find this later, there is a `curl` command-line to generate a new API v3 key on this Linode community post:

https://www.linode.com/community/questions/19555/how-do-i-update-an-expired-apiv3-token-now-that-the-classic-manager-has-reached#answer-71574

So, that should help folks continue to use salt-cloud before there is support for API v4.
