### ISSUE TITLE
Beacon events have trailing slashes in tag when other events typically do not

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#56349]
See [here](https://github.com/saltstack/salt/blob/3e913631bbcdbf66ade98794e4e272565a297c0d/salt/beacons/__init__.py#L119) for the line where the tag is generated.

Almost every other tag in salt (well, really all I have seen, to be honest) contain no trailing slash. This is because most of the built-in events in Salt have their tag created using a common function, `salt.utils.event.tagify()`. But, as noted in the link above, beacon events do not use `tagify` and thus they don't look like most events.

The question is, what to do about it? Does the project care about this inconsistency? If we change the way the beacon system fires events, then we would probably want to do something like ignore trailing slashes in reactor configuration (otherwise users would need to update their reactor configs so they'd continue to work, which would not be good). But, we'd also have to consider differing versions of master and minion and how that would impact things.

@saltstack/team-core thoughts?

**Comment by waynew** [comment]
Well, that's been there for 5 years.

For consistencies' sake I'd love if they all used `tagify` or other unified mechanism for generating tags.

But unless this is actually causing an issue within salt I'd recommend leaving it.

I'd also say that it should depend on the semantics of what an event "is".

The example that I'm thinking of is files and directories on Linux:

```
mkdir -p /tmp/funtimes/cool
touch /tmp/funtimes/cool/stuff.txt
ls /tmp/funtimes/cool
ls /tmp/funtimes/cool/
cd /
rm -rf /tmp/funtimes/cool
touch /tmp/funtimes/cool
ls /tmp/funtimes/cool
ls /tmp/funtimes/cool/
```

In the case of a directory the trailing slash is optional, in the case of a file it's never allowed. The counter example:

```
>>> 'foo/bar'.split('/')
['foo', 'bar']
>>> 'foo/bar/'.split('/')
['foo', 'bar', '']
```

Which approach is "more correct"? I have a mild preference for trailing slashes being insignificant., but I suspect the most correct answer would just come from asking Tom which approach he was thinking about.

**Comment by terminalmage** [comment]
I don't find any of that response relevant to what I said.

I'd welcome some input from someone who understands how events work in Salt, and the implications of making any changes.

**Comment by Ch3LL** [comment]
i believe @waynew 's comment is relevant. He clearly states he would prefer to use the tagify approach, but also doesn't want to change it if its not breaking behavior. I'm also of this thought process. His example with directories was attempting to display how others have done it and brings up the thoughtful question as to whether we should allow a trailing /.

ping @garethgreenaway i know you have done a lot of work in the beacons here. do you have any preference

**Comment by terminalmage** [comment]
I don't find it relevant, because the file and directory distinction have nothing to do with this. Furthermore, slashes aren't just "optional", there are important cases where their absence does make an actual difference. If you run `mv foo bar` and `bar` is a file instead of a dir, it will replace that file. So it's preferable to use trailing slashes whenever moving files to avoid this potential case.

Anyway...

I think it may be a good idea to remove any trailing slashes from events _in general_, as well as doing the same to event globs in the reactor config. Normalizing both would require no change in existing users' configs.

**Comment by garethgreenaway** [comment]
I agree with @Ch3LL here, the comment was relevant and was in agreement that ultimately we should standardize and use `tagify` for all events so there is consistency.  The example with files vs directories, while not a direct 1-to-1 comparison to events, does illustrate some fundamental ideas to think about when considering having a trailing slash or not.  My current preference is that we should use `tagify` to be consistent for all events but since this would semi-major change to beacons and any other areas, we should have a SEP in place for the change and give advance noticed to avoid breaking existing configuratoins.

**Comment by Ch3LL** [comment]
I agree a SEP is the best approach here. I'm going to close this issue, and feel free to open a SEP with details around implementation and we can have formalize the discussion there and approve.
