### ISSUE TITLE
Upgrade option for Windows Minions

### ISSUE THREAD

**Issue by drawsmcgraw** [saltstack/salt#5634]
A cleaner upgrade path for Windows minions would be nice. I just installed 0.15.3 over a 0.15.1 install and it clobbered the config information (c:\salt\conf). I suspected that was the behavior and saved my configs before upgrading, but I can see less wary users being sad from losing their configs.

I checked the docs (http://docs.saltstack.com/topics/installation/windows.html) and didn't find any mention of an upgrade option so I assume this isn't available yet.

**Comment by twangboy** [comment]
https://github.com/saltstack/salt/issues/27032
