### ISSUE TITLE
Refresh git_pillar on master start

### ISSUE THREAD

**Issue by sathieu** [saltstack/salt#56356]
### Description of Issue

With PR #53621, it is possible to reduce the frequency of `git_pillar` updates.

However, `git_pillar` is not updated on server start, and one need to wait for `git_pillar_update_interval` to have the first run.

### Setup
Master config:
```yaml
git_pillar_update_interval: 604800 # 1 week
```

### Steps to Reproduce Issue
- Add a new repo in the git pillar configuration.
- Restart the master

Expected behavior:
- The new repo is available directly

Actual behavior:
- The new repo is available after 1 week :disappointed: 

### Versions Report
`v3000`

**Comment by sathieu** [comment]
Fixed by #56316.

**Comment by Ch3LL** [comment]
thanks!

**Comment by pguinardco** [comment]
Any ETA on getting this merged in?
