### ISSUE TITLE
Minion's encoding problem

### ISSUE THREAD

**Issue by haoqixu** [saltstack/salt#56384]
### Description of Issue

When I run `salt 'foo' state.show_top` on the master, the minion raise `UnicodeDecodeError` at `template_shebang` . But running `salt-call state.show_top` on the minion works well. 

I put some debug logging at the `template_shebang` function to print the `__salt_system_encoding__` variable.  It is `ANSI_X3.4-1968` in the remote command and `UTF-8` in the local command.

`salt-call test.versions_report` reports that the locale of the minion is `UTF-8` but `salt 'foo' test.versions_report` reports it is `ANSI_X3.4-1968`.

### Setup

top.sls

```yaml
base:
  "*":
    - minion
    - common
  "device:area:天津":
    - match: pillar_exact
    - test
```
### Steps to Reproduce Issue

```
#salt '*' state.show_top
10.xx.xxx.xxx:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1675, in _thread_return
        return_data = minion_instance.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/state.py", line 2037, in show_top
        top_ = st_.get_top()
      File "/usr/lib/python3.6/site-packages/salt/state.py", line 3489, in get_top
        tops = self.get_tops()
      File "/usr/lib/python3.6/site-packages/salt/state.py", line 3198, in get_tops
        saltenv=saltenv
      File "/usr/lib/python3.6/site-packages/salt/template.py", line 88, in compile_template
        render_pipe = template_shebang(template, renderers, default, blacklist, whitelist, input_data)
      File "/usr/lib/python3.6/site-packages/salt/template.py", line 177, in template_shebang
        line = salt.utils.stringutils.to_unicode(ifile.readline())
      File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
        return codecs.ascii_decode(input, self.errors)[0]
    UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 54: ordinal not in range(128)
```

```
#salt-call state.show_top
local:
    ----------
    base:
        - minion
        - common
        - test
```

### Versions Report

`salt '10.xx.xxx.xxx' test.versions_report` on the master
```
#salt '10.xx.xxx.xxx' test.versions_report
10.xx.xxx.xxx:
    Salt Version:
               Salt: 3000

    Dependency Versions:
               cffi: Not Installed
           cherrypy: 5.6.0
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
           M2Crypto: 0.35.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 15.3.0
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.2 Final
             locale: ANSI_X3.4-1968   # <=============
            machine: x86_64
            release: 3.10.106-1-****
             system: Linux
            version: CentOS Linux 7.2 Final
```

`salt-call test.versions_report` on the minion
```
#salt-call test.versions_report
local:
    Salt Version:
               Salt: 3000

    Dependency Versions:
               cffi: Not Installed
           cherrypy: 5.6.0
           dateutil: Not Installed
          docker-py: Not Installed
              gitdb: Not Installed
          gitpython: Not Installed
             Jinja2: 2.8.1
            libgit2: Not Installed
           M2Crypto: 0.35.2
               Mako: Not Installed
       msgpack-pure: Not Installed
     msgpack-python: 0.6.2
       mysql-python: Not Installed
          pycparser: Not Installed
           pycrypto: 2.6.1
       pycryptodome: Not Installed
             pygit2: Not Installed
             Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
       python-gnupg: Not Installed
             PyYAML: 3.12
              PyZMQ: 15.3.0
              smmap: Not Installed
            timelib: Not Installed
            Tornado: 4.5.3
                ZMQ: 4.1.4

    System Versions:
               dist: centos 7.2 Final
             locale: UTF-8         # <=============
            machine: x86_64
            release: 3.10.106-1-****
             system: Linux
            version: CentOS Linux 7.2 Final
```

**Comment by frogunder** [comment]
@haoqixu Thank you for reporting this issue.

**Comment by haoqixu** [comment]
Sorry. This is caused by the incorrect locale setting of the server. 

The Python interpreter picks the `sys.stdin.encoding` according to `LC_CTYPE` environment variable and Salt will set `__salt_system_encoding__` with the value of `sys.stdin.encoding`.

I modified the `/etc/locale.conf` without rebooting the system and systemd only read it at early boot. So the environment which the minion daemon was running in is still with the `ansi` encoding and `__salt_system_encoding__` had the value `ANSI_X3.4-1968`. But `salt-call` was running in the new bash session with `utf8` encoding (sys.stdin.encoding == 'UTF-8').

My solution is using `localectl` to configure locale instead of changing the `/etc/locale.conf` manually. The `localectl` will take effect without rebooting the system. Or just reboot the system after modifying `/etc/locale.conf`.

@frogunder Thank you for your reply.

**Comment by ek1m92** [comment]
I just stumbled upon this problem in a similar situation where `__salt_system_encoding__` fell back to ASCII (I assume it is set by https://github.com/saltstack/salt/blob/b95213ec903402f25c1e0aeb3990fe8452ab63ce/salt/__init__.py#L53).

I'm not sure if this is a deliberate decision, but I'm not sure if the expected encoding of a SLS file should be platform dependent. Wouldn't  it make more sense to define a standard encoding for these files and expect that by default?
At first I thought something along these lines would be possible using the [`yaml_utf8`](yaml_utf8) config parameter, but this seems to be a deprecated relic.

A related (stale) issue where a fixed default was suggested seems to be https://github.com/saltstack/salt/issues/46956.

I'm sorry if this is already being addressed or it has been decided not to address this for other reasons, but my initial search did not yield any other results.

**Comment by eetievent** [comment]
Hi, we had lots of problems with locale too.
Here is a workaround **to get the master use the minion locale without rebooting** the machine (utf8):
(setup is salt 3000 on debian 9):
`salt $MINION cmd.run "localectl set-locale LANG=en_US.UTF-8; systemctl restart 'systemd-localed' salt-minion.service"`
Then `salt $MINION test.versions` reports `locale: UTF-8` as expected, and you get rid of the terrible `UnicodeDecodeError`. 
By the way, on the minion, `salt-call test.versions` has simply the current locale of the terminal (set by LANG=).
