### ISSUE TITLE
Why is there MSSQL states module, but it is not shown in the official document

### ISSUE THREAD

**Issue by xiaohuazi123** [saltstack/salt#56385]
### Description of Issue

There are four states modules about MSSQL in the source code of salt
ll /usr/lib/python2.7/site-packages/salt/states/mssql*
mssql_database.py
mssql_login.py
mssql_role.py
mssql_user.py

But,that four MSSQL states modules do not appear in the official documentation（https://docs.saltstack.com/en/latest/py-modindex.html）

Is it because it is not recommended to use that four MSSQL states modules? Since it is not recommended, why  still keep the four MSSQL states module code in the source code of salt?

Also, is it necessary to replace the four states modules with states.module.run?

### Setup
No

### Steps to Reproduce Issue
No

### Versions Report
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: Not Installed
       dateutil: 2.7.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Nov  6 2016, 00:28:07)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by frogunder** [comment]
@xiaohuazi123 Thank you for reporting this issue.

Seems like it it a documentation issue.

Thanks.

**Comment by mchugh19** [comment]
This is fixed in #55914

**Comment by xiaohuazi123** [comment]
Thanks to @mchugh19  for providing pr, however, this pr does not seem to have been merged yet, and the official documentation is not up to date yet?

**Comment by mchugh19** [comment]
@xiaohuazi123 Correct. The PR is waiting for master to be open for the Sodium release.

**Comment by xiaohuazi123** [comment]
> @xiaohuazi123 Correct. The PR is waiting for master to be open for the Sodium release.

Hopefully, Sodium's release won't take long
