### ISSUE TITLE
Buster install from the deb packages py3 version missing Mako

### ISSUE THREAD

**Issue by remyd1** [saltstack/salt#56393]
### Description of Issue
If you install the saltstack minion from https://repo.saltstack.com ; Debian buster / py3 version, the Mako python3 package will be missing.

### Steps to Reproduce Issue
On a fresh debian install:

```bash
apt install -y gnupg
wget -O - https://repo.saltstack.com/py3/debian/10/amd64/latest/SALTSTACK-GPG-KEY.pub | sudo apt-key add -
echo 'deb http://repo.saltstack.com/py3/debian/10/amd64/latest buster main' > /etc/apt/sources.list.d/saltstack.list
apt update
apt install -y salt-common salt-minion
```

### Versions Report

```bash
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.0 
         locale: utf-8
        machine: x86_64
        release: 4.15.18-19-pve
         system: Linux
        version: debian 10.0 

```

### Temporary fix

```bash
apt install -y python3-pip
pip3 install Mako
```

**Comment by frogunder** [comment]
@remyd1 Thank you for reporting this issue.

@dmurphy18 Can you take a look / comment at this one, please? 

Thanks.

**Comment by dmurphy18** [comment]
@remyd1 SaltStack does not provide the mako package for Debian 10 Py 3.  SaltStack only provides Salt for the Debian 10 platform.  SaltStack did provide the mako package for Ubuntu 12.04 Python 2 but it was only for that platform and that platform is long end of life'd.

Please utilize the underlying OS to full fill your requirements.

Please consider closing this issue unless there is other information you consider important to this issue

**Comment by remyd1** [comment]
Ok; understood.
I already provided a way to fix this error in my first message.

However, I think you should update your documentation on https//repo.saltstack.com for this problem, on the debian page.

Best regards.
