### ISSUE TITLE
tpldir calculation is broken in some cases

### ISSUE THREAD

**Issue by mlasevich** [saltstack/salt#56410]
### Description of Issue

Buggy code is here:
https://github.com/saltstack/salt/blob/84c60708cd355f0b24742e8bcdba39073d24c9f8/salt/utils/templates.py#L127-L131

Short version, if name of the directory containing the sls is contained in sls name, tpldir calculation will return wrong result.

Slightly longer version, it seems to be trying to find the tplpath by looking for last occurrence of slspath in template name - without realizing it may occur later in the full template path.

This can be fixed by simply adding the basename of the template to the slspath - although I am not really sure what is the point of this code - seems like a complicated way to get what you already have in slspath....

### Setup

setup as file x/x.sls

```
test:
  test.nop:
    - name: {{ tpldir }}
```
### Steps to Reproduce Issue

* if you run the state above, you will get output of name to be `.` - which is incorrect
* if you rename that state file to anything without "x" in the name, it will return name 'x' (correct)
* if you name it anything with x in the name, you will have a problem
* if you move it to x/x/x.sls - you will get "x" - which is, again, incorrect
* if you move it to x/x/y.sls - you will get "x/x" - which is correct

### Versions Report

bug is still present in the master branch as evident by code link above

**Comment by mlasevich** [comment]
Any news on this? Still hitting this bug in random places - driving people crazy where things unexpectedly fail

**Comment by sagetherage** [comment]
@mlasevich there is a long discussion on this and I can put this into the Magnesium release cycle as a possibility of fixing, but I cannot commit unless there is some help from the community to submit a PR perhaps @terminalmage?

**Comment by mlasevich** [comment]
What is the concern? I can take a stab, but I am a bit unclear about the larger context of this function and worried that its intertwined with other things I am not seeing... Thus would prefer to have someone who is more familiar with the code look at it.

**Comment by sagetherage** [comment]
@mlasevich you are of course welcome to take a stab at it! I was looking through the comments on the closed issue you linked and there was talk of many things, so it seems to have gone in many directions, and yes I also want to be sure  you have someone available to look through the code with you, that is my entire intent. I hope that is suitable.

**Comment by terminalmage** [comment]
I tried to tackle this (or something similar) but ended up breaking behavior that others relied upon. I'll try to dig up the PR and issue on Tuesday. Want to make sure we don't make the same mistakes this time around. :smile:

**Comment by sagetherage** [comment]
Thank you @terminalmage and if @mlasevich you two want to work together I am happy to help set up time and use our Community Slack or Zoom to help facilitate or @cassandrafaris can help as well :)

**Comment by sagetherage** [comment]
> I tried to tackle this (or something similar) but ended up breaking behavior that others relied upon. I'll try to dig up the PR and issue on Tuesday. Want to make sure we don't make the same mistakes this time around. 😄

This is the original PR, right? https://github.com/saltstack/salt/pull/55434 and this is commit that it reverts [7c28995](https://github.com/saltstack/salt/commit/7c28995a0a535f4db2f76db39f09754c7ceda2f5)

**Comment by terminalmage** [comment]
@sagetherage No, that commit is actually _from_ my original PR (https://github.com/saltstack/salt/pull/55434) which was reverted by @dwoz in https://github.com/saltstack/salt/pull/56341 per the conversation in https://github.com/saltstack/salt/issues/56119#issuecomment-597160470.

Note that the act of reverting added some documentation. If any changes are made, we want to make sure that we are not changing behavior in such a way that it will create further confusion (or conflict with the docs).

**Comment by sagetherage** [comment]
oh gosh! look at that, I am not correct! Thank you for setting me straight. Yes, I agree.

**Comment by mlasevich** [comment]
Ok, I actually just started poking at it (without looking at the above first) - I think that entire block of logic is way more complicated than it needs to be. 

From what I see the core issue is how to determine the "root" of the sls template in tmplpath - and there are all sorts of tricks used  to do that - which are source of the bugs - when the reality is - there are only two possibilities here -  either it is whatever is in sls or whatever is in sls plus "init" - am I missing something? Are there any scenarios where sls and tmplpath are completely different?

**Comment by mlasevich** [comment]
My first stab at it, I need to run out for a bit - may not be ready for a PR yet, but wanted any opinions:

https://github.com/mlasevich/salt/commit/c8c49cce88fa8854c33b8e68f960afdd5548cbdf
