### ISSUE TITLE
How to use saltstack to distribute large files?

### ISSUE THREAD

**Issue by xiaohuazi123** [saltstack/salt#56424]
### Description of Issue
Could you please tell me how to use saltstack to distribute large files? 
Such as a 1GB large file, was uploaded to master and then distributed to multiple minion. 
What are the solutions?

### Setup
no

### Steps to Reproduce Issue
no

### Versions Report
no

**Comment by Ch3LL** [comment]
you can take a look at `archive.extracted`, `file.managed`, `rsync.synchronized` states depending on the type of file you are handling. Also the `cp.get_file` execution module

**Comment by xiaohuazi123** [comment]
> you can take a look at `archive.extracted`, `file.managed`, `rsync.synchronized` states depending on the type of file you are handling. Also the `cp.get_file` execution module

Thank you for your answer. One more question, is there a direct file transfer module between minion and minion？

**Comment by markuskramerIgitt** [comment]
I use Salt to control BitTorrent Peer-to-peer file exchange between the clients.

**Comment by xiaohuazi123** [comment]
> I use Salt to control BitTorrent Peer-to-peer file exchange between the clients.

Thank you for your answer. May I ask what BitTorrent tool you are using and what are the specific operation steps?

**Comment by markuskramerIgitt** [comment]
Some (just made public again) description is [here](https://github.com/markuskramerIgitt/saltp2p).
Would you be interested in a collaboration?

**Comment by xiaohuazi123** [comment]
Can act as a collaborator

**Comment by xiaohuazi123** [comment]
> Some (just made public again) description is [here](https://github.com/markuskramerIgitt/saltp2p).
> Would you be interested in a collaboration?

Can act as a collaborator

**Comment by markuskramerIgitt** [comment]
Please describe the situation you want to solve by writing mail/Hangouts to <my github name> at gmail dot com.

**Comment by markuskramerIgitt** [comment]
Please describe the situation you want to solve by writing mail/Hangouts to "my github name" at gmail dot com.

**Comment by xiaohuazi123** [comment]
OK
