### ISSUE TITLE
`sysctl.present` converts spaces to tabs

### ISSUE THREAD

**Issue by kkallday** [saltstack/salt#56445]
### Description of Issue

Hi all.

I am running to the [same issue reported here](https://github.com/saltstack/salt/issues/40054
). I am also configuring the `kernel.core_pattern` variable however, the program I am pipeline core dump to **is able to successfully ignore the tabs** (the program is `systemd-coredump`).

It does seem like odd behavior to convert spaces to tabs because it might cause undesirable behavior for underlying programs (ex: if I want a string to have two spaces and instead a tab character gets inserted and causes the program to malfunction).

Here is the output of the `kernel.core_pattern` variable (those are tabs, see screenshot):
```
# cat /proc/sys/kernel/core_pattern
|/usr/lib/systemd/systemd-coredump	%P	%u	%g	%s	%t	%c	%e
```
![Screen Shot 2020-03-24 at 12 29 21 PM](https://user-images.githubusercontent.com/926865/77468890-7cee4480-6dcb-11ea-9ce5-16927ed021d2.png)

### Setup
Here is my state file:
```
configure_systemd_managed_core_dump:
  sysctl.present:
    - name: kernel.core_pattern
    - value: "|/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e"
```

### Steps to Reproduce Issue
1. Apply state with the above
2. See the following in `kernel.core_pattern`:
```
# cat /proc/sys/kernel/core_pattern
|/usr/lib/systemd/systemd-coredump	%P	%u	%g	%s	%t	%c	%e
```

Here is debug output from applying the state:
```
...
sysctl_|-configure_systemd_managed_core_dump_|-kernel.core_pattern_|-present:
        ----------
        __run_num__:
            13
        changes:
            ----------
            kernel.core_pattern:
                |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e
        comment:
            Updated sysctl value kernel.core_pattern = |/usr/lib/systemd/systemd-coredump %P %u %g %s %t %c %e
        duration:
            39.039
        name:
            kernel.core_pattern
        result:
            True
        start_time:
            19:16:58.241700
...
```

### Versions Report
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.11.5
       cherrypy: 17.4.2
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.2
         Python: 2.7.17 (default, Nov  7 2019, 10:07:09)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: <redacted>
         system: Linux
        version: Ubuntu 18.04 bionic
```

**Comment by Ch3LL** [comment]
that does seem odd that we are enforcing tabs. Is this causing issues once its set?

**Comment by kkallday** [comment]
This isn't causing issue with the underlying program but this is unexpected behavior. It could cause other programs to have issues (expect spaces but tab causes different behavior, syntax errors, etc). [Above, I linked to an issue](https://github.com/saltstack/salt/issues/40054) where the person reported it caused issues to the underlying program.

**Comment by Ch3LL** [comment]
thanks for the clarification.
