### ISSUE TITLE
GitFS checkout may fail on annotated tags

### ISSUE THREAD

**Issue by afischer-opentext-com** [saltstack/salt#56451]
### Description of Issue

We use the salt-masters ext_pillar feature using the git backend (with pygit2). 
We now observe the situation that we have a tag in our git repository which is handled differently by pygit2. Basically this seems to be caused by the situation that it is annotated (with an assigned message). This finally leads to the situation that the tag cannot be used due to error message

```
root@salt-master:/# salt-run pillar.show_pillar saltenv=v3.2.10 pillarenv=v3.2.10
[ERROR   ] Failed to checkout v3.2.10 from git_pillar remote '__env__ ssh://repositoryhost/salt': remote ref does not exist
```

When adding logging to the utils/gitfs.py file which raises the error, the situation is as follows. The tag v3.2.10 fails while tag v3.2.9 can be processed without error:

```
root@salt-master:/# salt-run pillar.show_pillar saltenv=v3.2.10 pillarenv=v3.2.10
[ERROR   ] <_pygit2.Tag object at 0x7f42339c5c30>
[ERROR   ] <class '_pygit2.Tag'>
[ERROR   ] refs/tags/v3.2.10 does not correspond to pygit2.Commit object
[ERROR   ] Failed to checkout v3.2.10 from git_pillar remote '__env__ ssh://repositoryhost/salt': remote ref does not exist
root@salt-master:/# salt-run pillar.show_pillar saltenv=v3.2.9 pillarenv=v3.2.9
[ERROR   ] <_pygit2.Commit object at 0x7f59a1a37c30>
[ERROR   ] <class '_pygit2.Commit'>
```

Due to that I propose to change the code in method `utils.gitfs.Pygit2.checkout` from

```(python)
            elif tag_ref in refs:
                tag_obj = self.repo.revparse_single(tag_ref)
                if not isinstance(tag_obj, pygit2.Commit):
                    log.error(
                        '%s does not correspond to pygit2.Commit object',
                        tag_ref
                    )
```

to 

```(python)
            elif tag_ref in refs:
                tag_obj = self.repo.revparse_single(tag_ref)
                if type(tag_obj) not in [pygit2.Commit, pygit2.Tag]:
                    log.error(
                        '%s does not correspond to pygit2.Commit or pygit2.Tag object (%s)',
                        tag_ref, tag_obj
                    )
```

I see no further issues with that in testing. 

The issue is present from at least 2018.3 up to development.

**Comment by Ch3LL** [comment]
looks like i am able to replicate this and the annotated tag is a tag object where as an un-annotated tag is a commit object.

looks to be the right approach. mind submitting as a PR with tests?

**Comment by afischer-opentext-com** [comment]
Hi, sure, is there a Dockerfile or documentation which allows me to quickly set up a proper local test environment? The last time I wrote tests this was somewhat high effort due to missing dependencies in wrong versions etc. :)

**Comment by afischer-opentext-com** [comment]
I attempted to write some tests. That was somewhat awkward because the affected class had no tests so far. See the linked PR. 

For speeding up this stuff, I wrote https://github.com/afischer-opentext-com/salt-devcontainer. Maybe it is helpful for someone. At least it was for me (still not perfect).

**Comment by Ch3LL** [comment]
thanks a bunch for the PR!

**Comment by sagetherage** [comment]
PR merged, closing will be released in Sodium
