### ISSUE TITLE
Error converting PowerShell JSON return

### ISSUE THREAD

**Issue by jmgascoriego** [saltstack/salt#56456]
### Description of Issue
SaltStack shows the error in the title when executing powershell command that must return a value.

### Setup
Salt Stack master running over RHEL7.
Salt Stack minions running over Windows 2012 R2.

### Steps to Reproduce Issue
State:

<pre><code>
{% set NextHop = salt['cmd.powershell']("Get-NetRoute | Where-Object {\$_.DestinationPrefix -match '198.25.24.4'} | Select-Object NextHop | Format-Table -HideTableHeaders | Out-String | ForEach-Object { \$_.Trim() } | ConvertTo-Json") %}

{% set Routes = ['84.54.4.32','84.54.7.32','84.54.57.32'] %}

{% for NetRoute in Routes %}

static_route_{{ NetRoute }}:
  cmd.run:
    - name: 'route -p ADD {{ NetRoute }} MASK 255.255.255.224 {{ NextHop }}'

{% endfor %}
</code></pre>

Salt command:
<pre><code>
salt 'ProdApp01' state.apply states/static_routes_windows test=True
</code></pre>

Execution of salt command is succesful but it's not getting the value returned by the PowerShell command executed As you can see below, the master output shows "{}":
<pre><code>
ProdApp01:
----------
          ID: static_route_84.54.4.32
    Function: cmd.run
        Name: route -p ADD 84.54.4.32 MASK 255.255.255.224 {}
      Result: None
     Comment: Command "route -p ADD 84.54.4.32 MASK 255.255.255.224 {}" would have been executed
     Started: 18:16:25.686000
    Duration: 0.0 ms
     Changes:
----------
          ID: static_route_84.54.7.32
    Function: cmd.run
        Name: route -p ADD 84.54.7.32 MASK 255.255.255.224 {}
      Result: None
     Comment: Command "route -p ADD 84.54.7.32 MASK 255.255.255.224 {}" would have been executed
     Started: 18:16:25.686000
    Duration: 0.0 ms
     Changes:
----------
          ID: static_route_84.54.57.32
    Function: cmd.run
        Name: route -p ADD 84.54.57.32 MASK 255.255.255.224 {}
      Result: None
     Comment: Command "route -p ADD 84.54.57.32 MASK 255.255.255.224 {}" would have been executed
     Started: 18:16:25.686000
    Duration: 0.0 ms
     Changes:

Summary for ProdApp01
-------------
Succeeded: 3 (unchanged=3)
Failed:     0
-------------
Total states run:     3
Total run time:    0.000 ms
</code></pre>

Output from the minion:
<pre><code>
2020-03-26 18:16:25,670 [salt.loaded.int.module.cmdmod:3611][ERROR   ][10308] Error converting PowerShell JSON return
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt\modules\cmdmod.py", line 3609, in powershell
    return salt.utils.json.loads(response)
  File "c:\salt\bin\lib\site-packages\salt\utils\json.py", line 92, in loads
    return json_module.loads(s, **kwargs)
  File "c:\salt\bin\lib\json\__init__.py", line 339, in loads
    return _default_decoder.decode(s)
  File "c:\salt\bin\lib\json\decoder.py", line 364, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "c:\salt\bin\lib\json\decoder.py", line 382, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded
</code></pre>

Execution of the command directly in PowerShell is succesful returning the expected value:
<pre><code>
PS C:\Users\administrator> Get-NetRoute | Where-Object {$_.DestinationPrefix -match '198.25.24.4'} | Select-Object
NextHop | Format-Table -HideTableHeaders | Out-String | ForEach-Object { $_.Trim() } | ConvertTo-Json
"192.168.164.254"
</code></pre>

### Versions Report
Master:

<pre><code>Salt Version:
           Salt: 2019.2.0

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Jun 11 2019, 14:33:56)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.7 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-957.21.3.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.7 Maipo
</code></pre>

Minion:
<pre><code>
Salt Version:
           Salt: 2019.2.3

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
        libnacl: 1.6.1
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 2.7.15 (v2.7.15:ca079a3ea3, Apr 30 2018, 16:30:26) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 18.0.1
           RAET: Not Installed
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2012ServerR2
         system: Windows
        version: 2012ServerR2 6.3.9600  Multiprocessor Free
</code></pre>

Minion PowerShell version:
<pre><code>
PS C:\> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
4      0      -1     -1
</code></pre>

As per SaltStack documentation, Windows minion meets the PowerShell requirement (PowerShell 3 or above):
[https://docs.saltstack.com/en/2019.2/topics/installation/windows.html#installation-prerequisites](url)

**Comment by Ch3LL** [comment]
can you paste the sanitized version of the debug output from running the command with salt-call so we can see the log before this error:

`salt-call state.apply states/static_routes_windows test=True -ldebug`

**Comment by jmgascoriego** [comment]
Hi Megan,

Running your command directly on the minion server, I can could see 1 issue with the PowerShell command that I have fixed. However, the return is still empty.

<pre><code>PS C:\salt> salt-call state.apply states/static_routes_windows test=True -ldebug
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Configuration file path: c:\salt\conf\minion
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from c:\salt\conf\minion
[DEBUG   ] Including configuration from 'c:\salt\conf\minion.d\_schedule.conf'
[DEBUG   ] Reading configuration from c:\salt\conf\minion.d\_schedule.conf
[DEBUG   ] Loading static grains from c:\salt\conf\grains
[INFO    ] Got list of available master addresses: [u'1-sstack01', u'2-sstack01']
[DEBUG   ] "1-sstack01" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://10.182.140.14:4506
[DEBUG   ] "2-sstack01" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://10.182.140.14:4506
[DEBUG   ] Connecting to master. Attempt 1 (infinite attempts)
[DEBUG   ] "1-sstack01" Not an IP address? Assuming it is a hostname.
[DEBUG   ] Master URI: tcp://10.182.140.14:4506
[DEBUG   ] Popen(['git', 'version'], cwd=C:\salt, universal_newlines=False, shell=None)
[DEBUG   ] Initializing new AsyncAuth for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (7087)
[DEBUG   ] Setting zmq_reconnect_ivl to '7087ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506', 'clear')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.182.140.14:4506
[DEBUG   ] Trying to connect to: tcp://10.182.140.14:4506
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] salt.crypt._get_key_with_evict: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Connecting the Minion to the Master publish port, using the URI: tcp://10.182.140.14:4505
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.182.140.14:4506
[DEBUG   ] Trying to connect to: tcp://10.182.140.14:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] LazyLoaded state.apply
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded saltutil.is_running
[DEBUG   ] LazyLoaded grains.get
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.182.140.14:4506
[DEBUG   ] Trying to connect to: tcp://10.182.140.14:4506
[DEBUG   ] Gathering pillar data for state run
[DEBUG   ] Determining pillar cache
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.182.140.14:4506
[DEBUG   ] Trying to connect to: tcp://10.182.140.14:4506
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: c:\salt\conf\pki\minion\minion.pem
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Finished gathering pillar data for state run
[INFO    ] Loading fresh modules for state activity
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] In saltenv 'base', looking at rel_path 'states/static_routes_windows.sls' to resolve 'salt://states/static_routes_windows.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path 'c:\salt\var\cache\salt\minion\files\base\states\static_routes_windows.sls' to resolve 'salt://states/static_routes_windows.sls'
[DEBUG   ] compile template: c:\salt\var\cache\salt\minion\files\base\states\static_routes_windows.sls
[DEBUG   ] Jinja search path: [u'c:\\salt\\var\\cache\\salt\\minion\\files\\base']
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.182.140.14:4506
[DEBUG   ] Trying to connect to: tcp://10.182.140.14:4506
[DEBUG   ] LazyLoaded cmd.powershell
[INFO    ] Executing command 'Powershell -NonInteractive -NoProfile "try {Get-NetRoute | Where-Object {\$_.DestinationPrefix -match '198.25.24.4'} | Select-Object NextHop | Format-Table -HideTableHeaders | Out-String | ForEach-Object { \$_.Trim('') } | ConvertTo-Json} catch { \"{}\" }"' in directory 'C:\Users\administrator'
[DEBUG   ] stdout: {}
[DEBUG   ] output: {}
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\states\static_routes_windows.sls' using 'jinja' renderer: 1.7650001049
[DEBUG   ] Rendered data from file: c:\salt\var\cache\salt\minion\files\base\states\static_routes_windows.sls:






static_route_84.54.4.32:
  cmd.run:
    - name: 'route -p ADD 84.54.4.32 MASK 255.255.255.224 {}'



static_route_84.54.7.32:
  cmd.run:
    - name: 'route -p ADD 84.54.7.32 MASK 255.255.255.224 {}'



static_route_84.54.57.32:
  cmd.run:
    - name: 'route -p ADD 84.54.57.32 MASK 255.255.255.224 {}'






[DEBUG   ] Results of YAML rendering:
OrderedDict([(u'static_route_84.54.4.32', OrderedDict([(u'cmd.run', [OrderedDict([(u'name', u'route -p ADD 84.54.4.32 MASK 255.255.255.224 {}')])])])), (u'static_route_84.54.7.32', OrderedDict([(u'cmd.run', [OrderedDict([(u'name', u'route -p ADD 84.54.7.32 MASK 255.255.255.224 {}')])])])), (u'static_route_84.54.57.32', OrderedDict([(u'cmd.run', [OrderedDict([(u'name', u'route -p ADD 84.54.57.32 MASK 255.255.255.224 {}')])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\states\static_routes_windows.sls' using 'yaml' renderer: 0.0160000324249
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Running state [route -p ADD 84.54.4.32 MASK 255.255.255.224 {}] at time 13:04:29.692000
[INFO    ] Executing state cmd.run for [route -p ADD 84.54.4.32 MASK 255.255.255.224 {}]
[INFO    ] Command "route -p ADD 84.54.4.32 MASK 255.255.255.224 {}" would have been executed
[INFO    ] Completed state [route -p ADD 84.54.4.32 MASK 255.255.255.224 {}] at time 13:04:29.692000 (duration_in_ms=0.0)
[INFO    ] Running state [route -p ADD 84.54.7.32 MASK 255.255.255.224 {}] at time 13:04:29.692000
[INFO    ] Executing state cmd.run for [route -p ADD 84.54.7.32 MASK 255.255.255.224 {}]
[INFO    ] Command "route -p ADD 84.54.7.32 MASK 255.255.255.224 {}" would have been executed
[INFO    ] Completed state [route -p ADD 84.54.7.32 MASK 255.255.255.224 {}] at time 13:04:29.708000 (duration_in_ms=16.0)
[INFO    ] Running state [route -p ADD 84.54.57.32 MASK 255.255.255.224 {}] at time 13:04:29.708000
[INFO    ] Executing state cmd.run for [route -p ADD 84.54.57.32 MASK 255.255.255.224 {}]
[INFO    ] Command "route -p ADD 84.54.57.32 MASK 255.255.255.224 {}" would have been executed
[INFO    ] Completed state [route -p ADD 84.54.57.32 MASK 255.255.255.224 {}] at time 13:04:29.708000 (duration_in_ms=0.0)
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\112827248 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command [u'attrib', u'-R', u'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\Users\administrator'
[DEBUG   ] output:
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506', u'aes')
[DEBUG   ] Initializing new AsyncAuth for (u'c:\\salt\\conf\\pki\\minion', u'ProdApp01', u'tcp://10.182.140.14:4506')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://10.182.140.14:4506
[DEBUG   ] Trying to connect to: tcp://10.182.140.14:4506
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: static_route_84.54.4.32
    Function: cmd.run
        Name: route -p ADD 84.54.4.32 MASK 255.255.255.224 {}
      Result: None
     Comment: Command "route -p ADD 84.54.4.32 MASK 255.255.255.224 {}" would have been executed
     Started: 18:16:25.686000
    Duration: 0.0 ms
     Changes:
----------
          ID: static_route_84.54.7.32
    Function: cmd.run
        Name: route -p ADD 84.54.7.32 MASK 255.255.255.224 {}
      Result: None
     Comment: Command "route -p ADD 84.54.7.32 MASK 255.255.255.224 {}" would have been executed
     Started: 18:16:25.686000
    Duration: 0.0 ms
     Changes:
----------
          ID: static_route_84.54.57.32
    Function: cmd.run
        Name: route -p ADD 84.54.57.32 MASK 255.255.255.224 {}
      Result: None
     Comment: Command "route -p ADD 84.54.57.32 MASK 255.255.255.224 {}" would have been executed
     Started: 18:16:25.686000
    Duration: 0.0 ms
     Changes:


Summary for ProdApp01
-------------
Succeeded: 3 (unchanged=3)
Failed:     0
-------------
Total states run:     3
Total run time:    0.000 ms
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
</code></pre>

Taking a deeper look to the below line, I saw executing the command manually doesn't return any value:

<pre><code>
[INFO    ] Executing command 'Powershell -NonInteractive -NoProfile "try {Get-NetRoute | Where-Object {\$_.DestinationPrefix -match '198.25.24.4'} | Select-Object NextHop | Format-Table -HideTableHeaders | Out-String | ForEach-Object { \$_.Trim('') } | ConvertTo-Json} catch { \"{}\" }"' in directory 'C:\Users\administrator'
</code></pre>

Manual execution in PowerShell:
<pre><code>
PS C:\salt> Powershell -NonInteractive -NoProfile Get-NetRoute | Where-Object {$_.DestinationPrefix -match '198.25.24.4'} | Select-Object NextHop | Format-Table -HideTableHeaders | Out-String | ForEach-Object { $_.Trim('') } | ConvertTo-Json
""
</code></pre>

After some minutes of testing different commands, I could identify the issue. By using the option "-Command {powershell-command-to-be-executed}", I was able to get the expected value:

<pre><code>
PS C:\salt> Powershell -NonInteractive -NoProfile -Command {Get-NetRoute | Where-Object {$_.DestinationPrefix -match '198.25.24.4'} | Select-Object NextHop | Format-Table -HideTableHeaders | Out-String | ForEach-Object { $_.Trim('') } | ConvertTo-Json}
"192.168.164.254"
</code></pre>

I haven't got deep knowledge about PowerShell to explain you the reason but perhaps this link helps to define the final solution:

[https://docs.microsoft.com/en-us/powershell/module/Microsoft.PowerShell.Core/About/about_PowerShell_exe?view=powershell-5.1#-command](url)

I'm not 100% sure whether this modification applies to lines 347, 349 and 351 of the file C:\salt\bin\Lib\site-packages\salt\modules\cmdmod.py and to its bytecode compiled file.

**Comment by Ch3LL** [comment]
ping @twangboy you have some more knowledge here. do you know why @jmgascoriego is running into this?

**Comment by ScriptAutomate** [comment]
@jmgascoriego I realize this ticket is rather old. Though, since I just noticed this and am familiar with PowerShell (and executing it in `salt`), I think your command was being executed in a way that `salt` wasn't a fan of. I think your goal could have been achieved by:

- Using `cmd.run` with `shell=powershell` instead of `cmd.powershell`
- Modifying the PowerShell command itself to shorten to a more ideal command, especially one without a `Format-*` cmdlet in the middle of the PowerShell pipeline

### The Problems

With PowerShell, when handling object output via the PowerShell pipeline, you should _never_ use `Format-*` cmdlets such as `Format-Table`. This is because those cmdlets completely destroy the object output, and transform the object into the something only meant for console output.

As [Lee Holmes says here](http://powershellcookbook.com/recipe/eeYh/display-the-properties-of-an-item-as-a-table):

> Internally, PowerShell’s formatting commands generate a new type of object:
>
> `Microsoft.PowerShell.Commands.Internal.Format.*`
>
> When these objects make it to the end of the pipeline, PowerShell then automatically sends them to an output cmdlet: by default, `Out-Default`. These `Out-*` cmdlets assume that the objects arrive in a certain order, so doing anything with the output of the formatting commands causes an error in the output system.
>
> To resolve this problem, try to avoid calling the formatting cmdlets in the middle of a script or pipeline. When you do this, the output of your script no longer lends itself to the object-based manipulation so synonymous with PowerShell.

Your cmdlet should not be this:

```powershell
Get-NetRoute | 
    Where-Object {$_.DestinationPrefix -match '198.25.24.4'} | 
    Select-Object NextHop |
    Format-Table -HideTableHeaders | 
    Out-String | 
    ForEach-Object { $_.Trim() } | 
    ConvertTo-Json
```
Note that **the output is not _really_ in json format, per your example output:**

```
PS C:\salt> Powershell -NonInteractive -NoProfile -Command {Get-NetRoute | Where-Object {$_.DestinationPrefix -match '198.25.24.4'} | Select-Object NextHop | Format-Table -HideTableHeaders | Out-String | ForEach-Object { $_.Trim('') } | ConvertTo-Json}
"192.168.164.254"
```

That output is simply text, a string. It is not json.

It doesn't seem like you actually need json returned, either, since your state only requires the string. Also, `cmd.powershell` appends `| ConvertTo-Json` by default, so you would not need it present in your command even if you wanted json. The conversion is normally needed if you have a PowerShell object you want returned as a Python dictionary, for easy access, since PowerShell deals in objects.

Since you simply want a string, you don't need a dictionary returned.

### The Solution

The PowerShell command should probably be more like this, a much more simplified version:

```powershell
(Get-NetRoute -DestinationPrefix "198.25.24.4/*").NextHop
```

Also, let's use `cmd.run` with `shell=powershell` instead, due to what [`salt.modules.cmdmod.powershell` says here](https://docs.saltstack.com/en/master/ref/modules/all/salt.modules.cmdmod.html#salt.modules.cmdmod.powershell):

> Other `cmd.*` functions (besides `cmd.powershell_all`) return the raw text output of the command. This function appends `| ConvertTo-JSON` to the command and then parses the JSON into a Python dictionary. If you want the raw textual result of your PowerShell command you should use `cmd.run` with the `shell=powershell` option.

So, attempt this locally:

```shell
salt-call --local cmd.run '(Get-NetRoute -DestinationPrefix \"198.25.24.4/*\").NextHop' shell=powershell
```

Your state would then need to be converted to `cmd.run` instead of `cmd.powershell`, but you would need to ensure you are using the `shell=powershell` arg, so something like this (this part is untested, as I'm not sure the best way to execute jinja formatted exec modules with args):

```jinja2
{% set NextHop = salt['cmd.run']('(Get-NetRoute -DestinationPrefix \"198.25.24.4/*\").NextHop',shell=powershell) %}
```

**Comment by sagetherage** [comment]
This isn't fix, but a fix has been suggested thanks to @ScriptAutomate a PR would need to be opened. I will move this to approved and get a severity label attached.

**Comment by ScriptAutomate** [comment]
@sagetherage If my suggestions resolve the issue being experienced by @jmgascoriego, it would mean this is an error having to do with how `cmd.run` / `cmd.powershell` was being used with PowerShell output rather than a problem with salt itself.

If it is the case, a PR or fix is not needed and this ticket can be closed upon verification from @jmgascoriego

**Comment by sagetherage** [comment]
Got it, I see I made assumptions based on Shane's label, my mistake! @jmgascoriego let us know if this works for you or not. I am currently closing the ticket, but please mention me if it needs to be reopened.
