### ISSUE TITLE
Inotify not working on minion beacon

### ISSUE THREAD

**Issue by raphaelabrantes** [saltstack/salt#56457]
### Setup

![Screenshot from 2020-03-26 15-05-27](https://user-images.githubusercontent.com/38765954/77681078-9b8f3f80-6f73-11ea-9d23-f6a3cd089506.png)

### /var/log/salt/minion 
> 2020-03-26` 17:55:11,058 [salt.minion      :2615][CRITICAL][8822] The beacon errored: $
> Traceback (most recent call last):$
> File "/usr/lib/python3.8/site-packages/salt/minion.py", line 2613, in handle_beacons$
>    beacons = self.process_beacons(self.functions)$
> File "/usr/lib/python3.8/site-packages/salt/minion.py", line 490, in process_beacons$
>    return self.beacons.process(b_conf, self.opts['grains'])  # pylint: disable=no-member$
>  File "/usr/lib/python3.8/site-packages/salt/beacons/__init__.py", line 104, in process$
>   valid, vcomment = self.beacons[validate_str](b_config[mod])$
> File "/usr/lib/python3.8/site-packages/salt/beacons/inotify.py", line 120, in validate$
>    for path in _config.get('files'):$
> TypeError: 'NoneType' object is not iterable$

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.6
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.8.2 (default, Mar 05 2020, 18:58:42) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.3
          PyZMQ: 19.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: opensuse-tumbleweed 20200322 n/a
         locale: utf-8
        machine: x86_64
        release: 5.5.9-1-default
         system: Linux
        version: openSUSE Tumbleweed 20200322 n/a

**Comment by Ch3LL** [comment]
When i added your config i got errors about it being configured incorrectly. looks like you just need a couple more spaces on the filename. Looks like this is how you currently have it setup:

```
beacons:
  inotify:
    - files:
      /tmp/test2:
        mask:
          - modify
```

I had to change that to:

```
beacons:
  inotify:
    - files:
        /tmp/test2:
          mask:
            - modify
```

**Comment by raphaelabrantes** [comment]
I'm felling really dumb, it fixed the problem,
Thx
