### ISSUE TITLE
virt.pool_running should not always trigger a build

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#56454]
### Description of Issue

When apply the `virt.pool_running` state the libvirt pool is automatically built after being defined. This is fine in most cases, but fails at least for an existing logical pool.

### Steps to Reproduce Issue

Here is one way to reproduce it:

  * Create an existing LVM group on the virtual host minion. We'll assume the VG name to be `libvirtVG` for the next steps.
  * Ensure the libvirt pool is not yet defined
  * Apply the following state

```yaml
dir_pool:
  virt.pool_running:
    - name: libvirtVG
    - ptype: logical
```

  * The state defines the pool and fails with the following error:

```
internal error: Child process (/sbin/vgcreate libvirtVG) unexpected exit status 3:   No command with matching syntax recognised.  Run 'vgcreate --help' for more information.
```

### Versions Report

Needs 3000+ on the minion

**Comment by cbosdo** [comment]
This issue may hit more than just the logical pool types

**Comment by cbosdo** [comment]
Will also apply for a disk pool that was already created:
`error: Storage pool already built: Device '/dev/vdb' already formatted using 'gpt'`

**Comment by sagetherage** [comment]
merged and will be released in Sodium - closing
