### ISSUE TITLE
Feature Request: New beacon "monitor"

### ISSUE THREAD

**Issue by jtraub91** [saltstack/salt#56461]
This beacon would provide a similar functionality as job scheduling but would implement it within salt's beacon system. The user would supply a list of _salt_ execution modules to run with optional args and kwargs. The execution modules return would be included with the event and the minion event would only be fired if the return is "truthy" (i.e. not `None`, `False`, `0`, or similar)

**Comment by jtraub91** [comment]
This module has been developed already and is located on my personal fork [here](https://github.com/jtraub91/salt/tree/add_monitor_beacon).

I thought it was a useful beacon and wanted to open issue here to gague whether it is useful to the community. I will hold off submitting the PR until I add unit tests, better docstring documentation, and / or receive comments here on its merit. 

Thanks!

**Comment by Ch3LL** [comment]
i can see this providing a lot of flexibility on what a user can monitor. they can then use execution modules to monitor different aspects of a system. i think this is a great idea. submit away.

**Comment by Ch3LL** [comment]
I wonder if we want to name it something different from just "monitor", maybe salt or salt_monitor?

**Comment by jtraub91** [comment]
I like `salt` since this beacon allows the general use of _any_ `salt` function.

**Comment by jtraub91** [comment]
Hey, I'm just wondering if this can be put back in the pipeline to be reviewed and merged. I rebased on `master` and have all passing CI tests right now. PR is here https://github.com/saltstack/salt/pull/56575
