### ISSUE TITLE
deprecation warning for getchildren when running salt-cloud

### ISSUE THREAD

**Issue by bensteinberg** [saltstack/salt#56475]
### Description of Issue

When I use `salt-cloud` to create or destroy a minion (in EC2), I get the following three warnings from the same line of code:

```
[WARNING ] /usr/lib/python3/dist-packages/salt/utils/xmlutil.py:30: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  if len(xmltree.getchildren()) < 1:

[WARNING ] /usr/lib/python3/dist-packages/salt/utils/xmlutil.py:30: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  if len(xmltree.getchildren()) < 1:

[WARNING ] /usr/lib/python3/dist-packages/salt/utils/xmlutil.py:30: DeprecationWarning: This method will be removed in future versions.  Use 'list(elem)' or iteration over elem instead.
  if len(xmltree.getchildren()) < 1:
```

This is not fatal, of course. The minion is created or destroyed correctly. 

A note about the deprecation can be seen in the docs [here](https://docs.python.org/3.7/library/xml.etree.elementtree.html#xml.etree.ElementTree.Element.getchildren).

A search through the develop branch shows additional use of `getchildren` in `salt/modules/bamboohr.py`, `salt/modules/win_lgpo.py`, and `salt/utils/aws.py`. I haven't yet encountered the warning from these files. (The master branch also has it in `salt/cloud/clouds/ec2.py`.)

I can suppress the warnings by changing e.g. `xmltree.getchildren()` to `list(xmltree)` in `xmlutil.py`. I'd be happy to submit a PR to remove uses of `getchildren` in this and the other files, but I thought I'd file a ticket first in case there are aspects I haven't thought of.

### Setup
Working cloud providers and profiles for AWS.

### Steps to Reproduce Issue

Run
```
sudo salt-cloud --out=json --script-args="-xpython3" -p <profile> <minion_id>
```

### Versions Report

```
Salt Version:
           Salt: 3000
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.3 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-8-amd64
         system: Linux
        version: debian 10.3 
```

**Comment by xeacott** [comment]
Thanks for submitting! There's definitely nothing wrong with submitting a PR, and I know core team has a laundry list of deprecation warnings they're wishing to handle because we want to ensure that we do not break states under any circumstances which probably includes `salt-cloud` too.

**Comment by sagetherage** [comment]
yes, that is correct @xeacott I made a label for deprecations (even though my spell check says that isn't word, it is now) and added it to Sodium for review during all deprecation warning work in the release cycle. @bensteinberg thank you for the issue and the PR!
