### ISSUE TITLE
Is there a donation channel for saltstack software?

### ISSUE THREAD

**Issue by xiaohuazi123** [saltstack/salt#56487]
### Description of Issue
Is there a donation channel for saltstack software? Also, there is a Chinese WeChat payment or alipay payment donation channels, so excellent software is worth supporting
I hope I can donate some money for this software

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by sagetherage** [comment]
@xiaoanyunfei please contact us, directly, by completing the form we have online on our website: https://www.saltstack.com/company/contact-us/ (works best in Chrome).
