### ISSUE TITLE
integration.shell.test_matcher sometimes failing on mac

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#56486]
### Description of Issue
The `integration.shell.test_matcher` tests are sometimes failing on mac.

```
Traceback (most recent call last):
  File "/private/tmp/kitchen/testing/tests/integration/shell/test_matcher.py", line 178, in test_glob
    self.assertIn('minion', data)
AssertionError: 'minion' not found in ''
```

https://jenkinsci.saltstack.com/job/pr-macosxmojave-py2/job/PR-54541/2/testReport/junit/integration.shell.test_matcher/MatchTest/test_glob/

**Comment by dmurphy18** [comment]
Closing this since Py 2 going away and the Python 3 tests appear to be more stable,  Will reopen if problem occurs on Python 3
