### ISSUE TITLE
 Will saltstack provide a protection mechanism or a rollback mechanism

### ISSUE THREAD

**Issue by xiaohuazi123** [saltstack/salt#56499]
### Description of Issue

Does saltstack have any rollback mechanism? Such as 
salt * cmb.run  "rm  -rf   /* " 
or  
delete some files in batches with saltstack on Windows

### Setup
no

### Steps to Reproduce Issue
no
### Versions Report
no

**Comment by OrangeDog** [comment]
It's not possible to magically rollback any arbitrary shell command you might run.
However, you can manage a separate backup/restore system using saltstack, just as you can manage anything else.

**Comment by lukasraska** [comment]
Salt also provides backup/restore of managed files = https://docs.saltstack.com/en/latest/ref/states/backup_mode.html#file-state-backups , but that doesn't involve any changes in the file outside Salt. For that you might want to either use some backup system or capabilities of underlying file system (such as snapshots in BTRFS for example)

**Comment by xeacott** [comment]
I'll close this issue with the solutions above but feel free to reach out to us through this ticket with anything else!

**Comment by xiaohuazi123** [comment]
Thank you for reply
