### ISSUE TITLE
salt-call --local grains.items prints bytestring (3000.1-py3 on French Windows 7)

### ISSUE THREAD

**Issue by lubyou** [saltstack/salt#56494]
### Description of Issue
Hi,

salt-call --local grains.items seemingly prints a bytestring on a French Windows 7 with salt minion 3000.1-py3:

![Screen Shot 2020-04-02 at 09 00 13](https://user-images.githubusercontent.com/300014/78220557-113e6280-74c2-11ea-9381-b3269b51af99.png)

salt-call --local grains.item does not seem to be affected:

![Screen Shot 2020-04-02 at 09 14 01](https://user-images.githubusercontent.com/300014/78220721-56629480-74c2-11ea-824a-e74842d37b8f.png)

### Steps to Reproduce Issue
Install Salt-Minion-3000.1-Py3-AMD64-Setup.exe, run salt-call --local grains.items

### Versions Report
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 7
         system: Windows
        version: 7 6.1.7601 SP1 Multiprocessor Free

**Comment by lubyou** [comment]
Hi again,

I tried the same on a French Windows 10, same result.

![Screen Shot 2020-04-02 at 10 13 14](https://user-images.githubusercontent.com/300014/78226083-7b0f3a00-74cb-11ea-92c1-10e28a18e1a9.png)

It seems to work as expected on an English Windows 10, though.

Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.8.1
         pygit2: Not Installed
         Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist:   
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0 Multiprocessor Free

**Comment by xeacott** [comment]
Thanks for reporting! We've actually had something very similar to this come up in the past too

**Comment by cmcmarrow** [comment]
Is this bug only --local?

**Comment by lubyou** [comment]
@cmcmarrow omitting --local yields the same result, sorry.

**Comment by cmcmarrow** [comment]
@lubyou Whats your Windows user name? Can I also see you minion config? Did you install windows in English then install the French laughing pack? What French language pack are you using?

**Comment by cmcmarrow** [comment]
I got a French ISO and install windows 10 in French “Kind of fun”. Then I installed salt 3000 and could not get the same out put as you. Have you tried running this in powershell? CMD is not very good at UTF-8.

**Comment by cmcmarrow** [comment]
Is your Windows a fresh install? Did you change your clock setting or anything like that? French must be giving salt a char that cant be handled.

**Comment by lubyou** [comment]
These were fresh installs, French, not English + French language pack.
The minion config is default, I just ran the installer and did not define anything.
The windows username is "me".

On the screenshot, you can see that the timezone contains \xc2\x92 (http://www.fileformat.info/info/unicode/char/92/index.htm), it should say "Europe de l'Ouest".

**Comment by cmcmarrow** [comment]
Thanks for the quick resonance! That did the trick. This is most likely an upstream error with python 3. I will put in a patch for salt and report it to python.

**Comment by cmcmarrow** [comment]
@lubyou I was able to get grains.items with your time zone. I got a different uft-8 error with the host name. I believe this bug is fixed in the latest vision of salt. Can see if you can get this bug on 3001 rather than 3000.1.

**Comment by lubyou** [comment]
Hi,

Looks like it is fixed in 3001:

```
C:\Windows\system32>salt-call --local grains.items
local:
    ----------
    SSDs:
        - \\.\PhysicalDrive0
    biosversion:
        VMW71.00V.14410784.B64.1908150010
    cpu_model:
        Intel(R) Core(TM) i7-8700 CPU @ 3.20GHz
    cpuarch:
        AMD64
    cwd:
        C:\Windows\system32
    disks:
        - \\.\PhysicalDrive0
    domain:
        sub.domain.tld
    fqdn:
        bitlocker-vm-de.sub.domain.tld
    fqdn_ip4:
        - 172.16.75.137
    fqdn_ip6:
        - fe80::383e:7deb:694c:96af
    fqdns:
    gpus:
    groupname:
    host:
        bitlocker-vm-de
    hwaddr_interfaces:
        ----------
        Intel(R) 82574L Gigabit Network Connection:
            00:0C:29:4D:C1:CE
        Software Loopback Interface 1:
            :::::
    id:
        bitlocker-vm-de.sub.domain.tld
    init:
        Windows
    ip4_interfaces:
        ----------
        Intel(R) 82574L Gigabit Network Connection:
            - 172.16.75.137
        Software Loopback Interface 1:
            - 127.0.0.1
    ip6_interfaces:
        ----------
        Intel(R) 82574L Gigabit Network Connection:
            - fe80::383e:7deb:694c:96af
        Software Loopback Interface 1:
            - ::1
    ip_interfaces:
        ----------
        Intel(R) 82574L Gigabit Network Connection:
            - 172.16.75.137
            - fe80::383e:7deb:694c:96af
        Software Loopback Interface 1:
            - 127.0.0.1
            - ::1
    ipv4:
        - 127.0.0.1
        - 172.16.75.137
    ipv6:
        - ::1
        - fe80::383e:7deb:694c:96af
    kernel:
        Windows
    kernelrelease:
        10.0.18363
    kernelversion:
        10.0.18362
    locale_info:
        ----------
        defaultencoding:
            cp1252
        defaultlanguage:
            fr_FR
        detectedencoding:
            cp1252
        timezone:
            Europe de l’Ouest (heure d’été)
    localhost:
        bitlocker-vm-de
    manufacturer:
        VMware, Inc.
    master:
        salt
    mem_total:
        8190
    motherboard:
        ----------
        productname:
            440BX Desktop Reference Platform
        serialnumber:
            None
    nodename:
        bitlocker-vm-de
    num_cpus:
        4
    num_gpus:
        0
    os:
        Windows
    os_family:
        Windows
    osfinger:
        Windows-10
    osfullname:
        Microsoft Windows 10 Professionnel
    osmanufacturer:
        Microsoft Corporation
    osrelease:
        10
    osrelease_info:
        - 10
    osservicepack:
        None
    osversion:
        10.0.18363
    path:
        C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\salt;C:\Users\user\AppData\Local\Microsoft\WindowsApps
    pending_reboot:
        False
    pid:
        1084
    productname:
        VMware7,1
    ps:
        tasklist.exe
    pythonexecutable:
        C:\salt\bin\python.exe
    pythonpath:
        - C:\salt\bin\Scripts
        - C:\salt\bin\python37.zip
        - C:\salt\bin\DLLs
        - C:\salt\bin\lib
        - C:\salt\bin
        - C:\salt\bin\lib\site-packages
        - C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg
        - C:\salt\bin\lib\site-packages\win32
        - C:\salt\bin\lib\site-packages\win32\lib
        - C:\salt\bin\lib\site-packages\Pythonwin
        - C:\Windows\Microsoft.NET\Framework64\v4.0.30319\
    pythonversion:
        - 3
        - 7
        - 4
        - final
        - 0
    saltpath:
        C:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt
    saltversion:
        3001
    saltversioninfo:
        - 3001
    serialnumber:
        VMware-56 4d 00 32 19 f9 4a 83-43 48 3e 17 21 4d c1 ce
    server_id:
        856321353
    shell:
        C:\Windows\system32\cmd.exe
    systempath:
        - C:\Windows\system32
        - C:\Windows
        - C:\Windows\System32\Wbem
        - C:\Windows\System32\WindowsPowerShell\v1.0\
        - C:\Windows\System32\OpenSSH\
        - C:\ProgramData\chocolatey\bin
        - C:\salt
        - C:\Users\user\AppData\Local\Microsoft\WindowsApps
    timezone:
        (UTC+01:00) Amsterdam, Berlin, Berne, Rome, Stockholm, Vienne
    username:
        DOMAIN\user
    virtual:
        VMware
    windowsdomain:
        DOMAIN
    windowsdomaintype:
        Domain
    zmqversion:
        4.3.1
```

```
C:\Windows\system32>salt-call --local -V
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.12.2
       cherrypy: 17.4.1
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 10
         system: Windows
        version: 10 10.0.18362 SP0
```

**Comment by cmcmarrow** [comment]
@lubyou that's great!
