### ISSUE TITLE
netbox openconfig hyperlinks are dead

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#56502]
Relevant salt docs page:
- https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.netbox.html

Relevant salt docs file and error:
```
writing output... [ 26%] ref/modules/all/salt.modules.netbox

(line    3) broken    http://ops.openconfig.net/branches/master/openconfig-interfaces.html - 404 Client Error: Not Found for url: http://ops.openconfig.net/branches/master/openconfig-interfaces.html
(line    3) broken    http://ops.openconfig.net/branches/master/openconfig-lacp.html - 404 Client Error: Not Found for url: http://ops.openconfig.net/branches/master/openconfig-lacp.html
(line    9) broken    http://ops.openconfig.net/branches/master/docs/openconfig-lacp.html#lacp-interfaces-interface-config-lacp-mode - 404 Client Error: Not Found for url: http://ops.openconfig.net/branches/master/docs/openconfig-lacp.html
(line    9) broken    http://ops.openconfig.net/branches/master/docs/openconfig-lacp.html#lacp-interfaces-interface-config-interval - 404 Client Error: Not Found for url: http://ops.openconfig.net/branches/master/docs/openconfig-lacp.html
```
Comments
- manually verified

**Comment by ggiesen** [comment]
It looks like the correct links are:

http://ops.openconfig.net/branches/models/master/openconfig-lldp.html
http://ops.openconfig.net/branches/models/master/openconfig-interfaces.html
http://ops.openconfig.net/branches/models/master/docs/openconfig-lacp.html#lacp-interfaces-interface-config-lacp-mode
http://ops.openconfig.net/branches/models/master/docs/openconfig-lacp.html#lacp-interfaces-interface-config-interval

I'll submit a PR for this when I get the chance
