### ISSUE TITLE
Azure cloud topic page links to removed pages (no good hyperlink)

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#56524]
Relevant salt docs page:
- https://docs.saltstack.com/en/master/topics/cloud/azure.html

Relevant salt docs file and error:
```
writing output... [ 78%] topics/cloud/azure

(line  606) broken    https://msdn.microsoft.com/en-us/library/azure/gg981929.aspx - 500 Server Error: Internal Server Error for url: https://msdn.microsoft.com/en-us/library/azure/gg981929.aspx
(line  553) broken    https://msdn.microsoft.com/en-us/library/azure/gg432987.aspx - 500 Server Error: Internal Server Error for url: https://msdn.microsoft.com/en-us/library/azure/gg432987.aspx
(line  844) broken    https://msdn.microsoft.com/en-us/library/azure/jj156209.aspx - 500 Server Error: Internal Server Error for url: https://msdn.microsoft.com/en-us/library/azure/jj156209.aspx
```
Comments
- manually verified

**Comment by nicholasmhughes** [comment]
This is for the super-old "Classic" API that is going away next year. Closing this as "won't fix". Everyone should be moving to the new Resource Manager driver

Additionally, the Azure functionality in Salt is moving to https://github.com/salt-extensions/saltext-azurerm

Start using that, and we can also ensure all docs are up-to-date there
