### ISSUE TITLE
Test Failure macos 10.15 Catalina 

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#56522]
### Description of Issue
6 Failures on Macos 10.15 Catalina

    integration.netapi.rest_cherrypy.test_app_pam.TestAuthPAM.test_bad_pwd_pam_chsh_service
    integration.netapi.rest_cherrypy.test_app_pam.TestAuthPAM.test_bad_pwd_pam_login_service
    integration.shell.test_key.KeyTest.test_list_acc_eauth_bad_creds
    integration.shell.test_runner.RunTest.test_salt_run_with_eauth_bad_passwd
    integration.states.test_service.ServiceTest.test_service_dead
    integration.states.test_service.ServiceTest.test_service_dead_init_delay

https://jenkinsci.saltstack.com/job/pr-macosxcatalina-py3/job/PR-55857/6/

**Comment by bryceml** [comment]
linking pr: https://github.com/saltstack/salt/pull/55857

**Comment by garethgreenaway** [comment]
Change to ensure these tests pass on Catalina:
```
integration.states.test_service.ServiceTest.test_service_dead
integration.states.test_service.ServiceTest.test_service_dead_init_delay
``

```
@@ -38,10 +39,15 @@ class ServiceTest(ModuleCase, SaltReturnAssertsMixin):
             cmd_name = "systemctl"
         elif os_family == "MacOS":
             self.service_name = "org.ntp.ntpd"
+            self.running = "[0-9]"
             if int(os_release.split(".")[1]) >= 13:
                 self.service_name = "com.apple.AirPlayXPCHelper"
+            if int(os_release.split(".")[1]) >= 15:
+                self.service_name = "org.cups.cupsd"
+                # Just make sure the service is stopped.
+                self.run_function("service.stop", name=self.service_name)
+                self.running = "loaded"
             self.stopped = ""
-            self.running = "[0-9]"
         elif os_family == "Windows":
             self.service_name = "Spooler"
```

The API and runner tests are failing because of an issue related to the libcrypto issue:
https://github.com/saltstack/salt/issues/55084
