### ISSUE TITLE
yaml troubleshooting page has deadlink

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#56540]
Relevant salt docs pages:
- https://docs.saltstack.com/en/master/topics/troubleshooting/yaml_idiosyncrasies.html

Relevant salt docs file and error:
```
writing output... [ 97%] topics/troubleshooting/yaml_idiosyncrasies

(line  382) broken    http://pyyaml.org/browser/pyyaml/trunk/lib/yaml/scanner.py#L91 - 404 Client Error: Not Found for url: https://pyyaml.org/browser/pyyaml/trunk/lib/yaml/scanner.py

```
Comments
- manually verified

**Comment by terminalmage** [comment]
Good catch, here's a pull request with that section updated: https://github.com/saltstack/salt/pull/56717

The limitation is actually from the YAML spec, not specifically from PyYAML, it's just that PyYAML is implementing the spec. I've rewritten that paragraph from the docs to reflect this.
