### ISSUE TITLE
Salt Community page doesnt mention slack

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#56559]
### Description of Issue
Salt community Resources page mentions everything under the sun but our primary online mode of communication, Slack.

Are we still using this page as a way to communicate community links? If so, lets add the slack channels and descriptions of them. If not, we should deprecate this page.

#### Relevant page
- https://docs.saltstack.com/en/develop/topics/community/index.html

**Comment by sagetherage** [comment]
we do mention it here, but yes should be on the community page as well https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request
