### ISSUE TITLE
Contributing Docs do not mention changelog

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#56561]
### Description of Issue
Changelog is in use and to add to the log it is more than a commit message, we should have that documented in the docs

### Setup
https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request

### Steps to Reproduce Issue
N/A

### Versions Report
N/A

**Comment by sagetherage** [comment]
@saltstack/docs-working-group

**Comment by sagetherage** [comment]
do we also need information on towncrier in the contributing docs?

**Comment by ScriptAutomate** [comment]
The good thing is that the following can be used:

```rst
:ref:`changelog`
```

As `towncrier` changelog directions were added via #56984, this should now be an easier fix since we'd be able to insert it as a simple reference. In order to avoid merge conflicts, this is currently blocked by #57645

**Comment by sagetherage** [comment]
the Core team won't be able to get to this in Aluminium, we will plan for it in another release.

**Comment by Ch3LL** [comment]
closed by https://github.com/saltstack/salt/pull/65190
