### ISSUE TITLE
Community Slack<-->IRC bridge may no longer work

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#56572]
From gtmanfred [on the community Slack](https://saltstackcommunity.slack.com/archives/C8832QN4U/p1586271917126300)

> thing I thought about that you should probably look into for this slack, slack is ending support for legacy tokens in may, which will mean that the slack <-> irc bridge in #formulas and #irc will stop working.
> If you have a desire to keep those two communities connected, you might want to look into it. Currently it uses https://irc3.readthedocs.io/en/latest/plugins/slack.html and uses the websocket gateway through the legacy tokens, but will probably have to switch to using the newer app model with a callback server.

It would be useful to get some effort to get a supported replacement.

**Comment by gtmanfred** [comment]
subscribe so I can unstale this in 30 days.

**Comment by myii** [comment]
If this works, it opens up bridging across a number of protocols:

* https://github.com/42wim/matterbridge

**Comment by freelock** [comment]
I'm already in the #salt IRC channel via Matrix -- the Matrix - IRC bridge is not going anywhere.

It's pretty easy to bridge between Matrix and Slack -- Matrix has a hosted bridge available, and I run my own Slack bridge so that I can bridge into some private Slacks.

This might be a relatively painless way to keep the channels from getting fragmented. Plus things like threaded replies, reactions, and message edits could be preserved between Matrix and Slack with a direct bridge, with IRC still getting the message text (and automatic shortening/linking of rich messages from the other two...)

**Comment by myii** [comment]
@freelock Are you using https://github.com/matrix-org/matrix-appservice-slack?

I myself use Matrix but while I'm familiar with using it to connect to IRC (I do that right now with the #formulas channel), how does it work the other way around?  What address would IRC users connect to?

**Comment by freelock** [comment]
Yes, that's the bridge I'm using...

The current Freenode #salt channel is in Matrix as #freenode_#salt:matrix.org . I think we can just add the Slack bridge in that room, and then nothing has to change at all for IRC users.

To bridge to Slack, somebody would need to add an app to the Slack team. I think Matrix-side, anybody can initiate that in Riot using the "integrations manager", and that will walk through what's needed on the Slack side.

For a self-hosted bridge (like mine) it's a different Slack app than the one that Riot hosts -- the app needs to be added to the team, and then the associated bot gets invited to the Slack channel and Matrix room. Finally, there's a slack control room for the bot, where the bot owner connects the Slack channel with the Matrix room. It's all pretty easy -- my bridge is currently bridging about 20 Matrix rooms into Slack channels across 6 different Slack teams...

Both the Matrix-hosted and my bridge use the same code base, matrix-appservice-slack -- but the Matrix one has a bunch of other UX in place so users can self-serve to set them up.

**Comment by sagetherage** [comment]
@cassandrafaris @TheDynaMoe

**Comment by myii** [comment]
We've got a trial going where we've got bridging between Slack <= Matrix => IRC.  If anyone cares to try it out, these are the details:

* Slack: #test-irc-bridge2
* Matrix: SaltStack_test-irc-bridge2
* IRC: ##SaltStack_test-irc-bridge2

**Comment by freelock** [comment]
just to clarify, the Matrix address is #SaltStack_test-irc-bridge2:matrix.org ...

Cheers,
John

**Comment by myii** [comment]
Bridge to Gitter also integrated for testing.  I've added the address to the [list above](https://github.com/saltstack/salt/issues/56572#issuecomment-614339526).
