### ISSUE TITLE
[BUG] Master will not create minion data cache for some minions

### ISSUE THREAD

**Issue by cro** [saltstack/salt#56611]
**Description**

When file_client=local and use_master_when_local is True a minion can still receive commands from the master, but the master will never create minion data cache entries for the minion.

This is problematic because the SSE master plugin depends on the existence of that data cache to help populate SSE's views of available minions and there are some situations (notably involving large numbers of proxy minions sharing a Docker container with their master) where it makes sense for the minions to not pull their state tree over the event bus.

**Setup**

Configure a master connected to SaltStack Enterprise.  It should have the defaults for minion data cache.  Configure a minion with 

```
file_client: local
use_master_when_local: True
local: False
```

Configure one or more other minions with `file_client: remote` (this is the default).

Stop the master and attached minions and remove the minion data cache at `/var/cache/salt/master/minions` on the master.

Restart the master and minions.  Observe that `/var/cache/salt/master/minions` will populate with entries for all connected minions except the one with `file_client: local`.

Ideally the cache should populate for all minions when `use_master_when_local: True` and `local: False` 

**Versions Report**

Salt 3000.1 on master and minions.

**Comment by notAJavaProgrammer** [comment]
This is a breaking change for me, as I am using local pillars, grains and files, and connecting to a master.

What's the rationale for changing this behavior on a forced basis? Seems like it should be a documentation update, a warning, and a new config value.

Is there any way to retain the old behavior via config values?
