### ISSUE TITLE
Wrong Salt version information from the master branch

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#56634]
**Description**

To build the Salt installer, version information is retrieved from git.

If git is checked out to a tag (e.g. `v3000`), there is no problem.

If git is checked out to `master`, the version information is unclear to me.

Building from master is necessary to test the installer for the next release.

[salt/version.py](https://github.com/saltstack/salt/blob/e1cf6ec7dbce2a56fb3b05dc0e37cf28bfa58c71/salt/version.py#L567) uses this command:

    git describe --tags --first-parent --match v[0-9]* --always

I think this was appropriate for the abandoned "develop" / multi releases git scheme.

Problem with the current "master" git scheme is that it returns from master

    v3000_docs-33-g4249d7f1e1

This happens to be the **last tag**, but not the **highest** 3000.1.

Verified with
```
$ git tag --list | tail
v2019.2.2
v2019.2.2_docs
v2019.2.3
v2019.2.3_docs
v2019.8
v3000
v3000.0rc1
v3000.0rc2
v3000.1
v3000_docs

``` 

When I execute `git describe`, I get

    v3000.1-206-g4249d7f1e1

which complies with [documentation](https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html#version-numbers-git-and-salt-version)

**Possibly related**
- PR https://github.com/saltstack/salt/pull/56418
- issue https://github.com/saltstack/salt/issues/56415

**Setup**
Checkout master git repository. On a forked repository use

    git pull upstream master && git fetch --tags upstream

**Steps to Reproduce the behavior**
Execute commands above.

**Expected behavior**
Containing 3000.1 and 206 

</details>

**Comment by markuskramerIgitt** [comment]
As [documented](https://docs.saltstack.com/en/latest/topics/releases/version_numbers.html#version-numbers-git-and-salt-version)  `v3000.1-206-g4249d7f1e1` could be the basis for a correct Salt version from the Git master branch.

Updated the expected behavior

**Comment by markuskramerIgitt** [comment]
@sagetherage why did you restricted the scope to Windows?

**Comment by xeacott** [comment]
Putting @cmcmarrow on this too since he is actively working on some MSI related things. Although I have a PR out for something quite similar, there recently there was a moderate refactoring to version.py which made my PR obsolete.

**Comment by sagetherage** [comment]
> @sagetherage why did you restrict the scope to Windows?

not limiting, more of a focus of who has the skill set - so more like a team tag

**Comment by cmcmarrow** [comment]
I talked to @markuskramerIgitt on salt community. The problem was found and no fix needs to be push to salt.

**Comment by markuskramerIgitt** [comment]
@cmcmarrow, @twangboy could you please reopen?

twangboy tells me that version.py "grabs the commit hash".

version.py did and must continue to grab the commit hash only in-between git tags, and omit the commit hash on a git tag (like `v3000.3`)
