### ISSUE TITLE
[BUG] pkgrepo.managed fails if PPA repository GPG key has UTF8 characters

### ISSUE THREAD

**Issue by TheJJ** [saltstack/salt#56652]
**Description**

State:
```sls
yq-ppa:
  pkgrepo.managed:
    - ppa: rmescandon/yq
    - refresh_db: true
```

Result:
```
    gpg: keyring `/tmp/tmpfhr1puyp/secring.gpg' created
    gpg: keyring `/tmp/tmpfhr1puyp/pubring.gpg' created
    gpg: requesting key CC86BB64 from hkp server keyserver.ubuntu.com
    gpg: /tmp/tmpfhr1puyp/trustdb.gpg: trustdb created
    gpg: key CC86BB64: public key "Launchpad PPA for Roberto Mier Escand�n \xee\x83\xbf" imported
    gpg: Total number processed: 1
    gpg:               imported: 1  (RSA: 1)
    'ascii' codec can't decode byte 0xc3 in position 108: ordinal not in range(128)
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 2019.2.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Nov  7 2019, 10:44:02)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: Not Installed
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: Not Installed
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-64-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Comment by Akm0d** [comment]
@TheJJ  Hey thank you for this report! Could you tell me exactly what command you ran to see this issue with `--log-level debug`?

**Comment by TheJJ** [comment]
I just ran `salt-ssh --refresh --user $USER servername state.sls test -l debug`.
<details><summary>Here's the log.</summary>
[INFO    ] Loading Saltfile from '/srv/saltstack/Saltfile'
[DEBUG   ] Reading configuration from /srv/saltstack/Saltfile
[DEBUG   ] Reading configuration from /srv/saltstack/etc/master
[DEBUG   ] Configuration file path: /srv/saltstack/etc/master
[DEBUG   ] LazyLoaded flat.targets
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: /srv/saltstack/etc/roster
[DEBUG   ] Jinja search path: ['/srv/saltstack/cache/files/base']
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[PROFILE ] Time (in seconds) to render '/srv/saltstack/etc/roster' using 'jinja' renderer: 0.152022123336792
[DEBUG   ] Rendered data from file: /srv/saltstack/etc/roster:
---8<---[snip]---8<---
[PROFILE ] Time (in seconds) to render '/srv/saltstack/etc/roster' using 'yaml' renderer: 0.06558918952941895
[DEBUG   ] LazyLoaded roster_matcher.targets
[DEBUG   ] Matched minions: {'servername': {'sudo': True, 'host': 'servername'}}
[DEBUG   ] LazyLoaded roots.envs
[DEBUG   ] Could not LazyLoad roots.init: 'roots.init' is not available.
[DEBUG   ] Updating roots fileserver cache
[DEBUG   ] LazyLoaded sqlite3.prep_jid
[DEBUG   ] sqlite3 returner <save_load> called jid: 20200421151115314178 load: {'jid': '20200421151115314178', 'tgt_type': 'glob', 'tgt': 'servername', 'user': 'user', 'fun': 'state.sls', 'arg': ['test']}
[DEBUG   ] Connecting the sqlite3 database: ./var/jobs.db timeout: 5
[DEBUG   ] Closing the sqlite3 database connection
[DEBUG   ] LazyLoaded state.sls
[DEBUG   ] Performing shimmed, blocking command as follows:
test.opts_pkg
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 2007  STDOUT_FD: 12  STDERR_FD: 14
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE servername: 0
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] compile template: ./pillar/top.sls
[DEBUG   ] Jinja search path: ['./pillar']
[PROFILE ] Time (in seconds) to render './pillar/top.sls' using 'jinja' renderer: 0.008234500885009766
[DEBUG   ] Rendered data from file: ./pillar/top.sls:
---8<---[snip]---8<---
[DEBUG   ] Results of YAML rendering: 
[DEBUG   ] Jinja search path: ['./pillar']
[DEBUG   ] Finished gathering pillar data for state run
[DEBUG   ] LazyLoaded jinja.render
[DEBUG   ] LazyLoaded yaml.render
[DEBUG   ] Could not find file 'salt://test.sls' in saltenv 'base'
[DEBUG   ] In saltenv 'base', looking at rel_path 'test/init.sls' to resolve 'salt://test/init.sls'
[DEBUG   ] In saltenv 'base', ** considering ** path '/srv/saltstack/cache/files/base/test/init.sls' to resolve 'salt://test/init.sls'
[DEBUG   ] compile template: /srv/saltstack/cache/files/base/test/init.sls
[DEBUG   ] Jinja search path: ['/var/tmp/.user_3c8639_salt/running_data/var/cache/salt/minion/files/base']
[PROFILE ] Time (in seconds) to render '/srv/saltstack/cache/files/base/test/init.sls' using 'jinja' renderer: 0.0006070137023925781
[DEBUG   ] Rendered data from file: /srv/saltstack/cache/files/base/test/init.sls:
yq-ppa:
  pkgrepo.managed:
    - ppa: rmescandon/yq
    - refresh_db: true

[DEBUG   ] Results of YAML rendering: 
OrderedDict([('yq-ppa', OrderedDict([('pkgrepo.managed', [OrderedDict([('ppa', 'rmescandon/yq')]), OrderedDict([('refresh_db', True)])])]))])
[PROFILE ] Time (in seconds) to render '/srv/saltstack/cache/files/base/test/init.sls' using 'yaml' renderer: 0.0002713203430175781
[DEBUG   ] Could not find file 'salt://_modules' in saltenv 'base'
[INFO    ] Caching directory '_modules/' for environment 'base'
[DEBUG   ] Returning file list from cache: age=19 cache_time=20 /srv/saltstack/cache/file_lists/roots/base.p
[DEBUG   ] Executing command: scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/srv/saltstack/pki/ssh/salt-ssh.rsa -o User=user  /tmp/__salt.tmp.6t_lnvif servername:/var/tmp/.user_3c8639_salt/salt_state.tgz
[DEBUG   ] Child Forked! PID: 2013  STDOUT_FD: 13  STDERR_FD: 15
[DEBUG   ] Terminal Command: /bin/sh -c scp -o KbdInteractiveAuthentication=no -o PasswordAuthentication=no -o GSSAPIAuthentication=no -o ConnectTimeout=65 -o Port=22 -o IdentityFile=/srv/saltstack/pki/ssh/salt-ssh.rsa -o User=user  /tmp/__salt.tmp.6t_lnvif servername:/var/tmp/.user_3c8639_salt/salt_state.tgz
[DEBUG   ] Performing shimmed, blocking command as follows:
state.pkg /var/tmp/.user_3c8639_salt/salt_state.tgz test=None pkg_sum=c5aa7a2b899462b99c2eb4ca31fcb42f99d7992e7c757f0be346e4ac1b299783 hash_type=sha256
[DEBUG   ] Executed SHIM command. Command logged to TRACE
[DEBUG   ] Child Forked! PID: 2019  STDOUT_FD: 13  STDERR_FD: 15
[DEBUG   ] VT: Salt-SSH SHIM Terminal Command executed. Logged to TRACE
[DEBUG   ] RETCODE servername: 2
[DEBUG   ] sqlite3 returner <returner> called with data: {'jid': '20200421151115314178', 'id': 'servername', 'return': {'id': 'servername', 'retcode': 2, 'fun': 'state.pkg', 'jid': '20200421151119809592', 'fun_args': ['/var/tmp/.user_3c8639_salt/salt_state.tgz', 'test=None', 'pkg_sum=c5aa7a2b899462b99c2eb4ca31fcb42f99d7992e7c757f0be346e4ac1b299783', 'hash_type=sha256'], 'out': 'highstate', 'return': {'pkgrepo_|-yq-ppa_|-yq-ppa_|-managed': {'result': False, '__run_num__': 0, 'duration': 1394.849, 'start_time': '15:11:20.057759', '__sls__': 'test', 'name': 'yq-ppa', 'changes': {}, 'comment': 'Failed to configure repo \'yq-ppa\': Unable to add PPA \'rmescandon/yq\'. \'[\'apt-add-repository\', \'-y\', \'ppa:rmescandon/yq\']\' exited with status 1: \'gpg: keyring `/tmp/tmprfkx_4bz/secring.gpg\' created\ngpg: keyring `/tmp/tmprfkx_4bz/pubring.gpg\' created\ngpg: requesting key CC86BB64 from hkp server keyserver.ubuntu.com\ngpg: /tmp/tmprfkx_4bz/trustdb.gpg: trustdb created\ngpg: key CC86BB64: public key "Launchpad PPA for Roberto Mier Escand�n \\xee\\x83\\xbf" imported\ngpg: Total number processed: 1\ngpg:               imported: 1  (RSA: 1)\' ', '__id__': 'yq-ppa'}}}, 'fun': 'state.sls'}
[DEBUG   ] Connecting the sqlite3 database: ./var/jobs.db timeout: 5
[DEBUG   ] Closing the sqlite3 database connection
[DEBUG   ] LazyLoaded highstate.output
servername:
----------
          ID: yq-ppa
    Function: pkgrepo.managed
      Result: False
     Comment: Failed to configure repo 'yq-ppa': Unable to add PPA 'rmescandon/yq'. '['apt-add-repository', '-y', 'ppa:rmescandon/yq']' exited with status 1: 'gpg: keyring `/tmp/tmprfkx_4bz/secring.gpg' created
              gpg: keyring `/tmp/tmprfkx_4bz/pubring.gpg' created
              gpg: requesting key CC86BB64 from hkp server keyserver.ubuntu.com
              gpg: /tmp/tmprfkx_4bz/trustdb.gpg: trustdb created
              gpg: key CC86BB64: public key "Launchpad PPA for Roberto Mier Escand�n \xee\x83\xbf" imported
              gpg: Total number processed: 1
              gpg:               imported: 1  (RSA: 1)'
     Started: 15:11:20.057759
    Duration: 1394.849 ms
     Changes:   

Summary for servername
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   1.395 s
</details>

Another important thing: Regardless of the failure, the PPA is added, but *without key*. When the state is applied again, it thinks that the ppa is configured, even though it doesn't work (since no gpg key was imported). One has to delete the `sources.list.d` file manually.

The only solution for me was to manually run `add-apt-repository`, since salt can't add the repo correctly.

**Comment by Ch3LL** [comment]
Closing this due to age, the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue, which will have metrics in tracking issues.
