### ISSUE TITLE
[BUG] Can't install docker python package and use docker module in the same state.

### ISSUE THREAD

**Issue by jtougas** [saltstack/salt#56669]
**Description**
Can't use the docker module (specifically `docker.login`) in the same state that installs the python package the module depends on. It seems that when the docker module's `import docker` picks up `salt.util.docker` instead of the newly installed package. Further executions pick up the correct package.

**Setup**
Brand new Ubuntu xenial box spun from vagrant (yk0/ubuntu-xenial)

```
#do-the-docker.sls
pip:
  pkg.installed:
    - name: python-pip

docker-python:
  pip.installed:
    - name: docker

dockerhub.login:
   module.run:
     - name: docker.login
     - onlyif:
       - test ! -f .docker/config.json
```

**Steps to Reproduce the behavior**

```
# first run, docker module fails to load correctly
salt-call -l debug state.apply do-the-docker

# second run, docker module loads correctly
salt-call -l debug state.apply do-the-docker
```

[first-run.txt](https://github.com/saltstack/salt/files/4489318/first-run.txt)
[second-run.txt](https://github.com/saltstack/salt/files/4489319/second-run.txt)

**Expected behavior**
State should succeed in one execution.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
root@minion2:~# salt-call --versions-report
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Oct  8 2019, 14:14:10)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-22-generic
         system: Linux
        version: Ubuntu 16.04 xenial
 
```
</details>

**Additional context**
* I tried adding `reload_modules: true`, but it didn't help. I don't believe it should be needed in this case.
* @terminalmage asked that I open this following a convo on slack. https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1587044537240100
* A log just after [the import](https://github.com/saltstack/salt/blob/f4feef105b3e2de1545f8c30a8328d70ea2f8d4f/salt/modules/dockermod.py#L246) prints
  * The first execution logs `['/usr/lib/python2.7/dist-packages/salt/utils/docker']`
  * Further executions log `['/usr/local/lib/python2.7/dist-packages/docker']`  
* [The error raised here](https://github.com/saltstack/salt/blob/f4feef105b3e2de1545f8c30a8328d70ea2f8d4f/salt/modules/dockermod.py#L363) is:
```
Traceback (most recent call last):
  File "/var/cache/salt/minion/extmods/modules/dockermod.py", line 378, in _get_docker_py_versioninfo
    return docker.version_info
AttributeError: 'module' object has no attribute 'version_info'
```

**Comment by terminalmage** [comment]
This is caused by the fact that the loader temporarily adds the module dir to the pythonpath while modules are being loaded. The fix here is to rename the `salt/utils/docker` dir and fix any direct imports of `salt.utils.docker`.

**Comment by cathode911** [comment]
reproduces on latest Ubuntu 16.04 with salt installed by terraform' salt-masterless

`local:
----------
          ID: docker-deps
    Function: pkg.installed
        Name: python-docker
      Result: True
     Comment: The following packages were installed/updated: python-docker
     Started: 11:56:22.339120
    Duration: 5317.573 ms
     Changes:
              ----------
              python-backports.ssl-match-hostname:
                  ----------
                  new:
                      3.4.0.2-1
                  old:
              python-docker:
                  ----------
                  new:
                      1.9.0-1~16.04.1
                  old:
              python-websocket:
                  ----------
                  new:
                      0.18.0-2
                  old:
----------
          ID: docker-offrepo
    Function: pkgrepo.managed
        Name: deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
      Result: True
     Comment: Configured package repo 'deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable'
     Started: 11:56:27.661025
    Duration: 5738.797 ms
     Changes:
              ----------
              repo:
                  deb [arch=amd64] https://download.docker.com/linux/ubuntu xenial stable
----------
          ID: docker-install
    Function: pkg.installed
        Name: docker-ce
      Result: True
     Comment: The following packages were installed/updated: docker-ce
     Started: 11:56:33.401597
    Duration: 18982.66 ms
     Changes:
              ----------
              aufs-tools:
                  ----------
                  new:
                      1:3.2+20130722-1.1ubuntu1
                  old:
              cgroupfs-mount:
                  ----------
                  new:
                      1.2
                  old:
              containerd.io:
                  ----------
                  new:
                      1.2.13-1
                  old:
              docker-ce:
                  ----------
                  new:
                      5:19.03.8~3-0~ubuntu-xenial
                  old:
              docker-ce-cli:
                  ----------
                  new:
                      5:19.03.8~3-0~ubuntu-xenial
                  old:
              libltdl7:
                  ----------
                  new:
                      2.4.6-0.1
                  old:
              libseccomp2:
                  ----------
                  new:
                      2.4.1-0ubuntu0.16.04.2
                  old:
                      2.3.1-2.1ubuntu2~16.04.1
              pigz:
                  ----------
                  new:
                      2.3.1-2
                  old:
----------
          ID: docker-service
    Function: service.running
        Name: docker
      Result: True
     Comment: The service docker is already running
     Started: 11:56:52.392849
    Duration: 25.006 ms
     Changes:
----------
          ID: docker-consul-image
    Function: docker_image.present
        Name: consul:1.7.2
      Result: False
     Comment: State 'docker_image.present' was not found in SLS 'consul.provision'
              Reason: 'docker_image' __virtual__ returned False: 'docker.version' is not available.
     Changes:
----------
          ID: docker-consul-container
    Function: docker_container.running
        Name: consul
      Result: False
     Comment: State 'docker_container.running' was not found in SLS 'consul.provision'
              Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.
     Changes:
Summary for local
------------
Succeeded: 4 (changed=3)
Failed:    2
------------
Total states run:     6
Total run time:  30.064 s`

module.consul-cluster-staging.null_resource.provision_app[2] (salt-masterless): [DEBUG   ] Could not LazyLoad docker_image.present: 'docker_image' __virtual__ returned False: 'docker.version' is not available.

root@oro-stgconsul-03:~# salt-minion --version
salt-minion 3000.1

**Comment by terminalmage** [comment]
@jtougas I opened https://github.com/saltstack/salt/pull/56857 which fixes this. However, you will still need to use `- reload_modules: True` on your `pip.installed` state for it to work in a single run, because the states/execution modules that are available are loaded at the beginning of the Salt run, and when they're explicitly reloaded (along with a couple exceptions, see below).

There's an argument to be made that Salt should automatically reload modules when a `pip` state has changes. Salt already does this for `pkg` and `ports` states with changes, because many states/execution modules depend on software being installed which might not have been installed at the beginning of the Salt run. I think the same logic should apply to pip packages, because many salt states/execution modules depend on third-party pip packages being installed. I'm going to bring this up at the Salt Open Hour meeting tomorrow.

**Comment by terminalmage** [comment]
After speaking with the rest of the core team, I opened https://github.com/saltstack/salt/pull/56867 so that `refresh_modules` is not required for pip states.
