### ISSUE TITLE
Ubuntu 20.04 Focal Fossa

### ISSUE THREAD

**Issue by andreasnuesslein** [saltstack/salt#56798]
I have ubuntu 20.04 running on my machine and basically I just wanted to raise my hand and said I'd be willing to beta test salt on this. I would like to upgrade my servers rather sooner than later due to the built-in python3.8 which is gonna be just awesome for my company so I'm also eager to get salt up and running.

 I tried the `bionic` repo from https://repo.saltstack.com/#ubuntu and straight of, many or most of the `grains.items` were missing.
Either way - I would like to offer my testing capabilities but wasn't sure where to go with this other than write a ticket. Hope this is an okay place

Cheers

**Comment by brianthelion** [comment]
@andreasnuesslein See #55310

**Comment by lblasc** [comment]
You can try to build your own deb packages, see: https://salsa.debian.org/salt-team/salt/-/tree/master/debian those packages have patches for python 3.8.
I'm using it on ubuntu 20.04 for a month without any problems.

**Comment by morph027** [comment]
Built packages for testing:

```
sudo curl -sL -o /etc/apt/trusted.gpg.d/morph027-salt.asc https://minio.morph027.de/salt-3000-focal/gpg.key
echo "deb https://minio.morph027.de/salt-3000-focal focal main" | sudo tee /etc/apt/sources.list.d/morph027-salt-3000-focal.list
```
* [build script](https://minio.morph027.de/salt-3000-focal/build.sh) (runs in docker)
* [build log](https://minio.morph027.de/salt-3000-focal/build.log)

**Comment by ichilton** [comment]
Ubuntu 20.04 is due to be released tomorrow (April 23rd) and is an LTS release, so would be good to get packages on the official repo as soon as possible...

**Comment by brianthelion** [comment]
@lblasc Does your patched version include a fix for for the `platform._supported_dists` bug discussed in #55310 ? To the best of my knowledge, it is (1) unfixed here and (2) crashes even the the most basic `salt` workflows on 3.8.

**Comment by lblasc** [comment]
I haven't experienced any issues so far. If it matters I'm using older release, 2019.2.3+dfsg1-2.

**Comment by morph027** [comment]
Testing 2019.2 too right now:

```
sudo curl -sL -o /etc/apt/trusted.gpg.d/morph027-salt.asc https://minio.morph027.de/salt/20.04/amd64/2019.2/SALTSTACK-GPG-KEY.pub
echo "deb https://minio.morph027.de/salt/20.04/amd64/2019.2 focal main" | sudo tee /etc/apt/sources.list.d/morph027-salt-focal.list
```

* [build script](https://minio.morph027.de/salt/20.04/amd64/2019.2/build.sh)
* [build log](https://minio.morph027.de/salt/20.04/amd64/2019.2/build.log)

**Comment by alexey-zhukovin** [comment]
@andreasnuesslein 
Thank you for your comment. 
For current time we don't support python 3.8. Please wait for updates.
You can tracking status of #55310 issue.

**Comment by andreasnuesslein** [comment]
Thanks everybody for the input - obviously I can build packages myself. But I was talking about a sort of beta-repo which I could just try and say "yea this and that is still failing on my end".

Anyways - thanks @alexey-zhukovin I will just track the py3.8 issue for now. :)

**Comment by mrueg** [comment]
Maybe https://github.com/saltstack/salt-bin can be used to provide a package for the minion on focal?

**Comment by joshboon** [comment]
also for folks deploying via salt-cloud you can build the packages and use the following script to install them. script should be dropped into /usr/lib/python3/dist-packages/salt/cloud/deploy/Ubuntu-2004.sh
```#!/bin/bash

# This legacy script pre-dates the salt-bootstrap project. In most cases, the
# bootstrap-salt.sh script is the recommended script for installing salt onto
# a new minion. However, that may not be appropriate for all situations. This
# script remains to help fill those needs, and to provide an example for users
# needing to write their own deploy scripts.

mkdir -p /etc/salt/pki
echo '{{ vm['priv_key'] }}' > /etc/salt/pki/minion.pem
echo '{{ vm['pub_key'] }}' > /etc/salt/pki/minion.pub
cat > /etc/salt/minion <<EOF
{{minion}}
EOF

# add-apt-repository requires an additional dep and is in different packages
# on different systems. Although seemingly ubiquitous it is not a standard,
# and is only a convenience script intended to accomplish the below two steps
# doing it this way is universal across all debian and ubuntu systems.
#echo deb http://ppa.launchpad.net/saltstack/salt/ubuntu `lsb_release -sc` main | tee /etc/apt/sources.list.d/saltstack.list
#wget -q -O- "http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x4759FA960E27C0A6" | apt-key add -

apt-get update
#apt-get install -y -o DPkg::Options::=--force-confold salt-minion
cd /tmp
# This will install 3000.1 I recommend you build your own though so you know the source
wget -q  "http://$HTTPSRC/salt-minion.deb"
wget -q  "http://$HTTPSRC/salt-common.deb"
apt-get -y install python3-dateutil python3-msgpack python3-psutil python3-crypto python3-zmq dctrl-tools python3-zmq dctrl-tools bsdmainutils dmidecode debconf-utils
dpkg --force-confold -i salt-common.deb
dpkg --force-confold -i salt-minion.deb
service salt-minion restart
# minion will be started automatically by install
```

You'll also need to add 
`script: Ubuntu-2004`
to your cloud-profile for deploy

**Comment by vskubriev** [comment]
Salt 3001 released. Ubuntu 20.04 now supported.
https://docs.saltstack.com/en/master/topics/releases/3001.html
