### ISSUE TITLE
salt-run state.event pretty=true:  'state.event'  is not available

### ISSUE THREAD

**Issue by rainer042** [saltstack/salt#56876]
I try to run a salt-run to debug a beacon that seems not to be working any longer on my salt-master. Trying to look at the events I remember I once used the following command that now no longer works returning:  'state.event' is not available:

```
saltmaster# salt-run -l debug  state.event pretty=true
DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/pillar.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/pillar.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.uni-koblenz.de
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Could not LazyLoad state.event: 'state.event' is not available.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] Initializing new IPCClient for path: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20200424085835678402/ret; data = {u'fun_args': [{u'pretty': True, u'__kwarg__': True}], u'jid': u'20200424085835678402', u'return': u"'state.event' is not available.", u'retcode': 254, u'success': False, u'_stamp': '2020-04-24T06:58:35.745965', u'fun': u'state.event'}
[DEBUG   ] LazyLoaded nested.output
'state.event' is not available.
[DEBUG   ] Closing IPCMessageSubscriber instance
[DEBUG   ] Closing IPCMessageClient instance

```
```
saltmaster# salt-call sys.list_functions | grep state.event
    - state.event
```
```
# salt --versions-report
Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: 1.11.2
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 14.0.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.0.4
 
System Versions:
          dist: SuSE 12 x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-122.17-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64
```

**Comment by waynew** [comment]
You probably already know this by now but:

# 2019.2.0 has a severe vulnerability, if you are running an unpatched master IMMEDIATELY SHUT DOWN YOUR MASTER

I'll see if I can reproduce this, thanks for the report!

**Comment by waynew** [comment]
I've tried to reproduce this, but this command is working for me. I don't have a SLES12 server, so it possible something is wonky there.

Can you try with a different OS?

**Comment by rainer042** [comment]
I just created a new SLES12SP5 VM and installed salt-master, same version like on my productive salt-master. On the test machine it works fine, i.e. the state.event module is found. I also tried and reinstalled the salt-master, salt-minion and salt packages but no change.

Do you have any idea how debug this strange problem?

Thanks
Rainer

**Comment by waynew** [comment]
Did you try with Salt 3000.2?

---

This looks like an issue with importing `state.event`, which... shouldn't fail at all.

Try using your Python that Salt is installed with and running `python -c 'import salt.states.event'`. If that fails then we should get a stack trace with a reason. There may be a different place that the import is failing, though.

**Comment by sagetherage** [comment]
@meaksh @agraul any ideas here?

**Comment by meaksh** [comment]
@rainer042 is this still an issue? are you able to still reproduce this?

Currently the Salt version at SLE12SP5 is 3000 (+ backported patches including CVE fixes) and I cannot reproduce this issue there:

```console
71f7c506232c:/ # cat /etc/os-release 
NAME="SLES"
VERSION="12-SP5"
VERSION_ID="12.5"
PRETTY_NAME="SUSE Linux Enterprise Server 12 SP5"
ID="sles"
ANSI_COLOR="0;32"
CPE_NAME="cpe:/o:suse:sles:12:sp5"

71f7c506232c:/ # rpm -qa | grep salt
salt-3000-46.139.1.x86_64
python2-salt-3000-46.139.1.x86_64
salt-master-3000-46.139.1.x86_64
salt-minion-3000-46.139.1.x86_64

71f7c506232c:/ # salt-run state.event pretty=True
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] LazyLoaded state.event
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: 71f7c506232c
[DEBUG   ] Grains refresh requested. Refreshing grains.
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/custom.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/custom.conf
[DEBUG   ] Elapsed time getting FQDNs: 0.125513076782 seconds
[DEBUG   ] Could not determine init system from command line: (/bin/bash)
[INFO    ] Although 'dmidecode' was found in path, the current user cannot execute it. Grains output might not be accurate.
[DEBUG   ] LazyLoaded zfs.is_supported
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20210616081304251545/new; data = {u'fun': u'runner.state.event', u'fun_args': [{u'pretty': True}], u'jid': u'20210616081304251545', u'user': u'salt', u'_stamp': '2021-06-16T08:13:12.610638'}
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
20210616081333425165	{
    "_stamp": "2021-06-16T08:13:33.426057", 
    "minions": [
        "71f7c506232c"
    ]
}
salt/job/20210616081333425165/new	{
    "_stamp": "2021-06-16T08:13:33.426356", 
    "arg": [], 
    "fun": "test.ping", 
    "jid": "20210616081333425165", 
    "minions": [
        "71f7c506232c"
    ], 
    "missing": [], 
    "tgt": "*", 
    "tgt_type": "glob", 
    "user": "root"
}
salt/job/20210616081333425165/ret/71f7c506232c	{
    "_stamp": "2021-06-16T08:13:33.575278", 
    "cmd": "_return", 
    "fun": "test.ping", 
    "fun_args": [], 
    "id": "71f7c506232c", 
    "jid": "20210616081333425165", 
    "retcode": 0, 
    "return": true, 
    "success": true
}
```

**Comment by sagetherage** [comment]
@rainer042 have you been able to upgrade to a supported version of Salt? and are you still seeing this issue?

Reviewed in Grooming 2021-JUN-21

**Comment by rainer042** [comment]
Thanks for your request. Unfortunately I have little time to go after this issue. For the current salt-master SLES version 12SP5 salt3000 is the latest release. And here I can still reproduce the problem. Sooner or later I will upgrade to SLES15 which has a more recent version of salt. But at the moment there is no time for this upgrade. So it will take some time. Sorry and thanks for reminding me.

**Comment by meaksh** [comment]
@rainer042 could you please provide the output from executing the following in your Salt master:

```console
python -c 'import salt.states.event'
```
as @waynew mentioned in https://github.com/saltstack/salt/issues/56876#issuecomment-626857214, this might bring some more light here. Thanks!

**Comment by rainer042** [comment]
On my salt-master:
```
salt:~ # salt-run state.event pretty=True
'state.event' is not available.
salt:~ # python -c 'import salt.states.event'        # no output
salt:~ # echo $?
0
```

**Comment by rainer042** [comment]
Hello,

in between I migrated my old salt  to a new system mostly by copying /etc/salt and the salt and pillar directories. The new host is SLES15SP3 running salt 3002.2.

The salt-maste ris working fine and the old error has gone now but unfortunately another one has come up, a syntax error:

> 
> salt:~ # salt-run -l debug  state.event pretty=true
> [DEBUG   ] Reading configuration from /etc/salt/master
> [DEBUG   ] Including configuration from '/etc/salt/master.d/pillar.conf'
> [DEBUG   ] Reading configuration from /etc/salt/master.d/pillar.conf
> [DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
> [DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
> [DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.uni-koblenz.de
> [DEBUG   ] Missing configuration file: /root/.saltrc
> [DEBUG   ] Configuration file path: /etc/salt/master
> [WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
> [ERROR   ] Failed to import runners state, this is due most likely to a syntax error:
> Traceback (most recent call last):
>   File "/usr/lib/python3.6/site-packages/salt/loader.py", line 1707, in _load_module
>     mod = spec.loader.load_module()
>   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
>   File "<frozen importlib._bootstrap_external>", line 823, in load_module
>   File "<frozen importlib._bootstrap_external>", line 682, in load_module
>   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
>   File "<frozen importlib._bootstrap>", line 684, in _load
>   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
>   File "<frozen importlib._bootstrap_external>", line 674, in exec_module
>   File "<frozen importlib._bootstrap_external>", line 781, in get_code
>   File "<frozen importlib._bootstrap_external>", line 741, in source_to_code
>   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
>   File "/srv/module/base/runners/state.py", line 11
>     print minion
>                ^
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(minion)?
> [DEBUG   ] Could not LazyLoad state.event: 'state' __virtual__ returned False: Missing parentheses in call to 'print'. Did you mean print(minion)? (state.py, line 11)
> [DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
> [DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
> [DEBUG   ] Sending event: tag = salt/run/20210707175222651822/ret; data = {'success': False, 'return': "'state' __virtual__ returned False: Missing parentheses in call to 'print'. Did you mean print(minion)? (state.py, line 11)", 'retcode': 254, 'fun': 'state.event', 'fun_args': [{'__kwarg__': True, 'pretty': True}], 'jid': '20210707175222651822', '_stamp': '2021-07-07T17:52:22.764841'}
> [DEBUG   ] Closing IPCMessageSubscriber instance
> [DEBUG   ] Closing IPCMessageClient instance
> [DEBUG   ] LazyLoaded nested.output
> 'state' __virtual__ returned False: Missing parentheses in call to 'print'. Did you mean print(minion)? (state.py, line 11)`
> 

the file probably it was installed some time ago with a module i needed but I cannot remember anything specific. The broken file is /srv/module/base/runners/state.py and it looks like this:

>
>  \# Import salt modules
> import salt.client
> 
> def up():
>     '''
>     Print a list of all of the minions that are up
>     '''
>     client = salt.client.LocalClient(__opts__['conf_file'])
>     minions = client.cmd('*', 'test.ping', timeout=1)
>     for minion in sorted(minions):
>         print minion

**Comment by agraul** [comment]
```python
for minion in sorted(minions):
    print minion
```
is the syntax from Python 2, it is not understood by Python 3. In Python 3, `print` is a function and must be called with parentheses:
```python
for minion in sorted(minions):
    print(minion)
```

**Comment by sagetherage** [comment]
@rainer042 did this solve your issue, are we able to close this?

**Comment by sagetherage** [comment]
@rainer042 friendly follow up, did this solve your issue, are we able to close?
reviewed in Backlog Refinement 2021-JUL-26 considering closing

**Comment by rainer042** [comment]
I fixed the syntactically wrong file /srv/module/base/runners/state.py as supposed by @agraul then the syntax error is history but the initial problem is still there:

```
# rpm -qa|grep salt-master
salt-master-3002.2-8.41.8.1.x86_64
# salt-run -l debug state.event pretty=true
[DEBUG   ] Reading configuration from /etc/salt/master
[DEBUG   ] Including configuration from '/etc/salt/master.d/pillar.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/pillar.conf
[DEBUG   ] Including configuration from '/etc/salt/master.d/reactor.conf'
[DEBUG   ] Reading configuration from /etc/salt/master.d/reactor.conf
[DEBUG   ] Using cached minion ID from /etc/salt/minion_id: salt.uni-koblenz.de
[DEBUG   ] Missing configuration file: /root/.saltrc
[DEBUG   ] Configuration file path: /etc/salt/master
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[DEBUG   ] Could not LazyLoad state.event: 'state.event' is not available.
[DEBUG   ] MasterEvent PUB socket URI: /var/run/salt/master/master_event_pub.ipc
[DEBUG   ] MasterEvent PULL socket URI: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/run/20210727072402886129/ret; data = {'success': False, 'return': "'state.event' is not available.", 'retcode': 254, 'fun': 'state.event', 'fun_args': [{'__kwarg__': True, 'pretty': True}], 'jid': '20210727072402886129', '_stamp': '2021-07-27T07:24:02.992736'}
[DEBUG   ] Closing IPCMessageSubscriber instance
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] LazyLoaded nested.output
'state.event' is not available.
```

**Comment by agraul** [comment]
I think the issue is that you have a custom runner that "shadows" the built-in `state` runner. Salt loads your `state` runner  that only knows about `state.up`, but does not load the equally named `/usr/lib/python3.6/site-packages/salt/runners/state.py`. Whey you then try to call `state.event`, Salt can't find it.

If you rename your custom runner to something else, your problem should be gone.

**Comment by rainer042** [comment]
Thanks for the hint. I understand basically what you want to say. But I do not have enough salt knowledge to know how I could identify/find such a custom runner? Any hints for this?

**Comment by agraul** [comment]
The custom runner is the file `/srv/module/base/runners/state.py`. A `mv /srv/module/base/runners/state.py /srv/module/base/runners/mystate.py` should re-enable `salt-run state.event`. You'd then use `salt-run mystate.up` to use the `up` function that is currently in `/srv/module/base/runners/state.py`. Of course you can also use a different name instead of `mystate`.

**Comment by rainer042** [comment]
I renamed the runner in /srv/module/base/runners/state.py and then again tried to call  salt-run state.event pretty=True. This time it worked just fine. The only thing I cannot answer at the moment is where this custom runner came from and where it was/is perhaps needed. I'll have a look if I see errors in the future in case the state.py runner is still used somewhere.
