### ISSUE TITLE
[BUG TypeError when pillar contains number as key

### ISSUE THREAD

**Issue by rbthomp** [saltstack/salt#56909]
**Description**
TypeError when pillar contains number as key.

```[ERROR   ] Nested output failed:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/output/__init__.py", line 43, in try_printout
    printout = get_printout(out, opts)(data, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/output/nested.py", line 217, in output
    lines = nest.display(ret, base_indent, '', [])
  File "/usr/lib/python3.6/site-packages/salt/output/nested.py", line 204, in display
    self.display(val, indent + 4, '', out)
  File "/usr/lib/python3.6/site-packages/salt/output/nested.py", line 204, in display
    self.display(val, indent + 4, '', out)
  File "/usr/lib/python3.6/site-packages/salt/output/nested.py", line 204, in display
    self.display(val, indent + 4, '', out)
  [Previous line repeated 4 more times]
  File "/usr/lib/python3.6/site-packages/salt/output/nested.py", line 189, in display
    keys = sorted(ret)
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Setup**
Pillars:
```
1:
  nested: data
2: 
  nested: data
```

**Steps to Reproduce the behavior**
``` salt-call piller.items```

**Versions Report**
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.18.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core```

**Comment by twangboy** [comment]
Should be fixed by the above PR
