### ISSUE TITLE
[FEATURE] PCS module/state broken for Pacemaker 2.x

### ISSUE THREAD

**Issue by thehunmonkgroup** [saltstack/salt#56924]
**Description**
Debian Buster saw a version change for both their ```pcs``` and ```pacemaker``` packages. Pacemaker moved from 1.x to 2.x, and it looks like some of the related PCS syntax has changed enough to break the current Salt PCS module/state.

**Setup**

I'm running ```2019.2.2``` but there have been no changes of consequence to this module since then.

**Steps to Reproduce the behavior**
 * ```pcs.auth``` is broken because the authentication approach/syntax has changed
 * ```pcs.resource_present``` fails with the following error:
   ```
   [ERROR   ] Command '['pcs', '-f', '/var/cache/salt/minion/pcs/base/cib.cib', 'resource', 'show', 
   'drbd']' failed with return code: 1
   [ERROR   ] stdout:
   ```
   This seems to be because the syntax of ```pcs resource show``` has changed.

**Expected behavior**

That pcs for both the 1.x and 2.x versions of Pacemaker would continue to work.

**Comment by thehunmonkgroup** [comment]
Including some additional context about the two changes I reported, there are undoubtedly more. This is from the ClusterLabs doc for Pacemaker 2.x:  https://clusterlabs.org/pacemaker/doc/en-US/Pacemaker/2.0/html/Clusters_from_Scratch

 * The command has been changed from ```pcs cluster auth```to ```pcs host auth``` (```pcs cluster auth``` still works, but authorizes all nodes in the cluster based on ```corosync.conf```, I think)
 * To avoid confusion whether the ```pcs resource show``` command displays resources' status or configuration, the command has been deprecated. Two new commands have been introduced for displaying resources' status and configuration: ```pcs resource status``` and ```pcs resource config```, respectively.

**Comment by twangboy** [comment]
Maybe try passing `config` in the `show` parameter in your state. It looks like it uses `pcs resource config` now instead of `pcs resource show`. The `show` parameter is configurable.

Not sure where to find all the syntax differences between the two. I found some here, but I'm not sure if this is the right place.

https://github.com/ClusterLabs/pacemaker/blob/master/doc/pcs-crmsh-quick-ref.md

**Comment by q1x** [comment]
Hitting this as well as Debian 10 ships Pacemaker 2.x by default.

**Comment by ocfmatt** [comment]
Redhat/CentOS 8.X HA repos ship Pacemaker 2.X so these run into the same problem too.
