### ISSUE TITLE
pkg.installed error too verbose when http connection is unavailable

### ISSUE THREAD

**Issue by H20-17** [saltstack/salt#56952]
**Description**

I have some minions behind a firewall that cannot connect to https://repo.saltstack.com. When pkg.installed is invoked to install a package from an https server, but the server cannot be reached, we get a big stacktrace instead of just an error message. 

**Setup**
Here is one hypothetical sls file which could be called _housekeeping.sls_:

```
salt minion installed:
    pkg.installed:
      - name: salt-minion-py3
      - version: "3000.1"
```

**Steps to Reproduce the behavior**

1. Start with a windows minion running salt version 3000 py3 and be sure that the minion cannot connect via https to _repo.saltstack.com_. Firewalling is one way to do this.

2. Apply the above sls file with something like
    ``` 
    salt-call state.apply housekeeping
    ```
3. You will see output like this

```    
         ID: salt minion installed
    Function: pkg.installed
        Name: salt-minion-py3
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\state.py", line 1981, in call
                  **cdata['kwargs'])
                File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\loader.py", line 1977, in wrapper
                  return f(*args, **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\states\pkg.py", line 1769, in installed
                  **kwargs)
                File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\win_pkg.py", line 1563, in install
                  cached_pkg = __salt__['cp.cache_file'](installer, saltenv)
                File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\modules\cp.py", line 517, in cache_file
                  result = _client().cache_file(path, saltenv, source_hash=source_hash)
                File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\fileclient.py", line 193, in cache_file
                  path, '', True, saltenv, cachedir=cachedir, source_hash=source_hash)
                File "c:\salt\bin\lib\site-packages\salt-3000-py3.5.egg\salt\fileclient.py", line 700, in get_url
                  raise MinionError('Error: {0} reading {1}'.format(query['error'], url))
              salt.exceptions.MinionError: Error: HTTP 599: Timeout while connecting reading https://repo.saltstack.com/windows/Salt-Minion-3000.1-Py3-AMD64-Setup.exe
     Started: 13:15:13.946101
    Duration: 38125.01 ms
     Changes:
```

**Expected behavior**
Ideally we might just report the exception string instead of having the whole stack trace in the comment.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 3.0.2
         Jinja2: 2.10.1
        libgit2: 0.28.2
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.7 (default, Mar 13 2020, 10:23:39)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 31 Thirty One
         locale: UTF-8
        machine: x86_64
        release: 5.6.6-200.fc31.x86_64
         system: Linux
        version: Fedora 31 Thirty One
```
</details>

**Comment by twangboy** [comment]
If we could guarantee that that would be the only error we would ever see from that function I could understand cleaning up the stack trace. However, I find the stacktrace useful when troubleshooting problems. I modified the code to return the following:
```
          ID: salt minion installed
    Function: pkg.installed
        Name: salt-minion-py3
      Result: False
     Comment: The following packages failed to install/update: salt-minion-py3=3000.1
              Error: [Errno 11001] getaddrinfo failed reading https://repo.saltstack.com/windows/Salt-Minion-3000.1-Py3-AMD64-Setup.exe
     Started: 14:14:37.614306
    Duration: 679.447 ms
     Changes:
```
Though it looks nice, I have no idea where that error is coming from. From your stacktrace I can see that it's coming from the fileclient and I can further troubleshoot.
@dwoz @garethgreenaway @cmcmarrow Do you guys have any opinions on this?

**Comment by twangboy** [comment]
I was grossly mistaken. Software is for Users not Developers. The above PR should address the issue.

**Comment by H20-17** [comment]
@twangboy, I've got an open mind.... If I'm wrong I'm wrong..... My thinking is just that often, yes, non developers see the output of state runs. That thought is what actually motivated the bug report. Sometimes, yes, a stacktrace may be ideal, but I'm not sure that stacktraces are a good thing in situtations with really _typical_ problems. Lack of a network connection is, to my mind, in the category of typical things that can go wrong.

**Comment by H20-17** [comment]
BTW, since the Covid lockdown started, every user has gone remote, which changed everything. Spefically they don't have an always-up vpn connection to active directory (perhaps they should, but the decision is not mine). That's when I decided that I'm seeing too many stack traces in the state run output, and you are right, it's _other non developer users_ who I don't want seeing stack traces, especially if I log the output and save it places. It certainly wouldn't look good in a meeting to present everyone else with output containing all kinds of stack traces. You might be able to convince _me_ that it's normal, but, yeah, I don't think it's good optics for the world in general.

**Comment by H20-17** [comment]
BTW, if you wish to revert the commit, I will be understanding of your position and I won't fight it. It's up to you.
