### ISSUE TITLE
[FEATURE] Unable to specify Splunk HEC Port for Splunk returner

### ISSUE THREAD

**Issue by jynolen** [saltstack/salt#56976]
**Description**
The returner splunk doesn't take the port of the splunk endpoint as parameter.
The get_options doesn't not retrieve the port from config file.

**Additional context**
For managed splunk instance the port used is 443 not 8088

**Comment by twangboy** [comment]
Looks like 8088 is hardcoded... we'll need to add the ability to specify a port.

**Comment by knine** [comment]
Any movement on this? It's been two years and I could really use this as a configurable option instead of having change the code open-heart-surgery style (or fork and make a custom returner). Would be nice if it was just a configurable option in the pillar data.

**Comment by larrys** [comment]
To clarify the original report, by managed Splunk instances, it is Splunk Cloud, not Splunk Enterprise running on prem. Even with on prem, you could put nginx/apache in front of the 8088 port on 443 to proxy to a cluster of indexers running HEC, and still need to override the port.
