### ISSUE TITLE
[BUG] Unable to install salt-ssh on windows

### ISSUE THREAD

**Issue by devagupt** [saltstack/salt#56982]
**Description**
I am trying to install salt-ssh module in windows. However, it is unable to install it using pip command. 

**Setup**
OS- Windows
Python - Python 3.5.3
Command - pip install salt-ssh==2019.2.3
Output - Trimmed output for building wheel step

> running install
running download-windows-dlls
Downloading libeay32.dll to c:\python35\libeay32.dll from https://repo.saltstack.com/windows/dependencies/64/libeay32.dll
error: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:720)>
----------------------------------------
ERROR: Failed building wheel for salt-ssh

Can you please explain how to resolve this error or I have to install salt through source on windows as mentioned [here](https://docs.saltstack.com/en/master/topics/installation/windows.html#building-and-developing-on-windows).

**Comment by twangboy** [comment]
Salt ssh isn't currently supported on Windows. It is an enterprise offering. It's quite different on Windows as it uses WinRM under the hood. You can't build it from open.

**Comment by devagupt** [comment]
Thanks for the info.
In that case I will be doingg source install of salt on windows. Can you please share the time when we can expect salt ssh to be supported on windows.
