### ISSUE TITLE
[BUG] Output of salt-call --version is different in 3000.2

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#57035]
**Description**
Output of salt-call --version is different in 3000.2

**Setup**
salt-call --version output on different versions:
```
mac-bld26.ci.mac.saltstack.net:
    salt-call 3000.2
mac-bld24.ci.mac.saltstack.net:
    salt-call 2019.2.3 (Fluorine)
```

@Ch3LL said this was low priority but to submit it as a bug so we can track it.

**Comment by anilsil** [comment]
Wont Fix
