### ISSUE TITLE
network.managed fails unexpectedly on el8

### ISSUE THREAD

**Issue by gandihar** [saltstack/salt#57047]
**Description**
Using network.managed on an EL8 box fails. It shows that it will remove all rules from the network config, then nothing happens. It works fine if I copy the rh7_eth.jinja template to rh8_eth.jinja in $PYTHON_SITE_PACKAGES/salt/templates/rh_ip/rh8_eth.jinja

**Steps to Reproduce the behavior**
Any rules applied through network.managed on an el8 box fail but the exact same rules on an el7 box work.

**Expected behavior**
For the network to re-configure and restart, like it does on other EL platforms.

**Example**
(minion):
----------
          ID: network-settings-ens3
    Function: network.managed
        Name: ens3
      Result: None
     Comment: Interface ens3 is set to be updated:
              --- 
              +++ 
              @@ -1,15 +0,0 @@
              -DEVICE="ens3"
              -UUID="af5c7ed0-7380-45f0-9be4-2934cffddcab"
              -USERCTL="no"
              -TYPE="Ethernet"
              -BOOTPROTO="none"
              -ONBOOT="yes"
              -IPV4_FAILURE_FATAL="yes"
              -IPADDR="192.168.1.80"
              -PREFIX="24"
              -GATEWAY="192.168.1.1"
              -IPV6INIT="yes"
              -IPV6_AUTOCONF="yes"
              -IPV6_DEFROUTE="yes"
              -DEFROUTE="yes"
              -NM_CONTROLLED="no"
     Started: 23:36:03.584422
    Duration: 12.23 ms
     Changes:   

**Versions Report**
Salt Version:
           Salt: 2019.2.4
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.2.5
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  2 2020, 13:16:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core

**Additional context**
As stated, I have been able to work around this by copying $PYTHON_SITE_PACKAGES/salt/templates/rh_ip/rh7_eth.jinja to $PYTHON_SITE_PACKAGES/salt/templates/rh_ip/rh8_eth.jinja. EL7 and EL8 network configs work the same, so this works. However the next Salt upgrade will break my workaround.

**Comment by waynew** [comment]
@gandihar thanks for opening this! Looks like it was just this missing line. I've opened a PR re-adding it.
