### ISSUE TITLE
[BUG] state/host.present and alias-assignment to multiple IPs fails

### ISSUE THREAD

**Issue by b-a-t** [saltstack/salt#57046]
**Description**

I'm basically re-opening #29313 again, as amusingly, 5 year later it was closed the same problem is again there.

**Setup**

Simple `init.sls`:
```
/etc/hosts-1:
  host.present:
    - ip: '127.0.0.1'
    - names:
      - localhost
      - localhost.localdomain
      - localhost4
      - localhost4.localdomain4

/etc/hosts-2:
  host.present:
    - ip: '::1'
    - names:
      - localhost
      - localhost.localdomain
      - localhost6
      - localhost6.localdomain6
```

**Steps to Reproduce the behavior**

Running the given SLS spits the following warnings:
```
Warnings:
Host localhost present for IP address ::1. To get rid of this warning, either run this state with 'clean' set to True to remove localhost from ::1, or add ::1 to the 'ip' argument.
00:09:16.276746 [   1.58 ms]       host.present    Clean     Name: /etc/hosts-1
Warnings:
Host localhost.localdomain present for IP address ::1. To get rid of this warning, either run this state with 'clean' set to True to remove localhost.localdomain from ::1, or add ::1 to the 'ip' argument.
00:09:16.300695 [  0.738 ms]       host.present    Clean     Name: /etc/hosts-1
00:09:16.323678 [  0.728 ms]       host.present    Clean     Name: /etc/hosts-1
00:09:16.350898 [  0.791 ms]       host.present    Clean     Name: /etc/hosts-1
Warnings:
Host localhost present for IP address 127.0.0.1. To get rid of this warning, either run this state with 'clean' set to True to remove localhost from 127.0.0.1, or add 127.0.0.1 to the 'ip' argument.
00:09:16.374525 [  0.771 ms]       host.present    Clean     Name: /etc/hosts-2
Warnings:
Host localhost.localdomain present for IP address 127.0.0.1. To get rid of this warning, either run this state with 'clean' set to True to remove localhost.localdomain from 127.0.0.1, or add 127.0.0.1 to the 'ip' argument.
00:09:16.400794 [  0.693 ms]       host.present    Clean     Name: /etc/hosts-2
00:09:16.424091 [  0.738 ms]       host.present    Clean     Name: /etc/hosts-2
00:09:16.449168 [   0.73 ms]       host.present    Clean     Name: /etc/hosts-2
```

**Expected behavior**

It's expected that there will be no warnings, as the given configuration is perfectly valid.

Despite the warnings the resulting `/etc/hosts` seems to be OK:
```
127.0.0.1               localhost localhost.localdomain localhost4 localhost4.localdomain4
::1                         localhost localhost.localdomain localhost6 localhost6.localdomain6
```
**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```
</details>

**Additional context**

We were seeing the same warnings with the 2018.3.3, 2019.2 and now with 3000.2.

**Comment by waynew** [comment]
Yeah, something is definitely screwy here. Thanks for the report @b-a-t!

**Comment by piterpunk** [comment]
While I was writing a patch to this issue, I found that the `ip` field is a list and you can set the same hostname to multiple IPs setting the different IPs as multiple items in the list. So, to assign the name `localhost` and `localhost.localdomain` to `127.0.0.1` and `::1` the declaration should be:
```
/etc/hosts-12:
  host.present:
    - ip:
      - '127.0.0.1'
      - '::1'
    - names:
      - localhost
      - localhost.localdomain
```
To have the same results of the initial state and avoiding the warnings the following state can be used:
```
/etc/hosts-12:
  host.present:
    - ip:
      - '127.0.0.1'
      - '::1'
    - names:
      - localhost
      - localhost.localdomain

/etc/hosts-1:
  host.present:
    - ip: '127.0.0.1'
    - names:
      - localhost4
      - localhost4.localdomain4

/etc/hosts-2:
  host.present:
    - ip: '::1'
    - names:
      - localhost6
      - localhost6.localdomain6
```
The patch that I was doing would compare if the current entry in `/etc/hosts` is IPv4 and allow to add IPv6 without warning and vice-versa. But it seems that already exists an way to do that.

What is better to do? Clarify the documentation stressing that you can have multiple IPs in the the `ip` field on state? Add the test for IPv4/IPv6? Do both?

I am inclined to only clarify the documentation.

**Comment by b-a-t** [comment]
Thank you, @piterpunk for looking into this case and finding out what we, seems, missed from the documentation.

> I am inclined to only clarify the documentation.

After testing your suggestion in our environment and see clean output first time in 3 years I agree that clarification of the documentation would be enough. Apparently, current one isn't clear in that regards.

As RedHat/CentOS is pretty popular platform may I suggest to include given block into the examples, so people could reproduce the default RH `/etc/hosts` file?

> To have the same results of the initial state and avoiding the warnings the following state can be used:
> 
> ```yaml
> /etc/hosts-localhost:
>   host.present:
>     - ip: ['127.0.0.1', '::1']
>     - names: ['localhost', 'localhost.localdomain']
> 
> /etc/hosts-localhost4:
>   host.present:
>     - ip: '127.0.0.1'
>     - names: ['localhost4', ' localhost4.localdomain4']
> 
> /etc/hosts-localhost6:
>   host.present:
>     - ip: '::1'
>     - names: ['localhost6', 'localhost6.localdomain6']
> ```

Thanks again for solving this long standing mastery!
