### ISSUE TITLE
execute sls rule and take conditional action

### ISSUE THREAD

**Issue by Vox1984** [saltstack/salt#57065]
**Is your feature request related to a problem? Please describe.**
I want to have saltstack sls rule that periodically executes bash command. Depending on the command output, I want to send notification.

**Describe the solution you'd like**
I want to have some salt keyword in .sls rule that sends out notifications

**Describe alternatives you've considered**
Python script conditionally calling out salt-run

>  salt-run mattermost.post_message message='Test'

**Comment by waynew** [comment]
Hi @Vox1984 thanks for the request! I'm pretty sure this already exists: https://docs.saltstack.com/en/master/ref/states/all/salt.states.schedule.html

If that doesn't suit your needs please update this issue and let me know!
