### ISSUE TITLE
Redis KeyError since 2019.2.1

### ISSUE THREAD

**Issue by cerberek** [saltstack/salt#57069]
### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

Redis part of master config.
cache.redis.host: 10.120.0.1
cache.redis.port: 6379
cache.redis.db: '0'
cache: redis

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

If we upgrade our salt-master entity to version bigger than 2019.2.0 we have issue with redis cache and getting lot of `KeyError`. 
All never versions have this behavior.

2020-05-04 13:22:51,015 [
In highstate I can see that it's failing one our pillar.
`    Comment: Unable to manage file: Jinja variable 'salt.utils.context.NamespacedDictWrapper object' has no attribute 'warning'`

```salt.master      :1879][ERROR   ][34391] Error in function _mine:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1872, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1441, in _mine
    return self.masterapi._mine(load, skip_verify=True)
  File "/usr/lib/python3/dist-packages/salt/daemons/masterapi.py", line 652, in _mine
    data = self.cache.fetch(cbank, ckey)
  File "/usr/lib/python3/dist-packages/salt/cache/__init__.py", line 180, in fetch
    return self.modules[fun](bank, key, **self._kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1248, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'redis.fetch'
2020-05-04 13:22:54,826 [salt.master      :1879][ERROR   ][34405] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1872, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1583, in _pillar
    'pillar': data})
  File "/usr/lib/python3/dist-packages/salt/cache/__init__.py", line 156, in store
    return self.modules[fun](bank, key, data, **self._kwargs)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1248, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'redis.store'```

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
Salt-minions are 2019.2.3/4
Salt-master:
`Salt Version:
           Salt: 2019.2.0
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
          ioflo: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.16 (default, Apr  6 2019, 01:42:57)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
           RAET: Not Installed
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 5.1.1
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.0 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-5-amd64
         system: Linux
        version: debian 10.0 `

**Comment by garethgreenaway** [comment]
@cerberek Thanks for the report.  A couple question, can you confirm that you have the python-redis  library installed on the Salt master.  If you have the `cluster_mode` option enabled, can you confirm that you have the `redis-py-cluster` package library installed?  Thanks!

**Comment by cerberek** [comment]
Hi, we are not running redis in cluster_mode. And python-redis is intalled in version 3.2.1-2.
What I think is that this issue is related with another redis case you have open here https://github.com/saltstack/salt/issues/54734

**Comment by garethgreenaway** [comment]
@cerberek Thanks for the response.  I just noticed you're using Python 2 and my testing was done using Python 3, will retest with Python 2 to try and reproduce.  Thanks!

**Comment by garethgreenaway** [comment]
@cerberek A fresh install of Debian 10 running Python 2, I haven't been able to reproduce this one.  Typically a key error from the Salt loader means that the module in question isn't available because checks in the `__virtual__` function didn't pass, these are usually checks to ensure certain libraries are installed.

**Comment by cerberek** [comment]
System default is python 2, but Salt on Debian Buster is available only as Python 3, so i expect that install of salt-master is able to install python 3 dependencies and call python 3 libraries. Which libraries are missing here?

**Comment by garethgreenaway** [comment]
@cerberek I ended up using the Debian 9 APT information to get around the Python2 / Python3 issue, but the packages you'll want would be python-redis for Python2 and python3-redis for a Python3 install.

**Comment by cerberek** [comment]
Yes it was missing python3-redis library. Thanks for help.

**Comment by garethgreenaway** [comment]
Awesome.  Glad you got it all figured out.
