### ISSUE TITLE
[BUG] Ubuntu installation instructions link to Python 2.7 version by default

### ISSUE THREAD

**Issue by philraj** [saltstack/salt#57135]
**Description**
The Ubuntu installation instructions for the official repository at https://docs.saltstack.com/en/master/topics/installation/ubuntu.html#installation-from-the-official-saltstack-repository link to the instructions for the Python 2.7 version by default. Once you land on the repository instructions page at https://repo.saltstack.com/#ubuntu, the only indication you're installing the deprecated version is the `PY2` string in the light blue heading, since neither the URL nor the appearance of the different version tabs change to reflect which version you're looking at, and the repository URL has no version number in it. You also can't link people to the Python 3 instructions, because it doesn't update the URL when you view that tab.

**Expected behavior**
It should link to the Python 3 version by default, since 2.7 is beyond EOL. The https://repo.saltstack.com/#ubuntu page should default to viewing the Python 3 tab, and changing tabs should change the URL to allow linking.

**Screenshots**
![image](https://user-images.githubusercontent.com/16470658/81322724-60982580-9062-11ea-943c-fce04666c733.png)

**Comment by waynew** [comment]
@bryceml Would this be one for you?

**Comment by barbaricyawps** [comment]
This issue should be resolved now that the instructions on repo.saltproject.io have been replaced by the instructions on the Salt Install Guide: https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html

3003 is reaching extended life support at the end of September, so we won't migrate those install instructions over, but we'll migrate the 3004 instructions over soon.
