### ISSUE TITLE
[BUG] Output is not always formatted correctly

### ISSUE THREAD

**Issue by gigi206** [saltstack/salt#57145]
**Description**
Sometimes, the output is not correctly formatted:
See https://travis-ci.org/github/gigi206/VSCode-Anywhere/builds/684425088#L15814 (line 15814)

It seems that saltstack is not able to handle unicode characters.

**Setup**
Install [brew](https://brew.sh) on Linux.

**Steps to Reproduce the behavior**
Run the following command:
```
salt-call state.single pkg.installed php provider=mac_brew_pkg
```

**Versions Report**
```
salt --versions-report
Salt Version:
           Salt: 3000.1
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.7.3
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Jul  2 2019, 20:43:20)
   python-gnupg: Not Installed
         PyYAML: 5.1.1
          PyZMQ: 18.0.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 32 Thirty Two
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 5.6.8-300.fc32.x86_64
         system: Linux
        version: Fedora 32 Thirty Two
```

**Comment by gigi206** [comment]
Seems to be a duplicate of #55931

**Comment by DmitryKuzmenko** [comment]
Yes it's a duplicate. You both have an ASCII system encoding this is the reason Salt can't properly show unicode characters. This is not meaning you should to feel this pain. We have to work it around.
Thank you for report. this report is already linked with #55931 so I'm closing this as a duplicate.
