### ISSUE TITLE
[BUG] grain 'virtual' is 'physical' instead of 'xen' on CentOS 7 (salt 2019.2.4)

### ISSUE THREAD

**Issue by mschiff** [saltstack/salt#57146]
**Description**
On a xen domU running centos 7 the 'virtual' grain is 'physical' instead of 'xen'

**Setup**
default setup, packages from repo.saltstack.com

**Steps to Reproduce the behavior**
```
salt-call grains.item virtual
```

**Expected behavior**
result must be 'xen', not 'physical'

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.4

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.4.2
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 4.9.112-32.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core
```
</details>

**Additional context**

This is a working patch:

```
--- /usr/lib/python3.6/site-packages/salt/grains/core.py.orig   2020-01-08 17:34:22.000000000 +0100
+++ /usr/lib/python3.6/site-packages/salt/grains/core.py        2020-05-08 00:09:59.095832356 +0200
@@ -792,7 +792,7 @@
                 break
         elif command == 'virt-what':
             try:
-                output = output.splitlines()[-1]
+                output = output.splitlines()[0]
             except IndexError:
                 pass
             if output in ('kvm', 'qemu', 'uml', 'xen', 'lxc'):
```

when salt is using the 'virt-what' command, it will parse the multiline output but uses the last line (of two) instead of the first line to compare against the list of hypervisors.

The output of 'virt-what' is 'xen\nxen-domU'

**Comment by erwindon** [comment]
The man-page of `virt-what` does not specify the order in which the properties of a system are produced.
(in my version of virt-what:) in the output for a xen system, the first line is "xen", the second line is "xen-hvm", "xen-dom0" or "xen-domU" or there may not be a second line.
On my system, `virt-what` returns "virtualbox" and "kvm". So "kvm" is part of the response, but only as the second line.
My conclusion is that neither solution is correct and all output lines should be considered instead of just one.

**Comment by DmitryKuzmenko** [comment]
@erwindon thank for the report and analyze.
I agree with you and your bug points to the same part of the code as #56885 
I propose to close this one in favor of the earlier bug #56885 
BTW your comment makes sense. Accordingly to the documentation virt-what just prints facts that it could determine. There's no guarantees about the order so we don't have to take the last one but should lookup interesting for us instead.
