### ISSUE TITLE
Does saltstack support installation in win Server 2003 system？

### ISSUE THREAD

**Issue by zhengwei19003** [saltstack/salt#57173]
Does saltstack support installation in win Server 2003 system? If so, which version of Python 2 or Python 3 is required?Cannot find salt minion in service after installing 2019.2.

**Comment by DmitryKuzmenko** [comment]
@twangboy @dmurphy18 could you please follow this up?

**Comment by twangboy** [comment]
The current iterations of Salt do not support Windows Server 2003 / Windows XP. There have been changes to underlying dependencies that no longer support those systems. I doubt you could even get a minion to start without disabling many things in salt... some grains come to mind. I would imagine you would have to go back as far as 2015.8 versions of salt before you would find something that would even run on Windows Server 2003.
