### ISSUE TITLE
[BUG]centos 7.6, install salt-minion-3000.2 from yum repository will lead os failed to boot(emergency mode)

### ISSUE THREAD

**Issue by echo-of-wind** [saltstack/salt#57171]
**Description**
centos 7.6, install salt-minion-3000.2 from yum repository will lead os failed to boot(emergency mode)

**Setup**
centos 7.6, yum install salt-minion

**Steps to Reproduce the behavior**
centos 7.6, yum install salt-minion from 3000.2 python2 repository

**Expected behavior**
boot normally

**Screenshots**
![emergency mode](https://user-images.githubusercontent.com/24787387/81460956-42096a00-91db-11ea-8f8d-4594e1698ad9.png)

**Versions Report**
salt-3000.2-1.el7.noarch.rpm
salt-minion-3000.2-1.el7.noarch

**Additional context**
polkit.service and initrd-switch-root.service failed to start, then the bootup process drop into emergency mode

**Comment by echo-of-wind** [comment]
related to systemd

**Comment by dropbrick** [comment]
@echo-of-wind is there a workaround ? How did you fix CentOS ? Having the exact same issue.

**Comment by dropbrick** [comment]
yum update to 7.8 fixed it.
