### ISSUE TITLE
[BUG] Ubuntu 20.04 py3 minion fails to execute jobs due to missing grain os_family

### ISSUE THREAD

**Issue by darkpaw** [saltstack/salt#57194]
**Description**

A fresh Python3 minion install on Ubuntu 20.04 fails to execute jobs from the master.

**Setup**
Using this repo:
 deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/3000 bionic main

**Steps to Reproduce the behavior**
sudo salt minion_id test.ping
minion_id:
    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code

In minion log is the Python exception:

  File "/usr/lib/python3/dist-packages/salt/utils/schedule.py", line 99, in __new__
    instance.__singleton_init__(opts, functions,
  File "/usr/lib/python3/dist-packages/salt/utils/schedule.py", line 152, in __singleton_init__
    self.time_offset = self.functions.get('timezone.get_offset', lambda: '0000')()
  File "/usr/lib/python3/dist-packages/salt/modules/timezone.py", line 234, in get_offset
    if 'AIX' not in __grains__['os_family']:
  File "/usr/lib/python3/dist-packages/salt/utils/context.py", line 236, in __getitem__
    return self._dict()[key]
KeyError: 'os_family'

**Expected behavior**

minion_id:
    True

**Versions Report**
Master : 
Salt Version:
           Salt: 3000.2

sudo salt minion_id test.version
minion_id:
    3000.2
 
**Additional context**

Manually adding the grain "os_family: linux" to /etc/salt/grains worked, but it looks like it's intended to be automatically generated?

**Comment by OrangeDog** [comment]
Already fixed by #56031 and #56896

**Comment by DmitryKuzmenko** [comment]
Thank you @OrangeDog !
@darkpaw could you please confirm and close the issue?

**Comment by darkpaw** [comment]
I'm not sure that #56031 would have fixed this as I didn't see that import error, but I will close and retest another time.

**Comment by OrangeDog** [comment]
I put together this patch for 3000.x on py38. It seems to be working.
https://gist.github.com/OrangeDog/b3c6a0a577ebcaa90d578941e198ac87

**Comment by darkpaw** [comment]
Thanks @OrangeDog I just tried master from source and that is fine, not sure if that's ahead or behind 3000.2 but grains/core/py does have your chicken and egg imports section from the patch.

**Comment by OrangeDog** [comment]
@darkpaw master is way ahead, so keep an eye out for other bugs that have slipped into it.

**Comment by DmitryKuzmenko** [comment]
@OrangeDog thank you one more time! You're awesome.
