### ISSUE TITLE
[BUG] win_network.ping and network.ping unnecessarily returning with non-zero exit code

### ISSUE THREAD

**Issue by H20-17** [saltstack/salt#57191]
**Description**
When I call _win_network.ping_ on a Windows machine with the value of _return_boolean_ set to _True_, when the return value is _False_ it also returns with a non-zero exit code. Perhaps this is reasonable when it fails to ping and you are not returning a boolean. When it is supposed to just return a boolean and fails to ping, I don't consider this to be an error condition per se. It should just return false and it should have a non-zero exit code.

The same thing happens with Linux machines.

It should just return false with a zero code exit when pinging fails (or the hostname does not resolve).

**Setup**
No specific setup

**Steps to Reproduce the behavior**

Issue a command like
```
salt -t 50 my_minion network.ping nonexistanthost return_boolean=True
```
The result will be:
```
my_minion:
    False
ERROR: Minions returned with non-zero exit code
```

**Expected behavior**
We should have the same behaviour but the exit code should just be 0. From the point of view of the user a return value of False is sufficient, and no error has ocurred.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3000.2
 
Dependency Versions:
           cffi: 1.12.3
       cherrypy: Not Installed
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 3.0.2
         Jinja2: 2.10.1
        libgit2: 0.28.2
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.28.2
         Python: 3.7.7 (default, Mar 13 2020, 10:23:39)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: fedora 31 Thirty One
         locale: UTF-8
        machine: x86_64
        release: 5.6.7-200.fc31.x86_64
         system: Linux
        version: Fedora 31 Thirty One
```
</details>

**Comment by waynew** [comment]
This would be entirely inconsistent with the way ping works:

```
$ ping -c1 asdfpaosidujfa.com
ping: asdfpaosidujfa.com: Name or service not known
$ echo $?
2
$ ping -c1 203.0.113.1
PING 203.0.113.1 (203.0.113.1) 56(84) bytes of data.

--- 203.0.113.1 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms
$ echo $?
1
```
These are non-zero exit codes, and Salt correctly interprets them as error conditions.

**Comment by H20-17** [comment]
It's a function that's supposed to return True or False. It shouldn't matter what goes on behind the scenes.....that was my entire point. 

Supposing in powershell if I issue the command
```
Test-Connection blah -Quiet
```
and it returns false, does it set the exit code to non-zero? No it doesn't. It just does its job and answers the question, just as network.ping ought to do.

**Comment by H20-17** [comment]
@waynew Can this be reopened so others can weigh on on this before it gets closed again?

**Comment by waynew** [comment]
This is just how salt works in general - https://docs.saltstack.com/en/latest/topics/return_codes/index.html if something returns False that is equivalent to a non-zero exit code.

Unless I'm completely misunderstanding what you're asking - because what you're describing is something that works different from how Salt works. Am I missing something?

What is the major problem with this return not being successful? Are you just wanting to know information but not act on it at all?

**Comment by H20-17** [comment]
@waynew when the value of the return_boolean parameter is _False_, it makes some sense that a non-zero exit code will be returned to signify failure (when pinging fails). When the _return_boolean_ parameter_ is set to _True_ and the function returns _False_, that is all the function should do. The return value of _False_ should not be accompanied by any kind of theatrics. It's being asked question and answering _True_ or _False_ is all it should do, unless some problem prevents it from returning a meaningful result (in which case a non-0 exit code makes sense).

Once again I ask that this issue be reopened and others on the salt team be asked about this.

And you said

> if something returns False that is equivalent to a non-zero exit code.

Right, so why does the function do both things instead of just one?
