### ISSUE TITLE
[BUG] warning in SALT-API may become error in future

### ISSUE THREAD

**Issue by erwindon** [saltstack/salt#57228]
**Description**
Starting with browser FireFox version 76, a warning is shown when the SALT-API is used from a web application.
With my translation from Dutch to English, the message is: "Cookie ‘session_id’ will soon be rejected because the attribute ‘sameSite’ is set to ‘none’ or to an invalid value, without the attribute ‘secure’. Read https://developer.mozilla.org/docs/Web/HTTP/Cookies for more information on attribute ‘sameSite’".
The attribute can be set by the server in its "Set-Cookie" reply.

Even for https sessions, the problem occurs because the "session_id" cookie does not have the "secure" attribute.

**Setup**
Install salt-master and salt-api packages.
No minions are required.
Use an application that uses the salt-api, e.g. SaltGUI.

**Steps to Reproduce the behavior**
Login into the application using http from a FireFox browser, version >= 76.
View the FireFox console and see the message.
Repeat, but now with a https session.

**Expected behavior**
That no warning is given by the browser, but more importantly, that error is raised in the future.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3000.2
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: 3.4.1
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10.4 
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-9-amd64
         system: Linux
        version: debian 10.4 
```
</details>

**Comment by whytewolf** [comment]
closing this as we don't support firefox accessing the api directly.
