### ISSUE TITLE
Local salt-call path different than salt call from master

### ISSUE THREAD

**Issue by Laserwhit** [saltstack/salt#57242]
### Description of Issue
Calling from salt-call locally succeeds while calling from master using salt 'specific_machine' fails because the paths/envs are different.  I apologize if this is expected behavior.  I was unable to find information on the web for this and I clearly did NOT EXPECT this so it is not expected behavior to me and seems new with version 3000.2. 

### Setup
Centos 7 machine create a script in /etc/profile.d/xxx that adds to the path.
Then just check paths from both sides (local and from master):
MASTER
```
salt 'slvmctl12*' cmd.run 'echo $PATH'
slvmctl12.a:
    /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin
```
vs
LOCAL
```
salt-call cmd.run 'echo $PATH'
local:
    /usr/lib64/qt-3.3/bin:/opt/rh/rh-python36/root/usr/bin:/opt/rh/rh-git29/root/usr/bin:/usr/local/sbin:/usr/local/bin:/sbin:/bin:/usr/sbin:/usr/bin:/root/bin
```

### Steps to Reproduce Issue
On Centos 7, add setup script to /etc/profile.d/xxx that adds paths to your system.  Then check the paths as shown above.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
LOCAL (MINION) VERSION INFO:
salt-call --versions-report
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.14
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.2.5
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.9.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

MASTER VERSION INFO:
salt --versions-report
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Apr 12 2017, 06:56:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.3.1611 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-514.el7.x86_64
         system: Linux
        version: CentOS Linux 7.3.1611 Core

**Comment by whytewolf** [comment]
This is the expected behavior. 

The difference between the two is the environment they are started in which is where the path comes from.

**Comment by DmitryKuzmenko** [comment]
@Laserwhit I agree with @whytewolf . This is expected. The difference you see is the difference between environments where master and salt-call is running. Try to figure out why your master's environment doesn't contain the `profile.d` scripts results. It's your os administration question, not salt.
If you're satisfied with this answers please close this. If not you're welcome with other questions.

**Comment by Laserwhit** [comment]
Ok, something seems to have changed then in the new 3000.2 version that is preventing env vars from getting setup in the call from master.  But still if this is not an issue I will close :-)  (If I can narrow the issue further compared to previous versions I will open a new ticket specific to that.)

**Comment by DmitryKuzmenko** [comment]
@Laserwhit you're welcome! Feel free to reopen this one or open a new one.
