### ISSUE TITLE
NOTICE file is both misleading and unnecessary

### ISSUE THREAD

**Issue by rjc** [saltstack/salt#57255]
**Description**
A `NOTICE` file has been included with this [commit](https://github.com/saltstack/salt/commit/1dd0e342b5af2501e761a4067e0ceab02f7a6616). As it stands, the text is misleading:

```
Apache SaltStack
Copyright 2014-2019 The Apache Software Foundation

This product includes software developed at
The Apache Software Foundation (http://www.apache.org/).
```

As it stands, the text is misleading as it attributes SaltStack's copyright to The Apache Software Foundation and calls the software `Apache SaltStack` - I check the ASF web pages and there's no sight of Salt being an Apache project.

Also, NOTICE file isn't at all necessary, unless you are an official ASF project (source https://www.apache.org/legal/src-headers.html):

```
Does this policy apply to projects outside the ASF that use the Apache License?

No. This is strictly an ASF policy. Other projects using the Apache License should still refer to the license's appendix for guidance on applying a header to their source files.
```

**Comment by DmitryKuzmenko** [comment]
@rjc thank you for poining this out. I need to request other to answer.
That file is introduced by @cachedout here https://github.com/saltstack/salt/pull/49979 and it's approved by @thatch45.

**Comment by cachedout** [comment]
I agree that this this is misleading and should be amended or removed.

**Comment by DmitryKuzmenko** [comment]
@rjc will you create a PR for this?

**Comment by DmitryKuzmenko** [comment]
@cachedout thank you for explining.

**Comment by rjc** [comment]
@DmitryKuzmenko My PR would be simply to delete said file :^)

However, if you would like to retain it, for one reason or another, then it needs to be fixed. I'm afraid that I don't know enough about all of the Salt's code copyright, 3rd-party components which might have been incorporated into it and/or their licenses, etc. in order to even attempt to compile such file and it reflecting the reality.

Given that `NOTICE` isn't *required*, my advice would be simply to drop it :^)

**Comment by DmitryKuzmenko** [comment]
@rjc please don't hear me wrong. I'm just about keeping your copyright on this finding. If you don't wan't to do this I will. Thank you! =)

**Comment by rjc** [comment]
@DmitryKuzmenko I understand where you're coming from. Here, however, there's no copyright to speak of - we're deleting a file after all, not adding any content - attribution, perhaps. I'm not after any brownie points ;^)

Your PR is fine, BTW. Thanks!
