### ISSUE TITLE
Provide a MOBI version of the Docs

### ISSUE THREAD

**Issue by EugeneKay** [saltstack/salt#5734]
Please provide a MOBI version of the Offline documentation for compatibility with the Kindle series of ereaders. Converting an ePub comes out usable, but has notable formatting issues and is not a "drag and drop" solution, and PDF is unsupported on the eInk family. Double extra bonus karma points if they could be provided as a $0.00 ebook on the Amazon Kindle store for auto-updating goodness.

**Comment by jacobhammons** [comment]
@EugeneKay I picked this back up again to see if there is any progress around tools, but there hasn't been much in the spinx > mobi tools arena. The latest version of kindlegen isn't converting our epub either.

What does work is Calibre, http://calibre-ebook.com/, which seems to be the preferred tool to convert eBooks for all the different readers already. 

Are you OK if we close this with the recommendation that users download Calibre to get an ebook in a different format? I don't see an easy way for us to provide and test a mobi file with any consistency. Thanks!

**Comment by EugeneKay** [comment]
My understanding is that the direct Sphinx creation of a Mobi is failing, but an ePub-to-Mobi conversion is working OK, via Calibre? I'd prefer to leave it open with a low-to-none priority, as Kindle docs are a great thing. I can put a bit of time into seeing about making it work, or possibly volunteering to do a manual convert+verify for each Release version. If you think it's better Closed, that's fine by me too ;-)

**Comment by Reiner030** [comment]
There is also a command line converting call available so it can be created automatically?
http://manual.calibre-ebook.com/generated/en/ebook-convert.html

**Comment by UtahDave** [comment]
We'll close this until sphinx creation of mobi files improves.

**Comment by Arupbakshi** [comment]
I face the problem, please help if any one knows

Error | E1003: Unknown error in class String.
Error | E3013: More number of characters are hidden using display:none than   allowed limit. Limit: 10000  in file:   10000 line: 10000
Notice | W14028: Following file does not exist :     ../fonts/SourceSansPro-Bold.eot?#iefix
Status | Book conversion failed.
