### ISSUE TITLE
Output fails to compile correctly with saltutil.sync_modules in orchestration

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#57414]
**Description**
I get a "Data failed to compile error" when I run the following orchestration:

```
saltutil.sync_modules:
  salt.function:
    - tgt: '*'
    - saltenv: {{ saltenv }}
```

From what I can tell the modules actually sync and if I use `--out=json` I can see that the output actually comes back as an empty list just fine. However, when using the default highstate outputter I get the following error:

```
              master1:
                  Data failed to compile:
              ----------
                  modules.checkit
              3785e3be9a11:
                  Data failed to compile:
              ----------
                  modules.checkit
              5bebb1c90729:
                  Data failed to compile:
              ----------
                  modules.checkit
```

You can see in the output above that it's listing the module that was synced over, `modules.checkit`.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: 1.0.0
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.2.1
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.6.1810 Core
         locale: UTF-8
        machine: x86_64
        release: 4.19.76-linuxkit
         system: Linux
        version: CentOS Linux 7.6.1810 Core
```
</details>

**Comment by garethgreenaway** [comment]
@doesitblend I believe I found the cause for this.  If you enable the debug level logging you'll see the traceback.

**Comment by garethgreenaway** [comment]
@doesitblend never mind, different issue than another one I was looking at.

**Comment by omegarus** [comment]
I have same problem with 3004.1 version.

**Comment by whytewolf** [comment]
I'm not able to reproduce this in 3006.x or later. if someone can can they create a new ticket with the details. as well as any log files that might help in debugging or tracking where the error is happening.
