### ISSUE TITLE
[BUG]pkg.installed shouldn't return an error when package is already installed

### ISSUE THREAD

**Issue by craigafinch** [saltstack/salt#57421]
**Description**
When using pkg.installed to directly install an RPM (NOT using yum), the state returns an error when the package is already installed and up to date. In other words, the state **returns an error when the system is already in the desired state**. This behavior is inconsistent with the operation of every other Salt state, which returns "clean" when the system is already in the desired state.

**Setup**

```yaml
salt-repo:
  pkg.installed:
    - sources:
      - salt-repo-latest: https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm
```

Actual output:
```
----------
          ID: salt-repo
    Function: pkg.installed
      Result: False
     Comment: Error occurred installing package(s). Additional info follows:

              errors:
                  - Running scope as unit run-382.scope.
                    Loaded plugins: priorities, remove-with-leaves, versionlock
                    Examining /var/cache/salt/minion/extrn_files/base/repo.saltstack.com/yum/redhat/salt-repo-
latest-2.el7.noarch.rpm: salt-repo-latest-2.el7.noarch
                    /var/cache/salt/minion/extrn_files/base/repo.saltstack.com/yum/redhat/salt-repo-latest-2.e
l7.noarch.rpm: does not update installed package.
                    Error: Nothing to do
     Started: 22:59:12.783126
    Duration: 11823.265 ms
     Changes:
```

**Steps to Reproduce the behavior**
salt 'my-host' state.apply --state-output=changes

**Expected behavior**
If the RPM is already present and up to date, the state should return "clean."

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 0.6.4
      gitpython: 1.0.1
         Jinja2: 2.7.2
        libgit2: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  2 2020, 13:16:51)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
          smmap: 0.9.0
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.8.2003 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.el7.x86_64
         system: Linux
        version: CentOS Linux 7.8.2003 Core
```
</details>

Minion is also on 3000.3

**Additional context**

**Comment by garethgreenaway** [comment]
@craigafinch Thanks for the report.  We'll get this fixed asap.

**Comment by piterpunk** [comment]
Hi,

Your state seems to be wrong, "latest" is the version of salt-repo package, not part of its name and the documentation says 

> A list of packages to install, along with the source URI or local path from which to install each package. In the example below, foo, bar, baz, etc. refer to the name of the package, as it would appear in the output of the pkg.version or pkg.list_pkgs salt CLI commands.

The pkg.list_pkgs output:

```
[root@li1060-98 ~]# salt-call pkg.list_pkgs | grep -A1 repo
    salt-repo:
        latest-2.el7
```

Changing the state to:

```
salt-repo:
  pkg.installed:
    - sources:
      - salt-repo: https://repo.saltstack.com/yum/redhat/salt-repo-latest-2.el7.noarch.rpm
```

Fixes this behaviour:

```
[root@li1060-98 states]# date ; salt-call state.apply tststate 
Fri Jun 12 03:54:36 UTC 2020
local:
----------
          ID: salt-repo
    Function: pkg.installed
      Result: True
     Comment: The following packages were installed/updated: salt-repo
     Started: 03:54:40.314927
    Duration: 5657.608 ms
     Changes:   
              ----------
              salt-repo:
                  ----------
                  new:
                      latest-2.el7
                  old:

Summary for local
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   5.658 s
[root@li1060-98 states]# date ; salt-call state.apply tststate
Fri Jun 12 03:54:49 UTC 2020
local:
----------
          ID: salt-repo
    Function: pkg.installed
      Result: True
     Comment: All specified packages are already installed
     Started: 03:54:53.716290
    Duration: 1033.497 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   1.033 s
```

Working as expected

**Comment by craigafinch** [comment]
@piterpunk Thank you for catching that subtle error in my state. I still think there is a Salt bug, though it's a different kind of bug than what I originally reported. The state output is not helpful in catching or troubleshooting the error in my state. Why this state need me to specify the exact package name, when I'm already providing a very specific RPM file that can only represent one package?  If this is meant as a consistency check, then if the package name doesn't match the RPM file specified, the state output should clearly explain that there's an inconsistency.

**Comment by whytewolf** [comment]
closing this as the second issue described is not a planned feature.
