### ISSUE TITLE
service.dead fails on macos catalina [BUG]

### ISSUE THREAD

**Issue by AldarisPale** [saltstack/salt#57436]
**Description**
service.dead is not working on macos catalina.
What happens is that I get "Operation now in progress" and retcode is 36.

**Setup**
demo state:
  service.dead:
    name: org.fusioninventory.agent

**Steps to Reproduce the behavior**
state.apply

**Expected behavior**
Service should be stopped

**Screenshots**
None

**Versions Report**
Can provide probably next week. Salt master is 3000.2, salt minion is 3000.3.
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by weswhet** [comment]
@AldarisPale Thanks for opening the issue. I can confirm this happening. Starting on Catalina the underlying command on `launchctl bootout system/org.fusioninventory.agent` returns an exit code of 36 which salt treats as an error. The state should actually stop the service. If run again it should return no changes/errors. I'll see If we can get a fix in for this that ignores retcode of `36` on Catalina.

**Comment by weswhet** [comment]
The attached PR should fix this and be included in the 3001.1 release.
