### ISSUE TITLE
pki/master/minions store module  

### ISSUE THREAD

**Issue by Deshke** [saltstack/salt#57449]
**Is your feature request related to a problem? Please describe.**

salt currently stores the minion keys as file in the configured pki_dir `/etc/salt/pki/master/minions` this does not scale at 5000 minions+ 

**Describe the solution you'd like**

a distributed pki store, something like a noSQL/keyValue backend for minion keys (redis/memcached/cassandra....)

**Describe alternatives you've considered**
* tmpfs for `pki/` -> reboot => minions gone (but nice high IO)
* gluster  => terrible for small files
* NFS => does also not scale for multiple masters in different regions in the world

**Comment by Deshke** [comment]
links to https://github.com/saltstack/salt/issues/34238 what got somehow sleept on since 2016

**Comment by Akm0d** [comment]
Closing in favor of #34238 which is reopened :+1:
