### ISSUE TITLE
[BUG] MacBookPro14,3 productname grain has a trailing null character

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#57454]
**Description**

For a MacBook Pro with a model identifier of `MacBookPro14,3` (at least), the `productname` grain includes a null character at the end.

**Steps to Reproduce the behavior**

```
$ sysctl -b hw.model
MacBookPro14,3%
```

```
$ sudo salt-call --local cmd.run 'sysctl -b hw.model' pythonshell=true --out=json
{
    "local": "MacBookPro14,3\u0000"
}
```

**Expected behavior**

The value of the `productname` grain would be `MacBookPro14,3` with no trailing null character.

I suppose it could be argued that we should take the value from `sysctl` as is, but it may be reasonable to trim null characters here.

**Versions Report**

Sorry, reporting this second-hand, but here's the code in the current master which suggests this would happen with the current code.

https://github.com/saltstack/salt/blob/310405df2c2a0dafa07b39eb54178d0031ed12ee/salt/grains/core.py#L2760-L2767

**Comment by oeuftete** [comment]
ZD-5071 and ZD-5133.

**Comment by weswhet** [comment]
Can confirm! Thanks for opening the issue. I'm in favor of striping the null character.

**Comment by Akm0d** [comment]
Fixed in [idem-darwin](https://gitlab.com/saltstack/pop/idem-darwin/-/blob/master/idem_darwin/corn/hw/sysctl.py) A strip just needs to be done on the output of `cmd.run`

**Comment by weswhet** [comment]
@Akm0d idem-darwin is slated for Magnesium?

**Comment by oeuftete** [comment]
@Akm0d it's going to need more than just a plain `strip()`, isn't it?

```
In [1]: "MacBookPro14,3\x00".strip()                                                                                         
Out[1]: 'MacBookPro14,3\x00'

In [2]: "MacBookPro14,3\x00".strip("\x00")                                                                                   
Out[2]: 'MacBookPro14,3'
```

**Comment by Akm0d** [comment]
> @Akm0d idem-darwin is slated for Magnesium?

Yes I believe so

**Comment by Akm0d** [comment]
> @Akm0d it's going to need more than just a plain `strip()`, isn't it?
> 
> ```
> In [1]: "MacBookPro14,3\x00".strip()                                                                                         
> Out[1]: 'MacBookPro14,3\x00'
> 
> In [2]: "MacBookPro14,3\x00".strip("\x00")                                                                                   
> Out[2]: 'MacBookPro14,3'
> ```

Oh it looks like the underlying command is different.  Idem-darwin is doing `sysctl -n hw.model` and salt is doing `sysctl -b hw.model`

**Comment by oeuftete** [comment]
ZD-6015.

**Comment by garethgreenaway** [comment]
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.
