### ISSUE TITLE
[BUG] [RC1 Sodium] python 2 deprecation warnings  and halt salt-call

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#57516]
**Description**
Missed deprecation warnings:

 https://github.com/saltstack/salt/blob/master/salt/scripts.py#L106 and https://github.com/saltstack/salt/blob/master/salt/scripts.py#L215-L227

**Comment by waynew** [comment]
Per discussion in the Community Slack, allowing people to even *start* Salt with Python2 is just a bad idea and will cause long-term confusion. We're going to change these to a `sys.exit` line, with some verbage to the effect of:

> ERROR: Python 2 is no longer supported in Salt. Please upgrade to Python 3 to continue receiving updates to Salt.

**Comment by waynew** [comment]
I believe we should also halt on `salt-call`
