### ISSUE TITLE
[BUG] Reactor is unable to read secrets from Vault 

### ISSUE THREAD

**Issue by gediminasz** [saltstack/salt#57512]
**Description**
After upgrading Salt master from Python 2 to 3, we have noticed that our reactor fails to read secrets from Hashicorp Vault with the following error:

```
[salt.loaded.int.module.vault:172 ][ERROR ][150811] Failed to read secret! AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
```

**Setup**
Snippet from Salt master config:

```yml
reactor:
  - 'salt/job/*/ret/*':
    - salt://reactor/deploy/done.sls
```

Snippet from reactor:

```py
#!py

def run():
    ...
    my_secret = __salt__["vault.read_secret"]("path/to/secret", "my_secret")
    ...
```

**Steps to Reproduce the behavior**
1. Make sure Vault is configured on Salt master
2. Invoke a job that would trigger the reactor, any state would do e.g. `salt foo state.apply bar`.
3. Observe error in master logs:

```
[salt.loaded.int.module.vault:172 ][ERROR ][150811] Failed to read secret! AssertionError: PID check failed. RNG must be re-initialized after fork(). Hint: Try Random.atfork()
```

**Expected behavior**
`__salt__["vault.read_secret"]` invoked in a reactor should succeed.

**Screenshots**
None.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: 2.5.1
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-99-generic
         system: Linux
        version: Ubuntu 18.04 bionic
```
</details>

**Additional context**
None.

**Comment by dmurphy18** [comment]
testing it now

**Comment by garethgreenaway** [comment]
@gediminasz Apologies for the delay in responding on this one.  Are you able to invoke `vault.read_secret` module directly not from a reactor?

**Comment by gediminasz** [comment]
`vault.read_secret` definitely worked when used in pillars like so: `{{ salt['vault'].read_secret('secret/my/secret', 'some-key') }}`. Haven't tried calling it via CLI, so can't say much about that.

This is a pretty old issue and in my team we ended up not using the reactor. So as far as I'm concerned, it can be closed :)

**Comment by garethgreenaway** [comment]
@gediminasz Will go ahead and close, if the issue comes up again please let us know.
