### ISSUE TITLE
Add a salt key subsystem

### ISSUE THREAD

**Issue by ryan-lane** [saltstack/salt#5752]
In my environment, we use puppet for config management, and salt for remote execution, deployment, and a number of other things. We want to avoid having two key systems, though. Salt's key system is fairly compatible with puppet's.

On the minion, it's possible to just reuse puppet's public and private keys, assuming salt knows their path. On the master, puppetca stores a PEM encoded X.509 file. It should be possible for the salt master to directly use these files as well, by just extracting the public key from the X.509 file.

To test this, on the minion:

 ln -s /var/lib/puppet/ssl/public_keys/$(hostname -f).pem  /etc/salt/pki/minion/minion.pub
 ln -s /var/lib/puppet/ssl/private_keys/$(hostname -f).pem /etc/salt/pki/minion/minion.pem

And on the master:

 openssl x509 -pubkey -noout -in /var/lib/puppet/server/ssl/ca/signed/<minion>.pem  -out /etc/salt/pki/master/minions/<minion>

Then, restart the minion, and everything works.

Ideally we'd be able to tell salt to use a "puppet key subsystem", then point it at puppet's ssl locations and salt would automatically work when puppet signs keys.

**Comment by marbindrakon** [comment]
I have done some basic work on this in my local fork: https://github.com/marbindrakon/salt/tree/ftr-keystore/salt/key_manager

If this is a direction the project wants to go, I can flesh this out some more and begin converting existing uses of pki_dir. I believe this also ties in with #25700 and #25284.
