### ISSUE TITLE
[BUG] [RC1 Sodium] we can't run on less than pyzmq 17 anymore

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#57532]
**Description**
We only seem to work on pyzmq 17 and newer, can't remember why exactly.  We should update our requirements to a minimum of pyzmq 17.0.0.

**Comment by dmurphy18** [comment]
let me add the requirement for pyzmq >= 19.0.0 for Py 3.8 is also onerous and is there only to make Salt testing with wheels easier.

Fedora 32 ships with python3-zmq v18.1.2, v19.0.0 is in Rawhide
Ubuntu 20.04 ships with 17.1.2-3ubuntu1, again an issue with Py 3.8  and zmq being less than requirements

**Comment by sagetherage** [comment]
@bryceml @s0undt3ch can we close this?

**Comment by s0undt3ch** [comment]
I'll @bryceml handle this since he's the one that worked on it.
