### ISSUE TITLE
[BUG] [RC1 Sodium] remove arista_pyeapi incorrectly states send_command

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#57531]
**Description**
The documentation example on page https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.arista_pyeapi.html

uses '**send_commands**' when it should be '**run_commands**' as stated drop down box and further down the page.

The error is in the bash example box just above the definition of 
salt.modules.arista_pyeapi.call(method, *args, **kwargs)

```
salt '*' pyeapi**.send_commands** 'show version' 'show interfaces'
salt '*' pyeapi.config 'ntp server 1.2.3.4'
```

**Screenshots**
![Screenshot from 2020-05-28 10-08-34](https://user-images.githubusercontent.com/9943204/83649369-55a6b700-a574-11ea-966b-43e8f9956ffd.png)

**Comment by sagetherage** [comment]
assigning to @dmurphy18 to remove Jun 8th
