### ISSUE TITLE
[BUG] lgpo set failing to set 

### ISSUE THREAD

**Issue by wb529kq** [saltstack/salt#57546]
**Description**
When I apply the state `lgpo.set`

results in ...
```
----------
          ID: Set Windows Update
    Function: lgpo.set
      Result: True
     Comment: All specified policies are properly configured
     Started: 16:23:05.024000
    Duration: 4938.0 ms
     Changes:

Summary for dtdeaugas424.md-man.biz
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   4.938 s
```
running salt blah `lgpo.get` shows the correct results..

```
Windows Components\Windows Update\Specify intranet Microsoft update service location:
            ----------
            Download files with no Url in the metadata if alternate download server is set.:
                True
            Set the alternate download server:
                http://blah.xx-xxx.comz:8530
            Set the intranet statistics server:
                http://blah.xx-xxx.com:8530
            Set the intranet update service for detecting updates:
                http://blah.xx-xxx.com:8530
```
however ...

opening the UI  gpedit.msc shows ...
![image](https://user-images.githubusercontent.com/54352944/83769418-1cf40400-a680-11ea-8bdb-79776eef5c31.png)

... and it does not work, however if I cut and paste the URL into the UI and hit apply it works

running the state again shows all well and everything is already configured correctly.

**Setup**
Master is 3000.2 Py3 Minion is 3000.2 Py3

**Steps to Reproduce the behavior**
Run state check gpedit.msc

**Expected behavior**
URL is shown correctly in UI

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Master:
Salt Version:
           Salt: 3000.2

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 3.0.2
      gitpython: 3.0.8
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 15.3.0
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7.7.1908 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.4.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7.7.1908 Core

Minion:
dtdeaugas424.md-man.biz:
    Salt Version:
               Salt: 3000.2

    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.8.1
             pygit2: Not Installed
             Python: 3.5.4 (v3.5.4:3f56838, Aug  8 2017, 02:17:05) [MSC v.1900 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 5.1.2
              PyZMQ: 18.0.1
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2019Server
             system: Windows
            version: 2019Server 10.0.17763 SP0 Multiprocessor Free
```
</details>

**Additional context**
```
Set Windows Update:
  lgpo.set:
    - computer_policy:
        Configure Automatic Updates:
            Configure automatic updating: 3 - Auto download and notify for install
{% if grains['osfinger'] == 'Windows-2019Server' %}
            Every week: False
            First week of the month: True
            Second week of the month: False
            Third week of the month: False
            Fourth week of the month: False
{% endif %}
            Install during automatic maintenance: False
            Install updates for other Microsoft products: False
            Scheduled install day: 2 - Every Monday
            Scheduled install time: 06:00
        Specify intranet Microsoft update service location:
            Set the intranet update service for detecting updates: http://blah.xx-xxx.com:8530
            Set the intranet statistics server: http://blah.xx-xxx.com:8530
            Download files with no Url in the metadata if alternate download server is set.: True
            Set the alternate download server: http://blah.xx-xxx.com:8530
        Windows Components\Windows Update\Do not allow update deferral policies to cause scans against Windows Update: Disabled
```

**Comment by dmurphy18** [comment]
@twangboy Can you take a look at this given its lgpo

**Comment by twangboy** [comment]
So, I just applied the following state:
```
Set Windows Update Service Location:
  lgpo.set:
    - computer_policy:
        Specify intranet Microsoft update service location:
          Set the intranet update service for detecting updates: http://blah.xx-xxx.com:8530
          Set the intranet statistics server: http://blah.xx-xxx.com:8530
          Download files with no Url in the metadata if alternate download server is set.: True
          Set the alternate download server: http://blah.xx-xxx.com:8530
```

I see the following in my gpedit:
![image](https://user-images.githubusercontent.com/9383935/84089684-dc142c00-a9ac-11ea-8a17-5f03bfcfb242.png)

I get this on 3000.2 and master branch...

**Comment by wb529kq** [comment]
On windows 2019 ?

**Comment by twangboy** [comment]
OK, let me try it on 2019...

**Comment by twangboy** [comment]
Yes, it works the same on 2019

**Comment by sagetherage** [comment]
@wb529kq looks like we can't reproduce this , can you give us more details? Maybe it is something specific to your box, or environment? Are you able to upgrade to a newer version of salt?

**Comment by obi-juan-syn** [comment]
Also having this issue on Windows 10 Build 1909, Salt Minion V. 3001.1

Will get the debug for context in a few

**Comment by obi-juan-syn** [comment]
Running into the same issue:

`logon_settings:
  lgpo.set:
    - computer_policy:
        Do not display network selection UI: Disabled
[DEBUG   ] Results of YAML rendering:
OrderedDict([('logon_settings', OrderedDict([('lgpo.set', [OrderedDict([('computer_policy', OrderedDict([('Do not display network selection UI', 'Disabled')]))])])]))])
[PROFILE ] Time (in seconds) to render 'c:\salt\var\cache\salt\minion\files\base\states\win\security\windows_logon.sls' using 'yaml' renderer: 0.0
[DEBUG   ] LazyLoaded config.option
[DEBUG   ] LazyLoaded lgpo.set
[DEBUG   ] LazyLoaded lgpo.set
[INFO    ] Running state [logon_settings] at time 16:37:49.652573
[INFO    ] Executing state lgpo.set for [logon_settings]
[DEBUG   ] LGPO: Loading policy definitions
[DEBUG   ] LazyLoaded file.file_exists
[DEBUG   ] Compiling non hierarchical return...
[DEBUG   ] pol_data == {'user': {'requested_policy': None, 'policy_lookup': {}}, 'machine': {'requested_policy': OrderedDict([('Do not display network selection UI', 'Disabled')]), 'policy_lookup': {'Do not display network selection UI': {'policy_name': 'Do not display network selection UI', 'policy_class': 'machine', 'policy_aliases': ['Do not display network selection UI', 'DontDisplayNetworkSelectionUI', 'System\\Logon\\Do not display network selection UI'], 'policy_found': True, 'rights_assignment': False, 'policy_elements': [], 'message': ''}}}}
[DEBUG   ] current policy == {'Computer Configuration': {'Do not display network selection UI': 'Disabled'}}
[DEBUG   ] need to compare Do not display network selection UI from current/requested policy
[DEBUG   ] "Do not display network selection UI" is already set
[INFO    ] All specified policies are properly configured
[INFO    ] Completed state [logon_settings] at time 16:37:50.491185 (duration_in_ms=838.612)
[DEBUG   ] File c:\salt\var\cache\salt\minion\accumulator\161752752 does not exist, no need to cleanup
[DEBUG   ] LazyLoaded cmd.run
[INFO    ] Executing command ['attrib', '-R', 'c:\\salt\\var\\cache\\salt\\minion\\sls.p'] in directory 'C:\Users\MichaelOblena'
[DEBUG   ] output:
[DEBUG   ] LazyLoaded state.check_result
[DEBUG   ] LazyLoaded highstate.output
local:
----------
          ID: logon_settings
    Function: lgpo.set
      Result: True
     Comment: All specified policies are properly configured
     Started: 16:37:49.652573
    Duration: 838.612 ms
     Changes:
Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time: 838.612 ms`

This is on all newly provisioned Windows 10 VM/Machines.

Debug states: `[DEBUG   ] current policy == {'Computer Configuration': {'Do not display network selection UI': 'Disabled'}}`

yet running lgpo to parse Machine.pol, `System\Logon\Do not display network selection UI` is not set

**Comment by twangboy** [comment]
Have you tried running `gpupdate` after applying the state?

**Comment by obi-juan-syn** [comment]
I've ran gpupdate after applying state, same result.

Since the state module did not modify `C:\Windows\System32\GroupPolicy\Machine\Registry.pol` during the successful run, running gpupdate was moot at that point.

**Comment by drenriza** [comment]
I got my GPO rules applied on Windows Server 2019 by using the AMD64 minion version instead of the x86 on 3002.2
[https://github.com/saltstack/salt/issues/59550](url)

**Comment by obi-juan-syn** [comment]
Recent observation:

1. Upgrading from 3002.2 to 3002.5, LGPO state module works!
2. Fresh install of 3002.5, we're back to the original issue of LGPO failing to set :(

**Comment by twangboy** [comment]
@obi-juan-syn Can you verify that it is the 64bit Salt Minion on 64bit Windows?

**Comment by doesitblend** [comment]
I tried to see if copying the win_lgpo.py module form 3002.2 would work to override the 3003.1 module and resolve the issue, but it did not. I then tried removing the `\salt\var\cache\salt\minion\lgpo` directory in the hopes that having these files recreated using the 3002.2 version of the module would help resolve the issue.

**Comment by twangboy** [comment]
Can't replicate the original issue. Tracking the secondary issue in #61604
