### ISSUE TITLE
Having issue regarding jinja template: "Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute"

### ISSUE THREAD

**Issue by akhilgoel09** [saltstack/salt#57593]
### Description of Issue
Hi Guys,
I am getting error on salt when using jijna template, error below,:
----------
          ID: /etc/tomcat8/context.xml
    Function: file.managed
      Result: False
     Comment: Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'redis_base64_password'
     Started: 04:43:30.104276
    Duration: 26.431 ms
     Changes:   

[ERROR   ] Rendering exception occurred: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'redis_host'
[ERROR   ] Unable to manage file: Jinja variable 'salt.utils.odict.OrderedDict object' has no attribute 'redis_host'

### Setup
I am using salt with master-less configuration

### Steps to Reproduce Issue
 salt-call --local -l debug state.highstate

### Versions Report

salt-minion --version
salt-minion 2017.7.4 (Nitrogen)

**Comment by frogunder** [comment]
@akhilgoel09 Thank you for reporting this issue.

Can you proved me the state file you are trying to run so I can try and replicate it. (Sanitized if any passwords or personal info is present, please)

Also I see you are running version 2017.7.x which is old and unsupported. 
https://www.saltstack.com/product-support-lifecycle/
If you try and upgrade to for example 3000.3, do you still see this issue?

Thanks.

**Comment by akhilgoel09** [comment]
**state files:**

init.sls:
tomcat:
  watch:
    - pkgs:
      - tomcat8
      - tomcat8-admin

/etc/tomcat8/context.xml:
  file.managed:
    - source: salt://tomcat/context.xml
    - template: jinja
    - user: tomcat8
    - group: tomcat8
    - mode: 644
    - makedirs: True  

context.xml file:

<Environment name="secretKey" type="java.lang.String" value="{{pillar['tomcat8']['secret_Key']}}"/>
    <Environment name="redisHost" type="java.lang.String" value="{{pillar['tomcat8']['redis_host']}}"/>
    <Environment name="redisPort" type="java.lang.Integer" value="{{pillar['tomcat8']['redis_port']}}"/>
    <Environment name="redisPassword" type="java.lang.String" value="{{pillar['tomcat8']['redis_base64_password']}}"/>



**pillar files:**

     secret_Key: xxxx
     redis_host: xxxx
     redis_port: xxxx
     redis_base64_password: xxxxx

**Comment by akhilgoel09** [comment]
sorry missed the context file above earlier:

context file:

    <Environment name="secretKey" type="java.lang.String" value="{{pillar['tomcat8']['secret_Key']}}"/>
    <Environment name="redisHost" type="java.lang.String" value="{{pillar['tomcat8']['redis_host']}}"/>
    <Environment name="redisPort" type="java.lang.Integer" value="{{pillar['tomcat8']['redis_port']}}"/>
    <Environment name="redisPassword" type="java.lang.String" value="{{pillar['tomcat8']['redis_base64_password']}}"/>


i will try to use the new salt version as you mentioned and let you know if that fixes.
let me know if anything else is needed to help in this issue
Thanks for the help!!!

**Comment by akhilgoel09** [comment]
Any update....

**Comment by frogunder** [comment]
Sorry for the late reply, we are in the middle of preparing for the 3001 release next week.

What happens when you do a pillar.get on those keys, what does it return at the CLI?

**Comment by terminalmage** [comment]
This looks like incorrectly-configured pillar to me.

You never provided the contents of `/srv/pillar/top.sls`, please do that and also please confirm the location of your pillar `tomcat.sls` pillar file.

**Comment by sagetherage** [comment]
@akhilgoel09 can you please provide the contents and confirm the location of your pillar file, please? Friendly follow up :)

> This looks like incorrectly-configured pillar to me.
> 
> You never provided the contents of `/srv/pillar/top.sls`, please do that and also please confirm the location of your pillar `tomcat.sls` pillar file.

**Comment by whytewolf** [comment]
going to close this 3 year old need-info bug as the needed info was not provided.
