### ISSUE TITLE
salt-minion fails startup on Windows 8.1 x86 and x64, and likely any that doesn't include the relevant vc++ runtime

### ISSUE THREAD

**Issue by arizvisa** [saltstack/salt#57594]
**Description**
salt-minion fails startup on Windows 8.1 x86 and x64 when using the Salt-Minion-3000.1-Py3-x86-Setup.exe or Salt-Minion-3000.1-Py3-x64-Setup.exe, due to api-ms-win-crt-runtime-l1-1-0.dll is missing.

**Setup**
This is actually due to wusa.. Stop the Windows Update service as if you were planning on using saltstack to bootstrap the windows updates.

If its easier, you can use the following packer template from github.com/boxcutter/windows: https://github.com/boxcutter/windows/blob/master/eval-win81x86-enterprise.json Most of the templates using the evaluation iso will have this issue actually.

Do something like `packer build eval-win81x86-enterprise.json`. The eval iso is at http://care.dlservice.microsoft.com/dl/download/B/9/9/B999286E-0A47-406D-8B3D-5B5AD7373A4A/9600.17050.WINBLUE_REFRESH.140317-1640_X64FRE_ENTERPRISE_EVAL_EN-US-IR3_CENA_X64FREE_EN-US_DV9.ISO if you want to pre-download it.

**Steps to Reproduce the behavior**
Run the installer (I've been using saltify-windows from salt-cloud, but you can run it normally too). It will fail to install the universal crt (http://repo.saltstack.com/windows/dependencies/64/ucrt/) due to using wusa which requires specific windows updates to be installed in order for wusa to work.

One symptom is that you'll see the salt-minion service hasn't automatically started and remains in the pause state. This is due to Python being unable to be executed.

Event log (Setup) will show the following depending on the patch that the salt-minion installer tried to install:
```
Windows update  could not be installed because of error 2147942402 "The system cannot find the file specified." (Command li ne: "wusa  "C:\Users\root\AppData\Local\Temp\nssB607.tmp\Windows8.1-KB2999226-x86.msu" /quiet /norestart")
```

You can prove that the crt didn't install by running `C:\salt\bin\python --version` and it will display an error from the runtime linker: "api-ms-win-crt-runtime-l1-1-0.dll is missing".

**Expected behavior**
Salt-minion service should be running, so then updates can be bootstrapped by salt...since we're trying to use salt-cloud after all. But because Python CRT couldn't install due to wusa the service is "paused" or really dead which requires manually repairing things.

**Versions Report**
salt-Minion-3000.3-Py3-x86-Setup.exe
salt-Minion-3000.3-Py3-x64-Setup.exe

This issue is the exact same one as #56296, and I documented a potential fix for it on that ticket.

**Comment by arizvisa** [comment]
I take that back. This will only affect Windows 8.1 (x86 and x64) and Windows Server 2012R2 (as per #56296).

**Comment by frogunder** [comment]
@arizvisa Thank you for reporting this issue.

@saltstack/team-windows @twangboy Can you take a look at this one?

Thanks.

**Comment by xeacott** [comment]
I think that will be on @twangboy after reading through all the comments. 

So from what I read... @arizvisa Win8.1/Server2012R2 is going to need to be patched in order for Salt to be installed on it properly, or during Salt's installation, we need to patch the system. From the looks of it (not super familiar with the Windows installation process), we are attempting to handle this case but one of our files maybe be corrupt?

**Comment by arizvisa** [comment]
Not a corruption issue at all.

It's related to the process being used to install an .msu patch. Installing the patch with the `wusa` api requires certain features to exist within Windows Update which requires a user to ensure that `wuauserv` is enabled, licensed, and patched before installing salt.

So, if you were planning on using saltstack to bootstrap your Windows updates and patches, this actually isn't possible due to the requirements of using the `wusa` api which the salt installer is using.

However, you don't have to use that api to install the patch  as it's literally a .cab file that can be installed with `dism`. You can extract the cab file from the .msu and install it that way.

**Comment by markuskramerIgitt** [comment]
@arizvisa would you have use of an Salt msi installer (instead of an Nullsoft exe)?

The msi installer (available for the release candidate) does not use msu but msm (merge modules)

**Comment by arizvisa** [comment]
I believe either installer could work. The issue is how is the installer going to install KB2999226 which is required for Python3 and directly triggering the issue. I'm using salt-cloud to deploy the installers from https://repo.saltstack.com/windows.

One possible workaround would be to enable the `preflight_cmds` option in salt-cloud for Windows as well as Posixy systems, this way users can use `salt-cloud` to prepare the minion prior to the install. As KB2999226 is a requirement for Python3 (and thus salt) to work (and its installation has its own constraints..), allowing salt-cloud users to pre-configure a minion prior to the install would allow us to use our own workarounds.

I'd be willing to try the .msi though as it's simply just plugging a different path into salt-cloud.

**Comment by arizvisa** [comment]
And here's screenshots of the .exe for the sake of being comprehensive.
Logs for the redistributable: https://gist.github.com/arizvisa/702ef52b6449a26d2a2b779cc40701f6

Screenshot of current install progress at point it asks me about the runtime.
![image](https://user-images.githubusercontent.com/2035497/84325531-96886800-ab40-11ea-9af1-0698a7597bd8.png)

Screenshot of issue:
![image](https://user-images.githubusercontent.com/2035497/84325777-275f4380-ab41-11ea-9710-383132ff5dc6.png)

Screenshot of installation of the crt without using wusa-based com api, and then running python --version. (dism.exe is the only way I know of how to avoid dispatching into the wusa api)
![image](https://user-images.githubusercontent.com/2035497/84326537-bd479e00-ab42-11ea-9811-a27cf8b9745d.png)

**Comment by arizvisa** [comment]
Despite this issue getting such a high severity and it being a critical issue, I don't think it's something you guys can fix "elegantly" as the issue could be considered out-of-scope for the salt project due to python3's dependency on the crt, and salt's depdendency on python3. 

Unless there's some way with the installers to avoid calling into the wusa api for KB2999226, or something similar to dism.exe (which doesn't expose a com api iirc, but probably a native one).

However, users of salt-cloud (which is how I encountered this) can bootstrap minions on systems like this if there was some way to make salt-cloud execute things (like the dism workaround that I suggested) prior to the deployment. There's a `preflight_cmds` implementation for ssh, but not for winrm. Having that capability would be ideal as this issue could then be closed in favor of documentation explaining the issue and how to one can use salt-cloud to work around it. After getting it running, then salt can be used to apply all the necessary updates in the "correct way.

**Comment by twangboy** [comment]
We should present that to the Salt-Cloud working group

**Comment by twangboy** [comment]
Would this fix it: https://github.com/saltstack/salt/pull/57625

**Comment by arizvisa** [comment]
The logic looks sound. Didn't know that you guys bundled the installer scripts in the main repo, hah. Would've submitted a PR if I knew.

Give me a moment though to setup an environment to build the installer and I'll let you know.

**Comment by arizvisa** [comment]
Also, what'd be the process to notify the salt-cloud folks? Just shout @ one of their usernames?

**Comment by arizvisa** [comment]
Just finished downloading (I have a garbage internet connection at the moment) and building. The installer seems to work on win8.1 (x86), so PR #57625 should close this whenev it gets merged.
