### ISSUE TITLE
[BUG] Intel GPU not found in GPU grain

### ISSUE THREAD

**Issue by gizahNL** [saltstack/salt#57602]
**Description**
Intel GPU not found in grain

**Setup**
default grains

**Steps to Reproduce the behavior**
Run salt-call grains.item gpus

**Expected behavior**
Expect to see Intel GPU listed in output.

```
local:
    ----------
    gpus:
        |_
          ----------
          model:
              ASPEED Graphics Family
          vendor:
              unknown

```
**relevant bit in lspci -vmm**
```
Slot:	00:02.0
Class:	Display controller
Vendor:	Intel Corporation
Device:	HD Graphics P630
SVendor:	Super Micro Computer Inc
SDevice:	HD Graphics P630
Rev:	04
```

**Comment by frogunder** [comment]
@gizahNL Thank you for reporting this issue and for the PR.

Thanks.
