### ISSUE TITLE
[BUG] Some modules are not sync with sync_all runner

### ISSUE THREAD

**Issue by jynolen** [saltstack/salt#57617]
**Description**
Runner saltutils miss the following component:
- log_handlers
- matcher
But there are present in the saltutil modules
So it is not possible with out of box runner to use log_handlers and matcher defined in external filesystem like gitfs

However there is the following workarround but it's not convinient to use
`salt-run salt.cmd saltutil.sync_all`

**Setup**
_/etc/salt/master (usefull section only)_
```
gitfs_remotes:
  - file:///opt/work/salt_custom:
    - name: log_handlers
    - root: src/log_handlers
    - mountpoint: salt://_log_handlers    
```
_/opt/work/salt_custom/src/log_handlers/null.py (Dummy handler just for example)_
```
import logging
def virtual():
   return "null"
def setup_handlers():
   return logging.NullHandler()
```

**Steps to Reproduce the behavior**
On minion (correct)
`$ salt-call saltutil.sync_all`
```
log_handlers:
    - log_handlers.null
```
On master (nothing)
`$ salt-run saltutil.sync_all`
```
.........
```
On master (workarround)
`$ salt-run salt.cmd saltutil.sync_all`
```
log_handlers:
    - log_handlers.null
```

**Expected behavior**

On master
`$ salt-run saltutil.sync_all`
```
log_handlers
    - log_handlers.null
```

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: 1.0.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.2.1
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: debian 10.4
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-9-amd64
         system: Linux
        version: debian 10.4
```
</details>

**Additional context**

**Comment by frogunder** [comment]
@jynolen Thank you for reporting this issue.

**Comment by sagetherage** [comment]
the Core team will not be able to get to this in `Aluminium` but we will review a PR if anyone in the community wants to submit one.
