### ISSUE TITLE
[BUG] Debian 9->10 apt-get dist-upgrade removes salt-common & salt-minion

### ISSUE THREAD

**Issue by xenadmin** [saltstack/salt#57619]
**Description**
A Debian 9 adm64 VM with salt-minion installed. 
I want to upgrade, either manual or via salt, doesn't matter, to buster. 
A `apt-get dist-upgrade` wants to remove salt-minion. The machine becomes un-managed. 

**Setup**
A Debian 9 adm64 VM with salt-minion installed.
Source before and after:
```
deb http://repo.saltstack.com/py3/debian/9/amd64/3000 stretch main
deb http://repo.saltstack.com/py3/debian/10/amd64/3000 buster main
```

**Steps to Reproduce the behavior**
Changing all repo sources from stretch to buster.
```
apt-get update
apt-get upgrade
apt-get dist-upgrade
```
The last command will tell you, that `salt-common & salt-minion` will be removed if you press yes. 

**Expected behavior**
The salt-minion should stay installed, so I don't lose control. 

**Versions Report**
```
root@deb9-salt-minion:~# salt-minion --versions-report
Salt Version:
           Salt: 3000.3
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 10.4 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-12-amd64
         system: Linux
        version: debian 10.4 

```

**Comment by frogunder** [comment]
@xenadmin Thank you for reporting this issue.

Did you install salt from https://repo.saltstack.com/#debian ?

Also for clarification, are you on a Debian 9 or Debian 10 machine when you try to upgrade? 
Because I think you will get errors if you are on a Debian 10 machine and try to install instructions for Debian 9. And the same the other way if you are on a Debian 9 machine trying to install instructions fro Debian 10.

Thanks.

**Comment by bryceml** [comment]
Marking as won't-fix since there's a workaround, debian 9 is only has 9 months left, and we can't fix this nicely in a way that will solve the problem for people who have already installed the newer packages.
