### ISSUE TITLE
creation /var/cache/salt/master/minions permission denied

### ISSUE THREAD

**Issue by castastrophix** [saltstack/salt#57627]
On a new installation with apt-get  on Ubuntu 18.04  downloaded with deb http://repo.saltstack.com/apt/ubuntu/18.04/amd64/latest bionic main

version Salt: 2017-7-4 

Directory /var/cache/salt/master is owned by root with only read rights to other users. 
some subdirectory exist under it. they were  created with user salt like tokens, jobs, proc...
minions directory did not exist yet. 

Salt try to create  the minions directory there without the rights to create it while it has created the other directories so it miss something in the installation to create the directory it needed.  After creating that directory manually with writing rights  for everyone salt began populating the directories under it created with user salt.

**Comment by frogunder** [comment]
@castastrophix Thank you for reporting this issue.

Did you try to install salt from the official salt repo? 
https://repo.saltstack.com/#ubuntu 

It seems weird if you install latest but got version 2017.7.4.

**Comment by garethgreenaway** [comment]
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.
