### ISSUE TITLE
[FEATURE REQUEST]: Grain with the LVM volumes

### ISSUE THREAD

**Issue by piterpunk** [saltstack/salt#57629]
**Is your feature request related to a problem? Please describe.**
The LVM makes easier to manage the machine storage, providing a logical abstraction over the physical disks. The logical volumes  are dynamical and could span for several disks or use only part of them. It's very common to use LVM in Linux Servers, so the filesystems could easily grow as needed and new disks are added.

But no LVM information is provided by the default grains. There is information about the disks,  ZFS information and even the Linux software RAID, mdadm, but nothing about the LVM volume groups and the logical volumes associated.

I would like to have access to the information about volume groups and logical volumes as a grain for all my Linux machines.

**Describe the solution you'd like**
I would like to have a grain with the information about the LVM volumes groups and their logical volumes

**Describe alternatives you've considered**
I considered setting up a custom grain to bring this information.  But I guess that this a useful information for everyone managing a Linux server.

**Comment by frogunder** [comment]
@piterpunk Thank you for this feature request and for the PR.

Thanks.
