### ISSUE TITLE
Memory Tuning Support

### ISSUE THREAD

**Issue by gqlo** [saltstack/salt#57639]
Having [Memory Tuning  support](https://libvirt.org/formatdomain.html#elementsMemoryTuning) allows much greater control of the memory allocation.

**Comment by frogunder** [comment]
@gqlo Thank you for this feature request and for your PR.

Thanks.

**Comment by gqlo** [comment]
> @gqlo Thank you for this feature request and for your PR.
> 
> Thanks.

:)
