### ISSUE TITLE
[BUG] [RC1 Sodium] Wrong PIDs in service.status when using sysvinit

### ISSUE THREAD

**Issue by piterpunk** [saltstack/salt#57634]
**Description**
When using service.status in a pure sysvinit environment, the PID of the python running the "service.status" always is in the results list. So, it always return at least one PID as result, even for non-existent services:

```
root@marvin:~# salt-call service.status service_that_dont_exists
local:
    8645
root@marvin:~# salt-call service.status service_that_dont_exists
local:
    8837
```

**Setup**
Nothing special, Salt 3001 (git202006091336) in two Slackware Linux machines.

**Steps to Reproduce the behavior**
Run "service.status" with a non-existent service, in a machine with pure sysvinit backend:

```
root@marvin:~# salt-call grains.get init
local:
    sysvinit
root@marvin:~# salt-call service.status another_service_that_dont_exists
local:
    9457
```

**Expected behavior**
It's expected to not have the python own PID in the output list.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: 1.1.3
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.3 (default, May 15 2020, 05:51:00)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: slackware 14.2 current
         locale: utf-8
        machine: i686
        release: 5.4.45
         system: Linux
        version: Slackware 14.2 current

```
</details>

**Comment by frogunder** [comment]
@piterpunk Thank you for reporting this issue and for you PR.

Thanks.
