### ISSUE TITLE
[FEATURE REQUEST]: Consider having all point releases on archive.repo.saltstack.com

### ISSUE THREAD

**Issue by rossengeorgiev** [saltstack/salt#57640]
**Is your feature request related to a problem? Please describe.**
It is currently **not possible** to template a URL to a specific version of salt without knowing what the latest release is.

Example URL templating:

```jinja2
http://archive.repo.saltstack.com/apt/ubuntu/{{ OS_VER }}/amd64/archive/{{ SALT_VER }}/
http://archive.repo.saltstack.com/yum/redhat/{{ OS_VER }}/x86_64/archive/{{ SALT_VER }}/
```
It doesn't work for the last 2 point releases:

http://archive.repo.saltstack.com/yum/redhat/7/x86_64/archive/3000.3/ - 404
http://archive.repo.saltstack.com/yum/redhat/7/x86_64/archive/3000.2/ - 404
http://archive.repo.saltstack.com/yum/redhat/7/x86_64/archive/3000.1/ - works!

http://archive.repo.saltstack.com/yum/redhat/7/x86_64/archive/3000/ - Not a point release. Points to `3000.2` currently

Doesn't seem right to have that in the archive as it will eventually disappear as new major versions are released.

**Describe the solution you'd like**
Have all point releases available on `archive.repo.saltstack.com`

**Additional context**
Examples other software projects with archive repos:

http://archive.ubuntu.com/ubuntu/dists/
http://vault.centos.org/

**Comment by frogunder** [comment]
@rossengeorgiev Thanks for reporting this feature request.

@saltstack/team-core @bryceml Can you chime in on this one?

Thanks

**Comment by bryceml** [comment]
It was discussed while the SEP was open was decided against.  Also, it's confusing but:

https://archive.repo.saltstack.com/yum/redhat/7/x86_64/archive/3000/ is a point release
https://repo.saltstack.com/yum/redhat/7/x86_64/3000/ is a symlink to 3000.3

It makes it hard to use the bootstrap script because of the version scheme because if you specify
`stable 3000` it will setup your repo files to point to the major release and there is no way to pin to the point release with the bootstrap script as far as I am aware.

**Comment by rossengeorgiev** [comment]
Oh, I didn't even notice that inconsistency. `3000` on `/archive/` is essentially `3000.0`. That is so confusing, and even comes last in the folder order in the listing.

For the moment, https://repo.saltstack.com/yum/redhat/7/x86_64/archive/ works for URL templating. I assume it will get removed? Then templating becomes a pain. I know the SEP came about around CVE/supported versions, and that is all fine. However, in my use case I perform a whole lot of testing with various combinations of salt and distributions. Having to adjust the scripts with every release will be frustrating.

**Comment by bryceml** [comment]
@rossengeorgiev anything here: https://archive.repo.saltstack.com/yum/redhat/7/x86_64/archive/  will be removed from repo.saltstack.com when we sync up the changes from staging.  It looks like the plan so far is to have those deletions sync up at the same time as the 3001 release which should be on the 17th.

**Comment by rossengeorgiev** [comment]
✔ http://archive.repo.saltstack.com/apt/ubuntu/14.04/amd64/2019.2/ 
❌ http://archive.repo.saltstack.com/apt/ubuntu/16.04/amd64/2019.2/
✔ http://archive.repo.saltstack.com/apt/ubuntu/16.04/amd64/archive/2019.2.3/ 
❌ http://archive.repo.saltstack.com/apt/ubuntu/18.04/amd64/2019.2/
✔ http://archive.repo.saltstack.com/apt/ubuntu/18.04/amd64/archive/2019.2.3/

❌ http://archive.repo.saltstack.com/py3/ubuntu/18.04/amd64/3000/
✔ http://archive.repo.saltstack.com/py3/ubuntu/18.04/amd64/archive/3000.1/

❌ http://archive.repo.saltstack.com/py3/ubuntu/20.04/ doesn't exist at all

❌ http://archive.repo.saltstack.com/yum/redhat/6/x86_64/2019.2/
✔ http://archive.repo.saltstack.com/yum/redhat/6/x86_64/archive/2019.2.3/
❌ http://archive.repo.saltstack.com/yum/redhat/6/x86_64/3000/
✔ http://archive.repo.saltstack.com/yum/redhat/6/x86_64/archive/3000.1/
^ same for CentOS 7

✔ http://archive.repo.saltstack.com/py3/redhat/7/x86_64/2018.3/
❌ http://archive.repo.saltstack.com/py3/redhat/7/x86_64/2019.2/
❌ http://archive.repo.saltstack.com/py3/redhat/7/x86_64/3000/
❌ http://archive.repo.saltstack.com/py3/redhat/7/x86_64/3001/
✔ http://archive.repo.saltstack.com/py3/redhat/7/x86_64/archive/ ....

❌ http://archive.repo.saltstack.com/py3/redhat/8/x86_64/2019.2/
❌ http://archive.repo.saltstack.com/py3/redhat/8/x86_64/3000/
❌ http://archive.repo.saltstack.com/py3/redhat/8/x86_64/3001/
✔ http://archive.repo.saltstack.com/py3/redhat/8/x86_64/archive/ ....

This has been an incredible source of frustration for me and colleagues.

**Comment by whytewolf** [comment]
so, we no longer are moving things to `archive.repo.saltstack.com` during cves. and the only versions on that site are unsupported versions. with that we are going to close this.
