### ISSUE TITLE
[DOCS] rework states part 1 clearer explanation to start at configure file_roots

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#57654]
**Description**
In the tutorial documentation, [States Part 1](https://docs.saltstack.com/en/latest/topics/tutorials/states_pt1.html#targeting-minions), under the section "SLS File Namespace" it's not quite clear that all paths must start at the configured file_roots.

**Comment by doesitblend** [comment]
ZD-5279

**Comment by sagetherage** [comment]
@saltstack/docs-working-group looks like we could make this clearer

**Comment by sagetherage** [comment]
@doesitblend updated the title so I don't have to dig all the way into the issue to remember what this one is, exactly, I hope that is ok. Thanks!

**Comment by sagetherage** [comment]
@doesitblend can you give me what you expect this to look like exactly? If we simply need to add a single line it is pretty small in scope but I am thinking it is bigger if the expectation is to re-write the tutorial, LMK

**Comment by ScriptAutomate** [comment]
> **Description**
> In the tutorial documentation, [States Part 1](https://docs.saltstack.com/en/latest/topics/tutorials/states_pt1.html#targeting-minions), under the section "SLS File Namespace" it's not quite clear that all paths must start at the configured file_roots.

@doesitblend Is the suggested fix to add something like another bullet point to the **SLS File Namespace** section, for **step 2**, like so:

```rst
    1. The ``.sls`` is discarded (i.e. ``webserver.sls`` becomes
       ``webserver``).
    2. :ref:`file_roots <file-roots-directory-overlay>`, set within the ``master`` configuration file,
       configures the directory paths where state files and their subdirectories exist.
    3. Subdirectories can be used for better organization.
        a. Each subdirectory is represented with a dot (following the Python
           import model) in Salt states and on the command line .  ``webserver/dev.sls``
           on the filesystem is referred to as ``webserver.dev`` in Salt
        b. Because slashes are represented as dots, SLS files can not contain
           dots in the name (other than the dot for the SLS suffix).  The SLS
           file ``webserver_1.0.sls`` can not be matched, and ``webserver_1.0``
           would match the directory/file ``webserver_1/0.sls``

    4. A file called ``init.sls`` in a subdirectory is referred to by the path
       of the directory. So, ``webserver/init.sls`` is referred to as
       ``webserver``.
    5. If both ``webserver.sls`` and ``webserver/init.sls`` happen to exist,
       ``webserver/init.sls`` will be ignored and ``webserver.sls`` will be the
       file referred to as ``webserver``.
```

**Comment by doesitblend** [comment]
We can probably just update this line
>Each subdirectory is represented with a dot (following the Python import model) in Salt states and on the command line . `webserver/dev.sls` on the filesystem is referred to as `webserver.dev` in Salt

to the following
>Each subdirectory under the configured file_roots (default: `/srv/salt/`) is represented with a dot (following the Python import model) in Salt states and on the command line . i.e. `webserver/dev.sls` on the filesystem is referred to as `webserver.dev` in Salt

It's already mentioned earlier in the document, so this would just be a little reminder of this fact to those are just referencing, or reviewing this document for specific information.
