### ISSUE TITLE
[BUG] [RC1 Sodium] Could not load configuration due to : "[Errno 21] Is a directory.."

### ISSUE THREAD

**Issue by vnitinv** [saltstack/salt#57667]
**Description**
When cache is not present, while copy we used cp_get_template, this return folder name and not the file path. Hence we got this error
```
[ERROR   ] {'out': False, 'message': 'Could not load configuration due to : "[Errno 21] Is a directory: \'/tmp/tmpgcohosan\'"', 'format': 'set'}
```

**Setup**
```
root@iagent:/srv/salt# cat install_conf.sls
Install the mentioned config:
  junos.install_config:
    - name: salt://configs/test.set
```

**Steps to Reproduce the behavior**
Remove any cache file on proxy server.
it can be found using
```
salt xxx cp.is_cached salt://configs/test.set
```

**Expected behavior**
Should not throw error

**Screenshots**

**Versions Report**
v3001rc1

```
PASTE HERE
```
</details>

**Additional context**

**Comment by bswilden** [comment]
I have encountered this issue in v3001rc1

**Comment by vnitinv** [comment]
Fixed via #57668

**Comment by dmurphy18** [comment]
@vnitinv Full information for versions-report is helpful in reproducing this, esp. that it provides platform information. Also the contents of the examples so that the error can be reproduced.

Given that I am running similar tests without error, more details need to be provided in order to reproduce the error.

Lastly is this with a proxy-minion or a regular salt-minion ?

**Comment by vnitinv** [comment]
@dmurphy18 

Salt Version:
           Salt: 3001rc1

The condition/setup is:

* salt master and proxy are running on a different server.

* There is **NO** cached file located on proxy server, which can be confirmed using
```
root@iagent:/srv/salt# salt proxy01 cp.is_cached salt://configs/test.set
proxy01:
```

To avoid copying every time, we check if we have cached file, if then check checksum and use the same.

* Using install_config module for Junos
```
$ cat install_conf.sls
Install the mentioned config:
  junos.install_config:
    - name: salt://configs/test.set
```
where `salt://configs/test.set` is a template which uses salt internal variable
```
$ cat configs/test.set
{% set proxyid = grains['id'] %}
set system host-name {{ pillar[proxyid]['hostname'] }}
```

if we have already cached file located, this issue wont come.

**Comment by dmurphy18** [comment]
PR approved, awaiting merge https://github.com/saltstack/salt/pull/57668
