### ISSUE TITLE
[QUESTION] Windows output of command line is on one line for many commands

### ISSUE THREAD

**Issue by castastrophix** [saltstack/salt#57675]
Do a simple comman  to have many line of text like 
Salt-call --local pkg.list_pkgs

On linux I got an output with  nice list of package on many lines in color and version in another color  with ident

On Windows there is a one line which include a lot of unescaped character like \n \\ 
Some commands are working on Windows without color like 
salt-call --local grains.ls 
which is on many lines 

Salt-call 3000.3 
versions.)

**Comment by xeacott** [comment]
Hey @castastrophix so what exactly would you like to see change? I'm not understanding the issue with Salt or what behavior is wrong/incorrect in this case.

**Comment by castastrophix** [comment]
the pkg.list_pkgs output would be 
`
b"local:\n ---------\n    tools for .Net 3.5:\n 3.11.50777\n .....
`
It is more difficult to read because nothing is aligned and if I want  to automate the output of the windows command line sometime I have to unescape the output and sometimes not.  This is not always the same and it is different than Linux which require even more different programming of the output

**Comment by aratik711** [comment]
+1 on this (salt version 3001, python3.8, ubuntu16.04)
@xeacott facing the same issue where the output comes in a single line as below:

pt/sources.list.d/3rdparty.list:3\\nW: Target Packages (multiverse/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list.d/3rdparty.list:3\\nW: Target Translations (multiverse/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:2 and /etc/apt/sources.list.d/3rdparty.list:3\\nW: Target Packages (main/binary-amd64/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/3rdparty.list:4\\nW: Target Packages (main/binary-all/Packages) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/3rdparty.list:4\\nW: Target Translations (main/i18n/Translation-en) is configured multiple times in /etc/apt/sources.list:3 and /etc/apt/sources.list.d/3rdparty.list:

79397\x1b[0;0m\n    \x1b[0;36mDuration: 7.461 ms\x1b[0;0m\n\x1b[0;36m     Changes:   \n              \x1b[0;36m----------\x1b[0;0m\n              \x1b[0;36mpid\x1b[0;0m:\n                  \x1b[0;1;33m2243\x1b[0;0m\n              \x1b[0;36mretcode\x1b[0;0m:\n                  \x1b[0;1;33m0\x1b[0;0m\n              \x1b[0;36mstderr\x1b[0;0m:\n              \x1b[0;36mstdout\x1b[0;0m:\x1b[0;0m\n\x1b[0;36m\nSummary for local\n--------------\x1b[0;0m\n\x1b[0;32mSucceeded: 217\x1b[0;0m (\x1b[0;32mchanged=73\x1b[0;0m)\n\x1b[0;31mFailed:      5\x1b[0;0m\n\x1b[0;36m--------------\nTotal states run:     222\x1b[0;0m\n\x1b[0;36mTotal run time:    43.864 s\x1b[0;0m'

@castastrophix did you find any fix for this?

**Comment by garethgreenaway** [comment]
@aratik711 When you see this output where are you running the Salt command from?  It appears that there are color codes in that output so I am wondering what the `TERM` variable is set to.

**Comment by lubo** [comment]
Experiencing the same problem on Salt 3000.3, Python 3.6, CentOS 7. Seems like the output is being logged as _bytes_ instead of _str_ if it contains non-ASCII characters like `…`. I've hacked up [a simple scripts](https://gist.github.com/lubo/ac7686699f6b5a27873e462ad495c170) which accepts Salt output on stdin, but you'll probably need to use `--no-color`.

**Comment by anilsil** [comment]
> Experiencing the same problem on Salt 3000.3, Python 3.6, CentOS 7. Seems like the output is being logged as _bytes_ instead of _str_ if it contains non-ASCII characters like `…`. I've hacked up [a simple scripts](https://gist.github.com/lubo/ac7686699f6b5a27873e462ad495c170) which fixes the output if necessary.

Closing as a workaround is available.
