### ISSUE TITLE
[FEATURE REQUEST] Updating %PATH% on installation SaltStack for Windows

### ISSUE THREAD

**Issue by berkut-174** [saltstack/salt#57673]
**Is your feature request related to a problem? Please describe.**
I see an error (see below) during the installation of SaltStack, when my %PATH% exceeds 1024 characters and the %PATH% does not update as expected.
When uninstalling SaltStack, %PATH% is also not updated regardless of its length.

**Describe the solution you'd like**
I suggest the NSIS EnVar plugin https://github.com/GsNSIS/EnVar/releases/download/v0.2.1/EnVar-Plugin.zip, it is recommended for use according to this wiki page https://nsis.sourceforge.io/Path_Manipulation.
I have a ready commit that works as it should. I want to ask to add an archive with the EnVar plugin in the repo SaltStack https://repo.saltstack.com/windows/dependencies. In this case, I can provide a ready pull request that will fix the existing problems with updating the %PATH% environment variable for Windows.

**Additional context**
![error](https://user-images.githubusercontent.com/1829509/84699350-ca152900-af6a-11ea-85a3-0b09952aa524.png)

**Comment by xeacott** [comment]
Ahhh nicely done. Would you like to get the PR up and we can move discussion there?

**Comment by berkut-174** [comment]
I expect the https://repo.saltstack.com/windows/dependencies/nsis-plugin-envar.zip file exists in the repo, but it is not. PR is here https://github.com/saltstack/salt/pull/57693
Thank.
