### ISSUE TITLE
SSE API cmds

### ISSUE THREAD

**Issue by karkey-salt** [saltstack/salt#57678]
We have a SALT SSE API, I'm trying to execute few commands to get current license count as mentioned in the document https://help.saltstack.com/hc/article_attachments/360049509052/SaltStackEnterpriseHelp-v6_1_0_October.pdf

But unable to execute the sample code provided in the document, getting python errror
**ImportError: No module named 'sseapiclient'**

We are using python3, already have tornado installed on the server.

from sseapiclient.tornado import SyncClient
host = 'http://localhost'
user = 'root'
password = 'salt'
client = SyncClient.connect(host, user, password)
client.api.admin.trim_database(
audit=30, events=30, jobs=30, schedule=30, test=True)

Please advice.

**Comment by sagetherage** [comment]
@karkey-salt you have opened an issue for the SaltStack Enterprise product in the Salt Open Source repo. If you are having trouble with the Enterprise Product, please reach out to our support department by emailing them at enterprisesupport@saltstack.com. You may also submit a ticket by logging in to the support portal at https://help.saltstack.com/ .
