### ISSUE TITLE
[Question] Upgrading windows salt minions from the salt master

### ISSUE THREAD

**Issue by StewAlexander-com** [saltstack/salt#57686]
We have about 1500 or so Windows PC salt minions distributed over a pretty big area, and we were wondering what the easiest way is to upgrade all of the out-of-date salt minions?

Is there a way to do this from the salt master?

This would be the easiest solution for us....

I read online that the salt-minion may loose connection to the salt master if we upgrade from the salt master, but we're curious if this is only an issue with Linux systems?

Please let us know, thanks....

**Comment by xeacott** [comment]
> Is there a way to do this from the salt master?

Yes! A few ways that come to mind, but the important part of all of this is to make sure that your question is answered, which unfortunately, I don't have a clear cut answer so we'll need to discuss this. @saltstack/team-core any thoughts on this?

**Comment by StewAlexanderACC** [comment]
Great, thanks for at least discussing this, as it would be problematic to send the 3 people we have to the 1500+ systems to upgrade individually

**Comment by xeacott** [comment]
Certainly! I'm thinking you should be able to follow this type of workflow ... (the _exact_ states for you will be different but its the same idea)

1. Run a state that downloads from repo.saltstack.com onto the salt-master
2. Run a command that copies over the file from the master to each windows minion with https://docs.saltstack.com/en/latest/ref/cli/salt-cp.html: 
3. Run a state that targets windows minions, which would install the binary

Example state that downloads the file onto the salt-master:
```
            upgrade_windows_machines:
              file.managed:
                - name: salt_upgrade.exe
                - source: https://repo.saltstack.com/windows/Salt-Minion-3000.3-Py2-x86-Setup.exe
```
Example state that would install the file once its on each salt-minion:
```
installed_windows_upgrade_file:
    cmd.run:
        - name: salt_upgrade.exe /S /master=yoursaltmaster /minion-name=yourminionname
```
cmd to run:
`salt windows_minion* state.apply installed_windows_upgrade_file`

**Comment by twangboy** [comment]
I would just use winrepo
```
install salt:
  pkg.installed:
    - name: salt-minion
    - version: latest
```

**Comment by twangboy** [comment]
Or
```
latest salt:
  pkg.latest:
    - name: salt-minion
```

**Comment by xeacott** [comment]
Whichever you find easier @StewAlexanderACC please only do a few minions before running it on 1500 😄 that way you don't have any _potential_ headaches 😉

**Comment by max-arnold** [comment]
1. If possible, ensure that you have a backup remote access (other than Salt) to each minion in case if something goes wrong
2. Survey your minion versions
3. Test the upgrade process for each minion version
4. Upgrade the master first
5. Upgrade one or two minions, then very carefully and gradually start upgrading them in larger batches (you can use the salt version grain to  target minions that weren’t upgraded yet)

Below is a blog post I wrote that describes the process in more details. It is about a slightly different problem of switching Salt from Py2 to Py3, but some steps should be the same. Please do not apply it blindly (I only upgraded a couple of Windows 10 minions)  and test everything upfront!
https://salt.tips/upgrading-salt-to-python-3/

**Comment by StewAlexanderACC** [comment]
How to use winrepo? I have heard of this in other posts, but I did not find how to use this...

If I upgrade the Master is it backwards compatible with the salt minion version ``` 2017.7.8```

That is the version of salt-minion on all of our Windows systems

**Comment by shaibaz711** [comment]
@StewAlexander-com Reviving this old thread. What steps did you finally took as I'm in a similar situation where I've to upgrade 350+ minions from 3004 to 3004.1. 
However, my problem is a lil different here. I know how to write the state file to upgrade the minions. I'm able to upgrade the minion successfully by using the below code:
`Upgrade Salt Minion:
  pkg.installed:
    - name: salt-minion
    - version: 3004.1
    - order: last`
 
But my only hiccups are:
1. The Master does not get any response after the minion is upgraded on Windows server. Has anyone got any hack to wait for sometime and then get a response from the minion? Currently, when I run the above state, it upgrades the service in the background and I get a No minion response error. I've to run the state on all the minions again.
2. Is it possible to upgrade the salt-minion service on Windows Server 2008? I know the server has reached EOL but for some unavoidable reasons, we can't upgrade it for some more time. And we don't want to stop upgrading salt on it. 

@twangboy If you can share some knowledge here and help me out, I'll be really grateful as I'm stuck onto this from quite sometime now.

**Comment by StewAlexander-com** [comment]
@shaibaz711 Still waiting on feedback, as yeah if we can use this that would be great....

**Comment by shaibaz711** [comment]
@StewAlexander-com Oohh. I thought your questions must have been answered by now somewhere else.

Anyways, let me try to help you as much as I can.

To start using WinRepo(This is very powerful) you just need to set a directory at your root level in the config and run this command **`salt-run winrepo.update_git_repos`** After which a repository containing the most important and widely used software library is mapped onto your master. You can then simply use it to install any of the software. The details of it can be found here - https://docs.saltproject.io/en/latest/topics/windows/windows-package-manager.html#quick-start
Don't forget to run `salt * pkg.refresh_db` This will refresh your repository and all you would need then is the package name and version as mentioned by twangyboy above.

Yes, the setup backwards compatible but I'm not sure of how many versions. I've tested 3004.1 master with 3003 version mininos and they are working fine.

I would suggest you to upgrade your minions as soon as possible as there are some serious critical vulnerabilities which can lead to compromise your machines.

Let me know if you need anything else from me. I would be more than happy to help :)
