### ISSUE TITLE
[FEATURE REQUEST] Get grains from grainsv2

### ISSUE THREAD

**Issue by Akm0d** [saltstack/salt#57680]
Separate grains from core.py and the `grains` directory into independent platform specific projects.
The SEP for this change is [here](https://github.com/saltstack/salt-enhancement-proposals/pull/30)
The bulk of the work has been done in:
[idem-linux](https://gitlab.com/saltstack/pop/idem-linux)
[idem-bsd](https://gitlab.com/saltstack/pop/idem-bsd)
[idem-windows](https://gitlab.com/saltstack/pop/idem-windows)
[idem-darwin](https://gitlab.com/saltstack/pop/idem-darwin)
[idem-aix](https://gitlab.com/saltstack/pop/idem-aix)
[idem-solaris](https://gitlab.com/saltstack/pop/idem-solaris)
[grains-virt](https://gitlab.com/saltstack/pop/corn_virtualiztion)

**Comment by sagetherage** [comment]
@Akm0d since we withdrew the SEP, what do we do this issue, now?
