### ISSUE TITLE
[FEATURE REQUEST] Appget module for dealing with the Microsoft AppGet package manager

### ISSUE THREAD

**Issue by StewAlexander-com** [saltstack/salt#57697]
Hi -

Microsoft recently copied AppGet for WinGet (https://it.slashdot.org/story/20/06/01/1447201/microsoft-now-credits-maker-of-package-manager-it-copied----but-offers-no-apology), which I suppose will be their defacto Windows package manager in later releases (?)

Anyway, just like there is a module for Chocolatey, we would like to see a module for AppGet

https://appget.net/

Thank you ....

**Comment by xeacott** [comment]
@StewAlexanderACC Yes, @twangboy @thatch45 and myself are super excited to see what we can do with winget. I would expect a module to appear at some point, but unfortunately we haven't really discussed it.
