### ISSUE TITLE
[FEATURE REQUEST] test-kitchen supporters wanted

### ISSUE THREAD

**Issue by Xorima** [saltstack/salt#57691]
Hi All,

I am one of the admins for https://github.com/test-kitchen and we are looking for additional maintainers to help ensure the direction of the project works for everyone. 

Would there be any members of Salt who would like to help us here (And ensure it continues to work for your usecases?)

Thanks

Jason

**Comment by sagetherage** [comment]
Hi Jason! Thank you for the request and we are very interested and it is my understanding our community manager @cassandrafaris has reached you via other communications platforms and we look forward to talking about this in a weekly Open Hour community meeting on Thursdays.
