### ISSUE TITLE
[BUG] `virtual` grains broken on illumos on 3001

### ISSUE THREAD

**Issue by sjorge** [saltstack/salt#57714]
**Description**
Somewhere between 3000.1 and 3001 the `virtual` grains got broken on illumos.
It only ever gets set to `physical` which is the default fallback if i am not mistaken.

**Setup**
Running salt 3001 inside a SmartOS zone.

**Steps to Reproduce the behavior**
```
[root@cronos ~]# /opt/salt3001/bin/salt-call grains.get virtual
local:
    physical
```

**Expected behavior**
```
[root@cronos ~]# /opt/salt3000/bin/salt-call grains.get virtual
local:
    zone
```

**Screenshots**
n/a

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
[root@cronos ~]# /opt/salt/bin/salt-call --versions-report
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.30.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.6 (default, Oct 23 2018, 17:13:47)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: pkgsrc 3
         locale: UTF-8
        machine: i86pc
        release: 5.11
         system: SunOS
        version: release: 2018Q 3
```
</details>

No master involved.

**Additional context**
I tried tracing it back but the diff between the too was rather confusing, there were some changes for Solaris LDOM which might have effected this, but AFAIK they don't.

I did do some debugging with pudb and it seems we now ever make it to  https://github.com/saltstack/salt/blob/b95213ec903402f25c1e0aeb3990fe8452ab63ce/salt/grains/core.py#L912 which we did in the past.

**Comment by sjorge** [comment]
Before it would hit this and then hit https://github.com/saltstack/salt/blob/b95213ec903402f25c1e0aeb3990fe8452ab63ce/salt/grains/core.py#L927, where it would fallback to zone.

It now seems to abort earlier.

**Comment by sjorge** [comment]
So it looks like before we stepped into the prtdiag block even if the command failed (non-global zone), we just did not append it to the failed_commands set.

In the ptrdiag block we then still check the zonename to figure out if we are physical or a zone.

Currently on 3001 we never make it because we bail out near the top because the exit code is not 0 (as mentioned, this is expected for a zone)

An easy fix is to add a new block that checks kernel == "SunOS" (sadly illumos still shares the name with Oracle Solaris) and move the else here https://github.com/saltstack/salt/blob/b95213ec903402f25c1e0aeb3990fe8452ab63ce/salt/grains/core.py#L922-931 to the new location.

But I am not sure this will mess up some of the LDOM detetion that was recently added or not as I no longer have access to Oracle Solaris machines, just a mix of illumos.

**Comment by sjorge** [comment]
This seems to fix it:
```patch
[root@cronos /opt/salt/lib/python3.6/site-packages/salt/grains]# diff -u core.py.orig core.py
--- core.py.orig        2020-06-18 16:12:13.333695535 +0000
+++ core.py     2020-06-18 17:44:04.672671660 +0000
@@ -775,15 +775,19 @@
         try:
             ret = __salt__["cmd.run_all"](cmd)

-            if ret["retcode"] > 0:
+            # ignore exitcode for prtdiag as it only
+            # works in the global zone, we have some
+            # fallbacks in the prtdiag block below
+            if (
+                ret["retcode"] > 0
+                and "prtdiag" not in cmd
+            ):
                 if salt.log.is_logging_configured():
                     # systemd-detect-virt always returns > 0 on non-virtualized
                     # systems
-                    # prtdiag only works in the global zone, skip if it fails
                     if (
                         salt.utils.platform.is_windows()
                         or "systemd-detect-virt" in cmd
-                        or "prtdiag" in cmd
                     ):
                         continue
                     failed_commands.add(command)
```

@DmitryKuzmenko perhaps some optimization changed the behavior of the retcode check.

I think some of the code should be rewritten to avoid this mess though, or would the above patch be acceptable?

**Comment by sjorge** [comment]
Actually I think this patch is better, we break the loop in the newer LDOM detection if we match anything, so this works as a fallback and that path is then used by illumos.

```patch
[root@cronos /opt/salt/lib/python3.6/site-packages/salt/grains]# diff -u core.py.orig core.py
--- core.py.orig        2020-06-18 16:12:13.333695535 +0000
+++ core.py     2020-06-18 17:50:40.655886903 +0000
@@ -919,16 +919,6 @@
                 grains["virtual"] = "kvm"
             elif "joyent smartdc hvm" in model:
                 grains["virtual"] = "kvm"
-            else:
-                # Check if it's a "regular" zone
-                zonename = salt.utils.path.which("zonename")
-                if zonename:
-                    zone = __salt__["cmd.run"]("{0}".format(zonename))
-                    if zone != "global":
-                        grains["virtual"] = "zone"
-                # Check if it's a branded zone
-                elif os.path.isdir("/.SUNWnative"):
-                    grains["virtual"] = "zone"
             break
         elif command == "virtinfo":
             if output == "logical-domain":
@@ -1121,6 +1111,18 @@
             ):
                 if os.path.isfile("/var/run/xenconsoled.pid"):
                     grains["virtual_subtype"] = "Xen Dom0"
+    elif osdata["kernel"] == "SunOS":
+        # we did not get any data from virtinfo or prtdiag
+        # check the zonename here as fallback
+        zonename = salt.utils.path.which("zonename")
+        if zonename:
+            zone = __salt__["cmd.run"]("{0}".format(zonename))
+            if zone != "global":
+                grains["virtual"] = "zone"
+
+        # Check if it's a branded zone
+        elif os.path.isdir("/.SUNWnative"):
+            grains["virtual"] = "zone"

     # If we have a virtual_subtype, we're virtual, but maybe we couldn't
     # figure out what specific virtual type we were?
```

**Comment by xeacott** [comment]
@sjorge Thanks for the report and spending so much time on diving into the code. Would you be able to open a PR and we can discuss there?

**Comment by sjorge** [comment]
@xeacott I can yeah, but won't have time the coming week to write tests (never written tests for grains and I am not sure how I can add a test that covers this particular bug well.)

**Comment by xeacott** [comment]
Hey no problem @sjorge there are a lot of tests that already exist in `unit/core/test_grains.py` that can be used for examples, just like the LXC grain. If you're feeling it, go for it. Otherwise we appreciate the PR and someone will get tests written for it.

**Comment by sjorge** [comment]
I'll try to get the PR in with just the patch and some more fleshed out description/analysis.
I can push tests later if I find time, or like you said someone form saltstack could do them.

**Comment by sagetherage** [comment]
looks as though this was fixed sometime ago, closing. @sjorge please mention me if I'm incorrect

**Comment by sjorge** [comment]
correct, I fixed it a few months ago.
