### ISSUE TITLE
[BUG] grains.delkey/delval requries an argument that does not exist

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#57718]
**Description**
Trying to use `grain.delkey` or `grains.delval` on a structured value results in this message
> The key 'foo' exists but is a dict or a list. Use 'force=True' to overwrite.

However, neither function accepts this argument
> The following keyword arguments are not valid: force=True

Trying to workaround by force-setting back to a string, and the `grains.delkey` reports no errors, but the key hasn't been deleted.
Also tried with `saltutil.refresh_grains` between each step, with no difference.

The only solution I found was to edit  `/etc/salt/grains`, restart the minion and then call `saltutil.refresh_grains`.

**Setup**
```
salt-call grains.set foo bar
```

**Steps to Reproduce the behavior**
```
salt-call grains.delkey foo  # fails
salt-call grains.delkey foo force=True  # fails

salt-call grains.set foo bar force=True  # succeeds
salt-call grains.delkey foo  # "succeeds"
salt-call grains.ls | grep foo  # shows a match
```

**Expected behavior**

Either:
 - the grain is deleted as before
 - the `force=True` allows it to be deleted

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: 1.0.3
         Python: 3.8.2 (default, Apr 27 2020, 15:53:34)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: ubuntu 20.04 focal
         locale: iso8859-1
        machine: x86_64
        release: 5.4.0-37-generic
         system: Linux
        version: Ubuntu 20.04 focal
```
</details>

**Additional context**
This is a regression from 3000.3

**Comment by xeacott** [comment]
@OrangeDog Thanks for reporting this, we'll get someone on it. 👍

**Comment by OrangeDog** [comment]
I realised I have `grains_cache: true`, which probably contributed to some of the behaviour.

**Comment by OrangeDog** [comment]
I'm guessing this was caused by #57235, which was missing from the changelog.
