### ISSUE TITLE
[BUG] Problem with pcre matching in SLS files

### ISSUE THREAD

**Issue by johje349** [saltstack/salt#57745]
**Description**
After upgrading from 2018.3.4 to 2019.2.5 salt['match.pcre'] stopped working in SLS files.

**Setup**
Pillar file test.sls:
```
{% set host = grains['id'] %}
test:
{% if salt['match.pcre']("asx-u[0-9]", host) %}
  matchedMinion: True
{% else %}
  matchedMinion: False
{% endif %}
```

salt 'asx-u9' pillar.items:
```
test:
        ----------
        matchedMinion:
            False
```

**Expected behavior**
Expected matchedMinion: True

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 2019.2.5
 
Dependency Versions:
           cffi: 1.11.5
       cherrypy: 3.7.0
       dateutil: 2.4.2
      docker-py: 4.2.0
          gitdb: 0.6.4
      gitpython: 1.0.1
          ioflo: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.3
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.18
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.12 (default, Apr 15 2020, 17:07:12)
   python-gnupg: 0.3.8
         PyYAML: 3.11
          PyZMQ: 15.2.0
           RAET: Not Installed
          smmap: 0.9.0
        timelib: 0.2.4
        Tornado: 4.2.1
            ZMQ: 4.1.4
 
System Versions:
           dist: Ubuntu 16.04 xenial
         locale: UTF-8
        machine: x86_64
        release: 4.4.0-166-generic
         system: Linux
        version: Ubuntu 16.04 xenial
```
</details>

**Comment by krionbsd** [comment]
@johje349 thank you for submitting the report. I tried to reproduce it with 3001 but couldn't. Could you please try it with 3001?

**Comment by johje349** [comment]
@krionbsd it works in 3001.
Follow up question then. I use salt-cloud to install my minions, and it installs 3000.3 from http://repo.saltstack.com/apt/ubuntu/16.04/amd64. It seems 3001 is at another url: http://repo.saltstack.com/py3/ubuntu/16.04/amd64.

How can I make it install 3001?

My provider config:
do:
  driver: digital_ocean
  personal_access_token: xxxxx
  ssh_key_file: /etc/salt/pki/cloud/do.pem
  ssh_key_names: asx-salt
  script: bootstrap-salt

**Comment by johje349** [comment]
Found the answer to the follow up question:
Add script_args: -x python3

**Comment by krionbsd** [comment]
OK, it's nice it worked with 3001, can we close this issue now?
