### ISSUE TITLE
libvirt engine doesn't listen on storage events on recent libvirt

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#57746]
**Description**

The minion log shows the following when starting the libvirt-events engine even when running against a recent libvirt like 6.0.0:

```
Skipping "pool/lifecycle" events: libvirt too old
Skipping "pool/refresh" events: libvirt too old
Skipping "nodedev/lifecycle" events: libvirt too old
Skipping "nodedev/update" events: libvirt too old
```

Storage events have  been added in libvirt 2.0.0, so libvirt is not too old for them.

**Setup**

* Recent enough libvirt
* Enable libvirt-events engine with this in the minion config:

```yaml
engines:
  - libvirt_events
```

**Steps to Reproduce the behavior**

Start the minion and look into the logs. Once the minion started, you can also monitor the salt events on the master and at the same time start or stop a storage pool on the minion. No event related to the pool start or stop can be seen in the Salt events.

**Expected behavior**

* No warning for recent libvirt.
* Pool events should be reported as Salt events

**Versions Report**

Bug exising in master

**Comment by sagetherage** [comment]
I am not sure what happened here, but one PR wasn't merged and so this will go into Magnesium, I will attempt to track this more carefully.
