### ISSUE TITLE
[BUG] postgres.datadir_init parameter "waldir" nonfunctional

### ISSUE THREAD

**Issue by moench-tegeder** [saltstack/salt#57769]
**Description**
postgres.datadir_init does not create an external WAL directory when requested via the "waldir" parameter - the "waldir" parameter is not passed through to _run_initdb(): https://github.com/saltstack/salt/blob/master/salt/modules/postgres.py#L3596

**Setup**
no special setup neccessary

**Steps to Reproduce the behavior**
look at the code and it's obvious

**Expected behavior**
pass the given parameters

**Screenshots**

**Versions Report**
Support for "waldir" and "checksums" parameters to datadir_init() was added in 2019.2 but both parameters were not passed through to _run_initdb() (which makes me wonder if I screwed up back then or if there was some merge disaster?). The "checksums" parameter has been fixed in commit 35e2cacac6e4dfe21208434b2dea295c62561e9e but "waldir" has once again been missed, so here we go.
```
PASTE HERE
```
</details>

**Additional context**

**Comment by krionbsd** [comment]
@moench-tegeder could you please provide `salt --versions-report` for your report, thanks

**Comment by moench-tegeder** [comment]
there's so many versions, which one?
Here's git master as of yesterday, if that helps:

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.5.3 (default, Sep 27 2018, 17:25:39)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9 stretch
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-12-amd64
         system: Linux
        version: Debian GNU/Linux 9 stretch
````

WTF why did I get that Debian VM? whatever.

**Comment by sagetherage** [comment]
Looks like this didn't pass all tests and didn't get merged into master for the Magnesium release, moving to next release cycle Aluminium
