### ISSUE TITLE
distro/linux_distribution in 3001 breaks osrelease on Centos 7

### ISSUE THREAD

**Issue by mcuca1** [saltstack/salt#57781]
*Description*

In grains/core.py, v.3001 importing linux_distribution has been changed from:
```

import warnings
....

try:
    from platform import linux_distribution as _deprecated_linux_distribution

    def linux_distribution(**kwargs):
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            return _deprecated_linux_distribution(**kwargs)
   except ImportError:
       from distro import linux_distribution


```
to

```
from distro import linux_distribution
```

which results in os_release returning only the major release here (line 2035):

```
        (osname, osrelease, oscodename) = [
            x.strip('"').strip("'") for x in linux_distribution()
        ]

```
and failing to retrieve the correct osrelease and osrelease_info values:

```
    osrelease:
        7
    osrelease_info:
        - 7

```
This is occurring on Centos 7.4, salt v3001

salt versions:

Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 21 2020, 17:13:27)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-693.2.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core

**Comment by mcuca1** [comment]
I've been looking into this and from what I can see the problem is that in distro, when linux_distribution() calls version(), it doesn't use best=true which would return the full version, the logic is there:
```

    def linux_distribution(self, full_distribution_name=True):
        """
        Return information about the Linux distribution that is compatible
        with Python's :func:`platform.linux_distribution`, supporting a subset
        of its parameters.

        For details, see :func:`distro.linux_distribution`.
        """
        return (
            self.name() if full_distribution_name else self.id(),
            self.version(), # this should be self.version(best=True)
            self.codename()
        ) 
```
a solution would be to import name, version, codename separately or distro itself and then use best=true with version, for example, line 2028 in grains/core.py:
```

import distro

...

        # Use the already intelligent platform module to get distro info
        # (though apparently it's not intelligent enough to strip quotes)
        log.trace(
            "Getting OS name, release, and codename from distro"
            "distro.name(), distro.version(). distro.codename()"
        )
        (osname, osrelease, oscodename) = [
            x.strip('"').strip("'") for x in [distro.name(), distro.version(best=True), distro.codename()]
        ]


```

this works correctly on EL7, is it satisfactory as a solution? If yes I can complete testing and submit a PR,

thanks

**Comment by mcuca1** [comment]
I'm also noticing that in ubuntu the codename returned is different between platform and distro linux_distribution..eg.

```
>>> platform.linux_distribution()
('Ubuntu', '18.04', 'bionic')
>>> distro.linux_distribution()
('Ubuntu', '18.04', 'Bionic Beaver')


```

**Comment by OrangeDog** [comment]
The `oscodename` should ideally remain e.g. "bionic" on Ubuntu, because that's what you need for defining apt repos.
The `lsb_distrib_codename` grain is currently the same value, which could be used instead if necessary.

**Comment by mcuca1** [comment]
I can see that in python3-distro 1.4.0-1 the code is different and returns the short codename on ubuntu based on the ubuntu_codename key but that is in focal, python3-distro in bionic is 1.0.1

**Comment by OrangeDog** [comment]
I checked a couple others to confirm (Debian 9 actually prints in a different order, but that doesn't matter here).
```python
{'id': 'ubuntu', 'version': '20.04', 'version_parts': {'major': '20', 'minor': '04', 'build_number': ''}, 'like': 'debian', 'codename': 'focal'}
{'id': 'debian', 'version': '9.12', 'version_parts': {'major': '9', 'minor': '12', 'build_number': ''}, 'like': '', 'codename': 'stretch'}
```

**Comment by mcuca1** [comment]
@OrangeDog 
looks like this actually isn't an issue since it's already defaulting to lsb_distrib_codename and not actually using the distro sourced value:

```
        grains["oscodename"] = (
            grains.get("lsb_distrib_codename", "").strip() or oscodename
        )

```

**Comment by mcuca1** [comment]
I found out there are a number of tests that rely on calling the linux_distribution function in grains/core.py so we can't just replace it with the distro subfunctions, but we can define the function in core.py it similarly to how it was pre-3001 with the platform module, and use best=True when calling version().

Interestingly the linux_distribution tests in test_core.py do not include a CentOS and that's why this wasn't spotted in the first place, so I'm going to look into adding it as that would've prevented this

**Comment by mcuca1** [comment]
ok this is quite puzzling, now the PR is failing tests because there is a number of tests where the expected outputs do not include the minor versions, which I assumed would be correct:
https://jenkinsci.saltstack.com/job/pr-amazon2-py3/job/PR-57817/5/console

picking debian 8 for example you can see how the test is not expecting osrelease and osrelease_info to contain nothing more than the major version, do these tests need to be changed?

```
    def test_debian_8_os_grains(self):
        """
        Test if OS grains are parsed correctly in Debian 8 "jessie"
        """
        _os_release_map = {
            "linux_distribution": ("debian", "8.10", ""),
        }
        expectation = {
            "os": "Debian",
            "os_family": "Debian",
            "oscodename": "jessie",
            "osfullname": "Debian GNU/Linux",
            "osrelease": "8",
            "osrelease_info": (8,),
            "osmajorrelease": 8,
            "osfinger": "Debian-8",
        }
```

**Comment by OrangeDog** [comment]
I would change the tests to expect the full versions, yes. As I mentioned they have been missing possibly since forever.

If the version of distro can be guaranteed (e.g. with Tiamat) then all the relevant grains could be switched to a single `distro.info(best=True)`.

**Comment by mcuca1** [comment]
but how was it passing the debian tests in the previous versions where platform was returning the complete versions?

as for distro.info it doesn't have a name key so can't really replace linux_distribution, we'd still have to use distro.name as well and seems cleaner to just define linux_distribution as in the PR.

**Comment by OrangeDog** [comment]
> using distro.info seems less clean since it's returning a dict and that would be more changes to the code

It would only need to scan everything once, instead of repeating the whole process for every grain.
But as we've established the older versions give an undesired answer for codename.

**Comment by mcuca1** [comment]
Ok I figured it out, Debian uses `lsb_release.get_distro_information()` and the tests are not representative of that, they use local os-release file instead as source and it's normal that they return only the major version.

Since in test_core.py we use mock on linux_distribution so they are useless to detect a problem like this. I added a Centos 8 just for the sake of it anyway.

The PR should be good at this point, @OrangeDog since the codename problem is related to the distro module in general, doesn't make a difference what distro function we use, they all use codename(), so maybe there should be a minimum python3-distro minium version requirement for 3001 onwards?

**Comment by mcuca1** [comment]
Also, this is not just related to 3001, in <=3000.3 even though the platform module is sourcing the correct oselease, this is not used for centos 8, only centos 7, so the code instead should be changed to look as below

```
            # /etc/os-release contains no minor distro release number so we fall back to parse
            # /etc/centos-release file instead.
            # Commit introducing this comment should be reverted after the upstream bug is released.
            # This also affects Centos 8
            if any(
                os in grains.get("lsb_distrib_codename", "")
                for os in ["CentOS Linux 7", "CentOS Linux 8"]
            ):
```

**Comment by mcuca1** [comment]
@garethgreenaway could we add this to the 3001.1 bugfix project?

**Comment by sagetherage** [comment]
@mcuca1 I am attempting to find out if this can get into the bugfix release or not, I have added it to the project, apologies for missing this issue. thank you for mentioning me to get my attention.
