### ISSUE TITLE
[BUG] pidfile is removed on check

### ISSUE THREAD

**Issue by litnimax** [saltstack/salt#57794]
**Description**
This bug makes possible to start a few copies of minion because the PID file is removed during the process of startup of the 2nd minion.
This short video demonstrated it - http://youtu.be/Ac-IBu7qnLY

**Expected behavior**
Always detect a pif file and do not run.

**Versions Report**
Salt 3001.

**Comment by krionbsd** [comment]
Thanks for the report @litnimax, I can reproduce it as well

**Comment by krionbsd** [comment]
To summarize it:
```
root@freebsd-minion:~ # ps axuwww | grep salt
root     21055   0.0  0.0   524   336  1  R+   15:25       0:00.00 grep salt

root@freebsd-minion:~ # salt-minion -l info
[INFO    ] Setting up the Salt Minion "freebsd-minion"
[INFO    ] Starting up the Salt Minion
[INFO    ] Starting pull socket on /var/run/salt/minion/minion_event_68f13135ff_pull.ipc
[INFO    ] Creating minion process manager
[INFO    ] Executing command ['date', '+%z'] in directory '/home/ec2-user'
[INFO    ] Updating job settings for scheduled job: __mine_interval
[INFO    ] Added mine.update to scheduler
[INFO    ] Minion is starting as user 'root'
[INFO    ] Minion is ready to receive requests!
[INFO    ] Running scheduled job: __mine_interval

root@freebsd-minion:~ # ls -l /var/run/salt-minion.pid
-rw-r--r--  1 root  wheel  5 Jun 26 15:25 /var/run/salt-minion.pid

root@freebsd-minion:~ # salt-minion -l info
[INFO    ] Setting up the Salt Minion "freebsd-minion"
[INFO    ] An instance is already running. Exiting the Salt Minion
[INFO    ] Shutting down the Salt Minion
The Salt Minion is shutdown.

root@freebsd-minion:~ # ls -l /var/run/salt-minion.pid
ls: /var/run/salt-minion.pid: No such file or directory

root@freebsd-minion:~ # ps axuwww | grep salt
root     21057   0.0  3.7 48080 37316  1  I+   15:25       0:00.35 /usr/local/bin/python3.7 /usr/local/bin/salt-minion -l info
root     21060   0.0  6.9 86200 69716  1  S+   15:25       0:01.58 /usr/local/bin/python3.7 /usr/local/bin/salt-minion -l info
root     21061   0.0  3.9 51588 39768  1  I+   15:25       0:00.00 /usr/local/bin/python3.7 /usr/local/bin/salt-minion -l info
```

so if you run the second instance of salt-minion it does not terminate the parent of first PID, deletes PID file and binds again to master from different local port. So we have to check while starting the 2nd minion process if there's a running minion process, terminate it and remove the PID file and start the 2nd process afterwards.

**Comment by litnimax** [comment]
Так точно, Кирилл! Благодарю.

**Comment by cmcmarrow** [comment]
@litnimax I confirmed that master behaves as normal. The minion does not behave as normal. The minion that is trying to start should fail to start. We need to save the PID, PID_Name and PID_Start_Time. This will give us a very reliable way to know if the minion is running.

**Comment by krionbsd** [comment]
@cmcmarrow I agree with your proposal, we can't run 2 daemons simultaneously to bind to the master

**Comment by cmcmarrow** [comment]
@krionbsd I put in a fix.
