### ISSUE TITLE
[BUG] `salt-run saltutil.sync_all` extremely slow with GitFS enabled

### ISSUE THREAD

**Issue by Rudd-O** [saltstack/salt#57837]
**Description**
When running `salt-run saltutil.sync_all` in a GitFS-enabled Salt master, the time it takes for it to finish is directly proportional to the number of open branches in the GitFS backends.  Enabling trace logging indicates thousands and thousands of log messages saying that `envs.p` has been synced from GitFS cache.

This behavior occurs even with `top_file_merging_strategy: same` in the Salt master, and even when specifying `saltenv=base` in the command line.

**Expected behavior**
`sync_all` should only look at the corresponding, configured Salt environment passed on the command line, or (alternatively) follow the behavior that `sync_all` obeys (when `top_file_merging_strategy: same` is turned on, the modules are only downloaded from the branch corresponding to the `saltenv` configured in the minion, defaulting to `base`).

**Screenshots**

**Versions Report**
Latest Salt 3000, on Ubuntu 16.04.5.  Minion not involved.

**Comment by cmcmarrow** [comment]
This sounds like an oversite with `envs.p` or at best its poorly optimized. At first look I agree with your expected behavior. How long does is take to run `salt-run saltutil.sync_all`? Thanks for the bug report @Rudd-O

**Comment by Rudd-O** [comment]
~3 minutes with 800 branches in the GitFS repo.

~3 seconds on the same configuration with one branch.

**Comment by sagetherage** [comment]
@cmcmarrow please follow up, thank you!

**Comment by sagetherage** [comment]
looks like we still have not gotten to this work yet, I will attempt to get it assigned for the Silicon release cycle

**Comment by whytewolf** [comment]
I've been looking into this and on 3004.1 I have been unable to replicate the issue. I'm wondering f this was fixed elsewhere. can you try again on 3004.1 and see if it is still happening. it does take a while for one part as it does fetch the gitfs filesystem. but i don't see the evns.p reload happening

**Comment by garethgreenaway** [comment]
Closing this out due to lack of activity.

**Comment by Rudd-O** [comment]
I have stopped using SaltStack API and server.  Cannot repro anymore.
