### ISSUE TITLE
[BUG] user.present(gid_from_name=True) causes rendering error

### ISSUE THREAD

**Issue by shish** [saltstack/salt#57843]
**Description**
Looking at the docs, salt.states.user.present() appears to have dropped the gid_from_name parameter? My .sls file still included it and it took ages to figure out that that was causing a rendering failure

**Steps to Reproduce the behavior**
Have a state with
```
user.present:
  - gid_from_name: True
```

**Expected behavior**
Error: "gid_from_name is not a valid parameter for user.present()"

**Screenshots**
```
[ERROR   ] JSON Render failed for: Execute a packaged state run, the packaged state run will exist in a
    tarball available locally. This packaged state
    can be generated using salt-ssh.

include:
    CLI Example:

    .. code-block:: bash

        salt '*' state.pkg /tmp/salt_state.tgz 760a9353810e36f6d81416366fc426dc md5
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: 1.12.2
       cherrypy: unknown
       dateutil: 2.8.0
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 2.1.15
         Jinja2: 2.10.1
        libgit2: 1.0.1
       M2Crypto: 0.35.2
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: Not Installed
   pycryptodome: 3.9.7
         pygit2: 1.2.1
         Python: 3.7.7 (default, Mar 10 2020, 15:43:33)
   python-gnupg: 0.4.4
         PyYAML: 5.1.2
          PyZMQ: 18.0.1
          smmap: 3.0.4
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: darwin 19.5.0
         locale: UTF-8
        machine: x86_64
        release: 19.5.0
         system: Darwin
        version: 10.15.5 x86_64
```
</details>

**Comment by cmcmarrow** [comment]
@shish Thanks for the report. It is currently a goal for the next update to improve SLS errors.

**Comment by terminalmage** [comment]
This looks to have been removed without a deprecation path, and replaced with an argument called `usergroup`. @shish you should be able to start using `usergroup` and it should work.

In the meantime, @cmcmarrow, I opened https://github.com/saltstack/salt/pull/57870 to restore `gid_from_name` and put it on a deprecation path. It would be helpful to try to get this into the 3001.1 release.
