### ISSUE TITLE
[FEATURE REQUEST] Add ability to profile jinja code

### ISSUE THREAD

**Issue by jfindlay** [saltstack/salt#57849]
### Description
Add profile block and profiling of import_* jinja calls.

### Example
```sls
# cat /srv/salt/example.sls 
{%- profile as 'local data' %}
  {%- set local_data = {'counter': 0} %}
  {%- for i in range(313377) %}
    {%- do local_data.update({'counter': i}) %}
  {%- endfor %}
{%- endprofile %}

test:
  cmd.run:
    - name: |-
        printf 'local data: %s' '{{ local_data['counter'] }}'
```

### Motivation

When working with a very large codebase, it becomes more important to trace inefficiencies in state and pillar render times.  The `profile` jinja block enables the user to get finely detailed information on the most time consuming jinja expressions in the codebase.

Especially as the codebase grows and the amount of minions increases, tracking down expensive expressions becomes imperative otherwise the resource burden for even just maintaining highstate becomes unmanageable.

**Comment by cmcmarrow** [comment]
@jfindlay I can see why you want this feature add it to salt. I can not give you a time frame or even promise this feature will be add it. If you really want to see this feature add it to salt we be happy to accept a PR from you. This Feature Request will be brought up in a meeting in a week or two. Their we will determine if a Salt Stack employee will add this feature in a later version of salt.

**Comment by jfindlay** [comment]
@cmcmarrow, I have implemented the feature in the shown linked pull request.  Do you know what I need to do to get it approved?

**Comment by sagetherage** [comment]
@jfindlay I have asked for review from more Core Team members and I will follow up, here, thank you for the PR!
