### ISSUE TITLE
template replace function not working with underscore

### ISSUE THREAD

**Issue by ysagon** [saltstack/salt#57844]
### Description of Issue
The replace function in a jinja template isn't working as expected when using underscore.

### Setup
```
- template: jinja
        - context:
            beegfs_version: {{ salt['pillar.get']('beegfs:version') | replace(".", "_") }} 
```
The value of `beegfs:version` is `7.1` and I would expect `beegfs_version` to be `7_1`. The actual result is `71`

**Comment by whytewolf** [comment]
This is not a bug, nor is it a problem with the replace.

you are running into this https://docs.saltstack.com/en/master/topics/troubleshooting/yaml_idiosyncrasies.html#underscores-stripped-in-integer-definitions

change 

```
- template: jinja
        - context:
            beegfs_version: {{ salt['pillar.get']('beegfs:version') | replace(".", "_") }} 
```

To 

```
- template: jinja
        - context:
            beegfs_version: "{{ salt['pillar.get']('beegfs:version') | replace(".", "_") }}"
```

And it will work.
