### ISSUE TITLE
master_tops interface inconsistent with ext_pillar

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#5786]
(updated on 3 July 2013)

The `master_tops` interface should really be the same as that of `ext_pillar`, that is,
- the config should take a list of hashes, not a hash of hashes, to preserve order and for consistency.
- the `top()` function should receive not opts and grains, but the configuration of the plugin from the `master_tops` config section, like `ext_pillar`.

**Comment by arroyoc** [comment]
We are closing this ticket due to inactivty, if anyone @thatch45 @madduck feels that this feature needs further attention feel free to re-open it.

**Comment by madduck** [comment]
I maintain that this should be fixed. Closing this just means this won't ever happen, while leaving it open at least serves as a reminder.

**Comment by thatch45** [comment]
Will do @madduck

**Comment by madduck** [comment]
@arroyoc I cannot reopen issues.
