### ISSUE TITLE
Installing Salt as Snap package (Ubuntu Core)

### ISSUE THREAD

**Issue by GiorgioNunzi** [saltstack/salt#57872]
Hi everyone,

I am looking at installing Salt on Ubuntu Core.
Currently, there are installation instructions for Ubuntu (Desktop/Server), but Ubuntu Core works differently.

Basically, a Snap package is needed, and the installation would be snap install salt-master or snap install salt-minion.

Is there anything available already?

Thanks for any hint!

**Comment by s0undt3ch** [comment]
@chxlumen currently, there are no plans on providing a snap package

**Comment by s0undt3ch** [comment]
I added this issue to the approved milestone but please be advised that it does not mean that SaltStack is committed to fullfil the feature request.

**Comment by asphaltbuffet** [comment]
Also interested in this if it were available.

**Comment by rksawyer** [comment]
Using salt stack to manage Ubuntu Core's transactional snap-based updates would be a powerful combination for IOT edge devices.
