### ISSUE TITLE
Error while creating users for MySQL versions prior to 5.6

### ISSUE THREAD

**Issue by apwrv** [saltstack/salt#57902]
### Description of Issue
mysql_user.present state throws an error while trying to create an user on MySQL Server whose version is prior to 5.6.
Following is the error;
`MySQL Error 1054: Unknown column 'plugin' in 'field list'`

### Setup
My current setup,
MySQL server: 5.1.3 (I know this is quite old but we have an application that is in the process of migration and have to make do with this till the parallel testing is successful)
Salt: 3000.3
Oracle Enterprise Linux 6 Update 10 with Python 2.7.13

### Steps to Reproduce Issue
Try creating a user for MySQL server whose version is less than 5.6. 

### Applied Fix
This error is due to the `__get_auth_plugin()` of **_modules/mysql.py_** throwing an error instead of just returning the `mysql_native_password` as output. Since `__context__[mysql.error]` is set, state is deemed as erroneous even though the function return `mysql_native_password`. 
**Removal of this error reporting will get the user created and the state goes through.**

### Versions Report
```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.1
   mysql-python: 1.2.5
      pycparser: 2.19
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, May  8 2020, 22:36:22)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.0.5

System Versions:
           dist: redhat 6.10 Santiago
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.1.12-124.38.1.el6uek.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 6.10 Santiago
```

### Question:
Will this bug be patched in any version of salt or is MySQL v < 5.6 declared as unsupported?

**Comment by sagetherage** [comment]
@garethgreenaway can you help answer this question, please? Thank you!

**Comment by frogunder** [comment]
@apwrv Thank you for reporting this issue.

You are right about that 5.1.3 is a bit old. 
I will have to reach out to the core team for an answer to your question. My first thought though, is that it will not but let's check with them.

@saltstack/team-core can I get your thoughts on this question, related to supporting version `MySQL server: 5.1.3`
`Will this bug be patched in any version of salt or is MySQL v < 5.6 declared as unsupported?` 


Thanks.

**Comment by waynew** [comment]
@apwrv Thanks for the issue. I think that, given the age of your MySQL version you have a couple of options:

- Downgrade Salt to a version (if any) that still had support for this older version of MySQL
- Patch your existing Salt installation
- Write a custom [module](https://docs.saltstack.com/en/latest/ref/modules/index.html)/[state](https://docs.saltstack.com/en/latest/ref/states/writing.html) that does the operations that you need in older MySQL.

But unfortunately, as MySQL 5.6 was EOLed back in 2018, that's not something that SaltStack is going to support.

If you get stuck writing states/modules, feel free to reach out to the community in the #salt channel on IRC, in the Salt Community Slack, or the salt-users Google Group.

HTH!

**Comment by sagetherage** [comment]
@apwrv let us know if this solve what you need here, if not mention myself or Wayne to open the issue. Thanks!

**Comment by apwrv** [comment]
It does answer my question. Thank you.
Will continue patching till we migration our environment to the latest version of MySQL.
