### ISSUE TITLE
[BUG] "superseded" means the old thing

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#57919]
Therefore the config option `use_superseded` has the opposite meaning to what it does.

> v. To be discarded or discontinued as useless or obsolete; to be replaced by something else. 
> adj. No longer in use.

**Comment by OrangeDog** [comment]
The only thing that uses it is the `module.run` state.

As the styles are mutually-exclusive, the state could be written to support both (and warn on the old one), without any need for a config option. The misnamed option can then simply be deleted.

**Comment by max-arnold** [comment]
I just learned that @meaksh implemented a compatibility layer that can automatically handle the differences between the `module.run` syntaxes: https://github.com/uyuni-project/uyuni/blob/master/susemanager-utils/susemanager-sls/src/states/mgrcompat.py

**Comment by OrangeDog** [comment]
That's a slightly different approach - it detects what it "should" be, and converts the input to be that.
I meant something that detects which style it is, and runs it (which could be by always converting to the new format).

Or, given it's been deprecated for a while, the old style could simply be dropped, and the config option along with it.
