### ISSUE TITLE
[BUG] module/network.py uses platform.is_windows on Windows

### ISSUE THREAD

**Issue by prensing** [saltstack/salt#57948]
**Description**
I have installed (via an update) version 3001 on various Windows machines. I am getting hourly log entries complaining about "platform.is_windows" inside modules/network.py.

**Setup**
Python 3 installation of salt-minion version 3001 on Windows (various OS versions). I have mine in pillar:

```
> mine_functions:
>   test.ping: []
>   network.ip_addrs: []
> 
```

**Steps to Reproduce the behavior**
Seems to be an automatic run hourly

**Log file entries**
```
2020-07-15 10:06:56,698 [salt.loader      :2000][ERROR   ][3260] Exception raised when processing __virtual__ function for salt.loaded.int.module.network. Module will not be loaded: 'platform.is_windows'
Traceback (most recent call last):
  File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\loader.py", line 1983, in _process_virtual
    virtual = getattr(mod, virtual_func)()
  File "c:\salt\bin\lib\site-packages\salt-3001-py3.7.egg\salt\modules\network.py", line 38, in __virtual__
    if __utils__["platform.is_windows"]():
KeyError: 'platform.is_windows'
2020-07-15 10:06:56,698 [salt.loader      :2018][WARNING ][3260] salt.loaded.int.module.network.__virtual__() is wrongly returning `None`. It should either return `True`, `False` or a new name. If you're the developer of the module 'network', please fix this.
```

**Versions Report**
From the minion:
<details>
    Salt Version:
               Salt: 3001
     
    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.9.7
             pygit2: Not Installed
             Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 5.1.2
              PyZMQ: 18.0.1
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1
     
    System Versions:
               dist:   
             locale: cp1252
            machine: AMD64
            release: 2012ServerR2
             system: Windows
            version: 2012ServerR2 6.3.9600 SP0
</details>

**Additional context**

**Comment by alexey-zhukovin** [comment]
@thank you
Could you provide version of salt previously installed?
Was it 3000.3?

**Comment by prensing** [comment]
The machine (there are a bunch of them) goes back to at least 2019.3, almost certainly early, and it used to have the Py2 version. I don't know for sure whether they also had 3000.x (probably some have).

**Comment by prensing** [comment]
Hmm, looks like the log entry got a little mangled by Markdown. If you need a clean version, let me know.

**Comment by twangboy** [comment]
Could you modify the `network.py` file to use a hard import instead of the `__utils__`.

To do that, add `import salt.utils.platform` to the imports above in the file
Then replace the `__utils__["platform.is_windows"]()` with `salt.utils.platform.is_windows()` in the `__virtual__` function.

Restart salt and see if the messages continue to appear in the minion log.

**Comment by prensing** [comment]
I am happy to try, but I found 5 files called "network.py" in the Salt directory. Which should I edit?

**Comment by prensing** [comment]
I updated modules/network.py the instructions. I will report back in a day or so.

**Comment by prensing** [comment]
Yes, that does seem to fix the hourly log messages.
