### ISSUE TITLE
After upgrade to 3001, salt master throwing errors for network.py "name '__utils__' not found".

### ISSUE THREAD

**Issue by tjones136** [saltstack/salt#57940]
### Description of Issue
salt-master throwing errors after upgrade:
```
2020-07-14 17:19:48,376 [salt.loader      :870 ][CRITICAL][53069] Failed to load grains defined in grain file subnetZone.main in function <function main at 0x7f835763c8c8>, error:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/loader.py", line 859, in grains
    ret = funcs[key](**kwargs)
  File "/var/cache/salt/master/extmods/grains/subnetZone.py", line 317, in main
    grains['networkZone'] = findZone()
  File "/var/cache/salt/master/extmods/grains/subnetZone.py", line 219, in findZone
    internalips = salt.modules.network.ip_addrs(cidr='172.16.0.0/16')
  File "/usr/lib/python3.6/site-packages/salt/modules/network.py", line 1287, in ip_addrs
    addrs = __utils__["network.ip_addrs"](
NameError: name '__utils__' is not defined
```

### Setup
Fresh upgrade from 2019.2.0 to 3001, all done via rpm packages.

### Steps to Reproduce Issue
Errors appearing in `/var/log/salt/master`, new error messages several times a minute. 

### Versions Report
```
# salt --versions-report
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Sep 26 2019, 11:57:09)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: rhel 7.8 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.8 Maipo
```

**Comment by max-arnold** [comment]
Looks somewhat similar to https://github.com/saltstack/salt/issues/56619

1. A custom module is involved (`subnetZone.py`). Anything can happen in custom code and it would be hard to reproduce the problem without this module.

2. A likely culprit is here `salt.modules.network.ip_addrs(cidr='172.16.0.0/16')`

Execution modules are [not available](https://docs.saltstack.com/en/master/topics/development/modules/developing.html#salt) in grains through the `__salt__` dunder (because they can depend on grains). So it looks like you imported the `salt.modules.network` directly as a workaround. When you do so, Salt loader is unable to inject the magic dunders (`__salt__`, `__utils__`, etc.). That is why it can't find `__utils__`.

The problem is that I have no idea how it ever worked in the past.

**Comment by tjones136** [comment]
_The problem is that I have no idea how it ever worked in the past._

That makes two of us.  Inherited this while the creators ran off to greener pastures.  I'll took a look into subnetZone.py and salt.modules.network.ip_addrs to see what, if anything, I can find.

Thanks for at least pointing me in a direction.

**Comment by max-arnold** [comment]
If that is just one call from `subnetZone.py` to `salt.modules.network.ip_addrs`, one possible (and dirty) solution is to replace it with the following implementation (e.g., inline the code, including the `is_private` function): https://github.com/saltstack/salt/blob/9536d322acf35931baaf0e780528c56334d718cd/salt/modules/network.py#L1287-L1298

`__utils__` [are available](https://docs.saltstack.com/en/master/topics/development/modules/developing.html#utils) inside grains, so this should work.
