### ISSUE TITLE
[BUG][Failing Test] VMWare Cloud tests are failing

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#57964]
**Description**
After https://github.com/saltstack/salt/pull/57913 got merged, cloud tests started running again(they were previously being skipped) and we now have a few failures
* integration.cloud.clouds.test_vmware.VMWareTest.test_instance
* integration.cloud.clouds.test_vmware.VMWareTest.test_instance

https://jenkinsci.saltstack.com/job/pr-centos7-py3-cloud/job/master/

**Comment by Ch3LL** [comment]
closing in favor of https://github.com/saltstack/salt/issues/58334  since vmware was passing for a while.
