### ISSUE TITLE
Salt Job results in a mail

### ISSUE THREAD

**Issue by karkey-salt** [saltstack/salt#57982]
I have an orchestration file which executes some Task A, Task B.. etc. 

Looking for some solution on the below:
1. How to store the result of the task and send that result in a mail.
2. At the end of Orchestration, I want to get the result of the job in a email automatically (which includes success/failure)

If anyone have any suggestion, please guide me with the complete steps.

My salt master version is 2019.2.3 and 3001.

**Comment by krionbsd** [comment]
I don't think we provide the solution for this out of the box, but anyway you might write a custom module to get it done, you might require running MTA on the server, working DNS/FQDN etc.

**Comment by sagetherage** [comment]
@karkey-salt please let us know if we have answered your question and can close the ticket or not.
