### ISSUE TITLE
[BUG] Unaccepted minions returning jobs from '*' targeting

### ISSUE THREAD

**Issue by jtraub91** [saltstack/salt#58005]
**Description**
Minions which are not included in the accepted keys list from `salt-key -L` nor `ls /etc/salt/pki/master/minions` are connected and returning when using `*` targeting.

**Setup**
`auto_accept: True` on the master. These might have been minions which were previously accepted but now are not. 

**Steps to Reproduce the behavior**
Issue `salt \* test.ping`. Observe minions which respond, that are not listed under accepted keys.

**Expected behavior**
Minions which are not in accepted keys should not be able to communicate with a salt master, at all. 

**Versions Report**
```
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.8
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 8.2.2004 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.18.1.el7.x86_64
         system: Linux
        version: CentOS Linux 8.2.2004 Core
```

**Comment by krionbsd** [comment]
Hey @jtraub91 thanks for the report, how did you revoke the keys which are no longer accepted by master?

**Comment by jtraub91** [comment]
@krionbsd manually deleting the file in `/etc/salt/pki/master/minions/<minionid>`

**Comment by krionbsd** [comment]
@jtraub91 did you restart minion after deleting the file?

**Comment by jtraub91** [comment]
No

**Comment by sagetherage** [comment]
@jtraub91 can you try restarting the minion after deleting the file?

**Comment by jtraub91** [comment]
That's avoiding the issue because you need to restart a minion in which you've just deleted the key, thus removed authentication.

However, I think the issue does not occur if you use the `salt-key -d` utility instead of manually deleting the files.

**Comment by sagetherage** [comment]
@jtraub91 I was simply following up, is this still an issue?

**Comment by krionbsd** [comment]
@jtraub91 I think we might close it

**Comment by jtraub91** [comment]
I think the resolution was to always use `salt-key` or the wheel module to delete minion keys. There seemed to be a weird edge condition if you deleted the files, the key was retained in memory for some period of time.

**Comment by sagetherage** [comment]
Yes, and we have an issue to document better the rotation of keys, perhaps we need more about specifics on this use case as well. Here is that key rotation doc issue: https://github.com/saltstack/salt/issues/57725

**Comment by sagetherage** [comment]
@jtraub91 closing this in favor of the documentation issue, let us know if it needs to be reopened for an edge case in master.
