### ISSUE TITLE
Elasticsearch returner fails when index exists.

### ISSUE THREAD

**Issue by waynegemmell** [saltstack/salt#58015]
### Description of Issue
When I trigger the elasticsearch returner the first time an index is created, on subsequent calls it just fails. 

### Setup
```
elasticsearch:
    hosts:
      - "elastic7:9200"
      - "elastic8:9200"
    index_date: False
    number_of_shards: 3
    number_of_replicas: 1
    debug_returner_payload: True
    states_count: True
    states_order_output: True
    states_single_index: True
```

### Steps to Reproduce Issue
Trigger the returner. 

Here's the logs
```
2020-07-23 16:19:52,469 [salt.minion      :2022][ERROR   ][29262] The return failed for job 20200723141934627314: 'elasticsearch.index_exists'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/minion.py", line 2011, in _thread_return
    minion_instance.returners[returner_str](ret)
  File "/usr/lib/python3/dist-packages/salt/returners/elasticsearch_return.py", line 301, in returner
    _ensure_index(index)
  File "/usr/lib/python3/dist-packages/salt/returners/elasticsearch_return.py", line 177, in _ensure_index
    index_exists = __salt__["elasticsearch.index_exists"](index)
  File "/usr/lib/python3/dist-packages/salt/loader.py", line 1278, in __getitem__
    func = super(LazyLoader, self).__getitem__(item)
  File "/usr/lib/python3/dist-packages/salt/utils/lazy.py", line 108, in __getitem__
    raise KeyError(key)
KeyError: 'elasticsearch.index_exists'
```

### Versions Report

```
salt --versions-report
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: 1.3.10
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pygit2: Not Installed
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-101-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver

```

**Comment by krionbsd** [comment]
@waynegemmell thanks for the report, could you please provide elastic version you're using?

**Comment by waynegemmell** [comment]
Elastic 7.8

**Comment by cmcmarrow** [comment]
@waynegemmell thanks for the report. Salt can find index_exists and it exists. I don’t know why it cant find it but this is a bug.

**Comment by garethgreenaway** [comment]
@waynegemmell Looking into this I saw the exception that you mentioned because I didn't have the Python `elasticsearch` library installed which is needed by the elastichsearch Salt module, which the returner is calling when checking that the index exists.  Can you verify that you have that library installed?  Thanks!

**Comment by waynegemmell** [comment]
I do have it. I mean, it must be, indexes are being made. That's not really the problem though.

**Comment by garethgreenaway** [comment]
@waynegemmell The error you're seeing means that Salt loader was unable to find `elasticsearch.index_exists`.  Two possible causes, 1) the entire module was unable to be loaded because the elasticsearch library is not installed so the virtual function returned False, 2) there is an older custom version installed on the minion that doesn't have the `index_exists` function available.

**Comment by waynegemmell** [comment]
Ok, I'll run it again tomorrow and experiment. There definitely are no custom versions and salt is writing to elasticsearch. It was creating the indexes and then failing the second time. I'll verify all this asap, it's been a while since I looked at it.
