### ISSUE TITLE
[BUG] s3fs file server fails with "Failed to load function s3fs.envs because its module (s3fs) is not in the whitelist: ['s3']"

### ISSUE THREAD

**Issue by ant1m** [saltstack/salt#58041]
**Description**
Salt-master doesn't put up s3fs-based file server, with error message "Failed to load function s3fs.envs because its module (s3fs) is not in the whitelist: ['s3']".
salt-run fileserver.file_list returns the same error.

**Setup**

/etc/salt/master.d/00-master.conf : 

fileserver_backend:
  - s3fs

s3.keyid: XXX
s3.key: XXX
s3.service_url: XXX
s3.https_enable: True
s3.path_style: True
s3.verify_ssl: False
s3.location: eu-west-0

s3fs_saltenv_whitelist:
  - base
  - master
  - devel

s3.buckets:
  base:
    - xxxxx

etc.

**Steps to Reproduce the behavior**
Configure the master to use s3fs backend and start.
Run salt-run fileserver.file_list.

**Expected behavior**
With no whitelist configured, there should not be need to add a module to the whitelist. The backend should not throw this error and the file server should be running.

**Versions Report**
<details><summary>
</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Dec 20 2019, 18:57:59)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-8-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster

```
</details>

**Additional context**
If the lines 1885 to 1893 of /usr/lib/python3/dist-packages/salt/loader.py are commented : 

    if self.whitelist and mod_name not in self.whitelist:
                log.error(
                    "Failed to load function %s because its module (%s) is "
                    "not in the whitelist: %s",
                    key,
                    mod_name,
                    self.whitelist,
                )
                raise KeyError(key)

the file server runs ok.

**Comment by cmcmarrow** [comment]
@ant1m that does seems wrong to me too. Thanks for the bug report.

**Comment by Timbus** [comment]
Yeah this just bit me, how annoying.
It's because of this wacky logic:
https://github.com/saltstack/salt/blob/35c5671d635eb6068dac720990f27c6d79d22311/salt/loader.py#L507

Seems to trim 'fs' off of the module name, then add it back if it's one of the three VCS modules. I can only hope this is some weird legacy thing. 
Anyway since 's3fs' doesn't match 's3' it fails. However since the master doesn't die if you give it a module that doesn't exist... Here's the horrendous workaround:
```yaml
 fileserver_backend:
   - s3fs
   - s3fsfs
```
