### ISSUE TITLE
Master not gracefully shutting down on Ctrl-C (again)

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#5810]
This is a reopen of #3032:

    […]
    [INFO    ] Worker binding to socket ipc:///home/madduck/code/salt/local/run/master/workers.ipc
    [INFO    ] Worker binding to socket ipc:///home/madduck/code/salt/local/run/master/workers.ipc
    [INFO    ] Worker binding to socket ipc:///home/madduck/code/salt/local/run/master/workers.ipc
    [INFO    ] Worker binding to socket ipc:///home/madduck/code/salt/local/run/master/workers.ipc
    [INFO    ] Worker binding to socket ipc:///home/madduck/code/salt/local/run/master/workers.ipc
    ^C^C[WARNING ] Stopping the Salt Master

Unfortunately, *sometimes* two Ctrl-C hits are required to stop the master.

**Comment by rallytime** [comment]
I tested this at the HEAD of 2015.5 just now and it has been fixed. Closing.

If this pops up again, feel free to open a new issue. Thanks!
