### ISSUE TITLE
[BUG] ConvertTo-JSON in win_servermanager is failing on Win 2008 R2

### ISSUE THREAD

**Issue by bsoldhogg** [saltstack/salt#58123]
**Description**
Running `win_servermanager.list_installed` against a minion running Windows Server 2008 R2 SP1 fails as ConvertTo-JSON is not recognised

**Setup**
No special setup, just trying to pull back the list of installed features on a 2008 R2 minion using the execution module win_servermanager.list_installed

**Steps to Reproduce the behavior**

`ERROR: The term 'ConvertTo-Json' is not recognized as the name of a cmdlet, function, . Additional info follows:

    retcode:
        1
    stderr:
        The term 'ConvertTo-Json' is not recognized as the name of a cmdlet, function,
        script file, or operable program. Check the spelling of the name, or if a path
        was included, verify that the path is correct and try again.
        At line:1 char:163
        + Import-Module ServerManager; Get-WindowsFeature -ErrorAction SilentlyContinue
         -WarningAction SilentlyContinue | Select DisplayName,Name,Installed | ConvertT
        o-Json <<<<
            + CategoryInfo          : ObjectNotFound: (ConvertTo-Json:String) [], Comm
           andNotFoundException
            + FullyQualifiedErrorId : CommandNotFoundException
    stdout:
`

**Expected behavior**
I would expect Salt to handle the error by checking OS and powershell versions, similar to this issue #36902, and use an alternative method to gather the information.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.4.7
         pygit2: 0.26.2
         Python: 3.6.9 (default, Apr 18 2020, 01:56:04)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-101-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver


minion:

Salt Version:
               Salt: 3001

    Dependency Versions:
               cffi: 1.12.2
           cherrypy: 17.4.1
           dateutil: 2.8.0
          docker-py: Not Installed
              gitdb: 2.0.5
          gitpython: Not Installed
             Jinja2: 2.10.1
            libgit2: Not Installed
           M2Crypto: Not Installed
               Mako: 1.0.7
       msgpack-pure: Not Installed
     msgpack-python: 0.5.6
       mysql-python: Not Installed
          pycparser: 2.19
           pycrypto: Not Installed
       pycryptodome: 3.9.7
             pygit2: Not Installed
             Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 20:34:20) [MSC v.1916 64 bit (AMD64)]
       python-gnupg: 0.4.4
             PyYAML: 5.1.2
              PyZMQ: 18.0.1
              smmap: 2.0.5
            timelib: 0.2.4
            Tornado: 4.5.3
                ZMQ: 4.3.1

    System Versions:
               dist:
             locale: cp1252
            machine: AMD64
            release: 2008ServerR2
             system: Windows
            version: 2008ServerR2 6.1.7601 SP1

```
</details>

**Comment by garethgreenaway** [comment]
@bsoldhogg Thanks for the report.

@cmcmarrow Can you take a look at this one?  It looks like we're using the right module and the right shell in this call.  I wonder if 
"ConvertTo-JSON" is not available in the version of Powershell that is installed?

**Comment by bsoldhogg** [comment]
It's running Powershell 2.0, although I've since upgraded it to 5.1 so I can proceed with what I was doing.

**Comment by lubyou** [comment]
> @bsoldhogg Thanks for the report.
> 
> @cmcmarrow Can you take a look at this one? It looks like we're using the right module and the right shell in this call. I wonder if
> "ConvertTo-JSON" is not available in the version of Powershell that is installed?

2008 R2 / 7 come with Powershell 2, ConvertTo-Json does not exist before Powershell 3

**Comment by twangboy** [comment]
We're not going to do this as everything now ships with PS 3+
