### ISSUE TITLE
[BUG] Salt reactor does not support all-digital minion_id

### ISSUE THREAD

**Issue by xiwangqi** [saltstack/salt#58134]
**Description**
Salt reactor does not support all-digital minion_id.

**Setup**
salt-master 3001

/etc/salt/master.d/reactor.conf
```
`reactor:
    - 'salt/minion/*/start':
      - /srv/reactor/sync.sls`
```

/srv/reactor/sync.sls
```
sync_everything:
  local.saltutil.sync_all:
    - tgt: {{ data['id'] }}
    - kwarg:
        refresh: True
```

**Steps to Reproduce the behavior**
Execute in minion： systemctl restart salt-minion
Get Error in salt master log:
`2020-08-05 14:13:49,022 [salt.utils.minions:749 ][ERROR   ][17576] Failed matching available minions with glob pattern: 2001
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/utils/minions.py", line 737, in check_minions
    _res = check_func(expr, greedy)  # pylint: disable=not-callable
  File "/usr/lib/python3/dist-packages/salt/utils/minions.py", line 240, in _check_glob_minions
    return {"minions": fnmatch.filter(self._pki_minions(), expr), "missing": []}
  File "/usr/lib/python3.6/fnmatch.py", line 51, in filter
    pat = os.path.normcase(pat)
  File "/usr/lib/python3.6/posixpath.py", line 54, in normcase
    s = os.fspath(s)
TypeError: expected str, bytes or os.PathLike object, not int`

Then
I try to modify the source code
/usr/lib/python3/dist-packages/salt/utils/minions.py
line 240  old
return {"minions": fnmatch.filter(self._pki_minions(), expr), "missing": []}
line 240  change
return {"minions": fnmatch.filter(self._pki_minions(), str(expr)), "missing": []}

Final
I can get the event trigger from the event log, but there is no return, and the minion did not execute successfully.

So how to solve the problem quickly ？？？

**Expected behavior**
ok

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by rossengeorgiev** [comment]
Formulates are yaml, so numbers will be converted to type `int`. In the template, you can cast to string and use yaml filter to get correctly format string:

```yaml
- tgt: {{ data['id']|string|yaml }
```

**Comment by garethgreenaway** [comment]
@xiwangqi Thanks for the report.  Can you confirm if the suggestion by @rossengeorgiev fixes the issue for you?

**Comment by sagetherage** [comment]
@xiwangqi closing for now, please let us know if you need anything
