### ISSUE TITLE
[BUG] grain dict order is not maintained

### ISSUE THREAD

**Issue by Prakash82x** [saltstack/salt#58145]
**Description**
While trying to retrieve some grains of few minions, the return order of grains  (key value) is not maintained at every execution and gets randomized while using --out=text.

**Setup**
I am trying to retrieve grains of following list of minions as below:
```
[root@saltit-master ~]# salt -L "minion2.domain.com,minion1.domain.com,minion3.domain.com,minion4.domain.com" grains.item os osfullname region osrelease manufacturer productname --out=text
```

**Steps to Reproduce the behavior**
Every time the above command is executed the return of grains is in different order I have pasted sample output from two executions below.
```
[root@saltit-master ~]# salt -L "minion2.domain.com,minion1.domain.com,minion3.domain.com,minion4.domain.com" grains.item os osfullname region osrelease manufacturer productname --out=text
minion1.domain.com: {'osrelease': '2012ServerR2', 'region': 'Region1', 'productname': 'VMware Virtual Platform', 'osfullname': 'Microsoft Windows Server 2012 R2 Standard', 'os': 'Windows', 'manufacturer': 'VMware, Inc.'}
minion2.domain.com: {'region': 'Region2', 'manufacturer': 'VMware, Inc.', 'productname': 'VMware Virtual Platform', 'osrelease': '2019Server', 'osfullname': 'Microsoft Windows Server 2019 Standard', 'os': 'Windows'}
minion3.domain.com: {'os': 'Windows', 'osfullname': 'Microsoft Windows Server 2012 R2 Standard', 'productname': 'VMware Virtual Platform', 'osrelease': '2012ServerR2', 'manufacturer': 'VMware, Inc.', 'region': 'Region2'}
minion4.domain.com: {'region': 'Region2', 'manufacturer': 'VMware, Inc.', 'productname': 'VMware Virtual Platform', 'osrelease': '2019Server', 'os': 'Windows', 'osfullname': 'Microsoft Windows Server 2019 Standard'}

[root@saltit-master ~]# salt -L "minion2.domain.com,minion1.domain.com,minion3.domain.com,minion4.domain.com" grains.item os osfullname region osrelease manufacturer productname --out=text
minion1.domain.com: {'osrelease': '2012ServerR2', 'region': 'Region1', 'productname': 'VMware Virtual Platform', 'osfullname': 'Microsoft Windows Server 2012 R2 Standard', 'os': 'Windows', 'manufacturer': 'VMware, Inc.'}
minion2.domain.com: {'manufacturer': 'VMware, Inc.', 'os': 'Windows', 'productname': 'VMware Virtual Platform', 'region': 'Region2', 'osfullname': 'Microsoft Windows Server 2019 Standard', 'osrelease': '2019Server'}
minion3.domain.com: {'productname': 'VMware Virtual Platform', 'osrelease': '2012ServerR2', 'manufacturer': 'VMware, Inc.', 'region': 'Region2', 'osfullname': 'Microsoft Windows Server 2012 R2 Standard', 'os': 'Windows'}
minion4.domain.com: {'manufacturer': 'VMware, Inc.', 'os': 'Windows', 'productname': 'VMware Virtual Platform', 'osrelease': '2019Server', 'osfullname': 'Microsoft Windows Server 2019 Standard', 'region': 'Region2'}

```

**Expected behavior**
This order was always maintained in the past with earlier version of Salt master and Minion (not sure of the versions though) 

**Screenshots**
Mentioned above are the returns that I get at every execution, Please notice the order of Grains returned.

**Versions Report**

```
salt --versions-report
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: 1.9.1
       cherrypy: unknown
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.5
         Jinja2: 2.11.1
        libgit2: 0.28.4
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 1.0.3
         Python: 3.6.8 (default, Sep 26 2019, 11:57:09)
   python-gnupg: 0.4.4
         PyYAML: 3.13
          PyZMQ: 15.3.0
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: redhat 7.8 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.10.1.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.8 Maipo

```

**Additional context**
Minion Version is 3000.3

**Comment by sagetherage** [comment]
@Prakash82x can you give us more detail in regards to your use-case, here, please?

**Comment by sagetherage** [comment]
@Prakash82x trying to understand more about what you are trying to do and what your end goal is by asking about your use-case scenario. I am putting this into blocked until we hear from you. If needed, please mention me so I am can move forward on this issue. Thank you!

**Comment by 11chrisadams11** [comment]
After further investigation, it appears that it is happening on systems with Python 3.5 and lower. It looks like Python 3.6+ added static, ordered dictionaries. I don't know why the random return order is only manifesting now after upgrading to Salt 3001.

**Comment by garethgreenaway** [comment]
@Prakash82x Thanks for the report.  @11chrisadams11 And thank you for the additional information.  Can you please let us know why the order of the returned grains data is important?

**Comment by 11chrisadams11** [comment]
For me, mostly the order is not as important as being stable and repeatable. Having the order change on every highstate, causes changes in files, which will restart multiple services (salt-minion, apache, nagios) every time. This makes it difficult to work with production systems as I never know what services will be restarted.

There are a few times, like with `host.present`, that I have had to resort to using `file.replace` because the data is not added in the order specified.

**Comment by Prakash82x** [comment]
> 
> 
> @Prakash82x Thanks for the report. @11chrisadams11 And thank you for the additional information. Can you please let us know why the order of the returned grains data is important?

Hello, Sorry for responding so late on this thread, I built a workround to get away with the issue. 
So to explain more about the issue and its importance for me, In my environment there are more than 8K minions with several different OSes hosted on different hardware/virtualization layer and across different Data centers. Our Asset management team requires inventory of all minions connected to Salt every month with following information like ID, MinionID, OSVersion, DataCenter, VirtualPlatform, Hardware Model etc.. All of these information are available in builtin and custom grains that we have setup. When I get these grains from salt they are returned in random order which makes it difficult to simply put them in csv/excel and send it over. The order used to be maintained perfectly fine earlier (not sure from which version it broke) and I just used to get the grains on console using --out=text and copy paste the content in excel with just little efforts.

**Comment by sagetherage** [comment]
@garethgreenaway let's review this in triage next Tuesday - around "order" so  I have created a label as such

**Comment by garethgreenaway** [comment]
@Prakash82x We discussed this issue during our weekly Triage meeting and concluded that the issue of ordering was likely caused by changes between Python versions.  There was also the suggestion for your particular use case sending the information to an database either SQL like MySQL or PSQL, or no-SQL like Mongo, using a Salt returner.  Then you could guarantee the ordering of the data you receive in your query.  I have done some light testing of your original Salt grains command using the latest version from the master branch and Python 3.8, and the order of the items I receive is always the same.
