### ISSUE TITLE
salt.states.file.managed not accurate

### ISSUE THREAD

**Issue by ykaly** [saltstack/salt#58150]
**Description**
salt.states.file.managed seems not to identify the file size is different from master and minion

**Setup**

```
diff:
  file.managed:
    - name: /tmp/file
    - source: salt://file
    - replace: False
```

`salt minion_id state.apply sls-file`

**Steps to Reproduce the behavior**
```
minion1:
----------
          ID: sls-file - diff
    Function: file.managed
        Name: /tmp/file
      Result: True
     Comment: File /tmp/file exists with proper permissions. No changes made.
     Started: 20:22:02.297901
    Duration: 8.693 ms
     Changes:

Summary for minion1
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   8.693 ms
```

Source/master: `-r--r----- 1 root root 2817 Aug  6 20:15 /srv/salt/file`
Minion: `-r--r----- 1 root root 2787 Aug  6 20:15 /tmp/file`

**Expected behavior**
Expected behavior is it would be able to see the file size differs.

**Versions Report**
`salt-2019.2.0-6.30.1.x86_64`

**Comment by rossengeorgiev** [comment]
That exactly what `replace: False` does according to the documentation. If the file already exists, it wont modified it.

> replace (default True)
>If set to False and the file already exists, the file will not be modified even if changes would otherwise be made. Permissions and ownership will still be enforced, however.

**Comment by garethgreenaway** [comment]
@ykaly Thanks for the report.  @rossengeorgiev is correct, this is the expected behavior with the `replace` flag set to False.
