### ISSUE TITLE
Memory Backing Support

### ISSUE THREAD

**Issue by gqlo** [saltstack/salt#58168]
Support Memory Backing to allow tuning virtual memory pages that are backed by host pages.
See [Libvirt domain xml](https://libvirt.org/formatdomain.html#memory-backing) for more details

**Comment by krionbsd** [comment]
@gqlo could you please elaborate what is this issue about?

**Comment by gqlo** [comment]
@krionbsd  Hi Krionbsd this is a feature request to support memory backing, Please see [Libvirt domain xml](https://libvirt.org/formatdomain.html#memory-backing) for more details.  This is in conjunction with two another PRs I am working on [CPU Model and Topology ](https://github.com/saltstack/salt/pull/57879) [Memory Tuning](https://github.com/saltstack/salt/pull/57636)

**Comment by gqlo** [comment]
I have working the draft PR for this feature already [Memory Backing](https://github.com/saltstack/salt/pull/58167)

**Comment by krionbsd** [comment]
@gqlo thank you for letting us know so we might interconnect these guys :)

**Comment by gqlo** [comment]
> @gqlo thank you for letting us know so we might interconnect these guys :)

hahah I am the person who is working on all those PRs. We probably don't need to interconnect. :) haha
