### ISSUE TITLE
[BUG] event.wait does not accept keywords listed in documentation

### ISSUE THREAD

**Issue by cheribral** [saltstack/salt#58182]
**Description**
After upgrading to salt v3001, states which use event.wait have quit working and throw an error about invalid keywords.  The keywords, however, are in the documentation [here](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.event.html#salt.states.event.wait)

**Setup**
```
always change:
  cmd.run:
    - name: "true"

missing database event:
  event:
    - wait
    - name: some/event
    - data:
        random: data
    - watch:
      - cmd: always change
```

**Steps to Reproduce the behavior**
Run the above state.  It returns `Passed invalid arguments: 'data' is an invalid keyword argument for 'event.wait'.`

**Expected behavior**
The event should fire successfully.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3001
 
Dependency Versions:
           cffi: 1.9.1
       cherrypy: Not Installed
       dateutil: 2.4.2
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.18.2.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core

```
</details>

**Comment by OrangeDog** [comment]
That example is wildly wrong. As the function signature shows, there is no `data` arg, and the state syntax is `event.wait:`.

**Comment by cheribral** [comment]
Sorry, I just saw the new info-needed tag.  Which information is needed for this exactly?  I'm pretty sure you have everything you need.  I gave a direct link to the documentation, and the example I gave is a working example which nearly mirrors what is in the documentation.

I'm not sure if @OrangeDog's comments meant he thought the docs had invalid syntax, or my example was wrong.  Since my example is intentionally close to the documentation, it probably doesn't matter.  In either case, the syntax is valid, and is simply an alternative way to write a state which probably isn't used as often. 
Also, yes, one can work around this by using event.send, but sending an event isn't the problem.  

The point of the bug report is that if you run an older version of  salt like 2018.3.5, the function works as documented, even though there is no  difference in the code for this state other than it appears to have been run through the black formatter in 3001.  Whatever happened, now either the documentation is wrong or the code is.  Which one should be fixed can probably be answered better by one of the authors.

**Comment by frogunder** [comment]
@cheribral Thank you for reporting this issue.
I see the same thing as you are. I will ping the core team for input on this one.

@saltstack/team-core can you take a look at this? I know we are not supporting 2018.3 anymore, but the example works there and on later versions it does not. So maybe something has changed in the code and/or the docs need to be updated?

Thanks

**Comment by sagetherage** [comment]
@ScriptAutomate when you get a minute can you look at the Documentation, here to see if this needs updates, pretty please?

**Comment by viq** [comment]
Just chiming in that I also have simple states similar to what's present in the documentation that used to work but now complain about `event.wait` not taking `data`.

**Comment by corywright** [comment]
Like others in this thread have said, passing parameters other than only `name` and `data` to the `event.wait` used to work successfully.  

I had asked about this on the Salt Slack channel back in March of this year, and the recommendation to me by one of the core salt devs there was to simply modify the `wait()` signature to be `def wait(name, sfun=None, **kwargs):` and then sync a local copy of `event.py` to my custom states modules.  This has worked for us, but this fix really should be added upstream.

**Comment by boltronics** [comment]
This has been an issue for *years* in one form or another. I proposed this change back in 2017 [here](https://github.com/saltstack/salt/issues/23518#issuecomment-327672497) but nobody ever bothered to include it, despite the fix only requiring 10 characters.

On all our masters, we have `/usr/lib/python3/dist-packages/salt/states/event.py` coped into our custom `_states` directory with the `, **kwargs` argument patched in to avoid these kinds of problems. I was just checking to see if this work-around was still required, but sadly it seems it still is.

**Comment by garethgreenaway** [comment]
Apologies for the delay in responding to this.  This was most likely broken back in the Fluorine release with this change (https://github.com/saltstack/salt/pull/46175) that deprecated the behavior of simply warning if/when there was an argument that was considered invalid in favor of raising an exception.  For the `event.wait` the correct fix here is to ensure `data` is a valid argument to the function going forward.
