### ISSUE TITLE
[BUG] Variables intented to be secret are displayed in the output of salt-ssh

### ISSUE THREAD

**Issue by victorenr-bit** [saltstack/salt#58187]
**Description**
When running salt-ssh and applying certain changes to files, those changes are displayed, if by any chance you are appending secrets in a file for example those changes are printed revealing the secret, even if the variable is ciphered with gpg in the pillar. This can be an issue if salt-ssh is executed under a CI/CD system with a not proper permission model or if someone is shoulder surfing behind you.

**Setup**
You can reproduce it by creating an encrypted gpg variable in any of your pillars and appending it to any text file with **file.append**.

**Steps to Reproduce the behavior**
Run salt as usual.

**Expected behavior**
Secret variables shouldn't be printed to the output, or there should be some kind of mechanism to decide which variables shouldn't be printed, maybe secrets should be it's own type of variable so that they get actually never printed to the screen, or at least the behavior could be customized. For me the workaround for now is using --state-output=terse.

**Versions Report**
salt-ssh 3001

</details>

**Comment by Ch3LL** [comment]
`show_changes` was added to some of the other file functions, but not to file.append. We could add this there.

**Comment by cmcmarrow** [comment]
Closing this due to age and the old version of Salt. Please feel free to reopen tick if bug is still present in salts latest version.
