### ISSUE TITLE
[BUG] salt/utils/jid.py Sodium deprecation notices still present

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#58225]
The following components in [salt/utils/jid.py](https://github.com/saltstack/salt/blob/master/salt/utils/jid.py) have been deprecated, and have a `warn_until()` message specifying `Sodium`.

https://github.com/saltstack/salt/blob/1a5ce828ad983e15205a80ae361150069afaebac/salt/utils/jid.py#L25-L35

This was included in the output of a query using the following `grep` command from root of the repo:

```
grep -Rn "warn_until" -A1 | egrep -i "Magnesium|Sodium" | egrep -v "_build|salt.7|deprecations.rst"
```

**Comment by cmcmarrow** [comment]
@ScriptAutomate We still need to remove the default argument. This should be done in `magnesium`.
As long as you pass an `opts` `dict` you should be okay.
