### ISSUE TITLE
Order of execution - `module.cmdmod` run before other `states` in sls.

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#58244]
I'm using salt modules in my sls to get more information in order to get a decision about what need to be executed next.
The problems I'm getting is that the module is running before the state, although its appearing afterwards.

My sls is:
```
eth0:
  network.managed:
    - enable: True
    - type: eth
    - proto: static
    - ipaddr: 1.1.1.1
    - netmask: 255.255.255.0

{% if salt.network.ping('1.1.1.254', timeout=5, return_boolean=True) %}
echo 'ping ok':
  cmd.run: []
{% else %}
echo 'ping failed':
  cmd.run: []
{% endif %}
```
While looking at the log I can see he perform the ping before the interface is configured.

Log output:
```
[salt.state] [INFO] Loading fresh modules for state activity
[salt.fileclient] [INFO] Fetching file from saltenv '*******' ** done ** 'PATH_TO_SLS_FILE'
[salt.loaded.int.moudle.cmdmod] [INFO] Executing command 'ping -W 5 -c 4 1.1.1.254' in directory '/root'
.
.
.
.
[salt.loaded.int.moudle.cmdmod] [ERROR] retcode: 1
```
**Here the sls start to execute... the configuration of the network etc..**

I' would expect the `network.ping` will execute to run after the `network.managed` finish his work, like all other sls ordering.
Alternative, to be able to add `watch_in`, `require_in` etc.. to module as well as for states.

I'm running on `Ubuntu 16.04` with salt-minion and salt-master version `3000.3`

**Comment by max-arnold** [comment]
Salt executes state files using multiple stages:

1. Parse and execute Jinja
2. Parse the resulting YAML
3. Parse slots
4. Interpret and execute the resulting data structure

What you are seeing is just stage (1)

**Comment by max-arnold** [comment]
Salt executes state files using multiple stages:

1. Parse and execute Jinja
2. Parse the resulting YAML
3. Parse slots
4. Interpret and execute the resulting data structure

What you are seeing is just stage (1)

**Comment by max-arnold** [comment]
Salt executes state files using multiple stages:

1. Parse and execute Jinja
2. Parse the resulting YAML
3. Parse slots
4. Interpret and execute the resulting data structure

What you are seeing is just stage (1)

**Comment by max-arnold** [comment]
Salt executes state files using multiple stages:

1. Parse and execute Jinja
2. Parse the resulting YAML
3. Parse slots
4. Interpret and execute the resulting data structure

What you are seeing is just stage (1)

**Comment by OrangeDog** [comment]
You need to put your ping in an actual state, with requistes. e.g.

```yaml
eth0:
  network.managed:
    - enable: True
    - type: eth
    - proto: static
    - ipaddr: 1.1.1.1
    - netmask: 255.255.255.0

ping 1.1.1.254:
  module.run:
    - network.ping:
      - host: 1.1.1.254
      - timeout: 5
    - requires:
      - network: eth0
```

**Comment by sagetherage** [comment]
@AmiramMaimon let us know if what Max and James have put here helps by closing the issue, or if you are still having trouble, please respond. Thank you!

**Comment by AmiramMaimon** [comment]
Another example:
{% set test = {'a': False} %}
```
eth0:
  network.managed:
    - enable: True
    - type: eth
    - proto: static
    - ipaddr: 1.1.1.1
    - netmask: 255.255.255.0

{% if salt.network.ping('1.1.1.254', timeout=5, return_boolean=True) %}
echo 'ping ok':
  cmd.run: []

{% do test.update('a': True) %}

{% else %}
echo 'ping failed':
  cmd.run: []
{% endif %}
```

How can I use your solution to solve this issue?

**Comment by OrangeDog** [comment]
What issue? What are you trying to achieve?

**Comment by sagetherage** [comment]
ok closing this issue @AmiramMaimon please mention me if you need this re-opened
