### ISSUE TITLE
[BUG] Salt-call randomly can't find any bin during highstate

### ISSUE THREAD

**Issue by Vaarlion** [saltstack/salt#58273]
**Description**
I got this error from a colleague, so i hop the data I've gather will be enough
Basically, we were running some highstate on a couple of server with salt-call. Some of them, seemingly randomly, couldn't find any binary during the run.
using the same command once again would run without issue.

I understand that salt-call are running with the environment of the user, but i can't find anything in there that could cause that behavior.
I have try to run the cmd with the same path without issue

At the same time i was running a highstate from salt-master on a separate set of server.
No error in the master log.

I know this is not enough to get a fix, but I am looking for some lead in order to start digging. (maybe a way to get this error reliably...)

**Setup**
Everything run on Debian 9, with salt master and minion 2019.2.5.
Because when this happen, every state from the highstate failed, there is no way to provide any linked sls.

**Steps to Reproduce the behavior**
I guess try to load the master with some highstate and run some salt-call on other highstate.

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 2019.2.5
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: Not Installed
          gitdb: 2.0.0
      gitpython: 2.1.14
          ioflo: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Sep 26 2018, 18:42:22)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 16.0.2
           RAET: Not Installed
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.4.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.12 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-12-amd64
         system: Linux
        version: debian 9.12 

```
</details>

**Additional context**
here are some error example

```
Function: service.running
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/service.py", line 897, in mod_watch
                  if __salt__['service.status'](name, sig):
                File "/usr/lib/python2.7/dist-packages/salt/modules/systemd_service.py", line 1057, in status
                  _check_for_unit_changes(service)
                File "/usr/lib/python2.7/dist-packages/salt/modules/systemd_service.py", line 120, in _check_for_unit_changes
                  if _untracked_custom_unit_found(name) or _unit_file_changed(name):
                File "/usr/lib/python2.7/dist-packages/salt/modules/systemd_service.py", line 374, in _unit_file_changed
                  return "'systemctl daemon-reload'" in _systemctl_status(name)['stdout'].lower()
                File "/usr/lib/python2.7/dist-packages/salt/modules/systemd_service.py", line 341, in _systemctl_status
                  ignore_retcode=True
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 2084, in run_all
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 684, in _run
                  raise CommandExecutionError(msg)
              CommandExecutionError: Unable to run command '[u'systemctl', 'status', u'nagios-nrpe-server.service', u'-n', u'0']' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -2, u'env': {'HISTTIMEFORMAT': '%F %T ', 'LC_NUMERIC': 'C', 'LESS': '-F -i -J -M -R -W -x4 -X -z-4', 'LC_CTYPE': 'C', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'LOGNAME': 'root', 'USER': 'root', 'PROMPT_COMMAND': 'set_prompt', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LC_PAPER': 'C', 'HOME': '/root', 'UCF_FORCE_CONFFOLD': '1', 'LANG': 'en_US.UTF-8', 'HISTCONTROL': 'ignoreboth:erasedups', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'LANGUAGE': 'C', 'LC_MEASUREMENT': 'C', 'LESS_TERMCAP_me': '\x1b[0m', 'LESS_TERMCAP_md': '\x1b[01;34m', 'LESS_TERMCAP_mb': '\x1b[01;31m', 'HISTSIZE': '10000', 'GCC_COLORS': 'error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01', 'EDITOR': 'vim', 'SUDO_USER': 'MYUSER', 'HISTFILESIZE': '200000', 'LC_MONETARY': 'C', 'USERNAME': 'root', 'SUDO_COMMAND': '/bin/bash', 'LC_ADDRESS': 'C', 'DEBIAN_FRONTEND': 'noninteractive', 'SUDO_UID': '1113', 'LESS_TERMCAP_ue': '\x1b[0m', 'GPG_TTY': '/dev/pts/0', 'LESS_TERMCAP_so': '\x1b[01;44;33m', '_': '/usr/bin/salt-call', 'LC_IDENTIFICATION': 'C', 'SUDO_GID': '1113', 'LSCOLORS': 'exgxcxdxbxexexabagacad', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LC_MESSAGES': 'C', 'APT_LISTCHANGES_FRONTEND': 'none', 'LC_COLLATE': 'C', 'LC_TELEPHONE': 'C', 'CLICOLOR': '1', 'LESS_TERMCAP_se': '\x1b[0m', 'SHLVL': '1', 'PWD': '/root', 'LESS_TERMCAP_us': '\x1b[01;32m', 'LC_NAME': 'C', 'MAIL': '/var/mail/root', 'LC_TIME': 'C', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'APT_LISTBUGS_FRONTEND': 'none'}, u'stdout': -1, u'close_fds': True, u'stdin': None, u'cwd': u'/root'}', reason: command not found
     Started: 14:49:19.248960
    Duration: 27.115 ms
     Changes: ```

```
----------
          ID: common.locale_set_Timezone
    Function: timezone.system
        Name: Europe/Paris
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/dist-packages/salt/state.py", line 1933, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/dist-packages/salt/loader.py", line 1951, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/states/timezone.py", line 73, in system
                  if __salt__['timezone.get_hwclock']() == 'localtime':
                File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 389, in get_hwclock
                  ret = _timedatectl()
                File "/usr/lib/python2.7/dist-packages/salt/modules/timezone.py", line 50, in _timedatectl
                  ret = __salt__['cmd.run_all'](['timedatectl'], python_shell=False)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 2084, in run_all
                  **kwargs)
                File "/usr/lib/python2.7/dist-packages/salt/modules/cmdmod.py", line 684, in _run
                  raise CommandExecutionError(msg)
              CommandExecutionError: Unable to run command '[u'timedatectl']' with the context '{u'timeout': None, u'with_communicate': True, u'shell': False, u'bg': False, u'stderr': -1, u'env': {'HISTTIMEFORMAT': '%F %T ', 'LC_NUMERIC': 'C', 'LESS': '-F -i -J -M -R -W -x4 -X -z-4', 'LC_CTYPE': 'C', 'LESSOPEN': '| /usr/bin/lesspipe %s', 'LOGNAME': 'root', 'USER': 'root', 'PROMPT_COMMAND': 'set_prompt', 'PATH': '/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin', 'LC_PAPER': 'C', 'HOME': '/root', 'UCF_FORCE_CONFFOLD': '1', 'LANG': 'en_US.UTF-8', 'HISTCONTROL': 'ignoreboth:erasedups', 'TERM': 'xterm-256color', 'SHELL': '/bin/bash', 'LANGUAGE': 'C', 'LC_MEASUREMENT': 'C', 'LESS_TERMCAP_me': '\x1b[0m', 'LESS_TERMCAP_md': '\x1b[01;34m', 'LESS_TERMCAP_mb': '\x1b[01;31m', 'HISTSIZE': '10000', 'GCC_COLORS': 'error=01;31:warning=01;35:note=01;36:caret=01;32:locus=01:quote=01', 'EDITOR': 'vim', 'SUDO_USER': 'MYUSER', 'HISTFILESIZE': '200000', 'LC_MONETARY': 'C', 'USERNAME': 'root', 'SUDO_COMMAND': '/bin/bash', 'LC_ADDRESS': 'C', 'DEBIAN_FRONTEND': 'noninteractive', 'SUDO_UID': '1113', 'LESS_TERMCAP_ue': '\x1b[0m', 'GPG_TTY': '/dev/pts/0', 'LESS_TERMCAP_so': '\x1b[01;44;33m', '_': '/usr/bin/salt-call', 'LC_IDENTIFICATION': 'C', 'SUDO_GID': '1113', 'LSCOLORS': 'exgxcxdxbxexexabagacad', 'LESSCLOSE': '/usr/bin/lesspipe %s %s', 'LC_MESSAGES': 'C', 'APT_LISTCHANGES_FRONTEND': 'none', 'LC_COLLATE': 'C', 'LC_TELEPHONE': 'C', 'CLICOLOR': '1', 'LESS_TERMCAP_se': '\x1b[0m', 'SHLVL': '1', 'PWD': '/root', 'LESS_TERMCAP_us': '\x1b[01;32m', 'LC_NAME': 'C', 'MAIL': '/var/mail/root', 'LC_TIME': 'C', 'LS_COLORS': 'rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:', 'APT_LISTBUGS_FRONTEND': 'none'}, u'stdout': -1, u'close_fds': True, u'stdin': None, u'cwd': u'/root'}', reason: command not found
     Started: 14:49:19.075244
    Duration: 47.384 ms
     Changes:   ```

**Comment by waynew** [comment]
I'm not sure what this bug is, but it's definitely related to Python2 - we no longer support Python2 with the Sodium release.

**Comment by Vaarlion** [comment]
Hello @waynew,
I'm aware that salt 2019 is only in phase3 support since march, but there is absolutely no possible way for us to upgrade to python 3. Some of the service we run aren't and will not be compatible, and obviously invest in brand new infrastructure is out of the question with the economical context.

we had encounter something similar a week ago while 2 big highstate were running, salt-master was sending empty pillar to some of the server (breaking everything by forcing default value)
We now fear every run, using a batch-size of 1 over 2K server ... i feel like this isn't doable anymore.

**Comment by Vaarlion** [comment]
What does make you think python2 is the cause ?

**Comment by waynew** [comment]
` CommandExecutionError: Unable to run command '[u'timedatectl']'` - Python 3 would not have the `u` prefix. It's *possible* that there is a different error at play here, but without ruling that out it's impossible to say.

Despite how awesome it would be to be able to continue to support everyone, we have limited resources, and many of our dependencies have already dropped support for legacy Python, which was a huge contributing factor in our dropping support as well. If you can reproduce this issue using Python 3, especially on a modern Salt, then we'll have a bug to fix. In the meantime, I'm going to go ahead and close this issue.

---

For what it's worth, you do not have to upgrade anything else to Python3, [though you should](https://www.python.org/doc/sunset-python-2/). It's entirely possible to have Salt running under Python (i.e. 3), and to keep everything else running under legacy Python.

If that is still not possible, you may be able to find volunteers in #salt on IRC, or the community Slack, or the salt-users group who are able to help dig deeper into your issue. If you already have a support contract you should reach out to professional services.
