### ISSUE TITLE
[DOCS] GPG renderer is listed as a text renderer, but used as a data renderer

### ISSUE THREAD

**Issue by leifb** [saltstack/salt#58276]
**Description**
The docs confused me a bit today: the [Renderers page](https://docs.saltstack.com/en/master/ref/renderers/index.html#two-kinds-of-renderers) lists the gpg renderer as a text renderer. At the same time the [salt.rendereres.gpg page](https://docs.saltstack.com/en/master/ref/renderers/all/salt.renderers.gpg.html) uses it as a data renderer (last in the pipeline). This confused me for a while and lead me to belive that the renderer pipline is executed from right to left.

I am not sure, if the gpg renderer can act as a text renderer or not. The docs should defeniteley be improved.

**Versions Report**
This is the case in the current master branch.

**Comment by sagetherage** [comment]
@saltstack/docs-working-group

**Comment by sagetherage** [comment]
@leifb that looks right, GPG renderer returns the same data structure as it gets decrypting text data fields. So it's worth to mentioning it either as data renderer type or as both text and data renderer in the docs @ScriptAutomate

**Comment by joybh98** [comment]
is anyone working on this issue ?

**Comment by priyank-R** [comment]
@sagetherage, I've made PR since the change was simple as you suggested and nobody had chipped in for a while. @joybh98 I hope you don't mind me creating a PR for this one.

**Comment by barbaricyawps** [comment]
@priyank-R , can you link this issue to that PR? I'll try to make sure it gets reviewed.

**Comment by barbaricyawps** [comment]
Tag me in any PRs you create and I'll make sure they get reviewed.
