### ISSUE TITLE
[BUG] network automation salt-proxy trouble

### ISSUE THREAD

**Issue by khireddine10** [saltstack/salt#58271]
**Description**
hi saltstack community i'm trying to use salt in network automation but i have a lot of trouble.
when bring up the salt-proxy, i get this issues.
![image](https://user-images.githubusercontent.com/44124081/90946207-a1098c80-e422-11ea-8874-d9d683a11bfd.png)

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).
do a simple napalm proxy, my test was done with a cisco ios router and the corresponding config.
**router.sls && top.sls**
![image](https://user-images.githubusercontent.com/44124081/90946247-e62dbe80-e422-11ea-88e7-8ff84a76d316.png)

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

![image](https://user-images.githubusercontent.com/44124081/90946296-56d4db00-e423-11ea-8d1c-b9ee9f7248c6.png)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

**salt-master version**
![image](https://user-images.githubusercontent.com/44124081/90946475-fb0b5180-e424-11ea-9e1c-866c29d05e1b.png)
![image](https://user-images.githubusercontent.com/44124081/90946478-05c5e680-e425-11ea-9dec-a564b341b33c.png)

**salt-minion version that run the salt proxy**
![image](https://user-images.githubusercontent.com/44124081/90946459-de6f1980-e424-11ea-9ac5-6e3417b8a2f8.png)
![image](https://user-images.githubusercontent.com/44124081/90946464-eb8c0880-e424-11ea-8f14-d57d2ca40acc.png)

**napalm version**
i've installed napalm using pip3.6
![image](https://user-images.githubusercontent.com/44124081/90946503-3dcd2980-e425-11ea-89ed-3db92990d34f.png)

**list of files in /usr/lib/python2.7/site-packages/salt/proxy/**
![image](https://user-images.githubusercontent.com/44124081/90946530-9ac8df80-e425-11ea-8d95-401aab48917f.png)

```
PASTE HERE
```
</details>

**Additional context**
please help me solve this problems.

**Comment by dmurphy18** [comment]
@khireddine10 Have you installed napalm on the salt-minion and if so, did you install it with pip3, or preferably 
``` 
python3 -m pip install napalm
```
Given that Salt v3001 and above no longer supports Python 2.

The debug logs for the salt-minion show that napalm is not installed.

**Comment by khireddine10** [comment]
thank you all, i have solved this problem.
the problem is that the saltstack was installed using python2, and the napalm was installed using python3.
after install both tools using python3 (pip3), now the proxy works very well.

**Comment by dmurphy18** [comment]
@khireddine10 Great news, I shall close the issue then since it is solved
