### ISSUE TITLE
[BUG]Salt-minion suddenly can't be started 

### ISSUE THREAD

**Issue by yz2524** [saltstack/salt#58303]
**Description**
I recently found out that one of our  minion is not reachable from mater test.ping.
I tried to restart the minion but it failed:
[ERROR   ] invalid syntax (utils.py, line 701)

**Versions Report**
salt-minion 2015.5.8 (Lithium) CentOS release 6.10
python2.6
salt-master 2015.5.10 (Lithium) CentOS release 6.10

**Comment by Ch3LL** [comment]
2015.5 is currently an unsupported version of Salt. Do you still see this issue on the latest version of Salt?

**Comment by yz2524** [comment]
Hello,
  We didn't update our salt since we are preparing the entire OS upgrading.
  Is there any way to fix this issue for this version for now?

**Comment by dmurphy18** [comment]
Closing this since 2015.2.x is long since EOL, as is Python 2 support
