### ISSUE TITLE
[BUG] #52359 was fixed for develop, but not merged to master

### ISSUE THREAD

**Issue by wegenerbenjamin** [saltstack/salt#58313]
The issue #52359 was fixed and merged into `develop`, but no further steps have been taken to bring the changes to the `master` branch; the bug is still present in the latest version.

[https://docs.saltstack.com/en/latest/topics/development/git/index.html](https://docs.saltstack.com/en/latest/topics/development/git/index.html) states `develop` as the main development branch, but [https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch](https://docs.saltstack.com/en/latest/topics/development/contributing.html#which-salt-branch) mentions `master` as the sole development branch. I was told in a different issue that `master` is the development branch.

I couldn't find any information on how open fixes/changes from `develop` will be moved into `master`.

**Comment by sagetherage** [comment]
Yes, we are aware of issues like this, we have a specific project board where we are trying to identify PRs that need to be ported to Master. This is likely on the project board in the first column https://github.com/saltstack/salt/projects/5

**Comment by sagetherage** [comment]
@wegenerbenjamin for this piece: " The issue #52359 was fixed and merged into develop" we have the original PR#52630 on the project board to be ported to master here https://github.com/saltstack/salt/projects/5?card_filter_query=52360 and we will eventually get to this and if you would like to help us, please consider opening a PR port to master branch, thank you!

**Comment by sagetherage** [comment]
@wegenerbenjamin for this: "I couldn't find any information on how open fixes/changes from develop will be moved into master." you are correct! The Core team did announce back when this was done, but we do not have documentation on this today, but we will take that up in the next major release to at least publish a blog post or perhaps we will put something sooner on the https://github.com/saltstack/community/wiki

**Comment by ScriptAutomate** [comment]
Places where `develop` branch is mentioned, and needs to be revisited:

```
doc/ref/configuration/master.rst:configuration will map the ``develop`` branch to the ``dev`` saltenv for all
doc/topics/development/git/index.rst:All new SaltStack code should be submitted against either the ``develop`` branch
doc/topics/releases/2016.3.3.rst:running Salt with the TCP transport. This is fixed on the ``develop`` branch of
doc/topics/tutorials/gitfs.rst:1. The first and fourth gitfs remotes will use the ``develop`` branch/tag as the
doc/topics/tutorials/gitfs.rst:   at ``develop``), and ``foo`` (pointed at ``foo``).
doc/topics/tutorials/gitfs.rst:   sourced from the ``develop`` branch.
.github/CONTRIBUTING.md:   as ``2016.3``, ``2016.11``, or even ``develop``, may already contain
```

**Comment by ScriptAutomate** [comment]
https://github.com/saltstack/salt/pull/57645 will be resolving inconsistencies in the contributing guide around `develop` vs. `master` branch mentions. When that is merged, I'll do another audit to check for remaining `develop` branch mentions throughout the repo.

**Comment by ScriptAutomate** [comment]
Board related to PRs to port (from `develop`) to `master`: https://github.com/saltstack/salt/projects/5
