### ISSUE TITLE
[BUG] New Arch AMI breaks full test suite

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#58320]
**Description**
https://github.com/saltstack/salt/pull/58319 updates to the latest arch ami, there are some failures that only fail when you run the full test suite, more details are on the pr, feel free to update the pr with changes that fix it.

**Comment by sagetherage** [comment]
@DmitryKuzmenko re-assigning this to you since most of the team is off on Monday for US holiday and Pedro is currently on PTO, he moved his PTO, originally I thought he would be working this week on this test failure, but plans change. Thank you for your help! :)

**Comment by s0undt3ch** [comment]
The issue has been addressed.
The offending test now skips if the required `crontab` binary is missing.
A new Arch AMI was also built which installs `cronie` which will prevent the rest from being skipped.
