### ISSUE TITLE
[BUG] New Fedora31 AMI breaks full test suite, integration.ssh.test_master.SSHMasterTestCase.test_can_it_ping is flaky

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#58321]
**Description**
https://github.com/saltstack/salt/pull/58317 updates to the latest fedora31 ami, there are some failures that only fail when you run the full test suite, more details are on the pr, feel free to update the pr with changes that fix it.

This one might just be a flaky test that's failing.

**Comment by waynew** [comment]
@bryceml is this actually still a problem?

**Comment by bryceml** [comment]
@waynew it appears to be a flaky test.  We can ignore the fact that it's flaky if you want and merge the linked pr.
