### ISSUE TITLE
Vmware cloud tests failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#58334]
**Description**
The VMWARE tests are failing here: https://jenkinsci.saltstack.com/job/pr-centos7-py3-cloud/job/master/1327/

```
    integration.cloud.clouds.test_vmware.VMWareTest.test_instance
    integration.cloud.clouds.test_vmware.VMWareTest.test_instance
```

**Comment by sagetherage** [comment]
Looks like this is passing now - closing.
