### ISSUE TITLE
unit.setup.test_install tests failing on windows

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#58336]
**Description**
The tests:

```
    unit.setup.test_install.InstallTest.test_sdist
    unit.setup.test_install.InstallTest.test_setup_install
```

are failing on windows.

https://jenkinsci.saltstack.com/job/pr-windows2019-py3-slow/job/master/454/
https://jenkinsci.saltstack.com/job/pr-windows2016-py3-slow/job/master/454/

this may be related to the failures here: https://github.com/saltstack/salt/issues/58335

**Comment by Ch3LL** [comment]
should be fixed by https://github.com/saltstack/salt/pull/58337

**Comment by Ch3LL** [comment]
@cmcmarrow i thought this would have been fixed by #58337 but these tests are still failing after this was merged so this still needs to be fixed.

**Comment by Ch3LL** [comment]
im not seeing this failing anymore. was there a pr pushed to fix this?

**Comment by bryceml** [comment]
https://pypi.org/project/setuptools/#history

I wonder if setuptools 50.1.0 fixed it.

I wonder if that means we can undo pedro's pr that locked us to <50 in other places.

**Comment by sagetherage** [comment]
these are passing now
