### ISSUE TITLE
[BUG] Big Sur softwareupdate module parsing

### ISSUE THREAD

**Issue by sheagcraig** [saltstack/salt#58340]
**Description**
Big Sur uses the same output format as Catalina, but the mac softwareupdate module mistakenly uses the earlier format due to the conditional that selects which regex to use. Currently, it's looking for a minor version that exceeds the version during which the new output of the softwareupdate CLI tool was released. However, Big Sur uses a new major version.

Please see https://github.com/saltstack/salt/pull/58247 for more details for a PR to solve this.

**Comment by sagetherage** [comment]
@DmitryKuzmenko assigning you as the Core Team member to help see the PR through to merge with those from the MacOS Working Group.
