### ISSUE TITLE
Reactor sls file for rsync not working in salt

### ISSUE THREAD

**Issue by divyaan23** [saltstack/salt#58363]
### Description of Issue
I am trying to configure reactor file for rsync module, it works fine with command as below, but not with reactor file

salt 'target' rsync.rsync /var/lib/salt-shared/salt-infra-prod/pki/master/minions /var/lib/salt-shared/salt-infra-prod/pki/master 

### Setup
I gave a try for different states as below

try1:

rsync.rsync:
  salt.function:
    - tgt: 'target'
    - arg:
      - src: /var/lib/salt-shared/salt-infra-prod/pki/master
      - dst: /var/lib/salt-shared/salt-infra-prod/pki/master

try2:

syncronize_minion_ids_primary:
  local.state.single:
    - tgt: 'target'
    - expr_form: list
    - kwarg:
        func: rsync.rsync
        src: /var/lib/salt-shared/salt-infra-prod/pki/master
        dst: /var/lib/salt-shared/salt-infra-prod/pki/master

try3:

syncronize_minion_ids_primary:
  rsync.rsync:
    - tgt: 'target'
    - kwarg:
        src: /var/lib/salt-shared/salt-infra-prod/pki/master
        dst: /var/lib/salt-shared/salt-infra-prod/pki/master

### Steps to Reproduce Issue
I could not see any change

### Versions Report
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.6
      gitpython: 3.0.7
         Jinja2: 2.10.1
        libgit2: 0.28.3
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.4
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: 1.0.3
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 4.15.0-114-generic
         system: Linux
        version: Ubuntu 20.04 focal

**Comment by divyaan23** [comment]
Hi, 

Is there anybody who could help me on this?

**Comment by divyaan23** [comment]
Tried with native Linux command and it works

minions_sync:
  local.cmd.run:
    - tgt: 'tartget'
    - expr_form: list
    - arg:
      - /usr/bin/rsync -av /var/lib/salt-shared/salt-infra-prod/pki/master/minions/ remote_machine:/var/lib/salt-shared/salt-infra-prod/pki/master/minions/

**Comment by sagetherage** [comment]
@divyaan23 apologies we have not triaged this issue glad you were able to find what works.
