### ISSUE TITLE
[BUG] Salt win_wua module commands from Salt master on Windows Server 2016 - "ERROR: Unknown Failure: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2145107945), None)" - ***unable to Generate/Trigger BITS Job/s"

### ISSUE THREAD

**Issue by apachipa** [saltstack/salt#58376]
**Description**
Windows Server 2016 Server by default BITS Service is in stopped state and is set to Manual start. When Salt win_wua module is used **Example:** command "**salt minion win_wua.list**" is used to check and Install updates for Windows Server 2016 Minions, it fails with "**ERROR: Unknown Failure: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2145107945), None)**". 

If I start BITS service manually on the minions(Windows Server 2016) salt command works fine to check, sync and install patches on Windows Server 2016. However it must be run before BITS service stops (from master). Which is by default BITS service stops if there is no BITS jobs(in 2 min) on Windows Server 2016. 

**Setup**

**Steps to Reproduce the behavior**
From Master "salt minion win_wua.list" fails with "ERROR: Unknown Failure: (-2147352567, 'Exception occurred.', (0, None, None, None, 0, -2145107945), None)". Because Windows BITS Service is stopped by default in Windows Server 2016 and salt is unable to generate BITS job which triggers BITS Service to start. This is very specific to Windows Server 2016. If we Start BITS Service and run"salt minion win_wua.list" immediately after with in 2 minutes, it works fine. 

However interestingly, if i run this on local machine "salt-call win_wua.list" it works fine without any issues. "salt-call win_wua.list" seem to be generating/triggering BITS Job and which is automatically starting BITS service.

**Expected behaviour**
Running "**salt minion win_wua.list**" from master should work similar to "**salt-call win_wua.list**" {running from local machine}

**Screenshots**

**Versions Report**
<details><summary>Salt Version:

**Minion:
----------**
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.10.0
       cherrypy: 10.2.1
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.3
          ioflo: Not Installed
         Jinja2: 2.9.6
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.14 (v2.7.14:84471935ed, Sep 16 2017, 20:25:58) [MSC v.1500 64 bit (AMD64)]
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.3
           RAET: Not Installed
          smmap: 2.0.3
        timelib: 0.2.4
        Tornado: 4.5.1
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: cp1252
        machine: AMD64
        release: 2016Server
         system: Windows
        version: 2016Server 10.0.14393  Multiprocessor Free

Master:
---------
Salt Version:
           Salt: 2018.3.2

Dependency Versions:
           cffi: 1.6.0
       cherrypy: 5.6.0
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
         Jinja2: 2.7.2
        libgit2: Not Installed
        libnacl: Not Installed
       M2Crypto: 0.28.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 2.7.5 (default, Dec  4 2019, 17:34:13)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 15.3.0
           RAET: Not Installed
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.2.1
            ZMQ: 4.1.4

System Versions:
           dist: oracle 7.7
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-x.xxxx
         system: Linux
        version: Oracle Linux Server 7.7

</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by twangboy** [comment]
Windows Update depends on the BITS service. Windows update will fail if it is disabled.

From https://docs.microsoft.com/en-us/archive/msdn-magazine/2003/february/net-apps-and-the-background-intelligent-transfer-service-api:
"Although the use of BITS is not limited to auto-updating applications, it is the underlying API used by Windows Update."
