### ISSUE TITLE
[BUG] Since upgrade to 3001.1 i cannot run multiple minion instances with different masters

### ISSUE THREAD

**Issue by schka17** [saltstack/salt#58397]
**Description**
Since upgrade to 3001.1 i cannot run multiple minion instances with different masters.
The first started service (default config dir) runs without any error.

The second minion exit with message
`[salt.cli.daemons :88  ][INFO    ][11809] An instance is already running. Exiting the Salt Minion`

**Setup**
create (copy config directory /etc/salt) /etc/c4sam-salt
minion.d/c4sam-minion.conf
`master: salt.c4sam.com
pki_dir: /etc/c4sam-salt/pki/minion
log_file: /var/log/c4sam-salt/minion
log_level: trace`

minion
`conf_file: /etc/c4sam-salt/minion
pki_dir: /etc/c4sam-salt/pki/minion
id: cockpit-w23.c4sam.com`

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

create the config dir described above
run command `salt-minion --config-dir=/etc/c4sam-salt`

output:
`[DEBUG   ] Configuration file path: /etc/c4sam-salt/minion
[TRACE   ] Trying os.getgrouplist for 'root'
[TRACE   ] Group list for user 'root': []
[WARNING ] Insecure logging configuration detected! Sensitive data may be logged.
[INFO    ] Setting up the Salt Minion "cockpit-w23.c4sam.com"
[INFO    ] An instance is already running. Exiting the Salt Minion
[INFO    ] Shutting down the Salt Minion
[DEBUG   ] Stopping the multiprocessing logging queue listener
[DEBUG   ] closing multiprocessing queue
[DEBUG   ] joining multiprocessing queue thread
[DEBUG   ] Stopped the multiprocessing logging queue listener
The Salt Minion is shutdown.
`

**Expected behavior**
Before the upgrade i could run two independent instances of minions connected to different masters, need this functionality.

**Screenshots**

**Versions Report**

```
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.13.2
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: 4.2.0
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 2.6
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-10-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**

**Comment by frogunder** [comment]
@schka17 Thank you for reporting this issue.

What salt version did this work on you, or what salt version did you upgrade from?

I have not been able to replicate it, if you have any additional info on your setup when seeing this it would be great.

Thanks.

**Comment by schka17** [comment]
> 
> 
> @schka17 Thank you for reporting this issue.
> 
> What salt version did this work on you, or what salt version did you upgrade from?
> 
> I have not been able to replicate it, if you have any additional info on your setup when seeing this it would be great.
> 
> Thanks.

Thanks for you response, unfortunately i'm not quit sure which was the last working version, i didn't detect the issue a while because of another issue (minion ID not read from non-default config directory) , for sure with 2019.2 it worked. This system was installed on debian stretch appr. 2 years ago and upgraded to buster some month ago.

What i did:
Standard installation for debian stretch, add repository to sources.list
`deb http://repo.saltstack.com/py3/debian/9/amd64/latest stretch main`

_after upgrade to buster i changed the source to:
`deb http://repo.saltstack.com/py3/debian/10/amd64/latest buster main`_

default configuration file `minion` is untouched, minion ID is defined in /etc/salt/minon_id
`cockpit-minion`
master is defined in /etc/salt/minion.d/cockpit_master.conf
`master: cockpit-w23.c4sam.com`

copy /etc/salt to /etc/c4sam-salt, 
modify /etc/c4sam-salt/minion_id
`cockpit-w23.c4sam.com`
modify /etc/c4sam-salt/minion
`conf_file: /etc/c4sam-salt/minion
pki_dir: /etc/c4sam-salt/pki/minion
id: cockpit-w23.c4sam.com`
create /etc/c4sam-salt/minion.d/c4sam-minion.conf
`master: salt.c4sam.com
pki_dir: /etc/c4sam-salt/pki/minion
log_file: /var/log/c4sam-salt/minion
log_level: trace`

create  `c4sam-salt-minion` file in /etc/init.d
```#!/bin/sh
### BEGIN INIT INFO
# Provides:          c4sam-salt-minion
# Required-Start:    $remote_fs $network
# Required-Stop:     $remote_fs $network
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: salt minion control daemon for C4SAM Cockpit
# Description:       This is a daemon that controls the salt minions
### END INIT INFO

# Author: Michael Prokop <mika@debian.org>

PATH=/sbin:/usr/sbin:/bin:/usr/bin
DESC="salt minion C4SAM Cockpit control daemon"
NAME=c4sam-salt-minion
DAEMON=/usr/bin/salt-minion
DAEMON_ARGS="-c /etc/c4sam-salt --log-file=/var/log/c4sam-salt/minion -d"
PIDFILE=/var/run/$NAME.pid
SCRIPTNAME=/etc/init.d/$NAME

# Exit if the package is not installed
[ -x "$DAEMON" ] || exit 0

# Read configuration variable file if it is present
[ -r /etc/default/$NAME ] && . /etc/default/$NAME

. /lib/lsb/init-functions

do_start() {
    # Return
    #   0 if daemon has been started
    #   1 if daemon was already running
    #   2 if daemon could not be started
    pid=$(pidofproc -p $PIDFILE $DAEMON)
    if [ -n "$pid" ] ; then
        return 1
    fi

    start-stop-daemon --start --quiet --background --pidfile $PIDFILE --exec $DAEMON -- \
            $DAEMON_ARGS \
            || return 2
}

do_stop() {
    # Return
    #   0 if daemon has been stopped
    #   1 if daemon was already stopped
    #   2 if daemon could not be stopped
    #   other if a failure occurred
    start-stop-daemon --stop --quiet --retry=TERM/30/KILL/5 --pidfile $PIDFILE --name $NAME
    RETVAL="$?"
    [ "$RETVAL" = 2 ] && return 2
    rm -f $PIDFILE
    return "$RETVAL"
}

case "$1" in
    start)
        [ "$VERBOSE" != no ] && log_daemon_msg "Starting $DESC" "$NAME"
        do_start
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
              2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    stop)
        [ "$VERBOSE" != no ] && log_daemon_msg "Stopping $DESC" "$NAME"
        do_stop
        case "$?" in
            0|1) [ "$VERBOSE" != no ] && log_end_msg 0 ;;
              2) [ "$VERBOSE" != no ] && log_end_msg 1 ;;
        esac
        ;;
    status)
        status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
        ;;
    #reload)
        # not implemented
        #;;
    restart|force-reload)
        log_daemon_msg "Restarting $DESC" "$NAME"
        do_stop
        case "$?" in
          0|1)
              do_start
              case "$?" in
                  0) log_end_msg 0 ;;
                  1) log_end_msg 1 ;; # Old process is still running
                  *) log_end_msg 1 ;; # Failed to start
              esac
              ;;
          *)
              # Failed to stop
              log_end_msg 1
              ;;
        esac
        ;;
    *)
        echo "Usage: $SCRIPTNAME {start|stop|status|restart|force-reload}" >&2
        exit 3
        ;;
esac

exit 0
```
start the 1. default minion
`service salt-minion start`
check state with
`service salt-minion status`
minion is running:
```● salt-minion.service - The Salt Minion
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled; vendor preset: enabled)
   Active: active (running) since Thu 2020-09-10 09:43:47 CEST; 11s ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
 Main PID: 26696 (salt-minion)
    Tasks: 6 (limit: 4915)
   Memory: 77.0M
   CGroup: /system.slice/salt-minion.service
           ├─26696 /usr/bin/python3 /usr/bin/salt-minion
           ├─26708 /usr/bin/python3 /usr/bin/salt-minion
           └─26710 /usr/bin/python3 /usr/bin/salt-minion

Sep 10 09:43:47 cockpit-w23 systemd[1]: Starting The Salt Minion...
Sep 10 09:43:47 cockpit-w23 systemd[1]: Started The Salt Minion.
```

start second minion with 
`service c4sam-salt-minion start`
check status
`service c4sam-salt-minion status`
`● c4sam-salt-minion.service - The Salt Minion
   Loaded: loaded (/etc/systemd/system/c4sam-salt-minion.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Thu 2020-09-10 09:45:05 CEST; 20s ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
  Process: 29192 ExecStart=/usr/bin/salt-minion -c /etc/c4sam-salt (code=exited, status=1/FAILURE)
 Main PID: 29192 (code=exited, status=1/FAILURE)

Sep 10 09:45:00 cockpit-w23 salt-minion[29192]: [INFO    ] Setting up the Salt Minion "cockpit-w23.c4sam.com"
Sep 10 09:45:00 cockpit-w23 salt-minion[29192]: [INFO    ] An instance is already running. Exiting the Salt Minion
Sep 10 09:45:00 cockpit-w23 salt-minion[29192]: [INFO    ] Shutting down the Salt Minion
Sep 10 09:45:00 cockpit-w23 salt-minion[29192]: [DEBUG   ] Stopping the multiprocessing logging queue listener
Sep 10 09:45:01 cockpit-w23 salt-minion[29192]: [DEBUG   ] closing multiprocessing queue
Sep 10 09:45:01 cockpit-w23 salt-minion[29192]: [DEBUG   ] joining multiprocessing queue thread
Sep 10 09:45:01 cockpit-w23 salt-minion[29192]: [DEBUG   ] Stopped the multiprocessing logging queue listener
Sep 10 09:45:05 cockpit-w23 salt-minion[29192]: The Salt Minion is shutdown.
Sep 10 09:45:05 cockpit-w23 systemd[1]: c4sam-salt-minion.service: Main process exited, code=exited, status=1/FAILURE
Sep 10 09:45:05 cockpit-w23 systemd[1]: c4sam-salt-minion.service: Failed with result 'exit-code'.
```
Today i will install a complete fresh system and install it following this procedure. Will update the result here

**Comment by frogunder** [comment]
Thank you for all this info.

I will give this another try tomorrow,

Thanks.

**Comment by lukasraska** [comment]
@schka17 We're relying on this functionality heavily, so out of curiosity i've tried it on latest version, since we're not yet using it

I've created `/etc/salt-another` directory with "new" config. The minion config file contains just these lines
```
root@salt-test:/etc/salt-another# grep -v "^#" minion | grep -v "^$"
master: localhost
id: another-minion.lxd
pidfile: /var/run/salt-minion-another.pid
conf_file: /etc/salt-another/minion
pki_dir: /etc/salt-another/pki/minion
cachedir: /var/cache/salt/minion-another
sock_dir: /var/run/salt/minion-another
log_file: /var/log/salt/minion-another
```

And it seems to work fine
```
root@salt-test:/etc/salt-another# salt-key
Accepted Keys:
another-minion.lxd
salt-test.lxd
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

```
root@salt-test:/etc/salt-another# salt '*' test.ping
salt-test.lxd:
    True
another-minion.lxd:
    True
root@salt-test:/etc/salt-another# salt '*' grains.get id
salt-test.lxd:
    salt-test.lxd
another-minion.lxd:
    another-minion.lxd
```


The `An instance is already running` seems to be generated due to `check_running` function -https://github.com/saltstack/salt/blob/master/salt/utils/parsers.py#L1059 , which checks the PID of the process. Since you don't specify the `pidfile` config option as I do, my assumption is it looks into the pidfile of the first minion and since it's already running, fails to start.

Can you try adding same options as I do if it helps?

**Comment by frogunder** [comment]
@lukasraska Thank you for also looking into this.

@schka17 It also seems to work for me. It seems, as @lukasraska pointed out that you will need to specify the `pidfile` in the config file for the second minion. Without that if fails for me but when specifying that is works.

I see this when `pidfile` is not specified, when trying to start the second minion:
```
[INFO    ] Setting up the Salt Minion "test-salt-another"
[INFO    ] An instance is already running. Exiting the Salt Minion
[INFO    ] Shutting down the Salt Minion
[DEBUG   ] Stopping the multiprocessing logging queue listener
[DEBUG   ] closing multiprocessing queue
[DEBUG   ] joining multiprocessing queue thread
[DEBUG   ] Stopped the multiprocessing logging queue listener
The Salt Minion is shutdown.
```
With `pidfile` specified, all seems to be fine.
```
root@localhost:~# ps aux | grep salt
root      2904  0.0  3.1 141512 62580 ?        Ss   16:14   0:01 /usr/bin/python3 /usr/bin/salt-master
root      2927  0.0  1.2  56928 26120 ?        S    16:14   0:00 /usr/bin/python3 /usr/bin/salt-master
root      2956  0.0  2.5 222848 51536 ?        Sl   16:14   0:00 /usr/bin/python3 /usr/bin/salt-master
root      2959  0.0  2.4 162012 49252 ?        S    16:14   0:00 /usr/bin/python3 /usr/bin/salt-master
root      2961  0.3  3.1 709960 64096 ?        S    16:14   0:08 /usr/bin/python3 /usr/bin/salt-master
root      2962  0.0  2.3 141336 48160 ?        S    16:14   0:00 /usr/bin/python3 /usr/bin/salt-master
root      2963  0.0  2.5 518092 52116 ?        Sl   16:14   0:00 /usr/bin/python3 /usr/bin/salt-master
root      2971  0.0  3.1 710408 63608 ?        Sl   16:14   0:01 /usr/bin/python3 /usr/bin/salt-master
root      2972  0.0  3.0 709892 61956 ?        Sl   16:14   0:01 /usr/bin/python3 /usr/bin/salt-master
root      2973  0.0  3.1 710840 62804 ?        Sl   16:14   0:01 /usr/bin/python3 /usr/bin/salt-master
root      2974  0.0  3.0 711408 62552 ?        Sl   16:14   0:01 /usr/bin/python3 /usr/bin/salt-master
root      2985  0.0  2.3 215244 48284 ?        Sl   16:14   0:00 /usr/bin/python3 /usr/bin/salt-master
root      2990  0.0  3.1 710376 62604 ?        Sl   16:14   0:01 /usr/bin/python3 /usr/bin/salt-master
root      7252  0.0  1.6  54264 34092 ?        Ss   16:36   0:00 /usr/bin/python3 /usr/bin/salt-minion
root      7256  0.1  3.1 728768 63384 ?        Sl   16:36   0:02 /usr/bin/python3 /usr/bin/salt-minion
root      7258  0.0  1.2 134792 25796 ?        S    16:36   0:00 /usr/bin/python3 /usr/bin/salt-minion
root      7318  0.0  1.6  54508 34228 pts/1    S+   16:36   0:00 /usr/bin/python3 /usr/bin/salt-minion --config-dir=/etc/salt-another
root      7331  0.1  3.1 728760 63384 pts/1    Sl+  16:36   0:01 /usr/bin/python3 /usr/bin/salt-minion --config-dir=/etc/salt-another
root      7335  0.0  1.2 134792 25460 pts/1    S+   16:36   0:00 /usr/bin/python3 /usr/bin/salt-minion --config-dir=/etc/salt-another
root      8281  0.0  0.0   6080   820 pts/0    S+   17:02   0:00 grep salt
root@localhost:~# salt-key
Accepted Keys:
test-salt
test-salt-another
Denied Keys:
Unaccepted Keys:
Rejected Keys:
root@localhost:~# salt \* test.version
test-salt:
    3001.1
test-salt-another:
    3001.1
root@localhost:~# 
root@localhost:~# salt \* grains.get id
test-salt-another:
    test-salt-another
test-salt:
    test-salt
root@localhost:~# 
```

**Comment by schka17** [comment]
@lukasraska @frogunder 

Thanks the definition of the pidfile is the solution.
Now it runs
