### ISSUE TITLE
[ISSUE] salt module is not available

### ISSUE THREAD

**Issue by Mateo-neo** [saltstack/salt#58399]
I have sls

My sls. Must create a mongodump file
```
create-dump:
  module.run:
   - name: docker.run
   - m_name: mongo
   - cmd: 'mongodump --out=/Mongodump
```
when i'm run salt minion state.sls sls i see:
```
ID: create-dump
    Function: module.run
        Name: docker.run
      Result: False
     Comment: Module function docker.run is not available
     Started: 06:03:40.273781
    Duration: 728.234 ms
     Changes:
```
--Versions
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.9.1
       cherrypy: 3.5.0
       dateutil: 2.5.3
      docker-py: 4.3.1
          gitdb: 2.0.0
      gitpython: 2.1.1
         Jinja2: 2.8
        libgit2: 0.24.5
       M2Crypto: Not Installed
           Mako: 1.0.6
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.3.7
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.24.2
         Python: 3.5.3 (default, Jul  9 2020, 13:00:10)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1

System Versions:
           dist: debian 9.6
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-8-amd64
         system: Linux
        version: debian 9.6

```
Tried `pip3 uninstall docker` - not work

If i'm reboot server docker-py downgrade to 1.10.6 version

**Comment by garethgreenaway** [comment]
@Mateo-neo It looks like docker-py is installed, are you able to run the docker execution module manually?  
Something like: `salt minion docker.run mongo "mongodump --out=/Mongodump"`

**Comment by Mateo-neo** [comment]
> @Mateo-neo It looks like docker-py is installed, are you able to run the docker execution module manually?
> Something like: `salt minion docker.run mongo "mongodump --out=/Mongodump"`

@garethgreenaway 

![image](https://user-images.githubusercontent.com/69625544/92558229-d79f2e00-f28f-11ea-91dc-f873518828a6.png)

**Comment by garethgreenaway** [comment]
@Mateo-neo Thanks for the update.  To be clear, you have the python-docker library installed on the Salt minion where you're attempting to run `docker.run` right?  You're running the `salt` command on the Salt master but the `docker.run` is running on the minion.

**Comment by Mateo-neo** [comment]
@garethgreenaway Yes, you are right. I didn’t think of the command being executed on a minion. I installed a docker for him and everything worked. Thank you so much
