### ISSUE TITLE
[BUG] Pop!_OS 20.04 not recognized as aptpkg for pkg states

### ISSUE THREAD

**Issue by thehunmonkgroup** [saltstack/salt#58395]
**Description**
Pop!_OS 20.04 currently throws the following error for all Salt ```pkg``` and ```pkgrepo``` states.

```
     Comment: State 'pkg.installed' was not found in SLS 'software.unoconv'
              Reason: 'pkg' __virtual__ returned False: pkg module could not be loaded
```

**Setup**
```
[:~] $ salt-call --version
salt-call 3001.1
```
```
[:~] $ cat /etc/issue
Pop!_OS 20.04 LTS \n \l
```
The machine in question was recently upgraded from Pop!_OS 19.10

**Steps to Reproduce the behavior**
Run any ```pkg``` or ```pkgrepo``` state

**Expected behavior**
State should complete successfully

**Versions Report**

```
[:~] 127 $ salt-call --versions-report
Salt Version:
           Salt: 3001.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.2 (default, Jul 16 2020, 14:00:26)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 18.1.1
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2
 
System Versions:
           dist: pop 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-7642-generic
         system: Linux
        version: Pop!_OS 20.04 focal
```
</details>

**Additional context**
The issue can be worked around by adding the following to ```/etc/salt/minion```

```
providers:
  pkg: aptpkg
```

**Comment by eliasp** [comment]
What does `salt-call grains.get os_family` and `salt-call grains.get os` return on Pop!_OS 20.04? That's all `aptpkg` depends on in its `__virtual__()` function. So far, I can't find anything related to Pop!_OS in the `_OS_FAMILY_MAP` of `salt/grains/core.py`.

```python
def __virtual__():
    """
    Confirm this module is on a Debian-based system
    """
    # If your minion is running an OS which is Debian-based but does not have
    # an "os_family" grain of Debian, then the proper fix is NOT to check for
    # the minion's "os_family" grain here in the __virtual__. The correct fix
    # is to add the value from the minion's "os" grain to the _OS_FAMILY_MAP
    # dict in salt/grains/core.py, so that we assign the correct "os_family"
    # grain to the minion.
    if __grains__.get("os_family") == "Debian":
        return __virtualname__
    return False, "The pkg module could not be loaded: unsupported OS family"
```

**Comment by thehunmonkgroup** [comment]
```
[:~] $ salt-call grains.get os_family
local:
    Pop
[:~] $ salt-call grains.get os
local:
    Pop
```

I'm *pretty* sure what happened is that Pop!_OS used to show up as Ubuntu in those queries (as it is largely Ubuntu-based), but this latest update has it showing as above.

So the correct fix seems to be adding the necessary entries to `_OS_NAME_MAP` and `_OS_FAMILY_MAP` -- I took a stab at it in #58443 .

**Comment by ScriptAutomate** [comment]
Created a related issue: https://github.com/saltstack/salt/issues/59061

**Comment by ScriptAutomate** [comment]
I checked Pop!_OS 20.10, and `/etc/os-release` has the same expected values for `ID` and `ID_LIKE`:

```
NAME="Pop!_OS"
VERSION="20.10"
ID=pop
ID_LIKE="ubuntu debian"
PRETTY_NAME="Pop!_OS 20.10"
VERSION_ID="20.10"
HOME_URL="https://pop.system76.com"
SUPPORT_URL="https://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=groovy
UBUNTU_CODENAME=groovy
LOGO=distributor-logo-pop-os
```

> *I'm pretty sure what happened is that Pop!_OS used to show up as Ubuntu in those queries (as it is largely Ubuntu-based), but this latest update has it showing as above.*

@thehunmonkgroup I think you're right. I found a previous example version of the Pop!_OS `os-release` config, and it is not using these fields the same way:

> Reference: https://github.com/pop-os/os-release/blob/master/examples/pop_cosmic

```
NAME="Pop!_OS"
VERSION="18.10"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Pop!_OS 18.10"
VERSION_ID="18.10"
HOME_URL="https://system76.com/pop"
SUPPORT_URL="http://support.system76.com"
BUG_REPORT_URL="https://github.com/pop-os/pop/issues"
PRIVACY_POLICY_URL="https://system76.com/privacy"
VERSION_CODENAME=cosmic
UBUNTU_CODENAME=cosmic
```

Which, as mentioned, would mean that earlier versions of Pop!_OS would have worked as expected as `salt` would have seen the `ubuntu` value for `ID`. This also lends more value to the potential of #59061
