### ISSUE TITLE
Errors mirroring repo with rclone

### ISSUE THREAD

**Issue by gandihar** [saltstack/salt#58427]
**Description**
Now that rsync.repo.saltstack.com is no more (R.I.P.), the rclone instructions end up failing semi-randomly and breaking random files in the mirror. An update to the instructions/flags on the repo website fixes the problem.

**Setup**
I followed the instructions (rclone command line specifically) on the repo website. In so doing, especially on large repos (py3/redhat and py3/ubuntu), the transfer ends up failing with upwards of 800 chain-linked errors.

**Steps to Reproduce the behavior**
Follow the instructions on http://repo.saltstack.com/#mirror.

**Expected behavior**
A successful mirror of the repository.

**Versions Report**
ALL (Version independent)

**Additional context**
After spending way too much time troubleshooting this, I have determined that the symlink'd directories combined S3's lack of symlink support are causing the problem. Limiting the transfer threads and checker threads in rclone to 1 each fixes the issue, at the cost of the whole transfer taking a little longer.

The options are: --checkers 1 --transfers 1

Adding this to the instructions on the repo website will save the community aggravation and the company S3 transfer costs.

**Comment by bryceml** [comment]
I don't recommend trying to sync from s3 to a directory that has existing symlinks.

To save space by excluding the redundant centos7 symlinks, what do you think about adding this to the documentation:

If you want to exclude the redhat version symlinks to save space, you can use some excludes:
```bash
RCLONE_CONFIG_S3_TYPE=s3 RCLONE_CONFIG_S3_PROVIDER=Other RCLONE_CONFIG_S3_ENV_AUTH=false RCLONE_CONFIG_S3_ENDPOINT=https://s3.repo.saltstack.com rclone sync --fast-list --use-server-modtime -v --exclude '**/redhat/6?*/**' --exclude '**/redhat/7?*/**' --exclude '**/redhat/8?*/**' s3:s3/ ./fullrepo/
```

**Comment by bryceml** [comment]
or even shorter

```bash
RCLONE_CONFIG_S3_TYPE=s3 RCLONE_CONFIG_S3_PROVIDER=Other RCLONE_CONFIG_S3_ENV_AUTH=false RCLONE_CONFIG_S3_ENDPOINT=https://s3.repo.saltstack.com rclone sync --fast-list --use-server-modtime -v --exclude '**/redhat/???*/**' --delete-excluded s3:s3/ ./fullrepo/
```

**Comment by gandihar** [comment]
The redhat repositories are the ones I'm trying to clone. Additionally, the ubuntu repos have similar symlinks.

**Comment by bryceml** [comment]
I've updated the instrucitons here: https://repo.saltstack.com/#mirror

you should remove all symlinks:

```bash
find /path/to/repo -type l -delete
```

you should add this to your clone command `--exclude '**/redhat/???*/**' --exclude '/yum/amazon/20**' --delete-excluded`

to save space by not downloading all of the multiple copies created by the redhat and amazon symlinks

The amazon symlinks are going away as soon as 3000 (python 2 versions) gets moved to archive.repo.saltstack.com which is why I didn't put them in the instructions on repo.saltstack.com/#mirror

**Comment by bryceml** [comment]
If you are cloning a sub path, you will have to change the exclude accordingly, If you sent me your whole rclone command you're using, I can help you adjust it.
