### ISSUE TITLE
integration.modules.test_decorators tests are failing periodically on catalina mac

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#58430]
https://jenkinsci.saltstack.com/job/pr-macosxcatalina-py3-slow/job/master/119/testReport/junit/integration.modules.test_decorators/DecoratorTest/test_command_failure_nonzero_retcode_false/

```
Traceback (most recent call last):
  File "/private/tmp/kitchen/testing/tests/integration/modules/test_decorators.py", line 101, in test_command_failure_nonzero_retcode_false
    "'runtests_decorators.command_failure_nonzero_retcode_false' is not available.",
AssertionError: False != "'runtests_decorators.command_failure_nonzero_retcode_false' is not available."
```

**Comment by Ch3LL** [comment]
these tests started failing on this date: Sep 9, 2020 12:12:47 PM.

It is not tied to a different commit though as the same commit was used when they were passing and when they started failing.

https://jenkinsci.saltstack.com/job/pr-macosxcatalina-py3-slow/job/master/111/

**Comment by sagetherage** [comment]
These are pass now, correct @Ch3LL ?
