### ISSUE TITLE
Cannot mirror HTTP repo for saltstack

### ISSUE THREAD

**Issue by saltpicker** [saltstack/salt#58459]
Hello.

For example: https://repo.saltstack.com/py3/redhat/8/x86_64/2019.2

```
[root@host rhel-x86_64-server-8-saltstack]# curl https://repo.saltstack.com/py3/redhat/8/x86_64/2019.2/repodata/
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
</head>
<body>
  <div id="listing"></div>
  <script type="text/javascript" src="/jquery-3.1.1.min.js"></script>
  <script type="text/javascript">
    if(! window.location.href.split('?')[0].endsWith("/")) {
      window.location.replace(window.location.href.split('?')[0] + "/" + window.location.search);
    }
    var BUCKET_URL = '/s3';
    var BUCKET_WEBSITE_URL = '';
  </script>
  <script type="text/javascript" src="/list.js"></script>
</body>
</html>

```
Could you setup the oldschool http repo instead of this *.js tools?
I just want to make a mirror with wget/curl but i cannot do this when this page is handled  by some javascripts.

Thank you.

**Comment by bryceml** [comment]
see https://repo.saltstack.com/#mirror

we stopped supporting recursive wget in part because it is much more expensive and resource intensive if any significant number of people use it.
