### ISSUE TITLE
__virtual__ returned False: invalid syntax on RHEL8

### ISSUE THREAD

**Issue by saltpicker** [saltstack/salt#58463]
Hello.

Simple module:
```
# just a failtest
def failTest():
        try:
                whatever
        except:
                print traceback.format_exc(sys.exc_info())
                return False
```

Execution on  rhel7 minion:
```
[mymaster ~]0$ sudo salt 'host' myModules.failTest
host:
    False
```

Look ok, now the same on rhel8 minion:
```
[mymaster ~]0$127$ sudo salt 'host' myModules.failTest
host:
    'myModules' __virtual__ returned False: invalid syntax (myModules.py, line 96)
ERROR: Minions returned with non-zero exit code

```
Same saltstack version on both matster and minions
```
salt-master-2019.2.5-1.el7.noarch
salt-2019.2.5-1.el7.noarch
salt-minion-2019.2.5-1.el7.noarch

```

Any idea?
Is this problem related with python2 -> python3?

Thank you!

**Comment by frogunder** [comment]
@saltpicker Thank you for reporting this issue.

Does the log files give any additional info?

Also 2019.2 is no longer a supported version, have you tried on 3001 or 3000? Does that give you the same error?
https://www.saltstack.com/product-support-lifecycle/

Thanks.

**Comment by saltpicker** [comment]
I will make an update at first.
It wil take a while.

Thank you!
