### ISSUE TITLE
[BUG] Missing quotes for dictionary in CLI example for saltutil.sync_all

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#58475]
**Description**
Documentation for saltutil.sync_all extmod_whitelist is incorrect in CLI examples
see https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_all

**Setup**
have:
salt '*' saltutil.sync_all extmod_whitelist={'modules': ['custom_module']}

Needs extra set of quotes
salt '*' saltutil.sync_all extmod_whitelist='{'modules': ['custom_module']}'

for the dictionary

**Comment by akentominas** [comment]
Hello!
This is my first attempt to contribute to the project and i fould this open unassigned issue to work on.
@dmurphy18 , @barbaricyawps 

Looking at the [source code](https://github.com/saltstack/salt/blob/master/salt/utils/extmods.py#L46) where `extmod_whitelist` is checked on wheather it is a `str` or a `dict`, both `str` & `dict` are allowed. 

If the input is a string, for example, `extmod_whitelist='my_module'` , it will create a dict out of it:
```
{'modules': ['my_module']}
```

If it is a dict, it will keep the type as is.

Changing the CLI command to `salt '*' saltutil.sync_all extmod_whitelist='{'modules': ['custom_module']}'`, i tested the above mentioned code block and getting:
```
extmod_whitelist='{'modules': ['custom_module']}'
                        ^
SyntaxError: invalid syntax
```

Am i missing something on the reason you would like to add single quotes there?

**Comment by dmurphy18** [comment]
Closing this since just checked with Salt 3006.0 and both uses work.
