### ISSUE TITLE
[FEATURE REQUEST] Add support for transactional systems, like openSUSE MicroOS

### ISSUE THREAD

**Issue by aplanas** [saltstack/salt#58519]
Transactional systems, like MicroOS, provide a read-only rootfs and a cli tool (transactional-update) to manage the system (update, install new packages, etc).

Each change in this system become a snapper snapshot, that needs to be activated after a reboot.

Currently Salt do not support this kind of systems.

**Comment by sagetherage** [comment]
we did get this into Aluminium, work is still in progress, but it will be released in the next major release - Silicon
