### ISSUE TITLE
No minions matched the target. No command was sent, no jid was assigned.

### ISSUE THREAD

**Issue by karthiksonti24** [saltstack/salt#58567]
I'm facing this weird issue. It works fine for individual nodes or else when I give it as a list. It fails when I give  *
```
[root@ip-192-168-53-163 ec2-user]# salt * test.ping
No minions matched the target. No command was sent, no jid was assigned.
ERROR: No return received
[root@ip-192-168-53-163 ec2-user]# salt -L redhat,ubuntu test.ping
ubuntu:
    True
redhat:
    True
[root@ip-192-168-53-163 ec2-user]# 
```

I tried the following steps also.
```
1. go to folder /etc/salt/pki/minion/ on minion
2. remove master_public file
3. restart the minion 
```

salt-version: salt 3001.1

Can someone help me with this issue.

**Comment by lukasraska** [comment]
@karthiksonti24 When you use plain `*` in bash, it expands it to all files in current directory. You need to escape it / use apostrophe for bash to pass it to salt command as it is.

Can you try one of following commands?
```
salt '*' test.ping
salt \* test.ping
```
```

**Comment by karthiksonti24** [comment]
Thanks, @lukasraska .both of them works.
