### ISSUE TITLE
[BUG] Salt on stock macOS triggers Command Line Developer Tools GUI dialog

### ISSUE THREAD

**Issue by sheagcraig** [saltstack/salt#58575]
**Description**
macOS unfortunately ships without git (among other standard dev tools). Compounding this nuisance, macOS _does_ ship with a stub in place that, when executed, triggers a GUI dialog prompting the user to download the Command Line Developer Tools (CLT) package via Software Update.

For our use case, managing client endpoints we are forced to first install the CLT package ahead of Salt, which does the main work of bootstrapping devices. The CLT package is strangely very costly timewise to install, and this is avoidable since the only real use of its deliverables is when Salt imports the gitpython package as part of the gitfs utils to determine which version of git may be present.

**Setup**
No special setup required.

**Steps to Reproduce the behavior**
1. Install macOS afresh.
2. Install macOS Salt package.
3. `sudo salt-call --local test.sls`  (state file doesn't even have to exist).

**Expected behavior**
Salt should test for whether git is actually installed on macOS/Darwin prior to trying to use the git python package for determining version. In this situation, it is not installed and will not be available during the current salt run.

**Screenshots**
![](https://macops.ca/images/2013/10/xcodeselect-install@2x.png)

**Versions Report**
This has been an issue for Salt across numerous versions.

**Additional context**
I have a PR in progress to resolve this issue.

**Comment by sheagcraig** [comment]
@weswhet

**Comment by sagetherage** [comment]
I can help with getting this triaged @sheagcraig and @weswhet let me know the PR in progress

**Comment by sheagcraig** [comment]
Thanks @sagetherage 

#58581
