### ISSUE TITLE
[FEATURE REQUEST] SSH module does not support newer OpenSSH key types 

### ISSUE THREAD

**Issue by monrad** [saltstack/salt#58578]
**Is your feature request related to a problem? Please describe.**
OpenSSH 8.2 added support for new key types that work with U2F tokens through the FIDO2
standard.
I am not 100% sure if this should be an bug report instead.

**Describe the solution you'd like**
That the SSH module also supports sk-ecdsa-sha2-nistp256@openssh.com and sk-ssh-ed25519@openssh.com key types.

**Describe alternatives you've considered**
I did consider just using an jinja template but it seems wrong since the ssh auth state module exists.

**Additional context**
Support for the new key types was announced in [OpenSSH 8.2 releases notes](https://www.openssh.com/txt/release-8.2)
More information about OpenSSH U2F/FIDO security keys is mention in the [PROTOCOL.u2f](https://raw.githubusercontent.com/openssh/openssh-portable/master/PROTOCOL.u2f) file.

**Comment by Ch3LL** [comment]
i'll approve as feature request. thanks :)

**Comment by hkbakke** [comment]
I also need this!

**Comment by HerHde** [comment]
This should have been fixed along with #59429 by #60128

**Comment by Ch3LL** [comment]
Thanks for pointing that out. I'll close this issue.
