### ISSUE TITLE
Vault Enterprise Integration [FEATURE REQUEST]

### ISSUE THREAD

**Issue by eadderley-tc** [saltstack/salt#58585]
**Is your feature request related to a problem? Please describe.**
In order to communicate with Vault Enterprise namespace,  a namespace must be declared as part of the headers, as X-Vault-Namespace. Info: https://www.vaultproject.io/docs/enterprise/namespaces

**Describe the solution you'd like**
The files runners/vault.py and utils/vault.py need to be updated so that the requests to vault pass these headers in where necessary.

**Describe alternatives you've considered**
None. If someone wants to use Salt and Vault Enterprise, this change would need to be implemented.

**Additional context**
A PR has been submitted to address this issue: https://github.com/saltstack/salt/pull/58586

I hope I'm doing this right.

**Comment by sagetherage** [comment]
@waynew this is a good one for the Test Clinics! I would love to get this into Aluminium or Silicon so assigning you to help move the needle on test cases.

**Comment by eadderley-tc** [comment]
When last I touched this some months ago I had asked for clarification why black's testing was failing.  

https://github.com/saltstack/salt/pull/58586#issuecomment-715583973

I can spare some time next week to rebase & work out the kinks again, maybe with a response when I run up against something in the test suite that doesn't make sense.
