### ISSUE TITLE
salt '*' test.verison No minions matched the target. No command was sent, no jid was assigned. ERROR: No return received

### ISSUE THREAD

**Issue by Venkateshsandupatla** [saltstack/salt#58631]
**Description**
I have created a salt-master on a rhel8 vm , and salt-minion another rhel8vm. I have installed by downloading repo and using yum. But, now am unable to accept the keys. So am unble to send commands to minion.  

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by sagetherage** [comment]
see #58632
