### ISSUE TITLE
[BUG] gitlab repo : _pygit2.GitError: Error receiving socket data: Connection reset by peer

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#58653]
**Description**

Not able to mount repo on gitab.com using git@xxx syntax on centos 8 while salt on centos 7 works.

Please see https://github.com/saltstack/salt/issues/58623, CentOS 8 doesn't support git@syntax using pygit2 anymore.
Thus gitlab repo mounts will  have to use git:// repo path. But gitlib doesn't support git:// path.  This leave slat user wanting to upgrade to centos 8 to get clean python3 stuck.  

```
2020-10-06 16:37:20,473 [salt.utils.gitfs :1887][ERROR   ][3914026] Error occurred fetching gitfs remote 'git://gitlab.com/tjyang/mysalt.git': Error receiving socket data: C\
onnection reset by peer
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/gitfs.py", line 1858, in _fetch
    fetch_results = origin.fetch(**fetch_kwargs)
  File "/usr/lib64/python3.6/site-packages/pygit2/remote.py", line 405, in fetch
    check_error(err)
  File "/usr/lib64/python3.6/site-packages/pygit2/errors.py", line 64, in check_error
    raise GitError(message)
_pygit2.GitError: Error receiving socket data: Connection reset by peer
```
**Setup**
- Make sure [libgit2 has ssh support](https://github.com/libgit2/pygit2/issues/789) on CentOS 8's default rpm pkg.
```
[tjyang@centos8t01 ~]$ python3
Python 3.6.8 (default, Apr 16 2020, 01:36:27)
[GCC 8.3.1 20191121 (Red Hat 8.3.1-5)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pygit2 as pg
>>> bool(pg.features and pg.GIT_FEATURE_SSH)
True
>>>

```
- repos config in /etc/salt/master
```
  - git://github.com/tjyang/salt-formula.git:
     - pubkey:  /home/tjyang/.ssh/id_dsa.pub
     - privkey: /home/tjyang/.ssh/id_dsa
     - mountpoint: salt://test01-git

  - git://gitlab.com/tjyang/mysalt.git:
     - pubkey:  /home/tjyang/.ssh/id_dsa.pub
     - privkey: /home/tjyang/.ssh/id_dsa
     - mountpoint: salt://test01-gitlab

```

**Steps to Reproduce the behavior**
- with above "git://gitlab.com/tjyang/mysalt.git:" config in /etc/salt/master.
- sudo salt-run -l debug fileserver.update # to trigger repo mount manually
- Or "sudo systemctl restart salt-master" to see the error in /var/log/salt/master.

**Expected behavior**
To see test01-gitlab successfully mounted like test01-github  on centos8t01.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>

```
[tjyang@centos8t01 ~]$ salt --versions-report
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.14.2.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core

[tjyang@centos8t01 ~]$

```
</details>

**Additional context**
- See  #58623 that centos8t01 was able to mount repo from GitHub.
- https://gitlab.com/gitlab-org/gitlab-foss/-/issues/52288

**Comment by tjyang** [comment]
- command line git clone failed with same reset message if using git:// syntax with gitlab.
```
[tjyang@centos8t01 ~]$ git clone git://gitlab.com/tjyang/mysalt.git
Cloning into 'mysalt'...
fatal: read error: Connection reset by peer
[tjyang@centos8t01 ~]$ 
```
- command line git clone successfully if using git@ syntax:
```
[tjyang@centos8t01 ~]$ git clone git@gitlab.com:tjyang/mysalt.git
Cloning into 'mysalt'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.
[tjyang@centos8t01 ~]$
```

**Comment by tjyang** [comment]
# Testing with gitlab on centos 7.8 #

-  OS info
```
[tjyang@salt01 ~]$ cat /etc/redhat-release
CentOS Linux release 7.8.2003 (Core)
[tjyang@salt01 ~]$ git --version
git version 1.8.3.1
[tjyang@salt01 ~]$

```
-  OK using **git@gitlab.com:tjyang/mysalt.git** syntax

```
[tjyang@salt01 ~]$ git clone git@gitlab.com:tjyang/mysalt.git
Cloning into 'mysalt'...
remote: Enumerating objects: 3, done.
remote: Counting objects: 100% (3/3), done.
remote: Total 3 (delta 0), reused 0 (delta 0), pack-reused 0
Receiving objects: 100% (3/3), done.
[tjyang@salt01 ~]$ 
```
- failed using **git://gitlab.com/tjyang/mysalt.git** syntax
```
[tjyang@salt01 ~]$  git clone git://gitlab.com/tjyang/mysalt.git
Cloning into 'mysalt'...
fatal: read error: Connection reset by peer
[tjyang@salt01 ~]$
```

**Comment by garethgreenaway** [comment]
@tjyang Thanks for the report.  There appears to be an issue running a git clone against Gitlab using the git:// syntax and not a Salt specific issue.  Are you certain that Gitlab supports the git:// syntax?

**Comment by tjyang** [comment]
@garethgreenaway 
Thanks for your response. I updated Descriptions with more details in 2nd paragraph.
The end goal is to run latest salt-maser with python3 and having salt formula repo mounted from gitlab server. 
Either git:// or git@ syntax is OK , which ever works.

**Comment by sagetherage** [comment]
git:// is no longer supported in GitHub and likely never worked GitLab so it is expected not to work and is not a Salt issue.

**Comment by sagetherage** [comment]
Git documentation doesn't mention deprecation, but is clear: https://git-scm.com/docs/git-clone#_git_urls
