### ISSUE TITLE
[BUG] Salt-Minion restart loop on Windows 

### ISSUE THREAD

**Issue by markuskramerIgitt** [saltstack/salt#58669]
**Description**
Windows uses a service manager. When the salt-minion contains invalid configuration, the service manager goes into a restart loop as fast as possible, exhausting the CPU of one core.

**Setup**
Invalidate the configuration, e.g. so that a YAMLError is thrown.

**Expected behavior**
The restart loop must not  exhaust a core.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

Pull Requests
- https://github.com/saltstack/salt/pull/58478
- https://github.com/saltstack/salt/pull/58179
- https://github.com/saltstack/salt-windows-msi/pull/71

**Comment by twangboy** [comment]
Closed by https://github.com/saltstack/salt/pull/58523
