### ISSUE TITLE
[BUG] Undefined variable "response" in "salt/utils/slack.py"

### ISSUE THREAD

**Issue by nicolas-harraudeau-sonarsource** [saltstack/salt#58682]
**Description**
Hello,

While analyzing salt on SonarCloud I saw a variable being used without being defined beforehand [`salt/utils/slack.py`](https://github.com/saltstack/salt/blob/e9e48b7fb6a688f4f22d74a849d58c1c156563d1/salt/utils/slack.py#L123). If executed it will raise a `NameError`. You can see [the issue in SonarCloud here](https://sonarcloud.io/project/issues?id=nicolas-harraudeau-sonarsource_salt&issues=AXUIK0fsPoEr8CkZiRSb&open=AXUIK0fsPoEr8CkZiRSb).

The variable is defined in another branch of the parent `if-else` block.
```python
    if result.get("status", None) == salt.ext.six.moves.http_client.OK:
        ...
        response = slack_functions.get(function).get("response")  # "response" is defined here
        ...
        ret["message"] = _result.get(response)  # "response" is used here correctly
        ...
    else:
        ...
        if "dict" in result:
            ...
            ret["message"] = _result.get(response)  # "response" is used but not defined here
```
**Setup**
There is no setup. This issue was detected by using the SonarCloud online service.
You can run the same analysis in a few clicks. I used [this configuration file](https://github.com/nicolas-harraudeau-sonarsource/salt/commit/aec7a4ce1e0ecad066703cfa9fc5c48378e15a64) to separate properly main code from test code.

**Screenshots**
<img width="1625" alt="Screenshot 2020-10-08 at 15 53 38" src="https://user-images.githubusercontent.com/40498978/95472646-9465d700-0983-11eb-87b2-538961e3f4fa.png">

**Versions Report**
This issue was found directly on the master branch of salt. I didn't check if it was present in any released version.

**Additional context**
In case you have any question, suggestion or if you see a False Positive on SonarCloud you can reach out on [SonarSource community forum](https://community.sonarsource.com/).

A few notes in case you want to use SonarCloud:
* SonarCloud can easily import pylint and flake8 issues in case you want to use a rule SonarCloud does not already provide. Note however that if you select a rule already covered by SonarCloud you might see different issues than what Pylint/Flake8 report. We design our code analyzers to avoid False Positives as much as possible and to detect complex bugs.
* SonarCloud is free for open-source projects.

**Comment by garethgreenaway** [comment]
@nicolas-harraudeau-sonarsource Thanks for the report.
