### ISSUE TITLE
[DOCS] Contributor Guide: Needed Review, Refresh, and Jumping Off Point

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#58703]
## Description

There are many separate contributor guides scattered throughout the `salt` project.

Most people expect `CONTRIBUTING.md` to be in the root of the repo. Ours is in `.github/CONTRIBUTING.md`, so it is hidden in a way. It means people would likely go to `CONTRIBUTING.rst` instead, which we also have.

GitHub, though, is using automation to reference `.github/CONTRIBUTING.md` when on the contribute page:
- https://github.com/saltstack/salt/contribute (top-right reference)

GitHub's doc on the contributing guide in repos, and how it automatically referenced: https://docs.github.com/en/free-pro-team@latest/github/building-a-strong-community/setting-guidelines-for-repository-contributors

## Suggested Fix

We should consolidate contributor guide information where possible, remove out-dated/unnecessary contributor docs, and probably use a `CONTRIBUTING.md` file in the root of the repo as a jumping-off point to the rest of the HTML contributing docs, depending on what a contributor wants to do. Unless we wish to keep it in `.github`. In my opinion, this would involve reviewing, pulling from, and deleting the `CONTRIBUTING.rst` and `HACKING.rst` files.

@waynew had an idea of a "Choose Your Own Adventure" type of contributor guide landing page, which may be good to take into account and adopt:
- https://gitlab.com/waynew/choose-your-own-saltventure

We should review the following in the root of the repo to consolidate, update, remove if needed, etc.:
- [`CONTRIBUTING.rst`](https://github.com/saltstack/salt/blob/master/CONTRIBUTING.rst)
- [`.github/CONTRIBUTING.md`](https://github.com/saltstack/salt/blob/master/.github/CONTRIBUTING.md)
- [`HACKING.rst`](https://github.com/saltstack/salt/blob/master/HACKING.rst)
- [HTML docs: Developing Salt](https://docs.saltstack.com/en/latest/topics/development/)
  - Source rst files generated there: https://github.com/saltstack/salt/tree/master/doc/topics/development

Whatever path we take, it looks like we would need to update the [`MANIFEST.in`](https://github.com/saltstack/salt/blob/master/MANIFEST.in) file, which I'm not sure what that is used for, but it does reference these files and may need including of the `CONTRIBUTING.md` file that is created.

The `README.md` file in the root should also link to the contributing guide somewhere, as it makes it an easy way to find the contributor guide, and also appears elsewhere such as in PyPi when a new release is cut:
- https://pypi.org/project/salt/

### Contributing to Documentation

Part of this needs review, revision, and consolidation of how to contribute to documentation. We can draw from the recent Docs Clinic:
- https://www.twitch.tv/videos/756539737

The sections of interest which are all related specifically to contributing to documentation:
- https://docs.saltstack.com/en/latest/topics/development/hacking.html#editing-and-previewing-the-documentation
- https://docs.saltstack.com/en/latest/topics/development/conventions/documentation.html

**Comment by ScriptAutomate** [comment]
> These are notes taken from review of https://github.com/saltstack/salt/pull/57645, which is addressing some baseline improvements around documentation.

I'm thinking we should do the following:

- Delete https://github.com/saltstack/salt/blob/master/.github/CONTRIBUTING.md (what GitHub is defaulting to as the contributing guide of the repo, in places like https://github.com/saltstack/salt/contribute and https://github.com/saltstack/salt/community)
- Overwrite `CONTRIBUTING.rst` with `HACKING.rst` , so that GitHub automatically picks it up as the default contributing guide for people new to the repo, and so that people looking at the repo can automatically see that they should be looking at that (`HACKING.md` is unclear, especially since there co-exists a `CONTRIBUTING.md` that this would also be replacing, I imagine)
- Delete `md` duplicate: `HACKING.md`
- Replace references of `HACKING.rst` and `CONTRIBUTING.rst`, where they appear in the repo, with `HACKING.md` (`HACKING.md` is not referenced by any other files in the repo):

```
# HACKING.rst -> CONTRIBUTING.rst
pkg/suse/salt.spec:782:%doc LICENSE AUTHORS README.rst HACKING.rst README.SUSE
MANIFEST.in:4:include HACKING.rst
```

We can have `CONTRIBUTING.rst` get pulled in as the new contents of https://docs.saltstack.com/en/latest/topics/development/hacking.html (and rst include call), where we then will have the contributing guide in both the GitHub repo root (for easy access and reference via GitHub or source code), and in the Sphinx-generated documentation, without having duplicate files.

This would do some nice, significant cleanup and reduce a lot of confusion. Either it should be done within this PR, or in a PR directly following the merge of this PR.

**Comment by barbaricyawps** [comment]
Here's an example of a really great contributing guide that uses a choose-your-own-adventure organization style: https://intellij-asciidoc-plugin.ahus1.de/docs/contributors-guide/index.html

**Comment by ScriptAutomate** [comment]
This issue is resolve by the combination of work from #57645 and #59289
