### ISSUE TITLE
[BUG] Not able to query integer key in pillar

### ISSUE THREAD

**Issue by Oddly** [saltstack/salt#58714]
**Description**
We have pillar keys and values as follows:

When we run `salt-call pillar.get storages`, we get all the information under storages. `salt-call pillar.get storages:234223432:frame` doesn't produce anything, `salt-call pillar.get storages:23422343B:frame` returns "SENO342".
In other places, we have integers as values and they return without problems, but it seems keys can not be integers. 

**Setup**
The pillar SLS file:

```
frames:
  - 094ADF:
    - frame: VMSA098
    - vio4: VME
  - 23423A:
    - frame: VMSE943
    - vio3: VMS

storages:
  - 234223432:
    - frame: SEND332
  - 23422343B:
    - frame: SENO342
```
**Steps to Reproduce the behavior**
See description

**Expected behavior**
Normally it should supply the value in the "- frame:" part.

**Versions Report**

```
*salt-minion*:
salt-minion --versions-report
/opt/salt/lib/python2.7/site-packages/salt/scripts.py:212: DeprecationWarning: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date.  Salt will drop support for Python 2.7 in the Sodium release or later.
Salt Version:
           Salt: 3000.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 3.5.0
       dateutil: 2.6.0
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.31.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.5 (default, Apr  2 2020, 00:36:59)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 16.0.2
          smmap: Not Installed
        timelib: 0.2.4
        Tornado: 4.5.3
            ZMQ: 4.1.6

System Versions:
           dist:
         locale: ISO8859-1
        machine: 00F9538F4C00
        release: 1
         system: AIX
        version: Not Installed

*salt-master*:
Salt Version:
           Salt: 3001.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: 0.26.0
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.4.7
         pygit2: 0.26.2
         Python: 3.6.9 (default, Jul 17 2020, 12:50:27)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5

System Versions:
           dist: ubuntu 18.04 Bionic Beaver
         locale: UTF-8
        machine: x86_64
        release: 4.15.0-118-generic
         system: Linux
        version: Ubuntu 18.04 Bionic Beaver

```

**Additional context**
Additional information when debugging the problem:

*Minion debug info*:
[DEBUG   ] minion return: {u'fun_args': [u'storages:23422343B:frame'], u'jid': u'20201012143505746324', u'return': 'SENO342', u'retcode': 0, u'success': True, u'fun': u'pillar.get'}
[DEBUG   ] minion return: {u'fun_args': [u'storages:234223432:frame'], u'jid': u'20201012144002737782', u'return': u'', u'retcode': 0, u'success': True, u'fun': u'pillar.get'}

*Master debug info(partial output)*:
('storages',[
  OrderedDict([('23422343B', [OrderedDict([('frame', 'SENO342')])])]), 
  OrderedDict([(234223432, [OrderedDict([('frame',  'SEND332')])])]), 

When quoting the value in the pillars file, the master debug info would appear correct (quoted), but on the minion nothing would change.

**Comment by garethgreenaway** [comment]
@Oddly Thanks for the report.
