### ISSUE TITLE
About reconnect for minions

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#58710]
Our salt master is deployed on the docker. And after the salt master container was rebuilded, all the minion data will be lost. However, the salt minion will not be automatically reconnected to the salt master. Unless we manually restart one salt minion, then all other salt minions will be reconnected together, otherwise all the minions will not be automatically reconnected.
It seems unless one minion to be connected otherwise all the other minions cannot to be connected automatically.

**Comment by garethgreenaway** [comment]
@andyyumiao Thanks for the report.  Can you provide the output from `salt --versions-report` so we know what version of Salt you're seeing this issue in.  Thanks!

**Comment by garethgreenaway** [comment]
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.
