### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'saltfactories' when running tests

### ISSUE THREAD

**Issue by asomers** [saltstack/salt#58731]
**Description**
I'm trying to run the builtin tests locally.  The instructions in HACKING.rst are out of date, so I may be doing things wrong, but the tests fail with the error:
```
ModuleNotFoundError: No module named 'saltfactories'
```

**Setup**
FreeBSD 13.0-CURRENT amd64, Python 3.7

**Steps to Reproduce the behavior**
```
pip-3.7 install --user -r requirements/base.txt
./setup.py build
./setup.py test
```

**Expected behavior**
It should've run the tests

**Screenshots**
```
> ./setup.py test
3000-2233-g52c9850ea0
running test
running build
running build_py
running build_scripts
running test
Traceback (most recent call last):
  File "/usr/home/somers/src/github/saltstack/salt/tests/runtests.py", line 60, in <module>
    from tests.integration import TestDaemon, TestDaemonStartFailed  # isort:skip
  File "/usr/home/somers/src/github/saltstack/salt/tests/integration/__init__.py", line 44, in <module>
    from tests.support.cli_scripts import ScriptPathMixin
  File "/usr/home/somers/src/github/saltstack/salt/tests/support/cli_scripts.py", line 12, in <module>
    from tests.support.saltfactories_compat import generate_script
  File "/usr/home/somers/src/github/saltstack/salt/tests/support/saltfactories_compat.py", line 26, in <module>
    from saltfactories.exceptions import FactoryTimeout as ProcessTimeout
ModuleNotFoundError: No module named 'saltfactories'
```

**Versions Report**'
I'm using the latest master branch in git

**Comment by krionbsd** [comment]
@asomers could you show all the steps you ran? The preferable method is to run the tests with `nox`

**Comment by asomers** [comment]
How does one use nox?  It isn't described in HACKING.

**Comment by krionbsd** [comment]
@asomers we're currently working on general HACKING.rst overhaul, in the meantime you might try depending on your python ver. `nox -e 'pytest-zeromq-3.7(coverage=False)' -- -v --run-slow $path_to_test`

**Comment by krionbsd** [comment]
@asomers can we close this issue now?

**Comment by krionbsd** [comment]
@asomers we've upgraded docs, you might find related info in `doc/topics/development/tests/index.rst`

**Comment by asomers** [comment]
Yeah, now that HACKING.rst is gone, this issue is fixed.

**Comment by zjzh** [comment]
I also encounter the same issue, how do you solve the problem ? @asomers @krionbsd
