### ISSUE TITLE
Request addition of --addtag as valid kwarg to linux_lvm module

### ISSUE THREAD

**Issue by ypise** [saltstack/salt#58747]
**Is your feature request related to a problem? Please describe.**
vgcreate command allows use of optional argument `--addtag`. However, the linux_lvm module doesn't support this option.

**Describe the solution you'd like**
Addition of `--addtag` to list of valid options in https://github.com/saltstack/salt/blob/b427688048fdbee106f910c22ebeb105eb30aa10/salt/modules/linux_lvm.py#L361 would be very helpful.
```
OPTIONS
       --addtag Tag
              Adds a tag to a PV, VG or LV. This option can be repeated to add multiple tags at once. See lvm(8) for information about tags.
```

**Describe alternatives you've considered**
The current alternative is to the above missing support for `--addtag` is to use cmd.run `vgchange --addtag <myTag> /dev/<VG_Name>`. This is not such a Saltonic (just made that up and I know it doesn't sound so nice) way.

**Additional context**
Please do add addtag to https://github.com/saltstack/salt/blob/b427688048fdbee106f910c22ebeb105eb30aa10/salt/modules/linux_lvm.py#L361:
```
valid = (
        "**addtag**",
        "clustered",
        "maxlogicalvolumes",
        "maxphysicalvolumes",
        "vgmetadatacopies",
        "metadatacopies",
        "physicalextentsize",
    )
```

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by sagetherage** [comment]
my mistake! I thought you were done here @s0undt3ch

**Comment by sagetherage** [comment]
looks like this was fixed in Aluminium lcosing
