### ISSUE TITLE
salt-ssh should build a simple tunnel to forward zeromq between a local temporary master and a remote temporary minion

### ISSUE THREAD

**Issue by baby-gnu** [saltstack/salt#58762]
**Is your feature request related to a problem? Please describe.**

It's not possible to use several standard feature of salt with `salt-ssh`:

- jinja TemplateNotFound:
  - #9878
  - #19564
  - #21370
  - #26585
- gitfs not working
  - #23576

**Describe the solution you'd like**

The `salt-ssh` command tunneled a full master / minion connexion using zeromq:

- start a local master:
  - listen on `127.0.0.1`
  - random `publish_port`
  - random `ret_port`
- open a connexion to a minion with SSH
  - transfert master ports locally:
    - listen on the minion `127.0.0.1`
    - random `publish_port` on the minion piped to master random `publish_port`
    - random `ret_port` on the minion piped to master random `ret_port`
  - start a temporary minion with the proper options to contact the temporary master
    - `master` is `127.0.0.1` to reach the local endpoint of the tunnel
	- `master_port` is local random `ret_port`
	- `publish_port` is local random `publish_port`

**Describe alternatives you've considered**

None.

**Additional context**

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by baby-gnu** [comment]
As I'm not sure it's a substantial change, I open this feature request.

Tell me if you prefer an issue in https://github.com/saltstack/salt-enhancement-proposals.

Regards.

**Comment by Ch3LL** [comment]
There is this project https://gitlab.com/saltstack/pop/heist that will solve this problem :)

**Comment by baby-gnu** [comment]
> There is this project https://gitlab.com/saltstack/pop/heist that will solve this problem :)

In one use case, I have several users connecting to a `salt-ssh` machine where everything is in place for them to call `salt-ssh` [as users](https://gist.github.com/baby-gnu/8a198629161fe8fc60bd2b33a8321012).

I may miss something but [heist](https://gitlab.com/saltstack/pop/heist) seems to require a `salt-master` service running.

Regards.
