### ISSUE TITLE
feature request: globbing in exclude (and include?)

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#5876]
I've written a .sls that installs php on a server, but by default it installs php-cli and php-apache2 (it's hard to separate). For a few minions, I'd like to exclude php-apache2, but I now have to tediously make sure that I exclude all states that reference the file for apache2 manually, for all minions that include php.

I'd like to do

```
include:
  - php

exclude:
  - php-apache2-*
```

Thoughts?

(I'm sorry if this is a duplicate, but the github search is giving me unicorns)

**Comment by Mrten** [comment]
seems approved?

**Comment by Mrten** [comment]
again

**Comment by Mrten** [comment]
please don't stale approved issues

**Comment by Mrten** [comment]
please don't stale approved issues

**Comment by dmurphy18** [comment]
@Mrten Closing this due to age, the old version of Salt and Python 2.
Can you retest this with the latest release of Salt 3006.2 and if still an issue, please open a new issue/feature request, which will have metrics in tracking issues.
