### ISSUE TITLE
[FEATURE REQUEST] TTP execution and runner modules

### ISSUE THREAD

**Issue by dmulyalin** [saltstack/salt#58779]
Would like to initiate a discussion on adding TTP execution and runners modules in SALT.

**Is your feature request related to a problem? Please describe.**
Since many systems can return their configuration and state data in a form of semi-structure text, the natural way to make use of that information in a programmatic fashion usually based on parsing. Reliable parsing requires knowledge and skills of working with regular expressions, which not all people have. Moreover, regex parsing is usually error-prone and time consuming process and quality of results heavily depends on implementer experience.

**Describe the solution you'd like**
To simplify the process of getting structured data out of semi structured text a number of libraries were developed with API and set of features capable of solving certain use cases. TTP falls in the same set of tools and uses templates for data extraction, with additional capabilities to prepare, process and form parsing results.

Being general purpose tool, TTP does not target any particular use case, such as parsing only indented text or only text tables or only output of certain device types, as a result the set of problems that can be solved limited only by ones imagination,  creativity and goals.

TTP combined with SALT execution and runners modules, significantly simplifies the process of obtaining raw text output from minions and converting it in arbitrary Python structures. This structures can be programmatically processed further to improve and add value to automation processes.

**Describe alternatives you've considered**
Alternatives are to use existing execution and runners modules capabilities which definitely can help to address a lot of tasks, however, will be limited to a set of use cases programmed into them. Extending their capabilities for the sake of solving certain use cases usually turns into programming exercise where significant portion of code dedicated to transforming minions' output in structured data, which TTP can help with as well.

**Additional context**
TTP was developed with intent to parse output from network devices, which usually comes back as a semi-structured text and output patterns are very diverse as a result naturally lacking of any readily available tools to consume them programmatically.

**Sample Use Cases**
1. reporting across several minions by parsing text output and returning text tables
2. transforming text data in structured format for storing in mine
3. produce time series data and pushing it to long term storage using returners
4. compliance testing by parsing text into structured data with further processing and analysis to detect deviations
5. facts and inventory gathering and extraction from raw text data

**Related pull request**
https://github.com/saltstack/salt/pull/58754

**Comment by whytewolf** [comment]
the PR was closed as not needed or valid by the poster. so I"m going to go ahead and close this request. if there is someone that does need this new module set. I purpose to them to build a salt-extension based off the original PR. this would allow it to be released on it's own terms at it's own speed.
