### ISSUE TITLE
[BUG] lvm.lv_present does not allow 100%FREE extents on resize

### ISSUE THREAD

**Issue by jthomisee** [saltstack/salt#58783]
**Description**
Setting extents to 100%FREE under lvm.present results in the below error when running the state more than once. It will successfully create the logical volume when run for the first time, but then fails when running a second time as it attempts to decide if it needs to resize

```File "/usr/lib/python3/dist-packages/salt/states/lvm.py", line 334, in lv_present
    if force is False and (size_mb < old_size_mb or extents < old_extents):
TypeError: '<' not supported between instances of 'str' and 'int'
```

**Setup**
Example sls
```# Create a logical volume
logical-volume-{{vg_name}}:
  lvm.lv_present:
    - name: {{vg_name}}
    - vgname: {{vg_name}}
    - extents: '100%FREE'
```

**Steps to Reproduce the behavior**
Create a logical volume using lvm.lv_present. Run that again and you will get the error.
```
$ sudo salt-call state.apply storage
          ID: logical-volume-var_lib_elasticsearch
    Function: lvm.lv_present
        Name: var_lib_elasticsearch
      Result: True
     Comment: Created Logical Volume var_lib_elasticsearch
     Started: 13:59:15.776366
    Duration: 943.935 ms
     Changes:
              ----------
              created:
                  ----------
                  /dev/var_lib_elasticsearch/var_lib_elasticsearch:
                      ----------
                      Allocated Logical Extents:
                          -1
                      Allocation Policy:
                          0
                      Current Logical Extents Associated:
                          25599
                      Internal Logical Volume Number:
                          -1
                      Logical Volume Access:
                          3
                      Logical Volume Name:
                          /dev/var_lib_elasticsearch/var_lib_elasticsearch
                      Logical Volume Size:
                          209707008
                      Logical Volume Status:
                          1
                      Major Device Number:
                          253
                      Minor Device Number:
                          5
                      Open Logical Volumes:
                          0
                      Read Ahead Sectors:
                          -1
                      Volume Group Name:
                          var_lib_elasticsearch
                  Output from lvcreate:
                      Logical volume "var_lib_elasticsearch" created.

$ sudo salt-call state.apply storage

----------
          ID: logical-volume-var_lib_elasticsearch
    Function: lvm.lv_present
        Name: var_lib_elasticsearch
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2153, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2188, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/lvm.py", line 341, in lv_present
                  if force is False and (size_mb < old_size_mb or extents < old_extents):
              TypeError: '<' not supported between instances of 'str' and 'int'
     Started: 14:00:24.268488
    Duration: 62.124 ms
     Changes:
----------
```

**Expected behavior**
Should resize to 100% available space if needed

**Versions Report**
<details><summary>salt --versions-report</summary>
Salt Version:
           Salt: 3002

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 4.0.5
      gitpython: 3.1.8
         Jinja2: 2.10.3
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: ubuntu 20.04 focal
         locale: utf-8
        machine: x86_64
        release: 5.4.0-1028-aws
         system: Linux
        version: Ubuntu 20.04 focal
```
PASTE HERE
```
</details>

**Additional context**
This appeared to be working no problem under salt 3001/ubuntu 16

**Comment by piterpunk** [comment]
This is duplicated of  #58759 

Here is a snippet about using %FREE in a state:
> The user specify "50%FREE", the state ran and there is 30 extents free in the VG, the LV is created with 15 extents. What should the state does at second time? Resize the Logical Volume to 7 extents?

You can see the effect of multiple 50%FREE resizes:
```
root@bat:~# lvcreate -l 50%FREE -n salttest3 testvg01
  Logical volume "salttest3" created.
root@bat:~# lvs testvg01/salttest3
  LV        VG       Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  salttest3 testvg01 -wi-a----- <2.00g                                                    
root@bat:~# lvresize -l 50%FREE /dev/testvg01/salttest3
  WARNING: Reducing active logical volume to 1.00 GiB.
  THIS MAY DESTROY YOUR DATA (filesystem etc.)
Do you really want to reduce testvg01/salttest3? [y/n]: y
  Size of logical volume testvg01/salttest3 changed from <2.00 GiB (511 extents) to 1.00 GiB (256 extents).
  Logical volume testvg01/salttest3 successfully resized.
root@bat:~# lvs testvg01/salttest3
  LV        VG       Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  salttest3 testvg01 -wi-a----- 1.00g                                                    
root@bat:~# lvresize -l 50%FREE /dev/testvg01/salttest3
  Size of logical volume testvg01/salttest3 changed from 1.00 GiB (256 extents) to 1.50 GiB (384 extents).
  Logical volume testvg01/salttest3 successfully resized.
root@bat:~# lvs testvg01/salttest3
  LV        VG       Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  salttest3 testvg01 -wi-a----- 1.50g                                                    
root@bat:~# lvresize -l 50%FREE /dev/testvg01/salttest3
  WARNING: Reducing active logical volume to 1.25 GiB.
  THIS MAY DESTROY YOUR DATA (filesystem etc.)
Do you really want to reduce testvg01/salttest3? [y/n]: y
  Size of logical volume testvg01/salttest3 changed from 1.50 GiB (384 extents) to 1.25 GiB (320 extents).
  Logical volume testvg01/salttest3 successfully resized.
root@bat:~# lvs testvg01/salttest3
  LV        VG       Attr       LSize Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  salttest3 testvg01 -wi-a----- 1.25g     
```
The volume size kept changing in each execution, because the amount of free space is different after each execution

With 100%FREE a similar problem can happen. I create a new LV salttest4 using 100%FREE:
```
root@bat:~# lvs testvg01
  LV        VG       Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  salttest  testvg01 -wi-ao---- 10.00g                                                    
  salttest2 testvg01 -wi-a-----  2.00g                                                    
  salttest3 testvg01 -wi-a-----  1.25g                                                    
root@bat:~# lvcreate -l 100%FREE -n salttest4 testvg01
  Logical volume "salttest4" created.
root@bat:~# lvs testvg01
  LV        VG       Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  salttest  testvg01 -wi-ao---- 10.00g                                                    
  salttest2 testvg01 -wi-a-----  2.00g                                                    
  salttest3 testvg01 -wi-a-----  1.25g                                                    
  salttest4 testvg01 -wi-a----- <2.75g            
```
Then I need to increase salttest4's size, to do that, I removed salttest3, and should re-run the state, which will run lvresize:
```
root@bat:~# lvremove testvg01/salttest3
Do you really want to remove active logical volume testvg01/salttest3? [y/n]: y
  Logical volume "salttest3" successfully removed
root@bat:~# lvresize -l 100%FREE /dev/testvg01/salttest4
  WARNING: Reducing active logical volume to 1.25 GiB.
  THIS MAY DESTROY YOUR DATA (filesystem etc.)
Do you really want to reduce testvg01/salttest4? [y/n]: y
  Size of logical volume testvg01/salttest4 changed from <2.75 GiB (703 extents) to 1.25 GiB (320 extents).
  Logical volume testvg01/salttest4 successfully resized.
root@bat:~# lvs testvg01
  LV        VG       Attr       LSize  Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  salttest  testvg01 -wi-ao---- 10.00g                                                    
  salttest2 testvg01 -wi-a-----  2.00g                                                    
  salttest4 testvg01 -wi-a-----  1.25g 
```
Instead a bigger logical volume, with 4G the resize to 100%FREE shrink the volume to 1.25, which was the free space after the salttest3 removal.

That's why the documentation states that the "extents" should be a number. As I wrote in the other issue, the best that I can think to keep the old undocumented behaviour, is to ignore the "extents" if it is a percentage. So, if the LV isn't present, keep creating it as it's doing now, sending directly the string to lvcreate. If it's present, do nothing, as it did before.

**Comment by dkacar-oradian** [comment]
Percentage is a number. 90% is the equivalent of 0.9. 0.9 is a number. It is not an integer (and it is not a non-negative integer), but it is a number. 90% of volume group is still a number. 3+2i is also a number. I'm not quite sure what would 2 imaginary extents look like, but it sounds cool.

**Comment by piterpunk** [comment]
"90%FREE" or "90%VG" are not numbers, they are strings. Also, the extent is the basic allocation unit for LVM, there is no such thing as a fractional extent. Usually it's not necessary to specify that the number in "amount of some unit" must be a natural number excluding zero.

**Comment by dkacar-oradian** [comment]
I know there is no such thing as a fraction or imaginary extent, but I know that from reading LVM command line utilities man pages, not from reading Salt's documentation. And those same man pages specify `[ -l|--extents Number[PERCENT] ]`.
But then, if we take a look at Salt's documentation for the `size` parameter we can read "The size of the Logical Volume" in v3002  or "The initial size of the Logical Volume" in v3001.
Taking the issue of "initial" aside at the moment, that begs the question in which units, strings or whatevers should I specify the value for `size`. Salt documentation doesn't say. If I put a number there, would that be the number of bits, bytes, disk blocks, kilobytes or what? Does it take some kind of units? If so, would that be "MB" of just "M"? And are the units the power of 1024 or the power of 1000?
Salt's documentation doesn't say any of those things. So the only reasonable thing I can think of is to take a look at the LVM man pages and check there.
But then, the same kind of man page checking should apply to the `extents` and other parameters, no? Salt's documentation again doesn't say anything about that, but I don't see any other rational conclusion. And so the "number" in the `extents` specification is just a placeholder for "whatever the man page says can go there".

And in all decent specifications I've seen to date people were using "integer" when they meant integer. I think that your "usually it's not necessary to specify" is a sign of pretty big incompetence. Not necessarily your own, but there's no way to defend that. You can use a "number" if it's specified somewhere else and you're referring to that spec. For example, databases usually have data type "number" and in the context of that database it's specified what "number" means.

**Comment by sagetherage** [comment]
closing as a dup, please put all comments in #58759, thank you!
