### ISSUE TITLE
[BUG] 3002 breaks rendering of GPG pillar data

### ISSUE THREAD

**Issue by dataflake** [saltstack/salt#58794]
**Description**
I am using GPG-encrypted pillar data. Last night the salt packages auto-updated from 3001.1 to 3002:

```
--------------------- dnf-rpm Begin ------------------------ 

Packages Updated:
   salt-3001.1-1.el8.noarch -> salt-3002-1.el8.noarch
   salt-master-3001.1-1.el8.noarch -> salt-master-3002-1.el8.noarch
   salt-minion-3001.1-1.el8.noarch -> salt-minion-3002-1.el8.noarch
   salt-ssh-3001.1-1.el8.noarch -> salt-ssh-3002-1.el8.noarch
```

**Setup**
CentOS 8
salt packages from the official repository at https://repo.saltstack.com/py3/redhat/8/$basearch/latest
Pillar data is stored in a pillar file tree and each file contains a PGP MESSAGE block

**Steps to Reproduce the behavior**
Try to view pillar data, e.g. `salt <server> pillar.items`

**Expected behavior**
I expect the pillar data output to contain decrypted data for keys that use PGP encryption. But they just contain the PGP MESSAGE block.

**Screenshots**

**Versions Report**
```
# salt --versions-report
Salt Version:
           Salt: 3002

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.6
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: 0.4.6
         PyYAML: 3.12
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.19.1.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core
```
</details>

**Additional context**
Changing the yum repository link from https://repo.saltstack.com/py3/redhat/8/$basearch/latest to https://repo.saltstack.com/py3/redhat/8/$basearch/3001 and issuing `dnf downgrade ...` for the installed salt packages and then restarting master and minion solves the issue immediately.

**Comment by Ch3LL** [comment]
I'm not able to replicate this. 

```
[root@0b1d1b9f7803 /]# cat /srv/pillar/one.sls 
#!yaml|gpg

secret: |
  -----BEGIN PGP MESSAGE-----

  hQGMAxhvtQVE1bjaAQwAk2TeX4njNL1ut6znrjmnJIEmtsRL2Ar3QNEAurU6QJ5b
  +ViHyuDPplVWel+AopSE5J7JivulZtkT/qt5+TzJreqQ4fDUkEt17Cln5SB+uxRO
  79OFtxzyHrAYedCuao0z2P6hyP0WhKg5kFVOe9aiEwmAj8BwucovHW0RXk/IyT8h
  +roRifLf/u+9XO9/a3LumjISOJFUwb0BAPxuHHiYKewi6DOT2hC3w1nZaKA7Dyoo
  zX3Dpn0faxFKg+yWRGWAj25RFWO0vAc+kdFMDPaJN9X+jE6NVfykmMwh47CNwVRq
  XEr8fSPes9OW/9QM6ZiWJvR+Mk3PQE8fWkACi4gg2WFs3Ct/3YCx+urvSWaKLrdQ
  htTOT2WtFoRxEd7E6JxSQ0Pv7MYcq/7ds9H/TepoDBpoVQXmAIZbkkDC+rELkMMt
  LndW6buE8KEr4mgv9vZbl8Kfr4jo3F5wR9A/7S+7SCkuUqKV0XyMgY30NMrgECYQ
  NPK1cRkBn/FP6yVvLsbc0kYBRFCMuiCLOTwzo1gVEXbTS9rhulsHn9WNWPOWSujH
  Yhe58bjjUqF93dTuminuMRhpIF7RjYQ1RcGyRR1fdZ0pxekbg6iq
  =4/BR
  -----END PGP MESSAGE-----
[root@0b1d1b9f7803 /]# salt \* pillar.items
test_minion:
    ----------
    secret:
        supersecret
[root@0b1d1b9f7803 /]# salt --version
salt 3002
[root@0b1d1b9f7803 /]# 
```

Anything in your debug logs that would indicate whats occurring? Any other information to help replicate what your seeing?

**Comment by dataflake** [comment]
I can confirm that the specific usage you demonstate, storing the GPG message block right inside a SLS file and adding the `#!yaml|gpg` instruction at the top still works, but that's not what I use. I use the following in my master configuration:

```
ext_pillar:
  - file_tree:
      root_dir: /path/to/pillar/root
      follow_dir_links: False
      keep_newline: False
  - gpg: {}
```

and the tree underneath `/path/to/pillar/root` contains a file structure with data files that have just the GPG message block in them. This worked with 3001. It doesn't work with 3002.

**Comment by Ch3LL** [comment]
thanks for the additional information. I am able to replicate this now and am working on a fix.

**Comment by Ch3LL** [comment]
can you try fix here https://github.com/saltstack/salt/pull/58815

**Comment by dataflake** [comment]
I can confirm that #58815 fixes the issue in my local sandbox.

**Comment by Ch3LL** [comment]
thanks for confirming :)

**Comment by Ch3LL** [comment]
@dataflake i ended up changing my approach in the PR. Can you give the change in #58815 another try please

**Comment by dataflake** [comment]
I switched out ` salt/pillar/file_tree.py` with the version in #58815 and it works.

**Comment by Ch3LL** [comment]
thanks for attempting that. i actually realized that there were historically reasons for allowing bytes in the file_Tree pillar so i actually ended up reverting to the original PR here https://github.com/saltstack/salt/pull/58917#pullrequestreview-529478529  just as an fyi
