### ISSUE TITLE
Question: How to setup Salt minion on AIX systems

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#58829]
**Description**
My databases are hosted in AIX server. How can I install salt minion on that servers? I couldnt find any direct link for the installation. could any one please send the available doc?

**Comment by bitskri3g** [comment]
AIX requires SSE: https://help.saltstack.com/hc/en-us/articles/360041242251-Why-are-AIX-and-Solaris-minions-only-supported-in-SaltStack-Enterprise-

**Comment by sooraj2589** [comment]
@bitskri3g 
I couldn't find the link for installing minion on AIX. We have procured SSE, now in the stage on installation setup. 

Could any one please provide the correct link for the installation?
Have tried [https://enterprise.saltstack.com/docs/downloads.html#aix-solaris-minions]

**Comment by Philip-A-Fry** [comment]
I know this is a bit old now, but I see the AIX minions here: 
- https://repo.saltproject.io/salt/py3/aix/
