### ISSUE TITLE
Question: usage of jinja-variables in salt-cmd.shell command

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#58821]
**Description of Issue/Question**

I am trying to get the jar files inside a directory in a salt-state.

**Setup**

```
{% import 'maps1_pilot.jinja' as hc %}
{% set remove_jar = salt['cmd.shell']('find $hc.Home_Path  -maxdepth 1 -type f -name "*.jar"') %}

preparation_deployment:
{% if remove_jar|length %}
  cmd.run:
    - names:
      - echo "removing existing jars"
      - rm {{ remove_jar }}
{% else %}
```

But getting the error output:-

not able to set the variable **remove_jar** not getting proper values.

preparation_deployment:

```
  cmd.run:
    - names:
      - echo "removing existing jars"
      - rm find: '.Home_Path': No such file or directory    <======================
```

But getting the value if I entered the path directly

Is there correct/another way to do it?

**Version**
3000.3

**Comment by OrangeDog** [comment]
It's a jinja variable, not a shell variable:
```sls
{% set remove_jar = salt['cmd.shell']('find ' ~ hc.Home_Path ~ ' -maxdepth 1 -type f -name "*.jar"') %}
```

Also, rather than calling out to shell, use the builtin function
```sls
{% set remove_jar = salt['file.find'](hc.Home_Path, maxdepth=1, type='f', name='*.jar') %}
```

You could use find's delete action, but a stateful system is prefered:
```sls
{% for file in remove_jar %}
{{ file }}:
  file.absent: []
{% endfor %}
```

**Comment by sooraj2589** [comment]
> It's a jinja variable, not a shell variable:
> 
> ```yaml-salt
> {% set remove_jar = salt['cmd.shell']('find ' ~ hc.Home_Path ~ ' -maxdepth 1 -type f -name "*.jar"') %}
> ```
> 
> Also, rather than calling out to shell, use the builtin function
> 
> ```yaml-salt
> {% set remove_jar = salt['file.find'](hc.Home_Path, maxdepth=1, type='f', name='*.jar') %}
> ```
> 
> You could use find's delete action, but a stateful system is prefered:
> 
> ```yaml-salt
> {% for file in remove_jar %}
> {{ file }}:
>   file.absent: []
> {% endfor %}
> ```

This works..! thank you very much for the great support
