### ISSUE TITLE
Question: Is it possible to control Data guard with Saltstack?

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#58831]
**Description**
We have Data guard in the infrastructure, looking forward to control the Data guard with saltstack. Is it possible to control DG with salt?

**Comment by bitskri3g** [comment]
There is no data guard module, but in theory you should be able to use the native cmd.script/cmd.run modules and states and control it that way.  Alternatively, you can write a custom module to do this work.

**Comment by sagetherage** [comment]
Please join our mailing lists, join our slack channels or find us on IRC for general questions.
