### ISSUE TITLE
[BUG] AttributeError: 'CacheDict' object has no attribute '_dict' when memory used as pillar_cache_backend

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#58838]
**Description**
`pillar_cache_backed: memory` is not experimental it is just broken. pillar makes log.debug calls to `self.cache._dict` however the CacheDict object does not have a _dict Attribute. while the CacheDisk object does. this completely breaks pillar if you try setting the pillar_cache backend to memory. 

**Setup**
set up pillar cache with `pillar_cache_backend: memory` refresh the minions cache and very the masters log and also see there are no pillars on the minions. 

**Steps to Reproduce the behavior**

See setup steps above and look in the logs for the following error and see that no minions have pillar. 

```
2020-10-29 08:40:17,845 [salt.master      :2019][ERROR   ][7443] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 2013, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3.6/site-packages/salt/master.py", line 1710, in _pillar
    data = pillar.compile_pillar()
  File "/usr/lib/python3.6/site-packages/salt/pillar/__init__.py", line 445, in compile_pillar
    log.debug("Scanning cache: %s", self.cache._dict)
AttributeError: 'CacheDict' object has no attribute '_dict'
```

**Expected behavior**
Even if experimental the basic functionality should at least keep a catastrophic failing of pillar rendering from happening. 

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3002

Dependency Versions:
           cffi: 1.14.0
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: 0.26.6
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: Not Installed
   pycryptodome: 3.9.8
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: 2.3.1
         PyYAML: 3.13
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.13.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core

```
</details>

Although this issue goes back to at least 2018.3.5 maybe as far back as when the option to include `pillar_cache_backend` was allowed.

**Comment by whytewolf** [comment]
zd-5931

**Comment by garethgreenaway** [comment]
It looks like the `CacheDisk` class has a `_dict` attribute, but the CacheDict one does not, since it is itself a Dict.  It's likely that the log messages were added to handle when the cache option was to use disk instead of memory.
