### ISSUE TITLE
URLError: <urlopen error [Errno -2] Name or service not known>

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#58867]
**Salt minion version: salt-minion 2018.3.4 (Oxygen)
Bug description: I have a salt returner file named abc.py, and it will send a http request with urllib2, but then i got the error below, and i'm sure my dns is normal because curl is ok. It will be fine after i reboot salt minion.**

...skipping...
    return opener.open(url, data, timeout)
  File "/usr/lib64/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/usr/lib64/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/usr/lib64/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib64/python2.7/urllib2.py", line 1244, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib64/python2.7/urllib2.py", line 1214, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno -2] Name or service not known>

**Comment by sagetherage** [comment]
@andyyumiao salt v2018.3.4 is no longer supported, are you able to upgrade to a supported version?

**Comment by garethgreenaway** [comment]
@andyyumiao Following up, the version you reported the problem again is no longer supported.  Are you able to upgrade to the latest version which is now 3003.1 and provide the code that is your custom returner, abc.py?  The above error could also be related to the fact that Python 2.7 is no longer supported.

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity.  If the problem persists please feel free to reopen this issue or open a new one.
