### ISSUE TITLE
[FEATURE REQUEST] Automatically update in-memory pillar upon highstate

### ISSUE THREAD

**Issue by yleong** [saltstack/salt#58877]
**Is your feature request related to a problem? Please describe.**
So in-memory pillar is not refreshed even when after a highstate or pillar.items. 
https://docs.saltstack.com/en/latest/topics/pillar/index.html#in-memory-pillar-data-vs-on-demand-pillar-data

**Describe the solution you'd like**
It will be good to opportunistically update the in-memory pillar with the fresh pillars generated during a highstate.

**Describe alternatives you've considered**
I've considered running saltutil.refresh_pillar periodically but that seems expensive/redundant since for my use case I am already running highstates regularly.

**Additional context**

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by waynew** [comment]
IIUC from reading that doc, it's potentially expensive to refresh the pillar. If you're running highstate and you'd like to refresh the pillars you can always [use the saltutil state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.saltutil.html#salt.states.saltutil.sync_pillar) as an `order: last`. Does that suit your purposes?

**Comment by sagetherage** [comment]
@yleong please let us know if this solves what you potentially asked for in a feature request and we can close or something else?

**Comment by sagetherage** [comment]
Reviewed in Grooming 2021-JUN-21 closing as not a feature to implement, but rather the use the saltutil state for `order: last`
