### ISSUE TITLE
[BUG] gpg: decryption failed: No secret key

### ISSUE THREAD

**Issue by xuhcc** [saltstack/salt#58880]
**Description**

`salt-ssh` started to warn about failed decryption after upgrade from v3001 to v3002 when it runs states. It seems to decrypt pillar data correctly though. `pillar.items` executes without warnings.

**Setup**

master config:

```
root_dir: .
pki_dir: config/pki
cachedir: config/cache
log_file: config/log
gpg_keydir: gpgkeys/

file_roots:
  base:
    - states

pillar_roots:
  base:
    - pillar
```

**Steps to Reproduce the behavior**

```
$ salt-ssh 'myserver' state.apply
[WARNING ] Could not decrypt cipher b'-----BEGIN PGP MESSAGE-...........-END PGP MESSAGE-----', received: b"gpg: keyblock resource '/var/tmp/.vp_684964_salt/gpgkeys/pubring.kbx': No such file or directory\n[GNUPG:] ERROR add_keyblock_resource ....\n[GNUPG:] ENC_TO .... 1 0\n[GNUPG:] ERROR keydb_search ....\n[GNUPG:] ERROR keydb_search ....\ngpg: encrypted with RSA key, ID ....\n[GNUPG:] NO_SECKEY ...\n[GNUPG:] BEGIN_DECRYPTION\n[GNUPG:] DECRYPTION_FAILED\ngpg: decryption failed: No secret key\n[GNUPG:] END_DECRYPTION\n"
```

**Expected behavior**

Should not produce any warnings.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3002.1
 
Dependency Versions:
           cffi: 1.14.3
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: 4.0.5
      gitpython: 3.1.7
         Jinja2: 2.11.2
        libgit2: Not Installed
       M2Crypto: 0.36.0
           Mako: 1.1.3
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 3.9.8
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.8.6 (default, Sep 30 2020, 04:00:38)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3
 
System Versions:
           dist: arch  
         locale: utf-8
        machine: x86_64
        release: 5.9.2-arch1-1
         system: Linux
        version: Arch Linux  
```
</details>

**Comment by kkoppel** [comment]
We have the same issue after upgrading from v3001.1 to v3002.1.
Looks like all states apply as before, but we get the same warning.

**Comment by s0undt3ch** [comment]
What python version is available on the hosts where salt-ssh runs?

**Comment by kkoppel** [comment]
On the target host we have Python 3.6.5.
On the master we have Python 3.7.3.

**Comment by xuhcc** [comment]
In my case the target has 2.7.17 and 3.6.9
Master has 3.8.6

**Comment by sc-kanga** [comment]
Can I ask what distribution you guys are using?

**Comment by kkoppel** [comment]
My target host is running Container-Optimized OS v1.17.12-gke.1504 (it's a GKE VM).

**Comment by sc-kanga** [comment]
Cheers; have you checked whether the default GPG home is set correctly? 

It _should_ be set to /etc/salt/gpgkeys but we've just had an issue where on Ubuntu the system sets it but on RedHat we've had to set manually. 

We had to set the GNUPGHOME environment variable in root's bash_profile and also on the salt-master service.

**Comment by kkoppel** [comment]
On my setup no changes to configuration were made when switching from v3001.1 to v3002.1 and it worked fine earlier.
I have gpg_keydir set to "/etc/salt/gpgkeys/" in master configuration. Never had to set GNUPGHOME for the master.

As the description says, decryption of secrets is still working fine with v3002.1. The issue here is the warning being shown when using salt-ssh.

**Comment by xuhcc** [comment]
The warnings disappeared after I upgraded to v3002.2

**Comment by s0undt3ch** [comment]
@Ch3LL will correct me, but I believe we stopped supporting Python 2 on the target hosts since 3001, or probably 3002, can't remember which now.

**Comment by kkoppel** [comment]
v3002.2 fixes this issue for me as well.

**Comment by Ch3LL** [comment]
Yes, Python 2 was dropped in 3001. Closing this issue now since this is resolved.
