### ISSUE TITLE
[BUG] Vault - write_raw/write_secret/destroy_secret/sdb.get/ext_pillar doesn't works

### ISSUE THREAD

**Issue by anthosz** [saltstack/salt#58897]
**Description**
Unable to create secret.
Read/delete works.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

**Steps to Reproduce the behavior**
`salt 'server' vault.write_raw "test/data/test" '{"aa":"aa"}'`
[OR]
`salt 'server*' vault.write_secret "test/data/test" aa="aa"`
-> Response: False / Failed to write secret! HTTPError: 400 Client Error: Bad Request for url: https://XXX/v1/test/data/test
(Include debug logs if possible and relevant)
-> Trying with the same token via vault bin: works -> vault kv put salt/test aa=aa 

Audit via vault bin:
```
{"time":"XXXXXXXX","type":"request","auth":{"client_token":"hmac-sha256:XXXXXXXX","accessor":"hmac-sha256:XXXXXXXX","display_name":"token","policies":["XXXXXXXX","XXXXXXXX"],"token_policies":["XXXXXXXX","XXXXXXXX"],"token_type":"service","token_ttl":XXXXXXXX,"token_issue_time":"XXXXXXXX"},"request":{"id":"XXXXXXXX","operation":"update","mount_type":"kv","client_token":"hmac-sha256:XXXXXXXX","client_token_accessor":"hmac-sha256:XXXXXXXX","namespace":{"id":"root"},"path":"test/data/test","data":{"data":{"aa":"hmac-sha256:XXXXXXXX"},"options":{}},"remote_address":"XXXXXXXX"}}
{"time":"XXXXXXXX","type":"response","auth":{"client_token":"hmac-sha256:XXXXXXXX","accessor":"hmac-sha256:XXXXXXXX","display_name":"token","policies":["XXXXXXXX","XXXXXXXX"],"token_policies":["XXXXXXXX","XXXXXXXX"],"token_type":"service","token_ttl":XXXXXXXX,"token_issue_time":"XXXXXXXX"},"request":{"id":"XXXXXXXX","operation":"update","mount_type":"kv","client_token":"hmac-sha256:XXXXXXXX","client_token_accessor":"hmac-sha256:XXXXXXXX","namespace":{"id":"root"},"path":"test/data/test","data":{"data":{"aa":"hmac-sha256:XXXXXXXX"},"options":{}},"remote_address":"XXXXXXXX"},"response":{"mount_type":"kv","data":{"created_time":"hmac-sha256:XXXXXXXX","deletion_time":"hmac-sha256:XXXXXXXX","destroyed":false,"version":6}}}
```
Audit via salt request:
```
{"time":"XXXXXXXX","type":"request","auth":{"client_token":"hmac-sha256:XXXXXXXX","accessor":"hmac-sha256:XXXXXXXX","display_name":"token","policies":["XXXXXXXX","XXXXXXXX"],"token_policies":["XXXXXXXX","XXXXXXXX"],"metadata":{"saltstack-jid":"XXXXXXXX","saltstack-minion":"XXXXXXXX","saltstack-user":"XXXXXXXX"},"remaining_uses":1,"entity_id":"XXXXXXXX","token_type":"service","token_ttl":XXXXXXXX,"token_issue_time":"XXXXXXXX"},"request":{"id":"6XXXXXXXX","operation":"update","mount_type":"kv","client_token":"hmac-sha256:XXXXXXXX","client_token_accessor":"hmac-sha256:XXXXXXXX","namespace":{"id":"root"},"path":"test/data/test","data":{"aa":"hmac-sha256:XXXXXXXX"},"remote_address":"XXXXXXXX"}}
{"time":"XXXXXXXX","type":"response","auth":{"client_token":"hmac-sha256:XXXXXXXX","accessor":"hmac-sha256:XXXXXXXX","display_name":"token","policies":["XXXXXXXX","XXXXXXXX"],"token_policies":["XXXXXXXX","XXXXXXXX"],"metadata":{"saltstack-jid":"XXXXXXXX","saltstack-minion":"XXXXXXXX","saltstack-user":"XXXXXXXX"},"remaining_uses":1,"entity_id":"XXXXXXXX","token_type":"service","token_ttl":XXXXXXXX,"token_issue_time":"XXXXXXXX"},"request":{"id":"XXXXXXXX","operation":"update","mount_type":"kv","client_token":"hmac-sha256:XXXXXXXX","client_token_accessor":"hmac-sha256:XXXXXXXX","namespace":{"id":"root"},"path":"test/data/test","data":{"aa":"hmac-sha256:XXXXXXXX"},"remote_address":"1XXXXXXXX"},"response":{"mount_type":"kv","data":{"error":"hmac-sha256:XXXXXXXX"}},"error":"1 error occurred:\n\t* invalid request\n\n"}
```

**Expected behavior**
Write is supposed to works

**Versions Report**
Vault: 1.5.4
```
Salt Version:
           Salt: 3000.5
Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 1.5
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.11.2
        libgit2: 0.26.3
       M2Crypto: 0.21.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: 1.4.6
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 2.7.5 (default, Sep 26 2019, 13:23:47)
   python-gnupg: 0.4.4
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: redhat 7.8 Maipo
```
</details>

**Additional context**

**Comment by anthosz** [comment]
- 'vault.destroy_secret' is not available also

- Sdb doesn't works (same if I follow the doc here: https://help.saltstack.com/hc/en-us/articles/360041140451-Quick-Guide-to-Vault-Integration):
```
salt-run sdb.get 'sdb://test_vault/test/data/test' --out=json
[ERROR   ] Failed to read secret! HTTPError: 404 Client Error: Not Found for url: https://XXXXXX/v1/salt/data
It is supposed to call "salt/data/test" instead (same if I add ?aa at then end, I confirm that the path is bad also in audit of Vault)
```
- ext_pillar doesn't works:
https://docs.saltstack.com/en/latest/ref/pillar/all/salt.pillar.vault.html followed and I can see that the request is good on audit log of vault during the refresh but nothing in the response.
`ext_pillar:
  - db: path=test/data/test
`
In top sls:
`*:
  aa`
If I try pillar.item or pillar.get aa -> no result.

**Comment by anthosz** [comment]
Do you have time to investigate on this? This essential module doesn't works anymore :(

**Comment by sagetherage** [comment]
@mchugh19 wondering if you have seen this previously, perhaps or have time to also take a peek?

**Comment by anitakrueger** [comment]
Is this a problem?
@anthosz I always got "invalid request" back from Vault if my master couldn't generate a token for the minion. Could you post your Vault policies for the master and the minion?

Also, I think the article at https://help.saltstack.com/hc/en-us/articles/360041140451-Quick-Guide-to-Vault-Integration is outdated. I couldn't get it to work with the examples posted there, but we do have a working vault integration now and use it quiet extensively.

**Comment by sagetherage** [comment]
@anitakrueger thank you! That article is a support article, but I will get with them to get that updated or completely re-written.

**Comment by JeremyHutchings** [comment]
@anitakrueger  Did you find anyway to get saltstack working with vault at all ? I can't access the article you linked to and it seems the vault support in saltstack is very broken at the moment.

**Comment by anitakrueger** [comment]
@JeremyHutchings Yes, we use Salt and Vault quite a lot now. Unfortunately not with the ext pillar module, but basically using `salt['vault'].read_secret` in our states. We manage the vault policies with Salt as well. Shame there isn't a state/module to manage user entity creation. We currently do that in terraform.

**Comment by JeremyHutchings** [comment]
@anitakrueger Thanks, so it is possible for Salt to get secrets or actually anything from Vault? 

Are you using a custom version of Vault or https://portal.cloud.hashicorp.com/services/vault/ ?

Can you give any clues to the set up or hacking you had to do to get Salt to make valid requests to Vault to get the secrets.

**Comment by anitakrueger** [comment]
@JeremyHutchings We use a vagrant environment for testing our Salt state/module changes which is updated and configured from scratch frequently. That environment then installs Vault (still on 1.6.0 atm) and configures the following in the salt master config:
```
peer:
  .*:
    - x509.sign_remote_certificate
vault:
  url: https://vault.domain.local
  auth:
    method: approle
    role_id: 12345678-8c58-aade-c0dc-123456781234
    secret_id: 12345678-0ec7-7984-3ce8-123456781234
    uses: 10
    ttl: 3600
    allow_minion_override: True
    token_backend: disk
  policies:
    - "{grains[environment]}/{grains[roles]}"
    - "saltstack/common"
```

The approle that Salt uses needs to be created in Vault to make valid requests. The policies also need to allow which secrets you are able to read/write.

Can you post your config and which errors you are seeing?

**Comment by JeremyHutchings** [comment]
Hi @anitakrueger  I can't find any documentation about setting it up other than this :

https://apassionatechie.wordpress.com/2017/09/22/saltstack-and-vault-integration/

Which seems really out of date, but I can't find anything newer for setting up the integration. 

I've got the master vault config policy down to this, with the token created below:

/etc/salt/master.d/vault.conf

```
vault:
  url: https://vault-cluster2.vault.[redacted].aws.hashicorp.cloud:8200
  auth:
    method: token
    token: [TOKEN]
```
and have /etc/salt/master.d/peer_run.conf  : 
```
peer_run:
    .*:
        - vault.generate_token
```

I created a salt-policy in Vault : 
```
path "kv/*" {
  capabilities = ["create", "read", "update", "delete", "list", "sudo"]
}

path "auth/*" {
  capabilities = ["read", "list","sudo","create","update","delete"]
}

path "sys/*" {
    capabilities = ["create", "read", "update", "delete", "list"]
}
```

Then create a key with that policy (for vault.conf on the master): 

```
workstation$> vault token create -display-name=salt-master -policy=salt-policy 
Key                  Value
---                  -----
token                [TOKEN]
token_accessor       2Y13JHovK5g0ON4r53j9KRpU.5Ubqb
token_duration       1h
token_renewable      true
token_policies       ["default" "salt-policy"]
identity_policies    []
policies             ["default" "salt-policy"]
```

Then setting some hello world KV data:

```
workstation$ vault write kv/password value=Passw0rd!
Success! Data written to: kv/password
```

Checking it's there with vault CLI just fine:

```
workstation$ vault read  kv/password
Key                 Value
---                 -----
refresh_interval    1h
value               Passw0rd!
```

Then on one of the minions trying to do the same:
```
minion$ salt-call -l debug vault.read_secret 'kv/password'
```

Just to try and get a hello world working and the only message I get is 'Forbidden' ... though I've no idea is that the Master being forbidden from creating a token for the minion to use to access Vault, or the minion being forbidden by the salt master from doing something, or something else.

```
[ERROR   ] Failed to get token from master! An error was returned: Forbidden
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/modules/vault.py", line 205, in read_secret
    response = __utils__["vault.make_request"]("GET", url)
  File "/usr/lib/python3/dist-packages/salt/utils/vault.py", line 298, in make_request
    connection = get_cache()
  File "/usr/lib/python3/dist-packages/salt/utils/vault.py", line 263, in get_cache
    return _gen_new_connection()
  File "/usr/lib/python3/dist-packages/salt/utils/vault.py", line 256, in _gen_new_connection
    connection = get_vault_connection()
  File "/usr/lib/python3/dist-packages/salt/utils/vault.py", line 179, in get_vault_connection
    return _get_token_and_url_from_master()
  File "/usr/lib/python3/dist-packages/salt/utils/vault.py", line 97, in _get_token_and_url_from_master
    raise salt.exceptions.CommandExecutionError(result)
salt.exceptions.CommandExecutionError: {'error': 'Forbidden'}

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/cli/caller.py", line 219, in call
    ret["return"] = self.minion.executors[fname](
  File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 12, in execute
    return func(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/salt/modules/vault.py", line 224, in read_secret
    raise CommandExecutionError(
salt.exceptions.CommandExecutionError: Failed to read secret! CommandExecutionError: {'error': 'Forbidden'}
Error running 'vault.read_secret': Failed to read secret! CommandExecutionError: {'error': 'Forbidden'}
```

**Comment by anthosz** [comment]
Hello,

I didn't have time to double check on my side. (but well, now there are no 'official' documentation anymore so it's tricky) 

Will tell you a feedback in few days. 

Best regards,

**Comment by anitakrueger** [comment]
@JeremyHutchings Can you specify the allowed policies in the /etc/salt/master.d/vault.conf as well? I don't think the minions get a policy assigned to them so they wouldn't be able to read any secrets: https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.vault.html

**Comment by JeremyHutchings** [comment]
@anitakrueger  I was relying on the docs of : https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.vault.html

> Optional. If policies is not configured, saltstack/minions and saltstack/{minion} are used as defaults.

So on the master I now have : 

> 
> $salt-run vault.show_policies node-14
> - saltstack/minions
> - saltstack/minion/node-14

Which I've tried before, though I'm not sure if there is anything else to specifically grant permissions to a minion to read a secret.

**Comment by glynnforrest** [comment]
Hi folks, just to say I'm using the Vault module just fine, but I agree the 'Forbidden' error message makes it really hard to debug where the problem is.

Try following the salt event bus when making Vault module calls:

```
salt-run state.event pretty=True
```

When I run `salt some-minion vault.read_secret secret/foo` in another terminal, I see the following messages:

```json
20210701115204531039    {
    "_stamp": "2021-07-01T11:52:04.531441",
    "minions": [
        "some-minion"
    ]
}
salt/job/20210701115204531039/new       {
    "_stamp": "2021-07-01T11:52:04.534022",
    "arg": [
        "secret/foo"
    ],
    "fun": "vault.read_secret",
    "jid": "20210701115204531039",
    "minions": [
        "some-minion"
    ],
    "missing": [],
    "tgt": "some-minion",
    "tgt_type": "glob",
    "user": "root"
}
salt/run/20210701115204715871/new       {
    "_stamp": "2021-07-01T11:52:05.091729",
    "fun": "runner.vault.generate_token",
    "fun_args": [
        "some-minion",
        "[REDACTED]",
        false,
        null,
        null
    ],
    "jid": "20210701115204715871",
    "user": "root"
}
salt/run/20210701115204715871/ret       {
    "_stamp": "2021-07-01T11:52:05.165046",
    "fun": "runner.vault.generate_token",
    "fun_args": [
        "some-minion",
        "[REDACTED]",
        false,
        null,
        null
    ],
    "jid": "20210701115204715871",
    "return": {
        "issued": 1625140325,
        "lease_duration": 2764800,
        "renewable": true,
        "token": "s.[REDACTED]",
        "token_backend": "session",
        "url": "https://vault.service.consul:8200",
        "uses": 0,
        "verify": null
    },
    "success": true,
    "user": "root"
}
salt/job/20210701115204531039/ret/some-minion     {
    "_stamp": "2021-07-01T11:52:05.258373",
    "cmd": "_return",
    "fun": "vault.read_secret",
    "fun_args": [
        "secret/foo"
    ],
    "id": "some-minion",
    "jid": "20210701115204531039",
    "retcode": 0,
    "return": {
        "value": "[VALUE OF secret/foo]"
    },
    "success": true
}
```

 Perhaps you could compare that to what you see to help narrow down the problem.

While they're a little old, I roughly follow the approach described in these blog posts to setup Vault and SaltStack (with a few more measures for a real deployment): https://backbeat.tech/tags/vault

**Comment by JeremyHutchings** [comment]
Hi @glynnforrest I can see how it might work with a local installation, though I don't think the saltstack implementation supports the hosted version at the moment  https://portal.cloud.hashicorp.com/services/vault/

**Comment by glynnforrest** [comment]
> Hi @glynnforrest I can see how it might work with a local installation

The example I posted referenced a Vault server running on a separate machine, in my case made available as a consul service:

```yaml
# /etc/salt/master.d/vault.conf
vault:
  url: https://vault.service.consul:8200
  auth:
    method: token
    token: s.[REDACTED]
```

> though I don't think the saltstack implementation supports the hosted version at the moment 

If the HCP Vault was accessible from the SaltStack machine, I can't see why putting a different URL (`https://vault-cluster2.vault.[redacted].aws.hashicorp.cloud:8200`) in there would change anything. I haven't tried HCP with SaltStack though, so perhaps I'm missing something.

**Comment by anthosz** [comment]
Dear all,

All seems to works right now.

Best regards,
