### ISSUE TITLE
[BUG] Regenerating grains every time a job runs on windows.

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#58904]
**Description**

The minion is regenerating grains for every job run on windows. This is slow and a waist of resources.

**Comment by damon-atkins** [comment]
Its due to the way fork/thread are implemented in python.  See also Master calling find_job every 10 seconds, Windows takes 10 seconds to execute it #51621

**Comment by damon-atkins** [comment]
The Grains process should be come a independent process, which collects all the data and saves into a cache file. And is regenerated once per system boot.  I suspect would also fit better with idem this way.  Possible it could mean a smaller amount of code in memory. @saltstack/core-pr-reviewers

**Comment by dwoz** [comment]
> Its due to the way fork/thread are implemented in python. See also `Master calling find_job every 10 seconds, Windows takes 10 seconds to execute it` #51621

Having understood that, this is still an issue and the fix provides a speed increase on Windows.

**Comment by dwoz** [comment]
> The Grains process should be come a independent process, which collects all the data and saves into a cache file. And is regenerated once per system boot. I suspect would also fit better with idem this way. Possible it could mean a smaller amount of code in memory. @saltstack/core-pr-reviewers

We are not re-designing grains right now. Simply fixing an issue that we found on Windows.
