### ISSUE TITLE
[BUG] Salt-call boto fails when boto is installed

### ISSUE THREAD

**Issue by kitsushadow** [saltstack/salt#58901]
**Description**

I can't get basic commands like 
salt-call boto_ec2.get_tags my-instance-id 
to run. 

salt-call boto_ec2.get_tags i-xxxxxxxxxxxxx
'boto_ec2' __virtual__ returned False: A minimum version of boto 2.8.0 is required.

pip list | grep boto
boto             2.49.0
boto3            1.16.12
botocore         1.19.12

**Setup**
salt-call boto_ec2.get_tags my-instance-id 

**Steps to Reproduce the behavior**
salt-call boto_ec2.get_tags my-instance-id 

**Expected behavior**
boto version check succeeds

**Screenshots**

**Versions Report**
salt-minion -V
Salt Version:
           Salt: 3002.1

Dependency Versions:
           cffi: Not Installed
       cherrypy: 5.6.0
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, May  6 2020, 12:04:35)
   python-gnupg: Not Installed
         PyYAML: 5.2
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: rhel 7.9 Maipo
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1062.el7.x86_64
         system: Linux
        version: Red Hat Enterprise Linux Server 7.9 Maipo

```
PASTE HERE
```
</details>

**Additional context**

**Comment by alftheo** [comment]
How was this solved? Still happening to me with 3005.2
