### ISSUE TITLE
Failed: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by nkrishnakishor** [saltstack/salt#58910]
### Description of Issue

Trying to use cmd.run output in Jinja If loop but seeing error as mapping values are not allowed in this context

### Setup
Below is the state file
```
{% if salt['cmd.shell']('whoami') == 'root' %} 
test cmd run:
  cmd.run:
    - name: echo success
{% endif %}
```

### Steps to Reproduce Issue
```salt *server* state.sls linux.test```

server:
    - Rendering SLS 'base:linux.test' failed: mapping values are not allowed in this context
ERROR: Minions returned with non-zero exit code

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

```
# salt --versions-report 
Salt Version:
           Salt: 3000.3

Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Feb 20 2019, 09:59:36)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 14.5.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.0.5

System Versions:
           dist: centos
         locale: UTF-8
        machine: x86_64
        release: 2.6.32-754.18.2.el6.x86_64
         system: Linux
        version: CentOS
```

**Comment by Ch3LL** [comment]
I'm not able to replicate this with your exact state. is there additional information when run with debug mode (`-ldebug`) on the target minion?

Also what happens when you run that command against your minion outside of the state file `salt-call cmd.shell whoami -ldebug`

**Comment by nkrishnakishor** [comment]
i got over the issue.

**Comment by tacerus** [comment]
There is no semicolon in your example.

**Comment by Exagone313** [comment]
@tacerus I meant `colon`, this is fixed :stuck_out_tongue:

**Comment by tacerus** [comment]
Oh, thank you - turns out, the error going by the same message on my end was caused by a _missing_ colon.
