### ISSUE TITLE
[BUG] The appoptics_return module couldn't load the appoptics_metrics module.

### ISSUE THREAD

**Issue by erwindon** [saltstack/salt#58911]
**Description**
An error message about "appoptics" is shown in the master logfile.
to be exact:
`[ERROR   ] The appoptics_return module couldn't load the appoptics_metrics module.`
`[ERROR   ] please make sure it is installed and is in the PYTHON_PATH.`

**Setup**
one master with 3 minions, each within their own virtualbox VM.

**Steps to Reproduce the behavior**
I think this happens always.

**Expected behavior**
No error message is shown

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
           Salt: 3002.1
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.7.3
      docker-py: 3.4.1
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1
 
System Versions:
           dist: debian 10 buster
         locale: utf-8
        machine: x86_64
        release: 4.19.0-12-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**
The same error message is visible in #58786, although that issue otherwise has a totally different content.

The source file `salt/returners/appoptics_return.py` clearly logs this error when module `appoptics_metrics` cannot be loaded.
But `appoptics_metrics` is an optional third-party library. Therefore it is more likely to be absent (and thus produce the error message).

**Comment by oeuftete** [comment]
@erwindon I see you are using 3002.1.  I strongly recommend upgrading to 3002.2.  Among other things, the issue you are reporting is fixed (via https://github.com/saltstack/salt/pull/57723).

**Comment by erwindon** [comment]
I already upgraded a few days ago, but I did not verify the status of this one again... thx!
