### ISSUE TITLE
Question: Usage of sh script inside cmd.shell assign to Jinja variable

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#58913]
I have written the state file for checking the server status using pid.

```
{% from "maps1.jinja" import HC_CIF_HOME1 %}
{% set path = HC_CIF_HOME1+"/scripts/./check_pid.sh" %}
{% set ret1 = salt ['cmd.shell'] (path) %}
server_status:
{% if ret1 == 1 %}
  cmd.run:
    - name: echo "Server started successfully"
{% endif %}
```

Locally check_pid.sh gives 1  but ret1 is not getting the value 1 here. instead getting the error:
"scripts/./check_pid.sh: line 1: [: -e: binary operator expected".  is the condition I added wrong? if so could any one please direct me to right way?

salt version
3000.3

**Comment by sooraj2589** [comment]
@OrangeDog,
could anyone help

**Comment by Ch3LL** [comment]
> Locally check_pid.sh gives 1 but ret1 is not getting the value 1 here

How is your script returning 1? Is 1 an exit code, etc?

Also what happens when you the `cmd.shell` command outside of your state file?

**Comment by sooraj2589** [comment]
Thank you. The issue got resolved, it was the issue with path in bash script
