### ISSUE TITLE
[BUG] can't find us-gov-east-1 region

### ISSUE THREAD

**Issue by kitsushadow** [saltstack/salt#58925]
2020-11-11 16:41:12,903 [salt.minion      :1949][ERROR   ][19755] Problem executing 'boto_elb.get_all_elbs': Region "us-gov-east-1" is not valid.

Simple issue. 
salt '*' boto_elb.get_all_elbs region=us-gov-west-1
minion:

salt '*' boto_elb.get_all_elbs region=us-gov-east-1
minion:
    ERROR executing 'boto_elb.get_all_elbs': Region "us-gov-east-1" is not valid.
ERROR: Minions returned with non-zero exit code

us-gov-east-1 is definitely a valid region

**Comment by sagetherage** [comment]
@kitsushadow can you give us salt versions report please?

**Comment by sagetherage** [comment]
likely this is a hard coded list, putting it into blocked to get that version report please @kitsushadow and will follow up with team-boto

**Comment by sagetherage** [comment]
@kitsushadow can you give us more details like the salt versions report for both master and minion and what steps you took to see this error, please?

**Comment by garethgreenaway** [comment]
@kitsushadow Following up on this one, were you able to provide a Salt version report so we know what version of Salt this is affecting?  Thanks!

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity.  If the problem persists please feel free to reopen this issue or open a new one.
