### ISSUE TITLE
[BUG] Problemas with minonfs / Version 3002.1 / Failed to load function minionfs

### ISSUE THREAD

**Issue by erespaulo** [saltstack/salt#58932]
Hi,

We upgraded a Salt structure from version 3000.3 to 3002.1;

In my configuration file, the fileserver_backend option was enabled.

"file_recv: True

fileserver_backend:
 - minionfs
 - roots

minionfs_mountpoint: salt: // minionfs "

After upgrading, I am experiencing the following error messages.

"2020-11-12 09: 54: 17,664 [salt.loader: 1992] [ERROR] [217520] Failed to load function minionfs.envs because its module (minionfs) is not in the whitelist: ['minion', 'roots '] "

Following the documentation (https://docs.saltstack.com/en/latest/topics/tutorials/minionfs.html), the simple configuration should already work, but it presented the error.

I added some other parameters even to try to resolve this whitelist issue
"file_recv: True
minionfs_env: minionfs

fileserver_backend:
 - minionfs
 - roots

minionfs_whitelist: minionfs

minionfs_mountpoint: salt: // minionfs "

However the error continues, what parameter is missing in this version (3002.1)?

[root @ master master.d] # salt-run test.get_opts | grep minionfs
[ERROR] The appoptics_return module couldn't load the appoptics_metrics module.
[ERROR] please make sure it is installed and is in the PYTHON_PATH.
    - minionfs
minionfs_blacklist:
minionfs_env:
    minionfs
minionfs_mountpoint:
    salt: // minionfs
minionfs_update_interval:
minionfs_whitelist:

I found several related / similar issues:

https://github.com/saltstack/salt/issues/50781
https://github.com/saltstack/salt/pull/49526

Salt Version:
           Salt: 3002.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: unknown
       dateutil: 2.8.1
      docker-py: 1.10.6
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: Not Installed
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-193.28.1.el8_2.x86_64
         system: Linux
        version: CentOS Linux 8 Core

Anyone can help?

Tks

**Comment by Timbus** [comment]
Yeah, I fixed this in an MR.. https://github.com/saltstack/salt/pull/58564
It's also fixed for any other filesystem ending in -fs.

**Comment by erespaulo** [comment]
@Timbus , i take a look for the tentative of build, but there's erros at Win2019 and Freebsd distro stomping your merge.

**Comment by erespaulo** [comment]
Just for knowledge, It happens to version of Salt 3002.2 too.

**Comment by sagetherage** [comment]
Yes, the fix was merged into `master` and released in `Aluminium` for the Salt version 3003
