### ISSUE TITLE
[BUG] hgfs fileserver backend still broken

### ISSUE THREAD

**Issue by AlexanderplUs** [saltstack/salt#58963]
**Description**
Issue https://github.com/saltstack/salt/issues/58191 hasn't been fixed. hgfs fileserver still doesn't work even after applying https://github.com/saltstack/salt/pull/58852

**Setup**
```
fileserver_backend:
  - hgfs

hgfs_remotes:
  - http://repo.com/my_repo  # replace by a valid repo url
```

**Steps to Reproduce the behavior**
`salt-run fileserver.file_list base hgfs` always shows nothing

**Expected behavior**
Get files from hgfs fileserver backend

**Versions Report**
current master 

**Research**
As long as I can find, the main reason is that `hglib` returns binary strings and salt expects standard python3 strings. In search for branch there is comparison between binary string returned from hglib (for example b'default') and target branch from saltenv (for example 'default'). This comparison is always False. So `_get_branch` function in `_get_ref` can't find branches.

**Comment by cmcmarrow** [comment]
@alex-leonhardt the PR only fixed init. We still need to go in and fix the other parts.

**Comment by alex-leonhardt** [comment]
@cmcmarrow did you mean @AlexanderplUs ?

**Comment by whytewolf** [comment]
looking into this now. @AlexanderplUs you were correct about the bytes vs strings issue. looking into this deeper python-hgfs is definitely returning bytes all over the place. looking into cleaning up the items now. lots of places we pull info.
