### ISSUE TITLE
[BUG] Problem with gitfs (pygit2) on CentOS 8

### ISSUE THREAD

**Issue by mdzidic** [saltstack/salt#58972]
**Description**
After installation and configuration of the latest SaltStack, I'm unable to use Git as a repository for our States and Pillars.

**Setup**

/etc/salt/master.d/states.conf
```
fileserver_backend:
  - roots
  - git
gitfs_remotes:
  - ssh://git@xxx.xxx.xxx.xxx
gitfs_root: states
gitfs_provider: pygit2
gitfs_pubkey: /etc/salt/.ssh/id_rsa_gitfs.pub
gitfs_privkey: /etc/salt/.ssh/id_rsa_gitfs
```

/etc/salt/master.d/pillar.conf
```
ext_pillar_first: True
ext_pillar:
  - git:
    - master ssh://git@xxx.xxx.xxx.xxx:
      - root: pillar
      - privkey: /etc/salt/.ssh/id_rsa_gitfs
      - pubkey: /etc/salt/.ssh/id_rsa_gitfs.pub
```

**Steps to Reproduce the behavior**
1. Clean CentOS 8 installation (docker image centos:centos8)
2. SaltStack from the official Salt Python3 repository

- Installation process:
```
dnf install epel-release
dnf install https://repo.saltstack.com/py3/redhat/salt-py3-repo-latest.el8.noarch.rpm
dnf install salt-master python3-pygit2
```

- Configuration process:
> Setup from above

- After starting Salt master I get this error message:
`[ERROR   ] Unable to fetch SSH-based gitfs remote 'ssh://git@xxx.xxx.xxx.xxx/xxx/salt.git'. You may need to add ssh:// to the repo string or libgit2 must be compiled with libssh2 to support SSH authentication.`

**Expected behavior**
Salt master should pull States and Pillars from the defined Git repository.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3002.1

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.14
       pycrypto: Not Installed
   pycryptodome: Not Installed
         pygit2: 0.26.4
         Python: 3.6.8 (default, Apr 16 2020, 01:36:27)
   python-gnupg: Not Installed
         PyYAML: 3.12
          PyZMQ: 19.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3

System Versions:
           dist: centos 8 Core
         locale: UTF-8
        machine: x86_64
        release: 5.4.39-linuxkit
         system: Linux
        version: CentOS Linux 8 Core
```
</details>

**Additional context**
There is an official `libssh2` deprecation announcement on https://github.com/libgit2/libgit2/issues/5225

**Comment by OrangeDog** [comment]
Duplicates #58623

**Comment by sagetherage** [comment]
Closing this in favor of duplicate issue #56127
