### ISSUE TITLE
[TEST FAILURE] tests.integration.client.test_syndic failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#58975]
When the test `tests.integration.client.test_syndic` is run individually with pytest it will fail. I found out this is because the syndic master is not running on pytest. When the test is not run individually the test passes but this is because the client is cached so when other tests run first the client is targeting the master so when it gets to the syndic tests its also targeting the master and not the syndic master.

After finding this i found out that even on runtests.py we were never properly testing the syndic either. Its currently targeting hte master when running the test individually or with other tests.

This issue is to track the work to properly get the syndic tests working on pytest. Would also be good to move the syndic tests to the pytest directory as well.

**Comment by s0undt3ch** [comment]
For history purposes, to get the right cached client we we would do:
```diff
diff --git a/tests/support/case.py b/tests/support/case.py
index f7355f7e10..77522c2b1a 100644
--- a/tests/support/case.py
+++ b/tests/support/case.py
@@ -918,6 +918,20 @@ class SyndicCase(TestCase, SaltClientTestCaseMixin):
     _salt_client_config_file_name_ = "syndic_master"
+    @property
+    def client(self):
+        # Late import
+        import salt.client
+
+        if "runtime_syndic_client" not in RUNTIME_VARS.RUNTIME_CONFIGS:
+            mopts = self.get_config(
+                self._salt_client_config_file_name_, from_scratch=True
+            )
+            RUNTIME_VARS.RUNTIME_CONFIGS[
+                "runtime_syndic_client"
+            ] = salt.client.get_local_client(mopts=mopts)
+        return RUNTIME_VARS.RUNTIME_CONFIGS["runtime_syndic_client"]
+
     def run_function(self, function, arg=(), timeout=90):
         """
         Run a single salt function and condition the return down to match the
```
