### ISSUE TITLE
[DOCS] salt.states.user correction

### ISSUE THREAD

**Issue by leonardp** [saltstack/salt#59005]
**Description**
The default value for `hash_password` given in the `salt.states.user` documentation appears to be wrong.

**Suggested Fix**
change `False` to `True`

**Location or format of documentation**
https://docs.saltstack.com/en/master/ref/states/all/salt.states.user.html

**Additional context**
After fiddeling around with hashed password in our salt pillar we discovered that we had to set
hash_password to `False` to make it work.

**Comment by cmcmarrow** [comment]
the arg `hash_password` is set to false by default https://github.com/saltstack/salt/blob/master/salt/states/user.py

**Comment by cmcmarrow** [comment]
What are you trying to do @leonardp?

**Comment by leonardp** [comment]
we are creating user accounts in out salt pillar and are hashing the user passwords with `openssl passwd -6`.

when not setting `hash_password` to any value the login password is set to the password hash.

when setting `hash_password: False` users can log in with their respective passwords.

**Comment by leonardp** [comment]
okay. after digging through our salt states with grep i found that we have a .yml witch overrides the defaults for the user
state and sets `hash_password: True`.

sorry for the noise!
