### ISSUE TITLE
[FEATURE REQUEST]  New restconf proxy/state/module to manage network devices via restconf

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#59006]
**Is your feature request related to a problem? Please describe.**
Modern network devices / appliances have a restconf interface. I want to be able to automate against these devices in a sane way

**Describe the solution you'd like**
Devices should show as minions (proxied in most cases) and have standard salt proxy methodologies like pillar etc for setting credentials

**Describe alternatives you've considered**
Using the existing http module, however it means having to write state files etc that are more complicated for assigning pillar information and states

**Additional context**
I have a PR open for this https://github.com/saltstack/salt/pull/58965

**Comment by dmurphy18** [comment]
PR still awaiting some resolution of comments
