### ISSUE TITLE
Replace cmd scripts with PowerShell scripts

### ISSUE THREAD

**Issue by Rockin2** [saltstack/salt#59027]
On Windows, there is multiple bat files for calling Salt. The escaping of double-quotes with the CMD shell is awkward when we use pillar dict with the Start-Process cmdlet.

Replacing these bat files with PowerShell scripts would be a good solution I think. PowerShell is better than CMD and the escaping of double-quotes is less awkward.

We have PowerShell scripts that calls salt-call.bat with Start-Process and we have to deal with two rules of escaping double-quotes in the same command.

Examples :

This works :
```
Start-Process -FilePath .\salt-call.bat -ArgumentList "state.apply doxygen ""pillar={'doxygen.version': '2.3.0'}"""
```

This doesn't works :
```
Start-Process -FilePath .\salt-call.bat -ArgumentList "state.apply doxygen ""pillar='{""doxygen.version"": ""2.3.0""}'"""
Start-Process -FilePath .\salt-call.bat -ArgumentList "state.apply doxygen pillar='{""doxygen.version"": ""2.3.0""}'"
```

More strange, if we put the string in a variable, its value will be ok but it will not work with the Start-Process cmdlet :
```
$test = "state.apply doxygen pillar='{""doxygen.version"": ""2.3.0""}'"
echo $test.
state.apply doxygen pillar='{"doxygen.version": "2.3.0"}'
```

**Comment by twangboy** [comment]
Those scripts are now binaries
