### ISSUE TITLE
[BUG] Add is_junos check around --proxyid check in cli daemons

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#59020]
**Description**
When the Juniper native minion code was merged into the master branch, the --proxyid check was removed since the Juniper native minion leverages the proxy code to communicate with the ncclient and in turn the Junos OS.  This code needs to be returned and bounded by is_junos platform check.

salt/cli/daemons.py
```diff
 --       if not self.values.proxyid:
--            self.error("salt-proxy requires --proxyid")
++        ## allow for native minion
```

see https://github.com/saltstack/salt/pull/58979

**Comment by dmurphy18** [comment]
seeing issue with current Juniper native minion based of Salt master using CI/CD
"""
    301 1970-01-01 02:15:28,554 [/var/db/scripts/jet/salt/proxy/ssh_sample.py:33  ][INFO    ][5798] ssh_sample proxy __virtual__() c
alled...
    302 1970-01-01 02:15:28,557 [salt.utils.lazy  :106 ][DEBUG   ][5798] Could not LazyLoad junos.initialized: 'junos' __virtual__ r
eturned False: Missing dependency: The junos proxy minion requires the 'jnpr' Python module.
    303 1970-01-01 02:15:28,558 [salt.loader      :864 ][CRITICAL][5798] Failed to load grains defined in grain file junos.facts in
function <function facts at 0x80fdc7e60>, error:
    304 Traceback (most recent call last):
    305   File "salt/loader.py", line 853, in grains
    306   File "/var/db/scripts/jet/salt/grains/junos.py", line 53, in facts
    307     if proxy is None or proxy["junos.initialized"]() is False:
    308   File "salt/loader.py", line 1283, in __getitem__
    309   File "salt/utils/lazy.py", line 108, in __getitem__
    310 KeyError: 'junos.initialized'
    311 1970-01-01 02:15:28,559 [salt.utils.lazy  :102 ][DEBUG   ][5798] LazyLoaded junos.grains
    312 1970-01-01 02:15:28,584 [junos_vmx17.salt.loaded.int.metaproxy.proxy:172 ][ERROR   ][5798] Proxymodule junos is missing an i
nit() or a shutdown() or both. Check your proxymodule.  Salt-proxy aborted.
"""

Need to check if missed a change in grains.

**Comment by s0undt3ch** [comment]
We will need to revert https://github.com/saltstack/salt/pull/59038 and this is fixed

**Comment by dmurphy18** [comment]
@s0undt3ch Working on this today, will remember #59038

**Comment by dmurphy18** [comment]
Also fixing issue in salt/modules/junos.py replacing recent is_junos() tests with is_proxy() but delayed by recent pip changes in testing.

```
diff --git a/salt/modules/junos.py b/salt/modules/junos.py
index 444889c2ef..73ab164bc1 100644
--- a/salt/modules/junos.py
+++ b/salt/modules/junos.py
@@ -1428,7 +1428,8 @@ def install_os(path=None, **kwargs):
                 ret["out"] = False
                 __proxy__["junos.reboot_clear"]()
                 return ret
-            if salt.utils.platform.is_junos():
+            ## DGM if salt.utils.platform.is_junos():
+            if not salt.utils.platform.is_proxy():
                 # If its native minion running on Junos, pyez dont need to SCP file
                 # hence setting no_copy as True, HandleFileCopy already copied file
                 # from master to Junos
@@ -1518,7 +1519,8 @@ def file_copy(src, dest):
 
         salt 'device_name' junos.file_copy /home/m2/info.txt info_copy.txt
     """
-    if salt.utils.platform.is_junos():
+    ## DGM if salt.utils.platform.is_junos():
+    if not salt.utils.platform.is_proxy():
         return {
             "success": False,
             "message": "This method is unsupported on the current operating system!",
@@ -2095,7 +2097,8 @@ def file_compare(file1, file2, **kwargs):
                 True
 
     """
-    if not salt.utils.platform.is_junos():
+    ## DGM if not salt.utils.platform.is_junos():
+    if salt.utils.platform.is_proxy():
         return {
             "success": False,
             "message": "This method is unsupported on the current operating system!",
@@ -2153,7 +2156,8 @@ def fsentry_exists(dir, **kwargs):
                 True
 
     """
-    if not salt.utils.platform.is_junos():
+    ## DGM if not salt.utils.platform.is_junos():
+    if salt.utils.platform.is_proxy():
         return {
             "success": False,
             "message": "This method is unsupported on the current operating system!",
@@ -2302,7 +2306,8 @@ def dir_copy(source, dest, force=False, **kwargs):
     `re1:/etc/salt/pki/<files and dirs in /etc/salt/pki`.
 
     """
-    if not salt.utils.platform.is_junos():
+    ## DGM if not salt.utils.platform.is_junos():
+    if salt.utils.platform.is_proxy():
         return {
             "success": False,
             "message": "This method is unsupported on the current operating system!",

```
