### ISSUE TITLE
Can you please help me if there is an option to pass the parameter while we install the package using salt-master.

### ISSUE THREAD

**Issue by Anilkris07** [saltstack/salt#59025]
**Description**
Hi,
I was working on the RHEL8 to install the Docker on the system,
as per the suggestion from RHEL8 
* https://linuxconfig.org/how-to-install-docker-in-rhel-8
 * https://computingforgeeks.com/install-docker-and-docker-compose-on-rhel-8-centos-8/

we need to use the option --allowerasing to remove the default docker (Podman) and install a docker on RHEL8.
(yum install docker-ce --allowerasing)
i used couple of options 
EG: 
- args: '--allowerasing' 
- opts: '--allowerasing'

And this is my salt code snippet to install the package.
```
docker repo:
  pkgrepo.managed:
    - name: rhel-8-server-extras-rpms
    - disabled: False
  file.managed:
    - name: /etc/yum.repos.d/docker-ce.repo
    - source: https://download.docker.com/linux/centos/docker-ce.repo
    - skip_verify: True

install docker:
  pkg.installed:
    - names:
      - docker-ce
	- args: '--allowerasing'
    - reload_modules: true
```
Any help on this would be great. !

**Suggested Fix**
What did you expect to see in the documentation that is missing or needs updating?

**Type of documentation**
This could be Salt documentation, Salt modules, the Salt Repo or the Getting Started guide.

**Location or format of documentation**
Insert page URL if applicable.

**Additional context**

**Comment by garethgreenaway** [comment]
@Anilkris07 Thanks for the question.  I believe what you want to use is the option `setopt` in the install function of the yumpkg module, so your updated state would look like this:
```
docker repo:
  pkgrepo.managed:
    - name: rhel-8-server-extras-rpms
    - disabled: False
  file.managed:
    - name: /etc/yum.repos.d/docker-ce.repo
    - source: https://download.docker.com/linux/centos/docker-ce.repo
    - skip_verify: True

install docker:
  pkg.installed:
    - names:
      - docker-ce
	- setopt: 'allowerasing'
    - reload_modules: true
 ```

**Comment by whytewolf** [comment]
as we have not heard back and it has been way more than a week. going a head and closing this issue.
