### ISSUE TITLE
[DOCS] quotes, colons and backslashes in salt.states.reg

### ISSUE THREAD

**Issue by marbx** [saltstack/salt#59055]
**Description**
- **Using single backslashes** is missing single backslashes
- **Using double backslashes** is missing double backslashes.
- **CLI Example** reg.absent is missing the colon, combines the wrong quotes and backslashes and isn't a CLI example

**Suggested Fix**
Add colons and backslashes, combine the correct quotes and backslashes 

**Type of documentation**
Salt documentation.

**Location or format of documentation**
https://docs.saltstack.com/en/master/ref/states/all/salt.states.reg.html

**Comment by s0undt3ch** [comment]
This will be addressed by https://github.com/saltstack/salt/pull/58539
