### ISSUE TITLE
[FEATURE REQUEST] proxmox cloud module: patch suggestion for possibility to set id of new vm/ct manually via yaml opt

### ISSUE THREAD

**Issue by exa-mk** [saltstack/salt#59057]
The proxmox cloud module (`salt/cloud/clouds/proxmox.py`) currently always generates the id of a new ct/vm. My patch solution would make it possible to set it to a manual value via the yaml opts:
```
<         newid = _get_next_vmid()
---
>         if 'vmid' in vm_:
>             newid = vm_['vmid']
>         else:
>             newid = _get_next_vmid()
```

**Comment by s0undt3ch** [comment]
How would it manage conflicts? Ie, the same ID is already in use?

**Comment by exa-mk** [comment]
UPDATE:

sorry, wasn't able to test my patch properly last week. it appears to fail because of the missing `_get_next_vmid()` the connection isn't authenticated and will drop.
new and tested part of the function:
```
[...]
    try:
        newid = _get_next_vmid()

        if 'vmid' in vm_:
            newid = int(vm_['vmid'])

        data = create_node(vm_, newid)
    except Exception as exc:
[...]
```

@s0undt3ch : if the ID is already in use, proxmox will throw an error and abort:
```
The following exception was thrown when trying to run the initial deployment: 
500 Server Error: CT 6051 already exists on node 'coreng09'
```

**Comment by nicholasmhughes** [comment]
moving to https://github.com/salt-extensions/saltext-proxmox/issues/10
