### ISSUE TITLE
[DOCS] How to Auto-Update salt-minion on Ubuntu 18.04 LTS (arm64)

### ISSUE THREAD

**Issue by sjkummer** [saltstack/salt#59076]
**Description**
As a saltstack user, I want to make sure all software (including the minion) is up-to-date. This is crucial regarding security. The documentation is not clear about how to achieve that on linux based minions.

An `apt-get install salt-minion` on Ubuntu 18.04 LTS only installs version `2017.7.4` which is quite old (tested on Nvidia Jetson / aarch64).

The bootstrap script can install newer versions using git, but its not clear if this is recommended and which branch is meant to be "latest stable" and recommended for security.

**Suggested Fix**
The doc should describe how a secure setup including auto-updates should look like for salt-minions on Ubuntu. 

**Additional context**
Latest CVEs announcement: https://www.saltstack.com/blog/on-november-3-2020-saltstack-publicly-disclosed-three-new-cves/

**Comment by sjkummer** [comment]
According to the SaltStack SecOps documentation, it should be CIS-certified for Ubuntu 18.04 and "Automated IT Security Remediation" is very important:
https://get.saltstack.com/rs/304-PHQ-615/images/SaltStack_Protect_Solution_Brief.pdf
https://get.saltstack.com/rs/304-PHQ-615/images/SaltStack_Comply_Solution_Brief.pdf

Unfortunately, this ticket seems to have no priority, Therefore I wonder: Are this documents just marketing?

**Comment by VietTPham** [comment]
you might be using the minor, or major version instead of latest.
example below would be the newest version 
`deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/latest bionic main`
below is if you only want 3002
`deb http://repo.saltstack.com/py3/ubuntu/18.04/amd64/3002 bionic main`

**Comment by sjkummer** [comment]
Hi @VietTPham thanks for the Repo link. Since those only contain AMD 64bit, it becomes clear that ARM (64bit) is not actively maintained / supported.

Are there any plans to officially support ARM (64bit) machines in the future? (e.g. mobile devices, embedded devices, new ARM laptops etc.)

**Comment by javierchan** [comment]
Same thing here, ARM64 must be supported by salt repo's, not just for jetson also for unifi devices must be required.

**Comment by sagetherage** [comment]
@sjkummer @javierchan this topic is a bit beyond the scope of the ticket, but I will respond here: ARM64 packaging for Salt is something we have discussed, but isn't on the roadmap ATM and instead we have been going in a different direction with [Tiamat](https://gitlab.com/saltstack/pop/tiamat) and [single binary packages for Salt](https://gitlab.com/saltstack/open/salt-pkg); however, this is requested often and we can revisit the subject.

**Comment by sjkummer** [comment]
@sagetherage Thanks for your comment. I had a quick look at the README and this seems not to be ready for production:
> Tiamat-generated builds of `salt` are in **beta**, and are ready for testing.

What I am looking for is the officially recommended way to automatically update minions which are not AMD based. Why am I looking for this? To close upcoming vulnerabilities (CVEs) as fast as possible.

**Comment by sagetherage** [comment]
@sjkummer we have a few ways to do this, and I am sorry to say it depends on your set up: 

https://docs.saltproject.io/en/latest/faq.html#what-is-the-best-way-to-restart-a-salt-minion-daemon-using-salt-after-upgrade

and there is a cool tutorial using esky: https://docs.saltproject.io/en/master/topics/tutorials/esky.html

I am thinking this probably needs to be some where more visible to others, are you on the SaltStack Community Slack? IRC?

**Comment by sjkummer** [comment]
@sagetherage Thanks for these links. This sounds very promising. I wonder if I can provide a ARM64 build environment using docker and QEMU.

>> are you on the SaltStack Community Slack? IRC?
Not yet.

**Comment by bryceml** [comment]
See also https://github.com/saltstack/salt/issues/59086

**Comment by bryceml** [comment]
3004rc1, 3004, and going forward will support arm64 on ubuntu 20.04.

@saltstack/team-core still needs to discuss whether we are going to support ubuntu 18.04 with arm64 versions or not.

**Comment by defanator** [comment]
I'd vote for adding arm64 support for Ubuntu 18.04 and Debian 10/11 as well. It would greatly improve overall experience of using salt as a management layer for infrastructure of various package builders (short-live VMs). So far we have to do a number of manual actions while spinning up arm builders. Out-of-the-box support would be much easier solution.

**Comment by krionbsd** [comment]
We already provide arm64 support for Ubuntu 20 and Debian 11, there are no plans to provide Ubuntu 18 arm64 packages
