### ISSUE TITLE
Make the Salt loader more Pythonic

### ISSUE THREAD

**Issue by madduck** [saltstack/salt#5908]
The current way Salt loads modules is a wrapper around Python module loading, which adds some flexibility and features, but also comes with some shortcomings.

Because the loader injects global variables like `__salt__` only into functions it loads, these variables are not accessible at the module level. Furthermore, the loader hard-codes states to have two components, like `file.managed`, and it's not possible to extends this, e.g. `file.managed.template`, which is what people used to Python might assume.

If the Salt loader were based on Python's `import`, then these limitations could go away. States would derive from a base state class, which would give access to global variables, and collect common functionality (e.g. permissions settings on files, or templating, or process control).

It would also become possible to reuse functionality by importing e.g. `file.managed` directly into a new state, rather than having to call a state via `__salt__`.

This issue exists to track progress and collect ideas.

**Comment by steverweber** [comment]
i think this was merged. . done?

**Comment by madduck** [comment]
Really? Where/when?

**Comment by thedrow** [comment]
I have to say that this sounds like a very good idea.
@steverweber I don't think anything happened in that direction.

**Comment by steverweber** [comment]
opps sorry mistake.

**Comment by UtahDave** [comment]
At this point I don't think such a major change to the loader is feasible. Closing for now. Please comment here if someone wishes to begin working on this.
