### ISSUE TITLE
[BUG] Fresh install pillar render errors.

### ISSUE THREAD

**Issue by Dodely** [saltstack/salt#59097]
**Description**
I encountered this error during a fresh installation, after restarting the master node before starting DeepSea Stage 0. I attempted to restart all nodes and the physical boxes, but the error is persistent. I am following OpenSuse's recommended installation guide. 
```
# systemctl status salt-master.service
Dec 07 12:49:42 node0 salt-master[13591]:     'pillar': partial(salt.utils.traverse_dict_and_list, pillar),
Dec 07 12:49:42 node0 salt-master[13591]: [CRITICAL] Pillar render error: Failed to load ext_pillar stack: module 'salt.utils' has no attribute 'traverse_dict_and_list'
Dec 07 12:49:44 node0 salt-master[13591]: [ERROR   ] Exception caught loading ext_pillar 'stack':
Dec 07 12:49:44 node0 salt-master[13591]:   File "/usr/lib/python3.6/site-packages/salt/pillar/__init__.py", line 982, in ext_pillar
Dec 07 12:49:44 node0 salt-master[13591]:     key)
Dec 07 12:49:44 node0 salt-master[13591]:   File "/usr/lib/python3.6/site-packages/salt/pillar/__init__.py", line 910, in _external_pillar_data
Dec 07 12:49:44 node0 salt-master[13591]:     *val)
Dec 07 12:49:44 node0 salt-master[13591]:   File "/srv/modules/pillar/stack.py", line 384, in ext_pillar
Dec 07 12:49:44 node0 salt-master[13591]:     'pillar': partial(salt.utils.traverse_dict_and_list, pillar),
Dec 07 12:49:44 node0 salt-master[13591]: [CRITICAL] Pillar render error: Failed to load ext_pillar stack: module 'salt.utils' has no attribute 'traverse_dict_and_list'
```

**Versions Report**
```
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.11.2
       cherrypy: unknown
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.26.8
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.17
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: 0.26.0
         Python: 3.6.12 (default, Dec 02 2020, 09:44:23) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.3

System Versions:
           dist:
         locale: UTF-8
        machine: x86_64
        release: 4.12.14-lp151.28.87-default
         system: Linux
        version: Not Installed

```
Running  on openSUSE Leap 15.1

**Comment by krionbsd** [comment]
@Dodely are you sure you don't have any stale files from previous salt installations? Could you try 3002 in the meantime, you might the packages [here](https://repo.saltstack.com/index.html#suse)

**Comment by Dodely** [comment]
I forgot to post an update a few months ago. After re-encountering this error, I found a fix.
I appended .data to the following lines located in /srv/modules/pillar/stack.py:384, as per https://docs.saltstack.com/en/3000/topics/releases/3000.html recommendations.
`	
#I changed this
	traverse = {
        'pillar': partial(salt.utils.traverse_dict_and_list, pillar),           
        'grains': partial(salt.utils.traverse_dict_and_list, __grains__),
        'opts': partial(salt.utils.traverse_dict_and_list, __opts__),
        }

#to this
    traverse = {
        'pillar': partial(salt.utils.data.traverse_dict_and_list, pillar),           
        'grains': partial(salt.utils.data.traverse_dict_and_list, __grains__),
        'opts': partial(salt.utils.data.traverse_dict_and_list, __opts__),
        }
'
