### ISSUE TITLE
[Question] stack install command with salt

### ISSUE THREAD

**Issue by hongyi-zhao** [saltstack/salt#59094]
I'm still confused on the relationship between stack and salt. Say, I can use `stack install` command to install some packges developed by Haskell. Can I also do this job with salt?

Regards,
HY

**Comment by OrangeDog** [comment]
SaltStack has nothing to do with the `stack` command. It's just a widely-used [computing term](https://en.wikipedia.org/wiki/Stack#Computing).

You can indeed use `salt` to install Haskell packages, with the [`cabal.installed` state](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cabal.html), or by [directly calling commands](https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cmd.html).

**Comment by hongyi-zhao** [comment]
Based on my current understanding, it seems that the SaltStack is similar to [ansible](https://www.ansible.com/). Am I right?

**Comment by OrangeDog** [comment]
It's closer to puppet, but yes it's a configuration management system.

**Comment by sagetherage** [comment]
@OrangeDog thank you!!! @hongyi-zhao please let us know if you more questions, these can be answered on IRC or you can join the our Salt Community Slack here saltstackcommunity.slack.com

**Comment by hongyi-zhao** [comment]
Got it. Thanks a lot. @sagetherage
