### ISSUE TITLE
[DOCS]|[BUG] schedule argument outlined in docs but has no feedback in practice

### ISSUE THREAD

**Issue by alan-cugler** [saltstack/salt#59102]
**Description**
When looking at documentation for the schedule state module, there is an option `persist` to have a job continue across minion restarts. The documentation says this is defaulted to `True`. The schedule execution module has no mention of this option, nor when you run a `salt \* schedule.list` is there any feedback on the status of this option for any currently scheduled jobs.

If I explicitly add it to a schedule state, then subsequently run the state, there is no feedback or status of the `persist` option.
```YAML
schedule_test:
  schedule.present:
    - function: cmd.run
      - args: '['sleep 30; echo hello']"
    - minutes: 10
    - persist: False
    - run_on_start: True
    - maxrunning: 1
    - jid_include: True
```
```BASH
$ salt salt_test_minion schedule.list
salt_test_minion:
    schedule:
      schedule_test:
        args:
        - sleep 30; echo hello
        enabled: true
        function: cmd.run
        jid_include: true
        maxrunning: 1
        name: schedule_test
```
Going a step further, if I add a new schedule via command line with the `persist` option included, there is still no feedback.
```BASH
$ salt salt_test_minion schedule.add schedule_test function='cmd.run' return_job=True maxrunning=100 job_args="['sleep 30; echo hello']" seconds=30 persist=True
salt_test_minion:
    ----------
    comment:
        Added job: schedule_test to schedule.
    result:
        True

$ salt local schedule.list
salt_test_minion:
    schedule:
      enabled: true
      schedule_test:
        args:
        - sleep 30; echo hello
        enabled: true
        function: cmd.run
        jid_include: true
        maxrunning: 100
        name: test_job
        return_job: true
        seconds: 30
```
Finally, if I modify the same above schedule that had `persist=True` set and explicitly only change that option to `persist=False`, the salt feedback only says the job is in the correct state. Which implies the persist function *isn't* recognized by salt at all.
```BASH
$ salt salt_test_minion schedule.modify schedule_test function='cmd.run' return_job=True maxrunning=100 job_args="['sleep 30; echo hello']" seconds=30 persist=False
salt_test_minion:
    ----------
    changes:
        ----------
    comment:
        Job schedule_test in correct state
    result:
        True
```

** Resources **
- https://docs.saltstack.com/en/latest/ref/states/all/salt.states.schedule.html#salt.states.schedule.present
- https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.schedule.html

** Final Thoughts **
- Clarification is needed to what a "persistent job across minion restarts" means?
- Does the `persist` option work or is it an artifact of past iterations of salt?
  - If it does work then why is there no feedback displayed in `schedule.list` return?
  - If it does work (x2), why can't I exclusively flip this boolean option on a scheduled job?

**Comment by alan-cugler** [comment]
Read over my issue and refactored some of my description for easier comprehension. Let me know if anything is unclear or needs follow up from me.

**Comment by OrangeDog** [comment]
> Clarification is needed to what a "persistent job across minion restarts" means?

Whether the job is written to `/etc/salt/minion.d/_schedule.conf` or only remains in memory.

> Does the persist option work?

I think so, but there might be a corner case if you add it with `persist=False` and subsequently run `schedule.save`.

**Comment by alan-cugler** [comment]
Alright, so further testing and conversation with others has resulted in the following observations.

![image](https://user-images.githubusercontent.com/25991646/101814239-79c6f000-3ae3-11eb-8f48-127ef9b8a036.png)
1. ^ This means the schedule that is currently enabled on the minion will be setup and enabled again after a minion has been restarted. This is not restricted to the schedule being in the `/etc/salt/minion.d/` directory, I also added schedules with persistence via terminal and state.

2. The `persist` option does work. I tested with true-positive and true-negative tests.
***

So this is what remediation steps that should take place:
- The persist **documentation** should explain this is schedule being present and enabled again after restarting a minion.
- The `persist` option should be **refactored** to be made viewable when you run `schedule.list`.
- Salt should be **refactored** to accept a schedule update where only the `persist` option is being flipped.

**Comment by OrangeDog** [comment]
> schedule being present and enabled again after restarting a minion

That's what "persist between minion restarts" means.

> This is not restricted to the schedule being in the /etc/salt/minion.d/ directory

How else is it being persisted? When you use the state or module functions they write to that file.

**Comment by garethgreenaway** [comment]
@alan-cugler The `persist` option is available when adding jobs to the schedule using the execution module, the module doesn't have all the options documented as it's more common to use the state module to manage the schedule.  We also don't indicate when a job is being persisted when using either the state module or the execution module, but that would be a pretty easy fix to add.  I'm also curious how you envision `schedule.list` being refactored to show jobs that are persistent, currently that functions show the jobs in the running minion.

**Comment by OrangeDog** [comment]
I think all that needs to happen is to persist (and read-back) the persist argument. Then when it's missing you know it's not a persistent job.

With some handling of old jobs that were persisted without it.

**Comment by alan-cugler** [comment]
so one change needed is where, `persist' is a documented option we need to clarify:
```
# currently what's in the docs

Whether the job should persist between minion restarts, defaults to True.
```
Is saying the **schedule** on the minion will persist between minion restarts, not a **job** triggered by a minion schedule will persist between minion restarts. 

I think my misunderstanding here in these docs, is caused by the overloaded term "job." It's meant to say the job is equivalent a schedule on a minion. I had taken it to mean the job triggered by a schedule on the minion.

**Comment by alan-cugler** [comment]
Secondly, @OrangeDog I am not sure if I am missing some documentation somewhere, (please link me the docs if so) but when you said:
![image](https://user-images.githubusercontent.com/25991646/103314511-f5cc9d80-49e8-11eb-9178-f8acc5d63895.png)
I thought you were saying when a schedule was explicitly added to that file by a user.
***
But you clarified here:
![image](https://user-images.githubusercontent.com/25991646/103314580-290f2c80-49e9-11eb-932a-84378fe2313e.png)
that you meant adding the schedule by any of the salt supported methods of creating a schedule.

So do we already have how the schedule system works somewhere for users to see, not just how to use it? If not then I think the @saltstack/docs-working-group will probably need to add an explanation somewhere like [here](https://docs.saltstack.com/en/latest/topics/jobs/#scheduling-jobs).

**Comment by alan-cugler** [comment]
@garethgreenaway is there a place we explicitly have salt scheduler set the `persist` option for the minion? Is that always showing up in `/etc/salt/minion.d/_schedule.conf` for example? I am looking at the schedule.py module, but it looks like its just asking the event bus when you run `schedule.list` so I gotta dig deeper where the utils module called is getting the schedule information.
