### ISSUE TITLE
[DOCS] Python 2 Deprecation FAQ is showing twice on the right navigation

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59117]
**Description**
Python 2 Deprecation FAQ is showing twice on the right navigation
![Screen Shot 2020-12-10 at 11 53 42 AM](https://user-images.githubusercontent.com/36676171/101823342-76ca0080-3adf-11eb-9d8a-6ae873a6250c.png)

**Suggested Fix**
Is this a duplicate on the index and then it is also pulling it into view from the .rst file? Unsure, but it looks incorrect.

**Type of documentation**
Developing Salt

**Location or format of documentation**
https://github.com/saltstack/salt/edit/master/doc/topics/development/index.rst

**Additional context**

**Comment by vmdhhh** [comment]
@sagetherage I think this issue is due to `\doc\topics\development\index.rst` as first it loads all the documents with the help of `*` and then at the end again trying to load `faq-py2-deprecation` hence the duplicate.
I will remove the `faq-py2-deprecation` from the end and create a PR if its ok.

**Comment by vmdhhh** [comment]
I have created a PR. As the doc edit does not require tests, will you @sagetherage please add a proper tag?
