### ISSUE TITLE
[Question] How to create user in saltstack to use api? 

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#59132]
We trying to use the salt api for the action to our custom portal.  How to create user for salt to use the api? Without proper username and password, we are getting unauthorised error while POST api.

our id ist showing <body>
HTTP/1.1 401 Unauthorized
Content-Type: text/html;charset=utf-8
Server: CherryPy/18.6.0
Date: Mon, 14 Dec 2020 09:55:37 GMT
Allow: GET, HEAD, POST
Access-Control-Allow-Origin: *
Access-Control-Expose-Headers: GET, POST
Access-Control-Allow-Credentials: true
Vary: Accept-Encoding
Content-Length: 761
Set-Cookie: session_id=ab0c95c859abefa2cd3a0207aeadc95062bc9934; expires=Mon, 14 Dec 2020 19:55:37 GMT; Max-Age=36000; Path=/

<!DOCTYPE html PUBLIC
"-//W3C//DTD XHTML 1.0 Transitional//EN"
"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8"></meta>
    <title>401 Unauthorized</title>
    <style type="text/css">
    #powered_by {
        margin-top: 20px;
        border-top: 2px solid black;
        font-style: italic;
    }

    #traceback {
        color: red;
    }
    </style>
</head>
    <body>
        <h2>401 Unauthorized</h2>
        <p>Could not authenticate using provided credentials</p>
        <pre id="traceback"></pre>
    <div id="powered_by">
      <span>
        Powered by <a href="http://www.cherrypy.org">CherryPy 18.6.0</a>
      </span>
    </div>
    </body>
</html>

Could anyone help how we can create user in salt master with sufficient privilege.

**Comment by sagetherage** [comment]
@sooraj2589 see if either of these docs help with your question:
https://docs.saltstack.com/en/latest/topics/eauth/index.html
https://docs.saltstack.com/en/master/topics/eauth/access_control.html

Please mention me with a comment if this helps, if you have more questions, or something else.

**Comment by sooraj2589** [comment]
@sagetherage is the unix account we need to create? that means os level user?

could you please advise?

**Comment by sagetherage** [comment]
@sooraj2589 apologies I have missed this, I am working to get you an engineer to help answer your questions.

**Comment by garethgreenaway** [comment]
@sooraj2589 Creating the user depends on what authentication backend you're using.  You can have Salt use local unix accounts for authentication if you're using the `pam` for external authentication.  The links that @sagetherage provided include information on setting that up.

**Comment by sagetherage** [comment]
@sooraj2589 please let us know if this answers your questions
