### ISSUE TITLE
[FEATURE REQUEST] rh_ip module support interface channels management

### ISSUE THREAD

**Issue by msciciel** [saltstack/salt#59147]
**Is your feature request related to a problem? Please describe.**
On some systems it is useful to manually control network interface channels in order to achieve proper performance.

**Describe the solution you'd like**
Introduce ability to control network interface channels using rh_ip module and network.managed state.

**Describe alternatives you've considered**
Extend ethtool module and state to allow it but it's hard because python ethtool module lacks support for it.

**Comment by sagetherage** [comment]
@msciciel thank you for submitting a PR with this issue, our documentation does mention `develop` branch, but please point your PR to the `master` branch. Thank you!

**Comment by msciciel** [comment]
@sagetherage branch changed.

**Comment by sagetherage** [comment]
@msciciel thank you! The Core Team will likely not review the PR until it is out of a draft state, but I realize that can be a chicken and egg scenario. Are you looking to have someone review and give feedback?

**Comment by msciciel** [comment]
@sagetherage may I ask for some hint? I've changed my code to disappear from diff in Pre-Commit / Run Pre-Commit Against Salt (pull_request) test but it still fails and I have no clue why. I've resolved Draft state.

**Comment by sagetherage** [comment]
@msciciel looking good! I will check back as this is looking like it will get merged soon, thank you!
