### ISSUE TITLE
Integrate salt-key with iptables for better security

### ISSUE THREAD

**Issue by avimar** [saltstack/salt#5916]
Due to general security concerns and the large potential impact of a breach, aggressive firewall strategies are recommended.

For environments that have static IPs:
Leave ports 4505,4506 closed. Using something like salt-key for salt to maintain the list of IPs it expects to have communication from? salt-key --add-ip X and that will run iptables state (this is a config management system, already...) to make sure that IP can use the ports. Removing the key would remote that iptables rule.

If there are some dynamic minions:
Is there a way to have a port open for minions to check in with their key (maybe only ones that are marked allowed to be dynamic) and then salt will add that IP to the firewall, until it times out or reconnect from a new IP and then it will remove the old firewall hole.
This can perhaps be done on ret_port without using a new port, but I'm unaware of the security implications of this.

**Comment by basepi** [comment]
I agree with @holmboe here. This would be very hard to integrate with salt's "minion reaches out to master" architecture. It can obviously be done in addition to salt if minion IPs are added to iptables as they are created. But I'm not sure this fits as a core feature in salt.

If someone still feels strongly about this I'm happy to discuss it more. We're just going through old issues and re-evaluating.
