### ISSUE TITLE
3002.6 regression salt minion broken in CentOS Stream

### ISSUE THREAD

**Issue by ekillian** [saltstack/salt#59161]
### Description of Issue
When I run a previously working sls file on a system that was CentOS 8 which I upgraded to CentOS Stream, I get error messages. I made a simple vim install sls for a test. The error is (yes, the minion name is CentSO8):

CentSO8:
----------
          ID: vim
    Function: pkg.installed
        Name: vim-enhanced
      Result: False
     Comment: State 'pkg.installed' was not found in SLS 'vim_test'
              Reason: 'pkg' __virtual__ returned False: pkg module could not be loaded
     Changes: 

### Setup
sls file contains:

vim:
  pkg:
    - installed
{% if 'CentOS' in grains['os'] %}
    - name: vim-enhanced
{% else %}
    - name: vim
{% endif %}

### Steps to Reproduce Issue
Created test sls file named vim_test and then ran

salt <minion_name> state.sls vim_test

### Versions Report
CentSO8:
    Salt Version:
              Salt: 3002.2
     
    Dependency Versions:
              cffi: 1.11.5
          cherrypy: Not Installed
          dateutil: 2.6.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: 0.35.2
              Mako: Not Installed
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.14
          pycrypto: Not Installed
      pycryptodome: Not Installed
            pygit2: Not Installed
            Python: 3.6.8 (default, Dec  3 2020, 18:11:24)
      python-gnupg: Not Installed
            PyYAML: 3.12
             PyZMQ: 19.0.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.3
     
    System Versions:
              dist: centos 8 
            locale: UTF-8
           machine: x86_64
           release: 4.18.0-257.el8.x86_64
            system: Linux
           version: CentOS Stream 8

**Comment by krionbsd** [comment]
Fixed by 59201 PR

**Comment by ekillian** [comment]
Why is my bug being highjacked? And my bug was fixed.

**Comment by sagetherage** [comment]
seeing this again in 3002.6 reopening for Silicon release

**Comment by ScriptAutomate** [comment]
Related: https://github.com/saltstack/salt/issues/59061

**Comment by sagetherage** [comment]
I am wrong. It was ONLY FIXED in 3003 and not before. Closing, apologies for my mistake.
