### ISSUE TITLE
[FEATURE REQUEST] add content directly from cron.file

### ISSUE THREAD

**Issue by kaushiksachin** [saltstack/salt#59210]
instead of mentioning source or template file can we add content directly something like :  

/etc/cron.d/test:
  cron.file:
    - identifier: "salt-call-run"
    - user: root
    - minute: '*/30'
    - content: "/bin/my-script.sh"
    
   Reason I am asking is cron.present put directly content inside crontab -e . but if I need a file inside /etc/cron.d/ there is no way I can specify content directly . I have top use source file for cron.file. Since usually it's a one liner. I hate to create a special file for single line .

**Comment by max-arnold** [comment]
Have you considered using something like this?

```yaml
/etc/cron.d/test:
  file.managed:
    - contents:
      - "*/30 * * * *   root    salt-call state.apply STATE"

**Comment by sagetherage** [comment]
@kaushiksachin have you tried using state.apply as Max suggested?

**Comment by sagetherage** [comment]
@kaushiksachin I am going to close this issue, please let us know if this persists by mentioning me in the comments and I can re-open the issue if so.
