### ISSUE TITLE
[BUG] curl command to target multiple minions

### ISSUE THREAD

**Issue by uvardan** [saltstack/salt#59220]
I am having issue targeting multiple minions using the curl command. 

My command looks as follows:

curl -b "cookies.txt" \
 -ssk "https://cud1.com:8000 \
-H 'Accept: application/x-yaml' \
-d client='local' \
-d tgt='minion1','minion2' \
-d fun="test.ping" \
-d expr_form='list'

I also tried to run using tgt-type='list' instead of expr_form however I didnt succeed
output:
return:
-{}

Note: When I run the same command on single 'minion1" it retuns success
return:
- minion1: true

**Comment by garethgreenaway** [comment]
@uvardan It looks like there might be a couple typos in your CURL command when specifying the minions to be targeted.  Can you update it to the following:
```
curl -b "cookies.txt"
-ssk "https://cud1.com:8000
-H 'Accept: application/x-yaml'
-d client='local'
-d tgt='minion1,minion2'
-d fun="test.ping"
-d tgt_type='list'
```
The expr_form argument was renamed to tgt_type in 2017.7.x release.

**Comment by uvardan** [comment]
@garethgreenaway : Thank you, It worked. I will close this issue.
Another quesiton, By adding the tag_type are we running the function test.ping asynchronously or is it similar to a for loop?
