### ISSUE TITLE
[BUG] Issue w/ adding config to Cisco Routers GNS3

### ISSUE THREAD

**Issue by macejko8** [saltstack/salt#59254]
**Description**
I have an issue with adding config using Salt to my cisco routers 7200 in GNS3.

**Setup**
I am using this command to do it               sudo salt router2 net.load_config text='ntp server 1.1.1.1'

**Steps to Reproduce the behavior**
And getting this error:  Cannot execute "compare_config" on 10.0.1.6 as matej. Reason: Netmiko _autodetect_fs failed (to workaround specify dest_file_system in optional_args.)!

So, please if someone would know where exactly dest_file_system arg should be added and what value should it have. I have tried to specify it in pillar file with values flash, flash0, disk0, ios, nvram but none of them worked.

**Comment by mirceaulinic** [comment]
@macejko8 this sounds like a NAPALM usage issue. Make sure you're using the latest NAPALM release and you've read the IOS prerequisites: https://napalm.readthedocs.io/en/latest/support/ios.html and the FAQ: https://github.com/napalm-automation/napalm#faq.
You probably just have to set the `dest_file_system` optional argument, see https://napalm.readthedocs.io/en/latest/support/index.html#list-of-supported-optional-arguments.
If you still have troubles, feel free to open an issue at https://github.com/napalm-automation/napalm/issues.

**Comment by macejko8** [comment]
@mirceaulinic thanks. previous error was fixed by setting dest_file_system to 'flash:'.....but now I am getting the different error while trying to use the same command as before

Here is the error:

router1:
    ----------
    already_configured:
        False
    comment:
        Cannot execute "load_merge_candidate" on 10.0.1.5 as matej. Reason: 'NoneType' object has no attribute 'group'!
        Configuration discarded.
    diff:
        +Error: Could not open file flash:/merge_config.txt for reading
    loaded_config:
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "/usr/lib/python3/dist-packages/salt/utils/napalm.py", line 167, in call
            out = getattr(napalm_device.get('DRIVER'), method)(*args, **kwargs)
          File "/home/matej/.local/lib/python3.6/site-packages/napalm/ios/ios.py", line 320, in load_merge_candidate
            file_system=self.dest_file_system,
          File "/home/matej/.local/lib/python3.6/site-packages/napalm/ios/ios.py", line 271, in _load_candidate_wrapper
            source_file=tmp_file, dest_file=dest_file, file_system=file_system
          File "/home/matej/.local/lib/python3.6/site-packages/napalm/ios/ios.py", line 626, in _scp_file
            TransferClass=FileTransfer,
          File "/home/matej/.local/lib/python3.6/site-packages/napalm/ios/ios.py", line 678, in _xfer_file
            if not transfer.verify_space_available():
          File "/home/matej/.local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 199, in verify_space_available
            space_avail = self.remote_space_available(search_pattern=search_pattern)
          File "/home/matej/.local/lib/python3.6/site-packages/netmiko/scp_handler.py", line 143, in remote_space_available
            if "kbytes" in match.group(0) or "Kbytes" in match.group(0):
        AttributeError: 'NoneType' object has no attribute 'group'
ERROR: Minions returned with non-zero exit code

**Comment by network-shark** [comment]
@macejko8 @mirceaulinic This is not a salt issue this is related to the 7200 images you are using. You need a correct one where the napalm can store the config in the flash before it can be applied. 

To verify that I am correct , can you run the "dir" command. Normally it should return the flash , but on some 7200 images it is broken and it does not return the expected string 

```
7897796608 bytes total (7036633088 bytes free)
```

Not sure if this makes sense to add the napalm FAQ, but it took me some hours to tshoot this.

**Comment by macejko8** [comment]
@network-shark yes you are right the dir command is not working on my image

Isn't there a chance that you have the "correct" 7200 image and you can share it with me?

Thanks

**Comment by network-shark** [comment]
I gave up on the 7200 router , because after fixing this I got other problems, but I don't remember them.

Not sure if the 7200 is the right choice . 

According to this thread: 

http://forum.gns3.net/topic6103.html

Version 15.1(4)M2 should be ok .

**Comment by mirceaulinic** [comment]
On Sat, 16 Jan 2021, 10:38 network-shark, <notifications@github.com> wrote:

> @macejko8 <https://github.com/macejko8> @mirceaulinic
> <https://github.com/mirceaulinic> This is not a salt issue this is
> related to the 7200 images you are using. You need a correct one where the
> napalm can store the config in the flash before it can be applied.
>
> To verify that I am correct , can you run the "dir" command. Normally it
> should return the flash , but on some 7200 images it is broken and it does
> not return the expected string
>
> 7897796608 bytes total (7036633088 bytes free)
>
> Not sure if this makes sense to add the napalm FAQ, but it took me some
> hours to tshoot this.
>
I think it'd totally make sense to add this to the IOS caveats document (
https://napalm.readthedocs.io/en/latest/support/ios.html). Perhaps as a
note under the Prerequisites section?

**Comment by network-shark** [comment]
Sounds good. Can create a PR . Can you confirm  the image is working ? @macejko8

**Comment by macejko8** [comment]
@network-shark I have tried to found the same image but no luck yet......I have tried about 6-7 different C7200 images but none of them were working

**Comment by network-shark** [comment]
None of them have a working flash ?

**Comment by macejko8** [comment]
no

**Comment by dmurphy18** [comment]
@macejko8 Closing this since not related to Salt.  Please reopen if there is a Salt related issue here, but it appears to be related to Cisco 7200 and its versions of software supported.
