### ISSUE TITLE
[BUG] search _find_crypto needs to be updated to allow for tiamat based salt-minion

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#59256]
**Description**
With tiamat based salt-minion's, the new path /opt/saltstack/salt is being adopted and as such additional search paths should also be considered.  For example:

"""
        lib = ctypes.util.find_library("crypto")
        if not lib:
            if salt.utils.platform.is_sunos():
                # Solaris-like distribution that use pkgsrc have libraries
                # in a non standard location.
                # (SmartOS, OmniOS, OpenIndiana, ...)
                # This could be /opt/tools/lib (Global Zone) or
                # /opt/local/lib (non-Global Zone), thus the two checks
                # below
                lib = glob.glob("/opt/local/lib/libcrypto.so*")
                lib = lib or glob.glob("/opt/tools/lib/libcrypto.so*")
                lib = lib[0] if lib else None
            elif salt.utils.platform.is_aix():
                if os.path.isdir("/opt/salt/lib"):
                    # preference for Salt installed fileset
                    lib = glob.glob("/opt/salt/lib/libcrypto.so*")
                else:
                    lib = glob.glob("/opt/freeware/lib/libcrypto.so*")
                lib = lib[0] if lib else None
"""

The new AIX library search path changes from /opt/salt/lib to /opt/saltstack/salt/run/libcrypto.so*
Similarly with Solaris and most likely regular Linux distributions, for example: Redhat / Centos 7 still utilizes OpenSSL 1.0.2 which End of Lifed Dec 31, 2019 and support for it is now being dropped by items such as python-cryptography (3.2 which also contains a CVE fix).  Which implies the need for updated OpenSSL installed not by the platforms packages, and hence in other than platform locations, such as, /usr/local/lib, /usr/local/openssl/lib, etc.

These new paths are in addition to regular paths provided by non-tiamat based  packaged salt-minions and other salt utilities.

**Additional context**
In addition this work will relate to FIPS compliance, given OpenSSL 1.0.2 is FIPS certified, but later versions are not.

**Comment by dmurphy18** [comment]
@s0undt3ch working a solution for this, done the Solaris and AIX parts, and moving on to the others, see https://github.com/dmurphy18/salt/tree/sol11_check

Since building Solaris 11 Py 3 minion, unit testing this at the moment

**Comment by s0undt3ch** [comment]
Looks good so far.

**Comment by dmurphy18** [comment]
Holding off on submitting it until further along in unit tests. Found a Python 3 bug in handling Solaris 11.4 in Python's Lib/ctypes/util.py that I need to inform Python about with fix.
