### ISSUE TITLE
[BUG] pillar.show_pillar for specific minion in orchestration also includes _master pillar

### ISSUE THREAD

**Issue by supfors** [saltstack/salt#59267]
**Description**
I'm looking up pillar data for specific minions from an orchestrate formula like this:

**myorch.sls**
```
{% set minion_pillar = salt.saltutil.runner('pillar.show_pillar', kwarg={'minion': 'mywindows1' }) %}
/tmp/mywindows1:
  file.managed:
    - contents: {{ minion_pillar.contacts }}
```

Pillar looks like this:
**top.sls**
```
base:
  'G@kernel:Windows':
    - windows
  'G@kernel:Linux':
    - linux
```
**windows.sls**
```
contacts:
  windows: [] 
```
**linux.sls**
```
contacts:
  linux: [] 
```

So, when running this orchestration, `/tmp/mywindows1` looks like this:
```
OrderedDict([('linux', []), ('windows', [])])
```

When I modify top.sls to:
```
base:
  'G@kernel:Windows':
    - windows
  'G@kernel:Linux and not localhost_master':
    - linux
```
(Where 'localhost_master' is the name of my salt-master), my file looks like this, which is how I expect it to be.

```
OrderedDict([('windows', [])])
```

So, is this a bug, or should I somehow be able to exclude _master results from my dict without explicitly excluding it in top.sls?
I do get the expected result when running from cli: 

```
salt-run pillar.show_pillar minion=mywindows1
contacts:
    ----------
    windows:
```

**Expected behavior**
`/tmp/mywindows1.` to not contain _master pillar data.

**Versions Report**
```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.3
      cherrypy: unknown
      dateutil: 2.4.2
     docker-py: 2.6.1
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: 1.1.0
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: 1.4.0
        Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1127.19.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

**Comment by garethgreenaway** [comment]
@supfors Thanks for the report.  One quick question, do you have a Salt minion running on your Salt master?

**Comment by supfors** [comment]
> @supfors Thanks for the report. One quick question, do you have a Salt minion running on your Salt master?
Yes, I have.

**Comment by garethgreenaway** [comment]
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.
