### ISSUE TITLE
[BUG] ensure proxy module for vcenter works in v6.7 vCenter

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59275]
**Description**
ensure proxy module for vcenter works in v6.7 and v7 vCenter to query data from and run automation actions in the scenarios listed below under requirements from PM 

**Expected behavior**
https://github.com/saltstack/salt/blob/develop/salt/proxy/vcenter.py functions in v6.7 of vCenter

Requirements from PM are in the internal ticketing system for VMware: https://jira.eng.vmware.com/browse/SSC-76

**Comment by waynew** [comment]
Closing this - it's basically referring to salt-ext-modules-vmware
