### ISSUE TITLE
[BUG] solarispkg.install only supports string "True" for current_zone_only kwarg

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#59305]
**Description**

The [`solarispkg.install`](https://docs.saltproject.io/en/master/ref/modules/all/salt.modules.solarispkg.html#salt.modules.solarispkg.install) function documents the use of `current_zone_only=True`, but in fact it only tests for the _string value_ `"True"`:

https://github.com/saltstack/salt/blob/20d5073a9186439b08f63e49b96c6d789ba6bda7/salt/modules/solarispkg.py#L359-L361

This should be a boolean test.

**Expected behavior**

`current_zone_only=True` should work.

**Versions Report**

This is a second-hand report against 3000.4, but it appears to still be an issue on `master`.

**Additional context**

ZD-6213.

**Comment by dmurphy18** [comment]
Currently there is a Python 3 version for Solaris 11 under development, and is functional.
Currently being integrated into SaltStack CI/CD pipelines.

This will be addressed as part of that development, since the current 3000.4 is based on Py 2 and support for Py 2 has been end-of-lifed.

**Comment by dmurphy18** [comment]
see https://gitlab.com/saltstack/enterprise/native-minion/-/issues/24

**Comment by dmurphy18** [comment]
NOTE: Solaris 10 issue
