### ISSUE TITLE
[BUG] zfs.filesystem_present fails on Solaris 10 (at least)

### ISSUE THREAD

**Issue by oeuftete** [saltstack/salt#59303]
**Description**

The `zfs.filesystem_present` state does not work on Solaris 10 (at least).  I don't have a traceback (reporting this second-hand), but the report I am working from suggests that the problem lies in https://github.com/saltstack/salt/blob/20d5073a9186439b08f63e49b96c6d789ba6bda7/salt/states/zfs.py#L436-L438.

The presence of the `type=dataset_type` `kwarg` there will ultimately cause `zfs get` to be called with `-t`, which does not appear to be a supported option: https://docs.oracle.com/cd/E26502_01/html/E29031/zfs-1m.html.  The original user reported being able to conditionally remove `type=dataset_type` for Solaris with success.

**Versions Report**

Reported against 3000.4, but this looks like it theoretically would be a problem with the current `master` code.

**Additional context**

ZD-6213.

**Comment by dmurphy18** [comment]
Currently there is a Python 3 version for Solaris 10 under development
This will be addressed as part of that development, since the current 3000.4 is based on Py 2 and support for Py 2 has been end-of-lifed.

**Comment by dmurphy18** [comment]
The lines https://github.com/saltstack/salt/blob/master/salt/modules/zfs.py#L1138-L1139 are incorrect, there is no '-t type' option with zfs.get command in Solaris 10 and 11.  

Only the following zfs commands:
- list
- userspace
- groupspace

Take a '-t type' parameter, zfs get does not.
Fixing

**Comment by dmurphy18** [comment]
This appears to be a divergence of ZFS implementations between Solaris 10 and 11 which do not support '-t' for zfs get, unlike OS's such as Illuminos, FreeBSD, and checking Linux implementations.

Correct solution will be to skip '-t' when running on Solaris 10 and 11
