### ISSUE TITLE
 [BUG] zabbix module usage

### ISSUE THREAD

**Issue by misch42** [saltstack/salt#59338]
**Description**
I have a problem understanding the pillar data of the saltstack zabbix module.
doc in https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.zabbix.html

When I call the zabbix.apiinfo_version from the command line everything works:
`# salt 'host' zabbix.apiinfo_version _connection_user=apiuser _connection_password='XXX' _connection_url='http://XXX/api_jsonrpc.php'
  host:
    5.2.3`

But when I try to add the connection data as pillar data, it fails:
`# salt 'host' zabbix.apiinfo_version pillar='{"zabbix.user": "apiuser", "zabbix.url": "http://XXX/api_jsonrpc.php", "zabbix.password": "XXX"}'

    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/modules/zabbix.py", line 275, in _login
        raise KeyError
    KeyError
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1870, in _thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/zabbix.py", line 498, in apiinfo_version
        conn_args = _login(**connection_args)
      File "/usr/lib/python3.6/site-packages/salt/modules/zabbix.py", line 277, in _login
        raise SaltException("URL is probably not correct! ({})".format(err))
    salt.exceptions.SaltException: URL is probably not correct! ()
`

**Setup**
Command line see above.

**Steps to Reproduce the behavior**
Command line see above.

**Expected behavior**
Adding the data to pillar also should work.

**Screenshots**

**Versions Report**
`# salt --versions-report
Salt Version:
           Salt: 3001.2
 
Dependency Versions:
           cffi: 1.14.0
       cherrypy: Not Installed
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: 4.0.5
      gitpython: 3.1.8
         Jinja2: 2.11.2
        libgit2: 1.0.1
       M2Crypto: 0.36.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 3.9.8
   pycryptodome: 3.9.8
         pygit2: 1.3.0
         Python: 3.7.9 (default, Nov  3 2020, 12:10:17)
   python-gnupg: 0.4.6
         PyYAML: 5.3.1
          PyZMQ: 19.0.1
          smmap: 3.0.4
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.3
 
System Versions:
           dist: gentoo 2.7 
         locale: UTF-8
        machine: x86_64
        release: 4.9.74-grsecurity
         system: Linux
        version: Gentoo 2.7`

salt minion is:
`  # salt-minion --version
  salt-minion 3001.4`

**Comment by piterpunk** [comment]
For what I understand from documentation, specifying pillar data from command line is only available for applying states, not for all execution modules.

[Setting Pillar Data On The Command Line](https://docs.saltproject.io/en/latest/topics/tutorials/pillar.html#setting-pillar-data-on-the-command-line)

But there is a bug in the zabbix execution module which makes the reading data from pillar not work. It is using the `config.option` to search for `zabbix.*`. But this function does not search in nested structures, so it never returns data for `zabbix.user`, `zabbix.password` and `zabbix.url`. I put a few debug messages in zabbix module so we can see what happens:
```
# salt-call zabbix.apiinfo_version 2>/dev/null
Show data in pillar zabbix
{'user': 'testuser', 'password': 'password', 'url': 'http://fake_url/zabbix/api_jsonrpc.php'}
Get value for zabbix.user using config.option: 
Show data in pillar zabbix
{'user': 'testuser', 'password': 'password', 'url': 'http://fake_url/zabbix/api_jsonrpc.php'}
Get value for zabbix.password using config.option: 
Show data in pillar zabbix
{'user': 'testuser', 'password': 'password', 'url': 'http://fake_url/zabbix/api_jsonrpc.php'}
Get value for zabbix.url using config.option:
 ```
The function to get the configuration in nested structures is the `config.get`:
```
# salt-call zabbix.apiinfo_version 2>/dev/null
Show data in pillar zabbix
{'user': 'testuser', 'password': 'password', 'url': 'http://fake_url/zabbix/api_jsonrpc.php'}
Get value for zabbix.user using config.get: testuser
Show data in pillar zabbix
{'user': 'testuser', 'password': 'password', 'url': 'http://fake_url/zabbix/api_jsonrpc.php'}
Get value for zabbix.password using config.get: password
Show data in pillar zabbix
{'user': 'testuser', 'password': 'password', 'url': 'http://fake_url/zabbix/api_jsonrpc.php'}
Get value for zabbix.url using config.get: http://fake_url/zabbix/api_jsonrpc.php
```
At first sight, to make zabbix works as documented and read the data from pillar, the line 240 of `salt/modules/zabbix.py` just needs to be changed from:
```
val = __salt__["config.option"]("zabbix.{}".format(name), None)
```
To:
```
val = __salt__["config.get"]("zabbix:{}".format(name), None)
```
Will do some additional tests and make a PR with this change.

**Comment by misch42** [comment]
Hi,

works for me with the changes to config.get(). Please merge.

**Comment by sagetherage** [comment]
Reviewed in Tuesday Triage meeting 2021-MAR-23 and getting reviews on the PR for merging
