### ISSUE TITLE
[BUG] missing binaries on https://repo.saltstack.com/windows/

### ISSUE THREAD

**Issue by jeremybusk** [saltstack/salt#59356]
**Description**
https://github.com/saltstack/salt/releases/tag/v2019.2.8
is missing on  https://repo.saltstack.com/windows/
i.e Salt-Minion-2019.2-Py3-AMD64-Setup.exe
This is breaking for bootstrap installer and other custom installers

**Setup**
Could you fix and even better compile and add windows binaries on github releases. I feel they should be included with releases.

**Steps to Reproduce the behavior**
https://repo.saltstack.com/windows/Salt-Minion-2019.2.8-Py2-AMD64-Setup.exe

**Expected behavior**
Download should work and binaries should be included on releases in github. Maybe an issue with your ci/cd.

**Comment by sagetherage** [comment]
@jeremybusk we have archived unsupported versions and they can be found here [https://archive.repo.saltstack.com/windows/](https://archive.repo.saltstack.com/windows/ )

**Comment by sagetherage** [comment]
We can also add these to the github release files, but that will take some time. I will leave this open to get that work completed.
