### ISSUE TITLE
[FEATURE REQUEST] new module Cohesity integration with Salt

### ISSUE THREAD

**Issue by naveena-maplelabs** [saltstack/salt#59368]
**Is your feature request related to a problem? Please describe.**
I m working on Cohesity integration with Salt. Have developed a module for the same. But i m facing during the pre-commit tests. Not sure what is missed.
https://github.com/saltstack/salt/pull/59328

**Comment by sagetherage** [comment]
Please see my comments in the PR linked [here](https://github.com/saltstack/salt/pull/59328#issuecomment-824924918)
