### ISSUE TITLE
[BUG] Delete the old installation instructions and repo rpms

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#59378]
**Description**
The old unsupported releases have moved to https://archive.repo.saltstack.com  the repo rpms such as https://archive.repo.saltstack.com/yum/redhat/salt-repo-latest.el6.noarch.rpm have the wrong urls in them.

- [x] the instructions are also wrong on https://repo.saltstack.com/2019.2.html - AL

- [x] We should delete the repo rpms from archive.repo.saltproject.io so they are not confusing.  Most people I've talked to say deleting them would be a good thing. - Si

- [x] We added .repo files to replace the rpms going forward in places like https://repo.saltstack.com/py3/redhat/8/x86_64/latest.repo AL

- [x] We need to update the repo landing page instructions to use them instead. AL

Working repo rpms on https://repo.saltstack.com will not be deleted until their repos move to https://archive.repo.saltstack.com

**Comment by bryceml** [comment]
The old installation instructions have been deleted.

**Comment by bryceml** [comment]
removing the repo rpms will happen after announcements.

**Comment by bryceml** [comment]
We would also like to remove the redhat and amazonlinux version symlinks such as https://archive.repo.saltproject.io/yum/redhat/7.2 at the same time as removing the repo rpms.

**Comment by ScriptAutomate** [comment]
> the instructions are also wrong on https://repo.saltstack.com/2019.2.html
>
> We should delete them so they are not confusing. Most people I've talked to say deleting them would be a good thing.

`2019.2.x` is in **[Extended Life Support](https://saltproject.io/salt-platform-support/)**, and the repo landing page has been removed, while `2019.2.x` packages have been migrated over to https://archive.repo.saltproject.io

> We added .repo files to replace the rpms going forward in places like https://repo.saltstack.com/py3/redhat/8/x86_64/latest.repo
> 
> We need to update the repo landing page instructions to use them instead.

We've now completely updated the https://repo.saltproject.io/ directions to use the new methods for `.repo` files instead of rpms.

> The old unsupported releases have moved to https://archive.repo.saltstack.com the repo rpms such as https://archive.repo.saltstack.com/yum/redhat/salt-repo-latest.el6.noarch.rpm have the wrong urls in them.
>
> Working repo rpms on https://repo.saltstack.com will not be deleted until their repos move to https://archive.repo.saltstack.com

`rpms` still exist, for current releases now, on https://repo.saltproject.io.

@bryceml Does this mean this issue is resolved? Or are we needing to add `.repo` files to the archive, too?

**Comment by ScriptAutomate** [comment]
> - [ ] We should delete the repo rpms from archive.repo.saltproject.io so they are not confusing. Most people I've talked to say deleting them would be a good thing.

This will be part of the #59647 EPIC and will be done then.
