### ISSUE TITLE
[BUG]SALT.STATES.WIN_PATH adds '.'(current directory) in path variable, windows 10

### ISSUE THREAD

**Issue by Meerkat81** [saltstack/salt#59396]
**Description**
Using the win_path adds '.' into the path variable

**Setup**
'C:/Users/{{client_username}}/AppData/Roaming/npm':
  win_path.exists

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
Only add the name to path not an arbitrary '.' into path variable

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
```
</details>

**Additional context**

**Comment by xeacott** [comment]
Can confirm.... Silly salt
<img width="441" alt="Capture" src="https://user-images.githubusercontent.com/31625359/107296991-b2297280-6a2f-11eb-98e3-a28d5ef7f7d7.PNG">
