### ISSUE TITLE
[BUG] Running pkg.upgrade from orchestration runner returns improper output (#2)

### ISSUE THREAD

**Issue by pprkut** [saltstack/salt#59400]
**Description**
```
host1.example.com:
The State execution failed to record the order in which all states were executed. The state return missing data is:
{'new': '1.17.2-1', 'old': '1.17.0-1'}

Summary for host1.example.com
-----------
Succeeded: 0
Failed:   0
-----------
```

The same as issue #55381, which was supposed to be fixed, but after updating to 3002.2 (and switching to python3), the issue remains.

**Setup**

Config in `pkg/upgrade/account1/updates.sls`
```
upgrade_account1_updates:
  salt.function:
    - name: pkg.upgrade
    - tgt: "ec2_tags:account:account1"
    - tgt_type: grain
    - kwarg:
        fromrepo: updates
```

**Steps to Reproduce the behavior**
```
salt-run state.orchestrate pkg.upgrade.account1.updates
```

**Versions Report**
```
Salt Version:
          Salt: 3002.3

Dependency Versions:
          cffi: 1.14.1
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: 1.0.1
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: 1.3.12
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 1.2.1
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1127.19.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```

**Comment by sagetherage** [comment]
@pprkut thank you for opening another ticket, I am assigning an engineer to look at it in AL to determine why this continues to be an issue. Hopefully, we will determine that soon.

**Comment by sagetherage** [comment]
@pprkut we didn't get to this in Aluminium so I am moving it to planning for the next release cycle and will try to get it assigned to an engineer.

**Comment by pprkut** [comment]
@Ch3LL Sorry for the long delay. Pre-Christmas stress :(

I just checked and it's still happening on 3004 too.

**Comment by Ch3LL** [comment]
Thanks for confirming. I've added it to the Sulphur release milestone.

**Comment by pprkut** [comment]
@MKLeb We're still on 3004.1, where I'm still experiencing the issue. We ran into some troubles when updating to a newer version that we didn't have time to investigate yet, but that's on our short term TODO list. I'll get back to you as soon as I can :pray:

**Comment by pprkut** [comment]
Still on 3004.1, but somehow I'm no longer seeing the issue... Not sure what changed. I'll close this issue for now, praying it won't come back :sweat_smile:
