### ISSUE TITLE
[DOCS] Issue while building docs, facing module not found error

### ISSUE THREAD

**Issue by naveena-maplelabs** [saltstack/salt#59407]
**Description**
I have added new module cohesity.py to the salt modules. Module have dependecy package cohesity-management-sdk. I have created a PR. PR is failing with error while building docs.
https://github.com/saltstack/salt/pull/59328/checks?check_run_id=1824829778
```
Warning, treated as error:
[autosummary] failed to import 'salt.modules.cohesity': no module named salt.modules.cohesity
Error while importing Cohesity SDK modules.
No module named 'cohesity_management_sdk'
Failed to import 'salt.modules.cohesity': no module named salt.modules.cohesity
Error while importing Cohesity SDK modules.
No module named 'cohesity_management_sdk'
make: *** [Makefile:56: html] Error 2
nox > Command make html SPHINXOPTS=-W failed with exit code 2
nox > Session docs-html(compress=False, clean=True) failed.
Error: Process completed with exit code 1.
```
While adding new module, do we need to update any other files, do we need to add required packages in any other files other than requirements. Thanks in advance.

**Comment by naveena-maplelabs** [comment]
@s0undt3ch , can you please provide a solution for the issue. Thanks in advance.

**Comment by s0undt3ch** [comment]
It looks like sphinx is just failing to import your module.

**Comment by s0undt3ch** [comment]
Ie, something is wrong that it's not importable by python

**Comment by garethgreenaway** [comment]
The recommendation was to move the original PR to a Salt extension.  Closing this one out.
