### ISSUE TITLE
[BUG] Netbox Pillar Not Working With Salt States

### ISSUE THREAD

**Issue by VaporSchmidt** [saltstack/salt#59406]
**Description**

I am unable to apply any salt state using Netbox as an external pillar. 

**Setup**

```
# cat testcase.sls 
testcase:
  test.nop

# cat /etc/salt/master.d/netbox.conf 
ext_pillar:
  - netbox:
      api_url: <>
      api_token: <>
      site_details: True
      site_prefixes: True
```

**Steps to Reproduce the behavior**

```
# salt QFX3.LAB state.apply testcase
QFX3.LAB:
    Data failed to compile:
----------
    Pillar failed to render with the following messages:
----------
    Specified SLS 'netbox' in environment 'base' is not available on the salt master

```

**Expected behavior**

**Screenshots**

```
**Versions Report**
# salt --versions-report
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Oct  8 2020, 12:12:24)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-1036-gcp
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
 

**Additional context**

The Netbox pillar works correctly at execution 

```
#  salt QFX3.LAB pillar.items
QFX3.LAB:
    ----------
    netbox:
        ----------
        asset_tag:
            None
        cluster:
            None
        comments:
        config_context:
            ----------
        created:
            2021-02-02
        custom_fields:
            ----------
            sf_id:
                None
        device_role:
            ----------
            id:
                1
            name:
                Access Switch
            slug:
                access-switch
[...]
```

**Comment by sagetherage** [comment]
@VaporSchmidt yesterday we had another issue submitted to update the documentation on something similar here: https://github.com/saltstack/salt/issues/59398 this configuration is on the master and not in the pillar directory, does that solve your problem?

**Comment by VaporSchmidt** [comment]
> @VaporSchmidt yesterday we had another issue submitted to update the documentation on something similar here: #59398 this configuration is on the master and not in the pillar directory, does that solve your problem?

No. My configuration data is on the master and works correctly outside of state application.

**Comment by alan-cugler** [comment]
@sagetherage This is possibly a bug, I can see his netbox external pillar works correctly when he does a terminal request. However, when trying to utilize the netbox external pillar the state system errors out.

I am super hoping its a user error I am not catching but definitely some eyes on this would be helpful from the community and experts.

**Comment by jtraub91** [comment]
I offer myself as a witness to the observed bug.

**Comment by doesitblend** [comment]
@jtraub91 If you run a `saltutil.refresh_pillar` prior to running the state, does it work?

**Comment by jtraub91** [comment]
@doesitblend I believe we tried that and it did not fix the issue, but maybe https://github.com/saltstack/salt/issues/59393 is related

**Comment by jtraub91** [comment]
After re-testing this in a separate envrionment, I am no longer seeing the error described. This may be user error after all :upside_down_face:

**Comment by sagetherage** [comment]
@jtraub91 thank you I will close this for now, keep us posted!
