### ISSUE TITLE
[FEATURE REQUEST] https only repo

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#59419]
**Is your feature request related to a problem? Please describe.**

Move repo.saltproject.io to https-only with a redirect from http.  All vmware repos are https only, so we should conform to that standard.

On debian based distros, that means installing apt-transport-https, or for newer versions, making sure ca-certificates is installed.

**Comment by sagetherage** [comment]
Are we thinking that this will happen as we use edge caching?

**Comment by bryceml** [comment]
> Are we thinking that this will happen as we use edge caching?

by that I think you mean akamai, which would look very similar to what https://packages.vmware.com/photon/ looks like.

not sure when/how, but we should move to https only regardless.  Any recommendation on how we do that with the least interruption is welcome.

**Comment by bryceml** [comment]
Tentative plans:

Step 1:
Investigate if akamai can be used instead of cloudfront.  If it can be used, use it to host:
* repo.saltproject.io
* archive.repo.saltproject.io
* bootstrap.saltproject.io
* winbootstrap.saltproject.io

possibly others

Http to https redirects will be in place from the start when it's introduced (assuming it fits the usecase)

If we can's use akamai, still add http -> https redirects for all saltproject.io urls on cloudfront.

A goal is to only support tls1.2 and tls1.3 on whatever is used.

Step 2:

This will be at a later date to give people a fall back to http if they need for a while by using saltstack.com domain names.

We will redirect saltstack.com domain names to saltproject.io domain names.

The domains beginning with s3 such as s3.repo.saltstack.com and s3.archive.repo.saltstack.com will not be redirected between domain names since the aws cli doesn't seem to be able to handle redirects, although rclone does seem to support it.  We will redirect http to https though to make sure http is not used.

Bootstrap and winbootstrap urls already redirect to https but we will add https://bootstrap.saltstack.com -> https://bootstrap.saltproject.io redirects at this same time.
