### ISSUE TITLE
[BUG] not all openssh public key authentication types are supported

### ISSUE THREAD

**Issue by MEschenbacher** [saltstack/salt#59429]
**Description**
The current ssh modules and states do not allow all supported key types for ssh public key authentication.

Any ssh pubkey type other than
- r
- rsa
- ssh-rsa
- e
- ecdsa
- ecdsa-sha2-nistp521
- ecdsa-sha2-nistp384
- ecdsa-sha2-nistp256
- ed25519
- ssh-ed25519

in this case `ssh-ed25519-cert-v01@openssh.com` fails with the following message:

```
          ID: ssh pubkey [...] for user root type ssh-ed25519-cert-v01@openssh.com
    Function: ssh_auth.present
        Name: [...]
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 1919, in call
                  **cdata['kwargs'])
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1918, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/ssh_auth.py", line 349, in present
                  fingerprint_hash_type=fingerprint_hash_type)
                File "/usr/lib/python3/dist-packages/salt/modules/ssh.py", line 717, in set_auth_key
                  enc = _refine_enc(enc)
                File "/usr/lib/python3/dist-packages/salt/modules/ssh.py", line 78, in _refine_enc
                  'Incorrect encryption key type \'{0}\'.'.format(enc)
              salt.exceptions.CommandExecutionError: Incorrect encryption key type 'ssh-ed25519-cert-v01@openssh.com'.
     Started: 20:49:13.855666
    Duration: 1.456 ms
     Changes:   

```

This is a list of ssh pubkey types which are supported by openssh client version 8.4 for which the current implementation errors out (https://github.com/saltstack/salt/blob/master/salt/modules/ssh.py#L80):

```
ecdsa-sha2-nistp256-cert-v01@openssh.com
ecdsa-sha2-nistp384-cert-v01@openssh.com
ecdsa-sha2-nistp521-cert-v01@openssh.com
sk-ecdsa-sha2-nistp256-cert-v01@openssh.com
ssh-ed25519-cert-v01@openssh.com
sk-ssh-ed25519-cert-v01@openssh.com
rsa-sha2-512-cert-v01@openssh.com
rsa-sha2-256-cert-v01@openssh.com
ssh-rsa-cert-v01@openssh.com
sk-ecdsa-sha2-nistp256@openssh.com
sk-ssh-ed25519@openssh.com
rsa-sha2-512
rsa-sha2-256
```

**Versions Report**
I've checked several versions including the current master branch, all of which filter the key type and error out.

**Comment by MEschenbacher** [comment]
I began developing a possible fix for this issue and figured we have two options:

1. continue maintaining an allowlist of pubkey types. This requires us to periodically update it (as we have to to now).
2. allow any future pubkey type by skipping both validation and normalisation for all new types.

What do you think is the better approach?

**Comment by xeacott** [comment]
Thought I had sent a message on this, but I did not and I apologize. Personally I would be in favor of 1 but Ill ask @saltstack/team-core and @s0undt3ch just in case...

**Comment by dwoz** [comment]
> I began developing a possible fix for this issue and figured we have two options:
> 
> 1. continue maintaining an allowlist of pubkey types. This requires us to periodically update it (as we have to to now).
> 2. allow any future pubkey type by skipping both validation and normalisation for all new types.
> 
> What do you think is the better approach?

I prefer approach 1.

**Comment by hkbakke** [comment]
> I began developing a possible fix for this issue and figured we have two options:
> 
>     1. continue maintaining an allowlist of pubkey types. This requires us to periodically update it (as we have to to now).
> 
>     2. allow any future pubkey type by skipping both validation and normalisation for all new types.
> 
> 
> What do you think is the better approach?

I prefer 2. I feel that application specific config option validation is not sustainable for a configuration management tool.

I would rather that my CMS allows me to do enforce what I need to, even if that includes possibly setting invalid config values from the view of the application. The alternative is not getting the thing done at all, like in this case.

**Comment by MEschenbacher** [comment]
I prefer option 2, too because if we select option 1, we have gained nothing from the fix except certainty that it will hit us again as soon as new pubkey types are introduced.

By the way, I've reported the same problem for ansible: https://github.com/ansible-collections/ansible.posix/issues/134

**Comment by dkacar-oradian** [comment]
You could add a flag which would skip validation.

**Comment by svenseeberg** [comment]
Is `sk-ssh-ed25519@openssh.com` expected to work with the mentioned PR or not?

**Comment by ipaqmaster** [comment]
This seems to still be a problem.

`raise CommandExecutionError("Incorrect encryption key type '{}'.".format(enc))`
