### ISSUE TITLE
[FEATURE REQUEST] FIPS mode flag

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#59427]
**Is your feature request related to a problem? Please describe.**

Add a FIPS compliant mode flag to salt and make sure this flag False before using non-fips compliant crypto libraries such as libnacl.

**Comment by OrangeDog** [comment]
Related: #56673 #50662

**Comment by bryceml** [comment]
https://github.com/saltstack/salt/pull/58918

PhotonOS 3 has fips enabled in the image on this PR.

**Comment by OrangeDog** [comment]
Appears to gave been done (but not documented) in #59833

**Comment by sagetherage** [comment]
closing is at the feature is implemented in Aluminium and we have another ticket to document and to start catching these as well
