### ISSUE TITLE
[DOCS] Conflicting information on grains and storing passwords: Deprecate salt.modules.grains.get_or_set_hash

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#59425]
**Description**

Salt best practices direct users to use the `pillar` or [SDB](https://docs.saltproject.io/en/latest/topics/sdb/index.html) for storing sensitive data, such as passwords. Outside of documentation, we explicitly advise users _not_ to store passwords in grains on minions, but this is only _implied_ by the documentation.

This gets more complicated with the existence of this execution module function:

- [grains.get_or_set_hash](https://docs.saltproject.io/en/master/ref/modules/all/salt.modules.grains.html#salt.modules.grains.get_or_set_hash)
  - [Initial commit](https://github.com/saltstack/salt/commit/9168eb12f76d28ae8eb9f7d60831ec6a03590088)

**Suggested Fix**

- Deprecate [grains.get_or_set_hash](https://docs.saltproject.io/en/master/ref/modules/all/salt.modules.grains.html#salt.modules.grains.get_or_set_hash)
- Create a `.. warning::` admonition `rst` file that should be included with `.. include::` in a variety of documentation endpoints:
  - [Hardening Guide](https://docs.saltproject.io/en/latest/topics/hardening.html)
  - [Salt Best Practices](https://docs.saltproject.io/en/latest/topics/best_practices.html)
  - [Grains](https://docs.saltproject.io/en/latest/topics/grains/index.html)
    - Likely somewhere in [Grains: Writing Grains](https://docs.saltproject.io/en/latest/topics/grains/index.html#writing-grains)
  - Section of FAQ: [Is targeting using grain data secure?](https://docs.saltproject.io/en/latest/faq.html#is-targeting-using-grain-data-secure)
    - Maybe this answer should be modified?

The warning admonition could be along the lines of:

```rst
.. warning::

   Grains can be set by users that have access to the minion configuration files on
   the local system, making them less secure than other identifiers in Salt. Avoid
   storing sensitive data, such as passwords or keys, on minions. Instead, make
   use of :ref:`pillar` and/or :ref:`sdb`.
```

**Type of documentation**

- Salt documentation
- Salt modules

**Additional context**

Related issues:

- #43287

**Comment by OrangeDog** [comment]
Just seen this in the release notes. What's the alternative when you want every minion to have a random unique value, and someone with root access to the minion changing it is not an issue?

`get_or_set_hash` is the only way I can see to do it automatically at scale.

**Comment by OrangeDog** [comment]
Never got any answer for this, and it's a bit late now.

You now have to replace a very simple system that was perfectly secure in many models with an entirely separate external database.

I'm just going to re-add `get_or_set_hash` as a custom module.
