### ISSUE TITLE
[BUG] napalm_mod.py does not set a default transport method for NXOS.  It should be https.

### ISSUE THREAD

**Issue by kaibabbob** [saltstack/salt#59448]
**Description**
The Napalm documentation says that the default transport is https.  However, if "transport" is not defined as an optional_arg in the pillar then the pyeapi_nxos_api_args() function in napalm_mod.py will set the transport kwarg to None which breaks commands like "salt my_router napalm.nxos_api_config 'ntp server 1.1.1.1'"

ValueError: Unsupported url scheme: None://my_router:4000/ins

I see three options for fixing this:
1.  Add transport: https as an optional_arg
2. Have pyeapi_nxos_api_args set the value to 'https' if its not found in the pillar in napalm_mod.py
3. Have _prepare_connection() in /usr/lib/python3.6/site-packages/salt/utils/nxos_api.py change None to 'https'

My opinions:
Option 1 seems like a hack to me.  If there is a default in Napalm, the Salt napalm module should not require a value if the default is fine.

Option 2 seems like a good choice as this is where Salt first learns the transport

**Setup**
proxy minion pillar:
```
    proxy:
        ----------
        connection:
            nxapi
        driver:
            nxos
        host:
            my_router
        key_accept:
            True
        multiprocessing:
            True
        no_save_config:
            True
        optional_args:
            ----------
            port:
                4000
            ssl_verify:
                /etc/pki/ca-trust/extracted/pem/tls-ca-bundle.pem
            transport:
                https
        password:
            the_clown
        prompt:
            my_router
        prompt_name:
            my_router
        proxytype:
            napalm
        ssh_args:
            -o PubkeyAuthentication=no
        ssh_private_key_file:
            /root/.ssh/id_rsa
        username:
            bozo

```
**Steps to Reproduce the behavior**
Execute the module:  salt my_router napalm.nxos_api_config 'ntp server 1.1.1.1'

**Expected behavior**
it should add a configuration line:
[root@my_master _modules]# salt my_router napalm.nxos_api_config 'ntp server 1.1.1.1'
my_router:
    ---
    +++
    @@ -79,6 +79,7 @@
     snmp-server community xxxx group vdc-operator
     snmp-server community xxxx group vdc-admin
     snmp-server community xxxx group vdc-operator
    +ntp server 1.1.1.1

     ip pim ssm range 232.0.0.0/8
     system vlan long-name

**Screenshots**
here is the traceback

`[root@my_master _modules]# salt my_router napalm.nxos_api_config 'ntp server 1.1.1.1'
my_router:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/metaproxy/proxy.py", line 480, in thread_return
        opts, data, func, args, kwargs
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/local/lib/python3.6/site-packages/salt/utils/napalm.py", line 515, in func_wrapper
        ret = func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/napalm_mod.py", line 1270, in nxos_api_config
        **nxos_api_kwargs
      File "/usr/lib/python3.6/site-packages/salt/modules/nxos_api.py", line 416, in config
        initial_config = show("show running-config", **kwargs)[0]
      File "/usr/lib/python3.6/site-packages/salt/modules/nxos_api.py", line 317, in show
        response_list = _cli_command(commands, method=method, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/nxos_api.py", line 183, in _cli_command
        rpc_responses = rpc(commands, method=method, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/nxos_api.py", line 260, in rpc
        return __utils__["nxos_api.rpc"](commands, method=method, **nxos_api_kwargs)
      File "/usr/lib/python3.6/site-packages/salt/utils/nxos_api.py", line 127, in rpc
        **init_args
      File "/usr/local/lib/python3.6/site-packages/salt/utils/http.py", line 629, in query
        result = download_client.fetch(url_full, **req_kwargs)
      File "/usr/local/lib/python3.6/site-packages/salt/ext/tornado/httpclient.py", line 103, in fetch
        self._async_client.fetch, request, **kwargs))
      File "/usr/local/lib/python3.6/site-packages/salt/ext/tornado/ioloop.py", line 459, in run_sync
        return future_cell[0].result()
      File "/usr/local/lib/python3.6/site-packages/salt/ext/tornado/concurrent.py", line 249, in result
        raise_exc_info(self._exc_info)
      File "<string>", line 4, in raise_exc_info
      File "/usr/local/lib/python3.6/site-packages/salt/ext/tornado/simple_httpclient.py", line 218, in __init__
        self.request.url)
    ValueError: Unsupported url scheme: None://my_router:4000/ins
ERROR: Minions returned with non-zero exit code`

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.5

Dependency Versions:
           cffi: 1.11.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: 4.0.2
      gitpython: Not Installed
         Jinja2: 2.10.1
        libgit2: 0.99.0
       M2Crypto: 0.35.2
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.19
       pycrypto: 3.8.2
   pycryptodome: 3.9.8
         pygit2: 1.1.1
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 17.0.0
          smmap: 3.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```
</details>

**Additional context**
I validated option 1 by adding transport: https as an optional_arg

I also validated option 2 by modifying pyeapi_nxos_api_args in napalm_mod.py

`# diff napalm_mod.py napalm_mod.py-
1019,1020d1018
<     #if optional_args.get("transport") == None:
<     #    optional_args["transport"] = 'https'`

**Comment by dmurphy18** [comment]
@kaibabbob See the issue, nxos_api_config calls into nxos_api.config and while that function in salt/modules/nxos_api.py declares transport default of 'https' in the doc at the start of the function, does not do anything to set that input or even make use of it, nor does it include it in the function definition.

Definitely needs fixing, will bring the issue up with the author.

**Comment by dmurphy18** [comment]
@mirceaulinic Have an issue arise with using nxos_api.config where the doc states transport but not in the function definition
https://github.com/saltstack/salt/blob/a9b9795c4a80ec92cb593c90a8b5ec295a9f7aab/salt/modules/nxos_api.py#L372-L375

https://github.com/saltstack/salt/blob/a9b9795c4a80ec92cb593c90a8b5ec295a9f7aab/salt/modules/nxos_api.py#L315-L323

Simplest fix is to add the following before the kwargs agruement, but wanted to check first unless you had other plans here

```
def config(
    commands=None,
    config_file=None,
    template_engine="jinja",
    context=None,
    defaults=None,
    saltenv="base",
    transport="https",
    **kwargs
):
```

**Comment by dmurphy18** [comment]
@mirceaulinic Any comments on the above comment

**Comment by mirceaulinic** [comment]
Yes, I think it makes sense to default to `https`. Cheers!

**Comment by dmurphy18** [comment]
A simple setting of defaults to https and 443 or http and 80 creates problems since for other drivers under Napalm, such as, nxos_ssh which wants to use port 22 presumably.

Attempts to set the https defaults etc in salt/utils/napalm get_device_opts caused issues.
Need to re-evaluate solution.

**Comment by dmurphy18** [comment]
@kaibabbob Actually Option 1 appears to be the better alternative since in salt/util/s/napalm.py when opening the network_driver, the optional arguments are passed into the Napalm driver. see 
https://github.com/saltstack/salt/blob/121c61c832a58874acf5ad55c7eb20c598995dff/salt/utils/napalm.py#L337-L348

You could presume that the Napalm network driver would know it's own defaults, however the Napalm driver for NXOS, the class NXOSDriver __init__ method relies on optional_args and does not handle defaulting if transport and port are not set, and these values are utilized in the open function, see
https://github.com/napalm-automation/napalm/blob/1e8a049d1fe091bcb033eabc7c793207d3bffa4e/napalm/nxos/nxos.py#L673-L709
setting values in Option 2 would be after the connection is already attempted.

Setting the defaults in https://github.com/saltstack/salt/blob/121c61c832a58874acf5ad55c7eb20c598995dff/salt/utils/napalm.py#L260
is a work-around for the napalm nxos driver not setting it's own defaults.

**Comment by kaibabbob** [comment]
@dmurphy18 Thanks for the detailed response.  I had initially noted the disconnect between the Napalm docs saying that the default it HTTPS and the lack of a default in Salt.  Am I understanding correctly that the issue is actually that the Napalm documentation is incorrect and should have noted that there is no default for NXOS?

**Comment by dmurphy18** [comment]
@kaibabbob The Napalm docs state https default for EOS and NXOS, links and comment up above. But mis-thought the actual implementation, for example the links above for the actual NXOS handling code in Napalm, if optional_args doesn't have 'transport' defined the get should return https
```
  681         # nxos_protocol is there for backwards compatibility, transport is the preferred method                                
   682         self.transport = optional_args.get(                                                                                    
   683             "transport", optional_args.get("nxos_protocol", "https")                                                           
   684         ) 
```

So need to revise my comments above, both Napalm NOX and EOS are defaulting correctly, need to dig back into this, since the internal napalm defaults are not being reflected in Salt and hence that None://xxxxxxxx

Thanks for the question, it caused me to re-visit my proposed solution.

**Comment by dmurphy18** [comment]
Able to duplicate the issue using nxos_ssh as the driver. The code has handling for defaulting the transport and port to https and appropriate port value: 
https://github.com/saltstack/salt/blob/d19b1da04930e7350117caa94da19be634c2f3a2/salt/utils/nxos_api.py#L31-L48

but transport is already defined with None, see log output
```
656 ^Mnexus9500# 
657 [DEBUG   ] Pattern found: nexus9500 ^M^M
658 ^Mnexus9500# ^M^M
659 ^Mnexus9500# ^M^M
660 ^Mnexus9500# 
661 [DEBUG   ] LazyLoaded nxos_api.config
662 [DEBUG   ] LazyLoaded nxos_api.rpc
663 [ERROR   ] These are the init args:
664 [ERROR   ] {'host': '10.225.0.229', 'username': 'admin', 'password': 'cisco', 'timeout': 60, 'transport': None, 'port': None, 'verify': None, 'ca_bundle': None, 'rpc_version': '2.0'}
665 [DEBUG   ] Requesting URL None://10.225.0.229:None/ins using POST method
666 [DEBUG   ] Using backend: tornado
667 [TRACE   ] Request POST Data: ('[{"jsonrpc": "2.0", "method": "cli_ascii", "params": {"cmd": "show '
668  'running-config", "version": 1}, "id": 1}]')
669 [ERROR   ] An un-handled exception was caught by salt's global exception handler:
670 ValueError: Unsupported url scheme: None://10.225.0.229:None/ins
671 Traceback (most recent call last):
```

**Comment by dmurphy18** [comment]
Fix coming in PR https://github.com/saltstack/salt/pull/61556
