### ISSUE TITLE
[BUG] apt-key should be removed from all salt states/modules

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#59456]
See https://github.com/saltstack/salt/issues/59408

The apt-key command should not be used anywhere in salt.

The new method of putting gpg keys in /usr/share/keyrings/ and adding `signed-by` to the sources.list entry should be made available in those states/modules, with documentation showing how to do so.

This should be done in a way that doesn't break existing states that people have written.

**Comment by sagetherage** [comment]
This is a shell of an issue - details will be put in this issue as we go through planning for Silicon release cycle.

**Comment by OrangeDog** [comment]
Related: https://github.com/saltstack/salt/issues/59785

**Comment by OrangeDog** [comment]
> This should be done in a way that doesn't break existing states that people have written.

The current way `pkgrepo` works for apt is pretty user-unfriendly, and completely inconsistent with how it works for rpm.
A bigger change and fully deprecating the old way may be a good idea, but needs some thought.

Perhaps switching from `.list` to `.sources` would make it easier.

**Comment by chsaj** [comment]
> Perhaps switching from .list to .sources would make it easier.

This is a pretty bad idea unless the Debian project makes the change itself.

**Comment by OrangeDog** [comment]
@chsaj what do you mean? The `.sources` format is from Debian, and they use both. See e.g. [this example](https://wiki.debian.org/DebianRepository/UseThirdParty#Complete_example).

**Comment by Ch3LL** [comment]
This was added here: https://github.com/saltstack/salt/pull/61760
