### ISSUE TITLE
Make scheduling more powerful

### ISSUE THREAD

**Issue by analogbyte** [saltstack/salt#5946]
Since the addition of multiple redundant masters it would be nice to improve on the scheduling included in salt.

When scheduling jobs on the masters, you have the following options:
 1. You schedule on both masters (with different intervalls). This leads to inconsistent intervalls which change on every restart of a master. Or two jobs running at once.
 2. You only schedule on one master and thus kill the intended redundancy.

I can think of these solutions:
* use cron, duh...
* outsource the scheduling to every minion using a state, which would then call to some master. This is possible right now, but note that you can't use the overstate system that way.
* make scheduling more powerful, i.e. not only simple interval based jobs, but functionality like cron or at least an option to run jobs at specific times.

**Comment by analogbyte** [comment]
This has been largely implemented, although a multimaster setup still does not have a shared schedule configuration. The cron like syntax used by scheduling today fixes the issues I've had back then.

**Comment by rallytime** [comment]
@analogbyte Thanks for following up! Do you want to file a new request for the multi-master pieces? Or does one already exist?

**Comment by analogbyte** [comment]
@rallytime I don't really know if it is necessary. 

The obvious solution is to schedule on both (all) masters in intervals. If I want highstates run every day, I do it every 48 hours on each master, but offset by 24 hours. Or just do it at double pace.
The original problem, the possibility that highstates get executed close together or at the same time by both masters is eliminated anyway.
If one really wants to say 'highstate at 0500, I don't care which master initiates it'... I don't know if there is a solution for that. But actually, I think this would pose a very difficult synchronization problem for a relativly minor feature.

Btw, there is this duplicate, too: #8122

**Comment by rallytime** [comment]
Sounds good! Thanks!
