### ISSUE TITLE
[BUG] grains.get() and pillar.get() cannot return values in nested dicts

### ISSUE THREAD

**Issue by alertedsnake** [saltstack/salt#59473]
**Description**
Both `grains.get()` and `pillar.get()` fail to return values in nested dictionaries, whereas `salt.grains.get()` and `salt.pillar.get()` both do.

Sorry if this is a duplicate or a known feature, I couldn't find anything in the issues, and couldn't find anything in the docs that suggests that this would be expected behavior.

**Setup**
Given this state file:
```
/tmp/test.txt:
    file.managed:
        - contents: |
            --- salt tests ---
            salt.grains.get: {{ salt.grains.get('meta-data:ami-id') }}
            grains.get: {{ grains.get('meta-data:ami-id') }}
            
            ---- pillar tests ---
            salt.pillar.get: {{ salt.pillar.get('test:value') }}
            pillar.get: {{ pillar.get('test:value') }}
```

And in Pillar, `test:value` is set to `monkey`.

**Steps to Reproduce the behavior**

Run `salt-call state.sls test.sls`

**Expected behavior**

I expected these to be equivalent, but here are the actual results:
```$ cat /tmp/test.txt
--- salt tests ---
salt.grains.get: ami-08306577a6694f5e7
grains.get: None

---- pillar tests ---
salt.pillar.get: monkey
pillar.get: None
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.14.4
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-1035-aws
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Comment by alertedsnake** [comment]
Ah I forgot to mention that both these calls do correctly return the same values when using a top-level key, such as the grain `oscodename`. It's only when using nested keys that they fail.

**Comment by whytewolf** [comment]
this is expected behavior. 

the pillar and grains dicts are just that, standard python dicts. the get object on those dicts is the standard python get function. not the salt version. the 'key:value' notation is specific to salt. when you call `salt.pillar.get` you are calling the salt pillar module with the salt version of get. but when you have just `pillar.get` you are using the pillar dict with the standard python get function.. that salt at the front means you are calling a different library.

**Comment by alertedsnake** [comment]
I couldn't say for sure, just that I definitely did not find it when I went looking.  Thanks for your help.

**Comment by whytewolf** [comment]
no problem, I'll go ahead and close this issue now. thank you and have a pleasant day.
