### ISSUE TITLE
[TEST FAILURE] mas 10.14 mojave pytest slow builds 2 failures

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59476]
**Description**
https://jenkins.saltproject.io/job/pr-macosxmojave-py3-pytest-slow/job/master/lastCompletedBuild/testReport/

```

tests.integration.netapi.test_client.NetapiSSHClientTest.test_shell_inject_remote_port_forwards
tests.integration.ssh.test_mine.SSHMineTest.test_ssh_mine_get

```

**Comment by twangboy** [comment]
Looks like that's from this build: https://jenkins.saltproject.io/job/pr-macosxmojave-py3-pytest-slow/job/master/1032/
Each successive build has different failed tests

**Comment by ggiesen** [comment]
Experiencing the same with PR #59649:

```
19:29:47  [GitHub Checks] GitHub check (name: ci/py3/macosxmojave/pytest, status: COMPLETED) has been published.
19:29:48  Timeout has been exceeded
19:29:48  Finished: ABORTED
```

https://jenkins.saltproject.io/job/pr-macosxmojave-py3-pytest/job/PR-59649/13/

**Comment by sagetherage** [comment]
These are still timing out @twangboy

**Comment by twangboy** [comment]
I don't know why they're timing out. The logs console output doesn't look like it's timing out.... looks like it's still running when it says it timed out. Maybe @bryceml has some ideas.

**Comment by bryceml** [comment]
@twangboy the tests are canceling because they take more than 5.75 hours which is our time limit for running tests.

I believe we could just change `testrun_timeout: 6,` to `testrun_timeout: 7,`  if we want to give it more time, or figure out which tests are taking so long and fix them.  We've been hesitant to increase the time in the past because otherwise we never find out why it's slow.

**Comment by twangboy** [comment]
OK, updated the timeout and now I'm seeing a different test failure:

`tests.pytests.integration.master.test_clear_funcs.test_pub_not_allowed`

Which seems to be a flaky test on Mac. Looks like this test doesn't regularly fail

**Comment by twangboy** [comment]
Plus, there were two successful runs before that...
