### ISSUE TITLE
[TEST FAILURE] multimaster beacons test inotify

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59477]
**Description**
https://jenkins.saltproject.io/job/pr-ubuntu1604-py3-m2crypto-pytest-slow/job/master/lastCompletedBuild/testReport/

```

tests.pytests.scenarios.multimaster.beacons.test_inotify.test_beacons_duplicate_53344

```

**Comment by s0undt3ch** [comment]
To someone reading this, it's a flaky test, likely passes locally.

**Comment by Ch3LL** [comment]
If it helps here is one that recently failed: https://jenkins.saltproject.io/job/pr-debian9-py3-pytest-slow/job/master/1056/

I'll keep the build
