### ISSUE TITLE
[TEST FAILURE] Random test suite timeouts

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#59496]
**Description**
Investigate random test suite timeouts
----
When closing this issue please remember to allow the linked jenkins builds to be deleted.

![image](https://user-images.githubusercontent.com/300048/107781196-87952d80-6d3f-11eb-9827-72c4c019fef9.png)

Examples:
- https://jenkins.saltproject.io/job/pr-centos7-py3-tcp-pytest/job/PR-59492/3/ 
- https://jenkins.saltproject.io/job/pr-centos8-py3-pytest/job/PR-59492/3/
- https://jenkins.saltproject.io/job/pr-ubuntu1604-py3-pycryptodome-pytest/job/PR-59492/4/
- https://jenkins.saltproject.io/job/pr-archlts-py3-pytest/job/PR-59492/4/
- https://jenkins.saltproject.io/job/pr-ubuntu1604-py3-pycryptodome-pytest/job/PR-59492/5/
- https://jenkins.saltproject.io/job/pr-centos7-py3-pytest-slow/job/master/1047/testReport/

**Comment by Ch3LL** [comment]
@s0undt3ch is this still occuring?

**Comment by s0undt3ch** [comment]
On macOS and FreeBSD, yes.

**Comment by krionbsd** [comment]
After skipping `tests/integration/states/test_file.py` FreeBSD tests work fine

**Comment by sagetherage** [comment]
@s0undt3ch is this still occurring on Mac? I think it is.
