### ISSUE TITLE
[BUG] beacons/__init__.py appending instead of update

### ISSUE THREAD

**Issue by ShaneHutter** [saltstack/salt#59506]
**Description**
Salt minions are throwing this error:
```
2021-02-16 10:11:20,906 [salt.minion      :2879][CRITICAL][20902] The beacon errored: 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 2877, in handle_beacons
    beacons = self.process_beacons(self.functions)
  File "/usr/lib/python3.6/site-packages/salt/minion.py", line 516, in process_beacons
    b_conf, self.opts["grains"]
  File "/usr/lib/python3.6/site-packages/salt/beacons/__init__.py", line 75, in process
    b_config[mod].append({"_beacon_name": mod})
AttributeError: 'dict' object has no attribute 'append'
```
It looks like /usr/lib/python3.6/site-packages/salt/beacons/\_\_init\_\_.py is attempting to append a value to this b_config[mod] dictionary, instead of updating the dictionary.

```
 75             b_config[mod].append({"_beacon_name": mod})
```

Unless b_config[mod] is a list of individual dictionaries, which it very well may be given the layout of a yaml based config for a beacon, this should be an update() not append()

**Setup**
I have an empty /etc/salt/minion.d/beacons.conf on the minion.
```
beacons:
  beacons: {}
```
Perhaps the empty dictionary here is causing the error?

**Expected behavior**
This error should not be thrown if updating the dict

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.9.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: 0.28.1
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 0.28.0
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.11.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Comment by ShaneHutter** [comment]
Hi Team,

I'm just checking to see if there has been any progress with this.  On our end, we are seeing allot of spamming to syslog from this bug, and this is adding to disk IO on servers.

**Comment by ShaneHutter** [comment]
I believe this issue was occurring due to something attempting to enable presence for SaltStack Enterprise.

We've been able to fix this issue by simply removing  the beacons beacon.

On salt-master:
```
salt \* beacons.delete beacons
```

This cleared the beacons config of the empty dictionary, and stopped spamming in the logs.

**Comment by ZsBT** [comment]
I think a final solution should be to handle dict input, at least skip processing. Currently, the salt minion logs an error in every second. I have the same issue with another beacon which is not easy to delete.
