### ISSUE TITLE
[FEATURE REQUEST] Salt Cloud Proxmox Driver: parameter needed to select storage volume for disk

### ISSUE THREAD

**Issue by jdkruzr** [saltstack/salt#59528]
As far as I can tell, there is no way described here to tell the driver what storage volume it should create the disk for the instance on. https://docs.saltproject.io/en/latest/topics/cloud/proxmox.html As a result it defaults to local-lvm, which is often very bad for systems with no local storage to speak of.

**Comment by mthibaut** [comment]
It is possible to set the default storage using the storage parameter for both qemu and lxc, see [https://pve.proxmox.com/pve-docs/api-viewer/index.html#/nodes/{node}/qemu](url).

However this is not documented in the salt documentation.
