### ISSUE TITLE
Salt Windows lgpo.set says it succesfully set group policy, but no values are set on the client.

### ISSUE THREAD

**Issue by drenriza** [saltstack/salt#59550]
I am quite new to SaltStack and this is my first bug report, i hope i do things at the correct place and in the right order, if i havent please let me know for the future.

### Description of Issue
When creating a wsus.sls state file and using the lgpo.set to set a group policy for **Specify intranet Microsoft update service location** i get the following result

> winmin1:
> ----------
>           ID: wsus_policy
>     Function: lgpo.set
>       Result: True
>      Comment: The following policies changed:
>               Specify intranet Microsoft update service location
>      Started: 11:12:17.430542
>     Duration: 2969.584 ms
>      Changes:
>               ----------
>               new:
>                   ----------
>                   Computer Configuration:
>                       ----------
>                       Specify intranet Microsoft update service location:
>                           ----------
>                           Set the alternate download server:
>                               http://MyWsusServerIP:8530
>                           Set the intranet statistics server:
>                               http://MyWsusServerIP:8530
>                           Set the intranet update service for detecting updates:
>                               http://MyWsusServerIP:8530
> 
> Summary for winmin1
> ------------
> Succeeded: 1
> Failed:    0
> ------------

### Setup
```
/srv/pillar/dev/wsus.sls
wsusserver: 'http://MyWsusServerIP:8530'
```

```
/srv/salt/dev/states/wsus.sls
wsus_policy:
  lgpo.set:
    - computer_policy:
        Specify intranet Microsoft update service location:
          Set the intranet update service for detecting updates: {{ pillar.get('wsusserver') }}
          Set the intranet statistics server: {{ pillar.get('wsusserver') }}
          Set the alternate download server: {{ pillar.get('wsusserver') }}
          CorpWUFillEmptyContentUrls: True
```

**CorpWUFillEmptyContentUrls** is a Salt internal alias (as i understand it) for the checkbox "**download files with no Url in the metadata if alternate download server is set**" and in Salt must be set if you set "**Set alternate download server**"

After the salt minion, have "successfully" applied the Group Policy and check
`(CMD) gpresult /Scope Computer /v`
No Group Policy has been applied under **Administrative Templates**

In the Windows Registry
`Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate`
I see that no values has been sat for the Group Policy

I dont know if this is relevant or not, but i would expect that when i check the Group Policy with the Windows GUI through RDP, that the policy would have been enabled and set under `Computer Configuration\Administrative Templates\Windows Components\Windows Update\Specify Intranet Microsoft update service location` but this is not the case.

If i set the Group Policy through the Windows GUI, i see expected values in both
`(CMD) gpresult /Scope Computer /v` and `Computer\HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate`

### Steps to Reproduce Issue
Ubuntu 20.04 LTS clean install
[deb http://repo.saltstack.com/py3/ubuntu/20.04/amd64/latest focal main](url)
`$ apt-get update && apt-get upgrade`
`$ apt-get install salt-master`

Windows WSUS server
[https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019?filetype=ISO](url)
Server roles: Windows Server Update Services.
Select: Add features that are required for Windows Server Update Services

Windows Client
[https://www.microsoft.com/en-us/evalcenter/evaluate-windows-server-2019?filetype=ISO](url)
Server roles: None
External packages installed: Salt-Minion-3002-2-Py3-x86-Setup

Windows WSUS server 2019, Windows client server 2019, SaltStack master Ubuntu 20.04 are all in the same virtual (virtualbox Version 6.1.16 r140961 (Qt5.6.2) environment within in the same bridged network 192.168.x.x

No connectivity issues between the VM's.

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Salt Master**

> Salt Version:
>           Salt: 3002.2
> 
> Dependency Versions:
>           cffi: Not Installed
>       cherrypy: Not Installed
>       dateutil: 2.7.3
>      docker-py: Not Installed
>          gitdb: 2.0.6
>      gitpython: 3.0.7
>         Jinja2: 2.10.1
>        libgit2: Not Installed
>       M2Crypto: Not Installed
>           Mako: Not Installed
>        msgpack: 0.6.2
>   msgpack-pure: Not Installed
>   mysql-python: Not Installed
>      pycparser: Not Installed
>       pycrypto: Not Installed
>   pycryptodome: 3.6.1
>         pygit2: Not Installed
>         Python: 3.8.5 (default, Jul 28 2020, 12:59:40)
>   python-gnupg: 0.4.5
>         PyYAML: 5.3.1
>          PyZMQ: 18.1.1
>          smmap: 2.0.5
>        timelib: Not Installed
>        Tornado: 4.5.3
>            ZMQ: 4.3.2
> 
> System Versions:
>           dist: ubuntu 20.04 focal
>         locale: utf-8
>        machine: x86_64
>        release: 5.4.0-65-generic
>         system: Linux
>        version: Ubuntu 20.04 focal

**Salt minion**

> winmin1:
>     Salt Version:
>               Salt: 3002.2
> 
>     Dependency Versions:
>               cffi: 1.12.2
>           cherrypy: 17.4.1
>           dateutil: 2.8.0
>          docker-py: Not Installed
>              gitdb: 2.0.5
>          gitpython: Not Installed
>             Jinja2: 2.10.1
>            libgit2: Not Installed
>           M2Crypto: Not Installed
>               Mako: 1.0.7
>            msgpack: 1.0.0
>       msgpack-pure: Not Installed
>       mysql-python: Not Installed
>          pycparser: 2.19
>           pycrypto: Not Installed
>       pycryptodome: 3.9.8
>             pygit2: Not Installed
>             Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
>       python-gnupg: 0.4.4
>             PyYAML: 5.3.1
>              PyZMQ: 18.0.1
>              smmap: 2.0.5
>            timelib: 0.2.4
>            Tornado: 4.5.3
>                ZMQ: 4.3.1
> 
>     System Versions:
>               dist:
>             locale: cp1252
>            machine: AMD64
>            release: 2019Server
>             system: Windows
>            version: 2019Server 10.0.17763 SP0

Thanks in advance

**Comment by obi-juan-syn** [comment]
Same issue here #57546

**Comment by twangboy** [comment]
Just tried the following state on a 2016 Server. It set the policy as expected:
```
configure_windows_update:
  lgpo.set:
    - computer_policy:
        CorpWuURL:
        {% set policy_info = salt["lgpo.get_policy_info"]("CorpWuURL", "machine") %}
        {% for element in policy_info["policy_elements"] %}

          {% if element["element_id"] == "CorpWUContentHost_Name" %}
          CorpWUContentHost_Name: ""
          {% endif %}

          {% if element["element_id"] == "CorpWUFillEmptyContentUrls" %}
          CorpWUFillEmptyContentUrls: False
          {% endif %}

          {% if element["element_id"] == "CorpWUStatusURL_Name" %}
          CorpWUStatusURL_Name: "http://10.27.79.56:8530"
          {% endif %}

          {% if element["element_id"] == "CorpWUURL_Name" %}
          CorpWUURL_Name: "http://10.27.79.56:8530"
          {% endif %}

          {% if element["element_id"] == "SetProxyBehaviorForUpdateDetection" %}
          SetProxyBehaviorForUpdateDetection: Only use system proxy for detecting updates (default)
          {% endif %}

          {% if element["element_id"] == "CorpWUDoNotEnforceEnterpriseTLSCertPinningForUpdateDetection" %}
          CorpWUDoNotEnforceEnterpriseTLSCertPinningForUpdateDetection: False
          {% endif %}

        {% endfor %}

        AutoUpdateCfg:
        {% set policy_info = salt["lgpo.get_policy_info"]("AutoUpdateCfg", "machine") %}
        {% for element in policy_info["policy_elements"] %}

          {% if element["element_id"] == "AutoUpdateMode" %}
          AutoUpdateMode: "3 - Auto download and notify for install"
          {% endif %}

          {% if element["element_id"] == "AutoUpdateAutomaticMaintenanceEnabled" %}
          AutoUpdateAutomaticMaintenanceEnabled: False
          {% endif %}

          {% if element["element_id"] == "AutoUpdateSchDay" %}
          AutoUpdateSchDay: "0 - Every day"
          {% endif %}

          {% if element["element_id"] == "AutoUpdateSchTime" %}
          AutoUpdateSchTime: "03:00"
          {% endif %}

          {% if element["element_id"] == "AllowMUUpdateServiceId" %}
          AllowMUUpdateServiceId: False
          {% endif %}

          {% if element["element_id"] == "AutoUpdateSchEveryWeek" %}
          AutoUpdateSchEveryWeek: True
          {% endif %}

          {% if element["element_id"] == "AutoUpdateSchFirstWeek" %}
          AutoUpdateSchFirstWeek: False
          {% endif %}

          {% if element["element_id"] == "AutoUpdateSchSecondWeek" %}
          AutoUpdateSchSecondWeek: False
          {% endif %}

          {% if element["element_id"] == "AutoUpdateSchThirdWeek" %}
          AutoUpdateSchThirdWeek: False
          {% endif %}

          {% if element["element_id"] == "AutoUpdateSchFourthWeek" %}
          AutoUpdateSchFourthWeek: False
          {% endif %}

        {% endfor %}
```
I will attempt on a 2019 Server...
The state applies successfully... but just to check I removed the registry keys and ran it again...
The registry keys were not created. However, after running `gpupdate` the registry keys were created. So, the keys will be created once the machine applies the policy.

**Comment by drenriza** [comment]
Thanks for taking the time to look into the issue twangboy.

In my own setup i also tried running `gpupdate` after Salt had applied the policy, but it did not make a difference, my registry was not populated with my group policy values and my Salt Minion reports to my Salt Master that all policies are in the correct state.

**Comment by drenriza** [comment]
Updated **Steps to Reproduce Issue** section

**Comment by drenriza** [comment]
If we wont break any Microsoft licens agreements, i dont see any reason as to why i would not be able to share the entire virtualbox environment with all three machines.

- SaltStack master
- SaltStack minion
- MS WSUS

**Comment by drenriza** [comment]
I have played around with it some more, and when i run my state.apply with my pillar information, nothing is written to

> C:\Windows\System32\GroupPolicy\Machine\Registry

### _IF_ i create my policy with "Edit Group Policy" interface, an entry is written into the above file, and this updates the registry database when gpupdate is run through the command line.

**Comment by drenriza** [comment]
@twangboy wake up, i have something for you @sagetherage @obi-juan-syn 
SaltStack minion versions
Salt-Minion-3002.2-Py3-x86-Setup.exe: Does not work
Salt-Minion-3002.5-Py3-AMD64-Setup.exe: Works

With Salt-Minion-3002.5-Py3-AMD64-Setup

`salt 'winmin1' state.apply`

 i get the following result from the minion
```
winmin1:
----------
          ID: wsus_policy
    Function: lgpo.set
      Result: True
     Comment: The following policies changed:
              Specify intranet Microsoft update service location
     Started: 13:59:18.362061
    Duration: 6253.561 ms
     Changes:
              ----------
              new:
                  ----------
                  Computer Configuration:
                      ----------
                      Specify intranet Microsoft update service location:
                          ----------
                          Download files with no Url in the metadata if alternate download server is set.:
                              True
                          Set the alternate download server:
                              http://192.168.1.108:8530
                          Set the intranet statistics server:
                              http://192.168.1.108:8530
                          Set the intranet update service for detecting updates:
                              http://192.168.1.108:8530
              old:
                  ----------
                  Computer Configuration:
                      ----------
                      Specify intranet Microsoft update service location:
                          Not Configured

Summary for winmin1
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:   6.254 s
```
But this time my Windows Group Policy manager (GUI) actually enables the policy, The file in C:\Windows\System32\GroupPolicy\Machine\Registry gets populated and my Windows Registry also gets populated.

So there is a bug between the two versions of the salt minion.

As a side note, the minion version Salt-Minion-3002.2-Py3-x86-Setup.exe also cannot process the commands
`salt 'winmin1' reg.read_value HKEY_LOCAL_MACHINE 'SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate' 'SusClientId'`

`salt 'winmin1' cmd.powershell 'Get-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate -Name SusClientId'`

or

`salt 'winmin1' cmd.powershell 'Get-ItemProperty -Path Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate -Name SusClientId'`

This works with no issues in Salt-Minion-3002.5-Py3-AMD64-Setup.exe

**Comment by drenriza** [comment]
Does this than mean that AMD64 will have the same problems on Windows 2016 servers or earlier and x86 will be the version on those systems that works?

I dont have a Windows server 2016 or earlier so i cannot test.

**Comment by twangboy** [comment]
So, 32bit minion will write all registry values in the 32bit portion of the registry... and in the 32bit portion of system (SysWOW64). I'm not sure how that affects 64bit machines. It is recommended that you match the bitness of your system to the installer. I can't think of a good reason to run 32bit Salt on 64bit Windows.

**Comment by twangboy** [comment]
I should have noticed that you were running the 32bit minion on a 64bit host.

**Comment by drenriza** [comment]
@twangboy Thanks for your reply, i am by no means a Windows or SaltStack guru, but i have been tasked with getting to know these systems. If 32bit vs 64bit is crucial to the salt minion as to if it can fail or sucessfully do a job, why is it not mentioned anywhere in for example [https://docs.saltproject.io/en/getstarted/](url) ? I cant imagine that i am the only human being in the world who has done this.

Why does the install process of the salt minion not make aware that installing a incompatable minion can have issues with for example the windows registry?

Why does the minion try to execute commands against a registry it is not compatable with?

It seems like there should be safe guards to avoid ending in this situation, but there isint.
