### ISSUE TITLE
Salt Windows minions uses outdated Python (3.7.4 at best)

### ISSUE THREAD

**Issue by szjur** [saltstack/salt#59592]
**Description**
Hi,

Is there a valid reason for the Windows minion to use Python 3.7.4 at best, while there is 3.7.10 already? _Actually as of 23rd Feb 2021 the latest Windows packages available for download from python.org seem to be 3.7.9 but that's still 5 minor releases ahead._ That doesn't look good in security audits. It is not that hard to change it but since the build process gets it from https://repo.saltstack.com/windows/dependencies/64/ and it's not there this requires more tweaks.

**Comment by xeacott** [comment]
There isn't a specific reason that comes to mind... It may be a year and some months old, but there doesn't seem to be any CVE/security related issues with that version of python. Are there any specific reasons we should be upgrading minor releases?

**Comment by szjur** [comment]
Well each minor release usually fixes a number of bugs, including security. The latter are listed in Security sections of https://docs.python.org/3.7/whatsnew/changelog.html#changelog. The reason for upgrading is that security scanners may detect the outdated version as a threat. Anyway, a minimally skilled user can rebuild it with a Python version of their choice, so I'm not that fussed.

**Comment by xeacott** [comment]
Chatted about this question, and realistically there isn't anything stopping us from bumping the minor release version, we just test and have been testing with 3.7.4. Perhaps we can do an experimental build with 3.7.9, run our tests against it, and see what happens. I'll keep this ticket open and mark it as Si.

**Comment by xeacott** [comment]
Hi @szjur we'll be upgrading to python 3.8 soon to address this ticket as well as https://github.com/saltstack/salt/issues/59865

**Comment by szjur** [comment]
Great news, thanks!

**Comment by sagetherage** [comment]
the PR https://github.com/saltstack/salt/pull/59870 is merged and will be released in Silicon - closing
