### ISSUE TITLE
[WEBSITE] saltproject.io website bugs: broken links on main page

### ISSUE THREAD

**Issue by TathanT** [saltstack/salt#59608]
**Description**
Links in the **Learn Salt** section of https://saltproject.io are broken.

**Setup**
OS: Ubuntu 20.04
Browser: Firefox 85.0.1

**Steps to Reproduce the behavior**
Browse to https://saltproject.io and scroll down to the **Learn Salt** section. Click on any of the following links:
* Salt tutorials
* documentation

**Expected behavior**
Browse to https://saltproject.io and scroll down to the **Learn Salt** section. When you click the **salt tutorials** link, you should be directed to https://docs.saltproject.io/en/getstarted/ but instead are directed to [https://saltproject.io/%E2%80%9Dhttps:/docs.saltproject.io/en/getstarted/](https://saltproject.io/%E2%80%9Dhttps:/docs.saltproject.io/en/getstarted/) .
When you click the **documentation** link, you should be directed to [https//docs.saltproject.io/en/latest/](https//docs.saltproject.io/en/latest/) but is instead directed to [https://https//docs.saltproject.io/en/latest/](https://https//docs.saltproject.io/en/latest/).

**Screenshots**
Section of the site to navigate to:
![image](https://user-images.githubusercontent.com/13752924/109079537-4d6f4880-76bc-11eb-8626-7f4fca7a1097.png)

After clicking on the **Salt tutorials** link:
![image](https://user-images.githubusercontent.com/13752924/109079672-827b9b00-76bc-11eb-9a6b-f11b6c9d721f.png)

After clicking on the **documentation** link:
![image](https://user-images.githubusercontent.com/13752924/109079791-ae971c00-76bc-11eb-91d2-422ebd0f4b57.png)

**Comment by sagetherage** [comment]
@TathanT please clear your cache and cookies and let me know if you are seeing the in website links no resolve and YouTube links open in a new window. Thank you for reporting the errors!

**Comment by TathanT** [comment]
After clearing cache and cookies, the two broken links work, however, they do not open a new tab or a new window. The **Salt Project YouTube channel** link opens YouTube in a new window but does not load any page except the main feed page with this url [https://www.youtube.com/?gl=US&tab=k1%2F](https://www.youtube.com/?gl=US&tab=k1%2F). The Salt Workshop video link works and opens the link in a new tab.

**Comment by sagetherage** [comment]
Yes, the links that go to other part of the saltproject.io site I left as simple nav - so the docs, tutorials will route you to those pages, or not open in a new windows. The YouTube opens in a new windows, but isn't going to anything specific, I believe that is the intent, but it does seem odd. I will find out what it should be and update. Thank you for the continual feedback!

**Comment by TathanT** [comment]
You're welcome, and thanks for the timely response. If the YouTube link isn't the issue and it's just with the account, I think this issue can be closed then.
