### ISSUE TITLE
Saltstack docker images out of date

### ISSUE THREAD

**Issue by jsandas** [saltstack/salt#59624]
I use the official saltstack docker images for my salt masters.  I am trying to update them to the latest version (3002.5), but the most recent docker image available is 3002.2.  It appears that all the 300* docker images are out of date.  Is there an ETA for update docker images?

**Comment by bryceml** [comment]
I released them over the weekend.

**Comment by jsandas** [comment]
I see that now.  Thank you.

**Comment by sagetherage** [comment]
https://hub.docker.com/r/saltstack/salt/tags?page=1&ordering=last_updated&name=3002.5
