### ISSUE TITLE
[DOCS] Link to Doug Hellmann's blog in Salt Coding Style guide is broken

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#59650]
**Description**
The link to Doug Hellmann's blog entry on The Performance Impact of Using dict() Instead of {} in CPython 2.7 is broken in the Salt Coding Style guide

**Suggested Fix**
Update link to https://doughellmann.com/posts/the-performance-impact-of-using-dict-instead-of-in-cpython-2-7-2/

**Type of documentation**
Salt Coding Style guide

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/development/conventions/style.html#dictionaries

**Additional context**

**Comment by sagetherage** [comment]
thank you! I will attempt to push that PR through the testing
