### ISSUE TITLE
[BUG]Pillar.get not working

### ISSUE THREAD

**Issue by macejko8** [saltstack/salt#59668]
**Description**

I have an issue of getting configured values from sls file.

I am trying to run this command:

sudo salt sw pillar.get conf.vlan............but getting only this:

sw:

I have tried also sudo salt sw pillar.get conf..........but it is the same

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

Here is my conf.sls file which is saved in /etc/salt/pillar

conf.vlan:
  - 10
  - 20
  - 30

It is added also in top.sls file under 'sw' minion id. Master config file is updated with file roots  and pillar roots paths.

Due to this I have also issues w/ creating Jinja configuration templates where I am getting error:

ID conf.vlan in SLS conf is not a dictionary

Any suggetions what could be the issue?

Thanks,
BR
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by macejko8** [comment]
I get managed to pillar.get working but data compilation using states is still failing, I have changed conf.sls pillar file to ntp.sls and file /etc/salt/pillar/ntp.sls looks like this:
ntp.servers:
  - 11.1.1.1
  - 2.2.2.2

this is my Jinja template /etc/salt/states/ntp/templates/ntp.jinja:

{%- for server in servers %}
ntp {{ server }}
{%- endfor %}


and my inti.sls file /etc/salt/states/ntp/init.sls:

ntp_example:
  netconfig.managed:
    - template_name: salt://ntp/templates/ntp.jinja
    - debug: true
    - servers: {{ salt.pillar.get('ntp.servers') }} 

I am getting the following error while trying run sudo salt sw state.sls ntp

Error:
sw:
    Data failed to compile:
----------
    ID ntp.servers in SLS ntp is not a dictionary

**Comment by sagetherage** [comment]
@macejko8 can you please give a versions report?

Provided by running salt --versions-report. Please also mention any differences in master/minion versions

**Comment by macejko8** [comment]
Master and minion are on the same machine, here are the outputs:

salt-master --versions-report
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-66-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver




----------------------------------------------------------

salt-minion --versions-report
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.0.7
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-66-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver

**Comment by sagetherage** [comment]
@macejko8 please mention me if this did not solve your problem, closing for now.
