### ISSUE TITLE
[TEST FAILURE] FreeBSD Test Failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#59675]
tests.pytests.integration.master.test_clear_funcs.test_pub_not_allowed
tests.pytests.integration.master.test_clear_funcs.test_clearfuncs_config
tests.pytests.integration.master.test_clear_funcs.test_fileroots_read
tests.pytests.integration.proxy.test_simple.test_state_highstate
tests.pytests.scenarios.setup.test_install.test_sdist[USE_STATIC_REQUIREMENTS=1]
tests.pytests.scenarios.setup.test_install.test_sdist[USE_STATIC_REQUIREMENTS=0]
tests.pytests.scenarios.setup.test_install.test_setup_install[USE_STATIC_REQUIREMENTS=1]
tests.pytests.scenarios.setup.test_install.test_setup_install[USE_STATIC_REQUIREMENTS=0]
tests.unit.utils.test_timeout.WaitForTests.test_wait_for_with_big_step

From https://jenkins.saltproject.io/job/pr-freebsd122-py3-pytest-slow/job/master/414/

**Comment by sagetherage** [comment]
Looks like these are passing now
