### ISSUE TITLE
[TEST FAILURE] MacOS 10.4 Mojave test failures in Netapi SSH tests

### ISSUE THREAD

**Issue by barneysowood** [saltstack/salt#59683]
**Description**

Seeing segfaults in tests in tests/integration/netapi/test_client.py::NetapiSSHClientTest and tests/integration/netapi/test_client.py::NetapiSSHClientAuthTest in both my own PR and another PR

* https://github.com/saltstack/salt/pull/59622
  * https://jenkins.saltproject.io/job/pr-macosxmojave-py3-pytest/job/PR-59622/3/
  * `I, [2021-02-26T03:14:47.008697 #65343]  INFO -- py3-macosx-mojave: tests/integration/netapi/test_client.py::NetapiSSHClientTest::test_shell_inject_ssh_options Fatal Python error: Segmentation fault`
 
* https://github.com/saltstack/salt/pull/59663
  * https://jenkins.saltproject.io/job/pr-macosxmojave-py3-pytest/job/PR-59663/1/
  * `I, [2021-03-01T09:37:29.081850 #38997]  INFO -- py3-macosx-mojave: tests/integration/netapi/test_client.py::NetapiSSHClientAuthTest::test_ssh_auth_token Fatal Python error: Segmentation fault`

Note that in both cases, the tests that segfault are *not* the tests added by the PRs

**Steps to Reproduce the behavior**
Submit PR that causes SSH tests in tests/integration/netapi/test_client.py to be run on MacOS Mojave

**Comment by barneysowood** [comment]
Just to confirm it looks like this is now fixed, that's run successfully in https://jenkins.saltproject.io/job/pr-macosxmojave-py3-pytest/job/PR-59622/7/.

Happy for this to be closed if there's nothing further required on it.

**Comment by Ch3LL** [comment]
Im good closing it, but will re-open if we see it fail again, because we are trying to tackle some flaky tests. I personally haven't seen this one fail anywhere else, so closing for now.
