### ISSUE TITLE
[DOCS] Salt Coding Style Guide needs review

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#59700]
**Description**

The Salt Coding Style Guide needs review. Since the last update in 2019, the code base has evolved a bit.

Example:
- [Salt Coding Style Guide: Formatting Strings](https://docs.saltproject.io/en/master/topics/development/conventions/style.html#formatting-strings)

This is out-dated, as `pre-commit` now _removes_ any indices it finds in strings like that. Also, it says we need to do so with this justification:

> Make sure to use indices or identifiers in the format brackets, since empty brackets are not supported by python 2.6.

The last version of Salt to support Python 2.x is `v3000.x`, which reaches end of **Phase 3** support at the end of August, 2021 (per the [Support Policy](https://saltproject.io/salt-platform-support/) page).

**Suggested Fix**

Review the coding style guide, and fix areas such as the above item.

**Type of documentation**

Salt Documentation

**Location or format of documentation**

- HTML: https://docs.saltproject.io/en/master/topics/development/conventions/style.html#formatting-strings
- Source rst file: https://github.com/saltstack/salt/blob/master/doc/topics/development/conventions/style.rst

**Comment by ggiesen** [comment]
It actually looks like @s0undt3ch has already fixed the string formatting in master (shame on me for looking at 3002.5 docs!) in 7528e42fcf54a28a914a43a80b1a39a007924b9a

**Comment by ScriptAutomate** [comment]
> It actually looks like @s0undt3ch has already fixed the string formatting in master (shame on me for looking at 3002.5 docs!) in [7528e42](https://github.com/saltstack/salt/commit/7528e42fcf54a28a914a43a80b1a39a007924b9a)

This is a consistent problem with our docs UX at the moment because of things being versioned that shouldn't be, so this will continue to happen for users (and Salt contribs/maintainers, alike). Since all topics should only be under `master`, and the reference guide should be versioned. We're hoping to resolve this with changes coming from [`salt-user-guide`](https://gitlab.com/saltstack/open/docs/salt-user-guide) sometime this year, as we merge the docsets.

**Comment by ScriptAutomate** [comment]
I'm going to close this issue, since the last update was in November 2020. It can have a final review upon merge with the `salt-user-guide` when the time comes.
