### ISSUE TITLE
[FEATURE REQUEST] Function to get file properties in Windows

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#59702]
**Is your feature request related to a problem? Please describe.**
Get file properties (in particular I was looking for the file version properties) in WIndows

**Describe the solution you'd like**
Function added to win_file.py

**Describe alternatives you've considered**
Custom module attached. GOt the code from stackoverflow site.

[mywin_file (copy).txt](https://github.com/saltstack/salt/files/6080935/mywin_file.copy.txt)

**Comment by xeacott** [comment]
Hi @amalaguti would you like to create a PR with these proposed changes?

**Comment by amalaguti** [comment]
@xeacott @twangboy created PR :)
