### ISSUE TITLE
[BUG] (?) regression (!)(?) in 3002.5 for linux yum pkg version numbers - AttributeError: 'float' object has no attribute 'lstrip'

### ISSUE THREAD

**Issue by TheBigBear** [saltstack/salt#59705]
**Description**
On a newly updated to 3002.5 salt master trying to install a specific version of salt-minion to the centos minions now returns an error. Regression? Pretty sure this worked before 3002.5?  

**Setup**
on a centos 8 salt master with a new upgrade to version 3002.5 trying to deploy the latest salt-minion to centos Linux minions. 

**Steps to Reproduce the behavior**
```salt 'mycentosminion1' pkg.install salt-minion version=3002.5```

now on newly upgraded salt master3002.5 gives the following error:
```
File "/usr/lib/python3.6/site-packages/salt/modules/yumpkg.py", line 1521, in install
        version_num = version_num.lstrip("=")
    AttributeError: 'float' object has no attribute 'lstrip'
```

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**
Here is me trying to see if single quoting the version number helps, but it does not. But on the other hand trying to upgrade the minions on windows still works. 
```
salt 'mycentosminion1' pkg.install salt-minion version=3002.5 
mycentosminion1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1890, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1846, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/yumpkg.py", line 1521, in install
        version_num = version_num.lstrip("=")
    AttributeError: 'float' object has no attribute 'lstrip'
ERROR: Minions returned with non-zero exit code
```
```
salt 'mycentosminion1' pkg.install salt-minion version='3002.5'
mycentosminion1:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1890, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1846, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3.6/site-packages/salt/executors/direct_call.py", line 12, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/modules/yumpkg.py", line 1521, in install
        version_num = version_num.lstrip("=")
    AttributeError: 'float' object has no attribute 'lstrip'
ERROR: Minions returned with non-zero exit code
```

**Comment by xeacott** [comment]
Booted up a centos box and tested this out... let me see if I can find the last working version

**Comment by xeacott** [comment]
@TheBigBear Went all the way back to salt 3000 and the issue is still persisting. So definitely replicating it, just not sure how far back the issue is. Nonetheless seems to be a pretty quick fix so I'll get one up here soon.
