### ISSUE TITLE
[WEBSITE] use security.txt standard on homepage 

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59729]
use the security.txt proposed standard on saltproject.io homepage

https://en.wikipedia.org/wiki/Security.txt

```
$ curl -L google.com/.well-known/security.txt
Contact: https://g.co/vulnz
Contact: mailto:security@google.com
Encryption: https://services.google.com/corporate/publickey.txt
Acknowledgements: https://bughunter.withgoogle.com/
Policy: https://g.co/vrp
Hiring: https://g.co/SecurityPrivacyEngJobs
# Flag: BountyCon{075e1e5eef2bc8d49bfe4a27cd17f0bf4b2b85cf}
```

**Comment by ScriptAutomate** [comment]
Information has been submitted to team managing the https://saltproject.io within their internal ticketing / project-planning. Ticket will be closed, as website feedback (specifically for https://saltproject.io website, not for the subdomains such as https://docs.saltproject.io or https://repo.saltproject.io) is requested to go through the `Contact Us` method listed on https://saltproject.io, which is:

- Send feedback, feature requests, bugs, etc. to saltproject@vmware.com
- OR reach out the @janae417 on the [Salt Community Slack](https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg) (she is `@Janae` on there)
