### ISSUE TITLE
[BUG] 3002.5 Sensitive information entered by users is displayed in the salt process.

### ISSUE THREAD

**Issue by CriProphet** [saltstack/salt#59740]
**Description**
The information entered by the user, including sensitive information such as passwords, is displayed in the memory. The path is as follows:/proc/salt-pid(process id)

**Setup**
/proc/salt-pid(process id)

**Expected behavior**
Do not print sensitive information entered by users in the salt stack process.

**Versions Report**
salt 3002.2

```
PASTE HERE
```
</details>

**Comment by sagetherage** [comment]
@CriProphet Salt v3002.2 is a vulnerable version can you upgrade to 3002.5 and do you still see this?

**Comment by CriProphet** [comment]
Currently, no upgrade has been performed and the upgrade verification is being performed. Can you confirm that the memory sensitive information problem has been fixed in version 3002.5?

**Comment by CriProphet** [comment]
I've upgraded to version 3002.5, but I still have a problem with the destruction of sensitive information in memory taking too long.

**Comment by sagetherage** [comment]
@CriProphet thank you, moving this back into triage to be reproduced to confirm.

**Comment by dwoz** [comment]
@CriProphet I don't understand this ticket. Can you please provide more information on the issue you are having?

**Comment by sagetherage** [comment]
@CriProphet can you give more details, here? Steps to reproduce, expected behavior, etc. please?

**Comment by sagetherage** [comment]
@CriProphet we have reviewed this several times and need more information from you, please. Can you please give more details and sanitize the results so we may help you, here?

**Comment by CriProphet** [comment]
@sagetherage I updated to 3002.5 and found no problems.

**Comment by sagetherage** [comment]
updated the labels as an experiment - closing as resolved in v3002.5
