### ISSUE TITLE
[BUG] 3002.5 String encoding error in boto3_route53

### ISSUE THREAD

**Issue by major0** [saltstack/salt#59755]
**Description**
The `aws_encode()` method in `boto3_route53` has some Python2 assumptions that break in Python3.

```
[ERROR   ] Couldn't encode saltstack.org. using either 'unicode_escape' or 'idna' codecs
Error running 'boto3_route53.find_hosted_zone': cannot use a string pattern on a bytes-like object
```

The bug appears to be a result of this line of code:
```
        ret = re.sub(r"\\x([a-f0-8]{2})", _hexReplace, x.encode("unicode_escape"))
```

In Python2 the `unicode_escape` returned a string, in Python3 it returns a byte array.

Decoding the escaped string into latin-1 appears to resolve the issue:
```
        ret = re.sub(r"\\x([a-f0-8]{2})", _hexReplace, x.encode("unicode_escape").decode("latin-1"))
```

**Setup**
Reprodicible from from the CLI w/out any special configurations.

**Steps to Reproduce the behavior**
```
salt-call  boto3_route53.find_hosted_zone Name=saltstack.org.
```

**Expected behavior**
Expected a response about valid or invalid zones.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
alt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: aarch64
       release: 5.4.0-1037-aws
        system: Linux
       version: Ubuntu 20.04 focal 
```
</details>

**Additional context**

**Comment by pruiz** [comment]
I would better add a 'b' prefix to regex expression: br"\\x([a-f0-8]{2})"

**Comment by anitakrueger** [comment]
This is breaking all our states to manage Route53 records.

I've tried @major0's workaround in the module, but then it borks in the `_aws_decode` with the following error:
```
                File "/usr/lib/python3.6/site-packages/salt/modules/boto3_route53.py", line 1029, in get_resource_records
                  rr["Name"] = _aws_decode(rr["Name"])
                File "/usr/lib/python3.6/site-packages/salt/modules/boto3_route53.py", line 939, in _aws_decode
                  return x.decode("idna")
              AttributeError: 'str' object has no attribute 'decode'
```

Any ideas?

**Comment by anitakrueger** [comment]
@pruiz This seems to work:
```
        ret = re.sub(rb"\\x([a-f0-8]{2})", _hexReplace, x.encode("unicode_escape"))
```
Unfortunately now the module doesn't find my private Route53 domain :(

**Comment by pruiz** [comment]
@anitakrueger unfortunately I am using a forked version of boto3 modules/states with additional features, so I dont know if I may help, but do you have en issue detailing your new problem?

**Comment by anitakrueger** [comment]
@pruiz What seems to happen is that in the get_hosted_zones_by_domain function the comparison of Names at https://github.com/saltstack/salt/blob/76e50885b07621e9e4c16bc3f1ebc16c93983b90/salt/modules/boto3_route53.py#L261 fails.
```
        if z["Name"] == aws_encode(Name)
```

In my log it looks like this:
```
2021-09-25 08:26:22,153 [salt.loaded.int.module.boto3_route53                  ][DEBUG   ] AWS-encoded result for mydomain.com.: b'mydomain.com.'
```

If I remove the aws_encode() function from there, it finds the hosted zone just fine.

Unfortunately, that seems to cause issues down the line in `boto3_route53.rr_present`. 
```
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3.6/site-packages/salt/state.py", line 2154, in call
                  *cdata["args"], **cdata["kwargs"]
                File "/usr/lib/python3.6/site-packages/salt/loader.py", line 2106, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3.6/site-packages/salt/states/boto3_route53.py", line 766, in rr_present
                  profile=profile,
                File "/usr/lib/python3.6/site-packages/salt/modules/boto3_route53.py", line 1030, in get_resource_records
                  r = conn.list_resource_record_sets(**args)
                File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
                  return self._make_api_call(operation_name, kwargs)
                File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 649, in _make_api_call
                  api_params, operation_model, context=request_context)
                File "/usr/local/lib/python3.6/site-packages/botocore/client.py", line 697, in _convert_to_request_dict
                  api_params, operation_model)
                File "/usr/local/lib/python3.6/site-packages/botocore/validate.py", line 293, in serialize_to_request
                  raise ParamValidationError(report=report.generate_report())
              botocore.exceptions.ParamValidationError: Parameter validation failed:
              Invalid type for parameter StartRecordName, value: b'qa-svc-my-service.mydomain.com', type: <class 'bytes'>, valid types: <class 'str'>
```

I can't help but feel this is an issue somewhere else with either my Python version or some other pip package I have installed.

**Comment by anitakrueger** [comment]
I've just updated to the latest boto3 and botocore versions (boto3==1.18.48, botocore==1.21.48) which hasn't helped.

**Comment by anitakrueger** [comment]
This fixes my issue: https://github.com/saltstack/salt/pull/60951

**Comment by garethgreenaway** [comment]
The PR that @anitakrueger mentioned has been merged and will be available in the Phosphorus release, if this fix resolves the issue for everyone please go ahead and close this issue.  Thanks!

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity, if the issue persists once the Phosphorus release is available please feel free to open a new issue.  Thanks!
