### ISSUE TITLE
[WEBSITE] add to template meta data of posts

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59759]
### Description of Issue
Blog posts don't contain general information normally found with blog posts: timestamp of post, timestamp of last updated, etc.

this will need to be added to the theme

**Comment by ScriptAutomate** [comment]
Information has been submitted to team managing the https://saltproject.io within their internal ticketing / project-planning. Ticket will be closed, as website feedback (specifically for https://saltproject.io website, not for the subdomains such as https://docs.saltproject.io or https://repo.saltproject.io) is requested to go through the `Contact Us` method listed on https://saltproject.io, which is:

- Send feedback, feature requests, bugs, etc. to saltproject@vmware.com
- OR reach out the @janae417 on the [Salt Community Slack](https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg) (she is `@Janae` on there)
