### ISSUE TITLE
[TEST FAILURE] Flaky Test scenarios.compat.test_with_versions

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#59753]
tests.pytests.scenarios.compat.test_with_versions.test_highstate[Py3-SaltMinion==3001.4-unicode=True]

sometimes fails:

https://jenkins.saltproject.io/job/pr-ubuntu1604-py3-tcp-pytest/job/PR-59748/5/

**Comment by twangboy** [comment]
We no longer support Ubuntu 16.04. I don't see the test failing on other OS'es.

**Comment by Ch3LL** [comment]
ping @twangboy I just saw it fail again here: https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-tcp-pytest-slow/job/master/227/#showFailuresLink

**Comment by Ch3LL** [comment]
Here is another one: https://jenkins.saltproject.io/view/Freeze%20Branch%20Jobs/job/pr-centos-7-x86_64-py3-m2crypto-pytest-slow/job/freeze/119/#showFailuresLink

**Comment by sagetherage** [comment]
Re-opened, but is still flaky and may be related to the sdb tests - it needs someone to look into it, please
