### ISSUE TITLE
Salt Syndic Key Management

### ISSUE THREAD

**Issue by Coonzoba** [saltstack/salt#59765]
The master is able to reach minions throught the Syndic once authenticated to the Syndic. However, I'm having to do cmd.run to accept the minions. 

My question is;

Is there a way to manage the Syndic salt-keys directly from the master?

**Comment by sagetherage** [comment]
I asked the Core Team and they are not aware of a way to do this, looking at some of our Solution Architects to see if they know any differently.

**Comment by whytewolf** [comment]
have the syndic masters as a minion of the MoM and use [saltutil.wheel](https://docs.saltproject.io/en/3001/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.wheel) to execute [salt.wheel.key](https://docs.saltproject.io/en/3001/ref/wheel/all/salt.wheel.key.html#module-salt.wheel.key) functions.

**Comment by sagetherage** [comment]
@Coonzoba let us know if this Master of Masters explanation answers your question, if we don't hear from you we will close the ticket in due time.
