### ISSUE TITLE
[FEATURE] AMZN Linux packages for the following architecture: arm64 

### ISSUE THREAD

**Issue by bginard** [saltstack/salt#59779]
**Description of Issue**

Please provide Amazon Linux packages for the following architecture, arm64. Presently, there are only Amazon Linux packages for amd64 architecture in https://repo.saltstack.com/#amzn

**Setup**

yum configured to install Salt packages from the Saltstack yum repositories as indicated in https://repo.saltstack.com/#amzn

**Steps to Reproduce Issue**

Configure Saltstack yum repository for Amazon Linux in an Amazon Linux EC2 instance and try to install one of the components (salt-minion for example) and it fails because the repo https://repo.saltstack.com/py3/amazon/2/ is only amd64 and some of the dependencies in it are native for amd64 and not available for arm64.

**Comment by MartinEmrich** [comment]
FYI: AWS just announced Amazon Linux 2023 and their planned release/maintenance schedule: https://aws.amazon.com/de/blogs/aws/amazon-linux-2023-a-cloud-optimized-linux-distribution-with-long-term-support/

**Comment by s0undt3ch** [comment]
The 3006.0 release will have Amazon Linux 2 Arm Packages.

As for the upcoming Amazon Linux release, we also knew about it on that announcement. There are plans to at least add it to our CI/CD pipelines.

**Comment by s0undt3ch** [comment]
The commit https://github.com/saltstack/salt/commit/6bb5832616c7236f9e9d052d026ee99231284f3f in https://github.com/saltstack/salt/pull/63893 added the RHEL arm repositories to the pipelines.

**Comment by garethgreenaway** [comment]
Closed by #63893 , 3006.0RC3 has ARM packages for Red Hat variants including Amazon Linux available.
