### ISSUE TITLE
[BUG] 3000.8 state.sls_id unable to run as a scheduled job

### ISSUE THREAD

**Issue by rofuentes** [saltstack/salt#59788]
**Description**
state.sls_id failing with incorrect number of arguments when run as a scheduled job.

Here is the specific error message from the salt-minion

Mar 12 19:18:19 salt salt-minion[15904]: [ERROR   ] Unhandled exception running state.sls_id
Mar 12 19:18:19 salt salt-minion[15904]: Traceback (most recent call last):
Mar 12 19:18:19 salt salt-minion[15904]:   File "/usr/lib/python2.7/dist-packages/salt/utils/schedule.py", line 769, in handle_func
Mar 12 19:18:19 salt salt-minion[15904]:     ret['return'] = self.functions[func](*args, **kwargs)
Mar 12 19:18:19 salt salt-minion[15904]: TypeError: sls_id() takes at least 2 arguments (0 given) 

**Setup**

```
schedule:{{ pillar.master.data.dir }}:
  schedule.present:
    - function: state.sls_id
    - args:
      - {{ pillar.master.data.dir }}
      - {{ sls }},git
    - minutes: 15
```

**Steps to Reproduce the behavior**
I can successfully run the command from the cli
`sudo salt 'salt*' state.sls_id /salt master.contents,git`

**Expected behavior**
Apply the desired salt state on a 15 minute schedule.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
# salt --versions-report
Salt Version:
           Salt: 3000.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
      docker-py: 4.2.1
          gitdb: 2.0.0
      gitpython: 2.1.1
         Jinja2: 2.9.4
        libgit2: Not Installed
       M2Crypto: 0.24.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 2.7.13 (default, Aug 22 2020, 10:03:02)
   python-gnupg: 0.3.9
         PyYAML: 3.12
          PyZMQ: 17.1.2
          smmap: 2.0.1
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.1
 
System Versions:
           dist: debian 9.13 
         locale: UTF-8
        machine: x86_64
        release: 4.9.0-15-amd64
         system: Linux
        version: debian 9.13 
```
</details>

**Additional context**

**Comment by sagetherage** [comment]
@rofuentes we no longer support Python 2.7, are you able to upgrade to a supported version of Python and still see this issue?

**Comment by rofuentes** [comment]
Ok, we have a few customizations that I am migrating to Py3. Please give me a week and I can test under same SaltStack version on Py3.

**Comment by rofuentes** [comment]
Closing this out, the error was due to a typo in our state file. `job_args` was written as `args`.
