### ISSUE TITLE
[BUG] 3002.5 lvm.present current size not calculated correctly

### ISSUE THREAD

**Issue by grimmjo** [saltstack/salt#59782]
**Description**
With the version 3002 and the changes for #55265, the current size of the lvm is not correctly calculated. 
The command `lvdisplay -c ` returns the logical volume size in sectors. 
That causes a miscalculation of the current logical volume size depending on the sector size.

**Setup**
```
vg_data-created:
  lvm.vg_present:
    - name: vg_data
    - devices: /dev/sdb

lv_data-created:
  lvm.lv_present:
    - name: lv_data
    - vgname: vg_data
    - size: 935G
    - require:
        - vg_data-created
```

**Steps to Reproduce the behavior**

Debug log:
```
[INFO    ] Running state [lv_data-created] at time 08:43:16.272746
[INFO    ] Executing state lvm.lv_present for [lv_data-created]
[INFO    ] Executing command lvdisplay in directory '/root'
[DEBUG   ] stdout:   /dev/vg_data/lv_data:vg_data:3:1:-1:1:1992294400:243200:-1:0:-1:253:1
[ERROR   ] To reduce a Logical Volume option 'force' must be True.
[INFO    ] Completed state [lv_data-created] at time 08:43:16.294345 (duration_in_ms=21.599)
```

```
root@test:~# lvdisplay -c /dev/vg_data/lv_data
  /dev/vg_data/lv_data:vg_data:3:1:-1:1:1992294400:243200:-1:0:-1:253:1

root@test:~# lvs --units g /dev/vg_data/lv_data
  LV         VG      Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_data vg_data -wi-ao---- 950.00g

root@test:~# lvs --units s /dev/vg_data/lv_data
  LV         VG      Attr       LSize       Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_data vg_data -wi-ao---- 1992294400S

root@test:~# df -ha /data/
Filesystem                      Size  Used Avail Use% Mounted on
/dev/mapper/vg_data-lv_data  935G  246G  642G  28% /data
```

**Expected behavior**

The linux_lvm module detects the correct size of the logical volume. 
Furthermore it would be nice to migrate to the commands `lvs` and `vgs` as they support json output and passing in units.

```
root@test:~# lvs --units m --reportformat json /dev/vg_data/lv_data
  {
      "report": [
          {
              "lv": [
                  {"lv_name":"lv_data", "vg_name":"vg_data", "lv_attr":"-wi-ao----", "lv_size":"972800.00m", "pool_lv":"", "origin":"", "data_percent":"", "metadata_percent":"", "move_pv":"", "mirror_log":"", "copy_percent":"", "convert_lv":""}
              ]
          }
      ]
  }
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.5

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-91-generic
        system: Linux
```
</details>

**Comment by piterpunk** [comment]
This difference is not related to LVM or the sector size conversion, the filesystem amount of 512b sectors is different than the block device amount of 512b sectors.

Here you can see the amount of 512b sectors of the filesystem `/home`:
```
# POSIXLY_CORRECT=1 df /home
Filesystem     512B-blocks      Used Available Use% Mounted on
/dev/sda7        196592680 167406624  19153632  90% /home
```
And the amount of 512b sectors of the block device `/dev/sda7`:
```
# blockdev --getsz /dev/sda7
199993122
```
The same happens to LVM block devices. The filesystem is smaller than the block device:
```
# POSIXLY_CORRECT=1 df /tmp
Filesystem              512B-blocks    Used Available Use% Mounted on
/dev/mapper/batvg02-tmp    16382832 6909952   8601256  45% /tmp
# blockdev --getsz /dev/mapper/batvg02-tmp
16777216
# lvs --unit s /dev/mapper/batvg02-tmp
  LV   VG      Attr       LSize     Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  tmp  batvg02 -wi-ao---- 16777216S
```
Filesystem will always have a smaller size than the block device. There are blocks used by the filesystem's structure itself: superblocks, inode tables, journal, group descriptors, inode and data bitmaps, etc... Those internal structures aren't available to use directly, that's why the size in `df` isn't the same of the reported by `blockdev`. But the filesystem is aware of the full block device size:
```
# dumpe2fs /dev/mapper/batvg02-tmp | grep -E "Block (count|size)"
dumpe2fs 1.46.1 (9-Feb-2021)
Block count:              2097152
Block size:               4096
# echo "2097152 * (4096 / 512)" | bc
16777216
```
The amount of 512 bytes sectors is 16777216, which is the total size of the block device used by this fileystem, the same reported by `blockdev` and by `lvs`.

As the LVM creates and manages block devices, the size used by it is related to the block device itself, not the size of the filesystem inside it, which can also change by type of filesystem or creation and tuning parameters, e.g.: putting the journal in a external device,

**Comment by grimmjo** [comment]
@piterpunk thank you for this explanation.

I think to problem is that the module relies on lvdisplay -c returning the sectors and using this value as the current size of the logical volume.

In my example lvdisplay -c returns 1992294400.
1992294400/1024/1024=1900
This is exactly the double amount of what is currently configured or the number of 512b sectors. 

This causes salt to think that it needs to shrink the volume to half of the size.

With 3001 the behavior is correct and everything works fine.

**Comment by piterpunk** [comment]
> In my example lvdisplay -c returns 1992294400.
1992294400/1024/1024=1900
This is exactly the double amount of what is currently configured or the number of 512b sectors.

The code already converts all the units to MB. The 1992294400 is divided by 2048 which results in 972800, the 935g in your state is multiplied by 1024 resulting in 957440. The logical volume size in your state needs to be 950g (950 * 1024 = 972800)

> This causes salt to think that it needs to shrink the volume to half of the size.

Not the half of size, only 15g less. Your state is trying to reduce the logical volume from 950g:
```
root@test:~# lvs --units g /dev/vg_data/lv_data
  LV         VG      Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  lv_data vg_data -wi-ao---- 950.00g
 ```
To 935g:
```
lv_data-created:
  lvm.lv_present:
    - name: lv_data
    - vgname: vg_data
    - size: 935G
    - require:
        - vg_data-created
```
As 935G is less than 950G it will give the error to you. You need to use `size: 950G` which is the size of the `lv_data` logical volume.

I use here this state to manage my `/home`:
```
home:
  lvm.lv_present:
    - vgname: batvg03
    - size: 144g
    - resizefs: True
    - require:
      - batvg03
```
The logical volume have, indeed 144g
```
root@bat:~# lvs /dev/batvg03/home 
  LV   VG      Attr       LSize   Pool Origin Data%  Meta%  Move Log Cpy%Sync Convert
  home batvg03 -wi-ao---- 144.00g
```
After running the state nothing happens, as expected:
```
local:
----------
          ID: home
    Function: lvm.lv_present
      Result: True
     Comment: Logical Volume home already present
     Started: 19:10:42.647126
    Duration: 68.095 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:  68.095 ms
```
But the `df` shows 141G:
```
root@bat:~# df -h /home
Filesystem                Size  Used Avail Use% Mounted on
/dev/mapper/batvg03-home  141G  112G   22G  84% /home
```
If I change the state to:
```
home:
  lvm.lv_present:
    - vgname: batvg03
    - size: 141g
    - resizefs: True
    - require:
      - batvg03
```
It will try to reduce the logical volume and give the error that you saw:
```
local:
----------
          ID: home
    Function: lvm.lv_present
      Result: False
     Comment: To reduce a Logical Volume option 'force' must be True.
     Started: 19:19:33.097751
    Duration: 72.991 ms
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:  72.991 ms
```

**Comment by grimmjo** [comment]
@sagetherage thank you for your help.

I will close the issue.
