### ISSUE TITLE
[BUG] 3000.8 3002.5 RC13003 ansiblegate if it is able to run doesn't pass args or kwargs to the submodule. 

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#59792]
**Description**
If you are able to get ansible gate to run. which is a big if right now. It doesn't seem to work with 3002 or 3003 as it is not passing the value of any args to the system.module. and has str errors in 3000 

**Setup**
```
salt-call ansible.system.ping 
```

will return ping: pong under normal circumstances. 

but if you pass data='string' it will respond with string. 

however currently if you pass data='hello' to ansible.system.ping you will still get pong. 

After putting some logging into the ansiblegate module that showed what the args values were. they were blank dicts. nothing in them. 

**Expected behavior**
args passed to ansiblegate are passed to the ansible modules

**Comment by whytewolf** [comment]
Can we get a bump in the priority of this issue?

**Comment by whytewolf** [comment]
@sagetherage any updates on this?

**Comment by sagetherage** [comment]
Since it is `severity-medium` I simply haven't assigned it, yet - thanks for the nudge. Will get it assigned.

**Comment by whytewolf** [comment]
May we get an update?

**Comment by sagetherage** [comment]
@whytewolf @s0undt3ch is likely the best person to dig into this issue and he was assigned 10 days ago, but is still transitioning back from working on another project and this will not be his highest priority for Silicon, but he is assigned and will review soon.
