### ISSUE TITLE
Repository HasSum missmatch - on package python3-distro_1.0.1-2_all.deb

### ISSUE THREAD

**Issue by AmiramMaimon** [saltstack/salt#59801]
Hey all,
After adding the `repo.saltstack.com` to my sources list I'm trying to install the `salt-minion` on my Linux 16.04 server.

While installing I'm getting an HashSum mismatch on package [python3-distro_1.0.1-2_all.deb](http://repo.saltstack.com/py3/ubuntu/16.04/amd64/latest/dists/xenial/main/binary-amd64/).

I test the hash of the package `python3-distro_1.0.1-2_all.deb` and compare it to the one written at the [Release](http://repo.saltstack.com/py3/ubuntu/16.04/amd64/latest/dists/xenial/main/binary-amd64/Release) file and they are different.

Please advice.
How this issue can be resolved?
Can you fix the (http://repo.saltstack.com/py3/ubuntu/16.04/amd64/latest/dists/xenial/main/binary-amd64/Release) file at the repo?

**Comment by bryceml** [comment]
```
Component: main
Origin: SaltStack
Label: salt_ubuntu1604
Architecture: amd64
Description: SaltStack Ubuntu 16.04 Python 3 package repo
```

are the contents of that file, there are no hashes.

The hashes from Packages.gz and Packages both have matching sha256sums for me for that package.

**Comment by AmiramMaimon** [comment]
You are right I got the wrong file there. 

The correct file to look is the  [Packages](http://repo.saltstack.com/py3/ubuntu/16.04/amd64/latest/dists/xenial/main/binary-amd64/Packages) file,
And the mismatch is **not** at the `sha256sums ` it's at the `MD5sum`.
The MD5 at the Packages file is: `90686f4641e59e0a15c24f04d3358348`
While the real MD5 of the file is: `e5538c4084ddafc6ce36904belef98b7`

Regarding the `python3-distro_1.0.1-2_all.deb` file under the `xenial`.

**Comment by bryceml** [comment]
I get `90686f4641e59e0a15c24f04d3358348` as the md5 hash on the file as well.

I did find though that `e5538c4084ddafc6ce36904belef98b7` matches https://repo.saltproject.io/py3/ubuntu/16.04/amd64/archive/3002.2/pool/main/p/python-distro/python3-distro_1.0.1-2_all.deb

The fact that they are different with matching names indicates a bug in our packaging process which I've fixed here: https://github.com/saltstack/salt-auto-pack/commit/ce4e8b0b6ce49c24743c5adbf083bc0cd8dfd9aa
