### ISSUE TITLE
[DOCS] add platform support page link and OS Support link to readme

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59817]
**Description**
add platform support page link and OS Support link to readme

**Suggested Fix**
add platform support page link and OS Support link to readme

**Type of documentation**
saltstack/salt/readme

**Location or format of documentation**
all formats of the README but mostly the md file

**Additional context**

N/A

**Comment by eclecticmiraclecat** [comment]
Hello, I would like to work on this issue. How could I get started?

**Comment by peanutduck** [comment]
Hello, I would like to work on this issue. How could I get started and which file should I edit?
