### ISSUE TITLE
[DOCS] add platform support page link and OS Support link to FAQ

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59818]
**Description**
add platform support page link and OS Support link to FAQ

**Suggested Fix**
add platform support page link and OS Support link to FAQ

**Type of documentation**
https://docs.saltproject.io/en/latest/faq.html#frequently-asked-questions

**Location or format of documentation**
https://github.com/saltstack/salt/edit/master/doc/faq.rst

**Additional context**

**Comment by barbaricyawps** [comment]
Resolved: https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-supported-operating-systems.html

https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-version-support-lifecycle.html
