### ISSUE TITLE
[BUG] rsync://repo.saltstack.com not working

### ISSUE THREAD

**Issue by bugfood** [saltstack/salt#59825]
Hi,

Please re-enable the rsync service for repo.saltstack.com; this is quite useful for those of us who need to make a local mirror.

Much of this is already discussed in https://github.com/saltstack/salt/issues/29222

From my end, it seems that TCP port 873 is remotely firewalled for IPv4 and IPv6. SYN packets sent to port 873 elicit no response.

```
$ rsync --contimeout 10 rsync://repo.saltstack.com
rsync error: timeout waiting for daemon connection (code 35) at socket.c(278) [Receiver=3.2.3]
```

That should look more like:
```
$ rsync --contimeout 10 rsync://rsync.puppet.com
packages       	Puppet Labs Package Repository
```

Thanks,
Corey

**Comment by sagetherage** [comment]
You can mirror from here: https://repo.saltproject.io/#mirror however we do not support rsync any longer, please see this page for mirroring instructions.
