### ISSUE TITLE
[BUG] Hetzner cloud driver does not recognize machines when rolling out a map

### ISSUE THREAD

**Issue by dithmer** [saltstack/salt#59863]
**Description**
When you are using the hetzner driver for saltcloud and try to rollout a machine, via a map

```
salt-cloud -m my.map
```

there is an error which pops up, caused by trying to convert a `PrivateNet`-model from package `hcloud` into an dictionary by using a property which doesn't exist in the model.

Without DEBUG output level, this bug causes the map rollout to not recognize that this machine is already existing and tries to roll it out nevertheless.

```
[DEBUG   ] Failed to execute 'hetzner.list_nodes()' while querying for running nodes: 'PrivateNet' object has no attribute 'ipv4'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/salt/cloud/__init__.py", line 2367, in run_parallel_map_providers_query
    salt.utils.data.simple_types_filter(cloud.clouds[data["fun"]]()),
  File "/usr/local/lib/python3.7/dist-packages/salt/cloud/clouds/hetzner.py", line 184, in list_nodes
    nodes = list_nodes_full()
  File "/usr/local/lib/python3.7/dist-packages/salt/cloud/clouds/hetzner.py", line 167, in list_nodes_full
    "private_ips": list(map(_network_to_dict, node.private_net)),
  File "/usr/local/lib/python3.7/dist-packages/salt/cloud/clouds/hetzner.py", line 87, in _network_to_dict
    log.info(net.ipv4)
AttributeError: 'PrivateNet' object has no attribute 'ipv4'
```

**Expected behavior**
`salt-cloud -m my.map` should not even try to rollout a machine which already exists in a hetzner project.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.0.3
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-13-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Comment by max-arnold** [comment]
Was this module backported to 3002.5?  AFAIK, it only exists in 3003-RC1, although the docs do not have a `versionadded` tag: https://docs.saltproject.io/en/master/ref/clouds/all/salt.cloud.clouds.hetzner.html

**Comment by dithmer** [comment]
> Was this module backported to 3002.5? AFAIK, it only exists in 3003-RC1, although the docs do not have a `versionadded` tag: https://docs.saltproject.io/en/master/ref/clouds/all/salt.cloud.clouds.hetzner.html

You are absolutely right. This was my mistake by copying the version info from the wrong machine.
