### ISSUE TITLE
[Request] Question about targeting states to specific minions

### ISSUE THREAD

**Issue by tanmay89** [saltstack/salt#59878]
Hi Team,

In my infrastructure i have X number of servers, just only few like 1-2 servers have high consumption of some files.
I want to deal with such specific servers, by creating some salt state files which should handle only those, do not touch the other servers which are working fine.

Is there a way out that i can create a salt state file which handles those 2 servers only, if yes, then how should i do it?

Note : I have just started using Saltstack, I am totally new here.

**Comment by dwoz** [comment]
@tanmay89 

You will want to use the top file to target which minions (servers) that you want the specific states applied too. More information can be found [here](https://docs.saltproject.io/en/latest/ref/states/top.html#the-top-file)

**Comment by tanmay89** [comment]
Thanks for the response.
But not that way via top.sls, I might be thinking very wrong, anything which can be more customized and local to targeted minion itself.
I really don't want to disrupt top.sls
Using salt-call, if I can have a local state file which can be applied something like that.

**Comment by sagetherage** [comment]
@tanmay89 you can also target specific minions there is documentation [here](https://docs.saltproject.io/en/latest/topics/targeting/index.html#targeting-minions)

**Comment by sagetherage** [comment]
@tanmay89 let us know if this answer your question and if we can close this issue, thank you!
