### ISSUE TITLE
[FEATURE REQUEST] grains.uuid on windows

### ISSUE THREAD

**Issue by evskorobogatij** [saltstack/salt#59888]
Hi

There is no grains.uuid item on windows 10.
It's present on linux and its very nice to identificate computer by grains.uuid 

It will be wonderful if grains.uuid will be accepted on windows

**Comment by xeacott** [comment]
Hi @evskorobogatij can you provide a `grains.items` on your linux machine so I can see your `uuid` grain please?

**Comment by evskorobogatij** [comment]
Hi @xeacott

**Comment by evskorobogatij** [comment]
a

**Comment by evskorobogatij** [comment]
Hi @xeacott 

If I run `salt-call grains.item uuid` on Linux we get uuid of machine. On windows machine this grains is not defined.
