### ISSUE TITLE
[TEST FAILURE] Ubuntu 20.04 arm64 tests.integration.pillar.test_git_pillar.TestPygit2SSH

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59884]
Please paste the link from the specific build where the failure first started:
https://jenkins.saltproject.io/job/pr-ubuntu-2004-arm64-py3-pytest/job/PR-57997/1/#showFailuresLink

**Comment by sagetherage** [comment]
Let's get this done for the Silicon RC1

**Comment by krionbsd** [comment]
I don't think we can do much about it right now, currently `libgit2-dev` on ubuntu20 is outdated, so it's just too old to build newer versions of `pygi2`, I hope pygit2 will support aarch64 wheels on pypi for arm64 in the future

**Comment by bryceml** [comment]
we will have to pin the requirements so that it uses an older version of pygit2 so that they match up.

**Comment by krionbsd** [comment]
I tried older versions as well, it didn't help

**Comment by bryceml** [comment]
so I just mean installing it, not necessarily getting tests passing.

btw, I tried building manylinux wheels for aarch64 and I get 

```Traceback (most recent call last):
  File "<string>", line 2, in <module>
  File "/opt/python/cp38-cp38/lib/python3.8/site-packages/pygit2/__init__.py", line 30, in <module>
    from ._pygit2 import *
ImportError: /opt/python/cp38-cp38/lib/python3.8/site-packages/pygit2/../pygit2.libs/libgit2-26070b3c.so.1.1.0: undefined symbol: pthread_atfork
```
when it tries to run the smoke tests against it.

I wonder if we should just skip the libgit2 tests on aarch64 until it actually works well on aarch64.  It looks like the guy maintaining pygit2 is working on getting aarch64 wheels working right now.

**Comment by krionbsd** [comment]
Still waiting for latest `pytest-salt-factories` version to be merged to skip some tests and enable CI for arm64

**Comment by sagetherage** [comment]
currently these are green, closing
