### ISSUE TITLE
set_dict_key_value: mapping values are not allowed in this context

### ISSUE THREAD

**Issue by SynPrime** [saltstack/salt#59906]
### Description of Issue
The function set_dict_key_values throws the following error: mapping values are not allowed in this context.
Without the function `set_dict_key_value`, the state doesn't fail.

### Setup
**State file**
```
{% from "icinga2/map.jinja" import icinga2 with context %}

include:
  - icinga2.service

{%- set lookup = {} %}
{%- set defaultZone = icinga2.default_global_zone %}

{%- for hostgroup, config in icinga2.objects.hostgroup.items() %}
  {%- if not config.get('_zone_location') %}
    {{ lookup|set_dict_key_value(defaultZone ~ ':' ~ hostgroup, config) }}
  {%- endif %}
{%- endfor %}

{%- for location, hostgroups in lookup.items() %}
icinga2_object_manage_hostgroups_{{ location }}:
  file.managed:
    - name: {{ icinga2.conf_dir }}/zones.d/{{ location }}/hostgroup.conf
    - source: salt://icinga2/files/objects/hostgroup.conf.jinja
    - template: jinja
    - user: {{ icinga2.user }}
    - group: {{ icinga2.group }}
    - makedirs: True
    - defaults:
      hostgroups: {{ hostgroups }}
      internals: {{ icinga2.internals }}
    - watch_in:
      - service: icinga2_service_running
{%- endfor %}

{%- do salt.log.error(lookup) %}
```
**Pillar**
```
icinga2:
  objects:
    hostgroup:
      salt-master:
        display_name: Salt Master
      web:
        display_name: Test
```
 
### Steps to Reproduce Issue
The log debug shows my variable _lookup_: `{'conf-global': {'salt-master': {'display_name': 'Salt Master'}, 'web': {'display_name': 'Test'}}}`. The variable seems to be right.

If I call the state, this error occurs: `[CRITICAL] Rendering SLS 'base:icinga2.objects.hostgroups' failed: mapping values are not allowed in this context`.

If I delete the set_dict_key_value function, the state will run normally.

### Versions Report
```
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: 1.12.2
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: 1.3.10
     pycparser: 2.19
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-14-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```

**Comment by OrangeDog** [comment]
> mapping values are not allowed in this context

Usually means you have a trailing `:` in the yaml where it shouldn't be. What is the jinja output of this sls?

```
salt-call slsutil.renderer salt://path/to/state.sls jinja
```

It looks like you're dumping the `lookup` dict just into the top level of the file, which won't form a valid state.

**Comment by SynPrime** [comment]
@OrangeDog I am sorry, this was a late coding night for me.
Just copied the example from documentation.

Changing the line `{{ lookup|set_dict_key_value(defaultZone ~ ':' ~ hostgroup, config) }}` to `{%- do lookup|set_dict_key_value(defaultZone ~ ':' ~ hostgroup, config) %}` fixed my issue.
