### ISSUE TITLE
[BUG] Enable salt-runners to run at scale.

### ISSUE THREAD

**Issue by cheburakshu** [saltstack/salt#59903]
**Is your feature request related to a problem? Please describe.**

I would like to make a feature request to make salt-runners scalable and be able to handle multiple concurrent requests from SSC.

It will help us in the following:
1. https://jira.eng.vmware.com/browse/SSC-50
2. Scale deploy minion api that gets called from VRA

For more context pls refer to my discussion with @dwoz  here:
https://saltstack.slack.com/archives/C04HEQ97D/p1616699308244800

**Related Issues**
#60215 
#60216
#59902
#59901
#60504

**Comment by dwoz** [comment]
This issue is also related https://jira.eng.vmware.com/browse/SSC-379

**Comment by sagetherage** [comment]
bugs for scaling runner are fixed in today Salt release [3003.2](https://github.com/saltstack/salt/releases/tag/v3003.2) closing
