### ISSUE TITLE
How to pass json data in cmd.run? 

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#59925]
I need to call an API with url with json data as input. how to pass the same with salt['cmd.run'](). I tried adding the curl command, but getting failed: **Jinja syntax error: expected token ',', got '{'; line 4**
Json data {} in not parsing with the salt command

can anyone advise please?

Salt-- version
3000.1

**Comment by OrangeDog** [comment]
You need to make sure it's correctly escaped throughout the various layers - curl, bash, yaml, jinja

Using the [http module](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.http.html) may be simpler than directly writing curl commands.

**Comment by sooraj2589** [comment]
I am assigning the curl command response to a jinja variable. couldnt find http module is useful

How to parse and escape '{' the json data '{"message":"test"}' within salt cmd.run??

any help would be appreciable

**Comment by OrangeDog** [comment]
Not sure how you can't find it useful - it does everything curl does but can also format the json for you so there's no need to escape at all. It's also available directly as a jinja filter as `http_query`.
