### ISSUE TITLE
[TEST FAILURE] tests.pytests.integration.proxy failing on macosx catalina

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#59938]
I'm seeing these tests fail consistently on PRs for macosx catalina:

tests.pytests.integration.proxy.test_simple.test_remove_pkgs
tests.pytests.integration.proxy.test_simple.test_upgrade
tests.pytests.integration.proxy.test_simple.test_service_list
tests.pytests.integration.proxy.test_simple.test_service_stop

https://jenkins.saltproject.io/job/pr-macosxcatalina-py3-pytest/job/PR-59915/9/

**Comment by sagetherage** [comment]
these look to be passing now, closing
