### ISSUE TITLE
[DOCS] ads on docs.saltproject.io are 404 erroring.

### ISSUE THREAD

**Issue by bryceml** [saltstack/salt#59936]
**Description**
https://get.saltstack.com/rs/304-PHQ-615/images/Salt-docs-menu-ad-250x63.jpg
and 
https://get.saltstack.com/rs/304-PHQ-615/images/Salt-docs-ad-330x330.png

are 404 erroring on the docs on pages such as https://docs.saltproject.io/en/master/topics/releases/3002.6.html

also, they link to saltconf.com urls which are no longer valid

**Suggested Fix**
update the images and the links

**Comment by ScriptAutomate** [comment]
Ah! Attaching these images for use and easy reference for replacements now that those other images are gone:

![Try Salt Now](https://user-images.githubusercontent.com/5951023/113169382-29e37480-920b-11eb-9d77-0b1642271231.png)
![Salt Banner](https://user-images.githubusercontent.com/5951023/113169385-2a7c0b00-920b-11eb-92b6-93e2822cc171.png)
![Presentation1](https://user-images.githubusercontent.com/5951023/113169387-2b14a180-920b-11eb-8d9a-cf8da4a9a475.png)

This impacts a few places:

- Main docs portal, a private repo that publishes to: docs.saltproject.io
- Salt Docs: docs.saltproject.io/en/master/contents.html

**Comment by ScriptAutomate** [comment]
Sources that need updates in the theme:

```
17:26 $ grep -rn 'get.saltstack.com'
doc/_themes/saltstack2/layout.html:276:                                 <a href="https://saltconf.com/ad" target="_blank"><img class="nolightbox footer-banner center" src="https://get.saltstack.com/rs/304-PHQ-615/images/Salt-docs-ad-330x330.png"/></a>
doc/_themes/saltstack2/layout.html:298:                <a href="https://saltconf.com/menu-ad" target="_blank"><img class="nolightbox sidebar-banner center" src="https://get.saltstack.com/rs/304-PHQ-615/images/Salt-docs-menu-ad-250x63.jpg"/></a>
```

**Comment by ScriptAutomate** [comment]
Opened related issue: https://gitlab.com/saltstack/open/salt-branding-guide/-/issues/1

**Comment by ScriptAutomate** [comment]
This issue involves some more work. Each of the broken banners have links we need to review and see if they need updates:
- Top-right: saltconf.com/menu-ad
  - Current link goes here: [SaltConf19 Videos](https://www.youtube.com/playlist?list=PL9svBjLDUl_8E03aA45ZncgwTrI96ky2m)
  - We currently have a **Binge Watch SaltConf20 Now** banner, but SaltConf21 now has a page: saltconf.com. This means a new strategy should be made in the `salt-branding-guide` repo:
    - `saltconf.png` (banner used dynamically for ads)
    - `saltconf-watch.png` (banner used for watching videos from previous conference)
- Bottom, larger graphic: saltconf.com/ad
  - Current link goes here: [vRA SaltStack Config](https://www.vmware.com/products/vrealize-automation/saltstack-config.html)
  - This must have originally been a graphic for SSE / SSC, but now we have a generic "Try Salt" graphic. Where should this go with the generic image? I'm currently following up on this with @janae417 

SaltConf21 banner:

![image](https://user-images.githubusercontent.com/5951023/123706271-ae0abf80-d82d-11eb-9cc8-45c8b3f756be.png)

**Comment by ScriptAutomate** [comment]
Follow-up: The links will be updated by @janae417 and a separate team that owns Wordpress. I'll just work on updating banners/images in the meantime, and leave the redirects so that they can be updated to point to the correct locations
