### ISSUE TITLE
[DOCS] 3003 Release Notes headers vary and out of order

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#59946]
**Description**
3003 Release Notes headers vary see screen shot -- all should be at the same as `New Features` and out of order
the order has been: Features, Added, Changed, Deleted, Fixed

**Suggested Fix**
Headers match and order is similar to above

**Type of documentation**
Release Notes for v3003

**Location or format of documentation**
https://docs.saltproject.io/en/3003/topics/releases/3003.html

**Additional context**

<img width="1568" alt="Screen Shot 2021-04-01 at 6 15 15 AM" src="https://user-images.githubusercontent.com/36676171/113300949-5357db00-92b3-11eb-8bb1-41631e75d883.png">

**Comment by ScriptAutomate** [comment]
The history of this file looks a bit mangled. Somewhere along the way, sections were deleted that messed up the headers:

@frogunder  https://github.com/saltstack/salt/commit/c9b2d89267b87a1dd32abd8a75b5196d246449ce#diff-ef7b315c9828d9a9a2de5f41ce[…]d2bb3c806e8356da834ad637aa3f209c

I'm not sure what sections were intentionally or unintentionally deleted, and what should actually be there, etc.
