### ISSUE TITLE
split string and display the second word only?

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#59945]
I am getting a response which has two parts such as 
**Boolean, Integer** eg: true,12334

How we can split the string and assign the second string to a variable.

I have tried with strngvar.split(',')[-1:], also other formats.nothing is working..

Can anyone help me on this?

Salt version
3000.1

**Comment by sooraj2589** [comment]
I could split the values and assigned the second string to a variable. I have imported the variable in another sls, but the variable gives new string values rather than from previous curl.

Can we make the variable as static and passing between state files?

**Comment by waynew** [comment]
Hi @sooraj2589, thanks for the question, but this is the wrong venue when it's not just something broken in Salt. For questions there are several options:

- [#salt on freenode](https://kiwiirc.com/nextclient/irc.freenode.net/?nick=IRC-Source_?#salt)
- [Salt Users email list](https://groups.google.com/forum/#!forum/salt-users)
- [Salt Community Slack](https://saltstackcommunity.herokuapp.com/)
