### ISSUE TITLE
[BUG] Salt 3003 thread does not have access to __salt__['mod.fun']() any more

### ISSUE THREAD

**Issue by litnimax** [saltstack/salt#59962]
**Description**
This is an engine that accepts salt commands using a custom protocol.  The engine is implemented in the tornado in IO loop.
Every command is handled async using thread pool executor (anybody knows a better idea how to call __salt__['mod.func'] asynchronously from async code?).
This code works fine in 3002.2 and earlier.
Here are meanning parts of it:

```
    ...
    # Defined above in start method.
    self.executor = concurrent.futures.ThreadPoolExecutor(max_workers=10)
    ...

   # There is a command receive loop that just calls salt execution modules calling handle_message_async from the loop.

    async def handle_message_async(self, channel, message):
        log.info('------ 1 %s', __salt__['test.ping']()) # This works.
        @coroutine
        def blocking_call():
            f = partial(self.handle_message, channel, message)
            future = self.executor.submit(f)
            return (yield future)
        return await blocking_call()

    def handle_message(self, channel, raw_message):
        log.info('------  2 %s', __salt__['test.ping']()) # Here we started to get an error in 3003.

```
Here is the traceback that raises only in 3003:

```
22:52:04 [ERROR   ] salt.loaded.ext.engines.odoo_connector:106 Method test.ping status notify error:
Traceback (most recent call last):
  File "/srv/odoopbx/salt/extensions/engines/odoo_connector.py", line 65, in execute
    res = __salt__[method](*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/loader_context.py", line 72, in __getitem__
    return self.value()[item]
TypeError: 'NoneType' object is not subscriptable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/odoopbx/salt/extensions/engines/odoo_connector.py", line 103, in execute
    __salt__['odoo.notify_user'](status_notify_uid, status,
  File "/usr/local/lib/python3.6/dist-packages/salt/loader_context.py", line 72, in __getitem__
    return self.value()[item]
TypeError: 'NoneType' object is not subscriptable
22:52:04 [ERROR   ] root:151 'NoneType' object is not subscriptable
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/jsonrpcserver/dispatcher.py", line 134, in handle_exceptions
    yield handler
  File "/usr/local/lib/python3.6/dist-packages/jsonrpcserver/dispatcher.py", line 174, in safe_call
    result = call(lookup(methods, request.method), *request.args, **request.kwargs)
  File "/usr/local/lib/python3.6/dist-packages/jsonrpcserver/dispatcher.py", line 127, in call
    return validate_args(method, *args, **kwargs)(*args, **kwargs)
  File "/srv/odoopbx/salt/extensions/engines/odoo_connector.py", line 65, in execute
    res = __salt__[method](*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/loader_context.py", line 72, in __getitem__
    return self.value()[item]
TypeError: 'NoneType' object is not subscriptable
22:52:04 [ERROR   ] tornado.application:640 Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f8c2c27ed90>, <salt.ext.tornado.concurrent.Future object at 0x7f8c2c7a6438>)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/tornado/ioloop.py", line 628, in _discard_future_result
    future.result()
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "<string>", line 6, in _wrap_awaitable
  File "/srv/odoopbx/salt/extensions/engines/odoo_connector.py", line 296, in handle_message_async
    return await blocking_call()
  File "<string>", line 3, in __await__
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/tornado/concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/tornado/gen.py", line 1064, in run
    yielded = self.gen.throw(*exc_info)
  File "/srv/odoopbx/salt/extensions/engines/odoo_connector.py", line 295, in blocking_call
    return (yield future)
  File "/usr/local/lib/python3.6/dist-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 425, in result
    return self.__get_result()
  File "/usr/lib/python3.6/concurrent/futures/_base.py", line 384, in __get_result
    raise self._exception
  File "/usr/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/srv/odoopbx/salt/extensions/engines/odoo_connector.py", line 327, in handle_message
    __salt__['odoo.execute'](
  File "/usr/local/lib/python3.6/dist-packages/salt/loader_context.py", line 72, in __getitem__
    return self.value()[item]
TypeError: 'NoneType' object is not subscriptable
```

I suppose this is what is related to it:

* https://salt.tips/whats-new-in-salt-aluminium-release/#loader-contexts
* https://github.com/saltstack/salt/pull/58853

Can anybody give an idea how to make it work in 3003?
Thanks.

**Comment by danielrobbins** [comment]
@litnimax Since this used to work but now does not, it seems reasonable to assume that recent changes to the lazy loader have made it not thread-safe. Maybe it was thread-safe before but now is not, or maybe it was never thread-safe (not sure if we ever made sure it was thread-safe) and you were lucky with earlier versions.

I am making this conclusion based on this part of the traceback:

```
  File "/usr/local/lib/python3.6/dist-packages/salt/loader_context.py", line 72, in __getitem__
    return self.value()[item]
TypeError: 'NoneType' object is not subscriptable
```

I can suggest a possible workaround for you while we investigate the problem further. If you have a way of calling the first operation in the current thread, rather than in the ``ThreadPoolExecutor``, this may possibly force the lazy loader to load all the things it needs in the main thread, and then after you do the first one, you can then use the ``ThreadPoolExecutor`` for the second and consecutive ones. In theory the lazy loader will not need to be called in the ``ThreadPoolExecutor``, and thus your code may work with this workaround.

**Comment by danielrobbins** [comment]
@dwoz Performing some dev triage on this issue. I have some thread-safe module loading code in subpop -- here is a snippet:

```
	def load_module(self, fullname):
		# do a lock before using our mod_path_lock to acquire a lock!
		self.lock.acquire()
		with self.mod_path_lock[fullname]:
			self.lock.release()
			result = self.really_load_module(fullname)
		return result
```

```loader.py/LazyLoader/_load_module()`` could be renamed to ``_really_load_module()`` and ``_load_module()`` could be replaced with something like the above code. In the above code, ``self.lock = threading.Lock()``.

If this change doesn't create any deadlocks, then there is a high likelihood that we have made the lazy loader thread-safe with this change. I hit the exact same issue in subpop.

It also would be really useful to use this example code in this bug to add a new test, which initially fails, but then with the fix will pass. This would confirm that we can reproduce the failure and that also our fix actually fixes the problem.

**Comment by danielrobbins** [comment]
I talked to @dwoz about this, and there has been some recent work on the LazyLoader which uses context variables to keep track of various things. It's not really using locks and he'd like to avoid hacking on it as I suggested. However, there is a ``run_in_thread()`` method which could be expanded upon -- possibly by adding something easier to use, or a recipe for doing what you're doing. So I know @dwoz is looking at this issue and I may assist in providing an easier way to use thread pools to accelerate certain tasks when building an engine. I will post more details here as I have them.

**Comment by danielrobbins** [comment]
@litinmax as an off-the-wall idea, it may be interesting to offer a threaded iterator state which will automatically set up a ThreadPoolExecutor and run exec functions or states. See #59810 -- imagine something like this that would automatically set up the threadpool and loop and do it all for you without having to write python code. This might be useful. I can also keep in mind custom engines and have this functionality available from python code as well.

**Comment by dwoz** [comment]
@litnimax in 3003 we started using contextvars to make sure loaders don't stomp on each other. You'll need to set up the context in the thread. The following should get things working again. 

```
    from salt.loader_context import loader_context
    ...
    # Defined above in start method.
    self.executor = concurrent.futures.ThreadPoolExecutor(max_workers=10)
    ...

   # There is a command receive loop that just calls salt execution modules calling handle_message_async from the loop.

    async def handle_message_async(self, channel, message):
        log.info('------ 1 %s', __salt__['test.ping']()) # This works.
        @coroutine
        def blocking_call():
            f = partial(self.handle_message, __salt__.loader(), channel, message)
            future = self.executor.submit(f)
            return (yield future)
        return await blocking_call()

    def handle_message(self, loader, channel, raw_message):
        with loader_context(loader):
            log.info('------  2 %s', __salt__['test.ping']()) # This should work now

```

**Comment by odoopbx-support** [comment]
Yes it works!
Thank you very much for the support.

**Comment by sastorsl** [comment]
Had the same issue but with `queue.Queue` and `threading.Thread()`

I have several general purpose functions which I _also_ called inside threads, which "broke" as of salt-3003 - since `__salt__` no longer was available.

I ended up adapting the above by:

1. Importing globally as pr above
2. Set `loader = __salt__.loader()` outside the threading
3. Pass the `loader` variable to the function and all sub functions that I required.

```python
# Global import
from salt.loader.context import loader_context  # NB! loader.context, not loader_context

def work_function(params..):
    # Set up workers to consume work
    loader = __salt__.loader()

    def run_cmd_queue(name, cnt, changes, errors, loader)
        # queue-stuff
        ret = global function(args, args2, loader):

    for cnt in range(threads):
        log.info("%s: Starting worker %s", func, cnt)
        thr = threading.Thread(target=run_cmd_queue, args=(name, cnt, changes, errors))
        thr = threading.Thread(target=run_cmd_queue, args=(name, cnt, changes, errors, loader))
        thr.start()
```
