### ISSUE TITLE
[BUG] 3003 pillar calls are twice as slow comparing to 3001.3

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#59971]
**Description**
We're testing an update from 3001.3 to 3003.0 and we noticed that any pillars call now takes roughly twice as long.

Note that we use [pillarstack](https://docs.saltproject.io/en/latest/ref/pillar/all/salt.pillar.stack.html) for pillars.

**Steps to Reproduce the behavior**
```
time salt-call pillar.ls
```

**Expected behavior**
The call time should be roughly the same or expected performance regression should be documented.

**Versions Report**
All minions and master are always on the same version in both examples.

<details><summary>salt --versions-report for 3003</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: 0.37.1
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 19.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1062.18.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

<details><summary>salt --versions-report for 3001.3</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3001.3

Dependency Versions:
           cffi: 1.14.5
       cherrypy: Not Installed
       dateutil: Not Installed
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.10.3
        libgit2: Not Installed
       M2Crypto: 0.37.1
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 1.0.0
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: 3.9.7
         pygit2: Not Installed
         Python: 3.6.8 (default, Aug  7 2019, 17:28:10)
   python-gnupg: 0.4.5
         PyYAML: 5.3.1
          PyZMQ: 19.0.2
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.2

System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.10.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```
</details>

**Additional context**
Trace logs for 3003: https://gist.github.com/Oloremo/55550d16d0be71466edfdf6432237f04

Trace logs for 3001.3:  https://gist.github.com/Oloremo/24f76197f6a44c4937f8a0504f3ce1c5

**Comment by cmcmarrow** [comment]
On my Box it was not as bad of slow down that you saw. But I can confirm salt took a performance hit in that release. I also saw the performance hit at the point as you ` [TRACE   ] ext_pillar_extra_data = {}`

**Comment by Oloremo** [comment]
@cmcmarrow Hm, could it depend on the size of the pillars? We do have a lot of stuff in our pillars.

**Comment by garethgreenaway** [comment]
@Oloremo When you saw you have a lot of data in your pillar, can you give an estimate of how much data?

**Comment by Oloremo** [comment]
@garethgreenaway 

~45000 LoC in yaml 🙄

**Comment by whytewolf** [comment]
@Oloremo have you been able to test if it is better in 3004?

**Comment by Oloremo** [comment]
@whytewolf retested on 3004:

```
real	0m24.709s
user	0m1.148s
sys	0m0.220s
```

**Comment by whytewolf** [comment]
ok, then it isn't strictly LOCs that cause it. how many files are your pillars divided between and how much jinja is in them? trying to figure out where to focus the issue. narrow the focus to see if we can find where the slowdown happened.

**Comment by Oloremo** [comment]
@whytewolf 
We actually strip down LoC as well to 18k from 45k. But the execution time is more or less the same.

> much jinja is in them
~500 variables set and conditions.

**Comment by whytewolf** [comment]
@Oloremo that is why i was asking about number of files. it doesn't look like LOCS but logic that is slowing it down. so i need to find that logic. like did we switch from os.path to pathlib and it slowdown or something like that. are you seeing any errors with rendering in the master? if you turn the master to profile logging do you see the render time for the pillars and if so how do they look?

**Comment by Oloremo** [comment]
@whytewolf ok it was a god hint and the problematic part is the `vault.read_secret` calls.

Without them `ls` takes 2 seconds.

So seems like we have a slow down in that module since 3002 or 3003?

**Comment by whytewolf** [comment]
ok, that is a wtf thing... I just ran a diff on vault.py in utils, modules and runners and the only changes between 3001.3 and 3003 are python2 removal stuff and formatting changes. nothing that should decrease speed. if anything some of it should increase speed. 

Is your vault responding like it used to or has it also slowed down?

**Comment by whytewolf** [comment]
Oh ... is reading vault the only module call you had in pillar?

**Comment by Oloremo** [comment]
> Oh ... is reading vault the only module call you had in pillar?

We do a lot of `grains.get` and some `pkg.version_cmp`.

But it's clear that vault read is the bottleneck. We don't have 3001.x anymore, I may be able to find a time to make a stand for re-testing...

**Comment by max-arnold** [comment]
Maybe the jinja profiling can help? https://docs.saltproject.io/en/latest/topics/jinja/index.html#profiling

**Comment by whytewolf** [comment]
humm. that is strange. I was trying to see if it might be the loader that is causing it. but if it is only vault module causing it. I'm not sure what changed. I think i might push this to sulfur for now. until we can get a better idea on what is happening. there is also some changes coming to the vault module in 3005 so maybe they will increase the speed.

**Comment by whytewolf** [comment]
@Oloremo were you able to test 3005 to see if the changes to vault helped in your issue?

**Comment by Oloremo** [comment]
I can't really go back to our 3001 configurations anymore. Way too much has changed. Seems like the issue was Vault read operations. Since then we added token cache and it improved the situation significantly. I think we can close the issue for now.
