### ISSUE TITLE
Update Installation documentation for Debian 10 Buster!

### ISSUE THREAD

**Issue by dachshund-digital** [saltstack/salt#60005]
Update the installation documentation for Debian 10 Buster!  This should clear and obvious.  Buster has been release for quite a while but the official documentation is still referencing Jessie?  Please update the documentation.

**Comment by dachshund-digital** [comment]
More information, to help triage...  

Attempting to following directions on [https://repo.saltstack.com/#debian
](url).  Only customization was change of 'amd64' to 'armhf' for the APT repository list file.  Such that  /etc/apt/sources.list.d/salt.list is set to 'deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg] https://repo.saltproject.io/py3/debian/10/armhf/latest buster main' for Raspberry Pi OS / hardware support.

Will post result of testing here as applicable.

**Comment by sagetherage** [comment]
we will accept a PR for any docs changes :-)

**Comment by danielrobbins** [comment]
It looks like we are referencing Buster in all the right places (just checked) so I am going to close this bug. If you have some areas where you feel like we have missed things, please include specific examples (a link, plus the text you think is wrong) and some suggested improvement text. You have pointed out an issue related to Raspbian but I think we have that covered with these docs: https://repo.saltstack.com/#raspbian
