### ISSUE TITLE
How to run multiple salt states in jinja for loop

### ISSUE THREAD

**Issue by Sudheendhar** [saltstack/salt#60014]
### Description of Issue
Hi can someone please help me in adding different state ids in jinja for loop. As I have to use same states multiple times. i have to create different state id's but for loop is not working when i create a new state id.

Without creating a new state id first 3 states are running but i'm getting error at delete file stage as i have to use file state once again in the same id which is not possible in salt. so please help me in running a for loop by using multiple state id's.

### Setup
{% for agent in 'folder1','folder2','folder3' %}
{{ agent }}:
  create-folders:
    file.directory:
      - name: /scratch/{{ agent }}
      - makedirs: true
      - mode: 644
  download-tarfile:
    cmd.run:
      - name: curl --url someurl --output /scratch/{{ agent }}/tarfile
  runmodule:
    module.run:
      -name: archive.tar
      - options: zxf
      - tarfile: /scratch/{{ agent }}/tarfile
      - dest: /scratch/{{ agent }}/
  delete-tarfile:
    file.absent:
      - name: /scratch/{{ agent }}/tar

{% endfor %}

**Comment by OrangeDog** [comment]
Your SLS syntax is incorrect, with an extra level of keys. It should be e.g.:
```sls
{% for agent in 'folder1','folder2','folder3' %}
{{ agent }}-create-folders:
  file.directory:
    - name: /scratch/{{ agent }}
    - makedirs: true
    - mode: 644

{{ agent }}-download-tarfile:
  cmd.run:
    - name: curl --url someurl --output /scratch/{{ agent }}/tarfile

{{ agent }}-runmodule:
  module.run:
    - name: archive.tar
    - options: zxf
    - tarfile: /scratch/{{ agent }}/tarfile
    - dest: /scratch/{{ agent }}/

{{ agent }}-delete-tarfile:
  file.absent:
    - name: /scratch/{{ agent }}/tar

{% endfor %}
```

You might want some requisites in there too.

**Comment by Sudheendhar** [comment]
wow, this is working as expected. Thank you so much :)
