### ISSUE TITLE
[BUG] 3003 minion not starting on macOS Big Sur

### ISSUE THREAD

**Issue by maennlse** [saltstack/salt#60012]
**Description**
version 3003 of the salt-minion is not starting on macOS Big Sur (at least not for me)

```
salt-minion -V
Traceback (most recent call last):
  File "/opt/salt/bin/salt-minion", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/opt/salt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3191, in <module>
    @_call_aside
  File "/opt/salt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3175, in _call_aside
    f(*args, **kwargs)
  File "/opt/salt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3204, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/opt/salt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/opt/salt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/opt/salt/lib/python3.7/site-packages/pkg_resources/__init__.py", line 786, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'pyobjc-framework-AutomaticAssessmentConfiguration==6.2.2; platform_release >= "19.0"' distribution was not found and is required by pyobjc
```

previous version 3002.6 worked as expected.

**Steps to Reproduce the behavior**
Install salt-minion 3003 on macOS Big Sur

**Expected behavior**
salt-minion starts 

**Versions Report**
salt-3003-py3-x86_64.pkg (sha256: F780DF6821043B3507B8705416D0D070929B9B1FB3E02E5FFAE4F49D81BF0F5E)
macOS Big Sur 11.2.3 (20D91)

**maybe related ?**
#57973
#56416

**Comment by sagetherage** [comment]
@sheagcraig @weswhet can you help with triaging this issue, please?

**Comment by sagetherage** [comment]
This also applies to 10.14

**Comment by sagetherage** [comment]
do we want to look at removing pyobjc?

**Comment by rrrix** [comment]
I noticed when looking at PR https://github.com/saltstack/salt/pull/60026 that the CI jobs for PR's don't include an automated test for Big Sur - only Mojave and Catalina. Should that be a separate issue?

**Comment by sagetherage** [comment]
@rrrix good point and I thought the MacOS Working Group was taking that on - but a new issue definitely won't hurt!

**Comment by twangboy** [comment]
The package has been rebuilt using the requirements file as found in #60026 and is now live:
https://staging.repo.saltproject.io/osx/salt-3003-py3-x86_64.pkg

The old package has been renamed:
https://staging.repo.saltproject.io/osx/salt-3003-py3-x86_64-broken-initial-release.pkg

**Comment by maennlse** [comment]
i can confirm that the updated package is working.
thank you.
