### ISSUE TITLE
[DOCS] Better documentation for log_granular_levels

### ISSUE THREAD

**Issue by ari** [saltstack/salt#60027]
Docs for this feature are very thin. How do we know what "log call names" are available? Is there some way to output those names into the logs so that we can see them?

https://docs.saltproject.io/en/latest/ref/configuration/logging/index.html#log-granular-levels

In my case, I'd like to log "Completed state" at INFO, but I can't tell if this level of granularity is available.

**Comment by OrangeDog** [comment]
The available "log call names" would be every single file in the Salt source. Technically only the ones that have a log call in them, but that can change with any release.

Note that this doesn't let you change the level of particular messages, it lets you control the verbosity of each module individually, compared to the global `log_level` property. The "Completed state" message is logged [here](https://github.com/saltstack/salt/blob/v3003/salt/state.py#L2241) so the name would be `salt.state` if you wanted to show/hide it.

If you want to see the name for every logged message you'd need to change the default log format to include it.

This is all well known to Python developers, but probably not general sysadmins.

**Comment by ari** [comment]
Thanks, that's helpful. For non-python experts, adding something like this to the docs would be great:

`You can determine what log call name to use here by adding %(module)s to the log format. Typically it is the path of the file which generates the log without the trailing .py and with path separators replaced with '.'`
