### ISSUE TITLE
[BUG] Snapper module _is_text_file function broken

### ISSUE THREAD

**Issue by stealthcopter** [saltstack/salt#60046]
**Description**

I believe the snapper module's `_is_text_file` has been broken as part of the security vulnerabilities that were fixed in this pull request: https://github.com/saltstack/salt/pull/59648

**Steps to Reproduce the behavior**
Attempt to run the snapper module's diff function. Or you can run the following code to test (copied from snapper module):

```python
import subprocess

def _is_text_file(filename):
    """
    Checks if a file is a text file
    """
    type_of_file = subprocess.run(
        ["file", "-bi", filename],
        check=False,
        stdout=subprocess.STDOUT,
        universal_newlines=True,
    ).stdout
    return type_of_file.startswith("text")

_is_text_file('textfile.txt')
```

If you test this out just in a python file you notice it errors with the following:

```
OSError: [Errno 9] Bad file descriptor
```

**Expected behavior**
For _is_text_file to function correctly  

**Additional context**

** Fix **

This is fixed by changing `STDOUT` to `PIPE`. Example:

```python
def _is_text_file(filename):
    """
    Checks if a file is a text file
    """
    type_of_file = subprocess.run(
        ["file", "-bi", filename],
        check=False,
        stdout=subprocess.PIPE,
        universal_newlines=True,
    ).stdout
    return type_of_file.startswith("text")
```

I would be happy to submit a pull request for this if this fix is acceptable.

Note that I attempted to notify you of this via the security email address but was ignored. I have detailed the security vulnerability that was fixed by the previous pull request here:
https://sec.stealthcopter.com/saltstack-snapper-minion-privledge-escaltion/

**Comment by sagetherage** [comment]
@stealthcopter 
> Note that I attempted to notify you of this via the security email address but was ignored. I have detailed the security vulnerability that was fixed by the previous pull request here:
https://sec.stealthcopter.com/saltstack-snapper-minion-privledge-escaltion/

I will look into this, we did receive other emails, but it is true I didn't see one around this issue described. I will get back to you on any findings.

**Comment by stealthcopter** [comment]
@sagetherage Ah sorry, I thought I had included it in the original report but couldn't check due to encrypting it :facepalm:

**Comment by sagetherage** [comment]
@stealthcopter we did migrate the email address recently, but have received emails before and after the migration date. Can you give me some more details on the email address and date sent? You can send those to me here: sage@saltstack.com 

thank you!
