### ISSUE TITLE
[BUG] Data failed to compile - Detected conflicting IDs, SLS IDs need to be globally unique. The conflicting ID is 'elasticsearch_repo' and is found in SLS 'base:filebeat.repo' and SLS 'base:elasticsearch6.repo'

### ISSUE THREAD

**Issue by DogasNetwork** [saltstack/salt#60041]
**Description**
```
I have tried to do the following troubleshoot:

Whilst I ran the `salt '*' state.apply test=true`, I've got the following error listed at the Title:

Data failed to compile - Detected conflicting IDs, SLS IDs need to be globally unique. The conflicting ID is 'elasticsearch_repo' and is found in SLS 'base:filebeat.repo' and SLS 'base:elasticsearch6.repo'

I have navigated to the `/srv/data/salt/elasticsearch` and tried to see if I could find the file that `elasticsearch_repo` was situated and also tried to find the `filebeat.repo` file, but eventually was not able to find it.
Then, I tried checking my log files at `/srv/data/logs` but I couldn't locate the `elasticsearch_repo` neither `filebeat.repo` file.
```

**Setup**
N/A

**Steps to Reproduce the behavior**
I do not know.

**Expected behavior**
The conflicting IDs, SLS IDs need to be globally unique.

**Screenshots**
N/A

**Versions Report**
<details><summary>
```
Salt Version:
           Salt: 3001.6

Dependency Versions:
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.7.3
      docker-py: Not Installed
          gitdb: 2.0.5
      gitpython: 2.1.11
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: 3.6.1
         pygit2: Not Installed
         Python: 3.7.3 (default, Jul 25 2020, 13:03:44)
   python-gnupg: Not Installed
         PyYAML: 3.13
          PyZMQ: 17.1.2
          smmap: 2.0.5
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.1

System Versions:
           dist: debian 10 buster
         locale: UTF-8
        machine: x86_64
        release: 4.19.0-13-amd64
         system: Linux
        version: Debian GNU/Linux 10 buster
```
</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
This isn't a bug. You have included both those conflicting states in some way. I'm guessing you have added some salt formulas via gitfs. You'll need to look at your master config and top files to confirm.

As an aside, you should not have your logs under `/srv`. I don't know why you've moved things from their default locations, but that's likely to be insecure.

**Comment by DogasNetwork** [comment]
> 
> 
> This isn't a bug. You have included both those conflicting states in some way. I'm guessing you have added some salt formulas via gitfs. You'll need to look at your master config and top files to confirm.
> 
> As an aside, you should not have your logs under `/srv`. I don't know why you've moved things from their default locations, but that's likely to be insecure.

Hi,

Tbh, I'm having this setup in the company. So I don't really know how to find the root cause just yet unfortunately.

And if its as you say that they added some **salt formulas via gitfs** I really wouldn't know how they've done it. 

Currently, I'm following an online SaltStack course, so my Salt knowledge is also quite limited at this time :/

But thank you! I'll check out the **salt-master config** and the **top.sls** files right?

**Comment by DogasNetwork** [comment]
I had to change the the name from **elasticsearch_repo** to **elasticsearch_filebeat_repo** located in the directory **/srv/data/salt/filebeat.repo.sls**

{%- set release = salt['pillar.get']('apt:release') %}
{%- set url = salt['pillar.get']('apt:proxy-url') %}

```
elasticsearch_filebeat_repo:
  pkgrepo.managed:
{% if salt['pillar.get']('elasticsearch:override_major_version', False) %}
    - name: deb {{ url }}/repository/elasticsearch-{{ salt['pillar.get']('elasticsearch:major_version_override', '7') }}.x stable main
    - file: /etc/apt/sources.list.d/elasticsearch_beats.list
{% else %}
    - name: deb {{ url }}/repository/elasticsearch-{{ salt['pillar.get']('elasticsearch:major_version', '7') }}.x stable main
    - file: /etc/apt/sources.list.d/elasticsearch_beats.list
{% endif %}
    - dist: stable
    - gpgcheck: 1
    - key_url: salt://{{ slspath }}/files/elastic.gpg
    - clean_file: true
```

But now I'm faced with different errors and they are as follows:

```
----------
          ID: filebeat
    Function: pkg.installed
      Result: False
     Comment: Problem encountered installing package(s). Additional info follows:

              errors:
                  - Running scope as unit: run-rd96e2e739b994872a21e0fe7d8ad8eb1.scope
                    E: Unable to locate package filebeat
     Started: 10:53:33.530258
    Duration: 6703.367 ms
     Changes:
----------
          ID: filebeat_cfg
    Function: file.managed
        Name: /etc/filebeat/filebeat.yml
      Result: False
     Comment: Parent directory not present
     Started: 10:53:40.233886
    Duration: 22.041 ms
     Changes:
----------
          ID: /etc/filebeat/cert.pem
    Function: file.managed
      Result: False
     Comment: Parent directory not present
     Started: 10:53:40.256102
    Duration: 0.971 ms
     Changes:
----------
          ID: /etc/filebeat/cert.key
    Function: file.managed
      Result: False
     Comment: Parent directory not present
     Started: 10:53:40.257242
    Duration: 0.836 ms
     Changes:
----------
          ID: /etc/filebeat/ca_siem.pem
    Function: file.managed
      Result: False
     Comment: Parent directory not present
     Started: 10:53:40.258214
    Duration: 0.801 ms
     Changes:
----------
          ID: filebeat_service
    Function: service.running
        Name: filebeat
      Result: False
     Comment: One or more requisite failed: filebeat.config.filebeat_cfg, filebeat.config./etc/filebeat/ca_siem.pem, filebeat.config./etc/filebeat/cert.pem, filebeat.pkg.filebeat, filebeat.config./etc/filebeat/cert.key
     Started: 10:53:40.273894
    Duration: 0.018 ms
     Changes:
----------
```

any ideas on how I should edit this on **/srv/data/salt/filebeat.repo.sls**?

Sorry for being too general, I'm currently following an online SaltStack course and I am at the course module: expanding states with jinja and pillar so trying to grasp the basic fundamentals of it all. :/

**Comment by OrangeDog** [comment]
Your system does not have a package called `filebeat`. That has nothing to do with Salt.
You've probably got the repo definition wrong in some way.

**Comment by DogasNetwork** [comment]
Sorry had to remove the comment since I had uploaded sensitive information without knowing

**Comment by DogasNetwork** [comment]
> 
> 
> Your system does not have a package called `filebeat`. That has nothing to do with Salt.
> You've probably got the repo definition wrong in some way.

I see thanks, I'll look into it appreciate it!
