### ISSUE TITLE
[BUG] Windows Salt Minion contains non-Windows modules and other components

### ISSUE THREAD

**Issue by marbx** [saltstack/salt#60057]
**Description**
The [Windows Salt Minion removes some Unix modules](https://github.com/saltstack/salt/blob/837e8dd5d037042c7a8896c2541a2f511a519e64/pkg/windows/build_pkg.bat#L222), grains and other components, but many remain.

The below lists are both incomplete and inaccurate, please help to correct and amend.
```
grains:
  - esxi
  - fibre_channel
  - fx2
  - junos
  - linux_distribution
  - mdata
  - metadata
  - nxos
  - smartos
  - zfs

modules:
  - aptpkg
  - consul
  - dockermod
  - lxc
  - lxd
  - virt
  - vsphere
  - yumpkg
  - zabbix
  - zypperpkg
```

**Expected behavior**
The Windows Salt Minion should only contain Windows modules, grains and other components (e.g. Unix man pages)

**Related pull requests**
- https://github.com/saltstack/salt/pull/60754

**Comment by whytewolf** [comment]
some of those modules you list are still useful in the windows world. MySQL can be installed on windows, so can versions of postgres. boto modules are also useful although the windows packages should install the boto modules to use them.

**Comment by markuskramerIgitt** [comment]
@whytewolf, thank you for pointing to MySQL, Postgres and boto.
I started above lists from what I personally don't use (which includes modules useful on Windows),  overlooked the databases, and I honestly don't know what boto is :-)

We briefly discussed the issue in the today [Windows working group](https://github.com/saltstack/community/blob/master/working_groups/wg-Windows/meeting-notes/2021-04-20.md), I will later remove modules which @twangboy already removes.

**Comment by whytewolf** [comment]
no problem, for reference boto is used for the control of aws. each of the boot modules controls an aspect of aws. boto_ec2 is used for the ec2 system etc. so for anyone running windows in aws they most likely will want those modules.

**Comment by xeacott** [comment]
Hey @marbx is this ticket still good to keep open?

**Comment by marbx** [comment]
Yes

**Comment by marbx** [comment]
should not be a ticket

**Comment by damon-atkins** [comment]
Modules, States & Grains are design to detect the platform, so the distribution code is the same contents on all platforms.  Some people may writing modules/grains may forget to limit were they run.   Only copying parts of Salt will result in Windows having a different process to other platforms.  Are we going to stop Windows Modules being distributed to Linux systems.  For example MS SQL is now available for Linux.

**Comment by marbx** [comment]
I closed this ticket to allow higher visibility for other tickets.
