### ISSUE TITLE
[TEST FAILURE] Mojave Branch Tests Time Out

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#60067]
The Mojave branch tests are timing out:

https://jenkins.saltproject.io/view/Freeze%20Branch%20Jobs/job/pr-macosx-mojave-x86_64-py3-pytest-slow/job/freeze/23/

After it hits the 6 hour mark it kills the test suite.

Possibly similar to https://github.com/saltstack/salt/issues/60066

**Comment by xeacott** [comment]
Can re-open if need be but looks like they are running now consistently
