### ISSUE TITLE
[TEST FAILURE] PR centos7 Tests Time Out

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#60066]
The following Tests are timing out on PRs but NOT on branch tests:

pr-centos-7-x86_64-py3-pycryptodome-pytest
pr-centos-7-x86_64-py3-m2crypto-pytest
pr-centos-7-x86_64-py3-pytest
pr-centos-7-x86_64-py3-tcp-pytest

Here is an example:

https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-tcp-pytest/job/PR-60062/1/

The tests ran for 6 hours and then it killed the tests due to the 6 hour timeout

**Comment by garethgreenaway** [comment]
Haven't seen this issue show up in any recent PRs so closing it out.
