### ISSUE TITLE
[BUG] pip.installed fails with  TypeError: 'NoneType' object is not reversible in pip_state.py

### ISSUE THREAD

**Issue by Yurmusp** [saltstack/salt#60085]
**Description**
State for pip.installed fails with python exception 

State is this:

salthelpers-scripts-upgrade-global-packages:
  pip.installed:
    - names:
      - awscli >= 1.11.34
      - boto3 >= 1.4.1
    - upgrade: True

OS: Ubuntu 20.04
Salt ver: 3003 , installed from official PPA.
See detailed salt versions in the end of the report.

Error is:
TypeError: 'NoneType' object is not reversible
as below:

File "/usr/lib/python3/dist-packages/salt/states/pip_state.py", line 324, in _check_if_installed
                  for version in reversed(available_versions):
              TypeError: 'NoneType' object is not reversible

**Setup**
State that fails is described above.

**Steps to Reproduce the behavior**
Create SLS with state above and apply it.
(I applied with salt-call --local state.highstate,
However, I'm pretty sure you can apply just this particular state 
and you will shall get same issue).

You will get this output for the state:

ID: salthelpers-scripts-upgrade-global-packages
    Function: pip.installed
        Name: boto3 >= 1.4.1
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2171, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 1235, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2268, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2283, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader.py", line 2316, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/pip_state.py", line 852, in installed
                  out = _check_if_installed(
                File "/usr/lib/python3/dist-packages/salt/states/pip_state.py", line 324, in _check_if_installed
                  for version in reversed(available_versions):
              TypeError: 'NoneType' object is not reversible
     Started: 17:27:26.200409
    Duration: 1212.3 ms
     Changes:

There will be one more output for aws-cli but almost identical to shown above.

I'm able to workaround the bug by adding option:
  - force_reinstall: True
 
This makes code going different route and this particular bug does not trigger.
However, I do not feel it's good idea to do the workaround everywhere.

**Expected behavior**
Expected behavior is to have state successful with Result: True

**Versions Report**
<details><summary>salt --versions-report</summary>

Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-72-generic
        system: Linux
       version: Ubuntu 20.04 focal

```
PASTE HERE
```
</details>

**Additional context**
May be I'm missing something simple, because bug seems shall be discovered by many people
but I did not find anything new and relevant by googling.
If you have any ideas on what I can be missing, let me know.

**Comment by s0undt3ch** [comment]
Found a fix for this issue while working through a test failure. See #60085
