### ISSUE TITLE
[Info-Needed] 'locke.notify' is not available.

### ISSUE THREAD

**Issue by dwicahyohph** [saltstack/salt#60082]
**Description**

'locke.notify' is not available. 

**Setup**
After upgrading salt-minion from 3002 to 3003, I got that error when executed test.sls. How should I fix this? 
this works fine on ver. 3002.

**Debug**
[INFO    ] Running state [get_salt_minion_version_test_run] at time 14:19:53.822731
[DEBUG   ] Could not LazyLoad locke.notify: 'locke.notify' is not available.
[ERROR   ] State 'locke.notify' was not found in SLS 'test'
Reason: 'locke.notify' is not available.

**Versions Report**

 Salt Version:
              Salt: 3003

    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: Not Installed
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.1
           libgit2: Not Installed
          M2Crypto: 0.35.2
              Mako: Not Installed
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: Not Installed
            pygit2: Not Installed
            Python: 3.6.8 (default, Mar  9 2021, 15:08:44)
      python-gnupg: Not Installed
            PyYAML: 3.13
             PyZMQ: 17.0.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.1.4

    System Versions:
              dist: ol 7.9
            locale: UTF-8
           machine: x86_64
           release: 4.14.35-1902.3.2.el7uek.x86_64
            system: Linux
           version: Oracle Linux Server 7.9

**Comment by danielrobbins** [comment]
@dwicahyohph I am not sure why you are getting this error, but I do recognize ``locke.notify``. "Locke" is the codename for SaltStack Enterprise, aka SaltStack Config -- so it is used for security assessments and remediations. I am not sure why it's coming up when you are running the standard Salt test suite, but hopefully that information is helpful.

So I guess a good first follow-up question: are you using SaltStack Enterprise/SaltStack Config in your environment?

**Comment by dwicahyohph** [comment]
@danielrobbins yes I am, it is work fine with minion ver3002, but after upgrading to 3003, it became an issue.

**Comment by sagetherage** [comment]
@dwicahyohph I will get this verified by the SaltStack Config team, putting it into blocked until I hear from them

**Comment by doesitblend** [comment]
HI @dwicahyohph . Can you submit a ticket through the https://my.vmware.com/  portal and we can address how to handle this issue? Thanks.

@sagetherage Since this is related to SSC, I recommend closing out this ticket.

**Comment by dwicahyohph** [comment]
I dont think I can open ticket from vmware.com as I dont hold the account. And yes, I am using SSE for secops. This is just one state file executed using state.apply to minion.

**Comment by doesitblend** [comment]
Hi @dwicahyohph Thanks for the clarification.

Have you tried re-syncing your modules with something like `salt \* saltutil.sync_all saltenv=sse` ?

**Comment by dwicahyohph** [comment]
Hi @doesitblend, I've tried it, this is what I got:

[root@master01 salt]# salt \* state.apply foldersls.test
RHEL8:
----------
          ID: get_salt_minion_version_test_run
    Function: locke.notify
      Result: False
     Comment: State 'locke.notify' was not found in SLS 'foldersls.test'
              Reason: 'locke.notify' is not available.
     Changes:

Summary for RHEL8
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
OL7:
----------
          ID: get_salt_minion_version_test_run
    Function: locke.notify
      Result: False
     Comment: State 'locke.notify' was not found in SLS 'foldersls.test'
              Reason: 'locke.notify' is not available.
     Changes:

Summary for OL7
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms
ERROR: Minions returned with non-zero exit code
[root@master01 salt]#

**Comment by dwicahyohph** [comment]
btw, this is what I did before executed state.apply above...

[root@master01 salt]# salt \* saltutil.sync_all saltenv=base
RHEL8:
    ----------
    beacons:
    clouds:
    engines:
    executors:
    grains:
    log_handlers:
    matchers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    serializers:
    states:
    thorium:
    utils:
OL7:
    ----------
    beacons:
    clouds:
    engines:
    executors:
    grains:
    log_handlers:
    matchers:
    modules:
    output:
    proxymodules:
    renderers:
    returners:
    sdb:
    serializers:
    states:
    thorium:
    utils:
[root@master01 salt]#

**Comment by dwicahyohph** [comment]
Actually, minion RHEL8 was fine even after upgraded to ver. 3003, but now after "sync_all", all minions (OL7 and RHEL8) are affected,

**Comment by dwicahyohph** [comment]
this is what I got when I tried "state.show_sls".  it works and gave me the output I want, although it's still didnt apply to minion.
[root@master01 salt]# salt \* state.show_sls foldersls.test
RHEL8:
    ----------
    get_salt_minion_version_test_run:
        ----------
        __env__:
            base
        __sls__:
            foldersls.test
        locke:
            |_
              ----------
              status:
                  compliant
            |_
              ----------
              result:
                  True
            |_
              ----------
              notify
            |_
              ----------
              order:
                  10000
OL7:
    ----------
    get_salt_minion_version_test_run:
        ----------
        __env__:
            base
        __sls__:
            foldersls.test
        locke:
            |_
              ----------
              status:
                  compliant
            |_
              ----------
              result:
                  True
            |_
              ----------
              notify
            |_
              ----------
              order:
                  10000
[root@master01 salt]#

**Comment by dwicahyohph** [comment]
update:
reverted it back to ver 3002, for both master and minion. the issue still persist.

**Comment by dwicahyohph** [comment]
turns out not only module locke is missing but also other module such as, auditctl and secops_pam, like below:

local:
    Data failed to compile:
----------
    Rendering SLS 'base:newfile' failed: Jinja variable 'salt.utils.templates.AliasedLoader object' has no attribute 'secops_pam.password_requirements'

**Comment by dwicahyohph** [comment]
I add this and solved the issue
/var/cache/salt/minion/extmods/modules/locke.py
/var/cache/salt/minion/extmods/states/locke.py

Others like auditctl, secops_pam are the same.

Close this threat.
