### ISSUE TITLE
state module archive.extracted with specific user and group leads to extracted data which is owned by root

### ISSUE THREAD

**Issue by nweidemann** [saltstack/salt#60095]
### Description of Issue
state module archive.extracted with specific user and group leads to extracted data which is owned by group root

### Setup
source file for kibana: https://artifacts.elastic.co/downloads/kibana/kibana-7.12.1-linux-x86_64.tar.gz

Minion runs with user root

### Steps to Reproduce Issue
State contains extraction of kibana tgz file. Extracted content should be owned by user/group: "soa"
Pillar data for {{ kibana_ver }} is "7.12.1"

Attached state file is simplified regarding pillar data etc. to reproduce issue

[test.zip](https://github.com/saltstack/salt/files/6392296/test.zip)

####outcome###
group of directory is root instead of soa
underlying directory is owned by root:root
( how to enforce_ownership_on: with wildcard?? )

my typical workaround is a simple cmd.run with chown -R soa:soa in this case, but I think the state module does not work as it should.

    extracted directory:
    ID: show_directory
        Function: cmd.run
            Name: ls -lah /app/soa/softwareag/kibana/7.12.1/
          Result: True
         Comment: Command "ls -lah /app/soa/softwareag/kibana/7.12.1/" run
         Started: 15:53:36.567981
        Duration: 96.947 ms
         Changes:
                  ----------
                  pid:
                      28574
                  retcode:
                      0
                  stderr:
                  stdout:
                      total 0
                      drwxr-xr-x.  3 soa  **root**  40 Apr 28 15:53 .
                      drwx------.  4 soa  soa   52 Apr 28 15:53 ..
                      drwxr-xr-x. 10 **root root** 210 Apr 28 15:53 kibana-7.12.1-linux-x86_64

### Versions Report
    #####Master#######: 
    salt --versions-report
    Salt Version:
                Salt: 3003

    Dependency Versions:
              cffi: 1.11.5
          cherrypy: Not Installed
          dateutil: 2.6.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: 0.35.2
              Mako: Not Installed
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.14
          pycrypto: Not Installed
      pycryptodome: Not Installed
            pygit2: Not Installed
            Python: 3.6.8 (default, Aug 18 2020, 08:33:21)
      python-gnupg: Not Installed
            PyYAML: 3.12
             PyZMQ: 19.0.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.4
    
    System Versions:
              dist: rhel 8.3 Ootpa
            locale: UTF-8
           machine: x86_64
           release: 4.18.0-240.22.1.el8_3.x86_64
            system: Linux
           version: Red Hat Enterprise Linux 8.3 Ootpa

    #####Minion#######:
    salt-minion --versions-report
    Salt Version:
              Salt: 3003
    
    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: Not Installed
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.11.1
           libgit2: Not Installed
          M2Crypto: 0.35.2
              Mako: Not Installed
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: 2.6.1
      pycryptodome: Not Installed
            pygit2: Not Installed
            Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
      python-gnupg: Not Installed
            PyYAML: 3.13
             PyZMQ: 17.0.0
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.1.4
    
    System Versions:
              dist: rhel 7.9 Maipo
            locale: UTF-8
           machine: x86_64
           release: 3.10.0-1160.24.1.el7.x86_64
            system: Linux
           version: Red Hat Enterprise Linux Server 7.9 Maipo

**Comment by dmurphy18** [comment]
Confirmed with Salt 3002, and after ensuring user and group **soa** exists on Centos 7 machine, and where test_archive.sls is equivalent to test.sls in test.zip

```
root@Unknown:/srv/salt# salt tc7 state.sls test_archive
tc7:
----------
          ID: install_dir_present
    Function: file.directory
        Name: /app/soa/softwareag/kibana/
      Result: True
     Comment: Directory /app/soa/softwareag/kibana updated
     Started: 17:07:03.446841
    Duration: 41.219 ms
     Changes:   
              ----------
              /app/soa/softwareag/kibana:
                  New Dir
----------
          ID: extract_kibana
    Function: archive.extracted
        Name: /app/soa/softwareag/kibana/7.12.1
      Result: True
     Comment: salt:///kibana-7.12.1-linux-x86_64.tar.gz extracted to /app/soa/softwareag/kibana/7.12.1/, due to absence of one or more files/dirs. Output was trimmed to 30 number of lines
     Started: 17:07:03.489259
    Duration: 34768.331 ms
     Changes:   
              ----------
              directories_created:
                  - /app/soa/softwareag/kibana/7.12.1/
              extracted_files:
                  - kibana-7.12.1-linux-x86_64/.i18nrc.json
                  - kibana-7.12.1-linux-x86_64/LICENSE.txt
                  - kibana-7.12.1-linux-x86_64/NOTICE.txt
                  - kibana-7.12.1-linux-x86_64/README.txt
                  - kibana-7.12.1-linux-x86_64/bin
                  - kibana-7.12.1-linux-x86_64/bin/kibana
                  - kibana-7.12.1-linux-x86_64/bin/kibana-encryption-keys
                  - kibana-7.12.1-linux-x86_64/bin/kibana-keystore
                  - kibana-7.12.1-linux-x86_64/bin/kibana-plugin
                  - kibana-7.12.1-linux-x86_64/config
                  - kibana-7.12.1-linux-x86_64/config/kibana.yml
                  - kibana-7.12.1-linux-x86_64/config/node.options
                  - kibana-7.12.1-linux-x86_64/data
                  - kibana-7.12.1-linux-x86_64/node
                  - kibana-7.12.1-linux-x86_64/node/CHANGELOG.md
                  - kibana-7.12.1-linux-x86_64/node/LICENSE
                  - kibana-7.12.1-linux-x86_64/node/README.md
                  - kibana-7.12.1-linux-x86_64/node/bin
                  - kibana-7.12.1-linux-x86_64/node/bin/node
                  - kibana-7.12.1-linux-x86_64/node/include
                  - kibana-7.12.1-linux-x86_64/node/include/node
                  - kibana-7.12.1-linux-x86_64/node/include/node/common.gypi
                  - kibana-7.12.1-linux-x86_64/node/include/node/config.gypi
                  - kibana-7.12.1-linux-x86_64/node/include/node/cppgc
                  - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/allocation.h
                  - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/common.h
                  - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/custom-space.h
                  - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/garbage-collected.h
                  - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/heap.h
                  - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/internal
----------
          ID: show_directory
    Function: cmd.run
        Name: ls -lah /app/soa/softwareag/kibana/7.12.1/
      Result: True
     Comment: Command "ls -lah /app/soa/softwareag/kibana/7.12.1/" run
     Started: 17:07:38.260562
    Duration: 661.872 ms
     Changes:   
              ----------
              pid:
                  3441
              retcode:
                  0
              stderr:
              stdout:
                  total 4.0K
                  drwxr-xr-x  3 soa  root   39 Apr 28 17:07 .
                  drwx------  3 soa  soa    19 Apr 28 17:07 ..
                  drwxr-xr-x 10 root root 4.0K Apr 28 17:07 kibana-7.12.1-linux-x86_64

Summary for tc7
------------
Succeeded: 3 (changed=3)
Failed:    0
------------
Total states run:     3
Total run time:  35.471 s
root@Unknown:/srv/salt#
```

However just running the command to untar with owner and group on Centos 7 ignores those settings, for example:
```
tar -xvzf kibana-7.12.1-linux-x86_64.tar.gz --owner=soa --group=soa 
root@Unknown:/tmp# ls -alh kib*
-rw-r--r--.  1 root root 269M Apr 28 17:00 kibana-7.12.1-linux-x86_64.tar.gz

kibana-7.12.1-linux-x86_64:
total 1.5M
drwxr-xr-x.  10 root root 4.0K Apr 28 17:20 .
drwxrwxrwt.  48 root root 4.0K Apr 28 17:19 ..
drwxr-xr-x.   2 root root   90 Apr 20 14:34 bin
drwxr-xr-x.   2 root root   42 Apr 20 14:34 config
drwxr-xr-x.   2 root root    6 Apr 20 14:34 data
-rw-r--r--.   1 root root 3.0K Apr 20 14:34 .i18nrc.json
-rw-r--r--.   1 root root 3.8K Apr 20 14:34 LICENSE.txt
drwxr-xr-x.   6 root root  101 Apr 20 14:34 node
drwxr-xr-x. 831 root root  24K Apr 20 14:34 node_modules
-rw-r--r--.   1 root root 1.4M Apr 20 14:34 NOTICE.txt
-rw-r--r--.   1 root root  740 Apr 20 14:34 package.json
drwxr-xr-x.   2 root root    6 Apr 20 14:34 plugins
-rw-r--r--.   1 root root 3.9K Apr 20 14:34 README.txt
drwxr-xr-x.  12 root root 4.0K Apr 20 14:34 src
drwxr-xr-x.   3 root root   75 Apr 20 14:34 x-pack
root@Unknown:/tmp# 
```

So this may be an issue with the underlying command on the OS, given Salt call the tar command on the OS, see https://github.com/saltstack/salt/blob/b3c3b52693b90c5c17f46511179acac6d15fd153/salt/modules/archive.py#L530-L542

**Comment by dmurphy18** [comment]
However a simple tar command extraction as root by default preserves the original user and group, for example:
```
root@david-laptop2:/home/david/Downloads/tmp# tar -xvzf test.tar.gz 
bashrc_minimal
vimrc_minimal
root@david-laptop2:/home/david/Downloads/tmp# ls -al 
total 752696
drwxrwxr-x  3 david david      4096 Apr 28 17:58 .
drwxr-xr-x  8 david david      4096 Apr 28 17:40 ..
-rwxrwxr-x  1 david david      3142 Jul 29  2020 bashrc_minimal
drwxr-xr-x 10 root  root       4096 Apr 28 17:41 kibana-7.12.1-linux-x86_64
-rw-rw-r--  1 david david 770722304 Apr 28 16:56 kibana-7.12.1-linux-x86_64.tar
-rw-rw-r--  1 david david       712 Apr 28 15:59 test_archive.sls
-rw-r--r--  1 root  root       1834 Apr 28 17:58 test.tar.gz
-rw-rw-r--  1 david david       469 Apr 28 16:56 test.zip
-rwxrwxr-x  1 david david       498 Jul 29  2020 vimrc_minimal
root@david-laptop2:/home/david/Downloads/tmp#
```
which begs the question, just what user and group was kibana-7.12.1-linux-x86_64.tar.gz archived with, since running a test.tar.gz with user:group david:david worked as expected

```
root@Unknown:/srv/salt# salt tc7 state.sls test_archive1
tc7:
----------
          ID: install_dir_present
    Function: file.directory
        Name: /app/soa/softwareag/kibana/
      Result: True
     Comment: The directory /app/soa/softwareag/kibana is in the correct state
     Started: 18:05:21.363742
    Duration: 16.471 ms
     Changes:   
----------
          ID: extract_kibana
    Function: archive.extracted
        Name: /app/bashrc_minimal
      Result: True
     Comment: salt:///test.tar.gz extracted to /app/bashrc_minimal/, due to absence of one or more files/dirs. Output was trimmed to 30 number of lines
     Started: 18:05:21.381752
    Duration: 34.994 ms
     Changes:   
              ----------
              directories_created:
                  - /app/bashrc_minimal/
              extracted_files:
                  - bashrc_minimal
                  - vimrc_minimal
              updated ownership:
                  True
----------
          ID: show_directory
    Function: cmd.run
        Name: ls -lah /app/
      Result: True
     Comment: Command "ls -lah /app/" run
     Started: 18:05:21.417522
    Duration: 509.787 ms
     Changes:   
              ----------
              pid:
                  4110
              retcode:
                  0
              stderr:
              stdout:
                  total 4.0K
                  drwx------   4 soa  soa    37 Apr 28 18:05 .
                  dr-xr-xr-x. 18 root root 4.0K Apr 28 17:07 ..
                  drwxr-xr-x   2 soa  root   47 Apr 28 18:05 bashrc_minimal
                  drwx------   3 soa  soa    23 Apr 28 17:07 soa

Summary for tc7
------------
Succeeded: 3 (changed=2)
Failed:    0
------------
Total states run:     3
Total run time: 561.252 ms
root@Unknown:/srv/salt# 
```
and
```
root@Unknown:/srv/salt# salt tc7 state.sls test_archive1
tc7:
----------
          ID: install_dir_present
    Function: file.directory
        Name: /app/soa/softwareag/kibana/
      Result: True
     Comment: The directory /app/soa/softwareag/kibana is in the correct state
     Started: 18:05:21.363742
    Duration: 16.471 ms
     Changes:   
----------
          ID: extract_kibana
    Function: archive.extracted
        Name: /app/bashrc_minimal
      Result: True
     Comment: salt:///test.tar.gz extracted to /app/bashrc_minimal/, due to absence of one or more files/dirs. Output was trimmed to 30 number of lines
     Started: 18:05:21.381752
    Duration: 34.994 ms
     Changes:   
              ----------
              directories_created:
                  - /app/bashrc_minimal/
              extracted_files:
                  - bashrc_minimal
                  - vimrc_minimal
              updated ownership:
                  True
----------
          ID: show_directory
    Function: cmd.run
        Name: ls -lah /app/
      Result: True
     Comment: Command "ls -lah /app/" run
     Started: 18:05:21.417522
    Duration: 509.787 ms
     Changes:   
              ----------
              pid:
                  4110
              retcode:
                  0
              stderr:
              stdout:
                  total 4.0K
                  drwx------   4 soa  soa    37 Apr 28 18:05 .
                  dr-xr-xr-x. 18 root root 4.0K Apr 28 17:07 ..
                  drwxr-xr-x   2 soa  root   47 Apr 28 18:05 bashrc_minimal
                  drwx------   3 soa  soa    23 Apr 28 17:07 soa

Summary for tc7
------------
Succeeded: 3 (changed=2)
Failed:    0
------------
Total states run:     3
Total run time: 561.252 ms
root@Unknown:/srv/salt# 
```

@nweidemann Can you retry this something else where you specifically know what the original user and group the archive were used.

**Comment by nweidemann** [comment]
Here is my test. 
After doing this, the problem with kibana-7.12.1-linux-x86_64.tar.gz seems to be a special thing.
In my test case everything is fine, even with a tgz made by root from a folder containing files that belong to root:root.

tgz files and state are attached. Any clues why this happens with kibana-7.12.1-linux-x86_64.tar.gz ?

I had this already in the past with other software, provided as zip file. Workaround was to chmod -R soa:soa everything that was extracted afterwards in a cmd.run. (I am sorry, but this source I can not provide, because it is licensed enterprise software)



    [RHEL soa@MINION soa_test]$ la soa_test/
    total 4.0K
    drwxrwxr-x.  2 soa soa   32 Apr 30 09:56 .
    drwx------. 22 soa soa 4.0K Apr 30 09:55 ..
    -rw-rw-r--.  1 soa soa    0 Apr 30 09:56 file1
    -rw-rw-r--.  1 soa soa    0 Apr 30 09:56 file2

    [RHEL soa@MINION ~]$ tar cvfz soa_test.tgz soa_test/
    soa_test/
    soa_test/file1
    soa_test/file2

    [RHEL root@MINION soa]$ la root_test/
    total 4.0K
    drwxr-xr-x.  2 root root   32 Apr 30 09:59 .
    drwx------. 23 soa  soa  4.0K Apr 30 09:59 ..
    -rw-r--r--.  1 root root    0 Apr 30 09:59 file1
    -rw-r--r--.  1 root root    0 Apr 30 09:59 file2

    [RHEL root@MINION soa]$ tar cvfz root_test.tgz root_test/
    root_test/
    root_test/file1
    root_test/file2

State execution

    [RHEL root@MASTER ems]$ salt MINION state.sls pbf.sag.kibana.test
    MINION:
    ----------
              ID: install_dir_present
        Function: file.directory
            Name: /app/soa/test_dir
          Result: True
         Comment:
         Started: 10:23:23.371789
        Duration: 13.981 ms
         Changes:
                  ----------
                  /app/soa/test_dir:
                      ----------
                      directory:
                          new
    ----------
              ID: extract_soa
        Function: archive.extracted
            Name: /app/soa/test_dir/
          Result: True
         Comment: salt:///files/pbf/sag/kibana/soa_test.tgz extracted to /app/soa/test_dir/, due to absence of one or more files/dirs. Output was trimmed to 30 number of lines
         Started: 10:23:23.386843
        Duration: 48.245 ms
         Changes:
                  ----------
                  extracted_files:
                      - soa_test
                      - soa_test/file1
                      - soa_test/file2
    ----------
              ID: extract_root
        Function: archive.extracted
            Name: /app/soa/test_dir/
          Result: True
         Comment: salt:///files/pbf/sag/kibana/root_test.tgz extracted to /app/soa/test_dir/, due to absence of one or more files/dirs. Output was trimmed to 30 number of lines
         Started: 10:23:23.435306
        Duration: 19.645 ms
         Changes:
                  ----------
                  extracted_files:
                      - root_test
                      - root_test/file1
                      - root_test/file2
                  updated ownership:
                      True
    ----------
              ID: show_directory
        Function: cmd.run
            Name: echo "soa_test"; ls -lah /app/soa/test_dir/soa_test; echo -e "\nroot_test"; ls -lah /app/soa/test_dir/root_test
          Result: True
         Comment: Command "echo "soa_test"; ls -lah /app/soa/test_dir/soa_test; echo -e "\nroot_test"; ls -lah /app/soa/test_dir/root_test" run
         Started: 10:23:23.456188
        Duration: 95.281 ms
         Changes:
                  ----------
                  pid:
                      5324
                  retcode:
                      0
                  stderr:
                  stdout:
                      soa_test
                      total 0
                      drwxrwxr-x. 2 soa soa 32 Apr 30 09:56 .
                      drwx------. 4 soa soa 39 Apr 30 10:23 ..
                      -rw-rw-r--. 1 soa soa  0 Apr 30 09:56 file1
                      -rw-rw-r--. 1 soa soa  0 Apr 30 09:56 file2

                      root_test
                      total 0
                      drwxr-xr-x. 2 soa soa 32 Apr 30 09:59 .
                      drwx------. 4 soa soa 39 Apr 30 10:23 ..
                      -rw-r--r--. 1 soa soa  0 Apr 30 09:59 file1
                      -rw-r--r--. 1 soa soa  0 Apr 30 09:59 file2

    Summary for MINION
    ------------
    Succeeded: 4 (changed=4)
    Failed:    0
    ------------
    Total states run:     4
    Total run time: 177.152 ms

[test_sources.zip](https://github.com/saltstack/salt/files/6403887/test_sources.zip)

**Comment by nweidemann** [comment]
Additional info..

the man page of tar tells us, that 
    -p, --preserve-permissions
              extract  information  about  file permissions (default for superuser)

It seems that the default for superuser, because MINION runs with root, is stronger than the parameter --user=soa --group=soa

    [RHEL soa@MINION test_dir]$ tar xvfz kibana-7.12.1-linux-x86_64.tar.gz --owner=soa --group=soa

    [RHEL soa@MINION test_dir]$ la
    total 269M
    drwx------.  5 soa soa  114 Apr 30 10:44 .
    drwx------. 22 soa soa 4.0K Apr 30 10:23 ..
    drwxrwxr-x. 10 soa soa  210 Apr 30 10:44 kibana-7.12.1-linux-x86_64
    -rw-r--r--.  1 soa soa 269M Apr 30 10:43 kibana-7.12.1-linux-x86_64.tar.gz

and

    [RHEL root@MINION test_dir]$ tar xvfz kibana-7.12.1-linux-x86_64.tar.gz --owner=soa --group=soa

    [RHEL root@MINION test_dir]$ la
    total 269M
    drwx------.  5 soa  soa   114 Apr 30 10:46 .
    drwx------. 22 soa  soa  4.0K Apr 30 10:23 ..
    drwxr-xr-x. 10 root root  210 Apr 30 10:47 kibana-7.12.1-linux-x86_64
    -rw-r--r--.  1 soa  soa  269M Apr 30 10:43 kibana-7.12.1-linux-x86_64.tar.gz

I can try to report this as a bug to bug-tar@gnu.org

But it does not explain why the same thing happened with zip files before.

**Comment by nweidemann** [comment]
Answer from bug-tar@gnu.org

nweidemann ha escrit:

> [RHEL soa@MINION test_dir]$ tar xvfz kibana-7.12.1-linux-x86_64.tar.gz 
> --owner=soa --group=soa

The options --owner and --group take effect only when *creating* the archive, not when *extracting* from it.  Please see [1].

Regards,
Sergey

[1] https://www.gnu.org/software/tar/manual/html_node/override.html#index-owner

**Comment by dmurphy18** [comment]
@nweidemann Actually my point was that from a test.tar.gz with some simple files which originally had david:david as owner:group, it appears to work with the override of soa (had to create that user and group on the machine first).  The other parts with --owner etc was me trying other approaches, thanks for that additional info.

Hence wondering how kibana tar ball was put together, since the code appears to be working correctly with the test case I generated.

**Comment by nweidemann** [comment]
Don't know what we can do here to get the problem solved...

I can add more information if I notice that this happens again with another package

**Comment by dmurphy18** [comment]
@nweidemann If you has a copy of the exact package which gave you the problem that would help in recreating what you experienced and I could investigate it further.  Otherwise, please consider closing this issue and opening a new issue if the problem reoccurs, and include the offending tar ball with the issue.

**Comment by nweidemann** [comment]
The package is

source file for kibana: https://artifacts.elastic.co/downloads/kibana/kibana-7.12.1-linux-x86_64.tar.gz

I thought you had the same issues with this package as I experienced.

**Comment by dmurphy18** [comment]
That is the exact package I used since you referenced it above and had no issue with it.  Wonder if you had a bad download, did you check the sha sums for what you downloaded ?

**Comment by nweidemann** [comment]
> Confirmed with Salt 3002, and after ensuring user and group **soa** exists on Centos 7 machine, and where test_archive.sls is equivalent to test.sls in test.zip
> 
> ```
> root@Unknown:/srv/salt# salt tc7 state.sls test_archive
> tc7:
> ----------
>           ID: install_dir_present
>     Function: file.directory
>         Name: /app/soa/softwareag/kibana/
>       Result: True
>      Comment: Directory /app/soa/softwareag/kibana updated
>      Started: 17:07:03.446841
>     Duration: 41.219 ms
>      Changes:   
>               ----------
>               /app/soa/softwareag/kibana:
>                   New Dir
> ----------
>           ID: extract_kibana
>     Function: archive.extracted
>         Name: /app/soa/softwareag/kibana/7.12.1
>       Result: True
>      Comment: salt:///kibana-7.12.1-linux-x86_64.tar.gz extracted to /app/soa/softwareag/kibana/7.12.1/, due to absence of one or more files/dirs. Output was trimmed to 30 number of lines
>      Started: 17:07:03.489259
>     Duration: 34768.331 ms
>      Changes:   
>               ----------
>               directories_created:
>                   - /app/soa/softwareag/kibana/7.12.1/
>               extracted_files:
>                   - kibana-7.12.1-linux-x86_64/.i18nrc.json
>                   - kibana-7.12.1-linux-x86_64/LICENSE.txt
>                   - kibana-7.12.1-linux-x86_64/NOTICE.txt
>                   - kibana-7.12.1-linux-x86_64/README.txt
>                   - kibana-7.12.1-linux-x86_64/bin
>                   - kibana-7.12.1-linux-x86_64/bin/kibana
>                   - kibana-7.12.1-linux-x86_64/bin/kibana-encryption-keys
>                   - kibana-7.12.1-linux-x86_64/bin/kibana-keystore
>                   - kibana-7.12.1-linux-x86_64/bin/kibana-plugin
>                   - kibana-7.12.1-linux-x86_64/config
>                   - kibana-7.12.1-linux-x86_64/config/kibana.yml
>                   - kibana-7.12.1-linux-x86_64/config/node.options
>                   - kibana-7.12.1-linux-x86_64/data
>                   - kibana-7.12.1-linux-x86_64/node
>                   - kibana-7.12.1-linux-x86_64/node/CHANGELOG.md
>                   - kibana-7.12.1-linux-x86_64/node/LICENSE
>                   - kibana-7.12.1-linux-x86_64/node/README.md
>                   - kibana-7.12.1-linux-x86_64/node/bin
>                   - kibana-7.12.1-linux-x86_64/node/bin/node
>                   - kibana-7.12.1-linux-x86_64/node/include
>                   - kibana-7.12.1-linux-x86_64/node/include/node
>                   - kibana-7.12.1-linux-x86_64/node/include/node/common.gypi
>                   - kibana-7.12.1-linux-x86_64/node/include/node/config.gypi
>                   - kibana-7.12.1-linux-x86_64/node/include/node/cppgc
>                   - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/allocation.h
>                   - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/common.h
>                   - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/custom-space.h
>                   - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/garbage-collected.h
>                   - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/heap.h
>                   - kibana-7.12.1-linux-x86_64/node/include/node/cppgc/internal
> ----------
>           ID: show_directory
>     Function: cmd.run
>         Name: ls -lah /app/soa/softwareag/kibana/7.12.1/
>       Result: True
>      Comment: Command "ls -lah /app/soa/softwareag/kibana/7.12.1/" run
>      Started: 17:07:38.260562
>     Duration: 661.872 ms
>      Changes:   
>               ----------
>               pid:
>                   3441
>               retcode:
>                   0
>               stderr:
>               stdout:
>                   total 4.0K
>                   drwxr-xr-x  3 soa  root   39 Apr 28 17:07 .
>                   drwx------  3 soa  soa    19 Apr 28 17:07 ..
>                   drwxr-xr-x 10 root root 4.0K Apr 28 17:07 kibana-7.12.1-linux-x86_64
> 
> Summary for tc7
> ------------
> Succeeded: 3 (changed=3)
> Failed:    0
> ------------
> Total states run:     3
> Total run time:  35.471 s
> root@Unknown:/srv/salt#
> ```
> 
> However just running the command to untar with owner and group on Centos 7 ignores those settings, for example:
> 
> ```
> tar -xvzf kibana-7.12.1-linux-x86_64.tar.gz --owner=soa --group=soa 
> root@Unknown:/tmp# ls -alh kib*
> -rw-r--r--.  1 root root 269M Apr 28 17:00 kibana-7.12.1-linux-x86_64.tar.gz
> 
> kibana-7.12.1-linux-x86_64:
> total 1.5M
> drwxr-xr-x.  10 root root 4.0K Apr 28 17:20 .
> drwxrwxrwt.  48 root root 4.0K Apr 28 17:19 ..
> drwxr-xr-x.   2 root root   90 Apr 20 14:34 bin
> drwxr-xr-x.   2 root root   42 Apr 20 14:34 config
> drwxr-xr-x.   2 root root    6 Apr 20 14:34 data
> -rw-r--r--.   1 root root 3.0K Apr 20 14:34 .i18nrc.json
> -rw-r--r--.   1 root root 3.8K Apr 20 14:34 LICENSE.txt
> drwxr-xr-x.   6 root root  101 Apr 20 14:34 node
> drwxr-xr-x. 831 root root  24K Apr 20 14:34 node_modules
> -rw-r--r--.   1 root root 1.4M Apr 20 14:34 NOTICE.txt
> -rw-r--r--.   1 root root  740 Apr 20 14:34 package.json
> drwxr-xr-x.   2 root root    6 Apr 20 14:34 plugins
> -rw-r--r--.   1 root root 3.9K Apr 20 14:34 README.txt
> drwxr-xr-x.  12 root root 4.0K Apr 20 14:34 src
> drwxr-xr-x.   3 root root   75 Apr 20 14:34 x-pack
> root@Unknown:/tmp# 
> ```
> 
> So this may be an issue with the underlying command on the OS, given Salt call the tar command on the OS, see
> 
> https://github.com/saltstack/salt/blob/b3c3b52693b90c5c17f46511179acac6d15fd153/salt/modules/archive.py#L530-L542
> 
> If it is due to an issue with the underlying OS tar command, then Salt relies on the OS functionality provided.


You have the same issue, that the user/group parameters of the archive.extracted state module are ignored?! Or am I wrong now?

**Comment by dmurphy18** [comment]
@nweidemann Yes, the problem is with the underlying command on the OS, in that, we call down to the OS to perform the command, and Salt is limited by the command's functionality on the OS.

I too experienced the same owner and group being ignored by tar on Centos 7, and also on Ubuntu 20.04.2,
But I believe these options are only valid during creation of a tarball and not during it's extraction.  From tar man page https://man7.org/linux/man-pages/man1/tar.1.html

```       --owner=NAME[:UID]
              Force NAME as owner for added files.  If UID is not
              supplied, NAME can be either a user name or numeric UID.
              In this case the missing part (UID or name) will be
              inferred from the current host's user database.
```
Similarly
```
       --group=NAME[:GID]
              Force NAME as group for added files.  If GID is not
              supplied, NAME can be either a user name or numeric GID.
              In this case the missing part (GID or name) will be
              inferred from the current host's group database.
```
That is,  these options are only valid when used creating the tarball archive with the tar command, and SaltStack is limited by the commands implementation.  Note my earlier answer in the comments that the options worked when creating a sample tarball.

If the answer is satisfactory, please consider closing this issue, or add additional information to understand the issue encountered.

**Comment by nweidemann** [comment]
Ok, I think I have to accept this behavior.

Do not understand why it works with the permissions and a self created tarball archive, which in contrary to "the parameters are only vaild at creation not on extraction", but I see that the behavior of Salt ist the same like on OS layer.

So that should be an issue with the tarball itself.

I will close the issue.

thanks for your support.
