### ISSUE TITLE
[BUG] The salt-master no longer reads LimitNOFILE from /etc/systemd/system/salt-master.service.d/filelimit.conf

### ISSUE THREAD

**Issue by marbx** [saltstack/salt#60122]
**Description**
The salt-master no longer reads LimitNOFILE from /etc/systemd/system/salt-master.service.d/filelimit.conf

**Setup**
```
cat /etc/systemd/system/salt-master.service.d/filelimit.conf 

[Service]
LimitNOFILE=887221
```
**Steps to Reproduce the behavior**
```
sudo systemctl daemon-reload
sudo systemctl start salt-master
sudo grep CRITICAL /var/log/salt/master

2021-05-03 15:40:08,517 [salt.utils.verify:490 ][CRITICAL][19239] The number of accepted minion keys(34377) should be lower than 1/4 of the max open files soft setting(4096). salt-master will crash pretty soon! Please consider raising this value.
```

**Expected behavior**
```
files soft setting(4096) 
```

should read 

```
files soft setting(887221) 
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.25.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
Salt shouldn't be "reading" any of that config. Systemd manages it and sets the limits on what it spawns. Salt simply shouldn't touch its own limits at all.

**Comment by markuskramerIgitt** [comment]
> Salt shouldn't be "reading" any of that config. Systemd manages it and sets the limits on what it spawns. Salt simply shouldn't touch its own limits at all.

Could you please rephrase? I don't understand

**Comment by OrangeDog** [comment]
> Could you please rephrase?

That isn't salt's config, it's systemd's config. Salt isn't supposed to be in charge of setting its limits.

**Comment by markuskramerIgitt** [comment]
I don't know if Salt set the limits, I only know it emits this warning.
But Salt does no longer read the relevant systemd configuration.

**Comment by mattp-** [comment]
what is the output of systemctl cat salt-master.service| grep -i nofile ?

**Comment by markuskramerIgitt** [comment]
@mattp, I had to remove 3003 due to issue #60049

**Comment by OrangeDog** [comment]
@markuskramerIgitt Salt has never read the systemd configuration. It's not supposed to. That is what I have been trying to explain.

**Comment by markuskramerIgitt** [comment]
@gtmanfred, in 2017, suggested to [use a systemd dropin](https://github.com/saltstack/salt/pull/39957#issuecomment-303817105).

I assume that Salt does no read the propin as a file, but so far the LimitNOFILE setting was processed, between 2017 and recentlty.

How do you suggest to change the setting?

**Comment by markuskramerIgitt** [comment]
I just found that the salt-master debian package sets the value: 
https://github.com/saltstack/salt/blob/4f3cb36955d84c6793efcbeabf53963067922d90/pkg/deb/salt-master.service#L6

**Comment by eliasp** [comment]
As SaltStack itself just uses `resource.getrlimit()` to retrieve the effective limits of the executed process, I just wanted to briefly verify what's going on here and found the following weird behaviour on a Ubuntu 20.04 LTS system:

- Create `/etc/systemd/system/salt-master.service.d/debuglimits.conf`
- ```ini
  [Service]
  LimitNOFILE=6144:8192
  Type=simple
  ExecStart=
  ExecStart=/usr/bin/python3 -c "import resource; print(resource.getrlimit(resource.RLIMIT_NOFILE));"
  ```
- Execute `systemctl daemon-reload`
- Execute `systemctl start salt-master`
- Execute `journalctl -n5 -u salt-master`:
  ```
  May 05 14:20:29 dai-2004-salt-master systemd[1]: Started The Salt Master Server.
  May 05 14:20:29 dai-2004-salt-master python3[32205]: (4096, 4096)
  May 05 14:20:29 dai-2004-salt-master systemd[1]: salt-master.service: Succeeded.
  ```
- Execute `systemctl show salt-master | grep '^LimitNOFILE'`:
  ```
  LimitNOFILE=8192
  LimitNOFILESoft=6144
  ```

This is rather strange, as this indicates that the values defined for the unit are effective within systemd's execution context, but are not applied to the actual service process.
I could understand this happening for a full `salt-master` service process, where this might happen due to the following fact:

> [Note that most process resource limits configured with these options are per-process, and processes may fork in order to acquire a new set of resources that are accounted independently of the original process, and may thus escape limits set. Also note that LimitRSS= is not implemented on Linux, and setting it has no effect. Often it is advisable to prefer the resource controls listed in systemd.resource-control(5) over these per-process limits, as they apply to services as a whole, may be altered dynamically at runtime, and are generally more expressive. For example, MemoryMax= is a more powerful (and working) replacement for LimitRSS=.](https://www.freedesktop.org/software/systemd/man/systemd.exec.html#LimitCPU=)

But this indicates there must be a problem with Python's `resource.getrlimit()`, but this once again seems rather implausible to me, as it just uses a plain `getrlimit()` syscall and does no magic like parsing a system's `limits.conf`, systemd's `/etc/systemd/system.conf` or something like that.

**Comment by markuskramerIgitt** [comment]
> what is the output of systemctl cat salt-master.service| grep -i nofile ?
```
LimitNOFILE=880000
LimitNOFILE=887221
```

The first is from Salt, the second from me

**Comment by markuskramerIgitt** [comment]
Right after  the line @eliasp mentioned I temporarily added logging to the  3002.6 salt-master and found no issue.

``` 

diff /lib/python3.6/site-packages/salt/utils/verify.py /lib/python3.6/site-packages/salt/utils/verify.pybackup

460,461d459

<     log.error("show mof_h %s", mof_h)
<     log.error("show mof_s %s", mof_s)

 
 

grep show /var/log/salt/master

2021-05-10 18:39:36,987 [salt.utils.verify:460 ][ERROR   ][16170] show mof_h 887221
2021-05-10 18:39:36,989 [salt.utils.verify:461 ][ERROR   ][16170] show mof_s 887221

 
```

**Comment by marbx** [comment]
No longer an issue
