### ISSUE TITLE
[TEST FAILURE] Linode Cloud Tests are Failing

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#60147]
The tests:

```
tests.integration.cloud.clouds.test_linode.LinodeTest.test_instance
tests.integration.cloud.clouds.test_linode.LinodeTest.test_instance_v4
```

are failing.

**Comment by sagetherage** [comment]
Looks like this hasn't been passing since 2021-APR-27 https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-cloud-pytest/job/master/87/

**Comment by Ch3LL** [comment]
this is passing now. I had to create a new v4 api key with more permissions. Also the v3 key had expired so i created a new one there as well.
