### ISSUE TITLE
[BUG]  Winrepo pkg.installed fails using state.apply in the UI but works using pkg.install from command line

### ISSUE THREAD

**Issue by karlhauck** [saltstack/salt#60167]
**Description**
Winrepo pkg.installed fails using state.apply in the UI but works using pkg.install from command line.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info).

root@ssc-01a [ /srv/salt/win/repo-ng ]# ls
remote_map.txt  salt-winrepo-ng  vscode2
root@ssc-01a [ /srv/salt/win/repo-ng ]#

vscode2:
  '1.56.0':
    full_name: Microsoft Visusal Studio Code
    installer: salt://win/repo-ng/vscode2/VSCodeSetup-x64-1.56.0.exe
    install_flags: /VERYSILENT /MERGETASKS=!runcode
    uninstaller: C:\Program Files\Microsoft VS Code\unins000.exe
    uninstall_flags: /VERYSILENT /NORESTART
    msiexec: False
    reboot: False

**Steps to Reproduce the behavior**
Create a job using the SSE interface.   Here is the install.sls file in/base/windows/vscodeinstall.  The return should be success since the software gets installed.  I had the same issues with 7zip.

vscodinstall:
  pkg.installed:
    - name: vscode2
    - refresh: False
    - 
[
  {
    "return": {
      "pkg_|-vscodinstall_|-vscode2_|-installed": {
        "name": "vscode2",
        "__id__": "vscodinstall",
        "result": false,
        "__sls__": "windows.vscodinstall.install",
        "changes": {
          "vscode2": {
            "install status": "success"
          }
        },
        "comment": "The following packages failed to install/update: vscode2",
        "duration": 23343.805,
        "start_time": "13:32:13.630589",
        "__run_num__": 0
      }
    },
    "master_uuid": "71d2c715-ef76-4eb0-8992-575fd1aea333",
    "minion_id": "windows01",
    "jid": "20210510192044858766",
    "fun": "state.apply",
    "alter_time": "2021-05-10T19:21:19.521466",
    "full_ret": {
      "id": "windows01",
      "cmd": "_return",
      "fun": "state.apply",
      "jid": "20210510192044858766",
      "out": "highstate",
      "_stamp": "2021-05-10T19:21:19.493820",
      "return": {
        "pkg_|-vscodinstall_|-vscode2_|-installed": {
          "name": "vscode2",
          "__id__": "vscodinstall",
          "result": false,
          "__sls__": "windows.vscodinstall.install",
          "changes": {
            "vscode2": {
              "install status": "success"
            }
          },
          "comment": "The following packages failed to install/update: vscode2",
          "duration": 23343.805,
          "start_time": "13:32:13.630589",
          "__run_num__": 0
        }
      },
      "retcode": 2,
      "success": false,
      "fun_args": [
        {
          "mods": "windows.vscodinstall.install"
        }
      ],
      "_master_path": [
        "saltstack_enterprise_installer"
      ]
    },
    "has_errors": true,
    "master": "salt",
    "fun_args": [
      {
        "mods": "windows.vscodinstall.install"
      }
    ],
    "cmd": null,
    "user": null,
    "job_name": null,
    "job_uuid": null,
    "tgt_name": null,
    "tgt_uuid": null,
    "low": null,
    "job_source": null
  }
]

**Expected behavior**
The complete return should be success.

**Screenshots**

**Versions Report**
SSC Enterprise 8.4.0+8
```
PASTE HERE
```
</details>

**Additional context**

**Comment by karlhauck** [comment]
Yes.  That is correct.  I am running it on Photon FYI

**Comment by xeacott** [comment]
Gotcha. This might not be the correct place to open a ticket, as this repository is only for the Salt open project and not for our Enterprise solutions. Let me see if I can get you better contact.

**Comment by sagetherage** [comment]
@doesitblend @whytewolf this looks like an Enterprise issue - closing
