### ISSUE TITLE
pillar data for reactor

### ISSUE THREAD

**Issue by speedytom** [saltstack/salt#60180]
**Description**
We don't get pillar data for reactor

**Setup**
   
root@salt:/srv/salt# salt --versions-report
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-70-generic
        system: Linux
       version: Ubuntu 20.04 focal
 

  

**Steps to Reproduce the behavior**
   root@salt:/srv/salt# cat reactor/email-on-failure.sls.210510 
     {% set sendMail = salt['pillar.get']('LOG_MAIL') %}
    {% if sendMail == 'Y' %}
    email-on-failure:
      runner.mail_sender.email_errors:
        - recipient: fridrich@ipp.cas.cz, tokos@ipp.cas.cz
        - sender: salt-info@salt.tok.ipp.cas.cz
        - smtp: mail.tok.ipp.cas.cz
        - data: {{ data|yaml_dquote }}
    {% endif %}

root@salt:/srv/salt# cat _runners/mail_sender.py
import json
from salt.modules.smtp import send_msg

mesg_template = """
Minion id:
{id}

Function:
{fun}

Return code:
{retcode}

Errors:
{returns}

You can run the following command for details:
salt-run jobs.lookup_jid {jid}
"""

def email_errors(sender,recipient,smtp,data):
    # Report only these:
    to_report = ("state.highstate", "state.apply")
    d = eval(data)
    if d['fun'] in to_report:
        subj = "Salt job {jid} failed on minion {id}".format(**d)
        # Let's report something instead of error in salt master log
        mesg = data
        if str(d['retcode']) != "0":
            try:
                ret = d.get('return',dict())
                if isinstance(ret,dict):
                    # Go through the dict and pick only failed results
                    failed = []
                    for k,v in ret.items():
                        if not v.get("result",False):
                            failed.append("sls = \"{}\"\nid = \"{}\"\nerror = \"{}\"".format(v.get("__sls__",None),
                                                                                             v.get("__id__",None),
                                                                                             v.get("comment"),None))
                    d['returns'] = "\n-----------\n".join(failed)
                else:
                    d['returns'] = "\n".join(ret)
                mesg = mesg_template.format(**d)
            except Exception as e:
                mesg += "\nException caught: \n{}".format(repr(e))
            send_msg(recipient,
                     mesg,
                     sender=sender,
                     subject=subj,
                     use_ssl=False,
                     server=smtp)

 salt 'tokos1*' pillar.data 'pillarenv=qa' -ldebug

root@salt:~# cat /srv/pillar_qa/variables.sls
LOG_MAIL: 'N'root@salt:~# 
root@salt:~# 
root@salt:~# cat /srv/pillar/variables.sls
LOG_MAIL: 'Y'root@salt:~# 

**Expected behavior**
Don't send errors by email for pillarevn=qa.
Send message for pillarevn 'base'

.

**Comment by speedytom** [comment]
[email-on-failure.sls.210510.txt](https://github.com/saltstack/salt/files/6471811/email-on-failure.sls.210510.txt)
[mail_sender.py.txt](https://github.com/saltstack/salt/files/6471812/mail_sender.py.txt)

**Comment by whytewolf** [comment]
this is expected behavior. reactors are not run on the minion they are run on the master. and the master is not running it in any kind of regard for a minion. it is just parsing the data given it and going through it. if you want to get pillars of the minion you need to query the minion. this is also not advised internally to the reactor and would be better to ship this to an orchestration at that point. this is because reactors need to do the render and move on as fast as possible. other wise they can block up the event bus and cause all sorts of problems.

**Comment by speedytom** [comment]
OK. I understand.

Do you have any option how to disable send emails by environment variable?
Thanks for your answer.

**Comment by sagetherage** [comment]
@speedytom you may want to pose your question in the [mailing list forum for salt-users](https://groups.google.com/forum/#!forum/salt-users), ask on [IRC](http://webchat.freenode.net/?channels=salt&uio=Mj10cnVlJjk9dHJ1ZSYxMD10cnVl83), or in our [community slack workspace](https://saltstackcommunity.slack.com/) for a better conversation platform.
