### ISSUE TITLE
[BUG] salt-master returns every minute [ERROR   ] Exception during resolving address: [Errno 2] Host name lookup failure

### ISSUE THREAD

**Issue by doc75** [saltstack/salt#60197]
**Description**

In `/var/log/syslog` on the salt master I can see the following error message raised 3 consecutive times every single minute:
```
May 16 00:13:19 <hostname removed> salt-master[990]: [ERROR   ] Exception during resolving address: [Errno 2] Host name lookup failure
May 16 00:13:19 <hostname removed> salt-master[990]: [ERROR   ] Exception during resolving address: [Errno 2] Host name lookup failure
May 16 00:13:19 <hostname removed> salt-master[990]: [ERROR   ] Exception during resolving address: [Errno 2] Host name lookup failure
```

It seems to be harmless, but as this is raised as an error, this is not good to have such message in the log (risk to miss other errors).

**Setup**
No specific setup, it seems that having a docker configuration on the salt master could lead to this error (see more info below)

**Steps to Reproduce the behavior**
I activate the debug log but no specific information is shown related to this error.
I modified the file modules/network.py to add the IP address that is causing the error, and the log is the following:
```
May 16 09:46:13 kactus salt-master[466453]: [ERROR   ] Exception during resolving address: [Errno 2] Host name lookup failure - ip=172.17.0.1
May 16 09:46:13 kactus salt-master[466451]: [ERROR   ] Exception during resolving address: [Errno 2] Host name lookup failure - ip=172.17.0.1
May 16 09:46:13 kactus salt-master[466455]: [ERROR   ] Exception during resolving address: [Errno 2] Host name lookup failure - ip=172.17.0.1
```

It appears that this local IP address is the one related to `docker0` (salt is not in a docker container and is not managing the configuration of any docker container)

**Expected behavior**
No error message should be raised

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-72-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**
None

Please do not hesitate to let me know if you need more information or if I can modify `network.py` file to get more clues.

**Comment by sagetherage** [comment]
This is working as expected, but this is on by default and you can turn it off here are the docs: https://docs.saltproject.io/en/latest/ref/configuration/minion.html#enable-fqdns-grains
We do recognize the error should be a warning and can put this as a backlog item to update to warn

**Comment by stappersg** [comment]
> I activate the debug log but no specific information is shown related to this error.
> I modified the file modules/network.py to add the IP address that is causing the error, and the log is the following:

Nice

**Comment by doc75** [comment]
@sagetherage it seems that the issue is not reproducible anymore with the latest version (3003.1).
Indeed, the error did not appear since June 24th (date when I upgrade from 3003 to 3003.1.

I propose to close this issue unless you think that you still need to check something on this.

**Comment by sagetherage** [comment]
@doc75 thank you!!
