### ISSUE TITLE
gitfs_saltenv per-environment directive does not work with fallback gitfs directive

### ISSUE THREAD

**Issue by rnickle** [saltstack/salt#60190]
**Description**
The per-saltenv configuration parameters section of the documentation describes the *gitfs_saltenv* directive.

**Setup**
I am successfully using gitfs_remotes with the _fallback_ directive, example:

```
gitfs_remotes:
  - http://bse/salt.git
    - root: ''
    - base: test
    - fallback: test
```

**Steps to Reproduce the behavior**
When I check my cp.list_master output, I am expecting to see content for the 'public' repository from the 'test' branch when I use the 'saltenv=user1' directive, because there is no 'user1' branch or tag in that repo.  This works fine when the fallback directive is applied as above to my gitfs_remotes entry for the repository.

```
> sudo salt 'bse*' cp.list_master saltenv=user1 | grep 'x/README.md'
    - public/README.md
```

**Expected behavior**
If I try to apply the same directive as a global using gitfs_saltenv and remove the per-remote entries:

```
gitfs_saltenv:
  - user1:
    - fallback: test
```
> sudo salt 'bse*' cp.list_master saltenv=user1 | grep 'x/README.md'

I do no have any errors on the master or the minion, but the fallback directive is not applied, so the expected query that worked with a per-remote directive does not return data.

**Screenshots**
I'm including a discussion of the issue on the slack channel:

https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1621027424061300

![image](https://user-images.githubusercontent.com/32749826/118336243-4861ae80-b4df-11eb-8a3e-6ac3e64cabf4.png)

**Versions Report**
<details>

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.5
     gitpython: 2.1.11
        Jinja2: 2.10
       libgit2: 0.27.7
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: 3.9.4
  pycryptodome: 3.6.1
        pygit2: 0.27.4
        Python: 3.7.3 (default, Apr  3 2019, 05:39:12)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-6-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Additional context**
I also tried setting the variable as a global (_gitfs_fallback: test_ and _fallback: test_.  Those did not work either.)  The documentation on fallback could use some clarification and enhancement.

**Comment by waynew** [comment]
@rnickle This does behave exactly as you describe - https://docs.saltproject.io/en/latest/topics/tutorials/gitfs.html#per-saltenv-configuration-parameters

However, that seems to indicate:

> For more granular control, Salt allows the following three things to be overridden for individual saltenvs within a given repo:
>    - The mountpoint
>    - The root
>    - The branch/tag to be used for a given saltenv

That fallback is *not* one of the values that's supported in this option. Is that how you read that, or should we clarify the docs somehow?

**Comment by waynew** [comment]
@rnickle I'm going to close this issue for now - if it's still an issue or an issue with the documentation, let me know and I'll re-open!
