### ISSUE TITLE
[BUG] On 3003 grains.get returns an empty string when called from minion's id_function

### ISSUE THREAD

**Issue by max-arnold** [saltstack/salt#60219]
**Description**

Since salt 3003, the `id_function` minion option that utilizes grains (useful for generating unique minion IDs based on hardware properties, especially with custom grains) returns an empty string.

```
[ERROR   ] Function grains.get returned value "" of type <class 'str'> instead of string
```

**Steps to Reproduce the behavior**

1. Install salt-minion
2. Stop it: `service salt-minion stop`
3. Remove the cached minion id: `rm -f /etc/salt/minion_id`
4. Add the following configuration snippet

```
# /etc/salt/minion.d/id.conf
id_function:
  grains.get:
    key: uuid
```

5. Run `salt-call --local test.ping`

```
[ERROR   ] Function grains.get returned value "" of type <class 'str'> instead of string
```

It works fine on Salt 3002.6 (`/etc/salt/minion_id` is populated with the `uuid` grain value). I have a feeling that the issue might be caused by loader contexts https://github.com/saltstack/salt/pull/58853

Cc: @dwoz 

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-58-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Comment by doesitblend** [comment]
I believe I am running into a similar issue using this state:

```
{% set env = salt['grains.get']('env','dev') %}
{% if 'unknown' in env %}
{% set env = salt['grains.get']('environment','dev') %}
{% endif %}

echo variables:
  cmd.run:
    - name: echo "{{ env }}"
```

Here I expect the value 'dev' to be output, but I get the value for the 'environment' key instead. For whatever reason, the lookup for the 'env' key is returning 'unknown' as the value. Seems there could be a bug in utils/data.py:traverse_dict_and_list function?
