### ISSUE TITLE
Add capirca to Arista native minions

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#60223]
Add capirca to Arista native minions

**Comment by sagetherage** [comment]
It can't be a bug and an enhancement, pick one.

**Comment by dmurphy18** [comment]
Testing capirca with Arista build for Salt 3003.1

**Comment by dmurphy18** [comment]
Unable to have capirca and M2Crypto on 32-bit Arista due to size limitations for swix package, namely needs to be under 65MB in size.  Had to remove installing these modules to reduce size, coming in at 64 MB, just under the wire.

**Comment by dmurphy18** [comment]
capirca has been added to the master branch and is available only for the 64-bit builds (see previous comment).
It should be available when 64-bit Salt 3003.1 support for Arista is released, soon.

Hence closing this issue
