### ISSUE TITLE
[BUG] Add capirca and napalm to Juniper native minion

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#60224]
Add capirca and napalm to Juniper native minion

**Comment by dmurphy18** [comment]
During development of the Juniper native minion, attempts were made to include napalm but issues were run into.  This was over a year ago so details are missing.

However will retry and log details of issue, if memory is correct, there were conflicts with Junos (FreeBSD)

**Comment by sagetherage** [comment]
It can't be a bug and an enhancement so pick one.

**Comment by dmurphy18** [comment]
Closing this since the support for Juniper has been moved to community support, see https://github.com/vmware/salt-native-minion-for-juniper
