### ISSUE TITLE
[BUG] Graceful exit throws an exception

### ISSUE THREAD

**Issue by uhthomas** [saltstack/salt#60242]
**Description**
Salt throws an exception when gracefully terminating.

**Setup**
Single master/minion with no config.

**Steps to Reproduce the behavior**

Run any salt command and then CTRL+C.

```
# salt '*' test.version
^C
Exiting gracefully on Ctrl-c
This job's jid is: 20210524155349599775
The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:

salt-run jobs.lookup_jid 20210524155349599775
[ERROR   ] Exception in callback None
Traceback (most recent call last):
  File "/nix/store/pldkmlc00xf66ihqpgi1hw1c3kiy8g3d-salt-3003/lib/python3.8/site-packages/salt/ext/tornado/ioloop.py", line 889, in start
    fd_obj, handler_func = self._handlers[fd]
KeyError: 18
Exception ignored in: <generator object IPCMessageSubscriber._read at 0x7fd93b4b3820>
Traceback (most recent call last):
  File "/nix/store/pldkmlc00xf66ihqpgi1hw1c3kiy8g3d-salt-3003/lib/python3.8/site-packages/salt/transport/ipc.py", line 695, in _read
TypeError: catching classes that do not inherit from BaseException is not allowed
```

**Expected behavior**
A nice, graceful exit.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
# salt --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.9 (default, Apr  2 2021, 11:20:07)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.0.3
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: nixos 21.05pre-git okapi
        locale: utf-8
       machine: x86_64
       release: 5.10.37
        system: Linux
       version: NixOS 21.05pre-git okapi
```
</details>

**Additional context**
N/A

**Comment by sagetherage** [comment]
similar issue: https://github.com/saltstack/salt/issues/59618

**Comment by MKLeb** [comment]
I have successfully reproduced this locally... will start working on a fix.

**Comment by MKLeb** [comment]
Actually, I have only been able to get the
`Exception ignored in: <generator object IPCMessageSubscriber._read at 0x7fd93b4b3820>
Traceback (most recent call last):
  File "/nix/store/pldkmlc00xf66ihqpgi1hw1c3kiy8g3d-salt-3003/lib/python3.8/site-packages/salt/transport/ipc.py", line 695, in _read
TypeError: catching classes that do not inherit from BaseException is not allowed`
piece to reproduce locally.

Are you referencing the `[ERROR   ] Exception in callback None` piece or the ignored exception @uhthomas ?

**Comment by MKLeb** [comment]
Similar issues: https://github.com/saltstack/salt/pull/60972 https://github.com/saltstack/salt/issues/60963
