### ISSUE TITLE
[BUG] 3003 sdb.get with strict=True returns incorrect error message when key/value missing

### ISSUE THREAD

**Issue by oliver-dungey** [saltstack/salt#60245]
**Description**
`sd.get` has an optional parameter `strict` which defaults to `False`. This feature was added last year here: https://github.com/saltstack/salt/pull/57630

The documentation says ` If the uri provided is not valid, then it will be returned as-is, unless strict=True was passed.` but it does not say what it will return. In my case the error returned is:

`ERROR executing 'sdb.get': SDB profile "vault" wasnt found in the minion configuration` when running:

But the error message is misleading as the profile "vault" was found, does exist and the minion configuration is correct, it just doesn't have the value `some-system:password` set in it. That is what the error message should say.

So why is a bit of vague documentation and an inaccurate error message a problem? I spent ages trying to diagnose what was wrong with my vault configuration until I realised it was nothing to do with that and was purely a missing key/value. The fix should just be an improvement to the documentation and error messages.

**Setup**
Vault config:
```
vault:
  driver: yaml
  files:
    - /etc/salt/vault/vault.yaml
```
Vault file:
```
some-system:
  user: blahblahblah
```
CLI call to sdb:
```
 salt 'minion' sdb.get sdb://vault/some-system:password strict=True
```
**Versions Report**
```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 4.19.128-microsoft-standard
        system: Linux
       version: CentOS Linux 7 Core
```

**Comment by MKLeb** [comment]
@oliver-dungey I have been unable to reproduce this issue, as it just returns `None` if there is no value for a given key.  As far as I can tell, the only way the error you got is thrown is if `strict=True` and there is no valid configuration on the minion.  See [this](https://github.com/saltstack/salt/blob/3d17d1dd4e160cb96350bc07583df335fc7ca1a8/salt/utils/sdb.py#L46) for when it was added.  Is it possible that your vault config was unable to be parsed for any reason?  I'm looking to close this issue without changes unless you have any opinions on this.

**Comment by oliver-dungey** [comment]
Thanks for debugging @MKLeb. I've just been through the logic again and all I can think is that Salt had not loaded the configuration at the time as the config all looks good. Sadly I can't re-test as I'm in a new job and don't have access to the code anymore. Closing
