### ISSUE TITLE
python api Parameter definition 

### ISSUE THREAD

**Issue by misrn** [saltstack/salt#60248]
curl -v http://127.0.0.1:58080/ -H "Accept: application/x-yaml" -H "X-Auth-Token: 72d32bf87eb543cc6eb52cb9dda6bfc002a148a2" -d client='local' -d tgt='*' -d fun='cmd.run' -d arg='ip -a' -d arg='runas=nginx' 

python code

import urllib
import urllib.request
import urllib.parse
import json

class SaltAPI(object):
    __token_id = ''

    def __init__(self, url, user, password):
        self.__url = url
        self.__user = user
        self.__password = password

    def token_id(self):
        params = {'eauth': 'pam', 'username': self.__user, 'password': self.__password}
        encode = urllib.parse.urlencode(params)
        obj = urllib.parse.unquote(encode).encode('utf-8')
        content = self.post_request(obj, prefix='/login')
        try:
            self.__token_id = content['return'][0]['token']
        except KeyError:
            raise KeyError

    def post_request(self, obj, prefix='/'):
        url = self.__url + prefix
        headers = {'X-Auth-Token': self.__token_id}
        req = urllib.request.Request(url, obj, headers)
        opener = urllib.request.urlopen(req)
        content = json.loads(opener.read().decode('utf-8'))
        return content

    def remote_execution_single(self, tgt, fun, arg=None, **kwargs):
        params = {'client': 'local', 'tgt': tgt, 'fun': fun, 'arg': arg, 'kwargs': kwargs}
        obj = urllib.parse.urlencode(params).encode('utf-8')
        self.token_id()
        content = self.post_request(obj)
        ret = content['return']
        return ret

sa = SaltAPI(url='http://127.0.0.1:58080', user='saltapi', password='************')

print(sa.remote_execution_single(
    tgt='*',
    fun='cmd.run',
    arg='ip a'

))

arg='runas=nginx'   how to define ？

**Comment by max-arnold** [comment]
Change the following line

```python
    obj = urllib.parse.urlencode(params).encode('utf-8')
```

to

```python
    obj = urllib.parse.urlencode(params, doseq=True).encode('utf-8')
```

And then call your method like this:

```python
print(
    sa.remote_execution_single(
        tgt='*',
        fun='cmd.run',
        arg=['ip -a', 'runas=nginx']
    )
)
```

Important caveat: multiple POST arguments with the same name are broken in Salt >= 3002: https://github.com/saltstack/salt/issues/59182

**Comment by sagetherage** [comment]
Thank you @max-arnold !
@misrn please mention me if this does not solve your issue and we can reopen or you may want to pose your question in the [mailing list forum for salt-users](https://groups.google.com/forum/#!forum/salt-users), ask on [IRC](http://webchat.freenode.net/?channels=salt&uio=Mj10cnVlJjk9dHJ1ZSYxMD10cnVl83), or in our [community slack workspace](https://saltstackcommunity.slack.com/) for a better conversation platform.
