### ISSUE TITLE
Add setup.cfg for default sdist owner and group to be root

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#60253]
By default, when packaging `salt` with `sdist`:

```bash
python3 setup.py sdist
python3 setup.py --ssh-packaging sdist
```

The generated `dist/*.tar.gz` tarballs embed the uid/gid of the archived files as matching the user that generated them. Previously, `sdist` had additional args so a command would look like:

```bash
python3 setup.py sdist --owner=root --group=root
python3 setup.py --ssh-packaging sdist --owner=root --group=root
```

These args no longer exist. Instead, these values can be picked up from `setup.cfg` as so:

```
[sdist]
owner = root
group = root
```

A `setup.cfg` should be added to this repo with those values to ensure consistent tarballs.

**Comment by sagetherage** [comment]
changed to a `bug` since it isn't working correctly since the args no longer exist.
