### ISSUE TITLE
[DOCS] redist_return.py contains docs copy/pasted from redis_cache.py

### ISSUE THREAD

**Issue by major0** [saltstack/salt#60271]
**Description**
It appears that the redis returner was developed using copy/paste from redis cache, and the docs were not completely cleaned up.

**Suggested Fix**
```
diff --git a/salt/returners/redis_return.py b/salt/returners/redis_return.py
index 5931103356..abfdda0c1d 100644
--- a/salt/returners/redis_return.py
+++ b/salt/returners/redis_return.py
@@ -77,7 +77,7 @@ cluster.startup_nodes:
 
     .. code-block:: yaml
 
-        cache.redis.cluster.startup_nodes
+        redis.cluster.startup_nodes
           - host: redis-member-1
             port: 6379
           - host: redis-member-2
```

**Comment by dmurphy18** [comment]
The documentation at https://docs.saltproject.io/en/latest/ref/cache/all/salt.cache.redis_cache.html presents
```
cache.redis.cluster.startup_nodes
  - host: redis-member-1
    port: 6379
  - host: redis-member-2
    port: 6379
```
for salt.cache.redis_cache

But the same example is also used in https://docs.saltproject.io/en/latest/ref/returners/all/salt.returners.redis_return.html

A case of cut and paste from salt/cache/redis_cache.py to salt/returners/redis_return.py probably and the example should be as the earlier example https://github.com/saltstack/salt/blob/0c4efe2cb8107861752c80ae88f3dd1d6033efd1/salt/returners/redis_return.py#L31-L36
