### ISSUE TITLE
[DOCS] Examples for ip_networks functions use wrong function name

### ISSUE THREAD

**Issue by heini** [saltstack/salt#60314]
**Description**
The examples for `ip_networks` functions use wrong function names

**Suggested Fix**
Rename functions in the examples

**Type of documentation**
Salt modules

**Location or format of documentation**
https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.network.html#salt.modules.network.ip_networks

**Comment by barbaricyawps** [comment]
Closing. Was resolved by https://github.com/saltstack/salt/issues/60835
