### ISSUE TITLE
[DOCS] fix 3003.1 docs formatting

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#60336]
Tagging and release was more important than having "correct" formatting - the rST file in https://github.com/saltstack/salt/pull/60334/files needs to get formatted as expected (e.g. adding ` `` ` back)

**Comment by sagetherage** [comment]
Wondering if this is often a problem not just in these release notes, but perhaps the rstcheck isn't always catching this or correcting? @ScriptAutomate

**Comment by ScriptAutomate** [comment]
We could evaluate using similar methods to https://github.com/saltstack/pytest-salt-factories/blob/master/pyproject.toml#L9-L49 where `towncrier` is generating an `.rst` version of CHANGELOG, preventing format clashing. This seems to be a problem coming from manual copy/pasting from `.md` (`CHANGELOG.md`) to the release file (ex. `3003.1.rst`)

**Comment by sagetherage** [comment]
let's discuss this in the Friday planning meeting this week

**Comment by barbaricyawps** [comment]
Hi, @waynew . I'm grooming the docs ticket backlog. Do you by any chance remember what the outcome of this discussion was? Is it still an issue?

**Comment by waynew** [comment]
Discussed in our triage meeting today I and it definitely still is an issue: https://github.com/saltstack/salt/blob/96586c106e805a5fe8ff2845bb1a59fa6fdd42f3/doc/topics/releases/3003.1.rst -- still missing ` `` ` around listen and LocalClient.

More broadly we probably should automate this - can discuss out of band what approach(es) we might take there..

**Comment by barbaricyawps** [comment]
Closing as a "won't fix" since 3003 is no longer supported.
