### ISSUE TITLE
[TEST FAILURE] fix flaky test Mock ip_addrs() in utils/minions.py unit test

### ISSUE THREAD

**Issue by sagetherage** [saltstack/salt#60345]
Please paste the link from the specific build where the failure first started:
When salt.utils.network.ip_addrs() returned no IPs, the test failed.

**Comment by agraul** [comment]
I haven't seen this specific test fail in the saltstack/salt's CI, but I can point to this GitHub Action run from our downstream repo where I saw this test failing: https://github.com/openSUSE/salt/runs/2763521974?check_suite_focus=true#step:4:10318
