### ISSUE TITLE
[BUG] Port option removed in Junos Proxy

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#60340]
**Description**
The option to specify the port was removed from the Junos proxy minion. This is what enables running Netconf connections over SSH. As far as I can tell, just adding this option back to the list of parameters in `def init` function resolves the issue and allows Netconf connections over SSH again.

**Setup**
Run `git diff v3002.6 v3003 salt/proxy/junos.py` to see that the port option was removed from the `def init` function.

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
Respect the port specification in the Pillar configuration.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: 1.1.0
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: 1.5.0
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
Salt Extensions:
        sseape: 8.4.1+2.2.plt.fixes.ge54bc20
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 5.8.18-100.fc31.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Comment by dmurphy18** [comment]
Accidentally removed by commit https://github.com/saltstack/salt/pull/58979/commits/57f28f1008583bd6b3faff6a1bba231859ba97b4

**Comment by dmurphy18** [comment]
Stated wrong issue in original PR #60341 , updated correctly now, hence closing this since fix merged in
