### ISSUE TITLE
[TEST FAILURE] Fedora 33 test_loader test_version failures

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#60368]
The following tests are failing on Fedora 33:

tests.pytests.functional.test_loader.test_new_entry_points_passing_func_returning_a_dict
tests.pytests.functional.test_loader.test_old_entry_points_returning_a_list
tests.pytests.functional.test_loader.test_old_entry_points_yielding_paths
tests.pytests.functional.test_version.test_salt_extensions_in_versions_report
tests.pytests.functional.test_version.test_salt_extensions_absent_in_versions_report

https://jenkins.saltproject.io/job/pr-fedora-33-x86_64-py3-pytest-slow/job/master/251/

**Comment by dmurphy18** [comment]
Errors are due to space left on device.
@s0undt3ch Would it be possible to increase the size of the disks for Fedora testing, betting the other versions will encounter too. EOD here and you'll be in 8 hours before me, where you can adjust sizes and kick them back off

**Comment by dmurphy18** [comment]
@bryceml @krionbsd See above, tests failing due to not enough disk space.  Need to update the amount of disk space allowed for the Fedora systems. Probably should check if any of the other Redhat / Centos family are pushing up against their limits.  Assigning this your way.

**Comment by krionbsd** [comment]
This issue comes with Fedora only because it mounts tmpfs at /tmp with 4GB, I will disable the mount point explicitly

**Comment by krionbsd** [comment]
should be fixed: https://github.com/saltstack/salt-jenkins/pull/1708
