### ISSUE TITLE
[BUG] Salt-ssh can't use ansible inventory as per documentation

### ISSUE THREAD

**Issue by joshiegy** [saltstack/salt#60370]
**Description**
Using ansible inventory file for salt-ssh does not work according to documentation,

**Setup**
salt installed via pip, version 3002.2.

**Steps to Reproduce the behavior**
* Install salt-ssh
* copy inventory file-example from [documentation](https://docs.saltproject.io/en/latest/ref/roster/all/salt.roster.ansible.html#module-salt.roster.ansible)
* run `salt-ssh --roster-file=/etc/salt/roster -N all test.ping`, just as the example in the documentation linked above

**Expected behavior**
Expecting the same result as the documentation

**Screenshots**
No screenshots, but example of error output:
```
salt-ssh --roster=ansible --roster-file=/etc/salt/roster -N all test.ping
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
JSONDecodeError: Expecting value: line 1 column 2 (char 1)
```
and
```
→ salt-ssh --roster-file=/etc/salt/roster -N all test.ping
[ERROR   ] Unable to render roster file: did not find expected <document start>
  in "<unicode string>", line 2, column 1
[ERROR   ] No matching targets found in roster.
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.9
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 20 2021, 00:00:00)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 21.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: fedora 33
        locale: utf-8
       machine: x86_64
       release: 4.19.128-microsoft-standard
        system: Linux
       version: Fedora 33
```
</details>

**Additional context**

**Comment by sagetherage** [comment]
@joshiegy 
The reported Salt version is vulnerable. We recommend upgrading as soon as possible to at least the latest point release or to latest. You can find those on [releases](https://github.com/saltstack/salt/releases) here in GitHub or the [package repo](https://repo.saltproject.io/).
