### ISSUE TITLE
[BUG] zabbix_host.present overwrites all inventory

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#60389]
**Description**
Instead of only updating the inventory items defined in the state, the entire inventory is replaced if there are any additional items.
These could be from automatic sources, or manually added in the Zabbix UI.

If the `- inventory` item is instead omitted, then the entire inventory is removed.

**Setup**
```sls
zabbix host:
  zabbix_host.present:
    - host: {{ grains['id'] }}
    - inventory:
      - vendor: {{ grains['manufacturer'] }}
```

**Steps to Reproduce the behavior**
Set another inventory property in the zabbix UI

**Expected behavior**
Inventory items should only be removed if specifically listed, e.g. with values `''` or `None`

If inventory is not defined, then it should not be changed.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 1.1.0
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.5.0
        Python: 3.8.5 (default, May 27 2021, 13:30:53)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-74-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Comment by OrangeDog** [comment]
The workaround is pretty horrible

```sls
{% set inventory = {'vendor': grains['manufacturer']} %}
{% if salt['zabbix.host_exists'](host=grains['id']) %}
  {% set hostid = salt['zabbix.host_get'](grains['id'])[0].hostid %}
  {% set new_inv = inventory %}
  {% set inventory = salt['zabbix.host_inventory_get'](hostid) %}
  {% do inventory.update(new_inv) %}
{% endif %}

zabbix_host:
  zabbix_host.present:
    - host: {{ grains['id'] }}
    - inventory:
{% for key, value in inventory.items() %}
  {% if value != '' %}      - {{ key }}: {{ value | tojson }}{% endif %}
{% endfor %}
```

**Comment by piterpunk** [comment]
Hi @OrangeDog ,

The state was thought to determine exactly what will be in the inventory, so it sets the `clear_old` option when calling `host_inventory_set` to remove anything that could be there. I agree with you that this probably isn't the desired behaviour for everyone, but change it will break for people that relies on this.

Probably the best is to include an `inventory_update` or `inventory_clear` option to the `zabbix.host_present` to control this.

What do you think?

**Comment by OrangeDog** [comment]
Yes a choice is probably best. The `file.recurse` state uses `clean`, so this should probably be `inventory_clean`.

**Comment by piterpunk** [comment]
> Yes a choice is probably best. The `file.recurse` state uses `clean`, so this should probably be `inventory_clean`.
>
> I think a lack of `inventory` should be changed to do nothing though. If people want to completely wipe it they can pass an empty list.

I agree with you, lack of `inventory` tag isn't a clear approach to clean up everything. I can start a PR with these two changes and #60382 tonight.

> As a bonus, could `inventory` also accept a dict, as well as a list of dict pairs?

I want some time to analyze this one, some inputs are done the way they are to make it easier to generate the expected json by Zabbix API and change it imply in a bigger effort. What should be the proposed syntax?

**Comment by OrangeDog** [comment]
The zabbix API already uses a dict for the inventory though. Note how I had to use a for loop to transform it in the workaround.
It's not a question of syntax...

**Comment by piterpunk** [comment]
Oh, sorry. Probably I couldn't express correctly my question.

Instead of:
```
- inventory:
  - key1: value1
  - key2: value2
```
What would be expected to be here?

**Comment by OrangeDog** [comment]
A dict...
```
- inventory:
    key1: value1
    key2: value2
```
```
- inventory: {"key1":"value1","key2":"value2"}
```
The syntax doesn't matter. Just check the type of the param.

**Comment by piterpunk** [comment]
Ok! I will begin to code at night.

Thank you!
