### ISSUE TITLE
salt-ssh 使用 ansible inventory报错[BUG]

### ISSUE THREAD

**Issue by neighbour-oldhuang** [saltstack/salt#60393]
**Description**
我参照https://docs.saltproject.io/en/latest/ref/roster/all/salt.roster.ansible.html#module-salt.roster.ansible 中的说明，尝试使用ansible的inventory 但是报错了.

**Setup**
1. 
cat >/etc/salt/hosts<<eol
#!/bin/bash
echo '{
  "servers": [
    "salt.gtmanfred.com"
  ],
  "desktop": [
    "home"
  ],
  "computers": {
    "hosts": [],
    "children": [
      "desktop",
      "servers"
    ]
  },
  "_meta": {
    "hostvars": {
      "salt.gtmanfred.com": {
        "ansible_ssh_user": "gtmanfred",
        "ansible_ssh_host": "127.0.0.1",
        "ansible_sudo_pass": "password",
        "ansible_ssh_port": 22
      },
      "home": {
        "ansible_ssh_user": "gtmanfred",
        "ansible_ssh_host": "12.34.56.78",
        "ansible_sudo_pass": "password",
        "ansible_ssh_port": 23
      }
    }
  }
}'
eol
2. salt-ssh --roster ansible --roster-file /etc/salt/ansible.hosts salt.gtmanfred.com test.ping

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
salt.gtmanfred.com:
   true

**Screenshots**
![image](https://user-images.githubusercontent.com/23180415/122407727-6d50b200-cfb4-11eb-9b3f-b1b706affb5b.png)
![image](https://user-images.githubusercontent.com/23180415/122407918-8d807100-cfb4-11eb-84af-89f5f66b8992.png)

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.14.5
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 11 2020, 18:30:39)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: alinux 2.1903 Hunting Beagle
        locale: UTF-8
       machine: x86_64
       release: 4.19.91-23.al7.x86_64
        system: Linux
       version: Alibaba Cloud Linux (Aliyun Linux) 2.1903 Hunting Beagle
```
</details>

**Additional context**

**Comment by neighbour-oldhuang** [comment]
不加 --roster ansible
![image](https://user-images.githubusercontent.com/23180415/122409005-61b1bb00-cfb5-11eb-8ae9-7f37870ea47c.png)

**Comment by sagetherage** [comment]
@neighbour-oldhuang the documentation needs to be updated - "gtmafred" should read as <example> or <insert-your-server> as well as with user and password. We have another issue already open for this, [here](https://github.com/saltstack/salt/issues/60370) to address the documentation and there is also a bytes vs. strings bug, as well. Please mention me and give more details if there is more or if I missed something.

**Comment by neighbour-oldhuang** [comment]
> @neighbour-oldhuang the documentation needs to be updated - "gtmafred" should read as or as well as with user and password. We have another issue already open for this, [here](https://github.com/saltstack/salt/issues/60370) to address the documentation and there is also a bytes vs. strings bug, as well. Please mention me and give more details if there is more or if I missed something.

我的问题跟链接中的问题貌似不一样，最新文档中的几种方式我试过了，跟文档中的预期不一致
