### ISSUE TITLE
[BUG]Salt minion unable to receive messages normally

### ISSUE THREAD

**Issue by andyyumiao** [saltstack/salt#60390]
Recently we encountered a problem. We deployed salt master and syndic in docker, and salt minion deployed on some physical machines. Recently, we discovered a problem: sometimes minion could not receive the command after sending a command, But minion can receive the command when sent repeatedly for the second time, please help analyze the possible reasons.

Our salt version: salt-2018.3.4

**Comment by OrangeDog** [comment]
Please include error, reproduction, and version details as in the template.

Also note that 2018.3.4 is unsupported. Upgrading is likely the simplest fix.

**Comment by garethgreenaway** [comment]
@andyyumiao Following on this one and making sure you saw the comments from @OrangeDog about upgrading from version 2018.3.4 to the latest version 3003.1.

**Comment by garethgreenaway** [comment]
@andyyumiao Following up and making sure you saw the comments about upgrading to the latest version of Salt.

**Comment by garethgreenaway** [comment]
Closing this one out due to the lack of response.  Please ensure you're running the latest available version of Salt, 3003.2.  If the issue persists please open a new issue.
