### ISSUE TITLE
[DOCS] Alternative nomenclature for "Master" and "Minion"

### ISSUE THREAD

**Issue by joncwong** [saltstack/salt#60407]
**Description**
Seeking alternative nomenclature in efforts of diversity/belonging. 

**Suggested Fix**
Does the community have any guidelines for those that wish to rebrand their own SaltStack usage or future plans to rename "Master" or "Minion"?

**Comment by OrangeDog** [comment]
Discussion is here: https://github.com/saltstack/salt-enhancement-proposals/pull/37
They will be replaced at some point.
It appears that "master" will become "controller".
