### ISSUE TITLE
[BUG] Subset option not respecting the number of targeted minions

### ISSUE THREAD

**Issue by houstonj1** [saltstack/salt#60425]
**Description**
When targeting a group of minions with the subset option set to a specific number of targets, I expect the named function to only run on that specified number of targets.

When passing a specific number of targets, `--subset=1`, the function is run on up to 3 minions ( if 3 are active ).

Ref: https://docs.saltproject.io/en/latest/ref/cli/salt.html

**Setup**
Have more than 1 minion targets

**Steps to Reproduce the behavior**
salt '*' cmd.run 'ls -al' --subset=1

**Expected behavior**
'ls -al' should only run on one target.

**Screenshots**
I can provide if this is difficult to reproduce

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Master:
salt 3002.6

Minions:
salt-minion 3002.6
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
Can confirm the value is completely ignored. It always only does three, even if you ask for more.

**Comment by whytewolf** [comment]
looks like an easy fix. 

in https://github.com/saltstack/salt/commit/df0859da74e3b3a08a1522bdc8128f8da54cb663 

salt/cli/salt.py had `kwargs["subset"] = self.options.subset` changed to `kwargs["sub"] = self.options.subset` however that change was not needed. and actually the option is subset not sub.

**Comment by OrangeDog** [comment]
@garethgreenaway you never explained why you reverted this: #58601

**Comment by garethgreenaway** [comment]
@OrangeDog Looks like I missed the original notification.  Thanks for bringing that to my attention.

**Comment by houstonj1** [comment]
@garethgreenaway or @OrangeDog is there a way to tell which version of Salt this change will be included in? I saw the PR get merged, does that mean it will be included in the next release?

**Comment by Ch3LL** [comment]
This will be included in the Silicon (3004) release.
