### ISSUE TITLE
Salt orchestration mixing the minions

### ISSUE THREAD

**Issue by sasyp** [saltstack/salt#60435]
### Description of Issue

I have a really weird issue and to be honest, have no idea even where to look.

A little background, I have preconfigured nodegroups, basically, for each minion from a nodegroup I'm starting orchestration like that:

                {% for minion_id in minions %}
                start-orch-for-minion-{{ minion_id }}:
                  salt.runner:
                    - name: state.orchestrate
                    - parallel: True
                    - kwarg:
                        mods: orch/minion
                        pillar:
                          minion: '{{ minion_id }}'
                {% endfor %}

The problem is that for some reason when I have a bigger group, above 20 minions. Salt somehow is losing the trail of each orchestration, at least for me looks like that.

In the example below the target minion is SENOFI-025 but somehow on "ret" we can see SENOFI-015 ... !?

Also, the comment of the result is - Run failed on minions: SENOFI-015.

I'm really confused about what the heck is happening ...

                salt_|-start-patching-SENOFI-025_|-start-patching-SENOFI-025_|-state:
                    ----------
                    __id__:
                        start-patching-SENOFI-025
                    __jid__:
                        20210624020207026084
                    __run_num__:
                        6
                    __sls__:
                        orch/minion
                    changes:
                        ----------
                        out:
                            highstate
                        ret:
                            ----------
                            SENOFI-015:
                                False
                            SENOFI-025:
                                ----------
                                wua_|-update_system_|-update_system_|-uptodate:
                                    ----------
                                    __id__:
                                        update_system
                                    __run_num__:
                                        0
                                    __sls__:
                                        patching.uptodate
                                    changes:
                                        ----------
                                        installed:
                                            ----------
                                            17b46563-df34-4749-9958-ee53b89a6c3a:
                                                ----------
                                                KBs:
                                                    - KB5003638
                                                NeedsReboot:
                                                    True
                                                Title:
                                                    2021-06 Cumulative Update for Windows Se...
                                    comment:
                                        Updates installed successfully
                                    duration:
                                        2000254.545
                                    name:
                                        update_system
                                    result:
                                        True
                                    start_time:
                                        04:02:22.729820
                    comment:
                        Run failed on minions: SENOFI-015
                    duration:
                        2060627.752
                    name:
                        start-patching-SENOFI-025
                    result:
                        False
                    start_time:
                        04:02:06.914601

If someone gives at least a direction where to look. Thanks

### Setup
patching/uptodate.sls:

                patching/uptodate.sls
				
                update_system:
                  wua.uptodate:
                    - drivers: True
                    - skip_reboot: False
                    - fire_event: uptodate/fishished

### Steps to Reproduce Issue
N/A

### Versions Report
salt --versions-report
Salt Version:
          Salt: 3003

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.13
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.26.4
        Python: 3.6.8 (default, Aug 18 2020, 08:33:21)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: 3.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 8.3 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-240.22.1.el8_3.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.3 Ootpa

**Comment by sagetherage** [comment]
@sasyp 
You may want to pose your question in the [mailing list forum for salt-users](https://groups.google.com/forum/#!forum/salt-users), ask on [IRC]((https://web.libera.chat/#salt), or join our [community slack workspace](https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg) for a better conversation platform.

**Comment by OrangeDog** [comment]
What is the actual orchestration (`orch/minion`)?

I'm confused why you're trying to run a separate orchestration for every minion. The point of orchestration is to have the master run things on multiple minions in a particular order.

If you just want to apply a state to every minion, orchestration is unnecessary
```
salt '*' state.appy patching/uptodate
```

**Comment by sasyp** [comment]
The idea to run separate orchestration for each minion is because I need the flow for each minion to be independent.

orch/minion:

            {% set minion = salt['pillar.get']('minion', 'PILLAR MINION NOT FOUND!') %}
            
            check-{{ minion }}:
              salt.state:
                - tgt: {{ minion }}
                - sls:
                  - patching.check-minion
                - failhard: True
                - comment: 'Minion does not exist or is unresponsive'
            
            pre-reboot-{{ minion }}:
              salt.state:
                - tgt: {{ minion }}
                - sls:
                  - patching.reboot
            
            wait-for-pre-reboot-{{ minion }}:
              salt.wait_for_event:
                - name: salt/minion/*/start
                - id_list:
                  - {{ minion }}
                - timeout: 3600
                - require:
                  - salt: pre-reboot-{{ minion }}
            
            bits-{{ minion }}:
              salt.state:
                - tgt: {{ minion }}
                - sls:
                  - patching.bits
            
            start-event-{{ minion }}:
              salt.function:
                - name: event.send
                - tgt: {{ minion }}
                - arg:
                  - 'patching.started'
            
            start-patching-{{ minion }}:
              salt.state:
                - tgt: {{ minion }}
                - require:
                  - bits-{{ minion }}
                - sls:
                  - patching.uptodate
            
            fail-{{ minion }}:
              salt.state:
                - tgt: {{ minion }}
                - failhard: True
                - sls:
                  - patching.failed
                - onfail:
                    - start-patching-{{ minion }}
            
            reboot-{{ minion }}:
              salt.state:
                - tgt: {{ minion }}
                - sls:
                  - patching.reboot
                - onchanges:
                    - start-patching-{{ minion }}
            
            wait-for-post-reboot-{{ minion }}:
              salt.wait_for_event:
                - name: salt/minion/*/start
                - id_list:
                  - {{ minion }}
                - timeout: 3600
                - onchanges:
                    - start-patching-{{ minion }}
                - require:
                  - salt: reboot-{{ minion }}
            
            post-start-bits-{{ minion }}:
              salt.state:
                - tgt: {{ minion }}
                - onchanges:
                    - start-patching-{{ minion }}
                - sls:
                  - patching.bits
            
            post-check-{{ minion }}:
              salt.state:
                - tgt: {{ minion }}
                - onchanges:
                    - start-patching-{{ minion }}
                - require:
                  - post-start-bits-{{ minion }}
                - sls:
                  - patching.post-check

**Comment by garethgreenaway** [comment]
@sasyp Thanks for report.  I will reiterate @OrangeDog's comments that the idea behind orchestration is to run states across multiple minions which depend on each other and need to run in a particular order.  The use case you described above sounds like the use case for a normal state run targeting a subset of your minions.

**Comment by OrangeDog** [comment]
@garethgreenaway the waiting for reboots makes it hard to do with just states, but you could move the for loop into the orchestration and run it once and the weird bit may go away.

**Comment by garethgreenaway** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
