### ISSUE TITLE
[BUG] salt-minion.service: Main process exited, code=exited, status=247/n/a

### ISSUE THREAD

**Issue by remyd1** [saltstack/salt#60452]
**Description**

The minion stopped with "247" exit code tells systemd. The master is not able to communicate with it anymore.
However, a "salt-minion" process is still running.
I have two machines with this bug; both are lxc containers with debian 10 and salt minion version 3003 (I did not have this bug before).

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: debian 10 buster
        locale: utf-8
       machine: x86_64
       release: 5.4.73-1-pve
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Comment by sagetherage** [comment]
@remyd1 if you restart the minion it does come back up and start communicating again? have you turned on debugging log level? are you able to sanitize and send log details?

**Comment by remyd1** [comment]
I am able to reproduce this bug on 3 different minions. Yes, the minion come back up and start communicated again after a restart of the minion.

All those minions have low resources (CPU and memory).

I will dig a little more to check if it comes from too much pillars data or only from the recent salt-minion upgrade.

**Comment by remyd1** [comment]
Ok; so, after upgrading memory from 512M to 2G, and CPU from 1 core to 2 cores, it works fine.
I had some `killed` processes in journalctl.

However, I am currently unable to say if it comes from this saltstack upgrade or from my quantity of pillars.

**Comment by garethgreenaway** [comment]
@remyd1 Thanks for the report.  Both the Salt minion and Salt master do require a minimal amount of memory to function, there are some tunable options that you can turn off that reduce the required resources such as memory.  Many of these options are around the Salt event bus, eg. disabling certain event types from being passed on the event bus.

**Comment by remyd1** [comment]
Hi @garethgreenaway ,

Is there any documentation about those requirements and how to disable these bus events ?

Many thanks,

**Comment by garethgreenaway** [comment]
@remyd1 All the tunable options for the Salt minion can be found here, https://docs.saltproject.io/en/latest/ref/configuration/minion.html, you'll find options to disable events, modules, etc.

**Comment by remyd1** [comment]
Hi,

Just a little update to confirm the bug on small containers (with not enough memory). I can see OOM killer stop salt-minion processes on the hypervisor (proxmox in my case, with lxc containers).

I will dig a little bit to see if I can reduce my pillars data.

Thanks,
Best regards

**Comment by garethgreenaway** [comment]
Closing this issue due to age and lack of activity. Please test this on version 3006.2 and create a new issue if the problem persists. The new issue template has more information and will allow us to track and reproduce the issue more effectively. Thanks!
