### ISSUE TITLE
[Question] How to get the Jid from the job itself? is there any option to add as flag?

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#60462]
**Description**
How to get the Jid from the job itself? is there any option to add as flag?

**Comment by sagetherage** [comment]
@sooraj2589 
you may want to pose your question in the [mailing list forum for salt-users](https://groups.google.com/forum/#!forum/salt-users), ask on [IRC](https://web.libera.chat/#salt), or in our [community slack workspace](https://join.slack.com/t/saltstackcommunity/shared_invite/zt-3av8jjyf-oBQ2M0vhXOhJpNpRkPWBvg) for a better conversation platform.

**Comment by OrangeDog** [comment]
The `--async` option will return the jid immediately instead of waiting for completion.
