### ISSUE TITLE
[FEATURE REQUEST] Add more info about source of error in Error logs for errors like: AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by MurzNN** [saltstack/salt#60482]
**Is your feature request related to a problem? Please describe.**
Very often, when one of pillar file contains some error, I see the error in Salt-Master logs like this:
```
AttributeError: 'str' object has no attribute 'get'
```
And similar error on salt-minion:
```
[salt.pillar      :253 ][ERROR   ][35174] Got a bad pillar from master, type str, expecting dict: 
[salt.minion      :1140][ERROR   ][35174] Error while bringing up minion for multi-master. Is master at salt.example.com responding?
```

This error doesn't give any information about source of this error, in which file and on each line this happens?
Full log record looks like this:
```
[salt.master      :1941][ERROR   ][789409] Error in function _pillar:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1935, in run_func
    ret = getattr(self, func)(load)
  File "/usr/lib/python3/dist-packages/salt/master.py", line 1632, in _pillar
    data = pillar.compile_pillar()
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 1192, in compile_pillar
    pillar, errors = self.render_pillar(matches)
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 1029, in render_pillar
    pstate, mods, err = self.render_pstate(sls, saltenv, mods)
  File "/usr/lib/python3/dist-packages/salt/pillar/__init__.py", line 926, in render_pstate
    defaults = v.get("defaults", {})
AttributeError: 'str' object has no attribute 'get'
```

**Describe the solution you'd like**
Please find the way to add more detailed info about real source of this problem to log record!

**Describe alternatives you've considered**
Alternative long way is to excluding each pillar file one-by-one to find problematic file, and commenting blocks in it to find problematic line. This is too hard way on complex setups!

**Comment by OrangeDog** [comment]
Tools like `salt-lint` should be able to find most of these errors. It's rather difficult for salt to give you the info at the exception site because all the jinja and yaml (or whatever other renderers are used) processing has already happened and it's dealing with python objects with no context of where they came from. This is a general problem with schemaless data and a dynamically-typed language.

In this specific case it appears from looking at the code (`salt/pillar/__init__.py", line 926`) that you have a malformed `include:` somewhere.

**Comment by garethgreenaway** [comment]
@MurzNN Thanks for your report.  We do have a number of checks in place to minimize the scenario that you ran into, unfortunately we can't account for everything that could happen at this point in the code, for the very reasons @OrangeDog explained.  If you do have suggestions for how this situations could be avoided we would definitely welcome them.

**Comment by garethgreenaway** [comment]
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.
