### ISSUE TITLE
[BUG] Proxy minion is not reading /etc/salt/minion.d/*.conf

### ISSUE THREAD

**Issue by ichilton** [saltstack/salt#60485]
**Description**
/etc/salt/proxy states:

```
# Per default the minion will automatically include all config files
# from minion.d/*.conf (minion.d is a directory in the same directory
# as the main minion config file).
#default_include: minion.d/*.conf
```

However, the minion.d/*.conf files are not being used.

**Setup**

/etc/salt/minion.d/salt.conf contains:

```
master: xx.xx.xx.xx
```

This works fine for the normal salt minion - it can connect to the master fine.

However, when starting a proxy minion, it can not connect to the master because master is not specified (so defaults to the hostname salt).

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

Start a proxy minion, eg:

```
salt-proxy --proxyid my-device -l debug
```

**Expected behavior**

It should read `/etc/salt/minion.d/*.conf` as well as `/etc/salt/proxy.d/*.conf`

**Screenshots**

```
[DEBUG   ] Connecting to master. Attempt 1 of 1
[DEBUG   ] "salt" Not an IP address? Assuming it is a hostname.
[ERROR   ] DNS lookup or connection check of 'salt' failed.
[ERROR   ] Master hostname: 'salt' not found or not responsive. Retrying in 30 seconds
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
# salt --versions-report
Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: 0.27.7
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.19
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 0.27.4
        Python: 3.7.3 (default, Jan 22 2021, 20:04:44)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: debian 10 buster
        locale: UTF-8
       machine: x86_64
       release: 4.19.0-12-amd64
        system: Linux
       version: Debian GNU/Linux 10 buster
```
</details>

**Comment by dmurphy18** [comment]
@ichilton You need to use /etc/salt/proxy and /etc/salt/proxy.d/*.conf, since this is for the proxy minion and not the salt-minion, for your reference https://docs.saltproject.io/en/latest/ref/configuration/proxy.html#proxy-specific-configuration-options

**Comment by ichilton** [comment]
@dmurphy18 If that's the intended functionality, the comments in proxy.conf need correcting then, as:

```
Per default the minion will automatically include all config files
# from minion.d/*.conf
```

.. is not true.

Thanks,

Ian

**Comment by dmurphy18** [comment]
@ichilton Thanks for catching that, will get doc's and default file updated correctly, see https://github.com/saltstack/salt/issues/60527

If that is acceptable, please consider closing this issue and thanks for the catch

**Comment by ichilton** [comment]
Thanks @dmurphy18!
