### ISSUE TITLE
FILE_ROOTS search result is empty, -- salt.wheel.file_roots.find('dir/a.sls', saltenv='base')

### ISSUE THREAD

**Issue by LewinSZ** [saltstack/salt#60497]
**Description**
FILE_ROOTS search result is empty, when the path parameter is a file in a subdirectory

salt.wheel.file_roots.find('dir/a.sls', saltenv='base')

**Setup**
```
#Source code
def find(path, saltenv="base"):
    """
    Return a dict of the files located with the given path and environment
    """
    # Return a list of paths + text or bin
    ret = []
    if saltenv not in __opts__["file_roots"]:
        return ret
    for root in __opts__["file_roots"][saltenv]:
        full = os.path.join(root, path)
        if not salt.utils.verify.clean_path(root, full):  #salt.utils.verify.clean_path(root, full) == FALSE
            continue
        if os.path.isfile(full):
            # Add it to the dict
            with salt.utils.files.fopen(full, "rb") as fp_:
                if salt.utils.files.is_text(fp_):
                    ret.append({full: "txt"})
                else:
                    ret.append({full: "bin"})
    return ret

def write(data, path, saltenv="base", index=0):
    """
    Write the named file, by default the first file found is written, but the
    index of the file can be specified to write to a lower priority file root
    """
    if saltenv not in __opts__["file_roots"]:
        return "Named environment {0} is not present".format(saltenv)
    if len(__opts__["file_roots"][saltenv]) <= index:
        return "Specified index {0} in environment {1} is not present".format(
            index, saltenv
        )
    if os.path.isabs(path):
        return (
            "The path passed in {0} is not relative to the environment " "{1}"
        ).format(path, saltenv)
    root = __opts__["file_roots"][saltenv][index]
    dest = os.path.join(root, path)
    if not salt.utils.verify.clean_path(root, dest, subdir=True):  ##salt.utils.verify.clean_path(root, dest, subdir=True) == True
        return "Invalid path: {}".format(path)
    dest_dir = os.path.dirname(dest)
    if not os.path.isdir(dest_dir):
        os.makedirs(dest_dir)
    with salt.utils.files.fopen(dest, "w+") as fp_:
        fp_.write(salt.utils.stringutils.to_str(data))
    return "Wrote data to file {0}".format(dest)

```

**Steps to Reproduce the behavior**
```
file_roots:
  base:
    - /srv/salt/base


/srv/salt/base
├── t1.sls
└── test
    └── t1.sls
```

```
 curl -sSk https://192.168.2.11:8000 \
>       -b ~/cookies.txt \
>       -H 'Accept: application/x-yaml' \
>       -d client=wheel \
>       -d fun='file_roots.find' \
>       -d path="t1.sls"
return:
- data:
    _stamp: '2021-07-07T06:16:29.944569'
    fun: wheel.file_roots.find
    jid: '20210707061629325255'
    return:
    - /srv/salt/base/t1.sls: txt
    success: true
    tag: salt/wheel/20210707061629325255
    user: saltapi
  tag: salt/wheel/20210707061629325255
 

 curl -sSk https://192.168.2.11:8000 \
>       -b ~/cookies.txt \
>       -H 'Accept: application/x-yaml' \
>       -d client=wheel \
>       -d fun='file_roots.find' \
>       -d path="test/t1.sls"
return:
- data:
    _stamp: '2021-07-07T06:17:11.593215'
    fun: wheel.file_roots.find
    jid: '20210707061711575966'
    return: []
    success: true
    tag: salt/wheel/20210707061711575966
    user: saltapi
  tag: salt/wheel/20210707061711575966
```

**Expected behavior**
Hope to find/read files in subdirectories

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

# salt --versions-report
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: 1.9.1
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1127.13.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

</details>

**Additional context**

**Comment by waynew** [comment]
Hey @LewinSZ thanks for this! I'm working through reproducing incoming issues and I'll get to trying to reproduce this as soon as I can :+1:

**Comment by waynew** [comment]
Hey, so unless I'm misunderstanding, this isn't a problem in Salt just a misunderstanding about Python.

```
  if os.path.isfile(full):
```
A quick search for "python os.path docs" turns up https://docs.python.org/3/library/os.path.html, and it looks like what you may want is `os.path.exists`.

If I'm misunderstanding, let me know and I'll go ahead and re-open this~
