### ISSUE TITLE
[BUG] pidfile is removed on check (salt 3003)

### ISSUE THREAD

**Issue by litnimax** [saltstack/salt#60523]
Hi!
I already reported the same bug in #57794 but seems it is introduced again.
The same. When one minion is running when I start it again it exits with:
```
18:11:20 [INFO    ] salt.cli.daemons:293 Setting up the Salt Minion "90520736270401"
18:11:20 [INFO    ] salt.cli.daemons:88 An instance is already running. Exiting the Salt Minion
18:11:20 [INFO    ] salt.cli.daemons:88 Shutting down the Salt Minion
```
And it removes the pid file. So when I start minion for the 3-rd time  it starts and I have 2 minions running.

**Comment by cmcmarrow** [comment]
@litnimax Need to find where the pidfile is being deleted and find out why someone is deleting it.

**Comment by cmcmarrow** [comment]
@litnimax do you have 'psutil' installed?

**Comment by litnimax** [comment]
Hi!
With psutil I don't have this issue.
So why psutil is not in salt requirements!?
Because I install salt with pip3 install salt.

![image](https://user-images.githubusercontent.com/1144539/125460683-9b919bc2-86fa-4857-9625-f9fd913170a0.png)

**Comment by cmcmarrow** [comment]
`psutil` was part of the requirements. Someone must have removed it. `psutil` does not support all OS’s so I left in the old behavior as fall back.

**Comment by litnimax** [comment]
I see. Thanks for your explanation.
