### ISSUE TITLE
[BUG] Ignore configuration for 'enable_fqdns_grains' for AIX, Solaris and Juniper

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#60529]
**Description**
The grain 'enable_fqdns_grains' is causing issues on AIX (seq fault), add ignore configuration setting for AIX, Solaris and Juniper, similar to Windows and Proxy

**Setup**
Problem found during development of Salt 3003.1 for AIX.

**Steps to Reproduce the behavior**
salt-call --local grains.items causing Seq Fault with default setting of True, if set to False, no issues occur.

**Expected behavior**
Grains produced for AIX without Seq. Fault. (Core)

**Versions Report**
Porting Salt 3003.1 to AIX

**Additional context**
Patched Salt 3003.1 with salt_fqdns adding checks for AIX, SunOS or Junos to checks for Windows and Proxy to ignore setting of 'enable_fqdns_grains' and assume False.

**Comment by sagetherage** [comment]
removed this issue from the bugfix milestone and kept the PR that went into the Freeze branch in the bugfix milestone - thank you @dmurphy18 for the link!

**Comment by dmurphy18** [comment]
@sagetherage FYI https://github.com/saltstack/salt/pull/60533 has the changes and the test_core.py migrated to pytest, still resolving Windows test issues related to pytest and Windows platform.
