### ISSUE TITLE
[BUG] Disable 'enable_fqdns_grains' configuration for AIX, Solaris and Junos

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#60525]
Need to disable the 'enable_fqdns_grains' configuration for AIX, Solaris and Junos (Juniper) platforms.
On AIX if this grain is True, then Seq. Faults occur

**Setup**
Development version of AIX without patch for salt_fqdns

**Steps to Reproduce the behavior**
salt-call --local grains.items

**Expected behavior**
No Seq Fault and grains.items to work.
Note: if /etc/salt/minion enable_fqdns_grain: False, no problems

**Versions Report**
Development of AIX Salt 3003.1

**Comment by OrangeDog** [comment]
Was this not done in 3003.2 - #60529?

**Comment by dmurphy18** [comment]
@OrangeDog Thanks for that, water flows under the bridge real fast lately and missed closing this once it went into Salt 3003.2. Was scheduled for Silicon, but considered important enough to get it into 3003.2 and forgot to close the Silicon issue.  Thanks for catching.
