### ISSUE TITLE
[BUG] Regression: pip.installed does not pass env_vars when calling pip.list to check if package is already installed

### ISSUE THREAD

**Issue by redbaron4** [saltstack/salt#60557]
**Description**
This is a regression of #46127 and was introduced a few months after the original fix merged

See that bug for more details about how to reproduce the issue

**Additional context**

[This commit](https://github.com/saltstack/salt/commit/4fec8f6bcce7965b5294939b906d0e344294c651) made a change to cache the installed list using `pip.list` to speed up pip execution. However, the call to pip list does not pass `env_vars` [(see 3003.1 code here)](https://github.com/saltstack/salt/blob/2ecd867850f85e2ca68a30838d44efafcaddc9ea/salt/states/pip_state.py#L843) and hence the bug has reappeared.

```
pip_list = __salt__["pip.list"](bin_env=bin_env, user=user, cwd=cwd)
```

Fix is trivial by passing `env_vars=env_vars` to this function.

**Comment by smokeytheblair** [comment]
When this gets addressed, please note that **kwargs is also not being passed.  Will want to confirm if that is also an issue.
