### ISSUE TITLE
[BUG] avoid/prevent re-releasing with the same name

### ISSUE THREAD

**Issue by maennlse** [saltstack/salt#60554]
**Description**
i noticed at least twice that a package was 're-released' with the same name (filename)
looks like yesterday `Salt-Minion-3003.1-Py3-AMD64-Setup.exe` was re-released 
```
2021-07-14T19:33:38.000Z        61.5 MB        Salt-Minion-3003.1-Py3-AMD64-Setup.exe
2021-07-14T19:33:38.000Z        0.1 kB         Salt-Minion-3003.1-Py3-AMD64-Setup.exe.md5
2021-07-14T19:33:38.000Z        0.1 kB         Salt-Minion-3003.1-Py3-AMD64-Setup.exe.sha256
```
initial release was (probably) something around: 2021-06-23T16:11:58.000Z ...

which in our particular case broke the installation of `saltminion` via chocolatey (https://community.chocolatey.org/packages/saltminion) because chocolatey is separatly saving checksums

**Setup**
n/a

**Steps to Reproduce the behavior**
n/a

**Expected behavior**
updated packages have a different filename?

**Screenshots**
n/a

**Versions Report**
Salt-Minion-3003.1-Py3-AMD64-Setup.exe

**Additional context*
n/a

**Comment by twangboy** [comment]
The packages were unsigned, that's why there were re-released.

**Comment by bryceml** [comment]
@twangboy do we want to add package verisons onto those ? like

```
Salt-Minion-3003.1-1-Py3-AMD64-Setup.exe
```
we would need to adjust in the winbootstrap script, if not other places too.

**Comment by maennlse** [comment]
just for documentation, the other package i noted that it was re-released with the same name was macOS salt-3003-py3-x86_64.pkg package triggered by #60012 (which also caused some trouble as we couldn't (didn't know how to) differentiate between the (broken) already installed one and the new one)

so, i (personally) would prefere to have some kine of package version or 'tag' in the filename (although this might break some other peoples routines?)

**Comment by krionbsd** [comment]
yes, tend to agree, something like pkg revision number would make sense

**Comment by twangboy** [comment]
We are now adding a build number to the package names

Salt-Minion-3004.1-1-Py3-AMD64-Setup.exe
