### ISSUE TITLE
[FEATURE REQUEST] macOS arm64 Support (on repo.saltproject.io/osx/) 

### ISSUE THREAD

**Issue by rrrix** [saltstack/salt#60560]
# Feature Request

Please provide either universal2 (x86_64 + arm64) and/or arm64-specific macOS salt packages on https://repo.saltproject.io/osx/.  

Currently the macOS salt packages are available for `x86_64` only, and are not built/compiled for `arm64` a.k.a. Apple Silicon. In order to use these packages, it requires an additional step of installing Rosetta 2 prior to installing Salt via:

```bash
sudo softwareupdate --install-rosetta --agree-to-license
``` 

While this isn't a terrible burden and Rosetta 2 is likely to be installed on typical developer machines, it will eventually be frowned upon as more and more software is natively compiled for arm64 (and bundled in a "fat" library). Python3.9.1+ [already supports a __universal2__ installer](https://www.python.org/downloads/mac-osx/).

# Background

My organization distributes a macOS __Terminal.app__ compatible shell script (`salt.command`) which does the following:

1. Checks the CPU architecture (`uname -s`), if `arm64`, then install rosetta
2. Downloads (`curl`) Salt package from https://repo.saltproject.io/osx/salt-latest-py3-x86_64.pkg 
2. Install Salt `installer -pkg "$SALT_PKG_TMP" -target /`
3. Configure Salt Minion file, `/etc/salt/minion` 
4. Opens a browser window to a custom in-house system that helps automate minion key registration (magic!)
5. `salt-call state.highstate` 

We increasingly are adopting more Apple Silicon based mac's all the time and will eventually be 100% Apple Silicon based as Apple completes the 2-year transition period for their entire Mac system portfolio. 

Thank you salt team for everything you do, you make my life so much easier with this project!

**Comment by garethgreenaway** [comment]
@rrrix Thanks for the request.  It's my understanding that Python 3.9.x is the version of Python that has support for OS X running on ARM and we have plans to move to that version but have a few outstanding issues preventing that from happening.  @s0undt3ch can you weigh in on this one as I believe you had experience with it.

**Comment by s0undt3ch** [comment]
We currently have an open PR(https://github.com/saltstack/salt/pull/57028) to enable support on macOS past 3.7 and for the packaging itself, @bryceml and @krionbsd likely know more.

**Comment by a-wildman** [comment]
@s0undt3ch With PR #57028 merged, can this feature request move forward?

**Comment by s0undt3ch** [comment]
Sorry, I don't know enough about our macOS packaging and what is required to build those packages.


/cc @krionbsd @twangboy

**Comment by techdragon** [comment]
From what I can tell, #57028 covers building, the current mac build scripts generate a platform specific build by performing CPU architecture detection, but the current CI pipeline for mac is... obtuse. Between GitHub, GitLab, Jenkins, Kitchen, and MacStadium, I really cant tell where the right place to make the changes to add a new mac build.

Some things I turned up that might help other people pushing on this. 
- Adding catalina to the MacStadium templates https://github.com/saltstack/salt-jenkins/commit/c0e20f9b95f346ff6b8f3e88fffd08a1bb773ef7 (We would need Big Sur or newer, Catalina one wont work on M1 or M2 CPUs) 
- The GitLab CI  YAML - https://gitlab.com/saltstack/open/salt-pkg/-/blob/master/.gitlab-ci.yml
- The current Jenkins dashboard with the multiple Mac builders https://jenkins.saltproject.io/computer/ 
- The current wiki page for the CI builds https://github.com/saltstack/community/wiki/Salt-CI-Job-Links (no updates in 2 years ... so it might be out of date) 

I'll be testing out a manual build test following the instructions later today and I'll update this to confirm if it works on my new laptop.

**Comment by eedgar** [comment]
Any updates? The Intel emulated performance is horrible.

All my cou cores go to 80+%  This makes it nearly unusable.

**Comment by wegotoeleven** [comment]
As much as I hate just replying +1, I fear that I have to just reply with a +1. Because I too, would like an Apple Silicon-native build of Salt. 

So +1 from me

**Comment by vogtmh** [comment]
+1

Without an ARM package, Salt won't be an option for my Mac environment anymore.

**Comment by loodde** [comment]
Are there any updates on this? 🤞

**Comment by cdalvaro** [comment]
With the release of Salt 3006, salt installation via Homebrew will be deprecated:

```
brew info salt
==> salt: stable 3005 (bottled), HEAD
Dynamic infrastructure communication bus
https://saltproject.io/
Deprecated because it next version will require a vendored python!
/opt/homebrew/Cellar/salt/3005_1 (10,038 files, 143.3MB) *
  Poured from bottle using the formulae.brew.sh API on 2023-02-23 at 12:52:44
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/salt.rb
License: Apache-2.0
```

Even more, currently you don't get the latest version of salt, which is 3005.1, if you install it via Homebrew, as shown above.

Beginning with the next major version, 3006, the only way to install salt will be using onedir (or .pkg). However, looking for more information about this, I have found that ARM64 packages will be provided for this version:

![UpgradeToOnedir](https://user-images.githubusercontent.com/16347742/224036643-dbfd0732-afe7-4a7f-8f73-60246b005f07.png)

https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#what-is-onedir

**Comment by lkubb** [comment]
FWIW, I have been using the official packages running under Rosetta and patched the `mac_brew_pkg` module to run brew natively from `/opt/homebrew` (in order to avoid installing everything under Rosetta):

```diff
diff --git salt/modules/mac_brew_pkg.py salt/modules/mac_brew_pkg.py
index 2fa425a9cc..002657e6d7 100644
--- salt/modules/mac_brew_pkg.py
+++ salt/modules/mac_brew_pkg.py
@@ -108,12 +108,16 @@ def _call_brew(*cmd, failhard=True):
     """
     Calls the brew command with the user account of brew
     """
-    user = __salt__["file.get_user"](_homebrew_bin())
+    brew_bin = _homebrew_bin()
+    user = __salt__["file.get_user"](brew_bin)
     runas = user if user != __opts__["user"] else None
     _cmd = []
     if runas:
         _cmd = ["sudo -i -n -H -u {} -- ".format(runas)]
-    _cmd = _cmd + [salt.utils.path.which("brew")] + list(cmd)
+    if "Apple" in __grains__.get("cpu_model", "") and brew_bin.startswith("/opt/homebrew"):
+        _cmd = _cmd + ["arch", "-arm64"]
+
+    _cmd = _cmd + [brew_bin] + list(cmd)
     _cmd = " ".join(_cmd)

     runas = None
```

Really happy that it looks like we are finally getting official support for the native performance on M1 (and I can ditch my workarounds). Thanks for your hard work!

**Comment by vogtmh** [comment]
> No arm64 packages for 3006 😔
> 
> https://repo.saltproject.io/salt/py3/macos/3006/

And even worse than that: the grains report back cpuarch=x86_64 - even if it's running on ARM. 

I guess we need to wait until Apple discontinues Intel until Salt will finally provide proper ARM packages.

**Comment by cdalvaro** [comment]
> And even worse than that: the grains report back cpuarch=x86_64 - even if it's running on ARM.
> 
> I guess we need to wait until Apple discontinues Intel until Salt will finally provide proper ARM packages.

I'm currently using this brew formula: [`cdalvaro/tap/salt`](https://github.com/cdalvaro/homebrew-tap/blob/main/Formula/salt.rb) to build the arm64 version while the official solution arrives.

Just execute: `brew install cdalvaro/tap/salt` and it will be built and installed automatically.

**Comment by cdalvaro** [comment]
Finally an Apple Silicon version starting with 3006.5 version!

https://repo.saltproject.io/salt/py3/macos/latest/salt-3006.5-py3-arm64.pkg

I've updated my homebrew tap to install this same package. Feel free to try it:

```sh
brew install --cask cdalvaro/tap/salt
```

**Comment by twangboy** [comment]
Salt is now building Arm packages for macOS

**Comment by cdalvaro** [comment]
Salt can be installed using the official Homebrew's casks repository.

https://github.com/Homebrew/homebrew-cask/pull/162371

```sh
brew install --cask salt
```
