### ISSUE TITLE
[BUG] valid hashing-algorithms (xmit_hash_policy) for bonding return an error

### ISSUE THREAD

**Issue by partytime** [saltstack/salt#60583]
**Description**
For mode4 linux bonds, valid hashing algorithms (xmit_hash_policy) encap2+3 and encap3+4 are considered invalid in salt/modules/rh_ip.py

See https://www.kernel.org/doc/Documentation/networking/bonding.txt , encap2+3 and encap3+4 should be valid hashing algorithms

**Setup**

The following sls will be invalid due to invalid hashing-algorithm option, with the Following error
```----------
          ID: bond0
    Function: network.managed
      Result: False
     Comment: Invalid option -- Interface: bond0, Option: hashing-algorithm, Expected: [layer2|layer2+3|layer3+4]
     Started: 16:41:44.573290
    Duration: 1.29 ms
     Changes:
```
bond0:
    network.managed:
      - enabled: True
      - ipaddr: 192.168.1.1
      - netmask: 255.255.255.255
      - proto: none
      - peerdns: no
      - type: eth
      - miimon: 100
      - dns:
          - 8.8.8.8
          - 4.4.4.4
      - name: bond0
      - type: bond
      - mode: 802.3ad
      - hashing-algorithm: encap3+4
      - lacp_rate: fast

**Steps to Reproduce the behavior**
See above sls

**Expected behavior**
Above sls should be valid, and the resulting ifcfg file should have an option in xmit_hash_policy like
`BONDING_OPTS="downdelay=200 miimon=100 use_carrier=0 mode=4 xmit_hash_policy=encap3+4 updelay=0 lacp_rate=1 ad_select=0 "`

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.1
```
</details>

**Additional context**
I believe this can simply be fixed by adding encap2+3 and encap3+4 to the `valid` tuple in `salt/modules/rh_ip.py`

```
    if "hashing-algorithm" in opts:
        valid = ("layer2", "layer2+3", "layer3+4")
        if opts["hashing-algorithm"] in valid:
            bond.update({"xmit_hash_policy": opts["hashing-algorithm"]})
        else:
            _raise_error_iface(iface, "hashing-algorithm", valid)
```

**Comment by dmurphy18** [comment]
@partytime Please provide all of the --versions-report has it provides useful information about the OS platform, what is installed etc, and not just the version of Salt being used.  This is required before this issue can be examined further, for example: Redhat or Centos, 6, 7 or 8, etc.

**Comment by partytime** [comment]
sure, though this will affect any version/OS that uses `salt/modules/rh_ip.py` in the saltstack source

```Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 5.10.25-linuxkit
        system: Linux
       version: CentOS Linux 7 Core```

**Comment by dmurphy18** [comment]
@partytime From the bonding doc
```
	The default value is layer2.  This option was added in bonding
	version 2.6.3.  In earlier versions of bonding, this parameter
	does not exist, and the layer2 policy is the only policy.  The
	layer2+3 value was added for bonding version 3.2.2.
```
So need to know what flavor of Redhat / Centos, since may not have full support for bonding depending on the version.  You could have been using Redhat 6, even though it is EOL.  Know of one customer who is still using RHEL 6, and using Tiamat based Salt.  More information is always better.

Thanks for the full --versions-report

**Comment by dmurphy18** [comment]
@partytime Can you supply the full --versions-report to allow progress on this issue

**Comment by partytime** [comment]
Hi @dmurphy18 I did in my initial response. Perhaps we are confused?

again here for posterity

```
[root@host salt]# salt  --versions-report
Salt Version:
          Salt: 3003.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 5.10.25-linuxkit
        system: Linux
       version: CentOS Linux 7 Core
```
