### ISSUE TITLE
[BUG] The cloud driver, 'hetzner', configured under the 'hcloud' cloud provider alias, could not be loaded.

### ISSUE THREAD

**Issue by mngitb** [saltstack/salt#60602]
**Description**
I cannot use hetzner cloud module with salt-cloud.
I have installed hcloud client also hcloud python3 module.
I am still receiving the below warning/error:

[WARNING ] The cloud driver, 'hetzner', configured under the 'hcloud' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'hetzner' driver.
In rare cases, this could indicate the 'hetzner.get_configured_provider()' function could not be found.
Removing 'hetzner' from the available providers list
Error: There was an error listing providers: There are no cloud providers configured. 

**Setup**

cat /etc/salt/cloud.providers.d/hetzner.conf 
hcloud:
  driver: hetzner
  key: xxxx

pip3 list 2>/dev/null | grep hcloud
hcloud (1.13.0)

hcloud version
hcloud 1.25.1

**Steps to Reproduce the behavior**
1. create hetzner.conf file under /etc/salt/cloud.providers.d/ with the content:

hcloud:
  driver: hetzner
  key: xxxx

2. execute salt-cloud --list-providers

**Expected behavior**

salt-cloud --list-providers shoudl list hetzner provider

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.26.8
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.26.4
        Python: 3.6.8 (default, May 24 2021, 08:40:28)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: almalinux 8.4 Electric Cheetah
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-305.7.1.el8_4.x86_64
        system: Linux
       version: AlmaLinux 8.4 Electric Cheetah
```
</details>

**Additional context**

**Comment by robinkaranu** [comment]
I got the same issue. I will try to collect and post some further information on my setup/issue this weekend. Is there anything in particular that I should look for? Importing (and using) the hcloud module from the same python installation that salt is using does work for me.

**Comment by fkantelberg** [comment]
I encountered the same problem with the same version. #60675 solved it for me locally.

My full log entry in /var/log/salt/cloud was:
```
The cloud driver, 'hetzner', configured under the 'hetzner-landkreis-harz' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'hetzner' driver.
In rare cases, this could indicate the 'hetzner.get_configured_provider()' function could not be found.
```

Can you confirm that it's the same bug? @robinkaranu @mngitb

**Comment by robinkaranu** [comment]
Yes @fkantelberg, that indeed seems to fix the problem for me.

I did only test `--list-providers` for now, but instead of 
```
[WARNING ] The cloud driver, 'hetzner', configured under the 'my-hetzner-redacted-infra' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'hetzner' driver.
In rare cases, this could indicate the 'hetzner.get_configured_provider()' function could not be found.
Removing 'hetzner' from the available providers list
```

after applying your patch i can now see the provider configured in output:

```
my-hetzner-redacted-infra:
    ----------
    hetzner:
        ----------

```

Thanks for sharing! :+1:

**Comment by mngitb** [comment]
@fkantelberg thank you! , your patch solved my issue

Best wishes!
