### ISSUE TITLE
[DOCS] --batch-wait is not documented in the salt(1) man page

### ISSUE THREAD

**Issue by justinclloyd** [saltstack/salt#60629]
**Description**
The `--batch-wait` argument to *salt(1)*  is in the [online docs](https://docs.saltproject.io/en/latest/topics/targeting/batch.html) but not the [man page](https://github.com/saltstack/salt/blob/master/doc/man/salt.1).

**Comment by ScriptAutomate** [comment]
Thanks for the issue!

When looking at the man pages, which are managed in an automated fashion via `nox` (like in this example PR: https://github.com/saltstack/salt/pull/60648), the man pages are collectively found here:
- https://github.com/saltstack/salt/tree/master/doc/man

When on the CLI, running `man salt` will automatically open up a rendered `salt.7` (as `SALT(7)`):

```
SALT(7)                                                         Salt                                                         SALT(7)

NAME
       salt - Salt Documentation

SALT PROJECT
       Salt  Project License: Apache v2.0PyPi Package DownloadsPyPi Package DownloadsSalt Project Slack CommunitySalt Project Twitch
       ChannelSalt Project subredditFollow SaltStack on Twitter.INDENT 0.0
         [image: Salt Project Logo] [image]

       • Latest Salt Documentation

       • Open an issue (bug report, feature request, etc.)

       Salt is the world’s fastest, most intelligent and scalable automation engine.
...
...
...
```

The option can be searched and found with `/bash-wait`, which will bring you to:

```
...
...
       This will only run test.version on 10 of the targeted minions at a time and then restart apache on 25% of the minions  match‐
       ing  os:RedHat  at  a  time  and  work  through  them all until the task is complete. This makes jobs like rolling web server
       restarts behind a load balancer or doing maintenance on BSD firewalls using carp much easier with salt.

       The batch system maintains a window of running minions, so, if there are a total of 150 minions targeted and the  batch  size
       is  10, then the command is sent to 10 minions, when one minion returns then the command is sent to one additional minion, so
       that the job is constantly running on 10 minions.

       New in version 2016.3.

       The --batch-wait argument can be used to specify a number of seconds to wait after a minion returns, before sending the  com‐
       mand to a new minion.

   SECO Range
       SECO range is a cluster-based metadata store developed and maintained by Yahoo!
...
...
```

If wanting to search the `raw` man pages in this repo, can do so with `grep 'batch\\-wait' doc/man/* -A5 -B5`:

```
12:00 $ grep 'batch\\-wait' doc/man/* -A5 -B5
doc/man/salt.7-additional minion, so that the job is constantly running on 10 minions.
doc/man/salt.7-.sp
doc/man/salt.7-New in version 2016.3.
doc/man/salt.7-
doc/man/salt.7-.sp
doc/man/salt.7:The \fB\-\-batch\-wait\fP argument can be used to specify a number of seconds to
doc/man/salt.7-wait after a minion returns, before sending the command to a new minion.
doc/man/salt.7-.SS SECO Range
doc/man/salt.7-.sp
doc/man/salt.7-SECO range is a cluster\-based metadata store developed and maintained by Yahoo!
doc/man/salt.7-.sp
```

Are you meaning that you want to see it available via `man 1 salt-call`, for example? Rather than that it is missing from the man pages in general, or? To see it as an arg in section 1 instead of just the docs rendering in section 7, which is a replica of the HTML site you linked?

**Comment by justinclloyd** [comment]
When typing `man salt`, the default man section is 1, and *salt(1)* is a far more manageable document when just looking up the runtime options for the basic `salt` command. To be honest, I've never even looked at *salt(7)*, as I'd go onto the web site for a full-length treatise on Salt. IMHO, there's no reason to have command-line options not documented on the command's basic man page, especially when `-b (--batch-size)` is already there. Why *wouldn't* `--batch-wait` be there as well?

**Comment by ScriptAutomate** [comment]
That makes sense. I have a feeling there are multiple CLI args missing from `salt.1`. Adding `--batch-wait` would be a good first step toward improving that documentation. I'll have to look into how Salt generates `salt.1` via Sphinx, and where the arg needs to be added within the codebase.

**Comment by ScriptAutomate** [comment]
I opened a PR for these batch args to be added to the section 1 man page (`salt.1`):

```
    --batch-wait
    --batch-safe-limit
    --batch-safe-size
```

And I opened a follow-up issue for a more thorough audit of missing args in general.
