### ISSUE TITLE
Run curl command in loop till the output response is SUCCESS

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#60637]
How to run curl command in loop till the output response is SUCCESS in a salt state file?

I have tried with salt['cmd.run']. But not able to run multiple times or get the required end value

{% set cache_response = salt['cmd.run']('curl -s -X GET -H "Content-Type: application/json" -k  https://vertex-dev.rno.apple.com:8409/hccif/rest/cachewarmupstatus/e33dfrfnerfjnr') %}

**Comment by eliasp** [comment]
There are several ways to do this:
- Use the [`until`](https://docs.saltproject.io/en/3000/ref/states/requisites.html#retrying-states) requisite to repeat a state a defined number of times until it succeeds or finally fails
- Use the [`http.wait_for_successful_query`](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.http.html#salt.states.http.wait_for_successful_query) state which basically comes with this functionality out-of-the-box
