### ISSUE TITLE
How can we install multiple RPMS placed on dir in salt-master to minions

### ISSUE THREAD

**Issue by numantahir123** [saltstack/salt#60644]
What I'm trying is this
`rpm-packages-install:
   - sources: 
     - rpm_name: salt://dir1/dir2/`
  
Let's assume dir2 contains all RPMS
I tried,  
rpm_name salt://dir1/dir2/*.rpm 
But it did not work. Is there any smarter way to do that?

**Comment by OrangeDog** [comment]
You can get a list of all files in that directory, and iterate over it with jinja, something like this (not tested)
```sls
rpm-packages-install:
  pkg.installed:
    - sources:
{% for rpm in salt["cp.list_master"](prefix="/dir1/dir2/") %}
      {{ rpm.split("/")[-1].split(".")[0] }}: salt:/{{ rpm }}
{% endfor %}
```
