### ISSUE TITLE
[BUG] - nacl.dec returns byte array and is tricky to use with some jinja

### ISSUE THREAD

**Issue by steverweber** [saltstack/salt#60653]
**Description**

when using {{salt.nacl.dec('...')|json}} in a pillar I get error:
`'bytes' is not JSON serializable`

**Expected behavior**

The decrypted data be added to the pillar.

**Versions Report**

```
root@salt-master-p01-02:~# salt --versions-report
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5
 
System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-151-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```

**Comment by steverweber** [comment]
we just need to toss .decode on the returned byte array. I'll fire a PR at this.

**Comment by StefanTT** [comment]
For those like me that stumble over this bug: a workaround is to use the NACL renderer as described here: https://docs.saltproject.io/en/latest/ref/renderers/all/salt.renderers.nacl.html

**Comment by dmurphy18** [comment]
Check if this is an issue with the changes in PR https://github.com/saltstack/salt/pull/64415

**Comment by dmurphy18** [comment]
@steverweber Would you be able to retry this with a nightly build of the master branch. The master branch has been changed from using libnacl to PyNaCl, see PR https://github.com/saltstack/salt/pull/64415 and I suspect that the intervening changes are no longer valid.

Also curious if there are other interactions with the change to PyNaCl that might be encountered.

**Comment by dmurphy18** [comment]
Closing due to unresponsive, please re-open if further information to consider concerning this issue

**Comment by bwdbethke** [comment]
> For those like me that stumble over this bug: a workaround is to use the NACL renderer as described here: https://docs.saltproject.io/en/latest/ref/renderers/all/salt.renderers.nacl.html

that works for me on single-line values, but I also need to decrypt some (multi-line) files that were NACL encrypted. Do you know how to do that with the alternate syntax?
