### ISSUE TITLE
[FEATURE REQUEST] salt.states.virt: support autostart for VMs

### ISSUE THREAD

**Issue by dseomn** [saltstack/salt#60700]
**Describe the solution you'd like**
It would be nice to have a way to control whether a VM starts on boot or not. Maybe a new `autostart` option to salt.states.virt.running and/or salt.states.virt.defined? Or maybe a new function?

**Describe alternatives you've considered**
I'll probably use salt.modules.virt.set_autostart for now.

**Comment by garethgreenaway** [comment]
@cbosdo FYI.

**Comment by cbosdo** [comment]
@dseomn Thanks for the feature request: after 7 years working on and with libvirt I wasn't aware we could autostart domains!

Since the `virt` module already has the function for it, it just means adding the feature on the `virt.running` state. I would be happy to help you work on such a simple change!

**Comment by XelK** [comment]
@cbosdo Hello, does this still relevant? Can I try to implement this?

**Comment by cbosdo** [comment]
> @cbosdo Hello, does this still relevant? Can I try to implement this?

Yes it's still relevant. The functions to change are `virt.defined()` and `virt.running()` in https://github.com/saltstack/salt/blob/master/salt/states/virt.py.  You just need to use the `virt.set_autostart()` module function in those. I would happily review your PR!

**Comment by XelK** [comment]
Hi @cbosdo could you please check my PR https://github.com/saltstack/salt/pull/61735

**Comment by gidoBOSSftw5731** [comment]
Is this feature implemented yet? And also, is it implemented for virsh networks as well?

**Comment by cbosdo** [comment]
Yes it's implemented for domains and networks. I'll close the issue, thanks for the heads up
