### ISSUE TITLE
[BUG] cmd.run shell=powershell on Windows 2016 servers error

### ISSUE THREAD

**Issue by AGirin** [saltstack/salt#60721]
**Description**
salt -G 'kernel:Windows' cmd.run 'Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol' shell=powershell

Windows 2019:

FeatureName      : SMB1Protocol
    DisplayName      : SMB 1.0/CIFS File Sharing Support
    Description      : Support for the SMB 1.0/CIFS file sharing protocol, and the Computer Browser protocol.
    RestartRequired  : Possible
    State            : Disabled

Windows 2016:

Get-WindowsOptionalFeature : An attempt was made to load a program with an incorrect format.
    At line:1 char:1
    + Get-WindowsOptionalFeature -Online -FeatureName SMB1Protocol
    + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        + CategoryInfo          : NotSpecified: (:) [Get-WindowsOptionalFeature], COMException
        + FullyQualifiedErrorId : Microsoft.Dism.Commands.GetWindowsOptionalFeatureCommand

**Setup**
Just trying to run form cmd.run

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: 0.28.2
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: 0.28.2
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.36.2.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

```
</details>

**Comment by AGirin** [comment]
I ran this to get what I needed: 

salt -G 'kernel:Windows' cmd.run 'Get-SmbServerConfiguration | Select EnableSMB1Protocol' shell=powershell

And it worked just fine.

Still the question remains why is the original command not working on Windows 2016...

**Comment by OrangeDog** [comment]
Does it work if you run it manually in PowerShell on the 2016 minion?
Is it the same version of Salt and Python on each minion?

That looks like a .NET exception when there's a 32/64-bit mismatch.
It's definitely from PowerShell, so the `shell` option worked.

**Comment by twangboy** [comment]
I can confirm that both commands work under 64bit powershell.
The first command fails with the above error on 32bit powershell, the 2nd succeeds.

I suspect you are running the 32bit minion on 64bit Windows.
