### ISSUE TITLE
[BUG] Jinja2 warns that Jinja2 3.1 will no longer support contextfunction, must use renamed decorater as pass_context

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#60745]
**Description**

Jinja gives a warning that `contextfunction` is being renamed to `pass_context` in Jinja 3.1:

```bash
/root/.pyenv/versions/3.6.10/lib/python3.6/site-packages/salt/utils/jinja.py:715: DeprecationWarning: 'contextfunction' is renamed to 'pass_context', the old name will be removed in Jinja 3.1.
```

This looks like it may be a slight fix by modifying https://github.com/saltstack/salt/blob/master/salt/utils/jinja.py#L709 in order to avoid future problems with Jinja as our dependency tree upgrades over time. Though, I don't know how many additional steps may need to occur to ensure we can upgrade the dependency tree to contain Jinja 3.x.

Other related Salt issues around Jinja 3.x:

- https://github.com/saltstack/salt/issues/60188

**Additional context**

Ref: https://github.com/pallets/jinja/issues/1381

**Comment by jonyhy96** [comment]
Any update on this?
