### ISSUE TITLE
--subset only uses 3 as argument

### ISSUE THREAD

**Issue by ewhitesides** [saltstack/salt#60751]
### Description of Issue
for testing commands on a large number of systems, I've found it helpful to use the subset parameter to just do a handful to speed up testing.  I noticed that no matter what number you give the --subset argument, it only performs the given operation on 3 minions.

### Steps to Reproduce Issue
salt <target large group of machines> test.ping --subset=5

### Versions Report
3003.1 all around

**Comment by OrangeDog** [comment]
Duplicates #58600
