### ISSUE TITLE
[TEST FAILURE] pr-lint and Static Analysis failures in PRs with unrelated changes

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#60757]
> Opened this issue as a result of https://github.com/saltstack/salt/pull/60255

Errors in https://github.com/saltstack/salt/pull/60255 tests are unrelated to the PR itself, since they have to do with the `salt` codebase. Examples:

- Error rooted in `pr-lint` which is doing static code analysis: https://jenkins.saltproject.io/job/pr-lint/job/PR-60255/14/console
```
16:09:58  [Static Analysis] [-ERROR-] Setting the reference job has been deprecated, please use the new reference recorder
16:09:58  [Static Analysis] [-ERROR-] Configured reference job 'pr-lint/env.CHANGE_TARGET' does not exist
16:09:58  [Static Analysis] No valid reference build found that meets the criteria (No history found)
16:09:58  [Static Analysis] All reported issues will be considered outstanding
16:09:58  [Static Analysis] Evaluating quality gates
16:09:58  [Static Analysis] -> FAILED - Total (any severity): 5 - Quality QualityGate: 1
16:09:58  [Static Analysis] -> Some quality gates have been missed: overall result is FAILED
16:09:58  [Static Analysis] Health report is disabled - skipping
16:09:58  [Static Analysis] Created analysis result for 5 issues (found 0 new issues, fixed 0 issues)
16:09:58  [Static Analysis] Attaching ResultAction with ID 'analysis' to build 'pr-lint/PR-60255 #14'.
16:09:59  [GitHub Checks] GitHub check (name: Static Analysis, status: COMPLETED) has been published.
```
- Static analysis errors/warnings against Salt codebase: https://jenkins.saltproject.io/job/pr-lint/job/PR-60255/14/analysis/
  - These have to do with Python static code analysis of the `salt/*` dir

I'm not sure what the other failures may be, but these failures above are unrelated.

**Comment by Ch3LL** [comment]
I'm not seeing this anymore. Closing
