### ISSUE TITLE
[BUG] Netmiko proxy fails with develop branch of Netmiko due to netmiko execeptions rename

### ISSUE THREAD

**Issue by auphofBSF** [saltstack/salt#60762]
**Description**
To use `salt.proxy.netmiko_py` with a set of fixes in Netmiko  the Netmiko develop branch  is installed `pip install git+https://github.com/ktbyers/netmiko.git@develop`

Netmiko Proxy fails with Proxymodule netmiko is missing.........
will not load netmiko and proxy call fails

Debugging it has tracked it to the following Netmiko - commit [Moving exceptions file to more logically named file](https://github.com/ktbyers/netmiko/commit/b8adf)

It is very likely the netmiko commit responsible for the failure goes into a a future version> 3.4.0.

I have a draft PR ready to submit to fix this

**Setup**
generic salt v3003.2 calling proxy with salt-sproxy and develop branch of Netmiko

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [X] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
with salt-sproxy installed, however will be same with just salt proxy
```bash
#install develop branch of Netmiko 
pip install git+https://github.com/ktbyers/netmiko.git@develop

salt-sproxy  router1 netmiko.send_command '/ip address print'
```

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3003.2

Dependency Versions:
          cffi: 1.14.4
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.11 (default, Jun 29 2021, 21:15:56)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: alpine 3.13.5
        locale: UTF-8
       machine: x86_64
       release: 4.19.128-microsoft-standard
        system: Linux
       version: Alpine Linux 3.13.5

salt-sproxy --version
     salt-sproxy 2021.6.1
```

</details>

**Additional context**

**Comment by garethgreenaway** [comment]
Fixed by https://github.com/saltstack/salt/pull/62412
