### ISSUE TITLE
[BUG] AzureFS doesn't work with latest versions of the Azure.Storage wheel

### ISSUE THREAD

**Issue by hirez-masmith** [saltstack/salt#60801]
**Description**
AzureFS filesystem module does not function with latest versions of azure-storage wheel due to missing __version__ attribute within their wheel.
Microsoft has said they won't be fixing it. 
https://github.com/Azure/azure-storage-python/issues/535

**Setup**
Add `azurefsfs` (extra FS needed due to https://github.com/saltstack/salt/issues/58041) to fileserver configuration after roots.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [x] VM running on a cloud service, please be explicit and add details
-- Azure-hosted VM
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
I had to add custom logging into the azurefs.py file to detect the error properly because the module, as written, doesn't actually report anything to any logs when it fails to initialize. At a minimum, it would be nice for this module to report why it's not doing what it should be doing so this level of spelunking isn't necessary.

Custom logging was added to the try at the top of the file attempting to import azure.storage. I had to move the log instantiation above this try block as well.
```
except (ImportError, AttributeError) as e:
    HAS_AZURE = False
    log.error(e)
```

Error that was then reported to the saltmaster log is:
`2021-08-27 14:23:35,120 [root             :79  ][ERROR   ][7246] module 'azure.storage' has no attribute '__version__'`

After commenting out the version check (since Microsoft doesn't want to follow conventions 😛) I hit an error that the hashes directory wasn't found on disk.
`FileNotFoundError: [Errno 2] No such file or directory: '/var/cache/salt/master/azurefs/hashes'`

I created that directory to attempt to bypass the error (created as the same user the master is running as)

I then discovered that the `CloudStorageAccount` object being utilized has been moved in the latest azure storage wheel.
So I modified the file once again to import the object properly via:
`from azure.storage.common.cloudstorageaccount import CloudStorageAccount` 
Within the same try block for the azure.storage wheel in general. I did the import this way as is convention within our internal codebase.

This finally allowed the FS to at least be able to query the available files / dirs within our private container.

Sending this in, in the hopes that I won't have to maintain these changes in all subsequent version updates of the salt master.

**Expected behavior**
The AzureFS filesystem package behaves properly with versions of the azure.storage wheel in line with latest iterations of the Azure Python SDK.

**Versions Report**
<details><summary>salt --versions-report</summary>
**(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)** 

```
Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.14.4
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-1039-azure
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver
```
</details>

**Additional context**

**Comment by nicholasmhughes** [comment]
The Azure functionality in Salt is moving to https://github.com/salt-extensions/saltext-azurerm

I have opened an issue there to represent the bug outlined here.
