### ISSUE TITLE
[FEATURE REQUEST] salt/modules/aptpkg.py find an alternative to using python-apt

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#60818]
Fixes this issue: https://gitlab.com/saltstack/open/salt-pkg/-/issues/38

This issue is created to track adding an alternative solution to using python-apt. We want to avoid using a c-implementation library in our tiamat packages, because it would require building a package per OS and we want to create one that can run on any linux OS.

**Comment by waynew** [comment]
Do we have an alternative package target?

**Comment by Ch3LL** [comment]
> Do we have an alternative package target? 

I have not found a pure python implementation library since creating this issue, other than a very old library on pypi that the team that manages python-apt stated they do not own and someone uploaded a version in 2012 and they do not want to upload to pypi. So my plan is to shell out with apt commands to replace the package repo commands that the current python-apt package is helping manage. (list_repos, get_repo, del_repo, mod_repo,expand_repo_def,)

>  Or do we really need to find a brand new one?

We need to find an alternative solution not necessarily a different package, because the python-apt library would require us to build a package per OS for single binary and onedir packages which we want to avoid.

**Comment by waynew** [comment]
> When in doubt, shell out

:grinning: 

That seems reasonable to me - `apt-get` is considered a well-defined API for use via tools, so I have no qualms there :+1:

**Comment by jensgw** [comment]
You forgot to update the docs:
https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.aptpkg.html
