### ISSUE TITLE
[FEATURE REQUEST] Create a cli parameter to overwrite git_branch without affecting the pillarenv

### ISSUE THREAD

**Issue by Nerigal** [saltstack/salt#60825]
Create a parameter for cli to overwrite git_branch without affecting the `pillarenv`

```
ext_pillar:
  - git:
    - __env__ https://gitserver/git-pillar.git:
      - root: pillar
      - env: base
```  

`salt 'newinstance02' pillar.items pillarenv=dev`

Base on the above example, the current behavior is that `pillarenv` defined the branch but also overwrite the `env:` value 
or this is at least the exact behavior i have right now with version 3003 for both master and minion 

and in fact it is kind of strange to have to manipulate the `pillarenv` to target a custom branch 

Expected behavior would be like:

To define both but different value :
`salt 'newinstance02' pillar.items pillarenv=dev git_branch=master`

To define different branch without affecting the `pillarenv`:
`salt 'newinstance02' pillar.items  git_branch=master`

This would allow much better flexibility to develop in parallel when having  pillar / states  on a git repo

for example all production server are under de default "base" env for pillar as well as states
base = master branch in a git
dev = dev branch
but no one can merge in master without following the merge request process which is long and take time
but in the Operational point of view when you have an incident this is not realistic
you may need to create a quick fix under a custom branch with for example the ticket ID
and being able to push the new config from using the master "base" env for state but with the new custom branch for pillar
vice versa

as well as testing config from a personnel branch without affecting the environment of the server.. because the environment cannot be changed

and the other reason is that this feature is already available in Ansible and very usefull and a show stopper to migrate to saltstack...

New from https://github.com/saltstack/salt/issues/60410 because some funny guy closed it

**Comment by OrangeDog** [comment]
Please do not open duplicates. Continue discussion on the original if necessary.
