### ISSUE TITLE
documentation error in module "network.list_networks" usage

### ISSUE THREAD

**Issue by rajhotagit19** [saltstack/salt#60835]
### Description of Issue
There is a documentation error in network.list_networks module in CLI example. It should be corrected in documentation pages as well as in the salt binaries.

### Setup

Salt doc says that the module can be used as the given CLI examples, but that really throws an error.

[ ] $ sudo salt-call  sys.doc network.ip_networks
local:
    ----------
    network.ip_networks:

            New in version 3001

            Returns a list of IPv4 networks to which the minion belongs.

            interface
                Restrict results to the specified interface(s). This value can be
                either a single interface name or a list of interfaces. Globbing is
                also supported.

            CLI Example:

                salt '*' network.list_networks
                salt '*' network.list_networks interface=docker0
                salt '*' network.list_networks interface=docker0,enp*
                salt '*' network.list_networks interface=eth*

[ ] $

### Steps to Reproduce Issue
Example output:-
[ ] $ sudo salt -N linux network.list_networks
hotap-sls-min:
    'network.list_networks' is not available.
hotap1:
    'network.list_networks' is not available.
ERROR: Minions returned with non-zero exit code
[ ] $ sudo salt -N linux network.ip_networks
hotap-sls-min:
    - 10.0.2.0/24
    - 192.168.56.0/24
hotap1:
    - 10.0.2.0/24
    - 10.202.20.83/32
    - 192.168.56.0/24
[ ] $

### Versions Report

**Salt-Minion:-**

hotap-sls-min:
    Salt Version:
              Salt: 3003.2

    Dependency Versions:
              cffi: Not Installed
          cherrypy: Not Installed
          dateutil: 2.7.3
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.0
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: Not Installed
      pycryptodome: 3.6.1
            pygit2: Not Installed
            Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
      python-gnupg: 0.4.5
            PyYAML: 5.3.1
             PyZMQ: 18.1.1
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.2

    System Versions:
              dist: ubuntu 20.04 focal
            locale: utf-8
           machine: x86_64
           release: 5.11.0-27-generic
            system: Linux
           version: Ubuntu 20.04 focal

**Master Salt-Server:-**

hotap1:                  
    Salt Version:
              Salt: 3003

    Dependency Versions:
              cffi: Not Installed
          cherrypy: 8.9.1
          dateutil: 2.7.3
         docker-py: Not Installed
             gitdb: 2.0.6
         gitpython: 3.0.7
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.0
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: Not Installed
          pycrypto: 2.6.1
      pycryptodome: 3.6.1
            pygit2: Not Installed
            Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
      python-gnupg: 0.4.5
            PyYAML: 5.3.1
             PyZMQ: 18.1.1
             smmap: 2.0.5
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.3.2

    System Versions:
              dist: ubuntu 20.04 focal
            locale: utf-8
           machine: x86_64
           release: 5.11.0-27-generic
            system: Linux
           version: Ubuntu 20.04 focal
[ ] $

**Comment by rajhotagit19** [comment]
Similarly there is documentation error in its another sub module which is currently written as following in all resources. 
It should be 

salt '*' network.ip_networks6 
 and so on in its all sort of documents. 


- Web:- https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.network.html

salt.modules.network.ip_networks6(interface=None, include_loopback=False, verbose=False)
New in version 3001.

Returns a list of IPv6 networks to which the minion belongs.

interface
Restrict results to the specified interface(s). This value can be either a single interface name or a list of interfaces. Globbing is also supported.

CLI Example:

salt '*' network.list_networks6
salt '*' network.list_networks6 interface=docker0
salt '*' network.list_networks6 interface=docker0,enp*
salt '*' network.list_networks6 interface=eth*



- As seen from modules directories(Example /usr/lib/python3/dist-packages/salt/modules/network.py) :- 


Ex:-

$ grep -A23 -m1 "ip_networks6" /usr/lib/python3/dist-packages/salt/modules/network.py
def ip_networks6(interface=None, include_loopback=False, verbose=False):
    """
    .. versionadded:: 3001

    Returns a list of IPv6 networks to which the minion belongs.

    interface
        Restrict results to the specified interface(s). This value can be
        either a single interface name or a list of interfaces. Globbing is
        also supported.

    CLI Example:

    .. code-block:: bash

        salt '*' network.list_networks6
        salt '*' network.list_networks6 interface=docker0
        salt '*' network.list_networks6 interface=docker0,enp*
        salt '*' network.list_networks6 interface=eth*
    """
    return __utils__["network.ip_networks6"](
        interface=interface, include_loopback=include_loopback, verbose=verbose
    )
$


Hence, it would be a great to help update all sort of documentations.

**Comment by OrangeDog** [comment]
@rajhotagit19 go ahead any fix anything that obviously needs fixing

**Comment by rajhotagit19** [comment]
Thanks a lot @OrangeDog for your kind reply. :) 
As I have no access your repository to push new commits to your [PR# 60839](https://github.com/saltstack/salt/pull/60839), hence I have opened a new [PR# 60886](https://github.com/saltstack/salt/pull/60886) with combined data required to update the module.

It would be great, if you have access and able to review the same and approve.

Many thanks.
Pravanjan Hota.
