### ISSUE TITLE
salt-minion with python 2.7.13  cmd.run / cmd.script does not work with match.grain 

### ISSUE THREAD

**Issue by jrpersson123** [saltstack/salt#60840]
### Description of Issue
I get the below error when using cmd.run or cmd.script with match.grain on SLES 12 SP4 mionion using python 2.7.13.  If I remove the match grain, it works.  If I use a different module for example file.managed it works.  There is only an issue when using cmd.* modules in salt states.  It works in sles 15 with python 3 but there is no upgrade path for salt-minion to use python 3 with sles 12.

### Setup
an example salt state:

hana_user_task_max:
  cmd.run:
    - name: sed -i '/\[Login\]/a UserTasksMax=infinity' /etc/systemd/logind.conf
    - onlyif:
      - fun: match.grain
        tgt: 'HANA:Y'
    - unless:
      - cat /etc/systemd/logind.conf | grep UserTasksMax=infinity

### Steps to Reproduce Issue
1. create salt state with cmd.run and use match.grain to target either custom or existing grains.
 error:

An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1999, in call
                  ret = self.states[cdata['full']](*cdata['args'], **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 2036, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/states/cmd.py", line 892, in run
                  cret = mod_run_check(cmd_kwargs, onlyif, unless, creates)
                File "/usr/lib/python2.7/site-packages/salt/states/cmd.py", line 351, in mod_run_check
                  cmd = __salt__['cmd.retcode'](entry, ignore_retcode=True, python_shell=True, **cmd_kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 2275, in retcode
                  **kwargs)
                File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 387, in _run
                  _log_cmd(cmd),
                File "/usr/lib/python2.7/site-packages/salt/modules/cmdmod.py", line 82, in _log_cmd
                  return cmd[0].strip()

### Versions Report
Minion:
---------

salt-call --versions-report
/usr/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 3, 1]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Salt Version:
           Salt: 3000

Dependency Versions:
           cffi: 1.5.2
       cherrypy: Not Installed
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.6
   mysql-python: Not Installed
      pycparser: 2.10
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.13 (default, Jan 11 2017, 10:56:06) [GCC]
   python-gnupg: Not Installed
         PyYAML: 5.1.2
          PyZMQ: 14.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.0.4

System Versions:
           dist: SuSE 12 x86_64
         locale: ANSI_X3.4-1968
        machine: x86_64
        release: 4.12.14-95.54-default
         system: Linux
        version: SUSE Linux Enterprise Server  12 x86_64

Salt Master
-------------

Salt Version:
          Salt: 3002.2

Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: sles 15.3 2021.05
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-59.16-default
        system: Linux
       version: SLES 15.3 2021.05

**Comment by OrangeDog** [comment]
Different major versions between master and minions are not generally supported, nor are Salt 3000 nor Python 2.
Can you upgrade?

**Comment by jrpersson123** [comment]
Hi, thanks for the reply.  What do you mean by: "nor are Salt 3000 nor
Python 2."

**Comment by OrangeDog** [comment]
I mean they're not supported either. You won't get any fixes to those.
If you upgrade and the issue is still there, then it can be fixed.

**Comment by jrpersson123** [comment]
Ok thanks. Can you help with a way to install salt minion on sles 12 so
that it uses python 3?  I have python 3 installed on my sles 12. The salt
docs dont show a supported install for sles 12 and python 3.

**Comment by OrangeDog** [comment]
SLES 12 was EOL in 2019, so that's not supported either.

The easiest way is probably to use `pip` to install for Python 3.

**Comment by garethgreenaway** [comment]
As pointed out above, Python 2.7.x and Salt 3000 is EOL and no longer supported.  If the issues persist is updated version of both Python and Salt, please feel free to open a new issue.  Thanks!
