### ISSUE TITLE
Handle JSON columns for SQL pillars

### ISSUE THREAD

**Issue by cbosdo** [saltstack/salt#60905]
**Is your feature request related to a problem? Please describe.**

Querying database for single column JSON data (like postgresql JSON or JSONB types) returns dict. Dict is not hashable and results in error in sql external pillar.

**Describe the solution you'd like**

Adding an `as_json` parameter to the `ext_pillar` would allow proper handling of the returned dictionary.

**Comment by garethgreenaway** [comment]
Closing this out since the linked PR has been merged.
