### ISSUE TITLE
[BUG] salt bootstrap script broken by repo URL changes

### ISSUE THREAD

**Issue by sbconslt** [saltstack/salt#60928]
**Description**
Changes to the repo.saltproject.io repo URLs apparently landing today have not been concurrently accomodated in the script served from https://bootstrap.saltproject.io. This is currently causing multiple versions of salt minion to fail to install for us as the script 404s on the repo pull. I have tried several versions between 3000 and 3003 and all failed.

**Setup**
Our targets are Ubuntu 18.04 LTS in Google Cloud Platform. The bootstrap script was tested working yesterday but is failing today. Initially it was detected during GCE startup script operation on freshly instantiated VMs, but the problem has been reproduced in debugging attempts on running machines as well.
  
**Steps to Reproduce the behavior**
curl -fsSL https://bootstrap.saltproject.io -o install_salt.sh
sudo /bin/sh ./install_salt.sh -A salt -D -P stable <any_version>

**Expected behavior**
salt-minion installs without error

**Versions Report**
As the minion has not been installed, cannot produce a version report. Attempted bootstrap install with several versions, but always 404s on repo.saltproject.io URLs.

**Comment by sbconslt** [comment]
Update: Passing the additional option `-R "archive.repo.saltproject.io"` to the bootstrap's `install_salt.sh` allowed us to install the version of salt-minion on the layout of the operating system in question.

**Comment by bryceml** [comment]
Newer versions of the bootstrap script default to python3, have you tried a more recent version of the bootstrap script?

You can also use `-x python3` on older versions of the bootstrap script.

Please let us know if a newer version of the bootstrap script solves your issue.

**Comment by sbconslt** [comment]
The root cause was that the v3000 repos were moved to `archive.repo.saltproject.io` and the bootstrap.sh was not updated to gracefully reflect that transition. Insofar as v3000 is past EOL I guess there is no reasonable expectation that bootstrap.sh would continue to support it. Our bad for running v3000 into the teeth of EOL. That's how things happen.
