### ISSUE TITLE
[BUG] How can we use the grains value of minion A in minion B?

### ISSUE THREAD

**Issue by sooraj2589** [saltstack/salt#60920]
**Description**
How can we use the grains value of minion A in minion B?

I have created a state file, in which it will set a grain value in minion A. Now I need to use that grain value in another state file on minion B.

Will salt support the feature of minion-minion grains usage?

I couldn't find any workable solutions. Could any one please help?

  

**Versions Report**
salt 3000.2

**Comment by OrangeDog** [comment]
The usual solution is to publish the necessary grains in the Salt Mine.
https://docs.saltproject.io/en/latest/topics/mine/
