### ISSUE TITLE
[BUG] User profile on Windows depends on currently logged in desktop sessions

### ISSUE THREAD

**Issue by achimmihca** [saltstack/salt#60938]
**Description**
I have two Windows users: `normal-user`, and `salt-user`.
I want to use the salt-user to run scripts via `cmd.run`. Therefor, I pass `runas` and `password` parameter.

The problem is that the user profile is different, depending on salt-user is logged in or not on the machine.
By "logged in", I mean another currently running desktop session (via "switch user" from my normal-user desktop session).

Example: test-user.sls
```
print user profile data:
  cmd.run:
    - name: |
        echo $env:USERPROFILE
        echo $env:PATH
    - shell: powershell
    - runas: salt-user
    - password: the-password
```

*When salt-user is NOT logged in to another desktop session*
- USERPROFILE is `C:\Users\Default`.
- PATH is the system-wide PATH, but the PATH for salt-user is missing

*When salt-user is logged in to another desktop session*
- USERPROFILE is `C:\Users\salt-user`
- PATH is the system-wide PATH plus the PATH of salt-user

Note that the salt-user password is checked correctly, i.e., when I change the password in the sls file, then the login does not work. Thus, I am actually using the salt-user and not something else (e.g. the system user).

Note further that the salt-user is a domain user. But because of #60076 I cannot specify the domain part.
Maybe this is part of the issue, i don't know how Windows is handling this.

**Setup**
So far, I am only evaluating SaltStack.
I have installed the salt-master on Ubuntu 20.04 (WSL running in Windows) and the salt-minion on the same Windows PC.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

**Steps to Reproduce the behavior**
- Install and connect recent salt-master and salt-minion
- setup two user accounts on Windows.
    - Note that salt-user in my case is a domain user. I am unsure if this is relevant.
- create sls file as in the example above
- run `salt '*' state.apply test-user`
    - shows the system PATH
- switch user in Windows, login as salt-user
- switch back in Windows to normal-user, but keep salt-user logged in
- re-run `salt '*' state.apply test-user`
    - shows the salt-user PATH 
- switch user in Windows to salt-user
- logout salt-user, switch back to normal-user
- re-run `salt '*' state.apply test-user`
    - shows (again) the systen PATH 

**Expected behavior**
It should always use the salt-user USERPROFILE and PATH when using cmd.run with runas.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun  2 2021, 10:49:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 4.4.0-19041-Microsoft
        system: Linux
       version: Ubuntu 20.04 focal
```

```
salt-minion 3003.3
```

```
Microsoft Windows 10 Pro
Version	10.0.19043 Build 19043
```
</details>

**Comment by twangboy** [comment]
I think this is the behavior of Windows. If you watch the registry, for example, the User hive is only loaded while the user is logged in. Once the user logs off, the registry hive is unloaded. A better solution may be to set up a "Multi-Minion" scenario. One minion is set up as a service (Default installation) and performs system-wide management. The 2nd minion starts when the user logs in and runs under the user context. It can only do things the user can do, but it does them the user profile. It's a pretty new concept and we probably have some bugs to work out, but that's the idea. There's a script in the installation called `multi-minion.ps1` that should create a running minion in a different context.
