### ISSUE TITLE
[RESOLVED Orphaned binary files /srv/salt/modules/runners/__pycache__ are executed 

### ISSUE THREAD

**Issue by marbx** [saltstack/salt#60957]
### Description

Create `/srv/salt/modules/runners/foo.py`

```
import salt.client
salt_client = salt.client.LocalClient()
minion = "bob"
minion_data = salt_client.cmd(minion, 'cmd.run', ['whoami'])
print(f"ok whoami {minion_data}")

```

Run `python3 /srv/salt/modules/runners/foo.py` and observe `ok whoami {'bob': b'nt-autorit\x84t\\system'}`

Delete `/srv/salt/modules/runners/foo.py`

Run `salt-run state.event pretty=True` and observe `ok whoami {'bob': b'nt-autorit\x84t\\system'}`

Run `grep -Rnw '/srv/salt/' -e 'ok whoami'` and observe
```
Binary file /srv/salt/modules/runners/__pycache__/foo.cpython-36.pyc matches
Binary file /srv/salt/modules/runners/__pycache__/flycheck_foo.cpython-36.pyc matches
```

Execute `rm /srv/salt/modules/runners/__pycache__/*`

Run `salt-run state.event pretty=True` and observe no `ok whoami`

### Workaround 

Execute `rm /srv/salt/modules/runners/__pycache__/*` after you change /srv/salt/modules/runners/*.py

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3002.7

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.25.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

```
</details>

**Comment by OrangeDog** [comment]
Does `salt-run fileserver.update`, `salt-run saltutil.sync_modules`, or restarting the service have any effect?

**Comment by dmurphy18** [comment]
@marbx Any information from trying @OrangeDog 's suggestion ?
Appears as if you delete the your file and expect the cache for your file to also to get deleted automatically, and Salt should automatically notice ?  I think this is similar to changing a minion's configuration file, you need to let Salt know to refresh and pick up the changes, or have a reactor / beacon to do that for you.

**Comment by marbx** [comment]
Resolved by remembering to delete` __pycache__/*`
