### ISSUE TITLE
[BUG] how to install file on windows minion

### ISSUE THREAD

**Issue by n8milk** [saltstack/salt#61000]
Hi. I'm JK who using saltstack API.

When I send http signal, it returns response.

test.bat
----------
```echo Hello World```

http signal
------------------
```
POST
{
    "client": "local",
    "tgt": "jk-02",
    "fun": "cmd.run",
    "arg": "test.bat"
}
```

response
-------------------
```
[
    "jk-02": "Hello World"
]
```

But if I execute exe file, there's no return. And endless waiting...

http signal
------------------
```
POST
{
    "client": "local",
    "tgt": "jk-02",
    "fun": "cmd.run",
    "arg": "visualstudiocode.exe /silent"
}
```

response
-----------------------
processing....

Is not possible to downloaded install file on windows minion?
What should I do? Please answer me. Thank you.

**Comment by OrangeDog** [comment]
Presumably because the command runs VisualStudio Code, which is an interactive GUI application. Salt will wait for the application to exit before returning.

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity.
