### ISSUE TITLE
[TECH DEBT][etcd v2-v3] sdb/etcd_db.py - ensure functional tests & v3 compatibility

### ISSUE THREAD

**Issue by waynew** [saltstack/salt#61036]
This is part of #60325 

It's not blocked on deciding which library to use. The process is:

- [x] - ensure that adequate functional tests exist for XXX
- [x] - when a library is picked, update this module to take advantage of the
  etcdv3 library (if needed)

With adequate functional tests, we can ensure that when we drop in a new
library, our existing API doesn't need to change.

**Comment by MKLeb** [comment]
Reopening because we still have to pick the v3 module we are going to use
