### ISSUE TITLE
[BUG] `utils/aws.py:assumed_creds()` attempts to update a dictionary while iterating on it

### ISSUE THREAD

**Issue by brianthelion** [saltstack/salt#61049]
https://github.com/saltstack/salt/blob/cc0abfe7176e57f2fabff45a3508f5680ed5dda4/salt/utils/aws.py#L189-L191

That code block wouldn't work even if `delete()` was a valid `dict` method.

**Comment by brianthelion** [comment]
@twangboy Bump? This is a clear bug.

**Comment by garethgreenaway** [comment]
@brianthelion Can you provide a Salt version report so we know what version of Salt you're seeing this error in?  Thanks!

**Comment by brianthelion** [comment]
@garethgreenaway Sorry, not using SaltStack anymore. The same code block is still preset today on [master](https://github.com/saltstack/salt/blob/master/salt/utils/aws.py#L189-L191). The bug should be clear from inspection of the code.

**Comment by MKLeb** [comment]
Fixed by https://github.com/saltstack/salt/pull/64392
