### ISSUE TITLE
Salt 3002 Upgrade Version

### ISSUE THREAD

**Issue by lorenzoquantyca** [saltstack/salt#61050]
We have Salt open installed on our infrastructure with version 3002.0 and we have some issues to solve.
The list of problems that we want to solve is the following:

**- Salt Master memory leak**
We have to restart the service of the Salt Master once a week to temporarily solve the problem.

**- Timeout on long running status**
When we execute state that running for more than 1 hour, that will be considered failed even if they are already running.

**- Schedule doesn't always start**
Sometimes the schedules skip their execution, without logging any error.

Do you have any suggestions about which version we have to install? We want to install a more stable version and fix the problems above.

Kind regards,
Lorenzo

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
           Salt: 3002
 
Dependency Versions:
           cffi: 1.14.5
       cherrypy: unknown
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.8.1
        libgit2: Not Installed
       M2Crypto: 0.33.0
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.6.2
   mysql-python: Not Installed
      pycparser: 2.20
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.6.8 (default, Apr  2 2020, 13:34:55)
   python-gnupg: Not Installed
         PyYAML: 3.11
          PyZMQ: 17.0.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.1.4
 
System Versions:
           dist: centos 7 Core
         locale: UTF-8
        machine: x86_64
        release: 3.10.0-1127.13.1.el7.x86_64
         system: Linux
        version: CentOS Linux 7 Core
```
</details>

**Comment by waynew** [comment]
This would be better sent to either the salt-users mailing list, or asked in IRC or on the community Slack.

The latest Salt release, 3004, should improve all of the problems. There is a known memory leak in the gitfs libraries, unfortunately there's not much we can do with that one, short of writing our own git module.

For the other issues, https://github.com/saltstack/salt/issues?q=is%3Aissue+is%3Aopen+schedule+label%3Abug and https://github.com/saltstack/salt/issues?q=is%3Aissue+is%3Aopen+timeout+long+label%3Abug+ may help find some issues that are what you're seeing. If you don't find any existing issues, then please go ahead and open a new issue.
