### ISSUE TITLE
[DOCS]   typo: ansible.playbook -> ansible.playbooks 

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#61085]
**Description**
ansible.playbook is wrong for annsiblegate in saltstack version 3004.1

salt 'ansiblehost'  ansible.playbooks  playbook=/srv/playbooks/play.yml

![image](https://user-images.githubusercontent.com/378638/138140531-c5b103de-daff-4605-b6f0-e9b1c7d6043a.png)

**Suggested Fix**
salt 'ansiblehost'  ansible.playbooks  playbook=/srv/playbooks/play.yml

**Type of documentation**
https://docs.saltproject.io/en/latest/ref/states/all/salt.states.ansiblegate.html

**Location or format of documentation**

https://docs.saltproject.io/en/latest/ref/states/all/salt.states.ansiblegate.html

**Additional context**

**Comment by waynew** [comment]
@tjyang would you be willing to open a PR to correct this?

**Comment by tjyang** [comment]
@waynew , sure I will do a PR.
