### ISSUE TITLE
[TECH DEBT] Add windows re-auth test to test suite.

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#61109]
Add windows re-auth test the test suite.

Make sure Linux master and Windows minion are connected and talking to each other.

Stop the Linux master and start the windows minion in debug mode:
It should just continue to restart the minion and attempt to re-authenticate. The process should not die in a 20 minutes time frame. 
Then restart the master and connection should resume.

**Comment by MKLeb** [comment]
Fixed by https://github.com/saltstack/salt/pull/63938
