### ISSUE TITLE
[TECH DEBT] Add newer master - older minion compability tests to the test suite

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#61102]
Add newer master and older minion tests to the test suite.

Need to test 3 versions back.
Use latest version on each branch

For example:

Previous 3004 minion with latest master
Latest 3003 minion with latest master
Latest 3002 minion with latest master
Latest 3001 minion with latest master

Make sure that they connect and talk to each other.

Of course the versions to test will change when we do newer releases, those are just examples, need to go 3 versions back.

**Comment by MKLeb** [comment]
This is fixed by `tests/pytests/scenarios/compat/test_with_versions.py`.  Right now it's a manual change for each release to change the tested versions, but once https://github.com/saltstack/salt/issues/62135 is solved, we can quickly generalize it.
