### ISSUE TITLE
[TECH DEBT] Add upgrade master and minion tests to the test suite.

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#61103]
Add tests to make sure the master and minion are updating to the newest salt version to the test suite.

Need to test 3 versions back.

Always use latest version on each branch.

For example:

Master:

Upgrade 3004.x to 3004.x
Upgrade 3003.x to 3004.x
Upgrade 3002.x to 3004.x
Upgrade 3001.x to 3004.x

Minion:

Upgrade 3004.x to 3004.x
Upgrade 3003.x to 3004.x
Upgrade 3002.x to 3004.x
Upgrade 3001.x to 3004.x

Windows Minion:

Upgrade 3004.x to 3004.x
Upgrade 3003.x to 3004.x
Upgrade 3002.x to 3004.x
Upgrade 3001.x to 3004.x

Also need to make sure the config files don't get overwritten when upgrading.

Of course the versions to test will change when we do newer releases, those are just examples, need to go 3 versions back.

**Comment by MKLeb** [comment]
We should also test upgrades and downgrades for (at least) the most recent minor version of the packages.
