### ISSUE TITLE
[BUG] pip.installed ignores failure due to wrongly specified bin_env path

### ISSUE THREAD

**Issue by eliasp** [saltstack/salt#61117]
**Description**
When using `pip.installed` and the defined path for `bin_env` is wrong (e.g. due to a typo), the state should fail - instead it succeeds even though `Comment` makes it clear what went wrong.

**Setup**
Reproduced the problem on Win10 and Ubuntu 20.04 using Salt 3004.
No special pre-requisites besides Salt itself are required.

Please be as specific as possible and give set-up details.

- [x] on-prem machine (Win10)
- [x] VM (WSL/Ubuntu 20.04)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Execute:
- Win10: `salt-call --local state.single pip.installed name='xkcd' bin_env="C:\Program Files\Python1234\Scripts\pip.exe"`
- Ubuntu 20.04: `salt-call --local state.single pip.installed name=xkcd bin_env=/usr/local/bin/python1234`

**Expected behavior**
- The state should fail (`Result: False`)
- The `salt-call` summary should show `Failed: 1`

**Versions Report**
<details><summary>salt --versions-report</summary>

```
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.0
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Sep 28 2021, 16:10:42)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-77-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Comment by dmurphy18** [comment]
Problem is due to https://github.com/saltstack/salt/commit/69e1d22c2aa42be15c57912b23449df19baed53a (7 years ago), changing ret["result"} to None when it had been False (see 9 years ago https://github.com/saltstack/salt/commit/9e232a3a5c9acd73cc2588ea8b97256a5adbdb0f by @terminalmage )

Will correct, cannot imagine why report None for result from an Exception which is reporting an Error

**Comment by dmurphy18** [comment]
Problem was probably introduced from the return codes of internal function _check_if _installed where result None means the command failed to run, see https://github.com/saltstack/salt/blob/a575896ef0c7fbfb4f90ed5d14bfba1e8b350178/salt/states/pip_state.py#L240-L270

However, the output from _check_if_installed is converted correctly to result False if None encountered, see https://github.com/saltstack/salt/blob/a575896ef0c7fbfb4f90ed5d14bfba1e8b350178/salt/states/pip_state.py#L845-L866

Exception should return ret["result"} = False.
