### ISSUE TITLE
[BUG] Salt state.apply hangs but can ping minion

### ISSUE THREAD

**Issue by jjedd97** [saltstack/salt#61127]
**Description**
On one of minions, a state is hanging indefinitely. This minion does not have the best connection, but I do see its return message, but the master does not seem to respond to it. The master continues to send find jobs, which keeps the state from timing out. 

**Setup**
Both master and minion are running 3003.3
This is the state that fails:
```yaml
"{% set teleport_version = "6.2.3" %}
install_teleport:
  pkg.installed:
    - sources:
      - teleport: https://get.gravitational.com/teleport_{{ teleport_version }}_amd64.deb"
``` 
 The minion is ubuntu 18.04
I have done restarts and not been able to resolve the issue

Please be as specific as possible and give set-up details.
The master is an ec2 instance on ubuntu 20.04 and the minion is a ubuntu 18.04 machine. 

  
**Steps to Reproduce the behavior**
Not sure this is reproducible as it only happens on one of the minions. 

**Expected behavior**
Minion passes or at least times out. 

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 
Master:
Salt Version:
          Salt: 3003.3
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.6.1
        Python: 3.8.10 (default, Sep 28 2021, 16:10:42)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.11.0-1017-aws
        system: Linux
       version: Ubuntu 20.04 focal

Minion:
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: 1.14.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: 4.4.4
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: Not Installed
        Python: 3.6.9 (default, Jan 26 2021, 15:33:00)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 bionic
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-29-generic
        system: Linux
       version: Ubuntu 18.04 bionic

**Additional context**
Here are some of the logs:
Minion:
 Starting a new job 20211025223255709918 with PID 728
[DEBUG   ] Could not LazyLoad direct_call.allow_missing_func: 'direct_call.allow_missing_func' is not available.
[DEBUG   ] LazyLoaded saltutil.find_job
[DEBUG   ] Minion return retry timer set to 6 seconds (randomized)
[INFO    ] Returning information for job: 20211025223255709918
[DEBUG   ] Initializing new AsyncZeroMQReqChannel for ('/etc/salt/pki/minion', 'Removed', 'tcp://removed', 'aes')
[DEBUG   ] Initializing new AsyncAuth for ('/etc/salt/pki/minion', 'Removed', 'tcp://removed')
[DEBUG   ] Connecting the Minion to the Master URI (for the return server): tcp://removed
[DEBUG   ] Trying to connect to: tcp://removed
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] minion return: {'success': True, 'return': {'pid': 31763, 'fun': 'state.apply', 'arg': ['teleport.installed'], 'tgt': 'removed', 'jid': '20211025223119867504', 'ret': '', 'tgt_type': 'glob', 'user': 'sudo_ubuntu'}, 'retcode': 0, 'jid': '20211025223255709918', 'fun': 'saltutil.find_job', 'fun_args': ['20211025223119867504']}
[DEBUG   ] Subprocess ProcessPayload-Job-20211025223255709918 cleaned up
[INFO    ] User sudo_ubuntu Executing command saltutil.find_job with jid 20211025223305772884
[DEBUG   ] Command details {'fun': 'saltutil.find_job', 'arg': ['20211025223119867504'], 'tgt': ['removed'], 'jid': '20211025223305772884', 'ret': '', 'tgt_type': 'list', 'user': 'sudo_ubuntu'}

Master event bus:
salt/job/20211026145820710718/ret/removedl	{
    "_stamp": "2021-10-26T14:58:22.666659",
    "cmd": "_return",
    "fun": "saltutil.find_job",
    "fun_args": [
        "20211026142048340531"
    ],
    "id": "removedl",
    "jid": "20211026145820710718",
    "retcode": 0,
    "return": {
        "arg": [
            "teleport.installed"
        ],
        "fun": "state.apply",
        "jid": "20211026142048340531",
        "pid": 20862,
        "ret": "",
        "tgt": "removed",
        "tgt_type": "glob",
        "user": "sudo_ubuntu"
    },
    "success": true
}
20211026145830892763	{
    "_stamp": "2021-10-26T14:58:30.892990",
    "minions": [
        "removedl"
    ]
}
salt/job/20211026145830892763/new	{
    "_stamp": "2021-10-26T14:58:30.893943",
    "arg": [
        "20211026142048340531"
    ],
    "fun": "saltutil.find_job",
    "jid": "20211026145830892763",
    "minions": [
        "removed"
    ],
    "missing": [],
    "tgt": [
        "removed"
    ],
    "tgt_type": "list",
    "user": "sudo_ubuntu"

**Comment by garethgreenaway** [comment]
@jjedd97 Thanks for the report.  This is definitely a weird issue.  Are you able to download the package manually on the EC2 instance?  I wonder if something is blocking the download or the installation of the package.

**Comment by jjedd97** [comment]
Hi @garethgreenaway I had looked some more at the minion, and it was failing to download the package in a reasonable amount of time as it has a limited lte connection. Unfortunately, this leads to a really long run time for the state as the failure to download took a few hours. The state also did not time out as the minion would report success.

**Comment by garethgreenaway** [comment]
Closing this due to age and the old version of Salt.
Can you retest this with the latest release of Salt 3006.2 and if this is still an issue, please open a new issue.
