### ISSUE TITLE
[BUG] Missing python-dateutil

### ISSUE THREAD

**Issue by tibetsam** [saltstack/salt#61147]
**Description**
python-dateutil was installed on minion but minion is still complaining about it.
2021-10-28 19:32:52,040 [salt.utils.schedule:1017][ERROR   ][10016] Missing python-dateutil. Ignoring job ic.restic.schedule.forget.
2021-10-28 19:32:52,040 [salt.utils.schedule:1017][ERROR   ][10016] Missing python-dateutil. Ignoring job ic.restic.schedule.forget.

/etc/salt/minion.d> python3
Python 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
'>>>' import dateutil.parser as dateutil_parser
'>>>'

And from the code, the error only comes with import error.

https://github.com/saltstack/salt/blob/master/salt/utils/schedule.py

if not _WHEN_SUPPORTED:
                data["_error"] = "Missing python-dateutil. Ignoring job {}.".format(
                    data["name"]
                )
if not _RANGE_SUPPORTED:
                data["_error"] = "Missing python-dateutil. Ignoring job {}.".format(
                    data["name"]
                )
try:
    import dateutil.parser as dateutil_parser
    _WHEN_SUPPORTED = True
    _RANGE_SUPPORTED = True
except ImportError:
    _WHEN_SUPPORTED = False
    _RANGE_SUPPORTED = False

**Setup**
ic.restic.schedule.forget:
  schedule.present:
    - function: restic.forget
    - job_args:
      - default
      - /backup
    - when: 1:00am
    - require:
      - ic.restic.schedule.backup
    - persist: True

Please be as specific as possible and give set-up details.

- [x ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
just apply the state

**Expected behavior**
No error message and job can run successfully 

**Screenshots**

**Versions Report**

4B6R363:~ # salt-minion -V
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: 5.0.3
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: sles 15.2 
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-24.86-default
        system: Linux
       version: SLES 15.2 
 
4B6R363:~ # 

**Additional context**

**Comment by OrangeDog** [comment]
You have probably installed it into a different location than salt is using.

How did you install both salt and the dependency?

**Comment by dmurphy18** [comment]
@tibetsam salt-minion depends on salt-common in Debian, and for Debian 10 if you examine the dependencies, you see that python3-dateutil is a dependency.

```root@tdeb10:/home/david# apt-cache depends salt-common
salt-common
  Depends: python3-apt
  Depends: python3-dateutil
  Depends: python3-jinja2
  Depends: python3-msgpack
  Depends: python3-pkg-resources
  Depends: python3-requests
  Depends: python3-yaml
  Depends: python3-systemd
  Depends: python3-psutil
  Depends: python3-distro
  Depends: python3-pycryptodome
  Depends: python3-zmq
  Depends: python3-markupsafe
  Depends: <python3:any>
    python3
  Breaks: python3-mako
  Recommends: lsb-release
  Recommends: python3-contextvars
  Recommends: python3-croniter
  Suggests: python3-pycurl
  Suggests: python3-twisted
root@tdeb10:/home/david#
```

You are using a container version of Debian 10, check if your image contains python3-dateutil, it may well be missing. The packaging and dependencies for Salt on Debian 10 are done for default OS versions, the container image used my be a minimal image which does not contain python3-dateutil.

**Comment by dmurphy18** [comment]
@tibetsam BTW going out to docker and getting a buster container, I find python3-dateutil available

```
david@david-laptop2:~$ docker run -it debian:buster
root@a02d2da1a54d:/# cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
root@a02d2da1a54d:/# apt update
Get:1 http://deb.debian.org/debian buster InRelease [122 kB]
Get:2 http://security.debian.org/debian-security buster/updates InRelease [65.4 kB]
Get:3 http://deb.debian.org/debian buster-updates InRelease [51.9 kB]
Get:4 http://security.debian.org/debian-security buster/updates/main amd64 Packages [308 kB]
Get:5 http://deb.debian.org/debian buster/main amd64 Packages [7906 kB]
Get:6 http://deb.debian.org/debian buster-updates/main amd64 Packages [15.2 kB]
Fetched 8469 kB in 3s (2614 kB/s)                         
Reading package lists... Done
Building dependency tree       
Reading state information... Done
1 package can be upgraded. Run 'apt list --upgradable' to see it.
root@a02d2da1a54d:/# apt-cache policy python3-dateutil
python3-dateutil:
  Installed: (none)
  Candidate: 2.7.3-3
  Version table:
     2.7.3-3 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
root@a02d2da1a54d:/# 
```

**Comment by tibetsam** [comment]
@dmurphy18 , thanks for your hint. I think it is also installed in my container.

root@salt-master-578cb9dcb8-8c9qp:/# apt-cache show salt-common
Package: salt-common
Source: salt
Version: 3003.3+ds-1
Architecture: all
Maintainer: Debian Salt Team <pkg-salt-team@lists.alioth.debian.org>
Installed-Size: 30512
Depends: python3-apt, python3-dateutil, python3-jinja2, python3-msgpack (>= 0.4), python3-pkg-resources, python3-requests, python3-yaml, python3-systemd, python3-psutil, python3-distro, python3-pycryptodome, python3-zmq (>= 17.0.0), python3-markupsafe, python3:any
Recommends: lsb-release, python3-contextvars, python3-croniter
Suggests: python3-pycurl, python3-twisted
Breaks: python3-mako (<< 0.7.0)
Homepage: http://saltstack.org/
Priority: optional
Section: admin
Filename: pool/main/s/salt/salt-common_3003.3+ds-1_all.deb
Size: 7136000
SHA256: 0b40a7c3abf94951e868913a7032d954500d494fc8b7b2c6032d0c1085374e10
SHA1: 5471a25c2bcf19c3b78f41f7fe32597d159f4ef2
MD5sum: b4955f205416860c10e5647de92b443a
Description: shared libraries that salt requires for all packages
Description-md5: aaa76a7bda4c75e02b81764c1dc6e91a

Package: salt-common
Source: salt
Version: 2018.3.4+dfsg1-6+deb10u2
Installed-Size: 23706
Maintainer: Debian Salt Team <pkg-salt-team@lists.alioth.debian.org>
Architecture: all
Depends: python3-apt, python3-dateutil, python3-jinja2, python3-msgpack, python3-pkg-resources, python3-psutil, python3-requests (>= 1.0.0), python3-tornado4 (>= 4.2) | python3-tornado (<< 5), python3-tornado4 (>= 4.2) | python3-tornado (>= 4.2), python3-yaml, python3:any
Recommends: lsb-release, python3-croniter
Suggests: python3-mako, salt-doc (= 2018.3.4+dfsg1-6+deb10u2)
Breaks: python3-mako (<< 0.7.0), salt-formula-ceilometer (<= 2016.12.1-1), salt-formula-cinder (<= 2016.12.1-1), salt-formula-glance (<= 2016.12.1-1), salt-formula-keystone (<= 2016.12.1-1), salt-formula-kubernetes (<= 2016.12.1-1)
Description: shared libraries that salt requires for all packages
Description-md5: aaa76a7bda4c75e02b81764c1dc6e91a
Homepage: http://saltstack.org/
Section: admin
Priority: optional
Filename: pool/main/s/salt/salt-common_2018.3.4+dfsg1-6+deb10u2_all.deb
Size: 3262296
MD5sum: 72732438a4ea77823e99fabeda954996
SHA256: ff0e6e13b6518d20cc8d17787cd8043fe1a7170eb0d4225d945a57b0de417911

root@salt-master-578cb9dcb8-8c9qp:/# apt-cache policy salt-common    
salt-common:
  Installed: 3003.3+ds-1
  Candidate: 3003.3+ds-1
  Version table:
 *** 3003.3+ds-1 500
        500 http://repo.saltproject.io/py3/debian/10/amd64/archive/3003.3 buster/main amd64 Packages
        100 /var/lib/dpkg/status
     2018.3.4+dfsg1-6+deb10u2 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        500 http://security.debian.org/debian-security buster/updates/main amd64 Packages
root@salt-master-578cb9dcb8-8c9qp:/# apt-cache policy python3-dateutil
python3-dateutil:
  Installed: 2.7.3-3
  Candidate: 2.7.3-3
  Version table:
 *** 2.7.3-3 500
        500 http://deb.debian.org/debian buster/main amd64 Packages
        100 /var/lib/dpkg/status
root@salt-master-578cb9dcb8-8c9qp:/#

**Comment by tibetsam** [comment]
@

> How did you install Salt, and how did you install `python-dateutil`?
> 
> They are probably in different environments.
to install minion:
zypper install salt-minion
to install dateutil, but anyway, i think dateutil is already installed by default before this state.
ic.install.pip-dateutil:
  pip.installed:
    - name: python-dateutil
    - require:
      - ic.system-pip.config.pip

**Comment by tibetsam** [comment]
> @tibetsam salt-minion depends on salt-common in Debian, and for Debian 10 if you examine the dependencies, you see that python3-dateutil is a dependency.
> 
> ```
> salt-common
>   Depends: python3-apt
>   Depends: python3-dateutil
>   Depends: python3-jinja2
>   Depends: python3-msgpack
>   Depends: python3-pkg-resources
>   Depends: python3-requests
>   Depends: python3-yaml
>   Depends: python3-systemd
>   Depends: python3-psutil
>   Depends: python3-distro
>   Depends: python3-pycryptodome
>   Depends: python3-zmq
>   Depends: python3-markupsafe
>   Depends: <python3:any>
>     python3
>   Breaks: python3-mako
>   Recommends: lsb-release
>   Recommends: python3-contextvars
>   Recommends: python3-croniter
>   Suggests: python3-pycurl
>   Suggests: python3-twisted
> root@tdeb10:/home/david#
> ```
> 
> You are using a container version of Debian 10, check if your image contains python3-dateutil, it may well be missing. The packaging and dependencies for Salt on Debian 10 are done for default OS versions, the container image used my be a minimal image which does not contain python3-dateutil.
> 
> If it is a minimal image, I would also check for other missing dependencies too. BTW:
> 
> ```
> root@tdeb10:/home/david# apt-cache depends salt-minion
> salt-minion
>   Depends: bsdmainutils
>   Depends: dctrl-tools
>   Depends: salt-common
>   Depends: <python3:any>
>     python3
>   Recommends: debconf-utils
>   Recommends: dmidecode
>   Suggests: python3-augeas
> ```

sorry @dmurphy18  i just realized i pasted salt-master version...here is minion version...will update is accordingly...
4B6R363:~ # salt-minion -V
Salt Version:
          Salt: 3002.2
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: 5.0.3
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.13 (default, Mar 10 2021, 18:30:35) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: sles 15.2 
        locale: UTF-8
       machine: x86_64
       release: 5.3.18-24.86-default
        system: Linux
       version: SLES 15.2 
 
4B6R363:~ #

**Comment by tibetsam** [comment]
short update:

the ERROR was gone after a minion restart, so i think python-dateutil is not loaded somehow, only after a restart, do you know how can we load it without a restart? 

another question is why this log is flooded every 1 second even non of my job is scheduled per second.

root@salt-master-578cb9dcb8-8c9qp:/srv/salt# salt 4B6R363 schedule.list                            
4B6R363:
    schedule:
      ic.restic.schedule.backup:
        args:
        - default
        - /backup
        enabled: true
        function: restic.backup
        jid_include: true
        maxrunning: 1
        name: ic.restic.schedule.backup
        seconds: 3600
      ic.restic.schedule.forget:
        args:
        - default
        enabled: true
        function: restic.forget
        jid_include: true
        kwargs:
          keepTag: swagger
        maxrunning: 1
        name: ic.restic.schedule.forget
        when: 1:00am
root@salt-master-578cb9dcb8-8c9qp:/srv/salt# 

2021-11-02 13:50:26,039 [salt.utils.schedule:1017][ERROR   ][10016] Missing python-dateutil. Ignoring job ic.restic.schedule.forget.
2021-11-02 13:50:27,040 [salt.utils.schedule:1017][ERROR   ][10016] Missing python-dateutil. Ignoring job ic.restic.schedule.forget.
2021-11-02 13:50:28,040 [salt.utils.schedule:1017][ERROR   ][10016] Missing python-dateutil. Ignoring job ic.restic.schedule.forget.
2021-11-02 13:50:29,040 [salt.utils.schedule:1017][ERROR   ][10016] Missing python-dateutil. Ignoring job ic.restic.schedule.forget.
2021-11-02 13:50:30,041 [salt.utils.schedule:1017][ERROR   ][10016] Missing python-dateutil. Ignoring job ic.restic.schedule.forget.
2021-11-02 13:50:31,039 [salt.utils.schedule:1017][ERROR   ][10016] Missing python-dateutil. Ignoring job ic.restic.schedule.forget.
2021-11-02 13:50:33,019 [salt.cli.daemons :91  ][INFO    ][5453] Starting up the Salt Minion
4B6R363:~ #

**Comment by dmurphy18** [comment]
@tibetsam With a regular Debian 10 machine (OS on bare metal or VirtualBox VM), the salt-minion is started with installation, unlike on Centos/RedHat where it does not automatically start.With a regular Debian 10 machine I have not seen a dependency not get found and utilized.  That is part of the APT packaging environment controlling this. Having a systemd restart of the service picked it up without any intervention from the salt-minion.

This leads me to wonder about the Kubernetes, Docker , container environment that you are using and how it is handling APT or systemd.  If Docker, wondering how you restarted the salt-minion given that while Docker has systemd, it is disabled by default, but have tested on Devuan so sure that /etc/init.d still works.

Logging flood is probably due to the ERROR in not finding dateutil, default is Errors and Warnings, and it falls into that camp.

Can you provide any information on the container used, if Docker, is it from DockerHub, such that Salt Project can duplicate the issue ?

**Comment by dmurphy18** [comment]
Just checked DockerHub's debian:buster container and 'ps' is missing, which is very surprising to me at least.  Hence wondering what else is missing from a default buster container for Docker  (10.10)
apt install procps installed ps in /bin/ps

Anyway see similar issue with starting the salt-minion due to no systemd, and /etc/init.d invoke-rc.d issue, from the end of install on a clean container
```
Setting up python3-pycryptodome (3.6.1-2+b1) ...
Setting up python3-croniter (0.3.24-2) ...
Setting up python3-yaml (3.13-2) ...
Setting up python3-chardet (3.0.4-3) ...
Setting up python3-requests (2.21.0-1) ...
Setting up salt-common (3004+ds-1) ...
Setting up salt-minion (3004+ds-1) ...
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
Processing triggers for libc-bin (2.28-10) ...
root@d0a59216eb16:/# l /bin/ps
ls: cannot access '/bin/ps': No such file or directory
root@d0a59216eb16:/# apt install procps
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  procps
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 259 kB of archives.
After this operation, 746 kB of additional disk space will be used.
Get:1 http://deb.debian.org/debian buster/main amd64 procps amd64 2:3.3.15-2 [259 kB]
Fetched 259 kB in 0s (1039 kB/s)
debconf: delaying package configuration, since apt-utils is not installed
Selecting previously unselected package procps.
(Reading database ... 14818 files and directories currently installed.)
Preparing to unpack .../procps_2%3a3.3.15-2_amd64.deb ...
Unpacking procps (2:3.3.15-2) ...
Setting up procps (2:3.3.15-2) ...
update-alternatives: using /usr/bin/w.procps to provide /usr/bin/w (w) in auto mode
root@d0a59216eb16:/# ps -ef | grep salt
root        4437       1  0 16:37 pts/0    00:00:00 grep salt
root@d0a59216eb16:/# command -v systemctl
root@d0a59216eb16:/# /etc/init.d/  
hwclock.sh   procps       salt-minion  sudo         
root@d0a59216eb16:/# /etc/init.d/salt-minion start
[ ok ] Starting salt minion control daemon: salt-minion.
root@d0a59216eb16:/# ps -ef | grep salt
root        4496       1  2 16:38 ?        00:00:00 /usr/bin/python3 /usr/bin/salt-minion -d
root        4528       1  0 16:38 pts/0    00:00:00 grep salt
root@d0a59216eb16:/# 
```

Normally you need to stop the salt-minion after an install to configure master and id at least in /etc/salt/minion and then start/restart the salt-minion.

Will discuss internally about a resolution.

**Comment by dmurphy18** [comment]
@tibetsam It is working as normal for a container without systemd support, the 
```
invoke-rc.d: could not determine current runlevel
invoke-rc.d: policy-rc.d denied execution of start.
```
is related to installing openssh-server

If on a container without systemD support, you need to start the salt-minion yourself.
However you may want to checkout the following links for better support of Docker with Salt

https://gitlab.com/saltstack/open/saltdocker
https://gitlab.com/saltstack/open/saltdocker/-/blob/master/cicd/docker/alpine.Dockerfile#L15

If this information is sufficient, please consider closing this issue.

**Comment by tibetsam** [comment]
> @tibetsam With a regular Debian 10 machine (OS on bare metal or VirtualBox VM), the salt-minion is started with installation, unlike on Centos/RedHat where it does not automatically start.With a regular Debian 10 machine I have not seen a dependency not get found and utilized. That is part of the APT packaging environment controlling this. Having a systemd restart of the service picked it up without any intervention from the salt-minion.
> 
> This leads me to wonder about the Kubernetes, Docker , container environment that you are using and how it is handling APT or systemd. If Docker, wondering how you restarted the salt-minion given that while Docker has systemd, it is disabled by default, but have tested on Devuan so sure that /etc/init.d still works.
> 
> Logging flood is probably due to the ERROR in not finding dateutil, default is Errors and Warnings, and it falls into that camp.
> 
> Can you provide any information on the container used, if Docker, is it from DockerHub, such that Salt Project can duplicate the issue ?

@dmurphy18 it is a bare metal machine with SLES, sorry that confusing you from the beginning, i though i replied to you before.

I knew logging flood is due to ERROR not finding dateutil, but why it is generating every 1 second? is it too much?

another question is why i can see dateuitl is installed with "salt-minion -V" command, but i still got error about dateutil is missing?

4B6R363:~ # salt-minion -V
Salt Version:
Salt: 3002.2

Dependency Versions:
cffi: 1.13.2
cherrypy: Not Installed
dateutil: 2.8.2

**Comment by dmurphy18** [comment]
@tibetsam You need to untick that Container box and state SLES bare-metal, otherwise people get the wrong idea and waste time looking in the wrong places.

salt-minion -V is reporting what version of dateutil  is found on the machine.

As to why SLES is not finding the correct python3-dateutil with zypper packages needs to be a question for SUSE and SLES team, since they package Salt Project for their platforms.

Don't know where I got the idea it was a Debian 10 container issue, esp since upon closer examination I see SLES 15.2 (probably the last bug I worked on still stuck in my head - sorry about that)

You need to contact SUSE with the issue as to what is happening with their packages.

**Comment by tibetsam** [comment]
sorry about the confusing....
thanks a lot, please go ahead and close this ticket

**Comment by lukasraska** [comment]
@tibetsam just FYI, the every-second log is because the scheduler actually runs every second and checks what should be executed... that should be configureable with https://docs.saltproject.io/en/latest/ref/configuration/minion.html#loop-interval

As to why running salt-minion doesn't load newly installed package - because it tries to load it at the start (https://github.com/saltstack/salt/blob/master/salt/utils/schedule.py#L48) and if that fails, it just marks python-dateutil is not available. I guess it would be nice enhancement to allow some kind of dynamic reload, or at least log it with debug level / just once

**Comment by dmurphy18** [comment]
Closing as per @tibetsam comments

**Comment by tibetsam** [comment]
> @tibetsam just FYI, the every-second log is because the scheduler actually runs every second and checks what should be executed... that should be configurable with https://docs.saltproject.io/en/latest/ref/configuration/minion.html#loop-interval
> 
> As to why running salt-minion doesn't load newly installed package - because it tries to load it at the start (https://github.com/saltstack/salt/blob/master/salt/utils/schedule.py#L48) and if that fails, it just marks python-dateutil is not available. I guess it would be nice enhancement to allow some kind of dynamic reload, or at least log it with debug level / just once

@lukasraska  it helped a lot.  after checking loop-interval, i found schedule is called periodically with tornado.ioloop and the interval is hardcoded, so i don't think changing loop-interval will help on every-second log problem.

            self.add_periodic_callback("schedule", handle_schedule)

    def add_periodic_callback(self, name, method, interval=1):
        """
        Add a periodic callback to the event loop and call its start method.
        If a callback by the given name exists this method returns False
        """
        if name in self.periodic_callbacks:
            return False
        self.periodic_callbacks[name] = salt.ext.tornado.ioloop.PeriodicCallback(
            method,
            interval * 1000,
        )
        self.periodic_callbacks[name].start()
        return True 

it will be great if we can support dynamic reload, or even manual reload from CLI.

**Comment by dmurphy18** [comment]
@tibetsam 
```
it will be great if we can support dynamic reload, or even manual reload from CLI.
```
Am I missing something, but isn't **systemctl restart salt-minion** not manual reload from CLI, or it's /etc/init.d equivalent

**Comment by tibetsam** [comment]
> @tibetsam
> 
> ```
> it will be great if we can support dynamic reload, or even manual reload from CLI.
> ```
> 
> Am I missing something, but isn't **systemctl restart salt-minion** not manual reload from CLI, or it's /etc/init.d equivalent

@dmurphy18 sorry,  i'm reload in dynamic module reload context...something like 'salt reload module', not reload salt daemon itself.
