### ISSUE TITLE
[BUG] salt-run runner module exit code is 0 when exception raised

### ISSUE THREAD

**Issue by TeddyAndrieux** [saltstack/salt#61173]
**Description**

If I have a runner module that raises an exception the exit code of the salt-run command is still 0

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

A really simple test using a built-in runner

```console
$ salt-run error.error name="Exception" message="This is an error."
Exception occurred in runner error.error: Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/client/mixins.py", line 390, in low
    data["return"] = func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/salt/runners/error.py", line 29, in error
    salt.utils.error.raise_error(name=name, message=message)
  File "/usr/lib/python3.6/site-packages/salt/utils/error.py", line 33, in raise_error
    raise ex(message)
Exception: This is an error.
$ echo $?
0
```

**Expected behavior**

Exit code not equal to 0 when the runner module raises an exception

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
salt-run 3004
```
</details>

**Additional context**

The only way I found to have a non-zero exit code for our custom runner is to return a dict with `retcode` set to non-zero

**Comment by TeddyAndrieux** [comment]
NOTE: Just found that we have the exact same issue with the state `salt.runner` that succeeds even if the function raises something.

And the only way to have a result False for this state is to return a dict with `success` set to `False`

**Comment by whytewolf** [comment]
closing since #64479 and #64545 are merged
