### ISSUE TITLE
[FEATURE REQUEST] yamllint module/utils

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#61182]
**Is your feature request related to a problem? Please describe.**
in trying to think of how to handle https://github.com/saltstack/salt/issues/802 I figure the first step would be getting linters into salt so that we can utilize them in more places. the first one being yamllint

**Describe the solution you'd like**
a yamllint utils that can be used in more places, as well as a yaml.lint module.function that can be used to validating states YAML. 

**Describe alternatives you've considered**
adding a lot of linters instead of adding them slowly over time.

**Additional context**
one thing that everyone has complained about for a long time is being able to troubleshoot different issues in salt. most of which come down to rendering issues. 

This is only the first step in a long chain of additions to bring more troubleshooting tools into salt.

**Comment by ITJamie** [comment]
+1 on this
I had a user accidentally modify the following
```
  'hostname':i
    - some.sls.path
```
they added a charter after the hostname key in the top file. 
this was actually hard to track down
salt-lint saw no issue with this.
its obviously invalid yaml, but salt-lint was fine with it.
salt minions and master obviously wernt happy. but debug lines on both did not point to the specific line in the pillar top file with the issue. this was the output from any pillar or state command. pretty useless.
```
    ----------
    _errors:
        - Rendering Primary Top file failed, render error:
          could not find expected ':'
```

**Comment by whytewolf** [comment]
this was implemented with https://github.com/saltstack/salt/pull/61183
