### ISSUE TITLE
[BUG] salt-cloud > proxmox driver > list-locations (func avail_locations()) not honoring node state

### ISSUE THREAD

**Issue by idncsk** [saltstack/salt#61215]
Hi,

This is the first time I tried salt + first time I looked at some python code, fix may not be appropriate nor written correctly

**Description**
The **--list-locations** option / avail_locations() on the proxmox driver does not honor cluster node states

This may not be a real issue per-se, it may be perfectly valid to return all cluster nodes even if status of a node is not online.. The main problem so far was that **avail_images** function is using  **for host_name, host_details in avail_locations().items():** internally (may be used in the same manner in other places). If one of the nodes is down for maintenance, query will fail

A quick&dirty fix was to add
```
# Return a list of the hypervisors (nodes) which this Proxmox PVE machine manages
    for node in nodes:
        name = node["node"]
        **if node["status"] == "online":**
            ret[name] = node
```
in avail_locations() but guess this should actually be moved to avail_images()
The avail_images function does not properly handle/support non-standard image locations (if your cluster hosts images on some nw share fe) - hence will be part of a separate bug/feature-request anyway

**Comment by waynew** [comment]
It seems like it would be more correct for `avail_images` to filter out where `host_details['status'] != 'online'`.

We welcome PRs - just check the above link for the Salt's Contributor Guide for getting started.

**Comment by mthibaut** [comment]
I agree with waynew and will create a PR for this.
