### ISSUE TITLE
[BUG] regressions in mysql_cache module

### ISSUE THREAD

**Issue by tkwilliams** [saltstack/salt#61222]
Two recent regressions in the mysql_cache module have broken it fairly significantly.  One is a generic function argument ordering bug which breaks the module globally, while the other only manifests when using PyMySQL (instead of MySQLdb) as the db connector.

I can't seem to push PRs anymore, so here's a tiny patch instead :)
```
index 87ad78eade..7f01cc2473 100644
--- a/salt/cache/mysql_cache.py
+++ b/salt/cache/mysql_cache.py
@@ -90,7 +90,7 @@ def __virtual__():
     return bool(MySQLdb), "No python mysql client installed." if MySQLdb is None else ""


-def run_query(conn, query, retries=3, args=None):
+def run_query(conn, query, args=None, retries=3):
     """
     Get a cursor and run a query. Reconnect up to `retries` times if
     needed.
@@ -203,7 +203,6 @@ def store(bank, key, data):
     query = "REPLACE INTO {} (bank, etcd_key, data) values(%s,%s,%s)".format(
         __context__["mysql_table_name"]
     )
-    query = salt.utils.stringutils.to_bytes(query)
     args = (bank, key, data)

     cur, cnt = run_query(__context__.get("mysql_client"), query, args)
```

**Comment by tkwilliams** [comment]
@sagetherage - not sure if calling to_bytes() with surrogatepass is an acceptable choice, but it solved the immediate problem for me, and I can't see any major downside to it off the top of my head.

**Comment by tkwilliams** [comment]
@waynew @terminalimage @sagetherage - please note that the current codebase (as of 3004.1, which is what AWS Linux has RPMs of in their repos) is ENTIRELY, 100% broken WRT mysql_cache and needs the above patch to work at all, so this bug is a total showstopper for anyone using the MySQL minion cache backend, so I'd recommend getting this fix in sooner rather than later...

**Comment by tkwilliams** [comment]
@rallytime @sagetherage @waynew - I believe this should be classified as "high priority", given that the mysql cache module is 100% broken in 3004.1

**Comment by OrangeDog** [comment]
There is no 3004.1. Latest version is 3004.0.

**Comment by tkwilliams** [comment]
My bad - Amazon versioned their RPM as `3004-1` and I unthinkingly transcribed it as `3004.1` :)  I've verified the actual RPM is built from version`3004.0`

**Comment by tkwilliams** [comment]
Corrected patch
```diff --git a/salt/cache/mysql_cache.py b/salt/cache/mysql_cache.py
index 87ad78eade..7f01cc2473 100644
--- a/salt/cache/mysql_cache.py
+++ b/salt/cache/mysql_cache.py
@@ -90,7 +90,7 @@ def __virtual__():
     return bool(MySQLdb), "No python mysql client installed." if MySQLdb is None else ""


-def run_query(conn, query, retries=3, args=None):
+def run_query(conn, query, args=None, retries=3):
     """
     Get a cursor and run a query. Reconnect up to `retries` times if
     needed.
@@ -203,7 +203,6 @@ def store(bank, key, data):
     query = "REPLACE INTO {} (bank, etcd_key, data) values(%s,%s,%s)".format(
         __context__["mysql_table_name"]
     )
-    query = salt.utils.stringutils.to_bytes(query)
     args = (bank, key, data)

     cur, cnt = run_query(__context__.get("mysql_client"), query, args)```

The previous version assumed that `query = salt.utils.stringutils.to_bytes(query)` even BELONGED in the original version, but this assumption was wrong - NONE of the other defined methods (e.g. `fetch()`, `ls()`, `_init_client()`, etc) force a conversion to bytes, so I can't see why this one does so, and in fact removing it makes for a much cleaner "pass it through for the mysql DBI implementation to handle" approach.
