### ISSUE TITLE
[Docs] Documentation for runner.manage indicates subset is CIDR mask, when it's actually list of minion IDs

### ISSUE THREAD

**Issue by jheiselman** [saltstack/salt#61226]
**Description**
The documentation for the runner.manage module is incorrect. For several functions, it indicates that they can take a subset argument and that the value is a CIDR range to filter the minions by IP address. This, however, is not true as the value is passed verbatim to utils.minions where it is used as a list and compared against a list of minion IDs. At no point in time is the IP address evaluated.

**Setup**
On-prem salt master and minions. Currently demonstrated with version 3002.7 and 3003 and it's clearly incorrect in the code here on github in the current master branch.

Please be as specific as possible and give set-up details.

  
**Steps to Reproduce the behavior**
```
salt 'testhost.example.com' network.subnets

testhost.example.com:
    - 172.24.0.0/19

# salt-run manage.list_state subset='["172.24.0.0/19"]'
# salt-run manage.list_state subset='["testhost.example.com"]'
    - testhost.example.com
```

**Expected behavior**
The list_state and list_not_state functions should properly accept a CIDR mask or the documentation should be updated to reflect that subset is a list of minion IDs.

**Screenshots**
N/A

**Versions Report**
This discrepancy exists in the current code found at https://github.com/saltstack/salt/blob/master/salt/runners/manage.py#L217 which is where the documentation is taken from as well.

**Additional context**

**Comment by whytewolf** [comment]
closing with the merge of https://github.com/saltstack/salt/pull/64975
