### ISSUE TITLE
[BUG] Available memory decreases and swaps, mostly salt-master 3003.3

### ISSUE THREAD

**Issue by marbx** [saltstack/salt#61231]
**Description**
Migrated to new VM and upgraded to 3003.3 at the same time.

![image](https://user-images.githubusercontent.com/8489107/141467236-bba62600-39c2-4992-95b5-0ede54d0ef5c.png)

Below table is the pivoted output of 

    for file in /proc/*/status ; do awk '/VmSwap|Name/{printf $2 " " $3}END{ print ""}' $file; done | sort -k 2 -n -r | head -n 60

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/d3a5ef/AppData/Local/Temp/1/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/d3a5ef/AppData/Local/Temp/1/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">

process | kB
-- | --
salt-master | 191144
oacore | 48352
hpsensor | 48296
perfd | 48260
bash | 5840
ovcd | 3152
redis-server | 3100
systemd-journal | 2628
qualys-cloud-ag | 2472
httpd | 2352
ovconfd | 1292
zabbix_agentd | 1212
bpcd | 952
vnetd | 792
ovbbccb | 588
salt-run | 356
sendmail | 196
perfalarm | 156
python3 | 132
rsyslogd | 128
sh | 128
screen | 112
midaemon | 28
systemd | 28
ttd | 24
auditd | 4
su | 4

</body>

</html>

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Mar 18 2021, 08:58:41)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 8.3 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-305.10.2.el8_4.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.3 Ootpa
```
</details>

**Additional context**

**Comment by lukasraska** [comment]
200MB in swap for salt-master process is not probably any specific issue - it could mean it just requests memory allocations / doesn't use that memory much and OS just decided to swap it

Is there anything in master logs? What is the process that utilizes the most RAM?

**Comment by marbx** [comment]
Nothing in master logs that wasn't in the master log on the previous VM.

4 salt-master processes use 2.5, 1.4, 1.4 and 1.4 GB of RAM (8GB RAM avail) 

![image](https://user-images.githubusercontent.com/8489107/141496619-ef0dd5be-91c7-4d94-902e-7900e8122473.png)

`dnf install python-setproctitle` does not work. I only have EPEL.

**Comment by marbx** [comment]
I would like to know if the process which consumes the most RAM is a runner (on the salt-master).

Reading this, is it?
```
ls -l /proc/3377946/fd
total 0
lr-x------ 1 root root 64 Nov 12 17:12 0 -> /dev/null
lrwx------ 1 root root 64 Nov 12 17:12 1 -> 'socket:[111952137]'
lr-x------ 1 root root 64 Nov 12 17:12 10 -> /dev/null
l-wx------ 1 root root 64 Nov 12 17:12 11 -> 'pipe:[111951748]'
lrwx------ 1 root root 64 Nov 12 17:12 12 -> 'anon_inode:[eventpoll]'
lr-x------ 1 root root 64 Nov 12 17:12 13 -> 'pipe:[111952167]'
l-wx------ 1 root root 64 Nov 12 17:12 14 -> 'pipe:[111952167]'
lrwx------ 1 root root 64 Nov 12 17:12 15 -> 'socket:[111952168]'
lrwx------ 1 root root 64 Nov 12 17:12 16 -> 'socket:[111952170]'
lrwx------ 1 root root 64 Nov 12 17:12 17 -> 'socket:[111952193]'
lrwx------ 1 root root 64 Nov 12 17:12 18 -> 'socket:[111952333]'
lrwx------ 1 root root 64 Nov 12 17:12 19 -> 'socket:[111956117]'
lrwx------ 1 root root 64 Nov 12 17:12 2 -> 'socket:[111952137]'
lrwx------ 1 root root 64 Nov 12 17:12 20 -> 'socket:[111956121]'
lrwx------ 1 root root 64 Nov 12 17:12 21 -> 'socket:[111956233]'
lrwx------ 1 root root 64 Nov 12 17:12 22 -> 'socket:[111957909]'
lrwx------ 1 root root 64 Nov 12 17:12 23 -> 'socket:[111975110]'
lrwx------ 1 root root 64 Nov 12 17:12 24 -> 'socket:[111988879]'
lrwx------ 1 root root 64 Nov 12 17:12 25 -> 'socket:[111990036]'
lrwx------ 1 root root 64 Nov 12 17:12 26 -> 'socket:[112000727]'
lrwx------ 1 root root 64 Nov 12 17:12 27 -> 'socket:[111999495]'
lrwx------ 1 root root 64 Nov 12 17:12 29 -> 'socket:[112021682]'
lr-x------ 1 root root 64 Nov 12 17:12 3 -> 'pipe:[111952155]'
lrwx------ 1 root root 64 Nov 12 17:12 30 -> 'socket:[112021181]'
lrwx------ 1 root root 64 Nov 12 17:12 31 -> 'socket:[112024496]'
lrwx------ 1 root root 64 Nov 12 17:12 32 -> 'socket:[130886658]'
l-wx------ 1 root root 64 Nov 12 17:12 4 -> 'pipe:[111952155]'
lr-x------ 1 root root 64 Nov 12 17:12 5 -> 'pipe:[111952159]'
l-wx------ 1 root root 64 Nov 12 17:12 6 -> /var/log/salt/master
lrwx------ 1 root root 64 Nov 12 17:12 7 -> '/tmp/pymp-r45ycf2_/pym-3377931-cdeb_yoz (deleted)'
lrwx------ 1 root root 64 Nov 12 17:12 8 -> '/tmp/pymp-r45ycf2_/pym-3377931-cdeb_yoz (deleted)'
lr-x------ 1 root root 64 Nov 12 17:12 9 -> 'pipe:[111951742]'
 ```

**Comment by lukasraska** [comment]
Try `dnf install python3-setproctitle` as RHEL 8 is using Python 3 by default and Salt 3003 is Python 3 only (the package should be in EPEL). Don't forget to restart the salt-master process for setproctitle to take effect.

Also can you share your master config, in case something is visible from there?

**Comment by max-arnold** [comment]
Can you try upgrading the master to 3004? It has a couple of memory leak fixes

**Comment by marbx** [comment]
Closing till a better understanding
