### ISSUE TITLE
[BUG] prune_rich_rules - state is not working as expected

### ISSUE THREAD

**Issue by saeedgenmills** [saltstack/salt#61235]
**Description**

**Setup**

Nov 15 13:29:39 server1 firewalld[13189]: WARNING: ALREADY_ENABLED: rule family="ipv4" source address="172.16.0.0/12" port protocol="tcp" port="22" accept
Nov 15 13:29:40 server1 firewalld[13189]: WARNING: ALREADY_ENABLED: rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="22" accept
Nov 15 13:29:40 server1 firewalld[13189]: WARNING: ALREADY_ENABLED: rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="22" accept

(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

drop:
  firewalld.present:
    - name: drop
    - default: True
    - prune_rich_rules: False   # If True, remove all but the specified rich rules from the zone.
    - prune_services: True      # If True, remove all but the specified services from the zone.
    - prune_ports: True         # If True, remove all but the specified ports from the zone.
    - rich_rules:
      - rule family="ipv4" source address="10.0.0.0/8" port protocol="tcp" port="22" accept
      - rule family="ipv4" source address="172.16.0.0/12" port protocol="tcp" port="22" accept
      - rule family="ipv4" source address="192.168.0.0/16" port protocol="tcp" port="22" accept

This code try to add rich_rule every time when we try state.apply of salt client. 

We tried to use prune_rich_rules: True option, however it remove rich rules and send run it again add rule. In short rules are getting removed every alternate run.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by frogunder** [comment]
@saeedgenmills  What version of salt are you seeing this on?

Can you run `salt --versions-report` and paste the output?

**Comment by saeedgenmills** [comment]
Salt Version:
          Salt: 3003.2
 
Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 4.0.1
     gitpython: 3.0.9
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug 12 2021, 07:06:15)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: 3.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: rhel 8.4 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-305.19.1.el8_4.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.4 Ootpa

**Comment by defaultUser0816** [comment]
Hi, i am struggeling with the same behavior in the firewalld module. Every second run the prune_rich_rules parameter works not like excepted. The pruning for services and sources are fine. Maybe the bug is in the execution module that requesting the rich rules that are currently set cause they were mixed with the rich rules that are going to be set. It is wired that the code for set and prune services and sources is exactly the same like the code that set and prune the rich rules. I tried a lot of things to go around this bug. Without a working rich rule pruning the firewalld module is not really good in complex firewall enviroments.

**Comment by Xaraxia** [comment]
Adding to this, rich_rules needs to be parsed. whytewolf (SaltStack slack) asked me to put in a feature request, but it directly relates to this bug. If the rich_rules were being parsed, this would work.

(The pruning needs to work in an idempotent fashion as per defaultUser0816's comment, but that's technically a different issue.)

**Comment by awerner** [comment]
Instead of parsing the rich_rules, it is possible to use `firewall-cmd --query-rich-rule` to check if a rich rule already exists. This also takes account of the different ordering of fields that causes the issues right now.

```bash
$ firewall-cmd --list-rich-rules
rule service name="snmp" accept
rule family="ipv4" source address="0.0.0.0/0" port port="666" protocol="tcp" accept
rule family="ipv4" source address="0.0.0.0/0" port port="667" protocol="tcp" accept
$ firewall-cmd --query-rich-rule='rule family="ipv4" source address="0.0.0.0/0" port protocol="tcp" port="666" accept'
yes
$ firewall-cmd --query-rich-rule='rule family="ipv4" source address="0.0.0.0/0" port protocol="tcp" port="668" accept'
no
```

**Comment by Xaraxia** [comment]
That works for a few rules, but making system calls for a few dozen rules is not efficient.
