### ISSUE TITLE
[FEATURE REQUEST] Node Label management in Salt Cloud

### ISSUE THREAD

**Issue by corey-hammerton** [saltstack/salt#61245]
**Is your feature request related to a problem? Please describe.**
I would like to request the ability to add labels to nodes provisioned by Salt Cloud (Node Labels)

**Describe the solution you'd like**
The following code block is what I would like to be made available to Salt Cloud profile configurations

```
labels:
  key: value
```

**Describe alternatives you've considered**
N/A

**Additional context**
Google Cloud is my primary baseline: https://cloud.google.com/compute/docs/labeling-resources

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by sentient-glare** [comment]
Going to start taking a look at this issue.

**Comment by sentient-glare** [comment]
MR: https://github.com/saltstack/salt/pull/62046
