### ISSUE TITLE
[BUG] The returned result is bound to the wrong jid

### ISSUE THREAD

**Issue by xinlng** [saltstack/salt#61263]
**Description**
![image](https://user-images.githubusercontent.com/74448156/142590574-f6ae89a1-ec6b-40a2-94e0-ea63b70d1eb3.png)
![image](https://user-images.githubusercontent.com/74448156/142590654-7d95dcec-b7b0-43e3-9a08-66d50f09369b.png)

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by garethgreenaway** [comment]
@xinlng Thanks for the report.  Can you please provide that configurations for both the Salt master and the Salt minion?  Thanks!

**Comment by garethgreenaway** [comment]
Closing this out due to lack of activity, if the issue persists please open a new issue.
