### ISSUE TITLE
[BUG] First-time dsc.compile_config in win_dsc.py fails

### ISSUE THREAD

**Issue by bjoernf73** [saltstack/salt#61261]
**Description**
The first time a dsc.compile_config is run on a fresh install, it produces two files;
1. \<target\>.mof
1. \<target\>.meta.mof  

Properties from both of these files are returned as a `list` from the command
```
cmd.append(
        "| Select-Object -Property FullName, Extension, Exists, "
        '@{Name="LastWriteTime";Expression={Get-Date ($_.LastWriteTime) '
        "-Format g}}"
    )
cmd = " ".join(cmd)
ret = _pshell(cmd, cwd)
if ret:
        # Script compiled, return results
        if ret.get("Exists"):
```

This is from the minion log, where you see that both a `localhost.mof` and a `localhost.meta.mof` is returned:
```
2021-11-18 18:54:42,885 [salt.loaded.int.module.win_dsc:91  ][INFO    ][8024] DSC: Returning "[{'FullName': 'C:\\DryDSCConfiguration\\localhost.mof', 'Extension': '.mof', 'Exists': True, 'LastWriteTime': '18.11.2021 18:54'}, {'FullName': 'C:\\DryDSCConfiguration\\localhost.meta.mof', 'Extension': '.mof', 'Exists': True, 'LastWriteTime': '18.11.2021 18:54'}]"
```

Therefore, when `dsc.compile_config` does the following: 
```
if ret:
        # Script compiled, return results
        if ret.get("Exists"):
            log.info("DSC: Compile Config: %s", ret)
            return ret
```
the following error is returned: 
```
AttributeError: 'list' object has no attribute 'get'
```

Note that on subsequent compiles, only a .mof is produced . 

**Setup**

Please be as specific as possible and give set-up details.

- [ x ] on-prem machine
- [ x] VM vCenter
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Run a dsc.compile_config on a fresh install of windows, or a windows machine on which a dsc compilation has not been performed

**Expected behavior**
The PowerShell command that produces the return value should filter on the .mof file, so that the .meta.mof is filtered out.  
![image](https://user-images.githubusercontent.com/46068634/142504665-5858b40a-c4a1-4f71-b31e-7ff0af713e82.png)

This is from win_dsc.py: 
![image](https://user-images.githubusercontent.com/46068634/142505034-be907196-f400-4f04-ad9c-a2a8d89e4e9e.png)

This is from the minion log. I Added "ret info" to see for myself what was going on: 
![image](https://user-images.githubusercontent.com/46068634/142505589-9b14c488-6e99-4658-a48a-65a61225315a.png)

**Versions Report**
Salt Version:
Salt: 3004

Dependency Versions:
cffi: Not Installed
cherrypy: Not Installed
dateutil: 2.7.3
docker-py: Not Installed
gitdb: 2.0.6
gitpython: 3.0.7
Jinja2: 2.10.1
libgit2: 0.28.3
M2Crypto: Not Installed
Mako: Not Installed
msgpack: 0.6.2
msgpack-pure: Not Installed
mysql-python: Not Installed
pycparser: Not Installed
pycrypto: 2.6.1
pycryptodome: 3.6.1
pygit2: 1.0.3
Python: 3.8.10 (default, Sep 28 2021, 16:10:42)
python-gnupg: 0.4.5
PyYAML: 5.3.1
PyZMQ: 18.1.1
smmap: 2.0.5
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.3.2

System Versions:
dist: ubuntu 20.04 focal
locale: utf-8
machine: x86_64
release: 5.4.0-90-generic
system: Linux
version: Ubuntu 20.04 focal

```
PASTE HERE
```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
@bjoernf73 Need the versions report filled before any progress can be made on this issue. Need to at least know the version of Salt and the platform it is running on, versions-report provides this information.

**Comment by bjoernf73** [comment]
What is `versions-report`?
```
salt versions-report
```
fails.

**Comment by bjoernf73** [comment]
root@sm-wan-p:/home/bjoernf@BHF.LOCAL# salt 'dc-s*' versions-report
dc-s5-d:
    'versions-report' is not available.
ERROR: Minions returned with non-zero exit code

**Comment by bjoernf73** [comment]
root@sm-wan-p:/home/bjoernf@BHF.LOCAL# salt --versions-report
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.10 (default, Sep 28 2021, 16:10:42)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-90-generic
        system: Linux
       version: Ubuntu 20.04 focal

**Comment by bjoernf73** [comment]
Version updated in issue above.

**Comment by bjoernf73** [comment]
Keep in mind that everything works - but the compile-parts returns an array - even though compilation of mof works.

**Comment by bjoernf73** [comment]
> @bjoernf73 Need the versions report filled before any progress can be made on this issue. Need to at least know the version of Salt and the platform it is running on, versions-report provides this information.

@dmurphy18 Please advise me if there is still some info missing in this - note also that the PR #61268 fixes this.

**Comment by dmurphy18** [comment]
@twangboy sent your way since Windows

**Comment by twangboy** [comment]
I was unable to reproduce this specific scenario. Is there something that we can delete to simulate a brand new machine that has never had DSC run on it? A way to reset DSC to defaults?

**Comment by twangboy** [comment]
I was able to produce it by adding LocalConfigurationManager settings to the dsc definition.
