### ISSUE TITLE
[TECH DEBT] remove get_event's transport argument

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#61275]
`salt.utils.event.get_event` takes a `transport` argument that never gets used. Remove this argument and make sure it's not being passed in anywhere.

**Comment by MKLeb** [comment]
@dwoz Will look into this next week!

**Comment by MKLeb** [comment]
A few questions...

1. Does this require some sort of deprecation notice?  I have seen uses of this method outside of salt (eg. salt extensions) that use the transport kwarg in this method.
2. What kind of tests would be relevant for this?
