### ISSUE TITLE
[FEATURE REQUEST] Use ETag in Salt Fileclient for HTTP sources

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#61270]
For any states which can provide a `http://` or `https://` source file, the file is always downloaded and cached on the minion before a determination can be made whether the file has changed. For large files, this can introduce long wait times in state runs.

**Describe the solution you'd like**
Ideally, the minion would try to perform a HEAD on the file to get the ETag and compare that to the last cached file if present. If the ETag differs, the file would then be downloaded. Otherwise, the file client would use the cached copy.

**Describe alternatives you've considered**
/shrug

**Additional context**
This feature might warrant a gate option in the minion config since it'll fundamentally change the operation of remote web sources for multiple states.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by OrangeDog** [comment]
A extra `HEAD` request is unnecessary. Use the `If-None-Match` header.
