### ISSUE TITLE
[FEATURE REQUEST] Salt Minion should cache ReqChannels.

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#61274]
**Is your feature request related to a problem? Please describe.**

Looks like there may be a bottleneck in minion.py: send_req_sync() and minion.py:send_req_async() below, where we are re-creating channels (instead of caching them). At scale (about 5K minions), this causes a lot of heavy channel creation operations when minions respond and the delay is noticeable.

I've only tested with rabbitmq, but the same issue may exist for zeromq.

**Describe the solution you'd like**

If possible cache a single request channel for each minion.

**Comment by dmurphy18** [comment]
getting addressed in PR https://github.com/saltstack/salt/pull/61468
