### ISSUE TITLE
[BUG] timezone.system fails on Archlinux if the path /etc/localtime is missing as it cannot determine the current localtime beforehand

### ISSUE THREAD

**Issue by ipaqmaster** [saltstack/salt#61296]
**Description**

Using a timezone.system state on Archlinux fails with `Unable to compare desired timezone 'myCountry/myCity' to system timezone: Failed to read /etc/localtime to determine current timezone: No such file or directory`

This is similar to what used to happen on FreeBSD in https://github.com/saltstack/salt/issues/44083 however that was patched back in 2017, as referenced in that issue.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

This is a kind of issue which will happen on any Archlinux install in any of these above environments.
  
**Steps to Reproduce the behavior**

1. Make a salt state with the timezone.system state while /etc/localtime does not exist
2. Run that state
3. Receive failed state with comment: `Unable to compare desired timezone 'myCountry/myCity' to system timezone: Failed to read /etc/localtime to determine current timezone: No such file or directory`

**Expected behavior**

I was hoping it would just create the symlink and move on.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.9.7 (default, Oct 10 2021, 15:13:22)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.2.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: arch  
        locale: utf-8
       machine: x86_64
       release: 5.15.5-arch1-1
        system: Linux
       version: Arch Linux  
```
</details>

**Additional context**

Not entirely world ending, I've added a jinja if in my Salt to just run a fallback state to create a dummy symlink first before this state runs just so it doesn't throw an error and just updates the timezone but in a perfect world the state would just make the change even if /etc/localtime is ever missing.

The issue feels like salt wants to do a comparison to see if it actually needs to make the change, but if the symlink is missing "how could it".

**Comment by OrangeDog** [comment]
Did you forget to add the error details?

**Comment by ipaqmaster** [comment]
Edited to include. But the error is also included under "Steps to Reproduce the behavior"

**Comment by OrangeDog** [comment]
Yeah, I see. Not really sure why the error handling is OS-specific. Whichever file is used, it should still be able to create it if it's missing.

**Comment by ipaqmaster** [comment]
I've made a tiny PR which appends "Arch" to an original fix for the same issue seen in FreeBSD.

Pulling this and installing it on an Arch machine, deleting /etc/localtime and running timezone.system successfully recreated the file with the desired timezone.

**Comment by ipaqmaster** [comment]
https://github.com/saltstack/salt/blob/fadb1d3b5c379ef6aa874ecf12fb6dadb6dc2e30/salt/modules/timezone.py#L353

Should the check which was used for FreeBSD instead be changed to support this on any *nix release? Creating the file if missing regardless of os_family? Or are there specific edge cases I'm missing where creating the file could be the wrong idea.
