### ISSUE TITLE
[DOCS] Improve file.absent description with reference to file.directory

### ISSUE THREAD

**Issue by dkacar-oradian** [saltstack/salt#61291]
**Description**
I needed to delete the complete contents of the directory, but leave the directory in existence. I hoped that `file.absent` would have a flag for that, but no luck. And then I didn't know where else to look.

**Suggested Fix**
Please add to `file.absent` documentation something like:

In case you want to delete the contents of the directory, but leave the directory in existence use `file.directory` with `clean=True`.

**Type of documentation**
Salt modules

**Location or format of documentation**
Insert page URL if applicable.

**Additional context**

**Comment by priyank-R** [comment]
@barbaricyawps I could improve the docs as mentioned. Please let me know if I should work on this one.

**Comment by barbaricyawps** [comment]
@priyank-R , that would be great if you want to take this one!
