### ISSUE TITLE
[BUG] salt-3004 tests fail if the test runner does not have working DNS, even with NO_INTERNET set

### ISSUE THREAD

**Issue by chutz** [saltstack/salt#61344]
It appears to be trying to do reverse then forward lookups of `10.0.0.1`, at least in the first test that I checked.

**Setup**
```pytest -vv``` being run in a network namespace with only the lo interface (specifically this is an updated Gentoo ebuild, running `ebuild salt-3004.0.ebuild test` as root.

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity.  If the issue persists please feel free to open a new issue.
