### ISSUE TITLE
Importing the API for Proxmox 7 fails

### ISSUE THREAD

**Issue by seandjones92** [saltstack/salt#61351]
### Description of the tech debt to be addressed, include links and screenshots

When using `salt-cloud` to provision to a Proxmox 7.x host it will fail with:
```
re_filter.findall(returned data.text) [0]
IndexError: list index out of range
```

Using `salt-cloud` against a Proxmox 6.x host does not result in this error

### Root cause findings
In `salt/cloud/clouds/proxmox.py` the `_import_api` function looks for a js variable called "pveapi" hosted at "/pve-docs/api-viewer/apidoc.js" on the host, in Proxmox 7.x this was changed to "apiSchema"

```
    re_filter = re.compile("(?<=pveapi =)(.*)(?=^;)", re.DOTALL | re.MULTILINE)
    api_json = re_filter.findall(returned_data.text)[0]
```
Since the code is looking for a variable name that does not exist the line with `re_filter.findall` fails with `list index out of range`

I have a fix in place for this and will be submitting a PR for review 

### Versions Report
```
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.9.1
      cherrypy: unknown
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: Not Installed
        Python: 3.6.8 (default, Aug 13 2020, 07:46:32)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
Salt Extensions:
        SSEAPE: 8.5.0.6
 
System Versions:
          dist: rhel 7.9 Maipo
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.49.1.el7.x86_64
        system: Linux
       version: Red Hat Enterprise Linux Server 7.9 Maipo
```

**Comment by seandjones92** [comment]
Created pull request here: https://github.com/saltstack/salt/pull/61352

**Comment by garethgreenaway** [comment]
Closed by https://github.com/saltstack/salt/pull/62166
