### ISSUE TITLE
[FEATURE REQUEST] Official salt packages for py3 / RHEL 9

### ISSUE THREAD

**Issue by sklochkov** [saltstack/salt#61364]
**Is your feature request related to a problem? Please describe.**
CentOS stream 9 has been released [recently](https://blog.centos.org/2021/12/introducing-centos-stream-9/) as part of preparation for a RHEL 9 release. It would be nice to have official builds available on repo.saltproject.io in order to help salt users on RHEL / CentOS  test their upgrades and migrations.

**Describe the solution you'd like**
It would be great to have official salt builds for RHEL / CentOS 9 available.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by llua** [comment]
bump

**Comment by mikhailal** [comment]
Well, double this. It will be amazing

**Comment by sklochkov** [comment]
Since RHEL 9 has been [released](https://www.redhat.com/en/about/press-releases/red-hat-defines-new-epicenter-innovation-red-hat-enterprise-linux-9), having an official package would be extra nice.

**Comment by jamesharr** [comment]
Likewise - AlmaLinux 9.0 is in beta and will likely have a stable release any day now. I've been trying to figure out a way to test our automations against it.

**Comment by jamesharr** [comment]
#61996 Might be a related ticket to keep tabs on. I'm not sure if/how binary compatibility is going to pan out between CentOS Stream and the RHEL derivatives like Alma or Rocky.

**Comment by M1Screw** [comment]
> Since RHEL 9 has been [released](https://www.redhat.com/en/about/press-releases/red-hat-defines-new-epicenter-innovation-red-hat-enterprise-linux-9), having an official package would be extra nice.

+1 this, we have planned and tested migrations for RHEL 8 to RHEL 9 in our production environment since 9's release, the only thing missing is saltstack support, would be nice to hear a response from salt devs regards this and rhel arm64 support.

**Comment by llua** [comment]
Seemingly this issue will be resolved when 3005 is released: https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-tiamat.html#what-is-tiamat

**Comment by M1Screw** [comment]
Thank you for the update.

**Comment by Ch3LL** [comment]
We now have rhel9 packages. Please note only the new onedir style packages are available:

https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/centos.html#install-onedir-packages-of-salt-on-centos-9

Closing as the packages are now available
