### ISSUE TITLE
question with no-root user

### ISSUE THREAD

**Issue by chwma0** [saltstack/salt#61397]
### Description of Issue

config user as 'changwei.ma' at salt-master and salt-minion, and accept key of salt-minion
```
salt-key -L
Accepted Keys:
10.10.14.46
Denied Keys:
Unaccepted Keys:
Rejected Keys:
```

salt-minion return [No response] when i exec salt command at salt-master: 
```
salt -S '10.10.14.46' cmd.run 'pwd'
10.10.14.46:
    Minion did not return. [No response]
```

If i config user as 'root' for salt-master and salt-minion, after accept keys, this command could work.
```
salt -S '10.10.14.46' cmd.run 'pwd'
```

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)

/etc/salt/master
user: changwei.ma
interface: 10.10.112.113

/etc/salt/minion
user: changwei.ma
master: 10.10.112.113
id: 10.10.14.46

### Steps to Reproduce Issue
(Include debug logs if possible and relevant.)

### Versions Report (salt-master)
Salt: 2015.5.10
         Python: 2.7.5 (default, Nov 16 2020, 22:23:17)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: Not Installed

salt-minion --versions-report
           Salt: 2015.5.10
         Python: 2.7.5 (default, Aug  7 2019, 00:51:29)
         Jinja2: 2.7.2
       M2Crypto: 0.21.1
 msgpack-python: 0.5.6
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.10
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 3.2.5
           Mako: Not Installed
        Tornado: Not Installed
        timelib: Not Installed
       dateutil: 2.7.3

**Comment by OrangeDog** [comment]
Is this a question? Are you asking how to achieve something?
Or are you asking for a feature to be added?
It's very unclear what you mean.

**Comment by dmurphy18** [comment]
@chwma0 The version of Salt you are using is no longer supported 2015.5.10 is also written in Python 2 which is not supported anymore either, EOL'd 1 Jan 2020.  You need to try with a version that is supported and those are all in Python 3 now, might I suggest Salt 3004.

The versions-report also appear to be missing the OS information, which would be required to debug any issue.

Lastly please visit Salt Enhancement Proposal for non-root user https://github.com/saltstack/salt-enhancement-proposals/blob/master/0019-master-non-root.md

Please retry with supported Salt and report back on your issue.

**Comment by OrangeDog** [comment]
Does this solve whatever the issue is?
https://docs.saltproject.io/en/latest/ref/configuration/nonroot.html

**Comment by chwma0** [comment]
> 

You haven't looked at the problem carefully, I don't know what you are talking about, are you sure you are the maintainer of the salt?

**Comment by chwma0** [comment]
> 



> Is this a question? Are you asking how to achieve something? Or are you asking for a feature to be added? It's very unclear what you mean.

**Comment by chwma0** [comment]
> @chwma0 The version of Salt you are using is no longer supported 2015.5.10 is also written in Python 2 which is not supported anymore either, EOL'd 1 Jan 2020. You need to try with a version that is supported and those are all in Python 3 now, might I suggest Salt 3004.
> 
> The versions-report also appear to be missing the OS information, which would be required to debug any issue.
> 
> Lastly please visit Salt Enhancement Proposal for non-root user https://github.com/saltstack/salt-enhancement-proposals/blob/master/0019-master-non-root.md
> 
> Please retry with supported Salt and report back on your issue.

Thank you very much for your professional response. My system is Centos7. I would like to ask, which version of the latest salt should be installed?

CentOS Linux release 7.5.1804 (Core
CentOS Linux release 7.9.2009 (Core)

**Comment by chwma0** [comment]
> Does this solve whatever the issue is? https://docs.saltproject.io/en/latest/ref/configuration/nonroot.html

You don’t know the problem and the corresponding solution
Please don’t reply to my question in the future, it’s a waste of time

**Comment by waynew** [comment]
@chwma0 please read and become familiar with our [Code of Conduct](https://github.com/saltstack/salt/blob/master/CODE_OF_CONDUCT.md)

>  Please don’t reply to my question in the future, it’s a waste of time

This is not the kind of behavior that we encourage in our community.

**Comment by chwma0** [comment]
> @chwma0 please read and become familiar with our [Code of Conduct](https://github.com/saltstack/salt/blob/master/CODE_OF_CONDUCT.md)
> 
> > Please don’t reply to my question in the future, it’s a waste of time
> 
> This is not the kind of behavior that we encourage in our community.

Could you please see what he said? If you don’t look at the problem carefully, and then casually question it, which is the behavior that you encourage?
