### ISSUE TITLE
[BUG] file.directory dereferences and fails on broken symbolic links having incorrect ownership

### ISSUE THREAD

**Issue by SaherH** [saltstack/salt#61406]
When recursing over ownership with file.directory, and if a broken symbolic link is present, the state will report result=False, and a "File Not Found" comment if the symbolic link has incorrect ownership regardless of the value of follow_symlinks.

This is because of the check_perms function from the file module, which is used in this state, and which contains [this line](https://github.com/saltstack/salt/blob/306aa6dd2948e8d149fa65f51e9959a2e464a930/salt/modules/file.py#L5006) that was added in #45257.

Steps to reproduce:

- Make a directory with a broken symlink inside it.
- Change the ownership of the symlink to other than what you would specify in the state.
- Run the state.

```bash
# the value of follow_symlinks does not affect the failure.
mkdir /tmp/salttest
ln -s nothing /tmp/salttest/broken_link
sudo chown -h nobody /tmp/salttest/broken_link
# Will Fail
sudo salt-call --local state.single file.directory name=/tmp/salttest user=root recurse="[user]" follow_symlinks=False
# ...
sudo chown -h nobody /tmp/salttest/broken_link
# Will Fail
sudo salt-call --local state.single file.directory name=/tmp/salttest user=root recurse="[user]" follow_symlinks=True
```

**Comment by twangboy** [comment]
I followed your steps on 3006.x and I was unable to replicate this problem. If this is still an issue, please provide detailed instructions on a currently supported version of Salt in a new issue.
