### ISSUE TITLE
[BUG] Salt Minion execution fails with Python error "AttributeError: module 'collections' has no attribute 'MutableMapping'" on Fedora 35/Python 3.10

### ISSUE THREAD

**Issue by spacez320** [saltstack/salt#61401]
**Description**

When executing sub-commands with the Salt Minion, a Python stack trace is encountered which ends with "AttributeError: module 'collections' has no attribute 'MutableMapping'".

**Setup**

1. Set up stock x86_64 Fedora 35.
2. Install Salt Minion.
3. Connect the Salt Minion to some Salt Master (may not be required).

- [x] on-prem machine
  
**Steps to Reproduce the behavior**

Run `sudo salt-call state.highstate` to observe the stack trace.

```
 salt $ sudo salt-call state.highstate
Traceback (most recent call last):
  File "/usr/bin/salt-call", line 33, in <module>
    sys.exit(load_entry_point('salt==3003.3', 'console_scripts', 'salt-call')())
  File "/usr/lib/python3.10/site-packages/salt/scripts.py", line 437, in salt_call
    import salt.cli.call
  File "/usr/lib/python3.10/site-packages/salt/cli/call.py", line 6, in <module>
    import salt.cli.caller
  File "/usr/lib/python3.10/site-packages/salt/cli/caller.py", line 15, in <module>
    import salt.minion
  File "/usr/lib/python3.10/site-packages/salt/minion.py", line 36, in <module>
    import salt.pillar
  File "/usr/lib/python3.10/site-packages/salt/pillar/__init__.py", line 16, in <module>
    import salt.fileclient
  File "/usr/lib/python3.10/site-packages/salt/fileclient.py", line 26, in <module>
    import salt.utils.http
  File "/usr/lib/python3.10/site-packages/salt/utils/http.py", line 73, in <module>
    import requests
  File "/usr/local/lib/python3.10/site-packages/requests/__init__.py", line 60, in <module>
    from . import utils
  File "/usr/local/lib/python3.10/site-packages/requests/utils.py", line 32, in <module>
    from .cookies import cookiejar_from_dict
  File "/usr/local/lib/python3.10/site-packages/requests/cookies.py", line 172, in <module>
    class RequestsCookieJar(cookielib.CookieJar, collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'
```

**Expected behavior**

Salt Minion works as expected and does not stack trace.

**Versions Report**

<details><summary>salt --versions-report</summary>

```
 salt $ salt-minion --versions-report
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: 1.14.6
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: 1.1.4
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.11.0
        pygit2: Not Installed
        Python: 3.10.1 (main, Dec  7 2021, 00:00:00) [GCC 11.2.1 20211203 (Red Hat 11.2.1-7)]
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 22.2.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: fedora 35
        locale: utf-8
       machine: x86_64
       release: 5.15.6-200.fc35.x86_64
        system: Linux
       version: Fedora Linux 35
```
</details>

**Additional context**

The Python error looks similar to other errors having to do with running Python packages on 3.10 and may be specific to the Python version.

Fedora bug filed here: https://bugzilla.redhat.com/show_bug.cgi?id=2035663

**Comment by spacez320** [comment]
Allowing Pip to upgrade the system requests library to `requests==2.26.0` seemed to fix the immediate issue, although I worry about the knock-off effects this has since it's the system Requests library.

It would be nice if Salt was able to install into a virtual environment via the bootstrap script, but the bootstrap script states this is an Ubuntu-only feature.

**Comment by OrangeDog** [comment]
If Fedora is providing Python 3.10 it should also be providing a working python3-requests.

However, from your stack trace, it appears someone already overwrote the system requests with an older version:
> /usr/local/lib/python3.10/site-packages/requests

If you `pip uninstall` it and then re-install the system package, it should work fine.

**Comment by spacez320** [comment]
@OrangeDog I think you might be correct. From a stock install of Fedora 35 going directly into `dnf update && dnf install salt-minion`, I'm able to execute something like `salt-call --local test.ping` successfully without the error.

It must be something I'm doing as part of machine setup that's overwriting Requests. Thanks for your help.

That being said, I'll recommend again that if there was an option to do a virtual environment install with bootstrap on RH systems, that would be awesome!
