### ISSUE TITLE
[FEATURE REQUEST] salt-cloud azure add availability zone as configuration setting

### ISSUE THREAD

**Issue by Dantin1234** [saltstack/salt#61425]
Hello,
**Is your feature request related to a problem? Please describe.**
I want to use the azure loadbalancer to loadbalance my traffic to my virtual machines created by salt-cloud and managed via salt. But it is not possible to configure an availability zone to an vm via salt. The azure loadbalancer is not usable with salt managed vms in azure until this feature is implemented

**Describe the solution you'd like**
Add availability zone as configuration setting in "cloud.profiles.d" or as setting usable in a mapping file. 

**Additional context**
[azure availability zone documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/availability)

best regards

**Comment by nicholasmhughes** [comment]
The Azure functionality in Salt is moving to https://github.com/salt-extensions/saltext-azurerm

I have opened an issue there to represent the feature request.
