### ISSUE TITLE
[DOCS] Recommendation for update in AUTOACCEPT MINIONS FROM GRAINS

### ISSUE THREAD

**Issue by Scientist786** [saltstack/salt#61436]
**Description**
I was trying to auto-accept minions by using [autosign_grains](https://docs.saltproject.io/en/latest/topics/tutorials/autoaccept_grains.html). I followed the document exactly word by word. As my minions didn't have a grain called UUID, I created a custom grain myself but still, the master was not receiving the grains sent by minion. Following was my grains file:
```
grains:
    my_custom_grain: a1b2c3d4
```
The grain used in the document (UUID) was a system grain having "string" as a data type as default.

**Suggested Fix**
The document does not explain if the user wants to use custom grains or use a system grain whose data type is not a string. According to the document, you can just add custom grain in your grains file and send it to master. Following should be added to the document:

If you want to use a grain whose data type is not string you need to encapsulate them in string format as shown below:
```
grains:
    my_custom_grain: "a1b2c3d4"
```

**Type of documentation**
Salt documentation

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/tutorials/autoaccept_grains.html

**Comment by OrangeDog** [comment]
Arguably it's a bug that autosign_grains only supports strings and not numbers.

Your example already is a string though. The actual reproduction would be e.g. `my_custom_grain: 123456`

**Comment by barbaricyawps** [comment]
@OrangeDog , in your opinion do you think this is actually a bug in Salt (e.g. autosign_grains needs to accept both datatypes) rather than a docs issue? Or perhaps we could note that it only accepts strings in the docs while the bug fix is pending?

**Comment by agraul** [comment]
@barbaricyawps I think this is a bug in Salt and not in the docs. I have a simple fix (with tests), do you think we can turn this DOCS issue into a source code one? What does the rest of core team think about this being designed as intended vs a bug?

BTW, https://github.com/saltstack/salt/issues/63708 looks like a duplicate of this issue to me

**Comment by barbaricyawps** [comment]
I think you make a compelling argument, @agraul . Would everyone be okay with me closing down this issue as a duplicate of #63708 ? Alternatively, I can change it to a bug instead of a docs issue, as you said.

**Comment by Scientist786** [comment]
Do I still get points for contributing? >.<
