### ISSUE TITLE
[BUG] salt-binary - apt-cache libstdc++ not found

### ISSUE THREAD

**Issue by ekristen** [saltstack/salt#61438]
**Description**

Using the all in one salt binary, when trying to install, running into the following errors on ubuntu 20.04.

```
Command 'apt-cache' failed with return code: 1
stderr: apt-cache: /tmp/_MEIq1Z41W/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by apt-cache)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /usr/bin/apt-get)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /usr/bin/apt-get)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /lib/x86_64-linux-gnu/libapt-private.so.0.0)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /lib/x86_64-linux-gnu/libapt-private.so.0.0)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /lib/x86_64-linux-gnu/libapt-private.so.0.0)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `CXXABI_1.3.8' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `GLIBCXX_3.4.26' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
/usr/bin/apt-get: /tmp/_MEIq1Z41W/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by /lib/x86_64-linux-gnu/libapt-pkg.so.6.0)
```

**Steps to Reproduce the behavior**
Using the latest salt-binary run the following ...

I'm cloning https://github.com/teamdfir/sift-saltstack to a random directory in /var/cache

```bash
salt call --local --retcode-passthrough -l debug --out yaml --file-root "/var/cache/...." --no-color state.apply sift.server
```

**Expected behavior**
Expected to work?

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:
          Salt: 3003
 
Dependency Versions:
          cffi: 1.14.4
      cherrypy: 17.4.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.7 (default, Feb 23 2021, 21:56:10)
  python-gnupg: 0.4.4
        PyYAML: 5.3.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: UTF-8
       machine: x86_64
       release: 5.4.0-88-generic
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

**Additional context**

/cc @Ch3LL

**Comment by Ch3LL** [comment]
Can you elaborate what you mean by "Using the latest salt-binary". Your salt versions report shows 3003, but the latest version is 3004.

- Are you using the single binary, onedir, or deb package?
- Where did you install it from?

**Comment by ekristen** [comment]
@Ch3LL it looks like the repo.saltstack.com has bad links. https://repo.saltproject.io/#single-binary shows 3003 but the link is broken to https://repo.saltproject.io/salt-singlebin/3004/salt-3003-3-linux-amd64.tar.gz, so I adjusted it to https://repo.saltproject.io/salt-singlebin/3003/salt-3003-3-linux-amd64.tar.gz and that's the one I'm using.

**Comment by Ch3LL** [comment]
Thanks for pointing that out. I will get the documentation fixed. Can you test with 3004? (https://repo.saltproject.io/salt-singlebin/3004-1/salt-3004-1-linux-amd64.tar.gz)

**Comment by ekristen** [comment]
Same error.

**Comment by Ch3LL** [comment]
I was able to replicate this behavior. This looks to be an issue with the package and not the Salt code recently added to support using apt-cache. I created this issue: https://gitlab.com/saltstack/open/salt-pkg/-/issues/44 in our packaing repo to track this error. 

I have also put in a fix to update the single binary link, and am working with the SRE team to ensure it gets deployed. I'll update here when the fix is live.

**Comment by ekristen** [comment]
Sounds good, I've set myself up to track the salt-pkg issue as well. It looks like this got slated for fixing in 3005? Will it be backported to 3004? I looked but couldn't find a date, when is 3005 due out? Thanks.

**Comment by Ch3LL** [comment]
Depending on the fix we might be able to add it to 3004. We don't have an exact date for 3005, but I believe we are targeting end of March for right now.

**Comment by Ch3LL** [comment]
repo.saltstack.com has been updated. I will close this issue now in favor of the salt-pkg issue concerning the packaging issue.

**Comment by ekristen** [comment]
Thanks @Ch3LL

**Comment by s0undt3ch** [comment]
Fix in Salt https://github.com/saltstack/salt/pull/61864
Tests in salt-pkg https://gitlab.com/saltstack/open/salt-pkg/-/merge_requests/141

**Comment by ekristen** [comment]
@s0undt3ch what release will this be in?

**Comment by s0undt3ch** [comment]
Fix will be in the Phosphorus, 3005, release.
