### ISSUE TITLE
[DOCS] Docs don't refect the list of supported platforms correctly

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#61455]
**Description**
The documentation for platform specific installation instructions fails to mention AIX, and Juniper and isn't Scientific Linux long dead at this point as a distribution.
Can probably get away with saying 'Amazon Linux' but should really be 'Amazon Linux 2' since that is the distribution name currently supported, given that 'Amazon Linux' was RHEL 6 based and both are EOL.
Wonder about including Gentoo at this point too.

This section should also be updated in conjunction with Salt  Platform Support on SaltProject.io which is out of date too.

**Suggested Fix**
Update docs to accurately reflect the platforms and OS's we support

**Type of documentation**
This could be Salt documentation, Salt modules, the Salt Repo or the Getting Started guide.

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/installation/index.html#platform-specific-installation-instructions
https://saltproject.io/salt-platform-support/

**Comment by barbaricyawps** [comment]
This is definitely on my Salt Docs Roadmap: https://saltdocs.prodcamp.com/6

However, the stakeholders who determine which doc initiatives I should work on first determined that another initiative was more important than this one. It will be at least 2-3 sprint cycles before I can get to it.

**Comment by barbaricyawps** [comment]
FYI, I'm creating a sister ticket on the salt-install-guide repo to track this work. It will get done eventually: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues/15

**Comment by barbaricyawps** [comment]
Closing. Resolved by: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/16
