### ISSUE TITLE
[FEATURE REQUEST] Encrypt pillar_cache info on disk

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#61493]
**Is your feature request related to a problem? Please describe.**
Secure environments with high speed requirements need to enable pillar_cache in the Salt master. However, the pillar_cache does not get encrypted on disk allowing for secrets to potentially be read in plain text.

**Describe the solution you'd like**
Have pillar_cache be encrypted on disk

One solution might be that if the user is using Vault in their environment, to use a token generated from Vault to encrypt the data on disk.

**Comment by OrangeDog** [comment]
Encrypting it doesn't add anything. If you have root access then you can just ask salt to give you the pillar data. If you don't have root access then you can't read the pillar cache.

If you are concerned about at-rest encryption, then you need to be encrypting the whole disk.

**Comment by waynew** [comment]
@doesitblend I think OrangeDog is correct here - it's considered best practice to encrypt the whole disk if you need at-rest encryption (i.e. that's out of scope for Salt - I mean in theory a Salt state could configure encryption for the disk, I'm sure, but...)

I'm going to go ahead and close this for now - feel free to reach out via Slack or something if there's something else at play here :+1:

**Comment by doesitblend** [comment]
@waynew There are cases where it is not reasonable to encrypt the entire disk to resolve this and having the pillar data encrypted before storing would be preferred. Please reconsider this feature for inclusion as a configurable option for use with pillar data.

**Comment by OrangeDog** [comment]
The decryption key will also be stored unencrypted on the same server. This approach is not going to achieve anything.

**Comment by doesitblend** [comment]
Thanks for the feedback all. We will look into using extension modules for this as this is a necessary feature for our organization.
