### ISSUE TITLE
[BUG] chcolatey.install "package_args" passed using bad param name

### ISSUE THREAD

**Issue by cavepopo** [saltstack/salt#61506]
**Description**
When using the --packageparameters option to pass params to installing packege using chocolatey, the param passed by the module is not using the correct name.

**Setup**
minion installed on windows using salt-cloud standard bootstrap installer, salt master running on debian 10.

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Windows salt minion running KVM on proxmox + debian salt master running on LXC on proxmox)

  
**Steps to Reproduce the behavior**
Using the following state would show the bug : 
```
install_git:
  chocolatey.installed:
    - name: git
    - package_args: "'/WindowsTerminal /GitAndUnixToolsOnPath'"
```

**Expected behavior**
**package_args** should be passed as "--params" to choco as seen in minion's choco logs :
``` Received arguments: install git -y --params='/WindowsTerminal /GitAndUnixToolsOnPath'```

instead it is wrongly passed as "--installarguments" to choco as seen in minion's choco logs : 
```Received arguments: install git --installarguments '/WindowsTerminal /GitAndUnixToolsOnPath' --no-progress --yes```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PS C:\Windows\system32> salt-call.bat --versions-report
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: 1.14.5
      cherrypy: 18.6.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.13
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.7.4 (tags/v3.7.4:e09359112e, Jul  8 2019, 19:29:22) [MSC v.1916 32 bit (Intel)]
  python-gnupg: 0.4.6
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: 3.0.4
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: msys_nt-10.0-19043 3.1.7
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19041 SP0
```
</details>

**Additional context**
Dunno if this is the case for other package than 'git'...

**Comment by dafyddj** [comment]
I tried this and got this in the logs:
```
2022-01-25 15:49:59,917 2632 [DEBUG] - Command line: "C:\ProgramData\chocolatey\choco.exe" install git --packageparameters "'/WindowsTerminal /GitAndUnixToolsOnPath'" --no-progress --yes
2022-01-25 15:49:59,917 2632 [DEBUG] - Received arguments: install git --packageparameters '/WindowsTerminal /GitAndUnixToolsOnPath' --no-progress --yes
```
which does not match your bug report. 
Salt v3004-3

**Comment by cavepopo** [comment]
Yes that is correct !
My bad, the wrong behavior I am seeing (which I thought came from this "bug" ) must come from somewhere else.

Closing then.
