### ISSUE TITLE
[TECH-DEBT] Note Napalm-base is no longer supported, from Slack with Mircea Ulinic

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#61542]
Note Napalm-base is no longer supported, from Slack with Mircea Ulinic
Network Engineer at DigitalOcean

Need to update this execution module to not rely on it

FYI @s0undt3ch as per request, and Slack conversation with Mircea
mirceaulinic:napalm: 11:33 AM
Hi. Sorry for late reply, haven't been much active over here lately... Napalm-base is no longer supported, napalm 2.5.0 is what you should be looking for. Let me know if you have any questions. :wink:

Daithi 1:25 PM
thanks for the info, building packages to support napalm and napalm-base on Redhat, will drop napalm-base then, doing napalm 2.5.0, almost done. Thanks for getting back to me, created a native minion for Arista, only found out about your work after it was done (based on Salt 2019.2.2), re-invention of the wheel :smile: but that is how life goes.
mirceaulinic:napalm: 1:28 PM
Haha I know the feeling. Cool, looking forward to give it a whirl. Thanks for working on this!

david@david-lap2:~/devcode/dgm-salt-fix/salt/salt$ grep -r napalm-base *
runners/bgp.py:    return (False, 'The napalm-base module could not be imported')
runners/net.py:    from netaddr import IPNetwork  # netaddr is already required by napalm-base
runners/net.py:    return (False, 'The napalm-base module could not be imported')
utils/napalm.py:    # from napalm-base
utils/napalm.py:        #   other than napalm-base.
utils/napalm.py:        # For example, if napalm-base does not satisfy the requirements
utils/napalm.py:        #   we may need to define a custom library on top of napalm-base
utils/napalm.py:            log.error('Falling back to napalm-base')

_Originally posted by @dmurphy18 in https://github.com/saltstack/salt/issues/55222#issuecomment-555195551_

**Comment by dmurphy18** [comment]
This was noted back in Nov 18, 2019, in closed issue https://github.com/saltstack/salt/issues/55222

But working on current Napalm issue noticed we have still not done anything about removing the deprecated napalm.base (died in 2017) which is no longer used in napalm.

**Comment by garethgreenaway** [comment]
I believe this one is already complete.  We're not importing `napalm-base` anywhere in the code base.

**Comment by dmurphy18** [comment]
Got a little cleanup left to do, we did make use of it back in Jan 28 when I checked.
A few droppings that should be cleaned up, from latest master branch
```david@david-XPS-15-9570:~/devcode/dgm_salt_master/salt$ grep -R napalm-base *
grep: doc/_build/doctrees/topics/installation/eos.doctree: binary file matches
doc/_build/html/topics/installation/eos.html:python-napalm-base-0.24.3-1.noarch.rpm
doc/_build/html/_sources/topics/installation/eos.rst.txt:    python-napalm-base-0.24.3-1.noarch.rpm
salt/utils/napalm.py:    # from napalm-base
salt/utils/napalm.py:        #   other than napalm-base.
salt/utils/napalm.py:        # For example, if napalm-base does not satisfy the requirements
salt/utils/napalm.py:        #   we may need to define a custom library on top of napalm-base
salt/utils/napalm.py:            log.error("Falling back to napalm-base")
```
