### ISSUE TITLE
[BUG] Debian Bullseye issues setting user passwords

### ISSUE THREAD

**Issue by peterbaumert** [saltstack/salt#61590]
**Description**
When I try to set the password of the root user, no matter if I use the hashed password or the cleartext with the option set, I can not log in. After I open the file with ```vipw -s``` and save it ( nothing edited ). It starts to work.

I tried this with several newly installed minions.

**Setup**
```
root.password:
  user.present:
    - name: root
    - password: {{ pillar.root.password }}
```

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
- Install blank Debian Bullseye
- Install salt-minion
- Run state-apply

**Expected behavior**
I expect that the password works without manual interaction.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
Salt Version:                                         
          Salt: 3004                                  
                                                      
Dependency Versions:                                  
          cffi: Not Installed                         
      cherrypy: Not Installed                         
      dateutil: 2.8.1                                 
     docker-py: Not Installed                         
         gitdb: 4.0.5                                 
     gitpython: 3.1.14                                
        Jinja2: 2.11.3                                
       libgit2: Not Installed                         
      M2Crypto: Not Installed                         
          Mako: Not Installed                         
       msgpack: 1.0.0                                 
  msgpack-pure: Not Installed                         
  mysql-python: Not Installed                         
     pycparser: Not Installed                         
      pycrypto: Not Installed                         
  pycryptodome: 3.9.7                                 
        pygit2: Not Installed                         
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed                         
        PyYAML: 5.3.1                                 
         PyZMQ: 20.0.0                                
         smmap: 4.0.0                                 
       timelib: Not Installed                         
       Tornado: 4.5.3                                 
           ZMQ: 4.3.4                                 
                                                      
System Versions:                                      
          dist: debian 11 bullseye                    
        locale: utf-8                                 
       machine: x86_64                                
       release: 5.10.0-11-amd64                       
        system: Linux                                 
       version: Debian GNU/Linux 11 bullseye          
```
</details>

**Additional context**
Minnion is running at Linux admin 5.10.0-11-amd64 #1 SMP Debian 5.10.92-1 (2022-01-18) x86_64 GNU/Linux
salt-minion 3002.6

**Comment by garethgreenaway** [comment]
@peterbaumert Just making sure you saw the question in the last comment.

**Comment by peterbaumert** [comment]
Hey sorry i actually didnt. Im currently in vacation and will get back to you next week.

**Comment by garethgreenaway** [comment]
@peterbaumert Just following up and seeing there was anymore feedback on this issue?

**Comment by garethgreenaway** [comment]
@peterbaumert Following up again on this one.

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity, if the issue is still occurring please feel free to reopen the issue.
