### ISSUE TITLE
[BUG] state.show_state_usage stop working when using other than base environments (like when having SSE installed)

### ISSUE THREAD

**Issue by amalaguti** [saltstack/salt#61614]
**Description**
state.show_state_usage fails when server has the enterprise plugin enabled, seems to be related to the sse environments, maybe missing a top.sls files for highstate.

**Setup**
In a server with raas.conf disable raas.conf and define highstate top under /srv/salt/top.sls, something simple will work like all minions running a test state.
Execute the highstate to make sure everything works ok
then run state.show_state_usage 

Once confirmed it works ok, stop salt-master, re enable raas.conf and re-start salt-master
Try state.show_state_usage again and it would fail.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
[root@mocks-sse-2 ~]# salt mocks-sse-2 state.show_state_usage
mocks-sse-2:
    ----------
    base:
        ----------
        count_all:
            17
        count_unused:
            16
        count_used:
            1
        unused:
            - linux_acl.acls_www
            - linux_acl.setup
            - merge-include-tests
            - merge-include-tests.config
            - merge-include-tests.includes_requirements
            - merge-include-tests.install
            - orch.orch_reboot
            - sse
            - sse.eapi_cache
            - sse.eapi_database
            - sse.eapi_database.revert
            - sse.eapi_plugin
            - sse.eapi_service
            - sse.eapi_service.revert
            - top
            - win.win_interactive_logon_msg
        used:
            - tsl_test
            
[root@mocks-sse-2 ~]# systemctl stop salt-master
[root@mocks-sse-2 ~]# cp /etc/salt/master.d/raas.bkp /etc/salt/master.d/raas.conf
[root@mocks-sse-2 ~]# systemctl start salt-master
[root@mocks-sse-2 ~]# salt mocks-sse-2 state.show_state_usage
mocks-sse-2:
    Passed invalid arguments to state.show_state_usage: argument of type 'NoneType' is not iterable

        Retrieve the highstate data from the salt master to analyse used and unused states

        Custom Pillar data can be passed with the ``pillar`` kwarg.

        CLI Example:

        .. code-block:: bash

            salt '*' state.show_state_usage

ERROR: Minions returned with non-zero exit code

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```
PASTE HERE
```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
@saltybaker Believe this is one of yours to assign to someone in your team

**Comment by msteed** [comment]
This looks like a bug in salt but should be an easy fix. I'll take a run at it.
