### ISSUE TITLE
salt-minion fails with "ModuleNotFoundError: No module named 'salt'" immediately after upgrading from 18.04 to 20.04

### ISSUE THREAD

**Issue by delvecchiomark** [saltstack/salt#61664]
### Description of Issue
I have a few workstations in my environment not reachable after upgrading from Ubuntu 18.04 to 20.04. I have another I just set up brand new exhibiting the same behavior. I installed Ubuntu, set up and salted it on 18.04 and it was fine. I upgraded to 20.04, rebooted to finish the install, and first thing I did was try to reach the workstation, no other changes made. I ran a `test.ping` both before and after the upgrade. 18.04 returned True, 20.04 returned `Minion did not return. [Not connected]`

When I run `service salt-minion status`, it returns `status=1/FAILURE` with the output `File "/us/local/bin/salt-minion:, line 7, in <module>
from salt.scripts import salt_minion
ModuleNotFoundError: No module named 'salt'`

I tried both `pip install salt` and `pip3 install salt` to no success. python -V returns 2.7.18 and python3 -V returns 3.8.10. Kind of at a loss as to what else would

### Versions Report
Minion:
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.0
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 26 2021, 20:14:08)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-100-generic
        system: Linux
       version: Ubuntu 20.04 focal

Master:
Salt Version:
           Salt: 3000.9
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: unknown
       dateutil: 2.6.1
      docker-py: Not Installed
          gitdb: 2.0.3
      gitpython: 2.1.8
         Jinja2: 2.10
        libgit2: Not Installed
       M2Crypto: 0.27.0
           Mako: 1.0.7
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: Not Installed
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 2.7.17 (default, Feb 27 2021, 15:10:58)
   python-gnupg: 0.4.1
         PyYAML: 3.12
          PyZMQ: 16.0.2
          smmap: 2.0.3
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.2.5
 
System Versions:
           dist: Ubuntu 18.04 bionic
         locale: UTF-8
        machine: x86_64
        release: 5.4.0-1047-aws
         system: Linux
        version: Ubuntu 18.04 bionic

**Comment by OrangeDog** [comment]
Presumably your Salt installation is still in `/usr/lib/python3.6`, not `/usr/lib/python3.8`.

I suggest removing your existing versions (via apt and pip and pip3) and reinstalling salt, ensuring you've also updated from the bionic to the focal repo.

**Comment by garethgreenaway** [comment]
@delvecchiomark Making sure you saw the comment from @OrangeDog above about cleaning out the older packages following the upgrade.  Also check that the Salt repositories are enabled, the Ubuntu upgrade process typically disables any non-Ubuntu repositories.

**Comment by garethgreenaway** [comment]
Closing this one out due to lack of activity, if the issue persists please feel free to open a new issue.  Thanks!
