### ISSUE TITLE
[FEATURE REQUEST] Allow grains to be refreshed before any operation

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#61708]
**Is your feature request related to a problem? Please describe.**
Environments using dynamic grains from external sources often have a need to populate grains information in another tool (such as a DCIM) and have those grains immediately take effect during the next execution on a minion. With the current workflow, grains can only be refreshed manually, on an interval (causing potentially unnecessary polling) or **after** a highstate (when we wanted the grains refreshed before the highstate).

**Describe the solution you'd like**
I'd like a way to refresh grains prior to any operation on a minion in order to ensure the minion has the most up-to-date information prior to execution.

**Describe alternatives you've considered**
Considered just using `grains_refresh_every` and also unsuccessfully tried a few different ways to refresh grains inside of Jinja and states.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by dmurphy18** [comment]
@nicholasmhughes Why would using saltutl.refresh_grains not suffice for your case of dynamic grains, see https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.refresh_grains

Note: also https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.sync_grains

**Comment by nicholasmhughes** [comment]
@dmurphy18 , because:

* manually calling `saltutil.refresh_grains` as a separate action before every operation is not viable
* implementing `saltutil.refresh_grains` inside of Jinja or as a `module.run` state does not seem to refresh the grains within the same run

**Comment by dmurphy18** [comment]
For the first I was think of a requisite ensuring the refresh_grains was performed before calling the action you wanted executed, but the second point negates that :( , presumably there is some caching going on  and preserving the grains till after the state finishes.  
Wonders if the changes in the associated PR have the same issue and tests to check for that, will check in review
