### ISSUE TITLE
[DOCS] spm intalltion docs show wrong setup for file_roots

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#61726]
**Description**

the docs at https://docs.saltproject.io/en/latest/topics/spm/master.html#update-file-roots show file_roots with numbered lines instead of the list indicator. 

```
file_roots:
  base:
    1. /srv/salt
    2. /srv/spm/salt
```

**Suggested Fix**
That should be 

```
file_roots:
  base:
    - /srv/salt
    - /srv/spm/salt
```
**Type of documentation**
Salt documentation example

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/spm/master.html#update-file-roots

**Comment by lowercase00** [comment]
@whytewolf up for grab? I can help.

**Comment by whytewolf** [comment]
@lowercase00 yes please. I almost completely forgot about this issue myself.

**Comment by lowercase00** [comment]
@whytewolf sure, I'll go through some docs issues to try to fix the easy stuff.

**Comment by lowercase00** [comment]
@whytewolf first PR, would be great if you could take a look if the flow was correct: https://github.com/saltstack/salt/pull/61979
thanks!
