### ISSUE TITLE
Add Ubuntu 22.04 to CI tests

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#61799]

**Comment by dmurphy18** [comment]
@krionbsd @MKLeb Added the Ubuntu 22.04  Beta to jenkins ci

**Comment by koenr** [comment]
Excuse my ignorance, but does this mean that Ubuntu 22.04 will not have an installable salt-minion for the next few months?
We use salt-stack to administer our students laptops and we planned to roll out 22.04 in august. If Salt is not ready for 22.04, then it will be a 20.04 - so it would be good to know.
Thank you for this great peace of software!

**Comment by Seldaek** [comment]
@koenr I've successfully (except for managed ppa support in salt being borked but I'm not sure what's at fault there yet) deployed it on 22.04 using the packages from the Ubuntu repo which are currently up to date, I expect I'll switch to the salt repo once it has 22.04 available.

**Comment by Foorack** [comment]
@Ch3LL Can this issue be closed as resolved?

I believe this and https://github.com/saltstack/salt/issues/61995 are duplicates, and as #62100 is merged now it should be fine to close both?

**Comment by dmurphy18** [comment]
Closing this as already done
