### ISSUE TITLE
[FEATURE REQUEST] allow specifying metadata in consul service registration 

### ISSUE THREAD

**Issue by tomdoherty** [saltstack/salt#61792]
**Is your feature request related to a problem? Please describe.**
At present Salts consul module cannot specify metadata for services registered in Consul

**Describe the solution you'd like**
Add new metadata option that is passed to Consul when registering a service

**Describe alternatives you've considered**
Not using Salt for registering Consul services

**Additional context**
N/A

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by dmurphy18** [comment]
Waiting on PR, which needs tests

**Comment by dmurphy18** [comment]
@tomdoherty Closing the due to unresponsiveness. Note: that Consul is slated to be moved to salt-extensions under community support in the future.
