### ISSUE TITLE
[DOCS] Phosphorus Release Note Updates

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#61801]
The tiamat packages will be ready for the Phosphorus Release. This issue is being created to track the work to document the following in the release notes:

New Tiamat Packages
------------------------------

- Announce the use of the new Tiamat Packages.
- Add the path to the installation guide for the tiamat packages.
- The tiamat packages will include Python version 3.9, where applicable.
- Any new OS supported for this release will be tiamat packages only and not supported with the old deprecated packaging going forward.

Old Deprecated Packaging
------------------------------------

-  The old packaging is on a deprecation path and will be removed in version 3007
-  We will only continue to support the old packaging for OSs that support Python 3.7 and above for the next 2 releases. Users will need to update their repo files to point to the new Tiamat packaging if they are on an OS supporting older than python3.7.  Will need to define what OSs are impacted.

Dropping Support for Python 3.5,3.6
------------------------------------------------

- We will no longer support Python 3.5 and 3.6 since they are end of life.
- For supported OSs that only have Python 3.5 and 3.6 tiamat packages will be provided.

OS Support
----------------

Removing: Centos8
Adding: Centos8 Steam, Centos 9 Stream, Ubuntu 22.04, Fedora 35, Fedora 36, AIX v7.3, MacOS

Bootstrap Script
----------------------
- The bootstrap script will use the tiamat packages by default going forward.

**Comment by Ch3LL** [comment]
@s0undt3ch @garethgreenaway @dwoz @waynew @frogunder @barbaricyawps @whytewolf @dmurphy18 @krionbsd @twangboy 

Please review the information above and note anything that needs to be fixed or added.

**Comment by dmurphy18** [comment]
Corrected Fedora 26 -? 36 and added AIX v7.3

**Comment by Ch3LL** [comment]
"The tiamat packages will include Python version 3.9 for linux, windows and mac packaging"

@dmurphy18 how about that?

**Comment by dmurphy18** [comment]
@Ch3LL Could add Solaris and Juniper.
AIX provides Python3.7.12 and would be nice not to have to build Python 3.9 if didn't have to.  Presuming that they will move to Python 3.8 or 3.9 soon and use that then.

On Arista, make use of OS provided Python 3.7, it is basically Centos 7 underneath the covers, so no Python 3.8 or 3.9 available.  But that is a similar situation for our regular Linux Centos 7 support (Centos 7 does not have native Python 3.8 or 3.9 packages) and it moving to Python 3.9 there, should be able to leverage that for Arista.  Only concern would be Centos 7 AltArch which is 32-bit for 32-bit Arista, and if we encounter any 64-bit assumptions in Python, but hopefully not, given Python usage in embedded environments which are typically 32-bit at this point (think ARM).

**Comment by twangboy** [comment]
Added MacOS to supported OSes

**Comment by barbaricyawps** [comment]
Related issue: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues/27

**Comment by dmurphy18** [comment]
@Ch3LL "The tiamat packages will include Python version 3.9 for linux, windows and mac packaging"

Forgot to say that looks great
