### ISSUE TITLE
[BUG] salt-ssh [ERROR   ] 'PathDistribution' object has no attribute '_normalized_name'

### ISSUE THREAD

**Issue by javiroman** [saltstack/salt#61819]
**Description**
Simple salt-ssh command raise error.

**Setup**
```
conda create -n salt python=3
conda activate salt
(salt) pip install salt
(salt) salt-ssh --verison
salt-ssh 3004

(salt) cat config/master 
root_dir: ./
ssh_use_home_key: True
file_roots:
  base:
    - ./rootfs
(salt) cat config/roster 
host1:
  host: 10.0.0.3
  sudo: True
  priv: /home/user/.ssh/private_key
  user: vagrant
(salt) salt-ssh -c config -i host1 test.ping
[ERROR   ] 'PathDistribution' object has no attribute '_normalized_name'
```

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
This appears to be caused by an incompatible / broken Python installation.
https://github.com/pypa/pipenv/issues/4883

I see you're using conda. That may be the problem. What python is installed on 10.0.0.3?
Please provide the full versions report from the master.

**Comment by javiroman** [comment]
You are right, it's an issue of Python 3.10.
I'm using Python 3.10.0 in the conda environment, changing for example to Python 3.9.7, salt-ssh works again.

Many thanks for your help.

**Comment by OrangeDog** [comment]
As far as I can tell, 3.10.1 should also work. Basically anything other than 3.10.0, which has [this bug](https://bugs.python.org/issue44246).
