### ISSUE TITLE
[FEATURE REQUEST] file.tidied should be more flexible

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#61823]
**Describe the solution you'd like**
The `file.tidied` function should allow more flexibility in cleaning out files from a directory. Currently, it can only clean out files files above a certain size threshold or files where the access time (atime) is older than a certain numbers of days. The ability to exclude specific files/directories in the directory tree via regex would be extremely helpful for some workflows. Additionally, both the matching and exclusion regular expressions should be able to work against the full file path instead of just the file/directory name itself. Following links is currently set statically in a disabled state, and enabling that would be nice. Finally, time comparison should be able to work against change (ctime) and modified (mtime) times as well.

**Describe alternatives you've considered**
Jinja gymnastics can be used to pipe `file.find` execution module output to `file.absent`, but that can get out of hand pretty quickly.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by dmurphy18** [comment]
@nicholasmhughes I wonder if this would be better as a SEP where the proposal has the exact interfaces and functionality laid out, and the side-interactions discussed.  Then the proposal would get a full hearing across the team.

The above requests live too much to interpretation when implementing, and a more concise definition of operation, would help, given this would be implemented across a wide range of platforms (Windows, MacOS, AIX, Solaris, as well as Linux).

Been out of Windows development too long to know if current Windows file systems have support for ctime, mtime and atime equivalents. I believe they do, but my Windows experience is not recent enough to be definitive.

**Comment by nicholasmhughes** [comment]
@dmurphy18 , there's already a PR in for the functionality and a SEP seems like overkill. Happy to discuss during Open Hour today if you're on.

**Comment by dmurphy18** [comment]
Sorry missed the PR associated with it, will review that
