### ISSUE TITLE
[BUG] Unable to use GPG encrypted files in Pillar with pillar_cache

### ISSUE THREAD

**Issue by doesitblend** [saltstack/salt#61836]
**Description**
Our organization requires having the `pillar_cache` setting to be enabled in our Salt masters for performance. We are currently working on upgrading to the latest version from Salt 2019 and while doing some testing we noticed that a piece is not working as expected. Something that used to work in Salt is to use GPG encrypted data as pillar data. But now we get a message on the master like the following (see attached file gpg_encrypted_pillar_cache_issue.log). 

[gpg_encrypted_pillar_cache_issue.log](https://github.com/saltstack/salt/files/8327372/gpg_encrypted_pillar_cache_issue.log)

However, if I disable pillar_cache in my Salt master it will work fine, ie. it will report the key found with no value since it is a binary value. This issue only occurs when `pillar_cache` is enabled in the Salt master. Please see below for more info on the setup.

**Setup**
This takes a little time to setup, but the steps to replicate are as follows:

Steps to replicate:
- Follow Pillar GPG guide to setup keyring
  - https://docs.saltproject.io/en/latest/ref/renderers/all/salt.renderers.gpg.html
- Enable pillar caching on Salt master
- GPG encrypt a zip'd file
  - `gpg --armor -e -r 'key name' state_backup.zip`
- Set a grain called "secret" to that GPG encrypted value
- Populate pillars from the secret grain, (see below for example)
- Refresh pillars

```
# Salt master sample configuration
pillar_cache: False
pillar_cache_ttl: 3600
pillar_cache_backend: disk
```

```
# Sample pillar SLS file
#!jinja|yaml|gpg
secrets:
  {% if grains.secrets is iterable %}
  {% for secret, val in grains.secrets.items() %}
    {{ secret }}: |
      {{ val|indent(8) }}
  {% endfor %}
  {% endif %}
```

```
# Sample grains configuration on minion containing the armored output
secrets:
  itsasecret: |
      -----BEGIN PGP MESSAGE-----
      Version: GnuPG v2.0.22 (GNU/Linux)

      hQEMA9JfA30VpYBKAQgA1WY/yTymDVYGoRmDKTAGDc/nntVavPRXt0iksp6wQfUl
      b0cN70DtInG2+vt7gL248DQZbAH4MY+b3jheznuJFxnlYdNyGPjfntTYG/n8IbAN
      siMtXFA1VEz8gNTkPIjRfa+wPyUnGerYuG4faRo5AnSvZOx5TErZcy1I1wYQWrEF
      h8jebn9edDCgX5/kY2gKvn8jV/kQ3drLekVi3h5yjFFNoQaHBMnkJLnLUZyrWd7P
      dut4k+wof81nK+w/4BqhVZAkorOtuZrPkoa2ga6obASy4+8IY/vlR0/to7PnRUH/
      w3puCByJabFzd2rcP5fkmdrNQy7tORmG6e8ym1+/YtLCDQFKYRWKeiT2lHs/5z/Q
      /8xHB8zI4N9lGGDoAKBooT9PVwlbR4M+WC9y3hQPh1p3W6IPU5r66W2iXsjaV4Tm
      O5vw9NLUEXOz00mo9nOLHIepHMN5Wru6ub0Odp8s0e414bpuJJxN2iyNp7WefMmu
      +HAhlmfh9dAyyDr/Xfp0kWWQAtBlMzBfDRLgzVploZYrjHKnkZm2SgqNavdsrWwo
      ZiUaTA3ZbgKwX5/6PqaLrHUUyBK98t2pDmGikObukxfKXVYcVM/2tGjLixKsWEKO
      qJlA+lpnUVbM4N0IcAWu87YGlyiwmmIJeZawlym5nsimEJtNu2Gs717Mc8RyOEU/
      dYekwN/aAR7sG9bhXvBabchPHJUYQahiuLcgvpJCaQXUGBoDBs6EKmOPMTQo3h/i
      uqRLdOahr2gSh/MxnQJ0n3cqnMmdj3yqbnLhqoDX9TCQd3mMufdSeCLMsRQPd6Js
      J4XlLk9orCKJCs5VD5vJSbzIBODm35CgNuLbSmE5829PLWdDPZzziO2LGH6ILVrh
      YLGT2FM0tM8mLVVfKdgtS19f+4eOSxQbPVBRXpe1jIoKy+7DeG8CN8HbjthstQXZ
      Gk0mxvdZilhl48lmdSMyFPT9C46zVVu/XYpMN5Q8pqQ5jbYQvUV5DajbCQfkclaU
      vMpnpSJlTXBM5ILogwybhPSdyIJACTxUOJox+AdRFDZGGSKR3VHfJmo39sA5zVJr
      9SzwZN0W6Z2T6XXbObsPwtNY/5NRM99VUgUZBKaR2zliDYYZ2pv+f7T/D9Ng7wPv
      GuOkGrXJ1An+rZ51ynk9Rrs6anQqGSzYsMeiA7lhKxVG4owgmxxPolynuHnq/LBZ
      1zYu7SYVNK8zqFzAb2b/+GSjCC+Tv0y3cXM73iImrol0e7uaCFr6xaw1HmMaIa0f
      MV1b77JT25cLOoXDtipBbZNN+DXTn2953kxDJNLC8w==
      =lzOu
      -----END PGP MESSAGE-----
```

We have certain binary files that we encrypt with GPG and store the GPG armored output as a grain value. 

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
Report the key found, but with no value output since the value is binary.

**Screenshots**

**Versions Report**
<details><summary>
Salt Versions Report
</summary>
Salt Version:
          Salt: 3004

Dependency Versions:
          cffi: 1.15.0
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: 2.3.1
        PyYAML: 6.0
         PyZMQ: 17.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.49.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

</details>

**Comment by Bleala** [comment]
Same here, always getting an error, when i try to use gpg encrypted pillars

```
    Data failed to compile:
----------
    Rendering SLS 'base:ad' failed: could not find expected ':'; line 65

```

Although having `#!yaml|gpg` in top of my pillar file, testet with `ext_pillar; -gpg` in the salt master config, wastet a whole workday with this.

Without the gpg encryption i can't (shouldn't) sync my salt config through a git repo, so i need this too.

**Comment by doesitblend** [comment]
@Bleala I'm not sure that yours is the same issue as my own. Your issue reports what appears to be a syntax error in your data structure. Can you confirm that you are seeing the same traceback message as me? See the log snippet that I posted in the original description for the traceback message.

**Comment by dwoz** [comment]
@Ch3LL do you think that #61926 is a fix or just fixing a symptom of a larger problem?

**Comment by waynew** [comment]
@dwoz  It's definitely fixing _this particular_ problem -- there is a larger problem generally about consistency with bytes vs text, but... that's just a broad issue within Salt :sweat_smile:
