### ISSUE TITLE
[TECH DEBT] security@saltstack.com gpg key has expired

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#61834]
We need to update the gpg key here: https://docs.saltproject.io/en/latest/security/index.html#saltstack-security-announcements

**Comment by OrangeDog** [comment]
And set a better reminder / alert for the next expiry.

**Comment by ScriptAutomate** [comment]
- Regenerated a new key, and merged into `3006.x` branch/docs: https://github.com/saltstack/salt/pull/66642
- Will be closing this out once merge forwarded into `3007.x` and `master` branches

**Comment by ScriptAutomate** [comment]
- Updated in source repo for all branches
- Updated at both `SECURITY.md` in the root, and `doc/security/index.rst` on `3006.x`, `3007.x`, and `master` branches
- Published docs website is updated for `3006.9` and `master`
- `3007.2` release will include an update to the published `doc/security/index` document

Closing as completed.
