### ISSUE TITLE
[BUG] Jinja 3.1 moved Markup

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#61848]
**Description**
Jinja 3.1 was [released today](https://jinja.palletsprojects.com/en/3.1.x/changes/) and removed some previously deprecated code. At minimum, this breaks [this line](https://github.com/saltstack/salt/blob/master/salt/utils/jinja.py#L29) in `salt/utils/jinja.py` as `Markup` should now be imported from `MarkupSafe`:

```py
from jinja2 import BaseLoader, Markup, TemplateNotFound, nodes
```

The [base Jinja requirement is currently not pinned](https://github.com/saltstack/salt/blob/master/requirements/base.txt#L1), so we'll either need to require <3.1 or change the import and require >=3.1 (or narrow the pin even further).

**Comment by nicholasmhughes** [comment]
Oh, nice... it's breaking Actions on PRs: https://github.com/saltstack/salt/runs/5679196982?check_suite_focus=true

**Comment by jpic** [comment]
PR to pin jinja2 https://github.com/saltstack/salt/pull/61850
Will need to backport... ie. issue 3002.6 etc

**Comment by OrangeDog** [comment]
Or change the import to handle both locations and any version of Jinja...

**Comment by jpic** [comment]
Of course, but it might not be the only fix we need: https://github.com/pallets/jinja/issues?q=is%3Aissue+is%3Aclosed

I believe in the short term we need to have the saltstack bootstrap script to work again, even with older saltstack versions.

But also, new saltstack versions should support new jinja2 versions that's for sure.

**Comment by Ch3LL** [comment]
@jpic can you please open up an issue in the salt-bootstrap repo https://github.com/saltstack/salt-bootstrap with more details of how you are running into this issue with the bootstrap script install.

I have submitted #61856 to fix this issue in Salt.

**Comment by jpic** [comment]
There you go but I'm not sure what you want to change in salt-bootstrap ... Remove -U in pip install of requirements?
https://github.com/saltstack/salt-bootstrap/issues/1810

**Comment by Ch3LL** [comment]
Lets discuss in that issue

**Comment by blackliner** [comment]
This broke our CI bootstrapping procedure, any plans how/when this gets fixed? For now we use a user data script with `sudo pip install markupsafe==2.0.1 jinja2==3.0`

**Comment by MartinEmrich** [comment]
If Jinja2 came from the Saltstack RPM repository (here on EL7 or AL2), a pip3-installed version seems to be prioritized. after
````
pip3 uninstall markupsafe ; pip3 uninstall Jinja2
````
salt-minion works again. (but that might break whatever installed them via pip in the first place)
