### ISSUE TITLE
[TECH DEBT]How does Grains refer to the above variable appname

### ISSUE THREAD

**Issue by gezsops** [saltstack/salt#61884]
my sls:
{% for appname in ['appname1','appname2','appname3','appname4','appname5','appname6'] %}
{% if "xxxx" in grains[{{ appname }}] %}  
/tmp/conf.d/{{ appname }}.conf:
  file.managed:
    - source: salt://init/{{ appname }}.conf
    - template: jinja
    - mode: 0755
    - makedirs: True
{% else %}
echo_{{ appname }}:
  cmd.run:
    - name: echo "{{ appname }} is null."
{% endif %}
{% endfor %}

error:
 Data failed to compile:
----------
    Rendering SLS 'base:test.apptest' failed: Jinja syntax error: expected token ':', got '}'; line 2

---
{% for appname in ['appname1','appname2','appname3','appname4','appname5','appname6'] %}
{% if "xxxx" in grains[{{ appname }}] %}      <======================
/tmp/conf.d/{{ appname }}.conf:
  file.managed:
    - source: salt://init/{{ appname }}.conf
    - template: jinja
    - mode: 0755

**Comment by OrangeDog** [comment]
This question was answered on Slack.
https://saltstackcommunity.slack.com/archives/C7K04SEJC/p1648633807662359
