### ISSUE TITLE
[TECH DEBT] Missing 3001 release from Debian package archive

### ISSUE THREAD

**Issue by thehunmonkgroup** [saltstack/salt#61907]
### Description of the tech debt to be addressed, include links and screenshots

ERROR: E: The repository 'http://repo.saltstack.com/py3/debian/10/amd64/archive/3001.7 buster Release' no longer has a Release file.

Checking https://repo.saltproject.io/py3/debian/10/amd64/archive/, I don't see any 3001.x releases.

I understand that they may no longer be officially supported, but I'm unclear why these older packages cannot remain in the archive?

**Comment by frogunder** [comment]
They have been moved to archive repo and can be found here:

https://archive.repo.saltproject.io/py3/debian/10/amd64/archive/

**Comment by thehunmonkgroup** [comment]
Works, thanks!
