### ISSUE TITLE
[DOCS] Remove ubuntu 16.04 from 3002

### ISSUE THREAD

**Issue by frogunder** [saltstack/salt#61905]
**Description**
Ubuntu 16.04 is no longer supported but still present in the docs for 3002.

The install links for Ubuntu 16.04 are not valid (which is correct, they should not work anyway)

https://repo.saltproject.io/3002.html#ubuntu

If people want to use older ubuntu 16.04 packages (which is not recommended) they can be found here, latest version is 3002.7
https://archive.repo.saltproject.io/py3/ubuntu/16.04/amd64/archive/

**Suggested Fix**
Remove ubuntu 16.04 tab from repo landing page for 3002.

**Comment by mbochenk** [comment]
https://repo.saltproject.io/3003.html mentions that 16.04 will get packages for 3002.x

**Comment by pnickerson-cashstar** [comment]
3001 as well: https://repo.saltproject.io/3001.html#ubuntu
On that page, click "Ubuntu 16 (xenial) PY3", and you'll see instruction commands that utilize https://repo.saltproject.io/py3/ubuntu/16.04/...
That repo directory no longer exists.

**Comment by barbaricyawps** [comment]
This issue should now be resolved as both the 3001 and 3002 installation documentation is now archived. Closing.
