### ISSUE TITLE
Installation guide refers to deleted repos

### ISSUE THREAD

**Issue by duerrt** [saltstack/salt#61904]
**Description**
The installation page for SaltStack 3001 an Amazon Linux 2 shows an invalid URL for the repo file.

This url returns a 404 https://repo.saltproject.io/py3/amazon/2/x86_64/3001.repo
 

**Suggested Fix**
Update the url for the repo file to be:
https://archive.repo.saltproject.io/py3/amazon/2/x86_64/3001.repo
Or 
remove the 3001 release from the site since I don't think its being supported anymore.

**Type of documentation**
Installation instructions

**Location or format of documentation**
https://repo.saltproject.io/3001.html#amzn

**Additional context**

**Comment by OrangeDog** [comment]
Can you update the title to e.g. `[DOCS] Installation guide refers to deleted repos`?

**Comment by barbaricyawps** [comment]
This issue should now be resolved because the 3001 and 3002 install instructions have been archived now that these releases are no longer supported. Closing.
