### ISSUE TITLE
Saltstack 3004.1 Issue

### ISSUE THREAD

**Issue by MarkPageEgress** [saltstack/salt#61914]
### Description of Issue
Upgraded the salt master to 3004.1 since then we are experiencing authentication error has occurred across the Linux estate. 
Please note we do not define a user the daemon is running as root. No other changes were made, put the master into debug mode which generated the following:
 
![image](https://user-images.githubusercontent.com/102965793/161540102-8933551b-d075-402a-97f9-1b12939feb4b.png)

### Setup
(Please provide relevant configs and/or SLS files (Be sure to remove sensitive info).)
Unfortunately we work on a secure bastion environments i wont be able to get the configs but can be pointed in the right direction where to check. 

### Steps to Reproduce Issue
Simply execute a test.ping to the required minions from the master, note minions are not running the same version as master but should be cross compatible. 

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)

**Comment by doesitblend** [comment]
@MarkPageEgress Can you provide more information about how the job is being launched/executed?
