### ISSUE TITLE
[BUG] Ubuntu 18.04 py3 repo for v3001 has disappeared

### ISSUE THREAD

**Issue by biggreenogre** [saltstack/salt#61940]
**Description**
The repository of Ubuntu Bionic packages for release 3001 has vanished.

 **Setup**
Configure /etc/apt/sources.list.d/salt.list for URL https://repo.saltproject.io/py3/ubuntu/18.04/amd64/3001
- any machine requiring access to the Ubuntu Bionic 3001 repository\
  
**Steps to Reproduce the behavior**
apt-get cannot retrieve the repository files.

**Expected behavior**
Repository files can be retrieved and packages installed.

**Versions Report**
salt v3001 for Ubuntu Bionic

</details>

**Additional context**
The document at https://saltproject.io/salt-platform-support/ states that v3001 for Ubuntu 18.04 Bionic will be available until 31st December 2022

**Comment by OrangeDog** [comment]
#61900 All CVE-vulnerable and unsupported releases are moved to the archive site

**Comment by OrangeDog** [comment]
https://archive.repo.saltproject.io/py3/ubuntu/18.04/amd64/3001/

**Comment by biggreenogre** [comment]
Sorry, my psychic abilities to discern URLs seem to be failing.

**Comment by biggreenogre** [comment]
https://repo.saltproject.io/3001.html#ubuntu

**Comment by rjc** [comment]
> https://repo.saltproject.io/3001.html#ubuntu

Yup, still referenced there - please fix your web pages.

**Comment by OrangeDog** [comment]
#61905
