### ISSUE TITLE
[BUG] ImportError: cannot import name 'Markup' from 'jinja2' 

### ISSUE THREAD

**Issue by cdorsman** [saltstack/salt#61952]
**Description**
After fresh installation of Salt master with the bootstrap method and package method for Ubuntu, Salt master gives the error:

2022-04-14 21:34:26,464 [salt.log.setup   :910 ][ERROR   ][7338] An un-handled exception was caught by salt's global exception handler:
ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.8/dist-packages/jinja2/__init__.py)

Issue is presented with packages for Ubuntu 20.04 and bootstrap for all versions. 

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
Ubuntu 20.04 LTS 
Salt 3002, 3003.
Jinja2==3.1.1

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [Proxmox] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
Start an installation of Salt master on Ubuntu 20.04 LTS server.

**Expected behavior**
Salt master should be starting without any problems.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 
Salt 3002, 3003. 3004 

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by cdorsman** [comment]
This issue was already solved in the source code. But it is not released yet. Not relevant anymore.

**Comment by OrangeDog** [comment]
Duplicate: #61848
