### ISSUE TITLE
[BUG] Salt-minion 3004.1 with Jinja2 >=3.0

### ISSUE THREAD

**Issue by Ramshield** [saltstack/salt#61970]
**Description**
I run Salt-minion on a host with Homeassistant.
I ran into the issue where Homeassistant installed Jinja2 3.1.1:

```
Apr 19 23:42:03 homeassistant-01 salt-minion[4445]: ImportError: cannot import name 'Markup' from 'jinja2' (/usr/local/lib/python3.9/dist-packages/jinja2/__init__.py)
```
According to: https://github.com/pallets/jinja/pull/1544
I changed the following lines in https://github.com/saltstack/salt/blob/master/salt/utils/jinja.py
```
from jinja2 import BaseLoader, Markup, TemplateNotFound, nodes
```
To
```
from jinja2 import BaseLoader, TemplateNotFound, nodes
from jinja2.utils import markupsafe
markupsafe.Markup()
```

Then I ran into the following issue:
```
Apr 19 23:43:45 homeassistant-01 salt-minion[4487]: AttributeError: module 'jinja2' has no attribute 'contextfunction'
```
According to: https://github.com/pallets/jinja/pull/1544
I changed the following lines in https://github.com/saltstack/salt/blob/master/salt/utils/jinja.py:
Replacing `jinja2.contextfunctio` with `jinja2.pass_context` fixed this.

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [X] KVM

**Steps to Reproduce the behavior**
Install Jinja2 >=3.0 and restart salt-minion.

**Expected behavior**

**Screenshots**

**Versions Report**
# salt-minion --version
salt-minion 3004.1

```yaml
PASTE HERE
```
</details>

**Additional context**
Any advice if it's possible to upgrade to Jinja 3.1.X? Thanks!

**Comment by OrangeDog** [comment]
Duplicate: #61848

**Comment by Ramshield** [comment]
> Duplicate: #61848

Thank you! :)
