### ISSUE TITLE
[DOCS] Installation instructions still mention Ubuntu 16 (Xenial)

### ISSUE THREAD

**Issue by pnickerson-cashstar** [saltstack/salt#61985]
**Description**
The documentation page linked below says that packages for Ubuntu 16 (Xenial) are available in the SaltStack repository.

**Suggested Fix**
Ubuntu 16.04 has been removed from `repo.saltproject.io` and is no longer supported. It is available at `archive.repo.saltproject.io`, but I think this page is still misleading. So "Ubuntu 16 (Xenial)" should be removed from this page.

**Type of documentation**
Salt documentation regarding the Salt Repo.

**Location or format of documentation**
Installation > Platform-specific Installation Instructions > Ubuntu > Installation from the Official SaltStack Repository
https://docs.saltproject.io/en/latest/topics/installation/ubuntu.html

**Additional context**
I'm less sure about some side issues I noticed:
- Should "SaltStack" be changed to "Salt Project" on this page?
- The `sed` command may not work for Ubuntu 16.04 if you ran the bootstrap script (which now fails), as https://archive.repo.saltproject.io/py3/ubuntu/16.04/amd64/latest does not exist. https://archive.repo.saltproject.io/py3/ubuntu/16.04/amd64/3002 does exist though.

**Comment by rjc** [comment]
#61972

**Comment by barbaricyawps** [comment]
Closing as this is a duplicate issue. We're aware of it.

**Comment by barbaricyawps** [comment]
Actually, I want to double-check if it's a duplicate first. Re-opening for a bit.

**Comment by barbaricyawps** [comment]
Closing this issue as it's now resolved in the new Salt Install Guide: https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html
