### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by natxo** [saltstack/salt#62008]
**Description**
data module keys/values not returning the expected values

**Setup**
- [x ] container (Kubernetes, Docker, containerd, etc. please specify)
systemd-nspawn container on a fedora 35 laptop with latest saltstack

  
**Steps to Reproduce the behavior**
[root@saltmaster minion]# salt-call data.clear
local:
    True
[root@saltmaster minion]# salt-call data.load
local:
    ----------
[root@saltmaster minion]# salt-call data.update fw [port1,port2,port3]
local:
    True
[root@saltmaster minion]# salt-call data.load
local:
    ----------
    fw:
        - port1
        - port2
        - port3

so far, so good. But when I use other functions, I get no results:

[root@saltmaster minion]# salt-call data.keys
local:

when run with -l trace:
DEBUG   ] LazyLoaded data.keys
[DEBUG   ] LazyLoaded direct_call.execute
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'local': dict_keys(['fw'])}

# salt-call data.values -l trace
[DEBUG   ] Closing AsyncZeroMQReqChannel instance
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'local': dict_values([['port1', 'port2', 'port3']])}

but no output when running without additional logging:

# salt-call data.values
local:

**Expected behavior**
I expect to get the keys en the values when calling data.keys and data.values

**Versions Report**
Salt Version:
          Salt: 3004.1
 
Dependency Versions:
          cffi: 1.15.0
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.10.4 (main, Mar 25 2022, 00:00:00) [GCC 11.2.1 20220127 (Red Hat 11.2.1-9)]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.2.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: fedora 35 
        locale: utf-8
       machine: x86_64
       release: 5.17.4-200.fc35.x86_64
        system: Linux
       version: Fedora Linux 35

**Additional context**
Originally asked https://groups.google.com/g/salt-users/c/OGvWRH14r5s

**Comment by OrangeDog** [comment]
Duplicate: #61818
