### ISSUE TITLE
[BUG] Recent logging "regression": debug output appearing after the state output

### ISSUE THREAD

**Issue by myii** [saltstack/salt#62005]
**Description**

CC: @s0undt3ch, @ch3ll.

I've encountered a logging "regression" after the merge of #61629 -- using `git bisect`, I've traced it down to this commit specifically: a9d5e75b528b711412b8fa30eb61c54413a254e9.

The issue occurs when using `-l debug`; while it is encountered with any state run (`state.highstate` or `state.apply`), the problem is far more noticeable when there are failures.  Compare these two runs across week 15 (before) and week 16 (after):

* W15: https://gitlab.com/myii/syslog-ng-formula/-/jobs/2318170468
* W16: https://gitlab.com/myii/syslog-ng-formula/-/jobs/2346448239

In the older run, the state output is available right at the bottom.  In the newer run, the state output is present but you have to scroll up a long way to get to it.

For clarity, this is the block that is usually displayed right at the bottom:

```sls
       Total states run:     4
       Total run time:  52.940 s
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
```

However, we've now got ~1,000 lines of debug output showing between the
`Total run time:` and `>>>>>> ------Exception-------` lines, making it very difficult to work with the CI logs.

This isn't limited to Kitchen CI; while performing the `git bisect` on my development installation of Salt, I was able to reproduce this problem by simply calling:

```console
$ salt -c local/etc/salt <minion> state.sls <formula> -l debug
```

**Setup**
Any `state.highstate` or `state.apply` using the `master` branch of Salt, with debug logging enabled (`-l debug`).

- [X] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [X] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

**Steps to Reproduce the behavior**
Any `state.highstate` or `state.apply` using the `master` branch of Salt, with debug logging enabled (`-l debug`).

**Expected behavior**
The extra debugging lines should not be displayed after the state output.

**Versions Report**
Any `master` branch installation of Salt.

**Comment by myii** [comment]
@s0undt3ch @Ch3LL Thanks for the fix, all looking OK again after rebuilding our images.  So taking the examples given above, this is the same failing run with the rebuilt image:

* https://gitlab.com/myii/syslog-ng-formula/-/jobs/2425489670

**Comment by s0undt3ch** [comment]
And the output looks in correct order. Awesome!
