### ISSUE TITLE
salt logging aggregator

### ISSUE THREAD

**Issue by nri-pl** [saltstack/salt#6202]
Hi,

I don't know if the feature was discussed or not, but ...
I'd love to see something like https://pypi.python.org/pypi/ScribeHandler in Salt.

eg:

import logging
import salt
mylogger = logging.getLogger('SaltLoggingHandler')
mylogger.setLevel(logging.DEBUG)
handler = salt.SaltLoggingHandler(category='%(hostname)s-%(levelname)s')
mylogger.addHandler(handler)
mylogger.debug('stuff happens')

Of course SaltLoggingHandler should send logs using ZMQ socket to the minion on the local machine.
Then minion should send logs to the master and there should be collected. The whole should be Internet connection fault tolerant, etc.

It would be ideal to have the ability to view logs to real-time on master.

Maybe someone has done something like this?
I would like to replace https://github.com/facebook/scribe

**Comment by arroyoc** [comment]
@DDarko @s0undt3ch I am closing this ticket due to inactivity. If anyone feels that this feature needs more attention feel free to reopen.

**Comment by basepi** [comment]
I still would really like to see this implemented, so I've re-opened it.

**Comment by vim-zz** [comment]
to me it would be highly valuable if i can stream a log file (e.g. tail -f) for a single minion for debugging over the existing salt infrastructure
