### ISSUE TITLE
[DOCS] please update the salt installation page for Debian 10, salt version 3001

### ISSUE THREAD

**Issue by GudaboinaSuhas** [saltstack/salt#62038]
**Description**

Salt installation document needs to be updated for version 3001, Debian 10. The commands provided for importing the repository key needs to be updated to use archive.repo.saltproject.io instead of repo.saltproject.io.

![image](https://user-images.githubusercontent.com/16036702/167379532-f61e31f3-9046-4db2-8c32-a2e45c2be6ea.png)

![image](https://user-images.githubusercontent.com/16036702/167379755-bf1787da-8d6e-4cbd-b319-9a8749014a1c.png)

**Location or format of documentation**
https://repo.saltproject.io/3001.html#debian

**Comment by OrangeDog** [comment]
Duplicate: #61904
