### ISSUE TITLE
[TEST FAILURE] tests.pytests.integration.modules.test_mysql failing on Amazon Linux 2

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#62071]
The mysql integration tests are failing consistently  on amazon linux 2:

[tests.pytests.integration.modules.test_mysql.test_create_alter_password_hash[container=mysql/mysql-server:5.7]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_create_alter_password_hash_container_mysql_mysql_server_5_7_/)
[tests.pytests.integration.modules.test_mysql.test_query[container=mysql/mysql-server:8.0]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_query_container_mysql_mysql_server_8_0_/)
[tests.pytests.integration.modules.test_mysql.test_grant_add_revoke[container=mysql/mysql-server:8.0]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_grant_add_revoke_container_mysql_mysql_server_8_0_/)
[tests.pytests.integration.modules.test_mysql.test_plugin_add_status_remove[container=mysql/mysql-server:8.0]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_plugin_add_status_remove_container_mysql_mysql_server_8_0_/)
[tests.pytests.integration.modules.test_mysql.test_plugin_list[container=mysql/mysql-server:8.0]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_plugin_list_container_mysql_mysql_server_8_0_/)
[tests.pytests.integration.modules.test_mysql.test_grant_add_revoke_password_hash[container=mysql/mysql-server:8.0]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_grant_add_revoke_password_hash_container_mysql_mysql_server_8_0_/)
[tests.pytests.integration.modules.test_mysql.test_create_alter_password_hash[container=mysql/mysql-server:8.0]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_create_alter_password_hash_container_mysql_mysql_server_8_0_/)
[tests.pytests.integration.modules.test_mysql.test_grant_add_revoke[container=percona:5.6]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_grant_add_revoke_container_percona_5_6_/)
[tests.pytests.integration.modules.test_mysql.test_grant_add_revoke_password_hash[container=percona:5.6]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_grant_add_revoke_password_hash_container_percona_5_6_/)
[tests.pytests.integration.modules.test_mysql.test_create_alter_password_hash[container=percona:5.6]](https://jenkins.saltproject.io/job/pr-amazon-2-x86_64-py3-pytest/job/master/1375/testReport/junit/tests.pytests.integration.modules/test_mysql/test_create_alter_password_hash_container_percona_5_6_/)

**Comment by nicholasmhughes** [comment]
Also seeing some potentially related failures on **pr-centos-7-x86_64-py3-pycryptodome-pytest**. See [PR 62069](https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-pycryptodome-pytest/job/PR-62069/2/) for details.

[tests.pytests.integration.states.test_mysql.test_database_present_absent[container=mariadb:10.1]](https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-pycryptodome-pytest/job/PR-62069/2/testReport/junit/tests.pytests.integration.states/test_mysql/test_database_present_absent_container_mariadb_10_1_/)
[tests.pytests.integration.states.test_mysql.test_grants_present_absent[container=mariadb:10.1]](https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-pycryptodome-pytest/job/PR-62069/2/testReport/junit/tests.pytests.integration.states/test_mysql/test_grants_present_absent_container_mariadb_10_1_/)
[tests.pytests.integration.states.test_mysql.test_user_present_absent[container=mariadb:10.1]](https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-pycryptodome-pytest/job/PR-62069/2/testReport/junit/tests.pytests.integration.states/test_mysql/test_user_present_absent_container_mariadb_10_1_/)
[tests.pytests.integration.states.test_mysql.test_user_present_absent_passwordless[container=mariadb:10.1]](https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-pycryptodome-pytest/job/PR-62069/2/testReport/junit/tests.pytests.integration.states/test_mysql/test_user_present_absent_passwordless_container_mariadb_10_1_/)
[tests.pytests.integration.states.test_mysql.test_user_present_absent_unixsocket[container=mariadb:10.1]](https://jenkins.saltproject.io/job/pr-centos-7-x86_64-py3-pycryptodome-pytest/job/PR-62069/2/testReport/junit/tests.pytests.integration.states/test_mysql/test_user_present_absent_unixsocket_container_mariadb_10_1_/)
