### ISSUE TITLE
[BUG] saltify driver still expects Impacket

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#62101]
**Description**
within the documentation at https://docs.saltproject.io/en/latest/topics/cloud/windows.html we say that impacket is depreciated in 3001. however the saltify cloud driver still requires this package. and will not deploy if it is not installed.  

**Setup**
https://github.com/saltstack/salt/blob/master/salt/cloud/clouds/saltify.py#L343-L345
for more info.

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
Try to use the saltify cloud driver on a system that doesn't have impacket

**Expected behavior**
salt-cloud uses alternatives instead of failing.

**Comment by xeacott** [comment]
Technically a regression since this caused new failures on salt-master service startup (as of python3.9 and impacket==0.10.0) which haven't been caused before. This became an issue for SSE.

**Comment by Philip-A-Fry** [comment]
This is still an issue in Salt 3005.3 (with Aria Automation Config).

**Comment by whytewolf** [comment]
> This is still an issue in Salt 3005.3 (with Aria Automation Config).

3005.x is CVE only branch. bug fixes will not be released for it. this fix went into 3006.x
