### ISSUE TITLE
[BUG] Salt version on head of master returning 3003rc1

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#62135]
The salt version on head of master is returning 3003rc1+2349.g87f6189e58 

This should be including the 3004 tag instead.

**Comment by MKLeb** [comment]
This stems from the fact that we now tag on a separate branch, and do not merge the final tag back over to master, thus `git describe ...` does not return the correct tag past `v3003rc1`.  We should maybe look into merging the tag back onto master if we end up making changes after the initial tag.  Running the following on the master branch gives the expected output of `v3004-<num commits after v3440 tag>-<commit-sha>` (merging with `-X theirs` to avoid many conflicts locally)...
```
git fetch --tags --all
git merge -X theirs v3004
```
