### ISSUE TITLE
[BUG] file.append: UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 

### ISSUE THREAD

**Issue by PacGyver** [saltstack/salt#62161]
**Description**
I use the file.append module to add a line to a file. A Windows minion reports the following error: 

                File "C:\Program Files\Salt Project\Salt\bin\Lib\site-packages\salt-3004.1-py3.8.egg\salt\states\file.py", line 6225, in append
                  nlines = nlines.decode(__salt_system_encoding__)
                File "c:\Program Files\Salt Project\Salt\bin\lib\encodings\cp1252.py", line 15, in decode
                  return codecs.charmap_decode(input,errors,decoding_table)
              UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 1987: character maps to <undefined>

**Setup**
Linux Salt Master: Debian 10.12 with Docker Image "saltstack/salt"
salt 3004.1

Windows Minion 3004.1-1

***Testfile on Windows Minion***
 Content:
```
Ã
```

**Steps to Reproduce the behavior**
state.apply

**Expected behavior**
Line "LocalConsent=64" is appended

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
3004.1

```yaml
file.append:
    - name: 'c:\testfile'
    - text: 'LocalConsent=64'
```
</details>

**Additional context**
Notepad++ shows the Windows Files as UTF-8 encoded. If I change the line 122 in salt\__init__.py from
    setattr(builtins, "__salt_system_encoding__", encoding)
to
    setattr(builtins, "__salt_system_encoding__", "mbcs")
or to
    setattr(builtins, "__salt_system_encoding__", "utf-8")
everything works as expected.

**Comment by twangboy** [comment]
I cannot replicate this issue on 3006.7. If you can replicate this on a later version of Salt, please open a new issue and provide detailed steps on how to reproduce this issue.
