### ISSUE TITLE
[DOCS] 404 when downloading Windows Minion

### ISSUE THREAD

**Issue by insy** [saltstack/salt#62231]
**Description**
Link to download last versions of Salt for Windows are broken (NoSuchKey).

**Suggested Fix**
Wrong filenames, eg: Salt-Minion-3004.2-Py3-AMD64-Setup.exe -> Salt-Minion-3004.2-1-Py3-AMD64-Setup.exe

**Type of documentation**
Installation guide

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/installation/windows.html

**Additional context**
Complete HTTP error:
```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>windows/Salt-Minion-3004.2-Py3-AMD64-Setup.exe</Key>
<RequestId>R5HZEE8506G1BCDB</RequestId>
<HostId>EHi60mlJf8xn1varX8Db1z7kbqFXGidjsKpPSplMJiZVnEhXBX0jXHozSXoYwHxvO8dakzXMGHY=</HostId>
</Error>
```

**Comment by barbaricyawps** [comment]
Hello! This documentation is being deprecated for the 3005 release in favor of the new Salt Install Guide that will be released along with 3005. For that reason, I'm closing this issue. You can preview the new documentation and provide early feedback at: https://docs.saltproject.io/salt/install-guide/en/latest/
