### ISSUE TITLE
Community feedback needed on new Salt Install Guide

### ISSUE THREAD

**Issue by barbaricyawps** [saltstack/salt#62244]
Welcome, Salt community members! :wave: :sparkles: :smile:

If you'd like to leave feedback on the draft for the new [Salt Install Guide](https://docs.saltproject.io/salt/install-guide/en/latest/index.html), this is the right place to do that! Please leave your feedback for improvement on this issue.

## :question: What is the new Salt Install Guide and why do we need it?
The Salt Docs team created the new install guide for a few important reasons:

- :tada: **To improve the installation process.** We wanted to improve the install documentation to make it quickly and easily install Salt. Since, it's your first experience with Salt, we want it to be a positive one!
- :clap: **Our installation process is changing for the better, thanks to the new onedir system.** With the upcoming release of Salt 3005 (Phosphorus), we will begin releasing onedir packages of Salt. Onedir is an improved installation process that installs the core Salt dependencies and the version of Python that Salt needs. With this new packaging system and process, we wanted to also unroll an improved installation guide to accompany it. See [Upgrade to onedir](https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html) for more information about onedir packaging that is forthcoming in 3005.
- :zap: **To make Salt more secure.** It's a security risk to have your install instructions on the same domain as your packages for GPG key verification purposes. We needed to move the installation instructions to a separate website so that if repo.saltproject.io were compromised, they couldn't also update the installation instructions to show a different GPG key fingerprint. See [Salt Issue 59421](https://github.com/saltstack/salt/issues/59421) for more information about this security risk.

## :exclamation: Before you start leaving comments...
Keep a few things in mind as you leave your comments:

- Try to keep your comments restricted to the documentation itself and not the actual installation process. You can leave comments about the installation process, but just be aware the Salt Docs Team can only take action on the documentation, not the installation process itself. The best we can do is pass along the suggestions.
- If possible, indicate whether your comment is **blocking** or **not-blocking.** Blocking comments are reserved for a serious problem in the guide that needs to be resolved before the official docs release. Non-blocking comments are for suggestions for improvement that are not urgent and can be resolved later, such as nice-to-have requests.
- We're huge fans of the [Conventional Comments](https://conventionalcomments.org/) method of giving draft comments if you'd like to use that. (Purely optional, but super nice!)

**Comment by OrangeDog** [comment]
- where is the new draft?
- if this were a PR then we could leave and track comments in-line

**Comment by barbaricyawps** [comment]
Thanks for your comments. You can view the draft here (link was also in the original issue description): https://docs.saltproject.io/salt/install-guide/en/latest/

It would be impossible to create an entire installation guide in one long PR, let alone a nightmare to review. Therefore, so many of the changes have already been merged in piece-by-piece to create the initial guide. But you can open issues or your own merge requests in the repo for the guide: https://gitlab.com/saltstack/open/docs/salt-install-guide

**Comment by OrangeDog** [comment]
I've not looked at everything yet, but here's first thoughts:

### Install Salt
- "Salt-supported" should be hyphenated, or just say "supported"
- First mention of Tiamat (in the Warning box) should be hyperlinked to some sort of explanation
- Sidebar should be in the same order as the overview
- In general a bunch of "X and Y" titles link to "Y and X" pages.
- You do not need to install Salt dependencies if you're using a non-Tiamat package either
- Step 5 is the minion config, so should link direct to the minion config
- Step 5 disagrees with the config it links to - one says add the master IP to config, the other says use DNS/hostname lookup
- Question: why start the minions before the master?
- Salt SSH is not masterless! Masterless minions are completely separate, and not mentioned at all.
- "Send and receive commands from minions that can’t run the standard salt-minion service" would also include Salt SSH as a solution
- salt-call (not capitalised) would be used for a masterless setup, but "Run commands locally" is a standard thing you can do, not an alternative installation

### Salt supported operating systems
- "Testing support" should be explained, same as the other columns

**Comment by barbaricyawps** [comment]
Re: announcements, the CVE release occurred while I was on PTO and I only just now merged in a fix for that. Patience, young grasshopper.

**Comment by nicholasmhughes** [comment]
> * Salt SSH is not masterless! Masterless installation and configuration is a separate thing (**blocking**)

Echoing this concern. The "agentless" type can still be retained here. Masterless would look something like what's outlined in [this post](https://eitr.tech/blog/2021/11/12/salt-masterless.html).

**Comment by TheBigBear** [comment]
So can you clarify in the docs somewhere if with the 3005 release and Tiamat (=python always included) the salt-ssh is now starting to work against and with windows salt-ssh minions?

**Comment by cachedout** [comment]
@barbaricyawps There was a [long Slack thread about this](https://saltstackcommunity.slack.com/archives/C8E7RJCPN/p1658844657525899) and I'll summarize the main point below: 

It is not clear what, if any, actions a user should take when upgrading from a non-Timat package to a Timat one. There was previously talk about [an upgrade tool ](https://github.com/saltstack/salt/issues/62361) but it's not clear if that was implemented or not. Either instructions on the use of the tool need to be included, or an explanation of which manual steps might be needed is critically important.

**Comment by barbaricyawps** [comment]
FYI, the name "Tiamat" has been changed to "onedir."  The core team discussed this topic at length and decided that it was more accurate and descriptive to refer to these packages as `onedir` rather than refering them to `tiamat`.  This gives us a clear distinction between the new `onedir` packages and the classic packages by focusing on the concept used to build them rather than the tool used to build them.

**Comment by barbaricyawps** [comment]
Thanks to everyone who has left feedback so far. I have a new MR that implements some of these changes: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/35

I am still working with a few subject matter experts to make improvements to the onedir upgrade instructions and will have those in soon.

**Comment by barbaricyawps** [comment]
Thanks to everyone who provided feedback on this issue. The Salt Install Guide is now released and if you notice any additional problems or issues, please feel free to join the #documentation channel on our Slack workspace to let me know about them or open issues in the Salt Install Guide repo going forward: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues
