### ISSUE TITLE
[BUG] pkg.version_cmp on openEuler systems fails

### ISSUE THREAD

**Issue by raulillo82** [saltstack/salt#62248]
**Description**
Runnig pkg.version_cmp on openEuler systems fails 

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Salt master is a uyuni server, latest available version (based on opensuse 15.4). Salt minion is an openEuler 22.03 LTS with latest patches.

- [ ] on-prem machine
- [X] VM (KVM)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD

  
**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)
```
uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1916, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/minion.py", line 1873, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/venv.py", line 24, in execute
        return __executors__["direct_call.execute"](opts, data, func, args, kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1203, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 1218, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/venv-salt-minion/lib/python3.10/site-packages/salt/modules/yumpkg.py", line 685, in version_cmp
        return __salt__["lowpkg.version_cmp"](pkg1, pkg2, ignore_epoch=ignore_epoch)
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/context.py", line 78, in __getitem__
        return self.value()[item]
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/loader/lazy.py", line 334, in __getitem__
        super().__getitem__(item)  # try to get the item from the dictionary
      File "/usr/lib/venv-salt-minion/lib64/python3.10/site-packages/salt/utils/lazy.py", line 105, in __getitem__
        raise KeyError(key)
    KeyError: 'lowpkg.version_cmp'
ERROR: Minions returned with non-zero exit code

uyuni:~ # salt '192*' grains.get os_family
192.168.122.173:
    openEuler
```

**Expected behavior**
A basic patch fixes the issue (will be added in a PR soon). When running the same command again with the patch, this is the output:

```
uyuni:~ # salt '192*' pkg.version_cmp 4.10.0-3.oe2203 4
192.168.122.173:
    1
```

**Screenshots**
Console output will act as screenshot.

**Versions Report**
Master:
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
uyuni:~ # salt --versions-report
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.3.0
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 1.7.0
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: opensuse-leap 15.4 
        locale: UTF-8
       machine: x86_64
       release: 5.14.21-150400.22-default
        system: Linux
       version: openSUSE Leap 15.4 
```
</details>

Minion:
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
[root@openeuler ~]# venv-salt-call --versions-report
Salt Version:
          Salt: 3004
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: 4.2.0
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.10.2 (main, Mar 01 2022, 07:23:53) [GCC]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.2.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: openeuler 22.03 
        locale: utf-8
       machine: x86_64
       release: 5.10.0-60.18.0.50.oe2203.x86_64
        system: Linux
       version: openEuler 22.03 

```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
Should `os_family` be RedHat then, as it's a CentOS fork? I'm assuming it still uses `dnf`/`yum`?

Related: #57490

**Comment by raulillo82** [comment]
> Should `os_family` be RedHat then, as it's a CentOS fork? I'm assuming it still uses `dnf`/`yum`?
> 
> Related: #57490

No, os_family is openeuler, see:
```
uyuni:~ # salt '192*' grains.get os_family
192.168.122.173:
    openEuler
```
It does use dnf/yum.

**Comment by OrangeDog** [comment]
Yes, I can see it says openEuler. I suspect that it shouldn't be.
What else is in the openEuler family? As ultimately a fork of RedHat EL, why should it not be in the RedHat family?

**Comment by raulillo82** [comment]
> Yes, I can see it says openEuler. I suspect that it shouldn't. What else is in the openEuler family? As ultimately a fork of RedHat EL, why should it not be in the RedHat family? Are any of the fundamentals of managing the OS different to RHEL/CentOS?

I'm afraid I don't have a clue, and I'm not even a regular developer to be of much help, doing my best to contribute (and hopefully start doing it more often). The fix is very small (see related PR) and it's actually simply copying from another fix in which the same line in another file had to be changed...

Hopefully someone else can shed some more light. @juliogonzalez maybe you know something else?

**Comment by juliogonzalez** [comment]
@OrangeDog: AFAIK it a fork of RHEL8, but in some cases so different, that I don't know if it should qualify as "family".

If the only condition for being RedHat is that it uses yum/dnf, then I guess it should be RedHat.

But keep in mind that, IMHO, this is distro only has dnf in common, because:

- There are no modules, no appstreams, or anything like similar.
- Newer versions of core libraries if you compare it gainst RHEL
- AFAIK it's not even compatible with EPEL, unlike other forks (they have their own `EPOL` repository)

So I guess that's was the reason to create a separate  family, for whoever implemented the initial support.

But not sure if @vzhestkov, @meaksh, @agraul or any other of our Salt developers for SUSE have any opinion about this?

**Comment by agraul** [comment]
> @OrangeDog: AFAIK it is a fork of RHEL8, but in some cases so different, that I don't know if it should qualify as "family".
> 

Without looking into this deeply, I'm inclined to say it still belongs to the RH family.

> If the only condition for being RedHat is that it uses yum/dnf, then I guess it should be RedHat.
> 
> But keep in mind that, IMHO, this is distro only has dnf in common, because:
> 
>     * There are no modules, no appstreams, or anything like similar.

Isn't that the same for e.g. CentOS 7 or Fedora?

>     * Newer versions of core libraries if you compare it gainst RHEL
> 

There is no single version of core libraries across the RedHat OS *family*, which includes RHEL 7 as well as Fedora 35.

>     * AFAIK it's not even compatible with EPEL, unlike other forks (they have their own `EPOL` repository)
> 

Is EPEL more than a repository? Not all OSes belonging to a family of OSes need to have the same repo layout.

> 
> So I guess that's was the reason to create a separate family, for whoever implemented the initial support.
> 
IMO the initial support took the wrong approach in https://github.com/saltstack/salt/pull/58973/files. I think adding an entry to https://github.com/saltstack/salt/blob/master/salt/grains/core.py#L1592 would have been better.

**Comment by juliogonzalez** [comment]
> > @OrangeDog: AFAIK it is a fork of RHEL8, but in some cases so different, that I don't know if it should qualify as "family".
> 
> Without looking into this deeply, I'm inclined to say it still belongs to the RH family.
> 
> > If the only condition for being RedHat is that it uses yum/dnf, then I guess it should be RedHat.
> > But keep in mind that, IMHO, this is distro only has dnf in common, because:
> > ```
> > * There are no modules, no appstreams, or anything like similar.
> > ```
> 
> Isn't that the same for e.g. CentOS 7 or Fedora?
> 
> > ```
> > * Newer versions of core libraries if you compare it gainst RHEL
> > ```
> 
> There is no single version of core libraries across the RedHat OS _family_, which includes RHEL 7 as well as Fedora 35.
> 
> > ```
> > * AFAIK it's not even compatible with EPEL, unlike other forks (they have their own `EPOL` repository)
> > ```
> 
> Is EPEL more than a repository? Not all OSes belonging to a family of OSes need to have the same repo layout.
> 
> > So I guess that's was the reason to create a separate family, for whoever implemented the initial support.
> 
> IMO the initial support took the wrong approach in https://github.com/saltstack/salt/pull/58973/files. I think adding an entry to https://github.com/saltstack/salt/blob/master/salt/grains/core.py#L1592 would have been better.

FIne by me if this is declared as RHEL family, but... what about retrocompatibility? Anyone using already salt for openEuler could be using the family, so if it's now suddenly changed, it will break stuff.

One example would be Uyuni if we now merge the support for openEuler (it's ready).

**Comment by OrangeDog** [comment]
> what about retrocompatibility?

openEuler is not officially supported by Salt, so there's no guarantees of compatibility anyway.
IMO this is fixing a bug. People who rely on incorrect behaviour unfortunately will have to make adjustments.

**Comment by garethgreenaway** [comment]
Repeating my comment from the PR, taking a quick look at an openEuler system it does appear to use and have similar tools to Red Hat / CentOS systems but is different enough that it should be considered it's own `os_family.`
