### ISSUE TITLE
Support for RHEL 9 in Saltstack

### ISSUE THREAD

**Issue by infantvin** [saltstack/salt#62270]
### Description of Issue
Need a status/roadmap of saltstack on RHEL 9 which has been released

Redhat has recently released Redhat Enterprise Linux 9

https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/9

Can you please let us know when saltstack will support RHEL9 for both master and minion?
If you have any timelines or versions for this please let us know as we plan to start using RHEL9 more actively in our Build/Dev environment which is managed by saltstack

Thanks

**Comment by OrangeDog** [comment]
According to [this draft documentation](https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-supported-operating-systems.html) it should be supported in the next release (3005).

**Comment by barbaricyawps** [comment]
Correct, it should be supported in 3005. Closing this issue.

**Comment by dennixxNL** [comment]
I see 3005 has been released, but I don't see any RHEL9 packages in the repository. Am I missing something?

**Comment by OrangeDog** [comment]
New OSes only get the onedir packages, from a new set of repos.

https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/rhel.html#install-onedir-packages-of-salt-on-redhat-rhel-9

**Comment by infantvin** [comment]
Many thanks.

We are planning for a test of the new salt version before we upgrade the systems we use daily.

I will visit this and check against the list of systems we have in our environment here.

Thanks for taking the time to update this as it is very useful for us.


  *   Infant

________________________________

**Comment by dennixxNL** [comment]
> New OSes only get the onedir packages, from a new set of repos.
> 
> https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/rhel.html#install-onedir-packages-of-salt-on-redhat-rhel-9

So yes I was missing something ;-) , thanks!

**Comment by infantvin** [comment]
Thank you

Do we have any RC packages for 3005 for us to test?

It would be nice if there were any for us to try. Please let us know.

- Infant

**Comment by OrangeDog** [comment]
@infantvin 3005 was released last month, and 3005.1 is already available.

**Comment by infantvin** [comment]
Hi James

Yes we are trying to find the time to test our states on the new major release and upgrade in sometime.
RHEL9 is needed to be used and we need the new version to use RHEL9 minions and master.

Thanks


  *   Infant

________________________________
