### ISSUE TITLE
salt-ssh gpg NO_SECKEY

### ISSUE THREAD

**Issue by dtzampanakis** [saltstack/salt#62296]
### Description of Issue
Master python3 --version Python 3.9.5
Target python3 --version Python 3.9.10

Updated salt-ssh to 3004.2 after using 3002.2 for years. 
When i try to apply a state(that previous worked) i have some warnings like 
`Could not decrypt cipher b'-----BEGIN PGP MESSAGE-----\n\nhQGMA5SEUz9/mRZgAQwAtxV0wHfl3PSYYL5P4J33t6tr1vuTsYy0y11CuMdasszQ\nNlQO8I9rntsRGE+8+m/qg0LVT347WIfs8m7XTCTK+SI=\n=AYGI\n-----END PGP MESSAGE-----', received: b"gpg: keyblock resource '/tmp/salt-thin/gpgkeys/pubring.kbx': No such file or directory\n[GNUPG:] ERROR add_keyblock_resource 33587281\n[GNUPG:] ENC_TO 9484533F7F991660 1 0\n[GNUPG:] ERROR keydb_search 33554445\n[GNUPG:] ERROR keydb_search 33554445\ngpg: encrypted with RSA key, ID 9484533F7F991660\n[GNUPG:] NO_SECKEY 9484533F7F991660\n[GNUPG:] BEGIN_DECRYPTION\n[GNUPG:] DECRYPTION_FAILED\ngpg: decryption failed: No secret key\n[GNUPG:] END_DECRYPTION\n"`

and 
  ```
File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 890, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.scanner.ScannerError: while scanning a simple key
  in "<unicode string>", line 109, column 1
could not find expected ':'
  in "<unicode string>", line 110, column 1
  
  {% load_yaml as locations %}
{%- import_text "servers/{0}.sls".format(grains.environment) as location_data  with context %}
{%- set location_data = salt.slsutil.renderer(string=location_data, default_renderer='yaml|gpg') %}    <======================

{{grains.environment}}:
  {{location_data.location}}


[...]
---
[CRITICAL] Rendering SLS 'servers' failed, render error:
```

The strange thing is that when i use 
salt-ssh 'stest8' pillar.items i get them correct. 

i rem

### Versions Report
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.3
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: 1.4.4
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.9.5 (default, Nov 18 2021, 16:00:48)
  python-gnupg: 0.4.6
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 21.04 hirsute
        locale: utf-8
       machine: x86_64
       release: 5.11.0-49-generic
        system: Linux
       version: Ubuntu 21.04 hirsute

**Comment by OrangeDog** [comment]
Duplicate: #60002
