### ISSUE TITLE
[BUG] salt command missing from salt-minion tiamat package

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#62358]
**Description**
The Tiamat documentation refers to using the salt command to install addition Python packages via PIP, but the salt command is not available.
 
**Steps to Reproduce the behavior**
Install the 3005 RC1 TIamat packages.

**Comment by OrangeDog** [comment]
Isn't it `salt-pip`, not `salt`?

**Comment by garethgreenaway** [comment]
@OrangeDog The documentation mentions using `salt` which is only available on the Master, `salt-pip` appears to be available with both.  This issue can be resolved by updating the documentation.
