### ISSUE TITLE
[BUG] telnetlib missing from Tiamat package

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#62362]
**Description**
telnetlib missing from Tiamat package

**Setup**
Install 3005 RC1 Timat packages
Run /usr/local/bin/salt/run/run shell
Attempt to import telnetlib

```
>>> import telnetlib
Traceback (most recent call last):
  File "code.py", line 90, in runcode
  File "<console>", line 1, in <module>
ModuleNotFoundError: No module named 'telnetlib
```

**Comment by garethgreenaway** [comment]
That deprecation happened in 3.11 I believe and we're building the Tiamat packages with 3.9, various libraries that are used by the Salt proxy minions such as netmiko rely on this.

**Comment by s0undt3ch** [comment]
This will be fixed either on a following RC for 3005 or the final release

**Comment by Ch3LL** [comment]
Re-opening due to windows failures.
