### ISSUE TITLE
require_in overrides excludes

### ISSUE THREAD

**Issue by josmardias** [saltstack/salt#6237]
I'm using Fedora 19

```
$ salt --versions-report
           Salt: 0.15.3
         Python: 2.7.5 (default, Jul  8 2013, 09:48:59)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.6
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.3

```

State:

```
test1:
  file.managed:
    - name: /tmp/nothing

test2:
  file.managed:
    - name: /tmp/nothing2
    - require:
      - file: test1

exclude:
  - id: test1
```

Output

```
$ sudo salt-call state.highstate
[INFO    ] Configuration file path: /etc/salt/minion
[INFO    ] Executing command 'ps -efH' in directory '/root'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file 'salt://top.sls'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/modules'
[INFO    ] Syncing modules for environment 'base'
[INFO    ] Loading cache from salt://_modules, for base)
[INFO    ] Caching directory '_modules/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/states'
[INFO    ] Syncing states for environment 'base'
[INFO    ] Loading cache from salt://_states, for base)
[INFO    ] Caching directory '_states/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/grains'
[INFO    ] Syncing grains for environment 'base'
[INFO    ] Loading cache from salt://_grains, for base)
[INFO    ] Caching directory '_grains/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/renderers'
[INFO    ] Syncing renderers for environment 'base'
[INFO    ] Loading cache from salt://_renderers, for base)
[INFO    ] Caching directory '_renderers/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/returners'
[INFO    ] Syncing returners for environment 'base'
[INFO    ] Loading cache from salt://_returners, for base)
[INFO    ] Caching directory '_returners/' for environment 'base'
[INFO    ] Creating module dir '/var/cache/salt/minion/extmods/outputters'
[INFO    ] Syncing outputters for environment 'base'
[INFO    ] Loading cache from salt://_outputters, for base)
[INFO    ] Caching directory '_outputters/' for environment 'base'
[INFO    ] Loading fresh modules for state activity
[INFO    ] Fetching file 'salt://test.sls'
local:
----------
    State: - file
    Name:      /tmp/nothing2
    Function:  managed
        Result:    False
        Comment:   The following requisites were not found:
                   require: {'file': 'test1'}

        Changes:    
```

**Comment by elxwill** [comment]
Was this bug ever fixed? I'm experiencing it now with the below salt --versions-report:

gesadmin@ny5kmduatinit01:~ $ salt --versions-report
Salt Version:
           Salt: 2015.8.8.2
 
Dependency Versions:
         Jinja2: 2.8
       M2Crypto: Not Installed
           Mako: Not Installed
         PyYAML: 3.10
          PyZMQ: 14.3.1
         Python: 2.7.5 (default, Nov 20 2015, 02:00:19)
           RAET: Not Installed
        Tornado: 4.2.1
            ZMQ: 3.2.5
           cffi: Not Installed
       cherrypy: Not Installed
       dateutil: 2.5.3
          gitdb: Not Installed
      gitpython: Not Installed
          ioflo: Not Installed
        libgit2: Not Installed
        libnacl: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.4.8
   mysql-python: 1.2.3
      pycparser: Not Installed
       pycrypto: 2.6.1
         pygit2: Not Installed
   python-gnupg: Not Installed
          smmap: Not Installed
        timelib: 0.2.4
 
System Versions:
           dist: centos 7.2.1511 Core
        machine: x86_64
        release: 3.10.0-327.el7.x86_64
         system: CentOS Linux 7.2.1511 Core

**Comment by thatch45** [comment]
This has not been fixed and I am leaning towards not fixing it. I worry that having an exclude do this may result in unwanted side effects.....

**Comment by elxwill** [comment]
What would be the recommended workaround?

**Comment by thatch45** [comment]
I would say to make a state that does not include the intended exclusion in the first place.

**Comment by disaster123** [comment]
+1 for a fix. Still don't understand how to work around this. I've the same issue like @jhenry82

**Comment by disaster123** [comment]
this issue is still valid

**Comment by waynew** [comment]
@josmardias your original issue is expected behavior, though the documentation isn't very clear. I've opened #55550 to track updating the docs/error message.

@jhenry82 this is a proper bug - if an exclude remove a state that has `require_in` then we should go ahead and just and remove the requisite, too.

**Comment by disaster123** [comment]
Still valid

**Comment by sagetherage** [comment]
@waynew is there a PR or another ticket for changing requistes/excludes?

**Comment by waynew** [comment]
@sagetherage this is the ticket for the buggy behavior and #55550 is the ticket to enhance the documentation/error messaging.

**Comment by dwoz** [comment]
@josmardias This issue is very old and has never gotten much traction. If this is still a priority for you please open a new issue against one of the currently [supported versions](https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-version-support-lifecycle.html).
