### ISSUE TITLE
[DOCS] Salt-cloud Azure dependency is deprecated 

### ISSUE THREAD

**Issue by Grayfoox** [saltstack/salt#62431]
**Description**
Salt-cloud Azure dependency is deprecated viz. https://github.com/Azure/azure-sdk-for-python/issues/10646

**Suggested Fix**
Check on which dependency is really needed from that meta package (https://azure.github.io/azure-sdk/releases/latest/all/python.html)

Or dirty fix, installing old version 
installing older version (Azure==4)

**Type of documentation**
Getting started with azure - salt cloud

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/cloud/azure.html

**Additional context**
![image](https://user-images.githubusercontent.com/7593761/183043272-f6ac88ca-0b1f-4804-86aa-cfff8bf45d13.png)

**Comment by nicholasmhughes** [comment]
All Azure functionality in Salt will be removed in version 3007. Please begin using the [Salt Extension for Azure](https://github.com/salt-extensions/saltext-azurerm)

The dependency versions have been updated in that repository.
