### ISSUE TITLE
[BUG] Salt 3005rc2 produces tornado exceptions

### ISSUE THREAD

**Issue by Oloremo** [saltstack/salt#62453]
**Description**
We noticed that Salt on 3005rc2 release produces errors like that in the logs:

https://gist.github.com/Oloremo/699cfd1b02cb9150ff549d9c415bee3d

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.) 

```yaml
Salt Version:
          Salt: 3005rc2

Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: 5.0.3
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 19.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1062.18.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core```
</details>

**Comment by frebib** [comment]
At a guess this is due to outdated libraries/dependencies? Can you try running this with python 3.7 or newer?

**Comment by Oloremo** [comment]
Is python3.6 no longer supported for 3005?

**Comment by frebib** [comment]
Despite python 3.6 already being end of life https://endoflife.date/python the release notes claim that it should be supported https://github.com/saltstack/salt/blob/v3005rc2/doc/topics/releases/3005.rst#python-35-and-36-deprecation

**Comment by Oloremo** [comment]
In that case, I consider it a regression that needs to be fixed. :-)

**Comment by Ch3LL** [comment]
fix is here: https://github.com/saltstack/salt/pull/62476

**Comment by Ch3LL** [comment]
closed by https://github.com/saltstack/salt/pull/62476
