### ISSUE TITLE
[BUG] modules.cmdmod template

### ISSUE THREAD

**Issue by VietTPham** [saltstack/salt#62491]
**Description**
Template parameter is not working in modules.cmdmod

**Setup**
I am using salt 3004.2 on Rocky 8

  
**Steps to Reproduce the behavior**
When using template=jinja I would get an error, of `failed: Jinja variable 'jinja' is undefined`. I used single quote, double quote, and no quote and error on all of them.
If I use template=None this works, but of course, it does nothing to the jinja.
```sls
{% set version = "xxx" %}
{% if salt['cmd.retcode']('/some_program --version | grep -q {{ version }}', template=jinja) %}
....
{% endif %}
```

**Expected behavior**
I should be able to use set template to jinja, mako, or wempy and not get an error.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
</details>
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.11.5
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Apr 12 2022, 06:55:39)
  python-gnupg: Not Installed
        PyYAML: 3.12
         PyZMQ: 19.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 8.6 Green Obsidian
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.19.1.el8_6.x86_64
        system: Linux
       version: Rocky Linux 8.6 Green Obsidian

**Additional context**

**Comment by lukasraska** [comment]
You most probably want something like this
```jinja
{% set version = "xxx" %}
{% if salt['cmd.retcode']('/some_program --version | grep -q ' ~ version) %}
....
{% endif %}
```

instead of the `template` argument approach.

**Comment by VietTPham** [comment]
I tried the above and it does not work.
The `~ version` is not being replaced with the `xxx` value.
I tested by manually putting the version value in like `grep -q xxx` and that works to rule out bad logic.

**Comment by OrangeDog** [comment]
You need to quote the string value:

```jinja2
{% if salt["cmd.retcode"]("/some_program --version | grep -q {{ version }}", template="jinja") %}
```
