### ISSUE TITLE
[DOCS] How to reference command line arguments in remotely executed script

### ISSUE THREAD

**Issue by jbemmel** [saltstack/salt#62507]
**Description**
It is unclear how to reference arguments passed on the command line using 'args', for example:
```
salt node cmd.script salt://templates/set_hostname.j2 template=jinja args='{ hostname: test }'
```
-> use args['hostname'] in the script set_hostname.j2

**Suggested Fix**
What works: 
``` host-name "{{ __pub_arg[1]['args']['hostname'] }}" ```

However, this looks more like a hack using internal variables

**Type of documentation**
Salt documentation for cmd.script

**Additional context**
Using v3004.2

**Comment by OrangeDog** [comment]
`args=` are arguments for the script, not context for the template engine. You probably don't actually want a template at all:

```bash
#!/bin/sh
host-name "$1"
```
```
salt node cmd.script salt://templates/set_hostname.sh args=test'
```

The template shouldn't be accessing the script arguments.
There does not appear to be any way to pass context variables to the template at all.

**Comment by Ch3LL** [comment]
Closing as this is labeled a Question and inactive. If there is a valid bug on the latest version of Salt please open a new issue with the details.
