### ISSUE TITLE
[FEATURE REQUEST] new core grain - a grain for telling if current salt build is onedir/singlebin/system packaged python 

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#62589]
**Is your feature request related to a problem? Please describe.**
Knowing if salt the current salt build is onedir/singlebin or system python based would be useful in certain states

**Describe the solution you'd like**
A grain that responds with "onedir","singlebin" or "system" 

**Describe alternatives you've considered**
custom grain

**Additional context**

**Comment by OrangeDog** [comment]
or pip-installed?

**Comment by lukasraska** [comment]
FWIW we're currently using this in custom grain to determine whether Salt is Tiamat-bundled
```python
def _is_tiamat():
    return getattr(sys, "frozen", False)
```

although that's not really the case, in practice it's enough for us

**Comment by ITJamie** [comment]
adding @Ch3LL as we talked about this in the past on slack

**Comment by OrangeDog** [comment]
It would be very useful if it was in the `--versions-report` too.

**Comment by max-arnold** [comment]
I'm curious, what use-cases you have in mind for this grain? I.e. what would be done differently in your states or modules based on this grain?

**Comment by OrangeDog** [comment]
If salt is installed with classic packaging, then people probably want to use `pkg.installed` for additional dependencies. But if it's onedir then they need to use `pip.installed` instead.

**Comment by Ch3LL** [comment]
Since this is a feature request, it would need to go into 3006 not a point release. There is still value in 3006 since there is still different ways to install Salt: `pip` install and installing from packages that OS's provide

**Comment by Ch3LL** [comment]
I've added https://github.com/saltstack/salt/pull/64446 , but I have not been able to determine a way to programattically determine if Salt was installed via pip. I'm open to suggestions in the meantime while I continue to investigate.
