### ISSUE TITLE
[BUG] Bootstrap script assigns amd64 architecture for arm64 arch

### ISSUE THREAD

**Issue by memphishasaheadache** [saltstack/salt#62647]
**Description**
When I download and run the currently published bootstrap script from  https://bootstrap.saltstack.com the script fails to install on a EC2 instance running Ubuntu 20.04, complaining that python3-zmq can't be installed.  Inspecting the script, specifically line 1436, you can see the architecture being incorrectly set to amd64

>         "arm64")
>            if [ "$_CUSTOM_REPO_URL" != "null" ]; then
>                warn_msg="Support for arm64 is experimental, make sure the custom repository used has the expected structure and contents."
 >           else
 >               # Saltstack official repository does not yet have arm64 metadata,
 >               # use amd64 repositories on arm64, since all pkgs are arch-independent
 >               __REPO_ARCH="amd64" <---
 >               __REPO_ARCH_DEB="deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg arch=$__REPO_ARCH]"
 >               warn_msg="Support for arm64 packages is experimental and might rely on architecture-independent packages from the amd64 repository."

**Setup**
A fresh EC2 instance with Ubuntu 20.04 running on a graviton processor
 
**Steps to Reproduce the behavior**
As root on the above fresh system, run: wget -O install_salt.sh https://bootstrap.saltstack.com && sh ./install_salt.sh

**Expected behavior**
Install the arm64 version of salt-minion/salt-common packages

**Comment by OrangeDog** [comment]
https://github.com/saltstack/salt-bootstrap/issues
