### ISSUE TITLE
[BUG] my salt state executes a command  using cmd.run and it generates a url which i should approve manually in browser. My state stucks in loop and does not return anything. I need generated URL as part of state execution.  does salt supports this kind of functionality?

### ISSUE THREAD

**Issue by subhashithareddy** [saltstack/salt#62659]
**Description**
My salt state executes a command  using cmd.run and generates a url which i should approve manually in browser. My state stucks in infinite loop and does not return anything. does salt supports this kind of functionality?

cloudflared-authenticate:
  cmd.run:
    - name: cloudflared tunnel login

**Comment by OrangeDog** [comment]
> does salt supports this kind of functionality?

No. Salt states are not interactive.

You'll need to find a solution to automate the command. Either with some sort of pre-auth you can deliver via e.g. pillar, or common automation tools like `expect`.

**Comment by OrangeDog** [comment]
A line of investigation that may be useful: https://github.com/cloudflare/cloudflared/issues/750
