### ISSUE TITLE
[DOCS] state - virtualenv.managed - onedir documentation needed + possibly block this state 

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#62687]
**Description**
I just noticed another place where we should add warnings about the python onedir change.
when using the virtualenv.managed state with salt onedir. if you dont supply the python variable it will use onedir’s python to create the virtualenv https://docs.saltproject.io/en/latest/ref/states/all/salt.states.virtualenv_mod.html#salt.states.virtualenv_mod.managed
we called needing to update pip.installed uses for the onedir changeover, but we should also add virtualenv.managed to those warnings
https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#how-to-upgrade-to-onedir (step 4)

**Suggested Fix**
add docs on upgrade guide to supply `python` path to a system python package

**Type of documentation**
Salt modules + salt repo / salt install guide

**Additional context**
It might be a good idea to block use of `virtualenv.managed` on onedir builds if `python` var isnt supplied. aka making it a required field

**Comment by OrangeDog** [comment]
Supplying `venv_bin` should also be sufficient.

**Comment by dwoz** [comment]
This will be in `3006.9`
