### ISSUE TITLE
[BUG]Initial install for version 3005 (not update) that install python3.9 in broken and salt-minion cannot start 

### ISSUE THREAD

**Issue by sjaganat** [saltstack/salt#62681]
Description of Issue
Salt-minion fails to start after install on a clean server for version 3005. (Please note updating existing works )

Setup
Salt-master and Salt-Minion verison 3005-1.
This happens after install, salt-minion cannot start

Steps to Reproduce Issue
Install salt-minion on clean server, i.e first install not update
Salt-minion fails to start with below error:

   Active: failed (Result: exit-code) since Wed 2022-08-31 18:56:19 SAST; 30s ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltproject.io/en/latest/contents.html
  Process: 16611 ExecStart=/usr/bin/salt-minion (code=exited, status=1/FAILURE)
 Main PID: 16611 (code=exited, status=1/FAILURE)

Aug 31 18:56:19 mmspsaltmaster01 salt-minion[16611]:   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 567, in _build_master
Aug 31 18:56:19 mmspsaltmaster01 salt-minion[16611]:     ws.require(__requires__)
Aug 31 18:56:19 mmspsaltmaster01 salt-minion[16611]:   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 884, in require
Aug 31 18:56:19 mmspsaltmaster01salt-minion[16611]:     needed = self.resolve(parse_requirements(requirements))
Aug 31 18:56:19 mmspsaltmaster01salt-minion[16611]:   File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 770, in resolve
Aug 31 18:56:19 mmspsaltmaster01 salt-minion[16611]:     raise DistributionNotFound(req, requirers)
Aug 31 18:56:19 mmspsaltmaster01 salt-minion[16611]: pkg_resources.DistributionNotFound: The 'salt==3005' distribution was not found and is required by the application
Aug 31 18:56:19 mmspsaltmaster01 systemd[1]: salt-minion.service: Main process exited, code=exited, status=1/FAILURE
Aug 31 18:56:19 mmspsaltmaster01 systemd[1]: salt-minion.service: Failed with result 'exit-code'.
Aug 31 18:56:19 mmspsaltmaster01 systemd[1]: Failed to start The Salt Minion.

**Comment by dmurphy18** [comment]
@sjaganat Specifically asked how you installed and on what OS, that information is missing, when I asked you to open this issue.  Is this a bootstrap install ?

**Comment by sjaganat** [comment]
OS is RHEL8.6 and I used the latest saltstack repo https://repo.saltproject.io/py3/redhat/8/x86_64/latest.repo. Used yum to install the salt-minion and salt-master.

**Comment by OrangeDog** [comment]
> Used yum to install the salt-minion and salt-master. It's bootstrap install.

These are mutually-exclusive. Did you use `yum` or did you use `bootstrap.saltproject.io`?

**Comment by sjaganat** [comment]
I used yum to install salt-minion and salt-master.

**Comment by dmurphy18** [comment]
@sjaganat you state bootstrap install above and in private communications.  The bug trace is percisely that seen by problems bootstrapping install with Salt 3005.
I have already throughly tested package install using yum on RHEL 8 Streaming, Alma 8.6 and Rocky 8.6 without problems.

I am therefore closing this as a duplicate issue since this issue has already been resolved by PR https://github.com/saltstack/salt-bootstrap/pull/1863 among others.
