### ISSUE TITLE
[TEST FAILURE] windows flaky test tests.pytests.functional.modules.test_win_dsc.test_get_config_not_configured

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#62714]
Please paste the link from the specific build where the failure first started:
https://jenkins.saltproject.io/job/pr-windows-2019-x64-py3-pytest/job/PR-62587/4/

**Comment by cmcmarrow** [comment]
Has this test been moved?

**Comment by whytewolf** [comment]
moved? maybe 4 months ago 

https://github.com/saltstack/salt/blob/master/tests/pytests/functional/modules/test_win_dsc.py#L217-L221

Looks like the test that failed ran into a locking issue of some kind.

**Comment by twangboy** [comment]
Probably related to this: https://github.com/saltstack/salt/issues/62714
Gonna try disabling the background refresh by setting the Config mode to Apply only
More info here: https://powershellmagazine.com/2015/02/19/dsc-local-configuration-manager-refresh-modes-in-wmf-5-0/
