### ISSUE TITLE
3005 upgrade: Cannot use pip to install dependencies w. onedir

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#62751]
### Description of Issue
(A lot of) My minions do not have external network access so any attempt to install external pip dependencies with pip.installed fail.
```
webstats:
----------
          ID: salt-pkgs
    Function: pip.installed
        Name: jinja
      Result: False
     Comment: Failed to install packages: jinja. Error: Collecting jinja   Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b42517b00>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/jinja/
                Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b42517c18>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/jinja/
                Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b42517978>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/jinja/
                Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b42517a58>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/jinja/
                Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f6b42517e48>: Failed to establish a new connection: [Errno 101] Network is unreachable',)': /simple/jinja/
                Could not find a version that satisfies the requirement jinja (from versions: )
              No matching distribution found for jinja
     Started: 17:02:42.134242
    Duration: 10702.842 ms
     Changes:

```
It does seem it is necessary to use pip.install since the upgrade to onedir because the mako (and jinja?) renderers aren't installed by default.

The pip.installed suggestion came from https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html

```
root@salt:/home/salt/conf# cat all-mandatory-packages/init.sls
[...]
{% if grains['saltversion'] >= '3005' %}
salt-pkgs:
  pip.installed:
    - names:
      - mako
      - jinja

{% endif %}
```

How does one resolve this conundrum? *Is* this a conundrum? If this isn't, then this is a bug about the documentation being unclear about the upgrade to onedir.

**Comment by OrangeDog** [comment]
`mako` and `jinja2` are already included in the onedir build, so there is no need for you to install them again.

For any optional dependencies, you'll need to fetch them via some other means (e.g. `pip download` on another machine`), distribute them to your minions (e.g. with Salt), and install them from local sources.

**Comment by Mrten** [comment]
You'll have to explain this error then:
```
----------
          ID: /etc/munin/munin-node.conf
    Function: file.managed
      Result: False
     Comment: Traceback (most recent call last):
                File "salt/utils/templates.py", line 216, in render_tmpl
                  output = render_str(tmplstr, context, tmplpath)
                File "salt/utils/templates.py", line 539, in render_mako_tmpl
                  import mako.exceptions  # pylint: disable=no-name-in-module
              ModuleNotFoundError: No module named 'mako.exceptions'; 'mako' is not a package
     Started: 17:24:43.336132
    Duration: 28.507 ms
     Changes:
```

which went away after a `salt pip install mako`

22.04 ubuntu

**Comment by Mrten** [comment]
The documentation about using `pip.installed` is sorely lacking in relation to onedir. How *does* one use `pip.installed` to provide the mako package to the onedir? The docs keep saying 'please look at the module documentation' and there is precisely nothing there to look at.

**Comment by OrangeDog** [comment]
I guess an additional example would be nice, but all it does is pass the arguments `pip`:

```yaml
mako:
  pip.installed:
    - name: /opt/python-packages/mako.whl
```
```yaml
mako:
  pip.installed:
    - index_url: https://repo.internal/python
```

**Comment by Mrten** [comment]
Thanks. Apologies for sounding salty, I realize reacting on github comments is a hard job :) It's just that installing pip "just for salt" sounds easy but it's yet another dependency I would have liked to avoid.

From [the text](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.pip_state.html#module-salt.states.pip_state) 

> If you are using onedir packages and you need to install python packages into the system python environment, you must provide the pip_bin or bin_env to the pip state module.

it *seems* that just using `pip.installed` installs packages in the onedir, but the text is a negative, not an explicit confirmation. It's just that my salt master is of course also firewalled off the internet so any extra dependecy I'd have to install would have to make at least two hops (proxy > salt master, salt master > salt minion).

Would it be hard to provide mako as a default dependency also for Linux? It's been a first-class renderer for as long as I've been using salt (since 2013!).

**Comment by Mrten** [comment]
And thanks for the feature request, as well :) 👍

**Comment by OrangeDog** [comment]
There have been many complaints in general about installing onedir dependencies.
It doesn't really fit the format of github issues unfortunately, and I don't think anything is going to persuade Salt to change direction.

**Comment by Mrten** [comment]
Nah, agreed. I think I understand the reason for onedir; it's a pain to provide eight different packages with eight different package management systems when you can also provide one. There has been a good salesman pitching for onedir! ;)

I like to think that this bug is one on the path to a smooth transition. Should I file another bug for the mako inclusion?

**Comment by OrangeDog** [comment]
I don't think either is a bug. I've asked on Slack why mako is only for Windows, but all the devs will be asleep right now.

**Comment by OrangeDog** [comment]
I'm afraid the consensus was to remove it from Windows, rather than add it to everything else: #62785
