### ISSUE TITLE
[FEATURE REQUEST] netbox pillar - pull related (connected) devices as part of pillar information

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#62761]
**Is your feature request related to a problem? Please describe.**
It would be really nice to have information about the connected devices (netbox interfaces show a connected object) to allow things like changing templates on interfaces based on the type of object attached to them in a netops context

**Describe the solution you'd like**
add an aditional key to the netbox dictionary that has the "device" api data for all connected devices

**Describe alternatives you've considered**
I considered writing another pillar module however extending the existing one is lower overhead as most of the data (interface data) is already populated, another module would have to duplicate api calls to netbox

**Comment by OrangeDog** [comment]
Is that in addition to the `interfaces` that it already can return?

**Comment by ITJamie** [comment]
it is in addition. ive prepared https://github.com/saltstack/salt/pull/62666 for this
