### ISSUE TITLE
[BUG] No man pages in 3005 onedir rpms.

### ISSUE THREAD

**Issue by matthewsht** [saltstack/salt#62763]
**Description**
There are no man pages for the v3005 onedir rpms.
This bug report should only apply to the onedir packaging.

**Setup**
[root@localhost ~]# salt-minion --version
salt-minion 3005

[root@localhost ~]# rpm -ql salt-minion
/etc/salt/minion
/etc/salt/minion.d
/etc/salt/pki/minion
/etc/salt/proxy
/usr/bin/salt-call
/usr/bin/salt-minion
/usr/bin/salt-proxy
/usr/lib/systemd/system/salt-minion.service
/usr/lib/systemd/system/salt-proxy@.service

**Steps to Reproduce the behavior**
[root@localhost ~]# man salt-minion
No manual entry for salt-minion

**Expected behavior**
For the man pages to exist and be queryable in the salt-minion, salt-master, et al onedir rpms.

**Additional context**
So far, the 3005 onedir rpms are working well for us and we appreciate everyones hard work to make that happen.

I put this in BUG rather than DOC advisedly - this isn't an edit or incorrectness thing - the man pages existed in earlier versions, they just need to be added to the onedir build process. My apologies if thats incorrect or this is a dup report.

**Comment by dmurphy18** [comment]
Sorry for that oversight, will look into fixing this packaging issue

**Comment by dmurphy18** [comment]
Merge Request https://gitlab.com/saltstack/open/salt-pkg/-/merge_requests/209 is out for review

**Comment by dmurphy18** [comment]
Closing as MR is merged
