### ISSUE TITLE
[TECH DEBT] remove mako from windows and setup.py dependencies

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#62785]
It's unknown why this renderer dependency is only in the Windows packages, but for consistency it should probably be removed.

The renderer doc should also be updated to mention the dependency.

https://saltstackcommunity.slack.com/archives/C8832QN4U/p1664276433155639

**Comment by dmurphy18** [comment]
This is @twangboy's headache

**Comment by OrangeDog** [comment]
`libnacl` is in the same situation: #63657

**Comment by garethgreenaway** [comment]
Closed by #64016
