### ISSUE TITLE
Scheduler No Longer List after Disable or Enable

### ISSUE THREAD

**Issue by sramsey822** [saltstack/salt#62795]
### Description of Issue
Seeing an ugly issue with the Scheduler: Apparently, a couple of versions (ie: years ago) the Scheduler would no longer perform a listing AFTER the user issued: schedule.enable or schedule.disable. If the user attempts to issue schedule.list an error is generated
"Passed invalid arguments: 'bool' object does not support item assignment."

### Setup
salt tradingpost schedule.add job1 function="cmd.script" job_args="['salt://files/mlx_apt_confirm.sh']" seconds=10

### Steps to Reproduce Issue
1. Create schedule job
2. salt minion1 schedule.list
3. salt minion1 schedule.disable
4. salt minion1 schedule.enable
5. salt minion1 schedule.list
Error Message:

minion1:
    Passed invalid arguments to schedule.list: 'bool' object does not support item assignment
    
        List the jobs currently scheduled on the minion
    
        CLI Example:
    
        .. code-block:: bash
    
            salt '*' schedule.list
    
            # Show all jobs including hidden internal jobs
            salt '*' schedule.list show_all=True
    
            # Hide disabled jobs from list of jobs
            salt '*' schedule.list show_disabled=False
    
[salt-log.txt](https://github.com/saltstack/salt/files/9690806/salt-log.txt)

### Versions Report
Both the master / minion are running the same versions Salt - 3005+ds-2
salt --versions-report
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-126-generic
        system: Linux
       version: Ubuntu 20.04 focal

**Comment by OrangeDog** [comment]
There were some changes to schedule storage in the past that ended up being not compatible, especially if you were using an old syntax.

Try `schedule.purge` and recreating the schedule. It should clear out any leftover old attributes.

**Comment by garethgreenaway** [comment]
Looks like this broke with this PR, https://github.com/saltstack/salt/pull/61683
