### ISSUE TITLE
[BUG] source file not found in saltenv after upgrade to saltstack 3005

### ISSUE THREAD

**Issue by bennodepenno** [saltstack/salt#62824]
**Description**
Salt minions upgraded to 3005 are no longer able to manage files using salt://{{ slspath}} as a source when used in states which are included in a main init.sls. Salt minions still on 3004 work as expected.

Error when executing file.managed state: Source file salt:///var/cache/salt/minion/files/develop/testslspath/templates/testile.txt not found in saltenv 'develop'

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
Salt master: 3004
Salt minion: 3004 and 3005

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
On the salt master:
```
testslspath/
├── init.sls
├── myslspath.sls
└── templates
    ├── testileinit.txt
    └── testile.txt
```

**Expected behavior**
An state part of an include section should be able to successfully manage a file using the {{ slspath }} construct.

**Screenshots**
Execution of the testslspath state on a salt-minion with version 3005:

```
# salt-call state.apply testslspath
local:
----------
          ID: echo_include_state
    Function: cmd.run
        Name: echo 'SLSPATH in included state = /var/cache/salt/minion/files/develop/testslspath.'
      Result: True
     Comment: Command "echo 'SLSPATH in included state = /var/cache/salt/minion/files/develop/testslspath.'" run
     Started: 11:11:49.140517
    Duration: 8.946 ms
     Changes:   
              ----------
              pid:
                  27640
              retcode:
                  0
              stderr:
              stdout:
                  SLSPATH in included state = /var/cache/salt/minion/files/develop/testslspath.
----------
          ID: from_included_state
    Function: file.managed
        Name: /tmp/testfile.txt
      Result: False
     Comment: Source file salt:///var/cache/salt/minion/files/develop/testslspath/templates/testile.txt not found in saltenv 'develop'
     Started: 11:11:49.152457
    Duration: 34.408 ms
     Changes:   
----------
          ID: echo_init_state
    Function: cmd.run
        Name: echo 'SLSPATH in init = testslspath.'
      Result: True
     Comment: Command "echo 'SLSPATH in init = testslspath.'" run
     Started: 11:11:49.187174
    Duration: 6.273 ms
     Changes:   
              ----------
              pid:
                  27644
              retcode:
                  0
              stderr:
              stdout:
                  SLSPATH in init = testslspath.
----------
          ID: from_init
    Function: file.managed
        Name: /tmp/testfileinit.txt
      Result: True
     Comment: File /tmp/testfileinit.txt is in the correct state
     Started: 11:11:49.193717
    Duration: 27.846 ms
     Changes:   

Summary for local
------------
Succeeded: 3 (changed=2)
Failed:    1
------------
Total states run:     4
Total run time:  77.473 ms
```

Execution of testslspath.myslspath works:
```
salt-call state.apply testslspath.myslspath
local:
----------
          ID: echo_include_state
    Function: cmd.run
        Name: echo 'SLSPATH in included state = testslspath.'
      Result: True
     Comment: Command "echo 'SLSPATH in included state = testslspath.'" run
     Started: 10:58:56.186844
    Duration: 6.617 ms
     Changes:   
              ----------
              pid:
                  26440
              retcode:
                  0
              stderr:
              stdout:
                  SLSPATH in included state = testslspath.
----------
          ID: from_included_state
    Function: file.managed
        Name: /tmp/testfile.txt
      Result: True
     Comment: File /tmp/testfile.txt is in the correct state
     Started: 10:58:56.195343
    Duration: 42.057 ms
     Changes:   

Summary for local
------------
Succeeded: 2 (changed=1)
Failed:    0
------------
Total states run:     2
Total run time:  48.674 ms
```

Execution of the testslspath state on a salt-minion with version 3004:

```
salt-call state.apply testslspath
local:
----------
          ID: echo_include_state
    Function: cmd.run
        Name: echo 'SLSPATH in included state = testslspath.'
      Result: True
     Comment: Command "echo 'SLSPATH in included state = testslspath.'" run
     Started: 08:44:31.923188
    Duration: 12.002 ms
     Changes:   
              ----------
              pid:
                  1078134
              retcode:
                  0
              stderr:
              stdout:
                  SLSPATH in included state = testslspath.
----------
          ID: from_included_state
    Function: file.managed
        Name: /tmp/testfile.txt
      Result: True
     Comment: File /tmp/testfile.txt updated
     Started: 08:44:31.939272
    Duration: 53.861 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644
----------
          ID: echo_init_state
    Function: cmd.run
        Name: echo 'SLSPATH in init = testslspath.'
      Result: True
     Comment: Command "echo 'SLSPATH in init = testslspath.'" run
     Started: 08:44:31.993375
    Duration: 8.751 ms
     Changes:   
              ----------
              pid:
                  1078142
              retcode:
                  0
              stderr:
              stdout:
                  SLSPATH in init = testslspath.
----------
          ID: from_init
    Function: file.managed
        Name: /tmp/testfileinit.txt
      Result: True
     Comment: File /tmp/testfileinit.txt updated
     Started: 08:44:32.002591
    Duration: 28.284 ms
     Changes:   
              ----------
              diff:
                  New file
              mode:
                  0644

Summary for local
------------
Succeeded: 4 (changed=4)
Failed:    0
------------
Total states run:     4
Total run time: 102.898 ms
```

**Versions Report**

Salt master:

<details><summary>
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
</summary>
</details>

Salt minion 3004:

<details><summary>
Salt Version:
          Salt: 3004.2
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 2.11.3
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: 1.4.0
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 20.0.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-18-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
</summary>
</details>

Salt minion 3005:

<details><summary>
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.4
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: 3.15.0
  pycryptodome: 3.12.0
        pygit2: Not Installed
        Python: 3.10.7 (main, Sep  6 2022, 21:22:27) [GCC 12.2.0]
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 24.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: arch rolling n/a
        locale: utf-8
       machine: x86_64
       release: 5.19.12-arch1-1
        system: Linux
       version: Arch Linux rolling n/a
</summary>
</details>

(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

Contents of init.sls:
```yaml
include:
  - ./myslspath

echo_init_state:
  cmd.run:
    - name: echo 'SLSPATH in init = {{ slspath }}.'

from_init:
  file.managed:
    - name: /tmp/testfileinit.txt
    - source: salt://{{ slspath }}/templates/testileinit.txt
    - user: root
    - group: root
    - show_changes: True
```

Contents of myslspath.sls:
```yaml
echo_include_state:
  cmd.run:
    - name: echo 'SLSPATH in included state = {{ slspath }}.'

from_included_state:
  file.managed:
    - name: /tmp/testfile.txt
    - source: salt://{{ slspath }}/templates/testile.txt
    - user: root
    - group: root
    - show_changes: True
```

**Additional context**

**Comment by OrangeDog** [comment]
The default behaviour of `slspath` et al. was changed in 3005. See #61697 and the release notes.

These changes were behind a feature flag for the last couple of releases to allow for migrations.

**Comment by bennodepenno** [comment]
> The default behaviour of `slspath` et al. was changed in 3005. See #61697 and the release notes.
> 
> These changes were behind a feature flag for the last couple of releases to allow for migrations.

I missed that change in the release notes. My bad. Thank you for clarifying this. Will close this item.
