### ISSUE TITLE
Failed to install Salt Minion on Ubuntu 18.04 - ARM64 machine - Salt's Oct 4th Release

### ISSUE THREAD

**Issue by anilknayak** [saltstack/salt#62833]
**Description**
Could not able to install Sal Minion on Ubuntu 18.04

**Setup**

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
Install script

```
/usr/bin/curl -o ./bootstrap-salt.sh -L https://bootstrap.saltproject.io
chmod +x ./bootstrap-salt.sh
./bootstrap-salt.sh -A ${SALTMASTER} -i ${MINION_ID}  -P git v2019.2.8
```

or 

```
./bootstrap-salt.sh -A ${SALTMASTER} -i ${MINION_ID}  -P stable 3005.1 
```
or

```
./bootstrap-salt.sh -A ${SALTMASTER} -i ${MINION_ID}   git v2019.2.8
```

Log

```
*  INFO: Running version: 2022.10.04
 *  INFO: Executed by: -
 *  INFO: Command line: './bootstrap-salt.sh -A <ip> -i <id> -P git v2019.2.8'

 *  INFO: System Information:
 *  INFO:   CPU:          :
 *  INFO:   CPU Arch:     aarch64
 *  INFO:   OS Name:      Linux
 *  INFO:   OS Version:   4.9.253-tegra
 *  INFO:   Distribution: Ubuntu 18.04

 *  INFO: Installing minion
 *  INFO: Found function install_ubuntu_stable_deps
 *  INFO: Found function config_salt
 *  INFO: Found function preseed_master
 *  INFO: Found function install_ubuntu_stable
 *  INFO: Found function install_ubuntu_stable_post
 *  INFO: Found function install_ubuntu_restart_daemons
 *  INFO: Found function daemons_running
 *  INFO: Found function install_ubuntu_check_services
 *  INFO: Running install_ubuntu_stable_deps()
Hit:1 http://download.zerotier.com/debian/bionic bionic InRelease
Hit:2 http://ports.ubuntu.com/ubuntu-ports bionic InRelease
Ign:3 https://repo.saltproject.io/py3/ubuntu/18.04/arm64/latest bionic InRelease
Hit:4 https://repo.download.nvidia.com/jetson/common r32.6 InRelease
Err:5 https://repo.saltproject.io/py3/ubuntu/18.04/arm64/latest bionic Release
  404  Not Found [IP: 13.225.41.123 443]
Hit:6 http://ports.ubuntu.com/ubuntu-ports bionic-updates InRelease
Hit:7 http://ports.ubuntu.com/ubuntu-ports bionic-backports InRelease
Hit:8 https://repo.download.nvidia.com/jetson/t194 r32.6 InRelease
Hit:9 http://ports.ubuntu.com/ubuntu-ports bionic-security InRelease
Reading package lists...
 * ERROR: Failed to run install_ubuntu_stable_deps()!!!
```

**Expected behavior**
Earlier before new release of salt on Oct 04th 2022, we were able to install using bootstrap but today, we see this error
```
Err:5 https://repo.saltproject.io/py3/ubuntu/18.04/arm64/latest bionic Release
  404  Not Found [IP: 13.225.41.123 443]
```
When I checked Ubuntu 18.04 is not present at all.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
Ubuntu 18.04 is no longer a supported operating system, and the repositories have been archived.

If you want to continue installing unsupported versions with bootstrap, I think you need the `-R https://archive.repo.saltproject.io/` option.

**Comment by OrangeDog** [comment]
Sorry, actually the repos are still there: https://repo.saltproject.io/py3/ubuntu/18.04/amd64/latest/

I don't know why they were missing when you checked. Perhaps a temporary server failure?

**Comment by anilknayak** [comment]
@OrangeDog 
Yes, before Oct 4th release they used to be present. Now its removed.

we never see the below error before Oct 4th release
```
Err:5 https://repo.saltproject.io/py3/ubuntu/18.04/arm64/latest bionic Release
  404  Not Found [IP: 13.225.41.123 443]
```

This means they were removed.

**Comment by anilknayak** [comment]
Actually we did following steps to resolve this problem temprarily 
1. Removed ```/etc/apt/sources.list.d/salt.list``
2. Used -r ```./bootstrap-salt.sh -A ${SALTMASTER} -i ${MINION_ID}  -r git v2019.2.8```

This two steps helped us to install minions. We are good for now. If anybody can help to figure out the arm64 version of saltproject. it wil be a great help

**Comment by OrangeDog** [comment]
There has never been an Ubuntu 18.04 arm64 release, so whatever you were using before it wasn't that.

Installing from git or pypi should always work, as Salt itself has no native code.

**Comment by HStry** [comment]
@OrangeDog I'm guessing this is due to the new onedir packaging? Even though the salt code isn't architecture-native, the python runtime is. The package salt-common is now architecture-native: `salt-common_3005.1+ds-3_amd64.deb`
