### ISSUE TITLE
 systemctl status salt-minion

### ISSUE THREAD

**Issue by Zayan1221** [saltstack/salt#62864]
AttributeError: 'dict' object has no attribute 'append'
: [CRITICAL] The beacon errored:
 Traceback (most recent call last):
File "/usr/lib/python3.6/site-packages/salt/minion.py", line 2954, in handle_beacons
beacons = self.process_beacons(self.functions)
File "/usr/lib/python3.6/site-packages/salt/minion.py", line 517, in process_beacons
   b_conf, self.opts["grains"]
 File "/usr/lib/python3.6/site-packages/salt/beacons/__init__.py", line 74, in process
    b_config[mod].append({"_beacon_name": mod})

**Comment by OrangeDog** [comment]
Please provide all the information in the new bug template, including a descriptive title, configuration, reproduction details, and the `--versions-report`

**Comment by Zayan1221** [comment]
***@***.*** ~]# systemctl status salt-minion● salt-minion.service - The Salt Minion   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; enabled; vendor preset: disabled)   Active: active (running) since Tue 2022-10-11 15:00:21 CDT; 18h ago     Docs: man:salt-minion(1)           file:///usr/share/doc/salt/html/contents.html           https://docs.saltproject.io/en/latest/contents.html Main PID: 6511 (salt-minion)   CGroup: /system.slice/salt-minion.service           ├─6511 /usr/bin/python3 /usr/bin/salt-minion           ├─6520 /usr/bin/python3 /usr/bin/salt-minion           └─6522 /usr/bin/python3 /usr/bin/salt-minion
Oct 12 09:20:44 NMSCDEVLEGACY salt-minion[6511]: AttributeError: 'dict' object has no attribute 'append'Oct 12 09:20:45 NMSCDEVLEGACY salt-minion[6511]: [CRITICAL] The beacon errored:Oct 12 09:20:45 NMSCDEVLEGACY salt-minion[6511]: Traceback (most recent call last):Oct 12 09:20:45 NMSCDEVLEGACY salt-minion[6511]: File "/usr/lib/python3.6/site-packages/salt/minion.py", line 2954, in handle_beaconsOct 12 09:20:45 NMSCDEVLEGACY salt-minion[6511]: beacons = self.process_beacons(self.functions)Oct 12 09:20:45 NMSCDEVLEGACY salt-minion[6511]: File "/usr/lib/python3.6/site-packages/salt/minion.py", line 517, in process_beaconsOct 12 09:20:45 NMSCDEVLEGACY salt-minion[6511]: b_conf, self.opts["grains"]Oct 12 09:20:45 NMSCDEVLEGACY salt-minion[6511]: File "/usr/lib/python3.6/site-packages/salt/beacons/__init__.py", line 74, in processOct 12 09:20:45 NMSCDEVLEGACY salt-minion[6511]: b_config[mod].append({"_beacon_name": mod})Oct 12 09:20:45 NMSCDEVLEGACY salt-minion[6511]: AttributeError: 'dict' object has no attribute ***@***.*** ~]#


    On Wednesday, October 12, 2022 at 04:12:36 AM CDT, James Howe ***@***.***> wrote:  
 
 


Please provide all the information in the bug template, including a descriptive title, configuration, reproduction details, and the --versions-report

**Comment by OrangeDog** [comment]
That's not any of the information I requested. Please also format it correctly, don't just reply to the email.

**Comment by Zayan1221** [comment]
salt version 3004 and the client server OS is RHEL,CentOS where as Master server is OPenSuse 15.4

**Comment by Zayan1221** [comment]
Can you please share that Template

**Comment by OrangeDog** [comment]
https://github.com/saltstack/salt/issues/new/choose

**Comment by OrangeDog** [comment]
Duplicate: #60838
