### ISSUE TITLE
Template transfer fails hard for UTF-8 strings

### ISSUE THREAD

**Issue by tomasfejfar** [saltstack/salt#6287]
As described in #2428 - template rendering (or maybe transfer) ends with uncaught exception for UTF-8 string in template. It's "feature" of msgpack and kind of a won't fix issue. What can be fixed though is the hard fail. 

The exception should be handled and salt should display human-readable error message instead, saying that it's known issue and solution is to remove diacritics from the file. Ideally it should display the incriminate part of the file if possible - I had invisible UTF-8 whitespace inside otherwise ascii file and it was hard to debug.

**Comment by icks** [comment]
It seems to me that this bug is still reproducible. Are there any plans to fix it?
