### ISSUE TITLE
[BUG] module 'rabbitmq_user.present' is broken to return existing permissions in some situations

### ISSUE THREAD

**Issue by polak785** [saltstack/salt#62880]
**Description**
Module `rabbitmq_user.present` is broken to return existing permissions in some situations. Consequence is that there is an error to display the changes summary.

The error is : 
```
          ID: test_user
    Function: rabbitmq_user.present
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python3/dist-packages/salt/state.py", line 2276, in call
                  ret = self.states[cdata["full"]](
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
                  return self.loader.run(run_func, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1276, in wrapper
                  return f(*args, **kwargs)
                File "/usr/lib/python3/dist-packages/salt/states/rabbitmq_user.py", line 207, in present
                  ret["changes"]["perms"]["old"].update(existing_perms[vhost])
              ValueError: dictionary update sequence element #1 has length 4; 2 is required
     Started: 09:31:54.568181
    Duration: 1727.198 ms
     Changes:   

```

**Setup**

`test.sls` : 
```
test_user:
  rabbitmq_user.present:
    - password: password
    - force: True
    - tags:
      - monitoring
      - user
    - perms:
      - '/':
        - ''
        - ''
        - '.*'
```

I did some tests but I guess there are another bugged situations : 

Current perms : 
![image](https://user-images.githubusercontent.com/37365812/195559842-018b0030-aed5-4b40-ae9d-c145341c9e1c.png)

Apply result with : 
`ValueError: dictionary update sequence element #2 has length 6; 2 is required`

---

Current perms : 
![image](https://user-images.githubusercontent.com/37365812/195559950-2fd6082f-040f-4fa6-8477-5bf4a5b05b5d.png)

Apply result with : 
`ValueError: dictionary update sequence element #1 has length 0; 2 is required`

---

Current perms : 
![image](https://user-images.githubusercontent.com/37365812/195560106-8f3bd97b-5002-425e-b10c-4ab4fe9b1b96.png)

Apply result with : 
`ValueError: dictionary update sequence element #1 has length 4; 2 is required`

**Steps to Reproduce the behavior**

Apply the above configuration in `test=true` or `test=false`, there is always the error.

**Expected behavior**

A summary about changes should be displayed.

**Versions Report**

RabbitMQ `3.9.20`

<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 0.28.3
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: 1.0.3
        Python: 3.8.10 (default, Jun 22 2022, 20:18:18)
  python-gnupg: 0.4.5
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1020-aws
        system: Linux
       version: Ubuntu 20.04 focal
```
</details>

Same between master and minions.

**Additional context**
https://github.com/saltstack/salt/pull/60217 could have introduced the bug

The workaround is to overload `/states/rabbitmq_users.py` with file from previous version.

**Comment by Ch3LL** [comment]
@garethgreenaway can you triage here please since the PR could be related to this breakage.

**Comment by garethgreenaway** [comment]
@polak785 Unfortunately I haven't been able to reproduce this issue.  I am setting the permissions manually in the RabbitMQ management UI and then running the state file above.  I'm not seeing the same traceback that you're seeing.  Can you offer some insight into how you're seeing this issue?  Thanks!

**Comment by garethgreenaway** [comment]
@polak785 I setup a new Ubuntu 20.04 instance with rabbitmq isntalled and wasn't able to reproduce, it was using rabbitmq 3.8 as that was the version available in the repositories.  Have you been able to test with 3.8?  And how did you install 3.9 in your 20.04 installation?

**Comment by garethgreenaway** [comment]
@polak785 Thanks.

**Comment by garethgreenaway** [comment]
@polak785 That gives me 3.8 and I am still unable to reproduce the issue with Salt 3005.1.

**Comment by garethgreenaway** [comment]
got a newer version of RabbitMQ installed but still unable to reproduce.

**Comment by garethgreenaway** [comment]
@polak785 I still have not been able to reproduce this issue and I have moved the `pending close` label, without additional information I'll need to close this one out in 2 weeks.

**Comment by polak785** [comment]
@garethgreenaway Sorry for the loss of time, indeed it works perfectly with a fresh new Salt. We had the bug because of presence of custom rabbitmq module. We had also a custom state but I just see that we also had a custom module. 

Thanks you for your availabilty and tests about that!

Conclusion: None bug :)

**Comment by garethgreenaway** [comment]
@polak785 Thanks for the update and for closing this one out!
