### ISSUE TITLE
[BUG] MongoDB module not up to date with latest pymongo library

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#62900]
**Description**
MongoDB module not up to date with latest pymongo library

**Comment by ravitejasssihl** [comment]
Hai @garethgreenaway Would you llike to assign me this issue...

**Comment by garethgreenaway** [comment]
@ravitejasssihl This issue was just a placeholder for some existing work to have an issue number for the changelog.  It'll be resolved by the linked PR.
