### ISSUE TITLE
[BUG] 'charmap' codec cant decode byte 0x81 in position ..: character maps to <undefined>

### ISSUE THREAD

**Issue by Canpy** [saltstack/salt#62912]
**Description**
Hello when I run a state, where I upload a Powershell and run it. I get following error:

```
          ID: exec
    Function: cmd.run
        Name: Powershell -NonInteractive -ExecutionPolicy Bypass -File "C:\\Windows\\Temp\\test.ps1"
      Result: False
     Comment: 'charmap' codec can't decode byte 0x81 in position 592: character maps to <undefined>
     Started: 10:50:03.957153
    Duration: 1506.344 ms
     Changes: 
```  
The function in the .ps1 that is causing this error is:

```
Function CreateRestorePoint {
    Enable-ComputerRestore -Drive "C:\"
    Checkpoint-Computer -Description "RestorePoint05" -RestorePointType "MODIFY_SETTINGS"
}
```
A restorepoint can only created every 24 hours, so when I run that Function it outputs the following on the windows machine (in german)

```
WARNUNG: Es kann kein neuer Systemwiederherstellungspunkt erstellt werden, da innerhalb der 
letzten 1440 Minuten bereits ein Wiederherstellungspunkt erstellt wurde. Sie können die Häuf
igkeit für die Erstellung von Wiederherstellungspunkten ändern, indem Sie den DWORD-Wert 'Sy
stemRestorePointCreationFrequency' unter dem Registrierungsschlüssel 'HKLM\Software\Microsof
t\Windows NT\CurrentVersion\SystemRestore' erstellen. Der Wert dieses Registrierungsschlüsse
ls gibt das erforderliche Zeitintervall (in Minuten) zwischen der Erstellung von zwei Wieder
herstellungspunkten an. Der Standardwert ist 1.440 Minuten (24 Stunden).
```

In the Saltmaster it says "'charmap' codec cant decode byte 0x81 in position 592: character maps to <(undefined)>" instead of the normal powershell error what should normally come

That just one function of many others where I get this error.

My Salt State:
```
{% for script in config.scripts %}

upload_{{ script|regex_replace(".ps1","")}}:
  file.managed:
    - name: "C:/Windows/Temp/{{ script }}"
    - source: salt://bit_script/files/scripts/{{ script }}

exec_{{ script|regex_replace(".ps1","")}}:
  cmd.run:
    - name: Powershell -NonInteractive -ExecutionPolicy Bypass -File "C:\\Windows\\Temp\\{{ script }}"
    - runas: {{config.runas}}  
    - require:
      - upload_{{ script|regex_replace(".ps1","")}}

{% endfor %}
```

I have tried to
1. added locales 
2. install older minion version

unfortunately nothing helped.

**Versions Report**
**Saltmaster** is running in a docker
<details><summary>
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.6.1
        Python: 3.7.13 (default, Apr 20 2022, 03:16:50)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: alpine 3.14.6 
        locale: UTF-8
       machine: x86_64
       release: 5.19.15-201.fc36.x86_64
        system: Linux
       version: Alpine Linux 3.14.6 
</summary>

</details>

**Windows Minion:**

<details>
<summary>
C:\Windows\system32>salt-minion --versions-report
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: 1.1.4
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
        Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
  python-gnupg: 0.4.7
        PyYAML: 5.4.1
         PyZMQ: 19.0.0
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist:
        locale: cp1252
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19041 SP0 Multiprocessor Free
</summary>

</details>

**Comment by OrangeDog** [comment]
Or, this might be related to #62205

**Comment by Canpy** [comment]
Thank you very much!

Under Control Panel > Region > Administration Tab > Change Locale. I activated "Beta: Unicode UTF-8...". Now it works

**Comment by OrangeDog** [comment]
Doesn't need to be for the whole machine, but if that works for you then it's fine.
