### ISSUE TITLE
[FEATURE REQUEST] Support for token authentication in Proxmox cloud provider

### ISSUE THREAD

**Issue by jamesharr** [saltstack/salt#62945]
**Is your feature request related to a problem? Please describe.**
We'd like to use an API token instead of a username/password to authenticate to a Proxmox Cloud Provider

**Describe the solution you'd like**
Add additional proxmox provider parameters.
```
my-promxox-provider:
  user: "my-user@pve!my-token-id"
  token_secret:  "...UUID..."
```

When `token_secret` is specified, `password` field would not be required.

**Describe alternatives you've considered**
Currently, I'm creating/maintaining a user account and authenticating that way, we're preferring authentication tokens when writing automation.

**Additional context**
- Token authentication is described in the Proxmox-VE wiki: https://pve.proxmox.com/wiki/Proxmox_VE_API#Example:_Use_API_Token
- Link to file needing patched: [salt/cloud/clouds/proxmox.py](https://github.com/saltstack/salt/blob/master/salt/cloud/clouds/proxmox.py#L121-L140)

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by nicholasmhughes** [comment]
Closing in favor of https://github.com/salt-extensions/saltext-proxmox/issues/6

The Proxmox driver in the Salt core will be deprecated, and the Extension in the linked repo will be the place for new features and bug fixes.
