### ISSUE TITLE
Unable to install salt-master, salt-minon on Raspberry PI OS Bullseye (Debian 11) OneDir

### ISSUE THREAD

**Issue by nocheinlarry** [saltstack/salt#62962]
**Description**
I pinned Major version for installation as stated in https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/debian.html#install-onedir-packages-of-salt-on-debian-11-bullseye 

Installation fails with unmet dependencies:
```
apt-get install salt-master salt-minion salt-api
```
**Log-Output**
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 salt-master : Depends: salt-common (= 3005.1+ds-1) but it is not going to be installed
 salt-minion : Depends: salt-common (= 3005.1+ds-1) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

**Setup**
Vanilla setup of Pi OS 11 (Bullseye) - Raspberry PI OS Lite (32-Bit)
```
sudo apt-get update
sudo curl -fsSL -o /usr/share/keyrings/salt-archive-keyring.gpg https://repo.saltproject.io/salt/py3/debian/11/amd64/3005/salt-archive-keyring.gpg
echo "deb [signed-by=/usr/share/keyrings/salt-archive-keyring.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/11/amd64/3005 bullseye main" | sudo tee /etc/apt/sources.list.d/salt.list
sudo apt-get update
sudo apt-get install salt-master salt-minion salt-api

```
Please be as specific as possible and give set-up details.

- [x] on-prem machine Raspberry PI
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
refer below commands

**Expected behavior**
Pinned packages should be installed as described in the docs.

**Comment by OrangeDog** [comment]
You have added the `amd64` repo, but your system is `armhf`.

The instructions you want are https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/raspbian.html

**Comment by nocheinlarry** [comment]
Hi, thanks for investigation. However the documentation is missleading. [Upgrade to onedir](https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#repository-paths) states the path to Raspian 11 (Raspberry Pi OS 11 - Bullseye) repos. However if I follow this path in a Browser [Repos](https://repo.saltproject.io/salt/py3/debian/11/) there is no armhf subfolder. 

So I'm puzzeled: Is Raspberry Pi OS 11 - Bullseye supported as onedir distribution or not?

The [Raspian Install documation](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/raspbian.html#raspbian) states only classic install. Which leads to my conclusio, Raspian 11 aks Raspberry Pi OS 11 is currently not supported as onedir distribution (missing repos path and missing documentation about onedir install).

May I ask you to verify and evtl. update documentation?

**Comment by barbaricyawps** [comment]
@nocheinlarry and @OrangeDog , since this issue is closed, there's no great way for me to use it to track a documentation request. But it sounds like possibly this is a packaging question and not a documentation question?

If something needs to be changed in the docs, can you open another doc issue to track doc requests? Also, I will probably need it to be slightly more actionable than what you are discussing here. I'm not clear what the ask for the documentation is. You can open the doc request here in the Salt repo, but it would be slightly better if you open it in the Salt install guide repo: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues

**Comment by nocheinlarry** [comment]
Hi @barbaricyawps, you might be right, it might be a packaging issue instead of documentation issue. My question in the upper comment was about answering the question:

Is Raspian 11 / aks Raspberry Pi OS 11 supported as onedir distribution or not from 3005.1 release?

If not I'll raise an issue in gitlab for the documentation update, if true (it is supported), how can I raise the topic with the Saltstack engineering team, packaging is goining wrong for Raspbian 11?

Currently I (as a noob) have no clear picture. Can you @barbaricyawps help to create clarity?

**Comment by PaladinEng** [comment]
Is there an answer on this?

**Comment by nocheinlarry** [comment]
no,I was giving up and installed classic package via bootstrap script. Worked out now.Waiting until onedir is the only install option.
    	Gesendet von Outlook für iOS
    
  

 Von: Alwyn Smith ***@***.***>Gesendet: Mittwoch, Mai 3, 2023 10:20 PMAn: saltstack/salt ***@***.***>Cc: Thomas Landgraf ***@***.***>; Mention ***@***.***>Betreff: Re: [saltstack/salt] Unable to install salt-master, salt-minon on Raspberry PI OS Bullseye (Debian 11) OneDir (Issue #62962) 
Is there an answer on this?
