### ISSUE TITLE
[FEATURE REQUEST] Mention whether minion is classic or onedir in salt versions report

### ISSUE THREAD

**Issue by frebib** [saltstack/salt#62961]
**Is your feature request related to a problem? Please describe.**
Save @OrangeDog having to ask everyone whether their minion is onedir or not: https://github.com/saltstack/salt/issues/62951#issuecomment-1291774046

**Describe the solution you'd like**
`salt-call -V` to say whether the minion is onedir or not

**Describe alternatives you've considered**
N/A

**Comment by OrangeDog** [comment]
Haha, thanks.

It's in the Bug template but people often delete it without answering.
I also requested it here: https://github.com/saltstack/salt/issues/62589#issuecomment-1234515851

**Comment by dfidler** [comment]
Legacy packages are going to be around for years.  SUSE packages their own minions, and other legacy platform (not yet onedir), installation from source isn't going to be onedir, etc.

Even if it's not codified in `salt --version(s)` then it's worthwhile to at least have a documented method of determining if you're running a onedir/legacy/source-installed minion.
