### ISSUE TITLE
[FEATURE REQUEST] environment file serializer

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#62983]
**Describe the solution you'd like**
A common workflow is to create environment files, which have an `=` between a key and value. It would be nice to have a serializer to handle that formatting.

**Describe alternatives you've considered**
`file.keyvalue` can perform a similar purpose, but it can't completely overwrite the file without invoking another state... and there also may be some value in having the functionality in a serializer for other non-state invocations.

**Additional context**
Format:
```
FOO=bar
```

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by OrangeDog** [comment]
Would it be better described as a properties file, or simply a keyvalue file?

The serializer should be named for the structure/format, not for one particular use for it.
