### ISSUE TITLE
[BUG] salt-call hangs after highstate for Windows minion 3005 and 3005.1 (Tiamat), has to be manually killed [BUG]

### ISSUE THREAD

**Issue by geisingerDev** [saltstack/salt#63028]
**Description**
Highstate doesn't end with salt-call on the 3005 and 3005.1 Windows minion. 

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem physical machine
- [ ] vmware vm
- [ ] ec2 

**Steps to Reproduce the behavior**
run salt-call state.highstate

**Expected behavior**
The highstate should end without manual intervention.

**Screenshots**
![image](https://user-images.githubusercontent.com/84455856/200322849-8cb1e1cf-1699-4734-baf6-ae5afd50486a.png)

**Versions Report**

Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.11.5
      cherrypy: Not Installed
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 4.0.1
     gitpython: 3.0.9
        Jinja2: 3.0.3
       libgit2: 1.1.0
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: 1.6.1
        Python: 3.6.8 (default, Jun 14 2022, 12:54:58)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 20.0.0
         smmap: 3.0.1
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

Salt Extensions:
        SSEAPE: 8.10.0.3

System Versions:
          dist: rhel 8.6 Ootpa
        locale: UTF-8
       machine: x86_64
       release: 4.18.0-372.32.1.el8_6.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 8.6 Ootpa

(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)
Master 3005.1
Minion 3005.1

```yaml
PASTE HERE
```
</details>

**Additional context**
![image](https://user-images.githubusercontent.com/84455856/200345148-c7299380-8264-40e3-99b4-d6e5bf14e873.png)

**Comment by OrangeDog** [comment]
Duplicate: #62937

**Comment by twangboy** [comment]
Closing this in favor of https://github.com/saltstack/salt/issues/62937. Thanks @OrangeDog

**Comment by geisingerDev** [comment]
How can you close a bug without resolution?

**Comment by geisingerDev** [comment]
is there a fix for Tiamat? we have to roll it out to all our systems

**Comment by geisingerDev** [comment]
@twangboy

**Comment by OrangeDog** [comment]
Because it's a duplicate. Watch the linked issue for a resolution.

**Comment by geisingerDev** [comment]
we are not using the classic package. is the resolution the same or we have to wait as you mentioned in https://github.com/saltstack/salt/issues/62937.

"If you are using a OneDir/Tiamat package, you will have to wait for the fix (either a patched build, or a new release)."

**Comment by geisingerDev** [comment]
as we know the master is at 20.0.0 of pyzmq, so you just want the minions updated to it? or i have to upgrade the master pyzmq to 22.0.3 as well?

**Comment by OrangeDog** [comment]
All the details are in the linked issue.

**Comment by geisingerDev** [comment]
![image](https://user-images.githubusercontent.com/84455856/200577306-eb40e6aa-f6f1-40f9-a00b-f014a902071d.png)

**Comment by geisingerDev** [comment]
i guess we will have to wait

**Comment by geisingerDev** [comment]
@OrangeDog  i think the details are missing in the other link. are you saying we have to upgrade the master and minions to pyzmq 22.0.3 even for Tiamat because there is conflicting information on that page. We just need know as it affects a big chunk of our environment
