### ISSUE TITLE
[FEATURE REQUEST] quiet mode for file.touch

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#63035]
**Describe the solution you'd like**
A parameter which allows `file.touch` to touch without updating the changes dictionary, effectively running "clean"

**Describe alternatives you've considered**
Various Jinja gymnastics. Not using the `file.touch` state....

**Additional context**
`file.touch` doesn't really make sense as a state module function because it's not idempotent. however, many people have workflows in which they want to use it... but without the "noise" of changes being reported during every run.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by OrangeDog** [comment]
Shouldn't they just use `module.run` to call the `file.touch` function if they want to touch regardless?

If the state isn't idempotent then that should be fixed. If the file already has the given times then it should do nothing.

**Comment by nicholasmhughes** [comment]
The `file.touch` state already exists. Reverting to `module.run` doesn't make sense in this context.

If a static timestamp isn't provided, a touch is performed every run. In that configuration, it can never run clean. I don't see the harm in an "opt-in" parameter which allows ignoring a low-impact activity such as updating a timestamp.

**Comment by OrangeDog** [comment]
The harm is that you then have a state that isn't idempotent, and is making changes, yet lies about it and says that it isn't.

If people want to touch a file and make changes every run, then they should be happy with a result that says it worked.

There is no problem here to fix, and the suggested change just breaks the general contract of Salt.

**Comment by nicholasmhughes** [comment]
We already have a state that isn't idempotent.

> "they should be happy with [the] result"

I don't agree. User experience should absolutely be taken into account, lest you lose touch with your users and they move elsewhere.

The contract is already broken on this state.

**Comment by dmurphy18** [comment]
@nicholasmhughes This matter was discussed in the core team meeting this morning and it was pointed out that the documentation for touch in Salt already states:
```
Replicate the 'nix "touch" command to create a new empty file or update the atime and mtime of an existing file.

Note that if you just want to create a file and don't care about atime or mtime, you should use file.managed instead, as it is more feature-complete. (Just leave out the source/template/contents arguments, and it will just create the file and/or check its permissions, without messing with contents)
```
see: https://docs.saltproject.io/en/latest/ref/states/all/salt.states.file.html#salt.states.file.touch

Alternatively use file.exists and unless to create the file if it doesn't exist, rather than adding additional usage corner cases when functionality already exists to perform the desired effect.

As to idempotent, an analogy, running a state on a Database can be idempotent, however the timestamps for the database will be updated, but its contents are the same.

Closing this issue.

**Comment by OrangeDog** [comment]
That is not a reason to break the contract further.

This state is idempotent if you use it as documented. If you want stateful control of the times on a file you use the `file.touch` state. If you want to execute a touch non-statefully you use the `file.touch` execution module. And if you just want to create a file you use `file.managed`.

Making Salt more broken and less consistent (this also breaks various requisites) is not going to retain users. Improving consistency and clarifying what things are for is.

If this was a good idea, it should be applied globally to every state.
