### ISSUE TITLE
[BUG] salt-master port not closed cause a "Too many open files" error

### ISSUE THREAD

**Issue by Denislb** [saltstack/salt#63040]
**Description**
salt-master does not close properly the receiving port from minions. This causes a "Too many open files" error and we cannot contact any minion after that.
I don't see errors on the master/minion (even in debug mode) and don't know how to reproduce this bug.

On the master if I check opens sockets:
```
$> netstat -laptune | grep 4506 | grep .135 | wc -l
655

$> netstat -laptune | grep .135
tcp        0      0 X.X.X.X:4506        X.X.X.135:48130    ESTABLISHED 1002       46738      2084/python3
tcp        0      0 X.X.X.X:4506        X.X.X.135:48254    ESTABLISHED 1002       46016      2084/python3
tcp        0      0 X.X.X.X:4506        X.X.X.135:48496    ESTABLISHED 1002       51677      2084/python3
tcp        0      0 X.X.X.X:4506        X.X.X.135:45780    ESTABLISHED 1002       76243      2084/python3
and more...
```

On the minion side:
```
$> netstat -laptune | grep 4506 | wc -l
1

$> netstat -laptune | grep 4506
tcp        0      0 X.X.X.135:45780    X.X.X.X:4506       ESTABLISHED 0          1021351    86014/python3

```

**Setup**
Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Expected behavior**
The open port should be closed properly after execution

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 5.4.223-1.el7.elrepo.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Comment by OrangeDog** [comment]
Are you doing anything to trigger this, or does an idle system just keep leaking sockets?

**Comment by OrangeDog** [comment]
Is it also leaking processes?
Similar things seem to happen here: #62706

**Comment by Denislb** [comment]
No, I don't have leaking processes. It's stable, and they don't increase.
It seems that the salt-master has done a job (or maybe something happened) but does not close the port after.

**Comment by Denislb** [comment]
Hello,

After a few investigations.
It seems that we have a leaking process, indeed.
As I show you below, EventPublisher and ReqServer MWorkerQueue have a huge leak.

![image](https://user-images.githubusercontent.com/7715984/204478248-18de30b9-087e-4ac0-8a3b-ac5988b5122e.png)
![image](https://user-images.githubusercontent.com/7715984/204478325-d57246d0-b7c0-4b03-8338-03992ed92ded.png)

**Comment by Denislb** [comment]
FYI
When ReqServer MWorkerQueue is at 100% CPU the process memory starts to increase for ~2 days.

![image](https://user-images.githubusercontent.com/7715984/204481280-f266097a-a1e9-4517-b829-a082a6a83e07.png)
![image](https://user-images.githubusercontent.com/7715984/204481348-761f8477-23b3-47f3-a5e8-89468aac4b20.png)

**Comment by Denislb** [comment]
Hello,

I tried with different transport tcp and zeromq. We have the same issue.

As you can see below, the process MWorkerQueue use 100% CPU and workers does nothing :( 
![image](https://user-images.githubusercontent.com/7715984/204742440-cb4d7508-48ba-4480-ae8c-d4704e7367a3.png)

Do you know where I can add more logs to help for debug ?

**Comment by dmurphy18** [comment]
This is largely fixed in Salt 3006.3, still a minor issue which is being investigated, but the main problem has been resolved.

**Comment by Denislb** [comment]
Hello,

Thanks. I will do some tests.

**Comment by bschoening** [comment]
@Denislb @dmurphy18 has anyone checked if pyflakes and pylint run w/out detecting anything related to open file handles?

**Comment by dmurphy18** [comment]
@bschoening As part of the Salt process, there is a pre-commit step which runs various tests against the intended code, and pre-commit has to be clean before you can even successfully get through the 'git commit' step.
The pre-commit file is https://github.com/saltstack/salt/blob/master/.pre-commit-config.yaml

Static analysis is done by Bandit, pylint, black, etc.

In an upcoming release, there have been changes made to allow for warnings in the log files, where detection is made for some outstanding remaining rare conditions with file handles not getting closed, however the majority of the file handle issues not being closed was resolved by the 3006.3 release of Salt.

**Comment by dmurphy18** [comment]
@Denislb The issue has been fixed in the Salt 3006.3 release and recommend upgrading to the latest release which is 3006.4.

Salt 3005 reaches End-Of-Life in February 2024, 2 and 1/2 months from now, hence the suggestion to upgrade.  If the answer is satisfactory, please consider closing this issue, or provide additional information.

**Comment by dmurphy18** [comment]
Here are the PR's for that attempted fix for majority of the 'too many open files', see https://github.com/saltstack/salt/pull/65508, https://github.com/saltstack/salt/pull/65061, https://github.com/saltstack/salt/pull/65247 and https://github.com/saltstack/salt/pull/65559 which will help to identify places that may have been missed and what is causing them.

**Comment by dmurphy18** [comment]
@Denislb Can you test this against the latest Salt 3006.8 and close the issue if it is resolved.  A number of changes have been made to deal with "too many open files" issues in earlier version of 3006.x.

**Comment by dmurphy18** [comment]
@Denislb Closing this due to unresponsive, please feel free to reopen if more information is provided.
Note the latest is Salt 3006.9
