### ISSUE TITLE
bootstrap installation of salt stable release on rockylinux-9 shows errors

### ISSUE THREAD

**Issue by sachk12** [saltstack/salt#63089]
### Description of Issue
When I run the command "./bootstrap-salt.sh stable 3005.1" on rocky-linux 9, I see the following errors
```
* ERROR: https://repo.saltproject.io/py3/redhat/9/x86_64/archive/3005.1/SALTSTACK-GPG-KEY2.pub failed to download to /tmp/salt-gpg-ViguTX2E.pub
* ERROR: Failed to run install_rocky_linux_stable_deps()!!!
* ERROR: https://repo.saltproject.io/py3/redhat/9/x86_64/archive/3005.1/SALTSTACK-GPG-KEY2.pub failed to download to /tmp/salt-gpg-ViguTX2E.pub
* ERROR: Failed to run install_rocky_linux_stable_deps()!!!
Errors during downloading metadata for repository 'saltstack':
Errors during downloading metadata for repository 'saltstack':
Error: Failed to download metadata for repo 'saltstack': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Error: Failed to download metadata for repo 'saltstack': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried

```

Tried using onedir installtion using the command "./bootstrap-salt.sh -D onedir 3005"
Saw an error about - "install_rocky_linux_check_services" . 

```
*  INFO: Running install_rocky_linux_check_services()
* DEBUG: Checking if service salt-minion is enabled
* DEBUG: Service salt-minion is NOT enabled
* ERROR: Failed to run install_rocky_linux_check_services()!!!
```

### Setup
just a regular instance running rocky-linux-9. Trying to install salt-minion on it.

### Steps to Reproduce Issue
1. Follow bootstrap installation of salt minion on rocky-linux-9 as documented here - https://docs.saltproject.io/salt/install-guide/en/latest/topics/bootstrap.html
2. run "./bootstrap-salt.sh stable 3005.1" on the shell on rocky-linux-9

### Versions Report
(output of salt-minion --versions-report)
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.14.0
        pygit2: Not Installed
        Python: 3.9.10 (main, Sep 23 2022, 00:00:00)
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rocky 9.0 Blue Onyx
        locale: utf-8
       machine: x86_64
       release: 5.14.0-70.17.1.el9_0.cloud.x86_64
        system: Linux
       version: Rocky Linux 9.0 Blue Onyx

**Comment by OrangeDog** [comment]
Duplicate: https://github.com/saltstack/salt-bootstrap/issues/1834

**Comment by sachk12** [comment]
Thank you for listing the duplicate bug. I see the duplicate bug https://github.com/saltstack/salt-bootstrap/issues/1834 closed with the comment "I'll close this issue, but let me know if i need to re-open if the onedir packages don't work either."

I have tried onedir installtion and it failed (as show in my original post). It failed with the error "ERROR: Failed to run install_rocky_linux_check_services()!!!".

I am sorry but I am new to this, what would be the process to get this looked at? Should the duplicate bug need to be reopened or can we use this bug to track this?

**Comment by OrangeDog** [comment]
It's not an problem in this project. Go comment on the other issue.

**Comment by ggiesen** [comment]
My apologies, I also missed that you tried OneDir as well. I've opened up saltstack/salt-bootstrap#1883 to address the issue.

**Comment by sachk12** [comment]
Thank you re-opening https://github.com/saltstack/salt-bootstrap/issues/1883 . 
regards,
