### ISSUE TITLE
[FEATURE REQUEST] Update salt.modules.kubernetes to support a recent version of Kubernetes

### ISSUE THREAD

**Issue by jamesharr** [saltstack/salt#63090]
**Is your feature request related to a problem? Please describe.**
The kubernetes modules no longer work. It appears that the cause is that they're expecting a very old version of the kubernetes python library.

It looks like `salt.modules.kubernetesmod` only supports a very outdated version of the Kubernetes python library (v2.0) and the [library import will fail](https://github.com/saltstack/salt/blob/021c44f3badf071b0e8e909943467c5898d7579c/salt/modules/kubernetesmod.py#L73-L78). I wish to attempt to bring Kubernetes up to something recent.

This version of the library, which was released in 2017, I believe was targeting [Kubernetes 1.6, I think](https://github.com/kubernetes-client/python#homogenizing-the-kubernetes-python-client-versions), which has been EOL'd [2017-11-23](https://kubernetes.io/releases/_print/#non-active-branch-history). The python library is up to [v25](https://github.com/kubernetes-client/python/blob/master/CHANGELOG.md).

**Describe the solution you'd like**
Upgrade the Kubernetes module, list the versions supported, rewrite the module/state, or drop the module/state.

**Describe alternatives you've considered**
Writing a wrapper around `kubectl` so that this module is more version agnostic.

**Additional context**

**Comment by OrangeDog** [comment]
Duplicate: #62621

**Comment by jamesharr** [comment]
Closing due to duplicate issue
