### ISSUE TITLE
[BUG] nonroot user with sudo causing json error. 

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#63107]
**Description**
currently it looks like in 3005.1 that running as non root salt-minion will cause a json error in non highstate functions. 

this currently looks to be related to the use_vt function of cmd.run_all

**Setup**
setup a minion as a non root user. and from a master run salt \* test.ping. 

the non root user minion will return with

```
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1936, in _thread_return
        function_name, function_args, executors, opts, data
      File "/usr/lib/python3.6/site-packages/salt/minion.py", line 1894, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1228, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3.6/site-packages/contextvars/__init__.py", line 38, in run
        return callable(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/loader/lazy.py", line 1243, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/salt/executors/sudo.py", line 77, in execute
        cmd_meta = salt.utils.json.loads(cmd_ret["stdout"])["local"]
      File "/usr/lib/python3.6/site-packages/salt/utils/json.py", line 89, in loads
        return json_module.loads(s, **kwargs)
      File "/usr/lib64/python3.6/json/__init__.py", line 354, in loads
        return _default_decoder.decode(s)
      File "/usr/lib64/python3.6/json/decoder.py", line 339, in decode
        obj, end = self.raw_decode(s, idx=_w(s, 0).end())
      File "/usr/lib64/python3.6/json/decoder.py", line 357, in raw_decode
        raise JSONDecodeError("Expecting value", s, err.value) from None
    json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

```

I found in testing that 
  a. the stdout return of cmd.run_all in the sudo executor is blank
  b. if i change line 69 in https://github.com/saltstack/salt/blob/master/salt/executors/sudo.py from `use_vt=True` to `use_vt=False` it starts working. 

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [X] VM (Virtualbox, KVM, etc. please specify)
- [X] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [X] or a combination, please be explicit
- [X] jails if it is FreeBSD
- [X] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
setup a minion as nonroot using user and sudo options and setup user in visudo to not need a password 

then run salt \* test.ping

salt-call test.ping as the user or root will work fine. but as the daemon it will not. 

**Expected behavior**
user is able to run salt-minion as non root user using sudo.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.9.1
      cherrypy: 5.6.0
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.14
      pycrypto: Not Installed
  pycryptodome: 3.15.0
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4
 
Salt Extensions:
        SSEAPE: 8.10.1.6
 
System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-229.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core
```
</details>

**Additional context**

**Comment by whytewolf** [comment]
with further testing this just seems to be how use_vt works. in that it doesn't 

```
root@salt00:~# salt salt00\* cmd.run_all use_vt=true python_shell=False "echo test"
salt00:
    ----------
    pid:
        310189
    retcode:
        0
    stderr:
    stdout:
root@salt00:~# salt-call cmd.run_all use_vt=true python_shell=False "echo test"
test
local:
    ----------
    pid:
        310597
    retcode:
        0
    stderr:
    stdout:
```

that wasn't even with a nonroot user.

**Comment by dmurphy18** [comment]
Well, the use of use_vt is listed as experimental, see https://github.com/saltstack/salt/blob/master/salt/modules/cmdmod.py#L1175-L1176

And given a large of the code for Salt is common between master and minion, it kind of ties in with SEP19 https://github.com/saltstack/salt-enhancement-proposals/blob/master/0019-master-non-root.md, hence this might be difficult to resolve, esp. since experimental.

In salt/modules/cmdmod.py, passing the bg=True will force use_vt=False, but the problem is sudo calling with cmd.run_all and no possibility to pass such a keyword, and the section of code is over 6 years old.

So with use_vt False, the cmd.run_all will execute a salt.utils.timed_subprocess but with use_vt True it executes salt.utils.vt.Terminal.

Question is: is sudo correctly calling with the right use_vt state, given untouched in 6 years, one would assume it is.

Further investigating to do, but wanted to capture findings to date.

**Comment by whytewolf** [comment]
so, after digging into this case me and @dmurphy18 found that the fix is already merged in master for a different issue. 

the PR that will fix this and be released in 3006 https://github.com/saltstack/salt/pull/62903
This issue is a duplicate of https://github.com/saltstack/salt/issues/60365
