### ISSUE TITLE
[BUG] Issues with installing OneDir on RHEL 9 clones due to presence of classic packages in EPEL

### ISSUE THREAD

**Issue by ggiesen** [saltstack/salt#63112]
**Description**
There are currently issues with installing Salt 3005.1 on RHEL 9 clones (CentOS, Rocky Linux, AlmaLinux, Scientific Linux, Oracle Linux) due to the presence of classic 3005.1 packages in EPEL (which is enabled by default)

Currently, if you attempt to follow the current [installation instructions](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/rhel.html#install-onedir-packages-of-salt-on-redhat-rhel-9) or use salt-bootstrap, in both cases the Salt repo is added but in at least some cases (if not all cases), the packages from EPEL are preferred over the Salt-provided OneDir packages.

In the case of salt-bootstrap, this causes the bootstrap script to fail when it checks for the running minion  (see saltstack/salt-bootstrap#1883), or in the case of a manual install, it's clearly just that unexpected packages are installed in the wrong location.

I'm generally aware of 3 potential solutions (there may be more, or some of these may not work as I haven't completely vetted all of them):

1. Exclude the salt packages from EPEL in the machine's repo configuration. Something like:

```
dnf config-manager --setopt=epel.exclude=salt,salt-api,salt-cloud,salt-master,salt-minion,salt-ssh,salt-syndic --save
```

Pros:
* Shouldn't interfere with any other packages

Cons:
* If Salt adds additional packages (additional salt utilities/daemons, support packages, etc), the user will have to add those additional   packages to the exclude list for EPEL (or any other repo that may contain Salt or other conflicting support packages)
* Requires modification to the bootstrap script and the Salt Install Guide. Still won't work for bootstrap if the user has additional repos that contain conflicting salt packages
<br>
<br>
2. Increase the priority of the Salt repo (by decreasing the number). The default priority is 99. Something like:

```
dnf config-manager --setopt=salt-latest-repo.priority=90 --save
```

Pros:
* Doesn't require any modifications to salt-bootstrap or to the Salt Install Guide
* Regardless of which repos the machine has installed, the Salt repo will always be preferred for the packages contained in it (unless the user or another repo both has a higher priority (lower number) and contains conflicting packages
* Gives Salt the most control/results in asking users to make fewer modifications to their systems

Cons:
* Salt Project/VMware has to be careful with which packages it offers in the Salt repo so as to not clobber other packages, although this risk is lessened with OneDir
<br>
<br>
3. Ask the maintainer of the EPEL Salt packages to make them part of a module that can be enabled/disabled. This is the option I understand the least, but I believe EPEL supports modules just like the base OS. In this case, the module could be disabled using something like:

```
dnf -qy module disable salt
```

Pros:
* Probably the best solution overall (practicalities excluded). Uses similar methods to other projects with competing packages (ie. Postgres)

Cons:
* Requires cooperation from the EPEL maintainer. Could potentially be broken again by any other new repos containing Salt packages
<br>
<br>
I tend to lean towards option 2 being the most practical solution, as it only requires a small modification to Salt packaging for RPM packages, but I'm not that familiar with what other vendors do in this case and what's considered best practice.
<br>
<br>
Regardless of which method is chosen, it would also be prudent to add tests for AlmaLinux 9 to saltstack/salt-bootstrap#1878 / saltstack/salt-bootstrap#1880

**References**

* saltstack/salt-bootstrap#1883
* #63089 
* [Update RHEL 9 instructions to exclude installing Salt from EPEL](https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues/65)

**Comment by OrangeDog** [comment]
https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues/65

**Comment by barbaricyawps** [comment]
Comment from @dmurphy18  on a related issue:

> I don't believe this is a Salt problem, if the user installs a forked built version of Salt from a different repository, then that is up to them.  For example: Debian and Ubuntu have long forked the Salt project and built their own packages.  It is up to the user to know what they are doing, and to decide which packages to install and from where.

> There is no warning about whose repository to install packages from for Debian / Ubuntu for years and I don't see why we should start doing it for RHEL 9 EPEL now.

> This is for Classic or Tiamat based packages

In light of that comment, I'm closing this issue.
