### ISSUE TITLE
[FEATURE REQUEST]failhard a saltstate when variable or condition is met or not met

### ISSUE THREAD

**Issue by cdorsman** [saltstack/salt#63119]
**Is your feature request related to a problem? Please describe.**

I am frustrated because it is not possible to stop a state when a variable has or hasn’t content that you need for further execution. 

For example: It is possible to fill in a pillar variable. But you cannot stop the state after checking the variable.

**Describe the solution you'd like**

I would like to see that the ‘failhard’ method, or a method named differently, that has the option to stop a state from running when a certain criteria is or is not met. With the option to define the return code if it is True or False on exit

For example. 
- When variable is empty, stop the state
- When a certain exercise is already done according to user, stop the state.

**Comment by OrangeDog** [comment]
Yes you can, for example using a `test.fail_without_changes` state.

Or you can fail earlier in the render phase using `test.assertion`.

**Comment by cdorsman** [comment]
Ok. Then I’ll these possibilities.
