### ISSUE TITLE
[DOCS] TCP transport documentation is out of date

### ISSUE THREAD

**Issue by lukasraska** [saltstack/salt#63120]
**Description**
As discussed on Slack, TCP transport documentation on https://docs.saltproject.io/en/latest/topics/transports/tcp.html is not really up-to-date, for example statement `As of today we send all publishes to all minions and rely on minion-side filtering.` is not really correct, as there is master-side filtering and only for certain cases minion-side filtering is used

**Suggested Fix**
Review the documentation and update it to current behaviour

**Type of documentation**
Salt documentation

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/transports/tcp.html

**Additional context**
I will prepare PR for fixing statements that are not valid anymore.

**Comment by OrangeDog** [comment]
Have you got a link to the Slack discussion?

**Comment by lukasraska** [comment]
@OrangeDog sure, https://saltstackcommunity.slack.com/archives/C7K4F0L8H/p1669017470983609

**Comment by barbaricyawps** [comment]
@lukasraska , since it sounds like you're preparing a PR, I'm going to assign you to this issue so that I know it's being worked on. Thanks for doing that work!
