### ISSUE TITLE
On the service.running module, the flag `enable: True` does not enable a service if that systemd service is an alias

### ISSUE THREAD

**Issue by bobhenz-jabil** [saltstack/salt#63214]
**Description**
On the service.running module the flag `enable: True` does not enable a service if that systemd service an alias.
We have a service `foo.service` which has a systemd alias `fooalias.service`.
If foo.service was disabled, the following salt rule would _start_ it, but would not _enable_ it:
```
will_not_enable_foo_service:
  service.running:
    - name: fooalias.service
    - enable: True
```

**Setup**
Linux

```
> salt --version
salt 3004.2

> systemctl --version
systemd 250 (250.5+)
-PAM -AUDIT -SELINUX -APPARMOR +IMA -SMACK +SECCOMP -GCRYPT -GNUTLS -OPENSSL +ACL +BLKID -CURL -ELFUTILS -FIDO2 -IDN2 -IDN -IPTC +KMOD -LIBCRYPTSETUP +LIBFDISK -PCRE2 -PWQUALITY -P11KIT -QRENCODE -BZIP2 -LZ4 -XZ -ZLIB +ZSTD -BPF_FRAMEWORK +XKBCOMMON +UTMP +SYSVINIT default-hierarchy=hybrid
```

**Steps to Reproduce the behavior**
Create a system service with an alias.
Setup a salt rule that should start and enable it but reference the alias instead of the actual service.
Disable the service with `systemctl disable`
Run salt state.apply
Run systemctl status and observe that the systemd service will have started but is not enabled.

**Expected behavior**
Expected systemd service to be started _and_ enabled.

```yaml
will_not_enable_foo_service:
  service.running:
    - name: fooalias.service
    - enable: True
```
</details>

**Additional context**
It is my understanding that saltstack uses systemctl is-enabled internally to decide if it needs to enable the service.
I believe that this problem with aliases is due to `systemctl is-enabled fooalias.service` will return `alias` and a return value of "0" regardless of the state of foo.service. While that is unfortunate, it appears to be intentional?

There are probably multiple ways to fix this and I don't presume to know saltstack internals, but (in case it's useful) the following command will return the non-alias name of a service: `systemctl show -p Id --value fooalias`

Thank you.

**Comment by OrangeDog** [comment]
The obvious workaround is to not use systemd aliases in Salt states. Is there any case where they're actually required?

**Comment by OrangeDog** [comment]
In case you haven't found it already, the easiest way if you don't already have a list of services in jinja is probably `- name: {{ "snap.blah." if is_snap else "" }}foo.service`.

One more thing to check, is it the same if you just use `fooalias` instead of `fooalias.service`?

**Comment by bobhenz-jabil** [comment]
Correct, that is more-or-less our work around.

Yes, behavior is the same whether we use `fooalias` instead of `fooalias.service`.

**Comment by nicholasmhughes** [comment]
This is due to the underlying `service.enabled` execution module failing to account for aliases. PR inbound.
