### ISSUE TITLE
Non-bootstrap install methods of salt-master and salt-cloud v3005.1-2 have issues with modules

### ISSUE THREAD

**Issue by infantvin** [saltstack/salt#63225]
**Description**

Installing a new salt-master on RHEL9 with any method other than the bootstrap.sh script with arguments.

Post installation, the relevant packages and pip modules are installed like pygit2, pyvmomi, pycrypto etc.

After this, running the salt-master --versions-report or salt-cloud --versions-report never detects the modules installed using pip or yum/dnf commands.

**Setup**

Fresh install of RHEL9/ Firewall etc disabled.

Run any salt installation method other than the bootstrap script method (onedir/install from the repos)
https://docs.saltproject.io/salt/install-guide/en/latest/index.html

Post this, install the modules needed like pygit2/pycrypto/pyvmomi etc using pip3 install or the yum install commands.
Once the install completes, try using salt-cloud --versions-report and salt-master --versions-report

These commands will not detect the installed modules mentioned above even though they are supposed to.

HOWEVER

If the bootstrap.sh method is used to install the master and cloud like below

sh bootstrap-salt.sh -M -L -N onedir 3005.1

then, the pip3 modules installed in this manner will be detected properly without issues when running the versions-report

Please be as specific as possible and give set-up details.

- [ X] VM  on Vsphere/ESXi 7
- [ X] classic packaging
- [ X] onedir packaging
- [ X] used bootstrap to install

**Steps to Reproduce the behavior**

- Install a fresh RHEL9.0 VM
- Follow instructions on the install guide https://docs.saltproject.io/salt/install-guide/en/latest/index.html 
  to install salt-master and salt-cloud using either the OS specific or onedir method
- Install the pygit2/pyvmomi/pycrypto modules which are used by the salt-master and salt-cloud commands using pip install or yum install
- Run the --versions-report in salt-master or salt-cloud to see if the modules are detected. It will show as not installed.

The same exercise can be repeated and the bootstrap.sh script can be used to install the master and cloud

curl -o bootstrap-salt.sh -L https://bootstrap.saltproject.io
sh bootstrap-salt.sh -M -L -N onedir 3005.1

The modules will be detected after install using either pip or yum and the versions-report will see the installed modules.

**Expected behavior**

Either yum or pip3 install will cause the modules needed to be put into /usr/local which python will detect. However this never happens here.

**Screenshots**

Attaching some command output here from a master that has this issue.

**Versions Report**
<details><summary>salt --versions-report</summary>
# salt-master --versions-report
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.15 (main, Nov  1 2022, 00:00:00)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: rhel 9.0 Plow
        locale: utf-8
       machine: x86_64
       release: 5.14.0-70.13.1.el9_0.x86_64
        system: Linux
       version: Red Hat Enterprise Linux 9.0 Plow

# salt-cloud --versions-report
Salt Version:
            Salt: 3005.1

Dependency Versions:
 Apache Libcloud: Not Installed
            cffi: 1.14.6
        cherrypy: 18.6.1
        dateutil: 2.8.1
       docker-py: Not Installed
           gitdb: Not Installed
       gitpython: Not Installed
          Jinja2: 3.1.0
         libgit2: Not Installed
        M2Crypto: Not Installed
            Mako: Not Installed
         msgpack: 1.0.2
    msgpack-pure: Not Installed
    mysql-python: Not Installed
       pycparser: 2.21
        pycrypto: Not Installed
    pycryptodome: 3.9.8
          pygit2: Not Installed
          Python: 3.9.15 (main, Nov  1 2022, 00:00:00)
    python-gnupg: 0.4.8
          PyYAML: 5.4.1
           PyZMQ: 23.2.0
           smmap: Not Installed
         timelib: 0.2.4
         Tornado: 4.5.3
             ZMQ: 4.3.4

System Versions:
            dist: rhel 9.0 Plow
          locale: utf-8
         machine: x86_64
         release: 5.14.0-70.13.1.el9_0.x86_64
          system: Linux
         version: Red Hat Enterprise Linux 9.0 Plow

On the same machine, pip shows the installed modules. You can see the ones the master uses like pycrypto and pygit2 are not detected by the salt-master versions report which is incorrect behavior

```
# pip3 list|grep -E "pygit|pyvm|pycryp"
pycrypto             2.6.1
pycryptodome         3.16.0
pygit2               1.11.1
pyvmomi              8.0.0.1
```

</details>

**Additional context**

My analysis is:

The onedir and install from repo methods are using something called as run which is a elf executable passing arguments such as salt-master and salt-minion etc. This method does not seem to be working correctly to detect the python modules installed in /usr/local 

The bootstrap.sh method mentioned is actually calling a python script which seems to be correctly detecting the directories where these modules are installed.

The result of the failure from the other methods causes salt-cloud and salt-master to fail because they never see the modules needed like pygit2 and pyvmomi resulting in a non-working salt-master.

It looks like the salt package installed is placing all the modules here

/opt/saltstack/salt/pypath/lib/python3.9/site-packages

However, how are we supposed to tell pip or yum to install the modules into this directory as this is salt specific and not the system paths used for the modules?

Is this a broken installation or is something being missed?

Please let me know any information needed from ,e.

**Comment by OrangeDog** [comment]
You need to use the `salt-pip` command or `pip.installed` states to install dependencies for onedir.
https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#how-to-upgrade-to-onedir
