### ISSUE TITLE
[FEATURE REQUEST] states.file - sync/manage entire folder from master state data

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#63318]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
It would be nice to have a function in states.file that allowed you to manage/deploy an entire folder of files in one state command.

For example if i have a folder in my states dir called test with 50 files inside it. Being able to sync that entire dir on the destination system would be nice.

This came up during a conversion of a large set of ansible states to salt. 

The main usecase is that people can just add files to that specific folder in future and they will get deployed in future salt runs without also having to edit state files or pillar data.

**Describe alternatives you've considered**
looping through a list of all files that need to be deployed, but it means maintaining a list of files that need to be deployed instead of just sourcing that information from the src states folder.

**Additional context**
example of what the ansible code does now that im converting
```
- name: copy role files to remote location
  synchronize:
   src: "./roles/rolename/appfiles"
   dest: "/srv/appfiles"
```

**Comment by lkubb** [comment]
Isn't [file.recurse](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.file.html#salt.states.file.recurse) what you are describing?

**Comment by OrangeDog** [comment]
Indeed, this feature already exists.

**Comment by ITJamie** [comment]
My bad. Not sure how i missed that
