### ISSUE TITLE
Minion producing two set of keys on provision

### ISSUE THREAD

**Issue by BLePera** [saltstack/salt#63321]
Recently upgraded from v2019.2 to v3004.2 and 
Noticing an issue after provisioning with Salt-Cloud, causing there to be two public keys for the newly provisioned minion when I run salt-key command. One public key is accepted and is shown when first provisioning. The other is within denied and seems to show right at the completion of the provisioning. This does not allow me to send commands to the minion.
![image](https://user-images.githubusercontent.com/97978005/207737875-585f90dc-2fcf-4440-ae0c-f21b17296017.png)
![image](https://user-images.githubusercontent.com/97978005/207737947-7fe1e5e0-080d-4347-b6c4-648d0df65f89.png)

When looking at the pki directory on the salt minion I found that there were two different directories and they seem to both contain the public keys that are causing the conflict. 
![image](https://user-images.githubusercontent.com/97978005/207738796-70e7363a-33d2-42d5-aae4-3f7578e3b0c2.png)

Removing the key from the master and restarting the service, seems to correct the issue, but does not leave a great experience when provisioning 20+ minions at a time

Command run for provisioning: sudo salt-cloud -m [redacted]-50-asc-map -P

### Setup
Can provide any config if believed to be relevant, I did attempt to find a key that was associated with the minions pki location, but was not able to when looking at documentation.

### Versions Report
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.16.0
        pygit2: Not Installed
        Python: 3.8.10 (default, Nov 14 2022, 12:59:47)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1022-aws
        system: Linux
       version: Ubuntu 20.04 focal

**Comment by OrangeDog** [comment]
Possible duplicate: #62968

**Comment by BLePera** [comment]
Thanks James (@OrangeDog ), looks like a PR was merged for 3006.0, any idea if there is plans to backport? https://github.com/saltstack/salt/pull/63030

**Comment by OrangeDog** [comment]
Bug fixes do not get backports.

**Comment by BLePera** [comment]
I feared that, thank you.
