### ISSUE TITLE
Runas currently logged in user with jinja variable [BUG] 

### ISSUE THREAD

**Issue by Canpy** [saltstack/salt#63346]
Hi, I want to get the current logged in windows user and then store it in a jinja variable

```
{% set user = salt['cmd.run']("((Get-WMIObject -ClassName Win32_ComputerSystem).Username).Split('\')[1]", shell='powershell')
%}

exec:
  cmd.run:
    - name: echo 'test'
    - runas: {{user}} 
```

But in slsutil.renderer it shows "none" in runas

```
/ # salt 'minion01' slsutil.renderer salt://formula/test.sls 'jinja|yaml'
minion01:
    ----------
    exec:
        ----------
        cmd.run:
            |_
              ----------
              name:
                  echo 'test'
            |_
              ----------
              runas:
                  None

```

*The output without sls*
```
/ # salt 'minion01' cmd.run shell=powershell "((Get-WMIObject -ClassName Win32_ComputerSystem).Username).Split('\')[1]"
minion01:
    WS01

```

while other things like echo 'test'  are working

```

{% set user = salt['cmd.run']('echo "test"', shell='powershell') %}
```
```
/ # salt 'minion01' slsutil.renderer salt://formula/test.sls 'jinja|yaml'
minion01:
    ----------
    exec:
        ----------
        cmd.run:
            |_
              ----------
              name:
                  echo 'test'
            |_
              ----------
              runas:
                  test

```

How can I fix this? Is there another way to get the currently logged in user and add him to runas?

**Versions Report**
<details><summary>/ # salt --versions-report
</summary>
/ # salt --versions-report
Salt Version:
          Salt: 3005
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: 1.1.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: 1.6.1
        Python: 3.7.13 (default, Apr 20 2022, 03:16:50)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1
 
System Versions:
          dist: alpine 3.14.6 
        locale: UTF-8
       machine: x86_64
       release: 6.0.12-200.fc36.x86_64
        system: Linux
       version: Alpine Linux 3.14.6
</details>

**Comment by OrangeDog** [comment]
Can you show debug logs for the minion when running that jinja?

**Comment by lukasraska** [comment]
I think the `Win32_ComputerSystem.Username` should under normal circumstances yield the user querying the table (e.g. "logged in"), but as Salt Minion runs under service (and by default under SYSTEM), it's completely possible this value is just null.
While there is `username` grain that contains the user salt-minion runs under, I don't belive it's actually what are you trying to achieve. Can you explain what exactly is the usecase?

**Comment by OrangeDog** [comment]
@lukasraska but the second command does return a user name, so it's not that.

**Comment by Canpy** [comment]
> Can you show debug logs for the minion when running that jinja?
```
                                                          
[DEBUG   ] LazyLoaded cmd.run                                                                                                
[INFO    ] Executing command '"powershell"' in directory 'C:\Users\WS01'                                                     
[DEBUG   ] output:                                                                                                           
[PROFILE ] Time (in seconds) to render 'C:\ProgramData\Salt Project\Salt\var\cache\salt\minion\files\base\formula\test.sls' using 'jinja' renderer: 0.3035588264465332                                                                                 
[DEBUG   ] Results of YAML rendering: 
OrderedDict([('exec', OrderedDict([('cmd.run', [OrderedDict([('name', "echo 'test'")]), OrderedDict([('runas', None)])])]))])
[PROFILE ] Time (in seconds) to render 'C:\ProgramData\Salt Project\Salt\var\cache\salt\minion\files\base\formula\test.sls' using 'yaml' renderer: 0.0009980201721191406

```

**Comment by Canpy** [comment]
> I think the `Win32_ComputerSystem.Username` should under normal circumstances yield the user querying the table (e.g. "logged in"), but as Salt Minion runs under service (and by default under SYSTEM), it's completely possible this value is just null. While there is `username` grain that contains the user salt-minion runs under, I don't belive it's actually what are you trying to achieve. Can you explain what exactly is the usecase?

The minions are running as a system user. I have powershell scripts I want to run on the minion where the variable $env:AppData is in it, instead of going into the directory "C:\Users\user\AppData\Roaming" it goes into this: "C:\Windows\System32\config\systemprofile\AppData\Roaming" which I don't want. 

The only way that I have found is to bypass this with "runas", but minions have different usernames, so I want to try to automate this. Maybe there is another and better way?

**Comment by Canpy** [comment]
{% set user = salt['cmd.run']("((Get-WMIObject -ClassName Win32_ComputerSystem).Username).Split('\\')[1]", shell='powershell') %}

Fixed it by using two backslashes \\
