### ISSUE TITLE
[FEATURE REQUEST] set max queue size for state runs

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#63356]
**Is your feature request related to a problem? Please describe.**
The `queue=True` parameter to state module functions allows a new state run to be queued and wait for a run already in progress to complete before proceeding. However, there is currently no limit to how many runs will wait in the queue. If state runs are being performed on an interval and the runs take longer than the interval time, the queue could stack up indefinitely until the machine "falls over".

**Describe the solution you'd like**
Allow the `queue` parameter to be set to an integer, which will be checked against the current queue size. If the queue is greater than or equal to maximum, then that specific run will be treated as if `queue=False` and return a conflict.

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by OrangeDog** [comment]
If state runs are being performed on an interval then you don't want to be using `queue` at all. If the previous one is still going, there's no point doing another as soon as it's finished.

Queuing is useful when you're manually running something different.
