### ISSUE TITLE
[DOCS] Need to document how to adding net-api clients to the master config

### ISSUE THREAD

**Issue by barbaricyawps** [saltstack/salt#63362]
**Description**
As a result of https://github.com/saltstack/salt/pull/63050 , which is a breaking change, we need to add documentation to the NetAPI module introduction that explains in-depth how to add clients to the master config in order to prevent disruption of services.

**Type of documentation**
Core Salt documentation.

**Location or format of documentation**
The doc that needs to be updated is in `doc > topics > netapi > index.rst` .

We could put it in a different location if you think that would be more helpful.

**Comment by barbaricyawps** [comment]
@barneysowood , sorry that it took me awhile to follow up on this, but I wanted to create an issue to ensure that we capture the specific steps for adding the clients to the master config file. If you want to explain the process to me, I could make sure it gets documented or you could write the documentation and tag me on a review. Do you have a preference?

**Comment by barbaricyawps** [comment]
@barneysowood , I'm hoping that now that people are returning to work, you might have a chance to take a look at this issue and give me your thoughts?

**Comment by barneysowood** [comment]
@barbaricyawps - I'm happy to add some additional documentation to expand what I put in https://github.com/saltstack/salt/pull/63050, I can see that's not really detailed enough, especially for existing users of the salt-api who are upgrading.

I'm not entirely sure if `doc > topics > netapi > index.rst` is the right place for that - that page is not the obvious place to look, it _might_ be better to add a new page and then ensure that's linked from each of the netapi modules where they describe how to config the master.

That page is also weird and somewhat broken I think.. the way it's returning data about NetapiClient is confusing. I also have no idea why it includes links to `doc > topics > tutorials > http`. I'll open a PR to clean that up.

Coming back to the process for users upgrading, that's going to be:

* Identify which netapi "clients" you use
* Add those to the config option in the master config
* Restart the master and test

The issues with documenting that are:

* There's no standard client application for the salt-api and many user will have custom written code to access it, so it's not possible to just say "if you are using this option, enable this client". I think best I could do is give examples using curl..
* Users may not know what netapi clients they are using. The easy option from their point of view is to enable all the clients, but that entirely negates the point of the change.

As I think this might end up being quite lengthy, I think adding it as a separate page makes sense - what do you think @barbaricyawps?

I'll try doing that and see how it comes out and ask for some feedback.

**Comment by barbaricyawps** [comment]
@barneysowood , this is super helpful. Thanks for providing so much information. I think I agree with you that adding a new page of documentation and then linking to it from the NetAPI module would be the best approach and I agree with your other recommendations about how to approach this documentation.

I will add this to my queue of tasks to do, but I might not be able to actively work on this until next week. If you would prefer to take this task on, just let me know.

**Comment by barneysowood** [comment]
@barbaricyawps - I'm happy to take this on.

**Comment by barbaricyawps** [comment]
@barneysowood , that's very generous of you. Please let me know if you would like any additional support from me in terms of the approach to the documentation. I'm also happy to provide a review when you have a PR ready.
