### ISSUE TITLE
Salt master on machine with alot of cpu cores starts very slow, few minutes

### ISSUE THREAD

**Issue by gzivdo** [saltstack/salt#63368]
**Description**
Each salt master subprocess runs lshw, then lspci. I have multi cpu system with many cores each, i configured 1k+ worker_threads.
When master starts all 1k+ subprocess of it running the same lshw + lspci about 2 minutes. Server is unresponsible.
Why to do that?

May be run only on one main process, then pass that data to all subprocesses.

**Comment by OrangeDog** [comment]
> I configured 1k+ worker_threads

Why? You have 250+ cores and millions of minions?

**Comment by Oloremo** [comment]
While `worker_threads` count is insane, it's not related to the issue. It doesn't matter if it is 1000 or 2 in the described case if every worker does duplicated work.

**Comment by gzivdo** [comment]
> > I configured 1k+ worker_threads
> 
> Why? You have 250+ cores and millions of minions?
Something like that.

> While `worker_threads` count is insane, it's not related to the issue. It doesn't matter if it is 1000 or 2 in the described case if every worker does duplicated work.
exactly

**Comment by dwoz** [comment]
Based on the information provided we can not reproduce this issue. I am not aware of salt master running lspci for any reason. I'm closing this, if it's still an issue please open a new issue and provide some more info as well as a version report.
