### ISSUE TITLE
[DOCS] Missing documentation about __states__

### ISSUE THREAD

**Issue by network-shark** [saltstack/salt#63412]
Hey Salties, 

recently I created my own custom state. I tried to figure out how to call another state from my custom state, but there is no documentation about it. Glad someone on slack pointed me in the right direction to use 
```
__states__ 

```

**Comment by bdrx312** [comment]
The documentation for cross calling another state from a custom state is here https://docs.saltproject.io/en/latest/ref/states/writing.html#cross-calling-state-modules
