### ISSUE TITLE
[TECH DEBT] ADAL to MSAL change

### ISSUE THREAD

**Issue by localden** [saltstack/salt#63447]
Hi folks - I am a PM on the Microsoft Identity SDK team. I've noticed that the project [takes a dependency on ADAL](https://github.com/saltstack/salt/blob/master/DEPENDENCIES.md?plain=1#L15). This library will hit end-of-support by June of this year (2023) - the recommended path forward here is to update this to MSAL (there is [a Python release](https://github.com/AzureAD/microsoft-authentication-library-for-python)).

What's the best path to make the change? 

This will affect the Azure token acquisition mechanism - I see that there are no direct references in code to the library, but it _likely_ comes through other librarires (such as [`msrestazure`](https://pypi.python.org/pypi/msrestazure) - which is [deprecated](https://github.com/Azure/msrestazure-for-python)).

**Comment by nicholasmhughes** [comment]
closing in favor of https://github.com/salt-extensions/saltext-azurerm/issues/23
