### ISSUE TITLE
[TECH DEBT]failed to check remote refs: fatal : unable to access 'https://<redacted>@dot-portal.com

### ISSUE THREAD

**Issue by chayanshah** [saltstack/salt#63479]
### Description of the tech debt to be addressed, include links and screenshots

while running git.latest module . we are trying to fetch our GITLAB repo  but faling and comment is showing (mentioned in heading) . we are able to clone the GITLAB repo manually on our container but with salt module its not happening . please help

### Versions Report
(Provided by running `salt --versions-report`. Please also mention any differences in master/minion versions.)
salt:3004

**Comment by OrangeDog** [comment]
Please fill out a BUG report, with all the information the template asks for, including the full versions report,

**Comment by OrangeDog** [comment]
Refiled as #63489
