### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by linuxstudent** [saltstack/salt#63470]
**Description**

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [X ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**
I've installed salt about 3 times started the service, enabked the service and configured the master, however, my minions are not talking to to the master and from several articles, the solutiuon was to kill all services and restart but seems to not be working. Instead I keep getting this message "salt-master[30737]: [ERROR   ] ReqServer clients tcp://X.X.X.X:4506"
"salt-master[30737]: [ERROR   ] ReqServer workers ipc:///var/run/salt/master/workers.ipc"

**Screenshots**
![image](https://user-images.githubusercontent.com/35510151/212097045-56242fbf-9cd1-4740-9c81-638e3f658fc1.png)

**Versions Report**
<details><summary>salt --versions-report</summary>
salt --version
salt 3005.1

(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
Please edit to fill in the template, including a title, description, setup, and versions report.

The ReqServer log messages are already solved: #62686

**Comment by Mathieu-Steininger** [comment]
Hello, I just installed a 3005.1 on ubuntu 22.04 on azure vm. I followed the doc using apt commands.
But the message still there on a `systemctl status salt-master`
```
● salt-master.service - The Salt Master Server
     Loaded: loaded (/lib/systemd/system/salt-master.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2023-02-15 17:11:28 UTC; 15min ago
       Docs: man:salt-master(1)
             file:///usr/share/doc/salt/html/contents.html
             https://docs.saltproject.io/en/latest/contents.html
   Main PID: 7931 (salt-master)
      Tasks: 37 (limit: 9530)
     Memory: 288.5M
        CPU: 7.339s
     CGroup: /system.slice/salt-master.service
             ├─7931 /usr/bin/python3 /usr/bin/salt-master
             ├─7978 /usr/bin/python3 /usr/bin/salt-master
             ├─7979 /usr/bin/python3 /usr/bin/salt-master
             ├─7982 /usr/bin/python3 /usr/bin/salt-master
             ├─7983 /usr/bin/python3 /usr/bin/salt-master
             ├─7985 /usr/bin/python3 /usr/bin/salt-master
             ├─7986 /usr/bin/python3 /usr/bin/salt-master
             ├─7987 /usr/bin/python3 /usr/bin/salt-master
             ├─7995 /usr/bin/python3 /usr/bin/salt-master
             ├─7996 /usr/bin/python3 /usr/bin/salt-master
             ├─7997 /usr/bin/python3 /usr/bin/salt-master
             └─9127 /usr/bin/python3 /usr/bin/salt-master

Feb 15 17:11:27 salt-server systemd[1]: Starting The Salt Master Server...
Feb 15 17:11:28 salt-server systemd[1]: Started The Salt Master Server.
Feb 15 17:11:28 salt-server salt-master[7985]: [ERROR   ] ReqServer clients tcp://xx.xx.xx.xx:4506
Feb 15 17:11:28 salt-server salt-master[7985]: [ERROR   ] ReqServer workers ipc:///var/run/salt/master/workers.ipc
```

```
sudo salt '*' test.version
rebel_1:
    3005.1
```
I think that everything is ok, but ... not sure

salt --versions-report
```
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.9
     gitpython: 3.1.24
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: Not Installed
        Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: 5.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 Jammy Jellyfish
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1033-azure
        system: Linux
       version: Ubuntu 22.04 Jammy Jellyfish
```

**Comment by garethgreenaway** [comment]
@Mathieu-Steininger The fix that was referenced likely went into the 3006 release.  Can you test that and if the issue persists please open a new issue.  Thanks!
