### ISSUE TITLE
file.keyvalue should create the file if it doesn't exist

### ISSUE THREAD

**Issue by TheNetworkIsDown** [saltstack/salt#63545]
If you don't yet have a file that you would like to create by key/value pairs, then this state should just create it.
Or at least be able to do it by using a "create=xxx" option.

**Comment by OrangeDog** [comment]
If this feature is added, then `file.replace` should also get it.

If you are wanting to manage (and create) an entire key-value file, then in 3006 you will be able to use `file.serialize` with `serializer: keyvalue`.
