### ISSUE TITLE
[FEATURE REQUEST] tools vm list - ability to list the VMs you currently have active

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#63543]
**Is your feature request related to a problem? Please describe.**
Have no ability to list the VMs I may have active / in-active with tools vm create

**Describe the solution you'd like**
Want a ```tools vm list``` command to list the VMs that have been created with ```tools vm create``` for when you forgotten what you have created.  Even though the VMs currently only exist for approx. 12 hours, after a long day, you can forget what you created and it would be great to get a list of those VMs currently available.

The new command ```tools vm list``` should output name and IP Address, to facilitate ability to copy with scp to it.
Running ```ip a``` from inside the VM gives 10.x.x.x addresses rather than the publically accessible IP address, such as, 54.187.67.80 (made up).

**Describe alternatives you've considered**
Keep better notes as to what you have created.

**Additional context**

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by OrangeDog** [comment]
Salt doesn't have a `tools` command...

**Comment by dmurphy18** [comment]
@OrangeDog This is on-going work for Sulfur as part of a new pipeline incorporating GitHub Actions etc.  And I noticed from debugging all day, 'what VMs did I create again ?', hence the want for a list option.

**Comment by OrangeDog** [comment]
RIght, but what's it for? Feature requests in here are usually feature requests for Salt, because this is Salt's issue tracker.
This issue has no context. What is this `tools` command and where is the source for it?

**Comment by dmurphy18** [comment]
@OrangeDog Picked a place to track the issue, and get additional feature. This is being done / used for Sulfur RC 1 and relenv and GitHub Actions use. Not ready for prime time yet but hopefully soon. 
This was part of getting pkg tests working on the new pipeline for Sulfur, still a work in progress.
Attend next open hour and ask there.

**Comment by MKLeb** [comment]
Closed by: https://github.com/saltstack/salt/pull/64663

**Comment by MKLeb** [comment]
Closed by: https://github.com/saltstack/salt/pull/64663
