### ISSUE TITLE
[BUG] Arista native minion net.load_config not working

### ISSUE THREAD

**Issue by xpress2001** [saltstack/salt#63578]
**Description**
testing arista eos native minion and stuck on an issue with napalm. i can do net.arp and net.cli , etc but it errors out on net.load_config with errors. napalm.conf has correct creds with privilege. 

**Setup**
Please be as specific as possible and give set-up details.

- [x] on-prem machine (arista switch)
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
IP, userid and password are masked.
1. on master
salt netauto-arista-dev-sw1 net.load_config text='ntp server y.y.y.y' test=True

2. on eos test switch

-bash-4.3# cat /etc/salt/minion.d/pyeapi.conf
pyeapi:
  username: [USERID]
  password: [PW]
  transport: socket

-bash-4.3# cat /etc/salt/minion.d/napalm.conf
napalm:
  username: [USERID]
  password: [PW]
  host: netauto-arista-dev-sw1
  driver: eos

**Expected behavior**
expecting the command 'ntp server y.y.y.y' added via net.load_config

**Screenshots**
```~#salt netauto-arista-dev-sw1 net.load_config text='ntp server y.y.y.y' test=True
netauto-arista-dev-sw1:
    ----------
    already_configured:
        False
    comment:
        Cannot execute "compare_config" on netauto-arista-dev-sw1 as [USERID]. Reason: Error [1000]: CLI command 2 of 2 'show session-config named napalm_439652 diffs' failed: could
 not run command [Session napalm_439652 does not exist]!
    diff:
        None
    loaded_config:
    out:
        ----------
    result:
        False
    traceback:
        Traceback (most recent call last):
          File "napalm/eos/eos.py", line 329, in _load_config
            self.device.run_commands(commands, fn0039_transform=self.fn0039_config)
          File "napalm/eos/pyeapi_syntax_wrapper.py", line 42, in run_commands
            return super(Node, self).run_commands(commands, *args, **kwargs)
          File "pyeapi/client.py", line 771, in run_commands
            response = self._connection.execute(commands, encoding, **kwargs)
          File "pyeapi/eapilib.py", line 554, in execute
            response = self.send(request)
          File "pyeapi/eapilib.py", line 473, in send
            raise CommandError(code, msg, command_error=err, output=out)
        pyeapi.eapilib.CommandError: Error [1000]: CLI command 2 of 3 'configure session napalm_439652' failed: could not run command [Maximum number of pending sessions has been reached. Please
 commit or abort previous sessions before creating a new one.]
During handling of the above exception, another exception occurred:

        Traceback (most recent call last):
          File "salt/utils/napalm.py", line 171, in call
            out = getattr(napalm_device.get("DRIVER"), method)(*args, **kwargs)
          File "napalm/eos/eos.py", line 344, in load_merge_candidate
            self._load_config(filename, config, False)
          File "napalm/eos/eos.py", line 331, in _load_config
            self.discard_config()
          File "napalm/eos/eos.py", line 415, in discard_config
            self.device.run_commands(commands)
          File "napalm/eos/pyeapi_syntax_wrapper.py", line 42, in run_commands
            return super(Node, self).run_commands(commands, *args, **kwargs)
          File "pyeapi/client.py", line 771, in run_commands
            response = self._connection.execute(commands, encoding, **kwargs)
          File "pyeapi/eapilib.py", line 554, in execute
            response = self.send(request)
          File "pyeapi/eapilib.py", line 473, in send
            raise CommandError(code, msg, command_error=err, output=out)
        pyeapi.eapilib.CommandError: Error [1000]: CLI command 2 of 3 'configure session napalm_439652' failed: could not run command [Maximum number of pending sessions has been reached. Please
 commit or abort previous sessions before creating a new one.]

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
master
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: Not Installed
      cherrypy: unknown
      dateutil: 2.6.1
     docker-py: Not Installed
         gitdb: 2.0.3
     gitpython: 2.1.8
        Jinja2: 2.10
       libgit2: 0.26.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: 2.6.1
  pycryptodome: 3.4.7
        pygit2: 0.26.2
        Python: 3.6.9 (default, Nov 25 2022, 14:10:45)
  python-gnupg: 0.4.1
        PyYAML: 3.12
         PyZMQ: 17.1.2
         smmap: 2.0.3
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.5

System Versions:
          dist: ubuntu 18.04 Bionic Beaver
        locale: UTF-8
       machine: x86_64
       release: 4.15.0-20-generic
        system: Linux
       version: Ubuntu 18.04 Bionic Beaver

```yaml
minion (eos switch)
-bash-4.3# salt-minion --versions-report
Salt Version:
          Salt: 3003.3

Dependency Versions:
          cffi: 1.14.4
      cherrypy: 17.4.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.17
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 18:00:48)
  python-gnupg: 0.4.4
        PyYAML: 5.4.1
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.1

System Versions:
          dist: eos
        locale: ANSI_X3.4-1968
       machine: x86_64
       release: 4.9.122.Ar-15576426.4224M
        system: Linux
       version: Arista Networks EOS 4.22.4M

```
</details>

**Additional context**
following net commands are working.
net.arp
net.lldp
net.cli

**Comment by dmurphy18** [comment]
@xpress2001 Need the version of the EOS Arista equipment, and can you try the latest version of salt-minion for EOS, since 3003.3 is EOL.

**Comment by xpress2001** [comment]
EOS version is 4.22.4M.
I've just tried 3004.2-1 on minion but same result.

```-bash-4.3# salt-minion --versions-report
Salt Version:
          Salt: 3004.2

Dependency Versions:
          cffi: 1.14.3
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.14.1
        pygit2: Not Installed
        Python: 3.7.7 (default, Apr  8 2020, 11:06:31)
  python-gnupg: Not Installed
        PyYAML: 6.0
         PyZMQ: 21.0.2
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.3

System Versions:
          dist: eos
        locale: utf-8
       machine: x86_64
       release: 4.9.122.Ar-15576426.4224M
        system: Linux
       version: Arista Networks EOS 4.22.4M```

**Comment by dmurphy18** [comment]
The traceback looks to be napalm and pyeapi errors, the native salt-minion includes those, when it is being built, but only utilizes it as a dependency.

On 32-bit  the requirements are:
pyeapi>=0.8.3   (probably used 0.8.4 in 3005.1)
napalm==3.4.1  

On 64-bit  the requirements are:
pyeapi>=0.8.3   (probably used 0.8.4 in 3005.1)
napalm              (probably used 4.0.0 in 3005.1)

**Comment by dmurphy18** [comment]
@xpress2001 that appears to be a 32-bit EOS system, can you confirm ?

**Comment by xpress2001** [comment]
correct. 32-bit EOS. (model 7010T)

**Comment by dmurphy18** [comment]
Thanks, currently head deep in another issue, but will take a look next week as time allows with 3005.1, but worried this is a naplam/pyeapi issue, given the error is :
```
pyeapi.eapilib.CommandError: Error [1000]: 
CLI command 2 of 3 'configure session napalm_439652' failed: 
could not run command [Maximum number of pending sessions has been reached.
Please commit or abort previous sessions before creating a new one.]
```

And Salt is just calling into naplam/pyeapi.

**Comment by xpress2001** [comment]
@dmurphy18 , any chance to take a look at this?

**Comment by xpress2001** [comment]
there were pending jobs (config sessions) on the switch. After I cleared all conf sessions. I get different message upon net.load_config.

root@dc6-arista-salt-syndic-dev-01:/etc# salt netauto-arista-dev-sw1 net.load_config text='ntp server 10.120.237.36'
netauto-arista-dev-sw1:
    Passed invalid arguments to net.load_config: can't pickle SSLContext objects

        Applies configuration changes on the device. It can be loaded from a file or from inline string.
        If you send both a filename and a string containing the configuration, the file has higher precedence.

        By default this function will commit the changes. If there are no changes, it does not commit and
        the flag ``already_configured`` will be set as ``True`` to point this out.

        To avoid committing the configuration, set the argument ``test`` to ``True`` and will discard (dry run).

        To keep the changes but not commit, set ``commit`` to ``False``.

        To replace the config, set ``replace`` to ``True``.

        filename
            Path to the file containing the desired configuration.
            This can be specified using the absolute path to the file,
            or using one of the following URL schemes:
[OUTPUT OMMITED]

**Comment by dmurphy18** [comment]
With support for Arista moving to a community repository, going to close this issue since not the correct place for it.  Even when Salt did provide internal support for Arista, it would have been actually duplicated in a GitLab repository where support for the various Native Minions was maintained, in their individual repositories.

Please duplicate the issue if you desire on the Git Hub repository https://github.com/vmware/salt-native-minion-for-arista.
