### ISSUE TITLE
[DOCS] reactors should have unquie state ids to avoid nameing conflicts. 

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#63589]
**Description**
currently the documentation for reactors does not call out that reactors should have unique state ids. this normally might not be a problem in most cases. however it is possible to have a name collision. which will cause reactors to silently fail or not run. 

the possibility of name collision is called out in the code. at https://github.com/saltstack/salt/blob/4ec04292e5da528c5dc8b93ed2455a200589e08f/salt/utils/process.py#L448-L450

**Suggested Fix**
document the possibility of name collision causing dropped reactors.

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/reactor/index.html

**Additional context**
This can cause an almost undetectable issue where a reactor will just not run and no error messages being displayed.

**Comment by OrangeDog** [comment]
Wouldn't they be reactor ids, not state ids?

**Comment by whytewolf** [comment]
While i would agree that name makes more sense. the chunk is still called a state. and the file is still an sls module. 

Also. currently is it is expected behavior. and commented as such in the code.
