### ISSUE TITLE
[DOCS] https://docs.saltproject.io is erroring

### ISSUE THREAD

**Issue by sinkingpoint** [saltstack/salt#63604]
Seems like the docs have started giving an error (e.g. https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.pillar.html):

![Screenshot 2023-02-02 at 09 23 24](https://user-images.githubusercontent.com/4386405/216177473-ebd9b81d-8db3-4414-ba3e-d2b990607318.png)

**Comment by whytewolf** [comment]
thank you for the information. the pages are back up and running. thank you.
