### ISSUE TITLE
[DOCS] "service" state and module docs do not mention that systemd daemon is reloaded

### ISSUE THREAD

**Issue by dafyddj** [saltstack/salt#63601]
**Description**
When systemd unit files are changed or extended the systemd daemon needs to be reloaded to read in the new files.
Salt provides an execution module function to do this: `service.systemctl_reload`

However nowhere is it documented that the `service` state does this automatically when running on a `systemd` minion.

This leads to people setting up their own methods of reloading the daemon.

**Suggested Fix**
The `service` state documentation and the `systemd_service` module documentation should make clear that this built-in feature exists.
**Type of documentation**
Salt state and module documentation.

**Location or format of documentation**
https://docs.saltproject.io/en/latest/ref/states/all/salt.states.service.html
and/or
https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.systemd_service.html#salt.modules.systemd_service.systemctl_reload

**Additional context**
I'm referring to the use of the function: `_check_for_unit_changes()`
https://github.com/saltstack/salt/blob/master/salt/modules/systemd_service.py#L136

**Comment by Lillecarl** [comment]
@barbaricyawps
I also misinterpreted this, I've written my own cmd.wait's before to reload if i change a unit file.

**Comment by barbaricyawps** [comment]
I triage docs issues on Mondays and will look at this at that time.

**Comment by barbaricyawps** [comment]
This seems like a relatively easy docs fix. I'm adding the community labels for "quick fix" and "help wanted" and hopefully someone will pick it up.

**Comment by Lillecarl** [comment]
For those looking to contribute for the first time, documentation is within the functions, you'll find it here https://github.com/saltstack/salt/blob/master/salt/states/service.py.

I don't see anywhere in the code that it does a reload at all @dafyddj could you point to the lines where this happens? Having this behavior automatic is actually a bit weird because you lose control by implicitly reloading all units.

**Comment by CharityKithaka** [comment]
I could pick it up.

**Comment by Tanmoy037** [comment]
I want to work on this please assign it to me

**Comment by barbaricyawps** [comment]
@Tanmoy037 , you got it.
