### ISSUE TITLE
Alternative key exchange mechanism using ssh-sub system

### ISSUE THREAD

**Issue by dbrainnet** [saltstack/salt#6364]
Per our conversation during the salt sprint we're looking for a way to restrict minion to master authentication via IP.

We spoke about using a pre-authentication handshake via ssh-sub system and automatically pre-seed the minion with a key generated from the master.

**Comment by arroyoc** [comment]
@thatch45 any update on this? If this feature still falls into the category insecurity then I think we should close it.

**Comment by arroyoc** [comment]
I am closing this ticket due to inactivity, if anyone feels that this feature needs more attention, feel free to reopen it.
