### ISSUE TITLE
[DOCS] Salt's `--preview-target` option is not listed in the man page.

### ISSUE THREAD

**Issue by andrew-vant** [saltstack/salt#63661]
It's a small thing, but this extremely-useful option isn't documented in salt's man page. I wished for something like it for a long time, and didn't realize until this morning that it's already there, and has been for five years (added in 49120b6d by @cachedout ).

(it does appear in the --help output, along with a number of other missing options. I'm not sure why the discrepancy between the two)

**Comment by OrangeDog** [comment]
Part of #60677.

**Comment by barbaricyawps** [comment]
@andrew-vant , thanks for reporting. I've added your note to issue https://github.com/saltstack/salt/issues/60677 . Since this is a duplicate of that issue, I'm going to close that issue.
