### ISSUE TITLE
[BUG]Amazon Linux 1 [Errno 14] HTTPS Error 404 - Not Found

### ISSUE THREAD

**Issue by smmnazar** [saltstack/salt#63689]
**Description**
Amazon Linux 1 getting problem accessing Salt repo and getting [Errno 14] HTTPS Error 404 - Not Found error. Not able to install any packages that belongs to Salt repo. 

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] VM running on a cloud service, please be explicit and add details. AWS Amazon Linux 1

**Steps to Reproduce the behavior**
any command with yum. I tried "yum list installed"

**Expected behavior**
It has to show what are packages installed 

**Screenshots**
![image](https://user-images.githubusercontent.com/11322262/217904307-bb8eae02-a51c-4d8a-b24a-6bba264b94da.png)

**Additional context**
Please let us know if there is working repo available for Amazon Linux 1?

**Comment by OrangeDog** [comment]
The repos moved to https://repo.saltproject.io nearly two years ago.

https://saltproject.io/repo-and-bootstrap-changes/
