### ISSUE TITLE
[DOCS] Multiple sources of documentation have conflicting information (meta)

### ISSUE THREAD

**Issue by joshmcorreia** [saltstack/salt#63690]
**Description**
I've recently been learning Salt and I've noticed that there are many different sources for documentation... But they all have conflicting information. What is the most up-to-date resource for documentation? Why are there so many different areas that documentation can be found? Why does their information differ?

For example I am trying to learn about Beacons. I found FOUR different documentation sources that all have differing information
- https://docs.saltproject.io/en/getstarted/event/beacons.html
- https://docs.saltproject.io/en/latest/topics/beacons/index.html
- https://docs.saltproject.io/salt/user-guide/en/latest/topics/beacons.html
- https://github.com/saltstack/salt/blob/master/doc/topics/beacons/index.rst

They all have different ways to set up the Beacon config files, most of which do not work. This ticket is not about Beacons, but this just serves as an example.

**Suggested Fix**
Have a single source for documentation.

**Type of documentation**
All documentation

**Comment by OrangeDog** [comment]
There isn't one.

They're all targeted at different audiences, but effort is not made to keep them in sync. And people usually find it easier to write a new set of documentation than to maintain an existing one.

The newest documentation is https://docs.saltproject.io, but that's the hardest to keep accurate because it's in an entirely separate repo (and repo host) to what it's documenting.

**Comment by OrangeDog** [comment]
Also note that https://github.com/saltstack/salt/blob/master/doc/topics/beacons/index.rst is just the source code for https://docs.saltproject.io/en/latest/topics/beacons/index.html, not a separate thing.

**Comment by joshmcorreia** [comment]
> The newest documentation is https://docs.saltproject.io/, but that's the hardest to keep accurate because it's in an entirely separate repo (and repo host) to what it's documenting.

What do you mean by it's a separate repo? The docs seem to be in the [same repo as the source code](https://github.com/saltstack/salt) unless I'm missing something

**Comment by OrangeDog** [comment]
Sorry, they're all on the same domain. It's [this one](https://docs.saltproject.io/salt/user-guide/en/latest/topics/beacons.html) that's on GitLab instead of here.

**Comment by joshmcorreia** [comment]
If I make PRs to update the documentation in [this repo](https://github.com/saltstack/salt/tree/master/doc) will it be reviewed or completely ignored in favor of the GitLab one?

**Comment by OrangeDog** [comment]
No, they're entirely separate documentation maintained separately.

**Comment by joshmcorreia** [comment]
Okay great, thank you :)
