### ISSUE TITLE
[DOCS] Need clarification in autoaccept_grains documentation about only working with strings

### ISSUE THREAD

**Issue by gee456** [saltstack/salt#63708]
**Description**
When using autoaccept_grains the documentation does not state that the match will only for for grains that are strings.
It will not work for integers, lists of strings or Booleans as well. 

**Suggested Fix**
Note in documentation that the grain must be a string and give examples.

Here are some grains that wont work that are not custom grains.
efi-secure-boot - it's a Boolean
ipv4 - it's a list
server_id - It's an integer

**Type of documentation**
Current docs are here (https://docs.saltproject.io/en/latest/topics/tutorials/autoaccept_grains.html)

**Location or format of documentation**
https://docs.saltproject.io/en/latest/topics/tutorials/autoaccept_grains.html

**Additional context**

**Comment by joshmcorreia** [comment]
FYI this is related to https://github.com/saltstack/salt/issues/61436#issuecomment-1008899410

**Comment by BabaYaga1221** [comment]
@gee456 I am interested to resolve this issue. can you give more details about file structure and documentation?

**Comment by Tanmoy037** [comment]
@barbaricyawps I want to give it a try, please assign this to me.

**Comment by barbaricyawps** [comment]
I would assign you @Tanmoy037 , but it looks like @BabaYaga1221 would like to work on the issue as well. Who should take it? Let me know and I'll assign one of you.

**Comment by BabaYaga1221** [comment]
@barbaricyawps We both will appreciate working on this issue. Please, provide related information and file structure, after that whosoever gives PR first, can close others.

**Comment by barbaricyawps** [comment]
I think it's a good practice to get used to the file structure yourself and see if you can map what you see on the web with where it is in the codebase. Let me give a hint: 

- For modules: `salt > salt >`
- For regular topics: `doc > topics`

If that hint isn't helpful enough, let me know and I'll give more.

**Comment by Tanmoy037** [comment]
@barbaricyawps This issue will not fix with doc change, it's a bug I'm working on it please assign it to me.

**Comment by barbaricyawps** [comment]
@Tanmoy037 , I've assigned you. Thanks!
