### ISSUE TITLE
Impossible to run salt command via Python subprocess

### ISSUE THREAD

**Issue by swood** [saltstack/salt#63713]
Hello.

I am trying to write a simple thing: run salt state.apply via a Python3 script, catch all exceptions and errors and put it into the output in a more friendly way as Salt does.
However, when I execute the simple subprocess.check_output script, I get:
`Authentication error occurred.`

In salt-master log I get:
` Authentication failure of type "user" occurred.`

Could anyone please help me to understand what is this error is about?

**Comment by OrangeDog** [comment]
If you believe you have found a bug please fill out the bug template properly with all the details it requests.

I suspect this is a simple case of you not having the correct user authentication.

**Comment by Akm0d** [comment]
@swood Unable to replicate without more details.  Please completely fill out a bug template if this is still an issue.
