### ISSUE TITLE
[BUG] onlyif doesnt work properly on windows 

### ISSUE THREAD

**Issue by nazarama** [saltstack/salt#63743]
**Description**
After upgrade from salt 2019 to 3004.2 onlyif condition doesnt work properly on windows OS.  Check more details below. 

**#note:  used text file doesn't exist on minion.** 
Below example works on salt 2019 and doesnt on 3004.2
```
test_onlyif:
  cmd.run:
    - name: hostname
    - shell: powershell
    - onlyif: {{ salt['file.file_exists']( 'c:\\test.txt2' ) }}
```
EXECUTION
```
**salt 3004.2  minion / master**
salt /win_minion/   state.sls test.test_onlyif 
----------
          ID: test_onlyif
    Function: cmd.run
        Name: hostname
      Result: True
     Comment: Command "hostname" run
     Started: 07:54:21.609094
    Duration: 22675.878 ms
     Changes:
              ----------
              pid:
                  5628
              retcode:
                  0
              stderr:
              stdout:
                  u06b1i01

Summary for ****
------------
Succeeded: 1 (changed=1)
Failed:    0
------------
Total states run:     1
Total run time:  22.676 s

**salt 2019  minion/master**
salt /win_minion/  state.sls test.test_onlyif 

  Name: hostname - Function: cmd.run - Result: Clean Started: - 08:05:10.618517 Duration: 0.0 ms

Summary for u03ps01.develop02.eu-de-1
------------
Succeeded: 1
Failed:    0
------------
Total states run:     1
Total run time:   0.000 ms

```
-----------------------------------------------------------------------------
It works only if i used  - onlyif_args:
```
test_onlyifv2:
   cmd.run:
      - name: hostname
      - shell: powershell
      - onlyif: file.file_exists
      - onlyif_args:
         - c:\\test2.txt
```
or if there is used another condition with exit result as f.ex: 
```
{% set path = salt['pillar.get']('path') -%}
test1:  
  cmd.run:    
       - name: echo "{{ path }}"    
       - onlyif: 'if not exist {{ path }} exit 1'

```
**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)
above
Please be as specific as possible and give set-up details.

- [X ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
above, nothing in logs

**Expected behavior**
To operate with true false result. 
I have workaround but i would like to understand why it works differently on windows. 

**Screenshots**

**Versions Report**
master:
salt-call test.versions_report
local:
    Salt Version:
              Salt: 3004

    Dependency Versions:
              cffi: 1.13.2
          cherrypy: Not Installed
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: Not Installed
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: 0.35.2
              Mako: Not Installed
           msgpack: 0.5.6
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.17
          pycrypto: Not Installed
      pycryptodome: Not Installed
            pygit2: Not Installed
            Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
      python-gnupg: Not Installed
            PyYAML: 5.4.1
             PyZMQ: 17.1.2
             smmap: Not Installed
           timelib: Not Installed
           Tornado: 4.5.3
               ZMQ: 4.2.3

    System Versions:
              dist: sles 15.3 n/a
            locale: UTF-8
           machine: x86_64
           release: 5.3.18-59.37-default
            system: Linux
           version: SLES 15.3 n/a

minion:
 salt  /minion_name/ test.versions_report

    Salt Version:
              Salt: 3004.2

    Dependency Versions:
              cffi: 1.14.6
          cherrypy: 18.6.1
          dateutil: 2.8.1
         docker-py: Not Installed
             gitdb: 4.0.7
         gitpython: Not Installed
            Jinja2: 2.10.1
           libgit2: Not Installed
          M2Crypto: Not Installed
              Mako: 1.1.4
           msgpack: 0.6.2
      msgpack-pure: Not Installed
      mysql-python: Not Installed
         pycparser: 2.20
          pycrypto: Not Installed
      pycryptodome: 3.10.1
            pygit2: Not Installed
            Python: 3.8.8 (tags/v3.8.8:024d805, Feb 19 2021, 13:18:16) [MSC v.1928 64 bit (AMD64)]
      python-gnupg: 0.4.7
            PyYAML: 5.4.1
             PyZMQ: 19.0.0
             smmap: 4.0.0
           timelib: 0.2.4
           Tornado: 4.5.3
               ZMQ: 4.3.2

    System Versions:
              dist:
            locale: cp1252
           machine: AMD64
           release: 2016Server
            system: Windows
           version: 2016Server 10.0.14393 SP0 Multiprocessor Free

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by OrangeDog** [comment]
You're using it wrong. You've put the test into the jinja template. The `onlyif` never sees it.
```yaml
test_onlyif:
  cmd.run:
    - name: hostname
    - shell: powershell
    - onlyif:
      - fun: file.file_exists
        path: c:\\test.txt2
````

**Comment by nazarama** [comment]
thank, so it works in salt v 2019 somehow accidently?

**Comment by OrangeDog** [comment]
It would shell out and run either the command `true` or `false`, which don't usually exist on Windows.
