### ISSUE TITLE
[Salt-minion service not getting started on UBUNTU 18.04] 

### ISSUE THREAD

**Issue by kunal-surana** [saltstack/salt#63770]
**Description**
After Installation of Salt-minion on Ubuntu 18, services didnt come up. 

```
  salt-minion.service - The Salt Minion
   Loaded: loaded (/lib/systemd/system/salt-minion.service; enabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Fri 2023-02-24 11:40:43 UTC; 19ms ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltproject.io/en/latest/contents.html
  Process: 14218 ExecStart=/usr/bin/salt-minion (code=exited, status=255)
 Main PID: 14218 (code=exited, status=255)

Feb 24 11:40:43 platform systemd[1]: Starting The Salt Minion...
Feb 24 11:40:43 platform salt-minion[14218]: [14218] Error loading Python lib '/opt/saltstack/salt/run/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/saltstack/salt/run/libpython3.9.so.1.0)
Feb 24 11:40:43 platform systemd[1]: salt-minion.service: Main process exited, code=exited, status=255/n/a
Feb 24 11:40:43 platform systemd[1]: salt-minion.service: Failed with result 'exit-code'.
Feb 24 11:40:43 platform systemd[1]: Failed to start The Salt Minion.
dpkg: error processing package salt-minion (--configure):
 installed salt-minion package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 salt-minion
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Setup**
Ubuntu 18.04.6 LTS

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Install Salt minion on ubuntu 18 
Check service status

** Error 
'/opt/saltstack/salt/run/libpython3.9.so.1.0': dlopen: /lib/x86_64-linux-gnu/libm.so.6: version `GLIBC_2.29' not found (required by /opt/saltstack/salt/run/libpython3.9.so.1.0)

Ubuntu 18 has GLIBC version 2.27
https://pkgs.org/download/libc6

**Comment by OrangeDog** [comment]
How did you install Salt? Which version? Which repo?

**Comment by kunal-surana** [comment]
Latest version of Salt. Followed this [link](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html#install-onedir-packages-of-salt-on-ubuntu-18-04-bionic
) .
Repo is  https://repo.saltproject.io/salt/py3/ubuntu/18.04/amd64/latest

**Comment by OrangeDog** [comment]
Yep, looks like that's broken, possibly by a recent security release.

The classic package should still work. See [this section further down](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html#install-classic-packages-of-salt-on-ubuntu-18-04-bionic).

**Comment by kunal-surana** [comment]
I have tried that too. Classic package is also not working.

**Comment by OrangeDog** [comment]
And what error do you get from that?

**Comment by OrangeDog** [comment]
Then that's still the onedir package, not the classic package.

**Comment by dmurphy18** [comment]
@kunal-surana Classic is from https://repo.saltproject.io/py3/ubuntu/18.04/amd64/latest

**Comment by whytewolf** [comment]
can you post the output from `apt list | grep salt-minion` cause I just tried this and not only am i NOT getting that error. when i check the library referenced in the error it's GLIB check only goes up to 2.9

```
GLIBC_2.2.5
GLIBC_2.3.3
GLIBC_2.3.2
GLIBC_2.14
GLIBC_2.7
GLIBC_2.6
GLIBC_2.25
GLIBC_2.15
GLIBC_2.26
GLIBC_2.27
GLIBC_2.4
GLIBC_2.3
GLIBC_2.3.4
GLIBC_2.17
GLIBC_2.9
```

**Comment by whytewolf** [comment]
are you sure you installed the ubuntu 18.04 version?
