### ISSUE TITLE
[BUG] CentOS7: salt-minion failed to load dynlib/dll 'libcrypto.so.42'

### ISSUE THREAD

**Issue by tjyang** [saltstack/salt#63771]
**Description**

Not able to start up 3005.1 on centos 7 using classic or onedir approach.
I had to revert to 3004.2 to avoid this issue.

**Setup**

Please be as specific as possible and give set-up details

- [x] classic packaging
- [x ] onedir packaging
- [x ] used bootstrap to install

**Steps to Reproduce the behavior**
Follow  [salt-minion install procedure ](https://docs.saltproject.io/salt/install-guide/en/latest/topics/overview.html)using bootstrap or classic/onedir approaches

**Expected behavior**
salt-minion start up  correctly after specifying salt-master name.
**Screenshots**
N/A, see error logs below in Version Report.

**Versions Report**
<details><summary>salt --versions-report</summary>
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:51:58)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 7 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-1160.11.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

```yaml
[root@minion04 yum.repos.d]# systemctl status -l salt-minion.service
● salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; disabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Fri 2023-02-24 13:07:08 UTC; 33s ago
     Docs: man:salt-minion(1)
           file:///usr/share/doc/salt/html/contents.html
           https://docs.saltstack.com/en/latest/contents.html
  Process: 14449 ExecStart=/usr/bin/salt-minion (code=exited, status=1/FAILURE)
 Main PID: 14449 (code=exited, status=1/FAILURE)

Feb 24 13:07:08 minion04.test.com salt-minion[14449]: libcrypto = _load_libcrypto()
Feb 24 13:07:08 minion04.test.com salt-minion[14449]: File "salt/utils/rsax931.py", line 88, in _load_libcrypto
Feb 24 13:07:08 minion04.test.com salt-minion[14449]: return cdll.LoadLibrary(_find_libcrypto())
Feb 24 13:07:08 minion04.test.com salt-minion[14449]: File "ctypes/__init__.py", line 452, in LoadLibrary
Feb 24 13:07:08 minion04.test.com salt-minion[14449]: File "PyInstaller/loader/pyimod04_ctypes.py", line 55, in __init__
Feb 24 13:07:08 minion04.test.com salt-minion[14449]: pyimod04_ctypes.install.<locals>.PyInstallerImportError: Failed to load dynlib/dll 'libcrypto.so.42'. Most likely this dynlib/dll was not found when the application was frozen.
Feb 24 13:07:08 minion04.test.com systemd[1]: salt-minion.service: main process exited, code=exited, status=1/FAILURE
Feb 24 13:07:08 minion04.test.com systemd[1]: Failed to start The Salt Minion.
Feb 24 13:07:08 minion04.test.com systemd[1]: Unit salt-minion.service entered failed state.
Feb 24 13:07:08 minion04.test.com systemd[1]: salt-minion.service failed.
[root@minion04 yum.repos.d]#
[root@va32lhdp04 yum.repos.d]#

```
</details>

**Comment by OrangeDog** [comment]
That is only the end of the log. Please provide the full output (e.g. from `journalctl -u salt-minion`).

**Comment by tjyang** [comment]
@OrangeDog , thanks for the reply. I will report back "journalctl -u salt-minion" output when I get another downtime scheduled.

**Comment by OrangeDog** [comment]
And the log from the classic package attempt, after being sure it wasn't just the onedir version again.

**Comment by whytewolf** [comment]
I can't seem to replicate this one. was there any config items changed?

**Comment by tjyang** [comment]
@OrangeDog  and @whytewolf . Thanks for spending time on this report. the said system is now out of maintenance windows.  Hard for me to try the 3004 to 3005.1 upgrade test. I am closing this ticket for now. I will open or create another ticket for this issue.
