### ISSUE TITLE
[BUG][ERROR] salt "xxx" test.ping return Minion did not return.  SaltReqTimeoutError, retrying. (1/3)

### ISSUE THREAD

**Issue by RunhangZhang** [saltstack/salt#63784]
**Description**
The master and minion is installed in the same OS. After restarting the master and minion, they can connect to each other by using test.ping. However, after several times, it shows that  "Minion did not return". And when we use "salt-minion -l debug" to see the logs, it shows SaltReqTimeoutError, retrying. (1/3). Can anyone help?

**Comment by OrangeDog** [comment]
Duplicate: #63582
