### ISSUE TITLE
[FEATURE REQUEST] Wildcard in SALT -L mode

### ISSUE THREAD

**Issue by KrystianPlichta** [saltstack/salt#63798]
Is there any way to add wildcard to the list, some names in my environment are called serverxxx and some are called server554.domain.local depending on whether the server was added to salt-master or AD first

command i tried to use

salt -L 'server554*,server876*,server234*' cmd.run 'ls -la'

**Comment by lukasraska** [comment]
The `-L` CLI option forces list targetting, which expects **exact** minion id, so no wildcards are possible there. However the default globbing option can be used to achieve this behaviour - see https://docs.saltproject.io/en/latest/topics/targeting/globbing.html .


It should be possible to also achieve this exact functionality by compound matching ( see https://docs.saltproject.io/en/latest/topics/targeting/compound.html ), but keep in mind compound matching is always filtered on minion side and not on master, so all minions receive this job and then decide whether they match the pattern or not (that also in general behaves differently, based on the used Salt transport).

**Comment by OrangeDog** [comment]
Just don't use the list matcher:

    salt 'server554* or server876* or server234*'

    salt -E '^server(554|876|234)'

**Comment by tjyang** [comment]
@OrangeDog, Thank for the pointer. I have similar questions and you address my question. @KrystianPlichta, are you good with the answer ? if yes. pls close out this issue.

**Comment by KrystianPlichta** [comment]
This work for me
salt -E '(server445|server556|server554|server555)(|.domain.local)' cmd.run  'ls -la'
