### ISSUE TITLE
[BUG] Binaries installed by `salt pip install` (required for onedir) not runnable by default, unlike `pip install`.

### ISSUE THREAD

**Issue by cheburakshu** [saltstack/salt#63830]
Hi folks, what is the guidance on running binaries that get deposited in the `/opt/saltstack/salt/pypath/bin` dir when doing `salt pip install` (onedir)? I can run it by referring the absolute path, `/opt/saltstack/salt/pypath/bin/mybinary`, but is it the recommended way to run it? Usually for normal pip install, I get the binary in `/usr/local/bin` and runnable with `mybinary` as it is in `$PATH`.

Even when a minion is running alongside, this binary is in a path that is not in the traditional `$PATH`, runnable only with `cmd.run` module and will require a cwd param if it is not in `$PATH`. So, should users include this new path `/opt/saltstack/salt/pypath/bin` in their `$PATH`.

**Comment by s0undt3ch** [comment]
Ok, so let's try and get some more information about your issue.

What are you trying to install?
* Is it something that is meant to be used by salt's python ?
* Is it something that is meant to used by the system's python ?

**Comment by s0undt3ch** [comment]
> I am trying to install `sseape` that usually goes in `/usr/local/bin/sseapi-config` when installed but now when installing `salt pip install SSEAPE.x.x.whl` it goes to `/opt/saltstack/salt/pypath/bin/sseapi-config`.
> 
> It is meant to be used by the user, that has salt engines, modules etc, as you know.
> 
> This is my current workaround `export PATH=$PATH:/opt/saltstack/salt/pypath/bin`

FYI, for 3006, the path will change to `/opt/saltstack/salt/bin`

I believe salt should not do anything special with `$PATH` so your workaround is appropriate.

We should however add a note for users who want to use scripts installed into Salt's Onedir.

**Comment by cheburakshu** [comment]
Good to know, thanks @s0undt3ch!

**Comment by OrangeDog** [comment]
Ah, it's an Enterprise thing.

**Comment by mastrong** [comment]
for sseape in particular, simply running the command from the full path works (`/opt/saltstack/salt/pypath/bin/sseapi-config join ...`). no need to cmd.run through salt or add salt's python to system path.

**Comment by barbaricyawps** [comment]
@s0undt3ch or @cheburakshu  , can either of you open a request for the documentation you think is needed as an issue or a merge request against the Salt Install Guide so that we can close out this issue here on the Salt repo? https://gitlab.com/saltstack/open/docs/salt-install-guide/-/issues

**Comment by barbaricyawps** [comment]
Making a note to myself that Pedro recommends putting this note about binary paths in the salt.states.pip_state module documentation in addition to the Salt Install Guide.

**Comment by garethgreenaway** [comment]
To summarize, if you pip install a library using `salt-pip install` method the Python package will be installed into the `onedir` location and will not be accessible from the usual system Python paths.  The command will need to be called directly using the full path to the command.

**Comment by barbaricyawps** [comment]
MR: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/92

**Comment by garethgreenaway** [comment]
Closed by https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/92
