### ISSUE TITLE
[BUG] aptpkg execution module doesn't send kwargs to apt

### ISSUE THREAD

**Issue by wasabi222** [saltstack/salt#63847]
**Description**
Line is here: https://github.com/saltstack/salt/blob/master/salt/modules/aptpkg.py#L1006

Because no kwargs are sent to _call_apt, it's not possible to override `scope=True` in that function (located here: https://github.com/saltstack/salt/blob/master/salt/modules/aptpkg.py#L346 ). The line above should be `out = _call_apt(cmd, **kwargs)` so that scope can be overridden if desired.

**Comment by garethgreenaway** [comment]
Closed by https://github.com/saltstack/salt/pull/63955
