### ISSUE TITLE
[BUG] docker state fails due to missing docker package in onedir package

### ISSUE THREAD

**Issue by kobus-v-schoor** [saltstack/salt#63884]
**Description**
The docker state is failing to apply due to the `docker` package being missing from the onedir package on Ubuntu 22 (Jammy) on amd64 architecture. I believe this is related to https://github.com/saltstack/salt/issues/63620. Following the same workaround as the previously mentioned issue solves the problem:

```
salt-pip install 'docker<6.0.0'
```

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**

Error received:

```
----------
          ID: ensure named docker volume is present
    Function: docker_volume.present
        Name: data
      Result: False
     Comment: State 'docker_volume.present' was not found in SLS '...'
              Reason: 'docker_volume' __virtual__ returned False: 'docker.version' is not available.
```

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
salt-minion --version
salt-minion 3005.1
```
</details>

**Additional context**

Tested on multiple deployments, all have the same issue. Not sure if this is relevant, but these devices were upgraded from Ubuntu 20 -> 22 (the sources.list was updated for the new Ubuntu version, and `apt dist-upgrade salt-minion` was performed to upgrade salt)

**Comment by kobus-v-schoor** [comment]
I've confirmed that this doesn't only affect Ubuntu 22, but also older Ubuntu versions using the onedir packaging.

**Comment by kobus-v-schoor** [comment]
@dwoz thanks for confirming that. Is there any way to track what version of the docker package to install inside the salt environment? Currently, if you do a `salt-pip install docker` it still doesn't work as salt doesn't yet work with the latest docker package, so I need to limit it to `docker<6.0.0`. Is there any way to automatically resolve this for automation purposes?

**Comment by Ch3LL** [comment]
Does `salt-pip install docker<6.0.0` work for you?

**Comment by kobus-v-schoor** [comment]
Hi @Ch3LL , yes the salt-pip command solves the issue. I'm just concerned about how to automate our salt minion deploys, as I don't know what version to pin the docker package to in the future.

> @kobus-v-schoor We do not intend to ship onedir packages with python docker. Please run `salt-pip install docker` to resolve your issue.

@dwoz The python docker package relies on very little extra external packages (can't say this 100% certainty, but I think installing the docker package just installed the docker package and a webrequests package IIRC). Is there another reason why the docker package can't be included with the onedir package?

**Comment by dwoz** [comment]
@kobus-v-schoor In the not too distant future we will be pulling docker related states and modules out of Salt into a Salt Extension python package. At that time, the extension can include docker as a dependency. For now, we want to keep the core of salt small (and make it smaller).
