### ISSUE TITLE
SaltStack Onedir python module not found

### ISSUE THREAD

**Issue by L4rS6** [saltstack/salt#63891]
### Description of Issue
Since migrating to Onedir salt does no longer recognise the shade python library:

```
# salt-call -l debug keystoneng.endpoint_list
...
[DEBUG   ] TiamatPipPathFinder.find_spec: First time trying to load shade
[DEBUG   ] TiamatPipPathFinder.find_spec: /opt/saltstack/salt/pypath/lib/python3.9/site-packages/shade is a directory
...
[DEBUG   ] Could not LazyLoad keystoneng.endpoint_list: 'keystoneng' __virtual__ returned False: The keystoneng execution module failed to load: shade python module is not available
'keystoneng' __virtual__ returned False: The keystoneng execution module failed to load: shade python module is not available
...
```

The module is installed:
```
# salt-call pip.list
...
    shade:
        1.33.0
...

```

### Setup
See provided info above.

### Steps to Reproduce Issue
Run e.g. openstack keystone list:
`# salt-call -l debug keystoneng.endpoint_list`

### Versions Report
```
# salt-call --versions-report
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:49:56)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-137-generic
        system: Linux
       version: Ubuntu 20.04 focal

```

**Comment by s0undt3ch** [comment]
@L4rS6 How was `shade` installed?

**Comment by L4rS6** [comment]
@s0undt3ch I installed shade by `salt-call pip.install shade`

**Comment by s0undt3ch** [comment]
> @s0undt3ch I installed shade by `salt-call pip.install shade`

Should have the same result, but could you try `salt-pip install shade` ?

And, are you able to import it?
```
salt shell
```
Once in the shell
```
import shade
```

**Comment by ccottam** [comment]
```
sudo salt shell
Python 3.9.16 (main, Jan  6 2023, 22:49:58)
[GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import shade
Traceback (most recent call last):
  File "code.py", line 90, in runcode
  File "<console>", line 1, in <module>
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/shade/__init__.py", line 24, in <module>
    from shade.exc import *  # noqa
  File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/shade/exc.py", line 18, in <module>
    import munch
ModuleNotFoundError: No module named 'munch'
```
I install munch 
```
 sudo salt-pip install munch
 Collecting munch
  Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
Requirement already satisfied: six in /opt/saltstack/salt/run (from munch) (1.16.0)
Installing collected packages: munch
Successfully installed munch-2.5.0
 ```
 and everything seems a lot happier

**Comment by L4rS6** [comment]
> > @s0undt3ch I installed shade by `salt-call pip.install shade`
> 
> Should have the same result, but could you try `salt-pip install shade` ?
> 
> And, are you able to import it?
> 
> ```
> salt shell
> ```
> 
> Once in the shell
> 
> ```
> import shade
> ```

I get the message that shade is already installed:
```
# salt-pip install shade
Requirement already satisfied: shade in /opt/saltstack/salt/pypath/lib/python3.9/site-packages (1.33.0)
...
```
Unfortunately I'm unable to drop into a shell:
```
# salt-call shell
'shell' is not available.
```
and the command `salt` is not available on the minion. Do I have to do something different?

**Comment by L4rS6** [comment]
> ```
> sudo salt shell
> Python 3.9.16 (main, Jan  6 2023, 22:49:58)
> [GCC 10.2.1 20210110] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> (InteractiveConsole)
> >>> import shade
> Traceback (most recent call last):
>   File "code.py", line 90, in runcode
>   File "<console>", line 1, in <module>
>   File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/shade/__init__.py", line 24, in <module>
>     from shade.exc import *  # noqa
>   File "/opt/saltstack/salt/pypath/lib/python3.9/site-packages/shade/exc.py", line 18, in <module>
>     import munch
> ModuleNotFoundError: No module named 'munch'
> ```
> 
> 
>      
>   
> 
> I install munch
> 
> 
> ```
>  sudo salt-pip install munch
>  Collecting munch
>   Downloading munch-2.5.0-py2.py3-none-any.whl (10 kB)
> Requirement already satisfied: six in /opt/saltstack/salt/run (from munch) (1.16.0)
> Installing collected packages: munch
> Successfully installed munch-2.5.0
> ```
> 
> 
>      
>   
> 
> and everything seems a lot happier

That worked for me as well! After running `salt-pip install munch` I was able to run the `keystoneng` module. Thanks a lot!

**Comment by ccottam** [comment]
that I still find myself having to patch https://github.com/saltstack/salt/issues/60239 to get vm creation working is disappointing though

**Comment by OrangeDog** [comment]
Dependencies need to be reinstalled after upgrade.
https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html
