### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by hansholgersson** [saltstack/salt#63910]
Hi everybody.
Recently we started to use Ubuntu 22.04 as main OS for our servers. Some of them are ARM architecture.
In our infrastructure we need to deploy alternative repos in order to install needed packages.
The issue is that the 3004 version of salt does not handle well the "pkgrepo.managed" declaration in sls.
On arch x86_64 we managed to solve the issue installing salt-minion from repo published on the saltstack page [Install onedir packages of Salt on Ubuntu 22.04](https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/ubuntu.html#install-onedir-packages-of-salt-on-ubuntu-22-04-jammy) but for the arm64 (aarch64) there not exist repo for ubuntu 22.04, but for 20.04.
The question is: will be a repo for arm64/aarch64 for Ubuntu 22.04, or could you advise us another solution for this issue?

Thank you.

Here some info:

`root@ip-172-29-149-109:/etc/apt# salt-minion --versions-report
Salt Version:
          Salt: 3004.1

Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 1.0.3
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.11.0
        pygit2: Not Installed
        Python: 3.10.6 (main, Nov 14 2022, 16:10:14) [GCC 11.3.0]
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 22.3.0
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 22.04 Jammy Jellyfish
        locale: utf-8
       machine: aarch64
       release: 5.15.0-1031-aws
        system: Linux
       version: Ubuntu 22.04 Jammy Jellyfish

root@ip-172-29-149-109:/etc/apt#
`

![image](https://user-images.githubusercontent.com/122869409/226295984-dd10f345-27f9-46f7-88a3-1085cd086cd1.png)

**Comment by network-shark** [comment]
I think aarch64 is  not officially supported by salt. You could try to install salt via pip. I would highly recommend to deploy it in a virtual environment

**Comment by Ch3LL** [comment]
Arm 64 packages for ubuntu 22.04 will be available for 3006.0 and going forward.

There is currently an RC2 release you can test against here: https://staging.repo.saltproject.io/salt_rc/salt/py3/ubuntu/22.04/arm64/

I will close this issue as this is resolved, but feel free to open a new issue if you find any issues with the arm packages.

**Comment by hansholgersson** [comment]
Ok. Thank you.
