### ISSUE TITLE
[BUG] [salt.transport.zeromq:***][ERROR   ][2142] Some exception handling a payload from minion

### ISSUE THREAD

**Issue by xiaopingxiao** [saltstack/salt#63926]
salt-master  is broken.  There was a sudden problem in the afternoon, causing many minions to be unable to test.ping

**cat /var/log/salt/master   
There's a lot of mistakes**

2023-03-22 15:51:55,538 [salt.transport.mixins.auth:256 ][ERROR   ][2144] Authentication attempt from kweekshcct-iuy70 failed, the public keys did not match. This may be an attempt to compromise the Salt cluster.
2023-03-22 15:53:53,086 [salt.transport.mixins.auth:256 ][ERROR   ][2149] Authentication attempt from kweekshcct-iuy70 failed, the public keys did not match. This may be an attempt to compromise the Salt cluster.
2023-03-22 16:00:55,888 [salt.transport.mixins.auth:256 ][ERROR   ][2147] Authentication attempt from kweekshcct-iuy70 failed, the public keys did not match. This may be an attempt to compromise the Salt cluster.
2023-03-22 16:02:59,552 [salt.transport.mixins.auth:256 ][ERROR   ][2152] Authentication attempt from kweekshcct-iuy70 failed, the public keys did not match. This may be an attempt to compromise the Salt cluster.
2023-03-22 16:05:53,597 [salt.transport.zeromq:777 ][ERROR   ][2142] Some exception handling a payload from minion
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/transport/zeromq.py", line 773, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 294, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python3.7/types.py", line 277, in wrapped
    coro = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/master.py", line 1065, in _handle_payload
    'clear': self._handle_clear}[key](load)
  File "/usr/local/lib/python3.7/site-packages/salt/master.py", line 1097, in _handle_clear
    ret = method(load), {'fun': 'send_clear'}
  File "/usr/local/lib/python3.7/site-packages/salt/master.py", line 2126, in publish
    auth_check = self.loadauth.check_authentication(extra, auth_type)
  File "/usr/local/lib/python3.7/site-packages/salt/auth/__init__.py", line 448, in check_authentication
    if not self.authenticate_eauth(load):
  File "/usr/local/lib/python3.7/site-packages/salt/auth/__init__.py", line 312, in authenticate_eauth
    if not self.time_auth(load):
  File "/usr/local/lib/python3.7/site-packages/salt/auth/__init__.py", line 120, in time_auth
    ret = self.__auth_call(load)
  File "/usr/local/lib/python3.7/site-packages/salt/auth/__init__.py", line 105, in __auth_call
    expected_extra_kws=AUTH_INTERNAL_KEYWORDS)
  File "/usr/local/lib/python3.7/site-packages/salt/utils/args.py", line 461, in format_call
    used_args_count
salt.exceptions.SaltInvocationError: auth takes at least 2 arguments (0 given)
2023-03-22 16:05:53,603 [tornado.general  :462 ][ERROR   ][2142] Uncaught exception in zmqstream callback
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 540, in send_multipart
    memoryview(msg)
TypeError: memoryview: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 455, in _handle_events
    self._handle_send()
  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 549, in send_multipart
    rmsg,
TypeError: Frame 0 ('Some exception handling minion ...) does not support the buffer interface.
2023-03-22 16:05:53,604 [tornado.application:640 ][ERROR   ][2142] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fe798049170>)
Traceback (most recent call last):
  File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 540, in send_multipart
    memoryview(msg)
TypeError: memoryview: a bytes-like object is required, not 'str'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
    ret = callback()
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 535, in <lambda>
    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 455, in _handle_events
    self._handle_send()
  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_send
    status = self.socket.send_multipart(msg, **kwargs)
  File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 549, in send_multipart
    rmsg,
TypeError: Frame 0 ('Some exception handling minion ...) does not support the buffer interface.
2023-03-22 16:06:53,467 [salt.transport.zeromq:777 ][ERROR   ][2151] Some exception handling a payload from minion
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/salt/transport/zeromq.py", line 773, in handle_message
    ret, req_opts = yield self.payload_handler(payload)
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 1056, in run
    value = future.result()
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/concurrent.py", line 239, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 294, in wrapper
    result = func(*args, **kwargs)
  File "/usr/lib64/python3.7/types.py", line 277, in wrapped
    coro = func(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/salt/master.py", line 1065, in _handle_payload
                                                                                                    

       

**systemctl status salt-master**

● salt-master.service - The Salt Master
   Loaded: loaded (/usr/lib/systemd/system/salt-master.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2023-03-21 18:39:17 CST; 23h ago
 Main PID: 1569 (salt-master)
    Tasks: 99
   Memory: 887.5M
   CGroup: /system.slice/salt-master.service
           ├─1569 /usr/bin/python3 /usr/bin/salt-master
           ├─1852 /usr/bin/python3 /usr/bin/salt-master
           ├─1860 /usr/bin/python3 /usr/bin/salt-master
           ├─1861 /usr/bin/python3 /usr/bin/salt-master
           ├─1866 /usr/bin/python3 /usr/bin/salt-master
           ├─1870 /usr/bin/python3 /usr/bin/salt-master
           ├─2128 /usr/bin/python3 /usr/bin/salt-master
           ├─2129 /usr/bin/python3 /usr/bin/salt-master
           ├─2140 /usr/bin/python3 /usr/bin/salt-master
           ├─2141 /usr/bin/python3 /usr/bin/salt-master
           ├─2142 /usr/bin/python3 /usr/bin/salt-master
           ├─2144 /usr/bin/python3 /usr/bin/salt-master
           ├─2145 /usr/bin/python3 /usr/bin/salt-master
           ├─2146 /usr/bin/python3 /usr/bin/salt-master
           ├─2147 /usr/bin/python3 /usr/bin/salt-master
           ├─2148 /usr/bin/python3 /usr/bin/salt-master
           ├─2149 /usr/bin/python3 /usr/bin/salt-master
           ├─2151 /usr/bin/python3 /usr/bin/salt-master
           └─2152 /usr/bin/python3 /usr/bin/salt-master

Mar 22 16:34:59 *******00001 salt-master[2149]:     return fn(*args, **kwargs)
Mar 22 16:34:59 *******00001 salt-master[2149]:   File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 535, in <lambda>
Mar 22 16:34:59 *******00001 salt-master[2149]:     self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
Mar 22 16:34:59 *******00001 salt-master[2149]:   File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 455, in _handle_events
Mar 22 16:34:59 *******00001 salt-master[2149]:     self._handle_send()
Mar 22 16:34:59 *******00001 salt-master[2149]:   File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_send
Mar 22 16:34:59 *******00001 salt-master[2149]:     status = self.socket.send_multipart(msg, **kwargs)
Mar 22 16:34:59 *******00001 salt-master[2149]:   File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 549, in send_multipart
Mar 22 16:34:59 *******00001 salt-master[2149]:     rmsg,
Mar 22 16:34:59 *******00001 salt-master[2149]: TypeError: Frame 0 ('Some exception handling minion ...) does not support the buffer interface.
 

[root@*******00001 log]# systemctl status salt-minion
● salt-minion.service - The Salt Minion
   Loaded: loaded (/usr/lib/systemd/system/salt-minion.service; enabled; vendor preset: disabled)
   Active: active (running) since Tue 2023-03-21 18:42:58 CST; 23h ago
 Main PID: 5746 (salt-minion)
    Tasks: 6
   Memory: 69.4M
   CGroup: /system.slice/salt-minion.service
           ├─5746 /usr/bin/python3 /usr/bin/salt-minion
           ├─5764 /usr/bin/python3 /usr/bin/salt-minion
           └─5766 /usr/bin/python3 /usr/bin/salt-minion

Mar 21 18:42:58 *******00001 systemd[1]: Stopped The Salt Minion.
Mar 21 18:42:58 *******00001 systemd[1]: Starting The Salt Minion...
Mar 21 18:42:58 *******00001 systemd[1]: Started The Salt Minion.
Mar 21 18:42:58 *******00001 salt-minion[5746]: /usr/local/lib/python3.7/site-packages/salt/ext/tornado/httputil.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is depreca>
Mar 21 18:42:58 *******00001 salt-minion[5746]:   class HTTPHeaders(collections.MutableMapping):
Mar 22 16:33:07 *******00001 salt-minion[89993]: [WARNING ] The minion failed to return the job information for job 20230322083235084448. This is often due to the master being shut down or overloaded. If the master is running, consi>

**[root@***********00001 log]# salt-master -V**

/usr/local/lib/python3.7/site-packages/salt/ext/tornado/httputil.py:107: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  class HTTPHeaders(collections.MutableMapping):
Salt Version:
           Salt: 3000.8
 
Dependency Versions:
           cffi: Not Installed
       cherrypy: 18.8.0
       dateutil: 2.8.1
      docker-py: Not Installed
          gitdb: Not Installed
      gitpython: Not Installed
         Jinja2: 2.11.1
        libgit2: Not Installed
       M2Crypto: Not Installed
           Mako: Not Installed
   msgpack-pure: Not Installed
 msgpack-python: 0.5.6
   mysql-python: Not Installed
      pycparser: 2.21
       pycrypto: 2.6.1
   pycryptodome: Not Installed
         pygit2: Not Installed
         Python: 3.7.4 (default, Jan 30 2021, 09:00:44)
   python-gnupg: Not Installed
         PyYAML: 5.3.1
          PyZMQ: 22.1.0
          smmap: Not Installed
        timelib: Not Installed
        Tornado: 4.5.3
            ZMQ: 4.3.4
 
System Versions:
           dist: ******* 2.0 SP9x86_64
         locale: UTF-8
        machine: x86_64
        release: 4.18.0-147.5.1.6.h729.*******.x86_64
         system: Linux
        version: ******* 2.0 SP9x86_64

**/var/log/message**     

Mar 22 16:04:47 *******00001 systemd[1]: Stopped node_exporter.
Mar 22 16:04:47 *******00001 systemd[1]: Started node_exporter.
Mar 22 16:04:47 *******00001 node_exporter[70890]: level=error ts=2023-03-22T08:04:47.434Z caller=node_exporter.go:194 err="listen tcp 10.28.101.91:19100: bind: cannot assign requested address"
Mar 22 16:04:47 *******00001 systemd[1]: node_exporter_hic.service: Main process exited, code=exited, status=1/FAILURE
Mar 22 16:04:47 *******00001 systemd[1]: node_exporter_hic.service: Failed with result 'exit-code'.
Mar 22 16:05:01 *******00001 systemd[1]: Started Session 1162 of user root.
Mar 22 16:05:01 *******00001 systemd[1]: Started Session 1161 of user zmonitor.
Mar 22 16:05:01 *******00001 systemd[1]: session-1162.scope: Succeeded.
Mar 22 16:05:01 *******00001 systemd[1]: session-1161.scope: Succeeded.
Mar 22 16:05:53 *******00001 salt-master[2142]: [ERROR   ] Some exception handling a payload from minion
Mar 22 16:05:53 *******00001 salt-master[2142]: Traceback (most recent call last):
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/transport/zeromq.py", line 773, in handle_message
Mar 22 16:05:53 *******00001 salt-master[2142]:    ret, req_opts = yield self.payload_handler(payload)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 1056, in run
Mar 22 16:05:53 *******00001 salt-master[2142]:    value = future.result()
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/concurrent.py", line 239, in result
Mar 22 16:05:53 *******00001 salt-master[2142]:    raise_exc_info(self._exc_info)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "<string>", line 4, in raise_exc_info
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/gen.py", line 294, in wrapper
Mar 22 16:05:53 *******00001 salt-master[2142]:    result = func(*args, **kwargs)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/lib64/python3.7/types.py", line 277, in wrapped
Mar 22 16:05:53 *******00001 salt-master[2142]:    coro = func(*args, **kwargs)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/master.py", line 1065, in _handle_payload
Mar 22 16:05:53 *******00001 salt-master[2142]:    'clear': self._handle_clear}[key](load)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/master.py", line 1097, in _handle_clear
Mar 22 16:05:53 *******00001 salt-master[2142]:    ret = method(load), {'fun': 'send_clear'}
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/master.py", line 2126, in publish
Mar 22 16:05:53 *******00001 salt-master[2142]:    auth_check = self.loadauth.check_authentication(extra, auth_type)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/auth/__init__.py", line 448, in check_authentication
Mar 22 16:05:53 *******00001 salt-master[2142]:    if not self.authenticate_eauth(load):
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/auth/__init__.py", line 312, in authenticate_eauth
Mar 22 16:05:53 *******00001 salt-master[2142]:    if not self.time_auth(load):
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/auth/__init__.py", line 120, in time_auth
Mar 22 16:05:53 *******00001 salt-master[2142]:    ret = self.__auth_call(load)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/auth/__init__.py", line 105, in __auth_call
Mar 22 16:05:53 *******00001 salt-master[2142]:    expected_extra_kws=AUTH_INTERNAL_KEYWORDS)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/utils/args.py", line 461, in format_call
Mar 22 16:05:53 *******00001 salt-master[2142]:    used_args_count
Mar 22 16:05:53 *******00001 salt-master[2142]: salt.exceptions.SaltInvocationError: auth takes at least 2 arguments (0 given)
Mar 22 16:05:53 *******00001 salt-master[2142]: [ERROR   ] Uncaught exception in zmqstream callback
Mar 22 16:05:53 *******00001 salt-master[2142]: Traceback (most recent call last):
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 540, in send_multipart
Mar 22 16:05:53 *******00001 salt-master[2142]:    memoryview(msg)
Mar 22 16:05:53 *******00001 salt-master[2142]: TypeError: memoryview: a bytes-like object is required, not 'str'
Mar 22 16:05:53 *******00001 salt-master[2142]: During handling of the above exception, another exception occurred:
Mar 22 16:05:53 *******00001 salt-master[2142]: [ERROR   ] Uncaught exception in zmqstream callback
Mar 22 16:05:53 *******00001 salt-master[2142]: Traceback (most recent call last):
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 540, in send_multipart
Mar 22 16:05:53 *******00001 salt-master[2142]:    memoryview(msg)
Mar 22 16:05:53 *******00001 salt-master[2142]: TypeError: memoryview: a bytes-like object is required, not 'str'
Mar 22 16:05:53 *******00001 salt-master[2142]: During handling of the above exception, another exception occurred:
Mar 22 16:05:53 *******00001 salt-master[2142]: Traceback (most recent call last):
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 455, in _handle_events
Mar 22 16:05:53 *******00001 salt-master[2142]:    self._handle_send()
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_send
Mar 22 16:05:53 *******00001 salt-master[2142]:    status = self.socket.send_multipart(msg, **kwargs)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 549, in send_multipart
Mar 22 16:05:53 *******00001 salt-master[2142]:    rmsg,
Mar 22 16:05:53 *******00001 salt-master[2142]: TypeError: Frame 0 ('Some exception handling minion ...) does not support the buffer interface.
Mar 22 16:05:53 *******00001 salt-master[2142]: [ERROR   ] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7fe798049170>)
Mar 22 16:05:53 *******00001 salt-master[2142]: Traceback (most recent call last):
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 540, in send_multipart
Mar 22 16:05:53 *******00001 salt-master[2142]:    memoryview(msg)
Mar 22 16:05:53 *******00001 salt-master[2142]: TypeError: memoryview: a bytes-like object is required, not 'str'
Mar 22 16:05:53 *******00001 salt-master[2142]: During handling of the above exception, another exception occurred:
Mar 22 16:05:53 *******00001 salt-master[2142]: Traceback (most recent call last):
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/ioloop.py", line 606, in _run_callback
Mar 22 16:05:53 *******00001 salt-master[2142]:    ret = callback()
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib/python3.7/site-packages/salt/ext/tornado/stack_context.py", line 278, in null_wrapper
Mar 22 16:05:53 *******00001 salt-master[2142]:    return fn(*args, **kwargs)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 535, in <lambda>
Mar 22 16:05:53 *******00001 salt-master[2142]:    self.io_loop.add_callback(lambda: self._handle_events(self.socket, 0))
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 455, in _handle_events
Mar 22 16:05:53 *******00001 salt-master[2142]:    self._handle_send()
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/eventloop/zmqstream.py", line 492, in _handle_send
Mar 22 16:05:53 *******00001 salt-master[2142]:    status = self.socket.send_multipart(msg, **kwargs)
Mar 22 16:05:53 *******00001 salt-master[2142]:  File "/usr/local/lib64/python3.7/site-packages/zmq/sugar/socket.py", line 549, in send_multipart
Mar 22 16:05:53 *******00001 salt-master[2142]:    rmsg,
Mar 22 16:05:53 *******00001 salt-master[2142]: TypeError: Frame 0 ('Some exception handling minion ...) does not support the buffer interface.
Mar 22 16:06:01 *******00001 systemd[1]: Started Session 1163 of user root.
Mar 22 16:06:01 *******00001 systemd[1]: session-1163.scope: Succeeded.
Mar 22 16:06:13 *******00001 salt-api[2004]: [ERROR   ] Message timed out
Mar 22 16:06:19 *******00001 nscd[71918]: 71918 monitoring file `/etc/hosts` (1)
Mar 22 16:06:19 *******00001 nscd[71918]: 71918 monitoring directory `/etc` (2)
Mar 22 16:06:19 *******00001 nscd[71918]: 71918 monitoring file `/etc/resolv.conf` (3)
Mar 22 16:06:19 *******00001 nscd[71918]: 71918 monitoring directory `/etc` (2)
Mar 22 16:06:53 *******00001 salt-master[2151]: [ERROR   ] Some exception handling a payload from minion
Mar 22 16:06:53 *******00001 salt-master[2151]: Traceback (most recent call last):
Mar 22 16:06:53 *******00001 salt-master[2151]:  File "/usr/local/lib/python3.7/site-packages/salt/transport/zeromq.py", line 773, in handle_message
Mar 22 16:06:53 *******00001 salt-master[2151]:    ret, req_opts = yield self.payload_handler(payload)

**Comment by xiaopingxiao** [comment]
Please help me to see this problem.Brother.

**Comment by OrangeDog** [comment]
3000.8 is not supported. Please upgrade and see if the problem continues.

**Comment by xiaopingxiao** [comment]
Thanks for your advice, we will upgrade to 3004.1 and check to see if this problem occurs again. Currently, the salt has been running normally for one month after it is installed. The official and gray versions are the same. The gray version suddenly appears this problem, but the gray version is running normally. This is very puzzling. The grayscale problem occurs three times. No error occurs. The impact of the version may not be great.

**Comment by xiaopingxiao** [comment]
Thanks for your advice, we will upgrade to 3004.1 and check to see if this problem occurs again. Currently, the salt has been running normally for one month after it is installed. The official and gray versions are the same. The gray version suddenly appears this problem, but the gray version is running normally. This is very puzzling. The grayscale problem occurs three times. No error occurs. The impact of the version may not be great.

**Comment by xiaopingxiao** [comment]
Thanks for your advice, we will upgrade to 3004.1 and check to see if this problem occurs again. Currently, the salt has been running normally for one month after it is installed. The pro and gray versions are the same. The gray version suddenly appears this problem, but the pro version is running normally. This is very puzzling. The grayscale problem occurs three times. pro No error occurs. The impact of the version may not be great.
