### ISSUE TITLE
salt-pip does not get installed unless you install salt-master

### ISSUE THREAD

**Issue by rterbush** [saltstack/salt#63940]
### Description of Issue/Question

Title says it all. Been tearing my hair out trying to get a working gitfs using onedir install without installing salt-master.

### Setup

Use bootstrap installer without the `-M` flag.

### Steps to Reproduce Issue

`which salt-pip`

### Versions and Systems

`install_salt.sh -P -d -X -x python3 onedir`

Come on Man!

**Comment by garethgreenaway** [comment]
@rterbush We believe this issue has been addressed in the upcoming 3006.0 release, if you're able to test this that would greatly appreciated.  You can install the RC packages by following the directions in the install guide, https://docs.saltproject.io/salt/install-guide/en/latest/topics/release-candidate.html

**Comment by rterbush** [comment]
@garethgreenaway Not clear to me if I have tested the correct RC. I've attempted to deploy via bootstrap 3006.0rc3 with the following command:

`/bin/sh ./install_salt.sh -P -d -X -x python3 git v3006.0rc3`

I'm getting the following error that I had reported earlier and was steered toward a `onedir` release.
```
* ERROR: https://repo.saltproject.io/py3/redhat/9/x86_64/latest/SALTSTACK-GPG-KEY2.pub failed to download to /tmp/salt-gpg-LKC25cIV.pub
* ERROR: Failed to run install_rocky_linux_git_deps()!!!
```

and then when my provision script calls /usr/bin/salt-pip
```
/usr/bin/salt-pip: No such file or directory
Failed to get unit file state for salt-minion.service: No such file or directory
```

**Comment by garethgreenaway** [comment]
@rterbush If you check the link I provided, https://docs.saltproject.io/salt/install-guide/en/latest/topics/release-candidate.html, it will have instructions on how to setup the instance to install and use the 3006rc release.  Installing via Git will not install the onedir packages so you will not have salt-pip available.  The GPG key issue with the bootstrap script has been resolved and will be available once a new release is pushed out.

**Comment by rterbush** [comment]
I did look at the link you provided which is why I used the parameters I did. Just confirming with you that they are correct.

My scenario is a remote container provision via Terraform. I don't have another scenario to test this so if this does not work currently, I cannot comment more on whether this is fixed.

**Comment by garethgreenaway** [comment]
@rterbush The current release of the bootstrap script doesn't include the support for installing the RC packages currently, this feature does exist in the development version and will be available once we do the next release.  If you're able to download the development version from here:

**Comment by garethgreenaway** [comment]
Moving to the 3006.1 milestone while waiting for verification.

**Comment by rterbush** [comment]
@garethgreenaway The link you provided does not point to the bootstrap script. It appears to point to a symlink. I dug around a bit and found the following script which I can confirm works for a minion only deployment that includes `salt-pip`.

https://raw.githubusercontent.com/saltstack/salt-bootstrap/develop/bootstrap-salt.sh

If that is a valid development  script to test, I think we can mark this as closed.

**Comment by garethgreenaway** [comment]
@rterbush Apologies, I copied the wrong file from the repository.  That URL you linked is the correct script.  Thanks for the confirmation, we'll close this one out and consider it resolved.
