### ISSUE TITLE
[BUG] Reactor not triggered by an event, .sls not detected

### ISSUE THREAD

**Issue by OthmanSt** [saltstack/salt#63964]
**Description**
Created a reactor and a beacon.  I can trigger the reactor with the specific tag linked to it, but the states aren't executed at all and I'm facing this error message in '/var/log/salt/master' :

```
2023-03-27 14:49:36,110 [salt.utils.process:1002][ERROR   ][8022] An un-handled exception from the multiprocessing process 'Reactor-9:1' was caught:
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 993, in wrapped_run_func
    return run_func()
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 277, in run
    self.call_reactions(chunks)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 202, in call_reactions
    self.wrap.run(chunk)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 341, in run
    self.populate_client_cache(low)
  File "/usr/lib/python3.6/site-packages/salt/utils/reactor.py", line 333, in populate_client_cache
    self.client_cache[reaction_type] = self.reaction_class[reaction_type](
KeyError: 'file'
```

**Setup**

- CentOS 7.9 VM
- Azure cloud
- used bootstrap to install

**Steps to Reproduce the behavior**

```
Here's 'etc/salt/master.d/reactor.conf' :
reactor:
  - 'salt/beacon/minion2/cert_info/':
    - salt://reactor/create_checked_file.sls
```

```
Here's /srv/salt/reactor/create_checked_file.sls' :
create_checked_file:
  file.management:
    - name: /srv/salt/reactor/checked_file
```

**Expected behavior**
A file '/srv/salt/reactor/cheked_file' is supposed to be created.

**Versions Report**
Minion report :

Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.15.1
      cherrypy: 5.6.0
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

Master report:
[root@centos-cap-dev01 reactor]# salt-minion -V
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.15.1
      cherrypy: Not Installed
      dateutil: Not Installed
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.11.1
       libgit2: Not Installed
      M2Crypto: 0.35.2
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: Not Installed
        pygit2: Not Installed
        Python: 3.6.8 (default, Nov 16 2020, 16:55:22)
  python-gnupg: Not Installed
        PyYAML: 3.13
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.1.4

System Versions:
          dist: centos 7 Core
        locale: UTF-8
       machine: x86_64
       release: 3.10.0-1160.76.1.el7.x86_64
        system: Linux
       version: CentOS Linux 7 Core

**Additional context**
The event bus and beacon are clearly working, the reactor is clearly triggered by the event and the tag.
As I'm beginning with Salt and Beacon/Reactor, might be a very simple error. Thanks in advance for your help !

**Comment by garethgreenaway** [comment]
@OthmanSt Thanks for the report. When using reactors there are four types `local`, `runner`, `wheel`, and `caller` depending on what you need to happen within the reactor state.  The two most common used are the `local` and `runner`, which are used to run commands on the minion or the master respectively.  Based on your example above, it seems like you want that file created on the minion where the beacon event came from?

**Comment by OthmanSt** [comment]
Hi @garethgreenaway !
You're right, I'm trying to do so. I'm in the local case. My reactor state should look like this :
create_checked_file:
  local.state.single:
    - tgt: '*'
    - arg:
      - file.managed
      - /srv/salt/reactor/checked_file

Found out the issue, it's finally working but I still have to find a solution to execute the state only on the minion that triggered the event. Sorry for the useless topic, it was clear on the salt documentation.
