### ISSUE TITLE
[BUG] adding ignore spacing jinja flags will kill a build with "mapping values don't belong here"

### ISSUE THREAD

**Issue by jeffdyke** [saltstack/salt#64027]
**Description**
The following code, which worked fine before 3005, currently on 3005.1, but fails now b/c of spacing issues. 
This works:
```
{% set user_home_folder = args['home'] %}
{% set group = username %}

create_plugin_dir_{{username}}:
  file.directory:
    - name: "{{user_home_folder}}/.oh-my-zsh/custom/plugins"
    - user: {{username}}
    - makedirs: True
```
This fails
```
{%- set user_home_folder = args['home'] -%}
{%- set group = username -%}

create_plugin_dir_{{username}}:
  file.directory:
    - name: "{{user_home_folder}}/.oh-my-zsh/custom/plugins"
    - user: {{username}}
    - makedirs: True
```

**Setup**
The above is enough to recreate the issue, the `{{username}}` is set in a `for  username, args in pillar.get('foo').items()`

The removal of spaces seemed to have been allowed before 3005, as i've had this zsh state in my salt repo for a long while, but currently, it must be put on the same line, or something...I would love to tell you what `something` is but the only error message is that "mapping values are not allowed in this context".  But all files run through a yaml linter/checker returns valid yaml. 

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Add the above yaml to a state file and the merged file is not valid yaml, there is not a better explanation or output, even if i do a test_template it fails with the random error that you have to rip everything apart to try to find.  

**Expected behavior**
It should parse the `{%- set foo = bar -%}` that is followed by an extra newline, as you can see in the example above.  Or emit a fatal error, Other than "mapping values don't belong here"

**Screenshots**
The error message is above, that is all that exists even in debug mode. 

**Versions Report**
Tested on both 3005 master and minion and 3005.1 master and minion.  

**Additional context**
I realize this may report need a little love in the form of a bug, but it took me about 6 hours to find this so i'm going to just go fix the issue in each of my 4 vpcs.  and stop working for the night ;)

I'll come back to it later, hopefully the information is sufficient to get someone started. 
Thanks

**Comment by jeffdyke** [comment]
Edit: To keep this clean i was testing the runs against a `salt-minion` that is on the `salt-master`, so versions would not impact it.

**Comment by jeffdyke** [comment]
FWIW, I may chalk this up to user error, **with** the exception that it seemed not to matter before.  I have done this nowhere else in states, and i'll avoid it like the plague.  A one off oddity i'm glad i've found.

**Comment by OrangeDog** [comment]
That doesn't fail.

The collapse on the for loop that you have omitted is probably doing it, because it will put the first line of the second iteration on the last line of the first.

**Comment by jeffdyke** [comment]
That's perfectly fine, so its the for loop them, it worked prior to 3005.  Ultimately as you see in my updates that is my only comment.  I don't need someeone to try to reproduce in 3004.X, nor will i bother, hopefully this just shows up in searches b/c when you get this error, its as opaque as it gets. So hopefully this helps someone else.

**Comment by jeffdyke** [comment]
I'm not harping on this not having an action item, just some information b/c when you search for that error message you simply get that one error message an 100% of the posts are about spacing(indentation) or missing colons.

I effectively admitted my own defeat in the last post before your first.  Its all good.  As i said this was not used in any of my other personal states.

**Comment by OrangeDog** [comment]
This isn't some sort of contest. I'm trying to work out if there is a bug here. That is impossible because you haven't provided the actual code that caused the error. Please do so.

**Comment by jeffdyke** [comment]
Apologies, i'm really not trying for it to be.  I'll see if i can. as i say, i think this is completely on me as i've never run into it.  

Out of curiousity is there a `saltutil` or other command that would spit out the malformed yaml, rather than failing.  It doesn't show up in debug logs.

I don't want you to waste your time to reproduce.  If the above exists I'll definitely do it, b/c i would use that for any errors that didn't make as much sense to me, like one that is open, and now i know what causes it (mostly).  "Changes are required to be a dictionary".  In my findings, this is normally related to a bad `source` path in a state, so thats a couple levels deep by the time (i think) python salt files get the error.  

I think the ultimate take away is "Don't use spacing syntax in state like this for conditionals and loops, b/c its really not "saving" any space, i don't think.  In a source file parsed as jinja, it makes a lot more sense. 

Appreciate your comments.

**Comment by jeffdyke** [comment]
Thank you for the link, and i believe that issue has been open for a while.  I'm embarrassed I didn't know about the `slsutil.renderer`

[Changes should be a dictionary](https://github.com/saltstack/salt/issues/55269.)  It was open for a few years, but seems its been closed as of September, and honestly i've not tried to break it again.  

Thanks!

**Comment by OrangeDog** [comment]
Please just paste the code that caused this issue. We don't need any excuses or explanations. Just put your code that you ran and got this error, and decided not to post for some reason.

**Comment by jeffdyke** [comment]
I closed this b/c i dont' know when i'll get back to it.  Clearly you're frustrated about how i write and i don't really want to continue the conversation like that.

**Comment by jeffdyke** [comment]
I'd like to end this on a positive note b/c you're correct and rightfully a bit frustrated.  Here is a minimal reproduce, I added the spacers/dashes back one by one and the one that fails this is at the end of the `for`
```
include:
  - users
zsh:
  pkg.latest:
    - require:
      - sls: users
{%- set defaults = salt['pillar.get']("oh-my-zsh") -%}
{%- for username, args in pillar.get('system-users', {}).items() -%}
echo {{username}}:
  cmd.run
{% endfor %}
```
The `echo {{username}}` will still fail if i added a newline.  

Feel free to close or respond  
This is the output of slsultil.renderer:
```
sudo salt "stagingmonitor" slsutil.renderer /src/salt/salt/test-template/init.sls default_renderer=yaml
stagingmonitor:
    The minion function caused an exception: Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/renderers/yaml.py", line 62, in render
        data = yamlloader.load(yaml_data, Loader=get_yaml_loader(argline))
      File "/usr/lib/python3/dist-packages/salt/utils/yamlloader.py", line 158, in load
        return yaml.load(stream, Loader=Loader)
      File "/usr/lib/python3/dist-packages/yaml/__init__.py", line 114, in load
        return loader.get_single_data()
      File "/usr/lib/python3/dist-packages/yaml/constructor.py", line 49, in get_single_data
        node = self.get_single_node()
      File "yaml/_yaml.pyx", line 707, in yaml._yaml.CParser.get_single_node
      File "yaml/_yaml.pyx", line 725, in yaml._yaml.CParser._compose_document
      File "yaml/_yaml.pyx", line 776, in yaml._yaml.CParser._compose_node
      File "yaml/_yaml.pyx", line 892, in yaml._yaml.CParser._compose_mapping_node
      File "yaml/_yaml.pyx", line 905, in yaml._yaml.CParser._parse_next_event
    yaml.scanner.ScannerError: while scanning for the next token
    found character that cannot start any token
      in "<unicode string>", line 7, column 2

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1934, in _thread_return
        return_data = minion_instance._execute_job_function(
      File "/usr/lib/python3/dist-packages/salt/minion.py", line 1893, in _execute_job_function
        return_data = self.executors[fname](opts, data, func, args, kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/executors/direct_call.py", line 10, in execute
        return func(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/modules/slsutil.py", line 176, in renderer
        ret = salt.template.compile_template(
      File "/usr/lib/python3/dist-packages/salt/template.py", line 99, in compile_template
        ret = render(input_data, saltenv, sls, **render_kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 149, in __call__
        return self.loader.run(run_func, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1228, in run
        return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/loader/lazy.py", line 1243, in _run_as
        return _func_or_method(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/salt/renderers/yaml.py", line 66, in render
        raise SaltRenderError(err_type, line_num, exc.problem_mark.buffer)
    salt.exceptions.SaltRenderError: found character that cannot start any token
```

**Comment by OrangeDog** [comment]
That's a different error because you told `slsutil.renderer` to parse it as yaml instead of jinja.

That example will indeed fail, because it will render to
```yaml
include:
  - users
zsh:
  pkg.latest:
    - require:
      - sls: usersecho username:
  cmd.run
```

That behaviour did not change between 3004 and 3005.

**Comment by jeffdyke** [comment]
> That's a different error because you told `slsutil.renderer` to parse it as yaml instead of jinja.
> 
> That example will indeed fail, because it will render to
> 
> ```yaml
> include:
>   - users
> zsh:
>   pkg.latest:
>     - require:
>       - sls: usersecho username:
>   cmd.run
> ```
> 
> That behaviour did not change between 3004 and 3005.

Yes that `yaml` was completely incorrect, thanks for pointing that out, and pasting the output.  I agree, i've run into a few issues with 3005, this is not one of them..  Hopefully this conversation will help a future google search.
