### ISSUE TITLE
[TECH DEBT] Harden Salt Master

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#64045]
### Description of the tech debt to be addressed, include links and screenshots

While it is [documented](https://docs.saltproject.io/en/latest/topics/hardening.html#general-hardening-tip) that masters are sensitive and access should be restricted. There are still some things we can do to harden master installations. We should start adding a salt user and group to master installs and run the master as an un-privileged user.  We should also make sure the permissions on any files the master makes are set properly to this user and group.

**Comment by Ch3LL** [comment]
closed by https://github.com/saltstack/salt/pull/64037
