### ISSUE TITLE
[DOCS] Top File Settings option says it is masterless when it is not.

### ISSUE THREAD

**Issue by whytewolf** [saltstack/salt#64067]
**Description**
Top File settings header states that the following settings only effect masterlss minions. when in fact they are not masterless only minion settings. also the section doesn't indicate when it ends so things like start_event_grains looks like it is part of that heading. 

**Suggested Fix**
remove the header comment about masterless

**Type of documentation**
salt minion configure options. 

**Location or format of documentation**
https://docs.saltproject.io/en/latest/ref/configuration/minion.html#top-file-settings

**Comment by barbaricyawps** [comment]
Sounds good, @Tanmoy037 . Thanks!
