### ISSUE TITLE
mysql module quote_identifier is missing to escape %

### ISSUE THREAD

**Issue by ns-bliu** [saltstack/salt#64083]
**Description**

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Granting privileges on database like 'test%data'.'*' is not escaping '%' to the literal database name 'test%data', but any wildcard database names surrounding by 'test' and 'data'.
MariaDB [(none)]> show grants for 'testuser'@'%';
+------------------------------------------------------------------------------------------------------------+
| Grants for qos-service@%                                                                                   |
+------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `testuser`@`%` IDENTIFIED BY PASSWORD '*' |                                        |
| GRANT ALL PRIVILEGES ON `test%data`.* TO `testuser`@`%`                                                |
+-----

**Expected behavior**
MariaDB [(none)]> show grants for 'testuser'@'%';
+------------------------------------------------------------------------------------------------------------+
| Grants for qos-service@%                                                                                   |
+------------------------------------------------------------------------------------------------------------+
| GRANT USAGE ON *.* TO `testuser`@`%` IDENTIFIED BY PASSWORD '*' |                                        |
| GRANT ALL PRIVILEGES ON `test\%data`.* TO `testuser`@`%`                                                |
+------------------------------------------------------------------------------------------------------------+

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
PASTE HERE
```
[</details>]()
https://github.com/saltstack/salt/blob/da6403b722a199a83ab4fbe8878869e26e4606ec/salt/modules/mysql.py#L716

'%' is not escaped with '\\'

https://github.com/saltstack/salt/blob/da6403b722a199a83ab4fbe8878869e26e4606ec/salt/modules/mysql.py#L2393
quote_identifier should apply to escape=False too

https://github.com/saltstack/salt/blob/da6403b722a199a83ab4fbe8878869e26e4606ec/salt/modules/mysql.py#L2666
grant_revoke check existence with escape arg but revoke with the default escape.

**Additional context**

**Comment by whytewolf** [comment]
so, I was starting to look into this bug and the original behavior is consistent with how mysql works. % is meant to be a wildcard character and it is allowed in grants because granting permission on database% to a user is better then granting database1 database2 database3 database4, with 10,000 which slows mysql down when trying to find the grants in the grants table full of literal names. 

so the purposed fix will break being able to use % as its intended purpose. 

if you have literal % in your database names and you want to escape it. you should be escaping it on your end.

**Comment by whytewolf** [comment]
I'm closing this as wont-fix as the intended purpose of % is a wildcard and grant is supposed to use that wildcard. if you need escaping of % in your grant you need to escape it yourself.
