### ISSUE TITLE
[BUG] Device mapper names not parsed properly

### ISSUE THREAD

**Issue by sean-anderson-seco** [saltstack/salt#64082]
**Description**

Device mapper names such as `dm_crypt-0` (the default format for Ubuntu Server) are not parsed properly by `cryptdev.list`. This is because device mapper names may include non-"word" characters such as dashes. This confuses the regex. Instead, we should match based on non-space and space characters instead (such as what is done by sean-anderson-seco/salt@6471623f89a7ad1d1701144f646ded6ddf50523a). I would submit this as a PR, but there are no tests for this module and I don't want to create them.

**Steps to Reproduce the behavior**

```
truncate -s 64M /tmp/dummy
echo | sudo cryptsetup luksFormat /tmp/dummy
echo | sudo cryptsetup open /tmp/dummy my-device
sudo salt-call cryptdev.active
```

**Expected behavior**

The device should be listed properly.

**Versions Report**

3005.1. I have verified by inspection that this issue exists in master.

**Comment by whytewolf** [comment]
closing as #64161 is merged
