### ISSUE TITLE
[BUG] Add multiple Network Devices without restarting proxy each time per device.  

### ISSUE THREAD

**Issue by vanditpatel619** [saltstack/salt#64103]
**Description**
Add multiple Network Devices without restarting proxy each time per device.  

**Setup**
Delta proxy devices loading from MongoDB script. There are 35 devices in one delta proxy and it requires 2-3 mins wait to accept key and it can be proceed only one device at a time.

Please be as specific as possible and give set-up details.
- [ ] VM (Virtualbox, KVM, etc. please specify)

**Steps to Reproduce the behavior**

**Expected behavior**
All devices keys should be accepted in one shot rather than serial acceptance and wait time.

**Screenshots**

**Versions Report**
Salt Version:
Salt: 3005

**Additional context**

**Comment by garethgreenaway** [comment]
@vanditpatel619 Do you have the `parallel: True` option in the pillar data for the control proxies?  Also, I discovered a bug when the number of devices configured for a control proxy is greater than 20, this causes an error to occur and the process will restart.  If you can divide up your minions to that each control proxy has no more than 20 sub proxies.

**Comment by s0undt3ch** [comment]
Fix will be available in the upcoming 3006.1 release
