### ISSUE TITLE
[BUG] salt user HOME is in /home

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#64141]
**Description**
The new 3006 salt-master installers create a `salt` user to run the service as. However, this user is given a HOME of `/home/salt`, as if it were a human user.

**Steps to Reproduce the behavior**
Install 3006 via onedir package on Linux system

**Expected behavior**
The `salt` user should be a system user with a HOME of ideally `/var/opt/saltstack`.

**Additional context**
https://refspecs.linuxfoundation.org/FHS_3.0/fhs-3.0.html#optAddonApplicationSoftwarePackages

**Comment by dwoz** [comment]
Fixed by #64174
