### ISSUE TITLE
[BUG] "NoSuchKey" error when syncing from https://s3.repo.saltstack.com/

### ISSUE THREAD

**Issue by taoky** [saltstack/salt#64140]
**Description**
When syncing from https://s3.repo.saltstack.com/, we find that some HTML files are unsyncable.

And https://s3.repo.saltstack.com/s3/ shows these files as existed. Affected files are:

- 3003.html (https://s3.repo.saltstack.com/s3/3003.html)
- 3002.html (https://s3.repo.saltstack.com/s3/3002.html)
- 3001.html (https://s3.repo.saltstack.com/s3/3001.html)
- 403.html (https://s3.repo.saltstack.com/s3/403.html)
- index.html (https://s3.repo.saltstack.com/s3/index.html)

**Setup**
~~(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)~~

~~Please be as specific as possible and give set-up details.~~ This is not a bug of salt software, so I guess the following options are not applicable.

- [x] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

Both aws (`aws-cli/1.27.89`) and rclone encounter this error when syncing.

**Steps to Reproduce the behavior**

```
> aws --no-sign-request --endpoint-url=https://s3.repo.saltstack.com/ s3 sync --exact-timestamps --delete --exclude 'dev/*' s3://s3/ .
download failed: s3://s3/3003.html to ./3003.html An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
download failed: s3://s3/3001.html to ./3001.html An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
download failed: s3://s3/403.html to ./403.html An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
download failed: s3://s3/3002.html to ./3002.html An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
cancelled: ctrl-c received
```

**Expected behavior**
Successfully sync from s3.repo.saltstack.com without errors.

**Screenshots**
N/A

**Versions Report**
<details><summary>salt --versions-report</summary>

```yaml
N/A
```
</details>

**Additional context**
N/A

**Comment by ScriptAutomate** [comment]
Was able to replicate with both `rclone` and `aws`.

This looks to currently only impact top-level files, as mentioned in issue:

- 3003.html (https://s3.repo.saltstack.com/s3/3003.html)
- 3002.html (https://s3.repo.saltstack.com/s3/3002.html)
- 3001.html (https://s3.repo.saltstack.com/s3/3001.html)
- 403.html (https://s3.repo.saltstack.com/s3/403.html)
- index.html (https://s3.repo.saltstack.com/s3/index.html)

Requires some further investigation.

**Comment by kapil-git1087** [comment]
Hi Team,
We are getting error while syncing the contents from the SaltStack S3 repos.
"2023/05/15 03:09:36 ERROR : 3003.html: Failed to copy: failed to open source object: NoSuchKey: The specified key does not exist.", "\tstatus code: 404, request id: , host id: ",
"2023/05/15 03:09:36 ERROR : index.html: Failed to copy: failed to open source object: NoSuchKey: The specified key does not exist.", "\tstatus code: 404, request id: , host id: ",
"2023/05/15 03:09:44 Failed to sync with 2 errors: last error was: failed to open source object: NoSuchKey: The specified key does not exist.", "\tstatus code: 404, request id: , host id: "], "stdout": "", "stdout_lines": []}
Please check and suggest.
Regards
Kapil Dev

**Comment by wilpig** [comment]
Just tagging this with confirmation of the same behavior so I can get updates if this gets looked at.

```
$ aws --no-sign-request --endpoint-url https://s3.repo.saltstack.com s3 sync --delete --exact-timestamps s3://s3/ /repo/saltstack
download failed: s3://s3/3001.html to ../../../repo/saltstack/3001.html An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
download failed: s3://s3/403.html to ../../../repo/saltstack/403.html An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
download failed: s3://s3/3002.html to ../../../repo/saltstack/3002.html An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
download failed: s3://s3/3003.html to ../../../repo/saltstack/3003.html An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
download failed: s3://s3/index.html to ../../../repo/saltstack/index.html An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist.
```

**Comment by bwdbethke** [comment]
Just tagging this with confirmation of the same behavior so I can get updates if this gets looked at.
my attempts to locally mirror the repo with rclone have similar errors

```
2024/03/20 11:40:27 ERROR : index.html: Failed to copy: failed to open source object: NoSuchKey: The specified key does not exist.
        status code: 404, request id: , host id:
2024/03/20 11:40:27 ERROR : 3003.html: Failed to copy: failed to open source object: NoSuchKey: The specified key does not exist.
        status code: 404, request id: , host id:
```

**Comment by ScriptAutomate** [comment]
Repo has since been migrated, and there is no longer a "NoSuchKey" error when using the new air-gapped environments directions for `rclone` or `wget`:
- https://docs.saltproject.io/salt/install-guide/en/latest/topics/other-install-types/air-gap-install.html
