### ISSUE TITLE
I want to reboot minion in between of state file and continue with state file once minion is back.

### ISSUE THREAD

**Issue by SaurabhKumar19** [saltstack/salt#64145]
I tried this but minion dis not return
reboot_after_update:
  module.run:
    - name: system.reboot
    - timeout: 1
    - in_seconds: False
    - wait_for_reboot: True

Error:

    Minion did not return. [Not connected]
ERROR: Minions returned with non-zero exit code

**Comment by SaurabhKumar19** [comment]
I have integrated salt stack with vRA and after domain joining i want to reboot windows minion and execute further salt state.

**Comment by OrangeDog** [comment]
Not only is this one of the things orchestration is designed for, but you can also set a job to run on startup if you want the minion to do it independently.
