### ISSUE TITLE
[DOCS] Install guide downloads page has wrong repository links

### ISSUE THREAD

**Issue by bdrx312** [saltstack/salt#64156]
**Description**

The documentation at https://docs.saltproject.io/salt/install-guide/en/latest/topics/downloads.html lists 3006 as available for download at https://repo.saltproject.io/py3/redhat/ but it is not in there. According to the documentation at 
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/rhel.html the link https://repo.saltproject.io/salt/py3/redhat/8/x86_64/ is the correct location and indeed it has the 3006 packages under it.

**Suggested Fix**

Update the information and links at https://docs.saltproject.io/salt/install-guide/en/latest/topics/downloads.html to point to the correct repository urls or just update to redirect or have links to the correct documentation.

**Type of documentation**
Salt documentation

**Location or format of documentation**
https://docs.saltproject.io/salt/install-guide/en/latest/topics/downloads.html

**Additional context**

**Comment by dmurphy18** [comment]
PY2 archive repository should be ```https://archive.repo.saltproject.io``` under yum and apt directories, other PY2 packages may be found under their respective directories, osx, windows, freebsd etc.
PY3 archive repository should be ```https://archive.repo.saltproject.io``` under py3 and salt/py3 directories

So hard to have a single link Py2 or Py3, perhaps updated with more wording.

@twangboy knows about the osx and windows better.

```
However, the 3006 version is in there, and according to the documentation at
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/rhel.html the link https://repo.saltproject.io/salt/py3/redhat/8/x86_64/ is the correct location for the current repo.
```
Don't know what they are referring to here, checked links and don't see anything out of place

**Comment by barbaricyawps** [comment]
I can update the wording as suggested for the archive directories to provide more nuance.

Question to check for my own understanding on the other items: Maybe the confusion is around how the latest version is displayed as `latest` rather than `3006`? Like the past releases show up in their respective folders (3005, 3004), but `3006` is `latest`. Am I right?

**Comment by dmurphy18** [comment]
latest is the latest, there should be latest and 3006 as the major versions, latest will be the same as 3006.
But when 3007 becomes available, then latest will be the same as 3007, and there will be 3007 major version too, and the now older 3006 major version.

**Comment by barbaricyawps** [comment]
Merge request is in: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/112

**Comment by barbaricyawps** [comment]
Thanks for the clarification, @dmurphy18 . The merge request is merged in now, so I'm going to close this issue, but let us know if you need anything else @bdrx312 !

**Comment by bdrx312** [comment]
Sorry, I added confusion to the report with comments about https://archive.repo.saltproject.io/salt/py3/. I apparently had brain fart and just looked at the path and not the host and thought it was the same as  https://repo.saltproject.io/salt/py3/redhat/8/x86_64/. The primary issue on that page is that the links in each of the sections point to https://repo.saltproject.io/py3/ and not  https://repo.saltproject.io/salt/py3/. They are missing the `salt` prefix of the path.

**Comment by s0undt3ch** [comment]
From 3006.0 onward, the releases always have the `salt/py3` prefix, not `py3`, regardless of OS.

**Comment by barbaricyawps** [comment]
New merge request: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/113

**Comment by barbaricyawps** [comment]
MR was merged. Closing as this should be fixed now.
