### ISSUE TITLE
[BUG] Errors, Warnings after installed at a fresh debian bullseye 

### ISSUE THREAD

**Issue by helgein** [saltstack/salt#64186]
**Description**
systemctl status salt-minion shows:
Apr 28 16:17:18 miniontest systemd[1]: Starting The Salt Minion...
Apr 28 16:17:18 miniontest systemd[1]: Started The Salt Minion.
Apr 28 16:17:18 miniontest salt-minion[1992]: /opt/saltstack/salt/lib/python3.10/site-packages/salt/transport/client.py:79: DeprecationWarning: **This module is deprecated. Please use salt.channel.client instead.**
Apr 28 16:17:18 miniontest salt-minion[1992]:   warn_until(
Apr 28 16:17:20 miniontest salt-minion[1992]: **[WARNING ] Got events for closed stream <zmq.eventloop.zmqstream.ZMQStream object at 0x7f8dfb848d30>**

**Setup**
Fresh Debian Bullseye netinst.iso 
Salt-minon 3006.0;
on the server salt-key -y -a servername has been executed
on the minion systemctl restart salt-minion
tested on different machines

- [X] on-prem machine
- [X ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [X] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
as under "Setup"

**Expected behavior**
should not throw errors, warnings in systemctl status output

**Comment by Ch3LL** [comment]
Closed by #64208
