### ISSUE TITLE
[BUG] Salt Extensions Installed to Extras Location Are Not Accessible

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#64192]
**Description**
Beginning in 3006.0, any Salt extensions that are installed via PIP that are installed to the onedir extras directory are not accessible by Salt

**Steps to Reproduce the behavior**
Install a Salt extension via PIP that will be installed to the onedir extras directory

**Expected behavior**
Salt extension should be accessible.

**Comment by anilsil** [comment]
closing as per #64212
