### ISSUE TITLE
[TECH DEBT] Deprecate Proxmox Cloud Modules

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#64224]
### Description of the tech debt to be addressed, include links and screenshots

Deprecating all Proxmox functionality in Salt and moving it to: 
https://github.com/salt-extensions/saltext-proxmox

First Salt version with Proxmox no longer present in the core: 3008.0

See this PR for an idea of how to deprecate the Proxmox cloud modules:
https://github.com/saltstack/salt/pull/62184

**Comment by Tanmoy037** [comment]
@nicholasmhughes I want to try this. Can you assign it to me?

**Comment by nicholasmhughes** [comment]
@Tanmoy037 do you need any help/guidance on this?

**Comment by Tanmoy037** [comment]
> @Tanmoy037 do you need any help/guidance on this?

Please allow me a few more time, if I will need any help I will contact you through Slack.
