### ISSUE TITLE
[DOCS] Python version support documentation is inconsistent

### ISSUE THREAD

**Issue by pjcreath** [saltstack/salt#64228]
**Description**
The "Support for Python versions" page says all three of the following:
* Salt 3006.0 requires Python 3.5 or higher.
* Salt 3006 requires Python 3.7 or higher.
* Salt 3005 is the last release that supports Python versions 3.5 and 3.6. In Salt release 3006, only Python versions 3.7 and higher will be supported.

**Suggested Fix**
It looks like the first statement should be "Salt 3005 requires Python 3.5 or higher".

I'm also not clear what the intent of "currently supported versions" vs. "future supported versions" is.

**Type of documentation**
Install guide

**Location or format of documentation**
https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-python-version-support.html

**Comment by pjcreath** [comment]
Also, it appears that development now requires Python 3.9, due to a python-tools-scripts requirement used by the pre-commit hooks.

**Comment by barbaricyawps** [comment]
Thanks for the note. This was basically stale content from 3005 that uses variables and didn't get updated for 3006. I included it in a different MR that I have open fixing this: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/113

**Comment by barbaricyawps** [comment]
MR was merged. Closing as this should be fixed now.

**Comment by pjcreath** [comment]
When would you expect this to be reflected in the online documentation?  (I'm not sure what happens on gitlab vs. github?)

**Comment by barbaricyawps** [comment]
In talking with the SRE team, it should have published live shortly after merging, but it looks like there's a hiccup. I'll investigate.

**Comment by barbaricyawps** [comment]
@pjcreath , I figured out the problem and it's fixed now. Changes are live: https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-python-version-support.html

Re: your note about using 3.9 in development, that note might work better in the Contributing guide. I'll look into putting that info there somewhere.
