### ISSUE TITLE
[FEATURE REQUEST] Add Salt support for Photon 5

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#64220]
**Is your feature request related to a problem? Please describe.**
VMware Photon 5.0 went GA 2nd May 2023, need to add support for the latest version of Photon

**Describe the solution you'd like**
Salt support for the Photon 5.0 platform, similar to existing support for Photon 3 and 4

**Describe alternatives you've considered**
Given VMware, I don't believe there is an alternative to supporting Photon 5

**Additional context**

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

- [ ] Add golden image for Photon 5
- [ ] Add test coverage for Photon 5
- [ ] Build packages for Photon 5
- [ ] Test built packages for Photon 5

**Comment by s0undt3ch** [comment]
Golden Image - https://github.com/saltstack/salt-jenkins/pull/1809

Currently only ARM64 since there isn't a x86_64 AMI available yet.

**Comment by s0undt3ch** [comment]
After checking with the PhotonOS Team; We need to import and maintain the base AMI - https://github.com/vmware/photon/wiki/Downloading-Photon-OS#downloading-photon-os-50-ga

**Comment by ScriptAutomate** [comment]
Photon 5 is officially supported, and included in the install guide:

- https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/photonos.html

Closing
