### ISSUE TITLE
Upcoming major releases of Chocolatey products that may impact functionality on the module

### ISSUE THREAD

**Issue by pauby** [saltstack/salt#64271]
I'm the Technical Engineering Manager at Chocolatey Software, Inc. and I wanted to make sure you are aware that there will be a new major release of Chocolatey products soon. As it is a major release, we are making changes that may have an impact on the Chocolatey module.

We have beta versions of [Chocolatey CLI](https://community.chocolatey.org/packages/chocolatey) and [Chocolatey GUI](https://community.chocolatey.org/packages/chocolateygui) publicly available that you can test against. 

The release notes for the various products are below (some may or may not be applicable to the module, but I wanted to list them all for completeness):

* [Chocolatey CLI](https://docs.chocolatey.org/en-us/choco/release-notes)
* [Chocolatey Licensed Extension](https://docs.chocolatey.org/en-us/licensed-extension/release-notes)
* [Chocolatey Agent](https://docs.chocolatey.org/en-us/agent/release-notes)
* [Chocolatey GUI](https://docs.chocolatey.org/en-us/chocolatey-gui/release-notes)
* [Chocolatey GUI Licensed Extension](https://docs.chocolatey.org/en-us/chocolatey-gui-licensed-extension/release-notes)

We have no fixed date for release as yet, but it is coming soon.

Apologies for the non-standard issue (I could not find any other way to contact the team). Please let me know if I can help in any way.

**Comment by pauby** [comment]
@twangboy Thanks for moving this to the correct place.

If you check out the release notes I pasted the links to in the original comment, you can see what changes have been made to the beat releases that have been made (2.0.0 betas or 6.0.0 betas for Chocolatey Licensed Extension). The [Chocolatey CLI milestone](https://github.com/chocolatey/choco/milestone/54) will also likely be helpful.

**Comment by chdeliens** [comment]
Hi everyone,

I confirm that I can no longer manage Chocolatey packages via Salt after upgrading/bootstrapping Chocolatey 2.0 on client devices.

Since it's not yet supported in Salt (I can see it's for the next milestone 3007.0), here's my workaround to downgrade to 1.4.0 (latest Chocolatey version supported by Salt 3006.1):

```
salt '[target]' cmd.run 'c:\programdata\chocolatey\bin\choco.exe upgrade chocolatey --version=1.4.0 --allow-downgrade --yes --force'
```

Of course, change the Salt `[target]` as you wish. Hope this helps someone!

**Comment by pauby** [comment]
The Chocolatey products were released today. Please refer to the above links for the release notes. Here is some more information that may be helpful:

* [Blog Post](https://blog.chocolatey.org/2023/05/announcing-chocolatey-products-2-and-6/).
* [Guide to upgrading](https://docs.chocolatey.org/en-us/guides/upgrading-to-chocolatey-v2-v6).
* [Highlight of changes](https://docs.chocolatey.org/en-us/choco/new-in-v2).

Please let me know if you need any more details.
