### ISSUE TITLE
[DOCS] dead link in modules.win_path

### ISSUE THREAD

**Issue by OrangeDog** [saltstack/salt#64290]
**Description**
http://support.microsoft.com/kb/104011

**Suggested Fix**
Find where the information is now, copy the relevant parts from an archive of it, or just remove it.

**Type of documentation**
Salt modules

**Location or format of documentation**
https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.win_path.html

**Comment by Tanmoy037** [comment]
@barbaricyawps I would like to work on this, please assign this to me.
