### ISSUE TITLE
[TECH DEBT] Upgrade Tornado

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#64305]
We're using a very old tornado version and have been working for some time to be able to upgrade. The time to upgrade is now.

**Comment by OrangeDog** [comment]
Does this obsolete #61380 or is that still going to happen later?

**Comment by dwoz** [comment]
> Does this obsolete #61380 or is that still going to happen later?

We still want to get off tornado for everything outside of salt-api and saltnado. This enables us to wean off tornado co-routines with smaller changes.

**Comment by s0undt3ch** [comment]
Upgrade to tornado 6.1 has landed in master.

Not closing since I believe @dwoz still wants to make the necessary changes to support tornado 6.2
