### ISSUE TITLE
[BUG] 3006.1: No Top file or master_tops data matches found[BUG]

### ISSUE THREAD

**Issue by cmyxap** [saltstack/salt#64301]
**Description**
Hello There. I have upgraded my system to Salt 3006.1 version. I am executing a highstate from a machine who's master is a syndic; Both machines upgraded - error I receive is "No Top file or master_tops data matches found.". I haven't changed anything from the setup since 3002 version of Salt, but now it isn't working. 

Output from command:

local:
----------
          ID: states
    Function: no.None
      Result: False
     Comment: No Top file or master_tops data matches found. Please see master log for details.
     Changes:   

Summary for local
------------
Succeeded: 0
Failed:    1
------------
Total states run:     1
Total run time:   0.000 ms

**Setup**
(Please provide relevant configs and/or SLS files (be sure to remove sensitive info. There is no general set-up of Salt.)

/etc/salt/master.d/settings.conf     ## on the master/syndic

syndic_master: <saltstack.master.url>
file_roots:
  env1:
    - /srv/salt/env1
    - /opt/product1
pillar_roots:
  env1:
    - /srv/pillar/env1
pillarenv_from_saltenv: True

/srv/salt/env1/top.sls

#! yaml
env1:
  '*':
    - common
    - ssh
    - sudo
    - vim

minion config file:

saltenv: env1
pillarenv_from_saltenv: True
master: <master ip>
log_level: quiet
use_superseded:
  - module.run

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
executing "salt-call state.highstate -ldebug" from minion

debug level logs show this:

	 Could not find file 'salt://top.sls' in saltenv 'env1'
[DEBUG   ] No contents found in top file. If this is not expected, verify that the 'file_roots' specified in 'etc/master' are accessible. The 'file_roots' configuration is: {'env1': []}

**Expected behavior**
I expect to have the highstate executed and the states described in top.sls file to be run on the minion.

**Screenshots**

**Versions Report**
salt 3006.1  for both salt-syndic and salt-minion
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: 6.1.2
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04.5 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-148-generic
        system: Linux
       version: Ubuntu 20.04.5 focal

```yaml
PASTE HERE
```
</details>

**Additional context**
Nothing changed from previous version which was working; Possible bug for 3006.1? THanks in advance!

**Comment by whytewolf** [comment]
3006.0 and .1 brought a change to the user that salt runs as. most likely it can not read your old files if they still have root only permission. make sure the files are accessible from the user salt.

**Comment by cmyxap** [comment]
Whytewolf, how come I didn't think of that ;D ...thanks a lot, this was the issue; After change of user/permissions highstate is now running properly

**Comment by cmyxap** [comment]
> Did you follow all the migration steps for 3003, 3004, 3005, and 3006?
> 
> Can you also edit the title of the issue to e.g. "[BUG] 3006.1: No Top file or master_tops data matches found"

I didn't follow anything in particular, directly upgraded from 3002 to 3006, changing the repository;
