### ISSUE TITLE
[TECH DEBT] Replace pycurl/tornado with requests in salt.utils.http

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#64371]
Having pycurl as a dependency for making web requests behind a proxy causes issues under our onedir packaging approach. Pycurl has no plans of releasing wheels meaning users will have to compile against libcurl. We have plans to migrate away from tornado anyway so it makes sense to replace pycurl and tornado with the python requests library.

**Comment by dwoz** [comment]
See also #64299

**Comment by Zpell82** [comment]
if this is implemented do a piece of news about it in good time, we have built proxy-minion tools using the "native" solution that would require a lot of rebuilding if implemented

**Comment by dwoz** [comment]
> if this is implemented do a piece of news about it in good time, we have built proxy-minion tools using the "native" solution that would require a lot of rebuilding if implemented

Can you explain more. If the proxy functionality in `salt.utils.http` works the same as it did before, why will that break things for you?

**Comment by dwoz** [comment]
My understanding is that proxy support is now fully working again (as of 3006.8) the last issue as fixed by #66163.
