### ISSUE TITLE
[TECH DEBT] Replace libnacl with pynacl

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#64372]
libnacl has been plagued with issues for some time now. We are no longer actively maintaining libnacl. An alternative, pynacl is being actively maintained and has all the bits we need for salt. Migrate from libnacl to pynacl. All of the changes needed should be in `salt.utils.nacl`.

**Comment by dwoz** [comment]
See also: #64342

**Comment by dmurphy18** [comment]
Closing this since PR https://github.com/saltstack/salt/pull/64415 is merged
