### ISSUE TITLE
[FEATURE REQUEST] Vault: Allow to specify the trusted CA root certificate inline

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#64379]
**Is your feature request related to a problem? Please describe.**
The Vault integration uses `requests`, which does not respect the system default CA bundle\*. Using an internal CA, it is cumbersome to ensure the internal root certificate is trusted by all minions since the `verify` parameter to `requests` requires a local file. Furthermore, since I know only this CA will issue certificates for my Vault cluster, I would like to restrict valid CA certs to this one.

\* Some distribution packages patch in that behavior, but with onedir packaging that became irrelevant.

**Describe the solution you'd like**
Allow to specify the root CA cert in the configuration directly and distribute it together with the other server connection parameters:
```yaml
vault:
  # [...]
  url: https://myvault.example.com:8200
  verify: |
    -----BEGIN CERTIFICATE-----
    [...]
```

**Describe alternatives you've considered**
* Have a state that writes the certificate to a consistent file path and specify it in the configuration.
* Have a state that writes the certificate to inconsistent file paths and override the `verify` parameter on the minions.

**Comment by dmurphy18** [comment]
Note, the PR https://github.com/saltstack/salt/pull/62684 is being moved to a salt extension for the Salt 3007 release
