### ISSUE TITLE
[DOCS] [Package Tests] Add instructions on how to run the package tests

### ISSUE THREAD

**Issue by MKLeb** [saltstack/salt#64400]
**Description**
Currently, the package tests are a black box for the community.  There are some prerequisites that are not documented well anywhere.  We should document them and the process of running the package tests.

**Comment by MKLeb** [comment]
@barneysowood, based on your open hour question, I have added this docs issue and get to it when I have the time.  Likely, at the very least, after the completion of https://github.com/saltstack/salt/issues/64387

**Comment by barneysowood** [comment]
@MKLeb - this is great, thanks very much!

**Comment by barbaricyawps** [comment]
@MKLeb , feel free to add me as a reviewer on any PRs.
