### ISSUE TITLE
[DOCS] Security Feed link leads to 404

### ISSUE THREAD

**Issue by jheiselman** [saltstack/salt#64423]
**Description**
The security feed link (https://saltproject.io/feed/?post_type=security) linked from https://docs.saltproject.io/en/latest/topics/about_salt_project.html#security-advisories leads to a 404. The security announcements link (https://saltproject.io/security-announcements/) does as well.

**Suggested Fix**
Just working like it used to.

**Type of documentation**
Security

**Location or format of documentation**
https://saltproject.io/security-announcements/

**Comment by jheiselman** [comment]
This appears to have broken sometime over the last few days.

**Comment by barbaricyawps** [comment]
It's related to the Salt Project being down for maintenance. We're working on a fix currently and we'll have an update for you soon.

**Comment by ScriptAutomate** [comment]
Some updates here:

- https://saltproject.io/security-announcements/ is now up and functional
- New RSS for security announcements: https://saltproject.io/security-announcements/index.xml

We will continue repopulating the site with the backlog of older security announcements, blog posts, etc. and will also be seeing whether we can get a redirect in place from the old RSS feed link.

**Comment by Ch3LL** [comment]
Closed by https://github.com/saltstack/salt/pull/65189
