### ISSUE TITLE
Add S3 State

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#6443]
Add a state function like `s3.bucket_exists`

**Comment by cachedout** [comment]
@scott-w I know this is waaaay old, but did you ever finish up the `aws_bucket` state? We'd love to have it, if you did. :]

**Comment by scott-w** [comment]
@cachedout I didn't unfortunately. I don't even know if the code I wrote up there would merge any more. I can throw up a PR if anyone wants to take it forward?
