### ISSUE TITLE
[BUG] Stalebot closed 40058: pillar.show_top and state.show_top differ in functionality

### ISSUE THREAD

**Issue by darkpixel** [saltstack/salt#64432]
Bug #40058 was closed by Stalebot.
Stalebot should probably continue automatically closing issues that are waiting on additional information that never arrives, but Stalebot shouldn't close bugs or feature requests that developers don't have a chance to handle in a timely manner.  It's not like the bug or feature request suddenly went away due to staffing shortages.

Anyways, I'm trying to debug some "missing" pillar data, and the current ```salt-run pillar.show_top minion=myminionid``` is useless because it just basically dumps the contents of my top.sls file instead of showing what pillar files are being applied to the specific minion (like ```salt-call pillar.show_top``` does for states).

Original bug report:

**Description of Issue/Question**
state.show_top returns information relegated to the minion in relation to the top file. pillar.show_top returns the entire pillar top file.

**Setup**
run "salt "minion" state.show_top and then salt-run pillar.show_top minion=minion and see the different results.

**Steps to Reproduce Issue**
run "salt "minion" state.show_top and then salt-run pillar.show_top minion=minion and see the different results.

**Desired Result**
pillar.show_top shows the pillars relegated to the minion like the state.show_top does

**Comment by anilsil** [comment]
Hi @darkpixel, is this happening on 3006.x?

**Comment by darkpixel** [comment]
My salt master is ```3005.1```.

I'm working to migrate to a new server, but that's delayed because you can't just update the ```master``` setting in a minion and restart it as it runs into keying issues, and I'm not quite ready to manage two salt masters for a few weeks or months while I manually move a few thousand minions over.

As soon as I get that sorted out, I will give it a shot.

**Comment by OrangeDog** [comment]
> Stalebot should probably continue

It was turned off years ago

**Comment by darkpixel** [comment]
Thanks @OrangeDog
