### ISSUE TITLE
Reason: 'docker_image' __virtual__ returned False: 'docker.version' is not available.

### ISSUE THREAD

**Issue by AlexandreDdaCosta** [saltstack/salt#64447]
**Description**
State file fails; SaltStack unable to find docker. Yet docker is installed and visible to Salt.

**Setup**
This is the Debian installation of Salt. See versions report below.

**Steps to Reproduce the behavior**
Run highstate. Failed output as follows:

          ID: dpage/pgadmin4
    Function: docker_image.present
      Result: False
     Comment: State 'docker_image.present' was not found in SLS 'services/database'
              Reason: 'docker_image' __virtual__ returned False: 'docker.version' is not available.
     Changes:

**Expected behavior**
State should run and install docker image.

**Screenshots**
None

**Versions Report**

salt --versions-report
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.15.0
      cherrypy: Not Installed
      dateutil: 2.8.2
     docker-py: 6.1.3
         gitdb: 4.0.5
     gitpython: 3.1.14
        Jinja2: 3.0.3
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.0
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.7
        pygit2: Not Installed
        Python: 3.9.2 (default, Feb 28 2021, 17:03:44)
  python-gnupg: Not Installed
        PyYAML: 5.3.1
         PyZMQ: 22.3.0
         smmap: 4.0.0
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 6.1.0-0.deb11.5-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
</details>

**Additional context**
None

**Comment by s0undt3ch** [comment]
To work around the issue, install docker < 6.0

**Comment by s0undt3ch** [comment]
This issue however, is not present in Salt 3006.0 onward.

See https://github.com/saltstack/salt/commit/1bbf8d6b1819515b1ae56977a2dc7aa10d19200e

**Comment by AlexandreDdaCosta** [comment]
You got it. Your second comment was especially helpful since 3006 isn't available for distribution on Debian yet. So, I've simply edited the wayward file for now., and it will get overwritten when the 3006 release becomes available. I've run highstate again and confirmed that the issue is resolved. Thanks!

**Comment by mariusradusysc** [comment]
This issue is still present in 3006 and 3007
