### ISSUE TITLE
[BUG] Inconsistent use of args in ssh_auth.managed

### ISSUE THREAD

**Issue by rittycat** [saltstack/salt#64442]
**Description**
ssh_auth.managed does not fully respect arguments such as config, fingerprint_hash_type, options, etc

In particular, it will happily use all of the args available when making sure that keys are present, always putting new keys into their correct places. However, when determining what keys to remove or modify, it won't, always using the default `~/.ssh/authorized_keys` file, and other such default options for `ssh.auth_keys` and `ssh_auth.absent` calls

**Setup**
Standard setup in v3005 or v3006. Doesn't matter if it's a VM, on-prem or anything else. It is linux-only, however

Please be as specific as possible and give set-up details.

- [x] on-prem machine
- [x] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [x] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
I originally spotted this bug while using a different config file, so!

- Have some keys in `~/.ssh/authorized_keys`
- Make a state with `ssh_auth.managed` and specify a different path for `config`. Use one or more different keys to those you added to the default file
- Apply the state. You'll find your new file is created correctly, but the keys you added to  `~/.ssh/authorized_keys` have been removed
- Swap the keys in the state with some others
- Apply the state again. This time you'll find that the keys originally in the state were never removed, and new keys have only been appended

**Expected behavior**
All functions called by `ssh_auth.managed` should respect arguments provided where applicable

**Screenshots**

**Versions Report**
N/A, exists in v3005 and v3006's code. Haven't checked other releases

**Additional context**

**Comment by davama** [comment]
Was testing this and noticed this too


```
/root/.ssh/authorized_keys3:
  ssh_auth.manage:
    - user: root
    - source: salt://ssh_keys/all/root_authorized_keys3
    - config: '%h/.ssh/authorized_keys3'
    - ssh_keys:
      - ''
```

the above state removes any keys i have in `/root/.ssh/authorized_keys` 
currently on `v3006.2`

**Comment by Ch3LL** [comment]
Closed by https://github.com/saltstack/salt/pull/65046
