### ISSUE TITLE
[FEATURE REQUEST] Add support for Amazon 2023

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#64455]
**Is your feature request related to a problem? Please describe.**

Need to add packages and test support coverage for Amazon 2023

- [x] Add golden image for Amazon 2023
- [x] Add test coverage for Amazon 2023
- [ ] Build packages for Amazon 2023
- [ ] Test built packages for Amazon 2023

**Comment by ScriptAutomate** [comment]
Amazon Linux 2023 will be part of an upcoming 3006.x release, and in the upcoming 3007 version of Salt.
This issue will be closed once the packages are published, and the docs are updated:

- MR for docs in install guide, pending when packages are available: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/167

**Comment by ScriptAutomate** [comment]
Closing, as is officially supported now, and is included on the Amazon install directions:

- https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/amazon.html
