### ISSUE TITLE
[FEATURE REQUEST] Add Python 3.11 to onedir packages

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#64457]
**Is your feature request related to a problem? Please describe.**
Add Python 3.11 to onedir packages and ensure the tests are passing.  There is currently a draft PR here: https://github.com/saltstack/salt/pull/63753

- [ ] Add note to release notes that Python 3.11 is added.

**Comment by Ch3LL** [comment]
@s0undt3ch I've assigned this to you since you have a draft PR, but if you need help please reach out for more help on this task.

**Comment by s0undt3ch** [comment]
New draft PR #64458
