### ISSUE TITLE
Add an Amazon VPC state

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#6447]
Please add an Amazon VPC state

```
vpc.exists
```

**Comment by sebest** [comment]
+1

**Comment by dneades** [comment]
+1 from here, too. Ansible has this feature and it is really helpful.

**Comment by sebest** [comment]
Same thing here, using ansible only to setup the VPCs.

**Comment by techhat** [comment]
This appears to have been added: https://github.com/saltstack/salt/blob/develop/salt/states/boto_vpc.py
