### ISSUE TITLE
Consolidate ipc "transport" with others

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#64488]
There is a lot of duplicate functionality between `salt/transport/ipc.py` and `salt/transport/tcp.py`. The primary difference is that `salt.transport.base.PublishClient` is missing a `recv` method. Consolidating this functionality will allow us to maintain less code and it opens the door to allow different transports to be used for ipc communication between processes.

**Comment by OrangeDog** [comment]
Any details at all?
