### ISSUE TITLE
Drop contextvars requirement in requirements/base.txt?

### ISSUE THREAD

**Issue by Jsollvander** [saltstack/salt#64493]
This is probably a duplicate so I'll start with apologizing for that right of the bat.

From what I understand contextvars is part of stdlib since Python 3.7 and the pip version of contextvars is a backport to Python 3.6. Can we drop the contextvars requirement or change it so it's only required when running older versions of python?

**Comment by s0undt3ch** [comment]
`contextvars` is required for salt-ssh, we can't remove it.
We need to upload the backport to target machines, we can't use the `contextvars` available in the standard library because that's now a C extension.

Closing as there's no action to do here.

**Comment by s0undt3ch** [comment]
https://github.com/saltstack/salt/blob/master/requirements/base.txt#L11-L12
