### ISSUE TITLE
how to install salt minion on windows platform

### ISSUE THREAD

**Issue by tomyzhang2020** [saltstack/salt#64492]
You know,a large amount of windows clients,if I install salt minion one by one,that's a huge problem.So how to install salt minion on windows platform via saltstack master automatically?

**Comment by damon-atkins** [comment]
@tomyzhang2020 one option is to install it as part of the AD Join process.  These days most clouds would allow the install at initialisation of a VM.

**Comment by OrangeDog** [comment]
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/windows.html#install-windows
