### ISSUE TITLE
[TECH DEBT] Linode APIv3 Reaching End of Life on July 31, 2023

### ISSUE THREAD

**Issue by ScriptAutomate** [saltstack/salt#64517]
### Description of the tech debt to be addressed, include links and screenshots

Linode has deprecated APIv3, which will reach its end of life on July 31, 2023.

Version 4 of the Linode API has been available for some time, and is a major improvement over previous versions. Almost any task which can be done through the Cloud Manager can now be performed through the API. Documentation on their APIv4 can be found here: https://www.linode.com/docs/api/

They've also documented guidance on how to upgrade your existing APIv3 calls to APIv4: https://www.linode.com/docs/products/tools/api/guides/upgrade-to-v4/

It looks like `salt-cloud` supports APIv4 just fine, from a glance at configs and the code base, but APIv3 hitting EOL will mean all APIv3 code will fail to function, and all `salt-cloud` tests relying on APIv3 will stop functioning.

We need to verify that:

- salt-cloud is deprecating Linode APIv3 support
- salt-cloud default should be to use APIv4 (as there won't be any alternatives from an API standpoint)
- salt-cloud has functional support for APIv4 (it looks like it does already)
- salt-cloud tests are using APIv4 exclusively, so that the salt-cloud tests don't fail at the end of July for Linode

Potentially related issue: https://github.com/saltstack/salt/issues/58424

**Comment by zliang-akamai** [comment]
@ScriptAutomate may I have your help on reviewing the PR?
