### ISSUE TITLE
[TECH DEBT] Add a label to run a full test run

### ISSUE THREAD

**Issue by MKLeb** [saltstack/salt#64539]
### Description of the tech debt to be addressed, include links and screenshots
We need a label that allows a full test run to be run on PRs, only assignable by dev-core members.  This will allow us to trigger full runs on PRs that may have a broad scope, or perhaps the reach of which is unclear.  This way, we can catch stray failures before we merge and see them in nightly builds.

**Comment by s0undt3ch** [comment]
This has been implemented in the `3006.x` branch and will be merged forwarded into `master` soon.
