### ISSUE TITLE
[DOCS] Raspbian support is shown in Repository paths for 'onedir'

### ISSUE THREAD

**Issue by dmurphy18** [saltstack/salt#64601]
**Description**
Raspbian support is shown in Repository paths for 'onedir', https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#repository-paths

**Suggested Fix**
Remove Raspbian from 'onedir repository paths

```
  | Onedir path | Classic path
-- | -- | --
Centos | https://repo.saltproject.io/salt/py3/redhat/ | https://repo.saltproject.io/py3/redhat/
Debian | https://repo.saltproject.io/salt/py3/debian/ | https://repo.saltproject.io/py3/debian/
Fedora | Hosted on Fedora repos | Hosted on Fedora repos
MacOS | https://repo.saltproject.io/salt/py3/macos/ | https://repo.saltproject.io/osx/
Raspbian | n-a | https://repo.saltproject.io/py3/debian/
RedHat | https://repo.saltproject.io/salt/py3/redhat/ | https://repo.saltproject.io/py3/redhat/
Ubuntu | https://repo.saltproject.io/salt/py3/ubuntu/ | https://repo.saltproject.io/py3/ubuntu/
Windows | https://repo.saltproject.io/salt/py3/windows/ | https://repo.saltproject.io/windows/
```

**Type of documentation**
This should be Salt documentation Install Guide.

**Location or format of documentation**
https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#repository-paths

**Additional context**

**Comment by barbaricyawps** [comment]
K. I should be able to make this quick fix some time soon.

**Comment by dmurphy18** [comment]
@barbaricyawps Was this part of the salt install guide clean up for 3005.2/3006.2 ?, wanting to close it.

**Comment by barbaricyawps** [comment]
This was on my radar (and still is), it's just that about a million other priorities came before it. I can try to get to it soon.

**Comment by barbaricyawps** [comment]
I have a merge request open to resolve this: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/141

**Comment by dmurphy18** [comment]
Closing since https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/141 merged 10 months ago
