### ISSUE TITLE
[Code Coverage] Automated way to ensure the changes added to a PR have sufficient test coverage

### ISSUE THREAD

**Issue by Ch3LL** [saltstack/salt#64693]
Investigate and implement a way to ensure the changes added to a PR have sufficient test coverage. 
One possible solution: https://github.com/marketplace/actions/test-coverage-comparison-of-added-modified-files

**Comment by dmurphy18** [comment]
Note the Codecov Report has a statement on the **_diff coverage_** showing whether the lines added are covered as a percentage

The **_diff coverage_** is typically the second line of the Codecov Report. A value of 90% can be acceptable, for example: added an exception path and no test covering it, but tests for the regular paths in the code

**Comment by dmurphy18** [comment]
The diff coverage report from Codecov appears to fine to use giving percentage of coverage on your changes, so will use Codecov report, esp. since reduction in the Salt Core Team recently.
Closing this issue
