### ISSUE TITLE
[BUG] salt-master process taking high cpu

### ISSUE THREAD

**Issue by smmnazar** [saltstack/salt#64724]
**Description**
We are using 4 vCPU (AWS EC2 m6i.mlarge) server and sometimes salt-master process taking high cpu when see "top" command. But AWS cloudwatch report shows the CPU utilization is not spiked above 25%.

We have checked with AWS support and they says that salt configuration has to tweaked to use 4 vCPU, can you please provide necessary configuration changes to be done in salt master configuration for salt-master process to use all vCPU.

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ Y] VM running on an AWS cloud service, EC2
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Versions Report**
Salt Version:
          Salt: 3005.1

Dependency Versions:
          cffi: 1.14.4
      cherrypy: unknown
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10
       libgit2: Not Installed
      M2Crypto: 0.31.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.20
      pycrypto: 2.6.1
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.7.10 (default, Jun  3 2021, 00:02:01)
  python-gnupg: 0.4.6
        PyYAML: 4.2
         PyZMQ: 18.0.1
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3

System Versions:
          dist: amzn 2
        locale: UTF-8
       machine: x86_64
       release: 4.14.246-187.474.amzn2.x86_64
        system: Linux
       version: Amazon Linux 2

**Comment by OrangeDog** [comment]
How many minions do you have, and what do you see in "top"? It should match exactly what cloudwatch says.
The default configuration should make fine use of 4 cores.

**Comment by smmnazar** [comment]
@OrangeDog 

CPU is hot but we are not hitting 100% in cloudwatch metrics. Please see the top command snip below.

![image](https://github.com/saltstack/salt/assets/11322262/f85cd8b9-ed64-4ea0-9b43-66e86a0a91d0)

See the cloudwatch snip below.

![image](https://github.com/saltstack/salt/assets/11322262/67343df2-4a4e-47a3-b6c1-6942e2c7b789)

**Comment by smmnazar** [comment]
@OrangeDog any update?

**Comment by smmnazar** [comment]
@OrangeDog the default configuration is not matching to use 4 cores and it only using single core of CPU. Any idea?

**Comment by dwoz** [comment]
Can you install `setproctitle` and let us know which process is consuming the cpu?

**Comment by smmnazar** [comment]
Server is good after I changed salt master config file to use all vCPU. Thanks all
