### ISSUE TITLE
[DOCS] The wheel.file_roots.read function description is incomplete.

### ISSUE THREAD

**Issue by justinclloyd** [saltstack/salt#64886]
**Description**
The [salt.wheel.file_roots.read](https://docs.saltproject.io/en/latest/ref/wheel/all/salt.wheel.file_roots.html#module-salt.wheel.file_roots) function documentation is an incomplete string.

**Type of documentation**
Both the web site and the output of `salt-run doc.wheel` show this incomplete documentation.

**Location or format of documentation**
https://docs.saltproject.io/en/latest/ref/wheel/all/salt.wheel.file_roots.html#module-salt.wheel.file_roots

**Comment by OrangeDog** [comment]
Already fixed in 22c4437580836577d9831ca48c788181bd5b97f1.
