### ISSUE TITLE
[BUG] win_wua.list not manage "Quality Updates"

### ISSUE THREAD

**Issue by madurani** [saltstack/salt#64930]
**Description**
Salt module **win_wua.list drivers=True summary=True** reported "Nothing to return", but on windows client is via graphical gui one package available from categories **"Quality Updates"** >> KB5028254. All other patches were installed via win_wua.list properly.

```
[root@tmv2007 ~]# salt tml1026\* win_wua.list drivers=True summary=True
tml1026.minion:
    Nothing to return
```

**Setup**

```
[root@tmv2007 ~]# salt-master --versions-report
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.32
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.8 n/a
        locale: utf-8
       machine: x86_64
       release: 4.18.0-477.13.1.el8_8.x86_64
        system: Linux
       version: Oracle Linux Server 8.8 n/a`
```

**Comment by twangboy** [comment]
Does setting Drivers to ``False`` have any effect on the return?

**Comment by twangboy** [comment]
The initial search criteria are in the `win_update` salt util on line 389:
https://github.com/saltstack/salt/blob/master/salt/utils/win_update.py#L389

The search parameters are here:
https://learn.microsoft.com/en-us/windows/win32/api/wuapi/nf-wuapi-iupdatesearcher-search#remarks

You could try different combinations of things... I've tried this so far, but this is hard to replicate on another machine as mine doesn't have the same updates as yours. In face, in my test case, the win_wua list was returning more than what was showing in the GUI. But mine doesn't show a feature update, which I see in the GUI.

Here's what I've been trying so far:
```
        search_string = (
            "(Type='Software' or Type='Driver') and "
            "(BrowseOnly=0 or BrowseOnly=1) and "
            "DeploymentAction=*"
        )
```

**Comment by madurani** [comment]
It look that search feature help. I need test it on more win clients...

**Comment by madurani** [comment]
I again found win 11 where salt reported, that all reachable patches were implemented, but windows gui found KB5029351 which wasn't installed:

**From Linux**
```
[root@tmv2007 ~]# salt tml1070.minion win_wua.list drivers=True summary=True install=True
tml1070.minion:
    ----------
    Download:
        ----------
        Success:
            False
        Updates:
            Nothing to download
    Install:
        ----------
        Success:
            False
        Updates:
            Nothing to install

```
```
[root@tmv2007 ~]# salt tml1070.minion win_wua.installed | grep -i kb5029351
[root@tmv2007 ~]# 
```
**From win:**
![Screenshot 2023-08-23 095430](https://github.com/saltstack/salt/assets/49711883/e4692d24-767b-4731-949a-c9435902afd6)

**Comment by twangboy** [comment]
Is this machine on a preview path for updates?

**Comment by twangboy** [comment]
Closing due to lack of response.
