### ISSUE TITLE
[BUG] license.install  issue: Error: 0xC004E016

### ISSUE THREAD

**Issue by madurani** [saltstack/salt#64948]
**Description**
Attempt to install activation's key to windows professional 11 crashed with error:
```
[root@tmv2007 opt]# salt tml1047.minion license.info
tml1047.minion:
    ----------
    description:
        Windows(R) Operating System, RETAIL channel
    licensed:
        True
    name:
        Windows(R), Professional edition
    partial_key:
        3V66T
[root@tmv2007 opt]# salt tml1047.minion license.install xxxxxxxxxxx
tml1047.minion:
    Microsoft (R) Windows Script Host verzia 5.812
    Copyright (C) Microsoft Corporation. Vçetky pr va vyhraden‚.
    
    Error: 0xC004E016 On a computer running Microsoft Windows non-core edition, run 'slui.exe 0x2a 0xC004E016' to display the error text.
ERROR: Minions returned with non-zero exit code
```
When is same code manually added via windows activation gui to same win minion, so is accepted and can be activated.

```
[root@tmv2007 ~]# salt-master --versions-report
Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.10
     gitpython: 3.1.32
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: 5.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: oracle 8.8 n/a
        locale: utf-8
       machine: x86_64
       release: 4.18.0-477.13.1.el8_8.x86_64
        system: Linux
       version: Oracle Linux Server 8.8 n/a
```

**Comment by OrangeDog** [comment]
> run 'slui.exe 0x2a 0xC004E016' to display the error text.

What did it say?

**Comment by madurani** [comment]
![Screenshot 2023-08-11 075712](https://github.com/saltstack/salt/assets/49711883/8ff01e86-c0c6-407d-9c5c-9da1b2ffda8c)

Message is: License service find out, that kode Product Key is invalid 

But when i same code paste via windows gui: change product key + activation of code, then is all accepted and windows is activated

**Comment by sanderc85** [comment]
What will happen if you run the following command on the Windows machine?

```
cscript C:\Windows\System32\slmgr.vbs /ipk xxxxxxxxxxx
```

Where `xxxxxxxxxxx` is your producte key.

**Comment by sanderc85** [comment]
It's not a issue in Salt, the error is from Windows.

For what I can find the issue can be various. Based on the error message I have found some sites which could help, like https://answers.microsoft.com/en-us/windows/forum/all/error-0xc004e016-on-windows-10-serial-key-invalid/436ba900-b8ee-4ba8-8f44-aeb87d6cedf2 or https://answers.microsoft.com/en-us/windows/forum/all/how-to-troubleshoot-product-activation-in-windows/33f31475-93b3-4d1c-812f-4b21fbd807a7.
