### ISSUE TITLE
[BUG] Debian 12 "Bookworm" package missing

### ISSUE THREAD

**Issue by chruck** [saltstack/salt#64997]
**Description**
The Salt Install Guide says at https://docs.saltproject.io/salt/install-guide/en/latest/topics/salt-supported-operating-systems.html#debian :
> Debian
> Debian stable, oldstable, and oldoldstable versions.

However, the latest stable version is Debian 12.1 "Bookworm".  But the repository at https://repo.saltproject.io/salt/py3/debian/ only has Debian 10 and 11.

**Setup**
* If using Docker:
```shell
docker pull debian:12
```
* If using VMware Workstation, create a VM with all defaults using the ISO at:  https://www.debian.org/CD/netinst/ (specifically, I used https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-12.1.0-amd64-netinst.iso ).

- [ ] on-prem machine
- [x] VM:  VMware Workstation
- [ ] VM running on a cloud service, please be explicit and add details
- [x] container: Docker
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [x] used bootstrap to install

**Steps to Reproduce the behavior**
Bootstrap used, but it correctly went to where there should be a package, https://repo.saltproject.io/salt/py3/debian/12 .  This directory does not exist, but `10` and `11` do.
```shell
docker run --rm -it debian:12
# I also created a Deb12 "netinst" VM in VMWare Workstation and ran the following:
apt update
apt install wget
wget https://bootstrap.saltproject.io -O bootstrap-salt.sh
bash ./bootstrap-salt.sh

...installs packages, then gives errors:

 * ERROR: https://repo.saltproject.io/salt/py3/debian/12/amd64/latest/salt-archive-keyring.gpg failed to download to /tmp/salt-gpg-VIaybYqv.pub
 * ERROR: https://repo.saltproject.io/salt/py3/debian/12/amd64/latest/SALT-PROJECT-GPG-PUBKEY-2023.gpg failed to download to /tmp/salt-gpg-faveooD3.pub
 * ERROR: Failed to run install_debian_onedir_deps()!!!
```

**Expected behavior**
There should be a salt minion package found in https://repo.saltproject.io/salt/py3/debian/12

**Screenshots**
none

**Versions Report**
n/a

**Additional context**
n/a

**Comment by OrangeDog** [comment]
Duplicates #64223.

Wasn't done fast enough to keep the documentation correct.

**Comment by chruck** [comment]
Sorry, I should have searched existing bugs.  Since this one has been milestone'd `Sulfur v3006.3`, should #64223 also be milestone'd `Sulfur v3006.3` (from `Chlorine v3007.0`)?
