### ISSUE TITLE
[BUG] yum Fails to Install CentOS 7 Repo

### ISSUE THREAD

**Issue by ddspell** [saltstack/salt#64996]
**Description**
https://repo.saltproject.io/salt/py3/redhat/7/x86_64/latest/repodata/repomd.xml.asc: [Errno 14] HTTPS Error 404 - Not Found

**Setup**
Followed instructions...
sudo rpm --import https://repo.saltproject.io/salt/py3/redhat/7/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub
curl -fsSL https://repo.saltproject.io/salt/py3/redhat/7/x86_64/latest.repo | sudo tee /etc/yum.repos.d/salt.repo

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [X ] VM on Nutanix AOS
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Did the setup, then...
sudo yum clean expire-cache
sudo yum repolist

**Expected behavior**
Expected that repo DB would update without a 404.

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)
Not possible given that I'm trying to install the salt-minion.
Salt is not installed on this VM.

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by whytewolf** [comment]
@ddspell do you have any extra settings in your yum configuration for this system? or any packages installed? I can not duplicate this issue on a fresh install. and we have never had a repomd.xml.asc our repomd.xml file is not signed. 

was any errors displayed when you ran `sudo rpm --import https://repo.saltproject.io/salt/py3/redhat/7/x86_64/SALT-PROJECT-GPG-PUBKEY-2023.pub` 

if you run `rpm -q --queryformat "%{SUMMARY}\n" $(rpm -q gpg-pubkey)` does `gpg(Salt Project Packaging <saltproject-packaging@vmware.com>)` show up in the list? 

notable `repo_gpgcheck` is what causes that error.

**Comment by ddspell** [comment]
Thanks for looking into this.
I'm actually looking into installing and older version (3005.2) and I'm running into issues.
I'll work through it.
