### ISSUE TITLE
[TECH DEBT] support for pysss can be removed

### ISSUE THREAD

**Issue by nicholasmhughes** [saltstack/salt#65029]
### Description of the tech debt to be addressed, include links and screenshots
...at least in the context of user management. It seems that there may have been a package called `pysss` which presumably offered user/group management capabilities.

However, that package is no longer related to that capability:

**PyPi:** https://pypi.org/project/pysss/

**GitHub:** https://github.com/mohamed/pysss

The sections below are referencing that package, and further digging should probably be done to see if it's used anywhere else.

https://github.com/saltstack/salt/blob/c9512a18537935ed44e798602920c18629125994/salt/utils/user.py#L34,L39

https://github.com/saltstack/salt/blob/c9512a18537935ed44e798602920c18629125994/salt/utils/user.py#L304,L310

### Versions Report
3006.2/master (dated 2023-08-22)

**Comment by whytewolf** [comment]
Thank you for the ticket. I know you are setup to handle this and https://github.com/saltstack/salt/issues/64953 and https://github.com/saltstack/salt/issues/64888 together. so I"ll assign this to myself. let me know when you get that PR in.
