### ISSUE TITLE
[BUG] After upgrading from salt 2019.2.8 to salt 3005.1 salt-ssh no longer works

### ISSUE THREAD

**Issue by gwohletz** [saltstack/salt#65070]
**Description**
After upgrading from salt 2019.2.8 to salt 3005.1 salt-ssh no longer works

**Setup**
simple state file for test:

bc:
  pkg.installed

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ X] VM running on a cloud service, please be explicit and add details
- AWS ec2
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ X] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
salt-ssh --ignore-host-keys -l trace 10.40.10.72 state.apply bc

**Expected behavior**
state is applied (works on older version of salt)

**Versions Report**
Salt Version:
          Salt: 3005.1
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.0
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
        Python: 3.9.16 (main, Jan  6 2023, 22:49:49)
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 18.04 bionic
        locale: utf-8
       machine: x86_64
       release: 4.15.0-20-generic
        system: Linux
       version: Ubuntu 18.04 bionic

**Additional context**
```
salt-ssh --ignore-host-keys -l trace 10.40.10.72 state.apply bc
[initial debug output left out for brevity]

[DEBUG   ] Rendered data from file: /var/tmp/.root_1af85c_salt/running_data/var/cache/salt/minion/files/base/bc/init.sls:
bc:
  pkg.installed

[PROFILE ] Time (in seconds) to render '/var/tmp/.root_1af85c_salt/running_data/var/cache/salt/minion/files/base/bc/init.sls' using 'yaml' renderer: 0.000102996826171875
[ERROR   ] TypeError encountered executing state.apply: Object of type bytes is not JSON serializable
Traceback (most recent call last):
  File "salt/client/ssh/__init__.py", line 1259, in run_wfunc
    result = self.wfuncs[self.fun](*self.args, **self.kwargs)
  File "salt/loader/lazy.py", line 149, in __call__
    return self.loader.run(run_func, *args, **kwargs)
  File "salt/loader/lazy.py", line 1228, in run
    return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
  File "salt/loader/lazy.py", line 1243, in _run_as
    return _func_or_method(*args, **kwargs)
  File "/opt/saltstack/salt/run/salt/client/ssh/wrapper/state.py", line 516, in apply_
    return sls(mods, **kwargs)
  File "/opt/saltstack/salt/run/salt/client/ssh/wrapper/state.py", line 222, in sls
    trans_tar = salt.client.ssh.state.prep_trans_tar(
  File "salt/client/ssh/state.py", line 206, in prep_trans_tar
    salt.utils.json.dump(pillar, fp_)
  File "salt/utils/json.py", line 116, in dump
    return json_module.dump(obj, fp, **kwargs)
  File "json/__init__.py", line 179, in dump
  File "json/encoder.py", line 431, in _iterencode
  File "json/encoder.py", line 405, in _iterencode_dict
  File "json/encoder.py", line 405, in _iterencode_dict
  File "json/encoder.py", line 405, in _iterencode_dict
  File "json/encoder.py", line 438, in _iterencode
  File "json/encoder.py", line 179, in default
TypeError: Object of type bytes is not JSON serializable
[DEBUG   ] The functions from module 'nested' are being loaded by dir() on the loaded module
[DEBUG   ] LazyLoaded nested.output
[TRACE   ] data = {'10.40.10.72': 'TypeError encountered executing state.apply: Object of type bytes is not JSON serializable'}
10.40.10.72:
    TypeError encountered executing state.apply: Object of type bytes is not JSON serializable
[TRACE   ] IPCClient: Connecting to socket: /var/run/salt/master/master_event_pull.ipc
[DEBUG   ] Sending event: tag = salt/job/20230828172913900334/ret/10.40.10.72; data = {'return': 'TypeError encountered executing state.apply: Object of type bytes is not JSON serializable', 'id': '10.40.10.72', 'fun': 'state.apply', 'jid': '20230828172913900334', '_stamp': '2023-08-28T17:29:22.928961'}
[DEBUG   ] Closing IPCMessageClient instance
[DEBUG   ] Restoring sys.argv to: ['/opt/saltstack/salt/run/run', '--ignore-host-keys', '-l', 'trace', '10.40.10.72', 'state.apply', 'bc']
```

Note: this only appears to happen when executing state.apply salt-ssh works correctly if you do something like cmd.run:

```
# salt-ssh --ignore-host-keys -l info 10.40.10.72 cmd.run date
[WARNING ] Using the old YAML Loader for rendering, consider disabling this and using the tojson filter.
[WARNING ] Using the old YAML Loader for rendering, consider disabling this and using the tojson filter.
10.40.10.72:
    Mon Aug 28 17:50:00 UTC 2023
```

**Comment by gwohletz** [comment]
Note: this only appears to happen when executing state.apply salt-ssh works correctly if you do something like cmd.run:

```
# salt-ssh --ignore-host-keys -l info 10.40.10.72 cmd.run date
[WARNING ] Using the old YAML Loader for rendering, consider disabling this and using the tojson filter.
[WARNING ] Using the old YAML Loader for rendering, consider disabling this and using the tojson filter.
10.40.10.72:
    Mon Aug 28 17:50:00 UTC 2023
```

**Comment by gwohletz** [comment]
additional note:

I initially had issues with ModuleNotFoundError: No module named 'contextvars', which i worked around by manually installing this pip module on the target, but this may point to something not being right with how salt-ssh is shipping over the python modules

**Comment by Ch3LL** [comment]
I'm having a hard time replicating this. Can you try running with the arguments `-wt`

**Comment by anilsil** [comment]
Closing as cannot be reproduced.

**Comment by gwohletz** [comment]
verified salt 3006.2 does not have this issue
