### ISSUE TITLE
syndic cant connect to minion [BUG]

### ISSUE THREAD

**Issue by Erickhawk** [saltstack/salt#65103]
**Description**
the problem is that when I install syndic and the minion,the master can naturally connect to the syndic ,but the minion cant connect  succcess to syndic, there is no log print indicate reason,the only log is 

2023-09-03 21:30:25,019 [salt.crypt       :514 ][DEBUG   ][2494] Re-using AsyncAuth for ('/etc/salt/pki/minion', '**********', 'tcp://172.27.128.44:4506')
2023-09-03 21:30:25,019 [salt.transport.zeromq:156 ][DEBUG   ][2494] Generated random reconnect delay between '1000ms' and '11000ms' (5865)
2023-09-03 21:30:25,019 [salt.transport.zeromq:163 ][DEBUG   ][2494] Setting zmq_reconnect_ivl to '5865ms'
2023-09-03 21:30:25,020 [salt.transport.zeromq:167 ][DEBUG   ][2494] Setting zmq_reconnect_ivl_max to '11000ms'
2023-09-03 21:30:25,020 [salt.crypt       :208 ][DEBUG   ][2494] salt.crypt.get_rsa_key: Loading private key
2023-09-03 21:30:25,020 [salt.crypt       :900 ][DEBUG   ][2494] Loaded minion key: /etc/salt/pki/minion/minion.pem
2023-09-03 21:30:25,029 [salt.utils.event :315 ][DEBUG   ][2494] SaltEvent PUB socket URI: /var/run/salt/minion/minion_event_f9efea8806_pub.ipc
2023-09-03 21:30:25,029 [salt.utils.event :316 ][DEBUG   ][2494] SaltEvent PULL socket URI: /var/run/salt/minion/minion_event_f9efea8806_pull.ipc
2023-09-03 21:30:25,029 [salt.crypt       :216 ][DEBUG   ][2494] salt.crypt.get_rsa_pub_key: Loading public key
2023-09-03 21:31:00,074 [salt.channel.client:313 ][DEBUG   ][2494] Closing AsyncReqChannel instance
2023-09-03 21:31:10,087 [salt.minion      :794 ][DEBUG   ][2494] Connecting to master. Attempt 176 (infinite attempts)

Salt Version:
          Salt: 3006.1
 
Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: centos 7.9.2009 Core
        locale: utf-8
       machine: x86_64
       release: 3.10.0-957.el7.x86_64
        system: Linux
       version: CentOS Linux 7.9.2009 Core
2.salt-master 172.27.128.67
   salt-syndic 172.27.128.44
   salt-minion 172.27.128.71
when i start run the commond on the the salt-minion to telnet 4505 with salt-syndic the result is 
[root@south-guangdong-guangzhou-27777777-node1 ~]# telnet 172.27.128.44 4505
Trying 172.27.128.44...
^Z
it can't connect to the syndic node from the minion. but when i switch the role syndic to master only,it can success manage the minion node , it is so wired. how can i solve this problem.

**Comment by whytewolf** [comment]
Thank you for the ticket. 

I need some more information. can i get the output of `ps -ef | grep salt` on all servers involved.
as well as `ss -lpnt` on all masters involved. 

and then the following files from any of the masters/syndics involved. please parse down so you are not leaking secrets.

* /etc/salt/master, and /etc/salt/master.d We only need the syndic part of the configs and which server they are on.
* /var/log/salt/master, this will be the log file. there might be some details about what is happening here.

**Comment by dwoz** [comment]
This may be related to or a similar issue as #66237 which was fixed in 3007.x

**Comment by markschuh** [comment]
I have tested a related syndic setup with this version 3006.1 and it is working fine here:

* Setup
```
host1:  h_syndicmain
  services: 
    - salt-master

host2: h_chef
  services:
    - salt-syndic
    - salt-master

host3: h_minion
  service:
    - salt-minion
```

* Connectivity diagram
```
"salt-minion on h_minion"   
       ---(connects_to)--->  "salt-master on h_chef"
                             "salt-syndic on h_chef"
                                  ---(connects_to)--->  "salt-master on h_syndicmain"
```

* Check
Syndic successfully verified with salt command run on `h_syndicmain` :
```
[root@h_syndicmain /]# salt '*' test.ping
h_minion:
    True
```
This forwards - via the syndic - the "test.ping" to `h_chef`, which sends the command to its own minions (just: `h_minion`) and returns the result back to `h_syndicmain`


* Configuration

Configuration of `salt-master` running on host `h_syndicmain`:
```
/etc/salt/master:
id: h_syndicmain
order_masters: True
```

Configuration of `salt-syndic` running on host `h_chef`:
```
/etc/salt/master:
syndic_master: h_syndicmain
```

Configuration of `salt-minion` running on host `h_minion`:
```
/etc/salt/minion:
id: h_minion
master: h_chef
```


* Salt version

all three hosts with same salt version:

```
Salt Version:
          Salt: 3006.1

Python Version:
        Python: 3.10.11 (main, May  5 2023, 02:31:54) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 5.4.1
         PyZMQ: 23.2.0
        relenv: 0.12.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: centos 7.9.2009 Core
        locale: utf-8
       machine: x86_64
       release: 5.15.153.1-microsoft-standard-WSL2
        system: Linux
       version: CentOS Linux 7.9.2009 Core
```

Note: This is a docker container based on image "centos:centos7", running in WSL

**Comment by dwoz** [comment]
@Erickhawk Since there was no more debug output provided and we have a report of syndic working in 3006.1 I'm going to close this.
