### ISSUE TITLE
salt-master run as non-root report Authentication failure of type "eauth" occurred in 3005.1

### ISSUE THREAD

**Issue by tianjingle** [saltstack/salt#65107]
I added` saltapi `to the system and started the salt-master and salt-api processes , using the` salt-api `user. However, when calling salt-api with curl, it was found that the salt master encountered an `Authentication failure of type "eauth" occurred exception.`

I have read other posts and found that there i[s currently no solution for this on](https://github.com/saltstack/salt/issues/7762)e. So I'm wondering if I'm using it incorrectly, or if salt master cannot be started as an unprivileged user?

Additionally, I have also modified the permissions for `/etc/shadow`, but it has no effect

**Comment by OrangeDog** [comment]
Duplicates #64275
