### ISSUE TITLE
[BUG] Windows 10 minion failing to connect to master

### ISSUE THREAD

**Issue by agriev** [saltstack/salt#65105]
**Description**
Freshly installed form NullSoftPackage windows minion log:

```
[DEBUG   ] Connecting minion's long-running req channel
[DEBUG   ] Re-using AsyncAuth for ('C:\\ProgramData\\Salt Project\\Salt\\conf\\pki\\minion', 'Windows3', 'tcp://10.22.22.4:4506')
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Decrypting the current master AES key
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] salt.crypt.verify_signature: Loading public key
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] salt.crypt.verify_signature: Verifying signature
[DEBUG   ] Closing AsyncReqChannel instance
[ERROR   ] Exception getting pillar:
Traceback (most recent call last):
  File "C:\Salt\lib\site-packages\salt\pillar\__init__.py", line 262, in compile_pillar
    ret_pillar = yield self.channel.crypted_transfer_decode_dictentry(
  File "C:\Salt\lib\site-packages\salt\ext\tornado\gen.py", line 1056, in run
    value = future.result()
  File "C:\Salt\lib\site-packages\salt\ext\tornado\concurrent.py", line 249, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 4, in raise_exc_info
  File "C:\Salt\lib\site-packages\salt\ext\tornado\gen.py", line 1070, in run
    yielded = self.gen.send(value)
  File "C:\Salt\lib\site-packages\salt\channel\client.py", line 187, in crypted_transfer_decode_dictentry
    aes = cipher.decrypt(ret["key"])
TypeError: string indices must be integers
[ERROR   ] Error while bringing up minion for multi-master. Is master at 10.22.22.4 responding?
```

Master log:

```
alcalli-tmp-install-master-1  | 21:43:00 master.1 | ValueError: not enough values to unpack (expected 2, got 0)
alcalli-tmp-install-master-1  | 21:43:01 master.1 | [ERROR   ] Received malformed command {}
alcalli-tmp-install-master-1  | 21:43:01 master.1 | [ERROR   ] Some exception handling a payload from minion
alcalli-tmp-install-master-1  | 21:43:01 master.1 | Traceback (most recent call last):
alcalli-tmp-install-master-1  | 21:43:01 master.1 |   File "/opt/saltstack/salt/lib/python3.10/site-packages/salt/channel/server.py", line 163, in handle_message
alcalli-tmp-install-master-1  | 21:43:01 master.1 |     ret, req_opts = yield self.payload_handler(payload)
alcalli-tmp-install-master-1  | 21:43:01 master.1 | ValueError: not enough values to unpack (expected 2, got 0)
```

**Setup**
https://github.com/agriev/alcali - dockerfiles and etc

```
salt --version
salt 3006.2
```

Please be as specific as possible and give set-up details.

- [x ] on-prem machine with Salt-Master in Docker
- [x ] VM (Virtualbox, KVM, etc. please specify) - Parallels Windows 10 running on arm64 Mac OS
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ x] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
Just install windows minion on a win10 machine from https://repo.saltproject.io/salt/py3/windows/latest/Salt-Minion-3006.2-Py3-AMD64-Setup.exe

**Expected behavior**
Minion is connecting to master as all of the debian minions already connecting

**Screenshots**
no screens

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
salt --versions-report
Salt Version:
          Salt: 3006.2

Python Version:
        Python: 3.10.12 (main, Aug  3 2023, 21:47:10) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: 2.6.1
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: debian 11 bullseye
        locale: utf-8
       machine: x86_64
       release: 5.10.0-25-amd64
        system: Linux
       version: Debian GNU/Linux 11 bullseye
```
</details>

**Additional context**
WIll provide any necessary info and can fix something myself if pointed out where to look for.

**Comment by twangboy** [comment]
How is your multi-master set up? Would you mind posting your minion and master config? Could you also post the version report for the minion?

**Comment by agriev** [comment]
there is single master setup, single master only.

.\salt-minion.exe --versions-report
Salt Version:
          Salt: 3006.2

Python Version:
        Python: 3.10.12 (heads/main:7eea318, Aug  3 2023, 21:56:22) [MSC v.1935 64 bit (AMD64)]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: 4.0.7
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.10.1
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 25.0.2
        relenv: 0.13.3
         smmap: 4.0.0
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist:
        locale: cp1251
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.22000 SP0 Multiprocessor Free


[master.txt](https://github.com/saltstack/salt/files/12528519/master.txt) - master config (changed it to txt to attach)

Minion config has only uncommented:

master: 10.22.22.4
id: Windows3


full master configuration pillars and etc could be found in [My alcali fork](https://github.com/agriev/alcali/tree/develop/docker/saltconfig)

**Comment by agriev** [comment]
@twangboy do you need any additional info. I'm up for assistance. also - if you'll need i can provide you with direct access to the installation. it's not in production yet

**Comment by agriev** [comment]
@whytewolf 
it installed in c:/Salt directory, but for some reason it creates c:\ProgramData\Salt Project\Salt\vat and conf directories and stores confs there

**Comment by twangboy** [comment]
Was this an upgrade from an older version of Salt? As of 3004, installation files should be in `C:\Program Files\Salt Project\Salt` and config should be in `C:\ProgramData\Salt Project\Salt`. If you have config in both `C:\salt` and `C:\ProgramData\Salt Project\Salt` then we need to see which config the service is trying to use. There should be a binary named `ssm.exe` in the installation directory `(C:\Program Files\Salt Project\Salt`). Run `ssm.exe edit salt-minion` to see what command is being run to start salt. Look in `Arguments:`

![image](https://github.com/saltstack/salt/assets/9383935/a62cc7e4-72f6-4c1e-b040-28149b13131d)

It should contain the default `-c "C:\ProgramData\Salt Project\Salt\conf"`

So, we can stop the `salt-minion` service and run minion from the CLI with debug to see what's going on:

```
salt-minion -l debug -c "C:\ProgramData\Salt Project\Salt\conf"
```

The debug should give a clue as to why the minion is not connecting. It may be the same as the log originally posted though... but this way we know what config is being used.

**Comment by aldkfjasdfasdf** [comment]
**My problem**
Running the minion triggers endless attempts at this one:
```
[DEBUG   ] Connecting to master. Attempt 9 (infinite attempts)
[DEBUG   ] Master URI: tcp://192.162.0.5:8080
[DEBUG   ] Re-using AsyncAuth for ('C:\\ProgramData\\Salt Project\\Salt\\conf\\pki\\minion', 'Win', 'tcp://192.162.0.5:8080')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (4541)
[DEBUG   ] Setting zmq_reconnect_ivl to '4541ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncReqChannel instance

[DEBUG   ] Connecting to master. Attempt 10 (infinite attempts)
[DEBUG   ] Master URI: tcp://192.162.0.5:8080
[DEBUG   ] Re-using AsyncAuth for ('C:\\ProgramData\\Salt Project\\Salt\\conf\\pki\\minion', 'Win', 'tcp://192.162.0.5:8080')
[DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5028)
[DEBUG   ] Setting zmq_reconnect_ivl to '5028ms'
[DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
[DEBUG   ] salt.crypt.get_rsa_key: Loading private key
[DEBUG   ] Loaded minion key: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem
[DEBUG   ] SaltEvent PUB socket URI: 4510
[DEBUG   ] SaltEvent PULL socket URI: 4511
[DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
[DEBUG   ] Closing AsyncReqChannel instance
```
minion config
```
id: Win
master: 192.162.0.5
master_port: 8080

log_level: debug
log_level_logfile: debug

```

**Comment by sanderc85** [comment]
> **My problem** Running the minion triggers endless attempts at this one:
> 
> ```
> [DEBUG   ] Connecting to master. Attempt 9 (infinite attempts)
> [DEBUG   ] Master URI: tcp://192.162.0.5:8080
> [DEBUG   ] Re-using AsyncAuth for ('C:\\ProgramData\\Salt Project\\Salt\\conf\\pki\\minion', 'Win', 'tcp://192.162.0.5:8080')
> [DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (4541)
> [DEBUG   ] Setting zmq_reconnect_ivl to '4541ms'
> [DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
> [DEBUG   ] salt.crypt.get_rsa_key: Loading private key
> [DEBUG   ] Loaded minion key: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem
> [DEBUG   ] SaltEvent PUB socket URI: 4510
> [DEBUG   ] SaltEvent PULL socket URI: 4511
> [DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
> [DEBUG   ] Closing AsyncReqChannel instance
> 
> [DEBUG   ] Connecting to master. Attempt 10 (infinite attempts)
> [DEBUG   ] Master URI: tcp://192.162.0.5:8080
> [DEBUG   ] Re-using AsyncAuth for ('C:\\ProgramData\\Salt Project\\Salt\\conf\\pki\\minion', 'Win', 'tcp://192.162.0.5:8080')
> [DEBUG   ] Generated random reconnect delay between '1000ms' and '11000ms' (5028)
> [DEBUG   ] Setting zmq_reconnect_ivl to '5028ms'
> [DEBUG   ] Setting zmq_reconnect_ivl_max to '11000ms'
> [DEBUG   ] salt.crypt.get_rsa_key: Loading private key
> [DEBUG   ] Loaded minion key: C:\ProgramData\Salt Project\Salt\conf\pki\minion\minion.pem
> [DEBUG   ] SaltEvent PUB socket URI: 4510
> [DEBUG   ] SaltEvent PULL socket URI: 4511
> [DEBUG   ] salt.crypt.get_rsa_pub_key: Loading public key
> [DEBUG   ] Closing AsyncReqChannel instance
> ```
> 
> minion config
> 
> ```
> id: Win
> master: 192.162.0.5
> master_port: 8080
> 
> log_level: debug
> log_level_logfile: debug
> ```

Don't set `master_port` to `8080` in de Salt minion config if the Salt master publisher port is not set to TCP port `8080`.

**Comment by twangboy** [comment]
You might also try removing the minion key from the master (`salt-key -d <minion id>`) and then deleting the pki directory on the minion (`C:\ProgramData\Salt Project\Salt\conf\pki`). I would also remove the `C:\salt` directory just to make sure you're getting everything from the right location.

**Comment by twangboy** [comment]
Were you able to get this working?

**Comment by twangboy** [comment]
I asked about multi-master because of the list line in your error text:
```
[ERROR   ] Error while bringing up minion for multi-master. Is master at 10.22.22.4 responding?
```

**Comment by twangboy** [comment]
Closing due to lack of response
