### ISSUE TITLE
[BUG] Occasional failure with SMBProtocol error when using salt-cloud saltify driver for windows.

### ISSUE THREAD

**Issue by cheburakshu** [saltstack/salt#65148]
1. Description:
   - When the customer deploys vms from vra and tries to deploy a salt-minion they sometimes get an error in _check_worker_running\n raise SMBConnectionClosed('SMB socket was closed, can not send or receive any more data') see 8:25 in recording for the full message

2. Setup:
   - The video has the full definition of the customer's blueprint but basically, they are deploying multiple vms in a vRA blueprint and sometimes they get this SMB error

3. Steps to Reproduce the behavior:
   - I am not sure if this is something specific to the customer environment but it sounds like to me that for some reason the SMB connection is getting closed not sure if it is by the server or the client. I can get the blueprint if that would be helpfull

4. Expected behavior:
   - The deployment should not fail and we should be able to get the minion to deploy successfully when making the request

5. Versions Report:
   - Salt Version:
Salt: 3005.1

Dependency Versions:
cffi: 1.15.1
cherrypy: Not Installed
dateutil: Not Installed
docker-py: Not Installed
gitdb: 4.0.10
gitpython: 3.1.29
Jinja2: 3.0.3
libgit2: 1.5.0
M2Crypto: Not Installed
Mako: Not Installed
msgpack: 0.5.6
msgpack-pure: Not Installed
mysql-python: Not Installed
pycparser: 2.21
pycrypto: 2.6.1
pycryptodome: 3.9.8
pygit2: 1.10.1
Python: 3.7.5 (default, Mar 22 2023, 17:31:55)
python-gnupg: Not Installed
PyYAML: 5.4.1
PyZMQ: 19.0.2
smmap: 5.0.0
timelib: Not Installed
Tornado: 4.5.3
ZMQ: 4.3.4

System Versions:
dist: photon 3.0 Photon
locale: utf-8
machine: x86_64
release: 4.19.277-3.ph3
system: Linux
version: VMware Photon OS 3.0 Photon

cryptography/hazmat/bindings/openssl/binding.py:173: CryptographyDeprecationWarning: OpenSSL version 1.0.2 is no longer supported by the OpenSSL project, please upgrade. The next version of cryptography will drop support for it.
warnings.warn(
RaaS:
build_date: 2023-04-27T15:32:11
build_version: 8.12.1.3
fips: False
raas: 8.12.1

Python: 3.9.15 (main, Mar 7 2023, 18:23:45)

Dependency Versions:
PyYAML: 6.0
SQLAlchemy: 1.3.24
alembic: 1.10.3
amqp: 5.1.1
asyncio: 3.4.3
asyncpg: 0.25.0
boto3: 1.26.114
celery: 5.2.7
certifi: 2022.12.07
croniter: 1.0.15
dateutil: 2.8.2
istr: Not Installed
jinja2: 3.1.2
json-delta: 2.0.2
jsonschema: 4.17.3
ldap3: 2.9.1
ldap3-binary: 2.9.1
libnacl: 1.8.0
mako: 1.2.4
marshmallow: 2.21.0
marshmallow-jsonschema: 0.10.0
msgpack: 1.0.2
pop: Not Installed
psutil: 5.8.0
psycopg2: 2.9.6 (dt dec pq3 ext lo64)
psycopg2-binary: 2.9.6 (dt dec pq3 ext lo64)
pyasn1: 0.4.8
pyasn1-binary: 0.4.8
python-editor: 1.0.4
pytz: 2021.3
raven: 6.10.0
redis: 4.5.4
salt: 3004.2
setproctitle: 1.1.10
six: 1.16.0
tblib: 1.7.0
tornado: 6.0.4

Operating System:
machine: x86_64
release: 4.19.277-3.ph3
sysname: Linux
version: #1-photon SMP Fri Apr 7 19:35:24 UTC 2023

Please see VRAE-53352 for additional context. Please see if it is possible re-try the connection. Thanks.

**Comment by twangboy** [comment]
The system is in the process of rebooting when Salt-Cloud attempts to install Salt.
