### ISSUE TITLE
[BUG] Install requirements no longer installing with new setuptools

### ISSUE THREAD

**Issue by dwoz** [saltstack/salt#65149]
**Description**

Pip install no longer installs our requirements. This seems to have broken with the new `setuptools==68.2.0`

Users looking to install salt via pip will need to add the `--no-build-isolation` and `--no-cache` flags to their pip install command.  Also, please ensure that `setuptools<68.2.0` is installed into your current environment, as installing salt will no leverage that setuptools version.

For example, `pip install salt --no-build-isolation --no-cache`.

**Comment by dwoz** [comment]
Upstream issue pypa/setuptools#4042

**Comment by ScriptAutomate** [comment]
This may be the cause of the current salt-cloud test failures, since it does a pip install of salt to work off of
