### ISSUE TITLE
[BUG] Add --nodigest and --nosignature flags to rpm call in yumpkg module

### ISSUE THREAD

**Issue by bdrx312** [saltstack/salt#65152]
**Is your feature request related to a problem? Please describe.**

`yumpkg` `list_pkgs` makes a subprocess command call to `rpm -qa` to list the packages (https://github.com/saltstack/salt/blob/caa5e39303aa8cffc6ea5b191249c6ec7fe0282e/salt/modules/yumpkg.py#L747-L752). `rpm -qa` does digest and signature checking by default. list_pkgs is does not need to verify checksums and signatures and therefore can reduce the time to list the packages by disabling the digest and signature checking with the `--nodigest` and `--nosignature` flags.

**Describe the solution you'd like**
Add the `--nodigest` and `--nosignature` to the `cmd` variable that is passed to `cmd.run` in the `list_pkgs` function of salt/modules/yumpkg.py

**Additional context**

Here are a couple of example timings of `rpm -qa` before and adding the flags on my rhel 8 ec2 instance:

```
$ free && sync && echo 3 > /proc/sys/vm/drop_caches && free
$ time rpm -qa > /dev/null

real: 0m2.944s
user: 0m1.689s
sys:  0m0.163s
$ time rpm -qa > /dev/null

real: 0m1.740s
user: 0m1.644s
sys:  0m0.079s
$ free && sync && echo 3 > /proc/sys/vm/drop_caches && free
$ time rpm -qa --nodigest --nosignature > /dev/null

real: 0m1.319s
user: 0m0.259s
sys:  0m0.147s
$ time rpm -qa --nodigest --nosignature > /dev/null

real: 0m0.366s
user: 0m0.235s
sys:  0m0.099s
```

**Comment by whytewolf** [comment]
@bdrx312 I know you were working on a PR were you able to get that started?

**Comment by bdrx312** [comment]
> @bdrx312 I know you were working on a PR were you able to get that started?

No I have been busy and haven't had time to figure out how to setup a saltstack development environment on Windows with vagrant yet. I created a fork and committed the change. If someone wants take the changes and pick up from there they can see it here https://github.com/bdrx312/salt. I am not sure when I will have time.

**Comment by whytewolf** [comment]
moving this to bug as the speed up is enough that this could be considered a bug in speed.

**Comment by Ch3LL** [comment]
Closed by https://github.com/saltstack/salt/pull/65172
