### ISSUE TITLE
[BUG] Upgrade error taking 3006.2 to 3006.3, salt-common_3006.3_amd64.deb, Ubuntu 20.04

### ISSUE THREAD

**Issue by sbconslt** [saltstack/salt#65170]
**Description**

When attempting to upgrade our Ubuntu 20.04 salt-master server from 3006.2 to 3006.3, salt-common package fails with an error during pre-installation script.

**Setup**

- Google Cloud Platform compute engine VM instance, Ubuntu 20.04
- onedir packaging
- apt package manager for install/upgrade, /etc/apt/sources.list.d/salt.list contains:
```
deb [signed-by=/etc/apt/keyrings/salt-archive-keyring.gpg arch=amd64] https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal main
```

**Steps to Reproduce the behavior**

- Initially be on salt-master 3006.2 with everything working normally
- Update salt.list to pick the 3006.3 minor version, as above
- apt-get update && apt-get upgrade
- Get this error:
```
Preparing to unpack .../salt-master_3006.3_amd64.deb ...
Unpacking salt-master (3006.3) over (3006.2) ...
Preparing to unpack .../salt-common_3006.3_amd64.deb ...
usermod: user salt is currently used by process 540
dpkg: error processing archive /var/cache/apt/archives/salt-common_3006.3_amd64.deb (--unpack):
 new salt-common package pre-installation script subprocess returned error exit status 8
Errors were encountered while processing:
 /var/cache/apt/archives/salt-common_3006.3_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Expected behavior**

salt-common and salt-master packages to be upgraded successfully to 3006.3. Instead, salt-master package succeeds, but salt-common package fails. Manually removing both packages and going back to 3006.2 is effective to restore the prior state. However, this blocks from upgrading to 3006.3.

**Versions Report**

In the initial state, on working 3006.2:

```
Salt Version:
          Salt: 3006.2

Python Version:
        Python: 3.10.12 (main, Aug  3 2023, 21:47:10) [GCC 11.2.0]

Dependency Versions:
          cffi: 1.14.6
      cherrypy: unknown
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.3
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4

System Versions:
          dist: ubuntu 20.04.5 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1041-gcp
        system: Linux
       version: Ubuntu 20.04.5 focal

```

Please advise. Thank you.

**Comment by dmurphy18** [comment]
@sbconslt Unable to reproduce this issue using VirtualBox and Ubuntu 20.04, here is the upgrade log

**Upgrade log**
<details><summary>log upgrading 3006.2 to 3006.3</summary>
30 packages can be upgraded. Run 'apt list --upgradable' to see them.
root@david-VirtualBox:/home/david# apt-cache policy salt-master
salt-master:
  Installed: 3006.2
  Candidate: 3006.3
  Version table:
     3006.3 500
        500 https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal/main amd64 Packages
 *** 3006.2 100
        100 /var/lib/dpkg/status
root@david-VirtualBox:/home/david# apt-cache policy salt-common
salt-common:
  Installed: 3006.2
  Candidate: 3006.3
  Version table:
     3006.3 500
        500 https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal/main amd64 Packages
 *** 3006.2 100
        100 /var/lib/dpkg/status
root@david-VirtualBox:/home/david# apt-get update
Hit:1 http://us.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease   
Hit:3 https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal InRelease
Get:4 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Fetched 222 kB in 1s (224 kB/s)                                     
Reading package lists... Done
root@david-VirtualBox:/home/david# ps -ef | grep salt
salt        6017       1  2 16:18 ?        00:00:03 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master MainProcess
salt        6058    6017  0 16:18 ?        00:00:00 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master PubServerChannel._publish_daemon
salt        6059    6017  0 16:18 ?        00:00:00 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master EventPublisher
salt        6062    6017  0 16:18 ?        00:00:01 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master Maintenance
salt        6063    6017  0 16:18 ?        00:00:00 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer ReqServer_ProcessManager
salt        6064    6063  0 16:18 ?        00:00:00 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorkerQueue
salt        6065    6063  1 16:18 ?        00:00:02 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-0
salt        6066    6063  1 16:18 ?        00:00:02 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-1
salt        6067    6063  1 16:18 ?        00:00:02 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-2
salt        6068    6063  1 16:18 ?        00:00:02 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-3
salt        6069    6063  1 16:18 ?        00:00:02 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master ReqServer MWorker-4
salt        6076    6017  0 16:18 ?        00:00:00 /opt/saltstack/salt/bin/python3.10 /usr/bin/salt-master FileServerUpdate
root        7477    2783  0 16:21 pts/1    00:00:00 grep --color=auto salt
root@david-VirtualBox:/home/david# apt-get upgrade 2>&1 | tee ~/myupgrade.log
Reading package lists...
Building dependency tree...
Reading state information...
Calculating upgrade...
The following packages have been kept back:
  linux-generic-hwe-20.04 linux-headers-generic-hwe-20.04
  linux-image-generic-hwe-20.04
The following packages will be upgraded:
  amd64-microcode distro-info firefox firefox-locale-en libdw1 libelf1
  libgpgme11 libgpgmepp6 libsmbclient libsnmp-base libsnmp35 libwbclient0
  linux-libc-dev python3-debian python3-distro-info
  python3-software-properties salt-common salt-master samba-libs
  software-properties-common software-properties-gtk thunderbird
  thunderbird-gnome-support thunderbird-locale-en thunderbird-locale-en-us
  ubuntu-advantage-tools ufw
27 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
Need to get 172 MB of archives.
After this operation, 402 kB disk space will be freed.
Do you want to continue? [Y/n] 
Get:1 https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal/main amd64 salt-master amd64 3006.3 [93.0 kB]
Get:2 https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal/main amd64 salt-common amd64 3006.3 [42.6 MB]
Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libsmbclient amd64 2:4.15.13+dfsg-0ubuntu0.20.04.5 [59.6 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libwbclient0 amd64 2:4.15.13+dfsg-0ubuntu0.20.04.5 [211 kB]
Get:5 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 samba-libs amd64 2:4.15.13+dfsg-0ubuntu0.20.04.5 [5,631 kB]
Get:6 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libdw1 amd64 0.176-1.1ubuntu0.1 [226 kB]
Get:7 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libelf1 amd64 0.176-1.1ubuntu0.1 [44.2 kB]
Get:8 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 distro-info amd64 0.23ubuntu1.1 [17.1 kB]
Get:9 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 ubuntu-advantage-tools amd64 28.1~20.04 [179 kB]
Get:10 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-distro-info all 0.23ubuntu1.1 [5,944 B]
Get:11 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 ufw all 0.36-6ubuntu1.1 [148 kB]
Get:12 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 firefox amd64 117.0+build2-0ubuntu0.20.04.1 [60.9 MB]
Get:13 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 firefox-locale-en amd64 117.0+build2-0ubuntu0.20.04.1 [718 kB]
Get:14 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libgpgme11 amd64 1.13.1-7ubuntu2.1 [121 kB]
Get:15 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libgpgmepp6 amd64 1.13.1-7ubuntu2.1 [101 kB]
Get:16 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libsnmp-base all 5.8+dfsg-2ubuntu2.9 [205 kB]
Get:17 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 libsnmp35 amd64 5.8+dfsg-2ubuntu2.9 [978 kB]
Get:18 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 linux-libc-dev amd64 5.4.0-162.179 [1,115 kB]
Get:19 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-debian all 0.1.36ubuntu1.1 [64.9 kB]
Get:20 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 software-properties-common all 0.99.9.12 [10.4 kB]
Get:21 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 software-properties-gtk all 0.99.9.12 [69.1 kB]
Get:22 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 python3-software-properties all 0.99.9.12 [21.7 kB]
Get:23 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 thunderbird-locale-en amd64 1:102.15.0+build1-0ubuntu0.20.04.1 [957 kB]
Get:24 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 thunderbird amd64 1:102.15.0+build1-0ubuntu0.20.04.1 [57.8 MB]
Get:25 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 thunderbird-gnome-support amd64 1:102.15.0+build1-0ubuntu0.20.04.1 [8,640 B]
Get:26 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 thunderbird-locale-en-us all 1:102.15.0+build1-0ubuntu0.20.04.1 [8,984 B]
Get:27 http://us.archive.ubuntu.com/ubuntu focal-updates/main amd64 amd64-microcode amd64 3.20191218.1ubuntu1.2 [68.6 kB]
Preconfiguring packages ...
Fetched 172 MB in 35s (4,867 kB/s)
(Reading database ... 197742 files and directories currently installed.)
Preparing to unpack .../00-libsmbclient_2%3a4.15.13+dfsg-0ubuntu0.20.04.5_amd64.deb ...
Unpacking libsmbclient:amd64 (2:4.15.13+dfsg-0ubuntu0.20.04.5) over (2:4.15.13+dfsg-0ubuntu0.20.04.3) ...
Preparing to unpack .../01-libwbclient0_2%3a4.15.13+dfsg-0ubuntu0.20.04.5_amd64.deb ...
Unpacking libwbclient0:amd64 (2:4.15.13+dfsg-0ubuntu0.20.04.5) over (2:4.15.13+dfsg-0ubuntu0.20.04.3) ...
Preparing to unpack .../02-samba-libs_2%3a4.15.13+dfsg-0ubuntu0.20.04.5_amd64.deb ...
Unpacking samba-libs:amd64 (2:4.15.13+dfsg-0ubuntu0.20.04.5) over (2:4.15.13+dfsg-0ubuntu0.20.04.3) ...
Preparing to unpack .../03-libdw1_0.176-1.1ubuntu0.1_amd64.deb ...
Unpacking libdw1:amd64 (0.176-1.1ubuntu0.1) over (0.176-1.1build1) ...
Preparing to unpack .../04-libelf1_0.176-1.1ubuntu0.1_amd64.deb ...
Unpacking libelf1:amd64 (0.176-1.1ubuntu0.1) over (0.176-1.1build1) ...
Preparing to unpack .../05-distro-info_0.23ubuntu1.1_amd64.deb ...
Unpacking distro-info (0.23ubuntu1.1) over (0.23ubuntu1) ...
Preparing to unpack .../06-ubuntu-advantage-tools_28.1~20.04_amd64.deb ...
Unpacking ubuntu-advantage-tools (28.1~20.04) over (27.14.4~20.04) ...
Preparing to unpack .../07-python3-distro-info_0.23ubuntu1.1_all.deb ...
Unpacking python3-distro-info (0.23ubuntu1.1) over (0.23ubuntu1) ...
Preparing to unpack .../08-ufw_0.36-6ubuntu1.1_all.deb ...
Unpacking ufw (0.36-6ubuntu1.1) over (0.36-6ubuntu1) ...
Preparing to unpack .../09-firefox_117.0+build2-0ubuntu0.20.04.1_amd64.deb ...
Unpacking firefox (117.0+build2-0ubuntu0.20.04.1) over (116.0.3+build2-0ubuntu0.20.04.1) ...
Preparing to unpack .../10-firefox-locale-en_117.0+build2-0ubuntu0.20.04.1_amd64.deb ...
Unpacking firefox-locale-en (117.0+build2-0ubuntu0.20.04.1) over (116.0.3+build2-0ubuntu0.20.04.1) ...
Preparing to unpack .../11-libgpgme11_1.13.1-7ubuntu2.1_amd64.deb ...
Unpacking libgpgme11:amd64 (1.13.1-7ubuntu2.1) over (1.13.1-7ubuntu2) ...
Preparing to unpack .../12-libgpgmepp6_1.13.1-7ubuntu2.1_amd64.deb ...
Unpacking libgpgmepp6:amd64 (1.13.1-7ubuntu2.1) over (1.13.1-7ubuntu2) ...
Preparing to unpack .../13-libsnmp-base_5.8+dfsg-2ubuntu2.9_all.deb ...
Unpacking libsnmp-base (5.8+dfsg-2ubuntu2.9) over (5.8+dfsg-2ubuntu2.7) ...
Preparing to unpack .../14-libsnmp35_5.8+dfsg-2ubuntu2.9_amd64.deb ...
Unpacking libsnmp35:amd64 (5.8+dfsg-2ubuntu2.9) over (5.8+dfsg-2ubuntu2.7) ...
Preparing to unpack .../15-linux-libc-dev_5.4.0-162.179_amd64.deb ...
Unpacking linux-libc-dev:amd64 (5.4.0-162.179) over (5.4.0-159.176) ...
Preparing to unpack .../16-python3-debian_0.1.36ubuntu1.1_all.deb ...
Unpacking python3-debian (0.1.36ubuntu1.1) over (0.1.36ubuntu1) ...
Preparing to unpack .../17-software-properties-common_0.99.9.12_all.deb ...
Unpacking software-properties-common (0.99.9.12) over (0.99.9.11) ...
Preparing to unpack .../18-software-properties-gtk_0.99.9.12_all.deb ...
Unpacking software-properties-gtk (0.99.9.12) over (0.99.9.11) ...
Preparing to unpack .../19-python3-software-properties_0.99.9.12_all.deb ...
Unpacking python3-software-properties (0.99.9.12) over (0.99.9.11) ...
Preparing to unpack .../20-salt-master_3006.3_amd64.deb ...
Unpacking salt-master (3006.3) over (3006.2) ...
Preparing to unpack .../21-salt-common_3006.3_amd64.deb ...
Unpacking salt-common (3006.3) over (3006.2) ...
Preparing to unpack .../22-thunderbird-locale-en_1%3a102.15.0+build1-0ubuntu0.20.04.1_amd64.deb ...
Unpacking thunderbird-locale-en (1:102.15.0+build1-0ubuntu0.20.04.1) over (1:102.13.0+build1-0ubuntu0.20.04.1) ...
Preparing to unpack .../23-thunderbird_1%3a102.15.0+build1-0ubuntu0.20.04.1_amd64.deb ...
Unpacking thunderbird (1:102.15.0+build1-0ubuntu0.20.04.1) over (1:102.13.0+build1-0ubuntu0.20.04.1) ...
Preparing to unpack .../24-thunderbird-gnome-support_1%3a102.15.0+build1-0ubuntu0.20.04.1_amd64.deb ...
Unpacking thunderbird-gnome-support (1:102.15.0+build1-0ubuntu0.20.04.1) over (1:102.13.0+build1-0ubuntu0.20.04.1) ...
Preparing to unpack .../25-thunderbird-locale-en-us_1%3a102.15.0+build1-0ubuntu0.20.04.1_all.deb ...
Unpacking thunderbird-locale-en-us (1:102.15.0+build1-0ubuntu0.20.04.1) over (1:102.13.0+build1-0ubuntu0.20.04.1) ...
Preparing to unpack .../26-amd64-microcode_3.20191218.1ubuntu1.2_amd64.deb ...
Unpacking amd64-microcode (3.20191218.1ubuntu1.2) over (3.20191218.1ubuntu1.1) ...
Setting up distro-info (0.23ubuntu1.1) ...
Setting up firefox (117.0+build2-0ubuntu0.20.04.1) ...
Please restart all running instances of firefox, or you will experience problems.
Setting up libsnmp-base (5.8+dfsg-2ubuntu2.9) ...
Setting up linux-libc-dev:amd64 (5.4.0-162.179) ...
Setting up ufw (0.36-6ubuntu1.1) ...
Setting up amd64-microcode (3.20191218.1ubuntu1.2) ...
update-initramfs: deferring update (trigger activated)
amd64-microcode: microcode will be updated at next boot
Setting up libgpgme11:amd64 (1.13.1-7ubuntu2.1) ...
Setting up libwbclient0:amd64 (2:4.15.13+dfsg-0ubuntu0.20.04.5) ...
Setting up salt-common (3006.3) ...
Setting up python3-software-properties (0.99.9.12) ...
Setting up firefox-locale-en (117.0+build2-0ubuntu0.20.04.1) ...
Setting up python3-debian (0.1.36ubuntu1.1) ...
Setting up thunderbird (1:102.15.0+build1-0ubuntu0.20.04.1) ...
Setting up ubuntu-advantage-tools (28.1~20.04) ...
Setting up libelf1:amd64 (0.176-1.1ubuntu0.1) ...
Setting up python3-distro-info (0.23ubuntu1.1) ...
Setting up libdw1:amd64 (0.176-1.1ubuntu0.1) ...
Setting up libsnmp35:amd64 (5.8+dfsg-2ubuntu2.9) ...
Setting up libgpgmepp6:amd64 (1.13.1-7ubuntu2.1) ...
Setting up samba-libs:amd64 (2:4.15.13+dfsg-0ubuntu0.20.04.5) ...
Setting up thunderbird-locale-en (1:102.15.0+build1-0ubuntu0.20.04.1) ...
Setting up software-properties-common (0.99.9.12) ...
Setting up salt-master (3006.3) ...
/usr/bin/systemctl
Synchronizing state of salt-master.service with SysV service script with /lib/systemd/systemd-sysv-install.
Executing: /lib/systemd/systemd-sysv-install enable salt-master
Setting up thunderbird-locale-en-us (1:102.15.0+build1-0ubuntu0.20.04.1) ...
Setting up thunderbird-gnome-support (1:102.15.0+build1-0ubuntu0.20.04.1) ...
Setting up libsmbclient:amd64 (2:4.15.13+dfsg-0ubuntu0.20.04.5) ...
Setting up software-properties-gtk (0.99.9.12) ...
Processing triggers for systemd (245.4-4ubuntu3.22) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for dbus (1.12.16-2ubuntu2.3) ...
Processing triggers for shared-mime-info (1.15-1) ...
Processing triggers for desktop-file-utils (0.24-1ubuntu3) ...
Processing triggers for mime-support (3.64ubuntu1) ...
Processing triggers for hicolor-icon-theme (0.17-2) ...
Processing triggers for gnome-menus (3.36.0-1ubuntu1) ...
Processing triggers for libglib2.0-0:amd64 (2.64.6-1~ubuntu20.04.6) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
Processing triggers for rsyslog (8.2001.0-1ubuntu1.3) ...
Processing triggers for initramfs-tools (0.136ubuntu6.7) ...
update-initramfs: Generating /boot/initrd.img-5.15.0-82-generic
Processing triggers for ufw (0.36-6ubuntu1.1) ...
root@david-VirtualBox:/home/david# salt-run --versions-report
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04.6 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-82-generic
        system: Linux
       version: Ubuntu 20.04.6 focal
 
root@david-VirtualBox:/home/david# 
</details>

I tried the same on an AWS VM and encountered no issues
```
root@ip-172-31-26-16:/home/ubuntu# apt-cache policy salt-master
salt-master:
  Installed: 3006.2
  Candidate: 3006.3
  Version table:
     3006.3 500
        500 https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal/main amd64 Packages
 *** 3006.2 100
        100 /var/lib/dpkg/status
root@ip-172-31-26-16:/home/ubuntu# apt-cache policy salt-common
salt-common:
  Installed: 3006.2
  Candidate: 3006.3
  Version table:
     3006.3 500
        500 https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal/main amd64 Packages
 *** 3006.2 100
        100 /var/lib/dpkg/status
root@ip-172-31-26-16:/home/ubuntu# apt upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages will be upgraded:
  salt-common salt-master
2 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 42.7 MB of archives.
After this operation, 10.2 kB of additional disk space will be used.
Do you want to continue? [Y/n] 
Get:1 https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal/main amd64 salt-master amd64 3006.3 [93.0 kB]
Get:2 https://repo.saltproject.io/salt/py3/ubuntu/20.04/amd64/minor/3006.3 focal/main amd64 salt-common amd64 3006.3 [42.6 MB]
Fetched 42.7 MB in 1s (46.8 MB/s)      
(Reading database ... 97165 files and directories currently installed.)
Preparing to unpack .../salt-master_3006.3_amd64.deb ...
Unpacking salt-master (3006.3) over (3006.2) ...
Preparing to unpack .../salt-common_3006.3_amd64.deb ...
Unpacking salt-common (3006.3) over (3006.2) ...
Setting up salt-common (3006.3) ...
Setting up salt-master (3006.3) ...
/usr/bin/systemctl
Processing triggers for ufw (0.36-6ubuntu1.1) ...
Processing triggers for man-db (2.9.1-1) ...
Processing triggers for libc-bin (2.31-0ubuntu9.9) ...
root@ip-172-31-26-16:/home/ubuntu# salt-run --versions-report
Salt Version:
          Salt: 3006.3
 
Python Version:
        Python: 3.10.13 (main, Sep  6 2023, 02:11:27) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.14.6
      cherrypy: 18.6.1
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.2
       libgit2: Not Installed
  looseversion: 1.0.2
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 22.0
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.9.8
        pygit2: Not Installed
  python-gnupg: 0.4.8
        PyYAML: 6.0.1
         PyZMQ: 23.2.0
        relenv: 0.13.10
         smmap: Not Installed
       timelib: 0.2.4
       Tornado: 4.5.3
           ZMQ: 4.3.4
 
System Versions:
          dist: ubuntu 20.04.6 focal
        locale: utf-8
       machine: x86_64
       release: 5.15.0-1036-aws
        system: Linux
       version: Ubuntu 20.04.6 focal
 
root@ip-172-31-26-16:/home/ubuntu# 
```

Can you retry on another platform and/or retry on Google.
If there is any other information you can provide in reproducing the issue, please add it to this issue.

**Comment by sbconslt** [comment]
Thank you for the quick response. Let me try to get more verbose information out of apt and see if I can pinpoint what is throwing the nonzero exit code on my instance.

**Comment by sbconslt** [comment]
I was able to upgrade our salt-master by doing `apt-get remove salt-common salt-master`, letting the old packages removing, then updating the minor version in `salt.list`, then doing `apt-get install salt-common salt-master`.

This doesn't explain what through the error and caused an in-place `apt-get upgrade` to fail, but however unsatisfactory, it gets us to the current patch level so that's it.

Salt minions were never afflicted, the in-place `apt-get upgrade` from 3006.2 to 3006.3 works fine on them.

Apologies for not having produced better information but thanks again for the quick (non) repro.

**Comment by richard-irwin** [comment]
I have had the same error when trying to upgrade my salt-master. Ubuntu 22.04, trying to upgrade 3006.2 to 3006.3

**Comment by richard-irwin** [comment]
I found what is causing the issue. The preinst script is running usermod on the salt user, but the salt-api service is still running and so the script threw an error (usermod: user salt is currently used by process xxxx). If I stop the api-service (and I had already stopped the salt-master service as part of debugging) the install can go forward.

**Comment by dmurphy18** [comment]
@richard-irwin Can you open a new issue with the details on how to reproduce this issue, since expect this to affect all Debian/Ubuntu family.

Thanks for digging in.

**Comment by qiaouchicago** [comment]
> I found what is causing the issue. The preinst script is running usermod on the salt user, but the salt-api service is still running and so the script threw an error (usermod: user salt is currently used by process xxxx). If I stop the api-service (and I had already stopped the salt-master service as part of debugging) the install can go forward.

This worked for me.
