### ISSUE TITLE
[BUG] proxy minions not getting kwargs key-value from deltaproxy

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#65179]
**Description**
proxy minions not getting kwargs key-value when they are run from deltaproxy which results in a traceback stating that multiple positional arguments have been passed.

**Setup**
Configure proxy minions and deltaproxy minion.

**Steps to Reproduce the behavior**
Run a command that passes kwargs against multiple sub proxy minions.

**Expected behavior**
The command should succeed and return correctly.

**Versions Report**
3006.x and later

**Comment by network-shark** [comment]
Is this problem related to this #61315 ?

**Comment by Zpell82** [comment]
> Is this problem related to this #61315 ?

yes, and it should be solved now since 3006.5 the solution was merged in

**Comment by dwoz** [comment]
> > Is this problem related to this #61315 ?
> 
> yes, and it should be solved now since 3006.5 the solution was merged in

Closing this as it seems to be resolved.
