### ISSUE TITLE
[BUG] Source says "Not a typo.", but I'm pretty sure it's a typo

### ISSUE THREAD

**Issue by bendikro** [saltstack/salt#65295]
**Description**
On line 445 in [salt/modules/nftables.py](https://github.com/saltstack/salt/blob/76e50885b07621e9e4c16bc3f1ebc16c93983b90/salt/modules/nftables.py#L445) we find:
```
    # Not a typo. Invert the dictionary twice to get unique values only.
    nft_families = {v: k for k, v in _NFTABLES_FAMILIES.items()}
    nft_families = {v: k for k, v in _NFTABLES_FAMILIES.items()}
```

How do these two identical lines make sense?

**Comment by lkubb** [comment]
I suppose it was meant as

```python
    # Not a typo. Invert the dictionary twice to get unique values only.
    nft_families = {v: k for k, v in _NFTABLES_FAMILIES.items()}
    nft_families = {v: k for k, v in nft_families.items()}
```
to filter unique values and then get back some set of corresponding labels. Since each label has an identity mapping, it would make much more sense to just write `set(_NFTABLES_FAMILIES.values())`. Although nonsensical and inefficient, the current code should still function as expected from what I glanced.

**Comment by bendikro** [comment]
Your suggestion would make sense. However, if the code is supposed to be

```
 # Not a typo. Invert the dictionary twice to get unique values only.
    nft_families = {v: k for k, v in _NFTABLES_FAMILIES.items()}
    nft_families = {v: k for k, v in nft_families.items()}
```

the resulting dict depends on the order of the key/values in `_NFTABLES_FAMILIES` returned by `items()`. Specifically the keys that have the same values. Is that intended? 

The current code works, however, the second line has no effect.

**Comment by lkubb** [comment]
From what I can tell (I'm not the author), the only purpose of the resulting dict's keys would be to be turned back into their values again, so order should not matter, just the uniqueness of values.

https://github.com/saltstack/salt/blob/76e50885b07621e9e4c16bc3f1ebc16c93983b90/salt/modules/nftables.py#L451-L452

https://github.com/saltstack/salt/blob/76e50885b07621e9e4c16bc3f1ebc16c93983b90/salt/modules/nftables.py#L380

**Comment by whytewolf** [comment]
@nicholasmhughes any comment on this? this was your code change.

**Comment by nicholasmhughes** [comment]
> I suppose it was meant as
> 
> ```python
>     # Not a typo. Invert the dictionary twice to get unique values only.
>     nft_families = {v: k for k, v in _NFTABLES_FAMILIES.items()}
>     nft_families = {v: k for k, v in nft_families.items()}
> ```
> 
> to filter unique values and then get back some set of corresponding labels. Since each label has an identity mapping, it would make much more sense to just write `set(_NFTABLES_FAMILIES.values())`. Although nonsensical and inefficient, the current code should still function as expected from what I glanced.

it's been forever since I messed with this... at first glance, I think it was probably intended to be this :point_up:
