### ISSUE TITLE
[BUG] pkg.update not working from Salt-master 3006.2 on RHEL 8 to Salt-minion 2006.2 on RHEL/Rocky9

### ISSUE THREAD

**Issue by tekelle** [saltstack/salt#65384]
**Description**
Executing a command either using pkg.update or "yum update -y" from the salt-master server (RHEL 8) to a server running salt-minion on RHEL9 or Rocky9 hangs.  Command to RHEL8/Rocky8/CentOS7, works as intended.  Other commands to RHEL9 or Rocky 9 seem to work.

**Setup**
Rocky 9 and RHEL 9 minimum server install.  Salt 3006.2 (3006.1 failed as well)

Please be as specific as possible and give set-up details.

- [X] on-prem machine
- [X] VM - Vmware

**Steps to Reproduce the behavior**
Install salt-minion and salt on a minimum install on Rocky or Red Hat 9.

**Expected behavior**
Minion does a yum/dnf update

**Versions Report**
salt-call --versions-report
Salt Version:
        Salt: 3006.2
Python Version:
        Python: 3.10.12 (main, Aug 3, 2023, 21:47:10) [GCC 11.2.0]
Dependency Versions:
         cffi: 1.14.6
     cherrypy: 18.6.1
     dateutil: 2.8.1
    docker-py: Not Installed
        gitdb: Not Installed
    gitpython: Not Installed
       Jinja2: 3.1.2
      libgit2: Not Installed
 looseversion: 1.0.2
     M2Crypto: Not Installed
         Mako: Not Installed
      msgpack: 1.0.2
 msgpack-pure: Not Installed
 mysql-python: Not Installed
    packaging: 22.0
    pycparcer: 2.21
     pycrypto: Not Installed
 pycryptodome: 3.9.8
       pygit2: Not Installed
 python-gnupg: 0.4.8
       PyYaml: 6.0.1
        PyZQK: 23.2.0
       relenv: 0.13.3
        smmap: Not Installed
      timelib: 0.2.4
      Tornado: 4.5.3
          ZMQ: 4.3.4

System Versions: (salt-master)
         dist: rhel 8.8 Ootpa
       locale: utf-8
      machine: x86_64
      release: 4.18.0-477.27.1.el8_8.x86_64
       system: Linux
      version: Red Hat Enterprise Linux 8.8 Ootpa

System Versions: (salt-minion)
         dist: rocky 9.2 Bue Onyx
       locale: utf-8
      machine: x86_64
      release: 5.14.0-284.30.1.el9_2.x86_64
       system: Linux
      version: Rocky Linux 9.2 Blue Onyx

**Comment by OrangeDog** [comment]
Presumably it's trying to upgrade the minion from 3006.2 to 3006.3 when you do that?

**Comment by tekelle** [comment]
This is a closed network.  The rpms are pulled down and moved to close network.  We do not have 3006.3 RPMs in our repos.

**Comment by OrangeDog** [comment]
Then does it hang because it's trying to reach the internet?
Getting a debug log from the minion would be useful.

**Comment by tekelle** [comment]
We see not calls to the outside.  We do get a -9 error code when trying to do the yum update via salt.  I am unable to provide debug logs.  Running "/usr/bin/python3 /usr/bin/yum update -y" works when running by hand on the system.

**Comment by OrangeDog** [comment]
-9 is not an error code I am aware of. Where do you see it?

Without logs or a reproduction this is unlikely to be solved.

**Comment by tekelle** [comment]
Ok, we tracked this down to FIPS on our end and we are still troubleshooting.  We are only allowed to use 6 specific cipher suites and although our RHEL 7, RHEL 8, and CentOS 7 are configured with same cipher suites, RHEL 9 and Rocky9 seems to have the issues with the configuration when running yum update.  We are stepping through this.  Looks like yum update does actually work but it will not end the "/usr/bin/python3 /usr/bin/yum update -y" process when yum completes.

**Comment by tekelle** [comment]
Finally got 3002.3 in and installed.  Updates now work with FIPS enabled.

**Comment by OrangeDog** [comment]
This may be the cause: https://github.com/pypa/pip/issues/12369
