### ISSUE TITLE
[BUG] x509 report "M2Crypto has no attributes"

### ISSUE THREAD

**Issue by skob** [saltstack/salt#65474]
salt x509 module unavailable anymore

M2Crypto module has breaking change:
>    - Excessively complicated and error-prone __init__py has been
>      cleaned and `import M2Crypto` doesn’t include everything
>      anymore. Imports should specified as for example with `from
>      M2Crypto import foo`.

https://gitlab.com/m2crypto/m2crypto/-/blob/master/CHANGES?ref_type=heads#L24

as workaround is possible to use M2Crypto==0.39

**Comment by OrangeDog** [comment]
The x509 module that uses M2Crypto is deprecated. Users should be migrating to x509_v2, which will become the default in a future release.
