### ISSUE TITLE
[FEATURE REQUEST] Masterless master tops

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#65479]
**Is your feature request related to a problem? Please describe.**
Masterless minions currently do not support master tops, which is a feature discrepancy vs regular Salt.

**Describe the solution you'd like**
When `opts["file_client"] == "local"`, evaluate master top modules locally.

**Describe alternatives you've considered**
None.

**Additional context**
https://github.com/saltstack/salt/issues/27930

**Comment by OrangeDog** [comment]
What would "master tops" mean when there is no master?

**Comment by lkubb** [comment]
> What would "master tops" mean when there is no master?

Just some external data source providing the targeted states for a highstate, as usual. Pillar modules work on masterless minions as well, this is roughly the state equivalent (without providing the actual states admittedly).
