### ISSUE TITLE
debian 12 compatible

### ISSUE THREAD

**Issue by backl1n** [saltstack/salt#65502]
**Is your feature request related to a problem? Please describe.**
just i would debian 12 compatible

**Describe the solution you'd like**
installation of agent salt-minion on debian 12

**Additional context**
today i can't use salt on debian 12 

**Please Note**
If this feature request would be considered a substantial change or addition, this should go through a SEP process here https://github.com/saltstack/salt-enhancement-proposals, instead of a feature request.

**Comment by backl1n** [comment]
thank you in advance for your reply

**Comment by colttt** [comment]
duplication of https://github.com/saltstack/salt/issues/64223
