### ISSUE TITLE
[BUG] AWS Metdata fails when IMDSv2 is enabled

### ISSUE THREAD

**Issue by garethgreenaway** [saltstack/salt#65513]
**Description**
If an AWS instance is running in an environment where IMDSv2 is enabled then the metadata grain will fail with a 401 Unauthorized error.

**Setup**
Create an instance in an AWS environment where IMDSv2 is enabled.  On that instance enable the `metadata_server_grains` grain in the minion configuration.

**Steps to Reproduce the behavior**
Query the grains on the running instance.

**Expected behavior**
AWS Metadata grains should be returned.

**Comment by OrangeDog** [comment]
Duplicate of #65233
See also #60668
