### ISSUE TITLE
[DOCS] Unclear if dependencies in zip archive modules can call __salt__

### ISSUE THREAD

**Issue by Daniel-Lecoq** [saltstack/salt#65534]
**Description**
Note: Adding this under docs because it might be a misunderstanding from my side.

I have created a zipped module with the following structure:

```
pega_api
  __init__.py
  helper
    __init__.py
```

The first file contains the main functions while the file in the subdirectory contains helper functions. The helper functions are called by the pega_api functions. Both also make use of other execution modules e.g. `__salt__["cmd.run"]`

The zipped module get imported correctly, but upon testing I get the following error

```
  File "/var/cache/salt/minion/extmods/modules/pega_api.zip/pega_api/__init__.py", line 81, in get_status
  File "/var/cache/salt/minion/extmods/modules/pega_api.zip/pega_api/helper/__init__.py", line 40, in generate_connection_details
  File "/var/cache/salt/minion/extmods/modules/pega_api.zip/pega_api/helper/__init__.py", line 54, in get_connection_details
NameError: name '__salt__' is not defined
```

Is it the case that dependencies in zipped modules cannot make use of salt execution modules? Or have I made some error here?

**Suggested Fix**
If dependencies cannot call salt in this way it would be nice to have some note about this in the documentation on zipped modules.

**Type of documentation**
Salt modules

**Location or format of documentation**
https://docs.saltproject.io/en/latest/ref/modules/index.html#zip-archives-as-modules

**Additional context**
We have other custom modules which have gotten very large and unwieldy. It would be nice if there was a way to split these up, especially in the case of helper functions or private functions.
For now I assume the solution is to split up the functions into smaller, more specific modules .

**Comment by OrangeDog** [comment]
> The helper functions are called by the pega_api functions.

How are they called?

The salt loader cannot insert the dunders if it is not involved. You either need to pass them as arguments to the functions you call, or hack it like this:

```py
from . import helper

def __init__(opts):
  helper.__salt__ = __salt__
```

**Comment by Daniel-Lecoq** [comment]
Okay thanks for the clarification, that's what I suspected.

The helper functions are called like this:

```py
from pega_api import helper

def get_status(operation_name, url=None, username=None, password=None, job_id=None):

    # Generate connection properties string
    connection_details = helper.generate_connection_details(url, username, password)
```

I will probably revert to private helper functions inside a single module file then. You can close this issue.

**Comment by OrangeDog** [comment]
> private helper functions inside a single module file

Or use one of the two solutions I gave.
