### ISSUE TITLE
[BUG] salt-minion service restart option only stops it

### ISSUE THREAD

**Issue by LeaDevelop** [saltstack/salt#65577]
**Description**
salt-minion service does not start after we restart it via Task Manager Services tab.
It gets from running -> stopping -> stopped and that's where it ends.

Salt version 3006.1
MS Windows Server 2022 standard, 10.0.20348

If we restart the services in the services window itself then it restarts as expected.

**Steps to Reproduce the behavior**

1. Open task manager and services tab
2. Look for salt-minion service
3. Right click on salt minion
4. Press restart
5. Observe salt-minion service status

Result: 
salt-minion goes from running -> stopping -> stopped and that's where it ends.

**Expected behavior**
salt-minion stops and returns to running status
running -> stopping -> stopped-> starting -> running

**Screenshots**
![not-working-as-expected](https://github.com/saltstack/salt/assets/104503492/6c083777-0f91-4720-9951-862dca240ddd)

**Additional context**
If salt-minion is restarted in the Services application then it will restart as expected.

**Comment by OrangeDog** [comment]
Restarting a service via Task Manager is supposed to be exactly the same as via Services, so that's very odd.

**Comment by whytewolf** [comment]
humm just tried this with windows 11 and it restarted without issue in taskman. 

however it shouldn't just go from running to not running it should cycle through the different status. 
running -> stopping -> stopped -> starting -> running

We are most likely going to need a lot more info. such as windows version. and if the minion does try starting. if it does try starting then fails we will need a log. 

you might also want to check your windows event log to see if there are any errors there. 

like @OrangeDog said restarting a service in taskman is supposed to be exactly the same as restarting it from services. so this is very odd one works the other doesn't.

**Comment by LeaDevelop** [comment]
> humm just tried this with windows 11 and it restarted without issue in taskman.
> 
> however it shouldn't just go from running to not running it should cycle through the different status. running -> stopping -> stopped -> starting -> running
> 
> We are most likely going to need a lot more info. such as windows version. and if the minion does try starting. if it does try starting then fails we will need a log.
> 
> you might also want to check your windows event log to see if there are any errors there.
> 
> like @OrangeDog said restarting a service in taskman is supposed to be exactly the same as restarting it from services. so this is very odd one works the other doesn't.

It gets from running -> stopping -> stopped and that's where it ends.
MS Windows Server 2022 standard, 10.0.20348

I'll give it a further look and get back with more info next week, thank you both. And yeah I was expecting same result that's why have opened issue and wondered if anybody else experienced the same :)

**Comment by LeaDevelop** [comment]
Didn't forget about the logs, got it noted for next week as am having some time off at the moment :)

**Comment by LeaDevelop** [comment]
Confirmed issue on our side and that specific minion nodegroup. Could not reproduce on fresh installation or similar setup. Thank you all for contributing to the topic ❤️ and ty for pointing out what all I should bring as info when I open issue, will properly read up guidelines next time 😊
