### ISSUE TITLE
[TEST FAILURE]  salt-ssh integration test: `test_saltcheck.py::test_saltcheck_state`

### ISSUE THREAD

**Issue by lkubb** [saltstack/salt#65574]
I noticed the test was failing in my PR to update the SSH wrappers: https://github.com/saltstack/salt/pull/65517

`git bisect` shows it has been failing since https://github.com/saltstack/salt/commit/639ec023f1a1a7e880a4675ddc6016fdb8ff68ab and is not caused by the PR.

Link to a failed run: https://github.com/saltstack/salt/actions/runs/6778504049/job/18427263656

**Comment by dmurphy18** [comment]
Fix under test for https://github.com/saltstack/salt/commit/639ec023f1a1a7e880a4675ddc6016fdb8ff68ab with PR https://github.com/saltstack/salt/pull/65738

Will check test once that fix is merged

**Comment by dmurphy18** [comment]
Closing this since the custom grains change has been reverted and merged by https://github.com/saltstack/salt/issues/65692
