### ISSUE TITLE
Postgres Grant State and Module needed.

### ISSUE THREAD

**Issue by JasonSwindle** [saltstack/salt#6558]
Howdy,

It would be real handy to have a Postgres grant module and state much like MySQL does.

[MySQL Grant Doc Link](http://docs.saltstack.com/search.html?q=mysql+grant)

To do this currently, you need to either use scripts or _gasp_ by hand.

Thanks
**Jason Swindle**

**Comment by jdelic** [comment]
I think this issue should be closed, postgres modules are here and have been for a while.
