### ISSUE TITLE
[BUG] Unable to estabilish tcp mTLS minion-master connection 

### ISSUE THREAD

**Issue by szymonsypula** [saltstack/salt#65609]
Hello

I was following documentation for tcp transport mTLS enablement for salt minion-master communication. 
When setting up salt-master configuration - master is producing SSL related Errors coming from python libraries.  

Errors are produced in loop. 

2023-11-24 14:41:07,180 [tornado.general  :1333][WARNING ][22216] SSL Error on 82 ('x.x.x.x', 24861): [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:852)

2023-11-24 14:41:09,663 [tornado.general  :555 ][ERROR   ][22201] Uncaught exception, closing connection.
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/iostream.py", line 520, in _handle_events
    self._handle_read()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/iostream.py", line 1396, in _handle_read
    self._do_ssl_handshake()
  File "/usr/lib/python3.6/site-packages/salt/ext/tornado/iostream.py", line 1316, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 1106, in do_handshake
    self._sslobj.do_handshake()
  File "/usr/lib64/python3.6/ssl.py", line 689, in do_handshake
    self._sslobj.do_handshake()
OSError: [Errno 0] Error

**Setup**
Salt-master VM running on a public cloud  

/etc/salt/master.d/ssl.conf

ssl:
  keyfile: /var/lib/certs/certificates/key.key
  certfile: /var/lib/certs/certificates/cert.crt                                         
  ca_certs: /var/lib/certs/certificates/ca_cert.crt
  cert_reqs: CERT_REQUIRED
  ssl_version: PROTOCOL_TLSv1_2
transport: tcp

**Versions Report**

Salt Version:
          Salt: 3006.0
 
Python Version:
        Python: 3.6.15 (default, Sep 23 2021, 15:41:43) [GCC]
 
Dependency Versions:
          cffi: 1.13.2
      cherrypy: 18.3.0
      dateutil: 2.8.1
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 2.10.1
       libgit2: 1.3.0
  looseversion: 1.0.2
      M2Crypto: 0.38.0
          Mako: Not Installed
       msgpack: 0.5.6
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 21.3
     pycparser: 2.17
      pycrypto: 3.9.0
  pycryptodome: Not Installed
        pygit2: 1.7.0
  python-gnupg: Not Installed
        PyYAML: 5.4.1
         PyZMQ: 17.1.2
        relenv: Not Installed
         smmap: Not Installed
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.2.3
 
System Versions:
          dist: opensuse-leap 15.5 
        locale: UTF-8
       machine: x86_64
       release: 5.14.21-150500.55.19-default
        system: Linux
       version: openSUSE Leap 15.5 

**Steps to Reproduce the behavior**
Set up /etc/salt/master.d/ssl.conf
systemctl restart salt-master 

**Expected behavior**
After setting up tcp transport and ssl options - salt master is ready to establish connection with minions.

**Comment by OrangeDog** [comment]
How is Salt installed? From SUSE packages or some other method?

**Comment by szymonsypula** [comment]
Salt is installed as a part of Uyuni server [2023.10] component.

**Comment by OrangeDog** [comment]
It's probably a dependency issue, so raise it with them first.

**Comment by szymonsypula** [comment]
Issue was related with dependent software. Thank you @OrangeDog for support.
