### ISSUE TITLE
[DOCS] install-salt-on-debian-11-bullseye-arm64

### ISSUE THREAD

**Issue by damon-atkins** [saltstack/salt#65607]
**Description**
Typo in install instuctions.

**Suggested Fix**
Should be arch=arm64 not amd64

**Type of documentation**
Install guide, typo.

**Location or format of documentation**
https://docs.saltproject.io/salt/install-guide/en/latest/topics/install-by-operating-system/debian.html#install-salt-on-debian-11-bullseye-arm64

**Additional context**
Should be arch=arm64 not amd64
```
echo "deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.gpg arch=amd64] https://repo.saltproject.io/salt/py3/debian/11/arm64/latest bullseye main" | sudo tee /etc/apt/sources.list.d/salt.list
```

**Comment by Akm0d** [comment]
Issue has already been fixed
