### ISSUE TITLE
Method to access the requesting user from module/runner

### ISSUE THREAD

**Issue by jacksontj** [saltstack/salt#6567]
RIght now the only way to get the username of the requestor is to instantiate the client and do client.salt_user (which only works in the runner). I know that the requestor is passed around in the payload_kwargs. Can we make that accessible in some sort of **payload** dict or something?

**Comment by arroyoc** [comment]
@jacobhammons @jacksontj I am closing this ticket due to inactivity. If anyone feels that this feature needs more attention feel free to reopen it.

**Comment by jacobhammons** [comment]
This still needs to be added to the docs, reopening.
