### ISSUE TITLE
[DOCS] curl command error: https://docs.saltproject.io/salt/install-guide/en/3006/topics/install-by-operating-system/debian.html#install-salt-on-debian-12-bookworm-arm64

### ISSUE THREAD

**Issue by dclyon** [saltstack/salt#65705]
The curl command listed under the "Install Salt on Debian 12 (Bookworm) arm64" section
 seems to contain a small error. The command should contain "arch=arm64" instead of "arch=amd64". When issuing the current command on an arm machine there is an architecture mismatch error. The syntax in question is highlighted within image below: 
 
![2023-12-14 at 13-31-04 Debian - Salt install guide](https://github.com/saltstack/salt/assets/141665671/547192d8-0e50-40d7-80ce-bdf92cd7f5c8)

**Comment by barbaricyawps** [comment]
Thanks for letting us know. I've got an MR in to fix it: https://gitlab.com/saltstack/open/docs/salt-install-guide/-/merge_requests/176

**Comment by barbaricyawps** [comment]
Merged and updated. Let me know if there are any other issues! Closing now.
