### ISSUE TITLE
[BUG] [master] nightly builds are no longer adding to repo ( since 2023-09-19 )

### ISSUE THREAD

**Issue by ITJamie** [saltstack/salt#65877]
nightly builds of the master branch (https://repo.saltproject.io/salt-dev/master/) has not been added to since 2023-09-19 

the 3006.x nightly builds are getting added. (https://repo.saltproject.io/salt-dev/3006.x/)

**Comment by whytewolf** [comment]
this should be fixed now. the issue was master was not passing the tests so without passing wouldn't upload. 3006, 3007 and master have all started passing tests now thanks to @s0undt3ch and have more recent versions.
