### ISSUE TITLE
[BUG] Minion->Master protocol design exacerbates edge cases in TCP connection failure detection

### ISSUE THREAD

**Issue by kuroneko** [saltstack/salt#66032]
**Description**
Minions running over long paths to the master can randomly loose connectivity with the master and not realise they have lost connectivity within reasonable time when using the default TCP keepalive config.

Whilst the TCP keepalive option can work around this for the environments that support it, those timeouts are quite slow (on purpose), and TCP keepalives aren't really the best option in all use cases as they can be fooled by certain network configurations.

Variations of this particular problem are likely responsible for a number of the transport related bugs that are presently open.

**Setup**
This is more fundamentally incorrect use of TCP rather than a platform specific bug.

Discovered with Salt 3006.4.

**Steps to Reproduce the behavior**
Silently break the connection path without generating a RST to the minion (easiest way is to drop the conntrack data silently on a NAT inbetween).  Wait for the minion to realise the connection is broken.

**Expected behaviour**

A TCP Socket is only able to be proven to be connected when you send traffic down it.  The corollary of this is that a predominantly passive participant is not capable of detecting TCP connection failures reliably.

As the minion is the initiator, it MUST heartbeat over the TCP paths (be it a simple NOP or a ping or a dedicated heartbeat message) to make sure the TCP connection it's assuming is open, is actually open and to trigger any connection failures so it knows to reconnect.

Without this, the minion cannot reliably know that it has lost it's connection to the master.  This results in the minion believing it is connected and doing noting to fix the situation, whilst the master can be well aware that the connection has dropped.

Whilst the TCP keepalive feature can mitigate some of this problem in some circumstances, it does not work correctly where there is use of TCP Performance Enhancing Proxies such as those found in satellite gear or WAN/VPN accelerators (as the TCP session is frequently terminated by the proxying device to encourage the communicating host's TCP stack to scale up the window size) or where the OS does not support it.   As such, it's highly recommended that the application (the minion in this case) routinely sends data to verify the connection and precipitate failures in this case - when interacting with proxies such as those described above, they will generally close the connection once they realise the connection path has failed, but they generally need traffic flowing to prove this).

**Comment by dwoz** [comment]
@kuroneko does the [master-alive-interval](https://docs.saltproject.io/en/latest/ref/configuration/minion.html#master-alive-interval) minion config option resolve this issue?

**Comment by kuroneko** [comment]
> @kuroneko does the [master-alive-interval](https://docs.saltproject.io/en/latest/ref/configuration/minion.html#master-alive-interval) minion config option resolve this issue?

I'll try that and see if the behaviour improves.  By the description, I'd imagine it will fix the poor behaviour we're seeing in which case the documentation probably needs amending to make it clear that this option is likely desirable in single-master configurations with complex/long paths to the master.

**Comment by kuroneko** [comment]
Actually, I just did a bit of code analysis, and whilst I'll still try it, I'm no longer hopeful this will fix the issue without code change.

Whilst it changes the schedule for the master check, the part that enables pinging the master is gated against failover being enabled - which it is not in our environment.

**Comment by kuroneko** [comment]
Confirmed that setting `master-alive-interval` alone is not enough to fix the issue.

**Comment by kuroneko** [comment]
after trying to analyse the connection handling, I discovered `ping_interval` exists and fixes the exact problem by ensuring there's regular traffic originating from the minion.

If anything, `ping_interval` should have a non-zero default because you *really* do not want to be relying on a silent TCP connection remaining connected (it's fundamentally not how TCP works).
