### ISSUE TITLE
rpm.spec file included hardcoded commands to restart the minion at upgrade which do not exist

### ISSUE THREAD

**Issue by ccoughle** [saltstack/salt#66143]
**Description**
Both the salt minion and the salt master run a script containing:  

```
# assumes systemd for RHEL 7 & 8 & 9
# foregoing %systemd_* scriptlets due to RHEL 7/8 vs. RHEL 9 incompatibilities
## - Using hardcoded scriptlet definitions from RHEL 7/8 that are forward-compatible
postinstall scriptlet (using /bin/sh):
# %systemd_post salt-master.service
if [ $1 -gt 1 ] ; then
  # Upgrade
  systemctl retry-restart salt-master.service >/dev/null 2>&1 || :
else
  # Initial installation
  systemctl preset salt-master.service >/dev/null 2>&1 || :
fi
```

The issue is that "systemctl retry-restart salt-master.service" does not exist.  So the minion never restarts.  
It seems that this has been fixed in the master branch, however since it drops minions into a bad state where communication is broken, it would seem to be something that should be included into the 3006 branch as soon as it can be.  

**Setup**

Nothing fancy, just a normal update of an rpm

**Steps to Reproduce the behavior**
update ( or re-install ) the salt minion and note the service doesn't restart

**Expected behavior**
Service should restart

**Screenshots**

**Versions Report**

salt-3006.6 to salt 3006.7.  ( has also happened on several recent point releases )

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by dmurphy18** [comment]
And the retry-restart was stolen form the spec file used to build the RHEL 7 etc classic packaging for Salt, see https://github.com/saltstack/salt-pack-py3/blob/develop/file_roots/pkg/salt/3005_5/rhel7/spec/salt.spec#L393-L501 and has been that way for years, at least since 2015/2016. Wonder if some systemd arguments have been deprecated and failed to notice.

**Comment by dmurphy18** [comment]
Wonder if there has been a typo all these years, since systemctl --help produces 
```
try-restart UNIT...                 Restart one or more units if active
```
perhaps it should be systemctl try-restart salt-master.service

Needs investigating

**Comment by dmurphy18** [comment]
Checked on RHEL 7, latest with systemd 219 and it look slike we have had a typo for years

**Comment by ccoughle** [comment]
It has been a problem for all of 3006.x for our environment.

**Comment by ccoughle** [comment]
Likely since this part was added:  
# assumes systemd for RHEL 7 & 8 & 9
# foregoing %systemd_* scriptlets due to RHEL 7/8 vs. RHEL 9 incompatibilities
## - Using hardcoded scriptlet definitions from RHEL 7/8 that are forward-compatible
postinstall scriptlet (using /bin/sh)

Which commented out all of the %systemd_post/pre/whatever scriptlets as noted above

**Comment by dmurphy18** [comment]
That was added due to RHEL 7 not having some later systemd macros etc., and pulled out what we used to do in classic packaging and not relying on those macros etc, except who knew, a typo for almost a decade and only discovered now.

**Comment by ccoughle** [comment]
Yeah, 

Looks like it entered into things in this commit:  

https://github.com/saltstack/salt/commit/62a58e3cca946641cad77a12ca08e7bfab642a1f
from the PR here:  https://github.com/saltstack/salt/pull/66030
Which in turn was an outgrowth of the issues here:  https://github.com/saltstack/salt/issues/65987

The really old spec file you linked above had systemctl try-restart in it, which does work.  Somehow it seems it got switched to retry-restart when it was copied into place for the commit above. 

Kinda wonder if this was the case of basically find-and-replace: start --> try-restart.  But it was ran against systemctl restart... 
hence you het back the retry-restart...

Anywho, I am glad the fix seems like it will be easy.

**Comment by dmurphy18** [comment]
Apparently my new glasses don't work, read **try-restart** as **retry-restart**, darn, typo in translation from the original example in classic packaging, will fix this personally

**Comment by dmurphy18** [comment]
Closing associated PR merged
