### ISSUE TITLE
[BUG]when run cmd.script with args=0 the script could not receive args

### ISSUE THREAD

**Issue by CyaLiven** [saltstack/salt#66145]
**Description**

foo.sh
```bash
#!/bin/sh
echo $*
```

when run salt myminion cmd.script salt://foo.sh 0 or salt myminion cmd.script salt://foo.sh "0", can't print 0
when  run salt myminion cmd.script salt://foo.sh 1, can print 1
when  run salt myminion cmd.script salt://foo.sh "'0'", can print 0

i found code in
[[modules](https://github.com/saltstack/salt/tree/master/salt/modules)cmdmod.py](https://github.com/saltstack/salt/blob/master/salt/modules/cmdmod.py#L2918)
`cmd_path + " " + str(args) if args else cmd_path`

**Comment by Akm0d** [comment]
Validated the bug and I am seeing the same issue.  Working on a fix now.

**Comment by Akm0d** [comment]
The input should be doubly quoted to pass in falsey values -- I updated the documentation for "args" to reflect that.    However, the output is being eaten and not returned if it is a falsey value. This is a problem that needs fixed.

**Comment by Akm0d** [comment]
For example, if I run this script:
```
```
With `cmd.script` like this:
```
$ salt-call --local cmd.script salt://foo.sh "''0''"
```
Then the output is as expected.

**Comment by Akm0d** [comment]
Come to think of it, given how salt renders input to scripts and output from scripts -- this might just be a documentation issue.  If you want to pass or return a falsey value (a string that evaluates to a false value in a python conditional) with "cmd.script", then you need to doubly quote it.
