### ISSUE TITLE
[TECH DEBT] salt-ssh needs a new release

### ISSUE THREAD

**Issue by ctrix** [saltstack/salt#66203]
### Description of the tech debt to be addressed, include links and screenshots

I see that at [this url](https://pypi.org/project/salt-ssh/#history) on pipy the last salt-ssh release is tagged as 9000 but i cannot find any similar tag in the main repository.
Also, the version is quite old and the previous one is 3005.1 from 2022. 3006 and 3007 are missing.

What is 9000 for? is that on purpose? Does it track to a specific git tag or hash?

### Versions Report

Not needed.

**Comment by Timmeeh** [comment]
To be fair on the PyPI [description](https://pypi.org/project/salt-ssh/#description) page of salt-ssh it does mention that 9000 is the last release, and that the salt package should be used for subsequent versions. Installing that one currently does install the expected salt-ssh 3007.0 as well.
Then again cannot immediately find a reference to this change in the docs anymore, and on the [getting started page of salt-ssh](https://docs.saltproject.io/en/getstarted/ssh/system.html), it still says to install the `salt-ssh` package via pip, not `salt`.

**Comment by whytewolf** [comment]
as @Timmeeh said the description page says exactly what is happening. salt-ssh has been moved entirely into the main salt package. 

```
Project description

NOTICE: Salt-SSH PyPi Project Not Active

    The Salt Project team will no longer publish releases to this Salt-SSH pypi project. Please use the [Salt pypi project](https://pypi.org/project/salt/) to install and use Salt-SSH.
```
