### ISSUE TITLE
[BUG] os.nice requires an argument

### ISSUE THREAD

**Issue by boyadzhievb** [saltstack/salt#66289]
**Description**
(https://github.com/saltstack/salt/blob/927ccc72641c8d103dcbc6ef73720626ea5e62e0/salt/master.py#L1293)
os.nice(increment) requires an argument

**Setup**
set mworker_niceness: 1 in master, you'll see the error in logs :

 2024-03-29 09:14:30,842 [salt.utils.process:913 ][ERROR   ][28892] An un-handled exception from the multiprocessing process 'MWorker-101' was caught:
                                      Traceback (most recent call last):
                                        File "/usr/lib/python3.6/site-packages/salt/utils/process.py", line 904, in wrapped_run_func
                                          return run_func()
                                        File "/usr/lib/python3.6/site-packages/salt/master.py", line 1195, in run
                                          log.info(os.nice())
                                      TypeError: nice() takes exactly one argument (0 given)

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [ ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Steps to Reproduce the behavior**
(Include debug logs if possible and relevant)

**Expected behavior**

**Screenshots**

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

```yaml
PASTE HERE
```
</details>

**Additional context**

**Comment by dwoz** [comment]
@boyadzhievb please provide the output of `salt --versions-report`

**Comment by boyadboz** [comment]
This is a clear example why salt is digging its grave ! 
You had to add an '0' instead of removing the log line ! :D :D :D
log.info(os.nice())  should become 
log.info(os.nice(0)) that's all

:D

**Comment by whytewolf** [comment]
> This is a clear example why salt is digging its grave ! You had to add an '0' instead of removing the log line ! :D :D :D log.info(os.nice()) should become log.info(os.nice(0)) that's all
> 
> The function sets current nice level + 'argument', so if current nice is 20 with os.nice(0) it will stay 20 but will print it .
> 
> :D

it was removed because it was useless information as is even when working. a random number in the middle of the logs does not help anyone. i knew perfectly well adding 0 to the function would output the current niceness level. but that just sticks a random number in the middle of the logs with no context. I could have updated the log to be more informative about what it meant yes. but the line above already covered what is happening.

**Comment by boyadzhievb** [comment]
> > This is a clear example why salt is digging its grave ! You had to add an '0' instead of removing the log line ! :D :D :D log.info(os.nice()) should become log.info(os.nice(0)) that's all
> > The function sets current nice level + 'argument', so if current nice is 20 with os.nice(0) it will stay 20 but will print it .
> > :D
> 
> it was removed because it was useless information as is even when working. a random number in the middle of the logs does not help anyone. i knew perfectly well adding 0 to the function would output the current niceness level. but that just sticks a random number in the middle of the logs with no context. I could have updated the log to be more informative about what it meant yes. but the line above already covered what is happening.

Adding the argument is pretty useful, i am talking from experience not from assumption. It is not random message it is exactly what i expected.
