### ISSUE TITLE
[BUG] Inline pillar cached when pillar_cache=True

### ISSUE THREAD

**Issue by jtraub91** [saltstack/salt#66292]
**Description**

When pillar cache is True, inline pillar is being cached in certain scenarios. It seems to be happening at unexpected times but, I've found a way to reliably reproduce it. It seems to happen when inline pillar is being supplied via the `pillar` argument to the [salt.state](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.saltmod.html#salt.states.saltmod.state) function, when called in an orchestration, _and_ when the pillar_cache file for the minion (e.g. `/var/cache/salt/master/pillar_cache/<minion-id>`) does not exist.  

**Setup**

Install salt-master and salt-minion on a machine. The configuration used was as follows.

```yaml
# /etc/salt/master.d/master.conf

user: root
pillar_cache: True
```

```yaml
# /etc/salt/minion.d/minion.conf

master: localhost
```

The orchestration and state used were as follows. The hostname / minion-id in the example below is `minion`.

```yaml
# /srv/salt/orch.sls
call_state:
  salt.state:
    - tgt: minion
    - sls: state
    - pillar:
        state_key: {{ pillar["key"] }}
```

```yaml
# /srv/salt/state.sls
echo {{ pillar["state_key"] }}:
  cmd.run
```

**Steps to Reproduce the behavior**

```bash
salt-run state.orch orch pillar='{"key": "yolo"}'
```

```bash
salt-call pillar.get state_key
```

Notice that the `key` pillar passed to the orch, which is subsequently passed as `pillar` to the [salt.state](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.saltmod.html#salt.states.saltmod.state) function as `state_key` is being persisted in the pillar_cache for `minion`.

If this does not happen for you, you may force the issue by removing the pillar_cache files for the minion, e.g.

```bash
rm -rf /var/cache/salt/master/pillar_cache/*
```

and re-running the above commands.

Also notice that once the minion's pillar_cache file exists, a subsequent execution won't change `state_key`'s value, e.g.

```bash
salt-run state.orch orch pillar='{"key": "yolofam"}'
```

including when the `state_key` doesn't even exist in the cache and `minion`'s pillar_cache file already exists. This situation can happen when a [saltutil.refresh_pillar](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.refresh_pillar) has been executed, e.g.

```bash
salt-call saltutil.refresh_pillar
```

When `state_key` does get cached in the above scenario, a subsequent call to [saltutil.refresh_pillar](https://docs.saltproject.io/en/latest/ref/modules/all/salt.modules.saltutil.html#salt.modules.saltutil.refresh_pillar) seems to clear it out, but nonetheless, this bug can be an issue for complex orchestrations and/or when it is unknown if this situation will occur.

**Expected behavior**

Inline pillar should never be cached.

**Versions Report**

```bash
root@minion:~# salt-call --versions-report
Salt Version:
          Salt: 3007.0
 
Python Version:
        Python: 3.10.13 (main, Feb 19 2024, 03:31:20) [GCC 11.2.0]
 
Dependency Versions:
          cffi: 1.16.0
      cherrypy: 18.8.0
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4
 
Salt Package Information:
  Package Type: onedir
 
System Versions:
          dist: ubuntu 22.04.2 jammy
        locale: utf-8
       machine: x86_64
       release: 5.15.0-67-generic
        system: Linux
       version: Ubuntu 22.04.2 jammy
```

**Comment by jtraub91** [comment]
Also, appears to only occur when called via the [salt.state](https://docs.saltproject.io/en/latest/ref/states/all/salt.states.saltmod.html#salt.states.saltmod.state) function, regardless of whether the `minion`'s pillar_cache file existed prior

**Comment by whytewolf** [comment]
thank you i have been able to replicate this. still trying to find where this is happening. it is weird. I was able to see that it cached in both the master pillar cache and the minion pillar cache.
