### ISSUE TITLE
[BUG] >3006.3 chocolatey error when package name is not lowercase

### ISSUE THREAD

**Issue by Timmeeh** [saltstack/salt#66290]
**Description**
Locally listed (`choco list`) packages sometimes have a capital, while using `choco search` for the same package (always?) returns the lowercase name. This causes issues since 3006.3 / https://github.com/saltstack/salt/pull/64922.

**Setup**

Using a master to manage several Windows minions with different versions, whose versions can differ. After upgrading a minion past 3006.3, problems start to occur.

**Steps to Reproduce the behavior**
Try to manage the installation of a Chocolatey package which is capitalized when running `choco list`. Examples are `firefox` and `everything`. The package should already be installed. Use the lowercase name to install.

Example

```
everything:
  chocolatey.installed
```

```
----------
          ID: everything
    Function: chocolatey.installed
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\state.py", line 2430, in call
                  ret = self.states[cdata["full"]](
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\loader\lazy.py", line 160, in __call__
                  ret = self.loader.run(run_func, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\loader\lazy.py", line 1233, in run
                  return self._last_context.run(self._run_as, _func_or_method, *args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\loader\lazy.py", line 1248, in _run_as
                  return _func_or_method(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\loader\lazy.py", line 1281, in wrapper
                  return f(*args, **kwargs)
                File "C:\Program Files\Salt Project\Salt\Lib\site-packages\salt\states\chocolatey.py", line 132, in installed
                  installed_version = version_info[full_name].get("installed")[0]
              TypeError: 'NoneType' object is not subscriptable
     Started: 09:11:45.221799
    Duration: 6375.082 ms
     Changes:
```

Reason seems to be that since 3006.3, the `chocolatey.version` module function starts returning available versions too

https://github.com/saltstack/salt/blob/8505972418f071f6dddbb41bdee6f2980d7fcf37/salt/modules/chocolatey.py#L1157-L1175

However when the package name is different between `choco list` and `choco search`, then the available and installed version info is not merged properly.

Works as expected, since name always lowercase
```
chocolatey.version notepadplusplus check_remote=True
  ----------
    notepadplusplus:
        ----------
        available:
            - 8.6.4
        installed:
            - 7.6.6
```

Merge doesn't happen, since difference in capitalization

```
chocolatey.version everything check_remote=True
  ----------
    Everything:
        ----------
        installed:
            - 1.4.1935
    everything:
        ----------
        available:
            - 1.4.11024
```

When the lowercase name is used to install the package, this will be used to index the `version_info` result from `chocolatey.version`, and the lowercase element does not have an `installed` key. Hence the error.
Note: indexing was changed to using `.get`, but when nothing is found None will be returned which cannot be indexed.

https://github.com/saltstack/salt/blob/8505972418f071f6dddbb41bdee6f2980d7fcf37/salt/states/chocolatey.py#L127-L132

**Expected behavior**
Package should be installed/managed.

**Versions Report**
<details><summary>salt --versions-report</summary>
(Provided by running salt --versions-report. Please also mention any differences in master/minion versions.)

Minion is 3007.0, master is still 3006.6

```yaml
Salt Version:
          Salt: 3007.0

Python Version:
        Python: 3.10.13 (heads/main:3079fcb, Feb 19 2024, 03:36:00) [MSC v.1937 64 bit (AMD64)]

Dependency Versions:
          cffi: 1.16.0
      cherrypy: 18.8.0
      dateutil: 2.8.2
     docker-py: Not Installed
         gitdb: Not Installed
     gitpython: Not Installed
        Jinja2: 3.1.3
       libgit2: Not Installed
  looseversion: 1.3.0
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 1.0.7
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     packaging: 23.1
     pycparser: 2.21
      pycrypto: Not Installed
  pycryptodome: 3.19.1
        pygit2: Not Installed
  python-gnupg: 0.5.2
        PyYAML: 6.0.1
         PyZMQ: 25.1.2
        relenv: 0.15.1
         smmap: Not Installed
       timelib: 0.3.0
       Tornado: 6.3.3
           ZMQ: 4.3.4

Salt Package Information:
  Package Type: onedir

System Versions:
          dist:
        locale: utf-8
       machine: AMD64
       release: 10
        system: Windows
       version: 10 10.0.19045 SP0 Multiprocessor Free
```
</details>

**Additional context**
Using `pkg.lower()` instead of `pkg` on these lines at least fixes the `chocolatey.installed` state.

https://github.com/saltstack/salt/blob/8505972418f071f6dddbb41bdee6f2980d7fcf37/salt/modules/chocolatey.py#L1160-L1161

**Comment by dwoz** [comment]
@twangboy thoughts on this one?

**Comment by twangboy** [comment]
Yeah, seems valid. I'll take a look.
