### ISSUE TITLE
Salt Minion - 3007.0 Installation Fails 

### ISSUE THREAD

**Issue by metaad** [saltstack/salt#66329]
**Description**
When tried to install salt minion from 3007.0 using "Salt-Minion-3007.0-Py3-AMD64.msi" it fails with the below error prompt

![Error](https://github.com/saltstack/salt/assets/106653425/06b76375-8718-4d12-805d-982c34c8e094)

In the same machine 3006.5 is getting installed without any issue. Tried installing 3007.0 on top of 3006.5. Still it fails.

**Steps to Reproduce the behavior**
 
Install "Salt-Minion-3006.5-Py3-AMD64.msi" with default settings.

**Screenshots**

![Error](https://github.com/saltstack/salt/assets/106653425/81c172b0-9e8d-4a59-936a-bdc2ca448cd7)

**Comment by twangboy** [comment]
An earlier report here: https://github.com/saltstack/salt/issues/66225
The issue has been fixed here: https://github.com/saltstack/salt/pull/66276
You can install VCredist to get the minion running.
https://learn.microsoft.com/en-us/cpp/windows/latest-supported-vc-redist
