### ISSUE TITLE
[BUG] docker python3 package missing from the debian 12 bookworm repo packages

### ISSUE THREAD

**Issue by mvintila** [saltstack/salt#66489]
**Description**
Docker_container.running state is not available on debian 12 with salt-minion installed from the apt repository because "docker" pip3 package is missing from the /opt/saltstack virtualenv.

```
[DEBUG   ] Could not LazyLoad docker_container.running: 'docker_container' __virtual__ returned False: 'docker.version' is not available.
[INFO    ] Running state [php_ct] at time 14:33:53.350317
[DEBUG   ] LazyLoaded docker_container.running
[ERROR   ] State 'docker_container.running' was not found in SLS 'webserver'
Reason: 'docker_container' __virtual__ returned False: 'docker.version' is not available.
```
**Setup**

Debian 12 virtual-machine with `salt-minion` package installed from `https://repo.saltproject.io/salt/py3/debian/12/amd64/latest bookworm main`

**Solution**
Run `/opt/saltstack/salt/bin/pip3 install docker`

**Comment by OrangeDog** [comment]
This is expected. You need to install additional dependencies (e.g. with `salt-pip`) before using modules that require them.

**Comment by mvintila** [comment]
Thank you for the clarification, but i did not come across this info before, did not even know about `salt-pip` until you mentioned it and i am a long time user of both Salt and Debian. 

Maybe this can be made more visible in the documentation?

Closing the issue.

**Comment by OrangeDog** [comment]
https://docs.saltproject.io/salt/install-guide/en/latest/topics/upgrade-to-onedir.html#how-to-upgrade-to-onedir
