### ISSUE TITLE
[DOCS] Fix typo on saltproject.io

### ISSUE THREAD

**Issue by leftsock** [saltstack/salt#66512]
**Description**

1- goto http://saltproject.io
2- see """It's data-drive orchestration and"""

**Suggested Fix**
What did you expect to see in the documentation that is missing or needs updating?

s/drive/driven/

**Type of documentation**
This could be Salt documentation, Salt modules, the Salt Repo or the Getting Started guide.

http://saltproject.io/index.html

**Location or format of documentation**
Insert page URL if applicable.

http://saltproject.io/index.html

**Additional context**

**Comment by ScriptAutomate** [comment]
Is fixed now!
