### ISSUE TITLE
[DOCS] Link to Slack community only works if you have a saltstack.com email address

### ISSUE THREAD

**Issue by dsyer** [saltstack/salt#66573]
Since https://github.com/saltstack/salt/blob/master/doc/_incl/requisite_incl.rst is visible to everyone and included in many pages of public documentation it seems unhelpful to include a link to a Slack community that you can only sign up to if you have a saltstack.com email address. Is there a better community to ask and answer questions about Salt?

**Comment by jheiselman** [comment]
The community switched from Slack to Discord due to a mandate from Broadcom. They are still finding all the places that need to be updated in the documentation. An invite link to the Discord server and a detailed explanation can be found at https://saltproject.io/blog/goodbye-slack-hello-discord/

**Comment by ScriptAutomate** [comment]
Updates are in-place via #66769 and will be part of merge-forwards.
