### ISSUE TITLE
[DOCS] SLACK community link is not working

### ISSUE THREAD

**Issue by rohanx01** [saltstack/salt#66815]
**Description**
I'm new to the Salt community, and when I clicked the Slack community link, it directed me to an unrelated site.

**Suggested Fix**
Admins need to update with the new link.

**Comment by max-arnold** [comment]
Could you please clarify where you found the broken Slack link?

Hopefully I found all of them, but I'm not 100% sure.

https://github.com/saltstack/salt/pull/66769

**Comment by jheiselman** [comment]
The welcome bot here on GitHub still posts the Slack link when a new reporter submits an issue.

**Comment by dmurphy18** [comment]
Darn, there in master and 3006.x branch :facepalm: always a missed place

**Comment by dmurphy18** [comment]
Closing since associated PR https://github.com/saltstack/salt/pull/66850 is merged and will be merge-forwarded to the other branches.

**Comment by max-arnold** [comment]
@dmurphy18 Any news on this one? https://github.com/saltstack/salt/pull/66769

**Comment by dmurphy18** [comment]
@max-arnold replied in https://github.com/saltstack/salt/pull/66769
