### ISSUE TITLE
[BUG] salt-cloud: Missing dependency: 'pyVmomi'

### ISSUE THREAD

**Issue by ZsBT** [saltstack/salt#66979]
**Description**
After a fresh install of salt-cloud, salt-cloud says "The vmware driver requires 'pyVmomi' to be installed."

**Setup**

- Environment: VMware VM: AlmaLinux 8.9 (Midnight Oncilla)
- Salt-cloud version:  3007.1 (Chlorine)
- Python 3.6.8

Salt-cloud provider config: anything with vmware driver.

Python module pyVmomi is already installed, but none of the OS package (python3-pyvmomi-7.0.3-1.el8.noarch), nor the pip3 install helped.

The module can be imported:
```
# python3 -c "import pyVmomi";echo $?
0
```

There are the site packages:
```
# find /usr -iname "*pyvmomi*" -type d
/usr/lib/python3.6/site-packages/pyVmomi
/usr/lib/python3.6/site-packages/pyvmomi-7.0.3-py3.6.egg-info
/usr/share/licenses/python3-pyvmomi
/usr/share/doc/python3-pyvmomi
```
Even with pip3:
```
# find /usr -iname "*pyvmomi*" -type d
/usr/local/lib/python3.6/site-packages/pyVmomi
/usr/local/lib/python3.6/site-packages/pyvmomi-8.0.3.0.1-py3.6.egg-info
```

**Steps to Reproduce the behavior**
```
[root@saltmaster-cloud ~]# salt-cloud --list-images MyProvider
[WARNING ] Missing dependency: 'pyVmomi'. The vmware driver requires 'pyVmomi' to be installed.
[WARNING ] The cloud driver, 'vmware', configured under the 'MyProvider' cloud provider alias, could not be loaded. Please check your provider configuration files and ensure all required dependencies are installed for the 'vmware' driver.
In rare cases, this could indicate the 'vmware.get_configured_provider()' function could not be found.
Removing 'vmware' from the available providers list
Error: There was an error listing images: No cloud providers matched 'MyProvider'. Available selections:
[root@saltmaster-cloud ~]# 
```

**Expected behavior**
Find the dependency that is already satisfied.

**Versions Report**
salt-cloud 3007.1 (Chlorine)

**Comment by dmurphy18** [comment]
@ZsBT salt-cloud is not VMware specific and should not have pyvmomi as a dependency.  Suggest you install saltext.vmware from PyPI which will install pyvmomi as a dependency, this salt extension contains means to interact with VMware.

**Comment by ZsBT** [comment]
Thanks @dmurphy18 , indeed the stock setup does not need VMware dependency. I've just found the AlmaLinux package has its own dedicated python in /opt (onedir approach?), this is why  none of any OS python module install did not have any positive effect.
After installing the module using `/opt/salt*/bin/pip3`, the dependency has been resolved.
I guess this should be mentioned somehow in the docs, at least in the quick start tutorial to make newbies more successful for the first try.
I'd be happy to contribute to add this info in docs/wiki if allowed.

**Comment by dmurphy18** [comment]
@ZsBT ```salt-pip``` is basically ```/opt/salt*/bin/pip3```, hence the easy way to install extensions for the onedir architecture and it is well documented, https://docs.saltproject.io/en/3006/topics/releases/3006.0.html and search for ```salt-pip```, for example.

If this has resolved your issue, please consider closing it, unless there is some other matter.

**Comment by ZsBT** [comment]
Indeed, searching for salt-pip or onedir shows the proper results, however people who are interested in salt-cloud tutorials probably read the [actual and relevant docs](https://docs.saltproject.io/en/master/topics/cloud/vmware.html), instead of investigating all the release notes of the past.
In my case, I fell to this trap, with 5-year memories of SaltStack, remembering the native, venv and onedir approach/era.
Do you think if I fork, fix and send a pull request on the above page linked above, someone will take a look at it and consider merging the proposed changes?

**Comment by dmurphy18** [comment]
@ZsBT Yes, always interesting in improving documentation, code, etc. Mark the PR as a Doc change.

**Comment by ZsBT** [comment]
Thanks, will do so soon. I'm closing this issue as it is not a bug.
