### ISSUE TITLE
[BUG] haproxy + saltstack salt '*' test.ping minions(random) not connected

### ISSUE THREAD

**Issue by iostrovskii1976** [saltstack/salt#66978]
**Description**
In the haproxy + saltstack configuration, some minions (randomly) do not respond the first time with salt ‘*’ test.ping, they give out no connection, when repeated, all minions respond. It has been empirically established that when the minions are idle for more than 15 minutes, this behavior manifests itself. If you run salt ‘*’ test.ping every 12-15 minutes, then everything works well.
Salt version 3006.9/3007

**Setup**
haproxy.cfg
global
    maxconn         2000
    stats socket    /var/run/haproxy.stat mode 600 level admin
    log             127.0.0.1:514 local2
    chroot          /var/empty
    pidfile         /var/run/haproxy.pid
    user            haproxy
    group           haproxy
    daemon

frontend salt-master-pub
mode tcp
bind X.X.X.X:4505
timeout client 3m
default_backend salt-master-pub-backend

backend salt-master-pub-backend
mode tcp
timeout connect 5m
timeout server 10m
server r1 X.X.X.X:4505

frontend salt-master-req
mode tcp
bind X.X.X.X:4506
timeout client 3m
default_backend salt-master-req-backend

backend salt-master-req-backend
mode tcp
timeout connect 5m
timeout server 10m
server r1 X.X.X.X:4506

master
id: X.X.X.X
interface: X.X.X.X
ret_port: 4506
publish_port: 4505
pki_dir: /etc/salt/pki/master
cachedir: /var/cache/salt/master
file_roots:
  base:
    - /srv/salt
pillar_roots:
  base:
    - /srv/pillar
gather_job_timeout: 90
timeout: 60

miniom
id: XXXXXX
master: XXXXX
master_port: 4506
publish_port: 4505
recon_default: 1000
recon_max: 30000
recon_randomize: True

- [X] VM running on a OpenStack
- [X] classic packaging

**Comment by dwoz** [comment]
```
frontend salt-master-pub
mode tcp
bind X.X.X.X:4505
timeout client 3m
default_backend salt-master-pub-backend

backend salt-master-pub-backend
mode tcp
timeout connect 5m
timeout server 10m
server r1 X.X.X.X:4505
```

`timeout server` and `timeout client` for the publish port should be equal to the master's `publish_session` which defaults to `86400` seconds. This is a known issue in our documentation.

**Comment by iostrovskii1976** [comment]
Thank you, that was helpful.
