### ISSUE TITLE
[BUG] bootstrap-salt.sh script doesn't work with new repo (bootstrap-salt.sh -R packages.broadcom.com)

### ISSUE THREAD

**Issue by rahulskumbhar1997** [saltstack/salt#67014]
As per the release notes the salt repo `repo.saltproject.io` is going to be changed to `packages.broadcom.com` by end of October. However the `bootstrap-salt.sh` still holds all the URL path which are valid only for old `repo.saltproject.io` repo. The URL path mentioned doesn't work for new repo `packages.broadcom.com`. Below are some details from `bootstrap-salt.sh` script highlighting URL path of old repo.

file: `bootstrap-salt.sh`
method: `__install_saltstack_rhel_onedir_repository()`
details: The URL path mentioned in variable `base_url` is not valid if we use new repo `packages.broadcom.com`.

Due to this even if we explicitly pass repository as CLI argument to `bootstrap-salt.sh` (-R cli argument) script it is failing to install the salt. Below is sample command used and the error shown.

Command:
`bootstrap-salt.sh -R packages.broadcom.com -P -x python3 stable 3006`

Error: 
```
 *  INFO: Running install_red_hat_enterprise_linux_onedir_deps()
 *  WARN: Detected -r or -R option while installing Salt packages for Python 3.
 *  WARN: Python 3 packages for older Salt releases requires the EPEL repository to be installed.
 *  WARN: Installing the EPEL repository automatically is disabled when using the -r or -R options.
SaltStack latest Release Channel for RHEL/CentO 108  B/s |  74  B     00:00
Errors during downloading metadata for repository 'saltstack':
  - Status code: 404 for https://packages.broadcom.com/salt/py3/redhat/8/x86_64/minor/3006.8/repodata/repomd.xml (IP: 44.226.59.123)
Error: Failed to download metadata for repo 'saltstack': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried
Ignoring repositories: saltstack
```

After this migration of repo, if the older repo `repo.saltproject.io` is no longer available then the bootstrap-salt.sh script will not work. We will be completly blocked.

**Comment by ScriptAutomate** [comment]
See new issue that has been made in the `salt-bootstrap` repo:
- https://github.com/saltstack/salt-bootstrap/issues/2027

**Comment by kristoffertt** [comment]
Hey. 
TurtleTraction (www.turtletraction.com) has mirrored saltproject repos. These mirrors are now available to help you smooth the process. 

https://repo.saltproject.io.turtletraction.com/ 
https://archive.repo.saltproject.io.turtletraction.com/ 

Please handle with care and avoid pointing a large number of Salt Minions to it. 
As always, if you have any issues teach out to us on support@turtletraction.com or directly to me here.
Please, share the word in order to avoid interruption of others.
