### ISSUE TITLE
[BUG] unable to sync repositories on packages.broadcom.com

### ISSUE THREAD

**Issue by mguidry3** [saltstack/salt#67025]
**Description**
repo.saltproject.io repositories were generated with filelists. It looks like the new repo at packages.broadcom.com do not.
This prevents mirroring from standard tools such as Redhat Satellite.

**Setup**
compare the repomd.xml from the two repositories. no filelist in the new one

Please be as specific as possible and give set-up details.

- [ ] on-prem machine
- [ ] VM (Virtualbox, KVM, etc. please specify)
- [ ] VM running on a cloud service, please be explicit and add details
- [ ] container (Kubernetes, Docker, containerd, etc. please specify)
- [ ] or a combination, please be explicit
- [ ] jails if it is FreeBSD
- [x ] classic packaging
- [ ] onedir packaging
- [ ] used bootstrap to install

**Expected behavior**
Filelists should be included in rpm repository at least.

</details>

**Additional context**

**Comment by dmurphy18** [comment]
@mguidry3 You have marked classic packages and with the move to packages.broadcom.com, these are no longer supported.  All of classic packaging is End-Of-Life and no longer supported, and old processes such as rsync are no longer valid with the infrastructure changes which have been mandated by Broadcom.

Please see

**Comment by ScriptAutomate** [comment]
Tracking an issue in Salt Install Guide, in the meantime, for newer 3006 LTS and 3007 STS (non-classic) packages:
- https://github.com/saltstack/salt-install-guide/issues/8
