### ISSUE TITLE
[GITHUB] Typo in github repo tags

### ISSUE THREAD

**Issue by blu-base** [saltstack/salt#67042]
One of the tags of this repository's about column has a typo. It's likely that `infrasructure` (https://github.com/topics/infrasructure) was supposed to be `infrastructure`
![image](https://github.com/user-attachments/assets/07316031-1ca9-492d-866c-23f9037ee8d2)

![image](https://github.com/user-attachments/assets/109f5cb1-d0b0-4124-9db8-a81728da8ea1)

**Comment by ScriptAutomate** [comment]
I have updated. This means that Salt is no longer the one and only champion of [`infrasructure`](https://github.com/topics/infrasructure) on GitHub.

Though I have decided to leave it in fierce competition among a few other projects under [`infrastructure-as-a-code`](https://github.com/topics/infrastructure-as-a-code), which I imagine must be Mario's tech stack.
