### ISSUE TITLE
[BUG] Unable to install salt-minion on Debian

### ISSUE THREAD

**Issue by odubuc** [saltstack/salt#67040]
**Description**
```
apt update
apt install salt-minion
```

doesn't work anymore

**Setup**
Simple Debian VM or even WSL

**Steps to Reproduce the behavior**
```
apt update
apt install salt-minion
```

**Expected behavior**
it should install salt-minion as usuall

**Screenshots**
![image](https://github.com/user-attachments/assets/bec62d6b-89d8-4f07-99bb-d1508f66aaf9)

**Comment by llamontagne666** [comment]
Same here

**Comment by llamontagne666** [comment]
dig repo.saltproject.io

; <<>> DiG 9.16.50-Debian <<>> repo.saltproject.io
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 16504
;; flags: qr rd ra; QUERY: 1, ANSWER: 1, AUTHORITY: 1, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 512
;; QUESTION SECTION:
;repo.saltproject.io.           IN      A

;; ANSWER SECTION:
repo.saltproject.io.    30      IN      CNAME   d39c38qjhaa4za.cloudfront.net.

;; AUTHORITY SECTION:
cloudfront.net.         30      IN      SOA     ns-418.awsdns-52.com. hostmaster.cloudfront.net. 1377556270 16384 2048 1048576 60

;; Query time: 284 msec
;; SERVER: 172.20.16.4#53(172.20.16.4)
;; WHEN: Wed Nov 06 15:02:58 UTC 2024
;; MSG SIZE  rcvd: 158

**Comment by odubuc** [comment]
I just saw the migration message. in the documentation... I'm closing this issue

> IMPORTANT ANNOUNCEMENT: repo.saltproject.io has migrated to packages.broadcom.com!

**Comment by odubuc** [comment]
re-opening the issue just to get confirmation where this is going. I'm reading the migration plan and I'm unsure of the outcome of this. looking at the current DNS progagation, I can see it isn't complete.

**Comment by jheiselman** [comment]
From the screenshot, @odubuc is not using the Salt package repository. Neither repo.saltstack.io nor packages.broadcom.com are listed in the output from the apt update command. Debian no longer includes the salt packages in their repositories since bullseye. You will need to setup the Broadcom repositories as documented in the migration announcement.

**Comment by dmurphy18** [comment]
Closing this, since read the Salt Install Guide which has been updated, https://docs.saltproject.io/salt/install-guide/en/latest/

**Comment by odubuc** [comment]
> Debian no longer includes the salt packages in their repositories since bullseye.

@jheiselman, This is exactly what I was looking for and the reason I left this open. Thank you for confirming. have a nice day.
