### ISSUE TITLE
Expect support in salt stack

### ISSUE THREAD

**Issue by majo83** [saltstack/salt#6712]
Hey folks,

I recently learned about the very cool unix utility expect, which is basically a tool script a unix terminal (and not just just the shell, like in a ordinary shell script). See here http://manpages.ubuntu.com/manpages/hardy/man1/expect.1.html . It's very handy to automate install dialogs and the like, and I am surprised that also other config-management solutions (like e.g. puppet) seem to lack proper support for that tool.

I think that would be a very handy together with salt stack. There's also a python version lying around here: http://sourceforge.net/projects/pexpect/ 

See also here: http://en.wikipedia.org/wiki/Expect

Best regards,
majo83

**Comment by arroyoc** [comment]
I am closing this ticket due to inactivity. If anyone feels that this feature needs more attention feel free to reopen it.
