### ISSUE TITLE
Handling restarts and the continuation of jobs.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#6792]
This issue comes from the IRC where a discussion sprung up on the best way to handle reboots for updates or other tasks. As an example I need to perform the following actions:

1. Rename a file to pull it from a load balancer.
2. Update a package.
3. Reboot the server.
4. Run highstate to put the file back in place, or perform other tasks.

When broken down really what I'd like to accomplish (to cover more use cases) is to:

1. Perform a task.
2. Reboot the server.
3. Run highstate on that server.

We discussed the idea of using both overstate, as well as states.over, but ran into concerns regarding the shutdown/reboot process where another command could be inserted between the time a shutdown/reboot command is issued, and when the machine actually starts killing processes, so a highstate could be in the middle of running during the reboot, and be marked as complete, thus never running when the machine comes back up.

Are there plans to implement something that would allow for the application of a highstate, or continuation of jobs after the reboot is complete? Or perhaps we're missing something and a solution to this use case already exists?

**Comment by gravyboat** [comment]
@whiteinge Can we close this now? Does the PR from last year fully resolve this? #15212 is still open.

**Comment by whiteinge** [comment]
A better interface for making a one-off startup state would still be a good addition but I think you're right that we can close this now.
