### ISSUE TITLE
Peer system

### ISSUE THREAD

**Issue by malinoff** [saltstack/salt#6797]
I am not sure is it possible, but anyway...

That would be awesome if i could match minions in the master config peer section not only by id regex, but by grain. Or anything else.

As i see this on a minion:
```
salt-call publish.publish 'some-minions*' test.ping match='G@roles:webnode'
```

In the master config:
```
peer:
  'roles: webnode':
    - match: grain
    - test.ping
```

So, any minion who has 'roles:webnode' grain can publish test.ping command.

**Comment by The-Loeki** [comment]
I think this is in now with the `expr_form` supported in `publish`?

**Comment by basepi** [comment]
It is! Good find, @The-Loeki, I'm going to go ahead and close this one.
