### ISSUE TITLE
cmd.run env= needs syntax warnings

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#6799]
Markedly different output when you don't give correct yaml to the env for cmd/run:

```
root@salt-master:/home/salt/conf/php/conf.d# salt idd* cmd.run env="EDITOR:sed" cmd='echo $EDITOR'
idd0012:

idd0014:

```

vs.

```
root@salt-master:/home/salt/conf/php/conf.d# salt idd* cmd.run env="EDITOR: sed" cmd='echo $EDITOR'
idd0012:
    sed
idd0014:
    sed
```

There's a space missing in the first example, but there's no error warning you for invalid yaml.

**Comment by CHgsd** [comment]
Interestingly, neither is working for me. I am not sure if this is a bug or an oversight on my part:
```bash
# salt 'testhost' cmd.run env="TEST: hello" cmd='echo $TEST'
testhost:
# salt 'testhost' cmd.run env="TEST:hello" cmd='echo $TEST'
testhost:
#
```
Is this related or a separate issue? Thanks!

**Comment by Mrten** [comment]
Heh, both my examples don't work for me either anymore ;) so you're not alone. @basepi? I don't see anything in the [docs](https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.cmdmod.html) that changed?

Tried cmd.shell, python_shell=True, clean_env=True, etc.
```
root@salt-master:/home/mrten# salt acme cmd.shell 'export' env="EDITOR: sed" clean_env=True
acme:
    export LC_ALL='C'
    export PWD='/root'
```
should show an `EDITOR` var, as far as I can see.
