### ISSUE TITLE
salt.modules.gem.install ignores ruby parameter if rvm is installed locally and runas is provided

### ISSUE THREAD

**Issue by davepeck** [saltstack/salt#6815]
To reproduce with `salt 0.16.3`:

1. Install `rvm` locally for a user (say, `rvmuser`) not systemwide (say, in the user's `$HOME/.rvm/...`)
2. Install a ruby (say `1.9.3`) and create a test gemset (say `testgemset`)
3. As root, `salt-call gem.install ruby=1.9.3@testgemset runas=rvmuser some_gem`

Actual result: 

`some_gem` is installed in the `default` gemset.

Expected:

`some_gem` should be installed in `testgemset` instead.

I have a guess where things go wrong. The `modules/gem.py::_gem()` method inspects `__salt__['rvm.is_installed']()` to decide whether to install the gem with `rvm.do`, but unfortunately, it seems to be testing `rvm.is_installed` for the current user, not the `runas` user. If `rvm` is installed locally rather than systemwide, it seems like this will break? This is my first 5 minutes looking at salt's code, so I'm likely missing something.

**Comment by sergvag** [comment]
rvm module is out of sync with rvm:
xecuting command "/usr/local/rvm/bin/rvm '2.2.0 do gem list rails'" in directory '/root'
2015-03-10 16:20:20,080 [salt.loaded.int.module.cmdmod][INFO    ] Executing command "/usr/local/rvm/bin/rvm '2.2.0 do gem install rails  --no-rdoc --no-ri'" in directory '/root'
2015-03-10 16:20:21,734 [salt.state       ][ERROR   ] Could not install gem.
If I try to use command on my shell: 
#rvm '2.2.0 do gem install rails'
ruby-2.2.0-rails is not installed.
To install do: 'rvm install ruby-2.2.0-rails'

It is clearly rvm module invokes rvm incorrectly.
