### ISSUE TITLE
GUI and enhancement SaltStack to add Workflow for orchestrating the execution of package functions local on master or remote on minions

### ISSUE THREAD

**Issue by asyafoek** [saltstack/salt#6819]
Can we add something like a orchestration library, were each step is executing a package functions. for each step you can mark if it must be executed on the master or on the minion. I understand this is an enhancement for the total Salt Stack as a solution. But the orchestration part requires a GUI to be friendly and usable.

It this way you can define patch procedures (e.g. orchestrations) and the target were this needs to be executed and exactly which steps in which order.

Please let know how to add this als an Enhancement for Salt.

This concept is also available in commercial products like Symentic Altiris, HP Rapid Deployment Pack, IBM Tivoli, Computer Associates Nolio. This improves the capability to not only provision Infrastructure and do patch management more efficient, But will also be usefull for Continous Deployment of Application and Service Components on Middleware products like TIBCO, SoftwareAG, IBM, JBoss.

**Comment by basepi** [comment]
SaltStack now has an enterprise offering that provides a GUI: https://saltstack.com/saltstack-enterprise/
