### ISSUE TITLE
propose: pkg.wait

### ISSUE THREAD

**Issue by shadowfax-chc** [saltstack/salt#6823]
This would be analogous to the `cmd.wait` but for pkg. It would install (or reinstall) the package based on a `watch`.

The motivation for this come from the following senario:

Under Gentoo, sudo is desired with the `ldap` use flag. Thus the following state is crafted:

    app-admin/sudo:
      portage_config.flags:
        - use:
          - ldap
      pkg.installed:
        - require:
          - portage_config: app-admin/sudo

This would work if sudo is not already installed. However, if sudo is installed, the use flags are set but sudo is not rebuilt to include `ldap`.

However, if the following state could be created:

    app-admin/sudo:
      portage_config.flags:
        - use:
          - ldap
      pkg.wait:
        - watch:
          - portage_config: app-admin/sudo

It would rebuild sudo when the use flags change.

I'm not sure if this helps any other distros, but it would be very useful for managing Gentoo.

**Comment by terminalmage** [comment]
Implemented in https://github.com/saltstack/salt/pull/29582
