### ISSUE TITLE
Salt formulas should be way more visible in the documentation

### ISSUE THREAD

**Issue by Psycojoker** [saltstack/salt#6853]
Hello,

[Salts formulas](http://docs.saltstack.com/topics/conventions/formulas.html) are very cool but totally absent from the documentation: they aren't on the [main page](http://docs.saltstack.com/index.html) nor in the introductions tutorials and this is very uncool.

I've discovered them randomly browsing [this page](http://docs.saltstack.com/contents.html). Ironically, I've been looking for a way to distribute and reuse salt states/modules/others and haven't been able to find it using the current documentation a search for "distribute salt states".

So salt formulas must be made way more visible and maybe mentioned in the introduction tutorials.

Kind regards,

**Comment by rallytime** [comment]
Fixed by #30215.
