### ISSUE TITLE
network state should set PERSISTENT_DHCLIENT

### ISSUE THREAD

**Issue by jpeach** [saltstack/salt#6857]
The network state should enable PERSISTENT_DHCLIENT on DHCP interfaces, or provide an option to enable this setting. This is setting is very useful to keep the DHCP client alive after the first DHCP failure.

**Comment by chnrxn** [comment]
I am not able to find PERSISTENT_DHCLIENT even in the latest 4dd22f54d0. What needs to be done to move this forward?
