### ISSUE TITLE
Rename salt keys

### ISSUE THREAD

**Issue by wichert** [saltstack/salt#6896]
On rare occasions I need to repurpose a server for something else. It would be practical if it was possible to rename the key.

**Comment by Vehyla** [comment]
:+1:

**Comment by sirshurf** [comment]
:+1:

**Comment by marclop** [comment]
:thumbsup:

**Comment by MrMarvin** [comment]
:+1:

**Comment by tkent-xetus** [comment]
:+1:

**Comment by ghostsquad** [comment]
+1

**Comment by iamfil** [comment]
:+1:

**Comment by badele** [comment]
:+1:

**Comment by CosminG** [comment]
+1

**Comment by thatch45** [comment]
@SaltDBray let's try to get thin into boron.

**Comment by rhansen** [comment]
:+1:

**Comment by dhpowrhost** [comment]
:+1:

**Comment by zerthimon** [comment]
Very +1!!! It would be great to have a way to "rename" a server (change it's hostname) without this hassle:

{quote}
a) delete old key on master, b) delete key on minion, c) change id on minion and generate a new key for it, d) accept new key on master.
{quote}

**Comment by zzzuzik** [comment]
:+1:

**Comment by taogogo** [comment]
👍

**Comment by lubyou** [comment]
👍🏻

**Comment by kemadz** [comment]
+1

**Comment by james-daniel** [comment]
:+1:

**Comment by kissifrot** [comment]
👍

**Comment by ryanmaclean** [comment]
👍

**Comment by joadha** [comment]
👍

**Comment by Reiner030** [comment]
:+1:

**Comment by Moulde** [comment]
👍

**Comment by LumbaJack** [comment]
👍

**Comment by christianvv** [comment]
+1

**Comment by jcalderin** [comment]
👍

**Comment by markuskramerIgitt** [comment]
+1

**Comment by gfraetis** [comment]
+ 1

**Comment by psyna** [comment]
+100500

**Comment by Helmi-helmutson** [comment]
+1

**Comment by adamsewell** [comment]
+1

**Comment by jfoboss** [comment]
+1

**Comment by jfoboss** [comment]
Workaround script:
```
#!/bin/bash

function usage() {
    cat << EOF

Usage: $0 old-id new-id

EOF
}

if [ $# -eq 0 ] ; then
    usage
    exit 1
fi

OLD=$1
NEW=$2

salt $OLD test.ping && salt $OLD cmd.run "echo $NEW > /etc/salt/minion_id"
salt $OLD service.restart salt-minion
mv -f /etc/salt/pki/master/minions/$OLD /etc/salt/pki/master/minions/$NEW
echo "Waiting 10 sec..."
sleep 10
salt $NEW test.ping # check if new host works
```

**Comment by dafyddj** [comment]
not stale

**Comment by speedytom** [comment]
I have tried script from this comment:
 "jfoboss commented on Feb 14, 2019"


I gets this error message:
    Minion did not return. [No response]
    The minions may not have all finished running and any remaining minions will return upon completion. To look up the return data for this job later, run the following command:
    
    salt-run jobs.lookup_jid 20210506103249534555

root@salt:/srv/salt# salt --versions-report
Salt Version:
          Salt: 3002.5
 
Dependency Versions:
          cffi: Not Installed
      cherrypy: Not Installed
      dateutil: 2.7.3
     docker-py: Not Installed
         gitdb: 2.0.6
     gitpython: 3.0.7
        Jinja2: 2.10.1
       libgit2: Not Installed
      M2Crypto: Not Installed
          Mako: Not Installed
       msgpack: 0.6.2
  msgpack-pure: Not Installed
  mysql-python: Not Installed
     pycparser: Not Installed
      pycrypto: Not Installed
  pycryptodome: 3.6.1
        pygit2: Not Installed
        Python: 3.8.5 (default, Jan 27 2021, 15:41:15)
  python-gnupg: 0.4.5
        PyYAML: 5.3.1
         PyZMQ: 18.1.1
         smmap: 2.0.5
       timelib: Not Installed
       Tornado: 4.5.3
           ZMQ: 4.3.2
 
System Versions:
          dist: ubuntu 20.04 focal
        locale: utf-8
       machine: x86_64
       release: 5.4.0-70-generic
        system: Linux
       version: Ubuntu 20.04 focal

**Comment by waynew** [comment]
Hey all, thanks for the discussion on this issue! We realize that it's been
open for quite a while and might be something that would have been a good idea
at the time, but after discussion with the core team, this issue no longer
seems relevant, and we're going to close it out. 

Our understanding is that the main reason to support renaming keys is that one
may have a particular name that identifies its role, and that name may change,
e.g. `mailserver.example.com` -> `webserver.example.com`. The desire is that it
would be possible to rename the minion key.

While there are use cases that would find this feature valuable, they're not
really very good practice. The entire reason that Salt exists is to enable
phoenix servers - burning it down and let them rise from the ashes.

There are several features that can be utilized:

- [Salt Cloud][salt-cloud], if you're using AWS, GCE, or Azure allows you to
  burn down/spin up new minions more or less on demand.
- Using [role grains][role-grains] to specify the role of the minion.
- Just use Salt and minion ID matching in the state top file.

But the consideration that weighs more heavily is that the keys are a
significant part of Salt's security model, and adding an API to easily change
the keys increases Salt's attack surface, which is undesirable.

If anyone still feels strongly that this *should* be a feature, at this point
we'd ask you to create a [Salt Enhancement Proposal][SEP] detailing why this is
a feature that we would want to support, and why none of the existing models or
workarounds are sufficient.

[salt-cloud]: https://docs.saltproject.io/en/latest/topics/cloud/index.html
[role-grains]: https://docs.saltproject.io/en/latest/topics/grains/index.html#grains-in-the-minion-config
[SEP]: https://github.com/saltstack/salt-enhancement-proposals/
