### ISSUE TITLE
[FreeBSD] status module doesn't work as expected

### ISSUE THREAD

**Issue by cedwards** [saltstack/salt#7119]
The only data returned by the status module is ``loadavg`` and ``uptime``:

```yaml
[root@starbuck ~]# salt 'ariel' status.all_status
ariel:
    ----------
    cpuinfo:
        ----------
    cpustats:
        ----------
    diskstats:
        ----------
    diskusage:
        ----------
    loadavg:
        ----------
        1-min:
            0.85400390625
        15-min:
            0.89111328125
        5-min:
            0.92724609375
    meminfo:
        ----------
    netdev:
        ----------
    netstats:
        ----------
    uptime:
         8:23AM  up 17 days, 59 mins, 0 users, load averages: 0.85, 0.93, 0.89
    vmstats:
        ----------
    w:

**Comment by kim0** [comment]
@terminalmage @basepi  I've ported the status module to FreeBSD, so this bug can be closed I suppose

**Comment by rallytime** [comment]
Sounds good @kim0 - thanks for fixing that. Mind linking the PR that this was fixed in?

@cedwards If you still see problems with this, let us know and we can re-open, but I am going to close this out for now.

**Comment by kim0** [comment]
Every method was its own PR really .. The last method was #20397

**Comment by rallytime** [comment]
Ah, ok. Thanks for posting the last one at least. :)
