### ISSUE TITLE
Salt Mine needs a function to flush contents

### ISSUE THREAD

**Issue by sbworth** [saltstack/salt#7226]
Once entered into the mine via mine.send, there is no function to remove data. We need some new functions, perhaps invoked along the lines of:

```
mine.flush module.function

mine.flush_all
```

If we can insert functions with arguments, then we will need to be able to distinguish

```
mine.flush network.interfaces
```

from

```
mine.flush network.interfaces eth0
```

I don't know any of the implementation details; so if the data is not tagged in any way to associate it with the function that generated it, we need to either introduce that into the data structures or opt for key-based rather than function-based eviction.

The ability to evict individual entries from the pillar might be useful in any event, in order to permit reshaping of mine contents. For example, the available functions may return a superset of the data actually wanted. While we could write a new module.function to return precisely the desired data, this will seem like overkill to the individual who wants 239 out of the 241 key-value pairs returned by an already existing function.

To delete the disk usage data returned for `/dev/shm` from all hosts:

```
salt@master#  salt-call mine.delete '*' disk.usage /dev/shm
```

I tend to think of `flush` as more coarse-grained than `delete`. The most natural API will be greatly affected by details of the mine data structure of which I currently remain ignorant.

**Comment by dmaze** [comment]
Even with the ``mine.delete`` and ``mine.flush`` execution modules, there's no way to delete mine content from a minion that's no longer running.  I was expecting to find a runner to reset the mine contents or something along those lines.

**Comment by dlanderson** [comment]
@dmaze check http://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.cache.html#salt.runners.cache.clear_mine

**Comment by dmaze** [comment]
@dlanderson That does look like exactly what I was looking for, thanks!

**Comment by timwsuqld** [comment]
@dmaze @dlanderson 
Not sure if either of you can help. I'm having a problem with mine data still being cached.
```salt 'email-relay' mine.get 'roles:postfix_client' network.ip_addrs grain``` still returns data from a host I've now removed. I've tried the following
```
salt-run cache.clear_mine_func tgt='*' clear_mine_func_flag='network.ip_addrs'
salt-run cache.clear_mine tgt=email-relay
salt-run cache.clear_mine tgt=DELETEDSERVER
```

Any pointers as to how I fix this?
```
$ salt --version
salt 2015.8.8.2 (Beryllium)
```
