### ISSUE TITLE
Feature request - add configurable scheduler random time slew to avoid simultaneous execution scenarios.

### ISSUE THREAD

**Issue by eugenea** [saltstack/salt#7324]
Please make scheduler random slew configurable from scheduler config.
For example slew: 5%. This will be added/substracted to schedule interval to avoid simultaneous execution. THe initial slew for first execution should be 100% (i e random within execution interval).

**Comment by eliasp** [comment]
Until this is implemented, [this article](http://bencane.com/2014/05/19/using-saltstack-to-update-all-hosts-but-not-at-the-same-time/) outlines various approaches on how to distribute the load across the Salt infrastructure.

**Comment by The-Loeki** [comment]
I think the current `splay` covers this? https://docs.saltstack.com/en/latest/ref/states/all/salt.states.schedule.html

> *splay*
> The amount of time in seconds to splay a scheduled job. Can be specified as a single value in  seconds or as a dictionary range with 'start' and 'end' values.
