### ISSUE TITLE
state.highstate random but frequent hangs on CentOS 6

### ISSUE THREAD

**Issue by gvansanden** [saltstack/salt#7347]
I installed Saltstack on both Ubuntu and CentOS (6.4).  On CentOS, initiating a state.highstate results in random hangs on the minions shown with state.running:

 - The function "state.highstate" is running as PID 18383 and was started at 2013, Sep 05 16:49:30.883503 with jid 20130905164930883503

I can clear it by logging in to the minion and killing that process, but during each run about 4 out of my 8 minions hang.  This is a new setup with very little to do but copy authorized_keys.

**Comment by steverweber** [comment]
inactivity.. resolved?

**Comment by udhayprakash** [comment]
I too faced the same problem. I solved it by updating the salt-minion(s), to that of salt-master. 

`salt '*' cmd.run "yum update salt"`
