### ISSUE TITLE
Make the secondary check-in timeout for salt commands configurable

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#7354]
We can currently configure the initial timeout for salt commands (before the master starts checking with minions) using the `-t` flag.  We should also make the secondary timeout (hardcoded to 2 currently?) configurable, both with a command line arg and a configuration option in the master config.

This will help a lot with long jobs in low-latency conditions.  (like #6881)

**Comment by solugebefola** [comment]
Hi there,
I am newly arrived from CodeTriage.  Can you tell me the specific file that contains the code for the timeouts for salt commands?  Thanks

**Comment by basepi** [comment]
All of the command line parsing into salt config values happens in https://github.com/saltstack/salt/blob/develop/salt/utils/parsers.py
