### ISSUE TITLE
Remove M2Crypto dependency

### ISSUE THREAD

**Issue by multani** [saltstack/salt#7413]
In #1112 , M2Crypto was removed in favor of PyCrypto but in bdb9dce5b81933927f58ca9a8783fdfc0fe7cdd2 and parents, it has been switched back for some reasons (I suspect 1e3754878cb2ba95aaea64c6360a219642003a46 to be the main culprit?)

As said in #1112 M2Crypto has lot of issues which makes it a pain to install and use.

In https://github.com/saltstack/salt/pull/3933#issuecomment-24531943, @basepi seemed to say it wasn't such a problem to remove M2Crypto once again.

I can probably volunteer some time for this task, if it's still on the roadmap and if the main developers of Salt aren't against it (@thatch45 if you still remember why you switched back from PyCrypto to M2Crypto, that would be good to know!)

**Comment by tdsmith** [comment]
It looks like this was accomplished in #23348. :tada:

**Comment by basepi** [comment]
It is indeed! We're super excited!

**Comment by AnneTheAgile** [comment]
Wow!! Great work!

**Comment by multani** [comment]
Awesome :+1:
