### ISSUE TITLE
feature: salt tls module ssl check

### ISSUE THREAD

**Issue by aboe76** [saltstack/salt#7424]
I would like to see an extension to the tls module with:
- certificate expiration date
- validity check

something allong the lines of:
https://gist.github.com/crashdump/5683952

that way we can monitor https/ssl certificate from within salt.

**Comment by QuinnyPig** [comment]
Where is this sitting today? It would be awesome to have nodes able to check cert expiry on their neighbors / ELBs...

**Comment by terminalmage** [comment]
I checked and we already had code in the module that was getting the cert expiration date, so I abstracted that to a helper function and then used that helper function to expose this functionality in a new function `tls.get_expiration_date`. The pull request that adds this new function is https://github.com/saltstack/salt/pull/46922.

As for validation, I don't know pyOpenSSL well enough to do that, would someone else like to tackle it?
