### ISSUE TITLE
Feature: 'ENC'/plugin enforced environments/custom SLS paths (multi-tenant support)

### ISSUE THREAD

**Issue by rmt** [saltstack/salt#7556]
As an extremely large scale user with a CMDB managing "what should be running where" across thousands of nodes with hundreds of unique applications managed by dozens of untrusted teams, I want to be able to dynamically specify and enforce the environment by specifying the fileserver plugin AND the node's environment on the Salt Master using an external script or plugin, so that I can properly isolate the applications and nodes from one another using an external authoritative source, as well as easily manage change control requirements of production nodes.

With puppet, this can be more or less achieved by using modulepath = /path/to/environments/$environment and specifying the environment in the Puppet ENC then managing these paths outside of Puppet.

It would be ideal if you could specify multiple paths (eg. a combination of formulae paths), as this would permit proper versioning of a single app's state and all of its dependencies.

Or maybe this could maybe be broken down into separate requirements:
  * Enforcing a node-specific environment server-side.
  * Dynamic environment support.
  * A custom fileserver to lookup files in the environments.
  * Optionally checking whether a node has access to an environment when it requests files. Optional because it'd be a performance hit and not required at every site.

**Comment by bechtoldt** [comment]
Right, this is now possible with Salt using the Master Tops system:

* http://docs.saltstack.com/en/latest/ref/tops/index.html
* http://docs.saltstack.com/en/latest/ref/tops/all/index.html

**Comment by basepi** [comment]
Yep, I think this can be closed because of master tops.
