### ISSUE TITLE
salt thin packaged as salt-common

### ISSUE THREAD

**Issue by joehealy** [saltstack/salt#7653]
salt thin in the 0.17.0 release notes is packaged as salt-common

This is probably confusing for most people, but probably also hard to change.

I know in debian, it will require another pass through the NEW queue to change.

Maybe all that is needed is a mention in the release or other spots or maybe longer term it is worth changing the packaging...

**Comment by jacobhammons** [comment]
It looks like there is a runner now to generate salt-thin, https://docs.saltstack.com/en/latest/ref/runners/all/salt.runners.thin.html#module-salt.runners.thin

@joehealy does this solve the issue? Thanks.
