### ISSUE TITLE
Add a flag to suppress detailed summary for salt states execution (salt-0.17.0 onward)

### ISSUE THREAD

**Issue by mlister2006** [saltstack/salt#7664]
Per discussion https://groups.google.com/forum/#!searchin/salt-users/7664/salt-users/J0DxqY4iHlI/xsYZ4k4PgJcJ
Requesting a flag (command line or config file) to suppress detailed summary when executing salt states. Very much like pre salt-0.17.0 style reporting

**Comment by richardhansen** [comment]
:+1:
