### ISSUE TITLE
Unclear --subset option for salt, should be --random ? or --first-n-returns ? 

### ISSUE THREAD

**Issue by arthurlogilab** [saltstack/salt#7672]
This was discussed at the SaltStack meetup in France. 

salt  \* --subset 3 test.ping only get only 3 results. But the timeout is  still the same since it waits for all results to be back and gets a  random subset. Someone in the crowd was expecting the first 3, with no timeout. 

Maybe replace --subset by --random and add --first-n-returns (or something better).

**Comment by jacobhammons** [comment]
The docs were updated for --subset, https://docs.saltstack.com/en/latest/ref/cli/salt.html#cmdoption-salt--subset

I'm going to close this.
