### ISSUE TITLE
feature request: profile state.highstate on the minion

### ISSUE THREAD

**Issue by Mrten** [saltstack/salt#7694]
I'd like to know why my highstate is taking the time that it takes so that I perhaps can make an update here-or-there, or leave out states that take a long time.

I realize that this is a 'perhaps in version 4.x' feature ;)

**Comment by Mrten** [comment]
State timing is in the highstate info on the master, timing is in the info log on the slave, are there more ideas where timing can be put?

**Comment by Mrten** [comment]
@basepi? what do you think? is this one done?

**Comment by basepi** [comment]
I think we've had timing for years now so yes, I think this can be closed.
