### ISSUE TITLE
network.managed sets wrong mac addresses for bonded NICs

### ISSUE THREAD

**Issue by jeagle** [saltstack/salt#7743]
When network.managed runs for an interface on a Red Hat-ish system, it creates the ifcfg-ethX file and in that file places the HWADDR line containing that interface's hardware address.

However, when a link bond is created (at least in LACP mode under the default settings), all interfaces in the bond are assigned the mac address of the first interface. If the salt state runs network.managed for any slave interface, it will write that changed mac address to the ifcfg-ethX file. The end result is every ifcfg-ethX file has the same HWADDR in it, and the next time the machine boots it will refuse to process the ifcfg-ethX file because the HWADDR is incorrect.

I don't have a good suggestion for how to fix this. Maybe detect the interface is a slave and don't set the HWADDR? Or use a different method to detect the permanent hardware address? Or give an option to network.managed to not set the HWADDR for a given interface, and users can set that on bond slaves?

**Comment by nzurku** [comment]
I'm having this same issue now. Slave interfaces are getting what appears to be bogus MACs and they're not working at all.

Simply removing the HWADDR line from the ifcfg-bondX file and bouncing the network stack fixes the issue.

Is there any way we can just get a method for disabling the HWADDR changes to an interface?
