### ISSUE TITLE
salt/auth/pam.py outdated

### ISSUE THREAD

**Issue by joehealy** [saltstack/salt#7747]
The upstream (from salt) library that has been included (almost verbatim) for pam has released a new version, presumably fixing some bugs/issues.

It appears that the currently included code is based on version 0.1.3 and 0.1.4 has been released.

This should be updated or removed and added as a dependency.

I would be in favour of removing it, as the package is available in debian unstable and should be easy enough to backport to the required releases. I don't know about other distros though.

I also think that the less copy/paste code we have lying around the better.

The actual salty bit required for pam authentication is tiny!

Thanks,

Joe

**Comment by aletourneau** [comment]
I submitted a pull request which includes pam's 0.1.4 copy/pasted code: #22895

**Comment by cachedout** [comment]
@aletourneau Awesome! Thanks.
