### ISSUE TITLE
Roster system should incorporate all minions, not just salt-ssh minions.

### ISSUE THREAD

**Issue by dangarthwaite** [saltstack/salt#7759]
The roster system seems to be a great place to stick a generated, up to date, roster of all minions, including their grains data.  That a particular machine is minionless and must be contacted via salt-ssh should just be another grain associated with that minion.

Feasible?

**Comment by The-Loeki** [comment]
@dangarthwaite your RFE should be fully addressed with my PR #39050 @rallytime I think you can close this one now?

**Comment by dangarthwaite** [comment]
👍

**Comment by rallytime** [comment]
Yeah, for sure. Thanks @The-Loeki!
