### ISSUE TITLE
PKI external_auth

### ISSUE THREAD

**Issue by drawsmcgraw** [saltstack/salt#7791]
What would a PKI `external_auth` look like? Would you pass it a DN from a user's cert? The email address? What configs would it need? 

I'm thinking more of how a PKI login would work for Halite (from https://github.com/saltstack/halite/issues/48) than managing user permissions for issuing the `salt` command. This would make Halite implementation for large enterprises running their own PKI ecosystem much easier.

**Comment by kottenator** [comment]
Have you tested it on the latest version? I can't get it work...

**Comment by drawsmcgraw** [comment]
@kottenator Can you describe how you're testing it and what you're seeing?

**Comment by kottenator** [comment]
I configure `pki` auth in master config:

```yaml
external_auth:
  pki:
    ca_file: /path/to/root-ca.pem
```

Then I try to execute:

```bash
salt -a pki --pem="`cat user.crt`" '*' test.ping
```

It gives an error: **no such option: --pem**

How can I pass the certificate?

**Comment by drawsmcgraw** [comment]
@kottenator Salt may not be recognizing the 'pki' eauth option. I'm seeing this in the man page:

```
       -a EAUTH, --auth=EAUTH
              Pass in an external authentication medium to validate against. The credentials will be prompted for. The options are auto, keystone, ldap, pam, and stormpath. Can be used with the -T option.
```

I'd have to dig into the code to confirm this suspicion though.

**Comment by kottenator** [comment]
Yes, it prompts to enter "pem" if it's not passed. But I want to automate it so prompt is not an option, I guess

**Comment by drawsmcgraw** [comment]
Oh. Well that's interesting. I wonder if something has to be done to the pki_auth module in order to expose those options...

**Comment by kottenator** [comment]
Another problem is: even if I pass the certificate contents into the prompt, it still doesn't work. The `pki.auth` function doesn't fire at all. 

I took a look into `salt` auth: it considers the first param as the username...

**Comment by kottenator** [comment]
Here is [my pull-request](https://github.com/saltstack/salt/pull/25197). You may take a look.
I haven't found a better way to make it work with CLI rather than to use `username` and `password` keywords
