### ISSUE TITLE
RabbitMQ Cluster/Plugins/Policy etc states do not track changes, preventing "watch" from working

### ISSUE THREAD

**Issue by kiall** [saltstack/salt#7811]
RabbitMQ Cluster/Plugins/Policy etc states do not track changes, preventing "watch" from working.

**Comment by rallytime** [comment]
- [ ] Plugin State: https://github.com/saltstack/salt/pull/28270
- [ ] User State: https://github.com/saltstack/salt/pull/28270
- [ ] Cluster State
- [ ] Policy State

**Comment by rallytime** [comment]
I've refactored each of the rabbitmq states mentioned in this issue to use test=true functionality correctly. Once PRs #30628 and #30631 are merged, that should finish up this ticket.
