### ISSUE TITLE
Sphinx domain to respect __func_alias and __virtual__ in docs

### ISSUE THREAD

**Issue by whiteinge** [saltstack/salt#7886]
Builds on pull req #7885.

We need an automated way of negotiating the difference between the name a module and it's functions are loaded as and how they are named in the code.

It may be time to bite the bullet and make a Salt-specific Sphinx domain.

``__func_alias`` support is straightforward. We can subclass the appropriate autodoc class then do the dictionary lookup and we're done.

I've been thinking on and off on how to approach the result of the ``__virtual__`` function. Doing this programmatically by actually executing the function may be tough to get right. I'm leaning toward a field list or some similar lookup table in a docstring in the ``__virtual__`` function itself. In any case, the end-goal is to be able not only to document the name a module is loaded under but also what conditionals affect that (third-party deps, platform, etc).

**Comment by jacobhammons** [comment]
I'm going to close this since this seems solved.
