### ISSUE TITLE
salt-ssh roster should default hostname to "ID"

### ISSUE THREAD

**Issue by pfalcon** [saltstack/salt#7909]
When user writes roster like this:

```
localhost:

ec2-ubuntu.amazon.com:
    user: ubuntu
```

, hopefully it's obvious what one means: there's a host with id "localhost", and same domain name; there's host with is "ec2-ubuntu.amazon.com" and same domain name, with specific connection user. Note that the above is a valid YAML. Currently, salt-ssh reacts weirdly to this:

```
Process Process-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/home/pfalcon/projects-3rdparty/salt/.venv/local/lib/python2.7/site-packages/salt/client/ssh/__init__.py", line 222, in handle_routine
    **target)
TypeError: __init__() takes at least 5 arguments (10 given)
```

DWIM! DWIM!

**Comment by mitar** [comment]
Has here been any change?

I would in fact prefer that I could configure the suffix to be added to the hostname. So that instead of:

```
foo:
  host: foo.example.com
  port: 22
  user: <username>
  sudo: True

bar:
  host: bar.example.com
  port: 22
  user: <username>
  sudo: True
```

I could write something like:

```
'foo,bar':
  host_suffix: example.com
  port: 22
  user: <username>
  sudo: True
```

**Comment by mitar** [comment]
Oh, I see that I can just use jinja:

```
{% for host in ['foo.example.com', 'bar.example.com'] %}
{{ host.split('.')[0] }}:
  host: {{ host }}
  port: 22
  user: <username>
  sudo: True
{% endfor %}
```

**Comment by basepi** [comment]
@saltstack/team-triage

**Comment by gtmanfred** [comment]
@saltstack/team-triage

**Comment by mitar** [comment]
Unstale.

**Comment by thatch45** [comment]
I am going to mark this as won't fix.
This issue is very old, and we have been working hard to migrate this stuff over to Heist, which does do this
