### ISSUE TITLE
pkg.installed should accept arbitrary parameters for underlying package manager

### ISSUE THREAD

**Issue by corywright** [saltstack/salt#7923]
Currently there is no way to pass arbitrary parameters from `pkg.installed` to the underlying package manager.  For example, in our environments we have certain packages that need to be installed with `--force-yes` passed to `apt-get`.

**Comment by corywright** [comment]
I still think this is a valid request and would be quite useful.

**Comment by terminalmage** [comment]
This has been implemented for years.

**Comment by terminalmage** [comment]
Actually, I misinterpreted this as "arbitrary arguments", as in function arguments, not CLI arguments.
