### ISSUE TITLE
Allow multiple same-command entries in cron

### ISSUE THREAD

**Issue by abcfy2** [saltstack/salt#7979]
I want my script exec twice at 5:30 and 18:00 every day.
In crontab, it like this:

---------
    30 5 * * * /usr/tomcat7/bin/restart.sh
    0 18 * * * /usr/tomcat7/bin/restart.sh

So I write these things in my sls:

    /usr/tomcat7/bin/restart.sh:
      cron.present:
        - minute: 30
        - hour: 5

    /usr/tomcat7/bin/restart.sh:
      cron.present:
        - minute: 0
        - hour: 18

When I exec ``salt '*' state.sls cron``, It doesn't works.

----------
    State: - cron
    Name:      /usr/tomcat7/bin/restart.sh
    Function:  present
        Result:    True
        Comment:   Cron /usr/tomcat7/bin/restart.sh already present
        Changes:  

In minion, crontab like this:

    # Lines below here are managed by Salt, do not edit
    30 5 * * * /usr/tomcat7/bin/restart.sh

Only one entry. What happend?
How can I add the same script in crontab twice at different times?

**Comment by dragon788** [comment]
This is probably fixed by the cron "identifier" option.
https://docs.saltstack.com/en/latest/ref/states/all/salt.states.cron.html

**Comment by basepi** [comment]
Good catch @dragon788!
