### ISSUE TITLE
salt MINION_ID saltutil.sync_all fails when /var/cache/salt/minion/proc/ is missing

### ISSUE THREAD

**Issue by johnnoone** [saltstack/salt#8013]
<code>salt MINION_ID saltutil.sync_all</code> fails when <code>/var/cache/salt/minion/proc/</code> does not exist into MINION.

But <code>salt-call saltutil.sync_all</code> works when it's executed on the minion side.

**Comment by arroyoc** [comment]
@johnnoone This ticket has been blocked waiting for your response.

**Comment by arroyoc** [comment]
@johnnoone Feel free to reopen this ticket it you ever get the chance to respond. In the meantime i'm closing this ticket.
