### ISSUE TITLE
virtualenv cannot use setuptools, it always uses distribute

### ISSUE THREAD

**Issue by mrtizmo** [saltstack/salt#8057]
When using the virtualenv state or module, it is not currently possible to create a virtualenv that does not contain distribute.

See discussion in groups: https://groups.google.com/d/msg/salt-users/3reWonnTSV0/o-1-P9VwFdkJ

**Comment by c4milo** [comment]
is there any update on this issue?

**Comment by basepi** [comment]
@c4milo Unfortunately, I don't think there is. We haven't had the bandwidth to address this ourselves, and I don't think any community members are looking at it currently.
