### ISSUE TITLE
Running Salt as an unpriviliege user fails in 0.17.1

### ISSUE THREAD

**Issue by PierreR** [saltstack/salt#8115]
The documentation advices us to run Salt with an unprivileged user.

"The only change needed is to alter the option
user in the master configuration file and all salt system components will be updated to function under the new user
when the master is started."

This seems to imply that I don't have to change the permission of "/etc/salt/master"

But on startup, I get  
```
"IOError: [Errno 13] Permission denied: '/etc/salt/master'"
```

I am under the impression that it had worked before though. I am using Halite and the error might come after the initialization of Halite as I had to struggle with changing certs permissions before getting this issue.

If you try this from a tag 0.17.1 also note there is a bug  that is now fixed in master:
https://github.com/saltstack/salt/commit/cea96b8f019120c14beae7ae7f88c40e47519d86

I don't know if a testcase had been added after/before fixing this bug. It surely proves there was none before.

Version information:
/etc/salt# salt --versions-report
           Salt: 0.17.1
         Python: 2.6.6 (r266:84292, Jul 10 2013, 22:48:45)
         Jinja2: 2.2.1
       M2Crypto: 0.21.1
 msgpack-python: 0.1.13
   msgpack-pure: Not Installed
       pycrypto: 2.0.1
         PyYAML: 3.10
          PyZMQ: 13.0.2
            ZMQ: 3.2.2

Related closed issue: https://github.com/saltstack/salt/pull/2308

**Comment by jacobhammons** [comment]
Appears this is resolved by #10150, closing.
