### ISSUE TITLE
Feature Request: More customizable scheduling

### ISSUE THREAD

**Issue by jalons** [saltstack/salt#8122]
Currently, saltstack schedules can be set to run on a period, but can not be defined to run at specific time frames.

For example, you can say run every five minutes or every 12 hours, but you can not specify to run at 6AM and 6PM (Specified via the minion's timezone, I would assume).

It might also be nice to be able to push adjustments to this time frame from the master.

I do not like the idea of running these scheduled tasks from cron or similar on the master, as then having to manage multiple cron jobs outside of salt introduces an external dependency, an extra item to modify, ensuring run execution vs completion gets interesting, etc, and scheduled tasks then have an external dependency on a single master (or the jobs must be scheduled on all masters in a multimaster setup).

**Comment by rallytime** [comment]
@jalons Significant work has been on on the salt scheduler thanks to the good work of @garethgreenaway. Have you been able to try out some of the new features implemented in the last year or so? I think many of you suggestions have been implemented.

@garethgreenaway - what do you think? Have most of the things discussed in this request been addressed?

**Comment by garethgreenaway** [comment]
@rallytime I believe all the requests are currently possible with the latest scheduling code.

**Comment by rallytime** [comment]
:+1:
