### ISSUE TITLE
CLI option to modify retcode based on highstate success/failure

### ISSUE THREAD

**Issue by basepi** [saltstack/salt#8180]
Doesn't seem to be an issue that directly addresses this, so I opened one.  I know that @thatch45 has stated previously that the return code of **`salt`** is defined by salt's success/failure, not the state(s) success/failure.  This is fine, but we should add an option which will change the retcode based on state(s) success/failure, for automation and scripting purposes.

**Comment by FunTimeCoding** [comment]
+1

**Comment by yagnik** [comment]
@basepi is someone working on this issue ? PR welcome ?

**Comment by basepi** [comment]
I actually think this may have been implemented. Are you still seeing retcodes of 0 when you have failures in your state runs?

**Comment by yagnik** [comment]
@basepi you are correct, highstate is working fine for me 👍

**Comment by basepi** [comment]
Perfect! Thanks for checking that.
