### ISSUE TITLE
salt-ssh and requiretty

### ISSUE THREAD

**Issue by mafalb** [saltstack/salt#8232]
On some machines I am getting an error

```
[root@master ~]# salt-ssh minion test.version
minion:
    ERROR: sudo is configured with requiretty
```

On the command line I can reproduce this behaviour, and fix it ;-)

```
[root@master ~]# ssh minion sudo echo "hu"
sudo: sorry, you must have a tty to run sudo
[root@master ~]# ssh -t minion sudo echo "hu"
hu
Connection to minion closed.
```

As a sidenote, when I connect the first time, then the error is different, maybe this could be consolidated

```
[root@master ~]# salt-ssh minion test.version
The authenticity of host 'minion (XXX)' can't be established.
RSA key fingerprint is XXX.
Are you sure you want to continue connecting (yes/no)? yes
minion:
    sudo: sorry, you must have a tty to run sudo
    sudo: sorry, you must have a tty to run sudo
```

**Comment by Xiol** [comment]
Hi,

Is there any workaround for this? We're starting to look at using Salt for some large-scale (~7000+ servers) stuff, but we'd want to use salt-ssh. The majority of the servers are CentOS/RHEL and we need to use sudo, so this is a bit of a dealbreaker. :/

Thanks

**Comment by basepi** [comment]
Yes, just stick `tty: True` into your roster under each minion which is configured with `requiretty`.

I had forgotten about this issue, it has actually been fixed for some time.
