### ISSUE TITLE
non optimal behaviour salt.modules.ssh.set_known_host

### ISSUE THREAD

**Issue by LeeBrown** [saltstack/salt#8240]
I have an issue with salt.modules.ssh.set_known_host.  If there is already an entry in the known_hosts file, but it is incorrect, it's flagged as 'exists' and not set.  In order to ensure the entry is always current, it would need to always be removed first, then always set.  This seems like it is going to generate a lot of unnecessary noise.

Could we either have an additional parameter update-if-incorrect, or change the behaviour so that the end result is that the host's entry is actually set.

To reproduce this problem:

saltmaster# cat ssh-user-keys.sls 
root_pub_keys:
  module.run:
    - name: ssh.set_known_host
    - user: root
    - hostname: 1.2.3.4

Execute this state once.  After, an attempt to ssh into 1.2.3.4 goes straight to login prompt.
Change the pub key on 1.2.3.4, then execute once more.  Now an attempt to ssh into 1.2.3.4 gives the fingerprint mismatch warning as the pubkey was not changed.

**Comment by cachedout** [comment]
Fixed by #19550
