### ISSUE TITLE
salt remote shell

### ISSUE THREAD

**Issue by veetow** [saltstack/salt#8249]
Hello,

I would personally find it extremely useful if salt provided a module for getting a remote command line shell  (bash/powershell/whatever) on a minion.  It should work something like this:

```
$ salt 'minion' shell.interactive user=root
[root@minion ~]#
```

The module should return an error if a glob or pattern is used which returns more than one minion, eg:

```
$ salt '*' shell.interactive user=root
Multiple minions matched the target. No command was sent, no jid was assigned.
```

Rationale:
Currently, my company uses HP Server Automation (formerly Opsware) which provides this feature via a command line tool called rosh.  rosh allows you to open an interactive shell via the opsware agent with its own permissions model and associated ACLs.

I am very much willing to hack at this if we can agree upon its usefulness, feasibility,  and functional requirements.

Thanks!

**Comment by passcod** [comment]
:+1:

**Comment by lichtamberg** [comment]
+1

**Comment by steverweber** [comment]
think the "reverse ssh tunnel" tunnel idea would be nice... perhaps make a module and salt-runner that automates most of the dirty work.

if we want something python based that perhaps could be wired over the salt communication pipes... should look at jupyter console code (linux/mac only).
https://github.com/jupyter/jupyter_console

**Comment by dtmateojr** [comment]
Hi there,

Reviving a zombie thread here...

I have coded something like a pseudo-interactive shell for saltstack. At the moment it simulates being in a real shell and does some very crude tab autocompletion and allows remote editing of files using vim. Hoping that someone would be interested in improving it. I am no programmer so please bear with me.

https://github.com/dtmateojr/shalt

**Comment by angeloudy** [comment]
An interactive shell would be very useful. In our environment, salt master manages some minions in different locations and there are firewalls between them. To run a command on the minion, I have to execute `salt 'minion_id' cmd.run 'something'`, which is not effective if I want to run a lot of commands.

**Comment by godlike64** [comment]
Are there any plans for this? Still interested in this. Sometimes after a power outage at home I can recover my systems if salt and internet are back up, but it's pretty crude and this would save a lot of trouble.

Is it feasible? Would @dtmateojr 's work be mergeable?

**Comment by dtmateojr** [comment]
@godlike64 It's ok if my code is not merged. It's just a single file anyway. Download the shalt script, put it in your salt master server and execute it directly. 

BTW, I have updated the README to show a sample session that demonstrates how I use this tool to manage hundreds of servers in our environment.

Cheers,

**Comment by nswalters** [comment]
👍

**Comment by waynegemmell** [comment]
I too would like this as currently I get the IP address from the grains and then ssh from another terminal. It's just a convenience thing for me but possibly useful for recovery.
