### ISSUE TITLE
`salt-ssh` prompts to overwrite (!) private keyfile passed via `--priv` 

### ISSUE THREAD

**Issue by pniederw** [saltstack/salt#8273]
As I had problems getting `salt-ssh` to work, I tried the `--priv` command line argument, in addition to the `priv:` roster setting. When I ran `salt-ssh` with `--priv ~/.ssh/id_rsa`, I got the following message (first line may be unrelated):

    [WARNING ] Warning:  sshpass is not present, so password-based authentication is not available.
    /Users/foo/.ssh/id_rsa already exists.
    Overwrite (y/n)?

I don't know what the purpose of `--priv` is, and how it relates to `priv:`. (`I wish salt-ssh` had more docs.) But I assume something is going wrong here. Mac OS 10.9, Salt 0.17.1

**Comment by cachedout** [comment]
I'm confident this got resolved a while back when we did a lot of work on salt-ssh and we just forgot to close this. ```--priv``` works correctly in my testing now.

**Comment by abcfy2** [comment]
Hi @cachedout

I find that `salt-ssh` does not [expand](https://docs.python.org/2/library/os.path.html#os.path.expanduser) the `~` directory, will also cause this issue.

```
 tree
.
├── config
│   ├── master
│   └── roster
├── install_salt-ssh.sh
├── pillar
├── salt
└── Saltfile

3 directories, 4 files
```

Here's `Saltfile`:
```
salt-ssh:
  config_dir: ./config
  ssh_max_procs: 30
  ssh_wipe: True
  ssh_log_file: ./logs/salt-ssh.log
  ssh_ignore_host_keys: True
  ssh_priv: ~/.ssh/id_rsa
```

```bash
$ salt-ssh '*' test.ping
/home/fengyu/.ssh/id_rsa already exists.
Overwrite (y/n)? n
ubuntu-trusty2:
    True
ubuntu-trusty3:
    True
ubuntu-trusty1:
    True
```

After do that, will be appeared `~` directory in current directory:
```
$ tree -L 3
.
├── ~
├── config
│   ├── master
│   └── roster
├── install_salt-ssh.sh
├── logs
│   └── salt-ssh.log
├── pillar
├── salt
├── Saltfile
└── var
    └── cache
        └── salt

8 directories, 5 files
```

**Comment by ypresto** [comment]
I had exactly same issue with above comment.
This issue might better to be reopened..?

**Comment by dvcrn** [comment]
Same issue here when using `~`
