### ISSUE TITLE
Add a file.serialize_pillar state

### ISSUE THREAD

**Issue by Lothiraldan** [saltstack/salt#8486]
As proposed by this comment: https://github.com/saltstack/salt/commit/48334025f25a1f8a46a246b59e77482531b2252c#commitcomment-3753937

It would helps if we could directly serialize pillar data to file.

The current solution is to use file.serialize with: 
  dataset: {{ pillar['my_pillar'] }}

But it means that pillar will be parsed, then state file will be rendered, then dataset will be parsed one more time for finally be serialized into a file.

Do you want I push a pull-request?

**Comment by The-Loeki** [comment]
https://docs.saltstack.com/en/develop/ref/states/all/salt.states.file.html#salt.states.file.serialize

Has that now w00tw00t

**Comment by The-Loeki** [comment]
@basepi this one can be closed :)

**Comment by rallytime** [comment]
Yeah good call, I'll close it as complete.
