### ISSUE TITLE
Active Directory Service Integration / Improvements

### ISSUE THREAD

**Issue by shantanub** [saltstack/salt#8521]
As requested by @basepi in https://github.com/saltstack/salt/issues/8119, I'm re-opening this issue as a feature request.

I am currently adding/updating/deleting entries from DNS and DHCP using netsh and dnscmd using the remote command execution framework and run states. The salt-minion executing these commands requires the minion service to be started as a privileged A/D user. 

Updates are complicated since netsh/dnscmd do not support "updates" directly, so I need to first determine if an update is required and then delete the current entry in DNS and DHCP before adding its replacement. This requires some set logic to compare the current state of all of my hosts/VMs with what's in DNS and DHCP. I will likely do this in memory from within python to start with (using dictionaries as hash tables perhaps) but will eventually move the set subtraction to redis probably.

It would be very helpful if we had functions in salt that provided add, delete and update/modify semantics for both DNS and DHCP in A/D.

Other A/D integration features like user management, user lookup (with member-of group lookups - including nested groups), etc.. would also be helpful but are secondary to anything I need at the moment.

**Comment by winston6071** [comment]
I know this is an old article but are there any updates how to solve this  ? 

i tried the following, calling a powershell script which does the appropriate stuff on the A/D controller but the problem i ran into is passing the arguments into the script 

i tried these 3 options but noone worked 
parameters are not passed into shell, the last option would be to call direct commandline tools dnscmd but this is not what i would like i would like to use powershell script and pass 4 arguments into it. 
----------------------
STATEFILE.sls
----------------------
```
dadi create DNS entry:
  cmd.script:
    - source: salt://files/internal_createdns.ps1
    - cwd: /temp/
    - shell: 'powershell'
    - args:
      - DNSNAME: "testserver24.mydomain.com"
      - HOST_IP: "192.168.1.100"
      - DNS_SUFFIX: "mydomain.com"
      - DNSSERVER: "192.168.1.1"
      - REVERSE_DNS_ZONE_1: "0.168.192.in-addr.arpa."

dadi create DNS entry1:
  cmd.script:
    - source: salt://files/internal_createdns.ps1
    - cwd: /temp/
    - shell: 'powershell'
    - args: 'testserver24 192.168.1.100 mydomain.com 192.168.1.1'

dadi create DNS entry2:
  - cmd.run:
    - name: 'dnscmd 192.168.1.1 /recordadd mydomain.com testserver24.mydomain.com. A 192.168.1.100'
```
------------------------------
POWERSHELL SCRIPT internal_createdns.ps1
------------------------------
```
# Load parameters if default values needed
param(
    $DNSNAME,
    $DNS_SUFFIX,
    $DNSSERVER,
    $HOST_IP
)
import-module DNSServer

# $last_ipadr_entry = $HOST_IP.split(".")[3] # check if this is needed without command line based dns management

$OldObj = Get-DnsServerResourceRecord -Name $DNSNAME -ZoneName $DNS_SUFFIX -RRType "A" -ComputerName $DNSSERVER -ErrorAction SilentlyContinue

If ($OldObj -eq $null) {
Add-DnsServerResourceRecord -Name $DNSNAME -ZoneName $DNS_SUFFIX -A -CreatePtr:$true -ComputerName $DNSSERVER -IPv4Address $HOST_IP
}
Else {
$NewObj = Get-DnsServerResourceRecord -Name $DNSNAME -ZoneName $DNS_SUFFIX -RRType "A" -ComputerName $DNSSERVER
$NewObj.RecordData.Ipv4Address = $HOST_IP
If ($NewObj -ne $OldObj) {
Set-DnsServerResourceRecord -NewInputObject $NewObj -OldInputObject $OldObj -ZoneName $DNS_SUFFIX -ComputerName $DNSSERVER
}
}
$OldObj = $null
$NewObj = $null
```

**Comment by winston6071** [comment]
ok found myself the solution was --> doubleqote not single quote single quotes would only be used if a argument would be separated by space 

- args: "testserver24 192.168.1.100 mydomain.com 192.168.1.1"
- args: "testserver24 192.168.1.100 mydomain.com 192.168.1.1 'two commandargument''

**Comment by basepi** [comment]
@winston6071 I'm glad you figured it out! Would you mind if I delete your first, longer post so that this issue is clearer?

**Comment by winston6071** [comment]
Sure no worries
Am 27.01.2016 22:20 schrieb Colton Myers <notifications@github.com>:@winston6071 I'm glad you figured it out! Would you mind if I delete your first, longer post so that this issue is clearer?

**Comment by mikeadamz** [comment]
Did this ever get done? definitely like to mange windows DNS from salt.

**Comment by rjrhaverkamp** [comment]
👍
