### ISSUE TITLE
enable salt to forward master authentication agent

### ISSUE THREAD

**Issue by mr-stateradio** [saltstack/salt#8625]
My first attempt to execute state git.latest failed because I wanted to fetch a private github repository, and github asked for the password. This can be easily circumvented by adding a ssh key to the user executing the git.latest call, and allowing this key to pull from github.

I did this with a not-password protected key, as I do not have the possibility to provide salt with the ssh key password. Using non password protected keys is a security vulnerability.

So it is recommendable that one uses a password protected ssh - key. As far as I know, it is currently not possible in salt to provide the ssh key password to the minion.

Therefore it would be great if one could pass by an ssh-agent from the master to the minion, in order one can use password protected ssh-keys. There is the option -A (authentication agent forwarding) in ssh by which this use case might be accomplished. 

See also my question on SOF: http://stackoverflow.com/questions/20000993/how-can-i-execute-the-salt-state-git-latest-with-password-protected-private-key

**Comment by pcn** [comment]
Using ssh agent forwarding would be nice.  If it's a worthwhile goal, maybe the path to the agent socket could be passed into the minion in some way that would find its way to the git states.

**Comment by dgorissen** [comment]
FWITW. In my case I only have a very small number of hosts to deal with so I live with using salt-call on the minion and typing the password. However, after cloning, I also need to do a git external which pulls in 20+ repositories, each needing the passphrase. As a workaround this works (after the git.latest) but I dont like it:

```
cmd.run:
    - name: |
        eval $(ssh-agent)
        ssh-add
        git external init
    - runas: oxbotica
    - cwd: /home/foo/bar/src
```

Slightly nicer would be to be able to run the cmd for ssh-agent once and have it active while you do other things but haven't figured out how to do that yet (if possible at all). I also feel that salt-ssh should help here but have not got it to work.

In any case, support within salt for this would be nice.

**Comment by kartiksubbarao** [comment]
I'm running masterless minions where I run `salt-call --local state.highstate` on each system, and would be very interested in this functionality with git.latest. Right now I'm doing something similar with the git credential cache daemon and using https URLs for the git repo, but there are some subtle issues with this approach that an ssh-agent-based approach could clean up. What I'd want to do is either specify the agent socket on the salt command line or have salt pick it up from an environment variable (e.g. SSH_AUTH_SOCK). And then have that transparently be used with any ssh commands that get invoked by salt.
