### ISSUE TITLE
salt-cloud only maps first ephemeral block device even if more are defined and available

### ISSUE THREAD

**Issue by sroegner** [saltstack/salt#8631]
As seen in a m1.large ec2 instance:

The profile defined

    block_device_mappings:
      - DeviceName: /dev/sdb
        VirtualName: ephemeral0
      - DeviceName: /dev/sdc
        VirtualName: ephemeral1

The instance ends up with

    # cat /etc/mtab
    /dev/xvda1 / ext4 rw,noatime 0 0
    proc /proc proc rw 0 0
    sysfs /sys sysfs rw 0 0
    devpts /dev/pts devpts rw,gid=5,mode=620 0 0
    tmpfs /dev/shm tmpfs rw 0 0
    none /proc/sys/fs/binfmt_misc binfmt_misc rw 0 0
    /dev/xvdb /media/ephemeral0 ext3 rw 0 0

But there is also

    # ls /dev/xvd?
    /dev/xvdb  /dev/xvdc

versions-report

    Salt: 0.17.1
    Python: 2.6.8 (unknown, Mar 14 2013, 09:31:22)
    Jinja2: 2.6
    M2Crypto: 0.20.2
    msgpack-python: 0.1.13
    msgpack-pure: Not Installed
    pycrypto: 2.6.1
    PyYAML: 3.10
    PyZMQ: 2.2.0.1
    ZMQ: 3.2.4

My salt-cloud version is 0.8.9 - but it is run off of a salt HEAD virtualenv so it is only a couple of days old.

**Comment by techhat** [comment]
Those of you that are experiencing this, we need more information, such as whether the aws driver is being used (I hope not) or the ec2 driver.

**Comment by tehmaspc** [comment]
we're no longer experiencing this issue; when we map 2 ephemeral drives we get 2 drives on the ec2 host. thanks.

**Comment by techhat** [comment]
Thanks @tehmaspc!
