### ISSUE TITLE
SaltCloud API erroneously returning success: True despite failure

### ISSUE THREAD

**Issue by SmithSamuelM** [saltstack/salt#8681]
Ret has success but it failed

```
2013-11-20_04:02:14.611817  salt/run/20131120040212486742/ret  runner.cloud.profile   
_stamp: 2013-11-20_04:02:14.611817
fun: runner.cloud.profile
jid: 20131120040212486742
ret: 
ioflominion_4: 
Error: ioflominion_4 already exists under ioflominion_4:techhat-rackspace
success: true
user: saltwui
```

Also see this for destroy operation if try to destroy vm that does not exist

**Comment by techhat** [comment]
It seems to me that from a stateful point of view, returning True is correct, since the profile was created (or deleted)  by the time it was requested to do so. Please reopen if necessary.
