### ISSUE TITLE
[salt.cloud] Add a search path for cloud.maps.d

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#8685]
We already have search paths for cloud.providers.d and cloud.profiles.d, so why not maps as well? Refs #8683.

**Comment by bradthurber** [comment]
@basepi I was just going to file a ticket for this very thing. It looks like it got lost. Can this be flagged for a future milestone?

**Comment by basepi** [comment]
@meggiebot ^

**Comment by cetanu** [comment]
I think this is already in salt
