### ISSUE TITLE
A Minion running on a Syndic blocks lower minions from responding

### ISSUE THREAD

**Issue by UtahDave** [saltstack/salt#8701]
I set up a scenario like the image below.

![syndicerror](https://f.cloud.github.com/assets/306240/1586571/8c2401ec-522a-11e3-98a8-69131c31a314.png)

Each salt-master has 2 minions below it with properly accepted keys. The syndics also have salt-minion installed and connected to the master directly above it.

When I run 'salt \* test.ping' from the master master I only get responses from its 2 minions directly below it and the minion running on the syndic below it. If I stop the minion service on the syndic, then the minions below the syndic respond to commands from the mastermaster.

**Comment by avb76** [comment]
So, I'm having the same problem when I try to use the run_job function ( http://docs.saltstack.com/en/latest/ref/clients/#salt.client.LocalClient.run_job ) from the python client API. The list of the minions that are expected to return does not contain the minions under the syndic master.

Any thoughts on what might be the problem? Thanks!

**Comment by basepi** [comment]
@avb76 What version of salt are you using, @avb76?

**Comment by basepi** [comment]
Also, what happens if you increase the value of `syndic_wait` on the upper level master?

**Comment by avb76** [comment]
I'm using salt 2015.5.0 (Lithium). And nothing happens if I increase the value of syndic_wait. The result is the same.

**Comment by basepi** [comment]
In that case, it appears this bug may still be present. We'll look into it.

**Comment by basepi** [comment]
@avb76 From all reports, this is fixed in recent versions of salt. When you say you are using 2015.5.0, do you mean on all your nodes or just your master?

**Comment by avb76** [comment]
@basepi I always keep the same version of Salt on all my nodes, so yes, I was using 2015.5.0 on all. In the mean time, I have updated to 2015.8.1, but I haven't tried to see if it works.

I'll get back to you with an answer tomorrow.

**Comment by basepi** [comment]
Thanks, we appreciate it. I'm mostly just surprised that it's fixed for everyone else but not you.... o_O

**Comment by avb76** [comment]
@basepi Well, I don't know, maybe I am doing something wrong. I tried again, this time in 2015.8.1. It appears that it doesn't work. I'll provide you with the example that I'm using. Tell me if I am doing something wrong, please.
```
[root@vm0 test]# salt '*' cmd.run 'salt-call --version'
vm2:
    salt-call 2015.8.1 (Beryllium)
vm0:
    salt-call 2015.8.1 (Beryllium)
vm3:
    salt-call 2015.8.1 (Beryllium)
vm1:
    salt-call 2015.8.1 (Beryllium)
vm4:
    salt-call 2015.8.1 (Beryllium)
vm5:
    salt-call 2015.8.1 (Beryllium)
```
Above, ```vm0``` is the upper level master. ```vm0, vm1, vm2, vm3``` are minions for ```vm0```.
```vm2``` is a syndic master and ```vm4``` and ```vm5``` are its minions.

This is the content of ```test_run_job.py```:
```
import salt.client
from pprint import pprint
local = salt.client.LocalClient()
job = local.run_job('*', 'test.sleep', [300])
pprint(job['minions'])
```

From what I read [here](https://docs.saltstack.com/en/latest/ref/clients/index.html#salt.client.LocalClient.run_job), ```job['minions']``` should contain a list with all the minions that are expected to return. But the output that is get is:
```
[root@vm0 test]# python test_run_job.py 
['vm0', 'vm1', 'vm2', 'vm3']
```

As you can see, ```vm4``` and ```vm5``` are not present in ```job['minions']```

Also, these machines are different from the ones that I've used in the first time.

Thanks!

**Comment by basepi** [comment]
That list of minions is the list that the master compiles when it runs the job. It can only compile the list for minions it directly knows about. It relies on the syndics to compile their own lists of "expected minions" and return them up the stream. But I am not sure that we update the minions list that we return for the job with those additional lists. It's possible this may be more of an API issue than a core issue. The lower-level minions are in fact returning when you run jobs, correct? It certainly appears so from your latest post, since they all run the cmd.run.

This original issue was about minions not returning at all in syndic setups.

**Comment by avb76** [comment]
Well, it looks like my problem is solved. I see that the returned data contains also the data returned by the minions unde the syndic. I don't remember this happening when I first noticed the issue and I was also confused by the fact that the expected minions list does not contain the minions under the syndic.

Thanks!

**Comment by avb76** [comment]
Actually, I'm very sure that the returned data did not contain the data from the minions under the syndic. I just tried the script that I had to do when I noticed the issue: it works just fine now, without any modifications.

**Comment by basepi** [comment]
Awesome! Glad it's resolved for you! I'm going to close this again, I think we're golden.

**Comment by avb76** [comment]
Thanks!
