### ISSUE TITLE
[salt.cloud] Need test cases for salt.cloud providers

### ISSUE THREAD

**Issue by techhat** [saltstack/salt#8754]
As noted in #8753, the API for Joyent has changed. We need to be able to catch these changes as they happen, to make sure any required updates make it into the next release.

I'm thinking we would want to have these tests check for the existence of a cloud.providers and cloud.profiles file, which would be documented but not present in the repository (can't be publishing that, you know).

**Comment by rallytime** [comment]
Providers with nightly tests:
- [x] Azure
- [x] Digital Ocean
- [x] EC2
- [x] Linode
- [ ] GCE
- [x] GoGrid (disabled - driver is broken, see #13365)
- [x] Joyent
- [x] Rackspace

**Comment by thedrow** [comment]
Related to #20239.
Well done on writing those tests. :+1:

**Comment by rallytime** [comment]
The GoGrid tests are now working on the 2015.8 and develop branches.
