### ISSUE TITLE
Extend troubleshooting docs for dealing with more issues on the master.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#8760]
Lately there have been a lot of issues with Master servers having errors, or not returning data because the jobs start. While the master conf documentation goes over this, I think the troubleshooting doc should cover this as well (honestly I think the troubleshooting doc should be broken up into master troubleshooting, and minion troubleshooting, but that can wait). If possible it should cover changing the timeout on the master, and modifying the worker threads, it should also suggest the use of batch mode in some circumstances.

**Comment by rallytime** [comment]
ping @jacobhammons
