### ISSUE TITLE
Traceback in case of prereq & require recursion

### ISSUE THREAD

**Issue by regilero** [saltstack/salt#8785]
This is closely related to #8210, but it's not the same case, here the recursion is between a `require` and a `prereq`. So not the same test case.

<pre>
A:
  cmd.run:
    - name: echo A
    - require_in:
      - cmd: B

# infinite recursion.....?
B:
  cmd.run:
    - name: echo B
    # will test A and be applied only if A changes,
    # and then will run before A
    - prereq:
        - cmd: A
</pre>

**Comment by JensRantil** [comment]
Related to #20143?
