### ISSUE TITLE
Write an arista "devops extension" module to manage arista switches

### ISSUE THREAD

**Issue by SEJeff** [saltstack/salt#8817]
http://www.lasthop-automation.com/blog/automation/ansible-arista.html

Arista [puppet integration](https://github.com/aristanetworks/puppet-eos)
Arista [ansible integration](https://github.com/aristanetworks/ansible-eos)
Arista [chef integration](https://github.com/aristanetworks/chef-eos)

CAN HAS salt-eos?

**Comment by briandowns** [comment]
@thatch45 Is the Arista module still in the works?

**Comment by jremond** [comment]
Any news on this ?
Thank you
