### ISSUE TITLE
ssh_known_hosts should add ip address as well

### ISSUE THREAD

**Issue by nvx** [saltstack/salt#8843]
Currently ssh_known_hosts only adds the hostname to the known_hosts file. If you then ssh to the server ssh will automatically add an ip address as well for the entry, but then this is unmanaged by salt.

A workaround would be to have two states, but this can make things harder to manage, especially if the ip changes and requires two lines in known_hosts.

sshd after accepting a key for a previously unknown host adds both the hostname and the ip in the following format:

```
git.example.com,192.168.0.1 ssh-rsa AAAAB....
```

Specifying 'git.example.com,192.168.0.1' causes the ssh_known_hosts state to continually re-add the line each time it is entered.

This behaviour could be controlled by a flag for cases where it is not desirable.

**Comment by babilen** [comment]
@garethgreenaway Did you implement that yourself in the ssh execution module? If so: Would you be interested in getting that merged in salt?

**Comment by garethgreenaway** [comment]
@babilen Let me look at what I ended up doing, almost 2 years later :)

**Comment by babilen** [comment]
@garethgreenaway It's just that I ran into this issue now and wouldn't want to duplicate your work. It should be possible to add different aliases as it is hard to predict which particular key a client will be offered.

**Comment by babilen** [comment]
pong
