### ISSUE TITLE
file.managed & file.blockreplace using file.accumulated do not support reload

### ISSUE THREAD

**Issue by kiorky** [saltstack/salt#8881]
See the commit sls, problem is that when we issue a reload in between a file.accumulated state & its file.managed or file.blockreplace counterpart, the file.accumulated data structure is blanked.

This is due to the reload mecanism which reloads all the modules, then resetting any module variable setted in specific modules.

We should then either document not to use dynamic global module variables like in file, dockerio at least, or instruct a way to persist data in them or just have another clever way or reloading module, either by pickling global vars or having only explicit reload not to have bad surprises.

**Comment by alangarf** [comment]
Any more word on this issue. This has been plaguing us for a while causing us to highstate twice to make sure all the accumulated pieces of the file are actually put into the file.

**Comment by basepi** [comment]
@alangarf Thanks for the bump. No new word on this one, we just have a lot of issues to catch up on.

**Comment by bclermont** [comment]
:+1:

this issue is so painful :|

**Comment by kiorky** [comment]
This may be fixed with recent @hvnsweeting stuff. (see related changesets)

**Comment by alangarf** [comment]
NICE! Was pretty much on the same path except for the awesome idea of the state object id for the accumulator filename. :+1:
