### ISSUE TITLE
Add ability to match "osmajorrelease[0]:6" syntax to salt.utils.subdict_match

### ISSUE THREAD

**Issue by nvx** [saltstack/salt#8906]
On RHEL, the os version can be accessed by the following two grains:

  osmajorrelease:
      6
      4
  osrelease: 6.4

In most instances (packaging etc) the only relevant part is the first component of the major release, ie RHEL 6.

Unfortunately this is difficult to target due to how grain matching works.

The initial thought would be to target with "osmajorrelease:6", unfortunately if you had hosts running version "5.6", they would also be targeted. This is easily tested in that above hosts also match for "osmajorrelease:4".

There are two ways to address this, one is by changing the grains so that "6" is in one grain, and "4" in another but the more general solution would be to edit the salt.utils.subdict_match function to allow matching on a specific entry in a list, not just the first member with something like:

"osmajorrelease[0]:6"

Thoughts?

**Comment by alexthegraham** [comment]
I have to agree with the OP, even though 'osfinger' does give a unique value based on the OS, the inconsistency of what is stored there makes it difficult to use and nearly impossible to use python functions StrictVersion and LooseVersion.

eg. 'CentOS-6' became 'CentOS Linux-7', and the SUSE variants are a mess.

'osmajorrelease' should only store a single value - the OS major release version. Even if there is some demand to get to the minor version, it shouldn't be stored in that grain, and certainly should be stored as the second item in a list.

**Comment by basepi** [comment]
I think I do agree with you. I'm not sure how both pieces of the version ended up in osmajorrelease. My only concern at this point is breaking people's setups if they're relying on both pieces of that grain. My gut says nobody is, but I don't know for sure.

**Comment by alexthegraham** [comment]
@basepi, I can see why you'd be concerned about breaking functionality for some edge case that someone might have built, but if they are querying the grain named 'osmajorrelease' to find minor release information, that's not really on you to account for – besides, that information is already in 'osrelease' and now 'osrelease_info' and 'lsb_distrib_release'.
IMO, consistency is most important.

**Comment by algorythmic** [comment]
This was fixed by d5629fa454219aec2529f79a4616869d6a72ebb2.
