### ISSUE TITLE
Case sensitivity of minion ids

### ISSUE THREAD

**Issue by nvx** [saltstack/salt#8965]
By default, the minion id is equal to the fqdn of the minion. The issue arises in that minion ids are case sensitive, while dns names are not case sensitive, although may contain case information. This can cause confusion.

One option to fix this would be to treat minion ids as case insensitive, but this has the potential to break existing deployments.

A safer option would be to normalise the default minion id to lowercase if a minion_id is not already present. This fix has the advantage that it will not change the behaviour of existing minions which will rely on the contents of the saved /etc/salt/minion_id file avoiding minion ids suddenly changing under people.

Of course in an ideal world everyone would already have lowercase fqdns on all hostnames and this would be a non-issue but alas...

**Comment by brad-alexander** [comment]
ran into this issue - bump

**Comment by joelbreton** [comment]
I just ran into this issue using salt-master 3001.1
