### ISSUE TITLE
tls.create_csr - support subject alternative names

### ISSUE THREAD

**Issue by drawsmcgraw** [saltstack/salt#8974]
I'd love to move away from my kludgy scripts for csr/cert creation/management. What would be awesome is if I could do this:

    salt master tls.create_csr my_ca CN=awesome.box.com SAN=sweet.website.com

I also just saw #5913. In light of that, is this something that's worth pursuing? Does the TLS module still have a future? 

If it's worth doing, I can look into making this happen.

**Comment by atbell** [comment]
Should be closed, SAN support has been in `tls` since 07fa4b343fc9dbe92c14a37974a1e3895ccccade.

**Comment by drawsmcgraw** [comment]
Sounds good to me. Thanks!
