### ISSUE TITLE
running syndic in root user, while a non-root user is configured in /etc/salt/master causes 'Authentication failure of type "user" occurred.'

### ISSUE THREAD

**Issue by hhkbp2** [saltstack/salt#9012]
Hi, while a non-root user is configured in /etc/salt/master, running syndic in root user would cause this problem: master would fail to execute the commands from syndic(which is from higher master) and log a message 'Authentication failure of type "user" occurred'.

In the source code, Syndic is implemented similarly as minion: in its start() method, check_user() is called before turn_in(). In Syndic's turn_in(), it will construct a LocalClient object, which will read the root key file in cache dir(/var/cache/salt/master/.root_key in default, which access mode is set to only readable to its owner user, root) to deliver those commands from higher master.

If a non-root user is configured in /etc/salt/master, then after check_user() does setuid() to this non-root user, LocalClient would fail to read the root key file due to 'Permission denied'.

Master didn't has this issue. It could be configured to run as non-root user and started as root user in command line.

**Comment by rallytime** [comment]
@hhkbp2 Are you still running into this one on newer versions of salt? I suspect this has been fixed. Current stable is 2015.5.3.

**Comment by hhkbp2** [comment]
@rallytime Sorry I have switched to another project and don't have the running enviroment of salt right now. You could check the latest source code to confirm whether the logic is correct and the issue is fixed.

**Comment by rallytime** [comment]
@hhkbp2 Oh, thanks for the pointer. Looks like this is still broken: https://github.com/saltstack/salt/blob/f77491a34dee23bba2d85f9ef74bc243a64f18d5/salt/cli/daemons.py#L502

**Comment by arthurlogilab** [comment]
not sure the +1 github votes are taken into account (are they ?) so I can say I am impacted by this bug too.
