### ISSUE TITLE
Feature request: blacklist/whitelist commands executed via cmd.run

### ISSUE THREAD

**Issue by rsuarezsoto** [saltstack/salt#9018]
Hi,

it would be great if salt could be configured to whitelist or blacklist certain commands to be executed via cmd.run. This way you could be sure that, for example, no one would execute by mistake (or on purpose!) something like "shutdown -r now", or "rm -rf /" in all your minions.

I've searched in the docs and asked in Salt-users, but it seems this is now not possible. Are there plans to implement something alike?

Thanks in advance.

**Comment by mostafahussein** [comment]
@basepi  when will we have the ability to define blackllisted/whitelisted commands for cmd.run ? i mean through states or execution module

**Comment by basepi** [comment]
Unfortunately right now our primary focus is on fixing bugs, so I don't have an ETA for this feature.

**Comment by mostafahussein** [comment]
@basepi I am trying to work on this feature, currently i modified the `run()` function, result as you see
it will check the command if its whitelisted on the minion configuration or not

![screenshot from 2015-11-09 08-07-37](https://cloud.githubusercontent.com/assets/4104127/11026984/61e50780-86b9-11e5-9452-60d8437dcebb.png)

**Comment by basepi** [comment]
@mostafahussein I think this would be a cool feature! What are you using for the minion opt for the whitelist? `cmd_run_whitelist` or something? We could also make it configurable via pillar/grains if we just use `config.get` to get the whitelist. It should also be off by default -- if the whitelist is empty or None, then it should allow all commands.

But yeah, I think you should probably submit a pull request!

**Comment by mostafahussein** [comment]
@basepi i am getting the whitelist by calling config.get then matching the command that passed through `cmd.run` state module if its not there it return false as the screenshot above. It it was just one command for a demo. I will continue on this feature with more cases as possible.

Should I leave it as a whitelist where you allow specific commands only. Or make it as a blacklist where you will be able to block specific commands ?

**Comment by rsuarezsoto** [comment]
Personally, I would love having both a blacklist and a whitelist. But if only one of them is possible, I'd prefer a whitelist.

**Comment by mostafahussein** [comment]
I maybe able to make both black and white lists but what if you have a
command* that doesn't belong to any of these lists ? Should I consider it
blacklisted by default unless you want to run this command* through
`cmd.run`

*Note: by command i mean the whole line that include the command options
and arguments as in `echo "foo"` or `rm -rf MyDir`

If you have anyother cases feel free to share it with us and i will try to
achieve what i could ^_^

**Comment by rsuarezsoto** [comment]
@mostafahussein yes, I'd consider everything blacklisted by default, unless explicitly added to the whitelist. Just make the whitelist optional for those who need to execute many different commands.

Thanks for your effort, by the way!

**Comment by damon-atkins** [comment]
Hi all Its a good idea to be able to restrict it.   I assume you mean if  you have white list, its the only commands you can run.   (some sort of pattern matching list).
If you have a blacklist you can run anything which does not match.   If both files existed, then you would need to match on the whitelist, and not match on the blacklist.

**Comment by lorengordon** [comment]
Is there a link to the code? I was wondering whether the whitelist (or blacklist) required an exact match, or if it was a list of regex patterns.

**Comment by mostafahussein** [comment]
Hello loren, unfortunately I haven't pushed the code to github yet, i will try to make it available as soon as possible.

and for your question yes currently it search for an exact match , i will try to make it support for regex patterns too so you can block a specific command without worring about the rest of the line , like if you want to block `rm` for example

**Comment by rsuarezsoto** [comment]
Hi,
has been there any work on this?

**Comment by greenmoss** [comment]
I would like to upvote this.
