### ISSUE TITLE
Extend Salt Windows Package Manager to Multiple Source Files

### ISSUE THREAD

**Issue by dimm037** [saltstack/salt#9028]
It would be nice to have the Salt Windows package manager support installers that are broken up into multiple files as in the case with disk spanning that is generally made up of a single .exe with multiple .bin files.

This would also be helpful in situations where the installer comes from a CD/DVD, e.g. Visual Studio, that is typically made up of one or more .exe or .msi and a number of .cab and configuration files.

It would be nice to do the following in a Windows package manager definition file:
* Specify a directory that contains all the installer components, where it would be copied to an appropriate location in the minion cache.
* Specify one or more installers (either .exe or .msi) along with arguments to invoke in a sequential order.
* Specify one or more un-installers (either .exe or .msi) along with arguments to invoke in a sequential order.

The installers and un-installers would be in a location relative to where it's copied to on the minion.

**Comment by lorengordon** [comment]
@eliasp Would you mind sharing your winrepo definition for the microsoft.office package so I can see how it plays together with the state file? I didn't see it in the salt-winrepo project... I'm guessing you reference the local cache path from the state file in the 'installer' property? Is there anything particularly special about the path you selected, or the directories in that path?

**Comment by eliasp** [comment]
@lorengordon As this is just a rather hackish workaround, I didn't want to add it to the salt-winrepo project as it requires manual intervention and can only be used through an SLS, but not through the usual `pkg.install` mechanisms.

In my win_repo I have:
**microsoft/office/init.sls:**
```salt
microsoft.office:
    15.0.4420.1017: # 2013
        installer: salt://win/repo/microsoft/office/2013/setup.exe
        full_name: Microsoft Office Professional Plus 2013
        reboot: False
        install_flags: ' /adminfile microsoft.office.2013.msp'
        msiexec: False
        uninstaller: salt://win/repo/microsoft/office/2013/setup.exe
        uninstall_flags: ' /uninstall'
```
I'm using the `/adminfile` param to pre-define some environment specific installation parameters (licensing) and to to enable the unattended mode of the installer.
The MSP was created using the [Microsoft Office Customization Tool](http://technet.microsoft.com/en-us/library/cc179097%28v=office.15%29.aspx), but there might be other approaches to run the installer in unattended mode too.

For dealing now with the fact, that Salt can't handle win_repo software yet which requires more than the file to which `installer` points, I'm using the following SLS in which `office_version` is set based on a grain:
**software/microsoft/office.sls:**
```salt
{% set office_version = grains['microsoft:office:version'] %}
office-installer-files:
    {% if 'microsoft.office' in salt['pkg.list_pkgs']() %}
        file.absent:
            - name: c:\salt\var\cache\salt\minion\files\base\win\repo\microsoft\office\{{ office_version }}
    {% else %}
        file.recurse:
            - name: c:\salt\var\cache\salt\minion\files\base\win\repo\microsoft\office\{{ office_version }}
            - source: salt://win/repo/microsoft/office/{{ office_version }}
    {% endif %}

microsoft.office:
    pkg:
        - installed
        - require:
            - file: office-installer-files
```
