### ISSUE TITLE
Pillar include loses list items

### ISSUE THREAD

**Issue by pniederw** [saltstack/salt#9033]
I have a pillar SLS which, among other things, defines the following:

```
roles:
  - build-server
  - salt-master
```

Another SLS then includes the former under a key named `host1`. Pillar `top.sls` applies the former SLS to the minion with id `host1.org`, and the second SLS to all minions. When I run `salt host1.org pillar.data`, I see that `roles` has both list items (as expected), but `host1.roles` only has a single item (`build-server`). This causes my state logic to fail on `highstate`.

Salt 0.17.2.2, Ubuntu 13.x

**Comment by keeth** [comment]
I think I just hit this bug too.. very odd.

**Comment by breskeby** [comment]
This issue makes our CI infrastructure completely unreliable since we can't ensure for 100% that the salt setup works when bringing in new machines.

**Comment by lhotari** [comment]
@basepi When are you going to look into this?

**Comment by lhotari** [comment]
It might be hard to reproduce the problem. 
In the most recent case the problem appeared when a file named `pillar/hosts/somehost.sls` gets included in 2 locations: in `pillar/top.sls` and in `pillar/hosts/init.sls` . In `pillar/top.sls`, the include is made only for the minion. For some strange reason this doesn't happen for all similar files.
When the problem appears, the key under `hosts` won't get included if the include is the first one in `pillar/hosts/init.sls`. If the include is made after some other include, the contents for the include will be the same as the previous include.

**Comment by basepi** [comment]
Thanks for the bump, I've updated the labels on this issue so we can hopefully get more eyes on it.
