### ISSUE TITLE
Nested Pillar includes don't seem to work

### ISSUE THREAD

**Issue by pniederw** [saltstack/salt#9036]
In an attempt to eliminate redundancies in my Pillar files, I've tried to use nested includes: SLS A includes SLS B, which in turn includes SLS C (along with some `defaults`). I can't get this to work though, getting strange rendering errors no matter what I try. Removing the nested level of includes solves the problem.

**Comment by jtand** [comment]
@pniederw Are you still seeing this behavior? If you are, would you be able to provide the information that @basepi asked for so we can look into this further? Thanks!
