### ISSUE TITLE
Add bash completion to the docs

### ISSUE THREAD

**Issue by olenz** [saltstack/salt#9051]
I noticed that there is a bash completion script in "pkg/salt.bash" since more than a year. This is highly useful, but not documented anywhere. I want to suggest to add this to the docs. Maybe I'm going to do this myself, but this is just a reminder.

**Comment by jacobhammons** [comment]
I've added this info at https://docs.saltstack.com/en/2015.5/ref/cli/index.html#cli-completion

@olenz if you think this is sufficient please close, thanks!

**Comment by olenz** [comment]
Thanks for doing this, and sorry for not doing this myself!
