### ISSUE TITLE
Windows Minions use too much CPU if master has rejected the salt-key

### ISSUE THREAD

**Issue by shealutton** [saltstack/salt#9052]
If you reject a Windows minion's key with salt-key, the minion will consume high % of cpu. It seems to be spinning on key checks. My workstation was using 50% on two cpus. 

Version 17.1.1. 

Very repeatable. Install minion on a windows system. Reject the key on the master. Observe the salt process on the windows minion.

**Comment by tjgruber** [comment]
This needs to be opened back up, as it is happening now with:

salt-minion (2018.3.3)
Windows 10 1809.

My CPU usage is nearly 51% + for Python.exe (salt-minion) on any PC who's denied/not accepted on the salt-master.

Background:
Multiple PCs, including my own, have been chewing high CPU resources constantly... fan spinning fast, degraded performance, etc. When I looked, it was python.exe (salt-minion) using over 51% of CPU and showing high power consumption.

Once I checked the salt-master, and removed the PCs via salt-key -d, then accepted them, it got better immediately.

In my case specifically, the computer was reloaded, so the old key was accepted, and the new but current key was denied. I removed both from salt-master, waited a second, then accepted the new current key.
