### ISSUE TITLE
document expectations for proper disclosure of security vulnerabilities

### ISSUE THREAD

**Issue by iluminite** [saltstack/salt#9073]
pretty self-explanatory.. there's been discussions on this topic on the mailing list, and clear words from Thomas about what ought to be done, but nothing (that I can find) in the docs. Please correct me if I'm wrong here and overlooked something obvious.

**Comment by jacobhammons** [comment]
Looks like this was added here: https://docs.saltstack.com/en/latest/security/index.html, I'm going to close this.
