### ISSUE TITLE
transparent and detailed documentation covering use of AES crypto, key exchanges, and other critical (but advanced) security topics

### ISSUE THREAD

**Issue by iluminite** [saltstack/salt#9074]
Right now we can refer to the code, but it isn't going to tell us why some decisions were made. It'd be best if there were a document available that made these details more clear to anyone interested in them. This is request for documentation is primarily in response to https://groups.google.com/forum/#!topic/salt-users/G8CyPTjKKxE and the lack of availability of this information (despite there being bonafide security audits and code reviews, which should produce similar documentation)

**Comment by felskrone** [comment]
There used to be a rather short documentation about this, but i think it has vanished from the docs over time. I cant seem to find it in the current docs. 

https://salt.readthedocs.org/en/v0.12.1/topics/specs/salt_auth_proto_abs.html
