### ISSUE TITLE
mtag do not work well

### ISSUE THREAD

**Issue by halfss** [saltstack/salt#9104]
salt/utils/event.py

        if self.sub in socks and socks[self.sub] == zmq.POLLIN:
            raw = self.sub.recv()
            if ord(raw[20]) >= 0x80:  # old style
                mtag = raw[0:20].rstrip('|')
                mdata = raw[20:]

use syndic
    salt '*' test.ping

    raw = '20131208202821379807��jid�20131208202821379807�returnâid�minion�_stamp�2013-12-08_20:28:22.217622
'
    mtag = '20131208202821379807'
    tag = '20131208202821379807'

it work well

but if use  "salt 'minion' test.ping"

    raw = 'new_job|||||||||||||��tgt_type�glob�jid�20131208202909426185�tgt�minion�_stamp�2013-12-08_20:29:09.426799�user�root�arg��fun�test.ping�minions�
' 
    mtag = 'new_job'
    tag = '20131208202909426185'

so here do not work well:
     if not (mtag.startswith(tag))

it means "salt 'minion' test.ping"  could not display the minion's return 

could we change 
       mtag = raw[0:20].rstrip('|')
to
       mtag = re.findall('\d+',raw)[0]

or there is a better to fixed this?

 thanks

**Comment by jfindlay** [comment]
@halfss, can this issue be closed?

**Comment by halfss** [comment]
Yes, you can close it right now.

Justin Findlay <notifications@github.com>于2015年7月29日周三 上午4:13写道：

**Comment by jfindlay** [comment]
Thanks, @halfss.
