### ISSUE TITLE
Salt-master Tracebacks don't end up in salt log

### ISSUE THREAD

**Issue by jacksontj** [saltstack/salt#9157]
If something in the main salt-master processes stack trace the traces don't end up in the logs. For example, i recently found a problem (https://github.com/saltstack/salt/pull/9156) which wasn't in the salt log.

**Comment by jfindlay** [comment]
@jacksontj, is this issue still relevant?

**Comment by jacksontj** [comment]
Don't think so-- at least with a couple minutes of trying I'm no longer able to repro this case ;)
