### ISSUE TITLE
Test for connectivity with minion and if a minion doesn't answer, i'd like to remove it from my keys

### ISSUE THREAD

**Issue by renoirb** [saltstack/salt#9187]
Use case:
  Depending on the quantity of machines you are managing, trying to find which are VMs that got deleted and clean up their keys can take some time.

Possible fix:
1. Add an option to test.ping
2. Document how to do if existing

**Comment by tjyang** [comment]
@renoirb,Can this issue be closed ? I tried out removekeys=True without issue.

**Comment by thatch45** [comment]
I also added the ability in Thorium to auto clean keys from disconnected minions:
https://docs.saltstack.com/en/develop/topics/thorium/index.html#writing-thorium-formulas

**Comment by tjyang** [comment]
@thatch45 , thanks for the Thorium info on this subject.

**Comment by renoirb** [comment]
I confirm! That's great! Thanks

(I've forgotten that this issue was still out there)
