### ISSUE TITLE
Update Reactor docs with an example using salt-cloud from the commandline.

### ISSUE THREAD

**Issue by gravyboat** [saltstack/salt#9319]
There's an example on the [here](http://docs.saltstack.com/topics/reactor/index.html#understanding-the-structure-of-reactor-formulas) that runs a salt command on the minion, but there's no example of running something else (salt-call --local, salt-key, salt-cloud, etc.). It would be nice if there was an example here where it showed how to do so in the event I wanted to delete a machine using the salt-cloud command or something along those lines. If it's not possible that should be noted.

**Comment by rallytime** [comment]
Fixed by #30215.
