### ISSUE TITLE
mine.send doesn't work as expected with positional arguments

### ISSUE THREAD

**Issue by terminalmage** [saltstack/salt#9323]
The issue is with `salt.utils.arg_lookup()`. It interprets positional arguments with default values as keyword arguments, resulting in the following return data when called against `network.ip_addrs`:

``` python
{
    'args': [],
    'kwargs': {
        'include_loopback': False,
        'interface': None,
        'cidr': None
    }
}
```

This means that when `mine.send` is invoked like so: `salt minion-id mine.send network.ip_addrs eth1`, then the `eth1` is ignored.

This can be worked around by passing the argument as a keyword argument, like this: `salt minion-id mine.send network.ip_addrs interface=eth1`, but this is not ideal, since configuring `mine_functions` for automated mine updates works with a list of positional arguments.

**Comment by jfindlay** [comment]
@terminalmage, is this still an issue?

**Comment by terminalmage** [comment]
No idea. Did you test?
