### ISSUE TITLE
State pkg.installed found in sls * is unavailable

### ISSUE THREAD

**Issue by tanyewei** [saltstack/salt#9331]
test.sls:

    sed:
      pkg.installed:
        - name: sed

run: salt 'minion1' state.sls test

    ----------
    State: - pkg
    Name:  sed
    Function:  installed
    Result:False
    Comment:   State pkg.installed found in sls vim is unavailable
    
    Changes:   
    
    Summary
    ------------
    Succeeded: 0
    Failed:1
    ------------
    Total: 1

change test.sls to :

    django:
      pip.installed:
        - name: django >= 1.6, <= 1.7

run: salt 'minion1' state.sls test

    ----------
    State: - pip
    Name:  django >= 1.6, <= 1.7
    Function:  installed
    Result:True
    Comment:   Package was successfully installed
    Changes:   Django==1.6.1: Installed
       
    
    Summary
    ------------
    Succeeded: 1
    Failed:0
    ------------
    Total: 1

minion logs:

    OrderedDict([('django', OrderedDict([('pip.installed', [OrderedDict([('name', 'django >= 1.6, <= 1.7')])])]))])
    
    OrderedDict([('sed', OrderedDict([('pkg.installed', [OrderedDict([('name', 'sed')])])]))])

master version:0.17.4 
minion version:0.17.4

**Comment by souadsadek** [comment]
Hi,
if u can help me i have the same error message when i update my os from suse11 to suse 12

please advice

**Comment by basepi** [comment]
Wow, this one's an old one. What version of salt are you running @souadsadek?

**Comment by souadsadek** [comment]
Hello Colton,

Thanks for ur reply :

L01SLS0001:/tmp/requests-2.5.1 # salt-call --versions-report
           Salt: 2014.7.1
         Python: 2.7.7 (default, Jun 23 2014, 13:38:05) [GCC]
         Jinja2: 2.7.3
       M2Crypto: 0.21.1
 msgpack-python: 0.4.2
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
        libnacl: Not Installed
         PyYAML: 3.11
          ioflo: Not Installed
          PyZMQ: 14.3.1
           RAET: Not Installed
            ZMQ: 4.0.5
           Mako: Not Installed

**Comment by souadsadek** [comment]
Hi

I think I understand what happened it was juste the Python path it was
wrong:-)
Many thanks


Envoyé de mon iPhone

Le Jan 28, 2015 à 18:25, Colton Myers <notifications@github.com> a écrit :

Wow, this one's an old one. What version of salt are you running @souadsadek
<https://github.com/souadsadek>?

—
Reply to this email directly or view it on GitHub
<https://github.com/saltstack/salt/issues/9331#issuecomment-71938724>.

**Comment by basepi** [comment]
Alright, glad you got it figured out!
