### ISSUE TITLE
pillar.get can't index into arrays

### ISSUE THREAD

**Issue by Whissi** [saltstack/salt#9354]
Hi,
1. Set the following pillar data for your test minion:

```
level0:
  - data: "level0"
  - level1:
    - data: "level1"
```
1. Refresh pillar data `salt 'test-minion' saltutil.refresh_pillar`
2. Verify your pillar data `salt 'test-minion' pillar.raw`:

```
test-mionion.example.org:
    ----------
    level0:
        ----------
        - data:
            level0
        ----------
        - level1:
            ----------
            - data:
                level1
```
1. Now try to access level1:

```
# salt 'test-minion' pillar.get level0:level1
test-minion.example.org:
```

```
# salt 'test-minion' pillar.get level0:0:level1
test-minion.example.org:
```

```
# salt 'test-minion' pillar.get level0:1:level1
test-minion.example.org:
```

```
# salt 'test-minion' pillar.get level0:2:level1
test-minion.example.org:
```

Tested with salt v0.17.4 on master and minion:

```
# salt --versions-report
           Salt: 0.17.4
         Python: 2.7.6 (default, Dec  2 2013, 13:35:18)
         Jinja2: 2.7.1
       M2Crypto: 0.21.1
 msgpack-python: 0.4.0
   msgpack-pure: Not Installed
       pycrypto: 2.6.1
         PyYAML: 3.10
          PyZMQ: 14.0.1
            ZMQ: 4.0.1
```

**Comment by mitar** [comment]
I think `pillar.get` supports this now, no?

**Comment by rallytime** [comment]
@mitar yes, thanks for pointing that out.

Here are the docs for this: https://docs.saltstack.com/en/latest/ref/modules/all/salt.modules.pillar.html#salt.modules.pillar.get

I'll close this as fixed.

**Comment by x70b1** [comment]
Is there a better explanation for this? I can't read anything about this behavior in the doc's. What have I overlooked?

**Comment by isaachui** [comment]
I know this issue is closed, but in case anyone is looking. If you want pillar data from the command line for an item in an array:
```yaml
my_pillar:
  - name: item0
     property: prop0
  - name: item1
     property: prop1
```

`salt-call pillar.get my_pillar:0` will return

```yaml
name:
    item0
property:
    prop0
```

`salt-call pillar.get my_pillar:1:name` will return
```yaml
name:
    item1
```
