### ISSUE TITLE
Packaging: bash autocomplete script not in RPMs

### ISSUE THREAD

**Issue by EugeneKay** [saltstack/salt#9387]
The bash autocompletion script(pkgs/salt.bash) is not included anywhere in the RPMs, likely not in the DEBs either. The (RHEL & kin, anyway) standardized place for this would be /etc/bash_completion.d/, regardless of whether the bash-completion package is installed.

CC: @gravyboat @terminalmage for attention

**Comment by chekolyn** [comment]
Mmm, are there any packages for RHEL/CentOS ? I can't seem to find them in the repos.

**Comment by gravyboat** [comment]
@chekolyn I don't believe so. @terminalmage the auto-completion stuff isn't being packaged up right? Should we revisit actually including this in the official packages? I'm not sure if it's too much to maintain...

**Comment by terminalmage** [comment]
The bash completion file will be in the 2015.5.3 packages, which I am in the process of building.

Thanks for the reminder @gravyboat, I'll close this.
