### ISSUE TITLE
RSA (and others) not properly guarded in `crypt.py`?

### ISSUE THREAD

**Issue by scoates** [saltstack/salt#9411]
The comment in the `except` block, here https://github.com/saltstack/salt/blob/develop/salt/crypt.py#L18 indicates that crypt is not needed in local mode, but there are other reasons that the import might fail.

RHEL seems to have a library linking problem, and complains with this:

    ImportError: /usr/lib64/python2.6/site-packages/M2Crypto/__m2crypto.so: undefined symbol: PEM_write_bio_SSL_SESSION

This makes the code try to do `RSA.gen_key(…)` on a failed `import` and missing `RSA`.

Seems guarding needs to be improved here.

(report via kcb on IRC)

**Comment by jfindlay** [comment]
@scoates, is this issue still relevant to recent releases?  Thanks.

**Comment by cachedout** [comment]
This is no longer relevant. Closing issue.
