### ISSUE TITLE
Cannot shutdown desktop Linux Mint system when salt-minion daemon is running.

### ISSUE THREAD

**Issue by nmbooker** [saltstack/salt#9421]
This occurs on Linux Mint 14 and 16 MATE edition.

If the salt-minion is running, and you're the only person logged in from the desktop, and you try to use the shutdown item from the desktop (Menu -> Shut Down then 'Restart' or 'Shut Down') the system will log out, but will refuse to shut down without an admin password, giving the following message:

"System policy prevents stopping the system when other users are logged in"

I've worked around this on my Mint 16 system:

1st: Stopping salt-minion with
```
$ sudo service salt-minion stop
```

2nd: editing /etc/init/salt-minion.conf and changing the following lines:

```
# invoke salt-minion via su so that /etc/environment is read
exec su -c salt-minion
```

to:

```
[ -f /etc/environment ] && . /etc/environment
exec salt-minion
```

3rd: Reboot

**Comment by jfindlay** [comment]
@nmbooker, is this issue still relevant?  Thanks.

**Comment by nmbooker** [comment]
@jfindlay Sorry for the delay replying.  No it's not relevant to me any more.
Thanks, Nick

**Comment by s0undt3ch** [comment]
Thank you for your reply @nmadhok. Closing.
