### ISSUE TITLE
Minion configuration as non-root user

### ISSUE THREAD

**Issue by sfvivek** [saltstack/salt#9436]
Hello:

first of all thanks for the great product.  

Here is out setup.  salt-master (lets say master.berkeley.com) is configured to run as root user.  one of the minions running on a different host (minion.berkeley.com) is configured to run as non-root user (unix account: vivek).  when we initiate commands to the minion from master - example (salt 'minion.berkeley.com' cmd.run 'ulimit -n') the output is different than what we get on running the same as "vivek" user on the minion.berkeley.com

output from when executed from the salt-master:
salt 'master.berkeley.com' cmd.run 'ulimit -n'
master.berkeley.com:
          1024

on the minion host as user vivek:
ulimit -n
65536

I believe what was happening is when we invoke from the salt-master, it's running su vivek -c 'ulimit -n' and returning the output to the master, where as it should run su - vivek -c 'ulimit -n' (note the - before vivek)

Is this an expected behavior with salt or a known issue that is planned to be fixed in the future releases?  Please let me know if you need any additional information about the issue.

**Comment by jfindlay** [comment]
@sfvivek, is this issue still relevant?  Thanks.

**Comment by clintberry** [comment]
This is still relevant to me. I am trying to execute a job for scale testing across 30 machines. The job opens 50k connections, but is stuck at 1024 because of this limitation. Is there a way around it? I updated the ulimits before restarting salt-minion, but no luck.

**Comment by CashIsClay** [comment]
+1 here. This actually isn't even limited to non-root users as the original subject suggests. If I set ulimits on the command line, in limits.d, etc, bounce salt minions... it's always 1024.

**Comment by sastorsl** [comment]
I just saw the same issue. My system on the minion: RHEL7, but it will apply to most.

You need to set the "nofiles" option i /etc/security/limit.d/* in my case:
# cat /etc/security/limits.d/30-nofile.conf
# Default limit for number of open files
*      hard    nofile     40960
*      soft    nofile      4096

To force this to be a default on login I had to add the following to PAM:

# grep limit /etc/pam.d/login
session     required      pam_limits.so

After I did this I logged in again in another shell, see 4096 with "ulimit -n" as my personal user. Sudo to root, and "ulimit -n" also reports 4096.
I then restarted the salt-minion and now the master get's 4096 as the response when running "salt 'target' cmd.run "ulimit -n"'

**Comment by sastorsl** [comment]
Sadly I was mistaken, and looked only at my test using "cmd.run 'su - <user> -c "ulimit -n"'

I would guess this is mainly an oS issue, barring that cmd.run is doing something funky / ignoring limits?

**Comment by sastorsl** [comment]
Is there any movement on this?

**Comment by jfindlay** [comment]
@sastorsl, not that I know of.  `cmd.run` does not invoke a login shell, but you should be able to override this with `salt minion cmd.run 'ulimit -n' shell='sh -i'`.

**Comment by sastorsl** [comment]
What puzzles me is that cmd.run does not seem to read even the limits of the salt-minion service when run with "salt-call"

    $ ps -ef | grep salt-minion
    root     17023     1  2 10:16 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
    root     17026 17023 10 10:16 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
    $ grep -i open /proc/17023/limits
    Max open files            1024                 4096                 files
    $ sudo salt-call -l error cmd.run 'ulimit -n'
    local:
        1024
    $ sudo mkdir /etc/systemd/system/salt-minion.service.d
    $ sudo sh -c 'echo -e "[Service]\nLimitNOFILE=8192" > /etc/systemd/system/salt-minion.service.d/nofile_limit.conf'
    $ cat /etc/systemd/system/salt-minion.service.d/nofile_limit.conf
    [Service]
    LimitNOFILE=8192
    $ sudo systemctl daemon-reload
    $ sudo systemctl restart salt-minion
    $ ps -ef | grep salt-minion
    root     17251     1  2 10:18 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
    root     17255 17251 11 10:18 ?        00:00:00 /usr/bin/python /usr/bin/salt-minion
    $ grep open /proc/17251/limits
    Max open files            8192                 8192                 files
    $ salt-call -l error cmd.run 'ulimit -n'
    local:
        1024

But with cmd.run from the master:

    $ sudo salt --out=txt -l error '<minion>' cmd.run 'ulimit -n'
    <minion>:8192

**Comment by amontalban** [comment]
I'm having this `ulimit -n` issue, here is a workaround I used:

```bash
#!/bin/bash

echo "Before"
ulimit -n
echo "Configuring"
ulimit -n 1048576
echo "After"
ulimit -n
```

```bash
root@salt:/# salt 'server' cmd.run '/root/test.sh'
server:
    Before
    1024
    Configuring
    After
    1048576
```

Hope it helps somebody and look forward for solution.

Thanks!

**Comment by pratik705** [comment]
I am configuring oracle12c. As prerequisite, I am set ulimit for oracle user with "/etc/security/limits.d/30-oracle.conf". But, it seems the values from the conf file are not reflecting and hence, the subsequent salt state fails. 

@amontalban I tried your workaround too. But, it do not work. As I am setting ulimit to "65536".

Can anyone recommend the steps to set ulimit for any user using salt state/execution module?
