### ISSUE TITLE
Update docs for ext_pillar with salt-call --local

### ISSUE THREAD

**Issue by iluminite** [saltstack/salt#9494]
``salt-call --local`` is an awesome way to use salt, it's also a great way to start out a generic bootstrap process - there are quite a few use cases for which ext_pillar should be available for salt-minion, but it's not currently available.

should salt-master be required just because you want to use ext_pillar with something like gpg, hiera, or reclass? is there a technical limitation, or would we just need to hook it up?

if anyone can point towards what would need to be done, I would be interested to know.

**Comment by jacobhammons** [comment]
note added here: https://docs.saltstack.com/en/latest/topics/tutorials/standalone_minion.html#external-pillars

Closing.
