### ISSUE TITLE
one of salt-master processes is defunct, why? How to prevent this?

### ISSUE THREAD

**Issue by Cofyc** [saltstack/salt#9576]
The output of ` ps aux | grep 'salt-master'`:
```
root     23622  0.0  0.0  48640  1540 ?        Ss   Jan05   0:00 su -c salt-master
root     23640  0.0  0.0 730324 48160 ?        Sl   Jan05   1:25 /usr/bin/python /usr/bin/salt-master
root     23677  1.2  0.0 268620 55136 ?        S    Jan05  28:48 /usr/bin/python /usr/bin/salt-master
root     23687  0.0  0.0 273340 26568 ?        Sl   Jan05   0:07 /usr/bin/python /usr/bin/salt-master
root     23688  0.0  0.0 271560 20136 ?        Sl   Jan05   0:21 /usr/bin/python /usr/bin/salt-master
root     23693  0.4  0.0 817516 45916 ?        Sl   Jan05  10:44 /usr/bin/python /usr/bin/salt-master
root     23694  0.4  0.0 816344 44624 ?        Sl   Jan05  10:44 /usr/bin/python /usr/bin/salt-master
root     23697  0.3  0.0      0     0 ?        Z    Jan05   8:00 [salt-master] <defunct>
root     23700  0.4  0.0 813308 40796 ?        Sl   Jan05  11:07 /usr/bin/python /usr/bin/salt-master
root     23703  0.4  0.0 846580 74776 ?        Sl   Jan05  10:36 /usr/bin/python /usr/bin/salt-master
root     23706  0.3  0.0      0     0 ?        Z    Jan05   8:48 [salt-master] <defunct>
root     23707  0.2  0.0      0     0 ?        Z    Jan05   5:03 [salt-master] <defunct>
root     23712  0.3  0.0      0     0 ?        Z    Jan05   8:47 [salt-master] <defunct>
root     23730  0.0  0.0  13932   920 pts/136  S+   13:39   0:00 grep --color=auto salt-master
```

The output of `salt-master --versions-report`:
```
           Salt: 0.17.4
         Python: 2.7.3 (default, Apr 10 2013, 06:20:15)
         Jinja2: 2.6
       M2Crypto: 0.21.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.4.1
         PyYAML: 3.10
          PyZMQ: 13.0.0
            ZMQ: 3.2.2
```

**Comment by WangWenchao** [comment]
any solutions?

**Comment by WangWenchao** [comment]
[root@puppet ~]# salt 'linux.autohome.com' test.ping
Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
[root@puppet ~]# salt 'linux.autohome.com' test.ping  --out=json --static --timeout=5
[ERROR   ] An un-handled exception was caught by salt's global exception handler:
SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Traceback (most recent call last):
  File "/usr/bin/salt", line 9, in <module>
    load_entry_point('salt==2015.8.0', 'console_scripts', 'salt')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 454, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 80, in run
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, quiet=True)
  File "/usr/lib/python2.7/site-packages/salt/cli/batch.py", line 34, in __init__
    self.minions, self.ping_gen = self.__gather_minions()
  File "/usr/lib/python2.7/site-packages/salt/cli/batch.py", line 56, in __gather_minions
    for ret in ping_gen:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 655, in cmd_iter
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 297, in run_job
    raise SaltClientError(general_exception)
SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.
Traceback (most recent call last):
  File "/usr/bin/salt", line 9, in <module>
    load_entry_point('salt==2015.8.0', 'console_scripts', 'salt')()
  File "/usr/lib/python2.7/site-packages/salt/scripts.py", line 454, in salt_main
    client.run()
  File "/usr/lib/python2.7/site-packages/salt/cli/salt.py", line 80, in run
    batch = salt.cli.batch.Batch(self.config, eauth=eauth, quiet=True)
  File "/usr/lib/python2.7/site-packages/salt/cli/batch.py", line 34, in __init__
    self.minions, self.ping_gen = self.__gather_minions()
  File "/usr/lib/python2.7/site-packages/salt/cli/batch.py", line 56, in __gather_minions
    for ret in ping_gen:
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 655, in cmd_iter
    **kwargs)
  File "/usr/lib/python2.7/site-packages/salt/client/__init__.py", line 297, in run_job
    raise SaltClientError(general_exception)
salt.exceptions.SaltClientError: Salt request timed out. The master is not responding. If this error persists after verifying the master is up, worker_threads may need to be increased.

**Comment by cachedout** [comment]
I'm very confident that we have solved this issue with the process management code in 2015.5 and above. I haven't seen nor heard of an issue like this since then.
