### ISSUE TITLE
Clarify salt-formula docs

### ISSUE THREAD

**Issue by timoguin** [saltstack/salt#9608]
Per this discussion on the mailing list: https://groups.google.com/forum/#!topic/salt-users/zx1VHnGx2lI

Need the following:

* Tutorial showing how to use formulas as drop ins with gitfs_remotes
* Link to this tutorial in all the formulas READMEs

**Comment by bechtoldt** [comment]
@timoguin do you think this issue have been fixed by the existence of http://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#writing-formulas?

**Comment by jacobhammons** [comment]
I confirmed that these docs are available here: https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html#adding-a-formula-as-a-gitfs-remote

Closing this one.
