### ISSUE TITLE
Add __sls__ to the state output

### ISSUE THREAD

**Issue by alangarf** [saltstack/salt#9628]
Hey all,

Using `saltstack-formulas/openstack-standalone-formula` I've found a weird bug in service.running (or the highstate rendering) in 0.17.4 on Ubuntu 13.10.

Apart from the openstack formula not working at all on 13.10, in the process of building a pull-request to fix it's issues I discovered that the mysqld service requirement for keystone uses the id `mysqld` rather than the service name `mysql` from the included mysql.server sls file.

This occurs when I run the base openstack sls like:
`salt-call state.sls openstack`

Yet the failing keystone state will work if I target it like:
`salt-call state.sls openstack.keystone`

The relevant highstate data is identical in both calls but one uses the correct service name and the other doesn't....

```
    keystone-db-init:
        ----------
        __env__:
            base
        __sls__:
            openstack.keystone
        cmd:
            - run
            ----------
            - name:
                openstack-db --init --service keystone --rootpw ''
            ----------
            - unless:
                echo '' | mysql keystone
            ----------
            - require:
                ----------
                - pkg:
                    openstack-keystone
                ----------
                - service:
                    mysqld
            ----------
            - order:
                10005
```

[SNIP]

```
    mysqld:
        ----------
        __env__:
            base
        __sls__:
            mysql.server
        pkg:
            - installed
            ----------
            - name:
                mysql-server
            ----------
            - order:
                10000
        service:
            - running
            ----------
            - name:
                mysql
            ----------
            - enable:
                True
            ----------
            - watch:
                ----------
                - pkg:
                    mysqld
            ----------
            - order:
                10001
```

Any ideas?

**Comment by iggy** [comment]
__sls__ is in show_(sls|highstate) output. Wonder if that's sufficient because as basepi mentioned, another line in normal highstate output can add up for some people.
