### ISSUE TITLE
Create release announcement RSS feed and/or mailing list

### ISSUE THREAD

**Issue by gldnspud** [saltstack/salt#9638]
These types of feeds/lists are helpful for tracking updates in a timely manner.

**Comment by daodennis** [comment]
Looks like we can close this per this announcement of salt-announce@: https://groups.google.com/forum/#!topic/salt-users/mrjYhSKYhBw.

**Comment by rallytime** [comment]
Good call @daodennis!

**Comment by rallytime** [comment]
Good call @daodennis!
