### ISSUE TITLE
Need a way to silently uninstall the windows minion

### ISSUE THREAD

**Issue by Tim-Co** [saltstack/salt#9751]
A way to silently uninstall the windows minion client would be great. Currrently /S does a great job of installing silently but does not work for c:\salt\uninst.exe.

**Comment by twangboy** [comment]
Apparently /S works (note, it's a capital S)

**Comment by twangboy** [comment]
Since 2014.7.3

**Comment by lorengordon** [comment]
Fantastic, will test this tomorrow!

**Comment by lorengordon** [comment]
Works like a charm, `c:\salt\uninst.exe /S`. I tested using v2015.5.0.
