### ISSUE TITLE
RFC: Returners that actually return to the master

### ISSUE THREAD

**Issue by kaithar** [saltstack/salt#9844]
I've been toying with this idea for a while but I'm not sure how best to accomplish it.

At the moment, I can only see ways to get the returners run on the minions regardless of where the instruction was issued from.  This has many problems, including:
- the need to expose connection details for reporting services to all minions
- having to deal with services that normally like to transmit in clear
- negotiating firewalls and NAT on both ends
- needing the minion to have the libraries needed to talk to the reporting service

If you're controlling a location diverse network and want to report data to a mysql or redis instance, you've basically got to either trust those minions with access and secure the connection ... or you've got to write a gateway service that mediates access and performs some kind of authentication.

Since a large part of the point of Salt's communications system is to mediate access, authenticate sources and provide secure transmission across potentially hostile networks, it seems horribly wrong that it doesn't support master side returners.

Have I missed some sort of official way for getting return behaviour on the master?
Is this an extension of Salt that others would want to see?
What might be a good way to implement it?

Lacking this is actually causing me issues in my roll out plan, I'd rather have a clean solution instead of hacking around it by quickly and repeatedly polling salt's job states.
I am, as usual, willing to put my coding where my mouth is on the issue and work on a PR... but in this instance I feel some discussion on mechanics before would be sensible.

Thoughts?

**Comment by whiteinge** [comment]
This was added in 2014.7 as the [master_job_cache](http://docs.saltstack.com/en/latest/topics/jobs/job_cache.html#master-job-cache) setting.

**Comment by anlutro** [comment]
I use event returners to run a returner on the master, which seems to work fine.

My main issue is that the naming of these configurations are not intuitive, and documentation is sparse on the subject.
