### ISSUE TITLE
Add logging information about git executions

### ISSUE THREAD

**Issue by ruimarinho** [saltstack/salt#9931]
When using the gitfs, it is extremely hard to debug what's going on with the git repositories, since the information is not being captured from gitpython. I assume this is also the case with other git adapters supported by salt.

With tracing enabled, I've managed to find out what gitpython is doing, but I think this should be logged by the salt-master when ran in debug mode. This is a sample output of a salt-master in debug mode with gitpython tracing enabled:

```
[DEBUG   ] Updating fileserver for git_pillar module
git fetch -> 0
git checkout origin/staging -> 0; stdout: ''; stderr: 'HEAD is now at 1234abc... Added xyz'
```

As you can see, the lack of additional information can make it quite hard to detect changes in the repositories.

**Comment by andrejohansson** [comment]
@ruimarinho what did you do to enable the tracing? I'm trying to figure out why my master refuses to update the fileserver. I get no errors, I've cleared the cache dir and rebooted the server, I've tried to clone as the user salt runs, then I get my full repo. But in the cache...the saltmaster will stubbornly "fetch" an old revision and I cannot figure out why.

**Comment by ruimarinho** [comment]
@andrejohansson probably something like `-l trace`, but I don't remember very well now :)

**Comment by andrejohansson** [comment]
@ruimarinho  ah, you mean you enabled the trace on the salt-master? not some trace flag for the gitpython library?

**Comment by ruimarinho** [comment]
Ah, I remember now! Yes, it was with the `GIT_PYTHON_TRACE` env var.

**Comment by andrejohansson** [comment]
Thank you!
