### ISSUE TITLE
python-api breaks when passing minions as list

### ISSUE THREAD

**Issue by felskrone** [saltstack/salt#9963]
Im trying to pass lists of minions into the salt-client-api like so:

```
01 import salt.client
02 local = salt.client.LocalClient()
03 
04 exec_func = local.cmd_iter_no_block(['server01.mydomain.de'],
05                                                             'test.ping',
06                                                             [],
07                                                             expr_form='list',
08                                                             verbose=True)
09 for i in exec_func:        
10     print str(i)
```

This works fine, if server01 is currently connected to the master:

```
{'server01.mydomain.de': {'ret': True}}
```

If the minion is not connected, the salt-master publishes the job, does not get a reply and tries to lookup the state of the job using saltutil.lookup_job.

When trying to publish 'lookup_job', no matching minion is found and the a message is printed:

"No minions matched the target. No command was sent, no jid was assigned."

It seems like the targetting information gets lost when passing lists into the client-api.

This only happens when going through the client-api. When using the salt-binary, it works fine.

```
01 $ salt -L server01.mydomain.de test.ping -v
02 Executing job with jid 20140127114911336536
03 -------------------------------------------
04
05 server01.mydomain.de:
06    Minion did not return
```

The masters versions are:

```
salt01:~/tests $ salt * --versions-report
           Salt: 0.17.0-6003-g9dd1f8a
         Python: 2.6.6 (r266:84292, Dec 26 2010, 22:31:48)
         Jinja2: 2.5.5
       M2Crypto: 0.20.1
 msgpack-python: 0.1.10
   msgpack-pure: Not Installed
       pycrypto: 2.1.0
         PyYAML: 3.09
          PyZMQ: 13.1.0
            ZMQ: 3.2.3
```

**Comment by cachedout** [comment]
I tested this against recent code and it's working correctly. The iterator returns `None` until the timeout expires, which is what I would expect. I'm going to go ahead and close this. :]
