### ISSUE TITLE
Automate Doc Translation Process

### ISSUE THREAD

**Issue by s0undt3ch** [saltstack/salt#9996]
Currently, we need to manually run a command to upload the documentation to [transifiex](https://www.transifex.com/organization/saltstack/dashboard/salt).

We need to automate this process to allow the translators to always have the latest version available

**Comment by rominf** [comment]
I think that even partially  translated documentation should be automatically published. That would stimulate translators.

**Comment by whiteinge** [comment]
Agreed. This is needed.

I know Transifiex has support for getting updated when we make doc updates. Do they have something going the other direction? Can Transfix call an external webhook?

**Comment by s0undt3ch** [comment]
I think we still need to push the updated documentation. We had a Jenkins job taking care of this on the old Jenkins Dev server which was taken down. We just need to recreate the job on the future Jenkins server.

**Comment by whiteinge** [comment]
What about going the other way? When a new translation is added can
Transifex notify salt-api via webhook?

**Comment by s0undt3ch** [comment]
To build the translated doc?

Will need to investigate that...

**Comment by s0undt3ch** [comment]
Though, a build per translated string?

**Comment by whiteinge** [comment]
You're right, might be overkill. If there's no way to group related translations then we could just build on a timer instead a few times a day.
